---
title: 'Start Here | About'
date: '2021-06-11T21:12:00.0010000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Eleutheria  | Freedom Theology'
blogger_status: 'DRAFT'
blogger_page_id: '6122205179953342532'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Eleutheria  _ Freedom Theology /feed.atom'
---

<p style="text-align: left;">This blog provides biblical studies and theological articles designed to help you find freedom from bad theology, hurts, hang ups, habits, and bad definitions so you can... *under construction*</p><p style="text-align: left;"></p><ul style="text-align: left;"><li>Subscribe now to get articles in your inbox.</li><li>Search for articles.</li><li>Resources page has links to books, videos podcasts, and other study helps from scholars around the web.&nbsp;</li></ul><p></p><p style="text-align: left;"><br /></p><h4 style="text-align: left;">Eleutheria is a Greek word that means “Freedom”, as seen in Galatians 5:1</h4><blockquote><i>For freedom Christ has set us free. Stand firm, then, and do not be subject again to the yoke of slavery.&nbsp;Galatians 5; <a href="http://netbible.org/bible/Galatians+5" target="_blank">NET Bible</a><br /><br />tn Translating the dative as “For freedom” shows the purpose for Christ setting us free; however, it is also possible to take the phrase in the sense of means or instrument (“with [or by] freedom”), referring to the freedom mentioned in 4:31 and implied throughout the letter. “Therefore, brothers and sisters, we are not children of the slave woman but of the free woman.” Gal 4:31 (NET)<br /><br /></i><div><i>sn Here the yoke figuratively represents the burdensome nature of slavery.</i></div></blockquote><div><br /></div><div><h4 style="text-align: left;">Why Freedom?</h4><br />Throughout my personal journey, the word “Freedom” has been a recurring theme.&nbsp;</div><div><br /></div><div>I’ve sought freedom from hurts, hang ups, habits, and ill defined holiness. To a large extent, I am walking in a measure of freedom today. Each day, I find a new layer to peel back, and a new measure of freedom in my relationship with Jesus, with The Father, with The Spirit, and with my fellow human beings.</div><div><br /></div><div>I’ve found that in each case, my theological worldview was a key factor in my freedom journey. As I relinquish another layer of bad theological tradition and replace it with a die-hard devotion to the text at it is and not as I would have it be, freedom is the result. In very practical ways, as I know the truth, it makes me free.&nbsp;<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p></div>