---
title: 'Resources'
date: '2019-11-29T11:04:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Grief Sucks'
blogger_status: 'LIVE'
blogger_page_id: '9040042390790345961'
blogger_filename: '/p/resources.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Grief Sucks/feed.atom'
---

<br />
<h3>
The following is a curated list of the best resources we've found for dealing with Grief, including support groups and assistance.&nbsp;</h3>
<br />
<h4>
</h4>
<h4>
</h4>
<h4>
Books on Grief</h4>
<div>
<br /></div>
The following are books we've either read and been helped by or we've seen impacted another widow's life positively.<br />
<br />
<ul>
<li><a href="https://www.amazon.com/Where-When-Hurts-Philip-Yancey/dp/0310245729/ref=sr_1_1?crid=1TQZCATG7PFJ1&amp;keywords=where+is+god+when+it+hurts+philip+yancey&amp;qid=1564301277&amp;s=gateway&amp;sprefix=where+is+god+when%2Caps%2C348&amp;sr=8-1" target="_blank">Where Is God When It Hurts?</a> by Philip Yancey&nbsp; (Author) (affiliate link)</li>
</ul>
<ul>
<li><a href="https://www.amazon.com/Emotionally-Healthy-Spirituality-Impossible-Spiritually/dp/0310348498/ref=sr_1_1?crid=2OBNEXYM6MRP6&amp;keywords=emotionally+healthy+spirituality+by+peter+scazzero&amp;qid=1564301344&amp;s=gateway&amp;sprefix=emotionally+hea%2Caps%2C292&amp;sr=8-1" target="_blank">Emotionally Healthy Spirituality..</a> by Peter Scazzero&nbsp; (Author) (affiliate link)</li>
</ul>
<ul>
<li><a href="https://www.amazon.com/Grief-Recovery-Handbook-Anniversary-Expanded/dp/0061686077/ref=sr_1_5?keywords=grief&amp;qid=1564301399&amp;s=gateway&amp;sr=8-5" target="_blank">The Grief Recovery Handbook</a>, 20th Anniversary Expanded Edition: The Action Program for Moving Beyond Death, Divorce, and Other Losses including Health, Career, and Faith by John W. James&nbsp; (Author), Russell Friedman&nbsp; (Contributor) (affiliate link)</li>
</ul>
<ul>
<li><a href="https://www.amazon.com/Grief-Observed-C-S-Lewis/dp/0060652381/ref=sr_1_8?keywords=grief&amp;qid=1564301525&amp;s=gateway&amp;sr=8-8" target="_blank">A Grief Observed</a> by C. S. Lewis&nbsp; (Author) (affiliate link)</li>
</ul>
<br />
<br />
<h4>
Facebook Groups</h4>
<div>
<br /></div>
There are a host of private Facebook Groups available for Widows/Widowers. You don't have to have been "officially married" to qualify. Most do require that you provide some details about the Date of Loss and a link to an article or obituary or some proof. This can hurt to be asked for "proof" but it's important. These questions are designed to protect you from people looking to prey on grieving people when they are at their most vulnerable. If you are ever approached by anyone in the groups and you don't believe they have good intentions, report these to the admins immediately. They will not tolerate anyone causing you more harm.<br />
<br />
These are the ones we found most helpful through our own experiences:<br />
<ul>
<li><a href="https://www.facebook.com/groups/YoungWidowsAndWidowersSupportGroup/?ref=group_header">Young Widows &amp; Widowers Support Group</a></li>
</ul>
<ul>
<li><a href="https://www.facebook.com/groups/541453565943856/?ref=group_header">* Late Night Widows &amp; Widowers * © LNWW</a></li>
</ul>
<ul>
<li><a href="https://www.facebook.com/groups/666388506732591/?ref=group_header">LNWW Forever Young Widows and Widowers 20s 30s 40s ©</a></li>
</ul>
<ul>
<li><a href="https://www.facebook.com/groups/910136392459408/?ref=group_header">Widows and Widowers : Dating After Loss</a></li>
</ul>
<ul>
<li><a href="https://www.facebook.com/groups/331084304231803/?ref=br_rs">widowed 4 widowed</a></li>
</ul>
<div>
<br /></div>
<h4>
IRL (In Real Life) Support&nbsp;</h4>
<div>
<br /></div>
<div>
Hospice provides free grief counseling, even if your loved one did not pass away using their services. The main website has a list of resources and their local offices can provide you with more information.</div>
<br />
<ul>
<li><a href="https://hospicefoundation.org/Grief-(1)/Support-Groups">Hopsice Foundation of America</a></li>
<ul>
<li><a href="https://www.hospiceofnorthidaho.org/grief-and-loss/">Grief &amp; Loss - Hospice of North Idaho</a></li>
<li><a href="https://www.hospiceofspokane.org/grief-support/">Grief Support – Hospice of Spokane</a></li>
</ul>
</ul>
<div>
<br /></div>
<div>
<br /></div>
<h4>
<b>Articles we've written just for you:</b></h4>
<h4>
<div style="font-weight: 400;">
<br /></div>
<div style="font-weight: 400;">
We hope that some of these provide you hope for the future, understanding for the present and maybe a smile when you thought you didn't have any left.</div>
<div style="font-weight: 400;">
<br /></div>
<div style="font-weight: 400;">
<br /></div>
<ul style="font-weight: 400;">
<li><a href="https://widowgriefsucks.blogspot.com/2019/06/the-five-stages-of-grief.html" target="_blank">The Five Stages of Grief for Widows</a></li>
</ul>
<ul style="font-weight: 400;">
<li><a href="https://widowgriefsucks.blogspot.com/2019/06/12-dumb-things-people-say-to-widowers.html" target="_blank">12 Dumb Things People Say To Widow(er)s and what you can try instead.</a></li>
</ul>
<ul style="font-weight: 400;">
<li><a href="https://widowgriefsucks.blogspot.com/2019/06/6-ways-to-support-your-widowed.html" target="_blank">6 Ways to Support Your Widowed Girlfriend or Boyfriend</a></li>
</ul>
</h4>
<div>
<ul>
</ul>
</div>
<div>
<br />
<br /></div>
<div>
Thank you for checking out our resources page. If you have any questions, you may contact us by commenting on this page.<br /><br />
<div>
A note about Affiliates. Periodically, we may recommend a book, product, service, or website. Some of these may pay us a small compensation for the sale. Rest assured, we only recommend things we believe will provide lasting value to you, many of them have impacted us first.<br />
<br />
For disclosures, see the bottom of <a href="https://widowgriefsucks.blogspot.com/p/start-here_29.html" target="_blank">Start Here!</a><br />
<div>
<br /></div>
</div>
</div>
<div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div>
