---
title: 'About Us'
date: '2019-11-29T20:04:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Grief Sucks'
blogger_status: 'LIVE'
blogger_page_id: '7973174020547646694'
blogger_filename: '/p/about-us.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Grief Sucks/feed.atom'
---

So who are "we" and why are we writing this? Well, we are a team of Widows/Widowers that have gone through the hard experience of losing a Spouse/Significant Other. We know in depth the pain and hardship that accompanies this experience.<br />
<br />
We are here to educate non-widows so they can be better equipped to deal with their grieving friends/family.<br />
<br />
We are here to come alongside Widows/Widowers and say "You Are Not Alone!" even though we know it feels like you are.<br />
<br />
Here's who we are:<br />
<br />
<h4>
Adrianne Butwell</h4>
<br />
Adrianne is a Widow to her fiance (November 11, 2018) with two daughters, living in&nbsp;South Florida. She has a Bachelor's Degree in Psychology and has several years of personal experience with grief, grief support and trauma.<br />
<br />
<a href="https://griefsucksawidowsguide.blogspot.com/p/adrianne-butwell.html" target="_blank">Continue... More about Adrianne</a><br />
<br />
<br />
<h4>
Darrell Wolfe</h4>
<br />
Darrell is a Widower (June 25, 2018) with two sons, living in North Idaho. He is a Biblical Studies and English major and has years of personal experience dealing with the topic of healing, addiction, and trauma recovery. He also writes at <a href="http://darrellwolfe.com/">DarrellWolfe.com</a>.<br />
<br />
<a href="https://griefsucksawidowsguide.blogspot.com/p/darrell-wolfe.html" target="_blank">Continue... More about Darrell</a><br />
<br />
<br />