---
title: 'Support'
date: '2015-10-19T05:17:00.0010000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Creatives'' Space'
blogger_status: 'LIVE'
blogger_page_id: '4111112296766807903'
blogger_filename: '/p/support.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Creatives_ Space/feed.atom'
---

<i>** Under Construction**</i><br />
<br />
<br />
<h3>
We're not the only shop in town, and why should we be?&nbsp;</h3>
<br />
<h4>
Creatives work best when we are in community, not competition.&nbsp;</h4>
<br />
We can connect you with other sources to help you walk in your creative endeavors.<br />
<div>
<br /></div>
If I serve your needs best, great! If I need to hook you up with another resources that can serve your needs better, great!<br />
<br />
How can we support YOUR creativity?<br />
<br />
Here are a few of our favorite resources to date:<br />
<br />
<br />
<br />
<h4>
Fine Art and Crafts</h4>
<br />
<ul>
<li><a href="http://www.hobbylobby.com/" target="_blank">Hobby Lobby</a></li>
<ul>
<li>Supplies including fabric, art, crafts, photo framing, home decorations, and chotchkies.&nbsp;</li>
</ul>
</ul>
<ul>
<li><a href="http://www.joann.com/" target="_blank">JoAnn's</a></li>
<ul>
<li>Fabric and Crafts</li>
</ul>
</ul>
<ul>
<li><a href="http://www.michaels.com/" target="_blank">Michaels</a></li>
<ul>
<li>Art supplies, crafts, jewelry &amp; beading, home decor, photo framing, fabric.</li>
</ul>
</ul>
<br />
<ul>
<li><a href="http://www.craftsy.com/" target="_blank">Craftsy</a></li>
<ul>
<li>Join Craftsy, a community of passionate crafters featuring online classes about all your favorite crafts including quilting, sewing &amp; cake decorating.</li>
</ul>
</ul>
<br />
<br />
<ul>
<li><a href="https://www.creativelive.com/" target="_blank">Creative Live</a></li>
<ul>
<li>Online classes for creative individuals. Photo &amp; Video, Art &amp; Design, Music &amp; Audio, Craft &amp; Makers, Money &amp; Life.</li>
</ul>
</ul>
<br />
<br />
<h4>
Fiber Arts</h4>
<br />
<br />
<br />
<br />
<br />
<h4>
Music, Audio, Sound</h4>
<br />
<br />
<ul>
<li><a href="http://ketoscreative.com/about_us" target="_blank">KetosCreative</a></li>
<ul>
<li>Offering services and training in Photography, Videography, Graphic Design, Web Design, Web Development and Coding, Recording, Live Sound, Audio Production, Songwriting, Musical Instrumentation, and more.&nbsp;</li>
</ul>
</ul>
<br />
<ul>
<li><a href="http://sota.gatewaypeople.com/" target="_blank">Gateway School of Technical Arts</a></li>
<ul>
<li>Offering courses and hands on training in LIVE Audio, Video, Staging and Lighting, Technical Arts Leadership. With over 735+ live events every month, you will not lack for hands on training at this school.&nbsp;</li>
</ul>
</ul>
<br />
<br />
<h4>
Graphic Arts</h4>
<br />
<ul>
<li><a href="http://ketoscreative.com/about_us" target="_blank">KetosCreative</a></li>
<ul>
<li>Offering services and training in Photography, Videography, Graphic Design, Web Design, Web Development and Coding, Stage Lighting, Recording, Live Sound, Audio Production, Songwriting, Musical Instrumentation, and more.&nbsp;</li>
</ul>
</ul>
<br />
<br />
<ul>
<li><a href="http://sota.gatewaypeople.com/" target="_blank">Gateway School of Technical Arts</a></li>
<ul>
<li>Offering courses and hands on training in LIVE Audio, Video, Staging and Lighting, Technical Arts Leadership. With over 735+ live events every month, you will not lack for hands on training at this school.&nbsp;</li>
</ul>
</ul>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />