---
title: 'About'
date: '2012-05-24T06:38:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Church Finder'
blogger_status: 'LIVE'
blogger_page_id: '4209049644429067723'
blogger_filename: '/p/about.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Church Finder/feed.atom'
---

This site is&nbsp;intended&nbsp;to be a way for you to connect to a local church in your area. This list could never be comprehensive. As it grows, there will be no way for me to personally verify every church is a good church. But I will list those that have been recommended to me, or who's teaching I have heard and was impressed with, or who are connected to other ministries I trust.<br />
<br />
Because this list could never include every good church I ask that you email me if you know of a church that ought to be on this list. I have also included links to other sites that have other lists of churches. If you don't find what you need here, please take advantage of those and other resources you find.<br />
<br />
Darrell G. Wolfe<br />
churchfinder@live.com<br />
<br />
<a href="http://wordchurchfinder.blogspot.com/2012/05/why-should-i-go-to-church.html" target="_blank">Why should I go to Church?</a>
<br />
<br />
See Also:&nbsp;<a href="http://wfconceptions.wordpress.com/" target="_blank">http://wfconceptions.wordpress.com/</a>