---
title: 'Obit: Laurence W. Wolfe'
date: '2018-04-06T05:05:00.0000000+00:00'
draft: true
blogger_blog: 'Wolfe Family Tree'
blogger_status: 'LIVE'
blogger_post_id: '5900853658532004475'
blogger_filename: '/2018/04/obit-laurence-w-wolfe.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Wolfe Family Tree/feed.atom'
---

I find this while looking up data on the family... I may have family in Kansas City, KS.<br />
<br />
<br />
<div id="sitetitle" style="border-bottom: 2px solid black; font-family: &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 12px; line-height: 18px; margin-bottom: 18px;">
BonnerSprings.com</div>
<div class="story-header" style="font-family: &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px;">
<h2 class="header" style="font-size: 28px; line-height: 36px; margin: 0px; padding-bottom: 9px; padding-top: 9px;">
Obit: Laurence W. Wolfe</h2>
</div>
<div id="story-body" style="border-bottom: 1px solid rgb(102, 102, 102); font-family: &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; margin-bottom: 1em;">
<div class="story-subheader" style="border-bottom: 1px solid rgb(102, 102, 102); margin-bottom: 1em;">
<div class="date" style="font-size: 12px; line-height: 18px; margin-bottom: 18px;">
June 5, 2002</div>
</div>
<div style="font-size: 12px; line-height: 18px; margin-bottom: 18px;">
1928 2002</div>
<div style="font-size: 12px; line-height: 18px; margin-bottom: 18px;">
Services for Laurence Wolfe, Linwood, formerly of Bonner Springs, were June 3 at the Alden-Harrington Funeral Home, Bonner Springs. Burial was in Lenape Cemetery, Linwood.</div>
<div style="font-size: 12px; line-height: 18px; margin-bottom: 18px;">
Mr. Wolfe died Thursday, May 30, at his home in Linwood.</div>
<div style="font-size: 12px; line-height: 18px; margin-bottom: 18px;">
Laurence was born Sept. 14, 1928, in Tonganoxie. He was employed at Mid Continent Underground Storage, retiring in 1989. He was a former member of the Delaware Dancers Square Dancer, belonged to the Basehor Lions Club, Fraternal Order of Eagles No. 8676 in Leavenworth. He was formerly on the Bonner Springs Volunteer Fire Department. He was a U.S. Navy veteran of Korea.</div>
<div style="font-size: 12px; line-height: 18px; margin-bottom: 18px;">
He was preceded in death by his parents, Roy L. and Ester Elizabeth Wolfe; and two brothers, Roy L. Wolfe Jr., and Donald Wolfe.</div>
<div style="font-size: 12px; line-height: 18px; margin-bottom: 18px;">
Survivors include his wife, Patricia Wolfe, of the home; three daughters, Kathy and husband Jay DeLap, Kansas City, Kan., Liz and husband Frank Pino, Edwardsville, and Tammy Pierce, Kansas City, Kan.; seven grandchildren, Devin, John, and Amy Pino, Edwardsville, Brian Pierce, Kansas City, Kan., Harmony DeLap, Overland Park, Heather and husband Phillip Els, Kansas City, Kan., Ryan DeLap, Merriam; two great-grandchildren, Alexandria and Arrison DeLap, Overland Park; and one brother, John and wife, Betty Wolfe, Weiser, Idaho.</div>
<div style="font-size: 12px; line-height: 18px; margin-bottom: 18px;">
The family suggests memorials to the American Heart Association.</div>
</div>
<div style="font-family: &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 12px; line-height: 18px; margin-bottom: 18px;">
<b>Originally published:</b></div>
<br />
http://www.bonnersprings.com/news/2002/jun/05/obit_laurence_w/?print<br />
<br />
<br />