---
title: 'BB4B Preview: Money'
date: '2012-06-26T15:25:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Bulldog Publications'
blogger_status: 'LIVE'
blogger_page_id: '7960027257660468308'
blogger_filename: '/p/bb4b-preview-money.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Bulldog Publications/feed.atom'
---

<br />
<div align="center" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
<strong>$</strong></div>
<div align="right" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
<strong>1</strong></div>
<div align="right" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
<strong>&nbsp;MONEY</strong></div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px;">
<span style="font-family: Verdana, Arial, Helvetica, sans-serif;"><span class="Apple-style-span" style="font-size: 11px; line-height: normal;"><br /></span></span></div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
There is a right place, a good place, for money in your life. There is a place where money is not your god but your servant. Money makes a terrible master but a fine servant. If money is your servant than it doesn’t matter how much you have, it will never control you.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
It takes money to print bibles, tracts, and books. It takes money to translate and print bibles and books into other languages. It takes money to ship those items and get them distributed into other places. It takes money to feed the poor, clothe the naked, and build shelters for the homeless. I had one young man try to tell me he didn’t need money, he said that he could go preach one on one anywhere in the world. I thought about that for a long time. He’ll still need food, clothing, covering, transportation, bathrooms, etc. Even if he doesn’t pay for them someone will have to. So really what he’s saying is that he’d rather be burden on others than believe God for provision. It sounds holy, but it’s actually selfish.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
Let’s take a look at a few scriptures that talk about how we are to conduct ourselves in the arena of work:</div>
<h4 align="center" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 16px; line-height: 20px; margin-bottom: 5px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;">


<em>Deuteronomy 8:7,18</em></h4>
<h4 align="center" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 16px; line-height: 20px; margin-bottom: 5px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;">


<em>“…For the LORD your God is bringing you into a good land…</em><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</em><em>And you shall remember the LORD your God, for it is&nbsp;<span style="text-decoration: underline;">He</span>&nbsp;who gives you power to get wealth”</em><em></em><em></em></h4>
<div align="center" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
<strong><em>Ephesians 4:28</em></strong></div>
<div align="center" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
<em>“…let him labor, working with his hands what is good, that he may have something to give him who has need.”</em></div>
<div align="center" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
<strong><em>1 Thessalonians 4:11 NIV</em></strong></div>
<div align="center" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
<em>“… mind your own business and to work with your hands…so that you will not be dependent on anybody.”</em></div>
<div align="center" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
<strong><em>1 Thessalonians 4:11 NKJV</em></strong></div>
<div align="center" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
<em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; “…to mind your own business, and to work with your own hands…that you may lack nothing.”</em></div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; So we can see that God is the one who gives us the power (means and ability) to get wealth. We also see the purpose of work is so that we lack nothing, we are not dependant on anybody, and so that we can give to those in need.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
<em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</em>God also wants to be a Father to us! We’ve known God as Savior, Healer, King, Provider of Needs, but we must know Him as Father. Good Fathers give to their kids. What decent father out there hasn’t gotten something for their kid that they did not “need”? What grandparent hasn’t gotten something for their grand baby that they did not need? Isn’t this the point Jesus made about Father’s giving stones to their kids when they asked for bread? He said even evil people don’t do that. He is OUR FATHER who gives us richly all things to enjoy<a href="http://kogconcepts.wordpress.com/Users/Public/Documents/Blog.Website/KOGC/BankingBasicsforBelievers%20for%20KOGC.doc#_ftn1" style="text-decoration: none;" title="">[1]</a>.<em></em></div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
Having said that let us take a look at an example of how not to live. Let us take a look at the story of Edward. He would often attend family meetings in his old car and very seldom wore anything new. When he did buy something “new” it would be from the local thrift store. One day the family got word that he had died. After the funeral was over and things had settled down from a busy week the family all gathered at his house to begin cleaning it out. It was a fine old house, small but quaint.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
Upon investigation they found over $68,000 in cash stuffed neatly into the mattress. They found another $35,000 rolled into socks in the dresser. The same story throughout the rest of the house; crevices, couches coffee tables, coffee cans, and even in the freezer, money was stashed everywhere. He had always seemed like the kind of person who was living off of little to nothing. He was always complaining how money was tight and usually only gave cards at Christmas time and for Birthdays, never presents or cash. Eventually over $1.5 million was discovered throughout the house. More money came by the sale of antique furniture. There was another car he owned but rarely drove in the back garage under cover. The car, a 1950 Mercedes in rare like new condition and hardly driven, sold to a collector for over $100,000 dollars. Edward was sitting on, sleeping on, and driving a living fortune. He never did enjoy any of it. He never really used anything to satisfy his basic needs, or the needs or desires of others.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
This then brings us to the point of this story. Why have money if you’re not going to use it? Money is nothing more than the medium of exchange used to trade time, talent, and resources. Edward had money that he could have used to enjoy life and to help others enjoy it. He chose, instead, to live in fear of loosing it. Money is only worth its ability to help you acquire needs, wants, and desires for yourself and others. What Edward failed to recognize was that true wealth can never be measured in money. It can not be measured in the having of or not having of money.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
In Israel today you can find a saying, it is used as a greeting much like “Hello” in the USA. The word is “Shalom”. In Arabic the word is “Salem”. In English the word is “Peace”. The Hebrew definition and meaning of this word is “Nothing Missing, Nothing Broken, Everything Whole and Complete”.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
Edward failed to see that money without family is not living. Having money and not enjoying it is not living. Having money and being afraid of loosing it is worse than not having it. So the very first thing we must settle for ourselves is: “What money is.” &amp; “What it is not.”</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
We’ve seen what money is not. It is not security. Money is NOT: happiness, or true wealth by itself. We all know of people who have a lot of money but are miserable. You may know them personally or know of them.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
In 1 Timothy 6:6-10, we see that godliness with contentment is great gain but the love of money is a root of all kinds of evil. Where does this contentment come from? How do we avoid this money anxiety? Philippians 4 gives us our answer: “…be anxious for nothing, but through prayer and supplication with thanksgiving let our requests be known to God. Prayer and Supplication, in Greek, literally mean General Requests and Specific Requests.&nbsp; It is through these requests with thanksgiving that we can do ALL things through Christ, (the Anointed One and His Anointing). What thanksgiving? We thank God not only for what he has already done… we thank Him in advance for giving us what we asked for, believing that He will and that it’s already done. (Mark 11:24 and 1 John 5:14-15)</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
Jesus told us, in Matthew 6:24-34, that we are not to worry about money meeting our needs but to seek God’s right order of doing things and all the rest of this we need, want, and desire would be added to us through Him!</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
Money is a tool, nothing more or less. There was a day in world history that we all used a system of trade. It is now called the “Barter System.”</div>
<h3 align="center" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 18px; font-weight: normal; line-height: 20px; margin-bottom: 5px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;">


~Barter System~</h3>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
If I owned cattle and you owned chickens, I could trade my milk for your eggs. Thus; in many trades we all get what we need. The problem is: if I need eggs, but you don’t want milk than I have to go trade for something else you do want to then trade for your eggs. This system, although simple, was cumbersome and awkward.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
Over time people would trade jewels, stones and metal for products and services. Eventually governments printed coins from metals (usually gold) with very specific logo’s to use as currency. As time went on they began to use printed paper, in addition to the metal coins. As people gathered and collected more and more coins and paper there arose the need to store it somewhere safe. If you leave it in your house and then leave, someone could come and take it, or it could be burnt down. All the gathering would have been lost.</div>
<h3 align="center" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 18px; font-weight: normal; line-height: 20px; margin-bottom: 5px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;">


~Banking System~</h3>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
This was the birth of the bank. A bank in its simplest form keeps your money safer from theft and disaster, and pays you for letting them use it. The bank benefits by lending the money to folks who need it in return the borrower pays it back plus interest. Interest is money you pay for borrowing money, and it is also money you earn for letting the bank use your money.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
Jesus mentioned the banking system. He awarded the one who had turned his five talents into ten. He told the one who had dug a whole and buried the money God gave him that he should have, at the very least, turned it in to the bank for interest. (Matthew 25:27)</div>
<h3 align="center" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 18px; font-weight: normal; line-height: 20px; margin-bottom: 5px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;">


~Today~</h3>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
Today all over the world, and especially here in the USA, there are many financial institutions. In recent decades changes have been made that allow for more competition and convenience. Up until the last few decades you purchased stock market products through investment firms, insurance through insurance companies, banking either through banks, savings and loans, or credit unions. Law changes over the last few decades have allowed one company to offer all in one services, to a degree. The competition has added fresh air to the market and created new products and services. It has also made it easier to do one stop shopping.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
These same law changes caused a new development; The National Bank. Most banks for the greater history of the world were local. They had a few branches here and there. Having a bank in two states required partnership between banks. Law changes now allow for banks to have branches in more than one state. This created the national bank. There are laws restricting how big one bank can be. However many banks are getting larger, adding more and more access to banking wherever you go.</div>
<h3 align="center" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 18px; font-weight: normal; line-height: 20px; margin-bottom: 5px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;">


~Time~</h3>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
“Time is money!” That saying has been rolling around for a long time. What does it mean? There are many resources in the world. Trees can be regrown. Oil although running low will last a very long time, in fact we haven’t even tapped all the known resources for oil. Money when lost can be remade. In the bible, Job lost everything he had and ended up with double what he had at first in the end.<a href="http://kogconcepts.wordpress.com/Users/Public/Documents/Blog.Website/KOGC/BankingBasicsforBelievers%20for%20KOGC.doc#_ftn2" style="text-decoration: none;" title="">[2]</a>&nbsp;Time, on the other hand, cannot be renewed. It’s true that God operates outside of time. It is even possible for Him to catch you up if you’ve fallen behind. It is possible for him to slow, reverse, or even stop time to accomplish something<a href="http://kogconcepts.wordpress.com/Users/Public/Documents/Blog.Website/KOGC/BankingBasicsforBelievers%20for%20KOGC.doc#_ftn3" style="text-decoration: none;" title="">[3]</a>.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
Ultimately, though, you have been given 24 hours a day, and 365 days a year on our common calendar. When you spend a day worrying about what you’re going to do about a problem that has come along you will not get that day back. You could invest your time in confessing the Word over that problem and meditating on what God says about it and thanking Him in advance for his provision. That would be a wiser use of your time.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
The time you spend will be spent. We even use the term “spent” in reference to time because we understand that it is valuable. Time is a resource, a commodity.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
Five people working on a project will make it happen faster than one person could on their own. That is because time has been duplicated in the efforts of many. When you are hired to work at a grocery store to push carts, you are effectively hired for your time. The owner or manager of that store could go and push the carts if he wanted to. However he would not be able to attend to the paperwork and decision-making he needs to do. So he hires you to duplicate his efforts and maximize his own time. You then trade your time for a pay check. You may get paid little or much, but you traded your time for money.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
So why do we think it’s so important to trade our time, which we cannot get back, for money which they print everyday and which decreases in value everyday? We do this because money is useful to us. Money is a tool. It’s a hammer or screw driver. A person can use a hammer in anger to break an expensive crystal vase or calmly and skillfully use it to drive a nail into the frame of a new house being built. One use is appropriate and one is not. Both can be done by the same person. The heart of the person holding the hammer will determine the use of that hammer. In the same manner the heart of the person using money will determine the use of that money.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
Many people inside and outside of churches throughout America quote a bible verse that says: “Money is the root of all evil.” This is actually a miss-quote. The bible doesn’t say money is the root of all evil. It says, in 1 Timothy 6:10, that the LOVE of money is the root of all KINDS of evil. To love money is to trust money for your security, this is always wrong. It will always lead to trouble. You can commit this crime without ever owning a dime. The next time you find yourself worried about bills, or how you are going to feed your family, or get a roof over your head, or clothe yourself, you can be assured you are committing this subtle and insidious crime. Worrying about money IS serving money. (Matthew 6:24-25)</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
Your purpose for money is what you can use it for. The wise use of wealth is more important that the wise use of a hammer. The man with his hammer crafts a fine home for the people he builds it for. The wise use of wealth crafts lifestyles, homes, jobs, provision, food, clothing, joy, peace, and most importantly provides the tools needed to spread the Gospel of a loving Jesus to a dying world.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
In Luke 22:7-14 Jesus is given the use of a man’s home for his last supper. In Acts 16:14-15 Paul is given the use of a woman’s home to preach the gospel. In I Kings 17:8-10 we see God use a widow woman’s gift to Elijah to provide for both him and herself and her son through a deadly drought. Over and over we see God provide through people.</div>
<h3 align="center" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 18px; font-weight: normal; line-height: 20px; margin-bottom: 5px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;">


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ~Preachers Money~</h3>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
Have you ever noticed how easy it is for someone to think that a sports person is being shafted when he is offered less than 10 million for a contract, but that same person starts to balk and squawk if he hears of a Pastor making 1 million? If you value The Word as more valuable than any other thing on the planet, and your Pastor handles The Word and delivers it to you week in and week out faithfully, than you should make absolutely sure that your Pastor is WELL taken care of. The Pastor SHOULD be among the highest paying callings in the world because he or she deals with The Word. If you don’t agree than you are telling us that The Word is NOT the highest priority in your life, plain and simple.</div>
<h3 align="center" style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 18px; font-weight: normal; line-height: 20px; margin-bottom: 5px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;">


~Conclusion~</h3>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
Money is not evil. Money is not good. The heart of the holder determines its value. Money is a tool. Money is a representation of your time, therefore you should be paid what your time is worth. Money is worthless unless it has direction and purpose. Money is essentially paper or numbers on a screen. Money is worth only what people value it to be worth. Money is a hammer and chisel. It will destroy or it will create master pieces depending on the hands that wield it.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
So now that we have settled where money came from and what it’s good for, let us move on to the practical applications for it.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
If you are interested in a deeper look at what the Word of God says about wealth for the believer I suggest you start with a book from Kenneth Copeland Ministries: “The Laws of Prosperity<a href="http://kogconcepts.wordpress.com/Users/Public/Documents/Blog.Website/KOGC/BankingBasicsforBelievers%20for%20KOGC.doc#_ftn4" style="text-decoration: none;" title="">[4]</a>”.</div>
<div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px;">
<hr align="left" size="1" width="33%" />
<div>
<div style="padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
<span style="color: black;"><a href="http://kogconcepts.wordpress.com/Users/Public/Documents/Blog.Website/KOGC/BankingBasicsforBelievers%20for%20KOGC.doc#_ftnref1" style="text-decoration: none;" title="">[1]</a>&nbsp;1 Timothy 6:17</span></div>
</div>
<div>
<div style="padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
<span style="color: black;"><a href="http://kogconcepts.wordpress.com/Users/Public/Documents/Blog.Website/KOGC/BankingBasicsforBelievers%20for%20KOGC.doc#_ftnref2" style="text-decoration: none;" title="">[2]</a><strong>&nbsp;&nbsp;&nbsp;&nbsp; Job 42:10</strong></span></div>
</div>
<div>
<div style="padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
<span style="color: black;"><a href="http://kogconcepts.wordpress.com/Users/Public/Documents/Blog.Website/KOGC/BankingBasicsforBelievers%20for%20KOGC.doc#_ftnref3" style="text-decoration: none;" title="">[3]</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Joshua 10:13,</strong>&nbsp;<strong>Habakkuk 3:11, 2 Kings 20:11,</strong>&nbsp;and&nbsp;<strong>Isaiah 38:8</strong></span></div>
</div>
<div>
<div style="padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">
<span style="color: black;"><a href="http://kogconcepts.wordpress.com/Users/Public/Documents/Blog.Website/KOGC/BankingBasicsforBelievers%20for%20KOGC.doc#_ftnref4" style="text-decoration: none;" title="">[4]</a>&nbsp;&nbsp;&nbsp;&nbsp; www.kcm.org</span><br />
<span style="color: black;"><b><br /></b></span><br />
<b><span style="color: black;">For more previews of the book see our <a href="http://n2gs.blogspot.com/" target="_blank">Good Success</a> site at:&nbsp;</span></b><a href="http://n2gs.blogspot.com/2012/06/you.html" style="background-color: white;">http://n2gs.blogspot.com/2012/06/you.html</a></div>
</div>
</div>