---
title: 'Resources'
date: '2024-07-18T01:21:00.0010000+00:00'
draft: true
blogger_blog: 'Sunrise Scentworks'
blogger_status: 'LIVE'
blogger_post_id: '7616072290153910029'
blogger_filename: '/2024/07/resources.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Sunrise Scentworks/feed.atom'
---

Here's a draft for the resources page linking to every vendor used in making the Vanilla Mint cold processed soap:<div><br></div><div>---</div><div><br></div><div>## Soap Making Resources</div><div><br></div><div>Creating high-quality cold processed soap requires sourcing the best ingredients and tools. Below is a list of trusted vendors we’ve used to procure the materials needed for our Vanilla Mint soap. Click on each link to visit the vendor's website.</div><div><br></div><div>### Oils and Butters</div><div><br></div><div>1. **Olive Oil**&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Website:** [Visit Placeholder](#)</div><div><br></div><div>2. **Coconut Oil**&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Website:** [Visit Placeholder](#)</div><div><br></div><div>3. **Organic Shea Butter**&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Website:** [Visit Placeholder](#)</div><div><br></div><div>4. **Castor Oil**&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Website:** [Visit Placeholder](#)</div><div><br></div><div>5. **Tallow**&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Website:** [Visit Placeholder](#)</div><div><br></div><div>### Fragrance</div><div><br></div><div>6. **Vanilla Mint Fragrance**&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Website:** [Visit Placeholder](#)</div><div><br></div><div>### Additives</div><div><br></div><div>7. **Kaolin Clay**&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Website:** [Visit Placeholder](#)</div><div><br></div><div>8. **Mica**&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Website:** [Visit Placeholder](#)</div><div><br></div><div>### Equipment</div><div><br></div><div>9. **Safety Gear (Goggles and Gloves)**&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp;- **Website:** [Visit Placeholder](#)</div><div><br></div><div>10. **Digital Scale**&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Website:** [Visit Placeholder](#)</div><div><br></div><div>11. **Stainless Steel or Plastic Mixing Bowls**&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Website:** [Visit Placeholder](#)</div><div><br></div><div>12. **Stick Blender**&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Website:** [Visit Placeholder](#)</div><div><br></div><div>13. **Soap Mold**&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Website:** [Visit Placeholder](#)</div><div><br></div><div>14. **Measuring Spoons**&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Website:** [Visit Placeholder](#)</div><div><br></div><div>15. **Heat-Resistant Container**&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Website:** [Visit Placeholder](#)</div><div><br></div><div>16. **Thermometer**&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Website:** [Visit Placeholder](#)</div><div><br></div><div>### Additional Resources</div><div><br></div><div>17. **Soap Making Books and Guides**&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Website:** [Visit Placeholder](#)</div><div><br></div><div>18. **Online Soap Making Classes**&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Vendor:** Placeholder&nbsp;&nbsp;</div><div>&nbsp; &nbsp; - **Website:** [Visit Placeholder](#)</div><div><br></div><div>### Conclusion</div><div><br></div><div>These vendors have been essential in helping us create our handcrafted Vanilla Mint soap. By sourcing high-quality ingredients and tools, we ensure that each bar of soap is made to the highest standard. We hope this resource page helps you in your soap-making journey.</div><div><br></div><div>---</div><div><br></div><div>Feel free to adjust the placeholders with the actual vendor names and their corresponding links.</div>