---
title: 'What does Towdah mean?'
date: '2016-06-04T23:18:00.0020000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Towdah: tō·dä'''
blogger_status: 'LIVE'
blogger_page_id: '5909554066287407155'
blogger_filename: '/p/blog-page.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Towdah_ tō·dä_/feed.atom'
---

<br /><h4>
Towdah is one of <a href="http://towdahaudio.blogspot.com/2013/09/towdah-among-seven-words-for-praise.html">seven words for "Praise"</a>.</h4>
<ul>
<li><b>Towdah</b>:&nbsp;</li>
</ul>
<blockquote class="tr_bq">
<i>An extension of the hand in adoration, avowal, or acceptance, to thank God in advance.&nbsp;</i></blockquote>
<br />
As an Audio person I am an extension of the worship team, pastor, etc. It is all funneled through me to the people. It's very hard for the back row to hear without the things I do.&nbsp;<div>
<br /></div>
<div>
Likewise I could mess up the flow of things if I am not watching, being diligent, and keeping my own art/craft to it's highest standard.&nbsp;</div>
<div>
<br /></div>
<div>
It might be better for there to be no audio than to have the wrong person behind the board. In a very real sense, I am an invisible extension of the hand from God through the platform to the people and from them, because they respond, back to God.<blockquote class="tr_bq">
</blockquote>
<br /><h4>
All Praise</h4>
<blockquote class="tr_bq">
Toda in Spanish means: ALL<br />Towdaw in Hebrew means: Praise, Confession, and Thanksgiving<br /><b>Therefore I am to give ALL Praise, Confession, and Thanksgiving to God.</b></blockquote>
<br />I know I’m called (in part) to music, worship, audio, and praise as a central part of my life. But I’ve been pushing it off and laying it aside for a long time.&nbsp;</div>
<div>
<br /></div>
<div>
Over the years I’ve spent lot’s of time on and off Church Platforms doing Praise and Worship. It seems that just as soon as I get anywhere close to a platform I start feeling ill, agitated, sick, nervous, scared, and depressed. It’s happened every time at every church.&nbsp;</div>
<div>
<br /></div>
<div>
Some may be tempted to call this stage fright. It’s not.&nbsp;</div>
<div>
<br /></div>
<div>
After many years of asking the Lord about this reaction I was having I finally just decided that I couldn’t be on a platform anymore until I knew what was happening.&nbsp;</div>
<div>
<br /></div>
<div>
Several years went by and the music inside grew dry. I didn’t even like listening to it. I didn’t want to be present for the worship part of the service. I all but forgot about music.&nbsp;</div>
<div>
<br /></div>
<div>
During that time God started dealing with me about the level of my intimacy with Him. I was keeping Him at a distance… as I was everyone else too.&nbsp;</div>
<div>
<br /></div>
<div>
Since then... He’s been teaching me about prayer and closeness to Him. I’ve grown...&nbsp;</div>
<div>
<br /></div>
<div>
Since 2010, God has brought music back to me... slowly.<br /><br /><br /><h4>
Confess-Praise-Thanksgiving… These are the heart of true music!</h4>
</div>
<div>
<a href="http://en.wikipedia.org/wiki/Rosh_Hashanah">Rosh Hashanah</a><br />תּוֹדָ |&nbsp;<a href="http://towdah.wordpress.com/lang/lexicon/Lexicon.cfm?strongs=H8426">H8426</a> <br /><br />towdah |&nbsp;tō·dä’ <br /><blockquote class="tr_bq">
<b>thanksgiving, praise, thanks, thank offerings, confession</b>1) confession, praise, thanksgiving<br />&nbsp; &nbsp;a) give praise to God<br />&nbsp; &nbsp;b) thanksgiving in songs of liturgical worship, hymn of praise<br />&nbsp; &nbsp;c) thanksgiving choir or procession or line or company<br />&nbsp; &nbsp;d) thank-offering, sacrifice of thanksgiving<br />&nbsp; &nbsp;e) confession</blockquote>
</div>
<div>
<blockquote class="tr_bq">
From the Root Word:<br />יָדָה |&nbsp;From&nbsp;<a href="http://towdah.wordpress.com/wp-admin/Lexicon.cfm?Strongs=H3034&amp;t=KJV">יָדָה (H3034)</a><br />yadah | yä·dä’<br />*) to throw, shoot, cast<br />*) to give thanks,, laud, praise<br />*) to confess, confess (the name of God)</blockquote>
</div>
<div>
Darrell</div>
