---
title: 'Small Business & Nonprofit Resources'
date: '2019-05-26T15:41:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Topos Creative, LLC'
blogger_status: 'LIVE'
blogger_page_id: '7742673571384682060'
blogger_filename: '/p/resources.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Topos Creative, LLC/feed.atom'
---

<div>Here is an ever-growing list of resources, links, blogs, articles, and tools to help Small Business and Nonprofit owners on a budget carve out their own strategic position of opportunity and influence, enhance their business, and get to doing what they love.<br /><br /><h4 style="text-align: left;">Microsoft Excel Help</h4></div><div><ul style="text-align: left;"><li><a href="https://youtube.com/playlist?list=PLSbGHx9UCQ8ql7z1fxp3cFIlSon7Gy00G" target="_blank">The Best of Excel, YouTube Playlist&nbsp;by Topos Creative LLC</a></li></ul><h4 style="text-align: left;">Best Free Editing Help</h4><div><ul style="text-align: left;"><li><a href="https://www.grammarly.com/" target="_blank">Grammarly</a></li></ul></div><h3 style="text-align: left;">Website and Online Tools</h3><h4 style="text-align: left;"><b> Website Creation</b></h4><b><ul style="text-align: left;"><li><a href="#">Blogger.com</a></li><li><a href="#">Wordpress.com</a></li><li><a href="#">Domain.com</a></li></ul></b><h4 style="text-align: left;"><b> Logo Design Tools</b></h4><b><ul style="text-align: left;"><li> My Favorite: <a href="#">LogoShuffle.com</a></li><li><a href="#">LogoMaker.com</a></li><li><a href="#">Logaster.com</a></li><li><a href="#">Logo.SquareSpace.com</a></li><li><a href="#">Vista Print's Logo Maker</a></li></ul></b><h4 style="text-align: left;"><b>Selling Products Online / Affiliate Marketing </b></h4><b><ul style="text-align: left;"><li><a href="#">Amazon Affiliate Program</a></li><li><a href="#">GUMROAD: </a>Sell products, name your own price!</li><li><a href="#">4 Steps to Affiliate Marketing Success, by Click Bank</a></li></ul></b><h4 style="text-align: left;"><b> Blogging &amp; Social Media Tools </b></h4><ul style="text-align: left;"><li><a href="#">Mail Chimp for Newsletters. </a></li><li><a href="#">Feedburner</a> (create personalized RSS feeds)</li><li><a href="#">Networked Blogs</a></li><li><a href="#">Tweet Deck</a></li><li><a href="#">BufferApp</a>: Pre-Schedule Social Media Posts</li><li><a href="#">IFTT</a></li><li><a href="#">AddThis: Smart Layers (Follow Buttons, Share Button, and more)</a></li><li><a href="#">Create a Flickr Slider</a></li><li><a href="#">Create a cool Header: Pic Monkey</a></li><li><a href="#">Google Analytics</a></li></ul>           <b>Blogger.com-Specific Resources <br /><ul style="text-align: left;"><li><a href="#">Blogger</a></li><li><a href="#">Getting started with a Blogger.Com Blog.</a></li><li><a href="#">How to use Blogger.Com and Domain.Com to host your Top Level Domain Name for less than $10/Year. </a></li><li><a href="#">A quick trick to optimize blogger headlines for SEO.</a></li><li><a href="#">About Blogger and SEO</a></li><li><a href="#">Adding Excerpts only to a Blogger Home Page</a></li></ul><div><br /></div></b>
<h3>The Small Business Startup Resource List</h3><h4 style="text-align: left;">Professional Growth &amp; Career Help</h4><a href="#"></a><ul><a href="#"></a><li><a href="#"></a><a href="#">How to answer Behavioral Interview Questions</a></li><li><a href="#">50 Behavioral Interview Questions</a></li><li><a href="#">Lou Adler</a>&nbsp;of the&nbsp;<a href="#">Adler Group</a>. You may not know him but any decent hiring manager in a large corporation has been trained under the&nbsp;<a href="#">Adler Interview Method</a>.</li><li><a href="#">2014 Resume Tips</a></li></ul><h3>Authority Authors/Articles/Podcasts</h3><ul><li>Pat Flynn,&nbsp;<a href="#">Smart Passive Income</a></li><ul><li><a href="#">Podcasting</a></li><li><a href="#">Blogging</a></li><li><a href="#">Affiliate Marketing</a></li></ul><li>Michael Hyatt,&nbsp;<a href="#">Virtual Mentor</a></li><ul><li>Do you have a&nbsp;<a href="#">personal mission/vision statement</a>?</li></ul><li>Podcast:&nbsp;<a href="#">How I Built This</a>, with Guy Raz</li></ul><br /></div>
