---
title: 'START HERE: About'
date: '2018-02-28T00:12:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Discerning The Time'
blogger_status: 'LIVE'
blogger_page_id: '4797552606822543451'
blogger_filename: '/p/start-here-about.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Discerning The Time/feed.atom'
---

<br />
<br />
<blockquote class="tr_bq">
<i>*Hype Disclosure: There is very little about end times prophecy that we can be completely certain of. So it's perfectly fine to disagree on the many points.I'm not interested in Hype or Mystery or Emotionalism... I'm interested in Truth. Which means I must always be open to further inquiry, debate, study, correction, refining, etc. Dogmatically holding to an idea, unable to consider other perspectives, is a sign that you are not fully convinced of that idea and/or do not have sufficient evidence to support your conclusion. In other words, calm down, relax, and come on a journey of discovery with me.&nbsp;</i></blockquote>
<br />
<h4>
Oh Excellent <a href="http://en.wikipedia.org/wiki/Theophilus_%28biblical%29" target="_blank">Theophilus</a>,&nbsp;</h4>
<br />
In as much as others have put together an account of the things which we have seen and heard, so I too felt it fitting to put together the results of my study, so that you, and those others who happen to find it, will benefit from it.<br />
<br />
This is an an ongoing study, not a final declaration. I'm constantly looking to better understand and re-evaluate my understanding. Some things I just know that I know. Many things I'm still refining. Others I'm just not sure about. I will post here as often as I am able. This is a side project for now, a place to park and gather my thoughts and studies on the topic of end times, last days prophecy.<br />
<br />
This is a repository of study. I've heard many things I thought I agreed with and it turned out that further understanding helped me see it in a new light. In other cases further understanding only strengthened that position.<br />
<br />
I'm merely documenting my study as I go. Don't expect everything to flow like a well thought out doctrinal thesis. And yet, I'll try to put together a <a href="http://discerningthetime.blogspot.com/p/the.html" target="_blank">Timeline Page</a>&nbsp;in order to keep things easy to follow and link posts to it as I go.<br />
<br />
<h3>
<br />Level Set: Pre-Study Foundation</h3>
<br />
<h4>
Jesus Has The Final Word</h4>
<br />
I'm operating from the base assumption that<br />
<br />
<ul>
<li>Jesus is my Lord and Savior</li>
<li>The Bible is 100% accurate Historically, Theologically, and otherwise.</li>
<li>The Bible Interprets the Bible, NOT other texts or authors. When a passage is in doubt let the Bible interpret itself.&nbsp;</li>
<li>These other texts and authors can, however, help us see things we've never seen or noticed about the culture, language, background, etc. Therefore they are helpful to our understanding.</li>
<li>Jesus has the final Word, He IS the Final Word. Therefore I defer all my study to Him. If I'm wrong he'll let me know eventually, either now or in the future, or the FAR future. I trust Him to lead my study.&nbsp;</li>
</ul>
<div>
<br /></div>
<br />
<h4>
Keep Up With Me</h4>
<br />
If you would like to subscribe you can do so by RSS or by email. You will get an email update every time I post something new. Which may be 10 times one week, and nothing for moths between.<br />
<br />
<h4>
Participate In The Conversation</h4>
<br />
If you have more to add to this study please feel free to leave a comment on any post or post a new comment on the Q&amp;A Page. Please keep it civil. This site is for learning the truth, not pushing out propaganda or agendas. You can also email <a href="mailto:Me@DarrellWolfe.Com" target="_blank">Me@DarrellWolfe.Com</a>.<br />
<br />
<h4>
Scholarly Disclosures</h4>
<br />
<b>I'm not a scholar</b>, wouldn't want to be. I could have been, tried to be for a while. I did the college academia thing. I know how to use critical thinking and science and history and math. I'm a smart cookie. But you will find that I defer to spiritual understanding over logic more often than not; with a little logic thrown in just for fun. God tends to use "the foolish things of this world to confound the wise", so I've made myself a fool in order to understand the things of God.<br />
<br />
<br />
<b>Affiliate Disclosure</b>. I do suggest other works, some of these may have affiliate links, in which case I would earn money from those links. If you should click on such a link I would earn a commission or other benefit from your click and/or purchases on that site. Regardless I only suggest things I've enjoyed or received some benefit from and think you would to.<br />
<br />
<h2 class="title" style="background-color: #c5c5c5; border: 0px; color: #414445; font-family: 'PT Sans', Arial; font-size: 14px; margin: 10px 0px 0px; padding: 4px 8px; text-shadow: rgb(255, 255, 255) 0px 1px 0px; text-transform: uppercase; vertical-align: baseline;">
16 CFR, PART 255 DISCLOSURE</h2>
<div class="widget-content" style="background-color: #e3e3e3; border: 0px; color: #222222; font-family: 'PT Sans', 'Helvetica Neue', Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18.001800537109375px; margin: 0px; padding: 0px; vertical-align: baseline;">
<span style="border: 0px; font-family: &quot;times new roman&quot;; font-size: 12px; font-style: inherit; font-weight: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">Disclosure of Material Connection: Some of the links in the post above are “affiliate links.” This means if you click on the link and purchase the item, I will receive an affiliate commission. I may also have received one or more of the products or services mentioned above for free in the hope that I would mention it on my blog. Regardless, I only recommend products or services I use personally and believe will add value to my readers. I am disclosing this in accordance with the Federal Trade Commission’s&nbsp;</span><a href="http://www.gpo.gov/fdsys/pkg/CFR-2003-title16-vol1/content-detail.html" style="border: 0px; color: #333333; font-family: 'Times New Roman'; font-size: medium; font-style: inherit; font-weight: inherit; margin: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;" target="_blank">16 CFR, Part 255</a><span style="border: 0px; font-family: &quot;times new roman&quot;; font-size: 12px; font-style: inherit; font-weight: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.” A Big Thank You to&nbsp;</span><a href="http://michaelhyatt.com/five-ways-to-comply-with-the-new-ftc-guidelines-for-bloggers.html" style="border: 0px; color: #333333; font-family: 'Times New Roman'; font-size: medium; font-style: inherit; font-weight: inherit; margin: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;" target="_blank">Michael Hyatt</a><span style="border: 0px; font-family: &quot;times new roman&quot;; font-size: 12px; font-style: inherit; font-weight: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">&nbsp;for helping us Bloggers with these new legal disclosure requirements.</span></div>
<br />
<br />
<h3>
Definitions</h3>
<br />
<h4>
It's important to know what one means by a thing (a word, phrase, or topic), before one can intelligently discuss said thing. Therefore the following are a growing list of terms and definitions.</h4>
<br />
<ul>
<li><b>Rapture</b>: The bodily evacuation of the born again believer from the planet earth, as separate and distinct from the second coming. The Church (previously dead, and currently alive) raise bodily into the air, and meet Jesus in the air, then head to heaven.</li>
</ul>
<ul>
<li><b>Second Coming:</b>&nbsp;Jesus comes comes back to earth for the first time, physically, since he left his disciples staring into the sky. He touches ground, takes over. The Church comes riding in behind him (meaning they already left earlier).&nbsp;</li>
</ul>
<ul>
<li><b>A Pre-Tribulation (Pre Trib) Rapture:</b>&nbsp;Church leaves earth prior to the start of a 7 year period called the tribulation. This event triggers the events that start the 7 years tribulation while believers are taking part in the 7 years marriage supper of the Lamb. There are also similar terms (Post-Trib) (Mid-Trib) that have other self-explanatory meanings. Decide for yourself which is true.</li>
</ul>
<ul>
<li><b>Tribulation</b>: A 7 year period of time, starting from the very public signing of a very specific treaty between Israel and Anti Christ (led by one character, not a cast of them), where God deals with Israel and Earth's inhabitants in a rather dramatic way, leading up to the second coming of Jesus to earth.</li>
</ul>
<ul>
<li><b>Great Tribulation:</b>&nbsp;The final half (3.5 years) of the tribulation in which AntiChrist breaks his covenant/treaty with Israel and persecutes Israel and those accepting God's Kingdom in a way that makes all other persecutions, including Hitler's Holocaust, look like a mere warm up.&nbsp;</li>
</ul>
<ul>
<li><b>AntiChrist:</b> A character that is opposite of Jesus Christ in every way, often imitating His Attributes to deceive. Led by Satan, and eventually inhabited by Satan himself. He leads a seven year war against God and the things of God on earth. He will be of Roman Decent (this could either mean Greek-Roman or even Eastern-Roman (Turkish)). He will be one of whom it is said: "You will know in your heart he is lying, but you just won't care".&nbsp;</li>
</ul>
<ul>
<li><b>Glorified Body:</b>&nbsp;The changing of the body we now know into a body like that of Jesus resurrected body, with new and/or enhanced characteristics.</li>
</ul>
<ul>
<li><b>The Resurrection Of The Dead:</b>&nbsp;Can either refer to Jesus being raised with a glorified body, the believers being raised out of the grave along with the current living believers, receiving their glorified body also, or another raising of the dead for those who are not in Christ at the end of all things for the final judgment.&nbsp;</li>
</ul>
<br />
<h3>
Key End Times Scriptures:</h3>
<br />
The books of Daniel (Old Testament) and Revelation (New Testament) together are the keys to understanding ALL biblical end times prophecy. Yet it is the entire bible which must interpret itself.<br />
<br />
This is the reason for all the confusion and false dogma. Never-the-less, I felt it good to at least keep a running log of the most primary scriptures pertaining to this topic. And they are, so far...<br />
<br />
<br />
<h4>
Old Testament Passages&nbsp;</h4>
<ul>
<li>Daniel (The whole book)</li>
<ul>
<li><a href="http://biblehub.com/niv/daniel/2.htm" target="_blank">Daniel 2</a>: The Statue of Nations and <strike>Four</strike>, make the Five, Arches Of World History</li>
<li><a href="http://biblehub.com/niv/daniel/7.htm" target="_blank">Daniel 7</a>: The Four Beasts</li>
<li><a href="http://biblehub.com/niv/daniel/9.htm" target="_blank">Daniel 9-12</a></li>
</ul>
<br />
<li><a href="http://biblehub.com/context/genesis/1.htm" target="_blank">Genesis 1-3</a></li>
<li><a href="http://biblehub.com/ezekiel/28.htm" target="_blank">Ezekiel 28</a> (King of Tyre = Satan)</li>
<br />



</ul>
<br />
<h4>
New Testament Passages&nbsp;</h4>
<div>
<div>
<ul>
<li><a href="http://biblehub.com/1_thessalonians/4-17.htm" target="_blank">1 Thessalonians 4:17</a></li>
<li><a href="http://biblehub.com/context/2_thessalonians/2-5.htm" target="_blank">2&nbsp;Thessalonians&nbsp;2:5-8</a></li>
<li><a href="http://biblehub.com/niv/revelation/4.htm" target="_blank">Revelations </a>(the whole book)</li>
<li><a href="http://biblehub.com/matthew/24.htm" target="_blank">Matthew 24</a></li>
<li><a href="http://www.gospelparallels.com/gospelparallels.html" target="_blank">Synoptic Gospels</a></li>
</ul>
</div>
<table border="1" cellpadding="0" cellspacing="0" style="background-color: white; color: black; font-family: verdana, arial, sans-serif; font-size: 10.8800001144409px; margin-left: auto; margin-right: auto;"><tbody>
<tr><td class="a" style="vertical-align: top; width: 270px;">The Day of the Son of Man</td><td style="vertical-align: top; width: 67px;">Matthew<br />
<a href="http://www.gospelparallels.com/gospelparallels.html#1" style="color: #67705a; outline: none; text-decoration: none;">10:39</a><br />
<a href="http://www.gospelparallels.com/gospelparallels.html#1" style="color: #67705a; outline: none; text-decoration: none;">24:17-18</a><br />
<a href="http://www.gospelparallels.com/gospelparallels.html#1" style="color: #67705a; outline: none; text-decoration: none;">24:23</a><br />
<a href="http://www.gospelparallels.com/gospelparallels.html#1" style="color: #67705a; outline: none; text-decoration: none;">24:26-28</a><br />
<a href="http://www.gospelparallels.com/gospelparallels.html#1" style="color: #67705a; outline: none; text-decoration: none;">24:37-41</a></td><td style="vertical-align: top; width: 67px;">Mark<br />
<a href="http://www.gospelparallels.com/gospelparallels.html#1" style="color: #67705a; outline: none; text-decoration: none;">13:19-23</a><br />
<a href="http://www.gospelparallels.com/gospelparallels.html#1" style="color: #67705a; outline: none; text-decoration: none;">13:14-16</a></td><td style="vertical-align: top; width: 67px;"><span style="color: #67705a; outline: none; text-decoration: none;">Luke<br /><a href="http://www.gospelparallels.com/gospelparallels.html#1" style="color: #67705a; font-weight: bold; outline: none; text-decoration: none;">17:22-37</a></span></td><td style="vertical-align: top; width: 67px;">John<br />
<a href="http://www.gospelparallels.com/gospelparallels.html#1" style="color: #67705a; outline: none; text-decoration: none;">12:25</a></td></tr>
</tbody></table>
<br />
<br />
<br /></div>
<h4>
Finally</h4>
Thank you for stopping by. If you have anything to add please feel free. I'm constantly reevaluating things for myself as well.<br />
<br />
<h4>
By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a></h4>
See also:&nbsp;<a href="http://www.darrellwolfe.com/">www.DarrellWolfe.com</a>