---
title: 'About You'
date: '2012-05-23T15:23:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Azarea Anne Wolfe - Journal'
blogger_status: 'LIVE'
blogger_page_id: '5233479390158150509'
blogger_filename: '/p/about-you.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Azarea Anne Wolfe - Journal/feed.atom'
---

<b>Azarea Anne Wolfe</b><br />
<b>Born - TBD</b><br />
<br />
Name Meaning:<br />
<br />
<ul>
<li>Helped by God - Favored of God - Faith in Adversity&nbsp;</li>
<ul>
<li><a href="http://www.thinkbabynames.com/meaning/0/Azaria">http://www.thinkbabynames.com/meaning/0/Azaria</a></li>
</ul>
<li><b style="background-color: white; font-family: Verdana; font-size: 11px;">Azaria</b><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;</span><span style="background-color: white; font-family: Verdana; font-size: smaller;">\a-za-<a href="http://www.thinkbabynames.com/ending/0/ria" style="color: blue;">ria</a>\</span><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;as a girl's name (also used as boy's name&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/1/Azaria" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Azaria</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">), is of&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/hebrew" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Hebrew</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;origin, and the meaning of Azaria is "</span><a href="http://www.thinkbabynames.com/search/0/helped" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">helped</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;by&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/god" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">God</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">". From the male&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/biblical" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">biblical</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;name&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/1/Azariah" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Azariah</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">. Used occasionally in&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/england" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">England</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;from the&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/17th" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">17th</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/century" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">century</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">, probably in&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/honor" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">honor</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;of the&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/biblical" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">biblical</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/prophet" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">prophet</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;who recalled&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/king" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">King</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">Asa to a&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/proper" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">proper</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;observance of&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/religion" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">religion</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">. The name is borne by a number of&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/minor" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">minor</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;male</span><a href="http://www.thinkbabynames.com/search/0/character" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">characters</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;in the&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/bible" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Bible</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">. The -a ending makes it suitable for a girl's name in the&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/modern" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">modern</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;English-speaking world.</span></li>
</ul>
<ul>
<li><b style="background-color: white; font-family: Verdana; font-size: 11px;">Anne</b><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;</span><span style="background-color: white; font-family: Verdana; font-size: smaller;">\a(n)-</span><a href="http://www.thinkbabynames.com/meaning/0/Anne" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">ne</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">\ as a girl's name is a variant of&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Ann" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Ann</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;(Hebrew) and&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Hannah" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Hannah</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;(Hebrew), and the meaning of Anne is "He (God) has favored me". See also&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Aine" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Aine</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">,&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Ana" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Ana</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">,&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Anise" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Anise</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">,&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Anita" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Anita</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">,&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Annamaria" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Annamaria</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">,</span><a href="http://www.thinkbabynames.com/meaning/0/Marianne" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Marianne</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">,&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Rexanne" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Rexanne</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">,&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Roseanne" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Roseanne</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;and&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Ysanne" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Ysanne</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">.</span></li>
</ul>
<ul>
<li><b>Wolfe</b>: &nbsp;</li>
<ul>
<li>Family Motto - Fides in Adversis - Faith in Adversity</li>
<li><a href="http://www.houseofnames.com/wolfe-family-crest">http://www.houseofnames.com/wolfe-family-crest</a></li>
</ul>
</ul>
<br />
<br />
<br />
<b>Favorite Color:&nbsp;</b><br />
<b><br /></b><br />
<b><br /></b><br />
<b>Favorite Things:</b><br />
<b><br /></b><br />
<br />
<div style="text-align: center;">
<b>Family:</b></div>
<div style="text-align: center;">
<b><br /></b></div>
<div style="text-align: center;">
<b>Parents:</b></div>
<br />
<ul>
<li>Darrell Glen Wolfe</li>
<ul>
<li>Born 07/15/1980</li>
<li>Graduated from: LOL, Went to College of the Desert</li>
</ul>
</ul>
<ul>
<li>Flavia Antoinette Wolfe (Miller)</li>
<ul>
<li>Born 10/24/1981</li>
<li>Graduated from: Westmont College, Santa Barbara, CA</li>
</ul>
</ul>
<br />
<div style="text-align: center;">
<b>Siblings:</b></div>
Connor David Wolfe<br />
Preston Markus Wolfe<br />
Kaylee Debra Wolfe<br />
<br />
<br />
<div style="text-align: center;">
<b>Grandparents</b>:</div>
By Darrell:<br />
<br />
<ul>
<li>Debra Yvonne Tweedy (Previous Last Names: Wolfe/Ford) - Born 07/10/1956</li>
<ul>
<li><a href="https://www.facebook.com/debbie.tweedy/timeline/story?ut=32&amp;wstart=-2649600&amp;wend=1170316799&amp;hash=1809052794663&amp;pagefilter=3" style="background-color: white; color: #3b5998; cursor: pointer; font-family: 'lucida grande', tahoma, verdana, arial, sans-serif; font-size: 11px; line-height: 15px; text-align: left; text-decoration: none;">Graduated from CSUSB</a>&nbsp;2007</li>
<li><span style="background-color: white; color: #3b5998; font-family: 'lucida grande', tahoma, verdana, arial, sans-serif; font-size: 11px; line-height: 15px; text-align: left;">Graduated from Arcadia High School</span>&nbsp;1974</li>
<li>Hometown Arcadia, CA</li>
</ul>
</ul>
<ul>
<li>Michael Craig Wolfe - Born 05/14/1954</li>
<ul>
<li>Hometown West Covina, CA</li>
<li>Graduated From: Azusa University, Claremont School of Heresy (Theology), Cal State Fullerton</li>
</ul>
</ul>
<div>
By Flavia</div>
<ul>
<li>JoAnn Southerland (Miller - ?) - Born 12/30/19??</li>
<ul>
<li>Hometown Aurora Colorado</li>
</ul>
</ul>
<ul>
<li>David Miller &nbsp;???</li>
</ul>