---
title: 'Start Here'
date: '2021-11-12T16:52:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Biblical Hebrew Crash Course'
blogger_status: 'LIVE'
blogger_page_id: '8415050177738213364'
blogger_filename: '/p/start-here.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Biblical Hebrew Crash Course/feed.atom'
---

<h4 style="text-align: left;">In short: Hebrew Studies</h4><p style="text-align: left;">I am a Hebrew student. As of today (11/12/2021), I actually know very little (comparatively to many scholars). But this is my study-guide site. This is the site where I am compiling all of the things I'm learning about this beautiful biblical language.</p><p style="text-align: left;">Vocabulary, tools, tricks, tips, insights, and anything I found helpful while learning this language will be posted here.&nbsp;</p><p style="text-align: left;">If you are wanting to learn Hebrew, I hope some of my notes help. And I hope to connect you with access to the resources from the real experts that will help you along your journey.&nbsp;</p><p style="text-align: left;">If that's you and you want to get started today, check at the Resources page under the main menu.&nbsp;</p><p style="text-align: left;">If you'd like to know more about why I decided to study Hebrew, keep reading.</p><div><br /></div><h4 style="text-align: left;">Why Hebrew</h4><p>Have you ever thought that the Bible was "hard to understand"? Especially the "Old Testament", with all those rules and rituals and strange words?&nbsp;</p><p>Many have, even many loyal, Bible believing, church-going Christians just can't make heads-or-tails of what some passages are supposed to "mean". Even that desire for it to "mean" something is a task we need to tackle later.&nbsp;</p><p>Part of the issues is language. For many bilingual speakers (say, Spanish/English speakers, for example) it comes as no surprise that two language do not exactly map. If I say "what is your name" in English, we think that is appropriate. But word-for-word translation to Spanish would be "que as to nombre", and they would giggle at the silly Gringo for saying such a thing. They say "como te llamma", or "how are you called".&nbsp;</p><p>It is no different, even more so, with a language that was primarily developed over thousands of years ago halfway across the world. Scholar N.T. Wright often quotes that “the past is a foreign country; they do things differently there.” (Hartley, Leslie Poles, and L.P. Hartley. The Go-Between. Hamish Hamilton, 1953.). See also:&nbsp;<span style="color: #0000ee;"><u>The Need for &amp; Goals of Biblical Interpretation.</u></span></p><p><br /></p><h4 style="text-align: left;">Biblical Hebrew vs Modern Hebrew</h4><p><a href="https://www.britannica.com/topic/Hebrew-language" target="_blank">Britannica</a> notes that Hebrew fell out of daily speaking around the 200s BC(BCE) when Aramaic (a dialect of Hebrew/Semitic came into daily use. Meanwhile, formal Hebrew lived on as a literary language of the Synagogue life.&nbsp;</p><p>Hebrew actually died off almost completely as Greek then Latin swept the world. A group of scribes called <a href="https://en.wikipedia.org/wiki/Masoretes#:~:text=The%20Masoretes%20(Hebrew%3A%20%D7%91%D7%A2%D7%9C%D7%99%20%D7%94%D7%9E%D7%A1%D7%95%D7%A8%D7%94,as%20in%20Iraq%20(Babylonia)." target="_blank">Masoretes</a>&nbsp;eventually created a vowel system, as Hebrew had no written vowels. They wanted to preserve the language for future generations. Thanks to their work, Hebrew was preserved and their work served to assist <a href="https://en.wikipedia.org/wiki/Tyndale_Bible" target="_blank">Tyndale</a> in one of the earliest Hebrew &gt; English translations in the early 1500s.&nbsp;</p><p>Thanks to the Zionist movement and the return of the Jews to Israel in the 1940s, Hebrew revived as a spoken language. However, like any spoken language, it evolved. As a result, modern Hebrew and Ancient Biblical Hebrew are distant relatives. Much like Elizabethan English and Modern American English are today. While studying one can help you with the other, the differences should be acknowledged.</p><p>Therefore, this site is dedicated to the study of Ancient Biblical Hebrew, for the purposes of understanding the beautiful literary design and structure of the Bible, and the mindsets of its authors.&nbsp;</p><p><br /></p><h4 style="text-align: left;">An Ancient Language, Culture, and People</h4><div>It is also important to note, that the Bible was written by an ancient people. They did not think in terms of technology, computers, physics, or modern sensibilities of what we think is right and wrong. God chose to come to a particular people, in a particular time and space, and communicate in ways they understand.</div><div><br /></div><div>We need to acknowledge that the Bible was written for our benefit, but not to us (in the modern west). It was written by, for, and to an Ancient Near East (ANE) people called the Israelites (aka Hebrews, aka Jews). They not only spoke a foreign language, but had different customs, ideas about how the world functioned, and held very few of our modern sensibilities.</div><p>For the bible student (believer and secular alike), Hebrew is essential for understanding the thoughts the biblical authors wanted to communicate.&nbsp;</p><p><a href="https://www.britannica.com/topic/Hebrew-language" target="_blank">Britannica</a>&nbsp;defines:</p><p><i></i></p><blockquote><i>"Hebrew language, Semitic language of the Northern Central (also called Northwestern) group; it is closely related to Phoenician and Moabite, with which it is often placed by scholars in a Canaanite subgroup. Spoken in ancient times in Palestine, Hebrew was supplanted by the western dialect of Aramaic beginning about the 3rd century BC; the language continued to be used as a liturgical and literary language, however. It was revived as a spoken language in the 19th and 20th centuries and is the official language of Israel."</i></blockquote><p></p><p>Hebrew is not just a language, it is a culture, a way of life, a thought-process. For example, if I say "EARTH" in English, you likely picture a round blue/green planet floating in space, circling the sun with nine (+/-) other planets. For the ancient Israelite, they picture dirt, trees, grass, gardens, and fruit trees. The "THE HEAVENS" (which we use to translate the Hebrew word Ha-Shamayim) does not mean anything more than "up there". In fact, the word Mayim (water) is inside the word Shamayim (skies) because God separated the waters up there from the waters down here. Again, concepts of the cosmos that are not in line with our modern sensibilities.&nbsp;</p><p>Even when those people came to Roman era, speaking Aramaic on the streets and Greek in commerce and Hebrew at Synagogue; and those people and began writing biographies of Jesus, and letters to the churches, they did so from the perspective of a community saturated in their Hebrew Bible.&nbsp;</p><p>As such, all Biblical interpretation (Old Testament and New Testament) requires a mind saturated in the Hebrew Bible, lest we fail to understand what they really mean.</p><p><br /></p><h4 style="text-align: left;">Studying Hebrew</h4><p>I would like to invite you on a journey with me in studying this language.&nbsp;</p><p>&nbsp;This website is dedicated to my notes from studying biblical Hebrew as a biblical studies major. It serves as a repository of the things I've found helpful while studying Hebrew</p><p>As of 11/12/2021, I am nearly done completing my Bachelors in General Christian Studies at <a href="https://www.tku.edu/academics/undergraduate/christian-studies-degree/" target="_blank">The King's University</a> (TKU) out of Southlake, Texas. I plan to go on to complete my Masters in&nbsp;Biblical and Theological Studies at <a href="https://www.westernseminary.edu/academics/masters-degrees/ma-biblical-theological-studies" target="_blank">Western Seminary</a>.&nbsp;</p><p>I don't know everything, I don't even know much (yet). But this is my note-taking blog, and I hope to make it helpful to my own study, and by extension yours.&nbsp;</p><p>At the moment, I am using:&nbsp;<span style="text-align: center;">Basics of Biblical Hebrew Grammar by Pratico and Van Pelt, (get the</span><span style="text-align: center;">&nbsp;</span><a href="https://www.amazon.com/Basics-Biblical-Hebrew-Workbook-Third/dp/0310533554/ref=sr_1_4?keywords=basics+of+hebrew&amp;qid=1636335985&amp;qsid=146-0390380-1124221&amp;sr=8-4&amp;sres=031053349X%2C0310533554%2C0310100232%2C0369600371%2C031053576X%2C0310098424%2C0310520673%2C1097942023%2C9657493072%2C1728725631%2C9657493080%2C1097936902%2C1532601905%2C0310270227%2C1097935353%2C1097941469&amp;srpt=ABIS_BOOK" style="text-align: center;" target="_blank">workbook&nbsp;</a><span style="text-align: center;">and</span><span style="text-align: center;">&nbsp;</span><a href="https://www.amazon.com/Basics-Biblical-Hebrew-Grammar-Third/dp/031053349X/ref=sr_1_3?keywords=basics+of+hebrew&amp;qid=1636335887&amp;qsid=146-0390380-1124221&amp;sr=8-3&amp;sres=031053349X%2C0310533554%2C0310100232%2C0369600371%2C031053576X%2C0310098424%2C0310520673%2C1097942023%2C9657493072%2C1728725631%2C9657493080%2C1097936902%2C1532601905%2C0310270227%2C1097935353%2C1097941469&amp;srpt=ABIS_BOOK" style="text-align: center;" target="_blank">textbook</a><span style="text-align: center;">, they are separate). I will add to this as I move forward.&nbsp;</span></p><p><b>Shalom!&nbsp;<span face="Roboto, arial, sans-serif" style="background-color: white; color: #202124; font-size: 16px;">שָׁלוֹם‎</span><span face="Roboto, arial, sans-serif" style="background-color: white; color: #202124; font-size: 16px;">&nbsp;</span></b></p><p><b>Darrell Wolfe, Hebrew Student</b></p><p><br /></p>