---
title: 'Resources: Books & Blogs'
date: '2022-08-18T17:25:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'NoHiding.Faith'
blogger_status: 'DRAFT'
blogger_page_id: '6731879029033861052'
blogger_filename: '/p/resources-books-blogs.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/NoHiding.Faith/feed.atom'
---

<p>&nbsp;<b style="font-family: Calibri;"><span style="font-size: x-large;">BOOKS &amp; BLOGS THAT HELPED ME</span></b></p><div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.4291in;"><div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.4291in;"><span style="font-family: Calibri; font-size: 11pt;">&nbsp;</span></div><div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.4291in;"><p style="font-family: Calibri; font-size: 16pt; margin: 0in;"><span style="font-weight: bold;">Scholarly / Biblical Studies Books</span></p><p style="font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="font-family: Calibri; margin: 0in;"><b><span style="font-size: medium;">Dr. Michael S. Heiser, PhD</span></b></p><p style="font-family: Calibri; margin: 0in;">Of the three scholars who have up-ended my biblical worldvirew, Dr Heiser is at the top of the list. The Divine Council Worldview will change everything you think you know about Old Testament theology, and as a result, New Testament theology.</p><ul><li><a href="https://amzn.to/3tEvRve">Unseen Realm</a>&nbsp;is Heiser's most popular book, it talks about what really happened in Genesis 6 and why it matters to what Jesus did. (<i>Amazon affiliate link</i>)</li><li><a href="https://amzn.to/36xk357">Supernatural&nbsp;</a>is the same content but at a more accessible "layman's" level. (<i>Amazon affiliate link</i>)</li><li>Angels &amp; Demons (two books) redfine everything you've been taught to believe about the beings from the other realm.&nbsp;</li><ul><li><a href="https://amzn.to/3Nfyziu" target="_blank">Angels</a>: What the Bible Really Says About God’s Heavenly Host</li><li><a href="https://amzn.to/3Norg86" target="_blank">Demons</a>: What the Bible Really Says About the Powers of Darkness</li></ul></ul><p style="font-family: Calibri; margin: 0in;"><b><span style="font-size: medium;">Dr. N.T. (Tom) Wright, PhD</span></b></p><div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.4291in;"><br /></div><p style="font-family: Calibri; font-size: 11pt; margin: 0in;"><span style="font-family: &quot;Times New Roman&quot;; font-size: medium;">While NT Wright has written more books that I could possibly list, here are the ones I've read and endorse for biblical studies. (</span><i style="font-family: &quot;Times New Roman&quot;; font-size: medium;">Amazon affiliate links</i><span style="font-family: &quot;Times New Roman&quot;; font-size: medium;">)</span><br style="font-family: &quot;Times New Roman&quot;; font-size: medium;" /></p><ul><li><a href="https://amzn.to/3tCyZYC">The New Testament in Its World:</a>&nbsp;An Introduction to the History, Literature, and Theology of the First Christians. NT Wright and Michael F. Bird - This book is a good entry-level summary of his lifetime's worth of work on the New Testament.</li><li><a href="https://amzn.to/3uxswgV" target="_blank">Surprised by Hope</a>: Rethinking Heaven, the Resurrection, and the Mission of the Church</li><li><a href="https://amzn.to/3qDBW9r" target="_blank">Simply Jesus</a>: A New Vision of Who He Was, What He Did, and Why He Matters</li><li><a href="https://amzn.to/3utvYZN" target="_blank">How God Became King</a>: The Forgotten Story of the Gospels</li><li>Warning: REALLY Heady and written to scholars not layman, but if you can follow the arguments, it's a direct rebuke of older thinking about the "Historical Jesus" scholarship.&nbsp;<a href="https://amzn.to/3izheDh" target="_blank">Jesus Victory of God V2: Christian Origins And The Question Of God</a></li></ul><div><p style="font-family: Calibri; margin: 0in;"><b><span style="font-size: medium;">Dr. Craig Keener</span></b></p><p style="font-family: Calibri; margin: 0in;"><span style="font-size: large;"><br /></span></p><p style="font-family: Calibri; margin: 0in; text-align: left;"><span style="font-size: medium;">From his website: "Dr. Keener did his Ph.D. work in New Testament and Christian Origins at Duke University and is known for his work as a New Testament scholar on Bible background (commentaries on the New Testament in its early Jewish and Greco-Roman settings). Well over a million of his thirty-plus books are in circulation and have won thirteen national and international awards." -<i>&nbsp;(some Amazon affiliate links)</i></span></p><ul><p style="margin: 0in;"><span style="font-size: medium;"><br /></span></p><li>Check out his free resources&nbsp;<a href="https://craigkeener.com/free-resources/" target="_blank">HERE</a>.</li><li>Especially -&nbsp;</li><ul><li><a href="https://craigkeener.com/wp-content/uploads/2021/11/Bible-In-Its-Context-revised-8-14-14-for-Snowfall.pdf" target="_blank">The Bible in Its Context</a>: How to Improve Your Study of the Scriptures</li><li><a href="https://craigkeener.com/wp-content/uploads/2020/05/EJ_2001_02_Spring_Keener-1.pdf" target="_blank">Women in Ministry</a></li></ul></ul></div><div><br /></div><div><br /></div><b><span style="font-size: medium;">Other Titles<br /></span></b><ul><li><a href="https://amzn.to/3urVdeT">The Pentateuch as Narrative</a>: A Biblical-Theological Commentary (1995) ISBN 978-0310574217, by&nbsp;John Sailhamer (<i>Amazon affiliate link</i>)</li><li><a href="https://amzn.to/3iA9tN9">Sitting at the Feet of Rabbi Jesus</a>: How the Jewishness of Jesus Can Transform Your Faith, by Ann Spangler (Author), Lois Tverberg (Author) (<i>Amazon affiliate link</i>)</li><li><a href="https://amzn.to/3ulWNiw">Grasping God’s Word</a>: A Hand-On Approach to Reading, Interpreting, and Applying the Bible. 4th Edition. Grand Rapids: Zondervan, 2012. ISBN 978-0-310-10917-4, by Daniel Hayes and J. Scott Duvall (<i>Amazon affiliate link</i>)</li><li><a href="https://amzn.to/3LjYpjL">Reading and Understanding the Bible.&nbsp;</a>New York: Oxford University Press, 2015. ISBN 978-0199340576, by Ben Witherington III (<i>Amazon affiliate link</i>)</li><li><a href="https://amzn.to/3iHTTPv">How to Read the Bible for All It’s Worth.</a>&nbsp;Grand Rapids: Zondervan, 2003., by Gordon Fee and Douglas Stuart (<i>Amazon affiliate link</i>)</li><li><a href="https://amzn.to/3uwsGF2">How to Read the Bible Book by Book</a>: A Guided Tour, by Gordon Fee and Douglas Stuart (<i>Amazon affiliate link</i>)</li><li><a href="https://amzn.to/3JWlatT">A Basic Guide to Interpreting the Bible: Playing by the Rules</a>. Grand Rapids: Baker, 1994, by Robert Stein (<i>Amazon affiliate link</i>)</li><li><a href="https://amzn.to/3wHs4PF">Elements of a Christian Worldview</a>&nbsp;by Michael Palmer (<i>Amazon affiliate link</i>)</li><li><a href="https://amzn.to/3tEtYid">Saving the Bible from Ourselves</a>: Learning to Read and Live the Bible Well by Glenn R. Paauw (<i>Amazon affiliate link</i>)</li><li><a href="https://amzn.to/381XtSK" target="_blank">Israel Matters</a>: Why Christians Must Think Differently about the People and the Land, by Gerald R. McDermott&nbsp; (<i>Amazon affiliate link</i>)</li></ul></div><p style="font-family: Calibri; font-size: 16pt; margin: 0in;"><span style="font-weight: bold;">Fiction Books</span></p><p style="font-family: Calibri; font-size: 11pt; margin: 0in;">Some fiction books that helped me see the heart of God for his humans:</p><span style="font-weight: bold;">Single Titles:</span><ul><li><a href="https://amzn.to/3uwtgTe">TheShack</a>, by William P. Young (<i>Amazon affiliate link</i>)</li></ul><span style="font-weight: bold;">Author Ted Dekker&nbsp;</span>(<i>Amazon affiliate link</i>)<ul><li><a href="https://amzn.to/3LgSOe0">TheCircle Series</a>&nbsp;(White, Green, Red, Black), by Ted Dekker</li><li><a href="https://amzn.to/3NfY4QV">Thr3e</a>, by Ted Dekker</li><li><a href="https://amzn.to/3IzSKUJ">Hacker:The Outlaw Chronicles</a>, by Ted Dekker</li></ul><span style="font-weight: bold;">Author Bill Myers&nbsp;</span>(<i>Amazon affiliate link</i>)<ul><li><a href="https://amzn.to/3JGLhop">Eli</a>, by Bill Myers</li><li><a href="https://amzn.to/3NhQQfj">Bloodof Heaven (Fire of Heaven Trilogy Book 1)</a>, Bill Myers</li></ul><b>Author Lauren Stinton&nbsp;</b>(<i>Amazon affiliate link</i>)<b><br /></b><ul><li><a href="https://amzn.to/3JBFSPk">TheHouse of Elah</a>&nbsp;(3 book series), by Lauren Stinton</li><li><a href="https://amzn.to/3tEDwcR">TheHamal Books</a>, by Lauren Stinton</li></ul>And... some fiction books that are not explicitly biblical but helped me enjoy that part of our reality that we all feel but can't touch, that part just beyond the veil.<br /></div><div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.4291in;"><br /></div><div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.4291in;"><b>Author K.M Wieland&nbsp;</b>(<i>Amazon affiliate link</i>)<b><br /></b><ul><li><a href="https://amzn.to/3iDDYli">Dreamlander</a>, by K.M. Wieland</li></ul><b>Author Brandon Sanderson&nbsp;</b>(<i>Amazon affiliate link</i>)<ul><li><a href="https://amzn.to/37UYls5">Mistborn (series)</a>, by Brandon Sanderson</li></ul><p style="font-family: Calibri; font-size: 11pt; margin: 0in;"><br /></p></div>