---
title: 'The NoHiding Bible School for Normal People'
date: '2022-06-17T16:26:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'NoHiding.Faith'
blogger_status: 'LIVE'
blogger_page_id: '2692190250044870352'
blogger_filename: '/p/the-nohiding-bible-school-for-normal.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/NoHiding.Faith/feed.atom'
---

<p><b><span style="font-size: large;">Under Construction&nbsp;</span></b></p><p><br /></p><p><i>If I were going to teach a Bible School for Layman (and Laywomen), this is brain dump for what I'd need to cover ... under construction as I braind storm.....&nbsp;</i></p><p><br /></p><p><b>****************&nbsp;</b></p><p><b>Biblical Studies&nbsp; - What is the Bible and how do we read it?</b></p><p><b>****************&nbsp;</b></p><p><br /></p><p><b>What IS the Bible anyway?&nbsp;</b></p><p>How was it constructed?&nbsp;</p><p>How was it used/read?&nbsp;</p><p>How was it copied and kept?&nbsp;</p><p>Introduction to OT &amp; NT&nbsp;</p><p><br /></p><p><b>How do we interpret the Bible?&nbsp;&nbsp;</b></p><p>What is Exegesis and Hermeneutics?&nbsp;&nbsp;</p><p>Various approaches that have been applied historically?&nbsp;&nbsp;</p><p>How do various approaches color or tint the way we see the text?&nbsp;&nbsp;</p><p>Are some approaches more valid than others (wrong, right, or just different)?&nbsp;</p><p><br /></p><p><b>Worldview&nbsp;</b></p><p>What is a Worldview?&nbsp;</p><p>What is your Worldview in the modern era?&nbsp;</p><p>What was the Worldview of the Ancient Near East (ANE), Atiquity, Rome, and the Biblical Authors? How are they similar and different?&nbsp;&nbsp;</p><p>What does it mean to think like the biblical authors, how might that differ from the traditions imposed on them by modern western Christianity?&nbsp;</p><p>In what ways do historical Christians like Augustine, Luther, Calvin, Arminius, Tyndale, Wesley, Graham, C.S. Lewis, and others share a common worldview and in what ways do each differ as a result of their unique background, experiences, time and place in history?&nbsp;&nbsp;</p><p>&nbsp;</p><p><b>Old Testament Survey&nbsp;</b></p><p>Pentateuch (Gen-Deut) Books of Moses&nbsp;&nbsp;</p><p>Genesis 1-11&nbsp;</p><p>Genesis 12-end&nbsp;</p><p>Prophets&nbsp;</p><p>Historicals&nbsp;</p><p>Major v Minor is size not importance&nbsp;</p><p><br /></p><p>Writings&nbsp;</p><p>The wisdom writings that reflect on the history of Israel.&nbsp;</p><p>&nbsp;</p><p><b>New Testament Survey&nbsp;</b></p><p>The Gospels&nbsp;</p><p>Ancient Biographies&nbsp;&nbsp;</p><p>The Life of Rabbi Yeshua (Jesus) HaMeshiach (The Anointed One, The Christ).&nbsp;&nbsp;</p><p>The Life of Rabbinic Disciples (The Twelve, the 170, and others Jesus touched).&nbsp;</p><p>The Jewish and Roman backdrop to these stories&nbsp;</p><p>Rabbinic Traditions (Sewing Pearls) and the role of Parables&nbsp;</p><p><br /></p><p><b>Second Writings&nbsp;</b></p><p>Epistles – Working out what it meant to be a Jewish Messianich movement in the Roman empire with Mixed Jewish/Gentile followers.&nbsp;&nbsp;</p><p>The Jewish and Roman backdrop to these stories&nbsp;</p><p><br /></p><p><b>Intro to the Apocalypse&nbsp;&nbsp;</b></p><p>The Apocalypse as a Genre and other examples of the genre&nbsp;</p><p>The literary structure and story arch of The Revelation of Jesus to John&nbsp;</p><p>The Seven Letters&nbsp;</p><p>The Apocalypse Arch – Rev 3-22&nbsp;</p><p>Intro to the "Old Testament" (Hebrew Scripture) backgrounds and allusions to John's writing&nbsp;</p><p>The Message of Revelation (regardless of one's view of eschatology)&nbsp;</p><p>Daniel and Ezekiel in Revelation&nbsp;</p><p>The possible impacts of good exegesis on Eschatology&nbsp;&nbsp;</p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p>&nbsp;<b>****************&nbsp;</b></p><p><b>Judeo-Christian History&nbsp;</b></p><div><b>****************&nbsp;</b></div><p>Jewish History&nbsp;&nbsp;</p><p>Adam to Abraham, Abraham to Exile, Exile to 1A.D., 1-200 A.D., 200-1800 A.D., 1800-2022 A.D.&nbsp;</p><p><br /></p><p><b>Jewish Messianic Movements -&nbsp;&nbsp;</b></p><p>1-200 A.D., 200-1800 A.D., 1800-2022 A.D.&nbsp;</p><p><br /></p><p><b>Non-Jewish/Gentile Jesus Movements&nbsp;</b></p><p>Jesus Movement 1-100 A.D.&nbsp;&nbsp;</p><p>Jesus Movement 100-400 A.D.&nbsp;&nbsp;</p><p>Catholic Christianity, Greek Orthodox Christianity, and Other movements 300-1500 A.D. Tertulian, Augustine, Jerome, Constantine, etc.&nbsp;</p><p>Protestant Christianity 1500-1800 – Luther, Calvin, Arminius, Gutenberg, Tyndale,&nbsp;&nbsp;</p><p>Protestant Christianity 1800-1900 -&nbsp;&nbsp;</p><p><br /></p><p><b>American Centric Christianity&nbsp;</b></p><p>Protestant Christianity 1900-2022 – Pentecostal &amp; Charismatic Movements&nbsp;</p><p>Protestant Christianity 1900-2022 – Mainline Denominations&nbsp;</p><p>Protestant Christianity 1900-2022 – Non-Denominational Movements&nbsp;</p><p><br /></p><p><b>Non-American Centric Christianity&nbsp;</b></p><p>Protestant Christianity 1900-2022 – Non-American Movements&nbsp;</p><p><br /></p><p><b>Theology – Theos (God) ology (study) - The Study of God&nbsp;</b></p><p>Jewish, Catholic, Orthodox, Protestant, "Christian", Messianic, theological studies&nbsp;</p><p>The various ways different traditions have viewed God and the Bible&nbsp;</p><p>To the Jew First / Mixed Jewish/Gentile Family of God&nbsp;</p><p>Systematic Theology (barf), Biblbical Theology, Etc.</p><p>Apologetics (barf)&nbsp;</p><p><br /></p><p><b>****************&nbsp;</b></p><p><b>Biblical Studies - Languges&nbsp;</b></p><p><b>****************&nbsp;</b></p><p><b>What you need to know about lagnuages, as a layman</b></p><p><b><br /></b></p><p><b>The Languages of the Bible</b></p><p>Hebrew (&amp; Aramaic)</p><p>Greek</p><p><b><br /></b></p><p><b>The Languages of the Ancient Near East</b></p><p>Ugaritic</p><p>Akadian</p><p>Egyptian</p><p><br /></p><p><b>The Languages of Theology&nbsp;</b></p><p>English</p><p>Latin</p><p>German</p><p>Etheopic&nbsp;</p><p><br /></p><p><br /></p><p><b>****************&nbsp;</b></p><p><b>Practical Application – Life Transformation&nbsp;</b></p><p><b>****************&nbsp;</b></p><p>Biblical/Lay Counseling vs Professional Counseling</p><p><br /></p><p>How people change&nbsp;</p><p>Two Trees&nbsp;</p><p>Parable of the Acrobat&nbsp;</p><p>How the Bible changes us, and how it doesn't.&nbsp;&nbsp;</p><p>Human Needs&nbsp;</p><p>Stronghold Cycles&nbsp;</p><p>Human Communication Emotional/Fact Over/Covert&nbsp;</p><p>Behavior vs Identity&nbsp;</p><p>Get Curious about That&nbsp;</p><p><br /></p><p><br /></p><p><b>****************&nbsp;</b></p><p><b>Biblical Studies - Study of specific books and groupings of Books&nbsp;&nbsp;</b></p><p><b>****************&nbsp;</b></p><p><b>The Hebrew Scriptures (aka Old Testament)&nbsp;</b></p><p>Genesis</p><p>Exodus</p><p>Leviticus</p><p>Numbers</p><p>Deuteronomy</p><p>Joshua</p><p>Judges</p><p>Ruth</p><p>1 Samuel</p><p>2 Samuel</p><p>1 Kings</p><p>2 Kings</p><p>1 Chronicles</p><p>2 Chronicles</p><p>Ezra</p><p>Nehemiah</p><p>Esther</p><p>Job</p><p>Psalms</p><p>Proverbs</p><p>Ecclesiastes</p><p>Song of Solomon (or Song of Songs)</p><p>Isaiah</p><p>Jeremiah</p><p>Lamentations</p><p>Ezekiel</p><p>Daniel</p><p>Hosea</p><p>Joel</p><p>Amos</p><p>Obadiah</p><p>Jonah</p><p>Micah</p><p>Nahum</p><p>Habakkuk</p><p>Zephaniah</p><p>Haggai</p><p>Zechariah</p><p>Malachi</p><p><b><br /></b></p><p><b>The&nbsp;Gospels &amp; Second Writings &amp; Apocalypse (aka New Testament)&nbsp;</b></p><p>Matthew</p><p>Mark</p><p>Luke</p><p>John</p><p>Acts of the Apostles</p><p>Romans</p><p>1 Corinthians</p><p>2 Corinthians</p><p>Galatians</p><p>Ephesians</p><p>Philippians</p><p>Colossians</p><p>1 Thessalonians</p><p>2 Thessalonians</p><p>1 Timothy</p><p>2 Timothy</p><p>Titus</p><p>Philemon</p><p>Hebrews</p><p>James</p><p>1 Peter</p><p>2 Peter</p><p>1 John</p><p>2 John</p><p>3 John</p><p>Jude</p><p>Revelation</p><p><br /></p><p><b>Other Non-Biblical Books you should know</b></p><p><br /></p><p>The Apocrypha/Deuterocanonical</p><p>Tobit</p><p>Judith</p><p>Additions to the Book of Esther</p><p>Wisdom of Solomon</p><p>Ecclesiasticus</p><p>Baruch</p><p>The Letter of Jeremiah</p><p>The Prayer of Azariah and the Song of the Three Jews</p><p>Susanna</p><p>Bel and the Dragon</p><p>1 Maccabees</p><p>2 Maccabees</p><p>1 Esdras</p><p>Prayer of Manasseh</p><p>Psalm 151</p><p>3 Maccabees</p><p>2 Esdras</p><p>4 Maccabees</p><p>1 Enoch</p><p><br /></p><p><br /></p><p><br /></p>