---
title: 'The Sods Shop'
date: '2016-06-05T22:00:00.0030000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Cornerstone Restaurants'
blogger_status: 'LIVE'
blogger_page_id: '6373234686176837158'
blogger_filename: '/p/the-sods-shop.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Cornerstone Restaurants/feed.atom'
---

<br />My wife and I have always been looking for a fun place to go, or even hang out, that is nice, family friendly, and ALCOHOL FREE!&nbsp;<div>
<br /></div>
<div>
Even some of our favorite restaurants have bars and sports on the TV. It just seems like there is no place for church goers, Alcoholics Anonymous (A.A.), and other members of the alcohol free society to go and truly relax and enjoy themselves.<br /><br />Then as we were pondering  what we wanted to do with out lives among our many tasks was that we felt called to provide that type on restaurant environment to others.</div>
<div>
<br /></div>
<h4>
The Soda Shop</h4>
<div>
<ul>
<li>A 21st Century Soda Fountain.&nbsp;</li>
<li>The worlds largest selection of on sodas, on draft, in the bottle, in the can.&nbsp;</li>
</ul>
</div>
<div>
In times gone by, the Soda Fountain was the place people went to relax, enjoy each other's company, and catch up on town news. The Soda Jerk was the bartender of children, tea-toddlers, and other people looking for a respectable place to enjoy themselves.&nbsp;</div>
<div>
<br /></div>
<div>
They also served Ice Cream Floats, and Diner Food.</div>
<div>
<br /></div>
<div>
Articles:</div>
<div>
<br /></div>
<div>
The History of Soda<br /><br />The History of the Soda Fountain.</div>
