---
title: 'Fed By Faith'
date: '2013-04-15T03:48:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_page_id: '8045349539390461920'
blogger_filename: '/p/fed-by-faith.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<b>This is a Faith Project Development Site.&nbsp;</b><br />
<br />
I intend to focus and target my faith at accomplishing something small and specific. To learn the practical ins and outs of walking by faith. Before I can speak to mountains and tell them to move I will start with mole hills. I know that I will make mistakes, have periods of doubt, and I am making that available to any passerby that finds this site. I'm not advertising the site, at least not in the&nbsp;beginning. However making it available adds a certain vulnerability and accountability.<br />
<br />
If you find this site and found it helpful at all please email me: darrellgwolfe@gmail.com. I may not get it right away, but I will try to read it eventually.<br />
<br />
<b>Background:</b><br />
<br />
<br />
My God takes even great pleasure in my prosperity because I am his child and not just his servant. Faith is the substance of things. All material in this or any universe was brought into being by faith. God did not create the world from nothing he created it from that which is not seen. Faith is the unseen substance of all material. The Word (which is Jesus) brings it to pass. Hope (dreams and visions from God) are it's blueprint, and Love (which is God and the power behind it all) powers the development.<br />
<br />
<b>As a Building</b>:<br />
Faith is the lumber, Hope is the blueprint, and Love is the&nbsp;power tool.<br />
<b>As an Air&nbsp;Conditioner</b>:<br />
Faith is the Air Unit, Hope is the thermostat, and Love is the electricity and wiring.<br />
<br />
<br />
<b>Faith, Hope, and Love.</b>.. the greatest of these is Love...(1 Corinthians 13:13)<br />
<br />
<a href="http://fedbyfaith.blogspot.com/2013/04/fed-by-faith-verses.html" target="_blank">Other Fed By Faith Verses for Study...</a><br />
<ul style="list-style-image: initial; list-style-position: initial; list-style-type: none; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 10px; padding-bottom: 0px; padding-left: 0px; padding-right: 15px; padding-top: 0px;">
</ul>
