---
title: '2014 The Vision'
date: '2014-01-06T15:33:00.0020000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_page_id: '7919587754745105569'
blogger_filename: '/p/2014-vision.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<h3 style="text-align: center;">
2014 The Vision</h3>
<h4>
Family</h4>
<div>
<ul>
<li><b>Marriage</b>:&nbsp;</li>
<ul>
<li><b>Go meet&nbsp;</b>with marriage counselors/couples.&nbsp;</li>
<li><b>Attend&nbsp;</b>marriage seminars.&nbsp;</li>
<li><b>Read&nbsp;</b>Marriage books.&nbsp;</li>
</ul>
<li><b>Kids</b>:</li>
<ul>
<li><b>Listen&nbsp;</b>when Connor asks a question, don't interupt him and give him an answer without letting him be heard.</li>
<li><b>Pay attention</b>&nbsp;to Preston and draw him out of his shell with questions and do things together.&nbsp;</li>
<li><b>Spend TIME</b>&nbsp;with both of them, together and separately.</li>
</ul>
<li><b>Vacations</b>. Go on SELF FUNDED Vacations</li>
</ul>
</div>
<h4>
Health</h4>
<div>
<ul>
<li><b>Physical Fitness</b></li>
<ul>
<li><b>Get Fit</b></li>
<ul>
<li>155 Lbs</li>
<li>Run One Mile without tiring.</li>
</ul>
</ul>
<li><b>Spiritual Fitness</b></li>
<ul>
<li><b>Morning Routine</b></li>
<ul>
<li>10 Minutes of Quiet. Play Rain sounds and allow mind to settle into the day. Not praying, reading, or thinking about anything in particular. But open to what Jesus might say during that time.&nbsp;</li>
<li>10 Minutes to Journal (either GNotes or Blogger)</li>
<li>10 Minutes to Pray Actively.&nbsp;</li>
<li>10 Minutes to Read the daily devotional and The Word.</li>
</ul>
<li><b>Meet with Jack</b></li>
<ul>
<li>2nd Wednesday of each month.&nbsp;</li>
</ul>
<li>???</li>
</ul>
</ul>
</div>
<div>
<b>Financial</b></div>
<div>
<ul>
<li><b>Get Debt Free</b></li>
<li><b>Go through Financial Peace with Flavia</b></li>
</ul>
</div>
<h4>
Income</h4>
<div>
<ul>
<li><b>One Job</b></li>
<ul>
<li>Make $50,000. Tailor Fit. Perfect Schedule for my other tasks.&nbsp;</li>
</ul>
<li><b>Self Employed.&nbsp;</b></li>
<ul>
<li>First Step. Get some income coming in from a source outside of a JOB.&nbsp;</li>
</ul>
</ul>
</div>
<h4>
My Ministry</h4>
<div>
<ul>
<li><b>Write</b></li>
<ul>
<li>Write Daily at DW.Com. Mostly to develop my voice, and provide valuable information.&nbsp;</li>
<li>Write Weekly Updates to Texas Living as a ministry to people who want to discover family friendly things to do in Texas.&nbsp;</li>
<li>Write at least weekly at Author Fun.&nbsp;</li>
</ul>
<li><b>Music</b></li>
<ul>
<li>Attend Audio 102</li>
<li>Do Something Musical at weekly.&nbsp;</li>
</ul>
</ul>
</div>
<div>
<br /></div>
<div>
<br /></div>
<h4>
By &nbsp;2018</h4>
<div>
<ul>
<li><b>Full Time&nbsp;</b>in the Ministry He called me to.</li>
<li><b>Sowed&nbsp;</b>the Zavala House (debt free) into the right people/person</li>
<li><b>New Property</b>. Debt Free. 10 Acres. Lake. Separate Office/Cabin.&nbsp;</li>
</ul>
</div>
<div>
<br /></div>
<h4>
The Future...</h4>
<div>
<ul>
<li><b>Be Preaching/Ministering/Teaching/(Pastoring?)</b></li>
<ul>
<li>Kingdom of God Ministries?</li>
<li>Property in Indio, CA?</li>
<li>Traveling Ministry?</li>
<li>Written and Distributed Books</li>
<li>Full Time Blogger</li>
<li>Laying hands on the sick and mentally ill and they recover!</li>
</ul>
<li><b>Be Debt Free</b></li>
<ul>
<li>Totally Debt Free</li>
</ul>
<li><b>Own Businesses</b></li>
<ul>
<li>Coffee Shops</li>
<li>Cornerstone&nbsp;Concepts Restaurants&nbsp;</li>
<ul>
<li>Soda Shop</li>
<li>Space Theme</li>
</ul>
<li>As Seed</li>
<ul>
<li>Start and give away all or parts of businesses to others.&nbsp;</li>
<li>Christian Venture Capitalists as a ministry.&nbsp;</li>
</ul>
</ul>
<li><b>Own Properties</b></li>
<ul>
<li>For the Wolfe Family</li>
<ul>
<li>Ranch Property for us</li>
<li>Cabin in ID</li>
<li>Disney Timeshare?</li>
</ul>
<li>As Investments</li>
<ul>
<li>Rental Homes</li>
<li>Rental Condo's</li>
</ul>
<li>As Seed</li>
<ul>
<li>Sow Homes Away</li>
</ul>
</ul>
</ul>
</div>
<div>
<br /></div>
<div>
To Be Edited and Reviewed on a regular basis... DW 04/14/2013</div>
