---
title: 'Daily Routine'
date: '2014-07-06T15:17:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_page_id: '8276637019018362461'
blogger_filename: '/p/my-daily-routine-set-day-in-order-5-10.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<h1>
My Daily Routine</h1>
<div>
<h4>
Routine: All in one journal entry</h4>
<ul>
<li>BE STILL: It must start with BE STILL before going to writing, bible devotional, or other things. Prayer will be involved, but it will be listening, not speaking.&nbsp;</li>
<li>PRAYER: This is the time I do some talking, but still listening also.&nbsp;</li>
<ul>
<li>Prayers, Petitions, and Thanksgivings be made on behalf of: FIRSTLY&gt;</li>
<ul>
<li>For all people</li>
<li>Then Kings, Leaders, Those in Authority</li>
<ul>
<li>SO THAT we may lead a tranquil and quite life in all godliness and dignity.&nbsp;</li>
</ul>
</ul>
<li>God desires all men to:</li>
<ul>
<li>Be saved</li>
</ul>
<br />
<ul>
<li>Come to the knowledge of the Truth.&nbsp;</li>
</ul>
<li><i><a href="http://biblehub.com/context/1_timothy/2-1.htm" target="_blank"><b>1 Timothy 2</b></a></i></li>
<li><i>1 First of all, then, I urge that entreaties and prayers, petitions and thanksgivings, be made on behalf of all men, 2 for kings and all who are in authority, so that we may lead a tranquil and quiet life in all godliness and dignity. 3 This is good and acceptable in the sight of God our Savior, 4 who desires all men to be saved and to come to the knowledge of the truth. 5 For there is one God, and one mediator also between God and men, the man Christ Jesus, 6 who gave Himself as a ransom for all, the testimony given at the proper time. 7 For this I was appointed a preacher and an apostle (I am telling the truth, I am not lying) as a teacher of the Gentiles in faith and truth. 8 Therefore I want the men in every place to pray, lifting up holy hands, without wrath and dissension.</i></li>
</ul>
</ul>
<ul>
<li>BIBLE: Instead of a bible devotional, I'm going to do a bible study. Take one of Kenneth's study notes from the front of my bible and do those.</li>
</ul>
<br />
<ul>
<li>JOURNAL entry will include all of the above, and anything else on my mind at the time. Take a moment to jot down:</li>
<ul>
<li>How you are feeling:</li>
<li>How you are believing:</li>
<li>What's happening in your life right now:</li>
</ul>
</ul>
<br />
<blockquote class="tr_bq">
<br /></blockquote>
</div>
