---
title: 'Answers Page'
date: '2016-06-19T01:39:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_page_id: '587239992542396726'
blogger_filename: '/p/answers-page.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<blockquote class="tr_bq">
This page is to document my life, year by year, and see the ups, downs, and sideways of it. To be reviewed as often as I need a perspective switch.</blockquote>
<br />
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------<br />
<div>
<br />
<br />
2016 In review - 01.31.17<br />
<br />
<br />
<br />
<br />
<br />
<h4>
Spiritual</h4>
<ul>
<li><br /></li>
</ul>
<h4>
Family</h4>
<ul>
<li>Connor enjoyed his third year at Dry Gulch Camp</li>
<li><br /></li>
</ul>
<h4>
Professional</h4>
<ul>
<li>I survived the Chaos of 2016 in WFDS OTP</li>
<li><br /></li>
</ul>
<h4>
Financial</h4>
<ul>
<li>We made $51,000 in 2015.</li>
<li><br /></li>
</ul>
<h4>
Writing</h4>
<ul>
<li><br /></li>
</ul>
<br />
<h4>
Music</h4>
<ul>
<li><br /></li>
</ul>
<br />
<br />
<br />
<br />
<div style="-webkit-text-stroke-width: 0px; color: black; font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px;">
</div>
<br />
<div style="-webkit-text-stroke-width: 0px; color: black; font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; margin: 0px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px;">
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</div>
</div>
<br />
2014-2015 In review - 01.31.16<br />
<h4>
Spiritual</h4>
<ul>
<li>... Groggy... Waking up to some things slowly, but... spiritually asleep. I know that a relationship with the Holy Spirit every morning and night is the only chance I have of saving my life before it's destroyed, but I still don't get up and put in the effort.&nbsp;</li>
</ul>
<br />
<ul>
<li>Most days... I wish I were dead, and I'm mad that God won't take me. I'd never kill myself, but I'm certainly not happy to be alive either. If God came down and gave me the choice, I'd leave this earth without a second thought about anything or anyone else. I HATE living, I always have... and I'm fearful that I always will.&nbsp;</li>
<li>Freedom Ministries, Kairos, Personal Ministry, Bob Hamp... they've all given me glimmers of hope for the first time in my 35 years of living... but only a glimmer. I've gone from 100% sure I'll never have more than an exist-for-the-sake-of-existing emotion, to a 90% sureness of that, and a 10% belief that it could change. I guess that's progress.</li>
</ul>
<br />
<br />
<h4>
Family</h4>
<ul>
<li>??????????????</li>
<li>This is THE question mark of my life. I feel Bi-Polar.&nbsp;</li>
<li>There are days that I feel a bond to these three under my roof. I feel that Flavia is my best friend, and the kids are great kids.&nbsp;</li>
<li>In a moment, in the blink of an eye, in the same day even, my emotions turn violently in my heart, I want them all to leave for Idaho. I then want to sell this house (and the associated pressure of bills) by a Tiny House and live alone somewhere.</li>
</ul>
<br />
<ul>
<li>Mustbethistalltoride.com is a great blog that's given us insight into where I'm missing her intentions and heart. BUT... CAN I turn this around? Can I be anything more than an emotional time bomb that's only half engaged (or less) in any activity involving my family? I honestly don't know. I don't know if I CAN be anything she needs me to be.&nbsp;</li>
</ul>
<br />
<h4>
Professional</h4>
<ul>
<li><b>I was hired at the Wells Fargo Dealer Services - Office of the President (OTP) in May 2014. There was favor there. The hiring manager wasn't going to bring me on, but the other two interviewers insisted that she bring me on.&nbsp;</b></li>
</ul>
<ul>
<li><b>I was then promoted to Team Lead and Dealer Complaints Specialist on February 12, 2015. In just a few days I will have been the Team Lead for a year.&nbsp;</b></li>
</ul>
<ul>
<li>The money was tight, because it was feast on OT weeks, and famine on non-OT weeks.</li>
</ul>
<ul>
<li>Things are deteriorating at OTP, and I am faced with a struggle I have faced times before.&nbsp;</li>
<ul>
<li>Do I stay, promote to manager and embrace a leadership role?</li>
<ul>
<li>If I stay, I may be able to lock in a Salary of $50,000, but I KNOW I'll work 50-60 hours. I'll struggle under the current leadership model (or lack thereof). But I'll have the opportunity to grow as a leader, and influence the creation of this new and better version of this office.</li>
</ul>
<li>Do I go, to a potentially more lucrative position (Compliance Consultant 2)?</li>
<ul>
<li>If I go to Compliance, I am facing a new world, again. I don't know what favor I will have there, or what challenges I will face. It's possible it will be less pressure, but it's possible it will be more. &nbsp;I'm much more likely to lock in a Salary closer to $60,000 (midpoint it $70,000). The Salary is in line with the goal I'm working toward. The position offers extreme independence, long term single-focused projects, and does not require I manage a team. It's more appealing to me at this point in time (01/31/16).</li>
</ul>
</ul>
</ul>
<br />
<h4>
Financial</h4>
<ul>
<li>Behind on several bills... still. I've been behind on bills as long as I've had any. I was over drafting when I was single. I'm behind on major bills for my entire 12 years of marriage. I'm tired of being poor.</li>
</ul>
<br />
<ul>
<li>That being said, last year (2015) I made $51,101.84 (including overtime). I reached a milestone. This was the first year that I made over $50,000 with one job. That was a goal, and it's been reached.&nbsp;</li>
</ul>
<ul>
<li>Next Goal: $60,000 Salary, One Job, less than 45 hours a week average worked. Every Bill paid ahead one month, two debt free cars in perfect working order ahead on maintenance, and $5,000 in savings.</li>
</ul>
<br />
<h4>
Writing</h4>
<ul>
<li>I started a novel, I'm reading a lot about writing. I'm not writing much... at all.</li>
</ul>
<br />
<h4>
Music</h4>
<ul>
<li>Took Audio 101 in Fall 2013. Shortly after January 2014 I made a tough decision. Although I enjoy Audio, it's not a career path for me. At least, not in any traditional sense.&nbsp;</li>
<ul>
<li>I'm not going to be a musician on stage like Garth Brooks, Michael Jackson, or Bryan Duncan. I don't have the musical study, physical mechanics, or (most importantly) the passion for it. I just don't enjoy it enough to do it full time.</li>
</ul>
<br />
<ul>
<li>I'm not going to be an Audio Technician. Those guys are lucky to get paid $15.00/Hr. I enjoy Audio. I may want to get a studio and mix as a hobby. Maybe something would come of it, but I just don't see myself as a "Musician" or "Audio Guy".&nbsp;</li>
<li>Music is a passing hobby, and less even that anymore (01/31/16).</li>
</ul>
</ul>
<br />
<br />
<br />
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------<br />
<h4>
2014</h4>
<h4>
Spiritual</h4>
<ul>
<li>Best January ever so far, 01/08</li>
</ul>
<br />
<h4>
Family</h4>
<ul>
<li>My relationship with Flavia is reborn... we're like honeymooners</li>
</ul>
<br />
<br />
<h4>
Professional</h4>
<ul>
<li>Still at Wells Fargo... for now</li>
</ul>
<br />
<h4>
Financial</h4>
<ul>
<li>Behind on several bills, BUT GOD has started cleaning it up and giving us favor with the student loan people and now Mortgage too.&nbsp;</li>
</ul>
<br />
<h4>
Writing</h4>
<ul>
<li>Clarifying the blogs...</li>
</ul>
<br />
<h4>
Music</h4>
<ul>
<li>Audio 102 Starts February</li>
</ul>
<br />
<br />
<br />
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------<br />
<h4>
2013</h4>
<ul>
<li><b>Personal</b></li>
<ul>
<li>Wife and I talked after Robert Morris' message on Freedom. Set apt to work things out. Healing and Recovery are begun. 12/29/2013</li>
</ul>
<li><b>Music</b></li>
<ul>
<li>Music Schools</li>
<ul>
<li>Felt led to visit Gateway Church in Southlake yesterday. They have a School of Tech Arts, $500 per class. World Class equipment and schooling, tours of top class facilities, etc. <a href="http://techartstraining.com/" target="_blank">techartstraining.com</a>. Emailing for more information.&nbsp;</li>
<li>Starting School of the Tech Arts August 22nd! Paid!</li>
</ul>
<li>14 Forty</li>
<ul>
<li>Learning more about Audio from Jordan, Blogs, and MP3's than I have in the last 32 years.&nbsp;</li>
</ul>
<li>Guitar/Music</li>
<ul>
<li>Meeting with Jeff Spangler Tomorrow (04/15/2013) to talk about guitar lessons/evaluations.&nbsp;</li>
</ul>
</ul>
<li><b>Writing</b></li>
<ul>
<li><b>New Plans</b></li>
<ul>
<li><b>Write&nbsp;@DarrellWolfe</b></li>
<li><b>Write Texas Living</b></li>
<li><b>Write a Fiction Blog: Author's Fun</b></li>
<li><b>Projects abandoned/altered/put on back burner</b></li>
<ul>
<li><b>N2 Good Success</b></li>
<ul>
<li>Started N2GS my new Blog Brand.</li>
<li>Focuses on my Core "Helping People&nbsp;Achieve&nbsp;Good Success"</li>
</ul>
<li><b>Texas Living Info</b></li>
<ul>
<li>Redefined and Relaunched TLI on Blogger</li>
</ul>
<li><b>Call To Excellence Favor</b></li>
<ul>
<li>Met with Jack to keep discussing Call to Excellence in Jan 2013</li>
</ul>
</ul>
</ul>
</ul>
<li><b>Job</b></li>
<ul>
<li>Favor</li>
<ul>
<li>People use my Excel tools to better their own preformance</li>
<li>Boss uses me as a fill in team lead.&nbsp;</li>
<li>Qtr 1 2013 Made a $1,960 Bonus</li>
<li>Qtr 2&nbsp; 2013 Made a $3,035 Bonus</li>
<li><i>Ran my big mouth in Complaining and decided to leave all leadership programs. Just taking calls now. 08/03/2013 not so much Favor now.</i></li>
<li>Qtr 3 No Bonus</li>
<li>Qtr 4&nbsp;</li>
<ul>
<li>...on the edge of the knife, two days left 12/30 7:50 am</li>
<li>Didn't make it. 01/08/2014</li>
</ul>
</ul>
<li><b>Word's of the Lord for Promotion:</b></li>
<ul>
<li>God said at end of 2012 to believe for:</li>
<ul>
<li>One Job, Tailor Fit, More then enough!&nbsp;</li>
</ul>
<li>Kenneth Copeland gave a Word for 2013</li>
<ul>
<li>"Stay where you are. Stay Steady. Why?! Your greatest BLESSING ever is at hand..."</li>
</ul>
<li>Pastor George Changed service just to deliver the Word of the Lord I needed. Maybe other people needed it too, but I'm SURE it was for me.&nbsp;</li>
<ul>
<li>Pastor George Pearsons 02/17/2013: ~~ "Someone is having a work situation and there is a lot of negativity. Stop talking about it. Stop it! You pray in tongues over that thing. Promotion is coming... stay above the fray... God will use you like Joseph and Daniel. You can control the whole thing from your prayer closet..."&nbsp;</li>
</ul>
<li>Olivier Simon</li>
<ul>
<li><div class="MsoNormal">
<i>good.
as i was praying earlier for you, I won't say that the Spirit resisted me
because that would be too strong of a word but i felt compelled to pray for
more than that and voiced that He has given you more than your mind can
actually contain....I prayed this while focusing on your promotion. Your God
loves you.&nbsp;</i><i>I
don't need it now but i'll eventually ask you to give me the different verses
you have been or intend to stand on so there can be agreement between the 2 of
us so we can do more.</i></div>
<div class="MsoNormal">
<o:p></o:p></div>
</li>
<li><div class="MsoNormal">
<i>As i
started praying for you earlier, what came surprisingly out of my spirit is
that He is consumed with you, with the thought of you. I'm saying surprisingly
because pastor Art taught a bit on Psalm 8.4 "what is mankind that you are
mindful of them, human beings that you care for them?" and i didn't expect
that to come out of my mouth as i was praying for you. What is clear was that
He was consumed with you.</i><i>Then
i got in my spirit that you must focus. The verse that came to mind is 1 Peter
5.8. Be sober, don't be scatter brain. Focus on what you know matters and not
on the unnecessary stuff.&nbsp;</i><i>Amen!&nbsp;</i><i>that's
it!&nbsp;</i><i>Going
to study now with my son.</i></div>
</li>
</ul>
</ul>
</ul>
</ul>
<br />
<ul><ul><ul>
<li>Word of the Lord to Me: 05/01</li>
<ul>
<li><i>God: Your promotion to leadership in the natural will be matched by your promotion in the Spirit. You will now see rapid growth throughout this year and beyond.&nbsp;Wed 5/1/2013 6:08 AM</i></li>
</ul>
</ul>
</ul>
</ul>
<br />
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------<br />
<h4>
2012</h4>
<br />
<ul>
<li><b>Write</b></li>
<ul>
<li>Jan 2012</li>
<ul>
<li>Met with Jack E. to start talking about</li>
</ul>
</ul>
<li><b>Job</b></li>
<ul>
<li>08/2002</li>
<ul>
<li>Bonused $1,500 in Qtr 2 because&nbsp;</li>
<ul>
<li>I obeyed God and my wife and stopped complaining and dared to trust him.&nbsp;</li>
<li>#1 They changed the rules at the end of the quarter for the second time in history!</li>
<li>#2 My numbers shot up without explanation and pushed me over their new lower mark!&nbsp;</li>
</ul>
</ul>
<li>11/2002&nbsp;</li>
<ul>
<li>Bonused $2,305 in Qtr 3</li>
<li>Qtr 4 Award lost, mostly due to bad attitude that I fell back into.&nbsp;</li>
</ul>
</ul>
<li><b>Household</b></li>
<ul>
<li>11/2002</li>
<ul>
<li>Car Accident on freeway.&nbsp;</li>
<ul>
<li>2002 Saturn, our only car, was totaled.&nbsp;</li>
<li>We paid $2,500 for that car.</li>
<li>God used us to protect a fearful young woman from harm.&nbsp;</li>
<li>I wasn't perfect in my faith, but I was much calmer and more faith filled than in previous years. There was a marked difference in how I reacted and responded.&nbsp;</li>
</ul>
<li>Within 2 WEEKS God brought us&nbsp;</li>
<ul>
<li>A check for $4,600</li>
<ul>
<li>2002 Honda Oddesy: $2,600</li>
<ul>
<li>AND</li>
</ul>
<li>1995 Ford Escort Wagon: $900</li>
<li>Both in better condition than the one we lost!</li>
</ul>
</ul>
</ul>
</ul>
</ul>
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------<br />
<h4>
2002 - 2011</h4>
<br />
<ul>
<li>2002-2004</li>
<ul>
<li>Met my wonderful Wife through a series of odd events and married her within two years.&nbsp;</li>
<li>08/2002-01/2004</li>
<li>He brought us a check, through happy/sad circumstances that covered out wedding and the first year.&nbsp;</li>
<li>Also gave me a new family because unlike other men I LOVE my Mother-In-Love</li>
</ul>
<li>2004-2010</li>
<ul>
<li>He brought us through leaving 2 Churches unhappy.&nbsp;</li>
<li>Moving from a 2 Bed Apt into a Studio into the Car and back up to a 1 Bed Apt.&nbsp;</li>
<li>Then to Texas into a 2 Bed Apt and now in a 4 Bed House We Own!</li>
</ul>
<li>12/2005-1/2006</li>
<ul>
<li>God brought me into a banking Career through Favor with Sharon M. at the WF Call Center in Orange.&nbsp;</li>
<li>Promoted while still in training!</li>
<ul>
<li>Consumer ($12/Hr) to Premier ($14/Hr)</li>
</ul>
<li>Promoted in 2006 to IRA also.&nbsp;</li>
</ul>
<li>2007</li>
<ul>
<li>Achieved&nbsp;personal Goal of&nbsp;becoming&nbsp;a Fine Dining Server within 3 years of serving (to the month)</li>
</ul>
<li>2009</li>
<ul>
<li>He moved us to Texas which had been on our heart for years, to attend EMIC the Church we were called to, and Pastor George the Pastor we were called to. We had known we should be at EMIC since 2005.&nbsp;</li>
<li>Job Favor!</li>
<ul>
<li>WF Orange&nbsp;Recruiter&nbsp;talked to WF Westlake&nbsp;Recruiter&nbsp;and they said come on out we'll find room for you!&nbsp;</li>
<li>Few months later promoted to Banker Coach.</li>
</ul>
</ul>
<li>2010</li>
<ul>
<li>June 2010</li>
<ul>
<li>Had opportunity to be promoted to PB4 but chose to bail to become a personal banker.&nbsp;</li>
<ul>
<li>Even as a Personal Banker I still ended back up at the Call Center frequently doing offsite work for the branch.&nbsp;</li>
</ul>
<li>Promoted in June to Personal Banker.&nbsp;</li>
<ul>
<li>Didn't ask God if it was His will, it wasn't, but He gave it to me because I asked.&nbsp;</li>
</ul>
</ul>
</ul>
<li>2011</li>
<ul>
<li>Wanted a Job at another bank. Got it without any sweat.&nbsp;</li>
<ul>
<li>Didn't ask God if it was His will, it wasn't, but He gave it to me because I asked.&nbsp;</li>
</ul>
<li>Repented and asked God to bring me back to where He wanted me.&nbsp;</li>
<ul>
<li>Within 2 weeks landed back at WF Call Center in Sales.</li>
</ul>
</ul>
</ul>
<br />
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------<br />
<h4>
1980-2002</h4>
<br />
<ul>
<li>God redirected my life, over and over.&nbsp;</li>
<ul>
<li>When I was starting to get into trouble in Orange County He moved me back to Indio (1996)</li>
<li>When I tried to pursue various forms of trouble and substance abuse I was only ever allowed to get so far before God pulled me from it or jerked me to attention. Despite the fact my repentance was often short lived He never gave up one me.&nbsp;</li>
<li>When I got married as a young kid of 20 against the will of God,&nbsp;Parents, and Pastors. He brought me through that troubling time without much of a scratch. He healed those wounds afterward too.&nbsp;</li>
<li>August 7th 2002&nbsp;</li>
<ul>
<li>Stopped Smoking at a truck stop in Washington State</li>
<ul>
<li>"If you don't stop smoking you'll never sing again"</li>
</ul>
<li>When I was trying to run away from it all and go into the AirForce he brought a prayer-filled woman of God to snap me out of it.&nbsp;</li>
</ul>
<li>August 8th 2002</li>
<ul>
<li>Rededicated my life to Jesus fully and completely.&nbsp;</li>
<ul>
<li>Me: "What do you want from me? I'll do anything but Pastor, I'm not ready to say yes to that." God can deal with a broken but honest person.&nbsp;</li>
<li>God: "I want you to go back into Music"</li>
</ul>
</ul>
<li>God gave me several opportunities to go back into Music.</li>
<ul>
<li>He brought me a guitar almost immediately.</li>
<li>Brought me a woman who saw a light over my head to join her band for awhile.&nbsp;</li>
<li>Brought me a great friend who loved music and taught me some things</li>
<li>Brought me to a pastor who was a musician (that I later left because I was too immature)</li>
<li>Gave me several attempts to go to School for music Before and after this period.</li>
<li>In 2010-2011 I agreed to pursue music again and he brought another guitar immediately.</li>
<ul>
<li>In 2012 I'm finally using it.</li>
</ul>
</ul>
</ul>
<li>God Preserved me through rough times.&nbsp;</li>
<ul>
<li>My father leaving me as an infant home alone in a crib to go to the store to buy more alcohol.</li>
<li>My Vision of Jesus at around 5 years old.</li>
<li>My Vision of a demon after my Brother Devin at 3-5 Years old.&nbsp;</li>
<li>My constant dreams of Devin in trouble from a young age.&nbsp;</li>
<li>My addiction to sexual relationships that started also around 5-6 years old.&nbsp;</li>
<li>My calling to Ministry/Pastorate at 10 years old</li>
<ul>
<li>My many attempts to either fulfill or run away from that calling</li>
</ul>
<li>My failed attempt at a marriage in 2000-2002.</li>
</ul>
</ul>
<br />
DW