---
title: '10 Lessons from a widow woman'
date: '2010-04-20T04:56:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7192567482138012289'
blogger_filename: '/2010/04/10-lessons-from-widow-woman.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=2%20kings%204&amp;version=NKJV">2 Kings 4</a><br />
<br />
<br />
<span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">&nbsp;<sup class="versenum" id="en-NKJV-9605" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">1</sup>&nbsp;A certain woman of the wives of the sons of the prophets cried out to Elisha, saying, “<b>Your servant </b>my husband is dead, and you know that <b>your servant</b> feared the LORD. And <b>the creditor is coming</b> to <b>take</b> my two sons to be his <b>slaves</b>.”<br />
<sup class="versenum" id="en-NKJV-9606" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">2</sup>&nbsp;So Elisha said to her, “What shall I do for you? Tell me, what do you have in the house?” And she said, “Your maidservant has nothing in the house but<b> a jar of oil.”&nbsp;</b><br />
<sup class="versenum" id="en-NKJV-9607" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">3</sup>&nbsp;Then he said, “<b>Go</b>, borrow vessels from everywhere, from all your neighbors—empty vessels; <b>do not gather just a few</b>.&nbsp;<sup class="versenum" id="en-NKJV-9608" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">4</sup>&nbsp;And when you have come in, you shall <b>shut the door behind you</b> and your sons; then <b>pour it</b> into all those vessels, and set aside the full ones.”<br />
<sup class="versenum" id="en-NKJV-9609" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">5</sup>&nbsp;So she went from him and shut the door behind her and her sons, who brought&nbsp;<i>the vessels</i>&nbsp;to her; and she poured&nbsp;<i>it</i>&nbsp;out.&nbsp;<sup class="versenum" id="en-NKJV-9610" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">6</sup><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">&nbsp;Now it came to pass, when the vessels were full, that <b>she said to her son, “Bring me another vessel.”</b></span></span><br />
<span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">And he said to her, “<i>There is</i>&nbsp;not another vessel.” <b>So the oil ceased.&nbsp;</b></span><br />
<span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><sup class="versenum" id="en-NKJV-9611" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;"><br />
</sup></span><br />
<span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><sup class="versenum" id="en-NKJV-9611" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;"><br />
</sup></span><br />
<span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><sup class="versenum" id="en-NKJV-9611" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">7</sup>&nbsp;Then <b>she came and told the man of God</b>. And he said, “<b>Go</b>, sell the oil and <b>pay your debt; and you&nbsp;</b><i><b>and</b></i><b>&nbsp;your sons live on the rest</b>.”</span><br />
<span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">There are several keys I've learned from this passage:</span><br />
<span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<br />
<ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Always run TO the Word and those appointed as your leaders in the Word.&nbsp;</span></li>
<ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">The more you feel like staying home, do double time and two services.</span></li>
<li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Determine right up front you are going to COME, HEAR, and DO</span></li>
</ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">The Creditor makes you a slave. Stay out of Debt. This happened because the profit didn't take his family into relying on God Word.&nbsp;</span></li>
<ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Deut 28:12-<span class="Apple-style-span" style="font-size: 16px;"><sup class="versenum" id="en-NKJV-5624" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">12</sup>&nbsp;The LORD will open to you His good treasure, the heavens, to give the rain to your land in its season, and to bless all the work of your hand.<b> You shall lend to many nations, but you shall not borrow.</b></span></span></li>
<li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><span class="Apple-style-span" style="font-size: 16px;">Ex 22&nbsp;<sup class="versenum" id="en-NIV-2139" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">25</sup>&nbsp;"<b>If you lend money to one of my people among you who is needy, do not be like a moneylender; charge him no interest.</b>&nbsp;<sup class="footnote" style="font-size: 0.75em; line-height: 0.5em;" value="[&lt;a href=&quot;#fen-NIV-2139e&quot; title=&quot;See footnote e&quot;&gt;e&lt;/a&gt;]">[<a href="http://www.blogger.com/post-create.g?blogID=1992799306809150069#fen-NIV-2139e" title="See footnote e">e</a>]</sup>&nbsp;<sup class="versenum" id="en-NIV-2140" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">26</sup>&nbsp;If you take your neighbor's cloak as a pledge, return it to him by sunset,&nbsp;<sup class="versenum" id="en-NIV-2141" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">27</sup>&nbsp;because his cloak is the only covering he has for his body. What else will he sleep in? When he cries out to me, I will hear, for I am compassionate.</span></span></li>
<li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><span class="Apple-style-span" style="font-size: 16px;">Deut. 15&nbsp;<sup class="versenum" id="en-NIV-5323" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">3</sup>&nbsp;You may require payment from a foreigner, but you must cancel any debt your brother owes you.&nbsp;<sup class="versenum" id="en-NIV-5324" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">4</sup>&nbsp;However,<b> there should be no poor among you,</b> for in the land the LORD your God is giving you to possess as your inheritance, he will richly bless you,&nbsp;<sup class="versenum" id="en-NIV-5325" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">5</sup>&nbsp;if only you fully obey the LORD your God and are careful to follow all these commands I am giving you today.</span></span></li>
<li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><span class="Apple-style-span" style="font-size: 16px;">This shows that the Man of God following God's Word SHOULD NOT BE POOR!</span></span></li>
<li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><span class="Apple-style-span" style="font-size: 16px;">Debt and Disobedience not only has bondage but it affects generations.&nbsp;</span></span></li>
</ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Be Servant Minded.</span></li>
<ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Twice in one&nbsp;sentence&nbsp;she called her late husband "Your Servant" Then she went on to call herself Your Maidservant.&nbsp;</span></li>
</ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Have what you know to be valuable on your mind already</span></li>
<ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">She had on her mind what value she had.&nbsp;</span></li>
<li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">She'd no doubt been racking her brain trying to come up with a solution before coming all the way out to see the man of God.&nbsp;</span></li>
<li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">She knew immediately the one thing she had that possessed any value. I believe she was ready to sow it.&nbsp;</span></li>
<li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">But she was thinking about how little it was. Like Andrew, Simon Peters brother who said in John 6:8-10 "Here is a little boy with two fish and five loaves but what are they among so many?"&nbsp;</span></li>
</ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Obedience</span></li>
<ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">He said GO, She went, she did.</span></li>
</ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Don't tell everyone what you are up to</span></li>
<ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Shut the door on outside participation</span></li>
</ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Pour Out what you have</span></li>
<ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Be ready to pour out what you think you have in order to get what you think you need.&nbsp;</span></li>
</ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Keep a "MORE" mindset</span></li>
<ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">She was ready to KEEP ON POURING when they ran out of vessels. Which tells me that she wasn't nervously keep track of each one, like some penny pincher. She was freely pouring and freely&nbsp;receiving.&nbsp;</span></li>
</ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">STOP... await further&nbsp;instructions</span></li>
<ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">She didn't Assume she was to sell all this.&nbsp;</span></li>
<li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">She went back for further instruction.</span></li>
<li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">If she had sold but He said give... she'd have short&nbsp;circuited&nbsp;the miracle. Be cautious not to ADD to what God has said to do.&nbsp;</span></li>
</ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">God is always about MORE than enough...&nbsp;</span></li>
<ol><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Pay off your debts</span></li>
<li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Live on the rest!!!!!</span></li>
</ol></ol><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br />
</span></div>