---
title: 'Work to Believe!'
date: '2010-04-15T03:28:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '171370042171440799'
blogger_filename: '/2010/04/work-to-believe.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=John%206&amp;version=NKJV">John 6</a><br />
<br />
<span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><sup class="versenum" id="en-NKJV-26280" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">26</sup>&nbsp;Jesus answered them and said, “Most assuredly, I say to you, you seek Me, not because you saw the signs, but because you ate of the loaves and were filled.&nbsp;<sup class="versenum" id="en-NKJV-26281" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">27</sup>&nbsp;<b>Do not labor for the food which perishes, but for the food which endures to everlasting life</b>, which the Son of Man will give you, because God the Father has set His seal on Him.”<br />
<sup class="versenum" id="en-NKJV-26282" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">28</sup>&nbsp;Then they said to Him, “What shall we do, that we may work the works of God?”<br />
<sup class="versenum" id="en-NKJV-26283" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">29</sup>&nbsp;Jesus answered and said to them, <b>“This is the work of God, that you believe in Him whom He sent.”&nbsp;</b></span><br />
<br />
<br />
<br />
Your WORK is to BELIEVE!<br />
<br />
You should NEVER be "working" for bread or food or bills!<br />
<br />
Now, you still go to a job and you bring home your paycheck until the Lord gives you a new plan... don't mistake this statement for laziness! But even then that job is NOT YOUR WORK!<br />
<br />
Your WORK... the thing you should be spending MOST of your energy on is&nbsp;BELIEVING!<br />
<br />
So what does that mean? You sit around on the couch with your eyes closed humming a mantra: "I Beleeeeeeeeeeeeeeeeeeeeeeeeeeeive.... I Beleeeeeeeeeeeeeeeeeeeeeive..."???<br />
<br />
NO!<br />
<br />
You study the Word,&nbsp;quote&nbsp;the Word, you research the Word, you talk about it morning, noon, and night. You make the Word the FIRST thing you think about between calls or duties at work. The MOMENT you have idle time you are thinking about the Word, talking with your Heavenly Father, Praying in tongues, thinking about the many meanings and applications of that verse you've been reading ... Etc Etc...<br />
<br />
It ALSO means that you are to take captive EVERY THOUGHT that&nbsp;contradicts&nbsp;the Word. That includes but is not limited to:<br />
<br />
<ul><li>Thoughts</li>
<li>Images</li>
<li>Imaginations</li>
<li>Ideas</li>
<li>Words you hear yourself saying</li>
<li>Words others are saying</li>
<li>Images and Words coming in through media such as:</li>

<ul><li>Print</li>
<li>TV</li>
<li>Magazines</li>
<li>Newspapers</li>
<li>Internet</li>
<li>Cable</li>
<li>Movies</li>
<li>etc</li>
<li>etc</li>
</ul>
<li>ANYTHING that distracts you from the Word.&nbsp;</li>
<li>Entertainment isn't bad in and of it'self unless you find yourself making excuses for why you should have this program, why you need this after such a long day... etc Then you have a red flag that you know in your spirit that you SHOULD be doing something to help the Word go further inside you and keeping it fresh and real</li>
</ul><div>It's time to be AGGRESSIVE; PERSISTENT; &amp;&nbsp;DETERMINED about the Word, Will, Work, and Wooing of God!&nbsp;</div><div><br />
</div><div>God not only wants you to do his WORK but He wants you to be WOOED by him... He wants YOUR PRESENCE and INTIMATE communion. One way talks are not conversations they are&nbsp;monologues!&nbsp;</div><div><br />
</div><div>In Your Prayer time...STOP... look to you area just between your belly and chest and wait...wait...wait...Listen for GOD speaking! If you feel&nbsp;distracted&nbsp;prayer quietly... or just say "I love you" every so often... but listen!!</div><div><br />
</div><div><br />
</div><div><br />
</div><div>Consider the Following by <a href="http://www.utmost.org/">Chambers</a>&nbsp;from todays reading 04.14:</div><div><br />
</div><div><span class="Apple-style-span" style="color: #555555; font-family: verdana, geneva, sans-serif; font-size: 17px; line-height: 25px;"></span><br />
<span class="Apple-style-span" style="color: #555555; font-family: verdana, geneva, sans-serif; font-size: 17px; line-height: 25px;"><div style="line-height: 1.5em; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 5px; padding-left: 15px; padding-right: 15px; padding-top: 5px;">The fact that the peace, light, and joy of God is in them is proof that a burden is there as well. The burden that God places on us squeezes the grapes in our lives and produces the wine, but most of us see only the wine and not the burden. No power on earth or in hell can conquer the Spirit of God living within the human spirit; it creates an inner invincibility.</div><div style="line-height: 1.5em; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 5px; padding-left: 15px; padding-right: 15px; padding-top: 5px;"><b>If your life is producing only a whine, instead of the wine, then ruthlessly kick it out</b>. It is definitely a crime for a Christian to be weak in God’s strength.</div></span></div><br />
<br />
<br />
<br />
Darrell G. Wolfe