---
title: 'Receiving isn''t for wussy''s!'
date: '2010-04-11T13:19:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3595170904031196413'
blogger_filename: '/2010/04/receiving-isnt-for-wussys.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

Friday a co-worker S came in asking if anyone wanted some of her nachos. There was a&nbsp;piece&nbsp;in me that felt like saying "No... I couldn't possibly..." There was another part of me that said YES NOW OVER HERE!!!! It was THAT part that processed about 15 seconds from the announcement and had me speak up and say "I'll take it!" And I was sitting eating my fresh nachos from planet burrito I was thinking about all this...<br />
<br />
False Humility is PURE EVIL! Satan WANTS you to deny yourself the&nbsp;opportunity&nbsp;to&nbsp;receive. I couldn't go back the next day and... "Um... I thought it over... do you still have some of those nachos?" That ship has sailed already. Many times delaying and not making rational decisions is a good idea. But if you've already set your faith for something you OUGHT to be looking for it, expecting it, and ready to act on a moments notice when a harvest comes in.<br />
<br />
Something similar happened yesterday. The apartments through a resident event with a petting zoo and&nbsp;barbecue&nbsp;and everything. I felt sheepish going over to get a hot dog, that was brought in for ME... I'M A RESIDENT!! Even though it was there for ME and others I felt little confidence in&nbsp;receiving. Then I sheepishly went for another and the cook who brought them to&nbsp;sponsor&nbsp;his business said "HEY BUDDY... you want more? We got a BUNCH!&nbsp;Every time&nbsp;I went his direction, even for something else He handed me one. I ended up eating SIX and taking another three home with me! On top of the ones Face and kids had.<br />
<br />
This brings me to a realization.<br />
<br />
<b><span class="Apple-style-span" style="font-size: x-large;">Receiving&nbsp;isn't for wussy's!</span></b><br />
<br />
What is "sheepish" anyway?<br />
<br />
<br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"></span><br />
<h2 id="passage_heading"><a href="http://www.biblegateway.com/passage/?search=James+1:6-8&amp;version=NIV"><span class="Apple-style-span" style="font-size: x-large;"><i>James 1:6-8&nbsp;(New International Version)</i></span></a></h2><div class="result-text-style-normal" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><sup class="versenum" id="en-NIV-30257" style="line-height: normal; vertical-align: text-top;"><span class="Apple-style-span" style="font-size: x-large;"><b><i>6</i></b></span></sup><span class="Apple-style-span" style="font-size: x-large;"><b><i>But when he asks, he must believe and not doubt, because he who doubts is like a wave of the sea, blown and tossed by the wind.&nbsp;</i></b></span><sup class="versenum" id="en-NIV-30258" style="line-height: normal; vertical-align: text-top;"><span class="Apple-style-span" style="font-size: x-large;"><b><i>7</i></b></span></sup><span class="Apple-style-span" style="font-size: x-large;"><b><i>That man should not think he will receive anything from the Lord;&nbsp;</i></b></span><sup class="versenum" id="en-NIV-30259" style="line-height: normal; vertical-align: text-top;"><span class="Apple-style-span" style="font-size: x-large;"><b><i>8</i></b></span></sup><span class="Apple-style-span" style="font-size: x-large;"><b><i>he is a double-minded man, unstable in all he does.</i></b></span></div><br />
<br />
<br />
<br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><strong><a href="http://www.blogger.com/passage/?search=1%20Corinthians+4:7&amp;version=NIV" style="color: #ff9933;">1 Corinthians 4:7</a></strong><br />
For who makes you different from anyone else? What do you have that you did not&nbsp;<b>receive</b>? And if you did&nbsp;<b>receive</b>&nbsp;it, why do you boast as though you did not?</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><strong><a href="http://www.blogger.com/passage/?search=2%20Timothy+2:6&amp;version=NIV">2 Timothy 2:6</a></strong><br />
The hardworking farmer should be the first to&nbsp;<b>receive</b>&nbsp;a share of the crops.</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><strong><a href="http://www.blogger.com/passage/?search=Exodus+25:3&amp;version=NIV">Exodus 25:3</a></strong><br />
These are the offerings you are to&nbsp;<b>receive</b>&nbsp;from them: gold, silver and bronze;</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><strong><a href="http://www.blogger.com/passage/?search=Matthew+10:41&amp;version=NIV">Matthew 10:41</a></strong><br />
Anyone who&nbsp;<b>receive</b>s a prophet because he is a prophet will&nbsp;<b>receive</b>&nbsp;a prophet's reward, and anyone who&nbsp;<b>receive</b>s a righteous man because he is a righteous man will&nbsp;<b>receive</b>&nbsp;a righteous man's reward.</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><strong><a href="http://www.blogger.com/passage/?search=Galatians+4:5&amp;version=NIV">Galatians 4:5</a></strong><br />
to redeem those under law, that we might&nbsp;<b>receive</b>&nbsp;the full rights of sons.</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><strong><a href="http://www.blogger.com/passage/?search=Proverbs+11:31&amp;version=NIV">Proverbs 11:31</a></strong><br />
If the righteous&nbsp;<b>receive</b>&nbsp;their due on earth, how much more the ungodly and the sinner!</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><strong><a href="http://www.blogger.com/passage/?search=1%20Thessalonians+5:9&amp;version=NIV" style="color: #ff9933;">1 Thessalonians 5:9</a></strong><br />
For God did not appoint us to suffer wrath but to&nbsp;<b>receive</b>&nbsp;salvation through our Lord Jesus Christ.</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><strong><a href="http://www.blogger.com/passage/?search=Acts+8:19&amp;version=NIV" style="color: #ff9933;">Acts 8:19</a></strong><br />
and said, "Give me also this ability so that everyone on whom I lay my hands may&nbsp;<b>receive</b>&nbsp;the Holy Spirit."</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><strong><a href="http://www.blogger.com/passage/?search=Hebrews+11:19&amp;version=NIV">Hebrews 11:19</a></strong><br />
Abraham reasoned that God could raise the dead, and figuratively speaking, he did&nbsp;<b>receive</b>&nbsp;Isaac back from death.</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><strong><a href="http://www.blogger.com/passage/?search=Matthew+21:22&amp;version=NIV">Matthew 21:22</a></strong><br />
If you believe, you will&nbsp;<b>receive</b>&nbsp;whatever you ask for in prayer."</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><strong><a href="http://www.blogger.com/passage/?search=John+20:22&amp;version=NIV">John 20:22</a></strong><br />
And with that he breathed on them and said, "<b>Receive</b>&nbsp;the Holy Spirit.</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><strong><a href="http://www.blogger.com/passage/?search=Acts+8:15&amp;version=NIV" style="color: #ff9933;">Acts 8:15</a></strong><br />
When they arrived, they prayed for them that they might&nbsp;<b>receive</b>&nbsp;the Holy Spirit,</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><strong><a href="http://www.blogger.com/passage/?search=1%20Corinthians+3:14&amp;version=NIV">1 Corinthians 3:14</a></strong><br />
If what he has built survives, he will&nbsp;<b>receive</b>&nbsp;his reward.</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span><br />
<span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />
</span>