---
title: 'ON Purpose! Unlimited Resource!'
date: '2010-04-15T04:08:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6653818248706729034'
blogger_filename: '/2010/04/on-purpose-unlimited-resource.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

I saw questions on the wall at work today. They were as follows:<div><br />
</div><div><ol><li>If I could throw caution to the wind and REALLY risk I would___________.</li>
<li>The Comic Character I would like to be is___________________.</li>
<li>If I had ALL THE MONEY IN THE WORLD I would____________.</li>
</ol><div><br />
</div></div><div>I thought about that...&nbsp;</div><div><ol><li>The first one was hard... I don't like the wording per se... I decided I would... and WILL walk on water... but that's been done... how about FLY!!!</li>
<li>Easy: Superman! Flying ROCKS! So does everything else he does! I feel ALL&nbsp;Christians&nbsp;are super-men! Even if we don't all live up to our potential or anywhere near what God has for us... we all have supernatural ability ABIDING in us... The same Spirit and power that raised Jesus from the dead now dwells in us quickening our mortal bodies!!!</li>
<li>This one grabbed me... And spun me around... and left me with the following:</li>
</ol></div><div><b><span class="Apple-style-span" style="font-size: x-large;"><br />
</span></b><br />
<a href="http://www.biblegateway.com/passage/?search=2%20cor%209&amp;version=NKJV"><b><span class="Apple-style-span" style="font-size: x-large;">2 Corinthians 9</span></b></a><br />
<br />
<br />
<span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><sup class="versenum" id="en-NKJV-28961" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">8</sup></span><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">&nbsp;</span><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">And </span><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><b>God&nbsp;</b></span><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><i><b>is</b></i></span><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><b>&nbsp;able to make all grace abound toward you, that you, always having all sufficiency in all&nbsp;</b></span><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><i><b>things,</b></i></span><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><b>&nbsp;may have an abundance for every good work.&nbsp;</b></span><br />
<br />
We not ONLY DO have all the money in the world... we have BETTER we have UNLIMITED RESOURCE!<br />
<br />
It's about time I started tapping into it!<br />
<br />
God: I already said I am able to make all grace abound toward you SO THAT YOU ALWAYS HAVING ALL SUFFICIENCY in ALL THING may have AN ABUNDANCE for EVERY good work!!!<br />
<br />
But there ARE pre-requisites.<br />
<br />
<span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><sup class="versenum" id="en-NKJV-28958" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">5</sup>&nbsp;Therefore I thought it necessary to exhort the brethren to go to you ahead of time, and <b>prepare your generous gift beforehand</b>, which&nbsp;<i><b>you had</b></i><b>&nbsp;previously promised</b>, that it may be ready as&nbsp;<i>a matter of</i>&nbsp;<b>generosity and not as a grudging obligation</b>.<sup class="versenum" id="en-NKJV-28959" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">6</sup>&nbsp;But this&nbsp;<i>I say:</i>&nbsp;He who sows sparingly will also reap sparingly, and <b>he who sows bountifully will also reap bountifully</b>.&nbsp;<sup class="versenum" id="en-NKJV-28960" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">7</sup>&nbsp;<i>So let</i>&nbsp;each one&nbsp;<i>give</i>s he purposes in his heart, not <b>grudgingly or of necessity; for God loves a cheerful giver.</b></span><br />
<br />
<br />
MY Giving in all it's forms needs to be; ON PURPOSE!!<br />
<br />
Tithing... Offering... Giving Projects.... There needs to be an ON PURPOSE-NESS to it!<br />
<br />
<br />
<br />
<br />
<br />
<br />
</div>