---
title: 'Day Two'
date: '2010-01-12T19:43:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3462524247841652059'
blogger_filename: '/2010/01/day-two.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

01/12/2009<br />
<br />
I've told no-one about this commitment. It's all between God and I. This blog won't even be published until this project is over. <br />
<br />
<br />
Day Two... My God provides ALL my need consistent with HIS riches in Christ Jesus. He is feeding me supernaturally, as Elijah was fed by ravens. I REFUSE to fret over what I will eat.<br />
(Phillipians 4, I Kings 17, Mathew 6)<br />
<br />
<a href="http://www.biblegateway.com/passage/?search=Mark%204&amp;version=ESV">Mark 4 (English Standard Version)</a><br />
<br />
<br />
The Parable of the Seed Growing<br />
<br />
26And he said, (AH) "The kingdom of God is as if a man should scatter seed on the ground. 27He sleeps and rises night and day, and the seed sprouts and grows;(AI) he knows not how. 28The earth produces by itself, first the blade, then the ear, then the full grain in the ear. 29But when the grain is ripe, at once(AJ) he puts in the sickle, because the harvest has come."<br />
<br />
Today at lunch a co-worker was offered free cake by another team and she came running and brought some to me... <br />
<br />
Desirre: "HEY DARRELL!! You want a piece of cake?" <br />
<br />
Here comes that blade... it's a cake blade... I'm calling in nutritious, healthy, delicious food now! Thai, Burgers, Mexican... Come to me in Jesus Name! <br />
<br />
My God is meeting my needs. There is the leaf coming up...<br />
<br />
Darrell G. Wolfe