---
title: 'Principle VS Rule'
date: '2010-06-01T13:01:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '659302224943971886'
blogger_filename: '/2010/06/principle-vs-rule.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

A Principle is&nbsp; a guide. It is about the spirit or heart of the matter. <br />
<br />
Rule is hard and unmoving. It is about the letter of the law.<br />
<br />
If you have a rule about "No Alcohol" you may be tempted to force that rule on others. The bible is not clear that you should or should not drink. It is left to a matter of conscience and conviction. If you say NO DRINKING than you will be tempted to think less of others and make is a rule or code or some doctrine<br />
<br />
If you have a principle about not drinking you may say: I have a history of overdoing things, and a family history or alcoholism. I've seen the fruit of drinking in others and the fruit of the advertisements around it. As for me, the wisdom of God restrains me from participating. Others may be able in good conscience, but I cannot. It is my principle not others. Others may do as they please.<br />
<br />
The local church may also make such decisions without imposing them on their sister churches within the city. This is part of the LOVE of God that doesn't Impose it's will on others.<br />
<br />
DW