---
title: 'Personal Banker to CEO'
date: '2010-06-01T12:50:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7505091052251865774'
blogger_filename: '/2010/06/personal-banker-to-ceo.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

How To Become CEO-Jeff Fox <br />
<br />
There were several tips given by Jeff Fox that I was reading at lunch. Among them was:<br />
Don't eat lunch, use that time to catch up and get ahead and stay productive, or recharge with a nap, or reading. That is what this no lunches time has become for me. It has brought a new level of understanding to me in how to treat this business as MY business.<br />
<br />
The no lunches thing has actually created in me a steel and work ethic I didn't have before. It was hard at first, and now food is no longer my god. I didn't realize that it had such control over me. But it did. In fact, we eat less at home, are less tempted to go out, and spend on fast food too. <br />
<br />
I don't know that I would have gotten my promotion to Personal Banker had I not taken on this endeavor. I still expect God to feed me. But I first had to realize that there are different types of feeding. God must be my God before He can be my provider.&nbsp; <br />
<br />
I finally understand the work ethic Jesse Duplantis speaks about so often. I'm able to say no to other temptations now too much more easily.<br />
<br />
DW