---
title: 'First The Blade'
date: '2010-03-28T00:29:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4435034685180390043'
blogger_filename: '/2010/03/first-blade.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<h2 id="passage_heading"><a href="http://www.biblegateway.com/passage/?search=Mark+4:27-29&amp;version=NKJV">Mark 4:27-29&nbsp;(New King James Version)</a></h2><sup class="versenum" id="en-NKJV-24347">27</sup> and should sleep by night and rise by day, and the seed should sprout and grow, he himself does not know how. <sup class="versenum" id="en-NKJV-24348">28</sup> For the earth yields crops by itself: <b>first the blade</b>, then the head, after that the full grain in the head. <sup class="versenum" id="en-NKJV-24349">29</sup> But when the grain ripens, immediately he puts in the sickle, because the harvest has come.”<br />
<br />
&nbsp;The first thing I should say is I've been slacking... I haven't kept up with this blog or my dedication to this project. So I'll have to summarize what has happened and start from here.<br />
<br />
<br />
<ul><li>&nbsp;&nbsp;&nbsp;&nbsp; Shortly after I started going to work without taking a lunch with me a co-worker Desirre came running up to me and said: "Hey Darrell! You want some?" And handed me a piece of cake on a plate with a fork. It was good cake too. I'm picky about frosting and it was my favourite kind. It was white cake which is also my favourite. </li>
</ul><ul><li>&nbsp;&nbsp;&nbsp;&nbsp; Random people have given me candy, various people have brought treats such as brownies and sopapillas for the team to share.&nbsp;</li>
<li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I got discouraged, but also didn't do anything about it, and started taking food for two weeks. Then got back on track, not because I had a faith boost but because we ran out of food at home and had to ration.&nbsp;</li>
<li>&nbsp;&nbsp;&nbsp;&nbsp; I still go without meals, but now I've come to expect not to get anything. That's fine for fasting and I've gotten a lot of work done, but very much in contrast to what I set out for. This is not a fast, I'm supposed to be expecting God to provide. Instead I'm expecting Him not to.&nbsp;</li>
<li>SO, Here I am... Sitting at home... typing this and about to get the kids ready for bed. I'm going to need to review the scriptures and make a declaration of faith regarding this project that I can confess every morning on the way to work.&nbsp;</li>
</ul>DW <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;