---
title: 'House and something more?'
date: '2010-08-31T14:14:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6724480526528180309'
blogger_filename: '/2010/08/house-and-something-more.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'House'
---

The Lord led us to a house in Haslet. So many things have happened to bring us to this point. We are closing on 09.10 and we will finally have a yard to play in. We will finally be able to have dogs. Yet as this comes nearer I sense more urgency behind it, to get me involved with the church and focused on my ultimate reason for being here in Texas. I've become so content with getting promoted that I have been starting to see Wells Fargo as a long term place. It can't be if I am to fulfill the vision of God for my life. <br />
<br />
I sense that the winds of Change are blowing, beyond this house and the few little business plans we have made. Something... something... is coming for us... something that will catapult us into the ministry and business and bring us to the place God has for us. The last days are here. New evidence has come to my attention that places 2019 as a probable year for Christs return. That doesn't leave much time to see all He has for us come to pass...<br />
<br />
I must get serious about my walk with God and not loose sight. My Kids and Wife are depending on it. People's souls and lives are depending on it. We shall see...<br />
<br />
DW