---
title: 'Covenant Defined by Websters 1828'
date: '2011-10-06T03:30:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4297666442228581982'
blogger_filename: '/2011/10/covenant-defined-by-websters-1828.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Ministry'
---

<span class="Apple-style-span" style="background-color: white;"></span><br />
<h1>

<a href="http://1828.mshaffer.com/d/word/covenant" style="color: #465131; text-decoration: underline;" title="[13219] 8 ">covenant</a></h1>
<br />
<div style="color: #465131;">
<b style="color: #dad496; font-weight: bold;">COVENANT</b>, n. [L, to come; a coming together; a meeting or agreement of minds.]</div>
<div style="color: #465131;">
</div>
<dd>1. A mutual consent or agreement of two or more persons, to do or to forbear some act or thing; a contract; stipulation. A covenant is created by deed in writing, sealed and executed; or it may be implied in the contract.<br />
<div style="color: #465131;">
</div>
</dd><dd>2. A writing containing the terms of agreement or contract between parties; or the clause of agreement in a deed containing the covenant.<br />
<div style="color: #465131;">
</div>
</dd><dd>3. In theology, the covenant of works, is that implied in the commands, prohibitions, and promises of God; the promise of God to man, that mans perfect obedience should entitle him to happiness. This do, and live; that do, and die.<br />
<div style="color: #465131;">
</div>
</dd><dd>The covenant of redemption, is the mutual agreement between the Father and Son, respecting the redemption of sinners by Christ.<br />
<div style="color: #465131;">
</div>
</dd><dd>The covenant of grace, is that by which God engages to bestow salvation on man, upon the condition that man shall believe in Christ and yield obedience to the terms of the gospel.<br />
<div style="color: #465131;">
</div>
</dd><dd>4. In church affairs, a solemn agreement between the members of a church, that they will walk together according to the precepts of the gospel, in brotherly affection.<br />
<div style="color: #465131;">
<b style="color: #dad496; font-weight: bold;">COVENANT</b>, v.i. To enter into a formal agreement; to stipulate; to bind ones self by contract. A covenants with B to convey to him a certain estate. When the terms are expressed ti has for before the thing or price.</div>
<div style="color: #465131;">
</div>
</dd><dd></dd><dd>They covenanted with him for thirty pieces of silver. Matthew 26.<br />
<div style="color: #465131;">
<b style="color: #dad496; font-weight: bold;">COVENANT</b>, v.t. To grant or promise by covenant.</div>
</dd>