---
title: 'Preach the Word! Convince, Rebuke, and Exhort!'
date: '2011-10-07T03:21:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5834163621176150445'
blogger_filename: '/2011/10/preach-word-convince-rebuke-and-exhort.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Ministry'
---

What is my calling as a pastor? What do I need to know regarding it? The following instructions were given to Timothy<br />
<br />
<ul>
<li>Preach the Word!</li>
<li><b>Convince</b></li>
</ul>
To Persuade or Satisfy the mind by evidence or to Overpower or Compel to yield or assent.<br />
<div>
<br /></div>
<div>
<b>Therefore to Convince is to:&nbsp;Show the Power and Preach the Word in order to persuade and satisfy.&nbsp;</b><br />
<ul>
<li><b>Rebuke</b></li>
</ul>
To Check: Restrain, Silence, Calm, Punish, or Heal. In all cases it is meant to bring correction to a situation. To make it the way God would have it be or to bring His Shalom to the situation. Even out of line behavior is to be corrected with the intention of healing and restoration, not punished just to punish.&nbsp;</div>
<div>
<br /></div>
<div>
<b>Therefore to Rebuke is to bring the nothing missing, nothing broken peace of God into every situation</b>; restraining the work of the devil bringing healing and calm to the people.&nbsp;</div>
<div>
<ul>
<li><b>Exhort</b></li>
</ul>
Incite to Action, Animate by arguments, Stimulate to exertion, <b>Encourage to action</b>.&nbsp;</div>
<div>
<br /></div>
<div>
<b>Therefore to Exhort is to Encourage to Action.&nbsp;</b><br />
<br />
<br />
<span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 12px;"></span><br />
<h1 class="Title TitleSmall" style="color: #9d3300; font-size: 24px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; width: 525px;">

2 Timothy 4:1-7 (New King James Version)</h1>
<span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 14px; line-height: 20px;"><span class="versetext" id="2ti4-1" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">1</span>&nbsp;I charge you therefore before God and the Lord Jesus Christ, who will judge the living and the dead at His appearing and His kingdom:<b>&nbsp;</b></span><span class="versetext highlightThenFade" id="2ti4-2" style="background-color: #f6f698; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><b><span class="versenum" style="margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">2</span>&nbsp;Preach the word! Be ready in season and out of season. <u>Convince, rebuke, exhort</u>, with all longsuffering and teaching</b>.&nbsp;</span><span class="versetext" id="2ti4-3" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">3</span>&nbsp;For the time will come when they will not endure sound doctrine, but according to their own desires, because they have itching ears, they will heap up for themselves teachers;&nbsp;</span><span class="versetext" id="2ti4-4" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">4</span>&nbsp;and they will turn their ears away from the truth, and be turned aside to fables.&nbsp;</span><span class="versetext" id="2ti4-5" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">5</span>&nbsp;But you be watchful in all things, endure afflictions, do the work of an evangelist, fulfill your ministry.&nbsp;</span><span class="versetext" id="2ti4-6" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">6</span>&nbsp;For I am already being poured out as a drink offering, and the time of my departure is at hand.&nbsp;</span><span class="versetext" id="2ti4-7" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">7</span>&nbsp;I have fought the good fight, I have finished the race, I have kept the faith.</span></span><br />
<span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 14px; line-height: 20px;"><span class="versetext" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><br /></span></span><br />
<span class="Apple-style-span" style="background-color: white; font-size: 32px; font-weight: bold;"><a href="http://1828.mshaffer.com/d/word/convince" style="color: #7b8b4c; text-decoration: none;" title="[12573] 8 ">convince</a></span><br />
<span class="Apple-style-span" style="background-color: white;"></span><br />
<div style="color: #465131;">
<b style="color: #dad496; font-weight: bold;">CONVINCE</b>, v.t. [L., to vanquish.]</div>
<div style="color: #465131;">
</div>
<br />
<dd>1. To <b>persuade </b>or <b>satisfy the mind by evidence</b>; to subdue the opposition of the mind to truth, or to what is alledged, and <b>compel it to yield its assent</b>; as, to convince a man of his errors; or to convince him of the truth.<br />
<div style="color: #465131;">
</div>
</dd><dd></dd><dd><b>For he mightily convinced the Jews--showing by the scriptures that Jesus was the Christ. Acts 18.</b><br />
<div style="color: #465131;">
</div>
</dd><dd>2. To <b>convict</b>; to prove guilty; to <b>constrain one to admit or acknowledge himself to be guilty</b>.<br />
<div style="color: #465131;">
</div>
</dd><dd></dd><dd>If ye have respect to persons, ye commit sin, and are convinced of [by] the law as transgressors. James 2.<br />
<div style="color: #465131;">
</div>
</dd><dd></dd><dd>To convince all that are ungodly among them of all their ungodly deeds. Jude 15.<br />
<div style="color: #465131;">
</div>
</dd><dd>3. To <b>envince</b>; to prove.<br />
<div style="color: #465131;">
</div>
</dd><dd>4. To <b>overpower; to surmount; to vanquish.</b></dd><br />
<span class="Apple-style-span" style="background-color: white; font-size: 32px; font-weight: bold;"><a href="http://1828.mshaffer.com/d/word/rebuke" style="color: #7b8b4c; text-decoration: none;" title="[44941] 6 ">rebuke</a></span><br />
<span class="Apple-style-span" style="background-color: white;"></span><br />
<div style="color: #465131;">
<b style="color: #dad496; font-weight: bold;">REBU'KE,</b>&nbsp;v.t. [See Pack and Impeach.]</div>
<div style="color: #465131;">
</div>
<br />
<dd>1. To <b>chide</b>; to <b>reprove</b>; to reprehend for a fault; to check by reproof.<br />
<div style="color: #465131;">
</div>
</dd><dd>The proud he tam'd, the penitent he cheer'd, not to rebuke the rich offender fear'd.<br />
<div style="color: #465131;">
</div>
</dd><dd>Thou shalt in any wise rebuke thy neighbor. Lev. 19.<br />
<div style="color: #465131;">
</div>
</dd><dd>2. <b>To check or restrain</b>.<br />
<div style="color: #465131;">
</div>
</dd><dd>The Lord rebuke thee, O Satan. Zech. 3. Is. 17.<br />
<div style="color: #465131;">
</div>
</dd><dd>3. To <b>chasten</b>; to <b>punish</b>; to <b><u>afflict for correction</u></b>.<br />
<div style="color: #465131;">
</div>
</dd><dd>O Lord, rebuke me not in thine anger. Ps. 6.<br />
<div style="color: #465131;">
</div>
</dd><dd>4. <b>To check; to silence</b>.<br />
<div style="color: #465131;">
</div>
</dd><dd>Master, rebuke thy disciples. Luke 19.<br />
<div style="color: #465131;">
</div>
</dd><dd>5. <b>To check; to heal</b>.<br />
<div style="color: #465131;">
</div>
</dd><dd><b><u>And he stood over her and rebuked the fever. Luke 4</u></b>.<br />
<div style="color: #465131;">
</div>
</dd><dd>6. <b>To restrain; to calm.</b><br />
<div style="color: #465131;">
</div>
</dd><dd><b><u>He arose and rebuked the winds and the sea</u>. Matt. 8.</b><br />
<div style="color: #465131;">
<b style="color: #dad496; font-weight: bold;">REBU'KE,</b>&nbsp;n.</div>
<div style="color: #465131;">
</div>
</dd><dd>1. A chiding; reproof for faults; reprehension.<br />
<div style="color: #465131;">
</div>
</dd><dd>Why bear you these rebukes and answer not?<br />
<div style="color: #465131;">
</div>
</dd><dd>2. In Scripture, chastisement; punishment; affliction for the purpose of restraint and correction. Ezek. 5. Hos. 5.<br />
<div style="color: #465131;">
</div>
</dd><dd>3. In low language, any kind of check.<br />
<div style="color: #465131;">
</div>
</dd><dd>To suffer rebuke, to endure the reproach and persecution of men. Jer. 15.<br />
<div style="color: #465131;">
</div>
</dd><dd>To be without rebuke, to live without giving cause of reproof or censure; to be blameless.</dd><br />
<span class="Apple-style-span" style="background-color: white; font-size: 32px; font-weight: bold;"><a href="http://1828.mshaffer.com/d/word/exhort" style="color: #7b8b4c; text-decoration: none;" title="[20597] 6 ">exhort</a></span><br />
<span class="Apple-style-span" style="background-color: white;"></span><br />
<div style="color: #465131;">
<b style="color: #dad496; font-weight: bold;">EXHORT'</b>, v.t. egzhort'. [L. exhortor; ex and hortor, to encourage, to embolden, to cheer, to advise. The primary sense seems to be to excite or to give strength, spirit or courage.]</div>
<div style="color: #465131;">
</div>
<br />
<dd>1. To <b>incite </b>by words or advice; to <b>animate or urge by arguments</b> to a good deed or to any laudable conduct or course of action.<br />
<div style="color: #465131;">
</div>
</dd><dd></dd><dd>I exhort you to be of good cheer. Acts. 27.<br />
<div style="color: #465131;">
</div>
</dd><dd></dd><dd>Young men also exhort to be sober minded.<br />
<div style="color: #465131;">
</div>
</dd><dd></dd><dd>Exhort servants to be obedient to their masters. Tit.2.<br />
<div style="color: #465131;">
</div>
</dd><dd>2.<b> To advise; to warn; to caution</b>.<br />
<div style="color: #465131;">
</div>
</dd><dd>3. <b>To incite or stimulate to exertion.</b><br />
<div style="color: #465131;">
<b style="color: #dad496; font-weight: bold;">EXHORT'</b>, v.i. To deliver exhortation; to use words or arguments to incite to good deeds.</div>
<div style="color: #465131;">
</div>
</dd><dd></dd><dd>And with many other words did he testify and exhort. Acts.2.</dd><br />
<br />
<span class="Apple-style-span" style="background-color: white; font-size: 32px; font-weight: bold;"><a href="http://1828.mshaffer.com/d/word/exhortation" style="color: #465131; text-decoration: underline;" title="[20598] 11 ">exhortation</a></span><br />
<span class="Apple-style-span" style="background-color: white;"></span><br />
<div style="color: #465131;">
<b style="color: #dad496; font-weight: bold;">EXHORTA'TION</b>, n. The act or practice of exhorting; the act of inciting to laudable deeds; incitement to that which is good or commendable.</div>
<div style="color: #465131;">
</div>
<br />
<dd>1.<b> The form of words intended to incite and encourage</b>.<br />
<div style="color: #465131;">
</div>
</dd><dd>2. <b>Advice; counsel.</b></dd><br />
<span class="Apple-style-span" style="background-color: white;"></span><br />
<h1>

<a href="http://1828.mshaffer.com/d/word/exertion" style="color: #465131; text-decoration: underline;" title="[20560] 8 ">exertion</a></h1>
<br />
<div style="color: #465131;">
<b style="color: #dad496; font-weight: bold;">EXER'TION</b>, n.<b> The act of exerting or straining; the act of putting into motion or action</b>; effort; a striving or struggling; as an exertion of strength or power; an exertion of the limbs, of the mind or faculties. The ship was saved by great exertions of the crew. No exertions will suppress a vice which great men countenance.</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br /></div>
