---
title: 'Financial Increase'
date: '2011-10-07T02:52:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3134509380802699452'
blogger_filename: '/2011/10/financial-increase.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Need'
---

I was hit with a bit of news today. Training will not start on the 10th as planned, but on the 24th. This means instead of having an overlap (Extra) week of paycheck between jobs I will be a week behind. Praise God that the J.O.B. is NOT my source.<br />
<br />
My God's Grace is providing ALL I need, to the full, until it overflows into good works for others. I refuse to allow this to steal my faith. I will work these next two weeks as I would if I were fully self employed and God will bless it. Who knows... maybe things will become so productive so fast that I will have to turn down the job and really go fully self employed. Thank you Father for meeting my needs, no matter what the outcome!<br />
<br />
<br />
<span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 12px;"></span><br />
<h1 class="Title TitleSmall" style="color: #9d3300; font-size: 24px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; width: 525px;">
1 Corinthians 9:18 NLT</h1>
<br />
<span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 14px; line-height: 20px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">18</span>&nbsp;What then is my pay? It is the satisfaction I get from preaching the Good News without expense to anyone, never demanding my rights as a preacher.</span><br />
<span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 14px; line-height: 20px;"><br /></span><br />
<span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 12px;"></span><br />
<h1 class="Title TitleSmall" style="color: #9d3300; font-size: 24px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; width: 525px;">
2 Corinthians 9:5-12 (New Living Translation)</h1>
<br />
<span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 14px; line-height: 20px;"><span class="versetext" id="2co9-5" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">5</span>&nbsp;So I thought I should send these brothers ahead of me to make sure the gift you promised is ready. But I want it to be a willing gift, not one given under pressure.&nbsp;</span><span class="versetext" id="2co9-6" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">6</span>&nbsp;Remember this -- a farmer who plants only a few seeds will get a small crop. But the one who plants generously will get a generous crop.&nbsp;</span><span class="versetext" id="2co9-7" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">7</span>&nbsp;You must each make up your own mind as to how much you should give. Don't give reluctantly or in response to pressure. For God loves the person who gives cheerfully.&nbsp;</span><span class="versetext" id="2co9-8" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">8</span><b>&nbsp;And God will generously provide all you need. Then you will always have everything you need and plenty left over to share with others.</b>&nbsp;</span><span class="versetext" id="2co9-9" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">9</span>&nbsp;As the Scriptures say, "Godly people give generously to the poor. Their good deeds will never be forgotten."&nbsp;<a href="" name="a"></a></span><span class="versetext" id="2co9-10" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">10</span>&nbsp;For God is the one who gives seed to the farmer and then bread to eat. In the same way, he will give you many opportunities to do good, and he will produce a great harvest of generosity&nbsp;<a href="" name="b"></a>in you.&nbsp;</span><span class="versetext" id="2co9-11" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">11</span>&nbsp;Yes, you will be enriched so that you can give even more generously. And when we take your gifts to those who need them, they will break out in thanksgiving to God.&nbsp;</span><span class="versetext" id="2co9-12" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">12</span>&nbsp;So two good things will happen -- the needs of the Christians in Jerusalem will be met, and they will joyfully express their thanksgiving to God.</span></span><br />
<span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 12px;"></span><br />
<h1 class="Title TitleSmall" style="color: #9d3300; font-size: 24px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; width: 525px;">
2 Corinthians 9:5-12 (New King James Version)</h1>
<span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 14px; line-height: 20px;"><span class="versetext" id="2co9-5" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">5</span>&nbsp;Therefore I thought it necessary to exhort the brethren to go to you ahead of time, and prepare your generous gift beforehand, which you had previously promised, that it may be ready as a matter of generosity and not as a grudging obligation.&nbsp;</span><span class="versetext" id="2co9-6" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">6</span>&nbsp;But this I say: He who sows sparingly will also reap sparingly, and he who sows bountifully will also reap bountifully.&nbsp;</span><span class="versetext" id="2co9-7" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">7</span>&nbsp;So let each one give as he purposes in his heart, not grudgingly or of necessity; for God loves a cheerful giver.&nbsp;</span><span class="versetext" id="2co9-8" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">8</span><b>&nbsp;And God is able to make all grace abound toward you, that you, always having all sufficiency in all things, may have an abundance for every good work.</b>&nbsp;</span><span class="versetext" id="2co9-9" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">9</span>&nbsp;As it is written: "He has dispersed abroad, He has given to the poor; His righteousness endures forever."&nbsp;</span><span class="versetext" id="2co9-10" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">10</span>&nbsp;Now may He who supplies seed to the sower, and bread for food, supply and multiply the seed you have sown and increase the fruits of your righteousness,&nbsp;</span><span class="versetext" id="2co9-11" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">11</span>&nbsp;while you are enriched in everything for all liberality, which causes thanksgiving through us to God.&nbsp;</span><span class="versetext" id="2co9-12" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">12</span>&nbsp;For the administration of this service not only supplies the needs of the saints, but also is abounding through many thanksgivings to God,</span></span><br />
<span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 12px;"></span><br />
<h1 class="Title TitleSmall" style="color: #9d3300; font-size: 24px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; width: 525px;">
Philippians 4:6-13 (New King James Version)</h1>
<span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 14px; line-height: 20px;"><span class="versetext" id="php4-6" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">6</span>&nbsp;<b>Be anxious for nothing, but in everything by prayer and supplication, with thanksgiving, let your requests be made known to God</b>;&nbsp;</span><span class="versetext" id="php4-7" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">7</span>&nbsp;<b>and the peace of God, which surpasses all understanding, will guard your hearts and minds through Christ Jesus</b>.&nbsp;</span><span class="versetext" id="php4-8" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">8</span>&nbsp;Finally, brethren, whatever things are <b>true</b>, whatever things are <b>noble</b>, whatever things are <b>just</b>, whatever things are <b>pure</b>, whatever things are <b>lovely</b>, whatever things are of<b> good report</b>, if there is any <b>virtue </b>and if there is anything <b>praiseworthy</b>--<b>meditate on these things</b>.&nbsp;</span><span class="versetext" id="php4-9" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">9</span>&nbsp;The things which you learned and received and heard and saw in me, these do, and the God of peace will be with you.&nbsp;</span><span class="versetext" id="php4-10" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">10</span>&nbsp;But I rejoiced in the Lord greatly that now at last your care for me has flourished again; though you surely did care, but you lacked opportunity.&nbsp;</span><span class="versetext" id="php4-11" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">11</span>&nbsp;Not that I speak in regard to need, for I have learned in whatever state I am, to be content:&nbsp;</span><span class="versetext" id="php4-12" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">12</span>&nbsp;I know how to be abased, and I know how to abound. Everywhere and in all things I have learned both to be full and to be hungry, both to abound and to suffer need.&nbsp;</span><span class="versetext" id="php4-13" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">13</span><b>&nbsp;I can do all things through Christ&nbsp;<a href="" name="a"></a>who strengthens me.</b></span></span><span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 12px;"><div>
<br /></div>
</span><br />
<span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 14px; line-height: 20px;"><b><span class="versenum" style="margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">19</span>&nbsp;And my God shall supply <u>all your need</u> according to His riches in glory by Christ Jesus</b></span><br />
<br />
<br />