---
title: 'Full Circle to break the circle....'
date: '2011-10-03T22:55:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '80618208530096368'
blogger_filename: '/2011/10/full-circle-to-break-circle.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Life Events'
---

<span class="Apple-style-span" style="background-color: white; font-family: arial, sans-serif; font-size: 13px;"><br /></span><br />
<span class="Apple-style-span" style="background-color: white; font-family: arial, sans-serif; font-size: 13px;">I am going back to the call center...</span><span class="Apple-style-span" style="background-color: white; font-family: arial, sans-serif; font-size: 13px;">I am looking forward to this reset and refocus on life. I feel like my steps into the retail branch world were Spirit led, but it was more about learning some things and learning to appreciate other things. This move to the call center is really a move out of banking entirely long term.</span><br />
<span class="Apple-style-span" style="background-color: white; font-family: arial, sans-serif; font-size: 13px;"><br /></span><br />
<span class="Apple-style-span" style="background-color: white; font-family: arial, sans-serif; font-size: 13px;">I view it as my first step to being self/God employed. I am tired of working for man and men's ideas. I am taking steps to be a writer, blogger... And then we'll see.&nbsp;</span><br />
<span class="Apple-style-span" style="background-color: white;"></span><br />
<div style="font-family: arial, sans-serif; font-size: 13px;">
<br /></div>
<div>
<span class="Apple-style-span" style="font-family: arial, sans-serif; font-size: x-small;">I think I also realized that I am NOT a retail person, which means I want to OWN retaurants and coffee shops.... NOT RUN them... lol... At least not the day to day. I view them as business opportunities and investments not something to do.&nbsp;Entrepreneur&nbsp;not&nbsp;business&nbsp;owner.&nbsp;</span></div>
<div style="font-family: arial, sans-serif; font-size: 13px;">
<br /></div>
<div style="font-family: arial, sans-serif; font-size: 13px;">
We shall see... I have good feelings about 2012 and beyond.&nbsp;</div>
<div style="font-family: arial, sans-serif; font-size: 13px;">
<br /></div>
<div style="font-family: arial, sans-serif; font-size: 13px;">
Darrell G. Wolfe</div>
