---
title: 'Clean and Focus'
date: '2011-10-02T02:13:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3565849011635078506'
blogger_filename: '/2011/10/clean-and-focus.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Life Events'
---

My office is nearly clean and organized. I spent some time today doing that so that I could focus. I turned in my two week notice of resignation to Chase yesterday and as predicted they released me that day. HR says I still get paid for the two weeks and I get to keep any bonus I earned in Sept.<br />
<br />
This new schedule at Wells Fargo Inbound Sales will be 3-12 and should allow me time each day to focus on writing and blog work. It will also allow me time with the family and a venue for increase in general.<br />
<br />
There are pictures of things I am believing for like the book sales for BB4B and my Traverse on my wall.<br />
<br />
The kids are talking in the other room even though it's late. I'm ok with that today. I'm usually all pent up and frustrated with that. What harm is there in letting them talk themselves to sleep?<br />
<br />
I put together my dream book because the blog, although VERY useful, wasn't tangible enough for my "Daily Review" I will use Word to build the pages for the dream book and then copy them onto the website. Both tools are useful.<br />
<br />
I must remember to assign time daily to review my dreams, pray, read the word, meditate, confess the scriptures... I must keep seperate "Study" for writing and "Meditation" for growth. Ministers fall into that trap alot, thinking that the "Study" they do for messages and ministry counts as their word time. It doesn't. Meditation in the Word for ME is NOT the same as study for a message or teaching. I've had that issue alot myself. Most of my Word time is studying for some knowledge rather than meditating that word for my own growth.<br />
<br />
Office is nearly ready... Let the Word and Spirit flow freely here.