---
title: 'Feeling.... *sigh*... I don''t know'
date: '2012-11-01T04:46:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3563017505067179683'
blogger_filename: '/2012/10/feeling-sigh-i-dont-know.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Feelings'
---

I feel... tired. Like I could just go to sleep and wake up in 100 years in heaven and be just fine with that. I have become weary in well doing. In fact... I don't even WANT to do well anymore. I'm tired of going to work then leaving work to go to work... then coming home to hear we're still not caught up on anything. Then find out we spent more money we didn't have on new things and we still aren't caught up on old things. I hate life. I hate my life. I want to die... there I said it... I want to die.<br />
<br />
Ok, I guess I don't REALLY want to die... I just want for the rapture to come and end this life... I'll go to heaven without having earned any crowns but I can leave now.&nbsp;I don't enjoy anything really. I vaugely enjoy running sound for 14-forty, but I'm not that great at it, and I don't have time to learn more about it and get better. I might be happy if I did that type of thing full time?<br />
<br />
I didn't like Costco because I felt pressured there? I didn't like selling Western Clothes because I didn't make any money doing it. I didn't like retaurants because of all the pressure and fast pace. Too many things at once.<br />
<br />
I don't like Wells Fargo because I always feel like we're trying to sell people things when we really don't need to be. They say their aren't. They say they are doing needs based selling. But we're not. If we were, than I wouldn't be having to fix junk for the bankers who came before me. If we were needs based sales we'd sell less, because people don't need that much crap! If we were needs based sales it would start at the top and work through all departments. We're not needs based sales, we're just sales. Plain old, used car salesmen sales. Here, get this new shiny dodad... it'll solve the issue for you.<br />
<br />
Maybe... just maybe... I could do needs based sales. What would that look like? Several success articles have talked about imagining the sale going your way... what is my way? ...<br />
<br />
I light up when teaching people about credit or doing equity applications.<br />
<br />
I suppose my way would be for people to come over, want to talk to me, and tell me everything about themselves. I'd get them using their bill pay, online statements, turn off that stupid DCOS... then what?<br />
<br />
Take out an Auto or Home secured loan to consolidate other debts, maybe even get that approved.<br />
<br />
Then agree to talk to an Insurance/ITP/Mortgage Rep. Periodically talk to WFA when they have the need for it.<br />
<br />
Uhg... just trying to say all of that sounds exhausting and boring and irritating... I don't want that. I want to tell them to RUN away from the banks and go to a credit union.... I guess I'm not going to solve this tonight...<br />
<br />