---
title: 'Renew My Mind... Through Worship'
date: '2012-11-18T06:22:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6063757050529598665'
blogger_filename: '/2012/11/renew-my-mind-through-worship.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Need'
  - 'Feelings'
  - 'Growing Up'
---

I've spent time reading and listening to Mac Hammond. Simplifying Your Life and A Change of Mind. I've also spent time listening to Worship Songs today. I cried, for the first time in a long time. Really cried. Sobbed. Broke down. It was wierd. But cleansing. Almost nice.<br />
<br />
I thought about Calvary Chapel Worship Services. They always felt so warm, open, broken, cleansing... but never served to provide any lasting change.<br />
<br />
I thought about Oasis and it's praise pumping, Heritage and it's sermon-in-a-song... EMIC and it's.... I don't know what EMIC Adult service is...<br />
<br />
Then I start working 14-Forty and I get introduced to cutting edge worship... youth worship... hard core, open, broken, building, emotion in your face worship. This is the kind of worship that produces alter calls without anyone having to say anything. This is what God meant by me worshipping Him like I did when I was younger. It's the HEART of the worship I've been missing, not just the music.<br />
<br />
If I'd spend more time in these kinds of woship songs daily... I'd probably notice a change in every other attitude I've struggled with, and every other decision I need to make would seem clearly, the voice of God would be more rich and ever-present to me... That's what He's been trying to get me to do for 10+ years now.... I've been trying to learn music and guitars.... that's all fine and well, and probably much MORE a part of my callig than I've realized. (I think I may need to go back to school for a Music Degree) but that's not the heart of what He's been asking. It's the WORSHIP that he's been asking for... because it changes me... into Him!<br />
<br />
<br />
<br />
<iframe allowfullscreen="allowfullscreen" frameborder="0" height="315" src="http://www.youtube.com/embed/TCunuL58odQ" width="560"></iframe>

<br />
<br />
<iframe allowfullscreen="allowfullscreen" frameborder="0" height="315" src="http://www.youtube.com/embed/TRiT9Ds4ch4" width="560"></iframe>

<br />
<br />
<iframe allowfullscreen="allowfullscreen" frameborder="0" height="315" src="http://www.youtube.com/embed/OyT9W5C1L-4" width="560"></iframe>

<br />
<br />
<br />
<iframe allowfullscreen="allowfullscreen" frameborder="0" height="315" src="http://www.youtube.com/embed/-97vww2xQJw" width="560"></iframe>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />