---
title: 'Judgement'
date: '2012-09-28T04:02:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '980882716630844129'
blogger_filename: '/2012/09/judgement.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Reading'
---

Just finished reading <a href="http://www.amazon.com/The-Harbinger-ancient-mystery-Americas/dp/161638610X" target="_blank">Harbinger</a>. America is being judged. We have turned from our founding. I always knew this was the case, but I didn't really believe it could be otherwise. Then Kenneth Copeland started&nbsp;prophesying&nbsp;that America's Best days were still ahead, that God wasn't through with her yet and she wasn't through with Him yet! Now I read this book about the 9/11 wake up call.<br />
<br />
*Looking back... 9/11/2001 marked the&nbsp;beginning&nbsp;of the end of my 1st marriage... judgement hit my house, me saying I can do it on my own and I don't need God... Hmm... *<br />
<br />
I know now, more than ever, that my calling to reach the lost within the church is more important than my need for a cheeseburger or Dr Pepper. It's time to start fasting and praying, to move past the flesh and find out what I'm supposed to be doing with my life.<br />
<br />
Lately God has been moving in me to believe him for $50,000/Year with ONE job and time to write. I also believe I'm supposed to take a more active role in the sound/media ministry at EMIC. I've been working 14-forty since July every Wed. But I feel I should be there Tuesdays as well. Robert asked me if I could be there Sunday and I'm working at Cheesecake and I found that grieved me. Deeply.<br />
<br />
I should NOT be working two jobs. There is something more I should be doing.<br />
<br />
However I've also been running around the same mountain for years and years. I get a new job. I'm excited about the possibilities and the good things about it. SHORTLY thereafter I become aware of all of the NOT SO GREAT things. Then I start complaining about the job, the policies, the bosses. In the end I feel like I'm protecting customers FROM the company. Then I quit before I can get fired. It's the&nbsp;rhythm&nbsp;of every job I've had. I stay as diligent a worker as I can, so MOST of my employers want me back. But then I look for a new job.<br />
<br />
The BLESSING of God will send me into a place to bring THE BLESSING in there. In some cases I saw it working and didn't know what it was. I figured it was because I was there. Now I realize that was THE BLESSING trying to work in me and through me.<br />
<br />
<b>LESSON</b><br />
<br />
I must learn:<br />
<br />
<ul>
<li>Report to God for Assignment as HE is my employer</li>
<ul>
<li>PRAY DAILY</li>
<ul>
<li>Tongues</li>
<li>Ask God for HIS assignment</li>
<li>IN YOUR ROOM BEFORE GETTING READY TO LEAVE (Read and Pray)</li>
</ul>
<li>SPEAK BLESSING and REBUKE CURSE</li>
<li>SPEAK LOVE and REBUKE STRIFE (complaining, bitterness, eye rolling, dread, fear, anxiety, etc...) Be motivated by LOVE for others.&nbsp;</li>
<ul>
<li>At Wells Fargo: LOVE your fellow Sales Specialists, Referring Bankers, Bosses, Etc...</li>
<li>At Cheesecake: LOVE your guests, and LOVE will still your mind!</li>
</ul>
</ul>
<li>Continue my Soda Fast until Jan 1st.&nbsp;</li>
<li>????</li>
</ul>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />