---
title: 'Storyteller'
date: '2013-08-05T07:46:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '661533313506283480'
blogger_filename: '/2013/08/storyteller.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Answers'
  - 'Ministry'
  - 'Revelation'
---

You are a story teller. You've been trying to hide it behind factual writing, but you are a story teller. You tell stories on the phone to your customers. You most enjoy recounting life as a story to others. Writing, Music, Audio, Theatre, Movies, Acting, Preaching, Teaching, ... It's all about storytelling!<br />
<br />
What makes a story so compelling? Why have you read hundreds of warnings about America but can remember nearly none of the details and yet you can remember Harbinger as though you read it yesterday? Why can you still remember the basic details of every fictional book and/or movie you've ever seen?<br />
<br />
Story implants in us what facts and figures never can.<br />
<br />
Music, then, enhances it. It opens the mind and heart to receive the message. Music is dangerous in the wrong hands because it opens us up to the wrong message. Satanic music opens us to Satanic stories. Godly music opens us up to Godly stories.<br />
<br />
Music plays a pivitol role. It can move us in deep ways words can't by themselves. However, music that moves with no words is like opening the door to never enter the room. You can peak inside and see some things, but you cannot take full advantage of the room.<br />
<br />
Tell THE Story, through stories... Use your passion for Heros, Sci Fi, Supernatural, Fantasy, and Epic Adventures to start a revolution!<br />
<br />
Let IT take you, as led by the Word and the Holy Spirit, and tempered by your wife.<br />
<br />
HS