---
title: 'Key Messages 2013'
date: '2013-04-19T10:17:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8025635269022174813'
blogger_filename: '/2013/04/key-messages-2013.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Answers'
  - 'Ministry'
  - 'Growing Up'
  - 'Vision'
---

<br />
<br />
These KEY messages&nbsp;completely&nbsp;impacted my life for 2013...<br />
<br />
Sunday 11:00 AM | STAND Rick Renner 02/03/13<br />
<br />
Sunday 11:00 AM | The Word - Spirit and Life Kenneth Copeland 03/03/13<br />
<br />
Sunday 9:00 AM | God's Promotion Pastor George Pearsons 02/17/13<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="separator" style="clear: both; text-align: center;">
</div>
<br />
<br />
<blockquote class="tr_bq">
<div style="text-align: center;">
<b><span style="font-size: 8pt; line-height: 12px;">Promotion</span></b></div>
<span style="font-size: 8pt; line-height: 12px;">Pastor changed his message just to address the very struggle I’ve been dealing with for months. It’s a struggle that came to a head recently and it is causing me to come to a fork in the road soon. I’ve talked it over with JoAnn and Flavia.</span><span style="font-size: 8pt; line-height: 12px;">I’ve been mad at my company. Ready to leave for their flagrant lack of integrity. How can I continue to work for a company that deals with people this way? &nbsp;Maybe I should just leave. I’m on the verge of a promotion there, but then I’ll have to be the leader representing a company that isn’t doing right by people. Then I keep staring at the Word of the Lord from Kenneth Copeland for 2013: “<b><u>Stay where you are</u></b>. Stay steady. Why? Your greatest blessing ever is at hand…” I’ve tried to ignore it, I’ve tried to argue with it. I’ve asked does that really mean Wells Fargo? Maybe it just means 14-forty where I’m serving now… God told me at the end of 2012 to believe him for “One Job, “Tailor Fit” More than Enough ($50+)”&nbsp; I have an interview with another company and some positions coming up at WF. I don’t know which way to go. Both look good. In 2010 I came to this same cross road and left the Phone Bank for the branch. I gave up a guaranteed leadership position that was mine for the taking and I went, I believe, the wrong way. My whole life is full of giving up and quitting before promotion comes. It’s been a theme. I’ve been at WF 7 years without taking a leadership role officially. But it’s so negative that I don’t know what to do. I hear “Stay where you are…” and I think “WHY?! What blessing is coming there!” At church today God had something to say about it through Pastor George.</span></blockquote>
<blockquote class="tr_bq">
<b><span style="font-size: 8pt; line-height: 12px;">Promotion</span></b><b><span style="font-size: 8pt; line-height: 12px;">Pastor George Pearsons 02/17/2013 9 AM service (Time 3:50 into message)</span></b><span style="font-size: 8pt; line-height: 12px;">Be BLESSED! Blessed means to be empowered to prosper. Prosperity means complete success!</span><span style="font-size: 8pt; line-height: 12px;">Deut 8:18 “You shall remember the Lord your God, for it is He that gives you power(capacity/force) to get wealth…”</span><span style="font-size: 8pt; line-height: 12px;">Prospering in every area of your life… What you do on the job prospering. Being just like Joseph. You just continue to rise to the top. No matter what is going on around you. No matter what is happening around you. You continue to rise to the top. You continue to rise to the top.</span><i><span style="font-size: 8pt; line-height: 12px;">Now this is something that is coming out of my heart now for you: Now if you are in a job situation, and it seems to be surrounded by strife, people of strife, stuff’s going on in there, do not…</span></i><i><span style="font-size: 8pt; line-height: 12px;">Number one insist on walking in the Love of God, you insist on walking in the Love of God. Number two, you stay above the fray, don’t dip down into it, don’t be talking (this is a Word from the Lord) don’t be talking to other people about it, don’t be getting on the phone and talking to people about that situation, you stop it right now, you cut that off! And you gain altitude over it, when you do that by praying in the Holy Ghost, you can look down on that thing, and you can know exactly what to do, exactly how to handle it, but you keep your mouth shut over that thing right now, you just stop it, you just stop talking about it. And here is the result of it God will lift you up… He will lift you up. He will lift you up above that situation. He’ll bring you above that situation so that He can deal with what’s going on down there. And then He’ll set you back down in it. You see that? Do you see that? Now for those of you who that means something to you take hold of that and you stay above the fray.</span></i><span style="font-size: 8pt; line-height: 12px;">(Story about Kenneth Hagin praising God with his staff to stop strife)</span><span style="font-size: 8pt; line-height: 12px;">You have to handle things like this above the fray. You’ve got to step up above that and not allow that to control you, to control your emotions, to control your words, because your words have got to line up with The Word of God. And don’t, don’t get down in there and be a part with the devil of being an accuser of the brethren. Or speaking ill of against other people. The Lord is going to work that out I’m telling you! He’s going to work that out.</span><span style="font-size: 8pt; line-height: 12px;">Now Father I pray over these situations in the name of Jesus and I thank you that each and every one of us, in whatever situation we are faced with, these agitating situations on the job, or even at home, Father we are rising above it right now, we are insisting in walking in Love, we are staying in the Word, we are staying steady, we are unwavering in our stand. And Father we believe for the moving of the Holy Spirit…</span><span style="font-size: 8pt; line-height: 12px;">Somebody’s wondering right now; can the Holy Spirit move on the secular corporation that I work with? OH YES! OH YES! Absolutely! Did God move in Egypt through Joseph? Yes! Yes He did. He turned that nation around because of Joseph. Because of Joseph being there, and the same thing with Joseph everywhere he went. He turned that situation around. He was a living breathing BLESSING of God wherever he went, and whatever he did. Wherever he showed up, that anointing that was on him to prosper, just was flowing out from him. And it changed Egypt to where Egypt was blessed during that time of famine because God put a man in there who was operating in the wisdom, the wisdom of God. They even said when they were talking about him: “There’s a man here who operates in the wisdom of God.” It’s the same thing with Daniel. Daniel did the same thing, that man was in a foreign land. He was not home. But he was controlling the whole thing from his prayer closet. Moving that whole thing, shifting that whole thing right there. So can God move in your business, can God move in the Corporation that you work for? Absolutely! And what I believe is that God is looking for people in the Body of Christ who will walk in places of integrity, walk in places of Honor, people who do not lie, people who do not cheat, people who are walking on the Word of God, and their only motivation for being on that job is to do exactly what Jesus said, “I am among you as one who serves.” A servants heart, a servants heart. Allowing that servants heart to flow through you. And we are going to see some things take place in these major corporations. That God is going to lift up the Humble. God is going to lift up into places of promotion those people that He wants set in there to do that job, to run that business, to run that corporation, He is going to do it with His people….</span></blockquote>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
