---
title: '2014/02/27 Journal Thu'
date: '2014-02-27T13:36:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3483799059630758134'
blogger_filename: '/2014/02/20140227-journal-thu.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<p>VOD<br>
Psalms 107</p>
<p>19Then they cry unto the Lord in their trouble,<br>
and he saveth them out of their distresses.<br>
20He sent his word, and healed them, and<br>
delivered them from their destructions.<br>
21Oh that men would praise the Lord for his<br>
goodness, and for his wonderful works to the<br>
children of men!</p>
<p>Feeling<br>
Good about the test for cusps and the job fair for the credit union.</p>
<p>Thankful<br>
For the people I can use as references and the many opportunities there are for jobs. Even if it's not exactly what I want yet.</p>
<p>What's Happening<br>
I got so frustrated I punched my desk. Broke it. Fixed it. But it's been a long time since I hit anything.</p>
<p>Ed heard about it and had to make a note. Also separately I'm on pip for sales.</p>
<p>New job here I come! I've been on plans before and climbed right out. But this is different ... I have no plan to get better. I'm at a total loss.</p>
<p>Lord. Deliver me from these things! </p>
<p><u>D</u></p>
<p>Today's faith to faith devoted... could be a story idea...</p>
<p>Believers who have died and come back say that<br>
they have no sensation of loss--no sting. Their<br>
minds stay intact, and they even have arms and<br>
legs, but they are spirit and not flesh. One man<br>
said he couldn't even tell he wasn't in his body<br>
until he tried to grasp something. His hand<br>
would just go right through the material object.<br>
He was spirit and not flesh.<br><br><br></p>
