---
title: 'Writing As Healing... Interesting Idea.'
date: '2014-04-13T03:51:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2648301044158302182'
blogger_filename: '/2014/04/writing-as-healing-interesting-idea.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Revelation'
---

<h3 style="background-color: white; color: #222222; font-family: arial, sans-serif;">
<a href="http://goinswriter.com/your-story/?utm_source=feedburner&amp;utm_medium=feed&amp;utm_campaign=Feed%3A+GoinsWriter+%28Goins%2C+Writer%3A+On+Writing%2C+Ideas%2C+and+Making+a+Difference%29" target="_blank">Connecting with my old story</a></h3>
<div style="background-color: white; color: #222222; font-family: arial, sans-serif; font-size: 13px;">
I allowed my memory to glide back in time, to re-enter a scene in which I ran away at the age of four and had to be returned home by a neighbor who had been out searching for me.</div>
<div style="background-color: white; color: #222222; font-family: arial, sans-serif; font-size: 13px;">
I focused on the details: my mother sitting on the bottom step of our olive green-carpeted 70s stairs, coarse caramel-colored wallpaper climbing up the wall beside her, a radiator lined with drying clothes to our left.&nbsp;How she pulled me into her arms and squeezed me so tight I could barely breathe. The sound of saliva slipping down her throat as she swallowed hard.</div>
<div style="background-color: white; color: #222222; font-family: arial, sans-serif; font-size: 13px;">
And in, remembering these details I felt the emotion again, the guilt and anger at seeing her cry once more.&nbsp;As I relived this memory, I barely noticed the tears slipping down my cheeks or the stiffness in my hands from typing so fast, but I do remember the way I felt when I typed that last period.</div>
<div style="background-color: white; color: #222222; font-family: arial, sans-serif; font-size: 13px;">
Relieved. Released. Unburdened.</div>
<div style="background-color: white; color: #222222; font-family: arial, sans-serif; font-size: 13px;">
I began to write about many different scenes and circumstances from my past in the same way, always focusing on what I could see, hear, smell and see, and the emotions that accompanied me as I re-entered those memories.</div>
<div style="background-color: white; color: #222222; font-family: arial, sans-serif; font-size: 13px;">
And I became fascinated with the process of writing as a form of healing.</div>
