---
title: 'Today is September 29, 2014 |'
date: '2014-09-29T13:16:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '547232175522917112'
blogger_filename: '/2014/09/today-is-september-29-2014.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
</h4>
<br />
<h3>
Daily Routine:</h3>
<h4>
BE STILL: Just Listen, write down what He tells you.&nbsp;</h4>
<div>
<b>What did God say today?</b></div>
<br />
<b>God Said:&nbsp;</b><br />
<br />
Appraise and Polish the ring. It has had a trail of broken marriages, end that.<br />
<br />
<br />
<h4>
PRAYER: This is the time I do some talking, but still listening also.</h4>
<br />
<i><a href="http://biblehub.com/niv/1_timothy/1.htm" target="_blank"><b>1 Timothy 1</b></a></i><br />
<i>18Timothy,
 my son, I am giving you this command in keeping with the prophecies 
once made about you, so that by recalling them you may fight the battle 
well, 19holding on to faith and a good conscience, which some have 
rejected and so have suffered shipwreck with regard to the faith. 
20Among them are Hymenaeus and Alexander, whom I have handed over to 
Satan to be taught not to blaspheme.
</i><br />
<br />
<i><a href="http://biblehub.com/context/1_timothy/2-1.htm" target="_blank"><b>1 Timothy 2</b></a></i><br />
<i>1
 First of all, then, I urge that entreaties and prayers, petitions and 
thanksgivings, be made on behalf of all men, 2 for kings and all who are
 in authority, so that we may lead a tranquil and quiet life in all 
godliness and dignity. 3 This is good and acceptable in the sight of God
 our Savior, 4 who desires all men to be saved and to come to the 
knowledge of the truth. 5 For there is one God, and one mediator also 
between God and men, the man Christ Jesus, 6 who gave Himself as a 
ransom for all, the testimony given at the proper time. 7 For this I was
 appointed a preacher and an apostle (I am telling the truth, I am not 
lying) as a teacher of the Gentiles in faith and truth. 8 Therefore I 
want the men in every place to pray, lifting up holy hands, without 
wrath and dissension.</i><br />
<div>
<br />
<div>
<a href="http://biblehub.com/greek/1162.htm" target="_blank">Entreaties </a>(specific felt need),&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/4335.htm" target="_blank">Prayers </a>(exchange of desires/wishes),&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/1783.htm" target="_blank">Petitions/Intersessions</a>
 (Intersection of heaven and earth, hit the bullseye, request something 
specific of a King. Technical/Civil term: VERY specific requests that 
meet an exact need!).&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/2169.htm" target="_blank">Thanksgivings</a> ( Lit: giving thanks for God's grace! Gratitude, Thankfulness)</div>
<div>
These are to be made on behalf of:&nbsp;</div>
<div>
<ul>
<li><b>FIRST </b>for <b>all people</b>, then <b>Kings</b>, <b>Leaders</b>, those in <b>Authority</b>, then you would be included in all men, so your family, kin folk, etc.&nbsp;</li>
<li>Pray for:&nbsp; </li>
<ul>
<li><b>God desires all men to:</b> Be saved and come to the knowledge of the Truth.&nbsp;</li>
<li>Filled with the knowledge of His will through all Wisdom. <a href="http://biblehub.com/colossians/1-9.htm" target="_blank">Col 1:9</a></li>
<li>They may be given the Spirit of Wisdom and revelation in the knowledge of Him. (<a href="https://www.biblegateway.com/passage/?search=Ephesians+1%3A15-23&amp;version=NKJV" target="_blank">Eph 1:15-23</a>)</li>
<ul>
<li>Understanding Be Enlightened.</li>
<li>Know the Hope of His calling.</li>
<li>Riches through inherited Glory.</li>
<li>Exceeding greatness of His power to those who believe. </li>
</ul>
</ul>
</ul>
</div>
</div>
<i><br /></i>
<b>Did anything else come up in prayer that should be notated?&nbsp;</b><br />
<i><br /></i>
<i>Godly leadership. Awakening in this nation. </i><i><br /></i>
<i><br /></i>
<i><br /></i>
<br />
<h4>
BIBLE: Instead of a bible devotional, I'm going to do a bible study.&nbsp;</h4>
<div>
Take one of Kenneth's study notes from the front of my bible and do those.</div>
<div>
JOURNAL entry will include all of the above, and anything else on my mind at the time. Take a moment to jot down:</div>
<div>
<br /></div>
<div>
You version.</div>
<div>
<br /></div>
<div>
<h4>
JOURNAL: What's Up Today?&nbsp;</h4>
</div>
<br />
<b>How you are feeling:</b><br />
<div>
<br /></div>
<div>
I'm feeling a mix of uncertainty about the future, and an expectation (hope) rising within that things are improving for us. The Freedom Ministry needs to be a priority for me. </div>
<div>
</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br />
<div>
<b>What you are believing:</b></div>
<div>
<br /></div>
<div>
Unknown. Somedays I'm believing that we're all going to make it. Other days I'm believing I should just send them off to ID and be single again. Today I'm believing we're going to make it.</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<b>What's happening in your life right now:</b></div>
<div>
<br /></div>
<br />
Possible promotion is coming soon. Interviews are over, now we wait for a decision. Work has been good. Preston's birthday just ended. Mom visited and left. The weather has cooled down. The drivers window still isn't working in the van, and the air conditioning is out too. We need to fix the van and get a second car.<br />
<br />
I'll need to ask God what to do about that.<br />
<br />
DW </div>
