---
title: 'The Vision... 2013'
date: '2014-01-01T03:28:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8517709483600383836'
blogger_filename: '/2013/04/the-vision-2013.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Need'
  - 'Answers'
  - 'Growing Up'
  - 'Vision'
---

<h4>
The Vision... As of 2013</h4>
<h4>
In 2013</h4>
<ul>
<li><b>Get Promoted:</b></li>
<ul>
<li>One job</li>
<li>$50,000+</li>
<li>40 hours</li>
<li>Self determined-flexible schedule</li>
<li>Own Office</li>
<li>Task/Project Oriented (Not Sales Goals Oriented)</li>
</ul>
<li><b>Write</b></li>
<ul>
<li>Complete "Call to Excellence" the Book</li>
<ul>
<li>Begin working on the Study Guides/Class Material</li>
</ul>
<li>Complete Financial Workshop Material</li>
<li>Blog when Inspired:</li>
<ul>
<li>Empowered To Prosper </li>
<li>N2 Good Success</li>
</ul>
<ul>
<li>Texas Living Info</li>
</ul>
</ul>
<li><b>Pursue Music</b></li>
<ul>
<li>Audio Training - After much research and prayer, got led to a brand new school!</li>
<ul>
<li>&nbsp;<b>School of the Tech Arts - Gateway Southlake - Kings Univ.</b></li>
<ul>
<li><b>Starts Thursday August 22nd!!</b></li>
</ul>
</ul>
<li>Guitar</li>
<li>Define what Music is to me and my future</li>
</ul>
</ul>
<div>
<br /></div>
<h4>
In 2014</h4>
<div>
<ul>
<li><b>Writing</b></li>
<ul>
<li>Call To Excellence</li>
<ul>
<li>Complete any work on Call to Excellence</li>
<li>Begin Teaching Call to Excellence</li>
</ul>
<li>Financial Workshops</li>
<ul>
<li>Begin (if not already) teaching financial workshops for ministries</li>
<ul>
<li>Esp those dealing with the destitute.</li>
</ul>
</ul>
<li>Grow the N2GoodSuccess Blog and TexasLiving Blog</li>
</ul>
<li><b>Music</b></li>
<ul>
<li>Define and Pursue the vision for Music in my life?</li>
</ul>
<li><b>Work</b></li>
<ul>
<li>One Job</li>
<li>More Than Enough</li>
<li>Tailor Fit</li>
<ul>
<li>Either be self employed</li>
<li>Or working one super awesome job!</li>
</ul>
</ul>
<li><b>Finance</b></li>
<ul>
<li>Be Debt Free</li>
</ul>
</ul>
</div>
<h4>
5-10 Years</h4>
<div>
<ul>
<li><b>Sowed </b>the Zavala House (debt free) into the right people/person</li>
<li><b>Living </b>back in CA smack dab in the middle of God's perfect Will for us.</li>
<li><b>Doing </b>everything God has called me to do at a high level of excellence and results</li>
</ul>
</div>
<div>
<br /></div>
<h4>
The Future...</h4>
<div>
<ul>
<li><b>Be Preaching/Ministering/Teaching/(Pastoring?)</b></li>
<ul>
<li>Kingdom of God Ministries?</li>
<li>Property in Indio, CA?</li>
<li>Traveling Ministry?</li>
<li>Written and Distributed Books</li>
<li>Full Time Blog Traffic</li>
</ul>
<li><b>Be Debt Free</b></li>
<ul>
<li>Totally Debt Free</li>
</ul>
<li><b>Own Businesses</b></li>
<ul>
<li>Coffee Shops</li>
<li>Cornerstone&nbsp;Concepts Restaurants&nbsp;</li>
<ul>
<li>Soda Shop</li>
<li>Space Theme</li>
</ul>
</ul>
<li><b>Own Properties</b></li>
<ul>
<li>For the Wolfe Family</li>
<ul>
<li>Ranch Property for us</li>
<li>Cabin in ID</li>
<li>Disney Timeshare?</li>
</ul>
<li>As Investments</li>
<ul>
<li>Rental Homes</li>
<li>Rental Condo's</li>
</ul>
<li>As Seed</li>
<ul>
<li>Sow Homes Away</li>
</ul>
</ul>
</ul>
</div>
<div>
<br /></div>
<div>
To Be Edited and Reviewed on a regular basis... DW 04/14/2013</div>
