---
title: '2014/02/04 Journal Tue'
date: '2014-02-04T13:39:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8863465380196922129'
blogger_filename: '/2014/02/20140204-journal-tue.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
VOD</h4>
<br />
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=84&amp;user_id=darrellwolfe&amp;version=1" target="_blank">LUKE 15</a><br />
<br />
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #888888; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17.33333396911621px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v25" data-usfm="LUK.15.25" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-size: 17.33333396911621px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">25</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; font-size: 17.33333396911621px; margin: 0px; padding: 0px;">Now his elder son was in the field: and as he came and drew nigh to the house, he heard musick and dancing.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #888888; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17.33333396911621px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v26" data-usfm="LUK.15.26" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-size: 17.33333396911621px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">26</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; font-size: 17.33333396911621px; margin: 0px; padding: 0px;">And he called one of the servants, and asked what these things meant.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #888888; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17.33333396911621px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v27" data-usfm="LUK.15.27" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-size: 17.33333396911621px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">27</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; font-size: 17.33333396911621px; margin: 0px; padding: 0px;">And he said unto him, Thy brother is come; and thy father hath killed the fatted calf, because he hath received him safe and sound.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #888888; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17.33333396911621px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v28" data-usfm="LUK.15.28" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-size: 17.33333396911621px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">28</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; font-size: 17.33333396911621px; margin: 0px; padding: 0px;">And he was angry, and would not go in: therefore came his father out, and intreated him.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #888888; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17.33333396911621px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v29" data-usfm="LUK.15.29" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-size: 17.33333396911621px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">29</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; font-size: 17.33333396911621px; margin: 0px; padding: 0px;">And he answering said to his father, Lo, these many years do I serve thee, neither transgressed I at any time thy commandment: and yet thou never gavest me a kid, that I might make merry with my friends:</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #888888; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17.33333396911621px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v30" data-usfm="LUK.15.30" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-size: 17.33333396911621px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">30</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; font-size: 17.33333396911621px; margin: 0px; padding: 0px;">But as soon as this thy son was come, which hath devoured thy living with harlots, thou hast killed for him the fatted calf.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #888888; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17.33333396911621px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v31 focused" data-usfm="LUK.15.31" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #444444; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">31</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17.33333396911621px; margin: 0px; padding: 0px;">And he said unto him, Son, thou art ever with me, and all that I have is thine.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #888888; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17.33333396911621px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v32" data-usfm="LUK.15.32" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-size: 17.33333396911621px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">32</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17.33333396911621px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; font-size: 17.33333396911621px; margin: 0px; padding: 0px;">It was meet that we should make merry, and be glad: for this thy brother was dead, and is alive again; and was lost, and is found.</span></span></span></div>
<br />
<br />
JP Devotional<br />
<span style="background-color: #eeedeb; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 17.280000686645508px;">Like the father in the parable, God has already given you an inheritance in Christ. Don’t fail to enjoy it by doubting God’s goodness or by believing that you must work for it. See your Father’s heart of love and goodness toward you, and celebrate your inheritance today!</span><br />
<br />
<h4>
Thankful</h4>
<br />
I am thankful today for Ed Reiss, who despite our not always seeing eye to eye, really does care about his staff and their success. And I'm thankful for Flavia who sees me as I am, and as I will be.<br />
<br />
<h4>
Feeling</h4>
I am feeling... slightly less stressed about my current job after my talk with Ed. But only slightly. Taking call after call of mindless stupidity is just unbearable. People getting abused by customer service and transfered to sales without knowing why is un acceptable. Hang up after hang up. It's just one big pointless merry go round. I have to get off and do something meaningful.<br />
<br />
<h4>
What's up?</h4>
<br />
I think I need to pull out of Audio. I didn't even feel the slightest pull between going there or going to a AAA interview tomorrow. Time to look for another avenue of service. Maybe this upcoming orientation for technical something or other will be good?<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />