---
title: 'Tuesday | 09/23/2014'
date: '2014-09-23T12:53:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6607954062475969716'
blogger_filename: '/2014/09/tuesday-09232014.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<p dir=ltr>Mom's leaving today' back for CA. What if today were the last time I saw her on earth? It's a weird thought, but its been on my mind for&nbsp; few moments now. I'm not as kind to her as I should be. I'm cold, distant, more than with most people. I don't know why. </p>
<p dir=ltr>Preston just turned 7. He said it was his best birthday ever. That's cool. </p>
<p dir=ltr>Connor... What am I going to do with Connor? Why do we bump heads so often? The Only word that. Ones to mind is control. We are both vying for control?</p>
<p dir=ltr>Am I ever going to be truly happy to have this family? Will I ever not wish for a different life? Will I ever be wholly devoted to God, and not tied to the old sin in my heart? Prosperity aside, I'd take average but free inside... How?</p>
<p dir=ltr>Lord, help me find, know, and understand freedom from my internal sins in a true and lasting way. Right now I'm saved, born again, but not free... I was filled with HolySpirit at one time, but maybe... Maybe I haven't been " being filled"?</p>
<p dir=ltr>Preston just walked in, time to start this day.</p>
