---
title: '2014/03/05 Journal Wed'
date: '2014-03-05T15:14:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3722759208126971914'
blogger_filename: '/2014/03/20140305-journal-wed.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12.222222328186035px; line-height: 24.000001907348633px; margin-bottom: 20px; padding: 0px;">
<br /><a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=113&amp;user_id=darrellwolfe&amp;version=1" target="_blank">Day 113</a><br />When It Is More Blessed To Receive<br />Luke 10:42<br />42… Mary has chosen that good part, which will not be taken away from her.”&nbsp;</blockquote>
<blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12.222222328186035px; line-height: 24.000001907348633px; margin-bottom: 20px; padding: 0px;">
If Jesus comes to your home, what would you do? Would you ask Him to sit down and then start serving Him? Or would you sit down and start drawing from Him? Would you let Him serve you and fill you up?</blockquote>
I think I'm doing this. I think I'm serving, but seeking his presence. To the point that I get burnt out on serving. I'll need to re-address my calendar and put the big rocks in first.<br />
<h4>
Thankful:</h4>
I'm thankful that I have a job I can call out of when I feel awful and nobody asks questions.<br />
<br />
<br />
<h4>
Feeling:</h4>
I am feeling better today than yesterday. Still dealing with feelings of depression and anxiety.<br />
<br />
<h4>
What's Up?</h4>
<br />
Today I stay home with kids while Flavia goes shopping for quilting material.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />