---
title: '2014/02/09 Journal Sun'
date: '2014-02-09T14:02:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2457754629636040659'
blogger_filename: '/2014/02/20140209-journal-sun.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
Hebrews 8:10,12<br />10… I will put My laws in their mind… I will be their God… 12… I will be merciful to their unrighteousness…their sins and their lawless deeds I will remember no more.”<br /><span style="background-color: #eeedeb; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px;">It is foolish for me to just tell you, “Come on, man, have faith!” You will still find it hard to have faith because I am not giving you anything to build faith in you. But if I were to tell you all about what God says He will do for you, faith will arise in your heart. Faith is a response to knowing what God says He will do for you.</span><br /><a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">JP Devotional</a></blockquote>
<br />
<h4>
Thankful:</h4>
I'm thankful today for laughs and random provisions. My kids really enjoyed that LEGO Movie.<br />
<br />
<h4>
Feeling:</h4>
Frustrated that I TRY to do the right thing at work and still end up with the same results as NOT TRYING.<br />
<br />
I feel the sales goals, as always, are unrealistic and leadership at WF is totally out of touch with reality.<br />
<h4>
What's Up?</h4>
I'm expecting to hear from AAA by next Saturday. Going to church today.<br />
<br />
<br />