---
title: '2014/03/24 Journal Mon Car For Sale. Listen and Obey.'
date: '2014-03-24T13:04:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3275129108946883803'
blogger_filename: '/2014/03/20140324-journal-car-for-sale-listen.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
COME:<br />
<br />
<br />
<a href="http://e.kcm.org/HM?a=ENX7CqkTRT6y8SA9MKJreDvnGHxKL86ZmfcStGb5lw8W0bBhOG5mpqVsje_Hhe-jNFF5" target="_blank">Faith To Faith</a><br />
<blockquote class="tr_bq" style="background-color: white; color: #222222; font-family: arial, sans-serif; font-size: 14px; line-height: 18px; margin-top: 15px; padding: 0px;">
<br />
<span style="background-color: white; color: #666666; font-family: arial, sans-serif; font-size: 16px; line-height: 18px;">He who being often reproved hardens his neck, shall suddenly be destroyed, and that without remedy. - Proverbs 29:1</span><br />
Some people have the mistaken idea that when the direction of the Holy Spirit comes to them, they can just ignore it for a while if they want to and then obey Him later in their own good time. They think to themselves, "I know what I'm doing is wrong. I know my lifestyle isn't right, but I'm just going to do it a while longer. Then I'll get things straightened out with the Lord."<br />
Let me warn you, that is an extremely dangerous thing to do. Because God says that when you refuse His guidance, your heart grows hard. It's not that God's grace doesn't extend to you anymore. It's not that He wouldn't forgive you if you turned to Him. It's just that sin will callous your heart to the point where you can't hear Him calling.</blockquote>
Don't refuse God's Leading... Don't wander in the wilderness the rest of your life.<br />
<br />
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">JP Devo</a><br />
<blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;">
Day 132<br />
Continue In God’s Grace<br />
2 Corinthians 3:6<br />
6… for the letter kills, but the Spirit gives life.<br />
To the Jews, the feast of Pentecost is a celebration of the giving of God’s law. It takes place 50 days after the Passover feast. When God gave the Israelites the Ten Commandments at Mount Sinai, it was 50 days after they had celebrated their first Passover and come out of slavery in Egypt.<br />
But what happened after God gave them the law on the first Pentecost? Three thousand people died! (Exodus 32:28) Contrast this with another Pentecost in the New Testament. In the book of Acts, it says that when Pentecost had fully come, God gave not the law but the Holy Spirit, and what happened? Three thousand people got saved (Acts 2:41), which goes to show that “the letter [the law] kills, but the Spirit gives life”!</blockquote>
<div style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;">
</div>
<br />
<br />
<br />
HERE:<br />
<br />
How often do I ignore God's leading? Daily? Yet I'm living in the age of Grace. So God can continue to view me through His Son! But that doesn't change the fact this is exactly how I've been feeling... hard inside.<br />
<br />
<br />
DO:<br />
<br />
I'm going to listen today for things to obey, little things if need be. Wear that instead of that. Etc.<br />
<br />
<br />
<h4>
Thankful:</h4>
I'm thankful for Joseph Prince and Kenneth Copeland.<br />
<br />
<h4>
Feeling:</h4>
I've been feeling this hardness for years. I go into Church and feel hard there. Distant. Maybe this obedience thing will play a huge role?<br />
<br />
<h4>
What's Up?</h4>
Put the Ford up for sale. Got a scam text first thing this morning, which is why I didn't put my full address on the listing. Late for work. Bye for now.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />