---
title: '2014-01-06 Journal Monday'
date: '2014-01-06T14:58:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8246899616041522535'
blogger_filename: '/2014/01/2014-01-06-journal-monday.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
  - 'Ministry'
  - 'Revelation'
  - 'Life Events'
  - 'Vision'
---

2014-01-06 Journal Monday<br />
<br />
Day Three. I tried using Several Journals.<br />
-Penzu; https://penzu.com/p<br />
-Evernote<br />
-<b>Blogger</b><br />
-<b>GNotes</b><br />
<br />
I settled in on GNotes because it was lighter weight for my phone than evernote therefore I could use it on the computer and mobile. Easier to access than blogger that way too. Blogger was too distracting also because I would want to make it more of a clean post and this is for me not an audience. Penzu was nice but the app and online wouldn't sync without the paid version and we're behind on several bills so that's not a luxery I can stand too.<br />
<br />
<i>... GNotes started freezing up as I wrote this entry. Blogger has a better reputation. I transfered my Journal entries to Fed By Faith, which was originally built to be my online private journal anyway. I know their reputation. I'll probably still use GNotes when I'm mobile and then transfer that too Blogger when I'm home? We'll see. I think GNotes is better for a quick note, not a long entry.&nbsp;</i><br />
<br />
It's too bad, had they put more into the free version they probably would have had me hooked for the paid version later. I guess that's a lesson for me. When I do products that are free and paid, make sure the free version is packed with cool features and the paid version just takes it over the top. With all my data in the free version I'd want to upgrade to the paid eventually. So I'm using GNotes for now.<br />
<br />
Connor can be a bit intrusive and in your face, but he means well and I need to help him hone that gift set into something that will be useful to him and others and not squash it.<br />
<br />
I should schedule time to blog/journal for them. I set them up with their own blogs as a gift to them. I should actually use them. 2014 is a new year.<br />
<br />
Preston isn't feeling well. We prayed over him this morning and gave him some medicine to help.<br />
<br />
<h4>
Thanks:</h4>
I'm thankful for Jesus. Flavia and our newly reborn romance. My two kids who are both fun and creative and intelligent. I'm thankful for GNotes providing this tool.<br />
<br />
<h4>
Feeling:</h4>
I'm feeling annoyed at Connor interrupting me and being loud this morning. I could be grateful instead that he is full of energy and life and that his inquisitive mind is fully functioning. Feeling a bit put out that we're not going to see the nutcracker today but also fearful of using money for that when we're behind on bills.<br />
<br />
<h4>
DREAM:</h4>
I had a dream last night. I pull up in a van to a car dealership. Make some comments to another person about how the really old car is "like new" because it's in mint condition not because it's actually new. Then next to the parking lot is a restaurant/hospital? Someone from work, a boss, asks me to help and I say I'll be right there I just need to put my shoes on. I go in and ask for her and she says that there is this man that was out in the parking lot just crazy as a lune that needs someone to talk to. Mixture of mental insanity and physical damage to the brain I think. He's lost a wife I think. He's like the homeless men that walk around yelling at "no-one-visible". I walk up to him and ask him if he needs help and he mumbles something. I lay hands on his shoulder and pray in tongues and he snaps to attention and starts praying in tongues too and he's healed, totally healed. I walk down a paved path of steps through a garden and find another woman like the man, mentally unstable. I lay my hands on her forehead and pray in tongues and she does too and then she starts praising God and her family runs over to see what's happening and they're shocked to see her talking normal.<br />
<br />
<h4>
Interpretation:</h4>
Flavia and I were talking yesterday about the idea that "Ministry" doesn't happen in the walls of the Church, Ministry happens outside in the real world, the Church is there to train PEOPLE to do the ministry. I wrote a note in my Church Notes:<br />
<blockquote class="tr_bq">
NOTE: What if you viewed YOUR ministry as that which you do outside the "church" walls.</blockquote>
I wondered then and now, what if I viewed everything I do as my Ministry. What if I'm not called to work in the confines of a Church but out in the marketplace. Writing, Blogging, Public Speaking, Property, Music, and yes, laying hands on people at hospitals, restaurants, and out on the street. What if I viewed Texas Living, DarrellWolfe.Com, and Author Fun as my Ministries and treated them with that level of diligence and respect? Interesting thought.<br />
<br />
Good thought but I've spent too much time on this entry already. To Be Continued.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div>
<br /></div>
