---
title: 'Successful Failure'
date: '2014-10-26T22:58:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5240167925015441552'
blogger_filename: '/2014/10/successful-failure.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

Today has been a day that feels mildly successful. I did the lawn, dishes, and bug stuff. Tasks have been crossed off ToDoist. <br />
<br />
Today has been a reminder of how much my life has turned out to be one big failure. I live in a house with an upside down mortgage, and I'm behind on the payment... again... I mowed the lawn with an old broken down lawn mower because I can't afford a new one. For that matter, I can't afford a Gardener. I have one car, with a broken window, air conditioner, God knows what else is wrong with the lights and grinding sound, and I'm like 6 months behind on the oil change.<br />
<br />
I'm failure at Parenting. I can't be in the same room with one of my kids for more than 5 minutes without being totally annoyed, and I the other one still likes me, but I ignore his request for quality time, so he won't like me for much longer either. And I don't know if I can find it within myself to do anything about any of it.<br />
<br />
I either need to die in some freak accident (because I'd never do that on purpose), or maybe I need to send them all to Idaho, sell the house, and go find a studio near Irving? I'm just tired of trying to be... what? What am I trying to be?<br />
<br />
That's so sad... I don't even know what it is I'm trying to be that I'm failing at.<br />
<br />
What a waste of a high IQ I turned out to be. 