---
title: '2014/02/03 Journal Mon'
date: '2014-02-03T13:23:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '766833532040176375'
blogger_filename: '/2014/02/20140203-journal-mon.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<h2 style="background-color: white; color: #013976; font-family: Arial, Helvetica, sans-serif; font-size: 17px; line-height: 1.2em; margin: 0px; padding: 0px;">
<a href="http://www.kcm.org/index.php?p=daily_devotional" target="_blank">Out of the Shadow</a></h2>
<span style="background-color: white; color: #837d70; font-family: Arial, Helvetica, sans-serif; font-size: x-small; line-height: 16.899999618530273px;">Kenneth Copeland</span><br />
<div class="print_quote" style="background-color: white; color: #5f5a50; font-family: Georgia, 'Times New Roman', Times, serif; font-size: 17px; font-style: italic; line-height: 1.7em; margin-top: 16px; padding: 0px;">
The next day John seeth Jesus coming unto him, and saith, Behold the Lamb of God, which taketh away the sin of the world.</div>
<div class="scripture_reference" style="background-color: white; color: #5f5a50; float: right; font-family: Georgia, 'Times New Roman', Times, serif; font-size: 17px; font-style: italic; line-height: 1.7em; padding: 0px;">
– John 1:29</div>
<br />
<br />
<a href="http://i%20remember%20one%20time%20in%20particular%20when%20i%20was%20in%20that%20spot.%20i%27d%20missed%20it%20something%20awful%2C%20and%20i%20was%20supposed%20to%20go%20preach%20that%20night.%20i%20felt%20so%20guilty%20that%20i%20just%20told%20the%20lord%20i%20wasn%27t%20going%20to%20go.%20%22lord%2C%20you%27ll%20just%20have%20to%20get%20yourself%20another%20preacher%20tonight%20because%20i%27m%20not%20going%20over%20there%20to%20that%20service.%22%20%20suddenly%20the%20spirit%20spoke%20up%20inside%20me.%20%22did%20you%20confess%20that%20sin%20before%20me%2C%20kenneth/?%22%20%20%22Yes,%20I%20did.%22%20%20%22Do%20you%20account%20the%20blood%20by%20which%20you%27re%20sanctified%20as%20an%20unholy%20thing?%22%20%20%22Oh,%20dear%20God,%20no!%22%20I%20answered.%20%20%22That%27s%20what%20you%27re%20standing%20there%20doing,%22%20He%20said.%20%22I%20gave%20you%20My%20Word%20that%20when%20you%20confess%20your%20sin%20before%20Me,%20I%20would%20not%20only%20forgive%20you%20of%20it,%20but%20I%27d%20cleanse%20it%20and%20cast%20it%20into%20a%20sea%20of%20forgetfulness.%20Now%20it%27s%20not%20good%20taste%20for%20you%20to%20keep%20bringing%20it%20up.%22%20%20I%27m%20telling%20you,%20I%20dropped%20the%20matter%20right%20then%20and%20marched%20into%20that%20service%20and%20preached%20for%20two%20and%20a%20half%20hours%20on%20the%20forgiveness%20of%20God!" target="_blank">Excerpt From Faith To Faith</a><br />
<div style="background-color: white; color: #837d70; font-family: Arial, Helvetica, sans-serif; font-size: small; line-height: 16.899999618530273px; margin-bottom: 16px; margin-top: 16px; padding: 0px;">
I remember one time in particular when I was in that spot. I'd missed it something awful, and I was supposed to go preach that night. I felt so guilty that I just told the Lord I wasn't going to go. "Lord, You'll just have to get Yourself another preacher tonight because I'm not going over there to that service."</div>
<div style="background-color: white; color: #837d70; font-family: Arial, Helvetica, sans-serif; font-size: small; line-height: 16.899999618530273px; margin-bottom: 16px; margin-top: 16px; padding: 0px;">
</div>
<div style="background-color: white; color: #837d70; font-family: Arial, Helvetica, sans-serif; font-size: small; line-height: 16.899999618530273px; margin-bottom: 16px; margin-top: 16px; padding: 0px;">
Suddenly the Spirit spoke up inside me. "Did you confess that sin before Me, Kenneth?"</div>
<div style="background-color: white; color: #837d70; font-family: Arial, Helvetica, sans-serif; font-size: small; line-height: 16.899999618530273px; margin-bottom: 16px; margin-top: 16px; padding: 0px;">
</div>
<div style="background-color: white; color: #837d70; font-family: Arial, Helvetica, sans-serif; font-size: small; line-height: 16.899999618530273px; margin-bottom: 16px; margin-top: 16px; padding: 0px;">
"Yes, I did."</div>
<div style="background-color: white; color: #837d70; font-family: Arial, Helvetica, sans-serif; font-size: small; line-height: 16.899999618530273px; margin-bottom: 16px; margin-top: 16px; padding: 0px;">
</div>
<div style="background-color: white; color: #837d70; font-family: Arial, Helvetica, sans-serif; font-size: small; line-height: 16.899999618530273px; margin-bottom: 16px; margin-top: 16px; padding: 0px;">
"Do you account the blood by which you're sanctified as an unholy thing?"</div>
<div style="background-color: white; color: #837d70; font-family: Arial, Helvetica, sans-serif; font-size: small; line-height: 16.899999618530273px; margin-bottom: 16px; margin-top: 16px; padding: 0px;">
</div>
<div style="background-color: white; color: #837d70; font-family: Arial, Helvetica, sans-serif; font-size: small; line-height: 16.899999618530273px; margin-bottom: 16px; margin-top: 16px; padding: 0px;">
"Oh, dear God, no!" I answered.</div>
<div style="background-color: white; color: #837d70; font-family: Arial, Helvetica, sans-serif; font-size: small; line-height: 16.899999618530273px; margin-bottom: 16px; margin-top: 16px; padding: 0px;">
</div>
<div style="background-color: white; color: #837d70; font-family: Arial, Helvetica, sans-serif; font-size: small; line-height: 16.899999618530273px; margin-bottom: 16px; margin-top: 16px; padding: 0px;">
"That's what you're standing there doing," He said. "I gave you My Word that when you confess your sin before Me, I would not only forgive you of it, but I'd cleanse it and cast it into a sea of forgetfulness. Now it's not good taste for you to keep bringing it up."</div>
<div style="background-color: white; color: #837d70; font-family: Arial, Helvetica, sans-serif; font-size: small; line-height: 16.899999618530273px; margin-bottom: 16px; margin-top: 16px; padding: 0px;">
</div>
<div style="background-color: white; color: #837d70; font-family: Arial, Helvetica, sans-serif; font-size: small; line-height: 16.899999618530273px; margin-bottom: 16px; margin-top: 16px; padding: 0px;">
I'm telling you, I dropped the matter right then and marched into that service and preached for two and a half hours on the forgiveness of God!</div>
<br />
<br />
<span style="color: #030404; font-family: calluna, 'Trebuchet MS', Tahoma, Verdana, sans-serif; font-size: 17px; letter-spacing: 0.5039999485015869px; line-height: 26.8799991607666px;">Joshua 1:8 says the Word will cause you to prosper “in whatever you do,” whether it be your marriage, health, finances, career or raising your children. Believing what Psalm 1:1–3 says will change our lives and our habits. But, conversely, if we don’t meditate on the Word day and night, what does that make us? We’ll be like trees not planted by water. We’ll dry up and wither, and we won’t bear fruit. - See more at: http://gatewaydevotions.com/it-is-written/day-3#sthash.kblmI6PK.dpuf</span><br />
<br />
<h4>
Thankful:</h4>
I am thankful for this office, and My continuing to hone into the right routine and schedule to balance work/life. Lord, continue to help me find the perfect Rhythm.<br />
<br />
<h4>
Feeling:</h4>
I am feeling... hopeful? This Wed will be the AAA interview. Maybe something good will come of it.<br />
<h4>
What's Up?</h4>
I'm getting ready for work in a few minutes. Flavia cut my hair last night. Looks good. Still getting used to have hair, the shaved head was so much easier. I got nothing else to say. DW<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />