---
title: '2014/03/02 Journal Sun'
date: '2014-03-02T14:46:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4774019668845179527'
blogger_filename: '/2014/03/20140302-journal-sun.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<p>VOD<br>
Deuteronomy 28<br>
Jesus redeemed us from the second half of this chapter.</p>
<p>Feeling<br>
Wild swings from hopefulness that things are about to change for the better to depression that I am an abject failure in every area of my life. </p>
<p>Thankful<br>
Listened to an NPR TED talks podcast on happiness.</p>
<p>Gratefulness was a cause not a by product.</p>
<p>Mind wandering tended toward the negative was a cause for unhappiness. Bible says that the meditation of the heart has a role in life.</p>
<p>I guess I need to cultivate a meditation of Gratefulness.</p>
<p>What's Up...<br>
Flavia pointed out that I'm always seeing the negative side of a situation. In the car I'm calling other drivers stupid. Work: customers and coworkers can't do right by me.</p>
<p>"Nothing is ever good enough..."</p>
<p>Why? Why can't I be happy like the retarded kids?</p>
<p>The happiness study showed the opposite of mind wandering was being fully present in the moment.&nbsp; Those who were fully engaged in what they were doing were more happy.</p>
<p>Job... How could this relate to the Bible book of Job?</p>
<p>Job became bitter as he recounted the past both good and bad... in his own perspective of it.</p>
<p>Financial life is crashing around us. Job I'm nearly fired. No passion to write. Depressed. I'm living a mini Job experience.</p>
<p>His key was not figuring out what he did wrong. His key was finding out who God really was. After the trial in times of peace God may show you an area of correction.</p>
<p>During the trial you have really only two choices. Magnify yourself. Magnify God.<br><br></p>
