---
title: '2014/03/07 Journal Fri - Do I really want to work at QT?'
date: '2014-03-07T14:04:00.0040000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7203542744718719340'
blogger_filename: '/2014/03/20140307-journal-fri.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<br />
<blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">Day 115</a><br />
Let Jesus Wash Your Feet<br />
John 13:8<br />
8Peter said to Him, “You shall never wash my feet!” Jesus answered him, “If I do not wash you, you have no part with Me.”&nbsp;</blockquote>
<blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;">
Can you imagine the Lord wanting to wash your feet? Peter could not. His shocked reaction — “Lord, how can you wash my feet!” — would probably be ours too.</blockquote>
<blockquote class="tr_bq">
<span style="background-color: #eeedeb; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px;">Once we have accepted Christ as our Lord and Savior, we are bathed all over, and cleansed by His blood once and for all eternity! His blood has perfected us forever (Hebrews 10:14), and we only need to wash our feet because we walk in the world and our feet pick up dust and dirt, causing us to stumble....</span><span style="background-color: #eeedeb; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px;">by washing our feet with a deeper revelation of Himself through His Word. Beloved, this is what gives us victory in our daily walk!</span></blockquote>
<br />
<a href="http://empoweredtooprosper.blogspot.com/2014/03/the-secret-key-to-being-happy.html" target="_blank">The Key To Being Truly Happy</a><br />
<br />
<br />
<h4>
Thankful:</h4>
<br />
Today I am thankful for opportunity. I may not have seen the exact options I want, but I have options. I'm in the USA. If I don't want to work at company X then I can go get a job at company ZB.<br />
<br />
I am Thankful that God is leading and guiding my search, when I let Him.<br />
<br />
I'm Thankful for my family. We are not perfect, but we are together. My kids are pretty cool too, when I take the time to appreciate them.<br />
<br />
<h4>
Feeling:</h4>
I'm feeling pretty nervous now.<br />
<br />
It was one thing to spout off about wanting a new job and "...flipping burgers would be better than taking phone calls for Wells Fargo..." But would it? Is going to QT as a Assistant Night Manager at $11/Hour plus OT working 46 hours plus, equaling $36,000/Year... is that better? I mean there's no sales goals. There's also no lunch or break time. You are GO GO GO... You literally eat between customers. You are lifting trash cans, cleaning bathrooms, etc... I did SAY I should just be a janitor, but is that really what I meant?<br />
<br />
What about a line full of people at QT. Can I ring them all up without any drawer mistakes? I'm not good at math on the fly. Would that be worse pressure than sales goals? And now I'd have to go buy Khaki pants?<br />
<br />
More importantly... is this good for my family? Is this better for them? I'm gone ALL night, sleeping during the day when they are trying to get things done? Maybe it is, because they could go places with the car.<br />
<br />
I'm getting cold feet on this idea.<br />
<br />
<br />
<h4>
What's Up?</h4>
In spite of the above? I just need out of the phone bank sales job. But... what do I REALLY want? I want an office, computer, paperwork... I don't want to be outside or getting dirty. I'd rather just get a lateral move or promotion in WF to a job with less sales and more operations. That's what I'd really like. I don't want to learn a new culture and a new way, with less benefits.<br />
<br />
Father. This is me. Asking. In writing. Please give me a job on the operations side, with no sales goals, where I just process paperwork and computer stuff, within Wells Fargo. Loan Underwriting. That would be great.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />