---
title: '2014/02/11 Journal Tue'
date: '2014-02-11T13:37:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7414682381155339853'
blogger_filename: '/2014/02/20140211-journal-tue.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=91&amp;user_id=darrellwolfe&amp;version=1" target="_blank">Joseph Prince Devotional on Youversion</a><br />Proverbs 4<br /><span class="verse v20 focused" data-usfm="PRO.4.20" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #444444; font-size: 16.666667938232422px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">20</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; margin: 0px; padding: 0px;">My son, attend to my words; incline thine ear unto my sayings.</span></span><span class="verse v21 focused" data-usfm="PRO.4.21" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #444444; font-size: 16.666667938232422px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">21</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; margin: 0px; padding: 0px;">Let them not depart from thine eyes; keep them in the midst of thine heart.</span></span><span class="verse v22 focused" data-usfm="PRO.4.22" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #444444; font-size: 16.666667938232422px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">22</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; margin: 0px; padding: 0px;">For they are life unto those that find them, and health to all their flesh.</span></span><span class="verse v23" data-usfm="PRO.4.23" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-size: 16.666667938232422px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">23</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; margin: 0px; padding: 0px;">Keep thy heart with all diligence; for out of it are the issues of life.</span></span><span class="verse v24" data-usfm="PRO.4.24" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-size: 16.666667938232422px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">24</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; margin: 0px; padding: 0px;">Put away from thee a froward mouth, and perverse lips put far from thee.</span></span><span class="verse v25" data-usfm="PRO.4.25" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-size: 16.666667938232422px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">25</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; margin: 0px; padding: 0px;">Let thine eyes look right on, and let thine eyelids look straight before thee.</span></span><span class="verse v26" data-usfm="PRO.4.26" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-size: 16.666667938232422px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">26</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; margin: 0px; padding: 0px;">Ponder the path of thy feet, and let all thy ways be established.</span></span><span class="verse v27" data-usfm="PRO.4.27" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-size: 16.666667938232422px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">27</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 16.666667938232422px; margin: 0px; padding: 0px;">Turn not to the right hand nor to the left: remove thy foot from evil.</span></span>&nbsp;</blockquote>
<blockquote class="tr_bq">
<br /><span style="background-color: #eeedeb; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px;">When you are going through a tough time, it is not enough to know that God’s answer to the problem is “somewhere in the Bible”. Find the scripture in which God has promised the solution. Meditate on it until the truth of that scripture is revealed to you. When you do this, no demon or devil can prevent that word from God from bearing fruit in your life.</span></blockquote>
<br />
<h4>
Thankful:</h4>
I"m thankful for technology. It allows me to get devotionals I may not of thought to buy and keep up with them in a way that is easier for my brain.<br />
<h4>
Feeling:</h4>
Starting to feel that "Messy Middle" Michael Hyatt talks about. I know I'm not supposed to hear an answer from AAA until the end of this week, but I at thought the HR person would reply to my email to her with more questions. The lack of communication has me... uneasy.<br />
<br />
Let that be a lesson for myself. When someone sends me something that will take time to respond to. Send them a quick reply that it will take some time to respond to. You could even create a warm template for that response and just send that.<br />
<br />
<h4>
What's Up?</h4>
The answer to every question is THE WORD. I need to spend more time in the Word, not just devotionals about the Word with a verse or two attached.<br />
<br />
It's freezing outside<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />