---
title: '2014/04/11 Journal Fri sigh*** I surrender all'
date: '2014-04-12T05:17:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4298153279530561480'
blogger_filename: '/2014/04/20140411-journal-fri-sigh-i-surrender.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<p>It's the end of the day. I started work well ended in the same quagmire of depression I end up in everyday.</p>
<p>I'm sure it's selfishness that causes the depression : what I want, I need, I can't take anymore...</p>
<p>But it's so hard to watch a vision I believe in die before my eyes while the leadership refuses to acknowledge there's even a problem.</p>
<p>It's hard to watch people transferred to sales not because a genuine need was found but because service has to meet their warm transfer numbers.</p>
<p>It's hard to then see that the only people calling in are the:</p>
<p>. Very old<br>
. Very young<br>
. Mentally unstable<br>
. Foreign Language<br>
. All other technologically challenged people's</p>
<p>Because anyone with Money is going to premier and anyone with any tech saavy (90% of active customers) are just doing things online. They only call when they can't do it for themselves.</p>
<p>Maybe that's just it. I only saw premier service for the first 3.5years. Maybe the vision never did exist at surface level...</p>
<p>I feel I need to document this so I remember why I left. How every day I wanted to die instead of going to work and facing that depressing mix of broken people who need a solution the bank can't offer and the bank trying to shove more broken product at them. Like odp which solves nothing. </p>
<p>They call these "solutions", but in fact they are selling useless services to people who have no needs because someone said that a metric must be met... </p>
<p>Then... When the day is done. I turn off the computer ... I sit there often for 30-40 minutes delaying coming home to a wife that picks at me and a kid that fights me tooth and nail... the other kid I have no problems with, but I don't do any better job with him. He just doesn't push as hard for my attention.</p>
<p>At Church. I started resenting serving in AV after one service. So I resigned "until my schedule straightened out".</p>
<p>My spiritual life is a wreck. I don't pray much I barely read my Bible. I have spurts of inspired study followed by relapses into bad thinking and periodically fall back into internet addictions.<br></p>
<p>I'm a failure at my job, at home, a church, and inside myself. To thine own self I am not true. I'm a shame.</p>
<p>Lord Jesus, I can't count how often I've given myself back to you. But I feel I'm coming to the end of myself, again...</p>
<p>If you can still make something of me, even if that something is just the person my family needs me to be emotionally for them, please do.</p>
<p>I surrender my dreams and visions to you? What am I doing wrong? Or rather is there ANYTHING I'm doing right?</p>
<p>I surrender all...<u>dw</u></p>
