---
title: '2014/01/15 Journal Wed'
date: '2014-01-16T03:48:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3312477828247252080'
blogger_filename: '/2014/01/20140115-journal-wed.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

&nbsp;Journal 1/15/2014 1/15/2014<br />
<br />
&nbsp;Prayer @gatewaypeople<br />
I forgive my mom for being human and not making perfect decisions. I allow her, and others in my life the grace to fail.<br />
<br />
I accept that I need not see the answer, just know Him who has it. And trust Him.<br />
<br />
Be being filled... not once, but continually.<br />
<br />
Fear of opportunity is opportunity risk. Not going is a potential opportunity loss. Going is also opportunity loss. Options. Get Flavia to put it in perspective. Pray following peace. If you feel there could be something, go if it's not too much cost.<br />
<br />
What's happening: came to prayer @gateway this morning. Meeting Jack here in a few minutes. Have an interview with psav, &nbsp;not sure its worth going to. Pay is too small. But I felt a small something to go, &nbsp;and the recruiting agent on the phone really seemed to think I should at least consider some free lance work with them.<br />
<br />
Feeling _ scared that its a waste of time. Resigned to at least get to see gaylord Texan hotel.<br />
<br />
Thankful for my Jesus that has already provided all my needs.<br />
<br />
------ Notes throughout the day-----<br />
<br />
&nbsp;- 1/15/2014 02:49 PM<br />
&nbsp;- psav... it's good to realize I'm thinking bigger. I feel more like I belong to this resort as a guest than a worker.<br />
&nbsp;- I'm not interested in working really hard to maybe make $50k<br />
&nbsp;-<br />
<br />