---
title: '2014/03/11 Journal Tue -- Hear His Voice. Find Your Sweet Spot'
date: '2014-03-11T13:16:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '925531416651737726'
blogger_filename: '/2014/03/20140311-journal-tue-hear-his-voice.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<div>
COME:</div>
<blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;">
<br />
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">Day 119</a><br />
Jesus, Your Good Shepherd And Door<br />
John 10:7<br />
7Then Jesus said to them again, “Most assuredly, I say to you, I am the door of the sheep.<br />
<br />
As your door, He keeps out everything evil that He has redeemed you from. Because He shed His blood for you, you are covered and protected within the sheepfold by a blood-stained door. Disaster, destruction and death must pass over you and your family because of His blood on your door. Remember that on the night of the first Passover in Egypt, the destroyer could not enter the houses of the Israelites because of the blood of the lamb on their doors. (Exodus 12:13, 23)<br />
Today, you can live life untroubled and unafraid, knowing that Jesus, your good shepherd and door, protects and preserves you and your family. No evil will befall you or your loved ones because He is your dwelling place and refuge!</blockquote>
<blockquote class="tr_bq">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">John 10 NASB</a><span class="verse v7 focused" data-usfm="JHN.10.7" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 34px; margin: 0px 0px 0px 3px; padding: 0px; text-indent: 17px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">7</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;">So Jesus said to them again,&nbsp;</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">"Truly, truly, I say to you, I am the door of the sheep.</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v8" data-usfm="JHN.10.8" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #888888; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 34px; margin: 0px 0px 0px 3px; padding: 0px; text-indent: 17px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">8</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; font-size: 17px; margin: 0px; padding: 0px;">All who came before Me are thieves and robbers, but the sheep did not hear them.</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v9" data-usfm="JHN.10.9" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #888888; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 34px; margin: 0px 0px 0px 3px; padding: 0px; text-indent: 17px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">9</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; font-size: 17px; margin: 0px; padding: 0px;">I am the door; if anyone enters through Me, he will be saved, and will go in and out and find pasture.</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v10" data-usfm="JHN.10.10" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #888888; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 34px; margin: 0px 0px 0px 3px; padding: 0px; text-indent: 17px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">10</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; font-size: 17px; margin: 0px; padding: 0px;">The thief comes only to steal and kill and destroy; I came that they may have life, and have&nbsp;</span><span class="it" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; font-style: italic; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; font-size: 17px; margin: 0px; padding: 0px;">it</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; font-size: 17px; margin: 0px; padding: 0px;">&nbsp;abundantly.</span></span></span></blockquote>
***<br />
<blockquote class="tr_bq">
<span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #aaaaaa; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px; text-indent: 17px;">16</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #888888; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 34px; margin: 0px; padding: 0px; text-indent: 17px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; font-size: 17px; margin: 0px; padding: 0px;">I have other sheep, which are not of this fold; I must bring them also, and they will hear My voice; and they will become one flock&nbsp;</span><span class="it" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; font-style: italic; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; font-size: 17px; margin: 0px; padding: 0px;">with</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; font-size: 17px; margin: 0px; padding: 0px;">&nbsp;one shepherd.</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #888888; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 34px; margin: 0px; padding: 0px; text-indent: 17px;">&nbsp;</span>&nbsp;</blockquote>
<br />
<br />
<br />
HERE:<br />
<br />
Jesus is the door of the sheepfold. He is the blood stained entrance that kept them safe during passover in Egypt. I've never seen that connection before! Jesus died for ME!<br />
<br />
He came to give me abundant life. If I'm not living it... why? The answer is often found in "Keep Reading". I notice that "Hear My Voice" is before "Become one flock with one shepherd." I also notice that I was among the gentiles that were "not of that fold".<br />
<br />
It's when I heard His voice that I became his sheep. Therefore it's by hearing his voice continually that I will remain protected within his sheepfold.<br />
<br />
<br />
<br />
DO:<br />
<br />
I will practice hearing his voice today.<br />
<br />
<br />
<br />
<h4>
Thankful:</h4>
I am thankful today, for Connor, who always asks lots of questions. And Questions are the driver for a successful life!<br />
<br />
<br />
<h4>
Feeling:</h4>
I am feeling hopeful about today. I've been given some tools that will help me better succeed on my calls.<br />
<br />
I also feel that a new job is near.<br />
<h4>
What's Up?</h4>
I've been learning about sales techniques and principles I hadn't quite understood before. Mandy at work has studied sales longer than I've studied banking and money. Took good notes.<br />
<br />
If my sweet spot is at the intersection of my greatest strength and my greatest passion... QT is a distraction not a prize.<br />
<br />
My greatest strengths are found in dealing information (written first, verbally second).<br />
<br />
My greatest passion is helping people succeed, teaching, solving mind puzzles.<br />
<br />
Underwriting wouldn't have me teaching, but it would have me putting things together. So of the available options some kind of "process" job like underwriting or back office stuff would be good for me.<br />
<br />
<br />
I'm late again... DW<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />