---
title: 'July 4th 2014 - Southwest Believers Convention'
date: '2014-07-05T07:19:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3446322356997465207'
blogger_filename: '/2014/07/july-4th-2014-southwest-believers.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Answers'
  - 'Scripture'
  - 'Car'
  - 'Vision'
  - 'Word From God'
  - 'Journal'
---

I have been either a participant, volunteer, or at least spectator of a KCM Believers Convention every year since 2003. I've only made it to a full convention, every session, once, the first year, before Connor was born. Every year I went to less and less of it. Until eventually I had to watch/listen afterward every year, because I was working trying to keep up with bills. I've been behind on bills since July 2004... I hate bills.<br />
<br />
So this year, 2014, after the first session with brother Copeland, I sent the following text to my mentor:<br />
<br />
<br />
<a href="http://empoweredtooprosper.blogspot.com/2014/07/swbc-2014-convention-notes.html" target="_blank">My Notes</a>&nbsp;are on my word journal.<br />
<br />
I left pondering these things:<br />
<br />
<div>
<ul>
<li>Your problem is your big mouth, you need to learn the vocabulary of silence.&nbsp;</li>
<li>You need to make a quality decision.&nbsp;</li>
<li>Your Father wants to provide for you for no other reason than He is your Father.&nbsp;</li>
<li>Like you observed in one child's attitude's today: it's hard to bless someone who is demanding, ungrateful, pushy, rude, not thinking of others, not a giver... etc.</li>
<ul>
<li><i>*not that this child is always this way, but it was the attitude today.&nbsp;</i></li>
</ul>
<li>You cannot give to God as though he were an ATM, stock investment, or lottery ticket, and expect to receive anything. "You have not because you ask not, and when you do ask, you ask amiss."&nbsp;<a href="http://biblehub.com/james/4-3.htm" target="_blank">James 4:3</a></li>
<ul>
<li><span class="versiontext" style="background-color: #fdfeff; color: #0092f2; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 14px; font-weight: 700; line-height: 20px;"><a href="http://biblehub.com/esv/james/4.htm" style="color: #0092f2; text-decoration: none;"><i>English Standard Version</i></a></span><div style="background-color: #fdfeff; color: #001320; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 14px; line-height: 20px; text-align: justify;">
<span style="font-size: 14px;"><i>You ask and do not receive, because you ask wrongly, to spend it on your passions.</i></span></div>
</li>
</ul>
<li>Faith is NOW. It's about what you failed to do yesterday, and it's not about the worries of tomorrow. Faith is NOW or it's not Faith! You can't be in Faith for someday! If The Blessing is always future tense than it's never received. The very definition of Faith is to receive now inside and then see it happen outside afterward.&nbsp;</li>
<li>Learn more about gardening. It will teach you more about Faith than you can possibly know.&nbsp;</li>
<li>You keep saying you've tried Faith and it didn't work. No! Faith tried you and YOU didn't work!&nbsp;</li>
<ul>
<li><b><a href="http://www.biblestudytools.com/kjv/psalms/105-19.html" target="_blank"><i>Psalms 105:19</i></a></b><i></i><div>
<i></i><i>Until the time that his word came : the word of the LORD&nbsp;<a href="http://biblehub.com/psalms/105-19.htm" target="_blank">tried him</a>.</i></div>
</li>
</ul>
<li>Be STILL! BE STILL BE STILL BE STILL!&nbsp;</li>
<ul>
<li>Flavia told you in the car, that you are so focused on being in motion, you are willing to take the longer or harder route, just to keep being in motion.&nbsp;</li>
<li>It's not the first time she's said that in the last 60 days. She said it on the freeway choice between 114 and 170. She said it again tonight in the parking lot. Going the back way, vs the front way, vs waiting for traffic to clear.&nbsp;</li>
<li>You KNOW God's already been dealing with you this BE STILL command since you first heard the practice of stillness from Michael Hyatt. Since you let it slip he had Michael Hyatt bring it up AGAIN!&nbsp;</li>
<li>EVERY morning, and several times throughout the day, practice stillness. Especially before sending an email, making a decision, writing a blog post, etc...&nbsp;</li>
</ul>
<li>Car Faith. Jesse talked about letting the Lord buy him a car. Let God lead you. Be led in your decision.&nbsp;</li>
<li>Being Led. If you are invited somewhere:</li>
<ul>
<li>A: Pray about it, pray for them, pray for their needs and the message they need to hear, and ask God to send the right person to them.&nbsp;</li>
<li>B: If God says no, tell them no. If God says nothing, don't go yet.&nbsp;</li>
</ul>
<li>Be In Your Place. If your place is X, then X has your provision, prosperity, protection and correction. You'll have the same attacks at A, B, C, Y, Z... but only X will produce favorable results despite the attack.&nbsp;</li>
<li>....</li>
</ul>
</div>
<div>
<br /></div>
<div>
<br /></div>
<blockquote class="tr_bq">
<br /></blockquote>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<br />