---
title: '2014/02/13 Journal Thu'
date: '2014-02-13T13:17:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1405676579663235874'
blogger_filename: '/2014/02/20140213-journal-thu.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<p>VOD<br>
Job 36:11<br>
If they obey and serve Him, they shall spend their days in prosperity and their years in pleasures.</p>
<p>How He loves me! David Crowder.</p>
<p>Feeling</p>
<p>? Wished I'd heard from AAA yesterday. Still believe it's a God thing. </p>
<p>Also feeling the need to be alone. Very alone.</p>
<p>What's up?</p>
<p>I walked into Gateway this morning a little late for the men's group. I walked over, saw all the men in room... and turned around. Found a quiet spot on the couch near the window. </p>
<p>I just couldn't handle a room full of people... ESP all men... just yet. </p>
<p>Reminds me of not wanting to go to camp. So many new people. I got over that feeling in theatre but generally even onto college I either met people one at a time, or got brought into a group by another. </p>
<p>Both the EMIC men's group and now this one were only because of invitation.</p>
<p>Interesting thing to know about myself for future pondering.</p>
<p>Thankful</p>
<p>For learning a little more about myself today...</p>
<p>Darrell </p>
