---
title: 'My thoughts on: How To Shift Away From A Career In Sales'
date: '2014-04-18T05:02:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2484250436227607513'
blogger_filename: '/2014/04/my-thoughts-on-how-to-shift-away-from.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<br />
<br />
<br />
<a href="http://www.careershifters.org/expert-advice/how-to-shift-away-from-a-career-in-sales" target="_blank">http://www.careershifters.org/expert-advice/how-to-shift-away-from-a-career-in-sales</a><br />
<br />
<h2 style="font-family: adelle-sans, Verdana, Tahoma, 'DejaVu Sans', sans-serif; line-height: 2em; margin-bottom: 1em; margin-top: 1em;">
Step 1:</h2>
<span style="background-color: white; font-family: adelle-sans, Verdana, Tahoma, 'DejaVu Sans', sans-serif; font-size: 15px; line-height: 22.799999237060547px;">Write down the barriers preventing you from leaving the job. Here are some most common reasons:</span><br style="font-family: adelle-sans, Verdana, Tahoma, 'DejaVu Sans', sans-serif; font-size: 15px; line-height: 22.799999237060547px;" /><br style="font-family: adelle-sans, Verdana, Tahoma, 'DejaVu Sans', sans-serif; font-size: 15px; line-height: 22.799999237060547px;" /><em style="font-family: adelle-sans, Verdana, Tahoma, 'DejaVu Sans', sans-serif; font-size: 15px; line-height: 22.799999237060547px;">Financial — you believe that another job won't give you the same salary.&nbsp;</em><span style="font-family: adelle-sans, Verdana, Tahoma, 'DejaVu Sans', sans-serif; font-size: 15px; line-height: 22.799999237060547px;"><br /></span><br />
<em style="font-family: adelle-sans, Verdana, Tahoma, 'DejaVu Sans', sans-serif; font-size: 15px; line-height: 22.799999237060547px;">Stumped— I don't know what to do?</em><br />
<br />
<br />
<h2 style="font-family: adelle-sans, Verdana, Tahoma, 'DejaVu Sans', sans-serif; line-height: 2em; margin-bottom: 1em; margin-top: 1em;">
Step 2:</h2>
<div style="font-family: adelle-sans, 'Times New Roman', Times, Georgia, 'DejaVu Serif', serif; font-size: 1.0625em; line-height: 1.625em; margin-bottom: 1.5em; margin-top: 1.5em;">
Write a list of all the reasons why you dislike your current job and also all the things that you enjoy. Can you see a pattern? What does your list tell you about the type of work that'll suit you?</div>
Dislike<br />
<div>
<ul>
<li>Having people shoved at me from other departments that don't even want to be on my phone.&nbsp;</li>
<li>Talking to people who have no desire for anything better in life.</li>
<li>Selling financial crack.</li>
<li>Pointless</li>
<li>Sales Goals. Metrics.&nbsp;</li>
<li><br /></li>
</ul>
</div>
Like<br />
<div>
<ul>
<li>The few times I can help someone</li>
<li>Teaching people</li>
<li>Fixing Problems</li>
<li>Solving Puzzles</li>
<li>Excel and Reports</li>
</ul>
</div>
<br />
<br />
<h2 style="font-family: adelle-sans, Verdana, Tahoma, 'DejaVu Sans', sans-serif; line-height: 2em; margin-bottom: 1em; margin-top: 1em;">
Step 3:</h2>
<div style="font-family: adelle-sans, 'Times New Roman', Times, Georgia, 'DejaVu Serif', serif; font-size: 1.0625em; line-height: 1.625em; margin-bottom: 1.5em; margin-top: 1.5em;">
Write down the answers to the following questions:</div>
<ol style="font-family: adelle-sans, Verdana, Tahoma, 'DejaVu Sans', sans-serif; font-size: 15px; line-height: 22.799999237060547px; margin: 1.5em 0px; padding: 0px 0px 0px 30px;">
<li>What inspires you?</li>
<li>What would you do if you knew you couldn't fail?</li>
<li>What did you want to do as a child when you were growing up?</li>
</ol>
<br />
1. I'm inspired when I see the light turn on for someone and they see the way out of a difficult place or to a new destination. I'm inspired by seeing the dots connect, and telling other people.<br />
<br />
2. I'd write.<br />
<br />
<br />
3. Read. Play musical instruments. Preach.<br />
<br />
<br />
<br />
<br />
<h2 style="font-family: adelle-sans, Verdana, Tahoma, 'DejaVu Sans', sans-serif; line-height: 2em; margin-bottom: 1em; margin-top: 1em;">
Step 4:</h2>
<div style="font-family: adelle-sans, 'Times New Roman', Times, Georgia, 'DejaVu Serif', serif; font-size: 1.0625em; line-height: 1.625em; margin-bottom: 1.5em; margin-top: 1.5em;">
Get to know yourself. What are your interests, personal qualities, strengths and values? Take a look at Melanie Castle's article, "Learning about Yourself" or email me at&nbsp;<a href="mailto:info@kayholdsworth.com" style="color: #363636;">info@kayholdsworth.com</a>&nbsp;for exercises to help you to learn who you are and what would be your ideal type of work.</div>
<br />
??? &nbsp;Email them.<br />
<br />
<br />
<br />
<br />
<h2 style="font-family: adelle-sans, Verdana, Tahoma, 'DejaVu Sans', sans-serif; line-height: 2em; margin-bottom: 1em; margin-top: 1em;">
Step 5:</h2>
<div style="font-family: adelle-sans, 'Times New Roman', Times, Georgia, 'DejaVu Serif', serif; font-size: 1.0625em; line-height: 1.625em; margin-bottom: 1.5em; margin-top: 1.5em;">
Complete a skills audit. Many people who have been in the same job for a number of years feel they haven't got the necessary skills or experience to change roles. Sales people can be the worst culprits when it comes to underselling their skills! The fact is, people in sales have a wealth of skills that are easily transferable to other areas of work. Here are just a few skills and qualities of typical sales people:<br /><br />Excellent communication and people skills, ambitious, able to manage and motivate individuals and teams, confidence, good understanding of the needs of customers and business, ability to build rapport, use of initiative, good at networking, negotiating and persuasion.<br /><br />Brainstorm with a partner or friend all the skills that you use in your current and previous roles. Now sort your skills into one of these three categories: people, technical or data skills. Most importantly, make a separate list of all the skills that you enjoy using.</div>
<br />
<br />
?<br />
<br />
<br />
<br />
<br />
<h2 style="font-family: adelle-sans, Verdana, Tahoma, 'DejaVu Sans', sans-serif; line-height: 2em; margin-bottom: 1em; margin-top: 1em;">
Step 6:</h2>
<div style="font-family: adelle-sans, 'Times New Roman', Times, Georgia, 'DejaVu Serif', serif; font-size: 1.0625em; line-height: 1.625em; margin-bottom: 1.5em; margin-top: 1.5em;">
Explore your options and brainstorm any jobs that appeal to you. &nbsp;Think about who might have a need for your skills. Be as creative and as imaginative as possible. There are no stupid ideas and this is not the time to be realistic. Brainstorming only works if you write whatever comes into your head without editing. Once you have your list of potential jobs, decide what criteria you will use to evaluate the ideas, such as genuine interest and achievability. Ask yourself, "What do I need to know about this role to know if it's right for me?"</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />