---
title: '2014/05/18 Journal Sunday'
date: '2014-05-18T13:10:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8636975222838914780'
blogger_filename: '/2014/05/20140518-journal-sunday.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

We went to church on Saturday night (last night). So Sunday is a whatever we want day. That works better. We went to the NFW Campus. We both felt Southlake is our home. But that was an interesting trip. It's much closer to our home. Next week we'll go back to Southlake.<br />
<br />
I woke up at 8 am this morning (four minutes ago). The house was still quiet, which was weird. Connor was awake, no surprise there, but he was keeping quiet for the rest of us. That was nice of him.<br />
<br />
I need to figure out... discover might be a better word.... what it is my blog is about. I feel lost still with it.<br />
<br />
LIFW is easy. Actually getting some traffic too. But DW is still... awkward.<br />
<br />
I'm thankful for Blogger, which allows me this opportunity. I'm thankful for Connor, a really smart kid who has a passion for truth and justice. I'm thankful for these little dogs. They are a comfortable distraction.<br />
<br />
DW<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />