---
title: '2014/01/23 Journal Thursday'
date: '2014-01-23T16:12:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3727344421526609291'
blogger_filename: '/2014/01/20140123-journal-thursday.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
Thankful</h4>
Thankful for the Wells Health Cash Infusion into the health card each year. Thankful for Flavia's Petrolium Jelly. Yummy! Thankful for my Mom flying here and back safely.<br />
<br />
<h4>
Feeling</h4>
Feeling overwhelmed by a sense that I start my life again tomorrow, job, bills, other adult stuff. Being an adult has not been fun at all. In fact I hate it. Feeling reservedly hopeful that I can turn online passive income into a reality.<br />
<br />
<h4>
What's happening right now</h4>
<br />
Flavia is at the dentist. Not enough money to do all the work. Needs to choose the most important things for now. Mom is in IL with Ryan. Ryan is in surgery. Just made the kids breakfast. Sitting down for a bit and then it's time to clean the kitchen.<br />
<br />
<br />
<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
<div style="text-align: center;">
Your word is a lamp to my feet and a light to my path.</div>
<cite style="border: 0px; color: #77533b; display: block; font-family: calluna, 'Trebuchet MS', Tahoma, Verdana, sans-serif; font-size: 18px; font-style: normal; letter-spacing: 0.5039999485015869px; line-height: 26.875px; margin: 0px 0px 20px; padding: 0px; text-align: center; text-transform: uppercase; width: 671.34375px;"><a class="lbsBibleRef" data-reference="Psalm 119.105" data-version="nkjv" href="http://biblia.com/bible/nkjv/Psalm%20119.105" style="border: 0px; color: #996b4c; margin: 0px; padding: 0px; text-decoration: none;" target="_blank">PSALM 119:105</a></cite></blockquote>
<span style="color: #030404; font-family: calluna, 'Trebuchet MS', Tahoma, Verdana, sans-serif; font-size: 17px; letter-spacing: 0.5039999485015869px; line-height: 26.875px;">Maybe things seem pretty good in your life right now. Maybe it doesn’t feel like you need to dive into the Word to get through your day. Let me tell you this—His Word doesn’t just drive out the darkness; it can keep you from it, too. We need to spend time letting the lamp light our paths every day. If there’s always light, we won’t have the chance to stumble. We’ll be able to walk in the light of God’s guidance. - See more at: http://gatewaydevotions.com/it-is-written/day-23#sthash.Tc28mtK5.dpuf</span><br />
<br />
<br />
<br />
<br />