---
title: '2014/05/24 Journal'
date: '2014-05-24T19:28:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7983079181259310923'
blogger_filename: '/2014/05/20140524-journal.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

So I got up early. Drank enhanced water. Did my bounce and shake from the Mars and Venus diet book. I came into this office to do some writing. Trying to figure out what I wanted to write about. Started looking into Memorial Day and then got into the history of Independence Day which had me taking a deeper look at the Declaration of Independence.<br />
<br />
Then Flavia comes in asking me what I'm doing, why I'm doing that. It felt very intrusive, interrupting, interrogating, and annoying. She keeps telling me that she's not meaning to be that way, but that's how it feels.<br />
<br />
I know there are men who are "Family Men", they like having a family, it's a high priority for them. I with I was like those men. As it is, I still just wish I could erase 2002 and forward and start over, knowing there was a different path.<br />
<br />
She's back with groceries. Gotta Go.<br />
<br />
DW