---
title: '11/24/14 | Journal Entry | Cast Your Rod'
date: '2014-11-24T13:35:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '403405422046399975'
blogger_filename: '/2014/11/112414-journal-entry-cast-your-rod.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<br />
<br />
<h3 class="hd">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=365&amp;id=28-joseph-prince&amp;version=1" target="_blank">Devotional</a>
</h3>
Day 365&nbsp; | Take The Snake By Its Tail <br />
<br />
<blockquote class="tr_bq">
Exodus 4:2–3 <br />
2So
 the Lord said to him, “What is that in your hand?” He said, “A 
rod.”3And He said, “Cast it on the ground.” So he cast it on the ground,
 and it became a serpent; and Moses fled from it.&nbsp;</blockquote>
<br />
God wants to 
take the natural things in your life and make them supernaturally 
blessed. He does this by asking you to give Him what you already have in
 the natural, and He will do the supernatural. <br />
That is why the 
Lord told Moses to cast his rod on the ground. And when Moses cast his 
rod on the ground, which represents him giving the rod to the Lord, that
 same rod became the rod of God. With that rod, the Red Sea was opened. 
(Exodus 14:16) And when that rod was used to hit a rock, water flowed 
out of the rock. (Exodus 17:5–6) It was no longer a natural rod, but the
 supernatural rod of God! <br />
<br />
But why did the rod become a serpent when Moses cast it to the ground?<br />
<br />
Moses
 never realized that there was a “snake” in his rod. You see, because of
 the fall of man, there is a touch of the curse — a snake — in every 
natural thing, including your career, natural strength, talents and 
ministry. <br />
So how do you deal with the “snake” that is in all the natural things in your life? <br />
<br />
First, cast it to the Lord. Then, do what the Lord told Moses next: “Reach out your hand and take it by the tail”. (Exodus 4:4) <br />
<br />
Now,
 it could be fatal to take a snake by its tail because it can easily 
turn its head around and bite you. So why did God say that?<br />
<br />
When 
you take it by the tail, God will take the head! He wants you to let Him
 handle the head, and not grab it or hold on to it tightly in fear or 
self-effort. That is how you see your career, strength, talents and 
ministry supernaturally blessed.<br />
<br />
Beloved, there is a snake, a 
touch of the curse, in everything in the natural. But give what is 
natural to the Lord and see the touch of the curse replaced with the 
supernatural touch of God!<br />
 <br />
Thought For The Day<br />
<br />
Give what is natural to the Lord and He will make it supernaturally blessed. <br />
<br />
**********************************<br />
<br />
<br />
I feel like I've been doing two things with my internet/authorship career.<br />
<br />
<br />
<br />
1. I've been learning, inputting, gaining understanding. Somewhere along the line though, that turned into... #2<br />
<br />
2. I've been trying in the natural, doing things I know to do... operating in the knowledge of good. <br />
<br />
<br />It's time to throw my rod to the ground. Stop everything I have going, which has nearly come to a stop anyway, and BeStillBeLed... <br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />