---
title: 'Facebook for spirit filled Drs'
date: '2014-07-24T00:07:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5220146814201070942'
blogger_filename: '/2014/07/facebook-for-spirit-filled-dr.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

Idea:<br />
<br />
A social sharing website geared toward Christians and their medical needs.<br />
<br />
<b>The Vision:</b><br />
Have a place where patience can find doctors that align with their beliefs<br />
Have a place where Doctors can find these patients and turn them into new clients. Also, a place where Doctors can meet other like minded Doctors and participate in group education and information sharing, broadening their own knowledge, and sharing theirs with others. <br />
<br />
<b>The Method:</b><br />
Each Doctor and Potential/Patient would fill out a sheet aligning to belief statements, location, and needs/specialties. <br />
<br />
Doctors sharing with each other would only be viewable by other registered Doctors. Verified by ?<br />
<br />
Doctors could also reach out to patients on the site and answer educational general questions, and request a consultation for more specific advice.<br />
<br />
Patients could find Doctors aligned with their beliefs and feel a trust bond before entering the office, which will make for a more open dialogue and accurate diagnosis. Good for everyone around. Win-Win<br />
<br />
<br />