---
title: '16 Types for the Wolfe Family'
date: '2014-10-20T02:51:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '763436868782387717'
blogger_filename: '/2014/10/16-types-for-wolfe-family.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'House'
---

<br />
<h4>
The <a href="http://www.16personalities.com/free-personality-test" target="_blank">16 Personality Types</a>: </h4>
<br />
I've grown as a person, able to provide more honest answers than my younger years. Early in life, I tested as an <a href="http://www.16personalities.com/enfp-personality" target="_blank">ENFP</a>.
 However, I don't know if my personality changed in my older years, or 
if I'm just more honest about who I am now... but my results differed 
this time. And the descriptions for my results are nearly perfectly on 
target. Or, maybe I was more honest then? I came up with several. 
EVERYONE is a bit of all of these things. It's the balance of all 
potential human reactions to this test. This is about tendencies and 
preferences. <br />
<br />
<h3>
<a href="http://www.16personalities.com/articles/our-theory" target="_blank">The Theory of IE,NS, TF, JP</a></h3>
<h4>
Extrovert vs Introvert - Affects Human Interaction</h4>
<br />
<b>E -<span style="background-color: blue;">?</span> Extrovert</b>: Tends to draw energy from human interactions, time alone leaves them feeling drained and in need of interaction.<br />
<br />
<span style="background-color: cyan;"><b>I<span style="background-color: magenta;"> - <span style="background-color: orange;">?</span></span>Introvert</b>: Tends to draw energy from time alone, time with people tends to leave them feeling drained and in need of solitude. </span><br />
<br />
<h4>
INtuitive vs ObServant (Sensing) - Affects how we perceive the world around us. </h4>
<br />
<b><br /></b>
<span style="background-color: cyan;"><b>N-<span style="background-color: orange;">?</span> Intuitive's</b>
 gather their sense of the world from this intuition, have a passion for
 ideas and concepts, and theoretical, tend to think of what could be. </span><br />
<br />
<b>S<span style="background-color: magenta;"> - </span><span style="background-color: blue;">?</span>Sensors (ObServants)</b>
 gather their sense of the world from what they can use their senses to 
perceive, have a passion for facts and hard evidence, tend to think of 
what is or has been. <br />
<br />
<br />
<h4>
Thinkers vs Feelers - How we make decisions, and cope with emotions</h4>
<b>T -<span style="background-color: blue;">-</span> Thinkers </b>tend to follow their minds, focus on rational objective truths. <br />
<br />
<b>F<span style="background-color: magenta;"> - </span><span style="background-color: orange;">?</span>Feelers </b>tend to follow their hearts, focus on harmony and cooperation. <br />
<br />
<br />
<br />
<b>Judging vs Prospecting - How we approach work, planning, and decision-making. .</b><br />
<br />
<b>J -<span style="background-color: blue;">-</span> Judging</b> individuals prefer clear guidelines, and deadlines, and seek closure and finality above all else. <br />
<br />
<b>P<span style="background-color: magenta;"> - </span><span style="background-color: orange;">?</span>Prospecting</b> individuals prefer flexible schedules, improvising, keeping options open, relaxed lifestyle, and freedom above all else. <br />
<br />
<br />
<h4>
I Tested:</h4>
<div class="row sidebar-trait-progress-wrapper">
<h4>
<span style="font-family: inherit;"><a href="http://www.16personalities.com/infj-personality" target="_blank">At 16 Personalities: INFJ</a><span style="font-family: inherit;">&nbsp; | </span>Introverted 44% | Intuitive 74%<span style="font-family: inherit;"> |&nbsp; </span>Feeling 23% (7%)<span style="font-family: inherit;"> </span>| Judging 15% (11%) ( I took this three times in two days, and it <span style="font-family: inherit;">came up INFJ every time. I <span style="font-family: inherit;">guess I should read th<span style="font-family: inherit;">rough this again?) </span></span></span></span></h4>
</div>
<h4>
<a href="http://www.humanmetrics.com/cgi-win/JTypes1.htm" target="_blank">At HumanMetrics: INTJ</a> Introvert 67% | Intuitive 88% | Thinking 12% | Judging 1%</h4>
It's
 fairly common to have low scores in one area and high in another. So 
it's safe to say I show a strong tendency toward Introversion and 
Intuition. IN. I score low (middle) in the T/F and J/P categories. So 
let's examine these possibilities and look at the different aspects of 
these more. I will look at the combinations of IN _ _.<br />
<br />
<br />
<h4>
<a href="http://www.16personalities.com/infj-personality" target="_blank">INFJ -</a> Help Me Help You - (Who I am)</h4>
<h4>
There are parts of this that are me, mostly not me. A lot of it sounds like Flavia though. </h4>
I (Drawing energy from solititude, needs to recharge after time with people) <br />
N (Intuiting possibilities)<br />
F (carefree heart followers)<br />
J (clear guidelines, closure finality)<br />
<br />
INFJs
 indeed share a very unique combination of traits: though soft-spoken, 
they have very strong opinions and will fight tirelessly for an idea 
they believe in. They are decisive and strong-willed, but will rarely 
use that energy for personal gain – INFJs will act with creativity, 
imagination, conviction and sensitivity not to create advantage, but to 
create balance. Egalitarianism and karma are very attractive ideas to 
INFJs, and they tend to believe that nothing would help the world so 
much as using love and compassion to soften the hearts of tyrants.<br />
<br />
<h4>
<a href="http://www.16personalities.com/intj-personality" target="_blank">INTJ </a>- Nothing Can Stop the Right Attitude from Achieving Its Goal (Who I wish I was)</h4>
I (Drawing energy from solititude, needs to recharge after time with people)<br />
N (Intuiting possibilities)<br />
T (Follow the mind, rational objective truth). <br />
J (clear guidelines, closure finality)<br />
<br />
It's lonely at the top, and being one of the rarest and most 
strategically capable personality types, INTJs know this all too well. 
INTJs form just two percent of the population, and women of this 
personality type are especially rare, forming just 0.8% of the 
population - it is often a challenge for them to find like-minded 
individuals who are able to keep up with their relentless 
intellectualism and chess-like maneuvering. People with the INTJ 
personality type are imaginative yet decisive, ambitious yet private, 
amazingly curious, but they do not squander their energy.<br />
<br />
With
 a natural thirst for knowledge that shows itself early in life, INTJs 
are often given the title of "bookworm" as children. While this may be 
intended as an insult by their peers, they more than likely identify 
with it and are even proud of it, greatly enjoying their broad and deep 
body of knowledge. INTJs enjoy sharing what they know as well, confident
 in their mastery of their chosen subjects, but owing to their Intuitive
 (N) and Judging (J) traits, they prefer to design and execute a 
brilliant plan within their field rather than share opinions on 
"uninteresting" distractions like gossip.<br />
<br />
------------------------------------------------------------<br />
My best guess for the family traits, we'll see as the kids progress.<br />
------------------------------------------------------------<br />
<b><br /></b>
<h4>
<b>Flavia</b><a href="http://www.16personalities.com/isfp-conclusion" target="_blank"><b> </b>ISFP -</a> VERY Flavia! Artistic - Rule Breaker - Sensible - Free</h4>
<br />
I (Drawing energy from solititude, needs to recharge after time with people)<br />
S (Sensing the here and now, what is and has been) <br />
F (carefree heart followers)<br />
P (open relaxed, likely to pick up and leave on a moments notice) <br />
<br />
<br />
ISFP
 personality types are true artists. This doesn’t necessarily apply in 
the typical sense, in which they are out painting happy little trees, 
though often enough they are perfectly capable of this. Rather, it’s 
that they use aesthetics, design and even their choices and actions to 
push the limits of social convention. ISFPs enjoy upsetting traditional 
expectations with experiments in beauty and behavior – chances are, 
they’ve expressed more than once the phrase<b> “Don’t box me in!”</b><br /><br />ISFP
 personalityISFPs live in a colorful, sensual world, inspired by 
connections with people and ideas. But rather than take things as they 
are, ISFPs take joy in reinterpreting these connections, reinventing and
 experimenting with both themselves and with new perspectives – no other
 type explores and experiments with these ideas more. This process leads
 to an air of spontaneity, making ISFPs often seem unpredictable, even 
to their close friends and loved ones.<br /><br />Despite the appearances of
 this expeditionary spirit, ISFPs are Introverts (I), and they will 
further surprise their friends when they need to step out of the 
spotlight and spend time by themselves to recharge. Just because they 
are alone though, doesn’t mean ISFPs sit idle – rather they are likely 
to take this time for introspection, assessing their principles, 
thinking not about what they’ve done or what they want to do with their 
future, but about who they are, set apart from the limits of society. 
They will return from their cloister, transformed.<br /><br />For all their 
aversion to structure and rules though, ISFPs will still need to make 
their way in a world governed by rule of law. Lucky ISFPs are likely to 
make their living in a field offering the greatest degree of flexibility
 and freedom, following their passions in music, writing, or design. 
Less lucky ISFPs will likely end up making do with less interesting 
work, but work that nonetheless allows them to do what they please in 
their off time. Either way, to some degree ISFPs will find a way to push
 their passions, even if it means engaging in riskier behaviors like 
gambling and extreme sports – chances are that their attunement to the 
moment and to their environment will allow them to perform better than 
most.<br /><br />ISFPs also enjoy connecting with others with a certain 
irresistible charm – they always know just the compliment to soften a 
heart that’s getting ready to call their risks irresponsible or 
reckless. However, if the criticism does get through, it can often end 
poorly. Some ISFPs can handle the right kind of constructive commentary,
 valuing it as another perspective to help push their passions in new 
directions, but if the comments are more biting and less mature, ISFPs 
are able to lose their tempers in spectacular fashion.<br /><br />Their 
tendency to push boundaries notwithstanding, ISFPs are sensitive to 
others’ feelings and value harmony highly. When faced with criticism, it
 can be a challenge for ISFPs to step away from the moment long enough 
to not get caught up in a bout of name-calling. But living in the moment
 goes both ways, and chances are that once the heightened emotions of an
 argument cool, ISFPs will likely call the past the past and move on as 
though it never occurred.<br /><br />The biggest challenge ISFPs are likely 
to face is in establishing constructive principles to base their goals 
on, and likewise to find goals that establish positive principles. 
Unlike more traditional Sentinels (SJ), ISFPs won’t be planning their 
future in the form of retirement contributions. Rather, they will plan 
actions and behaviors as contributions to a sense of identity, building a
 portfolio of experiences, not stocks.<br /><br />If their goals and 
principles are good and noble, ISFPs can act with amazing charity and 
selflessness, inspiring others to do good as well. But it can also 
happen that ISFPs will establish a more self-centered identity, in which
 case they can act with selfishness, connivance and egoism. It is 
important for ISFPs to remember to reflect on and actively contribute to
 who they want to be in this world – though developing and maintaining a
 habit may not come naturally to them, taking the time each day to 
understand their motivations will allow ISFPs to harness their strengths
 to pursue whatever it is they’ve come to love.<br />
<br />
Finally, it is important to note that people with the ISFP personality 
type need to know that their love and attention are valued and 
appreciated. The ISFP is unlikely to ask for this, but they may feel 
frustrated and disappointed if their partner does not make efforts to 
express their feelings. Such an expression does not necessarily have to 
be verbal—ISFPs believe in actions, not words—but it is crucial that 
ISFPs know that their feelings are being reciprocated.<br />
<br />
---------------------------------------------------------<br />
<h4>
Connor</h4>
<h4>
<a href="http://www.16personalities.com/estjs-at-work" target="_blank">ESTJ - Guess for Connor</a> - REALLY good guess</h4>
ESTJs
 are representatives of tradition and order, utilizing their 
understanding of what is right, wrong and socially acceptable to bring 
families and communities together. Embracing the values of honesty, 
dedication and dignity, people with the ESTJ personality type are valued
 for their clear advice and guidance, and they happily lead the way on 
difficult paths. Taking pride in bringing people together, ESTJs often 
take on roles as community organizers, working hard to bring everyone 
together in celebration of cherished local events, or in defense of the 
traditional values that hold families and communities together.<br /><br />
ESTJ
 personalityDemand for such leadership is high in democratic societies, 
and forming no less than 11% of the population, it's no wonder that many
 of America's presidents have been ESTJs. Strong believers in the rule 
of law and authority that must be earned, ESTJ personalities lead by 
example, demonstrating dedication and purposeful honesty, and an utter 
rejection of laziness and cheating, especially in work. If anyone 
declares hard, manual work to be an excellent way to build character, it
 is ESTJs.<br />
<br />ESTJs are aware of their surroundings and live in a
 world of clear, verifiable facts - the surety of their knowledge means 
that even against heavy resistance, they stick to their principles and 
push an unclouded vision of what is and is not acceptable. Their 
opinions aren't just empty talk either, as ESTJs are more than willing 
to dive into the most challenging projects, improving action plans and 
sorting details along the way, making even the most complicated tasks 
seem easy and approachable.<br /><br />However, ESTJs don't work alone, and 
they expect their reliability and work ethic to be reciprocated - people
 with this personality type meet their promises, and if partners or 
subordinates jeopardize them through incompetence or laziness, or worse 
still, dishonesty, they do not hesitate to show their wrath. This can 
earn them a reputation for inflexibility, a trait shared by all 
Sentinels (SJ), but it's not because ESTJs are arbitrarily stubborn, but
 because they truly believe that these values are what make society 
work.<br /><br />
<blockquote class="tr_bq">
<b>...But Still Better Are Those Who Acknowledge When They Are in Error.</b></blockquote>
<br />The
 main challenge for ESTJs is to recognize that not everyone follows the 
same path or contributes in the same way. A true leader recognizes the 
strength of the individual, as well as that of the group, and helps 
bring those individuals' ideas to the table. That way, ESTJs really do 
have all the facts, and are able to lead the charge in directions that 
work for everyone.<br /><br />
ESTJ strengths and weaknesses<br />
<blockquote class="tr_bq">
<b>ESTJ Strengths</b></blockquote>
<br />
<ul>
<li>&nbsp;&nbsp;&nbsp;
 Dedicated - Seeing things to completion borders on an ethical 
obligation for ESTJs. Tasks aren't simply abandoned because they've 
become difficult or boring - people with the ESTJ personality type take 
them up when they are the right thing to do, and they will be finished 
so long as they remain the right thing to do.</li>
<li>&nbsp;&nbsp;&nbsp; Strong-willed -
 A strong will makes this dedication possible, and ESTJs don't give up 
their beliefs because of simple opposition. ESTJs defend their ideas and
 principles relentlessly, and must be proven clearly and conclusively 
wrong for their stance to budge.</li>
<li>&nbsp;&nbsp;&nbsp; Direct and Honest - ESTJs 
trust facts far more than abstract ideas or opinions. Straightforward 
statements and information are king, and ESTJ personalities return the 
honesty (whether it's wanted or not).</li>
<li>&nbsp;&nbsp;&nbsp; Loyal, Patient and 
Reliable - ESTJs work to exemplify truthfulness and reliability, 
considering stability and security very important. When ESTJs say 
they'll do something, they keep their word, making them very responsible
 members of their families, companies and communities.</li>
<li>&nbsp;&nbsp;&nbsp; Enjoy
 Creating Order - Chaos makes things unpredictable, and unpredictable 
things can't be trusted when they are needed most - with this in mind, 
ESTJs strive to create order and security in their environments by 
establishing rules, structures and clear roles.</li>
<li>&nbsp;&nbsp;&nbsp; Excellent 
Organizers - This commitment to truth and clear standards makes ESTJs 
capable and confident leaders. People with this personality type have no
 problem distributing tasks and responsibilities to others fairly and 
objectively, making them excellent administrators.</li>
</ul>
<br />
<blockquote>
<b>ESTJ Weaknesses</b></blockquote>
<br />
<ul>
<li>&nbsp;&nbsp;&nbsp;
 Inflexible and Stubborn - The problem with being so fixated on what 
works is that ESTJs too often dismiss what might work better. Everything
 is opinion until proven, and ESTJ personalities are reluctant to trust 
an opinion long enough for it to have that chance.</li>
<li>&nbsp;&nbsp;&nbsp; 
Uncomfortable with Unconventional Situations - ESTJs are strong 
adherents to tradition and when suddenly forced to try unvetted 
solutions, they become uncomfortable and stressed. New ideas suggest 
that their methods weren't good enough, and abandoning what has always 
worked before in favor of something that may yet fail risks their image 
of reliability.</li>
<li>&nbsp;&nbsp;&nbsp; Judgmental - ESTJs have strong convictions 
about what is right, wrong, and socially acceptable. ESTJs' compulsion 
to create order often extends to all things and everyone, ignoring the 
possibility that there are two right ways to get things done. ESTJs do 
not hesitate to let these "deviants" know what they think, considering 
it their duty to set things right.</li>
<li>&nbsp;&nbsp;&nbsp; Too Focused on Social 
Status - ESTJs take pride in the respect of their friends, colleagues 
and community and while difficult to admit, are very concerned with 
public opinion. ESTJs (especially Turbulent ones) can get so caught up 
in meeting others' expectations that they fail to address their own 
needs.</li>
<li>&nbsp;&nbsp;&nbsp; Difficult to Relax - This need for respect fosters a 
need to maintain their dignity, which can make it difficult to cut loose
 and relax for risk of looking the fool, even in good fun.</li>
<li>&nbsp;&nbsp;&nbsp; 
Difficulty Expressing Emotion - This is all evidence of ESTJs' greatest 
weakness: expressing emotions and feeling empathy. People with the ESTJ 
personality type get so caught up in the facts and most effective 
methods that they forget to think of what makes others happy, or of 
their sensitivity. A detour can be breathtakingly beautiful, a joy for 
the family, but ESTJs may only see the consequence of arriving at their 
destination an hour late, hurting their loved ones by rejecting the 
notion too harshly.</li>
</ul>
<br /><b>ESTJ Subordinates</b><br /><br />ESTJs
 are hard-working and do things by the book. Though sometimes stubborn 
and inflexible, especially when presented with ideas that haven't been 
fully developed, ESTJ personalities are open to new methods that can be 
demonstrated to be better. However ESTJs are unlikely to do much 
experimenting on their own - adhering to stated responsibilities and 
fulfilling their duties is their primary concern.<br /><br /><b>ESTJs are also well-known for their loyalty and dedication, but in some ways this is contingent on their respect. </b>People
 with this personality type are willing to voice their opinions, 
especially in deciding what is and is not acceptable - if provided with 
sensible responses that address their concerns, they are often satisfied
 with that.<b> If ESTJs view their managers as illogical, dishonest or 
cowardly in their methods, they can be uncomfortably honest, if still 
calm and level, in voicing their opinions on that as well.</b><br />
--------------------------------------------------------------------------<br />
<br />
Preston<br />
<h4>
<a href="http://www.16personalities.com/infp-personality" target="_blank">Preston INFP</a> - My guess for Preston - Good Guess!</h4>
<br />
INFP personalities are true idealists, always looking for the hint of good in even the worst of people and events, searching for ways to make things better. While they may be perceived as calm, reserved, or even shy, INFPs have an inner flame and passion that can truly shine. Comprising just 4% of the population, the risk of feeling misunderstood is unfortunately high for the INFP personality type - but when they find like-minded people to spend their time with, the harmony they feel will be a fountain of joy and inspiration.<br /><br />INFP personalityBeing a part of the Diplomat (NF) personality group, INFPs are guided by their principles, rather than by logic (Analysts), excitement (Explorers), or practicality (Sentinels). When deciding how to move forward, they will look to honor, beauty, morality and virtue - INFPs are led by the purity of their intent, not rewards and punishments. People who share the INFP personality type are proud of this quality, and rightly so, but not everyone understands the drive behind these feelings, and it can lead to isolation.<br /><br />
<blockquote>
<b>We Know What We Are, But Know Not What We May Be</b></blockquote>
<br />INFPs’ ability with language doesn’t stop with their native tongue, either - as with most people who share the Diplomat personality types, they are considered gifted when it comes to learning a second (or third!) language. Their gift for communication also lends itself well to INFPs’ desire for harmony, a recurring theme with Diplomats, and helps them to move forward as they find their calling.<br /><br />Unlike their Extraverted cousins though, INFPs will focus their attention on just a few people, a single worthy cause - spread too thinly, they’ll run out of energy, and even become dejected and overwhelmed by all the bad in the world that they can’t fix. This is a sad sight for INFPs’ friends, who will come to depend on their rosy outlook.<br /><br />If they are not careful, INFPs can lose themselves in their quest for good and neglect the day-to-day upkeep that life demands. INFPs often drift into deep thought, enjoying contemplating the hypothetical and the philosophical more than any other personality type. Left unchecked, INFPs may start to lose touch, withdrawing into "hermit mode", and it can take a great deal of energy from their friends or partner to bring them back to the real world.<br /><br />Luckily, like the flowers in spring, INFP’s affection, creativity, altruism and idealism will always come back, rewarding them and those they love perhaps not with logic and utility, but with a world view that inspires compassion, kindness and beauty wherever they go.<br /><br /><br /><br />
<blockquote class="tr_bq">
<b>INFP Strengths</b></blockquote>
<br />
<ul>
<li>&nbsp;&nbsp;&nbsp; Idealistic - INFPs' friends and loved ones will come to admire and depend on them for their optimism. Their unshaken belief that all people are inherently good, perhaps simply misunderstood, lends itself to an incredibly resilient attitude in the face of hardship.</li>
<li>&nbsp;&nbsp;&nbsp; Seek and Value Harmony - People with the INFP personality type have no interest in having power over others, and don't much care for domineering attitudes at all. They prefer a more democratic approach, and work hard to ensure that every voice and perspective is heard.</li>
<li>&nbsp;&nbsp;&nbsp; Open-Minded and Flexible - A live-and-let-live attitude comes naturally to INFPs, and they dislike being constrained by rules. INFPs give the benefit of the doubt too, and so long as their principles and ideas are not being challenged, they'll support others' right to do what they think is right.</li>
<li>&nbsp;&nbsp;&nbsp; Very Creative - INFPs combine their intuitive nature with their open-mindedness to allow them to see things from unconventional perspectives. Being able to connect many far-flung dots into a single theme, it's no wonder that many INFPs are celebrated poets and authors.</li>
<li>&nbsp;&nbsp;&nbsp; Passionate and Energetic - When something captures INFPs' imagination and speaks to their beliefs, they go all in, dedicating their time, energy, thoughts and emotions to the project. Their shyness keeps them from the podium, but they are the first to lend a helping hand where it's needed.</li>
<li>&nbsp;&nbsp;&nbsp; Dedicated and Hard-Working - While others focusing on the challenges of the moment may give up when the going gets tough, INFPs (especially Assertive ones) have the benefit of their far-reaching vision to help them through. Knowing that what they are doing is meaningful gives people with this personality type a sense of purpose and even courage when it comes to accomplishing something they believe in.</li>
</ul>
<br />
<blockquote>
<b>INFP Weaknesses</b></blockquote>
<br />
<ul>
<li>&nbsp;&nbsp;&nbsp; Too Idealistic - INFPs often take their idealism too far, setting themselves up for disappointment as, again and again, evil things happen in the world. This is true on a personal level too, as INFPs may not just idealize their partners, but idolize them, forgetting that no one is perfect.</li>
<li>&nbsp;&nbsp;&nbsp; Too Altruistic - INFPs sometimes see themselves as selfish, but only because they want to give so much more than they are able to. This becomes a self-fulfilling prophecy, as they try to push themselves to commit to a chosen cause or person, forgetting to take care of the needs of others in their lives, and especially themselves.</li>
<li>&nbsp;&nbsp;&nbsp; Impractical - When something captures INFPs' imagination, they can neglect practical matters like day-to-day maintenance and simple pleasures. Sometimes people with the INFP personality type will take this asceticism so far as to neglect eating and drinking as they pursue their passion or cause.</li>
<li>&nbsp;&nbsp;&nbsp; Dislike Dealing With Data - INFPs are often so focused on the big picture that they forget the forest is made of individual trees. INFPs are in tune with emotions and morality, and when the facts and data contradict their ideals, it can be a real challenge for them.</li>
<li>&nbsp;&nbsp;&nbsp; Take Things Personally - INFPs often take challenges and criticisms personally, rather than as inspiration to reassess their positions. Avoiding conflict as much as possible, INFPs will put a great deal of time and energy into trying to align their principles and the criticisms into a middle ground that satisfies everybody.</li>
<li>&nbsp;&nbsp;&nbsp; Difficult to Get to Know - INFPs are private, reserved and self-conscious. This makes them notoriously difficult to really get to know, and their need for these qualities contributes to the guilt they often feel for not giving more of themselves to those they care about.</li>
</ul>
<br /><br />INFPs will always need to disappear for a while, removing themselves from others so they can re-center on their own minds and feelings. Often enough people with the INFP personality type will emerge from this time alone having come to some momentous decision that even their closest friends didn't know was weighing on them, evading even the option of receiving the sort of support and advice they so readily give. Such is INFPs' way, for better or for worse.<br /><br />Most any cause, idea, or field can benefit from the artful and natural expression that INFPs bring to the table, and INFPs have their pick of the world in choosing who they work with.<br /><br />Where INFPs will not thrive is in a high-stress, team-heavy, busy environment that burdens them with bureaucracy and tedium. INFPs need to be able to work with creativity and consideration - high-pressure salespeople they are not. It can be a challenge to avoid these roles, as they are the basis for so much starting work, and it's often a risk to break away into something less dependable, but more rewarding. To find a career that resonates with INFPs' values though, that's more than just a job, sometimes it's just what needs to be done.<br /><br /><br /><br /><b>INFP Subordinates</b><br /><br />As subordinates, INFPs prefer latitude, and would much rather immerse themselves in a project, alone or with a close team, than simply be told what task to do and move on. People with the INFP personality type aren't looking for easy, forgettable work that pays the bills, they're looking for meaningful work that they actually want to think about, and it helps for their managers to frame responsibilities in terms of emotional merit rather than cold rationalization or business for its own sake. INFPs would rather know that their work will help to deliver a service they believe in than to know that the bottom line has been boosted by 3%.<br /><br />If these standards are met, managers will find an extremely dedicated and considerate employee in INFPs. As idealistic opportunity-seekers INFPs may not always work well in technical applications, where the facts and logic really matter and critique is often necessary, but they work beautifully in more human and creative endeavors. While some types, especially Analysts (NT), respond favorably to negative feedback, taking criticism as an opportunity to not make the same mistake twice, people with the INFP personality type would much rather hear what they did right and focus on what to do, rather than what not to.<br /><br />