---
title: '3 solutions to being Mad @God...'
date: '2014-01-27T13:05:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7078422218466310990'
blogger_filename: '/2014/01/3-solutions-to-being-mad-god.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Word From God'
  - 'Scripture'
  - 'Revelation'
  - 'Life Events'
  - 'Vision'
---

3 solutions to being Mad @God...<br />
<br />
Conversation with Flavia at Pei Wei 01/26/2014<br />
<br />
The solution to life's recurring problems.<br />
<br />
When a single problem just keeps coming up, recurring problem or dilemma, it can feel like God isn't doing His part. I've done everything " I" know to do and this still isn't getting any better... It makes you wonder if God isn't being fair or doing His part. It's frankly hard to trust Him when it seems like it's not getting better, and might even be getting worse.<br />
<br />
What if He's not the problem? What if He already gave the solution but I am not participating?<br />
<br />
<br />
<br />
&nbsp;- He who has, more is given. He who does not have, what he has will be taken.<br />
&nbsp;- Seed must leave the hand to multiply.<br />
&nbsp;- Michael Hyatt's response to holding back on a post. You cannot receive more until you empty yourself of what you have.<br />
&nbsp;- Heart issue. Not material issue. The amount of things you own isn't = to lack OR abundance. Your attitude about them is.<br />
&nbsp;- There are three points to consider in your solution:<br />
&nbsp;- 1. Thank the Giver Himself. Be grateful for Who He is that loves you. Meditate on His love for you.<br />
&nbsp;- 2. Verbalize gratitude for what you have. Lack v Abundance is a state of mind. Consider what the third world thinks of your "Lack".<br />
<br />
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=75&amp;user_id=darrellwolfe&amp;version=1" target="_blank">See Joseph Prince devotional for today 1/26/2014 . Day 75</a><br />
<br />
&nbsp;- 3. Share freely what you've been given, spiritually, physically, and financially. Seed must leave the hand to multiply.