---
title: '2014/02/05 Journal Wed'
date: '2014-02-05T15:41:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4034917058917460976'
blogger_filename: '/2014/02/20140205-journal-wed.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
Proverbs 19:12<br />12The king’s wrath is like the roaring of a lion, but his favor is like dew on the grass.<br /><span style="background-color: #eeedeb; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 11.818181991577148px; line-height: 19.636363983154297px;">It has something to do with a lion’s roar. In the Bible, the roaring of a lion speaks of the king’s wrath — “The king’s wrath is like the roaring of a lion”. So when the devil walks about like a roaring lion, he is trying to give you the impression that the King is angry with you. And when you believe that God is angry with you, the devil knows that he has got you.</span></blockquote>
<br />
<h4>
Thankful:</h4>
I am thankful for my family, my understanding wife who has put up with my wondering aimless life so far. I am thankful for Jack who I can bounce things off of. Sean who reminds me how we all feel lost sometimes.<br />
<br />
<h4>
Feeling:</h4>
Surprisingly, not feeling nervous about this AAA thing. Despite the draw backs, which appear largely semantic anyway, I find that I am more excited about the prospect of something new, hopeful that just maybe this company actually cares about it's clients, at least a little more than WF. We'll see, interview is today at 2PM.<br />
<br />
<h4>
What's Up?</h4>
Interview today for AAA. It's cold outside, just like I like it! Mom is still at Ryan's with a broken foot, swelling, and fever. They say it's normal with the healing and prescribed nothing. Lord, I plead the blood of Jesus over her, heal her! Ryan seems to be healing too.<br />
<br />
Flavia and I have been staying up too late, we need to find a better rhythm.<br />
<br />
Ed Reiss really is a good guy, despite our differing perspective. I feel like he's blatantly ignoring what's going on in the company. He feels I'm so focused on the negative I'm not seeing the positive. Maybe we're both being a bit unrealistic. Then again, if he admitted the problem he'd be forced to confront it or look for a new job. Which is exactly what I'm doing. I cannot stay there pretending things will change. The company has taken their stand. They stand for profit over service. While I'm growing in the ways of giving all you have and are and letting profit be the byproduct. Thanks for Kenneth Copeland, Joseph Prince, Jeremy Pearsons, Michael Hyatt, Pat Flynn, and Seth Godin... I'm ruined for the profit first while we pay lip service to caring for customers model. Never again!<br />
<br />
<br />
DW<br />
<br />
<h4>
Some Random Notes: Didn't know where to put this for later. Here's good for now.&nbsp;</h4>
<div>
&nbsp;</div>
<div>
<span style="font-family: Calibri, sans-serif; font-size: x-small;">
<div>
Note To Self: Go find recent Dr Laura Shows… there’s a guy on there that 
sounds identical to me? </div>
<div>
&nbsp;</div>
<div>
<span style="font-family: Calibri, sans-serif; font-size: x-small;">
<div>
&nbsp;</div>
<div>
&nbsp;</div>
<div>
<span style="font-size: medium;"><b>Meeting Notes:</b></span></div>
<div>
Check Out: The Little Red Book of Sales</div>
<div>
&nbsp;</div>
<div>
Give them the help they NEED, not the help you’d like to give them. </div>
<div>
&nbsp;</div>
<div>
Budget = My Spending Report</div>
<div>
&nbsp;</div>
<div>
When you think about your finances right now, what’s the most important 
thing to you?</div>
<div>
&nbsp;</div>
<div>
You can’t <b>fix</b> everybody you can <b>help</b> everybody, or most 
people. </div>
<div>
&nbsp;</div>
<div>
There are basically three classes of people. </div>
<div style="padding-left: 36pt;">
&nbsp;</div>
<div style="padding-left: 36pt;">
<b>Spenders</b> (those who can’t save, live 
check to check sometimes barely sometimes very well, but not building a 
savings.)</div>
<div style="padding-left: 36pt;">
<b>Savings</b> ( Starting to build a savings. 
)</div>
<div style="padding-left: 36pt;">
<b>Investors</b> (Has a savings in place, and 
building wealth.)</div>
<div>
&nbsp;</div>
<div>
GET TO KNOW YOUR CUSTOMER. 80/20 rule. Ask MORE questions… let the customer 
do the talking. </div>
<div>
&nbsp;</div>
<div>
Help them overcome buyer’s remorse. If it’s not their idea, it’s ok to do, 
the pressure to make a decision is off. You basically make the decision for 
them, you are the advisor, and then check for agreement. They simply have to 
agree or not.&nbsp;</div>
</span></div>
</span></div>
<div>
&nbsp;</div>
<div>
Telephone Sales</div>
<div>
&nbsp;</div>
<ol style="margin-bottom: 0pt; margin-left: 36pt; margin-top: 0pt;">
<li>Set Sales Meetings/Appointments
</li>
<li>Gather Information
</li>
<li>Solve Customer Problems
</li>
<li>Make Sales</li>
</ol>
<div>
&nbsp;</div>
<div>
&nbsp;</div>
<ul style="margin-bottom: 0pt; margin-left: 36pt; margin-top: 0pt;">
<li>Skills – How you conduct yourself on the phone
</li>
<li>Process – The steps you use to accomplish your objectives
</li>
<li>Efficiency – The # of people you contact during your time on the phone
</li>
<li>Lead Levels –Level of people you contact within an organization</li>
</ul>
<div>
&nbsp;</div>
<div style="text-indent: 18pt;">
Who am I, where am I from (what company), what is 
my call in reference to. </div>
<div>
&nbsp;</div>
<div style="padding-left: 18pt;">
Hello, this is Darrell Wolfe from WF 
Conceptions. </div>
<div style="padding-left: 18pt;">
Could you please tell Mr/Mrs ____ I’m on the 
line. I’ll hold thank you. </div>
<div style="padding-left: 18pt;">
I’m calling to reach Mr/Mrs ____. Could you 
please tell them I’m on the line. Thanks. </div>
<div>
&nbsp;</div>
<div>
Method One: Introduction by someone. I was referred to call you by 
____.</div>
<div>
Method Two: Correspondence. Send a brief note ahead of your call. Then: 
“I’m calling in reference to some recent “Correspondence” we’ve had. </div>
<div>
In response to an email you received this week. To Follow up on an idea you 
got in writing recently? </div>
<div>
&nbsp;</div>
<div>
(Never use words like: letter, brochure, information, literature )</div>
<div>
(Instead use: Correspondence, Writing, Fax/Email) </div>
<div>
&nbsp;</div>
<div>
&nbsp;</div>
<div>
<b>Two Prong Once You Get Through</b></div>
<div>
<b>A Relevant Powerful Attention Getter</b></div>
<div>
<b>Referral</b>, Positive Relationship</div>
<div>
<b>Idea</b>, Provide and idea or trade news that is relevant</div>
<div>
<b>Compliment</b>, strength-centered comment followed by a question about 
that strength. </div>
<div>
<b>Exhibit</b>, displaying something physical that illustrates an important 
piece of information. </div>
<div>
AND</div>
<span style="font-family: Calibri, sans-serif; font-size: x-small;">































</span><br />
<div>
<b>General Benefit Statement</b></div>
