---
title: '2014/01/12 Journal Sunday'
date: '2014-01-12T16:05:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '907186209545510454'
blogger_filename: '/2014/01/20140112-journal-sunday.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
Thanks</h4>
I'm thankful for the blood of Jesus that causes us to be healed. I'm thankful for Kenneth Copeland and the platform and circle of influence he is. Not only has his teaching been powerful in my life, but the people that he's influenced and the people he's introduced me to through his ministry has been amazing.<br />
<br />
<br />
<br />
<h4>
Feelings</h4>
I'm feeling a little put out because I planned to get up today for the ministry center and yet again we couldn't make that happen today.<br />
<br />
I'm feeling pain in my neck and head since I woke up. Thanking Jesus for the healing that belongs to me to work it's way into my body's sense realm.<br />
<br />
I'm feeling grateful for my children, but tired of their constant questions for activities.<br />
<br />
<br />
<h4>
What's going on</h4>
Kids should not be put into children's ministry coughing and sniffling, which they are, so we didn't go this morning. But I had a good time on the couch watching Kenneth Copeland with Flavia sleeping on the couch beside me. I don't pause often enough. I'm inspired by Kenneth and David Barton to work more on the God's Platform blog. That won't be a regular project like my main three by any means. But I do want to be aware of it and update it as I learn more and more about the things of God concerning running a nation.<br />
<br />
DW<br />
<br />
<br />
<br />
<br />
<br />
<br />