---
title: '2014.01.09 Journal Thur'
date: '2014-01-09T13:27:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7457357181646800926'
blogger_filename: '/2014/01/20140109-journal-thur.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
Thankful For</h4>
<br />
<ul>
<li>Jesus' Sacrifice</li>
<li>Holy Spirit's constant guidance.</li>
<li>Flavia's heart towards God and me.</li>
<li>My children who are so full of life.</li>
<li><br /></li>
</ul>
<br />
<h4>
Feeling</h4>
I'm feeling resentful for having to go to work on my day off. Not because they "needed" me, but because I need the money that bad. I had PTO on Monday. So the ten hours I'm going to work today are all at regular pay not overtime pay. But we are so far behind it's worth it. It's not sustainable though. I NEED a new plan.<br />
<br />
I know that these blogs and my writing will become something. I feel more purpose and intention behind them now than I ever have. Maybe the pressure of money and job are good because they make me uncomfortable enough to want to do something else. But the pressure also makes me want to spend time doing something like looking for new work. Creative work is hard with this kind of pressure. I'm going to go to work and do my best.<br />
<br />
<br />
<h4>
What's happening right now</h4>
<br />
&nbsp;My mom is coming out on Monday and will be here for a week. That should be... interesting. Father help me be gracious. I've built up this wall with her. She can be very invading. She means well, but she's so full of complaining and millions of stories about what was, and has very little eye to what is or will be. Show me how to work with her, and not against her, as she visits.<br />
<br />
I've had more sex this past week than I've had in all of 2013. It's been very intriguing. I can feel myself shutting down from it though and wanting to pull away to the comfort of my intellectual work. I need to make a point to only work on the computer when it was pre planned and scheduled. Half the time I come in here and I'm not productive anyway because I get distracted.<br />
<br />
DW<br />
<br />
<br />
<br />
<br />