---
title: '2014/04/23  Journal  Job Change Update: Dealer Services Research Remediation Specialist.'
date: '2014-04-23T13:31:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3840754987523760071'
blogger_filename: '/2014/04/job-change-update-dealer-services.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
  - 'Life Events'
---

I just got a call from Steve the HR rep from Dealer Services. He offered me the position for Research Remediation. Pay is 10% increase from current position. $17.47/Hour Roughly $36,333/Year.<br />
<br />
It's not a HUGE increase, but it will be more than I've been netting in sales after my bonus' and OT cut off two quarters ago. I've been living on $32,000&nbsp;+-<br />
<br />
It should be a good environment too, better fit for my personality and gifting.<br />
<br />
It will be different, and it won't be perfect. But I think it will be a better place for me and the family.<br />
<br />
....<br />
<br />
I'm feeling excited. Still a bit bummed that I didn't get the $50,000 job closer to home. BUT, this job will have better benefits emotionally and mentally and maybe provide a better path to growth if I want to move up before my blog business takes off.<br />
<br />
Connor keeps bugging me every ten minutes to see some toy of his. SO I'm going to go out into the living room and face the onslaught of kids.<br />
<br />
Thank you Father, for coming through on this job thing. Reveal to me how I can be of services not just to WF, but to YOU in this position, and at Gateway.