---
title: '2014/02/25 Journal Tue'
date: '2014-02-25T13:08:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1899649088082073986'
blogger_filename: '/2014/02/20140225-journal-tue.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=105&amp;user_id=darrellwolfe&amp;version=1" target="_blank">Day 105</a><br />Choose The Good Part And Be Blessed<br />Isaiah 48:17<br />17… “I am the Lord your God, who teaches you to profit, who leads you by the way you should go.<br />God instructs us for our own benefit. He wants us to profit in every area of our lives — health, finances, career, marriage and family relationships. The Bible says that it is God who teaches us to profit. And it is He who leads us in the way that we should go.<br />...<br /><span style="background-color: #eeedeb; font-size: 12.222222328186035px;">Yet, many of us are like Martha. We worry about many things. And we are so busy that we have no time to sit at Jesus’ feet to listen to His Word and enjoy communion with Him. When we fail to draw from Him, we end up running on our own strength, and relying on our own flesh and wisdom to get things done. Listen, you can never have a plan that is better than God’s!</span></blockquote>
<br />
<br />
I have been so busy trying to do more and more with the blogs that I'm actually getting less and less done. If I would simply take the time to pray and ask God what I should do, he would direct me to the most important things.<br />
<br />
HE would teach me to profit. He would also lead me to a better place than WF to land while I get these up and running.<br />
<br />
<br />
<h4>
Thankful:</h4>
Thankful for Joseph Prince and Kenneth Copeland. Great reminders to me constantly of bringing it back to the most important thing.<br />
<br />
<h4>
Feeling:</h4>
Feeling better this morning. God woke me up at 6 AM without the alarm. Still don't want to go to WF today. But it is what it is. If I leave before April I'm going to owe back some of the PTO I've already used, I don't want to add more to that debt.<br />
<br />
<h4>
What's Up?</h4>
Had this weird dream last night.<br />
<br />
As with most dreams I'm inside more than one character... now that I've studied good writing though, that's not as weird as it was before. I always thought... "Why was I a woman?" but that's actually called Point Of View Character and you experience that often in fiction stories and don't think twice about it. Interesting.<br />
<br />
Anyway. Dream.<br />
<br />
There is a couple. She is a cop/detective and he is? Scientist? Maybe? He tells her he has to go. He is abducted and the police/FBI are investigating the crime scene. But they are overlooking lots of details, almost as if it's more to humor her than actually do anything about it. Then she starts her own investigation, starting my marking different points on the ground near the crime scene.<br />
<br />
She keeps finding more and more irregularities. When she brings them up she gets shut down and ignored. SO she stops trying to get cooperation because has this feeling they are in on it. Then other weird things are happening. For example, she comes home and there is a glass that has been cleaned and sitting on the dry rack towel... but when she left there was no glass it was perfectly clean, or was it? Was she so tired that she'd forgotten using and cleaning the glass?<br />
<br />
Meanwhile... images of him hiding out in an apartment during the day, but leaving at night...<br />
<br />
Low and behold... he's been in their apartment the entire time. That's why the odd glass or moved book. But why hasn't he told her he's ok? Why is he hanging out there and then leaving? Why are others covering it up? Something isn't right... but she can't place her finger on what's happening. More questions than answers.<br />
<br />
Then I woke up. Sounds like the start of a great storyline... Maybe that's where my best stories will come from?<br />
<br />
DW<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />