---
title: 'Compassion'
date: '2014-10-26T22:59:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7002050762485657892'
blogger_filename: '/2014/10/compassion.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<h4>
On July 14, 2014, I asked Jack, by text</h4>
<br />
"In one concise sentence what is the core of Call to Excellence? If you had ten seconds in an elevator? "Call to Excellence is about...."<br />
<br />
He asked for some time on that.<br />
<br />
I also asked for a key verse, and told him to take his time, we'd talk when we met next.<br />
<br />
He also asked me to ponder this: "What is compassion?"<br />
<br />
<h4>
So... What IS Compassion?</h4>
<br />
Word search revealed 44 results in the NKJV<br />
<br />
<div class="ResultList">
<ul id="Page-1" style="display: block;">
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/exodus/2-6.html">Exodus 2:6 NKJV</a></span></h4>
<span style="font-size: x-small;">
            </span><div class="ResultText">
<span style="font-size: x-small;">And when she had opened it, she saw the child, and behold, the baby wept. <span style="background-color: yellow;">So she had <span class="Highlight">compassion</span> on him, and said, "This is one of the Hebrews' children."</span></span></div>
<span style="font-size: x-small;">
            </span><div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/exodus/2.html">Read Exodus 2</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Exodus+2:6">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/exodus/2-6-compare.html">Compare Translations</a></span>
            </div>
<span style="font-size: x-small;">
          </span></li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/exodus/33-19.html">Exodus 33:19 NKJV</a></span></h4>
<div class="ResultText">
<span style="background-color: yellow;"><span style="font-size: x-small;">Then He said, "I will make all My 
goodness pass before you, and I will proclaim the name of the Lord 
before you. I will be gracious to whom I will be gracious, and I will 
have <span class="Highlight">compassion</span> on whom I will have <span class="Highlight">compassion</span>."</span></span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/exodus/33.html">Read Exodus 33</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Exodus+33:19">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/exodus/33-19-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/deuteronomy/13-17.html">Deuteronomy 13:17 NKJV</a></span></h4>
<div class="ResultText">
<span style="background-color: yellow;"><span style="font-size: x-small;">So none of the accursed things shall
 remain in your hand, that the Lord may turn from the fierceness of His 
anger and show you mercy, have <span class="Highlight">compassion</span> on you and multiply you, just as He swore to your fathers,</span></span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/deuteronomy/13.html">Read Deuteronomy 13</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Deuteronomy+13:17">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/deuteronomy/13-17-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/deuteronomy/30-3.html">Deuteronomy 30:3 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">that the Lord your God will bring you back from captivity, and <b>have <span class="Highlight">compassion</span> on you,</b> and gather you again from all the nations where the Lord your God has scattered you.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/deuteronomy/30.html">Read Deuteronomy 30</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Deuteronomy+30:3">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/deuteronomy/30-3-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/deuteronomy/32-36.html">Deuteronomy 32:36 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">"For the Lord will judge His people And have <b><span class="Highlight">compassion</span> </b>on His servants, When He sees that their power is gone, And there is no one remaining, bond or free.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/deuteronomy/32.html">Read Deuteronomy 32</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Deuteronomy+32:36">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/deuteronomy/32-36-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/1-samuel/23-21.html">1 Samuel 23:21 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">And Saul said, "Blessed are you of the Lord, for you have <span class="Highlight">compassion</span> on me.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/1-samuel/23.html">Read 1 Samuel 23</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=1%20Samuel+23:21">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/1-samuel/23-21-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/1-kings/3-26.html">1 Kings 3:26 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">Then the woman whose son was living spoke to the king, for she yearned with <span class="Highlight">compassion</span>
 for her son; and she said, "O my lord, give her the living child, and 
by no means kill him!" But the other said, "Let him be neither mine nor 
yours, but divide him."</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/1-kings/3.html">Read 1 Kings 3</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=1%20Kings+3:26">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/1-kings/3-26-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/1-kings/8-50.html">1 Kings 8:50 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">and forgive Your people who have 
sinned against You, and all their transgressions which they have 
transgressed against You; and grant them <span class="Highlight">compassion</span> before those who took them captive, that they may have <span class="Highlight">compassion</span> on them</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/1-kings/8.html">Read 1 Kings 8</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=1%20Kings+8:50">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/1-kings/8-50-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/2-kings/13-23.html">2 Kings 13:23 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">But the Lord was gracious to them, had <span class="Highlight">compassion</span>
 on them, and regarded them, because of His covenant with Abraham, 
Isaac, and Jacob, and would not yet destroy them or cast them from His 
presence.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/2-kings/13.html">Read 2 Kings 13</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=2%20Kings+13:23">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/2-kings/13-23-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/2-chronicles/30-9.html">2 Chronicles 30:9 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">For if you return to the Lord, your brethren and your children will be treated with <span class="Highlight">compassion</span>
 by those who lead them captive, so that they may come back to this 
land; for the Lord your God is gracious and merciful, and will not turn 
His face from you if you return to Him."</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/2-chronicles/30.html">Read 2 Chronicles 30</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=2%20Chronicles+30:9">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/2-chronicles/30-9-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/2-chronicles/36-15.html">2 Chronicles 36:15 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">And the Lord God of their fathers sent warnings to them by His messengers, rising up early and sending them, because He had <span class="Highlight">compassion</span> on His people and on His dwelling place.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/2-chronicles/36.html">Read 2 Chronicles 36</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=2%20Chronicles+36:15">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/2-chronicles/36-15-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/2-chronicles/36-17.html">2 Chronicles 36:17 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">Therefore He brought against them 
the king of the Chaldeans, who killed their young men with the sword in 
the house of their sanctuary, and had no <span class="Highlight">compassion</span> on young man or virgin, on the aged or the weak; He gave them all into his hand.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/2-chronicles/36.html">Read 2 Chronicles 36</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=2%20Chronicles+36:17">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/2-chronicles/36-17-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/psalms/78-38.html">Psalm 78:38 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">But He, being full of <span class="Highlight">compassion</span>,
 forgave their iniquity, And did not destroy them. Yes, many a time He 
turned His anger away, And did not stir up all His wrath;</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/psalms/78.html">Read Psalm 78</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Psalms+78:38">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/psalms/78-38-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/psalms/86-15.html">Psalm 86:15 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">But You, O Lord, are a God full of <span class="Highlight">compassion</span>, and gracious, Longsuffering and abundant in mercy and truth.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/psalms/86.html">Read Psalm 86</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Psalms+86:15">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/psalms/86-15-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/psalms/90-13.html">Psalm 90:13 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">Return, O Lord! How long? And have <span class="Highlight">compassion</span> on Your servants.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/psalms/90.html">Read Psalm 90</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Psalms+90:13">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/psalms/90-13-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/psalms/111-4.html">Psalm 111:4 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">He has made His wonderful works to be remembered; The Lord is gracious and full of <span class="Highlight">compassion</span>.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/psalms/111.html">Read Psalm 111</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Psalms+111:4">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/psalms/111-4-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/psalms/112-4.html">Psalm 112:4 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">Unto the upright there arises light in the darkness; He is gracious, and full of <span class="Highlight">compassion</span>, and righteous.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/psalms/112.html">Read Psalm 112</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Psalms+112:4">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/psalms/112-4-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/psalms/135-14.html">Psalm 135:14 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">For the Lord will judge His people, And He will have <span class="Highlight">compassion</span> on His servants.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/psalms/135.html">Read Psalm 135</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Psalms+135:14">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/psalms/135-14-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/psalms/145-8.html">Psalm 145:8 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">The Lord is gracious and full of <span class="Highlight">compassion</span>, Slow to anger and great in mercy.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/psalms/145.html">Read Psalm 145</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Psalms+145:8">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/psalms/145-8-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/isaiah/49-15.html">Isaiah 49:15 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">"Can a woman forget her nursing child, And not have <span class="Highlight">compassion</span> on the son of her womb? Surely they may forget, Yet I will not forget you.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/isaiah/49.html">Read Isaiah 49</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Isaiah+49:15">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/isaiah/49-15-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/jeremiah/12-15.html">Jeremiah 12:15 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">Then it shall be, after I have plucked them out, that I will return and have <span class="Highlight">compassion</span> on them and bring them back, everyone to his heritage and everyone to his land.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/jeremiah/12.html">Read Jeremiah 12</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Jeremiah+12:15">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/jeremiah/12-15-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/lamentations/3-32.html">Lamentations 3:32 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">Though He causes grief, Yet He will show <span class="Highlight">compassion</span> According to the multitude of His mercies.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/lamentations/3.html">Read Lamentations 3</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Lamentations+3:32">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/lamentations/3-32-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/ezekiel/16-5.html">Ezekiel 16:5 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">No eye pitied you, to do any of these things for you, to have <span class="Highlight">compassion</span> on you; but you were thrown out into the open field, when you yourself were loathed on the day you were born.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/ezekiel/16.html">Read Ezekiel 16</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Ezekiel+16:5">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/ezekiel/16-5-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/micah/7-19.html">Micah 7:19 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">He will again have <span class="Highlight">compassion</span> on us, And will subdue our iniquities. You will cast all our  sins Into the depths of the sea.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/micah/7.html">Read Micah 7</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Micah+7:19">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/micah/7-19-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/zechariah/7-9.html">Zechariah 7:9 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">"Thus says the Lord of hosts:  'Execute true justice, Show mercy and <span class="Highlight">compassion</span> Everyone to his brother.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/zechariah/7.html">Read Zechariah 7</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Zechariah+7:9">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/zechariah/7-9-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/matthew/9-36.html">Matthew 9:36 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">But when He saw the multitudes, He was moved with <span class="Highlight">compassion</span> for them, because they were weary  and scattered, like sheep having no shepherd.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/matthew/9.html">Read Matthew 9</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Matthew+9:36">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/matthew/9-36-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/matthew/14-14.html">Matthew 14:14 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">And when Jesus went out He saw a great multitude; and He was moved with <span class="Highlight">compassion</span> for them, and healed their sick.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/matthew/14.html">Read Matthew 14</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Matthew+14:14">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/matthew/14-14-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/matthew/15-32.html">Matthew 15:32 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">Now Jesus called His disciples to Himself and said, "I have <span class="Highlight">compassion</span>
 on the multitude, because they have now continued with Me three days 
and have nothing to eat. And I do not want to send them away hungry, 
lest they faint on the way."</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/matthew/15.html">Read Matthew 15</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Matthew+15:32">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/matthew/15-32-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/matthew/18-27.html">Matthew 18:27 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">Then the master of that servant was moved with <span class="Highlight">compassion</span>, released him, and forgave him the debt.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/matthew/18.html">Read Matthew 18</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Matthew+18:27">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/matthew/18-27-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/matthew/18-33.html">Matthew 18:33 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">Should you not also have had <span class="Highlight">compassion</span> on your fellow servant, just as I had pity on you?'</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/matthew/18.html">Read Matthew 18</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Matthew+18:33">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/matthew/18-33-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/matthew/20-34.html">Matthew 20:34 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">So Jesus had <span class="Highlight">compassion</span> and touched their eyes. And immediately their eyes received sight, and they followed Him.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/matthew/20.html">Read Matthew 20</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Matthew+20:34">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/matthew/20-34-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/mark/1-41.html">Mark 1:41 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">Then Jesus, moved with <span class="Highlight">compassion</span>, stretched out His hand and touched him, and said to him, "I am willing; be cleansed."</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/mark/1.html">Read Mark 1</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Mark+1:41">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/mark/1-41-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/mark/5-19.html">Mark 5:19 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">However, Jesus did not permit him, 
but said to him, "Go home to your friends, and tell them what great 
things the Lord has done for you, and how He has had <span class="Highlight">compassion</span> on you."</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/mark/5.html">Read Mark 5</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Mark+5:19">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/mark/5-19-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/mark/6-34.html">Mark 6:34 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">And Jesus, when He came out, saw a great multitude and was moved with <span class="Highlight">compassion</span> for them, because they were like sheep not having a shepherd. So He began to teach them many things.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/mark/6.html">Read Mark 6</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Mark+6:34">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/mark/6-34-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/mark/8-2.html">Mark 8:2 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">"I have <span class="Highlight">compassion</span> on the multitude, because they have now continued with Me three days and have nothing to eat.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/mark/8.html">Read Mark 8</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Mark+8:2">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/mark/8-2-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/mark/9-22.html">Mark 9:22 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">And often he has thrown him both into the fire and into the water to destroy him. But if You can do anything, have <span class="Highlight">compassion</span> on us and help us."</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/mark/9.html">Read Mark 9</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Mark+9:22">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/mark/9-22-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/luke/7-13.html">Luke 7:13 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">When the Lord saw her, He had <span class="Highlight">compassion</span> on her and said to her, "Do not weep."</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/luke/7.html">Read Luke 7</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Luke+7:13">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/luke/7-13-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/luke/10-33.html">Luke 10:33 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">But a certain Samaritan, as he journeyed, came where he was. And when he saw him, he had <span class="Highlight">compassion</span>.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/luke/10.html">Read Luke 10</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Luke+10:33">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/luke/10-33-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/luke/15-20.html">Luke 15:20 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">And he arose and came to his father. But when he was still a great way off, his father saw him and had <span class="Highlight">compassion</span>, and ran and fell on his neck and kissed him.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/luke/15.html">Read Luke 15</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Luke+15:20">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/luke/15-20-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/romans/9-15.html">Romans 9:15 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">For He says to Moses, "I will have mercy on whomever I will have mercy, and I will have <span class="Highlight">compassion</span> on whomever I will have <span class="Highlight">compassion</span>." </span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/romans/9.html">Read Romans 9</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Romans+9:15">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/romans/9-15-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/hebrews/5-2.html">Hebrews 5:2 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">He can have <span class="Highlight">compassion</span> on those who are ignorant and going astray, since he himself is also subject to weakness.</span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/hebrews/5.html">Read Hebrews 5</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Hebrews+5:2">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/hebrews/5-2-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/hebrews/10-34.html">Hebrews 10:34 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">for you had <span class="Highlight">compassion</span>
 on me  in my chains, and joyfully accepted the plundering of your 
goods, knowing that you have a better and an enduring possession for 
yourselves in heaven. </span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/hebrews/10.html">Read Hebrews 10</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Hebrews+10:34">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/hebrews/10-34-compare.html">Compare Translations</a></span>
            </div>
</li>
<li>
            <h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/1-peter/3-8.html">1 Peter 3:8 NKJV</a></span></h4>
<div class="ResultText">
<span style="font-size: x-small;">Finally, all of you be of one mind, having <span class="Highlight">compassion</span> for one another; love as brothers, be tenderhearted, be courteous; </span></div>
<div class="QuickLinks">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/1-peter/3.html">Read 1 Peter 3</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=1%20Peter+3:8">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/1-peter/3-8-compare.html">Compare Translations</a></span>
            </div>
</li>
<li><span style="font-size: x-small;">
            </span><h4 class="ResultTitle">
<span style="font-size: x-small;"><a href="http://www.biblestudytools.com/nkjv/jude/1-22.html">Jude 1:22 NKJV</a></span></h4>
<span style="font-size: x-small;">
            </span><div class="ResultText">
<span style="font-size: x-small;">And on some have <span class="Highlight">compassion</span>, making a distinction; </span></div>
<span style="font-size: x-small;">
            </span><div class="QuickLinks">
<span style="font-size: x-small;">
       <a href="http://www.biblestudytools.com/nkjv/jude/1.html">Read Jude 1</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Jude+1:22">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/jude/1-22-compare.html">Compare Translations</a></span>
            </div>
</li>
</ul>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />