---
title: '2014/06/04 Wed Journal Dopamine'
date: '2014-06-04T11:25:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3622617508284632854'
blogger_filename: '/2014/06/20140604-wed-journal-dopamine.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
I am reading the Mars and Venus Diet. I am becoming rapidly convinced that Flavia is Serotonin deficient and I am Dopamine deficient. Almost everything I've complained about in my own body and mood's is outlined in this book. Hers also. He clearly states that brining your brain chemicles in line is only half the battle, you still need the tools to deal with relationships, but the brain health helps give you the motivation to use those tools.<br />
<br />
I'm looking into it now.<br />
<br />
I'm enjoying work, and still grumpy and low energy at home. Apparently this is a classic symptom of low dopamine in men? You mean I'm not just grumpy? I can enjoy my family? What a concept! I've been talking with God about changing me to make me the man my family needs me to be, and helping me want to want them. Is it possible it could be as simple as brain chemical imbalance? My entire childhood and years leading up to meeting Flavia I experienced these symptoms to one degree of another.<br />
<br />
All the relationship hoping, and mood swings, BiPolar tendencies... much if it related to brain health. I knew sin had ruined diet in the world, and that caused toxicity and chemical imbalance. I didn't know it went this deep.<br />
<br />
Going to work, signing off. Darrell<br />
<br />
<br />
********<br />
<br />
<br />
<a href="http://www.balancingbrainchemistry.co.uk/32/Dopamine-Deficient-Depression.html" target="_blank">http://www.balancingbrainchemistry.co.uk/32/Dopamine-Deficient-Depression.html&nbsp;</a><br />
<br />
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
<span style="font-size: 11pt;"><strong>Increasing Dopamine with Diet, Supplements and Exercises.</strong></span></div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
&nbsp;</div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
<b><span style="font-size: x-large;"><span style="font-size: 11pt;">Dopamine Diet</span></span></b></div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
<span style="font-size: 11pt;">Eat lots of tyrosine and phenylalanine rich foods: cottage cheese, ricotta, wild game, turkey, chicken, duck, walnuts, oats, yoghurt and dark chocolate.</span></div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
&nbsp;</div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
<b><span style="font-size: 11pt;">Supplements to boost Dopamine:</span></b></div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
<span style="font-size: 11pt;">Tyrosine and L-phenylalanine make dopamine, use them for low-energy type depression, addictive behaviour, including (depressed) low mood food craving and overeating phases.&nbsp;</span></div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
&nbsp;</div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
<b><span style="font-size: 11pt;">L phenylalanine&nbsp;</span></b><b><span style="font-size: 11pt;">&gt;&gt;</span></b><b><span style="font-size: 11pt;">&nbsp;Tyrosine&nbsp;</span>&gt;&gt;<span style="font-size: 11pt;">&nbsp;(l-Dopa)&nbsp;</span></b><b><span style="font-size: 11pt;">&gt;&gt;</span></b><b><span style="font-size: 11pt;">&nbsp;Dopamine&nbsp;</span></b><b><span style="font-size: 11pt;">&gt;&gt;</span></b><b><span style="font-size: 11pt;">&nbsp;Norepinephrine</span></b></div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
&nbsp;</div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
<span style="font-size: 11pt;">(Phenylalanine also makes PEA important in atypical depression and&nbsp;cholecystokinin CCK with potential weight-loss benefits, see PEA chapter).</span></div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
&nbsp;</div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
<span style="font-size: 11pt;">CAUTION with dopamine boosting supplements in bipolar see bipolar syndrome below.</span></div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
&nbsp;</div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px; margin: 0cm 0cm 0pt 18pt; text-indent: -18pt;">
<span style="font-size: 11pt;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><b><span style="font-size: 11pt;">Tyrosine</span></b><span style="font-size: 11pt;">&nbsp;800-1500 m</span><span style="font-size: 11pt;">g</span><span style="font-size: 11pt;">&nbsp;(up to 5000 with severe depression or addiction) on an empty stomach in the morning.&nbsp;</span><br /><strong>Or</strong><b><span style="font-size: 11pt;"><br /></span></b></div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px; margin: 0cm 0cm 0pt 18pt; text-indent: -18pt;">
<span style="font-size: 11pt;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><b><span style="font-size: 11pt;">L-phenylalanine</span></b><span style="font-size: 11pt;">&nbsp;1000-1500 mg on an empty stomach in the morning.</span><br /><b>Or</b><span style="font-size: 15px;"><b>DL-phenylalanine</b>&nbsp;2000-3000 mg on an empty stomack in the morning</span><b><br /></b></div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px; margin: 0cm 0cm 0pt 18pt; text-indent: -18pt;">
<span style="font-size: 11pt;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><b><span style="font-size: 11pt;">B Complex</span></b><span style="font-size: 11pt;">&nbsp;50-100 mg</span></div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px; margin: 0cm 0cm 0pt 18pt; text-indent: -18pt;">
<span style="font-size: 11pt;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><b><span style="font-size: 11pt;">B6</span></b><span style="font-size: 11pt;">&nbsp;50-150 mg (keep the total B6 less than 250 mg/day unless you have pyroluria).</span></div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
<span style="font-size: 11pt;">For simplicity you could just take your high dose B6 by taking 100-250 mg B complex.&nbsp;</span></div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px;">
&nbsp;</div>
<div style="background-color: white; font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 18px; margin: 0cm 0cm 0pt 18pt; text-indent: -18pt;">
<span style="font-size: 11pt;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><b><span style="font-size: 11pt;">Rhodiola</span></b><span style="font-size: 11pt;">&nbsp;500 mg (3% standardised) 1-3 times per day.&nbsp;(I use Now Foods).</span></div>
