---
title: '2014/03/09 Journal Sunday'
date: '2014-03-09T15:06:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2411471394622192475'
blogger_filename: '/2014/03/20140309-journal-sunday.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;">
<br /><a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=117&amp;user_id=darrellwolfe&amp;version=1" target="_blank">Day 117</a><br />Don’t Sweat Over Loss Or Waste<br />Luke 15:22–23<br />22“But the father said to his servants, ‘Bring out the best robe and put it on him, and put a ring on his hand and sandals on his feet. 23And bring the fatted calf here and kill it, and let us eat and be merry;<br /><br />Perhaps you have lost something recently, or you are frustrated that something has gone to waste due to a bad decision you made. My friend, God does not see the finality of the loss or waste the way you do. When you come to Him with it, He sees it as an opportunity to restore to you what has been lost or wasted...&nbsp;</blockquote>
<blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;">
Even if, like the prodigal son, you feel far away from your heavenly Father, or you feel that you have disappointed Him, don’t despair. The truth is that the moment you come to Him, He immediately restores to you the robe of honor to clothe your nakedness, the ring of authority to declare your position of power and dominion, and the sandals on your feet (which servants do not wear) to reinstate you as a son in His house.<br />He reassures you that you had never lost the position of sonship. And He celebrates your return to Him with the killing of a fatted calf because you are His beloved child whom He cherishes.</blockquote>
<br />
<h4>
Prodigal Son Continued...</h4>
<br />
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=117&amp;user_id=darrellwolfe&amp;version=1">https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=117&amp;user_id=darrellwolfe&amp;version=1</a><br />
<br />
What if... What if the prodigal son came home as a son, just like the story goes. Then afterward the Father convinces the brother to treat him as family, as guest, and feed and shelter him, but still all the "things" of the household belong to the older brother. There is no inheritance left for the younger one, his was spent.<br />
<br />
What happens next? Could he, having learned from his mistakes, take a job. Not on his families estate because he doesn't want his Brother to feel taken from. From a local estate that knows the family. Maybe he even takes a job in a different form altogether, like in the market. With that job he tried to pay his brother for his keep but "duty" prevents him from accepting anything from younger brother. So he saves, and saves, and invests, eventually becoming even wealthier than his brother, like a Jospeh in modern times...<br />
<br />
Interesting story idea.<br />
<br />
<br />
<br />
<h4>
Thankful:</h4>
I'm thankful, despite my frequent despair over my current situation, that God is pushing me forward as a writer and teacher. I'm looking forward to see what that becomes.<br />
<br />
<br />
<h4>
Feeling:</h4>
Exited and Nervous. I'm getting multiple impressions in the last 9 months I should start a podcast, and the last two years I should start a YouTube Channel. The two can be one, just posting in different formats. Combine that with Google Hangouts for interviews, I got quite a thing going maybe... We shall see.<br />
<br />
<h4>
What's Up?</h4>
<br />
Church Today! Go to get ready<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />