---
title: '2014/03/23 Journal Sunday Car, TDA, National Day of Prayer is coming'
date: '2014-03-23T14:56:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4083183467005658412'
blogger_filename: '/2014/03/20140323-journal-sunday-car-tda.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
COME:<br />
<br />
<br />
<blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">Day 131</a>Don’t Be Dust-Conscious<br />Luke 13:11<br />11And behold, there was a woman who had a spirit of infirmity eighteen years, and was bent over and could in no way raise herself up.<br /><br />If you don’t want to be devoured by him, then lift your eyes above the dust! Instead of looking at your failures, look to Christ who has delivered you from every defeat. See yourself the way God sees you — righteous and holy in Christ. (Colossians 3:12; 2 Corinthians 5:21) You are not dust because you are not in and of the flesh — you are in and of the Spirit. (Romans 8:9)<br />My friend, the more you realize who you are in Christ, the more you will straighten up and walk the way God sees you — a new creation with His authority, power and overcoming Spirit!</blockquote>
<br />
HERE:<br />
<br />
I am conscious of my failures, short comings, and my lack. I am so focused on what I want and don't have, or have and don't want that I fail to see what I do have.<br />
<br />
I am realizing that I cannot succeed in life until I find deep gratitude for what I have now, and celebrate the small wins.<br />
<br />
<br />
DO:<br />
<br />
I'm going to take time to celebrate the small wins in my wife's life, and the kids. Find something to celebrate them for today. Two Birds (Celbrate Wins/Gratitude for what you have) in one!<br />
<br />
<h4>
Thankful:</h4>
I am thankful for my family. Especially Connor today, who is persistent. I could use some more of that in my personality.<br />
<h4>
Feeling:</h4>
Feeling hopeful about the future.<br />
<br />
Sad about my car being beyond my repair.<br />
<br />
<br />
<h4>
What's Up?</h4>
My Ford has oil on one spark plug. My best guess is piston ring. That is outside of my expertise and I'm going to be done with it. Putting it on Craig's List.<br />
<br />
I had a GREAT interview with Rachel Guillo at TD Ameritrade. She asked me a few questions beyond the formal ones, and then said "I'm not going to lie. I find you very interesting and wanted to ask a few more questions. But we have some more interviews to do." So that was encouraging. That happened last Wed.<br />
<br />
I have another interview within WF for a Research Position. That might work as a back up, but I'm really hoping for this TDA job.<br />
<br />
I'm feeling there needs to be more work on the business end of the Life In Fort Worth blog. More "How To..." around fort worth, car registrations, voting, etc.<br />
<br />
That reminds me, I need to go post the national day of prayer on LIF<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
Time To Give Up On The Car: Craigs List Ad:<br />
<br />
Title:<br />
<br />
1995 Ford Escort Station Wagon (Not Fully Running - Needs a Mechanic)<br />
<br />
This<br />
<br />
<br />
<br />