---
title: '2014/04/21 Journal Monday'
date: '2014-04-21T12:41:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '455642300705890098'
blogger_filename: '/2014/04/20140421-journal-monday.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

As you can tell, my journaling has been off. Which means my morning routine has been off too. I'm in a deep depression lately. I feel so trapped by everything around me. I reached out to Olivier and he has over come the same issue. He's helping me through that.<br />
<br />
<br />
I'm up earlier than more of the last few weeks, but not early. I need to go get ready for work... hell... whatever you call it.<br />
<br />
Joshua 1 and 2 has been an interesting study.<br />
<br />
<h4>
<a href="https://www.bible.com/bible/1/jos.1.kjv" target="_blank">Joshua 1</a></h4>
<br />
<br />
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px;">
<span class="verse v1" data-usfm="JOS.1.1" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">1</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Now after the death of Moses the servant of the&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;it came to pass, that the&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;spake unto Joshua the son of Nun, Moses' minister, saying,</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v1" data-usfm="JOS.1.1" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v2" data-usfm="JOS.1.2" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">2</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Moses my servant is dead; now therefore arise, go over this Jordan, thou, and all this people, unto the land which I do give to them, even to the children of Israel.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v2" data-usfm="JOS.1.2" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v3" data-usfm="JOS.1.3" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">3</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Every place that the sole of your foot shall tread upon, that have I given unto you, as I said unto Moses.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v3" data-usfm="JOS.1.3" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"></span></span><span class="verse v4" data-usfm="JOS.1.4" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">4</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">From the wilderness and this Lebanon even unto the great river, the river Euphrates, all the land of the Hittites, and unto the great sea toward the going down of the sun, shall be your coast.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v4" data-usfm="JOS.1.4" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v5" data-usfm="JOS.1.5" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">5</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">There shall not any man be able to stand before thee all the days of thy life: as I was with Moses, so I will be with thee: I will not fail thee, nor forsake thee.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v5" data-usfm="JOS.1.5" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v6" data-usfm="JOS.1.6" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">6</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Be strong and of a good courage: for unto this people shalt thou divide for an inheritance the land, which I sware unto their fathers to give them.</span><span class="note f" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; cursor: default; margin: 0px; padding: 0px;"></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v6" data-usfm="JOS.1.6" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v7" data-usfm="JOS.1.7" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">7</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Only be thou strong and very courageous, that thou mayest observe to do according to all the law, which Moses my servant commanded thee: turn not from it to the right hand or to the left, that thou mayest prosper whithersoever thou goest.</span><span class="note f" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; cursor: default; margin: 0px; padding: 0px;"></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v7" data-usfm="JOS.1.7" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v8" data-usfm="JOS.1.8" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">8</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night, that thou mayest observe to do according to all that is written therein: for then thou shalt make thy way prosperous, and then thou shalt have good success.</span><span class="note f" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; cursor: default; margin: 0px; padding: 0px;"></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v8" data-usfm="JOS.1.8" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v9" data-usfm="JOS.1.9" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">9</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;thy God is with thee whithersoever thou goest.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v9" data-usfm="JOS.1.9" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v10" data-usfm="JOS.1.10" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">10</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Then Joshua commanded the officers of the people, saying,</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v10" data-usfm="JOS.1.10" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v11" data-usfm="JOS.1.11" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">11</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Pass through the host, and command the people, saying, Prepare you victuals; for within three days ye shall pass over this Jordan, to go in to possess the land, which the&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;your God giveth you to possess it.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v11" data-usfm="JOS.1.11" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v12" data-usfm="JOS.1.12" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">12</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And to the Reubenites, and to the Gadites, and to half the tribe of Manasseh, spake Joshua, saying,</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v12" data-usfm="JOS.1.12" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v13" data-usfm="JOS.1.13" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">13</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Remember the word which Moses the servant of the&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;commanded you, saying, The&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;your God hath given you rest, and hath given you this land.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v13" data-usfm="JOS.1.13" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v14" data-usfm="JOS.1.14" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">14</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Your wives, your little ones, and your cattle, shall remain in the land which Moses gave you on this side Jordan; but ye shall pass before your brethren armed, all the mighty men of valour, and help them;</span><span class="note f" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; cursor: default; margin: 0px; padding: 0px;"></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v14" data-usfm="JOS.1.14" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v15" data-usfm="JOS.1.15" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">15</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Until the&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;have given your brethren rest, as he hath given you, and they also have possessed the land which the&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;your God giveth them: then ye shall return unto the land of your possession, and enjoy it, which Moses the&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord's</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;servant gave you on this side Jordan toward the sunrising.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v15" data-usfm="JOS.1.15" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v16" data-usfm="JOS.1.16" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">16</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And they answered Joshua, saying, All that thou commandest us we will do, and whithersoever thou sendest us, we will go.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v16" data-usfm="JOS.1.16" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v17" data-usfm="JOS.1.17" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">17</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">According as we hearkened unto Moses in all things, so will we hearken unto thee: only the&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;thy God be with thee, as he was with Moses.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v17" data-usfm="JOS.1.17" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v18" data-usfm="JOS.1.18" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">18</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Whosoever he be that doth rebel against thy commandment, and will not hearken unto thy words in all that thou commandest him, he shall be put to death: only be strong and of a good courage.</span></span></div>
<br />
<br />
<br />
<h4>
<a href="https://www.bible.com/bible/1/jos.2" target="_blank">Joshua 2</a></h4>
<br />
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px;">
<span class="verse v1" data-usfm="JOS.2.1" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">1</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And Joshua the son of Nun sent out of Shittim two men to spy secretly, saying, Go view the land, even Jericho. And they went, and came into an harlot's house, named Rahab, and lodged there.</span><span class="note f" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; cursor: default; margin: 0px; padding: 0px;"></span><span class="note f" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; cursor: default; margin: 0px; padding: 0px;"></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v1" data-usfm="JOS.2.1" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v2" data-usfm="JOS.2.2" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">2</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And it was told the king of Jericho, saying, Behold, there came men in hither to night of the children of Israel to search out the country.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v2" data-usfm="JOS.2.2" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v3" data-usfm="JOS.2.3" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">3</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And the king of Jericho sent unto Rahab, saying, Bring forth the men that are come to thee, which are entered into thine house: for they be come to search out all the country.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v3" data-usfm="JOS.2.3" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v4" data-usfm="JOS.2.4" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">4</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And the woman took the two men, and hid them, and said thus, There came men unto me, but I wist not whence they were:</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v4" data-usfm="JOS.2.4" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v5" data-usfm="JOS.2.5" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">5</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And it came to pass about the time of shutting of the gate, when it was dark, that the men went out: whither the men went I wot not: pursue after them quickly; for ye shall overtake them.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v5" data-usfm="JOS.2.5" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v6" data-usfm="JOS.2.6" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">6</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">But she had brought them up to the roof of the house, and hid them with the stalks of flax, which she had laid in order upon the roof.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v6" data-usfm="JOS.2.6" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v7" data-usfm="JOS.2.7" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">7</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And the men pursued after them the way to Jordan unto the fords: and as soon as they which pursued after them were gone out, they shut the gate.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v7" data-usfm="JOS.2.7" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v8" data-usfm="JOS.2.8" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">8</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And before they were laid down, she came up unto them upon the roof;</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v8" data-usfm="JOS.2.8" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v9" data-usfm="JOS.2.9" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">9</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And she said unto the men, I know that the&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;hath given you the land, and that your terror is fallen upon us, and that all the inhabitants of the land faint because of you.</span><span class="note f" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; cursor: default; margin: 0px; padding: 0px;"></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v9" data-usfm="JOS.2.9" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v10" data-usfm="JOS.2.10" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">10</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">For we have heard how the&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;dried up the water of the Red sea for you, when ye came out of Egypt; and what ye did unto the two kings of the Amorites, that were on the other side Jordan, Sihon and Og, whom ye utterly destroyed.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v10" data-usfm="JOS.2.10" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v11" data-usfm="JOS.2.11" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">11</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And as soon as we had heard these things, our hearts did melt, neither did there remain any more courage in any man, because of you: for the&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;your God, he is God in heaven above, and in earth beneath.</span><span class="note f" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; cursor: default; margin: 0px; padding: 0px;"></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v11" data-usfm="JOS.2.11" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v12" data-usfm="JOS.2.12" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">12</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Now therefore, I pray you, swear unto me by the&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">, since I have shewed you kindness, that ye will also shew kindness unto my father's house, and give me a true token:</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v12" data-usfm="JOS.2.12" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v13" data-usfm="JOS.2.13" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">13</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And that ye will save alive my father, and my mother, and my brethren, and my sisters, and all that they have, and deliver our lives from death.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v13" data-usfm="JOS.2.13" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v14" data-usfm="JOS.2.14" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">14</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And the men answered her, Our life for yours, if ye utter not this our business. And it shall be, when the&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">hath given us the land, that we will deal kindly and truly with thee.</span><span class="note f" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; cursor: default; margin: 0px; padding: 0px;"></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v14" data-usfm="JOS.2.14" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v15" data-usfm="JOS.2.15" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">15</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Then she let them down by a cord through the window: for her house was upon the town wall, and she dwelt upon the wall.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v15" data-usfm="JOS.2.15" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v16" data-usfm="JOS.2.16" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">16</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And she said unto them, Get you to the mountain, lest the pursuers meet you; and hide yourselves there three days, until the pursuers be returned: and afterward may ye go your way.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v16" data-usfm="JOS.2.16" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v17" data-usfm="JOS.2.17" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">17</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And the men said unto her, We will be blameless of this thine oath which thou hast made us swear.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v17" data-usfm="JOS.2.17" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v18" data-usfm="JOS.2.18" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">18</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Behold, when we come into the land, thou shalt bind this line of scarlet thread in the window which thou didst let us down by: and thou shalt bring thy father, and thy mother, and thy brethren, and all thy father's household, home unto thee.</span><span class="note f" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; cursor: default; margin: 0px; padding: 0px;"></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v18" data-usfm="JOS.2.18" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v19" data-usfm="JOS.2.19" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">19</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And it shall be, that whosoever shall go out of the doors of thy house into the street, his blood shall be upon his head, and we will be guiltless: and whosoever shall be with thee in the house, his blood shall be on our head, if any hand be upon him.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v19" data-usfm="JOS.2.19" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v20" data-usfm="JOS.2.20" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">20</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And if thou utter this our business, then we will be quit of thine oath which thou hast made us to swear.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v20" data-usfm="JOS.2.20" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"></span></span><span class="verse v21" data-usfm="JOS.2.21" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">21</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And she said, According unto your words, so be it. And she sent them away, and they departed: and she bound the scarlet line in the window.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v21" data-usfm="JOS.2.21" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v22" data-usfm="JOS.2.22" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">22</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And they went, and came unto the mountain, and abode there three days, until the pursuers were returned: and the pursuers sought them throughout all the way, but found them not.</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v22" data-usfm="JOS.2.22" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v23" data-usfm="JOS.2.23" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">23</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">So the two men returned, and descended from the mountain, and passed over, and came to Joshua the son of Nun, and told him all things that befell them:</span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; display: inline; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px 0px 0px 5px; padding: 0px; text-indent: 1em;">
<span class="verse v23" data-usfm="JOS.2.23" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span></span><span class="verse v24" data-usfm="JOS.2.24" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">24</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And they said unto Joshua, Truly the&nbsp;</span><span class="nd" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-variant: small-caps; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">Lord</span></span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;hath delivered into our hands all the land; for even all the inhabitants of the country do faint because of us.</span></span></div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />