---
title: '2014/03/15 Journal Sat "God is going to do something extravagant and amazing for me, and through me, today!"'
date: '2014-03-15T13:03:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5747175583179903151'
blogger_filename: '/2014/03/20140315-journal-sat-god-is-going-to-do.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
COME:<br />
<br />
<blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=123&amp;user_id=darrellwolfe&amp;version=1" target="_blank">Day 123</a><br />God Doesn’t Remember How Bad You Were<br />Hebrews 8:12<br />12For I will be merciful to their unrighteousness, and their sins and their lawless deeds I will remember no more.”<br />Perhaps you have heard people say of others: “Oh, if only you had seen my husband in the early years of our marriage. He had such an explosive temper that I used to seek shelter in my mother’s house!”</blockquote>
<br />
<br />
HERE:<br />
<br />
God is not looking to my past, but my future. He cares about me more than I care about me. I should not only stop worrying about things, I should be passionately excited every morning.<br />
<br />
<blockquote class="tr_bq">
"God is going to do something extravagant and amazing for me, and through me, today!"&nbsp;</blockquote>
<br />
<br />
DO:<br />
<br />
I"m going to say that out loud today, and try to make that a morning habit.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
Thankful:</h4>
I'm thankful for the scheduled interview at TD Ameritrade this coming Wed.<br />
<br />
<br />
<h4>
Feeling:</h4>
I'm feeling hopeful that it will be a position better suited to my personal needs and growth. It won't be perfect, no job/company/human is, but it will be better, more stable. It won't require me to put pressure on people to buy things.<br />
<br />
<h4>
What's Up?</h4>
I'm nearly late... got to go to work. Just wanted to stop in for a quick Journal entry.<br />
<br />
I'll have to talk more about the cars in the next one.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />