---
title: 'Jeff Goins Building a Blog'
date: '2014-11-18T01:45:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8529030400834998430'
blogger_filename: '/2014/11/jeff-goins-building-blog.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<br />
Jeff Goins did a <a href="http://goinswriter.com/intentional-blog-video1" target="_blank">three part video</a> on things that he learned that made his blog excel.<br />
<br />
Finding Your Voice: Don't JUST write about what you love. Major on something that you have passion for AND allows you to provide significant value to your audience. That is your sweet spot.It's not all about me: What are YOU struggling with? Maybe prayerfully consider, checking out Yahoo Answers for questions your can answer. Ask good questions, share what you know, and listen for people to indicate back to you that you are adding value to them, and the Holy Spirit is showing you that. <br />
<br />
Building Your Brand: Brand is about more than artwork and taglines. It's about what you are known for. If someone you don't know tells someone else you don't know about you... what do you want them to say, and HOW do you want them to say it? Provide that narrative and prove it. What's obvious to you, is amazing to other people. People will forget what you said, and how you said it, but they will never forget how you made them feel. <br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />