---
title: '2014/02/07 Journal Fri'
date: '2014-02-07T13:41:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8182886252305876417'
blogger_filename: '/2014/02/20140207-journal-fri.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?user_id=darrellwolfe&amp;version=1" target="_blank">Day 87</a>Your Sins Are Not Being Recorded<br />Hebrews 8:12<br />12For I will be merciful to their unrighteousness, and their sins and their lawless deeds I will remember no more.”</blockquote>
<br />
<blockquote class="tr_bq">
God is showing you that He does not record your sins or failures today. Instead, He records your faith confessions and deeds done in response to what His Son has done for you. Every time you sin, every time you waver in your faith, God does not record it. But every time you believe Him and respond in faith, He records it! That should not make you want to sin more. It should free you to love God more! Joseph Prince</blockquote>
<h4>
Thankful:</h4>
I'm thankful for the Job Interview. It gave me hope that there is more out there. If for any reason this doesn't work out I will keep searching.<br />
<br />
<h4>
Feeling:</h4>
Nervous. Regretful. I did it again. I WANT to keep my big mouth shut about a new job and not tell anyone, even my own Mom and Dad what I'm doing until it's done, but I keep broadcasting to the world. My nature is to simply tell everyone I come in contact with everything that's on my mind or going on in my life right then and there. I need to work on that, because some things need to be kept quiet. Apple demonstrated this over the years. Better to tell people what you are doing or what you've done, but NOT what you are going to do.<br />
<br />
Now I'm nervous because I talked so much. What if the job by AAA isn't offered? They can't offer to everyone they interviewed. I've had jobs not offered, told everyone it looked like I would get it, then I have to answer 20 questions about it over and over. NEXT time something big is coming... SAY NOTHING!<br />
<br />
Maybe I can do this by practicing on smaller things. Not tell people what I'll have for lunch... or something? Maybe I could just practice by resisting the urge to share anything past/present/future that I would otherwise want to say. This would not only avoid this situation in the future it would make me a better conversationalist. Let the other person do 80% of the talking.<br />
<h4>
What's Up?</h4>
Kind of hit this already. So let me just say IT SNOWED yesterday! Real powder snow, not that ice junk that wishes it was snow.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />