---
title: '2014/04/25 Journal The Kingdom Of God, INSIDE... and other stuff.'
date: '2014-04-25T13:07:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4365490371183889018'
blogger_filename: '/2014/04/20140425-journal-kingdom-of-god-inside.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
The Bible Study</h4>
<br />
COME:<br />
<blockquote class="tr_bq">
<span style="font-family: Georgia, Times New Roman, serif;">Luke 17<br /><span class="verse v20" data-usfm="LUK.17.20" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px 0px 0px 3px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">20</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">And when he was demanded of the Pharisees, when the kingdom of God should come, he answered them and said,&nbsp;</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; margin: 0px; padding: 0px;">The kingdom of God cometh not with observation:</span></span></span><br /><span class="verse v21 focused" data-usfm="LUK.17.21" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #444444; line-height: 2em; margin: 0px 0px 0px 3px; padding: 0px; text-indent: 1em;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">21</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">&nbsp;</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; margin: 0px; padding: 0px;">Neither shall they say, Lo here! or, lo there! for, behold, the kingdom of God is within you.</span></span></span></span></blockquote>
<br />
JP Devo<br />
<blockquote class="tr_bq">
<br /><span style="background-color: white; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px;">Remember the little boy’s five loaves and two fish? What did Jesus do when these were placed in His hands? Did He say, “What do you expect Me to do with so little?” No, His eyes were not on the natural, the visible, the lack. His eyes were on the kingdom of God where there is always abundance. So in His hands, the little boy’s lunch was multiplied, and 5,000 men, not counting women and children, were fed that day! (John 6:1–13)&nbsp;</span><br /><br /><span style="background-color: white; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px;">This means that the kingdom of God is not some physical place. It is within you and it is where the abundance of resources is. So if you want to experience abundance in your life, be conscious first of the abundance inside you. Then, what is inside you will become a reality on the outside.</span><br /><br /><br /><span style="background-color: white; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; line-height: 21.600000381469727px;"><b><span style="font-size: large;">Beloved, God doesn’t want you to be conscious of the lack you see outside you. He wants you to be conscious of the abundance within you because His kingdom is within you!&nbsp;</span></b></span></blockquote>
<br />
<br />
HEAR:<br />
<br />
<br />
That's it... isn't it. I've been lack or scarcity minded. When I walk into a room all I see is what could be different, what should be different, what isn't right. I see the things that are NOT working.<br />
<br />
At a certain level this is a God given gift. When you are able to see how the system isn't working you can fix it.<br />
<br />
Unless you have not the authority or power to fix it. Then you just see what is broken and can't do anything about it and you become frustrated! And angry, and bitter!<br />
<br />
Jesus managed to have one without the other. He saw life for what it was, not JUST the broken parts but the good parts too. I know he saw the broken because he said things to Pharisees like: "Hypocrites! Vipers!"<br />
<br />
At the same time you never see him scorn the sinner, or even the Church goer this way, only the leaders that refused to be teachable and humble before God. He expected ignorant people to be ignorant, and sinners to sin, and lay people to be what they had been taught to be.<br />
<br />
He came to fix those things, in those that would let him.<br />
<br />
Hey Blogger:<br />
<br />
He also didn't try to go get a crowd. Or find people to follow him. He did go grab some high level leadership and start training them. Then he just preached where the people were, and crowds started to follow. He employed two tactics.<br />
<br />
Won By One. He reached out to individuals. He was available. He stayed longer after the message to touch and heal. He stopped his life for those who would call to him by name. A woman who touched his clothes. A begger who called to him. A leader who humbled himself and came to him.<br />
<br />
Mass Messaging. He preached where the people were.<br />
<br />
<ul>
<li>He started in the Churches.</li>
<li>Then cities.</li>
<li>Then too many crowds forced him to find larger venues.</li>
<li>Eventually, for Jesus it was a hillside, usually.&nbsp;</li>
</ul>
<div>
So his venues grew as his audience did. Blog. You Tube. Public Speaking at Churches and other venues.&nbsp;</div>
<div>
<br /></div>
<div>
Hmm...</div>
<br />
<div>
<br /></div>
Anyway... the blogging part wasn't the point of this, but that is interesting.<br />
<br />
It all starts with a life of being Kingdom Inside Minded. Whether I'm to be a good Husband, Father, Friend, Mentor, Blogger, or anything else, it's to be as I stay Kingdom Inside Minded.<br />
<br />
SO, today... let's do a "Scavenger Hunt". Let's go look under rocks (all the people and situations I find myself in today), and hunt for signs that the Kingdom of God has been there, and see if it's a place I can deposit a small bit of the Kingdom of God myself!<br />
<br />
<h4>
The Journal:</h4>
<br />
As to the rest of life. I cut my hair for the first time in months last night. I cut it too short, out of habit. But it's longer than I used to, and I used some new techniques.<br />
<br />
I used this video.<br />
<br />
<a href="https://www.youtube.com/watch?v=HTHH5xvQZyc" target="_blank">https://www.youtube.com/watch?v=HTHH5xvQZyc</a><br />
<br />
And this one.<br />
<br />
<a href="https://www.youtube.com/watch?v=pht0v-HGBZs" target="_blank">https://www.youtube.com/watch?v=pht0v-HGBZs</a><br />
<br />
It was pretty cool.<br />
<br />
I'm headed to work! OFFICIALLY, on my count down to a new position!<br />
<br />
I accepted the position at Dealer Services and thus turns a new chapter!<br />
<br />
<br />
Garden is coming along.<br />
<br />
I had great sex two nights ago.<br />
<br />
I still forgot completely about waking up early enough for the Men's Meeting. I need to set an Alarm Thurs night to put it on my mind.<br />
<br />
I also need to email Jack about a meeting place again.<br />
<br />
Signing off, DW<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />