---
title: '2014/06/02 Monday Journal'
date: '2014-06-02T12:07:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4826345688337351014'
blogger_filename: '/2014/06/20140602-monday-journal.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<br />
<br />
<blockquote class="tr_bq">
<i><b>Rejoice in the Lord, O you [uncompromisingly] righteous [you upright, in right standing with God]; for praise is becoming and appropriate for those who are upright in heart.
– Psalm 33:1</b></i></blockquote>
<blockquote class="tr_bq">
<i>Praise. According to the Word of God, that's the most appropriate, becoming, thing that you as a believer can do." <a href="http://www.kcm.org/about/index.php?p=daily_devotional" target="_blank">Gloria Copeland FaithToFaith 06/02//14</a></i></blockquote>
<br />
<br />
<blockquote class="tr_bq">
<i><a href="http://www.biblestudytools.com/isaiah/passage.aspx?q=isaiah+6:1-8" target="_blank">Isaiah 6:1-8 (New International Version)</a><br />
</i><i><br /></i><i>Isaiah's Commission</i><i><br /></i><i>1 In the year that King Uzziah died, I saw the Lord seated on a throne, high and exalted, and the train of his robe filled the temple. 2 Above him were seraphs, each with six wings: With two wings they covered their faces, with two they covered their feet, and with two they were flying. 3 And they were calling to one another: "Holy, holy, holy is the LORD Almighty; the whole earth is full of his glory." 4 At the sound of their voices the doorposts and thresholds shook and the temple was filled with smoke. 5 "Woe to me!" I cried. "I am ruined! For I am a man of unclean lips, and I live among a people of unclean lips, and my eyes have seen the King, the LORD Almighty." 6 Then one of the seraphs flew to me with a live coal in his hand, which he had taken with tongs from the altar. 7 With it he touched my mouth and said, "See, this has touched your lips; your guilt is taken away and your sin atoned for." 8 Then I heard the voice of the Lord saying, "Whom shall I send? And who will go for us?" And I said, "Here am I. Send me!"</i></blockquote>
<br />
<br />
<blockquote class="tr_bq">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=202&amp;id=28-joseph-prince&amp;version=1" target="_blank">Romans 8</a>&nbsp;(JP Devo)&nbsp;</blockquote>
<blockquote class="tr_bq">
<i>30Moreover whom he did predestinate, them he also called: and whom he called, them he also justified: and whom he justified, them he also glorified. 31What shall we then say to these things? If God be for us, who can be against us? 32He that spared not his own Son, but delivered him up for us all, how shall he not with him also freely give us all things? 33Who shall lay any thing to the charge of God's elect? It is God that justifieth. 34Who is he that condemneth? It is Christ that died, yea rather, that is risen again, who is even at the right hand of God, who also maketh intercession for us. 35Who shall separate us from the love of Christ? shall tribulation, or distress, or persecution, or famine, or nakedness, or peril, or sword? 36As it is written, For thy sake we are killed all the day long; we are accounted as sheep for the slaughter. 37Nay, in all these things we are more than conquerors through him that loved us. 38For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come, 39Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.</i></blockquote>
<blockquote class="tr_bq">
<span style="background-color: white; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px;">Can famine or recession stop God’s love from providing for His beloved? No! So don’t think to yourself, “I must provide for my family. If I don’t, who is going to take care of them? How are they going to survive?” God wants you to know that His love will continue to provide abundantly for you and your family.</span></blockquote>
<br />
<br />
I have a God who loves me completely. As I wake up to that fact, and get it lodged in my heart I will not only praise Him spontaneously and enthusiastically, I will trust Him completely. How could God give his own son and withhold any other good thing? He can't! He loves me, more than I love myself or anyone around me. He is enamored with me. I need to mediate on these things today.<br />
<br />
<br />
The garden was on pause for a while, but we planted some things yesterday, I cleaned up the garden outside my window and planted the last missing pieces (Asparagus). I need to take a picture.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />