---
title: 'Journal - July 18, 2014 - Sampson and Sceva tied to Faith and Hearing God.'
date: '2014-07-18T11:33:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '822544265427934237'
blogger_filename: '/2014/07/journal-july-18-2014-sampson-and-sceva.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
</h4>
<br />
<h3>
Daily Routine:</h3>
<h4>
BE STILL: Just Listen, write down what He tells you.&nbsp;</h4>
<div>
<b>What did God say today?</b></div>
<br />
<b>God Said:&nbsp;</b><br />
<br />
I need you to get up earlier, which means going to bed earlier, so that you are not rushing through life. Rushing your time with me.<br />
<br />
<br />
<h4>
PRAYER: This is the time I do some talking, but still listening also.</h4>
<div>
<a href="http://biblehub.com/greek/1162.htm" target="_blank">Entreaties </a>(specific felt need),&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/4335.htm" target="_blank">Prayers </a>(exchange of desires/wishes),&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/1783.htm" target="_blank">Petitions/Intersessions</a>
 (Intersection of heaven and earth, hit the bullseye, request something 
specific of a King. Technical/Civil term: VERY specific requests that 
meet an exact need!).&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/2169.htm" target="_blank">Thanksgivings</a> ( Lit: giving thanks for God's grace! Gratitude, Thankfulness)</div>
<div>
These are to be made on behalf of:&nbsp;</div>
<div>
<ul>
<li><b>FIRST </b>for <b>all people</b>, then <b>Kings</b>, <b>Leaders</b>, those in <b>Authority</b>, then you would be included in all men, so your family, kin folk, etc.&nbsp;</li>
<li><b>God desires all men to:</b> Be saved and come to the knowledge of the Truth.</li>
</ul>
</div>
<i><a href="http://biblehub.com/context/1_timothy/2-1.htm" target="_blank"><b>1 Timothy 2</b></a></i><br />
<div>
<i>1
 First of all, then, I urge that entreaties and prayers, petitions and 
thanksgivings, be made on behalf of all men, 2 for kings and all who are
 in authority, so that we may lead a tranquil and quiet life in all 
godliness and dignity. 3 This is good and acceptable in the sight of God
 our Savior, 4 who desires all men to be saved and to come to the 
knowledge of the truth. 5 For there is one God, and one mediator also 
between God and men, the man Christ Jesus, 6 who gave Himself as a 
ransom for all, the testimony given at the proper time. 7 For this I was
 appointed a preacher and an apostle (I am telling the truth, I am not 
lying) as a teacher of the Gentiles in faith and truth. 8 Therefore I 
want the men in every place to pray, lifting up holy hands, without 
wrath and dissension.</i></div>
<i><br /></i>
<b>Did anything else come up in prayer that should be notated?&nbsp;</b><br />
<i><br /></i>
<i>In Car.... </i><i><br /></i>
<i><br /></i>
<br />
<h4>
BIBLE: Instead of a bible devotional, I'm going to do a bible study.&nbsp;</h4>
<div>
Take one of Kenneth's study notes from the front of my bible and do those.</div>
<div>
JOURNAL entry will include all of the above, and anything else on my mind at the time. Take a moment to jot down:</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<blockquote class="tr_bq">
<i><br /></i>
<i><a href="http://www.biblestudytools.com/nkjv/acts/passage.aspx?q=acts+19:9-19" target="_blank">Acts 19:9-19</a></i><br />
<i><br /></i>
<i>11
 Now God worked unusual miracles by the hands of Paul, 12 so that even 
handkerchiefs or aprons were brought from his body to the sick, and the 
diseases left them and the evil spirits went out of them. 13 Then some 
of the itinerant Jewish exorcists took it upon themselves to call the 
name of the Lord Jesus over those who had evil spirits, saying, "We 
exorcise you by the Jesus whom Paul preaches." 14 Also there were seven 
sons of Sceva, a Jewish chief priest, who did so. <b>15 And the evil spirit answered and said, "Jesus I know, and Paul I know; but who are you?" </b>16
 Then the man in whom the evil spirit was leaped on them, overpowered 
them, and prevailed against them, so that they fled out of that house 
naked and wounded. 17 This became known both to all Jews and Greeks 
dwelling in Ephesus; and fear fell on them all, and the name of the Lord
 Jesus was magnified. 18 And many who had believed came confessing and 
telling their deeds. 19 Also, many of those who had practiced magic 
brought their books together and burned them in the sight of all. And 
they counted up the value of them, and it totaled fifty thousand pieces 
of silver. 
</i></blockquote>
<br />
Jesus I <a href="http://www.biblestudytools.com/lexicons/greek/kjv/ginosko.html" target="_blank">Know</a> Ginosko -(Intimate - Like Sex)<br />
<br />
Paul I <a href="http://www.biblestudytools.com/lexicons/greek/kjv/epistamai.html" target="_blank">know</a>: Epistamai (Acquainted with, has my attention, preoccupied my thoughts)</div>
<div>
<br /></div>
<div>
<h4>
JOURNAL: What's Up Today?&nbsp;</h4>
</div>
<br />
<b>How you are feeling:</b><br />
<div>
<br />
Other than feeling bad about getting up late, good. I'm excited about the possibility of another promotion so soon.</div>
<div>
<br />
<div>
<b>How you are believing:</b></div>
<div>
<br /></div>
<div>
I've got some doubts about actually getting that promotion, or claiming it before it happens... given my history of that not panning out more often than not. But I'm being Spirit led now. That's the difference. Claiming something because you thought you started to see it happening, and then it falls apart: that's just natural. You saw it first, claimed it, then it disappeared.<br />
<br />
Even claiming something that you thought you saw in the Word, had a vague impression about isn't really your right. The only things you have a right to claim are those things that Jesus himself has told you, through the Holy Spirit, are yours.<br />
<br />
It's like Paul vs the 7 Sons of Sceva. Demons don't flee from people who have heard, they flee from people who KNOW. All the hearing they'd done had given them the confidence to go our and do this. What they were doing was not wrong, what they were doing was not rooted in that inner-knowing. It was mental assent vs heart belief.<br />
<br />
You have no power in and of yourself. Believing with mental assent is like Sampson with no hair. Just a man who can be overcome. You need to be walking in-under the anointing to get results. To do that, you must be flowing with God, not trying to get God to flow with your agenda.<br />
<br />
It's not enough to grab the bible, find a verse that sounds like what you need and claim it. You have to get into prayer, let God LEAD you into the Word He has for you. Then when you have HEARD God (not read Him) you can have something to sink you faith into. </div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<b>What's happening in your life right now:</b></div>
<div>
<br /></div>
I'm learning about being led.<br />
<br />
I'm contemplating possible promotion.<br />
<br />
I'm in CSC training with a trainer who is... trying my patience. I need to pray for her, and find ways to serve her. She can probably sense my annoyance if I'm feeling it. I need to counter that with Holy Spirit service. <br />
<br />
DW </div>
