---
title: '2014/05/22 Journal'
date: '2014-05-22T11:48:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4934911528380348462'
blogger_filename: '/2014/05/20140522-journal.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<p>I was just reading the JP Devoted and he talked about talking to plants.</p>
<p>I just remembered when this journey began in 2003 and I talked to the plant by Mom's mailbox. It was nearly dead and within days it was thriving!&nbsp; </p>
<p>Keith Moore was talking about walking in the light you have and not violating your conscience. Even if it seems like a minor unrelated thing; if it violates your conscience you will loose confidence before God in life and prayer.</p>
<p>Everytime I think of platform ministry I feel "unworthy " and "fake" and "impostor". </p>
<p>I thought for a while I could just bind the devil and it would go away. But now I see where I'm not walking in the light I have, therefore darkness, therefore guilty conscience,&nbsp; therefore no confidence.</p>
<p>I need go back and do the things I did in the beginning. </p>
