---
title: '2014/03/31 Journal Mon Thank God For Bean Dip!'
date: '2014-03-31T13:03:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4373095245735329589'
blogger_filename: '/2014/03/20140331-journal-mon-thank-god-for-bean.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
COME:<br />
<br />
<blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">Thank Your Way To Greater Blessings</a>&nbsp;Day 139<br />Luke 17:15<br />15And one of them, when he saw that he was healed, returned, and with a loud voice glorified God,<br />People who have a grateful heart are always praising God. You often hear them say, “God is good!” They know that God is the reason for every blessing they get.<br />But there are those who look to God for blessings and when they get blessed, they just go on their merry way. Their hearts are captivated by the blessings instead of the One who has blessed them.<br />**<br />Do you know that when the man came back to thank Jesus, he received the additional blessing of becoming whole? Jesus said to him, “Arise, go thy way: thy faith hath made thee whole.” (Luke 17:19, KJV) He was not just cleansed of leprosy, he got his missing fingers and toes back!<br />My friend, when your heart is thankful toward God, you position yourself for even greater blessings!</blockquote>
<div style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;">
</div>
<div style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;">
</div>
<div style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;">
<br /></div>
<br />
<br />
<br />
<br />
HERE:<br />
<br />
I've been thinking about gratitude a lot lately. Connor and I are similar here. Always focused on what we want but don't have (even if we didn't know we wanted it until 2 minutes ago), never very grateful for what we have.<br />
<br />
He must have learned that from me, picked it up spiritually, I never "Taught" it to him in my words, but he must have picked up my attitude towards things in life.<br />
<br />
I need to be grateful for everything, daily.<br />
<br />
<br />
DO:<br />
<br />
<br />
Today I will try to see just how many things I can thank God for! I'll go into over-do-it mode to help the reconditioning of my soul.<br />
<br />
<h4>
Thankful:</h4>
<br />
I'm not going to do that all in writing, because I have to go to work now. I'm thankful for this reminder to be thankful.<br />
<br />
<br />
<br />
<h4>
Feeling:</h4>
<br />
Feeling: Expectation start to rise in me again. Some fear that TD Ameritrade hasn't called yet. Casting Care over to God on that issue. He'll have to care because I refuse to!<br />
<br />
<br />
<h4>
What's Up?</h4>
I'm taking a healthy bean dip to work today. Hopefully people like it.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />