---
title: 'Phoenix, AZ?'
date: '2014-07-19T04:06:00.0050000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4945319638291663887'
blogger_filename: '/2014/07/phoenix-az.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Life Events'
  - 'Feelings'
---

<br />
So, some time ago I think I heard the Lord ask me:<br />
<br />
"Would you be willing to help a pastor build a Church? Would you serve him to help him accomplish his vision?"<br />
<br />
I said yes. Nothing has come of that in years. Maybe it's because I haven't been looking, or maybe it's the timing. Or maybe I didn't hear God? I don't know. SO... I did like Mary and pondered these things in my heart.<br />
<br />
---- Flash Forward----<br />
<br />
Within the last year I heard Gateway had a location in Az... near Phoenix. That's interesting... but it sort of sat in the back of my heart. Maybe I'm not going to move there, but maybe I need to pray for them as part of my Church? I don't know.<br />
<br />
--- Flash Forward---<br />
<br />
<a href="http://gatewayscottsdale.tv/about-us/meet-the-team/bio/preston-morrison/" target="_blank">Pastor Preston Morrison</a> came to speak at Gateway Southlake. What a great time I had. I really enjoyed him. Even, dare I say it, maybe impressed. Maybe even drawn to him a little? <br />
<br />
Again, not that I feel called to move here... but it's interesting. He's in Scottsdale, AZ<br />
<br />
---Flash Forward---<br />
<br />
WFDS OOP is starting a second office in Phoenix AZ, and they are eventually going to need a manager over that site. Hm... If I get promoted to Analyst now, and the current Analyst is the new manager... Hmmm.... ? Not that I feel called to move here... but it's interesting.<br />
<br />
<a href="https://www.wellsfargodealerservices.com/Dealers/dealerservice/autofinancelocations/rockymountaindivision/default.asp" target="_blank"><b>Division Headquarters</b></a><br /><a href="https://www.google.com/maps/dir/100+W+Washington+St,+Phoenix,+AZ+85003/15020+N+Hayden+Rd,+Scottsdale,+AZ+85260/@33.5607488,-112.1242039,11z/data=!3m1!4b1!4m13!4m12!1m5!1m1!1s0x872b122166d828e3:0x592d5aad3ba9a2a8!2m2!1d-112.0756209!2d33.4486486!1m5!1m1!1s0x872b744ba957657f:0xbf167ab21614454d!2m2!1d-111.9073927!2d33.6216372" target="_blank">100 West Washington Street, 11th Floor</a><br />Phoenix, AZ 85003<br />
<br />
---Observation---<br />
<br />
This is like 30 minutes from Gateway Scottsdale. Not that I'm looking to move here, but it's interesting.<br />
<br />
---Thoughts/Feelings---<br />
<br />
Would I be willing to move here if God said Go. Yes and No. I'm really not keen to moving to another desert with 100+ summers. I've seen enough cactus and palm trees for one lifetime. <br />
<br />
Yet, something about it feels very familiar, having grown up in Indio, CA.... which, btw, would only be 3.5 hours away. Housing is similarly priced.<br />
<br />
It's an interesting thought to ponder. But I'll let Flavia tell me God told her something about it before I bring it up.<br />
<br />
DW