---
title: '2014/03/06 Journal Thu - Going to Test for QT'
date: '2014-03-06T14:54:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6291425164799403982'
blogger_filename: '/2014/03/vod-day-114-start-using-your-measure-of.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12.222222328186035px; line-height: 24.000001907348633px; margin-bottom: 20px; padding: 0px;">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?user_id=darrellwolfe" target="_blank">Day 114</a><br />
Start Using Your Measure Of Faith<br />
Romans 12:3<br />
3… God has dealt to each one a measure of faith.<br />
As children of God, we should never say, “I don’t have any faith.” To say this is to say that God is a liar because His Word already tells us that “God has dealt to each one a measure of faith”.<br />
<br />
Beloved, you have been given a measure of faith. Start using it, believing that it is this measure of your faith that causes you to draw from the inexhaustible power of a faithful and loving God!<br />
Thought For The Day<br />
Your measure of faith grows when you feed and use it.</blockquote>
<br />
<br />
<blockquote class="tr_bq">
<span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 16.666667938232422px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px; text-indent: 17px;"><a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=114&amp;user_id=darrellwolfe&amp;version=1" target="_blank">Romans </a>12:3</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 16.666667938232422px; line-height: 34px; margin: 0px; padding: 0px; text-indent: 17px;">For I say, through the grace given unto me, to every man that is among you, not to think of himself more highly than he ought to think; but to think soberly, according as God hath dealt to every man the measure of faith.</span></blockquote>
<br />
<br />
How can I start to use my faith today? I had a migraine on Monday. I could use my faith to be rid of headaches. But the catch here is not to prevent the headache, although that is the ultimate goal, it is to address the headache with faith when it comes, instead of medicine. Take the Word as medicine.<br />
<br />
Besides, I've been taking so much medicine that my AST levels are elevated. It needs to stop.<br />
<br />
<h4>
Thankful:</h4>
I'm thankful for the Word of God. God has a plan for my life and I am going to live it. Discovering that plan one action at a time.<br />
<h4>
Feeling:</h4>
Feeling... weary of applications. But I know my God will come through for me. He always has in the past.<br />
<br />
<h4>
What's Up?</h4>
I got a voice mail to go in today to take a test for the QT position. I do remember that there was a man who told me he'd love to have me come work for him, he was a district manager for QT, and he made a LOT of money (I took his credit application), but he worked in a different state.<br />
<br />
I'm going to go. I'm not really sure why, other than I don't want to do what I'm doing and maybe the change of pace will be good for me. What I really want is to kick these websites up and running. But... that may take a while to build traffic.<br />
<br />
I need to implement the strategy of taking time each week to participate in forums or comments on blogs. I figure I'll comment on Michael Hyatt, Pat Flynn, and Jeff Goins Blog. Also I will find a forum, probably at Yahoo Answers because they always manage to come up high on search lists for google, which means more exposure and a better use of my time. I'll jump in anywhere else He points out.<br />
<br />
That's it for today. I'd better get going.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />