---
title: '2014-01-04 Journal Saturday'
date: '2014-01-04T14:56:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4154530082605915936'
blogger_filename: '/2014/01/2014-01-04-journal-saturday.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<span style="background-color: #f9faf5; color: #707070; font-family: 'Helvetica Neue', Helvetica, Arial, 'Microsoft YaHei', sans-serif; font-size: 13px; line-height: 18px;">Thus&nbsp;it&nbsp;Begins&nbsp;</span><br />
<br style="color: #707070; font-family: 'Helvetica Neue', Helvetica, Arial, 'Microsoft YaHei', sans-serif; font-size: 13px; line-height: 18px;" />
<span style="background-color: #f9faf5; color: #707070; font-family: 'Helvetica Neue', Helvetica, Arial, 'Microsoft YaHei', sans-serif; font-size: 13px; line-height: 18px;">I've&nbsp;had&nbsp;journals&nbsp;in&nbsp;the&nbsp;past.&nbsp;I&nbsp;was&nbsp;always&nbsp;inconsistent.&nbsp;I'd&nbsp;like&nbsp;to&nbsp;try&nbsp;this&nbsp;out&nbsp;and&nbsp;see&nbsp;how&nbsp;it&nbsp;goes.&nbsp;My&nbsp;plan&nbsp;is&nbsp;to&nbsp;write&nbsp;as&nbsp;often&nbsp;as&nbsp;I&nbsp;can.&nbsp;Daily,&nbsp;or&nbsp;not.&nbsp;</span><br />
<br />
<span style="background-color: #f9faf5; color: #707070; font-family: 'Helvetica Neue', Helvetica, Arial, 'Microsoft YaHei', sans-serif; font-size: 13px; line-height: 18px;">Tomorrow&nbsp;Flavia&nbsp;and&nbsp;I&nbsp;will&nbsp;see&nbsp;a&nbsp;marriage&nbsp;counselor&nbsp;to&nbsp;on&nbsp;a&nbsp;road&nbsp;to&nbsp;recovery&nbsp;that&nbsp;began&nbsp;last&nbsp;Sunday.&nbsp;Pastor&nbsp;Robert's&nbsp;message&nbsp;opened&nbsp;us&nbsp;up&nbsp;to&nbsp;talking&nbsp;about&nbsp;things&nbsp;we&nbsp;hadn't&nbsp;talked&nbsp;about&nbsp;in&nbsp;our&nbsp;whole&nbsp;marriage.&nbsp;We&nbsp;aired&nbsp;some&nbsp;things&nbsp;that&nbsp;had&nbsp;been&nbsp;weighing&nbsp;us&nbsp;down.&nbsp;We've&nbsp;had&nbsp;more&nbsp;sex&nbsp;in&nbsp;the&nbsp;last&nbsp;week&nbsp;than&nbsp;the&nbsp;past&nbsp;six&nbsp;months,&nbsp;and&nbsp;enjoyed&nbsp;it.&nbsp;</span><br />
<br />
<span style="background-color: #f9faf5; color: #707070; font-family: 'Helvetica Neue', Helvetica, Arial, 'Microsoft YaHei', sans-serif; font-size: 13px; line-height: 18px;">I'm&nbsp;feeling&nbsp;pensive&nbsp;but&nbsp;hopeful&nbsp;about&nbsp;2014.&nbsp;I&nbsp;feel&nbsp;like&nbsp;the&nbsp;winds&nbsp;of&nbsp;change&nbsp;are&nbsp;blowing&nbsp;through&nbsp;my&nbsp;marriage,&nbsp;work,&nbsp;and&nbsp;other&nbsp;projects&nbsp;I'm&nbsp;working&nbsp;on.&nbsp;I'm&nbsp;ready&nbsp;to&nbsp;focus&nbsp;on&nbsp;a&nbsp;new&nbsp;direction&nbsp;and&nbsp;intensity&nbsp;for&nbsp;my&nbsp;blogs&nbsp;and&nbsp;I&nbsp;want&nbsp;to&nbsp;write&nbsp;two&nbsp;books&nbsp;this&nbsp;year,&nbsp;one&nbsp;fiction&nbsp;and&nbsp;one&nbsp;non&nbsp;fiction.&nbsp;</span><br />
<br />
<span style="background-color: #f9faf5; color: #707070; font-family: 'Helvetica Neue', Helvetica, Arial, 'Microsoft YaHei', sans-serif; font-size: 13px; line-height: 18px;">That's&nbsp;it&nbsp;for&nbsp;my&nbsp;first&nbsp;entry...&nbsp;Maybe&nbsp;I'll&nbsp;get&nbsp;more&nbsp;organized&nbsp;in&nbsp;time.&nbsp;DW</span>