---
title: '2014/04/18 Journal Friday'
date: '2014-04-18T13:00:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '33367291564197629'
blogger_filename: '/2014/04/20140418-journal-friday.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

Well...<br />
<br />
It's five weeks and no news from TDA so I guess TDA has gone MIA.<br />
<br />
<br />
It's one week since the Dealer Services Interview and they said they'd have decisions by now. I haven't got a decline letter, but I would have thought I'd hear something by now.<br />
<br />
Flavia yelled at me last night again. I'm still not the person she thinks I'm supposed to be. Especially for the kids.<br />
<br />
Maybe this life just isn't worth it. Maybe I should short sale the house, send them off to live with JoAnn, and hit the road... live in the mountains, or... something...<br />
<br />
<br />
So now I'm going to hell, Wells Fargo Sales, and I don't know how I'm going to make it through the day.<br />
<br />
I'm mad at God for all of this. I asked to be single and stay single the rest of my life. This is all your fault.<br />
<br />
I know that's not true, but it's how it feels.<br />
<br />
Am I Job?