---
title: '2014/02/08 Journal Sat'
date: '2014-02-08T13:48:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '9105446441662068345'
blogger_filename: '/2014/02/20140208-journal-sat.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
<span style="font-family: Courier New, Courier, monospace;">John 4:32</span><span style="font-family: Courier New, Courier, monospace;">32But He said to them, “I have food to eat of which you do not know.”</span>&nbsp;</blockquote>
<blockquote class="tr_bq">
<span style="font-family: Courier New, Courier, monospace;"></span><span style="font-family: Courier New, Courier, monospace;">Heb 8:12</span><span style="font-family: Courier New, Courier, monospace;"><br /></span><span style="font-family: Courier New, Courier, monospace;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px; text-indent: 17px;">12</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; line-height: 34px; margin: 0px; padding: 0px; text-indent: 17px;">For I will be merciful to their unrighteousness, and their sins and their iniquities will I remember no more.</span></span><span style="font-family: Courier New, Courier, monospace;"><br /></span><span style="background-color: #eeedeb; color: #333333; line-height: 21.600000381469727px;"><span style="font-family: Courier New, Courier, monospace;">My friend, Jesus wants to minister to you. Don’t try to minister to yourself. That is pride and self-righteousness. The Pharisees of Jesus’ day, who felt that they did not need Him and that they could provide for themselves, were the ones who could not receive from Him. So bring to Him your needs and say, “Lord, I need to draw from You. I present my needs to You. Minister to me and meet my needs. I cannot, but You can. Thank you, Lord.”</span></span></blockquote>
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?content=1&amp;day=88&amp;user_id=darrellwolfe&amp;version=1" target="_blank">&nbsp;Joseph Prince Daily Devotional</a><br />
<br />
<h4>
Thankful:</h4>
I'm thankful for Connor David Wolfe and Preston Markus Wolfe! They are trying to take my toys!<br />
<br />
I'm thankful for my Father sending money through my my Dad for Valentines!<br />
<h4>
Feeling:</h4>
Excited! Flavia's taking the Kids to see the LEGO Movie, which they've been talking about over and over... but they don't know yet. She's going to surprise them when they get there. And, IF supplies are still lasting, they get a Minifigure of Emmitt in his PJ's<br />
<h4>
What's Up?</h4>
I took nearly everything home from work last night. Two boxes. I left all my pictures and decorations and such. But ultimately, most of that is getting tossed when I leave anyway. I'll just take four things and go. Even my drawers are empty. It felt good. I don't know anything from AAA for sure, but it felt like the right thing to do, and a good act of faith?<br />
<br />
It started because Ed sat me down and told me I was going on a sales plan and was not allowed to work any more overtime. I told him, among other things, that I'll get rid of all distractions. That includes my books and library I had there.<br />
<br />
It was symbolic mostly, but I think we both know, though I haven't said... I'm done. I have to go, I've over stayed my time at WF.<br />
<br />
<br />
DW