---
title: '2014/02/19 Journal Wed'
date: '2014-02-19T13:56:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8878871313801077761'
blogger_filename: '/2014/02/20140219-journal-wed.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">Day 99</a><br />God Is Your Strength&nbsp;</blockquote>
<blockquote class="tr_bq">
Ephesians 6:10<br />10Finally, my brethren, be strong in the Lord and in the power of His might.&nbsp;</blockquote>
<blockquote class="tr_bq">
When you say, “I can manage this problem by myself, Lord,” God says, “Okay, you do it then.” But when you say, “Help me, Lord! I need You. I cannot do this on my own,” God says, “Good, I have been waiting for you to say that. You cannot, but I can. Now, watch Me!” That is how God is — He loves it when you depend on Him.<br />...<br />So when you say, “I can do something about it,” you are still relying on your human strength. But when you say to God, “I cannot, but You can,” you have just tapped into the real source of your strength — Jesus. And as you rest in His strength, you will see His power manifesting in your life!&nbsp;</blockquote>
<blockquote class="tr_bq">
Thought For The Day<br />As you rest in God’s strength, you will see His power manifesting in your life!</blockquote>
<br />
<h4>
Thankful:</h4>
I cannot... but you can! Thank you Father for YOUR strength! I cannot fall in love with these people I serve, but you can fall in love with them in me. I cannot get a new job with better pay, but you can for me. Thank you Father for YOUR provision. You are my source.<br />
<h4>
Feeling:</h4>
Like I'm not sure if I'm wasting my time. I hate wasting time. I hate looking back and knowing my time was wasted. I don't want to go to an interview if the Job isn't mine. I don't want to go to an interview and get offered the job if I'm just going to turn it down. I don't know if this new position they are interviewing me for is right or not...<br />
<h4>
What's Up?</h4>
I have ANOTHER interview with AAA today. Something told me the last one wouldn't work out. This new one is a mix of in person and outbound calls. I've been telling myself for months that my current job is at least as bad or worse than outbound calls. The clients/leads from this AAA list have got to be better than the people I talk to at WF.<br />
<br />
My current client base is almost entirely comprised of the "bottom of the barrel" in terms of customer base. The AAA client base would be a mix of people who are financially like Flavia and I, strapped but making it and people like my Mom who have some extra money, and people like Jack who have a lot of money due to good financial planning, at least during his working years.<br />
<br />
I'll go to the interview with questions to ask. We shall see.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />