---
title: '2014/01/31 Journal Fri'
date: '2014-01-31T13:07:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '643003651971685681'
blogger_filename: '/2014/01/20140131-journal-fri.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
1 John 4:10<br />10In this is love, not that we loved God, but that He loved us and sent His Son to be the propitiation for our sins. &nbsp;</blockquote>
&nbsp;Pastor Prince Devotional: <a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?user_id=darrellwolfe" target="_blank">Day 80</a><br />
<blockquote class="tr_bq">
<span style="background-color: #eeedeb; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px;">Beloved, God has seen you trying your best to love Him. And because He loves you, He wants you to sit down and be still, and let Him love you instead. He wants to love you with all that He is and all that He has. He loves you unconditionally regardless of who you are or what you have done because His love is not dependent on you but on Himself. He will never stop loving you.</span></blockquote>
<br />
<h4>
Thankful:</h4>
Today I am thankful for Jesus who loves me, despite my unbelief. I am thankful for the great Daddy/Son day I had with the boys last night at McD's. I am thankful for Wells Fargo, it's not a perfect job, but it has provided a certain lifestyle and work-life balance that I've come to enjoy.<br />
<h4>
What's Up?</h4>
AAA phone screen interview came through. She called while I was in route and I decided just to do it then rather than take a block of time and have them not call again. The Position isn't exactly what I thought. It's not a salary plus bonuses deal. They do have a Min Guarantee of $40,000. But it's a commission/draw situation. So you earn commission and when you keep whatever you earn over and above your draw. Obviously that would mean you need to be exceeding your draw, because they probably don't want people on staff who don't. You are getting a few inbound calls from other partners, but 50% of your time is spent doing outbound to leads, prospects, and follow ups on quotes. I'd be selling AAA memberships and cross selling Insurance products. "Fast Paced" was a descriptor they chose.<br />
<br />
<b>Pros:&nbsp;</b><br />
It's a much higher Min Pay and bonus potential is much higher. They said that most make $52K their first year. Job has benefits and the typical corporate stuff in that sense.<br />
<br />
I would be forced to learn some of the skills that I need as an entrepreneur: Take ownership over my business, follow up on leads, push through fear of rejection. Could be a great stepping stone into being a business owner.<br />
<br />
3 months training... I like learning new stuff!<br />
<br />
I already believe in their product, much more than I do WF's!<br />
<br />
<b><br /></b>
<b>Cons:</b><br />
Cold Calls and Outbound are part of the job. Historically this has been very bad for me and frozen me in my tracks.<br />
<br />
Out of pocket expense for the Insurance License Test. But it's reimbursed if you pass.<br />
<br />
I'm scared that I'd get inside and believe in their product less, I'd have to make a commitment to being open minded.<br />
<br />
I'm committed to work there AT LEAST a year or I'll owe them a ton of money to pay back for training. <br />
<br />
I start all over for benefits and vesting into the 401K and all that.<br />
<br />
No shift Differential for working nights<br />
<br />
<h4>
Feeling:</h4>
Nervous? I've been here before... I don't want to make the wrong decision... again. It made me feel increasingly edgy on the phone. It was a lot of the things I've turned down in the past. I've been approached to do Insurance for a long time by other companies. I must say though, this is the easiest version I've ever heard of, and it's call center so that's nice.<br />
<br />
I'd probably work Tue-Sat 10-7...<br />
<br />
The only other readily available position I have in front of me is scheduling. Potentially making for $40K as well. No OT, No Bonuses, No Shift Diff. Flat pay. Flat schedule. Data Entry. Math. No Sales. Ultimately less pay but more the type of position I could feel relaxed in, then I can pursue my mental energy on the blogs. Less pay, better job for me. Still with same company, same benefits, same tenure, etc...<br />
<br />
I'll probably go to the interview for AAA on Wed to investigate it more... what if I say no and Wells Fargo doesn't call me for the Schedule position, or doesn't offer it to me?<br />
<br />
I REALLY need to make more money, and I don't want to do it in WF Sales anymore!<br />
<br />
Maybe that's a clue... I don't like sales, sales pressure, I'm not a closer... DW<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />