---
title: '2014/03/19 Missed a few days.'
date: '2014-03-19T15:10:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7401185858510872373'
blogger_filename: '/2014/03/20140319-missed-few-days.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
Quiet Time</h4>
<br />
You can't water down your message and be effective. But you can deliver it in such a way that it will be heard and bring value to them.<br />
<br />
<br />
<h4>
VOD:</h4>
COME:<br />
<br />
<br />
<blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=127&amp;user_id=darrellwolfe&amp;version=1" target="_blank">Day 127</a><br />The Mind Of Christ Doesn’t Grow Old<br />1 Corinthians 2:16<br />16... we have the mind of Christ.<br />The power of life and death is in your tongue. (Proverbs 18:21) So use your tongue for life. Don’t sit around saying, “I am getting old and forgetful.” Say, “I have the mind of Christ. My mind is sharp and quick because it is the mind of Christ!” Believe it, confess it, and see your thinking and memory live up to it!<br />Thought For The Day<br />You have the mind of Christ that is not old, slow or forgetful!</blockquote>
<br />
<blockquote class="tr_bq" style="background-color: white; font-family: Arial, Helvetica, sans-serif; margin-top: 15px; padding: 0px;">
<a href="http://e.kcm.org/HM?a=ENX7CqkTRT6y8SA9MKJrrP_nGHxKL9KSpvcStGb5lw8W0bBhOG5mpqVsje_Hhe-jNFGd" target="_blank">Faith To Faith</a><br /><span style="background-color: white; color: #666666; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">Leave no room or foothold for the devil give no opportunity to him. - Ephesians 4:27</span><span style="background-color: transparent;">&nbsp;</span></blockquote>
<blockquote class="tr_bq" style="background-color: white; font-family: Arial, Helvetica, sans-serif; margin-top: 15px; padding: 0px;">
<span style="background-color: white; color: #666666; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"></span>First, you must make the Word of God the final authority in your life. Line up your thinking with whatever the Word says.<span style="background-color: transparent;">&nbsp;</span></blockquote>
<blockquote class="tr_bq" style="background-color: white; font-family: Arial, Helvetica, sans-serif; margin-top: 15px; padding: 0px;">
Next, you must decide to live your life by faith in what God has said. The Bible says, "Faith comes by hearing, and hearing by the Word of God."<span style="background-color: transparent;">&nbsp;</span></blockquote>
<blockquote class="tr_bq" style="background-color: white; font-family: Arial, Helvetica, sans-serif; margin-top: 15px; padding: 0px;">
Finally, you must decide to live by the love of God because faith works by love. Without love, your faith won't function. Without the Word, you can't have faith. So don't try to make one of these decisions without the other two. You need to make all three of them. This lifestyle of the Word, faith and love keeps you in a place of resistance to the devil!</blockquote>
<br />
<br />
HERE:<br />
<br />
I've spent almost all my time digesting bloggers and success thinkers and TED Talks this last few weeks. I've spent almost no time in the Word.<br />
<br />
That may be why I'm feeling irritated and slow. And fighting old temptations. I've been lacking my Love Walk. Calling people "Idiots" after they hang up at work. I need to prioritize my mornings and days.<br />
<br />
What's REALLY important?<br />
<br />
Is NOT wanting to hear the Word Preached a Red Flag? Yes!<br />
<br />
<br />
DO:<br />
<br />
I'm going to get up and read the Word Today.<br />
<br />
<h4>
Thankful:</h4>
I'm thankful for Mandy at Work, she helped me with some skills I needed to survive a few weeks longer in sales, even bring my numbers back up.<br />
<br />
<h4>
Feeling:</h4>
Overdue to leave WF. I had a headache nearly every day there, or just thinking about being there. I cannot stand to see people mistreated. But what hurts/drains my emotional state is when I have to talk to someone who doesn't know why they've been pushed on me, and I'm supposed to over come that with "It's your lucky day mr/mrs Customer... You may not have known why you were transfered to me but I'm here to save you time and money..." or some other such garbage as that.<br />
<br />
It's all so plastic and 1990's used car salesman.<br />
<br />
It hurts just thinking about it. I've decided I don't ever want to talk to someone who doesn't want to talk to me again. You don't want to talk... have a great day, Bye! You want to argue... have a great day, Bye!<br />
<br />
This "Salesy" over come objections, get them to stay on your phone. It's so ridiculous. The worst part is it's not needed. If our service dept did what's right for the customer, it would never happen.<br />
<br />
So sad to see a company go down the drain like this and then have leadership say that this is our model now and like it or not here's some ways to cope with it. Wells Fargo is becoming Bank of America.<br />
<br />
<h4>
What's Up?</h4>
<br />
I have an interview today at 3pm... REALLY hoping to get this job!<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />