---
title: 'September 8, 2014 | New Beggining, Fresh Start'
date: '2014-09-08T12:52:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7085332603604093615'
blogger_filename: '/2014/09/september-8-2014-new-beggining-fresh.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
</h4>
One thing I love about Jesus is that He is all about fresh starts! Not matter how many times I fail, falter, or fall... there he is again, to lift me up. #JesusIsTheBest<br />
<br />
<br />
<h3>
Daily Routine:</h3>
<h4>
BE STILL: Just Listen, write down what He tells you.&nbsp;</h4>
<div>
<b>What did God say today?</b></div>
<br />
<b>God Said:&nbsp;</b><br />
<br />
Using a tasks list will help you clear your mind and focus your thoughts. It will help you, not just be more organized, but actually accomplish more with a clearer mind.<br />
<br />
As I looked at my garden, outside my window, I heard God say: I made that, with your help. Plants can grow if seeded directly outside, but there are many things fighting against them. It would be far safer to set up a greenhouse or greenroom, plant them in tailored soil, monitor their growth, and then, when they are ready, when their roots have nearly outgrown their pot, either transplant them to a larger pot, or plant them outside where they can grow to their fullest potential.<br />
<br />
When a plant begins to outgrow it's pot, it starts to whither. It's not a sign of a sick plant, it's a sign of a plan that needs to either have it's roots trimmed, or it needs to be transplanted to a larger pot, or planted out into the world to grow. So it is with a life. #PlantedInTheMastersGarden<br />
<br />
<br />
<h4>
PRAYER: This is the time I do some talking, but still listening also.</h4>
<br />
<i><a href="http://biblehub.com/niv/1_timothy/1.htm" target="_blank"><b>1 Timothy 1</b></a></i><br />
<i>18Timothy,
 my son, I am giving you this command in keeping with the prophecies 
once made about you, so that by recalling them you may fight the battle 
well, 19holding on to faith and a good conscience, which some have 
rejected and so have suffered shipwreck with regard to the faith. 
20Among them are Hymenaeus and Alexander, whom I have handed over to 
Satan to be taught not to blaspheme.
</i><br />
<br />
<i><a href="http://biblehub.com/context/1_timothy/2-1.htm" target="_blank"><b>1 Timothy 2</b></a></i><br />
<i>1
 First of all, then, I urge that entreaties and prayers, petitions and 
thanksgivings, be made on behalf of all men, 2 for kings and all who are
 in authority, so that we may lead a tranquil and quiet life in all 
godliness and dignity. 3 This is good and acceptable in the sight of God
 our Savior, 4 who desires all men to be saved and to come to the 
knowledge of the truth. 5 For there is one God, and one mediator also 
between God and men, the man Christ Jesus, 6 who gave Himself as a 
ransom for all, the testimony given at the proper time. 7 For this I was
 appointed a preacher and an apostle (I am telling the truth, I am not 
lying) as a teacher of the Gentiles in faith and truth. 8 Therefore I 
want the men in every place to pray, lifting up holy hands, without 
wrath and dissension.</i><br />
<div>
<br />
<div>
<a href="http://biblehub.com/greek/1162.htm" target="_blank">Entreaties </a>(specific felt need),&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/4335.htm" target="_blank">Prayers </a>(exchange of desires/wishes),&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/1783.htm" target="_blank">Petitions/Intersessions</a>
 (Intersection of heaven and earth, hit the bullseye, request something 
specific of a King. Technical/Civil term: VERY specific requests that 
meet an exact need!).&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/2169.htm" target="_blank">Thanksgivings</a> ( Lit: giving thanks for God's grace! Gratitude, Thankfulness)</div>
<div>
These are to be made on behalf of:&nbsp;</div>
<div>
<ul>
<li><b>FIRST </b>for <b>all people</b>, then <b>Kings</b>, <b>Leaders</b>, those in <b>Authority</b>, then you would be included in all men, so your family, kin folk, etc.&nbsp;</li>
<li>Pray for:&nbsp; </li>
<ul>
<li><b>God desires all men to:</b> Be saved and come to the knowledge of the Truth.&nbsp;</li>
<li>Filled with the knowledge of His will through all Wisdom. <a href="http://biblehub.com/colossians/1-9.htm" target="_blank">Col 1:9</a></li>
<li>They may be given the Spirit of Wisdom and revelation in the knowledge of Him. (<a href="https://www.biblegateway.com/passage/?search=Ephesians+1%3A15-23&amp;version=NKJV" target="_blank">Eph 1:15-23</a>)</li>
<ul>
<li>Understanding Be Enlightened.</li>
<li>Know the Hope of His calling.</li>
<li>Riches through inherited Glory.</li>
<li>Exceeding greatness of His power to those who believe. </li>
</ul>
</ul>
</ul>
</div>
</div>
<i><br /></i>
<b>Did anything else come up in prayer that should be notated?&nbsp;</b><br />
<i><br /></i>
<br />
<i>Put someone in their life that can hear you with pinpoint accuracy, someone in their friends/family that they can't get rid of through firing them. </i>
<br />
<h4>
BIBLE: Instead of a bible devotional, I'm going to do a bible study.&nbsp;</h4>
<div>
Take one of Kenneth's study notes from the front of my bible and do those.</div>
<div>
JOURNAL entry will include all of the above, and anything else on my mind at the time. Take a moment to jot down:</div>
<div>
<br /></div>
<div>
<b>JP Devo: Ephesians 4:32 - Be kind to one another, tenderhearted, forgiving one another, even as God in Christ forgave you. </b></div>
<div>
<br /></div>
<div>
</div>
<div>
<h4>
JOURNAL: What's Up Today?&nbsp;</h4>
</div>
<br />
<b>How you are feeling:</b><br />
<div>
This past week, I've felt between deeply depressed, to mildly entertained. This morning I feel more at peace than I have in a long time. Maybe I under-estimated this quiet time with Jesus. I need to go to bed early, and wake up early, I feel and act better when I do.</div>
<div>
<br /></div>
<div>
<br />
<div>
<b>How you are believing:</b></div>
<div>
Need a tune up, focus on getting up early.</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<b>What's happening in your life right now:</b></div>
<div>
<br /></div>
<br />
Connor and Preston have both just walked into my office. GOOD MORNING! <br />
<br />
Possible promotion, I did the phone screen interview. We'll see how that goes.<br />
<br />
I need to learn how to communicate with the 2005. <br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
DW</div>
