---
title: 'Life Plan'
date: '2014-12-31T13:28:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6079011952794903999'
blogger_filename: '/2014/01/life-plan.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Life Plan'
---

<h3>
Life Plan Outlines</h3>
<br />
<h4>
Relationships With:</h4>
<ul>
<li>God</li>
<li>Self 1. Flavia can't accept Jesus for me. 2. I can't minister to anyone without being full first.&nbsp;</li>
<li>Flavia</li>
<li>Connor</li>
<li>Preston</li>
<li>Family - JoAnn and Rocky. Mom (Debbie). Dad (Mike). GGG. Uncles, Aunts, Cousins, Etc.&nbsp;</li>
<li>Friends</li>
<li>Career</li>
<li>Finances</li>
<li>Ministry - Church</li>
</ul>
<h4>
Outcomes</h4>
<br />
<ul>
<li>How I Want To Be Remembered.&nbsp;</li>
<li>What Outcome I Want To Have</li>
<li>I am doing... I am feeling... (From One Minute Sales Person)</li>
</ul>
<h4>
Action Plans</h4>
<br />
<ul>
<li>Account Name</li>
<li>Purpose Statement</li>
<li>Envisioned Future</li>
<li>Supporting Verse</li>
<li>Current Reality</li>
<li>Specific Commitments</li>
</ul>
<br />
<br />
<br />
<h3>
My Life Plan For 2014:</h3>
<br />
<h4>
God</h4>
<div>
<b>Purpose Statement</b><br />
To fall so passionately In Love with God, that I have no desire for other things (that is - things contrary to His plan).<br />
<br />
<b>Envisioned Future</b><br />
In Jan 2015 I'll have had an amazing year in my relationship with God.<br />
<br />
<b>Supporting Verse</b><br />
<br />
<br />
<b>Current Reality</b><br />
<br />
<br />
<b>Specific Commitments</b><br />
<br />
<br />
<br />
<br />
<h4>
Self&nbsp;</h4>
<b>Purpose Statement</b><br />
<br />
<br />
<b>Envisioned Future</b><br />
<br />
<br />
<b>Supporting Verse</b><br />
<br />
<br />
<b>Current Reality</b><br />
<br />
<br />
<b>Specific Commitments</b><br />
<br />
<br />
<br /></div>
<div>
<h4>
Flavia</h4>
<b>Purpose Statement</b><br />
<br />
<br />
<b>Envisioned Future</b><br />
<br />
<br />
<b>Supporting Verse</b><br />
<br />
<br />
<b>Current Reality</b><br />
<br />
<br />
<b>Specific Commitments</b><br />
<br />
<br />
<br /></div>
<div>
<h4>
Connor</h4>
<b>Purpose Statement</b><br />
<br />
<br />
<b>Envisioned Future</b><br />
<br />
<br />
<b>Supporting Verse</b><br />
<br />
<br />
<b>Current Reality</b><br />
<br />
<br />
<b>Specific Commitments</b><br />
<br />
<br />
<br /></div>
<div>
<h4>
Preston</h4>
<b>Purpose Statement</b><br />
<br />
<br />
<b>Envisioned Future</b><br />
<br />
<br />
<b>Supporting Verse</b><br />
<br />
<br />
<b>Current Reality</b><br />
<br />
<br />
<b>Specific Commitments</b><br />
<br />
<br />
<br /></div>
<div>
<br /></div>
<h4>
Family</h4>
<div>
<br /></div>
<div>
JoAnn and Rocky. Mom (Debbie). Dad (Mike). GGG. Uncles, Aunts, Cousins, Etc.<br />
<div>
<br />
<b>Purpose Statement</b><br />
<br />
<br />
<b>Envisioned Future</b><br />
<br />
<br />
<b>Supporting Verse</b><br />
<br />
<br />
<b>Current Reality</b><br />
<br />
<br />
<b>Specific Commitments</b><br />
<br />
<br />
<br /></div>
</div>
<div>
<h4>
Friends</h4>
<b>Purpose Statement</b><br />
<br />
<br />
<b>Envisioned Future</b><br />
<br />
<br />
<b>Supporting Verse</b><br />
<br />
<br />
<b>Current Reality</b><br />
<br />
<br />
<b>Specific Commitments</b><br />
<br />
<br />
<br /></div>
<div>
<br /></div>
<div>
<h4>
Career</h4>
<b>Purpose Statement</b><br />
<br />
<br />
<b>Envisioned Future</b><br />
<br />
<br />
<b>Supporting Verse</b><br />
<br />
<br />
<b>Current Reality</b><br />
<br />
<br />
<b>Specific Commitments</b><br />
<br />
<br />
<br /></div>
<div>
<h4>
Finances</h4>
</div>
<b>Purpose Statement</b><br />
<br />
<br />
<b>Envisioned Future</b><br />
<br />
<br />
<b>Supporting Verse</b><br />
<br />
<br />
<b>Current Reality</b><br />
<br />
<br />
<b>Specific Commitments</b><br />
<br />
<br />
<br />
<div>
<h4>
Ministry - Church</h4>
<b>Purpose Statement</b><br />
<br />
<br />
<b>Envisioned Future</b><br />
<br />
<br />
<b>Supporting Verse</b><br />
<br />
<br />
<b>Current Reality</b><br />
<br />
<br />
<b>Specific Commitments</b><br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br /></div>
