---
title: '2014/01/27 Journal Mon'
date: '2014-01-27T13:21:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8404745276799120165'
blogger_filename: '/2014/01/20140127-journal-mon.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?user_id=darrellwolfe&amp;version=1" target="_blank">Joseph Prince Devotional</a><br />
<br />
<div style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21px; margin-bottom: 20px; padding: 0px;">
Luke 10:19</div>
<div style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21px; margin-bottom: 20px; padding: 0px;">
19Behold, I give you the authority to trample on serpents and scorpions, and over all the power of the enemy, and nothing shall by any means hurt you.</div>
<br />
<h4>
Thankful:</h4>
I'm thankful for this office, and a routine I can stick to. Even if I do get up a little too late.<br />
<br />
<br />
<h4>
Feeling:</h4>
Feeling hope. Yesterday was a whirlwind of talk with Flavia about trusting God and not trusting God at the same time. We dug down and found some answers. See yesterdays posts.<br />
<br />
<h4>
What's Up?</h4>
JOSH ESTES found me on Facebook. I've been trying to find him on Facebook and other social sites for years. He's been married for ten years with two kids. Amazing!<br />
<br />
Heading to work today. But I'm going to try something... being thankful. I want to replace every opportunity that I have to say something negative with something thankful. We'll see how that goes today.<br />
<br />
DW<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />