---
title: '2014/05/27 Journal Tuesday'
date: '2014-05-27T11:04:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8700439444238793841'
blogger_filename: '/2014/05/20140527-journal-tuesday.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
COME:<br />
<br />
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=196&amp;id=28-joseph-prince&amp;version=1" target="_blank">Hebrews 11:6</a><br />
<br />
But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him.
<br />
<br />
HEAR:<br />
<br />
Do I believe that God is a rewarder of those that diligently seek Him? Or not? If I do not, then why pretend to serve Him? If I do, then why keep Him at arms distance... always afraid of what He'll say or do?<br />
<br />
There comes a time where one must stop "Playing Church". Most Christians live their entire lives partially dedicated to God at different levels. Few ever totally jump in - head under water - immersed in the things of God.<br />
<br />
I think it's time to make that jump...<br />
<br />
The question is how?<br />
<br />
Lord,<br />
<br />
How do I totally immerse into your Zoe Life? Please help me see this more clearly today? Help me release the past, my version of the past, old desires... help me put my desire for a cheeseburger down and raise my desire for your Kingdom higher... Help me become passionate about You again!<br />
<br />
Thank you, for I know if I pray according to your will, you hear me. You will grant the things I desired when I pray.<br />
<br />
Darrell<br />
<br />
**<br />
<br />
It is now 6:02 AM CT. I am going to get ready for work soon. But first I think I'll do some writing on my fiction journal.<br />
<br />
DW<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />