---
title: '2014/03/08 Journal Sat - Land Of Opportunities Await...'
date: '2014-03-08T13:59:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2707589661456147889'
blogger_filename: '/2014/03/20140308-journal-sat-land-of.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;">
<br /><a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">Day 116</a>The Good Life Without The Sweat<br />Matthew 6:26<br />26Look at the birds of the air, for they neither sow nor reap nor gather into barns; yet your heavenly Father feeds them. Are you not of more value than they?<br />Most people are of the opinion that the good life does not happen without hard work and buckets of sweat. They believe that to achieve success, you first need to have this educational certificate, that professional qualification, this particular job and that many years of hard work. I have good news for you: God has a better way.</blockquote>
<br />
<h4>
Thankful:</h4>
Today I am thankful for opportunities. There are many out there. God is brining the right one to me and me to it.<br />
<h4>
Feeling:</h4>
I'm going to trust God that HE will provide the right move for me next. I'm going to keep exploring opportunities and see what comes next.<br />
<br />
<h4>
What's Up?</h4>
Just applied to a "Sales Coordinator" position, which sounded like a glorified secretary for the sales department.<br />
<br />
I'm thinking I need to do something different with Life In Fort Worth. Somehow I need to batch process that site. I don't want to touch it more than once a month. Maybe I can take a whole day and knock out four articles with pictures and links to Yelp/Urban spoon. I also need to work on some articles that are more Navigation based. Both refresh my current ones and write new ones. Auto Registration. I should start there.<br />
<br />
DarrellWolfe.Com has been a tough one. My articles there are feeling harder to write. I think I was trying to write too heavy too often. I need to choose lighter easier topics, and address them with the same brevity as Seth Godin. Peppering in a few long ones is fine. But few people want to read a long article every time.<br />
<br />
I still don't know exactly what I want to do with it. But I want to try this niche site thing. I want to do it with credit building. We shall see.<br />
<br />
DW<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />