---
title: '2014/02/24 Journal Mon'
date: '2014-02-25T06:32:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6989255938526177424'
blogger_filename: '/2014/02/20140224-journal-mon.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<p>VOD<br>
Fear of Man<br>
Steven LeBlanc @Gatewaypeople</p>
<p>Fear of man is holding you back from your destiny.</p>
<p>Feeling<br>
...<br>
That's as far as I got this morning. Anger got the best of me and I broke a piece of my desk... I fixed it. I tried to play it off as a goofy accident but I'm sure no one believed that.</p>
<p>I hate myself for being so lazy that I still work there. Its like prison everyday.</p>
<p>I wish I knew how to cry.</p>
<p>Maybe I should look into that life insurance policy... nah. I'd just end up crippled and alive...</p>
<p>I obviously don't trust God or I wouldn't be feeling this way. </p>
<p>I guess I could say : "that's not my thought". So... that's growth in that I'm catching that now and not days from now.</p>
<p>Lord... as an act of my will despite my lack of emotional backing ... I choose to trust You. Please bring me one job, tailor fit, MORE THAN ENOUGH! Quickly ..</p>
<p>Good Night <u>DW</u></p>
