---
title: '2014.01.07 Journal Tuesday'
date: '2014-01-07T13:06:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2048175607569795086'
blogger_filename: '/2014/01/20140107-journal-tuesday.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
Thankful</h4>
I am thankful for: Jesus. Praying in tongues. my wife's ability to respond to God. Her plans for the garden. My new sex life. Gateway Church's Ministry Center, which we'll visit next week. Connor for his bold attitude; always pushing the envelope and asking questions about everything. Preston for his giggles; always discovering the wonder around him.<br />
<br />
<h4>
Feeling</h4>
I'm dreading today. I could call out of work today and take an occurrence, but I don't have a reason to, other than I don't want to go. I never want to go. I'm feeling trapped. Customers are being transfered that don't want to talk to me, or wanting to apply for things they cannot have. I'm selling products that are bad for them, like credit cards, and that makes me feel worse. I've always felt this, but now that I know Dave Ramsey it feels worse. It's long past time for me to go FROM this position. But what am I going TO?<br />
<br />
Lord, give me opportunities today to help some people. Let me be nice to the rest, not just to them, but before and after their call, and on mute.<br />
<h4>
What's happening right now</h4>
Yesterday was supposed to be the Nutcracker Reschedule but even though we bought tickets a month ago the gas and food out would have been too expensive so we didn't go. I hate poverty. I'm sick of it. Literally.<br />
<br />
I read MORE than one book last night with the kids and they really liked it. Connor fell asleep at my side, which he hasn't done in a long time. Felt good.<br />
<br />
I'm working out the details of how to build a platform. Michael Hyatt makes it look so easy by having ONE blog that he hones and hones over time and then focusing on his other tasks. I can't just write one. But maybe I could have one primary blog.<br />
<br />
<ul>
<li><b>Texas Living: Helping people Discover, Enjoy, and Navigate Fort Worth Texas Life.&nbsp;</b></li>
<ul>
<li>This one is <b>feeling </b>very defined, and I can feel it growing and blossoming every time I touch it, even though I've ignored it for some time.&nbsp;</li>
</ul>
</ul>
<ul>
<li><b>DarrellWolfe.Com:</b> What IS this? It's a place to write about things that help people. Like how to avoid overdraft fees. What's the best email client to use. How can you be a better Father. It's for the:</li>
<ul>
<li>In Debt, Distressed, and Discouraged. 1 Sam 23?</li>
</ul>
</ul>
<ul>
<li><b>Author Fun: </b>I guess this really isn't a blog at all, it's a long term project, it's a place to write fiction and play with fiction. It needs to stay that way. If people want to follow great, but I can't turn that into something where each post is tailor perfect for an audience. It's me working out the nitty gritty details of fiction writing. It's messy and needs to stay that way.&nbsp;</li>
</ul>
<br />
That's what's happening right now. DW<br />
<br />
<br />
<br />