---
title: 'Journal - July 7, 2014 - Be Led'
date: '2014-07-08T01:43:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4494699014666606148'
blogger_filename: '/2014/07/journal-july-7-2014-be-led.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

I didn't get up early as I planned. But I did spend time being quite, and praying in the car to and from work. I spent a bit of time in the Word at lunch. Today's theme was "Being Led."<br />
<br />
As I pondered the victories of men of God from Noah, Abraham, Isaac, Jacob, Joseph, Moses, Joshua, David, all the way to Jesus and beyond to the Church; I see a repeating theme I've never quite noticed. It was always there, a side note, now highlighted in my mind. They were ALL LED by God.<br />
<br />
They weren't coming up with an idea on their own and trying to run with it, getting God to bless their latest scheme/plan. In fact, in the instances we do find a scheme/plan of their own design, we see God fixing a mess, rather than orchestrating a blessing.<br />
<br />
It was men surrendered to God's plan, listening for instruction, and obeying what they heard that won the victories. Jesus said it best: I only do what I see my Father do, I only say what I hear my Father say. This isn't just some lofty ideal to strive toward, it is the only way to live daily life.<br />
<br />
The more one hears God, and obeys what they hear, they more one becomes led.<br />
<br />
Taking a look at my life scripture, <a href="http://biblehub.com/joshua/1-8.htm" target="_blank">Joshua 1:8</a>, I see it in a deeper light.<br />
<br />
<blockquote class="tr_bq">
<i><span class="versiontext" style="background-color: #fdfeff; color: #0092f2; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 14px; font-weight: 700; line-height: 20px;"><a href="http://biblehub.com/esv/joshua/1.htm" style="color: #0092f2; text-decoration: none;">English Standard Version</a></span><span style="background-color: #fdfeff; color: #001320; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 14px; line-height: 20px; text-align: justify;">This Book of the Law shall not depart from your mouth, but you shall meditate on it day and night, so that you may be careful to do according to all that is written in it. For then you will make your way prosperous, and then you will have good success.</span></i></blockquote>
<blockquote class="tr_bq">
<i><span class="versiontext" style="background-color: #fdfeff; color: #0092f2; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 14px; font-weight: 700; line-height: 20px;"><a href="http://biblehub.com/hcsb/joshua/1.htm" style="color: #0092f2; text-decoration: none;">Holman Christian Standard Bible</a></span></i><i><span style="background-color: #fdfeff; color: #001320; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 14px; line-height: 20px; text-align: justify;">This book of instruction must not depart from your mouth; you are to recite it day and night so that you may carefully observe everything written in it. For then you will prosper and succeed in whatever you do.</span>&nbsp;</i></blockquote>
<br />
What does it mean to not let something depart your mouth? It means to keep speaking about it all the time, like a raving sports fan who can speak of nothing but his favorite team.<br />
<br />
What does it mean to meditate on something day and night? Meditate: to chew, ponder, murmur, repeat to one's self, recite over and over, like an actor trying to get into his role, and internalize his lines. One should not just do this in the morning, not just at night, but starting in the morning continue throughout the day.<br />
<br />
But this is just the start. As you ponder the Word of God, you will find revelation knowledge. God will reveal to you the things you need to know and do. You must be sure to observe what God is saying/doing, then DO what God says do, and say what God says say.<br />
<br />
ONLY then, when you are responding to the things you are seeing and hearing, will you make your way prosperous, and have good success! Aha! It's back to that again!<br />
<br />
Being Led! DW