---
title: '2014/05/15 Journal Wed_New Job_Questions About God: Who Is God? Why did He create Mankind? Does He still care?'
date: '2014-05-15T11:47:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '9012313269388427630'
blogger_filename: '/2014/05/20140515-journal-wednew-jobquestions.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<br />
<h4>
What Am I Feeling?</h4>
I am feeling happy-ish. I have a new job.<br />
<br />
I am feeling engaged, it seems like I already have some ideas on things I could do to provide value to the team.<br />
<br />
I am feeling like it's about time I start taking my role in this house as seriously as I do any job, task, or assignment.<br />
<br />
<br />
<h4>
What Am I Thankful For?</h4>
Thankful for my new job.<br />
<br />
Thankful for my fit within the environment.<br />
<br />
Thankful for my sure foundation on The Rock Jesus Christ.<br />
<br />
<br />
<br />
<h4>
What's Up?</h4>
<br />
As expected there are things I would improve. Almost immediately I realized this is not what I pictured an "Executive Office" would feel like. But... IT'S NOT SALES! So Hurrah! And they are improving things, slowly.<br />
<br />
There is NO adherence to speak of. No AHT. No Sales Goals. No QA Scores. There is a QA process where a lead reviews and Passes or Fails each and every case you submit. Then if you fail it must be fixed and resubmitted. No problem there.<br />
<br />
It's a bit backwards in the process and procedures arena. But that same lax environment made it possible for the above blessing I suppose. Still, I'd like to see them get a VL.<br />
<br />
***<br />
<br />
I'm sitting with Connor. And he's asking me why the computer thinks VL is misspelled.<br />
<br />
I am now also sitting with Preston. He is asking me: "What's That?!"<br />
<br />
Daddy? When can you help me get that, um, a blog too, um, it got erased.<br />
<br />
*****<br />
<br />
<br />
This Post was by Bryce Anderson on Google+&nbsp;<a href="https://plus.google.com/106575445817109588515/posts/axxaL77g4r4" target="_blank">HERE</a>.<br />
<br />
If you could sit on this bench and chat for 1 hour with anyone from the past or present who would it be...??<br />
<br />
<br />
<a href="https://plus.google.com/u/0/107239408609316397922/posts" target="_blank">+Raul Lopez</a>&nbsp;made the following long post. In reply, which really formulates a series of questions for the person he would sit with. I've edited the grammar, punctuation, and format for easier reading and analysis.<br />
<br />
<b>He states:</b><br />
<div class="MsoNormal">
</div>
<div>
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b>Our Creator</b>, I would have a deep and enlightening for
me (Hopefully) conversation, it would begin by me asking of The creators'&nbsp;<b>meaning
and reason for making humanity</b>,&nbsp;<b>the most erred</b>&nbsp;animal in
creation and Its seemingly most prized one (or so we like to believe).&nbsp;<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I would ask about&nbsp;<b>Its feelings now toward us...</b><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
...<b>after proving that we are capable of destruction only</b>,
while completely fooling ourselves into thinking that we are
"Building", "creating", "Discovering", and
"advancing" while in reality Anywhere we build we really destroy the
ORIGINAL environment as Created by Our Creator, wherever we put concrete and
asphalt we have indeed destroyed the natural flora and fauna of that place,
never to return again, at least not by "society's" will and/or
desire.&nbsp;<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b>We "believe" that we create new stuff while it
has been here all along, and most likely we found a way to destroy</b>&nbsp;an
animal, bug, microbe, fungi or plant by dissecting it and "taking"
only what we desire and discarding the rest therefore killing said organism, to
"create" a new chemical, fabric, leather, or anything we foolishly
believe we have Created.&nbsp;<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b>Only OUR CREATOR has the supreme Wisdom and vision to
truly CREATE without destroying in the process.</b>&nbsp;<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b>I can't find God to ask him,</b>&nbsp;so if anyone out
there has a real illuminated answer to my seemingly crazy ?'s please do leave
me an answer, I really would, no I really Need to know their answer,&nbsp;<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Please....With respect to all {except to those causing
directly or indirectly all the above pain and suffering in Our Creator's Home,
Our Planet Earth. (Yes, Me included, I'm an indirect participant I'm Not exempt
of my contempt)} <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Yet I really hope to somehow find a way to stop being a part
of this cycle and society of destruction and somehow begin to BE a part of the
healing, and fixing and to find a way to start "Consciously Creating"
a better world for ALL (Animals, Plants, Rocks, Bugs, and microbes, etc.) in
it. to create a society to and for the peace, and well being for all.&nbsp;<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
To create the Just and divinely inspired laws that would
defend the weak the mute and innocent from the Giant bullies, the $$$-ladden
screaming greedy minorities that seek to cause all this suffering, and from the
guilty of this innocent children being killed by hunger, lack of proper medical
aid, and the worst in my eyes by War and its violence specially by missiles,
bombs and/or terrible chemicals or radiation...&nbsp;<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I apologize I am ranting here, (or so it seems) I'm not
crazy, or a mental case, even if "society" would like to label me
that way so as not to have to ponder on these words. I am just a man that has
actively seeked the answer to these and other some deeper ?'s on this
subjects;&nbsp;<o:p></o:p></div>
<div class="MsoNormal">
<o:p>&nbsp;</o:p>&nbsp;</div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Yes I would like to take sometime to sit down with It
(Sacred Supreme Creator) and ask on his feelings and what would It like us to
truly do about things? About war? Corrupt governments and Corporations of
Global Greed? Famine? Children dying of hunger while food corporations dump
good edible food in the ocean so as to not cause a prize drop.&nbsp;<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
God, It's Role in all of this and it's true desire for us as
It's (seemingly) greatest creation,&nbsp;<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
</div>
<ul>
<li><span style="font-size: 12pt; line-height: 115%;">War,&nbsp;</span></li>
<li><span style="font-size: 12pt; line-height: 115%;">Famine,&nbsp;</span></li>
<li><span style="font-size: 12pt; line-height: 115%;">Greed,&nbsp;</span></li>
</ul>
<br />
<div class="MsoNormal">
<span style="font-size: 12.0pt; line-height: 115%;"><br /></span></div>
<div class="MsoNormal">
<span style="font-size: 12.0pt; line-height: 115%;">I wonder on
these subjects cause they are not needed to any of Us, the don't benefit any of
us, except those who seek to Own the world those who seek to take Our Creators
place (they are truly insane) and sell us what it's rightfully ours: All the
basic things needed for a happy healthy balanced and just life, yes Our Creator
"Created" us and everything we need to achieve happiness in life,
Food, Shelter, and clothes, yes he created the right amount of : Water,
fruit/nut trees, animals, dirt and other things we would need and with perfect
balance.&nbsp;<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Sadly&nbsp;<b>We corrupted everything</b>&nbsp;by allowing
it to be taken from us by Unjust Laws, and "Blind" Justice that only
serves the ones that "Truly" Steal our water, food, shelters, etc.
from us, that which has been created for Us each and every single one of us by
Divine wisdom and decree by Mine and Yours and sadly their Creator. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
And before you start screaming CRAZY! <b>I did not say not to "work" but not be a slave of your job</b>,
see there's a difference, imagine this: if everything you and I need to be
happy and satisfied in life is here already, put here at the same time we were,
then we don't need to Work for it, or pay for it, it is ours already, but we
can be productive for those around us as we were also created with particular
skills I'm a good writer and healer of the body, a herbal and "touch"
or massage healer, so <b>why not help those
around me where I see the need and without having to be paid or asked and worse
begged to help?</b> <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Why not make beautiful peace and conscience inducing stories
for our young to promote the right human values needed as opposed to creating
"Action, bullets flying, and injustice promoting stories to brain wash
them early? and in return not having to worry for food, shelter or any real
need in my life, others are good mechanics, &nbsp;green builders (another 1 of my skills)
teachers, harvesters etc. <o:p></o:p></div>
<div class="MsoNormal">
<b>We were created for a
reason and with a unique skill set to fulfil that happy existence while making
those around us happy, or at least not harming them.</b> Yet we have been
"Programed" since the womb to not believe this Sacred Truth, we have
been made slaves and made to forget the divine energy within each one of us,
programed to believe we are brute, violent and idiotic enough to
"need" some greedy **** &nbsp;to
make laws and rules for us to be ok, to be good. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I don't buy that<b>, I
believe that if No Laws existed or governments; Well then there would be peace,
bountiful harvests to be shared by all, doctors really healing the sick,
teachers teaching etc. Injustice would be banished since The Law would be
individually and Locally enforced</b>.&nbsp;</div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Eg; in todays world <b>You drive down a
street see a girl being assaulted viciously by a let's say drunk man, what is
everyone around doing? Sadly, Just watching,</b> staring and not doing any to help
the lady. (I have seen it for reals in my life once) Everyone afraid to
intervene and get "sued" or too cowards to put their own self in risk
to help the weak (the lady) from the Crazed strong man abusing her body
savagely, in "my world" it would be like it was that day: " I
asked my son's mother to stop the car, I stepped out with a broom and broke the
stick (we used to work cleaning houses and office buildings) and headed
straight for the dude, asked him once to please stop and let go of the lady, he
punched her again like in defiance and I hit him 3 times with that stick (Cause
it broke) 1ce in the knee, 1ce in the outside of the elbow and in the upper
shoulder, that brought him back to sense and began rambling apologies, i asked
him to give those to the lady, who was crying and in shock, he had been
pounding on her with her hair twisted on one hand and a crumpled beer can used
as a cutting brass knuckles, she had her face cut up, bloody and she was
shaking. I asked to come in the car with me, told her my lady was driving and
she would be safe, i was going to take her to a hospital. So she hopped in, the
guy got ballsy as we drove off screaming some about my mom and the next time he
see me... usual cowardly behaviour, like all the people walking by and not
helping. She told us My Lady and I that he was her Boyfriend, it began cause
she would not give em $$$ for another beer and tried to walk home, then he
pounced on her twisted her hair on one hand and beat her screaming that
"You are dead Bitch!" she was soaked in blood screaming begging for
help as there was at least 15-25 persons within a 25' radius (it was a crowded
bus stop) and no one helped her out! this guy would have killed her and they
would only watch like if at the movies! Ohh what a shame!!! that is what our
current societies moral, ethical, values are CROOKED, TWISTED AND CORRUPTED by
Corrupted Law, And Crooked Injustice not real justice anymore. Well if that was
not here Everyone able would have helped that lady on the spot, they were not afraid
of the drunk coward beating a girl, but of the police showing up and doing
their usual; taking the innocent to jail, and the abuser to a hospital as a
victim so no one helped. <o:p></o:p></div>
<div class="MsoNormal">
I did cause I do not believe in The Current Law system or
the Injustice dept. in place. I believe in the sacred duty to help the weak,
innocent and unable to defend themselves charged upon every single one of us at
creation, yes with rights by our Creator comes Duties to our Creator and since
it is not "Here" then those duties befall all of it's creation. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b>And that's how the
world would be without Laws, Govs, Kings, emirs, popes, elites, filthy Greedy
rich(owners of Our things as created for us by the Law they created to still
and still be "Honest"). No chaos would emerge, no anarchy, and no
crazed raging mad humanity would suddenly appear, to the contrary people would
help each other more, be more conscious of each others needs</b> and what is
not really a necessity and those few 1% that are inherently crooked, bad,
overly greedy and plain destruction seekers would be immediately repealed and
dealt with immediately by those around them. Yes we are created Good and with
good morals and values, Divine justice is put in each one of us at creation,
also innocence and honesty and conscience to not harm others. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b>Don't believe me?
observe a child 3 years old or under before he begins to go to school </b>and
"Programing" begins You will see the most perfect beings in the
world, Just, Rightful, afraid even, to hurt others innocent, chivalrous, respectful
brave enough to help and defend their friends or loved ones from perceived
danger, I have seen this a futile act of valor by a child trying to defend her
mom from an abusive step dad, or a child defending a lil girl from a bully kid
in school (before brainwashing takes root) and also before that washing takes
root their inability to lie, they just can't they are thought to do it by
society, also to be violent, crooked or indifferent to these things if not
active participants. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b>So if we are created
like that, by God, Creator, Supreme Being or whatever You may call Our creator,
why does society/Governments are so inclined to take all that goodness away and
put all this evil destruction causing values in everyone of us?</b> <o:p></o:p></div>
<div class="MsoNormal">
<b><br /></b></div>
<div class="MsoNormal">
Why the need to corrupt every living soul in the planet? And
why must we allow it? <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
WE DON'T! CHANGE BEGINS HERE, TODAY WITHIN EACH ONE OF US...
Or so I choose to believe, what do You choose? What if your choice was the one
needed to effect a change what would You Choose???&nbsp;</div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Thank you for taking the
time to read this, now please do leave your choice/comment/answer for the rest
to read and discuss in respect and open mindedness and most important in the
desire to understand this issues that are so important to me. Thank You for
Your understanding... Blessed Be! ﻿<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<br />
<div class="MsoNormal">
<br /></div>
