---
title: '2014/01/19 Journal Sunday 7:46 am'
date: '2014-01-19T13:50:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3553342101182308835'
blogger_filename: '/2014/01/20140119-journal-sunday-746-am.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

Thankful for clarity of vision and purpose. I am a writer. Thank you for helping me feed this. Thankful for the fact that TODAY I have a 9 year old.<br />
<br />
Feeling... older. I have a nine year old. How did THAT happen? LOL<br />
<br />
What's happening today? Must rush out the door of my bedroom because Connor wants to do his Birthday today! Yeah!.... DW<br />
<br />
---<br />
I got an email from Kenya today.<br />
<br />
Praise the Lord.<br />
Warm greetings in the wonderful name of Jesus Christ. May i introduce myself as Pastor Wycliffe wakhungu from webuye Kenya . I have passion for Christ and heart to care children in our ministry here in Kenya.Its our heart to outreach to unreached with the Gospel of Jesus Christ.I would like to welcome you to come and minister in Kenya.I do hold conferences,revival ,outreaches. children ministry,orphanages and widows ministry<br />
&nbsp;However i was blessed and touched visiting your friendly website.God bless you and grant you favor to reach worldwide for Christ.<br />
Thanks.I look forward hearing from you.<br />
&nbsp;In his service,<br />
pastor wycliffe wakhungu<br />
po box 751 webuye 50205 Kenya<br />
<br />
---<br />
<br />
Hmmm?