---
title: '12/03/14 | Thoughts for the day... politics, leadership, and calling'
date: '2014-12-03T13:53:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6784263315795750936'
blogger_filename: '/2014/12/120314-thoughts-for-day-politics.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<br />
I read 2 Kings Chapters 1-5 this morning. It seems to me that the life of David shows many lessons about leadership and doing something of significance for God. Primarily, that the road to success is not a clean and straight path. You WILL have set backs, delays, enemies (internal and external), and the path is long and winding, with back tracks and side tracks. In the end, God's path for David was partially affected by God's plan, and partially affected by Davids' personality. Mistakes were made, by himself and others. In the end, God brought David to power and the land of Israel was better for it.<br />
<br />
Consistently, David sought the word of God before taking action. We see God providing specific direction to him. This isn't a dry (what's the bible say about this?) type of response, it's a living breathing relational, conversational God that David is interacting with.<br />
<br />
And so it should be in my own life. The Word is important, vital, and the bible contains the Word of God. But the Word of God is alive, and He may speak specific things to you that are not in the bible... however, they should line up with what He's already said in the bible.<br />
<br />
God will provide specific Words to you, direction, and you will learn to obey and follow.<br />
<br />
How often do we ever just "Be still... and know that HE is God?!"<br />
<br />
<br />Also, being FOR a thing, is so much more appealing that being against a thing. David wasn't just against this leader or that because he was seeking his own power. In fact, when leaders died, and people brought that news to him, he mourned. His mourning was the catalyst that brought the land together. There was a substance and quality to his life that people wanted more of, and they made him leader. <br />
<br />
Lately, when I am still... I am inundated with thoughts of politics. Running for office, what I would say/do differently than other politicians. How I would run on openness and honesty. I would share my "dirt" before others could, and take control of my narrative before others have a chance to. I would be FOR solutions, and not just against the way things are. I wouldn't run "against Obamacare", I'd run FOR "The Health Care System Overhaul Plan", which in itself would be divided into smaller more passable bills, rather than built as one large chunk. Yes, it would have the effect of dismantling Obamacare, but it wouldn't be the point. The point is not to get rid of something that doesn't work and go back to the old thing that also didn't work. The point is to provide solutions. It's much easier to provide solutions looking forward and not backward.<br />
<br />
I have no idea why I find myself so taken with this topic for so many months now. Truth be told it's not months, it's years. I've often thought of what I would do/say differently. I have this idea that maybe... just maybe... God is asking me to consider running for public office. I've NEVER won in the popularity contest market, and I'm failing my own family as a Father. I've never run a team of 15 on my own, more less a city/state, etc. I'm not qualified to run for office. And yet... this idea grows.<br />
<br />
I suppose lots of people weren't qualified for lots of things in God's economy, "He qualifies the called"...<br />
<br />
DW<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />