---
title: 'Journal July 17,2014 - Good Soil - Promotion Coming ?!'
date: '2014-07-17T11:55:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6437073601784258333'
blogger_filename: '/2014/07/journal-july-172014-good-soil.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
</h4>
<br />
<h3>
Daily Routine:</h3>
<h4>
BE STILL: Just Listen, write down what He tells you.&nbsp;</h4>
<div>
<b>What did God say today?</b></div>
<br />
<b>God Said:&nbsp;</b><br />
<br />
The Word produces after it's own kind, it's not corruptible. Your heart is the soil. People are out there trying to work and produce enough faith to receive something. It's as though they are attempted to lift cars and houses. Sure, there are a few humans strong enough to lift a car... most never would be or could be that strong.<br />
<br />
God hasn't asked you to lift a car, he's asked you to let Him lift it! You job is to listen, hear, believe, and obey.<br />
<br />
You don't come up with idea either, He does. You can't have faith for what He hasn't said - to you!<br />
<br />
You job is to cultivate the soil. Be Still. Listen. Be Led. Obey. That's cultivating the soil. As you do this, your heart will hear Him more clearly. IF you stop trying to give Him your ideas, stop talking all the time, and listen for instructions, simply obey... Now you are cooking!<br />
<br />
Like Kenneth said: "Here lays a man who knows nothing, doing all the talking to the One who knows everything!"<br />
<h4>
PRAYER: This is the time I do some talking, but still listening also.</h4>
<div>
<a href="http://biblehub.com/greek/1162.htm" target="_blank">Entreaties </a>(specific felt need),&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/4335.htm" target="_blank">Prayers </a>(exchange of desires/wishes),&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/1783.htm" target="_blank">Petitions/Intersessions</a>
 (Intersection of heaven and earth, hit the bullseye, request something 
specific of a King. Technical/Civil term: VERY specific requests that 
meet an exact need!).&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/2169.htm" target="_blank">Thanksgivings</a> ( Lit: giving thanks for God's grace! Gratitude, Thankfulness)</div>
<div>
These are to be made on behalf of:&nbsp;</div>
<div>
<ul>
<li><b>FIRST </b>for <b>all people</b>, then <b>Kings</b>, <b>Leaders</b>, those in <b>Authority</b>, then you would be included in all men, so your family, kin folk, etc.&nbsp;</li>
<li><b>God desires all men to:</b> Be saved and come to the knowledge of the Truth.</li>
</ul>
</div>
<i><a href="http://biblehub.com/context/1_timothy/2-1.htm" target="_blank"><b>1 Timothy 2</b></a></i><br />
<div>
<i>1
 First of all, then, I urge that entreaties and prayers, petitions and 
thanksgivings, be made on behalf of all men, 2 for kings and all who are
 in authority, so that we may lead a tranquil and quiet life in all 
godliness and dignity. 3 This is good and acceptable in the sight of God
 our Savior, 4 who desires all men to be saved and to come to the 
knowledge of the truth. 5 For there is one God, and one mediator also 
between God and men, the man Christ Jesus, 6 who gave Himself as a 
ransom for all, the testimony given at the proper time. 7 For this I was
 appointed a preacher and an apostle (I am telling the truth, I am not 
lying) as a teacher of the Gentiles in faith and truth. 8 Therefore I 
want the men in every place to pray, lifting up holy hands, without 
wrath and dissension.</i></div>
<i><br /></i>
<b>Did anything else come up in prayer that should be notated?&nbsp;</b><br />
<i><br /></i>
<i>Pray for Kings and Priests! </i><i><br /></i>
<br />
<h4>
BIBLE: Instead of a bible devotional, I'm going to do a bible study.&nbsp;</h4>
<div>
Take one of Kenneth's study notes from the front of my bible and do those.</div>
<div>
JOURNAL entry will include all of the above, and anything else on my mind at the time. Take a moment to jot down:</div>
<div>
<br /></div>
<div>
<br /></div>
<blockquote class="tr_bq">
<div>
<i>JP Devo: </i></div>
<div>
<i><br /></i></div>
<div>
<i>So when you have a care or worry, straightaway, turn that care or worry 
into prayer. That is supplication. And when you are troubled by a care 
or worry that you don’t know how to pray for, pray in the Spirit or 
tongues. And in the midst of that prayer, thank God that He is already 
your healing, provision, good success and victory. That, my friend, is 
thanksgiving. <br /><br />
“Pastor Prince, if I am worried about something, how long should I pray?” <br /><br />
Keep on praying. Pray in the Spirit until the worry lifts or dissipates,
 “and the peace of God, which surpasses all understanding, will guard 
your hearts and minds through Christ Jesus”. (Philippians 4:7) </i></div>
</blockquote>
<div>
<br /></div>
<div>
<h4>
JOURNAL: What's Up Today?&nbsp;</h4>
</div>
<br />
<b>How you are feeling:</b><br />
<div>
<br /></div>
<div>
Excited... I can feel the Favor growing back.</div>
<div>
<br /></div>
<div>
<br />
<div>
<b>How you are believing:</b></div>
<div>
<br />
I've been believing better, as I've been listening to Him.</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<b>What's happening in your life right now:</b></div>
<div>
<br /></div>
<br />
Read yesterday's PS!<br />
<br />
DW </div>
