---
title: '2014/03/12 Journal Wed - Digest the Word. Prosper Your Soul. TD Ameritrade Interview.'
date: '2014-03-12T21:52:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3699147794222224334'
blogger_filename: '/2014/03/20140312-journal-wed-digest-word.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
COME:<br />
<br />
<a href="http://e.kcm.org/HM?a=ENX7CqkTRT6y8SA9MKJr7qrnGHxKL9Sxd_cStGb5lw8W0bBhOG5mpqVsje_Hhe-jNFHW">Faith To Faith</a> <br />
<blockquote class="tr_bq" style="background-color: white; font-family: Arial, Helvetica, sans-serif;">
<span style="background-color: white; color: #666666; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth. - 3 John 1:2</span><span style="background-color: transparent;">&nbsp;</span></blockquote>
<blockquote class="tr_bq" style="background-color: white; font-family: Arial, Helvetica, sans-serif;">
<br />
Once you begin to believe it is God's will to prosper you, you can't help but wonder how He is going to do it. Is He going to put a check in the mail? Or start floating $20 bills down from the trees?<br />
No. He's going to do it by prospering your soul. He's going to plant the seeds of prosperity in your mind, will and emotions, and as they grow, they'll produce a great financial harvest.<br />
...<br />
That's what makes God's method of prospering so exciting. It works anywhere and everywhere. It will work in the poorest countries on the face of this earth just like it works here in the United States. And you can be sure that it will work for you!<br />
<em>By Kenneth Copeland</em></blockquote>
<br />
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=120&amp;user_id=darrellwolfe&amp;version=1" target="_blank">Joseph Prince Devotional</a><br />
<br />
<blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12.222222328186035px; line-height: 24.000001907348633px; margin-bottom: 20px; padding: 0px;">
Day 120<br />
See God’s Goodness In The Midst Of Evil<br />
Matthew 2:13<br />
13… an angel of the Lord appeared to Joseph in a dream, saying, “Arise, take the young Child and His mother, flee to Egypt, and stay there until I bring you word; for Herod will seek the young Child to destroy Him.”<br />
...<span style="background-color: #eeedeb; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12.222222328186035px; line-height: 24.000001907348633px;">With every new virus that the devil throws at us, you must discern that the devil is trying to pervert and reverse what God is already doing. Then, you will know that something good is going to come out of it. You see, every new strain of virus tells us that God has already released a new anointing of health for His people. And I believe that He releases new levels of increase for His people too. So don’t just see the evil. See the good that God is already doing!</span></blockquote>
<br />
<br />
<br />
HERE:<br />
<br />
If the soul is comprised of the mind will and emotions... It is those that must prosper. HOW... These will prosper as I begin to take the Word of God and digest it as food, causing those nutrients to become part of my body. Food does no good on my table until it is in my body. I could starve sitting at a table of food if it's not ingested.<br />
<br />
How does food intake work?<br />
<br />
<b>You feel hungry.&nbsp;</b><br />
<ul>
<li>Your body gives you external signals to an internal need.&nbsp;</li>
<li>Smell and Taste can activate an otherwise dormant hunger.</li>
<li>Everyone has hunger for God, but many fast for so long that hunger is dormant. It must be awakened. You cannot force anyone to hunger.&nbsp;</li>
<li>You can prepare an atmosphere that creates a hunger sensation.</li>
<li>You can be aware of your own hunger and acknowledge that.&nbsp;</li>
</ul>
<blockquote class="tr_bq">
<b>Irritation and lack of Faith, Hope, or Love can be signs of spiritual hunger, or even deprivation.&nbsp;</b></blockquote>
<div>
<b><br /></b></div>
<div>
<b>You prepare food, or someone prepares it for you.&nbsp;</b><br />
<ul>
<li>Even an Apple must be harvested and delivered.&nbsp;</li>
<li>Someone will be preparing your spiritual meal. Either you will go into your quiet time and spend time with the Word, or someone will do that for you. We call those sermons, messages, devotionals.&nbsp;</li>
</ul>
<div>
<br /></div>
<b>You cut it down into smaller pieces</b>.<br />
<ul>
<li>Even something as simple as an apple is not taken in all at once, but through a series of bites.&nbsp;</li>
<li>Taking the WHOLE bible, even a whole book, or chapter at once is ok. But to digest it you must cut it down into smaller pieces. Read one chapter at at time, or study a topic and read a few verses and take notes on what they mean to you.&nbsp;</li>
</ul>
<b>You Intake. Put It In Your Mouth.</b><br />
<br />
<ul>
<li>You cannot have food without it passing your mouth. IV's can deliver enough to survive, but never enough to thrive.&nbsp;</li>
<li>Putting the Word into your mouth could have several connotations. But to start, literally put the Word into your mouth. Read it OUT LOUD. Speak it to yourself, of the wall, or a puppet if you must.&nbsp;</li>
<li>Meditation means to murmur to one's self and repeat. Speak the word to yourself. Repeat it often.&nbsp;</li>
<li>Best times to do this are In the Morning, At Night, and On Your Way (from office to office, home to work, etc)...&nbsp;</li>
</ul>
<b>You Chew.&nbsp;</b><br />
<br />
<ul>
<li>Even these bite size pieces must be broken down into digestible size.&nbsp;</li>
<li>Even after breaking them down into smaller bite size pieces you must chew. Chewing on the word indicates work. I've chewed enough on something that my jaw was sore. So take what you learned and break it down even further. It's not enough to know what a verse means, or get an insight into something you've never seen before. You must see how this breaks down into practical truth for you.&nbsp;</li>
<li><br /></li>
</ul>
<div>
<b>You Mix the Food with Saliva</b></div>
<div>
<ul>
<li>The Word must be mixed with Faith</li>
<li>But that's not enough, that's just for the first chew. It's not enough to satisfy your mind with to-do's. You must keep chewing until it saturates your heart.&nbsp;</li>
</ul>
</div>
<div>
<br /></div>
<div>
<b>You swallow</b></div>
<div>
<ul>
<li>This <b><u>nearly </u></b>involuntary act is important. There are eating disorders where people chew but don't swallow. I've seen TV shows where someone pretended to swallow a pill and then spit it out. It does take a willful act to take it into your body.&nbsp;</li>
<li>I would say that this could be as simple as saying:&nbsp;</li>
<ul>
<li>I Believe This.&nbsp;</li>
<li>God said it, that settles it.&nbsp;</li>
</ul>
</ul>
</div>
<div>
<br /></div>
<div>
<b>Your Stomach sends the nutrients to your blood stream</b></div>
<div>
<ul>
<li>This part is involuntary. Even poison, when swallowed will be digested (or rejected by the body). Your stomach will attempt to digest and pull nutrients from anything it receives.&nbsp;</li>
<li>A healthy spirit/body will reject poison. We call that rejection vomit.&nbsp;</li>
<li>This is like your spirit. Once you choose to believe something your spirit will attempt to make that part of you. If you have been feeding yourself good, and you accidentally take in something bad your spirit will reject this. You may not know why, but you will get a feeling that something isn't right.&nbsp;</li>
<li>An Unhealthy body will have a harder time rejecting bad, because it cannot distinguish.&nbsp;</li>
</ul>
</div>
<div>
<br /></div>
<div>
<b>Your blood delivers these nutrients to the place they are needed most.&nbsp;</b></div>
<div>
<ul>
<li>Nutrients don't jump from mouth to body. They must pass through this stomach and be torn down into their base elements and delivered to the blood.&nbsp;</li>
<li>The Blood. The Life Force. The bible calls the blood the life force and that's why Israel couldn't eat an animal with the blood still in it, because the life is in the blood.&nbsp;</li>
<ul>
<li>Practically this means that virus and bacteria would be in the blood and it must be drained asap when the animal is killed, ask any hunter.&nbsp;</li>
<li><a href="http://biblehub.com/leviticus/17-14.htm">http://biblehub.com/leviticus/17-14.htm</a></li>
</ul>
<li>But spiritually, what does this mean?&nbsp;</li>
<li>... The Spirit seeks to fulfill through it's quiet contact with he Spiritual Realm. (Flavia)</li>
</ul>
</div>
<br />
<br />
<br />
<br />
<br />
DO:<br />
<br />
Must block out a time each week to do an in dept Word Study. Daily devotional times each morning AND night are good, but one block of time for study, as least, each week, is part of my "Important but not urgent" category, and must be scheduled if I am to do it.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
Thankful:</h4>
<br />
I'm thankful for my wife, and a possible job with TD Ameritrade.<br />
<br />
<br />
<br />
<h4>
Feeling:</h4>
Exited about the idea of working for TDA<br />
<br />
<br />
<br />
<h4>
What's Up?</h4>
Had a phone screen with TDA. Monica. It went well! I like what she had to say and she liked what I had to say. There was some hint that the income would be more than I make now. I am going to do the assessments in a few minutes.<br />
<br />
Just got back from signing Modification docs for the THIRD time! But our banker was GREAT! I liked this guy!<br />
<br />
Just put down Weed and Feed on the lawn. Hopefully that helps this year.<br />
<br />
That's good for now.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br /></div>
