---
title: 'August 8, 2014 - Journal - Romans 8'
date: '2014-08-07T13:23:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1681928954456798686'
blogger_filename: '/2014/08/august-8-2014-journal-romans-8.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
</h4>
<br />
<h3>
Daily Routine:</h3>
<h4>
BE STILL: Just Listen, write down what He tells you.&nbsp;</h4>
<div>
<b>What did God say today?</b></div>
<br />
<b>God Said:&nbsp;</b><br />
<br />
I didn't have much of a quiet time this morning. Woke up by my alarm and kids coming to tell me they were arguing at the same time. I sent them to bed. However, instead of reacting, I chose to calm down and go into "low-slow" and listen to the Spirit instead. I'm learning that parenting doesn't work by one size fits all answers. You have to listen to HolySpirit and see what he would say. He knows that these two similar situations have different aspects and roots, he'll help you deal with it.<br />
<br />
Today he told me to leave them be in their beds. They were getting louder and louder: "No you", "No You" back and forth. I wanted to rush in and yell and scream at them... but I listened to the instruction and let them be. Soon after they yelled "No You" back and forth so much that it started being a game and they started busting out laughing and giggling. I went in the room a few minute later and they were in the same bed playing and laughing.<br />
<br />
I informed them that this was not the instruction I'd given, asked if they were done fighting, and let them go play. No screaming from Daddy today. I feel better, they feel better, no yelling (from me) and peace was restored. Amazing....<br />
<br />
<br />
<h4>
PRAYER: This is the time I do some talking, but still listening also.</h4>
<br />
<i><a href="http://biblehub.com/niv/1_timothy/1.htm" target="_blank"><b>1 Timothy 1</b></a></i><br />
<i>18Timothy,
 my son, I am giving you this command in keeping with the prophecies 
once made about you, so that by recalling them you may fight the battle 
well, 19holding on to faith and a good conscience, which some have 
rejected and so have suffered shipwreck with regard to the faith. 
20Among them are Hymenaeus and Alexander, whom I have handed over to 
Satan to be taught not to blaspheme.
</i><br />
<br />
<i><a href="http://biblehub.com/context/1_timothy/2-1.htm" target="_blank"><b>1 Timothy 2</b></a></i><br />
<i>1
 First of all, then, I urge that entreaties and prayers, petitions and 
thanksgivings, be made on behalf of all men, 2 for kings and all who are
 in authority, so that we may lead a tranquil and quiet life in all 
godliness and dignity. 3 This is good and acceptable in the sight of God
 our Savior, 4 who desires all men to be saved and to come to the 
knowledge of the truth. 5 For there is one God, and one mediator also 
between God and men, the man Christ Jesus, 6 who gave Himself as a 
ransom for all, the testimony given at the proper time. 7 For this I was
 appointed a preacher and an apostle (I am telling the truth, I am not 
lying) as a teacher of the Gentiles in faith and truth. 8 Therefore I 
want the men in every place to pray, lifting up holy hands, without 
wrath and dissension.</i><br />
<div>
<br />
<div>
<a href="http://biblehub.com/greek/1162.htm" target="_blank">Entreaties </a>(specific felt need),&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/4335.htm" target="_blank">Prayers </a>(exchange of desires/wishes),&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/1783.htm" target="_blank">Petitions/Intersessions</a>
 (Intersection of heaven and earth, hit the bullseye, request something 
specific of a King. Technical/Civil term: VERY specific requests that 
meet an exact need!).&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/2169.htm" target="_blank">Thanksgivings</a> ( Lit: giving thanks for God's grace! Gratitude, Thankfulness)</div>
<div>
These are to be made on behalf of:&nbsp;</div>
<div>
<ul>
<li><b>FIRST </b>for <b>all people</b>, then <b>Kings</b>, <b>Leaders</b>, those in <b>Authority</b>, then you would be included in all men, so your family, kin folk, etc.&nbsp;</li>
<li>Pray for:&nbsp; </li>
<ul>
<li><b>God desires all men to:</b> Be saved and come to the knowledge of the Truth.&nbsp;</li>
<li>Filled with the knowledge of His will through all Wisdom. <a href="http://biblehub.com/colossians/1-9.htm" target="_blank">Col 1:9</a></li>
<li>They may be given the Spirit of Wisdom and revelation in the knowledge of Him. (<a href="https://www.biblegateway.com/passage/?search=Ephesians+1%3A15-23&amp;version=NKJV" target="_blank">Eph 1:15-23</a>)</li>
<ul>
<li>Understanding Be Enlightened.</li>
<li>Know the Hope of His calling.</li>
<li>Riches through inherited Glory.</li>
<li>Exceeding greatness of His power to those who believe. </li>
</ul>
</ul>
</ul>
</div>
</div>
<i><br /></i>
<b>Did anything else come up in prayer that should be notated?&nbsp;</b><br />
<i><br /></i>
<i><br /></i>
<i><br /></i>
<i><br /></i>
<i><br /></i>
<i><br /></i>
<i><br /></i>
<i><br /></i>
<br />
<h4>
BIBLE: Instead of a bible devotional, I'm going to do a bible study.&nbsp;</h4>
<div>
Take one of Kenneth's study notes from the front of my bible and do those.</div>
<div>
JOURNAL entry will include all of the above, and anything else on my mind at the time. Take a moment to jot down:</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true" target="_blank">Romans 8</a> is PACKED full of good stuff! Who knew all that was in the same chapter!?<br />
<blockquote class="tr_bq">
<br />
<i><span class="verse v6" data-usfm="ROM.8.6"><span class="label">6</span><span class="content">For to be carnally minded is death; but to be spiritually minded is life and peace.</span></span></i><br />
<div class="p">
<i><span class="verse v6" data-usfm="ROM.8.6"><span class="content">  </span></span><span class="verse v7" data-usfm="ROM.8.7"><span class="label">7</span><span class="content">Because the carnal mind is enmity against God: for it is not subject to the law of God, neither indeed can be.</span></span></i></div>
<div class="p">
<i><span class="verse v7" data-usfm="ROM.8.7"><span class="content">  </span></span><span class="verse v8" data-usfm="ROM.8.8"><span class="label">8</span><span class="content">So then they that are in the flesh cannot please God.</span></span></i></div>
<div class="p">
<i><span class="verse v8" data-usfm="ROM.8.8"><span class="content">  </span></span><span class="verse v9" data-usfm="ROM.8.9"><span class="label">9</span><span class="content">But
 ye are not in the flesh, but in the Spirit, if so be that the Spirit of
 God dwell in you. Now if any man have not the Spirit of Christ, he is 
none of his.</span></span></i></div>
<div class="p">
<i><span class="verse v9" data-usfm="ROM.8.9"><span class="content">  </span></span><span class="verse v10" data-usfm="ROM.8.10"><span class="label">10</span><span class="content">And if Christ be in you, the body is dead because of sin; but the Spirit is life because of righteousness.</span></span></i></div>
<div class="p">
<i><span class="verse v10" data-usfm="ROM.8.10"><span class="content">  </span></span><span class="verse v11" data-usfm="ROM.8.11"><span class="label">11</span><span class="content">But
 if the Spirit of him that raised up Jesus from the dead dwell in you, 
he that raised up Christ from the dead shall also quicken your mortal 
bodies by his Spirit that dwelleth in you.</span></span></i></div>
</blockquote>
</div>
<div>
I've always used vs 11 for a healing scripture, which is just fine, nothing wrong with that. But today I saw it in a new and fresh light. If I have a carnal mind, I'm envoking the curse/death. If I engage the spiritual mind (mindsets) I am envoking blessing/life. The same Spirit that raised Jesus from the dead is in my body, quickening (making alive) my mortal flesh. That INCLUDES my mind! How do I engage this? </div>
<div>
<br /></div>
<blockquote class="tr_bq">
<div>
<i><br /></i>
<i><span class="verse v16" data-usfm="ROM.8.16"><span class="label">16</span><span class="content">The Spirit itself beareth witness with our spirit, that we are the children of God:</span></span></i><br />
<div class="p">
<i><span class="verse v16" data-usfm="ROM.8.16"><span class="content">  </span></span><span class="verse v17" data-usfm="ROM.8.17"><span class="label">17</span><span class="content">And
 if children, then heirs; heirs of God, and joint-heirs with Christ; if 
so be that we suffer with him, that we may be also glorified together.</span></span></i></div>
</div>
</blockquote>
<div>
<blockquote class="tr_bq">
--</blockquote>
<blockquote class="tr_bq">
<i><span class="verse v26" data-usfm="ROM.8.26"><span class="label">26</span><span class="content">Likewise
 the Spirit also helpeth our infirmities: for we know not what we should
 pray for as we ought: but the Spirit itself maketh intercession for us 
with groanings which cannot be uttered.</span></span></i><br />
<div class="p">
<i><span class="verse v26" data-usfm="ROM.8.26"><span class="content">  </span></span><span class="verse v27" data-usfm="ROM.8.27"><span class="label">27</span><span class="content">And
 he that searcheth the hearts knoweth what is the mind of the Spirit, 
because he maketh intercession for the saints according to the will of 
God.</span></span></i></div>
</blockquote>
<span class="verse v27" data-usfm="ROM.8.27"><span class="content"></span></span></div>
<div>
HolySpirit bears witness to my Spirit, first of my adoption, and then to any truth I need, because he is here to lead me into all truth (according to John). Likewise, he helps me in my weakness by interceding for me and praying out the Will of God in my life. I can tap into this during my times of prayer, meditation, and silence. <br />
<br />
<blockquote class="tr_bq">
<i><span class="verse v28" data-usfm="ROM.8.28"><span class="label">28</span><span class="content">And we know that all things work together for good to them that love God, to them who are the called according to his purpose.</span></span></i><span class="verse v28" data-usfm="ROM.8.28"><span class="content">  </span></span><span class="verse v29" data-usfm="ROM.8.29"><span class="label"></span></span></blockquote>
This process of allowing him to pray through you, specifically through times of silence and praying in tongues, is how he works all things together for Good!<br />
<br />
<blockquote class="tr_bq">
<div class="p">
<span class="verse v30" data-usfm="ROM.8.30"><span class="content">  </span></span><i><span class="verse v31 focused" data-usfm="ROM.8.31"><span class="label">31</span><span class="content">What shall we then say to these things? If God be for us, who can be against us?</span></span></i></div>
<div class="p">
<i><span class="verse v31 focused" data-usfm="ROM.8.31"><span class="content">  </span></span><span class="verse v32" data-usfm="ROM.8.32"><span class="label">32</span><span class="content">He that spared not his own Son, but delivered him up for us all, how shall he not with him also freely give us all things?</span></span></i></div>
</blockquote>
</div>
<div>
If God is for me, WHO can be against me? NO ONE! He didn't spare His own Son... So why, here on earth, would I doubt His desire to give me freely ALL THINGS?!!?!?!?! He's not out to get me, curse me, or do harm to me. If He told me to marry Flavia, and he gifted these children, they there is no other family on earth, or any other reality of choices, that could be better. If I'm not enjoying them, it's because I haven't tapped into that truth. He's given me these three to ENJOY. He'll just have to show me how to enjoy them. Much of the strife has most likely been self-induced on my part.<br />
<br />
Once I get that straight, and really accept God had my best in mind with these gifts, I'll be able to freely trust Him for other more temporal things.&nbsp; </div>
<div>
<h4>
JOURNAL: What's Up Today?&nbsp;</h4>
</div>
<br />
<b>How you are feeling:</b><br />
<div>
<br />
I'm feeling good! I may have another promotion looming, although things move slowly in OOP. I'm accepting the fact that I'm never going to be "Caught Up" because once I close a case another will come in, so I just need to accept that and relax.</div>
<div>
<br /></div>
<div>
<br />
<div>
<b>How you are believing:</b></div>
<div>
<br />
I'm starting to believe that my life good have an upward swing, it will depend on me slowing down, being still, and listening for instruction. </div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<b>What's happening in your life right now:</b></div>
<div>
<br /></div>
We're at Gateway. I'm meeting with Jack again soon. I feel there is something more to his Call To Excellence project, I just need to get it out of him and myself. My work in OOP and practice of being still and listening, may help me have a more productive conversation with him this time regarding this project. All our conversation have been good, but not nessesarily productive in regards to Call to Excellence.<br />
<br />
I just watched videos on Knife skills for cooking last night... REALLY enjoyed them! I'm going to listen to all of them! It was amazing! I really enjoy the kitchen!<br />
<br />
Going to head to work now.&nbsp; <br />
<br />
<br />
<br />
DW</div>
