---
title: '2014/02/18 Journal Tue'
date: '2014-02-18T13:26:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3022781786031787588'
blogger_filename: '/2014/02/20140218-journal-tue.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=98&amp;content=0" target="_blank">Day 98</a><br />Your Advocate Always Wins Your Case<br />1 John 2:1<br />1My little children, these things I write to you, so that you may not sin. And if anyone sins, we have an Advocate with the Father, Jesus Christ the righteous.<br />If you want a glimpse of some real-life celestial drama, picture this: God the Father sits as Judge of the universe with Jesus Christ at His right hand, who is not only your High Priest, but also your Advocate.<br />When your accuser, the devil, comes along and says, “You have done this wrong and you have not done that right,” Jesus says, “Father, the devil is right, but My blood has paid for what the devil is accusing him of.”</blockquote>
<br />
<h4>
Thankful:</h4>
Today I am thankful for the blood of Jesus. More specifically the patience of Jesus. God is not a demanding God. He is a faithful patient God. He doesn't cause me trouble, He is my solution.<br />
<h4>
Feeling:</h4>
Mixed Emotions.<br />
<br />
During my quiet reset time I had more flash back memories of my failures in past relationships. Among them came the strange desire to make sure my divorce papers actually got filled back in 2002. Weird thought. I was not just a failure in relationship then, I still am.<br />
<br />
At the same time, I feel grateful for yesterday. I set up a Self Pep Talk that seemed helpful to me. I was able to face the brutal reality of my current situation at work, stop pretending it's anything other than what it is, and then find a now solution and long term solution. I'll paste that below.<br />
<br />
<h4>
What's Up?</h4>
Going to work in a bit. Not ready. Never am. But people are people. The people I'm going to talk to today are A. Service Bankers and B. Customers. The A crowd are momentary blips, less than 15 seconds each. The B crowd are the ones I'll actually have to deal with. The B crowd have been shoved to me, have no idea who I am or why we're talking. The B crowd are just people. The are PERSONS. They are not customers or callers or interruptions to my peace.<br />
<br />
These are people with dreams, hopes, aspirations, faults, failures, pains, and problems. If I get to know them as people I may be able to offer a friendly word, spirit led suggestion, or maybe, just maybe, offer a product or service that could actually make their lives better.<br />
<br />
I am Darrell Wolfe, and I sell Financial Good Success!<br />
<br />
<h4>
</h4>
*****************************************<br />
<h3>
The Self Pep Talk</h3>
<br />
<h4>
This Job</h4>
<h2>
This Job is NOT:<o:p></o:p></h2>
<div class="MsoListParagraphCxSpFirst" style="mso-list: l3 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: Symbol; font-size: 10.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">Talking
to intelligent people. <o:p></o:p></span></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l3 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: Symbol; font-size: 10.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">Talking
to people who have any savvy. <o:p></o:p></span></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l3 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: Symbol; font-size: 10.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">Customer
will not know why they are being transferred. <o:p></o:p></span></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l3 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: Symbol; font-size: 10.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">Customers
will not be vetted the way you did when you were in service. <o:p></o:p></span></div>
<div class="MsoListParagraphCxSpLast" style="mso-list: l3 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: Symbol; font-size: 10.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">Service
bankers will NOT have looked for needs or make needs based referrals. <o:p></o:p></span></div>
<h2>
This Job IS:<o:p></o:p></h2>
<div class="MsoListParagraphCxSpFirst" style="mso-list: l2 level1 lfo2; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: Symbol; font-size: 10.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">Customers
getting transferred without knowing why.<o:p></o:p></span></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l2 level1 lfo2; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: Symbol; font-size: 10.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">Service
bankers under pressure to meet unreasonable sales goals pushing people at you
who shouldn't have been transferred in the first place. <o:p></o:p></span></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l2 level1 lfo2; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: Symbol; font-size: 10.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">Service
bankers who have little coaching or training about how to identify real needs
anymore, and didn't get trained the way we used to be, transferring customer
based on a random offer in an offer bag for something the customer MORE THAN
LIKELY doesn't need or want, and can't use. <o:p></o:p></span></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l2 level1 lfo2; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: Symbol; font-size: 10.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">ECPR
Sales Offers that don’t make any sense for the customers, created by an out of
touch marketing department based on pre social media web 2.0 ideas and
strategies. <o:p></o:p></span></div>
<div class="MsoListParagraphCxSpLast" style="mso-list: l2 level1 lfo2; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: Symbol; font-size: 10.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">Either
as bad as cold calling... or worse. <o:p></o:p></span></div>
<h2>
Wells Fargo is a secular and out of date company. <o:p></o:p></h2>
<div class="MsoListParagraphCxSpFirst" style="mso-list: l1 level1 lfo4; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: Symbol; font-size: 10.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">They
are Corporation 1.0 not corporation 2.0. <o:p></o:p></span></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo4; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: Symbol; font-size: 10.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">They
don't understand the new wave and they are a dying breed. <o:p></o:p></span></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo4; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: Symbol; font-size: 10.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">They
WILL NOT CHANGE for the better, they will keep plugging away and more than
likely die off like all old school brands before them. <o:p></o:p></span></div>
<div class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; mso-list: l1 level2 lfo4; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;Courier New&quot;; font-size: 10.0pt; line-height: 115%; mso-fareast-font-family: &quot;Courier New&quot;;">o<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">They
are Circuit City. Borders Bookstores. Dying like the current American Malls.<o:p></o:p></span></div>
<div class="MsoListParagraphCxSpLast" style="margin-left: 1.0in; mso-add-space: auto; mso-list: l1 level2 lfo4; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;Courier New&quot;; font-size: 10.0pt; line-height: 115%; mso-fareast-font-family: &quot;Courier New&quot;;">o<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">Stuck
in the old ways. Refusing to see the problems and address them. Measuring the
unimportant with great accuracy, as Seth Godin says. <o:p></o:p></span></div>
<h2>
Your options are:<o:p></o:p></h2>
<div class="MsoListParagraphCxSpFirst" style="mso-list: l0 level1 lfo3; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: Symbol; font-size: 12.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 115%;">Get
a new job.<o:p></o:p></span></div>
<div class="MsoListParagraphCxSpLast" style="mso-list: l0 level1 lfo3; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: Symbol; font-size: 12.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 115%;">Make
Due. <o:p></o:p></span></div>
<h2>
In the meantime:<o:p></o:p></h2>
<blockquote class="tr_bq">
<b><span class="MsoSubtleReference"><span style="font-family: Symbol; font-size: 10pt; line-height: 115%;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><!--[endif]--></b><span style="font-size: 10.0pt; line-height: 115%;"><b>Take each call with JOY. </b><span class="MsoSubtleReference"><b>Joy Through
Perspective: Heaven Is Home, Not Earth.</b><o:p></o:p></span></span></blockquote>
<div class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; mso-list: l4 level2 lfo5; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;Courier New&quot;; font-size: 10.0pt; line-height: 115%; mso-fareast-font-family: &quot;Courier New&quot;;">o<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">Not
Joy OF the call. <o:p></o:p></span></div>
<div class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; mso-list: l4 level2 lfo5; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;Courier New&quot;; font-size: 10.0pt; line-height: 115%; mso-fareast-font-family: &quot;Courier New&quot;;">o<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">Joy
IN the call. <o:p></o:p></span></div>
<div class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; mso-list: l4 level2 lfo5; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;Courier New&quot;; font-size: 10.0pt; line-height: 115%; mso-fareast-font-family: &quot;Courier New&quot;;">o<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">You
are not full of JOY because it's a great job. You are not full of joy because
everything is right or ok. <o:p></o:p></span></div>
<div class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; mso-list: l4 level2 lfo5; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;Courier New&quot;; font-size: 10.0pt; line-height: 115%; mso-fareast-font-family: &quot;Courier New&quot;;">o<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">You
are full of joy DESPITE the call and situation. <o:p></o:p></span></div>
<div class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; mso-list: l4 level2 lfo5; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;Courier New&quot;; font-size: 10.0pt; line-height: 115%; mso-fareast-font-family: &quot;Courier New&quot;;">o<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">You
are full of JOY because like Joseph in Prison or Daniel in the Lions den, you
are headed to a better place. <o:p></o:p></span></div>
<div class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; mso-list: l4 level2 lfo5; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;Courier New&quot;; font-size: 10.0pt; line-height: 115%; mso-fareast-font-family: &quot;Courier New&quot;;">o<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">If
things NEVER get better on earth, you will go to a better place someday and
this was only temporary. <o:p></o:p></span></div>
<blockquote class="tr_bq">
<b><span style="font-family: Symbol; font-size: 10.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--></b><span style="font-size: 10.0pt; line-height: 115%;"><b>Engage
in Thankfulness. </b><o:p></o:p></span></blockquote>
<div class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; mso-list: l4 level2 lfo5; text-indent: -.25in;">
<!--[if !supportLists]--><span class="MsoSubtleReference"><span style="font-family: 'Courier New';">o<span style="font-family: 'Times New Roman'; font-size: 7pt;">&nbsp;&nbsp; </span></span></span><!--[endif]--><span class="MsoSubtleReference">Find things to be grateful about. Make up stuff if you
need to. <o:p></o:p></span></div>
<blockquote class="tr_bq">
<b><span style="font-family: Symbol; font-size: 10.0pt; line-height: 115%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--></b><span style="font-size: 10.0pt; line-height: 115%;"><b>Engage
PEOPLE</b>.<o:p></o:p></span></blockquote>
<div class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; mso-list: l4 level2 lfo5; text-indent: -.25in;">
<!--[if !supportLists]--><span class="MsoSubtleReference"><span style="font-family: 'Courier New';">o<span style="font-family: 'Times New Roman'; font-size: 7pt;">&nbsp;&nbsp; </span></span></span><!--[endif]--><span class="MsoSubtleReference">These are not customers, callers, accounts, products…
these are PEOPLE. Engage them as people. <o:p></o:p></span></div>
<br />
<div class="MsoListParagraphCxSpLast" style="margin-left: 1.0in; mso-add-space: auto; mso-list: l4 level2 lfo5; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;Courier New&quot;; font-size: 10.0pt; line-height: 115%; mso-fareast-font-family: &quot;Courier New&quot;;">o<span style="font-family: 'Times New Roman'; font-size: 7pt; line-height: normal;">&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size: 10.0pt; line-height: 115%;">Ignore
the service banker. They have no bearing on your life. They are nothing more
than a brief distraction between you and the people you serve. Be polite,
quick, thank them for the call, and more on. 15 seconds or less with the
service banker.<o:p></o:p></span></div>
<br />