---
title: '2014/01/24 Journal Fri'
date: '2014-01-24T13:28:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5512724135059364297'
blogger_filename: '/2014/01/20140124-journal-fri.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
VOD:</h4>
<blockquote class="tr_bq">
Matthew 25:29<br />
29‘For to everyone who has, more will be given, and he will have abundance; but from him who does not have, even what he has will be taken away.</blockquote>
"The rich get richer and the poor get poorer..." That's biblical, and right, and good, and fair. Here's why.<br />
<blockquote class="tr_bq">
Excerpt from the Joseph Prince Devotional:<br />
<span style="background-color: #eeedeb; color: #333333; font-size: 12px; line-height: 21px;">"Have you come across people who have little, yet even that little is taken away from them? On the other hand, there are those who already have much, yet they receive even more.</span><span style="background-color: #eeedeb; color: #333333; font-size: 12px; line-height: 21px;">.....</span><span style="background-color: #eeedeb; color: #333333; font-size: 12px; line-height: 21px;">Today, we are talking about the haves and have-nots in the church. If you believe that it is yours, you will have it. You will see yourself possessing it and enjoying it, and more will be given to you. But if you say, “Well, I don’t feel it and I’m not sure if it will come,” in essence, you are saying that you don’t have it when you actually do. Then, even what you have will be taken away. So say you have it today!"</span></blockquote>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
<br /></div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
So I read that, and got to thinking. How many times have I heard this saying: "The rich get richer and the poor get poorer." Then that is used to justify punishing the rich. But I've met the poor. I work with people who are living the check to check mindset, and those who don't even have that, they have a moment by moment mindset.&nbsp;</div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
<br /></div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
For the vast majority of these this is not a problem of education, ability, situation, environment, or any of the other things people blame. It's a heart issue. They refuse to see or believe that there can be more.&nbsp;</div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
<br /></div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
Farrah Gray author of "Reallionaire", shows in living color his descriptions of his neighborhood and how the people of his ghetto were fighting, rather than encouraging, his prosperity. This is how the poor operate. All languages, cultures, races, ethnicities: the poverty mentality is the same in every state and every country. It may come with different nuances or flavors, but the poverty mentality wants you, and all the people around you to stay poor.</div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
<br /></div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
You have to fight against this kind of issue by grabbing hold of the Word of God. Finding out that he has already blessed you before you were even born, through Jesus. Digg in His Word and find out out what he has for you. And then say it, out loud, to yourself, every day, until belief swells inside of you...&nbsp;</div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
<br /></div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
But don't stop there. That is where most people stop. Then the belief starts to die again because nothing came of it. When belief has started to rise in you, and you feel it taking over. Start taking action to feed that flame and put action to Faith. Belief isn't Faith, although they are related.&nbsp;</div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
<br /></div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
Faith is the substance of Hope. Belief is more closely related to Hope than Faith. Hope is expectation. If your belief becomes strong enough, it becomes expectation/hope. But without action Faith is dead. Faith requires action to put begin to bring substance out of the Spiritual World and breath life into that Expectation.&nbsp;</div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
<br /></div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
Start Small. Finish Big. Go get a Library Card. Then choose books to read to feed the passions God is raising in you. Keep in mind that a solid life is built on many bricks. So God may have you read two books on HTML, that doesn't mean he wants you to go be a web designer. But maybe that material was enough to give you insight into how to use your blog building software better. Or maybe seeing the way code works gave you better understanding of how the Laws of Nature or the Laws of the Kingdom of God function. He may have you reading different kinds of books from all over the Library. Pray about each one you pick up.&nbsp;</div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
<br /></div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
Eventually you will weed out the things you are not called to be. Good ideas that weren't God ideas, or at least not permanent "here's what I want to be the rest of my life ideas". When you find your truest passion. Feed that. Read at least one chapter in a book, one blog post, listen to one Podcast on the way to work... Feed the passion He's given you.&nbsp;</div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
<br /></div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
Then take more action. Start a blog. Learn how to cook better. Look for free computer program that help you practice architecture. Do something, even a small thing, to put into practice the things you are learning. Sometimes the best schools are found outside of "School". They are a combination of your local library, your home/office, and a few mentors along the way.&nbsp;</div>
<div style="color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px;">
<br /></div>
<div>
<span style="color: #444444; font-family: Helvetica Neue, Arial, Liberation Sans, FreeSans, sans-serif;"><span style="font-size: 14px;"><a href="https://www.bible.com/notes/18946767" target="_blank">https://www.bible.com/notes/18946767</a></span></span></div>
<div>
<span style="color: #444444; font-family: Helvetica Neue, Arial, Liberation Sans, FreeSans, sans-serif;"><span style="font-size: 14px;"><br /></span></span></div>
<div>
<span style="color: #444444; font-family: Helvetica Neue, Arial, Liberation Sans, FreeSans, sans-serif;"><span style="font-size: 14px;"><br /></span></span></div>
<h4>
Thankful</h4>
I'm thankful for The Word of God! It's coming alive in me again. I need to keep feeding that fire with this daily routine. Part of that is putting the Word First!<br />
<br />
I'm thankful for Flavia. She get's me.<br />
<br />
<h4>
Feeling</h4>
Feeling... a bit of stress realizing I have to go back to work today. Why am I feeling stressed? I'm sitting in my office just like any other morning. The pressure of sales goals and micro managers is not something I'm looking forward to. I got a pretaste of that by seeing an Adherence report on my desk when I went in to do my time-card "Come see me when you get in"... uhg...<br />
<br />
Reframe: Adherence is totally within my ability to take care of. I only need to be diligent about it.<br />
<br />
Feeling sad about a job situation. AAA was supposed to call me at 9am on Wed and never called. I really had it in my mind that I'd do the interview, find out more about the position. Make a decision internally to see if it was a good fit. Possibly schedule a follow up interview and then leave WF before Feb... But they didn't call. I feel bummed.<br />
<br />
Reframe: Who knows why they didn't call. Maybe she was out sick that day and no body could get to her emails or schedule to find out what to do. Maybe God blocked it because that particular position, or interviewer wasn't right for me, but the same job title under a different manager or interviewer would be a perfect fit. Maybe AAA isn't right at all and there is another avenue.<br />
<br />
I trust you God. You care for me. Lead me to the place YOU want me to be.<br />
<h4>
What's happening right now</h4>
<br />
Going to work today. I'm going to be a good little worker be, adhere to my schedule, get warm transfers, and make sales. I'm not going to be the Dave Ramsey show, but I'll probably lightly mention his name a few times. I'll ask more questions and give less speeches. I'll listen and look for needs and then meet those needs, many times with products and services. I'll pray for each person as they are being introduced, and then silently pray for them as we talk throughout each call.<br />
<br />
Work is an all day deal... so that's the plan today.<br />
<br />
I want to communicate more with Ben's Dad. Something is there with this Kenya thing. Can't shake it.<br />
<br />
<br />
Darrell<br />
<div>
<br /></div>
