---
title: 'Church Notes Gatewaypeople 02/16/2014'
date: '2014-02-16T17:47:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5734113341501868166'
blogger_filename: '/2014/02/church-notes-gatewaypeople-02162014.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Church Notes'
---

<p>Jimmy Evans</p>
<p>Spirit. Soul. Body. Mind.</p>
<p>Love your spouse with all areas. Become soul mates.</p>
<p>Sin lies. Sin promises great fun and leaves you empty. </p>
<p>Soul mate myths</p>
<p>1. My soul mate they'll be just like me. Always think the same and read my mind. </p>
<p>Compatibility is based on character and values. Not on sameness.</p>
<p>2. If I marry my soul mate we'll never have problems.</p>
<p>That is not true. It could make you think "I married the wrong person". The best marriages are born in great work.</p>
<p>3. My soul mate will meet my needs and make me happy all the time</p>
<p>NO person will or could ever make you happy all the time. Only God makes you happy.</p>
<p>Soul: Mind. Will. Emotions</p>
<p>Three choices that birth soul mates.</p>
<p>1. Empathy.</p>
<p> Experience another persons emotions, experience.</p>
<p>Daters use empathy to be sensitive to the other persons need.</p>
<p>Empathy is a choice of will over emotion.&nbsp; You will often feel like doing something you shouldn't or not do something you should.</p>
<p>Ask: I wonder what it would be like to be married to me? How do my words, actions, inaction, silence affect them?</p>
<p>Five minutes of intentional empathy a day will resurrect a dead marriage. </p>
<p>2. Generosity</p>
<p>Do what they need not what you want. Give them what they need regardless of whether you see that need as valid. </p>
<p>Sow your soul to reap her/his soul.</p>
<p>3. Marriage is first.</p>
<p>ONLY God comes before your marriage.</p>
<p>Not your kids. Job. Hobby. Interest.&nbsp; Or anything else. <br><br><br></p>
