---
title: 'Journal - July 23, 2014 - Up Early - Be Still Be Silent - Yield to Healing - The Word is GOOD!!!!'
date: '2014-07-23T11:27:00.0040000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4324566521892456326'
blogger_filename: '/2014/07/journal-july-23-2014-up-early-be-still.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Healing'
  - 'Journal'
  - 'Revelation'
---

<h4>
</h4>
<br />
<h3>
Daily Routine:</h3>
<h4>
BE STILL: Just Listen, write down what He tells you.&nbsp;</h4>
<div>
<b>What did God say today?</b></div>
<br />
<b>God Said:&nbsp;</b><br />
<br />
<br />
*When I first started out learning how to walk by Faith, I would get 
woken up by HolySpirit at around +/- 4 am&nbsp; and I would pray and be led. 
Looking back, I realize that He'd been trying this with me for years (as
 He probably does with most people), but I was too fleshly to notice it 
was Him and went back to sleep.<br />
<br />
This morning I woke up
 needing to go potty because I ate too much too late. But as I was going
 back to sleep I felt that same call. "Stay with me a while." It's hard 
to describe if you haven't sensed it before. It's like a presence, a 
peace, a whispering, and a yearning all tied up together. But it's soft 
and subtle, usually it's not overpowering. It could be ignored if you 
want, or yielded to if you want. <br />
<br />
Learning to yield to 
that calling-request-His Desire To Be In Your Presence is the sweetest 
kind of yielding, but it's hard on the flesh at first. It won't be if 
you give it ten minutes, but those first minute when your body is 
telling you to be asleep can be hard for a moment. But as you yield to 
His presence all that subsides.<br />
<br />
This morning it was 
about 4:45 am and He was calling. I yielded, for the first time in a 
long time, and it felt great. This time though, I had been further armed
 with the things He's been teaching me about being led and being still 
and listening.<br />
<br />
This morning He said to me: Be Still Be 
Silent, and yield to healing. I was feeling symptoms of a cold/flu 
coming on and He said to me, "...these are symptoms of eating issues, 
not of sickness, but the enemy is trying to put sickness on you, don't 
accept it. Yield to healing, be still, be silent, and yield to it." Then
 scriptures started to rise. I felt led to say: "I yield to healing, 
bought and paid for by the blood and body of Jesus." I feel fine now. 
5:40 am<br />
<br />
<h4>
PRAYER: This is the time I do some talking, but still listening also.</h4>
<br />
<i><a href="http://biblehub.com/niv/1_timothy/1.htm" target="_blank"><b>1 Timothy 1</b></a></i><br />
<i>18Timothy, my son, I am giving you this command in keeping with the prophecies once made about you, so that by recalling them you may fight the battle well, 19<b>holding on to faith and a good conscience, which some have rejected and so have suffered shipwreck with regard to the faith.</b> 20Among them are Hymenaeus and Alexander, whom I have handed over to Satan to be taught not to blaspheme.
</i><br />
<br />
<i><a href="http://biblehub.com/context/1_timothy/2-1.htm" target="_blank"><b>1 Timothy 2</b></a></i><br />
<div>
<i>1
 <b>First of all, then, I urge that entreaties and prayers, petitions and 
thanksgivings, be made on behalf of all men, 2 for kings and all who are
 in authority, so that we may lead a tranquil and quiet life in all 
godliness and dignity.</b> 3 This is good and acceptable in the sight of God
 our Savior, 4 <b>who desires all men to be saved and to come to the 
knowledge of the truth.</b> 5 For there is one God, and one mediator also 
between God and men, the man Christ Jesus, 6 who gave Himself as a 
ransom for all, the testimony given at the proper time. 7 For this I was
 appointed a preacher and an apostle (I am telling the truth, I am not 
lying) as a teacher of the Gentiles in faith and truth. 8 Therefore I 
want the men in every place to pray, lifting up holy hands, without 
wrath and dissension.</i><br />
<br />
<div>
<a href="http://biblehub.com/greek/1162.htm" target="_blank">Entreaties </a>(specific felt need),&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/4335.htm" target="_blank">Prayers </a>(exchange of desires/wishes),&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/1783.htm" target="_blank">Petitions/Intersessions</a>
 (Intersection of heaven and earth, hit the bullseye, request something 
specific of a King. Technical/Civil term: VERY specific requests that 
meet an exact need!).&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/2169.htm" target="_blank">Thanksgivings</a> ( Lit: giving thanks for God's grace! Gratitude, Thankfulness)</div>
<div>
These are to be made on behalf of:&nbsp;</div>
<div>
<ul>
<li><b>FIRST </b>for <b>all people</b>, then <b>Kings</b>, <b>Leaders</b>, those in <b>Authority</b>, then you would be included in all men, so your family, kin folk, etc.&nbsp;</li>
<li>Pray for:&nbsp; </li>
<ul>
<li><b>God desires all men to:</b> Be saved and come to the knowledge of the Truth.&nbsp;</li>
<li>Filled with the knowledge of His will through all Wisdom. <a href="http://biblehub.com/colossians/1-9.htm" target="_blank">Col 1:9</a><i></i></li>
<li>They may be given the Spirit of Wisdom and revelation in the knowledge of Him. (<a href="https://www.biblegateway.com/passage/?search=Ephesians+1%3A15-23&amp;version=NKJV" target="_blank">Eph 1:15-23</a>)</li>
<ul>
<li>Understanding Be Enlightened.</li>
<li>Know the Hope of His calling.</li>
<li>Riches through inherited Glory.</li>
<li>Exceeding greatness of His power to those who believe. </li>
</ul>
</ul>
</ul>
</div>
</div>
<i><br /></i>
<b>Did anything else come up in prayer that should be notated?&nbsp;</b><br />
<i>...</i><i><br /></i>
<i><br /></i>
<br />
<h4>
BIBLE: Instead of a bible devotional, I'm going to do a bible study.&nbsp;</h4>
<div>
Take one of Kenneth's study notes from the front of my bible and do those.</div>
<div>
JOURNAL entry will include all of the above, and anything else on my mind at the time. Take a moment to jot down:</div>
<div>
<br />
See the above changes to my prayer time. </div>
<div>
<br /></div>
<div>
Also: <a href="http://www.kcm.org/sites/default/files/cck/document/field_document/Having%20Ears%20to%20Hear%20Study%20Notes.pdf" target="_blank">Having Ears To Hear Study, By KCM</a>. </div>
<div>
<ul>
<li>Build a stronghold of Faith as you are tearing down the stronghold of unbelief. You do both the same way: Casting down thoughts and imaginations contrary to God's Word! <a href="http://www.biblestudytools.com/nkjv/2-corinthians/passage.aspx?q=2-corinthians+10:3-6" target="_blank">2 Cor 10</a>&nbsp;</li>
<li>Be swift to hear, slow to speak, slow to anger. Lay aside twistedness and receive restrained/retrained power (meekness) through The Word of God. Be a doer, and not just a hearer. <a href="http://www.biblestudytools.com/nkjv/james/passage.aspx?q=james+1:19-22" target="_blank">James 1:19-22</a></li>
<li>&nbsp;The Word: you have known the Word which makes you wise for Sozo through Faith. <a href="http://www.biblestudytools.com/nkjv/2-timothy/passage.aspx?q=2-timothy+3:10-17" target="_blank">2 Tim 3</a></li>
</ul>
Glory to God! The Word will make you wise for salvation (Spirit, Soul, Body, Mind, Financially, Socially, Bodily-Health, Etc) If you need wisdom on how to receive the things God has for you, the Word will do it!&nbsp; <br />
<ul>
<li>The Word (Part 2): will be good for instruction, correction, protection, guidance, and more. <a href="http://biblehub.com/interlinear/2_timothy/3-16.htm" target="_blank">2 Tim 3:16</a></li>
<li>Specifically:</li>
<ul>
<li><b>Doctrine</b>: <a href="http://biblehub.com/greek/1319.htm" target="_blank">Didaskalia</a>- <b>Teachings, Precepts</b>. A better word than doctrine would be Teachings. Like when Dave Ramsey sets forth his Total Money Makeover, that would be his Teachings. </li>
<li><b>Reproof</b>: <a href="http://biblehub.com/greek/elegmon_1650.htm" target="_blank">Elegmon </a>- <b>"Proof" and "Conviction"</b>. Inner conviction of invisible realities. </li>
<ul>
<li>That by which invisible things are proved (and we are convinced of their reality), <a href="http://biblehub.com/interlinear/hebrews/11-1.htm">Hebrews 11:1</a></li>
</ul>
<li><b>Correction</b>: <a href="http://biblehub.com/greek/1882.htm" target="_blank">Epanortho'sis</a> - <b>To make right again.</b> </li>
<ul>
<li>1882 <i>epanórthōsis</i> (from <a href="http://biblehub.com/greek/1909.htm">1909</a> <i>/epí</i>, "<i>on</i>, fitting" intensifying <a href="http://biblehub.com/greek/461.htm">461</a> <i>/anorthóō</i>, "make straight") – properly, suitable because <i>straight</i>, i.e. <i>restored to its</i> (<i>original</i>) <i>proper condition</i>; hence, <i>correction</i> (referring to something that is aptly "<i>straightened</i> out").</li>
</ul>
<li><b>Instruction</b>: <a href="http://biblehub.com/greek/3809.htm" target="_blank">Paideia </a>-<b>Instruction that trains someone to full development! </b></li>
<ul>
<li><b>C</b>ognate: 3809 <i>paideía</i> (from <a href="http://biblehub.com/greek/3811.htm">3811</a> <i>/paideúō</i>, see there) – properly, <i>instruction</i> that <i>trains</i> someone to reach full development (maturity). </li>
</ul>
</ul>
</ul>
</div>
<div>
<br /></div>
<div>
<h4>
JOURNAL: What's Up Today?&nbsp;</h4>
</div>
<br />
<b>How you are feeling:</b><br />
<div>
<br /></div>
<div>
I'm feeling better than I was two hours ago!</div>
<div>
<br /></div>
<div>
<br />
<div>
<b>How you are believing:</b></div>
<div>
<br /></div>
<div>
I believe the Word is all I need!</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<b>What's happening in your life right now:</b></div>
<div>
<br /></div>
I'm in training for CSC so that I can better acclimate to the systems. I am going to work OT throughout the week after training to help with the OOP Caseload. I'm going to go get ready now!<br />
<br />
<br />
DW</div>
