---
title: 'Journal - 07/16/14 - *uhg *Promotion? *Blessing vs Burden'
date: '2014-07-16T11:51:00.0040000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3148259916414314855'
blogger_filename: '/2014/07/journal-071614-uhg-promotion-blessing.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
</h4>
<br />
<h3>
Daily Routine:</h3>
<h4>
BE STILL: Just Listen, write down what He tells you.&nbsp;</h4>
<div>
<b>What did God say today?</b></div>
<br />
<b>God Said:&nbsp;</b><br />
<br />
"Don't do that"... I did it anyway.... felt bad.<br />
<br />
And... I feel led toward my guitar. It's as though it's softly calling me, and I'm ignoring it... but it won't stop softly calling. I picked it up, played for a moment, it's a start I guess. <br />
<br />
<br />
<h4>
PRAYER: This is the time I do some talking, but still listening also.</h4>
<div>
<a href="http://biblehub.com/greek/1162.htm" target="_blank">Entreaties </a>(specific felt need),&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/4335.htm" target="_blank">Prayers </a>(exchange of desires/wishes),&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/1783.htm" target="_blank">Petitions/Intersessions</a>
 (Intersection of heaven and earth, hit the bullseye, request something 
specific of a King. Technical/Civil term: VERY specific requests that 
meet an exact need!).&nbsp;</div>
<div>
<a href="http://biblehub.com/greek/2169.htm" target="_blank">Thanksgivings</a> ( Lit: giving thanks for God's grace! Gratitude, Thankfulness)</div>
<div>
These are to be made on behalf of:&nbsp;</div>
<div>
<ul>
<li><b>FIRST </b>for <b>all people</b>, then <b>Kings</b>, <b>Leaders</b>, those in <b>Authority</b>, then you would be included in all men, so your family, kin folk, etc.&nbsp;</li>
<li><b>God desires all men to:</b> Be saved and come to the knowledge of the Truth.</li>
</ul>
</div>
<i><a href="http://biblehub.com/context/1_timothy/2-1.htm" target="_blank"><b>1 Timothy 2</b></a></i><br />
<div>
<i>1
 First of all, then, I urge that entreaties and prayers, petitions and 
thanksgivings, be made on behalf of all men, 2 for kings and all who are
 in authority, so that we may lead a tranquil and quiet life in all 
godliness and dignity. 3 This is good and acceptable in the sight of God
 our Savior, 4 who desires all men to be saved and to come to the 
knowledge of the truth. 5 For there is one God, and one mediator also 
between God and men, the man Christ Jesus, 6 who gave Himself as a 
ransom for all, the testimony given at the proper time. 7 For this I was
 appointed a preacher and an apostle (I am telling the truth, I am not 
lying) as a teacher of the Gentiles in faith and truth. 8 Therefore I 
want the men in every place to pray, lifting up holy hands, without 
wrath and dissension.</i></div>
<i><br /></i>
<b>Did anything else come up in prayer that should be notated?&nbsp;</b><br />
<i>Will do this in the car today.</i>
<i><br /></i>
<br />
<h4>
BIBLE: Instead of a bible devotional, I'm going to do a bible study.&nbsp;</h4>
<div>
Take one of Kenneth's study notes from the front of my bible and do those.</div>
<div>
JOURNAL entry will include all of the above, and anything else on my mind at the time. Take a moment to jot down:</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
No time today.</div>
<div>
<br /></div>
<div>
<h4>
JOURNAL: What's Up Today?&nbsp;</h4>
</div>
<br />
<b>How you are feeling:</b><br />
<div>
<br /></div>
<div>
Irritated. I get annoyed when the kids come in the morning. I just want to be alone for awhile, wake to my thoughts, etc. I'm learning part of this may be due to low dopamine.<br />
<br />
Sad. I still deal with unwanted sexual thoughts and desires. Things I know are not from God, but they persist. As I consider that issue, "Freedom Courses" come to mind. Maybe I need to spend some time going through freedom courses instead of watching TV with Flavia every night. Maybe she'll do them with me some nights instead. </div>
<div>
<br /></div>
<div>
<br />
<div>
<b>How you are believing:</b></div>
<div>
<br /></div>
<div>
I'm believing that I could have done more awful things when I was younger and had more fun doing them. That's a lie.<br />
<br />
I'm believing that my life is out of my control, that's a lie. I need to take time into my hands and tell it what I'll be doing.<br />
<br />
I'm believing my family is a burden, instead of the blessing they actually are. That's a lie too.<br />
<br />
<b>I'm believing that "there is promotion coming at work... sooner than I expected." That just come out of the God side of my spirit.... I'll have to pray about that on the way to work today. "It'll be just like Orange." </b></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<b>What's happening in your life right now:</b></div>
<div>
<br /></div>
I'm in training for CSC, which is kind of backward from OOP, but they said it'll be good to make me more well rounded as an RRR.<br />
<br />
WF likes their TLA's (Three Letter Acronyms). <br />
<br />
<br />
DW<br />
<br />
&nbsp;---------------------------------------------<br />
P.S.&nbsp; All that was written this morning before 7:00 am CT, there had been some conversation with Susan and Brandi (the two team leads) that someone would need to learn how to do reporting because Brandi was the only one who knew how. I also knew that Brandi had gone to some kind of interview recently... <br />
<br />
<h4>
Flash forward: Promotion is in the air!</h4>
At the very end of my day today I got news that Brandi will take Lydia's current role as manager over the cases and Lydia will handle the operations side, which will open up Brandi's role as reporting. So far, no one on the team has seemed particularly interested in doing reporting. Although someone could come from outside to do it, it really needs someone who has worked a few cases first. I've been listening to all of this and thinking that maybe in 6 months to 1 year I could move up into a role like that. <br />
<br />
So when I came to Brandi and Susan today to say hello, and congratulations, they both turned to me with an interesting look on their face and said: "How do you feel about reporting?" Of course, I love reporting, excel, and nerdy things like this so I said, sure, sign me up! I was then informed that if I took over this role officially it would involve applying for the position and interviewing, and... a raise... This is starting to sound like Orange... like I said this morning. That WAS fast!<br />
<br />
So I don't have anything official, it was all just talk. But I'll take it, combined with prayer this morning, to heart and ponder and pray about these things. Let it happen, don't force it, but don't back away and shy away either. 9:15 pm CT <br />
<br />
<br />
<br />
<br />
<br />
<br /></div>
