---
title: '2014/05/10 Journal Sat'
date: '2014-05-10T11:48:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '270844893633522534'
blogger_filename: '/2014/05/20140510-journal-sat.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

Yesterday... I turned in my key, badge, parking pass, etc. It was my last day at Westlake Sales. I'm using my floating holiday today. Monday marks a new beginning.<br />
<br />
I'm not sure how I feel about it. I read through some of the reports that will be like I'll be doing. It sounds like there are some tough phone calls with angry people ahead. But at least I'm not going to be selling things to some person who has nothing and wants nothing. Sales is evil.<br />
<br />
We're re-arranged the entire house. My new office is back where it was before, but it's put together differently. I have a window next to me, which is nice today, especially because I planted a better garden there now. I need to do the lawn though.<br />
<br />
I'm working on studying Job still. I Keep getting more and more insight. Very cool book.<br />
<br />
I'm going to stop writing now and join my family.<br />
<br />
It's mothers day tomorrow, and we ACTUALLY got something! Yeah, only ten years of marriage and I'm starting to get things going.<br />
<br />
<br />
Darrell