---
title: '2014/01/13 Journal Monday'
date: '2014-01-13T14:08:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1126292895873500708'
blogger_filename: '/2014/01/20140113-journal-monday.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
What's Happening:</h4>
<br />
Flavia may have strep. We're going to be proactive and deal with it now instead of waiting until it gets so bad that she's crying. I'm proud of her for taking care of it early.<br />
<br />
I'm staying home from work for that today, I was already thinking of calling out tomorrow because my mom is coming into town early and I don't want to leave Flavia to her alone. So I'll just stay home both days.<br />
<br />
Kids are recovered, mostly, from their coughs and sniffles. High Energy is back in the house. As I wrote that sentence I heard one of them cough. And now the other one is coughing.<br />
<br />
<h4>
Feeling:</h4>
Not happy for all the sickness in the house. Happy that it's not as bad as it could have been. Happy not to be at work. Nervous about the immediate future. I need to get a better job and make more money. Hopeful about 2014. If I keep my writing up I could eventually replace my real job with online work. I need to look into Niche Sites.<br />
<br />
<h4>
Thankful:</h4>
Thankful for Michael Hyatt and Patt Flynn and Gateway and Bob Hamp.<br />
<br />
Thankful for the Blood of Jesus that healed us!<br />
<br />
<br />
DW<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />