---
title: '2014/01/14 Journal Tue'
date: '2014-01-14T14:39:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7707639804750107355'
blogger_filename: '/2014/01/20140114-journal-tue.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
</h4>
<h3 style="text-align: center;">
2014 is my year for Double!&nbsp;</h3>
<ul>
<li>I want to double my income,&nbsp;</li>
<li>I want to double my quality of relationships,</li>
<li>I want to double my spiritual growth.&nbsp;</li>
</ul>
<br />
<div>
<br /></div>
<h4>
What's Happening?</h4>
<br />
Mom's in town, came in last night. She finds Ryan quite humorous. I wonder if it's because he is, or because she wants him to be. I felt myself not laughing in the car when she was laughing hysterically. Am I too serious for my own good? I felt like my Dad when he smiles and says "That's Humorous" when everyone else is laughing.<br />
<br />
I think I'll try to be more calm, relaxed, open around her this week than previous visits. At least I'll work on that.<br />
<br />
I'm meeting Jack tomorrow at Gateway NFW. That could be a great place to meet and talk. More comfortable than Starbucks. In fact, that may even be a great place for a <a href="http://www.thesuccessalliance.com/what-is-a-mastermind-group.html" target="_blank">Mastermind Group</a>.<br />
<br />
<br />
<h4>
Feeling</h4>
I'm feeling like I don't want to come out of my office, but that's not new. Like the winds of change are blowing softly and picking up speed. 2014 is my year for Double! I want to double my income, double my quality of relationships, and double my spiritual growth.<br />
<br />
<br />
<h4>
Thankful</h4>
I'm thankful for this journaling. It's given me a real sense of movement. I'm moving forward internally, which will have powerful external results.<br />
<br />
Thankful for my mom. Thankful for nature sound effects. Thankful for the Holy Spirit leading and guiding me, even when I don't feel it.<br />
<br />
<br />
dw