---
title: '2014/02/15 Journal Sat'
date: '2014-02-15T13:03:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2641833517802648350'
blogger_filename: '/2014/02/20140215-journal-sat.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">Day 95</a><br />‘I Am Who I Am’<br />Exodus 3:14<br />14And God said to Moses, “I am who I am.”…<br />Whatever your challenge is today, whether it is physical, emotional, financial or marital, the great I Am declares to you: “I am to you what you need Me to be.”</blockquote>
<blockquote class="tr_bq">
Are you groping in the dark, not knowing what to do? He says, “I am the light of the world. (John 8:12) When you walk in Me, you will not walk in darkness, but will have the light of life.”&nbsp;</blockquote>
<blockquote class="tr_bq">
Are you looking for a way out of a bad situation? He says, “I am your deliverer. I will reach down from on high, take hold of your hand and draw you out of the deep waters.” (Psalm 18:2, 16)</blockquote>
<h4>
Thankful:</h4>
I'm thankful for my God! He loves me! He isn't holding me back He is preparing me to propel forward!<br />
<br />
<br />
<h4>
Feeling:</h4>
Hopeful. I feel as though I'm on the verge of something grand and Satan would try to distract me from seeing it. I choose to expect greatness this year! 2014 will NOT be like every other year. In previous years I start out a project with hope and then loose gas. This year I press in.<br />
<br />
<h4>
What's Up?</h4>
AAA called yesterday afternoon. They did not accept me for the inbound position. But would be willing to do another assessment and another interview for a similar outbound position.<br />
<br />
It's outside my comfort zone to do outbound. But maybe I need to look outside my comfort zone. So far my comfort zone has paid me $32,000 base salary. I've turned down more opportunities than I applied to because they were outside my comfort zone. Then it occurred to me yesterday that<br />
<br />
<blockquote class="tr_bq">
I can only have what I do not have if I do what I have not done! Darrell G. Wolfe</blockquote>
<br />
<i><br /></i>
<i>PS: Apparently Flavia actually likes this Valentines thing. So I guess I'll have to start observing it for the first time in my life.&nbsp;</i><br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />