---
title: '2014.01.08 Journal Wed'
date: '2014-01-08T13:28:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '9119097357951593135'
blogger_filename: '/2014/01/20140108-journal-wed.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
Thankful</h4>
I am thankful for:<br />
<br />
<ul>
<li>The blood of Jesus, washing away my past be that 30 years or 30 seconds.&nbsp;</li>
<li>The Holy Spirit leading and guiding me, actively</li>
<li>Sex... lot's of sex...</li>
<li>My kids and how awesome they are!</li>
<li>Friends and Mentors</li>
</ul>
<br />
<br />
<h4>
Feeling</h4>
I'm feeling... excited to meet with Jack today. We always have such good talks. Happy I'm actually enjoying sex for the first time in years. Happy that I understand some more about why I didn't enjoy it before (after listing to Andrew Womacks series on the family "Sex in Marriage" message.<br />
<br />
Feeling like a sponge that can't absorb enough. I've been absorbing for months/years. Now it's time to give out in these blogs and other projects that I'm about to take on... whatever those might be.<br />
<br />
<br />
<h4>
What's happening right now</h4>
<div>
I'm meeting with Jack today. Not sure what we'll talk about. More than likely at least talk about marriage, work, and discuss more about the master mind group... and whatever else he brings to the table.&nbsp;</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
Darrell</div>
<br />
<br />
<br />
<br />
<br />
<br />