---
title: '2014/03/04 Journal Tue'
date: '2014-03-05T04:19:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7839373229949253656'
blogger_filename: '/2014/03/20140304-journal-tue.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h3>
WELL....&nbsp;</h3>
<h4>
Let's just recap the day at the end shall we?&nbsp;</h4>
<br />
<br />
I woke up barely on time. Had an awful headache. Felt semi-sick. Had to go potty but couldn't. Left early to take a blanket to a lady as a baby present, due in a few weeks. Flavia's first quilt! She REALLY likes quilting!<br />
<br />
By the time I got there I was glad she didn't answer the door because I wasn't feeling well. I took the bag and hung it from her door.<br />
<br />
I got to a nearby gas station/jack in the box... went potty... then walked around outside in the breath-visible cold, which actually helped me quite a bit. I used to stick my head in the freezer when I didn't feel good when I was young.<br />
<br />
Anyway, I threw up in the bushes and usually that starts the feeling better process... this time it didn't really. I felt a tad better, not as much as usual...<br />
<br />
I came home and took an epsom salt bath, took lot's of medication, even one of of the Tylenol/Codines left over from Flavia's root canal a few weeks/months back. Fell asleep on the bed. Woke up an hour later feeling better in the head, but neck still stiff.<br />
<br />
Finally decided to leave with Flavia to get some signatures done for the Mortg Modification that didn't get done right. Felt a tad better, went to library, fed ex, kfc, mcd's, braums, home.<br />
<br />
No it's 10:15 PM, kids are in bed, I watched some video's on how to replace a fuel pump in a 1995 Ford Escort Wagon. AutoZone is the BEST place to buy stuff from, their website and user experience is so superior to other places. They all cost the same, but the user experience is the best! I even got a $25 gift card for ordering ship-to-home online and not going in.<br />
<br />
My neck is STILL feeling a bit tight. Just took a half of a muscle relaxer I had left over from a previous order 1.5 years ago, three ibuprofren, and one tylenol.<br />
<br />
Now I'm going to bed, going to read a new (old) Bill Myers book from the library and go to sleep before 11! How about that?!<br />
<br />
Thank you Jesus for caring for me today... when I couldn't care for myself.<br />
<br />
<br />
DW