---
title: '2014/06/18 Wed Journal  -  Food....'
date: '2014-06-18T11:36:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1796971014448346454'
blogger_filename: '/2014/06/20140618-wed-journal-food.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

It's Wed morning. I woke up thinking about my cases at work. Funny how your mind can process things. I think I'll be caught up this week, unless someone else suddenly quits.<br />
<br />
Preston's Sweet Potato is growing rapidly!<br />
<br />
My Avocado seed split, but it hasn't done much else. I put a new one in with it.<br />
<br />
Flavia is VERY serious about getting fit. She had three weeks of eating right before my fast. She went on the juice only fast with me. But now she's going to continue the juice fast for another week or two. Then she'll transition into a juice/protein shake fast. Then she'll transition into a Juice/Protein shake, One meal plan. She's going to keep that up until she obtains her ideal weight/size. Then she's going to decide what her new "normal" will look like. Making room for a treat now and then, or a meal out with the kids, but not making those exceptions a lifestyle.<br />
<br />
It's pretty inspiring actually.<br />
<br />
I've decided to to try eat right by making as much of my diet as possible "Veggies and Fruit". I want to draft a new food pyramid to live by.<br />
<br />
<br />
DW