---
title: '2014/02/17 Journal Mon'
date: '2014-02-17T13:43:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3900249045411155222'
blogger_filename: '/2014/02/20140217-journal-mon.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

I HATE Mondays<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?user_id=darrellwolfe" target="_blank">Day 97</a><br />Jesus — King And Lord Over The Storm<br />Matthew 14:27<br />27But immediately Jesus spoke to them, saying, “Be of good cheer! It is I; do not be afraid.”<br /><span style="background-color: #eeedeb; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12.222222328186035px; line-height: 24.000001907348633px;">Are you going through a dark, difficult moment in your life? Perhaps the storm just rages on with no let-up and you are trembling in fear. You feel that any time now, you may just cave in and go under because you cannot beat this storm.</span><br />...<br />And as you behold Jesus, you become like Him. You will find yourself doing things you did not know you could do. You will, like Peter, walk on water. This happens when you are occupied with the person of Jesus, with His resources, love, wisdom, ability, power and majesty.<br />My friend, even during the times when you take your eyes off Jesus, He never takes His eyes off you. And when you cry out to Him, He will immediately stretch out His hand to catch hold of you. You will not go under.<br />There may be times that you are not able to find your way back. Jesus will then hold your hand and walk you back to the boat. And like Peter, you will realize that with your hand in His, the storm will come to a standstill!</blockquote>
<h4>
Feeling:</h4>
??<br />
<br />
My head hurts. Most of yesterday evening I began pondering what it would take to up my life insurance to a large enough amount to set Flavia up for her lifetime. Then I would drive my car off a cliff or something, make it look like an accident. Of course, that wouldn't work because there ARE no cliffs in Texas!<br />
<br />
<br />
I'm tired. It seems like every decision I make is wrong. This feeling started after a fight.<br />
<br />
I spanked Connor with my belt because he was throwing a fit because he didn't get his way, in what I felt was a calm manner, the same we do at home with the stick. She said that it's not the same. I don't know why still.<br />
<br />
The spanking all rooted from him asking over and over and over to go see Mommy in the store. I kept telling him to stop asking and he kept asking more.<br />
<br />
My phone battery died, and I parked the car in the same area I dropped her off at. Logically she would come find me parked where I dropped her off. Instead she walked all over the other areas of the parking lot looking for me and didn't at least start by walking the area she got dropped off at. Then got mad because I wasn't parked out front.<br />
<br />
The message yesterday by Jimmy Evans was about marriage and empathy. Identifying with how the other feels. Flavia said maybe it was the Holy Spirit telling me through Connor that she was going to be looking for us. She wondered why I would sit there in the car with a dead phone battery and not come out and get her attention or find her. I figured coming out and finding her was worse because now we are all wondering this whole store looking for her and she's wondering around looking for us.<br />
<br />
But, as usual, I'm wrong. She's right. Connor wanting to find her was obviously the Holy Spirit trying to communicate. If I can't get at least that by now, maybe I ought to just quit. If not kill myself, at least leave, like her Dad did when she was young. Maybe she doesn't know how good she had it not having him. Maybe him leaving was the best thing that ever happened to her. Maybe he just knew that he was inept as a Father. Maybe I need to leave and get out. WAY out. Different country out.<br />
<br />
<h4>
Thankful:</h4>
<div>
Actually I'm NOT thankful for much of anything right now. Except this passage from Joseph Prince Devotional pasted above. Like the disciples I'm on a storm, feeling like I'm near death. The blogs are feeling pointless. My cubicle at work is a coffin. My relationships with Flavia and the Kids are strained at best. I have no friends, other than Jack who I see once a month. I wish a plane would drop out of the sky and land on me, obliterating me instantly.&nbsp;</div>
<div>
<br /></div>
<div>
But... There is this hope, very light expectation, that Jesus might actually show up in my life and do something.&nbsp;</div>
<h4>
What's Up?</h4>
My question: Is it possible for me to make a decision that is the right decision without Flavia making it for me?<br />
<br />
<br />
I'm sure by tomorrow I won't feel this way. But I feel this way at least once a month.