---
title: 'Journal - July 6, 2014 - Post SWBC2014'
date: '2014-07-06T16:05:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '9139652833486565786'
blogger_filename: '/2014/07/journal-july-6-2014-post-swbc2014.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h3>
<i style="font-weight: normal;"><b><span style="font-size: large;">If you have ever had a vision from God, you may try as you will to be satisfied on a lower level, but God will never allow it</span></b></i></h3>
<h4>
<br /></h4>
<h4>
BE STILL</h4>
<br />
Lord: I'm going to teach you how to encourage you son, and in turn how to be encouraged.<br />
<br />
My son belongs to God, not me. I have been given the honor to shepherd this child. If I cannot shepherd one child, if I cannot shepherd one family: I cannot shepherd a people; big or small.<br />
<br />
Connor came in to talk to me as I was getting this revelation, and I felt annoyed and interrupted; which is how I often feel when he comes to talk to me because I'm always doing something that he's going to have to interrupt if he's ever going to talk to me. I cut him off, told him it was my prayer time and sent him away question unasked. It's not that it's wrong to tell him "not now", but HOW I told him was wrong. Instead of leaving edified, encouraged to spend time praying himself, he left feeling discouraged, like "as usual, Daddy doesn't listen to me".<br />
<br />
How do I start becoming a better contributor to this house? It starts with practicing gratitude. I need to practice saying out loud all the things I am grateful for about this family, instead of meditating on all the things I don't like. (which is what I've been doing - to be honest).<br />
<br />
I need to start an It Is Written Journal. It would be full of scriptures that I hand write and carry with me. It's not for taking notes, or any other purpose, only for scriptures that I need to carry, meditate one, and confess.<br />
<br />
I need to start doing the former things I let slip. Recently and in time past.<br />
<br />
I need to put my routine back together that I had for a whole two weeks until I let that slip.<br />
<br />
<h4>
Routine: All in one journal entry</h4>
<ul>
<li><b>BE STILL</b>: It must start with BE STILL before going to writing, bible devotional, or other things. Prayer will be involved, but it will be listening, not speaking.&nbsp;</li>
<li><b>PRAYER</b>: This is the time I do some talking, but still listening also.&nbsp;</li>
<ul>
<li>Prayers, Petitions, and Thanksgivings be made on behalf of: FIRSTLY&gt;</li>
<ul>
<li>For all people</li>
<li>Then Kings, Leaders, Those in Authority</li>
<ul>
<li>SO THAT we may lead a tranquil and quite life in all godliness and dignity.&nbsp;</li>
</ul>
</ul>
<li>God desires all men to:</li>
<ul>
<li>Be saved</li>
</ul>
<br />
<ul>
<li>Come to the knowledge of the Truth.&nbsp;</li>
</ul>
<li><i><a href="http://biblehub.com/context/1_timothy/2-1.htm" target="_blank"><b>1 Timothy 2</b></a></i></li>
<li><i>1 First of all, then, I urge that <a href="http://biblehub.com/greek/1162.htm" target="_blank">entreaties </a>and <a href="http://biblehub.com/greek/4335.htm" target="_blank">prayers</a>, <a href="http://biblehub.com/greek/1783.htm" target="_blank">petitions </a>and <a href="http://biblehub.com/greek/2169.htm" target="_blank">thanksgivings</a>, be made on behalf of all men, 2 for kings and all who are in authority, so that we may lead a tranquil and quiet life in all godliness and dignity. 3 This is good and acceptable in the sight of God our Savior, 4 who desires all men to be saved and to come to the knowledge of the truth. 5 For there is one God, and one mediator also between God and men, the man Christ Jesus, 6 who gave Himself as a ransom for all, the testimony given at the proper time. 7 For this I was appointed a preacher and an apostle (I am telling the truth, I am not lying) as a teacher of the Gentiles in faith and truth. 8 Therefore I want the men in every place to pray, lifting up holy hands, without wrath and dissension.</i></li>
</ul>
</ul>
<ul>
<li><b>BIBLE</b>: Instead of a bible devotional, I'm going to do a bible study. Take one of Kenneth's study notes from the front of my bible and do those.</li>
</ul>
<br />
<ul>
<li><b>JOURNAL </b>entry will include all of the above, and anything else on my mind at the time. Take a moment to jot down:</li>
<ul>
<li>How you are feeling:</li>
<li>How you are believing:</li>
<li>What's happening in your life right now:</li>
</ul>
</ul>
<br />
<blockquote class="tr_bq">
<div>
<br /></div>
</blockquote>
I created a template from this. I'll use it tomorrow!<br />
<br />
<br />
<h4>
What's Up Now?&nbsp;</h4>
<br />
Yesterday was the end of the SWBC2014. Flavia went all week and was pumped until I went with her. I dragged her down so much while I was there that she didn't want to go Sat, and sent me alone with the kids.<br />
<br />
I feel as though some real seed was planted, I just need to cultivate that seed. There may be little outward evidence that anything happened there... but I feel a subtle stirring inside. I'm SO tired of being half/half.<br />
<br />
I'm living half (80%) like the World. I'm not drinking, smoking, or sleeping around. But I watch many of the same things on TV, I get up and get ready and run out the house, just like they do, I'm learning to eat a little better, but so do they. Other than the list of things I don't do, there's not a whole lot of noticeable difference between them and I.<br />
<br />
The other half, (20% to be honest) is the one that reads the bible... occasionally, goes to church most of the time, but doesn't serve anywhere, and feels annoyed when I'm asked to.<br />
<br />
I'm simultaneously seeking God one day, and resisting Him the next. I'm almost back where I was in 2002 just before sitting on that rock in Gaviotta. Resisting God's call... mad at God for what I've had so far that I perceive He gave/did to/for me. I'm walking in such confusion that I can't tell which parts were God and which parts were an attack of the enemy.<br />
<br />
I'm basically dead, waiting to die, or get raptured. I feel like going to heaven now with no reward to show would be better than staying here. I'm accomplishing nothing by breathing.<br />
<br />
So... I guess it's time to make another decision. To live is Christ/Anointing to die is gain. However, God's assignment on my is far from over. So to leave now would be quitting on Him. And quiting on Flavia and the kids.<br />
<br />
Something Kenneth said last night has stuck with me. Satan knows how to hit your buttons. He'll keep hitting the same ones as long as they work. Money is one of my big buttons. Just mention bills and my head starts to hurt, and I get dizzy and confused, and I start to try to come up with schemes on how I could make more money. I've worked so many second jobs and OT in the last ten years, and I have virtually nothing to show for it all. I've been married ten years and I'm still behind on bills and driving a junk car. It's a decent junk car, but it's not "NICE".<br />
<br />
It's time I actually learned how to walk in Faith. I'm not even sure what that means anymore, but it's time to do it.<br />
<br />
Time to go see the family!<br />
<br />
DW<br />
<br />
<br />
<br />
<a href="http://utmost.org/" target="_blank">My Utmost For His Highest: July 6. 2014</a><br />
<br />
<blockquote class="tr_bq">
<i>The vision that God gives is not some unattainable castle in the sky, but a vision of what God wants you to be down here. Allow the Potter to put you on His wheel and whirl you around as He desires. Then as surely as God is God, and you are you, you will turn out as an exact likeness of the vision. But don’t lose heart in the process.</i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i><b><span style="font-size: large;">If you have ever had a vision from God, you may try as you will to be satisfied on a lower level, but God will never allow it.
</span></b></i></blockquote>
<br />
<br />
<br />