---
title: '09/28/14 | Weekly Review'
date: '2014-09-29T04:54:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5292701456291015506'
blogger_filename: '/2014/09/092814-weekly-review.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h3>
The Week of 09/28/14</h3>
<br />
Well let's see... <br />
<br />
I had a five day weekend for Preston's Birthday and Mom's visit from Thur 09/18 through Mon 09/22. Flavia and the boys took mom to the airport on Tue. Thus began another week at the office. As usual, we're under handed, and I took more cases than I wanted to, but it worked for some extra hours.<br />
<br />
Planning for something similar this week. Time to wrap up the cases I have, and prepare for the big month end reporting.<br />
<br />
Speaking of reporting, I interviewed for the reporting position. Do they realize how nerve racking a five person panel interview is? And what's with the questions about "how I'm better than others..."? Brandi says I did fine. I think she said good, actually. I'm not sure. JoAnn is expecting the new position to be mine, I'm 3/4 expecting it.<br />
<br />
I'm not sure how to expect anything, accurately. Faith and I are on rocky terms... Grace however... Grace is working something new in my life.<br />
<br />
Did you know Satan has two primary weapons again us? The knowledge of Good and the knowledge of Evil. We all know what evil we ought to avoid, or at least, we try to be aware of it. But do we realize that when he's pushing us from behind to try harder, try harder, try harder, do more, do more, do more... that's ALSO the tree of the knowledge of good and evil.<br />
<br />
Jesus didn't come so that we would be able to do better... He came that we might have life, and have life in more and more abundant quantities.<br />
<br />
Also... The Kingdom of God is like an oven. When you enter the atmosphere of the King, the power of His presence is applied to you by your merely being there and you are changed.&nbsp; You don't become more like Jesus by knowing more... the pharisees tried that. Saul was killing Christian's when he know the ot-bible better than most of us. It wasn't until he was subjected to The Presence that he was changed into something new.<br />
<br />
The purpose of prayer and worship isn't so that we can check off that we did it, like a religious exercise. The purpose of prayer and worship is so that we can enter His Presence, and be exposed to His Atmosphere, and be changed. The cookie dough can't try to become a cookie, no matter how much it wants to. It can only become a cookie by prolonged exposure to the atmosphere of the oven.<br />
<br />
Darrell<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />