---
title: '2014/01/28 Journal Tue'
date: '2014-01-28T13:27:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5565397013713490422'
blogger_filename: '/2014/01/20140128-journal-tue.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
Colossians 2:10<br />
10and you are complete in Him, who is the head of all principality and power.&nbsp;</blockquote>
<blockquote class="tr_bq">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?user_id=darrellwolfe" target="_blank">Joseph Prince:&nbsp;</a><span style="background-color: #eeedeb;">I used to think that I had to ask God to make me more patient, until I realized one day that Jesus is my patience. Since then, I no longer ask God to make me wiser either, because Jesus is my wisdom. (1 Corinthians 1:30) I am not waiting to receive more healing because Jesus is my complete healing at this moment. And I am not yearning for peace and rest one day because Jesus is my peace and rest today. Right now, I have everything because I stand complete in Christ!</span></blockquote>
<br />
<br />
<h4>
Thankful:</h4>
I'm thankful for this new routine, and looking forward to going to bed on time and starting it earlier.<br />
<br />
<h4>
Feeling:</h4>
Feeling rushed because I got up late. Excited because strange things are happening.<br />
<h4>
What's Up?</h4>
Joshua Estes found me night before last on Facebook! I've been looking for him for YEARS! And praying for him. It's nearly Erie how similar our lives have been in the last 12 years.<br />
<br />
<br />
<ul>
<li>We both had a failed first marriage, with the girl having multiple affairs and asking for a divorce.</li>
<li>We both remarried shortly after (within a year or two of the first)</li>
<li>We both had two boys</li>
<li>We both married women who were only children raised by a single mom.</li>
<li>We both worked for the same company for the past 8 years (not the same company as each other, but that we didn't move around within our respective companies)</li>
<li>We both worked for that company in two states.&nbsp;</li>
<li>I think there was some other things... but that was weird!&nbsp;</li>
</ul>
<div>
Africa keeps coming up. I may need to keep an Africa Log.&nbsp;</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />