---
title: '2014/01/22 Journal Wed'
date: '2014-01-22T16:13:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5321980963988258228'
blogger_filename: '/2014/01/20140122-journal-wed.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
Thankful</h4>
<br />
For waking up on time. Mom needs to be at airport by 4 am ish.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
Feeling</h4>
Amazingly awake for this time of morning!<br />
<br />
<br />
<br />
<br />
<h4>
What's happening right now</h4>
<br />
Taking mom to airport today. Then I'm having an interview with AAA today at 9am. I got an email from yelp, weekly digest saying they are hiring in Fort Worth.... intriguing...<br />
<br />
<br />
<br />
<h4>
1/22/2014 02:50 AM Journal</h4>
<h4>
Thankful for waking up early and not being late to take Mom to the airport</h4>
<h4>
</h4>
<h4>
Feeling amazing to be this awake.&nbsp;</h4>
<h4>
</h4>
<h4>
Happening. Interview today.</h4>
<h4>
&nbsp;</h4>
<h4>
Interviewer never called. Hmm...</h4>
<h4>
</h4>
<h4>
I have two blog posts scheduled for dw, Tomorrow I work on lif, and get ahead of that curve.&nbsp;</h4>
<h4>
</h4>
<h4>
</h4>
<h4>
VOD:</h4>
<h4>
Hebrews 5:7 HCSB</h4>
<h4>
</h4>
<h4>
During His earthly life, &nbsp;He offered prayers and appeals &nbsp;with loud cries and tears &nbsp;to the One who was able to save Him from death, and He was heard because of His reverence.</h4>
<br />
<br />