---
title: '2014/01/17 Journal Fri'
date: '2014-01-17T14:25:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1633425552996505219'
blogger_filename: '/2014/01/20140117-journal-fri.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
Thankful</h4>
I'm thankful for a sense of purpose and motion. My bills aren't any less overdue. My job is still with Wells Fargo... but I did do that AAA assessment for a possible interview. But I feel like my purpose, to be writer, is focused for 2014 now. Thanks in large part to Flavia who helped me see it.<br />
<h4>
Feeling</h4>
Feeling hope.<br />
<h4>
What's happening right now</h4>
Flavia and I have been married 10 years as of today! And I still failed to buy her a present or card. I feel like she controls the check book and I'm never without her. So it's hard to do anything that she isn't there to see me doing it. But that's an excuse, not a very good one either. I need to do like nike and "Just Do It".<br />
<br />
Mom and kids have done something for our anniversary because they told us not to come in the kitchen.<br />
<br />
And now... let the day begin! lol dw<br />
<br />
<br />
<br />
<br />
<br />
<br />