---
title: '2014/05/30 Fri Journal'
date: '2014-05-31T03:54:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4294965890966394397'
blogger_filename: '/2014/05/20140530-fri-journal.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<p>That ends week 3.</p>
<p>The new job is still keeping my mind engaged learning. I feel like there is enough new substance here to feed my mind with something new to learn for some time to come. At the same time I anticipate being settled into a routine quickly so that I can put my mental energy back on home and blog.</p>
<p>Speaking of blog. Seth Godin today said that its not about a race to the lowest prices... but the best rewards belong to those who create products then say boldly: "It's not the cheapest but it's worth it!" and then back it up with exceeded expectations.</p>
<p>I want to start believing in my product that way, and I feel that the practice of writing for corporate America will give me more skills to do just that. Create written material that conveys the message without missing anything but while also not fatiguing the reader.</p>
<p>Hhmmm.<br>
.<br></p>
<p>PS Connor and I discovered today that Faith is like an letter.</p>
<p><u>Dw</u><br></p>
