---
title: '2014/01/29 Journal Wed'
date: '2014-01-29T20:28:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3858417830782644698'
blogger_filename: '/2014/01/20140129-journal-wed.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
Deuteronomy 28:3<br />3“Blessed shall you be in the city, and blessed shall you be in the country..."&nbsp;</blockquote>
<blockquote class="tr_bq">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=78&amp;user_id=darrellwolfe&amp;version=1" target="_blank">Joseph Prince Devotional Excerpt:</a>&nbsp;You get blessed because you believe God for it. It has nothing to do with your boss or the company.<br />Why then don’t you seem to see the blessings?<br />My friend, if you don’t see the blessings, check what you have been believing and saying. Some people complain and blame everyone and everything around them — their parents, race, gender, environment and government — for their lack of blessings. Beloved, I want you to believe and confess that you are blessed because of Jesus’ finished work on the cross, not because you are of a certain race or work in a certain place.</blockquote>
<br />
<h4>
Thankful:</h4>
I'm thankful for the healing power of the Blood of Jesus!<br />
<br />
<h4>
Feeling:</h4>
... Not sure... happy... i love my wife, she is awesome and beautiful and is always right.;...<br />
<br />
<br />
<h4>
What's Up?</h4>
My mom is in the hospital... yes that's right. My MOM! Ryan just got out, and now she's fractured her ankle and is going in for surgery in the next few minutes... sigh... my family and their drama happenings. Tragedy follows them. Because they talk negative so often. I need to STOP talking negative too! <br />
<br />
AH! Bill Hybels did a message on how you calendar can change you destiny. Mom didn't listen to the inner witness telling her to go to the hotel before Ryan's surgery. Then failed to set her alarm clocks and missed Ryan's surgery. So she ends up coming out here, and going back, adding a week to her vacation time, to take Ryan to a second scheduled surgery. Now, only days later she falls and breaks her ankle and has to go in for surgery herself. SO now she can't go back to work for 6 MORE weeks, at least.<br />
<br />
So, to recap, all because she didn't listen to the Holy Spirit telling her to get a hotel (didn't want to spend money and felt lazy that evening to drive) and because she didn't set her alarms, failure to pay close attention to time and schedule, she has added 7 plus weeks of hassles, a surgery for herself, months of pain and recover (barring any divine intervention on that front) and who knows what other delays will come of it.<br />
<br />
Schedule is the most powerful thing in your control!<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />