---
title: '2014/02/02 Journal Sun'
date: '2014-02-02T12:52:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7384401142071833113'
blogger_filename: '/2014/02/20140202-journal-sun.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<p>VOD<br>
In every thing give thanks: for this is the will of<br>
God in Christ Jesus concerning you. - 1 Thessalonians 5:18</p>
<p>We give thanks FOR the victory IN the trial... not FOR the trial.</p>
<p>Thanks<br>
I'm thankful for this AAA opportunity whether it turns out to be God's open door or just another red Herring. </p>
<p>I'm thankful that God is my provider not myself.</p>
<p>Feeling...<br>
Apprehensive but intrigued. As I've looked for new jobs Insurance has come up time and time again. Many of those programs just wouldn't have worked. Too much investment for too little immediately return. This one will provide immediate increase in income. And then only requires a one year commitment. I could bluff my way to success for that long... lol But I've always done reasonably well in every job, this would be no different. The only real question is would I be willing to make outbound calls? And are there any other surprises?</p>
<p>What's up?<br>
Some talk of ice may be on the road today, but its time to get ready for church.</p>
