---
title: '2014/02/12 Journal Wed'
date: '2014-02-12T14:32:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3292481669830764087'
blogger_filename: '/2014/02/20140212-journal-wed.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">JPDevo</a>Exodus 14:15–16<br />
15And the Lord said to Moses, “Why do you cry to Me? Tell the children of Israel to go forward. 16But lift up your rod, and stretch out your hand over the sea and divide it...<br />
<span style="background-color: #eeedeb; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12.222222328186035px; line-height: 24.000001907348633px;">Do you realize that Jesus did not say, “Go and pray for the sick”? He said,” Go and heal the sick.” (Matthew 10:8) So stop pleading and asking all the time, and start using the authority you have in Christ.</span></blockquote>
<br />
<br />
<h4>
Thankful:</h4>
I'm thankful for days off and not working OT right now. I'm thankful for this office. I'm thankful for the ability to decide to be thankful when my kids actually annoy me a bit sometimes.<br />
<br />
<h4>
Feeling:</h4>
I'm feeling pressure. I need out of the WF job. Actually I need to be self employed with ever increasing income. But I feel, sometimes, like I have no idea how to do this with a wife and kids constantly begging for my attention.<br />
<br />
<br />
<br />
<h4>
What's Up?</h4>
I hate my family today... I don't really hate them. It's more like they want more from me than I have to give? My wife comes out swinging 30 seconds out of the shower. "Why are you in your office? Are the kids fed? Dogs walked and fed? Did you do this? Did you do that?..." While I'm doing my journal... AAAHHHHH!! Jesus woman calm down! I just woke up a few minutes ago!<br />
<br />
So... now it's hours later and I'm back to my journal. I'm going to have to figure out something that will work for her. Because she hates me in this office. And I hate me outside of it. Maybe with a new schedule Sunday through Thur schedule, I can leave really early and work on computer things for an hour or two before "Work". That way Fri and Sat are all family day!<br />
<br />
Maybe that would work. I feel like I have NO time to do anything with these blogs that I want to get up and running because she won't let me have a moments rest to do them. I need long blocks of time to work on them and she won't let me.<br />
<br />
On her side, I feel like she needs my attention. I've become her Bob Parr (see Incredibles). "BOB! I need you to engage!" And I keep pulling further and further away... as I long for something incredible.<br />
<br />
I wish I "liked" my family. I love them. I just don't enjoy being with them. I especially feel irritated every time the kids come show me a toy that look exactly the same as every other toy and I'm supposed to pretend it's exciting. I have to pretend I'm "happy to help" at work and pretend "I'm happy about their new widget" at home.<br />
<br />
I wish I could be like Bill Cosby. He seemed to engaged and interested in his kids and family. I realize that it was a TV show, but I want to be more like that... how do I get there?<br />
<br />
Sean is always bugging me about how he wants a wife and kids who want his attention. I'm always thinking I why?<br />
<br />
Maybe Jack can help me figure this out... It always seems to help.<br />
<br />
You know... as I think about it. There are times I really do enjoy my family wife AND kids. But it's usually the times when I don't feel pressure from them or the world. Maybe pressure is the key...<br />
<br />
I don't know. Darrell<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />