---
title: 'Journal Bite - July 19, 2014 - Baseball, Chess, Checkers and Sorry'
date: '2014-07-20T01:48:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5460825640921436617'
blogger_filename: '/2014/07/journal-bite-july-19-2014-baseball.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<h4>
MyGateway</h4>
SO, I didn't get up this morning and go to the meeting at Southlake Gateway for the MyGateway App volunteering meeting. I feel like I should go, I just keep not giving it any weight in my priorities. The fact is, I feel like I should go, but don't want to. In fact, I want not to. But I feel like I should, and that I'd enjoy it once I did... I'm afraid of the extra time commitment, I already feel rushed as it is. "Lord, Move me to Keller?!" (Less drive time for the new job).<br />
<br />
<br />
<h4>
Baseball, Chess, Checkers and Sorry</h4>
Connor and I had an us day, while Preston went with Mommy to the libraries and store. Connor has been frustrated, angry, irritable, etc. Today he tried to kick Preston's bike while he was riding it, which could have been very serious. When Flavia asked him to go to our room to calm down he threw his helmet at the wall. He's getting worse with his anger issues. How can I teach him to chill?<br />
<br />
Well, Flavia mentioned that although he must be discipline for his behavior, he may be reacting to us, as much as his brother. He continues to ask for quality time, and he is continuously pushed aside. "Go play, Go Read..." the message is "Don't bother me, leave me alone..."<br />
<br />
So Connor and I played Chess, Checkers, and Sorry. No matter how many times I play Sorry I still get frustrated with board games. But the other two were fun and Connor legitimately beat me at Chess two times. I let him beat me at Checkers because I wanted to build his confidence, I'm always picking at him and telling him where to improve, I felt he needed a win.<br />
<br />
Then we went outside to play catch with the baseball, and practice batting. He's getting better. If I could ever get him to focus, and pay attention to what others are doing and internalize that and emulate it, he might be a good player. He's not as intuitive as Preston is with sports, but he's twice as determined as Preston is to learn and grow.<br />
<br />
So it wasn't a bad day... even if it did start out in a funk. Getting out and mowing the lawn probably helped. I need to put some of Dr Gray's suggestions, about how to wake the body and make it be in the mood you want it to be in, to good use. <br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />