---
title: '2014/04/09 Journal Wed "No Word"'
date: '2014-04-09T15:19:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3490858610489907220'
blogger_filename: '/2014/04/20140409-journal-wed-no-word.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
COME:<br />
<br />
<blockquote class="tr_bq">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=148&amp;id=28-joseph-prince&amp;version=1" target="_blank">Isaiah 55</a><br />
<span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px; text-indent: 17px;">11</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 34px; margin: 0px; padding: 0px; text-indent: 17px;">So shall my word be that goeth forth out of my mouth: it shall not return unto me void, but it shall accomplish that which I please, and it shall prosper in the thing whereto I sent it.</span></blockquote>
<br />
<br />
HERE:<br />
<br />
God's Word is true, unchanging, and it accomplishes what it is sent to do.<br />
<br />
If I put my words and faith into God's Word it will come to pass.<br />
<br />
Faith is not just about saying something and believing it. Faith is about agreeing with what God has said.<br />
<br />
God has said I can prosper, and be healed. God has not SAID "You shall work at xyz place..." Can I have faith for a specific job?<br />
<br />
I'm thinking yes, because: God hasn't just spoken in his Book He speaks today.<br />
<br />
But now when I get out of the written Word I have to do two more things.<br />
<br />
<ul>
<li>I have to make sure I'm not hearing anything that conflicts with The Written Word.&nbsp;</li>
<li>I have to make sure I'm actually hearing GOD. That seems to be the tricky part?&nbsp;</li>
</ul>
<br />
<br />
HHmmm... It's been 12 years since I started studying this faith thing, and I still don't get it... This is frustrating.<br />
<br />
<br />
DO:<br />
<br />
I have no idea...<br />
<br />
<br />
<br />
<h4>
Thankful:</h4>
I'm thankful for my kids who are full of energy and life!<br />
<br />
I'm thankful for the ability to admit that I don't really know something as well as I thought I did, so that I can grow to understand it better.<br />
<br />
<h4>
Feeling:</h4>
I have a headache, mostly comprised of tight neck muscles. I need a chiropractor but can't afford it right now.<br />
<br />
<h4>
What's Up?</h4>
I Phone Screened for TDA on Wed March 12th. I interviewed for TD Ameritrade in person on Wed March 19th. I emailed Devida (the hr person) on the 19th and wanted some further information. She emailed me back that information on the 20th.<br />
<br />
I heard nothing so I emailed Devida and Monica on Thursday April 3rd saying I hadn't heard anything yet and I'd like to know if I could be of any further assistance or provide more information.<br />
<br />
It is now Wed April 9th. I've heard nothing. Neither approved, declined, we're still considering... nothing... from them since March 20th. So today is three weeks since the interview and tomorrow is three weeks since their last communication.<br />
<br />
Maybe that means I didn't get it. Maybe that also means communication is not their strong suit and maybe I should work there?<br />
<br />
But I really wanted to. I have a possible interview scheduled for today or tomorrow with Wells Fargo Dealer Services Ex Office as a research specialist. That could be interesting. But it's not the pay I wanted.<br />
<br />
Bother..........<br />
<br />
In other news, I have a garden to work on. So that's nice. Maybe I'll go to some of that today.<br />
<div>
<br /></div>
So I guess to wrap this up... I have no real concept of what Faith in the Word means... and I have no Word from TDA... so I guess I just have no Word. LOL.... I should spend some time in my Bible today...<br />
<br />
Peace! DW<br />
<br />
<br />
<br />
PS<br />
<br />
So I went and applied to four more positions from TDA today. One of them had the same title as the one I haven't heard back from yet. Within hours I get this:<br />
<br />
<blockquote class="tr_bq" style="background-color: white; color: #222222; font-family: Arial; font-size: 13px;">
Darrell Wolfe,<br />Thank you for your interest in the position Banking Operations Rep - Job Opening Number 102895 with TD Ameritrade. After careful consideration, we have decided to pursue other candidates whose qualifications more closely match the requirements for this position. This notification refers only to the above Job Opening number. If you submitted applications for multiple Job Openings (including positions with the same or similar job titles), you may still be in consideration for those positions.<br />Please continue visiting us at&nbsp;<a href="http://jobs.tdameritrade.com/" style="color: #1155cc;" target="_blank">http://jobs.tdameritrade.com</a>&nbsp;to review current job openings and apply for other opportunities. With the user name and the password that you provided when you initially applied for this position, you will be able to review and update your application and select new positions which you may be interested.<br />We thank you again for your interest in TD Ameritrade and wish you all the best.</blockquote>
So does that mean that they are still considering me for the first position? Or does it mean that something disqualified me for this position totally so that I can't even apply for the same title position at that company?<br />
<br />
Am I over thinking this?<br />
<br />
Probably... But I liked this one so much I stopped looking for another job. Oh well.. WF Dealer Services hasn't called back to schedule that other interview, so I guess I'll just keep looking. Back to the job site boards.<br />
<br />
This is SO depressing...<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />