---
title: '2014/02/04 Journal Fri'
date: '2014-02-14T12:37:00.0040000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '418480871984073907'
blogger_filename: '/2014/02/20140204-journal-fri.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
<h4>
VOD:</h4>
<blockquote class="tr_bq">
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">JP Devo</a>&nbsp;</blockquote>
<blockquote class="tr_bq">
<br />Matthew 26:26<br />26… “Take, eat; this is My body.”</blockquote>
<blockquote class="tr_bq">
Thought For The Day<br />Believe that Jesus is the true bread from heaven who took your cancer, diabetes and heart disease, so that you can have His supernatural health!1</blockquote>
<h4>
Thankful:</h4>
I'm thankful for my wife and children. Had a good day yesterday. Actually got work done, on an old laptop in the middle of the living room. Who knew I didn't need my office, in fact because I didn't have my office I got less distracted with other things.<br />
<br />
Those distractions are why I'm writing this at 6.33 AM and not 6:00 AM.<br />
<br />
I'm thankful for the ability to say NO to temptations!<br />
<br />
<h4>
Feeling:</h4>
Part of me had hoped to hear something from AAA yesterday. But I've decided to trust God. Not in a pathetic barely hanging on sort of way either. If God shuts this door I accept that His plan is bigger than mine.<br />
<br />
Flavia mentioned Real Estate. Note to self: Check that out more.<br />
<br />
<h4>
What's Up?</h4>
Met with Jack yesterday. As usual we talked about all sorts of random rabbit trails. If there was one theme it would be... Knowing where we are in time. Not doing everything you think you could do and doing instead those things you know you should do.<br />
<br />
I need to go to the ID seminar next time.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />