---
title: 'Pushing and Shoving  -  08/03/14'
date: '2014-08-03T12:45:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1488136801281936834'
blogger_filename: '/2014/08/pushing-and-shoving-080314.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
  - 'Feelings'
---

The kids came in and wanted me to see their book. Preston came in and laid on the pillows to see. Connor laid next to me. BUT, he kept shoving his way higher and higher, laying on Preston. Then, he says, that he was pushing because Preston wouldn't move his arm out of the way. He could have laid perfectly fine next to me, but he insisted on shoving his way up into his brother. I don't understand this child's perception of reality when he blames his younger brother for his own actions.<br />
<br />
I got angry and threw the book across the room and left. Wrong reaction. I listened to them fight and argue, and I watched Connor push and push to get his way and shove his way into things and try to take over all of yesterday. I don't know what to do with him, other than just take Preston to do things and tell Connor he can't participate at all if he's going to act this way?<br />
<br />
Flavia says it's because he gets in trouble even when it's Preston's fault. Maybe, but I don't see that. I discipline what I see and hear. Maybe I need to start by asking more questions to get behind what I see and hear, so He'll feel more "Listened" to? I wish he was just more gentle like his brother. Preston is so easy to get along with. Then again, Preston is more easy to ignore too. So without Connor pushing and shoving, maybe they'd both get less attention from their distracted father? I don't know what the solution is. The more they fight and argue the less and less time I want to spend with them. I've even had fleeting thoughts of sending the whole lot of them to live with JoAnn in ID, but then I correct that thinking as from the devil and push on through.<br />
<br />
I wish I ENJOYED family life. I hear other guys say they do. I'm trying to enjoy it. I'm purposing to spend time with them. I even played one of those awful board games the other day. I don't know how to change what I am to make this work. It may have to be a miracle intervention. Holy Spirit, do a DNA change in me to make me a man who enjoys the family you assigned me to... even when I asked you to be/stay single before this all started. DW