---
title: '2014/01/16 Journal Thur'
date: '2014-01-16T14:50:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8800030138192043709'
blogger_filename: '/2014/01/20140116-journal-thur.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
Feeling:</h4>
Tired, late nights with Mom in town. Renewed Hope, I have solved the pull between audio and writing, I got several confirmations yesterday that writing is my future for 2014, I got an email asking me to take an evaluation for AAA Sales and I've heard that they pay more and people are happier there. It's going to be an interested year.<br />
<br />
<h4>
Thankful&nbsp;</h4>
For my God who always comes through, often despite my doubt. He works to encourage me along. For Flavia who sees me, better than I see myself. For my Mom who loves me and my family. For my kids who really are great kids, I need to spend more time dedicated to them.<br />
<br />
<h4>
What's happening now?</h4>
<br />
Ha! It's great weather outside. Yesterday I got up early, went to prayer at Gateway NFW. Met with Jack in the morning. His friend Jim Delong (?) is a seer and he told me that "writers block will be a vapor to you, and you will write as one on fire." Jack and I had a great meeting, talked more about his projects and government. Had a great interview where I found I DO NOT want to be an audio person putting together equipment and tearing things down and setting them up over and over. I'm not an engineer I'm a creative.<br />
<br />
I don't admit this often... but I'm getting the feeling that part of my place is on stage, not just behind. I don't know if that's a 2014 thing though... we'll see.<br />
<br />
We went to Pei Wei and I got confirmation that I belong on this Texas Living Project. 2014 is my year to be a WRITER.<br />
<br />DW<br />
<br />
<br />