---
title: 'Alive - Again 07/15/1980 - 07/15/2015 - Present'
date: '2015-07-16T15:43:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3476961869685369591'
blogger_filename: '/2015/07/alive-again-07151980-07152015-present.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Life Events'
---

Well... I'm still here. Planet Earth. Home of headaches, back aches, heart aches, and hard labor. Home of weeds and thorns and things breaking all the time. Home of never enough of this and too much of that.<br />
<br />
Every day of my life.... as long I can recall... since before 10 years old... one thought has remained the undercurrent of my mind and heart. One thought has remained my deepest desire.<br />
<br />
I want to go home... to My Father's House, Planet Heaven.<br />
<div>
<br /></div>
That thought is not always conscious; but, it is always there. It's among my primary motivations. Someone once casually remarked how horrible it would be to jump from a plane and the parachute not open. Without thinking, I instantly remarked: "Are you kidding? That would be awesome! Painless death, instantly transported to my real home."<br />
<br />
No two seasons are more prone to illicit this thought, than January and July. Birth of the year, and birth of myself.<br />
<br />
Many mornings the undercurrent of thought I wake up to says: "I'm still here... Oh well !"<br />
<br />
I'm not suicidal. I don't plan to kill myself, or take unnecessary risks in an effort to cause death. I just wish I could be given permission to leave this stupid planet. I feel like I'm in prison, or in school (same difference) waiting for permission to graduate or be released.<br />
<br />
Paul was faced with this same dilemma:<br />
<blockquote class="tr_bq">
<i><a href="http://biblehub.com/esv/philippians/1.htm" target="_blank">Philippians 1</a></i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i>21For to me to live is Christ, and to die is gain. 22If I am to live in the flesh, that means fruitful labor for me. <b>Yet which I shall choose I cannot tell.</b> 23I am hard pressed between the two. <b>My desire is to depart and be with Christ, for that is far better.</b></i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i>24<b>But to remain in the flesh is more necessary on your account.</b> 25<b>Convinced of this, I know that I will remain</b> and continue with you all, for your progress and joy in the faith, 26so that in me you may have ample cause to glory in Christ Jesus, because of my coming to you again.
</i></blockquote>
<br />
He determined; although he'd have preferred to leave, that he would stay. Not for any desire of his own to stay. He'd already visited heaven, and he was ready to move there. But, he decided that it was necessary to remain here for the sake of the people he was called to serve.<br />
<br />
Eventually, he did complete his mission, and he was given permission to leave. At that time, his tone changed. No longer was it necessary to stay; rather, the time of his departure had come.<br />
<br />
<blockquote class="tr_bq">
<i><a href="http://biblehub.com/2_timothy/4-7.htm" target="_blank">2 Timothy 4:7</a></i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i><br /></i><i>6For I am already being poured out as a drink offering, and t<b>he time of my departure has come</b>. 7I have fought the good fight, I have finished the course, I have kept the faith; 8in the future there is laid up for me the crown of righteousness, which the Lord, the righteous Judge, will award to me on that day; and not only to me, but also to all who have loved His appearing.
</i></blockquote>
<br />
I suppose that is the difference though; between Paul and Myself. Paul fought the good fight, ran the race, finished the course. He fulfilled his mission on this earth. I, on the other hand, have gone through fits and spurts of productivity for the kingdom, followed by long periods of aimless existing. Not really trying, focusing, or attempting to attain to anything really. Watching T.V. at night, avoiding the writing and things I know in my heart I should be doing.<br />
<br />
So if I can't go until I fulfill my calling, I may as well make the most impact I can while I'm here. Not because I want to, or because it fulfills or excites me, or because I'm glad to be here....<br />
<br />
... although I'm sure those things may come as byproducts of being engaged in the task....<br />
<br />
... but because it's got to be better than just existing, sitting down on the race course waiting for the time to run out on the clock.<br />
<br />
<blockquote class="tr_bq">
<i><a href="http://biblehub.com/philippians/3-13.htm" target="_blank">Philippians 3:13</a></i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i><br /></i><i>Brothers and sisters, I do not consider myself yet to have taken hold of it. But one thing I do: Forgetting what is behind and straining toward what is ahead,
</i></blockquote>
<br />
So I need to add a new major to my mindset. I can still be a PhD in "Leave Earth", but I can add a second PhD in "Forgetting what is behind and straining toward what is ahead".<br />
<br />
.... Darrell<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />