---
title: 'Louse to Blessed | Tither'
date: '2015-02-23T12:39:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8847425022127852414'
blogger_filename: '/2015/02/louse-to-blessed-tither.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<br />
<br />
<br />
<br />
<br />
<div class="vk_ans" style="margin-bottom: 0;">
<h3>
<span data-dobid="hdw">louse</span></h3>
</div>
<div>
<div>
<div class="lr_dct_sf_h">
<i>noun</i></div>
<div class="xpdxpnd vk_gy" data-mh="-1">
<span>noun: <b>louse</b></span><span>; plural noun: <b>lice</b></span><span>; plural noun: <b>louses</b></span></div>
<div>
<span class="lr_dct_ph"><span>lous</span>/</span></div>
<ol class="lr_dct_sf_sens">
<li><div>
<div class="lr_dct_sf_sen vk_txt">
<div style="float: left;">
<strong>1</strong>. </div>
<div style="margin-left: 20px;">
<div style="font-size: small;">
<div data-dobid="dfn" style="display: inline;">
<span>a small, wingless, parasitic insect that lives on the skin of mammals and birds.</span></div>
</div>
<div style="margin-left: -13px;">
<ul>
<li class="xpdxpnd" data-mh="-1"><div class="lr_dct_sf_subsen">
<div style="font-size: small;">
<div data-dobid="dfn" style="display: inline;">
<span>used in names of small invertebrates that parasitize aquatic animals or infest plants, e.g., <i>fish louse</i>.</span></div>
</div>
</div>
</li>
</ul>
</div>
</div>
</div>
</div>
</li>
<li><div>
<div class="lr_dct_sf_sen vk_txt">
<div style="float: left;">
<strong>2</strong>. </div>
<div style="margin-left: 20px;">
<div style="font-size: small;">
<div>
<span class="lr_dct_lbl_blk vk_gy" style="font-style: italic;">informal</span></div>
<div data-dobid="dfn" style="display: inline;">
<span>a contemptible or unpleasant person.</span></div>
</div>
</div>
</div>
</div>
</li>
</ol>
</div>
<div>
<div class="lr_dct_sf_h">
<i>verb</i></div>
<div class="xpdxpnd vk_gy" data-mh="-1">
<span>verb: <b>louse</b></span><span>; 3rd person present: <b>louses</b></span><span>; past tense: <b>loused</b></span><span>; past participle: <b>loused</b></span><span>; gerund or present participle: <b>lousing</b></span></div>
<ol class="lr_dct_sf_sens">
<li><div>
<div class="lr_dct_sf_sen vk_txt">
<div style="float: left;">
<strong>1</strong>. </div>
<div style="margin-left: 20px;">
<div style="font-size: small;">
<div>
<span class="lr_dct_lbl_blk vk_gy" style="font-style: italic;">informal</span></div>
<div data-dobid="dfn" style="display: inline;">
<span>spoil or ruin something.</span></div>
<div class="vk_gy">
"<span>he loused up my promotion chances</span>"</div>
</div>
</div>
</div>
</div>
</li>
<li><div>
<div class="lr_dct_sf_sen vk_txt">
<div style="float: left;">
<strong>2</strong>. </div>
<div style="margin-left: 20px;">
<div style="font-size: small;">
<div>
<span class="lr_dct_lbl_blk vk_gy" style="font-style: italic;">archaic</span></div>
<div data-dobid="dfn" style="display: inline;">
<span>remove lice from.</span></div>
</div>
</div>
</div>
</div>
</li>
</ol>
</div>
</div>
<br />
<br />
<br />
<br />
<br />
I was a louse. Like my father, and his father before him. <br />
<br />
Moving from person to person, woman to woman, job to job, place to place... wondering. I left a trail of broken hearts and friendships behind me... and I carried pieces of those with me at all times. I was becoming an alcoholic. I stole a woman from a friend and lost both. Then You led me to AA and Alanon in Jan 2002. In Aug 2002, I asked You "What do you want from me?" I surrendered.<br />
<br />
There have been highs and lows since then. I've had some of my worst days (internally and externally) since that day. But You never left my side. You have protected, provided, funded my life. I don't talk about the tithe much, or think about it much, because she physically hits send. But I want to thank You.<br />
<br />
Thank You for the life you've given me. This wife, who sticks by me even in my stubbornness. These kids who love me even though I don't pay attention to them as much as they want/need. Two dogs, perfect for us. This house, although not my dream mansion, is great! Much better than the apartments we've lived in before now. If we never leave here, and I retire from WFDS here... I choose to be content with that.<br />
<br />
But I also know that you have so much more... Tithing didn't open that door. YOU opened that door. Tithing was my way of saying "I trust you, I thank you." Tithing is a natural response to Your Goodness.<br />
<br />
Thank You Jesus... For everything.<br />
<br />
<br />
Darrell<br />
<br />
03/02/2015<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />