---
title: 'NFW 10.18.15'
date: '2015-10-19T04:31:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1419376138869628134'
blogger_filename: '/2015/11/nfw-101815.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Church Notes'
---

<br />
<br />
<br />
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;calibri light&quot; , sans-serif; font-size: 20pt;">NFW 10.18.15<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="color: grey; font-family: &quot;calibri&quot; , sans-serif; font-size: 10.0pt;">Sunday, October 18, 2015<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="color: grey; font-family: &quot;calibri&quot; , sans-serif; font-size: 10.0pt;">8:59 AM<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , sans-serif; font-size: 11pt;">Sunday 9 am<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , sans-serif; font-size: 11pt;">If you are not accomplishing ALL
that I called you to do, then you are working too hard. Rest. Ask me what to
do, do it, rest in the results.<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , sans-serif; font-size: 11pt;">Joshua 6<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , sans-serif; font-size: 11pt;">Jericho unearthed<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , sans-serif; font-size: 11pt;">A generation of people out of
fear and repeated mistakes, into a life of victory. Joshua did not fight for
victory, he fought from victory.<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , sans-serif; font-size: 11pt;">Do not assume that tomorrow is a
day of defeat but a day of victory!<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , sans-serif; font-size: 11pt;">6 days of silent watching,
prayerful meditation, no speaking, saying nothing until instructed.<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , sans-serif; font-size: 11pt;">2 Chor 10:3-4<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , sans-serif; font-size: 11pt;">Strongholds= Any thought or idea
that sets itself up against the truth of God.<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , sans-serif; font-size: 11pt;">Satan will not linger where truth
is told, he will not loiter where God is praised. Satan has an allergy to
truth.<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , sans-serif; font-size: 11pt;">Satan cannot read your thoughts,
but he can hear your spoken words. Speak truth of God's word out loud.<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , sans-serif; font-size: 11pt;">…<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<br />
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="color: #969696; font-family: &quot;arial&quot; , sans-serif; font-size: 9.0pt;">Created with Microsoft OneNote
2013.<o:p></o:p></span></div>
