---
title: 'The Meat We Eat'
date: '2015-07-29T12:51:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2358726497346916193'
blogger_filename: '/2015/07/the-meat-we-eat.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Word From God'
  - 'Growing Up'
---

<br />
"The Grave You Crave Podcast Part 2 12/01/14"<br />
<br />
Pastor Charlotte Gambill of Life Church UK, was talking about the Israelites coming out of Egypt. They were looking back, and complaining about the meat they ate before they left. She said many of you are remembering the old life, no accountability, casual interactions, etc. The enemy has shown you a post card of the meat from Egypt, but he didn't show you the chains, whips, task masters, depravity, sickness, death.<br />
<br />
<br />
So often I look back at a job I worked that I hated, and from this side, it doesn't look that bad, even maybe more desirable than the one I'm in at the time. But on the rare occasion I went back, it was awful, all the old feelings rushed back.<br />
<br />
<br />
I have a tendency to view the past with Rose Colored glasses, and the future with Green (envy), and the present with Black. It's been my tendency from early in life. Maybe it's time for a new paradigm.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />