---
title: 'Car Trouble Solved --- Whoo Hoo!'
date: '2015-02-08T14:04:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7771941326673192100'
blogger_filename: '/2015/02/car-trouble-solved-whoo-hoo.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Car'
  - 'Answers'
---

<br />
We prayed about what to do, and Flavia felt "Trade It". We thought that meant trade it in, so I ran around to used car dealerships getting no where. I also feel that I may never go to Auto Land sales again... not because they are bad, but because God is trying to teach me not to go to the same well twice. <br />
<br />
<b>New Car</b><br />
<br />We bought the 2002 Volvo S60 for $1,000. She was just glad
 to be rid of it, and didn't want to do any more work herself, she'd 
done a bunch already. <br />
<br />
<b>Tire:</b> <br />
NTB re-seated the tire. The daughter had ran it off the road into a ditch, and in doing, there was grass between the tire and rim causing a slow leak. They cleaned it up, put sealer on it, and re-seated it.<br />
<br />
<b>Cost for tire: $0.00</b><br />
<br />
<b>Fuel Pump:</b><br />
Volvo confirmed that the fuel pump and assembly were bad, and needed to be replaced. They were covered under the recall. However, it was not all free. There was a passenger side relay that was damaged by the run off the road.<br />
<br />
But, because the fuel pump was part of the recall, the labor was covered for all of it. So I only need to buy the part.&nbsp; <br />
<br />
<b>Cost of Fuel Pump Assembly: $0.00</b><br />
<b><br /></b>
<b>Cost of total repair with new findings: $123.50</b><br />
<br />
<br />
<b>Old Car</b><br />
<br />
So, we sold the van last night, 
for $700.00, to a guy who owns a small dealership (probably a lot with 
five cars (LOL). He brought his mechanic, they looked it over. We asked 
$1,000 OBO, they offered $700.00. Worth it! (Especially since other 
offers were coming in at $500 or less). <br />
<br />
*************************Afterward*********************<br />
<br />
We're driving the Volvo last night, and the check engine light comes on. I'm like NOOOOOOOOO!!!!! Registration and Inspection are due in May 2015 (a few months).<br />
<br />
Then we decided. We kept pulling ourselves back from the edge of panic and trying to "make something happen" throughout this experience, purposing to be #BeStillBeLed. We took a deep breath, and said "God, you led us to this car. You do what you do, and we'll trust, listen, and be led". We stopped by O'Riely's Auto, checked the code, just a gas cap code.<br />
<br />
<b>&nbsp;Cost of Gas Cap (after coupon): $5.50</b><br />
<br />
<br />
<br />
I'm going back today to replace the power steering return hose. But I need to take it off so I can match it, they couldn't find the exact part in the computer.<br />
<br />
<br />
I'm thinking of trading the wheels/tires they have on now (Some low profile/high performance stuff), and putting on stock 15 inch wheels/tires. <br />
<br />
God is good. Looking forward to car two. <br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />