---
title: 'Dream: Woman/Daughter 04/14/15'
date: '2015-04-14T12:31:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8049155244889925650'
blogger_filename: '/2015/04/dream-womandaughter-041415.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'dream'
---

<div style="border-width: 100%; direction: ltr;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.0861in;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.0861in;">

<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
In my dream, I had a
woman on my lap, she was both a mature woman and young girl at the same time.
We were kissing frequently. Later she was taken by a furry goblin like
creature. I chased down leads, got very Raymond Reddington like with people and
creatures until I ended up in a small village school/warehouse. The goblins
were making a raucous in the village. Some were running from them, other
running to them out of curiosity. Most didn't know what they were, or even that
they were there. They just knew noise was being made. I ignored the commotion
and people and made my way into an underground area. I almost missed the hiding
placed but I turned and found it. The goblin knew me, and was terrified of me.
I demanded to know where he had taken her, and his eyes told me to look behind
me. She was in a hospital bed, strapped to wires and tubes, asleep. There were
monitors attached to a large touch screen. I tried to turn it off and it
started to defibrillate, so I just unplugged everything. She woke up. I held
her in one arm, and the goblin by the neck in the other. I had kept him alive
in case I needed him to wake her. When I knew she was safe, still holding her,
I reached behind her, broke his neck and took his head off. I threw his body
one way and his head the other. I woke. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
**</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
I started to try to
interpret the dream, it felt more than just a dream. Who were the key players?
The Woman/Girl, and the Goblin. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Then I heard a voice
inside of me. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
God: "The woman
and girl are one and the same. They are Flavia. Your wife and my daughter. You
are to have that kind of passion for her as your wife, and that kind of
protection over her as she is my daughter." </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
The Goblin is
obviously the demonic spirit that attacks our lives. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
**</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Second Dream: New
Search Provider?</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
I ran into Travis
Downs (of all people) and he had this great idea to start a new internet search
company to disrupt the market place. He wanted my advice. I told him he'll need
to hire a coder to design it, and buy a domain name and get the website hosted.
What he would need to do is to build it so that it comes up with two columns of
searches. One column with normal web search (better in whatever way) and a
second column with ad searches. This actually searches the paid ads for the
best/more relevant ads for the searcher, providing a benefit to add producer
and buyer at the same time. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
**</div>
</div>
</div>
</div>
