---
title: 'Meet | Allen Powers - Dream Talk'
date: '2015-03-31T14:29:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8005066300618103507'
blogger_filename: '/2015/03/meet-allen-powers-dream-talk.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'dream'
---

<br />
<br />
<br />
<br />
Who were the main players in the dream?<br />
What were the main themes (or theme) of the dream?<br />
What feelings did you have during and after the dream?<br />
<br />
<br />
<br />
Man on the floor, peppering me with questions. Made my feel off, like I couldn't help him, but I kept trying. I had to finally move on. <br />
<br />
The line was gone. This man peppering me with questions distracted me from the real calling and opportunity. <br />
<br />
The lady who was left (HolySpirit in this dream) was encouraging me anyway. "I'm so excited for this opporutnity you have." <br />
<br />
The Pastor, may/maynot have been a specific person. I don't know that I ever met or talked to him in the dream, as much as I knew he was there, or was around. This was the person I was seeking approval from, and didn't get it. <br />
<br />
-----<br />
<br />
There are questions in my own mind that need to cease. These questions are preventing me from taking part in my calling. I need to leave those questions un-answered sitting on the sidelines, and go pursue the calling. <br />
<br />
----<br />
<br />
Is there any signficance to the fact that it was a man peppering me with questions and a woman reaffirming my calling? I've struggled with men, and seeking approval from women all my life. It could be. The man peppering me with questions was the devil that's been doing that all my life. He was on the ground because he is impotent and powerless, yet I stoop over to answer him instead of standing and facing my calling. <br />
<br />
Others have had to move on without me, as I stood facing these worthless and pointless questions. <br />
<br />
It's time to leave them behind, and puruse the calling. God doesn't call the qualfied, He qualifies the called. You've heard that, taught it, but never believed it. You're still waiting to be qualified. Stop waiting. The very act of hesitating to pursue the calling, is the thing opening the void for non-calling related distractions to enter in. <br />
<br />
Pursue the calling, and the void is filled with God. <br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
