---
title: 'With Jack Feb 17, 2015'
date: '2015-02-17T13:09:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8784928807480407082'
blogger_filename: '/2015/02/with-jack-feb-17-2015.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
  - 'Counsel'
---

<div style="border-width: 100%; direction: ltr;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.0861in;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.0861in;">

<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Feed Election
Volunteer </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
90 Year Old Love</div>
<ul style="direction: ltr; margin-bottom: 0in; margin-left: .375in; margin-top: 0in; unicode-bidi: embed;" type="disc">
<li style="margin-bottom: 0; margin-top: 0; vertical-align: middle;"><span style="font-family: Calibri; font-size: 11.0pt;">Dual Heart Attacks</span></li>
<li style="margin-bottom: 0; margin-top: 0; vertical-align: middle;"><span style="font-family: Calibri; font-size: 11.0pt;">Decision to face bypass
     surgery</span></li>
<li style="margin-bottom: 0; margin-top: 0; vertical-align: middle;"><span style="font-family: Calibri; font-size: 11.0pt;">Recovery</span></li>
<li style="margin-bottom: 0; margin-top: 0; vertical-align: middle;"><span style="font-family: Calibri; font-size: 11.0pt;">Final Passing</span></li>
</ul>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Dual POV?</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Or just Son? </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
First person?</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Diary?</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
It was another post
retirement morning. I feel like I'm working more in post retirement than I did
running a company. I sat down to read the headlines and prepare for the day.
That was when the call came. Last night, both Mom and Dad had heart attacks. This
could be it, you new to come now. My sister was not unknown to exaggerate, but
she seemed serious this time. I hopped on the next flight to Palm Springs, CA. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Sun City was an
impressive retirement community. It was interesting to see more golf carts than
cars. I pulled in to the drive wday, and she came out and hopped in the
passenger seat of the rented Priuos.The lack of sound from these cars always
throws me off, is it on? The grinding screech tells me it is. We head to
Eisenhower Hospital, ICU. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
I've always hated
the smell of hospitals. Disinfectant was not the smell of health. There they
were, laying in beds next to each other. Mom was asleep, she often was these
days with her Angina getting worse. Dad was watching the game. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
How are they doing?</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Ah, how you know
those Sea Hawks... How they ever beat Green Bay I'll never know. Good to see ya
sport.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
How you doing? Oh...
I'm fine. Reports of my demise are greatly exaggerated. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Dad, she said, you
are over simplifying it as usual. He needs work, and a stint won't do it. They
are exploring options. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Just then, there was
a knock at the door. It was Dr. Jeffers. I'd heard you were both here. I'm glad
because I needed to talk to you. We have come to a consensus. I'm not going to
sugar coat it. We put a stint in one side. We could not stint the other. At 90
years old, you are not a great candidate for a bypass, especially a triple
bypass. My suggestion is that you rest, relax, and enjoy your last days or
years in peace. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
With that he left us
with a decision. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Not an option. She
needs me. Bypass recovery is hard. Research that. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
..</div>
</div>
</div>
</div>
