---
title: 'Fwd: a short response since i know you are not feeling well'
date: '2015-09-01T05:52:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8207125381437646233'
blogger_filename: '/2015/08/fwd-short-response-since-i-know-you-are.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Growing Up'
---

<div dir="ltr">
<div class="gmail_default" style="color: black; font-family: &quot;georgia&quot; , serif;">
<br clear="all" /></div>
<div>
<div class="gmail_signature">
<div dir="ltr">
<div>
<div dir="ltr">
<br />
<div>
</div>
<div>
<span style="font-family: &quot;comic sans ms&quot; , sans-serif;"><span style="font-size: medium;">Thank You! </span></span></div>
<div>
<br /></div>
<div>
<div style="margin-bottom: 0pt; text-indent: 0.5in;">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 12pt;"><span style="font-size: large;">Darrell G. Wolfe</span></span></div>
<div style="margin-bottom: 0pt;">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 12pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Writer. Blogger. </span></div>
<div style="margin-bottom: 0pt;">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 12pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; INFJ (INTJ) Intellection. Learner. Ideation. Achiever. Input.&nbsp; </span><span style="color: black; font-family: &quot;tempus sans itc&quot;; font-size: 12pt;"><br /></span></div>
<span style="color: grey; font-family: &quot;tempus sans itc&quot;; font-size: 12pt;"><span style="color: blue;"><span style="color: #0072bc;"></span></span></span><br />
<div style="font-family: &quot;trebuchet ms&quot;; font-size: 12pt;">
<span style="color: grey; font-family: &quot;tempus sans itc&quot;; font-size: 12pt;"><span style="color: blue;"><span style="color: #0072bc;"></span></span></span><br />
<div style="margin-bottom: 0pt; text-indent: 0.5in;">
<span style="color: grey; font-family: &quot;tempus sans itc&quot;; font-size: 12pt;"><span style="color: blue;"><span style="color: #0072bc;"><span style="color: grey; font-family: &quot;tempus sans itc&quot;; font-size: 12pt;"><span style="color: blue;"><span style="color: #0072bc;"><a href="http://darrellwolfe.blogspot.com/" target="_blank">www.DarrellWolfe.Com</a></span></span></span></span></span></span></div>
<div style="margin-bottom: 0pt; text-indent: 0.5in;">
<span style="color: grey; font-family: &quot;tempus sans itc&quot;; font-size: 12pt;"><span style="color: blue;"><span style="color: #0072bc;"><span style="color: grey; font-family: &quot;tempus sans itc&quot;; font-size: 12pt;"><span style="color: blue;"></span></span><span style="color: grey; font-family: &quot;tempus sans itc&quot;; font-size: 12pt;"><span style="color: #0072bc;"><span style="color: grey; font-size: 12pt;"><span style="color: blue;"><span style="color: #0072bc;"><a href="http://authorfun.blogspot.com/" target="_blank"></a></span></span></span></span></span></span></span></span></div>
<div style="margin-bottom: 0pt; text-indent: 0.5in;">
<span style="color: grey; font-family: &quot;tempus sans itc&quot;; font-size: 12pt;"><span style="color: blue;"><span style="color: #0072bc;"><span style="color: grey; font-family: &quot;tempus sans itc&quot;; font-size: 12pt;"><span style="color: #0072bc;"><span style="color: grey; font-size: 12pt;"><span style="color: blue;"></span></span><span style="color: grey; font-size: 12pt;"><span style="color: blue;"></span></span></span></span><span style="color: grey; font-family: &quot;tempus sans itc&quot;; font-size: 12pt;"><a href="https://twitter.com/DarrellWolfe" target="_blank"><span style="color: #0072bc;">Twitter: @DarrellWolfe</span></a><a href="http://darrellwolfe.blogspot.com/" target="_blank"></a></span></span></span></span></div>
<span style="color: grey; font-family: &quot;tempus sans itc&quot;; font-size: 12pt;"><span style="color: blue;"><span style="color: #0072bc;"><a href="http://darrellwolfe.blogspot.com/" target="_blank"></a><div style="margin-bottom: 0pt; text-indent: 0.5in;">
<a href="http://darrellwolfe.blogspot.com/" target="_blank"><span style="color: grey; font-family: &quot;tempus sans itc&quot;; font-size: 12pt;"></span></a><span style="color: blue;"><span style="color: #0072bc;"><a href="mailto:Darrell@DarrellWolfe.Com" target="_blank"><span style="color: blue;"><span style="color: #0072bc;"></span></span></a></span></span></div>
<div style="color: rgb(0 , 0 , 0); display: inline; font-family: &quot;georgia&quot; , serif;">
<span style="color: #0072bc;"><a href="mailto:Darrell@DarrellWolfe.Com" target="_blank"><span style="color: #0072bc;">​</span></a></span></div>
<span style="color: #0072bc;"><a href="mailto:Darrell@DarrellWolfe.Com" target="_blank"><span style="color: #0072bc;">Darrell@DarrellWolfe.Com</span></a></span></span></span></span></div>
</div>
<div>
<br /></div>
<div>
<br /></div>
</div>
</div>
</div>
</div>
</div>
<br />
<div class="gmail_quote">
---------- Forwarded message ----------<br />
From: <b class="gmail_sendername">Darrell Wolfe _ Gmail</b> <span dir="ltr">&lt;<a href="mailto:darrellwolfe@gmail.com">darrellwolfe@gmail.com</a>&gt;</span><br />
Date: Sat, Sep 5, 2015 at 1:11 AM<br />
Subject: RE: a short response since i know you are not feeling well<br />
To: Flavia Wolfe &lt;<a href="mailto:flaviawolfe@gmail.com">flaviawolfe@gmail.com</a>&gt;<br />
<br />
<br />
<div lang="EN-US" link="blue" vlink="purple">
<div>
<div class="MsoNormal">
<a href="https://draft.blogger.com/null" name="-1385438739__MailEndCompose"><span style="color: black;">We could try talking in person. It just hasn't ever really gone well. As soon as I start to feel any emotion I shut down, more a reaction to my own emotion than to yours. I can write it, but my voice turns off. <u></u><u></u></span></a></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">I feel very bi-polar, most days. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">In the same day I can be angry at you, or the kids, or both, and wish I'd stayed single. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">Later that same day I'm so glad I married you, and can't fathom how the earlier me thought that way. It's almost as though I'm two people, or demon possessed, although I'm pretty sure I'm not? <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">Today… seeing you with the kids, the way you talk to them, and work with them on the kitchen chairs, the way you recognized Preston as the one who needed to change in that moment with Connor and the balls on the couch… It's days like today I can appreciate what an amazing woman you are. You are smart, wise, resourceful.<u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">When I am at work, I'm good at what I do. I feel confident. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">When I get within moments of our home I feel a dread come over me. Like I'm walking into my abject failure staring me in the face. Long weekends like this one are hard, I escape because I have no idea how to cope.<u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">It's also days like today that I feel you three would be better off if I did just disappear, or leave earth, either way. I am self-centered, self-focused. I only see the world through how it affects my own comfort level. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">When I hear you talk about bills, or spending money on the kids, or money things, or dreams of a bigger financial future… these don't inspire me. They all lead me back to thinking about me. It makes me feel like I work 50+ hours a week for years and it's just not enough. It makes me feel like the air is sucked out of my hose. Eventually those feelings turned into feeling like you three were draining me. When in reality, it's my judgment of the situation that drained me, not you. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">I know most feelings are illogical, and that's why I hate emotions. All emotions. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">I can't tell you how much I want to go back to drinking, or medication right now. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">Drinking really gave me a buffer against my interactions with the outside world, other humans.<u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">Maybe I need to look at a psychologist, but that costs money too. I feel like I deceived those personal ministers into thinking I was good, because I deceived myself. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">I'm not good. I'm not O.K. There is something wrong with me. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">I have been struggling with porn addition off and on for years, and it's been worse the last few months. I talk about A.A. so much more lately, because I think about addiction constantly. I know that there is nothing good in the bottom of the bottle, but I find myself missing it. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">I was listening to Kenneth and Caroline Leaf talking about inherited DNA that finds it's expression. And how everyone in Kenneth's family died in their 70's and his body started acting up, until he made it stop.<u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">That got me thinking. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">You said I hurt you almost as bad as your dad, who left.<u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">My grandfather left his family in his 30's, to go be a selfish drunk.<u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">My father left his family in his 40's to be a selfish addict. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">Something about their lifestyle started appealing to me. I'm not sure when, or how long it's been in my head. But I started thinking that if you three left to live in Idaho, I could have more time and money to myself. Go back to drinking and stop going to church, and I'd have an excuse not to live up to this vision that is on the inside of me. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">This vision, that won't go away since I was a kid, and only gets bigger with time. This vision of ministry… it's scary. I feel the same with God as I do with you and the kids. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">All four of you (God, You, Connor, Preston) are a reminder that I'm not enough. I don't have enough. I'm not good enough. I'm not strong enough. I'm never going to get it right. I can't master my own emotions or attitude from day to day.<u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">Not once, in 11 years, have I ever been right in my first response to the kids. You have to observe and explain. Quite frankly, I'm a bit jealous, and exhausted.<u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">I don't want to keep living like this. I don't know what to do about it. I'm very tired. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">I just want to go Home, but He won't let me. I've been wanting to go Home since before 10, but He never lets me. I'm just so tired… <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">OK… so… if you want to talk in person, we could try. I just can't promise much will come out of my mouth. I can try to listen though. <u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b><span style="font-family: &quot;calibri&quot; , sans-serif; font-size: 11.0pt;">From:</span></b><span style="font-family: &quot;calibri&quot; , sans-serif; font-size: 11.0pt;"> Flavia Wolfe [mailto:<a href="mailto:flaviawolfe@gmail.com" target="_blank">flaviawolfe@gmail.com</a>] <br /><b>Sent:</b> Friday, September 4, 2015 1:57 AM<br /><b>To:</b> Darrell G. Wolfe &lt;<a href="mailto:Darrell.G.Wolfe@wellsfargo.com" target="_blank">Darrell.G.Wolfe@wellsfargo.com</a>&gt;; Darrell Wolfe &lt;<a href="mailto:darrellwolfe@gmail.com" target="_blank">darrellwolfe@gmail.com</a>&gt;<br /><b>Subject:</b> Re: a short response since i know you are not feeling well<u></u><u></u></span></div>
<div class="MsoNormal">
<br /></div>
<div>
<div class="MsoNormal">
I understood that it was a 'logical' list, but it wasn't specific so i was just trying to make it clearer. And then we could, perhaps, be on the same page about the options and what that may mean.&nbsp;<u></u><u></u></div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
You need to decide what you are and are not willing to do. And then do that, i guess. I don't know what it will be, or could be, or even what it should be. I believe I am on the right path towards forgiving you for what was said/done... not just the email... and not just towards me, but the boys as well.&nbsp;<u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
Through this i questioned God about us and I know that He brought us together, but we started messing it up and didn't seem to know what to do about it. We stumbled forward and ignored the issues. And now, here we are. Only God can bring us together again. Together and better able to walk forward. I believe this... but I am not ready to plunge head first into any 'option'.<u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
&nbsp;Going forward as it is now, ...right now this moment, no, that would not work very long. But I think over time we will be able to say a few more words, to each other in a day, than we are currently. The change in what our relationship has become will get past the readjustment phase. I think I am willing to go to the marriage challenge thing (of course on a non-volunteer week), but not in the mind set that a single however many minute long thing is going to fix things. And we are past putting a band aid on things, and hoping there's healing.&nbsp;<u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
Any permanent change is going to take time, effort and consistency... &nbsp;with the knowledge that neither of us are perfect and may do something the other doesn't like. I cannot make the first step(s) forward. I felt like I have tried, and it was not received the way I intended... and this has happened in different ways at different times, concerning many things/areas of life.&nbsp;<u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
Though I wish we had gotten to an honest talk about things another way, and with actual words... I am glad, at some level, that I don't have to wonder what you are thinking. I don't have to guess and make 'it's like..." statements when trying to explain how I feel to see if you can understand and we can connect.&nbsp;<u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
*oops, just realized this is an 'is like...' moment...habits...they can just pop up on you* &nbsp;The blue and pink headphone/microphone (marriage) guy talks about love languages and how a persons love language is like an air hose. When a spouse is doing those things the person can breathe and there is life. Or a spouse can ignore them and it's like they are stepping on the air hose suffocating them. And while friends can give a little air here and there, in a marriage that hose is important. I felt like you disconnecting my hose from your side, but i was trying and trying to get air from it anyway. And now that i know that there really was no air available through that hose right now, it helpful and because i can stop trying. I can stop feeling frustrated and upset about it not being there.&nbsp;<u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
It more frustrating to think you have something and can't get to it,or use it or whatever... than when you know that you just don't have it... you can come to terms with that revelation and move on to spend/use your time and effort to do something else.&nbsp;<u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
Its true that time is the only currency that you can't make more of... and i want to spend my time thinking about and doing things that matter... to me, to the boys and to God.&nbsp;<u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
As I said in the beginning of this email, you will need to decide what you are and are not willing to do. And then do that...If you decide to do something that I need to participate in, let me know and i will let you know what I think about it and if i am willing or ready. But if I say I need time and your response is in some way "fine, than lets just forget about it..." than future attempts for my involvement may come with greater cautiousness.&nbsp;<u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
moving forward: &gt; I will continue to work towards giving you cash on paycheck weekends for you to use as you will, and then I budget and really get one going again... &gt; I will try to let you know ahead of time, when we will be taking you to work, and if we need to leave early... I don't really use outlook , but when i have time i was going to try it again, so that may or may not be helpful for this &gt; Sundays - my plan is to always go to the early service, on a non volunteer week if you want to go to the 3rd service instead let me know Sat. so i can make sure to come right back.&nbsp;<u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
my first car use heads up is for this ^Sat.(afternoon), ^Mon.(its a holiday) , ^Fri.(taking you to work) , and ^next Sat. , and whatever day Preston's baseball practice will be if he has one.&nbsp;<u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
This seems to me like the clearest of all my thoughts and emotions from this week, for now.&nbsp;<span style="font-family: &quot;segoe ui symbol&quot; , sans-serif;"></span><u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
<div>
<div class="MsoNormal">
On Thu, Sep 3, 2015 at 4:55 PM, &lt;<a href="mailto:Darrell.G.Wolfe@wellsfargo.com" target="_blank">Darrell.G.Wolfe@wellsfargo.com</a>&gt; wrote:<u></u><u></u></div>
<blockquote style="border-left: solid #cccccc 1.0pt; border: none; margin-left: 4.8pt; margin-right: 0in; padding: 0in 0in 0in 6.0pt;">
<div>
<div>
<div class="MsoNormal">
<span style="color: black; font-family: &quot;verdana&quot; , sans-serif; font-size: 10.0pt;">I'll check out the videos. I was just listing what I saw as the three logical options/directions from here forward. </span><u></u><u></u></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black; font-family: &quot;verdana&quot; , sans-serif; font-size: 10.0pt;">What do you want to do about us? What actions can I/We take from here?</span><u></u><u></u></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black;">Thank you for your time, </span><u></u><u></u></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black; font-family: &quot;georgia&quot; , serif; font-size: 10.0pt;">Darrell G. Wolfe</span><u></u><u></u></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black; font-family: &quot;verdana&quot; , sans-serif; font-size: 10.0pt;">Research &amp; Remediation Analyst </span><u></u><u></u></div>
<div class="MsoNormal">
<span style="color: black; font-family: &quot;verdana&quot; , sans-serif; font-size: 10.0pt;">Dealer Complaints Specialist</span><u></u><u></u></div>
<div class="MsoNormal">
<span style="color: black; font-family: &quot;verdana&quot; , sans-serif; font-size: 10.0pt;">CRC Platinum Services, Office of the President</span><u></u><u></u></div>
<div class="MsoNormal">
<span style="color: navy; font-family: &quot;verdana&quot; , sans-serif; font-size: 10.0pt;"><br /></span><span style="color: grey; font-family: &quot;verdana&quot; , sans-serif; font-size: 10.0pt;">Wells Fargo Dealer Services&nbsp; |&nbsp; 6061&nbsp;N. State Highway 161&nbsp; | 2nd Floor | Irving,&nbsp;TX 75038-2242</span><u></u><u></u></div>
<div class="MsoNormal">
<span style="color: grey; font-family: &quot;verdana&quot; , sans-serif; font-size: 10.0pt;">MAC T9017-024<br />Tel <a href="tel:877-250-2265" target="_blank">877-250-2265</a> | Direct <a href="tel:972-870-8308" target="_blank">972-870-8308</a> | Fax <a href="tel:888-329-4855" target="_blank">888-329-4855</a></span><u></u><u></u></div>
<div class="MsoNormal">
<span style="color: black; font-family: &quot;calibri&quot; , sans-serif; font-size: 11.0pt;"><a href="mailto:Darrell.G.Wolfe@wellsfargo.com" target="_blank"><span style="font-family: &quot;verdana&quot; , sans-serif; font-size: 10.0pt;">Darrell.G.Wolfe@wellsfargo.com</span></a></span><span style="color: black; font-family: &quot;verdana&quot; , sans-serif; font-size: 10.0pt;"> </span><u></u><u></u></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: #262626; font-family: &quot;verdana&quot; , sans-serif; font-size: 9.0pt;">Should you have an escalated issue that needs immediate attention, please forward to: </span><span style="color: black; font-family: &quot;calibri&quot; , sans-serif; font-size: 11.0pt;"><a href="mailto:officeofthepresidentdealer@wellsfargo.com" target="_blank"><span style="font-family: &quot;verdana&quot; , sans-serif; font-size: 9.0pt;">officeofthepresidentdealer@wellsfargo.com</span></a></span><span style="color: #262626; font-family: &quot;verdana&quot; , sans-serif; font-size: 9.0pt;"> or call <a href="tel:%28877%29%20250-2265" target="_blank">(877) 250-2265</a></span><u></u><u></u></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: grey; font-family: &quot;verdana&quot; , sans-serif; font-size: 10.0pt;">This transmission may contain information that is confidential and/or proprietary. If you are not the individual or entity to which it is addressed, note that any review, disclosure, copying, retransmission or other use is strictly prohibited. If you received this transmission in error, please notify the sender immediately and delete the material from your system. This transmission is for informational purposes only, and is not intended as an offer or solicitation for the purchase or sale of any financial instrument or as an official confirmation of any transaction. </span><u></u><u></u></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b><span style="font-family: &quot;tahoma&quot; , sans-serif; font-size: 10.0pt;">From:</span></b><span style="font-family: &quot;tahoma&quot; , sans-serif; font-size: 10.0pt;"> Flavia Wolfe [mailto:<a href="mailto:flaviawolfe@gmail.com" target="_blank">flaviawolfe@gmail.com</a>] <br /><b>Sent:</b> Thursday, September 03, 2015 3:14 PM<br /><b>To:</b> Wolfe, Darrell G.<br /><b>Subject:</b> a short response since i know you are not feeling well</span><u></u><u></u></div>
<div>
<div>
<div class="MsoNormal">
<br /></div>
<div>
<div class="MsoNormal">
i didn't want to not respond, so I thought i would send a short response, to your email last night, since i know that you are not feeling well. At the end of your email you gave 3 options:&nbsp;<u></u><u></u></div>
<div>
<div class="MsoNormal">
&nbsp; &nbsp;- the first one is is no longer an option unless you are talking about us after the start of these emails, because things have changed.<u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
&nbsp; &nbsp;- for the second do you mean separate... or what... you didn't want a bed in the other room. more than that is...? a few emails ago you said divorce was not something you were thinking about, and i don't consider that an option.<u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
&nbsp; &nbsp;- the third one won't work unless you are willing to do a number of things your first email said you were not interested in.<u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
<a href="http://www.marriagetoday.com/how-to-daily-deal-with-anger/" target="_blank">http://www.marriagetoday.com/how-to-daily-deal-with-anger/</a>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;this is a good video if you are interested in watching, and other than that, i have nothing more to add...&nbsp;<u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div class="MsoNormal">
-- <u></u><u></u></div>
<div>
<div class="MsoNormal">
Today is a day of Supernatural !!!!<u></u><u></u></div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</blockquote>
</div>
<div class="MsoNormal">
<br /><br clear="all" /><u></u><u></u></div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div class="MsoNormal">
-- <u></u><u></u></div>
<div>
<div class="MsoNormal">
Today is a day of Supernatural Favor!!!<u></u><u></u></div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
<a href="http://www.texascowsandcrafts.com/" target="_blank">http://www.texascowsandcrafts.com/</a> <u></u><u></u></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
<a href="https://www.facebook.com/pages/Texas-Cows-Crafts/298135563538323" target="_blank">https://www.facebook.com/pages/Texas-Cows-Crafts/298135563538323</a> <u></u><u></u></div>
</div>
</div>
</div>
</div>
</div>
</div>
<br /></div>
