---
title: 'Journal Mon 03/30/15'
date: '2015-03-30T12:06:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7504056344453736931'
blogger_filename: '/2015/03/journal-mon-033015.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
This morning I woke
up later than I'd like to have, but it was quite, and a good morning. The Lord
put Miley Cirus on my heart, so I prayed for her. Blessed. Freed. Restored. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
I feel hopeful…
could I really be (not just called…. Equipped?) for ministry? </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
..</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
First things first,
I emailed Gateway about the Equip LTT training. To my surprise I got some
immediate replies. There are two classes I can sign up for, and Pastor Mondoe
Davis would like to meet to discuss things. I'm finding myself excited and
terrified. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
After two years,
will I now get involved at Gateway? Will it turn out to disappoint as all other
churches have? Will I fail them, as I often have before? Chickening out of
leadership opportunities? </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
I feel that
accepting this promotion at work opened something new. Something, risky,
emotionally. What if I'm not adequate for the task at hand? Correction always
feels like sand paper on my soulish wounds. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Yet, I feel safe
here. I feel like I could open up, and let those wounds heal. I went to
personal ministry and survived. It's time to take a new level of openness, and
make myself vulnerable to other people on an on-going basis. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<br />
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Here we go… new
season, here I come.&nbsp;</div>
