---
title: 'Gay Marriage, Supreme Court, My Week'
date: '2015-07-01T05:13:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4079421470941678036'
blogger_filename: '/2015/06/gay-marriage-supreme-court-my-week.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Life Events'
---

When the United States Supreme Court announced the legalization of Gay Marriage... my first reaction was very negative. Renounce my citizenship and move to... oh wait. There's no where to move to.<br />
<br />
The first Church (and much of the world wide Church today) had to live in constant awareness that their life could be taken for being Christian. The USA has been protected from that, until now. Now bakers lose their bakery, because they refuse to participate in Gay Marriage.<br />
<br />
I want to love the sinner without embracing or endorsing the sin. Is there a difference between public policy and Church policy?<br />
<br />
What should my reaction be?<br />
<br />
Jesse Duplantis (Tuesday SWBC 06/30/15) talked about the decision. He mentioned how he lovingly worked with two gay men to redecorate his office. The kindness he showed them during a regular business transaction, years later, opened the door to them getting saved before dying of AIDS.<br />
<br />
I have gay friends and co-workers. I don't hate them because they are gay. I don't fear them. They know I love and support them as human beings. Most, but not all, know that I do not support their lifestyle; yet, they know without a doubt that I love THEM.<br />
<br />
Yet... I cannot support Gay Marriage. I cannot say that it's OK to be Gay. I view Gay as equal to Alcoholic. Unfortunate sin disorders that need to be addressed and treated, not embraced and championed.<br />
<br />
How should I respond publicly?<br />
<br />
Should I respond at all?<br />
<br />
What should my "official" position be?<br />
<br />
Should I give this any more attention than I would any other sin, like alcoholism?<br />
<br />
If I'm not going to write posts about the one, then why should I write posts about the other? If I write posts about either, what tone should they take?<br />
<br />
Who's my audience, and why am I writing it?<br />
<br />
Hmmm.... TBC<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />