---
title: 'Late Night Prayer'
date: '2015-05-21T05:59:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5083690318550926364'
blogger_filename: '/2015/05/late-night-prayer.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'prayer'
---

Got up late, missed my meeting with Allen Powers. Sorry buddy. But I met with Kurt Winters after work, and he treated me to In N Out. Then after I was home for a few minutes, Connor woke up with a runny nose. I gave him some stuff, and tissue, and we sat up while it kicked in. Looked at old photos on Picasa. It was actually the best time I've had with him in a while. I hope he sleeps in tomorrow.<br />
<br />
Me:<br />
Father,<br />
<br />
I choose to trust you. You have come through time and again, you did it this time. You came through in a big way on the Volvo to Mazda deal. You continue to amaze me. I continued to be amazed at how good you are despite my unfaithful unbelieving heart.<br />
<br />
How can I come to a place where I can trust you without question, and without flinching?<br />
<br />
God:<br />
<br />
Be Still Be Led Follow Directions<br />
<br />
It's not rocket science.<br />
<br />
Faith is simple, my burden is easy, I wasn't kidding. You must learn to trust that I know what you need, before you ask. I want to do better than you can plan. Just follow my lead. That's it.<br />
<br />
It's a simple Gospel. Profound in it's simplicity.<br />
<br />
If you only KNEW how much I love you, you would never doubt again.<br />
<br />
Take this next few weeks, and turn off the distractions. Pray. Spend time praying. There are plenty of opportunities, you just have to take them.<br />
<br />
The better you hear me in the good times, the better you'll hear me in the "bad".<br />
<br />
Me:<br />
Father, What about Kurt's Dad? Can we turn that situation around?<br />
<br />
God:<br />
I'm glad you asked, yes we can.<br />
<br />
Me:<br />
How?<br />
<br />
God:<br />
In due time, son. In due time. I work all things to your good in due time.<br />
<br />
Son, Are you ready for something new, something bigger, more responsibility?<br />
<br />
Me:<br />
I think I am.<br />
<br />
God:<br />
Good. That's all for now. Go to bed.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />