---
title: 'I''ve been shot!'
date: '2015-09-16T12:04:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6410758915941222606'
blogger_filename: '/2015/09/ive-been-shot.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'dream'
---

Dream:<br />
<br />
Flavia and someone else (my brother?) are standing behind a counter, I'm sitting in front. Brother goes to empty the cash register. (I think he was robbing it because these were mobsters and they deserved it?).<br />
<br />
A man comes in with a 22 long barrel rifle. I yell duck and the bullets barely miss brother. I run toward the enemy, but not before he lets off a few rounds at me. I grab the rifle, beat the guy, hold his neck with my foot and turn the rifle and shoot him a bunch of times... mostly in the crotch.<br />
<br />
Then I realize I've been shot too.<br />
<br />
While we're both laying there, I call 911 and the lady wants to sell me the premium plan. I hang up angry and call again, the sheriff answers and wants to interrogate me to see if I'm good enough to bother sending someone out. He finds out I'm a Christian and decides it's not worth it.<br />
<br />
I tell Flavia, "I miss California!!! Let's just go". I get in the car, and she drives to the hospital. I'm not bleeding anymore, just wounds. I can look inside and see the bullets. I think, maybe I can just pull them out myself. But the more I look, I realize there are more wounds than I thought.<br />
<br />
She says, it might be best to let someone qualified look at you, and do that.<br />
<br />
Woke Up...