---
title: 'Angry at God, lies, Psalms 4'
date: '2015-08-19T06:46:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '861210115678456382'
blogger_filename: '/2015/08/angry-at-god-lies-psalms-4.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'prayer'
---

<br />
<br />
<h4>
<a href="http://biblehub.com/esv/psalms/4.htm" target="_blank">Psalms 4</a></h4>
<blockquote class="tr_bq">
<i>1Answer me when I call, O God of <b>my righteousness</b>!<b> You have given me relief when I was in distress</b>. Be gracious to me and hear my prayer! 2O men,a how long shall my honor be turned into shame? How long will you love vain words and seek after lies?</i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i>Selah</i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i>3<b>But know that the LORD has set apart the godly for himself; the LORD hears when I call to him.</b></i><b>&nbsp;</b></blockquote>
<blockquote class="tr_bq">
<i>4<b>Be angry,b and do not sin; ponder in your own hearts on your beds, and be silent.</b></i><b>&nbsp;</b></blockquote>
<blockquote class="tr_bq">
<i>Selah</i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<b><i>5Offer right sacrifices, and put your trust in the LORD.</i>&nbsp;</b></blockquote>
<blockquote class="tr_bq">
<i>6There are many who say, “Who will show us some good? Lift up the light of your face upon us, O LORD!”</i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i><b>7You have put more joy in my heart</b> than they have when their grain and wine abound. 8<b>In peace I will both lie down and sleep</b>; for you alone, O LORD, make me dwell in safety.</i></blockquote>
<div>
<br /></div>
<br />
***<br />
<br />
<br />
<ul>
<li>Jesus is my Righteousness. He has delivered me from times of confusion and distress countless times, more often than I even recognize.</li>
<li>I was set apart through Grace, and through Grace He hears me. Every time. There is no room for doubt on this point. I can never feel as though my prayers hit the wall or ceiling and fell deaf. My Father ALWAYS hears me.&nbsp;</li>
<li>HOW can I be angry without sinning? What's the key to doing that?&nbsp;</li>
<ul>
<li>Be Still - Meditate</li>
<li>Meditate means to speak to yourself softly, repeat, murmur, pray... continuing to keep your focus on Him. It's more about listening and receiving, than speaking and putting information out. Most modern prayer consists of the prayer doing 90-100% of the talking. True biblical meditation would be the opposite. Letting GOD do 90-100% of the talking, you just be still, listen for his voice.&nbsp;</li>
<li>He may speak words, phrases, sentences... or he may speak in dreams, images, visions, ideas, seeing one thing and another, then seeing how they connect.</li>
<li>Just as a Zip File is a quick download that must be unpacked... the meditation downloads from HolySpirit often come quickly, but need time to unpack in the hearer.&nbsp;</li>
<li>This is the key to being angry and sinning not.&nbsp;</li>
</ul>
<li>HOW can I learn to trust God? Same way... the result of this type of being still, and meditating is a developing trust in God. Once you begin to hear, you choose to trust it. As your hearing turns into instructions, you choose to obey it. As your hearing gets clearer, and your obeying gets more intuitive... the result is a trust in God.&nbsp;</li>
<ul>
<li>Anti-Trust: Saying "Show my some goodness, what about me?" is a sign that you don't trust Him.&nbsp;</li>
</ul>
<li>Result: Joy and Peace</li>
<ul>
<li>If you are lacking Joy and/or Peace, this is a sure sign you haven't been spending time Being Still and Meditating.&nbsp;</li>
</ul>
</ul>
<br />
<div>
<br /></div>
I fleshed this out more in an official post:&nbsp;http://www.darrellwolfe.com/2015/08/a-solution-to-being-irritated-and-mad.html<br />
<br />
******************************************************<br />
<br />
So... taking my own medicine...<br />
<br />
Father,<br />
<br />
I'm angry at you. I'm tired of this stupid planet. I have been for decades. Temptations sucks. If I give in I feel guilty. If I don't I keep wishing I had.<br />
<br />
I'm tired of being a "Good Boy". I'm tired of responsibility. I'm feeling stuck, bored, trapped, exhausted, and fed up.<br />
<br />
Forget the "good fight", I'm tired of fighting any fight.<br />
<br />
I don't want to master my body (through exercise) or my soul (through discipline). I want it to flow effortlessly, or I don't wan it.<br />
<br />
I'm whining and complaining, but you can handle it.<br />
<br />
So... now what?<br />
<br />
What lies am I believing, that keep me angry at you?<br />
<br />
<br />
TBC.... 08/19/15<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />