---
title: 'In Between day 1 and 2. Vacation.'
date: '2015-10-27T07:59:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2089049292027280686'
blogger_filename: '/2015/10/in-between-day-1-and-2-vacation.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
Started seeing Dr. Hess (Chiro) yesterday. No adjustment yet, just intake and evaluation. Flavia doesn't get it, and it's not worth arguing. I wanted to go back and get adjusted ASAP... I'm in pain every day for years, and this is my first chance for hope of change. She's worried about driving to the same place twice in a day? WTF?! Whatever...<br />
<br />
<br />
I had a big headache after the stretching evaluation. I woke up at 2am with no headache, but I can't get back to sleep.<br />
<br />
Topos: Strategic position of opportunity and influence<br />
<br />
Where did I hear that from?<br />
<br />
There are so many businesses without a website or Facebook page. Why? In 2015, where everything is plug and play ready? Am I really the right person for that job though? I'm not a web designer. Then again, maybe that's the point. Maybe some web designer who wants to charge the small business owner $2,000.00 for a new website is THE REASON why the owner chooses to go without one.<br />
<br />
What would it look like for me to do some basic consulting?<br />
<br />
I'd TELL their story. I'm a story teller. THAT is what I do. That is the hinge point of great marketing. The technical stuff we can outsource if need be. I can ask them questions, gather pictures, history, absorb the data, and then tell their story. I can put that together in a basic web page. Help them get onto Facebook and Google Place. Help them create some easy hand out / tip sheet for adding value to their customer's and gathering email addresses.<br />
<br />
I'd use Blogger, Google Place, and Facebook as the trifecta of start up online presence (optionally twitter and pintrest).<br />
<br />
I'd also teach Etsy as an online market place for Creatives.<br />
<br />
I'd have a list of resources for people who do what I don't do. Comprehensive web design, more aggressive social marketing, etc.<br />
<br />
<br />
Tools:<br />
<br />
Blogger<br />
Domain.com<br />
Facebook<br />
Google Place<br />
MailChimp<br />
Gumroad or another way to store and deliver the PDF?<br />
<br />
<br />
<br />
--------------------------------------------------------------------------------------------------------------<br />
<br />
<br />
Darrell,<o:p></o:p><br />
<br />
Oh my ... I can only imaging what would happen if you and my husband got
together ... ideation OVERLOAD! :-)<o:p></o:p><br />
<br />
I love all these ideas. But if the truth be told ... I'm glazing over again.
LOL&nbsp; But I will definitely forward this to the people who will know what
to do with all these ideas.<o:p></o:p><br />
<br />
I'm so excited to see how the Lord leads you on your journey. You and Flavia
are becoming two of my favorite people! I always enjoy visiting with you both
after checking the kids in. So glad to know you both!<o:p></o:p><br />
<br />
Blessings,<o:p></o:p><br />
<div class="MsoNormal">
---<o:p></o:p></div>
<pre><span style="font-family: &quot;Arial&quot;,sans-serif; font-size: 12.0pt;">Sandy Joanis&nbsp;

Amazing Kids Check-in Coordinator&nbsp;

Gateway Church NFW&nbsp;

817-480-1770&nbsp;

Woo | Developer | Harmony | Includer | Positivity</span><o:p></o:p></pre>
On 10/18/2015 5:41 pm, Darrell Wolfe wrote:<o:p></o:p><br />
<div class="MsoNormal">
<!-- html ignored --><!-- head ignored --><!-- meta ignored --><!-- meta ignored -->Hey
Sandy,<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I
have <em><b>lots</b></em> of random thoughts from today. I’ll try to organize
them into some kind of flow. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
What’s
funny is, I feel like I have everything I need from the perspective of how to
get business. I just can’t get myself to focus on a single business idea to
grow it. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
You
mentioned two of my favorite names on the internet: <o:p></o:p></div>
<div class="MsoNormal" style="margin-left: .5in; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="margin-left: .5in; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<a href="http://patflynn.com/">Pat Flynn</a> and <a href="http://michaelhyatt.com/">Michael Hyatt</a> are both AWESOME! <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I’ve
listened to both of their podcasts for a few years now. <a href="http://www.sethgodin.com/sg/">Seth Godin</a> and <a href="http://www.chrisducker.com/">Chris Ducker</a> are some interesting ones
to read/listen to if you get a chance.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Pat
Flynn has 3+ separate podcasts now. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoListParagraph" style="text-indent: -.25in;">
<span style="font-family: Symbol;">·</span><span style="font-size: 7.0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>His main site is <a href="http://www.smartpassiveincome.com/passive-income-101/">SmartPassiveIncome.com</a>.
His primary 45 minute podcast goes by the same name in iTunes. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoListParagraph" style="text-indent: -.25in;">
<span style="font-family: Symbol;">·</span><span style="font-size: 7.0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>He also has a shorter one called <a href="http://www.smartpassiveincome.com/ask-pat/">AskPat</a>.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoListParagraph" style="text-indent: -.25in;">
<span style="font-family: Symbol;">·</span><span style="font-size: 7.0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>His other site and podcast, which I think you would get a kick out of,
is 1-Day Business Breakthrough (<a href="https://1daybb.com/">1daybb.com</a>).
He co-hosts that with Chris Ducker. That one is interesting because they take a
person’s business who volunteers to sit on the “hot seat”, and present their
one biggest problem. Then they dissect and advise for 15 minutes. They do both
online and brick and mortar businesses (but specialize in the online aspects of
both). <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
From
an internet marketing perspective, there are a few things that I think Pat
Flynn would call basic-need-to-know’s. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I
feel like I could/should be doing all of these myself, if I only had a product
or service to offer that was worth investing in… Hmm… I’ve been pondering that
for a while. Started several and dropped them. Curse of the perfectionist I
suppose. Or curse of Ideation… lol…<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
But
that’s a conversation for another day.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Anyway…They
are…<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<strong>Advertising
and Landing Pages</strong><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
You
don’t seem to lack ideas for how to advertise. But here are some ideas on what
to do with it.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Any
advertising you do (paper flyers, offline to online, Facebook, etc.) should
have the singular purpose of directing people to a “landing page”. The landing
page can be hosted on your site, but should take them to a special page, not
just the home page. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal" style="margin-left: .5in; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
Example an ad ending: <o:p></o:p></div>
<div class="MsoNormal" style="margin-left: .5in; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<em>“Visit OfferName.KetosCreative.com for a special offer.”</em><o:p></o:p></div>
<div class="MsoNormal" style="margin-left: .5in; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<em>“Visit KetosCreative.com/OfferName for an exclusive
offer.”</em><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
And
then that site-page would be set up for two purposes. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoListParagraph" style="text-indent: -.25in;">
1.<span style="font-size: 7.0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>To sell that special offer
(whatever it may be) (should provide great value to the individual)<o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -.25in;">
2.<span style="font-size: 7.0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Get their email address<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
They
have to deliver their first and last name, and email, to get the offer. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<strong>Offer:</strong><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
The
offer could be anything that provides intense value, and increases their
curiosity about your story/brand. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Ideas
could be (reduced enrollment, special session, or even just a special pdf
handout, mini book, or CD, or….? You’re creatives I’m sure you’ll have ideas). <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I
like the single hand out, mini book, or CD/DVD/MP3/MP4, because the best offer
provides immediate reward. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal" style="margin-left: .5in; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
You tell me that you can help me do XYZ in less than 10
minutes, I do what you tell me, and I accomplish XYZ to my own utter amazement!
NOW I want to know what else you can do for me. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
What’s
great about that, is that this is what <em><b>you</b></em> are already doing
with your play now teaching style anyway. So I’m sure you’ll have ideas on what
your offer(s) could be. You can even try different offers for different events.
Have special landing pages for each.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal" style="margin-left: .5in; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<em>Note for your internet web geek: if you want to hide the
link to the pdf or mp3 on the site just make sure the download page is set to
“no follow” and don’t link it anywhere on the site, only link them in the ad
flow. That should keep people from getting to them accidentally. If a few find
them accidentally, Hurrah! They’ll get great value, and want to come back for more.
It’s ok.</em><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
In
essence, you did this for me personally already. In your 5-minute drum lesson
demo when I was there on open house day. I sat with your drum person, and when
I left I said “Hey… I could do this…” and even though I’ve been too busy to
come back so far, it’s still in the back of my mind… burning… “<em>go back… go
back….</em>”. Your offer, whatever it may be, should do the same thing that
drum lesson did to me, in the minds of those who get your offer. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Remember,
your brand is your story. You live to create, you love to teach. Tell that
story at every interaction point. So tell your story while you sell the offer. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<strong>Email
List: </strong><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
There
are many great services to manage an email list. I’ve tried most of them and my
favorite is “<a href="http://mailchimp.com/">MailChimp</a>”. It’s free to get
started (great feature) and you can pay for additional space and services after
the list starts being profitable. Once you get enough going to start paying for
anything, you can start writing that off as a business expense too.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Regardless
of which program you use, the point of the email list is to deliver value again
and again to your list. The subscribers should be on the edge of their seat for
your next email. However, how to go about that varies from person to person,
business to business. I’ve seen some that turned me off. So you have to find
your own way that works for you. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<strong>Bring
me back, remind me why I need you and your business in my life</strong>:<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
One
reason more blogs show up on Google Searches than static sites, is because
continuously updating content means fresh content and ideas. Some kind of
updating blog feed on your site is a great way to bring repeat traffic and
business. If you have no updating feed, then I see your site once, think
“that’s really cool” and then get busy and forget about it. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
The
feed doesn’t have to be a written post. I could be a YouTube video, podcast
update, or a mix of many things.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Give
me a reason to come back to your site as often as you can remind me. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
The
two components of that are:<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoListParagraph" style="text-indent: -.25in;">
1.<span style="font-size: 7.0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Having a site with updating content<o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -.25in;">
2.<span style="font-size: 7.0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Having an email list to remind
people to come back<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
The
content of the emails and site could be a variety of things.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<strong>As
to what goes into that email and site feed.</strong><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
It
could be a blog feed, podcast feed, just an actual letter from you to your
Creatives about the things you’ve been doing at Ketos Creative. Jesse Duplantis
said it best:<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal" style="margin-left: .5in; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<em>“Always tell them what you did, what you are doing, and
what you are going to do.” </em><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<strong>Content:</strong>
You could explore what you’ve been doing, tell stories about the business,
students, accomplishments, something you’ve learned, a break through your
student had, anything really. You could write about industry news, new tech,
creative ideas, creative tips, etc, etc… <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<strong>Student
led opportunities:</strong> Whatever avenue, or avenues, you choose could be at
least partially student led. Put them to work, teach, but get something out of
it for the business too. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<strong>Blog:</strong>
You could write about these things. Post weekly, monthly, as often or seldom as
you want. Regular is more important than frequent. If I know you have a monthly
newsletter, with all kinds of updates, I’ll be expecting. If I know you’ll be
having a weekly tip, I’ll expect that. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<strong>Podcast/VideoPodcast:</strong>
The benefit of adding video, is that you can use iTunes Audio, iTunes Video,
and YouTube all at once. I know personally, I’m more likely to listen to a
podcast on the go than I am watch a video, or read an article. But I find
articles and videos helpful when I’m looking for some instruction that is
specific to the task at hand. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<strong>NewsLetter:</strong>
Similar to the blog post, but this could be done monthly, have multiple
articles, and other news updates. Think “Gateway Life”. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Any
combination of these could be included in an email format through MailChimp,
and have links back to your site with encouraging “Calls to Action” to get
people back to the site. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<strong>Another
Ketos Service: Podcast Assistance</strong><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I
like the podcast too, because you could even offer that as a service. If people
want to podcast, but have ZERO technical ability or equipment, they could come
in to your studio for 30 minutes, record a session, and you can splice (and
create) their intro music and voice over… etc. Then send them the MP3/MP4. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I
THINK that’s all of what you saw going through my head… I’m sure I’ll think of
something else. I’ll let ya’ll digest that for now. <o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto; text-indent: .5in;">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;Tempus Sans ITC&quot;; font-size: 18.0pt;">Shalom!<!-- o ignored --></span><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;Tempus Sans ITC&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><o:p></o:p></div>
<div class="MsoNormal">
<span style="font-family: 'Tempus Sans ITC';">Author | INFJ | Intelection,
Learner, Ideation, Achiever, Input</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto; text-indent: .5in;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto; text-indent: .5in;">
<span style="color: #0072bc; font-family: &quot;Georgia&quot;,serif;"><a href="http://darrellwolfe.blogspot.com/">www.DarrellWolfe.Com</a><!-- o ignored --></span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto; text-indent: .5in;">
<span style="color: grey; font-family: &quot;Georgia&quot;,serif;"><a href="https://twitter.com/DarrellWolfe">Twitter: @DarrellWolfe</a></span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto; text-indent: .5in;">
<span style="color: #0072bc; font-family: &quot;Georgia&quot;,serif;"><a href="mailto:Darrell@DarrellWolfe.Com">Darrell@DarrellWolfe.Com</a></span><o:p></o:p></div>
<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->







<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->



<!-- o ignored -->



<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->



<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->







<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->







<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->



<!-- o ignored -->





<!-- o ignored -->







<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->





<!-- o ignored -->









<!-- o ignored -->



<!-- o ignored -->







<!-- o ignored -->



<!-- o ignored -->

<br />
<div class="MsoNormal">
<br /></div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
*******<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />