---
title: 'Personal Ministry with Mike and Ricky - March 25 2015'
date: '2015-03-25T12:08:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7550782919102661359'
blogger_filename: '/2015/03/personal-ministry-march-25-2015.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Counsel'
---

<div style="border-width: 100%; direction: ltr;">
<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 10.3229in;">
<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 10.3229in;">
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Mending the soul</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Mike Bradford</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Ricky Vargas</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Insecurity/Not Good
Enough/Inadequate</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Inadequate - Women,
Heading House, Leading Team, Pastoral Roles…</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Sabotaging
promotions.&nbsp; </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Got a promotion to a
leadership role and felt sad afterward. Inadequate. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Wife Arguments
usually revolve around my being head of the house, inadequate. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Dreams as a kid,
seeing but not being able to do/accomplish… See Devin tied to the bottom, but
being powerless to do anything about it. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Not being
validated/acknowledged by parents. I came to my mom and she either couldn't see
me for who I was, or didn't know what to do about it, or both. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
I had to kick dad
out, she should have had to do it, that's a mother/father wound. A child
shouldn't have had to go through that. A child shouldn't have to cheer on or
take care of their parent. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
It's clear that you
have a strong gifting in the prophetic, seeing things. You've had that blocked
by this feeling of inadequacy. Let it go. Only God is fully adequate. Only HE
can do it all. You are not enough, HE is enough in you . </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Spend time
developing your ear/meditating, listening. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Practice: Where is
the treasure today? I see a kid in a red hat. What does God want you to do?
Tell them this, write it down. The kid was sad because he didn't see a miracle
one day. Miracles SHOULD be normal. Stop calling yourself weird, accept that it
should be weird NOT to have supernatural things happening in your life. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Ask God for more
dreams. You may need someone to help you process this dream you had today, I
think there is a lot of meet there. Who was the man you ministered to? Who was
this pastor? Who was the woman who said "I'm so excited for this new
opportunity? Could it be that you thought you had one kind of ministry (laying
hands on many) but you are actually called to spend that longer quality time
with the one? How did you feel before during and after this dream/event? Why
did you feel that way? What words were tied to those feelings? </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Etc… He said: I
think we could help, but I feel like there someone else you need to reach out
to and share these dreams/visions AND ministry calling with. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Scott Graham?</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Joshua and Daniel
are Characters that come to mind for you. Joshua had dreams and visions?
Really? Hmm….</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Just like God freed
you in 30 seconds from a six year bondage/desire… he can free you in 30 seconds
from this. Let him. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
I'm really sorry
that happened to you. I think there is more hurt in that story than you admit…
not just hurt that Devin went awol, but more specifically in that you were
seeing and not able to do anything and felt inadequate because of it. You are a
seer. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
You may have a
non-functional definition of leadership. You probably know this in your head,
but never got it down in your heart. Leadership is just Service. If you serve,
you lead. So go serve. Serve in any and every capacity available to you… as you
serve, your arena of service will expand. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Delegation is part
of service, you must be willing to allow others to fail. You must be willing to
allow others to express through who they are. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Choose an area of
service, cast lots. Get connected. You need connections. Look into the
book/group Mending the soul. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
...</div>
</div>
</div>
</div>
