---
title: 'Dream Kaylee Sodas 02/08/15'
date: '2015-02-08T13:10:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2905940080720756195'
blogger_filename: '/2015/02/dream-kaylee-sodas-020815.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'dream'
---

<div style="border-width: 100%; direction: ltr;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.0798in;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.0798in;">

<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
2/8/15</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Flavia and I and the
boys were at a water park with Mike and Kaylee.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Boys innocently
grabbed sodas from a cart, and I had to buy them. The guy charged me $5 for two
cans. I gave him a $20 and he only gave me $1.85 in change. Then denied it.
Then tried to show me he was having an affair with Flavia, but it wasn't her. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
He left, so I tore
up his cart, and left. Took the boys and yelled at them, and left the park with
them. BUT, left Kaylee asleep on the ground by the chairs. I called my Dad,
he'd left her there too. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Flavia and I, and
some other girl, were trying to break back into the park secretly, I had to
rescue the other girl, and kill a guard dog. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Never got in.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
†*************</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
I woke up, thinking
" The boys made an innocent mistake, and you blew up at them. I guy stole
your money and lied about your wife and you passive-agreessively ripped up his
cart. Then, you forgot about Kaylee, and left her in that guarded prison.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
..</div>
</div>
</div>
</div>
