---
title: 'Dream Boys and Soda, Leaving Kaylee'
date: '2015-02-08T13:46:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8953134868248005193'
blogger_filename: '/2015/02/dream-boys-and-soda-leaving-kaylee.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'dream'
---

<br />
<br />
<br />
<br />


<br />
<div style="border-width: 100%; direction: ltr;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.109in;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.109in;">

<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
2/8/15</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Flavia and I and the
boys were at a water park with Mike and Kaylee.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Boys innocently
grabbed sodas from a cart, and I had to buy them. The guy charged me $5 for two
cans. I gave him a $20 and he only gave me $1.85 in change. Then denied it.
Then tried to show me he was having an affair with Flavia, but it wasn't her. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
He left, so I tore
up his cart, and left. Took the boys and yelled at them, and left the park with
them. BUT, left Kaylee asleep on the ground by the chairs. I called my Dad,
he'd left her there too. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Flavia and I, and
some other girl, were trying to break back into the park secretly, I had to
rescue the other girl, and kill a guard dog. Who is she? My daughter that hasn't been born yet? She was older though, a teen? A way for my imagination to play out rescue without putting meaning on who it was? Hmm..</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Never got in.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
†*************</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
I woke up, thinking
" The boys made an innocent mistake, and you blew up at them. I guy stole
your money and lied about your wife and you passive-aggressively ripped up his
cart. Then, you forgot about Kaylee, and left her in that guarded prison.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
&nbsp;**************</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<h4 style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
&nbsp;I learned</h4>
<ul>
<li>I need to be gently and kinder to the boys. Things they do are just not that important. If you are frustrated or disappointed, be so quietly before God, not loudly before them. </li>
<li>I do trust Flaiva, and I am jealous for her. </li>
<li>I've forgotten about Kaylee, left her behind in the spiritual realm. Just because she is not with us Physically, doesn't mean that I can guard her Spiritually from here. </li>
<li>I need to pray for all three of them. </li>
</ul>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
..</div>
</div>
</div>
</div>
