---
title: 'Creative Writer and Pastor to Creatives'
date: '2015-11-07T21:15:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3717748153168249198'
blogger_filename: '/2015/11/creative-writer-and-pastor-to-creatives.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Word From God'
  - 'Journal'
  - 'Revelation'
  - 'Vision'
---

<br />
<br />
<div class="MsoNormal">
<br /></div>
<blockquote class="tr_bq">
<span style="font-family: &quot;Verdana&quot;,sans-serif; font-size: 10.0pt;">“Everyone
needs encouragement! Successful people are different because their needs
generally do not scream at you. Like Don (rich man in Rick’s story), they wait
until they find a person they respect and trust, someone who understands them
and cares enough to meet them where they feel most comfortable. Then they will
open up, and you will find they are really a lot like you.” Rick Bezet – Be
Real, because fake is exhausting</span><span style="font-family: &quot;Verdana&quot;,sans-serif; font-size: 10.0pt;">&nbsp;</span></blockquote>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<br />
<div class="MsoNormal">
<span style="font-family: &quot;Verdana&quot;,sans-serif; font-size: 10.0pt;">I
continually feel that I am called to pastor Creatives (including famous people
that others would be star struck by).</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;Verdana&quot;,sans-serif; font-size: 10.0pt;"><br /></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;Verdana&quot;,sans-serif; font-size: 10.0pt;"><br /></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;Verdana&quot;,sans-serif; font-size: 10.0pt;"><br /></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;Verdana&quot;,sans-serif; font-size: 10.0pt;">Excerpt from my email to Olivier:</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;Verdana&quot;,sans-serif; font-size: 10.0pt;"><br /></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;Verdana&quot;,sans-serif; font-size: 10.0pt;"><br /></span></div>
<div class="MsoNormal">
<span style="font-family: 'Times New Roman', serif; font-size: 12pt;">I’m praying the last few weeks about my calling and purpose. I’m
tired of waiting for it to come on me and hit me in the head. It’s time to
pursue it actively through prayer. I don’t want to be working at Wells Fargo 10
years from now. <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: 'Times New Roman', serif; font-size: 12pt;">One consistent thing that keeps coming up is Storytelling. There
are thousands of “How To” and “Six steps to” books on the Christian market.
There are a handful of decent Christian fiction writers. But what I’ve noticed,
is that fiction sticks with you in a way that nonfiction doesn’t.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: 'Times New Roman', serif; font-size: 12pt;">I cannot remember the six steps to excellence in ministry, but I
can remember how I felt with Frodo climbed the mountain to through the ring
into the fire. Then it struck me, what if I could impact you through fiction,
tell you what I wanted you to know, without you really knowing I told you until
it was over? <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: 'Times New Roman', serif; font-size: 12pt;">What if Fiction was my ministry, or a part of it? More
specifically, what if story telling was? Writing, Theatre, Speaking, Preaching…
All from the theme of Storytelling. <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: 'Times New Roman', serif; font-size: 12pt;">My Co-Workers have pointed out many times over the years, that I
am a story teller. My passion is for great story telling. I can identify themes
and plot holes in movies and shows quickly. <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: 'Times New Roman', serif; font-size: 12pt;">Then this last week, at the Gateway Men’s Night, Jase Robertson (</span><a href="https://en.wikipedia.org/wiki/Jase_Robertson"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt;">here</span></a><span style="font-family: 'Times New Roman', serif; font-size: 12pt;">) of
Duck Dynasty, was the speaker. What interested me most, was that he is not a
preacher, not a teacher, yet he had a message. He told stories about his life,
crazy family, and duck calls, yet weaved through that a message of salvation,
and 100’s of men came to get saved. He’s an evangelist even if he wouldn’t say
so. All through entertaining story telling… He kind of reminds me of Jesse
Duplantis in that way. <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: 'Times New Roman', serif; font-size: 12pt;">That inspired me, and it was queue #104 this year, that story
telling is what I should be focused on. <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: 'Times New Roman', serif; font-size: 12pt;">It’s funny, I can dissect information, parse truth, and teach. I
can go toe to toe with intellectuals. But my writing in that genre ends up
stale to me. It feels dry, or forced, or…? Something… <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: 'Times New Roman', serif; font-size: 12pt;">Story telling… that’s where my strength lies. That doesn’t mean
Fiction only either. Just telling stories in general, true, fiction, parable,
they are all teachable…. <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: 'Times New Roman', serif; font-size: 12pt;">Come to think of it… Jesus did this, didn’t he? Parables were his
#1 tool. I feel dumb for not seeing that before JUST now… I’m going to copy
myself on this email and retain this for future reference. <o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: 'Times New Roman', serif; font-size: 12pt;">&nbsp;</span><span style="font-family: &quot;Verdana&quot;,sans-serif; font-size: 10.0pt;">&nbsp;<o:p></o:p></span></div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />