---
title: 'NFW - Sunday 11/08/15 - Prodigal Lessons'
date: '2015-11-09T06:01:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3595876612910036853'
blogger_filename: '/2015/11/nfw-sunday-110815-prodigal-lessons.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Word From God'
  - 'Revelation'
  - 'Church Notes'
---

<br />
<br />
Word: Through stories, you will find truth implanted and made real. Stories connect the truth you know to the truth you believe.<br />
<br />
Note after meeting a couple (guy from the Men's group): You don't remember his name. You didn't ask hers. You were only conscious of your un-comfortableness, and did nothing to make it about them. Become focused on others, use your input strength to get input from them by asking as many questions as you can.<br />
<br />
<br />
Abraham was asked to surrender his promise to die, in order to receive it back to life again. What promises are you holding onto, that you need to let die, so that something better can rise in it's place?<br />
<br />
The past is dead, let it die. Look to the future.<br />
<br />
We could be playing high cards in many areas, but leaving a door open to the enemy to play a low trump card in our lives.<br />
<br />
Luke 15 - Prodigal<br />
<br />
He left only a few days after the inheritance was split. In other words, he was planning this all along. He had it in his mind before it was ever split. It was part of his thinking, imagining, and self-story-telling.<br />
<br />
<blockquote class="tr_bq">
<i>"If only I could go with the money now, and live it up, that would be the life... "</i></blockquote>
<br />
1. Secrets<br />
<br />
Secret thoughts, imaginations, image, I make I become.<br />
<br />
Ex: Don't imagine a good marriage with another woman, imagine a good marriage with the woman you have.<br />
<br />
Ex: Don't imagine being rich <i>someday</i>, imagine being generous now.<br />
<br />
<br />
Gen 1: Darkness, the place where Satan resides.<br />
<br />
Jude 6: Darkness, This is where secrets live. The best thing to do with secret thoughts, is bring them to the light. Darkness will always be displaced by light, without any further effort than that. Bring them into the light, and keep them there.<br />
<br />
Ex: man left his family; he connected to his other woman instead of his wife and fell in love. He should have shared those thing with his wife, connected to his wife, and fell in love with her.<br />
<br />
2. Sin<br />
<br />
This was going on in his heart before he left. Prodigal<br />
<br />
Edom-Red, wanted to Red Stew so much that he traded his blessing for it.<br />
<br />
Some scholars liken food to sex. Instant gratification for a moment, and destroying higher things to get it. One moment for the call of God?<br />
<blockquote class="tr_bq">
<i><br /></i><i>Sin will always take you father than you wanted to go, keep you longer than you wanted to stay, and cost you more than you wanted to pay. Jesse D.</i></blockquote>
<br />
3. Shame<br />
<br />
What was his life after he came home? He still had no money. People most likely talked (there he goes... the boy who broke his father's heart). He still had images in his heart and mind of the places he'd gone, things he'd done, things he'd seen.<br />
<br />
<br />
Heb 12<br />
1 Cor 1:18<br />
<blockquote class="tr_bq">
<i><br /><span class="versiontext" style="background-color: #fdfeff; color: #0092f2; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 14px; font-weight: 700; line-height: 20px;"><a href="http://biblehub.com/esv/1_corinthians/1.htm" style="color: #99d6ff; text-decoration: none;">English Standard Version</a></span><span style="background-color: #fdfeff; color: #001320; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 14px; line-height: 20px; text-align: justify;">For the word of the cross is folly to those who are perishing, but to us who are <b><u>being </u></b>saved it is the power of God.</span></i></blockquote>
<br />
People in shame often talk too much, to convince others they are better, or talk to little to hide who they are. Pride and Self Loathing, both results of shame.<br />
<br />
Be Ye Being Filled<br />
Be Ye Being Saved<br />
<br />
<blockquote class="tr_bq">
<i><br /></i><i>Eph 5:18</i><i><span class="versiontext" style="background-color: #fdfeff; color: #0092f2; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 14px; font-weight: 700; line-height: 20px;"><a href="http://biblehub.com/esv/ephesians/5.htm" style="color: #99d6ff; text-decoration: none;">English Standard Version</a></span></i><i><span style="background-color: #fdfeff; color: #001320; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 14px; line-height: 20px; text-align: justify;">And do not get drunk with wine, for that is debauchery, but be filled with the Spirit,</span></i></blockquote>
<br />
<blockquote class="tr_bq">
<i><span class="reftext" style="background-color: #fdfeff; color: #001320; font-family: Arial, Helvetica, sans-serif; font-size: 11px; line-height: 14px; margin-left: 1px; margin-right: 2px; text-align: justify; text-indent: 25px; vertical-align: text-top;"><a href="http://biblehub.com/ephesians/5-15.htm" style="color: #0092f2; text-decoration: none;"><b>15</b></a></span><span style="background-color: #fdfeff; color: #001320; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 15px; line-height: 21px; text-align: justify; text-indent: 25px;">Look carefully then how you walk, not as unwise but as wise,&nbsp;</span><span class="reftext" style="background-color: #fdfeff; color: #001320; font-family: Arial, Helvetica, sans-serif; font-size: 11px; line-height: 14px; margin-left: 1px; margin-right: 2px; text-align: justify; text-indent: 25px; vertical-align: text-top;"><a href="http://biblehub.com/ephesians/5-16.htm" style="color: #0092f2; text-decoration: none;"><b>16</b></a></span><span style="background-color: #fdfeff; color: #001320; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 15px; line-height: 21px; text-align: justify; text-indent: 25px;">making the best use of the time, because the days are evil.&nbsp;</span><span class="reftext" style="background-color: #fdfeff; color: #001320; font-family: Arial, Helvetica, sans-serif; font-size: 11px; line-height: 14px; margin-left: 1px; margin-right: 2px; text-align: justify; text-indent: 25px; vertical-align: text-top;"><a href="http://biblehub.com/ephesians/5-17.htm" style="color: #0092f2; text-decoration: none;"><b>17</b></a></span><span style="background-color: #fdfeff; color: #001320; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 15px; line-height: 21px; text-align: justify; text-indent: 25px;">Therefore do not be foolish, but understand what the will of the Lord is.&nbsp;</span><span class="reftext" style="background-color: #fdfeff; color: #001320; font-family: Arial, Helvetica, sans-serif; font-size: 11px; line-height: 14px; margin-left: 1px; margin-right: 2px; text-align: justify; text-indent: 25px; vertical-align: text-top;"><a href="http://biblehub.com/ephesians/5-18.htm" style="color: #0092f2; text-decoration: none;"><b>18</b></a></span><span style="background-color: #fdfeff; color: #001320; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 15px; line-height: 21px; text-align: justify; text-indent: 25px;">And do not get drunk with wine, for that is debauchery, but be filled with the Spirit,&nbsp;</span><span class="reftext" style="background-color: #fdfeff; color: #001320; font-family: Arial, Helvetica, sans-serif; font-size: 11px; line-height: 14px; margin-left: 1px; margin-right: 2px; text-align: justify; text-indent: 25px; vertical-align: text-top;"><a href="http://biblehub.com/ephesians/5-19.htm" style="color: #0092f2; text-decoration: none;"><b>19</b></a></span><span style="background-color: #fdfeff; color: #001320; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 15px; line-height: 21px; text-align: justify; text-indent: 25px;">addressing one another in psalms and hymns and spiritual songs, singing and making melody to the Lord with your heart,&nbsp;</span><span class="reftext" style="background-color: #fdfeff; color: #001320; font-family: Arial, Helvetica, sans-serif; font-size: 11px; line-height: 14px; margin-left: 1px; margin-right: 2px; text-align: justify; text-indent: 25px; vertical-align: text-top;"><a href="http://biblehub.com/ephesians/5-20.htm" style="color: #0092f2; text-decoration: none;"><b>20</b></a></span><span style="background-color: #fdfeff; color: #001320; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 15px; line-height: 21px; text-align: justify; text-indent: 25px;">giving thanks always and for everything to God the Father in the name of our Lord Jesus Christ,&nbsp;</span><span class="reftext" style="background-color: #fdfeff; color: #001320; font-family: Arial, Helvetica, sans-serif; font-size: 11px; line-height: 14px; margin-left: 1px; margin-right: 2px; text-align: justify; text-indent: 25px; vertical-align: text-top;"><a href="http://biblehub.com/ephesians/5-21.htm" style="color: #0092f2; text-decoration: none;"><b>21</b></a></span><span style="background-color: #fdfeff; color: #001320; font-family: Trebuchet, Arial, Helvetica, sans-serif; font-size: 15px; line-height: 21px; text-align: justify; text-indent: 25px;">submitting to one another out of reverence for Christ.</span></i></blockquote>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />