---
title: 'Email Chain with Bill Myers - Saved for future reference'
date: '2015-12-02T04:13:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7175674672139707068'
blogger_filename: '/2015/12/email-chain-with-bill-myers-saved-for.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Counsel'
  - 'Answers'
  - 'Life Events'
---

<br />
<h4>
Email Chain with Bill Myers - Saved for future reference</h4>
<br />
<br />
-------------------------------------------------------------------------<br />
<br />
<br />
<br />
<div class="MsoNormal">
<a href="https://draft.blogger.com/null" name="_MailEndCompose">Hey
Bill,</a><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Thanks for taking the time to
respond, you must get lots of correspondence. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
This was all very good advice,
which I have now saved for future reference and reminders. I’m planning on
self-publishing, so I’ll make a point to find a good editor. I’ve also
considered joining a writing group locally. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I self-published a non-fiction book
back in 2010 and made it available through Kindle, Amazon as a paperback, and I
provide the PDF version direct on my website under my name your own price
policy. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
For now, I’m just enjoying the
writing. I’ll let God decide how many copies he wants to sell.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I’ll save this email so I can
remember that going through a 5<sup>th</sup> re-write is perfectly acceptable.
I may have been a bit of a perfectionist the last go-around. I’m learning to
let loose a little this time.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
It’s funny you mention abiding, as
that has been His key lesson to me this past two years. This was yet another
great reminder. Almost every time I think He’s showing me a new topic, it ends
up coming back to “Be Still, Be Led”.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Anyway, sorry for raving. I
appreciate that you took the time to respond. I just finished re-reading The
Voice, and I&nbsp; felt compelled to say “Hi”. My wife and her mom read
everything you publish, and turned me on to your work a few years ago. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I wish you all the best continued
success. Keep writing and challenging us to think and grow spiritually, while
we’re being entertained. We’ll keep reading. <o:p></o:p></div>
<div class="MsoNormal" style="text-indent: .5in;">
<br /></div>
<div class="MsoNormal">
<span style="font-family: 'Tempus Sans ITC'; font-size: 18pt;">Shalom!<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: 'Tempus Sans ITC'; font-size: 18pt;">Darrell G. Wolfe</span><o:p></o:p></div>
<div class="MsoNormal">
<span style="font-family: 'Tempus Sans ITC';">Story
Teller | INFJ | Intelection, Learner, Ideation, Achiever, Input</span><o:p></o:p></div>
<div class="MsoNormal" style="text-indent: .5in;">
<br /></div>
<div class="MsoNormal" style="text-indent: .5in;">
<a href="http://darrellwolfe.blogspot.com/" target="_blank"><span style="font-family: &quot;Georgia&quot;,serif;">www.DarrellWolfe.Com</span></a><span style="color: #0072bc; font-family: &quot;Georgia&quot;,serif;"><o:p></o:p></span></div>
<div class="MsoNormal" style="text-indent: .5in;">
<a href="https://twitter.com/DarrellWolfe" target="_blank"><span style="font-family: &quot;Georgia&quot;,serif;">Twitter: @DarrellWolfe</span></a><u><span style="color: blue;"><o:p></o:p></span></u></div>
<div class="MsoNormal" style="text-indent: .5in;">
<a href="mailto:Darrell@DarrellWolfe.Com" target="_blank"><span style="font-family: &quot;Georgia&quot;,serif;">Darrell@DarrellWolfe.Com</span></a><u><span style="color: blue; font-family: &quot;Georgia&quot;,serif;"><o:p></o:p></span></u></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b><span style="font-family: &quot;Calibri&quot;,sans-serif; font-size: 11.0pt;">From:</span></b><span style="font-family: &quot;Calibri&quot;,sans-serif; font-size: 11.0pt;"> Bill Myers [<a href="mailto:bill@billmyers.com">mailto:bill@billmyers.com</a>] <br />
<b>Sent:</b> Saturday, November 28, 2015 4:42 PM<br />
<b>To:</b> <a href="mailto:darrell@darrellwolfe.com">darrell@darrellwolfe.com</a><br />
<b>Subject:</b> Fwd: Contact Request From billmyers.com<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal" style="margin-bottom: 12.0pt;">
<br /></div>
<div class="MsoNormal">
Begin forwarded message:<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b><span style="font-family: &quot;Helvetica&quot;,sans-serif;">From: </span></b><span style="font-family: &quot;Helvetica&quot;,sans-serif;">Bill
Myers &lt;<a href="mailto:bill@billmyers.com">bill@billmyers.com</a>&gt;</span><o:p></o:p></div>
<div class="MsoNormal">
<b><span style="font-family: &quot;Helvetica&quot;,sans-serif;">Date: </span></b><span style="font-family: &quot;Helvetica&quot;,sans-serif;">November 28, 2015 at 2:39:49 PM PST</span><o:p></o:p></div>
<div class="MsoNormal">
<b><span style="font-family: &quot;Helvetica&quot;,sans-serif;">To: </span></b><span style="font-family: &quot;Helvetica&quot;,sans-serif;">Bill Myers &lt;<a href="mailto:bill@billmyers.com">bill@billmyers.com</a>&gt;</span><o:p></o:p></div>
<div class="MsoNormal">
<b><span style="font-family: &quot;Helvetica&quot;,sans-serif;">Cc: </span></b><span style="font-family: &quot;Helvetica&quot;,sans-serif;"><a href="mailto:darrell@darrewolfe.com">darrell@darrewolfe.com</a></span><o:p></o:p></div>
<div class="MsoNormal">
<b><span style="font-family: &quot;Helvetica&quot;,sans-serif;">Subject:
Re: Contact Request From <a href="http://billmyers.com/">billmyers.com</a></span></b><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Wow, Darrell. First of all thanks for the kind
comment.&nbsp;<o:p></o:p></div>
<div class="MsoNormal">
Second, there’s so much to say. But, I guess the most
important thing to writing is rewriting. I’m not saying stop and rewrite every
scene til it’s perfect before you go to the next (hint: no one writes perfect)
but set a easy word count per day for yourself and stick to it til you complete
the book. Then go back and rewrite. I wind up rewriting about 5 times til I
send it to folks I trust who point out errors and then I’ll rewrite it a couple
more times. I also listen to it read back to me by my computer (for free on a
Mac, a little bit more for a PC program) as it always points out things my eyes
skip over. Oh, and don’t give up. Like the little kid’s riddle asks, “How do
you eat an elephant?” A: “One bite at a time.” Tenacity also goes with finding
a publisher. I remember my pal Peretti was rejected 13 times before someone
finally thought, This Present Darkness was worth publishing. Finally, if you
self-pub, get an editor that you trust in both macro (story) and micro (line).
The good ones are worth their weight in gold. Hope that helps. And one more
thing. Getting published is not the end of the rainbow. Find your joy and
contentment in Christ during the right here and the right now. Success, no
matter how great, doesn’t bring it. Maybe for a few days, yes, but it then
becomes as empty as that Christmas gift you were dying for as a kid, and after
a few months completely forgot. Focus on abiding in God, not just weekly or
morningly. But learn to abide in him continually. It’s a trick, but learn to
quiet your soul and be in constant worship so the storms of success or failure
have little to do with your happiness. Learn to love the minute by minute
abiding in His presence and not in the success of a completed product.&nbsp;<o:p></o:p></div>
<div class="MsoNormal">
Okay, ending sermon now. Have fun. Bilbro<o:p></o:p></div>
<div class="MsoNormal">
&nbsp;&nbsp;<o:p></o:p></div>
<div class="MsoNormal">
On Nov 28, 2015, at 9:53 AM, Bill Myers Admin &lt;<a href="mailto:bill@billmyers.com">bill@billmyers.com</a>&gt; wrote:<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<table border="0" cellpadding="0" cellspacing="5" class="MsoNormalTable">
 <tbody>
<tr>
  <td colspan="2" style="padding: 3.75pt 3.75pt 3.75pt 3.75pt;">
  <div class="MsoNormal" style="margin-bottom: 12.0pt;">
<br />
  <br />
  <b><span style="font-size: 15.0pt;">Contact Bill</span></b><br />
  Want to ask a question or share a thought?<br />
  Simply use the form below.<o:p></o:p></div>
</td>
 </tr>
<tr>
  <td style="padding: 3.75pt 3.75pt 3.75pt 3.75pt;">
  <div class="MsoNormal">
<strong>Your Full Name</strong><o:p></o:p></div>
</td>
  <td style="padding: 3.75pt 3.75pt 3.75pt 3.75pt;">
  <div class="MsoNormal">
Darrell<o:p></o:p></div>
</td>
 </tr>
<tr>
  <td style="padding: 3.75pt 3.75pt 3.75pt 3.75pt;">
  <div class="MsoNormal">
<strong>Your Email</strong><o:p></o:p></div>
</td>
  <td style="padding: 3.75pt 3.75pt 3.75pt 3.75pt;">
  <div class="MsoNormal">
<a href="mailto:darrell@darrewolfe.com">darrell@darrewolfe.com</a><o:p></o:p></div>
</td>
 </tr>
<tr>
  <td style="padding: 3.75pt 3.75pt 3.75pt 3.75pt;">
  <div class="MsoNormal">
<strong>Your Message</strong><o:p></o:p></div>
</td>
  <td style="padding: 3.75pt 3.75pt 3.75pt 3.75pt;">
  <div class="MsoNormal">
I spent the last two years studying the craft of fiction,
  and I'm writing my first novel. I'm not worried about publishing at this
  point, just the craft. Bill, you are my favorite author. Any craft-level
  advice you give to up and coming authors? Darrell Wolfe <a href="mailto:darrell@darrellwolfe.com">darrell@darrellwolfe.com</a><o:p></o:p></div>
</td>
 </tr>
<tr>
  <td style="padding: 3.75pt 3.75pt 3.75pt 3.75pt;">
  <div class="MsoNormal">
<strong>Enter the code</strong><o:p></o:p></div>
</td>
  <td style="padding: 3.75pt 3.75pt 3.75pt 3.75pt;">
  <div class="MsoNormal">
xpa3q<o:p></o:p></div>
</td>
 </tr>
<tr>
  <td colspan="2" style="padding: 3.75pt 3.75pt 3.75pt 3.75pt;">
  <div class="MsoNormal" style="margin-bottom: 12.0pt;">
(All fields are required)<o:p></o:p></div>
</td>
 </tr>
</tbody></table>
<div class="MsoNormal">
<br />
<br />
Submitted by 141.0.9.78<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<br />
<div class="MsoNormal">
<br /></div>
