---
title: 'Gateway Personal Ministry - w/ Luke and Richard 01/28/15'
date: '2015-01-28T13:12:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8923736017551848379'
blogger_filename: '/2015/01/gateway-personal-ministry-w-luke-and_28.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Counsel'
---

<div style="border-width: 100%; direction: ltr;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.0861in;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.0861in;">

<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Belief thoughts
action reinforces belief</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Changing thoughts
and actions without changing belief is ineffective.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Don't ask is this
God or me? Ask is this life or death. Green until red. What is the fruit? If
you're producing fruit, is it life? If you are experiencing death your&nbsp; connected to item severe the connection. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
If you consider
bible and prayer Spirituality, are you putting God into a box. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
If the point of the
book is not leading to an experience with the author, the book is irrelevant.
Put the book down and listen and walk. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
God is more
concerned with who I am, not what I do. Why are asking what I should do??</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
...hearing is an
experience</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Mirrors</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Failure</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Hearing</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
You don't know what
you don't know.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Holds the world by
his word, the earth would implode if he stopped talking. 5 minutes</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Todd white</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Gram cook</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Hearts desires</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
With you</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
When the heart is
connected to love, Fear loses its rational grip on us.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Don't question it</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Richard -- Luke</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<span style="font-weight: bold;">Action plan… be still be led be open to the weird and
extra-ordinary</span></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
..</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Expounded</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
So on 01/28/15, I
went to Gateway Personal Ministry. I didn't know what to expect. It was a
little scary. After getting lost twice, and ending up inside the wrong Gateway
office, I finally reached my destination. I was ushered into the room with two
men. One about my age, maybe younger, and one about Rocky's age.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
After some
introductions, and commentary on my Superman Shirt, we got to talking. They had
reviewed my intro sheet I filled out ahead of time, and commented that I was an
open book. I stated that I was, in fact, you can read what I'm thinking on my
blog, I keep my life open.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 12.0pt; margin: 0in;">
<span style="font-weight: bold;">Belief - Thought - Action</span></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
So, as we got to
talking, the first thing that comes to memory, is the fact that Gateway Freedom
Ministries has several core beliefs. One of them is that we cannot deal with
matters of life through behavior, but through belief! That goes make to the
Levels of Change Foundation Class. Actions come from the variety of thoughts we
have. Thoughts are like branches that grow from the root of a belief. You
cannot deal with change at the level of actions or thoughts, as these just
manifest in different ways. When one is cut down, the next pops up. You cut off
Alcohol, and you are addicted to Dr. Pepper without realizing it. You cannot
deal with the substance, addiction, or behavior. That is irrelevant. You cannot
deal with the thoughts "I really want a ...." because that too, is a
symptom. You must, through the Holy Spirit, reveal the belief(s) that are
giving life to those thoughts, which are influencing those behaviors.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Beliefs gives birth
to thoughts, thoughts give birth to actions, and the resulting events that
arise from those actions reinforce the belief. This can be both a negative
and/or positive cycle, depending on what belief is in question.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
If I believe that
gravity causes me to fall, and I have thoughts that if I jump off of tables,
ladders, cars, roofs, I will fall... then I do some or all of these things and
it happens. This reinforces my belief.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Attempting to change
thoughts or actions without changing the belief root is ineffective at best.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 12.0pt; margin: 0in;">
<span style="font-weight: bold;">Hearing</span></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Don't ask "Is
this God, or is this me?" This is the wrong question for many reasons.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
1. God Speaks To and
Through Your Uniqueness.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
God doesn't just
speak in sentences, although he can and does do that. He also speaks in words,
images, visions, dreams, impressions, ideas, concepts, and more. God has also
given you a set of gifts, talents, and perspectives that, when put together,
are you uniquely yours. Then God puts ideas into your heart that align with the
way He's built you.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
So when I have an
idea for a story, or to go to certain place to minister to someone, or
whatever, it very well may sound like me. This because it is coming from God,
through my gifting, and resonating (bouncing around off of all of my giftings
and talents) in me.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
2. There were two
trees. Knowledge and Life.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
When man operates
without God, it looks like Knowledge. Religion attempts to overcome the
knowledge of Evil with the knowledge of Good. But the Knowledge of Good will
never re-connect you to LIFE, which is the real need of man. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
So do not attempt to
find the will or voice of God through Knowledge. "Is this God or is this
me?" attempts to rationalize the voice of God. This is almost like saying
"Does two plus two equal purple?" The question makes no sense. This
is because (as pointed in #1) we are built in a specific way, and God speaks to
us through our uniqueness. Also, we are built in the image of God. As with a
branch on a tree, as we get closer to Him, it gets harder and harder to
identify where one ends and the other begins. You can clearly see that the
branch is not the tree, and that the branch can be cut from the tree. But can
you honestly say that you can find the exact point at which a branch ceases to
be the branch and the tree begins? The joining point is so integrated, that is
become difficult to distinguish the point of separation. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
I feel
"stuck" in my Spiritual life.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
How you do you
define stuck?</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
I get real fired up
for God, and spiritual things. I'm in my bible and prayer time every morning.
Then after a number of weeks or months that wanes, and I wake up one day to
find that I haven't read my bible in months. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Have you considered
that it may be God, trying to get you to put your bible down and notebook down?</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
??</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
You stated that you
are an intellectual. You study. You study the words, the meanings, the
history... etc. God gave you those gifts and they are good. But consider this.
If you have read someone's book, and their Facebook profile. You know all their
stats. Do you KNOW them, do you have a living vibrant relationship with them (<a href="http://youtu.be/qM-gZintWDc">good will hunting</a>)(couldn't find the
scene "yeah I got plenty of mentors, Niche, Plato, etc")? No, you
just know about them. You don't know them. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
If the book is not
leading you to the author, put the book down, and go after the author. You are
so intellectual, that your disinterest in reading the bible during your
"devotional time" may be the Holy Spirit himself leading you to put
the bible down.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
This is not to say
that bible study is bad, or that you should stop it forever. This is to say
that God may want you to let Him out of the box, so that He can speak with you
in the 1,000's of ways that He wants to, instead of the three or four (Bible,
Journal, Prayer, Study) that you put Him into.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
If you are
experiencing this cycle of Spiritual Connectedness, followed by a disinterest
in your usual routine, then flowing into apathy, and this cycle has repeated
itself since you were a pre-teen. STOP the cycle!</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
God is not
interested in what you do, He is interested in who you are! He is not looking
for better behaviors, traditions, or rituals, he is looking for a vibrant
relationship.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Hearing is an
experience. You can't get hearing from reading. You can hear while you read, He
can speak to you through the words you read. But they are two separate things.
God can just as easily speak to your heart during a class taught by an atheist,
as He can through a sermon. But this will only happen if you are keeping your
lines of connection open and unplugged. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 12.0pt; margin: 0in;">
<span style="font-weight: bold;">Mirrors</span></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
You cannot know what
you look like without a mirror. In the natural, you cannot know what you look
like without a mirror. How will you know about the smudge on your forehead
without seeing it in a mirror? If someone tells you that it's there, how will
you know they are telling the truth? (I've seen people say it's there when it's
not just to mess with people).</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
God is your mirror.
You are made in his image. When you get close to Him, he reveals who and what
you are. But unlike a natural mirror, when you get close to God, you also
become more of who and what you are.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Other humans can
help with this process, they can point to the smudge they see, that you do not.
But some humans have a warped image, and therefore give you a warped
reflection. Therefore, you have to rely primarily on God as the revealing
image, and only those humans He leads you to. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Suggested I take a
look at <a href="http://lifestylechristianity.com/connect/#">Todd White</a> and
<a href="http://brilliantperspectives.com/">Graham Cooke</a>. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Thought: When the
heart is connected to LOVE, fear looses it's rational grip.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
My Achiever and
Intellection strengths have the tendency to make my relationship with God a
process (religion) as opposed to the vibrant flowing relationship that He
desires.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Past Words from God:</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
In the past years,
I've had God ask of me some interesting things. </div>
<ul style="direction: ltr; margin-bottom: 0in; margin-left: .375in; margin-top: 0in; unicode-bidi: embed;" type="disc">
<li style="margin-bottom: 0; margin-top: 0; vertical-align: middle;"><span style="font-family: Calibri; font-size: 11.0pt;">Sing to me like you did when
     you were younger.</span></li>
<li style="margin-bottom: 0; margin-top: 0; vertical-align: middle;"><span style="font-family: Calibri; font-size: 11.0pt;">Tell me a story.</span></li>
<li style="margin-bottom: 0; margin-top: 0; vertical-align: middle;"><span style="font-family: Calibri; font-size: 11.0pt;">Spend some time in the
     mornings being still. Just be still, no reading, praying, and be still.Be
     still and </span><span style="font-family: Calibri; font-size: 11.0pt; font-style: italic;">know </span><span style="font-family: Calibri; font-size: 11.0pt;">that I am God. This is one way to go from knowing about God to
     knowing God.</span></li>
</ul>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
It occurs to me
know, that they are all centered on getting out of routine and into
relationship.&nbsp; </div>
<div style="font-family: Calibri; font-size: 12.0pt; margin: 0in;">
<span style="font-weight: bold;">Assignment:&nbsp;</span></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Be still, be led, be
open to the weird and extra-ordinary ways God may want to communicate with you.
Follow the desires that come to your heart. If you feel he just says "go
for a walk", "listen to Lion King sound tracks", etc, don't question
it, just flow with it.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Be Still - Be Led -
Be Open. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
.....</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="https://draft.blogger.com/blogger.g?blogID=1992799306809150069#overview/src=dashboard">https://draft.blogger.com/blogger.g?blogID=1992799306809150069#overview/src=dashboard</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
</div>
</div>
</div>
