---
title: 'Dream, Go back in time? 02/05/15'
date: '2015-02-05T13:11:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5863251506754465529'
blogger_filename: '/2015/02/dream-go-back-in-time-020515.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'dream'
---

<div style="border-width: 100%; direction: ltr;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.0861in;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.0861in;">

<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
2/5/15</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Just woke up from a
vivid dream I was given the chance to go back in time. First, me and Connor and
Preston went to Agura Hills Church, and saw me as a kid. All dressed up in that
dumb little black suit. Just before service I walked into the Sanctuary and
passed by my younger then Dad. He was all focused on his message prep. I said
"Hey there." He said "Well hello." But kept walking.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
In service the man
in front of us set his bible on the floor on his left. We were sitting on the
very left of the left set of pews, 3/4 back. I pointed me out and kids got
excited. Connor knocked pap DDDers out of the mans bible, and he turned around
with a piercing stern look. I felt apologetic, and cleaned it up. I used my
customer skills to smooth him over. I feel now I was staring at angry me, and
it was awkward and uncomfortable.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Flash. New moment.
I'm by myself and I meet teen me. 14? I don't know where, space is irrelevant,
Young me turns around, laying with head up hands on chin, smiling. "There
you are. Its been years. I was wondering when you'd come back." Youngest
me had seen me in Augora. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Here's my
chance."If you could tell your younger self anything, what would you tell
him?" Apparently, I would tell him all the things/mistakes, to avoid. I
would tell him that he does meet the perfect wife, but it takes him 11 years of
marriage to realize itm because hes always looking for something he xqant quite
put hus finger on. Then I would realize that some of these mistakes led to
great experiences or outcomes.&nbsp; </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Somehow, I'm still
talking to him, but now he's on the telephone m and I'm at work. Keep getting
interrupted by the coworkers with problems. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Then, only as an
after thought, I would tell him what He could do make life better, KCM, Freedom
Ministries, Gateway, Joseph Prince... But only to realize young me has limited
ways to access these,&nbsp; becaus the internet
won't be invented for two more years, and it'll be crude at best fr several
more....</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Woke up.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
So. What did I
learn?&nbsp; </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Young me wasn't as
sad or depressed as I remembered. Sure, he had serious bouts with that demon
spirit, but overall he was a happy, well natured, easy going kid. He was
vibrant and energetic. He smiled more. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Old me is too
focused on actions, accomplishments, failures. Telling young me specific
actions or people to avoid solves nothing. Without a change if heart and mind,
young me may avoid certain mistakes, buyt will just make new ones, maybe worse
ones? </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
My mindset is off is
telling him about Gateway or KCM is an afterthought. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
I said nothing about
Jesus, or God, or the tools to be free. I just focused on failures he hadn't
had yet, and good "things" he could try.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
STORY IDEA: As q
resukt of ecposre to an ecpiriment, a man goes back in time to tell his younger
self things, and keeps messing things up worse and worse. Only to discover that
any attempts to repair the past are fruitless, however, he can change the future.
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
...........</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Lessons. Time with
HS</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
So? A life led by
the Spirit, surrendered to love, and focused on relationship instead of actions
and outcomes, is a life of victory. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
You cannot fix the
future by fixing the past. Only I can fix the past, by blood. Only I can fix
the future, by Grace, through relationship, resulting in Faith. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Just be led, instead
of trying to make things happen. If the vision is from me, I will lead you to
it in my timing. If the vision is not from me you don't want it. If its taking
longer than you expected, with detours you didn't foresee, just keep being led.
If I want to spend 30 years developing you, so that you can have an impact on
the last three years of human history, so be it. Just follow, stop trying to
learn push shove. Just be still. Be open. Be listening. Be led. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
I love you, with ALL
my heart. I will never leave you, or foresake you. Trust me, not your idea of
what you think I might have said about a future event or calling or purpose. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Its about connecting
to life, not getting better knowledge. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
.</div>
</div>
</div>
</div>
