---
title: 'Vision for the future - 2016'
date: '2016-01-13T02:36:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3486667764037864004'
blogger_filename: '/2016/01/vision-for-future-2016.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Vision'
  - 'Life Plan'
---

I see a future:<br />
<br />
<strong>Myself</strong><br />
<br />
I see a future where I am passionately in love with God, and it shows every day. I see a future in which I am open, honest, and volnerable with the God, my wife, my friends, family, and support network. <br />
<br />
I see a future in which I am getting up early in the mornings to surrender my day to Jesus, through prayer time with the Holy Spirit, praise, bible reading, listening, and then spending time writing. <br />
<br />
<br />
<strong>My Family</strong><br />
<br />
I see a future in which I am passionate about Flavia and she knows it and believes it. I see a future where I am my boys hero, and they are mine. I see a future where time off with them is a joy, and not a burden. I see a future were our finances are in order, fully funded by God, and we take extended trips around the world.<br />
<br />
We leave the house for a full month 2-3 months every year (not nessesarily consecutively) and go on trips. <br />
<br />
<strong>My Calling</strong><br />
<br />
I see a future where I am writing for a few hours each day, putting out 10 new&nbsp;novels per year, in addition to irregular non fiction books. I leave the house around 8 each morning, write from 9-5, and return home by 6; however, I am available to change and drop everything at a moments notice for the wife and kids. <br />
<br />
This writing schedule would be enhanced and suplimented with speaking engagements, seminars, and meetings to run the Freedom Center Leadership Team. <br />
<br />
<br />
**************<br />
<br />
<strong>The Freedom Center</strong><br />
<br />
I am also leading/starting a For Profit Ministry that builds on the work of Gateway Equip, Freedom Ministries, Rock Basic Training, and the Dream Center. An entire complex (multiple buildings laid out like a shopping center or college campus) full of activity 7 days a week. <br />
<br />
<strong>Freedom Center Leadership Team:</strong><br />
<br />
There are a team of leadership individuals who "do the work" of the ministry. They are on the ground, working with people in their respective fields. <br />
<br />
<strong>Church without Church Services</strong><br />
<br />
The Freedom Center is not a church, in the traditional american sense. There are no church services, but there are referrals to any and every local church that wants to participate with us in serving the community. We will never start a "church service" and therefore never compete with any church for the members. We will only add to the local churches, and never take away. Will encourage that tithe be sent to the local church, and that any wish to participate would be done by using the for profit facilities. <br />
<br />
<strong>For Profit, not For Greed</strong><br />
<br />
The name your own price program (for certain services, or all?) would allow someone who has the desire to contribute or donate the opportunity to pay more, so that other could pay less or receive for free.<br />
<br />
<strong>Freedom Ministries:</strong><br />
<br />
There are&nbsp;in patient and out patient programs for homeless families and&nbsp;recovery programs for addicts/alcoholics. There are freedom classess for every believer.<br />
<br />
<strong>Life Skill Ministries:</strong><br />
<br />
There are life-skill classes in everything from finances, cooking, mechanics, and more. Basics of each prepare people for life, and in depth training for anyone wanting to pursue the career in that path. Possibly through partnerships with local colleges. <br />
<br />
<strong>Equip Ministries:</strong><br />
<br />
There are Equip style courses on the Holy Spirit, Bible, Family, Marriage, etc, etc etc.... <br />
<br />
&nbsp;<br />
<strong>For Profit - The Funding</strong><br />
<br />
There are multiple output sources from all of this actvity. <br />
<br />
The freedom center would host podcasts, speaking enagements at local churches, host events like worship night concerts (especially from local worship bands), and put our products (like e-courses and e-books, shirts, back packs, artisan work, etc). <br />
<br />
But still will not start a weekend church service.<br />
<ul>
<li><strong>Bookstore/Library</strong> (facilitates book buying physical and electronic) partner with Amazon for that.</li>
<li><strong>Coffee Shop and Restaurant(s)</strong> on site. Run by chefs in the cooking school, and servers who want to earn money from the Life Training Center. </li>
<li><strong>Auto Repair Shop</strong> (fully insured and certified) where mechanical work is completed at a discount price in exchange for allowing the students to learn the work. Each job is overseen by an onsite certified mechaic (or more than one). </li>
<li><strong>Affiliate Marketing Links</strong> (resources we belive in can be affiliate market linked on our site, and hand outs). </li>
</ul>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
