---
title: 'Connor, Preston, Aiden "AJ" Flynn, Positive Influence'
date: '2016-04-03T04:39:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4678251212668161168'
blogger_filename: '/2016/04/connor-preston-aiden-aj-flynn-positive.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Preston'
  - 'Connor'
---

<br />
Connor and Preston,<br />
<br />
Maybe I need to start writing to you in my personal journal. I had thought I could do it in a different one for each of you, but I never did. At least here, I pull it up and write sometimes.<br />
<br />
This afternoon, from my office (adjacent the front door), I heard you talking with your very first neighborhood friend, Aiden/AJ.<br />
<br />
He said (approximately):<br />
<br />
"I feel like I'm a different person when I'm around you (both of you). Like the same body, with a different person in it. I mean, like, I have to watch what I say around you, but sometimes I forget and say things anyway."<br />
<br />
Connor responded:<br />
<br />
"Just keep working on it, it's important to watch what you say."<br />
<br />
And then it was something like "Hey, let's go play..." and off you three went again.<br />
<br />
I was impressed and encouraged by that interaction. You both are meant to be a positive influence on your generation. You have never judged him, to my knowledge. You didn't think he was a "bad person" because he said something like "Oh my God".<br />
<br />
You embraced his friendship, while simultaneously encouraging new and better behaviors. He's better for having been around you.<br />
<br />
I can't know his heart, but, I THINK he was saying that he was grateful for the influence too.<br />
<br />
I want you both to keep up that work, keep being a positive influence for change in people's lives by embracing who they are (in God's eyes) in love, without accepting the bad behaviors (which is what they do, not who they are).<br />
<br />
<br />
Daddy Darrell