---
title: 'My Mom, My Family, My Wife...'
date: '2016-01-28T07:02:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5392663521027574257'
blogger_filename: '/2016/01/my-mom-my-family-my-wife.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Revelation'
  - 'kairos'
  - 'Life Events'
---

<br />
I just had a realization of sorts.<br />
<br />
My father was an Alcoholic Pastor, turned atheist, who finally turned Crack Addict. I kicked him out of our house when he refused to go to rehab about the crack, and that was the day he ceased being my dad. I've used the term out of respect for his position, but he is not my dad, he is my biological patriarch. Despite all of this, I feel bound to him. We are the closest in age (as I was the oldest son), but we were also the closest in physical looks, temperament, and type. Both my brothers were more Tweedy than Wolfe.<br />
<br />
Yet it is not my Dad that I struggle with. We speak fairly often. I have come to understand and work with his idiosyncrasies, and even develop a bit of bitty for what a pathetic existence he's carved out for himself. I was disappointed in him as a human being many years before I kicked him out of the house. Of whom little is given, little is expected. I've never expected much from him, and he's never proven me wrong. He may be a sad person, but he is predictable. He is growing now, in his older years. He's proven to be more giving (tips to waiters). He's still hopelessly self-centered, but even that is true to his nature as an atheist.<br />
<br />
My mom, on the other hand, was kind. She was nurturing. She looked out for us boys, our needs, wants. We never went without. She stood by him when others would have left. I'm not sure she would have kicked him out, so I did.<br />
<br />
Despite the above assessment, I am now 35.5 and it is my mom, not my dad, that I have the horrible relationship with. I can barely speak with her for more than a few moments and I become rigid and angry. I would have cut 110% of all communication with any living biological relative if it had not been for Flavia insisting that I communicate with them all, if for no other reason than to ensure the boys knew their grandparents and relatives.<br />
<br />
But there is a question that has eluded my logic for all of these years. How, under the above assessment, could it be my mom that I struggle with? I used to think it was because she didn't have the back bone to leave him earlier, years earlier. And/or that it was me and not her that ended having to kick him out. Maybe that was it, but I'm thinking not.<br />
<br />
It occurred to me tonight that she is self-deceived. She knows only what she wants to know about people, events, etc.<br />
<br />
<br />
<ul>
<li>She recalls the bad things that dad did, but then says he was such a great father before it all went bad.&nbsp;</li>
<ul>
<li>No, he wasn't. He didn't "go bad" he was a vacant human being from day one. He went from absent minded, to absent. There really wasn't much of a change there for me.</li>
</ul>
<li>In the same tone and resolution, she says what a great father Devin was, how he loved Kaylee.&nbsp;</li>
<ul>
<li>Yes... the drug addict, gang-hit-man-killer, with swastikas tattooed on his body. Sure, I suppose even the mob loves their kids. But that doesn't make them great fathers. He was an awful human being, and father. He and his wife were purposefully abusing methadone and alcohol which led to their deaths, with their three year old daughter in the house. These were sick, broken people. Nothing good was in them.</li>
</ul>
<li>In the same tone and resolution, she says that I am a great father.&nbsp;</li>
<ul>
<li>Sure... the guy who spent most of the last years wishing he'd never had a wife or kids, avoiding them at any cost because it was easier than arguing, who got seriously close to asking them to leave many times.</li>
<li>I'm more involved on my worst days than my dad was on his best, but I'm still an awful father and husband (with rare moments of exception).&nbsp;</li>
</ul>
</ul>
<br />
I think I find her so infuriating because she refuses to see the truth. It's not that she can't see it, or that she's ignorant, it's that she refuses to see it. Her second ex-husband was the same. A generally bad influence, but she refused to see it. She'd rather "have fun" than grow up. In some respects I feel as though I raised her, and now I'm acting like a kid because of it.<br />
<br />
She's "incredible". She is the worst judge of character I've ever known, because she doesn't judge character. She embraces people ignoring their faults, and then wonders why they take advantage of her. She has my love, and thanks for her years of serving me growing up, and continued support, but not my respect. And for males love means little, respect is everything. If I don't respect you, I don't want to know you.<br />
<br />
THAT is why I don't like her. That is why I get mad when I hear her voice, or she drones on about the same thing. I feel as though we have the same conversation every time she picks up the phone, for 20 years. Why should I call her... I can have the conversation in my head right now.<br />
<br />
...<br />
<br />
And I've started treating Flavia like she was my mother, and not my wife. Lately, she's upgraded to room-mate... that's a step in the right direction. But Matthew (http://mustbethistalltoride.com) is right, I'm a shitty husband.<br />
<br />
I don't FEEL like trying anymore. I FEEL like I want every human I've ever known to leave me alone, and let me work in silent-solitude. Of course what I really want is for Jesus to take me home, off this stupid rock of a planet.<br />
<br />
I would not kill myself mind you, with my luck I wouldn't succeed anyway. But I do wish he'd let me leave and take me home. I've wished it since 10 years old or so.<br />
<br />
But I know that most or all of this is a lie. It's a demonic stronghold. These things have kept me from engaging in my family, marriage, job, calling, relationship with Jesus.<br />
<br />
I have decided to call all of this a demonic lie, and pursue marriage. I don't FEEL that I want to be married or a father... but I have decided to be. I don't know where to start...<br />
<br />
I will keep reading Matthew the divorced guy (it's a what not to do blog), and I'll go to marriage challenge, and we'll see from there.<br />
<br />
*********************************************************<br />
<br />
<br />
Jesus,<br />
<br />
I'm still mad at you for appearing all those years ago, and never since. If you won't take me home to stay, I'm asking you to take me home for visit (Pauline or Jesse Duplantis style, not through some accident-hospital dead for 30-minutes thing).<br />
<br />
I want to see you again, and I want you to fix me... or just take me home for good. Pick one. I'm tired.<br />
<br />
Darrell<br />
<br />
<br />
<br />