---
title: 'Hi... I''m your husband... Darrell'
date: '2016-02-24T03:55:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7287655513609104270'
blogger_filename: '/2016/02/hi-im-your-husband-darrell.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Flavia Antoinette Miller Wolfe,<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Sorry ahead of time, this is long. But I’m 99% sure nothing in here should hurt you, it’s a very long apology. When I hit send on this, I’m leaving work. I have my phone   if you need anything.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I was talking about you today with my co-worker, Jeremy. He’s been my Protégé of sorts at work. I was reminded about how I was living in the van, and you were living with   that lady, Janette?. You made a decision very few women would have ever made. You decided to leave a bed, shower, room and board, and bring a baby to come to live with me in the minivan. You wanted to be “together”, thick and thin, through it all.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">That inspired me tonight, to re-consider the lies the enemy has sown in my head about me, you, us, the future. I clocked out at 8:05 pm, and it’s 9:05 pm now, I’ve been reading,   praying. I even cried once, and that’s a rare event, very rare.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I just got done re-reading through your Husband To Be (HTB) letters from 1997-2000. I scanned them in to preserve them, they are fading after all these years.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">You were right about Kristina. The one in the lower spiritual condition brings down the higher.  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">You have always been the higher, from day one. And I’ve drug you down with me.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I keep a picture on my desk of you and me in your dorm room, spring 2003. You were smiling, and beautiful. I remember thinking that you were a mysterious and quirky girl,   totally different from anyone I’d ever met. I felt completely out of place in your life, like an outsider or foreigner. Your ability to dance and sing, and let loose still astounds me.  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I copy what you do with the kids, because I’m trying to be like you. I do nothing right, and you are my hero. I figure if I copy you, I can be like you.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">As I stare at that picture, the same thought keeps going through my head, I broke her, and I don’t know how to put her back together again.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">A few things stood out consistently as I read your letters. You wanted someone to hold your hand, hold you, someone you could run to when you cry (not from like I’ve forced   you to). You wanted a best friend. You wanted to be romantic. You wanted to be “in love”.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Unfortunately you got me, a lighter version of my cold hard dad.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I have completely failed you for 12+ years. I am a shitty husband.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I can only imagine the reason you are still here is because of your bull-dog faith, determination to honor God, and the glimmer of hope that the man you wrote to exists somewhere   inside of me, waiting to come out. <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I honestly don’t know if I’ve ever been that guy, even before we got married. I know God put us together, but I don’t think I’ve ever been that guy. I think there were glimpses   of that guy in my teenage self, before life killed him.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">It makes me sad for you, God should have given you that guy. Why would God put someone with your heart and passion with me? Doesn’t he know what He’s doing?  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I’m sorry.  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I’m really really sorry.  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I don’t know how to be him. I’d like to be though. I’m not sure how, but maybe he’s in there somewhere.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I tried to find the email you brought up, but couldn’t. I don’t even really remember what I said, but I know you took it very personally, and I’m sorry for hurting you. After   reading your letters, I think I can catch a glimpse as to why you took it so personally.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I can recall the feeling I was having while I wrote the email.  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Selfishly, I was also feeling a bit claustrophobic. I have struggled with the same thought all my life, “Everyone wants something from me, and I’m not enough, I don’t have   what they want”.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I figured if you had friends, it might relieve some of that pressure, and we’d be better friends as a result.  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I was feeling like I just wanted you to be happy and have friends. You had friends in college, and you really didn’t have any after we got married. I wanted you to have connections,   and wanted to push you into it.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">But that didn’t work like I wished it would, because it’s me who’s broken, not you. I was hoping you could find fulfillment in the world, and be happy at home. But I think,   and maybe this is too grandiose or self-centered to be true, but it’s my job to help you find fulfillment at home, and only then can you go into the world and be what you are supposed to be? I don’t know if that makes sense, or I’m totally off base.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Unfortunately, the version of me that you met in 2003, was the best possible version of me. That version rarely existed before or after that year. I miss that version of   me, I’d like to see him come back, or better.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">This got a little self-centered toward the end, but all things are with me. Another growth point I guess.  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">All that to say, I’m sorry. I know that doesn’t fix it, or us, but I’m sorry. I know we’ve got a road ahead of us if we’re going to pursue us.  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">That person you described sounds like a really great guy… I’d like to know if I could become that guy, and how to start.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">So… I think that’s all I can say right now. I hope I didn’t say anything wrong. I re-read this several times and deleted parts where I rambled on about me too much. I am   100% sure I didn’t say anything in here intended to harm you, if I did, it was an accident and I’m sorry again.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Darrell<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
</div>
