---
title: 'F1rst Conference - Sunday 01/03/16'
date: '2016-01-04T08:22:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4128784501738013628'
blogger_filename: '/2016/01/f1rst-conference-sunday-010316.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Word From God'
  - 'Revelation'
  - 'Church Notes'
---

<br />
<br />
Jack Hayford spoke tonight on the Holy Spirit.<br />
<br />
My one take away was Power/Prayer.<br />
<br />
Jesus said to go and wait until the Holy Spirit comes, and you shall receive power to be witnesses. Many associate that power with Fire, Wind, Demonstrations of the Spirit in public places....<br />
<br />
But Paul said that he prayed in tongues more than everyone else. How often have I heard the words of verse 28 quoted? God works all things to the good of those who love him.<br />
<br />
<blockquote class="tr_bq">
<i><a href="http://www.biblestudytools.com/romans/passage/?q=romans+8:26-28" target="_blank">Romans 8:26-28</a>26 In the same way, the Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us with groans that words cannot express. 27 And he who searches our hearts knows the mind of the Spirit, because the Spirit intercedes for the saints in accordance with God's will. 28 <b><u>And </u></b>we know that in all things God works for the good of those who love him, who have been called according to his purpose.</i></blockquote>
<br />
Verse 28 starts with the word AND. You cannot read it without reading its context. We do not know how we ought to pray, but the Spirit Himself prays for us... THAT is how things work together for our good.<br />
<br />
The POWER Jesus spoke of, was the power of Prayerful Direction, Guidance, Intersession, and Leading.<br />
<br />
Wait for it...<br />
<br />
#BeStillBeLed<br />
<br />
AH! It always comes back to that, doesn't it?<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />