---
title: 'One Job Tailor Fit More Than Enough'
date: '2016-06-19T01:30:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8754120832768728628'
blogger_filename: '/2016/06/one-job-tailor-fit-more-than-enough.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Praise Report'
---

<br />
<h4>
::: The Word :::</h4>
<ul style="font-family: &quot;times new roman&quot;;">
<li>Promotion</li>
<ul>
<li>God said at end of 2012 to believe for:</li>
<ul>
<li><b>One Job, Tailor Fit, More then enough!</b></li>
</ul>
<li>Kenneth Copeland gave a Word for 2013</li>
<ul>
<li>"Stay where you are. Stay Steady. Why?! Your greatest BLESSING ever is at hand..."</li>
</ul>
<li>Pastor George Changed service just to deliver the Word of the Lord I needed. Maybe other people needed it too, but I'm SURE it was for me.</li>
<ul>
<li>Pastor George Pearsons 02/17/2013: ~~ "Someone is having a work situation and there is a lot of negativity. Stop talking about it. Stop it! You pray in tongues over that thing. Promotion is coming... stay above the fray... God will use you like Joseph and Daniel. You can control the whole thing from your prayer closet..."</li>
</ul>
</ul>
</ul>
<div style="font-family: Georgia, serif; font-size: 16px;">
<span style="font-family: &quot;;"><br /></span></div>
<h4 style="font-family: Georgia, serif; font-size: 16px;">
<span style="font-family: &quot;;">::: Fulfilled :::</span></h4>
<div>
<ul>
<li>May 2015, hired at WFDS Office of the President doing Research/Remediation. Small pay cut from sales. Worked lots of overtime.</li>
<li>February 2015, promoted to Analyst and Team Lead, more pay, more overtime. Made $50,000 in 2015.&nbsp;</li>
<li>June 2016... interviewing for possible role as Implementation Associate for Business Documentation (P&amp;P Writer). This has the potential of making 50-55K without OT.</li>
</ul>
<div>
<div>
<b>I make complicated things simple; through writing, storytelling, &amp; studies.&nbsp;</b></div>
</div>
</div>
<div>
<br /></div>
<div>
These jobs have allowed me to research and write as a profession (with no sales goals). As tough as 2016 has been (with added pressure of bad leadership), I can take joy and be grateful for the job I've had since 2014.</div>
<div style="font-family: Georgia, serif; font-size: 16px;">
<span style="font-family: &quot;;"><br /></span></div>
