---
title: 'FW: Stuck'
date: '2016-02-20T06:27:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1499141676873023574'
blogger_filename: '/2016/02/fw-stuck.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;times new roman&quot; , &quot;serif&quot;; font-size: 12.0pt;">Hey You,<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;times new roman&quot; , &quot;serif&quot;; font-size: 12.0pt;">Today my wife blew up and argued with a man behind on the counter at CiCi’s pizza, for not accepting her printed coupon. I got mad at her for it. She got mad at me getting   mad at her for it. We got home. She said she doesn’t know if she wants to be married anymore because she’s always walking around on eggshells with me. Always needing to make sure I have space to protect me from yelling at her or the kids.  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;times new roman&quot; , &quot;serif&quot;; font-size: 12.0pt;">I said nothing. Well, that’s not true.&nbsp; I said “I have nothing to say.” I stared for a while. She asked if I had a reply. I said no, and walked to my office.  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;times new roman&quot; , &quot;serif&quot;; font-size: 12.0pt;">The truth is… I don’t want to be married anymore either. I didn’t want to be married a few weeks before we got married. We argued in the car on the way home from the wedding.   And I’ve wanted out ever since. Then she got pregnant, and I was stuck. Divorce is worse, they say. I’ve tried to “man up” and stick with it.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;times new roman&quot; , &quot;serif&quot;; font-size: 12.0pt;">Then came homelessness, new jobs, bills, debt, new jobs, moved to Texas, new job, a house, new job. Income continues to increase, and we’re a little better off financially   each year that passes. But still stuck in broke mode, and it’s never enough. I feel that the three of them are financial leaches, draining anything I can produce.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;times new roman&quot; , &quot;serif&quot;; font-size: 12.0pt;">It’s been 11 years and I have no more emotional desire to be in this today than I did at the beginning. I’m here out of duty, because it’s the right thing to do, not because   I want to be. <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;times new roman&quot; , &quot;serif&quot;; font-size: 12.0pt;">What I really  <i>want<span style="color: black;">ed</span></i> is to leave her, the kids, the church, and go back to drinking, pill popping, and then die.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black; font-family: &quot;times new roman&quot; , &quot;serif&quot;; font-size: 12.0pt;">But that’s not really what I wanted, was it?<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black; font-family: &quot;times new roman&quot; , &quot;serif&quot;; font-size: 12.0pt;">Why are emotions so volatile, shifting, and confusing? Why can I passionately want something one day, and passionate dis-want it the next? I hate emotions.</span><u><span style="color: blue; font-family: &quot;georgia&quot; , &quot;serif&quot;; font-size: 12.0pt;">  <o:p></o:p></span></u></div>
<div class="MsoNormal">
<br /></div>
</div>
