---
title: '*Never mind!'
date: '2016-11-29T14:50:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4202742498362971613'
blogger_filename: '/2016/11/never-mind.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Venting'
  - 'Thought'
---

I don't know what's wrong with us... since the beginning. <br />
<br />
Sunday, I told her that I'd started smoking.<br />
Monday night, she comes into my office and wants to "talk about this". <br />
<br />
The questions were like:<br />
<ul>
<li>Do you still have the pack your friend gave you?</li>
<li>This is a really expensive habit, are you going to use the $20 from the paycheck? This isn't in our budget.</li>
<li>Where do you do it when you're home? What about the weekends? </li>
<li>The kids are going to smell it on you. The car will smell of it if you do it and get into the car right away. I told like it. I'm not judging you for it, but I don't like to be around it...</li>
<li>I know it does whatever it does for you, but should we look at getting the meds you talked about instead?</li>
<li>There were probably other questions...</li>
</ul>
<br />
Not: Help me understand what you are going through...<br />
<br />
These were not questions of "help me understand" they were questions about "how can we minimize the impact of this on me". <br />
<br />
Guess what? I told you, on purpose, as a test. I wanted to see how you'd react to something I feel is trivial before I start getting into things closer to the heart I tell myself I don't have. Guess what? You failed. <br />
<br />
An hour and half before this conversation, I was telling God that maybe, just maybe, I'd be&nbsp;willing to make this marriage/family work if he'd just change my heart to help me want that. That maybe, just maybe, I did want that but didn't see a way for it to work... <br />
<br />
One conversation with ten or so questions and by the end I was ready to pack my bags and leave last night. The thoughts I had about making it work turned to "Never mind" in one conversation... <br />
<br />
So.... that happened.