---
title: 'Reminder: Lies'
date: '2016-02-12T06:34:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '909553024663484180'
blogger_filename: '/2016/02/reminder-lies.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Word From God'
  - 'Revelation'
  - 'Growing Up'
---

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="MsoNormal">
<a href="https://draft.blogger.com/null" name="_MailEndCompose">Hey
Sandy,</a><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I’ve re-read your email (below) a
few times. As you may or may not have picked up on since you met Flavia and I,
I too suffer from deep depression. My wife, I think, doesn’t entirely
understand it. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I’ve been sober since 2002, but
I’m what AA people call a “Dry Drunk”. I still have all the personality defects
that led me to drinking, and constant desire to self-medicate (but not acted
on, unless you count chocolate, Dr. Pepper, and excessive movie watching… I
think that could be a kind of medication). <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
More days than not, I find the
world, and interaction with human beings, unbearable after a while. I enjoy it
for a while, but it starts to overload my circuit board. I require massive
amounts of alone time to re-charge after church and work. Flavia was talking to
me about some new therapies she’d heard of that I’m considering looking into.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
What you typed was a great
reminder that these personal battles are rooted in lies. Lies I may not even
fully realize I’m believing much of the time. I need to spend more and more
time in the light, so He can reveal the lie, and replace it. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Thanks for the reminder, Darrell. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal" style="text-indent: .5in;">
<br /></div>
<div class="MsoNormal">
<span style="font-family: 'Tempus Sans ITC'; font-size: 18pt;">Shalom!<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: 'Tempus Sans ITC'; font-size: 18pt;">Darrell G. Wolfe</span><o:p></o:p></div>
<div class="MsoNormal">
<span style="font-family: 'Tempus Sans ITC';">Story
Teller | INFJ | Intelection, Learner, Ideation, Achiever, Input</span><o:p></o:p></div>
<div class="MsoNormal" style="text-indent: .5in;">
<br /></div>
<div class="MsoNormal" style="text-indent: .5in;">
<a href="http://darrellwolfe.blogspot.com/" target="_blank"><span style="color: blue; font-family: &quot;Georgia&quot;,serif;">www.DarrellWolfe.Com</span></a><span style="color: #0072bc; font-family: &quot;Georgia&quot;,serif;"><o:p></o:p></span></div>
<div class="MsoNormal" style="text-indent: .5in;">
<a href="https://twitter.com/DarrellWolfe" target="_blank"><span style="color: blue; font-family: &quot;Georgia&quot;,serif;">Twitter: @DarrellWolfe</span></a><u><span style="color: blue;"><o:p></o:p></span></u></div>
<div class="MsoNormal" style="text-indent: .5in;">
<a href="mailto:Darrell@DarrellWolfe.Com" target="_blank"><span style="color: blue; font-family: &quot;Georgia&quot;,serif;">Darrell@DarrellWolfe.Com</span></a><u><span style="color: blue; font-family: &quot;Georgia&quot;,serif;"><o:p></o:p></span></u></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b><span style="font-family: &quot;Calibri&quot;,sans-serif; font-size: 11.0pt;">From:</span></b><span style="font-family: &quot;Calibri&quot;,sans-serif; font-size: 11.0pt;"> Sandy Joanis [<a href="mailto:sandy.joanis@gatewaypeople.com">mailto:sandy.joanis@gatewaypeople.com</a>]
<br />
<b>Sent:</b> Saturday, February 6, 2016 12:53 AM<br />
<b>To:</b> Sandy Joanis &lt;<a href="mailto:skjoanis@me.com">skjoanis@me.com</a>&gt;<br />
<b>Subject:</b> Weekly Check-in Host News / Team 1 NFW<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
Hi Team,<o:p></o:p><br />
As many of you know, I am an enthusiast of all things Strengths Finder
related. (If you don't know what that is, we may need to visit soon so I can
tell you more about it!) One of my top talent themes is Harmony. People with
this theme are often uncomfortable with conflict and look for areas of
agreement. I have been walking through some challenging seasons lately and have
struggled with depression for about 12 years now. I'm finally trying to dig in,
find and remove the root of this depression so that I can walk in freedom and
victory. I was challenged by a friend to give myself permission to be angry
about the difficult things that have happened in my life and to confront God
with these things. Well, for someone who doesn't like conflict or
confrontations, I couldn't picture myself doing this (especially with God!);
but as I thought more about my friend's challenge, the word consensus and
agreement kept coming to the front of my thoughts. And then with a gentle word,
the Holy Spirit showed me that in my search for consensus and agreement, I have
been choosing to agree with the lies of the enemy instead of the truth of my
Father! Oh my ... one word from the Lord can make things so clear! Now, I have
much work to do to define the lies and bring them into the light of God's Word
and to replace them with the truth and hope given by God ... but the hope I
feel in my heart just hearing His voice again, so gently spoken with no
condemnation, I will move forward and overcome. I will walk in freedom and
victory ... Jesus has gone before me and will guide me every step of the way.
Are you believing lies? Do you need to bring them into the light for God to
bring healing and hope to you again? Let's trust Him together this year!&nbsp;
Hugs!<o:p></o:p><br />
---<br />
<br />
<div class="MsoNormal">
-- <o:p></o:p></div>
<br />
<pre><span style="font-family: &quot;Arial&quot;,sans-serif; font-size: 12.0pt;">Sandy Joanis&nbsp;

Amazing Kids Check-in

Gateway Church NFW&nbsp;

817-480-1770&nbsp;

Woo | Developer | Harmony | Includer | Positivity</span><o:p></o:p></pre>
