---
title: 'RE: Hi... I''m your husband... Darrell'
date: '2016-02-24T05:40:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4253154326439455942'
blogger_filename: '/2016/04/re-hi-im-your-husband-darrell.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Flavia'
  - 'Growing Up'
---

<div class="WordSection1">
<div class="MsoNormal">
<span style="color: black; font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Understood, thank you for the insight.<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black; font-family: &quot;georgia&quot; , &quot;serif&quot;; font-size: 10.0pt;">Thank you,<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: black; font-family: &quot;georgia&quot; , &quot;serif&quot;; font-size: 10.0pt;">Darrell G. Wolfe<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Research &amp; Remediation Analyst | DS Office of the President | Customer Excellence Group<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Wells Fargo Dealer Services&nbsp; |&nbsp; 6061&nbsp;N. State Highway 161&nbsp; | 2nd Floor | Irving,&nbsp;TX 75038-2242 | MAC T9017-024 | Tel 877-250-2265 | Direct 972-870-8308 | Fax 888-329-4855   | </span><span style="color: black; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;"><a href="mailto:Darrell.G.Wolfe@wellsfargo.com"><span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;;">Darrell.G.Wolfe@wellsfargo.com</span></a></span><span style="color: black; font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="color: #262626; font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Should you have an escalated issue that needs immediate attention, please forward to:  </span><span style="color: black; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;"><a href="mailto:officeofthepresidentdealer@wellsfargo.com"><span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;;">officeofthepresidentdealer@wellsfargo.com</span></a></span><span style="color: #262626; font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">   or call (877) 250-2265</span><span style="color: black; font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;"><o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">This transmission may contain information that is confidential and/or proprietary. If you are not the individual or entity to which it is addressed, note that   any review, disclosure, copying, retransmission or other use is strictly prohibited. If you received this transmission in error, please notify the sender immediately and delete the material from your system. This transmission is for informational purposes   only, and is not intended as an offer or solicitation for the purchase or sale of any financial instrument or as an official confirmation of any transaction.  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b><span style="font-family: &quot;tahoma&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">From:</span></b><span style="font-family: &quot;tahoma&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;"> Flavia Wolfe [mailto:flaviawolfe@gmail.com]  <br />  <b>Sent:</b> Wednesday, February 24, 2016 6:13 PM<br />  <b>To:</b> Wolfe, Darrell G.<br />  <b>Subject:</b> Re: Hi... I'm your husband... Darrell<o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div>
<div class="MsoNormal">
We are about to head to the store and then to you... but i think after all the little bits of this and that in conversation I have something to say... something small perhaps....<o:p></o:p></div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
last night when I first was wanting to say something and then ended up super emotional and lost for words I was mostly frustrated with myself than anything else at the time... but before that when you walked across the room and knelled   on the chair it was what I would have wanted you to do years ago... but you surprised me and I wasn't sure what to say. I do appreciate you email and am glad you felt you could share what is going on with you...&nbsp; I want to be hopeful but I am tired, so my   goal is to keep moving forward... I will call when we leave the store...<o:p></o:p></div>
</div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
<div>
<div class="MsoNormal">
On Tue, Feb 23, 2016 at 10:46 AM, &lt;<a href="mailto:Darrell.G.Wolfe@wellsfargo.com" target="_blank">Darrell.G.Wolfe@wellsfargo.com</a>&gt; wrote:<o:p></o:p></div>
<div>
<div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="color: black; font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">OK</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="color: black; font-family: &quot;georgia&quot; , &quot;serif&quot;; font-size: 10.0pt;">Thank you,</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="color: black; font-family: &quot;georgia&quot; , &quot;serif&quot;; font-size: 10.0pt;">Darrell G. Wolfe</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Research &amp; Remediation Analyst | DS Office of the President | Customer Excellence Group</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Wells Fargo Dealer Services&nbsp; |&nbsp; 6061&nbsp;N. State Highway 161&nbsp; | 2nd Floor | Irving,&nbsp;TX 75038-2242 | MAC   T9017-024 | Tel <a href="tel:877-250-2265" target="_blank">877-250-2265</a> | Direct  <a href="tel:972-870-8308" target="_blank">972-870-8308</a> | Fax <a href="tel:888-329-4855" target="_blank">  888-329-4855</a> | </span><span style="color: black; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;"><a href="mailto:Darrell.G.Wolfe@wellsfargo.com" target="_blank"><span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;;">Darrell.G.Wolfe@wellsfargo.com</span></a></span><span style="color: black; font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">  </span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="color: #262626; font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Should you have an escalated issue that needs immediate attention, please forward to:  </span><span style="color: black; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;"><a href="mailto:officeofthepresidentdealer@wellsfargo.com" target="_blank"><span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;;">officeofthepresidentdealer@wellsfargo.com</span></a></span><span style="color: #262626; font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">   or call <a href="tel:%28877%29%20250-2265" target="_blank">(877) 250-2265</a></span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">This transmission may contain information that is confidential and/or proprietary. If you are not the   individual or entity to which it is addressed, note that any review, disclosure, copying, retransmission or other use is strictly prohibited. If you received this transmission in error, please notify the sender immediately and delete the material from your   system. This transmission is for informational purposes only, and is not intended as an offer or solicitation for the purchase or sale of any financial instrument or as an official confirmation of any transaction.  </span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<b><span style="font-family: &quot;tahoma&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">From:</span></b><span style="font-family: &quot;tahoma&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;"> Flavia Wolfe [mailto:<a href="mailto:flaviawolfe@gmail.com" target="_blank">flaviawolfe@gmail.com</a>]  <br />  <b>Sent:</b> Tuesday, February 23, 2016 10:41 AM<br />  <b>To:</b> Wolfe, Darrell G.<br />  <b>Subject:</b> Re: Hi... I'm your husband... Darrell</span><o:p></o:p></div>
<div>
<div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
Hi, I just wanted to say that I read the email... I don't have much else to say at this time but i wanted to let you know that I got it<o:p></o:p></div>
</div>
<div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
On Mon, Feb 22, 2016 at 9:55 PM, &lt;<a href="mailto:Darrell.G.Wolfe@wellsfargo.com" target="_blank">Darrell.G.Wolfe@wellsfargo.com</a>&gt; wrote:<o:p></o:p></div>
<div>
<div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Flavia Antoinette Miller Wolfe,</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Sorry ahead of time, this is long. But I'm 99% sure nothing in here should hurt you, it's a very long apology.   When I hit send on this, I'm leaving work. I have my phone if you need anything.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I was talking about you today with my co-worker, Jeremy. He's been my Protégé of sorts at work. I was reminded   about how I was living in the van, and you were living with that lady, Janette?. You made a decision very few women would have ever made. You decided to leave a bed, shower, room and board, and bring a baby to come to live with me in the minivan. You wanted   to be "together", thick and thin, through it all.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">That inspired me tonight, to re-consider the lies the enemy has sown in my head about me, you, us, the future.   I clocked out at 8:05 pm, and it's 9:05 pm now, I've been reading, praying. I even cried once, and that's a rare event, very rare.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I just got done re-reading through your Husband To Be (HTB) letters from 1997-2000. I scanned them in to preserve   them, they are fading after all these years.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">You were right about Kristina. The one in the lower spiritual condition brings down the higher.  </span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">You have always been the higher, from day one. And I've drug you down with me.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I keep a picture on my desk of you and me in your dorm room, spring 2003. You were smiling, and beautiful. I remember   thinking that you were a mysterious and quirky girl, totally different from anyone I'd ever met. I felt completely out of place in your life, like an outsider or foreigner. Your ability to dance and sing, and let loose still astounds me.  </span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I copy what you do with the kids, because I'm trying to be like you. I do nothing right, and you are my hero. I   figure if I copy you, I can be like you.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">As I stare at that picture, the same thought keeps going through my head, I broke her, and I don't know how to   put her back together again.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">A few things stood out consistently as I read your letters. You wanted someone to hold your hand, hold you, someone   you could run to when you cry (not from like I've forced you to). You wanted a best friend. You wanted to be romantic. You wanted to be "in love".</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Unfortunately you got me, a lighter version of my cold hard dad.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I have completely failed you for 12+ years. I am a shitty husband.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I can only imagine the reason you are still here is because of your bull-dog faith, determination to honor God,   and the glimmer of hope that the man you wrote to exists somewhere inside of me, waiting to come out.  </span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I honestly don't know if I've ever been that guy, even before we got married. I know God put us together, but I   don't think I've ever been that guy. I think there were glimpses of that guy in my teenage self, before life killed him.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">It makes me sad for you, God should have given you that guy. Why would God put someone with your heart and passion   with me? Doesn't he know what He's doing? </span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I'm sorry.  </span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I'm really really sorry.  </span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I don't know how to be him. I'd like to be though. I'm not sure how, but maybe he's in there somewhere.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I tried to find the email you brought up, but couldn't. I don't even really remember what I said, but I know you   took it very personally, and I'm sorry for hurting you. After reading your letters, I think I can catch a glimpse as to why you took it so personally.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I can recall the feeling I was having while I wrote the email.  </span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Selfishly, I was also feeling a bit claustrophobic. I have struggled with the same thought all my life, "Everyone   wants something from me, and I'm not enough, I don't have what they want".</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I figured if you had friends, it might relieve some of that pressure, and we'd be better friends as a result.  </span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">I was feeling like I just wanted you to be happy and have friends. You had friends in college, and you really didn't   have any after we got married. I wanted you to have connections, and wanted to push you into it.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">But that didn't work like I wished it would, because it's me who's broken, not you. I was hoping you could find   fulfillment in the world, and be happy at home. But I think, and maybe this is too grandiose or self-centered to be true, but it's my job to help you find fulfillment at home, and only then can you go into the world and be what you are supposed to be? I don't   know if that makes sense, or I'm totally off base.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Unfortunately, the version of me that you met in 2003, was the best possible version of me. That version rarely   existed before or after that year. I miss that version of me, I'd like to see him come back, or better.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">This got a little self-centered toward the end, but all things are with me. Another growth point I guess.  </span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">All that to say, I'm sorry. I know that doesn't fix it, or us, but I'm sorry. I know we've got a road ahead of   us if we're going to pursue us. </span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">That person you described sounds like a really great guy… I'd like to know if I could become that guy, and how   to start.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">So… I think that's all I can say right now. I hope I didn't say anything wrong. I re-read this several times and   deleted parts where I rambled on about me too much. I am 100% sure I didn't say anything in here intended to harm you, if I did, it was an accident and I'm sorry again.</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="color: #888888; font-family: &quot;verdana&quot; , &quot;sans-serif&quot;; font-size: 10.0pt;">Darrell</span><o:p></o:p></div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
</div>
</div>
</div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br />
<br clear="all" />
<o:p></o:p></div>
<div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
</div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
--  <o:p></o:p></div>
<div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
Today is a day of Supernatural Favor!!!<o:p></o:p></div>
<div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
</div>
<div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<a href="http://www.texascowsandcrafts.com/" target="_blank">http://www.texascowsandcrafts.com/</a>  <o:p></o:p></div>
</div>
<div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
</div>
<div>
<div class="MsoNormal" style="mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<a href="https://www.facebook.com/pages/Texas-Cows-Crafts/298135563538323" target="_blank">https://www.facebook.com/pages/Texas-Cows-Crafts/298135563538323</a>  <o:p></o:p></div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="MsoNormal">
<br />
<br clear="all" />
<o:p></o:p></div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div class="MsoNormal">
-- <o:p></o:p></div>
<div>
<div class="MsoNormal">
Today is a day of Supernatural Favor!!!<o:p></o:p></div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
<a href="http://www.texascowsandcrafts.com/" target="_blank">http://www.texascowsandcrafts.com/</a>  <o:p></o:p></div>
</div>
<div>
<div class="MsoNormal">
<br /></div>
</div>
<div>
<div class="MsoNormal">
<a href="https://www.facebook.com/pages/Texas-Cows-Crafts/298135563538323" target="_blank">https://www.facebook.com/pages/Texas-Cows-Crafts/298135563538323</a>  <o:p></o:p></div>
</div>
</div>
</div>
</div>
