---
title: 'Disappointing Job Offer'
date: '2016-08-09T13:03:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1215982035363779996'
blogger_filename: '/2016/08/disappointing-job-offer.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Freedom Recovery (Kairos AA'
  - 'Answers'
  - 'Life Events'
---

<br />
<br />
For several days I have been wondering around thinking about this impending job offer. I felt like I was hearing God say "I got this", and that's it. That's all He'd say. Of course I didn't <i>feel </i>as though he Got This, but I said "OK Lord, I trust you got this".<br />
<br />
I got the call yesterday, they want to offer the job. I was hoping for $56,000, but would have settled for $53,000, they offered $51,100.<br />
<br />
On the screen that seems like it should be enough, but that's actually less than I'm making now with overtime.<br />
<br />
Overtime is not likely in this new position.<br />
<br />
So I'm taking an effective pay-cut.<br />
<br />
I've spent SO many years making "not enough", I was really hoping this position would put us over the top... but it's another in a long line of "better, almost there". I was hoping to be "almost there" years ago.<br />
<br />
I just don't know if I can do this "life" thing anymore... it's unbearably hard.<br />
<br />
I asked for a little more. I HATE negotiations. I won't even ask for car purchases (and it's generally accepted to do that). Even if they meet my "little more" it's not what I was hoping.<br />
<br />
God is so disappointing...<br />
<br />
Why won't you let me leave this damned planet? He won't give me that either.<br />
<br />
I'll probably accept this new job... it's "better" than my current job... I guess.<br />
<br />
Will somebody please shoot me, or run me over, or something? Please?<br />
<br />
Darrell<br />
<br />