---
title: 'The Gay Questions'
date: '2016-06-23T04:05:00.0060000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8423224759083567540'
blogger_filename: '/2016/06/the-gay-questions.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Thought'
---

<br />
<br />
Dear Holy Spirit,<br />
<br />
<br />
How should I (as a Christian) and WE (as a Church Body) respond to the issues around homosexuality and the LGBT?<br />
<br />
To start... what ARE the questions?<br />
<br />
Are you born gay?<br />
<br />
<ul>
<li>No. You are born created in God's image, but into a fallen world with fallen influences.</li>
<li>Sex is a desire. Any sex outside of one man and one woman for life is an unhealthy desire.&nbsp;</li>
<li>Unhealthy and Unusual desires are developed and fed, you are not born with them. But they can start young, which may make you feel that you were born with them.</li>
<li>A series of contributing factors can play a role in someone's developing a desire for sex with a same sex partner.&nbsp;</li>
<ul>
<li>broken biology,&nbsp;</li>
<li>parental upbringing,&nbsp;</li>
<li>exposure to pornography,&nbsp;</li>
<li>relational experiences with same and opposite sex friends (prior to adolescents),</li>
<li>relational experiences with same and opposite sex friends (prior to adolescents),</li>
<li>personality type,&nbsp;</li>
<li>Visual, Verbal, and Physical influences (pornography, tv, movies, videos, media)</li>
<li>Unhealthy sexual exposure (either through an early start into sex or through abuse)</li>
<li>... and many other factors&nbsp;</li>
</ul>
</ul>
<br />
<br />
Does God hate gays?<br />
<br />
<ul>
<li>God does not hate gays. Period. You cannot find that in the bible.&nbsp;</li>
<li>God does hate actions and behaviors that are not healthy; only because, those actions and behaviors cause pain in people's lives. He hates people's pain.</li>
<li>God loves every human on earth, so much so, that he died for you and me.</li>
</ul>
<br />
<br />
Can I change, and not be Gay (or experience gay feelings/desires)?<br />
<br />
<ul>
<li>Good News: You do not have to be gay. You can experience healing and radical change.&nbsp;</li>
<li>Good News that sounds like Bad News: There's no 12 step process. That change is less likely to be the result of some "program" and more likely to be the result of you walking in a radical, personal, relationship with Jesus... and letting Him work on whatever parts of you He wants to work on first.</li>
<li>Most often, healing for our soul wounds does not start at the perceived source of our pain, or our pain point. Often, we bring our pain point, our "owie" before God, and he will talk about something totally different. He may need to bring you healing in 15 different areas, seemingly unrelated, and then one day you will wake up free of the other and not know how you got there.&nbsp;</li>
</ul>
<div>
<br /></div>
<br />
What if I am convinced that I was born Gay, I don't want to change, but I still want to know God?<br />
<br />
<ul>
<li>Good News: God will take you in any condition. God never asks you to change before he takes you into his warm embrace. He never asks you to change first. He only asks you to let him in. Once he's inside, he will begin to change your desires, one at a time... you may or may not have this desire in the future... Start with "Hello... I'm willing to know you.", and see where it goes from there.&nbsp;</li>
</ul>
<br />
<br />
How should a church handle the Gay community?<br />
<br />
<ul>
<li>Your policies and programs should unquestionably embrace any human who walks through your doors, without causing them to doubt your sincere love for them, not even for a moment.&nbsp;</li>
<li>Your stance should be clear and direct on all issues.&nbsp;</li>
<li>Potential Policy Statements:</li>
<ul>
<li>To our friends in the LGBT community:</li>
<li>We love gay people and the gay community, and we welcome you with open arms.&nbsp;</li>
<li>Attend our services, join a small group, jump into our classes and counseling programs.&nbsp;If anything or anyone here makes you feel unwelcome, please email us at xxxxx and tell us about it immediately, please. We cannot address what we do not know about.</li>
<li>We do not believe that you are any different from any other human on earth, God loves each of us the same.</li>
<li>We do believe that you were not born gay, and we believe God can and will set you free if you want him to.</li>
<li>We do believe that the only healthy and proper sexual relationship is between one man and one woman in marriage. Any sexually active relationship outside of that is unhealthy for the human body and soul. Therefore, we do not support or participate in Gay Marriage. But you are still loved and welcome to join us in our collective journey to find the heart of God and his passionate purpose for our lives.</li>
<li>Anyone actively pursuing an official leadership role in this church will be vetted as striving to live a godly lifestyle. As such, a person actively living a gay lifestyle would not be eligible for a leadership role in this church. However, a person struggling with gay desires, but actively pursuing God for healing and restoration could be eligible.&nbsp;</li>
<ul>
<li>To clarify: any person living a lifestyle that disagrees with the biblical standard would not be eligible for a leadership role in this church. That would not be limited to a gay lifestyle, but also include an unmarried man living with a woman who is not his wife, or with several women.&nbsp;</li>
</ul>
</ul>
<li>If you are going to address the issue, consider addressing the issue of Sexuality as a whole, rather than singling out a specific sub-point on the Sexually Unhealthy Scale, to the exclusion of all others.</li>
</ul>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />