---
title: 'Gratitude Practice | 06/11/16'
date: '2016-06-12T05:44:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2013860419389941241'
blogger_filename: '/2016/06/gratitude-practice-061116.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Freedom Recovery (Kairos AA'
  - 'Gratitude Practice'
---

Sat Night:&nbsp;Gratitude Practice<br />
<br />
<br />
I am thankful and grateful TODAY for:<br />
<br />
<ul>
<li>Preston's practice and new coaches. He's got a great arm, and he enjoys the game.</li>
<li>Connor's game and coaches. They've embraced him and he's grown in his enjoyment of the game.</li>
<li>Tylenol, Ibuprofen, Excedrin... to alleviate the symptoms of my not taking great care of my body.</li>
<li>My wife, who lovingly didn't keep pestering me with questions when she saw I was hurting.</li>
<li>Sleep, and the restoration that brings.&nbsp;</li>
<li>The internet, roku, and Pastor Steven Furtick.</li>
<li>Blogger.Com for providing me the tools to journal without physical notebooks.</li>
<li>The dream of Idaho, and how it's only increased and not decreased.</li>
<li>Water to wash the dishes with.</li>
<li>Cold water to drink.</li>
<li>Air conditioner in my house.</li>
<li>An office to type in.</li>
<li>Avon</li>
<li>My gardens.</li>
<li>Freedom Ministries.</li>
<li>Karios</li>
<li>Bob Hamp</li>
<li>Serving in the Spirit, and not the flesh/physical. Open dialogue with my creator.&nbsp;</li>
<li>I need not bring you my list, I need only come to listen to what you would say.</li>
<li>Clarity of vision for the future and present. I have more clarity on who I am, and what I should do with my time, talent, and treasures... than I ever have had before.</li>
<li>Dream of a future and a hope. Specifically a dream to be a self employed writer/teacher/storyteller/creative. And 10+ acres on the lake with a writing office.</li>
<li>Snow, on occasions I get it.</li>
<li>JoAnn... and her insight and ability to bring it in.</li>
<li>Mom, and her affinity for family, fun, and pictures.</li>
<li>Dad, and his sobriety and the odd relationship we've developed.</li>
</ul>
<div>
<br /></div>
<div>
Darrell</div>
