---
title: 'The Shack, The Dream, The Early Morning'
date: '2016-04-06T11:52:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1276777731285917371'
blogger_filename: '/2016/04/the-shack-dream-early-morning.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'dream'
---

<br />
<br />
Wednesday 04/06/16 6:19 am<br />
<br />
So I've been reading The Shack, a man's encounter with God at the place of his daughter's murder. Too many lessons to put into an early morning post, it could take a whole book... oh wait... it DID take a whole book. LOL.<br />
<br />
So I went to bed after 12:13am last night, and I woke up (softly, suddenly, and completely) at 5:45 am. I laid there pondering my dream until I finally just got up at 6:12 am, and here I am.<br />
<br />
My dream reminded me of The Acrobat (only loosly) so I started a write up on the Story Structure of The Acrobat by Bob Hamp on It's Author Fun.<br />
<br />
I feel my dream was supernatural, not just another late night dream. So I started to pray about it in bed, but I just felt silence. I came into the office, in my chair, put I felt "you write better than you think", or something like that. So I'm here.<br />
<br />
So I met a long lost friend, and she and I were talking about the past many years.<br />
<br />
As I was playing with a circle and rope, hanging from the ceiling (Acrobatic Equipment), we were chatting about this and that, but I've lost those details now that I'm awake, so they must not have mattered.<br />
<br />
She said she'd rather not talk about the past, she's better off as a mystery. I agreed. In fact, I wasn't even curious in a nosy gossipy details sort of way.<br />
<div>
<br /></div>
Yet, I wanted to know her, her heart, so I said "That's fine. I've long ago taken you off of my romantic interest list. I want you to be the mystery, I appreciate that about you. Why don't you tell me anything you want to tell me about yourself, now or then."<br />
<div>
<br /></div>
She smiled, "I'd rather you didn't, just yet."<br />
<br />
Then a man was on the floor with some kids, I think it James Pratt, and we decided we couldn't talk in their presence.<br />
<br />
Then I woke up.<br />
<br />
<br />
------------------------------------------------------------------------------<br />
<br />
Somehow, in my heart, there are a storm of emotions trying to come up through this dream. As with many dreams, each element can mean more than one thing.<br />
<br />
I feel like the girl was Flavia, and I've forgotten the mystery that attracted me to her.<br />
<br />
In another sense, I feel like she represents so many of my past girlfriends and romantic interests. Even though I mentally decided to cut them off the list, my desire never stopped for many of them. The desire to keep them on the list is there, so how do I cut it off for good?<br />
<br />
------------------------------<br />
<br />
Sarayu (HolySpirit), is there anything you want to tell me about this dream?<br />
<br />
Healing. It reveals the condition of your heart. Healing cannot start until the problem is diagnosed and acknowledged.<br />
<br />
That's enough for now baby doll, go about your day. We'll chat later.<br />
<br />
God.<br />
<br />
--------------------------------<br />
<br />
**