---
title: 'Why won''t you speak to me?'
date: '2016-08-07T07:08:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3975179409197050326'
blogger_filename: '/2016/08/why-wont-you-speak-to-me.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Freedom Recovery (Kairos AA'
  - 'Healing'
  - 'Journal'
  - 'Feelings'
  - 'Growing Up'
---

You walked with Adam in the garden.<br />
<br />
You walked with Enoch.<br />
<br />
You worked with and took Elijah.<br />
<br />
You spoke with Moses and Abram.<br />
<br />
You spoke with Paul.<br />
<br />
You appeared to me once, when I was a child.<br />
<br />
Why do you insist on being so mysterious and missing in action? Why can't humans just see you, talk to you, and ask their questions? Why all the cloak and dagger?<br />
<br />
You say that things done in the darkness will come to light, why are you so hidden? Why don't you come into the light?<br />
<br />
How can I trust someone that never comes, never speaks, never shows up?<br />
<br />
<br />
---<br />
<br />
Yet you do show up, sometimes.<br />
<br />
You showed up for Jack, directing just the right events at just the right times... or was that just coincidence?<br />
<br />
You showed up when I went to that dealer in 2009, and get a car that wasn't even advertised, for the money we had available...<br />
<br />
BUT...<br />
<br />
WHY? Why didn't we have the money then? Why don't we have it now? You called us to this forsaken desert called Texas... you were supposed to be funding us. Instead I've had to borrow money to get the first decent car we've owned, and it's broken too. I had to borrow for a house I never liked. I had to pick my way through jobs I've hated, even riding my bike for a month when we first got here...<br />
<br />
YOU failed me... over and over... Your "so called" provisions have been a joke. <br />
<br />
Everything that comes through only brings more hardship.<br />
<br />
My mindset, developed since I've been here, is that : "If it's hard, it's not worth it".<br />
<br />
Maybe that's always been my mindset... even a genius intelligence has been a curse.<br />
<br />
I see, but can't do or fix.<br />
<br />
I see a future I want, but can't have it. We should have been self-employed and wealthy five years ago... and still we're here. In the land of everything fails.<br />
<br />
I don't get you... I don't know if I want to.<br />
<br />
WHY won't you let me leave this stupid planet?<br />
<br />
What else can you force on me, slave driver?<br />
<br />
Unlike my father, I don't doubt your existence... but I doubt your goodness.<br />
<br />
...<br />
<br />
IF you are good... help me see it... or leave me the fuck alone.<br />
<br />
Darrell