---
title: 'Acceptance was the answer'
date: '2016-01-13T07:06:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3563417657126737780'
blogger_filename: '/2016/01/acceptance-was-answer.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Freedom Recovery (Kairos AA'
  - 'Etc)'
  - 'Revelation'
  - 'kairos'
---

<br />
<br />
Last night, Monday 9pm Grapevine Unity AA meeting, the chosen leader read from the AA Big Book, chapter 16, Acceptance was the answer. <br />
<br />
This story sounded so eerily similar to my current circumstances, I nearly fell over:<br />
<br />
<blockquote class="tr_bq">
If there ever was anyone who came to A.A. by mistake, it was I. I just didn’t belong here. Never in my wildest moments had it occurred to me that I might like to be an alcoholic. Never once had my mother even hinted at the idea that, when I grew up, I might like to be president of A.A. Not only did I not think that being an alcoholic was a good idea, I didn’t even feel that I had all that much of a drinking problem! Of course, I had problems, all sorts of problems. “If you had my problems, you’d drink too” was my feeling.<br />
<br />
My major problems were marital. “If you had my wife, you’d drink too.” Max and I had been married for twenty-eight years when I ended up in A.A.<br />
<br />
It started out as a good marriage, but it deteriorated over the years as she progressed through the various stages of qualifying for Al-Anon. At ﬁrst, she would say, “You don’t love me. Why don’t you admit it?” Later, she would say, “You don’t like me. Why don’t you admit it?” And as her disease was reaching the terminal stages, she was screaming, “You hate me! You hate me! Why don’t you admit you hate me?” So I admitted it.<br />
I remember very well saying, <b>“There’s only one person in the world whose guts I hate worse than yours, and those are my own.”</b> She cried a bit and went to bed; that was the only answer to problems that she had left. I cried a bit and then mixed myself another drink. (Today, we don’t have to live like that any more.)<br />
<br />
<b>Max hadn’t gotten that way because I didn’t care. Indeed, it seemed that I cared too much. I had sent her to four consecutive psychiatrists, and not one of them had gotten me sober.</b><br />
I also sent my kids to psychiatrists. I remember, one time, even the dog had a psychiatric diagnosis. I yelled at Max, “What do you mean, ‘The dog just needs more love’? You tell that dumb cat-and-dog doctor he’s not a Beverly Hills psychiatrist. All I want to know is, why does that dog wet in my lap every time I hold him?” (That dog hasn’t wet my pants once since I joined A.A., and neither have I!)<br />
<br />
The harder I worked with Max, the sicker she got. So, when it ended up at a psycho ward, I wasn’t all that surprised. But then, when that steel door slammed shut, and she was the one that went home, I truly was amazed. </blockquote>
...<br />
<br />
<blockquote class="tr_bq">
In the hospital I hung on to the idea I’d had most of my life: that if I could just control the external environment, the internal environment would then become comfortable.&nbsp;</blockquote>
<br />
<blockquote class="tr_bq">
And life keeps getting simpler and easier as we try to reverse my old idea, by taking care of the internal environment via the Twelve Steps, and letting the external environment take care of itself.<br />
&nbsp;Right from the start, I felt that they weren’t doing anything for me, but they sure were helping Max.<br />
Finally, after seven months, I decided to try it. To this day, I am amazed at how many of my problems—most of which had nothing to do with drinking, I believed— have become manageable or have simply disappeared since I quit drinking.<br />
&nbsp;When I stopped living in the problem and began living in the answer, the problem went away. From that moment on, I have not had a single compulsion to drink. And acceptance is the answer to all my problems today. When I am disturbed, it is because I ﬁnd some person, place, thing, or situation—some fact of my life —unacceptable to me, and I can ﬁnd no serenity until I accept that person, place, thing, or situation as being exactly the way it is supposed to be at this moment. Nothing, absolutely nothing, happens in God’s world by mistake. Until I could accept my alcoholism, I could not stay sober; unless I accept life completely on life’s terms, I cannot be happy. I need to concentrate not so much on what needs to be changed in the world as on what needs to be changed in me and in my attitudes.<br />
Shakespeare said, “All the world’s a stage, and all the men and women merely players.” He forgot to mention that I was the chief critic. I was always able to see the ﬂaw in every person, every situation. And I was always glad to point it out, because I knew you wanted perfection, just as I did. A.A. and acceptance have taught me that there is a bit of good in the worst of us and a bit of bad in the best of us; that we are all children of God and we each have a right to be here. When I complain about me or about you, I am complaining about God’s handiwork. I am saying that I know better than God.<br />
Acceptance has been the answer to my marital problems. It’s as though A.A. had given me a new pair of glasses. Max and I have been married now for thirtyﬁve years. Prior to our marriage, when she was a shy, scrawny adolescent, I was able to see things in her that others couldn’t necessarily see—things like beauty, charm, gaiety, a gift for being easy to talk to, a sense of humor, and many other ﬁne qualities. It was as if I had, rather than a Midas touch which turned everything to gold, a magnifying mind that magniﬁed whatever it focused on. Over the years as I thought about Max, her good qualities grew and grew, and we married, and all these qualities became more and more apparent to me, and we were happier and happier. But then as I drank more and more, the alcohol seemed to affect my vision: Instead of continuing to see what was good about my wife, I began to see her defects. And the more I focused my mind on her defects, the more they grew and multiplied. Every defect I pointed out to her became greater and greater. Each time I told her she was a nothing, she receded a little more into nowhere. The more I drank, the more she wilted. Then, one day in A.A., I was told that I had the lenses in my glasses backwards; “the courage to change” in the Serenity Prayer meant not that I should change my marriage, but rather that I should change myself and learn to accept my spouse as she was. A.A. has given me a new pair of glasses. I can again focus on my wife’s good qualities and watch them grow and grow and grow.<br />
Eventually I had to redo each of the Twelve Steps speciﬁcally with Max in mind, from the First, saying, “I am powerless over alcohol, and my homelife is unmanageable by me,” to the Twelfth, in which I tried to think of her as a sick Al-Anon and treat her with the love I would give a sick A.A. newcomer. When I do this, we get along ﬁne.<br />
Perhaps the best thing of all for me is to remember that my serenity is inversely proportional to my expectations. The higher my expectations of Max and other people are, the lower is my serenity. I can watch my serenity level rise when I discard my expectations.<br />
Acceptance is the key to my relationship with God today. I never just sit and do nothing while waiting for Him to tell me what to do. Rather, I do whatever is in front of me to be done, and I leave the results up to Him; however it turns out, that’s God’s will for me.<br />
I must keep my magic magnifying mind on my acceptance and off my expectations, for my serenity is directly proportional to my level of acceptance.</blockquote>
<br />
<br />
Amazing... Another guy said it this way:<br />
<br />
<blockquote class="tr_bq">
I'm an Alcoholic, and my real problem is Darrell Wolfe.&nbsp;</blockquote>
And:<br />
<br />
<blockquote class="tr_bq">
"You know my problem? I'm Darrell, and I am the center of my own universe. I live on planet Darrell, In Darrell Town, on Darrell Street, at Castle Darrell. If you want to know where the center of the universe is, come to my house, I'm it."&nbsp;</blockquote>
<br />
Today in the book I'm reading, <a href="http://www.amazon.com/Your-key-Gods-bank-Humbard/dp/B0006WYQOI/ref=sr_1_12/182-3811800-2963854?s=books&amp;ie=UTF8&amp;qid=1452667983&amp;sr=1-12&amp;keywords=rex+humbard" target="_blank">Your key to God's bank Paperback – 1977by Rex Humbard</a> (Author), he talked about fasting on page 117.<br />
<br />
<blockquote class="tr_bq">
Fasting rather is to bring into captivity our thoughts, imaginations, and impulses to drew near to God so He can draw near to us. Fasting is getting in the place where God can speak to us.&nbsp;</blockquote>
<br />
Elijah met God in a cave, and God asked him: "Why are you here?" It was because Elijah was actually running from where he was supposed to be.<br />
<br />
Fasting is not about getting God to do my will, it's about me getting rid of Darrell as the center of Darrell's universe, and surrendering to God's thoughts about Flavia, Connor, Preston, Wells Fargo, Getting Early, Eating, Finances, etc, etc...<br />
<br />
For 12 years I've been treating Flavia like the enemy. Asking God what was wrong with this woman? Why is she so messed up? Why can't she just go pray and leave me alone? Fix her God! I did the same with both kids, especially Connor. "What's wrong with him God?" What's wrong with Flavia and Connor? Preston's the only normal one around here...<br />
<br />
Even the dogs were freaking out around me, and she'd say it was my fault, I'd say it's because something is wrong with them.<br />
<br />
Just like the guy from Chapter 16...<br />
<br />
The fact I think Preston is normal... worries me for Preston. Will he be more vulnerable to addiction than Connor... since I find so much in him to identify with?<br />
<br />
<br />
I guess I can't send them to a counselor to solve MY addiction... and my addiction is ME.<br />
<br />
Alcohol, Pornography, Pill Popping....<br />
Cheeseburgers, Soda, Coffee....<br />
<br />
Substances are irrelevant... I'm addicted to ME. I'm the center of my own universe. Every thought I have is about me. What is my calling? What is my gifting? What do I want today? What do I not want today? What makes me feel good, feel uncomfortable, feel whatever...<br />
<br />
Every conversation with another human is redirected to me. I will make their tragedy about me given a long enough conversation (5 min or less). If nothing else, it will be about how I want to avoid YOUR feelings, because of how they make ME feel.<br />
<br />
Fasting... is a way of removing SELF from the moment, and re-centering on HIM.<br />
<br />
Fasting is a way to get my thoughts aligned with his.<br />
<br />
Fasting is a way to draw closer to him... so that He can draw closer to me. He can't do it without fasting, because I'm too full of ME for him to get anywhere near.<br />
<br />
THIS KIND... selfishness and self centeredness.... comes out by prayer and fasting.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />