---
title: '2014-2015 In review - 01.31.16'
date: '2016-01-31T07:27:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5246960186074174210'
blogger_filename: '/2016/01/2014-2015-in-review-013116.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
2014-2015 In review - 01.31.16<br />
<h4>
Spiritual</h4>
<ul>
<li>... Groggy... Waking up to some things slowly, but... spiritually asleep. I know that a relationship with the Holy Spirit every morning and night is the only chance I have of saving my life before it's destroyed, but I still don't get up and put in the effort.&nbsp;</li>
</ul>
<br />
<ul>
<li>Most days... I wish I were dead, and I'm mad that God won't take me. I'd never kill myself, but I'm certainly not happy to be alive either. If God came down and gave me the choice, I'd leave this earth without a second thought about anything or anyone else. I HATE living, I always have... and I'm fearful that I always will.&nbsp;</li>
<li>Freedom Ministries, Kairos, Personal Ministry, Bob Hamp... they've all given me glimmers of hope for the first time in my 35 years of living... but only a glimmer. I've gone from 100% sure I'll never have more than an exist-for-the-sake-of-existing emotion, to a 90% sureness of that, and a 10% belief that it could change. I guess that's progress.</li>
</ul>
<br />
<br />
<h4>
Family</h4>
<ul>
<li>??????????????</li>
<li>This is THE question mark of my life. I feel Bi-Polar.&nbsp;</li>
<li>There are days that I feel a bond to these three under my roof. I feel that Flavia is my best friend, and the kids are great kids.&nbsp;</li>
<li>In a moment, in the blink of an eye, in the same day even, my emotions turn violently in my heart, I want them all to leave for Idaho. I then want to sell this house (and the associated pressure of bills) by a Tiny House and live alone somewhere.</li>
</ul>
<br />
<ul>
<li>Mustbethistalltoride.com is a great blog that's given us insight into where I'm missing her intentions and heart. BUT... CAN I turn this around? Can I be anything more than an emotional time bomb that's only half engaged (or less) in any activity involving my family? I honestly don't know. I don't know if I CAN be anything she needs me to be.&nbsp;</li>
</ul>
<br />
<br />
<div>
<br /></div>
<br />
<h4>
Professional</h4>
<ul>
<li>I was hired at the Wells Fargo Dealer Services - Office of the President (OTP) in May 2014. There was favor there. The hiring manager wasn't going to bring me on, but the other two interviewers insisted that she bring me on. I was then promoted to Team Lead and Dealer Complaints Specialist on February 12, 2015. In just a few days I will have been the Team Lead for a year.&nbsp;</li>
</ul>
<br />
<ul>
<li>The money was tight, because it was feast on OT weeks, and famine on non-OT weeks.</li>
</ul>
<br />
<br />
<ul>
<li>Things are deteriorating at OTP, and I am faced with a struggle I have faced times before.&nbsp;</li>
<ul>
<li>Do I stay, promote to manager and embrace a leadership role?</li>
<ul>
<li>If I stay, I may be able to lock in a Salary of $50,000, but I KNOW I'll work 50-60 hours. I'll struggle under the current leadership model (or lack thereof). But I'll have the opportunity to grow as a leader, and influence the creation of this new and better version of this office.</li>
</ul>
<li>Do I go, to a potentially more lucrative position (Compliance Consultant 2)?</li>
<ul>
<li>If I go to Compliance, I am facing a new world, again. I don't know what favor I will have there, or what challenges I will face. It's possible it will be less pressure, but it's possible it will be more. &nbsp;I'm much more likely to lock in a Salary closer to $60,000 (midpoint it $70,000). The Salary is in line with the goal I'm working toward. The position offers extreme independence, long term single-focused projects, and does not require I manage a team. It's more appealing to me at this point in time (01/31/16).</li>
</ul>
</ul>
</ul>
<br />
<br />
<h4>
Financial</h4>
<ul>
<li>Behind on several bills... still. I've been behind on bills as long as I've had any. I was over drafting when I was single. I'm behind on major bills for my entire 12 years of marriage. I'm tired of being poor.</li>
</ul>
<br />
<ul>
<li>That being said, last year (2015) I made $51,101.84 (including overtime). I reached a milestone. This was the first year that I made over $50,000 with one job. That was a goal, and it's been reached.&nbsp;</li>
</ul>
<ul>
<li>Next Goal: $60,000 Salary, One Job, less than 45 hours a week average worked. Every Bill paid ahead one month, two debt free cars in perfect working order ahead on maintenance, and $5,000 in savings.</li>
</ul>
<br />
<br />
<div>
<br /></div>
<br />
<h4>
Writing</h4>
<ul>
<li>I started a novel, I'm reading a lot about writing. I'm not writing much... at all.</li>
</ul>
<br />
<div>
<br /></div>
<br />
<h4>
Music</h4>
<ul>
<li>Took Audio 101 in Fall 2013. Shortly after January 2014 I made a tough decision. Although I enjoy Audio, it's not a career path for me. At least, not in any traditional sense.&nbsp;</li>
<ul>
<li>I'm not going to be a musician on stage like Garth Brooks, Michael Jackson, or Bryan Duncan. I don't have the musical study, physical mechanics, or (most importantly) the passion for it. I just don't enjoy it enough to do it full time.</li>
</ul>
<br />
<ul>
<li>I'm not going to be an Audio Technician. Those guys are lucky to get paid $15.00/Hr. I enjoy Audio. I may want to get a studio and mix as a hobby. Maybe something would come of it, but I just don't see myself as a "Musician" or "Audio Guy".&nbsp;</li>
<li>Music is a passing hobby, and less even that anymore (01/31/16).</li>
</ul>
</ul>
