---
title: 'Breakthrough: Freedom From Incubus'
date: '2016-01-08T18:27:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5973057301127477419'
blogger_filename: '/2016/01/breakthrough-freedom-from-incubus.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Word From God'
  - 'Revelation'
  - 'kairos'
---

This prayer was handwritten in my journal yesterday. It so momentous that I had to preserve it here.<br />
<br />
Dear God (Father, Jesus, and HolySpirit),<br />
<br />
I'm mad at you. In my heart, I am a frustrated, exhausted, little boy. I feel a nearly constant pull to be more than I am, with an equally strong assurance and conviction that I have nothing more in me to give.<br />
<br />
* But this didn't quite get at the heart of it.<br />
<br />
I don't have what you are asking for...<br />
<br />
Holiness, Purity, It's not in me...<br />
<br />
I fail<br />
<br />
I'm not enough<br />
<br />
I can't<br />
<br />
There are two minds in me at all times. Since at least 5 years old.<br />
<br />
<br />
<ul>
<li>The mind to pursue you</li>
<li>The mind to pursue "Her"</li>
</ul>
<br />
<br />
Who IS she? A figment of my imagination, a spirit, a sprite, an <a href="https://en.wikipedia.org/wiki/Incubus" target="_blank">Incubus</a>?<br />
<br />
My entire life has been spent (wasted) in the pursuit of... Mystery Woman?<br />
<br />
It's not sex, although it was embodied in sex often enough. Every gift, talent, ability, calling, purpose, virtue... they were all cast aside by me in pursuit of... Her.<br />
<br />
Every girl I caught in the pursuit proved to be NOT HER. Catch and release fishing. Some, I thought, could be her. Others I knew from the start were just distractions to sooth the itching desire and pass the time.<br />
<br />
Some came close, but only in-as-much as they stayed mysterious, distant, out of reach. The promise was always more appealing than the reality.<br />
<br />
SHE became my Drug of Choice (DOC).<br />
<br />
Just as other men have sacrificed their music &amp; art for physical drugs; I sacrificed them for HER.<br />
<br />
As I sit (last night and right now), quietly, in my office, my War Room, I am faced with a hard truth.<br />
<br />
<div>
<ol>
<li>SHE is not real, and never was.</li>
<li>SHE was a virus, planted by an Incubus spirit early in my life (3-5 years old).</li>
</ol>
<div>
The seeds of this were planted early. Mom's soap operas and who knows what else. Fertilized when I was 5 years old by a local girl. Watered when I was 6-9 by another local girl. Growing stronger and more potent with each pursuit.&nbsp;</div>
</div>
<br />
Before today, I never acknowledged or personified this feeling or pursuit. I thought I WAS pursuing a real person (hidden out there somewhere), a love, a soul mate... but I now know that I was not. I was being led by an evil, addictive, and self-destructive spirit.<br />
<br />
Only a demonic spirit of addiction would produce the fruit and results this kind has, leading me to hurt the people I hurt, take the risks I took, casting aside calling, purpose, and disregarding sound counsel, repeatedly.<br />
<br />
Due to tonights (last nights) study of <a href="https://en.wikipedia.org/wiki/Historia_Brittonum" target="_blank">Britain's History</a>&nbsp;, and the mythologies surrounding <a href="https://en.wikipedia.org/wiki/Gogmagog_(giant)" target="_blank">GogMagog</a> and <a href="https://en.wikipedia.org/wiki/Incubus" target="_blank">Incubus</a>, I have elected to call the spirit Incubus - Whore of Babylon.<br />
<br />
Incubus conjured images of secret connections, passion, love-lust, openness to another, through mystery, telepathic communication, desire, lust, etc...<br />
<br />
When I refused, from time to time, it's attempts to physically take me in, SHE found me in magazines (when I was young), and online when I was older... in the powerful realm of imagination.<br />
<br />
My ENTIRE life (3yr-35yr) has been a see-saw of drawing closer to God, but then leaving Him for HER (Spiritual/Physical adultery against the HolySpirit).<br />
<br />
Irony: The very things I sought (spiritual experience, mystery, connectedness of mind-body-spirit) can only have their true expression in communion with the HolySpirit; yet I rejected Him in pursuit of HER.<br />
<br />
The stronger HER influence in my life, the more irritated and agitated I would become. The more isolated I became. The less I wanted to pray, read my bible, go to church, be around other human beings (except for the few who carried her spirit), the less I wanted to sing, play guitar, dance, smile, write, create anything.<br />
<br />
Around HER I am as Sherlock Holmes on a cocaine binge. This isn't just like an addiction, it IS an addiction. All addiction is spiritual, but this addiction is to a spirit. It was THIS spirit, JoAnn saw on me by my truck many years ago that night.<br />
<br />
The wonderful thing about light and darkness, is that darkness is not the opposite of light, it is the absence of it. Darkness is not struggling against the light, it is attempting to take me out of the light so that it can thrive. I only need to keep this spirit in the light, to expose it, and remain free forever.<br />
<br />
Prayer, and the HolySpirit are not part of the solution, they ARE the solution. Everything SHE found in my to hook on, was twisted from the very needs HolySpirit designed me to find fulfillment for in HIM.<br />
<br />
I have been saved since 3, called since 10, surrendered since 22, baptized in the spirit since 23... I have been been possessed, but I have been oppressed. <a href="http://gatewaypeople.com/ministries/life/events/free-indeed/session/2013/10/19/believers-in-bondage" target="_blank">Paster Robert talked about being oppressed</a> as a believer, and I am now, tonight, admitting that it is me he was preaching to.<br />
<br />
Father, forgive me, for putting another spirit above you, and surrendering to it. I didn't know at 3, 5, 10... but I do now.<br />
<br />
Jesus, wash me in your blood, purge me of the influence SHE brought into my life, mind, heart. Replace the death trees in my brain with life trees.<br />
<br />
HolySpirit, I am surrendering to you now, as I used to surrender to HER. Please help me find my source of passion, desire, and mystery in you.<br />
<br />
Where do I start? HERE<br />
When do I start? NOW<br />
How do I start? Surrender<br />
<br />
Darrell Wolfe (4-5 AM CT, 01/08/15)