---
title: 'Boiling June 24th 2017'
date: '2017-06-25T02:20:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8979665097839139845'
blogger_filename: '/2017/06/boiling-june-24th-2017.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<p dir="ltr">I've had a rough week. Very busy. Kids off people. Draining. Exhausting. And for what? Why?</p>
<p dir="ltr">I left the only woman I ever felt got me... I went back to my wife, despite our constant miscommunication. I left the first job I ever liked, making the most I've ever made. I followed God and Flavia to a land that I like (geographically speaking) but nothing works here. </p>
<p dir="ltr">We got a ratty old house where I still have to do yard work instead of a nice apartment with gym and pool. </p>
<p dir="ltr">I ended up working for a great company, but doing a job that's not in my primary skill set and making half what I was making. We can't afford the ratty house with this job. </p>
<p dir="ltr">We found an ok church, but it's no Gateway. </p>
<p dir="ltr">One of my managers is fired for no good reason and this "great" company. </p>
<p dir="ltr">Why the FUCK am I here? Why didn't I just start in Texas and at WFDS and get an apartment?</p>
<p dir="ltr">Then today, my disrespectful ungrateful son continues to disobey and talk back and get up when I tell him to sit. And you want to sound my money in your damn to and cards? Get a fucking job. I'm done using for your shit.</p>
<p dir="ltr">My wife? She's to lazy to lose weight, and I'm supposed to keep pretending that I'm attracted to her when I struggle to even find body parts? And she stays home, doesn't work for 13 years, but cries when she does dishes and can't be bothered to learn how to cook because she doesn't enjoy it? We'll fuck you! I don't enjoy selling people checking accounts but I came out here for you and you can't lift a finger to be a normal stay at home wife? What the fuck am I getting out of this deal?</p>
<p dir="ltr">I'm getting a wife who cries if I'm honest. Who's to lazy to try to be attractive. Who's to lazy to do normal stay home shit. I'm getting a woman who hangs out with the kids I didn't want and does nothing all day but art, tv, and Facebook, then I have to come home and do the crap she's supposed to be doing as a " Stay at home wife". </p>
<p dir="ltr">I'm losing my God damn mind.</p>
<p dir="ltr">I hate you Abba! <br><br><br><br><br><br><br></p>
