---
title: 'What the hell do I want?'
date: '2017-12-20T08:52:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '251174865538556612'
blogger_filename: '/2017/12/what-hell-do-i-want.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

I don't want this... what I have. At any point in life, "this" (what I have at the moment) is never what I want. Every relationship, every job, every major, every decision... I've always wanted something else.<br />
<br />
I look at before/after weight loss photo's in hopes of getting hope that someday Flavia won't be grossly overweight. That someday, she'll be physically attractive. But will that change anything? I mean, she's right... there's always someone else more attractive.<br />
<br />
Still... it matters right? I mean, there's a reason that some looks are considered more attractive than others. Some things are a matter of taste or preference, but other things are universally accepted. It does matter...<br />
<br />
It's not that I'm never attracted to her. There are moments where I see past it, see around it, find the inside of her attractive, or, something? There are moments... But in general... I just don't.<br />
<br />
If I tell her that, it won't help anything. She already knows. She's trying, kind of, sometimes. She tries more than I do. I guess I kind of figured that if she's going to be overweight there's no reason for me to try. It's harder for women. If I try, I'll change overnight, and she'll be more depressed about it, which will prolong the weight problem... if it even CAN be solved.<br />
<br />
I look at guys who say they are so lucky to be married... I'm like, "Sure, you can say that, look at your wife".<br />
<br />
The trouble is, I really do love Flavia. Why the hell else would I be here still? I'm trying, God Dammit! But I don't know how to make her skinnier, or myself want her as-is. Fuck this shit is hard!<br />
<br />
She asked me today if everything was OK... I said what I always say, "Nothing we haven't talked about before." That's the truth. The weight issue has been discussed. There's nothing more to say. She's either going to lose weight, or we'll be stuck in this cycle of both wanting something we're not getting.<br />
<br />
I'm supposed to die to self, so I'm staying. I'm here. But my "heart" isn't in it.<br />
<br />
Maybe it would help if I told her that I'm not asking for a super-model. I'm not asking her to be free of stretch marks, or a 'perfect' body, or anything like that. I'd just like her to be handle-able. Fuck, I'd like to be able to pick her up and hold her against a wall. I'd like her to fit next to me on the couch. It's hard (impossible) to cuddle with her at this size.<br />
<br />
Pretty much everything she wants would be within range of possible if she was 190, 180, something under 200.<br />
<br />
The fitness sites generally say that a woman between 5'5"/5'8" should be between 118-160. I'm casting a wide net there. I'd settle for 180-190...<br />
<br />
I have a foot fetish, maybe if she was within the scope of "normal" sized, her feet would be attractive again too? Maybe not... I don't know.<br />
<br />
I've been hoping since 2003 (since before I married her) that she'd lose weight... I thought I could marry her and it would happen after, like love her to health. The problem is, I can't love. Not really.<br />
<br />
I don't know how. I'm broken... always have been. I've screwed up everything that ever resembled a connection.<br />
<br />
I only made it worse.<br />
<br />
I always make things worse.<br />
<br />
Maybe if I'm lucky, I'll ice skid off a bridge, and she can find someone who CAN love her to health... Then we can both have what we went. I can be free of this constant torment (my body/mind) and she can find someone capable of providing whatever the fuck it is she needs.<br />
<br />
I need a xanax... Goodnight.<br />
<br />
<br />
PS: I'm sure other-me has other things, more constructive things, to say. That's the one who's more rational and clear and spiritual. Maybe that me will sit down to write soon.