---
title: 'Can&#39;t talk'
date: '2017-08-21T08:55:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5540871992171859143'
blogger_filename: '/2017/08/can-talk.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<p dir="ltr">Flavia,</p>
<p dir="ltr">I wish I could talk to you like I did Alison. With no holding back, no hiding. But unlike her, you are hard to talk to. You question everything judgmentally. You want me to be your version of me. I can't just be me. </p>
<p dir="ltr">I want you to say: I'd rather you not smoke, but if you need to, please don't do it around the kids. And be ok with that. </p>
<p dir="ltr">Then again, I want to say threesome and you say ok, let me know when. </p>
<p dir="ltr">I want you to be a size 10 or 6, instead of a whatever you are, 1,000? </p>
<p dir="ltr">I don't know if I can keep doing this. I'm physically hurting myself to get past layers of fat in a vain attempt to reach you vagina. You have cooking. You don't clean.</p>
<p dir="ltr">You've been at work nights and honestly.... I don't notice the difference. The house and kids are the same as far as I can tell. </p>
<p dir="ltr">I wish I'd stayed at WFDS with Alison, but that ship has sailed... So I'm here... But I don't know how much longer.</p>
<p dir="ltr">You're a mom, not a wife.</p>
<p dir="ltr">I was never meant for this. I'm a stay until the wind blows another direction type. I'm not a monogamous decades type. </p>
<p dir="ltr">God messed up creating me, or the world is broken and I'm broken, I don't know...</p>
<p dir="ltr">I'm tired. Not just physically, I'm tired. I want to leave.</p>
<p dir="ltr">I'm either going one of three ways...</p>
<p dir="ltr">Leaving you and the kids.<br>
Leaving Earth.<br>
Some miracle fixes what's broken... I doubt this one.</p>
<p dir="ltr">I'm sorry. I wish I could snap my fingers and feel differently. Nothing worked. God hates me or something, I guess.</p>
<p dir="ltr">D<br>
</p>
