---
title: 'Church Notes 07/16/2017'
date: '2017-07-16T19:33:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8004060198375478894'
blogger_filename: '/2017/07/church-notes-07162017.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Church Notes'
---

<p dir="ltr">Sunday, July 16, 2017 11:54 AM Heart Of The City Church July 15, 2017<br>
==================================== Freedom Kingdom Pt. 2 null http://bible.com/events/248217 ==================================== </p>
<p dir="ltr">1 Timothy 2:6 NLT He gave his life to purchase freedom for everyone. This is the message God gave to the world at just the right time. http://bible.com/116/1ti.2.6.NLT</p>
<p dir="ltr">Galatians 5:1 NLT So Christ has truly set us free. Now make sure that you stay free, and don&#8217;t get tied up again in slavery to the law. http://bible.com/116/gal.5.1.NLT </p>
<p dir="ltr">Freedom Faith </p>
<p dir="ltr">Romans 1:17 NLT This Good News tells us how God makes us right in his sight. This is accomplished from start to finish by faith. As the Scriptures say, &#8220;It is through faith that a righteous person has life.&#8221; http://bible.com/116/rom.1.17.NLT </p>
<p dir="ltr">Freedom Believing </p>
<p dir="ltr">John 14:15-18 NKJV &#8220;If you love Me, keep My commandments. And I will pray the Father, and He will give you another Helper, that He may abide with you forever&#8212; the Spirit of truth, whom the world cannot receive, because it neither sees Him nor knows Him; but you know Him, for He dwells with you and will be in you. I will not leave you orphans; I will come to you. http://bible.com/114/jhn.14.15-18.NKJV </p>
<p dir="ltr">Wrong thinking about God </p>
<p dir="ltr">Psalms 145:8 NKJV The Lord is gracious and full of compassion, Slow to anger and great in mercy. http://bible.com/114/psa.145.8.NKJV </p>
<p dir="ltr">Wrong thinking and believing of others... </p>
<p dir="ltr">Luke 6:37-38 NKJV &#8220;Judge not, and you shall not be judged. Condemn not, and you shall not be condemned. Forgive, and you will be forgiven. Give, and it will be given to you: good measure, pressed down, shaken together, and running over will be put into your bosom. For with the same measure that you use, it will be measured back to you.&#8221; http://bible.com/114/luk.6.37-38.NKJV </p>
<p dir="ltr">Wrong thinking or believing of self negative self talk </p>
<p dir="ltr">II Corinthians 10:3-5 NKJV For though we walk in the flesh, we do not war according to the flesh. For the weapons of our warfare are not carnal but mighty in God for pulling down strongholds, casting down arguments and every high thing that exalts itself against the knowledge of God, bringing every thought into captivity to the obedience of Christ, http://bible.com/114/2co.10.3-5.NKJV </p>
<p dir="ltr">Freedom Words Process</p>
<p dir="ltr">*Worship vs Worry</p>
<p dir="ltr">*Pray vs Process</p>
<p dir="ltr">*Read vs Rehearse/Repeat/Reason</p>
<p dir="ltr">*Listen vs List</p>
<p dir="ltr">*Speak Truth vs Speak Lies</p>
<p dir="ltr">*</p>
<p dir="ltr">Speak to the mountain instead of speaking about the mountain.</p>
<p dir="ltr">1 Samuel 17:45 - Then David said to the Philistine, &#8220;You come to me with a sword, with a spear, and with a javelin. But I come to you in the name of the Lord of hosts, the God of the armies of Israel, whom you have defied.<br>
I Samuel 17:45 NKJV<br>
http://<b>bible.com</b>/114/1sa.17.45.NKJV<br></p>
<p dir="ltr">DarrellWolfe @HeartCDA</p>
