---
title: 'What do I want?'
date: '2017-12-15T08:30:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2851128517042004670'
blogger_filename: '/2017/12/what-do-i-want.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<p dir="ltr">I wish I could change what I want... How do I do that? Anyone? Pfft....</p>
<p dir="ltr">I'm not sure what I really want. I want the wife and family I have. I want four or five ex-girlfriends. I want a few ladies I've only met in an image online. I want some I never had, but wanted. I want a still un-named un-faced imagination that haunts me but never shows itself.... I want it all, and none of it. </p>
<p dir="ltr">I want a thousand imagined moments, strung together with various people, most of which never happened...</p>
<p dir="ltr">I don't want...</p>
<p dir="ltr">Bills<br>
House payments<br>
Family, theirs or mine<br>
Jobs<br>
Responsibilities<br>
Pretty much anything that resembles real life.....</p>
<p dir="ltr">I want the highlights, not the day to day.</p>
<p dir="ltr">A thousand "what if" senarios run through my mind. Some about the future, must about what might have been if... Going back to very young.</p>
<p dir="ltr">Can I ever be happy? I'm not sure. I don't think so... I wish a commet would land on my head... </p>
<p dir="ltr">Oh well. </p>
<p dir="ltr">Still here. <br></p>
<p dir="ltr">Pfft!<br><br><br><br><br><br><br><br><br></p>
