---
title: 'My Addiction Story... Part 1'
date: '2017-12-26T09:18:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1251356758217000658'
blogger_filename: '/2017/12/my-addiction-story-part-1.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

So... here's the thing. The Pure Desire, Seven Pillars workbook asks me to write an addiction story. When I was __ this happened. Then this happened. Timeline style.<br />
<br />
The workbook&nbsp;and videos also break down the limbic system, and how desires, fears, and auto-responses were mostly created early, before 6 years old, give or take.<br />
<br />
I've been thinking about my history and timeline for years, wondering why I am the way I am. So this sounds like promising homework. I started in on paper, but the deep level I want to travel will take more space. I plan to outline every relevant (or possibly relevant) moment.<br />
<br />
Also, I'm inspired to start again because of a <a href="http://www.pbs.org/independentlens/blog/for-filmmakers-geeta-and-ravi-patel-love-is-a-family-affair/" target="_blank">KPBS</a> special "<a href="http://www.pbs.org/independentlens/films/meet-the-patels/" target="_blank">Meet the Patels</a>", in which Ravi Patel (as shown through the lens of his sister's (Geeta Patel's - Film Maker) camera. It's a long story, worth seeing. It showed the struggles of American&nbsp;dating vs the arranged or partially-arranged type marriage systems.<br />
<br />
Without further ado... Here is my story:<br />
<br />
I was born to an Alcoholic Pastor (father) and a co-dependant Nurse (mother). My mother worked at the hospital at night, while my dad went to school/work during the day.<br />
<br />
I don't recall (obviously, due to age), but I'm told that at least on one occasion he left me alone (6-months old) in the middle of the night in my crib to go get more alcohol. He was so concerned that he would be pulled over and arrested and exposed, ruin his church career.<br />
<br />
<h4>
Bellflower (1980-1985):&nbsp;</h4>
There's probably history before Bellflower, but none that I am aware matters to my story. I actually remember eating the neighbor's cat food while they were on vacation, to see what it would taste like. I also ate pine-needles from the Christmas tree. I'm fairly certain both occasions resulted in my vomiting. It may or may not be relevant, but I feel it's an interesting fact.<br />
<br />
It's possible it was in Agoura; however, I'm fairly certain the timing of these events took place here.<br />
<br />
<ul>
<li>I saw Jesus. I was young, like in the 1 1/2 deep water kiddy-pool young. I was playing in the water, and I just looked up. Jesus was on his throne. He was surrounded&nbsp;by angels, in the clouds. Then, he was alone. Then, I could see him far away, and near at the same time. He never "spoke" audible words. But he sent a message that "felt" like this: "I'm here. I'm with you. I'm going to take care of you..." or... something like that. It wasn't audible, still hard to put into words today.</li>
</ul>
<div>
<br /></div>
<ul>
<li>I saw a demon. Specifically, the demon assigned to my brother, Devin. We had a room with two beds and a night-stand in between. The door was at the foot of my bed, which led down a hallway directly to Mom &amp; Dad's room (I just noticed the order, that may say something Mom, then Dad?). I had been asleep, then I was suddenly awake. I looked over and there was Mom, in her light blue nightgown, looking at Devin. BUT, nothing felt right. It felt very wrong. "She" turned her head to look at me, and its eye holes were hallow black. "She" also sent a clear inaudible message. "He's mine, stay out of my way". It turned robotically back and forth between me and him a few times, slowly. When it turned, I ran down the hallway to Mom &amp; Dad's room. After they calmed me down, they assured me it was just a dream and put me back to bed. I am 37 and I can tell you, it was not a dream.</li>
</ul>
<div>
<br /></div>
<ul>
<li>3 Years Old: I don't recall, but I feel it's important to note: My mom tells the story of me coming to her about 3 years old. She'd been watching many soap operas at that time. I said: "Kiss me, mommy... No, No... Like they do on the TV".</li>
</ul>
<br />
<br />
<h4>
Agoura Hills (~1985-1987):</h4>
A few remarkable things happened here. I continued to have dreams about Devin, nightmares.<br />
<br />
<ul>
<li>In one particular nightmare, Devin was stuck, chained, at the bottom of the pool. I ran into the house and told Mom, and she said: "That's nice dear" and ignored my pleas to come help. I ran back and dove to the bottom of the pool and tried to free him. We were both drowning, I woke up.</li>
</ul>
<div>
The other remarkable thing about Agoura Hills was young HM. She &amp; I were both about five years old. She was a cute little blond girl.</div>
<div>
<br /></div>
<div>
I have no idea to this day who's idea it was, or how we got started. I can tell you, we got naked often. We touched, we groped, we placed hands and fingers anywhere we could.</div>
<div>
<ul>
<li>On one occasion, we knew we had to keep this secret, so we hid in front of a truck parked in a driveway, between the grill and the garage door. We were small enough not be noticed.</li>
<li>In another occasion, we hid in the closet (did that many times).</li>
<li>One occasion, we were jumping up and down naked in the bathroom, with other kids.&nbsp;</li>
</ul>
</div>
I left Agoura Hills too young to realize what "never again see my friend" really meant. But I feel like a part of me looked for her, or people like her, from that day forward. Not "like her" physically, although I did date a lot of blonds; but, "like her" in the sense that I could find someone to be free with, naked with, and connect with emotionally.<br />
<br />
Throughout my life, girls who were too into themselves, too popular, too superficial... etc... didn't do it for me. There had to be a raw, openness, and an obvious desire to be naked and explore what that meant fully.<br />
<br />
<b><i>Side Note:</i></b> <i>She found me later in life (2015-2016?). If you can remember my name, I'm not hard to find. I made my name a brand through my website. But HM found me, and we've swapped stories about those years. I won't tell you her story, it's not mine to tell. But it was interesting and enlightening to see so many parallels about where we went from there.&nbsp;</i><br />
<br />
<h4>
Spearman, Texas (~1987-1989):</h4>
We moved to the Panhandle of Texas. I got "lucky". I met my new best-friend (BB) the day we moved into town. She lived two doors down. Her brother became my brother's best friend (just alike those two) so we had a great time. We climbed trees, made forts, snuck into the neighborhood "haunted house"... and ran away scared.<br />
<br />
This time I'm fairly certain it was my idea, as I'd just brought my new talents from California. We played "house", got naked, touched, and it went on the entire time I lived there.<br />
<ul>
<li>On one occasion, I recall playing house in her room at her house and having my brother breastfeed. Then, when he wasn't there, I got my mouth on her (non-existent, cause she was too young) breasts.&nbsp; I feel like there's this theme of me wanting to put things in my mouth?</li>
</ul>
<ul>
<li>On another occasion, I recall us hiding beneath the covers in my room. Mom walked in and scolded us for being under the covers, but it was all innocent like. "Ok, I'm glad you two are having fun, but let's get out from under the covers ok?" Little did she know we were pants-less under the covers. We just said "OK" and she walked out. We hid under the bed after that.&nbsp;</li>
</ul>
<div>
I was too young to have specific memories of missing HM, just a vague sense of missing. But when we left Spearman I cried for most of the first day driving back to CA. I still cried about her over the years since. Sometimes, even in my adult years, this profound sadness comes over me when I think of her, and how much I miss those times.&nbsp;</div>
<div>
<br /></div>
<div>
Agoura Hills &amp; Spearman were the only times I can recall in my life being truly happy. I was never really happy again.</div>
<div>
<br /></div>
<div>
I've smiled, and laughed... but the last time I ever smiled without a profound sadness in my heart underneath was in Spearman Texas. Everything after that was tainted by sadness.</div>
<div>
<br /></div>
<h4>
Indio, CA (1989-1994;<span style="font-weight: normal;"> (and later also:: 1996-2001; 2001-2004)</span>):</h4>
<div>
So, let's recap. By the time I was 9 years old, I'd been naked with at least two girls, seen Jesus, seen a Demon, had nightmares and moved 3-4 times. I'm fairly certain I learned a lesson I still haven't unlearned to this day:</div>
<blockquote class="tr_bq">
<i>If you enjoy something, it will be taken from you, eventually. Don't attach to anything.&nbsp;</i></blockquote>
<div>
We started in a small apartment and then bought a home in 1989-1990. As of this writing (05/24/2019), my mom still owns that home.<br />
<br /></div>
<div>
<b><br /></b></div>
<div>
<b>Madison Elementary School:</b></div>
<br />
I went to Madison for the 4th and 5th grade. My 4th-grade teacher, Theresa Barranco, might be the best teacher I ever had. Her lessons through art allowed me to stay engaged in my right brain and learn through the creative process. Everything from math to history could be learned through art.<br />
<br />
My fifth-grade teacher; however, was the worst teacher I ever had... and I don't ever recall why. Something about her teaching style was the opposite in every way. She was like anti-learning. I don't recall her name and don't intend to.<br />
<br />
In the 4th-grade I met another "her", HH. She was another blond, that's three in a row. I'm not positive, but I think it's possible I never got naked with this one. Probably due to her never coming over to my house, and the school not having a place to "play". Maybe we did and I don't recall, but I'm thinking we didn't.<br />
<br />
But my heart was there. HH had to move away halfway through fifth grade. She left for the east coast, North Carolina if I recall. Or maybe Virginia? I was sure I was in love with her (at 9-10 years old). We both promised that she'd come back to CA when she turned 18 and we'd get married.<br />
<br />
Funny, even years later, when I turned 18-19, I kept looking for her. But Facebook hadn't been invented yet, and the internet was new. Never found her again.<br />
<br />
<br />
<b>Homeschool:</b><br />
<br />
I left 5th-grade half-way through to be homeschooled. I forced it on my parents. Mom dropped me off one day and I "ran away" and hid behind a grocery store. She found me, apparently she noticed I'd run away from the school instead of to it. She pitied me, or gave up trying to understand, or...whatever it worked. I got to homeschool.<br />
<br />
I finished 5th, 6th, and 7th between 1992-1993 (one school year). Did I mention I have 148 IQ (or higher, they say these things are actually malleable)?<br />
<br />
Not much happened here. I was alone, in my room, for the entire year. And I loved it that way. The only memory that I think applies to this period was "the surprise party". I've complained ad nauseum about this so I'll keep it short.<br />
<ul>
<li>My mom specifically asked me what I wanted for my birthday, circa 1993 (13 years old). I said I wanted to take my birthday money, go shopping, and come up to my room and be left alone for the day.&nbsp;</li>
</ul>
<ul>
<li>We did that first part, and she asked me to go to the garage to get some soda's out. "Suprise!" The crowd yelled. I don't know how many were there, but my emotional-memory says 50-100. For my taste, that may as well have been a million. I was SO angry, I turned, pushed her aside, and went to my room like I'd planned. I think maybe I was only there a few minutes before she convinced me to come "duty" bound. But it feels like I was there hours, pouting, angry.&nbsp;</li>
</ul>
I recall nothing of that day, other than the feeling of being controlled and violated.<br />
<br />
It was also in these years I became convinced that I was called to ministry. I was baptized, and we played at the church a lot, homeschooled. We will walk to the corner store and buy treats. And I would hang out alone in the sanctuary. The sanctuary became my safe-space. I still enjoy a quiet sanctuary or alter area.<br />
<br />
I became convinced that I will pastor someday. Not just anywhere, but pastor there at that building. I became obsessed with the idea over the years. I even looked up blue prints and property records for the area. I wanted to put what I would later learn was a Gateway Church still ministry there. I also grew to gradually believe I could never do that. One part of me was in love with Jesus, the other couldn't stay celibate or with the person. I just knew that if I became a pastor I'd fall, just like Jimmy Swaggert.<br />
<b><br /></b> <b>Jefferson Middle School (~1993-1994):</b><br />
<br />
I made a few friends (at least a few of which I still know to this day). Josh, Jason, Roger, Peter; Hey guys!<br />
<br />
I "dated" this girl, cannot recall her name, for all of a few minutes. I recall her breaking up with me after making out against a wall behind the school. Or... something like that. Cloudy memory there.<br />
<br />
I also went to 8th-grade prom with a girl CC. She was not a blond, she was of latina heritage. She was a track star, and my heart was pounding when I saw her legs. She got me into track that whole year. She went to prom with me, but then broke up with me at prom because her friends thought I was a nerd. I was heart-broken.<br />
<br />
Somewhere in this period, I discovered Victoria's Secret Magazines and olive oil. The perfect introduction to masturbation. I later learned lotion was easier, less messy, but not as much fun. At least the girls in the magazine looked like they wanted me... some of them anyway. It's weird, some have "that look" in their eye, and some were just smiling but not looking at/for me. That's the way it felt. There's a look in the eye first before the body matters... much. If the body comes first, the look still has to be there. Or, something about their demeanor. It's hard to place my finger on... No Pun Intended. Ha ha!<br />
<br />
And then... we moved again anyway.<br />
<br />
<i>*Note: Somewhere in my early teens, not sure when (might have been 13? but may have been younger) I have a distinct memory of a male sleeping over at my house and hanging out with me in my bed-tent. I remember putting my mouth on his penis. I remember nothing else and only a faint idea of who he might have been. Must have blocked that one out.</i><br />
<i><br /></i>
<i>*Note: I also recall that 13 years old was around the time that a male friend from Spearman, TX died. He had been practicing masturbation with asphyxiation, and the rope never loosened. He was found like that in his attic. I went back with my mom to visit. I got to see BB again. It was a great visit, but things had changed with the onset of early puberty, and we never really touched on the subject of our earlier activities. Not that I recall, anyway.</i><br />
<br />
<h4>
Brea, CA (1994-1995):</h4>
We moved to Brea, CA just in time for me to start Freshman year at Brea-Olinda High School. We also started pastoring the First Christian Church, Norwalk, CA. I didn't know it then, but Dad had already become an Athiest by this point and this became the impetus for moving to Orange County. He wanted to be closer to the school he was attending so he could get a second masters&nbsp;degree, this time in Marriage &amp; Family Therapy (MFT). How ironic.<br />
<br />
It was in the youth group at this church I made friends with Brandon and Niel, and I met SJ. White, dark black hair, and desperate for attention. The last part, being my signature feature, drew me in. It was short-lived, we dated as groups.<br />
<ul>
<li>On one occasion I recall going to a movie theater and putting my hands in her pants, and my fingers inside. The smell and taste were intoxicating. I don't believe she returned the favor. I'm fairly certain her sister broke up for her while we were at a beach party.&nbsp;</li>
</ul>
<div>
<br /></div>
<h4>
Diamond Bar, CA (1995-1996):</h4>
After we moved to Diamond Bar, my brother Devin started dealing drugs (in Junior High). I still attended Brea-Olinda HS. Since I was the "good kid", and Devin and Ryan were both in their own version of louder chaos, I was pretty much left to be however I was going to be.<br />
<br />
In Diamond Bar, I met M.E. She was dark-skinned, brown curly-wavey hair. Might have been mixed (Mexican/Black)? She was wild. She would swim under me at the pool and blow air bubbles up my shorts. We kissed some, but eventually, she broke up with me. I'm sure nothing else happened physically. However, she loved my hair, long down to the middle of my back. In retaliation of her break up, I shaved my head. I also started smoking and drinking with the help of a friend in the neighborhood. His mom bought his cigarettes and liquor for him (better at home where I know what he's doing, was her argument... always felt strange to me).<br />
<br />
I'm fairly certain sophomore year was when I also "dated" T, but that could have been Freshman year. We were all friends, part of a group. Our group told us we should "date", so we verbally agreed to it. Then proceeded not to talk to each other for a week or two, then agreed to stop "dating" and went back to normal. That was weird.<br />
<br />
I went to a group sleepover once and we played "truth or dare" at the hot tub. I took off my pants and my friend who was also a girl commented: "How Mastiff!" I felt proud of my penis that day, LOL. I stayed at her house often and it never occurred to me until my adult years, I might have had a chance with her. But she was the alpha female and dating a guy already. I'm not sure it crossed her mind either. She's one of the few that hung out with me even years after. Who knows what might have been.<br />
<i><br /></i>

The last notable event, I think, for this period was my introduction to Theater. I ran the left of house spotlight for the Brea City Theater's production of Bye Bye Birdie. I saw several very attractive women (some older and some same age) come out onto the stage in nothing but their panties and bras. I was in heaven! I knew theater was my calling.<br />
<h4>
Indio, CA (1996-2001):</h4>
We left Brea/Diamond Bar (Orange County) and I spent my Junior/Senior year at La Quinta High School, where I immediately enrolled in Theater. However, I was too shy for the front of house stuff, so I became a stage builder and eventually ran the soundboard. I fell in love with sound/audio there.<br />
<br />
The theater was full of boys and girls coming into puberty with raging hormones, and to top that off, we were all touchy/feely. Never a day went by without a long hug, sometimes a group cuddles, and I got asked out by my best male friend. I said no, but part of me didn't want to say no.<br />
<br />
Junior (or Senior?) year, I met JM, another blonde. We were introduced by her cousin and did splits competitions in my mom's minivan. This was my first sexual encounter post-puberty. It was exhilarating. I still remember her lips tasting like cherry, and... well she tasted really good everywhere else too. I don't recall much, just that I felt she was too clingy and I was feeling smothered, so I broke it off.<br />
<br />
Senior Year, my mom tells me her work friend has a girl my age that needs to learn guitar and that I should teach her; "but don't date her, she is not okay"... moth to a flame. She pressured me into having intercourse, I didn't want to, but she talked me into it (I was deathly afraid of babies). I got barely in when she suddenly changed her mind and got up without a word. Never did find out why she changed her mind. Probably the Holy Spirit protecting us from babies.<br />
<br />
<b>Grade-Night</b><br />
<br />
From Junior Year, I had met this one girl, EL, who captured my attention like no-one else ever had. But she was a "good girl". She'd never been kissed, parents were missionaries, and I was certain that she was too good for me. So we became best friends but I kept my distance. We never dated. On Grade-Night, we were all getting on the bus to Disneyland. She ran up and asked if she could sit next to me. We talked for an hour and she eventually fell asleep, head on my shoulders. That bus ride is to this day one of my favorite moments. It was one of the few times in my life I felt truly happy... it was short lived. She spent the evening bouncing between friends. I don't remember if we rode home together. I just remember I felt rejected most of the rest of the evening. I don't think I enjoyed a single moment of that night after the initial bus ride.<br />
<br />
<b>The Infamous 1999</b><br />
<br />
I came home (spring?) and my mom was in tears, told me my dad was doing Crack in the garage and wouldn't leave. By this time, we'd all had enough of him anyway. I walked in and calmly let him know "You have forfeited your right to be here. I am now the man of this house. You have twenty minutes to leave of your own recognizance or I will send you away in an ambulance." He nodded, said "Okay". I closed the door. About ten minutes later the garage door opened and closed. We didn't see him for months. He spent the rest of the next few years in and out of half-way houses.<br />
<br />
I think my friend DF was there with me that night? I don't know if we were dating yet.<br />
<br />
EL came over that week, she was prepping for her trip to Bible School in Austria for three months. She'd made me a box with a separate, decorated, folded note for each day she'd be gone... and told me to only open one each day. She'd hoped it would get me through the depression of the situation until she could be there for me when she got back.<br />
<br />
<i><note: a="" adult="" an="" and="" believed="" broken="" could="" didn="" friend="" gift="" her="" i="" in="" just="" like="" liked="" love="" loved="" me.="" me="" mind.="" never="" really="" she="" sign="" so="" someone="" t="" that="" this="" understand="" until="" was="" wasn=""></note:></i><br />
<br />
I did know, intuitively, that there was a connection. So when I later ended up dating and sleeping with two girls that summer and then told her, I had betrayed her trust and she never talked with me again, not really. We stayed friends but from a wide distance.<br />
<br />
This was the season I dated DF, and we got naked in the bed with another couple doing the same next to us. It was by far the most awkward encounter I'd experienced. I realized I didn't live up to what she'd hoped it would be and tried to make it up to her a few days later. She came over, took a shower with me, but then declined to have sex. She broke it off after that. Said I was too good for her, how's that for immediate irony? I then had sex with her next-door neighbor. Which made her mad.<br />
<br />
Now that was an interesting story because, until this moment in my life, all my encounters were oral sex (unless you count the almost in Senior Year, which I don't). My night with ML was the first time I had ever really had full intercourse. Did I mention she was ten years older? We never talked much after that, because she had other men in her life.<br />
<br />
<b>Then came 2000</b><br />
<br />
In 2000, I met a young Latina with a broken past... my type... BG. Her story is not mine to tell; however, she took my heart. Against all wise counsel, pastors, friends, and family, we eloped in Vegas and moved into my room at my Mom's house because we were too broke to actually get our own place. I immediately came down with Mono, a great way to start a marriage.<br />
<br />
After a year, we were having issues and tried the geographical cure and moved out to San Bernardino. That lasted about two months until she found another man and begged me to leave. <i>*She recalls it differently, but I'm certain that's how it happened. Anyway, this is my story.</i> I specifically recall the moment I was asking to make it work and she demanded I just go already. She even stayed at his house so I could move out without her being there.<br />
<br />
My friends came over to help me move out... which is a story I don't have time for.<br />
<br />
<b>January 2002</b><br />
<br />
By December 2001, I realized I needed to stop drinking. Not that I had been drinking to excess or anything like that. I just knew it was an issue in my family. I also knew I was hoping the alcohol would make me feel better. Having spent years with addicts, I knew that was called self-medicating, and I decided to stop. In January 2002, I walked into Alcoholics Anonymous (A.A.) where I met Big John.<br />
<br />
This is where I learned a valuable lesson about how Iron Sharpens Iron is a practical tool, not just a bumper sticker verse. Big John said:<br />
<blockquote class="tr_bq">
<i>"Darrell, you know the reason I like sponsoring people? Because when I have a thought, it sounds reasonable. When I say it out loud, it sounds questionable. But when I hear YOU say it, it sounds downright STUPID!"&nbsp;</i></blockquote>
<br />
<b>August 2002</b><br />
<br />
August 2002 was a huge month for my history.<br />
<br />
<ul>
<li>I finalized divorce papers with BG.&nbsp;</li>
<li>My brother, Devin, got mad that I broke up a fight between him and my youngest brother, Ryan, so he hit me so hard that I lost 24 hours of memory.&nbsp;</li>
<li>I drove to Fairchild Airforce Base, in Spokane Washington and visited Spokane and Coeur d'Alene (which would become my home in 2017). I planned to go into the United States Airforce.&nbsp;</li>
<li>On the way back to CA, I visited my friend's mom to drop off some things. I told her I had to run "gotta see about a girl" because I was on my way to Santa Barabra to see EL, my "just friend" at her college. This wise little Italian Prayer Warrior made me stay for the evening, despite my plans. She told me "The Airforce is the best thing that ever happened to my son... and you're not supposed to go. I hear you talking about service. You have a different calling/path to service and you need to pray about it". I never did end up going into the Airforce... I still wonder if I should have.&nbsp;</li>
<li>While visiting my (secret) high school crush in college, I met her Roommate, Flavia.&nbsp;</li>
</ul>
<div>
Flavia was a wild-hair, bubbly, artistic black girl... she had fabric hanging everywhere around her room, doorway, and even off her shoulders. She was a walking ray of color and sunshine. She had my interest by not my attention yet. I got her number so I could spy on my crush, her roommate.&nbsp;</div>
<br />
<br />
Then in Spring of 2003, God removed my desire for that high school crush by showing me the marriage it could become. It was awful. In part, looking back, I can see how ELs constant "jabs" and sarcasm would eat away at my confidence and how someone like me, someone desperate to be affirmed by a woman, would wither under her attention. I wonder, though, if a healed me could actually find that kind of relationship enjoyable... who knows.<br />
<br />
Not long after that revelation/vision, God told me "that roommate is your wife". I didn't believe him. But I called her again, this time not to spy on the EL but to get to know her. She was passionate about God in a way I'd never seen anyone be. She taught me the baptism of the Holy Spirit and it was through her teaching and prayers that I found it myself one day, in a truck, under the stars, by myself... when I called the next time I prayed with her in tongues, she encouraged me, and then I knew... on that call... I would marry her. I didn't tell her though.<br />
<br />
<b>Marriage Two</b><br />
<br />
At graduation, we walked, went to the Chapel and prayed together. Finally, I turned to her and said: "God told me you were my wife". She replied: "He told me the same thing". We talked more, but I don't remember the rest of the conversation. What I do know, is that is the only thing we ever really said about it. She moved from Santa Barabara to Long Beach, then later that summer, she moved to Indio with some of my female friends. We courted throughout the summer and fall and married on January 17th, 2004.<br />
<br />
The wedding, we both agree, was the worst day ever. Ha ha ha... it was forced, tensions were high, we fought on the way home from the reception and almost didn't enjoy... a normal wedding night... but we made up and kind of... I guess forced it.<br />
<br />
I wish I could say it got better... but it didn't. We both had triggers we didn't understand, we set each other off in ways neither of us understood.<br />
<br />
We had high and low points, like any marriage. Some of those years were really really really good... parts of them anyway... but much of the time was spent in a constant wondering "will it ever get better" on both sides.<br />
<br />
If marriage is meant to bring all of our wounds to the surface, face them, and heal through them, then marriage did in me what it was meant to do. Or... it started the process.&nbsp;<br />
<br />
<b>Fall 2016</b><br />
<br />
I hit my low point in Fall 2016. I decided to walk away from my family, church, God, and wife. I had an affair. I'm not proud of it. I have to write about it because it's part of my journey. My co-worker, who shall remain nameless for privacy, was getting an earful of my woes everyday. Finally, she said "why don't you get what you're missing on the side?" and with that, I walked into the trap.<br />
<br />
<b>Affair is too light a word, I betrayed my wife's trust and broke her heart.&nbsp;</b><br />
<br />
It lasted a few months. By the end, I was so far into the darkness I was planning my own suicide. I hoped to make it look like a robbery gone wrong so Flavia and the boys would get the Life Insurance money.<br />
<br />
I made two important life-saving, decisions at this time.<br />
<br />
<ol>
<li>Counseling: I started seeing a Christian Psychotherapist I already knew of and trusted explicitly. His works, available on his website and Facebook page had saved me thousands of times over. I told him it was my last-ditch efforts before I walked away forever.</li>
<ol>
<li><a href="https://bobhamp.com/videos/" target="_blank">BobHamp.com</a></li>
<li><a href="https://www.facebook.com/ThinkDifferentlyCounseling/videos/?ref=page_internal" target="_blank">Think Differently Counseling</a></li>
</ol>
<li>Men's Small Group: I tried other's, and they were plastic in my opinion. Too much teaching, not enough transparency without judgment.&nbsp; But Rudy's was different and I knew I could trust him. So I walked up to him after and said "I am going through darkness. I am going to walk away from God, church, family, my wife, all of it... but this is my last-ditch effort to see if God still wants me. I'll be here every Friday, and you have permission to hunt me down if I don't show up." And he did hunt me down throughout the week each week.&nbsp;</li>
</ol>
<br />
I didn't reconcile with my wife or stop the affair... but I did these two things. And they subtly worked their way into my spirit.<br />
<br />
<b>Jan 2017</b><br />
<br />
On January 6, 2017, I was in the kitchen with my soon-to-be ex-wife (so I thought). We were working out the details of our pending divorce. The affair was known. It was over.<br />
<b><br /></b>
<b>But God...&nbsp;</b><br />
<br />
As we talked, openly, about our individual struggles, she shared her struggles and dark desires. That she, too, was a pornography addict. That she had thoughts that weren't godly. In that moment... something melted inside my heart.<br />
<br />
There had always been two Darrell's. Sexual Darrell (evil, dark, must be bound and held at bay) and Spiritual Darrell (Bible student, teacher, and future pastor if I could ever really conquer the other guy). In this moment, hearing her share her struggles, the wall between these two men melted. For the first time in my life, I realized I didn't have to choose one. I could be both. I could be Sexual and Spiritual in one marital union.<br />
<br />
This resulted in our marriage/life motto: No Hiding<br />
<br />
<b>No Hiding </b>(or as Shelley puts it "<b>Bring it to the light so it gets handled right</b>") simply means that whatever you keep hidden, secret, struggle with alone silently, will become master over you. It will rule you. When you bring it to the light, its power is mitigated and eventually destroyed.<br />
<br />
This means that you cannot be isolated. Community is key. "No Man Is An Island", <a href="https://web.cs.dal.ca/~johnston/poetry/island.html" target="_blank">John Donne</a>.<br />
<br />
In my experience, this means having a group of men (or women if you are female) to speak openly with about what's in your heart, even the scary things you don't want to admit.<br />
<br />
It means having an open dialogue with your spouse (if you have one) where you are allowed to share freely with each other even the dark desires you'd never act on. The purpose of bringing these up isn't to convince him/her to do them; rather, to bring them to the light, expose them, and pray the blood of Jesus over them.<br />
<br />
It means having this attitude of No Hiding at all times, while also being sensitive to your audience.<br />
<br />
It means not hiding from even your children. My children will know, as they are old enough, what happened in my life so they can learn from those mistakes.<br />
<br />
<b>After...</b><br />
<br />
We left that job, sold our house, left North Texas and moved to North Idaho. I'll never know if this was a good or bad decision... but God has used it. I wish I could say it was all better after that...<br />
<br />
I continued to deal with darkness. A single moment of healing doesn't heal everything. God still uses process to deal with most things. Even in those dark moments, though, something profound had changed... I was ready to let God heal that other stuff too. That was new.<br />
<br />
We had more good times than bad, despite our confusion and questions... But we still weren't sure we'd stay married. We kept at it though, forcing ourselves to have open conversations. It was a struggle, and hard, but we were not going to hide anymore.<br />
<br />
One thing we'd do, when one of us looked upset and wasn't talking about it, is get the other person to look us in the eyes and say "No Hiding?"... that was an invitation, not a demand, for the other to bring it to the light so it could get handled right.<br />
<br />
<b>June 24, 2018-June 25, 2018</b><br />
<br />
On the evening of June 24, 2018, we had a great talk about the future. We talked about pursuing God's best. Forget what makes money, just do what you're passionate about and let God deal with Money. We cuddled on the couch and held hands. It was a sweet moment. She was seven weeks pregnant and laying on the couch most days and nights due to pain in her leg that wouldn't go away (<a href="http://www.darrellwolfe.com/2018/06/flavia-antoinette-wolfe-heres-what.html" target="_blank">more here</a>&nbsp;on that).<br />
<br />
At about 1:45 am, she woke me up "Darrell, my leg stopped hurting and now I'm dizzy, you need to take me to the hospital!" I jumped up, grabbed her at the bedroom doorway, and walked her through the living room... where she collapsed on the couch, face down... she died as the paramedics walked in. They tried to bring her back at the house and hospital... but she never came back.<br />
<br />
<b>Now...</b><br />
<br />
As of May, 2019... I'm a Widower. I haven't done this year right... but I survived. Now I'm looking at a season of singleness asking God "What now?" and I have no great answers. But God does... so I'm working it out day by day... sometimes hour by hour...<br />
<br />
I left our details... maybe I'll add them if they seem relevant... but this isn't about every mistake I've made, it's about the key moments in my history that led me to become this person who needs healing...<br />
<br />
I hope you benefited from reading my story, I benefited from writing it.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />