---
title: 'Hhmmm'
date: '2017-08-22T06:54:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1048811611414876684'
blogger_filename: '/2017/08/hhmmm.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<div dir="ltr">
The Dark Ages were primarily due to religion. When men were allowed to read the Bible for themselves, instead of being told what to believe by so-called leaders, they found a God of order. Therefore, the Earth created by this God would have order.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
This thought led to Newtonian Physics, printed books, engines, light bulbs, Einstein's theory of relativity...</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
All science, medical advancements, everything you drive, see, eat...</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
In short without men reading God's word for themselves, you'd be packing your mule cart to head to the nearest township,&nbsp; paying your tax to the king, and hoping to live to 40.&nbsp;</div>
<div dir="ltr">
<br />So if God is a God of order, why am I living in this crummy house, with a woman I'm not attracted to?</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
We live in a broken world. That means, things break. If my life isn't as ordered as I'd hoped it's either because I'm broken inside and causing the chaos; or, there are other broken things out there and I'm reacting to those broken things.&nbsp;</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Addiction is my cross to bear... weight is hers. We're broken people. But if we truly serve a God of order... a God who makes a way where there seems to be no way... Maybe that can change for both of us?</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Hmmm.....<br /></div>
