---
title: 'Darrell the Lost Boy'
date: '2017-12-07T03:10:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5915837620853195437'
blogger_filename: '/2017/12/darrell-lost-boy.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

I kind of stopped using this after Flavia felt like she had to "talk" after reading it, uhg.<br />
<br />
Let's just not, ok? That was entirely UN Productive.<br />
<br />
But I guess it's time again.<br />
<br />
I don't want to be alive. I'm not exactly looking to kill myself, but I'm not motivated to take care of myself either. A drunken drive off a tall bridge does have a certain appeal. Then again, I'm usually happier when I'm drunk, I'm probably less likely to do it then.<br />
<br />
I miss drinking.<br />
<br />
EVERYTHING bugs me.<br />
<br />
I have to put these thoughts out because they are rotating in my head so much I can't even focus. I can't write a novel or even clean the dishes without this rotating broken record.<br />
<br />
Sorry Flavia, but I have to get it out of my head, and you've proven that I can't say anything to you without starting a fight.<br />
<br />
<br />
<ul>
<li>Everything if a fucking mess all the time. It's like living with three pigs. Even trash and shit is all over the floor. I need a clean home. Not pristine, but fucking clean. Ordered. Not Chaotic.&nbsp;</li>
<li>We have too much fucking shit. I want to throw out HALF or more of what we own so I can par the place down to a manageable level.&nbsp;</li>
<li>The fridge, pantry, and kitchen are constantly full of stuff I'd never buy or eat. It's frustrating to have this much food and so little to eat.&nbsp;</li>
<li>These things contribute to the feeling like I need my own house, one where I can have things my way. I think this is where the idea "man cave" came from. I can't stand living here.</li>
<li>The kids argue, constantly. Shut the fuck up!</li>
<li>They "clean" I guess... but mostly they leave unwrapped food containers lying around, make quesadillas and leave the cheese on the table, spill chips and food particles all over the floor in the kitchen and living room and don't give it a second thought.&nbsp;</li>
<li><b>I'm no longer convinced&nbsp;that they are being raised in a healthy and productive manner or that homeschool in this environment is a good thing.&nbsp;</b></li>
<li>My wife is fat. Not just overweight. Somehow I'm supposed to be ok with that. I'm supposed to "want" a woman who is so overweight that there's nothing on any rack or shelf that fits her. A normal sized woman that got a little chubby is still attractive. My wife is not attractive. I have to try to look past her physical side to the person inside that I love to find the attraction, but we fight so much and she's so touchy that even that is hard to do.&nbsp;</li>
<li>I do find it, sometimes, but mostly with my eyes closed. There have been a few outfits recently that weren't half bad.</li>
<li>But I was embarrassed for her and myself at the Christmas party. I took a picture and it was just awful.</li>
<li>My awakening to her in January was mostly brought on by being able to talk about sex more openly. That's helped, but I still have a person who I perceive as nagging if I have a cigarette. Newsflash, I didn't quit for you, I quit because I can't hide it from your nose and I'm tired of fighting about it. If I had my own place I start again, instantly.&nbsp;</li>
<li>If I could go back in time, I'd get fixed as early as I could talk a doctor (in any country) to do it. I'd stay single, move transiently from person to person, place to place, and if I found a like-minded woman who wanted that lifestyle, maybe travel with her until we parted ways, but never marry.&nbsp;</li>
</ul>
<div>
<br /></div>
<div>
And yet........</div>
<div>
<br /></div>
<div>
<ul>
<li>There's a person inside the inside the inside of me that feels differently.&nbsp;</li>
<li>That person sees the before/after pictures of weight loss and says that maybe, underneath the big, there's an attractive woman I married under there. Maybe I could just love her enough to free that woman.&nbsp;</li>
<li>Maybe my kids aren't so bad, maybe even likable. Maybe I could get to know them, play games, not yell so much.&nbsp;</li>
<li>Maybe this house isn't the house from hell, maybe it's a blessing compared to the other choices we had when we got here.&nbsp;</li>
<li>Maybe if I'd been a better human being, I could have stayed a Technical Writer for Wells Fargo and worked remotely here, if I hadn't screwed it up by getting involved with a co-worker. A co-worker that is actually unattractive in her own right. Someone I would <b><i>never </i></b>pick out of a catalog but happened to be interested and new at the time.&nbsp;</li>
<li>Maybe I could find this other person inside of me, underneath two or more decades of growing bitterness against a God I don't understand..........&nbsp;</li>
</ul>
</div>
<br />
Someone tried to tell me that I should consider the prophet Hosea, and how God told him to marry a woman he didn't like. They said God doesn't always have "prosperity" or good times for his servants. That I should follow God even if he's asked me to have something other than what I want.<br />
<br />
My response: Thanks! I'm now MUCH LESS likely to follow God. Fuck that shit. Fuck his will. Fuck his plan. So far his plan SUCKS!<br />
<br />
Maybe not. Maybe there's some kind of a sweetness to following him into dark places, letting his light shine through me there, and seeing it changed because of it.<br />
<br />
Truth be told though, I'd rather be sent with a gun into a war zone with almost certain death than I would be sent to a small city to pastor an impoverished church and "trust God" to supply. That's much harder, and I just don't know if I have it in me, or ever will.<br />
<br />
I'm back full circle again. Not in the details, but in the theme. I'm not smoking, drinking, or having an affair this year... but I'm considering whether I have a place in this house/family.<br />
<br />
I'm thinking/feeling that they'd be better off without me. I can just send a check, and visit a few times a year. I don't know if my hanging around with all this bitterness isn't worse for them than my absence.<br />
<br />
If I'd just stayed at Wells Fargo and let them go, I could be living on 50% of my the income, which after moving to Salary would have been what I'm making NOW. I could have sent them $30K and kept $30K and still lived better than I live now.<br />
<br />
Oh well, can't go back, burned that bridge. Can't get a job like it, because apparently, my getting that job was a fluke, and I'm actually unhirable.<br />
<br />
I'm a fucking loser either way.<br />
<br />
Going to make food now... I guess I want to die, but not die of hunger.<br />
<br />
Darrell the Lost Boy<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />