---
title: 'Snow. Sick. Contemplative.'
date: '2017-12-18T07:40:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7065343111104584962'
blogger_filename: '/2017/12/snow-sick-contemplative.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Thought'
---

<p dir="ltr">It's snowed this weekend. Real snow. Unlike I've seen since I lived in Spearman Texas. </p>
<p dir="ltr">We made snowmen today. That was fun.</p>
<p dir="ltr">Yesterday JoAnn &amp; Rocky helped us get tires. I feel bad. If I hadn't been so broken, and messed up everything last year, maybe I could have stayed with WFDS working remotely here... Made the money I was making, or more.</p>
<p dir="ltr">But instead we came up in a hurry to run from everything and wasted the entire house sale proceeds and ended up in a starter job again... It's like all the work I did to rise up the ranks was erased and I'm back in 2006, starting over. </p>
<p dir="ltr">I'm still broken though. I'm like a dry drunk. I maybe don't DO anything I'm not supposed to... But I don't want it any less, maybe more? </p>
<p dir="ltr">Maybe this is just the detox and renew phase. Then again, if I'm not working on myself or renewing, am I getting better? Or regressing?</p>
<p dir="ltr">I'm such today. Common Cold. Haven't had that in years... Proof I'm slipping physically.</p>
<p dir="ltr">No men's groups that fit my needs... Should I start one, like Rudy did? More than half his guys weren't from it church anyway. </p>
<p dir="ltr">Something to consider, still.</p>
<p dir="ltr">I guess if God brought me one guy that wanted to meet, it would be a start?</p>
<p dir="ltr">Or do I start with the date/time/place before I get that one?</p>
<p dir="ltr">Like Rudy did?</p>
<p dir="ltr">Why am I here?<br>
Why in Idaho?<br>
Why on Earth?<br>
Why this family, marriage, why?</p>
<p dir="ltr">Generally, God doesn't seem to answer "Why?" questions. </p>
<p dir="ltr">He deals with action, and identity, but not why, typically. </p>
<p dir="ltr">Uhg...<br><br><br><br><br><br><br><br><br><br><br><br></p>
