---
title: '07/26/2017 -  Meh. Irritated. Depressed. Anxious. Wishing for more, dreading what I have.'
date: '2017-07-26T08:23:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2157261030370796851'
blogger_filename: '/2017/07/07262017-meh-irritated-depressed.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<h4>
<br />Meh. Irritated. Depressed. Anxious. Wishing for more, dreading what I have.</h4>
<br />
I'd been learning about an emotion wheel a while back, which allows you to find names for emotions and connect your left brain ability to describe your experience with your right brain ability to have an experience.<br />
<br />
These words describe me as of late:<br />
<br />
<br />
Meh. Irritated. Depressed. Anxious. Wishing for more, dreading what I have.<br />
<br />
I know it would hurt Flavia to know, but I must write it out if I'm to uncover lies, recover from this disorder. Flavia is you are reading, just stop now unless you REALLY much keep reading. But it will be hurtful and I don't mean it to be.<br />
<br />
On one hand, I see Flavia as a talented woman, artist, gifted Mom. She sees people and situations at the "heart" "emotional cause" level. She should be selling at art galleries and counseling troubled women, not working at Walmart for pennies.<br />
<br />
However, there's another side. This side never really goes away but it gets bigger or smaller with my emotional state.<br />
<br />
I view her as a stay-at-home mom; BUT, not a stay-at-home WIFE. She doesn't cook, barely cleans, and she's over 300 Lbs. I can work up an appetite to eat just about anything and I can work up an appetite to find her attractive... but the fact is that she is over 300 Lbs. I actually find looking at her painful without clothes on most of the time.<br />
<br />
In addition to that, her weight makes it so that she's constantly tired, irritated, hurt or in pain. She's not "active" in bed very often. It's almost like having sex with a blow-up&nbsp;doll. To make matters worse, she's so fat I can't even reach parts of her. I'd like to hold her in my arms while I'm inside and I can't, she's just TOO round. I can't reach both. I have to bury my head past layers and layers of fat to find her clit; which is why I don't lick it very often, it's just WAY too damn hard.<br />
<br />
Frankly, I'm not sanctified in my wants. I want what I had with Alison. I want to check out other women with Alie, maybe even toy with the idea of finding one we both like that would join us. I want a wildcat like her that will be an equal in bed. I want small hands, small feet, and small breasts.<br />
<br />
I hear guys get a shirt or article of clothing and say: "It's too small for me, I'll give it to my wife".<br />
<br />
I want to scream and tear through walls when I hear that. My wife's hands, feet, and body are three to four times my size. I could fit three of me in her pants.<br />
<br />
I told her I didn't want a sexless marriage at the start of this year. She said she wanted sex. We've talked about almost everything, and danced around this one big thing.<br />
<br />
It's not that I didn't want sex, I just didn't want it with you. I have almost no attraction to you sexually.<br />
<br />
I understand that this is partially a legitimate thing, fat girls just aren't attractive. But it's also partially an illegitimate thing, a result of miswired brain chemistry due to sexual addiction going back over 30 years.<br />
<br />
But I can't tell which is which, never could.<br />
<br />
I'm honestly content with the idea of getting my kicks outside of the marriage bed/house and coming home to fulfill my duties in the house/bed/husband/father.<br />
<br />
But I don't know if I can continue like (just her and me) this without some major chemical re-wiring or her loosing about 150 Lbs or more.<br />
<br />
I'm finding myself daily wishing I'd stayed with WFDS as a writer and with Alison. I'm willing to bet that she'd have eventually left her guy if I'd stayed (it fits her pattern and mine). But I didn't so she stayed with him. I hope they're happy, I'm not.<br />
<br />
God, I hate you. I love you and I hate you. It's like everything you've ever asked me to do is all work and no reward. I had a desire for a woman of my dreams and you gave me this. Then you didn't take the desire away. I hate your planet, your ways, your decision making, your instructions.<br />
<br />
I wish you'd just leave me alone, but you keep pursuing me. Part of me hears a passionate lover in pursuit in you. Part of me hears a Tyrannt Bully. I'm not even sure if you are real anymore, or if I'm just such a good storyteller that I made you (and all our talks) up. Sometimes I think I hear you and it works out like it was you. Other times I think I hear you and I'm totally off my rocker. Are you even there? How the fuck am I supposed to know?<br />
<br />
Get off your lazy ass and get down here and talk to me or let me come up there. This spooky "impression" and "feeling" bullshit isn't cutting it anymore.<br />
<br />
Whatever!