---
title: 'Processing: My thoughts and notes from October 2016 - March 2017'
date: '2017-03-01T22:38:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6077462595325817157'
blogger_filename: '/2017/03/processing-my-thoughts-and-notes-from.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<br>
This is my random selection of notes from the past 6 months I wanted to preserve:<br>
<br>
When I hear Flavia say: "I'm proud of you" or "I care about you" it gives me a warm/comfort feeling. "Awwww..."<br>
<br>
When my Mom is in town, and she does that kissy kissy thing, I feel uncomfortable, irritated, agitated, run, hide, defend, protect, walls, cold.... not sure why.<br>
<br>
I was afraid to hear God, he might tell me to do more things I'd hate him for... which would only make it worse, in my mind.<br>
<br>
I told Flavia (according to her memory of the past):<br>
<br>
<ul>
<li>Bypass my mind.</li>
<li>Call it sex, not making love.&nbsp;</li>
</ul>
<div>
<br></div>
<div>
When my kids say to Flavia: "Daddy said we could do xyz,&nbsp;is that ok?" it invalidates my need to be present. I also feel like my default answers are broken.</div>
<div>
<br></div>
<div>
Flavia left me a voicemail: "I hope you went on a walk and not to smoke" I felt irritated and controlled and suffocated. But she felt unheard and uncared for and was trying to protect her children who wanted to be with Daddy.&nbsp;</div>
<br>
<br>
Why does my Mom irritate me?<br>
<br>
Trust God VS Wants/Desires: Why is it so hard to align these two?<br>
<br>
Feeling without chemicals is torture.<br>
<br>
Flavia and God are tied, I cannot heal with one and not the other.<br>
<br>
<blockquote class="tr_bq">
In late December, I heard: "You are going to leave her (the other woman) and go back to your marriage. It's winter now." Bob said that was interesting, I thought it was impossible.&nbsp;</blockquote>
Look up: <a href="https://www.youtube.com/watch?v=n3exJAalbIU" target="_blank">Jimmy Evans Spiritual Winter</a><br>
<br>
Thought: <b>Porn equals "her".</b> She's a magical her. She's an idea or ideology in my own mind. I've looked for "her" since I was young (five?). She's beautiful, intelligent, magical, spiritual, and she's a vision of perfection that does not exist in any real woman. She's an illusion. She prevents me from seeing the gifts in front of me.<br>
<br>
<b>Winterized Trees: If a tree gets a proper winter, it will destroy pests and produce sweeter fruit.</b><br>
<br>
<ol>
<li><b>Kills the bugs that would endanger the harvest?</b></li>
</ol>
<br>
<b><br></b>
<br>
Sometimes you find it easier to communicate with certain people because you are <b>Broken in the same way</b>.<br>
<br>
If you are broken in the same way, you have a lower chance of providing the missing things needed to fix each other.<br>
<br>
Communication gets what is in the heart, out. Sex is a form of communication. Connect to "out there".<br>
<br>
Emotions exist via communication (needs words).<br>
<br>
<b>Shame Filters</b><br>
<br>
If sex and love are separate inside of you, can you access both of them at the same time?<br>
<br>
Faith is not faith until you hear. Don't just listen for what you want to hear, listen for what he wants to say/talk about.<br>
<br>
"Lord, Father, Holy Spirit, What are you saying/doing right now?"<br>
<br>
<br>
<b>I think I heard God say: 12/19/16</b><br>
God: Ask me. Ask me for that Mitchell Guitar.<br>
Me: Lord, Father, I ask you for that Mitchell Guitar.<br>
God: "And the picks, strap, case."<br>
Me: "Yes Lord, the picks, straps, and case too. I receive it, thank you for it, it's mine, I have it, amen."<br>
<br>
<br>
<blockquote class="tr_bq">
<b>12/19/16: What are you saying right now?<br>"There's a hurting, confused, and scared woman out there in the other room. She doesn't know what to do, she doesn't want to lose you, but she can't reach you. You've made yourself inaccessible with walls too high for her to climb. Other's walk through the door because you opened it to them, let her in."</b></blockquote>
<br>
Sometimes, I can see my happily married with my family. But when I go home it is not my reality. There is a constant need, an itch, to do something else, anything else.<br>
<br>
Freedom, in my mind, still looks like an apartment by myself. Visitors but no co-occupants.<br>
<br>
<b>What is my way of knowing? What is a big lie that I believe?</b><br>
<br>
Prayer, worship, bible reading are scratching the end of the new limb; not things to do to be better or know more knowledge of good.<br>
<br>
Intuition does not equal emotion<br>
<br>
Quantify/Predictable Outcomes<br>
Right Brain: Experiences but no description<br>
Left Brain: Describe experiences we're not having.<br>
<br>
Brain= Mechanism/Engine<br>
Emotions= Fuel/Intensity/Steam<br>
<br>
<a href="https://www.youtube.com/watch?v=oiJWwWP1g7w" target="_blank">Big Yellow Taxi - Amy Grant</a><br>
<br>
<a href="https://www.youtube.com/watch?v=zPe2HSsk0k0" target="_blank">Rise of the Guardians- What's your center scene</a><br>
<div>
<br></div>
Archetypes: Structures of story that remind of spiritual truths.<br>
<br>
<br>
OCD: Brain arranges things, it's job. But it does it too much. Fueled by emotions.<br>
<br>
When the fuel inside gets out of control, the brain tries to manage the outside world.<br>
<br>
Center? What are you without controls? What is my center?<br>
<br>
Control keeps me wound up and keeps the real me hidden under layers.<br>
<br>
The brain's job is to filter and organize.<br>
<br>
In the OCD, the brain is over-organizing. Emotions feel out of control, so the brain attempts to box and contain and suppress to maintain control. (Like every color and picture in a room, versus only seeing the angry lion).<br>
<br>
The reason the parable of the acrobat resonates with everyone is that it speaks to structures or archetypes that are hard-wired into all of us.<br>
<br>
There are ways of knowing that are not left brain logic driven. Intution is a way of knowing.<br>
<br>
You've managed to control your way into a safe position at work but home still feels out of control.<br>
<br>
Do you want to fix it? Is it broken?<br>
<br>
How's that working for you?<br>
<br>
Roller Costers: Predictable / No Risk<br>
Skateboard: Not Predictable / Risk<br>
<br>
Responsibility = Fear Mom made me responsible for everything so I run from that. Church (pastor's kid) made me responsible for everything, so I run from that.<br>
<br>
I don't want to be responsible for anything. Even making a decision about menu items brings fear of losing out on other options.<br>
<br>
Result: Let someone else make the choice:<br>
<br>
<ul>
<li>Where to eat</li>
<li>Where to live</li>
<li>How to raise kids</li>
<li>To leave or stay in a relationship</li>
<li>Etc....</li>
<li>Control</li>
<li>Mitigate Risks</li>
<li>Predictable Outcomes</li>
</ul>
<div>
Love cannot be predictable or quantified. It is intuited.</div>
<div>
<br></div>
<div>
Faith is an intuitive response to a person not a quantifiable magic formula with predictable outcomes.</div>
<div>
<br></div>
<div>
Real Responses to a real Holy Spirit means you will get it wrong sometimes, especially in the beginning.&nbsp;</div>
<div>
<br></div>
<blockquote class="tr_bq">
<b>Lord, I tried what I thought you said. It didn't turn out so well. I'm afraid to listen, I'm afraid of what you'll say. I'm afraid I'll do it and it won't turn out so well either. I appreciate them in certain ways, but I don't love my wife and kids like you do. Nor do I see them as assets adding to my life. They upset the desire to control outcomes. I need you to help me see. Give me your sight to see them your way. Make my picture of Freedom look like yours. DW 12/22/16.</b></blockquote>
<div>
<b><br></b></div>
<div>
Men Need = A woman to be prouf of me.</div>
<div>
Women Need = A man she is proud of to love and cherish her.</div>
<div>
<br></div>
<div>
A man with a beautiful mind who cannot master his heart is no man but a child. An intelligent child.</div>
<div>
<br></div>
<div>
Father, how do you see me?</div>
<blockquote class="tr_bq">
I like mornings....</blockquote>
<blockquote class="tr_bq">
Seek me 1st, every morning. Until the decision becomes clear. Get Up Early. If you fail one morning, ok, just do it again the next morning. If I wake you up, get up. Don't check to see what time it is, just check your heart and get up. Scratch that new limb with me.</blockquote>
<div>
Dear God,</div>
<div>
<br></div>
<div>
I feel like a dog that has been abused and flinches every time the owner moves. At the time of a conversation, I'll listen to all her reason why I misunderstood everything, she did everything right, and 100% of the blame is mine. Then I come to be alone with my thoughts and reboot and I argue with her in my head. The truth is, I know I'm broken. Everything she says makes sense. My perceptions were wrong and irrational. But if I'm wrong, 100% of the time, why am I still here? I'm never going to feel validated here. My feelings may be based on misunderstandings but I' still feel them. Please kill me... DW Dec 2016</div>
<div>
<br></div>
<div style="text-align: center;">
<b>******************************</b></div>
<div style="text-align: center;">
<br></div>
<div>
<b>Friday 01/06/2017</b></div>
<div>
<b><br></b></div>
<div>
<b>I was having an affair and it came out this week. Flavia felt led to ask and I told her the truth. That was followed by a day of apartment hunting between tasks. I drove by last night, it's run down but it would do fine.</b></div>
<div>
<b><br></b></div>
<div>
<b>Then today, Flavia picked me up at work but stood outside the car in the snow. She refused to turn over the keys or let me in the car. I drove home planning to move out.</b></div>
<div>
<b><br></b></div>
<div>
<b>Enter Change</b></div>
<div>
<b><br></b></div>
<div>
<b>When we got home, she sat in the kitchen and we talked openly about our struggles and kept to our own side of the fence. During that talk, she admitted to sexual ideas, fantasies, and thoughts that made me totally re-think everything that's happened the last 14 years.&nbsp;</b></div>
<div>
<b><br></b></div>
<div>
<b>It was like floodgates. This one area of my life was dark, dirty, secret, wrong, things I couldn't talk to her about. She wouldn't understand.&nbsp;</b></div>
<div>
<b><br></b></div>
<div>
<b>As it turns out, her thoughts and mine were in perfect alignment. I wanted HER for the first time in years. Maybe ever. It unlocked the key to my heart, letting her in, but setting me free in the process. The shame wall that I used to keep that part of myself hidden and under control, melted and disappeared. The two people I thought I was (spiritual vs sexual) were melded into one person again, for the first time since 5 years old.</b></div>
<div>
<b><br></b></div>
<div>
<b>I think I'm in love with my wife for the first time.</b></div>
<div>
<b><br></b></div>
<div>
<b>Darrell 01/06/2017</b></div>
<div>
<br></div>
<div style="text-align: center;">
****************************</div>
<div>
<br></div>
<div>
<br></div>
<div>
Rudy's Men's Meeting: 01/20/2017: Thank you for forgiving me. I don't know why you chose to use me, but what's my next assignment?&nbsp;</div>
<div>
<br></div>
<div>
<div style="text-align: center;">
****************************</div>
</div>
<div>
<br></div>
<div>
<br></div>
<div>
NFW - 01/22/2017</div>
<div>
Repent= Change your mind. About what the Kingdom of God is, how it's accessed, and what it means for me today.</div>
<div>
<br></div>
<div>
Luke 17:20 No Observation - Within you now.</div>
<div>
<br></div>
<div>
<br></div>
<div>
<div>
<div style="text-align: center;">
****************************</div>
</div>
</div>
<div>
<br></div>
<div>
01/27/2017 Rudy's Meeting</div>
<div>
Satan knows you by your name and calls you out by your sin.</div>
<div>
God knows your sin but calls you out by your name.</div>
<div>
Let not love foresake you.</div>
<div>
<div>
<div style="text-align: center;">
<br></div>
</div>
</div>
<div style="text-align: center;">
<div style="text-align: start;">
<div style="text-align: center;">
****************************</div>
<div style="text-align: center;">
<br></div>
</div>
<div style="text-align: start;">
Two teachings by Bob Hamp:</div>
<div style="text-align: start;">
<ul>
<li>Catch the Fire: DFW True Authority</li>
<li>Overcoming Life Patterns</li>
</ul>
</div>
</div>
<div>
Internal locas of control vs External local of control.</div>
<div>
<br></div>
<div>
I know who I am and what I'm responsible for.</div>
<div>
<br></div>
<div>
Struggle repeats into relationship patterns.</div>
<div>
<br></div>
<div>
Not dealing with the problem but the symptoms of the problems created by the solutions.</div>
<div>
<br></div>
<div>
What other things, people, or circumstances are you dealing with?</div>
<div>
<br></div>
<div>
When one person in a family has a problem the whole family has that problem.</div>
<br>
<br>
<div style="text-align: center;">
****************************</div>
<div>
Covert / Overt communication:</div>
<div>
<br></div>
<div>
Overt is Data/Details/Facts</div>
<div>
Covert is Relationship, Inferences, Meaning, Interpretation, Implication.</div>
<div>
<br></div>
<div>
<b>Take the Covert and make it Overt. If someone says something that "hurts" just say it back to them the way you heard it and ask them if that's what they are saying.</b></div>
<br>
<div style="text-align: center;">
Perspective: Our story is part of a bigger story.</div>
<div>
<br></div>
<div>
Opposite of depression is Expression.&nbsp;</div>
<div>
<br></div>
<div>
Satan is not trying to get you to do bad, just do anything but be you.</div>
<div>
<br></div>
<div>
<b>Communication Tool: Make it specific to a temporary action and it's affect (not a permanent or person based thing).</b></div>
<div>
<b><br></b></div>
<div>
<b>When you ____ I feel / I hear _____</b></div>
<div>
<br></div>
<div>
Emotional Vocabulary.</div>
<div>
<b><br></b></div>
<b>Conflict Tool:&nbsp;</b><br>
<br>
<ol>
<li><b>Own it: What did I do? What should I have done?</b></li>
<li><b>What must it have been like to have that experience (in the other persons' shoes)?</b></li>
<li><b>Compassion/Empathy based response. I'm sorry... In the future, I'll do....</b></li>
</ol>
<br>
<br>
<br>
<br>
<br>
<div style="text-align: center;">
****************************</div>
<div>
<br></div>
<br>
<br>
<a href="https://www.youtube.com/watch?v=O4PJSYngv6k" target="_blank">When the devil has nothing in you, there's no access point.</a><br>
<br>
<br>
<br>
<div style="text-align: center;">
****************************</div>
<div>
<br></div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>