---
title: '08/13/2017 - I can''t take it anymore'
date: '2017-08-13T22:43:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5758161104132618080'
blogger_filename: '/2017/08/08132017-i-cant-take-it-anymore.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

I feel like I can't take it anymore...<br />
<br />
There are so many young, THIN, beautiful girls out there. I could be working my way through them now. Instead, I'm here in this house, working to support a family I don't want. Kids that annoy me. A wife &nbsp;I don't want.<br />
<br />
She's fat, really fat, like I have to REALLY try hard to find something attractive about her fat. I want to be attracted to her, but she's done nothing in 13+ years to help.<br />
<br />
She got a night job and sleeps all day now. The trouble is, I don't notice any difference. The kids aren't any more/less educated, the house is the same level of clean, I have to do the same things. I have NO IDEA what we're doing here.<br />
<br />
"Stay at Home Wife"? No. More like stay at home mother of kids I didn't want whose fat and lazy and does nothing that benefits me in any way.<br />
<br />
I'm sorry, but I miss Alison. I miss her tiny feet, tiny hands, small body, I could pick her up and hold her against a wall. I could bring her to climax in less than 120 seconds and keep her there until my hands wore out. It was awesome. Sex with Alison was everything I'd always hoped it could be. No other girl was like her.<br />
<br />
I miss her. But I still wouldn't have been "loyal" to her either. I wanted more variety. I want a new girl, often. I'd have probably used her a "regular" though. She'd have used me the same way. Something akin to the Doc Holiday and his lady from the movie "Tombstone".<br />
<br />
I wish I could be a "good boy" and just want my wife. I wish I could want God and church, and whatever I'm supposed to want...<br />
<br />
I just don't still.<br />
<br />
I had a short lived renewing of my interest in Flavia when I thought she could be what I wanted... But after we got to Idaho I learned that she just never will be. She's always going to be hard to communicate with, fat, lazy... a great mom and terrible wife.<br />
<br />
I wish I could put a gun to my head and pull the trigger to get out of this life, but I can't. SO I'm here. God is no-where to be seen, as usual.<br />
<br />
Fuck, I need a cigarette and a whiskey.<br />
<br />
D<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
