---
title: 'Dear Flavia: We Miss You'
date: '2018-06-28T14:30:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7396664626482316435'
blogger_filename: '/2018/06/dear-flavia-we-miss-you.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Flavia'
---

My update from yesterday:<br />
<br />
We got out of the house today. We hiked Tubbs Hill. Preston was enjoying himself until the last quarter. Then he broke down sobbing. He said: "I kept looking back, expecting to see mommy coming around the corner." My heart breaks for him. I said: "Me too buddy, me too." And just held him.<br />
<br />
Then we went to Panda, his favorite place to eat. I was ordering his and mine and kept thinking... "Who's order am I forgetting? Do we have everyone? I know I'm forgetting someone's order... Then it hit me. It was Flavia Wolfe. I was ingrained to have hers too."<br />
<br />
Thanks to Michael Wolsten for meeting us and paying for dinner. The gift card will help Preston get more if his favorite place.<br />
<br />
It was a relaxed day, lots of laughs and stories. But I'm crying now that I'm at home... Doing bills with an Excel Budget sheet I made especially for Flavia.<br />
<br />
*Sigh*<br />
<br />
<div style="text-align: center;">
***</div>
<div style="text-align: left;">
Dear Flavia,</div>
<div style="text-align: left;">
<br /></div>
<div style="text-align: left;">
The boys are going to be okay. I'm partnering with both of our mom's to make sure of it. I don't know about school. Your mom can't stop working to homeschool them. And they need the guidance of intelligent teachers, especially Connor in the areas of Science and Technology.</div>
<div style="text-align: left;">
<br /></div>
<div style="text-align: left;">
When we left your side Monday, Connor said he was going to build technology to bring you back, but I redirected him toward preventing this in others' lives. Preston said he's going to become a doctor so he can be a better doctor and prevent this in other's lives.</div>
<div style="text-align: left;">
<br /></div>
<div style="text-align: left;">
They both miss you, obviously, but you know Preston is taking this hard. How could this happen?&nbsp;</div>
<div style="text-align: left;">
<br /></div>
<div style="text-align: left;">
You'd be proud of me, or mad that I didn't take over years ago, but I managed to do bills last night without having a panic attack.&nbsp;</div>
<div style="text-align: left;">
<br /></div>
<div style="text-align: left;">
Yesterday, I realized that your anointing to mother was passed to be as a mantle. I'm knowing, seeing, etc., in ways I hadn't before. I'm seeing the boys through your eyes, interpreting situations accurately. I'll still make mistakes, but thanks for passing me the gift on your way out.</div>
<div style="text-align: left;">
<br /></div>
<div style="text-align: left;">
This just can't be happening. You're going to come back, right? Like, you'll just get up off the table healed? I know Jesus raised Lazurus after he'd already been embalmed. Can't we do the same? Even as I say it, I know I don't have the faith for it.</div>
<div style="text-align: left;">
<br /></div>
<div style="text-align: left;">
That morning, in the ER, Connor said: "Can't we get Kenneth Copeland or another pastor to come to raise her from the dead?"&nbsp; ...&nbsp; "We agreed and she died anyway. The Bible&nbsp;must not be true, it's all a lie."</div>
<div style="text-align: left;">
<br /></div>
<div style="text-align: left;">
How am I supposed to answer that?</div>
<div style="text-align: left;">
<br /></div>
<div style="text-align: left;">
*Sigh*</div>
<br />
<br />
<br />