---
title: 'Lessons In Grief'
date: '2018-06-25T08:30:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3179527424487959373'
blogger_filename: '/2018/06/lessons-in-grief.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Flavia'
  - 'Grief'
  - 'Freedom Recovery (Kairos AA'
---

Lessons In Grief - Things to help the grieving and their network<br />
<br />
It occurs to me, as I'm a few days into the worst tragedy&nbsp;I've ever experienced, that I could use this time to note what helped and didn't, then share it with others. So often we don't know what to say or do, or how to help, and maybe this will provide some insight in the future to myself when I minister to others... and to others who need guidance.<br />
<br />
The Lessons (in random order as they occur to me):<br />
<br />
Pokemon Package: One for two kids, or me?<br />
<br />
Food: It was great to have, but then it was too much, gift cards are great!<br />
<br />
Sadness and Laughter are both okay: You'll laugh when you didn't expect you would, you'll be hit with the sudden realization she's gone from the oddest things. Like grocery shopping, or ordering take-out.<br />
<br />
<br />