---
title: 'Dear Flavia: Why?'
date: '2018-06-27T10:59:00.0060000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4068381403360550674'
blogger_filename: '/2018/06/dear-flavia-why.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Flavia'
---

Flavia,<br />
<br />
We had our problems, more than most I think. But we'd finally come together last year. Although it wasn't perfect, although there was still pain and growth, we were getting there. We were confused, but we were making it.<br />
<br />
Sunday night, I told you to stop stressing, don't worry about making bread to sell, just focus on your talents. I said, "you are an artist, that's your wheelhouse". You never got around to doing much real art... you were always crafting to sell, make money, etc.<br />
<br />
You thanked me for reassuring you on that. We watched TV on the couch, you sent me to bed to get sleep so I could set up the car for Uber.<br />
<br />
Holy Fuck?! What the hell? You died that night. How could you just leave? Why didn't you fight to stay in the body? I know you were hurting, I caused most of it, but really? You couldn't stay for the boys? You KNOW they need you more than me!<br />
<br />
I'm sad, devastated, angry, confused...<br />
<br />
How could this happen? What could I have done to prevent this? I feel guilty because part of me, literally, asked for this (although I was thinking divorce or me dying at the time). I wanted to go. I've been asking to leave earth since I was TEN. YOU were the one who loved life. How could you leave me here with the boys?<br />
<br />
They'd have been sad to loose me, but loosing you is beyond words.<br />
<br />
I have no idea what to do now... I guess I have to stop playing parent, man-up, and be the parent you trained me to be... lol...<br />
<br />
I don't know if you can read these in heaven, but it feels good to write to you. My God, how could this happen?<br />
<br />
http://www.darrellwolfe.com/2018/06/flavia-antoinette-wolfe-heres-what.html<br />
<br />
<br />