---
title: 'Draft -- Eulogy Page'
date: '2018-06-28T15:14:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4145401633231676848'
blogger_filename: '/2018/06/draft-eulogy-page.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

Draft -- Eulogy Page<br />
<br />
Flavia Antoinette Wolfe passed away on 06/25/2018. For detail on what happened, click here. She leaves behind a Husband (Darrell Wolfe 37), Two Sons (Connor Wolfe 13, Preston Wolfe 10), a Mother and Father (JoAnn &amp; Rocky Sutherland), a Mother In Love (Debbie Tweedy), and a host of friends and family that loved her.<br />
<br />
<br />
<br />
<br />
<b>Links:</b><br />
<br />
<ul>
<li>Flavia's Facebook Page</li>
<li>Darrell's Facebook Page(s) Self &amp; Joint</li>
<li>Explanation of What Happened</li>
<li><a href="https://www.gofundme.com/flavia-wolfe-memorial-fund?teamInvite=fG3YEqhDKkCmqiGqDZTUVN8iCXWDvlLNeRkjqJTAL4eRqdGaU7QhFAheAGk7ar6V" target="_blank">GoFundMe</a></li>
<li><a href="https://photos.app.goo.gl/t2QPRtHa7VbJezbi8" target="_blank">Memorial Photo Album</a></li>
</ul>
<br />
<br />
<br />
<b>Service:</b><br />
<br />
There will be a memorial service held for those of us who remain so we can celebrate her life and influence.<br />
<br />
Date:<br />
Time:<br />
Location:<br />
<br />
<br />
<br />
<br />
<b>Shared Photo Album:</b><br />
<br />
I created a Google Photos album,&nbsp;<a href="https://photos.app.goo.gl/t2QPRtHa7VbJezbi8" target="_blank">! Flavia Wolfe (link here)</a>, so that I could share photos of her. I'll add more over time. I made it shareable so other's could add their photos.<br />
<br />
If the link doesn't work, paste this into your browser:<br />
<br />
https://photos.app.goo.gl/t2QPRtHa7VbJezbi8<br />
<br />
<br />
<br />
<br />
<b>Getting Involved:</b><br />
<br />
So many people want to help in some way. It's hard because there's only so many grocery deliveries&nbsp;or meals we can take before it ends up going to waste.<br />
<br />
<b>(1) Monetary Donations:</b><br />
<br />
We set up a <a href="https://www.gofundme.com/flavia-wolfe-memorial-fund?teamInvite=fG3YEqhDKkCmqiGqDZTUVN8iCXWDvlLNeRkjqJTAL4eRqdGaU7QhFAheAGk7ar6V" target="_blank">GoFundMe (link here)</a> campaign in her name. The funds will be used for several things:<br />
<br />
<ul>
<li>Medical &amp; Final Expense Costs</li>
<li>Bills, Debts, and Unexpected Items</li>
<li>Anything left over will go toward things the kids need over the next few years and maybe college accounts.</li>
</ul>
<br />
If the link doesn't work, paste this into your browser:<br />
<br />
https://www.gofundme.com/flavia-wolfe-memorial-fund?teamInvite=fG3YEqhDKkCmqiGqDZTUVN8iCXWDvlLNeRkjqJTAL4eRqdGaU7QhFAheAGk7ar6V<br />
<br />
<div>
<br /></div>
<div>
<b>(2) Other Needs:</b></div>
<div>
<br /></div>
<div>
Some would like to do something more than giving money. I'm going to list the random things we either need or would be helpful or just random things we talk about to give ideas. By no means should anyone feel like these are all needs, they're just things that come up in conversation and I've been asked to share no matter how random.</div>
<div>
<ul>
<li><b>Clothes</b>: She always handled this and we were just talking about how the boys outgrew everything in a sudden growth spurt this year.</li>
</ul>
<ul><ul>
<li><b>Connor</b>: Size TBA</li>
<ul>
<li>He's always been a preppy kid.&nbsp;</li>
<li>Shoes &amp; Hiking Boots: Size TBA</li>
<ul></ul>
<li>Jeans</li>
<li>Sweats / Night Pants</li>
<li>T-Shirts</li>
<li>Summer Evening Sweaters</li>
<li>Winter Jackets</li>
<li>Anything with Batman or Pokemon</li>
</ul>
</ul>
</ul>
<ul><ul>
<li><b>Preston</b>: Size TBA</li>
<ul>
<li>He's sensitive to fabric&nbsp;feel. He needs things that are soft, smooth, loose fitting.</li>
<li>Shoes &amp; Hiking Boots: Size TBA</li>
<li>Jeans</li>
<li>Athletic Wear</li>
<li>Sweats / Night Pants</li>
<li>T-Shirts</li>
<li>Summer Evening Sweaters</li>
<li>Winter Jackets</li>
<li>Anything with Batman or Pokemon</li>
</ul>
</ul>
<li>x</li>
<li>x</li>
<li>x</li>
<li>x</li>
<li><b>A Nintendo Switch (*2)</b>: This is a costly item, but I'll throw it out there. This was on our list to get and play together before she left. They now want two of them because I guess it turns into a hand-held? They wanted to play some new Mario game on there and the new Pokemon.</li>
</ul>
<ul>
<li>x</li>
<li>x</li>
<li>x</li>
<li>x</li>
<li>x</li>
<li>x</li>
</ul>
<ul><ul><ul><ul></ul>
</ul>
</ul>
</ul>
</div>
<div>
<br /></div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />