---
title: 'Hmmm... 7/13/18'
date: '2018-07-14T06:36:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2741651197645007951'
blogger_filename: '/2018/07/hmmm-71318.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<p dir="ltr">I'm submitting this to my private journal, hopefully nobody sees this for many years.</p>
<p dir="ltr">I've met a lot of friends the past few weeks. Some new, some old. Some good influences, some not so much.</p>
<p dir="ltr">But one stands out far and above the rest... And it scares me to no end.</p>
<p dir="ltr">J.A. as she'll be known for now... Has got my attention. I just can't be 100% sure it's of God... Not at this stage or in this frame of mind. </p>
<p dir="ltr">I felt like this was wife number three, and final. </p>
<p dir="ltr">It can't be though, can it? Can God tell you who your next wife is to be only three weeks after your last wife, that God gave you, left earth?</p>
<p dir="ltr">And she's only 26, 12 years younger.</p>
<p dir="ltr">And she's already been so hurt... I could make that worse.</p>
<p dir="ltr">And I can't get married again, ever, can I? I've already screwed up two marriages... Barely held on to and fixed the last one at the end. </p>
<p dir="ltr">Wouldn't I be betraying everything about Flavia if I married again?</p>
<p dir="ltr">But...</p>
<p dir="ltr">She is so full of the Spirit of God. Maybe that's what I'm attracted to, it's the anointing on her, not her... Right?</p>
<p dir="ltr">But... She speaks with such clarity in the spirit... We've run in the same circles... She's the kind of warrior I'd need at my side if I'm ever to see anything that's in my heart to do come to pass... And her voice, and her eyes... </p>
<p dir="ltr">Dear God, this must be that crazy brain they talk about in grief circles.</p>
<p dir="ltr">It can't be God. It can't be... Yet... There's something... Something I can't put I to words... Something illogical and totally non-sexual, and yet I'm attracted to her physically but it's not a simple physical attraction. </p>
<p dir="ltr">I could seek a pair of warm arms, I've been doing that... To no avail... But that's not this... </p>
<p dir="ltr">I feel like I could just lay everything I've struggled with aside and work on me for a few years until the timing was right... </p>
<p dir="ltr">But what am I saying? This can't be.</p>
<p dir="ltr">Yet I felt I heard God say; "The time is short, we can't wait long as we used to. You can partner together to usher in the kingdom of God..." Or something like that... I could say it in tongues...</p>
<p dir="ltr">Am I crazy? Delusional? Desperate for something that's not there?</p>
<p dir="ltr">Time will tell... I've laid it on God and his will and his timing. After I've had time to find out who whole Darrell is, we can look back and see if this was crazy...</p>
<p dir="ltr"><u>D</u><br></p>
<p dir="ltr">Update: the next morning. I had to be just crazy. It was the anointing I was attracted to. It was that she reminded me of Flavias spirit when I first met her. It was that she's a type of the woman I may someday marry... Still... I woke up with her on my mind. </p>
<p dir="ltr">And I deleted all my profiles on sites such as Ashley Madison. And I tossed my cigarettes last night.</p>
<p dir="ltr">Hm...<br>
</p>
