---
title: 'Word of the Lord 04/06/2019'
date: '2019-04-07T07:04:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7752211589299222168'
blogger_filename: '/2019/04/word-of-lord-04062019.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">
<div class="MsoNormal">
You see (a friend on Facebook) traveling executive class, touring the world… Do you see him as more valuable than you? Is your value based on what you do; or, who you are?<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Prophets, generally, are not kings. They are supported financially by those who believe in their calling and mission; or, in some special cases by miracles (ravens, widows). Kings hold the wealth and “authority” of nations in their hands.   Yet… <b><u>who turns a nation</u></b>? A King? Sometimes… but even then a king with a prophet in his ear! Pharaoh held the wealth and power but they were useless to him. Joseph wielded the wealth and power of Pharaoh by his prophetic gifting and submission   to authority.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
ONLY when you are willing, able, and have demonstrated genuine submission to authority, can I trust you to wield the power and wealth of others through your  <b>Prophetic Gift</b>. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Until now, you have been a teacher but aimless and wandering. As your teaching is surrendered to the Prophetic, secondary to it, you will experience new insight and authority and power and yes… wealth.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Submission 1<sup>st</sup> &gt; Prophetic Gift &gt; Then Power &gt; Wealth<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Selah<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Word/Prayer/Darrell Wolfe 04/06/2019<o:p></o:p></div>
</div>
<br clear="both" />
______________________________________________________________________<br />
The information contained in this e-mail message and any attachments may be privileged and confidential. If the reader of this message is not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that any review, dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by replying to this e-mail and delete the message and any attachments from your computer.<br />
______________________________________________________________________