---
title: 'Story Brand'
date: '2019-11-19T09:12:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8201193521242240033'
blogger_filename: '/2019/11/story-brand.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<br />
<b>Video 1: Customers aren’t buying? Here’s why.</b><br />
<br />
<a href="http://www.5minutemarketingmakeover.com/video-1/">http://www.5minutemarketingmakeover.com/video-1/</a><br />
<br />
<br /><b>1. Survive and Thrive</b><br />- You need to erase everything on this website about YOU, other than a short blip that establishes your authority.<br />
<br />
- You are the Mentor (Yoda), your reader is the Hero (Luke). This isn't about you, it's about them.<br />
<br />
- You need to make sure every word tells them about how you will help them Survive and Thrive.<br />
<br />
<br />
<br />
<b>2. Conserve Calories</b><br />
<br />
They have milliseconds to decide if they care about you, they won't take time to read and understand. They need to know immediately and without expending any effort, how you will help them.<br />
<br />
<br />
-- ONLY communicate about something that helps people survive and thrive, without inside and confusing lanaguge.<br />
<br />
-- Do so in such simple language nobody has to burn any calories to understand you.<br />
<br />
<br />
<br />
<br />
<br />
<b>Video 2: Five Things You Should Be Saying on Your Website</b><br />
<div>
<br /></div>
<a href="http://www.5minutemarketingmakeover.com/video-2/">http://www.5minutemarketingmakeover.com/video-2/</a><br />
<br />
<br />
<ul>
<li>What do you offer?</li>
<li>How will it make my life better?</li>
<li>What do I need to do to buy it?</li>
</ul>
<br />
<br />
<b>1. Header</b>: A header statement that says what you do. Don't get cute.<br />
<br />
<b>2. Call to Action</b>: An OBVIOUS call to action.<br />
<br />
Bad: Learn More. Get Started.<br />
Good: Buy Now. Start Here. Subscribe.<br />
<br />
<b>3. Failure. </b>Tell me what bad thing will happen if I don't buy from you. Or what problem you solve.<br />
-What stakes will there be if I don't buy from you?<br />
<br />
- Questions they're asking. Things they're struggling with. If they don't follow your advice, what bad things will keep happening, or get worse?<br />
<br />
<b>4. Success.</b> Tell me what great thing will happen if I buy your product.<br />
<br />
- What will life look like if they follow your advice? How will it change?<br />
<br />
<b>5. Plan. </b>Your website should spell out a plan.<br />
<br />
- Three steps. How do they engage you? Call them to action!<br />
<br />
<br />
<br />
<br />
<br />
<b>Video 3: The Best Possible Example of a Website That Works</b><br />
<div>
<a href="http://www.5minutemarketingmakeover.com/video-3/">http://www.5minutemarketingmakeover.com/video-3/</a></div>
<br />
Position yourself as a guide:<br />
<br />
<b>Empathy</b>: I care, I get it. "I care about you, I get you"<br />
<br />
<b>Authority</b>: Demonstrate competency to solve the problem. "I will help you"<br />
<br />
<br />
The Plan:<br />
ASK for the sale: First risk. You're asking them for something. Tell them how it works, how simple it is. Three steps. Easy. Simple.<br />
<br />
<br />
Flow:<br />
<br />
Header - What do you do? How will it help? What do I need to do?<br />
<br />
Cite the Problem<br />
<br />
Demonstrate Answer, as competent mentor.<br />
<br />
Ask for something. Subscribe. Buy.<br />
<br />
Lead Generator.<br />
<br />
Junk Drawer;<br />
<br />
((All the pages, FAQ, Contact us, etc etc... all at the bottom of the site))<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />