---
title: 'Dear Her'
date: '2019-07-13T09:27:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8942541836683824736'
blogger_filename: '/2019/07/dear-her_13.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Her'
---

Dear Her,<br />
<br />
It's so easy to get distracted with the trouble of the present that one forgets it'll feel and look different in hindsight.<br />
<br />
When I talked with my first wife, Brenda, this summer it was healing for both of us. I didn't feel hurt by her or any longing for her either. It was so old and gone I barely remember having been married to her except as a touchstone of life events.<br />
<br />
So too it'll be with this season. I thought I'd found you twice this past year. Tracy and Shelley both turned out to be not you, for different reasons.<br />
<br />
I find, though, as I sit here now in my very lonely bed... That I am less sad about Shelley, miss her less, when I realize she's not you. When I see her objectively as an amazing woman who's not healed and ready and also isn't good for me. She didn't honor my heart.<br />
<br />
I learned things from her though that have made me a better man. And both the fun and shitty lessons we're both formative. I'll be a better husband to you because of this past six months.<br />
<br />
But now that I know you're still out there... I wonder where?<br />
<br />
Are you in bed, lonely, writing me a letter?<br />
<br />
Are you in bed with another man, filling that loneliness for a while? If so, I get it. I'm grateful to him if he took care of you even for a while in my absence.<br />
<br />
Oh shit! If I really believe that, what if you ARE Shelley? And I just thanked Scott for taking care of her when I couldn't... What's the difference? Because I was there for it? Huh... I guess I have to forgive her now... Like really really forgive her.<br />
<br />
Whether or not I know you today or not... I want you to know I'm praying for you. I love you. I'm trying to overcome my past hurts as quickly as possible, grow up as quickly as possible, so I can be ready for you as quickly as possible.<br />
<br />
Hang in there... I'm a slow learner, but, when I get it I set like concrete.<br />
<br />
I'm so lonely. I want to be held so bad. But I'm starting to see that I should save myself.<br />
<br />
Shelley asked me to save myself for her. When she downgraded to Scott, I tossed that out and went out and got laid. But... It didn't satisfy. Because I want you, not a cheap imitation.<br />
<br />
As such... I'm considering making a commitment to myself to save myself for you. I'm going to be honest, with my background I don't know if I can keep a commitment like that. But I want to. With God's help, maybe I can.<br />
<br />
Dr. Jana is trying to work me to that point.<br />
<br />
Okay. I love you. Goodnight.<br />
<br />
See you soon, I hope.<br />
<br />
Darrell