---
title: 'Dear Shelley (06/28/2019 - 08/21/2019)'
date: '2019-06-29T01:07:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6837610722460691135'
blogger_filename: '/2019/06/dear-shelley-06282019-08212019.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<br />
<div class="gA gt acV" style="-webkit-text-stroke-width: 0px; background: rgb(255, 255, 255); border-bottom-left-radius: 0px; border-bottom-right-radius: 0px; border-top: none; color: #222222; font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: 0.875rem; font-style: normal; font-variant-caps: normal; font-variant-ligatures: normal; font-weight: 400; letter-spacing: normal; margin: 0px; orphans: 2; padding: 0px; text-align: start; text-decoration-color: initial; text-decoration-style: initial; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; width: auto; word-spacing: 0px;">
<div class="gB xu" style="border-top: 0px; padding: 0px;">
<div class="ip iq" style="border-top: none; clear: both; margin: 0px; padding: 16px 0px;">
</div>
</div>
</div>
<br />
<div class="adn ads" data-legacy-message-id="16ba2992e0feb0c1" data-message-id="#msg-a:r3738736634373560605" style="-webkit-text-stroke-width: 0px; background-color: white; border-left: none; color: #222222; display: flex; font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-caps: normal; font-variant-ligatures: normal; font-weight: 400; letter-spacing: normal; orphans: 2; padding: 0px; text-align: start; text-decoration-color: initial; text-decoration-style: initial; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px;">
<div class="gs" style="margin: 0px; padding: 0px 0px 20px; width: 1303.2px;">
<div class="">
<div class="ii gt" id=":bv" style="direction: ltr; font-size: 0.875rem; margin: 8px 0px 0px; padding: 0px; position: relative;">
<div class="a3s aXjCH " id=":bw" style="font: small/1.5 Arial, Helvetica, sans-serif; overflow: hidden;">
<div dir="ltr">
<div class="gmail_default" style="color: black; font-family: georgia, serif;">
<div style="margin: 0px;">
Dear Shelley,</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I wanted to talk about all this by telephone, but that's not possible for some reason. But I don't like leaving things unresolved either. So I am sending this by email so that you can have a long chance to process it. Take as long as you need. If you want to talk about it after August 21, I'd love the opportunity. If you're done with me, I understand.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<b>Disclaimer</b>: I'm going to tell MY story and do my best to use "she" and take out "you" statements as they can feel attacky and that's not my intent. I want to communicate&nbsp;<i>my</i>&nbsp;experience not judge you for yours. I want to communicate my hurt and have you hear me and see me, not blame you for it. I do feel there are things you could have done differently or you could have handled me/us better. I also know there are things I could have done differently or handled your heart better.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I'm not sure any of that matters any longer because it's already happened.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
What does matter is that if you are going to come back into my life someday, I need to feel seen and heard, valued, respected, and the friendship we had honored.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
In light of those disclaimers, here's how I experienced the last many months...</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
***</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
In November 2018, I reconnected with an old friend. She walked me through some tough stuff. She later told me she started getting feelings for me before I was aware of them, a few months before.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<i><b>Note</b>: In hindsight, I'd always tell someone to avoid developing romantically with someone whose divorce papers weren't signed yet. It's unwise and unbiblical, but I was so taken by her I ignored the warning.</i></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
On February 16th, 2019, that friendship changed. She gave me her phone number and I was able to talk with her voice to voice, not just via Messenger. We were both as giddy as a 16-year old. We talked about life and spiritual matters and the importance of words. That conversation, how words matter, made my heart open to her in profound ways. In that very moment, I knew I wanted to marry her.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
We talked and texted all day, every day. We made time at my lunches to chat. We set aside two nights a week to really talk for hours. She sent me picture after picture, some with less clothing (which my phone still won't delete, tried three times already, uhg). Pictures of her hind end still give me chills of excitement. This stuff was probably too much too soon, in hindsight. We should have waited and gone slower, but we were both so excited.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
What I discovered in this woman frequently took my breath away. She was attractive, witty, intelligent, logical, but deeply passionate. She loved my Daddy and modeled the type of relationship I used to have with him before I got bitter, and she drew me back to Him ever so gently. She was only the second woman I've known with that kind of intimate relationship with my Daddy.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She scared me a bit when she yelled at her boy to break him from the spell but that eased when I saw her turn it into affirmation afterward.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I knew she was too good for me, but she seemed to want to stay so I let her in.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She told me how it would be so exciting to just fall into the right thing without&nbsp;<b><i>having to date</i></b>&nbsp;anyone. She told me she wanted it to be forever. She said she was really making sure it was real. She told me she was head over heels.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She told me how she could see us together. She told me how she wanted me, have me visit her, her visit me.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She made plans to come with or without the babies, just to see me.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I scheduled time in July to come see her and didn't tell her but I took out one credit card just for the ticket.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I also didn't tell her but I planned a whole week off to see her for her birthday in November. It was going to be a surprise, but I canceled it now, it is what it is.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She told me she wanted to jump into my arms and attack my face.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She told me she was so turned on by me already she'd need to duct tape her pants.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She let me see her in the bath, grrrr.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She sent me more and more of&nbsp;<i>those</i>&nbsp;photos.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She told me that my words and passion for being a better man made her "creamy", and even wet a pillow.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
But most importantly, she affirmed me. Constantly. She told me I was amazing, impressive, and more than enough. She made me believe in myself. She reconnected me to the heart of my Daddy.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
This woman...</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Hear me...</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<b>This woman got deeper into my heart than any woman or person ever has.</b></div>
<div style="margin: 0px;">
<b><br /></b></div>
<div style="margin: 0px;">
<b>EVER.</b></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Flavia, due to longevity, occupied a wider space in my heart. Losing Flavia was the hardest thing I've gone through because it literally shattered the fabric of my life, day to day living, everything I saw or touched had been touched by her. It destroyed me.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
But we always struggled with the intimacy of the heart. We never quite got on the same page. I could never seem to give her what she was looking for and she couldn't hit my home in my heart either. We lacked the skills, maybe, to reach down inside. So while she occupied a wide space, it wasn't the deepest space available, that remained untouched.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Then this woman came along and between 02/16-04/10 she "affirmed" her way directly into the deepest parts of my soul. She touched places in me that have never been touched, I didn't know COULD be touched...</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She won my heart.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
If Flavia affirmed me half as well as this woman did, I'd have crawled on broken glass to make her happy every day.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I fell in love. Madly. Deeply. Permanently. In Love.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
There will never be a day going forward, that her name won't spring a yearning in my heart.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<i>I cry every time I take a call at work for a Shelley, or someone from DFW, or someone with the last name "Fox".&nbsp;</i></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I started building an entire life around her. Future joint ministry plans. Moving plans next year so I could court her in person.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I made plans to marry her.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I guess it doesn't matter if she knows now, because it's not going to happen now, at least not the way I'd planned.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
If by some divine miracle we actually decided to become romantic again, which is highly unlikely because I don't trust her with my heart anymore, I'd have to have a new plan anyway, this one no longer applied, the dates are void.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I was going to invite her brother Scott to help.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<i><b>Note</b>: Any coincidence that she married a Steve with a brother Steve, then rejected me for a Scott with a brother Scott?&nbsp;</i></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
On November 24, 2020, I was going to gather everyone I could find for a Birthday party and make them celebrate her.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
The Theme: My Pleasure</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I would have everyone give a gift that made them think of how she brought them pleasure in some way. I was going to end with my gift, and then tell her how she'd been My Pleasure and I knew I would marry her since February 16, 2019. Then ask her to marry me on February 16, 2021, two years to the day.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I know. It's cheesy. Probably not enough. She wanted something amazing, and this probably wasn't it, but it's what I had planned. I was hoping to build on it as I got to know her more.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
***</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
In March, God tried to warn me to back off, that I was getting ahead of him, but I couldn't. I was literally addicted to her affirmations.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
And she was still pushing hard, so I didn't see why I needed to. I keep going back and reading her texts and listening to the voice recordings and wondering what happened?</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
***</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
First Stab Wound</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
On April 10, 2019, when her divorce finalized, it flipped, almost instantly. She didn't want to be peed on, like marked territory. Which was a hurtful and offensive thing to say after telling me in March that she was head over heels in love with me and wanted to make a lasting forever connection.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She wanted to stretch and fly on your own. I was devasted. But I let her go... or tried to.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<i><b>Note</b>: In my heart, I thought she needed A LITTLE distance. Like, she'd go out on a few meaningless dates, come back home and talk to me still, tell me all about them. Our communication level wouldn't change. She'd just have the freedom to explore without pressure to marry me just yet.</i></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
On April 12, 2019, I wrote to her and tried to let her go. But my heart&nbsp;<b><i>refused</i></b>&nbsp;to line up with that decision.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<i><b>Note</b>: what I should have done here, is actually cut off ALL communication. That would have been wise until this season was over. I knew my heart wasn't lining up and but I was so terrified of losing her. So I stayed around, trying to be "the supportive friend" but killing myself in the process. If I'd shown more self-respect, I'd have let her go for real and stopped talking to her while she did her thing.</i></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Second Stab Wound, Self Inflicted</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She downloaded dating apps. I tried to be supportive but inside I was cutting myself every time she had a new guy she was talking with. It was like suicide to try to stay through this but I did it. I was terrified of losing her, of being discarded. I thought maybe I could just hang on long enough for this to pass.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
By participating in this, I betrayed myself. I didn't honor my heart or my value. I was terrified of losing her. I didn't honor my own value by not drawing better boundaries.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She said she was telling everyone I was her "Best Friend", which we both knew should be the person you marry, you should marry your best friend.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She said if we were still single in 3-4 years we'd marry each other... I was like, wait! What??</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I'm nobody's backup boyfriend or backup husband. If I'm not your first choice I don't want to be chosen. Not like that. How offensive and demeaning. Like "If I don't find anyone better I'll settle for you"? What happened to how amazing and impressive I was? How'd I gone from amazing and impressive to "the back up"?</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
On May 1, 2019, she wrote to me, let me know I was going to be going into a season of cultivating and that it would last to July 1, 2019. That Daddy had big things to do in my heart. I didn't want to hear it, but I knew it was true.</div>
<blockquote class="m_8829983953204898933gmail-tr_bq">
<div style="margin: 0px;">
"You have been alone for a few days... How are you Darrell? Your heart has some stuff gong on from now til July 1st.... a LOT!!!!!!!!! Did you know it is a cultivating season for you... Hey Daddy is on it tonight!"</div>
</blockquote>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Then the yoyo began</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
For the first half of May, she came back strong for a minute. She sent me 100+ photos. A new one of her I hadn't seen, (Wonder Woman). She was back. My girl was back. She wants me again!</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
On May 16, 2019, I sent her 100+ photos of QooBee just because she liked the character. I wanted to give her something.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Then...... She was gone again.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
YoYo 2</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
On Friday, May 24, 2019, she texted me and said the new guy Scott had bugged her and warned me she might come on to me because the day was so hard.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
"Yes! She needs me again! She wants me!"</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Then without warning a few minutes later, she sent me texts of getting ready for a date with the very guy she JUST said was bugging her?!?!?!?!</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Third Stab Wound</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
A few minutes after that, she sent a photo of her and Scott saying "Don't be mad".</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Of course, the fact she had to say that means she knew I would be mad but she sent it anyway?</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Disrespectful. Hurtful. Replaced. Second Best. Back Up.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Was she trying to make me jealous? Was I supposed to chase harder? Was I supposed to let her go?</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Was I supposed to feel rejected and humiliated? Because that's how I felt.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I tried to be supportive while she texted me a few times, then disappeared. Given her past, with abusive men, I thought he might have actually harmed her but she was just out bowling.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
This was confusing and painful. It felt like rejection and abandonment.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Then Came The Betrayal, the mortal wound.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Now to her, I now understand, this was just a missed calendar event. She'd slept through a few before. Probably not a huge deal, except I know she felt it when we talked... But to my knowledge, she doesn't understand what happened in my heart. For whatever reason, she didn't value our friendship enough to try to understand when I tried to tell her.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
On Sunday, May 26, 2019, I called at three minutes after our scheduled time and she answered the phone and said they had a movie night planned. Scott's voice was in the background. She'd thought about it three or four times but forgot to tell me.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Apparently, after talking and texting all day every day for two months, I'm not worth even a thirty-second text anymore.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Inside my<span>&nbsp;</span><b><i>own</i></b><span>&nbsp;</span>heart, we'd been practically engaged and I'd now walked into her in bed with another man. That's the emotional reaction this induced. It was an utter betrayal. A date, is one thing, but he's taking my sacred time now? This is the time we'd set apart for each other. And she can just toss it aside like it's no big deal?</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
An overreaction, almost certainly, but this is how it&nbsp;<b><i>felt</i></b>&nbsp;and this story is about my experience, not the objective truth.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Then The Rejection and Discard</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Monday-Tuesday, we talked it out by text because she wouldn't make time to talk by phone. But it was clear it wasn't working. I cried all day both days. Almost had to leave work because I couldn't take a call without tears and voice cracking.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She said I never bother her except for the "dramatics", indicating that my emotions are not valid or real they are simply overreactions.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
After calling me her "Best Friend" and telling me she'd been head over heels in love, she now didn't even consider me worth calling when I tried to communicate my hurt. Real friends, I thought, want to resolve matters quickly, before the sun goes down, but she'd rather ignore it, I guessed.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She hoped I'd just get over it on my own, I guessed?</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She sent me texts saying "Make sure you know I want you in my life", to which I wanted to respond and will now because I haven't changed my mind "If you want me in your life, put me there. I don't believe you, I still don't." I believe her actions, not her words on this matter. I'm so deprioritized, that I just don't matter anymore.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She somehow didn't see Scott as my replacement. Yet she was giving him all the time she'd given me, having the same conversations that built our intimacy and my love for her, and he was now getting the ONE thing I so desperately wanted but couldn't have, her physical presence. He wasn't just my replacement, he was getting a better deal and she'd literally taken everything she gave me and gave it to him instead, because, despite the fact she had all this time to do this with him, she was too busy now for me. He was, in fact, my replacement in every way, including and especially in her calendar, which is the most important communication of value.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Scott understands less spiritually, is more broken, but hey, he's there and I'm not, so he gets her best and I get nothing. Besides, he's of practical use around, and I'm not. I was worth pursuing when she had time, but I outlived my usefulness, I guessed.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Then, as though she were rubbing it in my face, as I'm dying inside and posting things to process my recovery from abandonment and rejection caused by her actions and my own, she starts tagging my replacement in my own posts.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Like hey, this guy's getting everything you wanted and still want and can't have and now I'll give him my piece of you too.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Let me rub it in your face more that he's replaced you. I'll give him myself and you.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<b>Eventually... Maybe she saw it? I think?</b></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Because, she sent me a song that was the exact feelings I was living, with two words "Never Planned".&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I now see she was trying to say she was beginning to see my pain? I guess... but she didn't really communicate. Which is the crux of where things went hopelessly bad... Communication.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She'd cut me off. From daily to zero to infrequent vague texts that were just enough to get my hopes up but never anything substantive or real. She never actually said anything in them.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Sending two words without premise, body, and conclusion, was worse than sending nothing. Two words are open to interpretation.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Never Planned.... What? Exactly?</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Never Planned to hurt me? Never planned to fall in love and then out of it so quickly? Never planned what? I still don't know what she meant.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Did I overreact? Sure. I was desperately trying to salvage what was left... But she didn't seem to care to salvage anything... That's the message her silence communicated.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I'm left to wonder if I was just a rebound guy. She enjoyed me until something new and shiny and more available came. He helped her with the house when I couldn't, he was more useful, I guess. I'd outgrown my usefulness.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Or maybe she really did love me, but she was scared. She saw this great guy but started to wonder if she was settling? She needed to go out into the world and find out?</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Or maybe she was just too wounded still from her past to know what she wanted, which is why she yoyo'd me for so long, because she herself didn't know what she wanted?</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Or maybe I was her rebound but she doesn't even realize that's the role she put me in. It wasn't intentional.. but now that she's in this really wierd place, she's got to go experience things and figure stuff out and I was just a casualty along the way. She didn't mean to hurt me, she may even still have feelings, but she's got to go find herself and there's nothing either of us can do about it.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
After re-reading her testimony, I think I might be a repeat of the guy from her high school years that "would have been a great husband and father" but she chased him away.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I really don't know what all happened in her heart, because she shut me out and never told me. She never said goodbye but stopped showing up too. She just faded away in fits and starts.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
On Wednesday, May 29, 2019, I finally accepted what I tried to accept on April 12, I really did have to let her go. I really can't follow her into this season.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
The problem is, I couldn't go back to "just friends" either.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
We were friends, but we crossed a line and she tore a "her" sized hole in my heart and filled it with herself and then left me with the hole.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I was angry, livid, furious, more at myself than her... for letting myself get fooled into thinking she really wanted me. I felt alone, rejected, discarded, unwanted, unloved, cast aside, cut off, discarded like yesterday's news.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I let my guard down and she pulled the rug. She didn't mean to. I don't think that. But it happened nonetheless.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Since then...</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Throughout the following weeks, I read the "How To Get a Date Worth Keeping" book by Dr. Henry Cloud. I came to realize that I am not okay. I have an unhealthy tendency in life and it goes far beyond this one woman.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
It's kept me from being a "Real Man" and initiating. It's kept me from taking risks and pursuing a career. All my friends, girlfriends, and careers have been something I backed into, never something I pursued with purpose and intention.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Then I read The Discard Trauma (<a data-saferedirecturl="https://www.google.com/url?q=https://www.facebook.com/Freetheself/posts/2726100637419943&amp;source=gmail&amp;ust=1561887489312000&amp;usg=AFQjCNEeCwuCZqaZhWBfF4XEt30ytAzVNw" href="https://www.facebook.com/Freetheself/posts/2726100637419943" style="color: #1155cc;" target="_blank">see here</a>) and I learned what happened to me internally that caused the dramatic overreactions.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I'm an Affirmation Addict.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I'm the male Runaway Bride.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I'm so dependant upon getting another hit of affirmation, that even starting an argument and getting her to respond is better than being ignored.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
So I started looking at the areas of my life in which I denied my "Self" in order to People Please or avoid The Discard.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I like Dr. Pepper. I enjoy the brand. I enjoyed going to the Dr. Pepper museum. It's part of who I am. My quirk. But I stopped wearing that shirt because she made fun of it, and I wanted her to like me. I won't do that again.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
She made fun of my toy collection and I considered removing it before she visited. But it's who I am. I like it. I'm keeping it right where it is.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I don't think she meant to, but it was almost like she was trying to change me, subtly, and I was letting her because I wanted her affirmations so bad, and I was so terrified of The Discard.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Like the Runaway Bride, I now need to find out who I am and stick to it. Like all of me or don't, but this is who I am. What kind of eggs do I like? I don't know. I never made decisions when I was married. Flavia made decisions. I was terrified of making the wrong one.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I think maybe... this woman I fell for is just broken, as am I. Her brokenness is just different than mine. We both reacted out of that place of fear and woundedness. Her reaction is to shut down and run away, my reactions probably felt like abuse or something, mine was to press in harder to try to work it out in abject terror of being discarded. Yet those very reactions caused a bigger discard than probably would have happened if I'd been strong enough to be "just friends" and healthy enough to let her go and just do me and take whatever contact she gave me.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
A bad combination of woundedness, I suppose.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
On June 21, 2019, God gave me a word, which I later shared with her by screenshots. He said to leave it all alone for 60 days.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
He did give me permission to write these words I keep rehearsing over and over and over in my head in this letter. That way, they're said. Since she wouldn't do it by phone, I can at least communicate them as dispassionately as possible, while also trying to feel heard by my Best Friend.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
After August 21?&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I don't know...&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I know the next two months are a season in which I will heal from the hurts (both the real and the perceived). I am already feeling more disconnected from the situation.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I cried over her every single day, multiple times a day, not exaggerating, between 05/24 and 06/26... I've only had a few cries since then. It no longer feels like an open bleeding wound. Now it feels like a sour wound, bandaged but still in need of major healing.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I don't know how to return to "friends" but God said he had plans for our friendship and I'm hoping He's able to make a way where there seems to be no way.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I can only pray, in time, she'll hear me and see me as I wanted. Even if she never "loves" me again, as she did in Feb and Mar, knowing she heard my heart and cared about it, would be amazing!&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
For now, I'm blind to all she experienced. Maybe when I hear her side, someday, it'll help me see what I missed, where I misinterpreted, where I could grow.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
As crazy as it sounds, I'm actually looking forward to single now. God's done some amazing things in me, and I hope to tell her all about it someday. But I'm not ready to open my heart again in that way just yet.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
In Conclusion</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Shelley is, despite everything I just said, the BEST thing that happened to me in Widow Year One. I owe my renewed relationship with Daddy, my ability to hear Him more clearly, and even some really sucky hard lessons He's taught me the past two weeks, all to her.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I understand that there must be some things I don't know about her side of the situation and I believe that knowing those would have helped me see it differently, or more deeply. Maybe she'll tell me someday when she's ready... maybe she doesn't have words for them yet herself.</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I am so proud of her. She amazes me. To come out of her past with as much healing as she has already is impressive.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I use her Shelleyisms often with my friends.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I am so looking forward to seeing her up on the platform, changing lives by the thousands some day.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I am sad that I can't be her Dave, that I'm not enough, but when she finds him, she's going to be glad she held out for him. Because he's going to love her better than I did.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
I don't know if this is goodbye or just see you later... I'm going to leave that ball in her court. If she decides to return after August 21, I guess we'll cross that bridge when we get there. If it's the day after, or the year after, either way.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Thank you for everything, I mean it. You've been amazing. I'm going to look for someone who is a lot like you in many ways when it comes time to settle down in a few years.&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
Your (fill in the blank?), Darrell&nbsp;</div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<br /></div>
</div>
<div>
<div class="m_8829983953204898933gmail_signature" data-smartmail="gmail_signature" dir="ltr">
<div dir="ltr">
<div>
<div dir="ltr">
<div>
<div dir="ltr">
<div>
<div style="color: black; font-family: &quot;Times New Roman&quot;; font-size: medium;">
<div style="margin: 0px;">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif;"></span></div>
</div>
<div style="color: black; font-family: &quot;Times New Roman&quot;; font-size: medium;">
<div style="margin: 0px;">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span><span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant&nbsp;</span></div>
<div style="margin: 0px;">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
<div style="margin: 0px;">
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="mailto:me@DarrellWolfe.com" style="color: #1155cc;" target="_blank">me@DarrellWolfe.com</a></span></div>
<div style="margin: 0px;">
<br /></div>
<div style="margin: 0px;">
<span style="font-family: &quot;tempus sans itc&quot;;"><a data-saferedirecturl="https://www.google.com/url?q=http://www.DarrellWolfe.com&amp;source=gmail&amp;ust=1561887489313000&amp;usg=AFQjCNFgTkIz1iO2qYI3MaVzy5MQ3sGZlw" href="http://www.darrellwolfe.com/" style="color: #1155cc;" target="_blank">www.DarrellWolfe.com</a></span></div>
</div>
</div>
<div class="yj6qo">
</div>
<div class="adL">
<br /></div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="adL">
</div>
</div>
</div>
<div class="hi" style="background: rgb(242, 242, 242); border-bottom-left-radius: 1px; border-bottom-right-radius: 1px; margin: 0px; padding: 0px; width: auto;">
</div>
</div>
</div>
<div class="ajx" style="clear: both;">
</div>
</div>
