---
title: 'Who am I? My Noble Self'
date: '2019-07-15T06:48:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7109098269578358535'
blogger_filename: '/2019/07/who-am-i-my-noble-self.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

Who am I?<br />
<br />
As I stare at the bright moon, on a cool summer night, less than 30 minutes from 39 years old... I'm asking myself that question yet again.<br />
<br />
But I'm asking it in a way I maybe haven't asked before. Not in a hopeless, clueless, aimless way... but in a way that says "I've seen clues, glimpses, of this Noble Self and Wounded Self. I see them both, and I now understand that I can choose which one I will feed. So who am I? How do I choose to feed this Noble Self?"<br />
<br />
All of my brokenness is tied to my make-up and character. You created me the way I was created. The Devil CANNOT create. He can only twist or distort. So who am I?<br />
<br />
What did you create me to be that the devil's forces used to twist and distort into this man?<br />
<br />
My patterns:<br />
<br />
Find a woman who's desperate and lonely and hurting. Comfort her. If I get a response, press into that comfort. Begin starting conversations about how hard it is not to be held, stroked, have hands run through my hair, feel the pressing of bodies... she misses that too. She responds. If that works, what do you miss most? She says things. I stroke her ego. We both begin to share things we missed, which turns into things we'd like to do, which turns into doing them if she's nearby. If we have sex, one of two things will happen:<br />
<br />
1. I'll get attached and she'll pull away.<br />
2. She'll get attached and I'll pull away.<br />
<br />
If that's my pattern? Where did it come from? What thing inside of me is twisted into this thing? And also, on the positive side, this shows I CAN initiate. I always said they found me, they pressed, but the truth (now that I can see it) is that I played an active role in my own seductions and didn't even realize it. Now that I see it, can I ever go back, knowing that I'm manipulating them this way? I didn't mean to. It was just two lonely hearts giving each other what we wanted. But honestly, was it? Or was it just two people using each other for short term highs and long term adding more pain.<br />
<br />
If I can't be that any longer... what can I be?<br />
<br />
Can I be this Noble Self? Can I go on dates and refrain from asking sex questions, or redirect them if she brings them up? Can I say no, if they invite me over?<br />
<br />
Later, if I find someone who I believe is "the one", will I have the fortitude NOT to text her all day every day, to maintain my separate sense of self, to pursue my goals, to tell her "No, you can't have this hour, it belongs to something else. You're important to me, but I need to do other things too. And I want to give you time also. Let's schedule that for XYZ."....... Instead of getting lost in the high of it and ignoring all my other duties until my life becomes unmanageable?<br />
<br />
What is it inside of me, the God Created Noble Self, that was twisted into this pattern?<br />
<br />
I guess he's not saying right now... because I hear silence. I guess that the answer is coming. Going to bed.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />