---
title: 'Her 2.0'
date: '2019-06-03T09:25:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4735953621494452319'
blogger_filename: '/2019/06/her-20.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Dear Her'
---

The first list I created was full of nit-picky things Dr. Cloud said would pigeon hole me into never finding the right woman. These were my preferences and not actual requirements. I am keeping the list for reflection someday, but not reading it anymore.<br>
<br>
Instead, I am building a list of attributes or characteristics the women I date and know have shown me, positive and negative. "She" in this list refers to my reflecting on an interaction but could refer to any number of different women I've interacted with.<br>
<br>
<br>
<b>Insights:</b><br>
<br>
<b>N</b>: Probably looking for an Intuitive. xNxx on the MB Type. I'd like to meet some S's to see the difference in action.<br>
<br>
<br>
<br>
<br>
<b>Things I've Liked:</b><br>
<br>
Authentic Self. I liked that she is her authentic self. She is the same with anybody and has no qualms about telling them who she is and isn't.<br>
<br>
Present In The Moment. She's not distracted on her phone, worried about the future, distracted by the past. She is simply present, here, now, enjoying this moment in time. I could benefit from learning how to do this.<br>
<br>
Active Listening. She listens well but actively listens. She doesn't just parrot back what I've said but speaks into the situation with her own thoughts.<br>
<br>
<b>Intuition</b>, Spiritual/Emotionally Connected: She is in tune with what other's are feeling. She even intuits when to call without me telling her I need someone to talk to. She just seems to know without always being told.&nbsp;<br>
<br>
SAFE Space. This is a big kicker for me and my background of hiding turned to No Hiding. I mean, literally. There's nothing I couldn't tell her that she wouldn't reply "That's where you are, it's important to acknowledge that. It's okay to be you. It's okay to be not okay. Sit with that for a moment."<br>
<br>
On Fire for God. She loves Daddy first and foremost and nobody would ever get in the way of that.<br>
<br>
Spitfire Personality. She's got spunk. I'm not used to holding the attention of a confident woman. She has insecurities but she's dealing with them and she is owning who she is.<br>
<br>
Affirmation. She listens and affirms who I am even in the middle of my not being all God made me to be. She makes it a point to be affirming on purpose.<br>
<br>
Sex: Our talks on this subject assured me that she would not only be an attractive spouse, but she would be an engaged sexual partner. She would give and not just receive in this area. My former partners have been so docile that this is a huge concern for me. I don't want to have to ask you to do something to me, I want you to just want it.<br>
<br>
<br>
<b>Things I didn't like:</b><br>
<br>
Respect. Shelley disrespected me. While her care for other's is great, we had a standing Date Night. Shelley gave it away without warning or heads-up, and although she says she meant to 3-4 times, she didn't. I was crushed. If you don't have enough respect for the effort and time we've put into building something to notify me well in advance... then I don't want you anywhere close to my heart. <i>Is this a J thing?</i><div>
<br>
Not Safe. Her Fears. What I mean is, her fears of things (like the comic character conversation) make me feel insecure about how safe she really is. If my just being ME creates negative emotions in her, I feel the need to hide who I am. That leads to unhealthy things in me. No Hiding is my number one priority. If she's not safe, she's not the one.<br>
<br>
Treatment of her Children. She says she's dealing with spirits and once she has their attention she does soften and affirm. But the way she totally screams and (from a distance over the phone) seems to lose it with them, scares me. Even after she explains it.<br>
<br>
Attachment Issues. With her background, and the children thing is an example, she has issues building real attachment (healthy or unhealthy). She's SO take it or leave it, that it comes across as me feeling unwanted or insecure about my status in her heart.<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br></div>