---
title: 'Daily Journal | Sunday 06/02/19'
date: '2019-06-03T09:12:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8199696772420210919'
blogger_filename: '/2019/06/daily-journal-sunday-060219.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

This morning at Church, we talked about the Discerning of Spirits. He made a lot of really great points. The big takeaway is that you face the demon in front of you, don't go looking for the fight. You are not "Dog the Demon Hunter". Also, that spirit has the goal of attaching itself to any place of power; and, twisting or distracting. If something feels off, it is. You may be dealing with a person, but you don't deal with that person you deal with the spirit inside of them/operating in them.<br />
<br />
Pastor Geoff called up anyone who wanted to walk in this gift or walk in it more fully. Then he had us turn around and pray over anyone that needed prayer. A woman came up and a group of us prayed over her. But nobody was really actively praying. As I did, checking my spirit "Daddy, how do you want me to participate in this?" An image came up. Scissors. Blue handles. I waited but nothing else came. I finally reached out to lightly touch her hand and said<br />
<br />
"I see Scissors. Cut. Cutting away. Like God wants to cut some things out of your life."<br />
<br />
She cried a bit and told about an on again off again man who'd done damage to their family. He called this morning and she told him to never call again. It was confirmation for her that she was on the right track.<br />
<br />
I mentioned the Bonzai Tree, Mr. Miagi, and how pruning does not look like hacking everything away but rather a delicate process of cutting away various pieces until a new form takes shape. You won't recognize yourself by the time this is done.<br />
<br />
Then I realized, it's as much for me as it is for her. That's the season I am in. I'm both growing new leaves and pruning dead ones.<br />
<br />
***<br />
I took the boys to Tubbs Hill. Nobody else showed, but it is what it is. We had fun, talked about Flavia, and the future of our family and making friends. We need to have interesting experiences with interesting people and stop setting ourselves up with requirements that exclude nearly everyone.<br />
<br />
Preston wants to go swimming more.<br />
***<br />
<br />
I took Aylish, rather she took me, to the Spokane Comedy Club tonight. It was a fun experience and definitely something I'll do again. Probably a good date idea for the future.<br />
<br />
After we talked, I shared my experience that morning. Then I saw something in her I've never paid enough attention to see. It's something that I want in a future spouse. I didn't really have a label for it before or even a context for it. I was barely aware of its existence.<br />
<br />
Authentic Self<br />
Present In The Moment<br />
<br />
We talked about how those are big parts of her and who she is. It allows her to experience more things and more people, and be present for the people she's with. I'll be on the lookout for those traits in the future.<br />
<br />
She's also dating a guy who has a Pentecostal background. She may bring Daniel to New Life next time he's out.<br />
<br />
If God could ever really get a hold of her heart... she'd be a FIREBALL of a prayer warrior and intercessor and an amazing wife. She wouldn't be mine, because there're other things she doesn't have I need... but Daniel would be a lucky man indeed.<br />
<br />
<br />
***<br />
<br />
I talked with Theresa on the way home. What is it with me finding all these Leftist females and making friends with them? ha ha...<br />
<br />
Theresa has shown me more traits to look for. She:<br />
<br />
Listens well, but actively listens. She doesn't just parrot back but speaks into the situation with her own thoughts.<br />
<br />
She is in tune with what other's are feeling. She even intuits when to call without me telling her I need someone to talk to.<br />
<br />
She is SAFE space. I mean, literally. There's nothing I couldn't tell her that she wouldn't reply "That's where you are, it's important to acknowledge that. It's okay to be you. It's okay to be not okay. Sit with that for a moment."<br />
<br />
I think they've both been instrumental in what I want...<br />
<br />
***<br />
<br />
My thoughts turn back to Shelley, then. I was SO enmeshed and I didn't see it. We called each other constantly, out of the blue, scheduled talks at lunches and twice a week for sure. I do remember getting a little annoyed by doing it every lunch, thinking I needed a little space. When she then got too busy for me and I couldn't get her attention, I started freaking out. Then she went on a date and sent me a picture saying "don't be mad", but I was mad. Fuming mad. Then she gave away our date night and I lost it completely. I literally had a meltdown. How could she do this to "us"? Yep... WAY too enmeshed for someone 1,800 miles away. There's a place for SOME of this in a marriage or serious relationship. And I did think we were headed to marriage until she disappeared. However, I can now see there was no way that was a healthy place for either of us to be in this season of our lives. She got there before I did and started pulling away, and I didn't let go until the last string was pulled from my white knuckles. Now I can see it wasn't healthy.<br />
<br />
<b>I liked:</b><br />
On Fire for God. She loves Daddy first and foremost and nobody would ever get in the way of that.<br />
<br />
Spitfire Personality. She's got spunk. I'm not used to holding the attention of a confident woman. She has insecurities but she's dealing with them and she is owning who she is.<br />
<br />
Affirmation. She listens and affirms who I am even in the middle of my not being all God made me to be. She makes it a point to be affirming on purpose.<br />
<br />
Sex: Our talks on this subject assured me that she would not only be an attractive spouse, but she would be an engaged sexual partner. She would give and not just receive in this area. My former partners have been so docile that this is a huge concern for me. I don't want to have to ask you to do something to me, I want you to just want it.<br />
<br />
<br />
<b>I didn't like:</b><br />
Respect. While her care for other's is great, we had a standing Date Night. She gave it away without warning or heads-up, and although she says she meant to 3-4 times, she didn't. I was crushed. If you don't have enough respect for the effort and time we've put into building something to notify me well in advance... then I don't want you anywhere close to my heart.<br />
<br />
Her Fears. What I mean is, her fears of things (like the comic character conversation) make me feel insecure about how safe she really is.<br />
<br />
Treatment of her Children: She says she's dealing with spirits and once she has their attention she does soften and affirm. But the way she totally screams and (from a distance over the phone) seems to lose it with them, scares me. Even after she explains it.<br />
<br />
Attachment Issues: with her background, and the children thing is an example, she has issues building real attachment (healthy or unhealthy). She's SO take it or leave it, that it comes across as me feeling unwanted or insecure about my status in her heart.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />