---
title: 'The Shelley Conundrum'
date: '2019-05-27T02:45:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5163494350113565145'
blogger_filename: '/2019/05/the-shelley-conundrum.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<b>Rejection (perceived rejection):&nbsp;</b><br />
<div>
<br /></div>
<div>
Shelley was just a friend. But then in February she and I began talking about a possible future together. I put together a whole timeline to begin courting her and working toward a proposal.&nbsp;</div>
<div>
<br /></div>
<div>
She was sending me pictures, both kinds, and practically convincing me that she was the one and I'd never find anyone better. And I began believing her.&nbsp;</div>
<div>
<br /></div>
<div>
Then when her divorce finalized it was like she turned 180*... She pulled back hard. She said "we're just friends" and didn't want to be "peed on". She needed space to embrace and enjoy her singleness.&nbsp;</div>
<div>
<br /></div>
<div>
Intellectually, I totally understand that. I went through that this past year. I had come to a point in February where I thought I was ready to put that aside and look for something "real". So I let her have her space... and she practically disappeared.</div>
<div>
<br /></div>
<div>
I spiraled into a deep depression. I went back to my old habits and even an old partner. I then felt that I betrayed myself and Shelley.&nbsp;</div>
<div>
<br /></div>
<div>
Even though we were "just friends" and she was downloading dating apps and talking about making out with random guys because she could now, my heart was already sold. It was too late. So I betrayed my heart, even if we were "just friends" on paper.&nbsp;</div>
<div>
<br /></div>
<div>
We kind of got our groove back after a while, found a new normal. But then Scott came into the picture more. He was around all the time. Helping her with the house. Helping her with the move. Now she's at his kids' games and they went on a date.&nbsp;</div>
<div>
<br /></div>
<div>
She assured me I was still her "best friend"... but she never calls or texts or communicates. She tells me it's more about ministry with him but tonight...&nbsp;</div>
<div>
<br /></div>
<div>
We'd set aside Sundays to catch up and chat. I viewed that time as special and set aside for her. She missed it a few times. Slept through it because she was tired... I get that.</div>
<div>
<br /></div>
<div>
But tonight... she set up a movie night with Scott and didn't even bother to tell me ahead of time?!?!?!?! What the giant fuck? Why bother telling me this time is set aside and then not even bother to cancel.</div>
<div>
<br /></div>
<div>
Even if we had never been anything than friends, I'd deserve better notice than that.</div>
<div>
<br /></div>
<div>
Then she gave away our dedicated date night to another man.&nbsp;</div>
<div>
<br /></div>
<div>
I am feeling cast-aside. Rejected. Hurt. Unwanted. Lonely. Desperate to be wanted. I refuse to be anyone's back-up or second choice.&nbsp;</div>
<div>
<br /></div>
<div>
I will not spend any more time or energy on this. If she wants space, she can have it. All of it. I can't do this anymore. The tension between where we were and where we are is not bearable. I need space too.</div>
<div>
<br />
I KNOW that I'm over-reacting. This is not the big deal that it feels like it is. But right now I feel like my world died again. It's probably compounded grief and raw emotions. But I don't even know how to break out of this particular stronghold cycle I'm in at the moment.<br />
<br />
I need to go for a walk...<br />
<br />
<br />
**************************<br />
<br />
After my walk...<br />
<br />
I'm being selfish. I'm viewing her out of my need and not hers. Which is unloving and unkind. She has a companion, of sorts, and she wants attention. She's been desperate for this kind of attention for years in a loveless marriage (two of them). I cannot give her what she needs right now. Maybe ever.<br />
<br />
What I can do is pray for her healing and safety. I can pray she is well provided for, even if that's not coming from me. I can pray for her calling, gifting, and purpose.<br />
<br />
And I can go let God by my spouse.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br /></div>
