---
title: 'Shared with a friend'
date: '2019-05-26T00:52:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4046622099920627242'
blogger_filename: '/2019/05/shared-with-friend.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

This is how I was feeling this afternoon...<br />
<br />
My best friend, and I thought future wife but now not so sure, is busy. She's got a guy helping her quite a bit and now she's gone on a date with him... We decided to be "just friends" for this season and I agree it's the right thing to do... But my jealous factor shot through the roof when I saw pictures and she actually started dating. I know in my head that she's exploring her new wings of singleness (recently divorced) and I get it. I even dated during this just friends period...<br />
<br />
Nevertheless, she used to text all the time, even during the day to see how I was doing or share some random tid bit... Now she goes days without responding... I'm feeling lonely and rejected and unworthy... I'm feeling cast aside... and I just want my late wife back... But when I read through our journals for the last few years, I'm forced to acknowledge my marriage to my LW sucked and we both wanted out. Even weeks before she passed she wrote that she wanted out... Apparently, I just suck as a partner...<br />
<br />
I have decided with my mind to be single on purpose for a season, regain a healthy singleness and healed mind)heart so I can enter the next season of marriage to whoever without dragging all the past in...<br />
<br />
But I just want someone there in my bed at night and someone to come home too, and it sucks.