---
title: 'Daddy about Shelley'
date: '2019-06-14T05:57:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8467445870015909328'
blogger_filename: '/2019/06/daddy-about-shelley.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">
<div class="MsoNormal">
I’m sure there’s coming a day where I’ll forgive her but-<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
You’ll forgive her right now!<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
But I’m angry!<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Be angry and sin not. She’s my daughter and you asked for her hand in marriage at one time. Now you forgive her and be angry. I’ll work on it. Stop messing with it. You two will be friends again, I assure you. You’ll even see where you   messed up, some things you can’t see from her perspective today. She’ll see your perspective someday too. You’ll even laugh about it. Today, go ahead and be angry but don’t you dare live in unforgiveness and cut me off from the ability to bless both of you.   I’m not promising you two will ever get married or want to again. But I can restore your friendship if you’ll let me do it and stop trying to make it happen. Don’t contact her until July 31 or after. Don’t respond. Don’t get wrapped up in a conversation. Disengage.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal" style="line-height: 125%;">
<b><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif;">Darrell Wolfe<o:p></o:p></span></b></div>
<div class="MsoNormal" style="line-height: 125%;">
<b><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 9.0pt; line-height: 125%;">Triage Associate | Account Protection  <o:p></o:p></span></b></div>
<div class="MsoNormal" style="line-height: 125%;">
<span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 9.0pt; line-height: 125%;">Alliance Data  </span><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif;"><o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: 125%;">
<span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 9.0pt; line-height: 125%;">751 W Hanley, Coeur d’Alene, ID 83815<o:p></o:p></span></div>
<div class="MsoNormal">
<a href="http://www.knowmoresellmore.com/"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">knowmoresellmore.com</span></a><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">   | </span><a href="https://www.linkedin.com/company/2973795?trk=tyah"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">LinkedIn  </span></a><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">|  </span><a href="https://www.facebook.com/KnowMoreSellMore"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">Facebook</span></a><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">  </span><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">|  </span><a href="https://twitter.com/know_sellmore"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">Twitter</span></a><span style="font-family: &quot;franklin gothic book&quot; , sans-serif;">  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
</div>
<br clear="both" />
______________________________________________________________________<br />
The information contained in this e-mail message and any attachments may be privileged and confidential. If the reader of this message is not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that any review, dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by replying to this e-mail and delete the message and any attachments from your computer.<br />
______________________________________________________________________