---
title: 'Prayer Walk, Shelley'
date: '2019-05-29T18:08:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7877743978852790132'
blogger_filename: '/2019/05/prayer-walk-shelley.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

Today on my walk with Jesus, we talked about two things. Me. The Cross. Shelley.<br />
<br />
<br />
<b>Me.&nbsp;</b><br />
<br />
I love you, Darrell. I died for you. I lived an entire life leading up to the cross for you. I had you in mind when I covered Adam's nakedness. I have planned on your life since before the foundations of the world.<br />
<br />
You are hurting, I understand. I hurt too while I was on this earth. I was rejected. I am still rejected and I hurt sometimes today. Remember, the tears I am going to wipe away in heaven are primarily mine. That is still in the future, it hasn't happened yet.<br />
<br />
<br />
<b>The Cross.</b><br />
<br />
As I was on my way to Golgotha, a man was taken from the crowd to carry my cross because I couldn't bear it any longer. I was physically too weak to carry it. I, Jesus, couldn't carry my own cross all the way to the hill. I needed help.<br />
<br />
That is the nature of crosses. They require assistance to be carried.<br />
<br />
<br />
<b>Shelley</b><br />
<br />
Right now, Shelley is in a season of carrying a cross. Some of it is due to her own decisions and stubbornness, and some of it is a season I'm walking her through. She needs help, more than you alone can provide. I've brought up people around her for this season.<br />
<br />
What I need you to do, is carry her cross. Lighten her load.<br />
<br />
Right now, she doesn't need you to be a husband she needs you to be a friend. She said it and I hinted at it and now I'm telling you. Be her friend, not her husband or boyfriend.<br />
<br />
<b>Here's how you carry her cross:</b><br />
<br />
<b>1. Prayer.</b> Come to me in prayer for her. Intercede. Fight demons. Be Impressive. She'll see how impressive you really are.<br />
<br />
<b>2. Selfless-Love</b>: Be her friend, even when you don't feel like she's being yours. Make it about her not about you or what you get from her. Listen to her. Ask questions. Make it about her not you. Don't share too much about what you are dealing with right now, bring that to me. Even if she asks you, keep it light on details. This is not your season, it's hers.<br />
<br />
There may come a day when she turns around and really sees just how impressive you really are. That day is not today. You may even find that she's the one after all... maybe. That will be up to you and her to decide, I will not force things either way. If she's not your "one", then I'll have another for you. Today, in this moment, I need you to put aside all of it, all the feelings, all the desires, and yes, all the dreams and just BE her friend.<br />
<br />
In the meantime, whether it's her or someone else, I need to be first in your life. Me and only me. I am the only source of LIFE and you need to be really plugged into me.<br />
<br />
Build a loving marriage with me. Love on me and let me love on you. Walk with me. Play with me. Learn to hear me in the most stressful moments. Build stillness in your life so that even when storms come, you are still inside. Then you can speak to the storms from that place of stillness.<br />
<br />
Build a relationship with your boys. They lost their mom. They need you more than you've been able to be there. It's time to level up. I'll show you how. The main focus will be doing things together, side-by-side.<br />
<br />
Have a great day, be impressive, Go be Amazing! R<br />
<br />
Remember to build stillness in your heart, hear me, throughout the day.<br />
<br />
<br />
<br />