---
title: 'Dear Shelley'
date: '2019-06-06T08:01:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8606585732118751610'
blogger_filename: '/2019/06/dear-shelley.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

Dear Shelley,<br />
<br />
There's probably nothing I'm about to say you don't already know but someone told me I could let go better if I wrote this.<br />
<br />
I love you.<br />
<br />
Not just as a friend. I fell in love with you. You came into my life when it would be inappropriate to pursue you and I didn't. Then you became single after I did. We talked and caught up. You were my friend as I went through an uphill battle for sanity.<br />
<br />
On February 16th, 2019, that changed. You gave me your phone number and I was able to talk to you voice to voice, not just via Messenger. You were as giddy as a 16-year old and so was I. We talked about life and spiritual matters and the importance of words. That conversation, how words matter, made my heart open to you.<br />
<br />
We talked and texted all day every day. We made time at my lunches to chat. We set aside two nights a week to really talk. You sent me picture after picture, some of you with less clothing. You told me how it would be so exciting to just fall into the right thing without having to date anyone. You told me how you could see us together. You told me how you wanted me there and you wanted to come here. You made plans to come with or without the babies, just to see me. You won my heart.<br />
<br />
On April 10, 2019, when your divorce finalized, it flipped. You didn't want to be peed on, like marked territory. You wanted to stretch and fly on your own. I was devasted. But I let you go, or tried to.<br />
<br />
On April 12, 2019, I wrote you and tried to let you go. But my heart refused to line up with that decision.<br />
<br />
On May 1, 2019, you wrote me. You let me know I was going to be going into a season of cultivating and that it would last to July 1, 2019. That Daddy had big things to do in my heart. I didn't want to hear it, but I knew it was true.<br />
<blockquote class="tr_bq">
"You have been alone for a few days... How are you Darrell? Your heart has some stuff gong on from now til July 1st.... a LOT!!!!!!!!! Did you know it is a cultivating season for you... Hey Daddy is on it tonight!"</blockquote>
<br />
For the first half of May, you came back strong for a minute. You sent me 100+ photos. A new one of you I hadn't seen anymore, (Wonder Woman).<br />
<br />
On May 16, 2019, I sent you 100+ photos of QooBee because you liked him. I wanted to give you something.<br />
<br />
Then...... You were gone again.<br />
<br />
On Friday, May 24, 2019, you texted me and warned me you might come on to me because the day was so hard. You sounded like you needed me. Then without warning a few minutes later you sent me texts of getting ready for a Date. A few minutes after that, a photo fo you and Scott.<br />
<br />
On Sunday, 26, 2019, you gave away our established Date Night without any warning. Scott was in the background. And I died inside. I tried to share my heart and you either heard it but couldn't communicate that you did or you couldn't hear it.<br />
<br />
Monday-Tuesday, we talked it out. But it was clear it wasn't working. I cried all day both days. Almost had to leave work because I couldn't take a call without tears and voice cracking.<br />
<br />
On Wednesday, May 29, 2019, I finally accepted what I tried to accept on April 12, I really did have to let you go. I really can't follow you into this season. The problem is, I can't go back. We were friends, but we crossed a line and you tore a hole in my heart and filled it with yourself and then left me with the hole. But I was angry, livid, furious.<br />
<br />
Throughout the week, I read the "How To Get a Date Worth Keeping" book by Dr. Henry Cloud. I came to realize that I am not okay. I have an unhealthy tendency in life and it goes far beyond you. It's kept me from being a "Real Man" and initiating. It's kept me from taking risks and pursuing a career. All my friends, girlfriends, and careers have been something I backed into, never something I pursued.<br />
<br />
I decided I really do need this time to just be single. But now I understand what "Single with Purpose" actually might look like.<br />
<br />
The problem is, your hole is still there. I cannot stand to see you with anyone else. I can't stand that you don't call or text anymore, barely.<br />
<br />
I had a plan to propose. I was going to invite your brother Scott to help.<br />
<br />
On November 24, 2020, I was going to gather everyone for a Birthday party and make them celebrate you. Have everyone give a gift that made them think of how you bring them pleasure. I was going to end with my gift, and then tell you how you'd been my pleasure and I knew I would marry you since February 16, 2019. Then ask you to marry me on February 16, 2021, two years to the day.<br />
<br />
I literally had my heart set on it. Now I have to burn that dream. Who knows, our lives changed in an instant on 02/16/2019, changed in an instant again on 04/10/2019, and my life was torn apart on 05/26/2019 and I died inside. Maybe God will restore everything. Maybe I'll decide this was worth it. Maybe you'll come back and I'll still want you.<br />
<br />
Even as I write this, I find myself hoping you'll want me after I've forgotten about you. Then I realize that's selfish and I really just want you to be happy. I'm just angry.<br />
<br />
I hope you find someone that is a Real Man, I'm sorry I wasn't enough to keep your attention.<br />
<br />
Frankly, if I can't have you at the alter as my wife, I don't want you there at all. Fuck that best man crap, you're not even invited to the wedding. I don't want to be your best friend unless it's as your BEST friend.<br />
<br />
Then I realize, I'm writing this out of my pain and not my truest heart. You really hurt me. I've almost killed myself three times since last Sunday. Well, not really, but I've wanted to. Maybe that's the problem. Maybe I'm just so broken that if we'd kept going I'd have broken you too. Another in a long line of disappointing men in your life. Maybe it's safer if we don't talk for a while.<br />
<br />
Maybe God can restore our friendship, but right now I don't feel like there's anything to restore. I hope you actually answer the phone/or call/ tomorrow like you said you would, but I feel you don't respect my time enough to even remember. If tomorrow doesn't go well, if we can't find a mutual place, then I am really going to let you go and cut you out of my life for a time. Because I can't move on with you still partially attached and you won't let me in.<br />
<br />
Maybe by the time July 1 comes, I'll feel differently. Maybe. I hope I do. Because even if you didn't choose me, you're still worth having as a friend. I just don't know if this hole will ever heal enough for that.<br />
<br />
If any of this hurts you, I'm sorry. It's what I'm feeling and it was never intended to be read by you unless I either died, or we really both got really healed and we can look back and laugh at what an immature ass I was.<br />
<br />
Goodbye Shelley. It was nice knowing you, then it wasn't.<br />
<br />
Darrell, your former best friend.