---
title: 'Stop living for the approval of women, Darrell'
date: '2019-05-25T04:21:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5920514888313017289'
blogger_filename: '/2019/05/stop-living-for-approval-of-women.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<br />
Article:&nbsp;<a href="https://www.artofmanliness.com/articles/stop-living-for-the-approval-of-women/" target="_blank">Stop living for the approval of women</a><br />
<br />
"You’ve been rationalizing, compromising, second-guessing, playing it safe, and avoiding confrontation. As a result, you’ve slowly forgotten what really matters to you, what you were once passionate about, how you truly feel about issues, yourself, and others."<br />
<br />
Shelley is dating... I feel rejected and unwanted. Why? We decided we're "just friends", shouldn't I be okay with this? Why did I get emotionally involved? She has every right to explore herself. Heck, I ran to someone local after she decided we were just friends.<br />
<br />
I guess I over-stepped because she isn't talking or responding right now.<br />
<br />
Just re-read it all. I don't think I overstepped, she's just busy and I'm getting clingy. Bad combination.<br />
<br />
Why do I do this? Why do I get so wrapped up in the approval/rejection of females in my life?<br />
<br />
Why do I care? She's, effectively, been in my life this way since February. Sure, there's a history of sorts, but I didn't care like this until then.<br />
<br />
OH.... This is a repeat of Emily. The too-good-for-me girl who spent time alone and I sought comfort in another's arms in her absence... causing distance between us.<br />
<br />
Darrell, you are a fallen human being. You failed. You betrayed yourself, and the decision you knew was right. You should have told Theresa "no" but you told her to come. You had multiple chances to say no, even just before she got off later and checked in again before coming, and you still said "come". You knew better.<br />
<br />
Darrell, I (you) apologize to you for letting you down. I forgive myself for making a bad decision. I plead the blood of Jesus over that decision.<br />
<br />
------<br />
<br />
I want to be a better human being. A better child of God. I cannot make one-time-forever decisions, I've learned that about myself. Decisions are made daily, moment by moment, decision by decision, but I can make better choices. I can decide now that I will make better decisions in the future.<br />
<br />
------<br />
<br />
I want to be free. Free from this incessant need to be approved by a woman. Free from lust, and inner loneliness. Free from the shackles of whatever it is that has me bound. Only then, can I be the kind of partner that a good woman deserves! Maybe it'll be Shelley, maybe it'll be someone else and she was a glimpse of the future.<br />
<br />
Selah<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />