---
title: 'Journal Notes'
date: '2019-06-07T08:16:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '371718170395337051'
blogger_filename: '/2019/06/journal-notes.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">
<div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><div class="MsoNormal">Apparently, I have the voice recording but never transcribed it... So I just did.</div><div class="MsoNormal"><br /></div><div class="MsoNormal">July 14, 2018:&nbsp;</div><div class="MsoNormal"><br /></div><div class="MsoNormal">The time is short my friend. The time is short my servant. The time is short my son. We don’t have time to wait around. We don’t have time to let time tell. Do all things in the right time but don’t delay this. The end (of times) is nearer than you think and there are people to save, there are people to heal there are people who need the Love, and Power, and Presence of God and you need a partner to do it. You need someone who you can help as much as they can help you. So take your time to grieve. Take your time to heal. But when the time comes, don’t delay. Don’t push back. Don’t tell me no. Don’t think selfishly. Step out of the boat onto the water. And I will be right there with you. And you’ll see amazing things.</div></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal">
07/17/2018&nbsp; - Gas station drive-through: Why are the outer leaves dry and parched and discolored but the inner leaves fine and healthy? It’s in a drive through, the exhaust is blowing toxins against the outer leaves. And so it is in the spirit. You can be connected to the one but if your spirit is contaminated by toxins you’ll be unhealthy. Unlike the leaves, you have a choice to detox daily by getting renewed daily In Him! Don’t just be a Christian; be a Christian who’s daily coming before your Father and renewing in His presence. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
07/23/2018 – I love you. I love you so much I died for you. I have great plans for you. I have another partner for you who will be great for you and the boys. JoAnn will love her too. She’s a writer with 2 kids the boys will love. Your households will blend perfectly. She’s coming soon, sooner than you might think you’re ready for. Take your time but don’t dawdle. Do Over. Grace. Mercy. Shalom. Selah.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
08/02/2018 – Text/Phone with Sister Julia. (1) Jesus love me! Really love me. He’s my Husband and I am the Bride of Christ. He’s passionate about me in ways I cannot currently comprehend. (2) Put “Pastor” on a shelf. Put it away. Don’t mention it to anyone. Don’t bring it up in conversations. Just put it away. (2.1) You must follow well to lead. (3) Titles you own today are Father-be present for the boys and Man of God-Be nothing but loved by Him.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
08/05/2018 – Victory City Church, Pastor Chris Vigil. *I remember “I have a pastor starting a church, would you be willing to help him?” I felt I could help this church, but didn’t feel right there still.  <i>(06/06/2019) Now at New Life I feel good there but still feel unsettled. OH SNAP, Amor de Calvario?</i><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Not just a good statement, this was a prophetic Word:<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b>The Course and Quality of your life will be determined by what you are willing to leave behind.  <o:p></o:p></b></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b>God's Plans: He knows, you may not, he has a plan, but since we don’t know it can feel unpredictable.  <o:p></o:p></b></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Either you lead (control) your life of God does. It can’t be both. Who do you want planning things?<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
When God wants to increase my faith; he decreases my sight. <o:p>  </o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
What you experience has FAR more to do with HOW you see than WHAT you see.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Vision: Transit Station, School, Hospital for Broken People.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Surrender means you don’t strive to try and produce fruit you strive to enter His Rest.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Would an MBA help me run my business ministries?<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
You cannot be more godly trying harder to do a better knowledge of good. Living righteous has nothing to do with “good behaviors”, those come from the Tree of Knowledge. Living rightly is about thinking differently, not seeing with Knowledge   but seeing with LIFE, and that only comes from a different tree. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
08/26/2018&nbsp; - Rise Up. Come Up Here. See things from my throne, my vantage point. All things are lawful but not all things are profitable. Rise above the distractions and see the path I’ve laid before you. See my right and live forward.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
08/27/2018 - Fear is a faith killer. The bigger the task, work, or dream… the more important it is to play it close to the vest. Remove influences that would introduce doubt or fear.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
08/29/2018 – God said, “I have a topic I want you to write about.” Topic: What it means to live a life set apart unto God. Honesty, Serving, Business, Sex, Relationships, Money.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Job was a man of integrity who does the right things. He kept his paths straight and activities above board. He feared God and turned away from evil. He didn’t just talk bad about evil but do it anyway. He turned from evil, kept his feet   from it, avoided it, and it’s opportunities to tempt.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
NO SIN IS VICTIMLESS<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
11/03/2018 – Dear Jesus, I don’t understand. I finally fell in love with the woman you gave me and now she’s gone. I got what I wanted (pre 2017) and it’s hollow. I can’t win. I know that I will not be prepared for the woman you have next   if I don’t put away these distractions and start working on me. But I’m so lonely. So So So LONELY. Maybe I can organize the list and keep it with me as motivation? Okay, I’m done talking now, what would you like to say?<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
God: “You are my beloved in whom I am well pleased. You stand before me dressed as my Son. I see you as a warrior. Be Strong and very courageous. The end of this seaons draws nigh and a new season begins. She’s just around the bend. Selah.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
**06/06/2019 – Here’s what I don’t get Daddy. You said this and you Shelley came. But you said two kids and writer and Shelley wasn’t that. You and I have a different concept of “just around the bend” and “soon”.**<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
11/04/2018 – <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
God deals with sin in categories but he’s categorically dealt with sin.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
You cannot live without temptation but you can chose not to yield to it.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
God’s BIG Moves are often followed by Satan’s BIG Temptations. The devil will always be back, he’s looking for opportunities.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Recognize that ANY hunger (I want) is a need for God that temptation will ask you to fill without God.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
What you worship, you will serve.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
11/12/2018 – 140 days, 7 hours, 35 minutes without you, Flavia. The boys and I spent the night in a cabin on the lake. You’d have been proud of Connor. He vacuumed the bugs and slept there anyway. Without you, it was hollow. All I could   think was how much you’d have liked it. Preston’s isolating a lot. I don’t know what else to do. You would.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
11/16/2018 – 1 Year from Now (11/16/2019) what will I wish I’d done/accomplished instead of scrolling through Facebook and feeling sorry?<o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -0.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: symbol;"><span>·<span style="font: 7pt &quot;times new roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;Spent time with the boys (quality time).<o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -0.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: symbol;"><span>·<span style="font: 7pt &quot;times new roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;Spent time in The Word, Prayer, Worship (loving union).<o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -0.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: symbol;"><span>·<span style="font: 7pt &quot;times new roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;Started school for myself and the boys. <o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -0.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: symbol;"><span>·<span style="font: 7pt &quot;times new roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;Joined a men’s group (or started one). <o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -0.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: symbol;"><span>·<span style="font: 7pt &quot;times new roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;Settled into a Church and Serving. <o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -0.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: symbol;"><span>·<span style="font: 7pt &quot;times new roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;Smoke Free<o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -0.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: symbol;"><span>·<span style="font: 7pt &quot;times new roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;180 lbs +/- // 34” waist // L Shirts // Isagenix Daily (or equivalent).  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
01/13/2018 – Jesus didn’t deal with the man he dealt with the demon inside of the man.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Dr. Jim Richards: The need to be valued can drive you to bad behavior. Someone who feels like a King acts like a King at all times.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
It’s not about Freedom FROM (behaviors, feelings) but from TO be who he has called us to be and created us to be from before the foundations of the earth.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
01/21/2019 – Vision (see teal journal). “I felt love and sympathy for him instead of hate. I didn’t want him dead, I wanted him delivered.” I felt like praying in tongues after the vision.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
01/22/2019 – As I sat praying and listening, I felt stronger and more mature.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
“There you are Peter!” Hook<o:p></o:p></div>
<div class="MsoNormal">
“There’s the Darrell I know and love.” Jesus.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
01/27/2019 – The more you allow someone else to do for you something you can and should do yourself, the more you lose yourself.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Darkness is a lack of knowing the Love of God for you.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div style="border: none; padding: 0in 0in 1pt;">
<div class="MsoNormal" style="border: none; padding: 0in;">
<br /></div>
</div>
<div class="MsoNormal">
<br /></div>
<div style="border: none; padding: 0in 0in 1pt;">
<div class="MsoNormal" style="border: none; padding: 0in;">
<br /></div>
</div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
05/27/2019<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
How I see myself:<o:p></o:p></div>
<div class="MsoNormal">
Fat. Failure. Unwanted. Unwantable. Used Up. Washed Out. Broken.  <o:p></o:p></div>
<div class="MsoNormal">
<br />
Daddy, how to you see me?<br />
I see a hurting child who lashes out to protect himself. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Daddy, what goodness do you see?<o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -0.25in;">
&lt;![if !supportLists]&gt;<span>-<span style="font: 7pt &quot;times new roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span>&lt;![endif]&gt;I see a man who will lay aside his own pain to minister healing to others in need.<o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -0.25in;">
&lt;![if !supportLists]&gt;<span>-<span style="font: 7pt &quot;times new roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span>&lt;![endif]&gt;I see a servant’s heart.<o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -0.25in;">
&lt;![if !supportLists]&gt;<span>-<span style="font: 7pt &quot;times new roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span>&lt;![endif]&gt;I see a man who wants to love his children well.<o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -0.25in;">
&lt;![if !supportLists]&gt;<span>-<span style="font: 7pt &quot;times new roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span>&lt;![endif]&gt;I see a Boaz, caring for the widows in need.<o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -0.25in;">
&lt;![if !supportLists]&gt;<span>-<span style="font: 7pt &quot;times new roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span>&lt;![endif]&gt;I see an intelligent and creative man who enjoys new projects.<o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -0.25in;">
&lt;![if !supportLists]&gt;<span>-<span style="font: 7pt &quot;times new roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span>&lt;![endif]&gt;I see a man who wants to do what’s right, because it’s right, but sometimes struggles to do it right away.<o:p></o:p></div>
<div class="MsoListParagraph" style="text-indent: -0.25in;">
&lt;![if !supportLists]&gt;<span>-<span style="font: 7pt &quot;times new roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span>&lt;![endif]&gt;I see a man who is willing to fight depression instead of surrender to it.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div style="border: none; padding: 0in 0in 1pt;">
<div class="MsoNormal" style="border: none; padding: 0in;">
<br /></div>
</div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
The problem isn’t that you don’t hear me. Your problem is that you hear me and then run off without hearing the rest of the instructions… Preston Jr. Yeah! That’s right, I called you Preston Jr. Stop doing that!  <o:p></o:p></div>
<div style="border: none; padding: 0in 0in 1pt;">
<div class="MsoNormal" style="border: none; padding: 0in;">
<br /></div>
</div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b>Shelley<o:p></o:p></b></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
On 07/23/2018, I thought you said my wife would be a writer with 2 kids who’d blend perfectly with our household. But Shelley is not a writer and has three children.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
On 02/21/2019, I asked you for Shelley’s (your daughter’s) hand in marriage.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
On 03/01/2019, Let’s talk about Shelley. I need you to back off just a smidge. You’re way out in front and I’m glad you’re excited. But not everything you see if for her to hear yet and not everything is for right now. Futuristic is a top talent and I made you that way. You are to see the future, she is to strategize that future. But you are the leader, as the man. Don’t give it to her until it’s time to strategize. She has some healing to do and so do you. *<b>God’s smiling</b>* You’ve done good kid, son, keep going. Just don’t run ahead. Walk with me on this path/road, at my pace. Your futuristic talent has you seeing ahead but if you run far ahead you’ll try to make it happen. That’s been your mistake, over-using your God Given Talent. In this instance, walk don’t run, slow, steady wins this race. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Last item on the agenda, Connor and Preston. Engage them. Listen to Connor and affirm/praise him. Play and spend time with Preston. Her kids aren’t your kids… yet. Sow into the fields I’ve given you and then I’ll expand. Make them secure   in your love. Show them MY heart… a Father’s heart.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
PS: Enjoy the house. You won’t have it long. *<b>smirk</b>* Not telling you, just watch. $$$<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
On 03/03/2019 – God showed me that distance makes the heart grow fonder and this seasons will help you stand on your feet and grow together with HIM (friend, family, father, brother).  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Confirmed: She Needs The Distance<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
She was feeling preached at. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Her fear: “I’m waiting for the other shoe to drop, that you’ll realize I’m not just a lot but I’m too much!”  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
On 03/07/2019, <o:p></o:p></div>
<div class="MsoNormal">
Me: “God, IS Shelley my wife?”<o:p></o:p></div>
<div class="MsoNormal">
God: “In time, yes. IF you both walk closer to me, you’ll walk closer to each other. Walk, don’t run!”<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
On 04/10/2019, she told me she needed to not be “peed on” or marked like territory and to back off a bit.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
On 04/12/2019 – I wrote her releasing her to singleness, but couldn’t let go in my heart.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
On 05/01/2019 – Shelley gave me a Word. Cultivating Season until July 1<sup>st</sup>.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
On 05/27/2019 – I officially ended any “relationship” with Shelley. She’s been just friends for months but I finally accepted it.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
06/07/2019 – I read all of my journal notes and see the whole picture and feel TOTALLY lame. I was the epic picture of a whiney baby instead of quiet strength. God’s walked me through depression recovery and started uprooting. My only hope   is that I haven’t damaged things with Shelley beyond repair. If it doesn’t work out with her, it’ll have been good practice. This next year I’m not going to hear as much from her. In fact, it could be July 2018 before I really start to hear from her again.   But everything in my hear disagrees with my mind, and tells me that she’ll come back to me and we’ll make it work. She’s got a lot of traits I wouldn’t look for and I’m no longer sure I ever heard God on this. I don’t know if I just wrote what I wanted or   if it was Him. But it’s all happened as He said (despite me)… so maybe there’s hope. In the meantime, I guess I have to really really really really let go and just go be single, and grow in God, and leave her alone. If she’s meant to be, she’ll return in due   season. Hm…. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
06/12/2019 - I had to block her on Facebook and send her a text. Then it blew up a bit more. See today's post. I can't be her friend anymore. Not in this season. Maybe someday. Maybe not. Only if she can start Validating my emotions instead of ignoring them or discounting them.&nbsp;</div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal" style="line-height: 125%;">
<b><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot;, sans-serif;">Darrell Wolfe<o:p></o:p></span></b></div>
<div class="MsoNormal" style="line-height: 125%;">
<b><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot;, sans-serif; font-size: 9pt; line-height: 125%;">Triage Associate | Account Protection  <o:p></o:p></span></b></div>
<div class="MsoNormal" style="line-height: 125%;">
<span style="color: #1f497d; font-family: &quot;franklin gothic book&quot;, sans-serif; font-size: 9pt; line-height: 125%;">Alliance Data  </span><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot;, sans-serif;"><o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: 125%;">
<span style="color: #1f497d; font-family: &quot;franklin gothic book&quot;, sans-serif; font-size: 9pt; line-height: 125%;">751 W Hanley, Coeur d’Alene, ID 83815<o:p></o:p></span></div>
<div class="MsoNormal">
<a href="http://www.knowmoresellmore.com/"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot;, sans-serif; font-size: 10pt;">knowmoresellmore.com</span></a><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot;, sans-serif; font-size: 10pt;">   | </span><a href="https://www.linkedin.com/company/2973795?trk=tyah"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot;, sans-serif; font-size: 10pt;">LinkedIn  </span></a><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot;, sans-serif; font-size: 10pt;">|  </span><a href="https://www.facebook.com/KnowMoreSellMore"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot;, sans-serif; font-size: 10pt;">Facebook</span></a><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot;, sans-serif; font-size: 10pt;">  </span><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot;, sans-serif; font-size: 10pt;">|  </span><a href="https://twitter.com/know_sellmore"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot;, sans-serif; font-size: 10pt;">Twitter</span></a><span style="font-family: &quot;franklin gothic book&quot;, sans-serif;">  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
</div>
<br clear="both" />
______________________________________________________________________<br />
The information contained in this e-mail message and any attachments may be privileged and confidential. If the reader of this message is not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that any review, dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by replying to this e-mail and delete the message and any attachments from your computer.<br />
______________________________________________________________________