---
title: 'Wed 05/22/2019'
date: '2019-05-22T20:00:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6982806775392079455'
blogger_filename: '/2019/05/wed-05222019.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

I'm feeling.... I'm not sure. But I laid down, face down, to drown out all the noise (internal and external) and felt I should take Preston for a walk (which I did) and then journal. Somehow Journaling gets at what I can't get at by talking to myself out loud.<br />
<br />
I've learned to pay attention to my body as it relates to my feelings. Today, I tried continuing my research into becoming a Copywriter. The articles and videos sound so promising. But as I tried to go into UpWork and bid I felt my mind and heart close off. Like I was trying to squeeze into a hole to small for me.<br />
<br />
It was so difficult that I had to stop. I tried to read my Bible and couldn't remember the last line. It was like a fog had come over me. I felt like there were a thousand things I could do but didn't know what I should do.<br />
<br />
My head felt heavy, my chest tight, I wanted to just turn off the world and sleep. But today is the day off. If I'm doing anything productive this week it'll be today, Yes?<br />
<br />
But is it really productive if I press into things that won't produce and ignore things that will? What needs my attention most?<br />
<br />
What do I really want? I want to lay it all down and run to Texas and hold Shelley in my arms for a week.<br />
<br />
On that note, Shelley. What's with this? There're 6.5 billion people on the planet, millions in this region, and I get hooked up with the one friend (potential girlfriend) who is 1800 miles away, too chaotic and busy for me, and a bit hard around the edges?<br />
<br />
But over the years, we liked each other's comments on WTF Sex Facts. She knew that at least one person saw her and accepted her plight. One person knew she wasn't happy. Meanwhile, I felt the same.<br />
<br />
In November, when I saw the Facebook handle change from ShelleyandSteveHunter to Shelley Hunter I was amazed and intrigued.<br />
<br />
When she shared her real story, all of it, childhood, first husband, marriage to Steve, I was shocked. I couldn't believe someone held it together that well after all of that.<br />
<br />
When I opened up and shared my struggles and she didn't reject me but did challenge me, I was beginning to link up.&nbsp; When I shared my exploits and she laughed at me but in a friendly way, asking if I was done with the world yet, I hooked.<br />
<br />
When we spent months talking about marriage and love, I was experiencing infatuation.<br />
<br />
When her divorce was final and she said she needed space and to not be peed on, I felt rejected.<br />
<br />
When she inched back and said I'd backed off too far, I felt rekindled.<br />
<br />
When I, guessing I was truly single again, met with a FWB and told her about it, and she didn't reject me, I felt understood.<br />
<br />
I betrayed what I knew in my heart, whether we agreed to it anywhere or not, and she felt a tad betrayed even though we'd asked nothing more than friendship from each other officially. We can "officially" be best friends all day long out loud, but I knew I was courting her and so it was wrong in my heart even if we weren't "together".<br />
<br />
I love that Shelley is smart, witty, giggly, small (not fat, a trigger for me), sexy and sex-minded, and a woman who is fiercely running after God's heart with everything she is and has.<br />
<br />
I find her hard outer shell to be a bit aggravating at times. When I want someone who will say "I hear you. I see you." I get "toughen up buttercup, let's do this.". Somehow, I feel that this won't change, per se, in person, but it will evolve and have more nuance. Hugs go a long way to soften this.<br />
<br />
I find her reactions to her own children to be a bit concerning. I get why she does it. I think that it's partially an attachment disorder (something I experience) and partially a reaction to the spiritual influences in them at this time and partially total exhaustion. I hope that she'll soften, or that I'll provide that balance. We won't know until I can be there in person. But this side does worry me. It's counterbalanced by how quickly she moves into affirmation though. Right after she yells to get their attention she softens to affirm. So I'm not that concerned, but it does shock me over the phone.<br />
<br />
I really do wonder if I'm the Dave to her Joyce Myers.<br />
<br />
She is pretty, but she is not the "type" I am usually drawn to. I wonder if that's a good thing. I wonder if I'm trying to be more attracted than I am, or, if I am and I am trying to convince myself not to be? ha ha...<br />
<br />
**<br />
<br />
It's been almost a year since Flavia passed. An ambulance drove down my block today and it didn't give me a panic attack. It did make me think about that night though and relive some of those emotions. Tried talking to Preston about it and he deflects as usual.<br />
<br />
**<br />
<br />
If I keep having to work dead-end jobs I'm going to cry. If Copywriting isn't an answer, what is?<br />
<br />
I think often about Niche Sites, but what niche? What can I do it on that will actually bring traffic and clicks and still provide value to the reader?<br />
<br />
I need to read my bible, and my textbook, and finish the other book RL gave me, and work on my best-list, and do the sink, and work on the children's to-do list, and somehow hope I have enough gas to make it to Friday.<br />
<br />
No conclusion... Oh well.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />