---
title: 'New Season'
date: '2019-07-06T08:26:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7721888847039476247'
blogger_filename: '/2019/07/new-season.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

So many things........ I'm not quite ready to give in and give up... I'm still clinging to my bad habits and coping mechanisms... but I'm almost ready. It's time to lay them all aside soon.<br />
<br />
Shelley isn't my person. She made me feel affirmed, wanted, and made me generally feel good. Her sexual talk made me squirm with excitement. She loves my Daddy and drew me to him.<br />
<br />
But frankly, there were things about her that weren't great. She yelled at her kids, would she scream and me like that? Fuck Shelley, not everything is a demon. You deal with brokenness differently than demons and you can't lump it all together. Get a softer side.<br />
<br />
She tried, unintentionally, to change me. Dr. Pepper. Toys. She was trying to form me into her image, not embrace who I am. My woman LOVES these idiosyncrasies about me.<br />
<br />
She didn't fight for me. My woman isn't looking for anyone else when she finds me. She's seen what's out there and she's waiting until I show up.<br />
<br />
I didn't see her and her kids fitting into our lives perfectly. It could have worked, but I didn't see it.<br />
<br />
Frankly, she's a pouty little girl who needs to grow the fuck up.<br />
<br />
That being said... is there a remote possibility that she and I could both grow in such a way that there's a future version of us that could fit? Maybe. Probably not.<br />
<br />
My woman is a writer and editor, and she'd never send me speech-to-text with indecipherable nonsense I have to interpret.&nbsp; She definitely wouldn't send an email with that to a cop. Every word would be carefully crafted, ever sentence articulated. I don't think I could live with someone who takes the written word so lightly.<br />
<br />
Is this a hang-up? Could I actually benefit from someone like this and we could compliment each other? Maybe. But this is actually my biggest pet peeve against her right now. I would find this insufferable at the moment. And it leads back to her unwillingness to communicate. It's not enough that you speak, you must ensure the other has heard you. Sending me links and partial sentences with inferred meanings are only cute when the inside joke is already known. I like picking up on subtleties, but not in place of real communication about important things.<br />
<br />
So I'm releasing Shelley. Not just to a season, but to her life. She can go have a wild season and then find her Dave. I'm sure I'll love him, whenever we meet.<br />
<br />
I'm looking for my Sarah Heart Pearsons to my Jeremy Pearsons. I'm looking for someone to soften my intellectual side but also be able to rise up and challenge it. Someone who can help me process my emotions, not constantly frustrate or belittle them.<br />
<br />
She's out there. I don't know if she's a blond with blue eyes, or a redhead with green, or a Pocahontas with black eyes and hair... and I don't care. I care about her character and heart.<br />
<br />
I'm holding out for the word I got last july/august. A writer, with two kids my kids love, and joann will love her, and she'll fit into this household perfectly, like an old glove, similar to how Dacia did.<br />
<br />
In the meantime, I need to get on top of some things I laid aside last year. Including my novel. And getting this house in order.<br />
<br />
Goodnight.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />