---
title: 'LNWW One Year Post'
date: '2019-07-15T06:56:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3814073744478321222'
blogger_filename: '/2019/07/lnww-one-year-post.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

It's been just over a year. 6/25/18. I just wanted to thank everyone here, especially Ron James. It was an insane year. But I'm feeling like I have a life in front of me now.<br />
<br />
I have less idea about where I'm headed, dreams, goals, visions, than ever before. But I'm also more at peace than I've ever been before.<br />
<br />
My ambition is pointless anyway. I never accomplished the things I spent decades working at, and missing time with my family for, anyway.<br />
<br />
I've chosen to stop rehearsing the past, and just be grateful for every good moment and every hard lesson.<br />
<br />
I've chosen to stop future tripping, I can't control anything about what happens next.<br />
<br />
I've learned to be PRESENT in this moment only. Cherrish what I have. It may be a sunset over pine trees on a warm evening, as it is today. My two healthy boys in the house playing on game systems provided for us by supportive friends and family. It may be the debt free SUV I'm sitting in. Or the half acre I bought this year that it's parked on.<br />
<br />
I'll let the credit cards be behind today. The dishes unwashed. The trash bill be unpaid. I'll let the fact I thought I had a chapter two and she didn't work out and I miss two women now for different reasons... All the things I could dwell on... I'll lat that all go for this present moment.<br />
<br />
For THIS Present Moment, I'll just be grateful and breath. I have a relationship with Jesus. He provides me the intimacy I need. Not all I want, but all I need for THIS Present Moment.<br />
<br />
I haven't participated much lately, not like I did the first six months. But I plan on being around a bit more again. We'll see which ways the wind blows.<br />
<br />
For those of you on the front end, GOD I'm so sorry. I know it sucks. Nothing we say will make it suck less. Hold on. Breath. Take walks. Take naps. Yell. Scream. Hit something. Cry. Veg Out on TV. It's okay to be not okay. Get into grief counseling, and take support from those in these rooms. Don't let anyone prey on your weakened state and take advantage of you. But if you want to seek comfort in the arms of another, and you know it's safe to do so, I won't blame you. Don't agree to marry anyone the first year. That's a rebound reflex. Not saying this person isn't great, build something, but take it slow. Tell them you'll talk about it after a year, or two.<br />
<br />
God bless Y'all! Thanks for being there for me this last year.<br />
<br />
Here's to year two.<br />
<br />
Shalom!