---
title: 'Sharon Dillion - Rathdrum Food Bank'
date: '2019-06-20T21:49:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2623975504434086974'
blogger_filename: '/2019/06/sharon-dillion-rathdrum-food-bank.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

In 1980, Sharon started the Rathdrum Food Bank inside a Methodist Church. When the Methodist Church closed, it was then moved to an old house for a few years, then they eventually found their home on small-town main street, right next to city hall. When she was first approached about moving into this full facility, she said she didn't have the money to take up that much space. However, a few friends wanted to own a Thrift Store and said she could use the back room and they would take the front. Together, they share the $1,000/month rent plus utilities.<br />
<br />
Donations come in from a variety of sources, including schools, churches, and local food drives. The USDA provides some food at a reduced order cost and that food requires special handling and tracking because it is ultimately tax dollars at work. The largest and most steady contributors are the Lutheran and Catholic churches as well as the Super One grocery store in town.<br />
<br />
Donations do not only include food, but the money required to keep the place running. There have been some who give when they can and some who contribute regularly on a monthly or every other month basis.<br />
<br />
She runs the place with a volunteer staff of 10, all over 50. She wonders what will happen to it when she's gone because young people don't often stay around to help. Her husband passed away in 2011, and she doesn't do much else but garden, tend her chickens, and run the Food Bank.<br />
<br />
The Food Bank serves the Rathdrum / Hauser school districts, and she directs people from surrounding areas to their own local Food Banks, many times they didn't know they had. She knows all the other owners and works with them to share resources. Participants are allowed to come once per month, but if it's been three weeks she'll let it go and help them out.<br />
<br />
Sharon also takes her service a step further, as an established member of her community, she occasionally helps some of the very needy elderly widows with paying an electric bill or water bill. The local utilities all know her and they work with her to help when bills get tight for residence in her area.<br />
<br />
Much of the money and donations come in during the fall/winter, but there are occasional food drives throughout the rest of the year. This year they were blessed and they've not been empty once since December, highly unusual compared to past years. Summer often pushes an increase in need, as kids are out of school and need a solid three meals at home. The school free meals programs often take this burden off of families, so they are more in need during the summer months.<br />
<br />
Sharon is a laid back lady who takes no gruff but has a passion for helping people in need. She has volunteers for now for staffing purposes but would like to see some older folks come in and not just ask to help but ask how they can really get involved in running things behind the scenes, not finances, and paperwork. She just takes it one day at at time and doesn't spend too much time thinking about what will happen when she's gone. Someone will pick up the reigns. Or they won't.