---
title: 'Walking with Jesus 05/30/2019'
date: '2019-05-30T18:54:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3409716911301950723'
blogger_filename: '/2019/05/walking-with-jesus-05302019.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

I'll never know, this side of heaven, whether moving to Idaho led to Flavia's death or whether it would have happened no matter where we lived. I now believe it would have happened anyway, because wherever you go, there you are. The dynamics of our relational skills, communication skills, finances, all the things... never really changed from CA to TX to ID. They grew and improved incrementally but did not fundamentally change. If we'd stayed in Texas... we still would have gotten pregnant and she still would have worked for Walmart and she still would have refused to see a doctor. Her weight and health issues as they were, they still would have missed the clot and she still would have passed away.<br />
<br />
Nothing that happens in life is for ONLY one reason... but one gift God has given me in this season of my life is the forest. I've always loved and connected with the forest in profound ways. I've always felt closer to God in the forest. He has given me not only Coeur d'Alene in general, but now a special half acre hideaway in Athol smack dab in the middle of the perfect blend of pavement and forest for my morning walks. It was his way of feeding my soul during a difficult season.<br />
<br />
This forest is also my wilderness. It's where I go to be along with God. Some have the desert, I have the mountains.<br />
<br />
***<br />
<br />
I took time to thank God for the many people He's brought into my life since last June. Michael, Corey and Kent for their support. Tracy, Aylish, Theresa, and Melissa have all contributed in one way or another to my growth. Even Victoria has shown me what I don't want but thought I did (one-night stands). Dacia and team has brought a special relief.<br />
<br />
A special thanks for Shelley. She has been the most profound key to my healing and growth. She's given me a vision for what my marriage could have been like. She's played the role of Darrell and I the role of Flavia a few times so I could see the other side. She's been the source of my greatest pleasure and greatest pain this year. But I'm grateful for her because she has awakened in me the life of God that I had cast aside so many years ago.<br />
<br />
I released her into God's hands. I accepted where she hurt me and where I let it happen. I accepted a gentle rebuke for having those thoughts and conversations with someone who's divorce wasn't yet finalized, knowing she would require this season she's in now after it happened. I accepted that she may not be for me (as a spouse) and if that's the case then someone else is. I accepted she could be, maybe, if some things change for both of us. God won't tell me that because it depends on some things we'd both have to line up with, and He will not over-ride human will.<br />
<br />
Story:<br />
<br />
I liken this to a man who held his deepest treasures in a room in the center of his heart. A woman came along, professed her love, and convinced him to open that door. She came in and played and danced and in her frolic, she broke quite a few things. Then she thanked him for letting her come and left him standing there to pick up the pieces. She came back to visit a few more times but couldn't understand why he was not the same. "It's just stuff", she said. But to him, this was his most prized treasure. She broke it and she didn't even notice or care. He had to add extra security to that door afterward to keep her out. He still let her come over and visit, but he would not allow her back into that room until she could see, really see, and feel, the damage she'd caused. He still enjoys her visits, but he's guarded.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />