---
title: 'Sigh..... AAHHHHHHHHH.....'
date: '2019-07-04T19:26:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2376472228503031002'
blogger_filename: '/2019/07/sigh-aahhhhhhhhh.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

Why?!?!?!?! Why did Shelley leave me, especially for THAT guy? Uhg.... I keep trying to find my way back. Consider unblocking her so I can see what she's doing? Text her and beg her to come back. All of that is co-dependant manipulation. If I love her, I have to let her go. I said what needed to be said. I sent it. I left the ball in her court. I asked her not to reply until after August 21... Boundaries tell me to leave it alone. But I'm dying. I want her so bad. I want MY Shelley back. The one who wanted me. Not that it would work. Everyone doubts her now. Including, and especially me...<br />
<br />
So I should learn to be PRESENT, not stuck in the past, even recent past. Shelley isn't coming back. If she does, it won't be the way we planned originally. So I'd rather she just doesn't if she isn't coming back to be mine. I can't separate friend from formerly future spouse.<br />
<br />
There's a "her" out there somewhere. But after the way I was treated... I don't know if I trust anyone again. I don't know if I can open my heart again...<br />
<br />
Maybe she'll have the Passion of a Shelley, Safety of a Theresa, Comfort of a Dacia, and Fire in the bedroom of a Tracy, and the Artistic Excentricity of a Flavia?<br />
<br />
Or maybe none of these... maybe she's just her own special combination of person and I just don't know what I want or need until God brings her.<br />
<br />
Yeah...<br />
<br />
I guess I should be working on my school paper. Instead of wasting my entire morning pining over lost love. But it's 12:25, so the morning is gone. Better not waste the rest of the day. Fuck this is hard to focus.