---
title: 'Dear Her'
date: '2019-07-03T16:55:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '846820217406691202'
blogger_filename: '/2019/07/dear-her.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Her'
---

Dear Her,<br />
<br />
I wish you were here. I wondered if I'd met you a few times this year. Each turned out to either be a place holder, a counterfeit, or a foreshadowing... But they weren't you. There was always something in me that held me back. Not quite right.<br />
<br />
I met someone earlier I really thought might be you... But even then it didn't fit perfectly. Then it blew up. Despite how much that hurt, I learned some things that really catapulted my growth and got me miles closer to finding you. You should be really grateful to Shelley for (a) helping me be better and (b) rejecting me and breaking my heart. I needed both of those to grow into the man you are going to fall for.<br />
<br />
I'm in bed, alone, I'm aching for you... But I refuse Counterfeits. I'm holding pillows and a soft blanket, petting your head. Telling you I love... And I don't even know your name.<br />
<br />
I've lived a broken past with women, sex, and love. But that led me to a path of healing, which led me to you.<br />
<br />
It may sound funny, but I've consistently asked God for someone who's past is broken like mine. If you're in another's arms tonight, even if he's a counterfeit, it's okay. You haven't failed me or you. I hope he brings you a little easing of the pain while you get ready for my arrival. I'm grateful to him because I know I'll stand out against the rest even brighter because of him. If you're alone... I'm coming. I can't wait to meet you.<br />
<br />
I need a nickname for you besides "her"... I'll have to pray about that, I'd bet Daddy had one that'll mean something to both of us. Wouldn't it be cool if I was calling you something you already identify with? I might even recognize you because of it?<br />
<br />
Hmmmm...<br />
<br />
For now, I love you. I believe in you! I'm exited to meet you. Our Daddy loves us so much, he's crafting the perfect plan.<br />
<br />
He told me to expect the Brady Bunch, a real partner, someone who would fit into our household without effort, someone so comfortable that it would be like she's always been here, and he's been using women in my life some romantic and don't not to show me what to look for and what to avoid...<br />
<br />
Rest well lover...<br />
<br />
Goodnight.<br />
<br />
<br />
<br />
<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a>&nbsp;(Myers-Briggs Type): INFJ</span></div>
