---
title: 'Notes: Boundaries and More'
date: '2019-06-23T08:02:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7557220972875263127'
blogger_filename: '/2019/06/notes-boundaries-and-more.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="http://ecosalon.com/couples-therapy-do-what-you-love-healthy-relationships/">http://ecosalon.com/couples-therapy-do-what-you-love-healthy-relationships/</a>  <o:p></o:p></div>
<div class="MsoNormal">
Couples Therapy: Doing What You Love Builds Healthy Relationships<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Pursuing your passions, particularly together, is good for your relationship.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
…pursuing passions together triggers the brain’s dopamine system, which in turn can sustain feelings of love and romance. In other words: find someone like you and adventure together.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="http://ecosalon.com/25-dating-dealbreakers-and-red-flag-271/">http://ecosalon.com/25-dating-dealbreakers-and-red-flag-271/</a>  <o:p></o:p></div>
<div class="MsoNormal">
25 Dating Dealbreakers and How to Spot Them<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
3. Has cut off all communication to family<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
We are perfectly understanding of strained familial relationships. It is a fact of human existence that all parents are flawed and we are all pissed off about it. No one’s perfect, and sometimes a break with those who are closest is what   we need. That’s different from complete and utter disconnect. Zero communication with family members is an indicator of larger issues at hand – the kind of larger issues that you don’t need to be dealing with.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
7. Two words: dental hygiene<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Brush twice a day, floss at least three times a week, and see the dentist now and then. That’s all we ask.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
15. Doesn’t understand your issue with his having a “best gal pal”<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
It isn’t your fear that he wants to sleep with her, but the fact that he is emotionally available to her and not you, which is why his repeated rantings about not wanting to sleep with her are so exasperating. Sleeping with you, confiding   in her means he is incapable of sexual and emotional intimacy with the same woman and will eventually cheat on whomever he marries.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
23. Has a filthy vehicle<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
You haven’t even been to his apartment yet but from the state of his car floor covered in candy wrappers, Coke bottles, chip bags and ATM receipts, you know for sure that not only is he disorganized, he’s a total pig who couldn’t even nice   up for your date.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="http://ecosalon.com/8-relationship-boundaries-you-should-never-cross/">http://ecosalon.com/8-relationship-boundaries-you-should-never-cross/</a><o:p></o:p></div>
<div class="MsoNormal">
8 Relationship Boundaries You Should Never Cross<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
1. Idealizing your mate:<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
The study found that idealized mates pull away both physically and emotionally, worried they won’t be able to live up to their partner’s expectations (especially when it comes to their abilities).<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
2. You initiate everything:<o:p></o:p></div>
<div class="MsoNormal">
3. You’ve adopted all of his interests:<o:p></o:p></div>
<div class="MsoNormal">
4. You include him in all of your plans:<o:p></o:p></div>
<div class="MsoNormal">
5. More of your belongings are at his place than your own:<o:p></o:p></div>
<div class="MsoNormal">
6. You feel less confident:<o:p></o:p></div>
<div class="MsoNormal">
7. Your bf wants you to re-connect with family and friends:<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
“It’s not uncommon for the partner in a ‘smothered relationship’ to express feeling some pressure to fulfill every emotional want and need, which can be extremely stressful and take its toll on your relationship,”<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
8. You text/IM him every 35 seconds:<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://theprayingwoman.com/3-boundaries-that-should-never-be-crossed-in-any-relationship/">https://theprayingwoman.com/3-boundaries-that-should-never-be-crossed-in-any-relationship/</a><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
3 Boundaries That Should Never Be Crossed In Any Relationship<o:p></o:p></div>
<div class="MsoNormal">
1. Disrespect<o:p></o:p></div>
<div class="MsoNormal">
Sometimes we become doormats in our relationships, hoping our loved ones will learn how to treat us better. We know we deserve better, but we timidly swallow our feelings for fear of pushing a loved ones away.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
2. Betrayal<o:p></o:p></div>
<div class="MsoNormal">
When trust is broken, it really doesn’t matter what the betrayal was because the effect is the same.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
3. Breaking Confidentiality<o:p></o:p></div>
<div class="MsoNormal">
When we are friends, we assume our secrets are safe. At some point or another, most of us have experienced the hurt and betrayal that occurs when someone we thought was a friend violates our trust, breaks confidentiality, uses information   told in confidence against us, and spreads private information.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://www.baggagereclaim.co.uk/stop-explaining-stop-justifying-stop-talking-boundaries-are-upheld-with-action/">https://www.baggagereclaim.co.uk/stop-explaining-stop-justifying-stop-talking-boundaries-are-upheld-with-action/</a>  <o:p></o:p></div>
<div class="MsoNormal">
Stop Explaining. Stop Justifying. Stop Talking. Boundaries Are Upheld With Action<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
1) They want to communicate the boundaries to someone that doesn’t respect boundaries. Pointless.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
2) They don’t want to do anything they just want say something. Also pointless.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
3) They want to ‘make’ people respect boundaries and they’re likely to be the types of people that they’d want to make love them and  <b>make them see their point of view</b>. <b>Pointless</b> – it’s like throwing your energy into the abyss or peeing into the wind.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://www.elitedaily.com/p/heres-how-to-stop-thinking-about-your-crush-according-to-experts-17912589">https://www.elitedaily.com/p/heres-how-to-stop-thinking-about-your-crush-according-to-experts-17912589</a><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Here's How To Stop Thinking About Your Crush, According To Experts<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Along with envisioning a new future, sit with all your feelings — even the not-so-pleasant ones, like hurt and disappointment. "Painful as it is, it is better to feel fully as part of the process of healing as opposed to suppressing, repressing   and avoiding feeling," Lee told Elite Daily. Dr. Gary Brown, a relationship therapist, also said that giving yourself time to acknowledge how you feel is a critical part of moving on. "Allow yourself to feel sad, to cry, to simply grieve the loss of something   that could have been," Dr. Brown said. But don't get stuck dwelling on the what-if's.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
The ability to have insight into our friends and faves' lives on the daily? A gift, truly! But that blessing turns into a curse when there are people who you shouldn't be checking up on — exes, haters, et cetera — for your own sake. As   Masini has said, "It's too easy to become an amateur stalker... That's a method of staying engaged, which won't help you get over your heartache."<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
So, don't do it. I know you want to look at your crush's cute lil face and check out what they're up to and daydream about being together. But don't! It's a trap that will only make you feel worse about the situation. You could unfollow   them, or take the less controversial route and mute them in the mean time.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Again, there's no need to be overwhelming negative toward your crush if you're trying to leave your romantic feelings behind. Instead, just focus on the qualities that make them a great addition to your crew. Take the romance out of your   interactions. See their friendliness (or even flirtiness) for what it truly is — being nice.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
There's a reason you were drawn to them in the first place and I'm willing to bet that each of those qualities are things you'd look for in any friend. And yeah, they might be... hot. But hot people need friends, too. And if you're up for   it, you're probably a good fit for the task.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://www.elitedaily.com/p/heres-how-to-set-boundaries-with-your-ex-according-to-9-women-who-have-done-it-15951554">https://www.elitedaily.com/p/heres-how-to-set-boundaries-with-your-ex-according-to-9-women-who-have-done-it-15951554</a><o:p></o:p></div>
<div class="MsoNormal">
Here's How To Set Boundaries With Your Ex, According To 9 Women Who Have Done It<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
My dad gave me the best ex advice I’ve ever heard: imagine yourself meeting up with him, and him telling you he’s dating someone new. If that wouldn’t bother you, you’re ready to be friends again. If that would upset you, you’re not over   him yet — so stay far, far away.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
There was one point when I was speaking to an ex who was emotionally dependent. A friend asked me one day if I was getting anything out of the communication with him — was it ever positive and was it ever benefitting me? When I realized   the answer was no, and that every interaction led to more emotional weight for me, I realized that the best act of love I could give myself was to end my communication with him. It was the only way I could move forward.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
My most recent ex played the ‘I’d still like to be friends, but I know that I’m the one breaking up with you, so ball is in your court if you ever want to reach out.’ So I set a timeline — I won’t even consider reaching out for at least   one month. (And I really, really wanted to message him a lot that first month, but I held myself accountable.) However, the first month passed, and then more time, and I realized I still don’t feel like reaching out. I’m thankful that he is sticking to his   end of the deal and not making the first move to reconnect and letting me wait until I am ready (if I am ever ready).<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
When I didn’t [set boundaries], it turned into a year of friendship and not getting over him. Once I finally stopped communication I was able to process it much better.  <b>Being friends is possible, but you need a break to really put a boundary around the ending of your relationship.<o:p></o:p></b></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://www.baggagereclaim.co.uk/understanding-code-red-and-code-amber-behaviour-in-dating-and-relationships/">https://www.baggagereclaim.co.uk/understanding-code-red-and-code-amber-behaviour-in-dating-and-relationships/</a><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Understanding Code Red and Amber behaviour in Relationships<o:p></o:p></div>
<div class="MsoNormal">
The chief problem that I come across time and again with people faced with code red behaviour is that we don’t do what we’re supposed to – opt out.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Addicted to something (FOCR)<o:p></o:p></div>
<div class="MsoNormal">
Married Or Attached (FOCR)<o:p></o:p></div>
<div class="MsoNormal">
Anger and aggression (FOCR)<o:p></o:p></div>
<div class="MsoNormal">
They play victim (FOCR)<o:p></o:p></div>
<div class="MsoNormal">
Not over the ex – (FOCR)<o:p></o:p></div>
<div class="MsoNormal">
Controlling<o:p></o:p></div>
<div class="MsoNormal">
Unresolved Problems with past/childhood<o:p></o:p></div>
<div class="MsoNormal">
Dodgy attitude towards sex (Value vs Use)<o:p></o:p></div>
<div class="MsoNormal">
Irresponsible – irresponsible with life in general – bills, rent, job and borrows money off you?<o:p></o:p></div>
<div class="MsoNormal">
Sleeping With Others<o:p></o:p></div>
<div class="MsoNormal">
Nasty and spiteful<o:p></o:p></div>
<div class="MsoNormal">
Emotionally Unavailable<o:p></o:p></div>
<div class="MsoNormal">
Bulk of communication by text and email etc<o:p></o:p></div>
<div class="MsoNormal">
They’re an assclown<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://www.baggagereclaim.co.uk/12-core-boundaries-to-live-by-in-life-dating-relationships/">https://www.baggagereclaim.co.uk/12-core-boundaries-to-live-by-in-life-dating-relationships/</a><o:p></o:p></div>
<div class="MsoNormal">
12 Core Boundaries To Live By in Life, Dating, &amp; Relationships<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
1. Under no circumstances will I date a married or attached person.<o:p></o:p></div>
<div class="MsoNormal">
2. I will not spend my time waiting around, whether it’s for their calls, or for them to show up after they’ve disappeared.<o:p></o:p></div>
<div class="MsoNormal">
3. I will not continue engaging in any relationship where either they (or I) don’t treat me with love, care, trust, and respect.<o:p></o:p></div>
<div class="MsoNormal">
4. I will not continue dating someone who reveals themselves to be a Future Faker or a Future Avoider.<o:p></o:p></div>
<div class="MsoNormal">
5. I will not date someone who controls the relationship on their terms. I must be in a mutually fulfilling, balanced, loving relationships.<o:p></o:p></div>
<div class="MsoNormal">
6. I will not allow someone to use me for sex, devalue me sexually, or treat me in a less than manner.<o:p></o:p></div>
<div class="MsoNormal">
7. I will drop guys who manage the bulk of the communication in our relationship by text, email, or instant messenger, like a hot potato<o:p></o:p></div>
<div class="MsoNormal">
There’s no excuse for this lazy communication, and it’s the hallmark of emotionally unavailable people who want to keep themselves distant. It’s not modern relationships and dating; it’s modern booty calls and half-hearted interest. It   says “I’m not interested enough to make a proper effort “..<o:p></o:p></div>
<div class="MsoNormal">
*** No texting all day every day with anyone. You are busy and have things to do. ***<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
8. I will not allow lies to foster my interactions.<o:p></o:p></div>
<div class="MsoNormal">
9. I will not pursue someone who has either directly or passively rejected me.<o:p></o:p></div>
<div class="MsoNormal">
10. I will not play Florence Nightingale. It’s not my job to fix/heal/help the Walking Wounded!<o:p></o:p></div>
<div class="MsoNormal">
11. I will not date an assclown: someone who is unkind/cruel, lacking in empathy, and at best takes advantage and at worst, abuses me.<o:p></o:p></div>
<div class="MsoNormal">
12. I will not make up excuses for other people’s behaviour or make exceptions to my boundaries. My boundaries are non-negotiable!<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://www.bustle.com/articles/133438-9-boundaries-you-need-to-set-up-in-your-relationship">https://www.bustle.com/articles/133438-9-boundaries-you-need-to-set-up-in-your-relationship</a><o:p></o:p></div>
<div class="MsoNormal">
9 Boundaries You Need To Set Up In Your Relationship<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
1. What You Can Call Each Other<o:p></o:p></div>
<div class="MsoNormal">
2. How You Will Fight<o:p></o:p></div>
<div class="MsoNormal">
How you will fight or settle disagreements is probably one of the most important boundaries you can set in a relationship. If one partner needs space when they're upset, that's an important boundary to acknowledge. You need to work together   to determine what is an appropriate way for you both to deal with your anger, and how you'll treat each other when you're mad. You also need to establish what each partner needs when they're sad, frustrated, etc.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
3. When You Get Alone Time<o:p></o:p></div>
<div class="MsoNormal">
4. How You Act On Social Media<o:p></o:p></div>
<div class="MsoNormal">
5. What You Share With Each Other<o:p></o:p></div>
<div class="MsoNormal">
6. How Often You'll Communicate<o:p></o:p></div>
<div class="MsoNormal">
7. What You Will And Won't Do For Each Other<o:p></o:p></div>
<div class="MsoNormal">
8. How You'll Have Sex<o:p></o:p></div>
<div class="MsoNormal">
9. How You Will Commit To Each Other<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://www.mindbodygreen.com/0-29215/why-cutting-off-all-contact-with-an-ex-is-the-only-way-to-move-on.html">https://www.mindbodygreen.com/0-29215/why-cutting-off-all-contact-with-an-ex-is-the-only-way-to-move-on.html</a><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Why Cutting Off All Contact With An Ex Is The Only Way To Move On<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Chasing xxx with a bunch of questions would not provide the answers Deidre desperately needs<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
It's true, going "no contact" is a bold move. But XXX was a drug in XXX’s system. It was time for her to detox—and reclaim her power.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
If you've been bawling your eyes out or hanging in limbo, it's time for radical change. During the first 60 days of no-contact (the minimum recommended time frame), you can expect the following:<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
1. It will suck.<o:p></o:p></div>
<div class="MsoNormal">
2. Your silence speaks so much louder than any words could.<o:p></o:p></div>
<div class="MsoNormal">
3. You will develop important emotional skills.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
No contact is a good time to develop better boundaries and increase your self-esteem. Abandon dysfunctional behaviors you learned in childhood. When you assess where you misstepped—and correct those behaviors—you have a much better probability   of success the next time around.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
4. You will rediscover forgotten sources of happiness.<o:p></o:p></div>
<div class="MsoNormal">
5. You'll be able to define your nonnegotiable values.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
What are your values? What are your must-haves? Here are some of my personal favorites:<o:p></o:p></div>
<div class="MsoNormal">
"I date partners who say 'I'm sorry' and own up to their mistakes."  <o:p></o:p></div>
<div class="MsoNormal">
"I date partners who believe in mutuality—where there is equal give and take."  <o:p></o:p></div>
<div class="MsoNormal">
"I date partners who believe in commitment and communication."<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
6. No contact will bring you back to reality.<o:p></o:p></div>
<div class="MsoNormal">
7. No contact will force some growth onto your partner as well.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
When you stop pinning your happiness on your partner, you realize it's just you in the world. No one will save you from your demons. It's your job to figure out why you were born and how to make your life rich with meaning.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://www.mindbodygreen.com/classes/28-days-to-your-best-relationship">https://www.mindbodygreen.com/classes/28-days-to-your-best-relationship</a><o:p></o:p></div>
<div class="MsoNormal">
Learn How To Build A More Confident You<o:p></o:p></div>
<div class="MsoNormal">
$39.99 USD <o:p></o:p></div>
<div class="MsoNormal">
WHAT YOU GET:<o:p></o:p></div>
<div class="MsoNormal">
•An exclusive workbook filled with Monica's lessons, activities, affirmations, and more<o:p></o:p></div>
<div class="MsoNormal">
•A 28-day journey that Monica's clients call "transformational"<o:p></o:p></div>
<div class="MsoNormal">
•Discussion boards to interact with fellow students<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://www.mindbodygreen.com/0-13176/6-steps-to-set-good-boundaries.html">https://www.mindbodygreen.com/0-13176/6-steps-to-set-good-boundaries.html</a><o:p></o:p></div>
<div class="MsoNormal">
6 Steps To Set Good Boundaries<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
1. Know this sad truth: NO boundaries = little self esteem.<o:p></o:p></div>
<div class="MsoNormal">
2. Decide what your core values are.<o:p></o:p></div>
<div class="MsoNormal">
3. You can't change others, so change yourself.<o:p></o:p></div>
<div class="MsoNormal">
4. Decide the consequences ahead of time.<o:p></o:p></div>
<div class="MsoNormal">
5. Let your behavior, not <b>your words</b>, speak for you.<o:p></o:p></div>
<div class="MsoNormal">
- This one is huge for me. Instead of going on and on about how you “wronged” me and “how could you”, I will share my hurt once. If not received I will simply go silent or walk away until such time as we can speak and be heard.  <o:p></o:p></div>
<div class="MsoNormal">
6. Say what you mean and mean what you say.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
This is key: Instead of creating your boundaries around a difficult relationship in your life, you must make your boundaries about you.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://thriveglobal.com/stories/how-to-set-boundaries-in-friendships/">https://thriveglobal.com/stories/how-to-set-boundaries-in-friendships/</a><o:p></o:p></div>
<div class="MsoNormal">
How to Set Boundaries in Friendships<o:p></o:p></div>
<div class="MsoNormal">
Sometimes the best way to be a friend is by looking out for yourself<o:p></o:p></div>
<div class="MsoNormal">
By Justine McGrath<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
1. Acknowledge what you’re feeling<o:p></o:p></div>
<div class="MsoNormal">
2. Decide how you want to handle the situation<o:p></o:p></div>
<div class="MsoNormal">
3. Choose your next course of action<o:p></o:p></div>
<div class="MsoNormal">
4. Stay firm in your conviction<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal" style="line-height: 125%;">
<b><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif;">Darrell Wolfe<o:p></o:p></span></b></div>
<div class="MsoNormal" style="line-height: 125%;">
<b><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 9.0pt; line-height: 125%;">Triage Associate | Account Protection  <o:p></o:p></span></b></div>
<div class="MsoNormal" style="line-height: 125%;">
<span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 9.0pt; line-height: 125%;">Alliance Data  </span><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif;"><o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: 125%;">
<span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 9.0pt; line-height: 125%;">751 W Hanley, Coeur d’Alene, ID 83815<o:p></o:p></span></div>
<div class="MsoNormal">
<a href="http://www.knowmoresellmore.com/"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">knowmoresellmore.com</span></a><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">   | </span><a href="https://www.linkedin.com/company/2973795?trk=tyah"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">LinkedIn  </span></a><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">|  </span><a href="https://www.facebook.com/KnowMoreSellMore"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">Facebook</span></a><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">  </span><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">|  </span><a href="https://twitter.com/know_sellmore"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">Twitter</span></a><span style="font-family: &quot;franklin gothic book&quot; , sans-serif;">  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
</div>
<br clear="both" />
______________________________________________________________________<br />
The information contained in this e-mail message and any attachments may be privileged and confidential. If the reader of this message is not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that any review, dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by replying to this e-mail and delete the message and any attachments from your computer.<br />
______________________________________________________________________