---
title: 'Dear Her'
date: '2019-07-26T08:44:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7518905406338130053'
blogger_filename: '/2019/07/dear-her_26.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Her'
---

One of the ways I'll recognize you is that you will appreciate all the work I'm doing to heal in this season.<br />
<br />
Everything in me wants to give up, stop growing, and go hide in the mountains. But the promise of your love for me as a reward at the end of this journey is so enticing, that I'm willing to push forward.<br />
<br />
It's not that I'm doing it for you, I'm doing it for me. But I'm doing it so I can be the me that attracts and retains a YOU.&nbsp;<br />
<br />
My heart is still broken. I saw a picture of Shelley and Scott having their First Kiss. She was supposed to be My Her. That was mine. She's given all the stuff she promised me to him. It hurts. But it just means, I remind myself, that she's not you. She's NOT my Her.<br />
<br />
So I'm letting that go, because when you show up, I'll forget she ever existed. It'll seem ridiculous to me that I even bothered being upset about Shelley when YOU were out there waiting for me.<br />
<br />
So I choose to wipe my tears, and close that door, and look forward to you.&nbsp; Please don't take forever. I'm trying to get ready for you. I'm going to counseling. I'm letting people call me on my BS. I'm letting them pull my covers and defense mechanisms.<br />
<br />
I'm pressing into healing so that when you show up, I'll be more than ready. I'll be the man you always dreamed of but didn't believe you'd find. I'll make all your Shelley's seem ridiculous too.<br />
<br />
You'll like the nerd and scholar who collects toys and enjoys dressing up for special occasions and wearing costumes for ComicCon and Ren Faire.<br />
<br />
I still don't know what to do with a Ministry Calling when I have such an antagonistic history with "The Church"... but I'm starting to see my calling may land outside those walls anyway.<br />
<br />
I bring that up because I realized recently that's another way I'll know you. You'll be as in love with Jesus as you are skeptical of church. Ha ha! What a strange pair we'll be. Or... maybe that'll all get healed and we'll both serve inside the church. I guess time will tell.<br />
<br />
I Love You!<br />
<br />
Darrell<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />