---
title: 'Reading List 2019 --Updates'
date: '2019-01-02T07:32:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3136115369464457715'
blogger_filename: '/2019/01/reading-list-2019-updates.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b><u>Fiction<o:p></o:p></u></b></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Author: Lauren Stinton (<a href="https://www.amazon.com/s?k=lauren+stinton&amp;ref=nav_signin">Affiliate Link</a>)<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal" style="margin-left: .5in;">
<a href="https://amzn.to/2NmzAd7">The House of Elah</a> (Volume 1)<o:p></o:p></div>
<div class="MsoNormal" style="margin-left: .5in;">
<a href="https://amzn.to/2Obqrn6">The Alusian's Quest</a> (The House of Elah) (Volume 2)<o:p></o:p></div>
<div class="MsoNormal" style="margin-left: .5in;">
<a href="https://amzn.to/2OisFku">The King's Man</a> (The House of Elah) (Volume 3)<o:p></o:p></div>
<div class="MsoNormal" style="margin-left: .5in;">
<br /></div>
<div class="MsoNormal" style="margin-left: .5in;">
<a href="https://amzn.to/306LLkO">Should I Choose to Die Again</a> (The Hamal Books) (Volume 1)<o:p></o:p></div>
<div class="MsoNormal" style="margin-left: .5in;">
<a href="https://amzn.to/30fIrmJ">The One-Eyed Man</a> (The Hamal Books) (Volume 2)<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b><u>Non-Fiction<o:p></o:p></u></b></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://amzn.to/2OchEl1">Leadership and Self-Deception: Getting Out of the Box</a>, by The Arbinger Institute  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://amzn.to/3331Ipt">Atomic Habits: An Easy &amp; Proven Way to Build Good Habits &amp; Break Bad Ones</a>, by James Clear<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://amzn.to/2OitdH4">Where Is God When It Hurts?</a>, by Philip Yancey<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://amzn.to/309Pxt3">Elements of a Christian Worldview</a>, by Michael Palmer<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://amzn.to/30yxo40">Saving the Bible from Ourselves: Learning to Read and Live the Bible Well</a>, by Glenn R. Paauw<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b><u>Author: C.S. Lewis<o:p></o:p></u></b></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://amzn.to/30e0oSE">Mere Christianity</a><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b><u>Author: Dr. Henry Cloud<o:p></o:p></u></b></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://amzn.to/2Obr9AM">How To Get A Date Worth Keeping: Be Dating In Six Months Or Your Money Back</a><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://amzn.to/2QuhR5U">Boundaries in Dating: How Healthy Choices Grow Healthy Relationships</a><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://amzn.to/32UxK6Y">Boundaries Updated and Expanded Edition: When to Say Yes, How to Say No To Take Control of Your Life</a><o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b><u>Author: Peter Scazzero<o:p></o:p></u></b></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://amzn.to/309ivJn">The Emotionally Healthy Leader: How Transforming Your Inner Life Will Deeply Transform Your Church, Team, and the World  </a>&nbsp;<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b><u>Other not otherwise catagoried<o:p></o:p></u></b></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://amzn.to/2LHMq3z">101 Conversation Starters for Couples</a> by Gary Chapman and Ramon Presson<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://amzn.to/2LCYoLK">Intellectual Foreplay: A Book of Questions for Lovers and Lovers-to-Be</a>, by Eve Eschner Hogan<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://amzn.to/30yx4Ck">41 Will Come: Holding On When Life Gets Tough--and Standing Strong Until a New Day Dawns</a>, by Tate, Chuck E.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<a href="https://amzn.to/2Oip3zj">The Hebrew-Greek Key Word Study Bible: NKJV Edition, Black Genuine Leather (Key Word Study Bibles),</a> by Publishers, AMG<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
</div>
<br clear="both" />
______________________________________________________________________<br />
The information contained in this e-mail message and any attachments may be privileged and confidential. If the reader of this message is not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that any review, dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by replying to this e-mail and delete the message and any attachments from your computer.<br />
______________________________________________________________________