---
title: 'Her: A List'
date: '2019-05-22T19:13:00.0040000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7532783313809335610'
blogger_filename: '/2019/05/her-list.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

In this moment of self-reflection… another round of disillusionment behind me… I am compelled to ask what I want. What am I expecting to find? Who is “she” going to be? Are there things that I want that aren’t God’s design for me? Or, are my desires placed there by God, in concert with his gifting’s, and therefore they are wholesome and good, even if quirky and odd? <br /><br />Therefore, I’m not saying the following are all deal breakers, but I I find myself compelled to yet again ask the question: What do I want in my future spouse?<br /><br />The Answers, as they occur to me, not necessarily in priority order:<br /><br />MUST<br /><br />She loves God, God’s Word, Prophetic Gifts and Gifts of the Spirit; however, she is raw and authentic in them. Not Hyper-Spiritual. <br /><br />She understands Freedom Ministry / Kairos.<br /><br />EASY: It has to be easy. Misunderstandings, conflicts, I don’t want any of that. I’d literally rather just stay single. Conflict is inevitable, for sure, but it should be resolved by calmly talking it through, arriving at a mutually satisfactory conclusion without hiding or shrinking back. <br /><br />Affirmation &amp; Respect: She’s got to affirm me, not knock me down. Teasing is okay, gently, but it must be affirming. Maybe I’ll grow past this, but I am just too damn sensitive for anyone who’s going to poke fun at, jab, or be abrasive. <br /><br />Brady Bunch: She LOVES my children as though they were hers, and I her children. Her love for my children will have them asking me to marry her and bring her home.<br /><br />SAFE SPACE: I can be totally open in her presence. Vulnerable. I can let out the darkest thoughts in my heart and they don’t scare her, she leans-in during those moments, and embraces me and assures me that those thoughts are not mine but the enemies and chases them away in perfected-love.<br /><br /> <br /><br />Probably a must:<br /><br />Brady Bunch 2.0: Likewise, our children will love each other as well, enjoy spending time with one-another, etc. That being said, they’re probably similar ages? Maybe? I don’t know.<br /><br />SOFT Personality. Someone who will call me on my BS but do so in a way that calms me. Being around her brings my blood pressure down.<br /><br /> <br /><br />Prefer, I think maybe I’d prefer:<br /><br />A writer. Someone for whom fiction writing is a hobby and passion already.<br /><br />A Geek &amp; Nerd, and she knows the difference. Someone to go to ComicCon and Ren Faire’s with, someone who enjoys theater, movies, Marvel Fan, Star Trek Fan, probably a Pokemon Fan(ish)… etc. She’s got her own Action Figure (toy) Collection. She probably owns a few fun outfits!<br /><br />God, is this wrong?&amp; Kinky but wholesome. Sexually wide-open, but committed to monogamous relationship within God. Enjoys fun, new exciting, tantric and ties. Etc. <br /><br /> <br /><br />Probably the wrong thing to ask… but it’s on my heart… maybe this will change:<br /><br />Sex. She’s not waiting for marriage. She knows we “should”, but she doesn’t want to, we’ve been married before, she doesn’t want to be stuck in an incompatible relationship. She’s even okay with the idea of being quasi-married for a while before we actually get married. <br /><br /> <br /><br /> 