---
title: 'Hannah Hardisty | Youth Pastor for New Life Church in Rathdrum'
date: '2019-06-21T16:50:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2163481220361528552'
blogger_filename: '/2019/06/hannah-hardisty-youth-pastor-for-new.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

Hannah Hardisty | Youth Pastor for New Life Church in Rathdrum<br />
<br />
<br />
<br />
<br />
You got it!<br />
<br />
How long have you been doing Youth Pastor? Youth pastor 2.5 years. Worship pastor 4 years.<br />
<br />
Do you have any formal degree in ministry? No. I did do a 2 year ministry internship and I have a Bachelors of Science in Child Development and Family Relations.<br />
<br />
Are you paid full time staff or do you have a separate career as well? I am a full time Pastor.<br />
<br />
Are you and Michael(?) as a couple both the Youth Pastor or is it formally you? It is me. Michal and I serve together as a family decision, but I am the youth pastor.<br />
<br />
Are you at the church forty hours? What does you day look like? Yes- I work 40+ hours- some meetings are outside of the church. My days are filled with: supervising other staff, planning events, writing curriculum, developing leaders, worship ministry strategy and connection, youth ministry strategy and connection, community connection, and all kinds of administrative tasks.<br />
<br />
Hope that helps!<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />