---
title: 'Dear Her 08/13/2019'
date: '2019-08-14T09:41:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2769822281781854888'
blogger_filename: '/2019/08/dear-her-08132019.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Her'
---

<div class="WordSection1">
<div class="MsoNormal">
Dear Her,<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
It’s been a hard week. I’m listening to Dr. Clouds advice and dating with the purpose of keeping my mind open, having new experiences with new people, and not pigeon holing myself into a “type”. So far, a month and a half in, that’s resulted   in two dates I didn’t really want but forced myself to go on. Both were more interesting (intellectually) than I expected but exactly as unromantic as I expected. I’ve had two dates schedule and then cancel the day of with “got called into work”.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I had a fifth date scheduled two nights ago, Sunday 08/11/2019, and she became the third to cancel with having to go into work. However, she texted after and we talked for three hours. We connected well enough by text I wonder if she’s   as fascinating as my imagination is trying to make her. But her passion for raw honesty and real people tugs at my heart. It would be interesting if she’s you, but I almost hope not, because then we have a year still before I can commit to you. Ha ha… Then   again, maybe we need that year to know each other’s minds before we engage our hearts. I kind of don’t think she’s you; only because, she is very reserved. Someone who doesn’t even have a profile photo on Facebook marrying someone who literally publishes their   life story online probably isn’t a match? Then again, maybe she’ll come out of her shell some and I’ll learn to hold more back? Who knows.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I hope you don’t mind if I admit it… but I want to be held so badly right now. I would settle for one of those counterfeits if I could just be held. But even then, I’m feeling pathetic. So far the apps have revealed rude girls or scams   or ones that don’t reply. Only a few conversations that amounted to nothing (other than the ones mentioned above). My friend T is out there getting dates and offers for hookups. Uhg.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I felt more confident before She Who Shall Not Be Named showed me how little I can be worth. Now I go on the apps and groups and the only ones who want me feel like aunts and OLDER sisters… Uhg.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Where are you? Sorry to complain. But I thought I heard God say you were coming soon. His idea of soon is different than mine.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Despite my complaints, I’m trying to grow. You are the only reason I’m still seeing my counselor. Because I really want to be the best me I can be when you arrive. If I didn’t think you were out there, I’d save the money, settle for a counterfeit   now and then, and settle for mediocrity. But my gut says you ARE out there, and you’re amazing, and you are inspiring, and you are worth me keeping up this painful growth trajectory, because you’re worth it!  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
So I’m pushing ahead, I hope you’re really out there. Please be real. Lol…  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I love you,<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
You’re future Him,<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Darrell<span style="font-family: &quot;franklin gothic book&quot; , sans-serif;">  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
</div>
<br clear="both" />
______________________________________________________________________<br />
The information contained in this e-mail message and any attachments may be privileged and confidential. If the reader of this message is not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that any review, dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by replying to this e-mail and delete the message and any attachments from your computer.<br />
______________________________________________________________________