---
title: 'Endings Indicator'
date: '2019-06-21T16:18:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6347685326881881605'
blogger_filename: '/2019/06/endings-indicator.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">
<div class="MsoNormal">
You know you’re not doing endings and new beginnings well when…<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoListParagraph" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: &quot;symbol&quot;;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;You can’t stop ruminating about something in the past.<o:p></o:p></div>
<div class="MsoListParagraph" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: &quot;symbol&quot;;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;You use busyness as an excuse to avoid taking time to grieve endings and losses or to allow for the possibility that you might meet God in the process.<o:p></o:p></div>
<div class="MsoListParagraph" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: &quot;symbol&quot;;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;You avoid acknowledging the pain of your losses rather than (1) grieve, (2) explore the reasons behind your sadness, and (3) allow God to work in you through them.<o:p></o:p></div>
<div class="MsoListParagraph" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: &quot;symbol&quot;;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;You often find yourself angry and frustrated by the grief and pain in life.<o:p></o:p></div>
<div class="MsoListParagraph" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: &quot;symbol&quot;;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;You escape or medicate the pain of loss through self-destructive behaviors such as overeating, use of pornography, inappropriate relationships, substance abuse, over engagement with social media, or working too much.  <o:p></o:p></div>
<div class="MsoListParagraph" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: &quot;symbol&quot;;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;You struggle with the envy you feel toward those who don’t seem to be hit by the same hardships in life that you experience.  <o:p></o:p></div>
<div class="MsoListParagraph" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: &quot;symbol&quot;;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;You often dream of quitting in order to avoid the pain, disappointments, setbacks, and endings that routinely characterize leadership.<o:p></o:p></div>
<div class="MsoListParagraph" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: &quot;symbol&quot;;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;You are not honest with yourself about the feelings, doubts, and hurts deep beneath the surface of your life.<o:p></o:p></div>
<div class="MsoListParagraph" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: &quot;symbol&quot;;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;You rarely acknowledge directly that a program or person has outright failed. You avoid that pain by spinning the truth and glossing over the losses, disappointments, and struggles.  <o:p></o:p></div>
<div class="MsoListParagraph" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
&lt;![if !supportLists]&gt;<span style="font-family: &quot;symbol&quot;;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span>&lt;![endif]&gt;You rarely think about change in your role or position because you dislike change.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal" style="line-height: 125%;">
<b><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif;">Darrell Wolfe<o:p></o:p></span></b></div>
<div class="MsoNormal" style="line-height: 125%;">
<b><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 9.0pt; line-height: 125%;">Triage Associate | Account Protection  <o:p></o:p></span></b></div>
<div class="MsoNormal" style="line-height: 125%;">
<span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 9.0pt; line-height: 125%;">Alliance Data  </span><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif;"><o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: 125%;">
<span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 9.0pt; line-height: 125%;">751 W Hanley, Coeur d’Alene, ID 83815<o:p></o:p></span></div>
<div class="MsoNormal">
<a href="http://www.knowmoresellmore.com/"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">knowmoresellmore.com</span></a><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">   | </span><a href="https://www.linkedin.com/company/2973795?trk=tyah"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">LinkedIn  </span></a><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">|  </span><a href="https://www.facebook.com/KnowMoreSellMore"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">Facebook</span></a><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">  </span><span style="color: #1f497d; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">|  </span><a href="https://twitter.com/know_sellmore"><span style="color: #0085ad; font-family: &quot;franklin gothic book&quot; , sans-serif; font-size: 10.0pt;">Twitter</span></a><span style="font-family: &quot;franklin gothic book&quot; , sans-serif;">  <o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
</div>
<br clear="both" />
______________________________________________________________________<br />
The information contained in this e-mail message and any attachments may be privileged and confidential. If the reader of this message is not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that any review, dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by replying to this e-mail and delete the message and any attachments from your computer.<br />
______________________________________________________________________