---
title: 'Prayers and Ponderings... Shelley'
date: '2019-06-21T16:19:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7583908789397183121'
blogger_filename: '/2019/06/prayers-and-ponderings-shelley.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">
<div class="MsoNormal">
I miss her. It aches in my chest, it’s heavy. It hurts. It’s like a Shelley sized hole that won’t fill. Despite that, she’s rejected me. So I’ve rejected her. I’m going to go about my life as I see fit. Am I self-justifying? Maybe. Do I   care. A little. Do I wish things were different, heck yes. Can I change what happened or where we are now? Not even a little. I know God can make a way where there seems to be no way… but I see NO WAY to get from here back or forward into anything resembling   a close friendship without me just wishing it was more… and no way to get to a place of more. It’s dead. That’s what it is. I wish I’d just stopped talking to her on April 11<sup>th</sup>. Let her go be. Then MAYBE I could have come back after her sabbatical   without mortal wounds. Now, I just don’t see that happening for me. I’ll never trust her, and she’ll be skittish around me. Just another in a long line of Darrell’s screw ups.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Despite that… in prayer today… God’s asked me to pray for her. I’m like, “Jesus!!!!!??!?!?! I’m doing my best to forget her, how I can pray for her? You want me to think about her more?<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div style="border-bottom: dotted 3.0pt; border: none; padding: 0in 0in 1.0pt 0in;">
<div class="MsoNormal" style="border: none; padding: 0in;">
<br /></div>
</div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Our Father… who’s? Mine AND Shelley’s. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Who art in heaven… in the place where true perspective resides. He can help me see Truth, and her see it too. He can help us see each other and heal this hurt.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Hallowed (Holy) is your name… you are set apart. If we both honor your name, he can heal this.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Thy Kingdom Come… it’s already here in our hearts. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Thy Will Be Done… not mine. Not hers. His Will. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
On earth, <i>in our lives</i>, as it already is in heaven.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Give us THIS day… I can’t do anything about yesterday or tomorrow<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Our daily bread… just enough for today.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Lead us not into temptation… I will look to my Noble Self and turn from my Fearful Self<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Deliver us from Evil… Even if evil comes, even if it ends up working through us temporarily… he can deliver us and fix it.<o:p></o:p></div>
<div style="border-bottom: dotted 3.0pt; border: none; padding: 0in 0in 1.0pt 0in;">
<div class="MsoNormal" style="border: none; padding: 0in;">
<br /></div>
</div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Daddy… *<b>sigh</b>*… I lift up Shelley, my sister, your daughter, before you now.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I first want to apologize for not submitting my emotions to you instead of her. That’s what she was trying to tell me. OH! I was burdening her with my emotions when I should have been bringing them to you first, letting you deal with them,   and then taking only things to her as you instructed me. I violated your word several times by not doing this. You even said “she can’t hear you” and I pushed on through anyway.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Second, I ask you to heal any wounds she has, especially those I caused. Resolve her triggers, impart peace and joy. Give her healthy dating experiences. Introduce her to men of God of a variety of ages and backgrounds that will help her   see how a healthy man can treat her, without using her body as their toy.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Third, I ask you to protect her from evil men with evil intentions. I ask you to protect her from men, like me, who want to drain her out of their need instead of filling her out of service of overflow.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Fourth, I ask you to remove me, permanently if needed, from her life if I cannot be the influence you originally intended for me to be.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Fifth, I ask you to heal the hearts of her children. Heal the triggers and wounds and remove the spiritual influences. I ask you to remove Stupid from the equation.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Finally, I ask you to bring her into a place where she is fully healed, delivered, and set free… then bring a man into her life that can love her the way I wanted to but failed to live up to.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
I release her into your hands. I understand she is your daughter and I mishandled her. I understand if you choose to protect her by never letting her come back into my life. I also know you love me so much you’d be protecting me from further   pain. I give my will over to you. I lay it down at your feet. I forfeit my rights to you and submit to your will.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
My heart is still hurting, crying, and begging but I choose to submit instead.  <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Selah<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
Darrell<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br /></div>
</div>
<br clear="both" />
______________________________________________________________________<br />
The information contained in this e-mail message and any attachments may be privileged and confidential. If the reader of this message is not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that any review, dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by replying to this e-mail and delete the message and any attachments from your computer.<br />
______________________________________________________________________