---
title: 'Reflections from Thursday 11/21'
date: '2019-11-22T09:23:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5657839175098787491'
blogger_filename: '/2019/11/reflections-from-thursday-1121.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<br />
Boundaries, Pages 260-263:<br />
<br />
"Jeremy," thought he loved God until he was forced to admit that he loved his affairs more than God's rules. Once he allowed this honesty, he could see himself for who he really was. It was not until this shift, that years of affairs ended, and his real Journey to healing began.<br />
<br />
That's my No Hiding story almost exactly.<br />
<br />
Paul's Thorn / Jesus' Cup... I've never tied those two together before. There will be times where God's boundaries require that he tells us "no". It may be to take something from us, prevent something we're about to walk through or to give us something we've asked for. He has healthy boundaries too.<br />
<br />
I must become willing and eager to hear God's "NO!", for in it, I find the edges of his Boundaries and his great love for me. I also find a hidden blessing underneath, for many of the things I'd asked him for were toxic for me, in hindsight. Some were simply out of his and my control, subject to a third party's will.<br />
<br />
I'm so grateful that Shelley told me no. She could have done it in a more loving way, that nurtured and stewarded out friendship. Her cryptic non-responses were and are unacceptable to me. Since she's unwilling to see how that hurt me, there's no reconciliation. Reconciliation requires change. It's too bad. There were parts of her friendship that may have been helpful. I also must own that I was unhealthy for her too and that together with our mixture of wounds created a toxic environment. It is what it is. I'll be grateful for the lessons, even the gift of rejection. I learned to stand on my own, but seek community in healthier ways, mostly. Nevertheless, forgiveness and even gratitude need not involve reconciliation. For that, she has to see how her behavior was hurtful, even if unintended, and sincerely own that and apologize for it. Since that couldn't happen, we had to part ways.&nbsp; Now that I'm free of that relationship, and I see how even the "good days" were toxic and unhealthy, unboundaried, I'm grateful for the lessons but I have no desire to return or start over. She can go on her journey and me on mine. I was a little tempted to send a birthday greeting this Sunday, but as she said for mine, it would do more harm than good. I said my goodbye. It was final. I'll ler her new "husband" however long he lasts, handle her birthday. Okay, that was a little bitter, but it's an honest assessment. It won't last. The question is, when it falls apart, and without divine intervention is will, will she come back and talk to me, and will I let her? Currently, I don't think I will even if she does.<br />
<br />
Wow, still have some of that in there I guess.<br />
<br />
Looking forward, but with that lesson in mind, it was nice to feel "known" in a way I hadn't before. That's why it hurt to let her go. But obviously, she didn't know me, or didn't care, or she wouldn't have treated me that way.<br />
<br />
So how do I handle relationships going forward, as I'm dancing with various partners until I find "her". I guess the Boundaries book has some answers for that too.<br />
<br />
I must be willing to say no, and hear no. She must too. I should practice saying "no" to a phone call at night when the kids need me. Things like that. Make sure my priorities stay on them, even if things get serious. And direct her to her own kids too.<br />
<br />
Despite Carla's prophecy the other day... and Joseph/Heather's reaffirmation of the SAME exact sentence "God's got a wife for you". That's twice now.<br />
<br />
I feel less willing to meet her than I ever have. Maybe that's good. It's about where I was when God pointed out Flavia.<br />
<br />
I want to be the best me I can be. I'm even feeling like I might be ready to start a group soon.<br />
<br />
But I also can't fathom doing anything while my schedule and finances are so chaotic. Time will tell, I suppose.<br />
<br />
Theresa and I have kept a distance this past two weeks. I don't know if it was on purpose for her. I just got busy. I send her things. But it's short quips. I'm feeling the need to pull back from her. Let her fly on her own, find her guy. I need to focus on me, my website, etc. I need to call the school too! Eeeks! Start counseling for classes.<br />
<br />
Time for bed.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />