---
title: 'Pain is Good'
date: '2019-07-26T08:34:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8984676112075912270'
blogger_filename: '/2019/07/pain-is-good.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Shelley'
---

<br />
<br />
Processing my Shelley Rage:<br />
<br />
<br />
<ul>
<li>07/24: a picture of their first kiss made my full of rage I could hardly contain.&nbsp;</li>
</ul>
<div>
<ul>
<li>07/25</li>
<ul>
<li>The counselor talked me off the ledge. Along with Theresa and Kate.&nbsp;</li>
</ul>
</ul>
<div>
<br /></div>
</div>
<div>
To Darrell's Wounded Self</div>
<div>
From Darrell's Noble Self</div>
<div>
<br /></div>
<br />
<div>
<ul>
<li>YOU saw her Facebook handle change from SteveandShelleyHunter to ShelleyHunter and YOU initiated contact.</li>
<li>YOU pressed, re-pressed, and re-pressed for her phone number until she gave it to you.</li>
<li>YOU bought marriage books/questions at her suggestion.&nbsp;</li>
<li>YOU told her you didn't have the right to ask her to commit to you until you'd earned it... you never did.&nbsp;</li>
<li>----Everything was looking good until she had to split on 04/10/2019 and God TOLD you she'd need to on 03/01/2019. He gave you a month to detach and you got further in instead.----</li>
<li>YOU risked and YOU got hurt from that risk.&nbsp;</li>
<li>YOU need to take responsibility for that risk and the hurt that gave from that investment. All investments come with inherent risk, you know this in finance, it's true in love. Sometimes you make an investment that seems right and you still lose your principal.&nbsp;</li>
<li>Shelley Hunter is NOT responsible for YOUR pain, YOU are responsible for your pain and YOUR healing.&nbsp;</li>
</ul>
<div>
*** Pain is a signal that something is wrong*** "Where is God when it hurts?" Philip Yancy</div>
</div>
<div>
<br /></div>
<div>
Darrell, have you ever gotten mad at the KNIFE when you cut your finger cooking? NO? Then why are you mad at LOVE when you got hurt by a romance? It's just a tool.&nbsp;</div>
<div>
<br /></div>
<div>
Leprosy Patients die and become permanently disabled from an inability to react from this simple lack of ability to feel pain.&nbsp;</div>
<div>
<br /></div>
<div>
A wound in the hand/finger after handling a kitchen knife incorrectly is a signal that the hand/finger now needs attention.&nbsp;</div>
<br />
Even IF someone else deliberately cut your hand and wounded you, the wound and associated pain is still yours. They are YOUR signal that YOU are hurt and YOU need healing.<br />
<br />
YOUR pain isn't a signal to the wounder at all, it's a signal to you to escape, protect, fix, and heal.<br />
<br />
A wound in the heart is the same. It hurts, has pain. That pain tells you that a wound exists.<br />
<br />
Even IF someone else deliberately wounded your heart, the pain isn't a signal of anything other than YOUR wound in YOUR heart. It's a signal that YOUR heart needs to be protected and healed... it's a signal of a wound in YOUR heart that needs YOUR attention.<br />
<br />
You can learn from pain. Learn to better calculate your risks, watch for danger signs (red flags), be more cautious when playing with Knives, Fire, or Love. You cannot really live without risk, you can only mitigate that risk to mitigate the possibility of injury or the severity of it.<br />
<br />
You cannot get mad at the knife/love, it's just a tool. Mitigate your risks, and get back in the kitchen and start cooking.<br />
<br />
<br />