---
title: 'Pastor Ray Duran'
date: '2019-06-21T15:13:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8111914611189397166'
blogger_filename: '/2019/06/pastor-ray-duran.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

Pastor Ray Duran has been in ministry for 40 years primarily within the Calvary Chapel movement. He has served on staff for or been associated with well-known leaders in the Body of Christ, such as Raul Ries, Jack Hibbs, Jon Courson, Greg Laurie. Ray is an unassuming man, humble, and down to earth. He goes where God sends him and does what God says to do, even if it doesn't seem logical or might not "work" from a worldly point of view.<br />
<br />
In one instance, he moved to a city and started a church just to see one young woman radically saved and that was enough for him. He moved on from that church after two years and left it in good hands.<br />
<br />
During a visit with his son, living in the North Idaho/Eastern Washington area, he passed an old man in tattered clothes sitting outside a restaurant. He'd just told his family to go to the car while he paid the bill then walked out on his own. The old man was still sitting on the bench. He had long white hair and a white beard, and he clung tightly to an old tattered bible.<br />
<br />
The old man waved him over, "This is my Bible".<br />
<br />
"That's good brother," Ray said.<br />
<br />
"You're going to start a church over there," he said and pointed to the area of Ottis Orchards. "In the valley."<br />
<br />
Ray put that away but pondered it in his heart. On the way back to California, he visited some old friends and they too gave him a word that he'd be moving soon.<br />
<br />
When he returned back to his home and went into his office, Jack Hibbs walked up to him and said: "You'll be leaving us soon."<br />
<br />
Eventually, Ray and his wife Bertha moved to North Idaho. They served faithfully at Candlelight Church and were eventually asked to start a Spanish Speaking congregation within the church. Spanish speakers often inquired about services, the only Spanish speaking congregation was in the local Catholic Mass services, only held twice a month. Ray is fluent in Spanish, but it's not his first language and he never felt qualified to preach in Spanish. Although he did many ministry trips to Spanish speaking nations, he always used an interpreter.<br />
<br />
"I have always had a love for Hispanic people," Ray said. "There are quite a few Latin people moving to the area and there are people looking for Spanish Bible studies."<br />
<br />
"I prayed about it a lot and finally said 'OK let's go ahead and do it,'" Duran said. "It's a challenge, but it's also a blessing and an honor to teach the Bible to Hispanic people."<br />
<br />
Ray, who was born in New Mexico, said many Latinos are turning to nondenominational churches like his as part of the charismatic renewal.<br />
<br />
The 2007 Pew study found that 15 percent of U.S. Hispanics identified as born-again or evangelical Protestant, 5 percent mainline Protestant and 3 percent other Christian, such as Mormon or Jehovah’s Witness.<br />
<br />
Ray said that when he was Catholic, he “never really had an experience with the Lord one-on-one.” He said many Latinos converting to charismatic or evangelical faiths are asking why this is. “Once they have a relationship like this with the Lord, there is no going back,” Ray said.<br />
<br />
Approximately 6-7 years ago, he felt led of the Lord to travel to an area in Western Washington called Ottis Orchards (mostly farms and small communities). He drove to all four corners of the area, North, South, East, and West, praying for the people in the houses, farms, and businesses.<br />
<br />
In 2013, he began to meet monthly with other pastors from the area, praying for God's will in the region. In 2014, he held a Night of Praise in the building that would eventually be their new home, though he didn't know it at the time. In 2015, he organized another Night of Praise in a different location with the pastor who would eventually lead him to his church's new home.<br />
<br />
In 2019, he was contacted by Pastor Gary and informed that the building was open and asked if he would consider planting his new church there. He opened the doors and his small start-up congregation began cleaning and making repairs and meeting on a weekly basis, among the first weekly Spanish speaking services in the region. He is still early in this project and he is serving faithfully. Instead of rushing or fretting to make things work, he simply walks humbly with his God and takes one day at a time. In lieu of a Worship Pastor, he plays songs through the computer on the overhead screen until God provides someone to come alongside.<br />
<br />
Ray lives by a simple Mantra: If they don't know (Jesus), I want them to know (Him). And that's what he's doing, one soul at a time.<br />
<div>
<br /></div>
References to articles written about this move of God recently:<br />
<br />
<a href="https://www.cdapress.com/archive/article-85ee1401-483f-5a1d-9a61-4a1b3ac58159.html">https://www.cdapress.com/archive/article-85ee1401-483f-5a1d-9a61-4a1b3ac58159.html</a><br />
<br />
<a href="http://www.spokesman.com/stories/2013/dec/25/new-area-church-services-oriented-toward-latinos/">http://www.spokesman.com/stories/2013/dec/25/new-area-church-services-oriented-toward-latinos/</a><br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<a href="https://www.cdapress.com/archive/article-85ee1401-483f-5a1d-9a61-4a1b3ac58159.html">https://www.cdapress.com/archive/article-85ee1401-483f-5a1d-9a61-4a1b3ac58159.html</a><br />
<br />
IN THEIR OWN LANGUAGE<br />
LOCAL CHURCH SERVICES OFFERED IN SPANISH<br />
December 28, 2013 at 5:00 am | KEITH COUSINS/Staff writer<br />
<br />
&nbsp;Print Article<br />
<br />
COEUR d'ALENE -<br />
<br />
Spanish-speaking Christian churchgoers in North Idaho will soon have a weekly opportunity to practice their faith together, in their native language.<br />
<br />
Beginning Jan. 5, Candlelight Christian Fellowship in Coeur d'Alene will offer a new Sunday morning church service called "Candlelight Hispanic Fellowship: The Love of Calvary."<br />
<br />
Pastor Paul Van Noy said he receives many inquiries from people seeking Spanish-language church services in the community.<br />
<br />
"We want to serve and meet the needs of this community, and there are quite a large number of people that are interested," Van Noy said.<br />
<br />
For the past few years, the only regular Spanish-language worship option in the area has been a Catholic Mass held twice a month at St. Pius X Church in Coeur d'Alene.<br />
<br />
To begin serving the Hispanic community at Candlelight Christian, Van Noy turned to longtime staff member Ray Duran.<br />
<br />
Duran, who is originally from New Mexico and was ordained in California, works at the church as a pastoral counselor.<br />
<br />
He has worked in ministry for 40 years, and prior to his move to Coeur d'Alene 20 years ago, he spent time flying to Mexico to train pastors.<br />
<br />
"I have always had a love for Hispanic people," Duran said. "There are quite a few Latin people moving to the area and there are people looking for Spanish Bible studies."<br />
<br />
When Duran was approached three months ago about leading the services, he said he needed some time to think it over.<br />
<br />
"I prayed about it a lot and finally said 'OK let's go ahead and do it,'" Duran said. "It's a challenge, but it's also a blessing and an honor to teach the Bible to Hispanic people."<br />
<br />
Duran said his services will take a "systematic" approach to studying the Bible by going chapter by chapter through the various books, adding that the services will also be bilingual.<br />
<br />
"We didn't want to hinder anyone from attending the service," Duran said. "So the worship and message will be in both Spanish and English."<br />
<br />
The Spanish language services will be held at Candlelight Christian Fellowship at 10:45 a.m. Sundays at the church, 5725 North Pioneer Drive.<br />
<br />
St. Pius X Catholic Church's Spanish-speaking worship services are held at 12:30 p.m. on the first and third Sundays of each month.<br />
<br />
<br />
<a href="http://www.spokesman.com/stories/2013/dec/25/new-area-church-services-oriented-toward-latinos/">http://www.spokesman.com/stories/2013/dec/25/new-area-church-services-oriented-toward-latinos/</a><br />
<br />
New area church services oriented toward Latinos<br />
Wed., Dec. 25, 2013<br />
By Kevin Graman<br />
Senior correspondent<br />
<br />
The Rev. Alvaro Gomez welcomed two new families to his small Pentecostal congregation in Spokane Valley on a recent Sunday afternoon.<br />
<br />
“Bienvenidos a la casa del Señor,” said Gomez, pastor of the Church of God of Prophecy.<br />
<br />
His words were immediately interpreted by a Mexican-American congregant standing alongside Gomez, an evangelical minister from Guatemala.<br />
<br />
“Welcome to the house of the Lord.”<br />
<br />
The new families – political refugees – had just arrived a few days before from Cuba, and were eager to connect with the 60 or 70 Spanish-speaking faithful who meet in space borrowed from another church.<br />
<br />
As the Latino population continues to rise in the Spokane area, a growing number of Spanish-language religious services are emerging to accommodate their distinctive form of spirit-filled and Latino-oriented Christianity.<br />
<br />
Nearly 807,000 Latinos now live in Washington, more than 23,000 of them in Spokane County, accounting for 4.9 percent of the county’s population.<br />
<br />
While more than two-thirds of U.S. Latinos identify as Roman Catholic, 39 percent describe themselves as either “born again” or “evangelical” whether or not they remain Catholic, according to a study by the Pew Hispanic Center and the Pew Forum on Religion and Public Life.<br />
<br />
As Latino numbers reach 17 percent of the total U.S. population and climbing, many are choosing a distinctly ethnic religious experience with Latino clergy, Latino congregations and liturgy in Spanish.<br />
<br />
“People are looking for something new,” said Gomez, who came to the United States to study theology 16 years ago. “They want to live a different kind of life closer to God.”<br />
<br />
Since establishing his ministry in his garage several months ago, Gomez and his wife, Leslie, have seen the congregation grow to about 120 people who now meet in the Intersection church in Spokane Valley. Some of the congregants were born in the United States. Others are immigrants from Mexico, Puerto Rico and Cuba, as well as Central and South America.<br />
<br />
The Bible-based service is punctuated by rock-based music – keyboard, drum and electric guitar – accompanying lyrics filled with references to the Holy Spirit. Congregants raise their arms or wave flags to symbolize the Spirit passing through them.<br />
<br />
Gomez preaches of the transformative power of prayer to congregants, many of whom believe in the real possibility of miracles, healing and divine intervention in their lives.<br />
<br />
Gomez said he knows of four other charismatic or evangelical religious groups, of 30 or 40 people each, attending Spanish-language services in Spokane and Spokane Valley.<br />
<br />
Among those welcomed to Gomez’s church recently was the family of Jose Luis and Thaimy Sanchez, Cuban refugees brought to Spokane in November by World Relief, the humanitarian arm of the National Association of Evangelicals.<br />
<br />
Sanchez, who was a Baptist minister at home in Pinar del Rio, Cuba, said his family had “a very hard life” there because of the nation’s poor economy and religious discrimination.<br />
<br />
“I came here to work and to learn, and I hope one day to have my own church,” Sanchez said.<br />
<br />
Though Catholic parishes such as St. Joseph’s in north Spokane and St. Rose of Lima in Cheney have offered Spanish-language Mass for more than a decade, the appearance of other Christian faiths offering Spanish or bilingual services is a relatively new phenomenon in the Spokane area.<br />
<br />
The Church of Jesus Christ of Latter-day Saints has offered Spanish-language services in downtown Spokane for the past five years.<br />
<br />
Last month, the church established a new Spanish-language branch in the LDS Spokane East Stake House in Spokane Valley to accommodate a growing number of Latino Mormons, some of whom travel from as far as Coeur d’Alene to attend religious services.<br />
<br />
<br />
“This new location will make church meetings and events more accessible to members,” said branch President Anibal Lopez, a Spokane dentist. “It is also another way to integrate with others in our community.”<br />
<br />
Lopez is the son of a Mexican schoolteacher who immigrated to the United States and taught elementary school in Yakima. Though his uncle was Mormon, Lopez said his family didn’t convert until 1989 after missionaries came to his retired father’s home in Quincy.<br />
<br />
“The church means everything to me,” Lopez said. “It provides my children a foundation to lead their lives.”<br />
<br />
Lopez said about 20 of his branch’s 29 families are Latino. Services are conducted in Spanish, and headphones are provided for English speakers to listen to an interpreter. Congregants sing traditional hymns in Spanish accompanied by piano.<br />
<br />
Mormon male elders, who are not professional clergy, read from the Bible or Book of Mormon and speak of the importance of charity and sacrifice as the means to success in this life and the possibility of passing into the next.<br />
<br />
Church spokeswoman Mindy Wright said children attend part of their services with an English congregation in the same building to help them improve their English-language skills.<br />
<br />
<span style="background-color: yellow;">In Kootenai County, the Rev. Ray Duran is preparing to launch a Spanish-English bilingual church service on the first Sunday of the new year. Duran said he hopes his Candlelight Christian Fellowship will attract Latinos from all over North Idaho.</span><br />
<span style="background-color: yellow;"><br /></span>
<span style="background-color: yellow;">Duran, who was born in New Mexico, said many Latinos are turning to nondenominational churches like his as part of the charismatic renewal.</span><br />
<span style="background-color: yellow;"><br /></span>
<span style="background-color: yellow;">The Catholic Church gave them a strong foundation, but Latinos “are starting to yearn for something more,” Duran said.</span><br />
<span style="background-color: yellow;"><br /></span>
<span style="background-color: yellow;">The 2007 Pew study found that 15 percent of U.S. Hispanics identified as born-again or evangelical Protestant, 5 percent mainline Protestant and 3 percent other Christian, such as Mormon or Jehovah’s Witness.</span><br />
<span style="background-color: yellow;"><br /></span>
<span style="background-color: yellow;">Regardless of their religious affiliation, Latinos told the Pew researchers that God plays an active role in their daily lives. Most pray every day, have crucifixes or other religious objects in their homes and attend services at least once a month. The majority of Latinos who go to a church believe in miracles and that true believers are rewarded with health and wealth.</span><br />
<span style="background-color: yellow;"><br /></span>
<span style="background-color: yellow;">Most houses of worship attended by Latinos are characterized by Latino clergy, Spanish-language services and a majority-Latino congregation, the study found. Nearly a fifth of all Latinos interviewed for the study said they had either converted to another religion or no religion at all. An overwhelming majority of the religious converts cited “a desire for a more direct, personal experience with God” as the reason for their conversion.</span><br />
<span style="background-color: yellow;"><br /></span>
<span style="background-color: yellow;">Duran said that when he was Catholic, he “never really had an experience with the Lord one-on-one.”</span><br />
<span style="background-color: yellow;"><br /></span>
<span style="background-color: yellow;">He said many Latinos converting to charismatic or evangelical faiths are asking why this is.</span><br />
<span style="background-color: yellow;"><br /></span>
<span style="background-color: yellow;">“Once they have a relationship like this with the Lord, there is no going back,” Duran said.</span><br />
<br />
<br />
<br />
2014 - Night of Praise took place in the same building they're in now<br />
<br />
2015 - Night of Praise with Pastor....<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />