---
title: 'School for Boys'
date: '2020-04-04T06:21:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2670659709984289359'
blogger_filename: '/2019/06/school-for-boys.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

The Stark Realities<br />
<br />
They've been homeschooled their whole lives. It's done good and maybe now I realize not so good for them. Pros and Cons.<br />
<br />
Last year, they'd just lost their Mom. I couldn't shock their system any more than it had already been. Their lives were uprooted and shattered. We moved, bought a new house. It helped move them forward. Now, a year later, 6/22, I see they're isolated like I am.<br />
<br />
The Realities that I must face:<br />
<br />
<ul>
<li>I haven't schooled them. I gave it a year. I haven't done it. I gave them a self-paced curriculum but I failed to involve myself beyond the occasional question.&nbsp;</li>
<li>They've failed their assignments consistently. This means they are not "getting it". Whether that's a lack of trying, just rushing so they can play, or my lack of involvement, or both, it's a reality. They aren't getting prepared to handle life's need for strong smart thinking people.</li>
<li>They are ISOLATED. They spend all day in this house alone. Every day. Other than an occasional visit from Aiden and Eagan, or a weekly Youth Group, they don't get out. We don't get out. Although I plan to take us on more activities, it's not a guarantee that I'll follow through or that it will be often enough.&nbsp;</li>
<li>They lack social skills. I am against "socialism" but I'm realizing that there is a God-ordained need for community. And I'm failing in providing them that need.&nbsp;</li>
<li>They need ROUTINE. They are aimless and wandering and I haven't provided them the routine they need. For a self-employed person or stay at home mom, this would still be possible. For my current state of physical, financial, and mental/emotional health, I cannot meet this basic need for them. This would establish a routine for them.&nbsp;</li>
<li>They need to learn INDEPENDENCE. They must learn to become fully functioning adults. That means learning from other's, handling conflict, submitting to authority, being responsible for their own things/tasks.&nbsp;</li>
<li>They need INSTRUCTORS. I learned, and still learn, from a variety of teachers. No one teacher is the be all end all. They need exposure to other personalities, thoughts, ideas, worldviews, and I cannot give them that locked away in a house.&nbsp;</li>
<li>They may not survive a regular school. It might be too big a shock to their system and they would suffer and get hurt by the process.&nbsp;</li>
<li>They may need an alternative school or program. I need to find out what is available.&nbsp;</li>
</ul>
<div>
<br /></div>
<div>
<br /></div>
<div>
Research:</div>
<div>
<br /></div>
<div>
Athol is served by the <a href="https://www.sd272.org/" target="_blank">Lakeland Joint School District</a>.&nbsp;</div>
<br />Lakeland Joint School District 272 is nestled in the Panhandle of North Idaho. It is home to six K-6 Schools; <a href="https://www.sd272.org/fs/pages/393">Athol Elementary</a>, <a href="https://www.sd272.org/fs/pages/629">Betty Kiefer Elementary</a>, <a href="https://www.sd272.org/fs/pages/739">Garwood Elementary</a>, <a href="https://www.sd272.org/fs/pages/849">John Brown Elementary</a>, <a href="https://www.sd272.org/fs/pages/959">Spirit Lake Elementary</a> and <a href="https://www.sd272.org/fs/pages/1069">Twin Lakes Elementary</a>. Two 7-8 Schools; <a href="https://www.sd272.org/fs/pages/507">Lakeland Junior High</a> and <a href="https://www.sd272.org/fs/pages/1179">Timberlake Junior High</a>. And three 9-12 Schools; <a href="https://www.sd272.org/fs/pages/1292">Lakeland Senior High</a>, <a href="https://www.sd272.org/fs/pages/1405">Timberlake Senior High</a> and <a href="https://www.sd272.org/fs/pages/1518">Mountain View Alternative</a>. We are also affiliated with <a href="http://www.ktectraining.org/">Kootenai Technical Education CampusOpens a New Window.</a> (a cooperative between Lakeland, Coeur d'Alene and Post Falls School Districts). <a href="https://www.sd272.org/fs/pages/337">State School Report Card</a><br /><br /><br /><br />Connor:<br />
<br />
<a href="https://www.sd272.org/fs/pages/1518">Mountain View Alternative</a>&nbsp;may be the answer. Small classrooms with hands-on attention for special needs kids.<br /><br /><br /><br /><div><br /></div>
