---
title: 'Coaching Call with Tom W.'
date: '2020-04-07T06:28:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8697475361483662227'
blogger_filename: '/2020/04/coaching-call-with-tom-w.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Freedom Recovery (Kairos AA'
---

<div><div>Coaching Call with Tom W.</div><div><br /></div><div><b>Lookup</b>:&nbsp;</div><div><ul style="text-align: left;"><li>Secret Life of Walter Middy</li><li>Blake Healy Seeing in the Spirit - The Veil</li></ul></div><div><div><b>Questions</b>:</div><div><br /></div><div>What would it look like if you asked more questions, spoke less, listened more?&nbsp;</div><div><br /></div><div>What would it look like if you didn't fill the silences after a short answer with stories, but instead, asked more/better questions?</div><div><br /></div><div>What would it look like if you asked more open-ended questions, probing questions, really tried to connect to hearts and not just information?</div><div><br /></div><div>What motive would you have for asking these questions? To get to know people, learn about them.</div><div><br /></div><div>Go deeper, what would the motive be to asking more/better questions? Love. Love is not self-seeking. Ask more questions... The motive to love them. You can't love them well unless you know them and their heart. Becoming other's-first gets you out of your own head. When you get out of your own head, you become less self-conscious. Less self-focused. Less awkward, because the awkward second-guessing comes from being self-focused.&nbsp;</div><div><br /></div><div>Stereotype: Intellectual/Spiritual men are good/safe. Jocks are jerks.&nbsp;</div><div><br /></div><div>You've seen it broken through James (college friend). He was a 6'5" Football Player, who cried easily, played guitar, and prayed in tongues. And he could go toe-to-toe on any scripture debate. He didn't fit your hyperbole stereotype.&nbsp;</div><div><br /></div><div>How might you be judging other's as not fit to be friends, above you, more manly than you, or unsafe... without actually getting to know them? Maybe asking questions would help you overcome this by getting to know the real layered human, vs, the stereotype. And, by getting you out of your own head, you'll become other's-focused vs self-focused which will drive you to care less about how they view you and more about how much you care about them, which will draw them to you.&nbsp;</div><div><br /></div><div>Realization: It's not that other's rejected you, it's that you rejected them before they had a chance to reject you. You created your own isolation.&nbsp;</div><div><br /></div><div><b>Action Plans:</b></div><div><br /></div><div>1. Intentionally send messages to Matthew. He's invited connection, sow into that ground.</div><div><br /></div><div>2. In any interactions you have (limited with COVID-19), focus on them (not how you feel), ask open-ended questions with a heart to care for them as His kids, really connecting to their hearts, not just getting information. It's not an interview, it's connection.&nbsp;</div><div><br /></div><div>3. Report back in a week.&nbsp;</div><div><br /></div></div></div>