---
title: 'Your Spiritual Life Coach'
date: '2020-04-04T06:32:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7472982383384616242'
blogger_filename: '/2020/04/your-spiritual-life-coach.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">  <p class="MsoNormal">Header:<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">No Hiding<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Your Spiritual Life Coach<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Guiding You To FREEDOM in Life and Peace with God, through a Lifestyle of No Hiding<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Subscribe – Follow Me To FREEDOM<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Problem:<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">If you’ve felt angry and bitter at God, struggled with hang-ups and habits that won’t go away, faced hardships and life events that left you confused with dark thoughts… but desperately wished for something better, for peace, joy, faith,   love, hope… YOU ARE NOT ALONE.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">I’ve been there, often.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">The first step is to admit we have a problem. Or put another way, bring it to the light so it gets handled right. Or in short:  <b><i>No Hiding</i></b>. <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">The first step to changing your relationship with God and your world, is adopt a lifestyle of No Hiding.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Once you admit your struggles, doubts, and questions, you can begin to seek answers and solutions.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Solution:<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">My name is Darrell, and I’m a Spiritual Life Coach<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">I’m also a Widower, Single Father, Writer, Thinker, and Friend.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">I give non-religious, spiritually based, raw, real, simple, honest, practical answers to life’s toughest moments and decisions.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">I’ve been on a journey of self-discovery, peeling away the layers of religious noise and doubts in the dark moments of life, to find a real, loving and easy friendship with God.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">I’m not “there” yet, I haven’t “arrived”, I still have my own questions I’m working through… but I have discovered some life changing truths that brought peace and freedom, and want to help you find your own peace and FREEDOM too.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Call to Action<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Subscribe – Follow Me To FREEDOM<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Pressing Questions:<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Here are some of the most popular articles/questions/answers:<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Email Magnet<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Click Here – get your copy of Why Do Bad Things Happen (pdf).  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Junk Drawer<o:p></o:p></p>  <p class="MsoNormal">Pages<o:p></o:p></p>  <p class="MsoNormal">Disclosures<o:p></o:p></p>  <p class="MsoNormal">Links<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p></div>  