---
title: 'Research / Thoughts'
date: '2020-04-04T06:31:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '364352625302093393'
blogger_filename: '/2020/04/research-thoughts.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p><b><u>What do I do?</u></b></p>  <p class="MsoNormal">Write, create content, teach, guide, counselor, mentor, advise, Jiminy Cricket, AA Sponsor, Yoda, Obe Won, Coach, Train, Tutor, Conductor, Sounding Board, Consultant, Confidant….  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">I listen to people, and give advice, based on my own journey and the things I’ve learned.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">What kind of advice? <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Primarily, spiritually based life advice. How to life freer, more effective, more peaceful lives. How to have more peace in the middle of storms, navigate hard decisions, practice better boundaries, and make decisions that impact the quality   of their lives, finances, and relationships. <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">I love people. And teach them how to love themselves and God.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b>I sell FREEDOM. Freedom from religion and freedom to be all you were created by God to be.<o:p></o:p></b></p>  <p class="MsoNormal"><b>Clarity<o:p></o:p></b></p>  <p class="MsoNormal"><b>Peace<o:p></o:p></b></p>  <p class="MsoNormal"><b>Serenity<o:p></o:p></b></p>  <p class="MsoNormal"><b><o:p></o:p></b></p>  <p class="MsoNormal"><b><o:p>&nbsp;</o:p></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><u>What problem do I solve?<o:p></o:p></u></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">If you’ve felt angry and bitter at God, and fed up with religion, but desperately hoped you could find a life of peace and healing… FREEDOM... If you’ve hoped to live a life closer to God, free from hang-ups, and a life of making better   choices… if you’ve been faced by real, dark, terrible hardships, and you felt lost and confused, and just wanted to know how a Good God can let this happen to you…  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">You’re not alone. <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">I have too. <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">I’ve been on a journey of discovery, peeling away the layers of religious noise and dark moments of life, to find a real, loving and easy friendship with God.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">I’m not “there” yet, I haven’t “arrived”, nobody can until we cross the threshold of eternity.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">But I have discovered some life changing truths, and answers to hard questions, and I help other people find their own answers too.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><u>What do I need to do to buy?<o:p></o:p></u></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><i>Subscribe – Follow Me To Freedom, one day at a time.<o:p></o:p></i></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><u>Research:<o:p></o:p></u></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b>Why Remote Leaders Need a Jiminy Cricket<o:p></o:p></b></p>  <p class="MsoNormal"><a href="https://www.thindifference.com/2018/09/why-remote-leaders-need-a-jiminy-cricket/">https://www.thindifference.com/2018/09/why-remote-leaders-need-a-jiminy-cricket/</a><o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">All leaders need trusted advisors—people to whom they can go for honest assessments and clear thinking.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">So, even though we as remote leaders might not have our Jiminy Crickets physically near, we still can access them by utilizing our virtual communication channels. Like all the other communication issues we talk about in “The Long-Distance   Leader,” though, this communication doesn’t happen as organically as it does in the office. You have to be intentional and plan for it to happen.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b>Michael Hyatt<o:p></o:p></b></p>  <p class="MsoNormal"><a href="https://michaelhyatt.com/about/">https://michaelhyatt.com/about/</a><o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><u>Terms:<o:p></o:p></u></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b>Guide: <o:p></o:p></b></p>  <p class="MsoNormal">1. a person who advises or shows the way to others.<o:p></o:p></p>  <p class="MsoNormal">2. a thing that helps someone to form an opinion or make a decision or calculation.<o:p></o:p></p>  <p class="MsoNormal">3. a structure or marking which directs the motion or positioning of something.<o:p></o:p></p>  <p class="MsoNormal">4. a soldier, vehicle, or ship whose position determines the movements of others.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b>Mentor:<o:p></o:p></b></p>  <p class="MsoNormal">1. an experienced and trusted adviser.<o:p></o:p></p>  <p class="MsoNormal">2. advise or train (someone, especially a younger colleague).<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b>Adviser: <o:p></o:p></b></p>  <p class="MsoNormal">1. a person who gives advice in a particular field.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b>Sounding Board:<o:p></o:p></b></p>  <p class="MsoNormal">1. a board or screen placed over or behind a pulpit or stage to reflect a speaker's voice forward.<o:p></o:p></p>  <p class="MsoNormal">2. a person or group whose reactions to suggested ideas are used as a test of their validity or likely success before they are made public.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b>Sponsor:<o:p></o:p></b></p>  <p class="MsoNormal">1. an individual or organization that pays some or all of the costs involved in staging a sporting or artistic event in return for advertising.<o:p></o:p></p>  <p class="MsoNormal">2. a person who introduces and supports a proposal for legislation.<o:p></o:p></p>  <p class="MsoNormal">3. provide funds for (a project or activity or the person carrying it out).<o:p></o:p></p>  <p class="MsoNormal">4. introduce and support (a proposal) in a legislative assembly.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">An AA sponsor is a role model who offers advice and sympathy for the struggles of recovering alcoholics. Most sponsors urge the person they're sponsoring to contact them at any time, day or night, if they are feeling the urge to relapse.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p></div>  