---
title: 'Dear Her 04/03/2020'
date: '2020-04-04T07:12:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5454072756894603796'
blogger_filename: '/2020/04/dear-her-04032020.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Dear Her'
---

Dear Her,<div><br /></div><div>Karla Colonval is fairly adamant about finding you for me. She's still praying and looking to be the matchmaker. It would be funny if she found you for me.&nbsp;</div><div><br /></div><div>It's April 3, 2020. What are you doing tonight? Huddled up in this crazy COVID-19 scare? Barely noticing it? Do you (*we) have kids that are struggling during this madness?&nbsp;</div><div><br /></div><div>Honestly, this week I've been pretty desperate feeling. Lonely. Despondent. I want a partner. Someone to do life with. The boys are boys. Not partners. No matter how much I want to, I can't share my life with them the way I would you. The cuddles would be nice too.&nbsp;</div><div><br /></div><div>I'm struggling with the websites a bit more these days. I decided to write you this letter instead tonight, so I can keep my vision of what is coming before me. You are worth overcoming this temptation.&nbsp;</div><div><br /></div><div>I don't know if you'll ever come, or ever read these. I'm going to be 40 by the time I'm allowed to commit to anyone again. Who knows how long after that before I am willing and I've found someone that is worth trying... someone who might be you or might not. I won't know until I ask her out, then ask her out again, then again... for a long while.&nbsp;</div><div><br /></div><div>It occurred to me, recently, that if circumstances have brought you to me, that you need healing too. You didn't come to me without having experienced some kind of darkness yourself. Otherwise, you'd be with someone else already/still.&nbsp;</div><div><br /></div><div>So, Father/Daddy, I lift up my Her tonight. Wherever She is, whatever She is doing. I ask you to overcome her with your love, warmth, hope, and healing. I ask you to wrap her in the arms I am unable to use tonight because I don't know her yet. Father her children, in ways that we humans are incomplete to do. Father my children; make up for my inadequacies. Fill out joint households with the Love of God tonight. Peace / Shalom, wash over us. This too, shall pass.&nbsp;</div><div><br /></div><div>Selah...&nbsp;</div><div><br /></div><div>I don't know you yet, but I love you. Somewhere, out there, you are preparing yourself for me, and I am you. I will not come to you unprepared. You will find me ready for you when you arrive.&nbsp;</div><div><br /></div><div>There will be challenges. Some of the growing we have to do won't happen untl we meet. You and I will press each other's buttons in ways nobody has before. But if we both press into that pain of growth, we will find a healing, wholeness, and peace on the other side unlike either of us have seen.&nbsp;</div><div><br /></div><div>I feel guilty. Flavia won't be here to enjoy the fruits of this version of me. You will be enjoying the fruits of her labors, her seed, sown into me.&nbsp;</div><div><br /></div><div>I too, will enjoy the fruits of those who have sown into your life, for better or worse. I honor them all, because they helped you become who you are.&nbsp;</div><div><br /></div><div>I hope you don't hide for too long, I'm looking forward to meeting you.&nbsp;</div><div><br /></div><div>Goodnight Precious Pearl.&nbsp;</div><div><br /></div><div><br /></div>