---
title: 'Writing Assignment 04/2020 Jana Ross'
date: '2020-04-22T13:53:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1669490721839442162'
blogger_filename: '/2020/04/writing-assignment-042020-jana-ross.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<br><div>Text:&nbsp;</div><div><div><div></div><blockquote><div><i>Hmmm...&nbsp; Someone asked me how I was. This came out without me thinking too much...</i></div><div><i><br></i></div><div><i>"I'm okay. Listless. Moody. Distracted.</i></div><div><i><br></i></div><div><i>For years and years I kept thinking that if I were single, I'd have the time to pursue projects and businesses and novels.... Now that I'm single, I only think about having a partner. And I can never seem to gain any focus on the projects.&nbsp;</i></div><div><i><br></i></div><div><i>I have faced my enemy. He is me.</i></div><div><i><br></i></div><div><i>I stare at the screen, nothing comes to mind. So I close it and go watch something or clean something.</i></div><div><i><br></i></div><div><i>"Someday" when the house is in order... But the house is never in order. We've been in it a year this week.</i></div><div><i><br></i></div><div><i>There's always three projects to replace the one I complete.</i></div><div><br></div><div><i>I think I am more terrified of trying and failing. At least if it's always in the future, I can always talk about what I'm going to do "someday".</i></div><div><br></div><div><i>Rather than admitting that I'm almost forty and I've accomplished nothing significant with my life and I may in fact retire from some dead end job.</i></div><div><i><br></i></div><div><i>Crap...</i></div><div><i><br></i></div><div><i>I didn't know I was thinking any of that until just now."</i></div><div><br></div><div><i>Getting curious about that now, I suppose.</i></div><div><br></div><div><i>It was unhealthy. But. I think Flavia took care of our whole life, the real stuff, bills, laundry, kids fights, etc.... Which left me free to dream. I don't dream much anymore since reality set in.</i></div><div><i><br></i></div><div><i>Without the dream, the creativity died.</i></div><div><i><br></i></div><div><i>Time to find a way to stoke that again in a more healthy balanced way.</i></div></blockquote><div></div></div><div><br></div><div>Dr Jana:&nbsp;</div><div><br></div></div><div><div><i></i></div><blockquote><div><i>Okay oh, I want you to do a writing assignment. What am I angry about? What am I scared of? What do I feel guilty for? After you complete that, go back and write the truth. The truth is not the all-or-nothing statements but that usually come out with the angry, scared, guilty. <b>An example would be that I'm totally failing my kids. And reality I haven't had meaningful conversation in a couple of days. </b>The third part of the assignment is to sort out what movement you want to make about each statement. Once I have identified the truth then I can take a step toward making it better. An example would be angry that I have to do this alone! The truth is that I'm not doing it alone. I have God, teachers, church friends that care, kids themselves are responsible for some of their life. My plan is to . . . Practice I See You" when I feel that ache, the temptation to believe I will not be married again. I will also reassure myself that I am taking steps to have a healthier relationship and am very glad I didn't jump in to anything earlier.</i></div><div><i><br></i></div><div><i><b>Depression sets in with all or nothing thinking.&nbsp;</b> What you are describing is the realization of what you have been thinking so you need to establish a battle plan that keeps you from getting stuck there</i></div><div></div></blockquote><div><br></div><div><br></div><div><br></div><div><br></div></div><div><b>What am I angry about?&nbsp;</b></div><div><br></div><div><br></div><div>I am angry that she left me here to raise these boys alone.&nbsp;</div><div><br></div><div>I am angry that the one person who made me feel special after her, left me too.&nbsp;</div><div><br></div><div>I am angry that I am almost 40 and I've never launched a successful career, business, blog, podcast, book... and that I'm still struggling to make ends meet when I should be driving my BMW by now.&nbsp;</div><div><br></div><div>I'm angry that I have 148 IQ, I'm smart enough to do anything and I've done nothing.</div><div><br></div><div>I'm angry that I'm here, alone, with no partner.&nbsp;</div><div><div><br></div><div>I guess this falls under angry...&nbsp;</div><div>I am a male. I send texts back and forth with my female friends daily, they respond, we dialogue. Every man I've tried this with doesn't engage. I get very closed reaponses. Am I the only man who likes words? Sigh... Oh well. I just keep trying new things. COVID-19 is almost passed us, I can start meeting them in person soon. They say females bond face to face, makes bond side by side. So I guess I need to do something with them, even if it's just shoot pool or something.&nbsp;</div></div><div><br></div><div><br></div><div><b>What am I scared of?&nbsp;</b></div><div><br></div><div>I'm terrified that I am not enough to raise these boys. That I'm insufficient to handle their emotional needs. I'm failing them psychologically, emotionally, quality time, physically. It's been almost a year since I intended to get them into the doctor and I haven't taken them in.&nbsp;</div><div><br></div><div>I'm scared to try, because I always fail to finish. And if I do try and finish, it won't be enough.</div><div><br></div><div>I'm scared of success because they'll figure out I was faking it. More success brings more attention, more attention brings more criticism, which tears me apart.&nbsp;</div><div><br></div><div>I'm scared of being nothing. Doing nothing significant.&nbsp;</div><div><br></div><div><br></div><div><b>What do I feel guilty for?</b></div><div><br></div><div>If I had loved Flavia better, she'd have gotten healthy faster, and she wouldn't have died, and my boys would have their mother. They'd be so much better off with her and not me than the other way around.&nbsp;</div><div><br></div><div>*Which is untrue. We cannot force people to make new choices.&nbsp;</div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><b>After you complete that, go back and write the truth.</b></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div>