---
title: 'Dream 12:32 PM Oct 16, 2019'
date: '2020-04-04T06:26:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6032145898683343047'
blogger_filename: '/2020/04/dream-1232-pm-oct-16-2019.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

Just now...
<br />
<br />I had an elaborate dream the Flavia had faked her death for some reason. And I knew about it but I was the only one besides some secret organization that was helping her communicate with me. Then I was giving her this tour of a village we had moved to showing her the mining operation. I was trying to convince her that the plan wasn't good and that she should come back. She insisted on keeping with the plan and insisted that it was better this way. Set up this whole elaborate party dash memorial and is about to singer favorite line from our favorite song... But I was going to say that very few people ever sung the line before it... In the line before it should someone had a brave really stand up and face reality. And just as I was about to sing it with her backstage possibly ready to come out... I woke up to realize that she really is gone she's not coming back.