---
title: 'Dear Jen Nelson... 5/5/2020'
date: '2020-05-05T13:49:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6145245764142971052'
blogger_filename: '/2020/05/dear-jen-nelson-552020.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Dear Her'
---

Dear Jen Nelson,<div><br></div><div>It is the morning of May 5, 2020. I woke up and realized something. I love you. You're a crazy walking contradiction, and I love you.</div><div><br></div><div>As I stopped making assumptions about you, and started observing, I found I actually really enjoy how you parent. You have boundaries, they're just different.</div><div><br></div><div>We come from different angles on Sex, but, we land in approximately the same place. And, I'm starting to see new things that you've shown me, while you're starting to come around my way on the whole idea.</div><div><br></div><div>My mind (The Thing I Want) is still fighting me. The list I was supposed to throw out but never forgot, isn't it.</div><div><br></div><div>My heart (The Thing I Need) is screaming at me "MARRY HER". You make my heart feel safe in so many ways.&nbsp;</div><div><br></div><div>I'm so confused. Ha ha.&nbsp;</div><div><br></div><div>If I were to throw caution to the wind, I would say marry me, right now, over the phone.</div><div><br></div><div>But...</div><div><br></div><div>As you know, I almost got married to very unhealthy women twice in my first year. So I'm being cautious.</div><div><br></div><div>Plus, you're only a few months from loss. You live in Florida. You and I would need to figure out housing and other things.&nbsp;</div><div><br></div><div>I don't know.</div><div><br></div><div>Some logistics don't make sense.</div><div><br></div><div>But the real test is my boys.&nbsp;</div><div><br></div><div>Do they like you?</div><div><br></div><div>Do our kids work?</div><div><br></div><div>Am I willing to take the gift your husband left you with?</div><div><br></div><div>God said, she would come before I thought I was ready, but, don't resist it, don't fight it. I didn't understand, I do now.&nbsp;</div><div><br></div><div>He reminded me twice, he had a wife for me.&nbsp;</div><div><br></div><div>But none of that matters.</div><div><br></div><div>Because, what he told me, is that it was my choice. I got to choose. I got to lead. I got to build it right.</div><div><br></div><div>I don't know if you're her... I don't KNOW it.&nbsp;</div><div><br></div><div>I think, maybe, you could be. And I would like to spend the next season studying you. And not rush anything.&nbsp;</div><div><br></div><div>But, I'm already in love. I realized that this morning. Which terrifies me.&nbsp;</div><div><br></div><div>If you're not her, she must be fucking amazing! Because you make me feel so safe to love again. The door I've kept shut, is cracking open.&nbsp;</div><div><br></div><div>Sigh...</div><div><br></div><div>Whether you're here for good or for a season, I want you to know, I love you.</div><div><br></div><div>Goodnight Hippie Chick</div><div><br></div><div>PS: I totally did while we were on the phone.&nbsp;</div>