---
title: 'Expectations are pre-meditated disappointments.'
date: '2020-04-04T06:37:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5701983703830742293'
blogger_filename: '/2020/04/expectations-are-pre-meditated.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">  <p class="MsoNormal">Expectations are pre-meditated disappointments. <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">1 . This could mean that you expected someone to give you something they were unwilling or unable to provide. Maybe they were incapable of providing emotional support. Maybe they just were busy in schedule and you expected them to drop   everything. In one form or another, you expected and they couldn’t. <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">2 . This could mean that you expected someone to be someone they were not. You need to grieve that loss and accept they are not who you hoped and move on.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">3 . This could mean that your own expectations of others is too high or too low, and that you need to adjust what you expect of others. Maybe you need to start doing for yourself what you’ve been hoping someone would do for you.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">4 . This could meant that you were positive (based on the evidence available) a particular outcome was inevitable. You were sure you’d get that job, everything was lining up easily, and yet, they offered the job to someone else.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">This could mean a lot of things… the end result is that you expected someone or something to be something it wasn’t. You expected something to happen that didn’t. You expected God to heal you or them, and healing didn’t come.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Sometimes expectations just need to be realigned. Sometimes they need to be avoided altogether.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p></div>  