---
title: 'Dear Her, 4/29/2020'
date: '2020-04-29T21:52:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6678323427889050081'
blogger_filename: '/2020/04/dear-her-4292020.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Dear Her'
---

Dear Her,<div><br></div><div>I've just been talking with a Widow from Florida, who I'm 60% certain isn't you. But it's been a profoundly growth spurt inducing conversation. In many ways, kick-starting things Shelley started in me that died on the vine when she left.</div><div><br></div><div>I wanted to tell you about it,&nbsp; actually quite excited. I think I just found a framework to understanding how to remain free of codependency and recognize it, in one phrase.&nbsp;</div><div><br></div><div>Own My Space&nbsp;</div><div><br></div><div>I used to not have firm answers, because I was afraid of being rejected. I was changing my opinions to match others, because I didn't want to scare them away.&nbsp;</div><div><br></div><div>I am beginning to see, like I did earlier last year, that as I own my space, decide what kind of eggs I like (Runaway Bride reference), I am less dependant on the feelings of others and I perceive they perceive me.&nbsp;</div><div><br></div><div>As a result, I can provide your heart a safe space to rest in my hands. Owning my space, is safety for you.&nbsp;</div><div><br></div><div>I never saw it that way.&nbsp;</div><div><br></div><div>I used to see Masculinity as cheap make bravado. Not so! It's a place where a man owns his space, and creates saftey for others inside that space. It's the thing that makes him stand in front of bullets, and it's the thing that makes him say, "I will not have you talk to my wife that way".&nbsp;</div><div><br></div><div>Wow!&nbsp;</div><div><br></div><div>I wish I knew this twenty years ago.&nbsp;</div><div><br></div><div>I do now. I'm excited to meet you, so you can tell me what you've been working on.&nbsp;</div><div><br></div><div>It's okay, I'll be patient, take your time.&nbsp;</div><div><br></div><div>I will find you when we're both ready, and Daddy says go!&nbsp;</div><div><br></div><div>Your him, Darrell</div><div><br></div>