---
title: 'I''m not okay....'
date: '2020-03-29T05:14:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '6561351138107469089'
blogger_filename: '/2020/03/im-not-okay.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Musings'
---

<div><br></div><div><br></div><div><br></div><div><br></div><div><div>Hmmm...&nbsp; Someone asked me how I was. This came out without me thinking too much...</div><div><br></div><div>"I'm okay. Listless. Moody. Distracted.</div><div><br></div><div>For years and years I kept thinking that if I were single, I'd have the time to pursue projects and businesses and novels.... Now that I'm single, I only think about having a partner. And I can never seen to gain any focus on the projects.&nbsp;</div><div><br></div><div>I have faced by enemy. He is me.</div><div><br></div><div><br></div><div>I stare at the screen, nothing comes to mind. So I close it and go watch something or clean something.</div><div><br></div><div>"Someday" when the house is in order... But the house is never in order. We've been in it a year this week.</div><div><br></div><div>There's always three projects to replace the one I complete.</div><div><br></div><div>There's always three projects to replace the one I complete.</div><div><br></div><div>I think I am more terrified of trying and failing. At least if it's always in the future, I can always talk about what I'm going to do "someday".</div><div><br></div><div><br></div><div>Rather than admitting that I'm almost forty and I've accomplished nothing significant with my life and I may in fact retire from some dead end job.</div><div><br></div><div>Crap...</div><div><br></div><div>I didn't know I was thinking any of that until just now."</div></div><div><br></div><div>Getting curious about that now, I suppose.<br></div><div><br></div><div><div>It was unhealthy. But. I think Flavia took care of our whole life, the real stuff, bills, laundry, kids fights, etc.... Which left me free to dream. I don't dream much anymore since reality set in.</div><div><br></div><div>Without the dream, the creativity died.</div><div><br></div><div>Time to find a way to stoke that again in a more healthy balanced way.</div></div><div><br></div><div><br></div><div><br></div>