---
title: 'Sigh.....'
date: '2020-04-22T13:47:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8341200966540341943'
blogger_filename: '/2020/04/sigh.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Pfft'
---

It's basically been a year since Shelley dumped me like it was no big deal and close to a year since she broke my heart.&nbsp;<div><br></div><div>I still find myself wanting to send a good morning text. Not so much to her, per se, not anymore, but to... My Someone.&nbsp;</div><div><br></div><div>I have 5-10 people I could send that text to today. But all of them feel like place holders. The only one that would be a genuine deep connection with is T and she also represents the past, in a different way. I'm purposefully sending fewer her way.&nbsp;</div><div><br></div><div>Sometimes, I think I pick a topic I know we'll disagree on, just to push her back a bit.&nbsp;</div><div><br></div><div>Lately, just in the past few weeks, my phone has been less in my face. I've got my book on the computer and my iPad for reading. I just haven't had anyone I wanted to connect with as much. I'm over the drama most of them bring. And talking with Julia is like rubbing my soul against sandpaper. And I keep trying to talk to Matthew, but, he's not very responsive, as is typical for men. So whatever. I guess I have to wait for COVID-19 to be over and start meeting him or others in person.&nbsp;</div><div><br></div><div>I like words. Why don't other men? Am I not man? Am I weird hybrid? I don't know.&nbsp;</div><div><br></div><div>Pfft.&nbsp;</div>