---
title: 'Dragged Into the Kingdom, Kicking and Screaming'
date: '2020-04-04T06:28:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '2655534273612537904'
blogger_filename: '/2020/04/dragged-into-kingdom-kicking-and.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><a href="https://jdgreear.com/blog/dragged-into-the-kingdom-kicking-and-screaming/">https://jdgreear.com/blog/dragged-into-the-kingdom-kicking-and-screaming/</a><o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal" style="background: white;">  <span style="color: #333333; font-family: montserrat; font-size: 22.5pt;">Dragged Into the Kingdom, Kicking and Screaming<o:p></o:p></span></p>  <p class="MsoNormal" style="background: white;"><span style="color: #777777; font-family: montserrat; font-size: 9pt; text-transform: uppercase;"><a href="https://jdgreear.com/blog/category/leadership/" title="View more Leadership"><span style="color: #777777; text-decoration: none;">Leadership</span></a>Pastor   J.D.Apr 7, 2014 <o:p></o:p></span></p>  <p class="MsoNormal" style="background: white; line-height: 0%;"><span style="border: 1pt none; color: #333333; font-family: &quot;open sans&quot;; font-size: 1pt; padding: 0in;">AddThis Sharing Buttons</span><span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 1pt;"><o:p></o:p></span></p>  <p align="center" class="MsoNormal" style="background: white; line-height: 0%; text-align: center;">  <span style="border: 1pt none; color: #333333; font-family: &quot;open sans&quot;; font-size: 1pt; padding: 0in;">Share to Facebook</span><span style="color: white; font-family: &quot;open sans&quot;; font-size: 8pt;">Facebook</span><span style="border: 1pt none; color: #333333; font-family: &quot;open sans&quot;; font-size: 1pt; padding: 0in;">Share   to Twitter</span><span style="color: white; font-family: &quot;open sans&quot;; font-size: 8pt;">Twitter</span><span style="border: 1pt none; color: #333333; font-family: &quot;open sans&quot;; font-size: 1pt; padding: 0in;">Share to Email</span><span style="color: white; font-family: &quot;open sans&quot;; font-size: 8pt;">Email</span><span style="border: 1pt none; color: #333333; font-family: &quot;open sans&quot;; font-size: 1pt; padding: 0in;">Share   to More</span><span style="color: white; font-family: &quot;open sans&quot;; font-size: 8pt;">More26</span><span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 1pt;"><o:p></o:p></span></p>  <p class="MsoNormal" style="background: white; line-height: 24pt;">  <span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;">C. S. Lewis has one of the more intriguing stories of conversion. In his autobiography,  <i>Surprised by Joy, </i>he called himself “the most dejected, reluctant convert in all of England . . . <b><u>drug into the kingdom kicking, struggling, resentful, and darting his eyes in every direction for a chance of escape</u></b>.” Somehow that doesn’t usually make   the list of people’s favorite C.S. Lewis quotes.<o:p></o:p></span></p>  <p class="MsoNormal" style="background: white; line-height: 24pt;">  <span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;">It’s important to see what Lewis isn’t saying: he’s not saying that he regrets becoming a Christian. (Remember, it’s  <i>Surprised by <b>Joy</b></i>.) And he’s not trying to weigh in on the Calvinism/Arminian debate (though he does elsewhere). C.S. Lewis is saying that God often pursues us  <b>long </b>before we have any inkling of what he’s up to. More often than not, we don’t like the pursuit.<o:p></o:p></span></p>  <p class="MsoNormal" style="background: white; line-height: 24pt;">  <span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;">A scene that beautifully captures Lewis’ experience is in his  <i>Voyage of the Dawn Treader</i>. One of the main characters—a boy named Eustace—has developed an evil heart and becomes a dragon. He wants to be a boy again, so Aslan leads him to a pristine fountain of water. Listen to Eustace (and behind him, C.S. Lewis),   describe his experience:<o:p></o:p></span></p>  <p class="MsoNormal" style="background: white; line-height: 24pt;">  <i><span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;">The water was as clear as anything and I thought if I could get in there and bathe it would ease the pain. But the lion [Aslan] told me I must undress first.</span></i><span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;"><o:p></o:p></span></p>  <p class="MsoNormal" style="background: white; line-height: 24pt;">  <i><span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;">So I started scratching myself and my scales began coming off all over the place. And then I scratched a little deeper and, instead of just scales coming off here and there, my whole skin   started peeling off beautifully. In a minute or two I just stepped out of it. I could see it lying there beside me, looking rather nasty. It was a most lovely feeling. So I started to go down into the well for my bathe.</span></i><span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;"><o:p></o:p></span></p>  <p class="MsoNormal" style="background: white; line-height: 24pt;">  <i><span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;">But just as I was going to put my feet into the water I looked down and saw that [the skin on my feet was] all hard and rough and wrinkled and scaly just as it had been before.</span></i><span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;"><o:p></o:p></span></p>  <p class="MsoNormal" style="background: white; line-height: 24pt;">  <span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;">[Eustace then repeats the process a second and third time, growing increasingly despairing.]<o:p></o:p></span></p>  <p class="MsoNormal" style="background: white; line-height: 24pt;">  <i><span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;">Then the lion said, ‘You will have to let me undress you.’ I was afraid of his claws, I can tell you, but I was pretty nearly desperate now. So I just lay flat down on my back to let him   do it.</span></i><span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;"><o:p></o:p></span></p>  <p class="MsoNormal" style="background: white; line-height: 24pt;">  <i><span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;">The very first tear he made was so deep that I thought it had gone right into my heart. And when he began pulling the skin off, it hurt worse than anything I’ve ever felt. The only thing   that made me able to bear it was just the pleasure of feeling the stuff peel off.</span></i><span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;"><o:p></o:p></span></p>  <p class="MsoNormal" style="background: white; line-height: 24pt;">  <i><span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;">Well, he peeled the beastly stuff right off – just as I thought I’d done it myself the other three times, only they hadn’t hurt – and there it was lying on the grass: only ever so much   thicker, and darker, and more knobbly-looking than the others had been. Then he caught hold of me – I didn’t like that much for I was very tender underneath now that I’d no skin on – and threw me into the water. It smarted like anything, but only for a moment.   After that it became perfectly delicious and as soon as I started swimming and splashing I found that all the pain had gone. And then I saw why. I’d turned into a boy again.</span></i><span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;"><o:p></o:p></span></p>  <p class="MsoNormal" style="background: white; line-height: 24pt;">  <span style="color: #333333; font-family: &quot;open sans&quot;; font-size: 12pt;">If you’re feeling God’s pursuit like the “claws” of a lion, know that while it may be painful, it’s not punishment. God never desires to pay you back, but to bring you back. Will you let him?<o:p></o:p></span></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p></div>  