---
title: 'Blessed Assurance'
date: '2020-04-04T06:22:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7134905437779489480'
blogger_filename: '/2020/04/blessed-assurance.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">  <p class="MsoNormal"><span style="color: #222222; font-family: arial, sans-serif; font-size: 12pt;">Blessed Assurance<o:p></o:p></span></p>  <p class="MsoNormal"><span style="color: #222222; font-family: arial, sans-serif; font-size: 12pt;"><a href="https://www.google.com/search?q=Elevation+Worship&amp;stick=H4sIAAAAAAAAAONgVuLSz9U3yMuozE7PXcQq6JqTWpZYkpmfpxCeX1SckVkAAM_ITqwiAAAA&amp;sa=X&amp;ved=2ahUKEwiviq2z5bjjAhUM6KQKHY_xBdUQMTAAegQIDRAF"><span style="color: blue; text-decoration: none;">Elevation   Worship</span></a><o:p></o:p></span></p>  <p class="MsoNormal"><span style="color: #222222; font-family: arial, sans-serif; font-size: 12pt;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="color: #222222; font-family: arial, sans-serif; font-size: 12pt;">Blessed assurance, Jesus is mine<br />  O what a foretaste of glory divine<br />  <br />  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="color: #222222; font-family: arial, sans-serif; font-size: 12pt;">Heir of salvation, purchase of God<br />  Born of His Spirit, washed in His blood<o:p></o:p></span></p>  <p class="MsoNormal"><span style="color: #222222; font-family: arial, sans-serif; font-size: 12pt;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="color: #222222; font-family: arial, sans-serif; font-size: 12pt;">Perfect submission, all is at rest<br />  I in my Savior am happy and blessed<br />  <br />  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="color: #222222; font-family: arial, sans-serif; font-size: 12pt;">Watching and waiting, looking above<br />  Filled with His goodness, lost in His love<o:p></o:p></span></p>  <p class="MsoNormal"><span style="color: #222222; font-family: arial, sans-serif; font-size: 12pt;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="color: #222222; font-family: arial, sans-serif; font-size: 12pt;">This is my story, this is my song<br />  Praising my Savior all the day long<br />  <br />  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="color: #222222; font-family: arial, sans-serif; font-size: 12pt;">This is my story, this is my song<br />  Praising my Savior all the day long<o:p></o:p></span></p>  <p class="MsoNormal"><span style="color: #222222; font-family: arial, sans-serif; font-size: 12pt;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="color: #222222; font-family: arial, sans-serif; font-size: 12pt;">Oh what a Savior, wonderful Jesus<br />  Oh what a Savior, wonderful Jesus<br />  Oh what a Savior, wonderful Jesus<br />  Oh what a Savior, wonderful Jesus<o:p></o:p></span></p>  <p class="MsoNormal"><span style="color: #222222; font-family: arial, sans-serif; font-size: 12pt;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="color: #222222; font-family: arial, sans-serif; font-size: 12pt;">Death could…  <o:p></o:p></span></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p><span lang="EN">"<b>Blessed Assurance</b>" is a well-known <a href="https://en.wikipedia.org/wiki/Christianity" title="Christianity">  Christian</a> <a href="https://en.wikipedia.org/wiki/Hymn" title="Hymn">hymn</a>. The lyrics were written in 1873 by blind hymn writer  <a href="https://en.wikipedia.org/wiki/Fanny_Crosby" title="Fanny Crosby">Fanny Crosby</a> to the music written in 1873 by  <a href="https://en.wikipedia.org/wiki/Phoebe_Knapp" title="Phoebe Knapp">Phoebe Knapp</a>.  <o:p></o:p></span></p>  <p><b><span lang="EN">Stanza 1</span></b><span lang="EN"><br />  Blessed assurance, Jesus is mine!<br />  O what a foretaste of glory divine!<br />  Heir of salvation, purchase of God, <br />  Born of His Spirit, washed in His blood. <o:p></o:p></span></p>  <p><b><span lang="EN">Refrain:</span></b><span lang="EN"><br />  <i>This is my story, this is my song, <br />  praising my Savior all the day long; <br />  this is my story, this is my song, <br />  praising my Savior all the day long. </i><o:p></o:p></span></p>  <p><b><span lang="EN">Stanza 2</span></b><span lang="EN"><br />  Perfect submission, perfect delight! <br />  Visions of rapture now burst on my sight; <br />  Angels descending bring from above <br />  Echoes of mercy, whispers of love. <o:p></o:p></span></p>  <p><b><span lang="EN">(Refrain)</span></b><span lang="EN"> <o:p></o:p></span></p>  <p><b><span lang="EN">Stanza 3</span></b><span lang="EN"><br />  Perfect submission, all is at rest! <br />  I in my Savior am happy and blessed, <br />  Watching and waiting, looking above, <br />  Filled with His goodness, lost in His love. <br />  <b>(Refrain)</b> <o:p></o:p></span></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p></div>  