---
title: '"Her" Realization'
date: '2020-02-23T07:45:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7308144693709648777'
blogger_filename: '/2020/02/her-realization.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">  <p class="MsoNormal">My coworker said she loved budgeting, planning, and organizing and crossing off lists in her physical paper dayplanner. I was suddenly overwhelmed with a very physical attraction to her statement. Like, I actually found it a turn on.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal" style="line-height:125%"><b><span style="font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#0085AD">Darrell Wolfe<o:p></o:p></span></b></p>  <p class="MsoNormal" style="line-height:125%"><b><span style="font-size:9.0pt;line-height:125%;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#1F497D">Triage Associate | Account Protection  <o:p></o:p></span></b></p>  <p class="MsoNormal" style="line-height:125%"><span style="font-size:9.0pt;line-height:125%;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#1F497D">Alliance Data  </span><span style="font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#1F497D"><o:p></o:p></span></p>  <p class="MsoNormal" style="line-height:125%"><span style="font-size:9.0pt;line-height:125%;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#1F497D">751 W Hanley, Coeur d&#8217;Alene, ID 83815<o:p></o:p></span></p>  <p class="MsoNormal"><span style="color:#1F497D"><a href="http://www.knowmoresellmore.com/"><span style="font-size:10.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#0085AD">knowmoresellmore.com</span></a></span><span style="font-size:10.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#1F497D">   | </span><span style="color:#1F497D"><a href="https://www.linkedin.com/company/2973795?trk=tyah"><span style="font-size:10.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#0085AD">LinkedIn  </span></a></span><span style="font-size:10.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#1F497D">|  </span><span style="color:#1F497D"><a href="https://www.facebook.com/KnowMoreSellMore"><span style="font-size:10.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#0085AD">Facebook</span></a></span><span style="font-size:10.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#0085AD">  </span><span style="font-size:10.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#1F497D">|  </span><span style="color:#1F497D"><a href="https://twitter.com/know_sellmore"><span style="font-size:10.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#0085AD">Twitter</span></a></span><span style="font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#1F497D">  <o:p></o:p></span></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  </div>  <br clear="both">  ______________________________________________________________________<BR>  The information contained in this e-mail message and any attachments may be privileged and confidential. If the reader of this message is not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that any review, dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by replying to this e-mail and delete the message and any attachments from your computer.<BR>  ______________________________________________________________________<BR>  