---
title: 'Dear Her 5/19/2020'
date: '2020-05-19T12:50:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '487643840765674289'
blogger_filename: '/2020/05/dear-her.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Dear Her'
---

Hello Dear Her,<div><br></div><div>It's been Three Weeks and Five Days since I met Jen. She's such a question mark for me. She's hitting me on levels I haven't been touched before; however, other aspects hold me back.&nbsp;</div><div><br></div><div>I understand her take on protecting the innocent. She sees the kid shooter as the victim of a society that hasn't given him the opportunity, he couldn't get to his meds because he aged out of the system. I see that, but, I'm more concerned about the 100 other people in the room. I see him needing meds as an entirely different matter, and I place some of the ownership on him, regardless of his disability.</div><div><br></div><div>She wouldn't want her kids in a house with guns, that seems nieve and foolish to me. I get why she says it though, for her kids. Nico doesn't even wear clothes sometimes and Ava is eating markers. But, is that parenting style too laid back for me? Too&nbsp;laissez-faire?</div><div><br></div><div>Then again, I'm not looking for me. I'm looking for a counterbalance and counterpart. Hm.</div><div><br></div><div>What does it mean to become a "life-partner"?&nbsp;</div><div><br></div><div>It means we do life together. That's all inclusive. For certain, we should enjoy the Bible together, pray together, and worship together. We should also take walks together and spend time being silent.&nbsp;</div><div><br></div><div>However, enjoying the same restaurants and movies and hobbies is big too. A vegetarian who mostly grazes raw things from the bag, doesn't already enjoy SciFi or Fantasy Genre Movies and Books, who doesn't like shooting guns, or by extension, arrows, doesn't even buy her kids Need guns... Hm.... I'm not sure what doing life together would look like with her.</div><div><br></div><div>I can't see the puzzle pieces fitting together. And highest on my hopes are a friction free fit, family to family, blending seemlessly like we had always been together. Our kids being each other's beat friends, which wouldn't be possible here.&nbsp;</div><div><br></div><div>There's so much here, I don't feel I can walk away... Yet... I want to give it time to see what it could be without my preconceived ideas... But... If I made a decision today, I would say this isn't you.</div><div><br></div><div>We shall see,</div><div><br></div><div>Darrell, your him.&nbsp;</div><div><br></div>