---
title: 'Dear Her: What about Jen?'
date: '2020-05-15T14:04:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7604768171512730867'
blogger_filename: '/2020/05/what-about-jen.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Dear Her'
---

<div class="WordSection1"><p class="MsoNormal">What about Jen?</p><p class="MsoNormal">&nbsp;Dear Her,</p><p class="MsoNormal">I've stopped trying to determine if Jen is you or not, I am just getting to know a human I enjoy and am attracted to and I will let God and time determine if she's you.</p><p class="MsoNormal">Jen is an unusual, unique, and rare woman. She knows my Daddy (God) in deep and profound ways that few others have shown me. She is deeply thoughtful, carefree and funny, irreligiously humorous.&nbsp;</p><p class="MsoNormal">She is dedicated to Jesus but not to “The&nbsp;Church”, just like me. She is committed to The Word but not religious tradition. She loves her children well, meeting their needs in a non-controlling way. She allows for their push back without bending to it.</p><p class="MsoNormal">Her insight is valuable to me. She sees. She sees me, life, others, the truth underneath a thing. Jen sees the world in a way that breaks the glass and looks behind the curtain.</p><p class="MsoNormal">At first glance, she did not appear to be my physical “type”. But, she says things, regular things, insightful things, that create reactions in me that I don’t understand. Non-sexual things that create a sexual response. Weird. Powerful.&nbsp;Amazing. I want more of it.</p><p class="MsoNormal">&nbsp;Also, the first time I saw her photos I wasn't drawn in, but, the more I know her the more the "Aww, there's my Jen" is happening.&nbsp;</p><p class="MsoNormal">I have patterns. I get drawn in by someone, falling for them often with a glance, a look in the eye, and almost every single one of them had the same troubled back story and trauma, and it's usually unhealed and unprocessed. I fall for them without really knowing them, then, I get bored quickly.</p><p class="MsoNormal">With Flavia it was different, I was called of God to make her my wife. I studied her, and fell for her over time. I went from uninterested to very interested.&nbsp;</p><p class="MsoNormal">That second pattern is happening here with Jen. She was all bells and whistles and lights going off and something strange is happening here on her end the first two weeks. I was just Intrigued and stayed around because I was interested. But here we are at 1 Month 2 Days, and I am very interested. I might even be falling for her.&nbsp;</p><p class="MsoNormal">Shelley was like that too though, I wasn't interested and then she made me interested, even hinted at Prophetic Words that meant we should be together... Then she walked away. So I'm staying guarded.</p><p class="MsoNormal">Her tastes are similar. We have wildly different interests in music and movies, but, underneath those is a similar way of seeing the world and a similar reason for those tastes. She’s willing to try the Marvel Movies, if we fast forward&nbsp;the parts she doesn’t like.</p><p class="MsoNormal">She’s a vegetarian, but, we like similar foods, so we can mix up ingredients, I’ve been cooking separate meals for each person my whole adult life, why not keep doing it?</p><p class="MsoNormal">Nico is special needs, so that will be a responsibility, but, I think I could be up to that task.</p><p class="MsoNormal">********* Stop over thinking…. Prayer…. **********</p><p class="MsoNormal">I could analyze this all day… but accessing my head will never translate to my heart. I keep looking for reasons to “fall in love” with her, or not to.</p><p class="MsoNormal">I learned form two marriages “falling in love” doesn’t last anyway. It matters but it’s not important.&nbsp;I learned from last year’s experiences that you can fall in love on purpose, not by talking yourself into it, but, by taking consistent actions that build real lasting intimacy with the person. If you keep that up, you’ll keep building it, it’ll keep coming,&nbsp;like waves of harvested crops.</p><p class="MsoNormal">So the question isn’t whether I’m “in love” with a woman I’ve only known for 3-4 weeks. That’s ridiculous movie nonsense anyway. The question is, could this be a woman with whom I would be willing to build that type of intimacy. And to that,&nbsp;my answer is a resounding yes!</p><p class="MsoNormal">So if that’s the case… let the adventure continue. We’ll see what happens next, but it will have been worth trying.</p><p class="MsoNormal">******</p><p class="MsoNormal">Written at well three, edited and added at week four. I should have just thrown together a new page but I didn't. Oh well.&nbsp;</p><p class="MsoNormal"><br></p><p class="MsoNormal">Darrell, Your Him.</p><p class="MsoNormal"></p></div>