---
title: 'Dear Her, 5/6/2020'
date: '2020-05-07T03:33:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1801023577839856885'
blogger_filename: '/2020/05/dear-her-562020.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Dear Her'
---

Dear Her,<div><br></div><div>So... I met someone two weeks ago. April 22. We talked for five hours. And almost every day since. I don't know if she's you. I don't know that she's not you. Because I don't KNOW she's you, I'm holding back a bit.&nbsp;</div><div><br></div><div>She's nothing like I expected, which is partly why I'm fascinated. Flavia wasn't anything I expected either. I may not have recognized it or stewarded Flavia well, but, she was God given, and a good partner. So the idea of a partner that doesn't look like what I thought, is appealing on that precedence.&nbsp;</div><div><br></div><div>I've been reading about Character Archs. How the character begins the story with a desire built on the symptoms of a lie he doesn't know he believes. By the end, he must come to terms with letting the lie go and accepting the truth. Often letting go of his desire and accepting what he needs. But in some cases, he ends up with a version of what he desires based on the Truth instead of the lie.</div><div><br></div><div>This is me.</div><div><br></div><div>I'm living this story.</div><div><br></div><div>I don't know if you and Jen are the same person or if you're not. I don't know if this is what I choose. My reservations won't be answered unless she moves here, we start dating, and I see her in season and out of season.&nbsp;</div><div><br></div><div>If she is you, I want to give her time. The first year is tough, regardless of how she says she prepared to let go leading up to that day.</div><div><br></div><div>Despite some things not looking like the list I wasn't supposed to be looking at, I am strongly attracted to her. Her heart, character, passion for Daddy... Her ability to help me lead by inviting me into that space without demanding but also submitting to it..... God, that's sexy. I've never seen that before. If I could quantify that, I would put it in a book!&nbsp;</div><div><br></div><div>In that, I can already see how she would be the one I couldn't fulfill my calling without.&nbsp;</div><div><br></div><div>She's so hot when she does that. Holding that space. Inviting but not controlling. Owning her space without allowing me to make her responsible for mine. She not only makes me want to be a better man, she helps me become the best version of myself, in many ways, a better version than I realized was inside.</div><div><br></div><div>I trust her. So far.</div><div><br></div><div>I'm starting to hope she's you. We shall see.&nbsp;</div><div><br></div><div>Goodnight Her,</div><div><br></div><div>Darrell, your him</div><div><br></div><div><br></div><div><br></div>