---
title: 'Boundaries'
date: '2020-04-04T06:24:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '378679228913363597'
blogger_filename: '/2020/04/boundaries.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">  <p class="MsoNormal">As I was speaking with a friend recently, I got to thinking about Boundaries…<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b>This World Is Broken<o:p></o:p></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">No. Really. This is a broken world. It broke in Genesis 3 and won’t be fully restored until AFTER the Tribulation and Millennial Reign of Christ. We’re a minimum of 1,007+ years from the permanent restoration of all things.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">The answer to “Why do bad things happen?” is simple, if wholly unsatisfying.  <b>In a broken world, things break</b>. Period. Bad things didn’t come to teach you a lesson. God didn’t need another angel. Nothing that happened was to make a point or example of you, in you, or through you.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Bad things happen because we live in a broken world and in a broken world, things break. Period. That’s it. That’s the whole answer…. Except, there’s a component of the brokenness that requires some extra attention.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b>Free Will Means Choices.<o:p></o:p></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Despite what some well-meaning but very mistaken Calvinists would tell you, Free Will is the epicenter of the Human Experience. God did not make robots. He does not make our choices for us. He WILL NOT make our choices for us. He flat refuses.   He’s so committed to free will that he is willing to let Hell be the result for millions who choose it.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b>Sometimes we suffer from other people’s choices<o:p></o:p></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Other people choose things. They may choose to make you an omelet or hit you with the frying pan. Either way, they chose. There’s things that influenced their choices. There’s things we sometimes do to influence their choices. In many cases,   their choices were made completely independent of us and there was nothing we could do to stop their choices.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">The drunk driver didn’t crash into that car to teach you a lesson or make you more patient, the drunk driver made a broken choice and you suffered the consequences. It sucks, sometimes we suffer from other people’s choices.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b>Sometimes we suffer from our own choices<o:p></o:p></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">You jumped off a ledge and broke your leg. God isn’t trying to teach you anything. You simply made a choice, and suffered a consequence of that choice. You slept with someone and got pregnant.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">The answer isn’t “Why are you giving me this __(fill in the blank)__, God? You know how stressed I am already!”  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">The answer is “I made a choice, and now I have a consequence. This may turn out to be bittersweet and beautiful in the end, but it’s a simple consequence nonetheless. God isn’t trying to teach me anything, he didn’t give me this to make   an example of me, he’s not trying to show me anything…” <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">It’s a simple (sometimes awful, sometimes profound) consequence of a choice.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b>Stop looking for meaning or purpose in “bad things” and start looking for opportunity.<o:p></o:p></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Once we know that bad things happen for no other “reason” than we live in a broken world and in a broken world, things break; we can stop looking for “why” or “what are you trying to teach me” and simply accept that it happened and grieve   the loss associated.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Once we know that Free Will ads a component to this broken world because often Free Will leads to broken choices, we can begin to accept that some things just are; and we can stop blaming God for Human Choices.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Once we accept that some things happened to us because someone else made a choice we couldn’t stop them from making; we can grieve what was taken from us.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Once we accept that some of our own choices led to some of our consequences; we can repent of those choices and either ask God to heal them or make peace with living with those thorns.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b>The result is more empowerment<o:p></o:p></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Once we stop blaming God or looking for reasons we can take responsibility for making new choices with the opportunities in front of us.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p><p class="MsoNormal"><o:p><br /></o:p></p></div>  