---
title: 'Dear Her PS 07/20/2020'
date: '2020-02-23T07:46:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '1731679375167384556'
blogger_filename: '/2020/02/dear-her-ps-07202020.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">  <p class="MsoNormal">PS: I don&#8217;t know why but I keep thinking I&#8217;ll meet you in July 2020. I won&#8217;t be heartbroken if I don&#8217;t, I&#8217;ve been wrong before. I also keep thinking July 20, 2020 is of some significance, don&#8217;t know why. I guess I&#8217;ll find out it isn&#8217;t or   it is. <span style="font-family:Wingdings">J</span> <span style="font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#1F497D">  <o:p></o:p></span></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  </div>  <br clear="both">  ______________________________________________________________________<BR>  The information contained in this e-mail message and any attachments may be privileged and confidential. If the reader of this message is not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that any review, dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by replying to this e-mail and delete the message and any attachments from your computer.<BR>  ______________________________________________________________________<BR>  