---
title: 'Dear Her, 04/21/2020, Season''s Changing'
date: '2020-04-22T05:50:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '5274428372531565202'
blogger_filename: '/2020/04/dear-her-04212020-seasons-changing.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Her'
---

<div>Dear Her,</div><div><br /></div><div>I'm on the verge of a new season. This one is closing...&nbsp;</div><div><br /></div><div>June 25 will be two years. So I’m at 22 months now?</div><div><br /></div><div>After learning lessons in year one, they who-shall-not-be-named... I committed to not committing to anyone from July 1, 2019 to July 1, 2020.... that’s just around the corner too.&nbsp;</div><div><br /></div><div>Through all of these things, I feel healed enough to actually give myself authentically to someone, yet, so settled into this new solo life we boys carved out I don't see space for anyone now.</div><div><br /></div><div>When Dacia and her boys were around a lot, I kind of saw how another family could theoretically fit with ours. So it's not as though I have no context, but we're settling into this groove we have for now.&nbsp;</div><div><br /></div><div>Such a weird place. I'm enjoying this season. I really am. I'm enjoying being "single", I wouldn't have believed it a year ago. But I feel a longing in my heart for you still.&nbsp;</div><div><br /></div><div>He told me in December not to let this go, but to hold it up in front of me, and pray on it, so that's what I'm doing... Sort of. I guess I am more trying not to think about it at all, and as such, I think about it a lot. Maybe time to get back on that prayer. ha ha.&nbsp;</div><div><br /></div><div>I still feel July 20 has something to do with my "Her", but that could be nothing. I don't know, the imagination of an author. We shall see.&nbsp;</div><div><br /></div><div>I hope whoever you are, wherever you are, you are well tonight. You are healed and/or healing. Shalom Love.</div><div><br /></div><div>Darrell</div><div><br /></div><div><br /></div>