---
title: 'You don''t always have to be right.'
date: '2020-02-26T05:52:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7153486631998964961'
blogger_filename: '/2020/02/you-dont-always-have-to-be-right.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Musings'
---

<div>I talked it out to myself mostly, and this is what came out...&nbsp;</div><div><br></div><div>I suppose this issue is one that makes me irrationally upset. The moment someone, like my cousin, espouses pro Socialism views... I begin to think of them as second class humans.</div><div><br></div><div>Thoughts....&nbsp;</div><div><br></div><div>1. Irrational reactions are a sign of irrational anger.</div><div><br></div><div>2. Anger is often a secondary emotion. It's a signal of a deeper emotion underneath.&nbsp;</div><div><br></div><div>3. What's underneath the anger? Fear. Fear of loosing the lifestyle I love and standing in bread lines like they do after Socialism ruined Venezuela's BOOMING Capitalist economy and turned it into a Socialist wasteland.&nbsp;</div><div><br></div><div>4. Which at it's base is a fear of loosing the comforts I have today and being out of control, like an impending doom I can't stop from coming.</div><div><br></div><div>If I keep peeling back that onion... Underneath those is a fear of loss of some Imaginary control I have over world events.&nbsp;</div><div><br></div><div>Which is a sign I am trying to be my own God, rather than letting God "turn the hearts of Kings" and "set on the throne whoever He wills".&nbsp;</div><div><br></div><div>So at it's very very very base... My irrational reactions to politics is s lack of trust in God to protect me and Father me through any circumstance.&nbsp;</div><div><br></div><div>Woah.</div><div><br></div><div>So with that knowledge, can I speak the truth in love, instead, gently pushing break in ideas without forgetting that hearts are more important than "winning" or "dominating" the discussion.</div><div><br></div><div>I've gotten into arguments all my life, having to be the one who was right. Even did it at work last week. Of course, I WAS right, but as it turns out, only 3/4 right. I was 1/4 wrong. In an attitude of humility, I could have learned that 1/4 a week earlier. Instead of sitting in my bed Sunday night rehearsing a one sided argument. Ha ha...&nbsp;</div><div><br></div><div>If I'm trusting God, I don't have to be right so the time.&nbsp;</div>