---
title: 'Stiff Necked: Bodily effects of a heart/spirit problem'
date: '2020-04-04T06:30:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7238636339036748099'
blogger_filename: '/2020/04/stiff-necked-bodily-effects-of.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1"> <p class="MsoNormal">Stiff Necked: Bodily effects of a heart/spirit problem<o:p></o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p><b><i><u>Reflection References:</u></i></b></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal"><b><u>Acts 7:51<o:p></o:p></u></b></p> <p class="MsoNormal"><a href="https://biblehub.com/acts/7-51.htm">English Standard Version</a><o:p></o:p></p> <p class="MsoNormal">"You stiff-necked people, uncircumcised in heart and ears, you always resist the Holy Spirit. <o:p></o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal"><b><u>Psalm 32 <o:p></o:p></u></b></p> <p class="MsoNormal"><a href="https://biblehub.com/bsb/psalms/32.htm">https://biblehub.com/bsb/psalms/32.htm</a><o:p></o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal">Of David. A Maskil<o:p></o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal">Blessed is he whose transgressions are forgiven, whose sins are covered.&nbsp; <o:p></o:p></p> <p class="MsoNormal">Blessed is the man whose sin the LORD does not count against him, in whose spirit there is no deceit. <o:p></o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal"><b>When I kept silent, my <i>bones</i> became brittle</b> from my groaning all day long. <o:p></o:p></p> <p class="MsoNormal">For day and night Your hand was heavy upon me; my strength was drained as in the summer heat. <o:p></o:p></p> <p class="MsoNormal">Selah <o:p></o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal">Then I <b><i>acknowledged</i></b> my sin to You and <b><i>did not hide</i></b> my iniquity. <o:p></o:p></p> <p class="MsoNormal">I said, "I will confess my transgressions to the LORD," and You <b><i>forgave</i></b> the guilt of my sin. <o:p></o:p></p> <p class="MsoNormal">Selah <o:p></o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal">Therefore let all the godly <b><i>pray</i></b> to You while You may be found. <o:p></o:p></p> <p class="MsoNormal">Surely when great waters rise, they will not come near. <o:p> </o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal">You are my hiding place. <o:p></o:p></p> <p class="MsoNormal">You protect me from trouble; <o:p></o:p></p> <p class="MsoNormal">You surround me with songs of deliverance. <o:p></o:p></p> <p class="MsoNormal">Selah <o:p></o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal"><b><i>I will instruct you and teach you the way you should go; <o:p></o:p></i></b></p> <p class="MsoNormal"><b><i>I will give you counsel and watch over you. <o:p></o:p></i></b></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal">Do not be like the horse or mule <i>(stiff necked&lt;added)</i>, which have no understanding; they must be controlled with bit and bridle to make them come to you. <o:p></o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal">Many are the sorrows of the wicked, but loving devotion surrounds him who trusts in the LORD. <o:p></o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal">Be glad in the LORD and rejoice, O righteous ones; shout for joy, all you upright in heart.<o:p></o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal"><b><u>What does the Bible say about being stiff-necked?<o:p></o:p></u></b></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal"><b><span lang="EN">Question: "What does the Bible say about being stiff-necked?"<br /> <br /> Answer: </span></b><span lang="EN">To be stiff-necked is to be obstinate and difficult to lead. The Bible often uses this figure of speech when describing the attitude of Israel toward God (e.g., <a href="https://biblia.com/bible/esv/Exod%2033.3" target="_blank">Exodus 33:3</a>; <a href="https://biblia.com/bible/esv/Deut%209.13" target="_blank">Deuteronomy 9:13</a>; <a href="https://biblia.com/bible/esv/Neh%209.16" target="_blank">Nehemiah 9:16</a>; <a href="https://biblia.com/bible/esv/Acts%207.51" target="_blank">Acts 7:51</a>). The term was originally used to describe an ox that refused to be directed by the farmer's <a href="https://www.gotquestions.org/oxgoad-Bible.html">ox goad</a>. When a farmer harnessed a team of oxen to a plow, he directed them by poking them lightly with a sharp spike on the heels or the neck to make them pick up speed or turn. An ox that refused  to be directed in such a way by the farmer was referred to as "stiff-necked." A stiff-necked animal (or person) refuses to turn the head in order to take a different path. <o:p></o:p></span></p> <p class="MsoNormal"><span lang="EN"><o:p>&nbsp;</o:p></span></p> <p class="MsoNormal"><span lang="EN">Continue reading… </span><a href="https://www.gotquestions.org/Bible-stiff-necked.html">https://www.gotquestions.org/Bible-stiff-necked.html</a><o:p></o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal"><b><u>Why Do Muscles Feel Stiff and Tight?<o:p></o:p></u></b></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal">Feel stiff? Tight? Think your range of motion is uncomfortably limited? These things often go together, but they don't always, and they definitely aren't the same. Wrapping your head around the difference is good human body owner's manual  stuff….<o:p></o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal"><b><span lang="EN">The stiffness of aging: "inflammaging" and arthritis<o:p></o:p></span></b></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal">But by far the most familiar source of inflammation — and stiffness — is probably aging. Everyone gets more inflamed as they age. This is known as "inflammaging" — I'm not making this up — and it happens to some people sooner and worse  than others…<o:p></o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal"><b><span lang="EN">Psychogenic stiffness<o:p></o:p></span></b></p> <p class="MsoNormal"><span lang="EN"><o:p>&nbsp;</o:p></span></p> <p class="MsoNormal"><span lang="EN"><a href="https://www.painscience.com/articles/anxiety.php">Anxiety disorder</a> is actually a well-known cause of dystonia. We "tense up" when we are anxious and if that emotional state is severe and persistent it becomes  a disorder and the dystonia gets entrenched.<o:p></o:p></span></p> <p class="MsoNormal"><span lang="EN">But I think psychogenic stiffness can be more nuanced. Maybe if you feel <i>emotionally stuck</i> your mind has some ways of feeling that way in the flesh as well. Some stiffness may be a form of self-expression, a common embodiment of many flavours of discontent. The transference from a state of mind to a state of body is <i>somatization</i>, and we're not as far out in left field here as you might think. Psychosomatic illness is probably more common and more serious than we realize, and milder forms therefore are also likely ubiquitous.<a href="javascript:toggleFootnote(20)">20</a>  We already know that mood, posture and even pain sensitivity can modify each other<a href="javascript:toggleFootnote(21)">21</a><a href="javascript:toggleFootnote(22)">22</a> It's really not much of a leap that <i>believing</i> you are stiff could result in <i>feeling</i> that way — even without frank dystonia.<o:p></o:p></span></p> <p class="MsoNormal"><i><span lang="EN"><o:p>&nbsp;</o:p></span></i></p> <p class="MsoNormal"><i><span lang="EN">Body is not stiff, mind is stiff.<o:p></o:p></span></i></p> <p class="MsoNormal"><b><i><span lang="EN">~</span></i></b><i><span lang="EN"> K. Pattabhi Jois<o:p></o:p></span></i></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p> <p class="MsoNormal">Continue reading… <a href="https://www.painscience.com/articles/stiffness-and-rom.php"> https://www.painscience.com/articles/stiffness-and-rom.php</a><o:p></o:p></p> <p class="MsoNormal"><o:p>&nbsp;</o:p></p><p class="MsoNormal"><o:p><br /></o:p></p></div> 