---
title: 'Processing The Day'
date: '2020-04-04T06:19:00.0000000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4523448379906619213'
blogger_filename: '/2020/04/processing-day.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">  <p class="MsoNormal">Hm….. Shelley said she intended to send an envelope with balloons, or text, but thought against both because of our timeline. It’s good to know she thought of me. Still, she was distant and non-responsive after. Guarded. I guess that makes   sense. I’ve been hyper emotional. I just miss her. But there’s also a noticeable lack of reciprocation in the “I love You” or “I Miss You”. That’s a strong message as well. But I need to stop making assumptions. Her lack of communication and silence and lack   of reciprocation IS a message… but I cannot extrapolate from that an entire disdain. I need to let her speak for herself.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">After August 21. <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">I’m growing so much, that I may be an entirely different man then anyway. I’m already stronger and more capable than I ever thought possible. But if this is how hard it is to grow up, I don’t want to. I’ll take Wounded Self back unless   it’s going to get easier. It hurts WAY too much to keep up with this bullshit. <o:p>  </o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Hannah said that I cannot serve on the team unless I correct my Facebook image. I need to be above reproach. But rather than leaving it there, she’d be willing to sit down with me and another male leader to discuss what that looks like.   I suppose that’s an opportunity to grow up some more. Flavia always said I posted too freely anyway. Justin used it as an excuse to cause problems with Dacia and the kids. I guess it would be easier if I didn’t give the devil fodder to take me out with.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Part of me, a tiny part that has yet to assert itself as the victor, is glad Shelley didn’t work out. She’s a tough cookie, and probably needs someone more successful, stronger, more capable, better bread winner… I’m just not enough for   her. I can’t stand up to the weight of her calling and personality. Part of me is hoping for an “easier” partner. I want someone strong, independent, a lot like Shelley… but… I don’t want to always feel “on” or like I have to perform or win their attention.   I just want it to be easy between. <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">My partner needs to be someone I feel relaxed and at peace with. If I have to have a loud OR silent battle, forget it. I was ignored and misunderstood and invalidated for 14 years… never again.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">At the same time… I’ve never met anyone like Shelley. What if the very easy, passive women in my life is just what I’m used to? What if a partner worth pursuing requires this much effort to win her over? What if Shelley needs me to pursue   her? AAAHHH… so many what ifs? <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">In this moment? I can’t. I proclaimed God’s decision for 60-days, and she’s abiding by it whether I do or not now.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">I guess time will tell. But I miss my friend. <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">I hate this.</p><p class="MsoNormal"><br /></p><p class="MsoNormal"><br /></p></div>  