---
title: 'Dear Her 08/16/2020'
date: '2020-08-16T07:37:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '3314341178972368956'
blogger_filename: '/2020/08/dear-her-08162020.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Dear Her'
---

<p>&nbsp;Dear Her,</p><p>Confused in North Pole, Idaho. I don't know what to make of this chick Jen. I can't get a read on her. She's amazing. She makes me feel safe. She engages the boys and they seem to really enjoy having her around.&nbsp;</p><p>But at the same time, I feel like she's kind of doing her own thing. She doesn't really need us but does want us. She is so out of sync with any kind of schedule, that even if she says she'll do something or be somewhere, she may not or may not be there when she said she would. Or she'll start something and not finish it.&nbsp;</p><p>Which is a potential Character Defect; or, it's just Widow Brain.&nbsp;</p><p>She's only 8-months into loss and I can't judge her today. If you'd met me 8 months into loss, you'd have got the guy who was destroyed by Shelley. He no longer exists. Which may be the other issue. I think Shelley broke me. She broke the part of me that can let someone in. After Flavia, I felt more loved by Shelley than anyone had ever helped me feel. And then just like that, she left abruptly. Proving my picker is broken, and locking me down like Fort Knox. Now here I am, a year later, and the most amazing partner is here, and I can't feel what I want to feel. I don't feel a "no", I don't feel a "yes"... just... silence. Maybe I need to heal more than I thought still.&nbsp;</p><p>But as I've said from day one, I don't have to "know" today. I am pretty sure I'm going to marry her. But I am not 100% positive. Until I "know", I cannot bind myself to her for life. For today, I will keep getting to know her. Let her challenge me in new ways, help me become more like Christ. Let other's watch her and give me insight into her through their eyes. Study her.&nbsp;</p><p>We shall see. For today, I think she's the best partner I've ever had the opportunity to know. I love her. I enjoy her wit and her view on life. I love how she loves people, and chooses to see the potential in even the most "vile" person. Because she doesn't see humans as her enemy, the enemy is the spirit influencing them. The person is just a person, a human that God made and died for. That's a perspective that is Christ-Like, even if it is irritating. And it's one I would enjoy having more of in my own heart.&nbsp;</p><p>She arrived 06/26/2020. On 07/26/2020, I broke both my legs at an event she invited me to. Either that's a sign I should stay away from her, or a sign that the enemy is out to attack what God is building. I'm believing the latter. So here it is, 08/16/2020, and I'm post-operative, wheelchair bound, with Mom in town and no way to be "alone" together. If this isn't a good test of "us", I don't know what is. I think he's knitting us together. That's how I'm still seeing it. So I will keep moving forward until I get a firm "yes" or "no".&nbsp;</p><p>Goodnight Her... If you're Jen, you should find this very entertaining. You probably will even if you're not.&nbsp;</p><p>Thank you for reading my madness,&nbsp;</p><p>Darrell Wolfe, your Him.&nbsp;&nbsp;</p><p><br /></p><p><br /></p>