---
title: 'Seek First to Understand'
date: '2020-04-04T06:38:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '4872195813658499830'
blogger_filename: '/2020/04/seek-first-to-understand.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
---

<div class="WordSection1">  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Do not seek to be understood; rather, seek to understand. <o:p>  </o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">In a culture of NO HIDING, it’s important that we not only force ourselves to embrace brutal honesty with ourselves and others but that we seek to truly understand ourselves an others as well.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Honesty with Self:<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">It’s not enough to acknowledge that something upset you, go deeper. Why did that upset you?<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Honesty with Others:<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">It’s not enough to tell someone that you are angry, go deeper. Why are you angry? “When you… I felt…”<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Honesty of Others:<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">It’s not enough to know that someone else has spoken, go deeper. What are they really telling you? What is the emotional truth they are trying to convey?<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">Honesty of Self-Care:<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">It’s not enough to try to communicate, go deeper. Ask why the communication is failing. Try different methods. If in the end it’s just not working… stop trying. Cut your losses. Move on, either from the discussion or maybe even the relationship.   It’s not worth getting back-tracked over it. <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><br /></p></div>  