---
title: 'Journal Entry 01/27/2021'
date: '2021-01-27T18:30:00.0030000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '8095553774372404009'
blogger_filename: '/2021/01/journal-entry-01272021.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Journal'
---

<p>I was sitting at my desk, looked for an email from Preston's doctor so I could forward the documents, which I didn't find. Then I started cleaning out old emails and folders I didn't need. Then I read a few Flavia related emails and cried. I miss her and I wish we'd found a greater level of intimacy while we were together.&nbsp;</p><p>Then I read my Dear Shelley email and cried some more. I felt every word and it's been almost two years since she left. Almost three since Flavia died.&nbsp;</p><p>How can Jen give me everything they didn't and I feel so apathetic towards her lately? Am I waiting for her to leave too? Like they did?&nbsp;</p><p>Did I close my heart to anyone else that may come and now it's closed to the one that would be worth pursuing?&nbsp;</p><p>When I think of the things that I "don't like" they're all silly things, meaningless at some level. I want to go out to eat and enjoy a meal with my bride but she doesn't eat most days and hardly ever when we go out. We can't enjoy a meal together. Yet, I'm chaning my food habits anyway, and my choices are blending into what she already does. So maybe we can?<br /></p><p>She doesn't watch many of the things I watch, so I cannot share story with her. But, the things I watch are feeling gross in my spirit anyway lately. Like I need to detox from the world's entertainment and purify my soul. So maybe I'm changing to become more like her? But I still want to sit and watch things together. Can we do that?</p><p>More importantly, who is she?&nbsp;</p><p>She is one who draws me closer to God. She is one who shows me God's heart. She is one who loves my children. She is one who supports me even when I'm being an ass. She is strong enough to stand on her own. She is quite far down the road in recovery from codependency. She is teachable. She is heart driven while in need of clearer thinking on certain "basics" of the faith. Meanwhile, her heart for people is closer to God's than mine.&nbsp;</p><p>I am the brain in need of her heart, she is the heart in need of my brain.&nbsp;</p><p>She's odd. Throws people off. But I think she might be perfect for us.&nbsp;</p><p>I don't see how all the pieces fit. How would we combine households or would we?&nbsp;</p><p>What does getting married without paper look like? What does getting married mean at our age with blended families?&nbsp;</p><p>How do two like us become "one"?&nbsp;</p><p>I think that means something different at 40 than it did at 20, or does it?&nbsp;</p><p>Okay, back to homework. <br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p><p><br /></p>