---
title: 'Flavia Dream'
date: '2021-05-28T13:41:00.0010000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '665874442129038187'
blogger_filename: '/2021/05/flavia-dream.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'Flavia'
  - 'dream'
---

<div>Flavia Dream</div><div>May 28, 2021, 6:23 AM PST</div><div><br></div><div>Flavia comes back, but I'm already with Jen.</div><div><br></div><div>She has our baby with her. It turns out, she said the hospital had left a voicemail but since I didn't call back she decided to live her own life. The only reason she called was because the cop pulled her over and she needed her ID and didn't have it.&nbsp;</div><div><br></div><div>I went through documents on my cloud storage sending the cop IDs and such, and she let her go.&nbsp;</div><div><br></div><div>While I was looking through IDs, I found photos of her naked, and her naked with her best girlfriend (all old old photos, but, I'd never seen them).&nbsp;</div><div><br></div><div>Now she's at my house. Jen's asleep in my bed, I give Flavia the guest bed.&nbsp;</div><div><br></div><div>She and I are talking about what's next.</div><div><br></div><div>I said, if you'd come back immediately, it would be a no brainer.&nbsp;</div><div><br></div><div>But now.....</div><div><br></div><div>I'm not who I was anymore. You're obviously not who you were. I have Jen now. Our vows were fulfilled. I was your husband until death do us part, and death parted us. You chose to remain dead to us, to your boys, your Mom... So you died, and I lived, and now I've moved forward.&nbsp;</div><div><br></div><div>She said we could be friends, and raise our child together but not be married. She seemed to want that.&nbsp;</div><div><br></div><div>I was upset, because she was the Flavia I always wanted. Strong, independent, skinny.&nbsp;</div><div><br></div><div>I was relieved, because she was different, so was I, and I had a new life with Jen.</div><div><br></div><div>I sort of woke up before the last part, but, I knew instinctively that's where is was headed.&nbsp;</div><div><br></div><div>Waking...</div><div><br></div><div>I miss her. Terribly. I wish she could see me now, who I am today. If she'd been here for the growth, I'd be proud of what we'd built. But if she came back, today, or was discovered alive today the whole time, I don't think I'd go back.&nbsp;</div><div><br></div><div>She's my past, she's Flavia Dream</div><div>May 28, 2021, 6:23 AM PST</div><div><br></div><div>Flavia comes back, but I'm already with Jen.</div><div><br></div><div>She has our baby with her. It turns out, she said the hospital had left a voicemail but since I didn't call back she decided to live her own life. The only reason she called was because the cop pulled her over and she needed her ID and didn't have it.&nbsp;</div><div><br></div><div>I went through documents on my cloud storage sending the cop IDs and such, and she let her go.&nbsp;</div><div><br></div><div>While I was looking through IDs, I found photos of her naked, and her naked with her best girlfriend (all old old photos, but, I'd never seen them).&nbsp;</div><div><br></div><div>Now she's at my house. Jen's asleep in my bed, I give Flavia the guest bed.&nbsp;</div><div><br></div><div>She and I are talking about what's next.</div><div><br></div><div>I said, if you'd come back immediately, it would be a no brainer.&nbsp;</div><div><br></div><div>But now.....</div><div><br></div><div>I'm not who I was anymore. You're obviously not who you were. I have Jen now. Our vows were fulfilled. I was your husband until death do us part, and death parted us. You chose to remain dead to us, to your boys, your Mom... So you died, and I lived, and now I've moved forward.&nbsp;</div><div><br></div><div>She said we could be friends, and raise our child together but not be married. She seemed to want that.&nbsp;</div><div><br></div><div>I was upset, because she was the Flavia I always wanted. Strong, independent, skinny.&nbsp;</div><div><br></div><div>I was relieved, because she was different, so was I, and I had a new life with Jen.</div><div><br></div><div>I sort of woke up before the last part, but, I knew instinctively that's where is was headed.&nbsp;</div><div><br></div><div>Waking...</div><div><br></div><div>I miss her. Terribly. I wish she could see me now, who I am today. If she'd been here for the growth, I'd be proud of what we'd built. But if she came back, today, or was discovered alive today the whole time, I don't think I'd go back.&nbsp;</div><div><br></div><div>She's my past, she's not my future.&nbsp;</div><div><br></div><div>Selah</div><div><br></div>