---
title: 'Dream Emily - Goodbye'
date: '2023-07-30T15:19:00.0020000+00:00'
draft: true
blogger_blog: '(My Journal) Fed By Faith'
blogger_status: 'LIVE'
blogger_post_id: '7303779391717066274'
blogger_filename: '/2023/07/dream-emily.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/(My Journal) Fed By Faith/feed.atom'
categories:
  - 'dream'
---

Emily,<div><br></div><div>You'll never read this. Even when Flavia died you didn't make contact, so I'm sure you won't if I'm gone. And I'm sure I'll never send this to you. I guess I just really needed to process this.</div><div><br></div><div>It is July 30, 2023. I just woke up after having a WIERD dream about you.&nbsp;</div><div><br></div><div>Dream--</div><div>You had been injured in some way? Maybe a surgery? There was also a play involved, and I watched from a distance as some other guy was being celebrated as the up and coming star actor of the play. I came to your house, knowing it had been decades, but I came because you needed me. I would always move mountains if you needed me. I cleaned up, set you up with heating pads and moves the couches so your be comfortable. I remember thinking the guy who liked you hated me, but I would stay anyway because you needed me. I slept on the couch. You slept in your room. I woke up and started looking at my year books and family albums, realizing you had them for some reason? Maybe doing research you needed to borrow them. I was walking down the hall naked to the bathroom, when you came out the door. But you looked me in the eye, you didn't look down or acknowledge my state, you didn't smile, but you didn't not smile? You left for work. I woke up.&nbsp;</div><div>--End Dream</div><div><br></div><div>-- Processing&nbsp;</div><div>I was curious about you, I saw your LinkedIn. You went to Westmont, Azusa, Job 1, Job 2. Four places in 23 years. I moved that often in one year.&nbsp;</div><div><br></div><div>My yearbook had various girls giving me their number, and I only had eyes for you.</div><div><br></div><div>I'm sorry.&nbsp;</div><div><br></div><div>I wish I could have been yours.&nbsp;</div><div><br></div><div>I don't know why you're still the one my heart is locked on after all this time. I guess, to call a trope, you're "the one that got away", or whatever.</div><div><br></div><div>I was awful to you. And your mom was right not to like me, I was unstable, and weak, and broken. I hope you had a good marriage and enjoyed your life. I wasn't the kind of man I'd wanted you to marry until well into my late 30s early 40s.&nbsp;</div><div><br></div><div>I was unhealthy, unstable, and didn't know until this passed year at 43, I'm autistic. Now that I understand that, I can understand the ways I've reacted. If I'd known then, things would have been so much different. I could have learned to self regulate, self sooth, stopped looking for external validation, I could have been stable, and maybe... Maybe I could have been yours, and you could have been mine.&nbsp;</div><div><br></div><div>I've made a lot of mistakes in my life. Most of the mistakes I'm grateful for, because I learned and grew through them.&nbsp;</div><div><br></div><div>You're my only real regret. You were so kind to me, and I pissed on it. I didn't fully know what I was pissing on. I didn't understand you liked me the way I wanted you to. "How could someone like her like me that way?" - was the internal script I was running. I knew what I did was "wrong", but I didn't fully understand or acknowledge to myself why until counseling in my late thirties.</div><div><br></div><div>I'm sorry that I became the antagonist in your story, so much that you cut me out of your life completely when I married Flavia.&nbsp;</div><div><br></div><div>I will always love you, emotionally. I didn't Agape you, and I'm sorry.&nbsp;</div><div><br></div><div>Please forgive me.&nbsp;</div><div><br></div><div>I guess I'll see you in heaven one day, or in New Creation.</div><div><br></div><div>Shalom,</div><div><br></div><div>Darrell Wolfe&nbsp;</div><div><br></div><div><br></div><div>Afterthoughts... While speaking with Theresa:</div><div><br></div><div>My counselor always says: Let's get curious about that. What inside of you resonates with it? What emotional need might need to be met in 2023 that wasn't being met then?</div><div><br></div><div>I suppose for my morning reminiscing, it's more like what does 19-year old Darrell need to hear from 43-year old Darrell today?</div><div><br></div><div>To 19-Year Old Darrell, 43-year old Darrell says:&nbsp;</div><div><br></div><div>I see you. I here you. I forgive you for failing. I honor your attempts to overcome the adversity of a brokenness you wouldn't understand for 25+ more years. You can let go now, I have it. I'll take it from here.</div><div><br></div><div>Continue... I'm sorry you miss your best friend. Yes, she's gone because of your actions. But you have grown, and you've honored the part of you that wanted to do well by her. You've become who you'd always hoped you could be, and better. And you've made new friends, who love and honor you for who you are. And you've learned not to be a puppy, but a man. And that has paid dividends. Wish your young self and young friend well, and let them go. You are a new human today.</div><div><br></div><div>Selah</div><div><br></div><div>(woke up with a vivid dream about the love of my life that I failed at 19, and lost completely at 23).</div><div><br></div><div>Just took a shower. Realized something else.</div><div><br></div><div><br></div><div>To Young Darrell, she didn't fail you, per se, but you did accurately pick up on something important about her.&nbsp;</div><div><br></div><div>She, her mom, and her sisters all unanimously treated the father poorly.&nbsp;</div><div><br></div><div>When she spoke to you, she used sarcasm to poke fun at the places you didn't measure up.&nbsp;</div><div><br></div><div>You didn't let yourself get close to her and kept her friend zoned because you didn't feel good enough for her. And legitimately, you'd have cheated on her like you eventually did Flavia, probably sooner because she was less supportive than Flavia. So yes, you'd have failed Emily.&nbsp;</div><div><br></div><div>But part of the reason you didn't feel good enough, was that she chided and corrected for more often than she praised. She ran from conflict. In many ways, Shelley and Emily shared a lot of traits.&nbsp;</div><div><br></div><div>It "didn't work out" for very legitimate reasons on both sides.&nbsp;</div><div><br></div><div>And it's time to take her off the pedestal of your review mirror, and see her for the broken human she was.&nbsp;</div><div><br></div><div>It didn't work, because you were both broken, and you both failed each other, you failed to be good partners as friends, and therefore never could go beyond friends.&nbsp;</div><div><br></div><div>It's a good thing you didn't get together, it really is.</div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div>