---
title: 'Coeur d''Alene (CDA) ID | Resources'
date: '2016-06-06T03:05:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Destination Coeur d''Alene, Idaho'
blogger_status: 'LIVE'
blogger_page_id: '401893488033306968'
blogger_filename: '/p/cda-resources.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Destination Coeur d_Alene, Idaho/feed.atom'
---

<h3>
This page is an ever growing list of links, tools, sites, and resources to help us (and you maybe) make the move to Coeur d'Alene, Idaho.&nbsp;</h3>
<div>
<br /></div>
<h4>
About Coeur d'Alene (CDA) ID Specific Sites:</h4>
<div>
<ul>
<li><b>Churches:</b></li>
<ul>
<li><a href="http://lakecity.church/" target="_blank">Lake City Church (CDA, ID)</a></li>
<li><a href="http://www.oneplacechurch.com/" target="_blank">One Place Church</a></li>
<li><a href="http://heartofthecitychurch.org/" target="_blank">Heart of the City Church</a></li>
</ul>
</ul>
</div>
<div>
<ul>
<li><b>CDA Overview:&nbsp;</b></li>
<ul>
<li><a href="https://en.wikipedia.org/wiki/Coeur_d%27Alene,_Idaho" target="_blank">Coeur d'Alene (WIKI)</a></li>
<li><a href="http://www.cdatribe-nsn.gov/" target="_blank">The Coeur d'Alene Tribe of Indians</a></li>
</ul>
</ul>
<ul>
<li><b>Government and Official Sites:</b></li>
<ul>
<li><a href="http://cdaid.org/" target="_blank">City of Coeur d'Alene</a></li>
<li><a href="http://www.cdachamber.com/" target="_blank">CDA Chamber of Commerce</a></li>
<li><a href="http://www.cdalibrary.org/" target="_blank">CDA City Library</a></li>
</ul>
</ul>
<ul>
<li><b>Getting Around / Travel Sites:</b></li>
<ul>
<li><a href="http://coeurdalene.org/">Coeurdalene.org</a></li>
<li><a href="http://cdaresort.com/">CDAResort.com</a></li>
<li><a href="https://visitidaho.org/places-to-stay/coeur-dalene/" target="_blank">Visit Idaho: CDA</a>&nbsp;</li>
<li><a href="http://www.cdadowntown.com/" target="_blank">CDA Down Town</a></li>
<li><a href="https://www.tripadvisor.com/Tourism-g35418-Coeur_d_Alene_Idaho-Vacations.html" target="_blank">Trip Adviser CDA</a></li>
</ul>
</ul>
<div>
<br /></div>
</div>
<h4>
State of Idaho Sites (Licenses, Registrations, Voting, Etc...):</h4>
<div>
<ul>
<li><b>Drivers Licenses (<a href="http://destinationcoeurdalene.blogspot.com/2016/06/getting-idaho-drivers-license-after.html" target="_blank">HERE</a>)</b></li>
<li>Car Registration</li>
<li>Voting in Idaho</li>
<li>Other Licences</li>
</ul>
</div>
<ul>
</ul>
<div>
<div>
<br /></div>
<h4>
Moving, Packing, Buying, &amp; Selling:</h4>
<div>
<div>
<b>Travel Planning</b></div>
<ul>
<li><a href="https://www.aaawa.com/index.asp?zip=83815&amp;devicecd=PC" target="_blank">AAA Idaho/Oregon/Washington</a></li>
<li><a href="http://coeurdalene.org/">Coeurdalene.org</a></li>
<li><a href="http://cdaresort.com/">CDAResort.com</a></li>
<li><a href="https://visitidaho.org/places-to-stay/coeur-dalene/" target="_blank">Visit Idaho: CDA</a>&nbsp;</li>
</ul>
<div>
<b>Moving</b></div>
<ul>
<li><a href="http://www.realsimple.com/home-organizing/organizing/moving/moving-checklist">Real Simple's Moving Checklist</a></li>
<li><a href="http://moving.about.com/od/afterthemove/a/after_checklist.htm">Moving.About: After Moving Checklist</a></li>
<li><a href="http://123relocation.com/Texas/">123 Relocation Guide</a></li>
<li><a href="http://www.dmv.org/tx-texas/relocation">DMV Relocation Guide</a></li>
<li><a href="http://www.emic.org/downloads_all.php?cat=10">EMIC Relocation Packet</a></li>
</ul>
</div>
<div>
<div>
<br /></div>
<b>Home Owners</b><br />
<ul>
<li>Fixing the home to sell, fixing the home you buy:</li>
<ul>
<li><a href="http://www.todayshomeowner.com/">Todays Home Owners - DIY Home Ownership</a></li>
<li><a href="http://www.diynetwork.com/">DIY Network</a></li>
</ul>
</ul>
</div>
<div>
<ul>
<li>Utility Information</li>
<ul>
<li>Gas</li>
<li>Electric</li>
<li>Water/Sewer/Trash</li>
<li>Telephone</li>
<li>Cable/Internet</li>
</ul>
</ul>
</div>
<div>
<ul>
<li>Finding Your Home</li>
<ul>
<li>Relocation Services</li>
</ul>
</ul>
</div>
<div>
<br /></div>
<h4>
OH... What Fun! (Things to do in CDA):</h4>
<div>
<ul>
<li><a href="http://www.silverwoodthemepark.com/" target="_blank">Silverwood Theme Park</a></li>
</ul>
</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
Darrell Wolfe, and Family</div>
</div>
