---
title: 'Widowed with a child'
date: '2019-06-04T21:28:00.0000000+00:00'
draft: true
blogger_blog: 'Grief Sucks'
blogger_status: 'DRAFT'
blogger_post_id: '1062990013007134315'
blogger_filename: '/2019/06/widowed-with-child.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Grief Sucks/feed.atom'
categories:
  - 'Written By Adrianne Butwell'
  - 'Edited by Darrell Wolfe'
---

<br />
<br />
<br />
Widowhood is easily one of the most difficult and soul-crushing times in one’s life. You receive the phone call, or you find your spouse, or whatever events lead up to the realization that your soul mate has died.<br />
<br />
Now you have so much to do and so much to feel. So many people who need to be told, and you wonder HOW to tell someone that your lover has died! Then your thoughts immediately go someplace unexplainably difficult. You need to tell someone so innocent and so incredibly loved by yourself and your spouse.<br />
<br />
You need to tell your child.<br />
<br />
This miraculous little being created by the love between you and your spouse needs to know that one of their parents will never kiss them again. One parent will never be at a football game or award ceremony ever again. One parent won’t be at their wedding or at the birth of their very own child.<br />
<br />
Tears are building up in my eyes as I write this. As I remember these exact same thoughts that ran through my own mind, I dread those thoughts in anybody having to experience them. The police were still in my home and I kept asking anyone who would come near me, “What do I tell my daughter?”<br />
<br />
The best piece of advice that I received from one of the officers that morning if you haven’t already done so, is to tell your child the truth. “There was a tragic accident, and your mom/dad has died.” As hard as it is to tell them this information, it is absolutely necessary. Your child will need to grieve the loss of their parent, just as you will need to grieve the loss of your partner.<br />
<br />
Seeing as you are reading this article, chances are that you have already told your child and you’re trying hard to work through your own heartbreaking grief.<br />
<br />
In the weeks and months after this, you will likely see changes in your child and their behavior. Some children get very clingy and worrisome over their living parent. Some children will ask how they can die so they can see their deceased parent. Some might act out in school or at home, or tell you that if their other parent was alive then they would get what they want (even if that’s not true). Some children are going to have these and other changes and thoughts as well.<br />
<br />
One good thing to do is to get them into a counselor who specializes in childhood trauma and grief. Your child may or may not connect with this new person, but it’s important to allow them to try. You can join in a family counseling session as well.<br />
<br />
Your child is going to need you at this time in their life like never before. But you are dying inside!<br />
<br />
People are telling you that you need to be strong, or that you are SO strong. The norm is that we don’t feel strong at this time and we aren’t strong. We are maintaining and that may be all we can do.<br />
<br />
Your child needs to see you mourn the loss of their parent. It’s important to remember that although they need to and certainly WILL see us cry, they can’t see us crying all day every day. If you’ve ever flown in a commercial airline, you’ll know that if the oxygen mask falls you need to give yourself the mask before placing one on your child. This is for the simple fact that we cannot care for our children unless we are well enough to do so.<br />
<br />
Certain times during the day can trigger meltdowns for us more than others, so in order to function as best as we can, it’s important to know when these times occur for you and to help reduce them.<br />
<br />
First thing in the morning is a common trigger because that’s when we forget that it really happened and hope it was a nightmare. Then we realize that it is our new life, and it’s hard to continue on with the morning routine.<br />
<br />
Driving at all can be a big trigger because that’s when we call our spouse, listen to music, or give ourselves time to be alone with our thoughts.<br />
<br />
Depending on your job that can be a trigger. If you work in a quiet office, if you worked with your spouse, you texted all day long, etc.<br />
<br />
One huge one is the time between getting the kids to sleep and the time you go to sleep.<br />
<br />
If your child sees you crying all day every day, and not able to care for them anymore they may think that they have to stop their grieving in order to help you with yours and this is not good for them.<br />
So in order to help your child the most during this time, you can try to control your own meltdowns.<br />
<br />
The commonality between the times of day that I mentioned is the sound of them, whether it be quiet or not. Changing the sound of those times can help. Specifically, talk radio instead of songs that may consume your thoughts, and listening to guided meditations to go to sleep can help with the deafening quiet at night.<br />
<br />
Allowing yourself to have your own meltdowns when the children go to sleep can give you a sense of relief and freedom to cry how you need. You can look at pictures, listen to songs, watch wedding videos, or anything else that you find comfort in. You can hold your spouse’s pillow and weep. Anything you need to do in order to help you cope can happen in the privacy of the night.<br />
<br />
Now there are going to be times when you breakdown in front of your child (or anybody else for that matter), and that is absolutely okay! We are devastated and our lives are forever changed, and it’s perfectly acceptable to let that show. The hope here that some of that can be controlled so that you can still function as a parent.<br />
<br />
One day you’ll be able to smile again and have fun with your little one. Until that day comes we can only try our best and work every day at it.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div style="text-align: center;">
***</div>
<br />
Thank you for spending time with us today.<br />
<br />
We hope this helps you either process your own grief or understand those in your life going through it. Please check out our <a href="https://griefsucksawidowsguide.blogspot.com/p/resources.html" target="_blank">Resources</a> page for more articles and some links to the tools we've found helpful. For more about who we are, click&nbsp;<a href="https://griefsucksawidowsguide.blogspot.com/p/about-us.html" target="_blank">About Us</a>.<br />
<br />
<br />
Adrianne and Darrell, fellow Widows/Widowers