---
title: '15 odd triggers of a meltdown'
date: '2019-06-11T19:10:00.0020000+00:00'
draft: true
blogger_blog: 'Grief Sucks'
blogger_status: 'DRAFT'
blogger_post_id: '7747079327088948038'
blogger_filename: '/2019/06/15-odd-triggers-of-meltdown.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Grief Sucks/feed.atom'
categories:
  - 'Written By Adrianne Butwell'
  - 'Edited by Darrell Wolfe'
---

<br />
<br />
<br />
As we grieve, we have different ways of experiencing a tremendous emotional breakdown. Most commonly we will have spells of uncontrollably crying, we may have the urge to act out physically. Whatever it is that you do in particular, you know what it is. For the purpose of this article, I’m going to call it a “meltdown.” I don’t know of a better term to use that encompasses the feelings of sheer desperation and helplessness that comes with the loss of a spouse.<br />
<br />
Any one of our senses may be stimulated when we experience a trigger, and sometimes they are in the oddest of places.<br />
<br />
So here are 15 triggers that have sparked an unexpected emotional meltdown in a fellow widow...<br />
<br />
<br />
Seeing or hearing the sound of a motorcycle driving if they died in a motorcycle accident<br />
<br />
An advertisement for the hospital they died in<br />
<br />
Hearing the sound of EMS sirens<br />
<br />
Someone introducing themselves and they have the same name as your departed spouse<br />
<br />
Your coffee shop not having your favorite drink<br />
<br />
Finding that someone has eaten your spouse’s food<br />
<br />
Seeing an item on a restaurant menu that your spouse would have ordered<br />
<br />
A commercial advertisement of the show they had been waiting to watch<br />
<br />
Check Engine Light on the car comes on and your spouse used to handle that<br />
<br />
Older couples walking together in public<br />
<br />
Seeing His and Her sets in stores<br />
<br />
A family looking happy together in public<br />
<br />
Paying a bill that they normally paid<br />
<br />
Closing down any of their accounts<br />
<br />
Seeing the word “widow” or “widower” on paper and referring to you<br />
<br />
<br />
<br />
<br />
<div style="text-align: center;">
***</div>
<br />
Thank you for spending time with us today.<br />
<br />
We hope this helps you either process your own grief or understand those in your life going through it. Please check out our <a href="https://griefsucksawidowsguide.blogspot.com/p/resources.html" target="_blank">Resources</a> page for more articles and some links to the tools we've found helpful. For more about who we are, click&nbsp;<a href="https://griefsucksawidowsguide.blogspot.com/p/about-us.html" target="_blank">About Us</a>.<br />
<br />
<br />
Adrianne and Darrell, fellow Widows/Widowers