---
title: 'Loneliness of a widow'
date: '2019-06-06T18:11:00.0010000+00:00'
draft: true
blogger_blog: 'Grief Sucks'
blogger_status: 'DRAFT'
blogger_post_id: '1320158437571628993'
blogger_filename: '/2019/06/loneliness-of-widow.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Grief Sucks/feed.atom'
categories:
  - 'Written By Adrianne Butwell'
  - 'Edited by Darrell Wolfe'
---

The loneliness of a widow<br />
<br />
Is there anything more lonely than being a widow? There are definitely people in different situations who will tell you that they are lonelier than us, but this isn’t a competition for the loneliest place on Earth is it?<br />
<br />
With the death of our spouse, we are now “I” instead of “we.” We wake up alone and sleep alone.<br />
<br />
Every single thing in our life changes the moment that our spouse dies.<br />
<br />
Grocery shopping changes and we no longer know what to cook or we choose to buy premade meals to avoid cooking altogether.<br />
<br />
Time spent watching TV is lonely because we used to have a couch buddy and we had our shows we watched as a couple.<br />
<br />
Walking in stores is lonely because we used to text pictures of things we’d see to our spouse and laugh about it together. Now we think of what we would have done, and walk past it with the gaping hole that once housed our heart.<br />
<br />
Any event hosted by a friend or relative that we would have attended as a couple now becomes something we try to get out of, or something we go to but feel like the only person in the room, in a room filled with people.<br />
<br />
A once casual thing, like coming home from anywhere, is now dreadful. We are now coming to an empty and silent home that used to be filled with love and laughter.<br />
<br />
Have you picked up the phone and felt lonely? The friend on the other end of the phone asks “Hey! What are you doing this weekend?” Your truthful response would be, “Saturday I’ll be grocery shopping for 7 frozen dinners to get me through the week, then coming home to weep. Sunday I’m thinking of laying in bed binge watching anything that might keep my mind numb until I get to go back to work on Monday.” Your real response is, “Hi! Well the usual weekend routine. Grocery shopping, hanging around the house, a little TV. No big plans.” The loneliness of the truth is too much to give out to a friend who just simply doesn’t understand.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div style="text-align: center;">
***</div>
<br />
Thank you for spending time with us today.<br />
<br />
We hope this helps you either process your own grief or understand those in your life going through it. Please check out our <a href="https://griefsucksawidowsguide.blogspot.com/p/resources.html" target="_blank">Resources</a> page for more articles and some links to the tools we've found helpful. For more about who we are, click&nbsp;<a href="https://griefsucksawidowsguide.blogspot.com/p/about-us.html" target="_blank">About Us</a>.<br />
<br />
<br />
Adrianne and Darrell, fellow Widows/Widowers