---
title: 'Desperate heart of the widow'
date: '2019-06-06T07:17:00.0010000+00:00'
draft: true
blogger_blog: 'Grief Sucks'
blogger_status: 'DRAFT'
blogger_post_id: '4403073384673158763'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Grief Sucks/feed.atom'
categories:
  - 'Written By Adrianne Butwell'
  - 'Edited by Darrell Wolfe'
---

<br />
<br />
<br />
<br />
<br />
Upon the legal or verbal commitment between you and your significant other, your heart overflows with love. You could pass this love out to everyone you know and there would probably be more left over. Your joy is visible on your face and everyone that knows you are happy that you and your person have found each other.<br />
<br />
Then they die.<br />
<br />
You were supposed to grow old together and watch your children and grandchildren grow up. You had dreams of holding hand on your porch swing, matching coffee mugs, and the sun rising over the open fields that stretch out in front of you. Once one of you passed, the other would move in with your children and be loved and cared for, with hugs and family dinners everyday.<br />
<br />
They died decades too early for any of this, so now you’re left with a gaping space in your heart. You wish to be with them again, but must wait out the remainder of your own life.<br />
<br />
Your heart yearns for the love you once had with your partner. You can’t imagine going on without someone to sit next to on the couch, or hug you after work.<br />
<br />
What are you supposed to do when you had so many unspoken dreams for your future?<br />
Not only that, but how do you get through another night without the warmth of another’s touch?<br />
<br />
___________________________________________________________________<br />
<br />
Anytime we experience love, there is something or someone attached to that love.<br />
Think about that for a moment… If I list things that I love, I would include my family members, my pets, my friends, some possessions, etc. Any of those things that are listed are things that I can touch.<br />
<br />
The exception is love of a spiritual nature. With spirituality, our love is based on faith, and having faith in that love can bring about a sense of joy in itself. Therefore, the faith fills in the space where we can’t physically touch our spirituality.<br />
<br />
When listing someone who has passed away, there is a sadness associated with loving them because we cannot talk with them and touch them any longer.<br />
<br />
Something that happens very frequently is that we have a strong desire to fill that space with someone else. Our heart is so desperate that we can easily latch onto someone or the idea of a relationship when we really shouldn’t.<br />
<br />
Many people will get into relationships very shortly after their spouse has died because they have such a strong desire to have a fulfilling love again.<br />
<br />
Some of us will get into imagined relationships with people in our lives who are offering no more than friendship. Our judgement can be clouded because we are so hurt.<br />
<br />
Often times, and occasionally more common with widowers than widows, we find ourselves involved in hook-ups and one night stands even if we’ve never done this in the past. We may think that being held for one night will give us something with which we can fill our heart’s void, when in fact we learn that it can’t do that for us.<br />
<br />
Emotionally we are struggling to get back to our old normal when that’s an impossible feat. The first months and years after a spouse dies are a time of desperation for some of us, and having a rational mind can prove to be more than difficult. Because of this, we may find that the person we choose to spend our time with is the wrong person for us. It may also be that the person seems super understanding of our situation and may act as an emotional crutch.<br />
<br />
Be gentle with yourself and know that this is a season that we often go through after losing our spouse.<br />
<br />
I love hearing stories of people finding their “Chapter 2” shortly after their spouse died, because they are able to experience true love once again. I know they will miss their late spouse, but they have a beautiful new love that they are able to give and receive.<br />
<br />
For the rest of us, we wait. We forgive ourselves and we allow this season of our grief to pass as comfortably as possible. Having a friend over and cuddling on the couch isn’t a crime, right? Just be aware that guilt may come as a result and your forgiveness of yourself must come after that.<br />
<div>
<br /></div>
<br />
<br />
<br />
<br />
<br />
<div style="text-align: center;">
***</div>
<br />
Thank you for spending time with us today.<br />
<br />
We hope this helps you either process your own grief or understand those in your life going through it. Please check out our <a href="https://griefsucksawidowsguide.blogspot.com/p/resources.html" target="_blank">Resources</a> page for more articles and some links to the tools we've found helpful. For more about who we are, click&nbsp;<a href="https://griefsucksawidowsguide.blogspot.com/p/about-us.html" target="_blank">About Us</a>.<br />
<br />
<br />
Adrianne and Darrell, fellow Widows/Widowers