---
title: 'I''m a Widower. My Sex Drive has increased to insane levels. Is that normal?'
date: '2023-02-18T04:04:00.0030000+00:00'
draft: true
blogger_blog: 'Grief Sucks'
blogger_status: 'LIVE'
blogger_post_id: '5513584213271316182'
blogger_filename: '/2023/02/im-widower-my-sex-drive-has-increased.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Grief Sucks/feed.atom'
categories:
  - 'Written by Darrell Wolfe'
---

<br /><br /><br /><div>I'm a Widower. My Sex Drive has increased to insane levels. Is that normal?&nbsp;</div><div><br /></div><div>Yes, here's why and what to do about it...</div><div><br /></div><h4 style="text-align: left;">Sex Drive increases with Trauma and PTSD...</h4><div><br /></div><div>After a major tragedy like becoming a widow(er), major life changing accident, disasters, war scenarios.... you have to understand that you've actually experienced brain damage.&nbsp;</div><div><br /></div><div>For the Widower, there are real physical neural pathways that were built around your life with her. You built protein structures in the brain around that life. Akin to muscle memory.&nbsp;</div><div><br /></div><div>Those neural pathways are no longer able to function and you are now rebuilding entirely New Life inside your brain.&nbsp;</div><div><br /></div><div>As a result of this you're disoriented and in pain. One of the ways the body copes with pain is sex. Sex creates the feel-good hormones. So a large number of Widows/Widowers experience an increase in sex drive for the first few years. Not a minor increase. A near MANIC level increase.</div><div><br /></div><div>With good counseling, good safe non-romantic community, and good time spent building a new life... those pathways will eventually rebuild into a new life... And the intensity will subside.&nbsp;</div><div><br /></div><div>You're still a sexual being so you're always going to want sex but the near manic levels of desire are a result of this rewiring of the brain.</div><div><br /></div><div>Go for a walk. Phone a friend. Attend a Bible study, A.A. or Al-Anon meeting, find a local meet up find an activity you enjoy... Get into counseling. Pick up new hobbies. Work the connections in your brain like any other muscle. Build new pathways by having been experiences. Take new routes to work. Go to a different gas station. Do need things. Force the brain to learn that life has changed.</div><div><br /></div><div>It takes time.</div><div><br /></div><div>But healing is available.</div><div><br /></div><div style="text-align: center;">***</div>
<br />
Thank you for spending time with us today.<br />
<br />
We hope this helps you either process your own grief or understand those in your life going through it. Please check out our <a href="https://griefsucksawidowsguide.blogspot.com/p/resources.html" target="_blank">Resources</a> page for more articles and some links to the tools we've found helpful. For more about who we are, click&nbsp;<a href="https://griefsucksawidowsguide.blogspot.com/p/about-us.html" target="_blank">About Us</a>.<br />
<br />
<br />
Adrianne and Darrell, fellow Widows/Widowers