---
title: 'DRAFT - Landing Page Templates'
date: '2050-05-27T05:29:00.0000000+00:00'
draft: true
blogger_blog: 'Grief Sucks'
blogger_status: 'DRAFT'
blogger_post_id: '1887267121546019567'
blogger_filename: '/2050/05/draft-landing-page-templates.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Grief Sucks/feed.atom'
categories:
  - 'Written By Adrianne Butwell'
  - 'Edited by Darrell Wolfe'
---

<span style="white-space: pre;"> </span>1. Headline<br />
<span style="white-space: pre;"> </span>2. Opening<br />
<span style="white-space: pre;"> </span>3. Credentials<br />
<span style="white-space: pre;"> </span>4. Offer<br />
<span style="white-space: pre;"> </span>5. Bullets<br />
<span style="white-space: pre;"> </span>6. Testimonials<br />
<span style="white-space: pre;"> </span>7. Valid Justification<br />
<span style="white-space: pre;"> </span>8. Risk Reversal<br />
<span style="white-space: pre;"> </span>9. Call to Action<br />
<span style="white-space: pre;"> </span>10. Urgency<br />
<br />
<br />
Headline (Sizzle not Steak)<br />
Purpose of the headline is not to sell, it's to get them to read the first paragraph.<br />
<br />
<span style="white-space: pre;"> </span>• State the claim as a question "Who else wants to? Would you like to?"<br />
<br />
<span style="white-space: pre;"> </span>• Make the subject new Introducing, Announcing, Discover, Insider secrets to…<br />
<br />
<br />
Opening<br />
Sets the criteria: Who is the intended audience and what do they stand to gain by reading it.<br />
<br />
Set up the question<br />
Or<br />
Paint Picture "Imagine…" You might be thinking, how can I…<br />
<br />
Each Paragraph tells them to read the next<br />
<br />
Credentials<br />
Establish credibility<br />
Why should I listen to you?<br />
Why do this? Here's why.<br />
Here's why we're so good, here's out stats, here's our unique value added<br />
<br />
Offer<br />
Make an offer.<br />
How you'll solve their problem.<br />
Most flexible, fastest, easiest<br />
Anticipate objections and answer them. It makes them feel comfortable.<br />
<br />
Bullets<br />
Brief statements that identifies a single benefit offered by a product or service.<br />
Easy to use …. Reduces your stress.<br />
<br />
<br />
Testimonials<br />
What other people can say about your product and services is infinitely more powerful than what you say.<br />
<br />
"Other's like you…"<br />
<br />
Text better / Picture of it best, more specific (including who the person is, and their credentials) the better.<br />
<br />
<br />
Value Justification<br />
Highlight the value of the offer and make it easy by comparison. Show shocking negative stat about not doing this, compared to how easy we make it.<br />
Picture<br />
<br />
You could…. Give up you wouldn't have read up to this point if you wanted that. You're here because you want…<br />
<br />
Or you could… read a lot because you love reading complex and detailed….<br />
<br />
Or you could do what we say…<br />
<br />
<br />
Risk Reversal<br />
Money back guarantee (or whatever) if you don't (desired result) we're selling results.<br />
<br />
<br />
Call to Action<br />
<br />
Do This (call, click) big button, easy as possible. Options. Make it obvious (from the comfort of your own home).<br />
<br />
<br />
Urgency<br />
<br />
Why do I need to buy now? Procrastination kills sales. Count down. Timer. Reason it should be now. The price could go up, act now! If you procrastinate it could be… until you do it if you ever do. Act Now. Change you life. Don't pay more later.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />