---
title: 'You came and died, within the same month, June 2018.'
date: '2023-12-25T05:53:00.0000000+00:00'
draft: true
blogger_blog: 'Azarea Anne Wolfe - Journal'
blogger_status: 'LIVE'
blogger_post_id: '4929725620888711274'
blogger_filename: '/2023/12/you-came-and-died-within-same-month.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Azarea Anne Wolfe - Journal/feed.atom'
---

<p>&nbsp;In June 2018, your Mom told me you were here. I was so excited, we were looking forward to you for so long.&nbsp;</p><p>On June 25, 2018, you and your mom died, you were only seven weeks along.&nbsp;</p><p>Your due date was January 29, 2019; you would be five in a month.&nbsp;</p><p>You missed hell-year, 2020! But, you wouldn't have been old enough to know the difference, I suppose.&nbsp;</p><p>Without your mom, and you, smiles and laughter were fewer and farther between. Giggle (Preston) lost his laugh, and it's been more sarcastic laugh ever since. He's only now, just this past two months, started learning to live.&nbsp;</p><p>One time, at target, I stopped as I was passing baby clothes, that first year, and it hit me I'd never buy them for you. And I broke.&nbsp;</p><p>When I married Jen, she came with a daughter. Guess what her birthday is? December 29, a month before yours. So, that's kind of like a bittersweet blessing.&nbsp;</p><p>I miss you baby girl,&nbsp;</p><p>Your Daddy, Darrell</p>