---
title: 'Tuskegee Christian Center - Tuskegee, AL'
date: '2012-05-24T05:27:00.0030000+00:00'
draft: true
blogger_blog: 'Church Finder'
blogger_status: 'LIVE'
blogger_post_id: '5453323768347741263'
blogger_filename: '/2012/05/tuskegee-christian-center-tuskegee-al.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Church Finder/feed.atom'
categories:
  - 'Alabama'
---

Tuskegee Christian Center<br />
Pastors Bill and Veronica Winston<br />
<br />
<a href="http://www.tuskegeechristiancenter.org/welcome.htm">http://www.tuskegeechristiancenter.org/welcome.htm</a>
<br />
<br />
Tuskegee Christian Center<br />
<br />
711 West Martin Luther King Highway
Tuskegee, Alabama 36083<br />
<br />
Greetings in the Name of our Lord Jesus Christ!<br />
<br />
&nbsp;Veronica and I, along with our staff and Church family, would like to welcome you to Tuskegee Christian Center (“TCC”).

We are so glad that you’ve chosen to visit with us today. It is our desire that your visit is rich and rewarding.

We believe that the Bible is the undisputed authority for church order and government. As we learn biblical principles, and gain the knowledge of God’s Word, we expect that all who come will see their lives changed and their dreams become a reality. There are many wonderful things happening at TCC as God continues to lead us into the Promised Land, and the entire Body of Believers here at Tuskegee are excited about being used by God to touch the lives of multitudes around them.

If you are looking for a church home, we invite you to be a part of all the wonderful things that God is doing here. Most importantly, please seek God first and pray for His direction so that you can be sure of the place He has called you to. We are here to serve you and your family, and we pray that you will be blessed by this ministry.

Thank you for visiting with us. We look forward to seeing you again.<br />
<br />
&nbsp;In His Service,


William S. Winston
Pastor