---
title: 'Destiny Church - Indio, CA'
date: '2012-05-24T04:58:00.0040000+00:00'
draft: true
blogger_blog: 'Church Finder'
blogger_status: 'LIVE'
blogger_post_id: '4442254296097514920'
blogger_filename: '/2012/05/destiny-church-indio-ca.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Church Finder/feed.atom'
categories:
  - 'California'
---

Destiny Church - Indio, CA<br />
Pastor Obed and Lissette Martinez<br />
<br />
<a href="http://www.destinychurch.tv/welcome-destiny-church">http://www.destinychurch.tv/welcome-destiny-church</a>
<br />
<br />
82-625 Showcase Pkwy, Suite 100
Indio, CA 92203
<br />
<br />
In 2004, Pastor Obed &amp; Lissette and 7 families met in a living room in Rancho Mirage, CA and dreamed for something amazing, Destiny opened its doors with 274 people attendance in the Adams Elementry School Atrium. In just over six years, God has moved in amazing ways and has used Destiny Church to change thousands of lives in the Coachella Valley. Destiny Church was recently recognized as one of the fastest growing Churches in America. Through God's favor and a unremitting pursuit of a passionate mission, Destiny Church has experienced over 5,000 professions of faith and over 1,700 baptisms since our launch. From humble and sacrificial beginnings, God has placed his hand on Destiny Church and we truly believe the best is yet to come.<br />
<br />
<br />