---
title: 'Living Word Christian Center - Forest Park, IL'
date: '2012-05-24T05:25:00.0000000+00:00'
draft: true
blogger_blog: 'Church Finder'
blogger_status: 'LIVE'
blogger_post_id: '7110426855872782652'
blogger_filename: '/2012/05/living-word-christian-center-forest.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Church Finder/feed.atom'
categories:
  - 'Illinois'
---

Living Word Christian Center<br />
Pastor Bill and Veronica Winston<br />
<br />
<a href="http://www.livingwd.org/welcome/">http://www.livingwd.org/welcome/</a>
<br />
<br />
7600 West Roosevelt Road 
Forest Park, IL 60130 
USA<br />
<br />
Dear Friends:<br />
<br />
Living Word Christian Center is a Word of Faith, non-denominational, full gospel church. Our mission is reaching and harvesting lost souls for Christ and teaching the Body of Christ how to effectively apply God's principles to have victory in every area of life. Living Word is a place where people can come to learn to use the Word of God as the Covenant of God, thus building a relationship with God, and not just being religious.

God is raising up churches that are equipped and committed to managing the great end-time harvest of souls that are coming into the Kingdom of God. As Veronica and I have stepped out in faith to fulfill the call God has placed on our lives, He has blessed this ministry tremendously. We have grown from a storefront church with a handful of members on the west side of Chicago to a fellowship of well over 20,000 people. And this is just the beginning.

The Lord has given us a vision for building His Kingdom which has resulted in the manifestations of the: Living Word Bible Training Center, Living Word World Missions Center, Faith Ministries Alliance, Living Word Christian Academy, The Joseph Center©, Joseph Business School, David Samuel Clothing Store, Royal Christian Bookstores and Cafes, Forest Park Plaza, Covenant Bancshares, Inc., and in Tuskegee Alabama, Golden Eagle Aviation, Washington Plaza and Tuskegee Christian Center. As you explore our website, you will see some of those ministries that make up Living Word Christian Center and the impact that they have had on individual's lives. My prayer is that your heart will be encouraged and your faith ignited by these testimonies of God's goodness. Our desire is that you will want to go after everything God has promised for you and everyone who believes. God is no respecter of persons. What He has done here at Living Word is His desire for the Church globally. And God is able to do "exceedingly, abundantly above all that we ask or think according to the power [faith] that worketh in us" (Ephesians 3:20).

Thank you for spending time with us and allowing us to share with you the goodness of God and what He has done in our lives and wants to do in yours. God Bless you. We look forward to seeing you at Living Word Christian Center.<br />
<br />
&nbsp;In His Service,

William S. Winston
Pastor<br />
<br />
<br />