---
title: 'Why should I go to Church?'
date: '2012-05-24T06:36:00.0000000+00:00'
draft: true
blogger_blog: 'Church Finder'
blogger_status: 'LIVE'
blogger_post_id: '8203043353232218813'
blogger_filename: '/2012/05/why-should-i-go-to-church.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Church Finder/feed.atom'
categories:
  - 'Articles'
---

<br />
When was the last time you got up, got dressed and went to the store, but left your right toe at home? How about your left foot?<br />
<blockquote class="tr_bq">
<a href="http://www.biblestudytools.com/nkjv/hebrews/passage.aspx?q=hebrews+10:23-25"><i>Hebrews 10:23-2523&nbsp;</i></a><br />
<i>Let us hold fast the confession of our hope without wavering, for He who promised is faithful. 24 And let us consider one another in order to stir up love and good works, 25&nbsp;<b>not forsaking the assembling of ourselves together,</b>&nbsp;as is the manner of some, but exhorting one another, and so much the more as you see the Day approaching.</i></blockquote>
<blockquote class="tr_bq">
<i><a href="http://www.biblestudytools.com/nkjv/acts/2.html">Acts 2</a><br />1 When the Day of Pentecost had fully come,&nbsp;<b>they were all with one accord in one place</b>. 2 And suddenly there came a sound from heaven, as of a rushing mighty wind, and it filled the whole house where they were sitting...41 Then those who gladly received his word were baptized; and that day about three thousand souls were added to them. 42 And they continued steadfastly in the apostles' doctrine and fellowship, in the breaking of bread, and in prayers. 43 Then fear came upon every soul, and many wonders and signs were done through the apostles. 44 Now all who believed were together, and had all things in common, 45 and sold their possessions and goods, and divided them among all, as anyone had need. 46&nbsp;<b>So continuing daily with one accord in the temple</b>, and breaking bread from house to house, they ate their food with gladness and simplicity of heart, 47 praising God and having favor with all the people. And the Lord added to the church daily those who were being saved.</i></blockquote>
<blockquote class="tr_bq">
<i><a href="http://www.biblestudytools.com/nkjv/1-corinthians/12.html">1 Corinthians 12</a><br />18<b>&nbsp;But now God has set the members, each one of them, in the body just as He pleased.&nbsp;</b>19&nbsp;<b>And if they were all one member, where would the body be?</b>&nbsp;20 But now indeed there are many members, yet one body. 21 And the eye cannot say to the hand, "I have no need of you"; nor again the head to the feet, "I have no need of you." 22 No, much rather, those members of the body which seem to be weaker are necessary. 23 And those members of the body which we think to be less honorable, on these we bestow greater honor; and our unpresentable parts have greater modesty, 24 but our presentable parts have no need.<b>&nbsp;But God composed the body, having given greater honor to that part which lacks it, 25 that there should be no schism in the body, but that the members should have the same care for one another.</b>&nbsp;26 And if one member suffers, all the members suffer with it; or if one member is honored, all the members rejoice with it. 27 Now you are the body of Christ, and members individually.</i></blockquote>
<br />
There is something about a body. Bodies only function when all parts function. I can't tell you how many times someone has figured out how dedicated I am to God and Church (which doesn't take long with me) and they reply with something along these lines:<br />
<blockquote class="tr_bq">
<i><b>"I don't believe you need to go to Church. I can worship God from my home just me and God..."</b></i></blockquote>
My Reply:<br />
<blockquote class="tr_bq">
<i><b>"Yes you can... if Church was all about you, you could do it from home...But it's not!"</b></i></blockquote>
Bodies don't function perfectly without all the parts in perfect order. Church isn't about you. If church was about you getting fed, then stay at home and watch it on the internet. But church isn't about you. Church is about you bringing your faith into a service, bringing a corporate anointing into the situation, so that when someone walks in with a need it is taken care of.<br />
<br />
You are called to join a Church. Your Pastor is called to watch over you, counsel you, equip you for your calling and destiny, and then turn you into a leader that can impact others. Your ultimate calling in joining a church is to serve.<br />
<br />
Your highest calling cannot be&nbsp;fulfilled&nbsp;until you are serving others. Unless you live in a situation that makes it impossible for you to attend a church, I guarantee you that you are called to a church and a pastor. You may even be called to move 1300 miles to a new state, like I was. You may be called to move to a new country, like another friend of mine was. But you have an assignment in a church, and you will not&nbsp;fulfill&nbsp;your God given&nbsp;destiny&nbsp;without connecting where you are supposed to be.<br />
<br />
Again, unless it's impossible to attend given a special circumstance, deliberately avoiding going to church is an act of selfishness. However, you need the right church. Not just any church will do. Even a great church, may not be THE church you are called to. Pray about where YOU are supposed to be. Find your strategic position of opportunity and influence.&nbsp;Fulfill&nbsp;your destiny and reach your destination.<br />
<br />
Darrell G. Wolfe