---
title: 'About Us | Sobre Nosotros'
date: '2019-06-23T19:59:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'El Amor de Calvario'
blogger_status: 'LIVE'
blogger_page_id: '227750595991238690'
blogger_filename: '/p/about-us.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/El Amor de Calvario/feed.atom'
---

<h3>
Information | Informacion</h3>
<h3>
<div face="&quot;" size="3" style="font-family: Georgia, serif; font-size: 16px;">
<span style="font-weight: normal;">Services:</span></div>
<div face="&quot;" size="3" style="font-family: Georgia, serif; font-size: 16px;">
<span style="font-weight: normal;">10:30 am PST</span></div>
<div style="font-family: georgia, serif; font-size: 16px;">
<span style="font-weight: normal;"><br /></span></div>
<div style="font-family: georgia, serif; font-size: 16px;">
<span style="font-weight: normal;">Address:</span></div>
<div style="font-family: georgia, serif; font-size: 16px;">
<span style="font-weight: normal;">22421 E Euclid Ave</span></div>
<div style="font-family: georgia, serif; font-size: 16px;">
<span style="font-weight: normal;">Otis Orchards, WA 99027</span></div>
<div style="font-family: georgia, serif; font-size: 16px;">
<span style="font-weight: normal;"><br /></span>
<div>
<span style="font-weight: normal;">Mailing Address:</span></div>
<div>
<span style="font-weight: normal;">PO Box 877</span></div>
<div>
<span style="font-weight: normal;">Otis Orchards, WA 99027</span></div>
<div>
<span style="font-weight: normal;"><br /></span></div>
</div>
<div style="font-family: georgia, serif; font-size: 16px;">
<span style="font-weight: normal;">Phone:</span></div>
<div style="font-family: georgia, serif; font-size: 16px;">
<span style="font-weight: normal;">208-771-3952</span></div>
<div style="font-family: georgia, serif; font-size: 16px;">
<span style="font-weight: normal;"><br /></span></div>
<div style="font-family: georgia, serif; font-size: 16px;">
<span style="font-weight: normal;">Email:</span></div>
<div style="font-family: Georgia, serif; font-size: 16px;">
<span style="font-family: &quot;;"><a href="mailto:elamordecalvario@protonmail.com" style="font-weight: normal;" target="_blank">elamordecalvario@protonmail.com</a></span><br />
<span style="font-weight: normal;"><br /></span></div>
<div style="font-family: Georgia, serif; font-size: 16px;">
<span style="font-weight: normal;"><br /></span></div>
<div style="font-family: georgia, serif; font-size: 16px;">
<span style="font-weight: normal;">Facebook</span></div>
<div style="font-family: georgia, serif; font-size: 16px;">
<a href="https://www.facebook.com/El-Amor-de-Calvario-347809975864785/" style="font-weight: normal;">El Amor de Calvario</a></div>
<br style="font-family: Georgia, serif; font-size: 16px;" />
<br style="font-family: Georgia, serif; font-size: 16px;" />
<iframe allowfullscreen="" frameborder="0" height="300" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13634.516064331126!2d-117.10825605650025!3d47.68505723896931!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5361de784f3aa5e5%3A0xa3446f9aa2ca9e6f!2s22421+E+Euclid+Ave%2C+Otis+Orchards%2C+WA+99027!5e0!3m2!1sen!2sus!4v1556085545983!5m2!1sen!2sus" style="border-style: initial; border-width: 0px; font-family: Georgia, serif; font-size: 16px;" width="400"></iframe><br />
<br />
</h3>
<h3>
Our Calling | N<span style="font-size: 18.72px;">uestro Llamamiento</span></h3>
<div>
<br /></div>
We exist to serve the community. Come early to have coffee and snacks while you get to know your brothers and sisters in Christ in a friendly atmosphere. Then stay for worship and a word delivered in both Spanish and English.<br />
<br />
Existimos para servir a la comunidad. Llegue temprano para tomar un café y bocadillos mientras conoce a sus hermanos y hermanas en Cristo en un ambiente agradable. Entonces quédate para adorar y una palabra entregada en español e inglés.<br />
<div>
<br /></div>
<br />
<h3>
Pastor's Story | <span style="font-size: 18.72px;">La Historia del Pastor</span></h3>
Pastor Ray &amp; Bertha Duran have served the Lord for over 40 years. Pastor Ray worked primarily within Calvary Chapels throughout California and the North Idaho/Spokane Washington region.<br />
<br />
El Amor de Calvario (Love of Calvary) is the fourth church planted by Pastor Ray who has always had a vision and heart for the Hispanic Community.<br />
<br />
For over 6 years, Pastor Ray prayed over the Eastern Washington area and in 2019 he felt called of the Lord to plant a Spanish/English church in Ottis Orchards, Washington.<br />
<br />
After getting a call from a local pastor that a church building was available for his congregation to meet, Pastor Ray was ecstatic to find that this was the very building he'd prayed over for 6-7 years before.<br />
<br />
<br />
El pastor Ray y Bertha Duran han servido al Señor por más de 40 años. El pastor Ray trabajó principalmente en las capillas de Calvary en California y en la región de North Idaho / Spokane Washington.<br />
<br />
El Amor de Calvario es la cuarta iglesia plantada por el pastor Ray, quien siempre ha tenido una visión y un corazón para la comunidad hispana.<br />
<br />
Durante más de 6 años, el pastor Ray oró por el área del este de Washington y en 2019 se sintió llamado por el Señor para plantar una iglesia en español / inglés en Ottis Orchards, Washington.<br />
<br />
Después de recibir una llamada de un pastor local de que un edificio de la iglesia estaba disponible para que su congregación se reuniera, el Pastor Ray estaba extasiado al descubrir que este era el edificio en el que había orado durante 6-7 años antes.<br />
<br />
<div>
<h3>
</h3>
</div>
