---
title: 'Our History DRAFT'
date: '2019-06-23T19:37:00.0020000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'El Amor de Calvario'
blogger_status: 'DRAFT'
blogger_page_id: '9015288672069734298'
blogger_filename: '/p/our-history-draft.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/El Amor de Calvario/feed.atom'
---

<h3>
Our History</h3>
<br />
Pastor Ray Duran has been in ministry for 40 years primarily within the Calvary Chapel movement. He has served on staff for or been associated with well-known leaders in the Body of Christ, such as Raul Ries, Jack Hibbs, Jon Courson, Greg Laurie. Ray is an unassuming man, humble, and down to earth. He goes where God sends him and does what God says to do, even if it doesn't seem logical or might not "work" from a worldly point of view.<br />
<br />
In one instance, he moved to a city and started a church just to see one young woman radically saved and that was enough for him. He moved on from that church after two years and left it in good hands.<br />
<br />
During a visit with his son, living in the North Idaho/Eastern Washington area, he passed an old man in tattered clothes sitting outside a restaurant. He'd just told his family to go to the car while he paid the bill then walked out on his own. The old man was still sitting on the bench. He had long white hair and a white beard, and he clung tightly to an old tattered bible.<br />
<br />
The old man waved him over, "This is my Bible".<br />
<br />
"That's good brother," Ray said.<br />
<br />
"You're going to start a church over there," he said and pointed to the area of Ottis Orchards. "In the valley."<br />
<br />
Ray put that away but pondered it in his heart. On the way back to California, he visited some old friends and they too gave him a word that he'd be moving soon.<br />
<br />
When he returned back to his home and went into his office, Jack Hibbs walked up to him and said: "You'll be leaving us soon."<br />
<br />
Eventually, Ray and his wife Bertha moved to North Idaho. They served faithfully at Candlelight Church and were eventually asked to start a Spanish Speaking congregation within the church. Spanish speakers often inquired about services, the only Spanish speaking congregation was in the local Catholic Mass services, only held twice a month. Ray is fluent in Spanish, but it's not his first language and he never felt qualified to preach in Spanish. Although he did many ministry trips to Spanish speaking nations, he always used an interpreter.<br />
<br />
"I have always had a love for Hispanic people," Ray said. "There are quite a few Latin people moving to the area and there are people looking for Spanish Bible studies."<br />
<br />
"I prayed about it a lot and finally said 'OK let's go ahead and do it,'" Duran said. "It's a challenge, but it's also a blessing and an honor to teach the Bible to Hispanic people."<br />
<br />
Ray, who was born in New Mexico, said many Latinos are turning to nondenominational churches like his as part of the charismatic renewal.<br />
<br />
The 2007 Pew study found that 15 percent of U.S. Hispanics identified as born-again or evangelical Protestant, 5 percent mainline Protestant and 3 percent other Christian, such as Mormon or Jehovah’s Witness.<br />
<br />
Ray said that when he was Catholic, he “never really had an experience with the Lord one-on-one.” He said many Latinos converting to charismatic or evangelical faiths are asking why this is. “Once they have a relationship like this with the Lord, there is no going back,” Ray&nbsp;said.<br />
<br />
Approximately 6-7 years ago, he felt led of the Lord to travel to an area in Western Washington called Ottis Orchards (mostly farms and small communities). He drove to all four corners of the area, North, South, East, and West, praying for the people in the houses, farms, and businesses.<br />
<br />
In 2013, he began to meet monthly with other pastors from the area, praying for God's will in the region. In 2014, he held a Night of Praise in the building that would eventually be their new home, though he didn't know it at the time. In 2015, he organized another Night of Praise in a different location with the pastor who would eventually lead him to his church's new home.<br />
<br />
In 2019, he was contacted by Pastor Gary and informed that the building was open and asked if he would consider planting his new church there. He opened the doors and his small start-up congregation began cleaning and making repairs and meeting on a weekly basis, among the first weekly Spanish speaking services in the region. He is still early in this project and he is serving faithfully. Instead of rushing or fretting to make things work, he simply walks humbly with his God and takes one day at a time. In lieu of a Worship Pastor, he plays songs through the computer on the overhead screen until God provides someone to come alongside.<br />
<br />
Ray lives by a simple Mantra: If they don't know (Jesus), I want them to know (Him). And that's what he's doing, one soul at a time.<br />
<div>
<br /></div>
References to articles written about this move of God recently:<br />
<br />
<a href="https://www.cdapress.com/archive/article-85ee1401-483f-5a1d-9a61-4a1b3ac58159.html">https://www.cdapress.com/archive/article-85ee1401-483f-5a1d-9a61-4a1b3ac58159.html</a><br />
<br />
<a href="http://www.spokesman.com/stories/2013/dec/25/new-area-church-services-oriented-toward-latinos/">http://www.spokesman.com/stories/2013/dec/25/new-area-church-services-oriented-toward-latinos/</a><br />
<br />
<br />
<br />