---
title: 'SIN, sins, and the Promises of God'
date: '2017-11-25T22:05:00.0010000+00:00'
draft: false
categories:
  - 'Studies'
  - 'study'
  - 'Armchair Theology'
---

Recently, I saw this statement (as a snippet of a much larger comment). I agreed with the comment as a whole, but this portion really bothered me for a few days.<br />
<br />
<blockquote class="tr_bq">
<i>If we spoke even one word, negatively or condemning about one person, without taking care of that by repenting and clearing that up, although God desires only blessing, favor and good on our behalf, He must rule on our guilt of sin.</i></blockquote>
<br />
My Response:<br />
<h4>
SIN vs sins</h4>
Individual sins are a result of our inherited SIN nature. Jesus died to take care of SIN, not individual sins. Of course, individual sins are covered in that death, but it was the root He was after. Once you are born again, you will NEVER be ruled guilty of any individual sins, whether you remember to repent of them(it) or not. They are covered under the blood (past, present, and future). They are not irrelevant, but more on that in a moment.<br />
<br />
<h4>
Repentance</h4>
Repentance has nothing to do with saying sorry or asking for forgiveness, repentance has to do with changing your WAY of thinking to align with His. Not just replacing your thoughts with His thoughts, rather, it's replacing your WAY of thinking, receiving information and processing information to become like His.<br />
<br />
<h4>
Confession/Profession</h4>
Confession has nothing to do with claiming what you want or with confessing your sins, at least not directly. Confession/Profession means to "say the same thing as".<br />
<br />
If God's talking to you about your sin, and you say the same thing he's saying, then this would be confession. But if God is talking to you about your Righteousness in Christ Jesus and you are talking about your sin, then you are NOT confessing. You are not saying the same thing as Him.<br />
<br />
Likewise, when it comes to the promises, unless God has said it, you can say it all day long and it's not confession, it's wishing.<br />
<br />
<h4>
Vague Promises vs Specific Promises</h4>
<h4>
Written = Vague</h4>
God's Written Word provides many promises. They are, on balance, general/vauge about most things. It says he will never leave us or forsake us, that we will live long in the land if we honor our father and mother, that God delights in the prosperity of his servants, that he has a future planned full of hope and prosperity, that if we confess with our mouths and believe in our hearts we are saved....<br />
<br />
On balance these are specific up to a point. Nothing in the written Word of God will promise you a specific outcome for a specific set of obedience. There are general principles, rock solid Truths, but not very many situation-specific/outcome-specific promises.<br />
<br />
<h4>
Heard = Specific</h4>
For these, you must go beyond the Written Word, beyond rote learning, repetition, study... you must HEAR the voice of God speaking into your heart/situation. This gets harder. For this, you must hear. To hear, you must be listening. A myriad of things can hinder your listening/hearing.<br />
<br />
You may be distracted by your own sins. Asking for forgiveness here could be a way to help clear your conscience and allow yourself to hear better. This does not mean that God needs you to repent in order to fulfill his promises or blessings, only that your dealing with this will help you clear your own conscience and help you hear. This mostly has to do with a need to renew your mind to His righteousness.<br />
<ul>
<li>You may be dragged away by your own desires (James 1:14). You don't WANT to hear.&nbsp;</li>
<li>You hear but don't like what you heard. You don't WANT to hear more.&nbsp;</li>
<li>You may not have learned how to listen/hear him. Training/Practice&nbsp;</li>
<li>You may have heard, but you're not sure how to know it's Him. Training/Coaching from others.&nbsp;</li>
<li>Many other reasons you may not hear and/or obey what you hear, thus not receive from God...&nbsp;</li>
</ul>
All of these have nothing to do with sins, directly. Sins can play a role in YOUR heart, not in God's response.<br />
<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<br />
<div class="MsoNormal">
</div>
<br />
<div class="MsoNormal" style="-webkit-text-stroke-width: 0px; color: black; font-family: Arial; font-size: medium; font-style: normal; font-variant-caps: normal; font-variant-ligatures: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-decoration-color: initial; text-decoration-style: initial; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px;">
<div style="margin: 0px;">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span><span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
</div>
