---
title: 'Transformation Ministry'
date: '2017-09-26T07:02:00.0010000+00:00'
draft: false
categories:
  - 'Insight'
  - 'Armchair Theology'
---

Today I had the honor of meeting a group called, Heart Writers. It's a group for anyone who feels they have a book to write.&nbsp;There were poets, short story writers, fiction writers, memoir writers, and others.<br />
<br />
During our talks, the leader presented the idea that all of our writing, even the seemingly random blog posts, could be a form of ministry. In my mind, writing and ministry mean theological works such as explaining the Bible. I've done plenty of that; however, that got me thinking about Ted Dekker and his teaching on writing fiction.<br />
<div>
<br /></div>
<div>
He said that one major key is for your character to undergo a major internal transformation.<br />
<br />
Ted Dekker said (<a href="http://www.darrellwolfe.com/2016/09/the-creative-way-creating-fiction-that.html?m=1" target="_blank">see more here</a>):</div>
<div>
<blockquote class="tr_bq">
<i>What is story? Story is a series of events involving worthy characters who change (are transformed) as a result of those events.</i></blockquote>
This was a great reminder that ministry means a lot of things. As Ted's character changes, I'm going through that transformation with him/her. I'm being transformed a little in the process myself. That is Ted's Ministry to me, the reader. That is my ministry to my readers, few and far between though they may be.<br />
<br />
Long after the average reader had forgotten all ten steps, and most of the habits, he/she will remember Frodo almost quitting and Sam coming to his aide, to push him to move on. They will feel with Captain America as he refuses to fight his best friend. They will laugh and cry with the revelation that God can be a black woman (The Shack).<br />
<br />
Story is what God used to reach us on the Bible. There are facts, lists, but the vast majority of God's Word to Mankind was told through story. Jesus said, "greater things that I do". He was a master storyteller above all else he did. Audiences may have gotten healed when they came to him, but they stayed long enough to get healed because they were captivated by his stories.</div>
<div>
<br /></div>
<div>
Story is the most important ministry I can be involved in, for my skill set.<br />
<br />
I NEED to tell a story... Maybe more than one.<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<br />
<div class="MsoNormal">
</div>
<br />
<div class="MsoNormal" style="-webkit-text-stroke-width: 0px; color: black; font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-caps: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-decoration-color: initial; text-decoration-style: initial; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px;">
<div style="margin: 0px;">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span><span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
</div>
</div>
