---
title: 'Got LIFE?'
date: '2018-03-31T17:36:00.0020000+00:00'
draft: false
categories:
  - 'Armchair Theology'
---

<blockquote class="tr_bq">
<i>And the Lord God formed man of the dust of the ground, and breathed into his nostrils the breath of life; and man became a living being. <a href="https://www.biblestudytools.com/nkjv/genesis/2.html" target="_blank">Genesis 2:7</a></i></blockquote>
<br />
<b>Are rocks dead?&nbsp;</b><br />
<br />
Consider this for a moment. A rock isn't dead, it's simply without life. It is not alive. In order for something to be dead (biologically) it must first have experienced or had the capacity to experience life. Death is not the absence of life, it is the removal of it.<br />
<br />
Spiritually, Adam did nothing to earn life. God breathed LIFE into him. He didn't go to church, do twenty good things, or earn it in any way. He was without life, and LIFE came to him without his works involved.<br />
<br />
How often do people say: "Well, I'm a good person..."<br />
<br />
How does your being a good person help you get LIFE?<br />
<br />
<b>You see, Heaven, Hell, and Spiritual things are NOT a matter of Good vs Bad.&nbsp;</b><br />
<blockquote class="tr_bq">
<i>And out of the ground the Lord God made every tree grow that is pleasant to the sight and good for food. The tree of life was also in the midst of the garden, and the tree of the knowledge of good and evil. *** Then the Lord God took the man and put him in the garden of Eden to tend and keep it. 16 And the Lord God commanded the man, saying, "Of every tree of the garden you may freely eat; 17 but of the tree of the knowledge of good and evil you shall not eat, for in the day that you eat of it you shall surely die."&nbsp;</i><i><a href="https://www.biblestudytools.com/nkjv/genesis/2.html" target="_blank">Genesis 2 (9, 15-17</a></i></blockquote>
The Tree of Knowledge (Good/Bad) was a tree that brought death. Being a Bad Person and being a Good Person are&nbsp;both totally irrelevant to the topic of Spiritual LIFE.<br />
<br />
<b>LIFE does not come from the tree of Knowledge of Doing.</b><br />
<br />
The Knowledge of Doing (Good/Bad) is what killed us in the Garden, and it's still bringing death to us daily today. Science and Religion are actually the same, sources of death.<br />
<b><br /></b>
<b>LIFE comes from its own tree. It's freely given and must be freely received.&nbsp;</b><br />
<br />
Before Jesus ever came to earth to walk among us, he was there in the original garden. He was forming Adam. He was giving LIFE freely without merit or deeds or doings or earnings.<br />
<br />
Religion tells you to try harder the Knowledge of Good. The Holy Spirit tells you to relax and receive the free gift of LIFE, the restoration of which is paid for by the freely given blood of Jesus.<br />
<br />
Selah...<br />
<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span> <span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
<div class="MsoNormal">
<br /></div>
