---
title: 'A Conduit of Blessing, NOT a Reservoir'
date: '2018-03-03T16:15:00.0000000+00:00'
draft: false
categories:
  - 'Studies'
---

<div dir="ltr">
I've read the book of Job more than any other book in the Bible. I identify with him in so many ways (real or imagined).</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
As I re-read the closing chapters this morning, I found a theme running through beginning to end, a silver thread hidden among the tapestry of his life.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Self<br />
<br />
There are four points through which this thread pulls most vividly:<br />
<br />
<ol>
<li>Sacrificing out of fear for his kids, at the start (inward focus, fear of loss).</li>
<li>Self-Admiration (I'm so innocent) throughout the book.</li>
<li>The counter offered by Elihu &gt; Then God (don't ascribe right-ness to yourself, but to God).</li>
<li>Sacrifice on behalf of his friends (outward focus, gain on half of others).</li>
</ol>
</div>
<div dir="ltr">
<br />
<h4>
<b>Sacrificing out of fear for his kids, at the start (inward focus, fear of loss).</b></h4>
</div>
<div dir="ltr">
<br />
At the start of his story, we find a man who is self-focused. You might argue that he was focused on his kids; however, he wasn't. He was focused on not losing his kids, which is a self-focus motive. He would make sacrifices from a spirit of fear (what if) rather than a spirit of faith (gratefulness of God).</div>
<div dir="ltr">
<br />
<h4>
<b>Self-Admiration (I'm so innocent) throughout the book.</b></h4>
<br /></div>
<div dir="ltr">
Throughout the book, Job focused on his own predicament. He focused on his own righteousness, or rightness, or right-standing. He said there was absolutely nothing in his life that wasn't perfect and God must be at fault. He started blaming God for his situation and pain.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Haven't we all, at one point or another blamed God for human suffering? But the start of the book shows it was Satan (who the Bible calls the god of this present <a href="http://biblehub.com/2_corinthians/4-4.htm" target="_blank">world/age</a>) who was the orchestrator of pain.&nbsp;</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
The God of the universe handed control of earth to Adam. Adam never lost that control, but continually hands that control over to the spirit of influence he bows to at any given moment. Throughout the world, Satan, through men/women, influences the control Adam received. Men, Sin, and a sin-broken earth/environment are the cause of all human suffering. Not God.</div>
<div dir="ltr">
<br />
<h4>
<b>The counter offered by Elihu &gt; Then God (don't ascribe right-ness to yourself, but to God).</b></h4>
<br /></div>
<div dir="ltr">
At the end of the book, God refuses to address the reasons' for Job's suffering. The final friend, the previously silent fourth friend, points out that God is to be praised and magnified. God-Focus, not Man-Focus, is the cure.&nbsp;</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Elihu shows us that by turning our attention from the problem entirely (including its causes and cures) and bringing our focus to bear instead on God's role, ability, and magnitude, we can then tap into that power (instead of little g's power). By developing a relationship with, and covenant&nbsp;with, God (big G) we can over-ride the things of this world and find a greater peace, prosperity, and wholeness.&nbsp;</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
This isn't to say we'd never again experience affliction, but that we'd be in covenant with the One who can over-ride it.<br />
<br />
<br />
<h4>
<b>Sacrifice on behalf of his friends (outward focus, gain on half of others)</b></h4>
<div>
<br /></div>
Finally, we see the second sacrifice. Whereas the first sacrifice is made out of a fear of loss, self-focus; the second sacrifice is made on behalf of a request from God for his friends, outward-focus.<br />
<br />
God got Job's attention to the needs of others instead of his own needs. As a direct result of that second outward focused event, Job's own situation was handled.<br />
<br />
There were times, in years past, where God directed me to pray for others' needs and my own were miraculously taken care of. It's possible there is a principle at work here that transcends the specific events of Job's life.<br />
<br />
Perhaps, when we turn out attention from our own wants, needs, desires, to the needs of others; our life's mission and purpose can be more clearly expressed.<br />
<br />
Perhaps, we cannot be blessed in and of ourselves but we can be a conduit of The Blessing that flows through our lives to others. We receive "blessings" in the process but it's only when the hose of our life is "turned on" to pour out on others.<br />
<br />
<blockquote class="tr_bq">
<b>We cannot be a reservoir of God's blessing, but we can be a conduit. Darrell Wolfe</b></blockquote>
<br />
Selah.<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span><span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
</div>
