---
title: 'Suicide: Can suicide send you to hell?'
date: '2018-01-15T07:08:00.0000000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5587261056865408877'
blogger_filename: '/2018/01/suicide-can-suicide-send-you-to-hell.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'bible'
  - 'suicide'
  - 'depression'
  - 'Armchair Theology'
---

The Blessed Life posted this video <a href="https://www.facebook.com/blessedlifeofficial/videos/1917223088606643/?comment_id=1917420161920269&amp;reply_comment_id=1919502158378736&amp;notif_id=1515990449110219&amp;notif_t=feed_comment_reply" target="_blank">(here) "What Happens When You Commit Suicide?"</a>. This sparked a long on-going debate with strong feelings on either side. I love Ravi. He's one of the best. I'm kind of surprised he couldn't answer this one simply.<br />
<br />
Here's the video, my answer below.<br />
<br />
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
<iframe allowfullscreen="true" allowtransparency="true" frameborder="0" height="543" scrolling="no" src="https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Fblessedlifeofficial%2Fvideos%2F1917223088606643%2F&amp;show_text=1&amp;width=476" style="border: none; overflow: hidden;" width="476"></iframe>

</div>
<div style="text-align: center;">
<br /></div>
<br />
<i><b>DISCLOSURE</b>: Before reading my answer, please be aware of this. Suicide is a serious thing, with impacts not just for you but for your family, co-workers, and many others. If you are contemplating this, please seek help.&nbsp;</i><br />
<i><br /></i>
<i>There are many great resources, watch videos by Dr.&nbsp;<a href="http://bobhamp.com/media/" target="_blank">BobHamp,</a>&nbsp;seek a pastor our counselor, join a group. Suicide is a sign of depression and isolation. You need, above all else, <b>connection </b>with other believers. Not just to be physically around them, but an actual heart connection. Find someone, anyone, that you can talk to who will love on you with the Grace of God. Someone who can show you that there's NOTHING in your heart that will prevent God and that person from loving on you.&nbsp;</i><br />
<i><br /></i>
<i>There's a second group, who don't care about the love, they just want to avoid the pain. The pain is real. Suicide <b>is NOT&nbsp;</b>the answer. Let God heal that pain. Most of that pain is caused by a lie the Enemy is trying to sell you. <b>Ask God: "What lie am I believing right now? What event caused me to believe that lie? And what Truth can you tell me about that?"&nbsp;</b></i><br />
<i><br /></i>
<i>The answers I give are to address a very specific, targeted, theological question. They are not indented to justify your decision to take your life. Seek help, it's out there. If you don't know where to start, contact GatewayChurch in Southlake Texas. They can point you to some resources.&nbsp;</i><br />
<i><br /></i>
<i>Finally, if you are actually serious, like right now serious. Call 911 and tell them you are contemplating suicide and need to be taken in. They will help you prevent the action for now until you can get help.&nbsp;</i><br />
<i><br /></i>
<i>Check out my Resources page for Overcoming <a href="http://www.darrellwolfe.com/p/personal-and-spiritual-growth.html" target="_blank">Depression</a>.&nbsp;</i><br />
<i><br /></i>
<i>You can also contact: the&nbsp;<a href="http://www.suicidepreventionlifeline.org/">National Suicide Prevention Lifeline</a>: Call 1-800-273-8255</i><br />
<br />
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
<b>************</b></div>
<b>Now for the answer:</b><br />
<br />
<h4>
<b>The question&nbsp;being asked is: Can suicide send you to hell?</b></h4>
<br />
I don't believe this is a complicated question at all. It's nothing to debate or get excited about.<br />
<b><br /></b>
<h4>
<b>My Short answer: No. Suicide will not send you to hell.&nbsp;</b></h4>
<br />
This very question is based on a simple, common, works-based <b><i>theological error.</i></b><br />
<br />
It can be worded in many different ways, here are some of the basics I saw in response. Each of the following commits the exact same theological error. Because they are in error, I'll leave their name off from what they said, and simply address the error itself.<br />
<br />
<h4>
<b>All of the following are responses given using the same theological ERROR:</b></h4>
<br />
<ul>
<li><i><b>... if you commit suicide you can't ask for forgiveness afterward...there is no second chance to repent. Suicide is a done deal and you're going to Hell !!</b></i></li>
</ul>
<ul>
<li><i>So if the Good Lord chooses to use you to Glorify himself in some manner, yet, you take your own life, in a selfish act of the flesh; you have glorified yourself and not the Lord. Tell to me, why Jesus would grant life to someone who does not want it.</i></li>
</ul>
<ul>
<li><i>You can't accept God and then not live by his word or have a relationship with him. Continuing to live in sin after having accepted God is not truly "accepting" Him. A relationship is a two-way street. You must follow God's rules and HE will give you everlasting life. I truly hope this is a learning opportunity for you as per your beliefs you just stated you possibly have been sinning after accepting Jesus. This is no worries though just ask God for forgiveness and I'm sure He will forgive you based on you not really understanding what He meant when He said "accept me"</i></li>
</ul>
<ul>
<li><i>...suicide is sin. All sin is based upon the flesh doing its will. I cannot make the choice to take my life which was given to me by God.</i></li>
</ul>
<ul>
<li><i>No dude. Suicide is cowardly. Suicide is not wearing the full armor of God. Suicide is lacking faith in God, in that He wants us to live a life of abundance. Jesus came to give life, not so you or I or anyone else can take it away at leisure. Remember, His ways are not our ways.&nbsp;</i></li>
</ul>
<ul>
<li><i>Everyone wants to have their cake and eat it too. However, the cake was created to pour out on behalf of our brethren.</i></li>
</ul>
<ul>
<li><i>God gives life and takes. Murder is a sin. To take your own life is murder. Blessed are they that do his commandments, that they may have right to the tree of life, and may enter in through the gates into the city. For without are dogs, and sorcerers, and whoremongers, and murderers, and idolaters, and whosoever loveth and maketh a lie.</i></li>
</ul>
<ul>
<li><i>Saved or not saved, if you commit suicide you do not go to heaven. Read Ex. 20:13. Thou Shalt not commit murder. That is exactly what you are doing. Also if you can follow through with suicide than you are lost you aren't saved, those are all lies of the devil.</i></li>
</ul>
<br />
<h4>
<b><br /></b></h4>
<h4>
<b><br /></b><b>Correcting the error:&nbsp;"Works" vs "Grace"</b></h4>
<br />
These are all reflections of an internal theological error, rooted into the church from day one. The early Jewish Christians made this error with their talk of "circumcision". Then it found its way into the church through other avenues, and it still lives with us today.<br />
<br />
<b>ALL (100%) </b>of the above comments have some element of a works-based mentality behind them.<br />
<br />
They all say, in essence:<br />
<br />
<ul>
<li><i><b>I'm saved through Jesus if I also....&nbsp;</b></i></li>
</ul>
<br />
The most common presentation is to hear the idea that "<b>if I commit a sin and can't repent of it before I die, I'm going to hell</b>". Well, that's religious nonsense and garbage. I can guarantee that you've committed sins at some point in your life that you don't remember and therefore cannot "repent" of.<br />
<h4>
<br /><b>"Asking for forgiveness" after each and every sin is irrelevant to salvation.&nbsp;</b></h4>
<br />
I know, that sounds like heresy, keep reading and you'll get it.<br />
<br />
<h4>
<b>SIN vs sins</b></h4>
<br />
There is a common misunderstanding between the condition called SIN and the individual acts called sins. We are in a state of being called SIN. We are born into this earth separated from God. Impure. Imperfect.<br />
<br />
Jesus came, died, was buried and resurrected, raised and seated at the right hand of God the Father, and sent the Holy Spirit all for one reason. He is our replacement.<br />
<br />
We either stand before God on the basis of our record or we stand before God on the basis of Jesus' record. He is the lamb, we cannot be. We will never be without blemish, and it's foolish for us to try to earn anything ever.<br />
<br />
Some twisted version of works-based theology always tries to creep in and this point and tell us that Jesus died for our past sins, but we still have to keep repenting over-and-over-and-over to keep staying clean.<br />
<br />
Hogwash.<br />
<br />
<br />
<b>Jesus died as our replacement. You will stand on His record or yours. Plain. Simple. Period.</b><br />
<br />
<br />
<h4>
<b>What about all the scriptures about repenting and asking for forgiveness?</b></h4>
<br />
These have nothing so much to do with Salvation and more to do with our quality of life on this earth, and rewards beyond. No time to go deeper, that's another post for another day.<br />
<br />
"Repentance" has little to do with actions anyway.<br />
<br />
Repentance isn't about changing your actions or thoughts.<br />
<br />
Repentance has to do with changing your WAY of thinking, your thought process. And this is not a one-time event, or repeated event, or an event at all. This is a way of life. We are to constantly be renewing our mind to God's way of thinking. And by getting his WAY of thinking, we eventually have new thoughts as a result, and then new actions. This is about how we live, and nothing to do with our salvation.<br />
<b><br /></b>
<h4>
<b>So everyone goes to heaven without needing to accept Jesus?</b></h4>
No. Again, you have a choice. You can stand on your record or His.<br />
<br />
Whoever believes in him is not condemned, but whoever does not believe stands condemned already because they have not believed in the name of God’s one and only Son. <a href="https://www.biblegateway.com/passage/?search=John+3&amp;version=NIV" target="_blank">John 3</a><br />
<br />
It's that simple. You either believe and accept that Jesus is your replacement or you don't.<br />
<br />
<br />
<br />
<h4>
<b>What now?</b></h4>
As I said in my disclosure, if you are struggling with this yourself, seek help.<br />
<br />
If any of this is new information to you, you've been lied to by religion and religious doctrines of men. You need Freedom. There are many good Bible-teaching churches that will show you the Grace of Jesus.<br />
<br />
I'd also recommend you check out Bob Hamp, Christian Pastor and Counselor (MFT). He has some mind-blowing teachings on Freedom.<br />
<br />
His website: <a href="http://bobhamp.com/media/" target="_blank">BobHamp.com</a><br />
Facebook: <a href="https://www.facebook.com/pg/ThinkDifferentlyCounseling/videos/?ref=page_internal" target="_blank">Think Differently: Counseling, Consulting, Connecting</a><br />
Podcast: <a href="https://castbox.fm/va/365612" target="_blank">BobHamp</a>&nbsp;on CastBox, including a teaching on <a href="https://castbox.fm/vb/23739127" target="_blank">Depression</a>.<br />
<br />
<br />
Also, one person in the thread gave a link to <a href="https://www.desiringgod.org/interviews/suicide-and-salvation" target="_blank">John Piper's answer</a>. It's a decent answer and worth checking out.<br />
<br />
<br />
Email <a href="mailto:Me@DarrellWolfe.com" target="_blank">Me@DarrellWolfe.com</a> if you'd like to chat more about this.<br />
<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span> <span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
<div class="MsoNormal">
<br /></div>
