---
title: 'Flavia Antoinette Wolfe: Here''s what happened...'
date: '2018-06-25T22:28:00.0030000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4316593898530566222'
blogger_filename: '/2018/06/flavia-antoinette-wolfe-heres-what.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Flavia'
---

<h3>
Flavia Antoinette Wolfe died this morning (06/25/2018) at approximately 2:45 am PST.</h3>
For update see<br />
http://www.darrellwolfe.com/2018/06/flavia-antoinette-wolfe-and-baby-wolfe.html?m=1<br />
<br />
The following is meant to answer some basic questions that everyone's asking me. I'd rather send a link then type or talk it out over and over. I'll add more memories and things later as I recall or rediscover. It's a little cathartic for me, to be able to get it out of my head anyway.<br />
<br />
The background leading up to this morning:<br />
<br />
<br />
<ul>
<li>On May 24, 2018, I got a text with a picture of a positive pregnancy test followed by "So... Boy, girl, twins?"</li>
</ul>
<ul>
<li>We made appointments, got excited. Flavia was overweight but in generally good health otherwise, so-say-the-tests. However, the pregnancy hit her hard and fast. She said within a month of that test she was feeling like she did when she was six-months pregnant.</li>
</ul>
<ul>
<li>06/06/2018: She took the boys to get Fro-Yo, it was nice outside, they decided to walk around the block. Everything was fine, except she got tired fast.</li>
</ul>
<ul>
<li>06/09/2018: She started complaining of cramping and&nbsp;little nausea. Common&nbsp;pregnancy issues.</li>
</ul>
<ul>
<li>06/10/2018: She said her left leg was started to hurt. It was the day after work, she guessed she hurt it up and down the ladders stalking, or strained it in some way.</li>
</ul>
<ul>
<li>06/11/2018: We had our first OBGYN appointment. They took pictures, the baby was the size of the blueberry. The leg was hurting worse. The doctor said if it continued that she wanted it checked out for blood clots.</li>
</ul>
<ul>
<li>06/12/2018: Her leg was still very sore, and getting worse. We called the OBGYN, she had Flavia scheduled for an ultra-sound on her leg. After reading, reading, re-reading, all of the symptoms common to clots, cramps, and strains, Flavia was becoming convinced that she had pulled a muscle but went anyway just to be safe.</li>
</ul>
<ul>
<li>06/13/2018: The ultrasound was performed, they said there were not able to find any clots. Flavia was worried about returning to work and making sure her Leave of Absence (LOA) was covered. I told her not to force is, returning to work too early could cause complications. She reluctantly agreed to take more time off. She went to the Urgent Care that night. They did whatever they do, said it was a strain and told her to use Aspercream.&nbsp;</li>
</ul>
<ul>
<li>06/13-06/24: This was a whole lot more of the same. No new appointments, but the leg was feeling better, then not, then it was, then her back was hurting from sleeping in positions that propped her leg. She was getting frustrated.</li>
</ul>
<ul>
<li>06/24/2018: We talked that night about our dreams for the future, our plans, making sure we focused on our areas of strength and not forcing things that don't fit us. Great talk. I went to be at her encouragement and she&nbsp;slept on the couch again to prop her leg.</li>
</ul>
<ul>
<li>06/24/2018--06/25/2019: At approximately 1:00-1:30 am PST, Flavia came into the bedroom and called my name. She was frantic. She said her leg didn't hurt anymore but she was dizzy and to take her to the hospital. She collapsed in the living room. I called 911.&nbsp;</li>
</ul>
<ul>
<li>The paramedics performed chest compressions for about 20 minutes? They took her to the hospital ER. I gathered the boys, expecting it to be a while and then follow her to the room when they got her back up and spend a long night there.&nbsp;</li>
</ul>
<ul>
<li>The boys stayed in the waiting room with a nurse, they talked about Pokemon.&nbsp;</li>
</ul>
<ul>
<li>I stayed in the corner of the ER, watching, praying, waiting. To my knowledge, they tried everything they could, for almost two hours. At no point during these interventions did she make progress or respond positively, as far as I could tell.&nbsp;</li>
</ul>
<ul>
<li>06/24/2018/06/25/2018: At approximately 2:45 am PST, the doctor informed me that she was not responding, hadn't responded once during the entire ordeal, and he was going to stop intervention. She was pronounced deceased.&nbsp;</li>
</ul>
<ul>
<li>The boys were escorted to a consultation room. I met them there and they expected to hear she was better. There was a lot of screaming and crying when I told them she'd passed. Then Flavia's mom and dad arrived. We all went to the room, saw Flavia, everyone had their own reactions.</li>
</ul>
<ul>
<li>Eventually, I took the boys home. Flavia's mom and dad followed and stayed for a while. Then it was clear the boys just needed space. They headed home to grieve. The boys spent today watching The Flash episodes. Flavia, the boys, and I had started on season one. We spent all yesterday watching it together. I think they want to finish out because we all started it. They also wanted the distraction. I bought them some more games for the handhelds.&nbsp;</li>
</ul>
<div>
And that's now. Several people lovingly brought us food, one came and took some bulk trash for me. My mom's coming tonight on a plane.&nbsp;</div>
<div>
<br /></div>
<div>
I know there's nothing you can say. I know you care. I know I can ask you for help when I need it. Right now, we just want to let it settle. The boys facilitate from crying to numb to distracted. We've laughed a few times, which is nice.&nbsp;</div>
<div>
<br /></div>
<div>
Flavia is in heaven. We didn't lose her. We know where she is, we'll see her again someday. The baby is in heaven too. I don't know if it was a girl or boy, maybe they'll tell us when they complete the autopsy. In my heart, it I believe it was our girl, Azarea. I'll see both of them again someday.&nbsp;</div>
<br />
<br />
For now, we are heartbroken, sad, angry, lost, confused, shocked, living in a surrealness that makes it feel that any moment she'll walk in the door, or walk from another room, or the hospital will call and say "we were wrong, she responded"... But we will make it. Team Wolfe. We'll let you know what we need as time goes on.<br />
<br />
Numb just ended, and I have to go cry now. Thank you for your love and support.<br />
<br />
**UPDATE: for those who asked, the autopsy did reveal a massive blot clot inithe left leg that shot loose bilateral to both lungs. Autopsy also revealed an enlarged heart that was most likely an issue for years leading up to this, and may have caused the hormone and weight issues prior. **<br />
<br />
<br />
<br />
Darrell<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper (in eternity)!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span></div>
<div class="MsoNormal">
<br /></div>
Some asked:<br />
** For the moment, you can mail things to 3403 N 4th St, CDA, ID 83815. We'll set up a GoFundMe account later, some asked for that too. Just don't have the energy to do that right now. Maybe later today or tomorrow.