---
title: 'Shots in the dark...'
date: '2018-12-11T09:00:00.0000000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7540240580454014424'
blogger_filename: '/2018/12/shots-in-dark.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
  - 'distortion'
---

<i>For the first time since my wife passed, June 25, 2018, I've decided to start writing again. Not sure if this will make it into the final cut of the novel I'm working on (Distortion, a White Noise series), but I thought I'd share the rough draft of my first words back.</i><br />
<br />
<div style="text-align: center;">
***</div>
<br />
Wet hail assaulted the thin metal roof of the RV like a barrage of weapons fire. Ash sat on the floor, back against the couch, dripping red water onto the floor, a mix of his own from a rough patch and hers... His mind was black as the room, his thoughts hidden from himself like the storm had hidden the stars.<br />
<br />
Like the random hits of blue lightning outside the windows, images flashed through his mind of the night's events. What he could have done differently. What he could have done to prevent it. Every plan had been stunted, but they persevered, until the end. He kept coming up blank. Every alternative could have ended them here. He was lost. Blank. Mind racing on a track with no destination.<br />
<br />
He was forced to leave Destiny’s body on the ground as he ran from the sniper. By the time he’d doubled back, the nest was cleaned and empty. Police, Fire, Ambulance now covered the scene below, they’d tend to her better than he could.<br />
<br />
Chester looked terrified as they put the hood over his head, and stuffed him into one of the five black armored Escalades and drove off.<br />
<br />
Escape. Run. Drive. Ash found the RV parked at the rendezvous point; now a rendezvous of one. After driving for two hours, Ash found his arms and legs shaking too much to continue. He pulled off onto an old mountain road, snaked up into the hills, and pulled over in a clearing covered by tall pines.<br />
<br />
Now he sat. Shaking. Blank. He should be feeling… something. Angry. Sad. Something. But he just sat, staring at the small refrigerator door, the faux grains making moving patterns in his head when the lightning revealed them.<br />
<br />
<br />
The next morning... TBC<br />
<br />
<div style="text-align: center;">
***</div>
<br />
Thank you for reading,<br />
<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span></div>
<div class="MsoNormal">
<br /></div>
<br />
<br />