---
title: 'Starting a business'
date: '2018-02-13T03:36:00.0000000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '706919822528412447'
blogger_filename: '/2018/02/starting-business.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<div class="WordSection1">
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
&nbsp;Many folks ask me how to start a business, here are the steps, in general.</div>
<div>
<div style="margin-left: 5.4pt; margin-top: 2.75pt;">
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<b style="text-indent: -0.25in;"><span style="color: #17365d; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 16.0pt;"><br /></span></b></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<b style="text-indent: -0.25in;"><span style="color: #17365d; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 16.0pt;">1. Choosing a Type/Structure:</span></b></div>
</div>
<div style="margin-top: 22.4pt;">
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">The US Small Business Administration (SBA) has a ton of information about starting, structuring, and launching a business. The SBA.Gov website has   a special topic on choosing a <a href="https://www.sba.gov/business-guide/launch/choose-business-structure-types-chart">  Business Structure</a>.<o:p></o:p></span></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<b><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Most Common:</span></b><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;"><o:p></o:p></span></div>
<div>
<table border="1" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="border-collapse: collapse; border: none;">  <tbody>
<tr>  <td style="border: solid #a3a3a3 1.0pt; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 117.35pt;" valign="top" width="156"><div style="margin-bottom: 0.0001pt; margin: 0in;">
<b><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Business structure</span></b><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;"><o:p></o:p></span></div>
</td>  <td style="border-left: none; border: solid #a3a3a3 1.0pt; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 164.6pt;" valign="top" width="219"><div style="margin-bottom: 0.0001pt; margin: 0in;">
<b><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Ownership</span></b><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;"><o:p></o:p></span></div>
</td>  <td style="border-left: none; border: solid #a3a3a3 1.0pt; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 93.1pt;" valign="top" width="124"><div style="margin-bottom: 0.0001pt; margin: 0in;">
<b><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Liability</span></b><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;"><o:p></o:p></span></div>
</td>  <td style="border-left: none; border: solid #a3a3a3 1.0pt; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 90.65pt;" valign="top" width="121"><div style="margin-bottom: 0.0001pt; margin: 0in;">
<b><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Taxes</span></b><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;"><o:p></o:p></span></div>
</td>  </tr>
<tr>  <td style="border-top: none; border: solid #a3a3a3 1.0pt; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 117.35pt;" valign="top" width="156"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Business structure:<o:p></o:p></span></div>
<div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<b><span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Sole proprietorship (often uses a DBA / ABN)</span></b><span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;"><o:p></o:p></span></div>
</td>  <td style="border-bottom: solid #a3a3a3 1.0pt; border-left: none; border-right: solid #a3a3a3 1.0pt; border-top: none; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 164.6pt;" valign="top" width="219"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Ownership:<o:p></o:p></span></div>
<div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">One person<o:p></o:p></span></div>
</td>  <td style="border-bottom: solid #a3a3a3 1.0pt; border-left: none; border-right: solid #a3a3a3 1.0pt; border-top: none; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 93.1pt;" valign="top" width="124"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Liability:<o:p></o:p></span></div>
<div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Unlimited personal liability<o:p></o:p></span></div>
</td>  <td style="border-bottom: solid #a3a3a3 1.0pt; border-left: none; border-right: solid #a3a3a3 1.0pt; border-top: none; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 90.65pt;" valign="top" width="121"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Taxes:<o:p></o:p></span></div>
<div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Personal tax only<o:p></o:p></span></div>
</td>  </tr>
<tr>  <td style="border-top: none; border: solid #a3a3a3 1.0pt; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 117.35pt;" valign="top" width="156"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Business structure:<o:p></o:p></span></div>
<div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<b><span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Limited liability company (LLC)</span></b><span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;"><o:p></o:p></span></div>
</td>  <td style="border-bottom: solid #a3a3a3 1.0pt; border-left: none; border-right: solid #a3a3a3 1.0pt; border-top: none; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 164.6pt;" valign="top" width="219"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Ownership:<o:p></o:p></span></div>
<div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">One or more people<o:p></o:p></span></div>
</td>  <td style="border-bottom: solid #a3a3a3 1.0pt; border-left: none; border-right: solid #a3a3a3 1.0pt; border-top: none; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 93.1pt;" valign="top" width="124"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Liability:<o:p></o:p></span></div>
<div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Owners are not personally liable<o:p></o:p></span></div>
</td>  <td style="border-bottom: solid #a3a3a3 1.0pt; border-left: none; border-right: solid #a3a3a3 1.0pt; border-top: none; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 90.65pt;" valign="top" width="121"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Taxes:<o:p></o:p></span></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Self-employment tax<o:p></o:p></span></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Personal tax or corporate tax<o:p></o:p></span></div>
</td>  </tr>
<tr>  <td style="border-top: none; border: solid #a3a3a3 1.0pt; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 117.35pt;" valign="top" width="156"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Business structure:<o:p></o:p></span></div>
<div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<b><span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Corporation - C corp</span></b><span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;"><o:p></o:p></span></div>
</td>  <td style="border-bottom: solid #a3a3a3 1.0pt; border-left: none; border-right: solid #a3a3a3 1.0pt; border-top: none; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 164.6pt;" valign="top" width="219"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Ownership:<o:p></o:p></span></div>
<div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">One or more people<o:p></o:p></span></div>
</td>  <td style="border-bottom: solid #a3a3a3 1.0pt; border-left: none; border-right: solid #a3a3a3 1.0pt; border-top: none; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 93.1pt;" valign="top" width="124"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Liability:<o:p></o:p></span></div>
<div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Owners are not personally liable<o:p></o:p></span></div>
</td>  <td style="border-bottom: solid #a3a3a3 1.0pt; border-left: none; border-right: solid #a3a3a3 1.0pt; border-top: none; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 90.65pt;" valign="top" width="121"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Taxes:<o:p></o:p></span></div>
<div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Corporate tax<o:p></o:p></span></div>
</td>  </tr>
<tr>  <td style="border-top: none; border: solid #a3a3a3 1.0pt; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 117.35pt;" valign="top" width="156"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Business structure:<o:p></o:p></span></div>
<div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<b><span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Corporation - S corp</span></b><span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;"><o:p></o:p></span></div>
</td>  <td style="border-bottom: solid #a3a3a3 1.0pt; border-left: none; border-right: solid #a3a3a3 1.0pt; border-top: none; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 164.6pt;" valign="top" width="219"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Ownership:<o:p></o:p></span></div>
<div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">One or more people, but no more than 100, and all must be U.S. citizens<o:p></o:p></span></div>
</td>  <td style="border-bottom: solid #a3a3a3 1.0pt; border-left: none; border-right: solid #a3a3a3 1.0pt; border-top: none; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 93.1pt;" valign="top" width="124"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Liability:<o:p></o:p></span></div>
<div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Owners are not personally liable<o:p></o:p></span></div>
</td>  <td style="border-bottom: solid #a3a3a3 1.0pt; border-left: none; border-right: solid #a3a3a3 1.0pt; border-top: none; padding: 1.95pt 3.0pt 1.95pt 3.0pt; width: 90.65pt;" valign="top" width="121"><div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #ab3ea0; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Taxes:<o:p></o:p></span></div>
<div style="margin-bottom: 22.0pt; margin-left: 0in; margin-right: 0in;">
<span style="color: #333333; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Personal tax<o:p></o:p></span></div>
</td>  </tr>
</tbody>  </table>
</div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<br /></div>
<div class="MsoNormal" style="margin-left: 27.0pt; mso-list: l5 level1 lfo4; text-indent: -.25in; vertical-align: middle;">
<span style="color: #17365d;"><span style="mso-list: Ignore;"><span style="font-family: calibri, sans-serif;"><span style="font-size: 16pt;"><b>2.</b></span></span><span style="font-family: times new roman; font-size: xx-small;">&nbsp;Entity</span></span></span><b><span style="color: #17365d; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 16.0pt;">&nbsp;Filing in Idaho<o:p></o:p></span></b></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">The Idaho Secretary of State  <a href="https://sos.idaho.gov/">website</a> contains all of the forms one could need to star their business filing. On the left, select  <a href="https://sos.idaho.gov/corp/index.html">Business Entities</a>, the select the entity type you are interested in creating.<o:p></o:p></span></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Most common are:</span></div>
<blockquote class="tr_bq" style="margin-bottom: 0.0001pt; margin: 0in;">
<ul>
<li><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11pt; text-indent: -0.25in;">A</span><a href="https://sos.idaho.gov/corp/abn_form.html" style="text-indent: -0.25in;"><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">ssumed Business Name (ABN)</span></a><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11pt; text-indent: -0.25in;"> / Doing   Business As (DBA)</span></li>
<li><a href="https://sos.idaho.gov/corp/corp_form.html" style="text-indent: -0.25in;"><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Corporation</span></a><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11pt; text-indent: -0.25in;"> (INC)</span></li>
<li><a href="https://sos.idaho.gov/corp/llc_form.html" style="text-indent: -0.25in;"><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Limited Liability Company</span></a><span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11pt; text-indent: -0.25in;"> (LLC)</span></li>
</ul>
</blockquote>
<div class="MsoNormal" style="margin-left: 27.0pt; mso-list: l4 level1 lfo5; text-indent: -.25in; vertical-align: middle;">
<o:p></o:p></div>
<div class="MsoNormal" style="margin-left: 27.0pt; mso-list: l0 level1 lfo6; text-indent: -.25in; vertical-align: middle;">
<o:p></o:p></div>
<div class="MsoNormal" style="margin-left: 27.0pt; mso-list: l0 level1 lfo6; text-indent: -.25in; vertical-align: middle;">
<o:p></o:p></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">You will print out the form, sign it, and send it by mail with a check for the filing fee ($25 or $100, typically). The Secretary of State in Idaho   takes FOREVER to complete the filing. Could be two weeks, could be six weeks. Could be longer.  <o:p></o:p></span></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">&nbsp;</span><b style="text-indent: -0.25in;"><span style="color: #17365d; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 16.0pt;"><span style="mso-list: Ignore;">3. EIN</span></span></b><b style="text-indent: -0.25in;"><span style="color: #17365d; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 16.0pt;">&nbsp;/ Tax ID</span></b></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">If you are any type of business except a Sole Proprietor using your name or an ABN/DBA, you'll need to have a Tax ID (EIN). Simple, easy, and Free   process. Just go to <a href="https://www.irs.gov/">IRS.Gov</a>, select "<a href="https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online">Apply for an Employer ID Number (EIN)</a>", under step 3   select <a href="https://sa.www4.irs.gov/modiein/individual/index.jsp">Apply Now</a>, then select Begin Application. Follow the prompts and make sure to save the PDF at the end before closing the screen.<o:p></o:p></span></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">&nbsp;</span><b style="text-indent: -0.25in;"><span style="color: #17365d; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 16.0pt;"><span style="mso-list: Ignore;">4.<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-weight: normal; line-height: normal;">&nbsp;</span></span></span></b><b style="text-indent: -0.25in;"><span style="color: #17365d; font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 16.0pt;">Opening Your Business Accounts</span></b></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 11.0pt;">Once the Secretary of State shows the filing on their website, we're ready to open accounts. We can pull that paperwork directly from the site, so   you just bring your ID, opening deposit, and EIN/TaxID. <o:p></o:p></span></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: 0.0001pt; margin: 0in;">
<span style="font-family: &quot;calibri&quot; , &quot;sans-serif&quot;; font-size: 14.6667px;">DarrellWolfe&nbsp;</span></div>
</div>
</div>
</div>
