---
title: 'Embracing Grief - The process God gave you to heal'
date: '2018-09-24T20:53:00.0000000+00:00'
draft: false
categories:
  - 'Lessons in Grief'
---

The following was a question from a Widow/Widower support group I belong to:<br />
<br />
<h3>
What is the most important thing you've learned about grief?</h3>
<br />
My Answer:<br />
<br />
<blockquote class="tr_bq">
<b>Grief is a process to be embraced and walked through.&nbsp;</b></blockquote>
<br />
Your physical brain has developed protein structures (memories and muscle memories) that tell your body to react in a certain way.<br />
<br />
These structures tell the leg to move when walking and they tell the body and mind to be a certain way at home with your spouse, certain expected norms.<br />
<br />
Just as when a Vet loses a limb, a widow(er) loses something much more profound, their other half.<br />
<br />
The new treatment for those who lose limbs is to activate the new nerve endings by rubbing them frequently with various materials (hard, soft, scratchy, smooth, hot, cold) so the brain can learn the new nerve endings. This helps alleviate "Phantom Limb Syndrome".<br />
<br />
God gave us Widows(ers) the gift of Grief to help us recognize and process these protein structures in the brain as they relate to our late spouse. They are gone. Grief helps us come to terms with that and then continue to live a God-given fulfilling life.<br />
<br />
This only works when we embrace the grief process, instead of burying and ignoring the process.<br />
<br />
That's been the more precious, if not hardest, lesson I've learned.<br />
<br />
<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span></div>
<div class="MsoNormal">
<br /></div>
<br />
<br />