---
title: 'Expression...'
date: '2018-04-04T06:04:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6604368987555276060'
blogger_filename: '/2018/04/expression.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<div dir="ltr">
Bob Hamp has a teaching called <a href="https://castbox.fm/vb/23739127">Freedom from Depression</a>.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
He says that a synonym for Depression it Suppression; and, an antonym is Expression.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
In other words, the opposite of Depression is to allow the Expression of who you were created by God to be.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
As soon as I typed that, my Knowledge of Good tried to figure out how to make that happen. I started thinking about how to find out who or what I was created to be, then force it to happen, work harder at it, go get a degree, write more, do more of whatever the right stuff is...</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Wrong.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
All of that thinking comes from the wrong Tree... That's the Tree of Knowledge...</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
It's trying harder the Knowledge of Good...&nbsp;</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Totally the wrong tree.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
We must look to the other tree...</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
LIFE is sourced in The One who created us.</div>
<div dir="ltr">
LIFE didn't require a single good deed. LIFE was received by simply being in the presence of The One.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Adam was not made immortal, contrary to popular belief. Adam was made to require frequently the Tree of Life. As long as he ate of that tree, he would remain alive forever. Choosing the Tree of Knowledge cut him off from the Tree of Life.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Eventually, the slow cadence of death took its toll and he died, 900+ years later. The source of life was strong enough to sustain him for that long without a refill.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
But only in the Presence of The One can we again find Life ourselves.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Got Life?</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Selah<br />
<br />
Bonus thought: what activities in your life make you feel more alive and which make you feel less alive (more numb)?</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
<br /></div>
<div class="MsoNormal">
<div class="MsoNormal" style="background-color: white; margin: 0px;">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal" style="background-color: white; margin: 0px;">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span><span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant&nbsp;</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span><span style="font-family: &quot;tempus sans itc&quot;;"><a href="mailto:me@DarrellWolfe.com">me@DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="http://www.darrellwolfe.com/">www.DarrellWolfe.com</a></span></div>
</div>
<div class="MsoNormal">
</div>
<div dir="ltr">
<br />
<br />
<br />
<br />
<br /></div>
