---
title: 'Constitutional Amendment Proposition: We The People Clause'
date: '2018-04-13T14:43:00.0000000+00:00'
draft: false
categories:
  - 'Government'
---
### Constitutional Amendment Proposition: We The People Clause

#### We are taking back the government\...

It's high time for another [amendment](https://en.wikipedia.org/wiki/Constitutional_amendment) to the constitution. There are already several great proposals, including a [Convention of the States](https://conventionofstates.com/) to make it happen.

As I've been thinking about it, there are several things I would like to see in an amendment. Here are a few points to consider:

**1. Preserve the Original Consitution**: The amendments should reinforce or clarify the intent of the original constitution, ***not change it***. Article 1, Section 9, paragraph 5 of the US Constitution says that there shall be no direct tax (income tax, property tax, etc.). The 16th Amendment Reversed this protection, and should never have been passed.

  ----------------------------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- --------------- ------------------ --------------
  [16th](https://en.wikipedia.org/wiki/Sixteenth_Amendment_to_the_United_States_Constitution "Sixteenth Amendment to the United States Constitution")   Permits Congress to levy an [income tax](https://en.wikipedia.org/wiki/Income_tax "Income tax") without apportioning it among the [states](https://en.wikipedia.org/wiki/U.S._state "U.S. state") or basing it on the [United States Census](https://en.wikipedia.org/wiki/United_States_Census "United States Census").   July 12, 1909   February 3, 1913   3 years
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      6 months
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      22 days

  ----------------------------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- --------------- ------------------ --------------

**2. Power/Control**: When you give government power, it does not like to give it back or reduce its influence. It's like a giant power suck. Case in point, the 27th Amendment was proposed to make sure that the Congress wouldn't give themselves raises, so it demanded that any raise given not take effect until after the next election. The result? It took 202 YEARS for a congress to finally ratify (agree) to the proposal.

[The 27th: Wiki](https://en.wikipedia.org/wiki/List_of_amendments_to_the_United_States_Constitution)

  --------------------------------------------------------------------------------------------------------------------------------------------------------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -------------------- ---------------------------------------------------------------------------------------------------------------------- --------------
  [27th](https://en.wikipedia.org/wiki/Twenty-seventh_Amendment_to_the_United_States_Constitution "Twenty-seventh Amendment to the United States Constitution")   Delays laws affecting Congressional salary from taking effect until after the next election of [representatives](https://en.wikipedia.org/wiki/United_States_House_of_Representatives "United States House of Representatives").   September 25, 1789   May 5, 1992^[\[5\]](https://en.wikipedia.org/wiki/List_of_amendments_to_the_United_States_Constitution#cite_note-5)^   202 years
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 7 months
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 10 days

  --------------------------------------------------------------------------------------------------------------------------------------------------------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -------------------- ---------------------------------------------------------------------------------------------------------------------- --------------

3\. Amendments should clarify the rights of the people and restrict the rights of the Government.

**New Proposals**

That being said, here are some of the things I'd like to see in a new Constitutional Amendment:

**1. REPEAL THE 16TH AMENDMENT AND CLARIFY** that no Tax, Levy, Fine, Fee, Ticket, or any other cost shall be laid on any individual person or entity or their property. This includes the removal and ban of all Income Taxes, Property Taxes, Traffic Tickets, Licencing Fees (driver's licenses, hunting licenses, or gun ownership licenses, etc.).

**2. HARD TERM LIMITS** should be enacted for 100% of elected officials. The current state of affairs is a direct result of "career politicians". These offices were meant to be held by "statesmen", who were people leaving the private sector to serve in the state for a period and then return to live under the laws they produced or preserved.

**A. 2-Terms per office**: No person shall hold any elected office at any level (Federal, State, County, City, or otherwise) for more than 2 terms in their lifetime.

**B. 4-Terms per individual:** No person shall hold any combination of elected offices for more than 4 terms.

**3. HARD INCOME LIMITS:** No elected official shall make more annually in total government compensation than the previous years [US Household Median Income](https://en.wikipedia.org/wiki/Median_income) for the US Population as a whole; currently \$43,585.00 annually.

**4. REAFFIRM THE 2ND AMENDMENT:** No laws shall be passed regarding gun ownership except where an actual crime using a gun has been committed by the restricted.

**5. VICTIM REQUIREMENT:** No law shall be passed or enforced making any activity illegal, nor shall any person or entity be prosecuted or jailed, except where a specific person/entity has caused a specific harm to a person's/entity's person or property. No government body shall be considered a person or entity, nor shall any government body be considered harmable under this protection.

I'll probably come back an updated this later\... you have any ideas? Comment below!

Darrell G. Wolfe

Storyteller \| Writer \| Thinker \| Consultant \| [Multipotentialite](https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en)
