---
title: 'Debt Disputes: What to do with collections, charge-offs, and unknown items on your credit report.'
date: '2018-02-11T09:03:00.0000000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4258361550663524767'
blogger_filename: '/2018/02/debt-disputes-what-to-do-with_11.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Money'
---

<div class="WordSection1"><div style="margin-bottom: 0.0001pt; margin: 0in;"><div>Quite often, over the years, I've worked with people who had old items on their credit reports. Sometimes they don't even know what the items are for. Other times they disagree with the legitimacy of the report, or the reason the company says they still owe money.&nbsp;</div><div><br /></div><div>The following is my advice for any such individuals. Take it for what it is. I'm not an "expert" but I've been a loan officer for over 12 years and I've seen quite a bit.&nbsp;</div><ul><li><b>Step One: Debt Validation Letter</b></li><li><b>Step 2.1: Debt Validated/Settle</b></li><li><b>Step 2.2: Debt Not Validated/Still Not Removed.</b></li></ul><div><br /></div><h4>Step One: Debt Validation Letter</h4>See&nbsp;<a href="https://www.thebalance.com/sample-debt-validation-letter-for-debt-collectors-960597">TheBalance.com</a>&nbsp;, I borrowed their letter and made it better. Here's my revised template:<br /><br />Date<br /><br />Your Name<br />Address<br />City, State Zip<br /><br />Debt Collector’s Name<br />Address<br />City, State Zip<br /><br />Re: [insert account number]<br /><br />This letter is sent in response to an item showing on my credit report. I am requesting that you provide validation of this debt. A validation of this debt includes a signed copy of the contract, statements, and notices.<br /><br />If you are unable to comply with a debt validation, you are required to remove this debt from my credit reports. Please provide me a letter confirming this was completed.<br /><br />If you do not comply with this request, I will may seek remediation through filing a complaint with the Consumer Financial Protection Bureau (CFPB) and/or the Idaho Attorney General’s Office (ID AG). Civil and criminal claims may also be pursued.<br /><br />Sincerely,<br /><br />Your Name<br /><br />CC: ID AG<br />CC: CFPB<br /><br /><br /><div style="text-align: center;">********</div><div style="text-align: center;"><br /></div><br /><h4>Step 2.1: Debt Validated/Settle</h4>If they validate the debt, and you are satisfied that you owe it. Work on settling the debt for less than you owe.<br /><ul><li><a href="https://www.daveramsey.com/blog/debt-consolidation-truth?gclid=Cj0KCQiAh_DTBRCTARIsABlT9MYqnAhB3lEAjXIQiw9iXLDxHX1akiHlvHE0tSx94YBXJSFfdVHkbZwaAo33EALw_wcB">Dave Ramsey Article on Debt Settlement</a></li><li><a href="https://www.ovlg.com/letters">Letter Templates</a></li></ul><br />Sample Lump Sum Debt Settlement Offer Letter::<br /><br />Date<br /><br />Acct Number: [insert account number]<br />Credit Card Company Name<br />Company’s Address<br />City, State and ZIP Code<br /><br />Re: Requesting Payoff of my Credit Account<br /><br />Dear [insert company name]:<br /><br />This letter serves as my official offer to pay my past due balance of [insert type of product] with your company [list the name of the card company, account number Account Number]. As you are aware, I am unable to pay the full balance, however, I am able, at this point in time, to gather an amount that I believe will be an agreeable payoff amount.<br /><br />I would like to request that if I pay the amount of [insert total amount here], my account will be considered paid in full.<br /><br />If this is agreed upon, I would also request the following:<br /><br />My account be closed and no further interest or penalty charges would be applied.<br /><br />A written confirmation of your agreement to this proposal be sent to my address below.<br /><br />After agreeing to this proposal and receipt of your written confirmation, I will pay the amount of LUMP SUM AMOUNT via certified check within 10 days of receiving your letter.<br /><br />After you receive and post the payment, I request the following:<br /><br />An official letter indicating that my account is closed and my balance is $0.<br /><br />The account status as reported to the Credit Reporting Agencies be “CLOSED BY REQUEST OF CARDHOLDER” or “PAID IN FULL”<br /><br />Thank you for your prompt attention to this matter. If you would like to discuss this further, please contact me by mail at the address below, by phone at the telephone number, or by email.<br /><br />I look forward to resolving this matter.<br /><br />Sincerely,<br /><br />Your Signature<br />Your Typed Name<br />Phone<br />Email<br />Address<br />City, State and ZIP Code<br /><br /><h4>Step 2.2: Debt Not Validated/Still Not Removed.</h4>If they do not validate the debt, or they do and you are not satisfied with the outcome, you may file a complete. The two best resources are the CFPB and ID AG.<br /><br />Consumer Financial Protection Bureau (CFPB)<br /><a href="https://www.consumerfinance.gov/complaint/">File A Complaint: Here</a><br /><br />The Idaho Attorney General’s Office (ID AG)<br /><a href="http://www.ag.idaho.gov/victimAssistance/victimAssistance_index.html">File A Claim: Here</a><br /><br />Office of the Attorney General<br />700 W. Jefferson Street<br />P.O. Box 83720<br />Boise, ID 83720-0010<br />Phone (208) 334-2400<br />Fax (208) 854-8071<br /><br /><br /><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;;"><br /></span><span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div></div></div>