---
title: 'Give light to my eyes'
date: '2018-06-09T16:49:00.0020000+00:00'
draft: false
categories:
  - 'bible'
  - 'study'
  - 'Armchair Theology'
---

This Psalms is my hearts cry:<br />
<br />
<blockquote class="tr_bq">
<i><b>Psalm 13</b><br />For the director of music. A psalm of David.</i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i>1How long, Lord? Will you forget me forever? How long will you hide your face from me?&nbsp; 2How long must I wrestle with my thoughts and day after day have sorrow in my heart? How long will my enemy triumph over me?&nbsp;</i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i>3Look on me and answer, Lord my God. <b>Give light to my eyes</b>, or I will sleep in death, 4and my enemy will say, “I have overcome him,” and my foes will rejoice when I fall.&nbsp;</i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i>5But I trust in your unfailing love; my heart rejoices in your salvation. 6I will sing the Lord’s praise, for he has been good to me.</i></blockquote>
<br />
<br />
I wrestle with depression... often... pretty much constantly. I try to keep myself above it, I smile, I laugh, I watch funny things, I make jokes... I distract myself by watching television shows, writing, doing chores or hobbies...<br />
<br />
But truth be told, none of that solves anything for very long. They are temporary pain medications to a bruised and battered soul.<br />
<br />
How long? God? How long will I battle with my own soul (mind, will, emotions)?<br />
<br />
It would seem that David suffered from these thoughts too, and fairly constantly if you read through the Psalms.<br />
<br />
<b>The Key</b><br />
<br />
The Key, he indicates, is a new vision. "Give light to my eyes"... God IS light; therefore, seeing things from God's perspective.<br />
<br />
This isn't about self-talk. It's not about trying to convince myself that it's not that bad&nbsp;or convince myself about all the good things I do have... it's about surrendering to the presence of God (feel like it or not, especially when not) and letting him supernaturally break through and give you a glimpse of his eternal vantage point.<br />
<br />
This is not a one-time and done solution. This is something I must do every day. It's THIS DAILY BREAD...<br />
<br />
<i>Selah!</i><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">
