---
title: 'The Rapture Debate'
date: '2018-03-01T08:50:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8066037779678886778'
blogger_filename: '/2018/03/the-rapture-debate.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Rapture'
  - 'End Times'
---

<p dir="ltr">https://bible.org/article/rapture-debate</p>
<p dir="ltr">In this great article, Sid Litke shows that The Rapture and The Second Coming must be different events. There is no other form scriptural stance. </p>
<p dir="ltr">He mentions the less popular view of a Mid Trib Rapture.</p>
<p dir="ltr">In light of a recent video teaching I watched, I'm exploring this as another possible interpretation. Nothing in this article, linked above, would negate a Mid Trib Rapture except the concept of imminence. </p>
<p dir="ltr">Believers are looking to the return of Jesus as the next event that could happen at any moment. </p>
<p dir="ltr">In the event of a Mid Trib Rapture, you can literally set the calendar for the exact day off Jesus' return. This fails the imminence test.</p>
<p dir="ltr">It requires further review and study, but my gut impression is to say anything other than a PreTrib Rapture fails sound scripture reading on the whole.</p>
<p dir="ltr">Still studying though.</p>
<p dir="ltr">Darrell</p>
