---
title: 'Praying for others...'
date: '2018-03-28T15:28:00.0030000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '9135268375377221272'
blogger_filename: '/2018/03/praying-for-others.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'Prayer Time'
  - 'Armchair Theology'
---

<br />
<blockquote class="tr_bq">
<i>And the Lord restored Job's losses when he prayed for his friends. Indeed the Lord gave Job twice as much as he had before. <a href="https://www.biblestudytools.com/nkjv/job/42.html" target="_blank">Job 42:10</a></i></blockquote>
<blockquote class="tr_bq">
<i>For God is my witness, whom I serve with my spirit in the gospel of His Son, that without ceasing I make mention of you always in my prayers... <a href="https://www.biblestudytools.com/nkjv/romans/1.html" target="_blank">Romans 1:9</a></i></blockquote>
<br />
I prayed today, really prayed, for the first time in....&nbsp;years? Maybe not years. Not sure. Everything before now, that I can recall was shouting &amp;&nbsp;complaining, or some form of that. This was the first time in a long time that I prayed from a place of surrender.<br />
<br />
I've been reading Job, off and on, for several years now. Did you ever notice, in Job 42, that it was AFTER Job prayed for his friends (<i>not himself)</i>&nbsp;that God restored Job's losses?<br />
<br />
Interesting, eh?<br />
<br />
So, that happened.<br />
<br />
<br />
<ul>
<li>Men (<i>and women)</i>, when is the last time you prayed for other people?&nbsp;</li>
</ul>
<br />
<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span> <span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
<div class="MsoNormal">
<br /></div>
