---
title: 'A Memorial Message of Hope'
date: '2018-07-07T22:00:00.0000000+00:00'
draft: false
categories:
  - 'Flavia'
  - 'bible'
  - 'Armchair Theology'
---

<h4>
My wife, Flavia Antoinette Wolfe, passed into Glory on 06/25/2018. This is the message/word God gave me.</h4>
<h4>
<b><u>Dealing with Tragedy</u></b></h4>
<br />
<b>When tragedy strikes,</b> we often compelled to ask questions and express doubts:<br />
<span style="white-space: pre;"> </span>• Why?<br />
<span style="white-space: pre;"> </span>• What if… a thousand what-ifs…<br />
<span style="white-space: pre;"> </span>• If only…<br />
<span style="white-space: pre;"> </span>• I should have/shouldn't have<br />
<span style="white-space: pre;"> </span>• Can God really be good?<br />
<span style="white-space: pre;"> </span>• Can the Bible really be true?<br />
<br />
<b>The answer to why is simple, hard, and totally unsatisfying: This World Is Broken.&nbsp;</b><br />
<br />
Sin entered the world, and through sin, death. BUT, God. So many powerful stories have a "but God" moment. Jesus came, he conquered death, and through him, our sorrow is lessened, and a drop of joy lies underneath.<br />
<br />
"These things I have spoken to you, that in Me you may have peace. In the world, you will have tribulation, but be of good cheer, I have overcome the world.” John 16:33 New King James Version (NKJV)<br />
<br />
You WILL have tribulation. That's just as much a promise as anything else in the bible. Trouble is here on this planet for all of us because of sin. He overcame! And Flavia has now received the fruit of that overcoming as she has been received into Glory.<br />
<br />
<h4>
<b><u>God's Word</u></b></h4>
<br />
<b>Breath of Life</b><br />
Genesis 2:7<br />
And the Lord God formed man of the dust of the ground and breathed into his nostrils the breath of life, and man became a living being.<br />
<br />
<b>Dust and Ashes</b><br />
Genesis 3:19<br />
In the sweat of your face, you shall eat bread Till you return to the ground, For out of it you were taken; For dust you are, And to dust, you shall return.<br />
<br />
<b>The Promise</b><br />
2 Corinthians 5:5-9 New King James Version (NKJV)<br />
5 Now He who has prepared us for this very thing is God, who also has given us the Spirit as a guarantee. 6 So we are always confident, knowing that while we are at home in the body we are absent from the Lord. 7 For we walk by faith, not by sight. 8 We are confident, yes, well pleased rather to be absent from the body and to be present with the Lord.<br />
<br />
<b>The Comfort of Christ’s Coming</b><br />
1 Thessalonians 4<br />
13 But I do not want you to be ignorant, brethren, concerning those who have fallen asleep, lest you sorrow as others who have no hope. 14 For if we believe that Jesus died and rose again, even so God will bring with Him those who sleep in Jesus. 15 For this, we say to you by the word of the Lord, that we who are alive and remain until the coming of the Lord will by no means precede those who are asleep. 16 For the Lord Himself will descend from heaven with a shout, with the voice of an archangel, and with the trumpet of God. And the dead in Christ will rise first. 17 Then we who are alive and remain shall be caught up together with them in the clouds to meet the Lord in the air. And thus we shall always be with the Lord. 18 Therefore comfort one another with these words.<br />
<br />
<b>My Father's House</b><br />
John 14:1-3 NIV<br />
1 “Do not let your hearts be troubled. You believe in God; believe also in me. 2 My Father’s house has many rooms; if that were not so, would I have told you that I am going there to prepare a place for you? 3 And if I go and prepare a place for you, I will come back and take you to be with me that you also may be where I am.<br />
<br />
<b>A Door In Heaven</b><br />
Revelation 4 New King James Version (NKJV)<br />
4 After these things I looked, and behold, a door standing open in heaven. And the first voice which I heard was like a trumpet speaking with me, saying, “Come up here, and I will show you things which must take place after this.”<br />
<br />
<b>The Great Exchange</b><br />
<br />
<ul>
<li>You: Give Him your dead life. All of it.&nbsp;</li>
<li>He: Gives your his LIFE. All of it.</li>
<li>He takes your death, and you take His LIFE.&nbsp;</li>
<li>Your work is to believe (John 6:29). That's it. Believe it in your heart, speak it out loud with your mouth, and you will have it. Guaranteed - John 3:16-18</li>
</ul>
<br />
<br />
Romans 10:9-11<br />
If you confess with your mouth, “Jesus is Lord,” and believe in your heart that God raised Him from the dead, you will be saved. For with your heart you believe and are justified, and with your mouth, you confess and are saved. It is just as the Scripture says: “Everyone who believes in Him will not be put to shame.”<br />
<br />
<br />
<h4>
<b><u>Three Keys To Remember While Grieving</u></b></h4>
<br />
<b><span style="white-space: pre;"> </span>1. It's not God's Fault</b><br />
From here on out, do not say that God "took her". God did not take her, but he did receive her. The devil comes only to steal, kill, and destroy; but, Jesus came that we might have LIFE and life more and more abundantly.<br />
<br />
<b><span style="white-space: pre;"> </span>2. Honor her: Live LIFE</b><br />
That LIFE we live on earth comes in quantities. It's not simply on or off. You can have some life, or more of it, or be full of it. Even day today, you can have more or less LIFE flowing through you. And ultimately, when we go to be with Flavia, we will have LIFE in a way we cannot even fathom here.<br />
<br />
<b><span style="white-space: pre;"> </span>3. Celebrate Her in memories of the good times and through living a better life because you knew her:</b><br />
We do not mourn FOR her, we mourn for ourselves. We miss her. We want her back. We want her presence, laughs, smiles, hugs… wisdom. We celebrate her life, influence, and passion. We celebrate her legacy in the lives of the people she impacted, Connor and Preston most of all… and myself.<br />
<br />
<br />
<h4>
<b><u>Parting thought:</u></b></h4>
Don't live every day like it's your last… live every day like it's their last.<br />
<br />
We'll be here to talk about her for a little while, but this officially ends our service. Thank you for coming to support our family and celebrate her life.<br />
<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">
