---
title: 'Holy Spirit > Righteousness > Peace > Joy'
date: '2019-10-09T16:28:00.0000000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3461854394761341572'
blogger_filename: '/2019/10/holy-spirit-righteousness-peace-joy.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

<br />
<i>For the kingdom of God does not consist of food and drink, but <b>righteousness, peace, and joy</b> in the Holy Spirit.&nbsp;<a href="https://biblehub.com/romans/14-17.htm" target="_blank">Romans 14:17 NET Bible</a></i><br />
<div>
<br /></div>
<a href="https://biblehub.com/lexicon/romans/14-17.htm" target="_blank">Lexicon at Bible Hub:</a><br />
<table border="0" cellpadding="5" cellspacing="1" class="maintext" style="background-color: #aaaaaa; color: #001320; font-family: Roboto, Arial, Helvetica, sans-serif; font-size: 16px; text-align: justify; width: 100%px;"><tbody>
<tr><td class="eng" style="background-color: white; font-size: 15px; line-height: 22px; text-align: left;" valign="top">but righteousness</td><td class="greek2" style="background-color: white; font-family: Cardo, GentiumAlt, &quot;Galilee Unicode Gk&quot;, &quot;Galatia SIL&quot;, &quot;Palatino Linotype&quot;, Arial, Helvetica, sans-serif; font-size: 21px; line-height: 25px;" valign="top"><span greek3="">δικαιοσύνη<br /><span class="translit" style="font-size: 15px; line-height: 22px;">(dikaiosunē)</span></span></td><td class="strongsnt" style="background-color: white; font-size: 15px; line-height: 22px; text-align: left;" valign="top"><a href="http://strongsnumbers.com/greek/1343.htm" style="color: #0092f2; text-decoration-line: none;">1343:</a>&nbsp;<span class="eng2" style="font-family: Arial, Helvetica, sans-serif; line-height: 22px;">righteousness, justice</span></td><td class="eng3" style="background-color: white; font-size: 15px; line-height: 22px; text-align: left;" valign="top">from&nbsp;<a href="http://strongsnumbers.com/greek/1342.htm" style="color: #0092f2; text-decoration-line: none;">dikaios</a></td></tr>
<tr><td class="eng" style="background-color: white; font-size: 15px; line-height: 22px; text-align: left;" valign="top">and peace</td><td class="greek2" style="background-color: white; font-family: Cardo, GentiumAlt, &quot;Galilee Unicode Gk&quot;, &quot;Galatia SIL&quot;, &quot;Palatino Linotype&quot;, Arial, Helvetica, sans-serif; font-size: 21px; line-height: 25px;" valign="top"><span greek3="">εἰρήνη<br /><span class="translit" style="font-size: 15px; line-height: 22px;">(eirēnē)</span></span></td><td class="strongsnt" style="background-color: white; font-size: 15px; line-height: 22px; text-align: left;" valign="top"><a href="http://strongsnumbers.com/greek/1515.htm" style="color: #0092f2; text-decoration-line: none;">1515:</a>&nbsp;<span class="eng2" style="font-family: Arial, Helvetica, sans-serif; line-height: 22px;">&nbsp;</span></td><td class="eng3" style="background-color: white; font-size: 15px; line-height: 22px; text-align: left;" valign="top">of uncertain derivation, perhaps from eiró (to join): lit. or fig. peace, by impl. welfare</td></tr>
<tr><td class="eng" style="background-color: white; font-size: 15px; line-height: 22px; text-align: left;" valign="top">and joy</td><td class="greek2" style="background-color: white; font-family: Cardo, GentiumAlt, &quot;Galilee Unicode Gk&quot;, &quot;Galatia SIL&quot;, &quot;Palatino Linotype&quot;, Arial, Helvetica, sans-serif; font-size: 21px; line-height: 25px;" valign="top"><span greek3="">χαρὰ<br /><span class="translit" style="font-size: 15px; line-height: 22px;">(chara)</span></span></td><td class="strongsnt" style="background-color: white; font-size: 15px; line-height: 22px; text-align: left;" valign="top"><a href="http://strongsnumbers.com/greek/5479.htm" style="color: #0092f2; text-decoration-line: none;">5479:</a>&nbsp;<span class="eng2" style="font-family: Arial, Helvetica, sans-serif; line-height: 22px;">joy, delight</span></td><td class="eng3" style="background-color: white; font-size: 15px; line-height: 22px; text-align: left;" valign="top">from&nbsp;<a href="http://strongsnumbers.com/greek/5463.htm" style="color: #0092f2; text-decoration-line: none;">chairó</a></td></tr>
</tbody></table>
<br />
<br />
<b>Righteousness</b>: I AM, right now, regardless of failings or faults, the RIGHTEOUSNESS of Jesus in the eyes of God. I stand before my Father in right standing not because of a single thing I've done except that I accepted his Son standing in my place. When he sees me, he sees his son, in whom he is well pleased.<br />
<br />
<b>Peace</b>: Eirene/Shalom: Nothing Missing. Nothing Broken. Everything Whole and Complete. This is the wellness of spirit, soul, body, mind, finances. It's an all-encompassing peace. I need not have it functioning to understand it belongs to me. I have tools I don't use in my toolbox, I still own them. This is a tool I need to be more thoughtful and purposeful about taking advantage of.<br />
<br />
<b>Joy</b>: This word Chario is a derivative of the word Charis (Grace/Favor/Gift). He apportions to each one of us a Gift (Charis). We find ourselves overwhelmed by his Grace/Favor toward us and it brings us Joy, even in the midst of heavy and sorrow-filled times.<br />
<br />
Each Element is a pre-requisite for the one before. Each begets the next.<br />
<br />
<b>Righteousness &gt; Peace &gt; Joy</b><br />
<br />
But the preemptive element to all of this is the Holy Spirit. Without having an active working relationship with God, allowing the Holy Spirit to work in and through me, my mind is dulled to my right standing, my peace is not enforced, and my joy is vacant without the first two.<br />
<br />
So it is actually: <b><u>Holy Spirit</u> &gt; Righteousness &gt; Peace &gt; Joy</b><br />
<br />
Each item causes the next, in succession. You cannot have Joy without Peace, or Peace without fully knowing your Right Standing, and you cannot know your Righteousness without a working relationship with the Holy Spirit.<br />
<br />
<b>Okay, so all of that is fine and well, but how do I activate that?</b><br />
<br />
Each of us is different, there's no cookie-cutter answer that I can provide.<br />
<br />
What I can say, is that <b>I am at my best when</b> I go for a walk every morning and speak to Him and let Him speak to me (the second being more important). Things just tent to fall in line better when I do that.<br />
<br />
How can you make a little room for the Holy Spirit to speak to you today? I guarantee that once he does, these other three will begin to make room for themselves.<br />
<br />
Maybe start by completing this sentence three times:<br />
<br />
<ol>
<li>I am at my best when....&nbsp;</li>
<li>I am at my best when....&nbsp;</li>
<li>I am at my best when....&nbsp;</li>
</ol>
<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span></div>
