---
title: 'Benefits Package of Heaven'
date: '2019-11-14T10:01:00.0010000+00:00'
draft: false
categories:
  - 'Musings'
---

Psalms 103, Benefits of God<div><br></div><div><br></div><div>As I ponder the benefits package of God, I'm forced to admit I haven't seen much of this play out in my life. It's been a collosal disappointment, frankly.&nbsp;</div><div><br></div><div>Yet I accept my part. How many times did He tell me to do a thing, and I did not. Not to do a thing, and I did. Invest, save, move, he's constantly talking to those who will listen. Partnership. He will not do your job for you.&nbsp;</div><div><br></div><div>If you're an author, he will inspire your book, he won't force you to sit and learn the craft and sit and write the book.</div><div><br></div><div>His Benefits take on a new meaning for me tonight, as I look them over more closely.&nbsp;</div><div><br></div><div>Forgiveness: implies I first failed.</div><div><br></div><div>Healing: implies I was first sick or broken.</div><div><br></div><div>Redemption: implies destruction came upon me.</div><div><br></div><div>Mercies: imply He protected me from myself.</div><div><br></div><div>Renewed Youth: implies the youth was spent and gone first.</div><div><br></div><div>Our Daddy keeps his covenant. He has compassion for our pain, even and maybe especially when it's self inflicted.</div><div><br></div><div>I don't understand my plight. I don't remember all the instructions I refused to obey, or even hear. I don't know why I'm living the life I live today. Or experiencing these particular pains.</div><div><br></div><div>Some of it is just because we live in a broken world. And in a broken world, things break.&nbsp;</div><div><br></div><div>Although I'm positive some of it was disobedience, some of it may have just been the brokenness of this world.&nbsp;</div><div><br></div><div>It rains on the just and unjust alike. Sometimes rains come and water dry land producing a harvest. Sometimes they come as Tsunamis, wiping out villages. Rain comes on us all.&nbsp;</div><div><br></div><div>But I know Daddy is Good and He is Able. Worst case, I die and this pain stops and I end up in paradise. Best case, I pick myself up, and start winning some victories.&nbsp;</div><div><br></div><div>This covenant is not a covenant of rules and duties. It's a covenant of LOVE, relationship. It's a covenant that says "Come sit in my lap, be with me, build relationship with me, and let this other stuff fall into place while you weren't looking".&nbsp;</div><div><br></div><div>I have ONLY one job. Strive to enter into His rest. His presence. His life giving presence.&nbsp;</div><div><br></div><div>The things you tried to KNOW (figure out with your mind) come from the wrong tree. The Tree of Knowledge brought death, and still does.&nbsp;</div><div><br></div><div>The things he REVEALS (hear, believe, obey) those come out of relationship. The Tree of Life brings relationship with Daddy, walking in the cool of the day, receiving His instructions and clarity.</div><div><br></div><div>My only job.... Today... Is to say "Speak, Daddy, Pappa, I'm listening".&nbsp;</div><div><br></div><div>#BeStillBeLed</div><div><br></div>