---
title: 'What does it mean to be a Widower?'
date: '2019-01-29T11:10:00.0000000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '653684709761119696'
blogger_filename: '/2019/01/what-does-it-mean-to-be-widower.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Lessons in Grief'
---

<br />
Today was supposed to be the day my third child, Azarea, was born.<br />
<br />
We should have a crib ready, house buzzing with the excitement of "it's time". But instead, I sit sleepless in my room, two boys sleeping but suffering from grief in their own ways. Instead of adding a fifth member to the house, we lost Mom and Baby. We are three.<br />
<br />
That was seven months ago.<br />
<br />
I've tried to pick up the pieces&nbsp;as best as I can. Make new friends for me and the boys. I've tried to make the house livable for "our new situation" as it became&nbsp;called. I've made many adjustments, most hard, some good. I even recently made an enemy, through no fault of my own.<br />
<br />
What does it mean to be a Widower?<br />
<br />
It means not wanting to talk about it anymore with people who aren't here, who haven't been here through it with us.<br />
<br />
It means trying to make it through each day without thinking about her, when she's everywhere. She's touched everything in this house.<br />
<br />
It means going through her things, and packing up the items We Three won't ever use.<br />
<br />
It means smiling through the tears. It means sleepless nights and a lonely bed. It means a lack of touch, extended hugs, cuddles, shared inside jokes and shows, and household rhythms.<br />
<br />
It means "why" repeating over and over even though you have all the why's you're going to get.<br />
<br />
Being a Widower means living... when she didn't. It means not just saying goodbye to the person, but the dreams, shared vision, partnership, plans... The entire trajectory of life changes.<br />
<br />
There are no pieces to pick up. There's just absence and void. You have to forge ahead, and make new memories, new plans, new dreams... but you don't want to.<br />
<br />
It means knowing you should play a game with the kids, or clean the house, but having no will to get up and do it.<br />
<br />
Despite all of that...........<br />
<br />
God's been SO good to us this year. We've seen financial blessings from a variety of sources. We've paid off debts, raised credit scores. We're getting ready to buy a new home and start a new life.<br />
<br />
We've made quite a few friends and we're making more. We've seen God bring comfort, encouragement, and gentle reminders of His Love.<br />
<br />
We've seen God show up with a friendly text, invite to join a group, classes, courses, events...<br />
<br />
I've personally gained more clarity on my life, what's important and what isn't. What fights are worth it and which ones aren't.<br />
<br />
I've started college again, which she and I always talked about.<br />
<br />
Even the enemy will come around, he just doesn't know it yet. God's Love is bigger than his hate and fear.<br />
<br />
Someday, we may add to our family again. But that day is not today. Today, I remember what was, what could have been, should have been, and then I look forward.<br />
<br />
The beautiful, bittersweet, Truth, is that Flavia and Azarea are my future, not just my past. Heaven is not our home, but it is our resting place until King Jesus returns. They're safely there, playing and laughing.<br />
<br />
Someday, should it happen before I die, I will meet my King in the air, and Flavia and I will be there together. And then, at some point after that, we'll all reside on earth again, in resurrected bodies.<br />
<br />
What a joyous reunion that'll be.<br />
<br />
For now:<br />
<br />
Happy Birthday Blueberry&nbsp;(Azarea). Flavia is taking care of you there, I've got the boys here. Say hi to my family and friends, and to Jiminy Cricket's kid for me.<br />
<br />
Peace!<br />
<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span></div>
<div class="MsoNormal">
<br /></div>
<br />
<br />