---
title: '2019 Reading List'
date: '2019-01-02T03:09:00.0000000+00:00'
draft: false
---

<br />
A list of the books I've been reading in 2019 (personal growth and for school).<br />
<br />
<br />
<b>Fiction</b><br />
<br />
Author: Lauren Stinton (<a href="https://www.amazon.com/s?k=lauren+stinton&amp;ref=nav_signin">Affiliate Link</a>)<br />
<br />
<a href="https://amzn.to/2NmzAd7">The House of Elah</a>&nbsp;(Volume 1)<br />
<br />
<a href="https://amzn.to/2Obqrn6">The Alusian's Quest</a>&nbsp;(The House of Elah) (Volume 2)<br />
<br />
<a href="https://amzn.to/2OisFku">The King's Man</a>&nbsp;(The House of Elah) (Volume 3)<br />
<br />
<br />
<a href="https://amzn.to/306LLkO">Should I Choose to Die Again</a>&nbsp;(The Hamal Books) (Volume 1)<br />
<br />
<a href="https://amzn.to/30fIrmJ">The One-Eyed Man</a>&nbsp;(The Hamal Books) (Volume 2)<br />
<br />
<br />
<br />
<br />
<b>Non-Fiction</b><br />
<br />
<br />
<a href="https://amzn.to/2OchEl1">Leadership and Self-Deception: Getting Out of the Box</a>, by The Arbinger Institute<br />
<br />
<a href="https://amzn.to/3331Ipt">Atomic Habits: An Easy &amp; Proven Way to Build Good Habits &amp; Break Bad Ones</a>, by James Clear<br />
<br />
<a href="https://amzn.to/2OitdH4">Where Is God When It Hurts?</a>, by Philip Yancey<br />
<br />
<a href="https://amzn.to/309Pxt3">Elements of a Christian Worldview</a>, by Michael Palmer<br />
<br />
<a href="https://amzn.to/30yxo40">Saving the Bible from Ourselves: Learning to Read and Live the Bible Well</a>, by Glenn R. Paauw<br />
<br />
<br />
<br />
Author: C.S. Lewis<br />
<br />
<a href="https://amzn.to/30e0oSE">Mere Christianity</a><br />
<br />
<br />
Author: Dr. Henry Cloud<br />
<br />
<a href="https://amzn.to/2Obr9AM">How To Get A Date Worth Keeping: Be Dating In Six Months Or Your Money Back</a><br />
<br />
<a href="https://amzn.to/2QuhR5U">Boundaries in Dating: How Healthy Choices Grow Healthy Relationships</a><br />
<br />
<a href="https://amzn.to/32UxK6Y">Boundaries Updated and Expanded Edition: When to Say Yes, How to Say No To Take Control of Your Life</a><br />
<br />
<br />
Author: Peter Scazzero<br />
<br />
<a href="https://amzn.to/309ivJn">The Emotionally Healthy Leader: How Transforming Your Inner Life Will Deeply Transform Your Church, Team, and the World&nbsp;</a><br />
<br />
<br />
<b>Other not otherwise catagoried</b><br />
<a href="https://amzn.to/2LHMq3z">101 Conversation Starters for Couples</a>&nbsp;by Gary Chapman and Ramon Presson<br />
<br />
<a href="https://amzn.to/2LCYoLK">Intellectual Foreplay: A Book of Questions for Lovers and Lovers-to-Be</a>, by Eve Eschner Hogan<br />
<br />
<a href="https://amzn.to/30yx4Ck">41 Will Come: Holding On When Life Gets Tough--and Standing Strong Until a New Day Dawns</a>, by Tate, Chuck E.<br />
<br />
<a href="https://amzn.to/2Oip3zj">The Hebrew-Greek Key Word Study Bible: NKJV Edition, Black Genuine Leather (Key Word Study Bibles),</a>&nbsp;by Publishers, AMG<br />
<br />
<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"></div>
