---
title: 'Short Story: The Treasure Room'
date: '2019-05-30T19:41:00.0010000+00:00'
draft: false
categories:
  - 'Short Story - Fiction'
---

<br />
<blockquote class="tr_bq">
<i>For where your treasure is, there will your heart be also.&nbsp;<a href="https://biblehub.com/matthew/6-21.htm" target="_blank">Matthew 6:21</a></i></blockquote>
<br />
<b>It's true, where you spend your money is an indication of what you value.</b> This is why Tithe (money) is the number one indicator of whether you Trust God (heart issue).<br />
<br />
What if we turned this verse around for a moment? What if we imagined that the treasure is your heart?<br />
<br />
<blockquote class="tr_bq">
<i>For where your heart is, there will be your deepest treasures.</i></blockquote>
<b>We then come to realize that the human heart is the real treasure.</b> It's not our money or belongings that matter in life, but the hearts we touch along the way.<br />
<br />
<b>As I pondered that this morning, I imagined the following story.</b> I hope you enjoy and take something away for yourself today.<br />
<br />
<div style="text-align: center;">
<b>*******</b></div>
<br />
<br />
The sun poured into his bedroom window casting shadows around his room. The birds chirping in the tree just outside provided a bittersweet contrast to his otherwise solemn mood.<br />
<br />
The house did not get many visitors, because Bob was a sheltered man. He lived far away, in the mountains. When he desired companions, he would leave his home and go into the city to spend time with his friends.<br />
<br />
Then came Kiwi. A unique name for a unique woman. She was among those friends he visited from time to time. But she was different. There was a burning energy and passion about her he could never quite fully understand. The way her wild hair bounced, her high pitched squeals of excitement at the smallest things, and her deep and penetrating mind all became more fascinating than he could stand.<br />
<br />
One day, while sitting alone at home, he realized just how much he really liked having her around. So he called Kiwi and invited her to his home (a rare occurrence). They talked until all hours of the day and night, she visited often. Things never got too physical (not that he didn't want them too), it was an emotional and intellectual connection they were building, even a spiritual one.<br />
<br />
The longer she stayed and explored the house the more she wanted to know about it. She brought gifts and spoke of desires. She told him how she could imagine herself living there with him and how wonderful it would be. She initiated pre-set date nights so the would carve out time for each other. She suggested going through pre-marital questions and discussing dreams and plans and logistics.<br />
<br />
The longer she stayed, the more at home he felt having her around. He resisted the idea of having her move in but she did such a fine job of convincing him that they were perfect for each other that the idea grew on him.<br />
<br />
Without really wanting to, he found himself attached to her. Which is why when she asked to see inside his Treasure Room, he hesitantly considered it. This is the room, in the very center of the house that he kept locked and secured. In here, Bob kept his most prized possessions. These were the collections of hopes and dreams that were most special to him.<br />
<br />
She said, "I love you", and his last resolve to keep everyone out of that room dissolved. He found he did love her too. So he unlocked that door and let her inside.<br />
<br />
At first, she marveled and awed at the way he kept it. Made fun of a few of his collection items. Then she danced and frolicked around the room, having so much fun that she didn't notice her arms knocked a few items off the shelves. By the time she was done, she'd broken quite a few of his favorite items.<br />
<br />
Then she walked out of the room without saying goodbye, walked out of the house, got in her car, and disappeared.&nbsp; He was left standing there, in a room full of broken treasures, picking up the pieces by himself.<br />
<br />
When a few weeks later she knocked at the door, she didn't seem to understand why he was grumpy and short. She walked in anyway and continued talking as though nothing had happened. She shared photos of her recent adventures and explained why she'd been Missing In Action (MIA) for so long. He tried to see things from her point of view and he decided to forgive her.<br />
<br />
Then he asked if she'd help clean up the room. He'd left all the broken pieces there because He couldn't bear to do it himself. She didn't seem to understand why he took it so seriously, but she agreed to try to help. However, while cleaning up she broke a few more items. Then her phone rang and she answered it. Without a word, she walked out the door, out of the house, got in her car, and left again. He was again left to pick up the pieces by himself.<br />
<br />
This time she was gone much longer. And wouldn't return his calls. When she finally came back again, she did so without any explanation this time. The only clue he was given about her whereabouts was that she'd been spending time with a new guy.<br />
<br />
Then she left again didn't visit as often. But she sent a few texts now and then.<br />
<br />
Finally, Bob had enough.<br />
<br />
He cleaned up the treasures as best as he could. Repaired a few. He held the one he'd been planning to show her, one that reminded him of her, in his hands. He made a decision that hurt but it had to be done. He took it outside and burned it. Leaving nothing but ash behind. Then he walked back inside and closed the door. This time, he sealed it, caulked the frame, and added extra security. From now on, nobody would be allowed in this room again until he was SURE that they would be safe.<br />
<br />
Now he sits at the window, light casting shadows against the doorway of that room. He did all the crying he can do, so he just sits by himself in the window, watching the birds chirp. Wondering how he let it all happen.<br />
<br />
Despite it all, he found that he was still grateful for Kiwi. He decided that she was still the greatest gift he'd received in a long time. She taught him how to enjoy life again. It's true that she was the source of one of his greatest hurts but she was also the source of some of his greatest pleasure... and that was worth it all.<br />
<br />
He takes the majority of the blame for letting her in, even if she did contribute by working so hard to convince him.<br />
<br />
She still visits from time to time, but she doesn't really understand what she did. She sees that he is hurting and that she helped cause it. But she doesn't really understand the pain she caused... and maybe she never will. Still... she brings him joy. So he lets her visit, just, not in that room.<br />
<br />
As he watches the shadows weave through the dancing trees, he realizes it's time he get back to his life. Maybe he'll go visit some of his friends in the city.<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"></div>
