---
title: 'What''s your story? Why are you here?'
date: '2019-12-17T06:35:00.0040000+00:00'
draft: false
categories:
  - 'Musings'
---

Dear Jesus,<br />
<br />
I sit here at stare at the blank page on my screen. Hesitant. Unsure about what to write. I find it acts as a strong metaphor for my life at the moment.<br />
<br />
One giant blank page. Thousands of potential things I "could" do; yet, none of them seem viable or worthy of pursuit.<br />
<br />
I find myself lacking a larger narrative for my life, a drive, a vision, a purpose.<br />
<br />
<ul>
<li>I know my calling is to those who are distressed, discouraged, and in debt; to train them into men and women who can be mighty for God, pulling down strongholds. These battles will take place in the hearts and minds of men.&nbsp;</li>
<li>I know I am a Storyteller. Writer/Scribe. Thinker, Sojourner. I am someone who works to discover the truth of a matter and bring it to the light. NO HIDING is my life's motto.&nbsp;</li>
<li>I know I am a father of two boys and they are my primary ministry and calling at this time. Yet, if I'm not headed anywhere, can I lead them?</li>
</ul>
<br />
<a href="https://www.entreleadership.com/blog/podcasts/donald-miller-core-values" target="_blank">Donald Miller</a> talked in the StoryBrand Podcast about creating a Family Mission Statement. He sold the idea that the mission statement doesn't have to be long term or life long. It can be a short-term mission statement. "We are a family that gets rid of our excess and sells it in a garage sale this spring..." and then you review it often and the whole family assesses what they've been doing to reach that target.<br />
<br />
So what is our vision? What is our family mission statement?<br />
<br />
Elements of a good mission statement:<br />
<br />
<ul>
<li><b>Identify the problem that we are on Earth to solve.</b></li>
<ul>
<li></li>
<li><i>"Most people suffer with..."</i></li>
<li>Be Specific. Don't be vague. They should immediately feel connected to the problem.&nbsp;</li>
</ul>
<li><b>How do we solve the problem?</b></li>
<ul>
<li></li>
<li><i>"We have a product/process that does..."</i></li>
<li>Make it feel like a new idea. Make it understandable. Make it brief.&nbsp;</li>
<li>This is the product, even if you sell a thousand things, make it one thing.&nbsp;</li>
</ul>
<li><b>What is their happy ending?</b></li>
<ul>
<li><i>"... so that they (happy ending)."</i></li>
<li>What is the outcome? How do they look when we're brought the solution to them?</li>
<li>This should be the controlling idea, everything drives to this.</li>
<li>Your product is not your business, their happy ended is the what you are selling. That's what you are in the business of doing.&nbsp;</li>
</ul>
</ul>
<br />
I don't have answers yet... just throwing this out there to ponder.<br />
<br />
Here's a quick possibility:<br />
<br />
<br />
<ul>
<li>Many people are walking through life "faking it till they make", lost in their own life story.</li>
</ul>
<ul>
<li>I write stories and articles that help people see past the lies and discover their true selves.</li>
</ul>
<ul>
<li>So they can live more authentically free to be who they were created to be.&nbsp;</li>
</ul>
<br />
Needs work... but it's a start.<br />
<br />
<br />
<b>What about you?&nbsp;</b><br />
<br />
<blockquote class="tr_bq">
<i>What problem are you on Earth to solve?</i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i>How do you solve it?</i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i>What is the happy ending others receive from your solution?</i></blockquote>
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label for="mce-EMAIL">Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" placeholder="email address" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
