---
title: 'What if you could make a 1% improvement to your life each day?'
date: '2019-07-10T21:07:00.0020000+00:00'
draft: false
---

<h3>
What if you could make a 1% improvement to your life each day?</h3>
<br />
This morning on my walk,<br />
<br />
God said: "I'm proud of you."<br />
<br />
I said: "I don't feel proud of myself..." and then started crying. "I'm still stuck in broken thinking cycles, rehearsing the past, scheming tomorrow in fear, and all the things that I've been stuck in for years."<br />
<br />
He said: "But unlike before, you are pressing into those feelings. You're sitting in them instead of running from them and numbing them with distractions. You're letting them process all the way through you and back out of you. You're pressing into "The Suck" and letting me walk you through the valley of the shadow of death. You're no longer camping in the valley, but walking through it each time, and coming out the other side."<br />
<br />
As I thought about it, I am spending less time there in The Suck each day. I can snap out faster, go there less often.<br />
<br />
<br />
<h4>
What if you could make a 1% improvement to your life each day?</h4>
<br />
This does NOT mean that if I walk a mile today I have to walk 1.1 miles tomorrow.<br />
<br />
This means that if I walked yesterday, I can choose to walk again today. And if I failed to walk yesterday, I can choose to walk today. And if I take enough of these small decisions, enough days in a row, they become habits. And small, incremental, 1% improvements will have a compounding effect so that I won't recognize myself a year from now.<br />
<br />
I can be sad that various outcomes I expected and planned this year went drastically sideways, and then rehearse what went wrong in a fear-based approach to prevent anything like that again. I can rehearse the speech I wanted to give because that distraction helps me avoid the pain of powerlessness.<br />
<br />
Or I can let those go and be present with God in THIS moment. If I'm following Him in THIS moment, he will direct my paths. Those things that were supposed to be in my life will stay/return, those things that were for a season but no longer will leave, and those things that are for upcoming seasons will arrive, and I'll be prepared for them because I was present in THIS moment.<br />
<br />
<h4>
My 1% decisions for now:</h4>
<br />
<ul>
<li>I'm going to keep walking every morning, and spending that time asking God what HE wants to talk about (instead of rehearsing what I already know).&nbsp;</li>
<li>I can keep my house clean.</li>
<li>I can write something every day.</li>
<li>I can look for one small decision each day. I don't have to do the whole task-list. But I can decide on one item, maybe more on a good day, and do that.&nbsp;</li>
</ul>
<div>
<br /></div>
<blockquote class="tr_bq">
<b>What will you do to achieve a 1% improvement in your day today?</b></blockquote>
<br />
<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span></div>
