---
title: 'The Bell Tolls For Thee... Perspectives on Pain and Suffering'
date: '2019-07-28T10:00:00.0000000+00:00'
draft: false
categories:
  - 'Selah'
---

<br />
<blockquote class="tr_bq">
<i><b>No man is an island</b>,&nbsp; entire of itself; every man is a piece of the continent, a part of the main; if a clod be washed away by the sea, Europe is the less, as well as if a promontory were, as well as if a manor of thy friend's or of thine own were;&nbsp; any man's death diminishes me, because I am involved in mankind, and <b>therefore never send to know for whom the bell tolls; it tolls for thee</b>. <a href="http://www.luminarium.org/sevenlit/donne/meditation17.php" target="_blank">John Donne Meditation 17</a></i></blockquote>
<div>
<br /></div>
<h4>
<b>We are All Connected&nbsp;</b></h4>
<div>
<br /></div>
<div>
Before cell phones, WiFi, Social Media, Email, Cars, or even Electricity... small rural towns had the Church Bell to communicate mass messages. The Bell Tolls to communicate something important has happened, and get our attention.</div>
<div>
<br /></div>
John Donne, a pastor-poet in 1635, was suffering from an illness he was sure would lead to his death. He wrote the above quote after hearing the Bell Toll for the passing of his neighbor. He wondered if he was so ill his family tolled it for him, thinking he was dead.<br />
<br />
When he says "it tolls for thee", Donne realized that the death of his neighbor might even help urge him on to continue to get right with God before his own passing. Even in that death, a good could come from it. The death of the neighbor was a "tolling" a "calling" an "urgency" for him as well, to get serious and ponder the most important things.<br />
<br />
We are all connected.<br />
<br />
We are all intricately linked to one another in this journey we call "life". Some people have had more opportunities to experience "good" and others more to experience "bad". But we are all connected.<br />
<br />
Philip Yancy, in <a href="https://amzn.to/2JZIcn2" target="_blank">Where is God when it Hurts?</a>, points out that the sufferers in the waiting rooms of the most desperate sections of the hospital are all evened by the event. Rich/Poor, Black/White, Man/Woman, all distinctions are gone. The suffering is the great equalizer. People who don't know each other and would never normally meet in other circumstances can become fellows in arms against the pending doom of the death of their loved one.<br />
<br />
<br />
<h4>
<b>Isolation Related Bitterness</b></h4>
<br />
So often, I am focused on MY PAIN. <i><b>I</b></i> have this pain, and it won't go away, and&nbsp;<i><b>I</b></i>&nbsp;want it to stop. Lately, that pain has been a pain of the heart... a bitterness for the loss of a dream that&nbsp;<i><b>I</b></i>&nbsp;can't get back.<br />
<br />
However, that pain is increased as&nbsp;<i><b>I</b></i>&nbsp;look more and more inward. What did&nbsp;<i><b>I</b></i>&nbsp;lose? What did&nbsp;<i><b>I</b></i>&nbsp;want? How dare the world do this to <b><i>ME</i></b>?<br />
<br />
As I begin to turn my focus away from myself, I see others' in pain. I see that a friend who wounded me, I also wounded in my hurtful retaliation. I see that she lived a life-long set of pains to this point, and maybe she deserves to be happy for a change, even if it caused me some pain and wasn't handled well by either of us.<br />
<br />
I also see where I had a hand to play in my own pain, in this instance.<br />
<br />
Physical Pain causes us to realize something needs healing, and tend to that, be gentle with it while it's healing.<br />
<br />
Emotional Pain can clue us into things within our own selves that require healing, adjustment, and change.<br />
<blockquote class="tr_bq">
<i>God, grant me the serinty to accept the things I cannot change (people), the courage to change the things I can (me) and the wisdom to know the difference (what can I change in me versus what I want others to change).&nbsp;</i></blockquote>
<br />
<h4>
<b>Turning Our Focus: Level Up!&nbsp;</b></h4>
<div>
<b><br /></b></div>
I can choose to focus on the things that life did me wrong or I can choose to focus on the things that I can do now, going forward. I can use this trial as a stepping stone or a weight to lift, that will propel me forward to a new level of growth in my life.<br />
<br />
I can Level Up!<br />
<br />
I've repeated the same patterns many times in life and ended up in the same places. I can use this to see those patterns and begin to affect changes that will ensure I won't be here ever again.<br />
<br />
I can then grow from these things, and use that growth to affect change in others' lives.<br />
<br />
I can go back into those (metaphorical and literal) hospital waiting rooms and be a source of comfort to those still there.<br />
<br />
<br />
<h4>
<b>Facing Two Truths</b></h4>
<br />
<b>1. This world has inherent goodness. </b>A non-biased walk on a cool sunny morning through the tall pine trees of North Idaho will assure you of this truth.<br />
<br />
<b>2. This world has inherent awfulness.</b> A trip to the ER, watching your wife's lifeless body not respond to the doctor's intervention, then being told that the doctor is ready to call time of death... then having to tell two young boys they'll never see their mom again... will show you that.<br />
<br />
<b>The world is not ALL bad.&nbsp;</b><br />
<b><br /></b>
<b>The world is not ALL good.&nbsp;</b><br />
<br />
In the very same hospital, often simultaneously... you find the death of a loved one and the birth of a baby. Even the birthing process involves pain before joy. The seasons of life bring both pain and pleasure. It's the combination of these that make up our lives.<br />
<br />
The sooner I allow bad stuff to just suck and stop trying to manipulate myself into pretending it didn't suck or changing the outcome, but just let it suck... the sooner I can move forward into another season when that season is through... the sooner I'll find myself in a new season that doesn't suck so much, and maybe even feels good. And I'll appreciate that season all the more because of the time I spent in The Suck.<br />
<br />
And maybe I'll offer a ray of hope to someone still stuck in The Suck...<br />
<br />
Selah,<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span></div>
