---
title: '4 Keys to understanding painful emotions and how to process them to facilitate healing.'
date: '2019-05-28T08:01:00.0000000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4099283259634052309'
blogger_filename: '/2019/05/4-keys-to-understanding-painful.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Freedom/Kairos'
---

<h3>When are Painful Emotions caused Real Trauma and when are they caused by a Lie</h3><br />When you feel hurt, sad, lonely, depressed, angry, fearful, infatuated, love, happiness, giddiness...<br /><br />These are emotions.<br /><br />Since "negative" or painful emotions are the ones that cause of the most problems, I will be focusing on those here.<br /><br />As I wrote about negative thoughts, filters, and triggers in <a href="http://www.topos.consulting/2019/05/a-letter-for-depression.html" target="_blank">An open letter for #Depression... Wanting to quit!</a> I was dealing with my own at the time.<br /><br />As I've now had some time to process through some of my own emotions, I want to talk specifically about "Emotions".<br /><br />I've come to realize there a few points that may help us deal with emotions more effectively:<br /><br />1. All emotions are valid<br />2. Some emotions are not caused by real trauma, lies.<br />3. Some emotions are caused by real trauma, truth.<br />4. The Compound Effect<br /><br /><h4>1. All emotions are valid</h4>Many times, we are afraid to admit we are feeling something painful. We don't want to face it or deal with it, so we bury, suppress, ignore, and dismiss the emotion. These tactics all fail to help us process through the emotion, thus it never really goes away.<br /><br />If we are ever going to process and heal, we must face the emotions head-on. To do this, we must realize they are valid.<br /><br />Regardless of the root of the emotion you are experiencing, the first thing we must do is validate your right to feel it.<br /><div><br /></div>You are experiencing "fear" or "sadness" or "anger"... it doesn't matter why. Those are real emotions and you are really experiencing them. You need to acknowledge they are there before we can process through.<br /><br />It doesn't matter if the thought that caused the emotion is a lie. Before we can get to that, we must acknowledge the emotions right to exist.<br /><br />Go ahead and say "I am feeling... " and fill in the blank with as many as you need to get it out.<br /><br />If you need help identifying your emotions, check out <a href="https://325424.com/2015/08/13/emotions-and-feelings-charts/" target="_blank">this article (here)</a>.<br /><br />Now that you have identified the emotions you are experiencing; and, validated their right to exist... we can begin to determine where they are coming from. What thoughts are associated with them. No emotion just "is".<br /><br />Go ahead and write down as many sentences, partial sentences, sentiments, or thoughts as you can about what you are feeling.<br /><br /><h4>2. Some emotions are not caused by real trauma.&nbsp;</h4><br />Once you have identified the emotions through words associated with them, it's time to find out where they are coming from. In some cases, you may be dealing with a LIE.<br /><br /><ul><li>Are you feeling the need to Justify Yourself and Blame Others?</li><li>Are you feeling the need to get Revenge or Lash Out to protect yourself?</li><li>Are you finding yourself saying anything in the way of extremes, using words like Always or Never, or Nobody or Everyone?</li><li>Do you find that you say things you regret later?</li></ul><br />These could be signals that these thoughts are directly or indirectly tied to lies. Once you identify the lie "I'm <i>never</i> going to be good enough, <i>nobody</i> wants me!" Then you can turn that over to your Daddy (God) and ask "Daddy, I acknowledge that as a lie. Tell me the Truth about that?"<br /><br />This isn't usually as simple as a one-time event. It's a process of continually bringing thoughts before Him and letting Him shine his light on them.<br /><br />Write down what you feel He's telling you. Keep a log or journal.<br /><br /><br /><h4>3. Some emotions are caused by real trauma.&nbsp;</h4>However... just because you are experiencing an emotion you don't like, does NOT mean that it is based on a lie.<br /><br />There are real hurts and pains caused by real trauma. It could be as simple as someone calling you out on a mistake and making fun of you for it; or, as life-altering as the death of a spouse or child or parent.<br /><br />These events are real. They cause real pain.<br /><br />While they are often used as openings for the devil to sow doubt and create a lie in you, the pain caused by these traumas is real, not a lie.<br /><br />It's okay to just say "I experienced a loss, it can't be fixed, and it really sucks."<br /><br />If you have a falling out with a friend or a spouse dies or an incident causes you to be the butt of everyone's joke... these are real and hurtful things.<br /><br />In these instances, you don't bring it to Daddy (God) because you need Him to uproot the lie, you bring these to Daddy (God) because he dealt with hurt and pain on this planet through Jesus and he understands. He will sit with you in that loss for a time and eventually lead you through a process of healing.<br /><br />Unlike lies, that can sometimes turn around instantly when you see the Truth, these are real traumas. They are wounds. They will (short of a miracle) take real time to heal and heal over time.<br /><br />In the early stages, you may need nothing more than to acknowledge this emotion and "sit in it". Be present in it. Don't ignore it or shove it aside. Just feel it. Where is it located in your body?<br /><br />Then acknowledge that this thing happened, that it sucks, and that you can't change that it happened. Depending on the situation, you may be able to fix it or you may not. Either way, it did happen (past tense) and that is important to acknowledge.<br /><br />Finally, bring that before Daddy and let Him talk to you about it and/or comfort you in it... and over time, heal it.<br /><br /><br /><h4>4. The Compound Effect</h4>Where things get a little trickier is that Real Trauma can also be an opening for the enemy to either sow a LIE into your heart or reinforce one that is already present.<br /><br />My wife died. That is real trauma. "She left me. Everyone always leaves me." is a lie... that the enemy successfully reinforced in me for a time in the early stages of my grief.<br /><br />So it may take some work, journaling, and the counsel of a friend/pastor/therapist to weed out and separate the Real Trauma from the Lie.<br /><br />The short version is to work through both of the processes above not just once, but continuously until you have resolved both issues.<br /><br />It is work. It is hard. It is worth it.<br /><br /><h4>Your Turn</h4>Go spend some time processing your emotions. Comment on this post on social media or message me and tell me if you'd like. Or share it with a friend.<br /><br />I hoped that helped.<br /><br /><br /><span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br /><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a>&nbsp;&amp; <a href="http://topos.consulting/">Topos.Consulting</a></span><br /><br /><span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br /><span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a>&nbsp;(Myers-Briggs Type): INFJ</span></div>