---
title: 'No Hiding Manifesto: How to pursue a more authentic relationship with God, others, and yourself.'
date: '2019-11-20T23:17:00.0000000+00:00'
draft: false
categories:
  - 'Musings'
---

If you're angry and bitter at God, failing in your relationships, and feeling defeated inside... You are not alone.<br />
<br />
There is a better way to live. Come follow me, and pursue a more authentic relationship with God, others, and yourself.<br />
<br />
<!-- Begin Mailchimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css"></link>
<style type="text/css">
 #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; width:100%;}
 /* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
    We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<style type="text/css">
 #mc-embedded-subscribe-form input[type=checkbox]{display: inline; width: auto;margin-right: 10px;}
 #mergeRow-gdpr {margin-top: 20px;}
 #mergeRow-gdpr fieldset label {font-weight: normal;}
 #mc-embedded-subscribe-form .mc_fieldset{border:none;min-height: 0px;padding-bottom:0px;}
</style>
