---
title: 'I am at my best when I... A tool to create daily habits that create victory one decision at a time.'
date: '2019-05-26T15:19:00.0000000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '9015642192471106508'
blogger_filename: '/2019/05/i-am-at-my-best-when-i-tool-to-create.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Templates'
---

<h3>Building a daily habit is a huge part of living successfully and also imperative when fighting depression.</h3><br />Creating a list of simple, practical things you can do each day to feed your inner spiritual/emotional/physical health and then posting it in places you can see will go a long way to helping you develop good healthy habits.<br /><br /><b>Keep in mind, these are intentions.&nbsp;</b><br /><br />If you don't do all of them, don't beat yourself up about it. Maybe today is a really hard day and all you can muster is the strength to read them, that's okay. Maybe you can just do one of them, that's better than nothing.<br /><br />Think of these as things you intend to do, not things you "must" do to "be a good person".<br /><br /><h4>Here’s some homework for you: fill in the blank with between 5-10 different statements.</h4><b>I am at my best when I ____________ (this should be a daily habit).</b><br /><br /><i><b>Note</b>: this can also include avoiding a negative habit, ideally one that in some way identifies as contributing to acting out, (some of your deepest sins can have triggers based in unhealthy habits or wrong thinking).</i><br /><br /><i><b>Note too</b>: you can change this list at any time. You may find something you thought of as important is really just some religious nonsense or an idea planted there in brokenness. Adapt the list to be things you ACTUALLY need to do, think, or say.</i><br /><br /><h4>Here's an example of mine:</h4>I am at my best when I ____________ (this should be a daily habit).<br /><br /><b>Daily</b><br /><ol><li>I am at my best when I daily get up early and walk at least 2,000 steps before the day starts.</li><li>I am at my best when I daily spend time reading the Bible and talking with Jesus before the day starts.</li><li>I am at my best when I daily speak out loud Identity Affirmations over myself.</li><li>I am at my best when I daily take my Isagenix, BP Meds, and Vitamin B Complex.</li><li>I am at my best when I daily engage in conversation with each sons for at least ten minutes.</li><li>I am at my best when I daily make my bed.</li><li>I am at my best when I daily brush my teeth.</li><li>I am at my best when I daily take thoughts of negativity, defeat, pessimism, and "woe is me" captive, replacing them with thoughts of victory, and identity in sonship. Asking God, "What do you see?"</li><li>I am at my best when I daily avoid Soda and Monsters and take my vitamins and drink at least 1 liter of water.</li><li>I am at my best when I&nbsp; daily...</li></ol><br /><b>Weekly</b><br /><b><br /></b>I am at my best when I weekly...<br /><ol><li>I am at my best when I weekly play a game with the boys, walk with them, or do some activity together.</li><li>I am at my best when I weekly&nbsp;get the three of us out of the house to do something non-electronic.</li><li>I am at my best when I weekly...</li></ol><br /><h4>Now it's your turn...</h4><br />Go write down the first five things that pop into your head.... edit as often as you like... post them somewhere you'll see them every day.<br /><br /><br /><br /><br /><span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br /><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a>&nbsp;&amp; <a href="http://topos.consulting/">Topos.Consulting</a></span><br /><br /><span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br /><span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a>&nbsp;(Myers-Briggs Type): INFJ</span></div>