---
title: 'When do you walk away?'
date: '2020-02-27T08:35:00.0010000+00:00'
draft: false
categories:
  - 'Musings'
---

<div>I’m pondering today, when does biblical advice say to reconcile when there’s been a wrong, when does it say to just overlook it, and when does the Bible say to walk away when one party will not try... This came up tonight at Bible study, it had me rethinking my experiences in 2019.</div><div><br></div><div>“Whoever covers an offense seeks love, but he who repeats a matter separates close friends.”</div><div>‭‭Proverbs‬ ‭17:9‬ ‭ESV‬‬</div><div>https://www.bible.com/59/pro.17.9.esv</div><div><br></div><div>“"If your brother sins against you, go and tell him his fault, between you and him alone. If he listens to you, you have gained your brother. But if he does not listen, take one or two others along with you, that every charge may be established by the evidence of two or three witnesses. If he refuses to listen to them, tell it to the church. And if he refuses to listen even to the church, let him be to you as a Gentile and a tax collector.”</div><div>‭‭Matthew‬ ‭18:15-17‬ ‭ESV‬‬</div><div>https://www.bible.com/59/mat.18.15-17.esv</div><div><br></div><div><br></div><div>I lost a meaningful friendship last year, 2019.&nbsp;</div><div><br></div><div>I tried, in a very broken way, to follow Matthew 18 and take my complaint to the other party, but they wouldn't hear me. I then made the mistake of trying harder and harder (repeating it, proverbs 17) and drove the wedge further.&nbsp;</div><div><br></div><div>As I look back, I can only see my side of the story, since I've asked the other party and they refused to talk about it. They won't admit to any wrong or talk about any wrong I committed.&nbsp;</div><div><br></div><div>The only path they offered was to pretend it didn't happen, which is a non starter for me.</div><div><br></div><div>Without addressing the issue, it remains unresolved. There's no path forward in any relationship (friend, romantic, family, etc) unless the things that caused a divide are resolved.&nbsp;</div><div><br></div><div>So I'm left to ponder it on my own, hope I'm seeing it right, and grow. I'd have grown more if I could see it from both sides, but I don't have that chance.</div><div><br></div><div>I'm 100% certain I did the right thing by trying to take the hurt to the person. According to Matthew 18, I should have then gotten a third party from the body of Christ involved instead of pressing harder by myself. A detached third party could have communicated without emotions.</div><div><br></div><div>I'm 100% certain I could have done it with more tact and waited until I could be more rational. So the WAY I addressed it created it's own wrong on my side. The emotions flared even hotter until it was impossible to communicate.&nbsp;</div><div><br></div><div>I'm 95% certain the other party didn't even try to hear me. I got a few responses justifying things, never apologizing, never trying to hear me, then a bunch of dismissal saying I was making a big deal out of nothing. No ownership of their part.</div><div><br></div><div>It went on so long, that other poor communication tactics on both sides drove the wedge further.&nbsp;</div><div><br></div><div>At this point, I can't see any path forward or any reason to try. I've forgiven them. But after the way I was treated both in the events that led up to the blow out and the way I was treated since, I'll most likely never be able to trust the other party again, so there's no reason to continue trying.&nbsp;</div><div><br></div><div>Two unhealthy people hurt each other, then made it worse. That's really the bottom line.</div><div><br></div><div>I believe I am healthier today, in measure.&nbsp;</div><div><br></div><div>If the other party did everything the same, the 2020 Darrell would have handled it differently. But maybe I needed that half year of hell to face the brokenness inside head on and deal with it. I don't know. I know the way I was treated wasn't acceptable, but, I could have handled it differently.</div><div><br></div><div>Unless God changes something, it's an impasse now.</div><div><br></div><div>My understanding of Matthew 18 is that I should now treat the other party as though they were outside the kingdom of God. Pray for them, evangelisticaly, but not attempt fellowship with them.</div><div><br></div><div>Maybe something like Paul's and Barnabas' "heated dispute" over John Mark applies here. We'll go our ways, but maybe God will do a work to restore the friendship down the road.&nbsp;</div><div><br></div><div>What I do know, is that you should wait to communicate until you can do so in love, without being defensive or reactionary. That would have helped, I believe.</div><div><br></div><div>I wish the friend great success in life. I hope the Heart of the Father is restored in us toward each other, someday.</div><div><br></div><div>In the meantime, how could you apply these two or three scriptures to your relationships?</div><div><br></div><div>#Selah&nbsp;</div>