---
title: 'Soul Mates don''t exist... Thank God!'
date: '2020-04-06T01:29:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5059238034063917527'
blogger_filename: '/2020/04/soul-mates-dont-exist-thank-god.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

<div><b>Question: This one comes in shades...&nbsp;</b></div><div><br /></div><div><div>What if I never find my Soul Mate?</div><div><br /></div><div>What if I had my Soul Mate and they died (or left)? Can I have two Soul Mates?</div><div><br /></div><div>What if I had my chance with my Soul Mate and I blew it, and now they're gone?</div><div><br /></div><div>How do I find my Soul Mate?</div><div><br /></div></div><div><br /></div><div><br /></div><div><b>Answer: Soul Mates are not discovered, they are created. And you can have more than one in a lifetime.&nbsp;</b></div><div><br /></div><div>I don't believe in "soul mates", in the traditional sense. It implies that if you meet the right person everything will be sunshine and roses. It also implies that if you marry someone and it turns into hell on earth that you "married the wrong one".&nbsp;</div><div><br /></div><div>Both of those ideas are antithetical to reality. You can marry the perfect match for you and still have issues that build on each other until they become a massive implosion (<i>I know because I did it</i>). If you have massive issues, it's often <b><i>not </i></b>because you married the wrong person but because one or both of you failed to put in the work of creating a good marriage.&nbsp;</div><div><br /></div><div>Marriage requires study, skill, perseverance, and the strength to do the right thing when it's inconvenient. It takes more training and purposeful effort than any career ever will.&nbsp;</div><div><br /></div><div>To be clear: You CAN absolutely marry the wrong person too. If you start with poor raw material, you will have an imperfect result. If you start with someone who is and was unwilling to grow, mature, develop, and work on self-care to become their best, then your marriage will have a broken leg from day one. If that's the case, you may have to get a lot of additional help to set boundaries until you two either (1) grow together, (2) find a status quo that works, or (3) you go separate ways.&nbsp;</div><div><br /></div><div>But that scenario less likely than what usually happens. Usually, two good humans who care for each other fail to do the work to become one. Hurt and insecurity blend until both act poorly toward the other.&nbsp;</div><div><br /></div><div><ul style="text-align: left;"><li><b>BUILDING A Marriage: I believe that two people decide to build something.&nbsp;</b></li></ul></div><div><br /></div><div>Even if God himself tells you to marry someone, it's no guarantee that you're "soul mates" status means anything.</div><div><br /></div><div>God literally told me to marry my late-wife, Flavia. Even with that direct command, we had a struggling marriage for much of it because we didn't know how to build a good one. Eventually, we learned how, we had some amazing times too, then she passed.</div><div><br /></div><div>After she passed away, I was praying about how it all went so wrong. How did God tell me to marry her, and things still didn't go well for many years?</div><div><br /></div><div>He said: "I did not tell you to marry her. I told you she was your wife".&nbsp;</div><div><br /></div><div>As I prayed about that Word, I had an epiphany. That word "...she is your wife", was not the be-all and end-all of the matter. It was my seed. Just as you are not given a harvest of Pumpkins to sell at the market with a single Pumpkin seed, I was not given an entire marriage with that Word. I was given a seed.&nbsp;</div><div><br /></div><div><b>Do something with the seed!</b></div><div><br /></div><div>Our job, then, was to take that seed and use it. Cultivate the soil, remove rocks, add nutrients. Plant the seed. Get a harvest. Plant more seeds. Grow this into a fully functioning Pumpkin Patch. Learn how to do it, get books, go to seminars, get help from people who have done it right.&nbsp;</div><div><br /></div><div>So what about the next round? Now that I've lost the woman I was told to marry, can I marry again?&nbsp;</div><div><br /></div><div>Just as I built something amazing with her when I learned how I will build something amazing with my next wife.</div><div><br /></div><div>You chose to build it together.&nbsp;</div><div><br /></div><div>Destiny gives you a seed.</div><div><br /></div><div>You either tend the garden or let the weeds overtake everything.&nbsp;</div><div><br /></div><div><b>"He who FINDS a wife, finds a good thing."</b></div><div><br /></div><div>It's my job to keep my eyes open, initiate contact when opportunities arise, and be an active participant in finding her.&nbsp;</div><div><br /></div><div>It's God's job to bring her within my field of vision when the time is right and I've learned the lessons and reached a place in life where meeting her would be appropriate.&nbsp;</div><div><br /></div><div>I can't control when I'll meet the next woman to plant that seed. But I can make opportunities to meet her, and I can tend the garden with her when she arrives. Together, we can build a marriage... and become Soul Mates.&nbsp;</div><div><br /></div><div>#Selah</div><div><br /></div><div><br /></div>