---
title: 'Radical Authenticity. Healthy Theology. Fulfilling Relationships.'
date: '2020-02-24T06:05:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1009725908711439044'
blogger_filename: '/2020/02/radical-authenticity-healthy-theology.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

<div>Are we being real with each other?</div><div><br></div><div>"How are you?"</div><div><br></div><div>"I'm well."</div><div><br></div><div>We move on with a smile.&nbsp;</div><div><br></div><div>But...</div><div><br></div><div>Is that real well, or fake Christian-eeze well. But inside you're actually dying?<br></div><div><br></div><div>It's always amazing to me how we say "Oh, I'm just blessed brother!" Then go cry in the car.&nbsp;</div><div><br></div><div>So I have begun pressing for the real truth.<br></div><div><br></div><div>The Church should be the one place where people feel the MOST safe to take the covers off... But I usually find that safety anywhere but the church walls.&nbsp;</div><div><br></div><div>This is one reason people find counterfeit safety and community outside the church, just to find themselves in a new type of bondage.</div><div><br></div><div>So I've decided to change that, one person at a time.<br></div><div><br></div><div>In our efforts to be Holy, we often fail to be full of Grace, Mercy, and Compassion.&nbsp;</div><div><br></div><div>As a pastor's kid, I felt that deeply. Now that I'm free, I am feeling the need to bring that healing back. Not the mission I wanted, not a sexy message, but a healthy and needed one.<br></div><div><br></div><div>Radical Authenticity. Healthy Theology. Fulfilling Relationships.</div><div><br></div><div>I guess that's my message.</div><div><br></div><div>#Selah&nbsp;</div><div><br></div><div><br></div><div><br></div><div><br></div>