---
title: 'An Aspirational Vision: The Next Revival 2020 and Beyond'
date: '2020-09-26T19:33:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5665945291585697646'
blogger_filename: '/2020/09/an-aspirational-vision-next-revival.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

<h3 style="text-align: left;">Aspirational Dream:&nbsp;</h3><div><br /></div><div>On Thursday 09/24/2020, at approximately 1:28 PM PST, I woke from a nap with these images and thoughts swirling around in my head. I am not so bold as to say they are prophetic or that they will happen this exact way. I see them more as an Aspirational Vision. Something we could each aspire to see happen in our own lives and communities if we begin to surrender to the work of the Holy Spirit in our generation. I could even see him doing this type of thing simultaneously all over the world so that there is no one epicenter? I felt led to share this to inspire you to begin to dream for your community.</div><div>&nbsp;</div><div><br /></div><div style="text-align: center;">***</div><div style="text-align: center;"><br /></div><h3 style="text-align: left;">An Aspirational Vision: The Next Revival 2020 and Beyond:</h3><div>&nbsp;</div><div>In 2024, a small group of believers had been gathering for some time in a manufactured home on a half-acre in North Pole, Idaho, near Coeur d'Alene.</div><div>&nbsp;</div><div>An outpouring struck that group unlike any that came before. The Holy Spirit moved in them with all the signs of the New Testament church. While no one sign was more present than another, they were all present: Signs included miracles, healing, tongues (both known and unknown), interpretation of tongues, words of knowledge to answer questions and words of wisdom to solve problems, Prophecy, and discerning of spirits all poured out in huge waves. Even in the relatively quiet hammock of North Idaho, demons presented themselves and were cast out by anyone standing by without waiting for "leaders" to direct them.</div><div>&nbsp;</div><div>Messages were taught and songs were sung, as the Spirit gave utterance, but no formal church services were ever announced. The meetings were only ever held as weekday prayer meetings only throughout the revival, allowing all the churches in the region to participate equally.</div><div>&nbsp;</div><div>At its apex, 10,000s were directly affected and present in these meetings. Millions were affected by people who left the meetings and brought the revival with them. The results were such that the small property wasn't big enough to contain the meetings. A larger piece of land was purchased, which eventually became their headquarters. People left this revival&nbsp; and went back into their own towns carrying the revival with them.</div><div>&nbsp;</div><div>All the previous signs of other revival were present. Gifts of the spirit. Unity between races, sexes, and even sexual orientations. Love was a hallmark sign. The fruit of the spirit was evident.</div><div>&nbsp;</div><div>As the movement matured, semi-formal parachurch organizations were created to help give unity to the message and provide a resource to other local churches for the duplication of its intent (but not style) in other areas.</div><div>&nbsp;</div><h4 style="text-align: left;">Two characteristics set this movement apart from previous movements.</h4><div>&nbsp;</div><div>1. No formal Sunday church services were started by the original group. The intent remained, throughout the revival, to bring the community together and revive life within the existing churches. The group never formally started their own.</div><div>&nbsp;</div><div>2. They remained home-prayer based extensions of the churches they affected. Although some new churches were planted around the world as a side effect of fresh evangelism and growth, no new churches or denominations were formed to represent this movement as being separated from its founding church. Although (as always happens) some leaders recoiled from the movement, most Pastors and Leaders from churches affected became leaders and participants of the meetings, rather than rejectors of them.</div><div>&nbsp;</div><div>Those hosting the prayer meetings also recognized that the point of any revival or movement of the Holy Spirit is to bring a new fresh perspective and life to HIS people. As such, once the wave had done its job of spreading this new phenomenon around the world, the intensity of the move crests and fresh waves come forward, and they were pleased with that arch. Thus, as predicted by the hosts, the flocking of millions to North Idaho lasted approximately 10 years, and the revival officially ended in 2034.</div><div>&nbsp;</div><div>However, today, some 50 years later, a consistent remnant of approximately 200-500 meet on a weekly basis in homes throughout the North Idaho region, including visitors.</div><div>&nbsp;</div><div>Most of the founding hosts are still faithful members of their original home churches, except for those who have passed on or gone to other works.</div><div>&nbsp;</div><div>The Kingdom of God, LLC (KOGLLC), a parachurch organization built to support existing churches. The KOGLLC still produces free content from and for churches around the globe, holds regular prayer meetings on its 100-acre campus, hosts leadership training, hosts a spirit-filled counseling center, and homeless outreach, among other activities. All of the activities are dedicated to helping support local churches; therefore, no Sunday church services are ever held on campus. Rather, any of the students or clients living on-site as part of the recovery or school programs, are bussed to any of the local churches they would like to attend.</div><div><br /></div><div style="text-align: center;">***</div><div>&nbsp;</div><div>Who knows… but it's got a nice ring to it, doesn't it?</div><div>&nbsp;</div><div><br /></div>
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
