---
title: 'Cognitive dissonance... Do you believe yourself?'
date: '2020-04-08T14:14:00.0010000+00:00'
draft: false
categories:
  - 'Musings'
---

<div><b>Do you believe yourself?</b></div><div><br></div><div>Judas protested the breaking of expensive perfume to wash Jesus's feet, by a grateful woman who Jesus had not only saved but he'd brought her brother back from the dead.&nbsp;</div><div><br></div><div>Judas's spoken "reason" for this protest was to give the money to the poor.</div><div><br></div><div>Judas's actual reason was because he was stealing money from the money bag and wanted that huge payday.&nbsp;</div><div><br></div><div>How many people cry loudly for the government to swoop in and care for the "poor" but do nothing for them directly? What's the real motive? To feel like they're righteous because they're on the "right side of history"?</div><div><br></div><div>How many times to I say something is harmful, like Pornography, then go do it myself hours later with excuses about just one more time?</div><div><br></div><div>We all have strange motives. They're not simple. Both could be true. But are we living a consistent, congruent, life?&nbsp;</div><div><br></div><div>Are the things we say to others, just as real to us at home, in bed, as we ponder the day drifting off to sleep?</div><div><br></div><div>What if we made more congruent choices in both words and actions?</div><div><br></div><div>Thou doth <a href="https://en.m.wikipedia.org/wiki/The_lady_doth_protest_too_much,_methinks">protest too much</a>!</div><div><br></div><div>#Selah</div><div><br></div>