---
title: 'Man. Moon. Duck Suit. God''s Ways.'
date: '2020-06-17T13:21:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8374184395925829780'
blogger_filename: '/2020/06/man-moon-duck-suit-gods-ways.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Short Story'
---

The black oil of night crept over the sidewalk making it hard to see where he was going. Not that Manny could see much through the mask of his Big Yellow Ducks mascot outfit. The team left without him, taking his change of clothes with them.&nbsp;<div><br></div><div>Manny stumbled down a dark alley, his guitar slung over his fake feathery yellow back. The street lights became puddles to reach one after another, accenting the voids between.</div><div><br></div><div>Finally, he reached a corner, he decided he'd had enough. He tried music and failed. He tried art and failed. And now he was reduced to wearing a mascot outfit for pennies just to make ends meet. The anger boiled inside until he couldn't take it anymore. He grabbed the guitar and smashed it over and over on the curb. Just as he was starting to break it, a white odd looking car passed by, splashing water onto him from the street. "Great, thanks!"</div><div><br></div><div>Cocking his big fake head, he looked up into the sky, and the Man in Moon, "Why give me a desire to be something but never let me be it?" Then he stumbled home, tossed his outfit to the bedroom floor and went to sleep.</div><div><br></div><div>A week later, he woke up on a Monday morning to 67 missed calls from his friend Conrad. "Dude, wake up! You're famous!"</div><div><br></div><div>There on his phone, was a picture of him dressed as a big yellow duck, smashing a guitar on the corner. Video from the corner store security footage, showing the events in time, had been circulating the internet and recieved over 2 Million Views.&nbsp;</div><div><br></div><div>At the school, he was fired for his making the mascot of their proud institution look bad, but he didn't even care, <i>totally worth it</i>, he thought. As he was leaving, a call came in from an agent looking to represent him, claiming he had an interview with Good Morning America if he was interested.</div><div><br></div><div>***</div><div><br></div><div>Turning from the screen, "... And that kids, is how I got my start in movies, right there, on a street corner. So never give up. God has funny ways of bringing about your calling."&nbsp;</div><div><br></div><div>As Manny packed up his gear, to end his presentation, the moonlight through the window showed the wrinkles on his hand growing darker and more defined. He'd had a really good run.&nbsp;</div><div><br></div><div>"Thanks Man in the Moon, couldn't have done it without you."</div>