---
title: 'He does not point out her sin and condemn her... he focuses on Grace.'
date: '2020-02-18T15:30:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1739059440446723524'
blogger_filename: '/2020/02/he-does-not-point-out-her-sin-and.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

Jesus was presented with someone who sinned (Woman caught in adultery, btw, where's the man?)...<br />
<br />
He does not point out her sin and condemn her.<br />
<br />
He does not point out her sin and condemn her.<br />
<br />
He does not point out her sin and condemn her.<br />
<br />
He does not point out her sin and condemn her.<br />
<br />
He does not point out her sin and condemn her.<br />
<br />
He does not point out her sin and condemn her.<br />
<br />
I want to draw that point home, for many of us (myself most of all) have the heart of a Pharisee or the Elder Brother (story of Prodigal Son). We focus one how we are not caught up in all that and therefore nobody else should be either. But if we stop to acknowledge that we still struggle with sins, maybe just different ones, we can re-learn to have compassion.<br />
<br />
Judgment was taken into the body of Jesus on the Cross. There is no judgment left, only a pleading call to Grace and to accept the finished work he already completed.<br />
<br />
We get so heated in our debates, vilifying the "other" side. While it is absolutely true that there are two kingdom's at work on this planet and they are at war with each other... you might find that kingdom of darkness has been hiding in your camp, not just the "other" camp.<br />
<br />
The woman at work with a poster of someone you think of as "enemy" might actually be a woman God really really loves and he could use you to reach her... or you can vilify her and walk around in judgment, inviting all that comes with that smug attitude.<br />
<br />
What does Jesus do, when presented with sin and asked for a verdict?<br />
<br />
"You who have no sin, cast the first stone".<br />
<br />
He didn't justify what she did by calling it "not sin". It was sin. Too often we swing the other way and try to say that the way someone is living is good or healthy, it's just an alternative lifestyle. No. It's sin.<br />
<br />
But...<br />
<br />
Jesus acknowledged her sin but focused on the verdict.<br />
<br />
"Who condemns you?" "Nobody"<br />
<br />
Then he makes a statement that acknowledges her sin, tells her to stop it, and yet carries no judgment or harshness or condemning attitude in it at all.<br />
<br />
"Neither do I condemn you, go and sin no more".<br />
<br />
We can, prayerfully, when faced with such a topic. "Is X a sin?" Focus too on the verdict and not the sin. We can say that we are all broken, and in need of change, and focus on the source of that change, Jesus.<br />
<br />
#Selah<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label for="mce-EMAIL">Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" placeholder="email address" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
