---
title: 'How does The Church handle its LGBTQIA members?  A Sociopolitical Research Paper.'
date: '2020-11-16T07:39:00.0020000+00:00'
draft: false
categories:
  - 'Class Assignment'
  - 'Mental Health'
---

<h3 style="text-align: left;">Answer: Historically we get an F, but we're in remedial class now so we're improving as a whole.&nbsp;</h3><div><br /></div><div><br /></div><div><i>*Disclaimer: I could not possibly do justice to the nuance of this topic in a 3-5 page double-spaced 12-point font paper. I was forced to choose a direction, and I ran with it. Given the time and space, I probably will write on this topic more in the future. I intend to give it the nuance and time each issue deserves. Therefore, consider this a primer for future discussions. I also reserve the right to change as I grow, this is how I am seeing it today.&nbsp;</i></div><div><br /></div><div><br /></div><div><br /></div><div style="text-align: center;">*******************</div><p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 16pt;"><br /></span></p><p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 16pt;">How does The
Church handle its LGBTQIA members?</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 16.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span class="MsoBookTitle"><span style="font-size: 16.0pt; line-height: 107%;">Sociopolitical
Research Paper<o:p></o:p></span></span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Darrell
Wolfe<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Biblical
Counseling, The King’s University<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Counseling
in the Church (BIBC 3304)<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Glenna
Massey<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">November
15, 2020<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">&nbsp;</span></p>

<span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;"><br clear="all" style="mso-special-character: line-break; page-break-before: always;" />
</span>

<p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;;">&nbsp;</span></p>

<h1>Abstract<o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">The
following will be a short evaluation of how the Church has and should handle
its LGBTQIA Members. We will review the impacts of the division with and in the
Church, the role of the Church, and the response of the Church. Lastly, we will
look at how a Biblical story reimagined could provide the answer.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; margin-left: .5in; text-indent: .5in;"><i><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Keywords:
LGBTQIA, Gay, Lesbian, Gay Marriage, Gays and Church<o:p></o:p></span></i></p>

<h1 style="line-height: 200%;">The Impact of being gay in Church<o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; United Methodist Pastor Jimmy Creech wrote a book called
Adam’s Gift, in which he speaks about the first time he was introduced to Adam,
a man who was both gay and serving in the church (circa 1984) </span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;jB8FQE6n&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;(Creech,
2011)&quot;,&quot;plainCitation&quot;:&quot;(Creech,
2011)&quot;,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:356,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/K7G2N65K&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/K7G2N65K&quot;],&quot;itemData&quot;:{&quot;id&quot;:356,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;Jimmy
Creech, a United Methodist pastor in North Carolina, was visited one morning in
1984 by Adam, a longtime parishioner whom he liked and respected. Adam said
that he was gay, and that he was leaving The United Methodist Church, which had
just pronounced that “self-avowed practicing homosexuals” could not be
ordained. He would not be part of a community that excluded him. Creech found
himself instinctively supporting Adam, telling him that he was sure that God
loved and accepted him as he was. Adam’s Gift is Creech’s inspiring
first-person account of how that conversation transformed his life and
ministry.Adam’s visit prompted Creech to re-evaluate his belief that
homosexuality was a sin, and to research the scriptural basis for the church’s
position. He determined that the church was mistaken, that scriptural
translations and interpretations had been botched and dangerously distorted. As
a Christian, Creech came to believe that discriminating against lesbian, gay,
bisexual, and transgender people was morally wrong. This understanding
compelled him to perform same-gender commitment ceremonies, which conflicted
with church directives. Creech was tried twice by The United Methodist Church,
and, after the second trial, his ordination credentials were revoked. Adam’s
Gift is a moving story and an important chapter in the unfinished struggle for
lesbian, gay, bisexual, and transgender civil and human
rights.&quot;,&quot;ISBN&quot;:&quot;978-0-8223-4885-6&quot;,&quot;language&quot;:&quot;en&quot;,&quot;number-of-pages&quot;:&quot;390&quot;,&quot;publisher&quot;:&quot;Duke
University Press&quot;,&quot;source&quot;:&quot;Google
Books&quot;,&quot;title&quot;:&quot;Adam's Gift: A Memoir of a Pastor's Calling
to Defy the Church's Persecution of Lesbians and
Gays&quot;,&quot;title-short&quot;:&quot;Adam's Gift&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Creech&quot;,&quot;given&quot;:&quot;Jimmy&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2011&quot;,4,4]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">(Creech, 2011)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-end'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">. Adam had same-sex
attraction from an early age. He tried to ignore it and even lived as a
straight man for a time. He lived and served God faithfully as a member of the
United Methodists. Nobody at the church knew he was gay. His experience with
“The Church” was that he was hearing about God’s unconditional love from one
ear and about how God hates gays and condemns them to hell from the other ear.
He could not reconcile these messages as he struggled to come to terms with his
sexuality. Feeling shamed and guilty for simply being who he was, he even
attempted suicide. All too often this has been the experience of the Lesbian,
Gay, Bisexual, Transgender, Queer, Intersex, and Asexual (LGBTQIA) community
both inside the churches as well as interacting with those claiming to
represent the church in the community at large. While attending white parades
(circa 1996-1998) in my hometown of Palm Springs, California, I saw someone
holding a sign that said, “God hates gays”. <o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">Even
as many churches are getting better at their response, the larger cultural
debate rages. Legislatures are gridlocked between the defense of religious
liberties and civil rights, often resulting in Supreme Court decisions to
determine where the lines are drawn in the US Constitution. The 2020 Bostock
decision was the latest iteration of that battle </span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;4mbYsrzv&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;(Bennett,
2020)&quot;,&quot;plainCitation&quot;:&quot;(Bennett, 2020)&quot;,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:354,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/77AFTEUU&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/77AFTEUU&quot;],&quot;itemData&quot;:{&quot;id&quot;:354,&quot;type&quot;:&quot;article-newspaper&quot;,&quot;abstract&quot;:&quot;Social
conservatives liked Neil Gorsuch before they didn’t. Maybe they were right the
first time.&quot;,&quot;container-title&quot;:&quot;Christianity
Today&quot;,&quot;title&quot;:&quot;LGBT Rights Ruling Isn’t the Beginning of
the End for Religious
Liberty&quot;,&quot;URL&quot;:&quot;https://www.christianitytoday.com/ct/2020/june-web-only/bostock-gorsuch-supreme-court-ruling-religious-liberty.html&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Bennett&quot;,&quot;given&quot;:&quot;Daniel&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,13]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,6,17]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">(Bennett, 2020)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-end'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">. &nbsp;Faith-Based Adoption agencies are finding
themselves in court over adoption to gay couples </span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;OqNLE3u0&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;(Shellnutt,
2019)&quot;,&quot;plainCitation&quot;:&quot;(Shellnutt, 2019)&quot;,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:350,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/TKAEUWVW&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/TKAEUWVW&quot;],&quot;itemData&quot;:{&quot;id&quot;:350,&quot;type&quot;:&quot;article-newspaper&quot;,&quot;abstract&quot;:&quot;After
ACLU lawsuit, Bethany Christian Services shifts foster care placement policy to
comply with Michigan’s new
requirements.&quot;,&quot;container-title&quot;:&quot;Christianity
Today&quot;,&quot;language&quot;:&quot;en&quot;,&quot;title&quot;:&quot;America’s
Largest Christian Adoption Agency Lets LGBT Couples Foster in 1 of 35
States&quot;,&quot;URL&quot;:&quot;https://www.christianitytoday.com/news/2019/april/bethany-christian-services-michigan-foster-lgbt-couples.html&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Shellnutt&quot;,&quot;given&quot;:&quot;Kate&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,13]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2019&quot;,4,25]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">(Shellnutt, 2019)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-end'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">. Youth Pastors will find
that the up and coming youth are more likely than ever to either identify as
LGBTQIA or be sympathetic to their plight </span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;Wo9DqjIT&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;(Shellnutt,
2018)&quot;,&quot;plainCitation&quot;:&quot;(Shellnutt,
2018)&quot;,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:353,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/SAFIJWZ8&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/SAFIJWZ8&quot;],&quot;itemData&quot;:{&quot;id&quot;:353,&quot;type&quot;:&quot;article-newspaper&quot;,&quot;abstract&quot;:&quot;Barna
findings on Generation Z pose new challenges for the
church.&quot;,&quot;container-title&quot;:&quot;Christianity
Today&quot;,&quot;title&quot;:&quot;Get Ready, Youth Group Leaders: Teens Twice
as Likely to Identity of Atheist of
LGBT&quot;,&quot;URL&quot;:&quot;https://www.christianitytoday.com/news/2018/january/youth-group-leaders-generation-z-atheist-lgbt-teens-barna.html&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Shellnutt&quot;,&quot;given&quot;:&quot;Kate&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,13]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2018&quot;,1,23]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">(Shellnutt, 2018)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-end'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">. <o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; To make matters more complicated, if a gay or lesbian
couple begins to attend church they are faced with a new dilemma. If the church
teaches them that their marriage is not authorized, do they encourage the
couple to break-up and divide the children into two homes? One United Methodist
pastor claimed that singling out the LGBTQIA community was a violation of the
church's charter to “do no harm” </span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;HYH9GZ06&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;(Steele,
2019)&quot;,&quot;plainCitation&quot;:&quot;(Steele, 2019)&quot;,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:348,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/67Q4QWCQ&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/67Q4QWCQ&quot;],&quot;itemData&quot;:{&quot;id&quot;:348,&quot;type&quot;:&quot;article-newspaper&quot;,&quot;abstract&quot;:&quot;(UPDATED)
Traditional Plan survives legal review, but could still set the UMC on path to
division over gay marriage and clergy as Judicial Council also approves exit
plan for dissenting
churches.&quot;,&quot;container-title&quot;:&quot;Christianity
Today&quot;,&quot;language&quot;:&quot;en&quot;,&quot;title&quot;:&quot;United
Methodist Court Keeps Core of New LGBT Legislation&quot;,&quot;URL&quot;:&quot;https://www.christianitytoday.com/news/2019/april/united-methodists-judicial-review-umc-traditional-plan-lgbt.html&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Steele&quot;,&quot;given&quot;:&quot;Jeremy&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,13]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2019&quot;,4,26]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">(Steele, 2019)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-end'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">.<o:p></o:p></span></p>

<h1 style="line-height: 200%;">The Role of the Church<o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">The
church faces a two-pronged battle. On one hand, the role of the church is to
love God, and love our neighbor as ourselves (Matthew 22:36-40)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-begin'></span> ADDIN ZOTERO_ITEM CSL_CITATION {&quot;citationID&quot;:&quot;f0IgatCJ&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;({\\i{}Key
Word Study Bible NKJV}, n.d.)&quot;,&quot;plainCitation&quot;:&quot;(Key Word
Study Bible NKJV, n.d.)&quot;,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:225,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/ANBA8KS5&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/ANBA8KS5&quot;],&quot;itemData&quot;:{&quot;id&quot;:225,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;There
are times when a Greek or Hebrew word has a distinct meaning that seriously affects
the proper interpretation of Scripture. Unless you are familiar with these
languages, you will not be able to determine what word in the original text was
used or the differences between these words-until now.\n\nThe Hebrew-Greek Key
Word Study Bible identifies the key words of the original languages and
presents clear, precise explanations of their meaning and usage. Those who love
God's Word will treasure this Bible, for it contains a whole library of
biblical helps within its
covers.&quot;,&quot;event-place&quot;:&quot;Chattanooga,
TN&quot;,&quot;ISBN&quot;:&quot;978-0-89957-868-2&quot;,&quot;publisher&quot;:&quot;AMG
Publishers&quot;,&quot;publisher-place&quot;:&quot;Chattanooga,
TN&quot;,&quot;title&quot;:&quot;The Hebrew-Greek Key Word Study BIBLE: Key
Insights Into God's Word. New King James
(NKJV)&quot;,&quot;title-short&quot;:&quot;Key Word Study Bible NKJV&quot;}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">(<i>Key
Word Study Bible NKJV</i>, n.d.)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-end'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">. On the other hand, the
role of the church is to speak the truth in love (Ephesians 4:15). For many
sincere men and women who struggle with same-sex attraction (orientation),
their options are churches that either accept the LGBTQIA positions on all
fronts without challenge (Ex: Pro-Gay Marriage) or challenge the positions
while rejecting the persons (Ex: Anti-Gay Rhetoric “God hates gays”). Both the
Church of the Brethren and the United Methodist Church have experienced splits
over the topic of how to respond to LGBTQIA issues; such as gay marriage </span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;vRK1pZMI&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;(Silliman,
2020; Steele, 2019)&quot;,&quot;plainCitation&quot;:&quot;(Silliman, 2020;
Steele,
2019)&quot;,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:351,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/548D6XH2&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/548D6XH2&quot;],&quot;itemData&quot;:{&quot;id&quot;:351,&quot;type&quot;:&quot;article-newspaper&quot;,&quot;abstract&quot;:&quot;Departing
congregations want stricter enforcement of official
positions.&quot;,&quot;container-title&quot;:&quot;Christianity
Today&quot;,&quot;title&quot;:&quot;Brethren Against Brethren: LGBT Fight
Divides Peace
Church.&quot;,&quot;URL&quot;:&quot;https://www.christianitytoday.com/news/2020/august/church-brethren-southeastern-district-divide-covenant-lgbt.html&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Silliman&quot;,&quot;given&quot;:&quot;Daniel&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,13]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,8,3]]}}},{&quot;id&quot;:348,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/67Q4QWCQ&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/67Q4QWCQ&quot;],&quot;itemData&quot;:{&quot;id&quot;:348,&quot;type&quot;:&quot;article-newspaper&quot;,&quot;abstract&quot;:&quot;(UPDATED)
Traditional Plan survives legal review, but could still set the UMC on path to
division over gay marriage and clergy as Judicial Council also approves exit
plan for dissenting
churches.&quot;,&quot;container-title&quot;:&quot;Christianity
Today&quot;,&quot;language&quot;:&quot;en&quot;,&quot;title&quot;:&quot;United
Methodist Court Keeps Core of New LGBT Legislation&quot;,&quot;URL&quot;:&quot;https://www.christianitytoday.com/news/2019/april/united-methodists-judicial-review-umc-traditional-plan-lgbt.html&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Steele&quot;,&quot;given&quot;:&quot;Jeremy&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,13]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2019&quot;,4,26]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">(Silliman, 2020; Steele, 2019)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-end'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">. <o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">Jay
Skylar, in an article analyzing the relevance of the biblical prohibitions of
homosexuality, frames the arguments for a biblical acceptance of homosexuality
as unlikely to be logically consistent with a Christian Worldview </span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;ej2FAA4j&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;(Skylar,
Jay, 2018)&quot;,&quot;plainCitation&quot;:&quot;(Skylar, Jay,
2018)&quot;,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:373,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/LEFCHAN7&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/LEFCHAN7&quot;],&quot;itemData&quot;:{&quot;id&quot;:373,&quot;type&quot;:&quot;article-journal&quot;,&quot;container-title&quot;:&quot;Bulletin
for Biblical
Research&quot;,&quot;DOI&quot;:&quot;10.5325/bullbiblrese.28.2.0165&quot;,&quot;ISSN&quot;:&quot;1065223X&quot;,&quot;issue&quot;:&quot;2&quot;,&quot;journalAbbreviation&quot;:&quot;Bulletin
for Biblical Research&quot;,&quot;page&quot;:&quot;165&quot;,&quot;source&quot;:&quot;DOI.org
(Crossref)&quot;,&quot;title&quot;:&quot;The Prohibitions against Homosexual
Sex in Leviticus 18:22 and 20:13: Are They Relevant
Today?&quot;,&quot;title-short&quot;:&quot;The Prohibitions against Homosexual
Sex in Leviticus
18&quot;,&quot;volume&quot;:&quot;28&quot;,&quot;author&quot;:[{&quot;literal&quot;:&quot;Skylar,
Jay&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2018&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">(Skylar, Jay, 2018)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-end'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">. Yet, he demonstrates an
understanding that Christians hold a dual responsibility to Truth and Love. <o:p></o:p></span></p>

<h1 style="line-height: 200%;">The Response of the Church<o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">The
response of the church is to love God, love folks, and speak the truth in love
so that we can bring freedom into the lives of all who accept that truth (Matthew
22:36-40; Ephesians 4:15; John 8:32). <o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">If
we genuinely love God, we will have his heart for God’s people. The biblical
account of the woman caught in adultery demonstrates how the church is to
respond to sin, regardless of the nature of that sin (John 8:1-11). Under no
circumstances is a follower of Jesus Christ to cast a stone. We cannot tell a
person created in God’s image (Imago Dei), who was so precious to the Father
that he gave his own son to ransom them to himself, that God hates them. In any
scriptural list of things God hates, one can find their own pet-sin included.
We have all fallen short of God’s standard (Romans 3:23).<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">Yet,
we have this second ideal: Speak the truth in love. Jesus ended his interaction
with the woman by telling her “sin no more”. In the Handbook of Christian
Counseling, Dr. Timothy Foster reminds us that “the first principle to remember
is speaking the truth in love, the second is unconditional acceptance… it means
not saying ‘you’ve got be different’</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-begin'></span> ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;DFWzHmZf&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;(Foster,
2005)&quot;,&quot;plainCitation&quot;:&quot;(Foster,
2005)&quot;,&quot;dontUpdate&quot;:true,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:180,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/HKU8Q9A7&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/HKU8Q9A7&quot;],&quot;itemData&quot;:{&quot;id&quot;:180,&quot;type&quot;:&quot;book&quot;,&quot;event-place&quot;:&quot;Eugene,
Or.&quot;,&quot;ISBN&quot;:&quot;978-1-59752-428-5&quot;,&quot;language&quot;:&quot;English&quot;,&quot;note&quot;:&quot;OCLC:
713192049&quot;,&quot;publisher&quot;:&quot;Wipf &amp; Stock
Publishers&quot;,&quot;publisher-place&quot;:&quot;Eugene,
Or.&quot;,&quot;source&quot;:&quot;Open
WorldCat&quot;,&quot;title&quot;:&quot;The Handbook of Christian
Counseling&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Foster&quot;,&quot;given&quot;:&quot;Timothy&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2005&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">(Foster, 2005)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-end'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">(</span><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Pg. 142)</span><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">. Ecumenical Minister David Du Plessis
once said that he never told anyone they were sinners; that was the Holy Spirit’s
job. His job was the love them well, introduce them to Jesus, and let the Holy
Spirit do His job </span><!--[if supportFields]><span style='font-size:12.0pt;
line-height:200%;mso-fareast-font-family:"Times New Roman";mso-fareast-theme-font:
major-fareast;mso-bidi-font-family:"Times New Roman"'><span style='mso-element:
field-begin'></span><span style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM
CSL_CITATION
{&quot;citationID&quot;:&quot;9isXLTaD&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;(Hearn,
1967)&quot;,&quot;plainCitation&quot;:&quot;(Hearn, 1967)&quot;,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:90,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/4336QA69&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/4336QA69&quot;],&quot;itemData&quot;:{&quot;id&quot;:90,&quot;type&quot;:&quot;motion_picture&quot;,&quot;abstract&quot;:&quot;Brother
David J. DuPlessis was known as Mr. Pentecost and was in the forefront of the
Charismatic movement in which the Baptism in the Holy Spirit became know and
experienced among non-Pentecostal denominations. This message entitled
\&quot;Forgiveness\&quot; by brother DuPlessis was given on the evening of June
30, 1967 at the Elim Campmeeting in Lima,
NY.&quot;,&quot;dimensions&quot;:&quot;1:16:51&quot;,&quot;medium&quot;:&quot;Audio
Recording: Posted to YouTube by Jay
Hearn&quot;,&quot;source&quot;:&quot;YouTube&quot;,&quot;title&quot;:&quot;David
DuPlessis<span style='mso-spacerun:yes'>  </span>- \&quot;Forgiveness\&quot;
June 30, 1967<span style='mso-spacerun:yes'> 
</span>pm&quot;,&quot;title-short&quot;:&quot;Forgiveness: Sermon by David Du
Plessis&quot;,&quot;URL&quot;:&quot;https://www.youtube.com/watch?v=afL_3rAM3yw&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Hearn&quot;,&quot;given&quot;:&quot;Jay&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,10,2]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1967&quot;,6,30]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">(Hearn, 1967)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-end'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">. In other words, we
accept you the way you are and refuse to force you to change, but we will
challenge you to take your life before the Holy Spirit and let Him shape you
into His image.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; One valid response is to work with people and lead them
into a process with God to seek healing and restoration. In his book, Think
Differently Live Differently, Licensed Marriage and Family Therapist (LMFT) Bob
Hamp tells the story of a woman who was set free from years of being trapped in
anger, living in masculine expression. Based on the description, this woman
could be classified today as transgender. Hamp softly challenged the lie she
was living, “you know you are a woman, right?”. As she released the lies of the
enemy (over many months), her body changed, and had her first-ever period in
her mid-thirties. Her body had lined up with her created order as her soul
healed, expressing physical changes in her femineity </span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;74ogjFy7&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;(Hamp,
2016)&quot;,&quot;plainCitation&quot;:&quot;(Hamp, 2016)&quot;,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:375,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/DAEH7RJG&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/DAEH7RJG&quot;],&quot;itemData&quot;:{&quot;id&quot;:375,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;In
Think Differently Live Differently Bob Hamp takes you on a practical journey to
change your thinking and discover a life of personal
freedom.&quot;,&quot;event-place&quot;:&quot;Southlake, Texas,
USA&quot;,&quot;ISBN&quot;:&quot;978-0-9963685-4-4&quot;,&quot;language&quot;:&quot;English&quot;,&quot;note&quot;:&quot;OCLC:
953439547&quot;,&quot;number-of-pages&quot;:&quot;207&quot;,&quot;publisher&quot;:&quot;bobhamp.com&quot;,&quot;publisher-place&quot;:&quot;Southlake,
Texas, USA&quot;,&quot;source&quot;:&quot;Open
WorldCat&quot;,&quot;title&quot;:&quot;Think Differently Live Differently Keys
to a Life of Freedom.&quot;,&quot;title-short&quot;:&quot;Think Differently
Live
Differently&quot;,&quot;URL&quot;:&quot;https://tdacad.com/product/think-differently-live-differently-book/&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Hamp&quot;,&quot;given&quot;:&quot;Bob&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2016&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">(Hamp, 2016)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-end'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">(Pg. 71-73). While this
type of healing is highly dependent on God and should likely be sought through
the careful hands of a trained and licensed Christian counselor, it is promising
that such instances of healing can occur.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Yet, we all know of people who prayed for some healing
that never came (physically, emotionally, mentally, etc.). What response can we
give these people? What about those who found no success in “praying the gay
way”? Phillip Yancey addresses the topic of pain in his book “Where is God When
it Hurts?” </span><!--[if supportFields]><span style='font-size:12.0pt;
line-height:200%;mso-fareast-font-family:"Times New Roman";mso-fareast-theme-font:
major-fareast;mso-bidi-font-family:"Times New Roman"'><span style='mso-element:
field-begin'></span><span style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM
CSL_CITATION
{&quot;citationID&quot;:&quot;Ukoyaa4F&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;(Yancey,
1997)&quot;,&quot;plainCitation&quot;:&quot;(Yancey, 1997)&quot;,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:374,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/NLQWNDDW&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/NLQWNDDW&quot;],&quot;itemData&quot;:{&quot;id&quot;:374,&quot;type&quot;:&quot;book&quot;,&quot;event-place&quot;:&quot;Grand
Rapids,
Mich.&quot;,&quot;ISBN&quot;:&quot;978-0-310-21437-3&quot;,&quot;language&quot;:&quot;English&quot;,&quot;note&quot;:&quot;OCLC:
864518538&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Mich.&quot;,&quot;source&quot;:&quot;Open
WorldCat&quot;,&quot;title&quot;:&quot;Where is God when it hurts?&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Yancey&quot;,&quot;given&quot;:&quot;Philip&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1997&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">(Yancey, 1997)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-end'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">. He concludes that even
when God does not bring healing, he comes alongside to be with us in our pain.
We can find comradery with Jesus in his pain on the cross. Ultimately, we can
all identify together with the same struggle. In an article about the church’s
response to the LGBT movement, Andy Crouch concludes that “All of us know, in
the depths of our heart, that we are queer. Our yearnings, especially those
bound up with our sexuality, are hardly ever fully satisfied by the biblical
model of one man and one woman yoked together for life.” Once Christians begin
to see that we are all fighting the same battle (submitting our desires to
God’s Word/Wisdom), we can see our LGBTQIA brothers and sisters as fellow
strugglers and not enemies.&nbsp; <o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This still leaves the church with debates. What about gay
marriage? What about gay lifestyle? Is there a difference between Orientation
and lived experience? Sean Fryling, a Pastoral Care Pastor for Real Life
Ministries, stated their position as follows. To anyone identifying as LGBTQIA,
the church saws “Welcome, we’re so glad you are here!” Anyone asking to get
into leadership or asking for the endorsement of their same-sex relationship
would be invited into deeper conversations. They have had pastors on staff who
have same-sex orientation but are committed to sexual expression being between
one man and one woman in a lifelong covenant relationship. These pastors live
as what the Bible would have called, Eunuchs. The Church works with these
pastors (and others like them) to get help, counseling, prayer, and support. If
they are committed to living faithfully to the Word, their orientation does not
prevent them from serving </span><!--[if supportFields]><span style='font-size:
12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";mso-fareast-theme-font:
major-fareast;mso-bidi-font-family:"Times New Roman"'><span style='mso-element:
field-begin'></span><span style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM
CSL_CITATION
{&quot;citationID&quot;:&quot;MSb8GcJC&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;(Fryling,
2020)&quot;,&quot;plainCitation&quot;:&quot;(Fryling,
2020)&quot;,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:347,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/ED27TIYR&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/ED27TIYR&quot;],&quot;itemData&quot;:{&quot;id&quot;:347,&quot;type&quot;:&quot;interview&quot;,&quot;abstract&quot;:&quot;Darrell
Wolfe (Interviewer) student at The King's University, sat down with Sean F
(Interviewee) Pastoral Care Pastor for Real Life Ministries, Post Falls, ID to
discuss the Pastoral Care/Lay Counseling available at Real
Life.&quot;,&quot;language&quot;:&quot;English&quot;,&quot;title&quot;:&quot;Pastoral
Care/Lay Counseling Interview: Real Life
Ministries&quot;,&quot;title-short&quot;:&quot;Interview - Pastoral
Care&quot;,&quot;URL&quot;:&quot;https://www.reallifeministries.com/pastoral-care&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Fryling&quot;,&quot;given&quot;:&quot;Sean&quot;}],&quot;interviewer&quot;:[{&quot;family&quot;:&quot;Wolfe&quot;,&quot;given&quot;:&quot;Darrell&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,11]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">(Fryling, 2020)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:major-fareast;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-end'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">. To those asking for
endorsement of their union, churches and pastors could say: “We believe in the
biblical mandate for marriage being between one man and one woman. We would
love the opportunity to discuss that further together, dive into the word
together, and help you see why we believe that to be the case. Please keep
coming, we hope you feel loved and accepted, but we cannot endorse the wedding
you are asking for.”<o:p></o:p></span></p>

<h1 style="line-height: 200%;">Conclusion<o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">While
the need persists to remain unchanging on The Church’s stance on topics such as
Marriage and Sexual Expression, the need also persists to remain unwavering on
our commitment to the hearts of people of any sexual orientation. We must begin
to see their struggle as no different than any other Christian’s struggle. Just
as to the woman caught in adultery, we must say to everyone (ourselves
included) “Neither do I condemn you, go and sin no more”. Then we must hold
their hand and walk with them.<b><o:p></o:p></b></span></p>

<h1 style="line-height: 200%;">References<o:p></o:p></h1>

<p class="MsoBibliography"><!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_BIBL
{&quot;uncited&quot;:[],&quot;omitted&quot;:[],&quot;custom&quot;:[]}
CSL_BIBLIOGRAPHY <span style='mso-element:field-separator'></span><![endif]-->Bennett, D. (2020, June 17).
LGBT Rights Ruling Isn’t the Beginning of the End for Religious Liberty. <i>Christianity
Today</i>. https://www.christianitytoday.com/ct/2020/june-web-only/bostock-gorsuch-supreme-court-ruling-religious-liberty.html<o:p></o:p></p>

<p class="MsoBibliography">Creech,
J. (2011). <i>Adam’s Gift: A Memoir of a Pastor’s Calling to Defy the Church’s
Persecution of Lesbians and Gays</i>. Duke University Press.<o:p></o:p></p>

<p class="MsoBibliography">Foster,
T. (2005). <i>The Handbook of Christian Counseling</i>. Wipf &amp; Stock
Publishers.<o:p></o:p></p>

<p class="MsoBibliography">Fryling,
S. (2020, November 11). <i>Pastoral Care/Lay Counseling Interview: Real Life
Ministries</i> (D. Wolfe, Interviewer) [Interview].
https://www.reallifeministries.com/pastoral-care<o:p></o:p></p>

<p class="MsoBibliography">Hamp,
B. (2016). <i>Think Differently Live Differently Keys to a Life of Freedom.</i>
bobhamp.com.
https://tdacad.com/product/think-differently-live-differently-book/<o:p></o:p></p>

<p class="MsoBibliography">Hearn,
J. (1967, June 30). <i>David DuPlessis—"Forgiveness" June 30,
1967&nbsp; pm</i> [Audio Recording: Posted to
YouTube by Jay Hearn]. https://www.youtube.com/watch?v=afL_3rAM3yw<o:p></o:p></p>

<p class="MsoBibliography">Shellnutt,
K. (2018, January 23). Get Ready, Youth Group Leaders: Teens Twice as Likely to
Identity of Atheist of LGBT. <i>Christianity Today</i>.
https://www.christianitytoday.com/news/2018/january/youth-group-leaders-generation-z-atheist-lgbt-teens-barna.html<o:p></o:p></p>

<p class="MsoBibliography">Shellnutt,
K. (2019, April 25). America’s Largest Christian Adoption Agency Lets LGBT
Couples Foster in 1 of 35 States. <i>Christianity Today</i>.
https://www.christianitytoday.com/news/2019/april/bethany-christian-services-michigan-foster-lgbt-couples.html<o:p></o:p></p>

<p class="MsoBibliography">Silliman,
D. (2020, August 3). Brethren Against Brethren: LGBT Fight Divides Peace
Church. <i>Christianity Today</i>.
https://www.christianitytoday.com/news/2020/august/church-brethren-southeastern-district-divide-covenant-lgbt.html<o:p></o:p></p>

<p class="MsoBibliography">Skylar,
Jay. (2018). The Prohibitions against Homosexual Sex in Leviticus 18:22 and
20:13: Are They Relevant Today? <i>Bulletin for Biblical Research</i>, <i>28</i>(2),
165. https://doi.org/10.5325/bullbiblrese.28.2.0165<o:p></o:p></p>

<p class="MsoBibliography">Steele,
J. (2019, April 26). United Methodist Court Keeps Core of New LGBT Legislation.
<i>Christianity Today</i>.
https://www.christianitytoday.com/news/2019/april/united-methodists-judicial-review-umc-traditional-plan-lgbt.html<o:p></o:p></p>

<p class="MsoBibliography"><i>The
Hebrew-Greek Key Word Study BIBLE: Key Insights Into God’s Word. New King James
(NKJV)</i>. (n.d.).
AMG Publishers.<o:p></o:p></p>

<p class="MsoBibliography">Yancey,
P. (1997). <i>Where is God when it hurts?</i> Zondervan.<o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%;"><!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p>&nbsp;</o:p></p>
<br />
<br />
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
