---
title: 'What happens to my marriage in heaven?'
date: '2020-03-22T15:41:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3413134934208907456'
blogger_filename: '/2020/03/what-happens-to-my-marriage-in-heaven.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

This question comes up a lot in the Widow rooms... If I get married again then who will I be married to in heaven? My first spouse or second?<div><br></div><div>This comes from a lack of understanding...</div><div><br></div><div>Things in heaven are of a higher order than what we experience on Earth.&nbsp;</div><div><br></div><div><div>There's no marriage in heaven.&nbsp;</div><div><br></div><div>That can sound like a "bad" thing to us here, but that's because we have such a small context for it.</div><div><br></div><div>Marriage is intimacy. As close as two people can be on Earth.</div><div><br></div><div>In heaven, and later when we all return to Earth again together, we know as we are known.&nbsp;</div><div><br></div><div>The intimacy we only glimpse here will permeate everything there.</div><div><br></div><div>The relationship we have there will be on a higher order than anything we are capable of here. Closer, not more distant.</div><div><br></div><div>There will be no hiding, no secrets, no shame, no guilt, no jealousy... Both my previous wives, #1 &amp;, #2... And my next wife... #3... Will all be my spiritual siblings. They all know Jesus, therefore, they'll all be there.</div><div><br></div><div>Even now, today, my late wife was my Sister in Christ which is a higher order than wife.&nbsp;</div><div><br></div><div>We'll ALWAYS, for eternity, be best friends and Sister/Brother in Christ...</div><div><br></div><div>We were only Husband and Wife for a few short years on Earth.</div><div><br></div><div>When I say Sister/Brother though, that's still an analogy. I'm not talking about spiritual incest.&nbsp;</div><div><br></div><div>It's like when military folks say "My brother in arms"... It's a Brotherhood/Sisterhood of joined identity... United under one family, with The Father as our Daddy. Jesus as our first born Brother. The Holy Spirit serving the function of Mother.&nbsp;</div><div><br></div><div>There's no marriage in heaven, because what we'll have will be SO much better, closer, and more intimate... That there's no way to label it here.&nbsp;</div><div><br></div><div>I hope that helps.&nbsp;</div><div><br></div><div>If you don't know if you're going to heaven... Read this: <a href="http://www.darrellwolfe.com/p/got-life.html?m=1">Got Life</a>?</div><div><br></div></div>