---
title: 'Is masturbation a sin?'
date: '2020-02-29T06:54:00.0000000+00:00'
draft: false
categories:
  - 'Musings'
---

<div>An anonymous friend of mine asked me this question, it's a question I've been asked by several friends in the last year. I'm reposting the question and my current thoughts (subject to change) with permission.</div><div><br></div><div><b><u>Question</u></b>:</div><div><br></div><div>Do you think masturbation, without using pornography, is still a sin?</div><div><br></div><div><b><u>My thoughts, as of February 28, 2020</u></b>:</div><div><br></div><div>That's a REALLY good question... I think there's a nuanced way of looking at this.... Multiple sides.&nbsp;</div><div><br></div><div>It's a question I've thought about, studied, and prayed about... A lot.</div><div><br></div><div>I've been sexually active and sexually aware since I was FIVE years old.&nbsp;</div><div><br></div><div>In Fall 2016, I was having an affair and planning my suicide.</div><div><br></div><div>In January 2017, I found a miracle healing of heart, but that miracle moment wasn't complete healing, it was merely the start of the journey.&nbsp;</div><div><br></div><div>It's taken two counselors, my late wife's unyielding Faith in me, Widowhood, multiple failed relationships and flings, and lots of prayers and some fasting and a lot of books and messages, a few classes, and a lot of safe friendships, and a lot of soul searching, and a lot of emotional healing... To finally say, in February 2020, I am free from Sexual Addiction.&nbsp;</div><div><br></div><div>Given that freedom, I know I must not return to bondage again. I must be diligent to guard my heart and steward my hard won freedom.</div><div><br></div><div>So with that background, what are my thoughts...</div><div><br></div><div><b>#1. Wrong Question from the end tree. Sin (S-State of being) is the root... sin (s-action or behavior) is the fruit.&nbsp;</b></div><div><br></div><div><div>Asking if a particular behavior is a "sin" is the wrong way to start any questions about God's Grace and Kingdom as New Testament believers. Behavior questions come from the Tree of Knowledge (of Good/Evil). All religious thought comes from that tree. It's the wrong tree. You cannot practice a "Better Knowledge of Good" and be any closer to God than the most evil sinner. We have all fallen short, all our righteousness is as filthy rags. You cannot be good. You cannot be "holy" if by that you mean good behavior. To be "holy" is to be set apart, not to behave well.</div><div><br></div><div>The Tree of LIFE doesn't ask behavior questions at all. It asks <b><i>identity</i></b> questions.&nbsp;</div><div><br></div><div>Who am I?&nbsp;</div><div><br></div><div>I'm God's Son/Daughter! I stand before him blood washed and stainless. My Sin (capital S, a state of being not an action) is paid for. My actions, sins (lower case s, fruit of Sin State, not the cause of it) are irrelevant.&nbsp;</div><div><br></div><div>This leaves us with:</div><div><br></div><div><b><i>All things are lawful but not all things are profitable.</i></b></div></div><div><br></div><div><b><u><br></u></b></div><div><div><b>#2. Principles not Laws. The Tree of Life alert what is best (heart issue), not what is best behaved (body, action issue).</b></div><div><br></div><div>So if all things are lawful but not all things are profitable, how can we view masturbation?</div><div><br></div><div>God made our bodies to be sexual bodies. This is why some people experience orgasms in their sleep. Many a man while going through adolescence has nocturnal ejaculation. The body processes it's need to release.</div><div><br></div><div>If due to the combination of psychological and biological need the pressure to release is so high that it's distracting you.... Go release it!&nbsp;</div><div><br></div><div>In some cases you may find that exercise meets that same need for release.</div><div><br></div><div><b>Caution</b>:</div><div><br></div><div>In the case of women more than men (but it's true for both) a state of arousal may require imagination or engaged mind. This is where we can get into trouble.&nbsp;</div><div><br></div><div>Fantasy is not bad. Fantasy is part of storytelling and storytelling is why we have movies and books and novels. But fantasy can lead to unreal expectations. When unreal expectations build up and become strongholds in the mind... They can create blocks for real intimacy.&nbsp;</div><div><br></div><div>This is why phornography is dangerous. Pornography builds unrealistic expectations inside the mind and heart, unrealistically high reactions of dopamine and serotonin and oxytocin... These inhibit real intimacy with another human.</div><div><br></div><div>So ultimately what you do with your body is irrelevant... Watch carefully how it's affecting your mind and heart.&nbsp;</div><div><br></div><div>You could accidentally create a block to real intimacy if you don't guard the heart and mind carefully.</div></div><div><br></div><div>As long as you have a peace about it... Get out the vibrator and get that release. Just watch the mind and heart and be sure you're not building any bondages.<br></div><div><br></div><div>See also, my best practices for alternatives here:</div><div><br></div><div>http://www.darrellwolfe.com/2020/02/god-is-passionate-about-your-sex-life.html<br></div><div><br></div><div><br></div><div>#Selah</div><div><br></div>