---
title: 'What happens after death, sleep or heaven?'
date: '2020-05-08T19:30:00.0010000+00:00'
draft: false
categories:
  - 'Musings'
---
**Question**: When you die, do you take a dirt nap until the end of times; or, do you go to heaven?

**Answer**:

I didn't know this was still a question. It's not even a grey area, biblically. Heaven.

You go to heaven for now, but that is not our final destination. Ultimately we'll all come back to earth at the end of times. But in the ages between prophetic events, we will go to heaven.

**Background**:

First interesting note, Jacob has a dream/vision of [Angels Ascending and Descending](https://www.biblehub.com/genesis/28-12.htm) from Heaven. Establishing early in Biblical interpretation that Heaven is an actual place that can be visited.

Paul, (speaking in the third person but referencing himself), [visited heaven](https://biblehub.com/2_corinthians/12-2.htm) and saw visions. This visitation is what led him to pen the statement which becomes the key idea for this topic:

**To be absent from the body, is to be [present with the Lord](https://biblehub.com/niv/2_corinthians/5.htm).**

When Jesus was on the cross, two men were with him on their crosses. One rejected Jesus, made fun of him. The other respected Jesus, and asked him to remember him when he came into his kingdom. In the most visceral act of "laying one's life down for another", in his own pain, Jesus told this man "you will be with me ***[today in paradise](https://biblehub.com/niv/luke/23.htm)***". This indicates that he will not be sleeping in the dirt.

Jesus, himself, told the story of a rich man and poor man. The story was not told in parable form, and may well have been a true account. Regardless, he portrays the scenario as being in line with truth about after life. Both men die, one is righteous and [escorted by an angel to Abraham's Bosom](https://biblehub.com/bsb/luke/16.htm). The other, being a selfish prick, is escorted to Hades. This story shows us another example of men being VERY conscious after death on earth. It's also an interesting example of the after-life pre-cross.

At that time, heaven was off limits. The Blood had not been shed. Jewish Tradition held that there were two sides of "[Sheol](https://en.wikipedia.org/wiki/Sheol)", hades and paradise. As the story shows, a chasm between the two was inseparable but there was still communication between them. Even discussion about why they can't return to earth to win the lost.

We also see that during his earthly ministry, Jesus received a visit from [Moses and Elijah](https://biblehub.com/matthew/17-3.htm), which is fascinated because one died and the other did not. This gives precedence for some, limited, interaction between Heaven, Sheol, and Earth, Dead and Living, as God wills only of course.

The bible says that when Jesus ascended from the grave, he took many [captives with him](https://biblehub.com/niv/ephesians/4.htm). Given the numerous references to the saints in heaven (especially throughout the book of [Revelations](https://biblehub.com/net/revelation/6.htm)) we see that Jesus cleared the captives from Paradise and took them with him into Heaven when he was raised from the dead.

Also interesting to note, there are two men who never have (yet) died. [Enoch](https://biblehub.com/bsb/genesis/5.htm) and [Elijah](https://biblehub.com/bsb/2_kings/2.htm). Both men have not yet physically died. These two received a special calling and were taken into Heaven directly from earth, body and all. Many end-times scholars (myself included) believe that these two men will come back as the [two witnesses](https://www.gotquestions.org/two-witnesses.html) spoken about in [Revelations](https://biblia.com/bible/esv/revelation/11/6). Since it has been appointed to man [once to die](https://biblehub.com/hebrews/9-27.htm), I believe these (the only two men to never die) will come back as the two witnesses.

At the end of the Great Tribulation, after the Marriage Supper of the Lamb which was taking place in heaven during the tribulation on earth, Jesus comes back to Earth with the believers in tow behind ([Rev 19](https://biblehub.com/net/revelation/19.htm)). This is after the Rapture, in which the dead in Christ have been risen. So it doesn't directly answer your question, but, it's interesting and the next stage in events.

After these, Jesus reigns, physically, on the Earth for [1,000 years](https://biblehub.com/net/revelation/20.htm), with all humanity that survived plus all believers that ever lived. Satan is locked in prison during this time, but afterward released once more. He will prove once and for all that even in a perfect society with a perfect King, the hearts of men will rebel. With this final global lesson learned, he will wipe the slate clean and remake the Earth all over again. I don't believe this means the planet will be destroyed. God is a God of Redemption. So he will clean up and make new a [New Heaven and New Earth](https://biblehub.com/net/revelation/21.htm). They will then be reunited, and co-exist as one entity in one location. The actual physical city that is built in heaven right now, populated with those who have passed, right now, will descend from Heaven onto Earth, and God Himself, the Father, will dwell on Earth at this point. Until now, the Son reigned on Earth for 1,000 years. Now the Father himself will reside on Earth forever more.

** A few fun [Heaven Scriptures here](https://www.biblestudytools.com/topical-verses/heaven-bible-verses/) as well.*

**References**:

[2 Corinthians 12:2](https://biblehub.com/2_corinthians/12-2.htm)
I knew a man in Christ above fourteen years ago, (whether in the body, I cannot tell; or whether out of the body, I cannot tell: God knows;) such an one caught up to the third heaven.

2 Cor 5:8 [New International Version](https://biblehub.com/niv/2_corinthians/5.htm)
We are confident, I say, and would prefer to be away from the body and at home with the Lord.

Luke 23:43 [New International Version](https://biblehub.com/niv/luke/23.htm)
Jesus answered him, "Truly I tell you, today you will be with me in paradise."

Revelation 4:1 [New International Version](https://biblehub.com/niv/revelation/4.htm)
After this I looked, and there before me was a door standing open in heaven. And the voice I had first heard speaking to me like a trumpet said, "Come up here, and I will show you what must take place after this."

[Genesis 5](https://biblehub.com/bsb/genesis/5.htm) - God Takes Up Enoch (See Also [Hebrews 11:5](https://biblehub.com/bsb/hebrews/11.htm#4))

[18](https://biblehub.com/genesis/5-18.htm)When Jared was 162 years old, he became the father of Enoch. [19](https://biblehub.com/genesis/5-19.htm)And after he had become the father of Enoch, Jared lived 800 years and had other sons and daughters. [20](https://biblehub.com/genesis/5-20.htm)So Jared lived a total of 962 years, and then he died.

[21](https://biblehub.com/genesis/5-21.htm)When Enoch was 65 years old, he became the father of Methuselah. [22](https://biblehub.com/genesis/5-22.htm)And after he had become the father of Methuselah, Enoch walked with God[c](https://biblehub.com/bsb/genesis/5.htm#fn) 300 years and had other sons and daughters. [23](https://biblehub.com/genesis/5-23.htm)So Enoch lived a total of 365 years.

[24](https://biblehub.com/genesis/5-24.htm)Enoch walked with God, and then he was no more, because God had taken him away.[d](https://biblehub.com/bsb/genesis/5.htm#fn)

[2 Kings 2](https://biblehub.com/bsb/2_kings/2.htm)

[11](https://biblehub.com/2_kings/2-11.htm)As they were walking along and talking together, suddenly a chariot of fire with horses of fire appeared and separated the two of them, and Elijah went up into heaven in a whirlwind.

[12](https://biblehub.com/2_kings/2-12.htm)As Elisha watched, he cried out, "My father, my father, the chariots and horsemen of Israel!" And he saw Elijah no more. So taking hold of his own clothes, he tore them in two.

[13](https://biblehub.com/2_kings/2-13.htm)Elisha also picked up the cloak that had fallen from Elijah, and he went back and stood on the bank of the Jordan. [14](https://biblehub.com/2_kings/2-14.htm)Then he took the cloak of Elijah that had fallen from him and struck the waters. "Where now is the LORD, the God of Elijah?" he asked.

And when he had struck the waters, they parted to the right and to the left, and Elisha crossed over.

[Luke 16](https://biblehub.com/bsb/luke/16.htm) The Rich Man and Lazarus ( See Also [John 5:39-47](https://biblehub.com/bsb/john/5.htm#39)) (Other translations say "Abrahams' Bossom").

[22](https://biblehub.com/luke/16-22.htm)One day the beggar died and was carried by the angels to Abraham's side.[d](https://biblehub.com/bsb/luke/16.htm#fn) And the rich man also died and was buried. [23](https://biblehub.com/luke/16-23.htm)In Hades, where he was in torment, he looked up and saw Abraham from afar, with Lazarus by his side.

[2859](https://biblehub.com/greek/2859.htm "Strong's Greek 2859: Apparently a primary word; the bosom; by analogy, a bay.") [\[e\]](https://biblehub.com/greek/strongs_2859.htm "Englishman's Greek Concordance") [kolpon](https://biblehub.com/greek/kolpon_2859.htm "kolpon: Apparently a primary word; the bosom; by analogy, a bay.") κόλπον bosom

2859 kólpos -- properly, the upper part of the chest where a garment naturally folded to form a "pocket" -- called the "bosom," the position synonymous with intimacy (union).

Ephesians 4:8 [New International Version](https://biblehub.com/niv/ephesians/4.htm)
This is why it says: "When he ascended on high, he took many captives and gave gifts to his people."

[Revelation 6](https://biblehub.com/net/revelation/6.htm)

[9](https://biblehub.com/revelation/6-9.htm)Now when the Lamb opened the fifth seal, I saw under the altar the souls of those who had been violently killed because of the word of God and because of the testimony they had given. [10](https://biblehub.com/revelation/6-10.htm)They cried out with a loud voice, "How long, Sovereign Master, holy and true, before you judge those who live on the earth and avenge our blood?"

Hebrews 9:27 [New International Version](https://biblehub.com/niv/hebrews/9.htm)
Just as people are destined to die once, and after that to face judgment,
