---
title: 'You are not alone...'
date: '2020-02-19T16:58:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7148260448839932138'
blogger_filename: '/2020/02/you-are-not-alone.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
  - 'Episode 1'
  - 'Season 0'
  - 'Podcast'
---

The suffering of Jesus...&nbsp;<div><br></div><div><i>"You unbelieving and perverse generation," Jesus replied, "how long shall I stay with you? How long shall I put up with you? Bring the boy here to me."&nbsp;Matthew 17:17</i><br></div><div>https://biblehub.com/matthew/17-17.htm<br></div><div><br></div><div>I bet that's not the first verse you think of when you think of the suffering of Jesus.</div><div><br></div><div>So often when we think of the suffering we think of the cross. Indeed, the cross was the final and most important work of Jesus. It is because of the cross that we even talked about him. It is because of the cross we can stand before his Father guiltless. It is because of the cross that he can be our high priest. But I submit to you that his suffering went far beyond the cross; when you are suffering he can empathize quite a bit.</div><div><br></div><div><i>For we do not have a high priest who is unable to empathize with our weaknesses, but we have one who has been tempted in every way, just as we are--yet he did not sin.&nbsp;Hebrews 4:15</i><br></div><div>https://biblehub.com/hebrews/4-15.htm<br></div><div><br></div><div>Jesus suffered the ignorance of people around him.&nbsp;</div><div><br></div><div>Jesus suffered persecution from the intellectual elite of his day.</div><div><br></div><div>Jesus suffered betrayal from one of his own.</div><div><br></div><div>Jesus suffered every temptation that we experience.</div><div><br></div><div>Jesus suffered hunger an lack.&nbsp;</div><div><br></div><div>Jesus suffered the mismanagement of his ministries finances by someone he trusted with them.</div><div><br></div><div>Jesus suffered obscurity for 30 years before starting a very public ministry. Burdened with a purpose beyond any purpose we've experienced and yet unable to do anything about it for 30 years other than prepare.</div><div><br></div><div>Jesus suffered the death of a friend.</div><div><br></div><div>Jesus suffered the death of a parent...</div><div><br></div><div>Not much is known about Joseph the husband of Mary. But we know that he obeyed God and took Mary and even though she was already pregnant. So we know he had high character. And we know that his life was disrupted not only by a census but by an emergency trip to Egypt which likely lasted several years. We know that he lived till at least the time Jesus was 12, because when he was 12 Joseph and Mary went looking for him after they lost him.&nbsp;</div><div><br></div><div>We hear no mention of Joseph during the days of Jesus ministry. And we know that Jesus assigned one of his disciples as Mary's new son to take care of her. From the day of jesus's death forward Mary went to live with the disciple John, the one whom Jesus loved.&nbsp;</div><div><br></div><div>So sometime between the age of 12 and 30, Jesus watched his dad die. The creator of the universe, who would eventually heal thousands of sick people and even raise some from the dead and eventually raise from the dead himself... This man watched his dad die and grieved him.</div><div><br></div><div>The Bible says he was tempted in every way that we were tempted. Every means all. All means all and that's all all means. Which means he was also tempted by sexual temptations. Having a former prostitute around him regularly cannot have been easy. She knows one way to show gratitude above all others and she does it so well she's been paid for it. I have every reason to believe she would have offered that type of gratitude. But he didn't accept.</div><div><br></div><div>It's impossible for one man to have suffered the exact circumstances of every other man on the planet, I'm sure that you could find examples of situations that he didn't suffer. He did not lose a parent before the age of 12. But in a broader sense if there's something that we suffer he has too.</div><div><br></div><div>So whatever you're going through today... Stop and think about that for a few moments and realize that Jesus actually feels your pain with you. Not just in some esoteric theological sense. Jesus feels that pain because he's experienced it.</div><div><br></div><div>You are not alone.</div><div><br></div><div>#Selah</div><div><br></div><div>PS: Testing the waters on a podcast. Used this post as a jumping off point.&nbsp;</div><div><br></div><div>https://anchor.fm/darrellwolfe/episodes/Jesus-suffered-in-more-ways-than-you-think-eanhlt<br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div>