---
title: 'Boundaries are for you not the other person.'
date: '2020-03-08T14:03:00.0010000+00:00'
draft: false
categories:
  - 'Musings'
---

It's always interesting when you draw boundaries.&nbsp;<div><br></div><div>When we first try to set boundaries, we think it means telling the other person to stop and the boundaries are a way of making them change. Then they don't change and we say "boundaries didn't work".</div><div><br></div><div>The other person usually doesn't change.&nbsp;</div><div><br></div><div>Sometimes they will, if you are firm and you change the rules of the game to be more healthy, it can create an environment where the other person is missing half their pattern, so they must change.</div><div><br></div><div>But you can't set the boundaries expecting change. It's nice, but don't expect it.</div><div><br></div><div>Rather, boundaries are YOUR protective fence. It's as though you decided you've had enough with people walking through your garden and you finally decided to put up a fence around it. If people climb over the fence, you may also need a guard dog or security guard.</div><div><br></div><div>The point of boundaries is for you to decide how <i>you</i> will respond, including what mechanisms you'll need to enforce that response.&nbsp;</div><div><br></div><div>The point is to protect the garden of your heart, not so that the other person will change. They'll go trample someone else's garden, but not yours.</div><div><br></div><div>If they change, they could be invited back into a healthier exchange. But people don't change without a lot of pain.</div><div><br></div><div>I know. I was awful for decades. It took many events, many confrontations, and dinner life shattering experiences to give me enough pain to seek help.</div><div><br></div><div>I am a completely different human than I was in Fall 2016.</div><div><br></div><div>But that didn't come without a lot of assistance, books, healthy community, and some tough love by people who cared enough to tell me I was wrong.</div><div><br></div><div>What boundaries do you need to set today to protect your garden?</div><div><br></div><div>In what ways might you be stepping over other people's boundaries and not knowing it?</div><div><br></div><div>#Selah&nbsp;</div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div>