---
title: 'Don''t get all worked up about tomorrow, focus on the story you are living today.'
date: '2020-12-09T06:24:00.0020000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5423280243767692773'
blogger_filename: '/2020/12/dont-get-all-worked-up-about-tomorrow.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<h3 style="text-align: left;">I'm older. I don't know if I'm wiser; however, I am less stubborn (slightly).&nbsp;</h3><div><br /></div><div><div><blockquote>16Then He told them a parable: “The ground of a certain rich man produced an abundance. 17So he thought to himself, ‘What shall I do, since I have nowhere to store my crops?’ 18Then he said, ‘This is what I will do: I will tear down my barns and will build bigger ones, and there I will store up all my grain and my goods. 19Then I will say to myself, “You have plenty of good things laid up for many years. Take it easy. Eat, drink, and be merry!”’ 20But God said to him, ‘You fool! This very night your life will be required of you. Then who will own what you have accumulated?’ 21This is how it will be for anyone who stores up treasure for himself but is not rich toward God.” <a href="https://biblehub.com/bsb-strongs/luke/12.htm" target="_blank">Luke 12</a></blockquote></div></div><div><br /><div><ul style="text-align: left;"><li><b>Lesson</b>: Don't get all worked up about tomorrow, focus on the story you are living today.&nbsp;</li></ul></div><div><br /></div><div>You do not need to be rich to make the mistake this parable is addressing.&nbsp;</div><div><br /></div><div>As I reflect on the "memories" which Google Photos and Facebook are so fond of showing me; I am reminded of a thousand instances of younger me.&nbsp;</div><div><br /></div><div>Hopes. Dreams. Worries. Fears.&nbsp;</div><div><br /></div><div>In every photo, I am smiling, engaged as I knew how to be, but I remember being lost in a thousand thoughts of things I needed to do and accomplish, things I didn't know how I could accomplish; and the burning question of "What's next?"</div><div><br /></div><div>Not much has changed, here I am having experienced losses that should make a man appreciate the story in front of him, but as life returns to "new normal" for the 100th time in the last four-ish years I find myself lost again in the minutia of the future at the expense of being present in the moment.&nbsp;</div><div><br /></div><div>I have people and experiences to be present for today. Tomorrow can handle its own worries. Rather than planning for ten thousand things that won't matter tomorrow because of the curve-ball that hasn't come yet... I will plan my best and then rest.&nbsp;</div><div><br /></div><div>Goodnight friends,</div><div><br /></div><div>
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
</div></div>