---
title: 'Who am I? Clarify Your Calling'
date: '2020-09-23T05:01:00.0030000+00:00'
draft: false
---
\~\~\~{=html}

# Who am I?

## Clarify Your Calling: Your Sweet Spot!

Over the years, I have made a point of self-study, so I can learn more about who I am and why I am the way I am. Who am I called to serve? What would be the best use of my skills? Etc. In that time, I've coached and worked with others through those same questions. There is one key lesson you must learn to make the process of self-discovery more effective.

In Clifton [Strengths Finder 2.0](https://www.amazon.com/Strengths-Finder-2-0-Upgraded-Discover/dp/B00DDR6WJK/ref=sr_1_6?crid=3NOFY8Q2175E2&dchild=1&keywords=clifton+strengthsfinder+2.0+with+access+code&qid=1600834235&sprefix=clifton+%2Caps%2C356&sr=8-6), the book, there is a powerful lesson that everyone would be best learning early in the self-discovery process and it runs contrary to the mythology many are taught in our society:

> You CANNOT be anything you want in life; but you CAN be a lot more of who you already are.

The essence of the lesson is that you can expend a lot of effort doing something you are passionate about but not good at, resulting in few results; OR, you can expend far less effort doing something you are passionate about and good at and see exponentially more results. Your best self, the self that does the most good in this world, is in that second category.

I've broken down these concepts more in previous posts ([Discovery](http://www.darrellwolfe.com/2016/05/discovery-finding-your-place-in-god-plan.html)) and (The [Hedgehog](http://www.darrellwolfe.com/2014/03/the-hedgehog-sweet-spot-finding-your.html)). The bottom line can be summarized by what [Ken Coleman](http://www.kencolemanshow.com/speaking/) referred to "The Sweet Spot":

> ***"You find your sweet spot by finding the intersection of your greatest strength and your greatest passion."***

The following is a series of exercises you can do to hone your calling and find your sweet spot.

These exercises will not tell you that you should become "a doctor" or a "a writer". What they will do, is help you identify your giftings, callings, passions, and themes. As you begin to refine these, they will help you define a Vision, Mission, Life Theme, Characteristics, and Guides (bottom of this post). Once you have a handle on these, you will use them throughout life to know what opportunities to take advantage of and which to take a pass on.

**NOTE**: You are always evolving. These will not remain stationary. You should revisit these periodically as you mature. Your Vision or Mission doesn't have to lifelong. They can be seasonal and are subject to change as you grow. Use them as guides, not hard rules.

I hope you enjoy this exercise. Write or comment if you'd like to get in touch.

**** I will be updating this post periodically, so please feel free to re-visit for updates.****

## DISCOVERY PROCESS

Discover your personality ***themes*** by taking a variety of personality tests, and personal evaluations, each designed to help you see aspects of your personality, gifting(s), and personal themes.

It's important to realize that your "type" in each test is less relevant than what you resonated with in the results. It's what you gained from knowing your type and how that helps you identify who you are that matters most.

From each test, your goal is to identify two things:

1.  Aha! Moments. Any moments where you felt like you were suddenly able to understand yourself better or you felt the test "got you".
2.  Recurrent Themes, did you notice the same ideas present in multiple test results, and each of them resonating strongly with you? Pay attention to these.

In the following sections, don't be too organized. Just throw it all out onto the pages. Anything you see, any themes, any key words, any insights, anything that stands out.

The goal is discovery first, then we can sift through that data and make sense of it. Then compile the results here in the tables below. Also, any other tests you are aware of, not included in this list, use those too! The more you data you have the more you can use to identify themes and Aha! moments.

***

## Myers-Briggs Type Indicator (MBTI) at 16Personalities

*Take the Myers-Briggs Type Indicator (MBTI) at [16Personalities](https://www.16personalities.com/personality-types), you will be assigned a four letter designation, a theme name, and a summary of the theme. For example, mine is INFJ/Advocate.

### Type: \_\_\_\_\_\_ (Ex: INFJ)

#### Theme Name: \_\_\_\_\_\_\_ **(Ex: Advocate)**

#### Discoveries:

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Key Words of Theme:

- \_\_\_\_\_\_\_\_\_\_
- \_\_\_\_\_\_\_\_\_\_
- \_\_\_\_\_\_\_\_\_\_
- \_\_\_\_\_\_\_\_\_\_
- \_\_\_\_\_\_\_\_\_\_

***

## CliftonStrengths

*Take the Gallup [CliftonStrengths](https://www.gallup.com/cliftonstrengths/en/253868/popular-cliftonstrengths-assessment-products.aspx), either Top 5 or all 34. Write down your top five, and read about them, including your unique combination of strengths.

#### Top Five Strengths:

1.  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
2.  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
3.  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
4.  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
5.  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Discoveries:

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Key Themes:

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

***

## DISC Profile Type

*Take the DISC Profile Type: (2 good options: [123Test.com](https://www.123test.com/disc-personality-test/) or [Tony Robbins](https://www.tonyrobbins.com/disc/)). You will be assigned one major type: Dominance, Influence, Steadiness and Conscientiousness. Read about your type and brainstorm your findings.

#### DISC Type: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Discoveries:

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Key Themes:

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

***

## Enneagram

*Take the Enneagram (by [Truity](https://www.truity.com/test/enneagram-personality-test)). You will have one of the nine numbers score highest, also pay attention to the two next highest, these are considered your Wings. Brainstorm your discoveries.

#### Enneagram Type: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Wing 1: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Wing 2: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Discoveries:

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Key Themes:

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

***

## Spiritual Giftings

*Take the Spiritual Giftings (by [Team Ministry Gifted to Serve](https://gifts.churchgrowth.org/spiritual-gifts-survey/)).

#### Spiritual Giftings:

1.  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
2.  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
3.  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
4.  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
5.  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Discoveries:

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Key Themes:

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

## **** Putting it all together ****

## THEME

**Based on your personality tests, what is your theme?*

#### Theme:\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Key Words of Theme:

1.  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
2.  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
3.  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
4.  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
5.  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

## CHARACTERISTICS

#### About Your Who

**Three traits/themes, unique to you, that make you authentically you. These are traits you possess, they are about you (You can use more than three if you'd like).*

1\. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

2\. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

3\. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

## GUIDES

#### About You

**Three principles, unique to you, to help guide you in every opportunity. When to say Yes/No. These are traits, patterns, themes, in your "who", the people, market, niche, types you are drawn to (You can use more than three if you'd like). *

1\. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

2\. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

3\. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

## VISION

**Problem that hurts you. Your solution. The transformation someone experiences from being with you. *

This is the line you give everyone you meet. See [Donald Miller](http://buildingastorybrand.com/minisode-1/) or [Michael Hyatt](https://michaelhyatt.com/communicating-vision/) for more on this. Here's a video on Donald Miller's One Liner.

https://youtu.be/HFergI0UOAs

When you meet someone in the elevator or at a party, they say "tell me about yourself, what do you do\... etc". Don't reply "My name is Darrell. I'm  father, I work a a call center\..." Reply with your vision.

**Framework**: You know how sometimes (describe the problem people have that you solve in life). I help \_\_(my who)\_\_ do (see, understand, get)\_\_(my unique value added/solution)\_, so that \_(the transformation they experience/benefits not features).

**Example Professional**:

You know how there are people who walk around frustrated with Religion but still desperately wish they could know God?

I use a philosophy called NO HIDING to help disillusioned or de-churched Christians reconnect with the Heart of Daddy-God, heal from old wounds, and discover new purpose.

So that they can experience: Radical Authenticity, Healthy Connection, and Identity Rooted in God's Love.

**Example Personal:** You know how some moms are exhausted and lonely? I connect with isolated moms, take them out to coffee, and let them know they're loved. Helping moms is my biggest passion. What's yours?

#### Your Vision Statement:

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

## MISSION

**Can be temporary, must be specific outcome based, but focused on daily actions that vote for this outcome.*

This mission is to be as specific as possible. Temporary or short term is fine. It must be actionable, measurable, and specific.

**Framework**: I am the kind of person who \_\_\_\_(your theme, can be lifelong or temporary)\_\_, and I am on a mission to \_(as specific as possible, clean the house by spring)\_. To do that, I (we) will \_(specific actions that cumulatively will create that result, clean out one room or closet every Saturday)\_.

Example: We are the type of family who loves each other. We know that being connected makes that love grow stronger. To do that, we will play board games 3-times each month this summer and turn of the screens while we do. We'll talk to each other during the game and find ways to honor each other in the process by asking questions without over speaking or arguing.

#### Your Mission Statement:

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

## Other helpful tests:

Use these same types of exercises on any other tests you can find or want to use. Here are a few others I and others found helpful:

- [Total SDI](https://totalsdi.com/assessments/overview/)
- [Uniquely You](https://uniquelyyou.org/)
- [The MAPP Career Assessment](https://www.assessment.com/)
- [The 11 Best Career Quizzes to Help You Find Your Dream Job](https://www.themuse.com/advice/the-11-best-career-quizzes-to-help-you-find-your-dream-job)

Thank you for reading today,
