---
title: 'It''s time for a Heart Transplant...'
date: '2020-08-22T10:38:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7356583288347979354'
blogger_filename: '/2020/08/its-time-for-heart-transplant.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musing'
---

<div>Doctor Gregory House, television Character in the TV Series House, is an arrogant, selfish, brilliant man who lives for the puzzle...&nbsp;</div><div><br></div><div>Often working to find out what's wrong with someone despite them, he endangers them just to answer the question. He's the doctor you want solving your case, as long as someone is holding his reigns and enforcing him to remain humane.&nbsp;</div><div><br></div><div>In short... He's me.</div><div><br></div><div>But I don't solve medical mysteries... I solve theological and philosophical and psychological ones.&nbsp;</div><div><br></div><div>And I've been known to leave a few wounded and bruised in the process of diagnosis.</div><div><br></div><div>Things fit together like a clean puzzle for me if I'm given long enough to ponder it.&nbsp;</div><div><br></div><div>People bring me the pain that seperates them from God or others... And I can usually begin to unravel the thing that seems so complicated to them, simplify it, and give them a prescription for the Spiritual-Psychological path to recovery.&nbsp;</div><div><br></div><div>Like Greg House, I too have a much harder time unraveling the mystery for those closest to me. I lack the distance required to diagnose.</div><div><br></div><div>I find the ones I can't help usually result from a few commonalities.</div><div><br></div><div>They don't like my diagnosis.</div><div>They don't agree with my diagnosis.</div><div><br></div><div>I already admitted I am arrogant, so I'll take another note from House and say: I am rarely wrong.&nbsp;</div><div><br></div><div>If they don't like it, or agree with it, it's usually because they can't see the whole picture... Not because I was wrong.</div><div><br></div><div>That's where I lack.&nbsp;</div><div><br></div><div>They're heart.</div><div><br></div><div>I can't get into their heart, and shove 40 years of experience and knowledge into them to give them the whole picture.&nbsp;</div><div><br></div><div>How do I communicate in a way that they'd see it?</div><div><br></div><div>Like House begins learning in season 7....... Love is the key.&nbsp;</div><div><br></div><div>Not just being kinder about my delivery... Or even my diagnosis...&nbsp;</div><div><br></div><div>LOVE Himself usually has a way of communicating to each heart in a way that is unique, like a fingerprint. He can reach into that heart, pull a memory tied to the healing they need, and tie them together, then download decades of revelations in a single moment.</div><div><br></div><div>As a Biblical Counselor... It's not my job to be brilliant, witty, or force my solution into someone. My intellectual capacity is a tool he's given me to see the problem in creative and unique ways, and see answers nobody's considered........&nbsp;</div><div><br></div><div>But HIS heart is required in each situation. In every instance, he's wanting to perform a heart transplant. And each and every time, he'll do it differently.&nbsp;</div><div><br></div><div>My job isn't to be smart and have all the answers. That's good TV but not real life.&nbsp;</div><div><br></div><div>My job is to use the gifting he's given me to facilitate a meeting between Jesus and this person.... And let Him do all the heavy lifting and cutting and transplanting.</div><div><br></div><div>My job... Is to usher Him in, and step aside.</div><div><br></div><div>Selah...</div><div><br></div><div>Shalom...</div><div><br></div><div>Darrell</div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div>