---
title: 'My superpower: Lean In.'
date: '2020-02-26T07:37:00.0010000+00:00'
draft: false
categories:
  - 'Musings'
---

I think I found my superpower... It's called Lean In.&nbsp;<div><br></div><div>All my life, I ran. In fifth grade, I ran from school, ran into homeschool, and I've been running from hard stuff ever since.&nbsp;</div><div><br></div><div>If it's too hard, challenging, it's not for me. My greeting of departure was always "Have fun!"</div><div><br></div><div>But when my inner life crashed in around me at the end of 2016... And I entered a season of darkness that led to me planning my own death... I made a choice I'd never made before. It seemed so small, at the time, but it turned out to be the theme upon which I've built my entire life's successes... I leaned in.&nbsp;</div><div><br></div><div>I went to two men, a counselor and a small group leader, and I laid it all out to them. Told them I'd be there regularly until I finished making up my mind who I was going to be.&nbsp;</div><div><br></div><div>Jacob wrestled with God all night, through his darkness, and he left touched by God. Out of that encounter he left with a permanent physical reminder of the struggle, and a new name, new identity.&nbsp;</div><div><br></div><div>When I came out of that season, I too had a permanent reminder and a new identity. It was a fledgling identity, but it was a start.&nbsp;</div><div><br></div><div>When my wife, the boy's mom, died, I had to press into that new identity pretty hard. I had to lean in. I failed and succeeded, back and forth. But I leaned in to the grieving process.&nbsp;</div><div><br></div><div>Tonight, I've been leaning into change on the way I handle political conversations.</div><div><br></div><div>That's been hard to swallow.</div><div><br></div><div>What's irritating you today? Bothering you? What's getting to you at an almost irrational level? What change are you afraid of?&nbsp;</div><div><br></div><div>Lean In to that feeling. Whatever makes you uncomfortable, is exactly where you need to be.</div><div><br></div><div>#Selah</div><div><br></div><div><br></div>