---
title: 'Special Edition: Is your food killing you?'
date: '2020-04-15T05:23:00.0010000+00:00'
draft: false
categories:
  - 'Studies'
  - 'Book Review Notes'
---
\~\~\~{=html}

## Everything I ever thought I knew about food is wrong.

Thankfully, I have been learning about it and seen tremendous results and I'm here to report my findings.

This is a long post, but it's everything I learned in the last few months about food.

****Disclaimer* I am not a medical expert. What you are about to read should be considered a book report/book review, and it contains anecdotal experiences. Nevertheless, I believe you will find it useful to take your own food journey.***

### Why talk about food?

*Myth: Nobody knows what healthy even means, everything is going to kill you, just eat what makes you happy and die happy.*

*Fact: The body was crafted and created by God to function at optimal levels. Eating unhealthy creates a slower-moving, more fragile, foggy-brained, lethargic, body that is often sick and in pain. You're not dying happy, you're dying Fat, Sick, and in Pain. And most of it is because of what you are feeding yourself. Almost every ailment in the US Health System from Diabetes Type 2 to ADHD to High Blood Pressure to even cancer can be linked to food. Even those with legitimate body break-downs like Alzheimer's and Parkinson's can find longer and higher quality life by adopting these food principals*

Part of NO HIDING is recognizing that your own brokenness and your own choices have led you to where you are today, and facing that truth head-on. When you face the truth for what it is, you can begin to heal through it and make new choices. As long as you live in denial, you will be doomed to repeat the past.

FOOD seems like such an innocuous subject. We post pictures of it on Instagram, follow recipe boards on Pinterest, get enticed by commercials of a sizzling steak. Yet, if I had understood a handful of years ago what I understand now, I am positive my late-wife would not have died.

The choices you make with food are life and death. It's literally in the power of your tongue.   My personal testimony is at the bottom of this post.

***********

### Food Discovery Highlights:

For those who don't want all the details, here is the Bottom Line:

- The FDA food pyramid is WRONG, completely upside down.
- Grain is evil. Fat is great!
- Sugar (not dietary fat): Is the leading cause of death and disease in the West. Including and especially cancer, diabetes, high blood pressure, and heart disease!
- Grain (which the body converts to sugar) is the leading cause of obesity in the West.
- Low-Fat products/diets combined with hyper-sweet fake sugars are killing you. "Low Fat" is about the worst thing you can eat.
- A High Fat / Low Sugar(sweet) / Low Grain Diet is the best food for you!
- A healthy food lifestyle primarily consists of lots of healthy fats, moderate proteins and veggies, some fruits, and very few breads or grains or sugars.
- Dairy is a crap-shoot, more on that below in the detailed section.
- Next to Grain/Sugar is most things labeled "Sugar-Free", which usually contain fake sugars, which are worse than normal sugars.
- Not all oils are created equally. Oils defined as PUFAs are generally to be avoided (details down below). I only use Coconut Oil, Avocado Oil, and Olive Oil in my cooking now. And occasional meat fats from ethically sourced meats.

*******

###  What is healthy eating?

After reading Whole30 and Keto Science, and doing my own experiments, my go-to plan is the following.

#### A "good" meal, would consist of:

1.  **Protein** (15-30 %) 1-2 palm-sized amounts of proteins Eggs (2-4) and Meats (locally sourced, no hormones, antibiotics, etc), Chicken, Fish, Etc.
2.  **FAT** (60-80 %): Lots of healthy fats (Olive Oil, Avocado Oil, Coconut Oil) // Avocados, walnuts, etc. Even meat fats.
3.  **Veggies**: Fill the rest of the plate with at least two veggies (preferably more, eat the rainbow).

#### Caveats:

- **Moderate use of fruits and whole-natural sweetness**, such as Raw Local Honey or Crushed Dates, nothing highly processed. Make sure the Honey is Raw Local Honey. Many things calling themselves honey are actually corn syrup flavored with some honey that is death juice. If you've removed nearly all "added sugars/sweeteners" from everything, the moderate use of fruit is fine. Just don't go overboard, especially in the first six months while becoming "fat-adapted".

&nbsp;

- Either no or as few as possible:
  - **Grains** (wheat, rice, etc)
  - **Added Sweetness** from Processed Means (even and especially, fake stuff).
    - *No Sugar, Monk Fruit, Stevia, Xylitol, Aspartame, the more hyper sweet the worse it is).
    - Careful, as this is deceptive. There are at least 61 names for sugar.
    - For a complete list, see this link, here are some common ones to watch for: Sugar, Syrup, Caramel, Lactose, Maltodextrin, Sorbitol, Sucrose, Fructose, Glucose, Molasses, Aspartame, Saccharin, Acesulfame, Sucralose.
    - Watch for these on labels you might not expect, like ketchup, pasta sauce, soy sauces, dressings, etc. I even saw sugar added to a Cranberry Juice bottle from Ocean Spray today. It will be listed under "Ingredients".

&nbsp;

- **Dairy**: Dairy is off-limits for me. Some people have no problem processing dairy and can safely include this in their keto plans. However, due to the dairy sugars involved, and other issues outlined below, I will avoid it as often as possible.

&nbsp;

- **Note**: For those wanting to induce full Ketosis, further restrictions about types of foods, fruits, and carb-heavy items like potatoes may be required. Especially if they are using it for a medical condition such as epilepsy or cancer recovery.

&nbsp;

- **Note Too**: I will NEVER count calories or plan in detail specific percentages of fat to protein ratios. It's just not me. So I will stick to basic rules about what the plate should look like. That I can follow.

You should have 2-3 of these meals a day (depending on whether you are including intermittent fasting).

This is about lifestyle, not rules. If you want to eat a cookie once in a while, go ahead. But how often do you want that cookie? If all you ever eat is cookies you'll be dead pretty quickly and painfully.

I learned first-hand. In March, I went back to eating like crap and my symptoms all returned in full force. So I am going back to correct eating forever, with the occasional day for something interesting.

If all you needed was the basics, there you go. Live long and prosper. If you're interested in some of the science, read-on. If you are REALLY interested in the science, buy both books! Amazing stuff.

- [The Ketogenic Bible](https://amzn.to/3dNP1F9), by Dr Jacob Wilson & Ryan Lowery PhD(c) *Affiliate Link* ((Very science-heavy))
- [It Starts With Food](https://amzn.to/3bL1Q0O), by Dallas and Melissa Hartwig *Affiliate Link* (Chock-full of science but in a very laymen's level easy read sort of way).

***********

### Keto Basics

- [The Ketogenic Bible](https://amzn.to/3dNP1F9), by Dr Jacob Wilson & Ryan Lowery PhD(c) *Affiliate Link* ((Very science-heavy))

Keto, Ketogenesis, Ketogenics refers to the process the body undergoes when breaking down fat and using it for fuel. The process creates Ketones.

There are two fuels the body can use.

1\. **Glucose** (derived primarily from sugar/carbs)

2\. **Ketones** (derived from burning fats).

#### What are ketones?

The body actually thrives when it uses **Ketones** as the primary fuel source and **Glucose** as a supplementary fuel.

**Your body was created to burn fat**, but we've so screwed up our fuel-system that we are mal-equipped for fat burning. We need a hard reset (re-becoming fat-adapted) in order to help our bodies remember how to function, restore hormone and gut health, and create a balanced immune system; all of which reduces systemic inflammation which is the cause of most disease in the West.

Most of the things you eat in a modern western diet are comprised of these Sugar and Carbohydrates. Not all "carbs" are bad,  especially if they come from fruits and veggies for example. However, most grains break directly down into glucose to be used as a form of fuel.

Although the science is now pretty clear that a fat burning ketone inducing diet would be better for performance and health, most doctors seem to be stuck handing out guidelines created decades ago under false pretenses. **The American Food Pyramid, for example, was based largely on the faulty work of Doctor Ancel Keys, in the 1950's**. He performed a correlation study between fat and heart disease and concluded that fat caused heart disease and therefore people should eat low fat. It's a reasonable conclusion, it's just wrong. And these two books firmly put that myth to death. In fact, it was his recommendation and the resulting food pyramid that caused the obesity epidemic in America.

Every component in your body requires fuel. Every organ, muscle, heart, brain, all of it. Each of these to varying degrees can run on either Glucose or Ketones.

We find, though, that the body only produces Ketones in a low-glucose environment. However, it can synthesis glucose from proteins even in a low-glucose environment. The body prefers ketones, especially in the heart and brain as the primary fuel. Glucose is for short term bursts of energy. Ketones are what the body was meant to thrive on day-to-day.

#### The Problem with Glucose:

A high-glucose body produces unhealthy gut bacteria, immune over-response, systemic inflammation, and host of hormone break-downs. Many (*most*) diseases are either directly linked to high glucose levels or further harmed by them. Diseases such as cancer, diabetes, gout, high blood pressure, heart disease, down to even ADHD can be directly linked to Sugar, Grains, and Glucose. Other serious genetic diseases, such as Parkinson's and Alzheimer's can be made worse by a high-glucose diet.

*Fun Fact: Alzheimer's is so closely related to Glucose, it could be called Diabetes Type III. It's essentially the brain's break-down of it's ability to handle Glucose. Increasing Ketones actually gives an Alzheimer's patient increased length and quality of life. *

Even Traumatic Brain Injury, especially when caused by repeated blows from high-contact sports, can benefit from a Ketone Rich diet. The brain becomes insulin-resistant in head trauma and ketones can bypass this and feed the brain the energy it needs to heal or slow down degradation.

In Short, switching to a Keto/Whole30 Lifestyle could save you \$1000,000s in medical costs, decades of pain (physical and emotional), increase your quality of life and quality time with loved ones, and even prevent your family from suffering at your pre-mature sickness and death. It's not a small thing to decide what food to feed the machine you were given to live inside of. It was meant to operate a certain way, anything outside of that is destructive in countless ways.

**Cancer**: Cancer is basically a normal cell that has malfunctioned. The Cancer Cell thrives under a high-glucose / low oxygen environment. One of the single best things you can do to prevent cancer or give your body the best chance of fighting cancer is to remove Glucose from your diet as much as possible, increase Ketones, and increase the intake of oxygen (through various means). Cancer cells can use Ketones but they do not use them efficiently. Even taking Ketone Supplements may act as a therapy to enhance your ability to fight cancer.

#### Going Keto

There are several ways to induce Ketosis (the body's creation and use of Ketones, breaking down fat and using them as a primary fuel source). The way it was first discovered was through Fasting. Fasting induces Ketosis and is still a legitimate way of increasing Ketones. But not a sustainable way. Along with this, some have adopted Intermittent Fasting (not eating for 12-18 hours, and eating all foods within certain hours, say noon to 8pm). This brings us to Cycling. The most common form of Cycling is going Keto M-F and Carb Loading on Sa and Su.

The problem with intermittent fasting and cycling when heavy carbs are still present is that the body doesn't regain Ketosis until Thursday with this cycling. Similar issues arrive with intermittent fasting. You will see results, but the results will be limited.

Diet-Induced Ketosis (Keto Diet) is eating in a way that induces a constant or near-constant state of Ketosis. The numbers vary based on individual needs, but generally fall around 60-80% Fat, 10-20% Protein, and 5-10% Carbs. Give or take. There's a handy calculator at [Ketogenic.com](https://ketogenic.com/).

*******

### Whole30 Basics

- [It Starts With Food](https://amzn.to/3bL1Q0O), by Dallas and Melissa Hartwig *Affiliate Link* (Chock-full of science but in a very laymen's level easy read sort of way).

**This section is long**

#### The Whole30 Overview:

The basics of the food recommendations in this book look a lot like The Paleo Diet (caveman diet) with some influence from Ketogenics as well; and some of the research from the Paleo system was included in the Whole30 book.

However, they are not the same in one fundamental way. The Paleo Diet primarily looks at what foods were available to our ancestors. This book does not.

Instead, this book looks at:

**1. Science:** The science of how the body works at fundamental, scientific, mechanical levels... what things interact with what other things, how hormones and gut health function with food to repair or damage the body. And then makes reccomendations about food based on how that food intereacts.

**2. Self-Experimentation:** all the generalities in the world can't tell you how your VERY complex system, structures, and genes will react to similar inputs. Using a very specific plan, you can experiment with food to determine what the right balance is for you.

#### Oversimplifying the building blocks of the body's functions:

**Micronutrients** are minerals and vitamins.

**Macronutrients** are Proteins (good), Fats (good, surprised?), and Carbohydrates (good in SMALL quantities from good whole-food sources, generally bad in our current food climate from highly over-processed packages foods full of grain and sweeteners and preservatives).

**Calories** are irrelevant; mostly not something to consider on a Whole30. The make-up of those calories is what matters. If you are eating the right things, you'll become satisfied or satiated and you won't overeat. Calorie counting becomes irrelevant.

#### Your Brain on Food (Satiety, Satisfied, Full)(Carbs/Sugars vs Protein/Fat):

In laymen's terms: Carbohydrates are Sugars. It's more complicated than that but roll with it for most of the important stuff below, because they essentially become each other interchangeably and that's bad in our current food world, in developed countries.

Your body wants to burn fat!

By page 43, my mind was already blown:

> *"To begin with, a constant excess supply of carbohydrates will tilt your metabolic "preference" toward burning what's most plentiful -- sugar -- when fuel is needed. If there is an overabundance of sugar, the sugar takes precedence over fat as a source of energy in many metabolic processes, and stored fat doesn't get burned for energy. If less fat is being burned for fuel, then it accumulates and the body fat levels tend to increase"*

Not only does fat not get burned; but, excess carbs get converted into fat, which is where MOST of the fat in your body is coming from. That's right, your bread is making you fat, not your butter and oil.

#### In ancient times, our brains developed (*or were created*) to understand food we found in three ways:

**Sweet**: (safe source of energy)

**Savory/Fatty**: (safe dense source of calories)

**Salty** (a means of conserving liquid), also known as electrolytes.

As it turns out, the Bible held this secret all along. The verse has a double meaning. It speaks of words spoken but it also speaks of the literal tongue.

> *The tongue has the power of life and death, and those who love it will eat its fruit. [Proverbs 18:21](https://biblehub.com/proverbs/18-21.htm)*

These told us which foods were nutritious for us, before the industrial revolution. In nature, sweet tastes come from seasonal raw fruit, rich in vitamins and minerals and phytonutrients. Today, food scientists have created Franken-Food that is sweeter than nature and totally void of all of those things.

#### You need to understand "satiated" or "full".

***MAJOR KEY: Prime Rib vs Oreos***

**Prime Rib** is a protein and fat, the body reads this information and says "we're being nourished with the stuff we need" and as you eat it, you become "full" or "satiated".  This fullness is the body's way of saying you've been nourished and it puts on the brakes.

**Oreos** provide no nourishment. There are carbs/sugars but no nourishing ingredients the body needs. Therefore, the body never signals the brain that "we've been nourished, enough". It's a no-brakes food. So you want the tenth as much as the first. Meanwhile, you are dumping sugars into the system.

#### You're Hormonal!

There are four major hormones (there are many, but these are the main four you need to know):

**Insulin: Building and Storing** -- It unlocks cells and tells them to store or release (fat, proteins, and carbs(sugar)).

Carbs can be stored in the liver and muscles to a limited degree (90 minutes of intense workout worth). Otherwise, the sugars in the bloodstream must be used or stored elsewhere. If these are full, it converts the excess sugar into a chain of three carbs created a fat called "triglycerides" which store in the body and create blockages in the arteries.

**Leptin: Energy Balance --** Leptin tells the brain what to do with storage. Low leptin tells the brain to tell the body to be less active and eat more. High leptin tells the body "we're full, burn the energy and don't eat so much". When the sugars are out of control in the body, the brain can be so overwhelmed with other commands that it cannot hear Leptin's screams. Meaning, the body is fat but the brain said "eat more, conserve energy" because it thinks leptin is low when it's high.

Type 2 Diabetes is created by diet. Building on everything said before, pages 47-49 break down the exact science. Essentially, Leptin resistance tells the brain to keep eating. We've become depending on empty No Brakes sugar foods that don't satiate, so we keep eating. Cells are full and can't take any more carbs/sugars so they start to resist Insulin's instructions to store more. The pancreas is flashing red because sugars are high, produces more insulin cramming even more into the cells until they basically die or become stressed. Insulin production eventually brakes down completely, and now you have to use a needle to get your insulin, meanwhile, the real problem "satiation" still hasn't been solved and stuff is still breaking down and getting worse with or without your needle poke daily.

And this brings us to...

**Glucagon: Energy Access --** Unlocks the cells and tells them to release the stored energy when energy demand is high, often as a result of high energy output (exercise) or hours without food "fasting". Intake protein, chronic stress, and low blood sugar can release this hormone. Elevated levels of insulin and fatty acids (those triglycerides) will slow down the release of this hormone.

If insulin is the air conditioner, cooling down the too high blood sugar levels, then Glucagon is the heater, warming up adding more blood sugar from stored fats and stored glucose.

As long as blood sugar is high, and insulin is high, Glucagon either won't be produced or things will be stored faster than it can unlock them. The body remains essentially deaf to this hormone as long as insulin is chronically high from too many "No Brakes Sugar/Carbs".

**Cortisol: Stress Hormone --** Plays a key role in salt metabolism, blood pressure, and immune function. High Cortisol for an extended period can suppress the immune system or cause prolonged inflammation. Prolonged stress causes higher Cortisol levels.

The killer component is that Cortisol breaks down Glucagon and promotes insulin resistance and tends to elevate leptin levels.

**Note**: Cortisol can also be produced in moderate levels just by "daytime" things. Screens at night can prolonge this hormone messing with sleep. Turning lights and screens off will help lower Cortisol at night.

Chronic Stress (under sleeping, over-exercising, prolonged psychological stress) creates chronic Cortisol levels. When these stresses come from low intake (fasts and reduced-calorie diets), these can create "emergency" scenarios eroding muscle while preserving fat. Which is why Calorie Restricted diets rarely lead to fat loss long term.

#### Your Gut Is Leaking: Gut Health / Leaky Gut

Keep this section short, bottom line, your intestines are the primary place food is absorbed by the body. They are designed to allow good in, and keep bad out. As your intestines are overwhelmed with bad, a bunch of stuff that shouldn't be in your body gets in. This creates inflammation and immune issues.

Good and Bad Bacteria -- In the gut there are a "flora" of good and bad bacteria. The bad stuff causes havoc, the good stuff acts as a combination digestion agent and protective barrier. A healthy bacteria grouping will feel good. An unhealthy bacteria grouping leads to bloating, gas, nausea, and a host of other things such as infection and inflammation.

#### Immune System / Inflammation:

Inflammation is your body's response to infections or damage. If anything is in your body (like the stuff you overwhelmed leaky gut allowed in) that doesn't belong there, your body will be overwhelmed with fighting it.

Inflammation is fine when it's short term and localized (you stub your toe, your body goes to fixing it).

Inflammation is not fine when it's long term and whole-body (due to chronic toxic conditions).

When your body isn't fighting an infection or repairing major damage, it's doing minor repairs. But if it's overloaded with chronic inflammation, it's less able to handle both the normal repairs and the injury/infection. This is the reason that injury is taking so long to heal.

#### What not to eat! Whole30 Food Standards:

There are four food standards that any food must meet to make it on the approved list, according to this book.

1.  **Promote a healthy psychological response** (make you feel full, satisfied, and promote brain health). AKA: Does not promote mindless over-consumption.
2.  **Promote a healthy hormonal response** (Insulin, Leptin, Glucagon, and Cortisol, all functioning accurately).
3.  **Support a healthy gut** (the right things are being let into the system, the wrong things are being kept out, no leaky gut).
4.  **Support immune function and minimize inflammation.**

The following items are considered to violate one or more of the food standards previously mentioned. It's important to note, this list is (a) the list of items banned during the Whole30 fasting diet, which is thirty days without any of these things and (b) can be reintroduced in small quantities to test your reactions to them, keeping in mind they still violate the food standards and should only be reintroduced with the full understanding of what they are and are not to your body.

If you chose to reintroduce them, small portions are still recommended.

In other words, after the fast and after your body is fully re-set, have a cupcake... just don't have ten and don't have one every day. You decide how often is too often.

The following DO NOTs will indicate which of these four Food Standards the category violates. After reading the full chapters, there's potential they all violate all of them, but they only categorized the ones that demonstrate beyond a doubt they violate one or more of the standards.

#### The following are on the DO NOT CONSUME list (and associated food standard):

**Sugar, Sweeteners, Alcohol (1, 2, 3, 4)**

**Seed Oils (4)**

**Grains, Legumes, Even Peanuts and Soy (1, 2, 3 4)**

**Dairy (yes, cheese and organic and raw dairy too) (2)**

*Good News Side Note: Before they tell us the reasons all these things are bad; they give us a little hope. They're not saying we can't ever have a cupcake, pancake, cheeseburger, or Red Wine/Beer again. They are saying, that once we've completed the re-set of our body, we may want to limit how often we allow these things back into our system. How often will be up to us. But if we allow it often enough to re-build dependency we'll erase all the hard work we did of re-setting the system.*

#### Sugar, Sweeteners, Alcohol (1, 2, 3 4)

First on the list of banned items is Sugar. It fails all four standards. It's empty of any nutrition. It promotes over consumption, unhealthy hormonal response, destroys gut health, and is a primary cause of immune deficiency and inflammation.

As stated in the summary... In nature, Fresh Fruits give us a sweet taste, which our brain is designed to recognize as a reward. This is so that we will instinctively know these are a good source of phytonutrients, micronutrients, and minerals. Sugars (table sugar, honey, stevia, all of it), instead, super-normally over activate that reward center like a drug. Simultaneously, the sweet taste that's supposed to be an indication of nutrition is a lie. There are zero nutrients in this sweetness.

Because there's no satiating component, these foods with no-brakes prompt overconsumption, which leads to carbohydrate reliance, insulin resistance, leptin resistance, bacterial imbalance in the gut leading to permeability, which leads to immune issues and systemic inflammation. It's a complete breakdown of your entire bodies function.

**Sugar: may as well be labeled poison.**

Artificial Sweeteners, do not just include Equal and Sweet'N Low. They also include anything else you think you're going to use as a substitute. Stevia, Agave, Honey, Molasses, all of it. In standard 1, Psychological Response, we learned that artificial table sugar was sweeter than fruit producing an unnatural reward reaction in the brain without containing any of fruits positives (minerals, phytonutrients, and micronutrient vitamins). Well... Equal is 200-300 times sweeter than table sugar and Splenda is 600 times sweeter. These create the same negative reward response without nutrition in the brain, but even more.

Making matters worse, when you're body and taste buds are used to sweeteners, fruit isn't sweet by comparison. The apple, strawberry, all of it, is bitter or bland. Yet your body should react positively to fruits, they are a source of nutrition. Once you've removed all artificial sweeteners, you're tastes will re-adjust and find fruit to be the reward it was designed to be.

**Alcohol (1, 2, 3, 4) --** Alcohol has no redeeming health qualities. Period. Alcohol has twice as many empty calories as sugar; therefore is at least twice as dangerous. It's also a neurotoxin, causing actual brain damage (short term/long term, deepening with use).

*Myth: Red Wine is good for your heart.*

*Fact: Red Wine as trace amounts of Resveratrol, but only trace amounts. It would take 80 bottles in one sitting to get a "dose" of the substance worth considering. And it hasn't been proven in humans. You'd get more of this substance from eating a handful of grapes as most of it comes from the skin anyway.*

#### Seed Oils (4)

Polyunsaturated Fats (PUFAs) are on of the general categories of fats, including Omega-3 and Omega-6 fatty acids. Omega-6 can be healthy in small amounts. But PUFAs give us an overdose of these fatty acids. It's now looking like an over-intake of PUFAs play a significant role in inflammation disorders.

Unlike a cold-pressed Olive Oil, these oils are often processed under heat, pressure, bleached and put through chemical solvents. By the time you get the bottle, you've got a form of Franken-Food.

External Oxidation: These oils have a tendency to break down and form free radicals, a process known as oxidation or "going rancid". They are so unbalanced, they begin this process with even moderate amounts of heat or light. So just sitting on the store shelf, in the bottle, this process has already begun. The oil is partially rancid before you open the bottle. Under the stress and heat of cooking, these oils breakdown further.

Internal Oxidation: Inside the body, the oxidation process actually continues and accelerates. Since these types of fats end up becoming part of the literal cellular walls, they are like building cells with termite ridden wood. They continue to break down, increasing cell instability.  This then promotes system inflammation.

High-Oleic Oils: they try to sell certain safflower or sunflower seed oils as high-oleic. These are still highly processed and do not compare to Cold-Pressed Olive Oil. Not even in the same category.

**BANNED OIL LIST:**

Canola (rapeseed), Chia, Corn, Cottonseed, Flax (linseed), Grapeseed, Hemp, Palm Kernel, Peanut, Rice Bran, Safflower, Sesame, Soybean, Sunflower

#### Grains & Legumes (especially Peanuts and Soy) (1, 2, 3 4)

The general nutritional recommendation of this book do not include any kind of grain. No breads, cereals, pasta, rice, not even gluten-free grains or pseudocereals like quinoa. Not even "whole grains". Everything you've been told by doctors, food pyramids, and the government is a lie.

**Survive vs Thrive**, big difference: Every ancient society has a form of grain, even "healthy" societies high in the Asian mountains. But this is about a readily available source of carbohydrate energy. It's not about thriving, but about surviving. They survived by adapting to these. That doesn't make them healthy, or good for thriving.

**Grains** (a form of grass) primarily involve eating the seed of the plant. The endosperm is the carbohydrate source you're eating. The bran is the cover. The germ is the part that actually grows into a plant. During processing, refined flour removes the bran and germ. Refined grains lack most of the nutrients but still contain all the calories.

So use Whole Grains then, yes? No. Whole Grains (not a regulated term, could mean anything) as defined by the actual whole grain, nothing stripped away, contain high amounts of Phytates (anti-nutrients) that actually prevent your body from getting a hold of the nutrients in them. So whole grains may contain more nutrients than refined grains, but they are no more accessible than if they weren't there.

**Whole Grains** are not more nutrient-dense than fresh fruits and veggies. In fact, Fruits and Veggies give more minerals, vitamins and yes more FIBER than grains. There's literally nothing in a grain that a salad wouldn't give you more of and the salad would be bio-accessible.

Note: The Glycemic Index (GI) is a lie also. Although it's true that blood sugar doesn't "spike" as quickly with whole grains. You are still loading empty (nutrient-poor/nutrient inaccessible) carbs into your system. You're still creating a system that prefers carbs over fats and proteins, leading to insulin and leptin resistance, leading to inflammation.

**Gluten**: Grains contain large amounts of "Prolamins", a type of protein. Gluten is a type of Prolamin. All prolamins are resistant to digestion (often impossible). They also are known to knock out the protective structures in your gut barrier, allowing themselves (and other bad guys already in your gut) into the body, triggering an immune response. This immune response can be so wide-spread, it has been known as a "Gluten Allergy" triggering immune weakening and inflammation.

Gluten-Free: Even gluten-free grains and non-grains (like quinoa) are likely to contain inflammation triggering proteins.

**Legumes (3, 4)** -- Beans, peas, lentils, and peanuts (not an actual nut). First, these must be prepared properly to make the carbohydrates inside accessible to the body. They come with many protective barriers. They do not contain a significant amount of nutrient value of fiber (as compared to veggies). They aren't worth it, and may have issues.

The Magical Fruit -- These are not absorbed properly in the small intestines, leading to being fermented inside the body. They become food for the bad bacteria. This leads to gas and bloating. Feeding bad bacteria leads to a reduction in good bacteria. This leads to poor gut health.

**Soy -- Is a source of phytoestrogen,** or Plant-Estrogen (female sex hormone). Your body can't tell the difference. So consuming large amounts of soy is basically like taking estrogen pills. In addition, some of these stimulate estrogen receptors (increase how much is being used in total, not just of the plant version), while some of these inhibit estrogen receptors (decrease how much is being used, not just of the plant version). Depending on the specific tissue, this can lead to all sorts of issues from breast issues, prostate issues, and more. Males, especially, should avoid soy products.

**Peanuts** -- contain a type of protein called lectin. In their raw state, lectins are highly resistant to digestion and even toxic to animals. Unlike other legumes (black beans, for example), peanuts resist these lectins being destroyed by cooking. When they land in your gut, they are hard to digest. They also act as a counterfeit, gaining access past the gut barrier into the body where they are attacked as outsiders by the immune response, leading to inflammation.

*Substitute: For peanut butter fanatics, there is a substitute, Sunflower seed butter is so similar, it might be better. But it's a seed, so still be careful.*

#### **Dairy (yes, cheese and organic and raw dairy too) (2) (*my arch-nemesis*). **

Dairy has a lot of potential issues, but no black and white answers. Let's start with what dairy is and isn't.

**Milk: Perfect --** A mother's milk is designed for her baby to obtain nutrients before they are able to eat whole foods. As such, it is packed with nutrients, growth hormones, and is an energy-dense, hormone delivery system. It's perfect in aiding an infant who needs to double in size and weight rapidly.

**Milk: Imperfect - **Once weaned, the very things that helped us grow become dangerous to our bodies as growth slows. Even children and teens do not need to grow and double in size like an infant.

**Species-Specific**: Cow's milk is designed for baby cows, with specific hormones and nutrients for their body. Humans milk for human babies. This is why "formula feeding", although an acceptable substitute if breast-feeding isn't possible

**Milk Proteins**: Casein and Whey makeup about 80% of the proteins and act as a source of amino acid building blocks that turn into muscles, connective tissues, skin, hair, hormones, and even enzymes. They form part of the structural bone-matrix and teeth. They are a good source of species-specific protein for aggressive growth. However, Casein shares structural similarities to Gluten, and up to 50% of Gluten-Sensitive individuals are also incapable of digesting these proteins. As we age, we are less and less able to use these proteins in our bodies, as we should be weaned from them in early childhood.

**Casein Exomorphines** (casomorphins) are a morphine-like substance derived from casein. They are able to cross the gut-barrier in young mammals and in adults with gut-permeability issues and bind to opioid receptors in the nervous system. It is believed that this is part of the bond created between mother and baby during breast-feeding.

Cheese is made from concentrated Casein, that has blended enzymes that partially digest the casein molecules liberating some of the morphine-like compounds. Is it any wonder that Cheese and Wine (two neuro-chemicals) are often paired together?

Casein, especially aged, causes specific types of immune system reactions called histamine responses (allergies) in many people.

**[Dairy Protein Powders (including Whey Protein)]{.underline}**: often lead to insulin spikes which are promoted to be used post-workout as a way to jam nutrients into cells; leading ultimately to insulin resistance. It would be far more nutrient-beneficial to eat eggs, meat, seafood, post-workout.

**[Milk Sugar (Lactose): is another carbohydrate]{.underline}**. While there is not a large amount of this in milk, a surprisingly large amount of people are sensitive to this sugar which cannot be properly digested. This leads to bloating, gas, and can create an unhealthy balance of gut bacteria.

***Calcium: Three Dairy Calcium Fallacies***

**1. Building strong healthy bones depends only on calcium.**

Calcium is important. Likes bricks to a building. But equally important are Vitamins C, D3, K, Magnesium, and Phosphorous.

**2. Your calcium intake is the only thing that matters.**

*Fun Fact: The USA has the Highest instances of Osteoporosis in the world, and the highest calcium intake.*

If your hormones are off and you hare systemic inflammation, your bones are going to have huge issues anyway. Get hormone balance and reducing systemic inflammation are priority one.

You can have the bone density without the bone matrix/structure and be just as brittle. Supplements aren't helping.

Vitamins D3 and K are Fat Soluble, low-fat diets are actually increasing bone deficiencies.

Phytates (anti-nutrients) from Grains, Legumes, Stress, and Aging all work against calcium absorption.

**3. Dairy is the only good source of calcium.**

Most Calcium supplements are non-bioavailable. Your body just can't use them.

**Veggies (such as: Kale, boiled spinach, collard greens, mustard greens, turnip greens, and bok choy) are much more plentiful sources of calcium than milk, and they are BIO-AVAILABLE.**

#### When the body attacks itself:

**Autoimmune Disease**: is essentially where the body attacks itself. I won't try to summarize this whole chapter but it is fascinating. In essence, your poor gut health (imbalanced gut bacteria) leading to gut permeability (allowing stuff that shouldn't be inside the blood/body inside) causes stuff to get into the actual body. The body then attacks these "foreign invaders" even if they are benign (like a stray protein that's undigested). Some of these things (and some more nefarious things) can mimic or look like actual cells

Bottom Line: A leaky gut lets partially digested food where it doesn't belong. Causing an immune response.

Eating the wrong foods causes a cascade failure of the entire body's systems. Gut Health, Hormone Balance, Immune Response, Inflammation, are all directly tied to Glucose and Ketones. Almost everything we deal with in America, every "lifestyle" caused disease, can be directly linked to being caused by or worsened by too much Glucose and not enough Ketones and poor gut health.

***********

### **Personal Testimony: It Works!**

In 2014, I went on a Green Juice Only fast after watching "Fat, Sick and Nearly Dead" the documentary. In only one week, my life-long bout with headaches, neck pain, and bowel issues disappeared. They only returned when I went back to eating. But knowing I can't live on only Green Juice, I gave up following that rabbit trail. Two friends tried to tell me about grains but I didn't listen, I wish I had.

After losing my wife to health issues in June 2018 that were theoretically preventable; also myself being put on three blood pressure meds, getting gout, and, being fed up with not feeling like I did back on that juice fast years ago\... I decided I want to "get healthy" and "eat better", but when I stopped to think about it, I had NO IDEA what that actually means.

To make matters worse, I went to two doctors and they just told me to eat more veggies and less fats, cut out sugars and processed flours, switch to low fat and whole grains... and suggested I see a dietician.

Half of that was good advice and half AWFUL advice.

I asked for the science of food and I got blank stares and shrugged shoulders.

They could not point me to even a book on the subject. So I went looking.

I don't plan meals. Ever. I mean.... Ever. If you give me a recipe... I WILL change it by the time I'm done cooking. I flow, ad-lib, riff, make music in the kitchen. Therefore, I am completely disinterested in the latest fad diet, and I don't want a cookbook with recipes.

I need to understand what food is, how it works in the body and the science behind "healthy".

Once I get the building blocks, I can start to make better choices in the moment as I'm riffing in the kitchen.

So I started reading.

I found two books that complement each other well. Some of the advice between the two conflicts, but if you get your head wrapped around what science they are reviewing and what things they're not considering, it all makes sense.

- [The Ketogenic Bible](https://amzn.to/3dNP1F9), by Dr Jacob Wilson & Ryan Lowery PhD(c) *Affiliate Link* ((Very science-heavy))
- [It Starts With Food](https://amzn.to/3bL1Q0O), by Dallas and Melissa Hartwig *Affiliate Link* (Chock-full of science but in a very laymen's level easy read sort of way).

I did a strict Whole30 in January. For thirty days (01/02-01/31), I eliminated 100% of all Grains (wheat, rice); Added Sweeteners ( No Sugar, Stevia, Agave, Honey, Nothing); Dairy (everything, cheese, all of it); Legumes (including anything with Soy or Peanut); and I also eliminated most oils from the house, replacing all oils with Coconut Oil, Avocado Oil, and Olive Oils.

In place of this, I ate three solid meals per day as described above. The first meal within an hour of waking. The exact content is irrelevant, so making the switch from calling it "breakfast" to calling it "Meal 1" really helped me mentally. Steak and Veggies cooked in coconut oil and Avocados make a great Meal 1. So does four eggs with veggies and guac.

Throughout January (01/02-01/31) I ate this way. In February, I added one food group (Grain, for example) at each meal for one day, then went back to Whole30 for two days. The goal is to test my body, see what it's responding negatively to.

I discovered that Dairy is my mortal enemy. Almost every symptom I ever had returned on Dairy day. So can I eat it? Sure. Should I eat it? Only if I want to suffer later that day.

My constant bowel issues, gout, headaches, and sleep issues vanished by the first week on Whole30. My issues almost completely returned on Dairy day, so that was a huge find for me. I also found that even without dairy, adding a lot of grain and sugar back during March caused a lot of old issues to come back.

I plan to eat a modified Whole30/Keto lifestyle for the rest of my life. Sure, I'll still make room for an occasional cookie and ice cream, cheeseburger, and a good donut. But I need to reset my system and keep it operating at peak efficiency so it can handle the (very seldom) infrequent indulgence.

If you read this far, Bravo! Email <me@darrellwolfe.com> if you'd like to talk about your food journey.
