---
title: 'Widow Brain: Why do I feel so crazy after loosing my Spouse?'
date: '2020-03-08T21:25:00.0010000+00:00'
draft: false
categories:
  - 'Musings'
---

<div>Question:&nbsp;</div><div><br></div><div>After loosing my Spouse (or parent, sibling, fiance, boyfriend/girlfriend, child, etc.); I experienced a time where I couldn't think clearly, my mind was foggy, I couldn't remember simple things, like why I came into a room... Is this normal? Or am I crazy!?&nbsp;</div><div><br></div><div>Answer:</div><div><br></div><div>I won't pretend to be a scientist, but I've read a lot of material going through grief.&nbsp;</div><div><br></div><div>Here's what I found out:&nbsp;</div><div><br></div><div>This is COMPLETELY normal. It's even got a name in the rooms I am in, "Widow Brain".&nbsp;</div><div><br></div><div>When you've built a relationship with another person, that person has become associated with established pathways in the brain's neural network.&nbsp;</div><div><br></div><div>Their absence creates a disconnection or cognitive dissonance. What should be isn't happening anymore, and the mind must completely rewire for a new normal.&nbsp;</div><div><br></div><div>The closer they were, the more integrated they were to your daily routines, the closer your intimacy and connection was, the more foggy you will feel. Because that is new neural pathways that have to be established.</div><div><br></div><div>This rewiring process is called Grief. You can get help processing through qualified grief counseling, books, healthy community, friendships, going through belongings, finding new patterns, and a thousand other helpful tips.&nbsp;</div><div><br></div><div>The bottom line, is that you've become an emotional amputee. You're missing a limb you once had.&nbsp;</div><div><br></div><div>Amputees are often asked to scratch the new nerve endings at the new stump with a variety of materials (soft, hard, scratchy smooth, cold, hot, etc) in order to teach the brain there are new nerve endings. This helps alleviate phantom limb syndrome.</div><div><br></div><div>So the more activities you can engage with to help you process this new normal, the better chance you have of gaining a new mental equilibrium.&nbsp;</div><div><br></div><div>Clean out their belongings, you won't feel ready, go slow, but do it. Take down "our" stuff and find new "me" stuff. Keep sentiments in a box or display, but start making OUR space YOUR space again.&nbsp;</div><div><br></div><div>Get qualified grief counseling, so you can go through targeted exercises that help you process and integrate those experiences.&nbsp;</div><div><br></div><div>Try new things,aybe things you always wanted to do but couldn't or were too afraid to try. Join a class. Pick a new hobby. Take a small trip. Get into a new group. Attend a theater show or play. Pick up an instrument or art or craft.... try things.&nbsp;</div><div><br></div><div>You won't keep or even like all of it. The point is to do things to exercise the new reality, build new pathways.&nbsp;</div><div><br></div><div>Start small. Do one thing today. Put away one draw. Take down one photo. Go on one walk.&nbsp;</div><div><br></div><div>When you're overwhelmed, which Widow Brain will ensure you will be, stop. Take a nap. Do something tomorrow.&nbsp;</div><div><br></div><div>Expect the first x-period of time to be insane. You've experienced a trauma. It's okay to acknowledge it as trauma. You need to heal.&nbsp;</div><div><br></div><div>Eventually, keep trying things.&nbsp;</div><div><br></div><div>Keep going.</div><div><br></div><div>Reach out when you'd rather hide.&nbsp;</div><div><br></div><div>NO HIDING is still the key to healing after trauma too.&nbsp;</div><div><br></div><div>I hope that helps.&nbsp;</div><div><br></div><div>#Selah&nbsp;</div><div><br></div>