---
title: 'Are you being Christ this election season?'
date: '2020-11-14T17:36:00.0020000+00:00'
draft: false
---

<br />
<div>My prophetic calling is to challenge assumptions and thoughts that keep you from growing in Christ.</div><div><br /></div><div>When I speak to my Left friends, I challenge their fear or anger at Trump. Not only is he not that bad, he’s actually done some really important things.&nbsp;</div><div><br /></div><div>When I talk with my Right friends, though, it is my job to challenge THOSE assumptions. Trump is not Jesus. He’s not even Peter. He might be Simon (before he got the call to follow). Trusted sources say he got saved and he’s a baby Christian, but that’s not validation that he’s a “Man of God” like a seasoned minister. If anything, he’s a King Darius... a SECULAR king that was kind to God’s people.&nbsp;</div><div><br /></div><div>Despite my advice, God brought him into office despite all odds. I didn’t vote for him in 2016 or 2020. But I was forced to acknowledge God’s hand has been all over him all four years.&nbsp;</div><div><br /></div><div>That being said, God may have brought him in to do what he did and leave. It may our may not be the will if God to have him another four years. We’ll see when the results are final.</div><div><br /></div><div>I’m worried, though, about how many are treating this election as important for all the wrong reasons. I feel the American Church has taken on an idol of the Republican Party, in place of Jesus himself.</div><div><br /></div><div>I don’t care who’s in the white house the next four years. I care about what The Church is going to either win hearts or push them away... I’m afraid The Church isn’t acting like Christ this season... that’s the tragedy of 2020. Not a virus, not an election, but the war for the HEART of The Church.</div>
<br />
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
