---
title: 'Valentine''s Day, Holocaust, Jesus, and Love'
date: '2020-02-14T15:40:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8644593079427470725'
blogger_filename: '/2020/02/valentines-day-holocaust-jesus-and-love.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

This is my second Valentine's Day without my late wife.&nbsp;<div><br></div><div>It's funny because I never really liked the holiday, we never really did much with it. Now I find myself wishing I had someone to give something to; celebrate it with. For a long time I was a server in restaurants and it was an "all hands on deck" day. So we just never had any particular reason or unction to do much with the day.<div><br></div><div>It's funny, you find yourself missing strange things, things you didn't think twice about before loss.</div><div><br></div><div>I spent the morning reading about how people either lost or gained faith during The Holocaust. The intense human suffering that accompanied those days was enough to drive many away from God but it drove others to Him.</div><div><br></div><div>I myself find that my experience with loss and grief left me with a deeper and more profound love for my God, and a more wholeistic theology. Gone are the days from my time in one particular brand of Christianity, that said serving God meant everything would make me prosperous, healthy, and whole. Those ideas were NOT wrong, just incomplete.&nbsp;</div><div><br></div><div>Sometimes you pray and she dies anyway.&nbsp;</div><div><br></div><div>God absolutely snuggles you close in those seasons, walks through the darkness with you, and he does eventually use that raw material to heal and mend the brokenness into a new masterpiece. But you may not get the outcome you originally prayed for. He does not make that promise.&nbsp;</div><div><br></div><div>So today, Jesus is my Valentine. He taught me that love isn't about candy grams, or date nights, though it could be expressed in those things. He taught me that love is not about some magical life where everything gets better and better, sunshine and roses every day.</div><div><br></div><div>Love is about getting down into the muck and mire with those who are hurting, being the good Samaritan and paying a price to help them heal.&nbsp;</div><div><br></div><div>Love is laying your life down on behalf of another.&nbsp;</div><div><br></div><div>Love is laying aside your own wants, desires, "needs", even hopes... And listening to your kids talk about school, art, arguments, YouTube, games, whatever interests them. It's about being present in those moments, "paying" attention (your attention may cost you something you wanted to be doing), so that you communicate they have value to you.</div><div><br></div><div>Love is being there for friends who need you, but, also allowing them the space to have pain that may drive change. Love may mean NOT jumping in to rescue someone from the pain that could ultimately drive them to become a better version of themselves.</div><div><br></div><div>Love may mean holding your tongue when someone says something you disagree with, because your goal is to pray for them and win hearts not arguments.</div><div><br></div><div>Love may mean saying no to things you want today because you have a higher calling and purpose ahead of you, and it's time to lay aside temporary things for better and lasting ones.</div></div><div><br></div><div>Love is.</div><div><br></div><div>Selah.</div>