---
title: 'Sometimes.... I don''t believe God but I still believe him.'
date: '2020-04-13T13:29:00.0010000+00:00'
draft: false
categories:
  - 'Musings'
---

<div>One thing we should always be, as Christians, is honest... And HONESTLY... Do you believe Jesus when he says this:</div><div><br></div><div><div><i>If you ask me anything in my name, I will do it. <a href="https://bible.com/bible/59/jhn.14.14.ESV">John 14:14 ESV</a></i></div><div><br></div></div><div>I have to admit... I don't. Not today. I did. I might again. But I wrestle with this. I prayed and she still died. The bills still go unpaid. The struggle continues.&nbsp;</div><div><br></div><div>Yes, theologically, there's a whole context to this verse and qualifications. I understand that. But it's a little hard to swallow when you're in the middle.</div><div><br></div><div>And that's okay. Walking with anyone is a struggle. It takes time to get to know someone, see their perspective, understand what they mean by what they say. Etc.&nbsp;</div><div><br></div><div>The best way to walk with Jesus is to be HONEST.</div><div><br></div><div>NO HIDING</div><div><br></div><div>Just tell him. That's a big claim, I don't know if I believe that. Tell me more about that. Let him speak to you.&nbsp;</div><div><br></div><div>And let it take a lifetime if needed. I've been struggling with this verse my whole life. That's okay.&nbsp;</div><div><br></div><div>Relationship is built in the struggle to hear and see.&nbsp;</div><div><br></div><div>What are you not believing today?</div><div><br></div><div>Tell Him. He can handle it.&nbsp;</div><div><br></div><div>#Selah</div><div><br></div><div><br></div>