---
title: 'Look for possibility, opportunity, and influence today.'
date: '2020-04-03T12:16:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3631686949538701173'
blogger_filename: '/2020/04/look-for-possibility-opportunity-and.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

Said this to a friend today and it's worth saying again!<div><br></div><div>I guess we'll see what happens in the rest of this crazy year. We're only to April 3. So much has already happened. I think great things are coming too.<br></div><div><br></div><div><div>Innovation.&nbsp;</div><div><br></div><div>Rekindling the desire (throughout the world) for real human contact.&nbsp;</div><div><br></div><div>Apps like Meet-Up will explode when things return to normal.&nbsp;</div><div><br></div><div>Things will start moving again.</div><div><br></div><div>When the dust settles, jobs will come back, people will spend, but some will be added to the widow ranks. Some people will start new careers, forced out of work. Some people will be worse for the wear but many will see gains.&nbsp;</div><div><br></div><div>When the dust settles, some in denial will see if was way bigger than they realized.&nbsp;</div><div><br></div><div>But many will see opportunity.</div><div><br></div><div>There will be negative and positive fallout.&nbsp;</div><div><br></div><div>We just have to look for the positive, the opportunity, the possible.&nbsp;</div></div><div><br></div><div>#Selah</div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div>