---
title: 'The journey starts with the first step.'
date: '2020-03-04T14:49:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1205626131499473677'
blogger_filename: '/2020/03/the-journey-starts-with-first-step.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

<div>Last night I did a thing.&nbsp;</div><div><br></div><div>I took a two hour class on Voiceover work. It was very interesting and I got some great tips on using my Tone, Pitch, and Pace with more purpose to clarify my message.&nbsp;</div><div><br></div><div>What I got most was confidence to try things.</div><div><br></div><div>For decades I talked about what I was GOING to do.&nbsp;</div><div><br></div><div>She said she worked in banking for years taking about how she was GOING to get into radio. But finally her mom asked her when she was going to DO it.&nbsp;</div><div><br></div><div>"You already know what it feels like not to do it..."</div><div><br></div><div>So she did. A year later, she got her first gig. Her mom passed away a few months later, but got to hear her on the radio.&nbsp;</div><div><br></div><div>Ironically, I work in banking, so this was an interesting example.</div><div><br></div><div>I've been TALKING about Blogging, Podcasting, and being my own boss, even talking about publishing books and doing Voiceover work, for over a decade. But short of infrequently posting here, and starting several websites I never finished. A half written novel... I've not taken many actions. Definitely not consistent ones.</div><div><br></div><div>It's time to show up every day, and take one action. Record one segment of a podcast. Work on one section of a novel. Take one class on voiceovers. Take actions. See where they lead you. Pivot when needed.&nbsp;</div><div><br></div><div>You never know where you'll end up, it starts with one step.</div><div><br></div><div>#Selah</div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div>