---
title: 'The gods have gone silent...'
date: '2021-01-20T16:32:00.0050000+00:00'
draft: false
---

<p>A short story clip...</p><p>&nbsp;</p><p>"The gods have gone silent", Edvard said, as he lit his long handled pipe. <br />&nbsp;<br />"The gods?" Villiam scorned. He adjusted his armor and tightened his belt. "There haven't been any gods in ages. That superstitious nonsense went out of fashion long ago." <br />&nbsp;<br />The moon glinted off of Villiams' platinum breastplate, making his face look more pale than usual. <br />&nbsp;<br />Evdard's dark hands were nearly invisible this time of night, but next to the pompous Villiam's shining attire he could make out the scar running down the back of his hand. A reminder of the time he met the gods first-hand and lived. &nbsp;<br />&nbsp;<br />"Belief in the gods may have gone out of fashion..." Edvard dragged on his pipe, letting the smoke curl into the night sky. Turning to look him straight in the, Edvard said: "... but I tell you, the silence of the gods is a dangerous omen. They're up to something. Displeased. Or preparing for war. Or who knows what. But it's a sure sign something is lurking." <br />&nbsp;<br />"You smoke too much," Villiam replied. &nbsp;<br /><br />
<br />
<br />
<br />
<br />
<br />
</p><div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
