---
title: 'Gifted to Minister: a reflection paper for The Spirit Formed Ministry (BIBM1302ONL2)'
date: '2021-04-29T06:11:00.0040000+00:00'
draft: false
categories:
  - 'Studies'
---
Gifted to Minister:

As a prophetic storyteller and teacher

The King's University, Southlake, Texas

The Spirit Formed Ministry (BIBM1302ONL2)

Professor: Dr. Leah Coulter

May 2, 2021

By Darrell Wolfe

**I read 80% of each text, possibly 90%*

### Gifted through the Holy Spirit

Jesus' mission as the Anointed One (Messiah/Christ) was to invade earth with the Kingdom of God (Luke 4:18-19).[1] When the Kingdom is present, it results in freedom, healing, deliverance, and good news about God's favor towards all people. Jesus accomplished his part of the mission and received all authority in heaven and on earth. He gave the pseudo-kingdom of darkness a fatal blow and introduced another development in the on-going competing-kingdoms saga. Upon his ascension, he handed the mission to his followers (Matthew 28:18-20). The mission never changed. Using the anointing (empowering) of the Holy Spirit (with which Jesus was anointed), Christians are to invade earth as ambassadors of the Kingdom of God until it fills the whole earth. That mission results in the same freedom, healing, and deliverance as they tell unreached people how passionate God is about them.

As part of this empowerment, the Holy Spirit came giving gifts to men (Ephesians 4:8). The key "gifts passages" describe the various ways God works among his people (1 Cor 12:8-10, 28; Rom 12:6-8; Eph 4:11; and 1 Peter 4:10-11).[2] It is commonly accepted to refer to these as the Office Gifts, Serving Gifts, and Charismatic Gifts.[3] However one classifies them, the theme of these passages list ways in which God empowers his people to be a blessing to others. The New Hope Oahu website lists 25 spiritual-gifts for which one can be tested.[4] These lists are not comprehensive (the only ways he works) but are examples of ways he has worked in and through his believers to accomplish the work of God on Earth. The following are take-aways from this course, in the form of key ideas found in the texts.

*Doing is key*. "As Christians, we are often in danger of becoming theoreticians rather than practitioners of the Kingdom".[5] It is far too easy to sit behind a keyboard, study the Bible, and tell people what it says; without ever really doing any of it. If Christians fallback into defenders of theology, they may find themselves on Facebook arguing theology rather than connecting with hurting hearts and leading them to God's heart for them. This type of activity "wins" the argument while destroying relationship. In essence, they become enemies of the kingdom they claim to defend. The first step in walking out the kingdom, is being mindful that it is a real kingdom to be walked-out, not just an ideology to defend or argue. This requires taking the time to develop real relationships with real human beings in real life, inviting them into your sacred space and loving them with His heart. It requires getting dirty, being with messy humans in their pain, and loving them well.

            *God-Connected-Relationship is key*. The Triune nature of God is at its core, relational. We are invited into the eternal pre-existing relationship with Father, Son, and Spirit. This relational core invites us to shift our thinking. Rather than doing things for people on God's behalf; we do things for The Father which people benefit from. Too often, detached from relationship, Christians can go about working "for God", while not being in relationship "with God". Rather than doing things for God according to some natural agenda or plan, Christians must do what The Father is leading them to do.[6] When Kingdom Ambassadors are in relationship with The Father, their work will flow from that relationship. To do life that way, requires hearing God.

*Hearing God is key*. As Christians tap into relationship, he empowers them to see what he is doing and participate. Without hearing the Father's heart, seeing what he is up to in the life of a fellow human being, one is left to quote scriptures and principles at them. To hear God, one must be tuned-in to the voice of the Father, spoken through his Word (Jesus), by the Spirit. Unless they are Spirit-Led in an encounter, they are left to work on God's behalf with mere natural efforts. This natural-only form of Christianity results in the famous "Romans Road" tracts; which have some benefit but ultimately lack much transforming power. Part of hearing God is speaking what God is saying into the lives of His precious people. Examples of this can come through Prophecy, Words of Knowledge, and Words of Wisdom. Essentially, one hears God and speaks His heart to His people. He also may lead his ambassador to do other things, which may be outside their comfort zone.

            *Getting uncomfortable is key*. Dawkins spends most of his text providing examples of moments when God used His people to walk into unusual or uncomfortable situations and bring healing, restoration, and break-through into the lives of hurting humanity. In one instance, a woman was prompted to do a handstand in a gas-station convenience store and the cashier gave their heart to Jesus.[7] Christians must be willing to step outside of their comfort zone if they want to see God move. This is, in part, because God will show up as the only one who could have arranged it (rather than His agent relying on talents, evangelism training, or tract-handouts).

            *Loving His people is key*. The members of the Body of Christ are "Ambassadors of His Presence", for His purpose, to His people.[8] In order to walk that out, Believers must have more than a dogged determination or right theology; they must have LOVE. This present darkness is icky, messy, and sometimes working with broken people is not fun. The Kingdom of God is "now and not yet". Christians today live in the Radical Middle between the empowering of the Holy Spirit (today) and the future Kingdom where sin will no longer exist.[9] Dawkins calls this tension The Upside-Down Kingdom.[10] Prostitutes, Witches, and Atheists have all found themselves weeping with Robby Dawkins not because he provided an impenetrable argument for the "rightness" of Christian Theology but because he allowed himself to be a conduit through which they could meet The Father for themselves. A Kingdom Ambassador must love someone first, in order to be willing to put down their own defenses and love their enemy; or better, realize the enemy is not the human standing before them but the spirit influencing that human.

### Gifted to Minister as a Team

*The APEST Model*: For most of church history, church leaders were considered the "Minister". When one went to seminary it was to "enter the ministry". This is antithetical to the biblical design of God for his body. The Apostle, Prophet, Evangelist, Shepherd, and Teacher (APEST) were given by God to equip the body to minister, not to do all the work themselves. While each person (even APEST Leaders) is a minister outside the church building, Church Leadership Gifts (APEST) are intended to be equippers, not ministers (Ephesians 4:11-16).[11] To make this a reality requires rethinking the church model; transitioning from a one-man-show to a team-based model where every member of the body is a "full-time minister".[12] To make this transition, those in leadership must develop the gifts of their people, develop future-leaders, and develop teams of leaders.

*Developing Gifts*: Each individual in the leaders' circle of influence is gifted. It is the leaders' responsibility to discover the person's gifting and bring it out of them, while also building their character. As they grow into a heart for God, developing God's character inside of them, their gifting will become self-evident. One may look at a tree and see a tree, another may see a group of trees and call it a forest; but one who is focused on bringing out the best in others is like one who sees the chair, coffee table, or decorative artwork inside of the tree that has yet to be released.[13]

*Developing Leaders*: As a leader develops the gifting of others, some will begin to show a gifting for leadership and shepherding their own people. As these individuals are developed, they will develop others. Godly leaders are Dream Releasers. They look for opportunities to develop the gifting in others. Leaders who are insecure will horde power and influence (K.M. Weiland refers to this as the King's Shadow, when leadership is turned self-protective of its own power).[14] Groups led by insecure leaders will be anemic and weak; while groups lead by Dream Releasers will become an ever-growing self-reproducing body. As a fractal continues to duplicate into ever more complicated shapes, a body of Dream Releasers will be a body of leaders developing leaders into continuous growth.[15]

*Developing Teams*: As the body grows from a natural result of people's gifting being developed, teams of people will be the natural byproduct of this fractal growth. Teams; however, require organization and direction. Building teams starts with picking the right people for the right positions. Being aware of someone's DESIGN helps the leader put them into positions in which they are gifted to excel. Once you begin to organize teams and get everyone on the same mission, the teams themselves can become self-replicating. Cordeiro provides tools which can assist the leaders in creating as many layers of structure as needed for the size and complexity of the body while maintaining the vision and compass of that body.[16] Once the vision and structure is in place, the body can become self-replicating.

The Body of the Anointed One will be at its healthiest when each member supplies its part. To see that kind of culture, requires APEST leadership doing their part to find and develop the giftings in their people and raise up fellow APEST leaders who will in turn develop the giftings in their people. As a fractal grows indefinitely into ever more complicated designs based on the same structures, this model provides the environment in which the body can grow unhindered and fully equipped.

### My Partnership with the Spirit

**Spiritual Gifting/DESIGN:** In Doing Church as a Team (Chapters 4 through 6), there are tools provided for understanding one's gifting and DESIGN.[17] The following are the results of my self-assessments.

1.     1. SPIRITUAL GIFTS: The following are my top (four) results, each scoring 12 on the assessment.

- *Pastor/Shepherd*: At the age of ten, standing on the platform of my Dad's empty church, by myself, I felt a strong calling to "Pastor", and I ran hard from that calling until 2018 when I finally decided to follow God's call. Despite myself, I have been a "Shepherd" in every role I served in corporate America. Even while avoiding "Supervisor" roles, my team-mates, friends, and even strangers on the street came to me for prayer, advice, and counsel. I would mentor/disciple and shepherd them into a closer relationship with God and help them find inner healing. Even my superiors would end up becoming my sheep, asking me for advice for situations I was technically not supposed to know about. I always provided them with a Priests' Confidence. I have seen first-hand that God will not relent on his calling and holds each of us accountable for that calling despite our compliance. I look forward to seeing how this Shepherd role will play out in the future.

- *Teaching*: I am best known among my friends as a storytelling teacher. Whether I was helping people build credit scores, fix identity theft, providing relationship advice (using Dr Henry Cloud's material), or expounding on God's Word, teaching was a theme for me. My own boss asked me to stop giving customer's lectures and to go start a Podcast. I have a knack for making "complicated things simple". I usually make them complicated for myself, them simplify them, before I reach the simple stage. In this same vein, my writing has always been superior to my peers and I feel my teaching gift is at its highest expression in the written word. Pride in my superior knowledge has been my Achilles Heel, and an area of constant development.

- *Words of Knowledge & Prophecy*: I scored evenly on these, but I see them as the same thing anyway. There has always been a prophetic bent to my personality; seeing visions and dreams even as a child. However, I largely avoided this part of my spiritual life, afraid of it (to be frank). In recent years, I began dipping my toes into these waters. I was surprised to see how readily God used me in these areas. In 2019, God said: "Your Teaching gift will become subordinate to your Prophetic gifting". I have seen glimpses of that starting to work its way into my day-to-day life, but it is still in its infancy. I am focusing on the phrase: "Be Still, Be Led" to develop this area in my walk. I have also struggled with being sensitive to when and where to use the things I see.

2.    2. DESIGN: Using the DESIGN acrostic, from the text, I can say the following:[18]

*[Desire]{.underline}*: My passions revolve around research, writing, storytelling, and teaching. I have started over 40 blogs with various purposes (most never came to fruition). I have a novel that is half complete. Often after teaching the same material repeatedly, I write it down so I can refer people to the article instead, then invite them to ask questions after reading.

*[Experience]{.underline}*: My experience in "church" has led me to largely reject the models we use in the west today. My experiences in Alcoholics Anonymous and recovery programs have given me a passion for broken people. Working with fellow Widows via Facebook has given me a unique insight into the unmet needs of that community. The themes of my experiences revolve around meeting the "de-churched" in their pain, answering their honest questions, and leading them into healing and freedom with God.

*[Spiritual]{.underline}* [*Gifts*]{.underline}: Pastor, Teacher, and Prophet are all symbiotic callings. I take what God says and deliver it to people in ways they can hear, with fresh ears.

*[Individual Style]{.underline}*: I am an INFJ with Clifton Strengths in Intellection, Ideation, Learner, Achiever, and Input. I am a walking brain, and require massive alone time to read, research, study, and write. While I genuinely enjoy teaching and mentoring, the finer points of "relationship building" are often lost on me (unless I've studied it in a book). I partner with Relational people to help me in those areas. I am starting a small-group with just such a person.

*[Growth Phase]{.underline}*: While my scholarly biblical acumen surpasses even some of the pastors I have served, my character development may be that of a young adult or teenager. The final stages of my freedom from bondages long-held date back only to January 2017 through November 2019. I feel the acute need for a mentor to help me take the next steps before I ever attempted to take the reins of leadership myself.

*[Natural Abilities]{.underline}*: Until now, I used my talent as a Sound Engineer to hide in the audio booth and stay away from the platform. While I am not ready to start teaching, I could begin looking for ways to assist pastors and teachers in their work. Also, God has been dropping hints that I should start to take my blogging from hobby to semi-professional; including the addition of a Podcast.

**Ministry Dreams:** Ultimately, I see myself as a teacher/writer. When asked "What would you do if anything was an option?", I would be something akin to a C.S. Lewis or a Dallas Willard. I would prefer the classroom to the pulpit; though guest teaching in churches is not out of the question. I see myself using the Shepherd gift with students and small groups; rather than as a Senior Pastor. Finishing this degree is part of that preparation.

**Risk of Ministry:** For me, facing the risk of ministry means (1) overcoming doubts by doing it anyway, (2) getting used to being uncomfortable for the sake of loving God's people, (3) purposefully investing in loving people the modern church often treats as "other" (as spiritual pariahs).

**Personal Transformation**: I am scared to start the Podcast, but it is on my to-do list for this summer between semesters. I am partnering with someone gifted in Relational strengths to help me step outside my comfort zone and develop real-world relationships with broken people (as opposed being online only).

### Bibliography

Averill, David Taylor. "PREACHING APEST: OBSERVING A SERMON SERIES, BASED ON EPHESIANS 4, AS A MEANS OF BEGINNING TO PLANT A VISION IN A LOCAL CONGREGATION." Pittsburgh Theological Seminary Barbour Library, 2019. https://www.academia.edu/39181904/PREACHING_APEST_OBSERVING_A_SERMON_SERIES_BASED_ON_EPHESIANS_4_AS_A_MEANS_OF_BEGINNING_TO_PLANT_A_VISION_IN_A_LOCAL_CONGREGATION.

Cordeiro, Wayne. *Doing Church as a Team*. Revised and Updated edition. Minneapolis, Minnesota: Bethany House, a division of Baker Publishing Group, 2014.

Coulter, Leah. "The Spirit Formed Ministry (BIBM1302)." Lectures, The King's University, Southlake Texas, Spring 2021.

Dawkins, Robby. *Do What Jesus Did: A Real-Life Field Guide to Healing the Sick, Routing Demons, and Changing Lives Forever*. Minneapolis, Minn: Chosen, 2013.

Jethani, Skye. *With: Reimagining the Way You Relate to God*. Nashville: Thomas Nelson, 2011.

Seamands, Stephen. *Ministry in the Image of God: The Trinitarian Shape of Christian Service*. Downers Grove, Ill: InterVarsity Press, 2005.

*Spiritual Gifts Evaluation/Test*. Honolulu, HI: New Hope Oahu, 2021. https://enewhope.org/resources/spiritual-gifts-test/.

*The Lexham Bible Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott, C., ... Widder, W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham, WA: Lexham Press.* Billingham, WA: Leham Press, 2016. LexhamPress.com.

*The Lexham English Bible (LEB), Fourth Edition*. Logo Bible Software. Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.). Bellingham, WA: Lexham Press, 2010. http://www.lexhampress.com.

Weiland, K.M. "Helping Writers Become Authors - Write Your Best Story. Change Your Life. Astound the World." Helping Writers Become Authors. Accessed April 27, 2021. https://www.helpingwritersbecomeauthors.com/.

### Notes

------------------------------------------------------------------------

[1] *The Lexham English Bible (LEB), Fourth Edition*, Logo Bible Software, Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010), Scripture References from LEB, http://www.lexhampress.com.

[2] *The Lexham Bible Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott, C., ... Widder, W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham, WA: Lexham Press.* (Billingham, WA: Leham Press, 2016), "Gifts of the Spirit," LexhamPress.com.

[3] Wayne Cordeiro, *Doing Church as a Team*, Revised and updated edition (Minneapolis, Minnesota: Bethany House, a division of Baker Publishing Group, 2014), 45--51.

[4] *Spiritual Gifts Evaluation/Test* (Honolulu, HI: New Hope Oahu, 2021), https://enewhope.org/resources/spiritual-gifts-test/.

[5] Robby Dawkins, *Do What Jesus Did: A Real-Life Field Guide to Healing the Sick, Routing Demons, and Changing Lives Forever* (Minneapolis, Minn: Chosen, 2013), 83.

[6] Stephen Seamands, *Ministry in the Image of God: The Trinitarian Shape of Christian Service* (Downers Grove, Ill: InterVarsity Press, 2005), 26; Skye Jethani, *With: Reimagining the Way You Relate to God* (Nashville: Thomas Nelson, 2011).

[7] Dawkins, *Do What Jesus Did*, 75--77.

[8] Leah Coulter, "The Spirit Formed Ministry (BIBM1302)" (Lectures, The King's University, Southlake Texas, Spring 2021), Lecture: SF Ministry Ambassadors F20.

[9] Coulter, Lecture: Bigger Context of Ministry F20.

[10] Dawkins, *Do What Jesus Did*, 55--73.

[11] David Taylor Averill, "PREACHING APEST: OBSERVING A SERMON SERIES, BASED ON EPHESIANS 4, AS A MEANS OF BEGINNING TO PLANT A VISION IN A LOCAL CONGREGATION" (Pittsburgh, Pennsylvania, Pittsburgh Theological Seminary Barbour Library, 2019), https://www.academia.edu/39181904/PREACHING_APEST_OBSERVING_A_SERMON_SERIES_BASED_ON_EPHESIANS_4_AS_A_MEANS_OF_BEGINNING_TO_PLANT_A_VISION_IN_A_LOCAL_CONGREGATION.

[12] Cordeiro, *Doing Church as a Team*, 37--41.

[13] Cordeiro, Chapters 1-6.

[14] K.M. Weiland, "Helping Writers Become Authors - Write Your Best Story. Change Your Life. Astound the World.," Helping Writers Become Authors, Podcast/Blog Post: Archetypal Character Arcs, Pt. 12: The King's Shadow Archetypes, 04/26/2021, accessed April 27, 2021, https://www.helpingwritersbecomeauthors.com/.

[15] Cordeiro, *Doing Church as a Team*, Chapters 7-8.

[16] Cordeiro, Chapters 9-13.

[17] Cordeiro, *Doing Church as a Team*.

[18] Cordeiro, 61--73.
