---
title: 'Who are you praying to?'
date: '2021-04-20T16:48:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4485569286784219293'
blogger_filename: '/2021/04/who-are-you-praying-to.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'Musings'
---

<div>Who are you paying to?</div><div><br></div><div>In a recent discussion about praying to "the saints" in Catholic tradition, some responded by saying they only pray to Jesus. While this is not incorrect and certainly the Trinity is co-equal and ONE so impossible to fully seperate, it is not technically accurate either.&nbsp;</div><div><br></div><div>Jesus said to pray TO the Father, IN Jesus name. Not to Jesus.&nbsp;</div><div><br></div><div>To be technically accurate, Jesus provided the way for us to come to the Father directly. We do not need for anyone to be a go between, even Jesus. Now, He is our Mediator of the New and Better Covenant. It is by His blood we come. And at the end of the day, it's pretty much the same. But if you think you don't need the saints to take your prayers to God the Father because Jesus does it... You're still only mostly there.</div><div><br></div><div>John 16: 23In that day you will ask nothing of me. Truly, truly, I say to you, whatever YOU ASK OF THE FATHER IN MY NAME, he will give it to you. 24Until now you have asked nothing in my name. Ask, and you will receive, that your joy may be full.</div><div><br></div><div>The "in my name" is descriptive not prescriptive.&nbsp;</div><div><br></div><div>When one does something in the name of, it's as a representative of.&nbsp;</div><div><br></div><div>So as a representative of Jesus, coheir, Jesus is my brother, first born of the dead. I come TO the Father, as a representative ambassador of Jesus on Earth, to do Kingdom business. I need nobody to take the request to the Father for me, because Jesus has paid the price.&nbsp;</div><div><br></div><div>I stand before the Father directly. Nobody takes my prayer to him, I do it myself. Not on my works, but on Jesus' blood.&nbsp;</div><div><br></div><div>"In Jesus name" isn't a way to end a prayer, it's a reality to be walked out. I am an ambassador of God, for the Kingdom of God, I present requests to God the Father directly. I do so as one bearing the name of Jesus.</div><div><br></div><div>It's not telling us to use the phrase 'in Jesus name' as a tagline to end prayers. It's telling us that we are Image Bearers who bear the name of Jesus. Whatever we ask for is in the context of Bearing Jesus' name, and doing His Kingdom business.</div><div><br></div><div>You're welcome to add Jesus name to prayers as long as you understand what he really meant by the instruction.&nbsp;</div><div><br></div><div>Don't get religious about it. Anyone who monitors prayers for forms and formulas is still in first gear as a believer. God's looking for relationship not religious exercises.&nbsp;</div><div><br></div><div>All I was after in this post was technical accuracy.&nbsp;</div><div><br></div><div>In light of the original discussion. Some folks are of the impression that they don't pray to saints who take the prayer to the father, they take it to Jesus who takes it to the Father. When the accurate understanding is that Jesus made the way for you to take it to the Father yourself, with no middle man, so to speak. It is through His finished work, but, we can come before the Father directly.&nbsp;</div><div><br></div><div><br></div><div><br></div>