---
title: 'The Next Great Awakening is here...'
date: '2021-07-10T13:05:00.0010000+00:00'
draft: false
categories:
  - 'Musings'
---

Just watched Black Widow. Good movie. I think it parallels the church. There are still so many of my friends who think Donald Trump is "God's Anointed" and he's coming back in 2024 to save America. <div><br></div><div>How does one get so twisted in their heart and mind as to believe this? Manipulation. Mind control. They've been sold a lie that there's an enemy that is threatening them and they need to defeat this enemy to "Make America Great Again".&nbsp;</div><div><br></div><div>The problem is, it's just not true. Yes. There are forces at work in world which act against us, especially the people of God. Those forces sit behind the powers of this age. I don't have any issue with their being an "enemy", a vary real one. But, our enemy is spiritual powers and dark forces in the heavenly spaces. Flesh and blood is not our enemy. Joe Biden is not your enemy. Your neighbor who voted for Biden is not your enemy. And America... Hear me spiritual Israel... America is not your citizenship.&nbsp;</div><div><br></div><div>The United States of America has been the best civilization in history, for some. And it's been the worst in history for others. It's done wonderful good, and unthinkable evil.&nbsp;</div><div><br></div><div>This is not our final stop, and America doesn't need to be "Great Again". It never really was. It needs to turn to Jesus, one neighborhood at a time, and experience a renewing of the heart.&nbsp;</div><div><br></div><div>It's ironic, as they rolled the gold statue of Donald Trump into a building last year (or was that earlier this year?), that the church didn't even blink. Nebuchadnezzar has issued his challenge, and the church bowed, instead of choosing the furnace.&nbsp;</div><div><br></div><div>It's not their fault, they're all still asleep. Other Christians are not the enemy, any more than the world of lost and hurting (and hurtful) humanity is the enemy. The church has been so busy hunkering down in our silos for decades, that we never stopped to think about "what if we're wrong"?&nbsp;</div><div><br></div><div>We laughed at people who said "millions of years" because we were so sure the Bible taught us the Earth was younger (it doesn't). We turned off our brains and read the text so "literally" that we became illiterate. We don't even know the difference between a poem, a narrative, a metaphor, and a history.&nbsp;</div><div><br></div><div>We weren't always so illiterate. Christianity founded the sciences of the modern era, it developed hospitals, schools, orphanages. The first church taught the people how to read, so they could read and understand the Tanakh, and eventually the compiled Apostlic writings.&nbsp;</div><div><br></div><div>Our live for the poor and needy ran so counterculture to the world, and ran so deep and consistent, that we changed the world. All while being hunted.</div><div><br></div><div>We upended the Roman Empire in approximately 350 years, and then... We vanished. Why? Because politics. Political power corrupted the church and made her useless.&nbsp;</div><div><br></div><div>It took from roughly 350 AD to 1500 AD (1,200 years +/-) to wake her back up. We've been asking the wrong questions, making the text out to say things it never claimed, but, at least we were waking up.&nbsp;</div><div><br></div><div>From Luther to Azusa Street, we've experienced wake up moments.&nbsp;</div><div><br></div><div>Now we are on the precipice of another... It's time we lay down our dogmatic narrow (and often incorrect) ways of reading the Bible.&nbsp;</div><div><br></div><div>We must wake up to the deep history of our text, become immersed in the mind of its authors and editors, and begin to hear the narrative they've been trying to whisper to us from its pages.&nbsp;</div><div><br></div><div>The Gospel of the Kingdom of God, and Jesus its King, is about far more than we ever knew, of a different character than we thought it was, and far more compelling than we ever dreamed.&nbsp;</div><div><br></div><div>The Kingdom of God has been here, moving, growing, seeping into and changing societies, ever since Jesus arrived. We've been so focused on a false gospel of escapism, that we didn't realize how much it actually affects how we live today.&nbsp;</div><div><br></div><div>The King is coming, it's time to wake up, the Bridegroom returns.</div><div><br></div>