---
title: 'Class Assignment: Gospel Reading: What is "The Gospel" according to Matthew, Mark, Luke, and John'
date: '2021-09-23T03:53:00.0040000+00:00'
draft: false
categories:
  - 'Class Assignment'
  - 'Biblical Studies'
---
*A research project for class. What is "The Gospel" according to these four gospel writers (as opposed to what your church always told you it was)? Let's explore those themes.

### Gospel Reading: Matthew

Darrell Wolfe

Literature, The King's University

Life of Jesus (BIBL-2302)

Professor Jason Moraff

October 25, 2020

#### Questions

1. Lilies of the Field (Matthew 6:28-30). Even Solomon was not dressed like lilies? I get that the point is not to worry. But I feel like there is something I'm missing. How are lilies and clothes comparable? How are Lilies adorned? There is something deeper here. Maybe if I know something about lilies, I could learn something about God's provision?

2. Ch. 8 - I still do not understand why the demons wanted to go into the pigs or why Jesus let them. I have theories, but nothing fully satisfying.

3. Ch. 9 -- How could we retool our churches to be hospitals for the sick rather than just schools for the healed?

4. Ch. 17 -- How often do I look down on "little ones"? Either actual children, finding even my own children annoying or distracting from my "real work". Or spiritual children, those who "know less" than I do? If the least are greatest, am I seeing them through God's eyes?

5. Ch. 25 -- I can't reconcile the 10 virgins. Are they believers? But then they'd all be allowed in? Are they Christians but five of them are in name only? Not really saved? Is this parallel to the one taken the other left Jesus referred to at his coming?

#### Observations

- Matthew 1: Rahab and Ruth were both foreigners brought into the Kingdom of Heaven by forsaking all they had. Tamar and Bathsheba were women who had been wronged sexually. Mary was an Israelite who forsook her future to say yes to God and was perceived by others to be wronged sexually. These five women made the list of Jesus' family[\[1\]](https://draft.blogger.com/#).

- Ch. 4 - Matthew summarizes Jesus' entire life message as: "Repent for the kingdom of heaven is at hand" but not "Repent, receive forgiveness, go to heaven when you die". Matthew 4:17[\[2\]](https://draft.blogger.com/#)

- Ch. 7 - Gentiles come in and sit with Abraham in the Kingdom. Not a new kingdom. Not a different kingdom. We come in; they do not come out. We are grafted into Israel; we are not a separate (implied better) nation. We are part of the same continuous story.

- Ch. 8 - Peter's Mom gets sick even though he is serving Jesus. I guess life still happens when we choose to serve. We are not exempt.

- Ch. 8:20 - Jesus said he had nowhere to lay his head. Spangler and Tverberg pointed out that Jesus would have been an itinerate rabbi[\[3\]](https://draft.blogger.com/#). Therefore, Jesus is not saying he was "poor" he is saying that he was rejected by some of the places he traveled and wasn't accepted into anyone's home (as was the custom).

- Ch. 9 -- Gentile churches today are often no more friendly to the spiritually sick than the pharisees that Jesus was confronting.

- Ch. 10 -- I often hesitate to accept hospitality from those I have served or helped. I think this a challenge for me to allow community into my life. Breathing in and out, I must serve but allow myself to be served (10:10 NLT). On that note, am I more afraid of what people think of me than what God thinks of me? Am I afraid of people and not afraid of God (10:28)?

- Ch. 26 -- Let this cup pass... Even Jesus didn't always "want" to do God's will, but he willed to do God's will. The emotions need not be present for obedience.

#### The Gospel According to Matthew

If gospel means "good news", what was the good news according to Matthew? It was that the old dead religious ways of being were passing away. A new vibrant way of living was among us. Matthew presents a Jesus who is rooted and grounded in the history of Israel's continuing story both in Jesus' own family of origin, as well as his fulfillment of prophecy, and he continues the story in our lives. He summarizes the entire life message of Jesus by saying that he came to preach one message: "Repent for the kingdom of heaven is at hand"[\[4\]](https://draft.blogger.com/#). I once heard a message from Bob Hamp, LMFT, who said that "repentance" simply means to think differently afterward. As such, Jesus began to challenge the minds of all who would listen. He told parables to attempt to alter the way they thought and the way they saw God's heart. He said, "you've heard... but I say...". He demonstrated his authority to challenge the status quo by revealing his power in healing and miracles. In one section, Jesus made a point to say that he was showing he had the authority to forgive sins by demonstrating that authority through healing. Matthew does not tell us of a hero but of the first and best role model. He is inviting us into the story. Jesus not only demonstrated this power in himself alone, but he gave it to his apostles as well. This power was available to anyone who would "have faith". Jesus frequently comments on those who have great faith, little faith, and no faith. He frequently puts the responsibility (good and bad) for outcome back on the receiver, "...your faith has made you whole". The Good News of Matthew is that if we will hear and think differently afterward, we can enter this Kingdom of Heaven now and live a new kind of adventurous life. He goes on to tell us that there are costs and rewards associated with this adventure lifestyle. And then he ends by telling us that we have access to the power of the risen Jesus to go out into the world and make disciples just as he had. I can almost hear him say "Tag, you're it".

#### Bibliography

[\[1\]](https://draft.blogger.com/#) Messiah, Immerse : The Reading Bible (Carol Stream, Illinois: Tyndale House Publishers, Inc, 2017).

[\[2\]](https://draft.blogger.com/#) Hebrew-Greek Key Word Study Bible: Key Insights Into God's Word. NKJV New King James Version, Genuine Black Leather (Chattanooga, TN: AMG Publishers, 2015).

\[3\] Ann Spangler and Lois Tverberg, Sitting at the Feet of Rabbi Jesus: How the Jewishness of Jesus Can Transform Your Faith, Updated edition (Grand Rapids, Michigan: Zondervan, 2018).

[\[4\]](https://draft.blogger.com/#) Key Word NKJV. 4:17

### Gospel Reading: Mark

Darrell Wolfe

Literature, The King's University

Life of Jesus (BIBL-2302)

Professor Jason Moraff

November 1, 2020

#### Questions

1. On its own, the comparison to Jesus as Bridegroom and his men with him not fasting makes sense. I fail to see how the new cloth patching old cloth or new wine and wineskins have any relevance to the question of why his men do not fast. This might be a point where cultural relevance would be at play?

2. Paraphrase: "Jesus climbed into the boat and the wind stopped. They were afraid. They still did not understand the significance of the loaves." How were his disciples expected to connect his ability to multiply food with his ability to stop wind? Should they have observed these as power over the natural order of things?

3. 9:10 -- Jesus's three closest men are asking among themselves what "rising from the dead" means. Considering the rest of the story, it means exactly what it means. How often do we make things too difficult or aloof, when he is really telling us quite plainly?

4. In most instances, Jesus heals a nameless blind person. But here in 10:46 the person is named. It feels odd or out of place compared to other stories of healing. What is naming this person accomplishing? What could his name reveal about him or the story? Is he important in some way in another place? This just stands out to me as a "things that make you go, hmm" sort of way.

5. Ch. 13 -- I am forced to admit that I do not see a "rapture" described in this set of events. I wonder how much we have a proper understanding of what is coming next and what Jesus actually said his second coming would look like (vs what Left Behind said it would be)?

6. My margin notes say that anything after 16:8 may or may not be authentic. This says more about the scholar than the text to me. Maybe I am just missing something about the history of it. Why do scholars find incomplete copies and then use them to doubt the authenticity of the original?

#### Observations

- Throughout Mark, Jesus tells people not to tell what he did for them; and demons not to reveal who he was. This was strange at first until I reached the end. Jesus was, ultimately, crucified for claiming to be the Son of God. So, he kept a lid on this until the time was right to admit it to the leaders at the end. He kept them second-guessing until then.

- 4:24-25 -- In the NKJV, this did not completely make sense. But the NLT Messiah version made more sense. "The closer you listen, the more understanding you will be given". I think this is what classes like this one teach us to do. Listen closer. Listen more attentively. Ask questions. Use the background and history to see deeper into the words. Preparing our hearts to be good soil.

- Jesus is on the way to heal a man's daughter. They are stopped by a woman who had faith to be healed. He calls her daughter. Between the lines, Jairus is still standing there when he said it. Jesus is building Jairus' faith by comparing the daughters of healing. The end of this section speaks about Jesus being unable to do any miracles because of unbelief. These stories juxtapose each other to show that we have a role to play in God's miracles in our lives.

- 9:24 -- "Lord, I believe; help my unbelief." This could be one of the most powerful prayers I pray. Despite decades walking with God and multiple experiences seeing Him show up for me, I continue to doubt he will do it again the next time. I have grown by leaps and bounds, but the tendency to doubt is strong and one I fight constantly. I love how Jesus met the father at his level. He took that seed of belief and used it.

- Ch. 11 -- Jesus shows up, observes, leaves. He comes back the next day and acts. Also, he speaks death to a tree. The next day, his disciples see the effects of that curse. I enjoyed seeing these weave into each other in the same story. Day 1, Day 2. I wonder how often we are rushed into action without taking time to pray? I wonder how often we pray and do not see anything and give up before the miracle comes?

- Roman officers were hardened to crucifixions. It must have been an impressive death scene to make the soldier believe that Jesus was the Son of God.

#### The Gospel According to Mark

According to Mark, this is the story of Jesus the Messiah, Kingly Son of David, and Son of God, who came preaching the Good News of the Kingdom of God. In Mark's story, we see an unlikely king. This man is no military leader or revolutionary. He comes as a Rabbi teaching people to see and think differently, and as a result, live differently. His teaching forces the religious leaders, people, and even his own disciples to think deeper and see things from a new (heavenly) perspective. Jesus comes racing onto the scene with a new style of message and new power to back it up. He heals the sick, casts out demons, and raises the dead. Most shockingly to a first century audience, he also comes forgiving sins. This kingdom, however, is no ordinary kingdom. It is a kingdom that is from above. He tells us that it starts small like a mustard seed and grows until it becomes the largest plant in the garden; possibly hinting at the non-geo-political nature of it. It is as if to say, this kingdom will be a kingdom of minds and hearts, worldview altering, but not one of palaces and policies. He even stops his disciples from fighting for him, which is what most disciples would have been expected to do for the Messiah they were expecting. As if to drive the point of Jesus's heavenly status home, he places the transfiguration and God the Father announcing "this is my Son" at the midpoint (9:7). It becomes the truth upon which the entire story hinges. Then again, at the end, a Roman solider repeats "truly this man was the Son of God" (15:39). This kingdom is lead by a King who conquered death and sits at God's right hand. The book ends by saying that Jesus tells his disciples to go into the world preaching the good news of this kingdom, and he backs it up with signs following. Even though the story is about the Son of God who introduces a new kind of kingdom, this Good News seems far more interested in how we think and live here on Earth than it does in getting us "saved to get to heaven".

### Gospel Reading: Luke

Darrell Wolfe

Literature, The King's University

Life of Jesus (BIBL-2302)

Professor Jason Moraff

November 8, 2020

#### Questions

1. 11:33-36 -- I could conjecture, but I'm still vague on what he means about the light of the eye. When we see but not seeing, but, what's the actual advice or command here? How do I get my eye lit?

2. I found myself making more observations than asking questions today.

#### Observations

- More than any other Gospel, the term "Holy Spirit" comes up frequently. Even before Jesus is born, the Holy Spirit is an active member of the story.

- 4:6 -- Jesus never denies that Satan has the authority to give, only that it was not how he would wrest it from him. Interesting to note when we consider "why bad things happen" on earth.

- Ch. 6 -- I found myself uncomfortable, in light of election season, comparing my attitudes to those Jesus commands. Loving my enemies was not the forethought in my mind, as I prepared mentally for the USA Civil War II.

- Ch. 9 -- How often have I heard one side (Republicans & Democrats) so angry at the other that they wanted to cause physical harm to them or their possessions? Yet, Jesus tells us he is not here to burn the enemy camp down, but to save them. His enemies are not enemies at all, but captives that need Freedom.

- 14:26 -- Makes so much more sense in light of our readings about first century disciples preferring their Rabbi over their own father. This is a cultural reference and amplified (like his reference to not just adultery but even lust is sin).

- 16:11 -- Never noticed this before, if you are not disciplined with your budget and earthly money/income, you will not be trusted with more. Those wanting to serve God must start by getting their own house in order.

- 23:25 -- They were expecting a king to free them from Roman rule. They did not just ask for a murder in place of Jesus (picture of forgiveness of sins), they asked for someone (a rebellion leader) who was more like the image they had of their Messiah. They asked for a false Messiah in place of the real one, one that would mold to their own ideas about what Messiah should be.

#### The Gospel According to Luke

Luke presents to us a very Jewish Jesus, rooted in the history of his people and in prophecy. We are well into the story before the Jesus who ministered for three and a half years is introduced onto the scene. After his victory in temptation Jesus is immediately rejected by his own, a paradox. Throughout his ministry, he preaches the Kingdom of God and heals the sick. He then sends his disciples (not just the 12, but the 70 as well) to do the same. These miracles establish his authority. Luke takes his time, builds the character of Jesus through interactions with various types of people. He also shows us why the leaders of the religious sects of the day hated him so much as to kill him. We see him sit at the table in a Pharisees own house, then condemn the entire group for their behavior. Meanwhile, we see Jesus take pity on the least of those in his midst. He makes a point to observe a widow and comment on her giving, show us that we must serve those we come across on the road who have been abused by others (Good Samaritan). Even at the end, as he is being arrested, we see him healing the ear of his captor. Luke ends with the punchline, as though nothing was understood by the disciples until this very last moment. Jesus had to die and rise again, so that the message of repentance and remission of sins could be taken to the whole world. Luke's Good News is that the Kingdom of God, established and confirmed through signs, results in repentance and remission of sins through Jesus' death and resurrection.

### Gospel Reading: John

Darrell Wolfe

Literature, The King's University

Life of Jesus (BIBL-2302)

Professor Jason Moraff

November 15, 2020

#### Questions

1. 3:18-19 -- Does God send people to hell? God did not send Jesus to condemn the world but to save it. He who believes is saved and does not believe is condemned (for they rejected the answer). What about those who have never heard? They did not reject him, yet. Hm.

2. 4:46-54 -- Jesus is presented with a little girl who is sick unto death, and his response feels dismissive and frustrated? We often paint Jesus as a codependent "Oh, poor baby, I'm coming to the rescue". But really? He was quite harsh at time, to my ears. What could this response teach me about walking as He did?

3. Ch 6 -- Eat my flesh and drink my blood. Why was Jesus so cryptic with his disciples? He practically provoked them to walk away. Why can't God just say things as they are? Why do we constantly have to play guessing games with what God's really saying or doing in our lives? This is a genuine frustration of mine.

4. 11:4 -- So, does God bring sickness into our lives on purpose just so he can show off his ability to heal? That seems cruel. Yet, Jesus only ever healed. He never put sickness on anyone. What else could this be saying, rather than what I am hearing it say?

5. Ch 11 -- Jesus Wept. Why? He already said he knew Lazarus was dead and he was headed to raise him up. He just told Martha that was his intention (though she did not understand him). What would cause Jesus to weep here? Some say he identified with Martha and Mary's pain. That could be true. But as a Widower, as I work with other Widow(er)s, I find myself reliving my own grief process. Could he have had his own earthly father's death in mind as he wept?

6. 12:20-26 -- What does the detail about Greeks asking to see Jesus have anything to do with his "answer" to them?

7. 20:23 -- If I forgive someone's sins, they are forgiven? If I do not forgive them, they are not forgiven? How does this make sense? What does this mean practically for me today?

8. 21:11 -- With a limited number of words, John tells us that there were 153 fish in the net. That is a really odd detail to provide John. Why? My only thought so far, is that it is just another example of this grandfatherly style of John's story.

#### Observations

- John tells us that not about the Kingdom of God, but about our status as Children of God (1:12). He goes on to tell us that we are transitioning from Law to Grace and Truth through Jesus.

- 1:35-51 -- Jesus started his ministry team with one interaction {Andrew and another (John?)}, and then built his team from there. I often wonder how I could ever build a ministry; it sounds so daunting. This tells me, I only have to reach one, then another, and so on.

- 3:14 -- Adam fell to a live snake, Moses lifted up a dead snake, and Jesus became the substitutionary sacrifice to undo all the snake brought into this world.

- Ch 11 -- Two ironies in the Pharisees response. (1) Jesus raising the dead results in their plotting to kill him. (2) The High Priest prophesies the death of Jesus saving Israel, then plots to kill Jesus. His own mouth prophesied but he misunderstood the meaning of his own prophecy.

- 17:15, 21 -- Could these statements affect how we consider politics? We are not to be taken out of the world; therefore, must engage it. The 2020 Christians in the USA are as divided as ever. The world seeing our unity will believe.

- 18:28 -- Another irony, the Priests who sacrifice the Passover lamb every year, are literally sacrificing the true Passover Lamb himself, and they're concerned about getting home and eating the lamb, small l.

- My Bible points out that the Strong's number for "love" is different between Jesus and Peter[\[1\]](https://draft.blogger.com/#). Do you Agape me, yes, I Phileo you. The second time, Agape/Phileo. The third time, Jesus comes down to Peter's level. Do you Phileo me? Yes, I Phileo you. I think Jesus has to meet me at my level more often than I like to admit.

#### The Gospel According to John

As an immigrant grandfather telling the grandchildren and great-grandchildren stories of the old world, John tells the intimate story of his experiences with the great I AM. He seldom if ever mentions the Kingdom of God, preferring instead to point out that "... as many as received Him to them He gave the right to become children of God, to those who believe in His name" (John 1:12). This is the story of the Children of God, and the invitation for all people to become a part of that family. Throughout, John tells details of the land and language to his audience, indicating that they do not already know. This is either because he is writing to a non-Jewish audience or because he is writing after the fall of Jerusalem or both. It is interesting to note that he uses the blanket statement "The Jews" when he is obviously referring to the Jewish leaders such as the Pharisees; presenting a possible line of demarcation between this new broader family (all God's people) and the old one (Just Israel). Yet, the Jewishness of Jesus is imperative to His story as the Passover Lamb. Throughout the story, Jesus shows us His father which is our Father. John gives intimate details throughout the story, as one who was reliving fond yet sometimes dark memories. He refers to himself only euphemistically as the "Disciple who Jesus loved". In doing so, we get to live through John as our surrogate, for we too are the disciple whom Jesus loves today. John makes it clear, beyond doubt, that Jesus claimed to be God/God's son; that Jesus existed long before Abraham was. Yet, this Son of God came to Earth, humbled himself as a man, and walked among us. The word that kept coming to me throughout this Gospel was "Intimate": intimate details, intimate settings, and intimate loving interactions with Jesus. John even chooses to end his tale with an intimate encounter, beachside, where Jesus restores Peter by coming down to his level/ability to Love (Agape/Phileo). Then he signs it with an admission that he was the disciple whom Jesus loved and a first-hand witness to all these things. The Gospel according to John is this: We are all now part of one family, God's family. Any and all who believe are welcome in Father's house. There will be a cost to joining this family, but the cost of not joining is far greater.

#### Bibliography

[\[1\]](https://draft.blogger.com/#) The Hebrew-Greek Key Word Study BIBLE: Key Insights Into God's Word. New King James (NKJV) (Chattanooga, TN: AMG Publishers, n.d.).
