---
title: 'God with Us:  Messianic Promise and the Kingdom of God in  GENESIS'
date: '2021-02-26T07:09:00.0000000+00:00'
draft: false
---
\~\~\~{=html}

## God with Us:

##  Messianic Promise and the Kingdom of God in

##  GENESIS

The King's University, Southlake Texas

Old Testament Survey (BIBL1305)

Professor: Dr. Eugene Chet Saunders

February 28, 2021 By Darrell Wolfe

### Outline

        I

I.    GOD PLANTS A FAMILY IN EDEN (God with Us)

- a.    Adam & Eve are created, planted, and given freedom (Genesis 1-2).

II.    GOD'S FAMILY REJECTS HIM.

- a.    Adam causes The Fall (Genesis 3).
- b.    Cain and God's other divine beings cause havoc (Genesis 4).
- c.    The whole earth is evil, God must wipe the slate clean (Genesis 5-6).

III.    GOD PRESERVES A SEED, PLANTS A NEW FAMILY. (God with Us)

- a.    Noah is preserved as a seed; God plants a new seed (Genesis 7-9:1-17).

IV.    GOD'S NEW FAMILY REJECTS HIM, AGAIN.

- a.    Noah's lineage almost immediately rejects God (Genesis 9:18-29).
- b.    Nimrod builds Babel, Babel rejects God. God must wipe the slate clean, again.
- c.    God destroys the Tower of Babel project, confuses their language, and forces them to spread out (Genesis 10-11:26).

V.    GOD PRESERVES A SEED, PLANTS A NEW FAMILY, AGAIN. (God with Us)

- a.    God takes a seed from the new peoples, Abram, and plants a new family (Genesis 11:27 - 50).
- b.    God builds a covenant mindset into this new line, working with one man at a time. Although other minor characters play roles and the lives of each intertwine and overlap, the broad stories are as follows:
  - i.    Abraham (12 -- 23)
  - ii.    Isaac (24 -- 26)
  - iii.    Jacob/Israel (27 -- 35)
  - iv.    Joseph (36 -- 50)

SUMMARY: Genesis is the first step in a new family for God, the rest of the biblical narrative (Exodus through Revelation) will play this story out on a cosmic scale.

### Introduction

The phrase "In the beginning" may be among the most quoted verses of the Bible. The book of Genesis sets the stage not just for the Pentateuch (first five books of the Bible) but for the entire biblical narrative. God created the earth, placed mankind inside, and gave them "all that they needed".[\[1\]](https://draft.blogger.com/#_ftn1) The fall of man delayed the original plan (God with Us) but could not stop it. To this day, God revives that original plan into the hearts of any who will receive Him. This paper provides a survey of the background for Genesis and its God with Us theme.
Authorship and Recipients

The first five books of the Bible, known as the Pentateuch, are commonly credited to Moses (though some debate this assumption).[\[2\]](https://draft.blogger.com/#_ftn2) The authorship of Moses (with some editorial updates) is established by statements made in the five books, statements made by other prophets, and the cohesion of the finished work.[\[3\]](https://draft.blogger.com/#_ftn3) The format of the Genesis narrative follows a structure known as a toledoth formula ("This is the account of...") and it is organized into sections. This indicates that at least portions of the history may have been written before Moses and he (or whoever the compiler was) acted as a divinely inspired editor splicing the story into a coherent narrative.[\[4\]](https://draft.blogger.com/#_ftn4) The Pentateuch is a single narrative ("a literary whole") broken into five parts.[\[5\]](https://draft.blogger.com/#_ftn5) Therefore, to understand Genesis one must read all five books to see the whole story. The initial audience of the book of Genesis were the Israelites of the Exodus/Wilderness period under Moses. Given that Moses hoped (and had God's promise) the nation would survive long after him, it is reasonable to assume he also knew the story would be told for generations to come.[\[6\]](https://draft.blogger.com/#_ftn6)
Date

The exact timing of the events of Genesis (as they relate to the modern calendar) is unclear. While some scholars attempt to use a precise dating system showing that individuals (such as Abraham) lived during specific dates; others use a relative scale to show a range of dates he might have lived.[\[7\]](https://draft.blogger.com/#_ftn7) Given the quagmire of debates on chronology, the patriarchs (Abraham, Isaac, Jacob, and Joseph) would have lived sometime between 2000 to 1600 BC (BCE).[\[8\]](https://draft.blogger.com/#_ftn8) The book of Genesis is typically attributed to the work of Moses (the indicated author of Exodus); therefore, the date of the initial compiling of the text would be during the Exodus/Wilderness period, between 1500 to 1200 BC, depending on whether you adhere to the early or late date theory.[\[9\]](https://draft.blogger.com/#_ftn9)

### Purpose and Background

*God with Us*: The covenant is the basis for understanding how Israelites viewed their theology and identity and Genesis provides the background and basis for covenant concepts.[\[10\]](https://draft.blogger.com/#_ftn10) Genesis begins with the story of God's plan to create a covenant family on Earth. Eden was God's first attempt to be "God with us"; he lived with his man (Adam) until the fall. Dr. Michael S Heiser argues that Eden was the seat of God's divine counsel and that Gardens and Mountains served as representations of divine abodes in the minds of the Ancient Near East.[\[11\]](https://draft.blogger.com/#_ftn11) Therefore, the concept of "Eden" plays recurring roles throughout the rest of scripture as a reference to God's house, divine council chamber, and access to his presence. Whether in Eden, visiting Abraham's tent, or in the Temple itself, the plan remains consistently: God with Us.

*Cultural Context*: A twenty-first-century reader is wise to remember that the Bible was written for our collective benefit, but it was not written to the modern reader. The Bible was written to Israel in the Ancient Near East (Old Testament) and Second Temple (New Testament) periods.[\[12\]](https://draft.blogger.com/#_ftn12) Therefore, if we are to properly understand the text, we must properly understand the context of the text. This includes understanding the culture in which the original author and audience lived and wrote. The lead character of the Genesis narrative is Abram (Abraham) who came out of ancient Mesopotamia. The story of Abraham and his family comprises most of the book, except for a few side stories and a precursor to the generations preceding him. A study of texts from Mesopotamian and Egyptian cultures contain parallels and similarities to the texts of the Hebrew Bible. The Ancient Near Eastern materials can help the modern reader understand the culture and mindsets of the characters, authors, and earliest recipients of Genesis.[\[13\]](https://draft.blogger.com/#_ftn13)

*Creation vs Science*: One common source of frustration for modern readers of Genesis is the creation account. Using other Ancient Near East texts, Dr. John Walton provides a convincing argument for understanding the creation texts, not in terms of "material origins" such as atoms and molecules; but rather, in terms of "functional origins" (the roles created things play in the function of the universe).[\[14\]](https://draft.blogger.com/#_ftn14)

*The Old Testament (Genesis) and Christianity*: Approximately 32 percent (one-third) of the New Testament is composed of quotes and allusions to the Old Testament. This makes studying the Old Testament vital to the Christian.[\[15\]](https://draft.blogger.com/#_ftn15) A lack of close reading in the Old Testament results in false dichotomies (Law vs Grace).[\[16\]](https://draft.blogger.com/#_ftn16) It was through God's work in the Old Covenant that he began to make himself known to humans and helped them create Sacred Space so he could be close to them.[\[17\]](https://draft.blogger.com/#_ftn17) In Enoch, we see a glimpse of God's intent, he loved him so much that he took him (God with Us).[\[18\]](https://draft.blogger.com/#_ftn18)

### Themes in Genesis

*The Kingdom of God in Genesis*: While the Kingdom of God is not expressly mentioned in Genesis, the seeds of the kingdom are laid here. The realm of mankind attempted to set up their own kingdom apart from God at Babel, the Earth's first kingdom.[\[19\]](https://draft.blogger.com/#_ftn19) God rejected the nations at Babel and made a direct promise to Abraham, "...kings shall go out from you."[\[20\]](https://draft.blogger.com/#_ftn20) Abraham and his line dominated their territories, and made covenant agreements (as co-equals) with kings in Canaan and Egypt.[\[21\]](https://draft.blogger.com/#_ftn21) God renewed his promise to Jacob that "kings shall go out from your loins".[\[22\]](https://draft.blogger.com/#_ftn22) By the end of Joseph's story, he was second only to Pharaoh himself.[\[23\]](https://draft.blogger.com/#_ftn23) Jack Hayford observes that the founding precepts of the Kingdom of God are found in Genesis one; God is the ruler of all and he has created mankind to share that domain with him.[\[24\]](https://draft.blogger.com/#_ftn24)

*God's Faithfulness Despite Man's Unfaithfulness*: The New Testament does not have a monopoly on the love of God for fallen people. The narratives of Genesis show the genealogy of Abraham as a descendant of Noah; however, they do not show any hint that the faith of Noah continues in an unbroken line to Abram (Abraham).[\[25\]](https://draft.blogger.com/#_ftn25) He is presented as an ordinary man from the early Mesopotamian culture of Ur (a descendant of the tower builders). God would reveal himself by several names, including YHWH and El Shaddai.[\[26\]](https://draft.blogger.com/#_ftn26) In this, God shows that he is faithful when mankind is not. Abraham is an example of God loving mankind "while we were yet sinners" (Romans 5:8).

*Messianic Promise / Image Bearers*: God created a planet especially suited for his new Image Bearers, and the rest of the Bible is his attempt to live with his Image Bearers.[\[27\]](https://draft.blogger.com/#_ftn27) When the divine Image Bearers disconnect from believing loyalty to God and attempt to cover their own shame, God responds by providing them with a more sufficient covering than they could provide for themselves (skin for fig leaves). He promised a day when the Seed of the woman (Jesus) would crush the serpent.[\[28\]](https://draft.blogger.com/#_ftn28) When the earth had become so corrupt that God required a reset, he preserved one Image Bearer to keep the promise of the seed of woman alive.[\[29\]](https://draft.blogger.com/#_ftn29) When Noah is established on the renewed Earth, he is told about the sanctity of life and punishment for taking life. Buried in this command that lifeblood would be required of animal and man, is another whisper of the one who would shed his blood as the lamb to take the sins of the world.[\[30\]](https://draft.blogger.com/#_ftn30)

When the renewed mankind rejected God's will, he divorced the nations and turned them over to other gods; then began fresh with a new man called Abram and built a nation from him.[\[31\]](https://draft.blogger.com/#_ftn31) Abram was promised that all the seeds of the earth would be blessed through him (an indication of The Seed of Eve who would come through his line).[\[32\]](https://draft.blogger.com/#_ftn32) The Apostle Paul tells us that this message "all nations will be blessed through you" was God preaching the Good News of Jesus to Abraham.[\[33\]](https://draft.blogger.com/#_ftn33) Later, Abram meets Melchizedek (Malki-Tsedeq) King of Salem (later renamed Jeru-Salem), and Priest of El-Elyon, (God Most High) who would be a type of shadow of the Davidic King (Jesus) who would come as Priest and King.[\[34\]](https://draft.blogger.com/#_ftn34) God leads Abram on a life-journey that culminates in the promised son, Isaac.

The covenant God establishes with Abram requires circumcision; another example of covenant ratified in blood.[\[35\]](https://draft.blogger.com/#_ftn35) By providing Abram with a son in his old age, YHWH makes Sarah laugh. Yet, after she was in her old age, king Abimelech wanted her for his wife (a sign God had done something miraculous in her). This miracle sets the stage for young Mary to believe that she will bear God's son many centuries later, for God can do anything through a woman, why not her?[\[36\]](https://draft.blogger.com/#_ftn36)

Then Abram (Abraham) was tested to lay his son on an altar and sacrifice him to God. As of this point, there is no law of Moses yet. In Abraham's day, human sacrifice to the gods was a standard practice of the neighboring Canaanites.[\[37\]](https://draft.blogger.com/#_ftn37) Yet, God uses this practice not only to test Abraham's loyalty (after seeing so many reject him) and teach Abraham about his covenant faithfulness; but also, to lay another foreshadowing of the blood sacrifice to come.[\[38\]](https://draft.blogger.com/#_ftn38) As they walk, Isaac notices the fire and wood but that there is no lamb. Abraham replies, "God will provide himself a lamb...".[\[39\]](https://draft.blogger.com/#_ftn39) As a result of this encounter, Abraham calls the place "YHWH will see/provide" (often transliterated Jehovah Jireh; YHWH Yireh).[\[40\]](https://draft.blogger.com/#_ftn40) It is one of the strongest foreshadowings of the work of the Seed of Eve to come found in all of Genesis.

Throughout the lifetimes of Isaac and Jacob, we see YHWH continue to be "God with Us" in their lives. Then in Abraham's great-grandson Joseph, we see another glimpse of Messianic Promise. Joseph becomes the first Israel-born prophet, predicting a famine for Pharaoh. Although his brothers sold him into slavery (a type of death) and told his father he died; God used this to deliver the entire family from near death in the famine. The evil planned by the brothers; God intended for the salvation of many people.[\[41\]](https://draft.blogger.com/#_ftn41) Joseph became a type and shadow of one "murdered" by his brothers to become the savior of them.

### Conclusion

Jesus is the ultimate divine Image Bearer, and as such, the ultimate example of having dominion, being fruitful, and multiplying.[\[42\]](https://draft.blogger.com/#_ftn42) As Emanual, he is God with Us. He is the fulfillment of the veiled promises and shadows first laid down in Genesis. Through a close reading of Genesis, we can see the heart of God has not changed from day one. He is a God who ultimately wants to be "God with Us". In Genesis, we see a picture of imperfect people pursued by a perfect God. Abraham "believed God and it was credited as righteousness".[\[43\]](https://draft.blogger.com/#_ftn43) This was before any law, and even before circumcision. The basis of faith in God has never changed. Our modes of operation, our theological perspectives, and our styles of life and worship have changed, grown, morphed, and evolved as God continues to reveal himself in new ways. However, the God of Adam, the God of Abraham, the God of Joseph, is the same God who gave us Jesus, Peter, and Paul. He is the God of Abraham, Isaac, Jacob, Jesus, and (insert your name here).

### Bibliography

Gore, Charles, Henry Leighton Goudge, and Alfred Guillaume, eds. A NEW COMMENTARY ON HOLY SCRIPTURE INCLUDING THE APOCRYPHA. Vol. 1, p. iii. New York, NY: The Macmillan Company, 1928.

Heiser, Dr. Michael S. "The Naked Bible Podcast." The Naked Bible Podcast. Accessed January 30, 2021. https://nakedbiblepodcast.com/episodes/.

---------. The Unseen Realm: Recovering the Supernatural Worldview of the Bible. First edition. Bellingham, WA: Lexham Press, 2015.

Hill, Andrew E., and John H. Walton. A Survey of the Old Testament. 3rd ed. Grand Rapids, Mich: Zondervan Publishing House, 2009.

Jamieson, Robert, A. R. Fausset, and David Brown. Commentary Critical and Explanatory on the Whole Bible (1871). Oak Harbor, WA: Logos Research Systems, Inc., 1997.

NET Bible®New English Translation (NET). Online Notes Edition. HarperCollins Christian Publishing; Biblical Studies Press, L.L.C. Accessed January 21, 2021. https://netbible.com/copyright/.

Saunders, Dr. Eugene. "Old Testament Survey (BIBL1305)." Coursework, The King's University, Southlake Texas, 2021.

The Lexham English Bible (LEB), Fourth Edition. Logo Bible Software. Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.). Bellingham, WA: Lexham Press, 2010. http://www.lexhampress.com.

The NET Bible First Edition Notes. Biblical Studies Press, 2006.

Walton, John H. The Lost World of Genesis One: Ancient Cosmology and the Origins Debate. Westmont: InterVarsity Press, 2010. https://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=2030851.

### Notes

[\[1\]](https://draft.blogger.com/#_ftnref1) Dr. Eugene Saunders, "Old Testament Survey (BIBL1305)" (Coursework, The King's University, Southlake Texas, 2021), Lecture: 1.1 In the Beginning Lecture one a; Page 3.

[\[2\]](https://draft.blogger.com/#_ftnref2) Andrew E. Hill and John H. Walton, A Survey of the Old Testament, 3rd ed (Grand Rapids, Mich: Zondervan Publishing House, 2009), 79.

[\[3\]](https://draft.blogger.com/#_ftnref3) Robert Jamieson, A. R. Fausset, and David Brown, Commentary Critical and Explanatory on the Whole Bible (1871) (Oak Harbor, WA: Logos Research Systems, Inc., 1997), INTRODUCTION-TO THE PENTATEUCH AND HISTORICAL BOOKS-by ROBERT JAMIESON.

[\[4\]](https://draft.blogger.com/#_ftnref4) Hill and Walton, A Survey of the Old Testament, 79. The Toledoth: "Toledoth of Heavens and Earth (2:4--4:26); Toledoth of Adam (5:1--6:8); Toledoth of Noah (6:9--9:29); Toledoth of Shem, Ham, and Japheth (10:1--11:9); Toledoth of Shem (11:10--26); Toledoth of Terah (11:27--25:11); Toledoth of Ishmael (25:12--18); Toledoth of Isaac (25:19--35:29); Toledoth of Esau (36:1--8); Toledoth of Esau (36:9--37:1); Toledoth of Jacob (37:2--50:26)"

[\[5\]](https://draft.blogger.com/#_ftnref5) Hill and Walton, 57.

[\[6\]](https://draft.blogger.com/#_ftnref6) The Lexham English Bible (LEB), Fourth Edition, Logo Bible Software, Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010), Exodus 6:6-8, http://www.lexhampress.com.

[\[7\]](https://draft.blogger.com/#_ftnref7) Hill and Walton, A Survey of the Old Testament, 64--69.

[\[8\]](https://draft.blogger.com/#_ftnref8) Hill and Walton, 64--72, discusses ANE Chronology.

[\[9\]](https://draft.blogger.com/#_ftnref9) Hill and Walton, 105--8, see Figures 5.1a Early Dating of the Exodus and 5.1b Late Dating of the Exodus.

[\[10\]](https://draft.blogger.com/#_ftnref10) Hill and Walton, 82.

[\[11\]](https://draft.blogger.com/#_ftnref11) Dr. Michael S. Heiser, The Unseen Realm: Recovering the Supernatural Worldview of the Bible, First edition (Bellingham, WA: Lexham Press, 2015), Chapter 6: Gardens and Mountains.

[\[12\]](https://draft.blogger.com/#_ftnref12) John H Walton, The Lost World of Genesis One: Ancient Cosmology and the Origins Debate. (Westmont: InterVarsity Press, 2010), Introduction, https://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=2030851."

[\[13\]](https://draft.blogger.com/#_ftnref13) Hill and Walton, A Survey of the Old Testament, 79--81. Interesting note: "Written about 2000 BC, the Atra-Hasis Epic contains an account of creation, growing population, and a destructive flood with similarities to some of the details on Genesis 2-9."

[\[14\]](https://draft.blogger.com/#_ftnref14) Walton, The Lost World of Genesis One, Proposition 1: Genesis 1 Is Ancient Cosmology.

[\[15\]](https://draft.blogger.com/#_ftnref15) Hill and Walton, A Survey of the Old Testament, 744.

[\[16\]](https://draft.blogger.com/#_ftnref16) Hill and Walton, 722.

[\[17\]](https://draft.blogger.com/#_ftnref17) LEB, Romans 7:7.

[\[18\]](https://draft.blogger.com/#_ftnref18) NET Bible®New English Translation (NET), Online Notes Edition (HarperCollins Christian Publishing; Biblical Studies Press, L.L.C.), Genesis 5 (Enoch); 2 Kings 2:10 (Elijah), accessed January 21, 2021, https://netbible.com/copyright/.

[\[19\]](https://draft.blogger.com/#_ftnref19) Saunders, "OTS BIBL1305," Lecture: 1.1 In the Beginning Lecture one a; Page 5.

[\[20\]](https://draft.blogger.com/#_ftnref20) LEB, Genesis 17:6.

[\[21\]](https://draft.blogger.com/#_ftnref21) LEB, Genesis 20: 1-17; 26:1-34;

[\[22\]](https://draft.blogger.com/#_ftnref22) LEB, Genesis 35:11.

[\[23\]](https://draft.blogger.com/#_ftnref23) LEB, Genesis 41:37-44.

[\[24\]](https://draft.blogger.com/#_ftnref24) Saunders, "OTS BIBL1305," Slide: 1. Genesis thru Lev.

[\[25\]](https://draft.blogger.com/#_ftnref25) Hill and Walton, A Survey of the Old Testament, 86.

[\[26\]](https://draft.blogger.com/#_ftnref26) Hill and Walton, 92.

[\[27\]](https://draft.blogger.com/#_ftnref27) NET Bible®, Genesis 1.

[\[28\]](https://draft.blogger.com/#_ftnref28) NET Bible®, Genesis 3:15; 21.

[\[29\]](https://draft.blogger.com/#_ftnref29) NET Bible®, Genesis 6 (Noah and his family).

[\[30\]](https://draft.blogger.com/#_ftnref30) NET Bible®, Genesis 9:5; 1 Peter 1:19.

[\[31\]](https://draft.blogger.com/#_ftnref31) NET Bible®, Genesis 11-12; Deuteronomy 32: 8-9; Heiser, The Unseen Realm, Chapter 14 Divine Allotment. Yahweh would have none of it. After the flood God had commanded humanity once again to "be fruitful and multiply, and fill the earth" (Gen 9: 1). These words reiterated the original Edenic intention. But instead of obeying and having Yahweh be their god, the people gathered to build the tower. The theological messaging of the story is clear. Humanity had shunned Yahweh and his plan to restore Eden through them, so he would shun them and start again.

[\[32\]](https://draft.blogger.com/#_ftnref32) NET Bible®, Genesis 12:2.

[\[33\]](https://draft.blogger.com/#_ftnref33) LEB, Galations 3:8.

[\[34\]](https://draft.blogger.com/#_ftnref34) NET Bible®, Genesis 14:18; Psalms 110:4; Hebrews 5:6; 5:10; 6:20; 7:1-17; Dr. Michael S. Heiser, "The Naked Bible Podcast," The Naked Bible Podcast, Episodes 166; 167; 168; 172; 185, accessed January 30, 2021, https://nakedbiblepodcast.com/episodes/.

[\[35\]](https://draft.blogger.com/#_ftnref35) NET Bible®, Genesis 18.

[\[36\]](https://draft.blogger.com/#_ftnref36) LEB, Genesis 18:15; 20:17; 21:1.

[\[37\]](https://draft.blogger.com/#_ftnref37) Charles Gore, Henry Leighton Goudge, and Alfred Guillaume, eds., A NEW COMMENTARY ON HOLY SCRIPTURE INCLUDING THE APOCRYPHA, Vol. 1, p. iii (New York, NY: The Macmillan Company, 1928), (3) Religious Value.

[\[38\]](https://draft.blogger.com/#_ftnref38) NET Bible®, Hebrews 11:19.

[\[39\]](https://draft.blogger.com/#_ftnref39) NET Bible®, Genesis 22:8; The NET Bible First Edition Notes (Biblical Studies Press, 2006), Notes for 22:8. 20 tn Heb "will see for himself." The construction means "to look out for; to see to it; to provide." sn God will provide is the central theme of the passage and the turning point in the story. Note Paul's allusion to the story in Rom 8:32 ("how shall he not freely give us all things?") as well as H. J. Schoeps, "The Sacrifice of Isaac in Paul's Theology," JBL 65 (1946): 385--92.

[\[40\]](https://draft.blogger.com/#_ftnref40) The NET Bible First Edition Notes, Genesis 22:14; The NET Bible First Edition Notes, Notes for 22:14. 33 tn Heb "the Lord sees" (יְהוָה יִרְאֶה, yéhvah yir'eh, traditionally transliterated "Jehovah Jireh".

[\[41\]](https://draft.blogger.com/#_ftnref41) LEB, Genesis 50:20.

[\[42\]](https://draft.blogger.com/#_ftnref42) NET Bible®, Genesis 1-2; 2 Corinthians 4:4; Colossians 1:15.

[\[43\]](https://draft.blogger.com/#_ftnref43) LEB, Genesis 15:6; Romans 4:3.
