---
title: 'Facebook question: Are there terms in the New Covenant? What does it take to be "saved"?'
date: '2021-11-14T17:59:00.0010000+00:00'
draft: false
categories:
  - 'Biblical Studies'
  - 'Q&A'
---

<h4 style="text-align: left;">Question (paraphrased): Are there terms in the New Covenant? </h4><br />  Jesus said that if we forgive, the Father will forgive us (Matthew 6:14-15), if we are standing before an altar and realize we have a strife with our brother, we should leave the altar and be reconciled and then come back (Mark 11:25-26), he said that we should be merciful and judge not lest we be judged (Luke 6:36-37), and then he made that "strange" comment about forgiving anyone we forgive (John 20:21-23). <br /><br /><ul style="text-align: left;"><li> Are these terms of the New Covenant?&nbsp;</li><li>Are this required aspects of being a follower of Jesus?</li><li>Implied: Can you still go to heaven if you don't forgive? <br /></li></ul><p style="text-align: left;"><br /></p><h4 style="text-align: left;">Answer: That depends on the framework you're using. Platonic Heaven or a Biblical Kingdom?</h4><p>&nbsp;</p><p>Here are my thoughts today (subject to change after more prayerful study and reflection). <br />&nbsp;</p><p><b>Modern western Christianity:</b> If you've got a 16th century Calvinist/Lutheran concept of an angry God who's going to send you to a place called hell, but Jesus came to let you go to heaven if you say the magic password; then if you're mapping onto that framework an additional requirement of saying the magic password AND behavioral modification, then that would be a difficult set of waters to tread. You will have trouble speaking of these as "terms" of the New Covenant. <br /><br />  If, however, you've come to realize that much of what is said about the Bible in modern churches (much of what is said between about 200-1900AD, frankly) is basically inaccurate, incomplete, and in some cases just wrong, then you have a different dialogue all together.&nbsp;</p><p><br /><br /><b>Background</b>: The later church fathers started thinking like Greeks instead of Hebrews around the late 200s, and most of what happened next took us on the wrong path to the wrong questions and wrong answers. Greeks thought in terms of a disembodied future and a ticket into that future. For Plato (not Jesus), this body is inherently evil and the disembodied state is the "real" state we should be in. <br /><br />  By consequence, the ROMAN Catholic church adopted that inherited Greek way of thinking and added ritual to it, and then Martin Luther and Calvin did their best with what they had to counter the gross practices of medieval Catholicism, but did so still thinking like Greeks. Thus, in 2021, Christians are still debating about what magic password combined with which behavior is required to get to the correct disembodied future. Meanwhile, the entire debate, all sides, Calvin, Arminius, and Catholic alike, are all asking questions of the text it never intended to answer... <br /><br />So, what does the text actually ask its audience to hear? <br /><br />  <br /><b>The Biblical Narrative</b>: God made a good world, and he chose to reside on it with his human and elohim co-rulers. <br /><br />In a series of joint rebellions, both of Human and elohims (Genesis 3-11), the plans for earth were delayed. <br /><br />  The results of this rebellion were Death. And that death is painted most prominently throughout the scriptures as "separation" and "exile". Adam and Eve are cast from the Garden, Cain is cast from the city, Noah shows the total destruction of the land and people (the ultimate separation). When Jacob plots and schemes it separates him from his family. When Joseph's brothers cast him into the "pit", which becomes a common metaphor for death, their relationship is severed. <br /><br />  Immediately after the first rebellion, without any repentance or request from the first humans, God stepped in to cover the transgression and make a promise of restoration. At Babel, YHWH divorced the nations, turned them over to lesser ELOHIM (an exile in-masse), but chose one man and built a nation from Him so that through him the entire population could be restored. Then Yahweh began working his promise to restore all people to himself through this one man's future offspring. <br /><br />  Genesis ends with God taking that which was intended for evil in the life of Joseph and using it to bring about restoration. Then, the story of Israel begins. Moses murders a man and is cast into the desert. Israel sins and wanders for forty years. Israel sins again and again and is eventually sent into exile (separation). <br /><br />  Sheol, the grave, is depicted as the ultimate separation from God, family, and land. Nobody can escape Sheol, it takes all big and small alike. Sheol and Death are the greatest enemy of humanity. <br /><br />  All along, the prophets acknowledge that the people's hearts need to be changed if they will ever be able to live out the covenant with Yahweh. He responds by promising them new hearts and a new covenant. <br /><br />  They imagine a day, The Day of the Lord, in which all humans who ever lived are raised from the dead, all evil is judged, and those who were loyal to Yahweh enter into the New Creation, with New Hearts, and a New Covenant. <br /><br />  <b>And this is the hope for which Israel waited, The Day of the Lord/New Creation. Not a disembodied future, but a re-embodied future in a new creation with a new heart and a new King.<br /></b></p><p><b>&nbsp;</b></p><p><b>Then Jesus/Yeshua/Messiah: </b>Yeshua came around the first century AD, as Yahweh embodied (God with us). The seed of Abraham steps on the scene. He shows what it really means to walk with Yahweh. It does not mean dead works. It does not mean following the laws by building a hedge around Torah, adding laws to the laws that God himself did not even add. It does not mean being so ritual and legal-code bound that one cannot breath for fear of violation and yet another exile. <br /><br />  It looks like freely eating grain on the Sabbath. It looks like loving your neighbor, serving the weak and broken, healing the man left for dead. It looks like having your heart changed. But, he acknowledged, that cannot happen until a few most steps come. <br /><br />  So, he goes to the cross. He spends three days in Sheol (apparently preaching, would love to have heard that). And then he raises from the dead. The first human in history to experience the resurrection before the Day of the Lord. <br /><br />  Then, he ascends to the right hand of the Father, and sends the Spirit to dwell inside humans. Why? What was the need? If "Jesus paid the price" what need did we have of a Spirit-Life? <br /><br />  It was never about paying a price so that we "get to heaven when we die". Jesus was a Hebrew Messiah, not a Platonic one. The Spirit came to dwell inside of us to begin making us into new kinds of human beings. <br /><br />  The Kingdom of God has already arrived, it arrived 2,000 years ago. All who live in this age between the inauguration of the King (at the cross) and the Coronation of the King (at the Day of the Lord) have an opportunity to join the Kingdom. While we wait for the Day of the Lord, the day in which all evil is judged and Death is defeated once and for all, we are given the Spirit to begin the process of renewing us from the inside out. We also get the opportunity to invite others on the highways and byways into the Kingdom. <br /><br />&nbsp;</p><h4 style="text-align: left;">So, about the "terms of the New Covenant"? </h4><p style="text-align: left;">We are invited to freely become members of the New Covenant Kingdom. The invitation is free and freely offered. All writers (Matthew, Mark, Luke, John, Peter, James, Paul, Jude, and the author of Hebrews) agree that being a part of this Kingdom involves being changed into a Kingdom citizen. <br /><br /><b>  Citizens should act like Kingdom People.  </b><br /><br />  The Spirit of Yahweh takes up residence in us to make us new from the inside out, because thousands of years of human history proved we cannot change ourselves. Is there some kind of behavioral bar by which we are judged?&nbsp;</p><p style="text-align: left;"><b>If you do X you can't stay in the Kingdom? In short, that's not accurate either.</b><br /><br />That would be conflating membership in the Kingdom from discipline of the Kingdom Citizens. The King, The Father, disciplines his children. He shows them how to become better human beings, he enables them to enter that change by giving them the Spirit. But, the very fact we are asked to change, and enabled to change, is a result of already having become Kingdom Citizens. <br /><br />The one and only "requirement" to become and stay a citizen, is to be loyal to Yahweh and his Son, Yeshua (Jesus). <br /><br />  But, he will convict you if you stubbornly refuse to change (which every human does to some extent) and he will press gently but firmly on your heart until you either submit to change or reject him and leave the Kingdom. He will leave that choice to you until your dying day. <br /></p><p style="text-align: left;"><br /><br />That's the best answer I got, as of 11/14/2021. I hope that helps. <br /><br /><br /></p>
