---
title: 'Generational Curses: What''s real and what''s not?'
date: '2021-02-21T23:22:00.0030000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '992665923109546020'
blogger_filename: '/2021/02/generational-curses-whats-real-and.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<p><br /></p><blockquote><p><i>18 The word of the LORD came to me: 2 “What do you mean by quoting this proverb concerning the land of Israel, <br /></i></p><p><i>"The fathers eat sour grapes and the children’s teeth become numb?"<br />&nbsp;</i></p><p><i>3 “As surely as I live, declares the sovereign LORD, you will not quote this proverb in Israel anymore! 4 Indeed! All lives are mine - the life of the father as well as the life of the son is mine. The one who sins will die.</i> <br /></p></blockquote><blockquote><p><i>Biblical Studies Press, The NET Bible First Edition (Noteless); Bible. English. NET Bible (Noteless). (Biblical Studies Press, 2005), Eze 18:1–4.</i><br /></p></blockquote><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p><br /></p><p></p><p>Systemic Sin (Generational Curses) and Individual Sin (Individual Responsibility) both play a role in our lives. I am the son of an Alcoholic Father who was the son of an Alcoholic Father. Before him? I don't know. I experienced brokenness in my life in part because of the parts of me that were broken in my family of origin; and in larger part because of choices I made out of that brokenness. <br /><br />As I went through a process of breaking down and being rebuilt over many years; I eventually found a level of freedom unknown in my family for at last three generations. I walk my children through that so that they will be blessed and not cursed as they become men.&nbsp;</p><p>Some people over-spiritualize generational curses. God showed in the time of Josiah that he would absolutely stay the execution for a righteous people. It was not "inevitable" that they would be destroyed. But after Josiah Israel rebelled, and they were destroyed.  <br /><br />So it is with us. We are all dealt "issues" from our family of origin and our culture. What we choose to do with those issues, how we treasure them like demonic pets or press into healing from them, will determine our ultimate outcomes. It's never too late to start getting healing that will usher you into your calling.  <br /><br /><br /><br /> <br /> </p><div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<div class="fx-relay-email-input-wrapper"><input class="email" id="mce-EMAIL" name="EMAIL" required="" style="padding-right: 30px;" type="email" value="" /><div class="fx-relay-icon" style="bottom: 0px; right: 2px; top: 0px;"><button class="fx-relay-button" id="fx-relay-button" style="height: 24px; min-width: 24px; width: 24px;" title="Generate new alias" type="button"></button></div></div><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
