---
title: 'Attend to the living'
date: '2021-03-09T03:05:00.0040000+00:00'
draft: false
categories:
  - 'Musings'
---

<p> While I was reviewing my schedule for the next few months, I had a stunning realization. <br /><br />I had scheduled the date of my late-wife’s death off from work. It will be the third year anniversary. However, I needed that day to schedule off to pick up my mom from the airport. I prayed about it, and I heard the hardest and most profound response. <br /><br /><i></i></p><blockquote><i>“Attend to the living.” </i></blockquote><br />In other words, “Give your time and attention to the living”. How often do we fail to attend to the living in our lives? We spend our lives regretting the past, wishing it had been different, pining over lost lovers and lost opportunities. <br /><br />As a Widower, one tool I have learned to use <i>with purpose</i>, is grief.&nbsp;<p></p><p>Grief is the tool God gave us to process all the way through a loss that cannot be recovered. It is ugly, and messy, and painful, and bitter… but if you will allow the work of the Holy Spirit to form your character in the process, it can become bitter-sweet. <br /><br />Some things will not change. Some doors you didn’t walk through, cannot be walked through now. <br /><br />If you failed to take advantage of an opportunity at 16, 19, 22, or 32… you cannot at 40 go back and take that path. Those years are spent. Those decisions were made, and the consequences (both good and bad) came to pass.<br /><br />However, if you are brave enough to embrace grief, let it do its work in you, process all the way through until it helps you release the grip the past has on you until you let it go completely, then… then you can walk into the future and grasp new opportunities before those too pass you by. <br /><br />So, my mom is coming to visit. I will spend my “vacation time” embracing people who are still here. I will build new memories as long as the opportunity to build them still exists. My season of grief has ended. I will always carry that day, but I may not always take time off for it. I must invest the time I have in the people who are still here, my mom, my mother in law, my children, and my <i>new family</i> and friends I've met along the way. <br /><br />  The past still visits from time to time. A dream, a memory, a flower, a scent, a photo… the past comes for a visit, I smile, laugh, cry, and sigh. I let grief walk me through that memory, all the way through, careful not to stop and make camp in the valley of the shadow of death, but finishing my walk all the way through and out the other side. <br /><br />Attend to the living, let the past be past. <br /><b><br /></b></p><p><b>Darrell Wolfe, Storyteller</b><br />  <br /> </p>