---
title: 'Who am I, that I should…?  Lessons from Moses.'
date: '2021-02-02T18:35:00.0040000+00:00'
draft: false
---

<h3 style="text-align: left;">Who am I, that I should…?&nbsp;</h3><br /><i>Exodus 3:11 (LEB): 11 But Moses said to God, “Who am I that I should go to Pharaoh and that I should bring the ⌊Israelites⌋ out from Egypt?”<br /></i><br /><br /><b>Who is man that you are mindful of him, care for him (Psalms 8:4; 144:3; Hebrews 2:6)?<br /></b><br /><b>Around ten years old</b>, I felt a distinct call “to the ministry”. I was standing in the sanctuary of the church my (soon-to-be “atheist”) father was pastoring at the time, and  the mantle or anointing fell on my shoulders. It was distinct, clear, and unquestionable. I was to become a “pastor” or “minister”. I saw myself preaching to the congregation. <br /><br />As I grew older, the pressure of life as a pastor’s kid, the pressures of sin and secret sinful choices, the sense of “dirty-ness” or unclean-ness of sin all lent themselves to the sense that I was a “screw up” and if I ever surrendered to the call to pastor I would “fall just like Jimmy Swaggart and take the church down with me”. <br /><br />I lived with the duality of Spiritual Darrell and Sinful Darrell for decades. Always working within ministries as a volunteer but staying as far from the pulpit as I could. Periodically, I would find myself on the “platform” in some musical capacity (guitar, singer, even lead worship singer a few times). The pressure would be too much to bear, and I would bolt, run, literally feeling torn in two by the process. <br /><br />Between 2013-2016, God began a process of dismantling that stronghold, which came to a head January 6, 2017. On that day, I gave myself to my God and my family in a new way. Those seasons led me into an even more difficult season, when my wife of 14.5 years died suddenly at 36, and I was left a Widower and father to two boys, then 10/13. Between 2018-2019 God purged the old me through trials by fire. <br /><br />With the help of friends, confidants, counselors, and my late-wife; I came through those fires a different man. My kids have often commented on how I’ve changed. One of the hallmarks of leadership, per Paul’s letter to Timothy, is a man who managed his household well. So my kids affirmation have given me the courage to keep going.<br /><br />Do I struggle still? Yes in some ways, no in others. Yet, the real lesson is that the struggle itself is irrelevant. It is not who we are or what we do that makes us fit for the master’s use. It is His Calling, and submitting to his calling that makes us fit.<br /><br /><b>Who am I to pastor or teach God’s Word?</b> The answer is, the one who God has chosen. That’s it. Moses was a murder and stuttering reject who fled his people and lived for 40-years in obscurity before being brought to the center of attention as God’s chosen mouthpiece. <br /><br />Even when his unbelief cost him part of the job and God had to bring on Aaron as a concession (plan B), Moses was still the chosen one. <br /><br />It was God who called him, God who enabled or empowered him. There was nothing special about Moses that caused the people of Israel to become free of Pharaoh’s grip. Ultimately, Moses was irrelevant. It was a show-down between YHWH and the god of Egypt Horace, who Pharaoh represented. <br /><br />Any human could have been used, as Aaron’s participation proved However, it was also clear that God wanted to use Moses’ story in the process. And Moses became known as a friend of God. <br /><br />There is a beautiful duality. God doesn’t need humans but he chooses to need/want/use them in the process of his plans. Yet, because he chooses to need them, each human participants story weaves itself into God’s larger story, adding that uniqueness to the story. <br /><br /><b>God steps in and uses men and women as he sees fit.</b> If he has called us, he enables us. We are not chosen because we have any special ability. It’s not because of our IQ or lack thereof. It’s not because of our ability to orate or lack thereof. He will enable us to do whatever he calls us to do. Or, he will work despite our inability and do miracles despite us. <br /><br />It is not because of “our faith” or “our gifting” that God brings about miraculous results; rather, it is because of our willingness to participate. <br /><br />We can see Moses’ willingness to participate and his reluctance to participate, both contribute to the story. If it had not been for Moses‘ refusal to cooperate at first, there would have been no Aaronic priesthood. The refusal of Moses led to the creation of the line of priests who would eventually reject the Priest-King Jesus. <br /><br />Adam, Noah, Melchizedek, Abraham, Isaac, Jacob, Joseph, David… Jesus… The King-Priest was the template ordained of God. Aaron created a dual leadership within Israel that has had ramifications to this day. The Pope vs King battles of the Middle Ages. The separation of Church and State in secular societies. All have their root in Moses’ disobedience to surrender to God’s plan. <br /><br /><b>Our abilities and talents are irrelevant.</b> But our willingness to participate or run from God’s asks are extremely relevant; and they create lasting impacts. <br /><br />So when God taps you on the shoulder, ask not what you can do for God. The answer is nothing. Your gifts, talents, and abilities (or lack thereof) are irrelevant. Ask, rather, what God can do with your surrender. That, is a question with eternal significance.<br /><br />He will use your uniqueness, your humanity, your gifts, talents, abilities, or lack thereof, to add the color and flavor of you humanity to the story. However, the ultimate outcomes will not be impacted for your ability, it will be impacted by your submission to God’s ability and what he decides to do. <br /><br /><ul style="text-align: left;"><li>If your church didn’t grow, that’s his responsibility.&nbsp;</li><li>If your church did grow, that’s his responsibility.&nbsp;</li></ul><br />Both outcomes are irrelevant to your gifts, talents, and abilities. They are his and his alone. <br /><br />Several prophets preached to an Israel that refused to repent. But the message still had to be recorded, that their disobedience would be recorded, that their punishment would be justified. <br /><br />Your job is to submit, and go, not judge the outcomes based on your limited perspectives.&nbsp;<div><br />Abraham is still, today, seeing the fruit of his obedience come into Glory. He has yet to see the fullness of his obedience, as you and I are a part of that obedience. Moses is still, today, seeing the fruit of preserving the people of the Messiah. Both greet the people of God as a they arrive in Heaven, the way station of God awaiting the final resurrection and return to Earth. Both see new fruit from their obedience arrive daily.<br /><br />So when God taps, just go on the journey. It’s not your job to bring people out off Egypt, it’s God’s. It’s your job to do whatever he says to do in cooperation with his plan.<br /><br />Selah.

</div>
