---
title: 'Recommendations for taking your faith further:'
date: '2021-01-30T07:09:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3950753151555520587'
blogger_filename: '/2021/01/recommendations-for-taking-your-faith.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Suggested'
---

<div>Darrell Wolfe, Storyteller:<br></div><div><br></div><div>My top suggestions right now for taking a step further into faith.</div><div><br></div><div><b>The Bible Project</b> takes a scholarly look in a creative video approach to make biblical concepts accessible. They are widely free of denominational influence and present the facts of history and difficulties of the text. It's a fascinating channel and worth your time. https://youtu.be/ak06MSETeo4</div><div><br></div><div><b>The The Lost World of Genesis One by Dr. John Walton</b> should be required reading for any Christian wanting to take their Bible reading to the next level, especially anyone interested in Creation Science. Dr Walton discusses the book here but it really needs to be read to be understood as it requires letting go of preconceived ideas about the term "creation" from a 21st century mind.&nbsp; https://philvischer.com/news/episode-16-the-one-american-history-and-guest-john-walton-2/</div><div><br></div><div><b>The Naked Bible Podcast by Dr Michael Hieser</b> is a must listen! I've read the Bible five times through, portions many many 100s of times. I've studied. Read commentaries. Worked in lexicons to dig up original language. And all of that was kindergarten compared to what I've learned listening to his breakdowns of scripture. https://nakedbiblepodcast.com/episodes/</div><div><br></div><div>Although I would differ from him on certain points, NT Wright is one of the world's leading New Testament Scholars. His podcast "<b>Ask NT Wright Anything</b>" is a thoughtful, deeply researched, and thought provoking response to some tricky biblical questions. A good one to add to your list. https://askntwrightanything.podbean.com/</div><div><br></div><div><b>"Jesus did NOT come to make bad people behave better. He came to make dead people alive." Bob Hamp LMFT </b>https://www.95network.org/blog/bob-hamp-59?hs_amp=true&amp;__twitter_impression=true</div><div><br></div><div><br></div>