---
title: 'Waking from the Matrix of American Christianity'
date: '2021-06-09T21:28:00.0010000+00:00'
draft: false
categories:
  - 'Musings'
---

<div>Once you learn to read the Bible in its own original contexts, it's almost impossible to see things the way you were taught in Sunday school.&nbsp;<br></div><div><br></div><div>It's like, every single thing I heard in church was partially correct, not false, mostly, but almost all of it was twisted out of context to the point it didn't quite even mean what it was actually supposed to mean.&nbsp;</div><div><br></div><div>Just a few years in Bible School, and some thoughtful podcast listening, and some reading of scholars, and I feel like I've been awakened from the Matrix.&nbsp;</div><div><br></div><div>The depth, richness, and nuance of the biblical text in its own original context makes American Christianity feel like a plastic version of the real thing. Like a Hot Wheels car held up by a three year old, next to the matching real car driven by his Daddy.&nbsp;</div><div><br></div><div>It's not that we've been "wrong", most of the time...&nbsp;</div><div><br></div><div>But I now see the entire culture of American Christianity as the church in Revelation that didn't know it was blind and naked.&nbsp;</div><div><br></div><div>The Bible is more true for me now, than it's ever been, but, far less "simple" than I thought it was.&nbsp;</div><div><br></div><div>I need to go write a blog post and stop pontificating....&nbsp;</div><div><br></div><div>Shalom y'all. </div>