---
title: 'SIN: What is sin, according to the Epistles of John, Peter, James, and Paul? And what is the counter-attribute (cure)?'
date: '2021-09-23T03:40:00.0030000+00:00'
draft: false
categories:
  - 'Studies'
  - 'Class Assignment'
  - 'Biblical Studies'
  - 'Armchair Theology'
---
*I thought I posted this last semester, apparently I'm behind on posts.

SIN: What is sin, according to the Epistles of John, Peter, James, and Paul? And what is the counter-attribute (cure)?

The King's University, Southlake, Texas

New Testament Studies (BIBL1306)

Professor: Jonathan E Jennings MTS

May 2, 2021

By Darrell Wolfe

# Sin: According to John

In his first epistle, John (the disciple whom Jesus loved) has a singular focus that runs throughout: Love. John establishes the image of Light and Darkness as opposite forces.[\[1\]](#_ftn1) His exhortation to live in the light begins to sound like a lifestyle of "works" until one contextualizes the light-concept with his key conclusion: "The one who *loves* his brother resides in the light".[\[2\]](#_ftn2) The rest of his letter is written in the context of this "Love Test".[\[3\]](#_ftn3) If you love, you will not kill your brother. If you love, you will not observe a brother's need and ignore it. He reiterates that LOVE is the single command of Jesus.[\[4\]](#_ftn4) The second and third epistles of John are more of the same. In the second, John re-emphases his point that the single commandment of Jesus is to love. In the third, it is a commendation of a friend whose hallmark is "love". For John, loving one's brothers is the sign that love is in you. Failure to love is a sign that God's love is not yet fully manifested in you.

# Sin: According to James

James sees sin as a failure of faith. He writes his letter as a series of statements and counterstatements, each designed to show how a person of faith should respond to a given situation. Because of this, some scholars throughout church history misunderstood James, seeing his message as opposite of Paul's grace through faith alone.[\[5\]](#_ftn5) However for James, "faith without works is dead".[\[6\]](#_ftn6) He insists that one who has faith is moved by that faith into action. He spends his epistle citing various examples of what a life of faith should look like. James summarizes his examples by saying that each is carrying out the Royal Law "you shall love your neighbor as yourself".[\[7\]](#_ftn7) James sees "works" as the natural byproduct of faith; love in us is expressed as love through us.

# Sin: According to Peter

While Peter never uses the word "sin", he spends his both letters explaining how the People of God should conduct their lives. Peter's premise is: because we love Jesus, there is a future inheritance to which the believer looks forward. Therefore, the believer is to endure hardships because of the larger story they have been invited into.[\[8\]](#_ftn8) Twice he uses the term "Temporary Residents" in reference to the believer's status on earth. Peter urges "self-control", "rid all evil behavior", "keep away from worldly desires", "submit to authority", and he asks that the body be of one mind, sympathize with each other, and love each other as brothers and sisters.[\[9\]](#_ftn9) Using examples of slaves, wives, husbands, and leaders; Peter urges the body of believers to submit one to another. For Peter, to be invited into the family of God is to want to become a member of that family, loving your brother and sister.

# Sin: According to Paul

Romans remains Pauls' most authoritative thesis on "sin". He begins his argument by building the case that "all have sinned" therefore nobody is right before God.[\[10\]](#_ftn10) Paul shows that sin brought death but faith in the finished work of Jesus brings life.[\[11\]](#_ftn11) What is the response, then, to this life? Paul tells us what the life of a believer, freed from the power of sin and death, ought to look like. How are we enabled to live differently? Because the "love of God has been poured out into our hearts through the Holy Spirit...".[\[12\]](#_ftn12) In every other letter, then, Paul builds on the case he made to the Romans that we are free from sin; therefore, ought to live differently. It is clear from the number of times "love" is used throughout his letters that even more than sin, Paul had love in mind as the key antidote to sin.[\[13\]](#_ftn13)

# Sin: A Unified View

Each author adds their own unique perspective to the topic of sin. Alone, we each see in part, together, we see the whole. Despite each author's unique style, flavor, and presentation; we see the key theme of "love" running as a thread throughout their works as the counter-attribute to "sin". If one walks in love, they will avoid walking in sin. If one is sinning, that is a failure to walk in love.

# Bibliography

*Immerse: Messiah - A New Testament Reader Bible, by the Immerse Project. Adapted from New Living Translation (NLT)*. Immerse : The Reading Bible. Carol Stream, Illinois: Tyndale House Publishers, Inc, 2017.

*Logos Bible Software 8.17 SR-38.17.0.0022*. Faithlife Corporation, 2000. logos.com.

*The Lexham English Bible (LEB), Fourth Edition*. Logo Bible Software. Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.). Bellingham, WA: Lexham Press, 2010. http://www.lexhampress.com.

Wright, N. T., and Michael F. Bird. *The New Testament in Its World: An Introduction to the History, Literature, and Theology of the First Christians*. London : Grand Rapids, MI: SPCK ; Zondervan Academic, 2019.

------------------------------------------------------------------------

[\[1\]](#_ftnref1) *The Lexham English Bible (LEB), Fourth Edition*, Logo Bible Software, Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010), 1 John 1:5-10, http://www.lexhampress.com.

[\[2\]](#_ftnref2) *LEB*, 1 John 2:10. Emphasis added.

[\[3\]](#_ftnref3) N. T. Wright and Michael F. Bird, *The New Testament in Its World: An Introduction to the History, Literature, and Theology of the First Christians* (London : Grand Rapids, MI: SPCK ; Zondervan Academic, 2019), 149.

[\[4\]](#_ftnref4) *LEB*, 1 John 3:18-24.

[\[5\]](#_ftnref5) Wright and Bird, *The New Testament in Its World*, 294.

[\[6\]](#_ftnref6) *LEB*, James 2:17.

[\[7\]](#_ftnref7) *LEB*, James 2:8.

[\[8\]](#_ftnref8) *Immerse: Messiah - A New Testament Reader Bible, by the Immerse Project. Adapted from New Living Translation (NLT)*, Immerse : The Reading Bible (Carol Stream, Illinois: Tyndale House Publishers, Inc, 2017), 1 Peter 1 (summary).

[\[9\]](#_ftnref9) *Immerse: Messiah - A New Testament Reader Bible, by the Immerse Project. Adapted from New Living Translation (NLT)*, 1 Peter 1-2.

[\[10\]](#_ftnref10) *LEB*, Romans 2:12; 3:9.

[\[11\]](#_ftnref11) *LEB*, Romans 5:12-17; 6:23.

[\[12\]](#_ftnref12) *LEB*, Romans 5:1-10.

[\[13\]](#_ftnref13) *Logos Bible Software 8.17 SR-38.17.0.0022* (Faithlife Corporation, 2000), Word Analysis: Of the 297 times "love" is used in the New Testament (LEB), 123 of those were used by Paul. John only used it more often if you count his Gospel, as his Epistles were short., logos.com.
