---
title: 'Discussion around "The Spirit Formed Life" for class.'
date: '2021-03-01T03:10:00.0000000+00:00'
draft: false
categories:
  - 'Studies'
---
*Coulter, Leah. "The Spirit-Formed Life (BIBM1301)." Coursework, The King's University, Southlake Texas, 2021.*

 *Semester discussion questions for class.

# DQ1: The Pillar Principle

**Prepare:**  Read *Living the Spirit-Formed Life, Prologue, Chapter 1 & 2 and listen to Pastor Jack's Invitational Video*

**Participate:** What does it mean to you that "Jesus Christ is still in the pillar-forming business (Hayford 2017, 24).  Discuss three key concepts of pillar-making and the role of the spiritual disciplines in making disciples rather than just believers.

Hayford takes verses from Revelation, John, and 1 Peter o build the case that Jesus is making people Pillars in the House of God. He draws from Revelation 3:12 to establish Faith, Creative Power, and Stability as three keys of his Pillar making process. Hayford states that the disciplines he will outline are fundamental to walking a life formed by the spirit. (Hayford 2017, 21-24)

My gut reaction was "And...?". I kept waiting for the punchline. I had to stop and think about what he was trying to say. Could be state of mind I've been in all week. But I've been harping all year on the need for The Church to stop being distracted by Washington DC and start being active members of the local community.

Today, in my area, the power went out for a large majority of the community. I was sad when my church (which has power) decided not to meet for Wednesday service while many of us had no power. Rather than being a pillar in the community, serving, opening the doors with hot coco, and offering to charge people's phones, etc. They simply closed. I think for me, that's what it means to be a pillar. It means to start mattering to community again. If the church is only open for "Bible Study" and not for meeting felt need, I think we've lost our salt and light.

# DQ2: God Speaks

Top of Form

**Prepare**:  Read *Living the Spirit-Formed Life, Chapter 3.*

**Participate: **Discuss three of the ways God speaks to us.  Describe what it means to be a "genuine listener" (Hayford 2017, 44).

The act of hearing God is well established in scripture and Christian history, even in song (Hayford 2017, 35-42). Especially in the age of Social Media and the false doctrine of Christian Nationalism, it has become important that we "take heed to what we hear" (Mark 4).

How often have I been reading a passage or considering a situation and the still-small voice of Holy Spirit led me to the right answer? How often have I spoken harshly or with too much confidence (a sure sign of incorrect thinking) and felt the nudge to tell me to stop?

Hearing the voice of God means staying sensitive to His voice, heading it, pausing to listen. I have had seasons of putting down the study of The Word and just listening or going for a walk to listen to Him; asking him for his agenda.

At the same time, I am concerned about how often I and others have "heard" God and it wasn't him at all. A proper exegesis of scripture is also needed to "test and approve" what we hear. Nevertheless, I always want to remain sensitive to His Voice.

We were meant to live a life WITH God, not just working FOR God, or serving UNDER God's law's as if he was a benevolent CEO we've never met but admire. He walked with Adam in the garden and he walks WITH us today, if we will pause long enough to hear him (Jethani 2011, Chapter 1).

# DQ3: People of His Presence

Top of Form

**Prepare: **Attend/listen to recorded lecture, "The SPIRIT-formed Life - People of His Presence" and read the accompanying lecture handout in Learning Materials.

**Participate: **Based upon the lecture materials, discuss three key concepts that stood out to you that describe what it means to live the SPIRIT-formed life.

Bottom of FormAs I pondered the phrases: *God With Us*, *People of his Presence*, and *Our Yielded Life*, it took me our larger story.[\[1\]](#_ftn1) God walked with Adam, Enoch, Abraham, Moses, and David. All along YHWH gave hints that he was coming to be Immanuel "God with Us" (Isaiah 7:14). Jesus, The Word with us. He sent the Holy Spirit and we are now God's Presence (1Corinthians 6:12).

So, if we are to live a life yielded to the SPIRIT, what would that look like? My reflection took me to Galatians 5: 13-26. The phrase "Live by the Spirit" could be translated "Conduct one's life by the Spirit".[\[2\]](#_ftn2) I began to see the fruit of the flesh and fruit of the spirit as dashboard lights to indicate if we are walking that life conducted by the spirit. In an orchestra, each plays their instruments, but they must follow the leading of the conductor.

So what does it mean, then, to be a people of His Presence? Ultimately, as Jethani's book demonstrates, we are living a life WITH God not for him or under him.[\[3\]](#_ftn3) So it may be as simple as pausing to see where the conductor is leading.

# DQ4: Baptism and Communion

**Prepare: **Read *Living the Spirit-Formed Life, Chapters 4 & 5.*

**Participate:** Baptism is a "miracle moment" (Hayford 2107, 47) and Communion is a "declaration of dependence" (Hayford 2017, 60). Discuss how the concepts presented in these two chapters are related and should influence the way we live the Spirit-formed life.

Baptism was "the central rite for entrance into the church".[\[4\]](#_ftn4) As circumcision was the rite of passage into Abrahamic/Mosaic community, baptism was the rite of passage into the community of Christ (Colossians 2:6-15).[\[5\]](#_ftn5) The Lord's Supper served as a communal reminder of what Jesus accomplished, creating the community.

Hayford observes that Jesus was baptized (Matthew 3:16-17).[\[6\]](#_ftn6) Jesus began his ministry being baptized as a symbolic gesture for what he would later call his baptism, the cross (Luke 12:50; Mark 10:38). Like Jesus, we also die and are risen again in our baptism. We then proclaim that message at every observance of the Lord's Supper.

We need both personal and community reminders that we died to ourselves and now live in Him. So we examine ourselves, am I living for His community? Am I making decisions based on His Word (written and spoken)? Am I serving myself or building His Kingdom? As Hayford put it, "Be Baptized. Live Baptized."[\[7\]](#_ftn7)

# DQ5: Life Under and Over God

Top of Form

**Prepare: **Read *WITH: Reimagining the Way You Relate to God, Chapters 1-3*

***Participate:**** *According to Jethani, compare the characteristics of Life Under God and Life Over God.  What stood out to you about the shortcomings/costs of relating to God from both of these postures?\-\--Bottom of Form

Life Over God seeks to use proven principles to control life's outcomes rather than rely on relationship with God.[\[8\]](#_ftn8) In a Life Over God approach, the idea of outcomes being based on "ritual or morality" is deemed "superstitious". God is seen as creator but not as relevant to day-to-day living.[\[9\]](#_ftn9) It is this approach which many Americans, myself included, tend to lead by default (often unknowingly). We wouldn't say God is irrelevant on a test; however, if we don't consult him daily but live without acknowledging his presence, it is our default mode.

Life Under God seeks to control life's outcomes by obeying (religiously) all of God's commands (if we obey, he will bless).[\[10\]](#_ftn10) In a Life Under God approach, faith is merely an obedience to morality rules and ethical requirements.[\[11\]](#_ftn11) It is this approach that allowed The Church in the USA to vote for a morally deficient man (Trump) who would "do right things" as they saw it. America will be blessed if we just force everyone to "do right".

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-- \-\-\-\-\--The best phrase of all three chapters, for my own walk, was: "... there is an eerie correlation between meanness and how absolutely certain a person is about their beliefs."[\[12\]](#_ftn12) I've been guilty of this far too often, far too recently. It's possibly my biggest vice, relying too heavily on my big brain and high IQ. As an antidote, God gave me a girlfriend who says, "I could be wrong, and I often am" and then she gives me observations that tie to the heart (not just mind) of God.

# DQ6: Life From and For God

Top of Form

**Prepare: **Read *WITH, Chapters 4 & 5*

**Participate:** According to Jethani, compare the characteristics of Life From God and Life For God.  What stood out to you about the shortcomings/costs of relating to God from these two postures?

Bottom of Form

Life From God seeks God's benefits and gifts "what's in it for me" without seeking his person, or, to know him personally.[\[13\]](#_ftn13) Jethani's argument against ministers like Joyce Myer is essentially a Straw Man argument that clearly lacks context and understanding of her position (having listened to her for years myself).[\[14\]](#_ftn14) However, despite the well-intentioned teachings about God's benefits (Psalms 103), I too found myself distracted by what God could do for me rather than becoming a "friend of God".[\[15\]](#_ftn15)

Life For God seeks to find a Purpose Driven Life, meaning, and significance in what we accomplish on God's behalf or in his name.[\[16\]](#_ftn16) Arguably, this is the more seductive and subtly misleading of all four anti-postures. The condition of Jethani's students is the condition that led me into a fallen and suicidal state by the end of 2016.[\[17\]](#_ftn17) Open communication, being "real" is what saved me. The seduction of "working for God" can lead one to be all action and no relationship. Yet, you feel like it's the right thing to do, until it's not.

More on that story:

I spend years trying to suppress and control the "dark" me so I could accomplish things for God. I saw myself on this epic adventure and I was going to take the world for Jesus. But as the years of trying to "be Christian" wore on, they became less successful and less rewarding. By fall 2016, I was in a full state of chaos and planning my own suicide. It was through multiple conversations, both with a Counselor and a small group of fellow strugglers, that I found my healing journey take a new turn. It was through one very important conversation with my late-wife, on January 6, 2017, where we laid our souls bare before each other, that I found my healing secured. Out of that season, came a standard called No Hiding, which we lived out before each other until her death in June 2018. Here I am, in 2021, realizing that yet again, I'm doing things for God, for my family/boys, for friends, but am I taking the time to know Him?

# DQ7: Life WITH God

Prepare: Read Jethani, Chapters 6 & 7and listen to "The Treasure" video

Participate: Describe what Jethani means to live a Life WITH God and how our relationship WITH God gives us a new/fuller understanding of living WITH faith.

Jathani builds on Brother Lawerence's observation that only those who experience life with God can comprehend what it means.[\[18\]](#_ftn18) A desire for Life With God is kindled by a vision for who he really is, which is made possible by the revelation of God in his Word, and ultimately through the revelation of Jesus as God With Us.[\[19\]](#_ftn19)

J.R.R. Tolkein's phrase "eucatastrophe" which is a sudden intervention of good, can be seen throughout the narratives of the Old and New Testament.[\[20\]](#_ftn20) We see this play out in the book of Job.

Throughout his trials, Job begs for an audience with God to plead his case as before a judge. The Prophet Elihu arrives on the scene to show Job his error. Job had spend the entire narrative trying to prove his innocence before God, and that his fate had not been "deserved". Job lived in a broken mindset of Life From God, and he assumed his right actions should have earned him peace. Elihu steps onto the scene to become The Mediator Job requested. In a reversal, Elihu does not plead Job's case to God; rather, he pleads God's case to Job. He shows that man's right-actions do not benefit God and that all the uprightness of man does not earn him a life without trials. Rather, it is the role of Mediator to make man aware of God's greatness and make a ransom to allow man to live a Life WITH God. Job ceases trying to be right in his own eyes, gets a vision for God's greatness, and then submits his fate to God. In doing so, his fortunes are turned. Job stops seeing God as provider or judge, and begins to see God for his greatness. Upon catching that vision, all he needs is God and God alone.

Job is an example of the Principle Jethani described in concentric circles. Danger \> Fear \> Control are turned on their head by Submission \> Faith \> Safety.[\[21\]](#_ftn21)

# DQ8: Life WITH Hope and Love

Prepare: Read Jethani, Chapters 8 & 9

Participate: Living WITH God empowers us to live WITH Hope and Love.  What one key point or concept resonated with your heart regarding living WITH Hope (Chapter 8) and living with Love (Chapter 9)?

Life WITH Hope: Hope acts as an anchor to the soul.[\[22\]](#_ftn22) Just like YHWH was with the people of God through the parting of the sea; just as Jesus was with his disciples in the boat tossed storm; so too can we have peace in the storm when we are aware of God WITH Us.[\[23\]](#_ftn23)

Life WITH Love: As we pursue the silence, the quiet knowing, as we "be still and know" that he is God, his love can wash over us. This "posture begins and ends with love".[\[24\]](#_ftn24)

As my girlfriend so often say, "LOVE is the key to everything else in God's word".[\[25\]](#_ftn25) There are many great and wonderful things about God but if you do not understand that he IS love and that he loves you, there is little hope of your understanding the rest properly. As I pursue "Truth" with all my energy, I bulldoze over people's hearts in the process. If I will but stop and realize just how much God loves that person, I may change my tone or tact. It begins by understanding how much he loves me. Realizing how much he loves me requires spending time in his presence, not to ask for things, or to get his agenda (though he requests I do both of those too), but to just be in his presence.

I use to sign my blog posts with #BeStillBeLed, which is a great way to end this post.

# DQ9: Fullness of the Holy Spirit

Top of Form

**Prepare**: Read Chapter 9,* Living the Spirit-Formed Life*, and listen to the video, "The Beauty of Spiritual Language" by Pastor Jack.

**Participate**:  Discuss the blessings of living a life that abides in the fullness of the Holy Spirit.  What resonated with your heart as you read or heard Pastor Jack's teachings?

In the video, Hayford drew a line from the breaking forth of the water from the rock, to the Feast of Tabernacles to the outpouring of the Holy Spirit.[\[26\]](#_ftn26) The Feast of Tabernacles (also known as the Feast of Booths; or Sukkot) is one of Israel's three primary annual festivals.[\[27\]](#_ftn27) People would gather and live in tent/booths as a reminder of their days in the wilderness; much like a large camping trip in the middle of the city.

Hayford says that in one tradition the priest would pour water down the steps of the Temple to signify the water poured out of the rock in the wilderness by God through Moses.[\[28\]](#_ftn28) Hayford then draws a parabolic meaning from the plural "rivers" that Jesus said would pour out of the belly of a man/woman who believed in him and drank from his Spirit. These waters include a variety of giftings which serve to draw us closer to God and make us better equipped to serve others.[\[29\]](#_ftn29)

The idea of powerful breakthrough of water (spirit) gushing from The Rock (Jesus) is a potent image. I had not seen the connection; which makes God's judgment of Moses the second time it happened, for striking instead of "speaking" to the rock, all that much more meaningful. The Rock was struck once (the cross) and could not be struck again. The Word was their deliverer.

**Lesson**: If I will build my life on The Rock (Jesus) and drink from his water (Spirit); I will have a life of stability against the storms and a life of overflow provision of that same Spirit for others.[\[30\]](#_ftn30)

# DQ10: "Abide in ME"

Top of Form

**Prepare**: Read John 14-17 and the accompanying "Abiding" articles.

**Participate**: Describe what it means to "Abide in Christ" and describe those relationships expressed by Jesus in His teachings and prayers.  What did the Holy Spirit reveal to your heart?

**Every time I try to shorten this it comes out long again:*

Repeat patterns are one Hebraic way of emphasizing a point. We see several such patterns in these passages (John Chapters 14-17).

Abide IN: Jesus is in the father, the father is in Jesus, the Holy Spirit is in us, we are in them, we are to be united with them and each other. There is a co-unity theme throughout these passages. God WITH Us.

Do My Words: IF you love me, do my words. As he will later tell Peter (feed my sheep) (John 21). His words, commands, teachings, all revolve around loving well. Love God. Love each other. Serve each other. Cast no stone. Summarized in John 16:23-28.

Results: Do works like I did and greater. Ask and it will be done. Bear Fruit.

The Original Testament is the context for the New Testament. Bearing fruit, to a Hebrew ear, should harken back to the commands to Adam (Genesis 1:28), Noah (Genesis 9:1), Abram (Genesis 12:1; 14:19-20; 17:6), Isaac (Gen 26), Jacob/Israel (Gen 29, 35:11), and others. Be Fruitful. Multiply. To be fruitful is to multiply.

Therefore, to Bear Fruit in Jesus is to multiply his spirit in others. Although we cannot save anyone, we can testify of his goodness. Throughout the section, The Holy Spirit is seen as helping on this mission, and convicting the world of sin, righteousness and judgement. The section begins by tying this together: I loved you, you love one another, the world will see that love and know you are mine (John 13: 34-35).

Therefore, to abide is to allow his love for you to run through you to others The fruit of that lifestyle is the replication of his love in others and through them to others. We together, multiply his love throughout the world, ever increasing, until the day he returns to take us (individually) to be with him (death) or the day he returns (corporately) to be with us here on Earth (resurrection).

It's not our job to convict the "world" of sin, that's the Holy Spirit's job (John 16:7-11). Our job it to be loved and then love as we are loved.

**There really is only one mission. God love us, we abide in his love, we share that love as an overflow with others until we leave or he comes.**

**[Probing Deeper:]{.underline}**

Eternal Perspective: John 14 begins by showing me that if I will keep my eyes on the ultimate outcome (being at home in the Father's house, in heaven, and eventually on earth after the resurrection), it will keep my heart stable and untroubled. I can be at peace despite the turbulence of this life.

Although the ultimate goal will be the physical reunion of The Church, Jesus, and His Father; the intermediate goal is "union". Even though Jesus left, he never stopped being Emanuel, God WITH Us. He repeats this theme of "I will come to him", "I will make myself known to him", "They will be one with us".

His Love & Word: He makes it clear that those who LOVE Him will live by His words, instructions, teachings, and commands. Where I (and much of Church history) miss his heart in this, is paying close attention to what that means. This is no rigid following of religious rules (the church I grew up in was like this). He is not making a new class of Pharisees. The Hebraic "Law" was "Wisdom Teachings", instructions for living well. His "commands", his "teachings",  were things like "Love God. Love your neighbor. Neither do I condemn you, go and sin no more." His lifestyle was his teaching. Sadly, I have all too often focused on "do this good" or "don't do that bad", which are dead works from the Tree of Knowledge. The Tree of Life is a tree of loving people through His spirit, which changes people from the inside out, not the outside in. In 15:12, Jesus says "THIS is my command: Love one another". We are often guilty of obeying commands he did not give (don't smoke, don't watch those movies, etc.) but not obeying the primary commandment he did give: "Love one another".

Abide: The phrase is compared to a vine. As a vine cannot live without being connected to the root system, with the life flowing from the root; we cannot "live" without the LIFE of God flowing through us. Abide, in this sense, takes us back to Eden, in the Tree of LIFE. It is not important WHAT we "know" (wrong tree) as much as it is important WHO we are connected with (Jesus, Father, Spirit, Tree of LIFE).

Ask/Receive: Another fascinating repeated pattern is his desire that we "ask the Father.. He will do it", and the references to works and manifesting Jesus (John 14: 12-13; 21; 15:7; 16:23-28). If we are loving God, loving Jesus, listening to his words spoken by His Spirit to our spirit, loving one another... then our desires will be aligned with His desires, we will ask and he will do what we ask. This is not about self satisfaction, though it satisfies our hearts.  James makes it clear that we don't have because we either do not ask or we ask with selfish motives (James 1). We must abide first, which includes love of Him and his word and his people; then after we are aligned with his desires, we can ask. Our desires will be his desires, and he will do what we ask. He will heal, move mountains, and perform miracles confirming our words. Study the requests of the apostles to see what they asked for, it was almost always "others" or "mission" centered.

# DQ11: True Submission

Top of Form

**Prepare**:  Read *Living the Spirit-Formed Life*, *Chapter 10, "Living a Life of Submission"*

**Participate**: Discuss the relationship between living a life of "true submission" and our sanctification journey in partnership with the Holy Spirit.

Bottom of Form

The mic drop moment of the entire chapter was this statement, "He understands that his submission -- alignment with the authority placed over him -- is the source of the power available to him".[\[31\]](#_ftn31) I recently heard someone define faith as "believing loyalty".[\[32\]](#_ftn32)

As I consider the story of the centurion, I have wondered how a man who wasn't a Jew could be the best example of "faith" in all four gospels (other than Jesus himself). But it is this capacity for believing loyalty (faith) that allowed him to first submit to the authority over him; then within that framework, he can delegate the authority delegated to him.[\[33\]](#_ftn33)

If I am experiencing a powerless life, a life void of meaning, significance, or a general sense of victory; I may need to check to see if I am first submitted to the authority over me. I am no longer my own. I don't get to "have faith to move mountains" unless I am first "only saying what I hear him say".[\[34\]](#_ftn34)

The last line is key. It's not a one-time event. It's so easy to take the mountain top high experience of an altar call and ride it for a few days, weeks, maybe a few months. But then the monotony of normalcy sets in. It is only through an ongoing submission to The Spirit and to other safe human beings that we can find our growth trajectory remains constant. I need to get back into a group.

**Author:** Peter Buike **Date:** Wednesday, February 17, 2021 4:46:00 PM CST **Subject:** RE: DQ11: True Submission

This is our calling then, to grow, and allow G-d to flow from us in love to others. We grow in G-d, in direct proportion to our submission to Him.

So; really, if we boil it down. Our calling is to submit to God's love for us; let that love saturate our every fiber of being, then allow the overflow of that love to run over into other's lives.

# DQ12: Living as a Worshiper

Top of Form

**Prepare**: Read *Living the Spirit-Formed Life, Chapter 12, "Living as a Worshiper"*

**Participate**: Summarize the "altar moments" presented by Pastor Jack. Which one resonated with your heart?Bottom of Form

Through a blending of Eisegesis and Exegesis, Hayford reviews the life of Abraham and draws four after moments.[\[35\]](#_ftn35) The Alter of Promise is when God shows up and makes a promise, and Abraham builds an alter to commemorate and seal that promise.[\[36\]](#_ftn36) The Alter of Intimacy is when Abraham camps between Bethel and Ai and calls on the name of YHWH; indicating a calling of intimacy.[\[37\]](#_ftn37) The Alter of No Return is when Abraham had gone to Egypt and returned to this same camp-site and called on the name of YHWH again. This was Abraham's point of no-return. He will stay in the land God promised him.[\[38\]](#_ftn38) The final Alter of Possession was when Abraham walked the land at length taking possession of what God had promised him. He was building a mental awareness of the promise.[\[39\]](#_ftn39)

One can see a progressive revelation on God's part and a progression of trust on Abraham's part through this journey. He believes God's promise and builds an alter. What is an alter? It is a sacrifice. It cost Abraham things, tangible things, to believe God. He left his father's house and possessions. He was now sacrificing an animal (typically a burnt offering, meaning he wouldn't eat of it, it would be burnt down to ash). Abraham's natural response to God's presence was giving up his own things to accept God's.  I am less moved by any specific instance and more moved by the consistency of response. Abraham's response to God is to "leave all" as Peter said to Jesus.[\[40\]](#_ftn40) I have "left all" for God several times; each occasion cost me more than I planned. Each occasion led to unexpected growth in ways I couldn't have predicted (and wouldn't have chosen ahead of time until it was too late to go back "no return"). Looking back, the cost was worth it, but I'm glad I didn't know what it would cost ahead of time, or I would have shrunk back.[\[41\]](#_ftn41)

# DQ13: Breaking Old Rhythms

Top of Form

**Prepare**: Reading Breaking Old Rhythms: Answering the Call of a Creative God, Chapters 1-4

**Participate**: Discuss 3 key points you heard Amena Brown say about "breaking old rhythms" as they apply to living the Spirit-formed life.

Bottom of Form

Three Key Points, as I see them.

1.       Breaking old rhythms starts with irritation, becoming aware of the fact that "here" is not "there". Sometimes the irritation grows inside of you (like the kind that drives you to leave a job/change careers). Sometimes the irritation is thrust upon you (like a break-up, or even a death). Either way, it forces you to face the need for a change.[\[42\]](#_ftn42)

2.       Breaking old rhythms leads to a fight in one form or another. Ultimately, the fight is between your old self and the new self God is calling you to. When this fight has it's way it "makes you want to quit and question everything you ever staked your life on"; however, it leads you to a more authentic expression of God's call on your life (if you'll let it do its work).[\[43\]](#_ftn43)

3.       Breaking old rhythms means allowing God to lead you onto the dance floor, it means allowing him to be your DJ. Sometimes he will break up the old tunes you thought you knew and change things up in new ways (frightening and exhilarating). Jesus "has this amazing way of connecting stories, beats, people, and rhythms", he takes our life experiences and remixes them with other people's life experiences and allows a fresh story to unfold.[\[44\]](#_ftn44)

This resonated with me in profound ways:

"It starts with a little irritation. The beginning of being annoyed, unnerved, dissatisfied. This feeling grows to become frustration and starts boiling in your chest. This is when you realize you don't like where you are. You want to be somewhere else -- anywhere else but here."[\[45\]](#_ftn45)

After I became a widower, I resigned myself to never dream again. I would serve my children (boys, then 10/13, now 13/16), help them become the men they were created to be. I would dream with them for their dreams. I put aside having any of my own. That lasted for a season, but the irritation drove me. It drove me to start studying and lead me back into school. It drove me to start dating and lead me back into a relationship. It drove me to find ways to help my children beyond the basics of food and school, how could they really thrive in this season? Irritation has been my frequent companion, and has done more good for me than I am comfortable admitting.

*The End*

------------------------------------------------------------------------

[\[1\]](#_ftnref1) LEAH COULTER, PH.D., "Lecture: The SPIRIT-Formed Life Rev 20.Pages," n.d.

[\[2\]](#_ftnref2) "Galations 5 NET Bible," accessed January 19, 2021, https://netbible.org/bible/Galatians+5. NET notes, *tn Grk "walk" (a common NT idiom for how one conducts one's life or how one behaves).*

[\[3\]](#_ftnref3) Skye Jethani, *With: Reimagining the Way You Relate to God* (Nashville: Thomas Nelson, 2011).

[\[4\]](#_ftnref4) Joel B Green, Jeannine K Brown, and Nicholas Perrin, *Dictionary of Jesus and the Gospels.* (Downers Grove: InterVarsity Press, 2014), BAPTISM, http://qut.eblib.com.au/patron/FullRecord.aspx?p=3316699.

[\[5\]](#_ftnref5) Dr. Michael S. Heiser, "Naked Bible 001: Baptism: What You Know May Not Be So," Blog, *The Naked Bible Podcast* (blog), January 21, 2015, https://nakedbiblepodcast.com/podcast/naked-bible-001-baptism-what-you-know-may-not-be-so/.

[\[6\]](#_ftnref6) Jack W. Hayford, *Living the Spirit-Formed Life: Growing in the 10 Principles of Spirit-Filled Discipleship*, Revised edition (Minneapolis, Minnesota: Chosen, a division of Baker Publishing Group, 2017), 68.

[\[7\]](#_ftnref7) Hayford, 67.

[\[8\]](#_ftnref8) Jethani, *With*, 6.

[\[9\]](#_ftnref9) Jethani, 48--49.

[\[10\]](#_ftnref10) Jethani, 9.

[\[11\]](#_ftnref11) Jethani, 31.

[\[12\]](#_ftnref12) Jethani, 11.

[\[13\]](#_ftnref13) Jethani, 6.

[\[14\]](#_ftnref14) Jethani, 64; "Cambridge Dictionary: Find Definitions, Meanings & Translations," https://dictionary.cambridge.org/us/dictionary/english/straw-man, accessed January 27, 2021, https://dictionary.cambridge.org/us/.

[\[15\]](#_ftnref15) M. G., *Easton's Bible Dictionary* (New York: Harper & Brothers, 1893), REUEL---friend of God; *The Lexham English Bible (LEB), Fourth Edition*, Logo Bible Software, Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010), Isaiah 41:8; James 2:23, http://www.lexhampress.com.

[\[16\]](#_ftnref16) Jethani, *With*, 7.

[\[17\]](#_ftnref17) Jethani, 77--82.

[\[18\]](#_ftnref18) Jethani, 98.

[\[19\]](#_ftnref19) Jethani, 110.

[\[20\]](#_ftnref20) Jethani, 99.

[\[21\]](#_ftnref21) Jethani, 124.

[\[22\]](#_ftnref22) Jethani, 140.

[\[23\]](#_ftnref23) Jethani, 139--42.

[\[24\]](#_ftnref24) Jethani, 162.

[\[25\]](#_ftnref25) Jennifer V. Nelson, n.d.

[\[26\]](#_ftnref26) Jack Hayford, "The Beauty of Spiritual Language" (Sermon, First Conference 2016, Gateway Church, Southlake Texas, January 3, 2016), https://www.youtube.com/watch?v=hSOef7lxTGo.

[\[27\]](#_ftnref27) *The Lexham Bible Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott, C., ... Widder, W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham, WA: Lexham Press.* (Billingham, WA: Leham Press, 2016), BOOTHS, FEAST OF, LexhamPress.com.

[\[28\]](#_ftnref28) Hayford, "The Beauty of Spiritual Language."

[\[29\]](#_ftnref29) Hayford, *Living the Spirit-Formed Life*, 147--51.

[\[30\]](#_ftnref30) *LEB*, John 7:37-39; Matthew 7:24.

[\[31\]](#_ftnref31) Hayford, *Living the Spirit-Formed Life*, 166--67.

[\[32\]](#_ftnref32) Dr. Michael S. Heiser, "The Naked Bible Podcast," The Naked Bible Podcast, Naked Bible 197: Hebrews 11, accessed January 30, 2021, https://nakedbiblepodcast.com/episodes/.

[\[33\]](#_ftnref33) *LEB*, Matthew 8.

[\[34\]](#_ftnref34) *LEB*, Mark 11:23; Matthew 21:21; John 12:49.

[\[35\]](#_ftnref35) Hayford, *Living the Spirit-Formed Life*, 217.

[\[36\]](#_ftnref36) Hayford, 219.

[\[37\]](#_ftnref37) Hayford, 218--19.

[\[38\]](#_ftnref38) Hayford, 219--21.

[\[39\]](#_ftnref39) Hayford, 221--22.

[\[40\]](#_ftnref40) *LEB*, Matthew 19:27.

[\[41\]](#_ftnref41) *LEB*, Exodus 13:17.

[\[42\]](#_ftnref42) Amena Brown, *Breaking Old Rhythms: Answering the Call of a Creative God* (Downers Grove, Illinois: InterVarsity Press, 2013), 22--23.

[\[43\]](#_ftnref43) Brown, 43.

[\[44\]](#_ftnref44) Brown, 56.

[\[45\]](#_ftnref45) Brown, 22.
