---
title: 'Untitled Post'
date: '2022-06-09T23:41:00.0000000+00:00'
draft: false
---

<div><br /></div><div><br /></div><div><br /></div><div><br /></div><div>The televisions series <a href="https://www.imdb.com/title/tt4052886/" target="_blank">"Lucifer" (2016-2021)</a> is suprisingly insightful.&nbsp;</div><div><br /></div><h4 style="text-align: left;">First, what the show "Lucifer" doesn't get right.&nbsp;</h4><div>Textually, the show gets almost all of the answers to theological questions wrong. It gets almost all of the details about Angelology/Demonology wrong (although, so does almost the entire modern church, so we can't blame them for that).</div><div><br /></div><div>For information on what the biblical data actually says about the Unseen Realm (contrary not only to most modern television but contrary to most modern Christian teaching as well), see the works of Dr. Michael Heiser:</div><div><ul style="text-align: left;"><li><a href="https://amzn.to/3xCuLCa" target="_blank">The Unseen Realm</a>: Recovering the Supernatural Worldview of the Bible</li><ul><li>Or, for a more layman's reading, the same material but slimmed down is in "<a href="https://amzn.to/3tr5HeZ" target="_blank">Supernatural</a>: What the Bible Teaches About the Unseen World - and Why It Matters"</li></ul><li><a href="https://amzn.to/3xmRm4g" target="_blank">Demons</a>: What the Bible Really Says About the Powers of Darkness</li><li><a href="https://amzn.to/39nStIZ" target="_blank">Angels</a>: What the Bible Really Says About God's Heavenly Host</li></ul><div><br /></div></div><div>The Divine Council Worldview is the basis for most of the claims of the ancient Hebrew writers. Yet again, this fact is missed by both the show and modern western American Christianity. It influences most of the facts it got wrong.</div><div><br /></div><div>A few particulars:</div><div><ul style="text-align: left;"><li>The show claims Angels and Humans never produed offspring before. This is either denial of or ignorance of the Nephelim stories which are the underpinning of nearly all of the Hebrew biblical theology.&nbsp;</li><li>The show claims</li></ul></div><div><br /></div><div><br /></div><h4 style="text-align: left;">Second, what the show "Lucifer" does right.</h4><div>It asks great questions, and ponders deep theological implications of those questions.&nbsp;<div><br /></div><div><br />
<br />
<br />
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
</div></div>