---
title: 'Wolfe Bible Institute (?)'
date: '2022-07-20T11:18:00.0020000+00:00'
draft: false
categories:
  - 'Musing'
---
\~\~\~{=html} My new wife, Jen, is constantly proding me to envision a school of sorts, called (working title):

**Wolfe Bible Institute**

\~ Institute for biblical studies and Jesus Communities \~

I'm thinking more along the lines of:

**The Community Center**

Coffee & Community

But maybe the second funds the first?

While I'm not sure about the name, the general vision is something I've carried for decades, at least since 2003, probably earlier.

In 2003, my friend James and I walked the campus of the church I grew up in, and prayed revival over that space. We both had visions of a multi campus facility there that would impact not just the area but the world\...

In 2022, I'm less inclined to believe that specific campus is the home for the facility, nor even that I'll ever see such a facility in my lifetime\... But if I could plant a seed for it, if I could start a community and maybe someone from that community will go on to do it\... Or maybe even if I just faithfully served 10-20 people, that would be enough? I don't know. I've really scaled down my expectations since life took a lot of turns since those early days.

Throughout the years, the vision has grown with me, matured with me, scaled way back from grandiose visions of greatness (multi million square feet of buildings on multiple acres) to something more possible (maybe renting space in a small meeting room in the back of some business or even local library once a month).

But the highlights are pretty consistent.

TEACHING

* Teach people to read and study the Bible in ways traditional American church usually doesn't. Think: Dr Michael Heiser, NT Wright, Tim Mackie.

* Teach people life skills (balancing their budget or bank accounts, cooking healthy food, basic vehicle maintenance).

* Teach people basic human skills (communicate with spouse, kids, and coworkers, resolve conflict, establish healthy boundaries, clarify thinking, break stronghold cycles, integrated emotions\...). Referring people to professional licensed counseling as needed.

COMMUNITY

* Provide community in ways that matter.

-Not just events for people to attend, but spaces made and purposefully created to forge lifelong friendships, where people come alongside one another to do life together, where men mentor men, women mentor women, where we all come together to celebrate a marriage or mourn a passing.

-NOT the artificial "community/home groups where people meet to have mini church services but never actually connect with one another in meaningful ways.

\- One way of seeing this is having meetings that envite real sharing, like Al-Anon did for me.

\- Another thought is just making space for this by having different spaces (multiple types of seating for different preferences, pool tables library knooks, etc.).

FUNDING:

In part because of the need for spaces that look nothing like traditional church, and in part because I strongly feel it should be a source of giving TO the community and not taking from it, I don't want donations at all.

We'll fund raise donations for local non-profits but only those that provide definite and specific services to the community. No churches or para churches. But food banks, shelters, scholarships, education, etc. Any group giving must meet a specific need felt by the secular (non church going) community at large. The organizations can be religious/Christian in nature, but must meet a specific need.

Funding comes from providing actual products and services to the local (external and internal) community. Coffee Shop, Cafe, (?)\... Something tied to the community that simultaneously offers the types of spaces talked about in the community section above.

If it grew into the larger older vision, it would include mechanic services where student mechanics do the work. Simultaneously training people for a profession while offering the community a discounted service.

Or a culinary school with students operating a restaurant\...

And similar training=new funding opportunities types of endeavors.

TBD\...

But that's the vision I felt I had to write down since I couldn't sleep.

Shalom! ,שׁלוֹם

***[Appendix]{.underline}***

**What do we teach? **

What IS the Bible anyway?

How was it constructed?

How was it used/read?

How was it copied and kept?

Introduction to OT & NT

Old Testament Survey

Pentateuch (Gen-Deut) Books of Moses

Genesis 1-11

Genesis 12-end

Prophets

Historicals

Major v Minor is size not importance

Writings

The wisdom writings that reflect on the history of Israel.

New Testament Survey

The Gospels

Ancient Biographies

The Life of Rabbi Yeshua (Jesus) HaMeshiach (The Anointed One, The Christ).

The Life of Rabbinic Disciples (The Twelve, the 170, and others Jesus touched).

The Jewish and Roman backdrop to these stories

Rabbinic Traditions (Sewing Pearls) and the role of Parables

Second Writings

Epistles -- Working out what it meant to be a Jewish Messianich movement in the Roman empire with Mixed Jewish/Gentile followers.

The Jewish and Roman backdrop to these stories

Intro to the Apocalypse

The Apocalypse as a Genre and other examples of the genre

The literary structure and story arch of The Revelation of Jesus to John

The Seven Letters

The Apocalypse Arch -- Rev 3-22

Intro to the "Old Testament" (Hebrew Scripture) backgrounds and allusions to John's writing

The Message of Revelation (regardless of one's view of eschatology)

Daniel and Ezekiel in Revelation

The possible impacts of good exegesis on Eschatology

Worldview

What is a Worldview?

What is your Worldview in the modern era?

What was the Worldview of the Ancient Near East (ANE), Atiquity, Rome, and the Biblical Authors? How are they similar and different?

What does it mean to think like the biblical authors, how might that differ from the traditions imposed on them by modern western Christianity?

In what ways do historical Christians like Augustine, Luther, Calvin, Arminius, Tyndale, Wesley, Graham, C.S. Lewis, and others share a common worldview and in what ways do each differ as a result of their unique background, experiences, time and place in history?

How do we interpret the Bible?

What is Exegesis and Hermeneutics?

Various approaches that have been applied historically?

How do various approaches color or tint the way we see the text?

Are some approaches more valid than others (wrong, right, or just different)?

Judeo-Christian History

Jewish History

Adam to Abraham, Abraham to Exile, Exile to 1A.D., 1-200 A.D., 200-1800 A.D., 1800-2022 A.D.

Jewish Messianic Movements -

1-200 A.D., 200-1800 A.D., 1800-2022 A.D.

Non-Jewish/Gentile Jesus Movements

Jesus Movement 1-100 A.D.

Jesus Movement 100-400 A.D.

Catholic Christianity, Greek Orthodox Christianity, and Other movements 300-1500 A.D. Tertulian, Augustine, Jerome, Constantine, etc.

Protestant Christianity 1500-1800 -- Luther, Calvin, Arminius, Gutenberg, Tyndale,

Protestant Christianity 1800-1900 -

American Centric Christianity

Protestant Christianity 1900-2022 -- Pentecostal & Charismatic Movements

Protestant Christianity 1900-2022 -- Mainline Denominations

Protestant Christianity 1900-2022 -- Non-Denominational Movements

Non-American Centric Christianity

Protestant Christianity 1900-2022 -- Non-American Movements

Theology -- Theos (God) ology (study) - The Study of God

Jewish, Catholic, Orthodox, Protestant, "Christian", Messianic, theological studies

The various ways different traditions have viewed God and the Bible

To the Jew First / Mixed Jewish/Gentile Family of God

****************

Practical Application -- Life Transformation

****************

How people change

Two Trees

Parable of the Acrobat

How the Bible changes us, and how it doesn't.

Human Needs

Stronghold Cycles

Human Communication Emotional/Fact Over/Covert

Behavior vs Identity

Get Curious about That

****************

Practical Application - Study of specific books and groupings of Books

****************

Pentateuch (Gen-Deut) Books of Moses

Genesis 1-11

Genesis 12-end

Prophets

Historicals

Major v Minor is size not importance

Writings

The wisdom writings that reflect on the history of Israel.

The Gospels

Ancient Biographies

The Life of Rabbi Yeshua (Jesus) HaMeshiach (The Anointed One, The Christ).

The Life of Rabbinic Disciples (The Twelve, the 170, and others Jesus touched).

The Jewish and Roman backdrop to these stories

Rabbinic Traditions (Sewing Pearls) and the role of Parables

Second Writings

Epistles -- Working out what it meant to be a Jewish Messianich movement in the Roman empire with Mixed Jewish/Gentile followers.

The Jewish and Roman backdrop to these stories

Going deeper Apocalypse

The Apocalypse as a Genre and other examples of the genre

The literary structure and story arch of The Revelation of Jesus to John

The Seven Letters

The Apocalypse Arch -- Rev 3-22

The "Old Testament" (Hebrew Scripture) backgrounds and allusions to John's writing

The Message of Revelation (regardless of one's view of eschatology)

Daniel and Ezekiel in Revelation

The possible impacts of good exegesis on Eschatology

\~\~\~
