---
title: 'Should I take that opportunity?'
date: '2022-06-05T17:58:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5434595471773265'
blogger_filename: '/2022/06/should-i-take-that-opportunity.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musing'
---

What does it mean to follow God?&nbsp;<div><br></div><div>I've only ever heard one thing from God clearly, and it took me thirteen years to figure out I ran the wrong way with it.&nbsp;</div><div><br></div><div>Most of what I've felt strongly about from God was just that.... A feeling. An inlikling. An unction. A gut check.&nbsp;</div><div><br></div><div>One of the best phrases I learned in counseling was "get curious about that".&nbsp;</div><div><br></div><div>One of the best things I've learned from my new wife, Jen, is that God's more interested in who I am becoming not what I can do for him; therefore, I should do whatever I feel less to do, it's for me.&nbsp;</div><div><br></div><div>Go to school, or don't.</div><div><br></div><div>Take the job, or don't.</div><div><br></div><div>Start the business, or don't.</div><div><br></div><div>Take the opportunity, or don't.&nbsp;</div><div><br></div><div>Just follow the joy and the curiosity.&nbsp;</div><div><br></div><div>It's not about accomplishments or mission. It's about becoming more genuinely you, in Him.&nbsp;</div><div><br></div><div><br></div>