---
title: 'And thus, a new chapter begins, if you''ll pardon the pun...'
date: '2023-12-31T08:26:00.0000000+00:00'
draft: false
---

<!-- wp:paragraph -->
<p>As 12/31/2023 rolls into 01/01/2024, I'm rebuilding my home website at DarrellWolfe.com.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>I tried to import all my content, and the file was too large. Maybe I'll just start over? I don't know. For now, let this be my Hello, World post. </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>After further review, 01/06/2024, I have decided to start over. My older posts can be found at <a href="https://darrellglenwolfe.blogspot.com/p/start-here.html">Start Here ~ Darrell Wolfe, Storyteller (darrellglenwolfe.blogspot.com)</a>. I may import old content at a later date, or bring forward individual articles. However, I have become an almost entirely new human in the last 5+ years, so I think I will just start over.&nbsp; - 12/31/2023</p>
<!-- /wp:paragraph -->
**That didn't last long. I always think I'm going to like Word Press, I always end up hating it. Blogger.com for life! ***06/01/2024<br />
<br />
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
