---
title: 'Inerrancy... !?'
date: '2023-03-09T15:59:00.0050000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8554028330342276308'
blogger_filename: '/2023/03/inerrancy.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

Inerrancy...&nbsp;<div><br /></div><div><div><a href="https://www.premierunbelievable.com/ask-nt-wright-anything/ask-nt-wright-anything-154-tom-answers-qs-on-universalism-hell-and-salvation/14803.article" target="_blank">Ask NT Wright Anything #154 Tom answers Qs on universalism, hell and salvation</a></div><div><br /></div>
<br />
Inerrancy is a dead end road, that has no purpose or benefit. That is a summary of Tom's (NT Wright) response to the topic in this podcast. It was a concept born illegitatemly from the enlightment rationalism movements of the 1700-1800s.&nbsp;</div><div><br /></div><div>That got me thinking, is the American Church good for anything? Like, the longer I deconstruct modern western American Christianity, look into the Bible for what it is and not what we tried to make it, and connect with the living-breathing-vibrant history of the Bible and various worldwide Christian mvoements for 2,000 +/- years...&nbsp;</div><div><br /></div><div>The more I wonder if we're the ones who need to be "saved", from ourselves.</div><div>
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
</div>