---
title: 'Donald Trump, an evaluation of a divisive character'
date: '2024-07-01T22:48:00.0000000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'DRAFT'
blogger_post_id: '3365260374082070099'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<div><br /></div><div><br /></div><div><br /></div><h4 style="text-align: left;">Arguments For Donald Trump</h4><div><ul style="text-align: left;"><li><b>Economic Policy</b>: Supporters argue that his policies, like tax cuts and deregulation, have benefited the economy by increasing GDP growth and reducing unemployment rates (prior to the COVID-19 pandemic).</li><ul><li>In reality, his tax cuts favored the rich, punished the poor, and defunded important government infrustructure leading to increasing the national debt.</li></ul><li><b>Judicial Appointments</b>: Many conservatives appreciate his appointment of conservative judges to the federal judiciary, including three Supreme Court justices, which they believe will have a long-lasting impact on American law.</li><ul><li>In reality, these activisist judges produced sweeping reformations that resulted in removing protections, reducing rights, and endangering american citizens. All of their decisions should have the justices he appointed removed from office.</li></ul><li><b>Foreign Policy</b>: Some credit him with fostering better relationships with certain foreign leaders and taking a hard stance against what he considered unfair trade practices, as well as promoting American interests first, encapsulated in his "America First" policy.</li><ul><li>In reality, he was the laughing stock of the world, never taken seriously, and he made our place in the world less secure.</li></ul><li><b>Immigration</b>: His tough stance on immigration, including building a border wall and enforcing strict immigration laws, has been praised by those who prioritize border security and law enforcement.</li><ul><li>His position on immigration is based on racism, and only serves to make the US less secure and more divise.</li></ul><li><b>Deregulation</b>: He rolled back numerous regulations, which his supporters argue has helped businesses by reducing the bureaucratic burden and stimulating economic growth.</li><ul><li>Deregulation almost always does, and has in his case, lead to stifling the economy and making the us less secure, less safe, empowering corporate monsters and disempowering and unprotecting consumers.</li></ul></ul></div><h4 style="text-align: left;">Arguments Against Donald Trump</h4><div>Divisiveness: Critics argue that his rhetoric and actions have deepened societal divisions, often appealing to racial and ethnic tensions, and undermining democratic norms.</div><div><br /></div><div>Handling of COVID-19: His administration's response to the COVID-19 pandemic has been widely criticized for being slow and disorganized, which may have exacerbated the health crisis in the United States.</div><div><br /></div><div>Impeachments: Trump was impeached twice by the House of Representatives; first for abuse of power and obstruction of Congress, and second for incitement of insurrection. Although acquitted by the Senate both times, these events are central to criticisms of his presidency as undermining democratic institutions and norms.</div><div><br /></div><div>Foreign Policy: While some praise his unconventional approach, others criticize it for alienating allies, cozying up to authoritarian leaders, and being erratic and lacking in strategic coherence.</div><div><br /></div><div>Ethics and Corruption: Allegations of self-dealing, refusal to divest business interests, and other ethical concerns have been a continuous source of controversy.</div>
<br />
<br />
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
