---
title: 'Get To Know You Bio'
date: '2024-09-03T06:32:00.0000000+00:00'
draft: false
categories:
  - 'Bio'
---
### I am Darrell G Wolfe, Storyteller, Writer, Thinker, Armchair Theologian, Reconstructing The Way of Yeshua at www.NoHiding.Faith. I hail from North Idaho (near Coeur dAlene).

I grew up as a pastor's kid in the Disciples of Christ (DOC), my dad was an alcoholic pastor (MDiv, DMin) turned atheist crack-addict psychologist (MFT). Meanwhile, I was having visions and spiritual experiences as a child that did not match the experiences of others in my circles. After our family left the ministry in 1996 (16-years old for me), I went through multiple expressions and traditions, and landed in the Word of Faith / Pentecostal movement for years (2003-2018).

After a mental health crises and recover in 2016-2017, then loosing my late-wife in 2018, I was spurred by questions my kids and I didn't have the framework to answer. I finally took the journey I had been avoiding for decades and went to Bible School. I completed my BA in General Christian Studies at The Kings University (TKU) in December 2022.

Recently, after spending time soul-searching, I realized I was answering an awful lot of questions for people about the Bible. I found myself reading biblical scholarship in my free time, and missing my access to EBSCOhost, JSTOR, and other repositories of academic journal articles. I found myself hungry for more. So here I am, at Fuller Theological Seminary, getting a MATS, with very little idea as to whether this will always be a passion-project or if it will ever pivot into a paid career.

Meanwhile, my "tent making job" is a Business Intelligence Analyst (BIA) where I write SQL, Python, and work with Excel, Power BI, and Tableau for a local county agency.

I am remarried to a fellow widow, and together we have six kids ranging 12-27.

Other terms that describe me:

- AuDHD
- INFJ/INTP (INXX)
- Clifton Strengths: Intellection, Learner, Ideation, Achiever, Input
  - But I'm curious to see if those changed since 2014, having experienced such a massive upheaval in my own personal growth, AuDHD demasking, etc.
- SciFi, Fantasy nerd, recently completed:
  - Wheel of Time
  - He Who Fights With Monsters
  - Mistborn
- Current Top Favorite Bible Thinkers: Michael Heiser, Tim Mackie, NT Wright, Mark Nanos, Mark Kinzer, Thorsten Moritz

The books that made me:

Bauckham, Richard. *Jesus and the God of Israel: God Crucified and Other Studies on the New Testament's Christology of Divine Identity*, n.d. <https://www.amazon.com/Jesus-God-Israel-Testaments-Christology/dp/0802845592>.

Cloud, Henry, and John Sims Townsend. *Boundaries: When to Say Yes, How to Say No to Take Control of Your Life*. Updated and Expanded \[edition\]. Boundaries. Grand Rapids, Michigan: Zondervan, 2017.

---------. *How to Have That Difficult Conversation You've Been Avoiding: With Your Spouse, Adult Child, Family, Boss, Coworker, Friend, Parent or Someone You're Dating*. Boundaries. Grand Rapids, Mich: Zondervan, 2006.

Du Plessis, David. *The Spirit Bade Me Go: The Astounding Move of  God in the Denominational Churches*. Alucha, FL: Bridge-Logos Publishers, 1970.

Du Plessis, David, and Bob Slosser. *A Man Called Mr. Pentecost: David Du Plessis as Told to Bob Slosser*. Plainfield, N.J.: Logos International, 1977.

Fee, Gordon D., and Douglas K. Stuart. *How to Read the Bible Book by Book: A Guided Tour*. Grand Rapids, Mich: Zondervan, 2002.

---------. *How to Read the Bible for All Its Worth*. 3rd ed. Grand Rapids, Mich: Zondervan, 2003.

Hamp, Bob. *Think Differently Live Differently Keys to a Life of Freedom.* Southlake, Texas, USA: [bobhamp.com](http://bobhamp.com), 2016. <https://tdacad.com/product/think-differently-live-differently-book/>.

Heiser, Michael. *Angels: What the Bible Really Says about God's Heavenly Host*, 2018. <https://search.ebscohost.com/login.aspx?direct=true&scope=site&db=nlebk&db=nlabk&AN=1900613>.

---------. *Demons: What the Bible Really Says about the Powers of Darkness*. Bellingham, WA: Lexham Press, 2020.

---------. *The Unseen Realm: Recovering the Supernatural Worldview of the Bible*. First edition. Bellingham, WA: Lexham Press, 2015.

Kinzer, Mark. "Finding Our Way Through Nicaea: The Deity of Yeshua, Bilateral Ecclesiology, and Redemptive Encounter with the Living God." *Kesher Journal* 24 / SUM 210 (2010). <https://www.kesherjournal.com/article/finding-our-way-through-nicaea-the-deity-of-yeshua-bilateral-ecclesiology-and-redemptive-encounter-with-the-living-god/>.

Moraff, Jason. "'Among My Own Nation': Reading the Way, Paul, and 'the Jews' in Acts within Judaism." Dissertation, Fuller Theological Seminary, School of Theology, Center for Advanced Theological Studies, 2021.

Nanos, Mark D. "Paul and Judaism, Why Not Paul's Judaism." *Reading Paul Within Judaism : Collected Essays of Mark D. Nanos, Vol. 1*. Part 1 A New Approach to the Apostle Paul as a Torah-Observant Jew. Eugene, OR: Cascade Books, 2017. <https://web.p.ebscohost.com/ehost/ebookviewer/ebook/bmxlYmtfXzE2OTE4MzhfX0FO0?sid=c0e38d84-c9c6-45ca-a253-4921d0fce688@redis&vid=9&format=EK&rid=2>.

Rudolph, David J., and Joel Willitts, eds. *Introduction to Messianic Judaism: Its Ecclesial Context and Biblical Foundations*. Grand Rapids, MI: Zondervan, 2013.

Sailhamer, John. *The Pentateuch as Narrative: A Biblical-Theological Commentary*. Library of Biblical Interpretation. Grand Rapids, Mich: Zondervan, 1995.

Scazzero, Peter. *Emotionally Healthy Spirituality: It's Impossible to Be Spiritually Mature, While Remaining Emotionally Immature*. Zondervan, 2014. <https://www.amazon.com/Emotionally-Healthy-Spirituality-Impossible-Spiritually/dp/B08SHX5632/ref=sr_1_6?crid=30T0P57ZF972Q&keywords=The+Emotionally+Healthy+church&qid=1643520881&s=books&sprefix=the+emotionally+healthy+churc%2Cstripbooks%2C221&sr=1-6>.

Schiffman, Lawrence H., and Chaim Potok. *Reclaiming the Dead Sea Scrolls: The History of Judaism, the Background of Christianity, the Lost Library of Qumran*. Anchor Yale Bible Reference Library. New Haven, Conn.: Yale Univ. Pr, 2009.

Synan, Vinson. *The Holiness-Pentecostal Tradition: Charismatic Movements in the Twentieth Century*. 2nd ed. Grand Rapids, MI; Cambridge, U.K.: William B. Eerdmans Publishing Company, 1971.

Tverberg, Lois, and Ann Spangler. *Sitting at the Feet of Rabbi Jesus: How the Jewishness of Jesus Can Transform Your Faith*. E-Edition via Logos Bible Software. Grand Rapids, Michigan: Zondervan, 2018.

Walton, John H. *The Lost World of Genesis One: Ancient Cosmology and the Origins Debate.* Westmont: InterVarsity Press, 2010. <https://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=2030851>.

Welton, Jonathan. *Raptureless*. 3rd Edition Printing. Place of publication not identified: Bookbaby, 2015. <http://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=4188734>.

Witherington, Ben. *Reading and Understanding the Bible*. Oxford ; New York: Oxford University Press USA, 2015.

Wright, N. T. *Jesus and the Victory of God*. 1st North American ed. Vol. 2 of *Christian Origins and the Question of God*. Minneapolis: Fortress Press, 1996. <https://www.logos.com/product/37361/christian-origins-and-the-question-of-god-series>.

Wright, N. T. *Surprised by Hope: Rethinking Heaven, the Resurrection, and the Mission of the Church*. San Francisco, CA: HarperOne an Imprint of Harper Collins Publishers, 2014.

Wright, N. T. *The Day the Revolution Began: Reconsidering the Meaning of Jesus's Crucifixion*. San Francisco, CA: HarperOne an Imprint of Harper Collins Publishers, 2018.

Wright, N. T., and Michael F. Bird. *The New Testament in Its World: An Introduction to the History, Literature, and Theology of the First Christians*. London : Grand Rapids, MI: SPCK ; Zondervan Academic, 2019.

Yancey, Philip. *Where Is God When It Hurts?* Grand Rapids, Mich.: Zondervan, 1997.

*David DuPlessis  - "Forgiveness" June 30, 1967  Pm*. Audio Recording: Posted to YouTube by Jay Hearn, 1967.

*Prohibition Theology (@prohibitiontheology)*. TikTok Channel, n.d. <https://www.tiktok.com/@prohibitiontheology>.
