---
title: 'Letter to MY Body - A Class Assignment Foundations_of_PsychologicalSense_PF501'
date: '2025-01-11T05:55:00.0000000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6163357996065207895'
blogger_filename: '/2025/01/letter-to-my-body-class-assignment.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Class Assignment'
---

<h4 style="text-align: left;">Dear Body,</h4>

<p class="MsoNormal">In many ways I cannot identify with the first half of
McBride’s letter. It sounds like she had a different relationship with her body
than I do mine. However, I do find there are things I could say to you. We’ve
discovered together that the biblical author’s worldview is that of an embodied
worldview. <o:p></o:p></p>

<p class="MsoNormal">For years, I lived with an eschatology that told me I had to
escape from my body. The body was evil, dirty, wrong, sinful. The highest hope
was to get raptured out of my body and into a disembodied heaven when I die. I
longed for that escape. I wondered why I should have to be stuck in a body that
betrayed me. If the hope is to go to heaven when I die, shouldn’t I hasten that
future? Shouldn’t I try to die? Isn’t escape the answer? <o:p></o:p></p>

<p class="MsoNormal">While I was never serious enough about that question to take
immediate action, I engaged in “long tail suicide”. I used you in such a way as
to use you up, such that I could hasten my departure. This led to a full mental
breakdown in 2016, and a long journey of getting in touch with the body I had
dismissed and ignored. You slowly stopped being a prison, and became my salvation.
By allowing myself to feel emotions (rather than suppress them), I became a “fully
integrated human” capable of experience conflicting emotions simultaneously.
When we first had that experience we thought we were going crazy, but we were
reassured we were becoming integrated.<o:p></o:p></p>

<p class="MsoNormal">Then we reconstructed just about every lie we inherited from
US-American Churchianity by re-learning the gospel of the biblical authors. We
learned better. We discovered that the hope is not for a disembodied future,
but a more fully embodied present and re-embodied future. We learned that this
is God’s good earth, and that we should be fruitful and multiply in it. We
should be looking for ways to bring God’s domain into partnership with our
domain, allowing the overlap of heaven and earth, not the departure from earth
to heaven.<o:p></o:p></p>

<p class="MsoNormal">When we discovered this, we stopped wanting to escape, and
started looking to honor you as the body we were given to live an embodied faith.<o:p></o:p></p>

<p class="MsoNormal">In light of the front row seat we just had for the last three
months watching Mike Wolfe mistreat his body unto death, and in light of all
these growing points. I submit to you the following:<o:p></o:p></p>

<p class="MsoNormal">I’m sorry for giving you food (quality and quantity) that
was not ideal for your operational best. <o:p></o:p></p>

<p class="MsoNormal">I’m sorry for allowing jocks from high school whom I haven’t
seen in over twenty years continue to keep you out of the gym so that you could
reach your highest potential.<o:p></o:p></p>

<p class="MsoNormal">I’m sorry for ignoring your screams to be heard until it
landed us on 14 medications just to function. <o:p></o:p></p>

<p class="MsoNormal">I’m proud of the progress we’ve made on our ability to
process and sit with “feels” in healthy ways. <o:p></o:p></p>

<p class="MsoNormal">I’m proud of the courage it took us to start Trulicity
(GLP1) and stab ourselves every week since July, and I’m proud of the fifteen
pounds we’ve lost combining that with the gym. <o:p></o:p></p>

<p class="MsoNormal">I’m proud of the work we’ve done in the gym, discovering it
wasn’t so scary afterall, and the strength we now bring to other areas of life
because of it, and the confidence physical health is bringing to our
relationships and work.<o:p></o:p></p>

<p class="MsoNormal">I’m proud of you for coming back after two broken legs and decades
of sedentary lifestyle.<o:p></o:p></p>

<p class="MsoNormal">I love you for supporting me in this journey. <o:p></o:p></p>

<p class="MsoNormal">I hope that I will continue this journey with you, so that
we don’t end like Mike Wolfe ended.<o:p></o:p></p>

<p class="MsoNormal">I hope to take you on new journeys and discoveries, and that
will require strength we don’t have today, but we are working toward.<o:p></o:p></p>

<p class="MsoNormal">I’m sorry to say… that’s going to mean some hard days at the
gym ahead and hours of the day you haven’t seen in decades. But it will be
worth it when you smell the sea air on the coast of Italy or feel the foggy
Scottish highlands on your face.<o:p></o:p></p>

<p class="MsoNormal">Let’s have an adventure, <o:p></o:p></p>

<p class="MsoNormal">Darrell<o:p></o:p></p>
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
