---
title: "The Errors of US American Conservative Evangelical Christianity: An Example"
date: "2026-07-29"
draft: false
categories:
  - "Christianity"
  - "Politics"
  - "Personal Reflections"
---

## An Example of Why the Right Is Wrong About Almost Everything

I was sent this video because it was “funny.” In reality, this is a perfect short example of what’s wrong with US American Christianity in particular and the US American Right and conservatives in general. I’ve decided to write about it point by point because it would be a good resource to share when people wonder why I take such an opposite view these days from where I was prior to 2020.

**Video short/clip:** [Brad Stine, “Being Offended Isn’t an Argument”](https://www.facebook.com/reel/1380396410299003)

Stine is coming from an obvious worldview, but it’s clear he has never questioned his own worldview. This is common among strongly opinionated people who like to shout everyone down or argue a point rather than explore it with curiosity and evaluate the evidence.

## On Political Correctness

There’s a ditch on both sides.

“Political correctness,” at its heart, is the gospel. It’s about loving people in the way they feel loved.

On one side, you have extreme—maybe most—conservatives, rightists, and US American evangelicals who wouldn’t know Jesus if he came and stood in front of them. Nearly everything they stand for is anti-Christ, and the one thing they get right—being pro-life—they still get demonically wrong in its application.

On the other side, you have extreme liberals and leftists who also wouldn’t know Jesus if he came and stood in front of them. They actually, often accidentally, get the gospel more right than the Right. But they still hold odd, cognitively dissonant positions. For example, the true extreme—and this is **not** most—might advocate for an elective, not medically necessary, third-trimester abortion. The Right and Left generally agree that would be evil.

## “Anti-American”

This is interesting because it depends on what you see the USA as. If you see the USA as a place that gives you the right to be an asshole, then sure, he’s right.

But self-censorship is something all the Founding Fathers would agree is a good thing, as would any mature person who is not a child. It’s part of walking in the love of Jesus. We don’t offend for the sake of offending. Truth is spoken in love. Truth without love is meaningless and evil.

> “It means you don’t stand for anything.”

Not at all. In fact, self-censoring means you are aware of the audience and choose to reach that audience in ways they can hear. A person who genuinely cares about reaching hearts—not just shouting out of a sense of self-righteousness—will absolutely self-censor in order to connect heart-to-heart with the people they want to reach.

They will also agree with Albert Einstein that they don’t know everything and will hold a certain level of humility about all their positions.

If doing one and a half degrees in biblical studies taught me anything, it’s that there are **zero** beliefs held universally among all Christians. It’s entirely possible, even likely, to vehemently hold a position that is patently false.

## “Merry Christmas”

In the study of logic, this is called a false premise, which is often part of the larger concept of a straw man argument. It is also intended to incite moral panic.

The “attack on Christmas” is one of those silly bogeymen conservatives often cry about. In truth, there is no such thing. There is zero evidence for it.

The evidence often cited is usually—nearly always—manufactured by a person or group into something it is not. For example, the change in Starbucks cups has **nothing** to do with some imaginary attack on Christmas. It’s just a silly, nonexistent conservative bogeyman. If you follow the conservative movement since the 1950s, you find that it thrives on and even relies on such imaginary bogeymen—an “evil bad” to be afraid of.

The only people I’ve **ever** heard talk about this bogeyman were Christians. There is no mass movement in the outside world attacking Christmas. Christmas is perfectly welcome in every business I’ve ever visited, worked for, or heard of. Even more liberal-leaning businesses don’t make a big deal about it.

Out of their own sense of love and inclusion for others, they usually change their messaging to “Happy Holidays” or wish people well on each of the individual holidays that take place during that season.

This is also a good example of white, male-dominant cultural Christianity centering itself over others, which is far from the love of Jesus.

Judaism had been celebrating Hanukkah for one to two centuries before Jesus. It is part of the Jewish and biblical tradition. Jesus himself likely celebrated Hanukkah. See [“Feast of Dedication: How Jesus Fulfills Hanukkah”](https://www.thegospelcoalition.org/article/feast-dedication-jesus-hanukkah/).

> “At that time the Feast of Dedication took place at Jerusalem; it was winter.”
>
> —John 10:22

And yet, most Christians do not talk about Hanukkah, an attack on Hanukkah, or honor it in any way. Some do if they are either Messianic or deeply interested in the Jewish roots of Christianity, but that is a small group compared with the majority of US American Christianity.

There are other winter holidays centered on other religions and cultures.

So when a company chooses, of its own free will, to say “Happy Holidays,” it is shorthand for honoring all the traditions. It is, in fact, the love of Jesus demonstrated. It’s simply shorter than naming them all and accidentally leaving one out. There are, in fact, many holidays—not just your mostly white, US American, Christian, majority-culture-centered one.

Conservatives have no real policy stances and only ever destroy any society or economy they control. Fear is their only tool, which in and of itself should make legitimate Jesus followers curious about why any Christian would align with them.

## “Truth Is Offensive”

One of the most common things I heard in my 40 years as a conservative was that truth is, by nature, offensive.

This is partially true—mostly not, but partially. Truth evokes a sense of freedom, not offense. However, psychologically speaking, the human brain is designed to preserve patterns. Even an unhealthy pattern is kept instead of seeking a newer, healthier pattern because that’s how the brain is wired. It takes an effort of will to override this and move to healthier patterns. Usually, some pain in the current pattern forces this change. A sick person who almost dies suddenly decides to hit the gym.

Generally, conservatives—especially Western Christians—hold to the idea of certainty because they are afraid of even the possibility that they could be wrong. US American Christianity has taught them to fear for their eternal salvation and therefore avoid questioning anything too much.

This is, of course, silliness and anti-Christ. Questions and exploration are an important part of authentic faith, which all the patristics advocated. US American Christianity is the church of Laodicea in Revelation: it thinks itself rich but is actually blind and naked. There is very little truth in any US American pulpit.

> “I wouldn’t have said it if it wasn’t right.”

That is a common arrogance among modern Western evangelicals.

> “You simply have to say you’re offended and everybody else has to back off.”

This is another false flag and false premise in a straw man argument that fails to represent any real development in societal growth and collective understanding. It is also, as usual, the arrogant rightist point of view. In fact, it is the very arrogance in this view that turns the tables, advocating for everyone to bow to dominant white male cultural standards.

Ironically, he goes on to say that he’s offended by offended people. Here, he accidentally confesses the real truth about conservatism: conservatives need a false enemy to be worked up about because they refuse the real growth of examining their own motives, understandings, and walk of love.

## Fostering Curiosity and Love

Nothing in this article is intended to be angry or mean toward US American Christian conservatives. I was one for 40 years.

It was the academic study of the Bible and growing closer to the heart of Jesus’ teaching and ministry that showed me just how far I was from the heart of Jesus in my conservatism.

This article is a quick review of a comedian who exemplifies some of the most dangerous and harmful aspects of white, male-dominant US American Christian conservatism.

It is intended to provoke curiosity and issue a call to action in love.

### Curiosity

The hardest part about growing up as an autistic Christian conservative—undiagnosed until age 42—was my natural curiosity. I had so many questions. My questions were often answered in one of two ways by pastors, youth pastors, and other Christians:

1. Simplified answers that one should simply take at face value and believe, not allowing doubt to rob one of assurance.

2. A call to simply “have faith” and “don’t doubt,” with an appeal to the mystery of God as if to say, “We don’t know; we just trust.”

True faith is never blind and does not require a lack of thought.

Faith (*pistis*) is a result of experiences with an individual or institution that bring about trust. If I say I’ll do something but have a history of flaking, you won’t have faith that I’ll do it. But if I’m known for always doing what I say, you’ll have faith that I will. That is what faith means.

We should be curious. We should ask all the questions. There is no question that should not be asked.

> “Alone among the patriarchs, he dies in exile. Jacob wrestles, as his descendants—the children of Israel—continue to wrestle with the world.”
>
> —Jonathan Sacks, *Covenant and Conversation: Genesis, the Book of the Beginnings* (Maggid Books and the Orthodox Union, 2009–2019)

Jacob wrestled with God, and the people of Abraham continue to wrestle with God today. As should we.

### Love

The one thing US American evangelical Christians are known for more than anything else is their hate. There is a popular quote in ex-evangelical spaces:

> “There is no hate like Christian love.”

We have cute little catchphrases that help us feel better about our hate:

> “Hate the sin, love the sinner.”

> “Speak truth in love, but sometimes the truth offends, brother.”

Christian people have been using biblical texts to hate from the earliest times, as the [essay on Ignatius](../biblical/2025-10-13-the-god-bearer-ignatius-bishop-of-antioch.qmd) demonstrates.

The fact is, we should be known for our love—only our love.

We continue to (a) hold one another accountable for a variety of opinions we impose on each other, pretending that these opinions about “sin” are correct, and (b) attempt to hold those outside our immediate church-body community accountable to them.

1. You have no business deciding that you think something is bad and holding anyone but yourself accountable to it. Yes, that includes abortion, since we get the science and nuance of that wrong 99 percent of the time.

2. You have no business involving yourself in community or group accountability unless those people know you personally, in real life. If someone has not looked you in the eye and agreed to walk with you in some way, their life is none of your business.

Yet we walk around as if we should be judging the world. That’s not my job. My job is to love everyone who comes into my presence. If, and only if, they ask, I may share what wisdom I have—as long as I remember that I don’t know everything and don’t act as though I’m definitely right about what I say.

If you aren’t known for your love, you aren’t following Jesus. It’s that simple.

Shalom! This has been Random Thoughts with Darrell.
