---
title: 'Genesis 1: Dr John Walton Explains Origin Stories And Accurate Genesis Interpretations'
date: '2015-08-08T16:49:00.0010000+00:00'
draft: true
blogger_blog: 'Discerning The Time'
blogger_status: 'LIVE'
blogger_post_id: '531603301941688751'
blogger_filename: '/2015/08/genesis-1-dr-john-walton-explains.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Discerning The Time/feed.atom'
categories:
  - 'Bible Background'
---

<h3>
</h3>
<h3>
Origin Stories - Who's the audience, and what is being communicated?</h3>
<br />
<br />
I fist learned of <a href="http://www.wheaton.edu/Academics/Faculty/W/John-Walton" target="_blank">Dr John Walton</a>&nbsp;on the <a href="https://www.youtube.com/watch?v=KciqJt-9MXM" target="_blank">Phil Vischer podcast #80</a>. Dr Walton is a Conservative Old Testament Professor at Wheaton Univ. Dr Walton wrote about his trip to explain alternate understandings in an article on BioLogos' website:&nbsp;"<a href="http://biologos.org/blog/john-waltons-world-tour-part-1" target="_blank">Reflections on Reading Genesis 1-3: John Walton’s World Tour, Part 1</a>".&nbsp;He makes several interesting points in his talk with Phil and in his article. <br />
<br />
<ul>
<li><a href="http://biologos.org/blog/john-waltons-world-tour-part-1" target="_blank">http://biologos.org/blog/john-waltons-world-tour-part-1</a></li>
<li><a href="http://biologos.org/blog/john-waltons-world-tour-part-2" target="_blank">http://biologos.org/blog/john-waltons-world-tour-part-2</a></li>
<li><a href="http://biologos.org/blog/john-waltons-world-tour-part-3" target="_blank">http://biologos.org/blog/john-waltons-world-tour-part-3</a></li>
</ul>
<br />
<br />
<h4>
Genesis One is an origin story. But what kind? </h4>
<br />
<b>House VS Home</b><br />
<br />
<blockquote class="tr_bq">
"<i>The material focus that is common today would yield a story about the origins of the (cosmic) house. The functional focus that I believe describes the biblical text would yield a story about the origins of the home (sacred space).</i>" John Walton</blockquote>
The purpose of Genesis is to speak to an ancient audience about the home God created. It is the origin of people on earth, not the origin of (creation of) the planet earth. You can talk about origins in terms of someone building a house (electricity, plumbing, framing), or you can talk about origins in terms of a home (den, office, bedroom). The home story is the story Genesis is telling, not a house story. Genesis is not discussing material objects (atoms, chemical elements), it is discussing the creation of the order of mankind.<br />
<br />
A house can stand there for 100's of years, but it becomes a home the moment a person moves in. The earth was ordered in Genesis for people to move in.<br />
<br />
<br />
<h4>
Audience Perspective - The bible is written for us, not to us.&nbsp;</h4>
<blockquote class="tr_bq">
<i>"He is trying to help the Israelites understand the gravity of what is about to happen. They are ready to establish sacred space defined by the indwelling presence of God for the first time since Eden. So he explains to them that God had planned for the cosmos to be sacred space with him dwelling in the midst of his people—he had set up the cosmos and ordered it for that very purpose."</i>&nbsp;John Walton</blockquote>
<blockquote class="tr_bq" style="-webkit-text-stroke-width: 0px; color: black; font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px;">
</blockquote>
Do not think of Genesis being communicated to Adam and Eve, but to an ancient Moses to Israel. The audience bring written to, is the key to understanding the author's intent. We cannot take modern questions, and imposing them onto a text that was never intended to answer them.<br />
<div>
<br /></div>
<div style="-webkit-text-stroke-width: 0px; color: black; font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; margin: 0px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px;">
<br />
<br /></div>
<h4>
Very Good: Order Not Perfection</h4>
<blockquote class="tr_bq">
<i>"Creating a room: In dinner table conversation one night, my wife and I were talking about the room in our house we call the “den,” and it led to an interesting observation: Naming a room and giving it a distinct function distinguishes (separates) it from other rooms and represents the “creation” of the room. In our house, a room had previously been used as a dining room by its former owners. We decided we didn’t want it to be a dining room so we called it a “den,” gave it a function as a den, put in it the furniture of a den and began to use it that way. By its name and function it was distinguished from other rooms in the house and thus the den was created. And it was good (functioned as it was intended to function). This serves as a good illustration of the role that naming, separating and determining a function have in the creation of a room and its existence as that room."</i> John Walton</blockquote>
<div>
<br /></div>
To order a thing, it to give it function. Things were "good" because they were in order, and they functioned in their intended order.<br />
<br />
<a href="https://www.youtube.com/watch?v=KciqJt-9MXM" target="_blank">Podcast#80 (50:00)</a><br />
<blockquote class="tr_bq">
<i>When God says in Genesis 1, God says it was all "Very Good"</i>, what do you do with that? Skye</blockquote>
<blockquote class="tr_bq">
<i>"Very Good" is not a term that pertains to righteousnesses, morality, or perfection. It is a term that applies to &nbsp;things working the way that they were designed to work. When God says that it is "Very Good" it means that Order has been achieved in that area, in that issue, and therefore it's ready to function properly. I use the example; when I get on a plane I assume the pilot is in the cockpit going through a checklist 'check, check, check'; 'very good, very good, very good'. He's saying everything is ready to run. It doesn't mean he's making them at that moment, it doesn't mean it's perfect; although I hope it is very functional. Flaps Good. Engine Good." </i>John Walton</blockquote>
<br />
The earth has three states: Order, Non Order, and Disorder. In the creation story, there is Non Order, God orders things enough for man to function on the planet. Not ALL things are ordered. There is still a sea, there won't be in the new creation (<a href="http://biblehub.com/revelation/21-1.htm" target="_blank">Revelations 21:1</a>).<br />
<br />
<h4>
Why do we need a Tree of Life? </h4>
<br />
Adam was not immortal. The Tree of Life was Adam's key to continually restoring LIFE. During the fall Adam did not introduce death into the world, he failed to obtain LIFE for the world.<br />
<div>
<br /></div>
Death Expounded. What is death exactly and when did it come into being?<br />
<blockquote class="tr_bq">
<i>"Given the position that I have taken, Adam was created mortal (and with pain and suffering—after all, “good” does not mean “perfect”), but he was given the hope for life through the tree and (more importantly) through relationship with God in his presence. This means that Adam did not bring death, pain, and suffering to an immortal humanity—he simply failed to acquire life for them (forfeited access to the tree of life; the need for the tree of life indicated their mortality)."</i> John Walton</blockquote>
<br />
By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">DarrellWolfe</a><br />
<br />
<a href="http://discerningthetime.blogspot.com/" target="_blank">DiscerningTheTime</a><br />
<br />
<a href="http://discerningthetime.blogspot.com/" target="_blank">http://discerningthetime.blogspot.com</a><br />
<br />