---
title: 'The 70 weeks of Daniel 9, The Age of Grace, and the Last 7 Years.'
date: '2016-05-30T16:16:00.0030000+00:00'
draft: true
blogger_blog: 'Discerning The Time'
blogger_status: 'DRAFT'
blogger_post_id: '7013837773065972373'
blogger_filename: '/2016/05/the-70-weeks-of-daniel-9-age-of-grace.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Discerning The Time/feed.atom'
---

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<a href="http://www.biblestudytools.com/nkjv/daniel/passage/?q=daniel+9:20-27" target="_blank">Daniel 9:20-27 NKJV</a><br />
<br />
<blockquote class="tr_bq">
<i>20 Now while I was speaking, praying, and confessing my sin and the sin of my people Israel, and presenting my supplication before the Lord my God for the holy mountain of my God, 21 yes, while I was speaking in prayer, the man Gabriel, whom I had seen in the vision at the beginning, being caused to fly swiftly, reached me about the time of the evening offering. 22 And he informed me, and talked with me, and said, "O Daniel, I have now come forth to give you skill to understand. 23 At the beginning of your supplications the command went out, and I have come to tell you, for you are greatly beloved; therefore consider the matter, and understand the vision:</i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<b><i>24 "Seventy weeks are determined For your people and for your holy city, To finish the transgression, To make an end of sins, To make reconciliation for iniquity, To bring in everlasting righteousness, To seal up vision and prophecy, And to anoint the Most Holy.</i>&nbsp;</b></blockquote>
<blockquote class="tr_bq">
<i>25 "Know therefore and understand, <b>That from the going forth of the command To restore and build Jerusalem Until Messiah the Prince, There shall be seven weeks and sixty-two weeks</b>; The street shall be built again, and the wall, Even in troublesome times.&nbsp;</i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i>26 "And after the sixty-two weeks Messiah shall be cut off, but not for Himself;</i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i>And the people of the prince who is to come Shall destroy the city and the sanctuary. The end of it shall be with a flood, And till the end of the war desolations are determined.</i>&nbsp;</blockquote>
<blockquote class="tr_bq">
<i>27 Then he shall confirm a covenant with many for one week; But in the middle of the week He shall bring an end to sacrifice and offering. And on the wing of abominations shall be one who makes desolate, Even until the consummation, which is determined, Is poured out on the desolate."&nbsp;</i></blockquote>
<br />
Breakdown<br />
<br />
<br />
62+7=69<br />
<blockquote class="tr_bq">
<b><i>24 "Seventy weeks are determined For your people and for your holy city, To finish the transgression, To make an end of sins, To make reconciliation for iniquity, To bring in everlasting righteousness, To seal up vision and prophecy, And to anoint the Most Holy.</i>&nbsp;</b></blockquote>
<br />
From the time that the temple is rebuilt, to the coming of the Messiah is 69 weeks of years.<br />
<blockquote class="tr_bq">
<i>25 "Know therefore and understand,&nbsp;<b>That from the going forth of the command To restore and build Jerusalem Until Messiah the Prince, There shall be seven weeks and sixty-two weeks</b>; The street shall be built again, and the wall, Even in troublesome times.&nbsp;</i>&nbsp;</blockquote>
The Messiah will come at the end of 69 weeks of years, but will be cut off. But he will not be cut off for himself. <br />
<blockquote class="tr_bq">
<i>26 "And after the sixty-two weeks Messiah shall be cut off, but not for Himself;</i>&nbsp;</blockquote>
The people of the prince who is to come, shall destroy the city and sanctuary. This was completed by Rome in 90 A.D. So we know the prince who is to come will be related to the Roman Empire in some way.<br />
<br />
<blockquote class="tr_bq">
<i>And the people of the prince who is to come Shall destroy the city and the sanctuary. The end of it shall be with a flood, And till the end of the war desolations are determined.</i>&nbsp;</blockquote>
<br />
Desolations will come until the end of war, and he (the prince to come) will confirm a covenant with the many for one week (of years). In the middle of that week, he will break his covenant, and defile the holy city.<br />
<br />
<blockquote class="tr_bq">
<i>27 Then he shall confirm a covenant with many for one week; But in the middle of the week He shall bring an end to sacrifice and offering. And on the wing of abominations shall be one who makes desolate, Even until the consummation, which is determined, Is poured out on the desolate."&nbsp;</i></blockquote>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
Thanks for studying with me.<br />
<br />
By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">DarrellWolfe</a><br />
<br />
<a href="http://discerningthetime.blogspot.com/" target="_blank">DiscerningTheTime</a><br />
<br />
<a href="http://discerningthetime.blogspot.com/" target="_blank">http://discerningthetime.blogspot.com</a><br />
<div>
<br /></div>
