---
title: 'The Seven (7) Church Ages and Archetypes'
date: '2016-05-30T16:38:00.0040000+00:00'
draft: true
blogger_blog: 'Discerning The Time'
blogger_status: 'DRAFT'
blogger_post_id: '6487064798489490827'
blogger_filename: '/2016/05/the-seven-7-church-ages-and-archetypes.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Discerning The Time/feed.atom'
categories:
  - 'Bible Background'
  - 'The Church'
---

<h4>
Overview: The Seven (7) Church Ages and Archetypes</h4>
<div>
There are several common methods of understanding these seven churches. As with many biblical principals, I feel that the right answer is not one or the other, but all of them.</div>
<div>
<ul>
<li><b>7 Actual Churches</b></li>
<ul>
<li>We know that these were seven actual churches. No decent historian would deny that. You can visit the cities these churches resided in, and read some of their histories outside the bible.</li>
</ul>
<li><b>7 Types of Churches (Archetypes)(Mirco Level)</b></li>
<ul>
<li>They also represent 7 types of churches, or spiritual conditions that a church may find itself in. Each has it's own message of warning or restoration or promise.</li>
<li><br /></li>
</ul>
<li><b>7 Church Ages (Macro Level)</b></li>
<ul>
<li>In addition to the the first two, they also represent the seven church ages. The Church globally took on it's own personality and followed through this patter over the last 2,000 years. We are now living in the 7th, &nbsp;Laodicean Age.&nbsp;</li>
</ul>
<li><b>Note</b>: This is not to say that any one particular body could not be better represented by one of the other Archetypes today.&nbsp;</li>
<ul>
<li>The Archetypes look at the Micro (local) level; while the Ages look at the Marco (global) level. Even within certain nations, there will be differences.</li>
<li>At the smallest, most local level, any particular church could be best represented by one of these. Even within a town, two churches could be represented by two cities.</li>
<li>But the overall/global influence of The Church can still be seen for the age you study.</li>
</ul>
</ul>
<div>
<br /></div>
</div>
<h4>
History and Archaeology:</h4>
<div>
Wiki does a great job breaking down history and archaeology for the&nbsp;<a href="https://en.wikipedia.org/wiki/Seven_churches_of_Asia">Seven Churches of Asia (here for wiki)</a>.&nbsp;</div>
<div>
<br />The seven churches are located in:<br /><ul>
<li><a href="https://en.wikipedia.org/wiki/Ephesus">Ephesus</a>&nbsp;(<a href="https://en.wikipedia.org/wiki/Metropolis_of_Ephesus">Metropolis of Ephesus</a>)</li>
<li><a href="https://en.wikipedia.org/wiki/Smyrna">Smyrna</a>&nbsp;(<a href="https://en.wikipedia.org/wiki/Metropolis_of_Smyrna">Metropolis of Smyrna</a>)</li>
<li><a href="https://en.wikipedia.org/wiki/Pergamum">Pergamum</a>&nbsp;(<a href="https://en.wikipedia.org/w/index.php?title=Metropolis_of_Pergamum&amp;action=edit&amp;redlink=1">Metropolis of Pergamum</a>)</li>
<li><a href="https://en.wikipedia.org/wiki/Thyatira">Thyatira</a></li>
<li><a href="https://en.wikipedia.org/wiki/Sardis">Sardis</a>&nbsp;(<a href="https://en.wikipedia.org/wiki/See_of_Sardis">See of Sardis</a>)</li>
<li><a href="https://en.wikipedia.org/wiki/Ala%C5%9Fehir">Philadelphia</a>&nbsp;(<a href="https://en.wikipedia.org/wiki/Metropolis_of_Philadelphia">Metropolis of Philadelphia</a>)</li>
<li>and&nbsp;<a href="https://en.wikipedia.org/wiki/Laodicea_on_the_Lycus">Laodicea</a>, near&nbsp;<a href="https://en.wikipedia.org/wiki/Denizli">Denizli</a>&nbsp;(see&nbsp;<a href="https://en.wikipedia.org/wiki/Laodicean_Church">Laodicean Church</a>)</li>
</ul>
</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<h4>
Verse by Verse Breakdown:</h4>
<br />Revelation 2<div>
<br /></div>
<div>
1st Church | Ephesus (Rev 2)</div>
<div>
<br /><div>
1 "To the angel of the church of Ephesus write,'These things says He who holds the seven stars in His right hand, who walks in the midst of the seven golden lampstands: 2 I know your works, your labor, your patience, and that you cannot bear those who are evil. And you have tested those who say they are apostles and are not, and have found them liars; 3 and you have persevered and have patience, and have labored for My name's sake and have not become weary. 4 Nevertheless I have this against you, that you have left your first love. 5 Remember therefore from where you have fallen; repent and do the first works, or else I will come to you quickly and remove your lampstand from its place--unless you repent. 6 But this you have, that you hate the deeds of the Nicolaitans, which I also hate. 7 He who has an ear, let him hear what the Spirit says to the churches. To him who overcomes I will give to eat from the tree of life, which is in the midst of the Paradise of God." '&nbsp;</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
2nd Church | Smyrna&nbsp;(Rev 2)</div>
<div>
<br /></div>
<div>
8 "And to the angel of the church in Smyrna write,'These things says the First and the Last, who was dead, and came to life: 9 I know your works, tribulation, and poverty (but you are rich); and I know the blasphemy of those who say they are Jews and are not, but are a synagogue of Satan. 10 Do not fear any of those things which you are about to suffer. Indeed, the devil is about to throw some of you into prison, that you may be tested, and you will have tribulation ten days. Be faithful until death, and I will give you the crown of life. 11 He who has an ear, let him hear what the Spirit says to the churches. He who overcomes shall not be hurt by the second death." '&nbsp;</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<div>
3rd Church | Pergamos&nbsp;(Rev 2)</div>
</div>
<div>
<br /></div>
<div>
12 "And to the angel of the church in Pergamos write,'These things says He who has the sharp two-edged sword: 13 I know your works, and where you dwell, where Satan's throne is. And you hold fast to My name, and did not deny My faith even in the days in which Antipas was My faithful martyr, who was killed among you, where Satan dwells. 14 But I have a few things against you, because you have there those who hold the doctrine of Balaam, who taught Balak to put a stumbling block before the children of Israel, to eat things sacrificed to idols, and to commit sexual immorality. 15 Thus you also have those who hold the doctrine of the Nicolaitans, which thing I hate. 16 Repent, or else I will come to you quickly and will fight against them with the sword of My mouth. 17 He who has an ear, let him hear what the Spirit says to the churches. To him who overcomes I will give some of the hidden manna to eat. And I will give him a white stone, and on the stone a new name written which no one knows except him who receives it." '&nbsp;</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<div>
4th Church | Thyatira&nbsp;(Rev 2)</div>
</div>
<div>
<br /></div>
<div>
18 "And to the angel of the church in Thyatira write,'These things says the Son of God, who has eyes like a flame of fire, and His feet like fine brass: 19 I know your works, love, service, faith, and your patience; and as for your works, the last are more than the first. 20 Nevertheless I have a few things against you, because you allow that woman Jezebel, who calls herself a prophetess, to teach and seduce My servants to commit sexual immorality and eat things sacrificed to idols. 21 And I gave her time to repent of her sexual immorality, and she did not repent. 22 Indeed I will cast her into a sickbed, and those who commit adultery with her into great tribulation, unless they repent of their deeds. 23 I will kill her children with death, and all the churches shall know that I am He who searches the minds and hearts. And I will give to each one of you according to your works. 24 Now to you I say, and to the rest in Thyatira, as many as do not have this doctrine, who have not known the depths of Satan, as they say, I will put on you no other burden. 25 But hold fast what you have till I come. 26 And he who overcomes, and keeps My works until the end, to him I will give power over the nations-- 27 'He shall rule them with a rod of iron; They shall be dashed to pieces like the potter's vessels'-- as I also have received from My Father; 28 and I will give him the morning star. 29 He who has an ear, let him hear what the Spirit says to the churches." '</div>
<div>
<br /></div>
<div>
Revelation 3</div>
<div>
<br /></div>
<div>
5th Church | Sardis (Rev 3)</div>
<div>
<br /></div>
<div>
1 "And to the angel of the church in Sardis write,'These things says He who has the seven Spirits of God and the seven stars: "I know your works, that you have a name that you are alive, but you are dead. 2 Be watchful, and strengthen the things which remain, that are ready to die, for I have not found your works perfect before God. 3 Remember therefore how you have received and heard; hold fast and repent. Therefore if you will not watch, I will come upon you as a thief, and you will not know what hour I will come upon you. 4 You have a few names even in Sardis who have not defiled their garments; and they shall walk with Me in white, for they are worthy. 5 He who overcomes shall be clothed in white garments, and I will not blot out his name from the Book of Life; but I will confess his name before My Father and before His angels. 6 He who has an ear, let him hear what the Spirit says to the churches." '&nbsp;</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<div>
6th Church | Philadelphia&nbsp;(Rev 3)</div>
</div>
<div>
<br /></div>
<div>
7 "And to the angel of the church in Philadelphia write,'These things says He who is holy, He who is true, "He who has the key of David, He who opens and no one shuts, and shuts and no one opens": 8 I know your works. See, I have set before you an open door, and no one can shut it; for you have a little strength, have kept My word, and have not denied My name. 9 Indeed I will make those of the synagogue of Satan, who say they are Jews and are not, but lie--indeed I will make them come and worship before your feet, and to know that I have loved you. 10 Because you have kept My command to persevere, I also will keep you from the hour of trial which shall come upon the whole world, to test those who dwell on the earth. 11 Behold, I am coming quickly! Hold fast what you have, that no one may take your crown. 12 He who overcomes, I will make him a pillar in the temple of My God, and he shall go out no more. And I will write on him the name of My God and the name of the city of My God, the New Jerusalem, which comes down out of heaven from My God. And I will write on him My new name. 13 He who has an ear, let him hear what the Spirit says to the churches." '&nbsp;</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
7th Church | &nbsp;Laodicea (Rev 3)</div>
<div>
<br /></div>
<div>
14 "And to the angel of the church of the Laodiceans write,'These things says the Amen, the Faithful and True Witness, the Beginning of the creation of God: 15 I know your works, that you are neither cold nor hot. I could wish you were cold or hot. 16 So then, because you are lukewarm, and neither cold nor hot, I will vomit you out of My mouth. 17 Because you say, 'I am rich, have become wealthy, and have need of nothing'--and do not know that you are wretched, miserable, poor, blind, and naked-- 18 I counsel you to buy from Me gold refined in the fire, that you may be rich; and white garments, that you may be clothed, that the shame of your nakedness may not be revealed; and anoint your eyes with eye salve, that you may see. 19 As many as I love, I rebuke and chasten. Therefore be zealous and repent. 20 Behold, I stand at the door and knock. If anyone hears My voice and opens the door, I will come in to him and dine with him, and he with Me. 21 To him who overcomes I will grant to sit with Me on My throne, as I also overcame and sat down with My Father on His throne. 22 He who has an ear, let him hear what the Spirit says to the churches." ' "</div>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /></div>
