---
title: 'About You'
date: '2012-05-23T15:50:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Kaylee Debra Wolfe - Journal'
blogger_status: 'LIVE'
blogger_page_id: '2298312823946691619'
blogger_filename: '/p/about-you.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Kaylee Debra Wolfe - Journal/feed.atom'
---

<b>Kaylee Debra Wolfe</b><br />
<b>Born: 09/2003</b><br />
<br />
<br />
<ul>
<li><b style="background-color: white; font-family: Verdana; font-size: 11px;">Royal Victor - Prophetess - Faith in Adversity</b></li>
<ul>
<li><b style="background-color: white; font-family: Verdana; font-size: 11px;">Kaylee</b><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;</span><span style="background-color: white; font-family: Verdana; font-size: smaller;">\<a href="http://www.thinkbabynames.com/beginning/0/Ka" style="color: blue;">ka</a>(y)-<a href="http://www.thinkbabynames.com/ending/0/lee" style="color: blue;">lee</a>\</span><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;as a girl's name is pronounced&nbsp;</span><i style="background-color: white; font-family: Verdana; font-size: 11px;">KAY-lee</i><span style="background-color: white; font-family: Verdana; font-size: 11px;">. It is of&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/gaelic" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Gaelic</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;origin, and the meaning of Kaylee is "</span><a href="http://www.thinkbabynames.com/search/0/slender" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">slender</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">". From Caollaidhe. Variant of&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Kayla" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Kayla</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;with the&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/popular" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">popular</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;-ley ending, much&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/favored" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">favored</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;in spelling variants. May also be considered a&nbsp;</span><a href="http://www.thinkbabynames.com/search/0/combination" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">combination</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;of&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Kay" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Kay</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;with&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Lee" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Lee</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">. See also&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Cayla" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Cayla</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;and&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Kaylin" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Kaylin</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">.</span></li>
<ul>
<li><span style="background-color: white; font-family: Verdana; font-size: 11px;"><b>Kayla</b></span>&nbsp;<span style="font-size: smaller;">\<a href="http://www.thinkbabynames.com/beginning/0/Ka" style="color: blue;">ka</a>(y)-<a href="http://www.thinkbabynames.com/ending/0/la" style="color: blue;">la</a>\</span>&nbsp;as a girl's name is pronounced&nbsp;<i>KAY-la</i>. It is of&nbsp;<a href="http://www.thinkbabynames.com/search/0/irish" style="color: blue;">Irish</a>&nbsp;and&nbsp;<a href="http://www.thinkbabynames.com/search/0/gaelic" style="color: blue;">Gaelic</a>&nbsp;origin, and the meaning of Kayla is "<a href="http://www.thinkbabynames.com/search/0/slim" style="color: blue;">slim</a>&nbsp;and&nbsp;<a href="http://www.thinkbabynames.com/search/0/fair" style="color: blue;">fair</a>". From&nbsp;<a href="http://www.thinkbabynames.com/meaning/0/Caoilainn" style="color: blue;"><b>Caoilainn</b></a>. Also used as a&nbsp;<a href="http://www.thinkbabynames.com/search/0/modern" style="color: blue;">modern</a>&nbsp;variant of&nbsp;<a href="http://www.thinkbabynames.com/meaning/0/Kayley" style="color: blue;">Kayley</a>and&nbsp;<a href="http://www.thinkbabynames.com/meaning/0/Katherine" style="color: blue;"><b>Katherine</b></a>, or as a&nbsp;<a href="http://www.thinkbabynames.com/search/0/diminutive" style="color: blue;">diminutive</a>&nbsp;of&nbsp;<a href="http://www.thinkbabynames.com/meaning/0/Michaela" style="color: blue;"><b>Michaela</b></a>. Also possibly from the&nbsp;<a href="http://www.thinkbabynames.com/search/0/yiddish" style="color: blue;">Yiddish</a>&nbsp;name&nbsp;<a href="http://www.thinkbabynames.com/meaning/0/Kelila" style="color: blue;"><b>Kelila</b></a>, meaning "<a href="http://www.thinkbabynames.com/search/0/crown" style="color: blue;">crown</a>&nbsp;of&nbsp;<a href="http://www.thinkbabynames.com/search/0/laurel" style="color: blue;">laurel</a>". Initial&nbsp;<a href="http://www.thinkbabynames.com/search/0/popularity" style="color: blue;">popularity</a>&nbsp;of the name is due to the&nbsp;<a href="http://www.thinkbabynames.com/search/0/character" style="color: blue;">character</a>&nbsp;named Kayla on the daytime TV drama "Days of Our&nbsp;<a href="http://www.thinkbabynames.com/search/0/live" style="color: blue;">Lives</a>". See also&nbsp;<a href="http://www.thinkbabynames.com/meaning/0/Kaylee" style="color: blue;"><b>Kaylee</b></a>.</li>
<li><span style="background-color: white; font-family: Verdana; font-size: 11px;">Slender/Slim and Fair</span></li>
<ul>
<li><span style="background-color: white; font-family: Verdana; font-size: 11px;">Royal - Honest</span></li>
</ul>
<li><span style="font-family: Verdana;"><span style="font-size: 11px;">Crown of Laurel (Laurel Wreath)</span></span></li>
<ul>
<li><span style="font-family: Verdana;"><span style="font-size: 11px;">Royal - Victor</span></span></li>
<li><a href="http://en.wikipedia.org/wiki/Laurel_wreath" style="font-family: Verdana; font-size: 11px;">http://en.wikipedia.org/wiki/Laurel_wreath</a></li>
</ul>
</ul>
<li><b style="background-color: white; font-family: Verdana; font-size: 11px;">Debra</b><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;</span><span style="background-color: white; font-family: Verdana; font-size: smaller;">\d(e)-</span><a href="http://www.thinkbabynames.com/meaning/0/Debra" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">bra</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">,</span><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Debra" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">deb</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">-</span><a href="http://www.thinkbabynames.com/meaning/0/Debra" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">ra</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">\ as a girl's name is a variant of</span><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/0/Deborah" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Deborah</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;</span><span style="background-color: white; font-family: Verdana; font-size: 11px;">(Hebrew), and the meaning of Debra is "bee".</span></li>
</ul>
</ul>
<ul><ul><ul>
<li><span style="background-color: white; font-family: Verdana; font-size: 11px;"><b>Deborah</b></span>&nbsp;<span style="font-size: smaller;">\d(e)-bo-<a href="http://www.thinkbabynames.com/ending/0/rah" style="color: blue;">rah</a>\</span>&nbsp;as a girl's name is pronounced&nbsp;<i>DEB-er-ah</i>. It is of&nbsp;<a href="http://www.thinkbabynames.com/search/0/hebrew" style="color: blue;">Hebrew</a>&nbsp;origin, and the meaning of Deborah is "<a href="http://www.thinkbabynames.com/search/0/bee" style="color: blue;">bee</a>".&nbsp;<a href="http://www.thinkbabynames.com/search/0/biblical" style="color: blue;">Biblical</a>: a&nbsp;<a href="http://www.thinkbabynames.com/search/0/prophetess" style="color: blue;">prophetess</a>&nbsp;who summoned Barak to&nbsp;<a href="http://www.thinkbabynames.com/search/0/battle" style="color: blue;">battle</a>&nbsp;against an invading&nbsp;<a href="http://www.thinkbabynames.com/search/0/army" style="color: blue;">army</a>. The&nbsp;<a href="http://www.thinkbabynames.com/search/0/victory" style="color: blue;">victory</a>&nbsp;<a href="http://www.thinkbabynames.com/search/0/song" style="color: blue;">song</a>&nbsp;she&nbsp;<a href="http://www.thinkbabynames.com/search/0/wrote" style="color: blue;">wrote</a>&nbsp;after the&nbsp;<a href="http://www.thinkbabynames.com/search/0/battle" style="color: blue;">battle</a>&nbsp;is part of the&nbsp;<a href="http://www.thinkbabynames.com/search/0/book" style="color: blue;">Book</a>&nbsp;of Judges.<a href="http://www.thinkbabynames.com/search/0/actress" style="color: blue;">Actresses</a>&nbsp;Deborah Kerr,&nbsp;<a href="http://www.thinkbabynames.com/meaning/0/Debbie" style="color: blue;">Debbie</a>&nbsp;Reynolds,&nbsp;<a href="http://www.thinkbabynames.com/meaning/0/Debra" style="color: blue;">Debra</a>&nbsp;Winger,&nbsp;<a href="http://www.thinkbabynames.com/meaning/0/Debra" style="color: blue;">Debra</a>&nbsp;Messing;&nbsp;<a href="http://www.thinkbabynames.com/search/0/olympic" style="color: blue;">Olympic</a>&nbsp;<a href="http://www.thinkbabynames.com/search/0/figure" style="color: blue;">figure</a>&nbsp;<a href="http://www.thinkbabynames.com/search/0/skater" style="color: blue;">skater</a><a href="http://www.thinkbabynames.com/meaning/0/Debi" style="color: blue;">Debi</a>&nbsp;Thomas; TV&nbsp;<a href="http://www.thinkbabynames.com/search/0/journalist" style="color: blue;">journalist</a>&nbsp;Deborah Norville.</li>
</ul>
</ul>
</ul>
<br />
<br />
<ul type="disc"><ul type="circle">
<li class="MsoNormal"><b><span style="font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; font-size: 8.5pt; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;;">Wolfe</span></b></li>
<ul>
<li class="MsoNormal"><span style="font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; font-size: 8.5pt; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;;">Motto: Fides in
      Adversis - Faith in Adversity</span></li>
<li class="MsoNormal"><span style="font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; font-size: 8.5pt; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;;"><a href="http://www.houseofnames.com/wolfe-family-crest"><span style="color: blue;">http://www.houseofnames.com/wolfe-family-crest</span></a></span></li>
</ul>
</ul>
</ul>
<br />
<br />
<b>Favorite Things:</b><br />
<br />
<ul>
<li>Pink</li>
<li>Hello Kitty</li>
<li>Dance</li>
</ul>
<div style="text-align: center;">
<b><u>Family</u>:</b></div>
<div style="text-align: center;">
<b><br /></b></div>
<div style="text-align: center;">
<b>Father:&nbsp;</b></div>
<br />
<ul>
<li>Devin Norris Wolfe - Born 05/12/1983 - Died ??20??</li>
<ul>
<li>Graduated from&nbsp;Juvenile&nbsp;Hall, Indio CA</li>
</ul>
</ul>
<div>
<br /></div>
<ul>
<li>Mother Dawn ? Wolfe &nbsp;- Born ?? - Died - ??</li>
<ul>
<li>Graduated ??</li>
</ul>
</ul>
<br />
<br />
<div style="text-align: center;">
<b>Grandparents</b>:</div>
<br />
By Devin:<br />
<br />
<ul>
<li>Debra Yvonne Tweedy (Previous Last Names: Wolfe/Ford) - Born 07/10/1956</li>
<ul>
<li><a href="https://www.facebook.com/debbie.tweedy/timeline/story?ut=32&amp;wstart=-2649600&amp;wend=1170316799&amp;hash=1809052794663&amp;pagefilter=3" style="background-color: white; color: #3b5998; cursor: pointer; font-family: 'lucida grande', tahoma, verdana, arial, sans-serif; font-size: 11px; line-height: 15px; text-align: left; text-decoration: none;">Graduated from CSUSB</a>&nbsp;2007</li>
<li><span style="background-color: white; color: #3b5998; font-family: 'lucida grande', tahoma, verdana, arial, sans-serif; font-size: 11px; line-height: 15px; text-align: left;">Graduated from Arcadia High School</span>&nbsp;1974</li>
<li>Hometown Arcadia, CA</li>
</ul>
</ul>
<br />
<br />
<ul>
<li>Michael Craig Wolfe - Born 05/14/1954</li>
<ul>
<li>Hometown West Covina, CA</li>
<li>Graduated From: Azusa University, Claremont School of Heresy (Theology), Cal State Fullerton</li>
</ul>
</ul>
<div>
By Dawn:</div>
<br />
<br />
<ul>
<li>Billie Intong ( )- Born 12/01/1953</li>
<ul>
<li><a href="https://www.facebook.com/billie.intong/timeline/story?ut=32&amp;wstart=-2649600&amp;wend=34243199&amp;hash=199671386726024&amp;pagefilter=3" style="background-color: white; color: #3b5998; cursor: pointer; font-family: 'lucida grande', tahoma, verdana, arial, sans-serif; font-size: 11px; line-height: 15px; text-align: left;">Graduated from Westmoor High</a>&nbsp;1971</li>
<li>Hometown Daly City, CA</li>
<li><a href="https://www.facebook.com/billie.intong/info">https://www.facebook.com/billie.intong/info</a></li>
</ul>
</ul>
<div>
<br /></div>
<ul>
<li>Alex Intong - Born 02/01/1944</li>
<ul>
<li><span style="background-color: white; color: #3b5998; font-family: 'lucida grande', tahoma, verdana, arial, sans-serif; font-size: 11px; line-height: 15px; text-align: left;">Graduated from Palm Springs High</span>&nbsp;1963</li>
<li>Hometown Indio, CA</li>
<li><a href="https://www.facebook.com/alex.intong/info">https://www.facebook.com/alex.intong/info</a></li>
</ul>
</ul>