---
title: 'Knowing your Guitar'
date: '2013-04-22T00:39:00.0010000+00:00'
draft: true
blogger_blog: 'Towdah: tō·dä'''
blogger_status: 'DRAFT'
blogger_post_id: '3820932127710703807'
blogger_filename: '/2013/04/knowing-your-guitar.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Towdah_ tō·dä_/feed.atom'
---

<h4 style="text-align: center;">
Back To Basics</h4>
So I'm going back to basics. I started playing guitar at 13. I tried when I was 10, lost&nbsp;interest&nbsp; and really started at 13. Parents, here's an interesting challenge. At 13 I asked my mom to buy me a guitar. She had one already of her own. She said that when I got better than her she would buy me my own. So somewhere around 13.5 I had my own guitar. I accomplished in 6 months what I could not in 3 years. Of course, that was partially due to being older and matured by 3 years, but incentive had a lot to do with it too.<br />
<br />
I took a handful of lessons with a very talented man I wish I'd paid more attention to. I had the ultimate resource as a family friend and not until now in my 30's do I look back and realize... MAN, I should have picked that guys brain from 13 to 25 (when I left that valley). Who knows, had I done that my life probably would have taken a WILDLY different path to get me here. Where is here?<br />
<br />
Well, I'm 32.5 now, I used to call myself moderate. But really I'm just an advanced beginner. I'm the guy you're talking about when you say "He knows enough to be dangerous..." in other words, I don't really know much, but what I know I know really well. As it turns out, I really don't know nearly as much as I thought, and the rest is a bit fuzzy. So after repeated attempts by God to get my attention I've slowly turned my attention to music. Since guitar is where I started, guitar is where I'll start over again.<br />
<br />
I signed up for a membership with "<a href="http://dangerousguitar.com/" target="_blank">http://dangerousguitar.com</a>" which was a really great idea! I'm able to go back over those basics I missed without boring some other player with it. When I say I started over, I mean I REALLY started over. They say that <a href="http://www.vincelombardi.com/" target="_blank">Vince Lombardi</a> started his coaching career by talking to a group of professional players. They'd been loosing for some time and he was taking over. He said: "<a href="http://www.insight.org/library/articles/church/back-to-the-basics.html" target="_blank">Gentlemen, this is a football.</a>" With that he went back and reviewed the basics. So that's what I'm doing with the guitar.<br />
<br />
<h4 style="text-align: center;">
Guitar Basics - Knowing Your Guitar</h4>
<br />
<h4 style="border: 0px; color: #222222; font-family: Arial, Helvetica, sans-serif; font-size: 12px; line-height: 15px; margin: 0px 0px 5px; outline: 0px; padding: 0px; vertical-align: baseline;">
<ul>
<li><a href="http://dangerousguitar.com/lessons/view/328" style="border: 0px; color: #333333; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;">#1-Basics-Parts of the Acoustic Guitar</a></li>
<li><a href="http://dangerousguitar.com/lessons/view/242" style="border: 0px; color: #333333; margin: 0px; outline: 0px; padding: 0px; vertical-align: baseline;">#2-Basics-Parts of the Electric Guitar</a></li>
</ul>
</h4>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />