---
title: 'Passionate Purpose of Music'
date: '2013-03-24T21:15:00.0020000+00:00'
draft: true
blogger_blog: 'Towdah: tō·dä'''
blogger_status: 'LIVE'
blogger_post_id: '5324842186825522165'
blogger_filename: '/2013/03/passionate-purpose-of-music.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Towdah_ tō·dä_/feed.atom'
categories:
  - 'Praise/Worship'
  - 'Insight'
---

<br />
<h1 style="color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; line-height: 19px;">
Colossians 3:14-17 (New King James Version)</h1>
<div style="color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">
14&nbsp;But<strong>&nbsp;above all</strong>&nbsp;these things&nbsp;<strong>put on love</strong>, which is the bond of perfection.&nbsp;15&nbsp;And&nbsp;<strong>let the peace of God rule</strong>&nbsp;in your hearts, to which also you were called in one body; and&nbsp;<strong>be thankful</strong>.&nbsp;16&nbsp;<strong>Let the word of Christ dwell in you richly</strong>&nbsp;in all&nbsp;<strong>wisdom, teaching and admonishing</strong>&nbsp;one another in<strong>&nbsp;psalms and hymns and spiritual songs</strong>,&nbsp;<strong>singing with grace in your hearts</strong>&nbsp;to the Lord.&nbsp;17&nbsp;And whatever you do in word or deed,&nbsp;<strong>do all in the name of the Lord Jesus, giving thanks</strong>&nbsp;to God the Father through Him.</div>
<div style="color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">
ABOVE ALL:</div>
<ul style="color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">
<li>Put On Love</li>
<li>Let Peace Rule</li>
<li>Be Thankful</li>
<li>Let THE Word dwell richly</li>
</ul>
<div style="color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">
How does the word&nbsp;dwell&nbsp;richly?</div>
<ul style="color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">
<li>Wisdom</li>
<li>Teaching</li>
<li>Admonishing</li>
</ul>
<div style="color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">
The best way, highest order, for these to be done:</div>
<ul style="color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">
<li>Psalms</li>
<li>Hymns</li>
<li>Spiritual Songs</li>
<li>Singing with Grace in your Hearts</li>
<li>Giving Thanks!</li>
</ul>
