---
title: 'Towdah, among SEVEN words for praise.'
date: '2013-09-29T23:56:00.0010000+00:00'
draft: true
blogger_blog: 'Towdah: tō·dä'''
blogger_status: 'LIVE'
blogger_post_id: '7040665814831220699'
blogger_filename: '/2013/09/towdah-among-seven-words-for-praise.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Towdah_ tō·dä_/feed.atom'
categories:
  - 'Insight'
---

Which one is most appropriate for an Audio and Music site? When I picked this site name I just looked up "Praise" "Worship" in Hebrew and Greek and this is the name that popped up. But which word is MOST appropriate?<br />
<br />
<ol>
<li>Towdah: An extension of the hand in adoration, avowal, or acceptance, to thank God in advance. Seems applicable. As an Audio person I am an extension of the worship team, pastor, etc. It is all funneled through me to the people. It's very hard for the back row to hear without the things I do. Likewise I could mess up the things going on if I am not watching, being diligent, and keeping my own art/craft to it's highest standard. It might be better for there to be no audio than to have the wrong person behind the board. In a very real sense, I am an invisible extension of the hand from God through the platform to the people and from them, because they respond, back to God. </li>
<li>Zamar: pluck the strings, sing, praise, music, musical praise. This is a function of what I do, a great deal of my time and energy is devoted to music, but it's not ALL I do...</li>
<li>All the other words seems to be various expressions of praise, but Towdah still seems to apply the best... who knew, I was spirit led when I picked it! </li>
</ol>
<br />
Someone else did all the work, why duplicate it. Here are words for "Praise" in Hebrew. Towdah being one of them. <br />
<br />
<a href="http://buddysheets.tripod.com/hebrewwordsforpraise.htm" target="_blank">http://buddysheets.tripod.com/hebrewwordsforpraise.htm </a><br />
<hr align="CENTER" size="2" width="100%" />
   
  
   <b><span style="color: red;"><span style="font-size: medium;">1. <u>Halal</u></span></span></b><br />

  
   <b>Halal is a primary Hebrew root word for praise. Our word 
   "hallelujah" comes from this base word. It means "to 
   be clear, to shine, to boast, show, to rave, celebrate, to be 
   clamorously foolish."</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+113:1-3">Ps
    113:1-3</a></u></b><br />
   <b>Praise (halal) ye the Lord, praise (halal) o ye servants of the 
   Lord, praise (halal) the name of the Lord.</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+150:1">Ps
    150:1</a></u></b><br />
   <b>Praise (halal) the Lord! Praise (halal) God in his sanctuary; 
   Praise (halal) him in his mighty expanse.</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+149:3">Ps
    149:3</a></u></b><br />
   <b>Let them praise (halal) his name in the dance: let them sing 
   praises with the timbrel and harp.</b><br />

  
   <b>(Other references: <a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=1Chr+2">1Chr
    2</a>)</b><br />

  
   <b><span style="color: red;"><span style="font-size: medium;">2. <u>Yadah</u></span></span></b><br />

  
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=2Chr+8:14">2Chr
    8:14</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Ezra+3:10">Ezra
    3:10</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+22:22">Ps
    22:22</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+63:5">Ps
    63:5</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+69:30">Ps
    69:30</a></b><br />

  
   <b>Yadah is a verb with a root meaning, "the extended hand, to 
   throw out the hand, therefore to worship with extended hand." 
   According to the Lexicon, the opposite meaning is "to bemoan, 
   the wringing of the hands."</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=2Chr+20:21">2Chr
    20:21</a></u></b><br />
   <b>Give thanks (yadah) to the Lord, for his lovingkindness is everlasting.</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+63:1">Ps
    63:1</a></u></b><br />
   <b>So I will bless thee as long as I live; I will (yadah) lift up my 
   hands in thy name.</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+107:15">Ps
    107:15</a></u></b><br />
   <b>Oh that men would praise (yadah) the Lord for his goodness, and 
   for his wonderful works to the children of men.</b><br />

  
   <b>Other references:</b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Gen+49:8">Gen
    49:8</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=2Chr+7:6">2Chr
    7:6</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=2Chr+20:21">2Chr
    20:21</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Isa+12:4">Isa
    12:4</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Jer+33:11">Jer
    33:11</a></b><br />

  
   <b><span style="color: red;"><span style="font-size: medium;">3. <u>Towdah</u></span></span></b><br />

  
   <b>Towdah comes from the same principle root word as yadah, but is 
   used more specifically. Towdah literally means, "an extension of 
   the hand in adoration, avowal, or acceptance." By way of 
   application, it is appratent in the Psalms and elsewhere that it is 
   used for thanking God for "things not yet received" as well 
   as things already at hand.</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+50:14">Ps
    50:14</a></u></b><br />
   <b>Offer unto God praise (towdah) and pay thy vows unto the Most High.</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+50:23">Ps
    50:23</a></u></b><br />
   <b>Whoso offereth praise (towdah) glorifieth me: and to him that 
   ordereth his conversation aright will I shew the salvation of God.</b><br />

  
   <b>Other references:</b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=2Chr+29:31">2Chr
    29:31</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Jer+33:11">Jer
    33:11</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+42:4">Ps
    42:4</a></b><br />

  
   <b><span style="color: red;"><span style="font-size: medium;">4. <u>Shabach</u></span></span></b><br />
   <b>Shabach means, "to shout, to address in a loud tone, to 
   command, to triumph."</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+47:1">Ps
    47:1</a></u></b><br />
   <b>O clap your hands, all peoples; shout (shabach) to God with the 
   voice of joy (or triumph).</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+145:4">Ps
    145:4</a></u></b><br />
   <b>One generation shall praise (shabach) thy works to another and 
   declare thy mighty acts.</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Isa+12:6">Isa
    12:6</a></u></b><br />
   <b>Cry aloud and shout (shabach) for joy, O inhabitant of Zion, For 
   great in your midst is the Holy One of Israel.</b><br />

  
   <b>Other references:</b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+63:1-4">Ps
    63:1-4</a></b><br />
   <b><span style="font-size: small;">Ps.117:1</span></b><br />
   <b><span style="font-size: small;"><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+35:27">Ps
    35:27</a></span></b><br />
   <b><span style="font-size: small;"><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+106:47">Ps
    106:47</a></span></b><br />

  
   <b><span style="color: red;"><span style="font-size: medium;">5. <u>Barak</u></span></span></b><br />

  
   <b>Barak means "to kneel down, to bless God as an act of adoration."</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+95:6">Ps
    95:6</a></u></b><br />
   <b>O come let us worship and bow down; let us kneel (barak) before 
   the Lord our maker.</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=1Chr+29:20">1Chr
    29:20</a></u></b><br />
   <b>Then David said to all the assembly, "Now bless (barak) the 
   Lord your God." And all the assembly blessed (barak) the Lord, 
   the God of their fathers, and bowed low and did homage to the Lord 
   and to the king.</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+34:1">Ps
    34:1</a></u></b><br />
   <b>I will bless (barak) the Lord at all times; His praise shall 
   continually be in my mouth.</b><br />

  
   <b>Other references:</b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Job+1:21">Job
    1:21</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+96:2">Ps
    96:2</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+103:1-2">Ps
    103:1-2</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+18:46">Ps
    18:46</a></b><br />

  
   <b><span style="color: red;"><span style="font-size: medium;">6. <u>Zamar</u></span></span></b><br />

  
   <b>Zamar means "to pluck the strings of an instrument, to sing, 
   to praise; a musical word which is largely involved with joyful 
   expressions of music with musical instruments.</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+21:13">Ps
    21:13</a></u></b><br />
   <b>Be exalted O Lord, in Thine own strength, so will we sing and 
   praise (zamar) Thy power.</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=1Chr+16:9">1Chr
    16:9</a></u></b><br />
   <b>Sing to Him, sing praises (zamar) to Him; speak of all His wonders.</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+57:8-9">Ps
    57:8-9</a></u></b><br />
   <b>Awake my glory; awake harp and lyre, I will awaken the dawn! I 
   will give thanks to Thee, O Lord among the peoples; I will sing 
   praises (zamar) to Thee among the nations.</b><br />

  
   <b>Other references:</b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+66:2-4">Ps
    66:2-4</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Isa+12:5">Isa
    12:5</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+27:6">Ps
    27:6</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+149:3">Ps
    149:3</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+30:4">Ps
    30:4</a></b><br />

  
   <b><span style="color: red;"><span style="font-size: medium;">7. <u>Tehillah</u></span></span></b><br />

  
   <b>Tehillah is derived from the word halal and means "the 
   singing of halals, to sing or to laud; perceived to involve music, 
   especially singing; hymns of the Spirit.</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+22:3">Ps
    22:3</a></u></b><br />
   <b>Yet Thou art holy, O Thou who art enthroned upon the praises 
   (tehillah) of Israel.</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+33:1">Ps
    33:1</a></u></b><br />
   <b>Rejoice in the Lord, o ye righteous, for praise (tehillah) is 
   comely for the upright.</b><br />

  
   <b><u><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Isa+61:3">Isa
    61:3</a></u></b><br />
   <b>To grant to those who mourn in Zion, Giving them a garland instead 
   of ashes, The oil of gladness instead of mourning, The mantle of 
   praise (tehillah) instead of the spirit of fainting, So they shall be 
   called oaks of righteousness, The planting of the Lord, that He may 
   be glorified.</b><br />

  
   <b>Other references:</b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+34:1">Ps
    34:1</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=1Chr+16:35">1Chr
    16:35</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=2Chr+20:22">2Chr
    20:22</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Deut+10:21">Deut
    10:21</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Exod+15:11">Exod
    15:11</a></b><br />
   <b><a href="http://goon.stg.brown.edu/cgi-bin/pbcgi?mode=paragraph&amp;sourceform=pbeasy.shtml&amp;maxhits=25&amp;searchtype=fetch&amp;version=rsv&amp;searchstring=Pss+147:1-2">Ps
    147:1-2</a></b>