---
title: 'What is Ministry in Music'
date: '2013-03-24T21:16:00.0020000+00:00'
draft: true
blogger_blog: 'Towdah: tō·dä'''
blogger_status: 'LIVE'
blogger_post_id: '4456586390949961597'
blogger_filename: '/2013/03/what-is-ministry-in-music.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Towdah_ tō·dä_/feed.atom'
categories:
  - 'Insight'
---

<br />
<div style="color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">
I heard a Pastor once say that a certain christian entertainer was not "ministry" because he wasn't getting people saved at his concerts.&nbsp; If that were true what does it mean that the Prophets and Teachers including Paul and Barnabas were "Ministering to the Lord". How can you get the Lord saved? Ministry means to Serve. You serve the Lord by doing what he wants you to do. You may be serving the Lord smiling at someone and never saying a word if that is what He told you to do.</div>
<div style="color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">
Getting your heart, in tune with His heart, and reaching through His heart to the Heart of others in service is ministry. Just remember that despite the opinions of anyone, you stand before Him and Him alone. What is HE telling you to do? If your assignment is to work behind a counter taking orders and doing it in the Joy of The Lord... that is YOUR ministry. Do it with all the enthusiasm of an evangelist.</div>
<div style="color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">
Write the music HE is calling you to. Too often because of this religious idea we've had of what God wants we in the Christian world have tried to over Christianize everything we do. If our song, book, movie, conversation didn't involve serious prayer and someone getting right with God and crying and repentance... we felt as though it wasn't a christian book. Why can't you just write a well done piece&nbsp; of literature and let what is in you flow out of you into the page without forcing it to preach? Lord of the Rings is among the most popular books of fiction in history and although there are christian themes throughout the book because the author was deeply christian not once was there a character preaching and carrying on and repenting in dust and ashes.</div>
<div style="color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">
We must rethink our work. Christians OUGHT TO BE producing the cutting edge in everything we do. The world for hundreds of years came to US to learn how WE did some new amazing thing. Science, art, etc. We ruled. It was a christian who was killed for saying the world was round! Christians said we ought to have a government "For the people by the people" and freedom TO religion and FROM the government NOT TO government and FROM religion.</div>
<div style="color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">
In the past 100 years Christian movies and music have become decades behind the times and it's time we had a revolution. Hollywood should be knocking down our door to see our newest inventions and ideas and software and techniques, etc.</div>
<div style="color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">
Will you answer the call?</div>
<div style="color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">
DW</div>
