---
title: 'The Concern'
date: '2012-10-02T04:51:00.0010000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'LIVE'
blogger_post_id: '7270070078817819508'
blogger_filename: '/2012/10/the-concern.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
categories:
  - 'The Concern'
---

<h3>
The Concern</h3>
<br />
On the morning of <a href="http://en.wikipedia.org/wiki/September_11_attacks" target="_blank">September 11th 2001</a> the nation woke up and went about their day as normal. Little to their knowledge a group of evil men, bound by an evil force, bent on destruction, boarded several planes. These were no ordinary hijackers. In the past these types of events ended up in hostage situations and often resulted in some or all of the hostages surviving as long as the terrorists got their way. The USA has a strict policy of non-negotiation with terrorists by this point, but will do what they can to secure the hostages before taking down the men.<br />
<br />
People have been trained to sit quite and wait it out. This was, in fact, the Satanic purpose behind all of the previous situations. To train people to respond a certain way. Being trained to sit and wait was what they wanted from these unsuspecting passengers. They would become the first victims of the worlds first large scale attack on USA Continental soil. The casualties of these two large buildings could easily have numbers of 50,000 to 250,000.<br />
<br />
<a href="http://en.wikipedia.org/wiki/World_Trade_Center" target="_blank">Wiki Explains:</a><br />
<blockquote class="tr_bq">
<span style="background-color: white; font-family: sans-serif; font-size: 13px; line-height: 19.200000762939453px;">On a typical weekday 50,000 people worked in the towers</span><sup class="reference" id="cite_ref-81" style="background-color: white; font-family: sans-serif; line-height: 1em;"><a href="http://en.wikipedia.org/wiki/World_Trade_Center#cite_note-81" style="background-image: none; background-position: initial initial; background-repeat: initial initial; color: #0b0080; text-decoration: none; white-space: nowrap;">[82]</a></sup><span style="background-color: white; font-family: sans-serif; font-size: 13px; line-height: 19.200000762939453px;">&nbsp;with another 200,000 passing through as visitors.</span><sup class="reference" id="cite_ref-82" style="background-color: white; font-family: sans-serif; line-height: 1em;"><a href="http://en.wikipedia.org/wiki/World_Trade_Center#cite_note-82" style="background-image: none; background-position: initial initial; background-repeat: initial initial; color: #0b0080; text-decoration: none; white-space: nowrap;">[83]</a></sup><span style="background-color: white; font-family: sans-serif; font-size: 13px; line-height: 19.200000762939453px;">&nbsp;The complex was so large that it had its own zip code:&nbsp;</span><a href="http://en.wikipedia.org/wiki/10048_(ZIP_code)" style="background-color: white; background-image: none; color: #0b0080; font-family: sans-serif; font-size: 13px; line-height: 19.200000762939453px; text-decoration: none;" title="10048 (ZIP code)">10048</a><span style="background-color: white; font-family: sans-serif; font-size: 13px; line-height: 19.200000762939453px;">.</span><sup class="reference" id="cite_ref-83" style="background-color: white; font-family: sans-serif; line-height: 1em;"><a href="http://en.wikipedia.org/wiki/World_Trade_Center#cite_note-83" style="background-image: none; background-position: initial initial; background-repeat: initial initial; color: #0b0080; text-decoration: none; white-space: nowrap;">[84]</a></sup><span style="background-color: white; font-family: sans-serif; font-size: 13px; line-height: 19.200000762939453px;">&nbsp;</span></blockquote>
This doesn't take into account the people working at the Pentagon or the people on the planes.&nbsp;Yet, although this attack could have the potential of ending between 50,000-150,000 lives or more, it would only end up taking a total of 2,977 Civilian lives and another 19 terrorists' lives. People asked after the attack: "Where was God?" Well there are two answers to that. <br />
<br />
First of all, we AS A NATION officially began reject and removing God in 1947 with the removal of God from our schools and have done so aggressively ever since. Whether by action or inaction, we all remain guilty for allowing it to happen. You can't have it both ways. You can't kick God out and then be angry for his absence.<br />
<br />
Second, in His GREAT mercy, more people were absent or late to work that day than usual. Others heard the voice of God as they approached and ran before it happened. Others found ways to evacuate and led people to&nbsp;safety. In the end, what should have been thousands upon thousands, ended up being near only 3,000.<br />
<br />
This date began the end of an era. The United States of America would begin loosing it's place in the world. Revelations gives us a startling warning that seems to apply here:<br />
<br />
<a href="http://www.biblestudytools.com/nkjv/revelation/passage.aspx?q=revelation+2:1-10" target="_blank">Revelations 2:4</a><br />
<blockquote class="tr_bq">
<i>Nevertheless I have this against you, that you have left your first love. 5 Remember therefore from where you have fallen; repent and do the first works, or else I will come to you quickly and remove your&nbsp;lamp-stand&nbsp;from its place--unless you repent. 
</i></blockquote>
The United States is being ridiculed around the world, we are experiencing social, economic and physical/natural distress. The very foundations of this nation both naturally (through&nbsp;catastrophes&nbsp; and spiritually (through a battle with darkness) are being shaken. We MUST rise and take our place.<br />
<br />
The enemy comes for only one purpose: To Steal, To Kill, and To Destroy! (<a href="http://www.biblegateway.com/passage/?search=John+10%3A10&amp;version=NIV" target="_blank">John 10:10</a>) Jesus came that we might have LIFE and have it more abundantly. The Enemy, Satan, right now is working his way into the United States like&nbsp;poison. He can only work through people. We see his fruit in evil special&nbsp;interest&nbsp;groups like the GLBT and Planned Parenthood and ACLU. These, and groups like them, are seeking at every opportunity to pervert God's ways, to promote evil and condemn good.<br />
<br />
While the USA sends more aid to foreign countries than any other nation it is ridiculed time and again by other nations. Many of the very nations we send aid to seek our destruction and use our own money to plan the attacks.<br />
<br />
The United States is under a&nbsp;siege. But this&nbsp;siege&nbsp;will not be won in battle's, political elections, or word wars... until first we seek to win the spiritual battle. Prayer and national repentance is the first and primary key to leading this charge to take back a nation from an enemy that has lulled us to sleep.<br />
<br />
We must awake, rise up, and begin to walk in the excellence with which we have been called.<br />
<br />
<a href="http://www.biblestudytools.com/nkjv/philippians/3-8.html" target="_blank">Philippians 3:8 NKJV&nbsp;</a><br />
<blockquote class="tr_bq">
<i>Yet indeed I also count all things loss for the <b>excellence of the knowledge of Christ Jesus</b> my Lord, for whom I have suffered the loss of all things, and count them as rubbish, that I may gain Christ</i></blockquote>
What is this excellence? It is our calling to Know Him and Be Like Him, together.<br />
DW