---
title: 'US History 101 - America''s New Civil War'
date: '2012-09-18T04:59:00.0020000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'LIVE'
blogger_post_id: '5597674026717706061'
blogger_filename: '/2012/09/us-history-101-americas-new-civil-war.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
---

<br />
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="line-height: 1.4;">US History 101</strong></div>
<blockquote style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; font-style: italic; line-height: 18px; padding: 0px 3em;">
<div style="line-height: 1.4; margin-bottom: 18px;">
“Have no worry. Do not be in fear about the United States of America. Don’t be in fear over the failure of this republic. This is not the time for this nation to fail. I’m not done with it yet. And it may come as a surprise to many; this nation is not done with Me yet,” saith The LORD. Hallelujah (<a data-mce-href="http://www.kcm.org/real-help/prophecy/what-about-2012" href="http://www.kcm.org/real-help/prophecy/what-about-2012" style="color: #cd4517; line-height: 1.4;" target="_blank">Kenneth Copeland 11/10/2011</a>)</div>
</blockquote>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
In 1776 a group of men sat in conference to draft a paper that would radically change the world forever. Despite Satan's attempts to downplay or ignore this document's creation through dark organizations and liberal/socialist leaders, this document stands as a beacon of light in a dark world.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
At no time in history had such a document been drafted and stood by unto death. Many writers, philosophers, and thinkers gave their contribution to the events that led to the creation of this document. These men, leaders each from his respective colony, did not simply draft a paper to debate and ponder. This was not just some&nbsp;intellectual&nbsp;endeavour. This was a&nbsp;<a data-mce-href="http://www.wallbuilders.com/libissuesarticles.asp?id=25685" href="http://www.wallbuilders.com/libissuesarticles.asp?id=25685" style="color: #cd4517; line-height: 1.4;" target="_blank">declaration of&nbsp;independence</a>. This was a declaration of a decision that they will not put up with things the way they are.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
This was a declaration of war! This was a serious document, with sober consequences. This declaration was saying to a king and a government: "NO! We will not bow to you and your government anymore!" These colonies were under the authority of England. What would make a group of people decide to throw off their government and choose another? This is not a strange thing to ask, it's happening nearly daily in the middle east right now. It's happening with more and more frequency. In 2011-2012 we saw several nations throw off their way of life and choose another way. But the consequences of this kind of action are based on the actions that follow. Their final state could be better or worse. During the founding of the United States of America, the time had come for Righteousness to stand up to the abuses of the government that they were under and rebuke a government that was abusing it's people.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
On July 4th, 1776 the men stood up and said: "NO!". The bloated government that oppressed the people by serving it's own interests and that of the bureaucrats&nbsp;and politicians, rather than the best interests of the people, was given it's eviction notice. They clearly stated in this&nbsp;<a data-mce-href="http://www.wallbuilders.com/libissuesarticles.asp?id=25685" href="http://www.wallbuilders.com/libissuesarticles.asp?id=25685" style="color: #cd4517; line-height: 1.4;" target="_blank">declaration of&nbsp;independence</a>&nbsp;that any such declaration should not be done lightly or over small matters, then they go on to say:</div>
<blockquote style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; font-style: italic; line-height: 18px; padding: 0px 3em;">
<div style="line-height: 1.4; margin-bottom: 18px;">
"<em style="border: none; font-style: normal; line-height: 1.4;">But when a long train of abuses and usurpations, pursuing invariably the same Object evinces a design to reduce them under absolute Despotism, it is their right, it is their duty, to throw off such Government, and to provide new Guards for their future security.</em>"</div>
</blockquote>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
These men revolted against&nbsp;tyranny&nbsp;by an all powerful government, especially one which would impose it's views on the religious and social freedoms that they held dear and the basic freedoms that they saw violated. These men believed that these rights were not their own invention but rather were&nbsp;innately&nbsp;natural rights. They believed that God gave them these rights. They said this <a data-mce-href="http://www.wallbuilders.com/libissuesarticles.asp?id=25685" href="http://www.wallbuilders.com/libissuesarticles.asp?id=25685" style="color: #cd4517; line-height: 1.4;" target="_blank">"Natures God", "Their Creator", "The Supreme Judge of the World"</a>, would vindicate&nbsp;their&nbsp;actions.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="line-height: 1.4;">USA's Bible Roots</strong></div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
So where did they get this crazy idea? How did anyone come to this idea that God wants all men equal and free? Well, let's take a look at what the Word of God says about this topic.</div>
<blockquote style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; font-style: italic; line-height: 18px; padding: 0px 3em;">
<h1 style="font-size: 20px; font-weight: normal; line-height: 1.5em; margin: 0px 0px 18px;">
<a data-mce-href="http://www.biblestudytools.com/nkjv/genesis/1-28.html" href="http://www.biblestudytools.com/nkjv/genesis/1-28.html" style="color: #cd4517; line-height: 1.4;" target="_blank">Genesis 1:28</a></h1>
<div style="line-height: 1.4; margin-bottom: 18px;">
Then God blessed them, and God said to them, "Be fruitful and multiply; fill the earth and subdue it; have dominion over the fish of the sea, over the birds of the air, and over every living thing that moves on the earth."</div>
<h1 style="font-size: 20px; font-weight: normal; line-height: 1.5em; margin: 0px 0px 18px;">
<a data-mce-href="http://www.biblestudytools.com/nkjv/galatians/5-1.html" href="http://www.biblestudytools.com/nkjv/galatians/5-1.html" style="color: #cd4517; line-height: 1.4;" target="_blank">Galatians 5:1</a></h1>
<div style="line-height: 1.4; margin-bottom: 18px;">
Stand fast therefore in the liberty by which Christ has made us free, and do not be entangled again with a yoke of bondage.</div>
<h1 style="font-size: 20px; font-weight: normal; line-height: 1.5em; margin: 0px 0px 18px;">
<a data-mce-href="http://www.biblestudytools.com/nkjv/galatians/3-13.html" href="http://www.biblestudytools.com/nkjv/galatians/3-13.html" style="color: #cd4517; line-height: 1.4;" target="_blank">Galatians 3:13</a></h1>
<div style="line-height: 1.4; margin-bottom: 18px;">
Christ has redeemed us from the curse of the law, having become a curse for us (for it is written, "Cursed is everyone who hangs on a tree")</div>
</blockquote>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
Freedom and Dominion! To secure the rights of Men Governments are created!</div>
<blockquote style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; font-style: italic; line-height: 18px; padding: 0px 3em;">
<div style="line-height: 1.4; margin-bottom: 18px;">
<a data-mce-href="http://www.wallbuilders.com/libissuesarticles.asp?id=25685" href="http://www.wallbuilders.com/libissuesarticles.asp?id=25685" style="color: #cd4517; line-height: 1.4;" target="_blank">We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness. — That to secure these rights, Governments are instituted among Men, deriving their just powers from the consent of the governed, — That whenever any Form of Government becomes destructive of these ends, it is the Right of the People to alter or to abolish it, and to institute new Government, laying its foundation on such principles and organizing its powers in such form, as to them shall seem most likely to effect their Safety and Happiness.</a></div>
</blockquote>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
These men knew that only under the leadership of God can a government be created that will serve the needs of the people. They also knew that no man was created to rule another man. So in the likeness of the ministry of Jesus, who said He didn't come to be served but to serve, these men created a system of servant leadership. They went on to draft a&nbsp;<a data-mce-href="http://www.wallbuilders.com/libissuesarticles.asp?id=36438" href="http://www.wallbuilders.com/libissuesarticles.asp?id=36438" style="color: #cd4517; line-height: 1.4;" target="_blank">Constitution</a>&nbsp;that will oversee the government that they were creating. After the basic&nbsp;<a data-mce-href="http://www.wallbuilders.com/libissuesarticles.asp?id=36438" href="http://www.wallbuilders.com/libissuesarticles.asp?id=36438" style="color: #cd4517; line-height: 1.4;" target="_blank">Constitution</a>&nbsp;was written they went home to their respective homes and brought this before the leadership of their home lands. After coming back together to seal this document as their governing document they would be adding a few more things.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
The states decided not to ratify (make&nbsp;permanent) the US Constitution until certain rights and liberties were ensured.</div>
<blockquote style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; font-style: italic; line-height: 18px; padding: 0px 3em;">
<div style="line-height: 1.4; margin-bottom: 18px;">
Opposition to the ratification of the Constitution was partly based on the Constitution's lack of adequate guarantees for&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Civil_liberties" href="http://en.wikipedia.org/wiki/Civil_liberties" style="color: #cd4517; line-height: 1.4;" title="Civil liberties">civil liberties</a>. To provide such guarantees, the First Amendment (along with the rest of the&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/United_States_Bill_of_Rights" href="http://en.wikipedia.org/wiki/United_States_Bill_of_Rights" style="color: #cd4517; line-height: 1.4;" title="United States Bill of Rights">Bill of Rights</a>) was submitted to the states for ratification on September 25, 1789, and adopted on December 15, 1791.&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/First_Amendment_to_the_United_States_Constitution" href="http://en.wikipedia.org/wiki/First_Amendment_to_the_United_States_Constitution" style="color: #cd4517; line-height: 1.4;" target="_blank">(Wiki)</a></div>
</blockquote>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="line-height: 1.4;">1st Amendment</strong></div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
The first of these rights, the most important to the most people was religious freedom! The churches were persecuted by a religious organization that was run by the government. The government told the church what they could and could not do, and could and could not say/preach. This was intolerable! So the first and greatest ammendment to the US Constitution was to secure the rights of the Church to preach and teach and practice freely her religion, the way she saw fit. The Bible and Ten commandments were welcome and invited into the government, it's offices, and it's halls. ALL laws of early American History were created using the Bible as their framework. However they didn't want the government interfering in the Churches business. The amendment states the following:</div>
<blockquote style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; font-style: italic; line-height: 18px; padding: 0px 3em;">
<div style="line-height: 1.4; margin-bottom: 18px;">
<em style="border: none; font-style: normal; line-height: 1.4;">Congress shall&nbsp;<strong style="line-height: 1.4;">make no law</strong>&nbsp;respecting an establishment of religion, or&nbsp;<strong style="line-height: 1.4;">prohibiting the free exercise</strong>&nbsp;thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.<a data-mce-href="http://en.wikipedia.org/wiki/First_Amendment_to_the_United_States_Constitution" href="http://en.wikipedia.org/wiki/First_Amendment_to_the_United_States_Constitution" style="color: #cd4517; line-height: 1.4;" target="_blank">(Wiki)</a></em></div>
</blockquote>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
There is however a twisting that came later. This firm security in freedom would be twisted by evil men and turned against the Church.&nbsp;</div>
<blockquote style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; font-style: italic; line-height: 18px; padding: 0px 3em;">
<div style="line-height: 1.4; margin-bottom: 18px;">
In 1947, in the case&nbsp;<em style="border: none; font-style: normal; line-height: 1.4;">Everson v. Board of Education</em>, the Supreme Court declared, "The First Amendment has erected a wall between church and state. That wall must be kept high and impregnable. We could not approve the slightest breach." The "separation of church and state" phrase which they invoked, and which has today become so familiar, was taken from an exchange of letters between President Thomas Jefferson and the Baptist Association of Danbury, Connecticut, shortly after Jefferson became President.&nbsp;<a data-mce-href="http://www.wallbuilders.com/libissuesarticles.asp?id=123" href="http://www.wallbuilders.com/libissuesarticles.asp?id=123" style="color: #cd4517; line-height: 1.4;" target="_blank">(Wall Builders)</a></div>
</blockquote>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
So then, a group of people in authority chose to override and change the intention and direction of the founding fathers. Now the Government would be protected from the Church, rather than the Church protected from the Government. Since that day an all out attack has come against the Church of Jesus by the very government that was founded to protect the Church. The very government that was told NOT to make any law prohibiting free speech or free&nbsp;exercise&nbsp;of religion, is now attacking the church by banning it's visible/verbal use in government buildings and now in public arenas. Just as the Church lost it's power when it was taken over by the government of ancient Rome, it now lost it's power to a growing all powerful government in the USA as well.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
It is a direct violation of the 1st amendment for any government entity to ban the free practice of&nbsp;religion&nbsp;in any part of this country, especially in it's leadership forums and offices. For the government to take down the 10 commandments, or remove nativity scenes from public places is a direct violation of the spirit and intent of the 1st amendment. Yet it's happening, and people by and in large are&nbsp;unaware&nbsp;that it's a violation, or unsure what they can do about it. The case of Everson Vs Board of Education demonstrates an official turn from the way things should be and a slow degrading of the moral fabric of our society. This decision was not created by accident. It was created by people who had a very real and aggressive vision to re-write american history and change america into their image. Socialism was now being weaved into the US fabric.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="line-height: 1.4;">Socialism VS USA</strong></div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
In a time when Marxism and Communism would have been&nbsp;despised there had to come a new plan. Upton Sinclair wrote a letter to Normal Thomas in 1951, both being socialists: "The American People will take Socialism, but they won't take the label..." And so both parties of have adapted to many pieces of this Satanic Doctrine. Call it Liberal,&nbsp;Progressive, or call it what it is: Godless Humanism. Either way, the people of America have been sold this way of thinking that has directly violated both the Bible and the US Constitution in favor of other forms of government that have proven time and again to fail, as they lack God's&nbsp;Wisdom, Guidance, and Protection.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
Socialism is a way of government that at it's core denies God. In fact, for the&nbsp;constructs&nbsp;of socialism to thrive you must remove God from the society first. In order to take any society just convince the kids. In time, they grow up and teach their kids and in one to two generations you will have taken a society. So naturally the first step in removing God from the country, so that socialism can thrive, is to remove God from schools! However, because America has always been a Christian Nation, founded by God Himself, this has proven more difficult than they thought.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
Now there are private schools that still teach God to kids, and Christian academics have risen to show the obvious holes in the false science of evolution. So what has happened is a country divided. This divide will only grow worse and not better. The divide is due to two opposing world views.</div>
<ol style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; list-style-image: initial; list-style-position: initial; margin: 0px 0px 18px 20px;">
<li style="line-height: 1.4;">God is Highest Authority: Men lead by serving.</li>
<li style="line-height: 1.4;">Man is Highest Authority: Men lead by ruling other men.</li>
</ol>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
Those who believe there is no God, or that he is&nbsp;unknowable, or generally despise the Bible, find themselves on the side of Liberalism/Socialism. Those that believe there is a God, He is knowable, and the Bible is His Word find themselves on the side of&nbsp;Conservatism/Judeo-Christian Ethics. So this divide continues to increase.<br />
<br />
Why is the country so divided about the fate of Israel, a nation smaller than the state of New&nbsp;Jersey? Because it's God's country! If you are a socialist you want God removed from Israel just as much as you do from America. They are a constant reminder that the Bible is true.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="line-height: 1.4;">America's New Civil War</strong></div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
This is where we find ourselves today. We are a country at war. Not with enemies outside of the USA, not really. We are at war with ourselves. The USA is involved in a civil war. This civil war will not ultimately be fought with guns in battle. This civil war is a war of worldviews. Satan's camp vs God's camp. Socialism vs The Bible. Liberal vs Conservative. Pro-Choice (to kill an innocent baby) vs Pro-Life (to protect all life, any age). This is the war we find ourselves in. It will not be won in court. It will not be won by talking. You cannot convince a person who is&nbsp;deceived&nbsp;that they are wrong. The weapons of our warfare are not carnal, but they ARE mighty! We pull down strongholds and&nbsp;everything that exalts itself against the knowledge of God. (<a data-mce-href="http://www.biblestudytools.com/nkjv/2-corinthians/passage.aspx?q=2-corinthians+10:1-9" href="http://www.biblestudytools.com/nkjv/2-corinthians/passage.aspx?q=2-corinthians+10:1-9" style="color: #cd4517; line-height: 1.4;" target="_blank">2 Cor 10:4</a>) We will not win this battle with words alone, but with a demonstration of God's power. (<a data-mce-href="http://www.biblestudytools.com/nkjv/1-corinthians/2-4.html" href="http://www.biblestudytools.com/nkjv/1-corinthians/2-4.html" style="color: #cd4517; line-height: 1.4;" target="_blank">1 Cor 2:4</a>,&nbsp;<a data-mce-href="http://www.biblestudytools.com/nkjv/1-corinthians/4-20.html" href="http://www.biblestudytools.com/nkjv/1-corinthians/4-20.html" style="color: #cd4517; line-height: 1.4;" target="_blank">1 Cor 4:20</a>,&nbsp;<a data-mce-href="http://www.biblestudytools.com/nkjv/1-thessalonians/1-5.html" href="http://www.biblestudytools.com/nkjv/1-thessalonians/1-5.html" style="color: #cd4517; line-height: 1.4;" target="_blank">1 Thess 1:5</a>)</div>
<div style="margin-bottom: 18px;">
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px;">
America is not in need of a re-write. It was written just fine. It's not in need of being over thrown, as the former government was. America is in need of a purge; a detox, if you will. We need to address the poison that has been injected into the arm of this nation and draw it out.&nbsp;It is now time, once again, for the Church to stand once again for Righteousness to stand and say: "NO!"&nbsp;</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px;">
<br /></div>
<span style="color: #444444; font-family: Arial, Trebuchet MS, sans-serif; font-size: x-small;"><span style="line-height: 18px;">It is once again time for the Church to issue an eviction notice to a system of government that has creeped in through Satanic forces and&nbsp;poisoned&nbsp;this country; a system of Tyranny and Godlessness and Oppression. This nation was founded to protect the Church FROM a large&nbsp;interfering&nbsp;government and it's the Church, that must first of all rise up and take it's place.&nbsp;This notice will not be given by a decree in battle, but it will be in our action and by the Spirit of God. It will be in our Call to Excellence!</span></span></div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="line-height: 1.4;">Darrell G. Wolfe</strong></div>
