---
title: 'Prayer and Politics'
date: '2012-09-18T04:57:00.0010000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'LIVE'
blogger_post_id: '4995277898725979537'
blogger_filename: '/2012/09/prayer-and-politics.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
---

<br />
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
In a prophecy some time ago.&nbsp;<a data-mce-href="http://www.kcm.org/sites/kcm.org/files/cck/prophecy/field_prophecy_attachment/Kenneth_Copeland_Prophecy_pay_attention_0.pdf" href="http://www.kcm.org/sites/kcm.org/files/cck/prophecy/field_prophecy_attachment/Kenneth_Copeland_Prophecy_pay_attention_0.pdf" style="color: #cd4517; line-height: 1.4;" target="_blank">Oct 19, 2008</a>&nbsp;Kenneth Copeland said to pay no attention to what the news media or politicians had to say.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
We are so apt to get to extremes in this realm of politics. Christians either ignore voting entirely choosing to be "Spiritual" and ignore the world that we knew would darker in the last days, or they get so heatedly involved that they loose spiritual focus and get angry with the people they disagree with, who are usually the ones who need to get saved but are now being turned off from Jesus by the ones who should be reaching them.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
So should we ignore&nbsp;politics? NO! We are called to be salt and light, and we have been given a&nbsp;tremendous&nbsp;opportunity&nbsp;here in the USA to participate in the governance of our own nation. There is no King, or authority, or law, that is so high that it cannot be changed with a demand from a united people. We not only have a right but a responsibility to participate in politics, a right which far too many Christians fail to&nbsp;exercise.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
We must find a place of proper understanding when it comes to dealing in the natural affairs of this life. We have &nbsp;been given the Authority of Adam restored to us. We have the dominion and authority to rule and reign on this planet. With that authority comes the&nbsp;responsibility&nbsp;to be the salt and light.&nbsp;<a data-mce-href="http://bible.cc/2_thessalonians/2-6.htm" href="http://bible.cc/2_thessalonians/2-6.htm" style="color: #cd4517; line-height: 1.4;" target="_blank">2 Thess 2</a>&nbsp;tells us that the Church, which Jesus called the salt and light, will continue to hold back the spirit of the&nbsp;Antichrist&nbsp;which has been working hard to take this planet by storm until it is taken out of the way. Until the day Jesus takes the Church out, this planet is still under our watchful care. We here in the USA are given the added responsibility to keep this nation as the beacon of light to a dying world. More financial and physical aid goes from the US to hurting people in other countries than from any other country. Most of the world's missionaries come from the USA. We are the salt and light.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
However we must use this ability to stand up for right, and speak and act with one voice for righteousness, without making unnecessary&nbsp;enemies. Many who might come to know Jesus and see the&nbsp;benefits&nbsp;of following his&nbsp;prescription&nbsp;of navigating life are turned off by our anger and temper with those who oppose us. We must be willing and able to have a conversation with someone who would love to&nbsp;antagonize&nbsp;us and still walk away clean before God that we spoke in Love. How do we change a nation, repeal ungodly laws, and enforce Righteousness without turning off the ones who need us most? Prayer.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
Prayer for Hearts</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
First of all, by praying for the people of this nation, and for those we have contact with, our own hearts become more&nbsp;sensitive&nbsp;to their needs. Before you get into a heated discussion with a gay person about the sanctity of marriage, show them, through your daily interactions, that you love them as they are. It's ok to be against sin, and not become angry with the sinner.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
Prayer for the Nation</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<a data-mce-href="http://www.kcm.org/sites/kcm.org/files/cck/prophecy/field_prophecy_attachment/Kenneth_Copeland_Prophecy_pay_attention_0.pdf" href="http://www.kcm.org/sites/kcm.org/files/cck/prophecy/field_prophecy_attachment/Kenneth_Copeland_Prophecy_pay_attention_0.pdf" style="color: #cd4517; line-height: 1.4;">http://www.kcm.org/sites/kcm.org/files/cck/prophecy/field_prophecy_attachment/Kenneth_Copeland_Prophecy_pay_attention_0.pdf</a></div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
“Pay Attention to Me…My system is stronger than ever.”</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<a data-mce-href="http://www.kcm.org/real-help/prophecy/your-finest-hour-yet-come" href="http://www.kcm.org/real-help/prophecy/your-finest-hour-yet-come" style="color: #cd4517; line-height: 1.4;">http://www.kcm.org/real-help/prophecy/your-finest-hour-yet-come</a></div>
<div id="kcmrealhelp-header-urls" style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px;">
<h1 style="font-size: 20px; font-weight: normal; line-height: 1.5em; margin: 0px 0px 18px;">
Your Finest Hour Is Yet to Come</h1>
<div id="kcmrealhelp-print-urls" style="line-height: 1.4;">
<a data-mce-href="http://www.kcm.org/print/real-help/prophecy/your-finest-hour-yet-come" href="http://www.kcm.org/print/real-help/prophecy/your-finest-hour-yet-come" rel="nofollow" style="color: #cd4517; line-height: 1.4;" title="Display a printer-friendly version of this page.">Printer-friendly version</a>&nbsp; &nbsp;<a data-mce-href="http://www.kcm.org/printpdf/real-help/prophecy/your-finest-hour-yet-come" href="http://www.kcm.org/printpdf/real-help/prophecy/your-finest-hour-yet-come" rel="nofollow" style="color: #cd4517; line-height: 1.4;" title="Display a PDF version of this page.">PDF version</a></div>
</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px;">
Prophecy delivered by Kenneth Copeland</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px;">
on August 4, 2009</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px;">
Southwest Believers' Convention</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px;">
<div style="line-height: 1.4; margin-bottom: 18px;">
“No, no, no, no, this is not the time,” saith the Lord, “of the downfall of your nation. Your nation is under covenant with Me,” saith the Lord. “You are witnessing not the failure of the United States, you are witnessing the failure of a worldly financial system that has eroded over the years.</div>
<div style="line-height: 1.4; margin-bottom: 18px;">
“My Word of prosperity, My Word of function, My Word that this nation began on and prospered beyond any nation in the history of this world. No, the United States is not falling. No! I will not allow that to happen,” says the Spirit of Grace. “How foolish do you think I am to allow the cradle of the gospel to fall from its limb? How foolish do you think I am? No, I remember your deeds, I remember the gospel that’s come from this nation. I remember,” saith the Lord, “that this is the most giving nation in history and I will not, I will not, I will not let you go.” Hallelujah. Give the Lord praise, hallelujah.</div>
<div style="line-height: 1.4; margin-bottom: 18px;">
“No, no, no, no, your finest hour is yet to come and it is on its way and it’s being born at this very time.” Oh, hallelujah. Hallelujah. “No, no, no, I did not bring this financial disaster on this nation. Now some have said this is judgment. It is judgment but I’m not bringing judgment on this nation. The seed of sin and Babylonian-world thinking has in itself its own judgment and its own disaster. And when you continue to walk out of line with My Word and My plan and My way you will eventually fail.</div>
<div style="line-height: 1.4; margin-bottom: 18px;">
“It’s not this nation that’s failing, it is the system that it has eroded into by getting away from My Word and depending on Me. But fear not. I have My eye on it and it will go only so far and no further,” saith the Lord. Hallelujah. “And you will see it, you will see it, you will be in it, you will be involved in the greatest spiritual awakening that this nation has ever seen. This is My time,” saith God. Give the Lord praise and thanksgiving.</div>
</div>
