---
title: 'Church History 101 - The Glorious Church'
date: '2012-09-18T04:58:00.0050000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'LIVE'
blogger_post_id: '947122432424898079'
blogger_filename: '/2012/09/church-history-101-glorious-church.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
---

<br />
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="line-height: 1.4;">Church History 101</strong></div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
In the 1st 300 years of Church History Christians were persecuted, hunted, hated, and killed. Under this constant pressure Church Growth Exploded! People were spread out further and further with each new wave of persecution and the Gospel message kept spreading. There were miracles, signs, and wonders like the world had never seen before and on a scale the world has never seen since. As people spread and persecution continued the boldness of faith in the face of death won over the hearts of people by the 100,000's!</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
In 313 AD the best and worst thing happened to the Church of Jesus. It became accepted. Under the rule of&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Constantine_I_and_Christianity" href="http://en.wikipedia.org/wiki/Constantine_I_and_Christianity" style="color: #cd4517; line-height: 1.4;" target="_blank">Constantine I</a>&nbsp;in the Edict of Milan, Christianity became not only legal in the Roman empire,&nbsp;<em style="border: none; line-height: 1.4;">"but&nbsp;in 391 under&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Theodosius_I" href="http://en.wikipedia.org/wiki/Theodosius_I" style="color: #cd4517; line-height: 1.4;" title="Theodosius I">Theodosius I</a>&nbsp;Christianity became the official&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/State_church_of_the_Roman_Empire" href="http://en.wikipedia.org/wiki/State_church_of_the_Roman_Empire" style="color: #cd4517; line-height: 1.4;" title="State church of the Roman Empire">state religion of Rome</a>, to the exclusion of all others" (<a data-mce-href="http://en.wikipedia.org/wiki/Religion_in_ancient_Rome" href="http://en.wikipedia.org/wiki/Religion_in_ancient_Rome" style="color: #cd4517; line-height: 1.4;" target="_blank">Wiki</a>)</em></div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
Slowly, over time, Satanic worship practices such as&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Constantine_I_turn_against_Paganism" href="http://en.wikipedia.org/wiki/Constantine_I_turn_against_Paganism" style="color: #cd4517; line-height: 1.4;" target="_blank">magic</a>, and other things that were anti-Christian were banned. However, this was good and bad. Yes, Christianity could now be spread over all the world, and in many ways this was a blessing to the Church. But as the Church lost its governance to the State/Empire it lost its way. As new societies were brought into this Christian Nation (The Holy Roman Empire) their practices were not abolished, but rather adopted and renamed. There were also pre-existing&nbsp;societies and their practices, like the Hellenistic practice of worshiping the god's of their own creation, from which most&nbsp;Greek&nbsp;mythologies arose.</div>
<blockquote style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; font-style: italic; line-height: 18px; padding: 0px 3em;">
<div style="line-height: 1.4; margin-bottom: 18px;">
From the 2nd century onward, the&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Church_Fathers" href="http://en.wikipedia.org/wiki/Church_Fathers" style="color: #cd4517; line-height: 1.4;" title="Church Fathers">Church Fathers</a>&nbsp;began to condemn the diverse religions practiced throughout the Empire collectively as "pagan."<sup style="bottom: 1ex; font-size: 10px; height: 0px; line-height: 1; position: relative; vertical-align: baseline;"><a data-mce-href="http://en.wikipedia.org/wiki/Religion_in_ancient_Rome#cite_note-5" href="http://en.wikipedia.org/wiki/Religion_in_ancient_Rome#cite_note-5" style="color: #cd4517; line-height: 1.4;">[6]</a></sup>&nbsp;In the early 4th century,<a data-mce-href="http://en.wikipedia.org/wiki/Constantine_I" href="http://en.wikipedia.org/wiki/Constantine_I" style="color: #cd4517; line-height: 1.4;" title="Constantine I">Constantine I</a>&nbsp;became the first emperor to&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Christian_conversion" href="http://en.wikipedia.org/wiki/Christian_conversion" style="color: #cd4517; line-height: 1.4;" title="Christian conversion">convert to Christianity</a>, launching the era of Christian&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Hegemony" href="http://en.wikipedia.org/wiki/Hegemony" style="color: #cd4517; line-height: 1.4;" title="Hegemony">hegemony</a>. The emperor&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Julian_the_Apostate" href="http://en.wikipedia.org/wiki/Julian_the_Apostate" style="color: #cd4517; line-height: 1.4;" title="Julian the Apostate">Julian</a>&nbsp;made a short-lived attempt to revive traditional and&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Hellenistic_religion" href="http://en.wikipedia.org/wiki/Hellenistic_religion" style="color: #cd4517; line-height: 1.4;" title="Hellenistic religion">Hellenistic religion</a>&nbsp;and to affirm the special status of Judaism, but in 391 under&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Theodosius_I" href="http://en.wikipedia.org/wiki/Theodosius_I" style="color: #cd4517; line-height: 1.4;" title="Theodosius I">Theodosius I</a>&nbsp;Christianity became the official&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/State_church_of_the_Roman_Empire" href="http://en.wikipedia.org/wiki/State_church_of_the_Roman_Empire" style="color: #cd4517; line-height: 1.4;" title="State church of the Roman Empire">state religion of Rome</a>, to the exclusion of all others. Pleas for religious tolerance from traditionalists such as the senator&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Quintus_Aurelius_Symmachus" href="http://en.wikipedia.org/wiki/Quintus_Aurelius_Symmachus" style="color: #cd4517; line-height: 1.4;" title="Quintus Aurelius Symmachus">Symmachus</a>&nbsp;(d. 402) were rejected, and Christian monotheism became a feature of Imperial domination.&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Christian_heresy" href="http://en.wikipedia.org/wiki/Christian_heresy" style="color: #cd4517; line-height: 1.4;" title="Christian heresy">Heretics</a>&nbsp;as well as non-Christians were subject to exclusion from public life or persecution, but Rome's original religious hierarchy and many aspects of its ritual influenced Christian forms, and many pre-Christian beliefs and practices survived in Christian festivals and local traditions. (<a data-mce-href="http://en.wikipedia.org/wiki/Religion_in_ancient_Rome" href="http://en.wikipedia.org/wiki/Religion_in_ancient_Rome" style="color: #cd4517; line-height: 1.4;" target="_blank">Wiki</a>)</div>
</blockquote>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="line-height: 1.4;">Darkness at Sunset</strong></div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
This&nbsp;officialism&nbsp;of the Church lost the house to house spreading, and open debates in public arenas. It became accepted, and people relaxed, forgetting that there is an enemy out to steal, kill, and destroy. Over time priests of the Church took the place of the&nbsp;Pharisees&nbsp;of the first covenant. Rules were made that were based on man's ideas, rather than on sound biblical teaching. Worst of all, the Word of God was locked away, under to preposterous idea that only a priest could understand it, and therefore the common man was unable to read the Word for himself. Previously churches read and taught the word, nearly daily. Now the Word would be read in a learned language and the people would base their lives on the teaching of men once again. The valid ministry of Apostles, Prophets, Evangelists, Pastors, and Teachers was replaced by Priests of the official Church order.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
This ushered in a period of time in earth's history that even secular scholars call the dark ages. They call it dark because religion bound the people and there were no inventions and was no progress. The truth is that there were no inventions and there was no progress because of religion, because religion had locked away the LIGHT of the Word of God! Religion is always contrary to God's people. And so the earth lay in darkness for a time. Satan most likely thought he'd won. Jesus may have come and gone, and the bible says that demons NEVER would have&nbsp;crucified&nbsp;Him if they'd known what that would mean. (<a data-mce-href="http://bible.cc/1_corinthians/2-8.htm" href="http://bible.cc/1_corinthians/2-8.htm" style="color: #cd4517; line-height: 1.4;" target="_blank">1 Cor 2:8</a>) But at least they were able to stamp out the light that He left in the form of&nbsp;religion&nbsp;which they could control. Yet, there were always a remnant that would rise, here and there, reminding them that the light still stood. These were often lumped together in historical view as "<a data-mce-href="http://en.wikipedia.org/wiki/Christian_mysticism#Eastern_Christianity" href="http://en.wikipedia.org/wiki/Christian_mysticism#Eastern_Christianity" style="color: #cd4517; line-height: 1.4;" target="_blank">Mystics</a>".</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
This period of history gave rise to two things:</div>
<ol style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; list-style-image: initial; list-style-position: initial; margin: 0px 0px 18px 20px;">
<li style="line-height: 1.4;">Light of the Word was hidden away from the common man. No major miracles or social breakthroughs.</li>
<li style="line-height: 1.4;">Darkness Rises. False religions took a stronger hold in Asia and Islam rises in the Middle East.</li>
</ol>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="line-height: 1.4;">Sunrise</strong></div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
There were things the Catholic Church did well. During the darkness, despite it's downfalls, the Catholic Church&nbsp;preserved&nbsp;the Word of God. The Bible was preserved through priests writing and re-writing the bible through painstaking process. The copies were processed by counting words and choosing certain places and making sure that they are in the right spots. Any handwritten copy that didn't meet the exacting standards was thrown out.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
Then came a day that a bright and public light once again flared up in the night. It was nothing more than a bright match stick, but against the backdrop of&nbsp;religious&nbsp;darkness it burned brightly and could be seen by all.&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Martin_Luther" href="http://en.wikipedia.org/wiki/Martin_Luther" style="color: #cd4517; line-height: 1.4;" target="_blank">Martin Luther</a>, in 1517, posted his&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Ninety-five_theses" href="http://en.wikipedia.org/wiki/Ninety-five_theses" style="color: #cd4517; line-height: 1.4;" title="Ninety-five theses">Ninety-five theses</a>. This was a declaration, above all else, that man would be saved through FAITH and not works! Followed by the work on&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/John_Calvin" href="http://en.wikipedia.org/wiki/John_Calvin" style="color: #cd4517; line-height: 1.4;" target="_blank">John Calvin</a>&nbsp;showing that man needed a savior. This sparked what would become known as the&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Protestant_Reformation" href="http://en.wikipedia.org/wiki/Protestant_Reformation" style="color: #cd4517; line-height: 1.4;" target="_blank">Protestant Reformation</a>. This reformation, despite it's often tripping over itself, became good for the World and the Church in the long run. Both Catholic and Protestant benefited from this reformation. Some ideas, over time, that were not God ideas were in fact altered by the Catholic Church and by the Denominations that rose and fell in the Protestant movement. Both groups benefited from this new spark of ideas.&nbsp;</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
Over time there were many more waves of reformation and restoration. As the Word of God became available to the common man, through modern language translations, and common language translations, and eventually the printing press; the people were fed the life bread of God. The spread of the Word made revivals spark brighter, and last longer and spread further. Eventually there were many denominations of churches that were created from the remnant of the fires of these revivals.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="line-height: 1.4;">Modern Light - Awakenings</strong></div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
The&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Great_Awakening" href="http://en.wikipedia.org/wiki/Great_Awakening" style="color: #cd4517; line-height: 1.4;" target="_blank">Great Awakening</a>&nbsp;came in the mid 1700's. Preachers such as&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Jonathan_Edwards_(theologian)" href="http://en.wikipedia.org/wiki/Jonathan_Edwards_(theologian)" style="color: #cd4517; line-height: 1.4;" target="_blank">Jonathan Edwards</a>&nbsp;and&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/George_Whitefield" href="http://en.wikipedia.org/wiki/George_Whitefield" style="color: #cd4517; line-height: 1.4;" target="_blank">George Whitefield</a>&nbsp;came preaching a new message. This message was designed to engage not just the minds of the hearers but the hearts as well. They were seeking an emotional response to lead the person to a lifestyle change. They wanted to see evidence of repentance. This was the period when the USA was being moved from a set of colonies of England and taking a stand as its own nation. It has been said that without this period of Great Awakening there never would have been a United States of America. It was these types of teachings that gave men boldness to rise and declare that evil abuses of&nbsp;tyrants&nbsp;must stop and good men must make a stand.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
The&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Great_Awakening" href="http://en.wikipedia.org/wiki/Great_Awakening" style="color: #cd4517; line-height: 1.4;" target="_blank">Second Great Awakening</a>&nbsp;took place in the 1800's. It was at this time that a life of purity was being preached, and hell was being made known loud and clear. Get right or else was the message. It sparked a period of cultural shifting away from evil. This period gave birth to the short-lived abolitionist movement, which banned alcohol. It also gave rise to <b>The Church</b> to fight for the abolition of Slavery and Women's Rights. (Yes, that's right, it was God and His Church, not some socialist liberal, that started these movements. If freedom is being brought to captives God is the instigator.)</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
The&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Great_Awakening" href="http://en.wikipedia.org/wiki/Great_Awakening" style="color: #cd4517; line-height: 1.4;" target="_blank">Third Great Awakening</a>&nbsp;took place in the late 1800's and early 1900's. This gave rise to social messages about doing good to your neighbor and a rekindling of the Good Samaritan.&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Dwight_L._Moody" href="http://en.wikipedia.org/wiki/Dwight_L._Moody" style="color: #cd4517; line-height: 1.4;" target="_blank">Dwight L Moody</a>&nbsp;became popular during this time. Also organization such as the&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/YMCA" href="http://en.wikipedia.org/wiki/YMCA" style="color: #cd4517; line-height: 1.4;" target="_blank">YMCA</a>&nbsp;and&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Salvation_Army" href="http://en.wikipedia.org/wiki/Salvation_Army" style="color: #cd4517; line-height: 1.4;" target="_blank">Salvation Army</a>&nbsp;were started out of this movement. During this time in the late 1800's a wave of&nbsp;independent&nbsp;evangelists&nbsp;came out of the Christian Churches. They were not linked to any one group or any one denomination until development Churches such as The&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Pentecostalism" href="http://en.wikipedia.org/wiki/Pentecostalism" style="color: #cd4517; line-height: 1.4;" target="_blank">Pentecostal</a>&nbsp;Church, Church of God, Assemblies of God, Apostolic Church, and others in the early and mid 1900's. Early Preachers such as&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Smith_Wigglesworth" href="http://en.wikipedia.org/wiki/Smith_Wigglesworth" style="color: #cd4517; line-height: 1.4;" target="_blank">Smith Wigglesworth</a>&nbsp;and&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Charles_Parham" href="http://en.wikipedia.org/wiki/Charles_Parham" style="color: #cd4517; line-height: 1.4;" target="_blank">Charles Parham</a>&nbsp;demonstrated another branch of Christianity and preached a message of close personal experience with God, gifts of the Holy Spirit, Healing, and other teachings that had been dead or dormant in most Churches up to then.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
The&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Great_Awakening" href="http://en.wikipedia.org/wiki/Great_Awakening" style="color: #cd4517; line-height: 1.4;" target="_blank">Fourth Great Awakening</a>&nbsp;took place in the mid 1900's from post World War II (1945) to the mid 1980's. This period was marked by a rapid decrease in many denominational churches due to an infiltration of tolerance doctrines. As Churches began to openly endorse homosexual pastors, abortion, and other secular and Satanic ideas people sought new Churches that were not associated with the mainline denominations. Other denominational Churches grew as they found new strength as the rose to take a stand against these developments and stand for&nbsp;conservative&nbsp;Christian values. This was a period of time when&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Jesus_Movement" href="http://en.wikipedia.org/wiki/Jesus_Movement" style="color: #cd4517; line-height: 1.4;" target="_blank">The Jesus Movement</a>&nbsp;swept the nation.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
This period gave rise to teachers like&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Hal_Lindsey" href="http://en.wikipedia.org/wiki/Hal_Lindsey" style="color: #cd4517; line-height: 1.4;" target="_blank">Hal Lindsey</a>,&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Chuck_Smith_(pastor)" href="http://en.wikipedia.org/wiki/Chuck_Smith_(pastor)" style="color: #cd4517; line-height: 1.4;" target="_blank">Chuck Smith</a>, founder of,<a data-mce-href="http://en.wikipedia.org/wiki/Bill_Bright" href="http://en.wikipedia.org/wiki/Bill_Bright" style="color: #cd4517; line-height: 1.4;" target="_blank">&nbsp;Bill Bright</a>,&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Billy_Graham" href="http://en.wikipedia.org/wiki/Billy_Graham" style="color: #cd4517; line-height: 1.4;" target="_blank">Billy Graham</a>,&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Kenneth_E._Hagin" href="http://en.wikipedia.org/wiki/Kenneth_E._Hagin" style="color: #cd4517; line-height: 1.4;" target="_blank">Kenneth Hagin</a>,&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Oral_Roberts" href="http://en.wikipedia.org/wiki/Oral_Roberts" style="color: #cd4517; line-height: 1.4;" target="_blank">Oral Roberts</a>,&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Charles_Capps" href="http://en.wikipedia.org/wiki/Charles_Capps" style="color: #cd4517; line-height: 1.4;" target="_blank">Charles Capps</a>,&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Kenneth_Copeland" href="http://en.wikipedia.org/wiki/Kenneth_Copeland" style="color: #cd4517; line-height: 1.4;" target="_blank">Kenneth Copeland</a>, and more.&nbsp;And Churches and Movements such as&nbsp;&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Calvary_Chapel" href="http://en.wikipedia.org/wiki/Calvary_Chapel" style="color: #cd4517; line-height: 1.4;" target="_blank">Calvary Chapel</a>,&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Association_of_Vineyard_Churches" href="http://en.wikipedia.org/wiki/Association_of_Vineyard_Churches" style="color: #cd4517; line-height: 1.4;" target="_blank">Vineyard</a>,&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Word_of_Faith" href="http://en.wikipedia.org/wiki/Word_of_Faith" style="color: #cd4517; line-height: 1.4;" target="_blank">Word of Faith</a>, and&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Jews_for_Jesus" href="http://en.wikipedia.org/wiki/Jews_for_Jesus" style="color: #cd4517; line-height: 1.4;" target="_blank">Jews for Jesus</a>. This was a period of time also known as the&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Charismatic_Movement" href="http://en.wikipedia.org/wiki/Charismatic_Movement" style="color: #cd4517; line-height: 1.4;" target="_blank">Charismatic&nbsp;Movement</a>. It was a time where a personal relationship with Jesus was preached. People could understand God without lofty theological words. The Gifts of the Spirit and Baptism of the Spirit were preached more widely.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="line-height: 1.4;">And Now...</strong></div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
The remnant of the fourth Great Awakening brings us up to today. Most of the teachers of the fourth Great Awakening are still with us and teaching. Throughout the 1980's and 1990's churches grew. A period of time came where&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Megachurch" href="http://en.wikipedia.org/wiki/Megachurch" style="color: #cd4517; line-height: 1.4;" target="_blank">Mega Churches</a>&nbsp;were created, which were Churches of much larger than normal congregations. Pastor<a data-mce-href="http://en.wikipedia.org/wiki/Rick_Warren" href="http://en.wikipedia.org/wiki/Rick_Warren" style="color: #cd4517; line-height: 1.4;" target="_blank">&nbsp;Rick Warren</a>&nbsp;was at the head of a movement to see&nbsp;<a data-mce-href="http://en.wikipedia.org/wiki/Church_growth" href="http://en.wikipedia.org/wiki/Church_growth" style="color: #cd4517; line-height: 1.4;" target="_blank">Church Growth</a>. Attempts were made to make churches less stuffy and provide an environment where the "Un-Churched" could be comfortable. Worship music also took off during this time, replacing organs and hymnals. Many churches looked to be more friendly to "seekers", those who would seek God but didn't have church background. They then&nbsp;endeavored&nbsp;to be more "seeker friendly". Although this has been looked down on, the heart of the movement was to win the lost. And it worked, by the 1,000's and 100,000's of thousands. Although some churches lost their fire and stand for righteousness in their fight to be "seeker friendly" this was never the intention of the movement or it's leaders. Many of the churches that started this trend have since continued with it's mission and clarified it's purpose, and are still making impact on the world around them today.<br />
<br />
<h4>
The Fifth Great Awakening... and the Last???</h4>
</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
So now we find ourselves in the post 2000 era. The seeker friendly movement has slowed down and a new breed of Christianity has risen. This new breed owes its thanks to all of those who came before, paving the way for each new wave of God's light. What is this new move? It hasn't been defined yet. I think we can call it the Fifth Great Awakening. Christians are rising everywhere from a slumber. They are finding that their "Christian Nation" has been hijacked while they were asleep or fighting about theological differences.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
This new wave seems to be aimed at truth. We became so seeker friendly that we hid the truth so as not to offend. We have raised a generation of baby Christians. So this new wave seems to be saying to the world "WAIT! There is a God and Truth is Truth!" It's partially in response to a secular trend called "<a data-mce-href="http://en.wikipedia.org/wiki/Relativism" href="http://en.wikipedia.org/wiki/Relativism" style="color: #cd4517; line-height: 1.4;" target="_blank">Relativism</a>". This has given rise to things like&nbsp;<a data-mce-href="http://www.thetruthproject.org/" href="http://www.thetruthproject.org/" style="color: #cd4517; line-height: 1.4;" target="_blank">The Truth Project</a>, and to Churches like&nbsp;<a data-mce-href="http://www.elevationchurch.org/" href="http://www.elevationchurch.org/" style="color: #cd4517; line-height: 1.4;" target="_blank">Elevation Church</a>, and to new associations like&nbsp;<a data-mce-href="http://www.arcchurches.com/" href="http://www.arcchurches.com/" style="color: #cd4517; line-height: 1.4;" target="_blank">ARC</a>. It's become known that although denominations were, in some cases,&nbsp;hindrance&nbsp;to the moves of God there were benefits to them. The organizational structure of a denomination allowed the&nbsp;Body of Christ to move and act as one voice. So groups like&nbsp;<a data-mce-href="http://www.arcchurches.com/" href="http://www.arcchurches.com/" style="color: #cd4517; line-height: 1.4;" target="_blank">ARC</a>&nbsp;(Association&nbsp;of Related Churches) began, allowing for the&nbsp;independence&nbsp;that breeds the moves of God and the structure and support of a larger movement.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
So the question now is: "What is your part?" What is God moving in you to do regarding the things He wants done on this earth. It's always, always, been about people. God wants people saved. God doesn't want people to go to hell. All his moves have been about restoring the Kingdom of God on this earth and preparing the way for Jesus' return. So what part do you play?</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
Darrell G. Wolfe</div>
