---
title: 'Should Christians Vote?'
date: '2012-10-26T12:55:00.0000000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'DRAFT'
blogger_post_id: '3759517240420635876'
blogger_filename: '/2012/10/should-christians-vote.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
categories:
  - 'Digesting'
  - 'The Concern'
---

Should Christians Vote?<br />
<br />
<br />
The arguments for and against Christian's involvement in politics and social arenas are many and wordy. There are those who would vote for Democrats because they believe that they are more socially concsious. There are those who would vote for Republicans because they beleive that they are more moral on issues like Gay Marriage and Abortion. There are those whoe feel that all government is worldly and that we should avoid the world and be in it but seperate from it, as Alien Ambassadors. So what's the story here? What is God's opinion on human government and voting?<br />
<br />
God's Government<br />
<br />
<b><a href="http://www.biblestudytools.com/nkjv/isaiah/passage.aspx?q=isaiah+9:6-7" target="_blank">Isaiah 9:6-7</a></b><br />
<blockquote class="tr_bq">
<i>6 For unto us a Child is born, Unto us a Son is given; And the government will be upon His shoulder. And His name will be called Wonderful, Counselor, Mighty God, Everlasting Father, Prince of Peace. 7 Of the increase of His government and peace There will be no end, Upon the throne of David and over His kingdom, To order it and establish it with judgment and justice From that time forward, even forever. The zeal of the Lord of hosts will perform this.</i></blockquote>
Ultimately, in the end, God has a system of Government that Trumps all Human Systems. It is called a Theocracy. That is where God is the ruler. The one who makes all decisions. God appoints his leaders and men obey that assignment. This is the highest form of government. This is the form of government that Churches should follow in their leadership patterns, which is why the very idea that a Pastor could be hired or fired by a board of Elders and Deacons is preposterous to God's way of doing things.<br />
<br />
Jesus is our High Priest, High Apostle, King of Kings.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
Pro Christian Voting<br />
<a href="http://www.gotquestions.org/Christians-vote.html">http://www.gotquestions.org/Christians-vote.html</a><br />
<br />
Anti Christian Voting<br />
<a href="http://www.cogwriter.com/vote.htm">http://www.cogwriter.com/vote.htm</a><br />
<br />
Tony Evans<br />
<a href="http://www.youtube.com/watch?v=1HpVV3HvgZc&amp;feature=related">http://www.youtube.com/watch?v=1HpVV3HvgZc&amp;feature=related</a><br />
<a href="http://www.tonyevans.org/site/c.feIKLOOpGlF/b.2017593/k.BE75/Home.htm">http://www.tonyevans.org/site/c.feIKLOOpGlF/b.2017593/k.BE75/Home.htm</a><br />
<a href="http://www.churchadoptaschool.org/">http://www.churchadoptaschool.org/</a><br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />