---
title: 'World Views 101'
date: '2012-09-18T04:58:00.0020000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'LIVE'
blogger_post_id: '6610708433827668993'
blogger_filename: '/2012/09/world-views-101.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
---

<br />
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
World Views 101</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
The Church has been so busy seeking higher truth and fighting holy wars internally within factions that as a whole, in the USA, we've lost sight on the greater story. This nation, which was God's gift to Christianity has been taken for granted. As happened many times in Israel throughout the bible, this whole nation, because of a lack of Church involvement and apathy, has become a secular nation. The USA was never intended to be a secular nation. It was not the founders design, it was not God's design. This happened as a result of good men doing nothing.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
Turn by turn steps were taken by organized, focused, well funded individuals to remove God from this nation and create the state we have before us today. This was no accident. It was not something that just happened over time. It was a deliberate attack by Satan, through well organized groups.&nbsp;<a data-mce-href="http://www.youtube.com/watch?v=FFkR2omHl2I" href="http://www.youtube.com/watch?v=FFkR2omHl2I" style="color: #cd4517; line-height: 1.4;" target="_blank">Rick Renner on 02/12/2012</a>&nbsp;gave a timely message at EMIC letting us know that the bible told us that in these last days men who had a form of godliness would cast it off on purpose.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
How does the GLBT group have a more unified voice on their agenda that the Church of Jesus? Any group divided against itself cannot stand. Jesus told us that, and He also told us that the children of darkness were better at using their system that the Children of God were at using the Kingdom of God. We need to answer how we got here, and what we do about it. Before we do that, we must examine an important topic. World Views.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
Satan is at the root of all mindsets that take men away from God. The Bible tells us to renew out minds. Many times when dealing people it can be beneficial to know why they think the way they think. Paul demonstrated this to us when he went to a group of men and observed something about their city that gave him an entrance to their audience. He noticed a statue of an unknown God. There are times where a person may be called of God to go in guns blazing calling for a city to repent. But many times God uses situations, like this one with Paul, to find common ground and get into their heads a little bit.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
A "<a data-mce-href="http://en.wikipedia.org/wiki/World_view" href="http://en.wikipedia.org/wiki/World_view" style="color: #cd4517; line-height: 1.4;" target="_blank">World View</a>", in&nbsp;layman's&nbsp;terms, is the way a person view the world around them. There is no such thing as "just the way it is". Two people can look at the same event in real time and have completely different, and&nbsp;contradictory&nbsp;reactions. How can this happen? It is a result of their world view. World view is the structure on which you hang data to form an opinion of the data you found. It is the&nbsp;lenses&nbsp;through which you interpret data. This is the idea of "Rose Colored Glasses". A person with rose colored glasses sees the good in the world, "All is&nbsp;rosy" and none of the bad. This is as bad as it is good. Sure they are not&nbsp;pessimistic. However, they may also walk off a cliff because they cannot see harm coming their way to avoid it. A person with a view of all the bad will miss the great moments of life and perpetuate the bad. We must have a balanced and true view of the world.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
A man in an asylum may believe he is George Washington. This doesn't mean that he is. Having a world view doesn't make it true. It just means it's the way you see it. So for out purposes it's not enough to know about world views but we must be able to see them for what they are and choose the ones that correlate to reality. We must also be able to lovingly expose those that are not valid.</div>
<div style="color: #444444; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
A "<a data-mce-href="http://www.focusonthefamily.com/faith/christian_worldview/whats_a_christian_worldview.aspx" href="http://www.focusonthefamily.com/faith/christian_worldview/whats_a_christian_worldview.aspx" style="color: #cd4517; line-height: 1.4;" target="_blank">Christian World View</a>"</div>
