---
title: 'The Great Awakening'
date: '2013-01-20T22:19:00.0020000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'LIVE'
blogger_post_id: '7145564470489730736'
blogger_filename: '/2013/01/the-great-awakening.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
categories:
  - 'STORY'
  - 'Filler'
  - 'News'
---

<br />
<br />
<h4>
TIMES Magazine Coverstory: The New Great Awakening? May 1st, 2016&nbsp;</h4>
<blockquote class="tr_bq">
In national breaking news the town of Newfoundland CT has been the most recent in a chain of cities to officially and legally re-define it's city charter as distinctly Christian. While these cities all state emphatically that they do not endorse any one brand of Christianity and that all other faiths are still welcome to freely practice their faith or lack their of; certain special interest groups like the National Athiest Association have been vocal in their opposition to such a blend of government and religion. The cities claim that these official alignments more accurately reflect the nature of the USA and it's founding intentions to be a land free for all religious people, to be free from government's interfering with and preventing in any way the "free practice thereof", also known as the<a href="http://en.wikipedia.org/wiki/Free_Exercise_Clause" target="_blank"> Free Excersize Clause</a>. &nbsp;</blockquote>
<blockquote class="tr_bq">
In fact several such cases are being taken to the supreme court next month and many are anticicpating new challenges to the original <a href="http://www.oyez.org/cases/1940-1949/1947/1947_90" target="_blank">MCCOLLUM v. BOARD OF EDUCATION DIST. 71</a>&nbsp;interpretation of the "<a href="http://en.wikipedia.org/wiki/Establishment_Clause" target="_blank">Establishment Clause</a>" in 1948, which some are citing as diametrically opposed to the founders original intent. The case is being made and felt widely that it this establishment clause was meant to prohibit the government interfering with churches and not the churches from being directly involved in government. &nbsp;</blockquote>
<blockquote class="tr_bq">
These sweeping grass roots movements have been organic in natute, but seem to be in reaction to governments overstepping their bounds of authority in the name of this establishment clause. The "straw that broke the camels back" seems to have been the case of MCBRIDE v. CITY OF MANCHESTER which gained national attention as it was taken to the supreme court, case still pending review. This attention was fueld by social media sites as they were inundated with news about it, bill boards bought up by private individuals and organizations were seen throughout the country. The case was in regards to a pastor having a bible study in his home and the city of Manchester fining him for holding religious meetings without a conditional use permit in residentially zoned land. It was started after a neighbor complained about the amount of cars on the block. This same neighbor was also discovered to be having a Superbowl party with double the amount of cars the following weekend by local news reporters, which then broke into national news controversy. Social media caused the case and it's controversial elements to go viral.&nbsp;</blockquote>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />