---
title: 'Miles of Travel 2'
date: '2013-04-15T04:46:00.0010000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'LIVE'
blogger_post_id: '6697715255049899422'
blogger_filename: '/2013/04/miles-of-travel-2.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
categories:
  - 'STORY'
  - 'Miles'
---

The next morning Miles woke to the sound of two twin boys playing with trains, a baby crying and burnt bacon. Leslie, his wife, was on the phone. He worked his way into a seated position and let the blood flow back into his legs. That spiked feeling in his feet was an all too common occurrence, as was sleeping on the couch. He just didn't want to wake anyone when he got home late, and he'd been home late many days in a row now. Leslie put her hand up in a gesture of good morning, now do something.<br />
<br />
He went to the bedroom to find baby Jess crying her 6 month old eyes out. Of course once she saw him she calmed down a peg. He grabbed her up and set her on the changing table. "<i>For goodness sake! How is it possible for such a small thing to make that?!</i>" Once changed, clothes in the sealed hamper, and smiles and giggles all around he walked past the boys room and gave a groggy hello. They both said "<i>Good Morning Daddy</i>..." without looking up from their adventure. Even the trains said good morning. His face may not show it, but these moments are good moments, worth the hell he faces out in the world everyday.<br />
<br />
Miles didn't have the heart to tell Leslie that the iPod had been lost. She saved three months for that present. He figured he'd call the Buss Station Lost and Found before giving her the bad news...