---
title: 'Voting Unto Death'
date: '2013-04-18T10:52:00.0000000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'DRAFT'
blogger_post_id: '85388575219737140'
blogger_filename: '/2013/04/voting-unto-death.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
---

<br />
<br />
<br />
<br />
<br />
<br />
<br />
Hmmm<br />
<blockquote class="tr_bq">
<span style="background-color: white; font-family: Verdana, sans-serif; font-size: 12px;">Germany was a powder keg during the Weimar era. The NSDAP was successful in capturing seats in the Reichstag because the German citizenry were scared by the social unrest, were upset by the Treaty of Versailles, and Germans believed the Nazi Party would offer the ability to regain German pride, and restore order in the country. Counted among the citizens who voted for the party were many Jews. It wasn't until 1935 and the Nuremberg Race Laws were enacted did the Jewish population as a whole realize what was actually happening. The SA bullied Jews and the 1938 Kristallnacht cemented the future of what was to come in Germany. Still, German Jewish veterans believed that their association with Nationalism (and their heroic service during the Great War) would be considered and they wouldn't be victimized by Nazism and the Nuremberg Laws.&nbsp;</span><br style="font-family: Verdana, sans-serif; font-size: 12px;" /><span style="background-color: white; font-family: Verdana, sans-serif; font-size: 12px;">So many German Jews supported the NSDAP in the early days. And a number of full-blood Jews remained in the service of the Reich, holding positions in the Wehrmacht high-command, and other positions in government even in spite of the Nuremberg Laws. Mischlings (which literally translates to&nbsp;</span><i style="font-family: Verdana, sans-serif; font-size: 12px;">half-breed</i><span style="background-color: white; font-family: Verdana, sans-serif; font-size: 12px;">) often practiced aspects of Judaism as well as Roman Catholicism/Protestantism and were active in all forms during the Reich. The vast majority of German Mischlings were exempted from the Nuremberg laws and persecution. However, it would be remiss, and a complete distortion of historical fact not to explain that in the occupied regions of the Sudetenland, Annexed Austria, occupied Poland, Lithuania, Latvia, Hungary, and the Western Soviet Caucasus, Jews, regardless of religious affiliation and regardless of their status as Mischlings, were subject to the Holocaust. Non-Jewish spouses of Jews (Roman Catholics, etc.) in the occupied areas were viewed by the Reich as "Jewish", as were Mischlings of any percentage, and again subject to the Nazi pogroms. A distinction existed during this tumultuous time between German Jews and Mischlings as opposed to Jews and Mischlings of other nationalities. This was another example of the endemic sickness of German National Socialist policy.&nbsp;</span><span style="font-family: Verdana, sans-serif; font-size: 12px;"><br /></span><span style="font-family: Verdana, sans-serif; font-size: 12px;">Read more:&nbsp;<a href="http://wiki.answers.com/Q/Did_some_Jews_vote_for_Hitler#ixzz2QoLSKEFC" style="color: #003399; cursor: pointer; text-decoration: none;">http://wiki.answers.com/Q/Did_some_Jews_vote_for_Hitler#ixzz2QoLSKEFC</a></span></blockquote>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />