---
title: 'Erynn; the homeless'
date: '2013-01-20T06:39:00.0020000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'LIVE'
blogger_post_id: '3499887885165905324'
blogger_filename: '/2013/01/aaron-continues.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
categories:
  - 'Miles'
  - 'STORY'
  - 'Erynn'
---

<div class="tr_bq">
Erynn saw the guy rush off the bus and abondon his favorite seat. She got up and moved to the back of the bus and grab her favorite chair next to the window. She put her feet across the seats and leaned back against the window. She pulled her long coat over her legs and began to close her eyes for the multi hour round trip bus tour. It was the best sleep she'd found a way to get, it was too cold for a card board box.</div>
<br />
As she was trying to sleep she noticed a sound coming from behind and under her. She turned and found an iPod slipped down between the seat and the window. She put the ear buds in to see what it was playing. She heard a preacher and nearly put it down, but she thought that it'd been a few years since he'd heard a good sermon, figured she was over due and "besides, what better to put you to sleep than some boring preacher..."<br />
<blockquote class="tr_bq">
<i>...That's what the call to excellence is all about! It's not about what you can do FOR God. God has already done everything FOR you! It's about believing what He'd done for you and responding apropriately. It's abour responding to Him and His constant subtle call...</i></blockquote>
With that she was hooked... She didn't find sleep for the next 30 minutes as the message played on about this Call to Excellence.<br />
<blockquote>
<i>"...it's about doing what's right, because it's right, doing it right, and doing it right away. But this is also about response. It's not about religious obedience, or forcing yourself to do the right thing even though you want to do the opposite. In fact, walking away from sin wishing you didn't have to is no victory at all. It's when you can walk away from the World and walk into the things of God wanting to do so, desiring to do so, passionate about doing so. It's as though you become so full of God that the things of the world just simply loose their interest, until some of those things that held you bound for so long not only seem to have lost their luster, they begin to repulse you. It all happens without you having to drum something up or force it to happen. It happens as you fill yourself with Him. As you find yourself filling up with Him, you begin to act like Him, talk like Him, and do things things that He does.</i><i><br /></i><i>How will you put this into practice? Millions of people read their bible and pray everyday and are still full of worldly desires and are one disappointment away from throwing down their life to the sin they secretely long for, or a simple life of laziness. So how do we put this life of God to use in our lives? It grows as a seed. It starts small and grows. Like any new skill you might learn it begins with putting it to use. One man called it "Practicing the Presence of God". Decide right now that you will begin to yield to God. Instead of giving in to laziness give in to God. When you hear that still-small-voice of the Holy Spirit, no matter how silly or small it may seem, give in to it. "Pick up that peice of paper and throw it away", "Stay up with me for a little bit", "turn on some praise music and sing with/to me", "pray, right now." The small things will grow over time... Let's all stand..."</i></blockquote>
The music started and the message was over. Erynn had never heard talk like that. It certainly wasn't the messages she'd grown up with as a pastors kid. Then again when you live with a pastor like her Dad, you kind of loose interest in the whole church thing. Then again, maybe she'd thrown out the baby with the bathwater here. Maybe there was more to this God thing than she'd realized. Interesting thought for a self proclaimed agnostic. With that she gave in to sleep and passed out against the window.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />