---
title: 'Jeffery, Success isn''t everything'
date: '2013-01-24T04:47:00.0010000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'LIVE'
blogger_post_id: '5995784863272608604'
blogger_filename: '/2013/01/jeffery-success-isnt-everything.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
categories:
  - 'STORY'
  - 'Jeff'
---

<div class="tr_bq">
Jeff &nbsp;yawned and stretched as he passed into his living room on the way to the kitchen which was a long walk considering he'd built a 40,000 sq ft home. He still questioned the sanity of building the kitchen so far from the master bedroom but he reasoned at the time that he'd not likely want people over for gatherings snooping through his bedroom so it made sense at the time. Jeff picked up the mornings paper which had been placed for him next to his breakfast by his butler Geoffrey. Jeff still wasn't sure if he hired him for his qualifications, his cool English accent, or just for the fun of having another "Jeff" around the house. Sure, it was spelled different, but it was just as funny! The front page had his name in headlines, again.&nbsp;</div>
<blockquote>
<i><b>Jeffery Chaucer Lands Land Deal</b></i><i><br /></i><i>In a turn of recent events, Jeffery Chaucer, billionaire business tycoon, actor, author, etc. recently surprised everyone with news that he would be buying up land that had been thought of as waste land previously to build a new shopping center. The EPA along with Green Peace activists had been trying for years to get the land turned into dedicated natural habitat for endangered lizards unsuccessfully. Never-the-less they fought Jeffery vehemently in court. It was announced late last night that the deal was approved by the city and the judge turned down all other claims to the land. What remains planned for the land has been held close up to this time. Definite plans have not yet been revealed. The only notice so far was a mention of a shopping center. More definitive plans are expected soon as the court processes are now complete.&nbsp;</i></blockquote>
Unlike most of his actor and musician colleagues Jeffery invested his millions from entertainment and turned it into a multi-billion dollar portfolio, including houses, land, investment and rental properties, restaurants, a recording studio, and other ventures. He did it all so that he could do what he really loved, music. But now he made what he wanted, not what the studios asked him to make. He gave much of his time to up and coming musicians that showed promise and he'd take on the unlikelies as often as he could.<br />
<br />
After breakfast he got ready for Church. It was not your typical hollywood style church. In fact built his home near his Church so that he only had a ten minute drive every Sunday to get there. But when he showed up in his busienss casual dress he fit right in. Every so often someone would ask if he was who they thought he was, he'd say that he was and they'd act all star struck for awhile. But eventually his disarming smile and genuine character would put them at ease and he'd just be "one of the guys".<br />
<br />
He worked with the sound department running the board and every so often he'd help the music pastor with the band or choir. He seldom preformed himself though, not because he was too good for it, but because he didn't want church to become a show or make it about him. He also had great respect for the music pastor and didn't want to show him up in any way. So Jeff reserved his preformances for special occasions and special invitations. Another benefit to working the booth was that most people looked forward and not backward so he was almost invisible most of the time, which was a great releif to him as it happened so rarely in his life.<br />
<br />
Chaucer Estate was not built with 40,000 sq ft just make him feel like a big shot either. His home was mostly built as a staging area for church parties and working projects. It included his own private recording studio and preview theatre and as well as a music store sized instrument collection. As the sound checks were finalized and the service was nearly read to begin he found himself going over check lists on his iPad for the upcoming week. It was going to be a light load to maybe he'd find a few of his protoge's and work with them if he and they had time.<br />
<br />
...