---
title: 'Erynn the Homeless 2'
date: '2013-04-15T05:03:00.0000000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'LIVE'
blogger_post_id: '6696410174316507874'
blogger_filename: '/2013/04/erynn-homeless-2.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
categories:
  - 'STORY'
  - 'Erynn'
---

Sleeping on a bus wasn't that bad. It beat the benches, boxes, and other places she'd tried. It certainly beat the shelters. Compared to the shelters a bus was the safest place in the world. Ironically the bus drivers name was Warden, and he could handle anything. He took a shine to Jess. He may have been in his sixties, with salt and pepper&nbsp;reseeding&nbsp;hair. But the man had been through Vietnam and he could handle himself. He still worked out daily. He may as well have been a jail Warden, just the sound of his booming baritone would put shivers down your spine when he was serious, which he rarely had to be.<br />
<br />
Bus line 65 was his route. There was something different about Old Warden, that's for sure. There was no other bus that Jess would rather be on at night. He was there 5 nights a week to watch over her and the rest of the&nbsp;motley&nbsp;crew&nbsp;that usually showed up. She could never make it out, but when things got quite he talked to himself. It was real quite but it was almost another language of some kind. Maybe he'd picked it up in Vietnam?<br />
<br />
Night was over, and there are only two round trips allowed before he has to shuffle you off his route. Thank goodness his round trips take hours a&nbsp;piece, and they always ended at HWY 1 Pacific Coast Highway. Jess thanked Old Warden with a nod and hopped off. She grabbed her skateboard and backpack and rolled down the seaside walkway.<br />
<br />
Jess had moved out to Southern California from Betsmouth Montana. She never could adjust to the small town cowgirls lifestyle. So she headed to the beach to make a way for herself. After run inns with drug pushers, users, bad boyfriends, and eventually some jail time for DUI's she found herself here. No real friends, because they just meant trouble. No job, no place, no life... just existence. Jess was industrious though.<br />
<br />
She found a few restaurants that would let her work under the table cleaning and organizing. They gave her $10/Hr and all the food she could eat. But hey never had many hours. So she made her rounds 1st by what kind of food she wanted that day, and then by who was available. Today she was in luck! So Cal Burgers was available. They served the best salmon burger ever! Several of the places,&nbsp;including&nbsp;So Cal tried to hire her full time, she just couldn't bring herself to dedicate to one place. What if she lost that position and the other places weren't available anymore. No, she had a good thing and didn't want to mess it up.<br />
<br />
<br />