---
title: 'Define Excel'
date: '2014-07-15T04:32:00.0000000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'LIVE'
blogger_post_id: '2854486635088567917'
blogger_filename: '/2014/07/define-excel.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
categories:
  - 'Digesting'
---

<br />
<br />
<br />
Wiki defines <a href="http://en.wikipedia.org/wiki/Excellence" title="Excellence">Excellence</a>, the state or quality of excelling. <br />
<br />
<br />
<br />
<a href="http://1828.mshaffer.com/d/word/excel" target="_blank">Websters 1828 Dictionary:&nbsp;</a><br />
<br />
<b>EXCEL'</b>, v.t.  [L. excello, the root of which, cello, is not in use.<br />
<span><dd>1.  To go beyond; to exceed; to surpass in good qualities or laudable deeds; to outdo.</dd><dd><br /></dd><dd>Excelling others, these were great;</dd><dd><br /></dd><dd>Thou greater still, must these excel.</dd><dd><br /></dd><dd>Many daughters have done virtuously, but </dd><dd><br /></dd><dd>thou excellest them all.  Prov.31.</dd><dd>2.  To exceed or go beyond in bad qualities or deeds.</dd><dd>3.  To exceed; to surpass.<span style="background-color: yellow;"><b>EXCEL'</b>,
 v.i. To have good qualities, or to perform meritorious actions, in an 
unusual degree; to be eminent, illustrious or distinguished.</span></dd><dd><span style="background-color: yellow;"><br /></span></dd><dd><span style="background-color: yellow;">Bless the Lord, ye his angels, that <a href="http://biblehub.com/hebrew/1368.htm" target="_blank">excel </a>in strength.  Ps.103.</span></dd></span><br />
<br />
<br />
<a href="http://www.openbible.info/topics/excellence" target="_blank">34 Bible Verses about Excellence:</a><br />
<br />
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Daniel+6%3A3&amp;version=ESV">Daniel 6:3</a>
     <span class="note">
      ESV / 102 helpful votes     </span>
    </h3>
Then this Daniel became distinguished above all the other 
presidents and satraps, because an <b>excellent </b>spirit was in him. And the 
king planned to set him over the whole kingdom.    <br />

   
        <div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Philippians+4%3A8&amp;version=ESV">Philippians 4:8</a>
     <span class="note">
      ESV / 98 helpful votes     </span>
    </h3>
Finally, brothers, whatever is true, whatever is honorable, 
whatever is just, whatever is pure, whatever is lovely, whatever is 
commendable, if there is any <b>excellence</b>, if there is anything worthy of 
praise, think about these things.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Philippians+1%3A9-10&amp;version=ESV">Philippians 1:9-10</a>
     <span class="note">
      ESV / 63 helpful votes     </span>
    </h3>
And it is my prayer that your love may abound more and more, with 
knowledge and all discernment, so that you may approve what is <b>
excellent</b>, and so be pure and blameless for the day of Christ,    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Colossians+3%3A23&amp;version=ESV">Colossians 3:23</a>
     <span class="note">
      ESV / 46 helpful votes     </span>
    </h3>
Whatever you do, work heartily, as for the Lord and not for men,    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Daniel+5%3A12&amp;version=ESV">Daniel 5:12</a>
     <span class="note">
      ESV / 38 helpful votes     </span>
    </h3>
Because an <b>excellent </b>spirit, knowledge, and understanding to 
interpret dreams, explain riddles, and solve problems were found in this
 Daniel, whom the king named Belteshazzar. Now let Daniel be called, and
 he will show the interpretation.”    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=2+Peter+1%3A3-4&amp;version=ESV">2 Peter 1:3-4</a>
     <span class="note">
      ESV / 29 helpful votes     </span>
    </h3>
His divine power has granted to us all things that pertain to life 
and godliness, through the knowledge of him who called us to his own 
glory and excellence, by which he has granted to us his precious and 
very great promises, so that through them you may become partakers of 
the divine nature, having escaped from the corruption that is in the 
world because of sinful desire.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Ephesians+6%3A7-8&amp;version=ESV">Ephesians 6:7-8</a>
     <span class="note">
      ESV / 22 helpful votes     </span>
    </h3>
Rendering service with a good will as to the Lord and not to man, 
knowing that whatever good anyone does, this he will receive back from 
the Lord, whether he is a slave or free.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Titus+2%3A7&amp;version=ESV">Titus 2:7</a>
     <span class="note">
      ESV / 21 helpful votes     </span>
    </h3>
Show yourself in all respects to be a model of good works, and in your teaching show integrity, dignity,    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=2+Corinthians+8%3A7&amp;version=ESV">2 Corinthians 8:7</a>
     <span class="note">
      ESV / 15 helpful votes     </span>
    </h3>
But as you excel in everything—in faith, in speech, in knowledge, 
in all earnestness, and in our love for you—see that you excel in this 
act of grace also.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Joshua+1%3A8&amp;version=ESV">Joshua 1:8</a>
     <span class="note">
      ESV / 14 helpful votes     </span>
    </h3>
This Book of the Law shall not depart from your mouth, but you 
shall meditate on it day and night, so that you may be careful to do 
according to all that is written in it. For then you will make your way 
prosperous, and then you will have good success.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Isaiah+12%3A1-6&amp;version=ESV">Isaiah 12:1-6</a>
     <span class="note">
      ESV / 10 helpful votes     </span>
    </h3>
You will say in that day: “I will give thanks to you, O <span class="sc">Lord</span>,
 for though you were angry with me, your anger turned away, that you 
might comfort me. “Behold, God is my salvation; I will trust, and will 
not be afraid; for the <span class="sc">Lord</span> <span class="sc">God</span>
 is my strength and my song, and he has become my salvation.” With joy 
you will draw water from the wells of salvation. And you will say in 
that day: “Give thanks to the <span class="sc">Lord</span>, call upon his name, make known his deeds among the peoples, proclaim that his name is exalted. “Sing praises to the <span class="sc">Lord</span>, for he has done gloriously; let this be made known in all the earth.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Psalm+119%3A99&amp;version=ESV">Psalm 119:99</a>
     <span class="note">
      ESV / 10 helpful votes     </span>
    </h3>
I have more understanding than all my teachers, for your testimonies are my meditation.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=2+Timothy+3%3A16&amp;version=ESV">2 Timothy 3:16</a>
     <span class="note">
      ESV / 8 helpful votes     </span>
    </h3>
All Scripture is breathed out by God and profitable for teaching, 
for reproof, for correction, and for training in righteousness,    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=1+Timothy+6%3A11&amp;version=ESV">1 Timothy 6:11</a>
     <span class="note">
      ESV / 8 helpful votes     </span>
    </h3>
But as for you, O man of God, flee these things. Pursue 
righteousness, godliness, faith, love, steadfastness, gentleness.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Isaiah+40%3A6-8&amp;version=ESV">Isaiah 40:6-8</a>
     <span class="note">
      ESV / 8 helpful votes     </span>
    </h3>
A voice says, “Cry!” And I said, “What shall I cry?” All flesh is 
grass, and all its beauty is like the flower of the field. The grass 
withers, the flower fades when the breath of the <span class="sc">Lord</span> blows on it; surely the people are grass. The grass withers, the flower fades, but the word of our God will stand forever.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Proverbs+17%3A27&amp;version=ESV">Proverbs 17:27</a>
     <span class="note">
      ESV / 7 helpful votes     </span>
    </h3>
Whoever restrains his words has knowledge, and he who has a cool spirit is a man of understanding.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Psalm+36%3A7&amp;version=ESV">Psalm 36:7</a>
     <span class="note">
      ESV / 7 helpful votes     </span>
    </h3>
How precious is your steadfast love, O God! The children of mankind take refuge in the shadow of your wings.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=1+Thessalonians+2%3A13&amp;version=ESV">1 Thessalonians 2:13</a>
     <span class="note">
      ESV / 6 helpful votes     </span>
    </h3>
And we also thank God constantly for this, that when you received 
the word of God, which you heard from us, you accepted it not as the 
word of men but as what it really is, the word of God, which is at work 
in you believers.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=1+Peter+2%3A1&amp;version=ESV">1 Peter 2:1</a>
     <span class="note">
      ESV / 5 helpful votes     </span>
    </h3>
So put away all malice and all deceit and hypocrisy and envy and all slander.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=James+1%3A1-27&amp;version=ESV">James 1:1-27</a>
     <span class="note">
      ESV / 5 helpful votes     </span>
    </h3>
James, a servant of God and of the Lord Jesus Christ, To the twelve
 tribes in the Dispersion: Greetings. Count it all joy, my brothers, 
when you meet trials of various kinds, for you know that the testing of 
your faith produces steadfastness. And let steadfastness have its full 
effect, that you may be perfect and complete, lacking in nothing. If any
 of you lacks wisdom, let him ask God, who gives generously to all 
without reproach, and it will be given him.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Proverbs+10%3A7&amp;version=ESV">Proverbs 10:7</a>
     <span class="note">
      ESV / 5 helpful votes     </span>
    </h3>
The memory of the righteous is a blessing, but the name of the wicked will rot.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=1+John+2%3A1-29&amp;version=ESV">1 John 2:1-29</a>
     <span class="note">
      ESV / 4 helpful votes     </span>
    </h3>
My little children, I am writing these things to you so that you 
may not sin. But if anyone does sin, we have an advocate with the 
Father, Jesus Christ the righteous. He is the propitiation for our sins,
 and not for ours only but also for the sins of the whole world. And by 
this we know that we have come to know him, if we keep his commandments.
 Whoever says “I know him” but does not keep his commandments is a liar,
 and the truth is not in him, but whoever keeps his word, in him truly 
the love of God is perfected. By this we may know that we are in him:   
 <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=2+Peter+1%3A9&amp;version=ESV">2 Peter 1:9</a>
     <span class="note">
      ESV / 4 helpful votes     </span>
    </h3>
For whoever lacks these qualities is so nearsighted that he is 
blind, having forgotten that he was cleansed from his former sins.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=2+Thessalonians+1%3A1-12&amp;version=ESV">2 Thessalonians 1:1-12</a>
     <span class="note">
      ESV / 4 helpful votes     </span>
    </h3>
Paul, Silvanus, and Timothy, To the church of the Thessalonians in 
God our Father and the Lord Jesus Christ: Grace to you and peace from 
God our Father and the Lord Jesus Christ. We ought always to give thanks
 to God for you, brothers, as is right, because your faith is growing 
abundantly, and the love of every one of you for one another is 
increasing. Therefore we ourselves boast about you in the churches of 
God for your steadfastness and faith in all your persecutions and in the
 afflictions that you are enduring. This is evidence of the righteous 
judgment of God, that you may be considered worthy of the kingdom of 
God, for which you are also suffering—    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Romans+5%3A12&amp;version=ESV">Romans 5:12</a>
     <span class="note">
      ESV / 4 helpful votes     </span>
    </h3>
Therefore, just as sin came into the world through one man, and 
death through sin, and so death spread to all men because all sinned—   
 <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Proverbs+25%3A13&amp;version=ESV">Proverbs 25:13</a>
     <span class="note">
      ESV / 4 helpful votes     </span>
    </h3>
Like the cold of snow in the time of harvest is a faithful 
messenger to those who send him; he refreshes the soul of his masters.  
  <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Psalm+17%3A15&amp;version=ESV">Psalm 17:15</a>
     <span class="note">
      ESV / 4 helpful votes     </span>
    </h3>
As for me, I shall behold your face in righteousness; when I awake, I shall be satisfied with your likeness.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=2+Kings+1%3A1-18&amp;version=ESV">2 Kings 1:1-18</a>
     <span class="note">
      ESV / 4 helpful votes     </span>
    </h3>
After the death of Ahab, Moab rebelled against Israel. Now Ahaziah 
fell through the lattice in his upper chamber in Samaria, and lay sick; 
so he sent messengers, telling them, “Go, inquire of Baal-zebub, the god
 of Ekron, whether I shall recover from this sickness.” But the angel of
 the <span class="sc">Lord</span> said to Elijah the Tishbite, “Arise, 
go up to meet the messengers of the king of Samaria, and say to them, 
‘Is it because there is no God in Israel that you are going to inquire 
of Baal-zebub, the god of Ekron? Now therefore thus says the <span class="sc">Lord</span>,
 You shall not come down from the bed to which you have gone up, but you
 shall surely die.’” So Elijah went. The messengers returned to the 
king, and he said to them, “Why have you returned?”    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Ruth+1%3A1-22&amp;version=ESV">Ruth 1:1-22</a>
     <span class="note">
      ESV / 4 helpful votes     </span>
    </h3>
In the days when the judges ruled there was a famine in the land, 
and a man of Bethlehem in Judah went to sojourn in the country of Moab, 
he and his wife and his two sons. The name of the man was Elimelech and 
the name of his wife Naomi, and the names of his two sons were Mahlon 
and Chilion. They were Ephrathites from Bethlehem in Judah. They went 
into the country of Moab and remained there. But Elimelech, the husband 
of Naomi, died, and she was left with her two sons. These took Moabite 
wives; the name of the one was Orpah and the name of the other Ruth. 
They lived there about ten years, and both Mahlon and Chilion died, so 
that the woman was left without her two sons and her husband.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Genesis+1%3A1-31&amp;version=ESV">Genesis 1:1-31</a>
     <span class="note">
      ESV / 4 helpful votes     </span>
    </h3>
In the beginning, God created the heavens and the earth. The earth 
was without form and void, and darkness was over the face of the deep. 
And the Spirit of God was hovering over the face of the waters. And God 
said, “Let there be light,” and there was light. And God saw that the 
light was good. And God separated the light from the darkness. God 
called the light Day, and the darkness he called Night. And there was 
evening and there was morning, the first day.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=1+John+3%3A2&amp;version=ESV">1 John 3:2</a>
     <span class="note">
      ESV / 3 helpful votes     </span>
    </h3>
Beloved, we are God's children now, and what we will be has not yet
 appeared; but we know that when he appears we shall be like him, 
because we shall see him as he is.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Isaiah+1%3A1-31&amp;version=ESV">Isaiah 1:1-31</a>
     <span class="note">
      ESV / 3 helpful votes     </span>
    </h3>
The vision of Isaiah the son of Amoz, which he saw concerning Judah
 and Jerusalem in the days of Uzziah, Jotham, Ahaz, and Hezekiah, kings 
of Judah. Hear, O heavens, and give ear, O earth; for the <span class="sc">Lord</span>
 has spoken: “Children have I reared and brought up, but they have 
rebelled against me. The ox knows its owner, and the donkey its master's
 crib, but Israel does not know, my people do not understand.” Ah, 
sinful nation, a people laden with iniquity, offspring of evildoers, 
children who deal corruptly! They have forsaken the <span class="sc">Lord</span>,
 they have despised the Holy One of Israel, they are utterly estranged. 
Why will you still be struck down? Why will you continue to rebel? The 
whole head is sick, and the whole heart faint.    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=1+Chronicles+4%3A9&amp;version=ESV">1 Chronicles 4:9</a>
     <span class="note">
      ESV / 3 helpful votes     </span>
    </h3>
Jabez was more honorable than his brothers; and his mother called his name Jabez, saying, “Because I bore him in pain.”    <br />

   </div>
<div class="verse">
    <div class="vote-buttons invisible">
     <span></span>
    </div>
<h3>
     <a class="bibleref" href="http://www.biblegateway.com/passage/?search=Ephesians+2%3A1-3&amp;version=ESV">Ephesians 2:1-3</a>
     <span class="note">
      ESV / 2 helpful votes     </span>
    </h3>
And you were dead in the trespasses and sins in which you once 
walked, following the course of this world, following the prince of the 
power of the air, the spirit that is now at work in the sons of 
disobedience— among whom we all once lived in the passions of our flesh,
 carrying out the desires of the body and the mind, and were by nature 
children of wrath, like the rest of mankind.    <br />

   </div>
