---
title: 'Call To Excellence:“Challenging Christians in the United States of America to a Life of Excellence”'
date: '2014-07-15T04:59:00.0000000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'LIVE'
blogger_post_id: '266946067218374651'
blogger_filename: '/2014/07/call-to-excellencechallenging.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
---

<i>*Boiling down a power point into it's most essential elements and highlights. Take it apart, digest it, and put it back together. </i><br />
<h3>
A Call To Excellence</h3>
<br />
<h4>
“Challenging Christians in the United States of America to a Life of Excellence”</h4>
<blockquote class="tr_bq">
<i><br /></i>
<a href="http://www.biblestudytools.com/nkjv/2-chronicles/7-14.html" target="_blank"><i>2 Chronicles 7:14&nbsp;</i></a><br />
<i>If My people who are called by My name will humble themselves, and pray and seek My face, and turn from their wicked ways, then I will hear from heaven, and will forgive their sin and heal their land. 
</i><br />
<i><br /></i>
<a href="http://www.biblestudytools.com/nkjv/proverbs/16-7.html" target="_blank"><i>Proverbs 16:7&nbsp;</i></a><br />
<i>When a man's ways please the Lord, He makes even his enemies to be at peace with him. 
</i><br />
<i><br /></i>
<i><a href="https://www.biblegateway.com/passage/?search=Matthew+5%3A48&amp;version=AMP" target="_blank">Matthew 5:48 (Amplified)</a>
</i><br />
<i>You, therefore, must be perfect [growing into complete [a]maturity of godliness in mind and character, [b]having reached the proper height of virtue and integrity], as your heavenly Father is perfect.
</i></blockquote>
<br />
<h4>
The Concern:</h4>
<br />
The USA has abandoned her first love, and gone after strange idols.<br />
<br />
<h4>
Something must be done:</h4>
<br />
There is an overwhelming need for the body of Christ, the Church, to start acting like a body. To be united under one banner: "His banner over me is love". Awakening to Excellence in Love.<br />
<br />
The time has come for the Church to awaken to that which has already been done in us.&nbsp; <br />
<blockquote class="tr_bq">
<i><a href="http://www.biblestudytools.com/nkjv/romans/passage.aspx?q=romans+8:18-27" target="_blank">Romans 8:18-27</a></i><br />
<i>19 For the earnest expectation of the creation eagerly waits for the revealing of the sons of God. 20 For the creation was subjected to futility, not willingly, but because of Him who subjected it in hope; 21 because the creation itself also will be delivered from the bondage of corruption into the glorious liberty of the children of God. 22 For we know that the whole creation groans and labors with birth pangs together until now. 23 Not only that, but we also who have the firstfruits of the Spirit, even we ourselves groan within ourselves, eagerly waiting for the adoption, the redemption of our body.
</i></blockquote>
<br />
<h4>
The Real War</h4>
<br />
The real war isn't again men, it's against spiritual darkness.<br />
<br />
Matthew 11:12<br />
Matthew 16:18<br />
Matthew 22:37-39<br />
Ephesians 6:12<br />
<br />
<h4>
The USA</h4>
<br />
"Those people who will not be governed by God will be ruled by tyrants!" William Penn<br />
<br />
<h4>
The State and Decay of the Church</h4>
<br />
Immorality, Abortion, Pornography, Divorce, Falsehood... are all prevalent in the Church today. Trading truth for political correctness.<br />
<br />
Meanwhile, infighting, world view wars, religious traditions further weaken the body like cancer... modern day pharasees.<br />
<br />
<h4>
Who is this message for:</h4>
<br />
Me<br />
You<br />
Us<br />
Christian Business Owners<br />
Christian Organizations<br />
Christian Schools<br />
Churches<br />
<br />
<br />
<br />
<h4>
The Solution:</h4>
Allow Jesus to be our common denominator: Leave the rest for God to Judge.<br />
<br />
All relying on the Holy Spirit for guidance, asking God about the direction of their lives before they make a move.<br />
<br />
Christian's speaking with one voice, one message, one Love.<br />
<br />
<br />
<br />
<br />
<h4>
Passion:&nbsp;</h4>
<br />
An educated, life changing, decision that something is worth everything.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />