---
title: 'Excellence'
date: '2014-11-03T16:00:00.0000000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'LIVE'
blogger_post_id: '7170007089029581813'
blogger_filename: '/2014/11/excellence.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
---

<div class="WordSection1">  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">Excel: Go above and beyond the normal, usual, or expected.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">Compassion: To be moved to action by the needs, wants, and/or desires of another.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">Excellence: To place God&#8217;s priorities above and beyond your own, to be moved with His needs, wants, and/or desires.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">Examples of Excellence:<o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">To leave the world around you in a better condition than it was when you came into it.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">To pick up the towel on the floor in the restroom, even though you didn&#8217;t put it there, because someone will have to pick it up, why not you? Leave the bathroom in a better condition   that the way you found it. <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">Stay up late when you&#8217;d rather go to bed, because they need someone to listen.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">Go to bed, when you&#8217;d rather stay up late, because you want to be a good steward of the time you have, and be totally prepared for tomorrow.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">Don&#8217;t buy that, even though you crave it, because it&#8217;s not your money, it&#8217;s God&#8217;s, and He has plans for that.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">Give, even when you don&#8217;t feel you can, because you know He&#8217;s leading you to give to that, right now, and He is your provider.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">See the world in a larger frame. Me &gt; Us&gt; Them &gt; HIM &gt; Them &gt; Us &gt; Me<o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">The one who is moved with compassion, but not excellence, will seek to meet the needs of other in their own power, and burn out.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">The one who is moved with excellence, but not compassion, will be driven to achieve but focused on self.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">One must be moved by compassionate excellence (or excellent compassion) in order to be effective in God&#8217;s plan.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  </div>  