---
title: 'Call to Excellence:'
date: '2020-10-02T02:48:00.0000000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'LIVE'
blogger_post_id: '8049525987811953080'
blogger_filename: '/2012/10/call-to-excellence.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
categories:
  - 'The Call'
---

<br />
<h2>
Call to Excellence:</h2>
<ul><ul><ul>
</ul>
</ul>
<li><a href="http://calltoexcellence.blogspot.com/2012/10/the-concern.html" target="_blank">The Concern</a></li>
<ul>
<li>The United States of America must consider it's:</li>
<ul>
<li>History:</li>
<ul>
<li><a href="http://calltoexcellence.blogspot.com/2012/09/church-history-101-glorious-church.html" target="_blank">Church History 101- The Glorious Church</a></li>
<li><a href="http://calltoexcellence.blogspot.com/2012/09/us-history-101-americas-new-civil-war.html" target="_blank">USA History 101 -America's New Civil War</a></li>
<li><a href="http://calltoexcellence.blogspot.com/2012/09/world-views-101.html" target="_blank">World Views 101</a></li>
</ul>
<li>Actions</li>
<ul>
<li>World View of America</li>
<li>World View of Christian Church</li>
</ul>
</ul>
</ul>
<ul>
<li>Something MUST be done</li>
<li>Something must be done NOW</li>
<li>The Real War - Love, Spirit, Prayer?</li>
</ul>
<li>The Purpose</li>
<ul>
<li>Focus: What we are to return to and become:</li>
<ul>
<li>God's People in the USA</li>
<li>World SEEING Jesus lived through us</li>
</ul>
</ul>
<li>The Solution</li>
<ul>
<li>Principle</li>
<ul>
<li>Seek God</li>
<li>Love People - It must be done in LOVE</li>
<li>Seek Common Ground - Where possible</li>
</ul>
<li>Structure</li>
<ul>
<li>One Voice and One Message</li>
<li>Individuals and Families</li>
<li>Local Churches and Organizations</li>
<li>National Organizations and Schools</li>
<li>Businesses and Business Leaders</li>
</ul>
</ul>
</ul>
<div>
<br /></div>
<div>
<h3>
Summary:</h3>
</div>
<div>
<br /></div>
<div>
The greatest nation in the world was born out of a desire to govern and worship as free men. With a divine destiny to serve the world as a haven of rest, opportunity, and a brighter life.<br />
<br />
Offering help to the oppressed, comfort to the homeless and food to the hungry. The USA was born out of the heart of God; a city set on a hill with a light shining bright in a dark world.<br />
<br />
God's representation has always been his people by men and women set apart to lead. We are these men and women of God in the earth today. Leading an army of believers in challenging God's people to Excellence in the spiritual war of the ages.<br />
<br />
"May God Bless You and May God Bless America"</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
Respectfully Jack Ernest Fort Worth, Texas<br />
<a href="mailto:jernest2@aol.com">jernest2@aol.com</a>&nbsp;2011</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
</div>
