---
title: 'Call to Excellence: Expounded and Expanded'
date: '2020-10-04T04:50:00.0000000+00:00'
draft: true
blogger_blog: 'Call To Excellence'
blogger_status: 'LIVE'
blogger_post_id: '2638450463637376139'
blogger_filename: '/2012/10/call-to-excellence-expounded-and.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Call To Excellence/feed.atom'
---

<br />
<h2>
Call to Excellence:</h2>
<h3 style="text-align: center;">
<a href="http://calltoexcellence.blogspot.com/2012/10/the-concern.html" target="_blank">The Concern</a><ul>
</ul>
</h3>
<ul><ul></ul>
<ul>
<li><b>The USA has fallen</b></li>
<ul>
<li>Officially and Legally changed it's national&nbsp;commitment&nbsp;to Jesus. We've broken&nbsp;covenant&nbsp;with the one who established us.&nbsp;</li>
<li>Special Interest Groups, motivated and spurred by pure evil, are changing our nation into their image, and after their likeness, in many cases actually re-writing history to make it say the opposite of what it says.&nbsp;</li>
<li>The Church, just as Adam in the Garden, has given up her rights and turned them over to the devil. We have disengaged the battle and allowed Satan to walk all over us. Churches are now finding new generations believing lies of our society instead of standing boldly for the truth of God's word.&nbsp;</li>
</ul>
<li><b>Something MUST be done</b></li>
<ul>
<li>The Church must wake up. Realize that she has fallen asleep and is under attack.</li>
<li>We have been so busy fighting internal holy wars of doctrine that we have retreated into our Church walls and allowed the world to go to hell. We are the salt and light. It is OUR responsibility to be that salt and light until the day of Jesus' return.&nbsp;</li>
<li>There must be a rally call, bringing people from all backgrounds, doctrines, and creeds to walk together in Excellence of Love. One Voice, One Message, One Body</li>
</ul>
<li><b>Something must be done NOW</b></li>
<ul>
<li>Romans 8:<i>22 For we know that the whole creation groans and labors with birth pangs&nbsp;<b>together until now</b>.</i></li>
<li>The time grows short. The United States has fallen into Enemy hands. We must take it back. The time for the last Great Awakening has come. The world wide harvest will start here in the USA and will grow and grow until the day of Jesus' return. Pray the Lord of the Harvest to send workers into HIS field! (<a href="http://bible.cc/matthew/9-38.htm" target="_blank">Matt 9:38</a>)</li>
</ul>
</ul>
</ul>
<ul><ul>
<li><b>The Real War - Love, Spirit, Prayer?</b></li>
<ul>
<li>Our battle is not with people. Planned Parenthood is not our enemy. Satan is our enemy. Satan is behind Planned Parenthood and other anti-God Special Interest groups. Our battle must be fought in the spiritual realm first, before we can take natural action.&nbsp;</li>
<li><b>Repentance</b></li>
<ul>
<li>The Church must repent for it's absence from society and failure to Love as Jesus Loved!</li>
<li>The Nation must repent for it's rejection of God and His ways. National leaders, spiritual, political, etc must rise and call for national repentance.&nbsp;</li>
</ul>
<li><b>LOVE</b></li>
<ul>
<li>Churches from different doctrines must work together to accomplish these things. We cannot allow ourselves to be so distracted with doctrines that we fail to LOVE each other and LOVE the world.&nbsp;</li>
<ul>
<li>We need not compromise our firmly held beliefs in order to LOVE ONE ANOTHER and work together to love a dying world. We can agree to disagree on some things, as long as we find our common denominator.&nbsp;</li>
</ul>
</ul>
</ul>
<li><b>The United States of America must consider it's:</b></li>
<ul>
<li><b>History:</b></li>
<ul>
<li><a href="http://calltoexcellence.blogspot.com/2012/09/church-history-101-glorious-church.html" target="_blank">Church History 101- The Glorious Church</a></li>
<li><a href="http://calltoexcellence.blogspot.com/2012/09/us-history-101-americas-new-civil-war.html" target="_blank">USA History 101 -America's New Civil War</a></li>
<li><a href="http://calltoexcellence.blogspot.com/2012/09/world-views-101.html" target="_blank">World Views 101</a></li>
</ul>
<li><b>Actions</b></li>
<ul>
<li><b>"Those people who will not be governed by God will by ruled by Tyrants!" </b><a href="http://en.wikipedia.org/wiki/William_Penn" target="_blank">William Penn</a>&nbsp;(Founder of PA and author of works that would later inspire the Constitution of the USA. In fact the very term "United States of America" came from his writings.&nbsp;</li>
<li>World View of America</li>
<ul>
<li>This Christian Nation now embraces: Abortion, Sexual Immoralities, and Other evils. We toss aside the sanctity of Marriage and Family. We have over paid celebraties who revil in their evil behaviors and under paid teachers and doers of good. We embrace political correctness (which is usually embracing some new evil behavior we are told to accept) and allow minority leaders to fan the flames of racial division. Only in God can race no longer define a man, and only in Churches where Love is King do we cease to see race at all.&nbsp;</li>
</ul>
<li>World View of Christian Church</li>
<ul>
<li>We are divided and fighting in holy wars. Accepting of traditional immoralities, seeking&nbsp;celebrities&nbsp;and marketing gurus to grow the Church instead of seeking God's Word and Ways.</li>
</ul>
</ul>
</ul>
</ul>
<ul>
<li><br /></li>
</ul>
</ul>
<h3 style="text-align: center;">
<b>The Purpose</b><ul>
</ul>
</h3>
<ul>
<ul>
<li><b>Focus</b>: What we are to return to and become:</li>
<ul>
<li>God's People in the USA</li>
<ul>
<li>We are Individuals, Families, Churches, Organizations, Businesses and Leaders...&nbsp;</li>
</ul>
<li>World SEEING Jesus lived through us</li>
<ul>
<li>Demonstrated in LOVE. By loving one another, they will see we are His disciples. &nbsp;(<a href="http://bible.cc/john/13-35.htm" target="_blank">John 13:35</a>)</li>
</ul>
<li>A Nation Seeking God for Guidance, Political Leaders seeking God, openly, for guidance.</li>
<li>Christians&nbsp;seeking God and the Holy Spirit for Guidance</li>
<li>Government seeking God and the Holy Spirit for Guidance</li>
<li>Businesses&nbsp;seeking God and the Holy Spirit for Guidance</li>
<li>The USA returning, officially and legally, to it's biblical roots and heritage.</li>
<li>The USA leading the World by it's actions in Excellence of LOVE.&nbsp;</li>
</ul>
</ul>
</ul>
<h3 style="text-align: center;">
<b>The Solution</b><ul>
</ul>
</h3>
<ul>
<ul>
<li><b>Principles</b></li>
<ul>
<li>Repent and Seek God</li>
<li>Love People - It must be done in LOVE</li>
<ul>
<li>Set aside judgment. People are not our enemy. Start loving people, more than fighting them.&nbsp;</li>
<li>Yes we must stand up to organizations of evil, like Planned Parenthood, but if we spent our time, money, and attention on providing the things women needed (WOMEN OUTSIDE THE CHURCH) we could de-fund planned parenthood by providing the REAL solutions. Instead of yelling at them for providing a lie, we could simply provide the truth and they would&nbsp;disappear&nbsp; like a shadow in the presence of light!&nbsp;</li>
</ul>
<li>Seek Common Ground - Where possible</li>
<ul>
<li>When Jesus is the common denominator we can work together to get the job done.&nbsp;</li>
</ul>
</ul>
<li><b>Structure</b></li>
<h4>
<ul>
<li>One Voice and One Message</li>
</ul>
<ul><ul>
<li>New Organizations being formed and Existing&nbsp;Organizations&nbsp;joining forces to find common ground, agreement, and partnership; so that the Body of Christ may act and move as ONE BODY under ONE LORD.&nbsp;</li>
</ul>
</ul>
</h4>
<ul>
<li>Individuals and Families</li>
<ul>
<li>Taking time to pray, reach out, vote, etc</li>
</ul>
<li>Local Churches and Organizations</li>
<ul>
<li>Working together to take a city. Creating joint programs, pooling talent and resources and ideas. Taking food to the hungry, education to those in need, tutoring, activities for youth and after school programs, educating people on money, history, family, etc... taking REAL action, not just teaching.&nbsp;</li>
</ul>
<li>National Organizations and Schools</li>
<ul>
<li>Pooling together to provide educational resources to the world around them, to churches, to leaders... speaking as one. There need not be any competition in or between Christian Universities.&nbsp;</li>
</ul>
<li>Businesses and Business Leaders</li>
<ul>
<li>The head of <a href="https://www.facebook.com/events/266281243473841/" target="_blank">Chick fil a</a> was only the&nbsp;beginning&nbsp; There are leaders who must rise, corporate leaders, who must stand for righteousness at any cost! They must use their influence and money to steer elections and policies. They must reach out to the&nbsp;community&nbsp;and do something for Jesus, not just for a tax return or publicity, but because it's right and good.&nbsp;</li>
</ul>
</ul>
</ul>
</ul>
<div>
<br /></div>
<div>
<h3>
Summary:</h3>
</div>
<div>
<br /></div>
<div>
The greatest nation in the world was born out of a desire to govern and worship as free men. With a divine destiny to serve the world as a haven of rest, opportunity, and a brighter life.<br />
<br />
Offering help to the oppressed, comfort to the homeless and food to the hungry. The USA was born out of the heart of God; a city set on a hill with a light shining bright in a dark world.<br />
<br />
God's representation has always been his people by men and women set apart to lead. We are these men and women of God in the earth today. Leading an army of believers in challenging God's people to Excellence in the spiritual war of the ages.<br />
<br />
"May God Bless You and May God Bless America"</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
Respectfully Jack Ernest Fort Worth, Texas<br />
<a href="mailto:jernest2@aol.com">jernest2@aol.com</a>&nbsp;2011</div>
<div>
<br /></div>
<div>
</div>
