---
title: 'Bible Versus on Politics'
date: '2012-11-18T15:51:00.0020000+00:00'
draft: true
blogger_blog: 'Wolfe for Office'
blogger_status: 'DRAFT'
blogger_post_id: '8455848398966036589'
blogger_filename: '/2012/11/bible-versus-on-politics.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Wolfe for Office/feed.atom'
categories:
  - 'Bible'
---

I have had more than one debate over what the bible has to say about political decisions this year. The fact is that the Bible has MUCH to say about all matters of life. In my search see what was already being said I found this helpful page of verses.<br />
<br />
<a href="http://www.openbible.info/topics/politics" target="_blank">http://www.openbible.info/topics/politics&nbsp;</a><br />
<br />
<br />
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Romans+13%3A1-7&amp;version=ESV">Romans 13:1-7</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 130 helpful votes</span></h3>
<div style="margin-top: -1em;">
Let every person be subject to the governing authorities. For there is no authority except from God, and those that exist have been instituted by God. Therefore whoever resists the authorities resists what God has appointed, and those who resist will incur judgment. For rulers are not a terror to good conduct, but to bad. Would you have no fear of the one who is in authority? Then do what is good, and you will receive his approval, for he is God's servant for your good. But if you do wrong, be afraid, for he does not bear the sword in vain. For he is the servant of God, an avenger who carries out God's wrath on the wrongdoer. Therefore one must be in subjection, not only to avoid God's wrath but also for the sake of conscience. ...</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_54002001-54002002" name="vote_u_54002001-54002002" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_54002001-54002002" name="vote_d_54002001-54002002" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=1+Timothy+2%3A1-2&amp;version=ESV">1 Timothy 2:1-2</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 97 helpful votes</span></h3>
<div style="margin-top: -1em;">
First of all, then, I urge that supplications, prayers, intercessions, and thanksgivings be made for all people, for kings and all who are in high positions, that we may lead a peaceful and quiet life, godly and dignified in every way.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_52004011-52004012" name="vote_u_52004011-52004012" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_52004011-52004012" name="vote_d_52004011-52004012" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=1+Thessalonians+4%3A11-12&amp;version=ESV">1 Thessalonians 4:11-12</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 44 helpful votes</span></h3>
<div style="margin-top: -1em;">
And to aspire to live quietly, and to mind your own affairs, and to work with your hands, as we instructed you, so that you may walk properly before outsiders and be dependent on no one.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_40022017-40022021" name="vote_u_40022017-40022021" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_40022017-40022021" name="vote_d_40022017-40022021" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Matthew+22%3A17-21&amp;version=ESV">Matthew 22:17-21</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 43 helpful votes</span></h3>
<div style="margin-top: -1em;">
Tell us, then, what you think. Is it lawful to pay taxes to Caesar, or not?” But Jesus, aware of their malice, said, “Why put me to the test, you hypocrites? Show me the coin for the tax.” And they brought him a denarius. And Jesus said to them, “Whose likeness and inscription is this?” They said, “Caesar's.” Then he said to them, “Therefore render to Caesar the things that are Caesar's, and to God the things that are God's.”</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_19033012" name="vote_u_19033012" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_19033012" name="vote_d_19033012" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Psalm+33%3A12&amp;version=ESV">Psalm 33:12</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 37 helpful votes</span></h3>
<div style="margin-top: -1em;">
Blessed is the nation whose God is the&nbsp;<span class="sc">Lord</span>, the people whom he has chosen as his heritage!</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_40006024" name="vote_u_40006024" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_40006024" name="vote_d_40006024" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Matthew+6%3A24&amp;version=ESV">Matthew 6:24</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 34 helpful votes</span></h3>
<div style="margin-top: -1em;">
“No one can serve two masters, for either he will hate the one and love the other, or he will be devoted to the one and despise the other. You cannot serve God and money.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_40028018" name="vote_u_40028018" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_40028018" name="vote_d_40028018" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Matthew+28%3A18&amp;version=ESV">Matthew 28:18</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 32 helpful votes</span></h3>
<div style="margin-top: -1em;">
And Jesus came and said to them, “All authority in heaven and on earth has been given to me.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_05015007-05015011" name="vote_u_05015007-05015011" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_05015007-05015011" name="vote_d_05015007-05015011" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Deuteronomy+15%3A7-11&amp;version=ESV">Deuteronomy 15:7-11</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 32 helpful votes</span></h3>
<div style="margin-top: -1em;">
“If among you, one of your brothers should become poor, in any of your towns within your land that the&nbsp;<span class="sc">Lord</span>&nbsp;your God is giving you, you shall not harden your heart or shut your hand against your poor brother, but you shall open your hand to him and lend him sufficient for his need, whatever it may be. Take care lest there be an unworthy thought in your heart and you say, ‘The seventh year, the year of release is near,’ and your eye look grudgingly on your poor brother, and you give him nothing, and he cry to the&nbsp;<span class="sc">Lord</span>&nbsp;against you, and you be guilty of sin. You shall give to him freely, and your heart shall not be grudging when you give to him, because for this the&nbsp;<span class="sc">Lord</span>&nbsp;your God will bless you in all your work and in all that you undertake. For there will never cease to be poor in the land. Therefore I command you, ‘You shall open wide your hand to your brother, to the needy and to the poor, in your land.’</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_05017014-05017015" name="vote_u_05017014-05017015" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_05017014-05017015" name="vote_d_05017014-05017015" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Deuteronomy+17%3A14-15&amp;version=ESV">Deuteronomy 17:14-15</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 24 helpful votes</span></h3>
<div style="margin-top: -1em;">
“When you come to the land that the&nbsp;<span class="sc">Lord</span>&nbsp;your God is giving you, and you possess it and dwell in it and then say, ‘I will set a king over me, like all the nations that are around me,’ you may indeed set a king over you whom the&nbsp;<span class="sc">Lord</span>&nbsp;your God will choose. One from among your brothers you shall set as king over you. You may not put a foreigner over you, who is not your brother.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_44005029" name="vote_u_44005029" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_44005029" name="vote_d_44005029" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Acts+5%3A29&amp;version=ESV">Acts 5:29</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 17 helpful votes</span></h3>
<div style="margin-top: -1em;">
But Peter and the apostles answered, “We must obey God rather than men.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_50003020" name="vote_u_50003020" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_50003020" name="vote_d_50003020" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Philippians+3%3A20&amp;version=ESV">Philippians 3:20</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 16 helpful votes</span></h3>
<div style="margin-top: -1em;">
But our citizenship is in heaven, and from it we await a Savior, the Lord Jesus Christ,</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_60002017" name="vote_u_60002017" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_60002017" name="vote_d_60002017" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=1+Peter+2%3A17&amp;version=ESV">1 Peter 2:17</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 15 helpful votes</span></h3>
<div style="margin-top: -1em;">
Honor everyone. Love the brotherhood. Fear God. Honor the emperor.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_54005008" name="vote_u_54005008" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_54005008" name="vote_d_54005008" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=1+Timothy+5%3A8&amp;version=ESV">1 Timothy 5:8</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 12 helpful votes</span></h3>
<div style="margin-top: -1em;">
But if anyone does not provide for his relatives, and especially for members of his household, he has denied the faith and is worse than an unbeliever.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_41012013-41012017" name="vote_u_41012013-41012017" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_41012013-41012017" name="vote_d_41012013-41012017" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Mark+12%3A13-17&amp;version=ESV">Mark 12:13-17</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 12 helpful votes</span></h3>
<div style="margin-top: -1em;">
And they sent to him some of the Pharisees and some of the Herodians, to trap him in his talk. And they came and said to him, “Teacher, we know that you are true and do not care about anyone's opinion. For you are not swayed by appearances, but truly teach the way of God. Is it lawful to pay taxes to Caesar, or not? Should we pay them, or should we not?” But, knowing their hypocrisy, he said to them, “Why put me to the test? Bring me a denarius and let me look at it.” And they brought one. And he said to them, “Whose likeness and inscription is this?” They said to him, “Caesar's.” Jesus said to them, “Render to Caesar the things that are Caesar's, and to God the things that are God's.” And they marveled at him.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_19109008" name="vote_u_19109008" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_19109008" name="vote_d_19109008" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Psalm+109%3A8&amp;version=ESV">Psalm 109:8</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 11 helpful votes</span></h3>
<div style="margin-top: -1em;">
May his days be few; may another take his office!</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_20021001" name="vote_u_20021001" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_20021001" name="vote_d_20021001" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Proverbs+21%3A1&amp;version=ESV">Proverbs 21:1</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 9 helpful votes</span></h3>
<div style="margin-top: -1em;">
The king's heart is a stream of water in the hand of the&nbsp;<span class="sc">Lord</span>; he turns it wherever he will.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_28004006" name="vote_u_28004006" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_28004006" name="vote_d_28004006" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Hosea+4%3A6&amp;version=ESV">Hosea 4:6</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 8 helpful votes</span></h3>
<div style="margin-top: -1em;">
My people are destroyed for lack of knowledge; because you have rejected knowledge, I reject you from being a priest to me. And since you have forgotten the law of your God, I also will forget your children.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_03019018" name="vote_u_03019018" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_03019018" name="vote_d_03019018" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Leviticus+19%3A18&amp;version=ESV">Leviticus 19:18</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 8 helpful votes</span></h3>
<div style="margin-top: -1em;">
You shall not take vengeance or bear a grudge against the sons of your own people, but you shall love your neighbor as yourself: I am the&nbsp;<span class="sc">Lord</span>.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_44020035" name="vote_u_44020035" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_44020035" name="vote_d_44020035" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Acts+20%3A35&amp;version=ESV">Acts 20:35</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 7 helpful votes</span></h3>
<div style="margin-top: -1em;">
In all things I have shown you that by working hard in this way we must help the weak and remember the words of the Lord Jesus, how he himself said, ‘It is more blessed to give than to receive.’”</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_41006017-41006028" name="vote_u_41006017-41006028" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_41006017-41006028" name="vote_d_41006017-41006028" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Mark+6%3A17-28&amp;version=ESV">Mark 6:17-28</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 7 helpful votes</span></h3>
<div style="margin-top: -1em;">
For it was Herod who had sent and seized John and bound him in prison for the sake of Herodias, his brother Philip's wife, because he had married her. For John had been saying to Herod, “It is not lawful for you to have your brother's wife.” And Herodias had a grudge against him and wanted to put him to death. But she could not, for Herod feared John, knowing that he was a righteous and holy man, and he kept him safe. When he heard him, he was greatly perplexed, and yet he heard him gladly. But an opportunity came when Herod on his birthday gave a banquet for his nobles and military commanders and the leading men of Galilee. ...</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_40025032-40025046" name="vote_u_40025032-40025046" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_40025032-40025046" name="vote_d_40025032-40025046" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Matthew+25%3A32-46&amp;version=ESV">Matthew 25:32-46</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 7 helpful votes</span></h3>
<div style="margin-top: -1em;">
Before him will be gathered all the nations, and he will separate people one from another as a shepherd separates the sheep from the goats. And he will place the sheep on his right, but the goats on the left. Then the King will say to those on his right, ‘Come, you who are blessed by my Father, inherit the kingdom prepared for you from the foundation of the world. For I was hungry and you gave me food, I was thirsty and you gave me drink, I was a stranger and you welcomed me, I was naked and you clothed me, I was sick and you visited me, I was in prison and you came to me.’ ...</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_56003009" name="vote_u_56003009" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_56003009" name="vote_d_56003009" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Titus+3%3A9&amp;version=ESV">Titus 3:9</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 6 helpful votes</span></h3>
<div style="margin-top: -1em;">
But avoid foolish controversies, genealogies, dissensions, and quarrels about the law, for they are unprofitable and worthless.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_42016013" name="vote_u_42016013" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_42016013" name="vote_d_42016013" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Luke+16%3A13&amp;version=ESV">Luke 16:13</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 6 helpful votes</span></h3>
<div style="margin-top: -1em;">
No servant can serve two masters, for either he will hate the one and love the other, or he will be devoted to the one and despise the other. You cannot serve God and money.”</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_20014034" name="vote_u_20014034" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_20014034" name="vote_d_20014034" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Proverbs+14%3A34&amp;version=ESV">Proverbs 14:34</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 6 helpful votes</span></h3>
<div style="margin-top: -1em;">
Righteousness exalts a nation, but sin is a reproach to any people.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_45013004" name="vote_u_45013004" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_45013004" name="vote_d_45013004" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Romans+13%3A4&amp;version=ESV">Romans 13:4</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 5 helpful votes</span></h3>
<div style="margin-top: -1em;">
For he is God's servant for your good. But if you do wrong, be afraid, for he does not bear the sword in vain. For he is the servant of God, an avenger who carries out God's wrath on the wrongdoer.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_41010017-41010030" name="vote_u_41010017-41010030" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_41010017-41010030" name="vote_d_41010017-41010030" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Mark+10%3A17-30&amp;version=ESV">Mark 10:17-30</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 5 helpful votes</span></h3>
<div style="margin-top: -1em;">
And as he was setting out on his journey, a man ran up and knelt before him and asked him, “Good Teacher, what must I do to inherit eternal life?” And Jesus said to him, “Why do you call me good? No one is good except God alone. You know the commandments: ‘Do not murder, Do not commit adultery, Do not steal, Do not bear false witness, Do not defraud, Honor your father and mother.’” And he said to him, “Teacher, all these I have kept from my youth.” And Jesus, looking at him, loved him, and said to him, “You lack one thing: go, sell all that you have and give to the poor, and you will have treasure in heaven; and come, follow me.” ...</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_14007014" name="vote_u_14007014" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_14007014" name="vote_d_14007014" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=2+Chronicles+7%3A14&amp;version=ESV">2 Chronicles 7:14</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 5 helpful votes</span></h3>
<div style="margin-top: -1em;">
If my people who are called by my name humble themselves, and pray and seek my face and turn from their wicked ways, then I will hear from heaven and will forgive their sin and heal their land.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_09008001-09008022" name="vote_u_09008001-09008022" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_09008001-09008022" name="vote_d_09008001-09008022" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=1+Samuel+8%3A1-22&amp;version=ESV">1 Samuel 8:1-22</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 5 helpful votes</span></h3>
<div style="margin-top: -1em;">
When Samuel became old, he made his sons judges over Israel. The name of his firstborn son was Joel, and the name of his second, Abijah; they were judges in Beersheba. Yet his sons did not walk in his ways but turned aside after gain. They took bribes and perverted justice. Then all the elders of Israel gathered together and came to Samuel at Ramah and said to him, “Behold, you are old and your sons do not walk in your ways. Now appoint for us a king to judge us like all the nations.” ...</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_02020001-02020026" name="vote_u_02020001-02020026" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_02020001-02020026" name="vote_d_02020001-02020026" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Exodus+20%3A1-26&amp;version=ESV">Exodus 20:1-26</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 4 helpful votes</span></h3>
<div style="margin-top: -1em;">
And God spoke all these words, saying, “I am the&nbsp;<span class="sc">Lord</span>&nbsp;your God, who brought you out of the land of Egypt, out of the house of slavery. “You shall have no other gods before me. “You shall not make for yourself a carved image, or any likeness of anything that is in heaven above, or that is in the earth beneath, or that is in the water under the earth. You shall not bow down to them or serve them, for I the&nbsp;<span class="sc">Lord</span>&nbsp;your God am a jealous God, visiting the iniquity of the fathers on the children to the third and the fourth generation of those who hate me, ...</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_17003001-17003015" name="vote_u_17003001-17003015" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_17003001-17003015" name="vote_d_17003001-17003015" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=Esther+3%3A1-15&amp;version=ESV">Esther 3:1-15</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 3 helpful votes</span></h3>
<div style="margin-top: -1em;">
After these things King Ahasuerus promoted Haman the Agagite, the son of Hammedatha, and advanced him and set his throne above all the officials who were with him. And all the king's servants who were at the king's gate bowed down and paid homage to Haman, for the king had so commanded concerning him. But Mordecai did not bow down or pay homage. Then the king's servants who were at the king's gate said to Mordecai, “Why do you transgress the king's command?” And when they spoke to him day after day and he would not listen to them, they told Haman, in order to see whether Mordecai's words would stand, for he had told them that he was a Jew. And when Haman saw that Mordecai did not bow down or pay homage to him, Haman was filled with fury. ...</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_11001001-11001053" name="vote_u_11001001-11001053" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_11001001-11001053" name="vote_d_11001001-11001053" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=1+Kings+1%3A1-53&amp;version=ESV">1 Kings 1:1-53</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 3 helpful votes</span></h3>
<div style="margin-top: -1em;">
Now King David was old and advanced in years. And although they covered him with clothes, he could not get warm. Therefore his servants said to him, “Let a young woman be sought for my lord the king, and let her wait on the king and be in his service. Let her lie in your arms, that my lord the king may be warm.” So they sought for a beautiful young woman throughout all the territory of Israel, and found Abishag the Shunammite, and brought her to the king. The young woman was very beautiful, and she was of service to the king and attended to him, but the king knew her not. Now Adonijah the son of Haggith exalted himself, saying, “I will be king.” And he prepared for himself chariots and horsemen, and fifty men to run before him. ...</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_10020016-10020022" name="vote_u_10020016-10020022" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_10020016-10020022" name="vote_d_10020016-10020022" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=2+Samuel+20%3A16-22&amp;version=ESV">2 Samuel 20:16-22</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 3 helpful votes</span></h3>
<div style="margin-top: -1em;">
Then a wise woman called from the city, “Listen! Listen! Tell Joab, ‘Come here, that I may speak to you.’” And he came near her, and the woman said, “Are you Joab?” He answered, “I am.” Then she said to him, “Listen to the words of your servant.” And he answered, “I am listening.” Then she said, “They used to say in former times, ‘Let them but ask counsel at Abel,’ and so they settled a matter. I am one of those who are peaceable and faithful in Israel. You seek to destroy a city that is a mother in Israel. Why will you swallow up the heritage of the&nbsp;<span class="sc">Lord</span>?” Joab answered, “Far be it from me, far be it, that I should swallow up or destroy! ...</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_10015002-10015006" name="vote_u_10015002-10015006" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_10015002-10015006" name="vote_d_10015002-10015006" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=2+Samuel+15%3A2-6&amp;version=ESV">2 Samuel 15:2-6</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 3 helpful votes</span></h3>
<div style="margin-top: -1em;">
And Absalom used to rise early and stand beside the way of the gate. And when any man had a dispute to come before the king for judgment, Absalom would call to him and say, “From what city are you?” And when he said, “Your servant is of such and such a tribe in Israel,” Absalom would say to him, “See, your claims are good and right, but there is no man designated by the king to hear you.” Then Absalom would say, “Oh that I were judge in the land! Then every man with a dispute or cause might come to me, and I would give him justice.” And whenever a man came near to pay homage to him, he would put out his hand and take hold of him and kiss him. Thus Absalom did to all of Israel who came to the king for judgment. So Absalom stole the hearts of the men of Israel.</div>
</div>
<div class="verse" style="background-color: white; font-family: Corbel, Verdana, sans-serif; margin-left: -150px; padding-left: 150px;">
<div class="vote-buttons invisible" style="left: 0px; padding-right: 10px; position: absolute; text-align: right; visibility: hidden; width: 140px;">
<button id="vote_u_59004001-59004012" name="vote_u_59004001-59004012" style="margin-bottom: 3px;" type="submit" value="1"></button><button id="vote_d_59004001-59004012" name="vote_d_59004001-59004012" style="margin-bottom: 3px;" type="submit" value="-1"></button></div>
<h3 style="background-image: none; border-top-style: none; color: #625529; font-size: 18px; left: 0px; position: relative; width: auto;">
<a class="bibleref" href="http://www.biblegateway.com/passage/?search=James+4%3A1-12&amp;version=ESV">James 4:1-12</a>&nbsp;<span class="note" style="color: #444444; font-size: 14px; font-weight: 400;">ESV / 1 helpful vote</span></h3>
<div style="margin-top: -1em;">
What causes quarrels and what causes fights among you? Is it not this, that your passions are at war within you? You desire and do not have, so you murder. You covet and cannot obtain, so you fight and quarrel. You do not have, because you do not ask. You ask and do not receive, because you ask wrongly, to spend it on your passions. You adulterous people! Do you not know that friendship with the world is enmity with God? Therefore whoever wishes to be a friend of the world makes himself an enemy of God. Or do you suppose it is to no purpose that the Scripture says, “He yearns jealously over the spirit that he has made to dwell in us”? ...</div>
</div>
<br />
<br />
<br />