---
title: 'Regarding Israel'
date: '2012-12-03T03:52:00.0010000+00:00'
draft: true
blogger_blog: 'Wolfe for Office'
blogger_status: 'DRAFT'
blogger_post_id: '6382310691743710507'
blogger_filename: '/2012/12/regarding-israel.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Wolfe for Office/feed.atom'
categories:
  - 'Israel'
---

There is ONLY ONE correct response for the USA, a Christian Nation despite efforts to tear that down, to have regarding Israel as a nation. It must stand. If only two nations on this earth must stand it must be the Israel first and USA second. It must stand with it's Davidic Boarders as promised through Torah. It must NEVER placate enemies. It must NEVER give up land. It must regain and possess ALL it's promised land. It must be backed up by money and might, but more importantly with staunch moral and political support. Any threat to Israel must be seen as a grave theat to the USA. Fierce and Immediate action must be taken in response to such a threat.<br />
<br />
Only when Presidents of the USA cease seeking peace through negotiation and begin to seek peace through dominance over terrorists and enemies of peace. The USA did to Osama Bin Laden as Israel should do to ALL leaders who would dare to bring threat against them.<br />
<br />
Only this stance can ensure peace for the USA and Israel. It is God's stance throughout His word. It was only when enemies were "tolerated" by Israel that she was destroyed.<br />
<br />
Darrell