---
title: 'The Dangerous Rise of the Moral Majority | Learning the power to live and let live'
date: '2016-07-31T12:48:00.0020000+00:00'
draft: true
blogger_blog: 'Wolfe for Office'
blogger_status: 'DRAFT'
blogger_post_id: '2987281685545142166'
blogger_filename: '/2016/07/the-dangerous-rise-of-moral-majority.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Wolfe for Office/feed.atom'
---

<br />
<br />
<br /><a href="https://en.wikipedia.org/wiki/Moral_Majority" target="_blank">Wiki:The Moral Majority&nbsp;</a><br />The Moral Majority was a prominent American political organization associated with the <a href="https://en.wikipedia.org/wiki/Christian_right">Christian right</a> and <a href="https://en.wikipedia.org/wiki/Republican_Party_(United_States)">Republican Party</a>. It was founded in 1979 by Baptist minister <a href="https://en.wikipedia.org/wiki/Jerry_Falwell">Jerry Falwell</a> and associates, and dissolved in the late 1980s. It played a key role in the mobilization of conservative Christians as a&nbsp;political force and particularly in Republican presidential victories throughout the 1980s.<br /><br />Some issues for which the Moral Majority campaigned included:<a href="https://en.wikipedia.org/wiki/Moral_Majority#cite_note-columbia-19">[19]</a><br /><ul>
<li>Promotion of a 'traditional' vision of family life</li>
<li>Opposition to media outlets that it claimed promote an "anti-family" agenda</li>
<li>Opposition to the <a href="https://en.wikipedia.org/wiki/Equal_Rights_Amendment">Equal Rights Amendment</a> and <a href="https://en.wikipedia.org/wiki/Strategic_Arms_Limitation_Talks">Strategic Arms Limitation Talks</a></li>
<li>Opposition to state recognition or acceptance of <a href="https://en.wikipedia.org/wiki/Homosexuality">homosexual</a> acts.</li>
<li>Prohibition of <a href="https://en.wikipedia.org/wiki/Abortion">abortion</a>, even in cases involving incest, rape or in pregnancies where the life of the mother is at stake.<a href="https://en.wikipedia.org/wiki/Moral_Majority#cite_note-20">[20]</a></li>
<li>Support for <a href="https://en.wikipedia.org/wiki/Christianity">Christian</a> prayers in schools</li>
<li>Marketing to <a href="https://en.wikipedia.org/wiki/Jews">Jews</a> and other non-Christians for conversion to <a href="https://en.wikipedia.org/wiki/Christian_right">conservative Christianity</a></li>
</ul>
<br /><a href="http://philvischer.com/the-phil-vischer-podcast/episode-71-phils-great-uncle-iner-origins-of-evangelicalism-and-louis-cks-musings-on-emptiness/" target="_blank">EPISODE 71</a>: PHIL’S GREAT UNCLE EINER, ORIGINS OF EVANGELICALISM, AND LOUIS CK’S MUSINGS ON EMPTINESS!<br /><br /><br />http://philvischer.com/the-phil-vischer-podcast/episode-183-american-politics/<div>
<br /></div>
<div>
http://philvischer.com/the-phil-vischer-podcast/episode-111-nasa-aliens-and-jesus-politics/</div>
<div>
<br /></div>
<div>
http://philvischer.com/the-phil-vischer-podcast/episode-17-christianity-and-politics-in-the-us-with-guest-amy-black/</div>
<div>
<br /></div>
<div>
<br /><br /><br /><br /><br /><br /><br /><br /><br />
<br />
<br />
<br />
<br />
<br /></div>
