---
title: 'I left the #GOP forever and it has nothing to do with Donald Trump.'
date: '2016-08-29T07:28:00.0000000+00:00'
draft: true
blogger_blog: 'Wolfe for Office'
blogger_status: 'DRAFT'
blogger_post_id: '7363550979362185470'
blogger_filename: '/2016/08/i-left-gop-forever-and-it-has-nothing.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Wolfe for Office/feed.atom'
categories:
  - 'News & Events'
  - 'Reason'
---

<h4>
Election2016 Clarification:</h4>
<br />
I heard another talk radio guy (<a href="http://grantstinchfield.com/">Grant Stinchfield</a>) jump on the Trump Train this morning... another person claiming to be a conservative who is so blinded by his hate for Hillary Clinton, he cannot see that the devil he chose is worse than the one he rejects.<br />
<div>
<br /></div>
<div>
Hillary and Obama combined couldn't harm this country as bad as Trump could. That's what worries me most about this coming election. But here's the thing Grant doesn't get. He thinks I'm voting for Gary Johnson because of Trump.<br />
<br />
<h4>
I left the #GOP forever and it has nothing to do with Donald Trump.&nbsp;</h4>
</div>
<div>
<br /></div>
<div>
He is a symptom, not the cause.<br />
<br />
In actuality, I'm voting for Gary Johnson because of every single candidate that ran this year, except for Ted Cruz. Anyone that was nominated, other than Cruz, would have resulted in my leaving the GOP this year. I didn't leave Donald Trump, I left the GOP.<br />
<br />
The way the GOP Leadership has consistently run from Constitutionalist values for decades upon decades is what pushed me out. The way the GOP Leadership, not Donald Trump, treated Ted Cruz demonstrated once and for all, that the GOP is not now, nor will they ever be a small government party. Even the great Ronald Reagan himself was not as small government as he needed to be.&nbsp;</div>
<div>
<br /></div>
<div>
The last good president this country had was&nbsp;<a href="https://www.prageru.com/courses/history/coolidge-best-president-you-dont-know" target="_blank">Calvin Coolidge</a>.<br />
<br />
<h4>
For that reason, I left the GOP.&nbsp;</h4>
</div>
<div>
<br /></div>
<div>
I want a small government candidate and ONLY a small government candidate. Nothing less will do. No Compromise. Ever again.<br />
<br />
Hillary Clinton is a Marxist Tyrant, and would ruin this country.&nbsp;</div>
<div>
<br /></div>
<div>
Donald Trump is a Fascist Tyrant, and would ruin this country.&nbsp;</div>
<div>
<br /></div>
<div>
Pick your poison, they are equally awful. If I had to choose, I'd pick Hillary.<br />
<br />
Why&nbsp;you ask? At least she's proven to be an inept loser. Donald Trump, on the other hand, has proven to be an effective negotiator. And that worries me far more than Hillary. He's the same as her, just a different letter next to his name. He would be more effective... in the wrong direction.<br />
<br />
<h4>
I will vote #Libertarian, unless and until a better party arises.</h4>
</div>
<div>
<br /></div>
<div>
President, Senate, House, Governor, Mayor, City Council... all Libertarian votes from me.</div>
<div>
<br /></div>
<div>
I will vote for Gary Johnson. There is little chance he will win, but I think there is a tiny outside chance. Nevertheless, I will only vote for small government people here forward. Never again, the lesser of two evils. I'm not playing their (R's and D's) game anymore. They are the same party in my book. "Statists"<br />
<br />
<h4>
Not just this election, but in all elections.&nbsp;</h4>
</div>
<div>
<br /></div>
<div>
This is a long battle plan change of voting. I'm not just concerned about 2016; rather, I'm concerned about being one pebble in the pond of change toward a new party for the USA.<br />
<br />
Hopefully, through many smaller wins, over many elections, we can start to turn the tide to a smaller government for the USA... one election at a time, for the rest of my life. There will be no big wins, but a steady fight to less government.<br />
<br />
<blockquote class="tr_bq">
<b>Win or Lose, voting @GaryJohnson and an all #Libertarian ticket... #YouIn?</b></blockquote>
<br />
<br />
Darrell Wolfe</div>
