---
title: 'If I were running for office: Introduction to liberty'
date: '2016-05-03T07:12:00.0000000+00:00'
draft: true
blogger_blog: 'Wolfe for Office'
blogger_status: 'DRAFT'
blogger_post_id: '8342969323895425466'
blogger_filename: '/2016/05/if-i-were-running-for-office_3.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Wolfe for Office/feed.atom'
---

<br />
<br />
<h2>
If I were running for office: Introduction to liberty&nbsp;</h2>
<h3>
Republicans are off track and Democrats are heading the wrong direction.</h3>
<br />
I have a confession to make. I'm coming out of the closet... as a #<a href="http://www.lp.org/" target="_blank">Libertarian</a>. Or something like that.<br />
<br />
With the resignation of #TedCruz, #Elections2016, and the way the #GOP has treated liberty and conservative constitutional values, I am leaving the #Republican party forever. Not just for president, but the party as a whole. From President to Garbage man, I am done with the GOP. If a particular general election ballot only gives me two choices, I'd probably still vote GOP? But my plan is to vote a straight #Libertarian ticket in November 2016.<br />
<br />
<h4>
But what about 2017 and beyond?&nbsp;</h4>
<br />
I believe the Grand Ol' Party (GOP)/Republicans, and the Democrats/Socialist have both left their moorings and dragged the United States of America into a swirling mess of chaos.<br />
<br />
The long term problem with Libertarian viability, is that they (as a group) are a bit prickly. We need a warmer, friendly, more inviting party. Unfortunately for 2016, no such party exists. So I'm voting Libertarian this year (2016).<br />
<br />
It's about time we knocked some sense into the political discourse. I'm ready for a brand new Political Party? What do you say? But on what basis is it founded, and what would be it's pillars.<br />
<br />
First step, we need to understand what we have and why, before we can understand where we are going and why.<br />
<br />
<blockquote class="tr_bq">
<i>It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery. Galatians 5:1 New International Version</i></blockquote>
<h4>
Why was the United States Created? Prevention of Tyranny to preserve Liberty.</h4>
The&nbsp;<a href="http://www.archives.gov/exhibits/charters/declaration_transcript.html" target="_blank">Declaration of Independence</a>&nbsp;was signed on July 04, 1776. It outlines a story of people suffering at the hands of an abusive government that takes advantage of people and robs them of their rights and private property. The opening is worth a re-read:<br />
<blockquote class="tr_bq">
<i><br /></i><i>When in the Course of human events, it becomes necessary for one people to dissolve the political bands which have connected them with another, and to assume among the powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation.</i></blockquote>
<blockquote class="tr_bq">
<i>We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.--That to secure these rights, Governments are instituted among Men, deriving their just powers from the consent of the governed, --That whenever any Form of Government becomes destructive of these ends, it is the Right of the People to alter or to abolish it, and to institute new Government, laying its foundation on such principles and organizing its powers in such form, as to them shall seem most likely to effect their Safety and Happiness. Prudence, indeed, will dictate that Governments long established should not be changed for light and transient causes; and accordingly all experience hath shewn, that mankind are more disposed to suffer, while evils are sufferable, than to right themselves by abolishing the forms to which they are accustomed. But when a long train of abuses and usurpations, pursuing invariably the same Object evinces a design to reduce them under absolute Despotism, it is their right, it is their duty, to throw off such Government, and to provide new Guards for their future security.</i></blockquote>
<br />
<br />
<h4>
What they reacted against...</h4>
<br />
To boil down the list that follows the above excerpt, the original founders of this Great Nation were rebelling against Big Government (BG) intruding into the lives of it's people, and attempting to control them by force and manipulation, wars, and taxes. Sound Familiar?<br />
<br />
They tried to reason with the BG, bargain with BG, plead with BG, but BG got more bloated and more controlling. Rights were continually stripped away until people that were supposed to be citizens of the government were prisoners of it instead.<br />
<br />
<br />
<br />
<h4>
Liberty is...</h4>
<blockquote class="tr_bq">
<b>liberty</b><br />
noun &nbsp;lib·er·ty \ˈli-bər-tē\&nbsp;</blockquote>
<blockquote class="tr_bq">
Simple Definition of liberty<br />
: the state or condition of people who are able to act and speak freely<br />
: the power to do or choose what you want to<br />
: a political right<br />
Source:&nbsp;<a href="http://www.merriam-webster.com/dictionary/liberty" target="_blank">Merriam-Webster's</a></blockquote>
This country was founded by people abused by a big government. They put protections in place to ensure that the government they created would stay small, local, by-for-of the people. In the 240 years since those protections were fought for, they have been eroded.<br />
<br />
This is not to say that our past was perfect. In many ways 2016 is better for people than previous years, but that is only true in areas in which their personal liberty has been upheld and enhanced.<br />
<br />
<br />
<h4>
The Solution...</h4>
<br />
I'm not advocating a full scale take down of the United States of America. It has great framing, and good bones. But like a house that was vandalized, it needs to be stripped down to it's frame, re-secured, and re-built.<br />
<br />
<br />
We need a new party, dedicated to liberty, that can do the job. Maybe a face lift on the Libertarian Party would be enough? Maybe we need something more? Not sure yet.<br />
<br />
<br />
More to come on this topic in the future...<br />
<br />
Darrell Wolfe<br />
Story Teller | INFJ | Intellection | Learner | Ideation | Achiever | Input | Multipotentialite<br />
<div>
<br /></div>
<br />
<br />