---
title: 'If I were running for office: Introduction to the US Constitution Legislative Branch'
date: '2016-05-29T07:05:00.0010000+00:00'
draft: true
blogger_blog: 'Wolfe for Office'
blogger_status: 'DRAFT'
blogger_post_id: '8821254696963687919'
blogger_filename: '/2016/05/if-i-were-running-for-office.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Wolfe for Office/feed.atom'
categories:
  - 'Compassion'
  - 'Foundations'
  - 'Liberty'
  - 'History'
  - 'Reason'
---

<br />
<h2>
If I were running for office: Introduction to the US Constitution Legislative Branch</h2>
<h3>
Republicans are off track and Democrats are heading the wrong direction.</h3>
<br />
<br />
<h4>
What was the purpose of the founding document (The Constitution)? Prevention of Tyranny to preserve Liberty.</h4>
<br />
The&nbsp;<a href="http://www.archives.gov/exhibits/charters/constitution_transcript.html" target="_blank">Constitution&nbsp;</a>(<a href="http://www.archives.gov/exhibits/charters/constitution_transcript.html" target="_blank">transcript here</a>)&nbsp;of the United States of America was designed to prevent the abuse of power seen in every other form of government in the history of man. The reason for the checks and balances put into the Constitution (<a href="https://en.wikipedia.org/wiki/United_States_Constitution" target="_blank">history here</a>) was to purposefully limit the power of the Federal Government, which was always intended to be small.<br />
<br />
<h4>
What was the purpose of the three separate branches? Prevention of Tyranny to preserve Liberty.</h4>
<b>Legislative Branch</b><br />
<br />
<blockquote class="tr_bq">
<i>All legislative Powers herein granted shall be vested in a Congress of the United States, which shall consist of a Senate and House of Representatives.</i></blockquote>
<br />
<b>The&nbsp;<a href="https://en.wikipedia.org/wiki/United_States_House_of_Representatives" target="_blank">House of Representatives</a></b>&nbsp;are comprised of many local level elected officials. There are more Representatives than there are Senators. They have the sole power of Impeachment. Bills should originate in the House, but may be ratified or augmented by the Senate.<br />
<br />
<b>The&nbsp;<a href="https://en.wikipedia.org/wiki/United_States_Senate" target="_blank">Senate&nbsp;</a></b>is comprised of just two Senators from each state (regardless of how many people are in that state. This creates a balance of power withing the congress. The Vice President is the president of the Senate. The chain of command if the both President and Vice President are incapacitated goes to various parties within the Senate. The Senate tries the Impeachment process.<br />
<br />
Section 8 of the US Constitution outlines the powers assigned. The Congress (House and Senate combined) shall have Power To:<br />
<ul>
<li>Create Taxes and Collect Them.</li>
<li>Borrow (debt) on behalf of the USA.</li>
<li>Initiate Regulations that affect commerce (buying/selling).</li>
<li>Establish rules about becoming a citizen</li>
<li>Establish Bankruptcy laws.</li>
<li>Create currency/money, and regulate it's use, and punish counterfeiters.</li>
<li>Fix the standard of weights and measures (fairness for consumers).</li>
<li>Establish Post Offices and Post Roads.</li>
<li>Promote Science and Art (by securing intellectual property rights, not by taxes or money or "incentives" or "grants").</li>
<li>Hold court on certain issues inferior to the Supreme Court.</li>
<li>Define and punish piracies and felonies.</li>
<li>Declare war.</li>
<li>Make Rules about land and water.</li>
<li>Raise and support the military (with two year limits on military spending budgets).</li>
<li>Use local militias to execute laws of the nation, suppress insurrections, and repel invasions.&nbsp;</li>
<li>Control the land used by the Capitol of the USA (not to exceed ten miles square.</li>
<li>To make all laws (only those necessary and proper for carrying out the duties outlined above).&nbsp;</li>
</ul>
<br />
The two houses, power divided, had to work together to do any of these things. There power was essentially limited to taxes, currency, military, roads, land use, and establishing fairness in commerce (buying/selling).<br />
<br />
These powers are broad, and so they were given to a large body of two houses to spread that power across many people. The intention was to keep this huge power from the hands of any one person or elite group.<br />
<br />
"Getting things done" was not the intention of Washington D.C. The intention was to ensure that any policy that was divisive or contentious would be thoroughly argued about, pushed back on, and never implemented until a majority had agreed.<br />
<br />
<i>(If it were up to me, I'd implement a rule that 80% of each houses had to agree to pass any law. That way only policies with broad support would be passed.)</i><br />
<br />
Notice the items that are missing. Many items that we debate nationally are not in the scope of the Federal Government, and should be left to the states and people to work out. The Bill of Rights covers some additional things, but we'll get to those in another post.<br />
<br />
Some recent examples:<br />
<ul>
<li>Schools (all forms of education)&nbsp;</li>
<li>Marriage (all forms)</li>
<li>Wages (what an employer agrees to pay, and a worker agrees to work for)</li>
<li>Health Care</li>
<li>Bathrooms</li>
<li>The Environmental</li>
<li>All Government Agencies</li>
<ul>
<li>&nbsp;The House can create rules.</li>
<li>Congress has the right to hold a hearing about any entity that violates the rules. They do not have the &nbsp;right to&nbsp;create bureaucratic agencies with no over sight or controls.</li>
<li>If congress wants to enforce the rules, they should hold a hearing, or leave it to each state to enforce.&nbsp;</li>
<li>They are rule makers, not rule enforcers.</li>
</ul>
</ul>
<br />
<br />
Articles I intend to write (or have written):<br />
<br />
<ul>
<li>If I were running for office: Liberty, Free Will, Choice, and the NAP</li>
<li>If I were running for office: Immigration - A Secure Nation Of Immigrants</li>
<li>If I were running for office: Education - Learning to Learn vs Learning to Test</li>
<li>If I were running for office: Economy - Unions, Corporations, and Free Markets</li>
<li>If I were running for office: Religion - Religious Freedom vs State Religion</li>
<li>If I were running for office: Rightful Place - Governments, Free Markets and Non Profits</li>
<li>If I were running for office: Abortion and NAP</li>
<li>If I were running for office: TBD</li>
<li>If I were running for office:&nbsp;TBD</li>
<li>If I were running for office:&nbsp;TBD</li>
<li>If I were running for office:&nbsp;TBD</li>
</ul>
<br />
<br />
<b>Darrell Wolfe</b><br />
<b><br /></b>
<b>Story Teller | INFJ | Intellection | Learner | Ideation | Achiever | Input | Multipotentialite</b>