---
title: 'Getting an Idaho drivers license; after moving to Coeur d''Alene ID'
date: '2016-06-06T03:02:00.0030000+00:00'
draft: true
blogger_blog: 'Destination Coeur d''Alene, Idaho'
blogger_status: 'LIVE'
blogger_post_id: '8046089264715034570'
blogger_filename: '/2016/06/getting-idaho-drivers-license-after.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Destination Coeur d_Alene, Idaho/feed.atom'
categories:
  - 'State & Gov Stuff'
---

<h3>
Here is all of the information I found relevant about obtaining a drivers license when we get to CDA.</h3>
<br />
<h3>
Getting a Divers License After Moving to Idaho:</h3>
<br />
<ul>
<li>One License Law—When applying for an Idaho Class D driver’s license, you must surrender any driver’s license or ID card issued to you from another state.</li>
</ul>
<ul>
<li>When I moved from CA to TX, my insurance company ended up asking me for my CA DL information for drivers history reasons.</li>
<ul>
<li>Just in case you need your OLD ID information, make sure to take a good high quality photo of the old ID before you go. Store the old ID picture on the cloud somewhere so you can't loose it.&nbsp;</li>
</ul>
</ul>
<br />
<br />
<b>The agency responsible for Drivers Licenses is the&nbsp;<a href="http://itd.idaho.gov/dmv/driverservices/index.html" target="_blank">Idaho Transportation Department (ITD)</a></b><br />
<div>
<blockquote class="tr_bq">
<i>Who needs a driver’s license?</i><i>Anyone who operates a motor vehicle on the public roads in Idaho is required to have a valid driver’s license.</i><i><b>When moving to Idaho you will need to apply for an Idaho driver’s license within 90 days of residing in Idaho</b>, whether your out-of-state license has expired or not. If you have a Commercial Driver’s License (CDL), you are required to be licensed in Idaho within 30 days of residing in Idaho.</i></blockquote>
</div>
<ul>
<li><a href="http://itd.idaho.gov/dmv/driverservices/DLFees.html"><b>How much will it cost?</b></a></li>
<ul>
<li></li>
<li>4-year License (age 21 and over)<span class="Apple-tab-span" style="white-space: pre;"> </span>$30.00</li>
<li>8-year License (age 21 to 62)<span class="Apple-tab-span" style="white-space: pre;"> </span>$55.00</li>
</ul>
</ul>
<ul>
<li><b>Where do I get a driver’s license or Identification Card?</b></li>
</ul>
<blockquote class="tr_bq">
<i>Idaho driver’s licenses, instruction permits, or identification cards are issued through the county sheriff’s offices. You may apply at the <a href="http://itd.idaho.gov/dmv/driverservices/Sheriff.html">sheriff’s driver licensing office</a> most convenient to you.</i></blockquote>
<div>
<blockquote class="tr_bq">
<i>You may apply at the sheriff’s driver licensing office most convenient to you.&nbsp;</i><a href="http://itd.idaho.gov/dmv/driverservices/Sheriff.html" target="_blank">Local Sheriff's Office for New Drivers License (HERE)</a></blockquote>
<div style="direction: ltr;">

<table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse; border-color: #A3A3A3; border-style: solid; border-width: 1pt; direction: ltr;" valign="top">
 <tbody>
<tr>
  <td style="border-color: #A3A3A3; border-style: solid; border-width: 1pt; padding: 4pt 4pt 4pt 4pt; vertical-align: top; width: .7798in;">
  <div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<span style="font-weight: bold;">COUNTY</span></div>
</td>
  <td style="border-color: #A3A3A3; border-style: solid; border-width: 1pt; padding: 4pt 4pt 4pt 4pt; vertical-align: top; width: .9868in;">
  <div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<span style="font-weight: bold;">CITY</span></div>
</td>
  <td style="border-color: #A3A3A3; border-style: solid; border-width: 1pt; padding: 4pt 4pt 4pt 4pt; vertical-align: top; width: 1.5256in;">
  <div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<span style="font-weight: bold;">ADDRESS</span></div>
</td>
  <td style="border-color: #A3A3A3; border-style: solid; border-width: 1pt; padding: 4pt 4pt 4pt 4pt; vertical-align: top; width: 1.0291in;">
  <div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<span style="font-weight: bold;">PHONE (208)</span></div>
</td>
  <td style="border-color: #A3A3A3; border-style: solid; border-width: 1pt; padding: 4pt 4pt 4pt 4pt; vertical-align: top; width: 1.1395in;">
  <div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<span style="font-weight: bold;">OFFICE HOURS</span></div>
</td>
  <td style="border-color: #A3A3A3; border-style: solid; border-width: 1pt; padding: 4pt 4pt 4pt 4pt; vertical-align: top; width: 1.2805in;">
  <div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<span style="font-weight: bold;">NON-CDL TESTS*</span></div>
</td>
  <td style="border-color: #A3A3A3; border-style: solid; border-width: 1pt; padding: 4pt 4pt 4pt 4pt; vertical-align: top; width: .9875in;">
  <div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<span style="font-weight: bold;">CDL TESTS*</span></div>
</td>
 </tr>
<tr>
  <td style="background-color: #eeeeee; border-color: #A3A3A3; border-style: solid; border-width: 1pt; padding: 4pt 4pt 4pt 4pt; vertical-align: top; width: .7798in;">
  <div style="font-family: Calibri; font-size: 9.75pt; margin: 0in;">
<span style="font-weight: bold;">KOOTENAI</span></div>
</td>
  <td style="background-color: #eeeeee; border-color: #A3A3A3; border-style: solid; border-width: 1pt; padding: 4pt 4pt 4pt 4pt; vertical-align: top; width: .9868in;">
  <div style="font-family: Calibri; font-size: 9.75pt; margin: 0in;">
<span style="font-weight: bold;">Coeur D'Alene</span></div>
</td>
  <td style="background-color: #eeeeee; border-color: #A3A3A3; border-style: solid; border-width: 1pt; padding: 4pt 4pt 4pt 4pt; vertical-align: top; width: 1.5256in;">
  <div style="font-family: Calibri; font-size: 9.75pt; margin: 0in;">
<span style="font-weight: bold;">451 N Government Way</span></div>
</td>
  <td style="background-color: #eeeeee; border-color: #A3A3A3; border-style: solid; border-width: 1pt; padding: 4pt 4pt 4pt 4pt; vertical-align: top; width: 1.0291in;">
  <div style="font-family: Calibri; font-size: 9.75pt; margin: 0in;">
<span style="font-weight: bold;">208-446-1340</span></div>
</td>
  <td style="background-color: #eeeeee; border-color: #A3A3A3; border-style: solid; border-width: 1pt; padding: 4pt 4pt 4pt 4pt; vertical-align: top; width: 1.1395in;">
  <div style="font-family: Calibri; font-size: 9.75pt; margin: 0in;">
<span style="font-weight: bold;">7:30a to 5:30p</span></div>
</td>
  <td style="background-color: #eeeeee; border-color: #A3A3A3; border-style: solid; border-width: 1pt; padding: 4pt 4pt 4pt 4pt; vertical-align: top; width: 1.2805in;">
  <div style="font-family: Calibri; font-size: 9.75pt; margin: 0in;">
<span style="font-weight: bold;">7:30a to 4:30p</span></div>
</td>
  <td style="background-color: #eeeeee; border-color: #A3A3A3; border-style: solid; border-width: 1pt; padding: 4pt 4pt 4pt 4pt; vertical-align: top; width: .9875in;">
  <div style="font-family: Calibri; font-size: 9.75pt; margin: 0in;">
<span style="font-weight: bold;">7:30a to 3:30p</span></div>
</td>
 </tr>
</tbody></table>
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<br />
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<ul>
<li><b><a href="http://itd.idaho.gov/dmv/driverservices/driver_license_facts.html">What do I need to bring with me?</a></b></li>
</ul>
<ul>
<li><b>Proof of Idaho Residency</b>—Utility Bill or Lease/Rental Docs.</li>
<ul>
<li>You must reside inside Idaho’s borders to be issued an Idaho driver’s license or ID card. Proof of residency can be shown with documents such as lease or rental agreements, utility bills, school enrollment records, etc. Your home address (where you live) cannot be your workplace, vacation residence, a part-time residence, P.O. Box, mail drop, or general delivery (that have been mailed to the applicant.) Please check with your local office to determine the acceptability of your documents.</li>
</ul>
</ul>
<ul>
<li><b>Proof of Age and Identity</b>— Old State DL</li>
<ul>
<li>Driver’s license examiners are required by law to verify your identity and age before issuing you a driver’s license or ID card.&nbsp;</li>
<li><b>If you have a valid, state-issued driver’s license or a state-issued ID card to surrender that meets the conditions of a primary document stated below, you do not need to provide any additional identity documents.&nbsp;</b></li>
</ul>
</ul>
<br />Darrell</div>
