---
title: 'Re-Registering your car; after moving to Coeur d''Alene, Idaho'
date: '2016-06-06T03:55:00.0000000+00:00'
draft: true
blogger_blog: 'Destination Coeur d''Alene, Idaho'
blogger_status: 'LIVE'
blogger_post_id: '4211952022873241563'
blogger_filename: '/2016/06/re-registering-your-car-after-moving-to.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Destination Coeur d_Alene, Idaho/feed.atom'
categories:
  - 'State & Gov Stuff'
---

<br /><h3>
The <a href="http://itd.idaho.gov/dmv/VehicleServices/index.html">Idaho Department of Transportation (IDT)</a>, Vehicle Services handles car registration and titles.</h3>
<br />A couple of interesting points. The Drivers License, Re-Titling, and Registration all need to be done within 90-days.&nbsp;<div>
<br /></div>
<div>
This is important if you have a loan on your car; because, you can't change the title on your own. If you have a loan (a lien holder) you need to contact the bank that holds the loan and title, and ask them to start the Out Of State Transfer (OOST) processing. They may ask you for paperwork. This could take 30-60 days if they have to order a title to be sent to your new state.</div>
<div>
<br /></div>
<div>
You should really start the process of all three of these the first or second week you are in the state, it could take 90-days to sort it all out.<br /><br /><h3>
Registering and Licensing Vehicles in Idaho (<a href="http://itd.idaho.gov/dmv/VehicleServices/registr.html" target="_blank">HERE</a>)</h3>
<br /><b>Registration REQUIREMENTS:</b><br />To register a vehicle in Idaho:<br /><ul>
<li>The vehicle must belong to an Idaho resident or business.</li>
<li><b style="background-color: yellow;">The vehicle must be titled in Idaho before it can be registered.</b> (You can apply for vehicle registration immediately after submitting the required documents to a county assessor's motor vehicle office.)</li>
<li><b style="background-color: yellow;">If you are a new resident, you must register and title your vehicle(s) within 90 days.</b></li>
</ul>
An Idaho resident is anyone whose principal home has been in Idaho for 90 continuous days, although residency may be declared at any time earlier, and vehicles may be titled and registered at that time. Idaho residents who are temporarily in another state (i.e., students or military personnel) may request titles and registrations for their vehicle(s) through the mail.<br /><br /><ul>
<li>Click here for information on: <a href="http://itd.idaho.gov/dmv/VehicleServices/titles1.html">Titling Vehicles in Idaho</a>.</li>
</ul>
<br /><b>FEES</b>:<br /><br />The following are approximate fees for passenger cars, motorhomes, motorcycles, boats, and recreational vehicle trailers.<br /><br /><b>Passenger Cars and Motorhomes </b><ul>
<li><b>$56.00 to $259.00* (depending on vehicle age and county of residence)&nbsp;</b></li>
</ul>
Motorcycles <br /><ul>
<li>$25.00 (except Ada County where the fee is $33.00)</li>
</ul>
Boats (Resident) <br /><ul>
<li>$30.00 for boats up to 12 feet (add $2.00 for every foot over 12 feet). Includes Invasive Species Fund fees.</li>
</ul>
Recreational Vehicle Trailers <br /><ul>
<li>$9.00**</li>
</ul>
<ul>
<li>* Vehicles registered in Ada County also pay a $24 to $40 Ada County Highway District Fee.</li>
</ul>
<ul>
<li>** Motorhome and RV trailer owners are required to purchase a Recreational Vehicle sticker. The cost of this sticker is $8.50 for the first $1,000 of market value, and $5.00 for each additional $1,000 or portion thereof of market value. RV stickers are prorated on a quarterly basis for first-time issuance.</li>
</ul>
<br /><b>WHERE TO REGISTER:</b><br /><ul>
<li>You can register your vehicle(s) at any of Idaho's <a href="http://itd.idaho.gov/dmv/VehicleServices/assessor.html">44 County Assessor motor vehicle offices</a> .</li>
</ul>
<ul>
<li>Aircraft registrations are administered by the Idaho Transportation Department's <a href="http://itd.idaho.gov/aero/default.htm">Division of Aeronautics</a> . Call (800) 426-4587 for more information.</li>
</ul>
<br /><br /><br /><span style="font-size: 18.72px; font-weight: bold;">Titling Vehicles in Idaho (<a href="http://itd.idaho.gov/dmv/VehicleServices/titles1.html" target="_blank">HERE</a>)</span><br /><br /><b>TITLING PROCEDURE:</b><br /><blockquote class="tr_bq">
<i>If an Idaho resident purchases a vehicle from an Idaho dealer, that dealer will prepare an application for title for the owner and file it with the Idaho Transportation Department (ITD) or a <a href="http://itd.idaho.gov/dmv/VehicleServices/assessor.html">county assessor motor vehicle office</a> within 30 days of delivery.&nbsp;</i></blockquote>
<blockquote class="tr_bq">
<i>If the vehicle was purchased from an out-of-state dealer or from a private party, and a financial institution is recording a lien, they may file the application for title.</i><i>&nbsp;</i></blockquote>
<blockquote class="tr_bq">
<i>Otherwise the buyer must file the following documents with a county assessor’s motor vehicle office within 30 days of transfer to avoid a $20.00 late-filing penalty:</i></blockquote>
<div>
<br /><b>1. Title (for used vehicles)</b> - must be properly released by the previous owner and lienholder (if any), or Manufacturer's Certificate of Origin (for new vehicles) - must be properly released by the dealer and assigned to the owner<br /><br /><b>2. <a href="http://itd.idaho.gov/dmv/VehicleServices/documents/3738.pdf">Bill of Sale</a></b> - must include vehicle description, sales price, buyer’s full legal name, original signature of seller, and date. A bill of sale is not required if the seller has entered the sales price on the title in a space dedicated for this information.<br /><br /><b>3. Odometer Disclosure </b>- required for any transfer of a motor vehicle less than 10 years old and under 16,000 lbs. G.V.W. Disclosure must be entered on the title.<br /><br /><b>4. <a href="http://itd.idaho.gov/dmv/VehicleServices/documents/3403.pdf">Vehicle Identification Number Inspection</a></b> - completed by an officer of the law, DMV employee, military police officer, or Idaho licensed vehicle dealer. (Out-of-state lienholders: If the vehicle and owner are in Idaho, the Vehicle Identification Number inspection can often be performed by the County Assessor’s office, Sheriff’s office, or City Police Department where the owner resides.)<br /><br /><b>5. Fees </b>- A. Sales tax equal to 6% of the purchase price (minus trade-in if purchased from a licensed dealer), or documentation that at least 6% sales tax was paid to the state of purchase or that the vehicle was purchased at least three months prior to the date the purchaser moved to Idaho. (The latter exemption does not apply to businesses bringing vehicles to Idaho from a non-taxing state.) In most cases, a taxing state’s title issued in the applicant’s name is sufficient documentation that tax was paid at that state’s tax rate.<br /><b><br />B. Title fee - $14.00</b><br /><br /><b>C. Registration fee (see <a href="http://itd.idaho.gov/dmv/VehicleServices/registr.html">Registering Vehicles in Idaho Fact Sheet</a>).</b><br /><br /><b>6. <a href="http://itd.idaho.gov/dmv/VehicleServices/documents/3368.pdf">Power of Attorney</a> </b>- include if applying for a title with a county assessor’s motor vehicle office through the mail. This authorizes the County Assessor to sign the application for the owner. The Power of Attorney must fully describe the vehicle and be signed by the owner/applicant.<br /><br /><span style="background-color: yellow;"><b>7. Title Application (optional) -</b> Out-of-state dealers, lienholders, and leasing companies may prepare.</span><br /><br /><b>RECORDING LIENS:</b><br />To record a lien on an existing Idaho title, the lienholder name and address must be printed in the new lienholder section of the title.&nbsp;</div>
<div>
<br /></div>
<div>
The title and an $14.00 fee may be mailed directly to the Idaho Transportation Department, Vehicle Services Section, at Post Office Box 34, Boise, Idaho 83731-0034, or submitted to your <a href="http://itd.idaho.gov/dmv/VehicleServices/assessor.html">local county assessor’s motor vehicle office</a>.<br /><br /><br /><b>ADDITIONAL INFORMATION</b><br />You may obtain additional information regarding titles by contacting the <a href="http://itd.idaho.gov/dmv/VehicleServices/assessor.html">county assessor</a> in the county where the vehicle will be registered.&nbsp;</div>
<div>
<br /></div>
<div>
You may also contact ITD between the hours of 8:30 A.M. to 5:00 P.M., Mountain Time, at (208) 334-8663 (for registration information, see the <a href="http://itd.idaho.gov/dmv/VehicleServices/registr.html">Vehicle Registering Fact Sheet</a>).&nbsp;</div>
<div>
<br /></div>
<div>
Additional information and forms are also available on ITD’s web site at <a href="http://dmv.idaho.gov/">dmv.idaho.gov</a>.<br /><br /><br /><br /><br />Darrell</div>
</div>
