---
title: 'Kaylee'
date: '2011-04-19T15:02:00.0000000+00:00'
draft: true
blogger_blog: 'Kaylee Debra Wolfe - Journal'
blogger_status: 'LIVE'
blogger_post_id: '386739562244707142'
blogger_filename: '/2011/04/kaylee.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Kaylee Debra Wolfe - Journal/feed.atom'
---

You are getting so Big. I see you on Skype with Grammie Debbie and I am amazed at how grown up you seem sometimes. You have had&nbsp;a hard time. I know you don't understand this now at 6 but we do want you out here, more than anything! Your Grammie Billey pushed and shoved and got lawyers and fought us tooth and nail to take you even though we know it's not the best thing for you. God told us before you turned three that you would come to live with us and we were to be there for you as parents. I already feel you are my daughter, long lost daughter. I really want you out here. God is working on it. We realized that the harder we pushed after your Mom and Dad died the more it didnt feel right. Billey needed you there. Debbie is just as bad about having you around. So maybe it is best, for the moment, that they have you there. I'm still learning things that will make me a better Dad for your unique needs. I look forward to you coming out here someday, I know God will work out exactly what he said He would. His word always comes to pass, even if it looks like it's delayed. I look forward to having you here. I pray for you evey night. I love you, daughter, Dad-2.