---
title: 'Coming to Light'
date: '2012-05-23T13:19:00.0010000+00:00'
draft: true
blogger_blog: 'Kaylee Debra Wolfe - Journal'
blogger_status: 'LIVE'
blogger_post_id: '2298063759806407007'
blogger_filename: '/2012/05/coming-to-light.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Kaylee Debra Wolfe - Journal/feed.atom'
categories:
  - 'Events'
  - 'Prayer'
---

So many things have happened in the last few years. Over the last year or two as we prayed about things we've seen an&nbsp;intensifying&nbsp;of bad things coming. We started praying over you regarding it and this was the Word of God given regarding you:<br />
<blockquote class="tr_bq" style="text-align: center;">
<b>Everything is coming to light!</b></blockquote>
We didn't know what that meant... Well, now I do... I'm sad to say. Your grandfather has been arrested, I'm hoping that he didn't touch you, you haven't said that he did, I think Ari and Loren have stood in the way of that for now. We've been praying protection over you. Still, even with this CPS refuses to take you all out of that house of insanity. There is, however, a new person assigned to the case, he is a God fearing man. We're praying that he can find the just cause and get you out of there pronto! He's tied up right now due to loop holes in the law. Billie brought that man to your graduation even though he was supposed to stay miles away from all of you. But because the CPS worker wasn't there to document it we were unable to press the issue. So he has agreed to do random surprise visits to your Grandma Billies and other places he knows she might be. She has removed most of us from Facebook and stopped taking our calls. She blocked our numbers.<br />
<br />
Even though Grandma Debbie has visiting rights Billie told her not to call anymore. That WILL NOT STAND! We rebuke this in the name of Jesus and command her to "yield&nbsp;to light or be removed." I'm sorry that you are going through this. I have no natural/legal authority to intervene, but I do have spiritual authority, so I am using that, and I will not make an even more focused effort regarding your situation.<br />
<br />
In prayer last night I had the impression that something would happen in the fall. Maybe in September. Everything comes to light...<br />
<br />
Things started coming to light with this arrest. Now CPS has a better worker on the case. It's just a matter of time now... you will be rescued from your insanity. I'm praying that you will be protected, not just physically, but&nbsp;mentally&nbsp;and spiritually. I'm praying that you will be filled with the Holy Spirit and Power and Peace and Joy, despite your circumstances.<br />
<br />
We have a room for you here as soon as you are able to come.<br />
<br />
Love you baby girl, Darrell Wolfe (Daddy2)<br />
<br />