---
title: 'About You'
date: '2012-05-23T15:29:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Connor David Wolfe - Journal'
blogger_status: 'LIVE'
blogger_page_id: '3709267637290710352'
blogger_filename: '/p/about-you.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Connor David Wolfe - Journal/feed.atom'
---

<br />
<b><br class="Apple-interchange-newline" />Connor David Wolfe</b><br />
<b>Born 01/19/2005</b><br />
<b><br /></b><br />
<b>Wolfe Lover - Beloved - Faith in Adversity</b><br />
<br />
<ul>
<li><b><a href="http://www.thinkbabynames.com/meaning/1/Connor">http://www.thinkbabynames.com/meaning/1/Connor</a>
</b></li>
<li><a href="http://www.babycenter.com/baby-names-connor-1091.htm">http://www.babycenter.com/baby-names-connor-1091.htm</a>
</li>
<ul>
<li><b style="background-color: white; font-family: Verdana; font-size: 11px;">Connor</b><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;</span><span style="background-color: white; font-family: Verdana; font-size: smaller;">\c(on)-<a href="http://www.thinkbabynames.com/ending/1/nor" style="color: blue;">nor</a>\</span><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;as a boy's name is pronounced&nbsp;</span><i style="background-color: white; font-family: Verdana; font-size: 11px;">KAH-ner</i><span style="background-color: white; font-family: Verdana; font-size: 11px;">. It is of&nbsp;</span><a href="http://www.thinkbabynames.com/search/1/irish" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Irish</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;and&nbsp;</span><a href="http://www.thinkbabynames.com/search/1/gaelic" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Gaelic</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;origin, and the meaning of Connor is "Wolf or&nbsp;</span><a href="http://www.thinkbabynames.com/search/1/hound" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">hound</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">-</span><a href="http://www.thinkbabynames.com/search/1/lover" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">lover</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">". Anglicized form of&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/1/Conchobhar" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Conchobhar</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;(</span><a href="http://www.thinkbabynames.com/search/1/gaelic" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Gaelic</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">), which was the name of a&nbsp;</span><a href="http://www.thinkbabynames.com/search/1/legendary" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">legendary</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;</span><a href="http://www.thinkbabynames.com/search/1/king" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">king</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;of&nbsp;</span><a href="http://www.thinkbabynames.com/search/1/ulster" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Ulster</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;who lived at the time of&nbsp;</span><a href="http://www.thinkbabynames.com/search/1/christ" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Christ</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">. See also&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/1/Konnor" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;"><b>Konnor</b></a><span style="background-color: white; font-family: Verdana; font-size: 11px;">.&nbsp;</span><a href="http://www.thinkbabynames.com/search/1/irish" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Irish</a><span style="background-color: white; font-family: Verdana; font-size: 11px;"></span><a href="http://www.thinkbabynames.com/search/1/author" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">author</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;</span><a href="http://www.thinkbabynames.com/meaning/1/Conor" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Conor</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;</span><a href="http://www.thinkbabynames.com/search/1/cruise" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Cruise</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;O'Brien.</span>
</li>
<li><span style="background-color: white; font-family: Verdana; font-size: 11px;"><b>David</b>&nbsp;<span style="font-size: smaller;">\d(a)-<a href="http://www.thinkbabynames.com/ending/1/vid" style="color: blue;">vid</a>\</span>&nbsp;as a boy's name is pronounced&nbsp;<i>DAY-vid</i>. It is of&nbsp;<a href="http://www.thinkbabynames.com/search/1/hebrew" style="color: blue;">Hebrew</a>&nbsp;origin, and the meaning of David is "<a href="http://www.thinkbabynames.com/search/1/beloved" style="color: blue;">beloved</a>".&nbsp;<a href="http://www.thinkbabynames.com/search/1/biblical" style="color: blue;">Biblical</a>: one of the most&nbsp;<a href="http://www.thinkbabynames.com/search/1/remarkable" style="color: blue;">remarkable</a>&nbsp;personalities in the&nbsp;<a href="http://www.thinkbabynames.com/search/1/scriptures" style="color: blue;">Scriptures</a>. David was a&nbsp;<a href="http://www.thinkbabynames.com/search/1/shepherd" style="color: blue;">shepherd</a>,&nbsp;<a href="http://www.thinkbabynames.com/search/1/musician" style="color: blue;">musician</a>,&nbsp;<a href="http://www.thinkbabynames.com/search/1/poet" style="color: blue;">poet</a>,&nbsp;<a href="http://www.thinkbabynames.com/search/1/soldier" style="color: blue;">soldier</a>,&nbsp;<a href="http://www.thinkbabynames.com/search/1/statesman" style="color: blue;">statesman</a>,&nbsp;<a href="http://www.thinkbabynames.com/search/1/prophet" style="color: blue;">prophet</a>, and&nbsp;<a href="http://www.thinkbabynames.com/search/1/king" style="color: blue;">king</a>. He&nbsp;<a href="http://www.thinkbabynames.com/search/1/wrote" style="color: blue;">wrote</a>&nbsp;about half of the&nbsp;<a href="http://www.thinkbabynames.com/search/1/psalms" style="color: blue;">Psalms</a>&nbsp;and very likely&nbsp;<a href="http://www.thinkbabynames.com/search/1/composed" style="color: blue;">composed</a>&nbsp;<a href="http://www.thinkbabynames.com/search/1/music" style="color: blue;">music</a>&nbsp;for them as well. He is the only David mentioned in the&nbsp;<a href="http://www.thinkbabynames.com/search/1/bible" style="color: blue;">Bible</a>; his name occurs there more than a thousand times. Today there are variants of the name in almost every language group.&nbsp;<a href="http://www.thinkbabynames.com/search/1/saint" style="color: blue;">Saint</a>&nbsp;David (<a href="http://www.thinkbabynames.com/search/1/sixth" style="color: blue;">sixth</a>&nbsp;<a href="http://www.thinkbabynames.com/search/1/century" style="color: blue;">century</a>) is the&nbsp;<a href="http://www.thinkbabynames.com/search/1/patron" style="color: blue;">patron</a>&nbsp;<a href="http://www.thinkbabynames.com/search/1/saint" style="color: blue;">saint</a>&nbsp;of&nbsp;<a href="http://www.thinkbabynames.com/search/1/wales" style="color: blue;">Wales</a>. In&nbsp;<a href="http://www.thinkbabynames.com/search/1/scotland" style="color: blue;">Scotland</a>, David was a&nbsp;<a href="http://www.thinkbabynames.com/search/1/royal" style="color: blue;">royal</a>&nbsp;name. See also&nbsp;<a href="http://www.thinkbabynames.com/meaning/1/Dawson" style="color: blue;"><b>Dawson</b></a>&nbsp;and&nbsp;<a href="http://www.thinkbabynames.com/meaning/1/Davion" style="color: blue;"><b>Davion</b></a>.&nbsp;<a href="http://www.thinkbabynames.com/search/1/explorer" style="color: blue;">Explorer</a>&nbsp;David Livingstone;&nbsp;<a href="http://www.thinkbabynames.com/search/1/actor" style="color: blue;">actors</a>&nbsp;David Niven, David Arquette, David Duchovny, David Schwimmer;&nbsp;<a href="http://www.thinkbabynames.com/search/1/baseball" style="color: blue;">baseball</a><a href="http://www.thinkbabynames.com/search/1/celebrity" style="color: blue;">celebrity</a>&nbsp;Dave Winfield; TV&nbsp;<a href="http://www.thinkbabynames.com/search/1/host" style="color: blue;">host</a>&nbsp;David Letterman;&nbsp;<a href="http://www.thinkbabynames.com/search/1/musician" style="color: blue;">musician</a>&nbsp;David Bowie;&nbsp;<a href="http://www.thinkbabynames.com/search/1/soccer" style="color: blue;">soccer</a>&nbsp;<a href="http://www.thinkbabynames.com/search/1/player" style="color: blue;">player</a>&nbsp;David Beckham.
</span></li>
<li><span style="font-family: Verdana;"><span style="font-size: 11px;"><b>Wolfe</b></span></span></li>
<ul>
<li><span style="font-family: Verdana;"><span style="font-size: 11px;">Motto: Fides in Adversis - Faith in Adversity</span></span></li>
<li><span style="font-family: Verdana;"><span style="font-size: 11px;"><a href="http://www.houseofnames.com/wolfe-family-crest">http://www.houseofnames.com/wolfe-family-crest</a>
</span></span></li>
</ul>
</ul>
</ul>
<br />
<b>Favorite Color:&nbsp;</b><br />
<b>Blue and Pink</b><br />
<b><br /></b><br />
<b>Favorite Things:</b><br />
<ul>
<li><b>Hero Factory Guys - MOST favorite! (As Of 05/23/2012)</b></li>
<li>Lego</li>
<li>Thomas Train</li>
<li>Iron Man and War Machine</li>
<li>Atlantis Lego - The Favorite</li>
</ul>
<br />
<br />
<br />
<div style="text-align: center;">
<b>Family:</b></div>
<div style="text-align: center;">
<b><br /></b></div>
<div style="text-align: center;">
<b>Parents:</b></div>
<br />
<ul>
<li>Darrell Glen Wolfe</li>
<ul>
<li>Born 07/15/1980</li>
<li>Graduated from: LOL, Went to College of the Desert</li>
</ul>
</ul>
<ul>
<li>Flavia Antoinette Wolfe (Miller)</li>
<ul>
<li>Born 10/24/1981</li>
<li>Graduated from: Westmont College, Santa Barbara, CA</li>
</ul>
</ul>
<br />
<br />
<br />
<br />
<div style="text-align: center;">
<b>Siblings:</b></div>
Preston Markus Wolfe<br />
Kaylee Debra Wolfe<br />
<br />
<br />
<div style="text-align: center;">
<b>Grandparents</b>:</div>
By Darrell:<br />
<br />
<ul>
<li>Debra Yvonne Tweedy (Previous Last Names: Wolfe/Ford) - Born 07/10/1956</li>
<ul>
<li><a href="https://www.facebook.com/debbie.tweedy/timeline/story?ut=32&amp;wstart=-2649600&amp;wend=1170316799&amp;hash=1809052794663&amp;pagefilter=3" style="background-color: white; color: #3b5998; cursor: pointer; font-family: 'lucida grande', tahoma, verdana, arial, sans-serif; font-size: 11px; line-height: 15px; text-align: left; text-decoration: none;">Graduated from CSUSB</a>&nbsp;2007</li>
<li><span style="background-color: white; color: #3b5998; font-family: 'lucida grande', tahoma, verdana, arial, sans-serif; font-size: 11px; line-height: 15px; text-align: left;">Graduated from Arcadia High School</span>&nbsp;1974</li>
<li>Hometown Arcadia, CA</li>
</ul>
</ul>
<ul>
<li>Michael Craig Wolfe - Born 05/14/1954</li>
<ul>
<li>Hometown West Covina, CA</li>
<li>Graduated From: Azusa University, Claremont School of Heresy (Theology), Cal State Fullerton</li>
</ul>
</ul>
<div>
By Flavia</div>
<ul>
<li>JoAnn Southerland (Miller - ?) - Born 12/30/19??</li>
<ul>
<li>Hometown Aurora Colorado</li>
</ul>
</ul>
<ul>
<li>David Miller &nbsp;???</li>
</ul>
<div>
<br class="Apple-interchange-newline" /></div>