---
title: 'Voting'
date: '2012-02-08T23:11:00.0000000+00:00'
draft: true
blogger_blog: 'LIFE in Review (s)'
blogger_status: 'LIVE'
blogger_post_id: '205376449126839200'
blogger_filename: '/2012/02/voting.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/LIFE in Review (s)/feed.atom'
categories:
  - 'Navigate'
---

<br /><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">For help knowing what county you are in:&nbsp;<a href="http://quickfacts.census.gov/qfd/maps/texas_map.html" target="_blank">http://quickfacts.census.gov/qfd/maps/texas_map.html</a></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;"><br /></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;"><br /></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;"><strong>Election and Voting Information</strong></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Who Represents You?&nbsp;<a data-mce-href="http://www.fyi.legis.state.tx.us/" href="http://www.fyi.legis.state.tx.us/">http://www.fyi.legis.state.tx.us/</a></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Tarrant County:&nbsp;<a data-mce-href="http://tarrantcounty.com/evote/site/default.asp" href="http://tarrantcounty.com/evote/site/default.asp">http://tarrantcounty.com/evote/site/default.asp</a></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Wise County:&nbsp;<a data-mce-href="http://www.co.wise.tx.us/" href="http://www.co.wise.tx.us/">http://www.co.wise.tx.us/</a></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Denton County:&nbsp;<a data-mce-href="http://elections.dentoncounty.com/go.asp?Dept=82" href="http://elections.dentoncounty.com/go.asp?Dept=82">http://elections.dentoncounty.com/go.asp?Dept=82</a></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Parker County:&nbsp;<a data-mce-href="http://co.parker.tx.us/ips/cms" href="http://co.parker.tx.us/ips/cms">http://co.parker.tx.us/ips/cms</a></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Proverbs 14:34 Righteousness exalts a nation</div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Important Links:</div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;"><a data-mce-href="http://texaseagle.org/" href="http://texaseagle.org/">http://texaseagle.org/</a></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;"><a data-mce-href="http://www.heritagealliance.com/" href="http://www.heritagealliance.com/">http://www.heritagealliance.com/</a></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Local Christian Political Movers and Shakers:</div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;"><a data-mce-href="http://richardclough.com/node/145" href="http://richardclough.com/node/145">http://richardclough.com/node/145</a></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;"><a data-mce-href="http://www.jackernest.com/" href="http://www.jackernest.com/">http://www.jackernest.com/</a></div>