---
title: 'Kids Stuff'
date: '2012-02-08T23:00:00.0000000+00:00'
draft: true
blogger_blog: 'LIFE in Review (s)'
blogger_status: 'LIVE'
blogger_post_id: '3245285622430182469'
blogger_filename: '/2012/02/kids-stuff.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/LIFE in Review (s)/feed.atom'
categories:
  - 'Discover'
---

<br /><div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">There are many great things to do with Kids. Many times it's just about finding them. For example you could visit the Fort Worth website for Fort Worth Family Fun to see all about the museums and activities. Many times it's just about getting outside your box.<br /><br /><a href="http://www.yelp.com/topic/fort-worth-where-to-take-the-family" target="_blank">Yelp </a>is a great place to find things to do as well!&nbsp;</div><div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;"><a data-mce-href="http://www.homedepot.com/" href="http://www.homedepot.com/" style="color: #743399;" target="_blank" title="Home Depot">Home Depot&nbsp;</a>and&nbsp;<a data-mce-href="http://www.lowes.com/" href="http://www.lowes.com/" style="color: #743399;" target="_blank" title="Lowes">Lowes&nbsp;</a>both have kids programs on various&nbsp;Saturdays&nbsp;throughout the month for the kids to come and build a project with the parents/guardians. The projects always include a small item to build and the kids will get a logo'd apron with their name on it and safety glasses. They will also&nbsp;receive&nbsp;a pin or patch showing which item they built. Make sure to put these events on your calendar for the&nbsp;nearest&nbsp;<a data-mce-href="http://lowesbuildandgrow.com/" href="http://lowesbuildandgrow.com/" style="color: #743399;" target="_blank" title="Lowes Build and Grow">Lowes Build and Grow</a>&nbsp;and/or&nbsp;<a data-mce-href="http://www.homedepot.com/webapp/wcs/stores/servlet/ContentView?pn=Kids_Workshops&amp;langId=-1&amp;storeId=10051" href="http://www.homedepot.com/webapp/wcs/stores/servlet/ContentView?pn=Kids_Workshops&amp;langId=-1&amp;storeId=10051" style="color: #743399;" target="_blank" title="Home Depot Kids Workshop">Home Depot Kids Workshop</a>&nbsp;near you.<br />Another local favorite is the&nbsp;<a data-mce-href="http://www.stockyardsstationdfw.com/lp/Stockyards_Station" href="http://www.stockyardsstationdfw.com/lp/Stockyards_Station" style="color: #743399;" target="_blank" title="Fort Worth Stockyards">Fort Worth Stockyards</a>. There are real cowboys with longhorn cattle. There are shops and food with an old Texas flare. Barbecue flavors and an old-time railroad train that come right through the middle of the shops.</div><div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">If you are looking for the ultimate playtime&nbsp;playground&nbsp;adventure look no further than "<a data-mce-href="http://txliving.wordpress.com/2011/10/04/going-bonkers/" href="http://txliving.wordpress.com/2011/10/04/going-bonkers/" style="color: #743399;" target="_blank">Going Bonkers</a>". An inexpensive indoor playground with multiple levels of climbing for all ages.</div><div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">You could go to the many great parks located in the area. For outdoor hiking that not as many people go to but everyone should try&nbsp;<a data-mce-href="http://www.trwd.com/EagleMountainPark.aspx" href="http://www.trwd.com/EagleMountainPark.aspx" style="color: #743399;" target="_blank">Eagle Mountain Park</a>. While you are there you could check out&nbsp;<a data-mce-href="http://www.texasoutside.com/txorails/public/reviews/show_lake/40" href="http://www.texasoutside.com/txorails/public/reviews/show_lake/40" style="color: #743399;" target="_blank">Eagle Mountain Lake</a>&nbsp;for other lake activities.</div><div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">The&nbsp;<a data-mce-href="http://www.fwmuseum.org/" href="http://www.fwmuseum.org/" style="color: #743399;" target="_blank">Fort Worth Museum</a>&nbsp;and the&nbsp;<a data-mce-href="http://www.natureandscience.org/" href="http://www.natureandscience.org/" style="color: #743399;" target="_blank">Dallas Museum</a>&nbsp;are also great kid activities. However, as a word of caution, the Fort Worth Museum required you to pay to park and for entry&nbsp;separately&nbsp;while the Dallas Museum has free parking and it's larger. The Fort Worth Museum may be a bit more interactive for the kids though. Both are worth trying once and comparing.</div><div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">If you are a sports fan there are the&nbsp;<a data-mce-href="http://texas.rangers.mlb.com/index.jsp?c_id=tex" href="http://texas.rangers.mlb.com/index.jsp?c_id=tex" style="color: #743399;" target="_blank">Texas Rangers</a>,&nbsp;<a data-mce-href="http://www.dallascowboys.com/" href="http://www.dallascowboys.com/" style="color: #743399;" target="_blank">Dallas Cowboys</a>,&nbsp;<a data-mce-href="http://www.nba.com/mavericks/index_main.html" href="http://www.nba.com/mavericks/index_main.html" style="color: #743399;" target="_blank">Dallas Mavericks</a>, and&nbsp;<a data-mce-href="http://stars.nhl.com/" href="http://stars.nhl.com/" style="color: #743399;" target="_blank">Dallas Stars</a>. Then of course you have all your college football teams like&nbsp;<a data-mce-href="http://gofrogs.cstv.com/sports/m-footbl/tcu-m-footbl-body.html" href="http://gofrogs.cstv.com/sports/m-footbl/tcu-m-footbl-body.html" style="color: #743399;" target="_blank">TCU</a>,&nbsp;<a data-mce-href="http://www.texassports.com/" href="http://www.texassports.com/" style="color: #743399;" target="_blank">TU</a>,&nbsp;<a data-mce-href="http://www.meangreensports.com/SportSelect.dbml?DB_OEM_ID=1800&amp;SPID=562&amp;SPSID=9058" href="http://www.meangreensports.com/SportSelect.dbml?DB_OEM_ID=1800&amp;SPID=562&amp;SPSID=9058" style="color: #743399;" target="_blank">UNT</a>, and more.</div><div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">For more great ideas see our&nbsp;Category&nbsp;Cloud titled: Texas Living Information and click on "<a data-mce-href="http://txliving.wordpress.com/category/kids/" href="http://txliving.wordpress.com/category/kids/" style="color: #743399;" target="_blank">Kids</a>", for up to date articles and reviews and places to take the&nbsp;<a data-mce-href="http://txliving.wordpress.com/category/kids/" href="http://txliving.wordpress.com/category/kids/" style="color: #743399;" target="_blank">kids</a>&nbsp;or just&nbsp;<a data-mce-href="http://txliving.wordpress.com/category/kids/" href="http://txliving.wordpress.com/category/kids/" style="color: #743399;" target="_blank">click here</a>.</div><div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;"><strong style="color: black;">Darrell G. Wolfe</strong></div>