---
title: 'Moving with Kids'
date: '2012-02-08T23:09:00.0010000+00:00'
draft: true
blogger_blog: 'LIFE in Review (s)'
blogger_status: 'LIVE'
blogger_post_id: '2957197540583941844'
blogger_filename: '/2012/02/moving-with-kids.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/LIFE in Review (s)/feed.atom'
categories:
  - 'Navigate'
---

<h4><span style="font-family: Trebuchet MS, sans-serif;">Remember the Kids</span></h4><div><span style="font-family: Trebuchet MS, sans-serif;"><br /></span></div><div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">Moving can be a time of uncertainty and excitement for anyone. However for many children the uncertainty can throw them off balance. I remember that each time we have moved, within a city or to another state, my children needed some reassurance. For the young mind home is home. They don't understand how we could leave one home to go to another because that is THEIR home! Even when we left a small two bedroom apartment to a larger four bedroom house with a backyard, my oldest would ask why we couldn't visit our old house.</div><div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">When we left California to come to Texas we decided for budget reasons to take the Amtrak. My loving wife made it quite the adventure for them.They loved Thomas the Train and now they would go on a train. We brought toys and video players. We watched the country go by out of the observatory windows.</div><div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">Once we arrived, the very first thing we did when settling in was to get their rooms in order. Once they had a settled room they were more settled and we could focus on the rest of the apartment.</div><div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">Take time to understand that kids cannot always see the big picture and just need a sense of normalcy in their life. Help them settle in to the idea, prepare them ahead of time, make it a grand adventure. See below for tips that helped us:</div><div style="color: #333333; margin-bottom: 24px;"><h4><span style="font-family: Trebuchet MS, sans-serif;">Links to tips for Moving with Kids</span></h4></div><ul style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; list-style-image: initial; list-style-position: initial; margin: 0px 0px 24px 0em; padding: 0px 0px 0px 1em;"><li><a data-mce-href="http://diane-laney-fitzpatrick.suite101.com/how-to-move-with-children-a16895" href="http://diane-laney-fitzpatrick.suite101.com/how-to-move-with-children-a16895" style="color: #743399;" target="_blank" title="10 Tips for relocating with kids">10 Tips for relocating with kids.&nbsp;</a></li><li><a data-mce-href="http://www.leslielevine.com/books.html" href="http://www.leslielevine.com/books.html" style="color: #743399;" target="_blank" title="Leslie Levine Communications">Information from Leslie Levine Communications:</a></li><li><a data-mce-href="http://www.emic.org/downloads_all.php?cat=10" href="http://www.emic.org/downloads_all.php?cat=10" style="color: #743399;" target="_blank">Eagle Mountain International Church &nbsp;Relocation Guide</a>&nbsp;had the following to say:</li></ul><pre style="background-color: #eeeeee; border: 0.1em solid rgb(221, 221, 221); color: #222222; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 15px; line-height: 21px; margin-bottom: 24px; padding: 1.5em;">CHILDREN AND RELOCATION<br />Moving can be a tumultuous time for all involved, but<br />especially so for children. Your kids will look to you for clues<br />on how to deal with their emotions and settle in to your new<br />home. You can help your child adjust more easily by<br />incorporating a few of the following suggestions into your<br />family’s routine:<br />• Encourage your children to openly discuss their feelings about the move,<br />their new home, new school or anything else that concerns them.<br />• Listen to their fears and reassure them that you understand their feelings.<br />• Be honest with your own feelings about the move, but try to keep a positive<br />attitude. Your kids will sense your inner feelings about this lifestyle<br />change.<br />• Subscribe to a magazine of your child’s choice. Receiving mail addressed<br />in his name will help him feel at home in unfamiliar surroundings.<br />• Take your child’s artwork from your old refrigerator and place it<br />prominently on the new one. This act of love will give him a sense of<br />consistency and normalcy.<br /><a data-mce-href="http://www.amazon.com/Will-This-Place-Ever-Updated/dp/0658020986" href="http://www.amazon.com/Will-This-Place-Ever-Updated/dp/0658020986" style="color: #743399;" target="_blank" title="Buy from Amazon">This information was obtained from Will This Place Ever Feel Like Home? By Leslie Levine, published by Real Estate Education Company, 1998.</a></pre>