---
title: 'Fasting/Vegetarian Lifestyle: Four Month Test, Doctor''s Orders'
date: '2020-06-10T21:40:00.0000000+00:00'
draft: true
blogger_blog: 'LIFE in Review (s)'
blogger_status: 'LIVE'
blogger_post_id: '6165247110338030150'
blogger_filename: '/2020/06/fastingvegetarian-lifestyle-four-month.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/LIFE in Review (s)/feed.atom'
---

<div class="MsoNormal">It's been quite a few years since I posted here. I'd laid down this project and now I'm giving it new life. It used to be a "review" site where I could post restaurant reviews, which I'll probably do more of in the future. But now I'm thinking I'll use it for the food research I've been doing and also include reviews of products, books, and anything else I've seen. It's going to be my Food and Lifestyle Journal.&nbsp;</div><div class="MsoNormal"><br /></div><div class="MsoNormal">I did a Whole30 in January 2020 and saw tremendous results (honestly, I'll probably go back to Whole30 when this next test phase is complete). But my doctor has a new plan he wants me to try, so I'm game for a new test. I need to incorporate more veggies anyway, so, here it is.&nbsp;</div><div class="MsoNormal"><br /></div><div class="MsoNormal">This week, after making fun of my Girlfriend for being a vegetarian, my Doctor asked me to do a strict Fasting/Vegetarian lifestyle for four months. I'm up for the challenge, so I'm pursuing it. Here's what he said to do:</div><div class="MsoNormal"><br /></div><div class="MsoNormal"><b>Plan</b>:</div><div class="MsoNormal"><br /></div><div class="MsoNormal">Total Vegetarian Diet: No red meat, fish, birds, or dairy.</div><div class="MsoNormal"><br /></div><div class="MsoNormal">Start by fasting two days (I have done a lot of research on fasting and it's benefits, I'll do three). I asked him about putting me into Ketosis, he said that this isn't that. But I disagree. The WHOLE point of fasting is to put the body into a state of Ketosis (switching over to using Ketones as a fuel source instead of Glucose). That's how they first discovered Ketosis in the first place. So I'll do three days, because three days is required to see real benefits of fasting.&nbsp;</div><div class="MsoNormal"><br /></div><div class="MsoNormal">2 Meals (ONLY) Daily: Meal 1 and Meal 2. Nothing after 2p. No Snacking.&nbsp;</div><div class="MsoNormal">No Caffeine/Alcohol</div><div class="MsoNormal">Herbal Tea okay</div><div class="MsoNormal"><br /></div><div class="MsoNormal">Meals should include:</div><div class="MsoNormal">Beans (no sauces or condiments)</div><div class="MsoNormal">All Veggies (Limit: Corn, Potatoes, Winter Squash)</div><div class="MsoNormal">Small Fruit, only at Meal 1.</div><div class="MsoNormal"><br /></div><div class="MsoNormal">Fast 1-day per week.&nbsp;</div><div class="MsoNormal"><br /></div><div class="MsoNormal">Exercise Moderate Level: Heavy Breathing, able to talk but in short bursts. One hour, either daily or, in 15-minute bursts.&nbsp;</div><div class="MsoNormal"><br /></div><div class="MsoNormal">Suggested checking out for exercise:&nbsp;<a href="https://www.pauleugene.com/">https://www.pauleugene.com/</a></div><div class="MsoNormal"><br /></div><div class="MsoNormal">Books Suggestions:&nbsp;</div><div class="MsoNormal"><a href="https://www.amazon.com/Victory-Christ-Charles-G-Trumbull/dp/0875085334/ref=sr_1_2?dchild=1&amp;keywords=victory+in+christ&amp;qid=1591824905&amp;sr=8-2" target="_blank">Victory in Christ</a></div><div class="MsoNormal"><a href="https://www.amazon.com/Goodbye-Diabetes-Dr-Wes-Youngberg/dp/187804642X/ref=sr_1_1?dchild=1&amp;keywords=goodbye+diabetes&amp;qid=1591824971&amp;sr=8-1" target="_blank">Goodbye Diabetes, by Wes Youngerberg</a></div><div class="MsoNormal"><br /></div><div class="MsoNormal">Suggested Websites:</div><div class="MsoNormal"><a href="https://kickstart.pcrm.org/en">https://kickstart.pcrm.org/en</a></div><div class="MsoNormal"><a href="https://www.newstart.com/">https://www.newstart.com/</a></div><div class="MsoNormal"><br /></div><div class="MsoNormal">Suggested Documentaries:</div><div class="MsoNormal"><br /></div><div class="MsoNormal">On Netflix:</div><div class="MsoNormal">Game Changers</div><div class="MsoNormal">Forks over Knives</div><div class="MsoNormal">Super Size Me</div><div class="MsoNormal">The China Study</div><div class="MsoNormal">Fat, Sick, and Nearly Dead</div><div class="MsoNormal"><br /></div><div class="MsoNormal">Blue Zones, by National Georaphic</div><div class="MsoNormal">Dr Ellsworth Wareham Loma Linda</div><div class="MsoNormal"><br /></div><div class="MsoNormal">Addressing the following:</div><div class="MsoNormal">Nutrition</div><div class="MsoNormal">Exercise</div><div class="MsoNormal">Water</div><div class="MsoNormal">Sunshine</div><div class="MsoNormal">Temperance</div><div class="MsoNormal">Air</div><div class="MsoNormal">Rest</div><div class="MsoNormal">Trust in Divine Power</div><div class="MsoNormal">NEWSTART</div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div>
