---
title: 'Signature/Template'
date: '2050-06-12T23:44:00.0000000+00:00'
draft: true
blogger_blog: 'LIFE in Review (s)'
blogger_status: 'DRAFT'
blogger_post_id: '8141412457595684879'
blogger_filename: '/2050/06/signaturetemplate.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/LIFE in Review (s)/feed.atom'
---

<br />
<h3 style="font-family: Georgia; margin: 0in;">
<br />&nbsp;</h3>
<h3 style="font-family: Georgia; margin: 0in;">
Name</h3>
<h3 style="font-family: Georgia; margin: 0in;">
&nbsp;</h3>
<h4 style="font-family: Georgia; margin: 0in;">
Adress</h4>
<br />
<div style="font-family: Georgia; margin: 0in;">
Where is it?<br />
<br /></div>
<div style="font-family: Georgia; margin: 0in;">
Yelp:&nbsp;<a href="http://www.yelp.com/biz/mai-thai-haslet">HERE</a><br />
Urban Spoon:&nbsp;<a href="http://www.urbanspoon.com/r/13/1590824/restaurant/Mai-Thai-Restaurant-Haslet">HERE</a></div>
<div style="font-family: Georgia; margin: 0in;">
<br /></div>
<div style="font-family: Georgia; margin: 0in;">
<br />
<br />
PICTURE</div>
<div style="font-family: Georgia; margin: 0in;">
<br /></div>
<div style="font-family: Georgia; margin: 0in;">
<br /></div>
<div style="font-family: Georgia; margin: 0in;">
<br /></div>
<div style="font-family: Georgia; margin: 0in;">
<h4>
<span style="font-family: inherit;">Overview</span></h4>
<span style="font-family: inherit;"><br /></span><span style="font-family: inherit;"><br /></span></div>
<div style="font-family: Georgia; margin: 0in;">
<br /></div>
<div style="font-family: Georgia; margin: 0in;">
<h4>
<span style="font-family: inherit;">Cost</span></h4>
</div>
<div style="font-family: Georgia; margin: 0in;">
<br /></div>
<div style="font-family: Georgia; margin: 0in;">
<span style="font-family: inherit;"><br /></span><span style="font-family: inherit;"><br /></span></div>
<div style="font-family: Georgia; margin: 0in;">
<br /></div>
<div style="font-family: Georgia; margin: 0in;">
<br /></div>
<div style="font-family: Georgia; margin: 0in;">
<h4>
<span style="font-family: inherit;">Kids</span></h4>
</div>
<div style="font-family: Georgia; margin: 0in;">
<span style="font-family: inherit;"><br /></span><span style="font-family: inherit;"></span></div>
<div style="font-family: Georgia; margin: 0in;">
<br />
<br />
<br />
<br /></div>
<div style="font-family: Georgia; margin: 0in;">
<h4>
<span style="font-family: inherit;">Final Thoughts</span></h4>
</div>
<div style="font-family: Georgia; margin: 0in;">
<span style="font-family: inherit;"><br /></span><span style="font-family: inherit;"><br /></span><br />
<br />
<br />
<br />
<br />
<br /></div>
<div style="font-family: Georgia; margin: 0in;">
<br /></div>
<div style="text-align: center;">
<h3>
********<br />Disclosures:</h3>
</div>
<div class="MsoNormal">
<b>Note</b>: My standards for service are high. I've spent a lifetime career studying books about providing high-quality service and quality standards. Books like Good to Great (Jim Collins), Raving Fans (Ken Blanchard &amp; Sheldon Bowles), and others have made me hard to impress. That being said, I know my high standards and I try to give each establishment the benefit of the doubt. I try to provide an honest run through my experience. It could have been an unusually good or bad experience, it just was what it was.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<b>My 1-10 Scale Standards</b>&nbsp;(for my own memory so I can try to be consistent)(unless otherwise specified each applies to a single visit and is subject to change, up or down, next visit):<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal" style="margin-left: 27pt; text-indent: -0.25in; vertical-align: middle;">
(1) Awful. They should close.<span style="font-family: &quot;times new roman&quot; , &quot;serif&quot;; font-size: 12pt;"><o:p></o:p></span></div>
<div class="MsoNormal" style="margin-left: 27pt; text-indent: -0.25in; vertical-align: middle;">
(2-3) Mostly bad, but they could recover, probably won't.<span style="font-family: &quot;times new roman&quot; , &quot;serif&quot;; font-size: 12pt;"><o:p></o:p></span></div>
<div class="MsoNormal" style="margin-left: 27pt; text-indent: -0.25in; vertical-align: middle;">
(4-6) Varying degrees of&nbsp; "OK". I'd go again,&nbsp;if need be. I'm what Raving Fans calls "satisfied", which is a euphemism for someone who will choose another place if a better option comes along.<span style="font-family: &quot;times new roman&quot; , &quot;serif&quot;; font-size: 12pt;"><o:p></o:p></span></div>
<div class="MsoNormal" style="margin-left: 27pt; text-indent: -0.25in; vertical-align: middle;">
(7-8) I'm a Fan. Not a raving fan, yet, but a fan. I like. I'd go again. If asked where I want to go, this might show up on the list.<span style="font-family: &quot;times new roman&quot; , &quot;serif&quot;; font-size: 12pt;"><o:p></o:p></span></div>
<div class="MsoNormal" style="margin-left: 27pt; text-indent: -0.25in; vertical-align: middle;">
(9-10) I'm a Raving Fan! There's something special about this place that makes me want to go again and again.<span style="font-family: &quot;times new roman&quot; , &quot;serif&quot;; font-size: 12pt;"><o:p></o:p></span></div>
<div class="MsoNormal" style="margin-left: 27pt; text-indent: -0.25in; vertical-align: middle;">
(11+) Something happened that took my experience so over the top that it doesn't fit on a normal scale.<span style="font-family: &quot;times new roman&quot; , &quot;serif&quot;; font-size: 12pt;"><o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<div class="MsoNormal">
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span><span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a><br />
<br />
https://wolfefamilyreviews.blogspot.com/</div>
</div>
</div>
