---
title: 'Class Assignment: Interpretive Project: John 1:1–18 (LEB)'
date: '2022-02-22T04:37:00.0040000+00:00'
draft: true
blogger_blog: 'NoHiding.Faith'
blogger_status: 'LIVE'
blogger_post_id: '2619487431749921844'
blogger_filename: '/2022/02/test.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/NoHiding.Faith/feed.atom'
categories:
  - 'Class Assignment'
---

<!--[if gte mso 9]><xml>
 <o:OfficeDocumentSettings>
  <o:RelyOnVML/>
  <o:AllowPNG/>
 </o:OfficeDocumentSettings>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <w:WordDocument>
  <w:View>Normal</w:View>
  <w:Zoom>0</w:Zoom>
  <w:TrackMoves/>
  <w:TrackFormatting/>
  <w:PunctuationKerning/>
  <w:ValidateAgainstSchemas/>
  <w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>
  <w:IgnoreMixedContent>false</w:IgnoreMixedContent>
  <w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>
  <w:DoNotPromoteQF/>
  <w:LidThemeOther>EN-US</w:LidThemeOther>
  <w:LidThemeAsian>X-NONE</w:LidThemeAsian>
  <w:LidThemeComplexScript>HE</w:LidThemeComplexScript>
  <w:Compatibility>
   <w:BreakWrappedTables/>
   <w:SnapToGridInCell/>
   <w:WrapTextWithPunct/>
   <w:UseAsianBreakRules/>
   <w:DontGrowAutofit/>
   <w:SplitPgBreakAndParaMark/>
   <w:EnableOpenTypeKerning/>
   <w:DontFlipMirrorIndents/>
   <w:OverrideTableStyleHps/>
   <w:UseFELayout/>
  </w:Compatibility>
  <m:mathPr>
   <m:mathFont m:val="Cambria Math"/>
   <m:brkBin m:val="before"/>
   <m:brkBinSub m:val="&#45;-"/>
   <m:smallFrac m:val="off"/>
   <m:dispDef/>
   <m:lMargin m:val="0"/>
   <m:rMargin m:val="0"/>
   <m:defJc m:val="centerGroup"/>
   <m:wrapIndent m:val="1440"/>
   <m:intLim m:val="subSup"/>
   <m:naryLim m:val="undOvr"/>
  </m:mathPr></w:WordDocument>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <w:LatentStyles DefLockedState="false" DefUnhideWhenUsed="false"
  DefSemiHidden="false" DefQFormat="false" DefPriority="99"
  LatentStyleCount="376">
  <w:LsdException Locked="false" Priority="0" QFormat="true" Name="Normal"/>
  <w:LsdException Locked="false" Priority="9" QFormat="true" Name="heading 1"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 2"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 3"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 4"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 5"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 6"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 7"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 8"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 9"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 6"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 7"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 8"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 9"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 1"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 2"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 3"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 4"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 5"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 6"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 7"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 8"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 9"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Normal Indent"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="footnote text"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="annotation text"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="header"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="footer"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index heading"/>
  <w:LsdException Locked="false" Priority="35" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="caption"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="table of figures"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="envelope address"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="envelope return"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="footnote reference"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="annotation reference"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="line number"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="page number"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="endnote reference"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="endnote text"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="table of authorities"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="macro"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="toa heading"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Bullet"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Number"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Bullet 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Bullet 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Bullet 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Bullet 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Number 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Number 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Number 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Number 5"/>
  <w:LsdException Locked="false" Priority="10" QFormat="true" Name="Title"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Closing"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Signature"/>
  <w:LsdException Locked="false" Priority="1" SemiHidden="true"
   UnhideWhenUsed="true" Name="Default Paragraph Font"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text Indent"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Continue"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Continue 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Continue 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Continue 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Continue 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Message Header"/>
  <w:LsdException Locked="false" Priority="11" QFormat="true" Name="Subtitle"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Salutation"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Date"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text First Indent"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text First Indent 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Note Heading"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text Indent 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text Indent 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Block Text"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Hyperlink"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="FollowedHyperlink"/>
  <w:LsdException Locked="false" Priority="22" QFormat="true" Name="Strong"/>
  <w:LsdException Locked="false" Priority="20" QFormat="true" Name="Emphasis"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Document Map"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Plain Text"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="E-mail Signature"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Top of Form"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Bottom of Form"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Normal (Web)"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Acronym"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Address"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Cite"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Code"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Definition"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Keyboard"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Preformatted"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Sample"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Typewriter"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Variable"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Normal Table"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="annotation subject"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="No List"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Outline List 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Outline List 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Outline List 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Simple 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Simple 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Simple 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Classic 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Classic 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Classic 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Classic 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Colorful 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Colorful 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Colorful 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Columns 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Columns 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Columns 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Columns 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Columns 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 6"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 7"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 8"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 6"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 7"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 8"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table 3D effects 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table 3D effects 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table 3D effects 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Contemporary"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Elegant"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Professional"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Subtle 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Subtle 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Web 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Web 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Web 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Balloon Text"/>
  <w:LsdException Locked="false" Priority="39" Name="Table Grid"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Theme"/>
  <w:LsdException Locked="false" SemiHidden="true" Name="Placeholder Text"/>
  <w:LsdException Locked="false" Priority="1" QFormat="true" Name="No Spacing"/>
  <w:LsdException Locked="false" Priority="60" Name="Light Shading"/>
  <w:LsdException Locked="false" Priority="61" Name="Light List"/>
  <w:LsdException Locked="false" Priority="62" Name="Light Grid"/>
  <w:LsdException Locked="false" Priority="63" Name="Medium Shading 1"/>
  <w:LsdException Locked="false" Priority="64" Name="Medium Shading 2"/>
  <w:LsdException Locked="false" Priority="65" Name="Medium List 1"/>
  <w:LsdException Locked="false" Priority="66" Name="Medium List 2"/>
  <w:LsdException Locked="false" Priority="67" Name="Medium Grid 1"/>
  <w:LsdException Locked="false" Priority="68" Name="Medium Grid 2"/>
  <w:LsdException Locked="false" Priority="69" Name="Medium Grid 3"/>
  <w:LsdException Locked="false" Priority="70" Name="Dark List"/>
  <w:LsdException Locked="false" Priority="71" Name="Colorful Shading"/>
  <w:LsdException Locked="false" Priority="72" Name="Colorful List"/>
  <w:LsdException Locked="false" Priority="73" Name="Colorful Grid"/>
  <w:LsdException Locked="false" Priority="60" Name="Light Shading Accent 1"/>
  <w:LsdException Locked="false" Priority="61" Name="Light List Accent 1"/>
  <w:LsdException Locked="false" Priority="62" Name="Light Grid Accent 1"/>
  <w:LsdException Locked="false" Priority="63" Name="Medium Shading 1 Accent 1"/>
  <w:LsdException Locked="false" Priority="64" Name="Medium Shading 2 Accent 1"/>
  <w:LsdException Locked="false" Priority="65" Name="Medium List 1 Accent 1"/>
  <w:LsdException Locked="false" SemiHidden="true" Name="Revision"/>
  <w:LsdException Locked="false" Priority="34" QFormat="true"
   Name="List Paragraph"/>
  <w:LsdException Locked="false" Priority="29" QFormat="true" Name="Quote"/>
  <w:LsdException Locked="false" Priority="30" QFormat="true"
   Name="Intense Quote"/>
  <w:LsdException Locked="false" Priority="66" Name="Medium List 2 Accent 1"/>
  <w:LsdException Locked="false" Priority="67" Name="Medium Grid 1 Accent 1"/>
  <w:LsdException Locked="false" Priority="68" Name="Medium Grid 2 Accent 1"/>
  <w:LsdException Locked="false" Priority="69" Name="Medium Grid 3 Accent 1"/>
  <w:LsdException Locked="false" Priority="70" Name="Dark List Accent 1"/>
  <w:LsdException Locked="false" Priority="71" Name="Colorful Shading Accent 1"/>
  <w:LsdException Locked="false" Priority="72" Name="Colorful List Accent 1"/>
  <w:LsdException Locked="false" Priority="73" Name="Colorful Grid Accent 1"/>
  <w:LsdException Locked="false" Priority="60" Name="Light Shading Accent 2"/>
  <w:LsdException Locked="false" Priority="61" Name="Light List Accent 2"/>
  <w:LsdException Locked="false" Priority="62" Name="Light Grid Accent 2"/>
  <w:LsdException Locked="false" Priority="63" Name="Medium Shading 1 Accent 2"/>
  <w:LsdException Locked="false" Priority="64" Name="Medium Shading 2 Accent 2"/>
  <w:LsdException Locked="false" Priority="65" Name="Medium List 1 Accent 2"/>
  <w:LsdException Locked="false" Priority="66" Name="Medium List 2 Accent 2"/>
  <w:LsdException Locked="false" Priority="67" Name="Medium Grid 1 Accent 2"/>
  <w:LsdException Locked="false" Priority="68" Name="Medium Grid 2 Accent 2"/>
  <w:LsdException Locked="false" Priority="69" Name="Medium Grid 3 Accent 2"/>
  <w:LsdException Locked="false" Priority="70" Name="Dark List Accent 2"/>
  <w:LsdException Locked="false" Priority="71" Name="Colorful Shading Accent 2"/>
  <w:LsdException Locked="false" Priority="72" Name="Colorful List Accent 2"/>
  <w:LsdException Locked="false" Priority="73" Name="Colorful Grid Accent 2"/>
  <w:LsdException Locked="false" Priority="60" Name="Light Shading Accent 3"/>
  <w:LsdException Locked="false" Priority="61" Name="Light List Accent 3"/>
  <w:LsdException Locked="false" Priority="62" Name="Light Grid Accent 3"/>
  <w:LsdException Locked="false" Priority="63" Name="Medium Shading 1 Accent 3"/>
  <w:LsdException Locked="false" Priority="64" Name="Medium Shading 2 Accent 3"/>
  <w:LsdException Locked="false" Priority="65" Name="Medium List 1 Accent 3"/>
  <w:LsdException Locked="false" Priority="66" Name="Medium List 2 Accent 3"/>
  <w:LsdException Locked="false" Priority="67" Name="Medium Grid 1 Accent 3"/>
  <w:LsdException Locked="false" Priority="68" Name="Medium Grid 2 Accent 3"/>
  <w:LsdException Locked="false" Priority="69" Name="Medium Grid 3 Accent 3"/>
  <w:LsdException Locked="false" Priority="70" Name="Dark List Accent 3"/>
  <w:LsdException Locked="false" Priority="71" Name="Colorful Shading Accent 3"/>
  <w:LsdException Locked="false" Priority="72" Name="Colorful List Accent 3"/>
  <w:LsdException Locked="false" Priority="73" Name="Colorful Grid Accent 3"/>
  <w:LsdException Locked="false" Priority="60" Name="Light Shading Accent 4"/>
  <w:LsdException Locked="false" Priority="61" Name="Light List Accent 4"/>
  <w:LsdException Locked="false" Priority="62" Name="Light Grid Accent 4"/>
  <w:LsdException Locked="false" Priority="63" Name="Medium Shading 1 Accent 4"/>
  <w:LsdException Locked="false" Priority="64" Name="Medium Shading 2 Accent 4"/>
  <w:LsdException Locked="false" Priority="65" Name="Medium List 1 Accent 4"/>
  <w:LsdException Locked="false" Priority="66" Name="Medium List 2 Accent 4"/>
  <w:LsdException Locked="false" Priority="67" Name="Medium Grid 1 Accent 4"/>
  <w:LsdException Locked="false" Priority="68" Name="Medium Grid 2 Accent 4"/>
  <w:LsdException Locked="false" Priority="69" Name="Medium Grid 3 Accent 4"/>
  <w:LsdException Locked="false" Priority="70" Name="Dark List Accent 4"/>
  <w:LsdException Locked="false" Priority="71" Name="Colorful Shading Accent 4"/>
  <w:LsdException Locked="false" Priority="72" Name="Colorful List Accent 4"/>
  <w:LsdException Locked="false" Priority="73" Name="Colorful Grid Accent 4"/>
  <w:LsdException Locked="false" Priority="60" Name="Light Shading Accent 5"/>
  <w:LsdException Locked="false" Priority="61" Name="Light List Accent 5"/>
  <w:LsdException Locked="false" Priority="62" Name="Light Grid Accent 5"/>
  <w:LsdException Locked="false" Priority="63" Name="Medium Shading 1 Accent 5"/>
  <w:LsdException Locked="false" Priority="64" Name="Medium Shading 2 Accent 5"/>
  <w:LsdException Locked="false" Priority="65" Name="Medium List 1 Accent 5"/>
  <w:LsdException Locked="false" Priority="66" Name="Medium List 2 Accent 5"/>
  <w:LsdException Locked="false" Priority="67" Name="Medium Grid 1 Accent 5"/>
  <w:LsdException Locked="false" Priority="68" Name="Medium Grid 2 Accent 5"/>
  <w:LsdException Locked="false" Priority="69" Name="Medium Grid 3 Accent 5"/>
  <w:LsdException Locked="false" Priority="70" Name="Dark List Accent 5"/>
  <w:LsdException Locked="false" Priority="71" Name="Colorful Shading Accent 5"/>
  <w:LsdException Locked="false" Priority="72" Name="Colorful List Accent 5"/>
  <w:LsdException Locked="false" Priority="73" Name="Colorful Grid Accent 5"/>
  <w:LsdException Locked="false" Priority="60" Name="Light Shading Accent 6"/>
  <w:LsdException Locked="false" Priority="61" Name="Light List Accent 6"/>
  <w:LsdException Locked="false" Priority="62" Name="Light Grid Accent 6"/>
  <w:LsdException Locked="false" Priority="63" Name="Medium Shading 1 Accent 6"/>
  <w:LsdException Locked="false" Priority="64" Name="Medium Shading 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="65" Name="Medium List 1 Accent 6"/>
  <w:LsdException Locked="false" Priority="66" Name="Medium List 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="67" Name="Medium Grid 1 Accent 6"/>
  <w:LsdException Locked="false" Priority="68" Name="Medium Grid 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="69" Name="Medium Grid 3 Accent 6"/>
  <w:LsdException Locked="false" Priority="70" Name="Dark List Accent 6"/>
  <w:LsdException Locked="false" Priority="71" Name="Colorful Shading Accent 6"/>
  <w:LsdException Locked="false" Priority="72" Name="Colorful List Accent 6"/>
  <w:LsdException Locked="false" Priority="73" Name="Colorful Grid Accent 6"/>
  <w:LsdException Locked="false" Priority="19" QFormat="true"
   Name="Subtle Emphasis"/>
  <w:LsdException Locked="false" Priority="21" QFormat="true"
   Name="Intense Emphasis"/>
  <w:LsdException Locked="false" Priority="31" QFormat="true"
   Name="Subtle Reference"/>
  <w:LsdException Locked="false" Priority="32" QFormat="true"
   Name="Intense Reference"/>
  <w:LsdException Locked="false" Priority="33" QFormat="true" Name="Book Title"/>
  <w:LsdException Locked="false" Priority="37" SemiHidden="true"
   UnhideWhenUsed="true" Name="Bibliography"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="TOC Heading"/>
  <w:LsdException Locked="false" Priority="41" Name="Plain Table 1"/>
  <w:LsdException Locked="false" Priority="42" Name="Plain Table 2"/>
  <w:LsdException Locked="false" Priority="43" Name="Plain Table 3"/>
  <w:LsdException Locked="false" Priority="44" Name="Plain Table 4"/>
  <w:LsdException Locked="false" Priority="45" Name="Plain Table 5"/>
  <w:LsdException Locked="false" Priority="40" Name="Grid Table Light"/>
  <w:LsdException Locked="false" Priority="46" Name="Grid Table 1 Light"/>
  <w:LsdException Locked="false" Priority="47" Name="Grid Table 2"/>
  <w:LsdException Locked="false" Priority="48" Name="Grid Table 3"/>
  <w:LsdException Locked="false" Priority="49" Name="Grid Table 4"/>
  <w:LsdException Locked="false" Priority="50" Name="Grid Table 5 Dark"/>
  <w:LsdException Locked="false" Priority="51" Name="Grid Table 6 Colorful"/>
  <w:LsdException Locked="false" Priority="52" Name="Grid Table 7 Colorful"/>
  <w:LsdException Locked="false" Priority="46"
   Name="Grid Table 1 Light Accent 1"/>
  <w:LsdException Locked="false" Priority="47" Name="Grid Table 2 Accent 1"/>
  <w:LsdException Locked="false" Priority="48" Name="Grid Table 3 Accent 1"/>
  <w:LsdException Locked="false" Priority="49" Name="Grid Table 4 Accent 1"/>
  <w:LsdException Locked="false" Priority="50" Name="Grid Table 5 Dark Accent 1"/>
  <w:LsdException Locked="false" Priority="51"
   Name="Grid Table 6 Colorful Accent 1"/>
  <w:LsdException Locked="false" Priority="52"
   Name="Grid Table 7 Colorful Accent 1"/>
  <w:LsdException Locked="false" Priority="46"
   Name="Grid Table 1 Light Accent 2"/>
  <w:LsdException Locked="false" Priority="47" Name="Grid Table 2 Accent 2"/>
  <w:LsdException Locked="false" Priority="48" Name="Grid Table 3 Accent 2"/>
  <w:LsdException Locked="false" Priority="49" Name="Grid Table 4 Accent 2"/>
  <w:LsdException Locked="false" Priority="50" Name="Grid Table 5 Dark Accent 2"/>
  <w:LsdException Locked="false" Priority="51"
   Name="Grid Table 6 Colorful Accent 2"/>
  <w:LsdException Locked="false" Priority="52"
   Name="Grid Table 7 Colorful Accent 2"/>
  <w:LsdException Locked="false" Priority="46"
   Name="Grid Table 1 Light Accent 3"/>
  <w:LsdException Locked="false" Priority="47" Name="Grid Table 2 Accent 3"/>
  <w:LsdException Locked="false" Priority="48" Name="Grid Table 3 Accent 3"/>
  <w:LsdException Locked="false" Priority="49" Name="Grid Table 4 Accent 3"/>
  <w:LsdException Locked="false" Priority="50" Name="Grid Table 5 Dark Accent 3"/>
  <w:LsdException Locked="false" Priority="51"
   Name="Grid Table 6 Colorful Accent 3"/>
  <w:LsdException Locked="false" Priority="52"
   Name="Grid Table 7 Colorful Accent 3"/>
  <w:LsdException Locked="false" Priority="46"
   Name="Grid Table 1 Light Accent 4"/>
  <w:LsdException Locked="false" Priority="47" Name="Grid Table 2 Accent 4"/>
  <w:LsdException Locked="false" Priority="48" Name="Grid Table 3 Accent 4"/>
  <w:LsdException Locked="false" Priority="49" Name="Grid Table 4 Accent 4"/>
  <w:LsdException Locked="false" Priority="50" Name="Grid Table 5 Dark Accent 4"/>
  <w:LsdException Locked="false" Priority="51"
   Name="Grid Table 6 Colorful Accent 4"/>
  <w:LsdException Locked="false" Priority="52"
   Name="Grid Table 7 Colorful Accent 4"/>
  <w:LsdException Locked="false" Priority="46"
   Name="Grid Table 1 Light Accent 5"/>
  <w:LsdException Locked="false" Priority="47" Name="Grid Table 2 Accent 5"/>
  <w:LsdException Locked="false" Priority="48" Name="Grid Table 3 Accent 5"/>
  <w:LsdException Locked="false" Priority="49" Name="Grid Table 4 Accent 5"/>
  <w:LsdException Locked="false" Priority="50" Name="Grid Table 5 Dark Accent 5"/>
  <w:LsdException Locked="false" Priority="51"
   Name="Grid Table 6 Colorful Accent 5"/>
  <w:LsdException Locked="false" Priority="52"
   Name="Grid Table 7 Colorful Accent 5"/>
  <w:LsdException Locked="false" Priority="46"
   Name="Grid Table 1 Light Accent 6"/>
  <w:LsdException Locked="false" Priority="47" Name="Grid Table 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="48" Name="Grid Table 3 Accent 6"/>
  <w:LsdException Locked="false" Priority="49" Name="Grid Table 4 Accent 6"/>
  <w:LsdException Locked="false" Priority="50" Name="Grid Table 5 Dark Accent 6"/>
  <w:LsdException Locked="false" Priority="51"
   Name="Grid Table 6 Colorful Accent 6"/>
  <w:LsdException Locked="false" Priority="52"
   Name="Grid Table 7 Colorful Accent 6"/>
  <w:LsdException Locked="false" Priority="46" Name="List Table 1 Light"/>
  <w:LsdException Locked="false" Priority="47" Name="List Table 2"/>
  <w:LsdException Locked="false" Priority="48" Name="List Table 3"/>
  <w:LsdException Locked="false" Priority="49" Name="List Table 4"/>
  <w:LsdException Locked="false" Priority="50" Name="List Table 5 Dark"/>
  <w:LsdException Locked="false" Priority="51" Name="List Table 6 Colorful"/>
  <w:LsdException Locked="false" Priority="52" Name="List Table 7 Colorful"/>
  <w:LsdException Locked="false" Priority="46"
   Name="List Table 1 Light Accent 1"/>
  <w:LsdException Locked="false" Priority="47" Name="List Table 2 Accent 1"/>
  <w:LsdException Locked="false" Priority="48" Name="List Table 3 Accent 1"/>
  <w:LsdException Locked="false" Priority="49" Name="List Table 4 Accent 1"/>
  <w:LsdException Locked="false" Priority="50" Name="List Table 5 Dark Accent 1"/>
  <w:LsdException Locked="false" Priority="51"
   Name="List Table 6 Colorful Accent 1"/>
  <w:LsdException Locked="false" Priority="52"
   Name="List Table 7 Colorful Accent 1"/>
  <w:LsdException Locked="false" Priority="46"
   Name="List Table 1 Light Accent 2"/>
  <w:LsdException Locked="false" Priority="47" Name="List Table 2 Accent 2"/>
  <w:LsdException Locked="false" Priority="48" Name="List Table 3 Accent 2"/>
  <w:LsdException Locked="false" Priority="49" Name="List Table 4 Accent 2"/>
  <w:LsdException Locked="false" Priority="50" Name="List Table 5 Dark Accent 2"/>
  <w:LsdException Locked="false" Priority="51"
   Name="List Table 6 Colorful Accent 2"/>
  <w:LsdException Locked="false" Priority="52"
   Name="List Table 7 Colorful Accent 2"/>
  <w:LsdException Locked="false" Priority="46"
   Name="List Table 1 Light Accent 3"/>
  <w:LsdException Locked="false" Priority="47" Name="List Table 2 Accent 3"/>
  <w:LsdException Locked="false" Priority="48" Name="List Table 3 Accent 3"/>
  <w:LsdException Locked="false" Priority="49" Name="List Table 4 Accent 3"/>
  <w:LsdException Locked="false" Priority="50" Name="List Table 5 Dark Accent 3"/>
  <w:LsdException Locked="false" Priority="51"
   Name="List Table 6 Colorful Accent 3"/>
  <w:LsdException Locked="false" Priority="52"
   Name="List Table 7 Colorful Accent 3"/>
  <w:LsdException Locked="false" Priority="46"
   Name="List Table 1 Light Accent 4"/>
  <w:LsdException Locked="false" Priority="47" Name="List Table 2 Accent 4"/>
  <w:LsdException Locked="false" Priority="48" Name="List Table 3 Accent 4"/>
  <w:LsdException Locked="false" Priority="49" Name="List Table 4 Accent 4"/>
  <w:LsdException Locked="false" Priority="50" Name="List Table 5 Dark Accent 4"/>
  <w:LsdException Locked="false" Priority="51"
   Name="List Table 6 Colorful Accent 4"/>
  <w:LsdException Locked="false" Priority="52"
   Name="List Table 7 Colorful Accent 4"/>
  <w:LsdException Locked="false" Priority="46"
   Name="List Table 1 Light Accent 5"/>
  <w:LsdException Locked="false" Priority="47" Name="List Table 2 Accent 5"/>
  <w:LsdException Locked="false" Priority="48" Name="List Table 3 Accent 5"/>
  <w:LsdException Locked="false" Priority="49" Name="List Table 4 Accent 5"/>
  <w:LsdException Locked="false" Priority="50" Name="List Table 5 Dark Accent 5"/>
  <w:LsdException Locked="false" Priority="51"
   Name="List Table 6 Colorful Accent 5"/>
  <w:LsdException Locked="false" Priority="52"
   Name="List Table 7 Colorful Accent 5"/>
  <w:LsdException Locked="false" Priority="46"
   Name="List Table 1 Light Accent 6"/>
  <w:LsdException Locked="false" Priority="47" Name="List Table 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="48" Name="List Table 3 Accent 6"/>
  <w:LsdException Locked="false" Priority="49" Name="List Table 4 Accent 6"/>
  <w:LsdException Locked="false" Priority="50" Name="List Table 5 Dark Accent 6"/>
  <w:LsdException Locked="false" Priority="51"
   Name="List Table 6 Colorful Accent 6"/>
  <w:LsdException Locked="false" Priority="52"
   Name="List Table 7 Colorful Accent 6"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Mention"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Smart Hyperlink"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Hashtag"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Unresolved Mention"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Smart Link"/>
 </w:LatentStyles>
</xml><![endif]--><!--[if gte mso 10]>
<style>
 /* Style Definitions */
 table.MsoNormalTable
	{mso-style-name:"Table Normal";
	mso-tstyle-rowband-size:0;
	mso-tstyle-colband-size:0;
	mso-style-noshow:yes;
	mso-style-priority:99;
	mso-style-parent:"";
	mso-padding-alt:0in 5.4pt 0in 5.4pt;
	mso-para-margin-top:0in;
	mso-para-margin-right:0in;
	mso-para-margin-bottom:8.0pt;
	mso-para-margin-left:0in;
	line-height:107%;
	mso-pagination:widow-orphan;
	font-size:11.0pt;
	font-family:"Times New Roman",serif;
	mso-bidi-font-family:Arial;
	mso-bidi-theme-font:minor-bidi;
	mso-bidi-language:AR-SA;}
</style>
<![endif]-->

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span class="MsoBookTitle"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Interpretive Project: <a name="_Hlk88318817">John
1:1–18 (LEB)</a></span></span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">The King’s University, Southlake, Texas</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Biblical Background and Interpretation (2021FA-BIBL-2301-ONL)</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Professor: Dr. J. Wallace</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">12/05/2021</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">By Darrell Wolfe</span></p>

<span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;"><br clear="all" style="mso-special-character: line-break; page-break-before: always;" />
</span>

<p class="MsoNormal"><b><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></b></p>

<h1><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Thesis</span></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">The following paper includes a translation of
John 1:1-18 (aka John’s Prologue) from the Lexham English Bible (LEB), which is
considered among the most literal translations.<a href="#_ftn1" name="_ftnref1" style="mso-footnote-id: ftn1;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[1]</span></span></span></span></a> <span style="mso-spacerun: yes;">&nbsp;</span>Then, the paper provides a Structural Outline
for the passage, Observations, a Situational Reconstruction, Theological
Questions posed by the text, and a Lexicography. Following these are an
analysis of the Message/Argument of the Text and a Conclusion with takeaways
about John’s primary message: Jesus is the Logos and he came because God wanted
his family back. </span></p>

<h1><a href="https://ref.ly/logosres/leb?ref=BibleLEB2.Jn1.1-18"><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">John
11–18 (LEB)</span></a><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"></span></h1>

<p class="MsoQuote"><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">1In the beginning was the Word, and the Word
was with God, and the Word was God. 2 This one was in the beginning with God. 3
All things came into being through him, and apart from him not one thing came
into being that has come into being. 4 In him was life, and the life was the
light of humanity. 5 And the light shines in the darkness, and the darkness did
not overcome it. 6 A man came, sent from God, </span><span style="font-family: &quot;Cambria Math&quot;,serif; mso-bidi-font-family: &quot;Cambria Math&quot;;">⌊</span><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">whose
name was</span><span style="font-family: &quot;Cambria Math&quot;,serif; mso-bidi-font-family: &quot;Cambria Math&quot;;">⌋</span><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> John. 7 This one came for a witness, in order
that he could testify about the light, so that all would believe through him. 8
That one was not the light but came in order that he could testify about the
light. 9 The true light, who gives light to every person, was coming into the
world. 10 He was in the world, and the world came into being through him, and
the world did not recognize him. 11 He came to his own things, and his own
people did not receive him. 12 <b>But as many as received him—to those who
believe in his name—he gave to them authority to become children of God</b>, 13
who were born not of blood, nor of the will of the flesh, nor of the will of a
husband, but of God. 14 And the Word became flesh and took up residence among
us, and we saw his glory, glory as of the one and only from the Father, full of
grace and truth. 15 John testified about him and cried out, saying, “This one
was he about whom I said, ‘The one who comes after me is ahead of me, because
he existed before me.’” 16 For from his fullness we have all received, and
grace after grace. 17 For the law was given through Moses; grace and truth came
about through Jesus Christ. 18 No one has seen God at any time; the one and
only, God, the one who is in the bosom of the Father—<b>that one has made him*
known</b>.<a href="#_ftn2" name="_ftnref2" style="mso-footnote-id: ftn2;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><b style="mso-bidi-font-weight: normal;"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[2]</span></b></span></span></span></a></span></p>

<h1><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Structural
Outline</span></h1>

<p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">John’s introduction to his theological biography
of Jesus (1:1-18)</span></p>

<p class="MsoListParagraphCxSpFirst" style="margin-left: .2in; mso-add-space: auto; mso-list: l1 level1 lfo1; text-indent: -.1in;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-list: Ignore;">I<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp; </span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Jesus’ Nature (v 1-9)</span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: .3in; mso-add-space: auto; mso-list: l1 level2 lfo1; text-indent: -.1in;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-list: Ignore;">A<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Nature
Claim 1: Jesus preexisted with Yahweh, and was the co-creator (v 1-3)</span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: .3in; mso-add-space: auto; mso-list: l1 level2 lfo1; text-indent: -.1in;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-list: Ignore;">B<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Nature
Claim 1: Jesus is the embodiment of Creation (v 4-5)</span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: .3in; mso-add-space: auto; mso-list: l1 level2 lfo1; text-indent: -.1in;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-list: Ignore;">C<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Clarification
from John the Baptist: Jesus is different from John the Baptist (v 6-9)</span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: .2in; mso-add-space: auto; mso-list: l1 level1 lfo1; text-indent: -.1in;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-list: Ignore;">II<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Jesus’
Mission (v 10-15)</span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: .3in; mso-add-space: auto; mso-list: l1 level2 lfo1; text-indent: -.1in;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-list: Ignore;">A<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Mission
Claim 1: Jesus came to offer adoption as God’s kids (v 10-13)</span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: .3in; mso-add-space: auto; mso-list: l1 level2 lfo1; text-indent: -.1in;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-list: Ignore;">B<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Mission
Claim 2: Jesus came to his creation as one of them (v 10-14)</span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: .3in; mso-add-space: auto; mso-list: l1 level2 lfo1; text-indent: -.1in;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-list: Ignore;">C<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Clarification
from John the Baptist: John was not Jesus, but the one who prepared the way (v
15)</span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: .2in; mso-add-space: auto; mso-list: l1 level1 lfo1; text-indent: -.1in;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-list: Ignore;">III<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Jesus’
Legacy/Results (v 16-18)</span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: .3in; mso-add-space: auto; mso-list: l1 level2 lfo1; text-indent: -.1in;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-list: Ignore;">A<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Jesus
brings “grace” (16)</span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: .3in; mso-add-space: auto; mso-list: l1 level2 lfo1; text-indent: -.1in;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-list: Ignore;">B<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Moses
brought the Torah (the mind of Yahweh), building on that Jesus brought Grace
(the Heart of Yahweh) (17)</span></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: .3in; mso-add-space: auto; mso-list: l1 level2 lfo1; text-indent: -.1in;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-list: Ignore;">C<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">To know
Jesus is to know the Father/Yahweh (18)</span></p>

<h1><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Observations</span></h1>

<p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">(1:1-3)</span></p>

<p class="MsoListParagraphCxSpFirst" style="mso-list: l3 level1 lfo2; text-indent: -.25in;"><span style="font-family: Symbol; font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><b><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Beginning
- Genesis One:</span></b><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> In <i>the</i>
beginning calls the reader back to Genesis 1:1, "In <i>the</i> beginning,
Elohim created the Skies and the Land".<a href="#_ftn3" name="_ftnref3" style="mso-footnote-id: ftn3;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[3]</span></span></span></span></a> John
mirrors the Hebrew (</span><a href="https://ref.ly/logosres/readhebgkbbl?ref=BibleRHG.Ge1"><span dir="RTL" lang="HE" style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">בְּרֵאשִׁ֖ית</span></a><span dir="LTR"></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span dir="LTR"></span><span dir="LTR"></span>) and the LXX by omitting the definite
article in Greek (</span><a href="https://ref.ly/logosres/otgrkswetetxt?ref=BibleLXX2.Ge1&amp;off=2"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">ΕΝ ΑΡΧΗ</span></a><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> (Gen1
LXX)/ </span><a href="https://ref.ly/logosres/readhebgkbbl?ref=BibleRHG.Jn1"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Ἐν ἀρχῇ</span></a><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> (John 1)
causing a direct mental hyperlink to the original passage for anyone familiar
with their Hebrew scriptures.<a href="#_ftn4" name="_ftnref4" style="mso-footnote-id: ftn4;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[4]</span></span></span></span></a></span></p>

<p class="MsoListParagraphCxSpMiddle" style="mso-list: l3 level1 lfo2; text-indent: -.25in;"><span style="font-family: Symbol; font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><b><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Beginning
- Greek philosophers</span></b><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> began a
search for the basic stuff from which everything was made, and Aristotle termed
the search “</span><a href="https://ref.ly/logosres/gs-netnotes?ref=Bible.Jn1.1"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">what is the beginning</span></a><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">”. John who was by this point living among the
Greek-Speaking peoples of Ephesus created a double impact by his use of the
phrase. His gospel will answer new Greek questions with old Hebrew answers, and
yet with a surprising new twist (the Logos became one of us).<a href="#_ftn5" name="_ftnref5" style="mso-footnote-id: ftn5;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[5]</span></span></span></span></a> </span></p>

<p class="MsoListParagraphCxSpMiddle" style="mso-list: l3 level1 lfo2; text-indent: -.25in;"><span style="font-family: Symbol; font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><b><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">New
Creation:</span></b><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> John writes his own Genesis, and his gospel is
saturated with Genesis imagery. The creation of the world in Genesis is now
interplayed with the New Creation in John. NET Bible Notes also make a point to
clarify that Genesis 1:1 was a physical/spiritual creation (bodies animated by
the breath of God), likewise, John’s gospel is about a second birth which is
also a physical/spiritual creation. Bodies are in this life in-breathed by
God’s Spirit, and the promise remains of a future Resurrection with new
in-breathed bodies. Thus, the water into wine is the first sign of this new
creation arriving.<a href="#_ftn6" name="_ftnref6" style="mso-footnote-id: ftn6;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[6]</span></span></span></span></a> In
John, Jesus begins and ends his ministry interaction with wine symbols. </span></p>

<p class="MsoListParagraphCxSpMiddle" style="mso-list: l3 level1 lfo2; text-indent: -.25in;"><span style="font-family: Symbol; font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><b><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Word - Hebrew
Thought:</span></b><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> For the Hebrews, God created the world not
through a fight with other divine beings as taught in the Ugaritic story of
Enuma Elish, but by simply speaking words and those words caused things to
happen.<a href="#_ftn7" name="_ftnref7" style="mso-footnote-id: ftn7;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[7]</span></span></span></span></a> This
then becomes tied into the ideas and concepts which play out in the work of later
Hebrew-Greek Philosopher, Philo.</span></p>

<p class="MsoListParagraphCxSpLast" style="mso-list: l3 level1 lfo2; text-indent: -.25in;"><span style="font-family: Symbol; font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><b><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Word - Greek
Philosophers:</span></b><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> The
word λόγος (logos) has a rich tradition in Greek Philosophy dating back to the
600s BC. In summary, by the first century AD, the Stoics had come to define the
Logos as a cosmological and divine entity from which everything was created.
The Jewish Philosopher, Philo (20 BC to 50 AD) brought the Hebrew scriptures to
the Greek Philosophy and taught that logos was the way God operated in the
world. For Philo, God did not govern directly but through his son, a mediator
called the Logos. Lexham Bible Dictionary explains:</span></p>

<p class="MsoQuote"><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">“In John’s prologue, God creates by way of the
logos (John 1:3), similar to Philo’s teachings. The logos is the only begotten
Son of the Father (John 1:14), who acts as mediator between God and the people
who do not know God (John 1:18), also like in Philo. The major difference
between Philo and John comes with John’s identification of the logos with the
historical person of Jesus.”<a href="#_ftn8" name="_ftnref8" style="mso-footnote-id: ftn8;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><b style="mso-bidi-font-weight: normal;"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[8]</span></b></span></span></span></a></span></p>

<p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">(1:4-5)</span></p>

<p class="MsoListParagraph" style="mso-list: l3 level1 lfo2; text-indent: -.25in;"><span style="font-family: Symbol; font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><b><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Light –
Life:</span></b><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> As the reader is already reminded of Genesis
One, they consider the first act of God speaking, “light be”, and then they're
reminded of the Tree of Life in the Garden. The two concepts are tied together
as one theme for John, the light that began all creation is the life that was
lost in Eden. He takes it further, showing that life-light was actually a being,
the Logos. When humankind lost the life-light, the life-light became a human to
bring it back to them.</span></p>

<p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">(1:1-18)</span></p>

<p class="MsoListParagraph" style="mso-list: l3 level1 lfo2; text-indent: -.25in;"><span style="font-family: Symbol; font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><b><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Eternal
Nature:</span></b><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> John uses a series of repetitive statements to
drive home the point that the Logos (Jesus) is God and is eternal. He begins by
showing he was in the beginning and the creator of all. Then he shows that he
was the light/life but became a human. Then he shows that he came to the world,
but most of the world did not recognize him, but those who did became Children
of God. Then he circles back to the concept of Logos becoming the very creation
he created. Then he uses John the Baptist to emphasize that Jesus pre-existed
John, even though John was six months older (which by now everyone knows
because the Synoptics have circulated for decades). He wraps up by showing that
Moses gave the Torah, and Jesus clarified and brought fullness to Torah by adding
Grace and Truth. </span></p>

<h1><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Situational
Reconstruction</span></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><b><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Authorship</span></b><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">: The
author of “John” is unidentified within the text and refers to himself as “the
disciple whom Jesus loved” (John 21:20). It is in the closing chapter that the
author gives us an interesting wordplay with the use of agapaō (to love, be
faithful towards, delight in) and phileō (to manifest an act of kindness or
token of affection, such as a kiss) (John 21:15-23).<a href="#_ftn9" name="_ftnref9" style="mso-footnote-id: ftn9;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[9]</span></span></span></span></a><i style="mso-bidi-font-style: normal;"> </i>This focus on “love” becomes the theme
of John’s gospel, “for God so loved the world” (John 3:16). Fee and Hubbard
note that the author chooses the moniker/self-designation “the disciple whom
Jesus loved” to generate trust in his testimony as a confidant of Jesus.<a href="#_ftn10" name="_ftnref10" style="mso-footnote-id: ftn10;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[10]</span></span></span></span></a> The
author was likely Jewish by birth as he wrote Greek with an Aramaic way of
thinking.<a href="#_ftn11" name="_ftnref11" style="mso-footnote-id: ftn11;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[11]</span></span></span></span></a> </span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Church tradition and many commentaries settle
on the author as John, the Apostle, the Son of Zebedee.<a href="#_ftn12" name="_ftnref12" style="mso-footnote-id: ftn12;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[12]</span></span></span></span></a>
However, it has been noted that John the Elder is also considered a possible
author.<a href="#_ftn13" name="_ftnref13" style="mso-footnote-id: ftn13;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[13]</span></span></span></span></a>
Keener makes a compelling case for the author being John the Apostle, one of
Jesus’ closest companions (the inner three).<a href="#_ftn14" name="_ftnref14" style="mso-footnote-id: ftn14;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[14]</span></span></span></span></a>
Meanwhile, Wright takes a different tact, saying that some internal and
external evidence leads him to “cautiously conclude” that the author was John
the Elder, a disciple of John the Apostle.<a href="#_ftn15" name="_ftnref15" style="mso-footnote-id: ftn15;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[15]</span></span></span></span></a>
This conclusion rests largely on how the early church father’s referred to John
as “The Elder” while referring to others as “Apostles” in the same writings,
and a tense change within the gospel itself that lends one to see the author as
having joined the party later in Jesus’ ministry. </span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">In either case, the author is close enough to
Jesus to have been leaning against him at the last supper and well-connected
enough to be the only disciple allowed in the inner courts during Jesus’
prosecution, and the only disciple present at the cross. He is also close
enough to Jesus, that he inherits the care of Jesus’ mother, Mary at the cross.
The author is also thought to be the same author as 1, 2, &amp; 3 John and
Revelation, due in large part to the contextual links in themes between all
these writings.<a href="#_ftn16" name="_ftnref16" style="mso-footnote-id: ftn16;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[16]</span></span></span></span></a>
It is noted that the author would not need to identify his name if were already
known to his “dear friends”.<a href="#_ftn17" name="_ftnref17" style="mso-footnote-id: ftn17;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[17]</span></span></span></span></a>
The traditional view of John the Apostle is assumed by this paper,
acknowledging the possibility of John the Elder.</span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><b><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Recipients and Date</span></b><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">: Most early traditions point to John having
been an Elder of the Church of Ephesus, between 70AD and 100AD. The Rylands
Fragment of John dates to 135 AD and was discovered in Egypt. For the gospel to
have circulated down that far, it would have had to have been written decades
before.<a href="#_ftn18" name="_ftnref18" style="mso-footnote-id: ftn18;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[18]</span></span></span></span></a>
This leads one to conclude that the gospel likely dates to the later decades of
the first century AD. As one of the four “Gospels”, the book was written with
the knowledge it would be passed around to various audiences, but likely would
have begun its circulation in Ephesus. </span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Barry notes the detail of Jewish customs
reflect a first-hand knowledge of Judea, and he concludes the audience would
have been Jewish Christians.<a href="#_ftn19" name="_ftnref19" style="mso-footnote-id: ftn19;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[19]</span></span></span></span></a>
However, JFB notes that the explanation of things familiar to most Jews
indicates the audience is largely Gentile.<a href="#_ftn20" name="_ftnref20" style="mso-footnote-id: ftn20;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[20]</span></span></span></span></a> Intertextually,
Ephesus plays a major role in the development of the New Testament. As noted
elsewhere, Paul’s work in Colossae led to the development of the church at
Ephesus and impacted all of Asia Minor.<a href="#_ftn21" name="_ftnref21" style="mso-footnote-id: ftn21;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[21]</span></span></span></span></a>
Thus, if the author of John is writing after the work of Paul, he is certainly
aware of the letters of Paul to Philemon, Ephesians, and Colossians and would
be writing firstly to those same audiences. </span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><b><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Why John Wrote the fourth Gospel:</span></b><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> By this point in history, the three synoptic
gospels had circulated as had the writings of Paul and most (if not all) the
other New Testament epistles. So, what did John feel was needed to add to the now-established
young church? While the three Synoptics focused on narrative-biography, John
had many decades to reflect on his experiences with Jesus and the resulting impacts
of those events on world history up to that point. He had seen the walls of
Jerusalem’s beloved temple fall, just as Jesus said they would (Matthew 24). John
presents a theological gospel, with an emphasis on Jesus as the “God-Man”.<a href="#_ftn22" name="_ftnref22" style="mso-footnote-id: ftn22;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[22]</span></span></span></span></a> </span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">The prologue of John begins with a series of
statements and theological claims about the nature of Jesus and his ministry
(1:1-18). The most striking of which are the use of “beginning”, “logos/word”,
and inferences to the eternal nature of Jesus who was “with God” and through
whom “everything was created”. The introduction concludes by using the words of
John the Baptist to emphasize the point of the story: “I have seen and testify
that this one (Jesus) is the Chosen One of God” (John 1:32-34). </span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">John concludes his book by telling the reader
why he wrote, that “you may believe the Jesus is the Christos (<i>Messiah</i>),
the Son of God (<i>a political and theological claim in one</i>), and that by
believing you may have life in His name.” (parenthesis added, John 20:30-31).
This final statement is often misunderstood by modern Christians to indicate a
disembodied future in “heaven”; while the common Jewish understanding would
have understood that he meant a forever-life at The Resurrection, which Paul
also referred to when he talked about getting new bodies.</span></p>

<h1><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Theological
Questions</span></h1>

<p class="MsoListParagraphCxSpFirst" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l2 level1 lfo4; text-indent: -.25in;"><span style="font-family: Wingdings; font-size: 12.0pt; mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings;"><span style="mso-list: Ignore;">Ø<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp; </span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">What does the passage teach us about God?</span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Everything
that exists came through the work of God and His Logos.</span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">God’s
Light and Life (Genesis one and two themes) are tied directly to his Logos. </span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">God’s
purposes in entering his creation were to make a family and show them the way
out of the darkness. </span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">It is
impossible to see God as Father without seeing Jesus as God’s Logos,
Creative-Force. </span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">While
God is big enough to create an entire universe, he is passionate about his
humans and wants them to be his family. He is so interested in them, he is
willing to become one of them for eternity (Jesus never stopped being incarnated,
he remains today in the resurrected human form he took at the incarnation). </span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Unlike
the Ugaritic People’s ideas about the “gods” creating through a war with Tiamat,
or the later version of essentially the same story in the Greek world’s ideas
of Zeus defeating Cronos, John’s God is capable of overcoming the chaos darkness
all on his own, by simply speaking through his Logos. While Stoics rejected the
personal gods in favor of an essence called logos, John shows them a personal
God does exist in the person of Logos.</span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l2 level1 lfo4; text-indent: -.25in;"><span style="font-family: Wingdings; font-size: 12.0pt; mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings;"><span style="mso-list: Ignore;">Ø<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp; </span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">What does the passage teach us about humankind?</span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Without
the Light, which is the Life, we stumble around in the darkness. </span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">It is
possible to be in the presence of the very thing you need most and be blind to
it.</span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Some may
never understand the calling on a person’s life or their message (John the
Baptist/Jesus alike). Some may even attack the message on behalf of God, even
though it was from God.</span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l2 level1 lfo4; text-indent: -.25in;"><span style="font-family: Wingdings; font-size: 12.0pt; mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings;"><span style="mso-list: Ignore;">Ø<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp; </span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">What does the passage teach us about the
relationship between God and humankind?</span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">We are
invited to become God’s family.</span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">God’s
work in the world may not be recognized by many in the world, but some will
recognize that work, and those will be recognized by God.</span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">When God
wants to do his greatest work, he becomes one of the very humans he created to
show them what he is like.</span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l2 level1 lfo4; text-indent: -.25in;"><span style="font-family: Wingdings; font-size: 12.0pt; mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings;"><span style="mso-list: Ignore;">Ø<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp; </span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">What does the passage teach us about the
responsibilities God gives to humankind?</span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Just as
God works through his Logos, he also works through his people. Rather than
announcing his purposes from the sky, he begins by sending a Spirit-empowered
human in the form of John the Baptist. </span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">He gives
humans access to light and life; however, he will not force them to accept it. </span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Just as
he will not force them to accept it, he will not provide them another avenue
either. As a parent might refuse to make a different meal than the one
prepared, the ending of the prologue makes it clear that no one can see God as
Father unless they come to him through his Logos. </span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l2 level1 lfo4; text-indent: -.25in;"><span style="font-family: Wingdings; font-size: 12.0pt; mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings;"><span style="mso-list: Ignore;">Ø<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp; </span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">What does the passage teach us about how people
should treat each other, particularly in light of our relationship with God?</span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto;"><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">While nothing directly speaks to human-to-human
relationships, there are inferences available in the text:</span></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">If John
the Baptist and the Logos himself could come and not be recognized by the very
people who studied the “word” day and night, we should be cautious when we
speak to believers we disagree with. It may turn out to be that they are trying
to bring us the light that we need and we are too blind to see it. </span></p>

<p class="MsoListParagraphCxSpLast" style="line-height: normal; margin-left: .75in; mso-add-space: auto; mso-list: l2 level2 lfo4; text-indent: -.25in;"><span style="font-family: &quot;Courier New&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Courier New&quot;;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Just as
Moses gave Torah (teachings) and the Logos expanded those teachings, we may
come to the things of God in stages. We should appreciate those who came
before, but not fail to move forward with the new things God wants to show us.
However, they should always align, as Torah/Logos do, in the beginning. </span></p>

<p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<h1><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Lexicography</span></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">This Lexicography is using reproduces but
condenses the Mounce Lexicon unless otherwise indicated.<a href="#_ftn23" name="_ftnref23" style="mso-footnote-id: ftn23;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[23]</span></span></span></span></a>
For brevity, some examples are included, but not an exhaustive list.</span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .25in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">(794) ἀρχή <b>archē</b> 55x “a <b>beginning</b>”
(Mt. 24:8), can refer to an extremity or corner (Acts 10:11; 11:5), but typically
referring to authority and headship (Jude 6; Lk. 20:20; Lk. 12:11; Eph. 3:10;
6:12). Could also refer to “from the first” (Mt. 19:4, 8; Lk. 1:2; Jn. 6:64; 2
Thess. 2:13; 1 Jn. 1:1; 2:7) <b>or “in the beginning of things”</b> (<b>Jn. 1:1</b>,
2; Heb. 1:10, Acts 11:15). <span style="mso-tab-count: 1;"> </span></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .25in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">(3364) λόγος <b>logos</b> 330x “a <b>word</b>”,
typically used in the common sense of “speech, language, talk”. However, could
also have conceptual links to the Hebrew concepts of “the Word of Yahweh” which
came to the prophets. (Mt. 13:21, 22; Mk. 16:20; Lk. 1:2; Acts 6:4); and in
only one place in the New Testament, it is used as <b>“the divine WORD” (or
Logos) (Jn. 1:1).</b> Originally a mathematical term referring to giving
account (bookkeeping), Logos came to have strong ties to Greek Philosophers
such as Pythagoras, Heraclitus, Socrates, Plato, Aristotle, the Stoics, and the
Hebrew-Greek Philosopher Philo.<a href="#_ftn24" name="_ftnref24" style="mso-footnote-id: ftn24;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[24]</span></span></span></span></a></span></p>

<p class="MsoListParagraphCxSpFirst" style="line-height: 200%; mso-list: l0 level1 lfo3; text-indent: -.25in;"><span style="font-family: Symbol; font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">See
also, the Old Testament, “dabar” Mounce expands here to say that while the word
“dabar/word” is common in the Hebrew for all sorts of speech, Human and God, it
is often used to refer to “The Dabar of Yahweh has come to me”. Verb: </span><span dir="RTL" lang="HE" style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">דָּבַר</span><span dir="LTR"></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span dir="LTR"></span><span dir="LTR"></span> (dābar), GK 1819 (S 1696), 1136×; Noun: </span><span dir="RTL" lang="HE" style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">דָּבָר</span><span dir="LTR"></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span dir="LTR"></span><span dir="LTR"></span> (dābār), GK 1821 (S 1697), 1454×; Noun: </span><span dir="RTL" lang="HE" style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">נְאֻם</span><span dir="LTR"></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span dir="LTR"></span><span dir="LTR"></span>
(neʾum), GK 5536 (S 5002), 376×. neʾum.<a href="#_ftn25" name="_ftnref25" style="mso-footnote-id: ftn25;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[25]</span></span></span></span></a>
See also, </span><span dir="RTL" lang="HE" style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">קָרָא</span><span dir="LTR"></span><span dir="LTR"></span><span lang="HE" style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span dir="LTR"></span><span dir="LTR"></span> </span><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">(qara) vb. call, proclaim, read and </span><span dir="RTL" lang="HE" style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">אָמַר</span><span dir="LTR"></span><span dir="LTR"></span><span lang="HE" style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span dir="LTR"></span><span dir="LTR"></span> </span><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">(amar) vb.
utter, say from Genesis One.<a href="#_ftn26" name="_ftnref26" style="mso-footnote-id: ftn26;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[26]</span></span></span></span></a></span></p>

<p class="MsoListParagraphCxSpLast" style="line-height: 200%; mso-list: l0 level1 lfo3; text-indent: -.25in;"><span style="font-family: Symbol; font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">This
“Word/Dabar”, Dr. Tim Mackie says, is seen as the subject of the verb in the vision
recorded in Genesis 15:1, and thus the “Word of Yahweh” becomes seen as an
analog for Yahweh himself in later Jewish traditions.<a href="#_ftn27" name="_ftnref27" style="mso-footnote-id: ftn27;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[27]</span></span></span></span></a>
This blends into the theme of God using his Logos at work in the world in Greek
thought, and the two are combined in the work of Philo.</span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .25in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">(2437) ζωή zōē 135× <b>life, living existence (</b>Lk.
16:25; Acts 17:25) spiritual life (Jn. 6:51; Rom. 5:18; 6:4); the final life of
the redeemed, (Mt. 25:46) life, source of spiritual life. Aligned with the
Hebrew background for these concepts, this should be understood as related to
the Tree of Life in Genesis 2; and to the Resurrection of the Dead at the Great
Day of Yahweh, in which everyone loyal to Yahweh is brought back from the grave
and invited into the eschatological Kingdom of God. Life, in the mouths of
Greek-speaking Hebrew minds, refers to the life we have a taste of now and a
promise of in the age to come. For the Hebrew, the grave is not the end, a
redemption will come at the end. We will live, embodied, again. Thus, Paul goes
on to talk about a day when all believers will rise from the dead, and together
we will get new bodies. This concept is what is meant by “eternal (zoe) life”
when spoken by a Hebrew-minded writer.</span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .25in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">(5890) φῶς phōs 73× <b>light </b>(Mt. 17:2; 2
Cor. 4:6) daylight, broad day (Mt. 10:27; Lk. 12:3) from the Hebrew, the light
of God’s presence (2 Cor. 11:14; 1 Tim. 6:16) the light of Divine truth,
spiritual illumination (Lk. 16:8; Jn. 3:19; Rom. 13:12; Eph. 5:8; 1 Pet. 2:9; 1
Jn. 1:7; 2:8, 9, 10). Contextualized by John, this word refers to the very
first act of creation, “and Elohim said ‘light be’ and light be’d”. It was
through the Logos that light and life were given to humankind, both in the
beginning and in this new beginning. </span></p>

<h1><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Authorial
Intent (Message/Argument of the Text)</span></h1>

<p class="MsoNormal" style="line-height: 200%;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>In the late first century AD, John
took his residence in Ephesus and became pastor over Asia Minor (hence his
seven letters in Revelation). Either John the Apostle or John the Elder working
with John the Apostle may have received a revelation from the Apostle Andrew to
write a fourth gospel account.<a href="#_ftn28" name="_ftnref28" style="mso-footnote-id: ftn28;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[28]</span></span></span></span></a> At
this point, the Synoptics, most epistles, and Paul’s letters had circulated
through the churches. Paul who began the work in Asia Minor was later killed by
the Romans, as was Peter. John built on Paul’s work in Ephesus. As an old man,
John had decades to reflect on the life of Jesus, speaking about it with anyone
who would listen. He had read the works of Matthew, Mark, and Luke and felt no
need to repeat their works. John is also fighting increased emperor worship in
his time, as Caesar is called “lord and god” by his people.<a href="#_ftn29" name="_ftnref29" style="mso-footnote-id: ftn29;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[29]</span></span></span></span></a></span></p>

<p class="MsoNormal" style="line-height: 200%;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Bringing together his life as a
Hebrew fisherman in Galilee and his life as a world-traveler among the Greeks,
John sets out to show the world a more intimate and theologically themed
narrative about the life of the man who changed everything. He allows his words
to do triple time, relating Hebrew and Greek ideas with a narrative aimed
directly at the emperor worship of his day. Clement of Alexandria said that
John had seen all the basic facts laid out by the other writers and wanted to
compose a gospel aimed at the core theological themes of Jesus’ ministry, a
“spiritual gospel”.<a href="#_ftn30" name="_ftnref30" style="mso-footnote-id: ftn30;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[30]</span></span></span></span></a> </span></p>

<p class="MsoNormal" style="line-height: 200%;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>While recent scholarship has shown
the works of the Synoptics to demonstrate high-Christology once understood in
their own original Hebrew contexts,<a href="#_ftn31" name="_ftnref31" style="mso-footnote-id: ftn31;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[31]</span></span></span></span></a>
John’s gospel remains the clearest indication to lay-readers of his divinity
focusing on the unity of Father and Son.<a href="#_ftn32" name="_ftnref32" style="mso-footnote-id: ftn32;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[32]</span></span></span></span></a> To
begin this narrative, John chooses a framework that highlights Jesus as
God-incarnate. Mackie says that Jesus is shown in John’s prologue to be equal
with Yahweh, and then he spends the rest of the gospel showing Jesus going
around doing “Yahweh Stuff”.<a href="#_ftn33" name="_ftnref33" style="mso-footnote-id: ftn33;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[33]</span></span></span></span></a> Blum
summarizes: </span></p>

<p class="MsoQuote" style="margin-bottom: 0in;"><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">It is almost as if John had said, “I want you
to consider Jesus in His teaching and deeds. But you will not understand the
good news of Jesus in its fullest sense unless you view Him from this point of
view. Jesus is God manifest in the flesh, and His words and deeds are those of
the God-Man.”<a href="#_ftn34" name="_ftnref34" style="mso-footnote-id: ftn34;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><b style="mso-bidi-font-weight: normal;"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[34]</span></b></span></span></span></a></span></p>

<p class="MsoNormal" style="line-height: 200%;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p class="MsoNormal" style="line-height: 200%;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Building on the work of Philo, John
brings ancient Hebrew and new Greek ideas to bear on the theological
significance of the life of Jesus. This is no mere prophet or philosopher or
martyr. Jesus is the Logos the Greeks are searching to understand. He is the
manifested Word of God which was in operation throughout Yahweh’s work with
Israel. Even before anything existed, Jesus was there, as the Logos, the Word.
Jesus was not only with God, but he was also God. Separate and together. Many
in the Jewish community were already familiar with the Two Powers in Heaven and
some knew of Philo’s work showing Yahweh worked through his “son” the Logos,
now John was introducing these concepts in a new way, one that tied them
directly to this one man in real history and his impact on the world.<a href="#_ftn35" name="_ftnref35" style="mso-footnote-id: ftn35;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: AR-SA; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: major-bidi;">[35]</span></span></span></span></a></span></p>

<p class="MsoNormal" style="line-height: 200%;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Humanity was groping about in
darkness and death, and the light-giver and life-giver came to bring them hope.
However, many failed to see it for what it was. Even after a movement had
started and gospels were written and shared, there remained only a portion of
the population that believed the good news of the Yeshua (Iesus/Jesus) as the
real Lord (kurios) and God (theos) who had come to bring peace (counter to the
Pax Romana). These were all direct opposition to the claims of Caesar. John upped
the ante and demonstrated once and for all that one must choose Caesar or Jesus
as Lord. And yet, the words he chooses do not speak as one who lays down a
demand but as one pleading from compassion. </span></p>

<p class="MsoNormal" style="line-height: 200%;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>John speaks of new creation, light,
life, and a new family of God. John centers his prologue around the invitation:
“as many as received him – to those who believe in his name – he gave them
authority to become children of God” (1:12, see bolded in the introduction to
this paper). Just as God once created a physical world and a physical human and
breathed life into that human; God was again at work in the world breathing new
life into humanity. As God had intended to walk with Adam in the cool of the
day, God was again calling humanity out to become children and family. The
prologue ends with the desire of John’s heart “to make Him known” just as the
Logos had made the heart of the father “known” (1:18). </span></p>

<h1><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Conclusion</span></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">After reviewing the text, the situational
background, and exploring the themes presented by John, this paper concludes
that John’s primary message both in his book and in this section (prologue) was
to demonstrate the Jesus was the Logos (the search of the Greek) and the Word
(the second power in heaven) who came to offer the opportunity to become
children of God. John wanted to “make him known” so that everyone would have
the opportunity to connect with God’s heart to have his human family return to
him. To do this, he spent his words repeating and driving home the theme that
this was no mere man, no mere prophet, but was the very Logos of Yahweh/God.
The rest of the book of John outlines the life of Jesus in ways that highlight
these points. The themes of the Logos at work in the world by bringing light
and life are repeated throughout the book. To everyone who believes, they are
given the opportunity to become God’s kids. Just as “the disciple whom Jesus
loved” was intimate with God’s heart, he desired everyone else should be too.
John knew that others had written the facts of Jesus, John wanted to
communicate the heart of Jesus and his Father to his lost and hurting humanity.
God wanted his family back. </span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<h1><span style="mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Bibliography</span></h1>

<p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<p class="MsoBibliography">“Bible
Translation Spectrum.” Accessed November 20, 2021.
https://wiki.logos.com/Bible_Translation_Spectrum.</p>

<p class="MsoBibliography"><i>Christian Standard Bible® (CSB)</i>. Nashville,
Tennessee.: Holman Bible Pub, 2017.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Clendenen, E. Ray, and Jeremy Howard. <i>Holman
Illustrated Bible Commentary</i>. Broadman &amp; Holman, 2015.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">“Enuma Elish - New World Encyclopedia.” Accessed
November 17, 2021. https://www.newworldencyclopedia.org/entry/Enuma_Elish.</p>

<p class="MsoBibliography"><i>&nbsp;</i></p>

<p class="MsoBibliography"><i>Faithlife Study Bible, via Logos Software</i>.
Faithlife / Logos Bible Software, 2018.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Fee, Gordon D., and Robert L. Hubbard, eds. <i>The
Eerdmans Companion to the Bible</i>. Grand Rapids, Mich. ; Cambridge, U.K: W.B.
Eerdmans Pub. Co, 2011.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Fee, Gordon D., and Douglas K. Stuart. <i>How to Read
the Bible Book by Book: A Guided Tour</i>. Grand Rapids, Mich: Zondervan, 2002.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Gesenius, Wilhelm, Charles Briggs, S.R. Driver, and
Francis Brown. <i>The Abridged Brown-Driver-Briggs Hebrew-English Lexicon of
the Old Testament: From A Hebrew and English Lexicon of the Old Testament.</i>
Boston; New York: Houghton, Mifflin and Company, 1906.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Goodrich, Richard J, Albert L Lukaszewski, A. Philip
Brown, and Bryan W Smith. <i>A reader’s Hebrew and Greek Bible: 2nd edition.</i>,
2020.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Gore, Charles, Henry Leighton Goudge, and Alfred
Guillaume, eds. <i>A NEW COMMENTARY ON HOLY SCRIPTURE INCLUDING THE APOCRYPHA</i>.
Vol. 1, p. Iii. New York, NY: The Macmillan Company, 1928.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Jamieson, Robert, A. R. Fausset, and David Brown. <i>Commentary
Critical and Explanatory on the Whole Bible (1871)</i>. Oak Harbor, WA: Logos
Research Systems, Inc., 1997.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Mackie, Tim, and Jon Collins. “BibleProject<sup>TM</sup>
Videos and Podcasts.” Accessed June 18, 2021. https://bibleproject.com/.</p>

<p class="MsoBibliography">———. “God’s Word, Spirit, &amp; Wisdom Podcast |
BibleProject<sup>TM</sup>.” BibleProject. Accessed November 26, 2021.
https://bibleproject.com/podcast/theme-god-e11-gods-word-spirit-wisdom/.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Mounce, William D., ed. <i>Mounce’s Complete
Expository Dictionary of Old &amp; New Testament Words</i>. Grand Rapids, Mich:
Zondervan, 2006.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">“NJAB - Comparison Chart of Bible Translations Showing
Style or Type of Translation and Readability or Grade Level.” Accessed November
20, 2021. https://notjustanotherbook.com/biblecomparison.htm.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Plummer, Rob. <i>Daily Dose of Greek</i>. Daily Dose
of Greek. Louisville, KY: Daily Dose of Greek and Hebrew. Accessed November 27,
2021. https://dailydoseofgreek.com/about/.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Segal, Alan F. <i>Two Powers in Heaven: Early Rabbinic
Reports about Christianity and Gnosticism</i>. Studies in Judaism in Late Antiquity,
v. 25. Leiden: Brill, 1977.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Swete, Henry Barclay. <i>The Old Testament in Greek:
According to the Septuagint</i>. Cambridge, UK: Cambridge University Press,
1909.</p>

<p class="MsoBibliography"><i>&nbsp;</i></p>

<p class="MsoBibliography"><i>The Lexham Bible Dictionary - Barry, J. D., Bomar,
D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott, C., … Widder,
W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham, WA: Lexham
Press.</i> Billingham, WA: Leham Press, 2016. LexhamPress.com.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Bible Bookshelf blog. “The Lexham English Bible: Dark
Horse of English Bible Versions.” Accessed November 20, 2021.
http://biblebookshelf.weebly.com/1/post/2017/01/the-lexham-english-bible-dark-horse-of-english-bible-versions.html.</p>

<p class="MsoBibliography"><i>&nbsp;</i></p>

<p class="MsoBibliography"><i>The Lexham English Bible (LEB), Fourth Edition</i>.
Logo Bible Software. Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D.,
Dunham, J., Reimer, J. A., &amp; Wierenga, M. (Eds.). Bellingham, WA: Lexham
Press, 2010. http://www.lexhampress.com.</p>

<p class="MsoBibliography"><i>&nbsp;</i></p>

<p class="MsoBibliography"><i>The Lexham Hebrew Bible (LHB)</i>. Bellingham, WA:
Leham Press, 2012.</p>

<p class="MsoBibliography"><i>&nbsp;</i></p>

<p class="MsoBibliography"><i>The NET Bible First Edition Notes</i>. Biblical
Studies Press, 2006.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Walton, John H. <i>The Lost World of Genesis One:
Ancient Cosmology and the Origins Debate.</i> Westmont: InterVarsity Press,
2010.
https://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=2030851.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Walvoord, John F., Roy B. Zuck, and Dallas Theological
Seminary, eds. <i>The Bible Knowledge Commentary: An Exposition of the
Scriptures</i>. Wheaton, Ill: Victor Books, 1983.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Wolfe, Darrell. “Class Assignment: Situational
Reconstruction | Philemon.” Paper presented at the Biblical Background and
Interpretation (2021FA-BIBL-2301-ONL), The King’s University, Southlake, Texas,
November 4, 2021.
http://www.darrellwolfe.com/2021/11/class-assignment-situational.html.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Wright, N. T. <i>Jesus and the Victory of God</i>. 1st
North American ed. Vol. Vol 2. Christian Origins and the Question of God.
Minneapolis, MN: Fortress Press, 1996.</p>

<p class="MsoBibliography">&nbsp;</p>

<p class="MsoBibliography">Wright, N. T., and Michael F. Bird. <i>The New
Testament in Its World: An Introduction to the History, Literature, and
Theology of the First Christians</i>. London : Grand Rapids, MI: SPCK ;
Zondervan Academic, 2019.</p>

<p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<div style="mso-element: footnote-list;"><br clear="all" />

<hr align="left" size="1" width="33%" />



<div id="ftn1" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref1" name="_ftn1" style="mso-footnote-id: ftn1;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[1]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">“Bible
Translation Spectrum,” accessed November 20, 2021,
https://wiki.logos.com/Bible_Translation_Spectrum; “The Lexham English Bible:
Dark Horse of English Bible Versions,” Bible Bookshelf blog, accessed November
20, 2021,
http://biblebookshelf.weebly.com/1/post/2017/01/the-lexham-english-bible-dark-horse-of-english-bible-versions.html.</span></p>

</div>

<div id="ftn2" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref2" name="_ftn2" style="mso-footnote-id: ftn2;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[2]</span></span></span></span></a> <i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">The
Lexham English Bible (LEB), Fourth Edition</span></i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">, Logo Bible Software, Harris,
W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A.,
&amp; Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010), John 1:1–18,
http://www.lexhampress.com; “NJAB - Comparison Chart of Bible Translations
Showing Style or Type of Translation and Readability or Grade Level,” accessed
November 20, 2021, https://notjustanotherbook.com/biblecomparison.htm.</span></p>

</div>

<div id="ftn3" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref3" name="_ftn3" style="mso-footnote-id: ftn3;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[3]</span></span></span></span></a> <i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">The
Lexham Hebrew Bible (LHB)</span></i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;"> (Bellingham, WA: Leham Press, 2012),
English translation of Gen 1:1 my own.</span></p>

</div>

<div id="ftn4" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref4" name="_ftn4" style="mso-footnote-id: ftn4;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[4]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Rob
Plummer, <i>Daily Dose of Greek</i>, Daily Dose of Greek (Louisville, KY: Daily
Dose of Greek and Hebrew), John 1, accessed November 27, 2021,
https://dailydoseofgreek.com/about/; <i>LHB</i>, Genesis 1; Henry Barclay
Swete, <i>The Old Testament in Greek: According to the Septuagint</i>
(Cambridge, UK: Cambridge University Press, 1909), Genesis 1; Richard J
Goodrich et al., <i>A reader’s Hebrew and Greek Bible: 2nd edition.</i>, 2020,
John 1.</span></p>

</div>

<div id="ftn5" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref5" name="_ftn5" style="mso-footnote-id: ftn5;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[5]</span></span></span></span></a> <i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">The
NET Bible First Edition Notes</span></i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;"> (Biblical Studies Press, 2006), Notes
for 1:1.</span></p>

</div>

<div id="ftn6" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref6" name="_ftn6" style="mso-footnote-id: ftn6;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[6]</span></span></span></span></a> <i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">The
NET Bible First Edition Notes</span></i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">, Notes for 1:1.</span></p>

</div>

<div id="ftn7" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref7" name="_ftn7" style="mso-footnote-id: ftn7;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[7]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">“Enuma
Elish - New World Encyclopedia,” accessed November 17, 2021,
https://www.newworldencyclopedia.org/entry/Enuma_Elish; John H Walton, <i>The
Lost World of Genesis One: Ancient Cosmology and the Origins Debate.</i>
(Westmont: InterVarsity Press, 2010),
https://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=2030851.</span></p>

</div>

<div id="ftn8" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref8" name="_ftn8" style="mso-footnote-id: ftn8;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[8]</span></span></span></span></a> <i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">The
Lexham Bible Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein,
R., Mangum, D., Sinclair Wolcott, C., … Widder, W. (Eds.). (2016). In The
Lexham Bible Dictionary. Bellingham, WA: Lexham Press.</span></i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">
(Billingham, WA: Leham Press, 2016), o<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>Brian
K. Gamel, “Logos, Greek Background,” ed. John D. Barry et al., LexhamPress.com.</span></p>

</div>

<div id="ftn9" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref9" name="_ftn9" style="mso-footnote-id: ftn9;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[9]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">William
D. Mounce, ed., <i>Mounce’s Complete Expository Dictionary of Old &amp; New
Testament Words</i> (Grand Rapids, Mich: Zondervan, 2006).</span></p>

</div>

<div id="ftn10" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref10" name="_ftn10" style="mso-footnote-id: ftn10;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[10]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Gordon
D. Fee and Robert L. Hubbard, eds., <i>The Eerdmans Companion to the Bible</i>
(Grand Rapids, Mich. ; Cambridge, U.K: W.B. Eerdmans Pub. Co, 2011), 585.</span></p>

</div>

<div id="ftn11" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref11" name="_ftn11" style="mso-footnote-id: ftn11;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[11]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Charles
Gore, Henry Leighton Goudge, and Alfred Guillaume, eds., <i>A NEW COMMENTARY ON
HOLY SCRIPTURE INCLUDING THE APOCRYPHA</i>, Vol. 1, p. iii (New York, NY: The
Macmillan Company, 1928), W. Lock, “The Gospel according to St. John,.”</span></p>

</div>

<div id="ftn12" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref12" name="_ftn12" style="mso-footnote-id: ftn12;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[12]</span></span></span></span></a> <i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Christian
Standard Bible® (CSB)</span></i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;"> (Nashville, Tennessee.: Holman Bible
Pub, 2017), Andreas J. Köstenberger, “John,”; E. Ray Clendenen and Jeremy
Howard, <i>Holman Illustrated Bible Commentary</i> (Broadman &amp; Holman,
2015), Andreas Köstenberger, “John,”; Gordon D. Fee and Douglas K. Stuart, <i>How
to Read the Bible Book by Book: A Guided Tour</i> (Grand Rapids, Mich:
Zondervan, 2002), 304; Robert Jamieson, A. R. Fausset, and David Brown, <i>Commentary
Critical and Explanatory on the Whole Bible (1871)</i> (Oak Harbor, WA: Logos
Research Systems, Inc., 1997), 126.</span></p>

</div>

<div id="ftn13" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref13" name="_ftn13" style="mso-footnote-id: ftn13;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[13]</span></span></span></span></a> <i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Faithlife
Study Bible, via Logos Software</span></i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;"> (Faithlife / Logos Bible Software,
2018), Introduction to John, John D. Barry et al.</span></p>

</div>

<div id="ftn14" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref14" name="_ftn14" style="mso-footnote-id: ftn14;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[14]</span></span></span></span></a> <i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Faithlife
Study Bible, via Logos Software</span></i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">, Craig S. Keener, “The Gospel of John
and the Johannine Letters,”.</span> The Beloved Disciple holds a
place of special honor in John 13:23, and options for who occupied this
position appear limited (though some suggest Lazarus or Thomas). Besides John,
Jesus’ inner circle in the other first-century Gospels included only James, who
was martyred early (Acts 12:2), and Peter, whom John’s Gospel distinguishes
from the Beloved Disciple (John 13:24; 20:4–6)… Differing significantly from
the earlier Synoptic Gospels, the Gospel of John itself took time to gain wide
acceptance, which may suggest John the Elder as its author. However, the son of
Zebedee, by contrast, is clearly close to Jesus and this gives him probable
status as the Beloved Disciple.</p>

</div>

<div id="ftn15" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref15" name="_ftn15" style="mso-footnote-id: ftn15;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[15]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">N. T.
Wright and Michael F. Bird, <i>The New Testament in Its World: An Introduction
to the History, Literature, and Theology of the First Christians</i> (London :
Grand Rapids, MI: SPCK ; Zondervan Academic, 2019), 652–63.</span></p>

</div>

<div id="ftn16" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref16" name="_ftn16" style="mso-footnote-id: ftn16;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[16]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">John
F. Walvoord, Roy B. Zuck, and Dallas Theological Seminary, eds., <i>The Bible
Knowledge Commentary: An Exposition of the Scriptures</i> (Wheaton, Ill: Victor
Books, 1983), Edwin A. Blum, “John,.”</span></p>

</div>

<div id="ftn17" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref17" name="_ftn17" style="mso-footnote-id: ftn17;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[17]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Fee
and Stuart, <i>How to Read the Bible Book by Book</i>, 411.</span> Note: John feels the need to
clarify that John the Baptist is not Jesus; however, never feels the need to
clarify that John the Baptist is not the same as John the Apostle. A possible
indication of John the Apostle being the author, audience familiarity.</p>

</div>

<div id="ftn18" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref18" name="_ftn18" style="mso-footnote-id: ftn18;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[18]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Fee
and Hubbard, <i>The Eerdmans Companion to the Bible</i>, 585.</span></p>

</div>

<div id="ftn19" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref19" name="_ftn19" style="mso-footnote-id: ftn19;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[19]</span></span></span></span></a> <i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Faithlife
Study Bible, via Logos Software</span></i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">, Introduction to John, by John D.
Barry et al.,.</span></p>

</div>

<div id="ftn20" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref20" name="_ftn20" style="mso-footnote-id: ftn20;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[20]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Jamieson,
Fausset, and Brown, <i>Commentary Critical and Explanatory on the Whole Bible
(1871)</i>, 126–27.</span></p>

</div>

<div id="ftn21" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref21" name="_ftn21" style="mso-footnote-id: ftn21;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[21]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Darrell
Wolfe, “Class Assignment: Situational Reconstruction | Philemon” (Paper,
Biblical Background and Interpretation (2021FA-BIBL-2301-ONL), The King’s
University, Southlake, Texas, November 4, 2021),
http://www.darrellwolfe.com/2021/11/class-assignment-situational.html.</span></p>

</div>

<div id="ftn22" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref22" name="_ftn22" style="mso-footnote-id: ftn22;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[22]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Walvoord,
Zuck, and Dallas Theological Seminary, <i>The Bible Knowledge Commentary</i>,
271;<span style="mso-spacerun: yes;">&nbsp;&nbsp; </span>The Prologue (1:1–18).</span></p>

</div>

<div id="ftn23" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref23" name="_ftn23" style="mso-footnote-id: ftn23;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[23]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Mounce,
<i>Mounce’s Complete Expository Dictionary of Old &amp; New Testament Words</i>.</span></p>

</div>

<div id="ftn24" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref24" name="_ftn24" style="mso-footnote-id: ftn24;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[24]</span></span></span></span></a> <i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Lexham
Bible Dictionary</span></i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">, LOGOS, GREEK BACKGROUND.</span></p>

</div>

<div id="ftn25" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref25" name="_ftn25" style="mso-footnote-id: ftn25;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[25]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Mounce,
<i>Mounce’s Complete Expository Dictionary of Old &amp; New Testament Words</i>,
801.</span></p>

</div>

<div id="ftn26" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref26" name="_ftn26" style="mso-footnote-id: ftn26;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[26]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Wilhelm
Gesenius et al., <i>The Abridged Brown-Driver-Briggs Hebrew-English Lexicon of
the Old Testament: From A Hebrew and English Lexicon of the Old Testament.</i>
(Boston; New York: Houghton, Mifflin and Company, 1906).</span></p>

</div>

<div id="ftn27" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref27" name="_ftn27" style="mso-footnote-id: ftn27;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[27]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Tim
Mackie and Jon Collins, “God’s Word, Spirit, &amp; Wisdom Podcast |
BibleProject<sup>TM</sup>,” BibleProject, accessed November 26, 2021,
https://bibleproject.com/podcast/theme-god-e11-gods-word-spirit-wisdom/.</span></p>

</div>

<div id="ftn28" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref28" name="_ftn28" style="mso-footnote-id: ftn28;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[28]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Gore,
Goudge, and Guillaume, <i>A NEW COMMENTARY ON HOLY SCRIPTURE INCLUDING THE
APOCRYPHA</i>, W. Lock, “The Gospel according to St. John,”<span style="mso-spacerun: yes;">&nbsp; </span>((Apostle Andrew (Muratorian Canon))).</span></p>

</div>

<div id="ftn29" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref29" name="_ftn29" style="mso-footnote-id: ftn29;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[29]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Fee
and Hubbard, <i>The Eerdmans Companion to the Bible</i>, Marianne Meye
Thompson, “The Johannine Writings,.”</span> (Not unlike the way some
mislead Christians have praised Donald Trump in the 2016-2022 era). </p>

</div>

<div id="ftn30" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref30" name="_ftn30" style="mso-footnote-id: ftn30;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[30]</span></span></span></span></a> <i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">CSB</span></i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">,
Andreas J. Köstenberger, “John,.”</span></p>

</div>

<div id="ftn31" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref31" name="_ftn31" style="mso-footnote-id: ftn31;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[31]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">N. T.
Wright, <i>Jesus and the Victory of God</i>, 1st North American ed, vol. Vol
2., Christian Origins and the Question of God (Minneapolis, MN: Fortress Press,
1996).</span></p>

</div>

<div id="ftn32" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref32" name="_ftn32" style="mso-footnote-id: ftn32;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[32]</span></span></span></span></a> <i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Faithlife
Study Bible, via Logos Software</span></i><span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">, John D. Barry et al.,.</span></p>

</div>

<div id="ftn33" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref33" name="_ftn33" style="mso-footnote-id: ftn33;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[33]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Tim
Mackie and Jon Collins, “BibleProject<sup>TM</sup> Videos and Podcasts,” God •
Episode 17 Jesus’ Identity in John’s Gospel; and, God • Episode 18 God Q&amp;R
3-Questions About Jesus’ Identity, accessed June 18, 2021, https://bibleproject.com/.</span></p>

</div>

<div id="ftn34" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref34" name="_ftn34" style="mso-footnote-id: ftn34;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[34]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Walvoord,
Zuck, and Dallas Theological Seminary, <i>The Bible Knowledge Commentary</i>,
Edwin A. Blum, “John,.”</span></p>

</div>

<div id="ftn35" style="mso-element: footnote;">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="#_ftnref35" name="_ftn35" style="mso-footnote-id: ftn35;" title=""><span class="MsoFootnoteReference"><span style="mso-special-character: footnote;"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[35]</span></span></span></span></a> <span style="mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">Alan
F. Segal, <i>Two Powers in Heaven: Early Rabbinic Reports about Christianity
and Gnosticism</i>, Studies in Judaism in Late Antiquity, v. 25 (Leiden: Brill,
1977).</span></p>

</div>

</div>

