---
title: 'Discussion Post Q&A: What is "faith"?'
date: '2022-04-26T13:45:00.0010000+00:00'
draft: true
blogger_blog: 'NoHiding.Faith'
blogger_status: 'LIVE'
blogger_post_id: '3481595440414563638'
blogger_filename: '/2022/04/discussion-post-q-what-is-faith.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/NoHiding.Faith/feed.atom'
categories:
  - 'Discussion Post'
  - 'Q&A'
---

<b>Question: What is FAITH?</b><div><br></div><div>Is faith believing a set of truth claims? Having the right doctrine?&nbsp;</div><div><br></div><div>Is faith a belief? I believe this stuff, so I have faith? Signing a statement of faith at your religious school or church, as if that could ensure you're in the right club?&nbsp;</div><div><br></div><div>Is faith a matter of personal conviction? My faith. Your faith. We all have faith in something, don't we? One said.&nbsp;</div><div><br></div><div>Is faith a tool? As the Word of Faith movement likes to say from Hebrews, "Faith is the evidence of things not seen, the substance of their reality... If you have enough faith you can move mountains.... Get your healing... Buy a jet plane or a business or a mansion... Or get your healing... You just need to make it happen by using your faith like a hammer." Is faith a tool like some claim?</div><div><br></div><div>-------------&nbsp;</div><div><br></div><div><b>Answer: Believing Loyalty</b></div><div><br></div><div>How do we arrive at our answer?</div><div><br></div><div>We could cherry pick certain verses that support our theological system, isolate those sentences from the surrounding sentences, the book they're in, and indeed the larger biblical narrative... And then our nice system of theology would sound so clean, so biblical... And this is what we do in the west. From Augustine to Luther to Calvin to Wesley to Charles Fox Parham to Kenneth Hagin, Billy Graham, Ray Comfort, or whoever you favorite voice is... they've all got the new handle on truth by sentence ripping, aka Cherry Picking, they're all convinced it's biblical because they're Bible sentences, and yet each one is followed by a new movement of people who ripped different sentences out snd found the better truth.</div><div><br></div><div>Each and every "system" is built on ripping sentences out of the Bible and stringing them together to make the Bible make claims it may or may not be making (usually isn't making).</div><div><br></div><div>Biblical Theology asks a different question than Systematic Theology: What if we stopped sentence ripping and took in the whole text, cover to cover, to see the larger meta narrative themes?</div><div><br></div><div>The Rabbis look for the hidden treasures buried in narratives, hyperlinks between narratives. A key word or phrase repeated throughout the texts carries all its previous narratives into the new text, carrying all the weight of of that matrix of ideas into the current reading... Strings of pearls.&nbsp;</div><div><br></div><div>A pastor or writer can quote a partial verse, a few sentences of a passage and modern western Christianity would attempt to figure out the meaning of that isolated sentence.&nbsp;</div><div><br></div><div>A Rabbi can quote a partial verse, a few sentences of a passage and their disciples would know to go find that passage, because the UNQUOTED part often carries quite a bit of the meaning the Rabbi was getting at, leaving the student to unburying the treasure. Jesus did this constantly, as a Rabbi himself.</div><div><br></div><div>So when we look at the whole book, original languages, and original contexts... What do we find?&nbsp;</div><div><br></div><div>Pistis/Faith was a Greek term, it was the faithfulness one would give to a covenant partner or master or patron. Faithfulness might be a better rendering. It was decidedly NOT intellectual assent to a belief statement list.&nbsp;</div><div><br></div><div>Throughout the biblical narratives, Genesis to Revelation, the theme is "you shall have no other gods"... As Dr Michael Heiser says, "there are no Ba'al worshipers in heaven". Revelation ends with the ultimate choose a side narrative.&nbsp;</div><div><br></div><div>Whether you lived a thousand years before Jesus came or 2022 years after, there has only really been one primary ask:</div><div><br></div><div>Hear, Yisrael, the Lord your God is one (could be rendered primary or best), serve him alone.&nbsp;</div><div><br></div><div>Renounce Ba'al, serve Yahweh only.&nbsp;</div><div><br></div><div>Renounce Zues serve Yahweh only.&nbsp;</div><div><br></div><div>Renounce Buddhism, Hinduism, Secular Humanism, Atheism, Agnosticism, Passive I Don't Care Ism...</div><div><br></div><div>Faith has less to do with intellectual assent to ideas and more to do with choosing an active participation in a relationship with Yahweh.</div><div><br></div><div>One is faithful to Yahweh. As a Jew, living in 800BC, that meant Torah observance. And as a Jew in 2022, it might mean a modified Torah observance, that's an active debate.&nbsp;</div><div><br></div><div>As a Gentile, living in 2022, it means know who your God is, love God, Love your neighbor, and don't be a donkey's behind to people.&nbsp;</div><div><br></div><div>Or, as Heiser calls that whole concept:</div><div><br></div><div><b>Believing Loyalty&nbsp;&nbsp;</b></div><div><b><br></b></div><div><b>#Faith #Belief #BelievingLoyalty&nbsp;</b></div>