---
title: '1 Corinthians 11:27-29 has nothing AT ALL to do with personal salvation.'
date: '2023-09-10T19:45:00.0040000+00:00'
draft: true
blogger_blog: 'NoHiding.Faith'
blogger_status: 'LIVE'
blogger_post_id: '1097303434054411207'
blogger_filename: '/2023/09/1-corinthians-1127-29-has-nothing-at.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/NoHiding.Faith/feed.atom'
---

<p>&nbsp;Reposting my answer for a forum question:</p><br />1 Corinthians 11:27-29 has nothing AT ALL to do with personal salvation. <br /><br />It was an admonition to the Corinthians to self-examine their actions, motives, and conduct in regards to the community of Jesus. Something modern western Christians have a hard time with (thanks or no-thanks to Luther and Calvin) is realizing that the invitation into "The Kingdom of God", Jesus' Kingdom, is first and foremost a community call before it is an individual call. <br /><br />You are being invited into a community. The "Lord's Supper" was a full meal, not a thimble of bread and juice. It was a weekly celebration of this new community where everyone shared what they had and operated as a single chosen family. Baptism, likewise, is a symbolic practice whereby someone announces they are dying to their old life and becoming a member of this new family, and the family receives them into the family. <br /><br />This is why the jailer could bring his whole family into baptism at one time, because this wasn't about "accepting individual salvation so we can go to heaven when we die" but about an announcement that they (as a family) would now be loyal to this God and join his family of fellow Jesus followers. <br /><br />Just like with circumcisions, which made you a part of Israel's family but did not guarantee that you would remain faithful to the family, these two practices are family practices first, before they are individual. On a personal note, this is why I don't consider tiny pieces of bread and thimbles of juice to be a true Lord's Supper at al, but a plastic imitation of one.<br /><br /><br /><a href="https://www.bible.com/bible/107/1CO.11.27.NET" target="_blank">1 Corinthians 11:27 NET</a><br />For this reason, whoever eats the bread or drinks the cup of the Lord in an unworthy manner will be guilty of the body and blood of the Lord.<p><br /></p><p><br /></p><p class="p13" style="margin-left: 0rem; min-height: 16px; text-indent: 1.5rem;"><b>Darrell Wolfe,&nbsp;<a href="http://www.nohiding.faith/p/blog-page.html" target="_blank">Storyteller at NoHiding.Faith</a></b></p><p class="p13" style="margin-left: 0rem; min-height: 16px; text-indent: 1.5rem;"><br style="font-family: &quot;Sitka Text&quot;; font-size: 16px;" /></p>