---
title: 'Class Assignment: What is the gospel, according to Luke-Acts?'
date: '2024-06-09T12:48:00.0050000+00:00'
draft: true
blogger_blog: 'NoHiding.Faith'
blogger_status: 'LIVE'
blogger_post_id: '7147814742275954334'
blogger_filename: '/2024/06/class-assignment-what-is-gospel_98.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/NoHiding.Faith/feed.atom'
categories:
  - 'Gospel'
---

Assignment: Without referencing any other New Testament writer, but you can reference any Hebrew Bible writer that the gospel author himself references, what is the gospel according to...<div><br /></div><div>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span class="MsoBookTitle"><span style="font-size: 16.0pt; line-height: 200%;">Gospel Reading:
Luke</span></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Darrell
Wolfe<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Literature,
The King’s University<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Life
of Jesus (BIBL-2302)<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Professor
Jason Moraff<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">November
8, 2020</span></p>

<h1 style="line-height: 150%;">Questions<o:p></o:p></h1>

<p class="MsoListParagraphCxSpFirst" style="line-height: 150%; margin-left: .25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->1.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>11:33-36 – I could conjecture, but I’m still vague on what
he means about the light of the eye. When we see but not seeing, but, what’s
the actual advice or command here? How do I get my eye lit?<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="line-height: 150%; margin-left: .25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->2.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>I found myself making more observations than asking
questions today.<o:p></o:p></p>

<h1 style="line-height: 150%;">Observations<o:p></o:p></h1>

<p class="MsoListParagraphCxSpFirst" style="line-height: 150%; margin-left: .25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>More than any other Gospel, the term “Holy Spirit” comes up
frequently. Even before Jesus is born, the Holy Spirit is an active member of
the story.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: 150%; margin-left: .25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>4:6 – Jesus never denies that Satan has the authority to
give, only that it was not how he would wrest it from him. Interesting to note
when we consider “why bad things happen” on earth. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: 150%; margin-left: .25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>Ch. 6 – I found myself uncomfortable, in light of election
season, comparing my attitudes to those Jesus commands. Loving my enemies was
not the forethought in my mind, as I prepared mentally for the USA Civil War
II.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: 150%; margin-left: .25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>Ch. 9 – How often have I heard one side (Republicans &amp;
Democrats) so angry at the other that they wanted to cause physical harm to
them or their possessions? Yet, Jesus tells us he is not here to burn the enemy
camp down, but to save them. His enemies are not enemies at all, but captives
that need Freedom.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: 150%; margin-left: .25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>14:26 – Makes so much more sense in light of our readings
about first century disciples preferring their Rabbi over their own father.
This is a cultural reference and amplified (like his reference to not just
adultery but even lust is sin). <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: 150%; margin-left: .25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>16:11 – Never noticed this before, if you are not
disciplined with your budget and earthly money/income, you will not be trusted
with more. Those wanting to serve God must start by getting their own house in
order. <o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="line-height: 150%; margin-left: .25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>23:25 – They were expecting a king to free them from Roman
rule. They did not just ask for a murder in place of Jesus (picture of
forgiveness of sins), they asked for someone (a rebellion leader) who was more
like the image they had of their Messiah. They asked for a false Messiah in
place of the real one, one that would mold to their own ideas about what
Messiah should be.<o:p></o:p></p>

<span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;"><br clear="all" style="mso-special-character: line-break; page-break-before: always;" />
</span>

<p class="MsoNormal"><b><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">&nbsp;</span></b></p>

<h1 style="line-height: 200%;">The Gospel According to Luke<o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">Luke presents to
us a very Jewish Jesus, rooted in the history of his people and in prophecy. We
are well into the story before the Jesus who ministered for three and a half
years is introduced onto the scene. After his victory in temptation Jesus is
immediately rejected by his own, a paradox. Throughout his ministry, he
preaches the Kingdom of God and heals the sick. He then sends his disciples
(not just the 12, but the 70 as well) to do the same. These miracles establish
his authority. Luke takes his time, builds the character of Jesus through
interactions with various types of people. He also shows us why the leaders of
the religious sects of the day hated him so much as to kill him. We see him sit
at the table in a Pharisees own house, then condemn the entire group for their
behavior. Meanwhile, we see Jesus take pity on the least of those in his midst.
He makes a point to observe a widow and comment on her giving, show us that we
must serve those we come across on the road who have been abused by others (Good
Samaritan). Even at the end, as he is being arrested, we see him healing the
ear of his captor. Luke ends with the punchline, as though nothing was
understood by the disciples until this very last moment. Jesus had to die and
rise again, so that the message of repentance and remission of sins could be
taken to the whole world. Luke’s Good News is that the Kingdom of God,
established and confirmed through signs, results in repentance and remission of
sins through Jesus’ death and resurrection.&nbsp;&nbsp;<o:p></o:p></p><br /><br /><br /><span style="font-family: &quot;tempus sans itc&quot;;">Shalom&nbsp;<span face="sans-serif" style="background-color: white; color: #202122; font-size: 14px;">שָׁלוֹם</span>: Live Long and Prosper!</span><br /><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe</span></div>Storyteller | Writer | Thinker | Consultant | Freelancer | Bible Nerd</div>