---
title: 'More on the Rapture and the Antichrist... notes by Eng-Wong (PhD Candidate) and Dr. Ok'
date: '2025-06-11T04:23:00.0040000+00:00'
draft: true
blogger_blog: 'NoHiding.Faith'
blogger_status: 'LIVE'
blogger_post_id: '6382698278974487652'
blogger_filename: '/2025/06/more-on-rapture-and-antichrist-notes-by.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/NoHiding.Faith/feed.atom'
categories:
  - 'Class Discussion Posts'
---

<p class="MsoNormal">I'm re-posting this for my later reference... it is from my Professor and TA...&nbsp;</p><span></span><p class="MsoNormal"><br /></p><span><!--more--></span><p class="MsoNormal"><br /></p><p class="MsoNormal"><b><a href="https://fuller.instructure.com/courses/13477/users/15486">Janette Ok</a><o:p></o:p></b></p>

<p class="MsoNormal">Posted Jun 9, 2025 10:26am<o:p></o:p></p>

<p class="MsoNormal">Discussion Topic: More on the Rapture and the Antichrist</p>

<p class="MsoNormal"><i>Friends,</i><o:p></o:p></p>

<p class="MsoNormal"><i>Eng-Wong (PhD Candidate), my TA for the in-person NT500
class, has shared this helpful follow-up to my last lecture on Revelation. I
wanted to share it with you since I think many of you will find it helpful.
David will also be grading some of the Final Exam Projects, so I wanted to
introduce you to him here as well. / Blessings, Dr. Ok&nbsp;</i><o:p></o:p></p><p class="MsoNormal"><span></span></p><!--more--><i><br /></i><p></p>

<p class="MsoNormal">Hey everyone,<o:p></o:p></p>

<p class="MsoNormal">In the last lecture, Dr. Ok mentioned that Revelation never
specifically mentions the Rapture or the Antichrist. Some folks were curious
about the topic so I've put together a quick blurb and some additional
resources for y'all to check out if you're curious.&nbsp;<o:p></o:p></p>

<p class="MsoNormal">First, regarding the Rapture, the primary Scriptural
reference that its proponents appeal to is 1 Thess 4:16-17. Revelation makes no
mention of any kind of "snatching up" of believers (though see Rev
11:1-14 for the prophecy(?)/vision(?) of the two witnesses who are killed by
the beast but then raised to life and taken up into heaven on a cloud). So
consult some commentaries on 1 Thess on that particular passage.<o:p></o:p></p>

<p class="MsoNormal">The history of reception of the Rapture in Christian history
is pretty spotty. Perhaps the earliest Christian argument for it is in
Irenaeus's&nbsp;<i>Against Heresies</i>&nbsp;in chapter 29 where he states that
the Church will be "caught up" prior to the suffering mentioned by
Jesus in Matt 24:21. He makes no appeal to 1 Thess, but a combination of ideas
from Genesis (Enoch being taken up), 2 Kings (Elijah's ascent on the chariot),
and Dan 3 (the three friends' survival of the fiery furnace). A few others
through history bring up the idea, but it is never a wide-stream view until the
19th century, through the work of John Darby. Through his work and the establishment
of the Plymouth Brethren, the Rapture becomes widely popularized in the UK and
North America. Since then, a few views of the Rapture have been offered
including pre-tribulation, mid-tribulation, and post-tribulation. If you really
want to learn about the Rapture, I suggest studies in Christian History more
than in Biblical Studies.<o:p></o:p></p>

<p class="MsoNormal">Regarding the term "Antichrist," the name is often
conflated with the false prophet, the beast, and Satan in Revelation, but its
only literal occurrence is in 1 John and 2 John. In the Johannine literature,
the Antichrist is just that--the anti-Christ--the one who goes against the
teachings of Christ. Hence, as 1 John 2:18 indicates, there can be many
antichrists. The antichrist is the "the one who denies the Father and the
Son" (1 John 2:22c, NRSVUE). The term is also related to the "man of
lawlessness" in 2 Thess inasmuch as they are described as enemies of God
and God's people. Though unlike the man of lawlessness or the beast, the
Antichrist is not necessarily an end-time figure. All of these figures are not
exactly described in the same manner and so they indicate different warnings
that the authors give to their audiences. We should be careful not to conflate
them to give due respect to their contexts.<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoNormal">Some references for further reading:</p>

<p class="MsoNormal"><a href="https://fuller.on.worldcat.org/oclc/1047729199" target="_blank">Atkenson - Exporting the Rapture: John Nelson Darby and the
Victorian Conquest of North American EvangelicalismLinks to an external site.</a><o:p></o:p></p>

<p class="MsoNormal">A study on Darby and his contribution to the spread of the
idea of the Rapture and dispensationalism.<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoNormal"><a href="https://fuller.on.worldcat.org/oclc/1004623898" target="_blank">Hultberg, Blaising, Moo - Three Views on the Rapture:Pretribulation, Prewrath, or PosttribulationLinks to an external site.</a><o:p></o:p></p>

<p class="MsoNormal">If you want to understand modern views of the Rapture in the
Anglophone world, this debate is helpful to understand how proponents argue
their positions.<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoNormal"><a href="https://fuller.on.worldcat.org/oclc/1294151549" target="_blank">Cohen - The Salvation of Israel: Jews in Christian Eschatology
from Paul to the PuritansLinks to an external site.</a><o:p></o:p></p>

<p class="MsoNormal">The role of Israel in Christian eschatology has been highly
contested and Christians have unfortunately weaponized eschatology against the
Jews at times. This book is helpful in uncovering some of the complex and
contradictory ways that ideas like the Antichrist have been misused in regard
to Christian/Jewish relations.<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoNormal"><a href="https://research-ebsco-com.fuller.idm.oclc.org/linkprocessor/plink?id=8784c5b1-38ad-3865-bdd5-0461869dc2d8" target="_blank">Nichols - "Prophecy Makes Strange Bedfellows: On the
History of Identifying the Antichrist"Links to an external site.</a><o:p></o:p></p>

<p class="MsoNormal">A helpful article that traces some of the historical
development of the idea of the Antichrist.<o:p></o:p></p>

<p class="MsoNormal"><br /></p>

