---
title: 'Jesus: Human and Divine'
date: '2025-02-02T01:22:00.0040000+00:00'
draft: true
blogger_blog: 'NoHiding.Faith'
blogger_status: 'LIVE'
blogger_post_id: '3483877350632693947'
blogger_filename: '/2025/02/jesus-human-and-divine.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/NoHiding.Faith/feed.atom'
categories:
  - 'Class Discussion Posts'
  - 'Armchair Theology'
---

<h4>Class Discussion Question: Why did God send Jesus Christ to <span class="Heading4Char">Earth</span> with perfect humanity and perfect
divinity?</h4>

<p class="MsoNormal"><br />
</p><h4 style="text-align: left;"><b>My Thoughts…</b></h4><p></p>

<p class="MsoNormal">Nowhere is the practice of diving into the biblical author’s
worldview more fascinating than the role of Jesus as the Human-God/God-Human. <o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<h4 style="text-align: left;"><b>Portraits in Tanakh</b></h4>

<p class="MsoNormal">Throughout the Tankah (Hebrew Bible), the writers painted
portraits of the relationship between YHWH and Israel (and humanity). All the
portraits of the Tanakh tell the stories of Yahweh’s attempts to co-reign with
his human imagers. At core, that is the singular message of the biblical
authors. <b>God. With. Us.</b> It is what Genesis 1-11 sets up as the prime
narrative, and it is the undercurrent in every other narrative.<o:p></o:p></p>

<p class="MsoNormal">The Prologue (Gen 1-11) provides poetic symbolism of Yahweh
creating a space for humanity and joining His space to humanity’s space, and
the separation/exile/death that came as a result of human and lesser elohim
rebellions. To be separated, exiled, from Yahweh’s space is to experience
death. Physical death is merely the final separation from the spaces where
Yahweh’s domain and Earth’s domains overlap. And it is the hope of the later
writers that a day would come in which the living and the dead would return to
this overlapping space.<o:p></o:p></p>

<p class="MsoNormal">But throughout the stories of Abraham, Isaac, Jacob, David,
Isaiah, Daniel, Ruth, and so many others, we see portraits of Yahweh “with us”
(1 Kings 8:57; 2 Chr 13:12; Isa 7:14, 8:8; Matt 1:23). Yahweh frequently made
physical appearances, and sometimes there was a muddying of the invisible and
visible Yahweh. But in all cases, the sense was a Yahweh who wanted to be with
us. Ezekial played the role of Son of Man, who would intercede for Yahweh among
his people. Isaiah say a Yahweh-empowered Israelite who would both suffer and
redeem.<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<h4 style="text-align: left;"><b>Each portrait pulled from previous threads but added new
facets.</b></h4>

<p class="MsoNormal">“A number of Jewish writers ca. 516 BC—AD 70 offered
opinions as to the identity of the “second Yahweh,” the second power in heaven”<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn1" name="_ftnref1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[1]</span></span><!--[endif]--></span></a> Heiser
worked this out in detail in his book Unseen Realm where he noted “The
startling reality is that long before Jesus and the New Testament, careful
readers of the Old Testament would not have been troubled by the notion of,
essentially, two Yahwehs—one invisible and in heaven, the other manifest on
earth in a variety of visible forms, including that of a man. In some instances
the two Yahweh figures are found together in the same scene.”.<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn2" name="_ftnref2" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[2]</span></span><!--[endif]--></span></a> He
also references the earlier work of Segal on the development of this thought in
Second Temple literature among the rabbis.<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn3" name="_ftnref3" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[3]</span></span><!--[endif]--></span></a><o:p></o:p></p>

<p class="MsoNormal">Also during this period, the sages and rabbis of various
movements, including the sects at Qumran, were pondering the Tanakh and other
writings, and asking what Yahweh might be doing in their day or what kind of
expectation they should hold. Some portraits speak of Messiah ben David, “the
reigning Kind who will bring peace to the world”; while some portraits speak of
Messiah ben Joseph, who is “the Suffering Servant”.<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn4" name="_ftnref4" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[4]</span></span><!--[endif]--></span></a> <o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<h4 style="text-align: left;"><b>Along comes Jesus</b></h4>

<p class="MsoNormal">Then came a rabbi from Nazareth, a small nothing town in the
north. Rabbi Yeshua (English-Jesus / Greek - Iesus) came teaching in much the
same way as his intellectual kin, the Pharisees. They did not view him as an
outsider, but as an insider. They saw him as worth their time to debate (as
debating each other on the finer points of Torah observance was their primary activity).
Rabbi Yeshua challenged them but also respected them. Some resisted him, while
other (like Nicodemus) followed The Way of Rabbi Yeshua. <o:p></o:p></p>

<p class="MsoNormal">Yeshua showed the ways in which these earlier portraits that
promised a “God with Us” were being filled-full in his presence among them (Luke
4:21). He went on to say that even the story of Jonah was a means of referring
to the larger story Yahweh was working through him (Matt 12:40, Jonah 1:17-2:1).
The Dictionary of Jesus and the Gospels notes that the gospel authors
emphasized the ways in which Yeshua did the works that only Yahweh could do.<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn5" name="_ftnref5" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[5]</span></span><!--[endif]--></span></a><o:p></o:p></p>

<p class="MsoNormal">The gospel writers wrestle with showing Yeshua’s language
and claims in portraits. To borrow a paragraph from my own post on this thread
about the “I AM” statements of Jesus equating himself with Yahweh while also
referring to the Father and Himself as separate individuals:<o:p></o:p></p>

<p class="MsoNormal" style="margin-left: .5in;"><i>// The Dictionary of Jesus and
the Gospels makes note of “three instances in Mark’s Gospel where Jesus’
pronouncement of egō eimi belongs to the narrative’s gradual unfolding of his
identity (Mk 6:50; 13:6; 14:62).”<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn6" name="_ftnref6" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><b><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[6]</span></b></span><!--[endif]--></span></a>
John’s gospel goes further by noting Jesus to say, “The Father and I are one”
(John 10:30).<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn7" name="_ftnref7" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><b><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[7]</span></b></span><!--[endif]--></span></a>
Paul calls Jesus “the image of the invisible God” (Col 1:10).<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn8" name="_ftnref8" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><b><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[8]</span></b></span><!--[endif]--></span></a>//<o:p></o:p></i></p>

<p class="MsoNormal">Yeshua makes the same statements about the Holy Spirit being
a person and not just a force, and yet equally Yahweh. <o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<h4 style="text-align: left;"><b>So what are we to do with these portraits? </b></h4>

<p class="MsoNormal">Messianic Judaism has dedicated the largest portion of their
scholarship and writing interacting with what they see as errors in both
Gentile Christianity and Non-Jesus-Believing modern Judaism. They have taught
me to live in the tension, acknowledge the various portraits, and not feel the
need to draw arbitrary lines in the sand about them.<o:p></o:p></p>

<p class="MsoNormal">Do we need to label these, or can we simply live in the
meditative tension of them? If we must label them, “Trinity” or “God-Head” seem
like they work well enough for me. But I tend not to use that verbiage, as I
prefer to refer people to the portraits. We can analyze a painting, or we can
simply soak it in. I think I’m in the soaking phase of my journey. <o:p></o:p></p>

<p class="MsoNormal">Shalom, Darrell<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<div><br /></div><div><br /></div><div><!--[if !supportFootnotes]--><h4 style="text-align: left;"><b>Notes:</b></h4>

<hr align="left" size="1" width="33%" />

<!--[endif]-->

<div id="ftn1">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref1" name="_ftn1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[1]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;PdJudEuM&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;{\\i{}The
Lexham Bible Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein,
R., Mangum, D., Sinclair Wolcott, C., \\uc0\\u8230{} Widder, W. (Eds.). (2016).
In The Lexham Bible Dictionary. Bellingham, WA: Lexham Press.} (Billingham, WA:
Leham Press, 2016), \\uc0\\u167{}Michael S. Heiser, \\uc0\\u8220{}Divine
Council,\\uc0\\u8221{} SubSection \\uc0\\u8220{}The Second Power in
Heaven/Second Yahweh,\\uc0\\u8221{}
LexhamPress.com.&quot;,&quot;plainCitation&quot;:&quot;The Lexham Bible
Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein, R., Mangum,
D., Sinclair Wolcott, C., … Widder, W. (Eds.). (2016). In The Lexham Bible
Dictionary. Bellingham, WA: Lexham Press. (Billingham, WA: Leham Press, 2016),
§Michael S. Heiser, “Divine Council,” SubSection “The Second Power in
Heaven/Second Yahweh,”
LexhamPress.com.&quot;,&quot;noteIndex&quot;:45},&quot;citationItems&quot;:[{&quot;id&quot;:59,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/GM87FDTW&quot;],&quot;itemData&quot;:{&quot;id&quot;:59,&quot;type&quot;:&quot;book&quot;,&quot;event-place&quot;:&quot;Billingham,
WA&quot;,&quot;publisher&quot;:&quot;Leham
Press&quot;,&quot;publisher-place&quot;:&quot;Billingham,
WA&quot;,&quot;title&quot;:&quot;The Lexham Bible Dictionary - Barry, J. D.,
Bomar, D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott, C., …
Widder, W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham, WA:
Lexham Press.&quot;,&quot;title-short&quot;:&quot;Lexham Bible
Dictionary&quot;,&quot;URL&quot;:&quot;LexhamPress.com&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2016&quot;]]}},&quot;locator&quot;:&quot;Michael
S. Heiser, “Divine Council,” SubSection \&quot;The Second Power in
Heaven/Second
Yahweh\&quot;&quot;,&quot;label&quot;:&quot;section&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><i>The Lexham Bible Dictionary - Barry, J.
D., Bomar, D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott,
C., … Widder, W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham,
WA: Lexham Press.</i>
(Billingham, WA: Leham Press, 2016), §Michael S. Heiser, “Divine Council,”
SubSection “The Second Power in Heaven/Second Yahweh,” LexhamPress.com.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn2">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref2" name="_ftn2" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[2]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;WalyB70D&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Heiser,
{\\i{}The Unseen Realm}, 134\\uc0\\u8211{}135 &gt; Notes &gt; The startling
reality is that long before Jesus and the New Testament, careful readers of the
Old Testament would not have been troubled by the notion of, essentially, two
Yahwehs\\uc0\\u8212{}one invisible and in heaven, the other manifest on earth
in a variety of visible forms, including that of a man. In some instances the
two Yahweh figures are found together in the same scene. In this and chapter
that follows, we\\uc0\\u8217{}ll see that the \\uc0\\u8220{}Word\\uc0\\u8221{}
was just one expression of a visible Yahweh in human form.1 The concept of a
Godhead in the Old Testament has many facets and layers.2 After the birth of
his promised son, Isaac, Abraham\\uc0\\u8217{}s spiritual journey includes a
divine figure that is integral to Israelite Godhead thinking: the Angel of
Yahweh. Although the most telling passages that show this angel as a visible embodiment
of the very presence of Yahweh occur later than the time of Abraham, there are
early hints of his nature during the lifetimes of Abraham and his sons. 1 The
Jewish community that inherited the Old Testament was well aware of this. For
centuries Judaism felt no discomfort with the notion of two Yahweh figures. The
idea was referred to as the \\uc0\\u8220{}two powers in heaven\\uc0\\u8221{}
and was endorsed within Judaism until the second century AD. It is important to
note that the two powers were both holy. This is not dualism, where two equal
deities exist, one good, the other evil. The major work on
Judaism\\uc0\\u8217{}s two-powers teaching was published originally in 1971 by
the late Alan Segal. Segal was Jewish and his career focused on Second Temple
and Rabbinic Judaism. His work documents how the two-powers idea became a
heresy in Judaism in the second century AD. It was recently reprinted. See Alan
F. Segal, Two Powers in Heaven: Early Rabbinic Reports about Christianity and
Gnosticism (reprint, Waco, TX: Baylor University Press, 2012). The Old
Testament roots of the two-powers doctrine were one of the major focus points
of my doctoral dissertation. The logic of the two Yahweh figures in the Old
Testament reflects an Israelite adaptation of the Canaanite structuring of the
top tier of the Canaanite divine council. See Michael S. Heiser,
\\uc0\\u8220{}The Divine Council in Late Canonical and Non-Canonical Second
Temple Jewish Literature\\uc0\\u8221{} (PhD diss., University of Wisconsin\\uc0\\u8211{}Madison,
2004).<span style='mso-spacerun:yes'>  </span>2 The conception of a Godhead in
orthodox Israelite thought, interpreted in the context of the wider Canaanite
environment, was a focus of my dissertation. That material has been revised and
put forth in an article accepted for publication at the time of this writing:
Michael S. Heiser, \\uc0\\u8220{}Co-Regency in Ancient Israel\\uc0\\u8217{}s
Divine Council as the Conceptual Backdrop to Ancient Jewish Binitarian
Monotheism,\\uc0\\u8221{} (forthcoming in the Bulletin for Biblical Research).
I will post that article (presuming permission from BBR) on the companion
website when it appears. The data and discussion go considerably beyond what
appears in this book.&quot;,&quot;plainCitation&quot;:&quot;Heiser, The Unseen
Realm, 134–135 &gt; Notes &gt; The startling reality is that long before Jesus
and the New Testament, careful readers of the Old Testament would not have been
troubled by the notion of, essentially, two Yahwehs—one invisible and in
heaven, the other manifest on earth in a variety of visible forms, including
that of a man. In some instances the two Yahweh figures are found together in
the same scene. In this and chapter that follows, we’ll see that the “Word” was
just one expression of a visible Yahweh in human form.1 The concept of a
Godhead in the Old Testament has many facets and layers.2 After the birth of
his promised son, Isaac, Abraham’s spiritual journey includes a divine figure
that is integral to Israelite Godhead thinking: the Angel of Yahweh. Although
the most telling passages that show this angel as a visible embodiment of the
very presence of Yahweh occur later than the time of Abraham, there are early
hints of his nature during the lifetimes of Abraham and his sons. 1 The Jewish
community that inherited the Old Testament was well aware of this. For
centuries Judaism felt no discomfort with the notion of two Yahweh figures. The
idea was referred to as the “two powers in heaven” and was endorsed within
Judaism until the second century AD. It is important to note that the two
powers were both holy. This is not dualism, where two equal deities exist, one
good, the other evil. The major work on Judaism’s two-powers teaching was
published originally in 1971 by the late Alan Segal. Segal was Jewish and his
career focused on Second Temple and Rabbinic Judaism. His work documents how
the two-powers idea became a heresy in Judaism in the second century AD. It was
recently reprinted. See Alan F. Segal, Two Powers in Heaven: Early Rabbinic
Reports about Christianity and Gnosticism (reprint, Waco, TX: Baylor University
Press, 2012). The Old Testament roots of the two-powers doctrine were one of
the major focus points of my doctoral dissertation. The logic of the two Yahweh
figures in the Old Testament reflects an Israelite adaptation of the Canaanite
structuring of the top tier of the Canaanite divine council. See Michael S.
Heiser, “The Divine Council in Late Canonical and Non-Canonical Second Temple
Jewish Literature” (PhD diss., University of Wisconsin–Madison, 2004).<span
style='mso-spacerun:yes'>  </span>2 The conception of a Godhead in orthodox
Israelite thought, interpreted in the context of the wider Canaanite
environment, was a focus of my dissertation. That material has been revised and
put forth in an article accepted for publication at the time of this writing:
Michael S. Heiser, “Co-Regency in Ancient Israel’s Divine Council as the
Conceptual Backdrop to Ancient Jewish Binitarian Monotheism,” (forthcoming in
the Bulletin for Biblical Research). I will post that article (presuming
permission from BBR) on the companion website when it appears. The data and
discussion go considerably beyond what appears in this
book.&quot;,&quot;noteIndex&quot;:46},&quot;citationItems&quot;:[{&quot;id&quot;:20,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/7SP8XMJB&quot;],&quot;itemData&quot;:{&quot;id&quot;:20,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS680.S86
H45 2015&quot;,&quot;edition&quot;:&quot;First
edition&quot;,&quot;event-place&quot;:&quot;Bellingham,
WA&quot;,&quot;ISBN&quot;:&quot;978-1-57799-556-2&quot;,&quot;note&quot;:&quot;OCLC:
ocn907177749&quot;,&quot;number-of-pages&quot;:&quot;413&quot;,&quot;publisher&quot;:&quot;Lexham
Press&quot;,&quot;publisher-place&quot;:&quot;Bellingham,
WA&quot;,&quot;source&quot;:&quot;Library of Congress ISBN&quot;,&quot;title&quot;:&quot;The
unseen realm: recovering the supernatural worldview of the
Bible&quot;,&quot;title-short&quot;:&quot;The unseen
realm&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Heiser&quot;,&quot;given&quot;:&quot;Michael&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2015&quot;]]}},&quot;locator&quot;:&quot;-134–135
&gt; Notes &gt; The startling reality is that long before Jesus and the New
Testament, careful readers of the Old Testament would not have been troubled by
the notion of, essentially, two Yahwehs—one invisible and in heaven, the other
manifest on earth in a variety of visible forms, including that of a man. In
some instances the two Yahweh figures are found together in the same scene. In
this and the chapter that follows, we’ll see that the “Word” was just one
expression of a visible Yahweh in human form.1 The concept of a Godhead in the
Old Testament has many facets and layers.2 After the birth of his promised son,
Isaac, Abraham’s spiritual journey includes a divine figure that is integral to
Israelite Godhead thinking: the Angel of Yahweh. Although the most telling
passages that show this angel as a visible embodiment of the very presence of
Yahweh occur later than the time of Abraham, there are early hints of his
nature during the lifetimes of Abraham and his sons. 1 The Jewish community
that inherited the Old Testament was well aware of this. For centuries Judaism
felt no discomfort with the notion of two Yahweh figures. The idea was referred
to as the “two powers in heaven” and was endorsed within Judaism until the
second century AD. It is important to note that the two powers were both holy.
This is not dualism, where two equal deities exist, one good, the other evil.
The major work on Judaism’s two-powers teaching was published originally in
1971 by the late Alan Segal. Segal was Jewish and his career focused on Second
Temple and Rabbinic Judaism. His work documents how the two-powers idea became
a heresy in Judaism in the second century AD. It was recently reprinted. See
Alan F. Segal, Two Powers in Heaven: Early Rabbinic Reports about Christianity
and Gnosticism (reprint, Waco, TX: Baylor University Press, 2012). The Old Testament
roots of the two-powers doctrine were one of the major focus points of my
doctoral dissertation. The logic of the two Yahweh figures in the Old Testament
reflects an Israelite adaptation of the Canaanite structuring of the top tier
of the Canaanite divine council. See Michael S. Heiser, “The Divine Council in
Late Canonical and Non-Canonical Second Temple Jewish Literature” (PhD diss.,
University of Wisconsin–Madison, 2004).<span style='mso-spacerun:yes'> 
</span>2 The conception of a Godhead in orthodox Israelite thought, interpreted
in the context of the wider Canaanite environment, was a focus of my
dissertation. That material has been revised and put forth in an article
accepted for publication at the time of this writing: Michael S. Heiser,
“Co-Regency in Ancient Israel’s Divine Council as the Conceptual Backdrop to
Ancient Jewish Binitarian Monotheism,” (forthcoming in the Bulletin for
Biblical Research). I will post that article (presuming permission from BBR) on
the companion website when it appears. The data and discussion go considerably
beyond what appears in this
book.&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Heiser, <i>The Unseen Realm</i>, 134–135
&gt; Notes &gt; The startling reality is that long before Jesus and the New
Testament, careful readers of the Old Testament would not have been troubled by
the notion of, essentially, two Yahwehs—one invisible and in heaven, the other
manifest on earth in a variety of visible forms, including that of a man. In
some instances the two Yahweh figures are found together in the same scene. In
this and chapter that follows, we’ll see that the “Word” was just one
expression of a visible Yahweh in human form.1 The concept of a Godhead in the
Old Testament has many facets and layers.2 After the birth of his promised son,
Isaac, Abraham’s spiritual journey includes a divine figure that is integral to
Israelite Godhead thinking: the Angel of Yahweh. Although the most telling
passages that show this angel as a visible embodiment of the very presence of
Yahweh occur later than the time of Abraham, there are early hints of his
nature during the lifetimes of Abraham and his sons. 1 The Jewish community
that inherited the Old Testament was well aware of this. For centuries Judaism
felt no discomfort with the notion of two Yahweh figures. The idea was referred
to as the “two powers in heaven” and was endorsed within Judaism until the
second century AD. It is important to note that the two powers were both holy.
This is not dualism, where two equal deities exist, one good, the other evil.
The major work on Judaism’s two-powers teaching was published originally in
1971 by the late Alan Segal. Segal was Jewish and his career focused on Second
Temple and Rabbinic Judaism. His work documents how the two-powers idea became
a heresy in Judaism in the second century AD. It was recently reprinted. See
Alan F. Segal, Two Powers in Heaven: Early Rabbinic Reports about Christianity
and Gnosticism (reprint, Waco, TX: Baylor University Press, 2012). The Old
Testament roots of the two-powers doctrine were one of the major focus points
of my doctoral dissertation. The logic of the two Yahweh figures in the Old
Testament reflects an Israelite adaptation of the Canaanite structuring of the
top tier of the Canaanite divine council. See Michael S. Heiser, “The Divine
Council in Late Canonical and Non-Canonical Second Temple Jewish Literature”
(PhD diss., University of Wisconsin–Madison, 2004).&nbsp; 2 The conception of a Godhead in orthodox
Israelite thought, interpreted in the context of the wider Canaanite
environment, was a focus of my dissertation. That material has been revised and
put forth in an article accepted for publication at the time of this writing:
Michael S. Heiser, “Co-Regency in Ancient Israel’s Divine Council as the
Conceptual Backdrop to Ancient Jewish Binitarian Monotheism,” (forthcoming in
the Bulletin for Biblical Research). I will post that article (presuming
permission from BBR) on the companion website when it appears. The data and
discussion go considerably beyond what appears in this book.</p>

</div>

<div id="ftn3">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref3" name="_ftn3" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[3]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;qOiXI2x4&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Alan
F. Segal, {\\i{}Two Powers in Heaven: Early Rabbinic Reports about Christianity
and Gnosticism}, Studies in Judaism in Late Antiquity v. 25 (Leiden: Brill,
1977).&quot;,&quot;plainCitation&quot;:&quot;Alan F. Segal, Two Powers in
Heaven: Early Rabbinic Reports about Christianity and Gnosticism, Studies in
Judaism in Late Antiquity v. 25 (Leiden: Brill,
1977).&quot;,&quot;noteIndex&quot;:47},&quot;citationItems&quot;:[{&quot;id&quot;:247,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/JT6L2X7K&quot;],&quot;itemData&quot;:{&quot;id&quot;:247,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BM646
.S44&quot;,&quot;collection-number&quot;:&quot;v.
25&quot;,&quot;collection-title&quot;:&quot;Studies in Judaism in late
antiquity&quot;,&quot;event-place&quot;:&quot;Leiden&quot;,&quot;ISBN&quot;:&quot;978-90-04-05453-0&quot;,&quot;number-of-pages&quot;:&quot;313&quot;,&quot;publisher&quot;:&quot;Brill&quot;,&quot;publisher-place&quot;:&quot;Leiden&quot;,&quot;source&quot;:&quot;Library
of Congress ISBN&quot;,&quot;title&quot;:&quot;Two powers in heaven: early
rabbinic reports about Christianity and
Gnosticism&quot;,&quot;title-short&quot;:&quot;Two powers in
heaven&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Segal&quot;,&quot;given&quot;:&quot;Alan
F.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1977&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Alan F. Segal, <i>Two Powers in Heaven:
Early Rabbinic Reports about Christianity and Gnosticism</i>, Studies in
Judaism in Late Antiquity v. 25 (Leiden: Brill, 1977).<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn4">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref4" name="_ftn4" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[4]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;WhOgIZ9v&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;John
B. Metzger, {\\i{}Discovering the Mystery of the Unity of God: A Theological
Study on the Plurality and Tri-Unity of God in the Hebrew Scriptures} (John
Metzger, www.Ariel.org, 2010), 846, www.PromisesToIsrael.org,www.Ariel.org,
https://www.logos.com/product/8050/discovering-the-mystery-of-the-unity-of-god.&quot;,&quot;plainCitation&quot;:&quot;John
B. Metzger, Discovering the Mystery of the Unity of God: A Theological Study on
the Plurality and Tri-Unity of God in the Hebrew Scriptures (John Metzger,
www.Ariel.org, 2010), 846, www.PromisesToIsrael.org,www.Ariel.org,
https://www.logos.com/product/8050/discovering-the-mystery-of-the-unity-of-god.&quot;,&quot;noteIndex&quot;:45},&quot;citationItems&quot;:[{&quot;id&quot;:2510,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/LZBPB2LZ&quot;],&quot;itemData&quot;:{&quot;id&quot;:2510,&quot;type&quot;:&quot;book&quot;,&quot;ISBN&quot;:&quot;978-1-935174-06-6&quot;,&quot;language&quot;:&quot;En&quot;,&quot;number-of-pages&quot;:&quot;936&quot;,&quot;publisher&quot;:&quot;John
Metzger, www.Ariel.org&quot;,&quot;title&quot;:&quot;Discovering the Mystery of
the Unity of God: A Theological Study on the Plurality and Tri-unity of God in
the Hebrew Scriptures&quot;,&quot;title-short&quot;:&quot;Discovering the
Mystery of the Unity of
God&quot;,&quot;URL&quot;:&quot;www.PromisesToIsrael.org,www.Ariel.org,
https://www.logos.com/product/8050/discovering-the-mystery-of-the-unity-of-god&quot;,&quot;author&quot;:[{&quot;literal&quot;:&quot;John
B.
Metzger&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2010&quot;]]}},&quot;locator&quot;:&quot;846&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->John B. Metzger, <i>Discovering the
Mystery of the Unity of God: A Theological Study on the Plurality and Tri-Unity
of God in the Hebrew Scriptures</i> (John Metzger, www.Ariel.org, 2010), 846,
www.PromisesToIsrael.org,www.Ariel.org,
https://www.logos.com/product/8050/discovering-the-mystery-of-the-unity-of-god.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn5">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref5" name="_ftn5" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[5]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;0Ti6AZxr&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Adams,
{\\i{}Dictionary of Jesus and the Gospels (IVP Bible Dictionary)}, n. G. H.
Twelftree, \\uc0\\u8220{}Miracles and Miracle Stories,\\uc0\\u8221{}, Pg
594.&quot;,&quot;plainCitation&quot;:&quot;Adams, Dictionary of Jesus and the
Gospels (IVP Bible Dictionary), n. G. H. Twelftree, “Miracles and Miracle
Stories,”, Pg 594.&quot;,&quot;noteIndex&quot;:48},&quot;citationItems&quot;:[{&quot;id&quot;:1733,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/M8HBMIBX&quot;],&quot;itemData&quot;:{&quot;id&quot;:1733,&quot;type&quot;:&quot;book&quot;,&quot;collection-title&quot;:&quot;IVP
Bible Dictionary&quot;,&quot;event-place&quot;:&quot;Downers
Grove&quot;,&quot;publisher&quot;:&quot;IVP&quot;,&quot;publisher-place&quot;:&quot;Downers
Grove&quot;,&quot;title&quot;:&quot;Dictionary of Jesus and the Gospels (IVP
Bible
Dictionary)&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Adams&quot;,&quot;given&quot;:&quot;Paul&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2016&quot;]]}},&quot;locator&quot;:&quot;
- G. H. Twelftree, “Miracles and Miracle Stories,”, Pg
594&quot;,&quot;label&quot;:&quot;note&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Adams, <i>Dictionary of Jesus and the
Gospels (IVP Bible Dictionary)</i>, n. G. H. Twelftree, “Miracles and Miracle
Stories,”, Pg 594.<!--[if supportFields]><span style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn6">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref6" name="_ftn6" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[6]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;xpO7e6fe&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Paul
Adams, {\\i{}Dictionary of Jesus and the Gospels (IVP Bible Dictionary)}, IVP
Bible Dictionary (Downers Grove: IVP, 2016), \\uc0\\u167{}C. H. Williams,
\\uc0\\u8220{}\\uc0\\u8216{}I Am\\uc0\\u8217{} Sayings,\\uc0\\u8221{} Pg
396.&quot;,&quot;plainCitation&quot;:&quot;Paul Adams, Dictionary of Jesus and
the Gospels (IVP Bible Dictionary), IVP Bible Dictionary (Downers Grove: IVP,
2016), §C. H. Williams, “‘I Am’ Sayings,” Pg 396.&quot;,&quot;noteIndex&quot;:39},&quot;citationItems&quot;:[{&quot;id&quot;:1733,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/M8HBMIBX&quot;],&quot;itemData&quot;:{&quot;id&quot;:1733,&quot;type&quot;:&quot;book&quot;,&quot;collection-title&quot;:&quot;IVP
Bible Dictionary&quot;,&quot;event-place&quot;:&quot;Downers
Grove&quot;,&quot;publisher&quot;:&quot;IVP&quot;,&quot;publisher-place&quot;:&quot;Downers
Grove&quot;,&quot;title&quot;:&quot;Dictionary of Jesus and the Gospels (IVP
Bible Dictionary)&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Adams&quot;,&quot;given&quot;:&quot;Paul&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2016&quot;]]}},&quot;locator&quot;:&quot;C.
H. Williams, “‘I Am’ Sayings,”, Pg 396&quot;,&quot;label&quot;:&quot;section&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Paul Adams, <i>Dictionary of Jesus and
the Gospels (IVP Bible Dictionary)</i>, IVP Bible Dictionary (Downers Grove:
IVP, 2016), §C. H. Williams, “‘I Am’ Sayings,” Pg 396.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn7">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref7" name="_ftn7" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[7]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;paxm9CdU&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;{\\i{}LEB},
v. John 10:30.&quot;,&quot;plainCitation&quot;:&quot;LEB, v. John 10:30.&quot;,&quot;noteIndex&quot;:36},&quot;citationItems&quot;:[{&quot;id&quot;:1483,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/7TLSBX8Q&quot;],&quot;itemData&quot;:{&quot;id&quot;:1483,&quot;type&quot;:&quot;book&quot;,&quot;collection-title&quot;:&quot;Harris,
W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A.,
&amp; Wierenga, M. (Eds.)&quot;,&quot;edition&quot;:&quot;Logo Bible
Software&quot;,&quot;event-place&quot;:&quot;Bellingham, WA&quot;,&quot;publisher&quot;:&quot;Lexham
Press&quot;,&quot;publisher-place&quot;:&quot;Bellingham,
WA&quot;,&quot;source&quot;:&quot;Logo Bible
Software&quot;,&quot;title&quot;:&quot;The Lexham English Bible (LEB), Fourth
Edition&quot;,&quot;title-short&quot;:&quot;LEB&quot;,&quot;URL&quot;:&quot;http://www.lexhampress.com&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2010&quot;]],&quot;season&quot;:&quot;Copyright<span
style='mso-spacerun:yes'>  </span>, 2012, 2013 Lexham
Press&quot;}},&quot;locator&quot;:&quot;- John 10:30&quot;,&quot;label&quot;:&quot;verse&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><i>LEB</i>, v. John 10:30.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn8">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref8" name="_ftn8" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[8]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;JLEBEqwI&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;{\\i{}LEB},
v. Col 1:10.&quot;,&quot;plainCitation&quot;:&quot;LEB, v. Col 1:10.&quot;,&quot;noteIndex&quot;:37},&quot;citationItems&quot;:[{&quot;id&quot;:1483,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/7TLSBX8Q&quot;],&quot;itemData&quot;:{&quot;id&quot;:1483,&quot;type&quot;:&quot;book&quot;,&quot;collection-title&quot;:&quot;Harris,
W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A.,
&amp; Wierenga, M. (Eds.)&quot;,&quot;edition&quot;:&quot;Logo Bible
Software&quot;,&quot;event-place&quot;:&quot;Bellingham,
WA&quot;,&quot;publisher&quot;:&quot;Lexham Press&quot;,&quot;publisher-place&quot;:&quot;Bellingham,
WA&quot;,&quot;source&quot;:&quot;Logo Bible
Software&quot;,&quot;title&quot;:&quot;The Lexham English Bible (LEB), Fourth
Edition&quot;,&quot;title-short&quot;:&quot;LEB&quot;,&quot;URL&quot;:&quot;http://www.lexhampress.com&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2010&quot;]],&quot;season&quot;:&quot;Copyright<span
style='mso-spacerun:yes'>  </span>, 2012, 2013 Lexham
Press&quot;}},&quot;locator&quot;:&quot;- Col 1:10&quot;,&quot;label&quot;:&quot;verse&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><i>LEB</i>, v. Col 1:10.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

</div><br /><br />

<span style="font-family: &quot;tempus sans itc&quot;;">Shalom&nbsp;<span face="sans-serif" style="background-color: white; color: #202122; font-size: 14px;">שָׁלוֹם</span>: Live Long and Prosper!</span>
<br />

<div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe</span>
</div>

Storyteller | Writer | Thinker | Consultant | Freelancer | Bible Nerd
<i>*Written withs some editing and research assistance from ChatGPT-4o</i>
<br /><br /><br />

