---
title: 'About Us'
date: '2017-11-28T05:57:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Creatively Unique Arts'
blogger_status: 'LIVE'
blogger_page_id: '8752313048676323556'
blogger_filename: '/p/about-us.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Creatively Unique Arts/feed.atom'
---

<div>
<br /></div>
<div>
Flavia Wolfe (Artist/Crafter/Creator):</div>
<div>
<br /></div>
I have always enjoyed making something out of nothing... whether it was sewing, painting, photography, or any other medium available. I am always trying new things and I like to put my twist on them. I not only want to use my hands, and my heart and my imagination; I want to encourage you to do the same. <br /><br />A part of the joy, for many artists and crafters, is knowing that someone else enjoys the things that you make. After spending time planning and creating, knowing that your time and efforts bring a smile to someone else is a great feeling.&nbsp;<div>
<br /></div>
<div>
My husband and I knew that we wanted to homeschool our children and that it would mean only one income for our home. So, we decided that finding an outlet for what seemed to be more of a hobby was something we wanted to look into. And that is how Creatively Unique Arts came to be. He came up with the name of my business and has helped me every step of the way.&nbsp;</div>
<div>
<br /></div>
<div>
From there my mom and I started working together and created another store and decided that working together would be fun.<br /><br />For me, Art and Craft are an extension of myself and a way to interact with the world. When I am not working on something, I am thinking about what I want to make next. There will rarely be a time when I am selling only one type of thing, as I am always interested in learning something new.&nbsp;</div>
<div>
<br /></div>
<div>
My husband calls me a Mixed Medium Artist because I like to combine two totally separate ideas/mediums into one piece. Unlike some, who are known as the one who always does "Bags" or "Hats", I will always be testing the boundaries of art, craft, and creations of various kinds.<br /><br />My Mom, JoAnn (Crafter/Creator):<br /><br />JoAnn says: I am a crafter and have been for many years. I moved to Idaho some time ago and have started gardening and canning. I have two little dogs and a hardworking husband.&nbsp;</div>
<div>
<br /></div>
<div>
I am also a certified massage therapist, a Zumba instructor, and a full-time Grandma. Not only is this fun, but a way to work with my daughter. In Idaho, I sell items at local stores and farmers markets. I am currently learning how to knit and I am excited to see what I will be able to create.<br /><br />JoAnn &amp; Flavia (and the boys):<br />Together, we communicate almost daily, talking about our day, what we are making and what we are thinking about making next. We collaborate as much as possible. We have always wanted to work together and now is the time. We hope you enjoy our stores as much as we enjoy the creative process and the joy of working together.&nbsp;</div>
<div>
<br /></div>
<div>
Thank you - Blessings, Flavia &amp; JoAnn</div>
