---
title: 'Olivier''s Vision Book'
date: '2012-02-09T06:25:00.0000000+00:00'
draft: true
blogger_blog: '1520923594909568292'
blogger_status: 'LIVE'
blogger_post_id: '2760541486110568138'
blogger_filename: '/2012/02/oliviers-vision-book.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/1520923594909568292/feed.atom'
categories:
  - 'Reminder'
  - 'Random'
  - 'Revelation'
  - 'Idea'
  - 'Vision'
---

Whether you use this or not is not my business, but I felt led to set it up as a seed planted into your future.<br />
<br />
This website is "Private", which means only those added as authors to the website can see or read it. You can write anything that comes to mind, call it your online journal if you'd like. When writing a new post you will see to the far right "Labels". If you click there you can either choose from the ones I pre-set, or just write in the box with a coma between each word for a new label.<br />
<br />
Pages: You also have the option of adding up to around 10 "Static Pages", meaning pages that are always there at the top. You will see on your blog dash board both options "Pages" and "Posts". Pages are like the one I started for you always located up at the top "About", for example.<br />
<br />
Posts are just like pages... they can be as long or as short as you like, they are essentially articles you write to yourself. You can organize types of articles by giving them labels, which years later are easily retrievable by clicking on that label and pulling up all like articles.<br />
<br />
I included links to websites and "RSS Feeds" from various ministries. Feel free to keep or remove them, but I always find it a fun way to keep up with those ministries that have pages with updates. I didn't know who you do or don't listen to these days so I pulled from the the Heritage&nbsp;Usual's&nbsp;that I remembered, and a few of my fav's.<br />
<br />
I imagine, even if you didn't spend hours/years praying about your gift and calling, that you have thought about it. I imagine you have certain verses of scripture that have impacted you more than others. You know there are things you are called to do, maybe they need defining. There are things you know that you are NOT called to do, that can be just as important.<br />
<br />
When you identify your calling, your core, all decisions become based on that core. Pastor Art talked about that one day when he talked about not being called to outdoor tent meetings, but being called to teach pastors. You can talk to him more about identifying your core.<br />
<br />
I hope this helps get you started my brother, have fun. Let me know if you need help with anything, and I'll remove myself as soon as you are ready to take it on your own.<br />
<br />
In love, your brother, Darrell G. Wolfe&nbsp;<a href="http://n2gs.blogspot.com/p/about-n2gs.html">http://n2gs.blogspot.com/p/about-n2gs.html</a><br />
<br />
<br />
<br />
<br />