---
title: 'Untitled Post'
date: '2019-02-22T18:08:00.0000000+00:00'
draft: false
categories:
  - 'bible'
  - 'Daily Reading'
  - 'Freedom'
---

The Gospel of Luke:<br />
<br />
Jesus was in the temple asking questions, his parents had been clueless and lost him. But he went home, was obedient to them, and grew in favor...<br />
<br />
As I read that story, I was reminded of what it was like to grow up with a high IQ and more wisdom than average...<br />
<br />
I realized, as I was meditating on this story, that God will ask you to submit to authority that often doesn't understand you and may not even be as intelligent as you... But submit you must if you will find maturity and favor.<br />
<br />
How often do we buck authority because we think we know better?<br />
<br />
Submission brings maturity and favor that all the intellect in the world can't bring.<br />
<br />
Selah.<br />
<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span></div>
<div class="MsoNormal">
<br /></div>
<br />
<br />
