---
title: 'Book Reflection: Saving the Bible from Ourselves'
date: '2019-05-24T04:48:00.0000000+00:00'
draft: false
categories:
  - 'Books'
---

<div style="text-align: center;"><br /></div><div style="text-align: center;"><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="https://ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&amp;OneJS=1&amp;Operation=GetAdHtml&amp;MarketPlace=US&amp;source=ss&amp;ref=as_ss_li_til&amp;ad_type=product_link&amp;tracking_id=198020052007-20&amp;language=en_US&amp;marketplace=amazon&amp;region=US&amp;placement=0830851240&amp;asins=0830851240&amp;linkId=8a8f7ad8f25b7fa1d23b126a7c581cd4&amp;show_border=true&amp;link_opens_in_new_window=true" style="height: 240px; width: 120px;"></iframe></div><div style="text-align: center;"><br /></div><div style="text-align: center;"><br /></div><h2 style="text-align: center;">Saving the Bible from Ourselves - <a href="https://amzn.to/30FmLOm" target="_blank">Buy Now</a></h2><div style="text-align: center;"><br /></div><div style="text-align: center;"><br /></div><h4>Review: Saving the Bible</h4>This is a review of the text, Saving the Bible from Ourselves (Paauw, 2016). Paauw begins by diagnosing a strongly felt problem throughout the Church in Western Culture. He summarizes it as follows:<br /><blockquote class="tr_bq">“But we are also assured that even if we spend only a few minutes in the morning, we’re sure to find the spiritual gem to get us through. The Bible will brighten our day, encourage us and strengthen us, if only we will faithfully open it – even if just for a few moments. Those ‘Scriptures’ – which more typically refer to presorted sentences and snippets – are said to be powerful. And Yet. We know there is more to the story than the official line… The ‘and yet’ comes down to this: There is more guilt about secret non-compliance with Bible-reading standards in the self-proclaimed Bible-believing community than there is gratitude for promises realized.” (Paauw, 2016), 14-15.</blockquote>With this simple statement, he accurately defines a problem I’ve lived with my entire Christian life. Paauw then goes on to describe the reasons for this problem in more detail.<br /><br /><div><h4>We Complicated the Bible</h4>The Bible we know today has chapters, verses, headers, commentary, footnotes, cross references, blurbs of insight, photos, graphs, and maps… to name a few. But exactly none of these are from the original copies of the Great Book. The books of the Bible were written as texts, poems, letters, histories, stories, and revelations. These additives have hidden the real Bible from us, underneath layers of items that are helpful for Study but not for daily Reading. The result has been the average reader taking a “verse” as having read “scripture”. However, these books were intended to be read as any other book. Start on page one, and read forward.<br />We Lost the History, Context, Story, and Narrative<br /><br />As a result of these additives and the “versification” of the Bible, we’ve lost the stories being told, the context and audience, the history of a real people in real places, the ongoing non-stop narrative flowing from Adam to Abraham to Jesus to Paul to Me.</div><div><h4>We Lost the Community</h4>The Bible was originally digested, primarily, in public gatherings. The original church didn’t have a book to hand to each person. Scrolls and codices were kept in safe places, and read publicly in large readings. Whole letters and books (or sections of the books) were read to those in attendance, and then they were discussed as a group. Pastoral leaders added insights and kept the conversation on track. Messages were given ad-hoc based on the texts read. This stands in stark contrast to our practices today, one verse from here and another from there, packaged as though they went together as stand-alone statements; all while reading them alone in pre-packaged apps or devotionals. We are each left to interpret as we will, without the benefit of community input.</div><div><h4>We Lost the Elegance and Beauty</h4>One of the subtle items we’ve lost is the elegance of the Bible. This is a combined book of Histories, Stories of Greatness, Poetry, Songs, and more. By having standard block text formatting with the insertion of chapters and verses, much of this is lost on the reader; even if they do try to read whole books or sections (as I have). Paauw proposes a new look that takes each of these literary styles, and brings them to light in a new formatting for modern English readers.<br /><br /><br /><br /><br /><br /><h3 style="text-align: center;">The Take Aways</h3><h4>I’m a Student.</h4>I have often read whole books of the Bible and read the entire Bible through several times. I’ve spent months in a single book. I’ve even spent the last several years reading and re-reading the book of Job. Therefore, I appreciate what’s lost eating in verse-fragments as we so often do in our culture. However, that’s all study. It’s tearing down sentences to the root-words and looking for context and meaning. What I haven’t done is simply pick up the Bible and read (as I would a novel). As a result of reading this text, I ordered the Immerse: Messiah New Testament (Institute for Bible Reading, 2017). This is a project that Paauw himself worked on, as a response to the challenges he laid out in his text. I’m also having my kids read their own copies, and gave a few to friends.</div><div><h4>I’m a Storyteller.</h4>Throughout my life, one thread has weaved its way through my many adventures: I am a Storyteller. I enjoy story. The art of storytelling is the back-bone of every great movie, book, TV Ad, or Speech. When good stories are told, they capture the imagination. I’ve forgotten most of the 10-steps to this or 7-habits of that… but I can still feel the heat of Mordor as Frodo battles with himself to let go of the One Ring. This text was a fabulous reminder that I am part of an ongoing story myself. It began with my Father, Adam. It continued throughout history through men and women, great and small, and led directly to my bedroom, where I was saved at three years old; asking Jesus for Wisdom just like Solomon did.</div><div><h4>I’m a Solo-Artist (no longer).</h4>Finding community is a new challenge for me. As a fairly extreme introvert, INFJ (Briggs, 1920), I find myself constantly “in my head”. If I don’t have mass amounts of quality quiet time to process all of my thoughts, I begin to feel fatigued and overwhelmed. However, I allowed this knowledge of myself (and some unhealthy dynamics with my late-wife) to become excuses for hibernation. I went to work, church, and home. I spent decades without real human interaction outside of the home. This came to a head at the end of 2016 in Fort Worth Texas, when I suffered a nervous breakdown (mid-life crises some call it). My road to recovery began as a challenge to God. I couldn’t attend any of the men’s bible studies as they conflicted with my schedule. I told God I’d go if a 9 pm start time was posted. It was posted the next week.&nbsp;</div><div><br /></div><div>At Rudy’s Bible study, we would read a whole chapter from a New Testament book, then discuss what each of us got out of it. I was shocked to realize, while reading Paauw’s text, that this was essentially the format of the original Church. I’ve subsequently ordered two more copies and sent them back to Rudy and Eric (the leaders of that group). Since moving to Idaho, my isolationist tendencies have been challenged in new ways. I’m finding community once more. But this was a strong reminder that I need community and community Bible reading, and a challenge to maybe start my own 9 pm group here… we shall see.</div><div><br /></div><br /><br /><br /><br /><br /><span style="font-family: &quot;tempus sans itc&quot;;"></div>
