---
title: 'Final Paper: A Christian Worldview | Be Still & Be Led'
date: '2019-05-04T07:00:00.0000000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '9015122686758166954'
blogger_filename: '/2019/05/final-paper-christian-worldview-be.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'bible'
  - 'Armchair Theology'
---

<h3>
A Christian Worldview | Be Still &amp; Be Led</h3>
<blockquote class="tr_bq">
“It takes a good theologian to help you misunderstand the Bible.” Jesse (Duplantis, Unknown)</blockquote>
<br />
We discussed many individual topics within the Christian Worldview course. The texts, Elements of a Christian Worldview (Palmer, 1998, 2013) and Mere Christianity (Lewis, 1952, 1980) forced us to look at things like sex and sexuality; politics, the place of literature, art, and entertainment/media in the life of a Christian, and what it means to “work hard/play hard”. How does one choose an individual topic to focus on? What one topic deserves our focused attention? It was as I pondered the Week 6 discussion questions about having discernment in our times to interact with Christ and Culture, that I realized the topic I needed to write about.&nbsp; Rather than address a single topic from the text Elements of a Christian Worldview (Palmer, 1998, 2013), we can all of them in a simple statement: Be Still &amp; Be Led.<br />
<br />
Jesus simplified all the commandments and prophets down to Love God &amp; Love Folks. As Christians, we’ve made a big fat mess of things again. We know we are not under “the law”; and yet, we have managed to totally frustrate and confuse the entire process of being a Christian. We’ve added tons of content to God’s Word (chapters, verses, headers, commentary, footnotes, cross-references, cute sayings, inspirational images) (Paauw, 2016). We’ve created entire schools dedicated to studying and debating the thinkers of Church History. We’ve managed to debate amongst ourselves whether it’s okay for a Christian to eat pork, watch movies, drink alcohol, wear certain clothing, participate in certain activities or even professions.<br />
<br />
We can divide all of the topics of the text and subject of Worldviews down to three primary categories, Shaping our Worldview, Shaping our Character, Shaping our World. Each of these can be summarized by the statement Be Still &amp; Be Led. Jesus did not do or say anything unless he saw the Father doing or saying it ((NIV), p. John 5:19).<br />
<br />
<h4>
Shaping our Worldview</h4>
<blockquote class="tr_bq">
For as many as are led by the Spirit of God, these are sons of God. Romans 8:14 ((NIV))</blockquote>
<br />
Our Worldview is ultimately shaped by many things. As Michael D. Palmer points out on page 24, everyone has a Worldview but not everyone possesses a well thought through Worldview (Palmer, 1998, 2013). Our worldviews are shaped by the people, places, and profound experiences of our lives. By studying and considering our thought processes, we can become more self-aware and chose a Worldview that is authentic to the Truth we see before us and in us.<br />
<br />
Studying the Bible, Biblical Scholars, Christian History, and Christian Thinkers, we can become better informed as we ponder many of life’s big questions. However, there is One who knows Truth. We know in part until we are forever in His Presence. Therefore, there is ultimately only One who can lead us to a view of the world that is authentic, right, true, and pure… God the Father, the Son, and the Holy Spirit.<br />
<br />
How do we find that voice, in the midst of the crowded noisy lives we lead? What makes it possible to cut through the lies we’ve inherited from our culture, broken lenses we inherited from our parents or upbringing, and distorted lenses we inherited from our woundedness? Only the Voice Himself can cut that deep. And the only way to hear Him is to Practice His Presence; or, to Be Still &amp; Be Led. As we are still, hearing His voice, he can open up the things we’ve learned and studied and help us see what was worth keeping and what must be laid aside.<br />
<br />
<h4>
Shaping our Character</h4>
<blockquote class="tr_bq">
A good character is the best tombstone. Charles (Spurgeon)</blockquote>
<br />
Character is ultimately the result of choices; however, those choices are a result of our deepest held beliefs (Palmer, 1998, 2013, p. 290).&nbsp; Those beliefs that lie deepest within us are often not planted there by God but rather by our pain, past experiences, and fallen human nature. When we decide how we will treat our fellow man we know inside of us what is the “right” thing to do. As C.S. Lewis points out in his first chapter, the law of God is written on our hearts even if we haven’t been saved yet (Lewis, 1952, 1980). However, we often still make the choice that is contrary to that law due to our sinful nature. As believers, we are no longer subject to the sinful nature and we are obligated to follow the leading of the Holy Spirit and do right. Many times, the right thing isn’t as clear as it could be. Is it right to wear this particular outfit on this particular occasion? The answer is often “it depends”.<br />
<br />
Only by being following the constant creed of Be Still &amp; Be Led can we get the Holy Spirit’s opinion on the matter in the moment. By doing so, we can weed out and brush aside all of the well-reasoned and “good” arguments for why we must or mustn’t do a particular thing and simply follow His leading in the moment. In other words, we can lay aside the business of “trying harder our knowledge of Good” because that is the wrong tree entirely anyway. Rather, we can plug into the Tree of Life, get a download that applies to us in this moment and simply do that.<br />
<br />
<h4>
Shaping our World</h4>
<br />
<blockquote class="tr_bq">
Music can change the world because it can change people. (Bono)</blockquote>
<br />
<span style="white-space: pre;"> </span>What is Bono saying, really? He is saying that minds do not change until hearts do. I have seen men won to Christ through Apologetics and then just as quickly won away from Christ through equally compelling intellectual ideas. It’s seldom true that these men were saved in heart; rather, their minds were temporarily convinced to “become Christians”. However, when a heart is won into a relationship with Jesus that heart is not easily swayed even while the mind is still confused.<br />
Music touches the heart in a way that intellect never will, that is the truth Bono is touching above. So it is in our walk with Jesus and the impact we can have on the world around us, our life should not be a dry text to be studied but a song to be heard. It must be a song that people cannot ignore and find themselves humming long after the audible music has stopped (we leave their presence).<br />
Our lives cannot be that song without the indwelling presence of the Holy Spirit in the everyday choices we make. As we navigate the cumulative choices we have before us, they lead us into careers and callings. The industries we choose, companies we choose, churches we choose, and individuals we choose to interact with, will all be influenced by how well we hear that still small voice telling us “go left” ((NIV), p. Isaiah 30:12).<br />
<br />
When I am at work and someone is making fun of my Christian Worldview, I can try to convince them with my superior well-reasoned logic (which I’ve done many times) but I risk losing the person while I win the debate. I have often won debates this way but never won a single heart with this method. On the other hand, I can listen to their story, ask them questions, and set a part of myself to the side to listen, be still, and hear what the Holy Spirit is saying in that moment and speak that. Those are the moments that hearts change while the mind is catching up to what has already happened.<br />
<br />
When I am working with my sons on how they treat each other, I can lay down dictates about what the Bible says; or, I can listen to the Holy Spirit reveal to me the heart conditions they are each dealing with and then help them really see each other and give them tools to communicate more effectively.<br />
<br />
When I am struggling with singleness in my near-forties, married twice before and now widowed, I can use logic and reason to determine that the Bible really meant its dictates on sex for young couples who are procreating, or I can listen to the Holy Spirit tell me that I will lose the opportunity to reach their hearts if I fail this test. This is an example of what C.S. Lewis warns about in his treatment of Social Morality:<br />
<br />
<blockquote class="tr_bq">
Most of us are not really approaching the subject in order to find out what Christianity says; we are approaching it in the hope of finding support from Christianity for the view of our own party. We are looking for an ally where we are offered either a Master of a Judge. (Lewis, 1952, 1980) Page 87</blockquote>
<br />
Does it matter if we see that movie, wear those clothes, eat that food, drink that, work there? In many cases, these are not answered by blanket regulations in the Bible as New Testament believers. Even the general truths that run like threads throughout may seem blurry against the hyper-specific choices before us. The only way we will have confidence in our choices is by Being Still and Being Led. Hearts are not changed by convincing arguments but by radical intervention of the Holy Spirit and we are allowed to be conduits of that power to the world around us. I am the best tool for World Changing when I am the purest conduit of His Voice.<br />
<br />
<blockquote class="tr_bq">
Hearing God’s Voice has become the singular quest of my heart, the sole pursuit that alone satisfies the great longings of my heart… Things don’t change when I talk to God; things change when God talks to me… So the power of prayer is found, not in convincing God of my agenda, but in waiting upon Him to hear His agenda. (Sorge, 2001, p. 11)</blockquote>
<br />
Thus, I believe my greatest ambition and sole requirement is to Be Still &amp; Be Led.<br />
 <br />
<h4>
Bibliography</h4>
<br />
(NIV), N. I. (n.d.). Retrieved from https://www.biblica.com/bible/niv/proverbs/2/<br />
Bono. (n.d.). Retrieved from Read more at: https://www.brainyquote.com/quotes/bono_141199?src=t_change_the_world0<br />
Duplantis, J. (Unknown). Southwest Believers Convention. Fort Worth, TX: It's in my notes but I don't know what year I wrote it down.<br />
Lewis, C. S. (1952, 1980). Mere Christianity. New York, NY: Harper Collins Publishers.<br />
Paauw, G. R. (2016). Saving the Bible from Ourselves. Downers Grove, IL: InterVarsity Press.<br />
Palmer, M. D. (1998, 2013). Elements of a Christian Worldview. Springfield, Missouri: Logion Press.<br />
Sorge, B. (2001). Secrets of the Secret Place. Grandview, MO: Oasis House.<br />
Spurgeon, C. (n.d.). Retrieved from Read more at: https://www.brainyquote.com/quotes/charles_spurgeon_106282?src=t_good_character<br />
<br />
<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span></div>
