---
title: 'FINAL PAPER |  The Storiented Bible | The Greatest Story Ever Told'
date: '2019-02-28T08:59:00.0050000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3727767781552352679'
blogger_filename: '/2019/02/final-paper-storiented-bible-greatest.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Class Assignment'
  - 'Biblical Studies'
---

<h2 style="text-align: center;">
The Storiented Bible</h2>
<h3 style="text-align: center;">
The Greatest Story Ever Told</h3>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
FINAL PAPER&nbsp;</div>
<br />
<br />
<div style="text-align: center;">
Darrell Wolfe&nbsp;</div>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
BIBL-1300 Introduction to the Bible&nbsp;</div>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
Spring 2019, Online Session 1&nbsp;</div>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
February 27, 2019&nbsp;</div>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
<b>Table of Contents&nbsp;</b></div>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
<a href="https://d.docs.live.net/6a09c1440da84011/TKU/Introduction%20to%20the%20Bible/Final%20Paper_The%20Storiented%20Bible_Darrell%20Wolfe.docx#_Toc2209133">Introduction.. 3</a> </div>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
<a href="https://d.docs.live.net/6a09c1440da84011/TKU/Introduction%20to%20the%20Bible/Final%20Paper_The%20Storiented%20Bible_Darrell%20Wolfe.docx#_Toc2209134">We Are Wired for Story.. 3</a> </div>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
<a href="https://d.docs.live.net/6a09c1440da84011/TKU/Introduction%20to%20the%20Bible/Final%20Paper_The%20Storiented%20Bible_Darrell%20Wolfe.docx#_Toc2209135">The Bible Is Story.. 5</a> </div>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
<a href="https://d.docs.live.net/6a09c1440da84011/TKU/Introduction%20to%20the%20Bible/Final%20Paper_The%20Storiented%20Bible_Darrell%20Wolfe.docx#_Toc2209136">Interpreting Our Story in The Story.. 7</a> </div>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
<a href="https://d.docs.live.net/6a09c1440da84011/TKU/Introduction%20to%20the%20Bible/Final%20Paper_The%20Storiented%20Bible_Darrell%20Wolfe.docx#_Toc2209137">Conclusion.. 8</a> </div>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
<br /></div>
<h4>
Introduction</h4>
<div style="text-align: center;">
In the beginning, the Word already existed. The Word was with God, and the Word was God. (Immerse, 2017) John, page 399&nbsp;</div>
<div style="text-align: center;">
<br /></div>
Notice that John begins his gospel by calling Jesus, The Word. We find Words, and the stories they create for us, impact us at a level that is beyond our cognitive ability to understand in the moment. Being caught up in a story can make you lose all sense of present, and be transported to another time and place (and sometimes another world entirely).<br />
<br />
Ever since Aristotle observed that stories had a beginning, a middle, and an end, the science of story has been developed and studied. Our modern sensibilities tell us at a gut level whether a story “works” or it doesn’t. We are hard-wired for story, and it is through story that we understand the World around us. It is no accident that God gave us a Bible full of story, as opposed to a user manual or guide (if this, then do that). God has given us His Story, His Narrative, and we are to find our place in it. It is only when we understand The Narrative, The Story, that we are able to accurately interpret our place in that Story, and what God is telling us today.<br />
<br />
<div>
<h4>
We Are Wired for Story</h4>
<blockquote class="tr_bq">
There is no “world” for us until we have named and languaged and storied whatever is. Amos Wilder (Paauw, 2016, p. 109) </blockquote>
Our brains are hard-wired for story, and our bodies respond to it. Forbes published an article titled This is Your Brain on Storytelling, in which the author breaks down the neurochemical responses in our brains that create Awareness, Arousal, and Action. They are Cortisol (Awareness), Dopamine (Arousal/Pleasure/Reward), Oxytocin (Call to Action/Empathetic Behavior) (Rodriguez, 2017).&nbsp;</div>
<div>
<br /></div>
<div>
These chemicals provide us with physiological responses to storytelling and stir us to take actions in response. If I say Frodo, the vast majority of movie-going audiences understand that means a small hobbit from the Shire, going on an epic quest with a band of friends to destroy the One Ring. Many Bible students have read Pilgrim’s progress, an allegorical tale of Christian. Stories stick with us, due in part to these God-given chemical responses in our brains. In her TEDx Talk, Wired for Story, Lisa Cron makes the following observations:<br />
<br />
<blockquote class="tr_bq">
We don’t turn to story to escape reality, we turn to story to navigate reality (TEDxTalks, 2014, p. 11:08)<br />
<br />
You are being affected by stories every minute of every day, whether you know it or not. (TEDxTalks, 2014, p. 15:19) </blockquote>
<br />
In the Operation Solid Lives (OSL) program, through The Rock Church, Anaheim CA, the Level One class begins with a story about how Jesus was so in love with us, that he paused creation (which up to that moment had been “God said/God saw”) in order to step down and personally create man with his own hands. Then we see him so passionately in love with Enoch that he just took him because God had to have Enoch with Him, to which they conclude “God’s a Tooker!” (OSL, 2009). Throughout the Bible we stop at moments to see hints and reminders that he hasn’t forgotten about his plan to redeem us. It’s as if Jesus is peeking his head around and saying, as a parent to child in a game of hide and seek, “I’m coming!” This class turns the Bible from a series of facts into a living breathing story, and one walks away feeling (not just knowing) that God loves them.</div>
<div>
<h4>
The Bible Is Story</h4>
God did not give us a book entitled, Basic Instructions Before Leaving Earth, he gave us a narrative, a story. Glenn Paauw, in his book Saving the Bible from Ourselves, observes:<br />
<br />
<blockquote class="tr_bq">
An ongoing, deep immersion in the Bible will reveal two fundamental things to us: (1) there really are different acts in the drama, so things change, and (2) it really is a single story, so the acts are related to each other and there are abiding patterns that persist over time… God’s intentions are expressed in motifs that persist in drama… Our improvisation of the drama today will look for ways to implement these core redemptive patterns in our specific scene. (Paauw, 2016, p. 128) </blockquote>
Often, in our attempt to “study to show ourselves approved”, we miss the story while we dig into the meaning of particular words, and gather fragments of the Bible together in a hodge-podge of “supporting text” to prove our stance or doctrine is the right one. We subscribe to the verse of the day, and snack on the Bible in little bite sized pieces. We come to Bible study groups and listen to someone else’s ideas about the Bible, and then read their supporting texts. We ask for “proof texts” and “addresses” for the things we say about God and His Word. When we find ourselves in need of support or guidance, we look up key words to see what the Bible has to say about Love, Forgiveness, Hardship, Finances, etc.<br />
<br />
But in so doing, we miss the point entirely. We miss the Story God has given us, and out place in that story. But fear not, even thought the Bible was not given to us as a user manual, to look up the answer or instructions to fix a particular problem with a series of “how to”, we were given something much better. A grand Story, a Narrative, and it is through that narrative that we find our place in God’s Word, God’s World, and God’s Will.<br />
<br />
We find ourselves actors in a play that has been running for thousands of years, and continues to run until a final climax we have been promised, and we were not left without help.<br />
<br />
Paauw addresses this point:<br />
<br />
<blockquote class="tr_bq">
In his wisdom, The Word did not leave us with a script and tell us to figure it out. The Playwright has provided us with some critical aids to help us perform well. We were given the Bible, The Narrative, The Story. We were given the ability to be receptive to our Playwright (God). We were given directors of the play (pastors, leaders, teachers). We were given a cast (friends and family in the Church). (Paauw, 2016, p. 129) </blockquote>
<br />
The Stories and The Story section of the Immerse: Messiah New Testament says:<br />
<br />
<blockquote class="tr_bq">
The Bible is a gift. The Creator of all things has entered into our human story, and he has spoken. (Immerse, 2017) Page 483 </blockquote>
<br />
The Bible Project, in their video The Story of the Bible, summarize:<br />
<br />
<blockquote class="tr_bq">
The Bible is an important book, but it’s really long. It’s a collection of many books written over a long period of time but all together they tell one unified story. (Mackie &amp; Collins, 2014, 2019) </blockquote>
In a typical modern story, we have several common points we have grown to look for intuitively. The Inciting Event is the thing that started all of this madness. It’s the event that set up the dominos. In some cases, it happened long before our character was either born or made aware of it. The Key Event is the moment that the first domino falls, setting off a chain reaction that cannot stop until the end. Throughout the story, there will be disasters and turning points. Finally, the Climax is the moment that ties back to the Inciting and Key events, and it resolves the tension they caused. The Climax is followed by a short Resolution, tying up the loose ends.<br />
<br />
<ul>
<li>Genesis chapters 1-2 give us the Inciting Event (Creation of Man) and Key Event (the Fall)</li>
<li>Genesis 3 through Jude give us twists, turns, disasters, conflict, awe-inspiring feats, and passionate people.</li>
<li>Revelation gives us the Climactic Ending and Resolution.</li>
</ul>
Paauw goes on to say:<br />
<br />
<blockquote class="tr_bq">
Reading whole books of the Bible functions as the preliminary act to the main event. This is because the biggest thing to do with the Bible is to read its overall story of The Story and to do so with such regularity and in such depth that we can begin to reimagine our personal and community stories as part of its world-restoring drama. This has little to do with the patchwork assemblage of Bible verses we’ve been attempting to survive on. (Paauw, 2016, p. 110) </blockquote>
<br />
<h4>
Interpreting Our Story in The Story</h4>
The book of John tells us that The Word (Story) Is God. Story is innate to God’s nature. Therefore, He entered our story and gave us a story to interpret our lives through. It is common to see individual verses quoted and used to justify a host of various actions. In some instances, it is possible to draw the wrong conclusion by pulling a statement from the Bible out of context.<br />
<br />
One day, a woman sat with her pastoral counselor and told him that she was having an affair and planning to leave her husband. She said she’d prayed about the situation, and she had scripture to back up her position, and she wanted the pastor’s blessing. Dumfounded, the pastor asked what scripture she had to support this decision. She said, “I prayed for direction, and opened my Bible. It landed on the verse that said ‘put on the new man’, so I did.”.<br />
<br />
This humorous story shows an absurd example of how people can often take a single verse and make it say something it does not say. This practice is known as taking the verse “out of context” or “verse jacking”. As a parent to a child, we must say, “Put that back where you found it!” It is only when we understand the context of a verse within its section, book, and the whole Story of the Bible, that we can have a proper understanding of its meaning and application.<br />
<br />
In the book, Understanding Scripture, the authors note:<br />
<blockquote class="tr_bq">
For example, taken together, the reports of Solomon’s reign show gold slowly becoming more prominent, and more highly valued, than wisdom. Solomon spent more on his palace than on the temple, and his adherence to the law steadily declined (1 Kings 4-11). Readers can draw conclusions as they read the reports in canonical perspective. (Grudem, Collins, &amp; Schreiner, 2012, p. 15) </blockquote>
<br />
Students of the Bible must locate concepts, not just words, to develop a theme. For example, a concordance search on “pray/prayer/praying” would turn up only one verse in John’s Gospel (John 17:9), but several other verses tell how to “ask” God for various things, and those verses also teach a number of particular lessons about prayer. (Grudem, Collins, &amp; Schreiner, 2012, p. 17)<br />
<br />
One can also use outside resources to get a better understanding of The Story. Archeology, for example, helps to illuminate the Bible and the Bible illuminates Archeology (Grudem, Collins, &amp; Schreiner, 2012, pp. 124-125). We can get a sense of the time and people who lived real lives in real places and faced real struggles. We can feel the sand beneath our sandals, and the cold iron around our wrists in a dark dank dungeon. In Understanding the Bible, the authors conclude:<br />
<br />
<blockquote class="tr_bq">
A fuller understanding of the meaning of the New Testament can be achieved by learning more about the world in which its human authors and recipients lived. (Grudem, Collins, &amp; Schreiner, 2012, p. 132)&nbsp;</blockquote>
</div>
<div>
<br />
<h4>
Conclusion</h4>
Without understanding the Bible is given to us as Story and understanding our place in that Story, we cannot interpret correctly. We were wired for story in the very nature of our brain chemistry. One cannot always remember the five steps to this or seven habits off that, but one can feel the fire of the mountain as Frodo struggles to fulfill his duty to destroy the One Ring. Lisa Cron concludes her TEDx Talk with this statement:<br />
<br />
<blockquote class="tr_bq">
Never underestimate the power of story. It doesn’t just change how we see some things some of the time; it’s the only thing that changes how we see the world and therefore what we do in the world. All stories are a call to action. (TEDxTalks, 2014, p. 17:05) </blockquote>
<br />
The Story of all stories, the greatest story ever told, is The Story of God’s work in creating man, saving man from his fall, redeeming man, and his promise of an ultimate climax and resolution. It’s Jesus’ love letter to us, his passionate pursuit of us, and his promise to return and bring us Shalom.<br />
<br />
<br />
<br />
<br />
<b>Bibliography </b><br />
Grudem, W., Collins, C. J., &amp; Schreiner, T. R. (2012). Understanding Scripture - An Overview of the Bible's Origin, Reliability, and Meaning. Wheaton, IL: Crossway.<br />
<br />
Institute for Bible Reading. (2017). Immerse: The Reading Bible - Messiah. Carol Stream, IL: Tyndale House Publishers, Inc. Retrieved from http://immersebible.com/messiah/<br />
<br />
Mackie, T., &amp; Collins, J. (2014, 2019). The Story of the Bible. Retrieved from TheBibleProject.com: https://thebibleproject.com/videos/the-story-of-the-bible/<br />
<br />
OSL. (2009). OPERATION: SOLID LIVES (OSL). The Love of God. Anaheim, CA: The Rock Church. Retrieved from https://www.gototherock.com/operation-solid-lives<br />
<br />
Paauw, G. R. (2016). Saving the Bible from Ourselves. Downers Grove, IL: InterVarsity Press.<br />
<br />
Rodriguez, G. (2017, July 21). This Is Your Brain On Storytelling: The Chemistry Of Modern Communication. Retrieved from Forbes.com: https://www.forbes.com/sites/giovannirodriguez/2017/07/21/this-is-your-brain-on-storytelling-the-chemistry-of-modern-communication/#2fd61aa4c865<br />
<br />
TEDxTalks. (2014, May 4). Wired for Story. (L. Cron, Performer) Furman University, Greenville, SC. Retrieved from https://www.youtube.com/watch?v=74uv0mJS0uM<br />
<br />
<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span></div>
<br /></div>
