---
title: 'Book Reflection: Elements of a Christian Worldview'
date: '2019-05-24T04:47:00.0000000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7690639104450531903'
blogger_filename: '/2019/05/book-reflection-elements-of-christian.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Books'
---

<div style="text-align: center;"><br /></div><div style="text-align: center;"><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="https://ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&amp;OneJS=1&amp;Operation=GetAdHtml&amp;MarketPlace=US&amp;source=ss&amp;ref=as_ss_li_til&amp;ad_type=product_link&amp;tracking_id=198020052007-20&amp;language=en_US&amp;marketplace=amazon&amp;region=US&amp;placement=0882434896&amp;asins=0882434896&amp;linkId=a13ae9012e900fb2e891dac9ebd1e6d7&amp;show_border=true&amp;link_opens_in_new_window=true" style="height: 240px; width: 120px;"></iframe></div><div style="text-align: center;"><br /></div><br /><br /><h3 style="text-align: center;">Elements of a Christian Worldview - <a href="https://amzn.to/2K29z0e" target="_blank">Buy Now</a></h3><br />This is a reflection of the text Elements of a Christian Worldview (Palmer, 1998, 2013). Rather than a single text devoted to the topic by the mind of one man, Palmer takes on a journey as a tour guide by editing together the essays of multiple authors on various topics as they relate to a Christian Worldview. From the history and shaping of Worldview as a concept, to how it relates to Christianity, the first portion of the text sets us up to understand the context.<br /><br />Palmer then dives into specific topics, such as Science, Human Nature, Divine Rest &amp; Work, Music, Literature, History, and Politics. Each essay author has a particular background and story to tell as they explore in-depth their particular assignment. While each comes with a clear perspective, they lead the horse to the water but do not force him to drink. The reader is left to ponder these weighty topics without being force-fed one particular view.<br /><br />Throughout the text, the authors weave into each other seamlessly despite being independent essays. One such example is how Miroslav Volf and Charles W. Neinkirchen take us to tandem journey’s into Work and Leisure.<br /><br />Volf shows us that we were always meant to work, even before the fall. The Garden was given to mankind to tend. The fall did not curse work; rather, the fall cursed the ground from which work’s fruits would produce. Work itself was always a reflection of God’s character, He is always doing something, creating something, tending to something. It is a reflection of God’s character to work diligently and do it well. The secular world toils endlessly, as though achieving at any cost (including stepping on their fellow man) was worth it to achieve the end goal of money, fame, retirement, or possessions. However, Volf demonstrates that the quality and manner of work, reflecting God in the process, is far more important than the end results achieved. He shows us that the results of our work should be to provide for ourselves and then provide for others. If this second piece, providing for other people, isn’t achieved, the work was not a reflection of God.<br /><br />Meanwhile, Neinkirchen demonstrates that leisure is far from the “vacation” or “retirement” we make it out to be. He shows us a mirror, and in it we see a society bent on fast-paced vacations that leave us more tired upon return than we were when we left. These, he affirms, are not leisure at all. Leisure is found in quiet reflection. It is found in spending communal time with The Creator, plugging into His Presence, and being refreshed. We are reminded that God himself rested from ALL work on the 7th day; and as such, we should take time to reflect, refresh, and recharge in His Presence on a daily, weekly, monthly, and annual basis. We should take times of refreshing in His Word and Presence. It is in these moments, as we disconnect from our many “doings” and reconnect to the Tree of Life, that we will find our purpose released back into us.<br /><br />My personal favorites were the sections on Music, Literature, Media and Entertainment. To me, although separate authors, these painted the picture I have been painting my whole life. Story. It is through Story that we are most impacted. Long before there were “how to” books, long before there were printed books, men sat around fires and listened to the storytellers of old. Storytelling communicates and replicates culture.<br /><br />From a psychological perspective, it is the stories we each tell ourselves that have more impact on our hearts and behavior than the individual events (however tragic or amazing). It is what we tell ourselves about the event that defines or redefines us. From a personal perspective, I think I’ve learned more about self-sacrifice and doing the right thing despite all odds from Frodo’s journey to Mount Mordor than I ever did from a “7-Steps of X” or “5-Keys to Y” type book.<br /><br /><span style="white-space: pre;"> </span>It is through stories that we bypass the mind and run deeply into the realm of the heart and emotions. Many times, we learn from stories in ways our mind would have rejected. My favorite music is the type that tells an ongoing story; rather than repeating basic phrases. The Thunder Rolls, by Garth Brooks, will always make my emotions churn at the heart of a woman betrayed. Media and Entertainment have given us the Marvel Universe, where all of life’s greatest questions are playing in full living color and bigger than life scenarios. What does it mean to love two friends when one has caused great pain to the other (Captain America, Civil War)? Is the story you’ve been told about your life helping you live your true potential? What if that story was always a lie, and your real full power has never been seen? But once you discover your true identity, your full power becomes apparent and the enemies that once held you captive now become dust under your feet (Captain Marvel).<br />What would it look like if the Church led the way in storytelling that made the Marvel Universe look like a warm-up act? That is the question I ask myself, as my novel sits in draft, unfinished for this season. Selah.<br /><br /><h4>Bibliography</h4>Palmer, M. D. (1998, 2013). Elements of a Christian Worldview. Springfield, Missouri: Logion Press.<br /><br /><br /><br /><br /><span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br /><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a>&nbsp;&amp; <a href="http://topos.consulting/">Topos.Consulting</a></span><br /><br /><span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br /><span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a>&nbsp;(Myers-Briggs Type): INFJ</span></div>