---
title: 'What is Torah?'
date: '2020-11-19T05:11:00.0020000+00:00'
draft: false
categories:
  - 'Musings'
  - 'Studies'
  - 'bible'
---

<div>This was worth sharing... thoughts from class this week.&nbsp;</div><div><span style="font-size: 12pt; text-align: center;">&nbsp;</span></div><div>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span class="MsoBookTitle"><span style="font-size: 16.0pt; line-height: 200%;">Reading
Response: <o:p></o:p></span></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span class="MsoBookTitle"><span style="font-size: 16.0pt; line-height: 200%;">Spangler, Tverberg
Ch. 10-12</span></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Darrell
Wolfe<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Literature,
The King’s University<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Life
of Jesus (BIBL-2302)<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Professor
Jason Moraff<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Week
Five Reading Response – 11/22/2020<o:p></o:p></span></p>

<b><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 200%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;"><br clear="all" style="mso-special-character: line-break; page-break-before: always;" />
</span></b>

<p class="MsoNormal" style="line-height: 200%;"><b><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">&nbsp;</span></b></p>

<h1>Summary<o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">In Chapter 10, At Table with the
Rabbi, we find the significance of food, hospitality, and what it meant to be
at table with someone. For a middle eastern culture, to have someone as a guest
was an honor. The responsibility was taken seriously, even to the point of
being responsible for your guests’ safety (which makes more sense of why Job
would offer his daughters to the men of the city rather than his guests). We
can also see in this practice more sense of Jesus’ command to his disciples to
take nothing for the journey and stay with whomever would have them. This also
sheds new light on Psalms 23, a table before my enemies. The table and breaking
bread were also a sign of peace, and peace treaties. It was, especially at
Shabbat, a time to slow down and take inventory of God’s goodness and enjoy
fellowship.&nbsp; <o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">In Chapter 11, Touching the
Rabbi’s Fringe, the authors discuss the relevance and significance of “The
Law”. Many moderns, especially Christians, see the books of Moses (Gen-Deut) as
fry religious rules, impossible to carry out. In fact, Torah is not most
accurately translated “The Law” it is translated better as “Teachings” or
“Instructions”. These are not rules to be carried out to earn God’s favor, but
a series of Instructions to live out of the favor already existent on you as
one of God’s chosen people. Breaking this down further, they looked at the rule
about wearing Tassels and developed multiple layers of meaning to the practice.
When the woman with the issue of blood touched Jesus’ Hem/Tassels, she was
making a demand on his authority. Rather than him being made impure by her, his
purity ran through her making her pure. The Torah was God’s call to live holy
and separate lives. We see through Torah, as compared to contemporary laws such
as Hammurabi, that God’s laws were more just, and more focused on the weak and
“less than”. Rather than unbearable laws, we see grace and respect for life
through each one. Even “an eye for an eye” is a maxim, not be taken literally,
ensuring that the vengeance would not be an eye for a life. <o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">In Chapter 12, Jesus and the
Torah, we see a new image of Jesus as Rabbi. His debates with the fellow Rabbis
of his day were not full rebukes of tradition. Rather, he used tradition,
Rabbinic styles of communication, and employed techniques such as “building a
fence around the Torah” in his communication style. Surprisingly, when
understood in context, Jesus did not say he was fulfilling the law in the sense
that he was doing away with it because it was over. Rather, he was fulfilling
the law in the sense that he was bringing light to its original intent and
meaning, bringing us a more authentic way to live Torah. Without understanding
Rabbinic idioms, styles, techniques, and culture, Western Christians miss the
subtlety and often the meaning of Jesus’ words. The authors state: “Jesus must
have thought the Pharisees close enough to the truth to want to correct their
errors. Why else would he have engaged them in debate?” <a href="file:///C:/Users/darre/OneDrive/Desktop/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/Reading%20Respones_Week%20Five_Wolfe,%20Darrell_Life%20of%20Jesus_Moraff,%20Jason.docx#_ftn1" name="_ftnref1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[1]</span></span><!--[endif]--></span></a>.
Knowing this, we can see Jesus’ “Instructions” (Jesus’ Torah) as giving us
opportunity to live not to the bare minimum (what is the way we make sure not
to break the law?) but I a maximum way (how far can we go in loving our
neighbor?). Also, with this in mind, Salvation is barely a first step. Western
Christians place such an emphasis on “getting people saved” and then we leave
them to figure it out with a few instructions to follow on a pamphlet. Rather,
we should be inviting them into a life of discipleship (human to human, not
just human to God); which by necessity includes community.<o:p></o:p></p>

<h1>Reflection<o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">It is sad that we do not “eat
together” anymore. Not only is this missing in the culture at large, but in my
own household. Even when my late wife was alive, we often ate around the
television. It was a shared experience, but not one that invited much
relationship building. Since she passed, the stilted sadness of the household
lingers. We smile, laugh, often watch something together. But the bantering
died for a long time. Recently though, it has begun to return. As we began
joining our lives with another family with quite a different style, we find
ourselves eating food with no screen in sight, talking and laughing and telling
stories. Possibly for the first time in my life, I am seeing the benefit of a
shared experience of community eating. The theme of these three chapters in my
mind was “Building Awareness”. The constant in the subject of food, a new way
to see Torah, and a new way to see Jesus interacting with Torah was a drumbeat
of awareness around God’s heart for people. My Libertarian bent has me thinking
mostly about being “left alone”. I moved out of the city into the country where
I am left alone. Nobody ever knocks, there are few cars passing by, and I am
left to my own ways. However, in that isolation is no community. I became
painfully aware of this when I broke both legs and couldn’t even get down the
steps to the gravel driveway to get into the car. Nobody delivers here, no Uber
Eats or Grub Hub. Friends came to build a scary looking wheelchair ramp, but
then the wheels would get caught on the driveway gravel. Another set of friends
gave me a plywood base to land on and maneuver. Another friend picked up
groceries I ordered but could not drive to get. My mom moved in for weeks and
helped us transition.&nbsp; Suddenly, my “leave
me alone” did not feel like a blessing but a curse. I have been rethinking the
need for deeper connection to community, breaking bread with others,
discipleship, and making a point of using my talents to help others. Rather
than waiting for someone to ask me to walk a mile, maybe I could start offering
to do so. <o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<div><!--[if !supportFootnotes]--><br clear="all" />

<hr align="left" size="1" width="33%" />

<!--[endif]-->

<div id="ftn1">

<p class="MsoFootnoteText"><a href="file:///C:/Users/darre/OneDrive/Desktop/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/Reading%20Respones_Week%20Five_Wolfe,%20Darrell_Life%20of%20Jesus_Moraff,%20Jason.docx#_ftnref1" name="_ftn1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[1]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;15TieOwP&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Ann
Spangler and Lois Tverberg, {\\i{}Sitting at the Feet of Rabbi Jesus: How the
Jewishness of Jesus Can Transform Your Faith}, Updated edition (Grand Rapids,
Michigan: Zondervan, 2018).&quot;,&quot;plainCitation&quot;:&quot;Ann Spangler
and Lois Tverberg, Sitting at the Feet of Rabbi Jesus: How the Jewishness of
Jesus Can Transform Your Faith, Updated edition (Grand Rapids, Michigan:
Zondervan, 2018).&quot;,&quot;noteIndex&quot;:1},&quot;citationItems&quot;:[{&quot;id&quot;:186,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/VFB8VX5A&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/VFB8VX5A&quot;],&quot;itemData&quot;:{&quot;id&quot;:186,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;Sitting
at the Feet of Rabbi Jesus takes readers on a fascinating journey, helping them
discover how learning about the Jewish world of Jesus can enrich their own
faith. This newly expanded softcover edition includes a discussion guide and a
Jewish Seder liturgy&quot;,&quot;call-number&quot;:&quot;BT590.J8 S63
2018&quot;,&quot;edition&quot;:&quot;Updated
edition&quot;,&quot;event-place&quot;:&quot;Grand Rapids,
Michigan&quot;,&quot;ISBN&quot;:&quot;978-0-310-33069-1&quot;,&quot;number-of-pages&quot;:&quot;301&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Michigan&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Sitting at the Feet of Rabbi Jesus: How the
Jewishness of Jesus Can Transform Your
Faith&quot;,&quot;title-short&quot;:&quot;Sitting at the feet of Rabbi
Jesus&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Spangler&quot;,&quot;given&quot;:&quot;Ann&quot;},{&quot;family&quot;:&quot;Tverberg&quot;,&quot;given&quot;:&quot;Lois&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2018&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Ann
Spangler and Lois Tverberg, <i>Sitting at the Feet of Rabbi Jesus: How the
Jewishness of Jesus Can Transform Your Faith</i>, Updated edition (Grand
Rapids, Michigan: Zondervan, 2018).<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

</div></div><div><br /></div><h3 style="text-align: left;">Follow Up Discussion:&nbsp;</h3><div><br /></div><h4 style="text-align: left;">How do you understand the relationship between Torah (the Law), the Jewish people, Jesus, and the Gospels?&nbsp;</h4><div><br /></div><div>First, Torah is not "law" as we understand it today. Torah was not a rigid set of rules under which people struggled; rather, it was a set of "instructions" for people who were already in covenant relationship with God to walk that relationship out in real life.&nbsp;</div><div><br /></div><div>Second, Jesus was a Rabbi of the Torah in much the same way the other Rabbis of his day were. He used many of the same maxims and idioms, styles of communication, and Rabbinic techniques. What was different about Jesus was twofold:&nbsp;</div><div><ol style="text-align: left;"><li>Jesus did not see the Torah as Minimalist: "if we do at least this, we're safe". Jesus saw Torah as Maximist: "Love your neighbor, what's the most you can do to love them?" As such, Rabbi Hillel would say "Don't steal" but Rabbi Jesus would say "Look around to see who's worse off than you and find a way to help." (Spangler/Tverberg Pg.183)</li><li>While other Rabbis were building a fence around Torah in a fearful attempt not to violate it because "who could know the mind of God?"; Jesus was the author Torah Himself, so he came offering God's own heart on the very instructions he originally gave.</li></ol></div><div><br /></div><h4 style="text-align: left;">What do you think is at stake in discussing Jesus and the Torah?&nbsp;</h4><div><br /></div><div>If we understand Torah for what it really was/is and Jesus' relationship to it, we run a far greater chance of having correct interpretation and a far lesser risk of being in error. In essence, we can live closer to God's heart for his people by understanding this relationship.</div><div><br /></div><h4 style="text-align: left;">How does this discussion affect how you understand the relationship between the Tanakh/Old Testament and the New Testament, as well as Jesus' relationship to the Jewish people?</h4><div><br /></div><div>This makes me want to read Gen to Rev all over again with a new eye for how they correlate. Especially knowing how often Jesus used the technique of quoting part of scripture to force the haverim to go find the rest of his meaning; I would like to restudy all the Gospels more slowly, taking a look at every single cross-reference, soaking in the possible hidden meanings that have eluded me all these years.&nbsp;</div><div><br /></div><div>I have always asserted, but apparently never lived out myself, that we are essentially Jewish. We, Gentile Christians, were grafted INTO Israel and not out of it. To the degree we remain disconnected from our family heritage, we remain incomplete in our understanding of what it means to follow the God of Abraham, Isaac, Jacob, David, Jesus, and Darrell.&nbsp;</div><div><br /></div><div><br /></div>
