---
title: 'My Research Paper on David Du Plessis (AKA Mr. Pentecost)'
date: '2020-10-03T02:24:00.0020000+00:00'
draft: false
categories:
  - 'Class Assignment'
  - 'Biblical Studies'
---
## David Du Plessis:

### An Apostle of Reconciliation, Mr. Pentecost, and a Key Leader in the Charismatic Renewal.

Darrell Wolfe

The King's University:

Pentecostal and Charismatic Movements BIBH 1301

October 4, 2020

#### Introduction

    Division and discord were ripe between denominational bodies (a hotbed of controversies and theological/political landmines) when David Du Plessis softly sauntered onto the scene with a message about the simplicity of the Gospel. With that message, he brought leaders from all sides to a quiet reflection of their own ministries' effectiveness. Within Ecumenical circles, Du Plessis was best known by his moniker, Mr. Pentecost. To church historians, he became known as one of the key influencers of the Pentecostal Movement, the Ecumenical Movement, and the Charismatic Renewal. In my estimation, David Du Plessis was an Apostle of Reconciliation. His impact was so broad, outside of the Pentecostal Movement itself, that he became the first non-Roman Catholic to receive the Benemerenti award (1983) on the Pope's behalf.[1].docx#_ftn1) Due to his unwavering dedication to unity and his quiet unassuming character, few men have exemplified the ministry of Jesus like David Du Plessis. To understand who he was, we will need to look at the environment he walked into, the character he came with, and the results of his presence.

#### The Old Gives Way to The New

    The scene upon which David Du Plessis arrives is relevant to understanding who he was and why his impact was so vital. The Pentecostal Movement in South Africa was kicked off by John G Lake between 1908-1913. Racial tensions were still high throughout the world and especially in South Africa. Influenced by Alexander Dowie of Zion City, IL, and William J Seymour of the Azusa Street Revival, John G Lake founded both the Apostolic Faith Mission (AFM) (white branch) and the Zion Christian Church (ZCC) (black branch) in South Africa.[2].docx#_ftn2) Into this movement, David Du Plessis was raised as a child, and he notes that he "was a little white heathen saved by the life and ministry of black Christians".[3].docx#_ftn3)

    David Du Plessis was born in 1905, just one year before the Azusa Street Revival would begin to rock the world. In the early years, David's father was a carpenter building a mission for the AFM. Having been kicked out of the Dutch Reform Church for his healing beliefs, the elder Du Plessis held firmly to the belief that nobody should use medicine or medical care but rely on God's healing only. He ended up in prison briefly for not giving his cattle medicine to avoid the plague.[4].docx#_ftn4) David's father was so against education, that when David Du Plessis went to Grey University in Bloemfontein, his father voluntarily surrendered his lay preacher's license because he felt like a parental failure.[5].docx#_ftn5) Despite their disagreements, David recalled learning from his father how to work hard, do the right thing no matter what, and to obey quickly (which would come in handy when God started sending him on strange assignments). Out of that environment, he was saved at eleven years old, received the Baptism of the Holy Spirit at thirteen, and at twenty-three David Du Plessis was himself ordained by the AFM. In 1935, at thirty years old, he became the general secretary of the AFM where he began to show the earliest signs of his passion for fostering unity.[6].docx#_ftn6)

    It was during his formative years (1905-1948) that the Pentecostal Movement was spreading throughout the world yet being rejected by the old denominations. As Synan points out in his work on The Holiness-Pentecostal Tradition, "One of the ironies of church history is that those responsible for the new religious movements often become hostile to the results of their own work".[7].docx#_ftn7) Such was the atmosphere in 1936 when Smith Wigglesworth came bursting into David Du Plessis' office with a prophetic word about the old churches experiencing the greatest revival in history; and, that Du Plessis would be a major player in that revival. Du Plessis was so shocked he decided not to believe Wigglesworth but was careful to tell the Lord he would act when instructed (but not a moment earlier).

#### The Tension of Obeying God

    Throughout his life and ministry, Du Plessis followed The Lord's direction even when it cost him his last dime, which it did on many occasions. In one such incident, he arrived home early from a trip to find his wife in tears because they had just eaten their last meal. The kids told her not to fear because Dad always said "when we used the last ten cents, the next hundred dollars is on the way."[8].docx#_ftn8) As David was still trying to coax the story out of his wife, the kids burst into the room with an open envelope and a check for \$100 and they ate well the next day. Time and again, Du Plessis would be on his way to a destination, book a ticket, and have no idea how he would pay for it, all because the Lord told him to go. Yet the money, ride, ticket, or provision would show up (often at the last minute) nearly every time. He lived in the constant tension between wanting to obey God and having to depend on God for miracle provision at each step of his journey.

    During his work with the Pentecostal World Conference, he experienced constant tension between parties pushing for power and those being suspicious of his intentions. The second world conference nearly fell apart until he suggested a meeting with the leaders of the disruption. In his soft, prayerful, questions, they managed to resolve in minutes what they had not been able to resolve in days. Donald Gee, the co-founder of the meeting, called it Du Plessis' greatest achievement, but Du Plessis saw it as only a steppingstone into his ultimate calling of uniting the Old Churches.[9].docx#_ftn9) Although Gee was interested in the Pentecostals being involved in a wider unity with the Old Churches, he was afraid of any movement that might appear to be causing more division or power struggles.[10].docx#_ftn10)

    In an article written for The Ecumenical Review, in July 2000, Walter Hollenweger observes that Gee and Du Plessis, much like Paul and Barnabas, were brought into tension by a disagreement in the vision for the future and style of the organization. In an excerpt from letters written by Gee to Du Plessis, Du Plessis is accused of using his signature (Secretary, World Fellowship) to create a position for himself that was not implied. Gee saw the position as being that of organizing a single conference once every three years, while Du Plessis saw the position as that of building unity between the bodies on an on-going basis. At the end of the dispute, Du Plessis resigned from his post as Secretary of the Pentecostal World Conference.[11].docx#_ftn11)

#### The Winds of Change

    Psalms tell us "The steps of a good man are ordered by the LORD, and He delights in his way.".[12].docx#_ftn12) In The Spirit Bade Me Go, David Du Plessis gives us the following insights into the steps that led to the opening of the first door into the Ecumenical Movement.[13].docx#_ftn13)

    The story begins in 1948 (twelve years after the Wigglesworth prophecy) when Du Plessis was reading about the formation of the World Council of Churches (WCC). By this point, he had been working for years to unite the Pentecostals and had moved from South Africa to Switzerland to the United States. Some argued that the work must be an evil attempt to form a "super-church" which gave Pentecostals reminders of the top-down authority they had left behind when they were kicked out, but he reasoned that "any movement of unity between the various churches must be of God". This moved him to begin praying about God's purposes in the WCC. This demonstrated a willingness on his part to listen for God's heart, rather than jumping to conclusions.

    In 1951, Du Plessis met with Dr. John A. Mackay (President of Princeton Theological Seminary and of the International Missionary Council) and established an instant kindred friendship.[14].docx#_ftn14) A few days after that meeting, Du Plessis said the Lord spoke to him to go and witness to the WCC leaders. He resisted the Lord's calling on this, having preached against the old churches for so long, but he felt strongly this is what he must do. Convicted to go, and inspired by his meeting with Mackay, Du Plessis took the train from his home in Connecticut to the WCC offices in New York. While on the train, still resisting, Du Plessis decided that he would be so blunt about the fact he was a Pentecostal (and worse, the world secretary) that they had to either accept him or kick him out; however, when he arrived the leadership liked him so much that they asked him to stay for lunch and speak with the rest of those onsite. This was David Du Plessis' first official encounter with the WCC.

    As a result of those first meetings, he was invited to come to the 1952 International Missionary Council (IMC), Extended Assembly, in Willingen Germany. When he arrived, Dr. Mackay "took him by the arm and introduced him as a great Pentecostal friend". The next day, the "speaker complained that Christianity had become so institutionalized that it would be a blessing if some of these institutions burned down".[15].docx#_ftn15) Dr. Mackay followed that message by asking Du Plessis to quickly give his reasons for the rapid spread of Pentecostalism in the world. The essence of his message was (1) Christians were never intended to go out into the world without The Power of God; and, (2) rather than send out highly-trained well-educated missionaries to preach doctrine, the Pentecostals allowed for a more organic person-to-person witnessing style. He said that witnesses did not need doctrine, only an experience to talk about. This led to an earlier rendition of the famous saying: Each One Reach One. During that first IMC conference, he met personally with 110 of the 210 delegates present that week.[16].docx#_ftn16) From that meeting forward, Du Plessis was invited into more councils, meetings, assemblies, and conferences.

    The real breakthrough came in 1956 when Du Plessis was speaking at a retreat in Connecticut where he was asked to be "devastatingly frank" about his thoughts on the Pentecostal Movement.[17].docx#_ftn17) He felt a heat wash over him and his critical heart was replaced with compassion for these church leaders. He then poured out his heart to them for seventy-five minutes. That meeting was the moment he changed from a passively resistant participant to an actively engaged participant in the Ecumenical Movement. He had God's heart for the men and the churches they represented, and it carried him through his entire ecumenical ministry.

#### The Apostle of Reconciliation

    The heart of Du Plessis can be seen on full display in an audio recording of a message entitled "Forgiveness", which he delivered on June 30, 1967, at the Elim Campmeeting in Lima, New York. Du Plessis recounts an interaction in which a man asked him about his experiences in the ecumenical circles. The man asked, "You don't tell them they're sinners?" To which Du Plessis replied, "No sir. I never tell them they're sinners. I don't care how bad they are. I never suggest they're sinners... Jesus said it's better that I go because I will send the Holy Spirit. And HE will reprove the world of sin, and you don't have to do it." [18].docx#_ftn18)

    As a result of his willingness to work with anybody and yet never compromise his standards, he was invited into the private meetings with the world's most elite religious leaders. He worked with high-level leaders in multiple denominations and interdenominational counsels, as well as those within the Catholic Church. He went on to be noted by Time Magazine (Sept 9, 1974, Pg. 66) as one of the key shapers and shakers of Christianity.[19].docx#_ftn19) He was given several prestigious awards and received an honorary doctorate from Bethany Bible College.[20].docx#_ftn20)

#### Conclusion

    A man of intrinsic power with no official office, David Du Plessis held titles, but he worked largely title-less. Although he held credentials, he worked mostly credential-less. David Du Plessis was all too willing to give up any title he obtained in the name of preserving peace. Yet he was willing to take a stand for his calling, even when the Assemblies of God (AG) revoked his credentials in 1962, leaving Du Plessis to work without them until they were restored many years later (1962-1980).[21].docx#_ftn21) David Du Plessis died on February 2, 1987 (days shy of his 82 birthday) and the Los Angeles Times, in his Obituary, noted that Du Plessis was "...the only Pentecostal invited to the third session of the Second Vatican Council in Rome in 1964.".[22].docx#_ftn22) Faith, Hope, and Love were hallmarks of his ministry. Faith caused him to go before provision arrived. Hope fueled his vision for unity. Love was felt by everyone he encountered. As a result of his work, many church leaders that considered themselves enemies were made friends. David Du Plessis carried the spirit of an Apostle of Reconciliation wherever he went. Given the spirit of division evident in 2020, he stands as an example of unity for the body of Christ today.

#### Bibliography

Burgess, Stanley M., and Eduard M van der Maas. *The New International Dictionary of the Pentecostal and Charismatic (NIDPCM)*. Revised and Expanded. Zondervan, 2002.

Dart, John. "OBITUARIES : David J. Du Plessis; Force in Pentecostal Movement - Los Angeles Times." News Paper, Online. Los Angeles Times, February 5, 1987. https://www.latimes.com/archives/la-xpm-1987-02-05-mn-978-story.html.

"David Du Plessis." In *Wikipedia*, December 31, 2019. https://en.wikipedia.org/w/index.php?title=David_du_Plessis&oldid=933332487.

Du Plessis, David. *The Spirit Bade Me Go: The Astounding Move of God in the Denominational Churches*. Alachua, FL: Bridge-Logos, 1970.

Encyclodpedia.Com. "Du Plessis, David J(Ohannes) 1905-1987 \| Encyclopedia.Com." General Reference. Accessed October 2, 2020. https://www.encyclopedia.com/arts/educational-magazines/du-plessis-david-johannes-1905-1987.

Du Plessis, David, and Bob Slosser. *A Man Called Mr. Pentecost: David Du Plessis as Told to Bob Slosser*. Plainfield, N.J.: Logos International, 1977.

Hearn, Jay. *David DuPlessis  - "Forgiveness" June 30, 1967  Pm*. Audio Recording: Posted to YouTube by Jay Hearn, 1967. https://www.youtube.com/watch?v=afL_3rAM3yw.

*Hebrew-Greek Key Word Study Bible: Key Insights Into God's Word. NKJV New King James Version*. Genuine Black Leather. Chattanooga, TN: AMG Publishers, 2015.

Hollenweger, Walter. "Two Extraordinary Pentecostal Ecumenists: The Letters of Donald Gee and David Du Plessis." *The Ecumenical Review* 52, no. 3 (July 2000): 391--402.

"Religion: Shapers and Shakers." *Time*, September 9, 1974. http://content.time.com/time/magazine/article/0,9171,904121,00.html.

Robeck, Cecil M. "A Pentecostal Looks at the World Council of Churches." *The Ecumenical Review*, January 1, 1995. https://www.thefreelibrary.com/A+Pentecostal+looks+at+the+World+Council+of+Churches.-a016420085.

Synan, Vinson. *The Holiness-Pentecostal Tradition: Charismatic Movements in the Twentieth Century*. 2nd ed. Grand Rapids, MI; Cambridge, U.K.: William B. Eerdmans Publishing Company, 1971.

Footnotes

------------------------------------------------------------------------

[1].docx#_ftnref1) Stanley M. Burgess and Eduard M van der Maas, *The New International Dictionary of the Pentecostal and Charismatic (NIDPCM)*, Revised and Expanded (Zondervan, 2002).

[2].docx#_ftnref2) Vinson Synan, *The Holiness-Pentecostal Tradition: Charismatic Movements in the Twentieth Century*, 2nd ed (Grand Rapids, MI; Cambridge, U.K.: William B. Eerdmans Publishing Company, 1971).

[3].docx#_ftnref3) David Du Plessis, *The Spirit Bade Me Go: The Astounding Move of God in the Denominational Churches* (Alachua, FL: Bridge-Logos, 1970).

[4].docx#_ftnref4) David Du Plessis and Bob Slosser, *A Man Called Mr. Pentecost: David Du Plessis as Told to Bob Slosser* (Plainfield, N.J.: Logos International, 1977).

[5].docx#_ftnref5) Burgess and van der Maas, *NIDPCM*.

[6].docx#_ftnref6) "David Du Plessis," in *Wikipedia*, December 31, 2019, https://en.wikipedia.org/w/index.php?title=David_du_Plessis&oldid=933332487.

[7].docx#_ftnref7) Synan, *The Holiness-Pentecostal Tradition*.

[8].docx#_ftnref8) Du Plessis and Slosser. Pg. 143

[9].docx#_ftnref9) Du Plessis and Slosser. Pg. 170

[10].docx#_ftnref10) Cecil M. Robeck, "A Pentecostal Looks at the World Council of Churches.," *The Ecumenical Review*, January 1, 1995, https://www.thefreelibrary.com/A+Pentecostal+looks+at+the+World+Council+of+Churches.-a016420085.

[11].docx#_ftnref11) Walter Hollenweger, "Two Extraordinary Pentecostal Ecumenists: The Letters of Donald Gee and David Du Plessis," *The Ecumenical Review* 52, no. 3 (July 2000): 391--402.

[12].docx#_ftnref12) *Hebrew-Greek Key Word Study Bible: Key Insights Into God's Word. NKJV New King James Version*, Genuine Black Leather (Chattanooga, TN: AMG Publishers, 2015). Psalms 37:23

[13].docx#_ftnref13) Du Plessis, *Spirit Bade Me Go*. Pgs. 6-13

[14].docx#_ftnref14) Du Plessis and Slosser. Pg. 172

[15].docx#_ftnref15) Du Plessis, *Spirit Bade Me Go*.

[16].docx#_ftnref16) Du Plessis.

[17].docx#_ftnref17) Du Plessis. Pg. 10

\18] Jay Hearn, *David DuPlessis  - "Forgiveness" June 30, 1967  Pm*, Audio Recording: Posted to YouTube by Jay Hearn, 1967, https://www.youtube.com/watch?v=afL_3rAM3yw.

[[19].docx#_ftnref19) "Religion: Shapers and Shakers," *Time*, September 9, 1974, http://content.time.com/time/magazine/article/0,9171,904121,00.html.

[20].docx#_ftnref20) Burgess and van der Maas, *NIDPCM*. See also, 24.

\21] "Du Plessis, David J(Ohannes) 1905-1987 \| Encyclopedia.Com," General Reference, Encyclodpedia.Com, accessed October 2, 2020, https://www.encyclopedia.com/arts/educational-magazines/du-plessis-david-johannes-1905-1987.

[[22].docx#_ftnref22) John Dart, "OBITUARIES : David J. Du Plessis; Force in Pentecostal Movement - Los Angeles Times," News Paper, Online, Los Angeles Times, February 5, 1987, https://www.latimes.com/archives/la-xpm-1987-02-05-mn-978-story.html.
