---
title: 'Render unto God and Caesar: Was Jesus’ Mission and Message Political? Exegesis of Luke 20:19-26'
date: '2020-12-04T07:35:00.0020000+00:00'
draft: false
categories:
  - 'Class Assignment'
  - 'Biblical Studies'
---
Research Paper:

Was Jesus' Mission and Message Political?

Exegesis of Luke 20:19-26

Darrell Wolfe

Literature, The King's University

Life of Jesus (BIBL-2302)

Professor Jason Moraff

December 6, 2020

### Introduction

This paper seeks to examine the question: Was Jesus' mission and message political? The answer requires a definition of the word: Political. For this paper, "political" will be used to mean those activities and policies which together affect the governing of a country or kingdom[1].  The paper will examine how Jesus' mission and message had political ramifications. The paper will establish that God is directly involved in the affairs of his people and sees himself as a literal King. The paper will examine the text of Luke 20:19-26 where a group is sent to Jesus to trap him and hand him over to the government because the political leadership of Israel were threatened by him. The paper will position Jesus as king over a literal kingdom, and what that might mean for us today. The history, culture, and conflict into which King Jesus was born are relevant to examine this question of Jesus' mission and message.

### God's Kingdom Reign, Israel, and the Roman Empire

#### Israel's Rightful King

Up to the time of Samuel, God himself reigned as king over Israel. Israel rejected God as their King and requested a natural king so they could be like everyone else (Samuel 8:6-9). Samuel warned Israel that the king they requested would take everything that belonged to them including taxes (Samuel 8:20-22). Then after God replaced the first king (Saul) with the second king (David), God promised David that a king would come from his own line that would build a house (family) for God and that this new king's throne would last forever (1 Chronicles 17:1-27).

#### The Ages of Kings

In 587 BCE, Babylon conquered Israel and destroyed the Temple, seemingly ending the line of Israeli Kings.[2] In Daniel, Nebuchadnezzar's statue showed Israel their new kings beginning from King Nebuchadnezzar the Babylonian leading up to the arrival of the Messiah-King. Daniel describes the final kingdom as the "rock not cut from human hands" that will crush every previous kingdom, which would grow until it filled the earth (Daniel 2). History shows that this came to pass in the form of the golden Babylonian empire, the silver Medo-Persian empire, the bronze Grecian-Macedonian empire, the iron Roman empire, and the final Rock Kingdom; which was established when Jesus arrived preaching and teaching the Kingdom of God.[3]

Israel's national identity was preserved in part due to the fall of Babylon to Persia who then held a policy toward Jews that "oscillated between toleration and benign neglect".[4] When the Persian Empire took over, Kings Cyrus and Darius were more friendly to the people of Israel and allowed for them to return to their homeland and rebuild the Temple (circa 520-519 BCE).[5] When the new Grecian-Macedonian Empire attempted to Hellenize Judea (175-168 BCE), it created such resistance that it led to a massive revolt under the Maccabeans.[6] This led to a spirit of independence among the Jewish people. Several smaller revolts and rebellions rose from time to time. In the final stages of Roman rule, Daniel predicted a kingdom whose people did not mix well, this was largely referring to the conflicts between Israel and Rome.

#### Israel's Conflicts with Rome

Caesar Augustus (27 BCE to 14 AD) divided Rome into ten provinces (just as Daniel predicted with the ten toes), and Jesus (The Rock) was born in the middle of his reign.[7] In 63 BCE, Rome expanded to include Israel. "Rome ruled her empire with tolerance for local customs and cultures..." and the issue that impacted ordinary people most was taxation because it forced peasant farmers into hardship[8]. The society was village-based and agrarian; therefore, the increasing pressure to pay taxes monetized the society breaking down cultural norms.[9]  The people generally believed that the "benefits of peace and prosperity that Rome claimed to give its subjects could not obscure the fact that the empire served primarily the prosperity of the Romans and local elites who supported them".[10] The Jews assimilated aspects of Roman culture (such as speaking Greek) while denouncing other aspects (such as Roman sacrifices). The religious leaders governed the people on behalf of Rome and the local Governor (Pilate). The average people held attitudes that "ranged from mercenary accommodation to violent protest".[11] Horsley describes the condition of Israel during the times of Jesus as follows:

"Domestic affairs were left to the priestly aristocracy again. From 6 to 66 C.E. four principal families dominated the society, with the office of high priest, in effect, alternating among them. The priestly aristocracy also dominated the Sanhedrin or high counsel throughout this period. Partially because of the awkward combination of Roman governor and Jewish priestly aristocracy, Roman control of Jewish Palestine was not as tight as it had been under Herod. But with all matters of importance in the hands of the high priests and the Roman governor, there was no legitimate channel for political participation by the people."[12]

#### The Political Class

Since Rome ruled in conjunction with local leaders, in this case, priestly aristocracy, there was no clear separation between religion, morals, law, and politics.[13] There were three religious-political parties with influence in Israel during the days of Jesus. The Essenes are never mentioned in the Gospels; however, their works are retained in the Dead Sea Scrolls.[14] They were a monastic-style secret club who were preparing to fight a physical holy war with Rome to free Israel from their oppression. The Essenes would certainly have had a role to play in the mindset of average townsfolk, especially since the mini-revolt under Herod (circa 4 AD) would be still fresh in their minds from just a few decades before.[15]

The Pharisees were known for being detail-oriented interpreters of the Torah. They held the most influence over the average first-century Jewish mind.[16] While Mark 12:13 and Matthew 22:15 lay the tax question at the feet of the Pharisees, Luke 20:19-20 only refers to the test givers as spies sent by the chief priests and scribes (lawyers). Most Pharisees were local Rabbis in the villages, but there were some Pharisees represented in Temple leadership.[17] This means the ones interacting with Jesus in Galilee are likely different than the ones posing the tax question in the temple.

The Sadducees were the dominant ruling class of high priests and other high-ranking officials within the Temple. The Sadducees held almost all political power, but their religious views were not influential.[18] These were the most threatened by Jesus because any revolt of the people would bring down quick and harsh reaction from Pilate (just as Herod had done before him), which threatened their own rule by association.

### Literary Setting

It is into this climate that we find Jesus entering Jerusalem for a showdown with the elite leadership of Israel, which led to his death on the cross. Some estimate that this took place on Tuesday of Passion Week (a few days later, on Friday, Jesus would be killed).[19]

Luke brings us the most complete account of Jesus' life of all four gospels. Luke's writing shows a passion for details that could be compared to a fine artist.[20] Though they did not understand his meaning, Jesus prepared his disciples for the Passion Week letting them know they would be heading to Jerusalem and that he would be killed (Luke 18:31). Jesus rides into Jerusalem on a donkey to praises reserved for the coming of Messiah. They even call him a king (Luke 19:38). Upon arrival, Jesus drove out the money changers and traders and taught in the temple. The chief priests and lawyers wanted to kick him out but were afraid of the people starting a riot (Luke 19:47-48).

It is while Jesus was teaching in the temple that the leaders came to challenge him. In one such challenge, he told the story of the vineyard owner whose son was killed by the hired staff, who were then killed by the owner himself. The leadership of the temple recognized this parable was spoken against them and they began to look for ways to hand Jesus over to the governor (who had the authority to kill him). Within days of these events, Jesus would be arrested at night, turned over to Pilate's guards, and executed as a rebellion leader. It is in this context that we find our way into the key text.

### Exegesis of Luke 20:19-26 (NEB)

The lawyers and chief priests wanted to lay hand on him \Jesus] there and then, for they saw that this parable was aimed at them; but they were afraid of the people. So they watched their opportunity and sent secret agents in the guise of honest men, to seize upon some word of his as a pretext for handing him over to the authority and jurisdiction of the Governor. They put a question to him: "Master", they said, "we know that what you speak and teach is sound; you pay deference to no one, but teach in all honesty the way of life that God requires. Are we or are we not permitted to pay taxes to the Roman Emperor?"

He saw through their trick and said, "Show me a silver piece. Whose head does it bear, and whose inscription?"

"Caesar's", they replied.

"Very well then," he said, "pay Caesar what is due to Caesar and pay God what is due to God".

Thus, their attempt to catch him out in public failed, and astonished by his reply, they fell silent. [[21]

#### The Politics of the Question

Jesus could have ridden the wave of the crowd's emotional response to consolidate power and take over as King of Israel.[22] The opportunity mirrors that of the temptation in the wilderness (Luke 4). The various challenges to Jesus' authority were all clashes between two regimes or worldviews. The question of the tax was the most obviously political question, not the only politically motivated question.[23]

They challenge Jesus: Is it legal to pay taxes? If he answers yes, he is going to upset the people who resent taxation, losing favor with them. If he answers no, he is guilty of rebellion and they can hand him over to the Roman Governor to be treated as a rebel. They believe they have him trapped. Jesus sees through their trap and gives his now-famous response: "Render to Caesar what is Caesar's and God what is God's" (Luke 20:24-26). Taxation was a flashpoint for the average citizens, and Jesus' answer "might be interpreted to question whether Caesar deserved any or all that he asked for".[24] However, Jesus avoids giving a clear yes or no and turns the hearer into the interpreter, wrestling with what is Caesar's and what is God's?[25]

#### The Coin

At face value (pun intended), the Denarius bears Caesar's image and inscription. The coin belongs to Caesar; therefore, he has a right to request some of his own coin back. By that reasoning, it is appropriate to pay taxes because you have already agreed to abide by the terms of the government by carrying the coin in the first place.[26] The coin itself brings an interesting dynamic to the interpretation. The silver Denarius became the backbone of the Roman economy. Many versions of the coin were in circulation throughout the empire at the time. A common theme on the coins was the image, reverse image, and inscription combining to create a claim at the divinity of Caesar. [27] The image on the front of a Denarius bore the image of Caesar and became a way of propagandizing him as a god.[28]

Jesus' observation about the coin itself is fascinating. "Whose image does the coin bear? Whose inscription?" Torah refers to mankind as being created in the image of God (literally, bearing God's image) (Genesis 1:27). The people are told to meditate on God's Torah and bind it to their foreheads and arms (Deuteronomy 11:18-21). Today, Orthodox Jews wrap the tefillin around their arm, binding a small box with a portion of scripture locked inside.[29] The Rabbis who were to bear the image and inscription of God were rejecting God's Messiah by even asking this question. In this sense, "Render unto God" could be read as render unto God the respect and honor due to his Messiah (the rock, the final King).[30]

### Theological Implications

*One cannot separate religion and politics in the Gospels.* The following points are presented for consideration. God established Israel as a nation and himself as their literal king. When they rejected him, God promised future kings would exact taxes; then promised each of the nations that arose to rule Israel. God fulfilled his promise to Israel by never letting her live without a king, he never promised that every king would be of Israel. Therefore, he fulfilled his promise through Samuel in the Israeli kings, but also in Babylonian, Persian, Greek, and Roman kings. In first-century Israel, aristocrats ruled the temple and the people on behalf of Rome. Therefore, every interaction with a religious ruler was an interaction with a political ruler (akin to a mayor, senator, or governor today). These leaders were threatened by Jesus' mission and message. Therefore, his mission and message threatened the politics of the day.

*The coin confirms God's role in the tax.* Render unto Caesar what is Caesar's goes beyond giving him back the coin his kingdom produced. Samuel 8 and Daniel 2 confirm that God himself established Caesar over Israel and the taxes he would exact from them.

*The coin confirmed the political leaders should have been God's image-bearers.* Render unto God the honor and obedience due to him as his image and inscription bearers. To bear his image and inscription but show loyalty to Caesar at the expense of loyalty to God's final King is the ultimate rejection of God as King. This brings their rejection full circle from Samuel to Jesus. Those who would bear God's image and inscription should submit each decision, especially political decisions, to God.

*Jesus' "Kingdom of God" is a real kingdom*. God predicts the four empires and a final rock kingdom that would replace them. That kingdom of God is the kingdom of the rock. Jesus tells Peter that "on this Rock (confession of Jesus as Messiah and God) I will build my Church" (Matthew 16:13-20; Luke 9:18-20). Jesus' kingdom replaces every other kingdom, eventually conquering Rome just as predicted. The final conquering of Rome was not accomplished through swords but through the power of God in his people. Today, the only remnant of the Roman Empire is the "Roman Catholic Church".

### Conclusion

            It could be said that the Kingdom of God has filled the entire earth. It filled the known world at the time. The Judeo-Christian ethic has influenced (if not dominated) world policies and governments since its foundation in the first century. Whether one could say that Jesus' mission and message were political depends on how politics is defined. However, it has been established that his mission and message had radical political ramifications. God himself has always been the king of his people and expects their loyalty over any kingdom or government in which they reside, and over any party affiliation. Given this relationship, it brings new thoughts to scriptures like "you cannot serve God and money" (Luke 16:13).The Denarius would have been in Jesus' money bag with Judas' when he said this. Although Jesus often cited the Kingdom of God is not like other kingdoms, it was predicted as one which would displace the natural kingdoms of Babylon, Persia, Greece, and Rome. Therefore, it is hard to say that it is only a "spiritual kingdom". The first-century people disagreed about who Messiah (The Anointed One) ought to be. Some believed that there might be three Anointed Ones, a King, a Priest, and a Prophet.[31] In hindsight, we can see that Jesus was all three, and yet something entirely different than each title would have suggested to that first-century audience. Finally, to be in the kingdom of God is to use God's power to affect the world. It does not necessarily mean taking positions of power; however, it does mean that the effectual use of his power will change the culture and affect (or even displace) governments. Based on these findings, at least in many meaningful aspects, Jesus' mission and message were political.

------------------------------------------------------------------------

[1] This definition is my own paraphrase of the Oxford Languages dictionary.

[2] Bruce Chilton, *Pure Kingdom: Jesus' Vision of God*, Studying the Historical Jesus (Grand Rapids, Mich. : London: Eerdmans ; Society for Prommoting Christian Knowledge, 1996). Pg. 24

[3] S.R. Driver, "CHAP. 2. NEBUCHADNEZZAR'S DREAM," in *Cambridge Bible for Schools and Colleges*, Daniel (Cambridge University Press, 1900), https://biblehub.com/commentaries/cambridge/.

[4] Chilton, *Pure Kingdom*.

[5] "The Decree of Darius (Ezra 5:3-6:13) July 26-27," in *Beyond Today Bible Commentary by United Church of God*, accessed November 28, 2020, https://bible.ucg.org/bible-commentary/Ezra/Tattenai's-inquiry-regarding-the-temple-reconstruction-and-the-decree-of-Darius/.

[6] Richard A. Horsley, *Jesus and the Spiral of Violence: Popular Jewish Resistance in Roman Palestine*, 1st ed (San Francisco: Harper & Row, 1987), https://archive.org/stream/jesusspiralofv00hors. Chapter 1 -- See also the apocryphal books of 1 and 2 Maccabees.

[7] Jonathan Welton, *Raptureless*, 3rd Edition Printing (Place of publication not identified: Bookbaby, 2015), http://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=4188734.

[8] Richard Bauckham, *Jesus: A Very Short Introduction*, Very Short Introductions 275 (Oxford: New York : Oxford Univ Press, 2011). Pg. 20

[9] Horsley, *Jesus and the Spiral of Violence*.

[10] Richard Bauckham, *Jesus: A Very Short Introduction*, Very Short Introductions 275 (Oxford: New York : Oxford Univ Press, 2011). Pg. 20

[11] Nicholas Perrin, Jeannine K. Brown, and Joel B. Green, *Dictionary of Jesus and the Gospels (DJG)*, IVP Bible Dictionary Series, K is for Kingdom; Judaism, Common (Downers Grove, Ill: IVP Academic, 2013), http://search.ebscohost.com/login.aspx?direct=true&db=nlebk&AN=633424&site=ehost-live. See: Judaism, Common 1.2.2

[12] Horsley. Pg. 11

[13] Benjamin Uffenheimer, Yair Hoffman, and Henning Reventlow, *Politics and Theopolitics in the Bible and Postbiblical Literature*, Journal for the Study of the Old Testament. Supplement Series (Sheffield, England: Sheffield Academic Press, 1994), http://search.ebscohost.com/login.aspx?direct=true&db=nlebk&AN=243970&site=ehost-live.

[14] Bauckham, *Jesus*.

[15] Horsley, *Jesus and the Spiral of Violence*.

[16] Bauckham, *Jesus*.

[17] Bauckham, *Jesus*.

[18] Bauckham.

[19] F.W. Farrar, "Luke 20," in *Cambridge Bible for Schools and Colleges* (Cambridge University Press, 1891), 20, https://biblehub.com/commentaries/cambridge/luke/20.htm.

[20] Daniel J. Harrington, *The Synoptic Gospels Set Free: Preaching Without Anti-Judaism* (New York ; Mahwah, NJ: Paulist Press, 2009).

[21] *The New English Bible (NEB) New Testament 1961*, vol. Library Copy-Inherited from First Christian Church, Norwalk CA (Oxford University Press, Cambridge University Press, 1961), https://en.wikipedia.org/wiki/New_English_Bible. \added for understanding]

[[22] John Howard Yoder, *The Politics of Jesus: Vicit Agnus Noster*, 2nd ed (Grand Rapids, Mich. : Carlisle, UK: Eerdmans ; Paternoster Press, 1994). Pg. 43-44

[23] Yoder. Pg. 44

[24] Perrin, Brown, and Green, *DJG*.

[25] Immanuel Maurice Wallerstein, "Render unto Caesar?: The Dilemmas of a Multicultural World," *Sociology of Religion* 66, no. 2 (2005): 121--33.

[26] Skye Jethani, Holy Post Podcast, Unknown, https://www.holypost.com/. I recently heard Jethani say something like this; however, I cannot find the quote or podcast episode. I want to ensure I give him credit for inspiring the idea.

[27] Richard E Oster, "'Show Me a Denarius': Symbolism of Roman Coinage and Christian Beliefs," *Restoration Quarterly* 28, no. 2 (1985): 107--15.

[28] Josephus Flavius, "Roman Currency," in *Josephus Flavius: Complete Works and Historical Background (Annotated and Illustrated) (Annotated Classics) Kindle Edition*, trans. William Whiston (Annotated Classics, 2013), 800, https://www.amazon.com/Josephus-Flavius-Historical-Background-Illustrated-ebook/dp/B00B4I367Q.

[29] Ann Spangler and Lois Tverberg, *Sitting at the Feet of Rabbi Jesus: How the Jewishness of Jesus Can Transform Your Faith*, Updated edition (Grand Rapids, Michigan: Zondervan, 2018).

[30] Thomas Lemke, "Render unto God\... What Exactly? An Examination of Matthew 22:15-22," Blog, *The Chi Files* (blog), October 30, 2017, http://thechifiles.com/2017/10/30/render-unto-god-what-exactly/.

[31] Bauckham.
