---
title: 'Gospel Reading: Matthew (Class Assignment)'
date: '2020-10-26T04:13:00.0000000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3477379839403736434'
blogger_filename: '/2020/10/gospel-reading-matthew-class-assignment.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 16pt;"><br /></span></p><p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 16pt;">Gospel Reading:
Matthew</span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12pt;"><br /></span></p><p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12pt;">Darrell
Wolfe</span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Literature,
The King’s University<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Life
of Jesus (BIBL-2302)<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Professor
Jason Moraff<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">October
25, 2020<o:p></o:p></span></p>

<b><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 200%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;"><br clear="all" style="mso-special-character: line-break; page-break-before: always;" />
</span></b>

<p class="MsoNormal" style="line-height: 200%;"><b><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">&nbsp;</span></b></p>

<h4 style="text-align: left;">Questions</h4><h1><o:p></o:p></h1>

<p class="MsoListParagraphCxSpFirst" style="line-height: normal; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->1.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->Lilies
of the Field (Matthew 6:28-30). Even Solomon was not dressed like lilies? I get
that the point is not to worry. But I feel like there is something I’m missing.
How are lilies and clothes comparable? How are Lilies adorned? There is
something deeper here. Maybe if I know something about lilies, I could learn something
about God’s provision?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->2.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->Ch.
8 - I still do not understand why the demons wanted to go into the pigs or why
Jesus let them. I have theories, but nothing fully satisfying.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->3.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->Ch.
9 – How could we retool our churches to be hospitals for the sick rather than just
schools for the healed?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->4.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->Ch.
17 – How often do I look down on “little ones”? Either actual children, finding
even my own children annoying or distracting from my “real work”. Or spiritual
children, those who “know less” than I do? If the least are greatest, am I
seeing them through God’s eyes?<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="line-height: normal; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->5.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->Ch.
25 – I can’t reconcile the 10 virgins. Are they believers? But then they’d all
be allowed in? Are they Christians but five of them are in name only? Not
really saved? Is this parallel to the one taken the other left Jesus referred
to at his coming? <o:p></o:p></p><p class="MsoListParagraphCxSpLast" style="line-height: normal; mso-list: l0 level1 lfo1; text-indent: -.25in;"><br /></p>

<h4 style="text-align: left;">Observations</h4><h1><o:p></o:p></h1>

<p class="MsoListParagraphCxSpFirst" style="line-height: normal; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]-->Matthew
1: Rahab and Ruth were both foreigners brought into the Kingdom of Heaven by forsaking
all they had. Tamar and Bathsheba were women who had been wronged sexually. Mary
was an Israelite who forsook her future to say yes to God and was perceived by
others to be wronged sexually. These five women made the list of Jesus’ family<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/Gospel%20Reading%20Matthew_Stud%20Wolfe,%20Darrell_Life%20of%20Jesus_Prof%20Moraff,%20Jason.docx#_ftn1" name="_ftnref1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[1]</span></span><!--[endif]--></span></a>.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]-->Ch.
4 - Matthew summarizes Jesus’ entire life message as: “Repent for the kingdom
of heaven is at hand” but not “Repent, receive forgiveness, go to heaven when
you die”. Matthew 4:17<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/Gospel%20Reading%20Matthew_Stud%20Wolfe,%20Darrell_Life%20of%20Jesus_Prof%20Moraff,%20Jason.docx#_ftn2" name="_ftnref2" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[2]</span></span><!--[endif]--></span></a><o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]-->Ch.
7 - Gentiles come in and sit with Abraham in the Kingdom. Not a new kingdom.
Not a different kingdom. We come in; they do not come out. We are grafted into Israel;
we are not a separate (<i>implied better</i>) nation. We are part of the same continuous
story.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]-->Ch.
8 - Peter’s Mom gets sick even though he is serving Jesus. I guess life still
happens when we choose to serve. We are not exempt.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]-->Ch.
8:20 - Jesus said he had nowhere to lay his head. Spangler and Tverberg pointed
out that Jesus would have been an itinerate rabbi<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/Gospel%20Reading%20Matthew_Stud%20Wolfe,%20Darrell_Life%20of%20Jesus_Prof%20Moraff,%20Jason.docx#_ftn3" name="_ftnref3" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[3]</span></span><!--[endif]--></span></a>. Therefore,
Jesus is not saying he was “poor” he is saying that he was rejected by some of
the places he traveled and wasn’t accepted into anyone’s home (as was the
custom). <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]-->Ch.
9 – Gentile churches today are often no more friendly to the spiritually sick
than the pharisees that Jesus was confronting. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]-->Ch.
10 – I often hesitate to accept hospitality from those I have served or helped.
I think this a challenge for me to allow community into my life. Breathing in
and out, I must serve but allow myself to be served (10:10 NLT). On that note, am
I more afraid of what people think of me than what God thinks of me? Am I
afraid of people and not afraid of God (10:28)?<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]-->Ch.
26 – Let this cup pass… Even Jesus didn’t always “want” to do God’s will, but
he willed to do God’s will. The emotions need not be present for obedience. <o:p></o:p></p><p class="MsoListParagraphCxSpLast" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -.25in;"><br /></p>

<h3 style="line-height: 200%; text-align: left;">The Gospel According to Matthew</h3><h1 style="line-height: 200%;"><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">If gospel means “good
news”, what was the good news according to Matthew? It was that the old dead
religious ways of being were passing away. A new vibrant way of living was
among us. Matthew presents a Jesus who is rooted and grounded in the history of
Israel’s continuing story both in Jesus’ own family of origin, as well as his fulfillment
of prophecy, and he continues the story in our lives. He summarizes the entire
life message of Jesus by saying that he came to preach one message: “Repent for
the kingdom of heaven is at hand”<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/Gospel%20Reading%20Matthew_Stud%20Wolfe,%20Darrell_Life%20of%20Jesus_Prof%20Moraff,%20Jason.docx#_ftn4" name="_ftnref4" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[4]</span></span><!--[endif]--></span></a>.
I once heard a message from Bob Hamp, LMFT, who said that “repentance” simply
means to think differently afterward. As such, Jesus began to challenge the
minds of all who would listen. He told parables to attempt to alter the way
they thought and the way they saw God’s heart. He said, “you’ve heard… but I
say…”. He demonstrated his authority to challenge the status quo by revealing
his power in healing and miracles. In one section, Jesus made a point to say
that he was showing he had the authority to forgive sins by demonstrating that
authority through healing. Matthew does not tell us of a hero but of the first
and best role model. He is inviting us into the story. Jesus not only demonstrated
this power in himself alone, but he gave it to his apostles as well. This power
was available to anyone who would “have faith”. Jesus frequently comments on those
who have great faith, little faith, and no faith. He frequently puts the
responsibility (good and bad) for outcome back on the receiver, “…your faith has
made you whole”. The Good News of Matthew is that if we will hear and think
differently afterward, we can enter this Kingdom of Heaven now and live a new
kind of adventurous life. He goes on to tell us that there are costs and
rewards associated with this adventure lifestyle. And then he ends by telling
us that we have access to the power of the risen Jesus to go out into the world
and make disciples just as he had. I can almost hear him say “Tag, you’re it”. <o:p></o:p></p>

<div><!--[if !supportFootnotes]--><br clear="all" />

<hr align="left" size="1" width="33%" />

<!--[endif]-->

<div id="ftn1">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/Gospel%20Reading%20Matthew_Stud%20Wolfe,%20Darrell_Life%20of%20Jesus_Prof%20Moraff,%20Jason.docx#_ftnref1" name="_ftn1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[1]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;vQG1nFHW&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;{\\i{}Messiah},
Immerse\\uc0\\u8239{}: The Reading Bible (Carol Stream, Illinois: Tyndale House
Publishers, Inc, 2017).&quot;,&quot;plainCitation&quot;:&quot;Messiah,
Immerse : The Reading Bible (Carol Stream, Illinois: Tyndale House Publishers,
Inc,
2017).&quot;,&quot;noteIndex&quot;:1},&quot;citationItems&quot;:[{&quot;id&quot;:182,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/UD6M72XX&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/UD6M72XX&quot;],&quot;itemData&quot;:{&quot;id&quot;:182,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;\&quot;Immerse:
Messiah is the first of six volumes of Immerse: The Reading Bible. Messiah
takes the reader on a new and unique journey through every book of the New
Testament. Each part of Messiah begins with one of the Gospels, and together,
they combine to provide the reader with enjoyable and impactful readings, all
centered on Jesus. The end result is a Bible developed for the purpose of being
read and understood, not referred to. Messiah is a new way to interact with
God's Word. Messiah delivers Scripture to the reader as it was originally
created: without chapter or verse breaks. While references are made available
for ease of finding specific scripture references, those references do not
appear within the actual text of Scripture. This makes for uninterrupted
reading of God's Word. Created with the look and feel of a paperback book, and
written using the Holy Bible New Living Translation, the most readable
translation available, Messiah enables you to easily read and understand the Bible\&quot;--&quot;,&quot;call-number&quot;:&quot;BS2095
.N394 2017&quot;,&quot;collection-title&quot;:&quot;Immerse : the reading
Bible&quot;,&quot;event-place&quot;:&quot;Carol Stream,
Illinois&quot;,&quot;ISBN&quot;:&quot;978-1-4964-2413-6&quot;,&quot;number-of-pages&quot;:&quot;502&quot;,&quot;publisher&quot;:&quot;Tyndale
House Publishers, Inc&quot;,&quot;publisher-place&quot;:&quot;Carol Stream,
Illinois&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Messiah&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2017&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><i>Messiah</i>,
Immerse : The Reading Bible (Carol Stream, Illinois: Tyndale House Publishers,
Inc, 2017).<!--[if supportFields]><span style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

<p class="MsoFootnoteText" style="text-indent: .5in;"><o:p>&nbsp;</o:p></p>

</div>

<div id="ftn2">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/Gospel%20Reading%20Matthew_Stud%20Wolfe,%20Darrell_Life%20of%20Jesus_Prof%20Moraff,%20Jason.docx#_ftnref2" name="_ftn2" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[2]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;VH9jJ0Mr&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;{\\i{}Hebrew-Greek
Key Word Study Bible: Key Insights Into God\\uc0\\u8217{}s Word. NKJV New King
James Version}, Genuine Black Leather (Chattanooga, TN: AMG Publishers,
2015).&quot;,&quot;plainCitation&quot;:&quot;Hebrew-Greek Key Word Study Bible:
Key Insights Into God’s Word. NKJV New King James Version, Genuine Black
Leather (Chattanooga, TN: AMG Publishers,
2015).&quot;,&quot;noteIndex&quot;:2},&quot;citationItems&quot;:[{&quot;id&quot;:93,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/CUWK86LA&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/CUWK86LA&quot;],&quot;itemData&quot;:{&quot;id&quot;:93,&quot;type&quot;:&quot;book&quot;,&quot;edition&quot;:&quot;Genuine
Black Leather&quot;,&quot;event-place&quot;:&quot;Chattanooga,
TN&quot;,&quot;ISBN&quot;:&quot;13:
978-0-89957-868-2&quot;,&quot;language&quot;:&quot;English&quot;,&quot;number-of-pages&quot;:&quot;2,615&quot;,&quot;publisher&quot;:&quot;AMG
Publishers&quot;,&quot;publisher-place&quot;:&quot;Chattanooga,
TN&quot;,&quot;title&quot;:&quot;Hebrew-Greek Key Word Study Bible: Key
Insights Into God's Word. NKJV New King James
Version&quot;,&quot;title-short&quot;:&quot;Key Word
NKJV&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2015&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><i>Hebrew-Greek
Key Word Study Bible: Key Insights Into God’s Word. NKJV New King James Version</i>,
Genuine Black Leather (Chattanooga, TN: AMG Publishers, 2015).<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn3">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/Gospel%20Reading%20Matthew_Stud%20Wolfe,%20Darrell_Life%20of%20Jesus_Prof%20Moraff,%20Jason.docx#_ftnref3" name="_ftn3" title=""></a><o:p>&nbsp;</o:p></p>

<p class="MsoFootnoteText" style="text-indent: .5in;"><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[3]</span></span><!--[endif]--></span>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;F3FfGKW2&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Ann
Spangler and Lois Tverberg, {\\i{}Sitting at the Feet of Rabbi Jesus: How the
Jewishness of Jesus Can Transform Your Faith}, Updated edition (Grand Rapids,
Michigan: Zondervan, 2018).&quot;,&quot;plainCitation&quot;:&quot;Ann Spangler
and Lois Tverberg, Sitting at the Feet of Rabbi Jesus: How the Jewishness of
Jesus Can Transform Your Faith, Updated edition (Grand Rapids, Michigan:
Zondervan, 2018).&quot;,&quot;noteIndex&quot;:3},&quot;citationItems&quot;:[{&quot;id&quot;:186,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/VFB8VX5A&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/VFB8VX5A&quot;],&quot;itemData&quot;:{&quot;id&quot;:186,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;Sitting
at the Feet of Rabbi Jesus takes readers on a fascinating journey, helping them
discover how learning about the Jewish world of Jesus can enrich their own
faith. This newly expanded softcover edition includes a discussion guide and a
Jewish Seder liturgy&quot;,&quot;call-number&quot;:&quot;BT590.J8 S63
2018&quot;,&quot;edition&quot;:&quot;Updated
edition&quot;,&quot;event-place&quot;:&quot;Grand Rapids,
Michigan&quot;,&quot;ISBN&quot;:&quot;978-0-310-33069-1&quot;,&quot;number-of-pages&quot;:&quot;301&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Michigan&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Sitting at the Feet of Rabbi Jesus: How the
Jewishness of Jesus Can Transform Your
Faith&quot;,&quot;title-short&quot;:&quot;Sitting at the feet of Rabbi
Jesus&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Spangler&quot;,&quot;given&quot;:&quot;Ann&quot;},{&quot;family&quot;:&quot;Tverberg&quot;,&quot;given&quot;:&quot;Lois&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2018&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Ann
Spangler and Lois Tverberg, <i>Sitting at the Feet of Rabbi Jesus: How the
Jewishness of Jesus Can Transform Your Faith</i>, Updated edition (Grand
Rapids, Michigan: Zondervan, 2018).<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p><p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/Gospel%20Reading%20Matthew_Stud%20Wolfe,%20Darrell_Life%20of%20Jesus_Prof%20Moraff,%20Jason.docx#_ftnref4" name="_ftn4" title=""><span class="MsoFootnoteReference"><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[4]</span></span></span></a> <i>Key
Word NKJV</i>. 4:17</p></div><div id="ftn4"><p class="MsoFootnoteText"><o:p></o:p></p>

</div>

</div>
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
