---
title: 'Class Assignement: Practicum: Reflection Essay'
date: '2021-11-29T01:04:00.0060000+00:00'
draft: false
categories:
  - 'Class Assignment'
  - 'Musing'
---
### Practicum: Reflection Essay

The King's University, Southlake, Texas

Junior Ministry Practicum (BIBM3201)

Professor: Holley Clough, D.Min.

Final Due: 12/05/2021

By Darrell Wolfe

### Reflection Essay for Practicum 1 of 2

#### Personal Background

For following reflection to make sense, I must start with my personal background. I grew up as a Pastor's Kid (PK) in the Disciples of Christ (DOC). I have seen the inside of church ministry, politics, scandals, abuse of the congregation by the pastor, abuse of the pastor by the "elder board". I have watched a church fire the pastor because they wanted a country club and not a church. I have watched church(es) chase the move of God out of the door so they can maintain their status quo and comfort. Hoping for healthier and better expressions of Christianity, I went searching.

In the following decades (and in three separate states), I transitioned from Evangelical Free (Eve-Free), to Calvary Chapel, to Pentecostal, to Word of Faith, to the Spirit-Filled Non-Denominational Mega Churches (including but not limited to Gateway Church). I also visited 100s of other churches during those years that I did not join. In those decades, I have been an audio engineer, usher, worked closely with leadership as a Worship Leader. I have taught classes but purposefully avoided the Sunday pulpit (a long story related to the paragraph above). I've done just about everything, seen every back hallway, where the audio cables are fed to the stage, and what the "pastor" is like behind closed doors in his office when he's mad. I've experienced some healthy things, but unhealthier on balance.

After almost losing my marriage to a midlife crisis (2013-2016), and then getting restored (2017), and then loosing my wife to sudden unexpected death (2018), I went through a full deconstruction and reconstruction of my faith (2018-2019). I learned what matters and what doesn't matter. What matters is the people who show up at your house and sit with you in tragedy, none of them were from the churches I was involved in. They were all people I met from outside the walls of the church, in places where community thrives. Many of them were de-churched, displaced by the machine I describe below. I learned that the sweet smell of rain, or sight of snowy treetops can wash a soul, and about the quiet moments where you hear Yahweh's voice say "you are mine" as you walk silently in the forest. I've discovered the beauty of academia, and the richness of studying his word deeper in healthy safe community.

In Summer 2021, I spent time visiting as many different expressions of Christianity as I could find with the goal of ignoring anything I did not like and only focusing on the good.[\[i\]](https://draft.blogger.com/#_edn1) I found beauty in a variety of expressions. I found new ways of doing music and even teaching that sparked my interest and gave me ideas. What I did not find; however, was the solution to the one issue I see in modern western Christianity: Community. Without fail, each group was hyper-focused on the Sunday-Spectator-Event (with on possible exception, but that would be for another paper).

#### The Church

After all my experiences, even now in Fall 2021, I cannot bring myself to say that "church" (the business-entity not the people, the body) as is it exists in modern western Christianity has been a net-positive experience in my life. It most certainly had its positive impacts; however, on balance I cannot say it was a "net" positive. I appreciate the classes, like Gateway Freedom Ministry and Kairos (which were the healthiest expression of "church" I've ever seen), and the various events that foster connection (the few I found), and the resources churches pour into local civic communities (such as women's ministries, feeding the poor, etc.).

Sunday Morning has become an event, not a community. Frankly, it is the least relevant part of my Faith Journey. By and in large, what I find is that "churches" (whether 200-members or 65,000 members) have become event-based organizations. People come, spectate, and leave without ever really knowing anyone else. Even small groups and mid-week classess are events, they all foster this same spectator environment. I can count on one, maybe two, hands the number of people I've built lifelong relationships with via churches in my lifetime. Most of my lifelong, Jesus loving, God Fearing, Bible Believing friends were met through other means.

As I see it, COVID-19 was the best thing to ever happen to the church. People realized what "an event" it had become. Many now say they can "get church at home, why go?" To that I say, you are right. Our modern expression of church does not require you know anyone else, be connected to anyone else, or even physically attend the "gathering". A first-century Christian would be appalled at what we have become. Frankly, I believe that modern western Christianity as become the church of Laodicea (Revelation 3:14-22). We are blind, miserable, and naked, and we don't even recognize it. We think we are the model when we are the anti-model. But COVD-19 woke many of us up to the lack of community in our lives. We began meeting with others one-on-one, or in small spontaneous groups, even though the "building" was closed.

I love Yahweh, and his son Yeshua, and his Spirit (Ha-Ruach-Elohim). The King's University (TKU) opened the Word of God (the Bible) to me in new and exciting ways. Classess opened the world of biblical scholarship, which was life-changing for me. Through scholarship, I came to know the work of Drs N.T. Wright, Michael Heiser, John Walton, and Tim Mackie, among others, each of whom have radically shifted my biblical worldview for the healthier.[\[ii\]](https://draft.blogger.com/#_edn2) I have become more convinced than ever before in the integrity and authority of the Bible as God's divine word, his revelation of his will on earth. Peter Scazzero showed us glimpses of what an Emotionally Healthy Christianity could be.[\[iii\]](https://draft.blogger.com/#_edn3) Which leads me to my experiences in Practicum.

#### Practicum Specific Reflection

With that background laid, I think this Practicum would have been a much different experience if I were a child of 18-20 coming out of my parent's home, or I was a stranger to the "church" or hadn't been so closely involved for decades. If I didn't see "church" as something that ultimately needs to be replaced with an entirely new model, unlike anything we do today.

When I read, "the Ministry Practicum is considered to be one of the most critical elements in a student's course of study". I shrug my shoulders and wonder how that could be true. I have seen the inside of churches, ministries, and parachurch organizations for decades before this semester. I do not believe this reaction would be any different if I had served at a church instead of a para-ministry. I would much rather have spent my time and money on two more courses aimed at academic biblical studies. I specifically chose a non-church ministry hoping to see something different, I did not.

This practicum served to re-enforce my existing perspective that we have layered too many things on top of "ministry" and lost the core of what it is: Family. I watched people get processed through a system and "assigned" a mentor, who then had to chase them around and hope for the mentee to show up. There were lots of ideas about how to "engage" the mentee, but no sense of community or family. After six months, I do not know my mentees or fellow mentors better than I did before. We mentors talked some, but no facilitation was set up to build a community even among ourselves. That, as I see it, is the crux of the issue in modern western Christianity.

The first-century church thrived because of its community, and the 21st century church is dying for the lack of it. Whether a mega church, a small local church, or a prison ministry, we've lost track of how to build real community. This could be a result of our rugged American fascination with "independence".

I have ideas about how we could have done things differently. But my ministry supervisor is so busy because of the system, chasing mentees down and processing them through the system, and meeting deadlines, that he doesn't have time for another task. I offered to sit and discuss some ideas, but he was too busy to get around to it. My ministry supervisor sees the same issues I do; however, he is not in a position to do anything about it today. The system he is working with is beyond his control too. I had two mentees, both failed to show to most appointments. I spent most of my time trying to chase down people who ultimately did not want to have a mentor and only signed up for the program out of coercion. I was reminded that my time is valuable and would be better spent with people who want the brotherhood and fellowship.

My own mentor (not through this program) showed me that for those who want mentorship it is invaluable. He takes an entirely different tact in meeting with as many people as possible met through as many means as possible. Some never come back to a second meeting, some he meets with regularly. Some of the ways he does his activities would be worth incorporating into my future work with people. His first words to me were this: "My vision of mentor means that one of us is at the other's funeral, because we were that close."

#### What can I do?

The first church thrived because they became the "family of God". By family, they meant family. People were often blacklisted from their biological family for joining The Way. They shared their lives together, homes, and built communities. They taught incomers Greek so they could read the Septuagint and the New Writings. They shared resources so that none lacked. Churches were named after their city because they were one.

In this sense, I got something valuable out of this Practicum. I became convinced beyond the shadow of any doubt that the issue God has been driving home inside of me for decades (community), is up for me to do something about. The system won't change until people start to do new things. In my laziness, I would rather someone else start the thing, and then I could come participate and help. But it hasn't happened. I must be the change I want to see in the world.

I have a second practicum to participate in. I recently joined the healthiest possible expression of a church I could locate in my region of the USA. The pastor and I have a kindred spirit and he sees the issues I see as well. He wants to do something about it. Maybe if we put our heads together, we can learn from each other and develop something, without totally dismantling the existing structures.

Subtle change. Dr. Davis (TKU Advisor) recently encouraged me to consider the possibility that the entire system does not have to be dismantled to make the appropriate changes. Right after that discussion, I went with my ministry supervisor to a meeting where I met a pastor at a local Presbyterian church (who is starting his own Celebrate Recovery program). As we talked about the changes he is making in his own congregation, he provided similar wisdom. He said that when he gives them the entire vision, they shut down and resist. However, he found that if he leads them an inch at a time, they move without realizing it. Then, as they look back, they find they've gone father than the original vision would have carried them. He encouraged me to consider that perspective. Sometimes the visionary must hold the change close to the vest and lead the people slowly through levels of change.

As I thought about this, I realized I can start small. I don't need an entire building and ministry of my own (just yet). I can also cultivate community where I am. Many times, I have a big vision of a building and I feel I cannot make a change without having everything in place. But I can start with the tools I have in front of me. I can build a community centered around studying the Bible, leaning into emotional health, and building relational connection with one another. I can start a community that is not "event based", has no Sunday "services" for people to be spectators of, and is structured in a way that builds an environment for connections. That need not wait for a building or a logo. Whether that looks like meeting some folks at the coffee shop, building my own coffee shop, or building a Non-Profit of my own, I can be the change I want to see in the world.

If this practicum did anything, it was to force my hand. I said "yes" to Yahweh. I'm not rushing out to open my own ministry today; however, I am no longer waiting for someone else to do it. I will begin listening, writing, researching, talking about, and building the backbone of the structure I want to see; so that, I will be ready when the opportunity and doors open.

#### Notes

[\[i\]](https://draft.blogger.com/#_ednref1) "My Ecumenical Walk-About\... #EcumenicalWalkAbout \~ Darrell Wolfe, Storyteller," accessed November 28, 2021, http://www.darrellwolfe.com/2021/05/my-ecumenical-walk-about.html.

[\[ii\]](https://draft.blogger.com/#_ednref2) N. T. Wright and Michael F. Bird, The New Testament in Its World: An Introduction to the History, Literature, and Theology of the First Christians (London : Grand Rapids, MI: SPCK ; Zondervan Academic, 2019); N. T Wright, Surprised by Hope (Place of publication not identified: HarperCollins e-Books, 2014), http://rbdigital.oneclickdigital.com; Michael Heiser, The Unseen Realm: Recovering the Supernatural Worldview of the Bible, First edition (Bellingham, WA: Lexham Press, 2015); John H Walton, The Lost World of Genesis One: Ancient Cosmology and the Origins Debate. (Westmont: InterVarsity Press, 2010), https://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=2030851; Tim Mackie and Jon Collins, "BibleProjectTM Videos and Podcasts," accessed June 18, 2021, https://bibleproject.com/.

[\[iii\]](https://draft.blogger.com/#_ednref3) Peter Scazzero, Emotionally Healthy Spirituality - Its Impossible to Be Spiritually Mature,. (Zondervan, 2014).
