---
title: 'Eschatology: Vision is not the Message. Group 8'
date: '2021-02-10T04:47:00.0040000+00:00'
draft: false
---
***Saunders, Dr. Eugene. "Old Testament Survey (BIBL1305)." Coursework, The King's University, Southlake Texas, 2021.***

### Discussion Responses

#### FORUM 1: INTRODUCTION TO PROPHETS

***Of what significance for eschatology is the principle that the vision is not the message, but the occasion for the message? Assigned to: Group 8***

#### Eschatology: Vision is not the Message. Group 8

No other ancient culture had an eschatological prophetic concept. Israel is unique in their understanding of the one true God, who plans the end from the beginning.[\[1\]](#_ftn1) Since we understand that God has a plan, we may ask "of what nature is that plan?" One possibility is to view the plan like a professor's syllabus. In this view, the basic outline is set upfront, but the actual outworking of the plan may morph and change as they take final shape.[\[2\]](#_ftn2)

For the prophet, the prophecy was about the message his audience needed to hear. The future-telling, storyline, visionary tale/setting, were all context or wrapping in which the message was to be understood. The "way" in which the message was delivered (through story, analogy, a vision, etc.) was of less importance than the message.[\[3\]](#_ftn3)

Human beings are "Wired for Story".[\[4\]](#_ftn4) "We don't turn to Story to escape reality; we turn to Story to navigate reality."[\[5\]](#_ftn5) The ultimate purpose of the prophet's storytelling was the get the message across.

All this brings us to the impact on "eschatology":

1\. When one attempts to interpret a prophetic word, one should focus on the message first (what the prophet intended to communicate to the audience).

2\. The "fulfillment" may come; however, one should be aware that God's idea of fulfilling a prophetic idea may look different than what the author (or reader) expected. Who could have known that the "Passover Lamb" would be a man hung on a cross?

3\. Finally, one should be cautious in interpreting "symbols" that God, the prophet, or other scripture has not clearly defined. The symbols may only exist as a wrapping to hold the message itself. Some symbols may have no deeper or hidden meaning.

While some symbols, like Nebuchadnezzar's statue (Daniel 2) are clearly defined and easy to follow; other symbols, like the basket of Zechariah 5 may have no deeper meaning.[\[6\]](#_ftn6) Trying to assign more meaning than the text provides can be dangerous. Giving more weight to a symbolic concept than scripture itself can support (without mental gymnastics) is a recipe for error.

**Note: This may be how we came up with the idea of a 7-year tribulation and rapture (which both may or may not biblical concepts).[**\[7\]**](#_ftn7)*

------------------------------------------------------------------------

[\[1\]](#_ftnref1) Andrew E. Hill and John H. Walton, *A Survey of the Old Testament*, 3rd ed (Grand Rapids, Mich: Zondervan Publishing House, 2009), 507.

[\[2\]](#_ftnref2) Hill and Walton, 512.

[\[3\]](#_ftnref3) Hill and Walton, 508--9.

[\[4\]](#_ftnref4) Lisa Cron, *Wired for Story: The Writer's Guide to Using Brain Science to Hook Readers from the Very First Sentence*, 1st ed (New York: Ten Speed Press, 2012), http://wiredforstory.com/about.

[\[5\]](#_ftnref5) Lisa Cron, "Wired for Story: Lisa Cron at TEDxFurmanU" (Ted Talk, TEDxFurmanU, Furman University, Greenville, South Carolina, May 4, 2014), 11:00-11:30, https://www.youtube.com/watch?v=74uv0mJS0uM.

[\[6\]](#_ftnref6) Hill and Walton, *A Survey of the Old Testament*, 508.

[\[7\]](#_ftnref7) Jonathan Welton, *Raptureless*, 3rd Edition Printing (Place of publication not identified: Bookbaby, 2015), http://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=4188734.

------------------------------------------------------------------------
