---
title: 'Rethinking the "tithe", biblically. A study of Malachi and its implications.'
date: '2021-03-03T04:01:00.0020000+00:00'
draft: false
categories:
  - 'Studies'
---

<h3 style="text-align: left;">Charles Asks:&nbsp;</h3><div class="dbThreadBody" style="-webkit-text-stroke-width: 0px; background-color: white; clear: both; color: #111111; font-family: &quot;Open Sans&quot;, sans-serif; font-size: 12.8px; font-style: normal; font-variant-caps: normal; font-variant-ligatures: normal; font-weight: 400; letter-spacing: normal; orphans: 2; outline: 0px; padding-bottom: 0.6em; text-align: start; text-decoration-color: initial; text-decoration-style: initial; text-decoration-thickness: initial; text-indent: 0px; text-shadow: none !important; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px;" tabindex="0"><div class="vtbegenerated" style="background: transparent !important; display: block; font-family: &quot;Open Sans&quot;, sans-serif; font-size: small; letter-spacing: normal !important; margin: 0px !important; overflow-wrap: break-word; overflow-x: auto; padding: 0px !important; position: relative; text-shadow: none !important;"><ul style="text-align: left;"><li>Do you have any opinion about Mal.3:8-10, which is used by preachers when they want to talk about the tithe? Thank you.</li></ul></div></div><h3 style="text-align: left;">Rethinking the "tithe".&nbsp;</h3><p style="text-align: left;">What would a text-driven (not theology driven) evaluation of "tithe" tell us about the topic? Could it create a new way we think about it?&nbsp;</p><p style="text-align: left;">Many pastors use Malachi 3:10 to discuss the tithe (I was one of them until tonight). After further review, I think we need to tweak how we use this verse if we are to remain consistent and connected to the context of the verse, writer of the verse, original audience of the verse, and context of the verse within the larger message.&nbsp; <br /></p><h4 style="text-align: left;">Evaluating the "context" of the short prophetic book of Malachi:</h4>

<p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">&nbsp;</p>

<ul style="text-align: left;"><li>Malachi 1: The
people had viewed the sacrifices to God as burdensome and tiresome. They
scoffed while doing it and gave him the worst, the left-overs (the sin of Cain,
Genesis 4). They were not putting God first or taking pleasure in his covenant
with them. <br /></li></ul><ul style="text-align: left;"><li>Malachi 2: A rebuke
of the priests. The leadership were leading the people into disdaining God. He
had given the system to sustain the priests and they were taking it for
granted. So he stopped accepting it from them. <br /></li></ul><ul style="text-align: left;"><li>Malachi 3: Prophetic
call of John the Baptist and the coming of YHWH himself to the temple. Followed
by, a rebuke of the attitude toward sacrifices. They rob God of their covenant
believing loyalty to him. This harkens back to the idea that they "gave"
but it was only the worst of what they had, the left-overs. He was calling them
back to giving their first and best to God. It was their heart, not just their
tithe, that they robbed God of. They were giving their believing loyalty to
other gods (elohim). <br /></li></ul><ul style="text-align: left;"><li>Malachi 4: After
reviewing a pattern of covenant dis-loyalty; of honoring God with lip service
and half-hearted ritual motions, but not having a believing loyalty of heart,
honoring him with their best, being grateful for his covenant blessing… God
ends on a prophetic word that many Christians today are either unaware of or
barely aware of. God essentially says: I'm going to tear down your whole gig
once and for all. It's all coming down. Some of you will be vindicated, those
who stay loyal to me. The rest are being burned down so totally, that not even
a root or branch will be left. I'm done. In 70AD, the nation was burned down,
every stone of the temple was removed, even the foundation stones. The people
were hunted down. One was killed, the one next to him was taken into slavery
(one taken, another left (dead), just like Jesus said would happen in Matthew
24). Shockingly, no Christians were reported to have died by Josephus or early
church fathers, they all headed Jesus' warning and when the abomination of
desolation stood in the Temple, they fled and survived that slaughter. </li></ul>

<p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">&nbsp;</p><p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">&nbsp;</p>

<h4 style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">Can Malachi 3:10 be
applied to tithing? </h4>

<p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">&nbsp;</p>

<p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">Maybe. If and only
if, the entire context is discussed. Tithing predates the Mosaic covenant.
Abraham tithed and Jacob tithed long before Moses was a twinkle in anyone's eye
(Genesis 14:20; 28:22). So one cannot rule out the principle of tithing by saying the Mosaic Law no longer applies.&nbsp;</p><p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">&nbsp;</p><p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">Tithing as a concept predates the "law". So there is
precedent for the practice. However, one should not overstate the precedent. There are two direct hints that it was performed once-each by Abraham and Jacob. There are no indications it was a regular occurrence. There are no indications it was a regular practice of all people all the time. Both were performed in extra-normal circumstances, more akin to a first-fruits offering than a weekly "tithe". <br /></p><p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">&nbsp;</p><p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">Paul doesn't really address "tithing" as
much as he does giving. While his silence is noteworthy, given the context of his background as a Pharisee; it is not proof of anything either way. One cannot make an argument from silence. Paul does say that "giving" is to be done with a grateful
heart and from a place of charity not "have-to-ness" (2 Corinthians
9:6-9). Paul may have had Malachi in mind when he gives this instruction. </p>

<p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">&nbsp;</p>

<p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">Tithing is one of
the few things Jesus praised the Pharisees for (Matthew 23:23). Jesus praised the
widow for the small amount she put in, because it was out of her lack that she
still gave to God (Mark 12:41-44). </p>



<p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">&nbsp;</p>

<p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">Here is the point,
if you use Malachi 3:10 to put your congregation under bondage to the law, they
might obey it with their checkbook but not with their hearts. This was the exact issue Malachi was rebuking. <br /></p>&nbsp;

<p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">Paul appears to have
removed the percentage from the equation to remove the legalistic mindset. The
very thing Paul warns about (do it from a place of gratitude, not reluctance or
compulsion) is the very thing Malachi was warning about. They "tithed"
with outward motions. But the quality of their tithe (both the gift and heart
of the giver) was far from God's covenant loyalty. </p>

<p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">&nbsp;</p><p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">Paul, in essence, says: Be loyal to God,
give what he moves on your heart to give, do it cheerfully and without
compulsion. If you cannot give without compulsion, you may even want to wait
until your heart is fixed first then give. Heart first, gift second. The gift
should be a reflection of the heart. </p>

<p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">&nbsp;</p>

<p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">&nbsp;For the New Covenant Disciple of Jesus, 2 Corinthians 9 (not Malachi 3:10) should drive our giving:<br /></p>

<p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">&nbsp;</p>

<p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;"><i></i></p><blockquote><i>2 Corinthians 9:6-9: 9:6&nbsp;My point is
this: The person who sows sparingly will also reap sparingly, and the person
who sows generously15 will also reap generously. 9:7&nbsp;Each one of you
should give16 just as he has decided in his heart,17 not reluctantly18 or under
compulsion,19 because God loves a cheerful giver. 9:8&nbsp;And God is able to
make all grace overflow20 to you so that because you have enough21 of
everything in every way at all times, you will overflow22 in every good work.
9:9&nbsp;Just as it is written, “He23 has scattered widely, he has given to the
poor; his righteousness remains forever.”24&nbsp; Biblical Studies
Press, The NET Bible First Edition; Bible. English. NET Bible.; The NET Bible
(Biblical Studies Press, 2005), 2 Co 9:6–9.</i></blockquote><p></p>

<p style="font-family: Calibri; font-size: 11pt; margin: 0in; text-align: left;">&nbsp;</p><p>

Selah.</p><p>This was a one-hour study, not exhaustive, if you have any thoughts that add to or even correct this, please share in the comments below. <br />
<br />
<br />
<br />
</p><div id="mc_embed_signup" style="text-align: left;">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label></div>
