---
title: 'Class Assignment: Genre Analysis: Gospels, Epistles and Apocalyptic Literature'
date: '2021-10-26T06:01:00.0090000+00:00'
draft: false
categories:
  - 'Studies'
  - 'Class Assignment'
  - 'Biblical Studies'
  - 'Armchair Theology'
---
### Genre Analysis: Gospels, Epistles and Apocalyptic Literature

The King's University, Southlake, Texas

Biblical Background and Interpretation (2021FA-BIBL-2301-ONL)

Professor: Dr. J. Wallace

Due: 10/31/2021

By Darrell Wolfe

#### Gospels, Epistles and Apocalyptic Literature

Early Jesus communities considered themselves to be the fullness of the covenants of Israel and used the Tanakh, or often the Greek Septuagint, as their scriptures. These communities began to produce literature themselves to supplement and augment their new way of life. These writings supported their origins (**Gospels**), helped flesh out what had changed and how they should conduct themselves as a community going forward (**Epistles**), and provided one final encouragement (**Revelation**).

The word **Gospel** comes from the Greek word "euangelion", which had firm roots in the Imperial Religion.[\[1\]](https://draft.blogger.com/#_ftn1) By producing the four accounts of Jesus, the early church not only made Jewish claims about the promised Messiah but counter-cultural claims about the real Lord and who brought peace (the not-Caesar). These gospels made claims that set this community apart from both the Traditional-Jewish and Roman worlds. The authors also took the opportunity to arrange information carefully, highlighting the points they wanted to make by which stories they included, and in which order. Each of the four gospels carries through its own theme.

The books known as the **Epistles** (letters) were written by Apostles to the churches they over-saw, and they were intended to be read aloud to the entire community (and often shared).[\[2\]](https://draft.blogger.com/#_ftn2) Although many were written by Paul; Peter, John, James and Jude (Jesus' biological brothers), and the unknown author of Hebrews (along with their scribes) each make a showing. These books provided pastoral oversight and theologically significant claims, often quoting from the Tanakh/Septuagint, about who Jesus was and how his body should conduct their lives because of his coming. Often, questions or issues in the community provided the occasion for the writing.[\[3\]](https://draft.blogger.com/#_ftn3)

Finally, John gave us the **Apocalypse (Revelation)**, which provided comfort to the persecuted church while offering a compelling vision of final things.[\[4\]](https://draft.blogger.com/#_ftn4) As things began to get dark for the early church (as Jesus' said they would), it would be easy to bow to the pressure and leave the faith behind. Following in the schema of other Jewish Apocalypses, John writes a visionary narrative promising that one day, Heaven and Earth will be made new, united again as it was "In the Beginning".

#### Bibliography

Duvall, J. Scott, J. Daniel Hays, and Mark L. Strauss and Kevin J Vanhoozer. Grasping God's Word, Fourth Edition: A Hands-On Approach to Reading, Interpreting, and Applying the Bible, 2020.

Fee, Gordon D., and Douglas K. Stuart. How to Read the Bible for All Its Worth. 3rd ed. Grand Rapids, Mich: Zondervan, 2003.

The Lexham Bible Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott, C., ... Widder, W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham, WA: Lexham Press. Billingham, WA: Leham Press, 2016. LexhamPress.com.

#### Notes

[\[1\]](https://draft.blogger.com/#_ftnref1) The Lexham Bible Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott, C., ... Widder, W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham, WA: Lexham Press. (Billingham, WA: Leham Press, 2016), Gospel Genre \> Backgrounds to the New Testament Usage of Gospel \> Imperial Relgion, LexhamPress.com; \|\| J. Scott Duvall, J. Daniel Hays, and Mark L. Strauss and Kevin J Vanhoozer, Grasping God's Word, Fourth Edition: A Hands-On Approach to Reading, Interpreting, and Applying the Bible, 2020, 280. What are the Gospels?

[\[2\]](https://draft.blogger.com/#_ftnref2) Duvall, Hays, and Vanhoozer, Grasping God's Word, Fourth Edition, 263.

[\[3\]](https://draft.blogger.com/#_ftnref3) Gordon D. Fee and Douglas K. Stuart, How to Read the Bible for All Its Worth, 3rd ed (Grand Rapids, Mich: Zondervan, 2003), 58.

[\[4\]](https://draft.blogger.com/#_ftnref4) Duvall, Hays, and Vanhoozer, Grasping God's Word, Fourth Edition, 333.
