---
title: 'Reflection Paper: Partnering with the Holy Spirit - For “The Spirit-Formed Life (BIBM1301).”'
date: '2021-03-02T04:56:00.0010000+00:00'
draft: false
categories:
  - 'Studies'
---
*Coulter, Leah. "The Spirit-Formed Life (BIBM1301)." Coursework, The King's University, Southlake Texas, 2021.*

## Reflection Paper: Partnering with the Holy Spirit

The King's University, Southlake, Texas

The Spirit-Formed Life (BIBM1301)

Professor: Dr. Leah Coulter

March 7, 2021 (Extended, by Instructor)

By Darrell Wolfe

### Living the Spirit-Formed Life

In *Living the Spirit Formed-Life*, Pastor Jack Hayford discusses ten disciplines of the Spirit which he feels are important for the life of a believer.[\[1\]](#_ftn1) He uses analogies from various texts to paint pictures around these disciplines. They are as follows:

1.      *Hearing God's voice*: Hayford establishes that God's word is clear about his people hearing his voice.[\[2\]](#_ftn2) It is up to the disciple of Jesus to cultivate their own hearing and listen.

2.      *Living in the Power of Baptism*: Hayford builds a case for understanding baptism as a command of scripture.[\[3\]](#_ftn3) He summarizes this notion by the phrase: "Be baptized. *Live* baptized."[\[4\]](#_ftn4)

3.      *Celebrating the Lord's Table*: As with baptism, Hayford makes the case for understanding The Lord's Supper (also known as Communion) as a command of scripture.[\[5\]](#_ftn5) He says it is significant as a remembrance of Jesus' victory at the cross, declaration of dependence on Jesus, a time for self-examination, and he also claims it is a provision for healing.[\[6\]](#_ftn6)

4.      *Walking in the Spirit of Forgiveness*: The Christian is to live in a place of extravagant forgiveness, just as we are extravagantly forgiven. It could be life or death for some people.[\[7\]](#_ftn7)

5.      *Feeding on the Word of God*: After giving the reader permission to chill-out a bit about "how" they go about digesting God's word, he provides principles for understanding why it is important. Ultimately, he concludes, "Live in it. Live by it. Live through it. Daily."[\[8\]](#_ftn8)

6.      *Maintaining Integrity of Heart*: Hayford defines this topic as "openness and transparency before God".[\[9\]](#_ftn9) When the believer remains open and transparent before God, he has room to work in the believer's life.

7.      *Abiding in the Fullness of the Spirit*: Hayford begins with an especially hard lesson for many intellectuals, males, and intellectual males; "open to the spirit of enthusiasm".[\[10\]](#_ftn10) One must remain pliable to the way the Spirit of Gods want to move them.

8.      *Living a Life of Submission*: This entire chapter can be summarized by a mic-drop-moment quote driven by the story of the centurion who had great faith: "He understands that his submission -- alignment with the authority placed over him -- is the source of the power available to him... his role as a "submitted" man has given rise to the power and authority he exercises".[\[11\]](#_ftn11)

9.      *Practicing Solitude*: Hayford begins by saying: "The hallmark of people who... experience trials beyond anything they had known before and come through with faithfulness, stability, and strength of character -- is that they have learned a simple way... quietness/solitude."[\[12\]](#_ftn12) When life crashes and burns, shatters beyond a million pieces, to dust which then blows away -- there is nothing left to hold one's rhythms.

10.  *Living as a Worshiper*: Worship is *whole-life*, including our attention, belongings, time, and abilities. When every aspect of our life is given to and submitted to God, then our worship is complete. [\[13\]](#_ftn13)

### Practicing the Disciplines of the Spirit

The four disciplines I have found are inescapable are Hearing God's voice, Feeding on the Word of God, Maintaining Integrity of Heart, and Practicing Solitude. I summarize them with the social media hashtag: "#BeStillBeLed". I would combine his written and spoken Word into one category. They are like breathing. I breath in God's Word (spoken and written), I breath out by being led. The practice of solitude cultivates an environment whereby the words (spoken and written) of God can be heard by my heart. I used to try to read in the mornings, but I found my ADD brain falls asleep. What I found works better, is quiet morning walks. I don't "pray" in the traditional sense. I just walk, ask God what he wants to talk about, and let him lead the conversation. I study and read his word consistently; however, it is in these walks where he takes the written word and makes it alive to me and my situation today.

The only "discipline" suggested in the practice sessions that I was not already practicing was The Lord's Supper.[\[14\]](#_ftn14) I would argue scripturally for less emphasis on Baptism and Lord's Supper than Hayford does. While I see their importance, I think he overstates them. Nevertheless, I also admit I could be understating them. So, I had communion by myself in my room. It was no magical experience; however, it was a sober reminder of what it cost YHWH to have me. I am worth what he paid, and he paid everything. It also helped me remember that he died for "them" too and made me less combative and more prayerful about how I interact with other people.

The chapter on integrity of heart was driven home for me on January 6, 2017, when my (now late) wife led me into a season of healing. It was through being completely open and transparent and vulnerable with men, her, and God that I found the inner-healing I had been searching for my whole Christian life. Out of that season, she and I came up with a life-motto: NO HIDING. The more I press into transparency, the more I lean-in to the hard stuff my heart begs me to avoid, the freer I become. The more secrets I hold, the more bound I become. The fastest way to stay free, is to never hide anything. One cannot "fall from grace" if they do not pretend piety in the first place. I am a fallen human, saved by grace, filled by the spirit, and walking out this life with an enemy who is constantly after my walk with God. If I press into NO HIDING, I have no secrets to expose because I exposed them already. It may ruin the image someone tried to have of me, but it keeps me free and authentic. The longer I live this way, the harder it is to keep company with anyone who does not also live this way. Authentic transparency has become the standard by which I determine how close I will become to people. I will love on everyone, without judgment. The "sinners" enjoy hanging out with me because they find no pretense in my presentation. While I stand for truth, I lead them to Jesus and let Him deal with whatever changes he sees fit to bring. That being said, to be in my inner circle requires radical transparency, NO HIDING.  I would argue that this type of radical transparency is the first and primary of the "disciplines" for me.

Hayford says that his approach is "nontechnical and insistently practical" because, "God is not so interested in educating us as He is in transforming us".[\[15\]](#_ftn15) He also said that these were the disciplines he found most useful, which means they are not an "authoritative list". If I wrote ten, I would probably re-order them, remove some, add others. What I enjoyed about his approach was that he made room for that type of thinking. These were the ones he chose, and the spirit of them allows for shift in the reader who would apply them.

### My Partnership with the Holy Spirit

In *Breaking Old Rhythms, Answering the call of a creative God*, Amena Brown uses a conversational style storytelling (much like Donald Miller) to draw life lessons from experiences, centered around life rhythms.[\[16\]](#_ftn16) The essence of the book is in the title, humans enjoy routines, predictability, comfort, and convenience and a life with God is often none of those things.[\[17\]](#_ftn17) God will stretch you in ways that build your character. He gives rest between seasons, but he always returns pressing into growth. We are being conformed to the image of his dear son.[\[18\]](#_ftn18) The change begins as a mild irritation, barely noticeable. It grows into a full-blown crisis of faith. God steps into your life, breaking up your rhythms, pushing for change. In the end, he connects your seemingly disparate life events into a story and weaves it into His larger narrative affecting others in the process.[\[19\]](#_ftn19) I think the key takeaway from this book, for my life today, is this: ***Get used to uncomfortable***. God is more interested in my character than he is my comfort. The more I learn to lean-in to the hard things (like messy emotions), the more connected I will be to His heart and the more he can use me to bring his healing to others.

Leaning-in to radical authenticity and stepping outside my comfort zone to follow God to the lost and hurting will require I be willing to allow Him to break my rhythms. If I am going to follow this unpredictable YHWH-God, I will have to heed the warning of Narnia: He is not a tame or safe God, but he is a good God and a good king.[\[20\]](#_ftn20)

*Practice Session Takeaways:* If I had my druthers, I would sit alone in my room for the rest of my life. I would read, study, eat, binge Netflix, and write, and write, and write. I would go back to my career as a Technical Writer and forget this ministry stuff. After Jesus died, rose again, and was no longer their daily companion, Peter and the boys had a "now what" moment. Reading between the lines, Peter may have thought to himself, "*that was a much crazier adventure than I planned. Rewarding, but it cost me. I think I'll just go back to doing what I do best."* He said to the boys, "I'm going fishing". They said, "We'll come with you". They caught nothing, as often happens when we return to what used to feed us before God instigated The Change. Eventually, Jesus appeared to them, fed them fish they were not catching, and had a locker room chat with Peter. [\[21\]](#_ftn21)

Like Peter, I have been through several crushing and life altering experiences, ending in the death of someone I loved, and the dreams I had with them. Like Peter, I have tried to return to my nets and boats (in my case, Technical Writing in Corporate America). Like Peter, I found that as much as I wanted to return to my previous life, I was supernaturally barred from entry. God has closed that door to me, my nets keep coming up empty. Like Peter, Jesus has been having a locker room chat with me over the past few weeks.

The thing I need most, is to leave my room and take what I obtained in my secret place and deliver it to others. I can bring them a nonjudgmental ear, real help that took me a long time to learn, and a practical theology that bears the weight of sin, sickness, demons, and fear. I am no Sunday morning cheer leader, I am the guy who sits with people in "the suck", in the hard stuff. This requires I leave my safe quiet room. My YHWH is calling, as to Peter, "Feed my sheep".

### Bibliography

Brown, Amena. *Breaking Old Rhythms: Answering the Call of a Creative God*. Downers Grove, Illinois: InterVarsity Press, 2013.

Coulter, Leah. "The Spirit-Formed Life (BIBM1301)." Coursework, The King's University, Southlake Texas, 2021.

Hayford, Jack W. *Living the Spirit-Formed Life: Growing in the 10 Principles of Spirit-Filled Discipleship*. Revised edition. Minneapolis, Minnesota: Chosen, a division of Baker Publishing Group, 2017.

Lewis, C. S, and Pauline Baynes. *The Chronicles of Narnia*. New York: Harper Trophy, 2000.

Miller, Donald. *Blue like Jazz: Nonreligious Thoughts on Christian Spirituality*. Nashville: T. Nelson, 2003.

---------. *Scary Close: Dropping the Act and Finding True Intimacy*. Nashville, Tennessee: Nelson Books, 2014.

*NET Bible®New English Translation (NET)*. Online Notes Edition. HarperCollins Christian Publishing; Biblical Studies Press, L.L.C. Accessed January 21, 2021. https://netbible.com/copyright/.

#### Notes

------------------------------------------------------------------------

------------------------------------------------------------------------

[\[1\]](#_ftnref1) Jack W. Hayford, *Living the Spirit-Formed Life: Growing in the 10 Principles of Spirit-Filled Discipleship*, Revised edition (Minneapolis, Minnesota: Chosen, a division of Baker Publishing Group, 2017).

[\[2\]](#_ftnref2) Hayford, 39--40.

[\[3\]](#_ftnref3) Hayford, 57--59.

[\[4\]](#_ftnref4) Hayford, 67.

[\[5\]](#_ftnref5) Hayford, 73--75.

[\[6\]](#_ftnref6) Hayford, 76--84.

[\[7\]](#_ftnref7) Hayford, 87--101.

[\[8\]](#_ftnref8) Hayford, 115.

[\[9\]](#_ftnref9) Hayford, 120.

[\[10\]](#_ftnref10) Hayford, 143--47.

[\[11\]](#_ftnref11) Hayford, 166--67.

[\[12\]](#_ftnref12) Hayford, 183 (quote edited for brevity).

[\[13\]](#_ftnref13) Hayford, 205--6.

[\[14\]](#_ftnref14) Leah Coulter, "The Spirit-Formed Life (BIBM1301)" (Coursework, The King's University, Southlake Texas, 2021), Assignment: Practice Session Prompts.

[\[15\]](#_ftnref15) Hayford, *Living the Spirit-Formed Life*, 31.

[\[16\]](#_ftnref16) Amena Brown, *Breaking Old Rhythms: Answering the Call of a Creative God* (Downers Grove, Illinois: InterVarsity Press, 2013); Donald Miller, *Blue like Jazz: Nonreligious Thoughts on Christian Spirituality* (Nashville: T. Nelson, 2003); Donald Miller, *Scary Close: Dropping the Act and Finding True Intimacy* (Nashville, Tennessee: Nelson Books, 2014).

[\[17\]](#_ftnref17) Brown, *Breaking Old Rhythms*, 99.

[\[18\]](#_ftnref18) *NET Bible®New English Translation (NET)*, Online Notes Edition (HarperCollins Christian Publishing; Biblical Studies Press, L.L.C.), Romans 8:29; Ephesians 4:11-16, accessed January 21, 2021, https://netbible.com/copyright/.

[\[19\]](#_ftnref19) Brown, *Breaking Old Rhythms*, 22--23, 43, 56.

[\[20\]](#_ftnref20) C. S Lewis and Pauline Baynes, *The Chronicles of Narnia* (New York: Harper Trophy, 2000), (Paraphrase, Luci's conversation).

[\[21\]](#_ftnref21) *NET Bible®*, John 21.
