---
title: 'Class Assignment: Genre Analysis: Wisdom Literature and Prophetic Literature'
date: '2021-11-13T05:23:00.0000000+00:00'
draft: false
categories:
  - 'Studies'
  - 'Class Assignment'
  - 'Biblical Studies'
  - 'Armchair Theology'
---
### Genre Analysis: Wisdom Literature and Prophetic Literature

The King's University, Southlake, Texas

Biblical Background and Interpretation (2021FA-BIBL-2301-ONL)

Professor: Dr. J. Wallace

10/24/2021

By Darrell Wolfe

#### Wisdom Literature and Prophetic Literature

Modern readers of the Bible tend to treat it as a rulebook. Every story is read as an example, which means the reader should be like that character. Every law is treated as something the reader may need believe or do today. Thus, when they come to a passage about wearing tassels, or not wearing mixed cloth, the reader may become confused, asking if this is something that must be obeyed in the modern era.

In his podcast series on Wisdom Literature, Tim Mackie, PhD makes the case that the entire Bible (even the New Testament, written in Greek by Hebrew minds) should be read as Hebrew Wisdom Literature.[\[1\]](https://draft.blogger.com/#_ftn1) Every story, narrative, genealogy, parable, and poem is intended to be pondered over a cup of tea and a pipe, murmuring the words to oneself as one ponders the deeper meanings of a passage, pulling on the threads, and looking for design patterns. When read this way, the Bible ceases to become a book of Do's and Don'ts. Instead, it becomes an opportunity to reflect on the themes and threads, finding principles to live by in our modern era. Nowhere is this truer than in the Wisdom books themselves. Witherington summarizes this way:

> "Wisdom literature then requires not merely reading but rumination. It is meat to tease the mind into active thought, not merely command or demand assent to some particular point of view."[\[2\]](https://draft.blogger.com/#_ftn2)

[](https://draft.blogger.com/#_ftn2)
One genre within the Hebrew Bible that requires special attention, is Prophetic Literature. The Prophet should be seen as a truth-teller, not a future-teller.[\[3\]](https://draft.blogger.com/#_ftn3) Prophets were called to speak God's mind and heart to the people of Israel under covenant with YHWH. They often use poetic and figurative language to paint word images for the people, compelling not just their minds but their hearts back to the covenant. Duvall and Hays observe that Amos does not say "God is mad" but rather "the lion has roared" (Amos 3:8).[\[4\]](https://draft.blogger.com/#_ftn4) These figurative ways of speaking open the heart to hear the real message.

Often, these words from God were for the present situation, bringing the people into remembrance of all that YHWH has said and done for them/to them already. In some instances, these words involve impending judgement (typically in the near future). In very rare instances, these prophetic words involve some far future event, and even rarer still are those words intended to be for the "end of the age" or final "Day of YHWH". Fee and Stuart state: "less than 1 percent concerns events yet to come in our time".[\[5\]](https://draft.blogger.com/#_ftn5) These messages equip one to hear the voice of God then and there, and still ring true today.

#### Bibliography

Duvall, J. Scott, J. Daniel Hays, and Mark L. Strauss and Kevin J Vanhoozer. Grasping God's Word, Fourth Edition: A Hands-On Approach to Reading, Interpreting, and Applying the Bible, 2020.

Fee, Gordon D., and Douglas K. Stuart. How to Read the Bible for All Its Worth. 3rd ed. Grand Rapids, Mich: Zondervan, 2003.

Mackie, Tim, and Jon Collins. "BibleProjectTM Videos and Podcasts." Accessed June 18, 2021. https://bibleproject.com/.

Witherington, Ben. Reading and Understanding the Bible. Oxford ; New York: Oxford University Press USA, 2015.

#### Notes

[\[1\]](https://draft.blogger.com/#_ftnref1) Tim Mackie and Jon Collins, "BibleProjectTM Videos and Podcasts," *https://bibleproject.com/podcast/series/wisdom-series/*, accessed June 18, 2021, https://bibleproject.com/.

[\[2\]](https://draft.blogger.com/#_ftnref2) Ben Witherington, Reading and Understanding the Bible (Oxford ; New York: Oxford University Press USA, 2015), 40.

[\[3\]](https://draft.blogger.com/#_ftnref3) Witherington, 46.

[\[4\]](https://draft.blogger.com/#_ftnref4) J. Scott Duvall, J. Daniel Hays, and Mark L. Strauss and Kevin J Vanhoozer, Grasping God's Word, Fourth Edition: A Hands-On Approach to Reading, Interpreting, and Applying the Bible, 2020, 438.

[\[5\]](https://draft.blogger.com/#_ftnref5) Gordon D. Fee and Douglas K. Stuart, How to Read the Bible for All Its Worth, 3rd ed (Grand Rapids, Mich: Zondervan, 2003), 182.
