---
title: 'Class Assignment: Literary Devices & Figures of Speech'
date: '2021-11-13T05:17:00.0010000+00:00'
draft: false
categories:
  - 'Studies'
  - 'Class Assignment'
  - 'Biblical Studies'
  - 'Armchair Theology'
---
### Literary Devices & Figures of Speech

The King's University, Southlake, Texas

Biblical Background and Interpretation (2021FA-BIBL-2301-ONL)

Professor: Dr. J. Wallace

09/19/2021

By Darrell Wolfe

*
*Note: I did this months ago, I do not recall where the definitions came from. It may have been a text or it may have been Google. If they deserve and attribution, please let me know. The definitions were not part of the original assignment, they were provided for my readers.*

#### Matching Terms to Verses

**Anthropomorphism** - the attribution of human characteristics or behavior to a god, animal, or object

-"You have a strong arm \[O LORD\]; Your hand is mighty, Your right hand is exalted." (Ps. 89:13)

**Litotes** - ironic understatement in which an affirmative is expressed by the negative of its contrary (e.g., you won't be sorry, meaning you'll be glad ).

 - I will multiply them, and they shall not be few; I will make them honored, and they shall not be small." (Jer. 30:19b)

**Metonymy** - the substitution of the name of an attribute or adjunct for that of the thing meant, for example suit for business executive, or the track for horse racing.

\- "The tongue of the wise person brings healing." (Prov. 12:18b)

**Euphemism** - a mild or indirect word or expression substituted for one considered to be too harsh or blunt when referring to something unpleasant or embarrassing.

\- "Thus says the Lord, 'Though they are at full strength and many, they will be cut down and pass away.'" (Nah. 1:12a)

**Apostrophe** - As a literary device, apostrophe refers to a speech or address to a person who is not present or to a personified object, such as Yorick's skull in Hamlet. It comes from the Greek word apostrephein which means "to turn away."

\- "O death, where is your victory? O death, where is your sting?" (1Cor. 15:55)

**Pleonasm** - A pleonasm is when one uses too many words to express a message. A pleonasm can either be a mistake or a tool for emphasis. Pleonasm (pronounced ˈplē-ə-ˌna-zəm) is derived from the Greek phrase pleonasmos meaning "excessive."

\- "For I do not do the good I want, but the evil I do not want is what I keep on doing. Now if I do what I do not want, it is no longer I who do it, but sin that dwells within me." (Rom. 7:19-20)

**Aphorism** - Aphorism is a short statement expressing general truths or opinions. Aphorisms are often applied to matters of philosophical, moral, and literary principles, usually using metaphors and other creative imagery.

\- "Whatever you sow, you will also reap." (Gal. 6:7)

**Simile** - A simile is a figure of speech and type of metaphor that compares two different things using the words "like" or "as." The purpose of a simile is to help describe one thing by comparing it to another thing that is perhaps seemingly unrelated.

\- "Come now, let us reason together, says the Lord: though your sins are like scarlet, they shall be as white as snow; though they are red like crimson, they shall become like wool." (Isa. 1:18)

**Hyperbole** - Hyperbole is a rhetorical and literary technique where an author or speaker intentionally uses exaggeration and overstatement for emphasis and effect.

\- "Again I tell you, it is easier for a camel to go through the eye of a needle than for a rich person to enter the kingdom of God." (Matt. 19:24)

**Rhetorical question** - A rhetorical question is asked just for effect, or to lay emphasis on some point being discussed, when no real answer is expected. A rhetorical question may have an obvious answer, but the questioner asks it to lay emphasis to the point. \... Such a question is used to emphasize a point or draw the audience's attention.

\- "Is anything too hard for the Lord?" (Gen. 18:14)
