---
title: 'Class Assignment: Hermeneutical Terms'
date: '2021-11-13T05:11:00.0060000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6291158416987894083'
blogger_filename: '/2021/11/class-assignment-hermeneutical-terms.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'Class Assignment'
  - 'Biblical Studies'
  - 'Armchair Theology'
---

 <h3 style="text-align: left;">Hermeneutical Terms </h3><p>&nbsp;</p><p>The King’s University, Southlake, Texas <br /><br />Biblical Background and Interpretation (2021FA-BIBL-2301-ONL) <br /><br />Professor: Dr. J. Wallace <br /><br />By Darrell Wolfe <br /> <br /><br />According to the Stein Handout "Defining the Rules,"<a href="https://draft.blogger.com/#_ftn1">[1]</a> the following definitions are provided. <br /><br /></p><h4 style="text-align: left;">1.       How does Stein define "Meaning" </h4><p style="text-align: left;"><br />a.       Stein refers to the “pattern of meaning” the author encodes into the text for the reader to then decode and understand. He juxtaposes this with “Implication”. <br /><br /></p><h4 style="text-align: left;">2.       How does he define "Implication"? </h4><p style="text-align: left;"><br />a.       While the “implication” of a text can go beyond the author’s original body of knowledge or experience and be applied to the present day, it must still follow the original pattern. Inferring an implication that does not follow the pattern is an invalid “implication”. <br /><br /></p><h4 style="text-align: left;">3.       What is meant by the term "Significance"? </h4><p style="text-align: left;"><br />a.       Essentially: “How does this change my life?” While there can be only one “meaning” and a pattern that indicates a limited number of “implications”; the “significance” can be multifaceted based on the contexts of the reader. The significance to a modern Christian in the USA will be different than the first century Jewish audience. But, the significance cannot be outside the pattern set in the meaning and its original implications. <br /><br /></p><h4 style="text-align: left;">4.       What is "Subject Matter"? </h4><p style="text-align: left;"><br />a.       The subject matter refers to the “content” or “stuff” the words are being used to speak about. Content can refer to a historical event, poetry, geography of the region (mentions of mountains or cities), grammar, commentary on contemporary traditions and customs and social norms, or a host of other materials. However, none of this has to do with “meaning”. Meaning, then, is derived from how the author uses the content to drive meaning. One could speak of Genesis 1-3 in terms of world creation, ancient traditions, polemics against literary contemporaries (like Enuma Elis), authorship dates, events surrounding the author’s life and times; however, these are not meaning. They may; however, inform the context of the content and what the author is driving toward which may impact meaning. <br /><br /></p><h4 style="text-align: left;">5.       How does he define "Understanding"? </h4><p style="text-align: left;"><br />a.       The author has a meaning, it is finite and definite. The author means what they mean. The reader is said to understand the text when they have grasped the author’s meaning. Some may have more grasp of the finer details than others; however, all should arrive to the same basic “understanding” of the meaning of the text. <br /><br /></p><h4 style="text-align: left;">6.       What is meant by the term "Interpretation"? </h4><p style="text-align: left;"><br />a.       To interpret something is to explain the understanding in ones own words, using whatever images and metaphors come to mind. While understanding should be singular, “interpretation” can take on a variety of colors and explanations. It can be found in phrases such as “Another way of saying this…” or “Another example is..” or “Perhaps a better way of saying this would be…” When Jesus taught about the Kingdom of God, he used many metaphors, and each was a way of interpreting the Kingdom for his audience. <br /><br /></p><h4 style="text-align: left;">7.       What are "Mental Acts?" </h4><p style="text-align: left;"><br />a.       Mental Acts refers to the variety of thoughts and thought processes the author experienced while writing the text. Some examples of these might be that while he was writing this paper, he was also thinking of when the food would be done and if his 14-year old would be okay by himself for a few hours if he want out for the evening, and what groceries and chores, and oh yeah the homework… Nobody could ever hope to know what processes were going through the mind of an author and they do not matter. What matters is the text the author left us. If the author provided some explanation, so be it. However, the text should be sufficient to provide us some idea of the “meaning” so we can gain “understanding”. <br /><br /></p><h4 style="text-align: left;">8.       What is the difference between "Norms of Language" versus "Norms of Utterance"? </h4><p style="text-align: left;"><br />a.       A single word can mean many things. The word “excel” can refer to a person who is outstanding in his field of expertise, or it can refer to Microsoft Excel the computer program. One would need to see the “literary context” (words around it) to infer which meaning is intended. Or, if both meanings were intended for emphasis or pun. As in, “That farmer is out standing in his field”. While one can look up a Strong’s number and see a list of English definitions possible for a single word, this does not mean that any of those fits just as well as another and the reader can choose whichever one fits their pet theory. The words have meaning in context. One needs to know something about those words before one can determine which options fit best within the literary context. <br /><br /></p><h4 style="text-align: left;">9.       How does Stein define "Literary Genre"? </h4><p style="text-align: left;"><br />a.       Literary Genre refers to forms of literature (writing) that work together to form conventions of use. Examples of Genre can be (but are not limited to) Poetry, Prose, Narrative, Letters, Ancient Near Eastern Apocalypses, and more. Each of these comes with an expectation of the genre, and the author may be intentionally following or breaking from those expectations. One must know the forms to see when they are being followed or diverted from. <br /><br /></p><h4 style="text-align: left;">10.   What is meant by the term "Context"? </h4><p style="text-align: left;"><br />a.       Words, sentences, and paragraphs are simply symbols that represent sounds in a given language. These symbols take on no specific “meaning” on their own. Even strung to together by a computer algorithm, they can sound grammatically correct but meaningless. However, the author can string them together in such a way as to pack them with his or her meaning. When an author fills these with their meaning by including in them explanations, similes, metaphors, comparisons, and explanations, they begin to take on a patter unto themselves. Language is quite fascinating in that similar words could be used to say something vastly different while different words could be used to say something quite similar. It is the meaning, the patterns of meaning and thought, conveyed in these otherwise arbitrary symbols that provide the context for “understanding”. So, it is not enough to simply understand the dictionary definitions of the words before and after a troublesome passage. One must delve further by unpacking the symbols and patterns of thought themselves, attempting even to explain in their own words, until finally one finds they have a grasp of the “meaning” hidden in the “context” of the passages. <br /><br />  <br /> <br /></p><h4 style="text-align: left;"> Notes</h4><p style="text-align: left;"><br /><a href="https://draft.blogger.com/#_ftnref1">[1]</a> Robert H. Stein and Robert H. Stein, A Basic Guide to Interpreting the Bible: Playing by the Rules, 2nd ed (Grand Rapids, Mich: Baker Academic, 2011), Chapter 2: Defining the Rules: A Vocabulary for Interpretation. <br /> <br /> <br /> <br /> <br /> Subscribe Now - Pursue a No Hiding Lifestyle <br /><br /><br /> <br /> <br /> <br /> Shalom: Live Long and Prosper!<br /> <br /> Darrell Wolfe (DG Wolfe) <br /> Storyteller | Writer | Thinker | Consultant @ <a href="https://draft.blogger.com/#">DarrellWolfe.com</a><br /> <br /> <a href="https://draft.blogger.com/#">Clifton StrengthsFinder</a>: Intellection, Learner, Ideation, Achiever, Input<br /> <a href="https://draft.blogger.com/#">16Personalities</a> (Myers-Briggs Type): INFJ<br /> <br /> <br /> </p>