---
title: 'Hosea, Final Prophet to Northern Israel Forum 5-2, Group 8 Discussion Post'
date: '2021-02-11T01:50:00.0000000+00:00'
draft: false
categories:
  - 'Musings'
  - 'Studies'
---

<i>*Saunders, Dr. Eugene. “Old Testament Survey (BIBL1305).” Coursework, The King’s University, Southlake Texas, 2021.  </i><br /> <br />  <br /><h3 style="text-align: left;">FORUM 2: PROPHETS OF ISRAEL AND JUDAH </h3><br /><i>What is the background of Hosea’s prophetic ministry to Israel? Discuss Hosea's purpose and message. Be sure to read this section and understand it for discussion. Assigned to: Group 8 </i><br /><br />  <br /><h4 style="text-align: left;">Hosea, Final Prophet to Northern Israel Forum 5-2, Group 8 </h4><p><br />As a result of Israel’s failure to conquer the whole land after Joshua, they chose to co-dwell and co-mingle with the Canaanites; the people of Israel/Judah eventually blended societies (even intermarrying). Israel then failed to trust YHWH to bring rain on the land, so they chose to co-mingle religious affiliations. By the time of the divided kingdoms, Northern Israel partially still worshiped YHWH (religiously) but they also worshiped Baal (a fertility and agriculture god). Baal worship involved human sacrifices and temple prostitutes (paid workers at the temple). One would worship Baal by having sex with the temple prostitute and assisting Baal in his fight against the god Mot to keep the agricultural cycles going.<a href="https://draft.blogger.com/#_ftn1">[1]</a> <br /><br />Onto this scene, arrives Hosea. His ministry begins when YHWH tells him to take a (temple) prostitute as a wife.<a href="https://draft.blogger.com/#_ftn2">[2]</a> Their first son was named Jezreel (God Sows), indicating that Israel would soon reap what they sowed.<a href="https://draft.blogger.com/#_ftn3">[3]</a> Their second child, a girl, was named Lo-ruhamah (no pity), for God will no longer have pity on Israel.<a href="https://draft.blogger.com/#_ftn4">[4]</a> Their third child was named Lo-Ammi (not my people), for God was rejecting them and turning them over to foreign gods/nations; just as he had done to Babel centuries before.<a href="https://draft.blogger.com/#_ftn5">[5]</a> <br /><br />Hosea prophesies to the kingdom of Northern Israel, saying they have “deeply corrupted themselves”.<a href="https://draft.blogger.com/#_ftn6">[6]</a> The prophetic-poetic words are the heart’s cry of a man who is begging his lover to return to him in one breath, and condemning her faithlessness in the next. Back and forth it goes. I once read a short story of a woman who’s husband betrayed her, it read much like this. A yearning for the partner, and a painful rejection of the hurt caused by them. <br /><br />As Hosea’s wife worked in the temple, having sex with people as a ritual act for Baal; Israel was engaged in spiritual and actual adultery against their covenant with YWHW. This would be the final prophetic plea for their repentance. Hosea is sometimes called the “death-bed prophet of Israel”; as his was the final curtain call before YHWH would wipe the kingdom of Northern Israel off the map.<a href="https://draft.blogger.com/#_ftn7">[7]</a> By 724-722 BC, Assyria would divide the land of Northern Israel into it’s own royal provinces. The land would never be fully under Israel’s control again.<a href="https://draft.blogger.com/#_ftn8">[8]</a> To this day the modern borders of the rebirthed nation, The State of Israel, are shared (co-mingled) with another nation (Palestinian Authority).<a href="https://draft.blogger.com/#_ftn9">[9]</a> <br /></p><p><br /> </p><p><i>PS: Child Sacrifice and Worship of Open-Sexuality... what does that remind me of in the 21st Century? </i><br /></p><div style="text-align: center;">&nbsp;</div><div style="text-align: center;">-------------------</div><div style="text-align: center;"><br /></div><div><br /><a href="https://draft.blogger.com/#_ftnref1">[1]</a> Hill and Walton, A Survey of the Old Testament, 589. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref2">[2]</a> The Lexham English Bible (LEB), Fourth Edition, Logo Bible Software, Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., &amp; Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010), Hosea 1:2-3, http://www.lexhampress.com. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref3">[3]</a> LEB, Hs 1:4. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref4">[4]</a> LEB, Hs 1:6. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref5">[5]</a> LEB, Hs 1:8-9. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref6">[6]</a> LEB, Hs 9:9. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref7">[7]</a> Hill and Walton, A Survey of the Old Testament, 586. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref8">[8]</a> Hill and Walton, See map, pp 287, (The Two Kingdoms 930-772 BC). <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref9">[9]</a> “Israel Maps &amp; Facts,” WorldAtlas, accessed February 10, 2021, https://www.worldatlas.com/maps/israel. <br /> <br /></div><div style="text-align: center;"> -------------------<br /></div><div> <br />
<br />
<br />
<br />
<div id="mc_embed_signup" style="text-align: left;">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<div class="fx-relay-email-input-wrapper"><input class="email" id="mce-EMAIL" name="EMAIL" required="" style="padding-right: 30px;" type="email" value="" /><div class="fx-relay-icon" style="bottom: 0px; right: 2px; top: 0px;"><button class="fx-relay-button" id="fx-relay-button" style="height: 24px; min-width: 24px; width: 24px;" title="Generate new alias" type="button"></button></div></div><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal" style="text-align: left;">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal" style="text-align: left;">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
</div>