---
title: 'Class Assignment: The Need for & Goals of Biblical Interpretation'
date: '2021-11-12T16:14:00.0020000+00:00'
draft: false
categories:
  - 'Studies'
  - 'Class Assignment'
  - 'Biblical Studies'
  - 'Armchair Theology'
---

<!--StartFragment-->

<p align="center" class="MsoNormal">
</p><div style="text-align: left;"><div id="ftn8">

</div>

</div>

<!--EndFragment--><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><h3 style="text-align: left;">The Need for &amp; Goals of Biblical Interpretation </h3><br />The King’s University, Southlake, Texas <br /><br />Biblical Background and Interpretation (2021FA-BIBL-2301-ONL) <br /><br />Professor: Dr. J. Wallace <br /><br />September 5, 2021 <br /><br />  By Darrell Wolfe <br /> <br /><br />  <h4 style="text-align: left;">The need for biblical interpretation </h4><br />As the story goes, a woman once asked her pastor to convince her husband it was God’s will that she leave him. The woman explained “I met a man at work. Torn, I was praying about what to do, flipped open my Bible, and read, ‘put on the new man’, so I did.” <a href="https://draft.blogger.com/#_ftn1">[1]</a> This is a person who did not understand what the Bible is or how to use it. As a basic function of reading a written text, there is an idea, concept, or message the author intends to communicate. The reader has an obligation to “receive everything the writer intended.”<a href="https://draft.blogger.com/#_ftn2">[2]</a> At some level all reading is interpretation. Whether one reads a meme on Facebook, a recipe, a historical novel, or a comic book, the act of reading (and that of listening) is to understand the information being presented. However, as any married couple will tell you, the words presented are not always received as intended. The reader/hearer has a role to play in making sure they understand what is being presented by the writer/speaker. <br /><br />            When we come to the Bible, we find that scripture is a collection of texts composed by an unknown number of authors and editors (40+) over an unclear number of centuries (1,500 years give or take depending on how you date the Exodus), all written in at least three different ancient languages on the other side of the world from many English-speaking Bible readers. They wrote from a variety of contexts, personalities, and writing styles.<a href="https://draft.blogger.com/#_ftn3">[3]</a> As rule, the very act of reading the Bible in English is already reading someone’s interpretation of these texts.<a href="https://draft.blogger.com/#_ftn4">[4]</a> Because these texts come from a real time, place, and people, we must honor the contexts that gave them to us. But “the past is a foreign country; they do things differently there.”<a href="https://draft.blogger.com/#_ftn5">[5]</a> <br /><br />  <br /><h4 style="text-align: left;">The goals of interpreting Scripture </h4><p><br />While one may recognize the “eternal relevance” of the texts as God’s Words; we also find a “tension” between their relevance and their “historical particularity.”<a href="https://draft.blogger.com/#_ftn6">[6]</a> So how do we get from here to there? Two academic terms for interpreting scripture are exegesis and hermeneutics. “Exegesis is the careful, systematic study of the Scripture to discover the original, intended meaning.”<a href="https://draft.blogger.com/#_ftn7">[7]</a> While hermeneutics can refer to the entire interpretive process (including exegesis); it is often understood as the method by which one applies scripture to modern life. In essence, exegesis can be understood as the “then and there”, while hermeneutics could be understood as the “here and now”.<a href="https://draft.blogger.com/#_ftn8">[8]</a> The only way to ensure you are applying the texts accurately in the “here and now” is to ensure you understand what was being said in the “then and there”.<a href="https://draft.blogger.com/#_ftn9">[9]</a> <br /><br />            In order to accomplish the task of understanding the “then and there” one must have the ancient Israelite in their head. To do this, we study the literature and history of the Ancient Near East (ANE) and Second Temple periods, which comprise the contexts of the biblical authors. Whatever tools we use to accomplish this, the goal is preventing a reading of any passage, word, phrase, or concept that is foreign to the text or author. In other words, “A text cannot mean what it never meant.”<a href="https://draft.blogger.com/#_ftn10">[10]</a> <br /><br />Often, theological debates arise and whole systems are built on a fundamental misreading of these texts. These misappropriations can be avoided by paying careful attention to the original contexts from which we derive the words we find in English (or any other) translation. The plain words on the page in our native language have already undergone a series of translation choices before arriving. Language carries concepts (a matrix of ideas) and translation often imperfectly carries those concepts into another language. It is our responsibility as readers to make sure we know what is being said before applying that wisdom in a modern context.</p><p><br /> <br /></p><h4>Bibliography </h4><p><br />  Adler, Mortimer Jerome, and Charles Van Doren. How to Read a Book. Rev. and Updated ed. New York: Simon and Schuster, 1972. <br /><br />“Attribution Unknown,” n.d. <br /><br />Duvall, J. Scott, J. Daniel Hays, and Mark L. Strauss and Kevin J Vanhoozer. Grasping God’s Word, Fourth Edition: A Hands-On Approach to Reading, Interpreting, and Applying the Bible, 2020. <br /><br />Fee, Gordon D., and Douglas K. Stuart. How to Read the Bible for All Its Worth. 3rd ed. Grand Rapids, Mich: Zondervan, 2003. <br /><br />Hartley, Leslie Poles, and L.P. Hartley. The Go-Between. Hamish Hamilton, 1953. <br /><br />Wallace, Jeremy. “Biblical Background and Interpretation (BIBL301).” The King’s University, Southlake Texas, Fall 2021. <br /><br />  </p><h4 style="text-align: left;">Notes</h4><p style="text-align: left;"> <br /><a href="https://draft.blogger.com/#_ftnref1">[1]</a> “Attribution Unknown,” n.d., Ephesians 2:24-Original attribution for this story is unknown, I’ve heard it from countless pastors since at least the mid-1990’s. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref2">[2]</a> Mortimer Jerome Adler and Charles Van Doren, How to Read a Book, Rev. and updated ed (New York: Simon and Schuster, 1972), 7. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref3">[3]</a> J. Scott Duvall, J. Daniel Hays, and Mark L. Strauss and Kevin J Vanhoozer, Grasping God’s Word, Fourth Edition: A Hands-On Approach to Reading, Interpreting, and Applying the Bible, 2020, 5. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref4">[4]</a> Jeremy Wallace, “Biblical Background and Interpretation (BIBL301)” (The King’s University, Southlake Texas, Fall 2021), Lecture: NeedAndGoalsOfInterpretationPartOne. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref5">[5]</a> Leslie Poles Hartley and L.P. Hartley, The Go-Between (Hamish Hamilton, 1953), *Note: I first heard this quoted by New Testament scholar NT Wright. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref6">[6]</a> Gordon D. Fee and Douglas K. Stuart, How to Read the Bible for All Its Worth, 3rd ed (Grand Rapids, Mich: Zondervan, 2003), 21. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref7">[7]</a> Fee and Stuart, 23. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref8">[8]</a> Fee and Stuart, 23. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref9">[9]</a> Fee and Stuart, The Second Task: Hermeneutics. <br /> <br /><br /><a href="https://draft.blogger.com/#_ftnref10">[10]</a> Fee and Stuart, 30.</p><div style="text-align: left;"><br /></div><div style="text-align: left;">Darrell Wolfe<br /></div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div><div style="text-align: left;">
</div>
