---
title: 'Class Assignment: Obadiah: A structural outline, commentary, and its ties to Divine Council imagery.'
date: '2021-10-17T04:31:00.0060000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5003857401500159432'
blogger_filename: '/2021/10/obadiah-structural-outline-commentary.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'Class Assignment'
  - 'Biblical Studies'
  - 'Armchair Theology'
---

<div><br /> <br /></div><div style="text-align: center;"><h2><b>Structural Outline: Obadiah </b></h2><br /> The King’s University, Southlake, Texas <br /><br />Biblical Background and Interpretation (2021FA-BIBL-2301-ONL) <br /><br />Professor: Dr. J. Wallace <br /><br />10/17/2021 <br /><br />By Darrell Wolfe <br /></div><div style="text-align: left;"> <br /><br />  <br /><h3>Structural Outline: Obadiah 1:1-21 </h3><br /><i>Note: Obadiah only has one chapter, the entire book is included in 1:1-21. </i><br /><br /><i>Background: Edom is comprised of Esau’s descendants. Esau was Jacob’s (aka Israel) brother, from whom Jacob stole the birthright and blessing. Therefore, the people of Edom are cousins to the people of Israel. There are other details, but this is sufficient to understand the family references in this prophecy. See also Jeremiah’s mirror prophecy against Bozrah, a major city in Edom, using much of the same language as Obadiah (Jeremiah 49:7-22). </i><br /><br /><ul style="text-align: left;"><li>I.        Introduction: The following is a vision the Prophet Obadiah saw, and the words Adonai YHWH says about Edom (the descendants of Esau) (Ob 1:1a NET).<b>(1)</b> </li><li>II.      YWHW’s judgment of Edom’s arrogance (1b-9). </li><ul><li>A.     The announcement encourages the nations to war against Edom. </li><li>B.      YHWH sends a report via a messenger that he will make war on Edom and make them weak (1b-2). </li><li>C.      He announces the first just-cause he has for this decision, which could read more like the underlying issue that lead to the real offense in III. </li><ul><li>1. They have pride in their heart and became self-deceived, thinking themselves invincible and safe (3). </li><li>2. But YHWH says that there is no place they can go that would be safe from him (not even the stars, a common biblical reference to the fallen Divine Council, members of the fallen Elohim) (4). </li><li>3. He introduces a comparison: If normal calamity struck, they could survive, but since YHWH is performing Judgement, it will result in their total destruction (5). </li><li>4. Their belongings will be taken (6). </li><li>5. The people they partnered with and trusted will be the ones to take them down (7). </li><li>6. The wise and the warriors alike among them will be removed from their stronghold and destroyed (8-9). </li></ul></ul><li>III.   YWHW’s judgment of Edom’s failure to honor family (10-14). </li><ul><li>A.     He announces the second just-cause he has for this decision: </li><ul><li>1. The people of Edom played a role in harming their relatives, resulting in judgment. The offense was bad enough, that YHWH determines it will be a permanent status “forever”. This is an escalation from the language used in section II (10). </li><li>2. Edom is portrayed as sometimes distant and unmoved by Israel’s destruction (as though a passive observer that should have come to her aid) as a foreign invader takes the city, but is then cast as a participant. This is worse than not coming to their aid, but contributing to their harm (11). </li><li>3. Edom is portrayed as “gloating”, “rejoicing”, and “boasting” as their cousins suffered at the hands of enemies (12). </li><li>4. Edom then decides to help the enemies beat up Israel, looting the city (13). </li><li>5. Edom rubs salt in the wound by standing at the fork in the road, killing anyone who escaped (14). </li></ul></ul><li>IV.   YWHW’s judgment expands to include all nations via “The Day of the Lord” (15-21a). </li><ul><li>A.     An unspoken question seems implicit in the following statement. That question: “Why should we care?” </li><li>B.      The answer to the unspoken question: </li><ul><li>1. “For the Day of the Lord is approaching for all nations”. There is judgment coming not just to one nation, not just for these actions, all nations are going to stand before YHWH and be judged. In light of this pending end-times judgment, Edom should have known better and done better. Pulling on that ultimate Day of the Lord motif, Obadiah/YHWH lay into Edom’s impending judgment in the here and now. What was done by Edom, will be repaid in full (15). </li><li>2. YHWH/Obadiah uses a metaphor about drinking on the holy mountain (16). </li><ul><li>a.       Given the context, it could be that drinking here refers to the idea that Edom drank from victory and now will drink from YWHW’s cup of wrath.<b>(2)</b> In the “now and not yet” fashion of biblical prophetic literature, Edom will suffer a Day of the Lord now, followed later by The Day of the Lord in an age to come. </li><li>b.       It is also relevant that “holy mountain” is yet another core biblical theme referring to God’s Space. Eden is the Garden of God, his Holy Mountain. So too, is Jerusalem. Typically, “the nations” refers to the Table of Nations and the rebel Elohim that rule them. Stars (referenced earlier) are quite often a reference to these fallen Elohim. Given the multiple coded references, “nations”, “stars”, “holy mountain”, and “Day of the Lord”, “the nations” is not likely a generic reference to earth’s inhabitants but a specific reference to these rebel-led nations that often came into conflict with God’s Holy People (Genesis 10-11; Deuteronomy 32:8; Psalms 82, 89). <b>(3)</b> This could be a veiled threat not only to Edom and the nations around them but to the rebel Elohim who rule them and cause chaos. </li></ul><li>3. YWHW brings the final hammer down on his judgment (17-21a). </li><ul><li>a.       In contrast to the utter destruction promised to Edom and the fallen nations (and their Elohim), YHWH promises to restore Israel from the remnant (17). </li><li>b.       He then compares Israel to fire and Edom to left-over yard clippings or food waste that will be burned so completely by Israel that they will cease to exist. Here again, escalating the language a third time, and in contrast to the remnant he promises Israel, Edom is promised to be wiped out so completely, that not a single survivor will be left to create an Edomic remnant (18). </li><li>c.       YHWH concludes by saying that other nations will take Edom’s spot in the mountains (another Divine Council reference as well as physical space reference) and that Israel will return and rule over it all (19-21). </li></ul></ul></ul><li>V.     YWHW announces his kingship (21b).  With one final line, YHWH announces he will be king, and it serves as the punctuation on the whole prophetic word. This, again, has the taste of a threat not only to Edom, not only to “the nations”, but to the Divine Council members who rebelled. YHWH will have the last word, he will be King. </li></ul>&nbsp;</div><div style="text-align: left;">&nbsp;</div><div style="text-align: left;"><h3>Bibliography </h3></div><div style="text-align: left;"><br />  Heiser, Michael. The Unseen Realm: Recovering the Supernatural Worldview of the Bible. First edition. Bellingham, WA: Lexham Press, 2015. <br /><br />NET Bible®New English Translation (NET). Online Notes Edition. HarperCollins Christian Publishing; Biblical Studies Press, L.L.C., n.d. https://netbible.com/copyright/. <br /><br />The NET Bible First Edition Notes. Biblical Studies Press, 2006. <br /><br />  <br /><h3 style="text-align: left;">Notes</h3>(1) NET Bible®New English Translation (NET), Online Notes Edition (HarperCollins Christian Publishing; Biblical Studies Press, L.L.C., n.d.), Obadiah, https://netbible.com/copyright/. <br /> <br />(2) The NET Bible First Edition Notes (Biblical Studies Press, 2006), Notes for 1:16-#79. <br /> </div><div style="text-align: left;">&nbsp;</div><div style="text-align: left;">(3) Michael Heiser, The Unseen Realm: Recovering the Supernatural Worldview of the Bible, First edition (Bellingham, WA: Lexham Press, 2015), *See the work(s) of Dr Heiser for more details on these themes.*. <br /> <br /> <br /> <br /> <br /> <br /> <br /> Subscribe Now - Pursue a No Hiding Lifestyle <br /><br /><br /> <br /> <br /> <br /> Shalom: Live Long and Prosper!<br /> <br /> Darrell Wolfe (DG Wolfe) <br /> Storyteller | Writer | Thinker | Consultant @ <a href="https://draft.blogger.com/#">DarrellWolfe.com</a><br /> <br /> <a href="https://draft.blogger.com/#">Clifton StrengthsFinder</a>: Intellection, Learner, Ideation, Achiever, Input<br /> <a href="https://draft.blogger.com/#">16Personalities</a> (Myers-Briggs Type): INFJ<br /> <br /> <br /> </div>