---
title: 'How should we understand Biblical Interpretation?'
date: '2021-10-07T02:42:00.0010000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1384432735156083555'
blogger_filename: '/2021/10/how-should-we-understand-biblical.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'Class Assignment'
  - 'Biblical Studies'
  - 'Armchair Theology'
---

<div>How should we understand Biblical Interpretation?&nbsp;</div><div><br></div><div>Especially as it relates to The Gospels or Salvation.</div><div><br></div><div>While some dispute this, the preponderance of evidence says that: Matthew, Mark, Luke, and John were individuals who each wrote according to their knowledge and ability to gather testimony and witnesses. Matthew and John were eye witnesses. Mark was Peter's interpretor and assistant. Luke was a researcher and associate of Paul.&nbsp;</div><div><br></div><div>The evidence demonstrates the Mark wrote his gospel early, possibly within the mid century. Matthew and Luke each used Mark's version which was already in circulation and added to it as they saw fit using their own experience and other resources and documents to make their own unique theological statements and claims.&nbsp;</div><div><br></div><div>John, writing much later at the end of his life decided to record his theology and biography of Jesus, choosing details not already accounted for in several instances.</div><div><br></div><div>Each author had a theological point to their letter and a reason for choosing and organizing the details they did.&nbsp;</div><div><br></div><div>In each case, you have a representative sampling of the words and interactions of Jesus.&nbsp;</div><div><br></div><div>In no case was a camera following Him around. These are the theological reflective biographical essays presented as the written preservation of oral traditions.</div><div><br></div><div>As to interpretation:</div><div><br></div><div>All scripture is inspired, so, we SHOULD add as much wait to Ruth, Leviticus, and Job as we do Matthew, Mark, Luke, and John... And Paul's letters... And Revelation.&nbsp;</div><div><br></div><div>And we SHOULD allow each to correlate and add interpretive value to the other.&nbsp;</div><div><br></div><div>Also, Jesus and all early Christians like Peter, Paul, etc. used the Hebrew Bible as their primary meditative text.&nbsp;</div><div><br></div><div>The gospels and letters were a supplement for the new covenant, but not a replacement for the Hebrew Bible.&nbsp;</div><div><br></div><div>Christianity, in its purest form, is a Jewish sect, not a Lutheran or Calvanist one.&nbsp;</div><div><br></div><div>The context for biblical interpretation is the context of its authors (Ancient Near East and Second Temple Period). The context is not Augustine, Luther, Calvin, Tyndale, Wesley, or any other thinker that came after. The context is the authors. So anything said after should be screened out and we should do our best to make sure we understand what the author is saying, not what our "Systematic Theology" tells us it says.&nbsp;</div><div><br></div><div>I would go further, and say that anything from the Systemic Theology bucket is basically trash and to throw it all out. Anything from Augustine to Parham, 300s to 1900 AD, just junk it all. That's probably just an overreaction on my part. I tend to take extreme positions and flow back to the middle after pondering it a while. So I reserve the right to say something different tomorrow, but, that's where I stand today.&nbsp;</div><div><br></div><div>That being said, unless you have the ancient Israelite in your head, you'll never understand the Bible and always Eisegete meanings into the text that aren't there (as so many Theologians did between 300-1900 AD.&nbsp;</div><div><br></div><div>Christianity is a Jewish sect. Period. Gentiles are grafted into Israel, not out away from it. If you miss that point, you run in danger of missing all the points. Most of the wrong headed and silly things modern Christianity says about the "Old Testament" (including labeling it the old testament to begin with) are from a lack of having our Jewish roots firmly in tact.&nbsp;</div><div><br></div><div>And yet, as a further overreaction to that truth, the Jewish Roots movement has people becoming Torah Observant in ways Jesus never intended. But, they are often more right than wrong, and I have some common ground with such people. Almost all the things people learn about Judaism and the Hebrew Bible from western American Christianity are wrong. Including, and especially, our understanding of "The Law".&nbsp;</div><div><br></div><div>The Bible Project has done a great job of breaking this down for us and helping people deconstruct these poor understandings.&nbsp;</div><div><br></div><div>Therefore, as a Jewish sect, any and all interpretation should work from Genesis to Revelation first, before working backward from Revelation to Genesis. In other words, the OT gives us understanding of the NT BEFORE the NT gives us understanding of the OT.&nbsp;</div><div><br></div><div>Most of the NT authors, including the gospels, are making heavy use of the OT theology and passages.&nbsp;</div><div><br></div><div>So much more to say, but that's what I'm getting the need to say today.</div>