---
title: 'A short discussion of Zephaniah, Lamentations, and Ezekiel.'
date: '2021-02-21T06:31:00.0010000+00:00'
draft: false
categories:
  - 'Studies'
---
Saunders, Dr. Eugene. "Old Testament Survey (BIBL1305)." Coursework, The King's University, Southlake Texas, 2021.

### Discussion Responses

###  Zephaniah -2: Purpose and Message and from Scripture -- discuss judgment, hope and the remnant -- the judgment of the nations; universal judgment and far reaching effects of current political situations. \-\--Assigned to: Group 8

#### Zephaniah: The Day of the Lord; Judgment, Hope, and Remnant (Group 8)

Zephaniah was a contemporary of Jeremiah and together they were the two prophets would usher in the destruction of Jerusalem by Babylon.[\[1\]](https://draft.blogger.com/#_ftn1) Zephaniah operated during the reign of Josiah (the good boy king) and his prophecies helped Israel denounce wickedness for a season before they returned and were destroyed by it.[\[2\]](https://draft.blogger.com/#_ftn2) The driving force of his message was "The Day of the Lord" or the "Day of YHWH". The Day of YHWH ends up being a thematic prophecy which finds its fulfillment's in several events, like steps leading toward an end.[\[3\]](https://draft.blogger.com/#_ftn3) The Day of YHWH is about reversals. Light is darkness. The first shall be last. "It has political, social, spiritual, and cosmic ramifications".[\[4\]](https://draft.blogger.com/#_ftn4) The Ultimate Day of YHWH may find its day in the Judgement Seat of Christ?

In three short chapters, Zephaniah raises a clarion call to the entire earth. Not only is the nation of Israel dealt with, but all nations are judged.[\[5\]](https://draft.blogger.com/#_ftn5) If one is familiar with the Deuteronomy 32 Worldview (God's Divine Counsel), the phrasing "YHWH... will weaken all the gods of the earth" will ring in their ears.[\[6\]](https://draft.blogger.com/#_ftn6) God will bring every one of the Elohim (gods) that rebelled against him to their knees; judging not only the nations but the rebellious spiritual beings as well (some call demons).

The passages take a sharp turn from Judgement to a new Hope:

> "*Know for sure that I will then enable the nations to give me acceptable praise. All of them will invoke the LORD's name when they pray, and will worship him in unison. From beyond the rivers of Ethiopia, those who pray to me will bring me tribute."[\[7\]](https://draft.blogger.com/#_ftn7)*

[](https://draft.blogger.com/#_ftn7)
It reminds me of the fact the USA sends "foreign aid" to Israel every year. That sounds a lot like a land from beyond the rivers of Ethiopia, full of praying people, that sends Tribute.

The prophet ends with a promise that has yet to be fulfilled. "I will make all the nations of the earth respect and admire you when you see me restore you."[\[8\]](https://draft.blogger.com/#_ftn8) We are living in the "yes but not yet" of scripture. Some of the things came to pass. Judgement was laid on many nations. Several of the nations that caused Israel great trouble no longer exist today, they have become as Sodom and Gomorrah.[\[9\]](https://draft.blogger.com/#_ftn9) But there appears to be a day coming where the entire earth will bow before YHWH; and Jesus hinted of this as well. We look forward to this day, when things are set right.

###  Lamentations: Themes of Human Suffering/ Divine Abandonment. \-\-- Assigned to: Groups 2,4, 6, and 8

#### Lamentations: Themes of Human Suffering and Divine Abandonment (Group 8)

The text posits two sides of the human suffering question. Suffering is inevitable because of the fall; and, that understanding the causes are beyond us because God's ways are bigger than ours.[\[10\]](https://draft.blogger.com/#_ftn10) While Mesopotamian literature showing the gods abandoned the city promoted repentance of their people, the departure of YHWH only further encouraged Judah's rebellion.[\[11\]](https://draft.blogger.com/#_ftn11)

The phrases that stuck out to me from Lamentations were: "Let a person sit alone in silence when the Lord (YHWH) is disciplining him" and "For he (YHWH) is not predisposed to afflict or to grieve people".[\[12\]](https://draft.blogger.com/#_ftn12)

It seems the essence of this Lament is reminiscent of Jesus's words, "Jerusalem... who kills your prophets... how many times I wanted to gather you like a hen gathers her chicks... your house will be left desolate... you will never see me again until you say "blessed is he who comes in the name of the Lord...".[\[13\]](https://draft.blogger.com/#_ftn13) There is this tension between "I wanted you" and "you rejected me"; between "I wanted good things for you" and "now you will get my discipline".

As a father of two teens, this sentiment resonates strongly. I wanted to do good things, but, you refuse to clean your room, you cause trouble for the teacher at school, now I've got to run around trying to handle the messes you make, help you get well, work on healing (psychologically = ADHD+Grief) instead of taking our free time to do better things.

It is a Lament of the prophet that we had better lean-in to the discipline now, so we can move on from this.

A friend's late husband used to say: "In every learning circumstance we have to be broken before we can be rebuilt." She said, "I don't like it, but I see the point."

***Matthew 23:37--39 (LEB): The Lament over Jerusalem***

> 37 "Jerusalem, Jerusalem, who kills the prophets and stones those who are sent to her! How many times I wanted to gather your children together ⌊the way⌋ a hen gathers her young together under her* wings, and you were not willing! 38 Behold, your house has been left to you desolate! 39 For I tell you, you will never see me from now on until you say, 'Blessed is the one who comes in the name of the Lord!' "

***Lamentations 3:28--33 (NET):***

> י *(Yod) 3:28 Let a person sit alone in silence, when the Lord is disciplining him. 3:29 Let him bury his face in the dust; perhaps there is hope. 3:30 Let him offer his cheek to the one who hits him; let him have his fill of insults.*

> *כ (Kaf) 3:31 For the Lord will not reject us forever. 3:32 Though he causes us grief, he then has compassion on us according to the abundance of his loyal kindness. 3:33 For he is not predisposed to afflict or to grieve people.*

###  EZEKIEL'S CHARIOT and TEMPLE VISIONS Ch 1-3 & 40-48 - Chariot Vision- Chapters 1-3: \-\--Assigned to: Group 8 o Temple Vision-Chapters

#### EZEKIEL'S CHARIOT and TEMPLE VISIONS Ch 1-3 & 40-48 (Group 8)

The visions of Ezekiel assured Israel, now in exile, that the covenant promises are still valid if they will serve YHWH and no other God. They also served as potent images for driving home the message that YHWH is big, powerful, and the driving force behind national and international events.[\[14\]](https://draft.blogger.com/#_ftn14)

In the first vision, Ezekiel sees a YHWH figure enthroned on top of creatures built from wheels and multiple faces; all riding inside of a storm.[\[15\]](https://draft.blogger.com/#_ftn15) This figure uses the term "Son of Man", which is a term Jesus used often in his ministry. YHWH first gives him words to eat and then tells Ezekiel that he has built him as stubborn for God as the people of Israel are stubborn against God.[\[16\]](https://draft.blogger.com/#_ftn16) He is then given his assignment as "Watchman" over Israel with the stern warning that he will be guilty for the outcomes of people if he fails to open his mouth and speak what God speaks.[\[17\]](https://draft.blogger.com/#_ftn17)

The second vision focuses on the measurements of the new Jerusalem, which he takes Chapters 40-48 to describe. Mixed in and through the vision of measurements are clues to the way the restored society will be. The theme could be summed up by his final words: "The name of the city from that day forward will be "YHWH ShMMH", "YHWH is There".[\[18\]](https://draft.blogger.com/#_ftn18) The CCE described it this way:

> *"The arrangements as to the land and the temple are, in many particulars, different from those subsisting before the captivity. There are things in it so improbable physically as to preclude a purely literal interpretation."[\[19\]](https://draft.blogger.com/#_ftn19)*

[](https://draft.blogger.com/#_ftn19)
There are similar themes in the New Jerusalem outlined by John in Revelation; where measurements are taken to describe the new city.[\[20\]](https://draft.blogger.com/#_ftn20) So John and Ezekiel are referring to the same event. The final restored planet earth, where God is realized as the King of Earth, reigning from his New Jerusalem.

**Worth a read, ramifications for today:**

> *16 At the end of seven days the word of the LORD came to me: 17 "Son of man, I have appointed you a watchman for the house of Israel. Whenever you hear a word from my mouth, you must give them a warning from me. 18 When I say to the wicked, "You will certainly die," and you do not warn him - you do not speak out to warn the wicked to turn from his wicked deed and wicked lifestyle so that he may live - that wicked person will die for his iniquity, but I will hold you accountable for his death. 19 But as for you, if you warn the wicked and he does not turn from his wicked deed and from his wicked lifestyle, he will die for his iniquity but you will have saved your own life. 20 "When a righteous person turns from his righteousness and commits iniquity, and I set an obstacle before him, he will die. If you have not warned him, he will die for his sin. The righteous deeds he performed will not be considered, but I will hold you accountable for his death. 21 However, if you warn the righteous person not to sin, and he does not sin, he will certainly live because he was warned, and you will have saved your own life."*

Biblical Studies Press, The NET Bible First Edition (Noteless); Bible. English. NET Bible (Noteless). (Biblical Studies Press, 2005), Eze 3:16--21.

------------------------------------------------------------------------

[\[1\]](#_ftnref1) Andrew E. Hill and John H. Walton, *A Survey of the Old Testament*, 3rd ed (Grand Rapids, Mich: Zondervan Publishing House, 2009), 670.

[\[2\]](#_ftnref2) Hill and Walton, 671.

[\[3\]](#_ftnref3) Hill and Walton, 672--73.

[\[4\]](#_ftnref4) Hill and Walton, 673.

[\[5\]](#_ftnref5) *NET Bible®New English Translation (NET)*, Online Notes Edition (HarperCollins Christian Publishing; Biblical Studies Press, L.L.C.), Zephaniah 2, accessed January 21, 2021, https://netbible.com/copyright/.

[\[6\]](#_ftnref6) *NET Bible®*, Zeph 2:11; Dr. Michael S. Heiser, *The Unseen Realm: Recovering the Supernatural Worldview of the Bible*, First edition (Bellingham, WA: Lexham Press, 2015).

[\[7\]](#_ftnref7) *NET Bible®*, Zeph 3:9-10.

[\[8\]](#_ftnref8) *NET Bible®*, Zeph 3:20.

[\[9\]](#_ftnref9) *NET Bible®*, Zeph 2:9.

[\[10\]](#_ftnref10) Hill and Walton, *A Survey of the Old Testament*, 548.

[\[11\]](#_ftnref11) Hill and Walton, 549.

[\[12\]](#_ftnref12) *NET Bible®*, Lamentations 3:28; 33.

[\[13\]](#_ftnref13) *The Lexham English Bible (LEB), Fourth Edition*, Logo Bible Software, Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010), Matthew 23:37-39, http://www.lexhampress.com.

[\[14\]](#_ftnref14) Hill and Walton, *A Survey of the Old Testament*, 561--62.

[\[15\]](#_ftnref15) *NET Bible®*, Ezekiel (Ez) Chapter 1.

[\[16\]](#_ftnref16) *NET Bible®*, Ez 2:8; 3:8.

[\[17\]](#_ftnref17) *NET Bible®*, Ez 3:16-21.

[\[18\]](#_ftnref18) *NET Bible®*, Ez 48:35.

[\[19\]](#_ftnref19) Robert Jamieson, A. R. Fausset, and David Brown, *Commentary Critical and Explanatory on the Whole Bible (1871)* (Oak Harbor, WA: Logos Research Systems, Inc., 1997), 613.

[\[20\]](#_ftnref20) *NET Bible®*, Revelation 21:9-27.
