---
title: 'Class Assignment: Situational Reconstruction | Philemon'
date: '2021-11-05T05:16:00.0010000+00:00'
draft: false
categories:
  - 'Studies'
  - 'Class Assignment'
  - 'Biblical Studies'
  - 'Armchair Theology'
---
### Situational Reconstruction \| Philemon

The King's University, Southlake, Texas

Biblical Background and Interpretation (2021FA-BIBL-2301-ONL)

Professor: Dr. J. Wallace

11/04/2021

By Darrell Wolfe

#### The Epistle to Philemon

**Authorship/Date --** One of the four "prison letters", the Apostle Paul (and co-author Timothy)[\[1\]](https://draft.blogger.com/#_ftn1) wrote the short letter to Philemon when he was "an old man and also a prisoner" likely during his first Roman prison stay.[\[2\]](https://draft.blogger.com/#_ftn2) While several commentaries locate the four "prison" letters of Paul to his first Roman imprisonment (circa 60A.D.),[\[3\]](https://draft.blogger.com/#_ftn3) N.T. Wright makes the case for all four letters to have been written from his prison time in Ephesus (circa 52 A.D.).[\[4\]](https://draft.blogger.com/#_ftn4) One further commentary provides these options and a third, at Caesarea.[\[5\]](https://draft.blogger.com/#_ftn5) The strongest case seems to support the Rome conclusion, given the list of people (including Aristarchus and Luke) who are said to be with him, however, NT Wright's case for a more nuanced understanding of Paul's multi-year work in the region remains compelling.[\[6\]](https://draft.blogger.com/#_ftn6)

Many early church theologians did not pay much attention to the book as it was considered trivial. Slavery was commonplace through the ancient world and up until the modern era, and they were more preoccupied with big theological questions.[\[7\]](https://draft.blogger.com/#_ftn7) However, scholar N.T. Wright argues that Philemon is the first place to begin speaking about Pauls' central theological themes, including the "nature of this new family, the Messiah-people."[\[8\]](https://draft.blogger.com/#_ftn8)

**Recipients/Context --** In the letter itself, Philemon is indicated to be the master of a slave Onesimus, who may have caused some harm (by running away and theft, both common in the ancient world).[\[9\]](https://draft.blogger.com/#_ftn9) Onesimus was one of the Colossians, which indicates Philemon was also a Colossian (Col 4:7-9).[\[10\]](https://draft.blogger.com/#_ftn10) The church at Colossae is thought to have been started by Epaphras working under Paul during his three-year work at Ephesus and contained a largely gentile congregation. While most commentaries cite Philemon as the owner of the house church, not much evidence is cited for this supposition. However, the fact that Paul calls Philemon a "partner" may indicate a financial partnership common to the ancient near east, roman culture, and to the early church.[\[11\]](https://draft.blogger.com/#_ftn11) While the content of the letter is addressed to Philemon, the plural use of "you" indicates the whole body would hear the letter read aloud.[\[12\]](https://draft.blogger.com/#_ftn12)

** **

**Purpose/Issue --** The internal evidence shows that Paul is pleading on behalf of Onesimus (possibly a runaway slave) for his freedom and forgiveness. Paul indicates that Onesimus may owe something to Philemon, indicating that he had stolen or caused a financial harm in his flight.[\[13\]](https://draft.blogger.com/#_ftn13) While the implicit request of Paul is total emancipation (or to be given to Paul for his service), Paul seems content to at least restore the two to right relationship with each other (but better than it was before).[\[14\]](https://draft.blogger.com/#_ftn14)

In Colossians (a letter written to the same body at the same time), Paul calls Tychicus his "faithful servant and fellow slave in the Lord" while he makes a point to call Onesimus his faithful and dear brother (although he calls him a son in this letter).[\[15\]](https://draft.blogger.com/#_ftn15) Given the likelihood that these letters were sent to the same congregation and would be read aloud, the point would not be missed. Paul is elevating the status of Onesimus before all who hear these letters read aloud. It is also possible that Ephesians contains a veiled reference to the letter of Philemon as Paul discusses masters and slaves (6:9).[\[16\]](https://draft.blogger.com/#_ftn16) He uses all three letters to re-shape the way Jesus-people live in community with one another. Given these inter-textual tie-ins, the situation was likely well-known and provided Paul with an opportunity and object lesson to re-shape the community into a Messiah-family.

** **

**Resolution --** To make his case, Paul begins by reminding Philemon of his own track-history of love and challenging him to grow even more efficient (implied by the request about to come verses later). Wright makes the case that "Paul is teaching Philemon how to think as a Messiah-shaped kingdom-person".[\[17\]](https://draft.blogger.com/#_ftn17)

Paul lowers his own status from "Apostle" to "Slave/Prisoner" (while still reminding Philemon of his authoritative status) and raises Onesimus' status to brother. He pleads on Onesimus' behalf that he was useless but has become useful (a play on his name, which means "Useful").[\[18\]](https://draft.blogger.com/#_ftn18) He goes on to make the case that this new Messiah-shaped-family changes the dynamics; demonstrating that Onesimus is legally a slave but in the Kingdom of God they are also brothers (and should be treated as such). He concludes with an appeal to their ongoing partnership in the service of the gospel and requests they make a room for him as he plans to visit (which while true, adds weight to the need for Philemon to consider how he chooses to respond to the request). Paul hopes to be "restored" to Philemon from prison, just as he hopes Onesimus will be restored from his role as a runaway slave.

Historical tradition indicates that Onesimus went on to become an emancipated slave and bishop of Berea but was eventually martyred in Rome.[\[19\]](https://draft.blogger.com/#_ftn19) If so, this letter had a far-reaching impact on more than just these two men. The letters of Ephesians, Colossians, and Philemon worked together to shape and form Jesus-communities into families, upending the structures and status-quos. These fall in line with his teaching to the Galatians that "there is neither Jew nor Greek, slave nor free, male nor female, for you are all one in The Anointed One, Jesus".[\[20\]](https://draft.blogger.com/#_ftn20)

### Notes

[\[1\]](https://draft.blogger.com/#_ftnref1) Gordon D. Fee and Robert L. Hubbard, eds., The Eerdmans Companion to the Bible (Grand Rapids, Mich. ; Cambridge, U.K: W.B. Eerdmans Pub. Co, 2011), sec. Philemon-A Request Hard to Refuse.

[\[2\]](https://draft.blogger.com/#_ftnref2) The Lexham English Bible (LEB), Fourth Edition, Logo Bible Software, Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010), Phil 1:9, http://www.lexhampress.com.

[\[3\]](https://draft.blogger.com/#_ftnref3) Gordon D. Fee and Douglas K. Stuart, How to Read the Bible Book by Book: A Guided Tour (Grand Rapids, Mich: Zondervan, 2002), chap. Philemon; Robert Jamieson, A. R. Fausset, and David Brown, Commentary Critical and Explanatory on the Whole Bible (1871) (Oak Harbor, WA: Logos Research Systems, Inc., 1997), chap. Philemon; E. Ray Clendenen and Jeremy Howard, Holman Illustrated Bible Commentary (Broadman & Holman, 2015), chap. Philemon by Murray J. Harris; Christian Standard Bible® (CSB) (Nashville, Tennessee.: Holman Bible Pub, 2017), chap. Study Notes for Philemon "Background."

[\[4\]](https://draft.blogger.com/#_ftnref4) N. T. Wright and Michael F. Bird, The New Testament in Its World: An Introduction to the History, Literature, and Theology of the First Christians (London : Grand Rapids, MI: SPCK ; Zondervan Academic, 2019), 450--54.

[\[5\]](https://draft.blogger.com/#_ftnref5) The Lexham Bible Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott, C., ... Widder, W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham, WA: Lexham Press. (Billingham, WA: Leham Press, 2016), sec. Prison Letters, LexhamPress.com.

[\[6\]](https://draft.blogger.com/#_ftnref6) LEB, (See: Col 4:10, 14; Acts 27:2, 28:14); Kenneth Berding and Matt Williams, What the New Testament Authors Really Cared about: A Survey of Their Writings, Second Edition (Grand Rapids Mich.: Kregel Publications, 2008), 244, Introduction to Colossians.

[\[7\]](https://draft.blogger.com/#_ftnref7) Matthew V. Johnson, James A. Noel, and Demetrius K. Williams, eds., Onesimus, Our Brother: Reading Religion, Race, and Culture in Philemon, Paul in Critical Contexts (Minneapolis: Fortress Press, 2012), Williams, Chapter 1. "No Longer as a slave".

[\[8\]](https://draft.blogger.com/#_ftnref8) Wright and Bird, The New Testament in Its World, 366--67.

[\[9\]](https://draft.blogger.com/#_ftnref9) LEB, Phil 1:11-16.

[\[10\]](https://draft.blogger.com/#_ftnref10) Fee and Stuart, How to Read the Bible Book by Book, Philemon.

[\[11\]](https://draft.blogger.com/#_ftnref11) Wright and Bird, The New Testament in Its World, 366--69; The NET Bible First Edition Notes (Biblical Studies Press, 2006), sec. Notes for 1:6.

[\[12\]](https://draft.blogger.com/#_ftnref12) CSB, sec. CSB Notes: Background; LEB, Phil 1:3; 22.

[\[13\]](https://draft.blogger.com/#_ftnref13) LEB, Phil 1:18; Jamieson, Fausset, and Brown, Commentary Critical and Explanatory on the Whole Bible (1871), sec. The Epistle of Paul to Philemon, Object.

[\[14\]](https://draft.blogger.com/#_ftnref14) LEB, Phil 1:12-16 "I wanted to keep him\..." "so that you might get him back.. no longer a slave/dear brother".

[\[15\]](https://draft.blogger.com/#_ftnref15) LEB, Col 4:7-9; Phil 1:10.

[\[16\]](https://draft.blogger.com/#_ftnref16) Wright and Bird, The New Testament in Its World, 275.

[\[17\]](https://draft.blogger.com/#_ftnref17) Wright and Bird, 369.

[\[18\]](https://draft.blogger.com/#_ftnref18) Lexham Bible Dictionary, sec. ONESIMUS (Ὀνήσιμος, Onēsimos, "useful").

[\[19\]](https://draft.blogger.com/#_ftnref19) Jamieson, Fausset, and Brown, Commentary Critical and Explanatory on the Whole Bible (1871), 436, THE EPISTLE OF PAUL TO PHILEMON . "Onesimus in the Apostolical Canons \[73\], is said to have been emancipated by his master. The Apostolical Constitutions \[7.46\] state that he was consecrated by Paul, bishop of Berea, in Macedonia, and that he was martyred at Rome. IGNATIUS \[Epistle to the Ephesians, 1\], speaks of him as bishop of the Ephesians."

[\[20\]](https://draft.blogger.com/#_ftnref20) LEB, Gal 3:28 *Paraphase my own*.

### Bibliography

Berding, Kenneth, and Matt Williams. What the New Testament Authors Really Cared about: A Survey of Their Writings. Second Edition. Grand Rapids Mich.: Kregel Publications, 2008.

Christian Standard Bible® (CSB). Nashville, Tennessee.: Holman Bible Pub, 2017.

Clendenen, E. Ray, and Jeremy Howard. Holman Illustrated Bible Commentary. Broadman & Holman, 2015.

Fee, Gordon D., and Robert L. Hubbard, eds. The Eerdmans Companion to the Bible. Grand Rapids, Mich. ; Cambridge, U.K: W.B. Eerdmans Pub. Co, 2011.

Fee, Gordon D., and Douglas K. Stuart. How to Read the Bible Book by Book: A Guided Tour. Grand Rapids, Mich: Zondervan, 2002.

Jamieson, Robert, A. R. Fausset, and David Brown. Commentary Critical and Explanatory on the Whole Bible (1871). Oak Harbor, WA: Logos Research Systems, Inc., 1997.

Johnson, Matthew V., James A. Noel, and Demetrius K. Williams, eds. Onesimus, Our Brother: Reading Religion, Race, and Culture in Philemon. Paul in Critical Contexts. Minneapolis: Fortress Press, 2012.

The Lexham Bible Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott, C., ... Widder, W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham, WA: Lexham Press. Billingham, WA: Leham Press, 2016. LexhamPress.com.

The Lexham English Bible (LEB), Fourth Edition. Logo Bible Software. Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.). Bellingham, WA: Lexham Press, 2010. http://www.lexhampress.com.

The NET Bible First Edition Notes. Biblical Studies Press, 2006.

Wright, N. T., and Michael F. Bird. The New Testament in Its World: An Introduction to the History, Literature, and Theology of the First Christians. London : Grand Rapids, MI: SPCK ; Zondervan Academic, 2019.
