---
title: 'Class Assignment: COUNSELING PLAN  Isolation: Building Healthy Community'
date: '2021-11-14T00:48:00.0040000+00:00'
draft: false
categories:
  - 'Studies'
  - 'Class Assignment'
  - 'Mental Health'
---
### COUNSELING PLAN

### Isolation: Building Healthy Community

#### TKU Course: Biblical Counseling BIBC-2301

#### 1. Portraits

Glen is a man who has lived a lifestyle of isolation. At a young age, he recalls his favorite place to play was by himself in his room. When given a surprise party, he was angry at the presence of people he did not want in his space. Over the years, he landed in groups only when someone would find him and pull him in for a season. When he got married to a fellow isolationist, he spent 15 years without many real friends other than her and the kids. When she died two years ago, he found himself without his one friend. Since then, he's tried to make friends and build healthy community, without much success. He also finds himself drawn to unhealthy sexual community with unsafe women. He wants to build healthy non-romantic community.

#### 2. Definitions and Key Thoughts

- This condition is chronic, which means it will take time and seasons of change to experience victory on rising levels.

- Isolation is the condition of being (emotionally) separated from other individuals (M.S., 2013).

- God created mankind for community. The first "not good" pronounced by God in creation was that it is not good for Man to be alone (Clinton, 2015).

- There are vertical needs (man/God), horizontal needs (man/man), romantic needs (man/woman). If any of these are unmet, misplaced, or met through counterfeits, there is a felt gap.

- Community requires interactions with real human beings, not images on a screen or in a book (Ph.D., 2015). Likewise, friends who are only digital (Facebook/Online) can only meet some of the needs for community.

- The vertical relationship (God/Man) is also required, so engaging in activities that will foster the vertical relationship with God (in real vulnerable ways) will be necessary.

#### 3. Assessment Interview

- Describe for me what your relationships look like? How do they make you feel?

- When did you begin to become aware that your feelings of isolation were hindering your quality of life?

- What types of activities are you involved in, week to week?

- Describe a typical day, week, month?

- Describe your home life and relationship with your kids, individually and together.

- Describe your prayer life and relationship with God.

- Have you ever felt more connected to community? If so, what was this like? What were you doing? Who was involved? Break that season down for me.

- What do you know of your early years, before 10 years old?

- What friendships do you have today, where are they, and how vulnerable can you be with them? And they with you?

#### 4. Wise Counsel

Attachment theory demonstrates Internal Working Models that cause one to formulate answers to questions such as: Are others safe, reliable, and accessible to me during times of distress? Since logic alone will not reprogram the emotional brain, cognitive therapy alone will not suffice. The programs the brain runs are only accessible through the same means with which they were created; repeated and emotionally charged relational experiences (Clinton, 2015). Therefore, real dynamic community is required to address the problem.

Community requires vulnerability, not just presence (Townsend, 2000). Doing activities with others without expressing fears, worries, hopes, and dreams will not meet this need for community, which requires "allowing yourself to be dependent, have needs, express pain and hurts..." (Townsend, 2000, p. 74). While engaging in hobbies may be useful in finding community, engaging afterward and looking for opportunities to be vulnerable will be required.

Small groups or Recovery programs (such as Celebrate Recovery) may also be needed, which provide built-in safety for shared vulnerability.

Dating is an adult relationship meant for mature, intact adults... Mature adults will have a good support system that meets their needs for human contact, taking their needs to others for healing (Townsend, 2000, p. 73). Therefore, while not to avoid dating, the client will need to separate the needs met through Romantic Relationship and the needs met through Healthy Non-Romantic Community.

#### 5. Action Steps

A. Counseling is the first point of safe community. During counseling we will explore the history of why this developed, looking for strongholds and lies associated with trauma or life events. However, we will also take moments to sit with these emotions rather than brush past them, even pressing for where the feeling may be located in the physical body and feeling through that moment.

B. We will explore existing relationships, assessing for safety and risks in those relationships. Determine which may be counterproductive and which may be worth exploring and pushing for further vulnerability. In the case of the latter, expressing one surface feeling that would have otherwise gone unspoken. Possibly a preference being ignored or a need going unmet.

C. Be the change you seek. In your existing situations (school, work, groups, activities), pause to monitor the room. Identify someone who is also apparently isolating and introduce yourself to them. Ask at least 10 questions about them and listen for the answers (The Quick Reference Guide to Biblical Counseling: Personal and Emotional Issues, 2009, p. Loneliness).

D. Seek to try multiple new sources of community, new events, small groups, recovery meetings. Trying each for a minimum of 6 times before dropping. If no connection or joy is resulting, trying another.

E. If invited to an activity, look for ways to say yes and not excuses to say no.

G. Practical ways to build your vertical relationship with God: Go for prayer walks, listen to worship music, journal your requests, fears, hopes, dreams, and things you are angry about. Ask Him to speak with no agenda of what you want to hear, then write down anything you hear, see, or perceive.

#### 6. Biblical Insights

And we urge you, brothers and sisters, warn those who are idle and disruptive, encourage the disheartened, help the weak, be patient with everyone. [1 Thessalonians 5:14](https://www.biblestudytools.com/1-thessalonians/5-14.html)

Live in harmony with one another. Do not be proud, but be willing to associate with people of low position. Do not be conceited. [Romans 12:16](https://www.biblestudytools.com/romans/12-16.html)

Often, we can feel like the lone outsider. Once we begin working with others we find that our seemingly isolated experience is actually the common human experience. If you can look to become the friend you need and keep your eyes open, you may find friends in the most unusual places. Sow the seeds of friendship that you hope to reap.

As iron sharpens iron, so one person sharpens another. [Proverbs 27:17](https://www.biblestudytools.com/proverbs/27-17.html)

A friend loves at all times, and a brother is born for a time of adversity. [Proverbs 17:17](https://www.biblestudytools.com/proverbs/17-17.html)

Therefore confess your sins to each other and pray for each other so that you may be healed. The prayer of a righteous person is powerful and effective. [James 5:16](https://www.biblestudytools.com/james/5-16.html)

We were built for community. It is through sharing our struggles and pain, as well as our highlights and triumphs, that we become healthy and whole. You cannot be sharp unless you've been challenged by a fellow human. You cannot become healed or whole unless you have become vulnerable with others, telling them about that which is making you sick and allowed others to pray with you and for you in that sickness.

"...so in Christ we, though many, form one body, and each member belongs to all the others. [Romans 12:5](https://www.biblestudytools.com/romans/12-5.html)

Carry each other's burdens, and in this way you will fulfill the law of Christ. [Galatians 6:2](https://www.biblestudytools.com/galatians/6-2.html)

We are one body. We cannot only serve; we must also be served. We must carry other's burdens and allow them to carry ours. If we are missing either half of this equation, we become soul-sick and isolated. This means that you much become willing to not only serve... but allow others to serve you. You must allow others to pray for you, bring you food when you're sick, build you a ramp while you watch helplessly from your wheelchair. You must submit to community and you must serve community. Either extreme is unhealthy.
7. Prayer Starter

Daddy God, today marks a turning point in the life of your son, Glen. As he has acknowledged a need for healing and healthy community, I come into agreement with him that this too is covered under your blood. You built us for community, so I ask you to open his eyes to opportunities already present, bring him new opportunities, and reveal to him any lie-based strongholds that are holding him back from meeting a need you created him to fulfill. So Be It.
8. Recommended Resources

- Al-Anon Meeting Finder: <https://al-anon.org/al-anon-meetings/find-an-al-anon-meeting/>

- Celebrate Recovery Meeting Finder: <https://locator.crgroups.info/>

- Co-Dependents Anonymous Meeting Finder: <https://coda.org/find-a-meeting/>

- American Association of Christian Counselors ([www.aacc.net](http://www.aacc.net/))

- Ecounseling ([www.ecounseling.com](http://www.ecounseling.com/))

- See also, Book Suggestions below in bold.

- #### Works Cited

(2009). In D. T. Hawkins, The Quick Reference Guide to Biblical Counseling: Personal and Emotional Issues. Grand Rapids, MI: Baker Books.

Brother Lawrence, F. C. (2017). Practicing His Presence. Seedsowers.

Clinton, D. R. (2015). In The New Christian Counselor. A fresh biblical & transformational approach. Eugene, OR: Harvest House Publishers.

God. (1984). Key Word Study Bible. In New King James. Chattanooga, TN: AMG Publishers.

Hamp, B. (2010). In Think Differently Live Differently: Keys to a Life of Freedom. Southlake, TX: Bob Hamp.

M.S., N. P. (2013, May 11). isolation. Retrieved from Psychology Dictionary: https://psychologydictionary.org/isolation/

Ph.D., D. D. (2015, Feb 19). Where Is Your Community? Is American community an endangered species? Retrieved from Psychology Today: https://www.psychologytoday.com/us/blog/your-personal-renaissance/201502/where-is-your-community

Richards, D. J. (1993). In Grace: The Power to Change. New Kensington, PA: Whitaker House.

Sorge, B. (2001). Secrets of the Secret Place: Keys to Igniting Your Personal Time with God. Oasis House.

Townsend, D. H. (2000). Boundaries in Dating. Grand Rapids: Zondervan.
