---
title: 'NoHiding Faith Studies:  Exegesis of Hebrews 13:4 – The Undefiled Marriage Bed'
date: '2022-05-07T22:21:00.0060000+00:00'
draft: false
categories:
  - 'NoHiding Faith Studies'
---
###  Exegesis of Hebrews 13:4 -- The Undefiled Marriage Bed

Submitted to NoHiding.Faith

By, Darrell Wolfe

Topos Creative LLC

North Pole, Idaho

May 2022

# Introduction to Hebrews

Recently, a friend asked my wife and I to meditate on [Hebrew 13:4](https://ref.ly/logosres/leb?ref=BibleLEB2.Heb13.4). The following is my written mediation on this passage.

*Marriage must be held in honor by all, and the marriage bed be undefiled, because God will judge sexually immoral people and adulterers.**[1]***

A proper and thorough "interpretation" of a passage of scripture should begin by an analysis of the whole book and the context of the passage. Since I was foggy on this text (Hebrews), I begin with such an analysis.

**Authorship and Date:** While many traditions assign the authorship of Hebrews to Paul, the authorship cannot be certain. Even in antiquity there were questions about the authorship. Nevertheless, it was deemed to be of sufficient quality and usefulness that most early Yeshua communities included this text within their authoritative references. There is some evidence for Pauline authorship, "Hebrews is first quoted by [Clement of Rome](https://ref.ly/logosres/csbstudybible?art=heb.1.5&off=1924) in his letter to the Corinthians. AD 96"[2] While authorship is disputable, one critical commentary makes a fascinating note, "[CLEMENT also says that Paul](https://ref.ly/logosres/jfbcomm?ref=VolumePage.V+2%2c+p+438&off=1172&ctx=le+to+the+Gentiles.+~Clement+also+says+th), as the Hebrews were prejudiced against him, prudently omitted to put forward his name in the beginning; also, that it was originally written in Hebrew for the Hebrews, and that Luke translated it into Greek for the Greeks, whence the style is similar to that of Acts."[3] This commentary also says asserts that "internal evidence favors Pauline authorship" and that it was probably written before the destruction of Jerusalem as this would have been mentioned if it were after (given the many citations to Temple life), therefore it was written before 70AD.[4]

**Audience:** The audience is also under some dispute. While the majority opinion is that Hebrews was written to a Jewish audience in need of reassurance that this new covenant was worth following, DeSilva makes a compelling case for understanding Gentiles as the primary audience of Hebrews. He [concludes by saying](https://ref.ly/logosres/introntdesilva2ed?ref=Page.p+688&off=267&ctx=+(%E2%80%9CTo+the+Hebrews%E2%80%9D)+~to+obscure+the+proba), "we would do well, therefore, not to allow the second-century conjectural title ("To the Hebrews") to obscure the probability that the sermon addressed Christians of mixed ethnic backgrounds (all the more if the letter was indeed addressed to a congregation formed as a result".[5] Gentile audiences, more than Jewish audiences, would have needed the thorough line by line of their community scriptures that Jewish audiences grew up with, and reassurance that these Hebrew Scriptures (Genesis-Malachi, the Tanakh) belonged to them. DeSilva also notes in his Genre and Structure section, that this could be considered a written speech, rather than a letter. It may be the Bible's longest recorded sermon. He goes on to note the [pastoral quality of the work](https://ref.ly/logosres/introntdesilva2ed?ref=Page.p+698&off=2444):

*"Helping people commit to an unpopular way of life---one that has already cost them a great deal---is a challenge for even the most skilled of orators. The author of Hebrews, however, rose to this challenge by means of a cohesive, multipronged attack on the forces that were eroding his hearers' commitment".**[6]***

# The Tone of Hebrews

Hebrews begins by saying that God worked with various people in various ways and finally sent his Son to be the ultimate guide to the heart of God (Hebrews 1:1). He warns his readers not to "drift away" but remain faithful to God (Hebrews 2:1; contrary to what some theological systems teach, one can drift away). He compares this new community of Yeshua followers to the original members of the exodus. Just as Israel left Egypt physically but rebelled in the wilderness between vacating slavery and entering the promised land; so too followers of Yeshua live today between vacating slavery (the world's Babylonian ways) and entering the promised land (New Creation after the Day of the Lord). The author of Hebrews warns us not to "harden your hearts" (Hebrew 3:7). Real, legitimate, practical fear of losing our place in God should drive us to remain awake (Hebrews 4:1). Not that we could "loose our salvation" by accident or by some arbitrary mistake or sinful action, those were covered by the blood of Yeshua HaMashiach. Rather, the danger as he continues to repeat and drive-home for his readers/hearers is: "if you hear his voice, do not harden your hearts" (Hebrews 4:3, Psalms 95:11). Michael Heiser calls this, "Believing Loyalty". On his Podcast commentary on Hebrews ([Naked Bible 184: Hebrews 5:11-6:20](https://nakedbiblepodcast.com/podcast/naked-bible-184-hebrews-511-620/)), Heiser says it this way:

*You can't just be like, "I believed ten minutes on a Sunday morning twenty years ago and I prayed this prayer, and since I prayed that prayer I'm in, and now I can more or less believe whatever I want." I'm sorry, but that's not the truth. You must believe. A biblical theology of belief involves believing loyalty. Not "I believe and now I've got to do all these works. That's how loyalty is defined---doing works." No, you believe and you keep believing. You are loyal to that belief. Salvation is by grace through faith---through belief. It has nothing to do with your own merit. You don't earn it. A biblical theology of belief is believing loyalty---remaining loyal to that belief. And, of course, Christ is the object of that belief---what he did, not what you do. That theology of belief does not mean we can pray a prayer of confession and then choose to follow another god or choose to follow another gospel or choose to follow no gospel at all. Belief is not uttering a prayer like it's an incantation.**[7]***

Pastoral note here, while believing loyalty is the best definition of "faith", we have all had a season of struggle at least once in our walk with God. If you haven't yet, you will. Some event, set of events, or series of seasons will draw us to question our allegiance to Yahweh. For some, it may come as a sense of coldness, making it all feel pointless or unreal. For others, it may come as a disappointment because the thing you expected didn't happen. For others, it may come as furious rage against God, after all, "how could he have let this happen to me"? For some, like me, it will be all of those things, several times, over multiple seasons over a lifetime. And yet, God stood by my rage, fist-shaking, honest-raw-intensity... and in the end, during my darkest hours 2016-2019, I felt him saying "I never promised I would prevent evil, only that I would make it right at the end of all things and walk with you through that valley as many times as you enter it". It took some of the hardest things anyone can go through to beat all expectations of a "good life" here and now out of me. I appreciate the days when things go well. I value the blessings. But I also allow the hardships to come, pass, and go. Feeling awful? It's okay, "this too shall pass". Feeling fabulous? It's okay, "this too shall pass". I used to believe that having "faith" meant the removal of all doubt and fear, I was wrong. Faith means having believing loyalty. It means remaining loyal to Yahweh despite the doubt and fear. It means being open, honest, and ruthless raw and real with that fear by brining it to Yahweh and trusted others and to work through it in community. Faith isn't fearless or doubtless, it is trusting in Yahweh despite the doubts and fears.

For brevity, since this is aimed at Hebrews 13, I will summarize the remaining chapters by saying that at each stage of the book of Hebrews, the author is making a single argument. The argument is that this Believing Loyalty in Yeshua is the long-awaited promise and only faith worth living and dying for, and he continually warns not to lose heart or walk away. Using the Hebrew Scriptures (primarily the Greek Septuagint translation), the author weaves back and forth to show the Messianic profile throughout the scriptures and shows how the Son of God, the New and Better David, the Better Priest, ultimately came to show the fullness of what God intended through the original covenant(s) and establish a new, better, and permeant covenant as its ultimate fullness. In essence, the work titled Hebrews is a first-century messianic commentary on the Tanakh (Torah, Prophets, and Writings). It is reminding Jews and introducing Gentiles to the long heritage into which the Yeshua follower is invited to participate.

In their exegetical guide to Hebrews, [Fee and Stuart](https://ref.ly/logosres/h2rbblbkbybk?ref=Bible.Heb&off=1428&ctx=OVERVIEW+OF+HEBREWS%0a~Hebrews+is+a+long%2c+s) provide the following introduction:

*"Hebrews is a long, sustained argument, in which the author moves back and forth between an argument (based on Scripture) and exhortation. What drives the argument from beginning to end is the absolute superiority of the Son of God to everything that has gone before; this is what his exposition of Scripture is all about. What concerns the author is the possibility that some believers under present distress will let go of Christ and thus lose out on the Son's saving work and high priestly intercession, and thus their own experience of God's presence; this is what the interspersed exhortations are all about."**[8]***

In the CSB Study Bible, [Yarnell](https://ref.ly/logosres/csbstudybible?ref=BibleHCSB.Heb&off=32) provides the following introduction:

*"The epistle to the Hebrews is a tribute to the incomparable Son of God and an encouragement to the author's persecuted fellow believers. The author feared that his Christian readers were wavering in their endurance. The writer had a twofold approach. (1) He exalted Jesus Christ, who is addressed as both "God" and "the Son of Man," and is thus the only one who can serve as mediator between God and humanity. (2) He exhorted his fellow Christians to "go on to maturity" and live "by faith.""**[9]***

# Looking closer at Hebrew 13:4

As we enter the closing chapter of Hebrews, we see the author take a turn to answering the unspoken question "and now what?". Now that we know the story of God goes back centuries, and that God has been working up to this moment in history for many generations, and that he finally sent his Son as the capstone project to the whole endeavor up to the point of this author's writing... now what? How should a community of Jewish and Gentile people, combined in Israel's Messiah, under a new and better covenant, live out that community together? What should that look like? The author concludes by demonstrating the different ways that "brotherly love" must be the key indication of this community (Hebrews 13:1). Each statement to follow is a demonstration of this Brotherly Love in action. One could summarize the entire section by the phrase "Love God, Love Folks, don't be a dick" (thanks to my forever irreverent wife for that quote). In podcast [episode 199](https://nakedbiblepodcast.com/podcast/naked-bible-199-hebrews-13/), Hebrews 13, Heiser makes the following observations:

*So you have the first six verses here, and the tone is really obvious: "Let brotherly love continue." Well, why would he even mention that? Again, it's because of what he just got done saying in the 12th chapter: "Let brotherly love continue." The context, of course, is encouraging mutual support in the face of persecution, so as to help believers (people in the community) endure (that is, keep believing). But the whole section here is just sort of peppered with pastoral sorts of encouragement.*

*\|*

*All of these exhortations, in general, are about the community life and, really, things that would either threaten the solidarity of the community, threaten the testimony of the community, and in some cases, it's aimed at getting the people within the community to not surrender their faith (that familiar idea that we've seen so many times going up to this chapter).*

*\|*

* Basically, what he's saying is that to the people of this time period kind of looking at Christian behavior, they thought it was a little bizarre because they engaged in behavior that was typically reserved for immediate family members, and they widened it to non-family members in their community. **[10]***

Fee, in his exegetical guide, [notes the following](https://ref.ly/logosres/h2rbblbkbybk?ref=Bible.Heb13.1-25): "Watch for the ways these exhortations emphasize his readers' need to love others in the community and to submit to their leaders, all the while still contrasting Christ with what has preceded him (thus, e.g., the sacrificial system is out, but a sacrifice of praise and of doing good to others is in \vv. 15--16])."[[11] [Merrill states is this way](https://ref.ly/logosres/csbstudybible?ref=BibleHCSB.Heb13.1-6&off=0&ctx=ived+in+the+church.%0a~13%3a1%E2%80%936+Under+the+gen), "under the general theme of allowing brotherly love to reign within the church, the author addressed five specific activities in which Christians should engage: (1) show hospitality toward strangers, (2) visit those in prison, (3) minister to the mistreated, (4) honor marriage, and (5) free themselves from the love of money."[12]

            Circling back to Hebrews 13:4, let's read this passage again but look at it closer.

*Marriage must be held in honor by all, and the marriage bed be undefiled, because God will judge sexually immoral people and adulterers.**[13]***

We see a key word: "undefiled". Mounce expounds on this word:

*"\[299\] [ἀμίαντος amiantos](https://ref.ly/logosres/mounceexpdic?ref=GreekStrongs.283) 4× pr. unstained, unsoiled; met. undefiled, chaste, Heb. 7:26; 13:4; pure, sincere, Jas. 1:27; undefiled, unimpaired, 1 Pet. 1:4* \283]"[**[14]***

Since the author uses the Septuagint (a Greek translation of the Old Testament plus other popular Second Temple Hebrew Literature, which was the primary Bible of the early church) in many of his quotes from the Tanakh, it may be helpful to look at the Septuagint to see where else this phrase has been used. Interestingly, when we reference The Lexham Analytical Lexicon to the Septuagint for this word amiantos ([ἀμίαντος](https://ref.ly/logosres/lxgrkotanlex?hw=%E1%BC%80%CE%BC%CE%AF%CE%B1%CE%BD%CF%84%CE%BF%CF%82)), we find a parallel passage in an unlikely place.[15] We see this used in two books that were considered important for Second Temple period Judaism but never included in the Tanakh (Wisdom of Solomon \[Wis 3:13; 4:2; 8:20\] and the 2 Maccabees \[2 Mac 14:36; 15:34\]). The author appears to be "[stringing pearls](https://ref.ly/logosres/9780310350415?art=r12)", a Rabbinic technique in which the author familiar with Hebrew literature, expecting his students to be familiar with Hebrew literature, partially quotes or alludes to a passage to make the fuller understanding only available to those who follow the pearl he left behind.[16] Keeping in mind that the Author of Hebrews is writing to people who are attempting to live within persecuted Yeshua communities, and that his goal is to keep them from hardening their hearts and walking away, what could he say that would encourage them to move forward? He calls to mind many things, but in this particular phrase about an undefiled marriage bed, he calls to mind a popular Second Temple Hebrew literary work. In [Wisdom of Solomon 3:14](https://ref.ly/logosres/lelxx?ref=BibleLXX2.Wis3.9&off=95), we find the following:

*But **righteous souls are in the hand of God, and torment will never touch them**. 2 They **seemed to have died**, in the eyes of the foolish, and **their departure was considered to be oppression**, 3 and their journey from us to be an affliction; **but they are at peace**. 4 For even if they are punished in the sight of people, their hope is full of immortality; 5 and having been disciplined a little, they will receive great good, because God tested them and found them worthy of himself. 6 **He tested them like gold in a smelting furnace, and he received them like a whole burnt offering of sacrifice**. 7 And in the time of their examination they will shine out, and they will run around like sparks in straw. 8 They will judge nations, and they will rule over peoples, and the Lord will reign over them* *⌊forever⌋.a 9 Those who trust him will understand truth, and the faithful in love will remain with him, because grace and mercy belong to his chosen ones. 10 But the ungodly will have punishment according to what they reckoned, those who neglected the righteous and deserted the Lord.*

*11 For the one who disdains wisdom and instruction is miserable, and their hope is vain, and their labors are unprofitable, and their works are useless. 12 Their wives are foolish, and their children wicked; and their lineage is cursed.*

*13 Because the blessed is the **undefiled barren woman**, who has **not experienced intercourse in transgression**; she will have fruit at the examination of souls.*

*14 And blessed is the eunuch who worked no transgression by hand or considered evil things against the Lord; for because of his faithfulness, there will be given to him choice favor and a delightful share in the temple of the Lord.*

*15 For the fruit of good labors is glorious, and the root of understanding is infallible. 16 But children of adulterers will be unable to reach maturity, and the seed of unlawful intercourse will perish. 17 For even if they become long-lived, they will be reckoned as nothing and without honor at the end of their old age. 18 Even if they die quickly, they have no hope or comfort in the day of decision; 19 for the ends of an unrighteous generation are grievous. Rick Brannan et al., eds., The Lexham English Septuagint (Bellingham, WA: Lexham Press, 2012), Wis 3:1--19.*

The [Apocrypha in the King James Version](https://ref.ly/logosres/kjvapoc?ref=BibleKJV.Wis3.19) words it this way:

*13 Their offspring is cursed. Wherefore blessed is the barren that is undefiled, which **hath not known the sinful bed**: she shall have fruit in the visitation of souls.**[17]***

# The Undefiled Marriage Bed

            So, what is the author of Hebrews getting at? Why is the undefiled marriage bed important to the Yeshua community? Regarding the marriage section in particular, [John Owen](https://ref.ly/logosres/worksowen24?ref=Bible.Heb13), one of the earliest scholars to do a full commentary on Hebrews, makes some interesting observations. Paraphrased to bring it into modern English, Owen notes that Adam and Eve were married "instantly" and within the context of paradise. In a place where no sin had yet tainted creation, Adam was considered incomplete without his Eve (Genesis 2). Further, he notes that Yahweh himself found it so important that the early law codes given to Israel banned children born outside of the marriage covenant from entering the assembly of Yahweh (a possible [Divine Council](https://www.thedivinecouncil.com/) reference)[18] even unto the tenth generation (Deuteronomy 23:2).[19]

            As with almost every question of theology, it all roots back to Genesis 1-11, the prologue of the Bible. The prologue establishes the "[Divine Ideal](https://bibleproject.com/podcast/series/holiness-series/?utm_source=web_social_share&medium=shared_podcast)"[20] God established Dirt (Adam) and Life (Eve) as a pair. Together they were to "be fruitful, multiple, fill the earth, and subdue it" (Genesis 1-2). The seed of the dirt-man was deposited into the life-woman and divine fruitfulness was the result. Both physically and metaphorically, the pairing together of equal but opposites created an environment in which fruitfulness could occur. The mandate for Humankind (Male and Female) to become Imagers of God was lived out by being fruitful and multiplying and filling and subduing (Genesis 1:28). This unity in diversity was solidified by joining Man (Ish -- אִישׁ) and Wife (Ishah - אִשָּׁה) as "one flesh", naked and unashamed. They were "one".

Throughout the Tanakh, the concept of adultery ([נָאַף nāʾap](https://ref.ly/logosres/mounceexpdic?hw=%D7%A0%D6%B8%D7%90%D6%B7%D7%A3&off=7&ctx=%5b5537%5d+~%D7%A0%D6%B8%D7%90%D6%B7%D7%A3+na%CC%84%CA%BEap+31%C3%97+%5bQ%2c+P%5d+to+commit) to commit adultery)[21] would be used as the driving metaphor for the way Israel treated Yahweh. While this particular word is used 31 times in the Hebrew Bible, other cognates (unfaithfulness, whoreing, etc.) are used many times. This theme is so prevalent in the story of Israel, that the entire book of Hosea is dedicated to this theme. Isaiah cries "how has a faithful city become like a whore?" (Isaiah 1:21). A careful reading of the meta-narrative of Israel shows that God finds a particularly poignant metaphor in the way a man and wife remain faithful (or feel betrayed) to the way he feels about believing loyalty between himself and his covenant people.

            As the author of Hebrews is wrapping up a book saturated in the Tanakh and the meta-narrative of Israel's relationship to Yahweh, and he attempts to find ways to express what living in community as Yahwehist Yeshua Followers should look like, he finds the undefiled marriage bed to be one of the key indicators of the kind of heart posture that is required. This is not an appeal to perfection, or a call to treat poorly those community members who have not abided by these standards perfectly. Rather, it is a call to the ideal.

Anyone who has had a partner leave them for another lover knows the keen sting that this kind of betrayal can cause. Anyone who has been the offending partner knows the devastation it brings to their partner, family, community, career, and the internal shame it brings to themselves. I have seen many friends (including myself during various seasons, I'm no exception to the imperfect brokenness of human sexuality) treat sex and sexuality causally, and without exception I've seen it bring death, depression, and chaos as a result, it never brought freedom and life to the participants.

Few other human situations are more analogous to this type of emotional state. Few others so totally encapsulate the call to Believing Loyalty. Keeping the marriage bed pure isn't about restriction of fun, arbitrary rules to prevent people from enjoying their sexuality, or any of the objections folks in alternative lifestyles want to push. Keeping the marriage bed pure is about protecting the hearts of all involved. While "all things are lawful... not all things are profitable or beneficial" (1 Corinthians 6:12; 10:23). Choosing to live in a restricted marriage covenant is an act of solidarity with the Creator of human sexuality who wants above and beyond anyone else on planet earth for his humans to enjoy what he built, within healthy and safe boundaries.

            Finally, a note about the fallen nature of our present reality. We do not live in an ideal world. Examples, including biblical examples, are numerous in which the ideal is not what happened. Abraham's marriage to his sister Sarah and Jacob's marriage to his sister-wives are both banned in later Levitical code (Leviticus 18; Genesis 12:19; Genesis 20:12; Genesis 29:15-29). The same passage that is often cited condemning homosexuality (Leviticus 18) also condemned the marriages of Abraham and Jacob, and even having sex with one's own wife on her period. The stories of the Bible are not there to give us moralizing codes, "this guy did this, therefore here's a lesson and go and do what he did". The stories of the Bible are real accounts of how imperfect fallen human beings walked out their imperfect relationship with Yahweh at the level of revealed understanding they had access to follow. Abraham knew less than Moses. Moses knew less than David. David knew less than Isaiah. Isaiah knew less than Yeshua HaMashiach. At each stage, Yahweh reaches into imperfect humanity, accepts them where they are within their own cultural context, but firmly raises them up another notch, calls them higher, further, farther. While the Levitical codes seem backward and oppressive to modern English readers, when compared to the [Code of Hammurabi](https://www.worldhistory.org/Code_of_Hammurabi/)[22] (a mirror code from a contemporary culture) the Levitical code seems progressive and a huge step forward. It provides more protection for the women, children, strangers, orphans, widows, and poor than any other contemporary culture's codes. Each step Yahweh takes, brings his people further into the ideal.

While the specifics of how this is walked out in our lives in 2022 are far murkier than the dominant voices in modern western American Christianity's mainstream would have you believe, they aren't as far off as their detractors would have you believe either. The ideal is and always has been for Ish & Ishah to become one single unified entity. Together they become the God Imagers, resulting in a fruitful multiplying of their efforts and a transformed environment whereby fruitfulness can flourish. Their complementary biology is the natural indicator of their equal but opposite spiritual natures joining to become one new thing. The whole is greater than the sum of its parts. Two individuals (even opposite gendered ones) who love each other without God as the center, will never become the imagers they were designed to be. Two individuals who are not equal but opposite genders, will never become the imagers they were designed to be. Three or more partners in a polyamorous relationship, will never become the imagers they were designed to be. Even those who are opposite gendered and submitted to God, will only ever become imperfect imagers, but they are striving toward the Divine Ideal.

Even scientific research has shown indications of gender playing a role in the oddest places. The XX and XY chromosomes play a role in just about every layer of male/female life from sexuality, thinking patterns and communication all the way down to which diseases are more likely to occur. Males and Females communicate differently, especially when paired with opposite gender.[23] Males have higher incidence of cardiovascular disease but the outcomes for females who get it are worse on average.[24] Meanwhile, 8-10 patients with auto-immune disease are female.[25] While society wants to erase these differences and allow for someone to self-identify, the genetic and biological properties of these differences will continue to remain the same for those individuals.

The ideal is for Ish & Ishah to become one with each other and one with God, and in that triune unity, to become fruitful imagers. That is the type of unity Yeshua refers to when he calls all his followers to become one with each other and with the Godhead (John 17:6-26). This undefiled marriage bed is an example of the unity of the Followers of Yeshua to Yahweh, and the unity of the Godhead within himself. Just as the Father, Spirit, and Son are distinct individuals but form a single complementary unit we call "God" in English, the marriage is to represent that reality by forming a unit of three (Man, Wife, and God). Therefore, Paul refers to a man needing to love his wife "as Christ loved the Church" and gave himself for her (Ephesians 5:15-33). While many in the "church" have quoted the passage about women obeying their husbands out of context, the entire section is referring to humans needing to consider "carefully how you live" while "speaking to one another with psalms, hymns, and songs" all while "being subject to one another out of reverence for The Anointed One (HaMashiach, Christos, Christ)" (Ephesians 5:17-21). Within that mutual submission, wives love husbands through a form of empowered submission/service (all leaders are servants in the Kingdom) and husbands love wives by dying to self and cherishing her needs above his own. It is this type of mutual submission, mutual dying to self, that embodies the lifestyle of Yeshua followers. It is this mutual self-sacrifice for one's partner that demonstrates the kind of love Yahweh had for his covenant partners, and Yeshua had by giving himself up for his "bride" who is "the church".

It is this matrix of ideas into which the author of Hebrews tells his community of Yeshua followers to "keep the marriage bed undefiled" (Hebrews 13:4).

# Bibliography

Carli, Linda L. "Gender Differences in Interaction Style and Influence." *Journal of Personality and Social Psychology* 56, no. 4 (1989): 565--76. https://doi.org/10.1037/0022-3514.56.4.565.

*Christian Standard Bible® (CSB), Notes Edition*. Nashville, Tennessee.: Holman Bible Pub, 2017.

World History Encyclopedia. "Code of Hammurabi." Accessed May 7, 2022. https://www.worldhistory.org/Code_of_Hammurabi/.

DeSilva, David Arthur. *An Introduction to the New Testament: Contexts, Methods & Ministry Formation*. Second Edition. Downers Grove: InterVarsity Press, 2018.

Editors, History com. "Code of Hammurabi." HISTORY. Accessed May 7, 2022. https://www.history.com/topics/ancient-history/hammurabi.

Fee, Gordon D., and Douglas K. Stuart. *How to Read the Bible Book by Book: A Guided Tour*. Grand Rapids, Mich: Zondervan, 2002.

Gao, Zujie, Zengsheng Chen, Anqiang Sun, and Xiaoyan Deng. "Gender Differences in Cardiovascular Disease." *Medicine in Novel Technology and Devices* 4 (December 1, 2019): 100025. https://doi.org/10.1016/j.medntd.2019.100025.

Greuter, Thomas, Christine Manser, Valerie Pittet, Stephan R. Vavricka, Luc Biedermann, and an official working group of the Swiss Society of Gastroenterology on behalf of Swiss IBDnet. "Gender Differences in Inflammatory Bowel Disease." *Digestion* 101, no. 1 (2020): 98--104. https://doi.org/10.1159/000504701.

Heiser, Michael, and Trey Stricklin. "Naked Bible 184: Hebrews 5:11-6:20." Hebrews. Accessed May 7, 2022. https://nakedbiblepodcast.com/podcast/naked-bible-184-hebrews-511-620/.

---------. "Naked Bible 199: Hebrews 13." Hebrews. Accessed May 7, 2022. https://nakedbiblepodcast.com/podcast/naked-bible-199-hebrews-13/.

BibleProject. "Holiness Podcast Series \| BibleProject^TM^." Accessed May 7, 2022. https://bibleproject.com/podcast/series/holiness-series/?medium=shared_podcast&utm_source=web_social_share.

Jamieson, Robert, A. R. Fausset, and David Brown. *Commentary Critical and Explanatory on the Whole Bible (1871)*. Oak Harbor, WA: Logos Research Systems, Inc., 1997.

Mounce, William D., ed. *Mounce's Complete Expository Dictionary of Old & New Testament Words*. Grand Rapids, Mich: Zondervan, 2006.

Owen, John. *An Exposition of the Epistle to the Hebrews - with Preliminary Exercitations*. Edited by W.H. Goold. Vol. 24. Works of John Owen. Edinburgh: Johnstone and Hunter, 1854.

Spangler, Ann, and Lois Tverberg. *Sitting at the Feet of Rabbi Jesus: How the Jewishness of Jesus Can Transform Your Faith*. Updated edition. Grand Rapids, Michigan: Zondervan, 2018.

*The Apocrypha: King James Version*. Bellingham, WA: Logos Research Systems, Inc., 1995.

"The Avalon Project : Code of Hammurabi." Accessed May 7, 2022. https://avalon.law.yale.edu/ancient/hamframe.asp.

The Divine Council.com. "The Divine Council.Com." Accessed May 7, 2022. https://www.thedivinecouncil.com/.

*The Lexham Analytical Lexicon to the Septuagint*. Bible Reference Series. Bellingham, WA: Lexham Press, 2012.

*The Lexham English Bible (LEB), Fourth Edition*. Logo Bible Software. Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.). Bellingham, WA: Lexham Press, 2010. http://www.lexhampress.com.

------------------------------------------------------------------------

[1] *The Lexham English Bible (LEB), Fourth Edition*, Logo Bible Software, Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010), Heb 13:4, http://www.lexhampress.com.

[2] *Christian Standard Bible® (CSB), Notes Edition* (Nashville, Tennessee.: Holman Bible Pub, 2017), 1947; Malcolm B. Yarnell III, "Hebrews,".

[3] Robert Jamieson, A. R. Fausset, and David Brown, *Commentary Critical and Explanatory on the Whole Bible (1871)* (Oak Harbor, WA: Logos Research Systems, Inc., 1997), 438.

[4] Jamieson, Fausset, and Brown, 438.

[5] David Arthur DeSilva, *An Introduction to the New Testament: Contexts, Methods & Ministry Formation*, Second Edition (Downers Grove: InterVarsity Press, 2018), 688.

[6] DeSilva, 698.

[7] Michael Heiser and Trey Stricklin, "Naked Bible 184: Hebrews 5:11-6:20," Hebrews, accessed May 7, 2022, https://nakedbiblepodcast.com/podcast/naked-bible-184-hebrews-511-620/.

[8] Gordon D. Fee and Douglas K. Stuart, *How to Read the Bible Book by Book: A Guided Tour* (Grand Rapids, Mich: Zondervan, 2002), 391.

[9] *CSB*, 1945; Malcolm B. Yarnell III, "Hebrews,".

[10] Michael Heiser and Trey Stricklin, "Naked Bible 199: Hebrews 13," Hebrews, accessed May 7, 2022, https://nakedbiblepodcast.com/podcast/naked-bible-199-hebrews-13/.

[11] Fee and Stuart, *How to Read the Bible Book by Book*, 396. 13:1--25 Concluding Practical Exhortations and Greetings

[12] *CSB*, 1961, Eugene H. Merrill, "Jesus and Atonement in the Old Testament,".

[13] *LEB*, Heb 13:4.

[14] William D. Mounce, ed., *Mounce's Complete Expository Dictionary of Old & New Testament Words* (Grand Rapids, Mich: Zondervan, 2006), 1079.

[15] *The Lexham Analytical Lexicon to the Septuagint*, Bible Reference Series (Bellingham, WA: Lexham Press, 2012), See: ἀμίαντος.

[16] Ann Spangler and Lois Tverberg, *Sitting at the Feet of Rabbi Jesus: How the Jewishness of Jesus Can Transform Your Faith*, Updated edition (Grand Rapids, Michigan: Zondervan, 2018), sec. See: Stringing Pearls.

[17] *The Apocrypha: King James Version* (Bellingham, WA: Logos Research Systems, Inc., 1995), Wis 3:13.

[18] "The Divine Council.Com," The Divine Council.com, accessed May 7, 2022, https://www.thedivinecouncil.com/.

[19] John Owen, *An Exposition of the Epistle to the Hebrews - with Preliminary Exercitations*, ed. W.H. Goold, vol. 24, Works of John Owen (Edinburgh: Johnstone and Hunter, 1854), 403, Verse 4.

[20] "Holiness Podcast Series \| BibleProject^TM^," BibleProject, accessed May 7, 2022, https://bibleproject.com/podcast/series/holiness-series/?medium=shared_podcast&utm_source=web_social_share.

[21] Mounce, *Mounce's Complete Expository Dictionary of Old & New Testament Words*, נָאַף nāʾap, 989.

[22] History com Editors, "Code of Hammurabi," HISTORY, accessed May 7, 2022, https://www.history.com/topics/ancient-history/hammurabi; "Code of Hammurabi," World History Encyclopedia, accessed May 7, 2022, https://www.worldhistory.org/Code_of_Hammurabi/; "The Avalon Project : Code of Hammurabi," accessed May 7, 2022, https://avalon.law.yale.edu/ancient/hamframe.asp.

[23] Linda L. Carli, "Gender Differences in Interaction Style and Influence," *Journal of Personality and Social Psychology* 56, no. 4 (1989): 565--76, https://doi.org/10.1037/0022-3514.56.4.565.

[24] Zujie Gao et al., "Gender Differences in Cardiovascular Disease," *Medicine in Novel Technology and Devices* 4 (December 1, 2019): 100025, https://doi.org/10.1016/j.medntd.2019.100025.

[25] Thomas Greuter et al., "Gender Differences in Inflammatory Bowel Disease," *Digestion* 101, no. 1 (2020): 98--104, https://doi.org/10.1159/000504701.
