---
title: 'The Divine Council Worldview: God''s advisory board of humans and elohim'
date: '2022-05-20T05:20:00.0030000+00:00'
draft: false
categories:
  - 'Bible Answer'
---
# An error occurred.

Unable to execute JavaScript.

### **The Divine Council**

If you've never heard the term "Divine Council", you're not alone. It's too bad. Most biblical scholars have some familiarity with this term, but most pastors are not biblical scholars.

Pastors train to lead churches, organize members, and read the Bible within their own preconceived denominational creeds. Biblical scholars, the good ones, seek to go beyond the ancient creeds and theological systems to unpeel the layers, and see what the original authors really wanted to communicate to their original audiences.

Biblical scholars look at the texts and archeology of the Ancient Near East (ANE) and Second Temple period. From these texts, they piece together the backgrounds of the biblical authors and of other contemporary cultures that Israel interacted with, influenced, and were influenced by, to try to see what the original audiences were supposed to hear by the words preserved for us.

One of those ideas, common to the entire ANE, is The Divine Council.

#### **What is the Divine Council Worldview?**

You actually know of a later version of this council (though it differs dramatically from the one the biblical authors had in mind).

When you see a Marvel movie, and Odin is holding court on his throne, that is a Divine Council.

When you watch a Percy Jackson film, and see Zeus holding court with the other gods, that is a Divine Council.

Unlike those, Yahweh stands alone, species unique, among the elohim. Yahweh is an elohim, but no other elohim is Yahweh. For the biblical authors, Yahweh is the only creator and ruler of all things. But he still rules through a council, and the rebel council members are a part of why the earth is so bad. Genesis 1-11 (not just Genesis 3) is the opening prologue and each word of it resonates throughout the remaining biblical author's imaginations as they weave the story they want you to hear.

In a nutshell, the Divine Council Worldview refers to the concept that God chooses to work (in heaven and earth) through divine representation. He likes to work with others. Once you understand the languaging around this concept, you begin to see that the story of Creation was God creating humankind to co-rule with them. He had a council in heaven, now he was creating one on earth.

Genesis 1-11 is about the rebellion of both humans and elohim (a name for a class of being, not a specific name for the one true God).

The Heavenly Divine Council is most obvious to modern readers in the opening of Job, God has his heavenly council/advisor staff coming and going ([Job 1 (LEB)](https://ref.ly/logosres/leb?ref=BibleLEB2.Job1.6-12&off=0&ctx=o+%E2%8C%8Aall+the+time%E2%8C%8B.k+%0a~6%C2%A0And+it+happened+%E2%8C%8Ao)). One that many may skim right over is in the fall of Ahab, and a Yahweh asks his Divine Council how he should proceed, and a spirit offers an idea, and Yahweh agrees to the idea ([2 Chronicles 18 (LEB)](https://ref.ly/logosres/leb?ref=BibleLEB2.2Ch18.16-22&off=0&ctx=he+name+of+Yahweh%3f%E2%80%9D+~16%C2%A0Then+he+said%2c+%E2%80%9CI+)). These are the "powers" Paul, Peter, and the author of Hebrews refer to are rulers, authorities, thrones, of this present age ([Romans 8:38](https://ref.ly/logosres/leb?ref=BibleLEB2.Ro8.38), [Colossians 1:16](https://ref.ly/logosres/leb?ref=BibleLEB2.Col1.16), [Hebrews 6:5](https://ref.ly/logosres/leb?ref=BibleLEB2.Heb6.5), [1 Peter 3:22](https://ref.ly/logosres/leb?ref=BibleLEB2.1Pe3.22&off=93)).

Some scholars argue for understanding the Sun, Moon, and Stars in Genesis One as a Divine Council concept, as these images get played as Divine Council members throughout the Hebrew scriptures. A common phrase looked at in American churches when talking about "Satan" is a quote from Isaiah "'I will ascend to heaven; I will raise up my throne above the stars of God; and I will sit on the mountain of assembly..." ([Isaiah 14 (LEB)](https://ref.ly/logosres/leb?ref=BibleLEB2.Is14.12-14&off=0&ctx=overing+is+worms.g+%0a~12%C2%A0How+you+have+fall)).

*"The term divine council is used by Hebrew and Semitics scholars to refer to the heavenly host, the pantheon of divine beings who administer the affairs of the cosmos. All ancient Mediterranean cultures had some conception of a divine council. The divine council of Israelite religion, known primarily through the psalms, was distinct in important ways."*

[Michael S. Heiser, "Divine Council,"](https://www.thedivinecouncil.com/) in Dictionary of the Old Testament: Wisdom, Poetry & Writings (ed. Tremper Longman III and Peter Enns; Downers Grove, IL; Nottingham, England: IVP Academic; Inter-Varsity Press, 2008), 112.

Dr. Heiser is the best selling author of Th[](https://www.amazon.com/gp/product/1577995562/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=1577995562&linkCode=as2&tag=drmicsheihom-20&linkId=743ca36c3513d4cc1d5a23cf46ca79c5), which focuses on the divine council worldview of the biblical writers.

It sounds crazy to many modern western ears, but if you check out the materials below, you can decide for yourself. I will end by sharing some important passages. These are not the only Divine Council passages, but they are a start to understanding the concept. Once you see it, it is everywhere in the biblical pages.

#### **Resources on Divine Council**

A quick video breakdown of the concept can be found at The BibleProject

- <https://bibleproject.com/explore/video/divine-council>/

The scholar most famous for his work on this subject is Dr. Michael Heiser's works:

- [https://www.thedivinecouncil.com](https://www.thedivinecouncil.com/)/
- [https://drmsh.com](https://drmsh.com/)/
- <https://nakedbiblepodcast.com/episodes>/

And this YouTube link to his Supernatural Conference at Celebration Church

- <https://www.youtube.com/watch?v=iHNRNoZYKzU>

# An error occurred.

Unable to execute JavaScript.

#### **Here are some important passages related to the Divine Council:**

#### [Deuteronomy 32 (LEB)](http://ref.ly/logosres/leb?ref=BibleLEB2.Dt32.1-47)

**The Song of Moses**

**32 ** "Give ear, O heavens, and I will speak,

and let the earth hear the words of my mouth.

**2 **May my teaching trickle like the dew,

my words like rain showers on tender grass,

and like spring showers on new growth.

**3 **For I will proclaim the name of Yahweh;

ascribe greatness to our God!

**4 **The Rock, his work *is* perfect,

for all his ways *are* just;

*he is* a faithful God, and ⌊without injustice⌋;a

righteous and upright *is* he.

**5 **They *have* behaved corruptly towardb him;

*they are* not his children; *this is* their flaw,

a generation crooked and perverse.

**6 ***Like* this do you treat Yahweh,

foolish and ⌊unwise⌋c people?

*Has* he not, your father, created you?

He made you, and he established you.

**7 **Remember *the* old days, ⌊the years long past⌋;d

ask your father, and he will inform you,

your elders and they will tell you.e

**8 **⌊**When the Most High apportioned⌋f *the* nations,**

**at his dividing *up* of the sons of humankind,**

**he fixed the boundaries of *the* peoples,**

**according to the number of the sons of God.g**

**9 For Yahweh's portion *was* his people,**

**Jacob the share of his inheritance.**

**10 **He found him in a desert land,

and in a howling, desert wasteland;

he ⌊encircled him⌋,h he cared for him,

he protected him like the ⌊apple⌋i of his eye.

**11 **As an eagle stirs up its nest,

hovers over its young,

spreads out its wings, takes them,j

carries themk on its pinions,l

**12 ***so* Yahweh alone guided him,m

and ⌊there was no foreign god accompanying him⌋.n

**13 **And he set him on the high places of *the* land,

and he fed *him* the cropso of *the* field,

and he nursed him with honey from crags,p

and *with* oil from flinty rock,

**14 ***With* curdsq from *the* herd,

and *with* milk from *the* flock,

with *the* fat of young rams,

and rams, the offspring of Bashan,

and with goats *along* with the finest kernels of wheat,

and *from* the blood of grapesr you drank fermented wine.s

**15 **And Jeshurun grew fat, and he kicked;

you grew fat, you bloated, and you became obstinate;

and he abandoned God, his maker,

and he scoffed *at* the rock of his salvation.

**16 **They made him jealous with strange *gods*;

with detestable things they provoked him.

**17 **They sacrificed to the demons, not God,

*to* gods whomt they had not known,

new *gods* *who*u came from recent times;

⌊their ancestors had not known them⌋.v

**18 ***The* rock whow bore you, you neglected,

and you forgot God, *the one* giving you birth.

**19 **Then Yahweh saw, and he spurned *them*,

because of the provocation of his sons and his daughters.

**20 **So he said, 'I will hide my face from them;

I will see what *will be* their end,

for they *are* a generation of perversity,

⌊children in whom there is no faithfulness⌋.x

**21 **They annoyed me with *what is* not a god;

they provoked me with their idols.

So I will make them jealous with *those* not a people,

with a foolish nation I will provoke them.

**22 **For a fire was kindledy by my anger,

and it burned ⌊up to the depths of Sheol⌋,z

and it devoured *the* earth and its produce,

and it set afire the foundation of *the* mountains.

**23 **I will heap disasters upon them;

my arrows I will spend on them.

**24 ***They will become* weakened by famine,

and consumed by plague and bitter pestilence;

and the teeth of wild animals I will send against them,

with *the* poison of *the* creeping *things* in *the* dust;

**25 **From outside *her boundaries* the sword will make *her* childless,

and from inside, terror;

both *for* *the* young man *and* also the young woman,

the infant *along with* the gray-headed man.

**26 **I thought, "I will wipe them out;

⌊I will make people forget they ever existed⌋."a

**27 **If I had not feared a provocation of *the* enemy,

lest their foes might misunderstand, b

lest they should say, c "Our hand is

⌊triumphant⌋,d and Yahweh *did* not do all this." '

**28 **For ⌊they are a nation void of sense⌋,e

and there is not *any* understanding in them.

**29 **If only they were wise, they would understand this;

they would discern ⌊for themselves their end⌋.f

**30 **How could one chase a thousand

and two could cause a myriad to flee,

if their Rock had not sold them,

and Yahweh had *not* given them up?

**31 **For the fact of the matter is,

their rock *is* not like our Rock,

and our enemies recognizeg *this*.

**32 **For their vine *is* from the vine of Sodom,

and from the terraces of Gomorrah;

their grapes *are* grapes of poison;

⌊their clusters are bitter⌋.h

**33 **Their wine *is* the poison of snakes,

and *the* deadly poison of horned vipers.

**34 **'*Is* not this stored up with me,

sealed in my treasuries?'i

**35 **⌊Vengeance belongs to me⌋j and *also* recompense,

⌊for at the time their foot slips⌋,k

because the day of their disaster *is* near,

⌊and fate comes quickly for them⌋.'l

**36 **For Yahweh will judge *on behalf of* his people,

and concerning his servants;

he will change his mind when he sees that *their* power has disappeared,

and *there is* no one left, confinedm or free.n

**37 **And he will say, 'Where *are* their gods,

*their* rock in whomo they took refuge?

**38 **Who ate the fat of their sacrifices

*and* drank the wine of their libations?

Let them rise *up*, and let them help you;

⌊Let them be to you a refuge⌋.p

**39 **See, now, that I, *even* I *am* he,

and there is not a god besides me;

I put to death and I give life;

I wound and I heal;

there is not *one* who delivers from my hand!

**40 **For *indeed* I lift up my hand to heaven,

And I promise ⌊as I live forever⌋,q

**41 **When I sharpenr ⌊my flashing sword⌋,s

and my hand takes holdt *of it* in judgment,

⌊I will take reprisals against my foes⌋,u

and my haters I will repay.

**42 **I will make my arrows drunk with blood,

and my sword shall devour flesh with the blood of the slain,

and captivesv from the headsw of the leaders of *the* enemy.'

**43 **Call for songs of joy, O nations, *concerning* his people,x

for the blood of his servants he will avenge,

⌊and he will take reprisals against his foes⌋,y

and he will make atonement *for* his land, his people."

**44 **And Moses came, and he spokez all the words of this song in the ears of the people; *that is*, he and Joshua the son of Nun. **45 **⌊And when Moses finished speaking⌋a all these words to all Israel, **46 **then he said to them, "⌊Take to heart all the words⌋b that I *am* admonishing *against* you ⌊today⌋c *concerning* which you should instruct them *with respect to* your childrend ⌊so that they will observe diligently⌋e all the words of this law, **47 **for it *is* not a trifling matter among you, but it *is* your life, and through this word ⌊you will live long in the land⌋f that you *are about* to cross the Jordan *to get* there to take possession of it."

- a Literally "there is not injustice"
- b Or "with"
- c Literally "not wise"
- d Literally "*the* years of *from* generation to generation"
- e Hebrew "to you"
- f Literally "In/at the apportioning of the Most High"
- g LXX reads "the number of the angels of God"; Dead Sea Scrolls reads "the number of the sons of God"
- h Literally "moved around him"
- i Literally "pupil"
- j Hebrew "it" but used poetically and with plural sense in context
- k Hebrew "it" but used poetically and with plural sense in context
- l Hebrew "pinion"
- m That is, Jacob, standing for Israel
- n Literally "and there was not with him a god foreign/strange"
- o Hebrew "crop"
- p Hebrew "crag"
- q Hebrew "curd"
- r Hebrew "grape"
- s Or "partially fermented wine"; others translate simply as wine (NASB, NEB); HALOT 330, "still fermenting wine"
- t Hebrew "them"
- u Hebrew "they," understood in the verb form
- v Literally "their fathers not knew them"
- w Hebrew "he," understood in verb form
- x Literally "sons not faithfulness *is* in them"
- y Or "ignited"
- z Literally "up to Sheol depths"
- a Literally "I will blot out from among human being their remembrance"
- b Or "so that they not make a false construal" of what has happened
- c Or "so that they might not"
- d Literally "raised/held high"
- e Literally "they a nation perishing of counsel"
- f Literally "they would discern for end their"
- g The meaning of this expression is uncertain, but "discerns" or "judges" seem good choices; see HALOT 932, which allows for "judges" or "in the estimation of our enemies"
- h Literally "clusters of bitter *are* for them"
- i Or "storehouses
- j Literally "To me *is* vengeance"
- k Literally "at *the* time *when* it shall slip foot their"
- l Literally "and comes quickly/hurries events to come to them"
- m Or "bond/bound"
- n Or "freed"
- o Hebrew "in him"
- p Literally "let there be/him/them unto you *as* a shelter"
- q Literally "live I to eternity"
- r Or "have sharpened"
- s Literally "the flashing of my sword"
- t Or "seizes"
- u Literally "I will let return vengeance to foes my"
- v Hebrew "captive"
- w Hebrew "head"
- x Dead Sea Scrolls reads: "Rejoice, O heavenly ones, with him! Bow down, all you gods, before him!"
- y Literally "vengeance he will let return to his foes"
- z Or "recited"
- a Literally "And *he* finished Moses to speak"
- b Literally "Put heart your to all the words"
- c Literally "the day"
- d Or "sons"
- e Literally "to keep to do"
- f Literally "you will make long days on the land"

W. Hall Harris III et al., eds., *[The Lexham English Bible](https://ref.ly/logosres/leb?ref=BibleLEB2.Dt32.1)* (Bellingham, WA: Lexham Press, 2012), Dt 32:1--47.

[Psalm 82 (LEB)](http://ref.ly/logosres/leb?ref=BibleLEB2.Ps82.title-8)

**82 **A psalm of Asaph.a

**1 God stands in the divine assembly;b**

**he administers judgment in the midst of *the* gods.c**

**2 **"How long will you judge unjustly

and ⌊show favoritism to the wicked⌋?d *Selah*

**3 **Judge *on behalf of the* helpless and *the* orphan;

provide justice *to the* afflicted and *the* poor.

**4 **Rescue *the* helpless and *the* needy;

deliver *them* from the hand of *the* wicked."

**5 **They do not know or consider.e

They go about in the darkness,

*so that* all *the* foundations of *the* earth are shaken.

**6 **I have said,f "You *are* gods,

and sons of the Most High, all of you.

**7 **However, you will die like men,g

and you will fall like one of the princes."

**8 **Rise up, O God, judge the earth,

because you shall inherith all the nations.

- a The Hebrew Bible counts the superscription as the first verse of the psalm
- b Or "assembly of *El* "
- c Hebrew *elohim*
- d Literally "lift up the faces of the wicked"
- e Or "understand"
- f Hebrew "I, I have said"
- g Singular
- h Or "receive an inheritance"

W. Hall Harris III et al., eds., *[The Lexham English Bible](https://ref.ly/logosres/leb?ref=BibleLEB2.Ps82.title)* (Bellingham, WA: Lexham Press, 2012), Ps 82:title--8.

#### [Psalms 89 (LEB)](https://ref.ly/logosres/leb?ref=BibleLEB2.Ps89.title-52&off=67&ctx=+for+Lost+Blessings%0a~89+A+maskil+of+Ethan)

**89 **A maskil of Ethan the Ezrahite.a

**1 **I will sing forever of Yahweh's acts of loyal love.

⌊From generation to generation⌋b

I will make known your faithfulness with my mouth.

**2 **For I say, "Forever *your* loyal love is built up.

*The* heavens you have established *with* your faithfulness in them."

**3 **"I made a covenant with my chosen one;

I swore *an oath* to David my servant:

**4 **'I will establish your descendants forever,

and I will build up your throne ⌊from generation to generation⌋.' "c *Selah*

**5 **And *so the* heavens will praise your wonderful deed, O Yahweh,

even your faithfulness, in *the* assembly of *the* holy ones.

**6 For who in the skyd is equal to Yahweh?**

***Who is* like Yahweh among the sons of God,**

**7 a God feared greatly in the council of *the* holy ones,**

**and awesome above all surrounding him?**

**8 **O Yahweh God *of* hosts,

who *is* mighty like you, O Yah,

withe your faithfulness surrounding you?

**9 **You are ruling the surging of the sea.

When its waves rise, ⌊you yourself still⌋f them.

**10 **⌊You yourself crushed⌋g Rahab like one *who is* slain;

you scattered your enemies with your strong arm.

**11 ***The* heavens are yours, *the* earth yours as well,

*the* world with its fullness, *because* you founded them.

**12 **North and south, you created them;

Tabor and Hermon shout joyfully over your name.

**13 **You have a mighty arm;

Your hand is strong; your right hand reaches high.

**14 **Righteousness and justice *are* the foundation of your throne.

Loyal love and faithfulnessh come before your face.i

**15 **Blessed *are* the people who know *the* joyful shout;

O Yahweh, they walk about in the light of your countenance.

**16 **In your name they rejoice all the day,

and in your righteousness they rise up.

**17 **For you *are* the glory of their strength,

and by your favor our horn rises up,j

**18 **because our shield belongs to Yahweh,k

and our king to the Holy One of Israel.l

**19 **Formerly you spoke in a vision

to your faithful ones, and said,

"I have bestowed help on a mighty man;

I have exalted one chosen from *the* people.

**20 **I have found David, my servant.

With my holy oil I have anointed him,

**21 **with whom my hand will be steadfast.

Surely my arm will strengthen him.

**22 ***The* enemy will not deceive him,

and no ⌊evil man⌋m will afflict him.

**23 **But I will crush his adversaries before him,

and I will strike those who hate him.

**24 **And *so* my faithfulness

and my loyal love *will be* with him,

and in my name his horn will rise up.

**25 **And I will set his hand on the sea

and his right hand on the rivers.

**26 **He will call out *to* me, 'You *are* my Father,

my God, and the rock of my salvation.'

**27 **I will also make him *the* firstborn,

*the* highest of *the* kings of *the* earth.

**28 **Forever I will keep my loyal love for him,

and my covenant *will be* reliable for him.

**29 **I will also establish his offspring forever,

and his throne as *the* days of *the* heavens.

**30 **If his sons forsake my law

and do not walk in my judgments,

**31 **if they defilen my statutes

and do not keep my commandments,

**32 **then I will punish their transgression with *a* rod,

and their guilt with wounds.

**33 **But I will not break off my loyal love from him,

and I will not be false against my faithfulness.

**34 **I will not defileo my covenant,

or alter what proceeded from my lips.

**35 **Oncep I have sworn by my holiness,

'I will surely not lie to David,

**36 **His offspring will endureq forever,

and his throne as the sun before me.

**37 **Like *the* moon it will be steadfast forever,

and *like* an enduring witness in the sky.' " *Selah*

**38 **But you have spurned and rejected;

you are very angry with your anointed one.

**39 **You have repudiated the covenant with your servant;

you have defiledr his crown ins the dirt.

**40 **You have broken down all his walls;

you have made his fortifications a ruin.

**41 **All passing along *the* road plunder him;

he has become a taunt to his neighbors.

**42 **You have raised the right handt of his adversaries.

You have made all his enemies rejoice.

**43 **You have also turned back the edge of his sword

and have not helped him stand *his ground* in the battle.

**44 **You have made his splendor to cease,

and cast his throne to the ground.

**45 **You have cut short the days of his youth;

you have covered him with shame. *Selah*

**46 **How long, O Yahweh? Will you hide yourself forever?

Will your wrath burn like fire *forever*?

**47 **Remember what my lifespan *is*.

*Remember* for what vanity

you have created all *the* children of humankind.

**48 **What man can live *on* and not see death?

Can he deliver his life from the ⌊power⌋u of Sheol? *Selah*

**49 **Where *are* your former acts of loyal love, O Lord,

*that* you swore to David by your faithfulness?

**50 **Remember, O Lord the taunting of your servants,

*how* I bear in my bosom *the taunts of* all *the* many peoples,

**51 ***by* which your enemies taunt, O Yahweh,

*by* which they taunt the steps of your anointed one.

**52 **Blessed be Yahweh forever.

Amen and Amen.

- a The Hebrew Bible counts the superscription as the first verse of the psalm; the English verse number is reduced by one
- b Literally "To a generation and a generation"
- c Literally "To a generation and a generation"
- d Hebrew singular collective "clouds"
- e Hebrew "and"
- f Literally "you, you calm"
- g Literally "You, you crushed"
- h Or "truth"
- i That is, enjoy continual access
- j According to the reading tradition (*Qere*). The *Kethib* reads "you exalt our horn"
- k Or "Yahweh *is* our shield."
- l Or "The Holy One of Israel *is* our king."
- m Literally "a son of wickedness"
- n Hebrew "profane; treat as common"
- o Hebrew "profane; treat as common"
- p Hebrew "One"
- q Hebrew "be"
- r Hebrew "profane; treat as common"
- s Hebrew "to"
- t That is, given them victory
- u Literally "hand""

W. Hall Harris III et al., eds., *[The Lexham English Bible](https://ref.ly/logosres/leb?ref=BibleLEB2.Ps89.title&off=67&ctx=+for+Lost+Blessings%0a~89+A+maskil+of+Ethan)* (Bellingham, WA: Lexham Press, 2012), Ps 89:title--52.

#### [Job 1 (LEB)](https://ref.ly/logosres/leb?ref=BibleLEB2.Job1.6-12&off=0&ctx=o+%E2%8C%8Aall+the+time%E2%8C%8B.k+%0a~6%C2%A0And+it+happened+%E2%8C%8Ao)

**6 **And it happened ⌊one day⌋l ⌊that⌋m the sons of Godn came to present themselves before Yahweh, and Satano also came into their midst. **7 **Sop Yahweh said to Satan,q "From where have you come?"

Thenr Satans answered Yahweh and said, "From roaming on the earth and from walking about in it."

**8 **Sot Yahweh said to Satan,u "Have you ⌊considered⌋v my servant Job? Indeed,w there is no one like him on the earth---a blameless man and upright and God-fearing and turning away from evil."

**9 **Thenx Satany answered Yahweh and said, "Does Job fear God for nothing? **10 **Have youz not put a fence around him and his household and around ⌊all that belongs to him⌋a ⌊on every side⌋?b You have blessed the work of his hands, and his livestockc has increased in the land. **11 **But,d on the other hand, stretch oute your hand and touch ⌊all that belongs to him⌋f *and see* ⌊whether⌋g he will ⌊curse⌋h you to your face."

**12 **Soi Yahweh said to Satan,j "Look, ⌊all that belongs to him⌋k is in your ⌊power⌋.l Only do not stretch out your hand ⌊against⌋m him." Son Satano went out from Yahweh's ⌊presence⌋.p

- l Literally "the day"
- m Literally "and"
- n Or "the heavenly beings," or "the angels"
- o Hebrew "the accuser," or "the adversary"
- p Hebrew "And"
- q Hebrew "the accuser," or "the adversary"
- r Hebrew "And"
- s Hebrew "the accuser," or "the adversary"
- t Hebrew "And"
- u Hebrew "the accuser," or "the adversary"
- v Literally "set your heart"
- w Or "For," or "Because"
- x Hebrew "And"
- y Hebrew "the accuser," or "the adversary"
- z Emphatic personal pronoun could be translated "you yourself"
- a Literally "all that *is* his"
- b Literally "from around"
- c Or "possessions"
- d Hebrew "And"
- e Or "please"
- f Literally "all that *is* his"
- g Literally "if not"
- h Literally "bless"--- negative meaning by context
- i Hebrew "And"
- j Hebrew "the accuser," or "the adversary"
- k Literally "all that *is* his"
- l Literally "hand"
- m Literally "to," or "unto"
- n Hebrew "And"
- o Hebrew "the accuser," or "the adversary"
- p Literally "faces of"

W. Hall Harris III et al., eds., *[The Lexham English Bible](https://ref.ly/logosres/leb?ref=BibleLEB2.Job1.6&off=0&ctx=o+%E2%8C%8Aall+the+time%E2%8C%8B.k+%0a~6%C2%A0And+it+happened+%E2%8C%8Ao)* (Bellingham, WA: Lexham Press, 2012), Job 1:6--12.

#### [2 Chronicles 18 (LEB)](https://ref.ly/logosres/leb?ref=BibleLEB2.2Ch18.16-22&off=0&ctx=he+name+of+Yahweh%3f%E2%80%9D+~16%C2%A0Then+he+said%2c+%E2%80%9CI+)

**16 **Then he said, "I saw all Israel scattered upon the mountains like sheep that had no shepherd. And Yahweh said, 'These have no masters; let each of them return to his own house in peace.' " **17 **Then the king of Israel said to Jehoshaphat, "Did I not say to you he would not prophesy good concerning me, but only disaster?" **18 **Then Micaiah said, "Therefore hear the word of Yahweh: I saw Yahweh sitting upon his throne with all the host of heaven standing on his right and on his left. **19 **And Yahweh said, 'Who will entice Ahab the king of Israel that he would go up and fall at Ramoth-Gilead?' And one said this, and another said that. **20 **Then a spirit came forth and stood before Yahweh and said, 'I will entice him.' Then Yahweh said to him, 'By what means?' **21 **Then he said, 'I will go forth and will be a lying spirit in the mouth of all his prophets.' And he said, 'You will entice him and will also succeed. Go out and do so.' **22 **So now, behold, Yahweh has put a spirit of deception into the mouths of these your prophets. Yahweh has spoken disaster against you."

W. Hall Harris III et al., eds., *[The Lexham English Bible](https://ref.ly/logosres/leb?ref=BibleLEB2.2Ch18.16&off=0&ctx=he+name+of+Yahweh%3f%E2%80%9D+~16%C2%A0Then+he+said%2c+%E2%80%9CI+)* (Bellingham, WA: Lexham Press, 2012), 2 Ch 18:16--22.

#### [Isaiah 14 (LEB)](https://ref.ly/logosres/leb?ref=BibleLEB2.Is14.12-14&off=0&ctx=overing+is+worms.g+%0a~12%C2%A0How+you+have+fall)

**12 **How you have fallen from heaven, morning star, son of dawn!

You are cut down to the ground, conqueror of nations!

**13 **And you yourself said in your heart,

'I will ascend *to* heaven;

I will raise up my throne above the stars of God;

and I will sit on *the* mountain of assembly

on the summit of Zaphon;h

**14 **I will ascend to *the* high places of *the* clouds,i

I will make myself like the Most High.'

- h Or "of the north"
- i Hebrew "cloud"

W. Hall Harris III et al., eds., *[The Lexham English Bible](https://ref.ly/logosres/leb?ref=BibleLEB2.Is14.12&off=0&ctx=overing+is+worms.g+%0a~12%C2%A0How+you+have+fall)* (Bellingham, WA: Lexham Press, 2012), Is 14:12--14.

**Darrell Wolfe, [Storyteller at NoHiding.Faith](http://www.nohiding.faith/p/blog-page.html)**
