---
title: 'Class Assignment: REFLECTION: IS PAUL THE FATHER OF MISOGYNY AND ANTISEMITISM? BY PAMELA EISENBAUM'
date: '2022-03-03T07:05:00.0060000+00:00'
draft: false
categories:
  - 'Class Assignment'
---
THE KING'S UNIVERSITY (TKU)

REFLECTION: IS PAUL THE FATHER OF MISOGYNY AND ANTISEMITISM? BY PAMELA EISENBAUM

REFLECTION PAPER SUBMITTED TO PROFESSOR DR. VERED HILLEL FOR THE NEW TESTAMENT AND SECOND TEMPLE JUDAISM (BIBL2325ONL1).

BY

DARRELL WOLFE

SOUTHLAKE, TEXAS, ONLINE VIA NORTH POLE, IDAHO

FEBRUARY 2022

# Introduction

This is a reflection paper on the article "Is Paul the Father of Misogyny and Antisemitism?", by Pamela Eisenbaum, which originally appeared as a paper delivered in November 1999 at Temple Emanu-El and was republished as an article in Cross Currents.[\[1\]](#_ftn1)

Early in the article, while setting the stage of current views on Paul, Eisenbaum lists several pairs of Pauline phrases that appear to be contradictory (Eisenbaum, 509). While many find contradictions in these phrases at a surface reading, I do not. I find them perfectly reasonable and consistent from a long view that Paul was not breaking away from Judaism at all but expressing its most authentic truths. His discussions on "law" are not a rebuke of Jews or even Judaism but on its expression in certain sub-sects of his day or even (as she noted in her article) how they separate Jews from Gentiles. Likewise, "justification" has nothing to do with "going to heaven when we die" but is a phrase specifically aimed at "justifying" Gentiles to enter into fellowship with Yahweh's covenant people. Justification is an ethno-religious phrase, not a phrase about sins before an angry God and going to heaven. These are intra-Jewish Rabbinic debates, not polemics against a 'religion he had converted away from' as some might say.

Therefore, Eisenbaum and I both seem to agree that these common readings are misunderstanding Paul's work. The article displays the various ways many have misunderstood and misused Paul's statements (on all sides). Boyarin sees Paul as the father of misogyny and antisemitism. While this is not an historically authentic reading of what Paul meant, it is an historically authentic reading of what subsequent people have used Paul's words to do implement.

Eisenbaum agrees with Boyarin that Paul sees each of the paired terms as having a clearly desired status (Jew, Free, Male, which are all Paul) and argues for the idea that there is "no such thing as human essence that is truly universal" (Eisenbaum, 514). The "essence" of human is to be Yahweh's Image Bearer, which is a topic for another paper but something she did not seem to pick up on in her article.

In regard to the pairings, I did not see any convincing argument for seeing Paul's statements as a call for a 'desired status' in the pairs. However, I agree with Eisenbaum that Paul was not trying to erase all differences either. One can appreciate and even celebrate difference while still arguing for erasing these boarders in other senses. In each pairing, Jew/Greek, Male/Female, Slave/Free a social barrier is in view. In each pairing, one party was subjected to another or played a non-dominant role in society.

Paul was arguing for just the opposite of what both Eisenbaum and Boyarin see in his pairs. Paul was arguing that these statuses no longer define participation in the Kingdom of Yahweh under the Lordship of Yeshua. For Paul, the status of an individual in the Kingdom (what one could do or be in God's Kingdom) was determined only by their status as Sons and Daughters of the Most-High. For Paul, the slave (Philemon) was now a dear brother. When it comes to a sense of vagueness from Paul (for example, he doesn't outright condemn slavery), one must contextualize the situation. In the first century, an abolitionist movement would have been culturally unthinkable. However, as NT Wright phrased his view, "he (Paul) puts a time-bomb beside it... the letter to Philemon is an extraordinary time-bomb on the subject."[\[2\]](#_ftn2) By equating slaves with their masters as brethren, the power of master of slave is extinguished, and diminished, and over time loses its power until it eventually becomes (in the modern era) unthinkable. While developed nations don't have slaves any longer, we have employee/employer relationship, and the same rules apply. While the status exists, the relationship is that of brothers and sisters serving each other (not over domineering one over the other). The very existence of these pairs is acknowledgement of their differences while also elevating them as co-equals. Likewise, the idea that "only males can lead" should be as unthinkable as having slaves, but portions of the church haven't caught up to this and even use Paul to justify this when he himself laid the groundwork to dismantle it.

The point, for Paul, was that neither of the pair was a second-class citizen. He was elevating all to co-equals (observing their differences but equating their value). Eisenbaum comes to this conclusion herself, "Perhaps one cannot or should not change one's social or ethnic status, but Paul strongly advocates changing the relationships between people of different status" (Eisenbaum, 515).

Eisenbaum observes:

"...that is why it is important to remember that Paul writes as a Jew, more specifically a Jewish man, addressing Gentiles. Paul calls himself the apostle to the Gentiles (Gal. 1:16; 2:9), because he founded Gentile congregations; Gentiles are consistently Paul's primary concern... But Paul's comments on circumcision in this letter were originally directed to Gentiles only\... In other words, Paul's message to the Galatians advocates the inclusion of Gentiles as Gentiles" (Eisenbaum, 517-518).

"The rejection of circumcision for which Paul is so well known derives from Paul's respect for Gentiles, not his disrespect for Judaism." (Eisenbaum, 518).

The interplay between Galatians 3:28 and Genesis 1:28 ("Male and Female") acts as a hyperlink for the reader, taking them back to first creation in light of new creation. This becomes Paul's hermeneutic for interpreting the other differences (Jew/Greek, Slave/Free). We are all becoming one family that while "different" is both complementary and co-equal in our uniqueness. She concludes with a Pauline aspirational goal, "people who are different can, if they so choose, come to understand themselves as meaningfully related to each other, committed to their well-being, and part of a shared world" (Eisenbaum 518-521).

------------------------------------------------------------------------

[\[1\]](#_ftnref1) PAMELA EISENBAUM, "Is Paul the Father of Misogyny and Antisemitism?," *CrossCurrents* 50, no. 4 (2000): 506--24.

[\[2\]](#_ftnref2) N.T. Wright and Justin Brierley, "Ask NT Wright Anything Podcast," Premier Christian Radio, Time: 23:40/31:26-Ask NT Wright Anything #7 Bible infallibility, Sola Scriptura and slavery-https://www.premierchristianradio.com/Shows/Weekday/Ask-NT-Wright-Anything/Podcast/Ask-NT-Wright-Anything-7-Bible-infallibility-Sola-Scriptura-and-slavery, accessed April 6, 2021, https://www.premierchristianradio.com/Shows/Weekday/Ask-NT-Wright-Anything/Podcast.
