---
title: 'Class Assignment: I Follow a Jewish Rabbi: Exploring what it means to be a Gentile follower of Yeshua HaMashiach (Jesus the Anointed One)'
date: '2022-10-10T02:55:00.0020000+00:00'
draft: false
categories:
  - 'Class Assignment'
---
The King's University (TKU)

# I Follow a Jewish Rabbi:

### Exploring what it means to be a Gentile follower of Yeshua HaMashiach (Jesus the Anointed One)

Final Thesis Paper Submitted to Professor Jennifer M. Rosner, PhD for The Shape of Messianic Jewish Theology (BIBT2310)

By Darrell Wolfe

Southlake, Texas, Online Via North Pole, Idaho

Due: October 9, 2022

### Thesis

A casual review of the current trends in social media revealed at least two common narratives for those claiming to "follow Jesus"; [1] yet, these are incompatible and mutually exclusive. Some claim Jesus is a hippie-like character who *just* wants us to love each other, accept each other, and who would never ask anyone to change their lifestyle, habits, or attitudes (unless it is to be more "loving and accepting"). Still others claim he is a militant king-like character who is empowering them to wage a "culture war" on behalf of righteousness, to be won at all costs. This second group is often heard to say, "Win the nation back to Jesus" and "Make America Great Again". A rising third group, into which this author falls, expresses a feeling of "homelessness" and an inability to reconcile either of the dominate views with the record left to us by the biblical authors (those who had been with him). We seek a third way, often called Deconstruction (or as I have come to call it, Exvangelical Reconstruction).[2]

It is at this point in the dialogue Messianic Jewish Theology enters the discussion; along with related comparative studies into the influences upon the biblical authors of the Ancient Near East (ANE) and Second Temple Judaism in its Greco-Roman context. These studies reveal Jesus as Yeshua of Nazareth, a Jewish Rabbi in first-century Palestine, whose followers upended the world in the wake of his death, resurrection, and ascension. This leaves us with a question: What does it mean for moderns (especially gentiles) to follow the Jewish Messiah today? This paper argues that following Yeshua means (*at least*) to (1) be saturated in the texts of the Tanakh and B'rit Chadashah; (2) building the kingdom of God through Spirit-filled *koinonia*-culture, and (3) look forward to The Return of the King and New Creation.

### The Tanakh (Christian: Old Testament)

The Hebrew Bible (Tankah) is comprised of the same books as the Christian Old Testament; however, they are presented differently. The books are arranged in a different order, go by their Hebrew names, and in some cases may be combined to account for a different number of books (with the same content). The Tanakh is a Hebrew acronym for the Torah (instructions), the Nevi'im (Prophets), and the Ketuvim (Writings).[3] Yeshua referred to this literary structure as, "the law of Moses, and the prophets, and psalms" (Luke 24:44-49). Psalms was the first book of the third section and thereby the designation for that section. Torah can refer to the entire collection, but usually refers to the first five books of Moses. While the Tanakh certainly contains "laws" (613 to be exact), it is primarily a story; a narrative. By understanding this one point, the entire narrative (and meta-narrative) comes alive. Sailhammer's *magnum opus* was showing these narrative links within the Torah.[4] Building on Sailhammer's work, Tim Mackie and Jon Collins have amassed a library of videos to help us understand the Bible as a "unified story that leads to Jesus" with "hyperlinks" to themes throughout the Tanakh and B'rit Chadashah.[5] Rosner calls this, The Biblical Drama.[6]

#### The Biblical Meta-Narrative

In the beginning God said, "Let us make humankind (אדם, adam) in our image (צלד, *tseled*)... let them rule (רדה,dominate, rule), (Ge 1:1, 26-30; LEB)"[7] Carmen Imes's work shows the original calling of humankind was to be co-rulers with Yahweh, acting as his *tseled* Imagers, or re-presentation, or representatives, to creation.[8] This word *tseled* is the word for "idols".[9] Humankind was not to create images to worship because God had already created an image for himself, and it was humankind. Humans are his Imagers, bearing the name YHWH.

As the first humans failed, God promised that the offspring of Eve would "crush" the serpent's head and that the serpent would "strike him on the heel" (Gen 3:15). The work of Michael Heiser show that this serpent (*nachash*) was no ordinary snake, but a supernatural being, a member of God's Divine Council, and a throne guardian (*cherub*). He then goes on to argue that Genesis 1-11 tells of three rebellions involving fallen spirit-beings (*elohim*) and humankind.[10]

As a result of this final rebellion, Yahweh "divorced the nations" at Babel and chose a single human (*Avram*/Abram; later Abraham) to be his new representative to creation order (Gen 11, Deut 32:8; Ps 82, 89).[11] The expressed goal in this new partnership was that "all the families (nations) of the earth will be blessed" (Gen 12:1-2). As Avraham's descendants are taken from Egypt up to Canaan, they are given an assignment to be "a kingdom of priests and a holy nation" (Ex 19:3-6). The vision of Israel is that they would be the world-wide priests and a nation set-apart from other nations. This covenant with Abraham to make him the "father of a multitude of nations" is an "everlasting covenant" which can never change; and involves the land of Canaan as an "everlasting property" to Abraham's descendants (Gen 17:1-8). The work of Yahweh through Abraham's offspring will bless the nations and make Abraham the father of them all, while preserving the uniqueness of Israel (ethnic and land) as God's set-apart nation. Jacob (Abraham's grandson) blessed his twelve sons, and he said that the "scepter shall not depart from Judah nor the ruler's staff between his feet until Shiloh comes. And to him shall be the obedience of the nations" (Gen 49:10); promising an everlasting kingship from the house of Judah to reign over the nations from Judah.[12]

Throughout the story of Yisrael, the covenant was repeatedly broken; yet despite this, the prophets spoke of a day when God would make a "new covenant" with the divided kingdoms of Yisrael (Israel) and Yehuda (Judah); which would give them a "new heart" and "new spirit" (Je 31:31--34; Eze 11:17--20; 36:24--32). Along with this promise of a new covenant, came a promise of a Messiah. Rose explains, "From the earliest traditions of Jewish and Christian exegesis onward, students of the Pentateuch have found references to the Messiah ... the conflict between the woman and the *serpent (Gen 3:15), the scepter that shall not depart from *Judah (Gen 49:8--12), the star and scepter coming from *Jacob/Israel (Num 24:17--19) and the *prophet like *Moses whom the Lord will raise up (Deut 18:18--19)."[13]

### The B'rit Chadashah: The New Covenant (Christian: New Testament)

The B'rit Chadashah can also be understood in three parts: The Gospels, The Epistles, and the Apocalypse (Revelation) of Yeshua. While written in Greek, these writings should be understood as Jewish literature written within a context of Second Temple Judaism. During this period, the Rabbis developed a technique called "stringing pearls", in which they would quote or allude to a passage in the Tanakh as they taught.[14] As we study the B'rit Chadashah we see that not only did Yeshua employ this practice, but all the authors did so as well.[15] Before we can look at Yeshua directly, we must dispense with two common misconceptions employed by modern Christianity's use of the Bible: the term "Fulfilled" and (2) the term "Gospel". Here, again, Jewish scholarship lends us a hand.

#### The B'rit Chadashah as Tanakh "Fulfilled"

When modern western Christians use the phrase "Jesus fulfilled" they typically mean that the scriptures "predicted something" and Jesus did the thing that was predicted, even sometimes inferring it was now meaningless except as a prediction of Jesus. However, when the biblical authors say that Yeshua fulfilled a given passage, they mean to say that he became the fullness of that passage; that he gave it new breath, new meaning, and new depth. Juster phrases this as Yeshua's capacity to "fill-full" the meaning of Torah.[16] Spangler and Tverberg show an example of this in Jewish idioms, "concerning 'abolishing' and 'fulfilling' the law. To 'fulfill' a law could simply mean doing what is says. But when Jesus contrasts 'fulfilling' with 'abolishing' the law, you know he is employing a rabbinic idiom... When rabbis disagreed, they would accuse each other of 'nullifying' the Torah (Mark 7:11-12)."[17] Kinzer takes this concept further to describe Jesus's entire life's work, "Yeshua the Nazarene is the fulfillment of Judaism. He is the Jew *par excellence*, the personal embodiment of the people of Israel... This is the key to interpreting the great Suffering Servant passage of Isaiah 53 -- the servant refers both to the people of Israel (as Jewish interpretation states) and to a personal Messiah (as the Christian interpretation states)."[18]

#### The Gospel

Many modern Christians preach a message about believing on Jesus so "you can go to heaven when you die." This makes a trip to the gospel narratives confusing as this message is all but absent from the narratives. When Yeshua steps onto the scene in first-century Palestine, Israel is living under centuries of foreign rule. In Second Temple Judaism's Greco-Roman context, the concept of Messiah becomes blended with a would-be messiah figure in Greco-Roman culture, Caesar (see John 19:15). Yeshua had one dominant theme throughout his teaching ministry; he said, "Repent, because the kingdom of heaven is near" and "the time is fulfilled and the kingdom of God has come near" as he preached "the good news of the kingdom of God" and helped others "see the kingdom of God" (Mat 4:17; Mk 1:14; Lk 4:43; Jn 3:5; Jn 1:49).[19] The "gospel" is the good news that the Kingdom of God came through Yeshua.

### The Way of Yeshua

#### Who was Rabbi Yeshua (Hebrew: יֵשׁוּעַ yēšûaʿ; Greek: Ἰησοῦς Iēsous; English: Jesus)?

            First, we must say that Jesus was a Jew. This is not always as obvious to modern Christianity as it should be, with the medieval artwork depicting Jesus as a Caucasian. Friedman summarizes the observations of Jesus' Jewishness, "We have seen ample evidence from the four Gospels that Yeshua was a Jewish man who lived his earthly life in absolute loyalty to the sacred covenants that God made with his people, Israel. Yeshua was a Torah-observant Jewish man."[20]

Second, it is also helpful to understand Yeshua is in his Jewish role as Rabbi of a band of disciples. Chilton notes that, "Jesus is addressed in the Gospels as 'rabbi' more often than with any other designation; it is obviously what his followers called him (Matt 26:25; 49)"[21] Nässelqvist explains, "In the Greek world, philosophers, religious leaders, and mystery cults attracted disciples. A person became a disciple as he sought out a teacher and followed him and his principles. Similarly, in the rabbinical tradition, a "learner" or "student" (תלמיד, tlmyd) attached himself to a rabbi (literally "my great one," with the additional meaning of "teacher" or "master") or to a movement. Followers of Old Testament prophets could also be described as disciples."[22] Spangler and Tverberg expand on this theme by saying, "Jesus lived transparently in front of his disciples in order to teach them how to live. They, in turn, were to live transparently before others, humbly teaching them the way of Christ. This approach involves not just information but transformation."[23]

When we see Yeshua as a Rabbi and compare his teaching with other rabbinic literature and the Tanakh, we see new depths meaning. Thiessen provides an example, "the use of running water, or what later rabbis referred to as 'living water' (*mayim hayyim*), suggests that John was concerned with using the strongest form of water purificant available to humans."[24] When Yeshua then says that he would have "given you living water" or that "out of his belly will flow rivers of living water" we see reference to this Jewish idiom (John 4:10-11; 7:38). We also see these phrases flowing in the Tanakh where Yahweh calls himself the "source of living water" and promises that one day "living waters will flow out from Jerusalem" (Jer 2:13; 7:13; Zech 14:8; cf. Rev 7:17). This leads to the aforementioned promise of a "new spirit" (Je 31:31--34).

#### Building God's Kingdom: HaRuach HaKodesh (the Holy Spirit) and koinonia-culture

            Just before Yeshua ascended to his throne, he instructed his disciples to not "depart from Jerusalem" until they received the Holy Spirit (Acts 1:4-8). As the Holy Spirit arrived and filled the first followers, Peter preached a sermon and 3,000 people joined them in a movement called, the Way. Luke then summarizes the entire story yet to unfold in Acts with a description of this group gathering frequently in the Temple courts and house to house while they devoted themselves to listening to teaching of the Apostles and to a *koinonia*-culture which was comprised of sharing meals and resources; and praying in regular rhythms. As I argued elsewhere, this *koinonia*-culture became the defining attribute of, the Way.[25] In summary of my other work, the term *koinonia* (often translated: fellowship) runs deeper than simply meeting often. This term, which Luke's Acts uses to define the culture of the early Yeshua followers, is a term which means that they were "one as we are one" (John 17:20-26). They shared meals frequently and used these meal-meetings as occasion to take care of the needs of the poorest in the community. They sold property (sometimes) and gave to those who had needs. They operated as a single living organism, not as disjointed and disconnected event attendees. Oliver observed that "For Luke, Israel's regathering begins as Jews and Samaritans embrace the same messiah and one another as neighbors, that is, fellow Israelites." This sense of one-ness expanded to the gentiles through Peter and later through Saul-Paul.

While the specifics of first-century Palestine may not apply in our modern contexts, the wisdom we can see from their story should inspire us to adopt their mindset and heart toward building thriving and vibrant communities in our context. Pulling from Rabbinic literature, Chilton observed that "*harara*" (needle) in Luke 18:24 opens the possibility of a fascinating interpretation, "a camel that passes through the eye of a needle is no longer a camel, and a rich man who enters the kingdom is no longer wealthy. By the time he has heeded the availability of the kingdom, he has put aside business to concern himself with the single royal invitation."[26] The early Yeshua followers found a way to live out Yeshua's teachings about the kingdom of God by developing this *koinonia*-culture. But they ultimately looked forward to his return.

#### The Return of the King

While J.R.R. Tolkien detested allegories, he enjoyed pursuing the truths of the Christian faith through his narratives. Tolkien rightly alluded to the central hope of the biblical authors by naming his third installment, The Return of the King.[27] Yeshua's disciple, Nathaniel, recognized him by saying, "Rabbi, you are the Son of God! You are the king of Israel!" (Jn 1:49).[28] Harrington observes that, "In referring to Jesus, Matthew used the common stock of honorific titles that emerged early in the Jesus movement: Son of David, Servant, Son of God, Messiah, Son of Man, Lord, Wisdom, and Prophet. But he gave them particularly Jewish spins. As the Son of David, Jesus is the royal Messiah sent to Israel."[29]

As Yeshua ascended to his kingly throne, he affirmed his kingly status "all authority in heaven and on earth has been given to me" and then gave his followers a commission to "make disciples of all nations" (Mat 28:18-20); his disciples became rabbis themselves. Maile provides an important note about the "ascension" of Jesus, "The exaltation of Jesus Christ and his enthronement at the right hand of God is a significant theme in Pauline christology. They are not merely a part of that christology but form the essential core which gives significance to everything else."[30] Noble argues for understanding the Way described in Acts as living out the Greek idea of a "Golden Age", implying a political counter-narrative to Caesar's claim to divine authority.[31]

As the Way carried on with its mission, they saw themselves as building the kingdom of God "on earth as it is in heaven" (Mat 6:9-13). On this subject, NT Wright built his career and concludes, "Let's be quite clear on two points. First, God builds God's kingdom. But God ordered his world in such a way that his own work within that world takes place not least through one of his creatures in particular, namely, the human beings who reflect his image... Second, we need to distinguish between the final kingdom and the present anticipations of it..."[32]

The B'rit Chadashah ends with John's Revelation of Jesus. Written in the genre of Second Temple Apocalyptic literature, he tells the entire story of Israel and the work of Yeshua in colorful imagery with multiple allusions to the Tanakh.[33]

### Conclusion

As I consider all that was said in light of the two groups I discussed at the beginning, I find the following to be true. The Kingdom of God has very real impacts on our very real world (shared meals, resources, care of the poor), which includes some political implications as our activities may be impacted by political decisions. However, the Kingdom of God has no interest in taking over human Babylonian government systems at this time (that's Yeshua's job after his return).

At the same time, being a disciple of a Jewish Rabbi has clear implications of change in view. We are to gradually become less self-centered and more others-centered; but we do this by becoming like our Rabbi, Yeshua. His dealings with both Jewish leaders and individuals showed a clear call to "repent" (change one's mind/attitude/direction) and join the kingdom of God. Neither of those social media narratives reflect accurately the call to Yeshua-faith.

Wright concludes that "The power of the gospel lies... in the powerful announcement that God is God, that Jesus is Lord, that the powers of evil have been defeated, that God's new world has begun."[34] We live this hope for "new Creation" by building communities saturated in the Tanakh and B'rit Chadashah, focused on building the kingdom of God through active participation in *koinonia*-culture, and keeping our hopes set on the Return of the King and the future eschatological ushering in of New Creation.

###  Bibliography

Alexander, T. Desmond, and David W. Baker, eds. *Dictionary of the Old Testament: Pentateuch (DOT: Pentateuch)*. Downers Grove, Ill: InterVarsity Press, 2003.

Chilton, Bruce. *Pure Kingdom: Jesus' Vision of God*. Studying the Historical Jesus. Grand Rapids, Mich. : London: Eerdmans ; Society for Prommoting Christian Knowledge, 1996.

Friedman, David. *They Loved the Torah: What Yeshua's First Followers Really Thought about the Law*. Baltimore, Md: Lederer Books, 2001.

Gesenius, Wilhelm, Charles Briggs, S.R. Driver, and Francis Brown. *The Abridged Brown-Driver-Briggs Hebrew-English Lexicon of the Old Testament: From A Hebrew and English Lexicon of the Old Testament.* Boston; New York: Houghton, Mifflin and Company, 1906.

Hawthorne, Gerald F., Ralph P. Martin, and Daniel G. Reid, eds. *Dictionary of Paul and His Letters*. Downers Grove, Ill: InterVarsity Press, 1993.

Hays, Richard B. *Echoes of Scripture in the Letters of Paul*. New Haven: Yale Univ. Pr, 1989.

Heiser, Michael. "The Naked Bible Podcast." The Naked Bible Podcast. Accessed January 30, 2021. https://nakedbiblepodcast.com/episodes/.

---------. "The Tower of Babel and Holy Ground." *Miqlat.Org* (blog). Accessed October 9, 2022. https://www.miqlat.org/the-tower-of-babel-and-holy-ground.htm.

---------. *The Unseen Realm: Recovering the Supernatural Worldview of the Bible*. First edition. Bellingham, WA: Lexham Press, 2015.

Imes, Carmen Joy. *Bearing God's Name: Why Sinai Still Matters*. Downers Grove, IL: IVP Academic, An Imprint of InterVarsity Press, 2019.

Jones, David. *Old Testament Quotations and Allusions in the New Testament.* Bellingham, WA: Logos Bible Software, 2009.

Juster, Dan. *Jewish Roots: Understanding Your Jewish Faith*. Destiny Image, 2013.

Kinzer, Mark, and Jennifer M. Rosner. *Israel's Messiah and the People of God: A Vision for Messianic Jewish Covenant Fidelity*. Eugene, Or: Cascade Books, 2011.

Mackie, Tim, and Jon Collins. "BibleProject^TM^ Videos and Podcasts." Accessed June 18, 2021. https://bibleproject.com/.

Metcalf, Reed. "Luke-Acts in Jewish Context (BIBL4310)." Lectures, The King's University, Southlake Texas, Fall 2022.

Noble, Joshua. *Common Property, the Golden Age, and Empire in Acts 2:42-47 and 4:32-35*. Bloomsbury Publishing, 2020.

Perrin, Nicholas, Jeannine K. Brown, and Joel B. Green. *Dictionary of Jesus and the Gospels (DJG)*. IVP Bible Dictionary Series. Downers Grove, Ill: IVP Academic, 2013. http://search.ebscohost.com/login.aspx?direct=true&db=nlebk&AN=633424&site=ehost-live.

Rosner, Jennifer. "The Shape of Messianic Jewish Theology (BIBT2310)." Lectures, The King's University, Southlake Texas, Fall 2022.

Rudolph, David J., and Joel Willitts, eds. *Introduction to Messianic Judaism: Its Ecclesial Context and Biblical Foundations*. Grand Rapids, MI: Zondervan, 2013.

Sailhamer, John. *The Pentateuch as Narrative: A Biblical-Theological Commentary*. Library of Biblical Interpretation. Grand Rapids, Mich: Zondervan, 1995.

Sanders, Kirsten Heacock. "You're Not Deconstructing?: What's Behind the Exvangelical Trend Isn't New: But It Sheds New Light on Theology." *Christianity Today* 66, no. 2 (March 2022): 32--37. https://search.ebscohost.com/login.aspx?direct=true&db=lsdar&AN=ATLAi9KZ220228000701&site=ehost-live.

Spangler, Ann, and Lois Tverberg. *Sitting at the Feet of Rabbi Jesus: How the Jewishness of Jesus Can Transform Your Faith*. Updated edition. Grand Rapids, Michigan: Zondervan, 2018.

*The Lexham Bible Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott, C., ... Widder, W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham, WA: Lexham Press.* Billingham, WA: Leham Press, 2016. LexhamPress.com.

*The Lexham English Bible (LEB), Fourth Edition*. Logo Bible Software. Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.). Bellingham, WA: Lexham Press, 2010. http://www.lexhampress.com.

Thiessen, Matthew. *Jesus and the Forces of Death: The Gospels' Portrayal of Ritual Impurity within First-Century Judaism*. Paperback edition. Grand Rapids, Michigan: Baker Academic, a division of Baker Publishing Group, 2021.

Tolkien, J.R.R. *The Lord of the Rings (LOTR)*. The Lord of the Rings Boxed Set (Including a Reader's Companion). London: HarperCollins, 2014.

*Torah Nevi'im U-Khetuvim (Tanakh). The Holy Scriptures According to the Masoretic Text.* Logos. A New Translation. Philadelphia, PA: The Jewish Publication Society of America, 1917.

Wolfe, Darrell. "Author's Note:," n.d.

---------. "Class Assignment: Exegesis of Acts 2:41-47." The King's University, Southlake, Texas, October 9, 2022. https://www.nohiding.faith/2022/10/class-assignment-exegesis-of-acts-241-47.html.

Wright, N. T. *Surprised by Hope: Rethinking Heaven, the Resurrection, and the Mission of the Church*. San Francisco, CA: HarperOne an Imprint of Harper Collins Publishers, 2014.

 Notes

------------------------------------------------------------------------

[1] Darrell Wolfe, "Author's Note:," n.d., n. Reviewed my personal feeds on Twitter, Facebook, and TicTok; paying attention to the posts about Jesus and seeing if they tended toward categories.

[2] Kirsten Heacock Sanders, "You're Not Deconstructing?: What's Behind the Exvangelical Trend Isn't New: But It Sheds New Light on Theology," *Christianity Today* 66, no. 2 (March 2022): 32--37, https://search.ebscohost.com/login.aspx?direct=true&db=lsdar&AN=ATLAi9KZ220228000701&site=ehost-live.

[3] *Torah Nevi'im U-Khetuvim (Tanakh). The Holy Scriptures According to the Masoretic Text.*, Logos, A New Translation (Philadelphia, PA: The Jewish Publication Society of America, 1917).

[4] John Sailhamer, *The Pentateuch as Narrative: A Biblical-Theological Commentary*, Library of Biblical Interpretation (Grand Rapids, Mich: Zondervan, 1995).

[5] Tim Mackie and Jon Collins, "BibleProject^TM^ Videos and Podcasts," accessed June 18, 2021, https://bibleproject.com/.

[6] Jennifer Rosner, "The Shape of Messianic Jewish Theology (BIBT2310)" (Lectures, The King's University, Southlake Texas, Fall 2022), n. Lecture and Handout.

[7] *The Lexham English Bible (LEB), Fourth Edition*, Logo Bible Software, Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010), http://www.lexhampress.com.

[8] Carmen Joy Imes, *Bearing God's Name: Why Sinai Still Matters* (Downers Grove, IL: IVP Academic, An Imprint of InterVarsity Press, 2019).

[9] Wilhelm Gesenius et al., *The Abridged Brown-Driver-Briggs Hebrew-English Lexicon of the Old Testament: From A Hebrew and English Lexicon of the Old Testament.* (Boston; New York: Houghton, Mifflin and Company, 1906), sec. צֶלֶם n.m. image.

[10] Michael Heiser, *The Unseen Realm: Recovering the Supernatural Worldview of the Bible*, First edition (Bellingham, WA: Lexham Press, 2015).

[11] Michael Heiser, "The Tower of Babel and Holy Ground," *Miqlat.Org* (blog), n. quote attributed, accessed October 9, 2022, https://www.miqlat.org/the-tower-of-babel-and-holy-ground.htm.

[12] *The Lexham Bible Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott, C., ... Widder, W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham, WA: Lexham Press.* (Billingham, WA: Leham Press, 2016), n. See: Daniel S. Diffey, "Shiloh,"-SHILOH (שִׁלֹה, shiloh). A city in the hill country of Ephraim, centrally located between Shechem to the north and Bethel to the south. Joshua and the tribes of Israel camped here after the settlement in the land. Home of the ark of the covenant and tabernacle during the time of Joshua to Samuel., LexhamPress.com.

[13] T. Desmond Alexander and David W. Baker, eds., *Dictionary of the Old Testament: Pentateuch (DOT: Pentateuch)* (Downers Grove, Ill: InterVarsity Press, 2003), 565; W. H. Rose, "Messiah,".

[14] Ann Spangler and Lois Tverberg, *Sitting at the Feet of Rabbi Jesus: How the Jewishness of Jesus Can Transform Your Faith*, Updated edition (Grand Rapids, Michigan: Zondervan, 2018), 40--54.

[15] Wolfe, "Author's Note:," n. See the following works for detailed analysis:; Richard B. Hays, *Echoes of Scripture in the Letters of Paul* (New Haven: Yale Univ. Pr, 1989); David Jones, *Old Testament Quotations and Allusions in the New Testament.* (Bellingham, WA: Logos Bible Software, 2009).

[16] Dan Juster, *Jewish Roots: Understanding Your Jewish Faith* (Destiny Image, 2013), 70--71.

[17] Spangler and Tverberg, *Sitting at the Feet of Rabbi Jesus*, 176.

[18] Mark Kinzer and Jennifer M. Rosner, *Israel's Messiah and the People of God: A Vision for Messianic Jewish Covenant Fidelity* (Eugene, Or: Cascade Books, 2011), 13.

[19] Nicholas Perrin, Jeannine K. Brown, and Joel B. Green, *Dictionary of Jesus and the Gospels (DJG)*, IVP Bible Dictionary Series (Downers Grove, Ill: IVP Academic, 2013), sc. For a detiled discussion see: J. B. Green, "Kingdom of God/Heaven," http://search.ebscohost.com/login.aspx?direct=true&db=nlebk&AN=633424&site=ehost-live.

[20] David Friedman, *They Loved the Torah: What Yeshua's First Followers Really Thought about the Law* (Baltimore, Md: Lederer Books, 2001), 43.

[21] Bruce Chilton, *Pure Kingdom: Jesus' Vision of God*, Studying the Historical Jesus (Grand Rapids, Mich. : London: Eerdmans ; Society for Prommoting Christian Knowledge, 1996), 104.

[22] *Lexham Bible Dictionary*, sec. Dan Nässelqvist, "Disciple,."

[23] Spangler and Tverberg, *Sitting at the Feet of Rabbi Jesus*, 69.

[24] Matthew Thiessen, *Jesus and the Forces of Death: The Gospels' Portrayal of Ritual Impurity within First-Century Judaism*, Paperback edition (Grand Rapids, Michigan: Baker Academic, a division of Baker Publishing Group, 2021), 22--23.

[25] Darrell Wolfe, "Class Assignment: Exegesis of Acts 2:41-47" (The King's University, Southlake, Texas, October 9, 2022), https://www.nohiding.faith/2022/10/class-assignment-exegesis-of-acts-241-47.html; Reed Metcalf, "Luke-Acts in Jewish Context (BIBL4310)" (The King's University, Southlake Texas, Fall 2022).

[26] Chilton, *Pure Kingdom*, 77.

[27] J.R.R. Tolkien, *The Lord of the Rings (LOTR)*, The Lord of the Rings Boxed Set (Including a Reader's Companion). (London: HarperCollins, 2014).

[28] Perrin, Brown, and Green, *DJG*, sc. For a detiled discussion see: J. B. Green, "Kingdom of God/Heaven,."

[29] David J. Rudolph and Joel Willitts, eds., *Introduction to Messianic Judaism: Its Ecclesial Context and Biblical Foundations* (Grand Rapids, MI: Zondervan, 2013), sec. p 163; Daniel Harrington's entry, titled "Matthew's Christian-Jewish Community".

[30] Gerald F. Hawthorne, Ralph P. Martin, and Daniel G. Reid, eds., *Dictionary of Paul and His Letters* (Downers Grove, Ill: InterVarsity Press, 1993), 275; John F. Maile, "Exaltation and Enthronement,".

[31] Joshua Noble, *Common Property, the Golden Age, and Empire in Acts 2:42-47 and 4:32-35* (Bloomsbury Publishing, 2020), 130 (see pages around 130 for full discussion).

[32] N. T Wright, *Surprised by Hope: Rethinking Heaven, the Resurrection, and the Mission of the Church* (San Francisco, CA: HarperOne an Imprint of Harper Collins Publishers, 2014), 207--9.

[33] Michael Heiser, "The Naked Bible Podcast," The Naked Bible Podcast, n. Heiser spent a full year of his podcast going over the allusions of the OT in Revelation. See the podcast or transcripts for details., accessed January 30, 2021, https://nakedbiblepodcast.com/episodes/.

[34] Wright, *Surprised by Hope: Rethinking Heaven, the Resurrection, and the Mission of the Church*, 277.

**Darrell Wolfe, [Storyteller at NoHiding.Faith](http://www.nohiding.faith/p/blog-page.html)**
