---
title: 'Class Assignment: PHILOSOPHY OF MINISTRY'
date: '2022-02-12T23:58:00.0030000+00:00'
draft: false
categories:
  - 'Class Assignment'
---
THE KING'S UNIVERSITY (TKU)
PHILOSOPHY OF MINISTRY
SUBMITTED TO PROFESSOR DR. HOLLEY S. CLOUGH FOR LEADERSHIP DEVELOPMENT (BIBM3302ONL1)

BY
DARRELL WOLFE

SOUTHLAKE, TEXAS, ONLINE VIA NORTH POLE, IDAHO
FEBRUARY 2022

### PHILOSOPHY OF MINISTRY

#### Darrell's LIFE Mission Statement

NO HIDING: Finding Faith & Freedom to walk out an authentic relationship with God, His Family, and His Word; through Biblical Studies, Stories, and Scholarship

#### Ministry is: Imaging Yahweh to others at all times

*Being an Image Bearer for God:*

- *Key Concept:* "Think of the "image" of God as a verb, and you'll get the idea. We were created to image God, to be his imagers---to represent him or be his proxy to each other and to all the earth." Michael Heiser

*Being an Image Bearer to the de-churched and disenfranchised (irreligious Christianity):*

- *Key Concept:* I am called to the de-churched and disenfranchised, to love them into fullness and to teach them to think differently so they can find freedom. This means I will sometimes look and act in ways that make religious people uncomfortable, which is just fine with me.

#### My Ministry Philosophies: What and why I do what I do.

*Transformational Teaching: I teach them to think differently and seek freedom.*

*Key Concepts:*

- By knowing Truth, we are freed from bondage to lies (strongholds).
- Freedom from Psychological bondage - by thinking differently, we can be freed from unhealthy behaviors and relationship patterns that came through stronghold patterns induced and perpetuated by lies.
- Freedom from Religious bondage - by thinking differently, we can see where old religious traditions have held us captive to unhealthy ideologies. It is seeing what the biblical authors really meant that brings us the truth of God's inspired revelation and the freedom that comes from that truth.
- Freedom from Tradition's bondage- by studying the Bible in its own Ancient Near East (ANE) and Second Temple period contexts, we can attempt to rid ourselves of all religious traditions and get back to the inspired narratives God wanted to communicate. By doing so, we find the freedom brought by His truth. There is no tradition too sacred too question.

*Transformational Community: Building community through relationship (doing life together)*

*Key Concepts:*

- Need for community: By developing relationships with others, in healthy, safe, nonromantic community we can find our needs for intimacy (to know and be known) and find freedom from lies that breed in isolation as people mirror God's Image back to us.
- Forming life-long community by doing life together. For me, community means real, life-long, deep relationship building. While some relationships can be seasonal, the hope-goal is that we (the community) will do life together, and one of us will be at the other's funeral (should the Lord tarry).
- Forming real community outside of the modern event-culture. Community is much harder to form by merely attending a weekly spectator event involving a concert and a public speaker, then quickly leaving afterwards. While that event (some people call "church") can be one avenue of meeting people, it is the activities that bring us into Koinonia (doing life together) that will ultimately create these life-long bonds of community. The event can be a component of that community, but it must not be the only tool one uses to develop community.

#### Wolfe Rules (Gibb's Style Rules) -- My curated truisms to living well.

***My highest priority: NO HIDING -- Radical authenticity in healthy community is the key to freedom (getting and staying free). -Darrell Wolfe***

*Doing Life:*

- Plans Fail. Live by Principles. -Unknown
- When Overwhelmed: Take the next indicated step. -Alcoholics Anonymous/Al-Anon
- "What you compromise to keep, you will eventually lose." -Jesse Duplantis
- "Do what's right because it's right, do it right, and do it right away." -Art Aragon
- "Strive not to be a success, but rather to be of value." -Albert Einstein
- "If you can't explain it simply, you don't understand it well enough." -Albert Einstein
- "To admit that you were wrong is to declare that you are wiser now than you were before." -Albert Einstein.
- "Stay away from negative people, they have a problem for every solution." -Albert Einstein
- "An ounce of prevention is worth a pound of cure." -Ben Franklin
- "People who believe in the resurrection, in God making a whole new world in which everything will be set right at last, are unstoppably motivated to work for that new world in the present." -NT Wright
- "Prayer is for hearing God's agenda not for bringing Him yours. Don't tell Him what you want to see happen. When praying, ask Him what He's doing and how you can participate." -Darrell Wolfe
- "When in doubt: Shift into 'Low Slow', listen for His voice." -Kenneth Copeland

*Finding Freedom:*

- "Freedom is not the absence of something, it is the presence of someone." -Bob Hamp
- "We are all broken, that's how the light gets through." -Ernest Hemingway
- "It's OKAY to be not okay" -Unknown
- "Religion attempts to overcome the Knowledge of Evil with the Knowledge of Good; but the Knowledge of Good will never re-connect you to LIFE, which is the real need of man. Life flows from a different tree (paraphrased)" -Bob Hamp

*Studying the Bible:*

- "Religion is the by-product left over after God's move is turned from movement to monument." -Darrell Wolfe
- "Don't seek out verses, seek out themes and patterns in the whole Bible. Ask Him to reveal His-Story to you, and your part in it. Only build theology on what the text of the bible can support." -- Darrell Wolfe
- "Traditions tell us where we have come from. Scripture itself is a better guide as to where we should be going now." -NT Wright
- "You are better off knowing what a passage means than you are memorizing it." -Michael Heiser
- "The New Testament is essentially an inspired commentary on the Old Testament. So, we need to pay attention to how the New Testament authors read the Old Testament, how they repurposed it, and their understanding of the it is not going to violate the Old Testament in its own original context. In fact, it will build on it. It will reinforce it." -Michael Heiser
- "Second Temple literature is really important, and therefore, we ought to pay more attention to that material for understanding the Old Testament and how the New Testament uses the Old Testament than to our own denominational traditions." -Michael Heiser

TBC\...
