---
title: 'Class Assignment: Case 5.1: The Unwanted Pregnancy'
date: '2022-04-06T05:01:00.0050000+00:00'
draft: false
blogger_blog: 'NoHiding.Faith'
blogger_status: 'LIVE'
blogger_post_id: '1805814267126771711'
blogger_filename: '/2022/04/class-assignment-case-51-unwanted.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/NoHiding.Faith/feed.atom'
categories:
  - 'Class Assignment'
  - 'Ethics'
  - 'Counseling'
  - 'Pastoral'
---

<p style="text-align: center;"><b>Case 5.1: The Unwanted Pregnancy</b></p><p><b><span style="font-size: medium;">Background:</span></b></p><p>For Christian Ethics class, we had to read a case study and discuss how we would respond. I decided this would be an interesting practical class assignment to include on the NO HIDING FAITH Website because while I wish this response were typical for all pastors everywhere, the fact is my response is probably more rare than common.&nbsp;</p><p><i>Note: Responses edited for the website.</i></p><p>Consider the following a case-specific example of my template for Pastoral Counseling and the relationships we should build with our people (in and out of the Yeshua communities).</p><p><b><span style="font-size: medium;">Case Study</span></b></p><p>For reference, I have included the textbook case study.&nbsp;</p><p></p><blockquote><p><i>Case 5.1: The Unwanted Pregnancy</i></p><p><i>You are the college pastor for your church, and this afternoon you have had a counseling appointment with one of your students and her parents. She is new to your ministry, having recently come to faith in Christ, and her parents do not attend your church. They are distraught with her pregnancy, and you are too, since she is pregnant by one of the young men in your college ministry. They have known each other for roughly six months and are seeing each other exclusively.</i></p><p><i>They are coming for your counsel on abortion. They are considering facilitating a pregnancy termination and want to know your opinion. Since the parents do not attend your church and are likely not Christians, it is unlikely that they recognize any authority to Scripture.</i></p><p><i>Questions for Discussion</i></p><p><i>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1.&nbsp; &nbsp; &nbsp; What will you tell your student and her parents about the decision to end the pregnancy?</i></p><p><i>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2.&nbsp; &nbsp; &nbsp; How would you defend your advice to the couple from the Bible? How, if at all, would you articulate your view to the girl’s parents differently, since they don’t appear to have much appreciation for the authority of the Bible?</i></p><p><i>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3.&nbsp; &nbsp; &nbsp; Would you advise the couple to get married? Be sure to explain your reasons for your view on this question.</i></p><p><i>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 4.&nbsp; &nbsp; &nbsp; Assuming that they do not terminate the pregnancy and do not get married, would you advise the girl to put the baby up for adoption? Why or why not?</i></p><p><i>Scott B. Rae, Moral Choices: An Introduction To Ethics, Third Edition (Grand Rapids, MI: Zondervan, 2009), 149–150.</i></p></blockquote><p><b><span style="font-size: medium;">My Response:</span></b></p><p style="text-align: center;">THE KING’S UNIVERSITY (TKU)</p><p style="text-align: center;">READING RESPONSES</p><p style="text-align: center;">READING RESPONSES SUBMITTED TO PROFESSOR DR. JAMES PATRICK GIRDLESTONE FOR CHRISTIAN ETHICS (PHIL2301).</p><p style="text-align: center;">BY</p><p style="text-align: center;">DARRELL WOLFE</p><p style="text-align: center;">DARRELL.WOLFE@STUDENT.TKU.EDU</p><p style="text-align: center;">SOUTHLAKE, TEXAS, ONLINE VIA NORTH POLE, IDAHO</p><p style="text-align: center;">SPRING 2022</p><p style="text-align: center;"><b>WEEK FOUR</b></p><p><br /></p><p><span>&nbsp;&nbsp; &nbsp;</span>As I understand this exercise, I am supposed to review the case and provide my answers to the worksheet questions. I chose Case 5.1: The Unwanted Pregnancy (149-150).&nbsp;</p><p><b><span style="white-space: pre;">	</span>Preface:&nbsp;</b></p><p><span>&nbsp;&nbsp; &nbsp;</span>As a family, they may be having a range of possible emotional responses from shame about the situation, anger at the young man or even the church since he is involved there, fear over the unknown, guilt that they are considering an abortion, and a host of other emotions.&nbsp;</p><p><span>&nbsp;&nbsp; &nbsp;</span>Long before we dispense with advice or diagnostics or any progress forward. I want to begin by asking them to share their story, talk about how they are feeling, see the reaction/nonreaction in my presence, and ensure them they are in a safe space to have this discussion. I also want to ensure that they know we are all (all humans) broken and messy, and that’s one of the beautiful parts of the ministry of Yeshua is that he comes to us in our brokenness. Therefore, I will walk through this next season with them regardless of what decision they make. Their future acceptance of the Kingdom demands that I not make my continued presence in their life contingent on this difficult decision.</p><p><span>&nbsp;&nbsp; &nbsp;</span>Also, I take a stance against the way these text questions are worded. Pastoral Counselors should not be giving “advice” or “telling them what to do”. We can guide but never demand. And when was the last time you heard of “giving advice” going well? They’re almost sure to do the opposite of whatever you say unless it is their idea and they own the final decision.</p><p><b><span style="white-space: pre;">	</span>Diagnostics from the text:</b></p><p><b>1.<span style="white-space: pre;">	</span>What will you tell your student and her parents about the decision to end the pregnancy?</b></p><p><span>&nbsp;&nbsp; &nbsp;</span>I would begin with questions to gauge their thoughts about the value of life (in general) and have them think through what makes a human being a full-fledged human being with rights?&nbsp;</p><p><span>&nbsp;&nbsp; &nbsp;</span>I would walk them backward from terminating the life of a three-year-old child, two, one, one day after birth, one hour after birth, ten minutes after birth, while it is being born, ten minutes before birth, etc... and then ask them how they differentiate the "right to life" at each stage?&nbsp;</p><p><span>&nbsp;&nbsp; &nbsp;</span>I would also help them ask their own questions about the decision:&nbsp;</p><p></p><ul style="text-align: left;"><li>What do you know about human biology and the procedure you are about to endure?&nbsp;</li><li>What do you believe about life, in general?&nbsp;</li><li>What options have you considered in addition to the Abortion?&nbsp;</li><li>What would it look like to follow through with keeping and raising the child?&nbsp;</li><li>What would it look like to go through with an abortion?&nbsp;</li><li>What would it look like if you carried to term but gave it up for adoption to a family who desperately wants a child but cannot have one (could this be a ministry opportunity for that family)?&nbsp;</li><li>Etc…</li></ul><p></p><p><b>2.<span style="white-space: pre;">	</span>How would you defend your advice to the couple from the Bible? How, if at all, would you articulate your view to the girl’s parents differently, since they don’t appear to have much appreciation for the authority of the Bible?</b></p><p><span>&nbsp;&nbsp; &nbsp;</span>The Bible is my source of wisdom, even if it is not theirs. But I can meet them where they are. If the girl and parents are both not believers (as the text implies), I would likely appeal on human-grounds, and not biblical ones, unless the topic came up, I was asked directly, or the Spirit prompted.&nbsp;</p><p><span>&nbsp;&nbsp; &nbsp;</span>The Torah is written on our hearts, people know killing is wrong when faced with the decision on human grounds. Though a parable can help, from time to time.</p><p><b>3.<span style="white-space: pre;">	</span>Would you advise the couple to get married? Be sure to explain your reasons for your view on this question.</b></p><p><span>&nbsp;&nbsp; &nbsp;</span>Unlikely! Marriage for the sake of pregnancy is almost certainly compounding mistakes and making the problem worse.&nbsp;</p><p><span>&nbsp;&nbsp; &nbsp;</span>However, if the couple decided to keep the baby and raise it together, and they were interested in marriage; I would walk them through some intense pre-marital counseling and request they wait for one year of meetings with me before making that decision.&nbsp;</p><p><b>God is more interested in human hearts than institutions.</b></p><p><b>4.<span style="white-space: pre;">	</span>Assuming that they do not terminate the pregnancy and do not get married, would you advise the girl to put the baby up for adoption? Why or why not?</b></p><p><span>&nbsp;&nbsp; &nbsp;</span>I don't give advice (try not to anymore).&nbsp;</p><p><span>&nbsp;&nbsp; &nbsp;</span>I ask questions that uncover the individual’s own moral grounding and help them come to a decision that is within their cognitive framework.&nbsp;</p><p><span>&nbsp;&nbsp; &nbsp;</span>As stated above, I will help her consider all options and the ramifications of those options and make a decision that aligns with her will, emotions, and intuitive sense.&nbsp;</p><p><span>&nbsp;&nbsp; &nbsp;</span>Hopefully, I will have earned the right to walk with her through various seasons of her life (regardless of the specific outcomes) and mentor/disciple her into a better and healthier future than may have otherwise been the case.</p><p><b>Darrell Wolfe</b></p><div><br /></div>