---
title: 'Class Assignment (2019): Reflection Paper Understanding Scripture'
date: '2022-03-03T07:07:00.0030000+00:00'
draft: false
categories:
  - 'Class Assignment'
---
Reflection Paper

Understanding Scripture

Darrell Wolfe

BIBL-1300 Introduction to the Bible

Spring 2019, Online Session 1

February 13, 2019

Table of Contents

Review: Understanding Scripture.. 3

The Narrative: The Greatest Story Ever Told.. 3

Did I Read That Right?. 4

Fire the Cannon.. 4

Lost in Translations. 5

The New Testament Makes Sense. 5

Preach! 6

Take Aways. 6

Verse Jacking! 6

Many Churches, Conflicting Ideas -- Firmly held beliefs in conflict. 6

Wrestling with Ideals. 7

Resolution: The Narrative Context. 7

Bibliography.. 9

# Review: Understanding Scripture

This is a review of the text, Understanding Scripture (Grudem, Collins, & Schreiner, 2012). The authors provide the backdrop for making their case:

To profit from Scripture, one must take the right posture. At one extreme, the skeptic questions and judges whatever he/she reads. At the other, the overconfident believer, convinced he has mastered the biblical or systematic theology, ignores or explains away whatever fails to support his system. Interpreters should come to Scripture humbly, expecting to learn and be corrected and willing to observe Scripture closely and accept whatever they find. (Grudem, Collins, & Schreiner, 2012), Pg 12

They go on to lay out several key items to contemplate as we embark on this journey of discovery in the greatest story ever told.

## The Narrative: The Greatest Story Ever Told

The Narrative refers to the on-going story that began In the Beginning and rolls right through Abraham, Jesus, Paul, and Me. The Bible, in large part, is handed to us as a narrative. The meaning of the "verse" one attempts to use to justify their position must fit within the overall context of The Narrative; and, it must mean to the original author/participants in that story what it means to you. We are part of that on-going story. The application we take away must be within the context of that larger story.

## Did I Read That Right?

Before one can study, one must read The Narrative as it was provided. It is within this framework that the meanings can be gathered. Understanding the literary style is also important. The Bible can be read as Historical, Literature (including the Literary Style), and Communion with the Author Himself. Depending on the mindset you come to the Bible with, this affects Application and Teaching. Also, to be considered, Literal vs Allegory. Some find hidden meanings while others take the text at face value. The Literary Style should help us determine what approach we take for any given book or section. One should take the instruction to love our neighbor literally but not assume that a literal Dragon was coming to eat a woman's child (Revelation). Genre matters.

## Fire the Cannon

The manuscripts we have today are reliable. That is covered in great depth in the texts. The variety, age, and abundance of older manuscripts allow us to see that the text we have is reliable and is exactly what the authors wrote for us to read. Archelogy does serve to reinforce the Historicity of the Bible (confirming events, names, and dates); however, it serves a more intricate purpose as well. Archeology paints the picture of the times and customs of the people we read about. That context allows us to immerse ourselves in the story, feel the sand beneath our sandals and in between our toes, and feel the upper room's cold night air.

## Lost in Translations

One of the reasons there are so many translations, is that so many translators do the important work of helping us read the original language in our Modern English. I speak a modicum of Spanish. One day, in class, I said "Estoy Caliente'", literally "I am (temporarily) hot". My teacher corrected, with a big grin, "No. No. No, Senior Wolfe. Hace Calor", meaning "it is presently hot". Apparently, "Estoy Caliente'" in the culture has an entirely different connotation, "I am Hot (Horny/Attractive)". This very simple misunderstanding is a humorous example of how easily one can mess up language-to-language translation. It is not enough to translate words, one must translate ideas and concepts in culturally accurate ways. In this same way, Hebrew, Greek, Aramaic, Latin, and other Biblically related languages (as they relate to manuscripts we possess) must be translated, and not simply transliterated.

## The New Testament Makes Sense

Why not stop with the Old Testament. The Cannon of the Old Testament was largely firmed up by the time of Jesus. It was the Scriptures he referred to often "as it is written". So why have a New Testament at all? Throughout the old covenant, God was promising a coming Messiah and new revelation. It follows then, as a continuation of The Narrative, that a new set of texts would be handed to us to preserve those steps in The Narrative. The New Testament makes sense because it is a continuation of the story. (Grudem, Collins, & Schreiner, 2012) Pg 82

## Preach!

It is often the case today (and has been true since at least the Church Growth Movement of the 70s), sermons can be nothing more than Three Points, a Reader's Digest Story, and a Joke... with a few supporting scriptures. The authors have the following to say about that:

The preacher must preach the text, not the idea that brought him to the text. He must stand behind the Bible, not in front of it. (Grudem, Collins, & Schreiner, 2012) Pg 64-65

This more common type of modern preaching leads to another issue: Verse Jacking.

# Take Aways

## Verse Jacking!

What is Verse Jacking? This is taking a set of hand-picked verses completely out of context, running them together as "proof" that your position is sound and "Biblical". This is where your inner parent must come out, "Put that back where you found it!" If the verse doesn't mean that in context, in The Narrative, and to the original author; it does not mean that to you.

## Many Churches, Conflicting Ideas -- Firmly held beliefs in conflict.

Due to Verse Jacking, we've got thousands of denominations. Every group has their corner staked out on The Truth. Although it's true that we know in part while on this earth, and "they" may be seeing something I haven't seen yet; it is also true that they may be Verse Jacking to create a position that God himself doesn't hold.

## Wrestling with Ideals

My own turmoil trying to wrestle with conflicting ideals stems from a life long search for The Truth. Over the years, I've moved from Christian group to Christian group in search of the most authentic, real, true, relationship with Jesus I can have. As a function of this search, I picked up many firmly held beliefs that I've since come to realize weren't True. They were supported with Bible verses; however, they were not actually Biblical.

## Resolution: The Narrative Context

With that in mind, here are some things I now realize will help me on the next phase of my journey.

- Proverbs are not TRUE, they are generally true. Just because a proverb says that the upright will be successful, doesn't mean that all people who do right will never have a tragedy. It does, however, indicate that on trend the upright fair well on principle. Proverbs 2:7-8 ((NIV))

- Where does that verse belong? If it didn't mean that to the author it doesn't mean that to you. Put it back where you found it and see what it means inside The Narrative. Only then can you determine what it means.

- Any doctrine must be firmly based on the whole Bible, a thread neatly woven into The Narrative. When speaking about the variety of manuscripts and differences of interpretation, the authors of this text indicate that on rare instance you may come to find that a particular verse wasn't saying what you thought it said.  This includes, especially, End Times Prophecy. To this point, they write:

At times, a particular doctrine may not, after all, be affirmed in a given passage, depending on the textual variant. But this is not the same thing as saying that such a doctrine is denied. Just because a particular verse may not affirm a cherished doctrine does not mean that that doctrine cannot be found in the New Testament. In the final analysis, no cardinal doctrine, no essential truth, is affected by any viable variant in the surviving New Testament manuscripts. (Grudem, Collins, & Schreiner, 2012) Pg 116-117

With these tools in hand, I can continue my journey to find the most authentic relationship with Jesus, His Father, His Holy Spirit, and His Word.

# Bibliography

(NIV), N. I. (n.d.). *Proverbs 2:7-8.* Retrieved from https://www.biblica.com/bible/niv/proverbs/2/

Grudem, W., Collins, C. J., & Schreiner, T. R. (2012). *Understanding Scripture - An Overview of the Bible's Origin, Reliability, and Meaning.* Wheaton, IL: Crossway.
