---
title: 'Research: Romans 3 / Original Testament Allusions & Quotes'
date: '2022-03-03T07:05:00.0010000+00:00'
draft: false
categories:
  - 'Research'
---
** The following was research for a local Bible Study**

# Romans 3 / Original Testament Allusions & Quotes

## Stringing Pearls, Not to be cast before swine

In Sitting at the Feet of Rabi Jesus, Spangler and Tverberg demonstrate the hidden meaning behind the famous swine passage.[\[1\]](#_ftn1) Jesus said:

*"Do not give what is holy to dogs, or throw your pearls in front of pigs, lest they trample them with their feet, and turn around and tear you to pieces.[^**^\[2\]^**^](#_ftn2)*

Both today and in first century AD, Rabbis would cite passages, partial passages, or even just images and allusions from the Hebrew Bible in o rder to incite their hearers to think about those passages. The act of thinking about where the quote came from was part of the learning experience.

In one story, an understudy took a careless action that caused his Rabbi/Professor a public grief. The Rabbi said, "I have reared children and brought them up" and he walked away. The whole passage reads "I reared children and brought them up, but they have rebelled against me!" The rebuke was inferred by the partial quote.[\[3\]](#_ftn3)

This practice of dropping a partial quote is called a "pearl", for there is hidden treasure when one looks closer. When a Rabbi teaches and quotes passage after passage, he is said to be stringing-pearls together. When Jesus said not to cast your pearls before swine, he was saying not to drop hidden knowledge nuggets onto the ears of people incapable of hearing it.

Here we see Rabbi Paul (formerly Pharisee Rabbi Saul) stringing pearls in Romans 3.

## Romans 3 (NET Bible)

- 3:9 What then? Are we better off? Certainly not, for we have already charged that Jews and Greeks alike are all under sin, 3:10 just as it is written:

- 3:10b"There is no one righteous, not even one, 3:11 there is no one who understands, there is no one who seeks God. 3:12 All have turned away, together they have become worthless; there is no one who shows kindness, not even one."

- 3:13 "Their throats are open graves, they deceive with their tongues, the poison of asps is under their lips."

- 3:14 "Their mouths are full of cursing and bitterness."

- 3:15 "Their feet are swift to shed blood, 3:16 ruin and misery are in their paths, 3:17 and the way of peace they have not known."

- 3:18 "There is no fear of God before their eyes."

- 3:19 Now we know that whatever the law says, it says to those who are under the law, so that every mouth may be silenced and the whole world may be held accountable to God. 3:20 For no one is declared righteous before him by the works of the law, for through the law comes the knowledge of sin.

## Original Testament Quotes from the LEB [\[4\]](#_ftn4)and Romans quotes from NETBible.[\[5\]](#_ftn5)

3:10b "There is no one righteous, not even one, 3:11 there is no one who understands, there is no one who seeks God. 3:12 All have turned away, together they have become worthless; there is no one who shows kindness, not even one."

- sn Verses 10--12 are a quotation from Ps 14:1--3.

- Psalms 14: For the music director. Of David. The fool says in his heart, "There is no God." They are corrupt. They do abominable deeds. **There is none who does good**. Yahweh looks down from heaven upon the children of humankind to see whether there is one who has insight, one who cares about God. All have gone astray; they are altogether corrupt. **There is not one who does good; there is not even one.** All who do evil---do they not know, they who eat my people as though they were eating bread? They do not call on Yahweh. There they are very fearful because God is with the generation of the righteous. You would put to shame the plan of the poor, because Yahweh is his refuge. Oh that from Zion would come salvation for Israel! When Yahweh returns the fortunes of his people, Jacob will rejoice; Israel will be happy.

3:13 "Their throats are open graves, they deceive with their tongues, the poison of asps is under their lips."

- sn A quotation from Pss 5:9; 140:3.

- Psalms 5: For the music director; with the flutes. A psalm of David. Hear my words, O Yahweh. Give heed to my sighing. Listen to the sound of my pleading, my king and my God, for to you I pray. O Yahweh, in the morning you will hear my voice. In the morning I will set forth my case to you and I will watch. For you are not a God who desires wickedness. Evil cannot dwell with you. The boastful do not stand before your eyes. You hate all evildoers. You destroy speakers of lies. A man of bloodshed and deceit Yahweh abhors. But as for me, through the abundance of your steadfast love I will enter your house. I will bow down toward your holy temple in awe of you. O Yahweh, lead me in your righteousness because of my enemies; make straight before me your way. For there is not anything reliable in his mouth; their inner part is destruction. **Their throat is an open grave; with their tongue they speak deceit.** Treat them as guilty, O God; let them fall because of their plans. Because of the abundance of their transgressions cast them out, for they have rebelled against you. But let all who take shelter in you rejoice. Let them ever sing for joy, because you spread protection over them; And let those who love your name exult in you. For you bless the righteous. O Yahweh, like a shield you surround him with good favor.

- Psalms 140: For the music director. A psalm of David. Rescue me, O Yahweh, from evil men. Preserve me from violent men, who plan evil things in their heart. They stir up wars continually. **They sharpen their tongue as sharp as a snake's; the venom of a viper is under their lips**. Selah Protect me, O Yahweh, from the hands of the wicked. Preserve me from violent men, who have planned to make me stumble. The proud have hidden a trap for me, and cords. They have spread out a net along the side of the path. They have set snares for me. Selah I say to Yahweh, "You are my God." Listen, O Yahweh, to the voice of my supplications. O Yahweh, my Lord, the strength of my salvation, you have covered my head in the day of battle. Do not grant, O Yahweh, the desires of the wicked. Do not allow them to attain their plan, lest they be exalted.

3:14 "Their mouths are full of cursing and bitterness."

- sn A quotation from Ps 10:7.

- Psalms 10: Why, O Yahweh, do you stand far off? Why do you hide during times of distress? In arrogance the wicked persecutes the poor. Let them be caught in the schemes that they devised, for the wicked boasts about the desire of his heart, and the one greedy for gain curses and treats Yahweh with contempt. With bald-faced pride the wicked will not seek God. There is no God in any of his thoughts. His ways endure at all times. Your judgments are aloof from him. As for all his enemies, he scoffs at them. He says in his heart, "I shall not be moved throughout all generations, during which I will have no trouble." **His mouth is filled with cursing, with deceits and oppression; under his tongue are trouble and evil**. He sits in ambush in villages; in the hiding places he kills the innocent. His eyes lurk for the helpless. He lies in ambush secretly, like a lion in a thicket. He lies in ambush to seize the poor; he seizes the poor by catching him in his net. He is crushed; he is bowed down; so the helpless host falls by his might. He says in his heart, "God has forgotten. He has hidden his face. He never sees." Rise up, O Yahweh; O God, lift up your hand. Do not forget the afflicted. Why does the wicked treat God with contempt? He says in his heart, "You will not call me to account." But you have seen; indeed you have noted trouble and grief to take it into your hand. The helpless abandons himself upon you; you have been the helper for the orphan. Break the arm of the wicked, and as for the evil man--- seek out his wickedness until you find none. Yahweh is king forever and ever; the nations have perished from his land. The longing of the afflicted you have heard, O Yahweh. You will make their heart secure. You will listen attentively to render judgment for the fatherless and the oppressed so that a mere mortal from the earth will no longer cause terror.

3:15 "Their feet are swift to shed blood, 3:16 ruin and misery are in their paths, 3:17 and the way of peace they have not known."

- sn Rom 3:15--17 is a quotation from Isa 59:7--8.

- Isaiah 59: Look! The hand of Yahweh is not too short to save, and his ear is not too dull to hear. Rather, your iniquities have been barriers between you and your God, and your sins have hidden his face from you, from hearing. For your hands are defiled with blood, and your fingers with iniquity. Your lips have spoken lies, your tongue speaks wickedness. There is nobody who pleads with justice, and there is nobody who judges with honesty. They rely on nothing and speak vanity. They conceive trouble and beget iniquity; they hatch viper eggs, and they weave a spider web. One who eats their eggs dies, and that which is pressed is hatched as a serpent. Their webs cannot become clothing, and they cannot cover themselves with their works. Their works are works of iniquity, and deeds of violence are in their hands. **Their feet run to evil, and they hasten to shed innocent blood**. Their thoughts are thoughts of iniquity; devastation and destruction are in their highways. They do not know the way of peace, and **there is no justice in their firm paths. They have made their paths crooked for themselves; everyone who walks in it knows no peace.**

3:18 "There is no fear of God before their eyes."

- sn A quotation from Ps 36:1.

- Psalms 36: For the music director. Of David, the servant of Yahweh. An oracle: the wicked has rebellion in the midst of his heart. **There is no fear of God before his eyes**. For he flatters himself in his eyes, hating to detect his iniquity. The words of his mouth are wickedness and deceit. He has ceased to have insight and to do good. He plans sin on his bed. He puts himself on a way that is not good. He does not reject evil. O Yahweh, your loyal love extends into the heavens, your faithfulness unto the clouds. Your righteousness is like the mighty mountains, your judgments like the great deep. You save man and beast, O Yahweh. How precious is your loyal love, O God, and the children of humankind take refuge in the shadow of your wings. They are refreshed with the fullness of your house, and you give them drink from the river of your delights. For with you is the fountain of life; in your light we see light. Prolong your loyal love to those who know you, and your righteousness to the upright of heart. Do not let a foot of pride come against me, nor let a wicked hand make me to wander homeless. There doers of evil have fallen; they are thrust down and not able to rise.

3:19 Now we know that whatever the law says, it says to those who are under the law, so that every mouth may be silenced and the whole world may be held accountable to God. 3:20 For no one is declared righteous before him by the works of the law, for through the law comes the knowledge of sin.

- sn An allusion to Ps 143:2.

- Psalms 143: A psalm of David. O Yahweh, hear my prayer; listen to my supplications. **In your faithfulness answer me, and in your righteousness. And do not enter into judgment with your servant, because no one alive is righteous before you.** For the enemy has pursued my soul; he has crushed my life to the ground. He has made me dwell in dark places like those long dead. And so my spirit grows faint within me; my heart within me is desolate. I remember the days of long ago; I meditate on all your doings. I muse on the labor of your hands. I stretch out my hands to you; my soul longs for you like a dry land. Selah Quickly answer me, O Yahweh; my spirit fails. Do not hide your face from me, or I will become like those descending to the pit. Cause me to hear your loyal love in the morning, for I trust you. Cause me to know the way that I should go, for I lift up my soul to you. Deliver me from my enemies, O Yahweh. I take refuge in you. Teach me to do your will, for you are my God; your Spirit is good. Lead me onto level ground. For your name's sake, O Yahweh, preserve my life; in your righteousness bring me out of trouble. And in your loyal love destroy my enemies, and exterminate all the adversaries of my soul, for I am your servant.

## Commentary Note:

In Echoes of Scripture in the Letters of Paul, Richard B. Hays says:

Impossible to miss, however, is the jackhammer indictment of human sinfulness in the scriptural catena of Rom. 3:10--18. Assembled from parts of at least five different psalms as well as from Ecclesiastes, Proverbs, and Isaiah, this anthology of condemnation relentlessly pounds home the charge enunciated by its opening line: "There is no righteous person, no not one" (cf. Ps. 14:1--3 and Eccl. 7:20). Why this unremitting attack on the moral integrity of human beings? In the context of Paul's argument, the catena of quotations provides a powerful rhetorical warrant for his assertions that all humanity, Jews and Greeks alike, is "under sin" (3:9), and that the whole world is therefore accountable (hypodikos) to God (3:19). The indictment is framed in the words of Scripture; this is crucial for Paul's purposes, because it demonstrates that "those in the Law" (Jews) are addressed by the Law (Scripture) in such a way that their own culpability before God should be inescapable: in an echo of Ps. 62:12 (LXX Septuagint), Paul observes that Scripture speaks this way "in order that every mouth might be stopped." Those who are entrusted with the oracles of God are thus given the paradoxical privilege of learning from those oracles the truth of their own depravity, a truth that remains hidden from the rest of humanity.

Thus, the underlying purpose of Rom. 3:9--20 is to establish beyond all possible doubt the affirmation that God is just in his judgment of the world. The passage rebuts the rhetorical suggestion of Rom. 3:5--7 that God might be considered unfair (adikos). The righteousness of God, proclaimed by Psalm 51, is highlighted by Scripture's contrasting account of human unrighteousness, which simultaneously cuts away any ground for human protest against God's justice.

Paul sums up this train of thought in Rom. 3:20 with one last scriptural allusion, this time to Psalm 143: "Therefore, by works of the Law no flesh shall be justified before him." Paul has tinkered with the wording of Ps. 143:2 in several ways. The phrase "by works of the Law" is his own explanatory exegetical comment, and he has changed the LXX Septuagint pas zōn (every living being) to pasa sarx (all flesh); furthermore, he has transmuted the psalmist's direct address to God ("No living being will be justified before you") into a declarative generalization by changing the personal pronoun from second to third person singular. The effect of these modifications is to render the intertextual relation indirect rather than direct. The psalm is not adduced as a proof for Paul's assertion, but his assertion echoes the psalm, activating Israel's canonical memory. A reader formed spiritually by the psalter, with or without recognizing the specific allusion, will know already that before God no one can claim to be justified; thus, hearing Paul's proclamation, the reader will be disposed to assent.[^^\[6\]^^](#_ftn6)

------------------------------------------------------------------------

[\[1\]](#_ftnref1) Spangler, Ann, and Lois Tverberg. Sitting at the Feet of Rabbi Jesus: How the Jewishness of Jesus Can Transform Your Faith. Updated edition. Grand Rapids, Michigan: Zondervan, 2018.

[^^\[2\]^^](#_ftnref2) W. Hall Harris III et al., eds., [*The Lexham English Bible*](https://ref.ly/logosres/leb?ref=BibleLEB2.Mt7.6&off=0&ctx=our+brother%E2%80%99s+eye!+%0a~6%C2%A0%E2%80%9CDo+not+give+what+) (Bellingham, WA: Lexham Press, 2012), Mt 7:6.

[\[3\]](#_ftnref3) Isaiah 1:2

[\[4\]](#_ftnref4) *W. Hall Harris III et al., eds., The Lexham English Bible (Bellingham, WA: Lexham Press, 2012), Ps 5,10, 14 140, 143; Is 59,*

[\[5\]](#_ftnref5) ^^\[5\]^^ Biblical Studies Press, [*The NET Bible First Edition; Bible. English. NET Bible.; The NET Bible*](https://ref.ly/logosres/gs-netbible?ref=BibleNET.Ro3.9&off=30&ctx=nation+of+the+World%0a~3%3a9%C2%A0What+then%3f+Are+w) (Biblical Studies Press, 2005), Ro 3:9--20.

[^^\[6\]^^](#_ftnref6) Richard B. Hays, [*Echoes of Scripture in the Letters of Paul*](https://ref.ly/logosres/chsscrptrlttrpl?ref=Page.p+50&off=1005&ctx=nd+Pauline+kerygma.%0a~Impossible+to+miss%2c+) (New Haven; London: Yale University Press, 1989), 50--51.
