---
title: 'Class Assignment: Exegesis of Acts 2:41-47'
date: '2022-10-09T22:21:00.0050000+00:00'
draft: false
categories:
  - 'Class Assignment'
---

<p style="text-align: center;">&nbsp;<span style="font-size: 12pt; text-align: center;">&nbsp;</span><span style="font-size: 12pt; text-align: center;">The King’s University (TKU)</span></p>

<h1 style="text-align: center;"><span class="MsoBookTitle"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Exegesis of Acts 2:41-47</span></span></h1>

<h3 style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Research Paper submitted to Professors Reed
Metcalf and Jason Moraff for Luke-Acts in Jewish Context (BIBL4310)</span></h3>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">By&nbsp;</span><span style="font-size: 12pt;">Darrell Wolfe</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Southlake, Texas, Online Via North Pole, Idaho<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Due October 9, 2022</span></p><p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><br /></span></p>

<h3 style="text-align: left;">Acts 2:41-47 Outline</h3><h1><o:p></o:p></h1>

<h4 style="text-align: left;">A chiasm
with a center highlighting common fellowship: koinonia/koinos</h4><h2><o:p></o:p></h2>

<p class="MsoNormal" style="line-height: normal; margin-bottom: 0in;"><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">2:41 –
Luke <u>transitions</u> from Peter’s speech to the results of the speech with
the phrase, “So…” (starting a new line of thought) and the fact people were
“added” to the church.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: normal; margin-bottom: 0in; margin-left: .5in; margin-right: 0in; margin-top: 0in;"><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">2:42 – <u>Activities</u>: what this new sect
did; they devoted themselves to Teaching, <b>Fellowship (<i>koinonia</i>)</b>,
Breaking of Bread, and Prayer(s).<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: normal; margin-bottom: 0in; margin-left: 1.0in; margin-right: 0in; margin-top: 0in;"><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">2:43 – <u>Results:</u> The outward result was fear,
wonders, and signs.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: normal; margin-bottom: 0in; margin-left: 1.5in; margin-right: 0in; margin-top: 0in;"><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">2:44 – <u>The Community Result</u>: Everyone
was in the same place and shared everything in <b><i>common (koinos).</i><o:p></o:p></b></span></p>

<p class="MsoNormal" style="line-height: normal; margin-bottom: 0in; margin-left: 1.0in; margin-right: 0in; margin-top: 0in;"><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">2:45 – <u>Results</u>: Giving additional details
about how they shared, through selling and distributing to anyone who had a
need.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: normal; margin-bottom: 0in; margin-left: .5in; margin-right: 0in; margin-top: 0in;"><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">2:46 – <u>Activities</u>: Restating what this
new sect did but with more detail. Repeating the phrase "devoting
themselves", the author expands his earlier explanation (v42) to say that
they met in the temple courts and broke bread in the homes.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: normal; margin-bottom: 0in;"><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">2:47 –
Luke <u>concludes</u> by restating that the Lord was “adding” people who were
"being saved" because of these activities and events.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: normal; margin-bottom: 0in;"><span style="font-size: 12.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;</span></p>

<h3 style="text-align: left;">Observations about the Way, a <i>Koinonia</i>-culture community</h3><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; margin-bottom: 0in; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Luke-Acts serves as a single work, in two
volumes, outlining the work of a Galilean Jewish Rabbi, Yeshua of Nazareth </span><span style="font-size: 12.0pt; line-height: 200%;">(Hebrew: </span><i><span dir="RTL" lang="HE" style="font-family: &quot;Arial&quot;,sans-serif; font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-bidi-language: HE; mso-hansi-font-family: &quot;Times New Roman&quot;;">יֵשׁוּעַ</span></i><span dir="LTR"></span><span dir="LTR"></span><i><span style="font-size: 12.0pt; line-height: 200%;"><span dir="LTR"></span><span dir="LTR"></span>
yēšûaʿ</span></i><span style="font-size: 12.0pt; line-height: 200%;">; Greek: <i>Ἰησοῦς
Iēsous</i>; English: Jesus), </span><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">also
called Jesus the Christ (Anointed One); and the effects of that work in the
community built on his legacy. Luke’s Acts begins with a transition from the
story of Yeshua’s work in Israel to the story of the early Jewish Yeshua
community, the Way. Luke’s Yeshua hands the reigns of his fledgling community
to the work of the Holy Spirit. Just as Yeshua was a Jewish prophet filled with
and anointed by the Holy Spirit (Luke 3:21-22; 4:1), so too his followers would
become his spirit-filled representatives multiplying his work everywhere they
spread “to Jerusalem, and in all Judea and Samaria, and to the farthest part of
the earth” (Luke 11:13; 12:1; Acts 1:5-8, 8; 2:4, 33, LEB). While it is often
called Acts of the Apostles, one Acts scholar quipped that we may be entitled
to call the book, "the Acts of the Holy Spirit, for from first to last it
is the record of his advent and activity."</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn1" name="_ftnref1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[1]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> Yahweh,
through Ezekiel, promised, “a new heart” and “a new spirit” (Ezekiel 36:23-32,
LEB).</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn2" name="_ftnref2" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[2]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> Ezekiel then goes on to describe a vision of a
community living in abundance within the land of promise, “I will cause the
fruit of the tree and the crop of the field to increase” (Ezekiel 36:30). Joel
picks up on this theme by saying, “I will pour out my spirit” (Joel 2:28-29). In
Acts, Luke portrays the Holy Spirit’s arrival as a fulfillment of the promise
(Acts 2:16-21).<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; margin-bottom: 0in; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Green summarizes Luke-Acts as, "a panoramic
mural of God's activity."</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn3" name="_ftnref3" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[3]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> This
early movement, the Way, began as a Jewish sect. Moraff observes that various
sects existed within Second Temple Judaism (Essenes, Pharisees, Sadducees, and Fourth
Philosophy) and that "the Way" became a new Jewish sect within
Judaism.</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn4" name="_ftnref4" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[4]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> Yet, participation with the Way did not mean
one would stop identifying with the sub-group or sect they came from; Paul
continued to identify as a Pharisee after joining the Way.</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn5" name="_ftnref5" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[5]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> <o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; margin-bottom: 0in; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">As the Way expanded into gentile territories,
they became increasingly multi-ethnic; but, Acts always retains Jerusalem, as
the “center” of the movement. Bauer provides a discussion with graphics showing
the progression of Acts from Jerusalem, then to Judea and Samaria, and then to
the “ends of the earth” (Acts 1:8).</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn6" name="_ftnref6" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[6]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> Throughout
these movements, Jerusalem plays a repeating role; and occurs twice as often in
Acts as in Luke (almost 60 times in Acts);</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn7" name="_ftnref7" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[7]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> which
shows that Jerusalem never loses its place of primacy in Acts even as the
progression moves towards, “the ends of the earth” ending at Rome. <o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; margin-bottom: 0in; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Sterling describes Luke’s work in Acts: “The
presentation of the earliest Christian community appears in two forms: five
extended narratives and three summaries.”</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn8" name="_ftnref8" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[8]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> We find
the first of these summaries in Acts 2:41-47. Bauer notes that, </span><span style="font-size: 12.0pt; line-height: 200%;">"In narrative-critical terms”
Peter’s sermon forms, “the basis for the life of the community in
2:42-47."</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn9" name="_ftnref9" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[9]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%;"> </span><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Knowles
summarizes this section by saying, “Luke gives us a glimpse of the everyday
life of the first Christians.”</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn10" name="_ftnref10" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[10]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> When
Luke curates the words with which he will describe this spirit-filled group of early
Yeshua followers, he chooses four primary themes: Teaching, Fellowship,
Breaking of Bread, and Prayers. In the following sections, we will explore
these four words which Luke uses to show the qualitative nature of this
community. The following definitions are a brief synopsis from Mounce,
including the Goodrick/Kohlenberger numbers, followed by an analysis of their
thematic usage in Luke-Acts (in the order in which Luke provided them).<o:p></o:p></span></p>

<h4 style="text-align: left;">Teaching</h4><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Teaching<i> (1439): διδαχή didachē,</i> means,
“instruction, the giving of instruction, teaching”</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn11" name="_ftnref11" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[11]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> Luke
mentions that people were “astounded” at Jesus’ teaching (Luke 4:32), and
provides an intimate example in the story of Mary sitting at Jesus’ feet
listening to his “teaching” (Luke 10:39). Now, in Acts, the apostles carry this
tradition forward (examples: Acts 2:14-47; 5:42; 6:4; 13:12; 17:19). Nässelqvist’s
entry in the Lexham Bible Dictionary explains, “In
the Greek world, philosophers, religious leaders, and mystery cults attracted
disciples. A person became a disciple as he sought out a teacher and followed
him and his principles. Similarly, in the rabbinical tradition, a “learner” or
“student” (</span><span dir="RTL" lang="HE" style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-language: HE; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi; mso-no-proof: yes;">תלמיד</span><span dir="LTR"></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi; mso-no-proof: yes;"><span dir="LTR"></span><span dir="LTR"></span>, <i>tlmyd</i>)
attached himself to a rabbi (literally “my great one,” with the additional
meaning of “teacher” or “master”) or to a movement.”</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn12" name="_ftnref12" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[12]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi; mso-no-proof: yes;"> Spangler and Tverberg expand on this concept showing that, “</span><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Jesus lived transparently in front of his
disciples to teach them how to live. They, in turn, were to live transparently
before others, humbly teaching them <i>the way</i> of Christ. This approach
involves not just information but transformation.”</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn13" name="_ftnref13" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[13]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> This
became the basis for the earliest self-moniker of early Yeshua followers, The
Way (of Messiah/Christ). <o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">What was the content and form of the Apostle’s
teaching? Acts explains, “Every day, both in the temple courts and from house
to house, they did not stop teaching and proclaiming the good news that the
Christ <i>(Hebrew: Messiah)</i> was Jesus (<i>Hebrew: Yeshua</i>)” (Acts 5:42,
LEB, parenthetical inserts my own). It is interesting to note that Acts does
not provide many examples of the Apostles teaching the believing community,
most of the messages Acts records are polemic sermons from the Apostles,
Elders, and Deacons to the leadership within Israel (see Acts 2:14-40; or Peter
and Paul before the Sanhedrin in Acts 4; or Steven’s defense in Acts 7). From
these examples, we can guess the content of the teaching within the believing
community likely, at least, involved showing that Yeshua was Messiah from the
Tanakh. However, Acts does not stand on its own but as the second of a twin
collection. Luke already provided the teaching and parables of Jesus, including
the blessings and woes, love for enemies, judging, and building one’s house on
the right foundation (Luke 6:20-49), the parable of the Sower (Luke 8:11-15),
and others. Since we have Luke’s first record, we can conclude that the
Apostles also likely repeated the sayings and teachings of Yeshua as part of
their teaching. Later, epistles developed additional teaching as required to
live within an ever-growing community in new contexts.<o:p></o:p></span></p>

<h4 style="text-align: left;">Fellowship</h4><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .25in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Fellowship<i> (3126): κοινωνία koinonia,</i>
means “fellowship, partnership”.</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn14" name="_ftnref14" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[14]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> This is
a word we do not often use in modern English except in religious settings. <i>Koinonia</i>
implies a shared sense of community bondedness that is often absent in modern
western American contexts where the phrase ends up being used in sentences such
as, “we went to Bible study and fellowshipped” or “we went to Denny’s and
fellowshipped.” While these can be occasions for <i>Koinonia</i>, the actual
term has deeper roots than merely meeting together and having a decent time.
Mounce explains that <i>Koinonia</i> also carries the inferred meaning of
“participation and sharing”, and he cites this passage in Acts: 2:42 as an
example of a community living <i>koinonia</i> with each other. Mounce also
notes that Paul uses this word thirteen times, and most often it is used to
refer to the “sharing of material things”.</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn15" name="_ftnref15" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[15]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> Due to
the frequency of Acts 2:41-47 as citation in political discourse, a side note
would be worth mentioning. Wright provides a short explanation for why this
passage certainly has a focus on taking care of the poor, but it is not an
endorsement for the government structure called <i>socialism</i> as people retain
private property and give willingly, with no government force or involvement.</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn16" name="_ftnref16" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[16]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .25in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">In the summary chiasm (2:41-47), the center is
built on the phrases, “same place” and “everything in common” (Acts 2:44). This
word, “common” (3123) is <i>κοινός koinos</i>, which means “common, belonging
equally to several”.</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn17" name="_ftnref17" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[17]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> The
followers of Jesus were devoted to <i>koinonia</i> and had everything in <i>koinos</i>.
This word is the center of the chiasm, and the pairing of these words (<i>koinonia</i>
v42, <i>koinos</i> v44) indicates Luke felt that this <i>koinos/koinonia</i>-culture
was the most important factor to share about this fledgling community. &nbsp;While teaching was important it was not the
central factor, <i>koinonia</i> was primary. This stands in stark contrast to
the de-Judaized Christianity that developed only a few hundred years later with
its emphasis on “doctrine”.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .25in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Toward the end of his life, the Apostle John
reflected on the movement that began with Yeshua and summarized Yeshua’s hope
that they were “one, just as we are one” (John 17:20-26). In Luke’s first
account, Yeshua tells the story of a man who was a neighbor to the man who fell
among the robbers (Luke 10:29–37). In Acts 2:41-47, we see a snapshot summary
of what it means to live out this kind of ethic, and it is encapsulated in the
terms <i>koinonia/koinos</i>.<o:p></o:p></span></p>

<h4 style="text-align: left;">Breaking of Bread</h4><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .25in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Breaking<i> (3082) κλάσις klasis </i>(breaking,
the act of breaking)</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn18" name="_ftnref18" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[18]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> of Bread
(788) <i>ἄρτος artos</i> (bread; a loaf or thin cake of bread).</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn19" name="_ftnref19" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[19]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> The
“breaking of bread” is another phrase we do not often use in modern western
American English. One might assume it means to eat together. Textually and contextually,
however, the following observations can be made to fill-out our understanding
of the practice. The phrase “breaking of the bread” is used in Acts 2:42 and
Luke 24:35. Luke makes a point of noting that the feast of “Unleavened Bread”
is also called “Passover” (Luke 22:1). Later in this same section, in what has
become known as The Lord’s Supper, Jesus “took bread, and after giving thanks,
he broke it and gave it to them, saying, “this is my body which is given for
you. Do this in remembrance of me.” (Luke 22:14, LEB). Post resurrection, Jesus
met two of his followers as they traveled to Emmaus, Luke makes a point of
mentioning that “he was recognized by them in the breaking of the bread” (Luke
24:35, LEB). The summary provided by Luke for the activities of the early
church was “they were devoting themselves to the teaching of the apostles and
to fellowship, to the <i>breaking of bread</i> and to prayers.” (Acts 2:42).
These facts lead one to conclude that this was not as simple as a meal but did
include a meal (not a thimble of juice and a tiny wafer). Bauer agrees saying
that the ‘breaking of bread’, “</span><span style="font-size: 12.0pt; line-height: 200%;">emphasizes the close relationship between common meals among believers
and the Eucharist."</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn20" name="_ftnref20" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[20]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%;"> These meals also served as reminders of Jesus’ last
supper and what it came to represent.</span><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .25in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">The “Agape Meal” (as Sturdevant called it), “functioned
to help feed the poorer members of the church.”</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn21" name="_ftnref21" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[21]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> This
sense of community <i>koinonia</i> through sharing of food was part of the
larger context in which they “had everything in common” (Acts 2:44) and there
were “not even anyone needy among them” (Acts 4:34). Within the wider Ancient
Near East context, Shirokov, notes that, “Shared meals often expresses the
universal Near Eastern value of hospitality (Gen 18:1–8; Heb 13:2).”</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn22" name="_ftnref22" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[22]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> Jipp
also observes that Luke-Acts combined tell a story of the community putting
action to Jesus’ “teachings on food, possessions, and hospitality”.</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn23" name="_ftnref23" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[23]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">
Harrington shows that one of Jesus’ “most certain and controversial matters”
was “his custom of sharing meals with tax collectors and sinners”.</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn24" name="_ftnref24" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[24]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">
Reflecting on this, Manning states, "Nowhere in the New Testament is the
privileged position of turkeys, nobodies, and marginal people on the fringes of
society disclosed more dramatically than in Jesus' ministry of meal
sharing."</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn25" name="_ftnref25" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[25]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> Another
important observation about the meal motif in Luke-Acts is made by Chilton, “The
last public act of Jesus before his crucifixion was to declare that his meals
were the center of the kingdom” and also “the conviction that the light of the
kingdom radiated from that practice went hand in hand with the conviction that
the true master of the table, the rabbi who began it all, remained with their
fellowship.”</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn26" name="_ftnref26" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[26]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> While
breaking of bread was one aspect of this <i>koinonia</i>, Toussaint observes
that perhaps “breaking of bread” and “prayer” should be considered descriptions
of “fellowship”. He states, “The omission of ‘and’ between ‘fellowship’ and ‘to
the breaking of bread and to prayer’ indicates the last two activities are
appositional to fellowship.”</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn27" name="_ftnref27" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[27]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><o:p></o:p></span></p>

<h3 style="text-align: left;">Prayers</h3><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Prayers<i> (4666): προσευχή proseuchē, </i>means
“prayer”.</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn28" name="_ftnref28" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[28]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> Mounce notes that, “<i>proseuchē</i> is always
prayer to a deity; in the NT, it is used for prayers to Jesus (Eph. 1:16–17;
Rev. 5:8; 8:3–4) or to God (Rom. 15:30), never to pagan deities.”</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn29" name="_ftnref29" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[29]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> He also
notes that the Hebrew cognate for this concept is “</span><span dir="RTL" lang="HE" style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">תְּפִלָּה</span><span dir="LTR"></span><span dir="LTR"></span><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><span dir="LTR"></span><span dir="LTR"></span> (tepillâ)… a common word in the OT for
‘prayer, intercession, petition’.”</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn30" name="_ftnref30" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[30]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> But
beyond this basic definition, it helps to contextualize the concept of prayer
in its own Ancient Near East and Second Temple Judaism contexts. Spangler and
Tverberg note, “Unlike our tendency to focus on our own individual needs,
Jewish prayers tend to involve community prayer for the needs of the whole
people.”</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn31" name="_ftnref31" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[31]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> Further, Penner claimed that the Jewish community
knew two ways of praying; (1) “spontaneous” prayers that involved the “will,
emotion, and particular circumstances of the one praying” but (2) Judaism had
developed a second form of prayer that was “governed by formality” in which the
prayers were “fixed in an attempt to regulate or ritualize in some way the
religious experience of praying to the divine, and to transform continually and
regularly the worshipper's perspective to the liturgical worldview.”</span><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftn32" name="_ftnref32" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[32]</span></span><!--[endif]--></span></a><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"> Some
modern non-denominational protestants may find this second form “stuffy”;
however, some (such as the Catholics, Anglicans, and Episcopalians, and others)
find liturgy provides them with a sense of meditative depth, historical
longevity, and shared community. One associate of mine referred to these
written prayers as “dipping into a 2,000-year-old tradition”. As Penner noted
(above) the formal prayers have the effect of bringing the community together,
as the group forms a type of hive-mind. Two famous community prayers are the
Shema (Deuteronomy 6:4-5) and the Lord’s Prayer (Matthew 6:9-13; Luke 11:2-4).
That this second form of prayer was continued by, the Way, is shown by the very
next story after the summary chiasm; “Now, Peter and John were going up to the
temple at the <i><u>hour of prayer</u></i>, the ninth hour” (Acts 3:1).<o:p></o:p></span></p>

<h3 style="text-align: left;">Wisdom from the text of Acts 2:41-47</h3><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Fellowship <i>koinonia</i> was the defining
characteristic of the Way. <i>Koinonia</i> was exemplified by a community that
gathered regularly to listen to those who had been with Yeshua teach about the
promises regarding Yeshua in the Tanakh, and through the stories and parables
of Yeshua about the way the Kingdom of God community is to be lived out. The
Way followed the ancient Jewish customs of regular rhythm of prayers and built
their community around shared meals and shared resources. While not an
endorsement of government socialism, this community took care of the poor among
them so that nobody had any needs. Sometimes, this was facilitated by a
wealthier member selling property or belongings to give to those who had less.
Prayers (formal and informal) created an atmosphere that was centered on
Yahweh, with Yeshua as head of the assembly, through the leading of the Holy
Spirit. This community was no mere gathering of event attendees, they were “one
as we are one” (John 17:20-26).<o:p></o:p></span></p>

<h3 style="text-align: left;">Conclusion: Theological and Practical Implications</h3><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">The Way was known for their <i>koinonia</i>-culture
and therefore modern followers of Yeshua should have the same reputation. This
attribute, more than any other, should define the community. John’s gospel said
that we would be known as Yeshua’s disciples by the way we loved one another (John
13:35), and Acts describes this in practice as <i>koinonia</i>.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">While our modern contexts and cultures have
changed, we may still find wisdom in making sure these elements (teaching, <i>koinonia</i>-culture,
shared meals, and prayers) are present in our Jesus communities. However, that
may look different in any given context. Modern westerners do not share the ANE
culture of hospitality in the same way. We will find ways to contextualize
these themes in ways that fit our modern times and peculiarities.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">Anecdotally, as I was mid-stream writing this
paper; my son’s best-friend’s grandmother came over to say hello. She had heard
our washing machine was broken and we were washing our clothes in the bathtub
until we could afford a replacement. She took her grandson and my son, headed
30 miles away to Spokane, Washington, and bought us a washing machine, “just
because we love you guys so much”. If there was ever a living example of
Koinonia; I may have just experienced, it myself. Now we are all encouraged, “go
and do likewise” (Luke 10:29–37).</span><br clear="all" style="mso-special-character: line-break; page-break-before: always;" />
<b><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;"><o:p></o:p></span></b></p><p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><br /></p>

<h4 style="text-align: left;">Bibliography</h4><h1><o:p></o:p></h1>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoBibliography"><!--[if supportFields]><span style='mso-ascii-font-family:
"Times New Roman";mso-ascii-theme-font:major-bidi;mso-hansi-font-family:"Times New Roman";
mso-hansi-theme-font:major-bidi;mso-bidi-font-family:"Times New Roman";
mso-bidi-theme-font:major-bidi'><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_BIBL
{&quot;uncited&quot;:[],&quot;omitted&quot;:[],&quot;custom&quot;:[]}
CSL_BIBLIOGRAPHY <span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Bauer, David R. <i>The Book of Acts as Story: A
Narrative-Critical Study</i>. Grand Rapids, Michigan: Baker Academic, a
division of Baker Publishing Group, 2021.<o:p></o:p></span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Chilton, Bruce. <i>Pure
Kingdom: Jesus’ Vision of God</i>. Studying the Historical Jesus. Grand Rapids,
Mich. : London: Eerdmans ; Society for Prommoting Christian Knowledge, 1996.<o:p></o:p></span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Green, Joel B. <i>Discovering
Luke: Content, Interpretation, Reception</i>. Discovering Biblical Texts :
Content, Interpretation, Reception. Grand Rapids, Michigan: William B. Eerdmans
Publishing Co, 2021.<o:p></o:p></span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Harrington, Daniel J. <i>The
Synoptic Gospels Set Free: Preaching Without Anti-Judaism</i>. New York ;
Mahwah, NJ: Paulist Press, 2009.<o:p></o:p></span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Jipp, Joshua W. <i>Reading
Acts</i>. Cascade Companions. Eugene, Oregon: Cascade Books, 2018.<o:p></o:p></span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Knowles, Andrew. <i>The
Bible Guide</i>. 1st Augsburg books ed. Minneapolis, MN: Augsburg, 2001.<o:p></o:p></span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">“Logos Bible Software
8.17 SR-38.17.0.0022.” Faithlife Corporation, 2021 2000. logos.com.<o:p></o:p></span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Manning, Brennan. <i>The
Ragamuffin Gospel</i>. 2nd Edition. Sisters, Or: Multnomah Publishers, 2000.<o:p></o:p></span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Moraff, Jason. “‘Among
My Own Nation’: Reading the Way, Paul, and ‘the Jews’ in Acts within Judaism.”
Dissertation, Fuller Theological Seminary, School of Theology, Center for
Advanced Theological Studies, 2021.<o:p></o:p></span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Mounce, William D.,
ed. <i>Mounce’s Complete Expository Dictionary of Old &amp; New Testament Words</i>.
Grand Rapids, Mich: Zondervan, 2006.<o:p></o:p></span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Penner, Jeremy. <i>Patterns
of Daily Prayer in Second Temple Period Judaism</i>. Studies on the Texts of
the Desert of Judah, v. 104. Leiden ; Boston: Brill, 2012.<o:p></o:p></span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Pierson, Arthur T. <i>The
Acts of the Holy Spirit</i>. University of Virginia: Gospel Publishing House,
originally from University of Virginia, 1896.<o:p></o:p></span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Spangler, Ann, and
Lois Tverberg. <i>Sitting at the Feet of Rabbi Jesus: How the Jewishness of
Jesus Can Transform Your Faith</i>. Updated edition. Grand Rapids, Michigan:
Zondervan, 2018.<o:p></o:p></span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Sterling, Gregory E.
“‘Athletes of Virtue’: An Analysis of the Summaries in Acts (2:41-47; 4:32-35;
5:12-16).” <i>Journal of Biblical Literature</i> 113, no. 4 (1994): 679–96.
https://doi.org/10.2307/3266714.<o:p></o:p></span></p>

<p class="MsoBibliography"><i><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></i></p>

<p class="MsoBibliography"><i><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">The Lexham
Bible Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein, R.,
Mangum, D., Sinclair Wolcott, C., … Widder, W. (Eds.). (2016). In The Lexham
Bible Dictionary. Bellingham, WA: Lexham Press.</span></i><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;"> Billingham, WA: Leham Press, 2016. LexhamPress.com.<o:p></o:p></span></p>

<p class="MsoBibliography"><i><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></i></p>

<p class="MsoBibliography"><i><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">The Lexham
English Bible (LEB), Fourth Edition</span></i><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">.
Logo Bible Software. Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D.,
Dunham, J., Reimer, J. A., &amp; Wierenga, M. (Eds.). Bellingham, WA: Lexham
Press, 2010. http://www.lexhampress.com.<o:p></o:p></span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Walvoord, John F., Roy
B. Zuck, and Dallas Theological Seminary, eds. <i>The Bible Knowledge
Commentary: An Exposition of the Scriptures</i>. Wheaton, Ill: Victor Books,
1983.<o:p></o:p></span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">&nbsp;</span></p>

<p class="MsoBibliography"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">Wright, N. T., and
Michael F. Bird. <i>The New Testament in Its World: An Introduction to the
History, Literature, and Theology of the First Christians</i>. London : Grand
Rapids, MI: SPCK ; Zondervan Academic, 2019.<o:p></o:p></span></p>

<h4 style="line-height: 200%; text-align: left;"><span style="font-size: 12.0pt; line-height: 200%; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-ascii-theme-font: major-bidi; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-theme-font: major-bidi; mso-hansi-font-family: &quot;Times New Roman&quot;; mso-hansi-theme-font: major-bidi;">&nbsp;<br /></span>Notes:</h4>

<div>

<hr align="left" size="1" width="33%" />

<!--[endif]-->

<div id="ftn1">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref1" name="_ftn1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[1]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;4gQff6LO&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Arthur
T. Pierson, {\\i{}The Acts of the Holy Spirit} (University of Virginia: Gospel
Publishing House, originally from University of Virginia, 1896), 18; Also cited
in the following article: F. F. Bruce, \\uc0\\u8220{}The Bible: Book of the
Month: The Acts of the Apostles,\\uc0\\u8221{} Christianity Today (Washington,
D.C.: Christianity Today, 1956),
19.&quot;,&quot;plainCitation&quot;:&quot;Arthur T. Pierson, The Acts of the
Holy Spirit (University of Virginia: Gospel Publishing House, originally from
University of Virginia, 1896), 18; Also cited in the following article: F. F.
Bruce, “The Bible: Book of the Month: The Acts of the Apostles,” Christianity
Today (Washington, D.C.: Christianity Today, 1956),
19.&quot;,&quot;noteIndex&quot;:1},&quot;citationItems&quot;:[{&quot;id&quot;:1027,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/AKKUSAJ2&quot;],&quot;itemData&quot;:{&quot;id&quot;:1027,&quot;type&quot;:&quot;book&quot;,&quot;event-place&quot;:&quot;University
of
Virginia&quot;,&quot;language&quot;:&quot;en&quot;,&quot;note&quot;:&quot;Google-Books-ID:
4549AAAAYAAJ&quot;,&quot;number-of-pages&quot;:&quot;142&quot;,&quot;publisher&quot;:&quot;Gospel
Publishing House, originally from University of
Virginia&quot;,&quot;publisher-place&quot;:&quot;University of
Virginia&quot;,&quot;source&quot;:&quot;Google Books&quot;,&quot;title&quot;:&quot;The
Acts of the Holy
Spirit&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Pierson&quot;,&quot;given&quot;:&quot;Arthur
T.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1896&quot;]]}},&quot;locator&quot;:&quot;18;
Also cited in the following article: F. F. Bruce, “The Bible: Book of the
Month: The Acts of the Apostles,” Christianity Today (Washington, D.C.: Christianity
Today, 1956), 19.&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Arthur
T. Pierson, <i>The Acts of the Holy Spirit</i> (University of Virginia: Gospel
Publishing House, originally from University of Virginia, 1896), 18; Also cited
in the following article: F. F. Bruce, “The Bible: Book of the Month: The Acts
of the Apostles,” Christianity Today (Washington, D.C.: Christianity Today,
1956), 19.<!--[if supportFields]><span style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn2">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref2" name="_ftn2" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[2]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;EOLpkIY8&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;{\\i{}The
Lexham English Bible (LEB), Fourth Edition}, Logo Bible Software, Harris, W.
H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., &amp;
Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010),
http://www.lexhampress.com.&quot;,&quot;plainCitation&quot;:&quot;The Lexham
English Bible (LEB), Fourth Edition, Logo Bible Software, Harris, W. H., III,
Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., &amp;
Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010), http://www.lexhampress.com.&quot;,&quot;noteIndex&quot;:2},&quot;citationItems&quot;:[{&quot;id&quot;:49,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/2TDD6GYW&quot;],&quot;itemData&quot;:{&quot;id&quot;:49,&quot;type&quot;:&quot;book&quot;,&quot;collection-title&quot;:&quot;Harris,
W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A.,
&amp; Wierenga, M. (Eds.)&quot;,&quot;edition&quot;:&quot;Logo Bible
Software&quot;,&quot;event-place&quot;:&quot;Bellingham,
WA&quot;,&quot;publisher&quot;:&quot;Lexham
Press&quot;,&quot;publisher-place&quot;:&quot;Bellingham,
WA&quot;,&quot;source&quot;:&quot;Logo Bible Software&quot;,&quot;title&quot;:&quot;The
Lexham English Bible (LEB), Fourth
Edition&quot;,&quot;title-short&quot;:&quot;LEB&quot;,&quot;URL&quot;:&quot;http://www.lexhampress.com&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2010&quot;]],&quot;season&quot;:&quot;Copyright<span
style='mso-spacerun:yes'>  </span>, 2012, 2013 Lexham
Press&quot;}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><i>The
Lexham English Bible (LEB), Fourth Edition</i>, Logo Bible Software, Harris,
W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A.,
&amp; Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010),
http://www.lexhampress.com.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn3">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref3" name="_ftn3" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[3]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;GabpKmUE&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Joel
B. Green, {\\i{}Discovering Luke: Content, Interpretation, Reception},
Discovering Biblical Texts\\uc0\\u8239{}: Content, Interpretation, Reception
(Grand Rapids, Michigan: William B. Eerdmans Publishing Co, 2021), 112.&quot;,&quot;plainCitation&quot;:&quot;Joel
B. Green, Discovering Luke: Content, Interpretation, Reception, Discovering
Biblical Texts : Content, Interpretation, Reception (Grand Rapids, Michigan:
William B. Eerdmans Publishing Co, 2021),
112.&quot;,&quot;noteIndex&quot;:3},&quot;citationItems&quot;:[{&quot;id&quot;:783,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/3AQYJ9X9&quot;],&quot;itemData&quot;:{&quot;id&quot;:783,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;This
interpretation of Luke encourages in-depth study of the text and genuine
grappling with the theological and sociohistorical questions it raises. It
draws on a range of methodological interests (author-, text-, and
reader-centered) as complementary rather than mutually exclusive ways of
understanding the text. It also recognizes the importance of the reception
history of biblical texts, increasingly viewed as a vital aspect of
interpretation rather than an optional extra. Throughout Discovering Luke, Joel
Green gives readers strategies for reading the Gospel of Luke and guides them
through Luke's world in its historical, ideological, political, and economic contexts.
Green reviews key issues raised by the Gospel and connects these issues to
questions of how Luke should be interpreted
today&quot;,&quot;call-number&quot;:&quot;BS2595.52 .G74
2021&quot;,&quot;collection-title&quot;:&quot;Discovering Biblical texts :
content, interpretation, reception&quot;,&quot;event-place&quot;:&quot;Grand
Rapids,
Michigan&quot;,&quot;ISBN&quot;:&quot;978-0-8028-7496-2&quot;,&quot;note&quot;:&quot;OCLC:
on1237693511&quot;,&quot;number-of-pages&quot;:&quot;247&quot;,&quot;publisher&quot;:&quot;William
B. Eerdmans Publishing Co&quot;,&quot;publisher-place&quot;:&quot;Grand Rapids,
Michigan&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Discovering Luke: content, interpretation,
reception&quot;,&quot;title-short&quot;:&quot;Discovering
Luke&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Green&quot;,&quot;given&quot;:&quot;Joel
B.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2021&quot;]]}},&quot;locator&quot;:&quot;112&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Joel
B. Green, <i>Discovering Luke: Content, Interpretation, Reception</i>,
Discovering Biblical Texts : Content, Interpretation, Reception (Grand Rapids,
Michigan: William B. Eerdmans Publishing Co, 2021), 112.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn4">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref4" name="_ftn4" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[4]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;UxkhEJZ0&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Jason
Moraff, \\uc0\\u8220{}\\uc0\\u8216{}Among My Own Nation\\uc0\\u8217{}: Reading
the Way, Paul, and \\uc0\\u8216{}the Jews\\uc0\\u8217{} in Acts within
Judaism\\uc0\\u8221{} (Dissertation, Pasadena, CA, Fuller Theological Seminary,
School of Theology, Center for Advanced Theological Studies, 2021),
11\\uc0\\u8211{}12,
86\\uc0\\u8211{}93.&quot;,&quot;plainCitation&quot;:&quot;Jason Moraff, “‘Among
My Own Nation’: Reading the Way, Paul, and ‘the Jews’ in Acts within Judaism”
(Dissertation, Pasadena, CA, Fuller Theological Seminary, School of Theology,
Center for Advanced Theological Studies, 2021), 11–12,
86–93.&quot;,&quot;noteIndex&quot;:4},&quot;citationItems&quot;:[{&quot;id&quot;:968,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/52REMG8G&quot;],&quot;itemData&quot;:{&quot;id&quot;:968,&quot;type&quot;:&quot;thesis&quot;,&quot;abstract&quot;:&quot;A
dissertation submitted to the faculty of the School of Theology, Fuller
Theological Seminary in partial fulfillment of the requirements for the degree
of Doctor of Philosophy&quot;,&quot;event-place&quot;:&quot;Pasadena,
CA&quot;,&quot;genre&quot;:&quot;Dissertation&quot;,&quot;language&quot;:&quot;English&quot;,&quot;number-of-pages&quot;:&quot;315&quot;,&quot;publisher&quot;:&quot;Fuller
Theological Seminary, School of Theology, Center for Advanced Theological
Studies&quot;,&quot;publisher-place&quot;:&quot;Pasadena,
CA&quot;,&quot;title&quot;:&quot;\&quot;Among My Own Nation\&quot;: Reading the
Way, Paul, and \&quot;the Jews\&quot; in Acts within
Judaism&quot;,&quot;title-short&quot;:&quot;Among My Own
Nation&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Moraff&quot;,&quot;given&quot;:&quot;Jason&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2021&quot;,5]]}},&quot;locator&quot;:&quot;11-12,
86-93&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Jason
Moraff, “‘Among My Own Nation’: Reading the Way, Paul, and ‘the Jews’ in Acts
within Judaism” (Dissertation, Pasadena, CA, Fuller Theological Seminary,
School of Theology, Center for Advanced Theological Studies, 2021), 11–12,
86–93.<!--[if supportFields]><span style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn5">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref5" name="_ftn5" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[5]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;6OHpTE0m&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Moraff,
58.&quot;,&quot;plainCitation&quot;:&quot;Moraff, 58.&quot;,&quot;noteIndex&quot;:5},&quot;citationItems&quot;:[{&quot;id&quot;:968,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/52REMG8G&quot;],&quot;itemData&quot;:{&quot;id&quot;:968,&quot;type&quot;:&quot;thesis&quot;,&quot;abstract&quot;:&quot;A
dissertation submitted to the faculty of the School of Theology, Fuller
Theological Seminary in partial fulfillment of the requirements for the degree
of Doctor of Philosophy&quot;,&quot;event-place&quot;:&quot;Pasadena,
CA&quot;,&quot;genre&quot;:&quot;Dissertation&quot;,&quot;language&quot;:&quot;English&quot;,&quot;number-of-pages&quot;:&quot;315&quot;,&quot;publisher&quot;:&quot;Fuller
Theological Seminary, School of Theology, Center for Advanced Theological
Studies&quot;,&quot;publisher-place&quot;:&quot;Pasadena,
CA&quot;,&quot;title&quot;:&quot;\&quot;Among My Own Nation\&quot;: Reading the
Way, Paul, and \&quot;the Jews\&quot; in Acts within
Judaism&quot;,&quot;title-short&quot;:&quot;Among My Own
Nation&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Moraff&quot;,&quot;given&quot;:&quot;Jason&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2021&quot;,5]]}},&quot;locator&quot;:&quot;58&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Moraff, 58.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn6">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref6" name="_ftn6" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[6]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;uBEkvfiZ&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;David
R. Bauer, {\\i{}The Book of Acts as Story: A Narrative-Critical Study} (Grand
Rapids, Michigan: Baker Academic, a division of Baker Publishing Group, 2021),
51\\uc0\\u8211{}18; Figures 3.1 &amp;
3.2.&quot;,&quot;plainCitation&quot;:&quot;David R. Bauer, The Book of Acts as
Story: A Narrative-Critical Study (Grand Rapids, Michigan: Baker Academic, a
division of Baker Publishing Group, 2021), 51–18; Figures 3.1 &amp;
3.2.&quot;,&quot;noteIndex&quot;:6},&quot;citationItems&quot;:[{&quot;id&quot;:782,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/S675ER6R&quot;],&quot;itemData&quot;:{&quot;id&quot;:782,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;\&quot;A
senior New Testament scholar and teacher helps students understand the
historical, literary, and theological issues of the Book of Acts and introduces
key concepts in the field of narrative
criticism\&quot;--&quot;,&quot;call-number&quot;:&quot;BS2625.52 .B38
2021&quot;,&quot;event-place&quot;:&quot;Grand Rapids,
Michigan&quot;,&quot;ISBN&quot;:&quot;978-1-5409-6438-0&quot;,&quot;number-of-pages&quot;:&quot;284&quot;,&quot;publisher&quot;:&quot;Baker
Academic, a division of Baker Publishing
Group&quot;,&quot;publisher-place&quot;:&quot;Grand Rapids,
Michigan&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;The book of Acts as story: a
narrative-critical study&quot;,&quot;title-short&quot;:&quot;The book of Acts
as
story&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Bauer&quot;,&quot;given&quot;:&quot;David
R.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2021&quot;]]}},&quot;locator&quot;:&quot;51-18;
Figures 3.1 &amp;
3.2&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->David
R. Bauer, <i>The Book of Acts as Story: A Narrative-Critical Study</i> (Grand Rapids,
Michigan: Baker Academic, a division of Baker Publishing Group, 2021), 51–18;
Figures 3.1 &amp; 3.2.<!--[if supportFields]><span style='mso-element:
field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn7">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref7" name="_ftn7" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[7]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;0lvE38oJ&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;\\uc0\\u8220{}Logos
Bible Software 8.17 SR-38.17.0.0022\\uc0\\u8221{} (Faithlife Corporation, 2021
2000), n. Logos Word Search,
logos.com.&quot;,&quot;plainCitation&quot;:&quot;“Logos Bible Software 8.17
SR-38.17.0.0022” (Faithlife Corporation, 2021 2000), n. Logos Word Search,
logos.com.&quot;,&quot;noteIndex&quot;:7},&quot;citationItems&quot;:[{&quot;id&quot;:54,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/23ZFEBAJ&quot;],&quot;itemData&quot;:{&quot;id&quot;:54,&quot;type&quot;:&quot;software&quot;,&quot;abstract&quot;:&quot;Logos
Bible Software 8.17 SR-38.17.0.0022 - Many of the resources used with Logos
Bible Software are protected by copyright. Copyright information for specific
resources is available from the “Resource information” view in a resource
panel.&quot;,&quot;license&quot;:&quot;Faithlife Corporation, unless otherwise
cited.&quot;,&quot;publisher&quot;:&quot;Faithlife
Corporation&quot;,&quot;title&quot;:&quot;Logos Bible Software 8.17
SR-38.17.0.0022&quot;,&quot;URL&quot;:&quot;logos.com&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2000&quot;]],&quot;season&quot;:&quot;2021&quot;}},&quot;locator&quot;:&quot;Logos
Word
Search&quot;,&quot;label&quot;:&quot;note&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->“Logos
Bible Software 8.17 SR-38.17.0.0022” (Faithlife Corporation, 2021 2000), n.
Logos Word Search, logos.com.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn8">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref8" name="_ftn8" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[8]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;FvFqfd7k&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Gregory
E. Sterling, \\uc0\\u8220{}\\uc0\\u8216{}Athletes of Virtue\\uc0\\u8217{}: An
Analysis of the Summaries in Acts (2:41-47; 4:32-35; 5:12-16),\\uc0\\u8221{}
{\\i{}Journal of Biblical Literature} 113, no. 4 (1994): 679,
https://doi.org/10.2307/3266714.&quot;,&quot;plainCitation&quot;:&quot;Gregory
E. Sterling, “‘Athletes of Virtue’: An Analysis of the Summaries in Acts (2:41-47;
4:32-35; 5:12-16),” Journal of Biblical Literature 113, no. 4 (1994): 679,
https://doi.org/10.2307/3266714.&quot;,&quot;noteIndex&quot;:8},&quot;citationItems&quot;:[{&quot;id&quot;:939,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/QRXHNZQK&quot;],&quot;itemData&quot;:{&quot;id&quot;:939,&quot;type&quot;:&quot;article-journal&quot;,&quot;container-title&quot;:&quot;Journal
of Biblical
Literature&quot;,&quot;DOI&quot;:&quot;10.2307/3266714&quot;,&quot;ISSN&quot;:&quot;0021-9231&quot;,&quot;issue&quot;:&quot;4&quot;,&quot;note&quot;:&quot;publisher:
Society of Biblical Literature&quot;,&quot;page&quot;:&quot;679-696&quot;,&quot;source&quot;:&quot;JSTOR&quot;,&quot;title&quot;:&quot;\&quot;Athletes
of Virtue\&quot;: An Analysis of the Summaries in Acts (2:41-47; 4:32-35;
5:12-16)&quot;,&quot;title-short&quot;:&quot;Athletes of
Virtue&quot;,&quot;URL&quot;:&quot;https://www.jstor.org/stable/3266714&quot;,&quot;volume&quot;:&quot;113&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Sterling&quot;,&quot;given&quot;:&quot;Gregory
E.&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2022&quot;,9,24]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1994&quot;]]}},&quot;locator&quot;:&quot;679&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Gregory
E. Sterling, “‘Athletes of Virtue’: An Analysis of the Summaries in Acts
(2:41-47; 4:32-35; 5:12-16),” <i>Journal of Biblical Literature</i> 113, no. 4
(1994): 679, https://doi.org/10.2307/3266714.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn9">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref9" name="_ftn9" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[9]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;nfgNCJMY&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Bauer,
{\\i{}The Book of Acts as Story}, 95.&quot;,&quot;plainCitation&quot;:&quot;Bauer,
The Book of Acts as Story,
95.&quot;,&quot;noteIndex&quot;:9},&quot;citationItems&quot;:[{&quot;id&quot;:782,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/S675ER6R&quot;],&quot;itemData&quot;:{&quot;id&quot;:782,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;\&quot;A
senior New Testament scholar and teacher helps students understand the
historical, literary, and theological issues of the Book of Acts and introduces
key concepts in the field of narrative
criticism\&quot;--&quot;,&quot;call-number&quot;:&quot;BS2625.52 .B38
2021&quot;,&quot;event-place&quot;:&quot;Grand Rapids,
Michigan&quot;,&quot;ISBN&quot;:&quot;978-1-5409-6438-0&quot;,&quot;number-of-pages&quot;:&quot;284&quot;,&quot;publisher&quot;:&quot;Baker
Academic, a division of Baker Publishing
Group&quot;,&quot;publisher-place&quot;:&quot;Grand Rapids,
Michigan&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;The book of Acts as story: a
narrative-critical study&quot;,&quot;title-short&quot;:&quot;The book of Acts
as story&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Bauer&quot;,&quot;given&quot;:&quot;David
R.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2021&quot;]]}},&quot;locator&quot;:&quot;95&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Bauer,
<i>The Book of Acts as Story</i>, 95.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn10">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref10" name="_ftn10" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[10]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;JndCwnEr&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Andrew
Knowles, {\\i{}The Bible Guide}, 1st Augsburg books ed (Minneapolis, MN:
Augsburg, 2001), 540\\uc0\\u8211{}41.&quot;,&quot;plainCitation&quot;:&quot;Andrew
Knowles, The Bible Guide, 1st Augsburg books ed (Minneapolis, MN: Augsburg,
2001),
540–41.&quot;,&quot;noteIndex&quot;:10},&quot;citationItems&quot;:[{&quot;id&quot;:263,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/7Z38J5BZ&quot;],&quot;itemData&quot;:{&quot;id&quot;:263,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS475.3
.K66 2001&quot;,&quot;edition&quot;:&quot;1st Augsburg books ed&quot;,&quot;event-place&quot;:&quot;Minneapolis,
MN&quot;,&quot;ISBN&quot;:&quot;978-0-8066-4356-4&quot;,&quot;number-of-pages&quot;:&quot;718&quot;,&quot;publisher&quot;:&quot;Augsburg&quot;,&quot;publisher-place&quot;:&quot;Minneapolis,
MN&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;The Bible
guide&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Knowles&quot;,&quot;given&quot;:&quot;Andrew&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2001&quot;]]}},&quot;locator&quot;:&quot;540-541&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Andrew
Knowles, <i>The Bible Guide</i>, 1st Augsburg books ed (Minneapolis, MN:
Augsburg, 2001), 540–41.<!--[if supportFields]><span style='mso-element:
field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn11">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref11" name="_ftn11" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[11]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;BitYMcdD&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;William
D. Mounce, ed., {\\i{}Mounce\\uc0\\u8217{}s Complete Expository Dictionary of
Old &amp; New Testament Words} (Grand Rapids, Mich: Zondervan, 2006),
1123.&quot;,&quot;plainCitation&quot;:&quot;William D. Mounce, ed., Mounce’s
Complete Expository Dictionary of Old &amp; New Testament Words (Grand Rapids,
Mich: Zondervan, 2006),
1123.&quot;,&quot;noteIndex&quot;:11},&quot;citationItems&quot;:[{&quot;id&quot;:276,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/WGGI4T74&quot;],&quot;itemData&quot;:{&quot;id&quot;:276,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS440
.M63 2006&quot;,&quot;event-place&quot;:&quot;Grand Rapids,
Mich&quot;,&quot;ISBN&quot;:&quot;978-0-310-24878-1&quot;,&quot;language&quot;:&quot;eng
grc heb&quot;,&quot;note&quot;:&quot;OCLC:
ocm64453290&quot;,&quot;number-of-pages&quot;:&quot;1316&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Mich&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Mounce's complete expository dictionary of
Old &amp; New Testament
words&quot;,&quot;editor&quot;:[{&quot;family&quot;:&quot;Mounce&quot;,&quot;given&quot;:&quot;William
D.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2006&quot;]]}},&quot;locator&quot;:&quot;1123&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->William
D. Mounce, ed., <i>Mounce’s Complete Expository Dictionary of Old &amp; New
Testament Words</i> (Grand Rapids, Mich: Zondervan, 2006), 1123.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn12">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref12" name="_ftn12" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[12]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;DOdYc2cx&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;{\\i{}The
Lexham Bible Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein,
R., Mangum, D., Sinclair Wolcott, C., \\uc0\\u8230{} Widder, W. (Eds.). (2016).
In The Lexham Bible Dictionary. Bellingham, WA: Lexham Press.} (Billingham, WA:
Leham Press, 2016), sec. Dan N\\uc0\\u228{}sselqvist,
\\uc0\\u8220{}Disciple,\\uc0\\u8221{}
LexhamPress.com.&quot;,&quot;plainCitation&quot;:&quot;The Lexham Bible
Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein, R., Mangum,
D., Sinclair Wolcott, C., … Widder, W. (Eds.). (2016). In The Lexham Bible
Dictionary. Bellingham, WA: Lexham Press. (Billingham, WA: Leham Press, 2016),
sec. Dan Nässelqvist, “Disciple,” LexhamPress.com.&quot;,&quot;noteIndex&quot;:12},&quot;citationItems&quot;:[{&quot;id&quot;:59,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/GM87FDTW&quot;],&quot;itemData&quot;:{&quot;id&quot;:59,&quot;type&quot;:&quot;book&quot;,&quot;event-place&quot;:&quot;Billingham,
WA&quot;,&quot;publisher&quot;:&quot;Leham
Press&quot;,&quot;publisher-place&quot;:&quot;Billingham,
WA&quot;,&quot;title&quot;:&quot;The Lexham Bible Dictionary - Barry, J. D.,
Bomar, D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott, C., …
Widder, W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham, WA:
Lexham Press.&quot;,&quot;title-short&quot;:&quot;Lexham Bible
Dictionary&quot;,&quot;URL&quot;:&quot;LexhamPress.com&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2016&quot;]]}},&quot;locator&quot;:&quot;Dan
Nässelqvist,
“Disciple,”&quot;,&quot;label&quot;:&quot;section&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><i>The
Lexham Bible Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein,
R., Mangum, D., Sinclair Wolcott, C., … Widder, W. (Eds.). (2016). In The
Lexham Bible Dictionary. Bellingham, WA: Lexham Press.</i>
(Billingham, WA: Leham Press, 2016), sec. Dan Nässelqvist, “Disciple,”
LexhamPress.com.<!--[if supportFields]><span style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn13">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref13" name="_ftn13" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[13]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION {&quot;citationID&quot;:&quot;eWEQJCQW&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Ann
Spangler and Lois Tverberg, {\\i{}Sitting at the Feet of Rabbi Jesus: How the
Jewishness of Jesus Can Transform Your Faith}, Updated edition (Grand Rapids,
Michigan: Zondervan, 2018), 69.&quot;,&quot;plainCitation&quot;:&quot;Ann
Spangler and Lois Tverberg, Sitting at the Feet of Rabbi Jesus: How the
Jewishness of Jesus Can Transform Your Faith, Updated edition (Grand Rapids,
Michigan: Zondervan, 2018),
69.&quot;,&quot;noteIndex&quot;:13},&quot;citationItems&quot;:[{&quot;id&quot;:119,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/VFB8VX5A&quot;],&quot;itemData&quot;:{&quot;id&quot;:119,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;Sitting
at the Feet of Rabbi Jesus takes readers on a fascinating journey, helping them
discover how learning about the Jewish world of Jesus can enrich their own
faith. This newly expanded softcover edition includes a discussion guide and a
Jewish Seder liturgy&quot;,&quot;call-number&quot;:&quot;BT590.J8 S63
2018&quot;,&quot;edition&quot;:&quot;Updated
edition&quot;,&quot;event-place&quot;:&quot;Grand Rapids, Michigan&quot;,&quot;ISBN&quot;:&quot;978-0-310-33069-1&quot;,&quot;number-of-pages&quot;:&quot;301&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Michigan&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Sitting at the Feet of Rabbi Jesus: How the
Jewishness of Jesus Can Transform Your
Faith&quot;,&quot;title-short&quot;:&quot;Sitting at the feet of Rabbi
Jesus&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Spangler&quot;,&quot;given&quot;:&quot;Ann&quot;},{&quot;family&quot;:&quot;Tverberg&quot;,&quot;given&quot;:&quot;Lois&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2018&quot;]]}},&quot;locator&quot;:&quot;69&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Ann
Spangler and Lois Tverberg, <i>Sitting at the Feet of Rabbi Jesus: How the
Jewishness of Jesus Can Transform Your Faith</i>, Updated edition (Grand
Rapids, Michigan: Zondervan, 2018), 69.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn14">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref14" name="_ftn14" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[14]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;rUF3HZU1&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Mounce,
{\\i{}Mounce\\uc0\\u8217{}s Complete Expository Dictionary of Old &amp; New
Testament Words}, 1192.&quot;,&quot;plainCitation&quot;:&quot;Mounce, Mounce’s
Complete Expository Dictionary of Old &amp; New Testament Words,
1192.&quot;,&quot;noteIndex&quot;:14},&quot;citationItems&quot;:[{&quot;id&quot;:276,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/WGGI4T74&quot;],&quot;itemData&quot;:{&quot;id&quot;:276,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS440
.M63 2006&quot;,&quot;event-place&quot;:&quot;Grand Rapids, Mich&quot;,&quot;ISBN&quot;:&quot;978-0-310-24878-1&quot;,&quot;language&quot;:&quot;eng
grc heb&quot;,&quot;note&quot;:&quot;OCLC:
ocm64453290&quot;,&quot;number-of-pages&quot;:&quot;1316&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Mich&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Mounce's complete expository dictionary of
Old &amp; New Testament
words&quot;,&quot;editor&quot;:[{&quot;family&quot;:&quot;Mounce&quot;,&quot;given&quot;:&quot;William
D.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2006&quot;]]}},&quot;locator&quot;:&quot;1192&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Mounce,
<i>Mounce’s Complete Expository Dictionary of Old &amp; New Testament Words</i>,
1192.<!--[if supportFields]><span style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn15">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref15" name="_ftn15" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[15]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;m92SzCtE&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Mounce,
247.&quot;,&quot;plainCitation&quot;:&quot;Mounce, 247.&quot;,&quot;noteIndex&quot;:15},&quot;citationItems&quot;:[{&quot;id&quot;:276,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/WGGI4T74&quot;],&quot;itemData&quot;:{&quot;id&quot;:276,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS440
.M63 2006&quot;,&quot;event-place&quot;:&quot;Grand Rapids,
Mich&quot;,&quot;ISBN&quot;:&quot;978-0-310-24878-1&quot;,&quot;language&quot;:&quot;eng
grc heb&quot;,&quot;note&quot;:&quot;OCLC:
ocm64453290&quot;,&quot;number-of-pages&quot;:&quot;1316&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Mich&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Mounce's complete expository dictionary of
Old &amp; New Testament
words&quot;,&quot;editor&quot;:[{&quot;family&quot;:&quot;Mounce&quot;,&quot;given&quot;:&quot;William
D.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2006&quot;]]}},&quot;locator&quot;:&quot;247&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Mounce, 247.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn16">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref16" name="_ftn16" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[16]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;WkbNH0Oh&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;N.
T. Wright and Michael F. Bird, {\\i{}The New Testament in Its World: An Introduction
to the History, Literature, and Theology of the First Christians}
(London\\uc0\\u8239{}: Grand Rapids, MI: SPCK\\uc0\\u8239{}; Zondervan
Academic, 2019), 630\\uc0\\u8211{}32.&quot;,&quot;plainCitation&quot;:&quot;N.
T. Wright and Michael F. Bird, The New Testament in Its World: An Introduction
to the History, Literature, and Theology of the First Christians (London :
Grand Rapids, MI: SPCK ; Zondervan Academic, 2019),
630–32.&quot;,&quot;noteIndex&quot;:16},&quot;citationItems&quot;:[{&quot;id&quot;:22,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/MGER9ADM&quot;],&quot;itemData&quot;:{&quot;id&quot;:22,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;\&quot;The
New Testament in Its World brings together decades of ground-breaking research,
writing, and teaching into one volume that will open readers' eyes to the
larger world of the New Testament. It presents the New Testament books as
historical, literary, and social phenomena located in the world of Second
Temple Judaism, amidst Greco-Roman politics and culture, and within early
Christianity. \&quot;--&quot;,&quot;call-number&quot;:&quot;BS2330.3 .W[right]&quot;,&quot;event-place&quot;:&quot;London
: Grand Rapids,
MI&quot;,&quot;ISBN&quot;:&quot;978-0-310-49930-5&quot;,&quot;note&quot;:&quot;OCLC:
on1090200946&quot;,&quot;number-of-pages&quot;:&quot;987&quot;,&quot;publisher&quot;:&quot;SPCK
; Zondervan Academic&quot;,&quot;publisher-place&quot;:&quot;London : Grand
Rapids, MI&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;The New Testament in its world: an
introduction to the history, literature, and theology of the first
Christians&quot;,&quot;title-short&quot;:&quot;The New Testament in its
world&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Wright&quot;,&quot;given&quot;:&quot;N.
T.&quot;},{&quot;family&quot;:&quot;Bird&quot;,&quot;given&quot;:&quot;Michael
F.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2019&quot;]]}},&quot;locator&quot;:&quot;630-632&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->N. T.
Wright and Michael F. Bird, <i>The New Testament in Its World: An Introduction
to the History, Literature, and Theology of the First Christians</i> (London :
Grand Rapids, MI: SPCK ; Zondervan Academic, 2019), 630–32.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn17">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref17" name="_ftn17" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[17]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;xnf3uwZu&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Mounce,
{\\i{}Mounce\\uc0\\u8217{}s Complete Expository Dictionary of Old &amp; New
Testament Words}, 1192.&quot;,&quot;plainCitation&quot;:&quot;Mounce, Mounce’s
Complete Expository Dictionary of Old &amp; New Testament Words,
1192.&quot;,&quot;noteIndex&quot;:17},&quot;citationItems&quot;:[{&quot;id&quot;:276,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/WGGI4T74&quot;],&quot;itemData&quot;:{&quot;id&quot;:276,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS440
.M63 2006&quot;,&quot;event-place&quot;:&quot;Grand Rapids,
Mich&quot;,&quot;ISBN&quot;:&quot;978-0-310-24878-1&quot;,&quot;language&quot;:&quot;eng
grc heb&quot;,&quot;note&quot;:&quot;OCLC:
ocm64453290&quot;,&quot;number-of-pages&quot;:&quot;1316&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Mich&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Mounce's complete expository dictionary of
Old &amp; New Testament
words&quot;,&quot;editor&quot;:[{&quot;family&quot;:&quot;Mounce&quot;,&quot;given&quot;:&quot;William
D.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2006&quot;]]}},&quot;locator&quot;:&quot;1192&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Mounce,
<i>Mounce’s Complete Expository Dictionary of Old &amp; New Testament Words</i>,
1192.<!--[if supportFields]><span style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn18">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref18" name="_ftn18" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[18]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;X7DhVZDX&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Mounce,
1190.&quot;,&quot;plainCitation&quot;:&quot;Mounce,
1190.&quot;,&quot;noteIndex&quot;:18},&quot;citationItems&quot;:[{&quot;id&quot;:276,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/WGGI4T74&quot;],&quot;itemData&quot;:{&quot;id&quot;:276,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS440
.M63 2006&quot;,&quot;event-place&quot;:&quot;Grand Rapids,
Mich&quot;,&quot;ISBN&quot;:&quot;978-0-310-24878-1&quot;,&quot;language&quot;:&quot;eng
grc heb&quot;,&quot;note&quot;:&quot;OCLC:
ocm64453290&quot;,&quot;number-of-pages&quot;:&quot;1316&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Mich&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Mounce's complete expository dictionary of
Old &amp; New Testament
words&quot;,&quot;editor&quot;:[{&quot;family&quot;:&quot;Mounce&quot;,&quot;given&quot;:&quot;William
D.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2006&quot;]]}},&quot;locator&quot;:&quot;1190&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Mounce, 1190.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn19">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref19" name="_ftn19" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[19]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;zyHK3j0t&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Mounce,
1097.&quot;,&quot;plainCitation&quot;:&quot;Mounce, 1097.&quot;,&quot;noteIndex&quot;:19},&quot;citationItems&quot;:[{&quot;id&quot;:276,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/WGGI4T74&quot;],&quot;itemData&quot;:{&quot;id&quot;:276,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS440
.M63 2006&quot;,&quot;event-place&quot;:&quot;Grand Rapids,
Mich&quot;,&quot;ISBN&quot;:&quot;978-0-310-24878-1&quot;,&quot;language&quot;:&quot;eng
grc heb&quot;,&quot;note&quot;:&quot;OCLC:
ocm64453290&quot;,&quot;number-of-pages&quot;:&quot;1316&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Mich&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Mounce's complete expository dictionary of
Old &amp; New Testament
words&quot;,&quot;editor&quot;:[{&quot;family&quot;:&quot;Mounce&quot;,&quot;given&quot;:&quot;William
D.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2006&quot;]]}},&quot;locator&quot;:&quot;1097&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Mounce, 1097.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn20">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref20" name="_ftn20" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[20]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;CDhn1cpC&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Bauer,
{\\i{}The Book of Acts as Story}, 94.&quot;,&quot;plainCitation&quot;:&quot;Bauer,
The Book of Acts as Story,
94.&quot;,&quot;noteIndex&quot;:20},&quot;citationItems&quot;:[{&quot;id&quot;:782,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/S675ER6R&quot;],&quot;itemData&quot;:{&quot;id&quot;:782,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;\&quot;A
senior New Testament scholar and teacher helps students understand the historical,
literary, and theological issues of the Book of Acts and introduces key
concepts in the field of narrative
criticism\&quot;--&quot;,&quot;call-number&quot;:&quot;BS2625.52 .B38
2021&quot;,&quot;event-place&quot;:&quot;Grand Rapids, Michigan&quot;,&quot;ISBN&quot;:&quot;978-1-5409-6438-0&quot;,&quot;number-of-pages&quot;:&quot;284&quot;,&quot;publisher&quot;:&quot;Baker
Academic, a division of Baker Publishing
Group&quot;,&quot;publisher-place&quot;:&quot;Grand Rapids,
Michigan&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;The book of Acts as story: a narrative-critical
study&quot;,&quot;title-short&quot;:&quot;The book of Acts as
story&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Bauer&quot;,&quot;given&quot;:&quot;David
R.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2021&quot;]]}},&quot;locator&quot;:&quot;94&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Bauer,
<i>The Book of Acts as Story</i>, 94.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn21">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref21" name="_ftn21" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[21]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;6e2Zya6E&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;{\\i{}Lexham
Bible Dictionary}, sec. Jason S. Sturdevant, \\uc0\\u8220{}Agape Meal,.\\uc0\\u8221{}&quot;,&quot;plainCitation&quot;:&quot;Lexham
Bible Dictionary, sec. Jason S. Sturdevant, “Agape
Meal,.”&quot;,&quot;noteIndex&quot;:21},&quot;citationItems&quot;:[{&quot;id&quot;:59,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/GM87FDTW&quot;],&quot;itemData&quot;:{&quot;id&quot;:59,&quot;type&quot;:&quot;book&quot;,&quot;event-place&quot;:&quot;Billingham,
WA&quot;,&quot;publisher&quot;:&quot;Leham
Press&quot;,&quot;publisher-place&quot;:&quot;Billingham,
WA&quot;,&quot;title&quot;:&quot;The Lexham Bible Dictionary - Barry, J. D.,
Bomar, D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott, C., …
Widder, W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham, WA:
Lexham Press.&quot;,&quot;title-short&quot;:&quot;Lexham Bible
Dictionary&quot;,&quot;URL&quot;:&quot;LexhamPress.com&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2016&quot;]]}},&quot;locator&quot;:&quot;Jason
S. Sturdevant, “Agape
Meal,”&quot;,&quot;label&quot;:&quot;section&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><i>Lexham
Bible Dictionary</i>, sec. Jason S. Sturdevant, “Agape Meal,.”<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn22">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref22" name="_ftn22" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[22]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;Q481X6bV&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;{\\i{}Lexham
Bible Dictionary}, sec. Peter Shirokov, \\uc0\\u8220{}Meal Customs,.\\uc0\\u8221{}&quot;,&quot;plainCitation&quot;:&quot;Lexham
Bible Dictionary, sec. Peter Shirokov, “Meal
Customs,.”&quot;,&quot;noteIndex&quot;:22},&quot;citationItems&quot;:[{&quot;id&quot;:59,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/GM87FDTW&quot;],&quot;itemData&quot;:{&quot;id&quot;:59,&quot;type&quot;:&quot;book&quot;,&quot;event-place&quot;:&quot;Billingham,
WA&quot;,&quot;publisher&quot;:&quot;Leham
Press&quot;,&quot;publisher-place&quot;:&quot;Billingham,
WA&quot;,&quot;title&quot;:&quot;The Lexham Bible Dictionary - Barry, J. D.,
Bomar, D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott, C., …
Widder, W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham, WA:
Lexham Press.&quot;,&quot;title-short&quot;:&quot;Lexham Bible
Dictionary&quot;,&quot;URL&quot;:&quot;LexhamPress.com&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2016&quot;]]}},&quot;locator&quot;:&quot;Peter
Shirokov, “Meal
Customs,”&quot;,&quot;label&quot;:&quot;section&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><i>Lexham
Bible Dictionary</i>, sec. Peter Shirokov, “Meal Customs,.”<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn23">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref23" name="_ftn23" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[23]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;1BORYRpj&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Joshua
W. Jipp, {\\i{}Reading Acts}, Cascade Companions (Eugene, Oregon: Cascade
Books, 2018), 49\\uc0\\u8211{}50.&quot;,&quot;plainCitation&quot;:&quot;Joshua
W. Jipp, Reading Acts, Cascade Companions (Eugene, Oregon: Cascade Books,
2018),
49–50.&quot;,&quot;noteIndex&quot;:23},&quot;citationItems&quot;:[{&quot;id&quot;:781,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/86TK2SZI&quot;],&quot;itemData&quot;:{&quot;id&quot;:781,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS2625.52
.J57 2018&quot;,&quot;collection-title&quot;:&quot;Cascade
companions&quot;,&quot;event-place&quot;:&quot;Eugene,
Oregon&quot;,&quot;ISBN&quot;:&quot;978-1-4982-9304-4&quot;,&quot;note&quot;:&quot;OCLC:
on1037060156&quot;,&quot;number-of-pages&quot;:&quot;160&quot;,&quot;publisher&quot;:&quot;Cascade
Books&quot;,&quot;publisher-place&quot;:&quot;Eugene,
Oregon&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Reading
Acts&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Jipp&quot;,&quot;given&quot;:&quot;Joshua
W.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2018&quot;]]}},&quot;locator&quot;:&quot;49-50&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Joshua
W. Jipp, <i>Reading Acts</i>, Cascade Companions (Eugene, Oregon: Cascade
Books, 2018), 49–50.<!--[if supportFields]><span style='mso-element:
field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn24">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref24" name="_ftn24" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[24]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;aR4SNkCv&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Daniel
J. Harrington, {\\i{}The Synoptic Gospels Set Free: Preaching Without
Anti-Judaism} (New York\\uc0\\u8239{}; Mahwah, NJ: Paulist Press, 2009),
155.&quot;,&quot;plainCitation&quot;:&quot;Daniel J. Harrington, The Synoptic
Gospels Set Free: Preaching Without Anti-Judaism (New York ; Mahwah, NJ:
Paulist Press, 2009), 155.&quot;,&quot;noteIndex&quot;:24},&quot;citationItems&quot;:[{&quot;id&quot;:118,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/CXCYLEBF&quot;],&quot;itemData&quot;:{&quot;id&quot;:118,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS2555.52
.H325 2009&quot;,&quot;event-place&quot;:&quot;New York ; Mahwah,
NJ&quot;,&quot;ISBN&quot;:&quot;978-0-8091-4583-6&quot;,&quot;number-of-pages&quot;:&quot;231&quot;,&quot;publisher&quot;:&quot;Paulist
Press&quot;,&quot;publisher-place&quot;:&quot;New York ; Mahwah,
NJ&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;The Synoptic Gospels Set Free: Preaching
Without Anti-Judaism&quot;,&quot;title-short&quot;:&quot;The Synoptic Gospels
set
free&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Harrington&quot;,&quot;given&quot;:&quot;Daniel
J.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2009&quot;]]}},&quot;locator&quot;:&quot;155&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Daniel
J. Harrington, <i>The Synoptic Gospels Set Free: Preaching Without Anti-Judaism</i>
(New York ; Mahwah, NJ: Paulist Press, 2009), 155.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn25">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref25" name="_ftn25" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[25]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;rPRjepta&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Brennan
Manning, {\\i{}The Ragamuffin Gospel}, 2nd Edition (Sisters, Or: Multnomah
Publishers, 2000), 58.&quot;,&quot;plainCitation&quot;:&quot;Brennan Manning,
The Ragamuffin Gospel, 2nd Edition (Sisters, Or: Multnomah Publishers, 2000),
58.&quot;,&quot;noteIndex&quot;:25},&quot;citationItems&quot;:[{&quot;id&quot;:165,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/39SVIJTK&quot;],&quot;itemData&quot;:{&quot;id&quot;:165,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BT140
.M365 2000&quot;,&quot;edition&quot;:&quot;2nd
Edition&quot;,&quot;event-place&quot;:&quot;Sisters,
Or&quot;,&quot;ISBN&quot;:&quot;978-1-57673-716-3&quot;,&quot;number-of-pages&quot;:&quot;235&quot;,&quot;publisher&quot;:&quot;Multnomah
Publishers&quot;,&quot;publisher-place&quot;:&quot;Sisters,
Or&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;The ragamuffin
Gospel&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Manning&quot;,&quot;given&quot;:&quot;Brennan&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2000&quot;]]}},&quot;locator&quot;:&quot;58&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Brennan
Manning, <i>The Ragamuffin Gospel</i>, 2nd Edition (Sisters, Or: Multnomah
Publishers, 2000), 58.<!--[if supportFields]><span style='mso-element:
field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn26">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref26" name="_ftn26" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[26]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;QxVpLeWO&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Bruce
Chilton, {\\i{}Pure Kingdom: Jesus\\uc0\\u8217{} Vision of God}, Studying the
Historical Jesus (Grand Rapids, Mich.\\uc0\\u8239{}: London:
Eerdmans\\uc0\\u8239{}; Society for Prommoting Christian Knowledge, 1996),
126.&quot;,&quot;plainCitation&quot;:&quot;Bruce Chilton, Pure Kingdom: Jesus’
Vision of God, Studying the Historical Jesus (Grand Rapids, Mich. : London:
Eerdmans ; Society for Prommoting Christian Knowledge, 1996),
126.&quot;,&quot;noteIndex&quot;:26},&quot;citationItems&quot;:[{&quot;id&quot;:94,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/DFZRZQ67&quot;],&quot;itemData&quot;:{&quot;id&quot;:94,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS2417.K5
C49 1996&quot;,&quot;collection-title&quot;:&quot;Studying the historical
Jesus&quot;,&quot;event-place&quot;:&quot;Grand Rapids, Mich. :
London&quot;,&quot;ISBN&quot;:&quot;978-0-8028-4187-2&quot;,&quot;number-of-pages&quot;:&quot;178&quot;,&quot;publisher&quot;:&quot;Eerdmans
; Society for Prommoting Christian
Knowledge&quot;,&quot;publisher-place&quot;:&quot;Grand Rapids, Mich. :
London&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Pure kingdom: Jesus' vision of
God&quot;,&quot;title-short&quot;:&quot;Pure
kingdom&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Chilton&quot;,&quot;given&quot;:&quot;Bruce&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1996&quot;]]}},&quot;locator&quot;:&quot;126&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Bruce
Chilton, <i>Pure Kingdom: Jesus’ Vision of God</i>, Studying the Historical
Jesus (Grand Rapids, Mich. : London: Eerdmans ; Society for Prommoting
Christian Knowledge, 1996), 126.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn27">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref27" name="_ftn27" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[27]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;0MOM6wbl&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;John
F. Walvoord, Roy B. Zuck, and Dallas Theological Seminary, eds., {\\i{}The
Bible Knowledge Commentary: An Exposition of the Scriptures} (Wheaton, Ill:
Victor Books, 1983), sec. Stanley D. Toussaint,
\\uc0\\u8220{}Acts,\\uc0\\u8221{}; c. The description of the first church
(2:41\\uc0\\u8211{}47).&quot;,&quot;plainCitation&quot;:&quot;John F. Walvoord,
Roy B. Zuck, and Dallas Theological Seminary, eds., The Bible Knowledge Commentary:
An Exposition of the Scriptures (Wheaton, Ill: Victor Books, 1983), sec.
Stanley D. Toussaint, “Acts,”; c. The description of the first church
(2:41–47).&quot;,&quot;noteIndex&quot;:27},&quot;citationItems&quot;:[{&quot;id&quot;:264,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/MTF9BKSU&quot;],&quot;itemData&quot;:{&quot;id&quot;:264,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS491.2
.B48 1983&quot;,&quot;event-place&quot;:&quot;Wheaton,
Ill&quot;,&quot;ISBN&quot;:&quot;978-0-88207-812-0&quot;,&quot;number-of-pages&quot;:&quot;2&quot;,&quot;publisher&quot;:&quot;Victor
Books&quot;,&quot;publisher-place&quot;:&quot;Wheaton,
Ill&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;The Bible knowledge commentary: an
exposition of the scriptures&quot;,&quot;title-short&quot;:&quot;The Bible
knowledge
commentary&quot;,&quot;editor&quot;:[{&quot;family&quot;:&quot;Walvoord&quot;,&quot;given&quot;:&quot;John
F.&quot;},{&quot;family&quot;:&quot;Zuck&quot;,&quot;given&quot;:&quot;Roy
B.&quot;},{&quot;family&quot;:&quot;Dallas Theological
Seminary&quot;,&quot;given&quot;:&quot;&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1983&quot;]]}},&quot;locator&quot;:&quot;Stanley
D. Toussaint, “Acts,”; c. The description of the first church
(2:41–47).&quot;,&quot;label&quot;:&quot;section&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->John
F. Walvoord, Roy B. Zuck, and Dallas Theological Seminary, eds., <i>The Bible
Knowledge Commentary: An Exposition of the Scriptures</i> (Wheaton, Ill: Victor
Books, 1983), sec. Stanley D. Toussaint, “Acts,”; c. The description of the
first church (2:41–47).<!--[if supportFields]><span style='mso-element:
field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn28">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref28" name="_ftn28" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[28]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;vuPrBXWt&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Mounce,
{\\i{}Mounce\\uc0\\u8217{}s Complete Expository Dictionary of Old &amp; New
Testament Words}, 1257.&quot;,&quot;plainCitation&quot;:&quot;Mounce, Mounce’s
Complete Expository Dictionary of Old &amp; New Testament Words,
1257.&quot;,&quot;noteIndex&quot;:28},&quot;citationItems&quot;:[{&quot;id&quot;:276,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/WGGI4T74&quot;],&quot;itemData&quot;:{&quot;id&quot;:276,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS440
.M63 2006&quot;,&quot;event-place&quot;:&quot;Grand Rapids,
Mich&quot;,&quot;ISBN&quot;:&quot;978-0-310-24878-1&quot;,&quot;language&quot;:&quot;eng
grc heb&quot;,&quot;note&quot;:&quot;OCLC:
ocm64453290&quot;,&quot;number-of-pages&quot;:&quot;1316&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Mich&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Mounce's complete expository dictionary of
Old &amp; New Testament words&quot;,&quot;editor&quot;:[{&quot;family&quot;:&quot;Mounce&quot;,&quot;given&quot;:&quot;William
D.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2006&quot;]]}},&quot;locator&quot;:&quot;1257&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Mounce,
<i>Mounce’s Complete Expository Dictionary of Old &amp; New Testament Words</i>,
1257.<!--[if supportFields]><span style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn29">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref29" name="_ftn29" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[29]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;sn7PniFR&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Mounce,
532.&quot;,&quot;plainCitation&quot;:&quot;Mounce, 532.&quot;,&quot;noteIndex&quot;:29},&quot;citationItems&quot;:[{&quot;id&quot;:276,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/WGGI4T74&quot;],&quot;itemData&quot;:{&quot;id&quot;:276,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS440
.M63 2006&quot;,&quot;event-place&quot;:&quot;Grand Rapids,
Mich&quot;,&quot;ISBN&quot;:&quot;978-0-310-24878-1&quot;,&quot;language&quot;:&quot;eng
grc heb&quot;,&quot;note&quot;:&quot;OCLC:
ocm64453290&quot;,&quot;number-of-pages&quot;:&quot;1316&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Mich&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Mounce's complete expository dictionary of
Old &amp; New Testament
words&quot;,&quot;editor&quot;:[{&quot;family&quot;:&quot;Mounce&quot;,&quot;given&quot;:&quot;William
D.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2006&quot;]]}},&quot;locator&quot;:&quot;532&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Mounce, 532.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn30">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref30" name="_ftn30" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[30]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;nw4MN6Y1&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Mounce,
532.&quot;,&quot;plainCitation&quot;:&quot;Mounce, 532.&quot;,&quot;noteIndex&quot;:30},&quot;citationItems&quot;:[{&quot;id&quot;:276,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/WGGI4T74&quot;],&quot;itemData&quot;:{&quot;id&quot;:276,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS440
.M63 2006&quot;,&quot;event-place&quot;:&quot;Grand Rapids,
Mich&quot;,&quot;ISBN&quot;:&quot;978-0-310-24878-1&quot;,&quot;language&quot;:&quot;eng
grc heb&quot;,&quot;note&quot;:&quot;OCLC:
ocm64453290&quot;,&quot;number-of-pages&quot;:&quot;1316&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Mich&quot;,&quot;source&quot;:&quot;Library of Congress ISBN&quot;,&quot;title&quot;:&quot;Mounce's
complete expository dictionary of Old &amp; New Testament
words&quot;,&quot;editor&quot;:[{&quot;family&quot;:&quot;Mounce&quot;,&quot;given&quot;:&quot;William
D.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2006&quot;]]}},&quot;locator&quot;:&quot;532&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Mounce, 532.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn31">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref31" name="_ftn31" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[31]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;wIDgmxw6&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Spangler
and Tverberg, {\\i{}Sitting at the Feet of Rabbi Jesus},
89.&quot;,&quot;plainCitation&quot;:&quot;Spangler and Tverberg, Sitting at the
Feet of Rabbi Jesus, 89.&quot;,&quot;noteIndex&quot;:31},&quot;citationItems&quot;:[{&quot;id&quot;:119,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/VFB8VX5A&quot;],&quot;itemData&quot;:{&quot;id&quot;:119,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;Sitting
at the Feet of Rabbi Jesus takes readers on a fascinating journey, helping them
discover how learning about the Jewish world of Jesus can enrich their own
faith. This newly expanded softcover edition includes a discussion guide and a
Jewish Seder liturgy&quot;,&quot;call-number&quot;:&quot;BT590.J8 S63
2018&quot;,&quot;edition&quot;:&quot;Updated
edition&quot;,&quot;event-place&quot;:&quot;Grand Rapids, Michigan&quot;,&quot;ISBN&quot;:&quot;978-0-310-33069-1&quot;,&quot;number-of-pages&quot;:&quot;301&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Michigan&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Sitting at the Feet of Rabbi Jesus: How the
Jewishness of Jesus Can Transform Your
Faith&quot;,&quot;title-short&quot;:&quot;Sitting at the feet of Rabbi
Jesus&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Spangler&quot;,&quot;given&quot;:&quot;Ann&quot;},{&quot;family&quot;:&quot;Tverberg&quot;,&quot;given&quot;:&quot;Lois&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2018&quot;]]}},&quot;locator&quot;:&quot;89&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Spangler
and Tverberg, <i>Sitting at the Feet of Rabbi Jesus</i>, 89.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn32">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///I:/My%20Drive/-TKU/Courses/Luke-Acts%20in%20Jewish%20Context%20(BIBL4310)%2008-10%202022/Research%20Paper,%20Darrell%20Wolfe.docx#_ftnref32" name="_ftn32" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[32]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;aQLPQ9MI&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Jeremy
Penner, {\\i{}Patterns of Daily Prayer in Second Temple Period Judaism},
Studies on the Texts of the Desert of Judah, v. 104 (Leiden\\uc0\\u8239{};
Boston: Brill, 2012), 1;
Introduction.&quot;,&quot;plainCitation&quot;:&quot;Jeremy Penner, Patterns of
Daily Prayer in Second Temple Period Judaism, Studies on the Texts of the
Desert of Judah, v. 104 (Leiden ; Boston: Brill, 2012), 1; Introduction.&quot;,&quot;noteIndex&quot;:32},&quot;citationItems&quot;:[{&quot;id&quot;:1047,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/DJSKJRLC&quot;],&quot;itemData&quot;:{&quot;id&quot;:1047,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BM669
.P46 2012&quot;,&quot;collection-number&quot;:&quot;v.
104&quot;,&quot;collection-title&quot;:&quot;Studies on the texts of the desert
of Judah&quot;,&quot;event-place&quot;:&quot;Leiden ;
Boston&quot;,&quot;ISBN&quot;:&quot;978-90-04-23307-2&quot;,&quot;number-of-pages&quot;:&quot;259&quot;,&quot;publisher&quot;:&quot;Brill&quot;,&quot;publisher-place&quot;:&quot;Leiden
; Boston&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Patterns of daily prayer in Second Temple
period Judaism&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Penner&quot;,&quot;given&quot;:&quot;Jeremy&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2012&quot;]]}},&quot;locator&quot;:&quot;1;
Introduction&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Jeremy
Penner, <i>Patterns of Daily Prayer in Second Temple Period Judaism</i>,
Studies on the Texts of the Desert of Judah, v. 104 (Leiden ; Boston: Brill,
2012), 1; Introduction.<!--[if supportFields]><span style='mso-element:
field-end'></span><![endif]--><o:p></o:p></p>

</div>

</div><p><br /></p><p><br /></p><p class="p13" style="margin-left: 0rem; min-height: 16px; text-indent: 1.5rem;"><b>Darrell Wolfe,&nbsp;<a href="http://www.nohiding.faith/p/blog-page.html" target="_blank">Storyteller at NoHiding.Faith</a></b></p><p class="p13" style="margin-left: 0rem; min-height: 16px; text-indent: 1.5rem;"><br style="font-family: &quot;Sitka Text&quot;; font-size: 16px;" /></p>