---
title: 'Finding my voice - somewhere in the range of Storyteller and Scholar'
date: '2023-02-13T01:20:00.0050000+00:00'
draft: false
categories:
  - 'Musings'
---

<p>&nbsp;The start of a new season…&nbsp;</p><p>After spending a decade blogging loosely about anything and everything on my personal blog (DarrellWolfe.com), and now several years doing academic writing in biblical studies, and graduating with my BA in biblical studies in December 2022; it is now time for me to find my voice for the next season.&nbsp;</p><p>Things I know…&nbsp;</p><p></p><ul style="text-align: left;"><li>I know my style is typically non-formal. However, biblical studies has taught me to be more formal than I had been, and this had the benefit of better researched, more thoughtful theological positions.</li><li>I also recognize that the stuffy formality of academic writing isn’t my authentic self for the purposes of the NoHiding.Faith brand. However, the loose blogging of disjointed thoughts about anything and everything also isn’t “on brand” for this site.&nbsp;</li><li>NoHiding exists to make biblical studies and faith-walk topics, academic content, solid thinking, and honest evaluation free from religious systems or denominational positions accessible to the every-day reader and non-academic.&nbsp;</li><li>I am primarily for the unchurched, dechurched, disenchanted, disenfranchised, and disillusioned who want to know God, Jesus, and build community with others free of the trappings of “religion”. These are my people.&nbsp;</li></ul><p></p><p>So it’s time for me to find the balance between footnotes and colloquialisms.&nbsp;</p><p>The post to come after this is one of many such attempts to find my new voice.</p><p class="p13" style="margin-left: 0rem; min-height: 16px; text-indent: 1.5rem;"><b>Darrell Wolfe,&nbsp;<a href="http://www.nohiding.faith/p/blog-page.html" target="_blank">Storyteller at NoHiding.Faith</a></b></p><p class="p13" style="margin-left: 0rem; min-height: 16px; text-indent: 1.5rem;"><br style="font-family: &quot;Sitka Text&quot;; font-size: 16px;" /></p>
