---
title: 'Reconstructing a deconstructed faith... My story.'
date: '2023-04-26T14:45:00.2210000+00:00'
draft: false
categories:
  - 'Musings'
---

<div>Reconstructing a deconstructed faith...</div><div><br /></div><div>My thoughts as I drove into work today.</div><div><br /></div>What would it look like if your worldview suddenly shattered?&nbsp;<div><br /></div><div>What if you had a core set of ideas that you believed were essential to your worldview and your faith, but you suddenly realized those ideas may me faulty?</div><div><br /></div><div>What would you do?<div><br /></div><div>I am the son of an alcoholic Pastor turned atheist crack addict psychologist.</div><div><br /></div><div>My dad was a pastor and Disciples of Christ (DOC) the nomination, AKA the Frozen chosen.</div><div><br /></div><div>I grew up in what could a cessationist tradition; which is one in which people didn't believe the miracles still happened in our day, all miracles died with the apostles.&nbsp;</div><div><br /></div><div>Meanwhile, I was having visions and spiritual experiences. I saw Jesus around 5 years old, I saw demons, and I had strange dreams and spiritual interactions throughout my young life.</div><div><br /></div><div>My dad left the church when I was around sixteen and I tried very traditions. I went to the Baptists, Evangelical Free, and Calvary Chapels (among others).</div><div><br /></div><div>In my twenties, I found the Pentecostals and the Word of Faith. Unlike every other tradition I had been exposed to, these folks believed in miracles, the supernatural, and embraced it all wholeheartedly. Therefore, I embraced their theology and lifestyle for a season.&nbsp;</div><div><br /></div><div>Eventually, I grew more frustrated as time went on because my lived experiences weren't matching the theology of my chosen tradition.&nbsp;</div><div><br /></div><div>When I eventually left this tradition in my late thirties, some of my former friends said I needed to try harder or have more faith or pray more. However, it became clear to me that the emporer had no clothes.</div><div><br /></div><div>In 2018 my wife died and any ideas that "healing and miracles belong to me as a birthright" (a common phrase in that movement) died with her.&nbsp;</div><div><br /></div><div><i>And yet</i> my experiences as a youth told me that I could not discount miracles or the supernatural entirely.</div><div><br /></div><div>After years of counseling, grief, but also for hurts, habits, and hang-ups; I eventually came to a place where I was mentally sound and emotionally healthy first time in my life. I also learned that ADHD and Autism (AuDHD) were major contributing factors to many of my worst hang-ups. I learned to process in healthy ways and develop real connections with my fellow humans.</div><div><br /></div><div>Around this same time (2018-2022), I entered Bible School and learned how to study the Bible academically and not just devotionally. I learned to lay down and lay aside theological systems, traditions, church creeds, and all the layers men have added to the text we now call "the Bible".&nbsp;</div><div><br /></div><div>I learned to see the Bible as a collection of ancient Jewish Hebrew meditation literature, divided into various sections. The TaNaKh {Torah (instruction - not 'law'); Nevi'im (prophets); Ketuvim (writings) make up the section many Christians call the "Old Testament", a poor misnomer. The Brit Chadashah (New Covenant) is a second collection of Jewish writings, sometimes called the "New Testament", also a bit of a misnomer.</div><div><br /></div><div><i>Fun Fact: For many years the majority opinion was that some New Testament authors, like Luke, were Gentiles. I currently find myself in a small but growing minority that believes all New Testament authors, including Luke, were Jewish authors.&nbsp;</i></div><div><br /></div><div>During my time in academic biblical studies, I found scholars to read and listen to on my own. Many of them are linked on my resources pages. A few names worthy of highlighting (<a href="https://drive.google.com/drive/folders/1-tLUQDr4EVcOjdAaKpNru8KqZrdBDYLH?usp=sharing" rel="nofollow" target="_blank">more here</a>):&nbsp;</div><div><ul style="text-align: left;"><li>NT (Tom) Wright</li><li>Michael Heiser</li><li>Tim Mackie</li><li>John Walton</li><li>David deSilva</li><li>John Sailhammer</li><li>David Rudolph</li><li>Paula Fredriksen</li><li>Mark Nanos</li><li>Craig Keener</li><li>Mark Kinzer</li></ul></div><div><br /></div><div>Back to the original thought, about getting a shaken worldview...</div><div><br /></div><div>One day, it became abundantly clear to me that the Bible did <i>not</i> teach anything close to a "rapture".&nbsp;</div><div><br /></div><div>Among all the doctrines I had grown to believe over my lifetime this one was core to my identity and my hope for the future.&nbsp;</div><div><br /></div><div>The rapture was the one thing we were all looking towards. It was the thing that got us through a tough day at work. "Gee," we told ourselves, "It sucked today, but someday the rapture is coming. Evil will be punished in a Great Tribulation and we're all going to escape this messed up place".&nbsp;</div><div><br /></div><div>After much study, I became 100% certain that no such doctrine of a rapture, or of any 7-year Tribulation, could be accurately found on any page or in any sentence in the entire Bible.</div><div><br /></div><div>This realization led me to a question that shook me to my core:</div><div><ul style="text-align: left;"><li><b>Am I going to be more faithful to my traditions than to understand these texts I claim to base my traditions on?&nbsp;</b></li></ul></div><div>Not too long after I answered yes to that question, this website was born.&nbsp;</div><div><br /></div><div>I purposefully and consciously chose to lay down every tradition, doctrine, theological system, creed, theory, or church label...&nbsp;</div><div><br /></div><div>I have since basically laid aside <i>everything</i> said by any Christian or Jewish Bible reader from about 180AD to the late 1900sAD.&nbsp;</div><div><br /></div><div>Everything from Apostles Creeds to "Church Fathers" are set aside so that I can ask this question:</div><div><ul style="text-align: left;"><li>What was the biblical author attempting to communicate to that author's ORIGINAL audience, in his/her own original context?</li></ul></div><div>This is not to say that later thinkers and writers did not provide some valuable thinking or processing.&nbsp;</div><div><br /></div><div>This IS to say that anything written after the biblical authors wrote is irrelevant to understanding the biblical authors. We need to be reading the texts, in their own historical, cultural, and literary contexts.&nbsp;</div><div><br /></div><div>Example: Comparing the ancient writings at Ugarit and the opening of Genesis, we can see clearly that the cultures were in an open dialogue with each other, and attempted to write poetically and allegorically about the human condition. Debates about 7 thousand year old earth are silly and ignorant, based on poor and uneducated reading skills. Yes. I said it. Ken Ham isn't worth reading or hearing. I'm still grumpy about being told I couldn't buy evolution and Jesus (I absolutely can, and have, as have most of the church outside of North America).</div><div><br /></div><div>We need to look to the best of current scholarship to help us understand what the biblical authors intended to communicate to their own original audience inside their original culture.</div><div><br /></div><div>ONLY after you properly understood what the biblical author wanted to say that biblical author's audience; can we then begin to ask what wisdom we might find in that meditation for our lives in the 21st Century.</div><div><br /></div><div>It's one thing to realize that all your traditions were probably wrong, and all your theological systems where a house of cards. That is called "Deconstructing".</div><div><br /></div><div>While many have gone through that Deconstruction journey, a much smaller subsection of us began the process of Reconstructing our faith in Yahweh, as he revealed his nature in the texts of ancient Jewish writers.&nbsp;</div><div><br /></div><div>Many in the deconstruction movement ignore these principles and simply replace one bad way or reading the Bible with a new bad ways of reading the Bible. Many of the claims of Deconstructionists use the same flawed reading skills they learned from Modern Western American Christianity read their new ideals into the texts. This isn't any more helpful than the flawed tradition that birthed them.</div><div><br /></div><div>What I (and those of my kind) want to do, is to read the texts in their own original contexts, seek to truly understand the biblical authors intended to communicate to their own original audiences, and then build an honest faith in whatever we see of "God" as he is revealed in his interactions with the people who have come before us.</div><div><br /></div><div>As I've done this, my faith has gone from rocked to rock solid. I have all the room I need to face honest textual difficulties without fear. I have no need to be "certain" of anything. I only need to keep meditating and searching.</div><div><br /></div><div>The Bible as I was taught to read it growing up, is a boring book.</div><div><br /></div><div>Having been given an academic brain and tools, I now see the biblical texts are some of the most interesting writing every produced. It just takes a new set of skills to start reading it as the literature it is, and stop reading it for "religion".&nbsp;</div><div><br /></div><div>I hope you'll join me for the ride...&nbsp;</div><div><br /></div><div>Darrell Wolfe</div><div>Shalom (שלום)</div><div><br /></div><div><br /></div><div><br /></div><div><br /></div></div>