---
title: '#DirtyPastor - Announcement'
date: '2023-01-21T03:15:00.0000000+00:00'
draft: false
categories:
  - '#DirtyPastor'
---

<p>I will be starting a new trademark under the NoHiding.Faith brand: #DirtyPastor. The Dirty Pastor threads will cover all manner of marriage, sex, gender, relationships, including clinical level details about orgasms. It’s a topic that far too few Christian couples get educated about because it’s been treated as “Taboo”. I have personally counseled with far too many men and women who have had little to no education on this topic. Their marriages and sex lives have suffered for it. It’s time to end that trend. There is no topic for which the people of God don’t have something to offer. Thus, its about to get real here.&nbsp;</p><p>Facebook:&nbsp;</p><p><a href="https://www.facebook.com/dirtypastor">https://www.facebook.com/dirtypastor</a></p><p class="p13" style="margin-left: 0rem; min-height: 16px; text-indent: 1.5rem;"><b>Darrell Wolfe,&nbsp;<a href="http://www.nohiding.faith/p/blog-page.html" target="_blank">Storyteller at NoHiding.Faith</a></b></p><p class="p13" style="margin-left: 0rem; min-height: 16px; text-indent: 1.5rem;"><br style="font-family: &quot;Sitka Text&quot;; font-size: 16px;" /></p>
