---
title: 'Question & Response 1 (a list of questions)'
date: '2023-02-13T02:23:00.0030000+00:00'
draft: false
categories:
  - 'Bible Answer'
  - 'Q&R'
---
I received an email with a list of questions from a reader I'll call "G" at DarrellWolfe.com.

I decided to answer these questions ad-hoc, in the moment, as if we were at a coffee shop talking (as she said in reference to a goal I have for my future).

I may circle back to these and write about them each in more detail, with research, citations, and footnotes. But for now, here are my gut-level responses to the questions she asked.

Note: my answers will be driven primarily by my understanding of the biblical meta-narratives and themes. Where life experiences come into play, I draw on those as well. While I am not (here in this post) making a particular exegetical argument, I believe these answers to be driven by my lifelong endeavors to understand what the biblical authors intended to communicate to us.

#### 1. What is the meaning of life?

Servant-hood driven by God-oriented compassion:

*But\... Warning: There is a ditch on any side of any extreme. *

What we are looking at here is not codependent selflessness, in which the self disappears in the service of others.

We are also not looking for a narcissistic service of others to make ourselves feel worthwhile or good.

We are looking for good healthy boundaries around our time and service (put the oxygen mask on yourself before helping others).

We are looking to protect our time, talent, and resources, in order to give them to targeted and spirit-led activities, people, and/or organizations.

We are looking to recognize, first, that God loved us while we were still failures.

We then allow him to love us as failures, and fill us with that love.

As we become so totally enraptured with his love for us, we become naturally aware of his love for others.

As this happens, his love for others becomes our love for others.

That compassion (within healthy boundaries) drives us to act driven by compassion (not a sense of obligation, religious duty, or a codependent need to fix everyone and everything).

#### 2. Is there such a thing as reincarnation?

Biblically and textually, reincarnation cannot be supported (at least as commonly understood, read the whole answer).

If by reincarnation, you mean a cycle of embodied existences in which you have lived past lives here on earth?

No.

While some claim to have experiences and memories of such experiences, I do not find any biblical textual argument to support such an idea. I think other explanations would fit the data such claims provide.

If by "reincarnation", you mean more vaguely that you can be disembodied for a time and later embodied, there is a place for that discussion.

Textually, valid arguments can be made for several positions about the afterlife state; and the after-afterlife state. Or as biblical scholar, NT Wright, says, "Life after, life after death."

I don't find any of the modern paradigms or ways of talking about those states to be helpful or textually supported - as stated by Churchianity today. "Heaven" and "Hell" as discussed and imagined in popular culture are far more medieval ideas than biblical ones. They're not "wrong" but yet they're not "right".

But that's a much longer discussion for another post.

To be absent from the body (for those in Jesus' kingdom) is to be present with Jesus. Those who are 'in Him' and have died are with Him now, they are not coming back as other humans, or cats, or dogs, etc.

They are at his side, and we are given glimpses that they are awaiting the New Creation. They may even be busy at work on Kingdom matters, or hosting an art class, or swimming with Jesus. Who knows, but we aren't told nearly as much about that (what scholars call the 'intermediate state') as modern western American evangelical Christianity would have you believe.

I think the Bible is clear that Eden was the seed, and New Creation (New Eden) is the future hope of those who are in the Messiah's Kingdom.

New Creation is an embodied existence on this planet. It is not being "destroyed" as modern prophecy teachers claim, it will, however, be "renewed".

Jesus is the template for our future hope. Just as his body after the resurrection was both similar (continuity) and different (discontinuity), so it will be for our future embodied existence here on this physical (renewed) earth.

Our bodies, and planets, get an upgrade, but our future remains embodied.

It is in *this* sense, that to be re-incarnated, or placed back in a body after being disembodied is biblical and is the very hope of Judaism and (true) Christianity alike.

We are not waiting for a Messiah who will snatch us away from this earth; rather, we are waiting for a Messiah to come join us on this earth.

Those who have died will come back for their new bodies, we who are still here when it happens will get our new bodies, we will meet him in the air as a welcome home party to usher him back to earth as King.

#### 3. If God is omnipotent and has a plan for us all, then how and why does He give us free will?

**Short**: Because he wanted to.

**Medium**: What does being all-powerful (omnipotent) have to do with giving us free will? These are unrelated concepts.

**Longer**: This is a common misconception I see frequently. One young lady just today, in a Facebook chat, made the argument that "If God is omnipotent (all powerful), and he wants everyone saved, then everyone will be saved."

This is what we call a non-sequitur (a conclusion that does not naturally follow the premise).

Premise: God is all-powerful (omnipotent) - The biblical text can support this claim.

Premise: God wants everyone saved - The biblical text can support this claim.

Non-Sequitur Conclusion:  God will save everyone and nobody won't be saved - Unclear and unlikely, a conclusion that has no basis in the two premises. And is not well-supported by textual evidence.

Some questions to consider:

- What character does this God possess?
- How has he chosen to use this all-powerful-power?

Despite the fact people try to use the Bible as a theology book to find quick answers from sentences stolen from pages forced into awkward claims, that is not the book we have.

The Bible is, ultimately a grand meta-narrative which also includes codes, legislations, poetry, stories, and other genres of writing.

We are left with a story. That story is about a God who chooses to create humans and give them choices; and then God's response to those choices.

This all-powerful God decided to partner with humans, and that involved giving them choices and honoring those choices (even unto death).

Even in the few textual cases where it might seem to an unskilled reader that God overrides choice, as with Pharaoh and Moses, a closer reading of the text shows that he never over-rode Pharaoh, he only sealed and locked Pharaoh's choices.

Since the textual evidence of the meta-narrative is overwhelmingly indicative of a God who chose to have free-will partners, then whatever else we can say this indicates or does not indicate about his character, it must indicate that this is what he wants to do with his all-powerful-power. He wants to partner with free-will beings.

Now, an examination of his character would be another matter altogether. But it seems clear he will not force us to comply with his will, even if that means some form of eternal separation from him.

1.  Whether that separation is like a room with an open door through which we will forever be allowed to free walk out and return to him (aka universal salvation in scholar speak).
2.  Whether that separation results in permanent and ongoing "punishment" for the pain we've caused others (aka hell, or eternal conscious torment) or a temporary state of punishment until all the bad is purged (aka purgatory).
3.  Whether that separation results in our forfeiting the right to exist at all, and those who reject his offer to joining the kingdom simply stop existing (aka annihilationism).
4.  Whether some other arrangement not cited here exists, because we simply aren't told as much as we would wish we were, and we don't know as much as we pretend to know (aka my current stance).

All up for debate. Good humans with strong scholarly stances and textual support take all of these positions.

What seems to me to be the fundamental fact of the biblical meta-narrative, is that regardless of the final outcome for those who reject Him, he does above all else want free-will human beings to join him in his plans to enjoy and over-see creation.

He's all-powerful (omnipotent) and that's what he wants most to do with that power: Share it with others.

#### 4. How do I get closer to God?  I've tried reading the Bible but it's difficult because of the ancient way it was written.

> \(1\) The fact we have here an acknowledgment that the Bible is ancient is a great start! Many modern readers make the error of reading the English translations as "literal" as possible and typically miss most of the point of the text in doing so.

The Bible is a text written primarily (possibly exclusively) by Jewish authors in the Ancient Near East (ANE) and in Second Temple Period Judaism. Both the Tanakh (aka Hebrew Bible, Old Testament) and the Second Writings (aka B'rit Chadashah, New Covenant, New Testament) were likely written by exclusively Jewish authors. For example, many claim that Luke was a Gentile, but strong textual evidence can be brought to bear to demonstrate he was likely also a Jewish author.

In order to read an ancient text, written thousands of years ago in three (or more) foreign languages in another world, time, culture, and place, we must do the work to understand.

Luckily, we have so many amazing tools to do so.

For beginners, I like to recommend starting with a Bible Project video about the book you are going to read. Stick with the four gospels, and use the Bible Project videos and podcasts that accompany those videos. That will help you acclimate to the story around which history has revolved. Then branch out as you grow comfortable. See also the "[How to read the Bible](https://bibleproject.com/explore/how-to-read-the-bible/)" series.

> \(2\) God (in three persons), known as (1) Yahweh (God, Father, Daddy), (2) Yeshua (Yehoshua, Joshua, Iesus, Jesus), and (3) Holy Spirit (HaRuach HaKodesh) are personal beings not abstract concepts. Together, they operate as a single operational unit called "God" in English. Get to know them, not just about them.

Maybe start with, "Jesus, I want to you to know, I'm ready to know you". Listen. Take a walk in the woods, or a drive around the lake, or pace the gym... talk to him, he's listening. Learn to listen and expect to "hear" in nontraditional ways. Like, that flower just grabs your attention, stop, look at it. Solomon the wise said "Ponder the anthill..." so you can ponder a flower. Let him speak to you in that. Sometimes you'll see words, pictures, ideas, and stories... let all that flow. Engage your heart as well as your mind.

> \(3\) Journal. Write down what you talk to God about, and what you think you hear back. Don't worry about "getting it right". No relationship was built in perfection, and this one won't be either on your side. Parents love when their kids bring them scribbles, scribble for Jesus.

> \(4\) Sing. Find songs that bypass your head and go to your heart. While I find some of Bethel's teaching questionable, I also find MOST modern western American evangelical teachings questionable. I know of zero denominations that have all the right answers. I do enjoy Bethel's worship style. They know how to find Daddy-God's heart, even if their head is a little wonky sometimes. Find something that speaks to your heart, have it playing on repeat.

> \(5\) Community. While we stand before God and God alone in judgment, we will stand before him about community. How did we love (or not love) our fellow human beings? We were build for community. In the earliest church, a whole family could be baptized because they weren't making a "personal declaration" they were making a family commitment. Baptism was intended to be a corporate acknowledgment that the individual was joining the family of God's people, and the family was accepting this person(s). When you decided to follow Jesus in the first century, you were joining a community of his family. Find your wing of that community.

It doesn't have to be in a "church" building if you prefer not to do so.

It can be if that speaks to you.

These days, my community is a rag-tag group of people I meet with irregularly. However, as my schedule is normalizing, I plan to find a more regular rhythm again.

No matter the shape or form, find people who love Jesus and go do life together. Whatever that looks like for you.

#### 5.a I've lost many loved ones in the past.

While it is a normal part of the human experience, losing someone always hurts. I am sorry for your loss, and I want you to know that the pain is a sign that you invested in them, it's a sign that love happened.

Acknowledge the loss. Allow it to hurt. Don't push that away.

Get a counselor (licensed preferably) who has certification or specialization in grief work.

#### 5.b How do you personally deal with the loss of a loved one?

Lean-In.

Whether I experience a major tragedy or a minor one, I have learned to immediately become present in the moment, and lean-in to the feelings, emotions, thoughts, and realities of that loss. The more present I am (not distracting the pain away but owning it and letting it process in, through, and out of me), the more I can integrate that emotion into the larger framework of my life.

We all live on a continuum, moments fly by. Our brains and bodies process those moments, deciding what to keep and what to discard. It's almost impossible that you remember every turn, every stop sign, every speck of trash on the side of the road, for every drive you've taken to or from work, school, church, etc. Your brain was designed to see, evaluate, and let go of unimportant moments.

Some of my childhood friends remember conversations I do not remember, their brain processed those moments as meaningful in some way, mine did not.

In a trauma event, everything comes in and nothing can be processed. It all comes in too fast. So everything is stored. But then we never (usually) go back and process the trauma, so it sits in the queue.

This leads to a feeling or sense that we are stuck, somehow. Unable to function at our highest level.

Timeline Integration Therapy (aka [Lifespan Integration© (LI)](https://www.goodtherapy.org/learn-about-therapy/types/lifespan-integration)) helped me work through my trauma events and integrate those moments into the timeline again. It essentially amounts to rehearsing the event with someone who is skilled at guided remembering, and allowing your brain, body, and emotions to process the event and place it back into the ongoing continuum of your life. It happened, but it is not happening now. The effects are present, but the event has passed.

You have reached true integration when you can be simultaneously joyful and mournful about the same person, or even events, at the same time.

Which leads me to the next question...

#### 5.c Does the pain ever go away?

No.

But it changes.

It moves, morphs, evolves. The bitterness can become bittersweet. I don't think about her as often, or as long when I do. I can look at her things without breaking down. I can see her photo on the wall and talk to her about the kids, laugh, cry, be angry she's not here to see and be, and yet grateful for the wisdom and seed she sowed into us while she was here.

It can get less intense, and more like a dull backdrop. And having that sense of intense loss, makes leaning-in to the joyful moments more intense too. It means understanding that time isn't guaranteed and to make moments count.

You're still going to be too tired to go out sometimes. You're still going to be too overwhelmed to notice a sunset sometimes.

But sometimes, you will.

#### 5.d What are some good coping mechanisms?

#1  - By a country mile - Get a counselor (licensed preferably) who has certification or specialization in grief work.

#2 - Let it be okay to be not okay. Allow yourself a sick day, or a cry day, or a watch old home videos and ugly cry day. It's okay to be not okay.

#3 - Get Connected. Don't allow yourself permanent isolation. It's okay to be not okay, and it's okay to isolate from time to time, for a day, a few days. But community and connection are the single most important part of any recovery and healthy lifestyle. Make sure these are healthy connections, as defined by Dr. Henry Cloud and Dr John Townsend:

"A safe relationship is one that does three things:

Draws us closer to God. (Matthew 22:37-38)

Draws us closer to others. (Matthew 22:39)

Helps us become the real person God created us to be. (Ephesians 2:10)

\[ Townsend, John, and Henry Cloud. "What Are Safe People? \| Cloud Townsend Resources." Accessed February 12, 2023. https://www.cloudtownsend.com/what-are-safe-people/. ; Cloud, Henry. "The Power of Healthy Connections in Your Life," December 12, 2018. https://www.boundaries.me/blog/the-power-of-healthy-connections-in-your-life.\]"

#4 - Invest in yourself. Start a hobby that you once loved but let go of, or start a brand new one. Start a new degree you kept putting off (I went back and finished by BA in my late thirties, forties). Join a paint-n-sip night. Take dancing lessons. Whatever sparks joy in your heart again.

#5 - Move your body. Take walks. Get into a gym or Thai Chi, or Yoga, or Archery class. Find a hiking group. Start swimming. Anything that moves the body.

#### 6. Why do good things happen to bad people?

The long answer is a worth a few books on it's own

(To start, check out "Where is God when it hurts? By Philip Yancey).\[ Yancey, Philip. Where Is God When It Hurts? Grand Rapids, Mich.: Zondervan, 1997.\]

Short answer, because we're alive, we exist, and we are not robots.

For whatever reason, the creator of existence likes to partner with others and share his rule and authority over creation.

He created spirit beings (elohim, sometimes called angels) to rule with him in the spirit realm, and he created human beings (literally dirt creatures in Hebrew / Adam-human/Adamah-dirt) to rule with him over creation.

Both realms rebelled and both realms require healing and restoration.

In order to partner with entities that are not him, he gave them his capacity for self directed governance.

Which means we have true free-will (despite what some clinging to medieval theologians try to teach).

We have the capacity to create unimaginable joy and unthinkable pain.

We often use this power to dominate and control each other (hence the repeating themes in the Bible about corrupt empires and kings, Egypt, Babylon, Assyria, Persia, eventually Rome, and even Jerusalem itself under many of its kings).

Jesus came to show us the upside down kingdom. A kingdom where its leaders live to serve, not be served. And where dying gives us life. And where the key to victory, is to die (sometimes metaphorically, and sometimes literally).

Injustice is a common theme in the biblical stories, and God works through humans to correct other humans.

Natural disasters could be linked to this trend; or, they could be seen as part of the seed but not yet full-grown nature of creation.

The whole of creation groans to see New Creation (a renewed existence for planet earth and its inhabitants).

Until then, we can only ask God how he will partner with us to create pockets of Eden in our world, and bring healing to a hurting world, light to a dark world, and blessing despite the curse.

There really is no good answer to "why".

It rains on the just and unjust. The answer becomes, "what" can we do despite this reality? We can sow light into the darkness. We can find ways to create Tov (good) in places of Ra (bad).

God never promises an answer to "why", not even to suffering Job. But he does promise that he'll walk through the darkness with us (Psalm 23). We may not even find rest on this side, but the promise of Eden stands in front of us, at the coming global Resurrection.

#### 7. Do animals have souls?

This requires a MUCH longer explanation. For a starter and primer to this topic, see the BibleProject video and podcast on this word "Soul".

\[ Mackie, Tim, and Jon Collins. "BibleProjectTM Videos and Podcasts." Word Study Discussions. Accessed October 2, 2022.

Video: <https://bibleproject.com/explore/video/nephesh-soul/>

Podcast: <https://bibleproject.com/podcast/you-are-soul/.>

The shorter answer, maybe.

But do you even have one of these "souls"?

I don't think the biblical writers thought in exactly the same terms that moderns use for such things.

Genesis 2:7 says that the human became a living "creature". This word translated as "creature" in the LEB is Nephesh, which is often translated as "soul". It literally means throat (the thing you breath through and eat through). In modern terms, if I say there are 20-head of cattle, I don't mean there are twenty bodiless cow heads, I mean there are twenty cows. So in Hebrew, a person is a throat. It is a way of identifying the whole by use of the part.

All animate earth beings (cows, deer, and humans) are Nephesh (beings of dirt animated by God's breath). It does not carry the connotation of "soul" that we use to refer to a disembodied part of the human.

So yes, all animals and humans are Nephesh (souls), if by that we mean bodies animated by God's breath.

 There is actually much less distinction between animals and humans in the biblical narratives than modern theologians are comfortable admitting (probably because it would put a crimp in their pet theological stances).

Humans are put over the earth and its creatures as Kings and Queens. That is what it means to "image God" or "be made in his image". It is a job title. We are to tend and steward and be good caretakers of creation (and we screwed that up royally).

So, when New Creation finally arrives, is it possible my long-dead dog from when I was a child will be there waiting for me. I don't think we can make a textual argument for or against it, firmly. But I don't see anything in the biblical narrative that would prevent that from being true. God is very pro-creation and I could absolutely see that possibility.

#### 8.  Am I being punished for all the bad things I've done earlier in life?

No.

From a biblical perspective, this is not a possible truth.

The biblical narrative precludes this as a possibility. Despite any impression, or even outright memories you may think you have about a former life, the biblical authors do not leave room for this possibility.

We live one time. After that, we stand before God for what we did in this life (good and bad), not as some arbitrary judgment of arbitrary rules (as many in modern western Christianity would have you believe).

Rather, we stand before him to account for good and bad seed we've sown, the way we treated our fellow humans, and whether we responded to his Son's invitation to join his Kingdom in New Creation.

It will always be about that invitation, and not our 'earning' of anything.

You can suffer the natural consequences of prior generations (my grandfather was an alcoholic, his abuse led to my father's issues, which led to mine). And we can stop the chain and start a new chain with us (my kids benefited from my getting help and counseling).

But you did not live a life before this one, nor are you suffering for such a life.

#### 9. Do you think the end is near?

Meh. Not worried about it. Maybe, maybe not.

I see no good reading of the Bible in its own original contexts that allows for any kind of "end times schedule of events". The ideas about a rapture, 7-year tribulation, and maybe even a battle with the Antichrist (I'm still weighing that one out myself) are far more pop-culture theology than good Bible reading. "Left Behind" made great novels but terrible Bible reading.

Every generation has had its battle with evil human-made empires resisting the upside-down kingdom.

Every generation has had the opportunity to see persecution for following the upside-down kingdom.

Every generation has had the opportunity to lay down its life (figuratively or literally) for Jesus.

Two things are primarily in view for the biblical authors:

(1) The invitation to join God's kingdom reaches every human on earth.

(2) Israel, nationally and publicly, acknowledges Jesus as Messiah.

Until those two things happen, no. We're not there yet.

#### 10. If so, what can I do to prepare?

The same thing we've done since day one of the upside-down kingdom, while Jesus still walked the earth, and shortly after he left his first followers with the Holy Spirit.

Gather in communities of people who are in the kingdom.

Study the texts he left us through his chosen (ancient) authors.

Pray, praise, sing, and eat together frequently.

Serve, serve, serve, serve...

Let Rome (whatever Rome/Babylon looks like in our day) be so taken by our tendency to be of service to our local communities that they even when they don't like us, they find us useful.

And if persecution comes, so be it. Sing while locked up in jail. Celebrate when it ends and we're reunited with our community.

And if death comes, look forward to being with Him and coming back with him someday.

#### 11. Are you a believer of fate, destiny, or synchronicity?

Not as they are usually defined.

God has an over-arching plan for this earth-humanity experience. It starts as a seed in Eden, and it ends with New Eden, New Creation. Our ultimate hope is for a reembodied experience on this renewed Earth. We will be snow skiing and cliff diving and painting, and doing plays and storytelling for many millions of year to come when New Creation arrives. It will be similar and different. Better. Painless. Tearless. But embodied.

He also knows us intimately, every hair on our heads. He cares deeply about us.

He also invites us into the upside-down kingdom, to live like Jesus, which means self-sacrifice. The miracles and healings come at the cost of going without and being misunderstood.

Was I always going to marry Flavia and become a widower? I don't know.

I think he gives us seed (time, talents, treasures) and opportunities to sow that seed. What we choose to do with that seed is up to us. As we sow, if we do it well, it reaps rewards and compounds.

If we waste the seed today, tomorrow he'll give us a new batch of seed and new opportunities.

I don't think we have a "destiny" to fulfill, I think we have opportunities to be useful, be of service, and to sow our time, talent, and treasures (motivated by love, not out of obligation).

He gives us new chances until finally, we reach a day where we have no more chances.

For reasons I will never understand on this side of New Creation, Flavia A. Miller Wolfe ran out of those opportunities on June 25, 2018. Yet, I have had more since. Even though she was far more deserving than I.

I blew many of them.

I chose wrongly many times.

But I've made more good choices than bad, cumulatively since she left. Especially the last few years. By his grace, I did better with my second chance life.

The thrust or direction of my life has produced more good fruit, in part, because the pain of her loss drove me to make my survival meaningful.

Originally, it was a codependent need to live up to her legacy. After two great counselors and a lot of support, and a lot of errors, I eventually healed from that motivation.

Now I live because my God has graced me with gifts and talents, and I love him, and I want to make use of them. I do things like respond to this email because his love for me causes me to share that love with others.

Was I always supposed to start this particular website; or, was it the result of the choices (good and bad) made by myself and others, and the fruit of many countless seeds sown?

I cannot ignore that there have been patterns, trends, and a general thrust toward a similar direction in every season of my life. But I see that as a function of the gifts and talents and opportunities. Not as a specific destiny.

Selah (prayerfully ponder and meditate on these things)

**Darrell Wolfe, [Storyteller at NoHiding.Faith](http://www.nohiding.faith/p/blog-page.html)**
