---
title: 'Bible Study: Outlines…'
date: '2023-04-02T19:03:00.0010000+00:00'
draft: false
---

<p>​</p><p><br></p><p>Write article about&nbsp;<span style="-webkit-text-size-adjust: 100%;">exegesis vs&nbsp;eisegesis, link in all studies</span></p><p><span style="-webkit-text-size-adjust: 100%;"><br></span></p><p>Overview</p><p>Historical contexts of Text&nbsp;</p><p>Authorship, date, occasion&nbsp;</p><p>Outline the entire book</p><p>Into to known exegetical issues, common mistakes, common takes, common schools of thought</p><p><br></p><p>First pericope</p><p>.</p><p>. Frequent return to outline&nbsp;</p><p>. Frequent side trails into Inter and Intra textual references</p><p>. Frequent side trails into historical contexts</p><p>. Frequent side trails into textual or scholarly issues</p><p>.</p><p>Final pericope&nbsp;</p><p><br></p><p>Review summary of pericopes in light of outline</p><p>Key themes of this text</p><p>Key whole-Bible themes</p><p><br></p><p><br></p><p>ONLY after these steps …. What principles can we derive from the text? How might those principles apply today?</p><p><br></p><p>Reminder: there’sa HUGE difference between “the author was saying”…. Vs “I get out of that for me today”.&nbsp;</p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p>&nbsp;</p>
