---
title: 'Class Assignment: What is the gospel, according to Luke-Acts?'
date: '2024-06-09T12:48:00.0050000+00:00'
draft: false
categories:
  - 'Gospel'
---
Assignment: Without referencing any other New Testament writer, but you can reference any Hebrew Bible writer that the gospel author himself references, what is the gospel according to\...

Gospel Reading: Luke

Darrell Wolfe

Literature, The King's University

Life of Jesus (BIBL-2302)

Professor Jason Moraff

November 8, 2020

# Questions

1.       11:33-36 -- I could conjecture, but I'm still vague on what he means about the light of the eye. When we see but not seeing, but, what's the actual advice or command here? How do I get my eye lit?

2.       I found myself making more observations than asking questions today.

# Observations

- More than any other Gospel, the term "Holy Spirit" comes up frequently. Even before Jesus is born, the Holy Spirit is an active member of the story.

- 4:6 -- Jesus never denies that Satan has the authority to give, only that it was not how he would wrest it from him. Interesting to note when we consider "why bad things happen" on earth.

- Ch. 6 -- I found myself uncomfortable, in light of election season, comparing my attitudes to those Jesus commands. Loving my enemies was not the forethought in my mind, as I prepared mentally for the USA Civil War II.

- Ch. 9 -- How often have I heard one side (Republicans & Democrats) so angry at the other that they wanted to cause physical harm to them or their possessions? Yet, Jesus tells us he is not here to burn the enemy camp down, but to save them. His enemies are not enemies at all, but captives that need Freedom.

- 14:26 -- Makes so much more sense in light of our readings about first century disciples preferring their Rabbi over their own father. This is a cultural reference and amplified (like his reference to not just adultery but even lust is sin).

- 16:11 -- Never noticed this before, if you are not disciplined with your budget and earthly money/income, you will not be trusted with more. Those wanting to serve God must start by getting their own house in order.

- 23:25 -- They were expecting a king to free them from Roman rule. They did not just ask for a murder in place of Jesus (picture of forgiveness of sins), they asked for someone (a rebellion leader) who was more like the image they had of their Messiah. They asked for a false Messiah in place of the real one, one that would mold to their own ideas about what Messiah should be.

# The Gospel According to Luke

Luke presents to us a very Jewish Jesus, rooted in the history of his people and in prophecy. We are well into the story before the Jesus who ministered for three and a half years is introduced onto the scene. After his victory in temptation Jesus is immediately rejected by his own, a paradox. Throughout his ministry, he preaches the Kingdom of God and heals the sick. He then sends his disciples (not just the 12, but the 70 as well) to do the same. These miracles establish his authority. Luke takes his time, builds the character of Jesus through interactions with various types of people. He also shows us why the leaders of the religious sects of the day hated him so much as to kill him. We see him sit at the table in a Pharisees own house, then condemn the entire group for their behavior. Meanwhile, we see Jesus take pity on the least of those in his midst. He makes a point to observe a widow and comment on her giving, show us that we must serve those we come across on the road who have been abused by others (Good Samaritan). Even at the end, as he is being arrested, we see him healing the ear of his captor. Luke ends with the punchline, as though nothing was understood by the disciples until this very last moment. Jesus had to die and rise again, so that the message of repentance and remission of sins could be taken to the whole world. Luke's Good News is that the Kingdom of God, established and confirmed through signs, results in repentance and remission of sins through Jesus' death and resurrection.

Shalom שָׁלוֹם: Live Long and Prosper!

Darrell Wolfe

Storyteller \| Writer \| Thinker \| Consultant \| Freelancer \| Bible Nerd
