---
title: 'Class Assignment: What is the gospel, according to Mark?'
date: '2024-06-09T12:47:00.0040000+00:00'
draft: false
categories:
  - 'Gospel'
---

Assignment: Without referencing any other New Testament writer, but you can reference any Hebrew Bible writer that the gospel author himself references, what is the gospel according to...<div><br /></div><div>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span class="MsoBookTitle"><span style="font-size: 16.0pt; line-height: 200%;">Gospel Reading:
Mark</span></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Darrell
Wolfe<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Literature,
The King’s University<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Life
of Jesus (BIBL-2302)<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Professor
Jason Moraff<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">November
1, 2020</span></p>

<h1>Questions<o:p></o:p></h1>

<p class="MsoListParagraphCxSpFirst" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->1.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>On its own, the comparison to Jesus as Bridegroom and his
men with him not fasting makes sense. I fail to see how the new cloth patching
old cloth or new wine and wineskins have any relevance to the question of why
his men do not fast. This might be a point where cultural relevance would be at
play?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->2.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Paraphrase: “Jesus climbed into the boat and the wind
stopped. They were afraid. They still did not understand the significance of
the loaves.” How were his disciples expected to connect his ability to multiply
food with his ability to stop wind? Should they have observed these as power
over the natural order of things?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->3.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>9:10 – Jesus’s three closest men are asking among themselves
what “rising from the dead” means. Considering the rest of the story, it means
exactly what it means. How often do we make things too difficult or aloof, when
he is really telling us quite plainly?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->4.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>In most instances, Jesus heals a nameless blind person. But
here in 10:46 the person is named. It feels odd or out of place compared to
other stories of healing. What is naming this person accomplishing? What could
his name reveal about him or the story? Is he important in some way in another
place? This just stands out to me as a “things that make you go, hmm” sort of
way. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->5.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Ch. 13 – I am forced to admit that I do not see a “rapture”
described in this set of events. I wonder how much we have a proper
understanding of what is coming next and what Jesus actually said his second
coming would look like (vs what Left Behind said it would be)?<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->6.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>My margin notes say that anything after 16:8 may or may not
be authentic. This says more about the scholar than the text to me. Maybe I am just
missing something about the history of it. Why do scholars find incomplete
copies and then use them to doubt the authenticity of the original?<o:p></o:p></p>

<h1>Observations<o:p></o:p></h1>

<p class="MsoListParagraphCxSpFirst" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>Throughout Mark, Jesus tells people not to tell what he did
for them; and demons not to reveal who he was. This was strange at first until
I reached the end. Jesus was, ultimately, crucified for claiming to be the Son
of God. So, he kept a lid on this until the time was right to admit it to the
leaders at the end. He kept them second-guessing until then.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>4:24-25 – In the NKJV, this did not completely make sense.
But the NLT Messiah version made more sense. “The closer you listen, the more
understanding you will be given”. I think this is what classes like this one
teach us to do. Listen closer. Listen more attentively. Ask questions. Use the
background and history to see deeper into the words. Preparing our hearts to be
good soil. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>Jesus is on the way to heal a man’s daughter. They are
stopped by a woman who had faith to be healed. He calls her daughter. Between
the lines, Jairus is still standing there when he said it. Jesus is building
Jairus’ faith by comparing the daughters of healing. The end of this section
speaks about Jesus being unable to do any miracles because of unbelief. These
stories juxtapose each other to show that we have a role to play in God’s
miracles in our lives. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>9:24 – “Lord, I believe; help my unbelief.” This could be
one of the most powerful prayers I pray. Despite decades walking with God and
multiple experiences seeing Him show up for me, I continue to doubt he will do
it again the next time. I have grown by leaps and bounds, but the tendency to
doubt is strong and one I fight constantly. I love how Jesus met the father at
his level. He took that seed of belief and used it. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>Ch. 11 – Jesus shows up, observes, leaves. He comes back the
next day and acts. Also, he speaks death to a tree. The next day, his disciples
see the effects of that curse. I enjoyed seeing these weave into each other in
the same story. Day 1, Day 2. I wonder how often we are rushed into action
without taking time to pray? I wonder how often we pray and do not see anything
and give up before the miracle comes? <o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>Roman officers were hardened to crucifixions. It must have
been an impressive death scene to make the soldier believe that Jesus was the
Son of God.<o:p></o:p></p>

<h1 style="line-height: 200%;">The Gospel According to Mark<o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; According
to Mark, this is the story of Jesus the Messiah, Kingly Son of David, and Son
of God, who came preaching the Good News of the Kingdom of God. In Mark’s
story, we see an unlikely king. This man is no military leader or
revolutionary. He comes as a Rabbi teaching people to see and think
differently, and as a result, live differently. His teaching forces the
religious leaders, people, and even his own disciples to think deeper and see
things from a new (heavenly) perspective. Jesus comes racing onto the scene
with a new style of message and new power to back it up. He heals the sick,
casts out demons, and raises the dead. Most shockingly to a first century
audience, he also comes forgiving sins. This kingdom, however, is no ordinary
kingdom. It is a kingdom that is from above. He tells us that it starts small
like a mustard seed and grows until it becomes the largest plant in the garden;
possibly hinting at the non-geo-political nature of it. It is as if to say,
this kingdom will be a kingdom of minds and hearts, worldview altering, but not
one of palaces and policies. He even stops his disciples from fighting for him,
which is what most disciples would have been expected to do for the Messiah
they were expecting. As if to drive the point of Jesus’s heavenly status home,
he places the transfiguration and God the Father announcing “this is my Son” at
the midpoint (9:7). It becomes the truth upon which the entire story hinges.
Then again, at the end, a Roman solider repeats “truly this man was the Son of
God” (15:39). This kingdom is lead by a King who conquered death and sits at
God’s right hand. The book ends by saying that Jesus tells his disciples to go
into the world preaching the good news of this kingdom, and he backs it up with
signs following. Even though the story is about the Son of God who introduces a
new kind of kingdom, this Good News seems far more interested in how we think
and live here on Earth than it does in getting us “saved to get to heaven”.&nbsp;<o:p></o:p></p></div><div><br /></div><div><br /></div><div><br /></div><div><br /><br /><br /><br /><span style="font-family: &quot;tempus sans itc&quot;;">Shalom&nbsp;<span face="sans-serif" style="background-color: white; color: #202122; font-size: 14px;">שָׁלוֹם</span>: Live Long and Prosper!</span><br /><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe</span></div>Storyteller | Writer | Thinker | Consultant | Freelancer | Bible Nerd</div>