---
title: 'I saw Jesus once…'
date: '2024-03-24T02:14:00.0060000+00:00'
draft: false
categories:
  - 'NoHiding Manifesto'
---

<h4 style="text-align: left;">&nbsp; I saw Jesus once…&nbsp;</h4><p>It was a warm summer day in southern California, somewhere near Arcadia or Bellflower I would guess. I have the impression it was near the Santa Anita race tracks, but that may not be correct. For some reason, that fact is just floating in my head near this story.&nbsp;</p><p>I recall that it was a large public pool. I can see other kids laughing and playing, I am entertaining myself in the water, admiring the sun dancing on the ripples. I was young. I’m not quite sure how young, three, five? I feel like the water wasn’t very high, maybe one of those 1-foot pools for young kids. I know I was alone in my immediate area, I usually preferred to play alone. I didn’t know until my 40s that it was part of my autism.</p><p>There was a sudden feeling that I was no longer alone, and I glanced around and then up.&nbsp;</p><p>Jesus was there, in the sky, on a throne, surrounded by beings in white.&nbsp;</p><p>Then the beings were gone, and it was just Jesus and me. He was seated the whole time in the clouds, but somehow also face to face with me. It was like me being in the water miles from him, and me being face to face, both at the same time.&nbsp;</p><p>Jesus smiled, I smiled. He never opened his mouth, but he smiled. It felt like he spoke words that don’t come in English to my soul-heart-mind, words that have taken on different tones over the years.&nbsp;</p><p>There is a fiction book called Wheel of Time, and in it a character named Perrin Aybara speaks with wolves. The authors paint a picture that Wolves speak in images and not words, or feelings. That’s the best description of what it was like with Jesus as a small child.&nbsp;</p><p>The closest I can come in words is: I AM</p><p>I am here. I am real. I am with you. I won’t leave you. It’s gonna be okay… Something in that general feeling.</p><p>It could have been an hour or ten minutes, I’m not sure.&nbsp;</p><p>Kids take these things for granted, we haven’t been trained to overthink it.&nbsp;</p><p>After a while, he nodded and I went back to playing. When I looked back up, he was gone.&nbsp;</p><p>Some people tell me it was just the imagination of a child. Who knows, maybe. We’ve seen the mind do strange things as we study it in Neuroscience. What I can tell you, is that the memory of that moment is never far. I don’t think about it daily, but I have thought about it at least a few times a year, for close to 40 years now.&nbsp;</p><p>In the years after that event, I’ve had many reasons to doubt the existence of “God” or “Jesus”. Yet, through disappointments, failures, shame, joy, wins, losses, family addiction issues, deaths, and the eventual “Deconstruction” from the ideas I grew up with in Churchianity, and Reconstruction thanks to Bible School, and great scholarship like Drs Michael Heiser, John Walton, Tim Mackie, NT Wright, Ben Witherington III, and so many others… Giving up “The Rapture” for a biblical vision of the returning King… becoming a Widower and raising two boys alone, with decades of church wounds… Through all of it, a small child, in a pool, with a Jesus far and near, ever present, never left me.&nbsp;</p><p>I AM.</p><p>I am with you. I am real. Hold on. Keep walking, I know you can’t see me right now, but I am right here…………..&nbsp;</p><p>Was it a real vision? It was to me, it still is to me. It sticks with me. If I close my eyes I am right there in that moment all over again.&nbsp;</p><p>I didn't do anything to earn it, and I don't think it's a theological flex, but it certainly grounded me on one key point of Theology.&nbsp;</p><p>He is real, he is risen.</p><p>I used to believe in a “young earth” and now I think that Genesis 1-11 were always intended to only be a metaphor for the human condition. I’m not sure there ever was a literal historical Adam &amp; Eve, if there were, they were probably taken from the early hominids.&nbsp;</p><p>Does giving up the Rapture and Young Earth make me toss out everything else? That depends on how you look at it…&nbsp;</p><p>Did I toss out modern Western Churchianity, with its megachurches and MAGA Christians? Absolutely.&nbsp;</p><p>Did I toss out Augustine, Luther, and Calvin? You betcha, mostly at least.&nbsp;</p><p>Did I toss out Jesus? No. Jesus lived as a Jewish Rabbi, gathered a bunch of rag-tag disciples, caused some of the religious establishment concern while gathering some to himself… he started a Jewish Messianic movement… he died on a cross, rose three days later, was seen by many witnesses, and his followers of The Way continued building Jesus communities all over Judea, Samaria, and to the known world at the time.&nbsp;</p><p>Eventually, that movement turned Jewish + Gentile.</p><p>Eventually, the Gentile factions took over and got a lot of it twisted, each generation having to struggle with it over and over, starting a fresh struggle. But that’s now new. Israel’s name was changed to Jacob because he “wrestled with God”. One Rabbi said that the nature of the people of Israel has been to wrestle with God ever since. I believe that is true of his Gentile followers as well.&nbsp;</p><p>Did Augustine get more wrong than right? Probably. Was Luther a brutal antisemite who also had some things about God right while others he got wrong? Yes. Did Calvin get almost everything wrong while wrestling with God in a medieval Catholic context? Yes. Does that make him evil? No, we each wrestle. Am I still “wrong” about probably half or more of my positions? Sure, why not.&nbsp;</p><p>I no longer care about getting the right answers on a theology test, the longer I study the Rabbis the more I realize that my Orthopraxy (how I live The Way) matters more than my Orthodoxy (the doctrines I hold).</p><p>I know that Jesus is real, he was in the beginning with God and is God. I am comfortable with the ambiguity of the biblical author's language and feel no need to get technical with doctrines about those words from years after-the-fact.&nbsp;</p><p>He is real.&nbsp;</p><p>He is risen.&nbsp;</p><p>He is with me.</p><p>He has not abandoned me.&nbsp;</p><p>He is coming back, physically, to reign on this planet.</p><p>I am living The Way of Jesus, in community, and working pockets of New Creation in there here and now while I wait for the then and there.</p><p>He IS.&nbsp;</p><p>That’s what it left me with, that’s what it still leaves me with. And that will matter as I write more about my story.</p><p>Shalom, Darrell. שלום</p><p><br /></p><p><br /></p><p class="p13" style="margin-left: 0rem; min-height: 16px; text-indent: 1.5rem;"><b>Darrell Wolfe,&nbsp;<a href="http://www.nohiding.faith/p/blog-page.html" target="_blank">Storyteller at NoHiding.Faith</a></b></p><p class="p13" style="margin-left: 0rem; min-height: 16px; text-indent: 1.5rem;"><br style="font-family: &quot;Sitka Text&quot;; font-size: 16px;" /></p>
