---
title: 'AUTOBIOGRAPHY/UNDERSTANDING OF CALLING, Life of the mind and the gift of hardship'
date: '2024-11-03T09:24:00.0040000+00:00'
draft: false
categories:
  - 'Class Assignment'
---

<i>Sharing on my website too...&nbsp;</i><div><br /></div><div><p align="center" class="MsoNormal" style="text-align: center;"><b>&nbsp;</b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>&nbsp;</b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="letter-spacing: -.5pt; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast; mso-font-kerning: 14.0pt;">AUTOBIOGRAPHY/UNDERSTANDING OF
CALLING</span><o:p></o:p></p>

<p align="center" class="MsoNormal" style="text-align: center;"><o:p>&nbsp;</o:p></p>

<p class="MsoSubtitle" style="text-align: center;">Life of the mind and the gift of hardship<o:p></o:p></p>

<p align="center" class="MsoNormal" style="text-align: center;"><o:p>&nbsp;</o:p></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>by</b><o:p></o:p></p>

<p align="center" class="MsoNormal" style="text-align: center;"><o:p>&nbsp;</o:p></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>Darrell Wolfe</b><o:p></o:p></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>&nbsp;</b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>&nbsp;</b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>&nbsp;</b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>&nbsp;</b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>Submitted in
partial fulfillment of the requirements <o:p></o:p></b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>for the course
SF509: Formation for Theological Studies</b><o:p></o:p></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>&nbsp;</b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>Professor Kristin
Huffman</b><o:p></o:p></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>&nbsp;</b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><o:p>&nbsp;</o:p></p>

<w:sdt calendar="t" calendartype="Gregorian" date="2024-11-03T00:00:00Z" dateformat="dddd, MMMM d, yyyy" docpart="621FAB913F7D4FEBBC1A2E84E432FFB2" id="-897983336" lang="EN-US" maptodatetime="t">
 <p align="center" class="MsoNormal" style="text-align: center;"><b>Sunday, November
 3, 2024</b><o:p></o:p><b><w:sdtpr></w:sdtpr></b></p>
</w:sdt><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;"><br clear="all" style="mso-special-character: line-break; page-break-before: always;" />
</span>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<h1>INTRODUCTION<o:p></o:p></h1>

<p class="MsoNormal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The
following is a reflection of my journey, my unique contexts, and my strengths
and gifts – all of which play a role in my story and my sense of calling.<o:p></o:p></p>

<h1>REFLECTION OF JOURNEY<o:p></o:p></h1>

<p class="MsoNormal" style="text-indent: .5in;">As my personal timeline was laid
out before me, a realization dawned that was both subtle and profound. My
formative years were hard, painful, and confusing. My young adult years were
harder, more painful, and more confusing. I am intimately aware of the <i>many</i>
painful moments and how they shaped me; I use those stories often when working
with others through their painful moments. I am reminded of a ubiquitous social
media meme, “Trauma didn’t make me stronger, it gave me dark humor and
unhealthy coping mechanisms”.<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Formation_for_Theological_Studies_SF509/AutobiographyUnderstanding%20of%20Calling_Wolfe_Darrell_.docx#_ftn1" name="_ftnref1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[1]</span></span><!--[endif]--></span></a> I
eventually healed from many of those and I’m still unlearning others; however,
the trauma gave me a sense of realism and <i>non-fake-ness</i> that others
appreciate. Several folks have commented on how they don’t have to put on mask
when working with me (like watching their language) – which is all too common
in US-American Churchianity.<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">Yet, I was surprised by how many
non-painful or not-as-painful moments dotted my personal timeline in those
early years. Even in those sad and hard years, I can look backward and see
Yahweh guiding and providing –through access to mentors, successful businesspeople,
and quirky or unusual men and women of God. At one point, I was given direct
access to the executive leadership at a major bank, and recently he’s given me
an inside view of an elected official’s inner workings. I was given access to leaders
(both great and awful leaders) inside and outside of the Church. Throughout the
journey, Yahweh has shown me his nature, mind, heart, and ways of operation,
bringing me closer to him and to his human imagers. On many occasions in many
jobs with many leaders, I’ve sat in a one-on-one meeting with my manager that
was intended to be about my job performance but ended up taking a pastoral or
counselor role for that manager as they went through hard things. HaRuach
HaKodesh (The Holy Spirit) moved on these leaders such that they often
spontaneously shared their pain – often surprising themselves to be doing so.
I’ve come to recognize it when Ruach is leading in these moments.<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">All these preparation seasons were
followed by a season of profound personal death (both literal for my late-wife,
Flavia, and metaphorical for me). In many ways, my darkest nights of the soul
(ages 36-40) became the furnace in which I was burned to ashes and reborn.<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Formation_for_Theological_Studies_SF509/AutobiographyUnderstanding%20of%20Calling_Wolfe_Darrell_.docx#_ftn2" name="_ftnref2" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[2]</span></span><!--[endif]--></span></a> Like
the mythological Phoenix, or Yeshua himself, I rose from the ashes with a new
lease on life. Suddenly, while some new hard and painful moments still dotted
the remaining timeline, most of them took on a different tenor; the nature of
the hard moments was different somehow. The timeline also exploded with
positives, or at least neutrals after 2019. <o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">Greene-McCreight notes, “I think
that people who are engaged in psychotherapy, if they work hard with the right
therapist, cannot help but come out the other end of depression changed.”<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Formation_for_Theological_Studies_SF509/AutobiographyUnderstanding%20of%20Calling_Wolfe_Darrell_.docx#_ftn3" name="_ftnref3" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[3]</span></span><!--[endif]--></span></a> This
was my experience. I count myself extremely lucky to have worked with two
world-class counselors since 2016; both of whom helped me become a “fully
integrated” human imager. While I remain connected to my second counselor for
regular check-ins – like getting my emotional oil changed, it was the end of 2019
that my breakthrough hit in the oddest way. <o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">After years of dealing with some
really big things in the counselor’s office, I had this one nagging memory that
didn’t feel like a ‘big deal’. Jana (the counselor) said, “It’s usually the
things that don’t seem like a big deal that we should be working on.” So, we
set out to do Lifespan Integration Therapy techniques on this memory. In what
is otherwise an innocuous memory of a fifth grader who skipped school, I had
internalized that I should run far and fast from hard things. We thanked
10-year Darrell for protecting me but assured him that I’m an adult now and I
can take it from here. While it felt healing to have that moment, it did not
feel “profound”. The moment passed without fanfare, or fireworks, or sudden
blasts of “Aha!”. Yet, I woke up a week later realizing that over 20-years of
depression was gone. It was simply – Gone! When I’m tempted to run away from
hard things today, I can look at that moment, turn back to the hard thing, and stand.<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">Now I’ve followed Yahweh into
seminary – a place I swore since childhood I would never be. Today, he is
teaching me how to lead-well within my context. For most of my life, I took
seriously the warning, “not many should become teachers” (James 3:1).<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Formation_for_Theological_Studies_SF509/AutobiographyUnderstanding%20of%20Calling_Wolfe_Darrell_.docx#_ftn4" name="_ftnref4" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[4]</span></span><!--[endif]--></span></a> I
knew I was emotionally weak and vulnerable, prone to mood swings, and unable to
sustain momentum. I would volunteer for a season, feel a pressure of some kind
that I could never quite explain, then to the bewilderment of those around me I
would jump ship. I “needed milk because I couldn’t handle meat” (Hebrews 5:12),
and that was true for many years.<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">The dark nights of my soul forged
me into someone who can handle tough things. Getting my Autism and ADHD (AuDHD)
diagnosis helped me understand things like sensory overload, which allowed me
to carve out space in my life and schedule to work with my uniqueness. These
have resulted in my capacity to lead, teach, and guide in new ways. Getting my bachelor’s
in general Christian studies allowed me to learn a healthier relationship with
Yahweh and the Bible. I found shalom (<span dir="RTL" lang="HE">שָׁלוֹם</span><span dir="LTR"></span><span dir="LTR"></span><span dir="LTR"></span><span dir="LTR"></span>)
in my relationship with Yahweh, and with my wrestling with some Bible questions.<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">In many ways, this current season
is marked by “you ought to be teachers by this time” (Hebrews 5:12), and so I
am tentatively taking steps into that space. Due to experiences from my own
past and formative years, I avoided any roles that felt like a church leader. These
days, I am beginning to accept that role as he provides me opportunities to
step into it. Most of my work today is through one-on-one work with others like
me – those who have questions. We shall see what the future holds. As I walk
into this next season, I am also aware of how my contexts have shaped who I am
and what I bring into those one-on-one fireside chats.<o:p></o:p></p>

<h1>PERSONAL CONTEXT(S)<o:p></o:p></h1>

<p class="MsoNormal" style="text-indent: .5in;">I was raised a white middle-class male
by two white educated parents. My dad was a Doctor of Ministry, one uncle was a
PhD in Psychology, another uncle was a high school dropout but built a million-dollar
painting business. My mom was a union nurse who went back to get more education
and became a nursing educator for the CalState University system.<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">All of this led me to expect many
things from life, which is why I was frustrated when I spent six years in city
college and couldn’t seem to find a major or finish a degree (1998-2004). I was
even more frustrated when I became homeless with a wife and 9-month-old (2006).
I grew bitter as my life continued into poverty for most of my adult years.
Only in my forties did I finally “break even” financially. Why could my family
seem to succeed but I couldn’t? <o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">Then I learned that I have the
“inattentive” presentation of Attention Deficit Hyperactivity Disorder (ADHD)
which is a cognitive processing disorder, and that my constant struggle to
handle social pressure (which blocked me from many promotions) was related to
level 1 Autism spectrum disorder. It was as though this AuDHD diagnosis snapped
everything into focus and all my ‘failure-to-launch’ suddenly made sense. <o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">Meanwhile, counseling related to
grief and codependency and family addiction trauma gave me new tools to “handle
hard stuff”. It gave me grace for myself (accepting that today is enough, and I
don’t have to accomplish everything I once thought I should), and it gave me
the capacity to sit with others in their hard stuff (as my dopamine reserves
allow). I also bring my widower journey with me, and my recovery from a mental
health crisis.<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">I bring all of this with me into my
studies, my perspectives, my worldviews, and my interactions with people. There
are positives and drawbacks to each of those for my calling. Part of becoming
an “integrated human”, as my counselor once calls, is to accept that all those
things are true and own them. So, if these hard things are part of my context,
what strengths do I bring to the table?<o:p></o:p></p>

<h1>STRENGTHSFINDER INSIGHTS<o:p></o:p></h1>

<p class="MsoNormal" style="text-indent: .5in;">I first took CliftonStrengths in
2014 at the beginning of a long process of personal and religious Deconstruction.
Several pivotal, traumatic, life-altering events have taken place between 2014
and 2024. The cumulative effects of these are a profound shift in my
personality. No small part of that shift was due to “de-masking” after the
AuDHD diagnosis; seeking my authentic self behind neurodivergent masks
originally created to live in a neurotypical world. <o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">So, I decided to take this
opportunity to re-take the CliftonStrengths. While my results shifted slightly
between 2014 and 2024 in some important ways, my patterns remain centered
around the life of the mind. My happy place is at my desk or with my books,
pouring over ideas, learning new information, and drawing out the contexts through
a process of intellection and ideation to connect new dots between seemingly
disparate ideas. The intellectual strengths pair with each other as dynamic
duos, pulling more out of their combination.<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">Meanwhile, my life of the mind is
balanced through paradoxical pairs. Context allows me to see all the “what ifs”
and Strategic allows me to push forward without getting stuck in analysis. A
need to achieve and cross off to-do lists – and – my need to make deep
connections and relate to the minds of others, both pull me out of my own mind
and connect me with the world around me. It is not enough to hold these ideas
and connected-dots to myself, I must share them with others. <o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">This leads me to the spiritual gift
Yeshua uses in me to bring gifts to his people, “teaching”. διδασκαλία (<i>didaskalia</i>;
teaching, instruction) - The act of teaching or instructing, focused on
imparting knowledge or doctrine to others (Romans 12, Ephesians 4). It is when
I’ve had hours, days, weeks, or sometimes years to dissect a topic or passage,
break it down to its core elements, and fit it back together by connecting all
the relevant dots that I begin helping others see those dots.<o:p></o:p></p>

<h1>CONCLUSION<o:p></o:p></h1>

<p class="MsoNormal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The
hardships, grief, trauma, and subsequent counseling left me with the capacity
to be brutally vulnerable with others – a policy I call “No Hiding”. Getting my
AuDHD diagnosis gave me the capacity to recognize my strengths and limitations,
carving out space for the unique challenges I face as a neurodivergent navigating
a neurotypical world. My strength-sets allow me to revel in the playground of
the mind, which blend well with my autistic need to preserve energy and limit
my exposure to sensory overload. For example, working from home two days a week
has allowed me to stay engaged in my job without being overwhelmed by social
interactions and harsh lights of the office environment. My Relator strength
allows me to share my internal world with those who can meet me on that
playground. My teaching gift allows me to share the insights from that life of
the mind with a broader audience. For now, I am at Fuller learning both the academic
skills to go deeper into that life of the mind while learning more about how my
contexts play a role in that endeavor. Where we go from here is yet to be
determined; it is enough for this season to “do justice, love kindness, and
walk humbly with my God” (Micah 6:8).<o:p></o:p></p>

<div><!--[if !supportFootnotes]--><br clear="all" />

<hr align="left" size="1" width="33%" />

<!--[endif]-->

<div id="ftn1">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Formation_for_Theological_Studies_SF509/AutobiographyUnderstanding%20of%20Calling_Wolfe_Darrell_.docx#_ftnref1" name="_ftn1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[1]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;tD1qpfm7&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Darrell
Wolfe, \\uc0\\u8220{}Author\\uc0\\u8217{}s Note:,\\uc0\\u8221{} n.d., n.The
meme is common, original citation
unknown.&quot;,&quot;plainCitation&quot;:&quot;Darrell Wolfe, “Author’s Note:,”
n.d., n.The meme is common, original citation
unknown.&quot;,&quot;noteIndex&quot;:1},&quot;citationItems&quot;:[{&quot;id&quot;:1050,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/U7KLYHJD&quot;],&quot;itemData&quot;:{&quot;id&quot;:1050,&quot;type&quot;:&quot;document&quot;,&quot;title&quot;:&quot;Author's
Note:&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Wolfe&quot;,&quot;given&quot;:&quot;Darrell&quot;}]},&quot;locator&quot;:&quot;The
meme is common, original citation
unknown.&quot;,&quot;label&quot;:&quot;note&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Darrell Wolfe, “Author’s Note:,” n.d.,
n.The meme is common, original citation unknown.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn2">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Formation_for_Theological_Studies_SF509/AutobiographyUnderstanding%20of%20Calling_Wolfe_Darrell_.docx#_ftnref2" name="_ftn2" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[2]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;NSNVpSVh&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Saint
John of the Cross, {\\i{}The Dark Night of the Soul (La Noche Oscura Del Alma)},
trans. David Lewis (London: Thomas Baker,
1577).&quot;,&quot;plainCitation&quot;:&quot;Saint John of the Cross, The Dark
Night of the Soul (La Noche Oscura Del Alma), trans. David Lewis (London:
Thomas Baker, 1577).&quot;,&quot;noteIndex&quot;:2},&quot;citationItems&quot;:[{&quot;id&quot;:2259,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/7C39ENB4&quot;],&quot;itemData&quot;:{&quot;id&quot;:2259,&quot;type&quot;:&quot;book&quot;,&quot;event-place&quot;:&quot;London&quot;,&quot;language&quot;:&quot;en&quot;,&quot;note&quot;:&quot;Google-Books-ID:
B8tMAQAAMAAJ&quot;,&quot;number-of-pages&quot;:&quot;224&quot;,&quot;publisher&quot;:&quot;Thomas
Baker&quot;,&quot;publisher-place&quot;:&quot;London&quot;,&quot;source&quot;:&quot;Google
Books&quot;,&quot;title&quot;:&quot;The Dark Night of the Soul (La Noche Oscura
del Alma)&quot;,&quot;author&quot;:[{&quot;literal&quot;:&quot;Saint John of
the Cross&quot;}],&quot;translator&quot;:[{&quot;literal&quot;:&quot;David
Lewis&quot;}],&quot;contributor&quot;:[{&quot;literal&quot;:&quot;Benedict
Zimmermann,
OCD&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1577&quot;]],&quot;season&quot;:&quot;1579;
1908&quot;}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Saint John of the Cross, <i>The Dark
Night of the Soul (La Noche Oscura Del Alma)</i>, trans. David Lewis (London:
Thomas Baker, 1577).<!--[if supportFields]><span style='mso-element:
field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn3">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Formation_for_Theological_Studies_SF509/AutobiographyUnderstanding%20of%20Calling_Wolfe_Darrell_.docx#_ftnref3" name="_ftn3" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[3]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;dspHjtBa&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Kathryn
Greene-McCreight, {\\i{}Darkness Is My Only Companion: A Christian Response to
Mental Illness}, Second edition. (Grand Rapids, MI: Brazos Press, 2015), 114,
https://fuller.on.worldcat.org/oclc/904227520.&quot;,&quot;plainCitation&quot;:&quot;Kathryn
Greene-McCreight, Darkness Is My Only Companion: A Christian Response to Mental
Illness, Second edition. (Grand Rapids, MI: Brazos Press, 2015), 114,
https://fuller.on.worldcat.org/oclc/904227520.&quot;,&quot;noteIndex&quot;:3},&quot;citationItems&quot;:[{&quot;id&quot;:1530,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/6HK6HTSQ&quot;],&quot;itemData&quot;:{&quot;id&quot;:1530,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;RC455.4.R4
G74 2015&quot;,&quot;edition&quot;:&quot;Second
edition&quot;,&quot;event-place&quot;:&quot;Grand Rapids,
MI&quot;,&quot;ISBN&quot;:&quot;978-1-58743-372-6&quot;,&quot;number-of-pages&quot;:&quot;216&quot;,&quot;publisher&quot;:&quot;Brazos
Press&quot;,&quot;publisher-place&quot;:&quot;Grand Rapids,
MI&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Darkness is my only companion: a Christian
response to mental illness&quot;,&quot;title-short&quot;:&quot;Darkness is my
only
companion&quot;,&quot;URL&quot;:&quot;https://fuller.on.worldcat.org/oclc/904227520&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Greene-McCreight&quot;,&quot;given&quot;:&quot;Kathryn&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2015&quot;]]}},&quot;locator&quot;:&quot;114&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Kathryn Greene-McCreight, <i>Darkness
Is My Only Companion: A Christian Response to Mental Illness</i>, Second
edition. (Grand Rapids, MI: Brazos Press, 2015), 114,
https://fuller.on.worldcat.org/oclc/904227520.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn4">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Formation_for_Theological_Studies_SF509/AutobiographyUnderstanding%20of%20Calling_Wolfe_Darrell_.docx#_ftnref4" name="_ftn4" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[4]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;pOrIJGtb&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;{\\i{}The
Lexham English Bible (LEB), Fourth Edition}, Logo Bible Software., Harris, W.
H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., &amp;
Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010), n. All Bible quotes
from LEB, http://www.lexhampress.com.&quot;,&quot;plainCitation&quot;:&quot;The
Lexham English Bible (LEB), Fourth Edition, Logo Bible Software., Harris, W.
H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., &amp;
Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010), n. All Bible quotes
from LEB,
http://www.lexhampress.com.&quot;,&quot;noteIndex&quot;:1},&quot;citationItems&quot;:[{&quot;id&quot;:49,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/2TDD6GYW&quot;],&quot;itemData&quot;:{&quot;id&quot;:49,&quot;type&quot;:&quot;book&quot;,&quot;collection-title&quot;:&quot;Harris,
W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., &amp;
Wierenga, M. (Eds.)&quot;,&quot;edition&quot;:&quot;Logo Bible
Software&quot;,&quot;event-place&quot;:&quot;Bellingham,
WA&quot;,&quot;publisher&quot;:&quot;Lexham Press&quot;,&quot;publisher-place&quot;:&quot;Bellingham,
WA&quot;,&quot;source&quot;:&quot;Logo Bible
Software&quot;,&quot;title&quot;:&quot;The Lexham English Bible (LEB), Fourth
Edition&quot;,&quot;title-short&quot;:&quot;LEB&quot;,&quot;URL&quot;:&quot;http://www.lexhampress.com&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2010&quot;]],&quot;season&quot;:&quot;Copyright<span
style='mso-spacerun:yes'>  </span>, 2012, 2013 Lexham
Press&quot;}},&quot;locator&quot;:&quot;All Bible quotes from
LEB&quot;,&quot;label&quot;:&quot;note&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><i>The Lexham English Bible (LEB), Fourth
Edition</i>,
Logo Bible Software., Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D.,
Dunham, J., Reimer, J. A., &amp; Wierenga, M. (Eds.) (Bellingham, WA: Lexham
Press, 2010), n. All Bible quotes from LEB, http://www.lexhampress.com.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

</div><br /><br />

<span style="font-family: &quot;tempus sans itc&quot;;">Shalom&nbsp;<span face="sans-serif" style="background-color: white; color: #202122; font-size: 14px;">שָׁלוֹם</span>: Live Long and Prosper!</span>
<br />

<div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe</span>
</div>

Storyteller | Writer | Thinker | Consultant | Freelancer | Bible Nerd
<i>*Written withs some editing and research assistance from ChatGPT-4o</i>
</div>
