---
title: 'Class Assignment: What is the gospel, according to Matthew?'
date: '2024-06-09T12:46:00.0000000+00:00'
draft: false
categories:
  - 'Gospel'
---
Assignment: Without referencing any other New Testament writer, but you can reference any Hebrew Bible writer that the gospel author himself references, what is the gospel according to\...

Gospel Reading: Matthew

Darrell Wolfe

Literature, The King's University

Life of Jesus (BIBL-2302)

Professor Jason Moraff

October 25, 2020

# Questions

1.       Lilies of the Field (Matthew 6:28-30). Even Solomon was not dressed like lilies? I get that the point is not to worry. But I feel like there is something I'm missing. How are lilies and clothes comparable? How are Lilies adorned? There is something deeper here. Maybe if I know something about lilies, I could learn something about God's provision?

2.       Ch. 8 - I still do not understand why the demons wanted to go into the pigs or why Jesus let them. I have theories, but nothing fully satisfying.

3.       Ch. 9 -- How could we retool our churches to be hospitals for the sick rather than just schools for the healed?

4.       Ch. 17 -- How often do I look down on "little ones"? Either actual children, finding even my own children annoying or distracting from my "real work". Or spiritual children, those who "know less" than I do? If the least are greatest, am I seeing them through God's eyes?

5.       Ch. 25 -- I can't reconcile the 10 virgins. Are they believers? But then they'd all be allowed in? Are they Christians but five of them are in name only? Not really saved? Is this parallel to the one taken the other left Jesus referred to at his coming?

# Observations

- Matthew 1: Rahab and Ruth were both foreigners brought into the Kingdom of Heaven by forsaking all they had. Tamar and Bathsheba were women who had been wronged sexually. Mary was an Israelite who forsook her future to say yes to God and was perceived by others to be wronged sexually. These five women made the list of Jesus' family[1].

- Ch. 4 - Matthew summarizes Jesus' entire life message as: "Repent for the kingdom of heaven is at hand" but not "Repent, receive forgiveness, go to heaven when you die". Matthew 4:17[2]

- Ch. 7 - Gentiles come in and sit with Abraham in the Kingdom. Not a new kingdom. Not a different kingdom. We come in; they do not come out. We are grafted into Israel; we are not a separate (*implied better*) nation. We are part of the same continuous story.

- Ch. 8 - Peter's Mom gets sick even though he is serving Jesus. I guess life still happens when we choose to serve. We are not exempt.

- Ch. 8:20 - Jesus said he had nowhere to lay his head. Spangler and Tverberg pointed out that Jesus would have been an itinerate rabbi[3]. Therefore, Jesus is not saying he was "poor" he is saying that he was rejected by some of the places he traveled and wasn't accepted into anyone's home (as was the custom).

- Ch. 9 -- Gentile churches today are often no more friendly to the spiritually sick than the pharisees that Jesus was confronting.

- Ch. 10 -- I often hesitate to accept hospitality from those I have served or helped. I think this a challenge for me to allow community into my life. Breathing in and out, I must serve but allow myself to be served (10:10 NLT). On that note, am I more afraid of what people think of me than what God thinks of me? Am I afraid of people and not afraid of God (10:28)?

 Ch. 26 -- Let this cup pass... Even Jesus didn't always "want" to do God's will, but he willed to do God's will. The emotions need not be present for obedience.

# The Gospel According to Matthew

If gospel means "good news", what was the good news according to Matthew? It was that the old dead religious ways of being were passing away. A new vibrant way of living was among us. Matthew presents a Jesus who is rooted and grounded in the history of Israel's continuing story both in Jesus' own family of origin, as well as his fulfillment of prophecy, and he continues the story in our lives. He summarizes the entire life message of Jesus by saying that he came to preach one message: "Repent for the kingdom of heaven is at hand"[4]. I once heard a message from Bob Hamp, LMFT, who said that "repentance" simply means to think differently afterward. As such, Jesus began to challenge the minds of all who would listen. He told parables to attempt to alter the way they thought and the way they saw God's heart. He said, "you've heard... but I say...". He demonstrated his authority to challenge the status quo by revealing his power in healing and miracles. In one section, Jesus made a point to say that he was showing he had the authority to forgive sins by demonstrating that authority through healing. Matthew does not tell us of a hero but of the first and best role model. He is inviting us into the story. Jesus not only demonstrated this power in himself alone, but he gave it to his apostles as well. This power was available to anyone who would "have faith". Jesus frequently comments on those who have great faith, little faith, and no faith. He frequently puts the responsibility (good and bad) for outcome back on the receiver, "...your faith has made you whole". The Good News of Matthew is that if we will hear and think differently afterward, we can enter this Kingdom of Heaven now and live a new kind of adventurous life. He goes on to tell us that there are costs and rewards associated with this adventure lifestyle. And then he ends by telling us that we have access to the power of the risen Jesus to go out into the world and make disciples just as he had. I can almost hear him say "Tag, you're it".

------------------------------------------------------------------------

[1] *Messiah*, Immerse : The Reading Bible (Carol Stream, Illinois: Tyndale House Publishers, Inc, 2017).

[2] *Hebrew-Greek Key Word Study Bible: Key Insights Into God's Word. NKJV New King James Version*, Genuine Black Leather (Chattanooga, TN: AMG Publishers, 2015).

\3] Ann Spangler and Lois Tverberg, *Sitting at the Feet of Rabbi Jesus: How the Jewishness of Jesus Can Transform Your Faith*, Updated edition (Grand Rapids, Michigan: Zondervan, 2018).

[[4] *Key Word NKJV*. 4:17

Shalom שָׁלוֹם: Live Long and Prosper!

Darrell Wolfe

Storyteller \| Writer \| Thinker \| Consultant \| Freelancer \| Bible Nerd
