---
title: 'Random Study of Psalms 103'
date: '2024-10-18T06:50:00.0000000+00:00'
draft: false
categories:
  - 'NoHiding Faith Studies'
---
\~\~\~{=html}

> #### [Psalms 103](https://ref.ly/logosres/leb?ref=BibleLEB2.Ps103.1) "Of David.
>
> Bless Yahweh, O my soul, and all within me, bless his holy name. Bless Yahweh, O my soul, and do not forget all his benefits:
>
> - who forgives (סָלַח sālaḥ) all your iniquity (עָוֹן ʿāwōn),
> - who heals (רָפָא rāpāʾ) all your diseases (תַּחֲלֻאִים taḥaluʾîm),
> - who redeems (גְּאוּלִים geʾûlîm) your life from the pit,
> - *who crowns you with loyal love and mercies,*
> - who satisfies your life with good so that your youth is renewed like the eagle's.

> Yahweh does deeds of justice and judgments for all who are oppressed, who made known his ways to Moses, his deeds to the people of Israel.
>
> Yahweh is compassionate and gracious, slow to anger and abundant in loyal love.
>
> - He does not dispute continually, nor keep his anger forever.
> - He has not dealt with us according to our sins, nor repaid us according to our iniquities.
>
> For as the heavens are high above the earth, so his loyal love prevails over those who fear him.
>
> - As far as east is from west, so he has removed far from us the guilt of our transgressions.
> - As a father pities his children, so Yahweh pities those who fear him.
>
> For he knows our frame. He remembers that we are dust.
>
> - As for man, his days are like the grass. As the flower of the field, so he blossoms.
> - When the wind passes over it, it is no more, and its place knows it no longer.
>
> But the loyal love of Yahweh is from everlasting to everlasting on those who fear him, and his righteousness to their children's children, to those who keep his covenant and remember to do his precepts.
>
> Yahweh has established his throne in the heavens, and his kingdom rules over all.
>
> - Bless Yahweh, you his angels, you mighty heroes who do his word by obeying the sound of his word.
> - Bless Yahweh, all you his hosts, you his attendants who do his will.
> - Bless Yahweh, all his works, in all the places of his dominion.
> - Bless Yahweh, O my soul."

> **(Psalm 103, LEB)  **

#### Scofield Reference Bible Notes: PSALM 103

103:12 Three Hebrew words are trans, forgive, forgiven: kaphar, to cover; nasa, to lift away; salach, to send away (cf. Lev. 16:21, 22), the fundamental O.T. idea of forgiveness being not the remission of penalty, but the separation of the sinner from his sin. Psa. 103:12 expresses this.

C. I. Scofield, ed., The Scofield Reference Bible: The Holy Bible Containing the Old and New Testaments (New York; London; Toronto; Melbourne; Bombay: Oxford University Press, 1917), 648--649.

#### **Word References**

\[6411\] עָוֹן ʿāwōn 233× sin, wickedness, iniquity, often with a focus on the guilt or liability incurred, and the punishment to follow \[5771\] See guilt; iniquity; sin; wicked, wickedness.

William D. Mounce, Mounce's Complete Expository Dictionary of Old & New Testament Words (Grand Rapids, MI: Zondervan, 2006), 1007.

\[6142\] סָלַח sālaḥ 46× \[Q\] to forgive, release, pardon; \[N\] to be forgiven \[5545\]

Q Qal N Niphal

William D. Mounce, Mounce's Complete Expository Dictionary of Old & New Testament Words (Grand Rapids, MI: Zondervan, 2006), 1002.

\[8324\] 1 רָפָא rāpāʾ 69× \[Q\] to heal; \[N\] to be healed, be cured; \[P\] to heal, repair; \[Ht\] to recover \[7495\] See cure; heal; restore. Q Qal N Niphal P Piel

William D. Mounce, Mounce's Complete Expository Dictionary of Old & New Testament Words (Grand Rapids, MI: Zondervan, 2006), 1044.

\[9377\] תַּחֲלֻאִים taḥaluʾîm 5× diseases \[8463*\]

* the Lexical form listed by Kohlenberger is slightly different from that listed by Strong.

William D. Mounce, Mounce's Complete Expository Dictionary of Old & New Testament Words (Grand Rapids, MI: Zondervan, 2006), 1063.

\[1453\] גְּאוּלִים geʾûlîm 1× redemption, with an implication that the redemption involves recompense \[1350*\] * the Lexical form listed by Kohlenberger is slightly different from that listed by Strong.

William D. Mounce, Mounce's Complete Expository Dictionary of Old & New Testament Words (Grand Rapids, MI: Zondervan, 2006), 910.

Shalom שָׁלוֹם: Live Long and Prosper!

Darrell Wolfe

Storyteller \| Writer \| Thinker \| Consultant \| Freelancer \| Bible Nerd **Written withs some editing and research assistance from ChatGPT-4o*

\~\~\~
