---
title: 'Class Assignment: What is the gospel, according to John?'
date: '2024-06-09T12:49:00.0080000+00:00'
draft: false
categories:
  - 'Gospel'
---

<div>Assignment: Without referencing any other New Testament writer, but you can reference any Hebrew Bible writer that the gospel author himself references, what is the gospel according to...&nbsp;</div><div><br /></div>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span class="MsoBookTitle"><span style="font-size: 16pt; line-height: 200%;">Gospel Reading:
John</span></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Darrell
Wolfe<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Literature,
The King’s University<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Life
of Jesus (BIBL-2302)<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Professor
Jason Moraff<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">November
15, 2020</span></p>

<h1>Questions<o:p></o:p></h1>

<p class="MsoListParagraphCxSpFirst" style="line-height: normal; margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->1.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>3:18-19 – Does God send people to hell? God did not send
Jesus to condemn the world but to save it. He who believes is saved and does
not believe is condemned (for they rejected the answer). What about those who
have never heard? They did not reject him, yet. Hm. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->2.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>4:46-54 – Jesus is
presented with a little girl who is sick unto death, and his response feels
dismissive and frustrated? We often paint Jesus as a codependent “Oh, poor
baby, I’m coming to the rescue”. But really? He was quite harsh at time, to my
ears. What could this response teach me about walking as He did?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->3.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Ch 6 – Eat my flesh and drink my blood. Why was Jesus so
cryptic with his disciples? He practically provoked them to walk away. Why
can’t God just say things as they are? Why do we constantly have to play
guessing games with what God’s really saying or doing in our lives? This is a
genuine frustration of mine. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->4.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>11:4 – So, does God bring sickness into our lives on purpose
just so he can show off his ability to heal? That seems cruel. Yet, Jesus only
ever healed. He never put sickness on anyone. What else could this be saying,
rather than what I am hearing it say?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->5.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Ch 11 – Jesus Wept. Why? He already said he knew Lazarus was
dead and he was headed to raise him up. He just told Martha that was his
intention (though she did not understand him). What would cause Jesus to weep
here? Some say he identified with Martha and Mary’s pain. That could be true.
But as a Widower, as I work with other Widow(er)s, I find myself reliving my
own grief process. Could he have had his own earthly father’s death in mind as
he wept?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->6.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>12:20-26 – What does the detail about Greeks asking to see
Jesus have anything to do with his “answer” to them? <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->7.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>20:23 – If I forgive someone’s sins, they are forgiven? If I
do not forgive them, they are not forgiven? How does this make sense? What does
this mean practically for me today? <o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="line-height: normal; margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->8.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>21:11 – With a limited number of words, John tells us that
there were 153 fish in the net. That is a really odd detail to provide John.
Why? My only thought so far, is that it is just another example of this
grandfatherly style of John’s story. <o:p></o:p></p>

<h1>Observations<o:p></o:p></h1>

<p class="MsoListParagraphCxSpFirst" style="line-height: normal; margin-left: 0.25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -0.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>John tells us that not about the Kingdom of God, but about
our status as Children of God (1:12). He goes on to tell us that we are
transitioning from Law to Grace and Truth through Jesus. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: 0.25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -0.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>1:35-51 – Jesus started his ministry team with one
interaction {Andrew and another (John?)}, and then built his team from there. I
often wonder how I could ever build a ministry; it sounds so daunting. This
tells me, I only have to reach one, then another, and so on. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: 0.25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -0.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>3:14 – Adam fell to a live snake, Moses lifted up a dead
snake, and Jesus became the substitutionary sacrifice to undo all the snake
brought into this world. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: 0.25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -0.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>Ch 11 – Two ironies in the Pharisees response. (1) Jesus
raising the dead results in their plotting to kill him. (2) The High Priest
prophesies the death of Jesus saving Israel, then plots to kill Jesus. His own
mouth prophesied but he misunderstood the meaning of his own prophecy. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: 0.25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -0.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>17:15, 21 – Could these statements affect how we consider
politics? We are not to be taken out of the world; therefore, must engage it. The
2020 Christians in the USA are as divided as ever. The world seeing our unity
will believe. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: 0.25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -0.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>18:28 – Another irony, the Priests who sacrifice the
Passover lamb every year, are literally sacrificing the true Passover Lamb
himself, and they’re concerned about getting home and eating the lamb, small l.
<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="line-height: normal; margin-left: 0.25in; mso-add-space: auto; mso-list: l1 level1 lfo2; text-indent: -0.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>My Bible points out that the Strong’s number for “love” is
different between Jesus and Peter<a href="file:///H:/My%20Drive/TKU%20Courses%20to%20be%20reviewed%20and%20cleaned%20out/Life%20of%20Jesus%20-%20BIBL2302ONL2/.Completed/Gospel%20Reading%20John_Stud%20Wolfe,%20Darrell_Life%20of%20Jesus_Prof%20Moraff,%20Jason.docx#_ftn1" name="_ftnref1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[1]</span></span><!--[endif]--></span></a>.
Do you Agape me, yes, I Phileo you. The second time, Agape/Phileo. The third
time, Jesus comes down to Peter’s level. Do you Phileo me? Yes, I Phileo you. I
think Jesus has to meet me at my level more often than I like to admit.<o:p></o:p></p>

<h1 style="line-height: 200%;">The Gospel According to John<o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 150%; text-indent: 0.5in;">As an immigrant
grandfather telling the grandchildren and great-grandchildren stories of the
old world, John tells the intimate story of his experiences with the great I
AM. He seldom if ever mentions the Kingdom of God, preferring instead to point
out that “… as many as received Him to them He gave the right to become
children of God, to those who believe in His name” (John 1:12). This is the
story of the Children of God, and the invitation for all people to become a
part of that family. Throughout, John tells details of the land and language to
his audience, indicating that they do not already know. This is either because
he is writing to a non-Jewish audience or because he is writing after the fall
of Jerusalem or both. It is interesting to note that he uses the blanket
statement “The Jews” when he is obviously referring to the Jewish leaders such
as the Pharisees; presenting a possible line of demarcation between this new
broader family (all God’s people) and the old one (Just Israel). Yet, the
Jewishness of Jesus is imperative to His story as the Passover Lamb. Throughout
the story, Jesus shows us His father which is our Father. John gives intimate
details throughout the story, as one who was reliving fond yet sometimes dark
memories. He refers to himself only euphemistically as the “Disciple who Jesus
loved”. In doing so, we get to live through John as our surrogate, for we too
are the disciple whom Jesus loves today. John makes it clear, beyond doubt,
that Jesus claimed to be God/God’s son; that Jesus existed long before Abraham
was. Yet, this Son of God came to Earth, humbled himself as a man, and walked
among us. The word that kept coming to me throughout this Gospel was “Intimate”:
intimate details, intimate settings, and intimate loving interactions with
Jesus. John even chooses to end his tale with an intimate encounter, beachside,
where Jesus restores Peter by coming down to his level/ability to Love
(Agape/Phileo). Then he signs it with an admission that he was the disciple
whom Jesus loved and a first-hand witness to all these things. The Gospel
according to John is this: We are all now part of one family, God’s family. Any
and all who believe are welcome in Father’s house. There will be a cost to
joining this family, but the cost of not joining is far greater. <o:p></o:p></p>

<div><!--[if !supportFootnotes]--><br clear="all" />

<hr align="left" size="1" width="33%" />

<!--[endif]-->

<div id="ftn1">

<p class="MsoFootnoteText"><a href="file:///H:/My%20Drive/TKU%20Courses%20to%20be%20reviewed%20and%20cleaned%20out/Life%20of%20Jesus%20-%20BIBL2302ONL2/.Completed/Gospel%20Reading%20John_Stud%20Wolfe,%20Darrell_Life%20of%20Jesus_Prof%20Moraff,%20Jason.docx#_ftnref1" name="_ftn1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-font-family: Arial; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[1]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;0X1v3R1o&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;{\\i{}The
Hebrew-Greek Key Word Study BIBLE: Key Insights Into God\\uc0\\u8217{}s Word.
New King James (NKJV)} (Chattanooga, TN: AMG Publishers,
n.d.).&quot;,&quot;plainCitation&quot;:&quot;The Hebrew-Greek Key Word Study
BIBLE: Key Insights Into God’s Word. New King James (NKJV) (Chattanooga, TN:
AMG Publishers, n.d.).&quot;,&quot;noteIndex&quot;:1},&quot;citationItems&quot;:[{&quot;id&quot;:225,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/ANBA8KS5&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/ANBA8KS5&quot;],&quot;itemData&quot;:{&quot;id&quot;:225,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;There
are times when a Greek or Hebrew word has a distinct meaning that seriously
affects the proper interpretation of Scripture. Unless you are familiar with
these languages, you will not be able to determine what word in the original
text was used or the differences between these words-until now.\n\nThe
Hebrew-Greek Key Word Study Bible identifies the key words of the original
languages and presents clear, precise explanations of their meaning and usage.
Those who love God's Word will treasure this Bible, for it contains a whole
library of biblical helps within its
covers.&quot;,&quot;event-place&quot;:&quot;Chattanooga,
TN&quot;,&quot;ISBN&quot;:&quot;978-0-89957-868-2&quot;,&quot;publisher&quot;:&quot;AMG
Publishers&quot;,&quot;publisher-place&quot;:&quot;Chattanooga,
TN&quot;,&quot;title&quot;:&quot;The Hebrew-Greek Key Word Study BIBLE: Key
Insights Into God's Word. New King James (NKJV)&quot;,&quot;title-short&quot;:&quot;Key
Word Study Bible:
NASB&quot;}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><i>The
Hebrew-Greek Key Word Study BIBLE: Key Insights Into God’s Word. New King James
(NKJV)</i> (Chattanooga, TN: AMG Publishers, n.d.).<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

</div><br /><br /><br /><span style="font-family: &quot;tempus sans itc&quot;;">Shalom&nbsp;<span face="sans-serif" style="background-color: white; color: #202122; font-size: 14px;">שָׁלוֹם</span>: Live Long and Prosper!</span><br /><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe</span></div>Storyteller | Writer | Thinker | Consultant | Freelancer | Bible Nerd