---
title: 'I''m Darrell Wolfe, and this is my story...'
date: '2024-10-11T07:39:00.0030000+00:00'
draft: false
categories:
  - 'Class Assignment'
---

<i>Note: This was a class assignment at Fuller Seminary, and it came out so well I decided to post it on my blog. Something of this flavor and nature will become my own version of Blue Like Jazz, someday, if I ever write it.</i><div><br /></div><div><p class="MsoNormal" style="text-indent: .5in;">I grew up as a Pastor’s Kid (PK) in
the Disciples of Christ (DOC). I can still smell the wood pews, well-worn
cushions, and old hymnals and bibles resting in the back of the pew in front of
me. I can see the stained-glass windows dance on the walls as I had the sanctuary
to myself for hours each day, being homeschooled at the time. Sacred spaces
still give me a sense of “awe”, even if all traditions make me itch.<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">One day, I stood on the platform
looking over the empty pews, and I thought, “I belong here”. That moment still
sticks with me.<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">Unrelated to that moment, as a
child, I saw Jesus in a vision. When Paul lists Jesus appearing as a sign of
the apostle, I often think, “Well, I guess I check that box?”. I also saw a
rebel elohim (spirit entity) in a different vision. My childhood and teenage
years were peppered with spiritual dreams and “odd” experiences.<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">My DOC Church never really talked
about “the gifts” of the Holy Spirit in either a positive or negative light, so
if nothing else we were functionally Cessationist. Yet, I was having radical
spiritual experiences that continue to challenge my sense of what is “possible”
to this day.<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">Against that radical spiritual backdrop,
my alcoholic-pastor-father with an MDiv and Dmin from Claremont School of
Theology (CST) turned into an atheist crack-addict psychologist. With that
cognitive dissonance in view, I set out on a personal mission to find out what
is “true”. Given my dad’s history, I ran from Bible school, “ministry”, “pastoring”,
or even anything platform-ey.<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">The first life-phase of exploring
was driven to the less intellectual and more experiential side of Churchianity in
the Pentecostal and Word of Faith circles. One day my, at 23-years old, a
friend told me to go “jump into the deep end” at a local Pentecostal church. The
pastor was loud and laying hands on people as they fell, caught by ushers. <o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">I thought (inside, not out loud), “This
is weird, but everybody should experience new things. I’ll stay until it’s
over, call it an interesting experience, and leave. As long as he doesn’t come
over here, I’ll be fine—.” <o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">Before I had finished saying “fine”
in my head, the preacher stopped everything, cocked his head funny, and said
into the microphone, “Huh… well that’s interesting.” Then he turned his head to
look directly at me some 300 feet across the room, then walked directly to my
seat and called me into the aisle. Without touching me, without getting within 3-5
feet of me, he said, “God wants to open—" and he made a motion with his arms
like a veil being ripped. I woke up on the ground 20 minutes later. I thought
to myself, “Ok, maybe he knows something.” I stayed for a few years until his authoritarian
style spiritual abuse outweighed his experiences.<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">After years of both fascinating
experiences and more authoritarian style spiritual abuse in Pentecostal and
Word of Faith churches, my wife dying in an ER at 36-years old led me to
challenge the worldview(s) I had adopted for over a decade.<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">Again, I went on a search for “truth”,
this time academically. I enrolled in my BA in General Christian Studies and set
about to reading and listening to biblical scholarship. I learned about
exegesis, hermeneutics, and reading the Bible “in context”. I learned about the
Divine Council Worldview (Dr Michael S Heiser), the Ancient Near East (ANE) and
Second Temple Judaism. <o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">Today, October 10, 2024, I feel
grounded. I am no longer chasing any elusive “truth”. I accept the Bible on its
own terms. More importantly, Philip Yancey and Bob Hamp helped me be “okay to
be not okay” and sit with hard things that don’t have clean answers.<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Formation_for_Theological_Studies_SF509/Activity%20%5eN2--Story%20Corps%20for%20Darrell%20Wolfe.docx#_ftn1" name="_ftnref1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[1]</span></span><!--[endif]--></span></a> I need
only “do justice, love kindness, and to walk humbly with <i>my</i> God” (Micah
6:8 NRSV).<o:p></o:p></p>

<p class="MsoNormal" style="text-indent: .5in;">Yet, my passion for biblical
studies has lit up light a bonfire in my soul to know my Yeshua better, love
his community better, and activate my Learner strength by engaging in my
autistic special interest “biblical studies”. Where it goes from here is up to
him.<o:p></o:p></p>

<div><!--[if !supportFootnotes]--><br clear="all" />

<hr align="left" size="1" width="33%" />

<!--[endif]-->

<div id="ftn1">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Formation_for_Theological_Studies_SF509/Activity%20%5eN2--Story%20Corps%20for%20Darrell%20Wolfe.docx#_ftnref1" name="_ftn1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[1]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;dRonIkFA&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Philip
Yancey, {\\i{}Where Is God When It Hurts?} (Grand Rapids, Mich.: Zondervan,
1997); Bob Hamp, {\\i{}Think Differently Live Differently Keys to a Life of
Freedom.} (Southlake, Texas, USA: bobhamp.com, 2016),
https://tdacad.com/product/think-differently-live-differently-book/; Bob Hamp
and Poly Hamp, \\uc0\\u8220{}Think Differently Academy - A Virtual Community
for Life and Freedom,\\uc0\\u8221{} Homepage, Think Differently Academy,
accessed May 27, 2024,
https://tdacad.com/.&quot;,&quot;plainCitation&quot;:&quot;Philip Yancey, Where
Is God When It Hurts? (Grand Rapids, Mich.: Zondervan, 1997); Bob Hamp, Think
Differently Live Differently Keys to a Life of Freedom. (Southlake, Texas, USA:
bobhamp.com, 2016),
https://tdacad.com/product/think-differently-live-differently-book/; Bob Hamp
and Poly Hamp, “Think Differently Academy - A Virtual Community for Life and
Freedom,” Homepage, Think Differently Academy, accessed May 27, 2024, https://tdacad.com/.&quot;,&quot;noteIndex&quot;:2},&quot;citationItems&quot;:[{&quot;id&quot;:98,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/NLQWNDDW&quot;],&quot;itemData&quot;:{&quot;id&quot;:98,&quot;type&quot;:&quot;book&quot;,&quot;event-place&quot;:&quot;Grand
Rapids,
Mich.&quot;,&quot;ISBN&quot;:&quot;978-0-310-21437-3&quot;,&quot;language&quot;:&quot;English&quot;,&quot;note&quot;:&quot;OCLC:
864518538&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Mich.&quot;,&quot;source&quot;:&quot;Open
WorldCat&quot;,&quot;title&quot;:&quot;Where is God when it
hurts?&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Yancey&quot;,&quot;given&quot;:&quot;Philip&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1997&quot;]]}}},{&quot;id&quot;:96,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/DAEH7RJG&quot;],&quot;itemData&quot;:{&quot;id&quot;:96,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;In
Think Differently Live Differently Bob Hamp takes you on a practical journey to
change your thinking and discover a life of personal
freedom.&quot;,&quot;event-place&quot;:&quot;Southlake, Texas,
USA&quot;,&quot;ISBN&quot;:&quot;978-0-9963685-4-4&quot;,&quot;language&quot;:&quot;English&quot;,&quot;note&quot;:&quot;OCLC:
953439547&quot;,&quot;number-of-pages&quot;:&quot;207&quot;,&quot;publisher&quot;:&quot;bobhamp.com&quot;,&quot;publisher-place&quot;:&quot;Southlake,
Texas, USA&quot;,&quot;source&quot;:&quot;Open
WorldCat&quot;,&quot;title&quot;:&quot;Think Differently Live Differently Keys
to a Life of Freedom.&quot;,&quot;title-short&quot;:&quot;Think Differently
Live
Differently&quot;,&quot;URL&quot;:&quot;https://tdacad.com/product/think-differently-live-differently-book/&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Hamp&quot;,&quot;given&quot;:&quot;Bob&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2016&quot;]]}}},{&quot;id&quot;:1490,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/J5EJZXER&quot;],&quot;itemData&quot;:{&quot;id&quot;:1490,&quot;type&quot;:&quot;webpage&quot;,&quot;abstract&quot;:&quot;Fulfilling
Lives and Relationships - Topical Classes, eCourse &amp;
Masterclasses&quot;,&quot;container-title&quot;:&quot;Think Differently
Academy&quot;,&quot;genre&quot;:&quot;Homepage&quot;,&quot;language&quot;:&quot;en_US&quot;,&quot;title&quot;:&quot;Think
Differently Academy - A virtual Community for Life and
Freedom&quot;,&quot;URL&quot;:&quot;https://tdacad.com/&quot;,&quot;author&quot;:[{&quot;literal&quot;:&quot;Bob
Hamp&quot;},{&quot;literal&quot;:&quot;Poly
Hamp&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2024&quot;,5,27]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Philip Yancey, <i>Where Is God When It
Hurts?</i> (Grand Rapids, Mich.: Zondervan, 1997); Bob Hamp, <i>Think
Differently Live Differently Keys to a Life of Freedom.</i> (Southlake, Texas,
USA: bobhamp.com, 2016),
https://tdacad.com/product/think-differently-live-differently-book/; Bob Hamp
and Poly Hamp, “Think Differently Academy - A Virtual Community for Life and
Freedom,” Homepage, Think Differently Academy, accessed May 27, 2024,
https://tdacad.com/.</p></div></div></div><div><br /><br />

<span style="font-family: &quot;tempus sans itc&quot;;">Shalom&nbsp;<span face="sans-serif" style="background-color: white; color: #202122; font-size: 14px;">שָׁלוֹם</span>: Live Long and Prosper!</span>
<br />

<div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe</span>
</div>

Storyteller | Writer | Thinker | Consultant | Freelancer | Bible Nerd
<i>*Written withs some editing and research assistance from ChatGPT-4o</i>
</div>
