---
title: 'A New Testament Introduction Final Test (Student Project) Part 2 The Answer Key'
date: '2025-06-07T07:12:00.0010000+00:00'
draft: false
categories:
  - 'Class Assignment'
  - 'Seminary Course Work'
  - 'Thinking Biblically'
---

<div><div><i>To see the test before you see the answer key:&nbsp;</i><a href="https://www.nohiding.faith/2025/06/a-new-testament-introduction-final-test.html" target="_blank">A New Testament Introduction Final Test (Student Project) Part 1 The Test ~ NoHiding.Faith</a></div><div><br /></div><div><i>New Testament Introduction (NT500)</i></div><div><i>The following questions will test the students’ understanding of the key components of the course materials broken out into three sections. The questions will include Multiple Choice (10), True/False (10), and Short-Essay (5). This is an open book test, please have your primary texts and a copy of the NRSVue or CEB translations available.</i></div></div><h1>Answer Key<o:p></o:p></h1>

<p class="MsoNormal"><i>Note: I generally don’t use True/False questions for
testing, but since this assignment gave specific numbers of each type, I have
broken them down as requested: Multiple Choice (10), True/False (10), and
Short-Essay (5)<o:p></o:p></i></p>

<h2>Part I: Lectures<o:p></o:p></h2>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->1.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The term ‘Hellenism’ finds
its roots in the conquests of which ancient conqueror:<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Caesar Augustus<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>Alexander the Great
&lt; Correct<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Socrates the Wise<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Hellen of Troy<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->2.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Explain what Hellenism was,
and why it is crucial for understanding the New Covenant (NT) texts:<o:p></o:p></p>

<p class="MsoNormal"><b>Essay Answer: <o:p></o:p></b></p>

<p class="MsoNormal"><b>Hellenized people were those who adopted a Greek or
Greco-Roman culture due to the development and spread of the Polis (a Greek
City-State) in conquered territories. There were zero Jews living in the first
century who were so isolated from Hellenization as to be immune or untouched.
Hellenization was accepted, resisted, or both, but was never not-a-factor. Or
put more directly from the lecture: “There was no unhellenized Judaism in the
first century and no part of the Hellenistic world totally isolated from the
Jewish Experience” (Roetzel)<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->3.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The New Covenant writers
use descriptions of Jesus that echo those of Emperor Augustus on the Priene
Calendar Inscription.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>True &lt; Correct<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->4.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>While dissenting opinions
exist, most scholars agree that this gospel was produced first:<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Matthew<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>Mark &lt; Correct<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Luke<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>John<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->5.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>If it were not for this
gospel, there would be no written record to indicate that Jesus’s ministry
lasted more than one year:<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Matthew<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Mark<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Luke<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>John &lt; Correct<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->6.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Describe Intercalations
(Markan Sandwiches) in the gospel of Mark:<o:p></o:p></p>

<p class="MsoNormal"><b>Essay Answer:<o:p></o:p></b></p>

<p class="MsoNormal"><b>Inclusios, enclosing a words or themes before and after a
section to bracket them are closely related to Intercalations (sandwiching a
related or contrasting story within the middle of another story, to highlight
themes. Often in an A1 – B – A2 pattern. When Mark tells of a local Jewish
leader coming to Jesus about his daughter, then being interrupted by a sick
woman who was rejected by the leaders who Jesus calls ‘daughter’ and then ends
with the finale of Jesus healing the leaders’ daughter; Mark is using the two
contrasting stories to drive home theological ideas.<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->7.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Other than the letters
attributed to Paul (Rabbi Sha’ul), what other sources give us a portrait of his
life? <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The works of Josephus<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The works of Philo of
Alexandria<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>The work of
Luke-Acts &lt; Correct<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The book of Hebrews<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->8.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>According to the writings
of Paul (Rabbi Sha’ul), what are the themes and driving concerns of the 1<sup>st</sup>
century Jesus communities?<o:p></o:p></p>

<p class="MsoNormal"><b>Essay Answer:<o:p></o:p></b></p>

<p class="MsoNormal"><b>For Rabbi Sha’ul (Paul) the primary theme of his work is
to unite the Jews and Gentiles under the banner of Jesus. He views Peter and
James as having been called to the Jewish communities and Paul’s own calling as
primarily aimed at the Gentiles. However, Gentiles were entering a Jewish
movement. What did that mean for them? Were they converting to Judaism? Where
they to become Torah observant in the same ways that Jews did (both as law and
as culture)? Paul’s writings were centered on addressing the similarities and
differences of his Jewish and Gentile church members, and how they remain
different and yet one, “there is no Jew or Greek, Male or Female, Slave or
Master…” all are one, but clearly the differences remain. How do we live in
community with that tension? <o:p></o:p></b></p>

<p class="MsoNormal"><b>Directly from the lecture: The role of Torah observance,
laws of Moses, circumcision, and other ‘Jewish’ practices for Gentiles.<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->9.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Paul’s gospel is a story of
salvation for the human race in continuity with Israel’s Scriptures and in
contrast to the gospel of Rome. It was inherently both religious and political.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>True &lt; Correct<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->10.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>Regarding the book of Hebrews, which statement below is false:<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Hebrews’ Author is
anonymous, and various authors have been suggested.<b> &lt; Correct</b><o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Hebrews’ Audience is
anonymous, but the letter reads as if there is a familial closeness.<b> &lt;
Correct</b><o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>Hebrews is a
traditional epistle with a clear opening and closing, following the format of
Paul’s other letters. &lt;False<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Hebrews is an
often-overlooked key to concepts around the fatherhood of God. <b>&lt; Correct</b><o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->11.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The term Apocalypse (apokalupsis) in second temple Judaism
literature literally translates to:<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>End Times Prophecy<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>Uncovering/Unveiling/Disclosing
&lt; Correct<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Pending Disaster<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The Concealer / One who
hides <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto;"><b><i>(Fun fact, Calypso from Homer’s Odyssey and Pirates of the
Caribbean is the antonym for Apocalypse and it means Concealer or One who hides
or she hides. While related in their root, they are opposite words).</i><o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->12.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>An Apocalypse (apokalupsis) in second temple Judaism literature
is most commonly used to tell what kind of story:<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Anticipation that the world
will end suddenly because of something catastrophic and unexpected.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Anticipation that the world
will end because of the mess human beings have made of the earth.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Anticipation that things
are working toward a dystopian world in which evil reigns and good is
extinguished.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>Anticipation that
things are being revealed for what they actually are; and that the world and
everything in it will be made right. &lt; Correct<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->13.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The two-part work of Luke-Acts is known in the world of biblical
scholarship as a:<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>Diptych &lt; Correct<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Diphthong<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Dysentery<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Dysphoria<o:p></o:p></p>

<h2>Part II: NT Texts<o:p></o:p></h2>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->14.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>Matthew begins his gospel with several series of 14-step
lineages. How many sets of 14 does Matthew use?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>2<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>3 &lt; Correct There
were three sets of 14, making 42 generations in Matthew’s account, likely a
symbolic number.<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>4<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>5<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->15.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>Hebrews 11 is often called the ‘Hall of Faith’ which promises
that nobody who follows Yahweh/Yeshua ever dies without having received all the
promises they were owed beforehand.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>True<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>False &lt; Correct<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->16.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The book of Jude directly quotes from what other text within
second temple Judaism, which was not later accepted into the final canon of
‘scripture’.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The Wisdom of Solomon<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The Maccabees<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>1 Esdras<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>1 Enoch &lt; Correct
<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto;"><b>Fun Fact: While no other text is directly quoted in Jude, there are
possible allusions to another text not listed here, Assumption of Moses.<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->17.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>Paul’s letter to the Romans has a recurring theme exploring Jews
and Greeks (Gentiles). How could that theme inform one’s reading of Romans?
Give at least two examples.<o:p></o:p></p>

<p class="MsoNormal"><b>Essay Answer:<o:p></o:p></b></p>

<p class="MsoNormal"><b>For Paul, in Romans, the gospel is “for the Jew first and
also the Greek” (Rom 1:16 NRSVue). He shows the Gentiles how they had a Torah
in their own nature even if it was written, and yet he shows the Jew how
relying on Torah did not make them more like Yahweh (Ch 2). He goes on to show
that all humankind (Jew and Greek) have the same failures, such that with or
without Torah we all need a solution (Ch 3). He spends the rest of his letter
building on this theme, showing how Abraham believed before Torah, and then he
transitions to the ways in which Jew and Gentile can live in harmony as one
community of Jesus with shared gifts and resources. He ends his letter with allusions
and quotes from Tanakh showing that a day for Gentiles to join the movement was
always coming. Then he artfully names fellow workers showing names from various
origins</b>.<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoListParagraph" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->18.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The gospel of John begins by identifying Jesus as “The Lamb of
God” (Ch 1), then shows Jesus as The Good Shepherd (Ch 10), then ends with
Jesus asking Peter to “feed my lambs” (Ch 21). How could reading the gospel
with these hinge-points in mind inform your reading of the text of John?<o:p></o:p></p>

<p class="MsoNormal"><b>Essay Answer:<o:p></o:p></b></p>

<p class="MsoNormal"><b>John begins by showing that Jesus was the sacrificial
‘lamb of God’ whose slaughter would take away the ‘sins of the world’. This
pulled on a well-established idea within Judaism, exemplified by the temple
practices and by each year’s Pesach (Passover) feast, where the blood of the
lamb represented the doors passed over by the first-born killer in Exodus. By
using this imagery, John is showing that Jesus’ sacrifice will cause Yahweh to
‘pass over’ his reader’s failures as well. But then he subverts this image by
turning Jesus into the Shepherd midway through the story. At this point, Jesus
is not just the sacrifice, but he is now the new Moses, who will tend them as
sheep and lead them safety. But he will do this by ‘laying down his life’ for
the sheep; pulling nuance into the theme. In the end, John’s Jesus tells Peter
to take up the exact same mantle he is leaving behind. He wants Peter to become
a Shepherd that feeds the sheep but also lays his life down for them later.
This story transitions the readers from those who would follow Jesus as sheep,
to those who would become Shepherds for him over his sheep, and follow his lifestyle
and example; whether that means dying like Peter or living a long life like the
Beloved Disciple.<o:p></o:p></b></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<h2>Part III: Secondary Readings<o:p></o:p></h2>

<p class="MsoNormal"><i>BGNTS: Gupta, Nijay K. A Beginner’s Guide to New Testament
Studies: Understanding Key Debates. Grand Rapids, MI: Baker Academic: A
Division of Baker Publishing Group, 2020.<o:p></o:p></i></p>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->19.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>How did the New Testament authors read and/or understand their
Old Testament (Hebrew Bible)? There are two common views in biblical
scholarship, in context or out of context, briefly explain which view is most
compelling and why? <o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.25in; mso-add-space: auto;"><i>*Refresh
your understanding in Chapter 12: The Old and New Testament.<o:p></o:p></i></p>

<p class="MsoNormal"><b>Essay Answer:<o:p></o:p></b></p>

<p class="MsoNormal"><b>Scholars who take the view that the NT authors did not
read the OT in context, but imposed their ideas into the text generally cite
good reasons for their skepticism or confusion. For example, when Matthew says
the prophets predicted Jesus would be called a Nazarene, they find no such
prophecy in the texts of the Tanakh (OT). <o:p></o:p></b></p>

<p class="MsoNormal"><b>However, the discovery of the Qumran (Dead Sea) Scrolls
and subsequent scholarship created a blossoming field for the study of second
temple Judaism. By comparing the various second temple texts both at Qumran and
libraries throughout the world, and then comparing these with preserved
traditions in the Talmud, Midrash, and other Jewish writings, and then
comparing all these with the NT Authors, one tends to find a lot of similarity
in thinking and approach. Several methodologies used by ancient rabbis could
explain Matthew’s reasoning for using Isaiah’s “branch” (netzer) prophecy,
including word-play common to ancient rabbinic techniques. <o:p></o:p></b></p>

<p class="MsoNormal"><b>Regardless of Matthew’s exact reasons, the more data that
is provided the more convincing the argument that the NT Authors were either
all Jewish and writing with second temple Judaism’s worldviews, or at least
were heavily influenced by that worldview.<o:p></o:p></b></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->20.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>Some scholars see Paul’s writing as Apocalyptic, which means
that Paul’s gospel is not a continuation of the on-going story of
salvation-history but a line of demarcation into an entirely new age (Ch 5).<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>True &lt; Correct<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->21.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>There are two views in scholarship on ‘Women in Leadership’,
they are referred to officially in the BGNTS as the heretical leadership and egalitarian
leadership models.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>True<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>False &lt; Correct<o:p></o:p></b></p>

<p class="MsoNormal"><i>NTIC: McCaulley, Esau, Amy Peeler, Janette H. Ok, and
Osvaldo Padilla, eds. The New Testament in Color: A Multiethnic Bible
Commentary. Downers Grove, IL: IVP Academic: An Imprint of InterVarsity Press,
2024.<o:p></o:p></i></p>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->22.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The Turtle Island Biblical Interpretation recognizes that the
Indigenous Peoples of what is now North America had a relationship with Creator
long before the colonizers showed up with bibles and diseases. For these
tribes, their native mythologies, histories, creation stories and cultural
practices are an “Old Testament” to them even as The Hebrew Bible (Torah,
Tanakh, and Second Temple Judaism) are an ‘Old Testament’ for many first
century Jewish Jesus followers.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>True &lt; Correct<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->23.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The Hispanic Biblical Interpretation must “critique
Enlightenment-based biblical approaches” because they tend to deal with
afterlife concerns but not real-world practical concerns in local communities. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>True &lt; Correct<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->24.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The Asian American Biblical Interpretation is difficult to pin
down because there are so many cultures and time-periods represented in the
term “Asian American”, nevertheless, it seeks to find the overlap between
exegesis and the Asian American experiences and histories that this community
brings to the text, including the experience of being treated as “Always
Ethnic, Never American”.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>True &lt; Correct<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->25.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The African American Biblical Interpretation shows the unique
ways in which being Black in the United States of America is qualitatively
different than being black in other countries. A history of slave ownership
created a reading of the biblical texts rooted in ‘hope’ of freedom, with a
strong root in the Exodus narratives. This interpretation helps the reader see
hope in the midst of deep pain and turmoil and opposition.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>True &lt; Correct<o:p></o:p></b></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->26.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The Majority-Culture Biblical Interpretation (Reading While
White) is already the default reading and lion-share of biblical scholarship;
therefore, this reading is intended to make white people feel guilty about
being white and dominating the discussion, so they can stop contributing and
give others their turn instead.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>True<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]--><b>b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; font-weight: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></b><!--[endif]--><span dir="LTR"></span><b>False &lt; Correct<o:p></o:p></b></p>

<p class="MsoNormal"><b><i>Test Creator’s Note for the NTIC questions: <o:p></o:p></i></b></p>

<p class="MsoNormal"><b><i>These final questions on the NTIC were partially because
I needed to fulfill the T/F question count requirement. But then I wanted to do
justice to the various views. Yet, as a majority-culture white reader, I have
run into plenty of people in my life and in my churches that would answer True
to the final question, even if it was only in their heart or in words spoken
when they thought nobody could hear. This ideology is at the root of the MAGA
heresy, among others. <o:p></o:p></i></b></p>

<p class="MsoNormal"><b><i>In this way, I’ve used the T/F questions to drive home
the point of the texts, that all voices should be considered and that means all
voices. This is a corrective to those who would drown out non-white voices and
a corrective to those who would drown out white voices as well. Which I
gathered was a major reason for including Majority-Culture readings in this
text. This section does no so much ‘test’ the student’s ability to answer the
right questions; rather, it sends the student away with a final sense of the
importance of these texts and readings.</i></b><o:p></o:p></p><br /><br />

<span style="font-family: &quot;tempus sans itc&quot;;">Shalom&nbsp;<span face="sans-serif" style="background-color: white; color: #202122; font-size: 14px;">שָׁלוֹם</span>: Live Long and Prosper!</span>
<br />

<div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe</span>
</div>

Storyteller | Writer | Thinker | Consultant | Freelancer | Bible Nerd
<i>*Written withs some editing and research assistance from ChatGPT-4o</i>
<br /><br /><br />
