---
title: 'The Divine Council Worldview’s Relationship with Inter-Religious Dialogue, The Divine Council Worldview’s Relationship with Inter-Religious Dialogue'
date: '2025-06-12T13:58:00.0010000+00:00'
draft: false
categories:
  - 'Class Assignment'
---
** **The Divine Council Worldview's Relationship with Inter-Religious Dialogue

A reciprocal relational approach to missions.

**by**

**Darrell Wolfe**

**Submitted in partial fulfillment of the requirements**

**for the course Living Missiologically: SF503**

**Professor Mareque Ireland**

**Word Count 3107 (not including works cited or researched lists).**

**Thursday, June 12, 2025**

# Introduction

Lisa Cron, in her TEDx talk "Wired for story"[\[1\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn1), observed that throughout history societies have built themselves on stories. Long before written records, the oral storyteller took a prominent role in cultivating the culture of their tribe and passing down wisdom through stories. Stories remain deeply relevant to us in the modern era. The meta-narratives adopted by White US-American Evangelicals in the last 100 years have led to a host of culture wars culminating in the rise of Christian Nationalism sweeping the nation. In Spring 2025, these worldviews clashed in national protests. The behavior of the US Government that sparked these protests is owed in large part to White US-American Evangelicals taking control of the reigns of power due to the stories and narratives they adopted.

Those stories and narratives were my inheritance, and they left me with a lot of pain and confusion throughout my life, but especially after my late-wife's passing. In the wake of my world imploding, I began a process of questioning the stories I internalized and asking the question: "Am I more loyal to the doctrines I inherited or to the biblical author's own intended message?" The process of deconstructing US-American Churchianity and reconstructing the biblical authors worldview led me to a healthier relationship with Jesus, the Bible, and my fellow human Image Bearers. I no longer struggle with cognitive dissonance between my faith and my daily life.

My goal is to explore the meta-narrative of the biblical authors' worldview, and how it can inform our orthopraxy in the modern era. My specific claim is that an understanding of the biblical authors' Divine Council Worldview opens a new window into reciprocal relational inter-religious dialogue. To build the framework for this claim, I have laid the following roadmap: 1. I will briefly touch on the importance of our story, our meta-narrative. 2. I will explore the history and importance of Inter-Religious Dialogue 3. I will spend the lion-share of this paper highlighting the biblical authors' worldview and meta-narrative, which is far different from the one I inherited. 4. I transition to how the biblical authors' narrative can provide a framework for the modern era. 5. I will explore that worldview in the context of my missional calling.

# 1.      What kind of story are we living in?

The narratives we adopt and encode are what drive our view of self, view of God, and view of others; these narratives create worldviews that effect our interactions with every realm of our lives. It has often been noted by creatives that stories affect us in ways that rote memorization and teaching of facts cannot. The story we believe we are living changes how we view the world. Brandon Sanderson said, "the mandate of a writer is to get inside the heads of people other than yourself..." and "if they read a story with somebody who sees the world differently than themselves" they can become open to new ways of seeing the world.[\[2\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn2)

Our narratives matter. The biblical texts influence Jesus Follower's narratives and worldviews; and therefore, our interactions with those who are 'other' to our own US-American Evangelical contexts. We must examine our understanding of the biblical narratives, what they tell us about the 'other' and how we understand our sense of mission as followers of Rabbi Yeshua. If we are to have meaningful inter-religious and relational dialogue with those who are not yet Jesus Followers, it will require we be wise and harmless, and "consider carefully" how we live among those who are outside our Jesus communities (Mat 10.16; Eph 5.15-17). Drawing a finer point, understanding the Divine Council Worldview of the biblical authors gives us an entry point for reciprocal relational inter-religious dialogue in which we love and respect our dialogue partners.

# 2.      Inter-Religious Dialogue

Since the opening prologue of the Torah, Yahweh has been at work to restore the nations to himself (Gen 12, the call of Abraham). The rising of Rabbi Yeshua from the grave became a catalyst for an era in which the Gentile nations were invited to return to Yahweh's embrace. For over two thousand years, communities of Jesus have been planted all over the world. However, those communities exist within contexts, cultures, and pre-existing worldviews. If we are to "love thy neighbor" (Matt 22.39) it will mean respecting the individuals and communities with which we interact. This includes all people, not just fellow Christians. We "must treat people of any faith and no faith with genuine respect".[\[3\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn3)

As early as the 1970s, religious leaders and scholars debated the importance of Interfaith Dialogue (Vatican II).[\[4\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn4) One conclusion of the scholarly efforts since those early conversations was an "emphasis on neighbor" which means that "we cannot dialogue with, or witness to, people if we from the outset resent their views".[\[5\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn5) This means we are not preaching at our neighbors in a one-sided monologue; rather, we are in dialogue with our neighbors, learning from each other. Put another way, "Reciprocity is the glue that holds the relational polarities of uniqueness and unity together".[\[6\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn6) We hold dialogue as our chief aim because "relation is intrinsic to our personhood".[\[7\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn7)

This means we see people as people, humans, beings created to bear the image of God. When God met the ancient Israelites at Sinai, he had already freed them before entering a formal covenant. Throughout the early years of their developing relationship, God taught them to be his Image Bearers. They were to be a singled-out nation and their calling was to "bear Yahweh's name among the nations, that is, to represent him well".[\[8\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn8) If we are to be Image Bearers in our modern era, it is going to mean learning how to read the biblical author's in their own context and it will mean learning to recognize the presuppositions we bring to the text. When we come to the biblical narratives, we must recognize that we bring our own contexts to our reading. McCaulley highlights this well, "We come from somewhere, and that somewhere has left its mark whether we acknowledge it or not."[\[9\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn9) We need to understand the story we are being invited into, and how that meta-narrative can inform our own.

# 3.      What is the biblical story?

Dr. Witherington sets the tone of our study, "A text without a context is just a pretext for whatever you want it to mean; therefore always study the Bible in light of its original historical, archaeological, literary, theological, ethical contexts".[\[10\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn10) Walton describes these contexts using the metaphor of a "cultural river" in which the Israelites "floated on the current" of shared cultural narratives and worldviews with the surrounding cultures of their day.[\[11\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn11) By including contemporary literature in addition to a close reading of the biblical texts, we develop a healthier understanding of the story into which we are invited to participate. What story are the biblical authors, in all their variety, inviting us into? How does that story invite us into a shared cultural narrative that crosses eras and cultures? While not exhaustive, we will look at a few examples which provide clues to answer these questions.

## The Biblical Authors Meta-Narrative

            The opening prologue to Torah (Gen 1-11, supported by later texts throughout Tankah) tell us that God is the creator of order and the tamer of chaos, that humankind and the lesser gods of the Divine Council partnered to rebel against his rule, and that Yahweh turned the nations over other gods. But chapter 12 begins Yahweh's plan of redemption of all nations by carving out a nation for himself in Abraham. The Tanakh is an internal critique (Jewish writer to their own Jewish culture) of the ways in which they either worked with Yahweh or rebelled against him. This frequent failure to follow The Way of Yahweh is cited as the chief cause of their suffering and exile(s) as they interacted with the nations.

By the time we get to the New Covenant writers, we see the Messiah, Rabbi Yeshua, step onto the scene to create new hearts in the people and to free them from the 'powers' of the lesser gods. This Christus Victor view culminates in the ultimate victory of the Cross and Ascension, creating a new community of The Way of Yeshua. This Way is typified by "love thy neighbor" (Luke 10.27) as demonstrated in the sharing of resources and doing life together (Acts 2). The Apostle Paul (Rabbi Sha'ul) comes on the scene in this community to begin inviting Gentiles (the nations) into the community, and he cites stories throughout the Tanakh in his effort to show them the story they are adopting.

## Divine Council Worldview

            To understand my reason for engaging in inter-religious dialogue, I will briefly explain the Divine Council worldview and why it is relevant. The term Divine Council (Deut 32) Worldview has been in Old Testament scholarship for decades and was made popular in lay and the wider academy through the works of Dr. Michael Heiser.[\[12\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn12) Yahweh operates with a council of gods (lesser gods) (Deut 32, Psalms 82 and 89, Job 38, 1 Kings 22, 2 Chron 18). Various texts both within the Tanakh and in literature from second temple Judaism paint a portrait that some of the members of this Divine Council rebelled and this becomes part of the mission of Jesus to restore the order of things. This explains some of Paul's references to the powers that sometimes baffle western readers.[\[13\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn13)

In this reading of the texts, it becomes clear that Israel adapted their sister culture's worldviews of a council of gods. An interesting set of charts and comparisons showing the Ugaritic and Hebrew texts shows the early Israelites development of 'two powers' in heaven, a visible Yahweh and an invisible Yahweh.[\[14\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn14) Hilderbrand and Sritrakool build on Heiser's work as they developed their missional approach in Thailand. They critique the way modern western Christians "discount the reality of the gods" which "may be pulling a people away from a more biblical worldview".[\[15\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn15) They further develop the ways in which the biblical authors, including Jesus and Paul reference the powers, principalities, gods of the nations, and evil influences over humankind. Yet, "Even though humans fell into deception, rebellion and sin, God had a plan to redeem humanity back to their original purpose."[\[16\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftn16) They conclude that this worldview and understanding of the biblical narrative offers a more compelling, meaningful, and resonate message to the culture of Thailand and by extension many cultures in the 10-40 window. They see the nations are invited into a "a new nation that has no boundaries on earth, a kingdom of God. Humans take the place of the sons of God who have been judged by God."

            By reading the biblical authors in context, we can see the ways in which they adopted and adapted the cultural worldviews of their own cultures (both in the Ancient Near East, and later within the larger framework of Hellenized second temple Judaism). We also see that within this worldview, the nations had their own separate relationship with Yahweh through his lesser Council, and that those relationships were appropriate for them (Deut 32). We then see the mission of Jesus and Paul to invite the nations back into relationship with Yahweh. This view allows us to hold space for religions and worldviews that differ from our own.

# 4.      What is our narrative today?

Given the arguments above, it is entirely appropriate to accept another cultures or religions relationship with Yahweh on their terms. We can understand that all cultures and religions have attempted to understand the deeper truths of life and they offer wisdom and perspective that we can learn from; likewise, we can offer the wisdom and perspective of our culture and relationship with Rabbi Yeshua. We do not force them to convert; we engage in dialogue and offer an invitation for interested parties to join our communities. God loved the nations and gave his son "in order that everyone who believes in him will not perish but will have eternal life" (John 3.16). If God loved them that much, how could we treat them with disdain, distrust, or as less-than us in any way? Instead, we follow the example of Jesus and Paul and other followers in subversive love of thy enemies (Matt 5.43-48; Luke 6.27-37; Rom 12.14-21; Prov 25.21-22), we love the immigrants and strangers and 'other' who come among us (Deut 10.19; 24.17-18; Lev 19.33-34; Jer 7.6; Matt 25.35; Heb 13.2). We gather into communities of Jesus Followers, do life together, share resources, and meet often to discuss the texts of those who came before us (Acts 2). Jesus said that those outside the community would recognize us as his "if you have love for one another" (John 13.34-35). We demonstrate The Way of Jesus, the better way of being human, by our love of God and our love for our fellow human Image Bearers. We cannot love them if we judge them as 'ignorant heathens', as many did with a worldview of European colonialism.

# 5.      What is my mission in my context?

            That is a general argument for why it is important to treat those of other cultures and religions as co-equals in reciprocal relational dialogue; and how the Divine Council worldview creates the space to interact with others in an open-handed approach. Throughout my life I have been driven by a burning desire for 'true' things and 'real' things. I had experiences in childhood that prevented me from ever denying the existence of an Unseen Realm. This was why Heiser's work was pivotal in my own reconstruction of a more authentic biblical faith. However, my pursuit for the 'truth' has led me into a variety of experiences, church traditions, and methods of reading the Bible. Many of those were helpful, and many of those were harmful. After a particular worldview left me and my children deeply wounded, I set out to understand the biblical authors for myself rather than interpreting through the traditions handed down to me. This sent me to the academic study of the biblical texts and those texts contemporary to the biblical authors. I now fall under the wider heading of "Deconstruction" but also under the heading of "Reconstruction". I developed a healthier relationship with biblical texts, Jesus, Holy Spirit, Father, and as a result my fellow human Image Bearers.

My anti-tradition approach includes using terms that invite the hearer/reader to think differently about the texts of the biblical authors, as one may have noticed throughout this paper. That 'irreverent' approach, as one friend described it, has opened the doors for me to enter into dialogue with a host of people who have rarely had positive interactions with Christians or the Bible (especially not the common White US-American Evangelical brand of Christians). Recently, I met a fellow 'truth seeker' at a Buddhist Temple. While we came to the discussion with divergent paths in our deconstruction, the reciprocal relational dialogue has continued to bear fruit since that first meeting. We have learned much from each other.

I often speak with atheists, wiccans, and members of other faiths through happenstance meetings (divine encounters). My most common connections are invariably with a group I call the De-Churched. These are people who have Deconstructed Christianity (or at least Churchianity) but often have not taken a deeper look at the biblical texts or the biblical authors worldview on its own merits. In these, I do not dismiss or deny their experiences and worldviews. Rather, I get curious about what they think, feel, or perceive as 'true' in the world. People find themselves saying things like, "I don't know why I'm even telling you this..." and they go on to explore things with me that they would not feel safe exploring inside the four walls of most churches. The Divine Council Worldview has given me both a wider framework for understanding Yahweh's work among the nations and the freedom to see how each person's unique contexts were used by Yahweh to lead them to him. It is my contention that the Divine Council Worldview is one key to developing a healthier relationship with the biblical texts, which opens the opportunity for a healthier relationship with our fellow Image Bearers in all their contexts.

# 6.      Works Cited

Cron, Lisa. "Wired for Story: Lisa Cron at TEDxFurmanU." Ted Talk presented at the TEDxFurmanU. Furman University, Greenville, South Carolina, 4 May 2014.

Heiser, Michael. "The Naked Bible Podcast." The Naked Bible Podcast, n.d.

\_\_\_\_\_. "Co-Regency in Ancient Israel's Divine Council as the Conceptual Backdrop to Ancient Jewish Binitarian Monotheism." *Bull. Biblic. Res.* 26.2 (2016): 195--22.

\_\_\_\_\_. *The Unseen Realm: Recovering the Supernatural Worldview of the Bible*. First edition. Bellingham, WA: Lexham Press, 2015.

Hilderbrand, Kelly Michael, and Sutheera Sritrakool. "Developing a Thai Theological and Biblical Understanding of the World: Rethinking Thai Cosmology in Light of Divine Council Theology." *Transformation* 38.1 (2021): 63--77.

Imes, Carmen Joy. *Bearing God's Name: Why Sinai Still Matters*. Downers Grove, IL: IVP Academic, An Imprint of InterVarsity Press, 2019.

Jack O. Balswick, Kevin S. Reimer, and Pamela E. King. *The Reciprocating Self: Human Development in Theological Perspective*. Second Edition. Downers Grove: IVP Academic, An Imprint of InterVarsity Press, 2016.

Janette H. Ok, Osvaldo Padilla, and Amy L. B. Peeler. *The New Testament in Color: A Multiethnic Bible Commentary*. Edited by Esau McCaulley. IVP Academic, 2024.

Marèque Steele Ireland. "Conversion and the Mutually Transformative Power of Dialogue (Aka Fuller in Dialogue: Engaging the 'Other' with Civility)." *Theology, News & Notes*, Fall 2010.

Pachuau, Lalsangkima. "Witnessing to Christ in a Pluralistic World: Christian Mission among Other Faiths" (2011).

Sanderson, Brandon. "Q&A: Brandon Sanderson on the Importance of Fiction and How Writing Influences His LDS Faith." [Interview by Justin Carmony](https://www.deseret.com/2017/11/10/20636072/q-a-brandon-sanderson-on-the-importance-of-fiction-and-how-writing-influences-his-lds-faith/)v. Q & A Book Launch Interview, 11 November 2017. Deseret News, Deseret Magazine.

Walton, John H. *The Lost World of the Torah: Law as Covenant and Wisdom in Ancient Context*. The Lost World Series Volume 6. Place of publication not identified: Inter-Varsity Press, 2019.

Witherington, Ben. *Reading and Understanding the Bible*. Oxford ; New York: Oxford University Press USA, 2015.

"Gentile Gods at the Eschaton: A Reconsideration of Paul's 'Principalities and Powers' in 1 Corinthians 15 on JSTOR," n.d.

# 7.      Works Read and Researched for this Paper

Heiser, Michael S. "[Co-Regency in Ancient Israel's Divine Council](https://doi.org/10.2307/26371649,%20https:/dx.doi.org/10.2307/26371649) as the Conceptual Backdrop to Ancient Jewish Binitarian Monotheism." *Bulletin for Biblical Research* 26.2 (2016): 195--225.

Hilderbrand, Kelly Michael, and Sutheera Sritrakool. "[Developing a Thai Theological and Biblical Understanding of the World](https://www.jstor.org/stable/27081796): Rethinking Thai Cosmology in Light of Divine Council Theology." *Transformation* 38.1 (2021): 63--77.

Mullen, E. Theodore. *The Divine Council in Canaanite and Early Hebrew Literature*. Harvard Semitic Monographs no. 24. Chico, Calif.: Scholars Press, 1980.

Niemandt, Nelus. "[TOGETHER TOWARDS NEW LIFE FOR MISSIOLOGY?](https://doi.org/10.4314/ACTAT.V35I1.1,%20https:/www.academia.edu/19889320/TOGETHER_TOWARDS_NEW_LIFE_FOR_MISSIOLOGY_MISSION_AND_MISSIOLOGY_IN_THE_LIGHT_OF_THE_WORLD_COUNCIL_OF_CHURCHES_2013_POLICY_STATEMENT) MISSION AND MISSIOLOGY IN THE LIGHT OF THE WORLD COUNCIL OF CHURCHES 2013 POLICY STATEMENT." *Acta Theologica* (2015).

Pachuau, Lalsangkima. "[Missiology in a Pluralistic World](https://www.academia.edu/34367786/MISSIOLOGY_IN_A_PLURALISTIC_WORLD_THE_PLACE_OF_MISSION_STUDY_IN_THEOLOGICAL_EDUCATION)." *International Review of Mission* (2000).

---------. "[Witnessing to Christ in a Pluralistic World](https://www.academia.edu/63639702/Witnessing_to_Christ_in_a_Pluralistic_World_Christian_Mission_among_Other_Faiths): Christian Mission among Other Faiths" (2011).

Peterson, Ryan S. "[The Imago Dei as Human Identity](https://search.ebscohost.com/login.aspx?direct=true&scope=site&db=nlebk&db=nlabk&AN=1435735): A Theological Interpretation." Eisenbrauns, 2016.

Rozko, J. R. "[Toward a Mission-Shaped Vision of Theological Formation](https://www.academia.edu/4148062/Toward_a_Mission_Shaped_Vision_of_Theological_Formation_Implications_of_the_Missio_Dei_for_Theological_Education): Implications of the Missio Dei for Theological Education" (n.d.).

Smith, Anthony D. "[Biblical Beliefs in the Shaping of Modern Nations](https://doi.org/10.1111/nana.12131,%20https:/onlinelibrary.wiley.com/doi/abs/10.1111/nana.12131)." *Nations and Nationalism* 21.3 (2015): 403--22.

Taypin, Rommel. "[MISSIOLOGY IN A PLURALISTIC WORLD](https://www.academia.edu/34367786/MISSIOLOGY_IN_A_PLURALISTIC_WORLD_THE_PLACE_OF_MISSION_STUDY_IN_THEOLOGICAL_EDUCATION) THE PLACE OF MISSION STUDY IN THEOLOGICAL EDUCATION" (n.d.).

Walton, John H. *The Lost World of the Torah: Law as Covenant and Wisdom in Ancient Context*. The Lost World Series Volume 6. Place of publication not identified: Inter-Varsity Press, 2019.

"[Chapter One Three Models of Creation in the Bible](https://www-jstor-org.fuller.idm.oclc.org/stable/j.ctv1hqdhc8.7?searchText=Divine+Council+Worldview+and+the+gods+of+the+nations&searchUri=%2Faction%2FdoBasicSearch%3FQuery%3DDivine%2BCouncil%2BWorldview%2Band%2Bthe%2Bgods%2Bof%2Bthe%2Bnations%26so%3Drel&ab_segments=0%2Fbasic_search_gsv2%2Fcontrol&refreqid=fastly-default%3A5ebf2f9558ec9b2f6f4572cedc07f56d&seq=1) from The Priestly Vision of Genesis 1 on JSTOR," n.d.

"[Gentile Gods at the Eschaton](https://www-jstor-org.fuller.idm.oclc.org/stable/10.15699/jbl.1363.2017.290006?searchText=Divine+Council+Worldview+and+the+gods+of+the+nations&searchUri=%2Faction%2FdoBasicSearch%3FQuery%3DDivine%2BCouncil%2BWorldview%2Band%2Bthe%2Bgods%2Bof%2Bthe%2Bnations%26so%3Drel&ab_segments=0%2Fbasic_search_gsv2%2Fcontrol&refreqid=fastly-default%3A5ebf2f9558ec9b2f6f4572cedc07f56d&seq=1): A Reconsideration of Paul's 'Principalities and Powers' in 1 Corinthians 15 on JSTOR," n.d..

"[The Gods-Complaint](https://www-jstor-org.fuller.idm.oclc.org/stable/10.15699/jbl.1374.2018.452196?searchText=Divine+Council+Worldview+and+the+gods+of+the+nations&searchUri=%2Faction%2FdoBasicSearch%3FQuery%3DDivine%2BCouncil%2BWorldview%2Band%2Bthe%2Bgods%2Bof%2Bthe%2Bnations%26so%3Drel&ab_segments=0%2Fbasic_search_gsv2%2Fcontrol&refreqid=fastly-default%3A5ebf2f9558ec9b2f6f4572cedc07f56d&seq=1): Psalm 82 as a Psalm of Complaint on JSTOR," n.d.

------------------------------------------------------------------------

[\[1\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref1) Cron, Lisa. "Wired for Story: Lisa Cron at TEDxFurmanU." Ted Talk presented at the TEDxFurmanU. Furman University, Greenville, South Carolina, 4 May 2014.

[\[2\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref2) Brandon Sanderson. "Q&A: Brandon Sanderson on the Importance of Fiction and How Writing Influences His LDS Faith." [Interview by Justin Carmony](https://www.deseret.com/2017/11/10/20636072/q-a-brandon-sanderson-on-the-importance-of-fiction-and-how-writing-influences-his-lds-faith/)v. Q & A Book Launch Interview, 11 November 2017. Deseret News, Deseret Magazine.

[\[3\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref3) Lalsangkima Pachuau, "Witnessing to Christ in a Pluralistic World: Christian Mission among Other Faiths" (2011): 14

[\[4\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref4) Pachuau, "Witnessing to Christ in a Pluralistic World," 11.

[\[5\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref5) Pachuau, "Witnessing to Christ in a Pluralistic World," 23.

[\[6\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref6) Jack O. Balswick, Kevin S. Reimer, and Pamela E. King, *The Reciprocating Self: Human Development in Theological Perspective*, Second Edition. (Downers Grove: IVP Academic, An Imprint of InterVarsity Press, 2016), 39.

[\[7\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref7) Marèque Steele Ireland, "Conversion and the Mutually Transformative Power of Dialogue (Aka Fuller in Dialogue: Engaging the 'Other' with Civility)," *Theology, News & Notes*, Fall 2010.

[\[8\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref8) Carmen Joy Imes, *Bearing God's Name: Why Sinai Still Matters* (Downers Grove, IL: IVP Academic, An Imprint of InterVarsity Press, 2019), 51.

[\[9\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref9) Janette H. Ok, Osvaldo Padilla, and Amy L. B. Peeler, *The New Testament in Color: A Multiethnic Bible Commentary*, ed. Esau McCaulley (IVP Academic, 2024), xii.

[\[10\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref10) Ben Witherington, *Reading and Understanding the Bible* (Oxford ; New York: Oxford University Press USA, 2015).

[\[11\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref11) John H. Walton, *The Lost World of the Torah: Law as Covenant and Wisdom in Ancient Context*, The Lost World Series Volume 6 (Place of publication not identified: Inter-Varsity Press, 2019), 88.

[\[12\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref12) Note: the two most common outlets for Heiser's work are: Michael Heiser, "The Naked Bible Podcast," The Naked Bible Podcast, n.d.; Michael Heiser, *The Unseen Realm: Recovering the Supernatural Worldview of the Bible*, First edition. (Bellingham, WA: Lexham Press, 2015).

[\[13\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref13) "Gentile Gods at the Eschaton: A Reconsideration of Paul's 'Principalities and Powers' in 1 Corinthians 15 on JSTOR," n.d., n.This article provides a detailed treatment of Paul's references specifically within second temple Judaism's cultural worldview.

[\[14\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref14) Michael S. Heiser, "Co-Regency in Ancient Israel's Divine Council as the Conceptual Backdrop to Ancient Jewish Binitarian Monotheism," *Bull. Biblic. Res.* 26.2 (2016): 197--98. Note: This builds the case for a god-head within second temple Judaism long before Jesus arrived on the scene.

[\[15\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref15) Kelly Michael Hilderbrand and Sutheera Sritrakool, "Developing a Thai Theological and Biblical Understanding of the World: Rethinking Thai Cosmology in Light of Divine Council Theology," *Transformation* 38.1 (2021): 64.

[\[16\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Living_Missiologically_SF503/ST503_WolfeDarrell_ResearchPaper/ST503_WolfeDarrell_ResearchPaper_2.0.docx#_ftnref16) Hilderbrand and Sritrakool, "Developing a Thai Theological and Biblical Understanding of the World," 66.
