---
title: 'Your Question: What is your take on Original Sin or the state of sinfulness of human beings?'
date: '2025-01-26T02:28:00.0070000+00:00'
draft: false
blogger_blog: 'NoHiding.Faith'
blogger_status: 'LIVE'
blogger_post_id: '255699343274571557'
blogger_filename: '/2025/01/your-question-what-is-your-take-on.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/NoHiding.Faith/feed.atom'
categories:
  - 'Class Discussion Posts'
  - 'Sin'
---

<div style="text-align: left;"><i>My answer in a class discussion post</i></div><h4>Question: What is your take on Original Sin or the state of sinfulness
of human beings?&nbsp;</h4>

<p class="MsoNormal">My Thoughts: The idea of "Original Sin" is totally
foreign to the biblical authors worldview, up to and including Paul.&nbsp;<o:p></o:p></p>

<p class="MsoNormal">Some rabbis, thinking Augustine got Paul right, have argued
that Paul twisted Torah to say there was such an idea.<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn1" name="_ftnref1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[1]</span></span><!--[endif]--></span></a> However,
Stewart makes a decent case for defending that while the idea is completely
foreign to the Hebrew Bible, it was developed in Second Temple Judaism.<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn2" name="_ftnref2" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[2]</span></span><!--[endif]--></span></a> <o:p></o:p></p>

<p class="MsoNormal">This begs way too many questions for a discussion post, I will
try to be brief (not my strong suite, ha ha). <o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<h4>What is the biblical original of evil? <o:p></o:p></h4>

<p class="MsoNormal">Heiser has made the case in his books and podcasts that the
biblical authors would not describe the original of evil as a single event between
God and Adam in Genesis three.<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn3" name="_ftnref3" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[3]</span></span><!--[endif]--></span></a> Rather,
Genesis 1-11 operates as the prologue of Torah and Tanakh (and therefore the B’rit
Chadashah/ New Testament). <o:p></o:p></p>

<p class="MsoNormal">In this prologue, there are various portraits and narratives
that culminate in three major rebellions (and several minor ones). In all three
archetype rebellions, there are Human and Elohim rebels present. <o:p></o:p></p>

<p class="MsoNormal">In all three narrative archetypes, "death" is
shown as exile. Exile = Death. Physical death in later authors becomes the
ultimate exile.&nbsp;<o:p></o:p></p>

<p class="MsoListParagraphCxSpFirst" style="mso-list: l0 level1 lfo1; text-indent: -.25in;"></p><ol style="text-align: left;"><li>The Nachash (serpent) is a
word that calls on divine origins, not simply a talking snake. Original readers
would not simply see a snake, but a divine throne guardian operating in a
serpent like manner. It is the partnership of Human (adam), Life (eve), and HaNachash
(diviner or communicator for God, Shiny One, Serpent)<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn4" name="_ftnref4" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[4]</span></span><!--[endif]--></span></a> that
leads to the exile of Human from the garden (human/divine joint space). </li><li>The sin of the Watchers - The
elohim intermingle with humankind and create hybrid offspring. They are also
depicted as teaching humankind to war and kill. The story of the hybrid
Nephilim is a callback to various Mesopotamian and Babylonian mythologies of
the Apkallus. Long story there, but many Hebrew Bible texts make more sense once
we have that history in our brains.</li><li>The Rebellion at Babylon –
For some reason, various English interpreters insist on translating Gen 11 as
Babel, but it is the same Hebrew word for Babylon elsewhere, and that is
intentional. This is a call back to Babylon’s history including the Apkallus
from #2. Babylon considered themselves to have been founded by demigods who were
mighty kings and warriors. The Tower of Babel isn’t just a tower, it’s a Ziggurat
(worship temple) intended to bring the elohim (gods) and humankind together.
This is a rejection of Yahweh. Thus, he divorces the nations, turns them over
to the rebel elohim, and starts over with Abraham (See also Psalm 82, Psalm 89,
etc.).</li></ol><!--[if !supportLists]--><p></p>





<p class="MsoNormal">Genesis 12 is where the story really starts after this
prologue. All human evil, throughout the biblical authors, including Paul, is
brought back to the elohim + humankind tendency toward rebellion, and
culturally toward using empire to break human relationships. It is the human
tendency to partner with or be deceived by these rebel elohim that leads to so
much evil. This is seen individually but also at a macro level by comparing
God's rule and reign in contrast to "empire" where Babylon and Egypt
become archetypes of human + elohim evil inflicted on other humans.<o:p></o:p></p>

<p class="MsoNormal">Sin is humans inspired by evil spirits in rebellion against
God’s ways, resulting in broken relationship with God and fellow humans. Jesus
defeats the rebel "powers" and The Church begins the mission of
calling the divorced nations back to Yahweh, and taking dominion back from the
rebel elohim's nations.<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<h4>What is sin and what is Paul talking about? <o:p></o:p></h4>

<p class="MsoNormal">Paul is working through why there is no distinction between
different humans in regards to Jesus’ redemption, and he says, “For there is no
distinction, for all have sinned and fall short of the glory of God, being
justified as a gift…” (Rom 3:22-23). Thus, Paul’s statement is about there
being no distinction between Jew and Gentile, because all have fallen short.
Indeed, throughout the Hebrew Bible (Paul’s Scriptures), we see instance after
instance of humankind being given the chance to rise up and failing in their
relationship with God and/or their fellow human imagers. Paul goes on to expand
on this by discussing the history of Abram (Abraham) and how he was considered
to have faith and be loyal to Yahweh long before he received circumcision or any
outward signs of covenant. Again, this is a Jew vs Gentile discussion. <o:p></o:p></p>

<p class="MsoNormal">It’s important to note that Paul says, “until the law, sin
was in the world but sin is not charged to one’s account” – So he is not saying
that people are guilty before an arbitrary set of sky rules, which is how many
Christian traditions have ended up talking about “sin”. This reminds me of the
US-American context of the 20<sup>th</sup> century, where it was a “sin” to
wear makeup, go to the movies, smoke a cigarette, or other behaviors the
community deemed untoward but have no biblical prohibition. Sin is often
referred to as though it were about arbitrary behavior modification; rather,
than about right-relationships, which is the biblical concern.<o:p></o:p></p>

<p class="MsoNormal">Following the Hebrew Bible authors use of words like sin,
death, and exile interchangeably, Paul draws on the example of Human (adam)
showing that death entered the world through one man and therefore one man can
solve the problem.<o:p></o:p></p>

<p class="MsoNormal">What death? The death of exile from God’s presence. What is
the answer then? God-With-Us, Emmanuel, came down in human form and restored us
to right relationship with God and each other.<o:p></o:p></p>

<p class="MsoNormal">The entire argument is messier and muddier and more full of analogies
than clean systems of theology are capable of nuancing. The ancient Israelite authors
of the Hebrew Bible (and thus the Jewish authors of the New Testament) worked
primarily through euphemism, analogy, metaphor, poetic license, hyperbole, and
other literary devices to pain multiple portraits of the human condition from
multiple angles. <o:p></o:p></p>

<p class="MsoNormal"></p><ul style="text-align: left;"><li>The biblical narrative is <b>not </b>about Perfection &gt; Fall
&gt; Redemption. That’s a foreign concept to the biblical authors’ worldview.</li></ul><ul style="text-align: left;"><li>The biblical narrative is about Seed &gt; Failure to Thrive/Grow
into the Desired Outcome &gt; Continued Progress Toward the Outcome (Hebrew
Bible) &gt; Renewed Covenant and Re-Empowered Re-Invigorated Mission aka New
Creation / New Life (New Test) &gt; And someday, on The Day of the Lord, a
final and firm redemption and renewal in New Creation. </li></ul><p></p>



<p class="MsoNormal"><b>The narrative isn't about a fall, but a seed, failure, and
progressive work on that seed.<o:p></o:p></b></p>

<p class="MsoNormal">The narrative is that God started a project to join God’s
space with Human space, all humans fail in the process of that relationship,
and God is continuing to work to see that initial seed of an idea come to fruition.<o:p></o:p></p>

<p class="MsoNormal">There was no fall or “original sin”, because there was no perfection
to fall from. There was a seed, Human (adam) failed to finish the project, and
all humans since have lived with that failure (narratively). God worked and
continues to work on this human + God project, and he has initiated a new
higher phase in Jesus, and he has an ultimate phase coming on The Day.<o:p></o:p></p>

<p class="MsoNormal"><i>Side Note: When "original sin" is thrown out as
an idea imposed on the text, other debates about Genesis start to mean
less.&nbsp;I see no reason to understand Genesis 1-11 as anything but a
metaphor and analogy of the human condition, and when Paul or Jesus draw Human
(adam) into the discussion, they are calling on the literary figure, not a
literal one. It’s not unlike me saying, “Just like Iron Man pulled one over on
Thanos, Jesus pulled one over on the rebel elohim.” I’m drawing an analogy from
a literary/media figure to make a point about a real one.<o:p></o:p></i></p>

<div><!--[if !supportFootnotes]--><br clear="all" />

<hr align="left" size="1" width="33%" />

<!--[endif]-->

<div id="ftn1">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref1" name="_ftn1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[1]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;abf9Pend&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Tovia
Singer, \\uc0\\u8220{}Does Judaism Believe in Original Sin? - Outreach Judaism,\\uc0\\u8221{}
28 April 2014,
https://outreachjudaism.org/original-sin/.&quot;,&quot;plainCitation&quot;:&quot;Tovia
Singer, “Does Judaism Believe in Original Sin? - Outreach Judaism,” 28 April
2014, https://outreachjudaism.org/original-sin/.&quot;,&quot;noteIndex&quot;:30},&quot;citationItems&quot;:[{&quot;id&quot;:2493,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/VVSH8BKG&quot;],&quot;itemData&quot;:{&quot;id&quot;:2493,&quot;type&quot;:&quot;webpage&quot;,&quot;abstract&quot;:&quot;[button
linking=\&quot;new_window\&quot;
link=\&quot;http://outreachjudaism.org/sin-and-atonement-audio/\&quot;
align=\&quot;left\&quot; size=\&quot;big\&quot; type=\&quot;standard\&quot;
icon=\&quot;microphone\&quot; title=\&quot;Sin and Atonement\&quot;
text_color=\&quot;#ffffff\&quot; bg_color=\&quot;blue\&quot;]Click here to
listen to the Audio Sin and Atonement[/button] Question: Dear Rabbi Singer,
Does the Jewish faith have a teaching comparable to that of \&quot;original
sin\&quot; in the Christian tradition? By this I mean the teaching that all
human beings are born with an
innate&quot;,&quot;language&quot;:&quot;en-US&quot;,&quot;title&quot;:&quot;Does
Judaism Believe in Original Sin? - Outreach
Judaism&quot;,&quot;title-short&quot;:&quot;Does Judaism Believe in Original
Sin?&quot;,&quot;URL&quot;:&quot;https://outreachjudaism.org/original-sin/&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Singer&quot;,&quot;given&quot;:&quot;Tovia&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2025&quot;,1,25]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2014&quot;,4,28]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Tovia Singer, “Does Judaism Believe in
Original Sin? - Outreach Judaism,” 28 April 2014,
https://outreachjudaism.org/original-sin/.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn2">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref2" name="_ftn2" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[2]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;c9YQsLJ7&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Tyler
Allen Stewart, \\uc0\\u8220{}\\uc0\\u8216{}The Present Evil Age\\uc0\\u8217{}:
The Origin and Persistence of Evil in Galatians\\uc0\\u8221{} (Marquette
University, April 2019), Argument picks up around page 75., Dissertations (1934
-) - 830, Dissertations, Theses, and Professional Projects,
https://epublications.marquette.edu/dissertations_mu/830/.&quot;,&quot;plainCitation&quot;:&quot;Tyler
Allen Stewart, “‘The Present Evil Age’: The Origin and Persistence of Evil in
Galatians” (Marquette University, April 2019), Argument picks up around page
75., Dissertations (1934 -) - 830, Dissertations, Theses, and Professional
Projects, https://epublications.marquette.edu/dissertations_mu/830/.&quot;,&quot;noteIndex&quot;:31},&quot;citationItems&quot;:[{&quot;id&quot;:2494,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/8YH7CLA4&quot;],&quot;itemData&quot;:{&quot;id&quot;:2494,&quot;type&quot;:&quot;document&quot;,&quot;archive&quot;:&quot;Dissertations,
Theses, and Professional
Projects&quot;,&quot;archive_location&quot;:&quot;Dissertations (1934 -) - 830&quot;,&quot;publisher&quot;:&quot;Marquette
University&quot;,&quot;title&quot;:&quot;\&quot;The Present Evil Age\&quot;:
The Origin and Persistence of Evil in
Galatians&quot;,&quot;URL&quot;:&quot;https://epublications.marquette.edu/dissertations_mu/830/&quot;,&quot;author&quot;:[{&quot;literal&quot;:&quot;Tyler
Allen
Stewart&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2019&quot;,4]]}},&quot;locator&quot;:&quot;Argument
picks up around page 75. &quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Tyler Allen Stewart, “‘The Present Evil
Age’: The Origin and Persistence of Evil in Galatians” (Marquette University,
April 2019), Argument picks up around page 75., Dissertations (1934 -) - 830,
Dissertations, Theses, and Professional Projects,
https://epublications.marquette.edu/dissertations_mu/830/.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn3">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref3" name="_ftn3" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[3]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;pKTO48Xo&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Heiser,
{\\i{}The Unseen Realm}; Michael Heiser, {\\i{}Angels: What the Bible Really
Says about God\\uc0\\u8217{}s Heavenly Host}, 2018,
https://search.ebscohost.com/login.aspx?direct=true&amp;scope=site&amp;db=nlebk&amp;db=nlabk&amp;AN=1900613;
Michael Heiser, {\\i{}Demons: What the Bible Really Says about the Powers of
Darkness} (Bellingham, WA: Lexham Press, 2020); Michael Heiser,
\\uc0\\u8220{}The Naked Bible Podcast,\\uc0\\u8221{} The Naked Bible Podcast,
n.d.,
https://nakedbiblepodcast.com/episodes/.&quot;,&quot;plainCitation&quot;:&quot;Heiser,
The Unseen Realm; Michael Heiser, Angels: What the Bible Really Says about
God’s Heavenly Host, 2018, https://search.ebscohost.com/login.aspx?direct=true&amp;scope=site&amp;db=nlebk&amp;db=nlabk&amp;AN=1900613;
Michael Heiser, Demons: What the Bible Really Says about the Powers of Darkness
(Bellingham, WA: Lexham Press, 2020); Michael Heiser, “The Naked Bible
Podcast,” The Naked Bible Podcast, n.d., https://nakedbiblepodcast.com/episodes/.&quot;,&quot;noteIndex&quot;:32},&quot;citationItems&quot;:[{&quot;id&quot;:20,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/7SP8XMJB&quot;],&quot;itemData&quot;:{&quot;id&quot;:20,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS680.S86
H45 2015&quot;,&quot;edition&quot;:&quot;First
edition&quot;,&quot;event-place&quot;:&quot;Bellingham,
WA&quot;,&quot;ISBN&quot;:&quot;978-1-57799-556-2&quot;,&quot;note&quot;:&quot;OCLC:
ocn907177749&quot;,&quot;number-of-pages&quot;:&quot;413&quot;,&quot;publisher&quot;:&quot;Lexham
Press&quot;,&quot;publisher-place&quot;:&quot;Bellingham,
WA&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;The unseen realm: recovering the supernatural
worldview of the Bible&quot;,&quot;title-short&quot;:&quot;The unseen
realm&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Heiser&quot;,&quot;given&quot;:&quot;Michael&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2015&quot;]]}}},{&quot;id&quot;:272,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/9MSX7GS9&quot;],&quot;itemData&quot;:{&quot;id&quot;:272,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;Angels
is not guided by traditions, stories, speculations, or myths about angels.
Heiser's study is grounded in the terms the Bible itself uses to describe
members of God's heavenly host; he examines the terms in their biblical context
while drawing on insights from the wider context of the ancient Near Eastern
world. The bible's view on heavenly beings begins with Old Testament terms but
then moves into literature from the Second Temple period--Jewish writings from
around the 5th century BC to the 1st century AD. This literature from the time
between the Old Testament and the New Testament influenced the New Testament
writers in significant ways. With that important background established, the
book focuses on what the New Testament tells us about God's holy ones. Finally,
the book reflects on common misconceptions about angels and addresses why the
topic is still important and relevant for Christians
today.&quot;,&quot;ISBN&quot;:&quot;978-1-68359-105-4&quot;,&quot;language&quot;:&quot;English&quot;,&quot;note&quot;:&quot;OCLC:
1055048226&quot;,&quot;source&quot;:&quot;Open
WorldCat&quot;,&quot;title&quot;:&quot;Angels: what the Bible really says about
God's heavenly
host&quot;,&quot;title-short&quot;:&quot;Angels&quot;,&quot;URL&quot;:&quot;https://search.ebscohost.com/login.aspx?direct=true&amp;scope=site&amp;db=nlebk&amp;db=nlabk&amp;AN=1900613&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Heiser&quot;,&quot;given&quot;:&quot;Michael&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2021&quot;,11,14]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2018&quot;]]}}},{&quot;id&quot;:273,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/GL7LUWN2&quot;],&quot;itemData&quot;:{&quot;id&quot;:273,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;\&quot;Are
demons real? Are they red creatures with goatees holding pitchforks and sitting
on people's shoulders while whispering bad things? Did a third of the angels
really rebel with Satan? Are demons and \&quot;principalities and powers\&quot;
just terms for the same entities, or are they different members of the kingdom
of darkness? Is the world a chaotic mess because of what happened in Eden, or
is there more to the story of evil? What people believed about evil spiritual
forces in ancient biblical times is often very different than what people have
been led to believe about them today. And this ancient worldview is missing
from most attempts to treat the topic. In Demons, Michael Heiser debunks
popular presuppositions about the very real powers of darkness. Rather than
traditions, stories, speculations, or myths, Demons is grounded in what ancient
people of both the Old and New Testament eras believed about evil spiritual
forces and in what the Bible actually says. You'll come away with a sound,
biblical understanding of demons, supernatural rebellion, evil spirits, and
spiritual warfare.\&quot; - from the back cover&quot;,&quot;call-number&quot;:&quot;BS680.D5
H45 2020&quot;,&quot;event-place&quot;:&quot;Bellingham,
WA&quot;,&quot;ISBN&quot;:&quot;978-1-68359-289-1&quot;,&quot;note&quot;:&quot;OCLC:
on1157236819&quot;,&quot;number-of-pages&quot;:&quot;321&quot;,&quot;publisher&quot;:&quot;Lexham
Press&quot;,&quot;publisher-place&quot;:&quot;Bellingham,
WA&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Demons: what the Bible really says about the
powers of
darkness&quot;,&quot;title-short&quot;:&quot;Demons&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Heiser&quot;,&quot;given&quot;:&quot;Michael&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;]]}}},{&quot;id&quot;:46,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/48VY2VQY&quot;],&quot;itemData&quot;:{&quot;id&quot;:46,&quot;type&quot;:&quot;broadcast&quot;,&quot;collection-title&quot;:&quot;The
Naked Bible Podcast&quot;,&quot;title&quot;:&quot;The Naked Bible
Podcast&quot;,&quot;title-short&quot;:&quot;The Naked Bible
Podcast&quot;,&quot;URL&quot;:&quot;https://nakedbiblepodcast.com/episodes/&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Heiser&quot;,&quot;given&quot;:&quot;Michael&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2021&quot;,1,30]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Heiser, <i>The Unseen Realm</i>;
Michael Heiser, <i>Angels: What the Bible Really Says about God’s Heavenly Host</i>,
2018,
https://search.ebscohost.com/login.aspx?direct=true&amp;scope=site&amp;db=nlebk&amp;db=nlabk&amp;AN=1900613;
Michael Heiser, <i>Demons: What the Bible Really Says about the Powers of
Darkness</i> (Bellingham, WA: Lexham Press, 2020); Michael Heiser, “The Naked
Bible Podcast,” The Naked Bible Podcast, n.d.,
https://nakedbiblepodcast.com/episodes/.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn4">

<p class="MsoFootnoteText"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref4" name="_ftn4" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[4]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;VBwwiy5r&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Heiser,
{\\i{}The Unseen Realm}, \\uc0\\u167{}Chapter 11-Section: The Nachash of
Genesis 3.&quot;,&quot;plainCitation&quot;:&quot;Heiser, The Unseen Realm,
§Chapter 11-Section: The Nachash of Genesis
3.&quot;,&quot;noteIndex&quot;:33},&quot;citationItems&quot;:[{&quot;id&quot;:20,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/7SP8XMJB&quot;],&quot;itemData&quot;:{&quot;id&quot;:20,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS680.S86
H45 2015&quot;,&quot;edition&quot;:&quot;First
edition&quot;,&quot;event-place&quot;:&quot;Bellingham, WA&quot;,&quot;ISBN&quot;:&quot;978-1-57799-556-2&quot;,&quot;note&quot;:&quot;OCLC:
ocn907177749&quot;,&quot;number-of-pages&quot;:&quot;413&quot;,&quot;publisher&quot;:&quot;Lexham
Press&quot;,&quot;publisher-place&quot;:&quot;Bellingham,
WA&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;The unseen realm: recovering the
supernatural worldview of the Bible&quot;,&quot;title-short&quot;:&quot;The
unseen
realm&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Heiser&quot;,&quot;given&quot;:&quot;Michael&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2015&quot;]]}},&quot;locator&quot;:&quot;Chapter
11 -<span style='mso-spacerun:yes'>  </span>Section: The Nachash of Genesis
3&quot;,&quot;label&quot;:&quot;section&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Heiser, <i>The Unseen Realm</i>, §Chapter
11-Section: The Nachash of Genesis 3.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

</div><br /><br />

<span style="font-family: &quot;tempus sans itc&quot;;">Shalom&nbsp;<span face="sans-serif" style="background-color: white; color: #202122; font-size: 14px;">שָׁלוֹם</span>: Live Long and Prosper!</span>
<br />

<div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe</span>
</div>

Storyteller | Writer | Thinker | Consultant | Freelancer | Bible Nerd
<i>*Written withs some editing and research assistance from ChatGPT-4o</i>
<br /><br /><br />

