---
title: 'Class Assignment: John 2.13-15 Table Flipping Jesus in the Fourth Gospel'
date: '2025-05-09T06:32:00.0010000+00:00'
draft: false
categories:
  - 'Class Assignment'
---
\~\~\~{=html}

For a link to this paper in paper format: [John 2.13-15 Table Flipping Jesus in the Fourth Gospel](https://www.academia.edu/129202852/John_2_13_15_Table_Flipping_Jesus_in_the_Fourth_Gospel)

INTERPRETIVE WORKING PAPER (IWP)

John 2:13--25 \| Table Flipping Jesus in the Fourth Gospel

**by Darrell Wolfe**

**Submitted in partial fulfillment of the requirements**

**for the course New Testament Introduction: New Testament Introduction**

**Professor Janette Ok**

**Monday, April 14, 2025**

# I - TABLE FLIPPING JESUS

## JOHN 2:13--25

*"The Passover of the Jews was near, and Jesus went up to Jerusalem. In the temple he found people selling cattle, sheep, and doves and the money changers seated at their tables. Making a whip of cords, he drove all of them out of the temple, with the sheep and the cattle. He also poured out the coins of the money changers and overturned their tables. He told those who were selling the doves, "Take these things out of here! Stop making my Father's house a marketplace!" His disciples remembered that it was written, "Zeal for your house will consume me." The Jews then said to him, "What sign can you show us for doing this?" Jesus answered them, "Destroy this temple, and in three days I will raise it up." The Jews then said, "This temple has been under construction for forty-six years, and will you raise it up in three days?" But he was speaking of the temple of his body. After he was raised from the dead, his disciples remembered that he had said this, and they believed the scripture and the word that Jesus had spoken. When he was in Jerusalem during the Passover festival, many believed in his name because they saw the signs that he was doing. But Jesus on his part would not entrust himself to them, because he knew all people and needed no one to testify about anyone, for he himself knew what was in everyone." (John 2:13--25, NRSVue)*[\[1\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn1)

## OUTLINE of John 2:13--25 (NRSVue)

**1.     ** **Introduction and Setting (v. 13--14)**

a.       New Scene: Passover in Jerusalem (v. 13)

b.      Upon arrival, merchants are selling things at their tables (v. 14)

*                                                              i.     * *Background Context Required for Conflict: Tanakh and 2^nd^ Temple Judaism.*

**2.     ** **Jesus Flips Out (v. 15--16)**

a.       Jesus 'Flips Out' (v. 15)

b.      Jesus Explains His Anger (v. 16)

**3.     ** **Parenthetical Authorial Interpretation (v. 17)**

a.       Author inserts interpretation for the reader (motive) (v. 17)

**4.     ** **Jesus' Authority Challenged (v. 18--20)**

a.       Unidentified "Jews" challenge his authority (v. 18)

b.      Jesus responds with a cryptic response (which John's author will payoff in a future section) (v. 19)

c.       Unidentified "Jews" scoff at his cryptic response (v. 20)

**5.     ** **Parenthetical Authorial Interpretation (v. 21)**

a.       Author inserts interpretation for the reader (the key to the cryptic response) (v. 21)

Note: This is parenthetical to the above section, and not part of the conclusion

**6.     ** **Conclusion: Authorial Interpretation with Hindsight (v. 22-25)**

a.       Author inserts a final interpretation for the reader (v. 22-25)

                                                              i.      Foreshadowing the end of the gospel (v. 22)

                                                            ii.      Results of his actions, many believe (v. 23)

                                                          iii.      Hesitance in Jesus to get too close (Messianic Secret) (v. 24)

                                                          iv.      Omniscient Jesus (or at least wisely cautious) (v. 25)

# II - EXEGETICAL ISSUES

## Boundaries

In the Fourth Gospel (John), 2:12 ends with a conclusion for the previous pericope, v. 13 picks up with a new scene setting to start a new narrative entry. One could argue that the pericope ends with v. 22 as the conclusion of the event. However, the author continues the interpretive conclusion into v.25, and 3:1 begins a new narrative pericope with a new introduction. So, the data-driven boundaries are 2:12-25.

## Translations

The key to this pericope is Jesus' anger at the temple workers. The following translations reflect a strong similarity in the migration of the Greek for this pericope into English. While the synoptics use a different phrasing ("cave of robbers"), the author of the Fourth Gospel is focused on turning the Sacred Space of Yahweh's temple into a common profit center, or business center.

- "*He told those who were selling the doves, "Take these things out of here! Stop making my Father's house a marketplace!"*" (John 2:16, NRSVue)

- "*And to the ones selling the doves he said, "Take these things away from here! Do not make my Father's house a marketplace!"*" (John 2:16, LEB)

- "*To those who sold the doves he said, "Take these things away from here! Do not make my Father's house a marketplace!"*" (John 2:16, NET 2nd ed.)

- "*He said to the dove sellers, "Get these things out of here! Don't make my Father's house a place of business."*" (John 2:16, CEB)

- "*And said unto them that sold doves, Take these things hence; make not my Father's house an house of merchandise.*" (John 2:16, KJV 1900)

- "*and to the pigeon-sellers he said, "Get these things out of here! How dare you turn my Father's house into a market?"*" (John 2:16, CJB)

- "*And he told those who sold the pigeons, "Take these things away; do not make my Father's house a house of trade."*" (John 2:16, ESV)

## Keywords

- Key Words: Temple and House, Hebrew (בַּ֫יִת, bayit) Greek (οἶκος, oikos) has intricate ties to the Tanakh, specifically 2 Samuel 7 (David's House / Yahweh's House), see discussion below.

- Key Words: Marketplace (Greek: ἐμπόριον, emporion). It is worth noting that the synoptics all use "den of thieves" or "cave or robbers" for this in lieu of "Marketplace", indicating a different narrative goal or possibly a different oral tradition.

## Authorship

            Echevarría points out that the gospels were all originally anonymous, being assigned authorship as they were shared in early Jesus communities.[\[2\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn2) While many attribute authorship either to the apostle John or John the Elder, deSilva posits an interesting case for understanding the author as Lazurus.[\[3\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn3) Whoever the Beloved Disciple was, his testimony has the feel of someone intimately familiar with Jesus and with the life situation of the residence of Israel before the temple was destroyed. Keener points out that the author of this gospel is "noteworthy not for including the Greek translation but rather for including the Semitic terms that are translated."[\[4\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn4) Johannine scholarship has begun to recognize the influence of E.P Sanders' and Mark Nanos' work on Jesus within Judaism, reflecting that John's gospel does not "drift away from Judaism towards Greek patterns of thought" but rather "fits within the variety of Jewish ideas about God found in the first century C.E."[\[5\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn5) Meanwhile, Tat Yu Lam demonstrated that the Gospel of John sits within the 2^nd^ Temple Judaism ecosystem as part of the "Temple Cleansing-Rebuilding Tradition".[\[6\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn6) Lam's argument is to see larger themes within the cultural landscape as a framework for understanding John's Gospel within this tradition. When we see the hyper-Jewishness of John's Gospel, we cease to see his use of "the Jews" as a racial slur against Jewish people in general, and instead we see this as an internal debate between Jewish Jesus Followers and Jewish non-Jesus-Followers. When we read the gospel within this framework interpretive options around the temple cleansing theme become more apparent.

## Related New Covenant texts (Intertextual - NT)

The author of the Fourth Gospel is generally believed to have written long after the synoptics were complete and circulating (circa 90 C.E.) and "incorporates earlier traditions."[\[7\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn7) Rather than simply rehash the other gospels or oral traditions, John provides new insights into the person of Jesus. There is an overlap and difference with this event in the other gospels.[\[8\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn8) Matthew presents the driving out of the money changers but provides other details about the events, miracles, and children crying praises. Then he segues into a retreat for the night and shows more events the next day in which the challenges to his authority continue (Matt 21:1--46). Likewise, Mark provides slightly different details in a different order of events (Mark 11:1--33). Luke mentions the story, citing the "cave of robbers" line, but downplays the physical events of Jesus' actions, focusing instead on challenge to Jesus' authority (Luke 19:28--47). Also, Luke makes it sound like these Jerusalem temple trips were a daily occurrence for a season, each night retreating to home base (Luke 20:1). Blum says that the synoptics including this event at the end of Jesus' public ministry means there were two separate cleansing events, citing some dissimilarities in the details. [\[9\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn9) The radical nature of the cleansing event makes it unlikely to have occurred twice. If the historicity of the event is assumed, it is far more likely the synoptics got the timing correct, as a culmination event leading to the temple leadership seeking the death of Jesus as he interrupted their center of power in such a dramatic way. It is far more likely, given the various narrative and stylistic choices for the author of the Fourth Gospel, and the likely Socio-Historical contexts, that the author placed the story here to set the tone of why Jesus's cleansing was important and to set the tone of his ministry, rather than a strict adherence to details of history that is foreign to ancient biographers.

## Internal (Intratextual) Literary Contexts

Brown simplifies the Fourth Gospel into two books, "the book of signs" (chs. 1--12) and "the book of glory" (chs. 13--21).[\[10\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn10) David deSilva provides a brief overview of the structure of the fourth gospel as a whole:

"Prologue: Jn 1:1--18

The "Book of Signs": Jn 1:19--12:50: Jesus' ministry to the world

The "Book of Glory": Jn 13:1--20:31

Jesus' instructions to his followers: Jn 13:1--17:26

Passion and resurrection appearances and conclusion: Jn 18:1--20:31

Epilogue: Additional resurrection appearance and conclusion: Jn 21:1--25"[**\[11\]**](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn11)

The temple cleansing narrative is located at the front end of the Book of Signs, demonstrating the meaning-centered view of the events surrounding Jesus' life, death, and resurrection. The placement at the front of the text provides a book end to the moment where Jesus' body is destroyed, and he raises from the dead three day later, as he promised he would in the start of the narrative (John 2:19). This is a narrative literary move showing "meaning and moment of the incarnate Word."[\[12\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn12) Gupta notes that some early interpreters considered John a "spiritual gospel".[\[13\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn13)

## Literary & Rhetorical (Intratextual) Observations

The Tanakh indicates that a Jewish currency (half-shekel) was to be paid to the priests/temple as a "ransom" and to fund the temple activities (Exod 30:11-16). For people to fulfill this Torah command in the 2^nd^ Temple Period under Greco-Roman occupation, "Roman money was changed into Jewish money to pay the Temple tax."[\[14\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn14) Given that this type of activity is advocated in the Torah, or it is at least an attempt to fulfill the Mitzvah of Torah, one then wonders why Jesus found it so abhorrent. Commenting on this, Grassmick notes that it was the way in which the half-shekel command was handled, casually turning the temple into a center of commerce, that was at the root of Jesus' anger.[\[15\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn15) This speaks to debates and splits between Sadducees, Pharisees, Essenes, and the Qumran sects.[\[16\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn16) Jesus's Way finds itself in conflict with each, though to differing levels. Here in this pericope, the conflict is directed at the Sadducee handling of Torah and Temple. Understanding this conflict gives us a deeper understanding of the tension Jesus is addressing with his display of righteous anger.

## Socio-Historical (Extratextual) Contexts

For the sake of brevity, a full discussion of the Ancient Near East (ANE) and Tanakh concepts of Sacred Space is omitted here, but this gives further background to the discussion that follows regarding the 2^nd^ Temple Period tensions regarding the temple. This framework also provides additional context as to the source of Jesus' anger regarding the handling of Temple as Sacred Space. For that background, see Jesus and the Forces of Death by Matthew Thiessen.[\[17\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn17) For the more immediate context, we examine the current tensions between Jewish sects regarding the handling of the temple, and how that played out after its destruction.

The destruction of the temple in 70 C.E. is a factor largely overlooked by some interpreters of the New Testament.[\[18\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn18) By 85 C.E (though certainly before this), non-Jesus-follower Jews were purging their synagogues of Jesus-follower Jews. This inside-baseball rivalry between the Jewish sects led to questions about the legitimacy of each sides' perspectives. This becomes a "recurrent concern in John 9:22; 12:42; 16:2."[\[19\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn19) The author of the fourth gospel is writing this gospel after the destruction of the temple and of Jerusalem, and the perspective of the author processing this radical event must be considered when looking at the passage of Jesus cleansing the temple. In this, the author justifies The Way of Rabbi Yeshua as legitimate cleanser and ultimate representation of Torah, despite the devastating loss of Judaism's center of activity.

Throughout the Tanakh there was a "longstanding tradition of Temple critique."[\[20\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn20) While the entire Tanakh could be seen as a commentary by the biblical redactors against the long history of syncretism in Israel, this criticism reached a fever pitch during the 2^nd^ Temple period. Several sects divided over issues of Torah observance, leading in one case to the cache of texts discovered at Qumran (Dead Sea Scrolls). To understand the more immediate history into which Jesus is stepping, we pull back briefly to look at the events leading up to the current state of Temple affairs.

Antiochus IV Epiphanes (175--164 B.C.E.) led a series of persecutions against the Jewish anti-Hellenizers, which (among other things) included idol worship, cult-prostitutes, and unclean-animal sacrifices in the Temple of Jerusalem (this is the action referred to by author of Daniel as "the abomination that causes desolation", Dan 9:27; 11:31; 12:11). The Maccabean Revolt of 168-164 B.C.E. led to the restoration and cleansing of the temple in 164 B.C.E., which Jewish communities worldwide still celebrate as Hanukkah (rededication) to this day.

On one hand, this temple cleansing was a huge win for the Jewish community in Jerusalem. On the other hand, it led to a deep chasm in the life of various Jewish communities, when the long-held Zadokite line of priests was ousted by the new Hasmonaean priestly line. These events eventually led to the division of 2^nd^ Temple Judaism into multiple sects, of which the most well-known are the Sadducees (primary caretakers of the Temple), Pharisees (involved in temple life, but more involved in small local synagogues and day-to-day life of Jewish people), and Essenes (a hyper purity group, less is known about them), and the Qumran/Dead Sea sect that may or may not be related to the Essenes, but who considered themselves separate from the Temple primarily due to its impurities. Skarsaune also mentions a fact relevant here in relation to the opposition parties; the "Sadducean chief priests, who denied the resurrection of the dead (Mt 22:23--33; Acts 23:6--9)".[\[21\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn21) These were the ruling elite, and the primary source of Jesus' opposition. While the Pharisees had their disputes, many of their disputes with Jesus could be seen as disputes within the same group, not outsiders. While he stands alone in his own Halakhic tradition, Jesus is closest in scope to the Pharisees.

This history is in the minds of all the hearers of Jesus' words in the temple that day, and the subsequent history is in the minds of John's Jewish and Gentile audience, especially in light of both the destruction of the temple in real space-time and the synagogue cleansing activities of non-Jesus-follower Jews in the aftermath.

The author of the Fourth Gospel is writing this within a few years after the temple's destruction and placing Jesus' temple cleansing activity just a decades before. Schiffman and Potok note that when the Temple was destroyed and Jerusalem purged by the Romans in 70 C.E., most of these groups were eliminated or at least lost their base of operations. Of these, only the Pharisees were equipped to continue existing and thriving without the temple or Jerusalem as their base of operations.[\[22\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn22) Likewise, Skarsaune posits that a subset of two sects of 2^nd^ Temple Judaism "were mentally prepared to cope with the new situation,"[\[23\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn23) namely, the Pharisees and The Way of Rabbi Yeshua (Christ-Followers) were the two groups most well situated to carry on.

Therefore, placing this narrative at the front of his Gospel (whereas the synoptics place it at the end of theirs (Luke 19:46, Mark 11:17, Matthew 21:13), sets the tone of this gospel in a context where John's audience is not only facing questions about the legitimacy of a Jewish Messiah without the temple but also in light of their expulsion from traditionally Jewish spaces (diaspora synagogues).

## Author's use of Sources (Intertextual - Tanakh, Other NT Authors, Other contemporary works)

            When Jesus refers to the Temple as "my father's house" (v. 16) and then refers to his body as the temple (v. 19), he is drawing a long history of interpretation regarding the interchangeable terms Temple and House. In my paper on 2 Samuel 7,[\[24\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn24) I discussed the how the author of 2 Samuel uses the concept of "House" (Hebrew: בַּ֫יִת, bayit) in multiple interwoven meanings. David wants to build Yahweh a structure (temple/house) then Yahweh decides to build David a dynasty (house) and Yahweh goes further to say that he will use David's descendant to build himself a house (both structure and dynasty). Throughout the Tanakh and into the 2^nd^ Temple Judaism literature, the hope was building for a descendant of David to come and make things right.[\[25\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn25)^/[\[26\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn26)^

The author of John ends his prologue with declarations that Jesus is the "Son of God" and "King of Israel", both kingly declarations that draw upon the wider Messianic hope that builds on the promise of a son of David, that would eventually be the culmination of the physical and dynastic "House" for Yahweh, as promised to David in 2 Samuel 7. In these images, the author of the Fourth Gospel is weaving Jewish and Greek expectations. The author's use of "Zeal for your house will consume me" (v. 17) is a reference to a Psalm written from David's perspective, reflecting on this House/Temple/Dynasty promise, *"It is for your sake that I have borne reproach, that shame has covered my face. I have become a stranger to my kindred, an alien to my mother's children. It is zeal for your house that has consumed me; the insults of those who insult you have fallen on me." (Psalm 69:7--9, NRSVue)*[\[27\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn27)

            In this way, the author of the Fourth Gospel is drawing a reader familiar with the Messianic hopes of 2^nd^ Temple Judaism to the longstanding hope that David's descendant would come and clean house and make everything right again. Carrying the concept forward, then, the author shows Jesus reimagining the promise further blurring the lines between House, Temple, Dynasty, and now his physical body, showing that his life, death, and resurrection (coming at the end of John's gospel) would be the culmination of this David Covenant promise.

## Wisdom of the text

            The author of the Fourth Gospel had a purpose in including the narratives they chose to include. Echevarria says that while "some speculate the John's gospel addresses deficient beliefs of his followers in Asia Minor..." we should focus on the resulting gospel, and what it tells us about Jesus, not speculations regarding what it might have been correcting.[\[28\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftn28) The author is writing to a post 70 C.E. audience who've been ejected from diaspora synagogues while following the ways of a Jewish Messiah. The author wants to encourage his audience that this path is the correct path, despite increasing persecution both from non-Jesus-follower Jews and from the Roman Empire as a whole. By including this narrative at the front of the text, the author agrees with the Qumran sect that the temple was corrupt and needed to be cleansed, and that those who are in Jesus are the new Temple. At the point of this writing, the temple was already gone, and persecution was widespread. What motivation is there that the followers of Jesus should continue in The Way despite all those odds against them? The author provides this story to answer the question of which group had the better answers after the temple's destruction and which group had The Way of Life.

# III - SIGNIFICANCE FOR THEOLOGY AND PREACHING

I spent the better part of the last five years visiting as many different churches and church traditions as I could fit into my schedule (and emotional bandwidth). I attended a Catholic Mass recently that reminded me of a temple, with iconography and stained glass and ornate fixtures. A prominent open-air gift shop displayed trinkets, crosses, rosaries, prayer shawls, and other iconographic wares for sale. I thought about this narrative from John and wondered, "What would Jesus feel about this gift shop?" I then thought about all the bookstores and coffee shops in the ubiquitous Mega Churches I've visited and joined over the years. I thought about specialty Bibles with our favorite celebrity pastor's name on the cover. I thought about how an entire wing of white US-American evangelicals sold their soul to a scam artist and huckster whose dedication to Jesus is so plastic, so surface, so veneer, that it is plain to all who did not buy his snake oil. Then I thought about how he doubled down on this pseudo-Christianity by selling them a Bible with his name on it and then blending a feigned love of God with love of country (a Yahweh-Roman syncretistic hybrid). In a post 70 C.E. world, Jewish people were seeking an identity without a temple. Some went to The Way of Rabbi Yeshua, others went with the Pharisees. Today, many of us who are disillusioned with both the USA and the Churchianity we were raised with are also looking for an identity without them. Some have gone with the Pharisees and followed the way of MAGA. Others have been left feeling homeless and asking what it would mean to continue being Jesus Followers without our temples.

# IV - ANNOTATED BIBLIOGRAPHY

## Course Assigned Texts

1.      Nijay K. Gupta. *A Beginner's Guide to New Testament Studies: Understanding Key Debates*. Grand Rapids: Baker Academic, 2020.

-- Gupta's text provides a framework for new students to begin asking interpretive questions of the text, including text critical discussions. There is a discussion introducing each book's most common questions, including John's Gospel.

2.      Janette H. Ok, Osvaldo Padilla, and Amy L. B. Peeler. *The New Testament in Color: A Multiethnic Bible Commentary*. Edited by Esau McCaulley. IVP Academic, 2024.

-- Specifically, Miguel G. Echevarría provides a breakdown for the "Gospel of John". Like deSilva, Echevarría also mentions the possibility of Lazarus being the Beloved Disciple. Echevarría discusses various text critical elements of John's Gospel as well as the over arching themes present within the text.

## Commentaries

1.      C. S. Keener, "John, Gospel Of," in Nicholas Perrin, Jeannine K. Brown, and Joel B. Green. *Dictionary of Jesus and the Gospels (DJG)*. IVP Bible Dictionary Series. Downers Grove, Ill: IVP Academic, 2013

 -- Keener provides additional details about text critical issues regarding John's gospel. Specifically, the section 2.3.2 Judaism was helpful in providing context regarding this passage.

2.      DeSilva, David Arthur. *An Introduction to the New Testament: Contexts, Methods & Ministry Formation*. Second Edition. Downers Grove: InterVarsity Press, 2018.

-- DeSilva's text pairs well with the two course texts in introducing the reader to text critical issues and interpretive methods. He also provides a breakdown of Narrative Criticism which is helpful when discussing Johannine literature.

3.      Edwin A. Blum, "John," in The Bible Knowledge Commentary: An Exposition of the Scriptures, ed. J. F. Walvoord and R. B. Zuck (Wheaton, IL: Victor Books, 1985), 279--280.

-- While not a text from after 2000, this text deserves an honorable mention as it helped provide some additional insights into the larger/longer debates in Johannine studies.

## Monographs

1.      Craig R. Koester, *The Word of Life: A Theology of John's Gospel* (Grand Rapids, MI; Cambridge, U.K.: William B. Eerdmans Publishing Company, 2008)

-- This text helps take some of the text critical and historical hats off, and place a "so what" hat on. Why does this gospel matter? How can it help one think theologically about the text.

2.      Skarsaune, Oskar. *In the Shadow of the Temple: Jewish Influences on Early Christianity*. Downers Grove, Ill: InterVarsity Press, 2002.

-- This text is helpful for understanding the cultural moment in which the gospels take place.

3.      Jipp, Joshua W. The Messianic Theology of the New Testament. Grand Rapids (Mich.): William. B. Eerdmans Publishing Company, 2020.

\- This text is helpful for understanding Messianism in the 2^nd^ Temple Judaism.

4.      Schiffman, Lawrence H., and Chaim Potok. Reclaiming the Dead Sea Scrolls: The History of Judaism, the Background of Christianity, the Lost Library of Qumran. Anchor Yale Bible Reference Library. New Haven, Conn.: Yale Univ. Pr, 1995.

\- This text provides a detailed breakdown of the history of Qumran's break with the Hasmonean dynasty; and thus the Sadducees and Pharisees. It also provides a Jewish Rabbinical scholarship breakdown of Messianism in 2^nd^ Temple Judaism without Christian filters.

5.      Matthew Thiessen. Jesus and the Forces of Death: The Gospels' Portrayal of Ritual Impurity within First-Century Judaism. Paperback edition. Grand Rapids, Michigan: Baker Academic, a division of Baker Publishing Group, 2021.

-- While not discussed or referenced much, this text heavily influenced my understanding of the way a Jewish audience understands what a temple is and why it matters to Jesus.

## Journal Articles

1.      Tat Yu Lam. "Hyper-Intertextuality: The Temple Cleansing-Rebuilding Tradition as a Compositional Framework in John's Gospel" ([2023](https://doi.org/10.1163/15685152-20231746,%20https:/brill.com/view/journals/bi/32/1/article-p71_004.xml)).

-- This article makes a compelling argument for how themes within a culture and narrative traditions can help us better understand the biblical texts without being one-for-one quotes or directly linked phrasings.

2.      Jutta Leonhardt-Balzer. "The Johannine Literature and Contemporary Jewish Literature." in The Oxford Handbook of Johannine Studies. Edited by Judith M. Lieu and Martinus C. de Boer. Oxford University Press, 2018.

-- The Oxford Handbook is a series of articles showing the state of Johannine studies to date. While I read and saved multiple articles from this collection, this article in particular was helpful in further reading the Fourth Gospel in light of its 2^nd^ Temple Judaism contexts.

# V - WORD COUNT

Leaving out the biblical text plus outline and final works cited, the total word count for this IWP paper is 4,819.

# VI - WORKS CITED

Adams, Paul. *Dictionary of Jesus and the Gospels (IVP Bible Dictionary)*. IVP Bible Dictionary. Downers Grove: IVP, 2016.

Darrell G. Wolfe. "INTERPRETATION OF 2 SAMUEL 7.1-17." *Introduction to Old Testament: OT500*. Pasadena, CA: Fuller Theological Seminary, 2024. https://www.academia.edu/126053128/INTERPRETATION_OF_2_SAMUEL_7_1_17.

David deSilva. *An Introduction to the New Testament: Contexts, Methods & Ministry Formation*. Second Edition. Downers Grove: InterVarsity Press, 2018.

Gregerman, Adam. *Building on the Ruins of the Temple: Apologetics and Polemics in Early Christianity and Rabbinic Judaism*. First Edition. Tübingen: Mohr Siebeck, 2016.

Janette H. Ok, Osvaldo Padilla, and Amy L. B. Peeler. *The New Testament in Color: A Multiethnic Bible Commentary*. Edited by Esau McCaulley. IVP Academic, 2024.

Jeannine K Brown. "BI131 Introducing Literary Interpretation" presented at the Logos Mobile Education, Lexham Press. Bellingham, WA, 2015.

Jipp, Joshua W. *The Messianic Theology of the New Testament*. Grand Rapids (Mich.): William. B. Eerdmans Publishing Company, 2020.

John F. Walvoord, Roy B. Zuck, and Dallas Theological Seminary, eds. *The Bible Knowledge Commentary: An Exposition of the Scriptures*. Wheaton, Ill: Victor Books, 1983.

Jutta Leonhardt-Balzer. "The Johannine Literature and Contemporary Jewish Literature." Page 0 in *The Oxford Handbook of Johannine Studies*. Edited by Judith M. Lieu and Martinus C. de Boer. Oxford University Press, 2018. https://doi.org/10.1093/oxfordhb/9780198739982.013.9, https://doi.org/10.1093/oxfordhb/9780198739982.013.9.

Matthew Thiessen. *Jesus and the Forces of Death: The Gospels' Portrayal of Ritual Impurity within First-Century Judaism*. Paperback edition. Grand Rapids, Michigan: Baker Academic, a division of Baker Publishing Group, 2021.

Michael David Coogan, Marc Zvi Brettler, and Carol Ann Newsom, eds. *The New Oxford Annotated Bible: New Revised Standard Version (NRSV); with the Apocrypha ; An Ecumenical Study Bible*. Fully revised fifth edition. Oxford New York: Oxford University Press, 2018.

Nijay K. Gupta. *A Beginner's Guide to New Testament Studies: Understanding Key Debates*. Grand Rapids: Baker Academic, 2020.

Oskar Skarsaune. *In the Shadow of the Temple: Jewish Influences on Early Christianity*. Downers Grove, Ill: InterVarsity Press, 2002.

Schiffman, Lawrence H., and Chaim Potok. *Reclaiming the Dead Sea Scrolls: The History of Judaism, the Background of Christianity, the Lost Library of Qumran*. Anchor Yale Bible Reference Library. New Haven, Conn.: Yale Univ. Pr, 1995. https://ref.ly/logosres/reclaimdss?ref=Page.p+101&off=1239.

Selvén, Sebastian. "Building on The Ruins of the Temple: Apologetics and Polemics in Early Christianity and Rabbinic Judaism." *J. Theol. Stud.* 69.1 (2018): 277--79. https://doi.org/10.1093/jts/flx230, https://research.ebsco.com/linkprocessor/plink?id=9886d0f8-4c68-389f-89c9-6687d9f28e4e.

Tat Yu Lam. "Hyper-Intertextuality: The Temple Cleansing-Rebuilding Tradition as a Compositional Framework in John's Gospel" (2023). https://doi.org/10.1163/15685152-20231746, https://brill.com/view/journals/bi/32/1/article-p71_004.xml.

Weiss, Dov. "Building on The Ruins of the Temple: Apologetics and Polemics in Early Christianity and Rabbinic Judaism." *AJS Rev.* 42.1 (2018): 219--21. https://doi.org/10.1017/s0364009418000223, https://research.ebsco.com/linkprocessor/plink?id=b244192f-4ce4-3949-ab00-e947a89d99e0.

*New Revised Standard Version, Updated Edition (NRSVue)*. Logos Bible Software. USA: Friendship Press, National Council of the Churches of Christ in the United States of America, 2021.

#### Footnotes

------------------------------------------------------------------------

[\[1\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref1) *New Revised Standard Version, Updated Edition (NRSVue)*, Logos Bible Software. (USA: Friendship Press, National Council of the Churches of Christ in the United States of America, 2021).

[\[2\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref2) Janette H. Ok, Osvaldo Padilla, and Amy L. B. Peeler, *The New Testament in Color: A Multiethnic Bible Commentary*, ed. Esau McCaulley (IVP Academic, 2024), 173; Miguel G. Echevarría, "Gospel of John,".

[\[3\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref3) David deSilva, *An Introduction to the New Testament: Contexts, Methods & Ministry Formation*, Second Edition. (Downers Grove: InterVarsity Press, 2018), 341--42.

[\[4\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref4) Paul Adams, *Dictionary of Jesus and the Gospels (IVP Bible Dictionary)*, IVP Bible Dictionary (Downers Grove: IVP, 2016), 423--24; C. S. Keener, "John, Gospel Of," 2.3.2 Judaism.

[\[5\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref5) Jutta Leonhardt-Balzer, "The Johannine Literature and Contemporary Jewish Literature," in *The Oxford Handbook of Johannine Studies*, ed. Judith M. Lieu and Martinus C. de Boer (Oxford University Press, 2018), 156, https://doi.org/10.1093/oxfordhb/9780198739982.013.9, https://doi.org/10.1093/oxfordhb/9780198739982.013.9.

[\[6\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref6) Tat Yu Lam, "Hyper-Intertextuality: The Temple Cleansing-Rebuilding Tradition as a Compositional Framework in John's Gospel" (2023), https://doi.org/10.1163/15685152-20231746, https://brill.com/view/journals/bi/32/1/article-p71_004.xml.

[\[7\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref7) Michael David Coogan, Marc Zvi Brettler, and Carol Ann Newsom, eds., *The New Oxford Annotated Bible: New Revised Standard Version (NRSV); with the Apocrypha ; An Ecumenical Study Bible*, Fully revised fifth edition. (Oxford New York: Oxford University Press, 2018), §Introduction to John.

[\[8\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref8) Michael David Coogan, Marc Zvi Brettler, and Carol Ann Newsom, *The New Oxford Annotated Bible*, n. Pointed out to me by the textual note: "2:13--25 The demonstration against corruption in the Temple (cf. Mt 21:17; Mk 11:15--19; Lk 19:45--48).".

[\[9\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref9) John F. Walvoord, Roy B. Zuck, and Dallas Theological Seminary, eds., *The Bible Knowledge Commentary: An Exposition of the Scriptures* (Wheaton, Ill: Victor Books, 1983), §Pg 279-280. Edwin A. Blum, "John," ; Section 5. JESUS' FIRST MINISTRY IN JERUSALEM (2:13--3:21).  Subsection a.      Jesus' cleansing of the temple (2:13--25).

[\[10\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref10) Jeannine K Brown, "BI131 Introducing Literary Interpretation" (presented at the Logos Mobile Education, Lexham Press, Bellingham, WA, 2015).

[\[11\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref11) David deSilva, *An Introduction to the New Testament*, 352.

[\[12\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref12) David deSilva, *An Introduction to the New Testament*, 341; "Earlier assessments of the lack of historical value to John's Gospel have given way to a more balanced assessment of the tradition behind this Gospel, but we are still struck more by the Gospel's focus on the meaning and moment of the incarnate Word than by its contributions to a "life of Jesus."".

[\[13\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref13) Nijay K. Gupta, *A Beginner's Guide to New Testament Studies: Understanding Key Debates* (Grand Rapids: Baker Academic, 2020), 33.

[\[14\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref14) Michael David Coogan, Marc Zvi Brettler, and Carol Ann Newsom, *The New Oxford Annotated Bible*, n. Michael D. Coogan, Commentary on Jn 2:14. "2:14 Animals were sold for sacrifice. Different currencies used by worshipers had to be changed to the official half-shekel of Tyre for the Temple tax (see Ex 30:11--16). Roman money was changed into Jewish money to pay the Temple tax.".

[\[15\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref15) John F. Walvoord, Roy B. Zuck, and Dallas Theological Seminary, *The Bible Knowledge Commentary*, 157--158; John D. Grassmick, "Mark,": "Though a small surcharge was permitted in these transactions, dealings were not free from extortion and fraud. In addition (according to Mark 11:16) people loaded with merchandise were taking shortcuts through this area, making it a thoroughfare from one part of the city to another. Jesus was outraged by this blatant disregard for the temple area specifically set apart for Gentile use. So He overturned the money changers' tables and the dove-sellers' benches, and would not allow people to use the area as a thoroughfare. Other certified markets were available elsewhere in the city.".

[\[16\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref16) Nijay K. Gupta, *A Beginner's Guide to New Testament Studies*, 32. See Gupta's discussion on how John lumps "the Jews" together as an internal debate among Jewish Jesus followers and non-Jesus followers, not as an epithet against the ethnicity or people.

[\[17\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref17) Matthew Thiessen, *Jesus and the Forces of Death: The Gospels' Portrayal of Ritual Impurity within First-Century Judaism*, Paperback edition. (Grand Rapids, Michigan: Baker Academic, a division of Baker Publishing Group, 2021).

[\[18\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref18) Adam Gregerman, *Building on the Ruins of the Temple: Apologetics and Polemics in Early Christianity and Rabbinic Judaism*, First Edition. (Tübingen: Mohr Siebeck, 2016), n. The case was made by Adam Gregerman in this text, but I could not obtain a copy of the text. I referenced two academic reviews to get the gist of his argument, with which I agree.; Sebastian Selvén, "Building on The Ruins of the Temple: Apologetics and Polemics in Early Christianity and Rabbinic Judaism," *J. Theol. Stud.* 69.1 (2018): 277--79, https://doi.org/10.1093/jts/flx230, https://research.ebsco.com/linkprocessor/plink?id=9886d0f8-4c68-389f-89c9-6687d9f28e4e; Dov Weiss, "Building on The Ruins of the Temple: Apologetics and Polemics in Early Christianity and Rabbinic Judaism," *AJS Rev.* 42.1 (2018): 219--21, https://doi.org/10.1017/s0364009418000223, https://research.ebsco.com/linkprocessor/plink?id=b244192f-4ce4-3949-ab00-e947a89d99e0.

[\[19\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref19) David deSilva, *An Introduction to the New Testament*, 27-62. See discussion on the synagogues.

[\[20\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref20) Michael David Coogan, Marc Zvi Brettler, and Carol Ann Newsom, *The New Oxford Annotated Bible*, n. Michael D. Coogan: Commentary on 2:19 "Destroy this temple ..., reflects a longstanding tradition of Temple critique (cf. 4:21; 2 Sam 7:5--7; see Jer 7:1--15; 35:2--10; Ezek 10:18--19; Acts 7:48).".

[\[21\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref21) Oskar Skarsaune, *In the Shadow of the Temple: Jewish Influences on Early Christianity* (Downers Grove, Ill: InterVarsity Press, 2002), 149.

[\[22\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref22) Lawrence H. Schiffman and Chaim Potok, *Reclaiming the Dead Sea Scrolls: The History of Judaism, the Background of Christianity, the Lost Library of Qumran*, Anchor Yale Bible Reference Library (New Haven, Conn.: Yale Univ. Pr, 1995), 69-81. Note: The entire discussion of pages 69-81 is summarized in my review, but the final conclusion is in the last pargraphs of page 81., https://ref.ly/logosres/reclaimdss?ref=Page.p+101&off=1239.

[\[23\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref23) Oskar Skarsaune, *In the Shadow of the Temple*, 155.

[\[24\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref24) Darrell G. Wolfe, "INTERPRETATION OF 2 SAMUEL 7.1-17," in *Introduction to Old Testament: OT500* (Pasadena, CA: Fuller Theological Seminary, 2024), https://www.academia.edu/126053128/INTERPRETATION_OF_2_SAMUEL_7_1_17.

[\[25\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref25) Schiffman and Potok, *Reclaiming the Dead Sea Scrolls*, n. See Chapter 19: The Messianic Idea.

[\[26\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref26) Joshua W. Jipp, *The Messianic Theology of the New Testament* (Grand Rapids (Mich.): William. B. Eerdmans Publishing Company, 2020), n. See also Jipps text, discussing how the ideas of Messiah in 2nd Temple Judaism played in the New Testament texts.

[\[27\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref27) *NRSVue*, v. Psalm 69:7--9.

[\[28\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/New_Testament_Introduction_NT500/IWP%20Paper/IWP_DarrellWolfe_2025.docx#_ftnref28) Janette H. Ok, Osvaldo Padilla, and Amy L. B. Peeler, *The New Testament in Color (NTIC)*, 175. Miguel G. Echevarría, "Gospel of John,".

Shalom שָׁלוֹם: Live Long and Prosper!

Darrell Wolfe

Storyteller \| Writer \| Thinker \| Consultant \| Freelancer \| Bible Nerd **Written withs some editing and research assistance from ChatGPT-4o*

\~\~\~
