---
title: 'Jesus: Human and Divine'
date: '2025-02-02T01:22:00.0040000+00:00'
draft: false
categories:
  - 'Class Discussion Posts'
  - 'Armchair Theology'
---
#### Class Discussion Question: Why did God send Jesus Christ to Earth with perfect humanity and perfect divinity?

#### **My Thoughts...**

Nowhere is the practice of diving into the biblical author's worldview more fascinating than the role of Jesus as the Human-God/God-Human.

#### **Portraits in Tanakh**

Throughout the Tankah (Hebrew Bible), the writers painted portraits of the relationship between YHWH and Israel (and humanity). All the portraits of the Tanakh tell the stories of Yahweh's attempts to co-reign with his human imagers. At core, that is the singular message of the biblical authors. **God. With. Us.** It is what Genesis 1-11 sets up as the prime narrative, and it is the undercurrent in every other narrative.

The Prologue (Gen 1-11) provides poetic symbolism of Yahweh creating a space for humanity and joining His space to humanity's space, and the separation/exile/death that came as a result of human and lesser elohim rebellions. To be separated, exiled, from Yahweh's space is to experience death. Physical death is merely the final separation from the spaces where Yahweh's domain and Earth's domains overlap. And it is the hope of the later writers that a day would come in which the living and the dead would return to this overlapping space.

But throughout the stories of Abraham, Isaac, Jacob, David, Isaiah, Daniel, Ruth, and so many others, we see portraits of Yahweh "with us" (1 Kings 8:57; 2 Chr 13:12; Isa 7:14, 8:8; Matt 1:23). Yahweh frequently made physical appearances, and sometimes there was a muddying of the invisible and visible Yahweh. But in all cases, the sense was a Yahweh who wanted to be with us. Ezekial played the role of Son of Man, who would intercede for Yahweh among his people. Isaiah say a Yahweh-empowered Israelite who would both suffer and redeem.

#### **Each portrait pulled from previous threads but added new facets.**

"A number of Jewish writers ca. 516 BC---AD 70 offered opinions as to the identity of the "second Yahweh," the second power in heaven"[\[1\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn1) Heiser worked this out in detail in his book Unseen Realm where he noted "The startling reality is that long before Jesus and the New Testament, careful readers of the Old Testament would not have been troubled by the notion of, essentially, two Yahwehs---one invisible and in heaven, the other manifest on earth in a variety of visible forms, including that of a man. In some instances the two Yahweh figures are found together in the same scene.".[\[2\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn2) He also references the earlier work of Segal on the development of this thought in Second Temple literature among the rabbis.[\[3\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn3)

Also during this period, the sages and rabbis of various movements, including the sects at Qumran, were pondering the Tanakh and other writings, and asking what Yahweh might be doing in their day or what kind of expectation they should hold. Some portraits speak of Messiah ben David, "the reigning Kind who will bring peace to the world"; while some portraits speak of Messiah ben Joseph, who is "the Suffering Servant".[\[4\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn4)

#### **Along comes Jesus**

Then came a rabbi from Nazareth, a small nothing town in the north. Rabbi Yeshua (English-Jesus / Greek - Iesus) came teaching in much the same way as his intellectual kin, the Pharisees. They did not view him as an outsider, but as an insider. They saw him as worth their time to debate (as debating each other on the finer points of Torah observance was their primary activity). Rabbi Yeshua challenged them but also respected them. Some resisted him, while other (like Nicodemus) followed The Way of Rabbi Yeshua.

Yeshua showed the ways in which these earlier portraits that promised a "God with Us" were being filled-full in his presence among them (Luke 4:21). He went on to say that even the story of Jonah was a means of referring to the larger story Yahweh was working through him (Matt 12:40, Jonah 1:17-2:1). The Dictionary of Jesus and the Gospels notes that the gospel authors emphasized the ways in which Yeshua did the works that only Yahweh could do.[\[5\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn5)

The gospel writers wrestle with showing Yeshua's language and claims in portraits. To borrow a paragraph from my own post on this thread about the "I AM" statements of Jesus equating himself with Yahweh while also referring to the Father and Himself as separate individuals:

*// The Dictionary of Jesus and the Gospels makes note of "three instances in Mark's Gospel where Jesus' pronouncement of egō eimi belongs to the narrative's gradual unfolding of his identity (Mk 6:50; 13:6; 14:62)."[**\[6\]**](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn6) John's gospel goes further by noting Jesus to say, "The Father and I are one" (John 10:30).[**\[7\]**](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn7) Paul calls Jesus "the image of the invisible God" (Col 1:10).[**\[8\]**](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftn8)//*

Yeshua makes the same statements about the Holy Spirit being a person and not just a force, and yet equally Yahweh.

#### **So what are we to do with these portraits?**

Messianic Judaism has dedicated the largest portion of their scholarship and writing interacting with what they see as errors in both Gentile Christianity and Non-Jesus-Believing modern Judaism. They have taught me to live in the tension, acknowledge the various portraits, and not feel the need to draw arbitrary lines in the sand about them.

Do we need to label these, or can we simply live in the meditative tension of them? If we must label them, "Trinity" or "God-Head" seem like they work well enough for me. But I tend not to use that verbiage, as I prefer to refer people to the portraits. We can analyze a painting, or we can simply soak it in. I think I'm in the soaking phase of my journey.

Shalom, Darrell

#### **Notes:**

------------------------------------------------------------------------

[\[1\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref1) *The Lexham Bible Dictionary - Barry, J. D., Bomar, D., Brown, D. R., Klippenstein, R., Mangum, D., Sinclair Wolcott, C., ... Widder, W. (Eds.). (2016). In The Lexham Bible Dictionary. Bellingham, WA: Lexham Press.* (Billingham, WA: Leham Press, 2016), §Michael S. Heiser, "Divine Council," SubSection "The Second Power in Heaven/Second Yahweh," LexhamPress.com.

[\[2\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref2) Heiser, *The Unseen Realm*, 134--135 \> Notes \> The startling reality is that long before Jesus and the New Testament, careful readers of the Old Testament would not have been troubled by the notion of, essentially, two Yahwehs---one invisible and in heaven, the other manifest on earth in a variety of visible forms, including that of a man. In some instances the two Yahweh figures are found together in the same scene. In this and chapter that follows, we'll see that the "Word" was just one expression of a visible Yahweh in human form.1 The concept of a Godhead in the Old Testament has many facets and layers.2 After the birth of his promised son, Isaac, Abraham's spiritual journey includes a divine figure that is integral to Israelite Godhead thinking: the Angel of Yahweh. Although the most telling passages that show this angel as a visible embodiment of the very presence of Yahweh occur later than the time of Abraham, there are early hints of his nature during the lifetimes of Abraham and his sons. 1 The Jewish community that inherited the Old Testament was well aware of this. For centuries Judaism felt no discomfort with the notion of two Yahweh figures. The idea was referred to as the "two powers in heaven" and was endorsed within Judaism until the second century AD. It is important to note that the two powers were both holy. This is not dualism, where two equal deities exist, one good, the other evil. The major work on Judaism's two-powers teaching was published originally in 1971 by the late Alan Segal. Segal was Jewish and his career focused on Second Temple and Rabbinic Judaism. His work documents how the two-powers idea became a heresy in Judaism in the second century AD. It was recently reprinted. See Alan F. Segal, Two Powers in Heaven: Early Rabbinic Reports about Christianity and Gnosticism (reprint, Waco, TX: Baylor University Press, 2012). The Old Testament roots of the two-powers doctrine were one of the major focus points of my doctoral dissertation. The logic of the two Yahweh figures in the Old Testament reflects an Israelite adaptation of the Canaanite structuring of the top tier of the Canaanite divine council. See Michael S. Heiser, "The Divine Council in Late Canonical and Non-Canonical Second Temple Jewish Literature" (PhD diss., University of Wisconsin--Madison, 2004).  2 The conception of a Godhead in orthodox Israelite thought, interpreted in the context of the wider Canaanite environment, was a focus of my dissertation. That material has been revised and put forth in an article accepted for publication at the time of this writing: Michael S. Heiser, "Co-Regency in Ancient Israel's Divine Council as the Conceptual Backdrop to Ancient Jewish Binitarian Monotheism," (forthcoming in the Bulletin for Biblical Research). I will post that article (presuming permission from BBR) on the companion website when it appears. The data and discussion go considerably beyond what appears in this book.

[\[3\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref3) Alan F. Segal, *Two Powers in Heaven: Early Rabbinic Reports about Christianity and Gnosticism*, Studies in Judaism in Late Antiquity v. 25 (Leiden: Brill, 1977).

[\[4\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref4) John B. Metzger, *Discovering the Mystery of the Unity of God: A Theological Study on the Plurality and Tri-Unity of God in the Hebrew Scriptures* (John Metzger, www.Ariel.org, 2010), 846, www.PromisesToIsrael.org,www.Ariel.org, https://www.logos.com/product/8050/discovering-the-mystery-of-the-unity-of-god.

[\[5\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref5) Adams, *Dictionary of Jesus and the Gospels (IVP Bible Dictionary)*, n. G. H. Twelftree, "Miracles and Miracle Stories,", Pg 594.

[\[6\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref6) Paul Adams, *Dictionary of Jesus and the Gospels (IVP Bible Dictionary)*, IVP Bible Dictionary (Downers Grove: IVP, 2016), §C. H. Williams, "'I Am' Sayings," Pg 396.

[\[7\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref7) *LEB*, v. John 10:30.

[\[8\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Introduction_to_Global_Christian_Traditions_SF502/Discussions_Course_.docx#_ftnref8) *LEB*, v. Col 1:10.

Shalom שָׁלוֹם: Live Long and Prosper!

Darrell Wolfe

Storyteller \| Writer \| Thinker \| Consultant \| Freelancer \| Bible Nerd **Written withs some editing and research assistance from ChatGPT-4o*
