---
title: "The God-Bearer: Ignatius, Bishop of Antioch"
date: "2025-10-13"
draft: false
categories:
  - "Biblical Studies"
  - "Church History"
  - "Patristics"
---

*Submitted in partial fulfillment of the requirements for Early Church History: CH500-45099, Professor Emily Buck Mendenhall.*

Ignatius was “the second Bishop of Antioch after Peter.”[^1] He was born 30–35 CE and died at 70 years old circa 107 CE (other dates proposed).[^2] He is one of the earliest writers preserved after the end of the New Testament writings. In this essay, we review the history, teaching themes, and controversy around Ignatius the God-Bearer.

Ignatius was a contemporary of Polycarp, who was the Bishop of Smyrna.[^3] Seven letters are attributed to Ignatius as genuine, mentioned by Eusebius.[^4] They were written just before he became a martyr and were useful for “informing our knowledge of early Christianity.”[^5]

He begins his letters with the salutation, “Ignatius [who also is Theophoros]”;[^6] he “glories in the epithet Θεοφόρος (‘God-bearer’)”[^7] or “The Bearer of God.” Vall says Ignatius was “the first to achieve a vital synthesis of Pauline, synoptic, and Johannine thought.”[^8] He also may have met Onesimus, of Paul’s letter to Philemon.[^9] Ignatius is the first patristic to use the terms “Christianity,” “catholic church,” and the adjective “apostolic.”[^10]

Ignatius’ writings were theological but not dry religiosity. He wrote with “a sense of personal devotion to Jesus Christ.”[^11] He saw God as personally involved,[^12] and viewed love as the end goal for the church’s way of life.[^13] He spoke about the importance of silence, earning him the title of “Silent Bishop,” and he believed “well-timed and temperate speech” was required for “social harmony.”[^14] He viewed humility as a shield against his critics,[^15] and choosing when to speak and when to remain silent as a method for effective communication.[^16] It was in this silence that we overcome the world’s evil and “attain unto God.”[^17]

Ignatius was concerned with unity, both within the church and between the church and its leaders. He viewed the roles of the “bishop, presbyter, and deacons” as deserving respect, and considered it shameful for that respect to be absent,[^18] as they were “an example and lesson of immortality.”[^19] In pairing shame and respect, he used the same root word, which shows a scholastic ability to use wordplays to make his point.[^20] Ignatius viewed the unity of the church as an act of love.[^21] Ignatius also repurposed the words of Jesus and Paul in his own remarks, demonstrating a keen familiarity with those writings.[^22]

For some, he was an antisemite. He said, “For if we are living until now according to Judaism, we confess that we have not received grace”;[^23] and “It is monstrous to talk of Jesus Christ and to practice Judaism.”[^24] From quotes like these, it is easy to draw the opinion that supersessionism and antisemitism were already rampant in the Gentile church. However, Cohen argues that Ignatius was focused on a form of Judaism practiced by Christian communities, not on the Jews themselves.[^25] Marshall argues that the opponents of Ignatius—angel worshipers, Gnostics, and Judaizers—are the same group.[^26] In this way, Ignatius could be seen as keeping with the tradition of Paul, who fought against Gentiles adopting Jewish practices.

Ignatius was martyred by the Romans around 107 CE. About his pending fate, he said it was “the final proof of his total dedication and faithfulness to Christ.”[^27] He was convinced that he would “rise from the dead, in him, a free man.”[^28] Ignatius set the stage for what would become the real test of the Jesus movement: What happens next? What stands out most about Ignatius is his personal writing style—not dry, but full of passion and personal spirituality. His passion for Jesus and the church shows his shepherd’s heart.

## Bibliography

Chan, Yi-Sang Patrick. “[Εντροπη: Shame and Identity Formation in the Letters of Ignatius of Antioch](https://doi.org/10.3390/rel15101258).” *Religions* 15.10 (2024): 1258.

Coakley, John W., and Andrea Sterk. *Readings in World Christian History, Vol. I: Earliest Christianity to 1453*. Orbis Books, 2004.

Cohen, Shaye J. D. “[Judaism without Circumcision and ‘Judaism’ without ‘Circumcision’ in Ignatius](https://www.jstor.org/stable/4150728).” *Harvard Theological Review* 95.4 (2002): 395–415.

Jackson, George A. *The Apostolic Fathers and the Apologists of the Second Century*. Edited by George P. Fisher. Early Christian Literature Primers. New York: D. Appleton and Company, 1879.

González, Justo L. *The Story of Christianity, Vol. 1: The Early Church to the Dawn of the Reformation*. 2nd ed. HarperOne, 2010.

Vall, Gregory. “[Chapter 5: Attaining God: The Spiritual Theology of Ignatius of Antioch](https://search.catalog.loc.gov/instances/402f58fc-6b1b-5150-8c69-88aa042371ba?option=lccn&query=2022034469).” Pages 91–108 in *Patristic Spirituality: Classical Perspectives on Ascent in the Journey to God*. Edited by Don W. Springer and Kevin M. Clarke. Leiden; Boston: Brill, 2022.

Maier, Harry O. “[The Politics of the Silent Bishop: Silence and Persuasion in Ignatius of Antioch](https://www.jstor.org/stable/23969594).” *Journal of Theological Studies* 55.2 (2004): 503–19.

Michael, Pavulraj. “[Ignatius and His Understanding of God](https://www.jstor.org/stable/24433109).” *Gregorianum* 95.1 (2014): 127–44.

Foster, Paul. “[The Ignatian Problem: The Recensions of a Letter Corpus as a Reflection of Theological Concerns and Developments](http://www.jstor.org/stable/10.2307/j.ctv1q26nrm).” In *Texts in Context: Essays on Dating and Contextualising Christian Writings from the Second and Early Third Centuries*. Edited by Joseph Verheyden, Jens Schröter, and Tobias Nicklas. Peeters Publishers, 2021.

Smit, Peter-Ben. “[On Being Consumed: The Martyred Body as a Site of Divine—Human Encounter in the Letters of Ignatius of Antioch](https://www.mdpi.com/2077-1444/11/12/637).” *Religions* 11.12 (2020): 637.

[^1]: George A. Jackson, *The Apostolic Fathers and the Apologists of the Second Century*, ed. George P. Fisher, Early Christian Literature Primers (New York: D. Appleton and Company, 1879), 67.
[^2]: Gregory Vall, “Chapter 5: Attaining God: The Spiritual Theology of Ignatius of Antioch,” in *Patristic Spirituality: Classical Perspectives on Ascent in the Journey to God*, ed. Don W. Springer and Kevin M. Clarke (Leiden; Boston: Brill, 2022), 91. Vall proposes 113, for example.
[^3]: Justo L. González, *The Story of Christianity, Vol. 1: The Early Church to the Dawn of the Reformation*, 2nd ed. (HarperOne, 2010), 57–58.
[^4]: Paul Foster, “The Ignatian Problem: The Recensions of a Letter Corpus as a Reflection of Theological Concerns and Developments,” in *Texts in Context: Essays on Dating and Contextualising Christian Writings from the Second and Early Third Centuries*, ed. Joseph Verheyden, Jens Schröter, and Tobias Nicklas (Peeters Publishers, 2021). For an extended review of the reasons for these claims, see Foster’s article.
[^5]: González, *The Story of Christianity*, 55–56.
[^6]: Jackson, *The Apostolic Fathers and the Apologists of the Second Century*, section “Ignatius of Antioch,” subsections A, B, and C, 69, 72, 74.
[^7]: Vall, “Attaining God,” 100.
[^8]: Vall, “Attaining God,” 91.
[^9]: González, *The Story of Christianity*, 56–57.
[^10]: Vall, “Attaining God,” 92.
[^11]: Vall, “Attaining God,” 92.
[^12]: Pavulraj Michael, “Ignatius and His Understanding of God,” *Gregorianum* 95.1 (2014): 141.
[^13]: Vall, “Attaining God,” 104.
[^14]: Harry O. Maier, “The Politics of the Silent Bishop: Silence and Persuasion in Ignatius of Antioch,” *Journal of Theological Studies* 55.2 (2004): 506.
[^15]: Jackson, *The Apostolic Fathers and the Apologists of the Second Century*, “The Epistle to the Ephesians” (B2), 73.
[^16]: Jackson, *The Apostolic Fathers and the Apologists of the Second Century*, “The Epistle to the Ephesians” (B2), 73.
[^17]: John W. Coakley and Andrea Sterk, *Readings in World Christian History, Vol. I: Earliest Christianity to 1453* (Orbis Books, 2004), “Ignatius of Antioch, Letter to the Magnesians,” I.2.
[^18]: Yi-Sang Patrick Chan, “Εντροπη: Shame and Identity Formation in the Letters of Ignatius of Antioch,” *Religions* 15.10 (2024): 6.
[^19]: Coakley and Sterk, *Readings in World Christian History*, “Ignatius of Antioch, Letter to the Magnesians,” VI.2.
[^20]: Chan, “Εντροπη,” 2.
[^21]: Jackson, *The Apostolic Fathers and the Apologists of the Second Century*, “The Epistle to Polycarp” (1), 69–70.
[^22]: Jackson, *The Apostolic Fathers and the Apologists of the Second Century*, “The Epistle to Polycarp” (A2), 71. This is an example of near copies of New Testament writings in Ignatius’ own writing.
[^23]: Coakley and Sterk, *Readings in World Christian History*, “Ignatius of Antioch, Letter to the Magnesians,” VII.1.
[^24]: Coakley and Sterk, *Readings in World Christian History*, “Ignatius of Antioch, Letter to the Magnesians,” X.3.
[^25]: Shaye J. D. Cohen, “Judaism without Circumcision and ‘Judaism’ without ‘Circumcision’ in Ignatius,” *Harvard Theological Review* 95.4 (2002): 398.
[^26]: Chan, “Εντροπη,” 5, and John W. Marshall, “The Objects of Ignatius’ Wrath and Jewish Angelic Mediators,” *Journal of Ecclesiastical History* 56 (2005): 1–23.
[^27]: Peter-Ben Smit, “On Being Consumed: The Martyred Body as a Site of Divine—Human Encounter in the Letters of Ignatius of Antioch,” *Religions* 11.12 (2020): 9.
[^28]: Jackson, *The Apostolic Fathers and the Apologists of the Second Century*, “The Epistle to the Romans” (C2), 75.

