---
title: 'How can I be a "Good Christian" in the 21st century?'
date: '2025-01-11T07:25:00.0020000+00:00'
draft: false
blogger_blog: 'NoHiding.Faith'
blogger_status: 'LIVE'
blogger_post_id: '5157566177452096702'
blogger_filename: '/2025/01/how-can-i-be-good-christian-in-21st.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/NoHiding.Faith/feed.atom'
categories:
  - 'Class Assignment'
  - 'Thinking Biblically'
  - 'Class Discussion Posts'
  - 'Counseling'
  - 'Bible Answer'
  - 'Q&R'
  - 'Churchianity Myths'
  - 'Pastoral'
---

<p><i>Cross posting from another conversation thread...&nbsp;</i></p><h3 style="text-align: left;">To your question, "...should it be easy to be a good Christian?" I posit a thought to add to your musing.&nbsp;</h3>
<p>I've spent the last five years studying the Ancient Near East and Second Temple Judaism contexts of the biblical authors. One of the fascinating shifts was away from a Jewish mentality of focusing on "Orthopraxy" (right practice) to a Gentile mentality of focusing on "Orthodoxy" (right belief). It is my thesis at this point in my journey that this shift fundamentally broke the Gentile western Church. From the very beginning, we took a wrong turn by doing this.</p>
<p>I find it interesting that so many of us who grew up in modern western Churchianity find ourselves asking what we need to "do" to be a "good Christian"?&nbsp;</p><p>That was the question Jewish believers were asking themselves in the first century AD. Go read the gospels and stop thinking of the Pharisees as Jesus' adversaries and instead see them as his peers (not an inter faith debate, but an intra faith debate). This was inside baseball, this was rabbi to rabbi... Jesus was recognized as a Rabbi by the Pharisees. This wasn't a Jesus against the Jewish Rabbis debate they were having, this is Jewish Rabbi Jesus saying, "This is how you be a Torah observant Jew" and the other Jewish Rabbis saying, "But what about this practice? What about what Rabbi Shammai? What about Rabbi Hillel? Why should be "Good Jews" your way?"&nbsp;</p><p>When the Gentiles first came to The Way of Rabbi Yeshua, they didn't ask what doctrines they should believe to be part of the family. They asked "what should they be required to DO?" Abstain from blood, don't eat meat.... etc."&nbsp;</p>
<p>They were asking how Gentiles can come to a Jewish sect without becoming fully Torah observant Jews. In other words, the entire New Testament exists to answer "How can I be a Good Christian?" not to answer "What Doctrines should I believe?"&nbsp;</p>
<p>It was about practice, not doctrines.</p>
<p>While I cannot do much to change anyone else's mind about that, I find myself in 2025 looking not to what churches have the right doctrinal statements, but rather, HOW they live. If a person or group claims to be a follower of Jesus, I look to see if they are</p>
<ul>
<li>feeding the hungry,</li>
<li>giving water to the thirsty,</li>
<li>welcoming and providing hospitality to the stranger/traveler/immigrant,</li>
<li>working with the Sick to bring healing or relieve pain,</li>
<li>vising those in prison.... (Matthew 25).</li>
</ul>
<p>If they're doing that kind of stuff, or stuff in that general direction... they're a "Good Christian" and if they aren't they're not (regardless of they claim to hold on their "We Believe" pages on their website).&nbsp;</p>
<p>I might get more nuanced in the future, but that's where I'm sitting with that question today.&nbsp;</p>
<p><br /></p><br />

<span style="font-family: &quot;tempus sans itc&quot;;">Shalom&nbsp;<span face="sans-serif" style="background-color: white; color: #202122; font-size: 14px;">שָׁלוֹם</span>: Live Long and Prosper!</span>
<br />

<div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe</span>
</div>

Storyteller | Writer | Thinker | Consultant | Freelancer | Bible Nerd
<i>*Written withs some editing and research assistance from ChatGPT-4o</i>
<br /><br /><br />

