---
title: 'Authoritarian Pastor, a case study in spiritual abuse and un-Christlike authority claims by Pentecostal circles.'
date: '2025-03-31T21:02:00.0030000+00:00'
draft: false
categories:
  - 'Class Assignment'
  - 'Leadership'
  - 'Church Hurt & Trauma'
  - 'Churchianity Myths'
  - 'Armchair Theology'
  - 'Pastoral'
---
** This paper began as an assignment for a class but took on a deeper meaning for me as I processed a deeply traumatic experience and exit from a church. It wasn't the only traumatic exit from a church to that point, nor was it the last, several would come after. But due to my emotional vulnerability in 2003-2005, this incident had the longest and deepest impact on me. This church experience because one of many reasons I left Churchianity as a whole, though I sometimes visit new buildings hoping to find something more genuine. If I ever join or start a church or parachurch organization, this type of authoritarian abuse of power will be in the back of my mind as we plan to build systems and cultures to ensure we avoid it. Without further ado\...*** **

FINAL PAPER: CASE STUDY

Authoritarian Pastor

**by Darrell Wolfe**

**Submitted in partial fulfillment of the requirements**

**for the course Foundations of Psychological Science: On Being Human: PF501**

**Winter 2025**

**Professors Amy Drennan, Kutter Callaway**

**Tuesday, March 18, 2025**

# CASE STUDY

I was the son of an alcoholic pastor who later became an atheist crack-addict psychologist. While he was emotionally absent, he was never authoritarian. His style was far more laissez-faire, when not uninvolved entirely. I was 19 years old in 1999 when my father left the house to follow his addiction to the streets. Simultaneously, I grew up within a Cessationist tradition while I myself had profound spiritual experiences which that tradition gave no framework to understand. This led me to wonder if anyone else had experiences similar to those of the Prophets and Apostles. My father's pastor-atheist transition and my own experiences compared to my tradition of origin, gave me cognitive dissonance. In the following years, I set out to various churches and Christian traditions looking for *something*, but I couldn't quite verbalize what it was at the time. I would now call it 'Truth' that I was seeking; something and/or someone true, which led me to the Pentecostals. When I was 23 years old (2003), I joined a Pentecostal church in Palm Desert, CA. Pastor Joe (not his real name) was a charismatic man, a lifelong musician, and the 'spiritual son' of Pastor Rod Parsley of Ohio fame.

The incident described in this case study occurred around 2005. It was both a single incident, but also the type of thing he said often. But this one moment, toward the end of my time there, stood out to me as one of the reasons I decided to leave that ministry. I would later learn to call the feeling that it left me a 'boundary violation'.[\[1\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn1) On this occasion, Pastor Joe was literally preaching to the choir, at a choir and band rehearsal. He had recently asked someone (me, maybe, I can't recall) to assist with some volunteer activity, and they responded with 'I'll pray about it', to which he gave the following response:

*"If I come to you and tell you God told me to have you do something, you don't respond with 'I'll pray about that pastor'. I'm your Man of God. I'm the prophet God called you to submit to. I already prayed. I got the word from the mountain. You don't need to pray about it, you need to do it."*

It was often like this, the entire structure of the environment was built around the idea that the pastor of any church should be considered a Prophetic voice, an Elijah or Elisha or Moses. We should respond as the Israelites should have responded to those voices. On this occasion, I remember feeling violated, offended, and ready to fight. "Who does this guy think he is..." probably came out of my mouth when my wife and I both got home. Pastor Joe had a hard time keeping any volunteers, and those who stayed for any length of time were more like abuse victims than willing participants. Eventually, even his elders left (with much eye rolling when we would happen to mention our days in his ministry, and it was "his" ministry, not ours, and not God's). In my search for answers, I ended up with several more ministries just like this one, all different flavors and styles, but the same root error "the Man of God has the answers, do what he says, don't question."

# PSYCHOLOGICAL CONSTRUCTS

## Bowen Family Systems Theory (BSFT)

Using a Bowen Family Systems Theory (BSFT) approach gives us some tools to discuss the scenario. Creech uses BSFT to analyze congregational life noting, "When human beings work or live together, an emotional system forms. This means that we unconsciously monitor those around us and automatically react or respond without thinking, as anxiety makes its way around the system."[\[2\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn2) As humans develop in their family of origin, we fall into familiar patterns. Creech's use of BFST attempts to take the patterns common to many families and reimagine how those roles and patterns play out in larger post-family environments (churches, parachurches, organizations, and workplaces). He notes that "everyone has a part to play in this drama" and we often act out these roles "below the level of awareness," which means it takes care to recognize and address the patterns.[\[3\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn3) When anxiety is high, the "system pulls its members into a common center to conform to common thinking, to agree to common practices, to speak a common language, even if that means compromising principles or values espoused by individuals. This pressure can be unbearably strong at times."[\[4\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn4) For the purposes of this Case Study, I would like to review two components of the BFST as presented by Creech, The Scale of Differentiation and the Family Emotional Process.

## The Scale of Differentiation

Differentiation describes a person's ability to maintain a separate sense of self while remaining connected to others within the system. An undifferentiated individual or system can fall into extremes on either side of a continuum (either disconnected entirely, or, overly connected and enmeshed). Differentiation, then, is the balance between separation and connection. Creech said that when systems become agitated through anxiety the system (and leaders within the system) tend to respond on a scale between *undifferentiated*, "fused with others and more reactive to their environment and to people around them" to *differentiated* "capacity for a person to balance emotion and intellect."[\[5\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn5) Speaking of the ability to differentiate, Balswick, King, and Reimer call an undifferentiated person or group "enmeshed" having "fusion between persons" where individuals have "given over their identity to the group."[\[6\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn6) Specifically, they note that "Less extreme forms of congregational enmeshment can be seen in high-demand or abusive congregations, where blind obedience is given to a leader by followers."[\[7\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn7) They also note that "there is little interdependence in the enmeshed church since all members are dependent on the leader. A constant barrage of authoritarian commands and demands maintains dependence."[\[8\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn8) In contrast, they say that a differentiated church body has their primary identity rooted not in the leader but in Jesus, and that each member retains their full autonomy while living "by a mutual reinforcing and supporting of each other" and that "healthy differentiation is characterized by members experiencing unity in their connectedness with the congregation and their separation from the congregation as a whole."[\[9\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn9)

In the Case Study scenario, Pastor Joe provided an enmeshed undifferentiated culture. Rather than autonomous humans with their own right to hear and respond to God, they were to become extensions of Joe's will. This system not only fails to honor the individual's relationship with God, but it fails to train the individual to hear and respond to God on their own, making them dependent upon the pastor rather than on God. In the concept of a "Maturity Continuum" one moves from "Dependence, to Independence, to Interdependence."[\[10\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn10) In this case, Pastor Joe was encouraging regression to dependence rather than progression to a fully interdependent, mutually submitted, model.

## Family Emotional Process (aka -- System Anxiety Response)

Family systems have a group dynamic when responding to stress or anxiety. "Our repertoire is small: we fight, we flee, we overfunction or underfunction, or we engage emotional triangles."[\[11\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn11) Modern psychology sometimes refers to this as the "Fight, Flight, Freeze, or Fawn" response.[\[12\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn12) This is related to the sympathetic nervous system (SNS) and the autonomic nervous system (ANS), which one study shows to have physiological responses to social stress.[\[13\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn13) Drawing from BFST, Shitama says that "an effective leader is a non-anxious presence," which he contrasts to a "non-anxious, non-presence" (someone who is disconnected, like my father was) and also to an "anxious presence" which is "someone who can't help but let \[his/or\] her anxiety spew into the system" (like Pastor Joe was doing).[\[14\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn14)

In this Case Study, Pastor Joe self-selected his people through intimidation behaviors. If Fight or Flight is activated, these members will self-select and exclude themselves from the group. Freeze may cause inaction temporarily, but this Case Study is not just a one-time event but rather a culture; that culture is one of intimidation. Thus, it is more likely to result in Fight, Flight, or Fawn. In the case of Fawn, the pastor's ideal response for those who stay, the fawner is "immediately acting to try to please to avoid any conflict."[\[15\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn15) Rather than being a non-anxious presence, he increased the anxiety of the group to force a SNS/ANS response to either remove non-compliant participants or ensure the compliance of those who remain. This system-anxiety was crucial to achieve compliance among the members who stayed within the system.

## Multigenerational Transmission Process

It might also be interesting to note that the Multigenerational Transmission Process tells us how the culture is passed down and perpetuates long after the original group is gone. As new members enter a family or organization, they enter a culture that is already established. From the elder members, the newbies learn and grow into the culture and then pass it down to other newcomers behind them. As there are multiple generations of participants at different stages of this progression, the culture is perpetuated long past the time the original participants are dead and gone. Creech called this transmission process a "rotating door of people entering and leaving the system."[\[16\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn16) Studying the history of the Pentecostal and Charismatic movements, and their origins with Charles Fox Parham, gave me a new understanding of just how long this culture of giving the pastoral leader far too much authority may have been developing (at least since 1901), predating Pastor Joe specifically.[\[17\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn17)

# THEOLOGICAL CONSTRUCTS

It seems a major key theological issue here is one of authority. It is a misuse of authority to think of oneself as the very essence of God's authority over another human being. Even Moses, for all his unique displays of God's authority among the Israelites, is portrayed by the biblical authors as afraid to handle that kind of authority too loosely.[\[18\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn18) Moses was not a perfect leader and his example shows us that one should be cautious speaking and acting for God too hastily.[\[19\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn19) While Moses hesitated to accept the mantle of authority, Pastor Joe claimed it outright.

Further, Moses (whether a literary or literal character) had a context, a specific context of a people leaving physical slavery and entering a wilderness to be tested before entering a promised land. While we can see loose analogies between this story and our own sense of calling in the modern era, taking the story and concept of divine authority too literally, at the level this pastor did, at the level the Pentecostal movement often does, is a sign of poor Bible reading, in addition to poor shepherding.

Throughout the Tanakh, we see recurring themes. In Genesis, we see the garden of God had two trees. In US-American Churchianity, we often speak of 'sin' in terms of doing 'good' or doing 'bad'. But as Bob Hamp notes a few times in his Foundations of Freedom lectures, the Knowledge of Good and the Knowledge of Bad comes from the same tree.[\[20\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn20) We try to get people to overcome the knowledge of bad by a better doing of the knowledge of good, and this fails because it comes from the same tree. Pastor Joe's misuse and abuse of scriptural narratives to paint his own authority as stronger than is warranted, reminds me of this misuse of knowledge. We also see that Genesis 4-12 reflect how poorly things go when humankind builds empires for themselves. Throughout the Tanakh, Egypt, Babylon and even Jerusalem are rebuked for the tendencies of empire. In my view, Pastor Joe was building his own kingdom, his own empire, rather than Gods. Thus, when a leader seeks to dominate and control, they are employing the tools of Empire not the tools of Yahwehism.

Jesus said that whoever wants to become the greatest would become servant of all.[\[21\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn21) We call these 'servant leaders' in modern leadership vernacular. As Jesus so often laid his needs aside for the people, as Paul so often put himself in danger for people, 'leaders' in The Way of Yeshua are servants first. They do not build for themselves a kingdom, but they build it for God. This reminds me of David, who having set out first to build a house for Yahweh, then received a house for himself.[\[22\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn22) This reversal was made possible because David did not seek to build his own kingdom, but Yahweh's. Too often, we look to build for ourselves a kingdom. This is the error of many pastors, and a root issue at the heart of Pastor Joe's abuse of authority.

# WHAT COULD BE DIFFERENT...?

Strawn and Brown noted that "No one is Christian (or "spiritual") entirely on their own. Rather, it is the body of Christ (your church, hopefully) that establishes, nourishes, and enhances Christian life."[\[23\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn23) They noted that when we co-regulate together, we extend our capacity.[\[24\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn24) Creech said the same by comparing group-anxiety to the contents of a cup, "An eight-ounce cup can contain only eight ounces of coffee before it spills over the edge. A sixteen-ounce cup can easily handle several ounces more without a mess. Systems with more emotionally mature members (capacity) can manage more anxiety (content) before producing a symptom."[\[25\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn25) So if we can develop a healthier system, then it can withstand individual differences and even failures more readily.

            If I was in that church today, what might I do differently? Unfortunately, I do not believe I could do anything other than to leave earlier. In my decades since, I've come across this same leader in churches, workplaces, and organizations. The name and face changes, the root-issues do not. I find myself working for someone similar today. Though the specific issues and attitudes are slightly different, the same root error, "I am building my own kingdom" is at the heart of it. I have found that leaders like this are rarely capable of listening or accepting correction, especially from someone "under" them. The solution is usually to leave or replace the leader. In my current role, my predecessors attempted to replace the leader and failed, which is why I have my resume floating today.

            What could we do at a systemic level? Cultural changes often happen because ideas spread. The books, media, phrases, and sayings of a group make up their culture. Apple, Nike, Audi, Subaru, Stetson and other brands develop a following of similarly minded people by striking a conversation around a set of ideas and cultural narratives. Seth Goden says that one of the internalized messages people take away from being involved in these brands is "people like us do things like this."[\[26\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn26) As schools, pastors, leaders, and organizations begin the process of saying "Followers of Jesus do things like this..." it sets the tone for the rest. Stragglers may take a while to catch up, but if enough of us refuse to accept the old paradigms, and set new examples to follow, we can begin to shift the narrative and thus the culture.

McBride observed that "Oppression happens to the body... through the interpersonal lived experiences\..."[\[27\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn27) In her text, she spoke of individual physical bodies. But I think the truth she observed extends to the corporate body in both directions. If we (as an organization) embody abuse through lived experiences, we perpetuate it. If we (as an organization, or interconnected group of organizations) re-embody healthier expressions, we perpetuate those. Pastor Joe was living the model he learned from his 'spiritual father', what if he had learned a healthier model? Some pastors of larger organizations have noticed, and they are turning the tide.[\[28\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftn28) As we all do our part to make our respective spheres of influence healthier, we can shift the larger cultural narrative. When enough of us catch up, it hits a tipping point. Most people no longer believe the earth revolves around the sun (it should be zero).

Societies reach tipping points. When enough of us shift the narrative, the tipping point spills into most other groups. This is why there are more churches today with guitars, drums, and soundboard technicians (things my pastor-father fought for in the 1980-90s), than there are organs and hymnals. Culture reached a tipping point on the presentation of music, and people followed the shift. It starts with those of us who see the problem, it is our responsibility to shift the narrative.

The solution is a healthier culture through leaders who have bought into the new paradigms and who cultivate that healthier perspective throughout the systems within their circle(s) of influence. We could also set up a series of checks and balances, looking for red and green flags of healthy culture, always monitoring for abuses and adjusting the measures as cultures shift. In my case, I had very little power in the system. I would like to have sat down with him and found a way to describe the problem and give Pastor Joe an opportunity to join me in fixing it. I suspect that he would decline the opportunity, and I would still have had to move on. But at least I could have said I'd tried. In the future, however, I can enter new (imperfect) systems looking for the green flags that they are attempting to cultivate an emotionally and mentally healthy/safe community. In those spaces, I imagine anything I observe might be safe to bring forward. Ultimately, I wonder if I am called to start such a community myself. I do not see that as a possibility in this season of life, but maybe in the future the winds of opportunity may blow my way, and maybe a group of us can start something in our area, an idea worth spreading.

# WORKS CITED OR REFERENCED

Brown, Warren, and Brad Strawn. *Enhancing Christian Life: How Extended Cognition Augments Religious Community*. Downers Grove, IL: IVP Academic, 2020.

Cloud, Henry, and John Sims Townsend. *Boundaries: When to Say Yes, How to Say No to Take Control of Your Life*. Updated and Expanded \[edition\]. Boundaries. Grand Rapids, Michigan: Zondervan, 2017.

Creech, Robert. *Family Systems and Congregational Life: A Map for Ministry*. Grand Rapids: Baker Academic, 2019. https://ebookcentral.proquest.com/lib/fuller/detail.action?docID=5660416.

Darrell G. Wolfe. "INTERPRETATION OF 2 SAMUEL 7.1-17." *Introduction to Old Testament: OT500*. Pasadena, CA: Fuller Theological Seminary, 2024. https://www.academia.edu/126053128/INTERPRETATION_OF_2_SAMUEL_7_1_17.

Jack O. Balswick, Kevin S. Reimer, and Pamela E. King. *The Reciprocating Self: Human Development in Theological Perspective*. Second Edition. Downers Grove: IVP Academic, An Imprint of InterVarsity Press, 2016. https://ebookcentral.proquest.com/lib/fuller/detail.action?docID=4622971.

McBride, Hillary L. *The Wisdom of Your Body: Finding Healing, Wholeness, and Connection through Embodied Living*. Grand Rapids, Michigan: Brazos Press, a division of Baker Publishing Group, 2021.

Olivia Guy-Evans. "Fight, Flight, Freeze, or Fawn: How We Respond to Threats." Scholarly Blog. *Simply Psychology*, 9 November 2023. https://www.simplypsychology.org/fight-flight-freeze-fawn.html.

Ryken, Philip Graham, and R. Kent Hughes. *Exodus: Saved for God's Glory*. Preaching the Word. Wheaton: Crossway Books, 2005.

Scazzero, Peter. *Emotionally Healthy Spirituality: It's Impossible to Be Spiritually Mature, While Remaining Emotionally Immature*. Zondervan, 2014. https://www.amazon.com/Emotionally-Healthy-Spirituality-Impossible-Spiritually/dp/B08SHX5632/ref=sr_1_6?crid=30T0P57ZF972Q&keywords=The+Emotionally+Healthy+church&qid=1643520881&s=books&sprefix=the+emotionally+healthy+churc%2Cstripbooks%2C221&sr=1-6.

---------. *The Emotionally Healthy Church, Updated and Expanded Edition: A Strategy for Discipleship That Actually Changes Lives*. Zondervan, 2015. https://www.amazon.com/Emotionally-Healthy-Spirituality-Impossible-Spiritually/dp/B08SHX5632/ref=sr_1_6?crid=30T0P57ZF972Q&keywords=The+Emotionally+Healthy+church&qid=1643520881&s=books&sprefix=the+emotionally+healthy+churc%2Cstripbooks%2C221&sr=1-6.

---------. *The Emotionally Healthy Leader: How Transforming Your Inner Life Will Deeply Transform Your Church, Team, and the World*. Zondervan, 2015. https://www.amazon.com/Emotionally-Healthy-Leader-Transforming-Transform/dp/0310525365/ref=tmm_pap_swatch_0?\_encoding=UTF8&qid=&sr=.

Seth Godin. "How to Get Your Ideas to Spread" presented at the Nordic Business Forum, 10 March 2020. https://www.youtube.com/watch?v=04pdq5IppL8.

Shitama, Jack. *Anxious Church, Anxious People: How to Lead Change in an Age of Anxiety*. Earleville, Maryland: Claris Works Inc, 2018. https://fuller.on.worldcat.org/oclc/1085365353.

Sinusoid, Darya. "7 Habits: Dependence, Independence, Interdependence." *Shortform Books*, 9 December 2021. https://www.shortform.com/blog/dependence-independence-interdependence-7-habits/.

Vinson Synan. *The Holiness-Pentecostal Tradition: Charismatic Movements in the Twentieth Century*. 2nd ed. Grand Rapids, MI; Cambridge, U.K.: William B. Eerdmans Publishing Company, 1971. https://www.logos.com/product/37509/the-holiness-pentecostal-tradition-charismatic-movements-in-the-twentieth-century.

Weissman, David G., and Wendy Berry Mendes. "Correlation of Sympathetic and Parasympathetic Nervous System Activity during Rest and Acute Stress Tasks." *Int. J. Psychophysiol. Off. J. Int. Organ. Psychophysiol.* 162 (2021): 60--68. https://doi.org/10.1016/j.ijpsycho.2021.01.015, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7987796/.

*Foundations of Freedom Classes*. Gateway Church, Southlake Texas: Freedom Ministries, 2011. https://www.youtube.com/playlist?list=PL3F52B8EC7E050087.

*The Lexham English Bible (LEB), Fourth Edition*. Logo Bible Software. Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.). Bellingham, WA: Lexham Press, 2010. http://www.lexhampress.com.

## END NOTES

------------------------------------------------------------------------

[\[1\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref1) Henry Cloud and John Sims Townsend, *Boundaries: When to Say Yes, How to Say No to Take Control of Your Life*, Updated and expanded \[edition\]., Boundaries (Grand Rapids, Michigan: Zondervan, 2017), n. Townsend and Cloud became a major part of my early recovery from spiritual abuse.

[\[2\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref2) Robert Creech, *Family Systems and Congregational Life: A Map for Ministry* (Grand Rapids: Baker Academic, 2019), 15, https://ebookcentral.proquest.com/lib/fuller/detail.action?docID=5660416.

[\[3\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref3) Creech, *Family Systems and Congregational Life: A Map for Ministry*, 16.

[\[4\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref4) Creech, *Family Systems and Congregational Life: A Map for Ministry*, 16.

[\[5\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref5) Creech, *Family Systems and Congregational Life: A Map for Ministry*, 20.

[\[6\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref6) Jack O. Balswick, Kevin S. Reimer, and Pamela E. King, *The Reciprocating Self: Human Development in Theological Perspective*, Second Edition. (Downers Grove: IVP Academic, An Imprint of InterVarsity Press, 2016), 342, https://ebookcentral.proquest.com/lib/fuller/detail.action?docID=4622971.

[\[7\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref7) Jack O. Balswick, Kevin S. Reimer, and Pamela E. King, *The Reciprocating Self: Human Development in Theological Perspective*, 342.

[\[8\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref8) Jack O. Balswick, Kevin S. Reimer, and Pamela E. King, *The Reciprocating Self: Human Development in Theological Perspective*, 342--43.

[\[9\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref9) Jack O. Balswick, Kevin S. Reimer, and Pamela E. King, *The Reciprocating Self: Human Development in Theological Perspective*, 343.

[\[10\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref10) Darya Sinusoid, "7 Habits: Dependence, Independence, Interdependence," *Shortform Books*, 9 December 2021, https://www.shortform.com/blog/dependence-independence-interdependence-7-habits/.

[\[11\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref11) Creech, *Family Systems and Congregational Life: A Map for Ministry*, 21.

[\[12\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref12) Olivia Guy-Evans, "Fight, Flight, Freeze, or Fawn: How We Respond to Threats," Scholarly Blog, *Simply Psychology*, 9 November 2023, https://www.simplypsychology.org/fight-flight-freeze-fawn.html.

[\[13\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref13) David G. Weissman and Wendy Berry Mendes, "Correlation of Sympathetic and Parasympathetic Nervous System Activity during Rest and Acute Stress Tasks," *Int. J. Psychophysiol. Off. J. Int. Organ. Psychophysiol.* 162 (2021): 60--68, https://doi.org/10.1016/j.ijpsycho.2021.01.015, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7987796/.

[\[14\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref14) Jack Shitama, *Anxious Church, Anxious People: How to Lead Change in an Age of Anxiety* (Earleville, Maryland: Claris Works Inc, 2018), 12, https://fuller.on.worldcat.org/oclc/1085365353.

[\[15\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref15) Olivia Guy-Evans, "Fight, Flight, Freeze, or Fawn."

[\[16\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref16) Creech, *Family Systems and Congregational Life: A Map for Ministry*, 23.

[\[17\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref17) Vinson Synan, *The Holiness-Pentecostal Tradition: Charismatic Movements in the Twentieth Century*, 2nd ed. (Grand Rapids, MI; Cambridge, U.K.: William B. Eerdmans Publishing Company, 1971), §Kindle Locations 948-949, https://www.logos.com/product/37509/the-holiness-pentecostal-tradition-charismatic-movements-in-the-twentieth-century.

[\[18\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref18) Philip Graham Ryken and R. Kent Hughes, *Exodus: Saved for God's Glory*, Preaching the Word (Wheaton: Crossway Books, 2005), 122-"By God's authority and with God's assistance---symbolized by the mighty staff---he went back to Egypt to rescue the children of Israel. Moses proved to be a great leader, of course, but his reluctance to answer God's call is a reminder that there is only one perfect Savior. God promised that one day he would send his people a prophet "like Moses."".

[\[19\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref19) *The Lexham English Bible (LEB), Fourth Edition*, Logo Bible Software., Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., & Wierenga, M. (Eds.) (Bellingham, WA: Lexham Press, 2010), v. Numbers 20:1-13, Note: Moses got results from God, like Pastor Bob got real results, but that didn't make his actions godly., http://www.lexhampress.com.

[\[20\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref20) *Foundations of Freedom Classes* (Gateway Church, Southlake Texas: Freedom Ministries, 2011), https://www.youtube.com/playlist?list=PL3F52B8EC7E050087.

[\[21\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref21) *LEB*, v. Matthew 20:26--28.

[\[22\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref22) Darrell G. Wolfe, "INTERPRETATION OF 2 SAMUEL 7.1-17," in *Introduction to Old Testament: OT500* (Pasadena, CA: Fuller Theological Seminary, 2024), https://www.academia.edu/126053128/INTERPRETATION_OF_2_SAMUEL_7_1_17.

[\[23\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref23) Warren Brown and Brad Strawn, *Enhancing Christian Life: How Extended Cognition Augments Religious Community* (Downers Grove, IL: IVP Academic, 2020), 12.

[\[24\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref24) Brown and Strawn, *Enhancing Christian Life: How Extended Cognition Augments Religious Community*, 18.

[\[25\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref25) Creech, *Family Systems and Congregational Life: A Map for Ministry*, 18--19.

[\[26\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref26) Seth Godin, "How to Get Your Ideas to Spread," 10 March 2020, sc.See timestamp 43:56, https://www.youtube.com/watch?v=04pdq5IppL8.

[\[27\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref27) Hillary L. McBride, *The Wisdom of Your Body: Finding Healing, Wholeness, and Connection through Embodied Living* (Grand Rapids, Michigan: Brazos Press, a division of Baker Publishing Group, 2021), 159.

[\[28\]](https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/z.Foundations_of_PsychologicalSense_PF501/FinalPaper_CaseStudy_DarrellWolfe_vFinal.docx#_ftnref28) Peter Scazzero, *Emotionally Healthy Spirituality: It's Impossible to Be Spiritually Mature, While Remaining Emotionally Immature* (Zondervan, 2014), https://www.amazon.com/Emotionally-Healthy-Spirituality-Impossible-Spiritually/dp/B08SHX5632/ref=sr_1_6?crid=30T0P57ZF972Q&keywords=The+Emotionally+Healthy+church&qid=1643520881&s=books&sprefix=the+emotionally+healthy+churc%2Cstripbooks%2C221&sr=1-6; Peter Scazzero, *The Emotionally Healthy Church, Updated and Expanded Edition: A Strategy for Discipleship That Actually Changes Lives* (Zondervan, 2015), https://www.amazon.com/Emotionally-Healthy-Spirituality-Impossible-Spiritually/dp/B08SHX5632/ref=sr_1_6?crid=30T0P57ZF972Q&keywords=The+Emotionally+Healthy+church&qid=1643520881&s=books&sprefix=the+emotionally+healthy+churc%2Cstripbooks%2C221&sr=1-6; Peter Scazzero, *The Emotionally Healthy Leader: How Transforming Your Inner Life Will Deeply Transform Your Church, Team, and the World* (Zondervan, 2015), https://www.amazon.com/Emotionally-Healthy-Leader-Transforming-Transform/dp/0310525365/ref=tmm_pap_swatch_0?\_encoding=UTF8&qid=&sr=.

Shalom שָׁלוֹם: Live Long and Prosper!

Darrell Wolfe

Storyteller \| Writer \| Thinker \| Consultant \| Freelancer \| Bible Nerd **Written withs some editing and research assistance from ChatGPT-4o*
