---
title: 'A New Testament Introduction Final Test (Student Project) Part 1 The Test'
date: '2025-06-07T07:09:00.0090000+00:00'
draft: false
blogger_blog: 'NoHiding.Faith'
blogger_status: 'LIVE'
blogger_post_id: '6965951739896706522'
blogger_filename: '/2025/06/a-new-testament-introduction-final-test.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/NoHiding.Faith/feed.atom'
categories:
  - 'Class Assignment'
  - 'Seminary Course Work'
  - 'Thinking Biblically'
---

<h1>New Testament Introduction (NT500)<o:p></o:p></h1>

<p class="MsoNormal"><i>The following questions will test the students’
understanding of the key components of the course materials broken out into
three sections. The questions will include Multiple Choice (10), True/False
(10), and Short-Essay (5). This is an open book test, please have your primary
texts and a copy of the NRSVue or CEB translations available.<o:p></o:p></i></p><p class="MsoNormal"><i>For the Answer Key:&nbsp;</i><a href="https://www.nohiding.faith/2025/06/a-new-testament-introduction-final-test_7.html" target="_blank">A New Testament Introduction Final Test (Student Project) Part 2 The Answer Key ~ NoHiding.Faith</a></p>

<h2>Part I: Lectures<o:p></o:p></h2>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->1.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The term ‘Hellenism’ finds
its roots in the conquests of which ancient conqueror:<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Caesar Augustus<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Alexander the Great<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Socrates the Wise<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Hellen of Troy<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->2.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Explain what Hellenism was,
and why it is crucial for understanding the New Covenant (NT) texts:<o:p></o:p></p>

<p class="MsoNormal">Essay Answer: <o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->3.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The New Covenant writers use
descriptions of Jesus that echo those of Emperor Augustus on the Priene
Calendar Inscription.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>True<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->4.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>While dissenting opinions
exist, most scholars agree that this gospel was produced first:<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Matthew<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Mark<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Luke<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>John<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->5.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>If it were not for this
gospel, there would be no written record to indicate that Jesus’s ministry
lasted more than one year:<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Matthew<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Mark<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Luke<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>John<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->6.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Describe Intercalations
(Markan Sandwiches) in the gospel of Mark:<o:p></o:p></p>

<p class="MsoNormal">Essay Answer:<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->7.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Other than the letters
attributed to Paul (Rabbi Sha’ul), what other sources give us a portrait of his
life? <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The works of Josephus<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The works of Philo of
Alexandria<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The work of Luke-Acts<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The book of Hebrews<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->8.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>According to the writings
of Paul (Rabbi Sha’ul), what are the themes and driving concerns of the 1<sup>st</sup>
century Jesus communities?<o:p></o:p></p>

<p class="MsoNormal">Essay Answer:<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->9.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Paul’s gospel is a story of
salvation for the human race in continuity with Israel’s Scriptures and in
contrast to the gospel of Rome. It was inherently both religious and political.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>True<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->10.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>Regarding the book of Hebrews, which statement below is false:<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Hebrews’ Author is
anonymous, and various authors have been suggested.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Hebrews’ Audience is anonymous,
but the letter reads as if there is a familial closeness.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Hebrews is a traditional
epistle with a clear opening and closing, following the format of Paul’s other
letters.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Hebrews is an often-overlooked
key to concepts around the fatherhood of God. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->11.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The term Apocalypse (apokalupsis) in second temple Judaism
literature literally translates to:<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>End Times Prophecy<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Uncovering/Unveiling/Disclosing<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Pending Disaster<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The Concealer / One who
hides<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->12.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>An Apocalypse (apokalupsis) in second temple Judaism literature
is most commonly used to tell what kind of story:<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Anticipation that the world
will end suddenly because of something catastrophic and unexpected.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Anticipation that the world
will end because of the mess human beings have made of the earth.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Anticipation that things are
working toward a dystopian world in which evil reigns and good is extinguished.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Anticipation that things
are being revealed for what they actually are; and that the world and
everything in it will be made right.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->13.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The two-part work of Luke-Acts is known in the world of biblical
scholarship as a:<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Diptych<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Diphthong<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Dysentery<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>Dysphoria<o:p></o:p></p>

<h2>Part II: NT Texts<o:p></o:p></h2>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->14.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>Matthew begins his gospel with several series of 14-step lineages.
How many sets of 14 does Matthew use?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>2<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>3<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>4<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>5<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->15.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>Hebrews 11 is often called the ‘Hall of Faith’ which promises
that nobody who follows Yahweh/Yeshua ever dies without having received all the
promises they were owed beforehand.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>True<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->16.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The book of Jude directly quotes from what other text within second
temple Judaism, which was not later accepted into the final canon of
‘scripture’.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The Wisdom of Solomon<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>The Maccabees<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->c.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>1 Esdras<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->d.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>1 Enoch<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->17.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>Paul’s letter to the Romans has a recurring theme exploring Jews
and Greeks (Gentiles). How could that theme inform one’s reading of Romans?
Give at least two examples.<o:p></o:p></p>

<p class="MsoNormal">Essay Answer:<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoListParagraph" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->18.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The gospel of John begins by identifying Jesus as “The Lamb of
God” (Ch 1), then shows Jesus as The Good Shepherd (Ch 10), then ends with
Jesus asking Peter to “feed my lambs” (Ch 21). How could reading the gospel
with these hinge-points in mind inform your reading of the text of John?<o:p></o:p></p>

<p class="MsoNormal">Essay Answer:<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<h2>Part III: Secondary Readings<o:p></o:p></h2>

<p class="MsoNormal"><i>BGNTS: Gupta, Nijay K. A Beginner’s Guide to New
Testament Studies: Understanding Key Debates. Grand Rapids, MI: Baker Academic:
A Division of Baker Publishing Group, 2020.<o:p></o:p></i></p>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->19.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>How did the New Testament authors read and/or understand their
Old Testament (Hebrew Bible)? There are two common views in biblical scholarship,
in context or out of context, briefly explain which view is most compelling and
why? <o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.25in; mso-add-space: auto;"><i>*Refresh
your understanding in Chapter 12: The Old and New Testament.<o:p></o:p></i></p>

<p class="MsoNormal">Essay Answer:<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->20.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>Some scholars see Paul’s writing as Apocalyptic, which means
that Paul’s gospel is not a continuation of the on-going story of
salvation-history but a line of demarcation into an entirely new age (Ch 5).<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>True<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->21.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>There are two views in scholarship on ‘Women in Leadership’,
they are referred to officially in the BGNTS as the heretical leadership and
egalitarian leadership models.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>True<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoNormal"><i>NTIC: McCaulley, Esau, Amy Peeler, Janette H. Ok, and
Osvaldo Padilla, eds. The New Testament in Color: A Multiethnic Bible
Commentary. Downers Grove, IL: IVP Academic: An Imprint of InterVarsity Press,
2024.<o:p></o:p></i></p>

<p class="MsoListParagraphCxSpFirst" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->22.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The Turtle Island Biblical Interpretation recognizes that the Indigenous
Peoples of what is now North America had a relationship with Creator long
before the colonizers showed up with bibles and diseases. For these tribes,
their native mythologies, histories, creation stories and cultural practices
are an “Old Testament” to them even as The Hebrew Bible (Torah, Tanakh, and
Second Temple Judaism) are an ‘Old Testament’ for many first century Jewish
Jesus followers.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>True<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->23.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The Hispanic Biblical Interpretation must “critique
Enlightenment-based biblical approaches” because they tend to deal with
afterlife concerns but not real-world practical concerns in local communities. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>True <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->24.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The Asian American Biblical Interpretation is difficult to pin
down because there are so many cultures and time-periods represented in the term
“Asian American”, nevertheless, it seeks to find the overlap between exegesis
and the Asian American experiences and histories that this community brings to
the text, including the experience of being treated as “Always Ethnic, Never
American”.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>True <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->25.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The African American Biblical Interpretation shows the unique
ways in which being Black in the United States of America is qualitatively
different than being black in other countries. A history of slave ownership
created a reading of the biblical texts rooted in ‘hope’ of freedom, with a
strong root in the Exodus narratives. This interpretation helps the reader see
hope in the midst of deep pain and turmoil and opposition.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>True<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->26.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp; </span><!--[endif]--><span dir="LTR"></span>The Majority-Culture Biblical Interpretation (Reading While
White) is already the default reading and lion-share of biblical scholarship;
therefore, this reading is intended to make white people feel guilty about
being white and dominating the discussion, so they can stop contributing and
give others their turn instead.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->a.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>True<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="margin-left: 0.75in; mso-add-space: auto; mso-list: l0 level2 lfo1; text-indent: -0.25in;"><!--[if !supportLists]-->b.<span style="font-feature-settings: normal; font-kerning: auto; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]--><span dir="LTR"></span>False<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p><br /><br />

<span style="font-family: &quot;tempus sans itc&quot;;">Shalom&nbsp;<span face="sans-serif" style="background-color: white; color: #202122; font-size: 14px;">שָׁלוֹם</span>: Live Long and Prosper!</span>
<br />

<div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe</span>
</div>

Storyteller | Writer | Thinker | Consultant | Freelancer | Bible Nerd
<i>*Written withs some editing and research assistance from ChatGPT-4o</i>
<br /><br /><br />

