---
title: 'The Interpretive Question: How to understand the Bible, methodically.'
date: '2025-05-03T18:59:00.0030000+00:00'
draft: false
categories:
  - 'Study'
  - 'Thinking Biblically'
  - 'Ancient Near East (ANE)'
  - 'Church Hurt & Trauma'
  - 'Bible Answer'
  - 'Research'
  - 'Q&R'
  - 'Churchianity Myths'
  - 'Armchair Theology'
---

<h4 style="text-align: left;"><span style="white-space-collapse: preserve;"><span>There is critical thinking (textual criticism) and then there is outright </span><span>skepticism</span><span>. </span></span></h4><div><span style="white-space-collapse: preserve;"><span><br /></span></span></div><div><span style="white-space-collapse: preserve;">When scholars like Bart D. Ehrman or Daniel McClellan make big sweeping claims, like "The Bible never..." or "There are no data that support..." or "Jesus nowhere said..." or "The scholarly consensus is..."; they are speaking scholar-eese. </span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">The thing is, a lot of what they say is accurate. Sometimes, however, their commitment to a particular worldview or bias shows, and this is where it gets interesting. We have our own commitments to worldviews and biases. You'll hear Dan say that certain claims are just "dogma", but he never admits that his own biases are dogma as well. </span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">Textual Criticism is good, </span><span style="white-space-collapse: preserve;">it asks us to throw off dogma, assumptions, biases, and ask what's really going on in, behind, and in front of the text. It asks us to be willing to change our understanding of what we see in the text. This is healthy skepticism.</span></div><div><br /><span style="white-space-collapse: preserve;">Then there is unhealthy skepticism that assumes the worst possible about a thing from moment one. Scholars sometimes over-react to the dogma of the church with their own dogma against the church. </span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">When you hear me or anyone else use sweeping claims, exaggeration of evidence, hasty generalizations, false dichotomies (must be this or that), absolutisms (always, never, none), it is an indication that we are likely  tending toward the unhealthy skepticism side of the pendulum. </span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">Unhealthy: There is no evidence for... All scholars agree... </span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;"><span>&nbsp;&nbsp; &nbsp;Hint: I've read a lot of scholars, there is no such thing as consensus. You can have majority and minority. You can even have either no representation of an idea, or such little representation for it that it is fringe. But you cannot have 100% unanimity on any position or claim. </span><br /></span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">Healthy: Most scholars (or most scholars I've read within my circle of influence) agree about... </span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">Healthy: Scholars generally agree that interpretation D is not textually valid, but they usually land divided between A, B. and C. I lean toward C for the following reasons... </span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">Healthy: Group-A makes this claim. I (being in Group-B) think that claim is nonsensical and the data do not support that claim. Here is what I see in the data. I want to freely admit to the biases, worldviews, and assumptions I am bringing to the conversation, and why I outright reject some or all of Group-A's claims. </span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><h4 style="text-align: left;"><span style="white-space-collapse: preserve;">Missing Data</span></h4><div><span style="white-space-collapse: preserve;">It is often the case that as I read Group-A (Dogmatic holding to Church traditions) and Group-B (dogmatic holding to secular positions), that I see them as the same group.</span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">I look for scholars who freely to admit to how often they've changed their mind or changed a position upon new evidence. I look for scholars who show which positions they've considered and why they chose the position they arrived at, up to this point.</span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div>I often find that people who arrived in a different position I did have either (1) never heard of the data I've considered or (2) have heard it and have reasons for rejecting it, reasons which I would like to know and understand. I may or may not agree with their reasons, but I want to understand it. Understanding it will either strengthen my view of the data, or, cause me to reject my view for a more accurate view.&nbsp;</div><div><br /></div><div><span style="white-space-collapse: preserve;">We must find a balance. </span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">Dogmatic Churchianity and Dogmatic Secular Skepticism are both extremes.</span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">So, how do we find that balance?</span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;"><b>Simple ask one simple but difficult </b></span><b style="white-space-collapse: preserve;">Interpretive </b><b style="white-space-collapse: preserve;">Question: </b></div><div><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">What is this author attempting to communicate to this author's audience? </span></li></ul><div><span style="white-space-collapse: preserve;">We... </span></div><ul style="text-align: left;"><ul><li><span style="white-space-collapse: preserve;">Don't assume that this author is attempting to mislead us. </span></li><li><span style="white-space-collapse: preserve;">Don't assume this author is intending to be literal or historical.</span></li><li><span style="white-space-collapse: preserve;">Do assume that this author has a worldview and is operating within the literary conventions of their time and place.  </span></li><li><span style="white-space-collapse: preserve;">Do assume that this author has an audience, and is attempting to communicate some idea or emotion or construct to their audience in the manner which is common for them.</span></li></ul></ul><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;"><b>To answer the Interpretive Question is less simple:</b></span></div></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">This requires us to start asking increasingly complicated questions that require PhD(s) and several lifetimes worth of study. We simply don't live 2000+ years ago, in a non-English speaking part of the world, without modern assumptions. The past is a foreign world, and they did things differently there. </span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">So, we get as much material as we can, compiled by thousands of people who've done those PhD(s) in various different fields attempting to answer aspects of the questions, and we call those compilations by names like:</span></div><div><div><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">Dictionary</span></li><li><span style="white-space-collapse: preserve;">Lexicon</span></li><li><span style="white-space-collapse: preserve;">Commentary</span></li><li><span style="white-space-collapse: preserve;">Monograph</span></li><li><span style="white-space-collapse: preserve;">Journal Article</span></li><li><span style="white-space-collapse: preserve;">Textual Notes</span></li><li>Among other names...&nbsp;</li></ul><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">Then we sift through those works, understanding that some of the PhD(s) will have the same level of bias that a Flat Earther has, but most of them will provide us with good data we can use to answer the questions we'll need to ask. </span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><h4 style="text-align: left;"><span style="white-space-collapse: preserve;">Redactors and Authorial Goals</span></h4><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">Also, w</span><span style="white-space-collapse: preserve;">e r</span><span style="white-space-collapse: preserve;">efuse to think of "The Bible" as one monolithic work. We understand that each "book" was originally a scroll or document in its own right. Even that "book" or scroll may have originally been many other works that are lost to history, and what we have is a compilation by some final editor or redactor. </span></div></div><div><span style="white-space-collapse: preserve;"><i><blockquote>ChatGPT Explains Redactor: A <b>redactor</b> is someone who collects, arranges, modifies, and combines source materials (oral or written traditions) into a new, cohesive literary work. This person isn't just correcting grammar or updating words—they're shaping theological meaning, narrative flow, and even historical framing.
</blockquote></i>In any given text, we are seeing potentially several source documents underneath that text, plus editors along the way who make editorial inserts (look in the Tanakh for "to this day"). We are also seeing redactors who compiled these into a final work of some kind for some kind of purpose. It is ultimately these redactors who play the most crucial role in the document we have in its final form. </span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">We can begin to ask questions that will help us start to understand the world, worldview, purposes, and goals of the authors/editors/redactors who gave us this final text document.</span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><h4 style="text-align: left;"><b style="white-space-collapse: preserve;">Interpretive Questions</b></h4><div><span style="white-space-collapse: preserve;">This is how we start digging into the </span><b style="white-space-collapse: preserve;">Interpretive Question</b><span style="white-space-collapse: preserve;">, and this can take a lifetime, so we take bite sized pieces.</span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">Here are just a few of the kinds of questions we can begin to ask of the text:</span></div><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">What can we know about the author(s), editors, and redactors? </span></li></ul><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">What can we know about the time period the text is speaking about?</span></li></ul><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">What can we know about the time period of the author and intended audience, and how might that be different that the time period of the narrative/text?</span></li></ul><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">What are some plausible things we can understand about the author and audience? </span></li></ul><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">What kinds of rhetorical goals might this author have in communicating with their audience(s)? Are there things we know about the larger culture, or clues within the text itself to help us answer that question?</span></li></ul><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">What genre, style, and conventions that other authors in that period are following, how does this author follow or diverge from those? </span></li></ul><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">What level of detail or historicity can/should we expect of any author from this time period, in this part of the world? </span></li></ul><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">What are the author's rhetorical goals? </span></li></ul><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">What other texts (either in the target language, or in languages adjacent to the target languages/context) might this author be aware of, or be drawing inspiration from? </span></li></ul><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">What are the worldview elements that everyone in this and surrounding cultures just assume is correct, such that it is adopted and brought into the text without question? </span></li></ul><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">What are the semantic ranges of the keywords in the target text's language, and how might that semantic range flavor our understanding in the translated language (English in our case)? </span></li></ul></div><div><span style="white-space-collapse: preserve;">These are just some entry level questions, there are many hundreds or thousands of other questions, depending on where these might lead. </span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><span style="white-space-collapse: preserve;">We have to admit that these are ancient peoples writing within their genres and contexts, and not assume they are doing something a modern would do while also not assuming they are completely fabricating everything to lie to us. They're just not us. </span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><h4 style="text-align: left;"><span style="white-space-collapse: preserve;">Closing thoughts...</span></h4><div><span style="white-space-collapse: preserve;">What are some conclusion that I've arrived at, in which I might still change my mind but this is where I land today?</span></div><div><span style="white-space-collapse: preserve;"><br /></span></div><div><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">Genesis 1-11 was written during the Babylonian exile and is fiction to make a theological point as it interacts with the shared cultural worldview of that time and place. </span></li></ul><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">The earth is billions of years old; it was not created in 6-literal days 6,000 years ago. Augustine agrees with me. But more importantly, the author of Genesis 1 wasn't making that claim. That is you doing poor Bible reading in English Bibles without even bothering to compare all the creation narratives (including Psalms). Even a rudimentary comparison of Genesis 1 and 2 would tell you that kind of reading has issues from square one. Is it an interpretive option? Maybe, if you throw out the Interpretive Question and adopt a less academic process for your reading. I just don't see how you arrive at that conclusion when you really take the text seriously. I do see how people arrive there, I did for years, but it requires not knowing the Interpretive Question, or even how to read very well. </span></li></ul><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">Genealogies in Matthew and Luke are fiction, they are narrative devices to show a theological linkage between Jesus and the story of Israel, they are not intended by the authors to be literal history.</span></li></ul><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">Some scholars work very hard to prop-up Dispensational Theology that produces concepts like a "Rapture" and "7-Year Tribulation". I simply cannot see that as a viable reading of the texts in their original contexts. I would not even consider those to be among the viable interpretive choices, based on the data. I understand well-meaning people see it differently. I would love and respect those people but would avoid them as teachers. Why? Because the commitments they had to make to arrive at those conclusions will mean that they are not faithfully engaging with the Interpretive Question as outlined above. </span></li></ul><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">The Jewish Rabbi, Yeshua (Iesos/Jesus) was a real individual in the 1st century, he was killed by the Romans in the 30s AD. Most scholars, even secular scholars, do find agreement on this point. </span></li></ul><ul style="text-align: left;"><li><span style="white-space-collapse: preserve;">Unlike the secular scholars (who have a worldview and pre-commitment against miracles as a viable interpretive option), I have seen the risen Jesus with my own eyes. I believe he died, rose bodily, and is returning bodily to earth someday. </span></li><ul><li>That is a bias and commitment I bring to the interpretive question.</li><li>Is it possible that I hallucinated as a child and the core-memory childhood imagination is now driving my interpretative choices? Yes. That's possible. I have checked with both my gut and trained therapists, and I don't believe this is the case. However, it could be. Nevertheless, I do believe my experience(s) to be legitimate and thus they do drive some of my pre-assumptions; or at least, they force me to consider as possible things that secular scholars reject as possible without considering them.</li></ul></ul><div><br /></div><div>This last part is what I mean by being critical without being skeptical. If you want to begin the Interpretive Question by claiming that miracles are impossible and therefore all such claims are fabrications or hallucinations, that is fine. But you cannot claim that you are more objective than the dogmatic Young Earther. You should admit that you are bringing that bias to your research and claims. Own it, and don't try to hide behind scholarly consensus. We all have biases, own yours, and your conclusions will be more honest (No Hiding).&nbsp;</div><div><br /></div><div>To find people who are asking good questions, check out my resource pages linked here:</div><div><br /></div><div><a href="https://www.nohiding.faith/p/resources.html" target="_blank">Resources ~ NoHiding.Faith</a></div><div><br /></div><div><a href="https://www.nohiding.faith/p/resources-scholars-thinkers.html" target="_blank">Written Resources: Scholars &amp; Thinkers ~ NoHiding.Faith</a></div><div><br /></div><div><a href="https://www.nohiding.faith/p/podcastsyoutube-channels.html" target="_blank">Audio/Visual Resources: Podcasts/YouTube Channels ~ NoHiding.Faith</a></div><br /><br />

<span style="font-family: &quot;tempus sans itc&quot;;">Shalom&nbsp;<span face="sans-serif" style="background-color: white; color: #202122; font-size: 14px;">שָׁלוֹם</span>: Live Long and Prosper!</span>
<br />

<div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe</span>
</div>

Storyteller | Writer | Thinker | Consultant | Freelancer | Bible Nerd
<i>*Written withs some editing and research assistance from ChatGPT-4o</i>
<br /><br /><br />

</div><div><br /></div>