---
title: 'What is Paradise? Who ascended? Recontextualizing John 3:13 and Luke 23:43'
date: '2025-02-08T07:49:00.0020000+00:00'
draft: false
categories:
  - 'Class Discussion Posts'
---

<p><i>Question:&nbsp;How can we explain Jesus’s response to the man on the cross “today you will be with me in paradise” whereas Jesus himself says in John 3:13 No one has ever gone into Heaven except the one who came from Heaven? What paradise does Jesus talk about?</i></p>
<p>&nbsp;</p>
<h4 style="text-align: left;"><span class="post_mention">Thoughts:</span></h4>
<ol>
<li><span class="post_mention">We should start by asking what each gospel author is doing separately before we start combining the narratives. Each gospel author has specific things they are highlighting and themes they are drawing upon. These are not merely historical records of events, they are theological works. Each gospel author should be taken on their own first. </span></li>
<li><span class="post_mention">The author of the gospel of John never mentions the interaction of the thief. In John 3:13, Jesus is speaking with his fellow rabbi/colleague, Nicodemus. The interaction begins by Nico being confused by Jesus' claims. Jesus responds by asserting his authority to speak of the things of God's domain. "</span>And no one has ascended into heaven except the one who descended from heaven—the Son of Man." Any reference to the Son of Man is a reference to a human+divine figure from the Hebrew Bible (specifically Daniel). This sentence is asking Rabbi Nico to reflect on the passage(s) around this figure and this figure's ascent to heaven. Jesus is making a play on very old ideas around who this figure might be. He's claiming to be this figure, and Nico as a Rabbi would have understood this. Further, this conversation takes place before the cross event.</li>
<li>The author of the gospel of Luke tells a longer story about the cross event, and he is the one who mentions the paradise. Jesus turns to the thief and says, "<em>today you will be with me in paradise</em>" Lk 23:43. This term, paradise [παράδεισος (paradeisos)] has also has a long history of use in Second Temple Judaism. In the Greek translation of the Hebrew Bible (aka The Septuagint, LXX), "Eden" in Genesis 3 is translated from Hebrew to Greek as paradise [παράδεισος (paradeisos)]. The "garden of God" is a well establish motif in Ancient Near East literature, and in the Hebrew Bible specifically. Gardens and Mountains were poetic motifs of God's space or sacred spaces. To a Jewish audience living in the first century AD, Jesus telling the thief he would be together in paradise [παράδεισος (paradeisos)] is to say that they will be together in Yahweh's domain, Eden, The Garden of God, the Mountain of God. All of these are thematic and poetic references to the same concept. We call this "Heaven" in English, though our English word carries frieght that may not be in their worldview. It's close enough for understanding what is meant by paradise [παράδεισος (paradeisos)].&nbsp;</li>
</ol>
<p>&nbsp;</p>
<h4 style="text-align: left;">Conclusion:</h4>
<p>Jesus told Nico that only the one who came from God's domain (paradise [παράδεισος (paradeisos)], heaven, Eden, etc.) could then ascend to this same space. That is pre-cross. At the cross, he announces that he is taking people with him on his return.&nbsp;</p>
<p>Recontextualizing our English terms (loaded with medieval theologians' ideas) with the Jewish worldview of the first century helps clarify almost every confusing statement in the New Testament.&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><b><u><i>For further reading, copy this somewhere and check out these resources and themes:</i></u></b></p>
<hr />
<p><strong>See further explanations &gt;&nbsp;</strong></p>
<p>&nbsp;</p>
<p>From: D. L. Bock, “Son of Man,” in Dictionary of Jesus and the Gospels, Second Edition, ed. Joel B. Green, Jeannine K. Brown, and Nicholas Perrin (Downers Grove, IL; Nottingham, England: IVP Academic; IVP, 2013), 894.</p>
<p style="padding-left: 40px;">SON OF MAN</p>
<p style="padding-left: 40px;">According to the Gospels, “Son of Man” is Jesus’ favorite self-designation. It is used eighty-six times in the NT (Synoptics 69×, John 13×, elsewhere 4×). In the NT it is never presented as a confessional term from someone in the early church. However, Jesus does use it alongside confessional titles, such as “Messiah,” that others raise (e.g., Mk 8:29–31; 14:61–62). The phrase in its various lexical constructions is almost exclusively confined to the Gospels, except at Acts 7:56; Hebrews 2:6 (where Ps 8:4 is cited); Revelation 1:13; 14:14. In the Gospels only Jesus uses the term, except at John 12:34, where what he has said is cited by others. The term is written in Greek as “the son of the man” (ho huios tou anthrōpou), except for John 5:27; Hebrews 2:6; Revelation 1:13; 14:14 (huios anthrōpou). The phrase in a few Gospel passages (Mt 24:30 // Mk 13:26 // Lk 21:27; Mt 26:64 // Mk 14:62 // Lk 22:69) is related directly to language from Daniel 7:13–14 and, as was noted above, is associated in Hebrews 2:6 with Psalm 8, where it carries its common meaning of “human being,” as a “son of man” is a descendant of a man and thus a human.<br />The expression also has a rich background in the Scripture of Second Temple Judaism as well as in traditions derived from it. So we proceed by examining its usage and background in this Jewish context before considering its NT use.<br />Finally, the expression in Aramaic is idiomatic (bar ʾĕnāš). It is not a title, just as it is not a title but rather a description (“one like a son of man”) in its original use in Daniel 7:13–14. This means that it can function as an expression on its own without evoking any biblical associations, although the power of the description makes it a candidate to become a title or at least a clear designation of a distinct figure. This type of usage feeds into its development in Second Temple Judaism and in the NT.</p>
<p style="padding-left: 40px;">///</p>
<p style="padding-left: 40px;">2. Usage in Second Temple Judaism</p>
<p style="padding-left: 40px;">Besides a linguistic context for the use of “son of man,” there also is a tradition rooted in Scripture and reflected on in Second Temple Judaism that is sometimes reflected in this phrase. Two texts are of great significance, while others show the context in which such hope operated. The idea of the vindicated, rejected righteous has roots in the Psalter (Pss 22; 69) and is presented in the picture of vindicated, rejected wisdom in Wisdom 2 and 5. The influence of the latter passage on some “son of man” passages is traced by G. Nickelsburg. These set a context that Daniel 7 also reflects: the vindication of the righteous. This Danielic text is by far the most important scriptural context for the expression “son of man” when it is linked to Scripture.<br />2.1. Daniel 7. This text is an overview of the historical movement toward God’s deliverance of his people. It moves through four world dynasties pictured as aberrant animals (lion with eagle’s wings, bear with a human mind, leopard with four birdlike wings, dreadful beast with two rows of iron teeth). In contrast comes “one like a son of man,” a human, who rides the clouds to the Ancient of Days to receive ruling authority (Dan 7:13–14). In Daniel 7:27 this authority and the identification of the figure are tied to the saints of the Most High. But the dynasties of Daniel 7 are also tied to kings who lead them. So, although Daniel’s interpretation points to the corporate beneficiaries of this new thing that God will do, the idea of a figure to lead it is not far away. This idea is suggested by the statement in Daniel 7:27 that all will serve and obey him. The term translated as “serve” (plḥ) here carries the meaning of “worship” (Dan 3:12, 14, 18, 28; 6:17, 21; 7:14, 27 [parallel to sgd in Dan 3:18]), something not done of a nation. The Son of Man is pictured as a singular human figure with transcendent qualities, as his riding of the clouds indicates. In the OT it is deity that rides the clouds (Ex 14:20; 34:5; Num 10:34; Ps 104:3; Is 19:1). <span style="background-color: #fbeeb8; text-decoration-line: underline;"><em><strong>So this image is of a human being who also has heavenly qualities.</strong></em></span> The emphasis in the text is that he receives authority in response to the suffering of God’s people. It is the feature of human-heavenly elements and authority that are important in the usage picked up in the NT. The interpretation of this figure in Daniel is disputed as being either corporate for Israel, an angelic figure (perhaps Michael or Gabriel), or involving an eschatological figure (either a messiah or another eschatological deliverer). What is indisputable is that in Second Temple Judaism an individual with authority to deliver and judge developed from this image, as our two other key Second Temple texts show.<br />2.2. 1 Enoch 37–71.The book of 1 Enoch is a composite Jewish book, probably made up of five parts stitched together over time. The earliest part comes from two centuries before the time of Jesus. The last section added includes material that refers to the Son of Man. These key chapters probably go back to the Herodian era of the late first century B.C. and early first century A.D., since they contain allusions to the Parthian conflict in the forties B.C. (Bock and Charlesworth). This date is likely despite the fact this section was missing from Enoch texts found at Qumran (Esther too was not found there, and we know it predates the community) (see Dead Sea Scrolls). The book of 1 Enoch has an eschatological hero in Enoch, and this would counter the hero of Qumran, the Teacher of Righteousness. This important section 1 Enoch 37–71 is known as the Similitudes or Parables of Enoch. In it there is a key figure who goes by a variety of names: “righteous one,” “chosen one,” “anointed one,” and this or that “son of man.” He functions as a judge and is preexistent (1 En. 46; 62–63). Nickelsburg speaks of a conflation of images in this portrait, drawing on Wisdom 2; 5 (preexistent like wisdom) and the one who vindicates in Isaiah 52–53. Some discount any connections between Jesus as the Son of Man and the ideas expressed in 1 Enoch because of the preexistence of the Enoch figure, which is not like the NT usage, and because there is no mention of the Son of Man “coming” as in the NT (Burkett). Others argue in response that the point is the function of this figure as judge and his transcendent quality. In any case, 1 Enoch shows that imagery associated with a Son of Man figure was in play and under development in the Second Temple period.<br />2.3. 4 Ezra 11–13. This text is the least important of the three, in part because this material postdates our period. However, its picture of an eschatological judge who has royal characteristics while appealing to the imagery of Daniel 7 confirms that imagery associated with a Son of Man concept was current during the period.<br /><span style="background-color: #fbeeb8;"><em><span style="text-decoration-line: underline;"><strong>As a group, these texts show that a transcendent judge-deliverer was associated with a figure who was called Son of Man.</strong></span></em></span> The notion that a “Son of Man” title existed in this period is sometimes challenged, but the presence of a specific title is not the key point. Rather, the point is that there existed in some Jewish thought a figure associated with heaven who judges. The portrait occurs in various forms, but this figure is called, among other names, Son of Man.</p>
<p>&nbsp;</p>
<p>From: W. Hall Harris III et al., eds., The Lexham English Bible (Bellingham, WA: Lexham Press, 2012), Lk 23:39–44.</p>
<p style="padding-left: 40px;"><em>39 And one of the criminals who were hanged there reviled him, saying, “Are you not the Christ? Save yourself—and us!” 40 But the other answered and rebuked him, saying, “Do you not even fear God, because you are undergoing the same condemnation? 41 And we indeed justly, for we are receiving what we deserve for what we have done. But this man has done nothing wrong!” 42 And he said, “Jesus, remember me when you come into your kingdom!” 43 And he said to him, “Truly I say to you, today you will be with me in paradise.”&nbsp;</em></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>From:&nbsp;Benjamin M. Austin, “Afterlife,” in Lexham Theological Wordbook, ed. Douglas Mangum et al. (Bellingham, WA: Lexham Press, 2014).</p>
<p style="padding-left: 40px;">παράδεισος (paradeisos). n. masc. paradise. Refers to the place where the blessed or righteous dead go after death. The place where the righteous dead enjoy a blessed afterlife is sometimes called paradise (paradeisos) in the NT. In Luke 23:43, Jesus tells the thief who had faith that he would be with him in paradise (paradeisos). In 2 Corinthians 12:1–4, Paul refers to heaven as paradise (paradeisos). Revelation 2:7 also seems to refer to heaven as the “paradise (paradeisos) of God.”</p>
<p>&nbsp;</p>
<p>From:&nbsp;Justin W. Bass, “Paradise,” in The Lexham Bible Dictionary, ed. John D. Barry et al. (Bellingham, WA: Lexham Press, 2016).</p>
<p style="padding-left: 40px;">PARADISE (παράδεισος, paradeisos). A loanword from ancient Persian pairi-daeza which can mean “an enclosed space,” “park,” or “garden.” Associated with heaven, New Jerusalem, and Christ’s dwelling place.</p>
<p style="padding-left: 40px;">Paradise in the Ancient World<br />The earliest attestation for “paradise” (παράδεισος, paradeisos) in ancient literature is found in the Septuagint (LXX), in Gen 2 and 3. It is likely a loanword from ancient Persia dating back to the sixth century BC. It comes from the Persian word pairi-daeza which can mean “an enclosed space,” “park,” or “garden” (Xenophon, Anabasis 1.2, 7; 2.4, 14; Aristides, Roman, 26, 99).</p>
<p style="padding-left: 40px;">Paradise in the Septuagint (LXX)<br />Alexandrian Jews translated the Hebrew words פַּרְדֵּס (pardes), גַּן (gan), and עֵדֶן (eden) (once) with the Greek word “paradise” (παράδεισος, paradeisos). פַּרְדֵּס (pardes) is used in the book of Nehemiah to describe a forest (Neh 2:8), in Song of Songs to depict an orchard (Song 4:13), and in Ecclesiastes to describe Solomon’s campaigns to create gardens and parks (Eccl 2:5). The Prophets first gave this word its eschatological connotations, beginning with Isa 51:3. Isaiah promises that the eschatological Jerusalem will be like the Garden of Eden—paradise redivivus. Within the Hebrew (and LXX) Scriptures:</p>
<p style="padding-left: 40px;">&nbsp; • &nbsp; &nbsp; &nbsp;God planted paradise for His people (Gen 2).<br />&nbsp; • &nbsp; &nbsp; &nbsp;Paradise was taken away as a result of sin (Gen 3).<br />&nbsp; • &nbsp; &nbsp; &nbsp;Paradise will be restored for His people in the messianic age (Isa 51:3; Ezek 47:1–12; Rev 22:1–2).</p>
<p style="padding-left: 40px;">Paradise in Second Temple Literature<br />During the Second Temple period, paradise was one of the primary locales for the righteous in the afterlife. The Testament of Levi presents the Messiah opening the “gates of paradise” for the saints (T. Levi 18.10–11). This is the earliest example of a religious use of “paradise” outside of the Old Testament (Jeremias, TDNT, 5.765). Paradise is the dwelling place of the righteous dead in the afterlife. Paradise may have been:</p>
<p style="padding-left: 40px;">&nbsp; • &nbsp; &nbsp; &nbsp;The Underworld (1 En. 22; 4 Ezra 4:7–8; 7:37, 38; compare Josephus, Antiquities 18.14–15).<br />&nbsp; • &nbsp; &nbsp; &nbsp;In the earth (Jubilees 3.12; 4.26; 8.16, 19; compare Origen, First Principles 2.11.6).<br />&nbsp; • &nbsp; &nbsp; &nbsp;In heaven (1 En. 60.8; 65.2; 70.3; 89.52; Ps. Sol. 14.2–3; 2 En. 8–9; L.A.E. 37.5).</p>
<p style="padding-left: 40px;">Paradise in the New Testament<br />The word “paradise” only occurs in the New Testament three times (Luke 23:43; 2 Cor 12:4; Rev 2:7). In Paul’s writings, paradise is presented as synonymous with the third heaven (2 Cor 12:2, 4). In Revelation, it is synonymous with the New Jerusalem (Rev 2:7; 21:2). This shows the transferable nature of the term παράδεισος (paradeisos) in the New Testament. Paradise is clearly distinguished from “heaven” (τοῦ οὐρανοῦ, tou ouranou) in Rev 21:2, but Paul equates paradise and heaven (2 Cor 12:2, 4).<br />The book of Luke presents Jesus stating that he will see the man crucified next to Him in paradise, that day (Luke 23:43), but it also includes Peter’s statement that Christ’s soul dwelt in Hades between His death and resurrection (Acts 2:27, 31). This may suggest that Luke considered paradise to be the abode of the righteous in the Underworld (compare 1 En. 22; 4 Ezra 4:7–8; 7:37, 38; Josephus, Antiquities 18.14–15). Paradise could also be a transferable locale in the New Testament because the presence of Christ is what makes the reality paradise.</p>
<p style="padding-left: 40px;">&nbsp; • &nbsp; &nbsp; &nbsp;The criminal was with Christ in paradise in the Underworld on Good Friday.<br />&nbsp; • &nbsp; &nbsp; &nbsp;Paul visited paradise in the third heaven where Christ currently dwells (2 Cor 12:2, 4; Phil 1:21–26; 3:20).<br />&nbsp; • &nbsp; &nbsp; &nbsp;The saints enter paradise in the New Jerusalem because the Lamb (Christ) will dwell there forever and ever (Rev 2:7; 21:22; 22:1–5, 14).</p>
<p style="padding-left: 40px;">Bibliography<br />&nbsp; Beale, G. K. The Book of Revelation: A Commentary on the Greek Text. New International Greek Testament Commentary. Edited by I. H. Marshall and D. A. Hagner. Grand Rapids: Eerdmans, 1999.<br />&nbsp; Jeremias, J. “παράδεισος (paradeisos).” Pages 765–73 in Theological Dictionary of the New Testament 5. Edited by G. Kittel, G. Freidrich, and G. Bromiley. Grand Rapids: Eerdmans, 1964–76.<br />&nbsp; MacCulloch, J. A. The Harrowing of Hell: A Comparative Study of an Early Christian Doctrine. Edinburgh: T&amp;T Clark, 1930.<br />&nbsp; Weisengoff, J. P. “Paradise and St. Luke 23:43.” American Ecclesiastical Review 103 (1940): 163–68.</p>
<p style="padding-left: 40px;">JUSTIN W. BASS</p>
<p>&nbsp;<br /></p><br /><br />

<span style="font-family: &quot;tempus sans itc&quot;;">Shalom&nbsp;<span face="sans-serif" style="background-color: white; color: #202122; font-size: 14px;">שָׁלוֹם</span>: Live Long and Prosper!</span>
<br />

<div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe</span>
</div>

Storyteller | Writer | Thinker | Consultant | Freelancer | Bible Nerd
<i>*Written withs some editing and research assistance from ChatGPT-4o</i>
<br /><br /><br />
