---
title: 'Life after death, and the question of evil...'
date: '2025-08-24T17:09:00.0050000+00:00'
draft: false
categories:
  - 'Q&R'
---
This was a question from a Facebook group, and I ended up writing an answer so long, I thought it was worth posting here too.

**The Question:**

*So what DOES happen to "souls" when we go to the great beyond? I'm being completely serious. I got confirmed in the [Lutheran church](https://www.google.com/search?ved=1t:260882&q=Lutheran+church+beliefs&bbid=886465956400541517&bpid=1429149364207651413), have not been back in 40 some years. I don't know if I even believe there is some [mysterious being](https://www.google.com/search?ved=1t:260882&q=concept+of+a+mysterious+being+religion&bbid=886465956400541517&bpid=1429149364207651413) that is in charge of life and death. All I know is I'm looking for someone to blame and that mysterious being is the one.*

**My Answer:**

The question of the ages.

Short answer, if we're using the [biblical texts](https://www.google.com/search?ved=1t:260882&q=types+of+biblical+texts&bbid=886465956400541517&bpid=1429149364207651413) as our source, is that it's impossible to say with any certainty.

Almost every 'doctrine' of Christianity was created (contrived) in the post biblical periods. Very few claims of any Christian movement today would be recognized by any of the [biblical authors](https://www.google.com/search?ved=1t:260882&q=famous+biblical+authors&bbid=886465956400541517&bpid=1429149364207651413).

Even the biblical authors themselves had very little to say about the non-material world or life after death. They provided very little commentary, and when they did it was shrouded in metaphor and allusion. They did however make a few interesting notes, but first I have to lay the framework for the non-initiated into the [Ancient Near East worldview](https://www.google.com/search?ved=1t:260882&q=define+Ancient+Near+East+worldview&bbid=886465956400541517&bpid=1429149364207651413) so it makes sense.

They weren't interested in the afterlife much, not in the way moderns think of it.

They were primarily focused on how to live well in this life. They were also frequently interested in life after "life after death", as [NT Wright](https://www.google.com/search?ved=1t:260882&q=NT+Wright+biography&bbid=886465956400541517&bpid=1429149364207651413) would describe it. They were interested in [The Resurrection](https://www.google.com/search?ved=1t:260882&q=The+Resurrection+biblical+meaning&bbid=886465956400541517&bpid=1429149364207651413), [The Day of Yahweh](https://www.google.com/search?ved=1t:260882&q=define+The+Day+of+Yahweh&bbid=886465956400541517&bpid=1429149364207651413) ([the Day of the LORD](https://www.google.com/search?ved=1t:260882&q=define+the+Day+of+the+LORD&bbid=886465956400541517&bpid=1429149364207651413) in English translations).

For the biblical authors, death was the great enemy. It was envisioned as exile from the land of the living. This is what many non-Hebrew readers miss in [Genesis 1-11](https://www.google.com/search?ved=1t:260882&q=Genesis+1-11+meaning&bbid=886465956400541517&bpid=1429149364207651413). When it is said that Human ([Hebrew adam](https://www.google.com/search?ved=1t:260882&q=define+Hebrew+adam&bbid=886465956400541517&bpid=1429149364207651413) = human, it's an analogy story) is told that in the day he will eat of the fruit of knowledge he will 'surely die', and then he goes on to live almost a thousand years, English readers get confused. They debate over the term death, the application of it, and the timing. The actual concept the biblical authors were drawing on was plain and simple for anyone saturated in [Torah](https://www.google.com/search?ved=1t:260882&q=define+Torah&bbid=886465956400541517&bpid=1429149364207651413) (Gen - Deut) [Tanakh](https://www.google.com/search?ved=1t:260882&q=define+Tanakh&bbid=886465956400541517&bpid=1429149364207651413) ([Hebrew Bible](https://www.google.com/search?ved=1t:260882&q=define+Hebrew+Bible&bbid=886465956400541517&bpid=1429149364207651413), aka OT).

Human ate and was exiled.

Exile = Death.

This story was an analogy to help interpret their experience after being exiled to [Babylon](https://www.google.com/search?ved=1t:260882&q=Babylon+historical+significance&bbid=886465956400541517&bpid=1429149364207651413), and it was written during the exilic period, not before.

For the various unnamed poets and scribes throughout Tanakh. This theme of exile was explored in imagery, poetic language, metaphor, etc. To die was to be exiled from the land of the living and go their fathers (ancestors). It was to become a disembodied one (elohim = disembodied being, not strictly god, and it was used of many types of non-embodied entities).

While the biblical authors, from Genesis to Revelation, both in the Hebrew Bible (aka OT) and Greek biblical commentary (aka NT) had very little commentary on the after-life, they were deeply interested in the day when this final enemy, Death personified, was to be defeated, and injustice to be judged in its fullness.

They looked to a day when Yahweh would descend from his divine space and fully merge with this earthly space. They weren't looking to go to him, they were looking for him to come to us.

They had many terms, but the most common was The Day of Yahweh (the Day of the LORD in English translations). They imagined a day where the living and the dead would all rise and stand before Yahweh's judgement seat. There, he would punish those who created injustice and reward those who fought for justice.

**Ironically, in this framework, many modern [white evangelicals](https://www.google.com/search?ved=1t:260882&q=white+evangelicals+beliefs&bbid=886465956400541517&bpid=1429149364207651413) would fail the test.**

The biblical authors saw pain, death, and injustice as the result of human agency leading to exile [Shalom](https://www.google.com/search?ved=1t:260882&q=define+Shalom&bbid=886465956400541517&bpid=1429149364207651413) (peaceful life) and eventually from the material world. They blamed [agents of injustice](https://www.google.com/search?ved=1t:260882&q=agents+of+injustice+religion&bbid=886465956400541517&bpid=1429149364207651413) (both human and [rebel Elohim](https://www.google.com/search?ved=1t:260882&q=define+rebel+Elohim&bbid=886465956400541517&bpid=1429149364207651413), [disembodied rebel spirit beings](https://www.google.com/search?ved=1t:260882&q=disembodied+rebel+spirit+beings+definition&bbid=886465956400541517&bpid=1429149364207651413)) as the sources of all injustice. They looked forward to a day when Humankind's lease on this earth was complete, and Yahweh would return to judge his tenants for how they handled things while he was away. This is the root [Ancient Near East](https://www.google.com/search?ved=1t:260882&q=Ancient+Near+East+history&bbid=886465956400541517&bpid=1429149364207651413) and Hebrew Bible worldview behind [Jesus](https://www.google.com/search?ved=1t:260882&q=Jesus+Christ+biography&bbid=886465956400541517&bpid=1429149364207651413)' analogy of the [Land Owner](https://www.google.com/search?ved=1t:260882&q=Jesus+Land+Owner+analogy&bbid=886465956400541517&bpid=1429149364207651413) who left his farm to Tenants ([Matthew 21:33-41](https://www.google.com/search?ved=1t:260882&q=Matthew+21:33-41+meaning&bbid=886465956400541517&bpid=1429149364207651413)).

At this point, the 'wicked' those who twisted or perverted justice, would be cast out into\... nobody knows. They used a lot of poetic and metaphorical language based on real events in Israel's history. Much of the language is self-contradictory to other language. It all revolves around the theme of "the bad guys get theirs".

The biblical authors did not see Yahweh as a source of evil, but rather the judge of it and power to defeat it. They saw him as intervening in smaller more localized ways for his people in this present reality, and the future judge of all evil at some undisclosed future date. For them it was an 'already, but not yet' kind of idea. It's happening, but hasn't fully happened.

Meanwhile, those who fought for [The Ways of Yahweh](https://www.google.com/search?ved=1t:260882&q=define+The+Ways+of+Yahweh&bbid=886465956400541517&bpid=1429149364207651413), his justice and his Shalom (peace) would be rewarded by being given entrance into his everlasting kingdom. This was envisioned by a re-embodied experience, not a disembodied one. They weren't looking to leave earth and 'go to heaven when they die'. Not even the very Jewish Rabbi Sha'ul (apostle Paul) was looking for escape from earth. Rather, he was looking forward to the day when his own Rabbi, Yeshua (Jesus) who was the first-born of the dead, with a new body, would return and everyone else would get their new bodies.

The biblical authors weren't looking to escape earth, they were hoping for a day when earth would be redeemed, death defeated, and everyone would get new bodies free of death, sickness, and pain.

They called this Day, The Day of the LORD (Yahweh), or The Resurrection. Their vision was of a day when all who ever lived and sought the justice of Yahweh, even if they didn't know him by name, would return to their new bodies and live in peace forever on this earth, but renewed.

All that to say\... there were a few, very few, glimpses into what people thought might be happening for those who were exiled between this life and the resurrection.

The most clear post-Jesus reference is Paul's statement that 'to be absent from the body is to be present with The Lord'. This hints that Paul understood there to be a consciousness after the death of the body, at least for those on Yahweh's side. Virtually nothing is ever said about those who aren't on his side during this intermediate period between death and The Day.

Beyond the biblical authors, I can only cite people's varied experiences and ponder what they could mean. Many claims have been made, some more credible than others.

After my wife died, I saw her and the child who died in her, in a short vision. It was very realistic, but brief. They were happy. I believe I even heard 'god' say a few things to me about her status with him.

Whether those things were real, or ways my brain was processing grief, is probably open to interpretation. But I experienced them. And they allowed me to let some things go, and move forward with some degree of Shalom, tinged by grief though it was.

Are any of the things the biblical authors aspired to 'true'? Will there be a great Day of Yahweh? Or were they just metaphors and analogies that an ancient people used to grapple with the injustice of their time?

I think anyone who claims to be certain beyond any doubt about that is fooling themselves. But most data is just data until its interpreted. This worldview has the most compelling explanatory evidence for my own life experiences and 'strange' events since childhood.

I think quantum physics has taught us to question what is 'real' at some level. Humans can't perceive many basic things (like UV and Infrared) that some animals and bugs can.

Some scientists claim that there is mathematical and theoretical evidence to show that higher dimensions are plausible. They would claim these realities aren't 'out there' somewhere but rather right here with us in ways we cannot perceive.

That's similar to the Ancient Near East worldview. They didn't try to go to gods space, they created spaces where material and non-material could become one, sacred spaces, temples, ziggurats.

It is compelling that modern scientists are coming up with ideas that mirror an Ancient Near East worldview, the same worldview of the biblical authors, but a very different worldview from the Platonic Greek thinkers who used the biblical authors to create an entirely different creature in the first 300 years A.D.

So\..... what happens? My guess, the biblical authors were on to something, if we stop thinking in literal terms and wrestle with the truths they wrestled with but in modern terms.

**If you want to go further:**

- [Naked Bible 440: The Afterlife Part 1](https://nakedbiblepodcast.com/podcast/naked-bible-440-the-afterlife-part-1/)
- [Naked Bible 441: The Afterlife Part 2](https://nakedbiblepodcast.com/podcast/naked-bible-441-the-afterlife-part-2/)
- [Naked Bible 327: The Old Testament Afterlife and the Psalms of Korah](https://nakedbiblepodcast.com/podcast/naked-bible-327-the-old-testament-afterlife-and-the-psalms-of-korah/)
- [Exile](https://bibleproject.com/podcast/series/exile-series/) - Exile Follow discussions between Tim & Jon as they prepare to write the theme video on "Exile." This is a major theme in the Old Testament and essential in understanding Jesus' message.

Shalom ×©Ö¸×?×œ×•Ö¹×?: Live Long and Prosper!

Darrell Wolfe

Storyteller \| Writer \| Thinker \| Consultant \| Freelancer \| Bible Nerd **Written withs some editing and research assistance from ChatGPT-4o*
