---
title: "A Modern Beit Midrash: Engaging Scripture in Community"
date: 2026-3-07
categories: [biblical-studies]
tags: [scripture, context, study]
---

I've had a dream of starting something akin to Beit Midrash (בית מדרש), House of Study. 

I want something of a smash between an A.A. meeting and a Book Study, where we come to hear the biblical texts read and interpreted in their own ancient contexts, focus on what those contexts were, and then ask as a group what wisdom was operating for them back then, and as a group (in group discussion, not sermon) come to some conclusion about what wisdom it might have for us today. 

All the while, there is food for everyone (actual meals, not a thimble of grape juice) and places for kids to play, and song times campfire style. And then throughout the week, the facility (or homes or coffee shops or whatever) would be places where people can gather in smaller groups or 1:1 to do life together, share struggles, help each other accomplish things. 

If someone needs a new roof, we all go make it happen as a group. If we hear of someone in the larger community needing help, we go help, regardless of whether they're "one of us" or not. 

We regularly find the most needy in the region and meet their real needs in meaningful ways, not in token ways. Etc. 

It's ironic, because I'm the least likely person to (1) start anything like this and (2) go find other humans to be human with. But the dream won't die, it only grows every year. 

If anyone wants to start this, I'll help. 🙂

Just thinking out loud.

Darrell Wolfe, Storyteller. 