---
title: 'Walking more humbly. A spiritual discipline for Justice Warriors'
date: '2026-02-08T00:33:00.0060000+00:00'
draft: false
categories:
  - 'Class Assignment'
  - 'Sermon'
---

<p align="center" class="MsoNormal" style="text-align: center;"><b>&nbsp;</b><b>&nbsp;</b></p>

<p class="MsoTitleCxSpFirst" style="text-align: center;"><b>Walking more humbly.<o:p></o:p></b></p>

<p class="MsoTitleCxSpLast"><b>&nbsp;</b></p>

<p class="MsoNormal"><b>&nbsp;</b></p>

<p class="MsoTitle" style="text-align: center;"><b>A spiritual discipline for Justice Warriors<o:p></o:p></b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><o:p>&nbsp;</o:p></p>

<p align="center" class="MsoNormal" style="text-align: center;"><o:p>&nbsp;</o:p></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>By Darrell Wolfe</b><o:p></o:p></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>&nbsp;</b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>&nbsp;</b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>&nbsp;</b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>&nbsp;</b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>Submitted in
partial fulfillment of the requirements</b><br />
<b>for the course The Theology and Ethics of Martin Luther King, Jr.: ET543</b><o:p></o:p></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>&nbsp;</b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>Professor Phillip
Allen</b><o:p></o:p></p>

<p align="center" class="MsoNormal" style="text-align: center;"><b>&nbsp;</b></p>

<p align="center" class="MsoNormal" style="text-align: center;"><o:p>&nbsp;</o:p></p>

<w:sdt calendar="t" calendartype="Gregorian" date="2026-01-30T00:00:00Z" dateformat="dddd, MMMM d, yyyy" docpart="56F2F5988B774FDAB068B5A7327E4B13" id="-897983336" lang="EN-US" maptodatetime="t">
 <p align="center" class="MsoNormal" style="text-align: center;"><b>Friday, January
 30, 2026</b><o:p></o:p><b><w:sdtpr></w:sdtpr></b></p>
</w:sdt><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;"><br clear="all" style="mso-special-character: line-break; page-break-before: always;" />
</span>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<h1 style="line-height: 200%;"><b>Sermon – “<i>Walking more humbly… a spiritual
discipline for Justice Warriors</i>.”<o:p></o:p></b></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><i>“He has told
you, O mortal, what is good, and what does Yahweh ask from you but to do
justice, and to love kindness, and to walk humbly with your God?” (Micah 6:8,
LEB).<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Ethics_Martin_Luther_KingJr_ET543/Sermon_PublicSpeech_DarrellWolfe.docx#_ftn1" name="_ftnref1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><b><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[1]</span></b></span><!--[endif]--></span></a><o:p></o:p></i></p>

<h2 style="line-height: 200%;">Introduction<o:p></o:p></h2>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">I really like to
argue. This is not to say that I enjoy the academic pursuit of laying down
premises followed by evidence-based conclusions that follow logically from the
data. No, I mean I like to post things to my social media pages that will
intentionally stir ‘the other side’ to rage and then engage them in my comments
section with escalating vitriol and mutual disrespect. For years, my more
pastoral friends, my counselor, and my wife all lamented this habit. In my
calmer moments, I lament this habit as well. My autistic over-active sense of
justice rages against injustices and then I find myself taking extreme
positions against the extreme abuses I witness in the world. I’ve made repeated
attempts to change. Yet, I find myself falling back into the habit repeatedly. One
of the truly great ironies about this habit is that I have changed my own
understanding and stances largely through the academic pursuits I first mentioned.
The very stances I argue against today, inciting rage-filled rebuke by some of
my friends and acquaintances are the stances I used to support while these same
friends and acquaintances yelled “Yeah, you tell them!” Why do I engage in this
online behavior when my true core-self would rather I not? I have come to learn
it is (<i>in part</i>) related to low dopamine from Autism and ADHD, and it is
a dopamine seeking behavior. I still wanted to address the atrocities and
injustices, but it was time for a change in approach.<o:p></o:p></p>

<h2 style="line-height: 200%;">Exposition<o:p></o:p></h2>

<p class="MsoNormal" style="line-height: 200%;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Let
us start by looking to Micah for guidance. The setting of Micah’s prophetic
writing is the northern Kingdom of Isreal just prior to its destruction by the
Assyrians (~ 722 BCE).<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Ethics_Martin_Luther_KingJr_ET543/Sermon_PublicSpeech_DarrellWolfe.docx#_ftn2" name="_ftnref2" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[2]</span></span><!--[endif]--></span></a> In
chapter six, Micah begins a divine court case against Israel, “Arise! Plead our
case…” (Micah 6:1),<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Ethics_Martin_Luther_KingJr_ET543/Sermon_PublicSpeech_DarrellWolfe.docx#_ftn3" name="_ftnref3" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[3]</span></span><!--[endif]--></span></a>
and then he begins to speak for Yahweh with his indictment against his own
people. Yahweh, via Micah, reminds Israel how he birthed them as a nation and
gave them their code of honor, “do justice, and to love kindness, and to walk
humbly with your God” (Micah 6:8, LEB). Some of the things Yahweh calls Israel
out for are:<o:p></o:p></p>

<p class="MsoListParagraphCxSpFirst" style="line-height: 200%; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-language-override: normal; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>Rich taking advantage of
people and causing violence.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: 200%; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-language-override: normal; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>Lies are commonplace among
people of the nation.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: 200%; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-language-override: normal; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>Deceitful weights (social
and economic coercion of the powerless by the powerful).<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="line-height: 200%; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-feature-settings: normal; font-kerning: auto; font-language-override: normal; font-optical-sizing: auto; font-size-adjust: none; font-size: 7pt; font-stretch: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-emoji: normal; font-variant-numeric: normal; font-variant-position: normal; font-variation-settings: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span dir="LTR"></span>Aligning their thoughts
with evil leaders who should have been examples to avoid.<o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .25in;">Micah knew
something about extreme injustices committed by people who claimed to be
Yahweh’s people. In recent years, and more markedly recent weeks, the United
States of America and the US-American White Evangelical Church have been
looking an awful lot like the northern Kingdom of Isreal just prior to its
destruction. While I want to use the term ‘they’, it is ‘we’. For I was them,
and they were me, and we failed to see the heart of Yahweh and the heart of
Jesus for social justice, mercy, kindness, understanding, humble approaches to
knowledge, and the highest command to love even our enemy. As recent marches,
protests, and violence spiked, I found myself lamenting for my part of the
cause in the decades leading up to this cultural moment. I grew and changed
through deconstruction and reconstruction of my worldview through academic
biblical studies; by adopting a humble seeker mindset; and through the patience
of professors, professionals, pastors, and new friends.<o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In
a similar cultural moment, in 1955, Dr. Martin Luther King Jr. addressed a
crowd of Black-Americans who were angry at the injustices caused against them
by the dominant culture, and the most recent injustice of the arrest of Rosa
Parks for choosing not to give up her seat to a white passenger. They performed
a successful one-day boycott of the public bus system with close to one hundred
percent participation from all the black citizens of the city. Following this
day of success, the instigators of the boycott determined that one day would
not be enough, it was time to organize a movement. In his impromptu speech
given in a small church in Alabama, Dr. King inaugurated a new organization and
set the tone of the movement going forward by affirming their collective anger
at injustice and their responsibility to act in opposition to it while also
noting that Jesus said to love your enemies,<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Ethics_Martin_Luther_KingJr_ET543/Sermon_PublicSpeech_DarrellWolfe.docx#_ftn4" name="_ftnref4" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[4]</span></span><!--[endif]--></span></a> and
he quoted Booker T Washington “Let no man pull you down so low as to make you
hate him.”<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Ethics_Martin_Luther_KingJr_ET543/Sermon_PublicSpeech_DarrellWolfe.docx#_ftn5" name="_ftnref5" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[5]</span></span><!--[endif]--></span></a> Rather
than leading violent protests, which was advocated by some other movements, the
people of Montgomery, Alabama sustained a city-wide boycott of the public bus
system for one year, leading to multiple wins for the community and culminating
in a US Supreme Court decision against segregation. While my over-active sense
of justice wanted to take the more violent approach while reading about those
days, I am forced to admit that the peaceful protests ultimately won the day.<o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">This week
something wonderful happened in my approach to interacting with opposing views.
A former colleague reached out to tell me how I had fallen from grace for now
supporting the opposing side, and he tried to shout me into submission to his
way (my old way) of thinking using name calling and coded language. For a
micro-moment, I considered engaging him in the way I always have, both of us
feeding each other’s need for a dopamine fix. Then I found there was nothing in
me that wanted to pursue this path. I had no pull toward this awful habit. <o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">Meditating on the
way of love and Dr. King’s approach snuffed out this flame, at least for this
interaction. I wanted an effective strategy that could open the door for
authentic exploration. I attempted to lead the conversation into evidence,
data, and facts. But rather than simply give that data to an unwilling
participant as pearls to be trampled,<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Ethics_Martin_Luther_KingJr_ET543/Sermon_PublicSpeech_DarrellWolfe.docx#_ftn6" name="_ftnref6" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[6]</span></span><!--[endif]--></span></a> I
challenged him to find data related to his chosen topic. He immediately tried
to change the topic, but I refused to follow him to the new topic, insisting instead
that he look up the data, evidence, statistics, and facts of the situations
around which his chosen topic revolved, and then we could have a discussion. I
let him know I would move on to other topics when we fully explored this topic
together calmly using data. Ultimately, he was unwilling to engage in
data-driven analysis, and the conversation ended with no dopamine fix for
either party. <o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">What I walked away
with was a sense of peace. I sowed the seeds for peace and the opportunity to
grow, learn, and resolve in discussion (not argument). The door remains open
without burned bridges or blocked profiles. My goal was to move the
conversation toward a productive dialogue that could have given us both an
opportunity to widen our perspectives and move toward Justice, Kindness, and a
Humble walk with God. It was a good start to a new way of interacting with the
world for my part, following Dr. King’s lead.<o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In
my view, Micah is a clarion call to Yahweh’s heart, and Jesus’s message to love
our enemies is a furthering of that goal. Had the northern Kingdom of Israel
heeded this call, they may have survived for at least another generation. You
cannot stand by and allow the rich to abuse the poor if you are loving your
enemies. Dr. King’s approach followed Micah’s direction to “do justice, and to
love kindness, and to walk humbly with your God” (Micah 6:8). The boycott,
lasting one year, did not incite riots (though they had a model to do this in
the white pro-segregation organization they were compared with). They did not
burn bridges; rather, Dr. King actively made his audience aware that the goal
was reconciliation and not further division. His approach was one of active
participation while employing humility in approach. Sadly, this is not the way
I (we) often engage with high-tension topics, especially in social media. I
find a model for this in my former counselor Bob Hamp, whose posts always
account for the pain points both ‘sides’ of a contentious topic may feel while
calling both to a higher way of thinking. It is my hope to inspire that way in
myself and in my audience.<o:p></o:p></p>

<br clear="all" style="mso-special-character: line-break; page-break-before: always;" />

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<h1 style="line-height: 200%;">COMMENTARY<o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; My
intended primary audience are (1) fellow arguers – keyboard warriors – those of
us who feel the need to shout against injustice, and (2) those of us who came
out of the majority white evangelical culture, deconstructed, reconstructed,
and now feel passion to see our former friends and acquaintances make the same
changes to fight against injustice. As a writer, first and foremost, I will be
posting this on my website(s); however, if I ever found the occasion to give a
public address, speech, or sermon, I may pull this from my archives and use
this material as a jumping off point. When I read Dr. King’s recounting of his
impromptu message, and the way he juxtaposed active resistance with loving both
the harmed and those causing harm (actively or passively), it challenged me. I
saw in him the balance of the two ideals, which he himself said, “With less
than fifteen minutes left, I began preparing an outline. In the midst of this,
however, I faced a new and sobering dilemma: How could I make a speech that
would be militant enough to keep my people aroused to positive action and yet
moderate enough to keep this fervor within controllable and Christian bounds?”<a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Ethics_Martin_Luther_KingJr_ET543/Sermon_PublicSpeech_DarrellWolfe.docx#_ftn7" name="_ftnref7" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[7]</span></span><!--[endif]--></span></a><o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">As I read this, Micah
6:8 came flooding to mind, and I got to seeing his movement and ethos in terms
of Micah’s words. Dr. King actively and consciously stoked the fires of the
people to resist injustice (do justice) but he balanced this with loving
kindness toward all involved. This approach is one of humility and not pride.
Pride did enter the movement at one point, a man felt slighted for having been
passed over for a leadership role, and he put out false accusations against the
movement. This threatened to quickly derail the cohesion and momentum. Dr. King
left his vacation in another state, leaving behind his wife and child, to
return home and handle the conflict before it escalated. Here again, Dr. King
resisted the injustice while remaining in loving kindness towards the man and
those he felt wronged him. This humble approach led the man to repent and healed
the rift. Micah 6:8 may be the “how-to” to Jesus’ ethos to “love your enemies”.
<o:p></o:p></p>

<br clear="all" style="mso-special-character: line-break; page-break-before: always;" />

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<h1>BIBLIOGRAPHY<o:p></o:p></h1>

<p class="MsoBibliography"><!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_BIBL
{&quot;uncited&quot;:[],&quot;omitted&quot;:[],&quot;custom&quot;:[]}
CSL_BIBLIOGRAPHY <span style='mso-element:field-separator'></span><![endif]-->King, Martin Luther, Jr. <i>A Testament
of Hope: The Essential Writings of Martin Luther King, Jr.</i> HarperOne, 2003.<o:p></o:p></p>

<p class="MsoBibliography"><i>The
Lexham English Bible (LEB), Fourth Edition</i>. Logo Bible Software. Harris, W. H., III, Ritzema, E.,
Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., &amp; Wierenga, M. (Eds.).
Lexham Press, 2010. http://www.lexhampress.com.<o:p></o:p></p>

<p class="MsoBibliography">Walton,
John H., Victor Harold Matthews, and Mark W. Chavalas. <i>The IVP Bible
Background Commentary: Old Testament</i>. InterVarsity Press, 2000.<o:p></o:p></p>

<p class="MsoNormal"><!--[if supportFields]><span style='mso-element:field-end'></span><![endif]--><o:p>&nbsp;</o:p></p>

<div><!--[if !supportFootnotes]--><br clear="all" />

<hr align="left" size="1" width="33%" />

<!--[endif]-->

<div id="ftn1">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Ethics_Martin_Luther_KingJr_ET543/Sermon_PublicSpeech_DarrellWolfe.docx#_ftnref1" name="_ftn1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[1]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;4EHvx3Br&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;{\\i{}The
Lexham English Bible (LEB), Fourth Edition}, Logo Bible Software, Harris, W.
H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., &amp;
Wierenga, M. (Eds.) (Lexham Press, 2010), Micah 6:8,
http://www.lexhampress.com.&quot;,&quot;plainCitation&quot;:&quot;The Lexham
English Bible (LEB), Fourth Edition, Logo Bible Software, Harris, W. H., III,
Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A., &amp; Wierenga,
M. (Eds.) (Lexham Press, 2010), Micah 6:8,
http://www.lexhampress.com.&quot;,&quot;noteIndex&quot;:1},&quot;citationItems&quot;:[{&quot;id&quot;:1483,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/7TLSBX8Q&quot;],&quot;itemData&quot;:{&quot;id&quot;:1483,&quot;type&quot;:&quot;book&quot;,&quot;collection-title&quot;:&quot;Harris,
W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A.,
&amp; Wierenga, M. (Eds.)&quot;,&quot;edition&quot;:&quot;Logo Bible Software&quot;,&quot;event-place&quot;:&quot;Bellingham,
WA&quot;,&quot;publisher&quot;:&quot;Lexham
Press&quot;,&quot;publisher-place&quot;:&quot;Bellingham,
WA&quot;,&quot;source&quot;:&quot;Logo Bible
Software&quot;,&quot;title&quot;:&quot;The Lexham English Bible (LEB), Fourth
Edition&quot;,&quot;title-short&quot;:&quot;LEB&quot;,&quot;URL&quot;:&quot;http://www.lexhampress.com&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2010&quot;]],&quot;season&quot;:&quot;Copyright<span
style='mso-spacerun:yes'>  </span>, 2012, 2013 Lexham
Press&quot;}},&quot;locator&quot;:&quot;Micah
6:8&quot;,&quot;label&quot;:&quot;verse&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><i>The Lexham English Bible (LEB), Fourth
Edition</i>,
Logo Bible Software, Harris, W. H., III, Ritzema, E., Brannan, R., Mangum, D.,
Dunham, J., Reimer, J. A., &amp; Wierenga, M. (Eds.) (Lexham Press, 2010),
Micah 6:8, http://www.lexhampress.com.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn2">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Ethics_Martin_Luther_KingJr_ET543/Sermon_PublicSpeech_DarrellWolfe.docx#_ftnref2" name="_ftn2" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[2]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;tKlrhFkD&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;John
H. Walton et al., {\\i{}The IVP Bible Background Commentary: Old Testament}
(InterVarsity Press, 2000), sec. Micah: 1:1-16 Judgment Coming to Samaria and
Jerusalem.&quot;,&quot;plainCitation&quot;:&quot;John H. Walton et al., The IVP
Bible Background Commentary: Old Testament (InterVarsity Press, 2000), sec.
Micah: 1:1-16 Judgment Coming to Samaria and
Jerusalem.&quot;,&quot;noteIndex&quot;:2},&quot;citationItems&quot;:[{&quot;id&quot;:1866,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/5GTQXVID&quot;],&quot;itemData&quot;:{&quot;id&quot;:1866,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS1151.2
.W35 2000&quot;,&quot;event-place&quot;:&quot;Downers Grove,
Ill&quot;,&quot;ISBN&quot;:&quot;978-0-8308-1419-0&quot;,&quot;number-of-pages&quot;:&quot;832&quot;,&quot;publisher&quot;:&quot;InterVarsity
Press&quot;,&quot;publisher-place&quot;:&quot;Downers Grove,
Ill&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;The IVP Bible background commentary: Old
Testament&quot;,&quot;title-short&quot;:&quot;The IVP Bible background
commentary&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Walton&quot;,&quot;given&quot;:&quot;John
H.&quot;},{&quot;family&quot;:&quot;Matthews&quot;,&quot;given&quot;:&quot;Victor
Harold&quot;},{&quot;family&quot;:&quot;Chavalas&quot;,&quot;given&quot;:&quot;Mark
W.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2000&quot;]]}},&quot;locator&quot;:&quot;Micah:
1:1-16 Judgment Coming to Samaria and
Jerusalem&quot;,&quot;label&quot;:&quot;section&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->John H. Walton et al., <i>The IVP Bible
Background Commentary: Old Testament</i> (InterVarsity Press, 2000), sec.
Micah: 1:1-16 Judgment Coming to Samaria and Jerusalem.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn3">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Ethics_Martin_Luther_KingJr_ET543/Sermon_PublicSpeech_DarrellWolfe.docx#_ftnref3" name="_ftn3" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[3]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;61qt2bfn&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;{\\i{}LEB},
Micah 6:1.&quot;,&quot;plainCitation&quot;:&quot;LEB, Micah 6:1.&quot;,&quot;noteIndex&quot;:3},&quot;citationItems&quot;:[{&quot;id&quot;:1483,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/7TLSBX8Q&quot;],&quot;itemData&quot;:{&quot;id&quot;:1483,&quot;type&quot;:&quot;book&quot;,&quot;collection-title&quot;:&quot;Harris,
W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A.,
&amp; Wierenga, M. (Eds.)&quot;,&quot;edition&quot;:&quot;Logo Bible
Software&quot;,&quot;event-place&quot;:&quot;Bellingham,
WA&quot;,&quot;publisher&quot;:&quot;Lexham Press&quot;,&quot;publisher-place&quot;:&quot;Bellingham,
WA&quot;,&quot;source&quot;:&quot;Logo Bible
Software&quot;,&quot;title&quot;:&quot;The Lexham English Bible (LEB), Fourth
Edition&quot;,&quot;title-short&quot;:&quot;LEB&quot;,&quot;URL&quot;:&quot;http://www.lexhampress.com&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2010&quot;]],&quot;season&quot;:&quot;Copyright<span
style='mso-spacerun:yes'>  </span>, 2012, 2013 Lexham
Press&quot;}},&quot;locator&quot;:&quot;Micah
6:1&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><i>LEB</i>, Micah 6:1.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn4">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Ethics_Martin_Luther_KingJr_ET543/Sermon_PublicSpeech_DarrellWolfe.docx#_ftnref4" name="_ftn4" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[4]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;OmAFgxda&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Martin
Luther King Jr., {\\i{}A Testament of Hope: The Essential Writings of Martin
Luther King, Jr.} (HarperOne, 2003), 436; {\\i{}LEB}, Matt 5:43-44; Luke
6:27-35-- \\uc0\\u8220{}\\uc0\\u8220{}You have heard that it was said,
\\uc0\\u8216{}Love your neighbor\\uc0\\u8217{} and \\uc0\\u8216{}Hate your
enemy.\\uc0\\u8217{} But I say to you, love your enemies and pray for those who
persecute you,\\uc0\\u8221{} (Matthew 5:43\\uc0\\u8211{}44, LEB);
\\uc0\\u8220{}\\uc0\\u8220{}But to you who are listening I say: Love your
enemies, do good to those who hate you,\\uc0\\u8221{} (Luke 6:27, LEB);
\\uc0\\u8220{}But love your enemies, and good, and lend expecting back nothing,
and your reward will be great, and you will be sons of the Most High, because
he is kind to the ungrateful and wicked.\\uc0\\u8221{} (Luke 6:35,
LEB).&quot;,&quot;plainCitation&quot;:&quot;Martin Luther King Jr., A Testament
of Hope: The Essential Writings of Martin Luther King, Jr. (HarperOne, 2003),
436; LEB, Matt 5:43-44; Luke 6:27-35-- ““You have heard that it was said, ‘Love
your neighbor’ and ‘Hate your enemy.’ But I say to you, love your enemies and
pray for those who persecute you,” (Matthew 5:43–44, LEB); ““But to you who are
listening I say: Love your enemies, do good to those who hate you,” (Luke 6:27,
LEB); “But love your enemies, and good, and lend expecting back nothing, and
your reward will be great, and you will be sons of the Most High, because he is
kind to the ungrateful and wicked.” (Luke 6:35,
LEB).&quot;,&quot;noteIndex&quot;:4},&quot;citationItems&quot;:[{&quot;id&quot;:3204,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/93QPI3NV&quot;],&quot;itemData&quot;:{&quot;id&quot;:3204,&quot;type&quot;:&quot;book&quot;,&quot;ISBN&quot;:&quot;978-0-06-064691-2&quot;,&quot;publisher&quot;:&quot;HarperOne&quot;,&quot;title&quot;:&quot;A
Testament of Hope: The Essential Writings of Martin Luther King,
Jr.&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;King&quot;,&quot;given&quot;:&quot;Martin
Luther&quot;,&quot;suffix&quot;:&quot;Jr.&quot;}],&quot;collection-editor&quot;:[{&quot;family&quot;:&quot;Washington&quot;,&quot;given&quot;:&quot;James
M.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2003&quot;]]}},&quot;locator&quot;:&quot;436&quot;,&quot;label&quot;:&quot;page&quot;},{&quot;id&quot;:1483,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/7TLSBX8Q&quot;],&quot;itemData&quot;:{&quot;id&quot;:1483,&quot;type&quot;:&quot;book&quot;,&quot;collection-title&quot;:&quot;Harris,
W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A.,
&amp; Wierenga, M. (Eds.)&quot;,&quot;edition&quot;:&quot;Logo Bible
Software&quot;,&quot;event-place&quot;:&quot;Bellingham,
WA&quot;,&quot;publisher&quot;:&quot;Lexham
Press&quot;,&quot;publisher-place&quot;:&quot;Bellingham,
WA&quot;,&quot;source&quot;:&quot;Logo Bible
Software&quot;,&quot;title&quot;:&quot;The Lexham English Bible (LEB), Fourth
Edition&quot;,&quot;title-short&quot;:&quot;LEB&quot;,&quot;URL&quot;:&quot;http://www.lexhampress.com&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2010&quot;]],&quot;season&quot;:&quot;Copyright<span
style='mso-spacerun:yes'>  </span>, 2012, 2013 Lexham
Press&quot;}},&quot;locator&quot;:&quot;Matt 5:43-44; Luke 6:27-35 -- ““You
have heard that it was said, ‘Love your neighbor’ and ‘Hate your enemy.’ But I
say to you, love your enemies and pray for those who persecute you,” (Matthew
5:43–44, LEB); ““But to you who are listening I say: Love your enemies, do good
to those who hate you,” (Luke 6:27, LEB); “But love your enemies, and do good,
and lend expecting back nothing, and your reward will be great, and you will be
sons of the Most High, because he is kind to the ungrateful and wicked.” (Luke
6:35,
LEB)&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Martin Luther King Jr., <i>A Testament
of Hope: The Essential Writings of Martin Luther King, Jr.</i> (HarperOne,
2003), 436; <i>LEB</i>, Matt 5:43-44; Luke 6:27-35-- ““You have heard that it
was said, ‘Love your neighbor’ and ‘Hate your enemy.’ But I say to you, love
your enemies and pray for those who persecute you,” (Matthew 5:43–44, LEB);
““But to you who are listening I say: Love your enemies, do good to those who
hate you,” (Luke 6:27, LEB); “But love your enemies, and good, and lend
expecting back nothing, and your reward will be great, and you will be sons of
the Most High, because he is kind to the ungrateful and wicked.” (Luke 6:35,
LEB).<!--[if supportFields]><span style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn5">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Ethics_Martin_Luther_KingJr_ET543/Sermon_PublicSpeech_DarrellWolfe.docx#_ftnref5" name="_ftn5" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[5]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;1FQfHso7&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;King,
{\\i{}A Testament of Hope: The Essential Writings of Martin Luther King, Jr.},
436.&quot;,&quot;plainCitation&quot;:&quot;King, A Testament of Hope: The
Essential Writings of Martin Luther King, Jr.,
436.&quot;,&quot;noteIndex&quot;:5},&quot;citationItems&quot;:[{&quot;id&quot;:3204,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/93QPI3NV&quot;],&quot;itemData&quot;:{&quot;id&quot;:3204,&quot;type&quot;:&quot;book&quot;,&quot;ISBN&quot;:&quot;978-0-06-064691-2&quot;,&quot;publisher&quot;:&quot;HarperOne&quot;,&quot;title&quot;:&quot;A
Testament of Hope: The Essential Writings of Martin Luther King,
Jr.&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;King&quot;,&quot;given&quot;:&quot;Martin
Luther&quot;,&quot;suffix&quot;:&quot;Jr.&quot;}],&quot;collection-editor&quot;:[{&quot;family&quot;:&quot;Washington&quot;,&quot;given&quot;:&quot;James
M.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2003&quot;]]}},&quot;locator&quot;:&quot;436&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->King, <i>A Testament of Hope: The
Essential Writings of Martin Luther King, Jr.</i>, 436.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn6">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Ethics_Martin_Luther_KingJr_ET543/Sermon_PublicSpeech_DarrellWolfe.docx#_ftnref6" name="_ftn6" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[6]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;sAOP72Ro&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;{\\i{}LEB},
Matthew 7:6.&quot;,&quot;plainCitation&quot;:&quot;LEB, Matthew 7:6.&quot;,&quot;noteIndex&quot;:6},&quot;citationItems&quot;:[{&quot;id&quot;:1483,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/7TLSBX8Q&quot;],&quot;itemData&quot;:{&quot;id&quot;:1483,&quot;type&quot;:&quot;book&quot;,&quot;collection-title&quot;:&quot;Harris,
W. H., III, Ritzema, E., Brannan, R., Mangum, D., Dunham, J., Reimer, J. A.,
&amp; Wierenga, M. (Eds.)&quot;,&quot;edition&quot;:&quot;Logo Bible
Software&quot;,&quot;event-place&quot;:&quot;Bellingham,
WA&quot;,&quot;publisher&quot;:&quot;Lexham Press&quot;,&quot;publisher-place&quot;:&quot;Bellingham,
WA&quot;,&quot;source&quot;:&quot;Logo Bible
Software&quot;,&quot;title&quot;:&quot;The Lexham English Bible (LEB), Fourth
Edition&quot;,&quot;title-short&quot;:&quot;LEB&quot;,&quot;URL&quot;:&quot;http://www.lexhampress.com&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2010&quot;]],&quot;season&quot;:&quot;Copyright<span
style='mso-spacerun:yes'>  </span>, 2012, 2013 Lexham
Press&quot;}},&quot;locator&quot;:&quot;Matthew 7:6&quot;,&quot;label&quot;:&quot;verse&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><i>LEB</i>, Matthew 7:6.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn7">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="https://d.docs.live.net/6a09c1440da84011/_Education/Fuller%20Theological%20Seminary%20(FTS)/Courses/Ethics_Martin_Luther_KingJr_ET543/Sermon_PublicSpeech_DarrellWolfe.docx#_ftnref7" name="_ftn7" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-ascii-theme-font: major-bidi; mso-bidi-language: HE; mso-bidi-theme-font: major-bidi; mso-fareast-font-family: Aptos; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: major-bidi;">[7]</span></span><!--[endif]--></span></a> <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;gxVniMTD&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;King,
{\\i{}A Testament of Hope: The Essential Writings of Martin Luther King, Jr.},
434.&quot;,&quot;plainCitation&quot;:&quot;King, A Testament of Hope: The
Essential Writings of Martin Luther King, Jr.,
434.&quot;,&quot;noteIndex&quot;:7},&quot;citationItems&quot;:[{&quot;id&quot;:3204,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/93QPI3NV&quot;],&quot;itemData&quot;:{&quot;id&quot;:3204,&quot;type&quot;:&quot;book&quot;,&quot;ISBN&quot;:&quot;978-0-06-064691-2&quot;,&quot;publisher&quot;:&quot;HarperOne&quot;,&quot;title&quot;:&quot;A
Testament of Hope: The Essential Writings of Martin Luther King,
Jr.&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;King&quot;,&quot;given&quot;:&quot;Martin
Luther&quot;,&quot;suffix&quot;:&quot;Jr.&quot;}],&quot;collection-editor&quot;:[{&quot;family&quot;:&quot;Washington&quot;,&quot;given&quot;:&quot;James
M.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2003&quot;]]}},&quot;locator&quot;:&quot;434&quot;,&quot;label&quot;:&quot;page&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->King, <i>A Testament of Hope: The
Essential Writings of Martin Luther King, Jr.</i>, 434.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

</div><br /><br />

<span style="font-family: &quot;tempus sans itc&quot;;">Shalom&nbsp;<span face="sans-serif" style="background-color: white; color: #202122; font-size: 14px;">שָׁלוֹם</span>: Live Long and Prosper!</span>
<br />

<div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe</span>
</div>

Storyteller | Writer | Thinker | Consultant | Freelancer | Bible Nerd
<i>*Written withs some editing and research assistance from ChatGPT-4o</i>
<br /><br /><br />
