---
title: "Transcendent Community"
subtitle: "Martin Luther King Jr., Andrew Sung Park, and a blended vision for confronting racism and injustice"
date: "2026-03-17"
draft: false
description: "A final paper for ET543 comparing Martin Luther King Jr. and Andrew Sung Park on racism, resistance, healing, and the church's role in pursuing a transcendent community."
categories:
  - "Class Assignment"
  - "Seminary Course Work"
  - "Ethics"
---

_Darrell Wolfe_  
_Submitted in partial fulfillment of the requirements for the course The Theology and Ethics of Martin Luther King, Jr.: ET543_  
_Professor Phillip Allen_  
_March 17, 2026_

## Introduction

This paper evaluates the subject of racism considering the life and work of Dr. Martin Luther King Jr. and Andrew Sung Park. Both diagnosed the issues of their day and proposed ideas about how to solve them. I will discuss each in turn and then compare them together to see where they align and where they differ in their approach. Then I propose that seeing them as deepening each other's perspective is a way to create a new blended vision that evokes action to change. Following this, I reflect on my experiences, followed by an honest reflection on where I stand on this journey to resist injustice.

## Martin Luther King Jr.'s Approach

Dr. Martin Luther King Jr.'s work encircles the core issue of his time: racism and segregation. One hundred years after chattel slavery was legally abolished, the Black American was still living under segregation (an unjust separation of white and Black communities in the USA).[^1] King defines the roots of racism against Black Americans, "through forced separation from our African culture, through slavery, poverty, and deprivation, many black men lost self-respect" and in that condition the white majority "rationalized-insisting that the unfortunate Negro, being less than human, deserved and even enjoyed second-class status."[^2] That unjust status quo lasted for a time until some began chafing under their oppression and "Negro masses in the South began to reevaluate themselves-a process that was to change the nature of the Negro community and doom the social patterns of the South."[^3]

His first opportunity to act against this injustice was the arrest of Rosa Parks for not giving up her seat to a white passenger in Montgomery, Alabama. Reflecting on that incident, King said, "a righteous man has no alternative but to refuse to cooperate with an evil system."[^4] And that refusal cost King. He had been "arrested five times and put in Alabama jail. My home has been bombed twice. A day seldom passes that my family and I are not the recipients of threats of death. I have been the victim of a near-fatal stabbing." In many ways, I am the benefactor of his sacrifices, as my late wife was Black and we were an interracial couple. This would not have been free of danger if it were not for the work of King and those like him only one generation before mine.

If resistance is called for, one might ask why violent resistance is not on the table for King. To this question, he made the following observation, "violent eruptions are unplanned, uncontrollable temper tantrums brought on by long-neglected poverty, humiliation, oppression, and exploitation. Violence as a strategy for social change in America is nonexistent. All the sound and fury seems but the posturing of cowards whose bold talk produces no action and signifies nothing."[^5] Pursuing a path of nonviolent resistance, King explained, "this is not a method for cowards; it does resist" and "nonviolent resistance does not seek to defeat or humiliate the opponent, but to win his friendship and understanding."[^6] Nonviolence is also a resistance "directed against the forces of evil we are seeking to defeat, not the persons victimized by evil" and it "avoids not only external physical violence but also internal violence of spirit."[^7] King also insisted, "in your struggle for justice, let your oppressor know that you are not attempting to defeat or humiliate him, or even to pay him back... you are merely seeking justice for him as well as for yourself."[^8]

For King, love became the primary driver. When he delivered his first speech in Alabama, he decided to hinge that speech on two keys. He would "arouse the group to action by insisting that their self-respect was at stake" while also providing a counterweight with "a strong affirmation of the Christian doctrine of love."[^9] He extended his ideas further by looking to the American Dream as written in the Declaration of Independence, "all Men are created equal, that they are endowed by their Creator with certain unalienable Rights."[^10] For King, this was not a reality yet achieved but a dream for which to more closely strive. This dream was not only for white Anglo-Europeans, but for black men, Jews, Gentiles, Protestants, Catholics, and any other group identifier one can use to demarcate one human from another.[^11] King's most famous "I Have a Dream" speech begins by an appeal to the US American core foundational documents, and he says "America has defaulted on this promissory note in so far as her citizens of color are concerned."[^12] For King, the ways of God were coalesced in the two principles of resistance and love. He saw that anyone who would be made in the image of God or endowed with rights by God should have enough self-respect to resist oppression. Likewise, anyone following that God was required to do so in love, with respect for all people created in God's image. These two hinges were not at cross purposes but rather acted as support beams for his faith and his ethic.

The Montgomery Bus Boycotts do not reflect an angry mob out for revenge or retaliation, but an oppressed community brought together under one banner for a just cause. The movement was not born on the words of wise speakers alone; it was born on the backs of everyday Black Americans-men and women-who voluntarily walked instead of taking the bus, organized group ride-shares, dedicated time to meetings, passed out flyers, answered mail for the budding organization, and saw that nobody was left out wherever possible. It was these two pillars of self-respecting resistance and others-respecting love that held this movement together for a full year until it resulted in a Supreme Court decision banning segregation. It was resistance-in-unity-in-love. Dr. King died for his commitment to see this dream of equality for all humans come to pass in 1968.

## Andrew Sung Park's Approach

Andrew Sung Park wrote on the Asian American (and Korean American) experience of racism in 1996, 28 years after King's death. By the 1990s segments of society were moving forward but many lagged. One place oppression was notable, for Park, was the experience of Asian Americans. Park describes *han* as a "node of pain" that creates a "visceral, psychological, and pneumatic reaction to unbearable pain" of injustice.[^13] It comes from long-standing and intense suffering under injustice or frequent wrongs. It involves a "sense of helplessness because of overwhelming odds,"[^14] and it can be experienced by individuals and groups. Park goes on to describe the *han* of various Asian people groups throughout the 19th and 20th centuries, including racism by white Christians against Asian Christians.[^15] Meanwhile, he also demonstrates that communities with *han* (reaction to sin against them) can still also sin (create *han* in others). What is a group or culture with both *han* and sin to do if they want to move forward as a society?

*Han* creates a lived narrative inside a person or people which can become a lens or paradigm through which they see the world, always reacting to abuse whether it is present or not. It can also create a sense of entitlement whereby those with *han* sin against others. But this paradigm or model offers a path forward for communities. By gaining new lenses with which to see the world, new paradigms or models of group behavior can be developed. Park notes, "when our metaphors and models change, theology changes."[^16] Gaining a new narrative becomes a method by which to shift a culture. If the base worldview narrative in the culture shifts, the culture shifts. A community (or city, state, nation) exists by a common view of what unites them and differentiates them from others.

Park then goes on to show how various segments of society hold vision for themselves, for their neighbor, and for their future prospects.[^17] To all of these Park provides an insight: "In Confucianism, there is room for individuality not for individualism."[^18] The uniqueness of individuals contributes to the whole, but individuals must also remember that a portion of their existence and sense of self comes in how they define themselves in relationship to the whole. He then asks how divisions in the United States of America between groups can become whole and how to reduce conflicts in our differences.

Park compared models of reducing these conflicts. He cited the following: Assimilation (Anglo-Conformity) Model in which everyone becomes like the dominant group; Amalgamation Model in which all groups become a "melting pot" to create a new distinct identity together; and Cultural Pluralism Model in which all cultures remain distinct, but each contributes to what the whole becomes. He concludes with an idea of synthesis in which each group becomes part of the whole but remains distinct as well, blending into special interest groups whereby each group participates in the whole while advocating for their unique needs.[^19]

Then Park suggests a final path which he endorses. Transcendence applies to a form of transmutation/assimilation whereby the new whole transcends their individual origins, still contributes from those origins to the whole, without importing their *han* or sin into the new whole.[^20] For example, not importing racism, sexism, hierarchy, or other biases from the culture of origin while still providing their uniqueness to the whole. It is this concept that the first disciples at Pentecost employed when they each came from various nations to join the one family of God under Jesus the Anointed One. They remained people from various cultural identities but with a new higher-order identity layered over the top to unite them. They were not asked to give up their origin identities, but to accept a higher identity which acted like an umbrella over the whole. This is a both-and approach rather than an either-or approach.

A required step toward this transcendence is "Seeing Others";[^21] we must see the pain and needs of others, the violations they fear repeating upon them, and the specific needs of others in order to create an atmosphere where transcendence can be realized. Seeing each other as we are and not through our filters then becomes a way of healing *han* together. People cannot feel validated and accepted without feeling heard and understood.[^22] When the whole embraces this kind of radical acceptance and others-centered kindness, one for another, the transcendent community can become a safe haven for all, not just the dominant group. Park believed the best place for this kind of transcendent community was within a local church which then bleeds that ethos into local communities.

## Critical Comparison

King and Park dealt with a similar issue-racism-from different time periods, perspectives, and with unique experiences and *han*. Each saw injustice within their world and sought a paradigm with which to correct it. Park was more direct about the ways communities with *han* also created *han* in others, but King also rejected the ways violence was encouraged by some of his contemporaries. While he used different phrasings, it could be said that King saw the *han* of his community and wanted to avoid the ineffective reaction of creating *han* in others, seeking instead to love those with whom they were in conflict. This works well with Park's vision of a community that seeks to understand each other and see each other, coming together under a higher identity while actively resisting the importation of *han* into the new community.

King envisioned a community where oppression and injustice were actively resisted with love for the oppressed and those outside the oppressed group. He sought unity rather than sowing more disunity and division. This folds into Park's notion of transcendent community. Both sought an identity rooted in God's ways and God's higher order of vision as one community.

Perkins built on the work of King, which he calls "Beloved Community,"[^23] in which we build toward a Kingdom community that moves past racism and differences. Perkins suggests that the church is and always has been the best place to foster beloved community because it can "offer good news in broken communities," but to do this the local church has to be "committed to a place," which allows it to be vested in the outcomes of that community. The local church must be rooted in and focused on its region. If enough churches in enough regions do this, it can transform a culture into one of transcendence. In this way, Perkins is seeking to live out the vision of both Park and King.

One notable difference is Park's and King's approach to these issues. While King seeks to accomplish the one community, he does so with action focused outward. He seeks to foster community and then put that community to use fighting injustice in society at large. In this way, he seeks to force the change that needs to occur to put a stop to national injustices. This is a top-down approach. The focus is at the highest levels of the nation, which can affect the most change for the most people. It is pressing the issue forcefully but peacefully at a national level. Even within his first incident, it was a Supreme Court decision that ultimately ended the boycott.

Park also sees a vision of one community that impacts the nation, but he sees the change as happening at the local level. He makes an appeal to each local church to become a place of healing for its local community in its local context. He sees a bottom-up approach where small local changes create larger changes, eventually impacting the whole.

Another difference is that while King was an intellectual and reflected on the philosophy of his movement, Park focused mostly on the philosophy and science of understanding the problem. While he diagnosed the issue and proposed a solution, his text does not go on to itemize the ways in which he started a movement of churches across the nation (which could be an equivalent action level to King's from Park's approach). His text appears more like an intellectual exercise than a transformative movement. In this way, King's philosophy and also his life offer a more compelling story with a paradigm to follow. Had Park included this kind of action, it might offer examples with which to follow his vision in concrete terms.

From another perspective, Park deepens the work of King by providing the internal contexts that help explain why King's external approaches worked so well. With an action plan and a better way of seeing each other, one may put together a powerful movement in their own era. Without the structural change demonstrated by King, the vision of Park feels incomplete. If the two are combined, however, a path forward may not only force the changes we need in our own time but provide spaces for healing in the communities that join our movements.

## Implications for Ministry and Public Policy

In the predominantly white-majority churches and spaces I occupied for forty-plus years, I have seen a shift toward Park's view, slightly. There was a time in my former spaces where a Christian was not to seek therapy or counseling because we only needed to repent of sin and accept Jesus. This was all the healing we needed, so the narrative went. When I attended a large church in Fort Worth, Texas, however, I found a different culture. Not only were the congregants and pastors (plural) of every race and ethnic background, but therapy and counseling (healing our *han* and our sin) were encouraged. This church's Freedom Ministry was established to take groups through healing methodology and walk out that freedom with each other. For me, this was a first step toward the kind of seeing that Park envisioned. I could not see the pain of others unless I was willing to face and heal my own pain rather than ignore it.

At the same time, I did not see more than token attempts to reach the community outside the church walls. People were encouraged to come to the church and even become members before substantial investment was made in their lives. So the opinions of those outside were mixed. The church made financial contributions to local community centers and parks. But many saw the church as an overpriced clique, or even a business model. They avoided the church in favor of more open and embracing spaces.

Because of this lack of local community focus, any sense of acting against injustice or fighting the fights of King was absent. Also, because these were still predominantly white-majority spaces, the biases of the dominant group were often the lead vision. This tended to downplay or even deny the experiences and *han* of non-white communities. If a person from any community experienced financial lack, they were offered Dave Ramsey financial courses (at significant cost, though sometimes scholarshiped). Even this action was a form of systemic racism and bias. Only those with means were given the ability to gain more means. If a person or community had a history of poverty, this locked them out of even taking these courses. There was never any attempt to acknowledge the systemic ways racism was baked into the system or how generational systemic abuse amplified from the past. If someone was poor, it was because they mishandled money and needed to be taught better. There was no real account given for those whose families had never been to college and were not set up for success by their parents' and grandparents' successes. This speaks to an Assimilation (Anglo-Conformity) Model rather than a truly transcendent model. For the model to be transcendent, the *han* and sin of all communities must be seen, acknowledged, healed, and their injustices advocated for at political levels. While reconciliation with oneself, each other, and the larger community is important, it cannot be rushed past without working through *han* together as a community. Otherwise, the oneness is compromised.

When people are being kidnapped by their government off the street, the church cannot support this nor can the church stand by passively. A transcendent church stands in the gap between government abuse and its victims. Having experienced the abject failures of our immigration system firsthand with my first wife, I advocate for a full overhaul of our immigration system. From the laws, enforcement, and process down to the treatment of individuals, the immigration system is a farce and travesty. Radical reform, equal in assertiveness to the anti-segregation work of Dr. King, is required at the national level. Communities-majority and non-majority-who serve Jesus must rise in protest against the way the foreigner is treated in the United States. It is our first and highest calling as followers of Yahweh. To fail to accept the foreigner as a gift from God and our highest honor to value is a direct rejection of God's ways (Deut 10:18-19; 14:28-29; 24:17-22; 26:12-13). Likewise, the orphan, widow, and poor are also our priority. Both nationally and locally, churches and governments must make the least of these the highest priority of the nation. This includes non-majority and other oppressed communities. This is higher than national or border defense, higher than politicians' special interests, higher than any other activity of government. A failure to place a high value on these individuals and groups is a failure to honor Jesus. It is a failure to strive for a transcendent church. It is a failure to learn from Dr. King and have enough self-respect to oppose injustice. It is hard for me to know where to begin, as all my former white-majority spaces both disagree that these should be a priority and how they should be handled. But this is the vision I have, and the vision I hope for. It is my dream for the United States. I see yet another defaulted promissory note by the vision of what the United States never has been but always strived to be.

I rejected those white church spaces entirely. I have not attended a traditional church regularly since 2020. I found house meetings and smaller communities with which to form the bonds of Christian fellowship. Meanwhile, I have never found a traditional church, even among other traditions, that offers me the kind of space I envision. Yet, I lack the social skills to gather people or start a movement. I continue to search for something I can join, a Dr. King figure I can serve under. Until then, I feel more like Park. I can see and diagnose, but I do not know what to do with the burden. Maybe having the vision is the first step on a larger journey; we shall see.

## Bibliography

"Declaration of Independence." Declaration Resources Project, n.d. Accessed March 16, 2026. https://declaration.fas.harvard.edu/resources/text.

King, Martin Luther, Jr. *A Testament of Hope: The Essential Writings of Martin Luther King, Jr.* HarperOne, 2003.

Marsh, Charles, and John Perkins. *Welcoming Justice: God's Movement toward the Beloved Community*. IVP Books, 2009.

Park, Andrew Sung. *Racial Conflict and Healing: An Asian-American Theological Perspective*. Orbis Books, 1996. https://archive.org/details/racialconflicthe0000park.

[^1]: Martin Luther King Jr., *A Testament of Hope: The Essential Writings of Martin Luther King, Jr.* (HarperOne, 2003), 6.

[^2]: King, *A Testament of Hope: The Essential Writings of Martin Luther King, Jr.*, 75.

[^3]: King, *A Testament of Hope: The Essential Writings of Martin Luther King, Jr.*, 75.

[^4]: King, *A Testament of Hope: The Essential Writings of Martin Luther King, Jr.*, 429.

[^5]: King, *A Testament of Hope: The Essential Writings of Martin Luther King, Jr.*, 55.

[^6]: King, *A Testament of Hope: The Essential Writings of Martin Luther King, Jr.*, 7.

[^7]: King, *A Testament of Hope: The Essential Writings of Martin Luther King, Jr.*, 8.

[^8]: King, *A Testament of Hope: The Essential Writings of Martin Luther King, Jr.*, 10.

[^9]: King, *A Testament of Hope: The Essential Writings of Martin Luther King, Jr.*, 434.

[^10]: "Declaration of Independence," Declaration Resources Project, n.d., accessed March 16, 2026, https://declaration.fas.harvard.edu/resources/text.

[^11]: King, *A Testament of Hope: The Essential Writings of Martin Luther King, Jr.*, 208.

[^12]: King, *A Testament of Hope: The Essential Writings of Martin Luther King, Jr.*, 217.

[^13]: Andrew Sung Park, *Racial Conflict and Healing: An Asian-American Theological Perspective* (Orbis Books, 1996), 9, https://archive.org/details/racialconflicthe0000park.

[^14]: Park, *Racial Conflict and Healing: An Asian-American Theological Perspective*, 9. Park quotes Young_Hak Hyun.

[^15]: Park, *Racial Conflict and Healing: An Asian-American Theological Perspective*, 20-21.

[^16]: Park, *Racial Conflict and Healing: An Asian-American Theological Perspective*, 51.

[^17]: Park, *Racial Conflict and Healing: An Asian-American Theological Perspective*, 51-81.

[^18]: Park, *Racial Conflict and Healing: An Asian-American Theological Perspective*, 80.

[^19]: Park, *Racial Conflict and Healing: An Asian-American Theological Perspective*, 85-92.

[^20]: Park, *Racial Conflict and Healing: An Asian-American Theological Perspective*, 102-3.

[^21]: Park, *Racial Conflict and Healing: An Asian-American Theological Perspective*, 139.

[^22]: Park, *Racial Conflict and Healing: An Asian-American Theological Perspective*, 14.

[^23]: Charles Marsh and John Perkins, *Welcoming Justice: God's Movement toward the Beloved Community* (IVP Books, 2009), 6, "A time for rebuilding," by John M. Perkins, subsection: "Making Beloved Community Happen."
