---
title: 'Employee Treatment'
date: '2016-06-05T22:13:00.0020000+00:00'
draft: true
blogger_blog: 'Cornerstone Restaurants'
blogger_status: 'LIVE'
blogger_post_id: '2340586825433365979'
blogger_filename: '/2016/06/employee-treatment.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Cornerstone Restaurants/feed.atom'
---

<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
Managers must be:</div>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li>Present - Actively involved in the affairs of the restaurant. Paperwork time should be provided to managers and only done while other managers are in their place on the floor. Two Managers should be present on the floor at all times. Not seating guests, not cleaning and re-setting tables, not expo-ing, TOTALLY available to the servers and guests. When a server gets in the weeds the manager should be just as available as fellow servers to help them out. FIRST priority is the guests and servers. Find team leaders who can lead in those other areas like hosting. Each team has a clear leader for the night. Primarily the manager should be talking to guests, taking care of issues as they arise, doing computer adjustments and overseeing the operation. This can't be done if they are burried in the expo line or host stand or bussing or serving tables.</li>
<li>OPEN - Manager NEVER shoots down an idea on the fly. When an idea is presented he asks the person to write it down and place it in the idea box. These ideas are given group discussion by the management team and staff. NO idea is dismissed out of hand. Only as an entire team can an idea be deemed&nbsp;unfeasible or unnessesary. WHY must be provided for every decision, both the yes and no decisions. GROUP discussions of the entire staff should be frequent and open. Team meetings should be less about agendas and spewing out information and more about open discussions lead by an organized leader who can keep these discussions on course.</li>
<li>SUPPORT SUPPORT SUPPORT... TEAM.</li>
</ul>
