---
title: 'The History of Soda'
date: '2016-06-05T22:02:00.0020000+00:00'
draft: true
blogger_blog: 'Cornerstone Restaurants'
blogger_status: 'LIVE'
blogger_post_id: '4016847820527544830'
blogger_filename: '/2016/06/the-history-of-soda.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Cornerstone Restaurants/feed.atom'
categories:
  - 'History'
  - 'Research'
---

<br />Soda is a fun and happy drink. It's cool and refreshing.<br /><br /><a href="http://inventors.about.com/od/sstartinventions/a/soda_fountain.htm">History of Soda</a><br /><br /><div>
<blockquote class="tr_bq">
<i>"Until the 1960s, it was common for both small town and big city dwellers to enjoy carbonated beverages at local soda fountains and <a href="https://wordpress.com/od/foodrelatedinventions/a/ice_cream.htm">ice cream saloons</a>. Often housed together with a pharmacy, the soda fountain counter served as a meeting place for people of all ages. However, the popularity of soda fountains declined with the introduction of fast foods, commercial ice cream, bottled <a href="https://wordpress.com/library/weekly/aa092399.htm">soft drinks</a>, and restaurants."</i></blockquote>
<div>
<ul>
<li><a href="http://inventors.about.com/od/sstartinventions/a/soft_drink.htm">1819 The "soda fountain" patented by Samuel Fahnestock.</a></li>
<li><a href="http://inventors.about.com/od/sstartinventions/a/soft_drink.htm">1835 The first bottled soda water in the U.S.</a></li>
<li><a href="http://inventors.about.com/od/sstartinventions/a/soft_drink.htm">1850 A manual hand &amp; foot operated filling &amp; corking device, first used for bottling soda water.</a></li>
<li><a href="http://inventors.about.com/od/sstartinventions/a/soft_drink.htm">1851 Ginger ale created in Ireland.</a></li>
<li><a href="http://inventors.about.com/od/sstartinventions/a/soft_drink.htm">1861 The term "pop" first coined.</a></li>
<li><a href="http://inventors.about.com/od/sstartinventions/a/soft_drink.htm">1874 The first ice-cream soda sold.</a></li>
<li><a href="http://inventors.about.com/od/sstartinventions/a/soft_drink.htm">1876 Root beer mass produced for public sale.</a></li>
<li><a href="http://inventors.about.com/od/sstartinventions/a/soft_drink.htm">1881 The first cola-flavored beverage introduced.</a></li>
<li><a href="http://inventors.about.com/od/sstartinventions/a/soft_drink.htm">1885 Charles Aderton invented "Dr Pepper" in Waco, Texas.</a></li>
<li><a href="http://inventors.about.com/od/sstartinventions/a/soft_drink.htm">1886 Dr. John S. Pemberton invented "Coca-Cola" in Atlanta, Georgia.</a></li>
<li><a href="http://inventors.about.com/od/sstartinventions/a/soft_drink.htm">1892 William Painter invented the crown bottle cap.</a></li>
<li><a href="http://inventors.about.com/od/sstartinventions/a/soft_drink.htm">1898 "Pepsi-Cola" is invented by Caleb Bradham.</a></li>
</ul>
</div>
</div>
