---
title: 'References from: Entrepreneur.com'
date: '2016-06-05T22:06:00.0020000+00:00'
draft: true
blogger_blog: 'Cornerstone Restaurants'
blogger_status: 'LIVE'
blogger_post_id: '662336371735920789'
blogger_filename: '/2016/06/references-from-entrepreneurcom.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Cornerstone Restaurants/feed.atom'
categories:
  - 'Research'
---

This article was copied from&nbsp;<a data-mce-href="http://www.entrepreneur.com/startingabusiness/businessideas/startupkits/article73384.html" href="http://www.entrepreneur.com/startingabusiness/businessideas/startupkits/article73384.html" style="color: #00aadc; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;" target="_blank">entrepreneur.com</a>&nbsp;for my own records and research. Please click <a href="http://www.entrepreneur.com/startingabusiness/businessideas/startupkits/article73384.html">HERE </a>for the original article.<br />
<br />
<div style="text-align: center;">
-----------------------------------------------------</div>
<div style="text-align: center;">
<br /></div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
Robert V. Owens, owner of RV's Seafood Restaurant, a casual seafood restaurant in Nags Head, North Carolina, observes, "The restaurant business is a simple business that people make complicated." His formula for success is quality food, good service and great people--an approach that's worked for him for nearly a quarter century.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
To help you get started, we've compiled this thorough, but easy-to-digest, guide to starting your own food business. Whether your dream is to open a traditional American diner, a New York-style pizzeria, a Chinese&nbsp;<a data-mce-href="#" href="https://wordpress.com/pages/cornerstonerestaurants.wordpress.com#" id="KonaLink3" style="color: #00aadc;" target="undefined"><span data-mce-style="color: green;" style="color: green;">buffet</span></a>, a deli for busy lunch-goers or a local coffeehouse/hang-out spot, start your business research here.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
<strong>Generation X.</strong>&nbsp;Generation X is a label applied to those who were born between 1965 and 1977. This group is known for strong family values. While earlier generations strove to do better financially than their parents, Gen Xers are more likely to focus on their relationship with their children. They are concerned with value, and they favor quick-service restaurants and midscale operations that offer all-you-can-eat salad bars and buffets. To appeal to this market group, offer a comfortable atmosphere that focuses on value and ambience.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
<strong>Baby boomers.</strong>&nbsp;Born between 1946 and 1964, baby boomers make up the largest segment of the U.S. population. Prominent in this generation are affluent professionals who can afford to visit upscale restaurants and spend money freely. During the 1980s, they were the main customer group for upscale, trendy restaurants. In the 1990s, many baby boomer were two-income households with children. Today, those on the leading edge of the boomer generation are becoming grandparents, making them a target of restaurants that offer a family-friendly atmosphere and those that provide an upscale, formal&nbsp;<a data-mce-href="#" href="https://wordpress.com/pages/cornerstonerestaurants.wordpress.com#" id="KonaLink4" style="color: #00aadc;" target="undefined"><span data-mce-style="color: green;" style="color: green;">dining&nbsp;experience</span></a>.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
<a data-mce-href="#" href="https://wordpress.com/pages/cornerstonerestaurants.wordpress.com#" id="KonaLink0" style="color: #00aadc;" target="undefined"><span data-mce-style="color: green;" style="color: green;">Restaurants</span></a>&nbsp;are classified into three primary categories: quick-service, midscale and upscale.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
Midscale restaurants, as the name implies, occupy the middle ground between quick-service and upscale restaurants. They offer full meals but charge prices that customers perceive as providing good value. Midscale restaurants offer a range of limited- and full-service options. In a full-service restaurant, patrons place and receive their orders at their tables; in a limited-service operation, patrons order their food at a counter and then receive their meals at their tables. Many limited-service restaurants offer salad bars and buffets.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
<strong><a data-mce-href="http://www.entrepreneur.com/startingabusiness/businessideas/startupkits/article73384-2.html" href="http://www.entrepreneur.com/startingabusiness/businessideas/startupkits/article73384-2.html" style="color: #00aadc;" target="_blank">Family-style restaurants</a>.</strong>&nbsp;As the name implies, these establishments are geared toward families. Since they charge reasonable prices, they also appeal to seniors. They offer speedy service that falls somewhere between that of quick-service places and full-service restaurants. Their menus offer a variety of selections to appeal to the interests of a broad range of customers, from children to seniors. Family-style restaurant prices may be higher than those at fast-food restaurants, but these establishments provide table service to compensate. The décor of family-style restaurants is generally comfortable, with muted tones, unremarkable artwork, and plenty of booths and wide chairs. Booster seats and highchairs for children are readily available.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
<strong>Casual-dining restaurants.</strong>&nbsp;These establishments appeal to a wide audience, ranging from members of Generation Y to Generation X to baby boomers with families to seniors, and they provide a variety of food items, from appetizers and salads to main dishes and desserts. Casual-dining restaurants offer comfortable atmospheres with midrange prices. Many center on a theme that's incorporated into their menus and décor.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
<strong>Coffeehouse.</strong>&nbsp;With more than 400 billion cups consumed every year, coffee is the world's most popular beverage. But beyond the beverage itself, people frequent coffeehouses and espresso bars for a variety of reasons: to meet with friends, for a quick lunch and a drink to perk up the afternoon, or simply to start off each morning with a great cup of coffee to start off each morning. Most successful coffeehouses have heavy foot traffic and high-volume sales. The majority will serve up to 500 customers per day and manage up to five customer turnovers during the lunch hour, despite having limited floor space and modest seating capacity. Profit margins for coffee and espresso drinks are extremely high--after all, you're dealing with a product that's more than 95 percent water. At the same time, your average ticket amount is around $3, so you need volume to reach and maintain profitability. Besides specialty roasted coffee by the cup, most coffeehouses also have espresso-based drinks (cappuccinos, lattes, etc.), assorted teas, bottled water and fruit juices, along with an inviting assortment of baked goods, a selection of desserts, and coffee beans by the pound.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
For example, are you an early riser, or do you prefer to stay up late and sleep late? If you like--or at least don't mind--getting up before dawn, your niche may be a bakery or a casual breakfast-and-lunch operation. Night owls are going to be drawn to the hours required for bar-and-grill types of&nbsp;<a data-mce-href="#" href="https://wordpress.com/pages/cornerstonerestaurants.wordpress.com#" id="KonaLink2" style="color: #00aadc;" target="undefined"><span data-mce-style="color: green;" style="color: green;">restaurants</span></a>, fine-dining establishments and even pizzerias.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
Do you like dealing with the public, or are you happier in the kitchen? If you're a people person, choose a food-service business that gives you plenty of opportunity to connect with your customers. If you're not especially gregarious, you'll probably lean more toward a commercial type of business, perhaps a<a data-mce-href="#" href="https://wordpress.com/pages/cornerstonerestaurants.wordpress.com#" id="KonaLink3" style="color: #00aadc;" target="undefined"><span data-mce-style="color: green;" style="color: green;">bakery</span></a>&nbsp;or even a catering service, where you can deal more with operational issues than with people.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
Some other types of questions to ask yourself include, Do you have a passion for a particular type of cuisine? Do you enjoy a predictable routine, or do you prefer something different every day? Are you willing to deal with the additional responsibilities and liabilities that come with serving alcoholic beverages?</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
<strong>As you do this self-analysis, think about your ideal day. If you could be doing exactly what you wanted to do, what would it be?</strong></div>
<h4 style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
Working in a Restaurant</h4>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
Dealing graciously with customers and playing the role of elegant host are only part of a restaurateur's many duties. Food-service business operators spend most of their time developing menus; ordering&nbsp;<a data-mce-href="#" href="https://wordpress.com/pages/cornerstonerestaurants.wordpress.com#" id="KonaLink4" style="color: #00aadc;" target="undefined"><span data-mce-style="color: green;" style="color: green;">inventory</span></a>&nbsp;and supplies; managing personnel; creating and implementing marketing campaigns; making sure their operation is in compliance with a myriad of local, state and federal regulations; completing a wide range of paperwork; and performing other administrative chores. Certainly the financial opportunities are there--as are the fun aspects of the business--but starting, running and growing a food-service business is also hard work.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
rmed with practical experience, you're ready to put together&nbsp;<a data-mce-href="#" href="https://wordpress.com/pages/cornerstonerestaurants.wordpress.com#" id="KonaLink0" style="color: #00aadc;" target="undefined"><span data-mce-style="color: green;" style="color: green;">your&nbsp;business</span></a>&nbsp;plan--the most critical element of your restaurant. Map out everything on paper before you buy the first spoon or crack the first egg. According to industry expert Rich Melman, chair of Lettuce Entertain You Enterprises Inc., a Chicago-based company that owns, manages and consults with restaurants throughout the country, 80 percent of what will make your restaurant a success will take place before you ever open the doors.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
Your business plan should include: a clear definition of your concept; a description of your market; your menu and pricing; detailed financial information, including data on your&nbsp;<a data-mce-href="#" href="https://wordpress.com/pages/cornerstonerestaurants.wordpress.com#" id="KonaLink1" style="color: #00aadc;" target="undefined"><span data-mce-style="color: green;" style="color: green;">startup</span></a>&nbsp;capital (amount and sources) and your long-term income and expense forecasts; a marketing plan; employee hiring, training and retention programs; and detailed plans that outline how you'll deal with the challenges restaurateurs face every day. Including an exit plan in your strategy is also a good idea.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
Funding: The Holy Spirit</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
Depending on how much money you have to invest in your food-service&nbsp;<a data-mce-href="#" href="https://wordpress.com/pages/cornerstonerestaurants.wordpress.com#" id="KonaLink0" style="color: #00aadc;" target="undefined"><span data-mce-style="color: green;" style="color: green;">business</span></a>&nbsp;and the particular type of business you choose, you can spend anywhere between $30,000 and $1.5 million on a facility.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
Not every food-service operation needs to be in a retail location, but for those that do depend on retail traffic, here are some factors to consider when deciding on a location:</div>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>Anticipated sales volume.</strong>&nbsp;How will the location contribute to your sales volume?</li>
</ul>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>Accessibility to potential customers.</strong>&nbsp;Consider how easy it will be for customers to get into&nbsp;<a data-mce-href="#" href="https://wordpress.com/pages/cornerstonerestaurants.wordpress.com#" id="KonaLink1" style="color: #00aadc;" target="undefined"><span data-mce-style="color: green;" style="color: green;">your&nbsp;business</span></a>. If you are relying on strong pedestrian traffic, consider whether or not nearby businesses will generate foot traffic for you.</li>
</ul>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>The rent-paying capacity of your business.</strong>&nbsp;If you've done a sales-and-profit projection for your first year of operation, you will know approximately how much revenue you can expect to generate, and you can use that information to decide how much rent you can afford to pay.</li>
</ul>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>Restrictive ordinances.</strong>&nbsp;You may encounter unusually restrictive ordinances that make an otherwise strong site less than ideal, such as limitations on the hours of the day that trucks can legally load or unload.</li>
</ul>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>Traffic density.</strong>&nbsp;With careful examination of food traffic, you can determine the approximate sales potential of each pedestrian passing a given location. Two factors are especially important in this analysis: total pedestrian traffic during business hours and the percentage of it that is likely to patronize your food service business.</li>
</ul>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>Customer parking facilities.</strong>&nbsp;The site should provide convenient, adequate parking as well as easy access for customers.</li>
</ul>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>Proximity to other&nbsp;<a data-mce-href="#" href="https://wordpress.com/pages/cornerstonerestaurants.wordpress.com#" id="KonaLink2" style="color: #00aadc;" target="undefined"><span data-mce-style="color: green;" style="color: green;">businesses</span></a>.</strong>&nbsp;Neighboring businesses may influence your store's volume, and their presence can work for you or against you.</li>
</ul>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>History of the site.</strong>&nbsp;Find out the recent history of each site under consideration before you make a final selection. Who were the previous tenants, and why are they no longer there?</li>
</ul>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>Terms of the lease.</strong>&nbsp;Be sure you understand all the details of the lease, because it's possible that an excellent site may have unacceptable leasing terms.</li>
</ul>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong><a data-mce-href="#" href="https://wordpress.com/pages/cornerstonerestaurants.wordpress.com#" id="KonaLink3" style="color: #00aadc;" target="undefined"><span data-mce-style="color: green;" style="color: green;">Future&nbsp;development</span></a>.</strong>&nbsp;Check with the local planning board to see if anything is planned for the future that could affect your business, such as additional buildings nearby or road construction.</li>
</ul>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
Layout and design are major factors in your restaurant's success. You'll need to take into account the size and layout of the dining room, kitchen space, storage space and office. Typically, restaurants allot 40 to 60 percent of their space to the dining area, approximately 30 percent to the kitchen and prep area, and the remainder to storage and office space.</div>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>Dining area.</strong>&nbsp;This is where you'll be making the bulk of your money, so don't cut corners when designing your dining room. Visit restaurants in your area and analyze the décor. Watch the diners; do they react positively to the décor? Is it comfortable, or are people shifting in their seats throughout their&nbsp;<a data-mce-href="#" href="https://wordpress.com/pages/cornerstonerestaurants.wordpress.com#" id="KonaLink4" style="color: #00aadc;" target="undefined"><span data-mce-style="color: green;" style="color: green;">meals</span></a>? Note what works well and what doesn't.</li>
</ul>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
Much of your dining room design will depend on your concept. It will help you to know that studies indicate that 40 to 50 percent of all sit-down customers arrive in pairs; 30 percent come alone or in parties of three; and 20 percent come in groups of four or more.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
To accommodate the different groups of customers, use tables for two that can be pushed together in areas where there is ample floor space. This gives you flexibility in accommodating both small and large parties. Place booths for four to six people along the walls.</div>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>Production area.</strong>&nbsp;Too often, the production area in a restaurant is inefficiently designed--the result is a poorly organized kitchen and less than top-notch service. Keep your&nbsp;<a data-mce-href="#" href="https://wordpress.com/pages/cornerstonerestaurants.wordpress.com#" id="KonaLink5" style="color: #00aadc;" target="undefined"><span data-mce-style="color: green;" style="color: green;">menu</span></a>&nbsp;in mind as you determine each element in the production area. You'll need to include space for receiving, storage, food preparation, cooking, baking, dishwashing, production aisles, trash storage, employee facilities and an area for a small office where you can perform daily management duties.</li>
</ul>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
Arrange your food production area so that everything is just a few steps away from the cook. Your design should also allow for two or more cooks to be able to work side by side during your busiest hours.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
Every prospective employee should fill out an application--even if it's someone you already know, and even if that person hsa submitted a detailed resume. A resume is not a signed, sworn statement acknowledging that you can fire the person if he or she lies about his or her background; the application, which includes a truth affidavit, is. The application will also help you verify the applicants' resumes, so you should compare the two and make sure the information is consistent.</div>
<div style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px; margin-bottom: 24px;">
Here are some tips to help you find and keep great people:</div>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>Hire right.</strong>&nbsp;Take the time to thoroughly screen applicants. Be sure they understand what you expect of them. Do background checks. If you can't do this yourself, contract with a HR&nbsp;<a data-mce-href="#" href="https://wordpress.com/pages/cornerstonerestaurants.wordpress.com#" id="KonaLink1" style="color: #00aadc;" target="undefined"><span data-mce-style="color: green;" style="color: green;">consultant</span></a>&nbsp;to do it for you on an as-needed basis.</li>
</ul>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>Create detailed job descriptions.</strong>&nbsp;Don't make your employees guess about their responsibilities.</li>
</ul>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>Understand wage-and-hour and child labor laws.</strong>&nbsp;Check with your own state's Department of Labor to be sure you comply with regulations on issues such as minimum wage (which can vary depending on the age of the workers and whether they're eligible for tips), and when teenagers can work and what tasks they're allowed to do.</li>
</ul>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>Report tips properly.</strong>&nbsp;The IRS is very specific about how tips are to be reported; for details, check with your accountant or contact the&nbsp;<a data-mce-href="http://www.irs.gov/" href="http://www.irs.gov/" style="color: #00aadc;" target="_blank">IRS</a>(or see your local telephone directory for the number).</li>
</ul>
<ul style="color: #3d596d; font-family: Merriweather, Georgia, 'Times New Roman', Times, serif; font-size: 15px; line-height: 25.5px;">
<li><strong>Provide initial and ongoing training.</strong>&nbsp;Even experienced workers need to know how things are done in your restaurant. Well-trained employees are happier, more confident and more effective. Plus, ongoing training builds loyalty and reduces turnover. The&nbsp;<a data-mce-href="http://www.restaurant.org/" href="http://www.restaurant.org/" style="color: #00aadc;" target="_blank">National Restaurant Association</a>can help you develop appropriate employee training programs.</li>
</ul>
