---
title: 'What is a Creative?'
date: '2015-10-19T05:56:00.0050000+00:00'
draft: true
blogger_blog: 'Creatives'' Space'
blogger_status: 'LIVE'
blogger_post_id: '4273605576099958958'
blogger_filename: '/2015/10/what-is-creative.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Creatives_ Space/feed.atom'
categories:
  - 'Creatives'
---

<br />
<h3>
Calling all Artists and Creatives!
</h3>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
<iframe allowfullscreen="" frameborder="0" height="281" mozallowfullscreen="" src="https://player.vimeo.com/video/122366308" webkitallowfullscreen="" width="500"></iframe></div>
<div style="text-align: center;">

<a href="https://vimeo.com/122366308">Calling All Artists (from SeedsConf 2015)</a> from <a href="https://vimeo.com/cotm">Church on the Move</a> on <a href="https://vimeo.com/">Vimeo</a>.</div>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
<br /></div>
<h4>
Searching online dictionaries results in a myriad of definitions:</h4>
<br />
<blockquote class="tr_bq">
<i>Having the ability to create, come up with new or original ideas, innovative, artistic, make things, imaginative, create rather than imitate,&nbsp;</i></blockquote>
<br />
<h4>
Read these verses, and meditate on them for just a moment:</h4>
<br />
<blockquote class="tr_bq">
<i>Ephesians 3:9</i><i>and to bring to light what is the administration of the mystery which for ages has been hidden in God who created all things;</i><i><br /></i><i><br /></i><i>Psalm 104:30</i><i>You send forth Your Spirit, they are created; And You renew the face of the ground.</i><i><br /></i><i><br /></i><i>Proverbs 8:30</i><i>Then I was beside Him, as a master workman; And I was daily His delight, Rejoicing always before Him,</i></blockquote>
<blockquote class="tr_bq">
<i>Psalm 19:1</i><i>The heavens are telling of the glory of God; And their expanse is declaring the work of His hands.</i></blockquote>
<blockquote class="tr_bq">
<i>Amos 4:13</i><i>For behold, He who forms mountains and creates the wind And declares to man what are His thoughts, He who makes dawn into darkness And treads on the high places of the earth, The LORD God of hosts is His name.</i></blockquote>
<br />
<h4>
God is THE Creative!&nbsp;</h4>
<br />
Everything on earth, every sunset, mountain, flower, it's all Him. God could have created one color, but he created thousands of shades and hues. Just as Wisdom/Jesus was by the Father's side, creating earth. So we too, are by Jesus' side creating for His glory on this earth.<br />
<br />
We were created by our Father, to create.<br />
<br />
<blockquote class="tr_bq">
<b><i>Creating with the Creator, to bring about creations that bring people to Him.</i></b></blockquote>
<br />
Creatives are those who cannot help but to create. They may create in a variety of forms and formats, but they create nonetheless. Music, Painting, Writing, Inventions, they are all the byproducts of creating.<br />
<br />
Creatives create things. They see the world not as it is, but as it could be. They see beauty where you saw ugliness, form what you saw raw material, power where you saw weakness...<br />
<br />
Creatives are limitless, free thinkers, free flowing, rule breakers.<br />
<br />
Creatives are the only reason things ever get better... Innovators.<br />
<br />
<br />
Darrell Wolfe, Wolfe Family Creations