---
title: 'Creatives Space - Your source for Learning, Supplies and Support'
date: '2015-09-16T14:57:00.0030000+00:00'
draft: true
blogger_blog: 'Creatives'' Space'
blogger_status: 'LIVE'
blogger_post_id: '3590456442004780361'
blogger_filename: '/2015/09/creatives-space-your-source-for.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Creatives_ Space/feed.atom'
categories:
  - 'Learning'
  - 'Supplies'
  - 'Support'
---

<br />
<br />
<head>

</head>

<br />
<h3 style="font-family: Georgia; font-size: 12pt; margin: 0in;">
Creatives Space</h3>
<br />
<h4 style="font-family: Georgia; font-size: 12pt; margin: 0in;">
Your source for
Learning, Supplies and Support</h4>
<br />
<div style="font-family: Georgia; font-size: 12pt; margin: 0in;">
</div>
<br />
Flavia and I were driving along, chatting about the future. We've always wanted to open a creative store, for Art Supplies, but so much more. And do it better than the one's that are already out there (JoAnn's, Michaels, Hobby Lobby). It's like those places stopped innovating 50 years ago. They stopped imagining what being a source for Creative's could mean.<br />
<br />
As of today (10/18/15), this doesn't exist. But I'm casting the vision of what it could be:<br />
<br />
<h4>
Learning:</h4>
<br />
Your source for learning. In house courses taught by life local artisans in the field of your choice. Fine Art, Craft, Models, Music, and More. Courses will be recorded by professional videographers, so that they can be uploaded and sold online after the fact.<br />
<br />
<br />
<h4>
Supplies:</h4>
<br />
You can come touch, and get hands on instruction or guidance, multiple supplies. Everything from paint to fabric, Photos to Music. If you want to order online, we can do that too.<br />
<br />
<br />
<b>Support</b>:<br />
<br />
We can connect you with other sources to help you walk in your creative endeavors. We're not the only shop in town, and why should we be? Creatives work best when we are in community, not competition. If I serve your needs best, great! If I need to hook you up with another resources that can serve your needs better, great! How can we support YOUR creativity?<br />
<br />
<br />
<b>The Store:</b><br />
<br />
<br />
<b>Creative Corners</b><br />
<ul>
<li>Arenas/Sections for each type of Creative Endeavor. Think Best Buy.</li>
<li>Crochet, Knitting, Bolts of Fabric, Sewing Supplies</li>
<li>Photography and Framing Supplies</li>
<li>Artist - Paint, Pencil, Easels, etc</li>
<li>Model Kits, Train Kits, Craft Supply, Make Stuff - Stuff,</li>
<li>"Writers Block" - An area for writers, journals, materials on publishing, Scrivener, etc.</li>
<li>Technology - Artist pen/pads (Bamboo), computers, tablets, software, etc..</li>
</ul>
<br />
<b>Connection Corner</b><br />
<ul>
<li>Coffee Shop, Couches, Hang Out for Creatives to Connect </li>
</ul>
<br />
<b>Creative Classes</b><br />
<ul>
<li>Instructor Led courses on creative topics. You can pay for the class. You can also buy the course after the fact (online shop). Proceeds split between CreativeSpace and the Instructor.</li>
</ul>
<br />
<b>Creatives' Resource Center</b><br />
<ul>
<li>We will connect you to other stores and services that serve Creatives, like <a href="http://ketoscreative.com/" target="_blank">KetosCreative</a>. We will bring guides, materials, books, manuals, software, and more into the mix. Will will connect you to other instructors and others who serve this market (collaboration not competition)..</li>
</ul>
<br />
<div>
<br /></div>
<div>
Should you ever stumble upon this post... I hope this vision makes you as excited as it made us. I also hope that we're more excited about this vision three years from now, as we were today.&nbsp;</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
Darrell Wolfe, Wolfe Family Conceptions.&nbsp;</div>
