---
title: 'Stars and Stripes (Working Title) 3'
date: '2011-12-04T04:16:00.0010000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '3280844432557106320'
blogger_filename: '/2011/12/stars-and-stripes-working-title-3.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Stars and Stripes (Working Title)'
---

...<br />
<br />
It was now 11:33pm... and Erik suddenly woke up. He was wide awake. As though he hadn't been sleeping at all. The coffee machine wouldn't be starting for another few minutes and the alarm wouldn't be ringing for at least 15 minutes or so. But he felt awake. Wide awake. More awake than he'd felt in a very long time, as he typically only slept a few hours a night and worked&nbsp;incessantly.<br />
<br />
Erik sat up in the chair and looked about the room. Nothing seemed out of the ordinary. Nothing seemed disturbed or moved. But he suddenly felt very, very awake. He also felt a strong sense of anticipation combined with&nbsp;foreboding. At the same time he didn't feel like some stalker would burst through the door at any minute or anything like that. Then, faintly at first, a small light&nbsp;appeared&nbsp;in front of his eyes. He thought that a firefly must have gotten through the screen door. But the light grew brighter and brighter.<br />
<br />
Then with a flash it was so bright he couldn't see anything, at all. Eyes open or closed, it didn't matter, he saw nothing. Then as quickly as it came it was gone. His eye sight started to return and the room came into focus. Erik sat back and rubbed his eyes and waited for the room to quit spinning in his mind. He closed his eyes and opened them several times. Finally his vision cleared. As he started to sit back the silence was broken by a soft low voice coming from the couch&nbsp;across&nbsp;from him. "Hello Erik." Erik jumped; nearly out of his skin! The voice wasn't shocking in and of itself. It was actually quite calm. But he had been alone. Who was there. He turned to look at the couch and there was a man, dressed in a white suit with blue and red pin stripes. It could have been a patriotic suit, but it was also first class. There was nothing tacky about it. He wore a matching bowler cap and one hand rested on a cane. At second glance the cane looked like a walking stick more than a cane. It was longer than the average cane.<br />
<br />
The man sat back, comfortably on the couch and let Erik adjust to the sight. He was too stunned to say anything. "Don't worry, your not crazy..." the man said. "No I'm not here to attack you either..." the man said.<i> It was as if he was responding my very thoughts</i>. "Yes I'm really here..." <i>Ok now that was just&nbsp;weird&nbsp;how did he know...</i> "Because I can read your thoughts as though they were spoken."<br />
<br />
A moment of silence then passed as the two men examined one another and stared into&nbsp;each others&nbsp;eyes. There was something kind about this man's eyes. As though he were older than he looked and maybe wiser. "OK..." Erik started. "I'm not crazy, or&nbsp;hallucinating, or whatever... " How did you get in here and what do you want? And what sort of device creates a flash that bright? Who do you work for?" Erik realized that was too many questions and the man must have a point in being here so he stopped and waited.<br />
<br />
The man in the suit spend a moment or two studying Erik before responding. "I work for me. There is no device. How I got here is not important." The man let that sink in. "In fact, who I am in not important either, for now. You wouldn't understand right now anyway. Let me just say that I am well connected and I've been watching you for some time. What I'm interested in is truth young man. Nothing more, nothing less. You are talented beyond the skill of others in your field. You have insight that surpasses those within the limits of government bureaucracies. However..." The man took a few moments to let that settle. "I am not interested in your talents or education as much as I am&nbsp;interested&nbsp;in your insight. You have been created with the ability to see what others fail to see. But you give too much credit to that which you see and fail to see things that are right in front of you. Therefore that which you see could lead you to believe that, that which you see is true when it is in fact false. Do you see?"<br />
<br />
"I think so?" Replied Erik<br />
<br />
"Good!" the man continued with a lift of excitement. "You don't yet but you will. I came here to warn you. You are about to see things that are not what they appear to be. Take a healthy and liberal dose of&nbsp;skepticism&nbsp;into the next few months. Don't believe your eyes, your instruments, or your colleagues. However, trust your heart and your belly. When you get the gut feeling that something isn't right, don't just brush it off. Follow that instinct. You will find more than you saw at first. Trust that feeling. Do you understand?"<br />
<br />
"Yes, I believe so." replied Erik.<br />
<br />
"Good!" the man said again with a warm grin, he was an excitable fellow if ever there was one. He waited a few moments and studied&nbsp;Erik's&nbsp;face again. "Your coffee is waiting for you, enjoy the meteor shower ok?"<br />
<br />
FLASH! Again with the bright lights...<br />
<br />
Erik woke up to the smell of expensive&nbsp;Colombian&nbsp;coffee and a buzzing sound coming from the granite counter top. It was his alarm going off. It had been a dream! But it felt so real, more real than any dream he'd ever experienced. It must be the mountain air combined with a few bottles of&nbsp;Guinness. It was time to get up and get the recorder on before the meteorite shower started up.<br />
<br />
The dream quickly faded but something gnawed at him about it still. He'd have to reconsider those dream books and see if your mind really did try to communicate with you through sleep. What could it mean though. What was with the red, white, and blue? "I guess I need to take fourth of&nbsp;July&nbsp;more seriously..." He mused to himself.<br />
<br />
...<br />
<br />