---
title: 'A new room. Silence, negative sound.'
date: '2014-04-28T04:21:00.0000000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '5965294578431834614'
blogger_filename: '/2014/04/a-new-room-silence-negative-sound.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Writing Practice'
  - 'White Noise'
---

<h3 style="text-align: center;">
04/27/2014 Writing Practice</h3>
<br />
After what seems 10 days, as per the marks on the box, Ash wakes to the sound of his food being delivered for breakfast. He eats in silence. He doesn't even hear the noise they've been pumping into the room for 10 days. When he is done he places his tray on the shelf and it disappears into the wall again.<br />
<br />
*Click* The sound in the overhead turns off. A voice, deep and gravely. "Good, good Mr Ashlund. You've done excellent. Now we head to the second phase of our test. In the next room you will find a chair. Please take a seat. You won't be here long. Less than a day by our last calculations. Then you are free to go."<br />
<br />
A slit in the wall opens to a dimly lit room, if you could call it that. The floor is stretch chicken wire, over triangles of foam cut at different angles. The walls, ceiling, all made of the same substance. One chair, bolted to the floor. It looks comfortable enough. Like a dentist chair. Seeing no other option, he takes a seat.<br />
<br />
The silence is deafening, immediately. If you have ever clapped your hand, and heard the reflections of that clap come back to you from the walls in a room. Imagine that you heard no such reflection. Imagine that it was just the sound of the two hands coming together that came directly to your ear and nothing else. It's negative sound. It's as though the sound is sucked right out of you, so that all you can hear is your own heart beat, and breathing. Even your ears, so accustomed to sound begin to make their own ringing.<br />
<br />
Ash takes a seat. The lights are turn out. Cool air is keeping the room a comfortable 74*F.<br />
<br />
After the silence of 10 days, all of Ash's racing thoughts of subsided. He's moved past wondering where he is, when he'll leave, he's now just him. Alone with his thoughts. And increasingly, his past.<br />
<br />
Alone, in the dark now, with no sound of any kind, negative sound. He sits. Lays back in the reclining dentist chair, and he waits. He waits. He sleeps.<br />
<br />
***<br />
<br />
<i>Ash... Ash...&nbsp;</i><br />
<br />
He sits up. How long was he asleep? Is he still asleep? How would you know in dark silence?<br />
<i><br /></i>
<i>Ash... we know about you Ash... We know who you are... what you've done... how could you...&nbsp;</i><br />
<br />
Ash shakes his head... the voices vanish. What as that?<br />
<br />
<br />
***<br />
<br />
"He's incredible. Getting a trained military man, accustomed to being alone for days and weeks, a survival expert. He is already outlasted every scientist, street volunteer, and audio geek we've ran through these tests. Many of them didn't make it through the prep room, but we've never had anyone last over and hour, he's been in there for three and just now he's starting to show signs of a dimensional tear. You are a genius!"<br />
<br />
"Yes, Dr. I am! That is why you brought me here. To fix this reject project and bring something valuable out of it. Keep me appraised of any changes."<br />
<br />
The white lab coated man turned and left the room. His tuft of white hair bouncing along as he walked away.<br />
<br />
<br />
******<br />
<br />
Thank you for reading. I hope you enjoyed this. I'd love to make a community with this project. If you would like to add, comment on, critique, or otherwise participate... that would be great!<br />
<br />
Please include any information about yourself, your blog/wesbite/amazon author page that you want to share with the community also.<br />
<br />
<i>* I may include "Affiliate Links" which means I earn a commission when you buy products I link to. To see my full about page and disclosures:&nbsp;<a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a></i><br />
<br />
<a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br />
<br />
To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br />
<br />
For Non-Fiction writing by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell G. Wolfe: Click Here</a><br />
<br />
<br />
<br />
<br />
<br />
<div style="clear: both; float: left; padding-bottom: 10px; text-align: right;">
<br /></div>
