---
title: 'Randy Elwood – Sr Audio-Medical Equipment Technician.'
date: '2014-03-08T04:49:00.0030000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '2559559578186858878'
blogger_filename: '/2014/03/randy-elwood-sr-audio-medical-equipment.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Writing Practice'
  - 'White Noise'
---

***<br />
“Goooood… Did you see that? His blood pressure spiked and he stood up. Eye dilated. Something is starting. We’re almost there…” The voice said. Technician Randy Elwood took note of the time and date. <br />
***<br />
Randy Elwood. Sr Medical Equipment Technician at Briar Psychiatric Center. Randy has three PHD’s. <br />
<ul>
<li>Audio Physics (Science of Sound) – Just because he could never stop dissecting music. Thought it would be fun to study sound. Turned out to be his favorite degree. Though, he wasn’t sure what he could do with it, other than make great You Tube Video Soundtracks, which is how he paid for most of his training and school. </li>
<li></li>
<li>One in Group Behavior – Maybe he could figure out how to interact with these humans he lived with. He’d never been much good throughout his life. Turns out the degree only made him better able to understand and predict human behavior, not mimic it to any realist believable degree. </li>
<li></li>
<li>Human Anatomy-Biology – Maybe understanding the body better he could understand the mind and social patterns. Not so much. Just made for more awkward conversations are the few parties he tried to attend. </li>
</ul>
Although incredibly bright, Randy was a perpetual student. His professors advised he leave the comforts of school for the real world. Only so much can be learned in the library. With a few phone calls he was connected to to the Briar Psychiatric Center to assist in the on going study of sound waves on the human mind.&nbsp;&nbsp; <br />
He didn’t mind the gig. He spent most of his time in a lab, by himself, reading and watching monitors. Not bad for $100,000 a year job. Especially not bad for the first paying job he’d had outside of school. Real job anyway, he still made a few sound tracks now and then. This was a great gig for someone with his specialty: “Not interacting with other people.” <br />
Randy checked the monitors one last time before returning to his book. It was assigned reading by his new employer. Supposed to help the workers understand the “culture” of the company. <br />
“Unlocking the Paranormal Mind. A study of how the human mind’s unlocked potential”, By Dr Richard T. Briar. <br />
Couldn’t be worse than doing nothing, or that whole semester he took wasted reading about the breeding behavior of wombats! <br />
*** <br />
<br />
<br />
******<br />
<br />
Thank you for reading. I hope you enjoyed this. I'd love to make a community with this project. If you would like to add, comment on, critique, or otherwise participate... that would be great!<br />
<br />
Please include any information about yourself, your blog/wesbite/amazon author page that you want to share with the community also.<br />
<br />
<i>* I may include "Affiliate Links" which means I earn a commission when you buy products I link to. To see my full about page and disclosures:&nbsp;<a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a></i><br />
<br />
<a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br />
<br />
To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br />
<br />
For Non-Fiction writing by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell G. Wolfe: Click Here</a><br />
<br />
<br />
<br />
<br />