---
title: 'Location Sketch: Sriklan Islands'
date: '2014-10-28T02:04:00.0010000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '5363769342086565828'
blogger_filename: '/2014/10/location-sketch-sriklan-islands.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Location Sketch'
  - 'White Noise'
---

<div class="WordSection1">  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><a href="http://authorfun.blogspot.com/2013/12/whereabouts.html"><o:p></o:p></a></span></p>  <p class="MsoNormal"><span class="MsoHyperlink"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><a href="http://authorfun.blogspot.com/2013/12/whereabouts.html">Sri-Klan Islands (need a new name)</a></span></span><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">Somewhere in the Pacific Ocean, south of Hawaii, even with Australia and Mexico. Large grouping of small islands, hidden from even the most sophisticated maps.<o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <h2>Climate:<o:p></o:p></h2>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">Beaches are comprised of Quartz Sand, white in color, and cool the touch, even on the hottest day. Tropical, near equator?  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">Buildings, once used by the Japanese during WWII prior to the attack on Pearl Harbor, now owned and used by the USA for Top Secret training exercises. Only the most elite train   here, and even they don&#8217;t know where it is. The buildings are kept in full operational use, and often rebuilt after training causes collateral damage.<o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <h2>Landscape:<o:p></o:p></h2>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">Peppered with Cherry Blossom Trees, Palms, Oak, and Spruce. A reminder of many former residents.<o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">No large beasts, there are monkeys, birds, reptiles, sea turtles.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">Each Island is within visibility of another, barely. One could swim from one to another, however, white sharks are known to travel out this far and visit nearby reefs. Attacks   are rare, but can happen when blood is in the water. <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <h2>Technology:<o:p></o:p></h2>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">The island is fully wired with generators and satellites, wireless cameras and motion sensors are kept running 24 hours a day.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  </div>  