---
title: 'Location Sketch: White Room'
date: '2014-10-28T19:01:00.0010000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '5836170865482651201'
blogger_filename: '/2014/10/location-sketch-white-room.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Location Sketch'
  - 'White Noise'
---

<div class="WordSection1">  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">Overview:<o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">The white room is located inside a research facility owned by the XXXXXX. The facility is ran by Dr. XXXXXX, and his assistant XXXXX. The room is 8X8 square, made from  <a href="http://en.wikipedia.org/wiki/Titanium">titanium</a> and painted with white high gloss paint. The titanium plates cover each wall, the floor, and the ceiling, and are nearly seamless, so that the room appears to be a solid white box from end to end,   top to bottom. <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">There is no apparent door. The door exists, but it cannot be seen or felt until it is opened. There is a place to lay down, which slides out from the wall. Three times a day,   a small door, no larger than an iPad, opens, and a tray of food is inside. Box inside this door is equally seamless, and back lit by a small LED light. The door stays open until the tray is placed back, and then closes.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">There is a table, which also rises on it’s own from the ground as one solid piece, no legs, just a large rectangular box that rises out of the ground. On the table is a small   white cardboard box, wrapped in white paper. Inside is a white iPod, with one track, which gives a brief explanation (which may/may not be true), and instructions on what will happen next.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">From the ceiling, there is white noise, pumped through speakers into the room. It is noticeable at first, as echoes off the smoth metalic reverberant walls, but it quickly fades into the background and cannot even be heard or detected.   Inside that white noise, is a series of frequencies that are not audible to human ears, but have shown signs of being able to make the human spirit more malleable, or open, to the spiritual realm.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;">This room is meant as a way to wash the candidate of extraneous interference from the outside world, before entering the Dark Room.  <o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoListParagraph" style="text-indent:-.25in;mso-list:l0 level1 lfo1"><!--[if !supportLists]--><span style="font-size:12.0pt;font-family:Symbol"><span style="mso-list:Ignore">·<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span></span><!--[endif]--><span lang="EN">Titanium’s most common compound, <a href="http://en.wikipedia.org/wiki/Titanium_dioxide" title="Titanium dioxide">  titanium dioxide</a>, is a popular <a href="http://en.wikipedia.org/wiki/Photocatalysis" title="Photocatalysis">  photocatalyst</a> and is used in the manufacture of white pigments.<sup id="cite_ref-HistoryAndUse_4-0"><a href="http://en.wikipedia.org/wiki/Titanium#cite_note-HistoryAndUse-4">[4]</a></sup></span><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p></o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  <p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Georgia&quot;,&quot;serif&quot;"><o:p>&nbsp;</o:p></span></p>  </div>  