---
title: 'The Plight of the Black Pen'
date: '2014-01-24T13:46:00.0020000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '7649035204253227165'
blogger_filename: '/2014/01/the-plight-of-black-pen.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Writing Practice'
---

<h3 style="text-align: center;">
2014/01/24 Writing Practice</h3>
<div>
<br /></div>
It's laying on the desk, next to several other pens. The only difference is it's color. Black and Silver pick up more of the light from the room than the other pens do. Maybe this is why he is more aware of his plight then they are. They lay there, simple, content to do nothing. Some are prettier, but less functional than he is. But they all lay, unchosen, for now. Is Black the only pen that chooses to ponder his fate, his plight, his meaning in this life?<br />
<div>
<br /></div>
<div>
Each pen is different, but this pen feels more different. He lays there. Incapable of moving until The Author chooses him for his craft. He was not chosen today. He will remain until he is either chosen, or discarded. The pen has no choice but to wait, and find out his fate. To see if The Author will use him today.</div>
<div>
<br /></div>
<div>
&nbsp;Allas, The Author gets up to leave, off to work for the day. The pen was not chosen this day... but there is hope, tomorrow may be different. The pen will keep being who the pen is. Because one day, he just knows it, the pen will fulfill his destiny!&nbsp;</div>
<div>
<br /></div>
<div>
Darrell<br />
<br />
<br />
Thank you for reading. I hope you enjoyed this. I'd love to make a community with this project. If you would like to add, comment on, critique, or otherwise participate... that would be great! Please include any information about yourself, your blog/wesbite/amazon author page that you want to share with the community also.<br />
<br />
<br />
<a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://twitter.com/DarrellWolfe" target="_blank">@DarrellWolfe</a><br />
<br />
To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br />
<br />
For Non-Fiction writing by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell G. Wolfe: Click Here</a><br />
<br />
Any work not otherwise attributed is Copy Right Darrell G. Wolfe<br />
<br />
All Rights Reserved © Darrell G. Wolfe<br />
<br />
<b>Disclosure of Material Connection: Some of the links in the post above are “affiliate links.” This means if you click on the link and purchase the item, I will receive an affiliate commission. I may also have received one or more of the products or services mentioned above for free in the hope that I would mention it on my blog. Regardless, I only recommend products or services I use personally and believe will add value to my readers. I am disclosing this in accordance with the Federal Trade Commission’s&nbsp;<a href="http://www.gpo.gov/fdsys/pkg/CFR-2003-title16-vol1/content-detail.html" target="_blank">16 CFR, Part 255</a>: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.” A Big Thank You to&nbsp;<a href="http://michaelhyatt.com/five-ways-to-comply-with-the-new-ftc-guidelines-for-bloggers.html" target="_blank">Michael Hyatt</a>&nbsp;for helping us Bloggers with these new legal disclosure requirements.</b><br />
<br />
<br /></div>
