---
title: 'Street Noise'
date: '2014-09-23T05:36:00.0010000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '3370659039818881022'
blogger_filename: '/2014/09/street-noise.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Writing Practice'
  - 'White Noise'
---

<p dir=ltr>He sat alone in a leather bound chair, in the corner. Always in the keep your back to the wall, be near the most exits, but never too visible. Training never stopped. Even here, in Podunk, Nowhere, USA. He had specifically looked for a city that was large enough to blend into, small enough to be off radar, and not a frequent tourist area. He enjoyed the northwest, so Ash chose a city he'd never been to, in the right quadrant of the country.</p>
<p dir=ltr>Out of the corner of his eye, Ash thought he saw two men dressed in all black duck behind a car. " Now I know I need a his vacation. I'm seeing black ops teams in small town Oregon. "</p>
<p dir=ltr>Some commotion outside broke his self absorbed train of thought... People were turning and staring. He heard yelling. Ash stepped outside to see what wax happening. An man in torn clothes and graying beard, was standing on top of a pick up truck screaming at noon one in particular. </p>
<p dir=ltr>"You always did love Mother best... I know... That's why... That's why she died you know... You couldn't keep your mouth shut..."</p>
<p dir=ltr>On he went, incoherently. Ash took a step closer, the then the man turned to him and in a deeper, more gutteral voice: "YOU... Child of the King... What do you want with us? You ho have seen?"</p>
<p dir=ltr>As the Looney man stood staring a large creature suddenly came into view, as though he were made of smoke taking form. It was 8 feet tall , at least. But it had three heads on its neck, many more protruding from various parts of its body. It was staring at Ash directly. As it tilted it's head&#160; to the left, the gray haired loon tilted in unison. They both tilted their heads back and laughed menacingly, "He doesn't even know what he is.... Ha ha ha ha..."</p>
<p dir=ltr>With that the&#160; creature disappeared and the man leaped down off the truck, and ran at Ash. It took all his training to keep from being pinned down. The wiry man was stronger than he looked. Ash was so surprised that he let out a "Jesus!" But it also came from down inside of him too, as though he meant to say it,but didn't premeditate it.</p>
<p dir=ltr>The wiry man stepped back as though he had been punched. That was all Ash needed. In 30 seconds he had the man hog tied with his own belt. By now the police were just arriving. "Charlie's at it again... take him in..." Three fairly big men put a muzzle on the old man,and&#160; threw him, rather harshly, into the back of the squad car. Turning to Ash, the more seasoned cop replied "Those were some moves Marine. Would you like to press charges?"</p>
<p dir=ltr>" USAF, and no... No harm done." </p>
<p dir=ltr>"You be in town long? We could use a guy like you on the team."</p>
<p dir=ltr>"Just on vacation. Thanks."</p>
<p dir=ltr>With a small town friendly waive and smile, the squad cars took off North. Ash was left non the worse for wear... On the outside anyway..." He started to get up and walk away when he realized he'd dropped his coffee cup in all the commotion. It was spilled all over the floor. </p>
<p dir=ltr>"Why don't you let me get you another one, on the house." Ash looked up to see a man in a plaid shirt and jeans sitting nearby.</p>
<p dir=ltr>"My name is Jim Struthers, this is my coffee shop, it's on the house."<br><br></p>
