---
title: 'Time Passed'
date: '2014-02-24T03:52:00.0000000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '2462645196919492320'
blogger_filename: '/2014/02/time-passed.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Writing Practice'
---

<h3 style="text-align: center;">
02/23/2014 Writing Practice</h3>
<br />
<span style="font-family: Calibri, sans-serif;">Ash woke up to 
the soft whiz of the cabinet door opening beside him. Food is served. Breakfast, 
by the smell of it. He had only two ways to keep track of time. An enclosed room 
with no windows or natural light prevents any external data. Time runs together 
without a point of reference. Ash had two. The type of food being served. And 
his internal body clock which has been regulated for decades now.</span><br />



<br />
<div>
<span style="font-family: Calibri, sans-serif;"><br /></span></div>
<div>
<span style="font-family: Calibri, sans-serif;">Slight nail marks on the box.</span></div>
<br />
<br />
<br />
******<br />
<br />
Thank you for reading. I hope you enjoyed this. I'd love to make a community with this project. If you would like to add, comment on, critique, or otherwise participate... that would be great! Please include any information about yourself, your blog/wesbite/amazon author page that you want to share with the community also.<br />
<br />
<br />
<a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br />
<br />
To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br />
<br />
For Non-Fiction writing by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell G. Wolfe: Click Here</a><br />
<br />
<br />
<br />
<i>Disclosure of Material Connection: Some of the links in the post above are “affiliate links.” This means if you click on the link and purchase the item, I will receive an affiliate commission. I may also have received one or more of the products or services mentioned above for free in the hope that I would mention it on my blog. Regardless, I only recommend products or services I use personally and believe will add value to my readers. I am disclosing this in accordance with the Federal Trade Commission’s&nbsp;<a href="http://www.gpo.gov/fdsys/pkg/CFR-2003-title16-vol1/content-detail.html" target="_blank">16 CFR, Part 255</a>: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.” A Big Thank You to&nbsp;<a href="http://michaelhyatt.com/five-ways-to-comply-with-the-new-ftc-guidelines-for-bloggers.html" target="_blank">Michael Hyatt</a>&nbsp;for helping us Bloggers with these new legal disclosure requirements.</i><br />
<br />
<br />
<div style="clear: both; float: left; padding-bottom: 10px; text-align: right;">
<br /></div>
