---
title: 'Character Sketch: Dr Richard T. Briar'
date: '2014-12-28T07:23:00.0020000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '7302293665669087504'
blogger_filename: '/2014/12/character-sketch-dr-richard-t-briar.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'White Noise'
---



<br />
<div style="border-width: 100%; direction: ltr;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.3916in;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.3916in;">

<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Author of:<span style="mso-spacerun: yes;">&nbsp; </span>“Unlocking the Paranormal Mind. A study of
how the human mind’s unlocked potential”, By Dr Richard T. Briar. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Richard Briar was a
scientist, who specialized in the paranormal. His birth name was Niklaus von
Klaus</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
He was named after
the patron saint of Switzerland. Niklaus von Flue, also known as Brother Klaus,
who died in 1487. Brother Klaus was known as a spiritual advisor and pastor to
both rural and rich; however, was also known for heretical practices of mysticism.
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Dr. Briar's mother
was a mystic from Switzerland, and his father was a German scientist during
WWI. Dr Niklaus von Klaus was a German Nazi scientist during WWII, who fled to
Switzerland, and then to the UK, after changing his name and accent. He now
operated under the alias of Dr. Richard Briar, tenured professor (retired) of
Cambridge University, and founder of the Briar Psychiatric Center, Colorado
Springs, CO. , dedicated to studying the farthest reaches and capabilities of
the human mind. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
There were exactly
zero people alive who knew Dr. Briar's original identity, or the extent of his
true plans.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
It would be
interesting to see just how far this rabbit hole would go…. What secrets the
unlocking the human mind would reveal. It was necessary to operate on the
fringe of the law, after all, we all know how bureaucracies hold back the
spirit of innovation! </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
&nbsp;******</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<span style="font-weight: bold;">Niklaus von Flue, Nicholas of Flühe</span> or <span style="font-weight: bold;">brother Klaus</span> (* <a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/1417&amp;usg=ALkJrhg4R0hNoWbINKnOOAjEMvXr3wCQCw">1417</a>
; † <a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/21._M%25C3%25A4rz&amp;usg=ALkJrhg6UEvyxQlBliVx3pQUBq7XsFrTCg">21
March</a> <a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/1487&amp;usg=ALkJrhi7SY-gS8rLYlX_1U43Bfw23nXdzQ">1487</a>
in <a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Fl%25C3%25BCeli-Ranft&amp;usg=ALkJrhjcq3VhWbEfOVpDxOSDs01GmQQvlA">Flüeli</a>
at <a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Sachseln&amp;usg=ALkJrhj49mLeR0yvaj4nfSGVCXKh4FE_EA">Sachseln</a>
in the canton of <a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Kanton_Obwalden&amp;usg=ALkJrhjDlMjGpy611UhUIxFnsqYcm5mq6w">Obwalden</a>
) was a <a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Schweiz&amp;usg=ALkJrhgC4TbYggj3r-ij8TR1ENwE5SimJw">Swiss</a>
<a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Eremit&amp;usg=ALkJrhjyV_b-ay9KOZPrgLbcQHi4IZR3sQ">hermit</a>
, <a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Askese&amp;usg=ALkJrhhzqJ4u78g2VU-KG-xKHMWZAqZnSA">ascetic</a>
and <a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Mystik&amp;usg=ALkJrhiM_DYiVWRRtSulY8H2tKq099J-2A">mystic</a>
. He is the patron saint of Switzerland.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Niklaus_von_Fl%25C3%25BCe&amp;usg=ALkJrhg49HZRF0nkWXbl5N4OPvyGPgXZBw">http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Niklaus_von_Fl%25C3%25BCe&amp;usg=ALkJrhg49HZRF0nkWXbl5N4OPvyGPgXZBw</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<span style="background: #E6ECF9;">On March 21, 1487 Brother Klaus died after a hard
agony on the floor of his cell.</span></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Niklaus_von_Fl%25C3%25BCe&amp;usg=ALkJrhg49HZRF0nkWXbl5N4OPvyGPgXZBw">http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Niklaus_von_Fl%25C3%25BCe&amp;usg=ALkJrhg49HZRF0nkWXbl5N4OPvyGPgXZBw</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Niklaus von Flue
gained widely reputation as <a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Seelsorger&amp;usg=ALkJrhi_leZjQbvmjg7YGcbhMl-5yToMGA">pastor</a>
and spiritual advisor, not only for the rural population, but also as a guide
for foreign heads of state in Europe in the 15th century. So says a special
envoy of the Duchy of Milan, in a letter to <a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Ludovico_Sforza&amp;usg=ALkJrhhWE83ImHcF9mcR2NDffqVD0m40Yg">Ludovico
Sforza</a> of visits to the hermit, where he discussed political issues, and
the Duke thanked in the response for its gracious greetings. <a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Niklaus_von_Fl%25C3%25BCe&amp;usg=ALkJrhg49HZRF0nkWXbl5N4OPvyGPgXZBw#cite_note-3"><span style="vertical-align: super;">[3]</span></a> </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Nicholas of Flue was
also interested in a mystic in worldly things. He watched the political events
and was asked for advice on such matters. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Niklaus_von_Fl%25C3%25BCe&amp;usg=ALkJrhg49HZRF0nkWXbl5N4OPvyGPgXZBw">http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Niklaus_von_Fl%25C3%25BCe&amp;usg=ALkJrhg49HZRF0nkWXbl5N4OPvyGPgXZBw</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
The origins of <a href="http://en.wikipedia.org/wiki/Nazism">Nazism</a> and its relation to the <a href="http://en.wikipedia.org/wiki/Occult">occult</a> have been a part of <a href="http://en.wikipedia.org/wiki/Popular_culture">popular culture</a> since
at least 1959. There are documentaries and books on the topic, including <a href="http://en.wikipedia.org/wiki/The_Morning_of_the_Magicians"><span style="font-style: italic;">The Morning of the Magicians</span></a> (1960) and <a href="http://en.wikipedia.org/wiki/Holy_Lance#Trevor_Ravenscroft"><span style="font-style: italic;">The Spear of Destiny</span></a> (1972). Historian <a href="http://en.wikipedia.org/wiki/Nicholas_Goodrick-Clarke">Nicholas
Goodrick-Clarke</a> analyzed the topic in <a href="http://en.wikipedia.org/wiki/The_Occult_Roots_of_Nazism"><span style="font-style: italic;">The Occult Roots of Nazism</span></a> in which he
argued there were links between some ideals of <a href="http://en.wikipedia.org/wiki/Ariosophy">Ariosophy</a> and Nazi ideology.
He also analyzed the problems of the numerous popular "occult
historiography" books written on the topic. He sought to separate <a href="http://en.wikipedia.org/wiki/Empiricism">empiricism</a> and <a href="http://en.wikipedia.org/wiki/Sociology">sociology</a> from the
"Modern Mythology of Nazi Occultism" that exist in many books which
"have represented the Nazi phenomenon as the product of arcane and demonic
influence". He considered most of these to be "sensational and
under-researched".<a href="http://en.wikipedia.org/wiki/Nazism_and_occultism#cite_note-1"><span style="vertical-align: super;">[1]</span></a></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="http://en.wikipedia.org/wiki/Nazism_and_occultism">http://en.wikipedia.org/wiki/Nazism_and_occultism</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
**</div>
</div>
</div>
</div>
