---
title: 'Is Someone There?'
date: '2014-03-08T04:49:00.0010000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '503756674530296463'
blogger_filename: '/2014/03/is-someone-there.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Writing Practice'
  - 'White Noise'
---

Day 10. Ash woke from another nap. It was hard to keep up his physical strength in an enclosed room. He was pushing his work out routine hard. Every morning, and afternoon he would work out different parts of his body, always keeping cardio and core strength training in his daily routine. The hash marks on the cardboard box were divided into days, and muscle groups.&nbsp; Knowing that resting was just as important to muscle training as work outs he took a nap after his morning routine, and rested early each evening. At least, he was thinking it was evening. The lights never dimmed. Food rations were plentiful, but the same each day. So much of the same. If anyone of lesser mind had been kept in this environment he was sure they’d have gone mad.<br />
The voice giving instructions was the only thing he had to hang on to. He re-listened to the iPod over and over the first few days. Trying to get some kind of handle on the situation. Was the any memory of having volunteered for this? Is it even possible he would have? He was quite sure he wouldn’t, unless ordered to. Ash was a go and do person, not a lab rat. But maybe this was the type of person they needed… on and on he thought in circles for those first few days. Now, by day 10, he was over it. Now he would just keep his strength in top shape and get ready for his break out. Sooner or later they would have to open a door, or make a move. He couldn’t stay here forever. Could he?<br />
<em>What was that?</em> There was movement. Just a shadow really. But even a shadow was new in this room.<br />
<em>“Ash… AAAsssshhhhh…”&nbsp; </em>The sound was like a whisper on the wind. Carried from far away. Not near.&nbsp; <br />
What… Who… Nothing. He stood and looked around the room. For several moments he stood still. Barely breathing. Was this a trick. Were they messing with him through the loud speakers? After an eternity he finally assumed he must have been dozing into a dream. Still… that voice sounded familiar. Who was that? <br />
<br />
***<br />
<br />
<br />
<br />
******<br />
<br />
Thank you for reading. I hope you enjoyed this. I'd love to make a community with this project. If you would like to add, comment on, critique, or otherwise participate... that would be great!<br />
<br />
Please include any information about yourself, your blog/wesbite/amazon author page that you want to share with the community also.<br />
<br />
<i>* I may include "Affiliate Links" which means I earn a commission when you buy products I link to. To see my full about page and disclosures:&nbsp;<a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a></i><br />
<br />
<a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br />
<br />
To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br />
<br />
For Non-Fiction writing by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell G. Wolfe: Click Here</a><br />
<br />
<br />
<br />
<br />