---
title: 'Unknown Antagonist'
date: '2014-12-30T14:43:00.0000000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '2684644938139442719'
blogger_filename: '/2014/12/unknown-antagonist.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'White Noise'
---



<br />
<div style="border-width: 100%; direction: ltr;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.6041in;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.6041in;">

<div style="border-width: 100%; direction: ltr;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.6041in;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.6041in;">

<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Someone is brought
in by Dr. Briar to fix the project with sound and spirit world experiments. He
is superior in intellect to most, he is a strong strategist, and he has motives
that are not entirely purely scientific. His motives differ from Dr. Briar's in
that sense. He's RICH… but so rich that making more money has no appeal to him.
He'd be just as likely to drop a billion on a failing business just for the fun
of turning it around as he would to just watch the money burn and spin that
business wildly out of control. He's bored… he likes the power of anonymity. He
made Dr. Briar think that Dr. Briar sought out his help; when in fact, he
orchestrated the whole thing. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
Who is this
Antagonist? Does he have a name? Will we ever know it? How much mystery is
good, vs how much do we need to build flesh and blood into this guy and make
him more real, menacing? Then again, the unknown has it's own fear built in.<span style="mso-spacerun: yes;">&nbsp; </span></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
He motivated by
money, in the sense that once should have gain, value, profit of some kind of
out one's expenditure of energy. That value added need not be monetary though.
Power. Control. Can the other dimensions, what some call the spirit world, be
accessed? Can they be manipulated? Can they be controlled? These are the real
power, the real questions. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
***</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
"Yes, Dr. Briar
I am! That is why you brought me here. To fix this reject project and bring
something valuable out of it. Keep me appraised of any changes."</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
The black suited man
turned and left the room. His tuft of white hair bouncing along as he walked
away.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
****</div>
</div>
</div>
</div>
</div>
</div>
</div>
