---
title: 'Prodigal Son Returns'
date: '2014-03-24T05:13:00.0030000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '354732701083121645'
blogger_filename: '/2014/03/prodigal-son-returns.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Prodigal Blessings'
---

<h3 style="text-align: center;">
03/09/201 Writing Practice</h3>
<br />
<h4>
Prodigal Son Story Idea...</h4>
<br />
Idea Sparked by this Devotional:<br />
<br />
<a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=117&amp;user_id=darrellwolfe&amp;version=1">https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=117&amp;user_id=darrellwolfe&amp;version=1</a><br />
<br />
My Journal Entry:<br />
<br />
<blockquote class="tr_bq">
What if... What if the prodigal son came home as a son, just like the story goes. Then afterward the Father convinces the brother to treat him as family, as guest, and feed and shelter him, but still all the "things" of the household belong to the older brother. There is no inheritance left for the younger one, his was spent. &nbsp;</blockquote>
<blockquote class="tr_bq">
What happens next? Could he, having learned from his mistakes, take a job. Not on his families estate because he doesn't want his Brother to feel taken from. From a local estate that knows the family. Maybe he even takes a job in a different form altogether, like in the market. With that job he tried to pay his brother for his keep but "duty" prevents him from accepting anything from younger brother. So he saves, and saves, and invests, eventually becoming even wealthier than his brother, like a Joseph in modern times... &nbsp;</blockquote>
<blockquote class="tr_bq">
Interesting story idea.&nbsp;</blockquote>
<br />
<h4>
The Original Story</h4>
<br />
<b><a href="https://www.bible.com/bible/1/luk.15.kjv" target="_blank">LUKE 15</a></b><br />
<br />
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v11" data-usfm="LUK.15.11" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">11</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;">And he said,&nbsp;</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">A certain man had two sons:</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v12" data-usfm="LUK.15.12" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">12</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">And the younger of them said to his father, Father, give me the portion of goods that falleth to me. And he divided unto them his living.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v13" data-usfm="LUK.15.13" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">13</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">And not many days after the younger son gathered all together, and took his journey into a far country, and there wasted his substance with riotous living.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v14" data-usfm="LUK.15.14" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">14</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">And when he had spent all, there arose a mighty famine in that land; and he began to be in want.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v15" data-usfm="LUK.15.15" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">15</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">And he went and joined himself to a citizen of that country; and he sent him into his fields to feed swine.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v16" data-usfm="LUK.15.16" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">16</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">And he would fain have filled his belly with the husks that the swine did eat: and no man gave unto him.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v17" data-usfm="LUK.15.17" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">17</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">And when he came to himself, he said, How many hired servants of my father's have bread enough and to spare, and I perish with hunger!</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v18" data-usfm="LUK.15.18" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">18</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">I will arise and go to my father, and will say unto him, Father, I have sinned against heaven, and before thee,</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v19" data-usfm="LUK.15.19" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">19</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">And am no more worthy to be called thy son: make me as one of thy hired servants.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v20" data-usfm="LUK.15.20" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">20</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">And he arose, and came to his father. But when he was yet a great way off, his father saw him, and had compassion, and ran, and fell on his neck, and kissed him.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v21" data-usfm="LUK.15.21" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">21</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">And the son said unto him, Father, I have sinned against heaven, and in thy sight, and am no more worthy to be called thy son.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v22" data-usfm="LUK.15.22" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">22</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">But the father said to his servants, Bring forth the best robe, and put it on him; and put a ring on his hand, and shoes on his feet:</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v23" data-usfm="LUK.15.23" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">23</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">And bring hither the fatted calf, and kill it; and let us eat, and be merry:</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v24" data-usfm="LUK.15.24" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">24</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">For this my son was dead, and is alive again; he was lost, and is found. And they began to be merry.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v25" data-usfm="LUK.15.25" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">25</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">Now his elder son was in the field: and as he came and drew nigh to the house, he heard musick and dancing.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v26" data-usfm="LUK.15.26" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">26</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">And he called one of the servants, and asked what these things meant.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v27" data-usfm="LUK.15.27" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">27</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">And he said unto him, Thy brother is come; and thy father hath killed the fatted calf, because he hath received him safe and sound.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v28" data-usfm="LUK.15.28" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">28</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">And he was angry, and would not go in: therefore came his father out, and intreated him.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v29" data-usfm="LUK.15.29" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">29</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">And he answering said to his father, Lo, these many years do I serve thee, neither transgressed I at any time thy commandment: and yet thou never gavest me a kid, that I might make merry with my friends:</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v30" data-usfm="LUK.15.30" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">30</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">But as soon as this thy son was come, which hath devoured thy living with harlots, thou hast killed for him the fatted calf.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v31" data-usfm="LUK.15.31" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">31</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">And he said unto him, Son, thou art ever with me, and all that I have is thine.</span></span></span></div>
<div class="p" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #444444; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;">
<span class="verse v32" data-usfm="LUK.15.32" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #666666; font-size: 17px; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">32</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; font-size: 17px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #cc0000; font-size: 17px; margin: 0px; padding: 0px;">It was meet that we should make merry, and be glad: for this thy brother was dead, and is alive again; and was lost, and is found.</span></span></span></div>
<br />
<h4>
The New 21st Century Version - According to Darrell Wolfe - Loose Translation</h4>
<br />
<h3>
<a href="http://en.wikipedia.org/wiki/Prologue" target="_blank">Prologue</a></h3>
Once upon a time, in Laguna Nigel, CA a man had two sons. The youngest son asked the father to split the estate now, rather than waiting until his death many years from now. The father was more than happy to do it. All he lived for was his children. Winston Churchill Montgomery III, The Father, gave to each son his portion of the inheritance.<br />
<br />
According to family custom and tradition, the youngest son (Dean) received 1/3 and the oldest (Richard) 2/3 of the estate. When the lawyers verified that the Father was of good health and sound mind, they processed the request.<br />
<br />
One day, a few months after the estate was divided, and all the assets belonging to him were liquidated, the youngest son departed to "Find Himself".<br />
<br />
The 1/3 that Dean took with him was worth quite a bit. He spent time in Vegas, Paris, New York, and other places. He toured the world, went to concerts, spent time in Dubai. His portion of the estate was large enough that he was gone for years. The occasional post on Facebook told the family all they needed to know about where he was, but he hardly ever bothered even sending a text to his Father, who watched the social feeds with growing concern.<br />
<br />
Meanwhile, back at home the eldest Son managed the estate and affairs of the family, doing his duty to keep the family name clean and reputation separate from his youngest brothers debauchery. Often paying news editors to keep headlines down, such as the cover story from two years ago which read:<br />
<blockquote class="tr_bq">
"Dean Montgomery, youngest son and heir of the Montgomery and Company Estate, a Fortune 500 Company, was seen naked, painted blue, hanging from a hot air balloon last night on March 17th, apparently in staged attempt to bring awareness to Scottish-Irish abuse by England. He had the letters IRA painted on his rear, which he says stands for Irish Republican Army. Some believe this may have had a <a href="http://www.merriam-webster.com/dictionary/double%20entendre" target="_blank">double entendre</a>, as his family is well known for their investment and stock in financial companies, especially those in majoring in retirement services."</blockquote>
<br />
13 Years went by. Then, slowly, the Facebook Posts, News Photo's, and other channels of information on the youngest son dried up. There were less and less posts. "Going to Al's to watch the game..." was the last post on his Facebook account. That was 1.5 Year ago.<br />
<blockquote class="tr_bq">
<i>Then without warning, Dean shows up this evening, about four hours ago. He arrives on the back of a pick up truck, wearing rags, smelling like a sewer. He obviously hadn't shaved in over a year, and he looked like the worst kind of homeless man, the one you walk far around when you notice him nearby</i>.&nbsp;</blockquote>
<blockquote class="tr_bq">
<i>Then Father comes out and instead of disowning him, or at least giving a disgusted rebuke and sending him to a rehab center, he hugs him, and throws a last minute party. Of all the nerve</i>.&nbsp;</blockquote>
Richard fumes back and forth as he recounts the activities to his finance' Rebeka.<br />
<br />
<blockquote class="tr_bq">
<i>I had to find out when I drove up to the estate, finding a huge, unplanned, party underway. I wasn't notified to have the guest list checked with security, or anything. I didn't even get a text letting me know anything had happened. The entire event was explained to me by Jose, our night gate guard.</i></blockquote>
<blockquote class="tr_bq">
<i>Father had the gall to wonder why I wasn't joining the party. Of all the nerve, the ridiculous reactions to have! Here this kid has been out wasting one third of Father's hard earned fortune, blowing himself up across new channels, creating nightmares of bad press for us, living like a gypsy. Then he shows up, money spent, looking for a hand out and Father throws a party? Unbelievable!&nbsp;</i></blockquote>
Rebeka nodded. Richard collapsed on the couch, lays across her lap exhausted, as she scratches his back. She quietly pulls out her phone with one hand while she scratches her back with the other. She quietly deletes the invite from her Facebook Page.<br />
<br />
***<br />
<h4>
The Next Day</h4>
<br />
The embers still dying in the outside fireplace, the household has gone to bed. The elder brother never did come inside. He left, heading back to his finance's house. Father was asleep. The crowds were gone. The only ones left awake were Jose, the night Guard out front, Dean who was still in awe over his Dad's reaction, and Buddy. The old dog was still alive, amazing.<br />
<br />
So what now? He still didn't have any money. He'd intended to ask his Dad to let him work for him, but his Dad wouldn't hear of it. He had a place to stay, a warm bed, new clothes, fresh shower, and more good than he knew what to do with. It had been so long since he'd felt this good.<br />
<br />
He'd make up with Richard, he always came around. He'd apologize good and proper, let him know he intended to earn his keep and not take anything else from the family. But now what? The "Prodigal Son Returns!", What's next?<br />
<br />
Dean would have to figure that out tomorrow. He was just grateful to be alive, warm, clean, and fed. Dad insisted he take a shower and shave before anybody arrived, and arrive they did! Amazing how many people will show up for free food and fun at the Montgomery's!<br />
<br />
He was just so amazed at this unexpected welcome... it felt great to be called "son" again.<br />
<br />
What's next could wait until tomorrow. Tonight, he was going to bask in...Home. Home is a good feeling. It's been far too long.<br />
<br />
<br />
<br />
******<br />
<br />
Thank you for reading. I hope you enjoyed this. I'd love to make a community with this project. If you would like to add, comment on, critique, or otherwise participate... that would be great!<br />
<br />
Please include any information about yourself, your blog/wesbite/amazon author page that you want to share with the community also.<br />
<br />
<i>* I may include "Affiliate Links" which means I earn a commission when you buy products I link to. To see my full about page and disclosures:&nbsp;<a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a></i><br />
<br />
<a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br />
<br />
To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br />
<br />
For Non-Fiction writing by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell G. Wolfe: Click Here</a><br />
<br />
<br />
<br />
<br />
<br />
<div style="clear: both; float: left; padding-bottom: 10px; text-align: right;">
<br /></div>
