---
title: 'Super Powers: The Spiritual and Supernatural Laws of White Noise'
date: '2015-12-14T22:32:00.0000000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '3980292284389018068'
blogger_filename: '/2015/12/super-powers-spiritual-and-supernatural.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
---

<br />
Every world, especially fictional ones, must follow the rules. They need not be the rules we all know. Maybe in this world everything falls down, not up? But there must be rules and they must be followed. Otherwise your fiction becomes "incredible", or unbelievable.<br />
<br />
<br />
<strong><span style="background-color: yellow;">*** World Under Contruction ***</span></strong><br />
<br />
<h3>
World Rules</h3>
<h4>
The following rules will serve the the world of White Noise:</h4>
<ul>
<li>&nbsp;The powers' source is exposure to vibration frequencies, most of which are not audible to the human ear.</li>
<ul>
<li>Vibrations create vinrations which either bring in tune with or out of tune with LIFE force.&nbsp;</li>
<li>LIFE is nothing more than being at harmony with THE vibration that runs through all matter (living or not).&nbsp;</li>
<li>Light, Sound, Pressure Waves from bombs, are all forms of vibrations.</li>
<li>Ex, Healing is the cells natural ability to self cure being sped up by an environment in tune with The Vibration.</li>
<li>THE Virbration is 7.77 hz. </li>
<ul>
<li>This brings things into harmony with The Vibration, all elements are properly functioning when turned as a harmonic of 7.77 hz</li>
</ul>
<li>The dissonant (which brings opposite results) is 6.66 hz.</li>
<ul>
<li>This brings chaos, disharmony, dissonance, confusion, resulting in destruction and death. Even this harmony can be useful (ex, causing cancer&nbsp;cells to restore&nbsp;apoptosis, programed cell death).&nbsp;</li>
</ul>
</ul>
<li>Affected by:</li>
<ul>
<li>The powers can be enhanced by exposure to more good frequencies.</li>
<li>They can be hindered by dissonant frequencies.</li>
<li>Think the harpist for the prophet.</li>
</ul>
<li>The powers endued by the Experiment would only be those that the bible either demonstrates, eludes to, or at least does not exclude.&nbsp;</li>
<ul>
<li>Therefore, walking through walls (yes), Laser beams coming from the eyes (maybe? the prophets do have fire coming from their mouths), Atomantium Claws, (no).&nbsp;</li>
</ul>
<li>The powers will be named by biblical names, scientific names, and magic/comic names.&nbsp;</li>
<ul>
<li>Ex, Vision vs Precognition.&nbsp;</li>
</ul>
<li>The powers are always intended for good, but not always used for good. </li>
<ul>
<li>They can be abused.</li>
</ul>
<li>The powers are endued upon anyone that is open to the supernatural, not just those who want to do good.&nbsp;</li>
<ul>
<li>"He poured out his spirit on all mankind."&nbsp;</li>
</ul>
<li>Kids are more easily affected than adults.</li>
<li>All powers are available to all people; however, most do not realize it. </li>
<ul>
<li>And not all powers come as quickly or naturally to all people. </li>
<li>Some people, through design, exposure, or experience find that they lend more easily to one than another. </li>
<li>But in a pinch, it's possible for anyone to manifest any power. </li>
</ul>
</ul>
<br />
<br />
<br />
<h3>
Power Rules</h3>
<br />
<h4>
The approved powers (list growing).&nbsp;</h4>
<br />
<b>Wisdom </b>- Superhuman mentality - Innate capability - hyper-intelligence<br />
<ul>
<li>Ability to know or understand something without the need of studying or previous experience.</li>
<li>Ability to see through the siutation to the right answer.</li>
<li>Ability to have intelligence quotient far above that of a genius level. </li>
<ul>
<li>This ability can be so evolved that its user can gain psychic abilities (psychokinesis, telepathy, etc.) and resist both mind control and other psionic attacks.</li>
</ul>
<li>Knowing what to do, without having previous training, would appear as hyper-intelligence.</li>
<li><strong>Oranazition - Puzzle Solving - Technopathy - </strong></li>
</ul>
<br />
<br />
<br />
<b>Knowledge </b>- &nbsp;Empathy -&nbsp;Psychic - Telepathy - Psychometry (Future Only)<br />
<br />
<ul>
<li>Ability to read or sense the emotions and/or control the emotions or feelings of others</li>
<li>Psychic ability to know things about another person. Places, Events, Thoughts, Feelings, past and present, but not future.</li>
<li>Ability to relate details about the past condition of an object or location, usually by being in close contact with it</li>
<li>Telepathy - Ability to read the thoughts of, or to mentally communicate with others</li>
<li>Ability to relate details about the past condition of an object or location, usually by being in close contact with it</li>
</ul>
<br />
<br />
<br />
<b>Faith </b>- Nature Manipulation - Elemental/Chemical Manipulation - Imagination<br />
<ul>
<li>Make things happen. </li>
<li>Mountains move, plants grow or die, bugs or animals do your bidding.</li>
<li>Definitions for
<a href="http://dictionary.reference.com/wordoftheday/2015/12/14/telluric" target="_blank">telluric</a> </li>
<ul>
<li>1.of or proceeding
from the earth or soil.</li>
<li>2.of or relating to
the earth; terrestrial.</li>
</ul>
<li>Water come from rocks.</li>
<li>Walls fall down.</li>
<li>Birds bring you food.</li>
</ul>
<br />
<br />
<b>Healings </b>- Biological manipulation - Healing factor<br />
<br />
<ul>
<li>Vibrations create sound, light, and LIFE force. LIFE is nothing more than being at harmony with the vibrations.&nbsp;</li>
<li>Ex, Healing is the cells natural ability to self cure being sped up by an environment in tune with The Vibration.&nbsp;</li>
<li>Healing includes anything from gun shot wounds to cancer.&nbsp;</li>
<li>But it does not restore missing parts, that is Miracles.</li>
<li>Ability to heal rapidly and with greater finality from any injury; the rate of recovery varies from character to character. Can sometimes result in the slowing of aging and immunity to illnesses and other defects.</li>
</ul>
<b>Matter ingestion<span class="Apple-tab-span" style="white-space: pre;"> </span></b><br />
<br />
<ul>
<li>Ability to consume any sort of matter without any ill effects on the user.</li>
</ul>
<br />
<br />
<br />
<br />
<b>Miracles </b>- Resurrection - Regeneration - Restorative<br />
<br />
<ul>
<li>Ability to come back to life after being killed as well, or to bring others back to life</li>
<li>Ability to grown back limbs, or assist in the regrowing of others limbs.</li>
<li><b>Restorative Powers</b></li>
<ul>
<li>All matter, not just biological. Rusted cars can be restored by touch. Guns can be restored to their natural elements (iron, rock, etc).</li>
</ul>
</ul>
<br />
<br />
<b>Prophecy </b>- Precognition - Psychometry (Future Only)<br />
<br />
<ul>
<li>Ability to perceive the future.&nbsp;</li>
<li>It may be expressed in vague dreams while asleep, other times it can be clear and can occur at will.&nbsp;</li>
<li>It may also be used as a form of "danger sense" to show the user that they are being threatened and from what direction it is coming from.&nbsp;</li>
<li>Ability to relate details about the future condition of an object or location, usually by being in close contact with it</li>
</ul>
<br />
<br />
<br />
<b>Discerning of Spirits</b> - Cross-dimensional awareness<span class="Apple-tab-span" style="white-space: pre;"> </span><br />
<br />
<ul>
<li>Ability to detect actions and events in other dimensions.&nbsp;</li>
<li>Ability to detect beings and general atmosphere.</li>
<li>This is occasionally used in comics as an awareness of the fourth wall between the characters and the artist or audience.</li>
<li>Seeing angels, demons, spiritual condition of a person.</li>
</ul>
<br />
<br />
<b>Tongues - Interpretation of Tongues</b> - Omni-linguism<span class="Apple-tab-span" style="white-space: pre;"> </span><br />
<br />
<ul>
<li>Ability to speak any form of language, a natural polyglot. This can be accomplished in various ways.</li>
<li>Ability to understand any form of language, a natural polyglot. This can be accomplished in various ways.</li>
<li>Sound manipulation - Ability to manipulate sound</li>
<li><b>Echolocation</b></li>
<ul>
<li>Ability to determine location of objects in the environment by use of reflected sound waves, whether generated by the character or ambient sound. Also known as sonar or radar sense.</li>
</ul>
</ul>
<br />
Donkey Talked <br />
<br />
Material Manipulation (Red Sea) <br />
<br />
Time Manipulation (Sun Stood Still)<br />
<br />
<br />
Encouragement - Edification - Motiviation - Cognitive Enhancment and Manipulation - Pursuassion<br />
<ul>
<li>Think of the great orators (good/bad) Hitler, Winston Churchhill, </li>
</ul>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
Other<br />
<br />
<b>Time manipulation</b><br />
<ul>
<li>Ability to affect the flow of time by slowing, accelerating, reversing, or stopping it</li>
</ul>
<b>Teleportation -&nbsp;Translated - </b>Astral projection<span class="Apple-tab-span" style="white-space: pre;"> </span><br />
<div>
<ul>
<li>Ability to move from one place to another without occupying the space in between</li>
<li>Also known as astral travel, this is the ability to separate and control one's astral body.</li>
</ul>
<div>
<br /></div>
<b>Firebreathing</b><br />
<br />
<ul>
<li>Ability generate gases from the body and exhale fire from the mouth.</li>
</ul>
<br />
<br />
<b>Invisibility</b><br />
<br />
<ul>
<li>Ability to render the user unseen to the naked eye and/or other forms of perception.</li>
</ul>
<br />
<br />
<br />

<br />
<br />
<b>Superhuman longevity<span class="Apple-tab-span" style="white-space: pre;"> </span></b><br />
<br />
<ul>
<li>Ability to live longer than a normal human.</li>
</ul>
<br />
<br />
<b>Superhuman durability / endurance /&nbsp;agility / reflexes / strength / speed</b><br />
<br />
<ul>
<li>Samson, Elijah when he outran the chariots</li>
<li>Ability to have a higher resistance to one or more forms of damage before being injured as well as the ability to exert oneself in an activity indefinitely without becoming tired and/or survive for long periods of time without consumption or water. Ability to react faster than a normal human and to possess greater flexibility and with higher/farther jumping capacity.</li>
<li>Ability to have a level of strength much higher than normally possible given their proportions.</li>
</ul>
<div>
<br /></div>
<div>
<br /></div>
<br />
<b>Superhuman senses<span class="Apple-tab-span" style="white-space: pre;"> - Magnification</span></b><br />
<br />
<ul>
<li>Ability to see, smell, taste, feel and/or hear more than a normal Human.</li>
</ul>
<br />
<br />
<br />
<br />
Mind control<br />
The ability to alter the perceptions of others, and general ability to control the actions of others with the mind<br />
<br />
Memory manipulation (yes with caveeats) <br />
You cannot violate the will, but you can assist with the recovery or ridding of memory for the willing.<br />
Ability to erase or enhance the memories of another<br />
<br />
Elemental transmutation<span class="Apple-tab-span" style="white-space: pre;"> </span><br />
The ability to alter chemical elements, changing them from one substance to another by rearranging the atomic structure. May be limited to self-transmutation<br />
<br />
Gravity manipulation<span class="Apple-tab-span" style="white-space: pre;"> </span><br />
Ability to manipulate or generate gravitons, or other types of gravitational interactions<br />
<br />
Intangibility or phasing<span class="Apple-tab-span" style="white-space: pre;"> </span><br />
Ability to quantum tunnel through solid matter without harm[171]<br />
<br />
Light manipulation<span class="Apple-tab-span" style="white-space: pre;"> </span><br />
Ability to control, generate or absorb light particles<br />
<br />
<br />
<br />
<br />
<strong>Who are the Nephlim in this world?</strong><br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
Research:<br />
<br />
Superhuman Abilities - (Inhuman, Object Based, Mutant)<br />
https://en.wikipedia.org/wiki/List_of_superhuman_features_and_abilities_in_fiction<br />
<br />
List of Elemental Abilities<br />
http://powerlisting.wikia.com/wiki/List_of_Elemental_Abilities<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">
<div style="font-weight: normal;">
<b>Comment on this post, or Hit me up on Twitter&nbsp;<a href="https://twitter.com/darrellwolfe" style="color: #149adf; text-decoration: none;" target="_blank">@DarrellWolfe&nbsp;</a>,&nbsp;Google&nbsp;<a class="g-profile" data-gapiattached="true" data-gapiscan="true" data-onload="true" href="https://plus.google.com/106337514196493406365" style="color: #149adf; text-decoration: none;" target="_blank">+DarrellWolfe</a>, Facebook&nbsp;<a href="https://www.facebook.com/groups/907869989282584/" style="color: #149adf; text-decoration: none;" target="_blank">DarrellGWolfe</a>,&nbsp;</b></div>
</h4>
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<br /></blockquote>
<h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">
By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4>
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<i>Storyteller, Creative,&nbsp;<a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>,&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>, Ideation, Input, Learner, Achiever</i></blockquote>
<br />
<i>* I may include "Affiliate Links" which means I earn a commission when you buy some of the products I link to.&nbsp;</i><br />
<br />
<ul>
<li><i>See my full about page and disclosures:&nbsp;<a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li>
</ul>
<ul>
<li><i>Also check out my&nbsp;<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions&nbsp;</a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li>
</ul>
<br />
<i></i><br />
<br />
<a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br />
<br />
To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br />
<br />
For Non-Fiction stories with a lesson by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a><br />
<br />
<br />
<br />
<br />
<br />
<div style="clear: both; float: left; padding-bottom: 10px; text-align: right;">
<br /></div>
</div>
