---
title: 'Thaddeus J. B. Rotcudnoc'
date: '2015-12-02T05:06:00.0050000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '229959730533556730'
blogger_filename: '/2015/12/thaddeus-j-b-rotcudnoc.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Character Sketch'
---

<br />
<br />
<br />
<div style="margin: 0in 0in 0.0001pt;">
</div>
<br />
<div style="margin-bottom: .0001pt; margin-bottom: 0in; margin-left: .5in; margin-right: 0in; margin-top: 0in; mso-list: l0 level1 lfo1; text-indent: -.25in;">
<div style="margin: 0px;">
<span style="font-family: &quot;symbol&quot;;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span style="font-family: &quot;georgia&quot; , serif;">Character Sketch Template (<a href="https://www.udemy.com/blog/character-sketch-examples/">Hints</a>)(<a href="https://en.wikipedia.org/wiki/Now,_Discover_Your_Strengths" target="_blank">Strengths List</a>)(<a href="https://www.isa.org/templates/two-column.aspx?pageid=134103&amp;append=35734" target="_blank">Strengths details</a>)(<a href="http://www.16personalities.com/personality-types" target="_blank">16P-Types</a>)(<a href="http://www.16personalities.com/articles/our-theory" target="_blank">16P-Theory</a>)<o:p></o:p></span></div>
</div>
<br />
<br />
Thaddeus J. B. Rotcudnoc<br />
<br />
Black Suit, real name unknown<br />
<br />
<br />
<br />
<br />
Thaddeus abhors social inventions. He is a trillion-aire. His net personal (non-corporate) net worth is equal, at least, to the annual GDP of North America combined.<br />
<br />
He needs to be in control of all things at all times. Money is not a motivation, it is a tool used to achieve that control. He owns half the US Senators, and blackmails another 1/4 of them. He considers Warren Buffet a small time nuisance, and sometimes an unwitting participant in his schemes.<br />
<br />
Real power is wielded secretly, quietly, and firmly. He never uses his real name, he's not even sure if he can remember his real name.<br />
<br />
Today he's decided to be known as Thaddeus.<br />
<br />
<br />
Overview: Traits, Strengths, SDI, Type, Gifts, Talents, Skills<br />
<br />
<span class="Apple-tab-span" style="white-space: pre;"> </span>I. Physical Description<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>a. Hair<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. White Hiar<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. Clean, Professional, part to the side.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>iii. Bright White, Bounces a bit if he walks/turns quickly<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>b. Eyes<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Grey<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. No Glasses<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>c. Height/Weight<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. 5'7"<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. 155 lbs<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>iii. Fit, not buff, but fit.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>d. Style of Dress<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Typically wears expensive business suits, popular/common cuts and colors.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. Most Commonly wears a black suit and white shirt.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>e. Speech<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Hard to pin down, possibly a subtle German underpinning.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. Speaks with simple phrases, may throw out a few college words from time to time which betray an intelligence. Prefers to get to what he is going to say directly, without misunderstanding, to control the situation with his words.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>f. &nbsp;How Character Feels About Physical Appearance<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Appearance is a tool used to wield power. I often wear a black suit, white shirt, and various ties. Always up to date with the latest fashions, but with a conservative and ubiquitous style. Flashy is not my thing.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. The clothing should be expensive enough to make an impression on those who know what money can buy, but neutral enough to be vague in description to any authorities. I always make contingencies, ensuring that any evidence of my presence is wiped from cameras and recordings, but in this new digital age, you can never be too cautious, so I keep a low profile.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>iii. Appearance, like nearly all things for Thaddeus, is a finished product. Finley tuned and honed over many decades.<br />
<span class="Apple-tab-span" style="white-space: pre;"> </span>II. Personality<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>a. Mannerisms<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. certain little thing the character likes to do, like tearing up napkins while waiting for food at a restaurant<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. another certain little thing the character likes to do<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>b. Bad Habits<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Bad Habit 1<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. Bad Habit 2<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>c. Strengths/Weaknesses<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Strengths<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. Weaknesses<br />
<span class="Apple-tab-span" style="white-space: pre;"> </span>III. Likes/Dislikes<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>a. Likes<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Snifter of Cognac<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. Making People Nervous<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>b. Dislikes<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Things that are not well made / done right. Mistakes.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. When things happen that he did not plan for / make contingencies for.<br />
<span class="Apple-tab-span" style="white-space: pre;"> </span>IV. Family<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>a. Parents - Orphan<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>b. Siblings - None<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>c. Extended Family - None<br />
<span class="Apple-tab-span" style="white-space: pre;"> </span>V. Hobbies<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>a. Hobby 1<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Science/Discovery<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. To be used to gain more control.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>b. Hobby 2<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. details about hobby<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. character’s feelings about hobby<br />
<span class="Apple-tab-span" style="white-space: pre;"> </span>VI. History<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>a. Childhood<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Event<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. Event<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>iii. character’s feelings about childhood<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>b. Teen Years<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Event<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. Event<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>iii. character’s feelings about teen years<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>c. Young Adulthood<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Event<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. Event<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>iii. character’s feelings about young adulthood<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>d. Just Before the Story Begins<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Event<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. Event<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>iii. character’s feelings about events<br />
<span class="Apple-tab-span" style="white-space: pre;"> </span>VII. Conflicts<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>a. Must be in Power/Control, to be the apex of every triangle, and the conductor of every interaction.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>b. Outer Conflicts<br />
<br />
<div style="margin-bottom: .0001pt; margin-bottom: 0in; margin-left: .5in; margin-right: 0in; margin-top: 0in; mso-list: l0 level1 lfo1; text-indent: -.25in;">
<span style="font-family: &quot;symbol&quot;;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span style="font-family: &quot;georgia&quot; , serif;">Character Sketch Template (<a href="https://www.udemy.com/blog/character-sketch-examples/">Hints</a>)<o:p></o:p></span></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Hello my name is Amy Truthfinder, and I’m here with xxxxxxxx from the xxxxxxx series, to find out more about him/her and get a little behind the scenes information.<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<b><span style="font-family: &quot;georgia&quot; , serif;">In the way of introductions:<o:p></o:p></span></b></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Xxxxxxx is a Primary/Supporting character in the book xxxxx. He has chosen to side with the (Good/Bad/ Neither, he remains neutral, is unware of the sides).<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Xxxxxx was born on xx/xx/xx, which makes him xxxx years old as of xx/xx/xx.<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">He/She has the following distinct physical characteristics; xxxxxxxxxxxxxxxxxxx.<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<b><span style="font-family: &quot;georgia&quot; , serif;">Personality and Motivations:<o:p></o:p></span></b></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Tell me, what is your 16P Type, what are you top five Strengths finders results, and what one-three words best describes you?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What do you do with<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">time when you are not working?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What are the things you enjoy most in life?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What things just bug you to no end?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">If every job, task, and activity in the world paid the same (and it was more than enough to have everything you wanted) what would you do?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">If you could sit down and chat with person who is alive today, who would it be? What about anyone not alive today? What about a non-real person? What about someone from your story world?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<b><span style="font-family: &quot;georgia&quot; , serif;">Training and background<o:p></o:p></span></b></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Tell me about your schooling. What high school did you go to? Where did you go to college? What activities did you participate in? Sororities / Fraternities? Were you&nbsp; in any other groups? Did you work through school, loans, scholarships, rich family?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Tell me about your major. How many degrees do you have? In what? Why that and not something else?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What was your first job? How many jobs have you had? What was your favorite job? Least favorite job? What do you do now?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Do you hold any licenses, specialties, etc.?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">If you could switch jobs today what would you do? (Real and Imagined)<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin: 0in 0in 0.0001pt;">
<b><span style="font-family: &quot;georgia&quot; , serif;">Family history<o:p></o:p></span></b></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What are your parents name? Do you know your grandparents? Do you have an siblings? Cousins, Aunts, Uncles, Other important relatives? Are you related to anyone famous?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What does your name mean, and why did you parents choose it?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Is there anything interesting or important or unusual we need to know about your family?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What was your relationship like with your Mother? Father? Others?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">How is your relationship now?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<b><span style="font-family: &quot;georgia&quot; , serif;">Early Childhood through middle school<o:p></o:p></span></b></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What experiences, growing up, marked your memory? In other words, what can you remember about your childhood, what stands out?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Who were your best friends?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Worst enemies, bullies?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What was your best day? Worst?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<b><span style="font-family: &quot;georgia&quot; , serif;">Here are some photos that remind me of you:<o:p></o:p></span></b></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<br />
<div style="margin: 0in 0in 0.0001pt;">
</div>
<br />
<div style="margin: 0in 0in 0.0001pt;">
<div style="margin: 0px;">
<br /></div>
</div>
<br />
<br />
<br />
<br />
<h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">
<div style="font-weight: normal;">
<b>Comment on this post, or Hit me up on Twitter&nbsp;<a href="https://twitter.com/darrellwolfe" style="color: #149adf; text-decoration: none;" target="_blank">@DarrellWolfe&nbsp;</a>,&nbsp;Google&nbsp;<a class="g-profile" data-gapiattached="true" data-gapiscan="true" data-onload="true" href="https://plus.google.com/106337514196493406365" style="color: #149adf; text-decoration: none;" target="_blank">+DarrellWolfe</a>, Facebook&nbsp;<a href="https://www.facebook.com/groups/907869989282584/" style="color: #149adf; text-decoration: none;" target="_blank">DarrellGWolfe</a>,&nbsp;</b></div>
</h4>
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<br /></blockquote>
<h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">
By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4>
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<i>Storyteller, Creative,&nbsp;<a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>,&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>, Ideation, Input, Learner, Achiever</i></blockquote>
<br />
<i>* I may include "Affiliate Links" which means I earn a commission when you buy some of the products I link to.&nbsp;</i><br />
<br />
<ul>
<li><i>See my full about page and disclosures:&nbsp;<a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li>
</ul>
<ul>
<li><i>Also check out my&nbsp;<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions&nbsp;</a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li>
</ul>
<br />
<i></i><br />
<br />
<a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br />
<br />
To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br />
<br />
For Non-Fiction stories with a lesson by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a><br />
<br />
<br />
<br />
<br />
<br />
<div style="clear: both; float: left; padding-bottom: 10px; text-align: right;">
<br /></div>
