---
title: 'General Akbar'
date: '2015-12-02T05:08:00.0030000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '6457167228087962459'
blogger_filename: '/2015/12/general-akbar.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Character Sketch'
---

<br />
<div style="margin-bottom: .0001pt; margin-bottom: 0in; margin-left: .5in; margin-right: 0in; margin-top: 0in; mso-list: l0 level1 lfo1; text-indent: -.25in;">
<br />
<div style="margin: 0in 0in 0.0001pt;">
</div>
<br />
<div style="margin-bottom: .0001pt; margin-bottom: 0in; margin-left: .5in; margin-right: 0in; margin-top: 0in; mso-list: l0 level1 lfo1; text-indent: -.25in;">
<div style="margin: 0px;">
<span style="font-family: &quot;symbol&quot;;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span style="font-family: &quot;georgia&quot; , serif;">Character Sketch Template (<a href="https://www.udemy.com/blog/character-sketch-examples/">Hints</a>)(<a href="https://en.wikipedia.org/wiki/Now,_Discover_Your_Strengths" target="_blank">Strengths List</a>)(<a href="https://www.isa.org/templates/two-column.aspx?pageid=134103&amp;append=35734" target="_blank">Strengths details</a>)(<a href="http://www.16personalities.com/personality-types" target="_blank">16P-Types</a>)(<a href="http://www.16personalities.com/articles/our-theory" target="_blank">16P-Theory</a>)<o:p></o:p></span></div>
</div>
</div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Hello my name is Amy Truthfinder, and I’m here with xxxxxxxx from the xxxxxxx series, to find out more about him/her and get a little behind the scenes information.<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<b><span style="font-family: &quot;georgia&quot; , serif;">In the way of introductions:<o:p></o:p></span></b></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Xxxxxxx is a Primary/Supporting character in the book xxxxx. He has chosen to side with the (Good/Bad/ Neither, he remains neutral, is unware of the sides).<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Xxxxxx was born on xx/xx/xx, which makes him xxxx years old as of xx/xx/xx.<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">He/She has the following distinct physical characteristics; xxxxxxxxxxxxxxxxxxx.<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<b><span style="font-family: &quot;georgia&quot; , serif;">Personality and Motivations:<o:p></o:p></span></b></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Tell me, what is your 16P Type, what are you top five Strengths finders results, and what one-three words best describes you?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What do you do with<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">time when you are not working?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What are the things you enjoy most in life?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What things just bug you to no end?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">If every job, task, and activity in the world paid the same (and it was more than enough to have everything you wanted) what would you do?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">If you could sit down and chat with person who is alive today, who would it be? What about anyone not alive today? What about a non-real person? What about someone from your story world?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<b><span style="font-family: &quot;georgia&quot; , serif;">Training and background<o:p></o:p></span></b></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Tell me about your schooling. What high school did you go to? Where did you go to college? What activities did you participate in? Sororities / Fraternities? Were you&nbsp; in any other groups? Did you work through school, loans, scholarships, rich family?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Tell me about your major. How many degrees do you have? In what? Why that and not something else?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What was your first job? How many jobs have you had? What was your favorite job? Least favorite job? What do you do now?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Do you hold any licenses, specialties, etc.?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">If you could switch jobs today what would you do? (Real and Imagined)<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin: 0in 0in 0.0001pt;">
<b><span style="font-family: &quot;georgia&quot; , serif;">Family history<o:p></o:p></span></b></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What are your parents name? Do you know your grandparents? Do you have an siblings? Cousins, Aunts, Uncles, Other important relatives? Are you related to anyone famous?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What does your name mean, and why did you parents choose it?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Is there anything interesting or important or unusual we need to know about your family?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What was your relationship like with your Mother? Father? Others?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">How is your relationship now?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<b><span style="font-family: &quot;georgia&quot; , serif;">Early Childhood through middle school<o:p></o:p></span></b></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What experiences, growing up, marked your memory? In other words, what can you remember about your childhood, what stands out?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Who were your best friends?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Worst enemies, bullies?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What was your best day? Worst?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<b><span style="font-family: &quot;georgia&quot; , serif;">Here are some photos that remind me of you:<o:p></o:p></span></b></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<br />
<div style="margin: 0in 0in 0.0001pt;">
</div>
<br />
<div style="margin: 0in 0in 0.0001pt;">
<div style="margin: 0px;">
<br /></div>
</div>
<br />
<br />
Wake Up Call<br />
<br />
Sriklan Islands were swamped with helicopters, sea planes, and search boats. A literal army, a swarm of military personnel had flooded the restricted island territories.<br />
<br />
"These Islands are strictly off limits, no official maps even contain their presence... The President of the United States isn't even permitted to know of the location of these islands Jim... So tell me how two of my best operatives simply disappeared? ...I don't want excuses I want answers! Call me when you actually know something!" General Akbar nearly broke the com phone as he slammed it into its receiver in his quarters aboard the USS Silence. "The CIA is worthless...", he muttered to himself.<br />
<br />
General Akbar looked down at his watch. 2313. It had been just over 21 days since they had each disappeared from their pick up points… at the same time. Both had reported in, ready for evac. Now, both were Missing In Action (MIA) upon extraction. What was most disturbing was the total lack of any other presence having come or gone. No signs of struggle; no blood or missing items; it's as though they'd simply vanished. The worst possibility was that they are defected, but he knew these two, like his own kids, better than his own kids. It wasn't possible. The other possibility, nearly as bad possibility was that they had been taken, which was a more likely scenario. The preferred possibility is that they were playing some massive practical joke on him, which would warrant a severe reprimand and was totally contrary to their character. Option 2 had the most merit, but that's leaves more questions than answers. How can two people disappear from the most top secrete set of Islands in the world?<br />
<br />
The door swung open, and in ran a younger man, half heaving, holding a piece of paper.<br />
<br />
"Sir."<br />
<br />
"What is it Sargent?"<br />
<br />
"Motion sensors detect movement on one of the south islands."<br />
<br />
"We haven't trained down there in months. Are you sure it's not those stupid Monkey's again?"<br />
<br />
"We checked sir, camera footage is rough from the distance, but we captured this image."<br />
<br />
"Well I'll be... Get a unit down there now, and go in armed, we don't know what to expect."<br />
<br />
"Yes sir"<br />
<br />
With that the door closed and left the General alone. "Where have those two been?!"<br />
<br />
***********<br />
<br />
Ash came to himself blinded by a terrible light, which hurt his eyes. He rolled over onto his belly, and planted his face into his pillow... No, this wasn't a pillow, it was... sand? He accidentally breathed some in and began coughing uncontrollably. He would have to get his bearings, but first he'd have to get his senses. He rose to his hands and knees and calmed his mind, slowed his heart rate. Focus. That's what he needed right now. His eyes still hurt too much to open, but he didn't need them just yet.<br />
<br />
Birds. Sand. Wind in trees. Water washing ashore in a quiet steady cadence. He was on the island? The sand between his fingers was cold to the touch, but the sun on his back and face was quite warm. These had to be white sand islands. He was back to the training center? Had he ever left? What happened.... wait... What is that? As his vision came back, he could make out the silhouette of someone thrashing about on the sand. "Eta…", of course.<br />
<br />
***********<br />
<br />
Eta was thrashing around, blindly looking for something or someone to attack. It was only after she ran out of breath that she realized she was alone. Her eyesight was coming back, but it was still much too bright to fully open her eyes, even with the clothe that she'd tied around her face to block the sun.<br />
<br />
All she could see was trees, water, sand. Now that she was too tired to fight.... nothing... she could hear the sounds of the island. There was one sound that was not familiar... A rustling in the trees, less than half a klick away. Someone was headed this way,<br />
<br />
"Eta…" the voice called.<br />
<br />
"Ash?"<br />
<br />
"Yep, it's me."<br />
<br />
"Where are we? I can't see a thing out here."<br />
<br />
"I have no idea, I was hoping you could tell me."<br />
<br />
She could hear helicopters and speed boats headed their way…. "We have to move quickly, sounds like a whole bunch of bogies are coming our way."<br />
<br />
"Eta, their friendlies. It's the General's team." They stood together, waiting for the evac team to come on to the beach. She gave him a friendly punch on the shoulder. He was like her big brother, always looking out for her. Even when she didn't want him to.<br />
<br />
***********<br />
<br />
General Akbar waiting until they had been checked by doctors, before taking them straight into the briefing room with his top staff.<br />
<br />
"Where have you two been?"<br />
<br />
"What do you mean sir?" Ash replied.<br />
<br />
"What do I mean?" General Akbar looked to his staff with a questioning glance. "I mean, you've been missing for 15 days, and I need to know why, and where you were?"<br />
<br />
"21 days?" Eta stated, dumfounded. "I figured 15 minutes… maybe. I completed the mission, called for an evac…"<br />
<br />
"Me too." Ash interrupted. Then there was this bright light, and I woke up on the beach a few minutes later."<br />
<br />
"That's right. Are you saying we've been missing for 21days?" Eta was incredulous.<br />
<br />
"These two need to be checked again. Get them to the infirmary, now!"<br />
<br />
Two months later:<br />
<br />
General Akbar walked into a meeting room and slid two files in front of Ash and Eta. "It is with a heavy heart I have to inform you, that you are being retired. We just can't keep two of our most valuable assets in the field, if you cannot account for missing 21 days of your life. Even with all your training, if you have been programed… You'll be under surveillance, and required to report in to me directly four times a year. Maybe, in time, this will pass. For now you are being honorably discharged, with cover stories to account for the last 20 years of your respective careers. You will report any new memory you have to me, personally, immediately. Is that clear?"<br />
<br />
"Yes Sir."<br />
<br />
"Yes Sir."<br />
<br />
***********<br />
<div>
<br /></div>
<br />
<br />
<br />
<br />
<br />
<h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">
<div style="font-weight: normal;">
<b>Comment on this post, or Hit me up on Twitter&nbsp;<a href="https://twitter.com/darrellwolfe" style="color: #149adf; text-decoration: none;" target="_blank">@DarrellWolfe&nbsp;</a>,&nbsp;Google&nbsp;<a class="g-profile" data-gapiattached="true" data-gapiscan="true" data-onload="true" href="https://plus.google.com/106337514196493406365" style="color: #149adf; text-decoration: none;" target="_blank">+DarrellWolfe</a>, Facebook&nbsp;<a href="https://www.facebook.com/groups/907869989282584/" style="color: #149adf; text-decoration: none;" target="_blank">DarrellGWolfe</a>,&nbsp;</b></div>
</h4>
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<br /></blockquote>
<h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">
By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4>
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<i>Storyteller, Creative,&nbsp;<a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>,&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>, Ideation, Input, Learner, Achiever</i></blockquote>
<br />
<i>* I may include "Affiliate Links" which means I earn a commission when you buy some of the products I link to.&nbsp;</i><br />
<br />
<ul>
<li><i>See my full about page and disclosures:&nbsp;<a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li>
</ul>
<ul>
<li><i>Also check out my&nbsp;<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions&nbsp;</a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li>
</ul>
<br />
<i></i><br />
<br />
<a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br />
<br />
To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br />
<br />
For Non-Fiction stories with a lesson by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a><br />
<br />
<br />
<br />
<br />
<br />
<div style="clear: both; float: left; padding-bottom: 10px; text-align: right;">
<br /></div>
