---
title: 'Ash at the Facility'
date: '2015-05-27T01:36:00.0030000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '2218890728661292520'
blogger_filename: '/2015/05/ash-at-facility.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'White Noise'
---

The silence was deafening. The light was still too bright to open his eyes. But the sound was familiar. <br />
<br />
<em>I know this place... </em><br />
<br />
The dream again.&nbsp;He could feel the cold steel against his wrists. This was knew. He didn't recall being locked to the chair in his dream. Then he heard it... click. click. click. A clock? This was not his dream. <br />
<br />
Ash forced his eyes open to see a room very similar to one from his dream. Only this one was longer, the table was at one end. And there was a single analogue clock on the wall. This room had a pronounced and obvious door. <br />
<br />
"Oh good... you are awake. I'll be with you in a just little while."<br />
<br />
<em>That voice. I know that voice. </em><br />
<br />
Ash took in his souroundings. Nothing much to see. Nothing but white walls, white chair, white table, white clock. Silver Handcuffs on his wrists. The chair was built into the floor it didn't budge. <br />
<br />
No silly outfit this time, he was simply wearing his black clothing from the night before. Blood had dried on his sleave where the gaurd got a good kick with his boot. It looked like their patched him up, maybe a few stitches in the shoulder. <br />
<br />
Ash noticed four cameras, one in each corner. Just then the white noise was interupted by a crackling, and then a whine. <br />
<br />
"Ash, can you hear me?" He nodded in the affirmative. <br />
<br />
"Ash, you can talk, we can see you on the cameras, and there are no gaurds outside the door. I've looped the audio and video, so they can't see or hear you right now."<br />
<br />
"OK, what's going on?" <br />
<br />
"You are in the facility still. Thirteenth Floor. I'm in control of the security, but I can't do anything about those cuffs." <br />
<br />
"It's OK. I want to play this out, and see where it leads. Don't let them catch you in the feeds. Watch, but don't jump in until I give you a signal."<br />
<br />
"What signal?" <br />
<br />
"Is Eta with you?"<br />
<br />
"Yes, I'm right here." <br />
<br />
"She'll know. Just have her watch the feeds with you." <br />
<br />
"Going radio silent, someones coming." Eta's voice. He really missed her as a partner. It's good to have her around, even from a distance. That's why he knew he had to give her time for escape, and let himself get caught... taking as many down with him as he could. <br />
<br />
The door opened, and in walked a small bald man in a lab coat. Dr. Briar, from the Cafe'. <br />
<br />
"Good morning Col Ashland. It's nice to have you back among us. You took a pretty nasty fall last night, and put three of my gaurds in the hospital."<br />
<br />
"Glad I could help." Ash Smiled. <br />
<br />
Dr. Briar returned the smile. "It seems you and I have some unfinished business. As soon as we track down your friend, we'll have questions for her too. My best head hunters are looking for her now. Tell me, Col Ashland, how much do you remember about me?"<br />
<br />
"You are a Dr. Briar, who mistakenly called me a marine. You asked too many wierd questions outside of the cafe in Oregon, and you smell like peppermint candy."<br />
<br />
"Yes, all true. But how about before that time at the cafe, is there anything else you remember about me?" <br />
<br />
"No. Should there be?" <br />
<br />
"We shall see. Dr Briar pulled out some wires and pads. While you were out, you were injected with a serium of my own design. It will help you be more forth coming. I'm simply going to attach these to you for monitoring. We tried putting them on while you were out, but you kept sweating them off.... Tell me, Col. Ashland, how long have you been having these nightmares?" <br />
<br />
"Are you my psychologist now? <br />
<br />
"Now? Col Ashland, I've been your psychologist for quite a few years, you should know that by now." <br />
<br />
"I just get bad dreams. Nothing to worry yourself about there Dr., what do you mean a few years?" <br />
<br />
"Col Ashland, how often must we go through this same routine. You have been a patient here since you had a mental break and left the USAF." <br />
<br />
<br />
............................<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
