---
title: 'The Closet'
date: '2015-05-24T06:11:00.0010000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '5429502404921650390'
blogger_filename: '/2015/05/the-closet.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'White Noise'
---

It was the sound. It washed over his mind, like a shower on the inside. Water landing on pavement, concrete, and wood; as though beating a million tiny drums. The distant sound of the tiny river, washing down the sidewalks into the gutters. Ash always slept with the window open, but most especially on rainy nights.<br />
<br />
We are no closer now to getting to the bottom of this, than we were when it started.<br />
<br />
The rest of the house was asleep, but he couldn't find sleep. The air shifted slightly, and he felt he wasn't alone. Ash sat up straight, and at the edge of his bed sat a man. He was wearing blue jeans, a T-shirt, and a well kept beard. His hair was pulled back into a pony tail, and he smiled. The man's eyes held a piercing gaze, frightening and peaceful all at once. <br />
<br />
The man stood, and motioned to Ash. Almost unable to fight his own body, he rose to follow the man to the closet door. He reached out to open it, and a blinding light raced across the room. When Ash opened his eyes again, they were not in his room anymore. They were standing on a rooftop, overlooking New York City, and Herald Square.<br />
<br />
There, sitting on the ledge was a young man, maybe no more than 20. He was holding himself, rocking himself back and forth.<br />
<br />
It'll all be over soon. It'll all be over soon. He repeated to himself over and over.<br />
<br />
Ash could see the Parade balloons in the distance. He knew this is what Eta had been talking about. Ash wanted to go stop him, but he couldn't move. His traveling companion put his arm on Ash's shoulder and smiled. He could feel the answer.<br />
<br />
Not Now.<br />
<br />
The bright light flashed, and he found himself standing in front of his open closet, staring at the darkness. Ash turned back to his bed, and lay there for a few more hours. Sleep overcame him, and he rested. For the first time in a long time, confused, but peaceful, he rested.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />