---
title: 'Dr. Richard T. Briar PhD'
date: '2015-12-02T05:05:00.0020000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '1981668651198920459'
blogger_filename: '/2015/12/dr-richard-t-briar-phdborn-niklaus-von.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Character Sketch'
---

<br />
<h3>
Dr. Richard T. Briar PhD</h3>
<br />
Author of: &nbsp;“Unlocking the Paranormal Mind. A study of how the human mind’s unlocked potential”, By Dr Richard T. Briar.<br />
<h4>
Getting into the background: Dr. Briar</h4>
Dr. Briar is a scientist, first and foremost, but he's also bound to the needs of his financial benefactor "Thaddeus". <br />
<br />
They've had incidents from prior research "volunteers" that led to exposure to their less than legal program, code named "White Noise". One such incident involved a man who was perfectly normal before the experiment suddenly deciding to walk into oncoming traffic on a freeway. He said he did it at the demands of "voices in his head". He was taken to a hospital, but the next day he snuck out and did it again. He died, as did three other people due to the crash that ensued.<br />
<br />
A young reporter, Grace Scriven,&nbsp;tied his medical records back to his involvement in "White Noise". Even after several press releases insisting no ties between their research (several years prior) and the current incidents, she was not satisfied and she kept pressing.<br />
<br />
These incidents led local authorities in Los Angeles (LA), County California to investigate the Institute further, which&nbsp;put them at Legal and Regulatory risk, but also increased&nbsp;media exposure. <br />
<br />
Dr. Brian doesn't know it, but Thaddeus (his benefactor) is operating under an Assumed Alias that he spent a great deal of time creating, and this is why he is getting even greater pressure from Thaddeus to keep a lid on the exposure.<br />
<br />
At the <strong><em>lethal</em></strong> insistence of his benefactor and due to a fear of losing his own research (which he prizes above life itself), Dr. Briar agrees to hunt down and exterminate any participants of "White Noise" that were showing any signs of ill-effects.<br />
<br />
At the start of our story, due to the length of time it's taken and the increased pressure from a variety of sources, Thaddeus now insists that ALL participants of White Noise either become deceased or vegetative in short order (or Dr. Briar himself will be eliminated).<br />
<br />
Dr. Briar heads to Ashland, OR where two of his former volunteers happen to reside (no relation). <br />
<br />
Grace Scriven has been monitoring his travel plans and happens to track him to Ashland, Oregon where she begins to understand the level of&nbsp;the Dr.'s&nbsp;depravity.<br />
<br />
Dr. Briar sneaks poison into Ash's coffee, but he doesn't drink it before an outburst outside (with the other volunteer) causes him to lose the contents, spilling them onto the ground.<br />
<br />
After seeing him handle the volunteer, Dr. Briar sends a hit man to cause Ash to "crash" his truck off a cliff on his way back to his cabin.<br />
<br />
Grace (disguised - incognito) saw Dr. Briar's interest in Ash the first time around. She follows him to his car and she's with him when the crash attempt occurs.<br />
<br />
The hit man checks to ensure fatality, realizes they escaped, and follows them into the forest to finish the job.... <br />
<br /><strong>Now Action!</strong><br />
<br />
<br />
<br />
<h4>
&nbsp;**********************NEW bio sketch above. OLD bio sketch below for reference but no longer valid. *************&nbsp;</h4>
<br />
Overview:<br />
<br />
<span class="Apple-tab-span" style="white-space: pre;"> </span>• Motivation: Exploring Science, to unlock the human potential to access, and possibly control, other dimensions.<br />
<br />
Author of: &nbsp;“Unlocking the Paranormal Mind. A study of how the human mind’s unlocked potential”, By Dr Richard T. Briar.<br />
<br />
Richard Briar was a scientist, who specialized in the paranormal. His birth name was Niklaus von Klaus<br />
<br />
He was named after the patron saint of Switzerland. Niklaus von Flue, also known as Brother Klaus, who died in 1487. Brother Klaus was known as a spiritual advisor and pastor to both rural and rich; however, was also known for heretical practices of mysticism.<br />
<br />
Dr. Briar's mother was a mystic from Switzerland, and his father was a German scientist during WWI. Dr Niklaus von Klaus was a German Nazi scientist during WWII, who fled to Switzerland, and then to the UK, after changing his name and accent. He now operated under the alias of Dr. Richard Briar, tenured professor (retired) of Cambridge University, and founder of the Briar Psychiatric Center, Colorado Springs, CO. , dedicated to studying the farthest reaches and capabilities of the human mind.<br />
<br />
There were exactly zero people alive who knew Dr. Briar's original identity, or the extent of his true plans.<br />
<br />
It would be interesting to see just how far this rabbit hole would go…. What secrets the unlocking the human mind would reveal. It was necessary to operate on the fringe of the law, after all, we all know how bureaucracies hold back the spirit of innovation!<br />
<br />
Introverted, Intuitive, Thinking, Perceptive &nbsp;(INTP)<br />
<br />
The INTP personality type is fairly rare, making up only three percent of the population, which is definitely a good thing for them, as there's nothing they'd be more unhappy about than being "common". INTPs pride themselves on their inventiveness and creativity, their unique perspective and vigorous intellect. Usually known as the philosopher, the architect, or the dreamy professor, INTPs have been responsible for many scientific discoveries throughout history.<br />
<br />
Known for Brilliant Theories, and Unrelenting Logic. Not punctual, do not bother themselves with day to day activities or maintenance. This constant thinking can have the effect of making them look pensive and detached, as they are often conducting full-fledged debates in their own heads, but really INTPs are quite relaxed and friendly when they are with people they know, or who share their interests. However, this can be replaced by overwhelming shyness when INTP personalities are among unfamiliar faces, and friendly banter can quickly become combative if they believe their logical conclusions or theories are being criticized.<br />
<br />
<br />
<br />
<span class="Apple-tab-span" style="white-space: pre;"> </span>I. Physical Description<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>a. Born<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. 78 years old in 2015<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. 1937 - Born (Born: Niklaus von Klaus), in Switzerland to German speaking parents, trying to escape the war. In 1954, when the war was a few years over, he made his way to the USA, under the name Richard Titus Briar. Later, graduating from M.I.T with multiple PhD's, he became known as Dr. Richard T. Briar PhD.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>b. Hair<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Gray, turning white. Disheveled.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>c. Eyes<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Blue. Thick rim Glasses.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>d. Height/Weight<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. 5'6"<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. 135Lbs (never eats, too busy thinking).<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>iii. Scrawny, Boney.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>e. Style of Dress<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Good Will Suits, mostly. Or a lab coat.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>f. Speech<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. An articulate, practiced, American accent.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. Could start to sound Swiss/German when he becomes angry.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>iii. ?<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>g. &nbsp;How Character Feels About Physical Appearance<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Could care less what he looks like, just as long as it doesn't bring too much attention.<br />
<span class="Apple-tab-span" style="white-space: pre;"> </span>II. Personality<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>a. Mannerisms<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Using his index finger, he rubs the side of his temple, right where the sideburn comes down. He does this when he thinking, which is nearly any time he's idle.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. He enjoys writing words and phrases backwards on napkins. The longer the phrase the better.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>b. Bad Habits<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Smokes Pipes. He started because he thought it looked distinguished. He kept it up because he liked it.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. Stops listening to you, as his mind wanders off.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>c. Strengths/Weaknesses<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>INTP Strengths<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>? &nbsp; &nbsp; Great Analysts and Abstract Thinkers - People with the INTP personality type view the world as a big, complex machine, and recognize that as with any machine, all parts are interrelated. INTPs excel in analyzing these connections, seeing how seemingly unrelated factors tie in with each other in ways that bewilder most other personality types.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>? &nbsp; &nbsp; Imaginative and Original - These connections are the product of an unrelenting imagination - INTPs' ideas may seem counter-intuitive at a glance, and may never even see the light of day, but they will always prove remarkable innovations.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>? &nbsp; &nbsp; Open-Minded - INTPs couldn't make these connections if they thought they knew it all - they are highly receptive to alternate theories, so long as they're supported by logic and facts. In more subjective matters like social norms and traditions, INTPs are usually fairly liberal, with a "none of my business" sort of attitude - peoples' ideas are what matter.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>? &nbsp; &nbsp; Enthusiastic - When a new idea piques their interest, INTPs can be very enthusiastic - they are a reserved personality type, but if another person shares an interest, they can be downright excited about discussing it. More likely though, the only outward evidence of this enthusiasm will be INTPs' silent pacing or their staring into the distance.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>? &nbsp; &nbsp; Objective - INTPs' analysis, creativity and open-mindedness aren't the tools of some quest for ideology or emotional validation. Rather, it's as though people with the INTP personality type are a conduit for the truths around them, so far as they can be expressed, and they are proud of this role as theoretical mediator.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>? &nbsp; &nbsp; Honest and Straightforward - To know one thing and say another would be terribly disingenuous - INTPs don't often go around intentionally hurting feelings, but they believe that the truth is the most important factor, and they expect that to be appreciated and reciprocated.<br />
<span class="Apple-tab-span" style="white-space: pre;"> </span><br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>INTP Weaknesses<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>? &nbsp; &nbsp; Very Private and Withdrawn - While INTPs' intellectualism yields many insights into their surroundings, their surroundings are ironically considered an intrusion on their thoughts. This is especially true with people - INTPs are quite shy in social settings. More complicated situations such as parties exacerbate this, but even close friends struggle to get into INTPs' hearts and minds.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>? &nbsp; &nbsp; Insensitive - Oftentimes INTP personalities get so caught up in their logic that they forget any kind of emotional consideration - they dismiss subjectivity as irrational and tradition as an attempt to bar much-needed progress. Purely emotional situations are often utterly puzzling to INTPs, and their lack of timely sympathy can easily offend.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>? &nbsp; &nbsp; Absent-minded - When INTPs' interest is captured, their absence goes beyond social matters to include the rest of the physical world. INTPs become forgetful, missing even the obvious if it's unrelated to their current infatuation, and they can even forget their own health, skipping meals and sleep as they muse.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>? &nbsp; &nbsp; Condescending - Attempts at connecting with others are often worse than INTPs' withdrawal. People with the INTP personality type take pride in their knowledge and rationale, and enjoy sharing their ideas, but in trying to explain how they got from A to B to Z, they can get frustrated, sometimes simplifying things to the point of insult as they struggle to gauge their conversation partners' perspective. The ultimate insult comes as INTPs give up with a dismissive "never mind".<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>? &nbsp; &nbsp; Loathe Rules and Guidelines - These social struggles are partly a product of INTPs' desire to bypass the rules, of social conduct and otherwise. While this attitude helps INTPs' strength of unconventional creativity, it also causes them to reinvent the wheel constantly and to shun security in favor of autonomy in ways that can compromise both.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>? &nbsp; &nbsp; Second-Guess Themselves - INTPs remain so open to new information that they often never commit to a decision at all. This applies to their own skills as well - INTP personalities know that as they practice, they improve, and any work they do is second-best to what they could do. Unable to settle for this, INTPs sometimes delay their output indefinitely with constant revisions, sometimes even quitting before they ever begin.<br />
<span class="Apple-tab-span" style="white-space: pre;"> </span><br />
<span class="Apple-tab-span" style="white-space: pre;"> </span>III. Likes/Dislikes<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>a. Likes<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Like 1<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. Like 2<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>b. Dislikes<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. For INTPs, colleagues aren't so much a group of people who they socialize and work with as they are a series of obstacles and diversions with occasionally useful knowledge. <br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. Dislike 2<br />
<span class="Apple-tab-span" style="white-space: pre;"> </span>IV. Family<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>a. Parents<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Both died. Father died in WWII. Mother died of malaria in 1951, when he was 14. He floated between friends' houses for a few more years, before leaving for the USA.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>b. Siblings - None<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>c. Extended Family - None Known. Died in WWII.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>d. Hobbies - None. Life is Work. Work is Science. Science is all consuming.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>e. Childhood<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. Father died when he was too young to remember.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. September 7, 1937: In a speech underscoring a perceived need for Lebensraum (living space), Adolf Hitler claims that Nazi Germany "is too small to guarantee an undisturbed, assured, and permanent food supply."<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>iii. October 1937 - the von Klaus Family (with powerful ties in government) could see what was happening, and moved to Switzerland to keep safe as Europe was destabilizing, just prior to WWII.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>iv. Richard (Niklaus ) cannot remember much of this era, only vague recollections of hushed conversations among adults, and an abrupt move to a new country/place.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>f. Teen Years<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. At 14 years old, 1951, his mother died of a disease, he now believes was malaria.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. 14-17 - floats between friends' houses.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>iii. Richard (Niklaus) remembers feeling cold, distant, unwanted, in the way, and very odd for his intellect and interests.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>g. Young Adulthood<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. By 17, he had gotten a hold of everything he could find on American culture, and scientific learning. He built a fake persona, passports and all, and made his way to the USA.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. He was able to fake his college transcripts from Switzerland, and was admitted into M.I.T.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>iii. Majored in Biology. After achieving his PhD in Biology, he continued on with his education, gaining other majors Biological Technology. By 1964, at the young age of 27, he became among the founding members of the Department of Psychology, with a course he co-developed and frequently lectured, called &nbsp;Brain and Cognitive Science".<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>iv. He was fascinated by the scientific breakthroughs he discovered; however, was lonely as even among these elite he was considered an outcast. He was also increasingly frustrated with the bureaucratic systems that prevented him from taking on new projects, and pushing all the way to the cutting edge of possibilities.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>h. Just Before the Story Begins<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. He left the school system, working for various corporation backed projects for decades, as he continued to invest, save, and build a small corporation of his own design. One in which he could control the policies and decisions. Unfortunately, he wasn't a very good business man, and his company retained one employee, himself, and very seldom made money.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>ii. A rich person, interested in his work, and referred by a mutual former associate, contacts him to back and fund his wildest research. So he makes a "deal with the devil", as it turned out. And he regrets it daily. The White Noise project was supposed to unlock the human potential; unfortunately it only seems to result in driving people insane, and in some cases render them dangerous to themselves or others.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>iii. character’s feelings about events<br />
<span class="Apple-tab-span" style="white-space: pre;"> </span>V. Conflicts<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>a. Passion for scientific breakthroughs, and exploring the realities just beyond the possible.<br />
<span class="Apple-tab-span" style="white-space: pre;">  </span>b. Need for money, and willingness to cut corners, ignore laws, and take lives in the process.<br />
<span class="Apple-tab-span" style="white-space: pre;">   </span>i. The scientist in him is passionate about his work, but is also quietly concerned about the steps taken to accomplish it, and the results achieved.<br />
<br />
******<br />
The Department of Brain and Cognitive Sciences (Course IX) began as the Department of Psychology in 1964.[4]<br />
<br />
****<br />
<br />
Niklaus von Flue, Nicholas of Flühe or brother Klaus (* 1417 ; † 21 March 1487 in Flüeli at Sachseln in the canton of Obwalden ) was a Swiss hermit , ascetic and mystic . He is the patron saint of Switzerland.<br />
<br />
From &lt;&lt;http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Niklaus_von_Fl%25C3%25BCe&amp;usg=ALkJrhg49HZRF0nkWXbl5N4OPvyGPgXZBw&gt;&gt;<br />
<br />
<br />
On March 21, 1487 Brother Klaus died after a hard agony on the floor of his cell.<br />
<br />
From &lt;&lt;http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Niklaus_von_Fl%25C3%25BCe&amp;usg=ALkJrhg49HZRF0nkWXbl5N4OPvyGPgXZBw&gt;&gt;<br />
<br />
Niklaus von Flue gained widely reputation as pastor and spiritual advisor, not only for the rural population, but also as a guide for foreign heads of state in Europe in the 15th century. So says a special envoy of the Duchy of Milan, in a letter to Ludovico Sforza of visits to the hermit, where he discussed political issues, and the Duke thanked in the response for its gracious greetings. [3]<br />
Nicholas of Flue was also interested in a mystic in worldly things. He watched the political events and was asked for advice on such matters.<br />
<br />
From &lt;&lt;http://translate.googleusercontent.com/translate_c?depth=1&amp;hl=en&amp;rurl=translate.google.com&amp;sandbox=0&amp;sl=auto&amp;tl=en&amp;u=http://de.wikipedia.org/wiki/Niklaus_von_Fl%25C3%25BCe&amp;usg=ALkJrhg49HZRF0nkWXbl5N4OPvyGPgXZBw&gt;&gt;<br />
<br />
<br />
The origins of Nazism and its relation to the occult have been a part of popular culture since at least 1959. There are documentaries and books on the topic, including The Morning of the Magicians (1960) and The Spear of Destiny (1972). Historian Nicholas Goodrick-Clarke analyzed the topic in The Occult Roots of Nazism in which he argued there were links between some ideals of Ariosophy and Nazi ideology. He also analyzed the problems of the numerous popular "occult historiography" books written on the topic. He sought to separate empiricism and sociology from the "Modern Mythology of Nazi Occultism" that exist in many books which "have represented the Nazi phenomenon as the product of arcane and demonic influence". He considered most of these to be "sensational and under-researched".[1]<br />
<br />
From <a href="http://en.wikipedia.org/wiki/Nazism_and_occultism">http://en.wikipedia.org/wiki/Nazism_and_occultism</a><br />
<i></i><br />
<br />
<a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br />
<br />
To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br />
<br />
For Non-Fiction stories with a lesson by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a><br />
<br />
<br />
<br />
<br />
<br />
<div style="clear: both; float: left; padding-bottom: 10px; text-align: right;">
<br /></div>
