---
title: 'Greek gods... study research'
date: '2015-06-18T05:10:00.0000000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '7026236386026507369'
blogger_filename: '/2015/06/greek-gods-study-research.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Research'
---

<br />
<br />
<br />
<br />
<br />
<br />
<br />
http://www.rickriordan.com/books/percy-jacksons-world/resources/explore-greek-mythology/meet-the-greek-gods<br />
<br />
<br />
Hecate: goddess of magic and ghosts.<br />
<br />
https://en.wikipedia.org/wiki/Hecate<br />
<br />
<div style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px; margin-bottom: 0.5em; margin-top: 0.5em;">
<b>Hecate</b>&nbsp;or&nbsp;<b>Hekate</b>&nbsp;(<span class="nowrap" style="white-space: nowrap;"><span class="IPA" title="Representation in the International Phonetic Alphabet (IPA)"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English">/</a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="/ˈ/ primary stress follows">ˈ</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="'h' in 'hi'">h</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="/ɛ/ short 'e' in 'bed'">ɛ</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="'k' in 'kind'">k</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="/ə/ 'a' in 'about'">ə</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="'t' in 'tie'">t</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="/iː/ long 'e' in 'bead'">iː</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English">,</a></span>&nbsp;<span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="/ˈ/ primary stress follows">ˈ</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="'h' in 'hi'">h</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="/ɛ/ short 'e' in 'bed'">ɛ</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="'k' in 'kind'">k</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="/ɪ/ short 'i' in 'bid'">ɪ</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="'t' in 'tie'">t</span></a></span><span class="IPA" title="Representation in the International Phonetic Alphabet (IPA)"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English">/</a></span></span>;&nbsp;<a href="https://en.wikipedia.org/wiki/Ancient_Greek" style="background: none; color: #0b0080; text-decoration: none;" title="Ancient Greek">Greek</a>&nbsp;Ἑκάτη,&nbsp;<i>Hekátē</i>) is a goddess in Greek&nbsp;<a class="mw-redirect" href="https://en.wikipedia.org/wiki/Religion_in_Ancient_Greece" style="background: none; color: #0b0080; text-decoration: none;" title="Religion in Ancient Greece">religion</a>&nbsp;and&nbsp;<a href="https://en.wikipedia.org/wiki/Greek_mythology" style="background: none; color: #0b0080; text-decoration: none;" title="Greek mythology">mythology</a>, most often shown holding two torches or a key<sup class="reference" id="cite_ref-Charles_M_1986_pp._307-318_1-0" style="font-size: 11.1999998092651px; line-height: 1; unicode-bidi: -webkit-isolate;"><a href="https://en.wikipedia.org/wiki/Hecate#cite_note-Charles_M_1986_pp._307-318-1" style="background: none; color: #0b0080; text-decoration: none; white-space: nowrap;">[1]</a></sup>&nbsp;and in later periods depicted in triple form. She was variously associated with crossroads, entrance-ways, dogs, light, the&nbsp;<a href="https://en.wikipedia.org/wiki/Moon" style="background: none; color: #0b0080; text-decoration: none;" title="Moon">moon</a>,&nbsp;<a href="https://en.wikipedia.org/wiki/Magic_(paranormal)" style="background: none; color: #0b0080; text-decoration: none;" title="Magic (paranormal)">magic</a>,&nbsp;<a href="https://en.wikipedia.org/wiki/Witchcraft" style="background: none; color: #0b0080; text-decoration: none;" title="Witchcraft">witchcraft</a>, knowledge of herbs and poisonous plants, ghosts, necromancy, and sorcery.<sup class="reference" id="cite_ref-2" style="font-size: 11.1999998092651px; line-height: 1; unicode-bidi: -webkit-isolate;"><a href="https://en.wikipedia.org/wiki/Hecate#cite_note-2" style="background: none; color: #0b0080; text-decoration: none; white-space: nowrap;">[2]</a></sup><sup class="reference" id="cite_ref-autogenerated1_3-0" style="font-size: 11.1999998092651px; line-height: 1; unicode-bidi: -webkit-isolate;"><a href="https://en.wikipedia.org/wiki/Hecate#cite_note-autogenerated1-3" style="background: none; color: #0b0080; text-decoration: none; white-space: nowrap;">[3]</a></sup>&nbsp;In the post-Christian writings of the&nbsp;<a href="https://en.wikipedia.org/wiki/Chaldean_Oracles" style="background: none; color: #0b0080; text-decoration: none;" title="Chaldean Oracles">Chaldean Oracles</a>&nbsp;(2nd-3rd century CE) she was regarded with (some) rulership over earth, sea and sky, as well as a more universal role as Saviour (Soteira), Mother of Angels and the Cosmic World Soul.<sup class="reference" id="cite_ref-4" style="font-size: 11.1999998092651px; line-height: 1; unicode-bidi: -webkit-isolate;"><a href="https://en.wikipedia.org/wiki/Hecate#cite_note-4" style="background: none; color: #0b0080; text-decoration: none; white-space: nowrap;">[4]</a></sup><sup class="reference" id="cite_ref-5" style="font-size: 11.1999998092651px; line-height: 1; unicode-bidi: -webkit-isolate;"><a href="https://en.wikipedia.org/wiki/Hecate#cite_note-5" style="background: none; color: #0b0080; text-decoration: none; white-space: nowrap;">[5]</a></sup>&nbsp;She was one of the main deities worshiped in Athenian households as a protective goddess and one who bestowed prosperity and daily blessings on the family.<sup class="reference" id="cite_ref-6" style="font-size: 11.1999998092651px; line-height: 1; unicode-bidi: -webkit-isolate;"><a href="https://en.wikipedia.org/wiki/Hecate#cite_note-6" style="background: none; color: #0b0080; text-decoration: none; white-space: nowrap;">[6]</a></sup></div>
<div style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px; margin-bottom: 0.5em; margin-top: 0.5em;">
Hecate may have originated among the&nbsp;<a href="https://en.wikipedia.org/wiki/Carians" style="background: none; color: #0b0080; text-decoration: none;" title="Carians">Carians</a>&nbsp;of&nbsp;<a href="https://en.wikipedia.org/wiki/Anatolia" style="background: none; color: #0b0080; text-decoration: none;" title="Anatolia">Anatolia</a>, where variants of her name are found as names given to children. William Berg observes, "Since children are not called after spooks, it is safe to assume that Carian theophoric names involving&nbsp;<i>hekat-</i>refer to a major deity free from the dark and unsavoury ties to the underworld and to witchcraft associated with the Hecate of classical Athens."<sup class="reference" id="cite_ref-7" style="font-size: 11.1999998092651px; line-height: 1; unicode-bidi: -webkit-isolate;"><a href="https://en.wikipedia.org/wiki/Hecate#cite_note-7" style="background: none; color: #0b0080; text-decoration: none; white-space: nowrap;">[7]</a></sup>&nbsp;She also closely parallels the Roman goddess&nbsp;<a href="https://en.wikipedia.org/wiki/Trivia_(mythology)" style="background: none; color: #0b0080; text-decoration: none;" title="Trivia (mythology)">Trivia</a>, with whom she was identified in Rome.</div>
<br />
<br />
<br />
https://en.wikipedia.org/wiki/Trivia_(mythology)<br />
<br />
<div style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px; margin-bottom: 0.5em; margin-top: 0.5em;">
<b>Trivia</b>&nbsp;in&nbsp;<a href="https://en.wikipedia.org/wiki/Roman_mythology" style="background: none; color: #0b0080;" title="Roman mythology">Roman mythology</a>&nbsp;was the goddess who "haunted crossroads, graveyards, and was the goddess of sorcery and witchcraft, she wandered about at night and was seen only by the barking of dogs who told of her approach."<sup class="reference" id="cite_ref-Zimmerman_1-0" style="font-size: 11.1999998092651px; line-height: 1; unicode-bidi: -webkit-isolate;"><a href="https://en.wikipedia.org/wiki/Trivia_(mythology)#cite_note-Zimmerman-1" style="background: none; color: #0b0080; text-decoration: none; white-space: nowrap;">[1]</a></sup>&nbsp;She was the equivalent of the&nbsp;<a href="https://en.wikipedia.org/wiki/Greek_mythology" style="background: none; color: #0b0080; text-decoration: none;" title="Greek mythology">Greek</a>&nbsp;goddess&nbsp;<a href="https://en.wikipedia.org/wiki/Hecate" style="background: none; color: #0b0080; text-decoration: none;" title="Hecate">Hecate</a>, the goddess of&nbsp;<a href="https://en.wikipedia.org/wiki/Witchcraft" style="background: none; color: #0b0080; text-decoration: none;" title="Witchcraft">witchcraft</a>, the three-way crossroads and the harvest moon.<sup class="reference" id="cite_ref-2" style="font-size: 11.1999998092651px; line-height: 1; unicode-bidi: -webkit-isolate;"><a href="https://en.wikipedia.org/wiki/Trivia_(mythology)#cite_note-2" style="background: none; color: #0b0080; text-decoration: none; white-space: nowrap;">[2]</a></sup>&nbsp;She was an underworld&nbsp;<a href="https://en.wikipedia.org/wiki/Titan_(mythology)" style="background: none; color: #0b0080; text-decoration: none;" title="Titan (mythology)">Titan</a>-goddess who assisted&nbsp;<a class="mw-redirect" href="https://en.wikipedia.org/wiki/Jove" style="background: none; color: #0b0080; text-decoration: none;" title="Jove">Jove</a>&nbsp;in the&nbsp;<a href="https://en.wikipedia.org/wiki/Titanomachy" style="background: none; color: #0b0080; text-decoration: none;" title="Titanomachy">Titanomachy</a>&nbsp;and was therefore able to keep her powers. She was a friend of&nbsp;<a class="mw-redirect" href="https://en.wikipedia.org/wiki/Ceres_(Roman_mythology)" style="background: none; color: #0b0080; text-decoration: none;" title="Ceres (Roman mythology)">Ceres</a>&nbsp;and helped her to find her daughter&nbsp;<a href="https://en.wikipedia.org/wiki/Proserpina" style="background: none; color: #0b0080; text-decoration: none;" title="Proserpina">Proserpina</a>. As a part of her role as an underworld goddess, she was known as the Queen of Ghosts. Although she helped Ceres to find her daughter, she was also known to steal young maidens to assist her in her powers. These women later became&nbsp;<a href="https://en.wikipedia.org/wiki/Nymph" style="background: none; color: #0b0080; text-decoration: none;" title="Nymph">nymphs</a>.</div>
<div style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px; margin-bottom: 0.5em; margin-top: 0.5em;">
Her association for Romans of the first century BCE with&nbsp;<a href="https://en.wikipedia.org/wiki/Artemis" style="background: none; color: #0b0080; text-decoration: none;" title="Artemis">Artemis</a>&nbsp;was so thorough that&nbsp;<a href="https://en.wikipedia.org/wiki/Lucretius" style="background: none; color: #0b0080; text-decoration: none;" title="Lucretius">Lucretius</a><sup class="reference" id="cite_ref-3" style="font-size: 11.1999998092651px; line-height: 1; unicode-bidi: -webkit-isolate;"><a href="https://en.wikipedia.org/wiki/Trivia_(mythology)#cite_note-3" style="background: none; color: #0b0080; text-decoration: none; white-space: nowrap;">[3]</a></sup>&nbsp;identifies the altar of the goddess at the sacrifice of&nbsp;<a href="https://en.wikipedia.org/wiki/Iphianassa" style="background: none; color: #0b0080; text-decoration: none;" title="Iphianassa">Iphianassa</a>&nbsp;(<a class="mw-redirect" href="https://en.wikipedia.org/wiki/Iphigeneia" style="background: none; color: #0b0080; text-decoration: none;" title="Iphigeneia">Iphigeneia</a>) in Aulis as&nbsp;<i>Triviai virginis aram</i>.</div>
<br />
<br />
Nemesis, judge jury and executioner<br />
<br />
<span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">In&nbsp;</span><a href="https://en.wikipedia.org/wiki/Ancient_Greek_religion" style="background: none rgb(255, 255, 255); color: #0b0080; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px; text-decoration: none;" title="Ancient Greek religion">ancient Greek religion</a><span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">,&nbsp;</span><b style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">Nemesis</b><span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">&nbsp;(</span><span class="nowrap" style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px; white-space: nowrap;"><span class="IPA" title="Representation in the International Phonetic Alphabet (IPA)"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English">/</a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="/ˈ/ primary stress follows">ˈ</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="'n' in 'no'">n</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="/ɛ/ short 'e' in 'bed'">ɛ</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="'m' in 'my'">m</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="/ə/ 'a' in 'about'">ə</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="'s' in 'sigh'">s</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="/ɪ/ short 'i' in 'bid'">ɪ</span></a></span><span class="IPA nopopups"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English#Key" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English"><span style="border-bottom-style: dotted; border-bottom-width: 1px;" title="'s' in 'sigh'">s</span></a></span><span class="IPA" title="Representation in the International Phonetic Alphabet (IPA)"><a href="https://en.wikipedia.org/wiki/Help:IPA_for_English" style="background: none; color: #0b0080; text-decoration: none !important;" title="Help:IPA for English">/</a></span></span><span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">;&nbsp;</span><a href="https://en.wikipedia.org/wiki/Greek_language" style="background: none rgb(255, 255, 255); color: #0b0080; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px; text-decoration: none;" title="Greek language">Greek</a><span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">:&nbsp;</span><span lang="grc" style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;" xml:lang="grc">Νέμεσις</span><span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">), also called&nbsp;</span><b style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">Rhamnousia/Rhamnusia</b><span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">&nbsp;("the&nbsp;</span><a href="https://en.wikipedia.org/wiki/Goddess" style="background: none rgb(255, 255, 255); color: #0b0080; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px; text-decoration: none;" title="Goddess">goddess</a><span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">&nbsp;of&nbsp;</span><a href="https://en.wikipedia.org/wiki/Rhamnous" style="background: none rgb(255, 255, 255); color: #0b0080; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px; text-decoration: none;" title="Rhamnous">Rhamnous</a><span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">") at her sanctuary at&nbsp;</span><a href="https://en.wikipedia.org/wiki/Rhamnous" style="background: none rgb(255, 255, 255); color: #0b0080; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px; text-decoration: none;" title="Rhamnous">Rhamnous</a><span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">, north of&nbsp;</span><a href="https://en.wikipedia.org/wiki/Marathon,_Greece" style="background: none rgb(255, 255, 255); color: #0b0080; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px; text-decoration: none;" title="Marathon, Greece">Marathon</a><span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">, was the spirit of divine&nbsp;</span><a href="https://en.wikipedia.org/wiki/Retributive_justice" style="background: none rgb(255, 255, 255); color: #0b0080; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px; text-decoration: none;" title="Retributive justice">retribution</a><span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">&nbsp;against those who succumb to&nbsp;</span><a href="https://en.wikipedia.org/wiki/Hubris" style="background: none rgb(255, 255, 255); color: #0b0080; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px; text-decoration: none;" title="Hubris">hubris</a><span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">&nbsp;(arrogance before the gods). Another name was&nbsp;</span><b style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">Adrasteia</b><span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">, meaning "the inescapable."</span><sup class="reference" id="cite_ref-1" style="background-color: white; color: #252525; font-family: sans-serif; font-size: 11.1999998092651px; line-height: 1; unicode-bidi: -webkit-isolate;"><a href="https://en.wikipedia.org/wiki/Nemesis_(mythology)#cite_note-1" style="background: none; color: #0b0080; text-decoration: none; white-space: nowrap;">[1]</a></sup><br />
<br />
<h2 style="background: none rgb(255, 255, 255); border-bottom-color: rgb(170, 170, 170); border-bottom-style: solid; border-bottom-width: 1px; font-family: 'Linux Libertine', Georgia, Times, serif; font-weight: normal; line-height: 1.3; margin: 1em 0px 0.25em; overflow: hidden; padding: 0px;">
<span class="mw-headline" id="Etymology">Etymology</span><span class="mw-editsection" style="-webkit-user-select: none; display: inline-block; font-family: sans-serif; font-size: x-small; line-height: 1em; margin-left: 1em; unicode-bidi: -webkit-isolate; vertical-align: baseline; white-space: nowrap;"><span class="mw-editsection-bracket" style="color: #555555; margin-left: 0px; margin-right: 0px;">[</span><a href="https://en.wikipedia.org/w/index.php?title=Nemesis_(mythology)&amp;action=edit&amp;section=1" style="background: none; color: #0b0080; text-decoration: none;" title="Edit section: Etymology">edit</a><span class="mw-editsection-bracket" style="color: #555555; margin-left: 0px; margin-right: 0px;">]</span></span></h2>
<div style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px; margin-bottom: 0.5em; margin-top: 0.5em;">
The name&nbsp;<i>Nemesis</i>&nbsp;is related to the&nbsp;<a href="https://en.wikipedia.org/wiki/Greek_language" style="background: none; color: #0b0080; text-decoration: none;" title="Greek language">Greek</a>&nbsp;word νέμειν&nbsp;<i>némein</i>, meaning "to give what is due",<sup class="reference" id="cite_ref-2" style="font-size: 11.1999998092651px; line-height: 1; unicode-bidi: -webkit-isolate;"><a href="https://en.wikipedia.org/wiki/Nemesis_(mythology)#cite_note-2" style="background: none; color: #0b0080; text-decoration: none; white-space: nowrap;">[2]</a></sup>&nbsp;from&nbsp;<a class="mw-redirect" href="https://en.wikipedia.org/wiki/Proto-Indo-European" style="background: none; color: #0b0080; text-decoration: none;" title="Proto-Indo-European">Proto-Indo-European</a>&nbsp;<i>nem-</i>&nbsp;"distribute".<sup class="reference" id="cite_ref-3" style="font-size: 11.1999998092651px; line-height: 1; unicode-bidi: -webkit-isolate;"><a href="https://en.wikipedia.org/wiki/Nemesis_(mythology)#cite_note-3" style="background: none; color: #0b0080; text-decoration: none; white-space: nowrap;">[3]</a></sup></div>
<h2 style="background: none rgb(255, 255, 255); border-bottom-color: rgb(170, 170, 170); border-bottom-style: solid; border-bottom-width: 1px; font-family: 'Linux Libertine', Georgia, Times, serif; font-weight: normal; line-height: 1.3; margin: 1em 0px 0.25em; overflow: hidden; padding: 0px;">
<span class="mw-headline" id="Background">Background</span><span class="mw-editsection" style="-webkit-user-select: none; display: inline-block; font-family: sans-serif; font-size: x-small; line-height: 1em; margin-left: 1em; unicode-bidi: -webkit-isolate; vertical-align: baseline; white-space: nowrap;"><span class="mw-editsection-bracket" style="color: #555555; margin-left: 0px; margin-right: 0px;">[</span><a href="https://en.wikipedia.org/w/index.php?title=Nemesis_(mythology)&amp;action=edit&amp;section=2" style="background: none; color: #0b0080; text-decoration: none;" title="Edit section: Background">edit</a><span class="mw-editsection-bracket" style="color: #555555; margin-left: 0px; margin-right: 0px;">]</span></span></h2>
<div style="background-color: white; color: #252525; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px; margin-bottom: 0.5em; margin-top: 0.5em;">
Divine retribution is a major theme in the&nbsp;<a href="https://en.wikipedia.org/wiki/Hellenistic_period" style="background: none; color: #0b0080; text-decoration: none;" title="Hellenistic period">Hellenic</a>&nbsp;world view, providing the unifying theme of the&nbsp;<a href="https://en.wikipedia.org/wiki/Greek_tragedy" style="background: none; color: #0b0080; text-decoration: none;" title="Greek tragedy">tragedies</a>&nbsp;of&nbsp;<a href="https://en.wikipedia.org/wiki/Sophocles" style="background: none; color: #0b0080; text-decoration: none;" title="Sophocles">Sophocles</a>&nbsp;and many other literary works.<sup class="reference" id="cite_ref-4" style="font-size: 11.1999998092651px; line-height: 1; unicode-bidi: -webkit-isolate;"><a href="https://en.wikipedia.org/wiki/Nemesis_(mythology)#cite_note-4" style="background: none; color: #0b0080; text-decoration: none; white-space: nowrap;">[4]</a></sup><sup class="reference" id="cite_ref-5" style="font-size: 11.1999998092651px; line-height: 1; unicode-bidi: -webkit-isolate;"><a href="https://en.wikipedia.org/wiki/Nemesis_(mythology)#cite_note-5" style="background: none; color: #0b0080; text-decoration: none; white-space: nowrap;">[5]</a></sup>&nbsp;<a href="https://en.wikipedia.org/wiki/Hesiod" style="background: none; color: #0b0080; text-decoration: none;" title="Hesiod">Hesiod</a>&nbsp;states: "Also deadly&nbsp;<a class="mw-redirect" href="https://en.wikipedia.org/wiki/Nyx_(mythology)" style="background: none; color: #0b0080; text-decoration: none;" title="Nyx (mythology)">Nyx</a>&nbsp;bore Nemesis an affliction to mortals subject to death." (<i><a href="https://en.wikipedia.org/wiki/Theogony" style="background: none; color: #0b0080; text-decoration: none;" title="Theogony">Theogony</a></i>, 223, though perhaps an interpolated line). Nemesis appears in a still more concrete form in a fragment of the epic&nbsp;<i><a href="https://en.wikipedia.org/wiki/Cypria" style="background: none; color: #0b0080; text-decoration: none;" title="Cypria">Cypria</a></i>.</div>
<br />
<br />
https://en.wikipedia.org/wiki/List_of_Greek_mythological_figures<br />
<br />
<br />
Zues (Greek) - &nbsp;Jupiter (Roman), also known as Jove.<br />
<br />
He was the god of the gods, father of them Satan would have chosen this for himself.<br />
<br />
Note the similarities between the propagation of the gods in Greek mythology, and the propagation of angels in Gen 5-6.<br />
<br />
<br />
<br />