---
title: 'The God Frequency'
date: '2015-07-20T06:49:00.0050000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '2359423471929562512'
blogger_filename: '/2015/07/the-god-frequency.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Research'
---

<br />
<br />
<br />
Research:<br />
<br />
People are talking about their ideas on "The God Frequency". Interesting fiction fodder.<br />
<br />
---------------------------------------------------------------------------<br />
<br />
<div style="border-width: 100%; direction: ltr;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.6041in;">

<div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.6041in;">

<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #222222; font-family: Calibri; font-size: 18.0pt; margin-bottom: 9pt; margin-top: 0pt;">
The 6 Tones Of Creation (God's Healing Frequencies)</div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="https://www.youtube.com/watch?v=4Tno4L-6vP4">https://www.youtube.com/watch?v=4Tno4L-6vP4</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; line-height: 12pt; margin: 0in;">
<span style="font-weight: bold;">Published on Dec 24, 2013</span></div>
<div style="font-family: Calibri; margin: 0in;">
<a href="http://youarecreators.org/"><span style="font-size: 9.75pt;">http://youarecreators.org/</span></a><span style="color: #333333; font-size: 9.75pt;">&nbsp;We (YouAreCreators) created this
channel to share one of the greatest secrets of the universe, and the secret
is, we literally create our reality! (Quantum Physics now proves this) We are
all governed by a set of Universal Laws, and these laws were created by GOD, to
aid us in creating the life we desire. One of these laws is known as the
"Law Of Attraction", or the law of "Reaping and Sowing".
This law simply states, whatever you give out in Thought, Word, Feeling, and
Action is returned to you. Whether the return is negative, or positive, failure
or success, is all up to what you give out. Many authors and celebrities such
as, Wayne Dyer, Oprah Winfrey, Will Smith, Jim Carrey, Steve Harvey, Rhonda
Byrne, and many others has testified to this amazing Law Of Attraction. Its
time you learn this wonderful secret...</span></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
Sleep
or meditate with these frequencies playing.</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
These
Solfeggio frequencies make up the sacred Solfeggio scale:</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
UT --
396 Hz</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
Intent:
turning grief into joy, liberating guilt &amp; fear</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
This
frequency liberates the energy and has beneficial effects on feelings of guilt.
It cleanses the feeling of guilt, which often represents one of the basic
obstacles to realization, enabling achievement of goals in the most direct way.
The 'Ut' tone releases you from the feeling of guilt and fear by bringing down
the defense mechanisms. 396 Hz frequency searches out hidden blockages,
subconscious negative beliefs, and ideas that have led to your present
situations.</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
RE --
417 Hz</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
Intent:
undoing situations and facilitating change</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
The
next main tone from the Solfeggio scale produces energy to bring about change.
This frequency cleanses traumatic experiences and clears destructive influences
of past events. When speaking of cellular processes, tone 'Re' encourages the
cell and its functions in an optimal way. 417 Hz frequency puts you in touch
with an inexhaustible source of energy that allows you to change your life.</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
MI --
528 Hz</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
Intent:
transformation and miracles (DNA repair)</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
Tone
'Mi' is used to return human DNA to its original, perfect state. This frequency
brings transformation and miracles into your life. The process of DNA
reparation is followed by beneficial effects -- increased amount of life
energy, clarity of mind, awareness, awakened or activated creativity, ecstatic
states like deep inner peace, dance and celebration. Tone 'Mi' activates your
imagination, intention and intuition to operate for your highest and best
purpose.</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
FA --
639 Hz</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
Intent:
re-connecting and balancing, relationships</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
Another
frequency from the sacred Solfeggio scale. It enables creation of harmonious
community and harmonious interpersonal relationships. Tone 'Fa' can be used for
dealing with relationships problems -- those in family, between partners,
friends or social problems. When talking about cellular processes, 639 Hz
frequency can be used to encourage the cell to communicate with its
environment. This ancient Solfeggio frequency enhances communication,
understanding, tolerance and love.</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
SOL --
741 Hz</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
Intent:
solving problems, expressions/solutions</div>
<div style="color: #333333; font-family: Calibri; font-size: 9.75pt; margin: 0in;">
It
cleans the cell ("Solve polluti") from the toxins. Frequent use of
741 Hz leads to a healthier, simpler life, and also to changes in diet towards
foods which are not poisoned by various kinds of toxins. Tone 'Sol' cleans the
cell from different kinds of electromagnetic radiations. Another application of
this sound frequency is solving problems of any nature. The fifth frequency of
the Solfeggio scale will also lead you into the power of self-expression, which
results in a pure and stable life.</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #222222; font-family: Calibri; font-size: 18.0pt; margin-bottom: 9pt; margin-top: 0pt;">
The Frequency and Sound of God = 528 Hertz ~ by Zeph Daniel</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="https://www.youtube.com/watch?v=q7VM7dvYkeU">https://www.youtube.com/watch?v=q7VM7dvYkeU</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #222222; font-family: Calibri; font-size: 18.0pt; margin-bottom: 9pt; margin-top: 0pt;">
528 Hz | Miracle Tone</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="https://www.youtube.com/watch?v=6xpI00ShS4M">https://www.youtube.com/watch?v=6xpI00ShS4M</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #222222; font-family: Calibri; font-size: 18.0pt; margin-bottom: 9pt; margin-top: 0pt;">
Ancient Miracle Music: Solfeggio 528 Hz, Repair DNA, Healing
tones of love</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
According to Dr.
Leonard Horowitz, 528 Hertz is a frequency that is central to the “musical
mathematical matrix of creation.”&nbsp;</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="https://www.youtube.com/watch?v=VsPxHfHuhfI">https://www.youtube.com/watch?v=VsPxHfHuhfI</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #222222; font-family: Calibri; font-size: 12.0pt; line-height: 22pt; margin: 0in;">
<span style="background: #F4F4F4;">The first time Ivan Yanakiev
heard an instrument tuned to 432 Hertz, he says, it was like he’d heard God
speak.</span></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="http://motherboard.vice.com/read/the-fringe-audiophiles-who-want-to-topple-standard-tuning">http://motherboard.vice.com/read/the-fringe-audiophiles-who-want-to-topple-standard-tuning</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #373737; font-family: Calibri; font-size: 11.25pt; line-height: 18pt; margin: 0in;">
<span style="background: #E2E2E2;">Dr. Leonard G. Horowitz (Dr Len
Horowitz) is the world’s most prolific, best credential, and most controversial
drug industry whistleblower.</span></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
- See more at: <a href="http://drlenhorowitz.com/about/#sthash.3ieXHI5D.dpuf">http://drlenhorowitz.com/about/#sthash.3ieXHI5D.dpuf</a></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="http://drlenhorowitz.com/about/">http://drlenhorowitz.com/about/</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
HA HA HA HA!....
Seriously? This man is FULL of himself. He has demonic written all over him. </div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: white; font-family: Verdana; font-size: 9.0pt; line-height: 13pt; margin: 0in;">
<span style="background: #21103E;">&nbsp;</span><span style="background: #21103E; font-weight: bold;">Quantum Musicology™</span><span style="background: #21103E;">&nbsp;is a new medium using the universal principal
of music.</span></div>
<div style="color: white; font-family: Verdana; font-size: 9.0pt; line-height: 13pt; margin: 0in;">
<span style="background: #21103E;">Music has always been the centre
of true communication through the sensation of tone and metaphysical
experience.</span></div>
<div style="color: white; font-family: Verdana; font-size: 9.0pt; line-height: 13pt; margin: 0in;">
<span style="background: #21103E;">I have combined a lifetime of
research and experience into a masterful modality which incorporates astrology,
numerology, music and mathematics with the use of time, space, rhythm, colour
and tempo.</span></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="http://www.briantcollins.com/?page_id=506">http://www.briantcollins.com/?page_id=506</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #222222; font-family: Calibri; font-size: 18.0pt; margin-bottom: 9pt; margin-top: 0pt;">
Theta Binaural Beat (7hz) ~ Pure</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="https://www.youtube.com/watch?v=E5G6mLNfayA">https://www.youtube.com/watch?v=E5G6mLNfayA</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Arial; font-size: 11pt; margin: 0in;">
<span style="background: white;">Nicola Tesla, the Croatian born inventor, had
performed experiments at the turn of the century that revealed that air, at its
ordinary pressure, is a conductor for large amounts of electrical energy over
great distances without wires. This meant a few things: That electrical use for
the purposes of man would be available at any place on the globe. And that
electricity traveling through the air shows how frequencies and waves of
powerful energy do not need wires to be generated at one place and received in
another. Furthermore, it is of the opinion of some that the mathematics that
provide the underpinning for Tesla's work also provides the basis for
understanding telepathy. This suggests the openings of vast potentials for the
human mind.</span></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="http://www.stephen-knapp.com/frequencies_that_can_kill.htm">http://www.stephen-knapp.com/frequencies_that_can_kill.htm</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Arial; font-size: 11pt; margin: 0in;">
<span style="background: white;">However, in the late 1970s, there was widespread
cattle deaths in Oregon. It was determined by research that the cattle had been
killed by adverse ELF radio frequency transmissions from the Russians. It seems
that man is a bio-cosmic transducer, a transmitter and receiver as well, and
that somehow our brain waves can lock on and modulate with the earth's
electromagnetic field, the Universal Magnetic Field (UMF), as Tesla called it.
Research has shown that altering these electro magnetic fields can influence
the brain waves of cats and monkeys. Humans are also affected.</span></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="http://www.stephen-knapp.com/frequencies_that_can_kill.htm">http://www.stephen-knapp.com/frequencies_that_can_kill.htm</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Arial; font-size: 11pt; margin: 0in;">
<span style="background: white;">Researchers have found that frequencies under seven
hertz create a general feeling of relaxation and well being, known as the alpha
state. The most beneficial frequency on earth is said to be the 6.8 hertz
frequency. Interestingly, the Pyramid at Giza has a constant frequency of 6.8
hertz running through it. Although researchers have studied it, they don't know
where it comes from or why in such an ancient structure.</span></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="http://www.stephen-knapp.com/frequencies_that_can_kill.htm">http://www.stephen-knapp.com/frequencies_that_can_kill.htm</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Arial; font-size: 11pt; margin: 0in;">
<span style="background: white;">Thus, by absorbing one's consciousness in the sound
vibration of these names of God, it will do several things, such as alter and
improve the electrical impulses that are generated by the body, and help defend
oneself from the negative impulses that one may encounter. In this way, it
helps create a peaceful attitude within the individual and a healthier
disposition. It also prepares one's consciousness for perceiving higher levels
of reality, opens one up to the spiritual world, gradually reveals one's true
spiritual identity, which would also allow one to see the unity between all
people. It also harmonizes one's existence with nature, and even begins to
rekindle one's real relationship with the Supreme Soul, God. Once the higher
vibration of the spiritual realm is invoked on a regular basis in this way, and
is opened for its use among the people in general, the chances for world change
become enormous.</span></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="color: #595959; font-family: Calibri; font-size: 9.0pt; margin: 0in;">
From
&lt;<a href="http://www.stephen-knapp.com/frequencies_that_can_kill.htm">http://www.stephen-knapp.com/frequencies_that_can_kill.htm</a>&gt;
</div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
<br /></div>
<div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">
*</div>
</div>
</div>
</div>
