---
title: 'Walter Elias Vanderbilt / Darkmater (Moriarty)'
date: '2015-12-02T05:07:00.0040000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '4191984311684241733'
blogger_filename: '/2015/12/walter-elias-vanderbilt-darkmater.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Character Sketch'
---

<br />
<br />
<br />
<div style="margin: 0in 0in 0.0001pt;">
</div>
<br />
<div style="margin-bottom: .0001pt; margin-bottom: 0in; margin-left: .5in; margin-right: 0in; margin-top: 0in; mso-list: l0 level1 lfo1; text-indent: -.25in;">
<div style="margin: 0px;">
<span style="font-family: &quot;symbol&quot;;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span style="font-family: &quot;georgia&quot; , serif;">Character Sketch Template (<a href="https://www.udemy.com/blog/character-sketch-examples/">Hints</a>)(<a href="https://en.wikipedia.org/wiki/Now,_Discover_Your_Strengths" target="_blank">Strengths List</a>)(<a href="https://www.isa.org/templates/two-column.aspx?pageid=134103&amp;append=35734" target="_blank">Strengths details</a>)(<a href="http://www.16personalities.com/personality-types" target="_blank">16P-Types</a>)(<a href="http://www.16personalities.com/articles/our-theory" target="_blank">16P-Theory</a>)<o:p></o:p></span></div>
</div>
<br />
<br />
Character’s Name: Elias Vanderbilt / Dark Elf<br />
<br />
Elias Vanderbilt was a trust fund kid, who flunked out of MIT. But not for lack of ability. He was a member of the Center for Brains Minds &amp; Machines (CBMM), and Master of Science (M.Sci.) graduate student majoring in Integrative Research on Intelligence. He was working on a project to map the code required to duplicate aspects of the human mind. Specifically, those that relate to the phenomenon of what are called spiritual experiences.<br />
<br />
One day, the he just disappeared for weeks. When he comes back to school, he doesn't know where he has been, and he's acting strangely. Then he disappears again, this time (as far as his fellow students are concerned) he's missing for good.<br />
<br />
Actually, he's been operating underground under the hacker alias "Dark Elf". He's been coding programs for nefarious purposes, and making a decent living doing so. He blacks out for long periods, and when he comes back to himself, he has inspirational ideas for new code and programs, which he sells on the Hacker Black-Market.<br />
<br />
During those periods of black out he's come to a realization… he could make the biggest sale of his life by creating a program to detect terrorist attacks. He's already built it, and tried to sell it to Military Technology Companies and the Government. But he can't even get an audience. So he's decided to use his ability to hide his digital footprint, to recruit terrorists to plant a bomb at the Macy's Thanksgiving Day Parade. This way, there will be an instant market for his program, and bidders to buy it from the best of the best agencies around the world.<br />
<br />
He's so sure that he's hidden his digital foot print, and that nobody will ever discover he was the one who master minded the attack… but he's unaware that he himself, is just a tool of the test he was subjected to. There are those who can stop him. And they are coming…<br />
<br />
<br />
<div style="margin-bottom: .0001pt; margin-bottom: 0in; margin-left: .5in; margin-right: 0in; margin-top: 0in; mso-list: l0 level1 lfo1; text-indent: -.25in;">
<span style="font-family: &quot;symbol&quot;;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span style="font-family: &quot;georgia&quot; , serif;">Character Sketch Template (<a href="https://www.udemy.com/blog/character-sketch-examples/">Hints</a>)<o:p></o:p></span></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Hello my name is Amy Truthfinder, and I’m here with xxxxxxxx from the xxxxxxx series, to find out more about him/her and get a little behind the scenes information.<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<b><span style="font-family: &quot;georgia&quot; , serif;">In the way of introductions:<o:p></o:p></span></b></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Xxxxxxx is a Primary/Supporting character in the book xxxxx. He has chosen to side with the (Good/Bad/ Neither, he remains neutral, is unware of the sides).<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Xxxxxx was born on xx/xx/xx, which makes him xxxx years old as of xx/xx/xx.<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">He/She has the following distinct physical characteristics; xxxxxxxxxxxxxxxxxxx.<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<b><span style="font-family: &quot;georgia&quot; , serif;">Personality and Motivations:<o:p></o:p></span></b></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Tell me, what is your 16P Type, what are you top five Strengths finders results, and what one-three words best describes you?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What do you do with<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">time when you are not working?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What are the things you enjoy most in life?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What things just bug you to no end?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">If every job, task, and activity in the world paid the same (and it was more than enough to have everything you wanted) what would you do?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">If you could sit down and chat with person who is alive today, who would it be? What about anyone not alive today? What about a non-real person? What about someone from your story world?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<b><span style="font-family: &quot;georgia&quot; , serif;">Training and background<o:p></o:p></span></b></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Tell me about your schooling. What high school did you go to? Where did you go to college? What activities did you participate in? Sororities / Fraternities? Were you&nbsp; in any other groups? Did you work through school, loans, scholarships, rich family?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Tell me about your major. How many degrees do you have? In what? Why that and not something else?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What was your first job? How many jobs have you had? What was your favorite job? Least favorite job? What do you do now?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Do you hold any licenses, specialties, etc.?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">If you could switch jobs today what would you do? (Real and Imagined)<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin: 0in 0in 0.0001pt;">
<b><span style="font-family: &quot;georgia&quot; , serif;">Family history<o:p></o:p></span></b></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What are your parents name? Do you know your grandparents? Do you have an siblings? Cousins, Aunts, Uncles, Other important relatives? Are you related to anyone famous?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What does your name mean, and why did you parents choose it?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Is there anything interesting or important or unusual we need to know about your family?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What was your relationship like with your Mother? Father? Others?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">How is your relationship now?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<b><span style="font-family: &quot;georgia&quot; , serif;">Early Childhood through middle school<o:p></o:p></span></b></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What experiences, growing up, marked your memory? In other words, what can you remember about your childhood, what stands out?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Who were your best friends?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">Worst enemies, bullies?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<span style="font-family: &quot;georgia&quot; , serif;">What was your best day? Worst?<o:p></o:p></span></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<br /></div>
<div style="margin-bottom: .0001pt; margin: 0in;">
<b><span style="font-family: &quot;georgia&quot; , serif;">Here are some photos that remind me of you:<o:p></o:p></span></b></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<div style="margin: 0in 0in 0.0001pt;">
<br /></div>
<br />
<div style="margin: 0in 0in 0.0001pt;">
</div>
<br />
<div style="margin: 0in 0in 0.0001pt;">
<div style="margin: 0px;">
<br /></div>
</div>
<br />
<br />
<br />
<br />
<br />
<h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">
<div style="font-weight: normal;">
<b>Comment on this post, or Hit me up on Twitter&nbsp;<a href="https://twitter.com/darrellwolfe" style="color: #149adf; text-decoration: none;" target="_blank">@DarrellWolfe&nbsp;</a>,&nbsp;Google&nbsp;<a class="g-profile" data-gapiattached="true" data-gapiscan="true" data-onload="true" href="https://plus.google.com/106337514196493406365" style="color: #149adf; text-decoration: none;" target="_blank">+DarrellWolfe</a>, Facebook&nbsp;<a href="https://www.facebook.com/groups/907869989282584/" style="color: #149adf; text-decoration: none;" target="_blank">DarrellGWolfe</a>,&nbsp;</b></div>
</h4>
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<br /></blockquote>
<h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">
By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4>
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<i>Storyteller, Creative,&nbsp;<a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>,&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>, Ideation, Input, Learner, Achiever</i></blockquote>
<br />
<i>* I may include "Affiliate Links" which means I earn a commission when you buy some of the products I link to.&nbsp;</i><br />
<br />
<ul>
<li><i>See my full about page and disclosures:&nbsp;<a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li>
</ul>
<ul>
<li><i>Also check out my&nbsp;<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions&nbsp;</a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li>
</ul>
<br />
<i></i><br />
<br />
<a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br />
<br />
To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br />
<br />
For Non-Fiction stories with a lesson by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a><br />
<br />
<br />
<br />
<br />
<br />
<div style="clear: both; float: left; padding-bottom: 10px; text-align: right;">
<br /></div>
