---
title: 'Writers Digest _ Short Story Competition _ Due 10/2016'
date: '2016-09-04T08:03:00.0000000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '4687796223620348272'
blogger_filename: '/2016/09/writers-digest-short-story-competition.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
---

<br />
<a href="http://www.writersdigest.com/your-story-competition/story-77-submit-now" target="_blank">Writers Digest _ Short Story Competition _ Due 10/2016</a><br />
<br />
<blockquote class="tr_bq" style="border: 0px; color: #333333; font-family: &quot;Lucida Sans&quot;, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 1.5; margin-bottom: 1.07143rem; padding: 0px;">
<span style="background-color: white;"><strong style="border: 0px; margin: 0px; padding: 0px;">Prompt:</strong>&nbsp;Write a short story, of </span><span style="background-color: yellow;">700 words<b> or fewer</b></span><span style="background-color: white;">, based on this prompt: When a man takes lunch to his wife’s office, he’s told that she hasn’t worked there in weeks.</span><span style="background-color: transparent;">&nbsp;</span></blockquote>
<blockquote class="tr_bq" style="background-color: white; border: 0px; color: #333333; font-family: &quot;Lucida Sans&quot;, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 1.5; margin-bottom: 1.07143rem; padding: 0px;">
You can be funny, poignant, witty, etc.; it is, after all,&nbsp;<em style="border: 0px; margin: 0px; padding: 0px;">your</em>&nbsp;story.<br />Use the submission form below&nbsp;<strong style="border: 0px; margin: 0px; padding: 0px;"><u style="border: 0px; margin: 0px; padding: 0px;">OR</u></strong>&nbsp;email your submission directly to yourstorycontest@fwcommunity.com.<span style="background-color: transparent;">&nbsp;</span></blockquote>
<blockquote class="tr_bq" style="background-color: white; border: 0px; color: #333333; font-family: &quot;Lucida Sans&quot;, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 1.5; margin-bottom: 1.07143rem; padding: 0px;">
<strong style="border: 0px; margin: 0px; padding: 0px;">IMPORTANT:</strong>&nbsp;If you experience trouble with the submission form, please email your submission directly to yourstorycontest@fwcommunity.com within the body of your email (no attachments, please). Unfortunately, we cannot respond to every entry we receive, due to volume.&nbsp;<strong style="border: 0px; margin: 0px; padding: 0px;">No confirmation emails will be sent out to confirm receipt of submission.</strong>&nbsp;But be assured all submissions received before entry deadline are considered carefully.&nbsp;<a href="http://www.writersdigest.com/your-story-official-rules" style="border: 0px; color: #006699; margin: 0px; outline: none; padding: 0px; text-decoration: none;">Official Rules</a><span style="background-color: transparent;">&nbsp;</span></blockquote>
<blockquote class="tr_bq" style="background-color: white; border: 0px; color: #333333; font-family: &quot;Lucida Sans&quot;, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 1.5; margin-bottom: 1.07143rem; padding: 0px;">
Entry Deadline: October 10, 2016.</blockquote>
<div style="background-color: white; border: 0px; color: #333333; font-family: &quot;Lucida Sans&quot;, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 1.5; margin-bottom: 1.07143rem; padding: 0px; text-align: center;">
***************************</div>
<div style="background-color: white; border: 0px; margin-bottom: 1.07143rem; padding: 0px;">
<span style="color: #333333; font-family: Lucida Sans, Arial, Helvetica, sans-serif;"><span style="line-height: 18px;"><b>When a man takes lunch to his wife’s office, he’s told that she hasn’t worked there in weeks.&nbsp;</b></span></span></div>
<div style="background-color: white; border: 0px; color: #333333; font-family: &quot;Lucida Sans&quot;, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 1.5; margin-bottom: 1.07143rem; padding: 0px; text-align: center;">
***************************</div>
<div>
Hook: Emotional grab to start the scene. He's feeling tense because of an argument before he left on business.&nbsp;</div>
<div>
<br /></div>
<div>
Situation</div>
<div>
<ul>
<li>George McFarlane has been away on business. He didn't want to go home because his last discussion with his wife was so pleasant, he couldn't wait to get home. He goes straight from the airport to her favorite Thai Restaurant&nbsp;and brings her lunch as a surprise.</li>
</ul>
<ul>
<li>He takes lunch to his wife's office and he's told that she hasn't worked there in weeks. He tried to reach her by telephone, but can't get a hold of her. He gets home to find everything is gone.&nbsp;</li>
</ul>
<ul>
<li>However, her driver's license and personal identification are all on the mantle with a note:</li>
</ul>
<blockquote class="tr_bq">
"I don't have time to explain, but I'm not your wife. You are not who you think you are. You need to leave this house and remember. I'll find you when this is over... I hope."</blockquote>
</div>
<div>
<div style="background-color: white; border: 0px; color: #333333; font-family: &quot;Lucida Sans&quot;, Arial, Helvetica, sans-serif; font-size: 12px; line-height: 1.5; margin-bottom: 1.07143rem; padding: 0px; text-align: center;">
***************************</div>
</div>
<div>
George McFarlane walked up the steps and paused outside the door. His belly was turning around in knots, a mixture of hunger and excitement. They were newlyweds, just under a year, and he still hadn't lost that giddy feeling when he saw her.</div>
<div>
<br /></div>
<div>
He hadn't eaten since last night, or was that the night before? 28-hour flights were confusing. He refused to eat without her. Being around her was intoxicating, and it had been too long already. Four weeks in Korea negotiating a major business merger, and all he could think about was getting home to Darlene.</div>
<div>
<br /></div>
<div>
He opened the door and peeked around, she was not in sight.&nbsp;</div>
<div>
<br /></div>
<div>
George walked up to the admin and asked if she could page his wife.&nbsp;</div>
<div>
<br /></div>
<div>
"Hey, George. It's good to see you, but Darlene doesn't work here anymore... didn't she tell you?"&nbsp;</div>
<div>
<br /></div>
<div>
"She doesn't work-- What do you mean she doesn't work here anymore?"</div>
<div>
<br /></div>
<div>
"She quit about two and half weeks ago, said she had a better offer she just couldn't pass up."&nbsp;</div>
<div>
<br /></div>
<div>
"Are you pulling my leg?"&nbsp;</div>
<div>
<br /></div>
<div>
"No sweety, I'm afraid not. I can't believe she didn't tell you. Maybe she was waiting until you got back... I hope I didn't ruin the surprise?"&nbsp;</div>
<div>
<br /></div>
<div>
"That's ok Bonnie, I'll just catch her at home and let her tell me all about it. Thanks for the heads up, I guess." George shrugged.&nbsp;</div>
<div>
<br /></div>
<div>
He took the steps back to the parking garage. Confusion overtook hunger, and he set the To-Go bags on the passenger seat.&nbsp;</div>
<div>
<br /></div>
<div style="text-align: center;">
***</div>
<div>
<br /></div>
<div>
When he arrived home, her car was no in the garage or driveway. The mailbox was full.&nbsp;</div>
<div>
<br /></div>
<div>
George stepped up to the front door and found it open. He took a step back, listening for burglars. He heard nothing.&nbsp;</div>
<div>
<br /></div>
<div>
Picking up a rake from the garden in one hand, he pressed the door the rest of the way open with the other.&nbsp;</div>
<div>
<br /></div>
<div>
There was a musty smell coming from the carpet where rain had soaked in the prior week.</div>
<div>
<br /></div>
<div>
Furniture, tables, lamps, all gone. One envelope was stapled to the wall with his name on it.</div>
<div>
<br /></div>
<div>
George walked opened it to find his wife's ID's, credit cards, and passport. Inside was a simple note card:</div>
<blockquote class="tr_bq">
"I won't be needing these anymore. I don't have time to explain, but I'm not your wife. You are not who you think you are. You need to leave this house and remember. I'll find you when this is over... I hope."<br /><br /><br /><br />*******************It needs more, but it's a start.******************<br /><br /></blockquote>
<h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">
By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4>
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote>
<ul>
<li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li>
<li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li>
<li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li>
<li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li>
</ul>
<ul>
</ul>
