---
title: 'Lost is found in hidden wealth'
date: '2016-01-20T20:05:00.0000000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '5071424968486408058'
blogger_filename: '/2016/01/lost-is-found-in-hidden-wealth.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Short Story - Fiction'
---

<br />
It all started with a poster. Minding his own business, waiting for his fiancée to come out of the rest room. He hated shopping at Walmart, but she enjoyed it for some reason.<br />
<br />
"It keeps me humble." Molly said. "We must never forget who we are, or where we came from." She smiled. A conversation they'd had many times.<br />
<br />
"We could shop anywhere." he said. "Can't we go to Dillard's? Soma's? St John's Boutique? Anywhere else? You enjoy those stores too."<br />
<br />
"You know I do, but for a few basics I enjoy going back to my roots. Why spend more, when you can spend less?"<br />
<br />
"Because you can afford to spend more so that you don't have to go places like this." He could feel the poverty crawling on his skin. The mere thought of using one of these restrooms, he felt like taking a shower.<br />
<br />
"You are such a snob Aaron. You need to live a little." With a twirl of her hair, and a look of defiance in her eye, she headed to the restroom.<br />
<br />
It was there, in Walmart, standing by the bathrooms, that he saw it. The stories of children gone missing. Most of these kids went missing in their older, teenage years. They probably weren't missing, not in the traditional sense. They were run aways.<br />
<br />
For most of human history, these "young" people would have been considered adults, or at least apprentices for a trade by this age. Aaron knew it was callous to say so, but he didn't really feel bad for these.<br />
<br />
It was the truly young, those under 13, that he felt for. An orphan himself, adopted by a wealthy family. There was something in their story that often touched him.<br />
<br />
Then he saw it.<br />
<blockquote class="tr_bq">
<i>Adam Standish is shown here, age progressed to 25. He would be 31 this year. He was last seen sleeping in his mother's bed. His mother went to the local store at 12:10 am and when she returned at 12:40 am the child was missing. He has light&nbsp;blond&nbsp;hair. Born May&nbsp;4th, 1984, missing since December 24th, 1986.&nbsp;</i></blockquote>
The image was remarkable. It wasn't exact mind you, but remarkable. It could have been his high school reunion photo. More remarkable, it was his birthday. It was also, one week before the day he was adopted. The similarities were striking.<br />
<br />
Molly came out of the restroom. "Aaron, I know you don't like this place. Let's make it-." She came to his side and looked up at him. "What is it babe? What's wrong?"<br />
<br />
He said nothing, just kept staring. He could feel the tinge of emotions, wrestling to come to the surface.<br />
<br />
She turned to see what he was staring at, and gasped. "That's... that's you!" She said, loudly enough that several people turned in her direction for a moment.<br />
<br />
<br />
<div style="text-align: center;">
***</div>
<div style="text-align: center;">
<br /></div>
"There was so much red tape in an adoption dear." His mother said. "So we went with a private adoption."<br />
<br />
Aaron and Molly sat next to her bedside. Mrs. Withering wasn't old, but she was ill, constantly. It was part of the reason she was never able to bear children of her own.<br />
<br />
"Did you meet the mother?" Aaron asked.<br />
<br />
"She did not want to be known. The adoption agent arranged everything. We filled out the paperwork, and you were delivered to our door."<br />
<br />
"Do you still have the adoption agents name and contact information?"<br />
<br />
"I suppose so." Mrs. Withering said. He skin flushed, as she waived a fan in her face. "Why all of this fuss now? You've known you were adopted since you were ten child. Why bother an old woman with all of these questions now?"<br />
<br />
Aaron glanced at Molly, then back to his mother. Not wanting to upset her, in her weakened condition. "Father is gone. You are getting more ill by the day. It's just come to my mind recently that I may not be able to ask these questions for much longer. So I should ask them now, if ever."<br />
<br />
She stared him in the eye for a few moments. Then turning her eyes back to the television, "Well that's fair enough. You'll need to see Charles about the papers, I'm sure the information you need is in there. I wish I could tell you more, but-" She glanced at the wall."Well you see, dear, these types of adoptions... well... as I understand they are better performed with less questions, than more. You see? I'm afraid I just don't know any more than that."<br />
<br />
"I understand, Mother." Aaron stood.<br />
<br />
"Now before you go, be a good dear. Hand me the remote, and tell Ingrid to bring me more tea."<br />
<br />
"As you wish Mother. Be well."<br />
<br />
With a kiss on each check, he turned. Molly in tow.<br />
<br />
<br />
<div style="text-align: center;">
***</div>
<div style="text-align: center;">
<br /></div>
<br />
"The family papers, as you asked." Charles escorted them into a large conference room. Oak and marble covering nearly every inch. "I'm afraid I don't know much about your adoption Aaron. I did not come on to the firm until you were about 19 years old, shortly before my father retired. I'd like to keep these here at the firm, I don't want them lost. But you are welcome to stay here and go through them. If you want copies of anything, just tell Yvette, she'll get them for you."<br />
<br />
Charles left Aaron and Molly to themselves. Five boxes of papers, files, and forms from 1980-1998, were neatly set on the table. Anything the Withering Family Estate felt necessary to keep on record during his formative years.<br />
<br />
Chesterton, Markus, &amp; Dunn was more than a law firm. They were an advanced Estate Planning Firm. They kept and recorded generational wealth, dating back to 1756. Some of the archives on record here, were the oldest and best preserved in the world. "The fastest way to debunk a fraud, is original records." As Charles Chesterton I was so fond of saying.<br />
<br />
They found the box containing 1984-1987, and sorted through files. Several infertility reports, doctors bills marked paid. Adoption agency rejections, primarily due to the health and age of the would-be parents.<br />
<br />
"Hey, look at this." Molly handed a file to Aaron.<br />
<br />
The cover letter read: "Adoptable Child Finders Agency. We will find you a private adoption, guaranteed."<br />
<br />
Molly pointed at the bottom, "It's signed J. Farnsworth."<br />
<br />
They continued looking through all the papers, but they could not find anything more. No clues to his origins. "Wait." Molly was tapping on the box. "There's something else in here. It's seems empty, but it's still a little heavier than it should be."<br />
<br />
After some poking and prodding, they found a false bottom, and another thick folder. The file contained newspaper clippings from the Los Angeles Times, mostly from 1986-1987. There were all about a child that had gone missing from his mother's bed.<br />
<br />
"Listen to this." Aaron read aloud,<br />
<blockquote class="tr_bq">
'The mother remains the chief suspect in the murder of the missing two year old Adam Standish; however, with no body and no evidence formal charges are yet to be filed.'&nbsp;</blockquote>
"Here's another one."<br />
<blockquote class="tr_bq">
'West Covina mother arrested for Child Endangerment.'&nbsp;</blockquote>
"It says here that the mother reported her two year old missing after leaving him in the house to go to the local corner store at midnight. She was intoxicated at the time the police arrived. It was determined by the Police that she was intoxicated before leaving the child at home."<br />
<br />
"Here's another article, from 1989." Molly said.<br />
<blockquote class="tr_bq">
'After serving two years of the five year Child Endangerment sentence, April Standish was released on probation. It was widely believed that she had murdered the child, but the body was never found. In the face of murder allegations, Mrs. Standish maintained her innocence throughout the trail. However, she pled guilty to Child Endangerment for a reduced sentence.'&nbsp;</blockquote>
"This is awful." Molly said, a tear filled her eye.<br />
<br />
A mild horror was chasing down Aaron's spine as the realization dawned. "This is the child from the Walmart poster. These clippings are hidden in my parents files. This child is me, or at least... someone in my family or this firm suspected it was me."<br />
<br />
After reading through all the clippings, Molly started putting everything back into the folders, but then set them down on the table. "What's this?" she said, reaching into the box again. She pulled out an off-white envelope, with a wax seal in the family crest. Labeled simply, Aaron.<br />
<br />
He took the envelope, and opened the seal. The letter was typed, but hand signed.<br />
<blockquote class="tr_bq">
Aaron,&nbsp;</blockquote>
<blockquote class="tr_bq">
You will no doubt reach an age where you will want to know your origins. You parents never wanted to know, but I felt it necessary. This has been stored and preserved for your records. It is everything I have been able to find.&nbsp;</blockquote>
<blockquote class="tr_bq">
The adoption agent, as he called himself at the time, never presented any credentials. Your father insisted that I work the papers anyway, and I never could resist your father. He said that your mother was too weak to handle the details, and he had found an agent to secure an adoption. &nbsp;</blockquote>
<blockquote class="tr_bq">
For several years I did my research. I was never able to locate the so-called J. Farnsworth again. But I did locate these clippings, the dates and conditions are similar. The child looked so much like you that it could hardly be a coincidence. It is my hopes that I could leave these answers for you, as they are the best I could find, before I gave up and moved on with my life.&nbsp;</blockquote>
<blockquote class="tr_bq">
One day, when you are old enough to ask questions, these may bring you some level of peace, or closure.</blockquote>
<blockquote class="tr_bq">
Charles Chesterton I, July 4th, 1991</blockquote>
<br />
<div style="text-align: center;">
***</div>
<br />
It took a few public records searches, but Aaron and Molly were able to locate April Standish. She was still living in her original home in West Covina, CA.<br />
<br />
Aaron paused just outside the black iron gate. Some kids past them on the sidewalk, on bikes. The thick grass reminded him of green shag carpet. Two weathered garden gnomes kept watch by the front path.<br />
<br />
Molly gave him a reassuring nod, the rusted iron made a high pitched whine as he pushed it open. Three short steps to the right, and they were on the landing. A barred screen door protected the inner wooden door. Black iron gates, matching the one around the house, covered each window. Each bar was tipped, top and bottom, with a sharp pointed <a href="https://en.wikipedia.org/wiki/Fleur-de-lis" target="_blank">fleur de lis</a>.<br />
<br />
The screen door was locked. Aaron hesitated, so Molly pushed the door bell for him. No sounds.<br />
<br />
"We should have called first, before driving all the way down here. We don't even know for sure."<br />
<br />
He started to turn for the steps, but Molly held his hand tight. She reached out and pressed the doorbell again.<br />
<br />
There was some shuffling inside. Two dead bolts slid open, and the door cracked.&nbsp;A woman in a night gown answered. "Hello? Can I help you two with something?"<br />
<br />
The voice. Somehow... he knew that voice. It could just be wishful thinking. Aaron turned to her through the screen. "I'm sorry ma'am, I don't mean to bother you... But-"<br />
<br />
"Oh my Lord!" she said. The screen flew open. "Adam... is that you? Is that my baby boy?"<br />
<br />
<br />
<div style="text-align: center;">
***</div>
<br />
<blockquote class="tr_bq">
<i>*The details of this story are fiction, but the story idea came from a real missing child poster in a Walmart. Name and dates have been changed.&nbsp;</i></blockquote>
<blockquote class="tr_bq">
<i>*Related Research:</i></blockquote>
<ul style="background-color: white; list-style-image: url(&quot;data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%0A%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20version%3D%221.1%22%20width%3D%225%22%20height%3D%2213%22%3E%0A%3Ccircle%20cx%3D%222.5%22%20cy%3D%229.5%22%20r%3D%222.5%22%20fill%3D%22%2300528c%22%2F%3E%0A%3C%2Fsvg%3E%0A&quot;); list-style-type: disc; margin: 0.3em 0px 0px 1.6em; orphans: auto; padding: 0px; text-align: start; text-indent: 0px; widows: 1;">
<li>http://www.cnn.com/2015/11/04/us/missing-boy-found-alabama-ohio/&nbsp;</li>
<li>http://www.wcvb.com/news/police-searching-for-woman-and-two-children-in-suv/37064620</li>
<li>https://en.wikipedia.org/wiki/Endangerment</li>
<li style="-webkit-text-stroke-width: 0px; color: #252525; font-family: sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22.4px; margin-bottom: 0.1em; text-transform: none; white-space: normal; word-spacing: 0px;"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Child_endangerment" style="background: none; color: #0b0080; text-decoration: none;" title="Child endangerment">Child endangerment</a>: placing a child in a potentially harmful situation, either through negligence or misconduct.</li>
<li style="-webkit-text-stroke-width: 0px; color: #252525; font-family: sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22.4px; text-transform: none; white-space: normal; word-spacing: 0px;"><span style="background-color: transparent;">https://en.wikipedia.org/wiki/Child_neglect</span></li>
</ul>
<ul style="background-color: white; list-style-image: url(&quot;data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%0A%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20version%3D%221.1%22%20width%3D%225%22%20height%3D%2213%22%3E%0A%3Ccircle%20cx%3D%222.5%22%20cy%3D%229.5%22%20r%3D%222.5%22%20fill%3D%22%2300528c%22%2F%3E%0A%3C%2Fsvg%3E%0A&quot;); list-style-type: disc; margin: 0.3em 0px 0px 1.6em; orphans: auto; padding: 0px; text-align: start; text-indent: 0px; widows: 1;">
<li><span style="background-color: transparent;">http://criminal-law.freeadvice.com/criminal-law/violent_crimes/child-endangerment-charges.htm</span></li>
<li><span style="background-color: transparent;">https://en.wikipedia.org/wiki/Breathalyzer#Origins</span></li>
</ul>
<br />
<h4 style="background-color: white; color: #333333; font-family: verdana, geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">
<div style="font-weight: normal;">
<b>Comment on this post, or Hit me up on Twitter&nbsp;<a href="https://twitter.com/darrellwolfe" style="color: #149adf; text-decoration: none;" target="_blank">@DarrellWolfe&nbsp;</a>,&nbsp;Google&nbsp;<a class="g-profile" data-gapiattached="true" data-gapiscan="true" data-onload="true" href="https://plus.google.com/106337514196493406365" style="color: #149adf; text-decoration: none;" target="_blank">+DarrellWolfe</a>, Facebook&nbsp;<a href="https://www.facebook.com/groups/907869989282584/" style="color: #149adf; text-decoration: none;" target="_blank">DarrellGWolfe</a>,&nbsp;</b></div>
</h4>
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: verdana, geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<br /></blockquote>
<h4 style="background-color: white; color: #333333; font-family: verdana, geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">
By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4>
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: verdana, geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<i>Storyteller, Creative,&nbsp;<a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>,&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>, Ideation, Input, Learner, Achiever</i></blockquote>
<br />
<i>* I may include "Affiliate Links" which means I earn a commission when you buy some of the products I link to.&nbsp;</i><br />
<br />
<ul>
<li><i>See my full about page and disclosures:&nbsp;<a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li>
</ul>
<ul>
<li><i>Also check out my&nbsp;<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions&nbsp;</a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li>
</ul>
<br />
<i></i><br />
<br />
<a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br />
<br />
To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br />
<br />
For Non-Fiction stories with a lesson by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a><br />
<br />
<br />
<br />
<br />
<br />
<div style="clear: both; float: left; padding-bottom: 10px; text-align: right;">
<br /></div>
