---
title: 'Three Basic Character Arcs'
date: '2016-08-13T13:42:00.0010000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '2143047020741297303'
blogger_filename: '/2016/08/three-basic-character-arcs.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
---

<br />As I continue to study the craft of fiction, K.M. Weiland (<a href="http://www.helpingwritersbecomeauthors.com/character-arcs-1/" target="_blank">Full article here</a>) has fast become my favorite author/writer/teacher of writing craft. She has a powerful platform on her websites, podcast, and books. She has a way of breaking down seemingly difficult topics into easily understandable (and actionable) ideas.&nbsp;<div>
<br /></div>
<div>
Here's what she said about Character Arcs:<div>
<blockquote class="tr_bq">
<b>The Three Basic Character Arcs</b>Although the variations of character arcs are as endless as the vagaries of human nature, we can narrow character arcs down to three basic types, with a few primary variations upon each:&nbsp;</blockquote>
<blockquote class="tr_bq">
<b>The Change Arc</b>This is the most popular and often the most resonant character arc. The protagonist will start out with varying levels of personal unfulfillment and denial. Over the course of the story, he will be forced to challenge his beliefs about himself and the world, until finally he conquers his inner demons (and,<a href="http://www.helpingwritersbecomeauthors.com/2010/12/external-and-internal-conflict-killer.html">as a result, probably his outer antagonists as well</a>) and ends his arc having changed in a positive way.&nbsp;</blockquote>
<blockquote class="tr_bq">
<b>The Flat Arc</b>Many popular stories feature characters who are already essentially complete unto themselves. They’re already heroes and don’t require any noticeable personal growth to gain the inner strength to defeat the external antagonists. These characters experience little to no change over the course of the story, making their arcs static or “flat.” Sometimes these characters are the catalysts for change in the story world around them, so that we find more prominent growth arcs in the minor characters.&nbsp;</blockquote>
<blockquote class="tr_bq">
<b>The Negative Arc</b>Negative character arcs offer, arguably, more variations that either of the other arcs. However, at their most basic level, the Negative Arc is just a Change Arc flipped on its head. Instead of a character who grows out of his faults into a better person, the Negative Arc presents a character who ends up in a worse state than that in which he began the story.</blockquote>
<blockquote class="tr_bq">
By K.M. Weiland | @KMWeiland (<a href="http://www.helpingwritersbecomeauthors.com/character-arcs-1/" target="_blank">Full article here</a>)</blockquote>
<div>
Ash (in White Noise - The Tower) experiences The Change Arc. He starts out doubting himself (and his sanity) and he discovers that he isn't going crazy after all. In fact, his hallucinations are real (and he did this to himself).</div>
<br /><br /><h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">
By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4>
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote>
<ul>
<li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li>
<li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li>
<li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li>
<li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li>
</ul>
<ul>
</ul>
</div>
</div>
