---
title: 'Research: Post-Traumatic Stress Disorder, PTSD, Symptoms and Gun rules'
date: '2016-09-19T15:59:00.0040000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '3222657521379945366'
blogger_filename: '/2016/09/research-post-traumatic-stress-disorder.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Research'
  - 'White Noise'
---

<br />
Here is some background information I found on PTSD, it may help me flesh out Ash's character more.<br />
<br />
<a href="http://umm.edu/health/medical/altmed/condition/posttraumatic-stress-disorder" target="_blank">University of Maryland Medical Center</a> has a great article breaking down PTSD and treatment.<br />
<br />
<blockquote class="tr_bq">
Post-traumatic stress disorder (PTSD) is an anxiety disorder that is brought on by memories of an extremely stressful event or series of events that cause intense fear, particularly if feelings of helplessness accompanied the fear.</blockquote>
<br />
<blockquote class="tr_bq">
Symptoms of PTSD usually develop within the first 3 months after the event, but they may not surface until months or even years after the original traumatic event. Symptoms may include:</blockquote>
<br />
<ul>
<li><b>Intrusive thoughts recalling the traumatic event</b></li>
<li><b>Nightmares</b></li>
<li><b>Flashbacks</b></li>
<li><b>Efforts to avoid feelings</b> and thoughts that either remind you of the traumatic event or that trigger similar feelings</li>
<li><b>Feeling detached</b> or unable to connect with loved ones</li>
<li>Depression, hopelessness</li>
<li>Feelings of guilt (from the false belief that you were responsible for the traumatic incident)</li>
<li>Irritability or angry outbursts</li>
<li>Hypervigilance (being overly aware of possible danger)</li>
<li>Hypersensitivity, including at least two of the following reactions: trouble sleeping, being angry, having difficulty concentrating, startling easily, having a physical reaction (rapid heart rate or breathing, increase in blood pressure)</li>
<li>Headache</li>
<li>Disrupted sleep, insomnia</li>
</ul>
<br />
<blockquote class="tr_bq">
Experts are not entirely sure what causes some people to develop PTSD, but many think it happens when you are confronted with a traumatic event, and <b>your mind is not able to process all the thoughts and feelings as it usually does. </b>Scientists studying the brain think there may be some differences in the brain structure or chemistry of those with PTSD. For example, certain areas of the brain involved <b>with feeling fear may be hyperactive</b> in people with PTSD. Other researchers have focused on the hippocampus, the area of the brain responsible for memory and for how we deal with stress, and are investigating whether changes in that area also appear in people with PTSD.</blockquote>
<br />
<br />
<b>Treatment Plan</b><br />
<br />
<blockquote class="tr_bq">
The treatments for PTSD include:</blockquote>
<br />
<ul>
<li>Cognitive behavior therapy (CBT). With the help of a psychotherapist, you learn techniques to manage your thoughts and feelings when you are in situations that remind you of the traumatic event. <b>You may gradually expose yourself to situations and thoughts that cause anxiety</b>, as you build up a tolerance for them and your fear is lessened. Ultimately, the goal of cognitive therapy is to allow you to control your fear and anxiety.</li>
<li>Stress management therapy. A therapist teaches you relaxation techniques to help you overcome fear and anxiety, and to break the cycle of negative thoughts.</li>
<li>Medication for depression or anxiety.</li>
<li>Drug Therapies</li>
</ul>
<br />
<br />
<ul>
<li><b>Antidepressants </b>such as selective serotonin reuptake inhibitors (SSRIs), including sertraline (Zoloft), fluoxetine (Prozac), fluvoxamine (Luvox), or paroxetine (Paxil).</li>
<li>Benzodiazepines, a group of <b>medications sometimes used for anxiety, </b>including lorazepam (Ativan) and alprazolam (<b>Xanax</b>). These drugs have sedating properties and may cause drowsiness, constipation, or nausea. DO NOT take them if you have narrow angle glaucoma, a psychosis, or are pregnant. They also interact with other drugs, including some antidepressants (such as Luvox).</li>
<li>Dopamine-blocking agents, such as neuroleptics. There is some evidence of increased dopamine presence in children and adults with PTSD.</li>
</ul>
<br />
<br />
<ul>
<li>Biofeedback involves using a machine, at first, to see bodily functions that are normally unconscious and occur involuntarily (for example, heart rate and temperature). As you see how your body reacts to stress, you learn to control the reactions, and eventually you can perform the techniques to control the reactions without using a machine. Some studies suggest that biofeedback, among other forms of relaxation training, may be an effective treatment for some people with PTSD.</li>
<li>Hypnosis has long been used to treat war-related post-traumatic conditions.&nbsp;</li>
</ul>
<ul>
<li>Avoid coffee and other stimulants, alcohol, and tobacco.</li>
<li>Green tea (Camellia sinensis) standardized extract, 250 to 500 mg daily, for antioxidant and immune effects. Use caffeine-free products. You may also prepare teas from the leaf of this herb.</li>
</ul>
<br />
<div>
<br /></div>
<div>
<div>
Prognosis/Possible Complications</div>
<div>
<br /></div>
<blockquote class="tr_bq">
If PTSD symptoms continue for longer than 3 months, the condition is considered to be chronic (ongoing). Chronic PTSD may become less severe even if it is not treated,<b> or it may become severely disabling, interfering with many areas of life and causing physical complaints. </b>Some research suggests that PTSD may be related to physical disorders, such as arthritis, but few studies have examined the relationship between PTSD and physical health.</blockquote>
</div>
<div>
<br /></div>
<div>
<br /></div>
<h4>
<b>**Can you have PTSD and own guns?&nbsp;</b></h4>
<div>
<a href="http://www.theveteransvoice.com/Vets-PTSD-and-Guns.html" target="_blank">The Veterans' Voice</a> offers the following:&nbsp;</div>
<div>
<br /></div>
<div>
<blockquote class="tr_bq">
Most of the restrictive laws are actually at your local level. The feds only do a criminal background check to ensure you're not a felon. That's the NICS check and it is done in a matter of minutes most days. If you aren't in the federal database, they will tell the licensed dealer that he can sell you a weapon.&nbsp;</blockquote>
<blockquote class="tr_bq">
To get a carry permit then is governed by your state law. Some states are wide open and others don't issue carry permits at all. From there it usually goes to your county.</blockquote>
</div>
<div>
<blockquote class="tr_bq">
Personally, I am concerned about any citizen who takes psychotropic medicines for a mental health condition carrying a concealed weapon. I'm a gun owner and I've carried a sidearm most of my life. On the other hand, if a man is admittedly unstable and has recurrent problems with PTSD and is on powerful medications, I'm not sure I want him in the same room with me when he's packing a 357.&nbsp;</blockquote>
<blockquote class="tr_bq">
Let's be realistic here...guns are dangerous. I don't drink alcohol and shoot. I don't think a guy on a sedative medication should shoot...or be armed.&nbsp;</blockquote>
<blockquote class="tr_bq">
I don't know your situation, of course. I can tell you only of my many friends who I've known over the years who have PTSD. One buddy is close to me today. He has a 10% rating for PTSD and he has a carry permit. I've had to intervene and take his guns from him when he's had anger problems in his marriage. I know another guy and he's 100% for PTSD and an avid hunter. He has no problems to speak of.</blockquote>
</div>
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<div>
<br /></div>
</blockquote>
<h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">
By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4>
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote>
<ul>
<li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li>
<li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li>
<li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li>
<li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li>
</ul>
<ul>
</ul>
