---
title: 'Distortion - Street Noise - Scene One Rewrite - In Progress...'
date: '2016-10-27T01:27:00.0000000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '1518935325892415450'
blogger_filename: '/2016/10/distortion-sceneone.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Writing Practice'
  - 'White Noise'
---

<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto; mso-outline-level: 3;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">A&nbsp;man&nbsp;in
black&nbsp;rushed behind a gray Chevy Suburban across the street. Theron "Ash" Ashland spotted him through the window of The Grounded Café while waiting for his
morning Java Chip Frappe'. </span><i style="font-family: &quot;Times New Roman&quot;, serif; font-size: 12pt;">Wait, was he&nbsp;wearing combat gear?</i><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Ice-shards tore down his spine, his
heart skipped a beat. The muscles in his right arm tensed as he reached for the
Glock 9mm holstered on&nbsp;his side. <em>Huh?</em> He
shook his head, on second glance the man&nbsp;was&nbsp;gone, a cloud of charcoal
dust whisping into the air from under the
SUV.<o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">A breath slowly escaped his lungs,
Ash released his grip on what he originally thought was his Glock 9mm, but he
now realized was a holstered steel tape measure. He wasn't licensed to carry
anymore, so he typically didn't. He let his arm slowly lower to his side as he
closed his eyes. Deliberately inhaling slowly,&nbsp;silently counting to
ten, . The scents of blonde roast and espresso filled his mind and
centered him.<o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Eight years away from any war zone and&nbsp;apparitions still haunt him.&nbsp;Eyes open again, the world
returned to normal. No threats. No combat zone. Just passers-by;
shoppers on a crowded small-town tourist street in&nbsp;Orion, Oregon. A town known for its&nbsp;big-game hunting cabins, as well as its&nbsp;boutiques and quaint scenery.</span><br />
<br />
The reflection of the café window caught the&nbsp;silver lining the side of his head.&nbsp;Ash&nbsp;thought it&nbsp;made him look wiser, almost regal. The creases near his eyes and lips betrayed a man older than he actually was. <em>You're too damn young to feel this old buddy</em>, Ash thought. Despite multiple tours in hot arid deserts, he still couldn't hold a tan. He turned red, pealed, and turned white again. He enjoyed these mountains as it&nbsp;rarely got above 85 degrees in the heat of summer.<br />
<br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Movement from above, just outside the window caught his attention. The shade of a Basswood tree was crawling down the sidewalk for the days' last stretch. A&nbsp;yellow and orange leaf twirled down, landing on a coffee table on the&nbsp;empty patio. </span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">A young college girl&nbsp;walked&nbsp;by outside, face glued to her screen like so many others. She
bumped into an elderly homeless gentlemen
but&nbsp;didn't look up, or give any indication to acknowledge the incident. The old man walked off mumbling to himself. A gray
dust cloud&nbsp;hung around the girl's shoulders like a shawl, and riding&nbsp;the
cloud was a small green frog with red eyes. Its legs disappeared into the mist,
becoming one with it. </span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">As she passed, the frog held Ash's gaze; head turning
unnaturally backward. He shuddered, no matter how many times he saw them, they
were still creepy. They weren't always frogs, and they weren't often cute. Even after eight years of seeing the various creatures&nbsp;crawling on people, they were sometimes terrifying. </span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">He was coping with combination of&nbsp;Prazosin, Dr. Pepper, and Jack Daniels; and a guarded distance from his fellow man. It was dangerous to spend too much time talking&nbsp;anyone, he'd learned to shield his reactions to the dust clouds and companions that appeared and disappeared at will, but the reactions&nbsp;sudden appearances&nbsp;sometimes caused him to jump at the wrong point in the conversation. </span><br />
<br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">To the best of his knowledge, nobody
else could see the colorful dust clouds that wrapped people like a shawl or
overcoat, nor the variety of creatures that accompanied some of them. Each person's cloud seemed
to be colored by their mood or attitude. Not everyone had a&nbsp;creature companion, but many did. This
insight&nbsp;was his unique gift,&nbsp;a prize brought home from overseas.</span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span>&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">"Don't worry so much,"
Ash could still hear his&nbsp;doctor's advice from
their last session a few weeks earlier.&nbsp;"We’re just beginning to
understand PTSD and many veterans come back with&nbsp;hallucinations. The mind
is a marvelous adapter to stress. As long as these phantoms do not interrupt
your daily work, or cause you to want to harm yourself or others, you should be
fine. Consider yourself lucky. Just think of them as a construct of your
over-active imagination, an amusing distraction from the mundane realities of
life." </span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">"Ash,"&nbsp;the Barista
called him back to the present. "One Java Chip. Are you ever going to let me talk you into trying
something else?"<o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Ash turned from the glass reflection,&nbsp;walked to the counter, and replied, "I doubt it, Jake, maybe next
time," He grabbed a sleeve and slipped it on the plastic cup. Even in winter he wanted cold drinks, a thirst from hot desert war zones that could never be quenched.</span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">"That's what you said last
week.&nbsp;You&nbsp;working on&nbsp;anything new lately?"&nbsp;Jake asked.</span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span>&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Ash forced a
smile and glanced up to look Jake in the eye, <em>no creature today</em>. Ash&nbsp;took stuttered&nbsp;breath and&nbsp;</span><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">replied, "Yeah,&nbsp;I've got a few new pieces. Just dropped
them off this morning over at Woodmen Furnishings. You should go by later, a
few of the other craftsmen were there...&nbsp;lots of new inventory."<o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">"Will do," Jake said as he
turned back to start another order. "Good to see you, as always."<o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Ash nodded and said, "You
too,"&nbsp;as he headed to a far corner and&nbsp;found his favorite
leather chair.<o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">He glanced around the café before
taking a seat.&nbsp;Two women were talking about their kids. Three
teenagers typing away on laptops as though their life depended on it. Two men&nbsp;had just arrived while he was waiting, they were having a meeting. One with glasses, the other in a black turtleneck.&nbsp;<i>Always
keep your back to the wall, stay as inconspicuous as possible</i>. The need to
be hyper-vigilant was like breathing, it never stopped. With the possible
exception of the guy in the turtleneck
who looked like he could handle himself, the room seemed fairly free of danger for the moment. He'd still keep an eye on Mr. Turtleneck. 
He bit his lip and sighed, <em>You're doing it again...</em> He took his
seat, the leather hugged him like a cool blanket.<o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">The morning paper had been abandoned
on a nearby table, as was the&nbsp;café custom. He reached to grab it when he
noticed&nbsp;several people outside turning and staring in the same direction.
Others ran from across the street to join a&nbsp;crowd that was developing just
outside the window. Whatever had their attention was just
out&nbsp;of&nbsp;view. </span><br />
<br />
Not one to ignore possible danger, he reluctantly got back up and headed outside. <span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">After he exited the front door,
he&nbsp;turned to the crowd.&nbsp;The man&nbsp;with the&nbsp;glasses followed
from inside the coffee shop, turtleneck
in tow. Turtleneck&nbsp;bumped into
him.&nbsp;"Excuse me," the man said flatly but he kept walking. <o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">A voice from the direction of the crowd was yelling something he couldn't
quite hear. He could see the white hair of a man's head bobbing back and forth, "I know-- I know--- Shut up you!" the man kept repeating. </span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Ash wasn't going to get a good view from here, so he walked around
the outside of the crowd, keeping his distance from actually touching anyone.
The whisps of colorful dust rose and fell
off each person. When people&nbsp;were close together like this the dust&nbsp;combined, grow even. He avoided getting near it if he could help it. <o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">A woman in a red hoodie rushed
passed him to join the crowd and knocked the coffee out of his hand. The lid
popped off, contents&nbsp;spilling down the front of his jeans as it tumbled to
its final resting place on the asphalt.<o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">"Dang lady, watch it!" He
said. She paid no attention, engrossed in whatever was happening just beyond
his field of vision. "Whatever," he said, more to himself than her,
and worked his way around the crowd.<o:p></o:p></span><br />
<br />
A small boy&nbsp;in blue and white overalls let go of his mother's hand and started walking across the street. Ash's fingers fidgeted with the edge of his shirt, eyes darting between the boy, the oblivious mother, and up and down the street. "Ma'am?" he tried to call, but his voice cracked and she didn't hear him. <br />
<br />
Not wanting to be accused of trying to hurt or take the child, Ash&nbsp;waited to see if the mother would notice but&nbsp;a car turned the corner. Sprinting to the middle of the road he grabbed the toddler and moved him out of the way of the oncoming traffic. The car barely stopped, looking at the commotion rather than the road. The kid laughed loudly, as though it were a game. The mother turned and saw Ash with him, eyes wide. Then she turned and saw the car that had just passed. Her eyes darted to the ground and back&nbsp;to the child. He skin turned a shade whiter.<br />
<br />
Ash walked back across the street, child in his arms. "Ma'am, you really ought to be more careful. He ran out into the road." He handed the child back to her.<br />
<br />
"Oh my baby! Thank you so much," she replied and&nbsp;turned to the child. She wagged her finger in his face, "How dare you scare Mommy like that! No! You hold my hand!"<br />
<br />
<span style="background-color: yellow;"></span><br />
<span style="background-color: yellow;"></span><br />
He shook his head and sighed. <em>Sure - it's the kids fault</em>. <em>Crazy people.&nbsp;</em>The child, now&nbsp;glued on his mother's hip, smiled at him over her shoulder. The rock façade Ash&nbsp;kept in place for adults melted a little in the presence of happy kids. Ash&nbsp;smiled back, stuck his tongue out, and made a silly face. The little boy laughed. Kids were easier to handle than adults. No expectations of proper behavior. They either didn't notice you were being odd, or better, they appreciated you for it. <br />
<br />
From this vantage point, Ash got a better view of the man yelling. He was wearing a tattered suit, head and shoulders above the crowd.<br />
<br />
<span style="background-color: yellow;">(Left off here)</span><br />
<br />
Ash made his way further around the crowd and&nbsp;<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">found a clearing on the
opposite side. He pushed past a few people at the edge of the building and&nbsp;stepped onto the sidewalk. The elderly man, the
one the little girl bumped into earlier, was now standing on the bed of a pickup truck. A tattered brown dress coat,
stained with years of unwashed use, hung over his thin skin like a cape. The
coat&nbsp;may have been black in a former life. A scruffy white beard hid his gaunt features.</span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span>&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">It was Frank, now that he could get
close enough to see him up close. Frank&nbsp;was one of the several train-hopping
hobos that made camp on the outskirts of town. He came to pick up his Social
Security check every month about this time. Ash had tried to reach out to him a few times, sat next to him on the bench and talked about the war. In his more lucid moments, Frank would tell Ash about Vietnam and tease Ash about having all the high-tech gear. Apparently, this was not one of his more lucis moments. In fact, he'd never seen him this bad. Frank was pulling strands of hair out of his own head arguing with what other people probably thought was an invisible force. The dents on the roof of the truck revealed the source of some of the noises he couldn't make out earlier. Then Franks eyes narrowed and he went into a fit and started banging his fists on the hood. </span><br />
<br />
"Hey-- Stop it-- That's my truck you old idiot-- " a teenage boy yelled but stayed back.<br />
<br />
Ash scanned the crowd for anyone to assist with the situation. <span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">The man with the glasses had managed to shove his way through&nbsp;on the
other side of the crowd.&nbsp;<em>Maybe that's Turtleneck's real job.</em> Glasses had his eyes fixed on&nbsp;his tablet and not directly the scene, taking pictures no doubt, <em>tourists.</em> Several other's had their cameras on, taking live video.&nbsp;<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><em>They always live behind their camera taking selfies and posting videos. Why can't people just be present, in the moment? </em></span>Nobody seemed too interested in approaching the scene. Ash pulled out his flip-phone and pressed number one and held it a moment. <em>I'm probably the last person on the planet without a smart phone,</em>&nbsp;he thought. Orion PD displayed on the little screen, and he held it up to his ear.</span><br />
<br />
"Yell-oh," his friend George answered. <br />
<br />
"George.&nbsp;Ash. We need you down in front of the café. Frank, the old timer, he's gone totally off his rocker and he's causing property damage this time."<br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span><br />
"I'll be right there," George replied. "See what you can do to keep him from hurting anyone."<br />
<br />
"Heard," Ash said and closed the phone and put it in his pocket. <br />
<br />
Frank stopped beating the truck top momentarily and&nbsp;lifted his eyes to the sky and screamed, <span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">"You always did love Mother best-- I know-- That's
why-- You couldn't keep your mouth shut--". The rest of his words were unintelligible. </span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
Ash turned his attention to the dust cloud&nbsp;r<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">ising up off Frank's&nbsp;shoulders. A creature emerged from the dust, only the top half visible. It bore some resemblance
to a sloth but moved more quickly. It
swayed&nbsp;from shoulder to shoulder, shouting in each ear,&nbsp;visibly
agitated. Ash couldn't hear the creature, he never could, but it
was&nbsp;obviously feeding the other side of the conversation Frank had been having.</span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span>&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">The hair on his neck rose as he
watched it. <i>Could this be me if I&nbsp;stop taking my&nbsp;medication?</i>
He shuddered at the thought.<o:p></o:p></span><br />
<br />
Frank's conversation was going badly and he&nbsp;started beating his forehead into the roof of the truck several times before slowing to an unsteady stop. Blood poured down the old man's face from a gash in the left side of his temple. He grabbed his face and bowed his head and started sobbing.<br />
<br />
At the site of blood,&nbsp;someone shouted&nbsp;"Careful!&nbsp;He might be diseased." The crowd responded in unison with several steps backward, widening the semi-circle now almost fully formed around the truck and building.<br />
<br />
I guess it's up to me, Ash thought. "Frank,"&nbsp;&nbsp;he said and&nbsp;took a step forward to see if he could coax the man off the bed of the truck. "It's alright Frank. It's me, the high-tech woosie you love talking to. Come on down buddy." Three feet from the bed of the truck, Ash raised and offered his hand.<br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">A larger creature&nbsp;rose from the
mist behind Frank. This one had a different quality about it, more tangible. The bottom was
still rooted in the dust rising and falling from Frank. The top of the
creature was like that of a man, but it had the head of a bull with long horns
shooting out to each side and curving upward. The Bull-thing was over nine feet
tall, black skin made of charcoal,&nbsp;three white streaks&nbsp;across
and down&nbsp;its chest in white chalk.<o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">The bull creature cocked its head to
one side and stared Ash in the eye. Its
eyes were pools of black-smoke, billowing&nbsp;from their sockets. They&nbsp;pierced through him as
none of the previous creatures he'd seen before. Other creatures&nbsp;seemed more interested in
their hosts than Ash, but this one was staring him down. A fog entered his
mind, his vision clouded over slightly. The muscles in Ash's jaw tightened, and
he took a step back. A tingle ran down his thighs, he felt like he was suffocating.</span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">The Bull-thing's&nbsp;mouth
curved upward, eyes narrowed. It slapped the smaller creature into stillness and it disappeared into the mist.
Frank looked confused at the sudden silence. The larger creature leaned down
and spoke something into Franks' ear. The creature stood upright and evaporated back into the dust cloud. Frank turned to look at Ash, whose hand was still out to help him down. He looked at Ash's hand as though it were a weapon or snake. Frank's eyes narrowed,&nbsp; face contorted. He screamed, "Ahhhhh!" and the truck bed gave&nbsp;a rusty
creak as Frank leapt to the ground, spry for an otherwise elderly man. Head tilted
awkwardly to one side,&nbsp;he ran at Ash with a wild deranged look in his eye.
</span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span>&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Ash tried to step out of the way, or
run, but his legs were now glued to the
pavement. He raised his hands to prepare for a fight, but Frank jumped at him
before he could properly react, they both went tumbling to the sidewalk.<o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Ash's head slammed into the concrete
sending his vision swirling with&nbsp;white dots, and a throbbing throughout
his skull. He could feel Franks' hands on his neck, tearing into the flesh.
Making a fist, he aimed a punch at Frank through the white dots, where he
figured his head would be. </span><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Frank released his grip with one hand and loosened the other.</span></div>
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span><br />
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Ash caught his breath.
"Jesus," he&nbsp;cried as he recoiled at the throbbing in his throat
and gagging on the scent of unwashed clothing.<o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Frank backed up and looked
confused momentarily, as though he didn't know where he was. <o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Ash took the opening,&nbsp;kicked
Frank in the chest and sent him sprawling backward. He struggled to his feet and half-fell forward as he&nbsp;punched Frank&nbsp;with a
right-hook to the jaw. Frank spun back and fell to the sidewalk, unconscious. Ash fell beside him, one hand on his back and one hand on the ground. He took a deep breath, the skin on his throat burned. He reached to feel the man's neck for a pulse, <em>still alive. Good.</em></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Sirens&nbsp;pierced&nbsp;the
air&nbsp;as a patrol car sped to&nbsp;stop a few feet away. Two officers got
out and ran over, stopping just in front of Ash and Frank. <o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">"Dang old man," George the&nbsp;police officer said. "You still got it!"</span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span>&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">"I'll say. Remind me not to get on your&nbsp;bad side,"
the younger deputy said, cuffing the unconscious old man.</span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">"Hey Ash, those cuts look pretty bad. You OK? " George&nbsp;asked.<o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Ash rose to his knees, took a few deep breaths.&nbsp;The throbbing in his skull was subsiding, but his muscles were fast becoming sore&nbsp;from the altercation. "L</span>et me get you something for your neck," George said as Ash sat on a the curb. The deputy was kneeling next to Frank, checking pulse, talking codes into his shoulder-talkie. <br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
A few quick swabs, and a band-aide or too was all he needed. "Want to file a report?" George asked as he finished with the bandages. <br />
<br />
"Maybe later George, I'll let you know,"&nbsp;Ash gave George the look they'd agreed on&nbsp;one day when they met for coffee after the Veteran's&nbsp;support group meeting. He was&nbsp;hoping George would&nbsp;leave it alone.<br />
<br />
"Alright," George said and held his gaze a moment longer. He nodded as though he'd made up his mind and walked over to Frank. He turned over his shoulder, "But I want to see you tomorrow morning, you hear?"<br />
<br />
Ash nodded, relieved to get away from the scene. So many people staring at him was making his skin crawl.<br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span>&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">George looked down at Ash's jeans,
"You get yourself cleaned up, we need to take Frank in anyway." </span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">The two officers each grabbed one of Franks' arms&nbsp;and
laid&nbsp;him in the back of the squad car. They didn't bother to belt him, body&nbsp;awkwardly sprawled across the
back seat. The patrol car backed up and
took off down the street.</span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span>&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">"Are you OK sir?" a male
voice spoke from in front of&nbsp; him. A pair of highly polished leather shoes now occupied the ground in front of Ash's vision. </span><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Ash looked up&nbsp;slightly, the voice came
from the man in glasses. He was wearing a yellow polo, with two overlapping Es,
and gray slacks. </span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">"I'll be alright," Ash replied reaching for the bump
growing on the back of his head.<o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">"That was quite brave,"&nbsp;Glasses
said. "To step up when others stepped back."</span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
"Brave or stupid," Ash chuckled. "Ow..." the laughter hurt his head.<br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
"<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Your coffee spilled," Glasses observed. "Every do-gooder deserves a reward. Can I&nbsp;get&nbsp;you&nbsp;another?"<o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">With&nbsp;heart still&nbsp;stampeding through his chest, Ash replied,
"Thanks for the offer, Mr.--?"<o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">"Briar. Dr. Briar actually,"
the man replied.<o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">"Well thanks for the offer Dr.
Briar, but&nbsp;I've had enough excitement for one day. I just need to get
home, and cleaned up." <i>And a shower... and something way stronger than coffee....</i></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">"Another time then," Dr.
Briar smiled, his pudgy flat face pinched a little too tight around the cheeks. Too interested, too
helpful. But maybe Ash was over-reacting, considering the incident he just
endured. Then again, turtleneck's total lack of personality kept him on the
edgy side. <em>Nah</em>, he thought. <em>You're doing it again....</em></span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span>&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">He&nbsp;stood from the curb and waved them off. Ash&nbsp;walked down the street, wanting to get home, his refuge from humanity,
as fast as possible. He needed to escape, re-center, and espresso wasn't going
to do it this time. He needed a medically induced coma, 6 hours if he was
lucky. He turned back one more time to glance at the location of the incident.
Glasses was still watching him, turtle neck&nbsp;still behind. A nauseousness
crept into his belly, and he turned back toward his truck. Ash kept an eye on
window panes and the mirrors on cars he passed, to ensure he wasn't being followed.
</span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span>&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">In the town parking lot, just behind
the main buildings,&nbsp;was his escape. The&nbsp;1977 Ford F-150 wore a faded
blue paint job, with&nbsp;the rust spot accents. He adjusted the mirror
again, ensuring no one was watching him. The engine turned over like a beast
waking from slumber. The Marvel-Beast bobble head&nbsp;shook with the roar of the engine.&nbsp;The cool-smooth-glass floor shifter knob was a familiar tactile sensation in his palm, and his
stomach calmed a bit.<o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">He made his way down main
street. A
few miles down the highway, he turned onto a private road. Taking the driveway
two more miles into the woods, he parked in front a two story cabin-style home.<o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"></span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Ash glanced back&nbsp;one last time,
ensuring nobody followed him. He paused and listened for any sounds out of the
ordinary, tires on the gravel, shuffling in the house, a branch breaking.
Paranoia satisfied, he inserted the key, opened the door, and flipped the
switch.</span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span>&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Office to the left, den to the
right, hallway, <i>secure</i>. He made his way down the hall to the kitchen,
grabbed an orange bottle from the shelf and twisted the white top. <i>They
should call these adult-proof</i>. Two blue&nbsp;peacekeepers&nbsp;dropped into his hand. He placed the
pills&nbsp;on the counter,&nbsp;took a large plastic Braveheart collectors cup
out of the dish drying rack.&nbsp;The pills washed down
nicely with&nbsp;Dr. Pepper and Jack Daniels, half and half, over ice.<o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">The stairs to the second floor were
hard on his knee caps, but he managed with one hand, keeping a tight grip on
the cup of sleep. The fight replayed in his mind. Ash walked over to the
bookcase and pushed it aside, revealing a large steel Liberty Safe. A few spins
of the dial, and the heavy door swung open. He may not be licensed to carry
anymore, but that didn't stop him from keeping a stash of weapons, dating back
several generations of Ashland's leading on up to his retirement from the
United States Air Force, Special Tactics unit. Tonight felt safer with having
something nearby, so he grabbed the Glock 9mm, two extra clips, and the holster
and&nbsp;stashed them in the kitchen drawer so they'd be handy, just in case.
House alarm set, he made his way&nbsp;out onto the patio which was tucked away
out of sight. <i>Police report</i>, he
remembered and grabbed a sticky note and stuck it to the face
of&nbsp;the&nbsp;flip-phone.<o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">The hammock swung slightly, creaking
as it adjusted to his weight. It enveloped him like a cocoon, shielding him
from the events of the day. The first signs of stars peeped&nbsp;through the
evening&nbsp;sky. A chorus of crickets and critters chirped, his heart settling
into the rhythm of the night as Ash finished off the last of Dr. Daniels' magic potion. </span><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">The image of&nbsp;the man-bull
lingered in his mind, <i>so real, </i>he laid his head down and the
image&nbsp;faded to sweet nothingness.<o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">The mess hall wasn't much to look
at, a building in the middle of&nbsp;a desert Air Force base, thrown together
with gray cinderblocks and a make-shift
kitchen. It was over one hundred fifteen degrees outside, but the mess hall
managed to keep a balmy ninety-five. The
last of what passed for French fries sat on the tray&nbsp;in front of him.
"Did you hear what General Akbar said?" two&nbsp;soldiers at the
table in front of Ash were talking. "Yeah, another three months of this
hell-hole." Ash stood, grabbed the brown plastic tray that doubled as a plate
and walked to the trash to dump it.</span></i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">There was a bright flash, a shockwave&nbsp;propelled him&nbsp;face first
onto the wall, all went dark momentarily. When he came to, Ash found
himself&nbsp;on the floor of what was left of the mess hall. For a moment Ash
was deaf, accept a high pitched frequency ringing in both ears.&nbsp;Vision
returning, bracing his hand on the wall, he raised to his feet, the air cleared
some but&nbsp;smoke still obscured&nbsp;the scene as he tried to see what
happened.</span></i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Heart&nbsp;racing, hearing
normalizing. Nothing felt broken, everything moved. He took a step, nothing
hurt. He tried to make out his immediate surroundings. The ceiling was caved
in, mostly rubble. "Help me with this!" one soldier barked to
another, they lifted several fallen cinder blocks from a fallen soldier's leg.
From what Ash could tell from this&nbsp;distance&nbsp;it would need to be
amputated. Another concussion came from outside, a cloud of dust and smoke rose
to the sky, which was now visible from inside the mess hall. </span></i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Ash glanced once more at the scene
in front of him, there were enough rescuers, he needed to stop the onslaught.
He pushed through some fallen wall nearby
and paused to listen. A third explosion hit a building on the far side of camp,
there didn't seem to be a pattern. </span></i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">An image of the armory, his rifle;
he ran down the lane and hooked a left to the Armory. Rifle in hand, Ash took
off and found a steel communications
tower just higher than the rest of the buildings, and climbed to a small flat
spot he could use as a nest. They were targeting large buildings, it was a risk,
but an educated risk. </span></i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Ash steadied his breathing, after
the&nbsp;long run and climb, and positioned himself&nbsp;low on the flat
surface of the tower so his profile would be nearly invisible on the horizon.
The high powered scope revealed ten men,&nbsp;faces covered by
their&nbsp;keffiyehs and robes, hiding behind an outcropping of rocks and three
old jeeps. Two of them were holding rocket launchers, two others were helping
re-load. The rest were stationed around them with AK-74M Assault Rifles, ready
to defend their position.</span></i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Taking aim at the bulky portion of
the first rocket launcher itself, and not its handler, should incapacitate it,
and Ash rarely missed. The unit exploded in its handlers face. </span></i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">He looked away. This was his first
kill, but his stomach turned a little each time. It's us or them, they'd
started this, he would finish it. His blood boiled at the decision. Resolved, he peered
back through his scope and found the&nbsp;small band of attackers had turned
toward their fallen comrade, surprised by the explosion. The look on their face
said that they thought it had malfunctioned.</span></i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">That gave him the few seconds he
needed to line up the second shot. A second explosion took the remaining rocket
launcher and its handler out of commission. "Yes," he hissed to
himself. The band no longer posed an immediate threat to his buildings from
this distance, not with those rifles, but they were still a threat. A threat
now reduced to eight with no&nbsp;long range weapons. Three of the men&nbsp;decided to leave the relative safety of the
outcropping&nbsp;and run the mile and half of open desert firing at the outer
walls of the base.&nbsp;Like ducks flying&nbsp;from a bush.&nbsp;Ash&nbsp;aimed
and fired. Seven. Six. Five left. He re-centered
his scope on the rocks, the remaining five popped up periodically, firing
aimlessly.</span></i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Whack A Mole, he thought briefly,
and a "hmph" escaped his
throat. Ash&nbsp;fired&nbsp;each time he found a clean shot. Four. Three. Two.
For&nbsp;less than&nbsp;30 seconds, there was stillness from the desert. A
shadow by the farthest Jeep. The last two&nbsp;crawled inside, the Jeep sped
away from the scene. They were keeping low, out of sight. Ash aimed at the back
of each front seat. Two. One. The vehicle drove erratically and crashed into
the hill a little further out. The front gates of the base opened as an armored
attack vehicle raced out. They'd clean up anything he missed, his job was done.</span></i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">Back on solid ground, he surveyed
the scene. Devastation. By the time he'd taken the rocket launchers out, there
were four buildings decimated. The dead would be counted after the rescue was
over. Despite the sinking feeling in the pit of his stomach that wouldn't
leave, he chose to feel no remorse about the job he had to stop the attack. He
brushed the feeling aside and ran to back
to the mess hall to clean up. </span></i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">As he ran down the street toward the
mess hall, the&nbsp;scene turned white and morphed. Now he was jogging down a
long hallway with white walls and porcelain tiles. He stopped before a door,
tugged on his shirt, and glanced down at the letter he'd received that morning.
"Due to valor in the line of fire, you are hereby invited to join an
experimental&nbsp;program for soldiers with your unique skill set. Your invitation and participation is optional -&nbsp;classified as Top Secret.
Please report for a briefing at 10:00 hours..." Ash glanced at his watch,
2 minutes to 10:00. The door plaque read:
General Akbar. </span></i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">He raised his hand and knocked.
"Come," the voice replied. Ash opened the door, "Permission to enter, Sir?" General Akbar looked up,
"Come in soldier." As he
entered, General Akbar stood- </span></i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">The image morphed again, General Akbar's uniform was now worn by a larger man
shaped body, with the head of a bull. White striped streaked across its face. </span></i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">The scene turned to black...</span></i><span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span><br />
&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">The sound of crickets slowly brought
Ash back to his cabin patio. The hammock swinging slightly in the&nbsp;mountain
breeze through the mountain pass. Another one, <i>ugh</i>. He rubbed his eyes and glanced at his wrist. 3:00 hours.
His body ached, his heart was racing but his mind was foggy. Like it hadn't
fully kicked on. <i>Why would anyone live in a big city? Ugh... I need to go to town and file that report.
Maybe George will come up here instead... </i></span><br />
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;"><o:p></o:p></span>&nbsp;</div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<span style="font-family: &quot;times new roman&quot; , serif; font-size: 12pt;">A single falling star shot across
the night sky among the backdrop of a clear milky way. He decided to lay there
until his mind rebooted or shut down. <o:p></o:p></span></div>
<div class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto;">
<br /></div>
END Scene 1<br /><br /><a href="mailto:Me@DarrellWolfe.com">Me@DarrellWolfe.com</a><br /><br /><a href="https://www.verywell.com/relationship-between-ptsd-and-psychotic-symptoms-2797525">Posttraumatic Stress Disorder</a> and <a href="http://www.medscape.com/viewarticle/842449_2">Schizophrenia</a>&nbsp;and <a href="http://emedicine.medscape.com/article/288154-medication" target="_blank">Medication</a> for PTSD<br /><br /><br />By <a href="https://plus.google.com/+DarrellWolfe/posts">Darrell Wolfe</a><br />
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote>
<ul>
<li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li>
<li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li>
<li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li>
<li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li>
</ul>
<ul>
</ul>
