---
title: 'Distortion: Who - Why - Where - What - How'
date: '2016-10-04T02:45:00.0020000+00:00'
draft: true
blogger_blog: 'It''s Author Fun'
blogger_status: 'LIVE'
blogger_post_id: '875077567478191295'
blogger_filename: '/2016/10/distortion-who-why-where-what-how.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/It_s Author Fun/feed.atom'
categories:
  - 'Outline'
  - 'White Noise'
  - 'Character Sketch'
---

<br />
I need to get into the background of White Noise's lead Characters so I can re-write effectively. I'm using a few techniques I've picked up lately.<br />
<h4>
<span style="font-size: large;">Getting into the background: Dr. Briar</span></h4>
Dr. Briar is a scientist, first and foremost, but he's also bound to the needs of his financial benefactor "Thaddeus". <br />
<br />
They've had incidents from prior research "volunteers" that led to exposure to their less than legal program, code named "White Noise". One such incident involved a man who was perfectly normal before the experiment suddenly deciding to walk into oncoming traffic on a freeway. He said he did it at the demands of "voices in his head". He was taken to a hospital, but the next day he snuck out and did it again. He died, as did three other people due to the crash that ensued.<br />
<br />
A reporter, Grace Scriven,&nbsp;tied his medical records back to his involvement in "White Noise". Even after several press releases insisting no ties between their research (several years prior) and the current incidents, she was not satisfied and she kept pressing.<br />
<br />
These incidents led local authorities in Los Angeles (LA), County California to investigate the Institute further, which&nbsp;put them at Legal and Regulatory risk, but also increased&nbsp;media exposure. <br />
<br />
Dr. Brian doesn't know it, but Thaddeus (his benefactor) is operating under an Assumed Alias that he spent a great deal of time creating, and this is why he is getting even greater pressure from Thaddeus to keep a lid on the exposure.<br />
<br />
At the <strong><em>lethal</em></strong> insistence of his benefactor and due to a fear of losing his own research (which he prizes above life itself), Dr. Briar agrees to hunt down and exterminate any participants of "White Noise" that were showing any signs of ill-effects.<br />
<br />
At the start of our story, due to the length of time it's taken and the increased pressure from a variety of sources, Thaddeus now insists that ALL participants of White Noise either become deceased or vegetative in short order (or Dr. Briar himself will be eliminated).<br />
<br />
Dr. Briar heads to Ashland, OR where two of his former volunteers happen to reside (no relation). <br />
<br />
Grace Scriven has been monitoring his travel plans and happens to track him to Ashland, Oregon where she begins to understand the level of&nbsp;the Dr.'s&nbsp;depravity.<br />
<br />
Dr. Briar sneaks poison into Ash's coffee, but he doesn't drink it before an outburst outside (with the other volunteer) causes him to lose the contents, spilling them onto the ground.<br />
<br />
After seeing him handle the volunteer, Dr. Briar sends a hit man to cause Ash to "crash" his truck off a cliff on his way back to his cabin.<br />
<br />
Grace (disguised - incognito) saw Dr. Briar's interest in Ash the first time around. She follows him to his car and she's with him when the crash attempt occurs.<br />
<br />
The hit man checks to ensure fatality, realizes they escaped, and follows them into the forest to finish the job.... <br />
<br />
<strong>Now Action!</strong><br />
<br />
<h4>
<span style="font-size: large;">Getting into the background: Ash</span></h4>
His mother passed away giving birth to his younger sister. <br />
<br />
While Ash was in college in Oregon, his sister Jennie (one year younger) went to Biola University in southern California. When she was at an event in down town LA, performing, she was killed accidentally in a drive shooting&nbsp;by El Maduro, a Latino gang from Los Angeles. They were attempting to a revival gang member present on the scene.<br />
<br />
After his sister died, his father (a pastor) killed himself too. Leaving Ash with the house, and no family. Ash was already in his senior year getting a B.S. in Military Science, and he went into the USAF after that year (to run away from the memories and pain).<br />
<br />
His lack of family ties made him an excellent candidate for the unsanctioned Operation White Noise, which was the military wing of the experiment.<br />
<br />
Ash was a volunteer in White Noise while he was a USAF Captain,&nbsp;Special Tactics Officer. <br />
<br />
As a result of the experiment, he lost all memories from about 3 weeks prior to the experiment to 3 weeks afterward. This included the time period in which he volunteered. Therefore, he has no memory of it. He only knows that he woke with 12 weeks of missing memory (6 of, 3 before and after), with no explanation. He also knows that he's had strange PTSD side effects. He was medically discharged with little to no explanation. He was told that he was on a mission and recovered from behind enemy lines, and that's it. Which was a lie on behalf of his leaders. <br />
<br />
He was medically discharged 8 years ago. <br />
<br />
He moved into his parents home (which he's owned since his father's passing), a two story cabin style home in the woods of Ashland Oregon.<br />
<br />
The losses of his youth,&nbsp;later his memories, and his eventual PTSD symptoms left Ash a broken man. <br />
<br />
Internally, he jumps at the slightest hint of danger and&nbsp;he sees things that aren't there. But despite that, he strives for a normal life. His medications and&nbsp;counseling appointments keep him fairly stable. <br />
<br />
He sees clouds on nearly everyone, every day. On some people he sees actual creatures.&nbsp;Some sightings are clearer than others. Sometimes he sees a colorful cloud grow into a creature, then disappear into cloud again. Mist, smoke, vapor? Hm... <br />
<br />
After 8 years, he is generally able to shield his reactions from physically showing to all but the most keen observer. <br />
<br />
As part of his therapy, he writes what he sees in a notebook that he keeps in his pocket. He doesn't use cell phones or technology. <br />
<br />
Due to his own paranoia, he does keep unregistered weapons, a stash of burner phones, cash, passports, and transportation all at three&nbsp;safe houses. One local, two remote. He also knows the location of empty facilities in the immediate area that he can make use of at any given moment.<br />
<br />
As part of his ritual to keep life normal, he works in his workshop making furniture and carvings from the wood on his property (25 acres). He brings the items into town every few days to sell through a local craftsman consignment store, Woodmen Furnishings.<br />
<br />
He also stops by the Grounded Cafe' every Monday and Wednesday morning to sit and observe the locals. He has a Veterans support group every Wednesday evening. On Sundays he heads into town for Church on Sunday morning, and to the local Pub on Sunday afternoons (during football season).<br />
<br />
This particular Wednesday morning, he's just got his coffee when he's interrupted by crazy Eddie outside. He knows him, he usually acts up every few months, but never this bad. Then he sees creatures on Eddie, talking to him. He's attacked, spilling his coffee onto the ground. That's never happened before. He tries not to hurt him, and the police come and take&nbsp;Eddie away.<br />
<br />
Later, on his way&nbsp;to the support group, he meets a woman stranded on the side of the road. She gets into his car for a ride into town. While driving to town, they are rammed off the road off a cliff, but survive. He sees a light creature (not an angel, make is something else, animal, rabbit? wolf? something), just before going off the cliff.<br />
<br />
He comes to, injured, the girl is fine, but trapped. There is a man at the top of the cliff holding a gun. Instinct tells him that this is no accident, and he runs with the girl into the forest. They are tracked by the hit man. This is when she confides that she is a reporter, that Dr. Briar was interested in Ash, and she thinks they are up to something.<br />
<br />
Ash leads evades the hit man, brings the girl to his safe house, and he gets his weapons. The safe house is shot up, and Ash kills the hit man. They then take off in his back up vehicle (or motorcycle) and head out of town. <br />
<br />
<strong>Action!</strong><br />
<br />
<br />
<h4>
<span style="font-size: large;">Getting into the background: Grace</span></h4>
Grace Scriven has wanted nothing less than to be a reporter. She was assigned fluff pieces and other things she didn't like for over ten years of her career. She had enough, so she went Freelance. She kept enough work through Freelancing that she paid the bills. She also worked for more than one news paper this way.<br />
<br />
In the meantime, she kept her eye out for stories that could "make her career". She wants to prove her worth as a real journalist, and make a difference in peoples' lives, give them a voice. <br />
<br />
She is also willing to step on people's toes to get her reports, which doesn't make her a lot of friends, or give her the chance to make a positive impact on the people she meets. Her desire to be a star reporter often leaves her pushing her sources too far and too hard; hurting the ones she was supposed to be giving a voice to.<br />
<br />
After several false starts, she found a story nobody was following. Grace titled the piece, "What Noise - A science experiment gone amuck (working title)."<br />
<br />
She spent the better part of two years worth of her off time looking into the operation. She finally landed a solid lead with Dr. Briar's trip to Ashland, Oregon. She decided to follow him there where she hoped to catch him doing something nefarious, or at least get a clue to what they were up to. She knew his volunteers kept disappearing, but he didn't know how to prove it.<br />
<br />
She saw Dr. Briar put something into Ash's drink, but she didn't know who he was. She assumed he must be a former volunteer. Before she could warn him, without exposing her disguise, a man jumped him knocking him over. The coffee spilled, and disaster was averted for the moment.<br />
<br />
Before she left the scene, she caught Dr. Briar staring at her. Recognition hit his eyes, and she ran.<br />
<br />
Grace needed to get to this guy before Dr. Briar could get to him again, so she lifted her hood and poured water on the engine to produce steam (a trick she'd learned from growing up around her mechanic father, who would wash down engines he worked on). Pretending to be stranded, she hoped Ash would stop and give her a ride, which he did. She tried to play it safe, ask questions, before she could reveal her real reason for getting to him, they were run off the road and chased through a forest.<br />
<br />
She agreed to run with him, as her life was in danger now too.<br />
<br />
<strong>Action!</strong><br />
<br />
<h4>
<span style="font-size: large;">Getting into the background: Chester</span></h4>
Chester Jandihar was the son of two parents that wanted him to achieve. He graduated college at 23 with a PhD in Computer Science and a Masters in Behavioral Psychology. He was working with a cutting edge research firm, on an intuitive computer user interface program, when he cracked from the pressure. <br />
<br />
He was fired from his job, as undependable. His parents didn't disown him, but they didn't understand him either. They keep their distance.<br />
<br />
He got into drug and alcohol addiction, until he nearly died in an accident where he wrapped his car around a telephone pole, and killing a jogger. He was sentenced to three years for manslaughter,&nbsp;rehab and ongoing community service. Which is where he met Ms. Wu. <br />
<br />
Since then, he's worked Freelance as a programmer, and he volunteers as often as possible at Ms. Wu's. <br />
<br />
He brings in people to his house frequently, down and outers, who he feels obligated to help in one way or another.<br />
<br />
He is the most centered character, and he wants to help others with no expectation of return. But he also afraid that non of his good works will ever atone for his sin or the life he took.<br />
<br />
He is now 32, and he meets Ash and Grace, takes them in, and got more than he bargained for. But he's all-in. <br />
<br />
<strong>Can he help them survive, without becoming a target?</strong><br />
<br />
<h4>
<span style="font-size: large;">Getting into the background: Jazmin</span></h4>
<div class="MsoNormal" style="margin-bottom: 0in;">
<span style="font-family: &quot;book antiqua&quot; , serif; font-size: 10pt;">Jazmin&nbsp;Doe was the victim of a botched abortion attempt. The "doctor" delivered her whole, and she was thrown into a dumpster. The cries were heard by a passer-by and reported to the police. She was turned over to an adoption agency. One arm was injured and never grew right.</span><br />
<span style="font-family: &quot;book antiqua&quot;; font-size: x-small;"></span><br />
<span style="font-family: &quot;book antiqua&quot;; font-size: x-small;">Ms. Wu left her last name as Doe, as she did with all her orphans. She felt it gave them a unity together as a family, and the opportunity to shed the name for one of their own choosing if they wanted as they got older.</span><br />
<span style="font-family: &quot;book antiqua&quot;; font-size: x-small;"></span><br />
<span style="font-family: &quot;book antiqua&quot;; font-size: x-small;">She a mixed girl, mostly black. At the time of the story she is 16 years old.</span><br />
<span style="font-family: &quot;book antiqua&quot;; font-size: x-small;"></span><br />
<span style="font-family: &quot;book antiqua&quot;; font-size: x-small;">She is Chester's protégé, a hacker, and a good one. She's not as white hat as Chester though. She makes a living (secretly) doing grey hat, and black hat work.</span><br />
<span style="font-family: &quot;book antiqua&quot;; font-size: x-small;"></span><br />
<span style="font-family: &quot;book antiqua&quot;; font-size: x-small;">She wants to impress her mentor and make money for herself, not always possible to do at the same time.</span><br />
<span style="font-family: &quot;book antiqua&quot;; font-size: x-small;"></span><br />
<span style="font-family: &quot;book antiqua&quot;; font-size: x-small;">She thinks she's about to get&nbsp;a pay day and impress her mentor when she goes behind Chester to show him up. Instead it gets her in trouble... and killed?</span></div>
<br />
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<div>
<br /></div>
</blockquote>
<h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">
By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4>
<blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;">
<i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote>
<ul>
<li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li>
<li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li>
<li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li>
<li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li>
</ul>
<ul>
</ul>
