---
title: 'Building Traffic? How do I do it?'
date: '2011-12-29T07:03:00.0000000+00:00'
draft: true
blogger_blog: 'Tech Knowledge Storage'
blogger_status: 'LIVE'
blogger_post_id: '4823958234774412391'
blogger_filename: '/2011/12/building-traffic-how-do-i-do-it.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Tech Knowledge Storage/feed.atom'
categories:
  - 'Build Traffic'
---

<br />
One of the hardest things to learn concretely as a new blog writer is how to build traffic. Blogger and Wordpress both have their advantages. But Blogger makes it increasingly easy to use amazon&nbsp;affiliation&nbsp;and&nbsp;Google&nbsp;adsense. So there is so little work left to do but build the blog to an&nbsp;appearance&nbsp;of your liking and then write on your hearts passions. You are told from the start that MOST blogs don't make money and that&nbsp;writing&nbsp;should be done because you enjoy it. But if no-one ever reads it what's the point right?<br />
<br />
Then there is the point that comes after you've been doing this for years and you only see traffic from a few friends and relatives and some random foreign tracking machines that you wonder is there anything else? What's next? Can this be more?<br />
<br />
So you wonder what I am wondering now. How do I build a steady stream of traffic both from repeat visits and new visitors? How do I top the Google Hit List when someone looks up my subject? How do I get someone to click on those ads so I can make some money? That's what I want to know so I'm starting my research. I found the below articles that I don't have time to read. But I'll look into them and then see if there are any common threads that I can summarize.<br />
<br />
<br />
Articles on Building Traffic:<br />
<a href="http://www.seomoz.org/blog/21-tactics-to-increase-blog-traffic">http://www.seomoz.org/blog/21-tactics-to-increase-blog-traffic</a>
<br />
<br />
<a href="http://weblogs.about.com/od/bloggingtips/tp/TipsIncreaseBlogTraffic.htm">http://weblogs.about.com/od/bloggingtips/tp/TipsIncreaseBlogTraffic.htm</a>
<br />
<br />
<a href="http://techgyo.com/index.php/networking-to-increase-blog-traffic/">http://techgyo.com/index.php/networking-to-increase-blog-traffic/</a>
<br />
<br />
<a href="http://www.stevescottsite.com/how-to-increase-blog-traffic">http://www.stevescottsite.com/how-to-increase-blog-traffic</a>
<br />
<br />
Darrell G. Wolfe