---
title: 'Coby Kryos MID1125 Tablet - Android Market Place Work Around'
date: '2012-02-27T03:53:00.0030000+00:00'
draft: true
blogger_blog: 'Tech Knowledge Storage'
blogger_status: 'LIVE'
blogger_post_id: '2749546210716695684'
blogger_filename: '/2012/02/coby-kryos-mid1125-tablet-android.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Tech Knowledge Storage/feed.atom'
categories:
  - 'Tablet Talk'
---

<br />
Bought a <a href="http://www.cobyusa.com/?p=prod&amp;prod_num_id=10579&amp;pcat_id=3001" target="_blank">Coby Kryos MID1125 Tablet </a>on clearance. It comes with GetJar for getting apps, which is not all that helpful. Amazon App Store was MUCH more helpful. Then I finally found a way to install the Android Market Place, which some sites told me couldn't be done on this tablet. See below for the &nbsp;instructions that this person so nicely gave the rest of us!<br />
<br />
Posted from:<br />
<a href="http://forum.xda-developers.com/showthread.php?t=1285920">http://forum.xda-developers.com/showthread.php?t=1285920</a>
<br />
<br />
<span style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;">I hope this helps some people out there, because it drove me nuts trying to find a way to do this for the MID1125 since it's so new...</span><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><span style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;">First off, I was told by the two main rooting software developers that there is currently no way to root my device, so I needed to find a way to add Market without rooting the tablet. BTW, I’m running 2.3.3.</span><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><span style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;">Secondly, none of the guides on how to add Android Market out there worked for me (once again because my tablet is too new). Every time I tried to use Market, it would just keep crashing, so here is how I did it:</span><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><span style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;">1. Turn on the Debugging Mode (Settings&gt;Applications&gt;Development, then check the box).</span><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><span style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;">2. If you have a microSD card in the tablet, safely eject it.</span><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><span style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;">3. Plug your Kyros into your computer with the supplied USB cable and turn USB Storage on. You will then be prompted to open a window up, so do that because that is the internal storage of your tablet.</span><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><span style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;">4. Download and unzip the file I attached to your computer (there should be 8 files in the zip).</span><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><span style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;">5. Drag the 8 files onto the root of your device.</span><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><span style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;">6. Turn off USB Storage on your tablet and disconnect the cable.</span><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><span style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;">7. On your tablet, use a file managing program. I use the one that came stock on the unit, which is ES File Explorer. Once this program is open, you should see “/sdcard/” on the top left. If you don’t, click the home picture toward the top left. Now when you scroll down, you will see the 8 files that you dragged onto the tablet. Install them in the order that they are listed by selecting each one at a time, which should be GoogleBackupTransport.apk, GoogleCalendarSyncAdapter.apk, GoogleContactsSyncAdapter.apk, GoogleFeedback.apk, GooglePartnerSetup.apk, GoogleServicesFramework.apk, Talk.apk, and Vending.apk.</span><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><span style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;">8. Once all 8 files are successfully installed, reboot your tablet, and when it comes back on, click the Market icon, and log in with the normal Google username and password (or create a new account if you don’t have one).</span><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><span style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;">9. Turn off the Debugging Mode (Settings&gt;Applications&gt;Development, then uncheck the box) and you should be good to go.</span><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><br style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;" /><span style="background-color: #fbf8f4; color: #111111; font-family: verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif; font-size: 13px; line-height: 19px;">* I've successfully done this on three of these MID1125 tablets, so I figured I would try to save others the MANY hours it took for me to figure this out.</span>
<br />
<br />
For the files go to the website to see the original post, or<a href="http://forum.xda-developers.com/attachment.php?s=a36713b4246ed4bf5f082c1944426a51&amp;attachmentid=737731&amp;d=1317563485" target="_blank"> click here</a>.<br />
<br />
So Helpful!<br />
<br />
<br />
<br />