---
title: 'Conversation with Kory'
date: '2012-01-26T03:56:00.0000000+00:00'
draft: true
blogger_blog: 'Tech Knowledge Storage'
blogger_status: 'LIVE'
blogger_post_id: '1071266609006893127'
blogger_filename: '/2012/01/conversation-with-kory.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Tech Knowledge Storage/feed.atom'
categories:
  - 'Build Traffic'
---

<b><u>Conversation with Kory:</u></b><br />
<ul>
<li>How long you purchased the Domain name for matters to Google.</li>
<li>Quality AND Quantity AND Consistency Content</li>
<li>Consistency&nbsp;&nbsp;</li>
<ul>
<li>Wordpress platform is a good platform.&nbsp;</li>
<li>Knock out articles, but schedule the articles to post over time.</li>
</ul>
<li>Clean Code, up to date coding style</li>
<ul>
<li>Tables are for Tables and Data</li>
<ul>
<li>VS</li>
</ul>
<li>Clean and&nbsp;separate&nbsp;DIV's, Headings, Paragraphs, Etc...&nbsp;</li>
<ul>
<li>HTML 5: Elements like&nbsp;</li>
</ul>
</ul>
<li>Look for themes: Responsive to multiple Devices</li>
<ul>
<li>iPad, iPhones, Computers, TV's, Etc...</li>
</ul>
<li>Responsive: Content VS Style</li>
<ul>
<li>See:&nbsp;
<a href="http://css-tricks.com/">http://css-tricks.com/</a></li>
<ul>
<li>Content is focus no matter how you zoom in our out.&nbsp;</li>
<li>No matter how wide or small it works</li>
</ul>
</ul>
<li>Commenting is good.</li>
<ul>
<li>Just make sure that you add meaningful comments.</li>
<li>Cite other authors, but don't copy lots and lots of others content.&nbsp;</li>
</ul>
<li>Adding Content Media</li>
<ul>
<li>Embedding&nbsp;Video's, And other things.&nbsp;</li>
</ul>
<li>Wordpress best to used when you start hosting a site. &nbsp;</li>
<li>Buying a top level domain and hosting...&nbsp;</li>
<ul>
<li>Domains</li>
<ul>
<li>DON'T use Go Daddy</li>
<li><a href="https://www.hover.com/">https://www.hover.com/</a></li>
<li>.
<a href="http://www.namecheap.com/">http://www.namecheap.com/</a></li>
</ul>
<li>Hosting</li>
<ul>
<li><ul>
<li><a href="http://www.site5.com/">http://www.site5.com/</a></li>
</ul>
</li>
</ul>
<li>Themes</li>
<ul>
<li><a href="http://www.premiumwptheme.net/">http://www.premiumwptheme.net/</a></li>
</ul>
</ul>
<li>With themes, consider what you want out of it before you use it.&nbsp;</li>
<ul>
<li>If it's primarily it's about content, don't need to be too flashy or distracting.&nbsp;</li>
<ul>
<li>VS</li>
</ul>
<li>Business website that embodies your personality, maybe more flash. Unless people can sign on to your website like a bank.&nbsp;</li>
<ul>
<li>Interactive</li>
<ul>
<li>Bank is signing on</li>
<li>Restaurant, click and play</li>
</ul>
</ul>
<li>Examples &nbsp;</li>
<ul>
<li><a href="http://net.tutsplus.com/">http://net.tutsplus.com/</a></li>
<li><a href="http://www.smashingmagazine.com/">http://www.smashingmagazine.com/</a></li>
</ul>
</ul>
</ul>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>