---
title: '12/14/2023'
date: '2023-12-14T22:48:00.0000000+00:00'
draft: true
blogger_blog: 'Wolfe Testing'
blogger_status: 'DRAFT'
blogger_post_id: '3626454125059552'
blogger_filename: '/2023/12/12142023.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Wolfe Testing/feed.atom'
---

He read her text...&nbsp;<div><i><blockquote>"And i may buy a garter belt for my thigh high socks i just ordered"</blockquote></i></div><div>His heart skipped a beat, skin flushed, he suddenly felt very warm...&nbsp;</div><div><br /></div><div><i>She's not flirting with you, fool. She's just friendly, and excited about her outfit,</i> he thought.&nbsp;</div><div><br /></div><div>He did wonder if she was flirting, or if she was just nice. She used the word "date" the other day. He was getting such mixed signals. Or were they only mixed in his own head.</div><div><br /></div><div>They were both married, this was a foolish line of thinking.</div><div><br /></div><div>But he couldn't stop imagining a loose sweater, leading to a garter belt, which was attached to thigh highs, and her wearing nothing but these, and wondering what it would be like if she showed up at his house in this...&nbsp;</div><div><br /></div><div>He felt dizzy...&nbsp;</div><div><br /></div><div>Standing up, shaking his arms and legs, trying to catch his breath...&nbsp;</div><div><br /></div><div>&nbsp;"Now, what the hell was I supposed to be doing?" He wondered absent mindedly.&nbsp;</div><div><br /></div><div>After a few minutes, he remembered he was supposed to be working, and, flustered, he went to find his glasses.&nbsp;</div><div><br /></div><div>"Damnit, where did I put them this time?!" After a moment of squinting around, he realized, they were on top of his head. He might need a shower soon, to cool his thoughts.</div><div><br /></div><div><i>But what if she did....</i> he thought trailed as he looked out the window.</div><div><br /></div><div><br /></div>