---
title: 'BFT - Money Management'
date: '2013-07-06T03:08:00.0010000+00:00'
draft: true
blogger_blog: 'Bulldog Publications'
blogger_status: 'DRAFT'
blogger_post_id: '266482775524327582'
blogger_filename: '/2013/07/bft-money-management.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Bulldog Publications/feed.atom'
categories:
  - 'Banking'
---

<div style="text-align: center;">
<h4>
<b>Money Management</b></h4>
</div>
<h4>
Money as Time</h4>
&nbsp;&nbsp;&nbsp;&nbsp; I won't spend too much time on this subject of time. However I want to establish a baseline for everything we are about to discuss. How do you get money? You agree to go to work in order to get paid. Why?<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp; You want food, housing, healthcare, products, and services. You have 
time, 24 hours a day approximately. You can't go to a car dealership and
 give them your time for the car. They don't want it. There are 
occasions where your skill is worth as much to someone else as their 
skill is to you. You'll create a custom fish tank for them and they'll 
redo your old classic car for you. When people exchange their products 
or services with each other this is called "bartering". And it's still 
alive and well in 2013, maybe even on the rise, but it's still not the 
predominate way of obtaining what you want. In our society most people 
want money.&nbsp;&nbsp;<br />
<br />
<br />
&nbsp; &nbsp;&nbsp; Time is the one thing you have that you cannot get back. Once you give 1 minute to one thing you cannot take that minute back and do something else with it. That minute has been spent forever. It cannot, naturally, be redeemed. If you go to work you are selling a piece of yourself, your time. You agree to give someone 8 hours of your day plus travel time in exchange for $5/Hr, $10/Hr, $20/Hr, $100/Hr... why? Why on earth would you give your time, which you can never get back, in exchange for money that will be gone quickly? Well you need things. You need food, clothing, housing, and provisions. Also, you WANT things, like entertainment and enjoyment. Guess what? It's OK to WANT things. That's not evil or bad. Psalms 23 promises that if we serve God we SHALL NOT WANT for any good thing.<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp; What makes one persons time worth $5/Hr and another persons time worth $100? Business owners hire people to solve a problem or do things they don't want to do. If I don't want to mow my lawn, but the lawn needs to be mowed, someone else will have to do it. Either I get over my not wanting to and do it myself, or I PAY someone else for their time to do it. At what point do I give in and pay someone? I will pay them when my income and desire to not do it, increase past the point of my lacking income or desire not to spend the money. In other words, when my time becomes more valuable to me than the money it takes to pay someone else for their time.<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp; Cost of time then is equal to how much your time is worth. Low paying jobs are typically low skill and low thought jobs. It pays very little because nearly anyone could do it and there are MANY people competing for that paycheck. High paying jobs are those that require more skill, training, knowledge, and/or experience because those jobs are harder to do right. Less people have those skills and therefore less people are competing for those jobs. In a down economy where many skilled workers are looking for work, employers can pay less for those jobs because more applicants are competing for the jobs. In a great economy where there are more jobs that skilled workers to fill them the pay will be higher to attract more people to come do the job.<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp; What is the point to all of this? Your time is worth something to you. You alone can decide what your time is worth to you. And employers will decide what they are willing to pay for someones time. The job you land will depend on your ability to convince someone to pay you what you want for your time and your willingness to sell your time for a price they are willing to pay.<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp; Is there another way to get more money for less time? Possibly. If you want to start your own business you could sell your time by creating a products, providing services, or solving problems with creative solutions that people want or need. Then instead of your employer finding those buyers, selling the product or service and then paying you to deliver it, you erase the middle man and keep a higher percentage of the profit for yourself. You can also provide things people want or need directly. If you gain income enough to purchase a home for yourself and another home to rent, someone can rent the second home from you because they want a home but cannot afford to buy one. Now you are making money by providing a real need of another person, but it's costing you virtually no time at all. These are just the surface of this topic. Anything people need or want can equate to something you can provide with enough Time and/or Resources.<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp; If you are unhappy with the dollar amount you are selling your time for then you must decide what you are willing to do about it. You must find a way to obtain a higher price for your time. You could get more or different training, change fields, start a business or service, sell a resource, etc.The value of your time is found and the intersection of "what you are willing to sell your time for" and "what someone is willing to pay you for it". <br />
<br />
<br />
<h4>
Money as a Tool</h4>
What IS Money? You exchange your time for money? Why? You get money by exchanging your time for it. In simple terms money is a tool. As with any tool it can be used for good or misused for harm. You can use a hammer to drive a nail and build a house, or you can use a hammer to break a window. One is "Constructive" and one is "Destructive". It was not the tool that decided it's use, but the one who held it.<br />
<br />
Money is neither good nor bad. Some misquote a bible verse that by saying "Money is the root of all evil". It is not, that is not found in the bible.<br />
<blockquote class="tr_bq">
<i><a class="PassageTitle" href="http://www.biblestudytools.com/ceb/1-timothy/6-10.html">1 Timothy 6:10 CEB</a></i>
     <br />
<div class="Translation">
<i><a href="http://www.biblestudytools.com/ceb/">Common English Bible</a></i></div>
<i>
     </i><div class="VerseText">
<i>The <u>love of money</u> is the root of all kinds 
of evil. Some have wandered away from the faith and have impaled 
themselves with a lot of pain because they made money their goal.</i></div>
</blockquote>
&nbsp;The LOVE of money is the root of many (all kinds of) evils, not all of them. Money wasn't the issue, the Love of Money is. What you do with Money will bring you blessing or curse. Some call Money an amplifier. A good person with money will be better and a bad person with money will be worse. It is illogical to be a giver and tither and love God feel that Money would change that. If that person get's money they'll give more, tithe more and love the people of God more with that money.<br />
<br />
Since money is a tool, we should have a heart set with the right motives before we take to getting any. We should understand that God has made us Stewards over his Kingdom and therefore we are responsible for the things he gives us and we are to use them to further His work. In the parable of the Talents three men are given money by the Master. <a href="http://www.biblestudytools.com/matthew/passage.aspx?q=matthew+25:9-19" target="_blank">Matthew 25:9-19</a>. The reward was given to the two that used it wisely and grew it, the curse was given to the one who misused it and misunderstood it. If you want to live in Blessing and not Curse, you must understand Money and how to use it wisely. Therefore what talents, gifts, knowledge, skills, money, time, resources, etc, have you been given by God. He is expecting you to understand those, develop those and multiply them for Him and increase your own life in the process. It's not only possible for you to become wealthier than you are today, it's your responsibility under God to do so!<br />
<h4>
Balancing, Budgeting, and Bookkeeping </h4>
<br />
<ul>
<li>Processing and Posting Crash Course </li>
</ul>
<b>Processing </b><br />
Banks operate under the Federal Reserve. In basic terms when you deposit your check with Bank A and the check is drawn off of Bank B, Bank A sends that to the Federal Reserve who then sends it to Bank B for processing. Bank B then turns around a day or two later and sends the money back to Bank A through the Federal Reserve again. The Federal Reserve processes these payments overnight. If the Federal Reserve is closed banks cannot process payments to each other. Therefore processing is done Monday NIGHT through Friday NIGHT. The posting of these items is available for your viewing at some point during the night, no later than early morning the following morning.<br />
<br />
So if you're check is deposited on Monday you would see that check available Tuesday morning after it's processed as a courtesy to you. I say courtesy because the bank you deposited the check with may not have the money from the other bank for a week or more (although due to electronic processing this whole thing happens faster and faster as the days go on). If the bank puts a hold on your check it's because they don't want to loose and feel there is reason to believe the money may no be there when the try to get it.<br />
<br />
This process means there is no processing on Saturday night, Sunday night, or Holidays. If you deposit a check Friday it will usually be available Saturday morning. If you deposit a check Saturday it will usually be available Tuesday morning. Not Monday, remember there is NO processing on Sunday night!<br />
<br />
<b>Balances</b><br />
When you write a check, give your account number/card number online or over the phone, or in any way provide your banking information for a payment or withdrawal it will go through this processing and may or may not show as pending before it comes out. It's nearly impossible for the bank to tell you how much money you have because they don't know what you've done, only what they've received.<br />
<br />
Card transactions still go through this same processing, however they usually show as pending while they are waiting to be processed. I say usually because this is NOT always true. Even if you ONLY use card and never checks or check-by-phones or e-checks you're balance may still not be accurate. This is because cards can be used two ways.<br />
<br />
PIN/POS purchases typically clear the same day they are done. If you are having trouble with balancing your account try using ONLY PIN purchases and never "credit" at the machines. <br />
<br />
Checkcard/Credit purchases are cleared through the credit card companies. Usually Visa/Master Card. These transactions take two steps to process. First the merchant "authorizes" the card which is when it shows as pending to your account balance and you balance reflects that pending purchase.&nbsp; <br />
<ul>
<li>Overdraft Prevention</li>
<ul>
<li>#1 Spend LESS than you put in!&nbsp;</li>
<ul>
<li>Dealing with Basic Math.&nbsp;</li>
<li>Register Concepts (1-1=0)</li>
</ul>
<li>Debit Card Overdraft Service V Overdraft Protection</li>
<li>Bill Pay, Money Orders, Cash, V the rest (ACH, Checks, Card Payments)</li>
<li>Recurring Payments and Payment Processors (like Paypal)&nbsp;</li>
<ul>
<li>Pros and Cons&nbsp;</li>
<li>ACH V Card </li>
</ul>
</ul>
<li>&nbsp;Cash Living</li>
<ul>
<li>Envelope System</li>
<li>Multi Account Approach</li>
</ul>
</ul>
<br />
<br />
<br />
<br />