---
title: 'Basic Financial Training Intro'
date: '2013-07-05T23:47:00.0000000+00:00'
draft: true
blogger_blog: 'Bulldog Publications'
blogger_status: 'LIVE'
blogger_post_id: '1559355080595607650'
blogger_filename: '/2013/07/financial-basics-training-intro.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Bulldog Publications/feed.atom'
categories:
  - 'Banking'
---

I'm looking to develop a basic training course. It will consist of basic things a person would need to know to be financially successful. It will take the things I learned producing "<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6/ref=ntt_dp_epwbk_0" target="_blank">Banking Basics for Believers</a>" and those things I've learned and clarified since then. I want this to be simple enough to hear once and walk away with something small to read to remember the points. Maybe 1-3 courses and if there are more than one course they should be stand alone, you don't need to take them in order and you don't need to take all three to benefit from one. <br />
<ul>
<li><b>Money Management (Balancing, Budgeting, and Basics of Money as a Tool)</b></li>
<li><b>Savings (Buying the future one dollar at a time)(Including Retirement)</b></li>
<li><b>Credit (Maybe teach on credit if they want to build it or use it for select things)</b></li>
</ul>
From these topics, which I deal with daily in my job, I can build meaningful material, cover it in a quick class and provide an impact to others. Let's break it down into more detail.<br />
<br />
<ul>
<li>Money Management</li>
<ul>
<li>Money as a tool, what's for/not for, money not bad or good. Money = Time</li>
<li>How a bank account works, registers, processing, posting, etc. </li>
<li>Overdraft Prevention NOT Overdraft Protection</li>
<ul>
<li>Debit Card Overdraft Service</li>
<li>Overdraft Protection</li>
<li>Bill Pay</li>
<li>Recurring Debit Card Transactions</li>
<li>Envelope System/Multiple Accounts</li>
</ul>
</ul>
<li>Savings</li>
<ul>
<li>Why pay $35,000 for a $20,000 car that looses value?</li>
<li>Small steps, savings, investing, purchases, time.&nbsp;</li>
<li>&nbsp;Property Rent V Own</li>
<ul>
<li>15 Year Mortgage </li>
</ul>
<li>Retirement 30-50% income boost by owning home.&nbsp;</li>
<ul>
<li>IRA, 401K, Roth V Traditional </li>
</ul>
</ul>
<li>Credit</li>
<ul>
<li>Best option, live without credit</li>
<li>IF you must or feel that you want to engage in credit, here are the things you need to know.&nbsp;</li>
<li>FICO Building</li>
<ul>
<li>Score Breakdown </li>
<li>Credit Cards are Transaction Tools NOT Borrowing Tools</li>
<li>Buy less home</li>
<li>Borrow strategically</li>
</ul>
</ul>
</ul>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />