---
title: 'About You'
date: '2012-05-23T15:38:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Preston Markus Wolfe - Journal'
blogger_status: 'LIVE'
blogger_page_id: '6459341004263252269'
blogger_filename: '/p/about-you.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Preston Markus Wolfe - Journal/feed.atom'
---

<br />
<b>Preston Markus Wolfe</b><br />
<b>Born 09/18/2007</b><br />
<b><br /></b><br />
<br />
<ul>
<li>Priest - Warrior - Faith in Adversity</li>
<li><b><a href="http://www.thinkbabynames.com/meaning/1/Preston">http://www.thinkbabynames.com/meaning/1/Preston</a>
</b></li>
<ul>
<li><b style="background-color: white; font-family: Verdana; font-size: 11px;">Preston</b><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;</span><span style="background-color: white; font-family: Verdana; font-size: smaller;">\p-res-<a href="http://www.thinkbabynames.com/ending/1/ton" style="color: blue;">ton</a>,&nbsp;<a href="http://www.thinkbabynames.com/beginning/1/Pr" style="color: blue;">pr</a>(e)-<a href="http://www.thinkbabynames.com/ending/1/ston" style="color: blue;">ston</a>\</span><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;as a boy's name is pronounced&nbsp;</span><i style="background-color: white; font-family: Verdana; font-size: 11px;">PRES-ten</i><span style="background-color: white; font-family: Verdana; font-size: 11px;">. It is of&nbsp;</span><a href="http://www.thinkbabynames.com/search/1/english" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Old English</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">origin, and the meaning of Preston is "</span><a href="http://www.thinkbabynames.com/search/1/priest" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">priest</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">'s&nbsp;</span><a href="http://www.thinkbabynames.com/search/1/town" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">town</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">".&nbsp;</span><a href="http://www.thinkbabynames.com/search/1/place" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Place</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;name.&nbsp;</span><a href="http://www.thinkbabynames.com/search/1/actor" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">Actor</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;Robert Preston;&nbsp;</span><a href="http://www.thinkbabynames.com/search/1/film" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">film</a><span style="background-color: white; font-family: Verdana; font-size: 11px;"></span><a href="http://www.thinkbabynames.com/search/1/director" style="background-color: white; color: blue; font-family: Verdana; font-size: 11px;">director</a><span style="background-color: white; font-family: Verdana; font-size: 11px;">&nbsp;Preston Sturges.</span>
</li>
<li><span style="background-color: white;"><div style="font-family: Verdana; font-size: 11px;">
<b>Markus</b>&nbsp;<span style="font-size: smaller;">\m(a)-</span></div>
<a href="http://www.thinkbabynames.com/meaning/1/Markus" style="color: blue; font-family: Verdana; font-size: 11px;">rkus</a><span style="font-family: Verdana;"><span style="font-size: 11px;">,&nbsp;</span></span><a href="http://www.thinkbabynames.com/meaning/1/Markus" style="color: blue; font-family: Verdana; font-size: 11px;">mar</a><span style="font-family: Verdana;"><span style="font-size: 11px;">-</span></span><a href="http://www.thinkbabynames.com/meaning/1/Markus" style="color: blue; font-family: Verdana; font-size: 11px;">kus</a><span style="font-family: Verdana;"><span style="font-size: 11px;">\ as a boy's name is a variant of&nbsp;</span></span><a href="http://www.thinkbabynames.com/meaning/1/Marcus" style="color: blue; font-family: Verdana; font-size: 11px;"><b>Marcus</b></a><span style="font-family: Verdana;"><span style="font-size: 11px;">&nbsp;(Latin) and&nbsp;</span></span><a href="http://www.thinkbabynames.com/meaning/1/Mark" style="color: blue; font-family: Verdana; font-size: 11px;"><b>Mark</b></a><span style="font-family: Verdana;"><span style="font-size: 11px;">&nbsp;(Latin), and the meaning of Markus is "dedicated to Mars".&nbsp;</span></span></span></li>
<ul>
<li><span style="background-color: white;"><span style="font-family: Verdana;"><span style="font-size: 11px;">Mars was the The Roman god of war. Therefore by&nbsp;Extension: Warrior</span></span></span></li>
<li><span style="background-color: white;"><span style="font-family: Verdana;"><span style="font-size: 11px;">Mark, derived from Marcus was one of the four Gospel writers.</span></span></span></li>
</ul>
<li><b style="font-family: Verdana; font-size: 11px;"><span style="font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; font-size: 8.5pt; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;;">Wolfe</span></b></li>
<ul><ul>
<li><span style="font-family: Verdana, sans-serif; font-size: 8.5pt;">Motto: Fides in
      Adversis - Faith in Adversity</span></li>
<li><a href="http://www.houseofnames.com/wolfe-family-crest" style="font-family: Verdana, sans-serif; font-size: 8.5pt;"><span style="color: blue;">http://www.houseofnames.com/wolfe-family-crest</span></a></li>
</ul>
</ul>
</ul>
</ul>
<br />
<b><br /></b><br />
<b><br /></b><br />
<b><br /></b><br />
<b><br /></b><br />
<b><br /></b><br />
<b>Favorite Color:&nbsp;</b><br />
<b>All the Colors - "My most favorite color is: Orange</b><br />
<br />
Favorite Things:<br />
Whatever Connor Likes<br />
<br />
<ul>
<li>Lego</li>
<li>Thomas Train</li>
<li>Iron Man and War Machine</li>
<li><b>Atlantis Lego - The Favorite</b></li>
</ul>
<br />
<br />
<br />
<div style="text-align: center;">
<b>Family:</b></div>
<div style="text-align: center;">
<b><br /></b></div>
<div style="text-align: center;">
<b>Parents:</b></div>
<br />
<ul>
<li>Darrell Glen Wolfe</li>
<ul>
<li>Born 07/15/1980</li>
<li>Graduated from: LOL, Went to College of the Desert</li>
</ul>
</ul>
<ul>
<li>Flavia Antoinette Wolfe (Miller)</li>
<ul>
<li>Born 10/24/1981</li>
<li>Graduated from: Westmont College, Santa Barbara, CA</li>
</ul>
</ul>
<br />
<br />
<br />
<br />
<div style="text-align: center;">
<b>Siblings:</b></div>
Connor David Wolfe<br />
Kaylee Debra Wolfe<br />
<br />
<br />
<div style="text-align: center;">
<b>Grandparents</b>:</div>
By Darrell:<br />
<br />
<ul>
<li>Debra Yvonne Tweedy (Previous Last Names: Wolfe/Ford) - Born 07/10/1956</li>
<ul>
<li><a href="https://www.facebook.com/debbie.tweedy/timeline/story?ut=32&amp;wstart=-2649600&amp;wend=1170316799&amp;hash=1809052794663&amp;pagefilter=3" style="background-color: white; color: #3b5998; cursor: pointer; font-family: 'lucida grande', tahoma, verdana, arial, sans-serif; font-size: 11px; line-height: 15px; text-align: left; text-decoration: none;">Graduated from CSUSB</a>&nbsp;2007</li>
<li><span style="background-color: white; color: #3b5998; font-family: 'lucida grande', tahoma, verdana, arial, sans-serif; font-size: 11px; line-height: 15px; text-align: left;">Graduated from Arcadia High School</span>&nbsp;1974</li>
<li>Hometown Arcadia, CA</li>
</ul>
</ul>
<ul>
<li>Michael Craig Wolfe - Born 05/14/1954</li>
<ul>
<li>Hometown West Covina, CA</li>
<li>Graduated From: Azusa University, Claremont School of Heresy (Theology), Cal State Fullerton</li>
</ul>
</ul>
<div>
By Flavia</div>
<ul>
<li>JoAnn Southerland (Miller - ?) - Born 12/30/19??</li>
<ul>
<li>Hometown Aurora Colorado</li>
</ul>
</ul>
<ul>
<li>David Miller &nbsp;???</li>
</ul>
<div>
<br class="Apple-interchange-newline" /></div>