---
title: 'Quotes and Sayings'
date: '1980-01-05T08:39:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7775772581749123482'
blogger_filename: '/1980/01/quotes-and-sayings.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Quotes and Sayings'
---

<br /><ul style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">You must define your destination or you won’t know when you get there. Only then can you fulfill your destiny and reach your destination. (Paraphrase Jesse Duplantis)</li></ul><ul style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Wherever&nbsp;you go. There you are.(?)</li></ul><ul style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">What I love about&nbsp;sponsoring is that when I think something in my head it sounds OK. When I say it out loud it doesn’t sound so good. But when I hear you say it, it sounds down right STUPID! (Big John, AA)</li></ul><ul style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Prayer is the foundation for EVERY successful christian&nbsp;endeavor. (Kenneth Copeland)</li></ul><ul style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">The apex of all Christian endeavor must become to place the jewel of a soul in the crown of our King; to bring to the Lamb the reward of his suffering. (Pastor Rod Parsley)</li></ul><ul style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">When your’ manner of&nbsp;speech&nbsp;changes from “I need it” to “I got it” then the things you’ve been needing can come in to your life. (Tongues and Interp Ed and Nancy Dufresne)</li></ul><ul style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">You see the person who sits next to you should feel the same thing you do. If you really have hope it quickens the dead bones to your right and to your left. If they don’t want to change they’ve &nbsp;got to move. (Tonex’)</li></ul><ul style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">It’s about winning not competition. If I am competing I look for a prize, trophy, recognition. If I’m here to win I am here to make an eternal significance. (Al Pearson)</li></ul><ul style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Ask people to define their questions. Only after you get their question and definition can you give an answer. You cannot answer someone else’s question with your definition. Find their definition and then answer accordingly. (Al Pearson)</li></ul><ul style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">The difference between me and you is that you have a swelled head and I have a swelled heart. (Jerry Savelle/Kenneth Hagin)</li></ul>