---
title: 'e2p'
date: '2009-03-03T23:10:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3813324875429920415'
blogger_filename: '/2009/03/e2p.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'EMIC'
  - 'Mens Meeting'
  - 'study'
  - 'Random'
  - 'Prayer Time'
  - 'Daily Reading'
  - 'Job'
---

<div>E2p Now</div><div>Stands for Empowered To Prosper Now in this present world and in the world to come.&nbsp;</div><br /><div>"The Blessing" was given to mankind just after his creation. It was the command of God, the driving purpose for man, the underlying passion of everything man has ever done and God has ever done for man. The God who does not change ( ) and cannot lie ( ) spoke a &nbsp;series of commands into His man. These words set the stage, the precident, and the tone for all that was to come, forever. If you are asking yourself:&nbsp;Who am I?&nbsp;Where am I from?&nbsp;Why am I here?&nbsp;What can I do?&nbsp;Where am I going? Then you need to start with The Blessing! This was, is, and always will be God's original intention for all men, women, and children everywhere.&nbsp;</div><div></div><br /><div>The dictionary definition of blessed is to bring or have good fortune or happiness:</div><br /><div><a href="http://www.thefreedictionary.com/blessed">http://www.thefreedictionary.com/blessed</a></div><br /><div>BLESSED:<br />Adjective<br />1. made holy<br />2. RC Church (of a person) beatified by the pope<br />3. <strong>bringing great happiness or good fortune: he was blessed with good looks</strong>4. Euphemistic damned: I'm blessed if I know </div><br /><div></div>The Blessing can be found in:<br /><div><span class="Apple-style-span" style="font-style: italic;"><br /></span><br /><div><a href="http://www.biblegateway.com/passage/?book_id=1&amp;chapter=1&amp;verse=28&amp;version=31&amp;context=verse"><span class="Apple-style-span" style="font-style: italic;">Genesis 1:28</span></a></div><div><span class="Apple-style-span" style="font-style: italic;">God blessed them and said to them, "Be fruitful and increase in number; fill the earth and subdue it. Rule over the fish of the sea and the birds of the air and over every living creature that moves on the ground."&nbsp;</span></div><div><br /></div><div>As you study this out and watch the blessing in operation in the lives of the men and women of God throughout the word you notice a pattern. In Moses, Abraham, Issac, Jacob, Joseph, David, the prophets, Jesus, the Apostles... From small to great you notice a theme. When God is involved they are increasing and being fruitful, and having success. When God is not involved there is heart ache and pain.&nbsp;</div><div><br /></div><div>God lays it out in detail here in Duet. 28:</div><div><span class="Apple-style-span" style="font-family: 'Charis SIL';"></span><br /><h4><span class="Apple-style-span" style="font-family: 'Charis SIL';"><span class="Apple-style-span" style="font-style: italic;">Deuteronomy 28</span></span></h4><span class="Apple-style-span" style="font-family: 'Charis SIL';"><span class="Apple-style-span" style="font-style: italic;">&nbsp;</span><sup class="versenum" id="en-NIV-5613" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;" value="1"><span class="Apple-style-span" style="font-style: italic;">1</span></sup><span class="Apple-style-span" style="font-style: italic;">&nbsp;If you fully obey the LORD your God and carefully follow all his commands I give you today, the LORD your God will set you high above all the nations on earth.&nbsp;</span><sup class="versenum" id="en-NIV-5614" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;" value="2"><span class="Apple-style-span" style="font-style: italic;">2</span></sup><span class="Apple-style-span" style="font-style: italic;">&nbsp;All these blessings will come upon you and accompany you if you obey the LORD your God:</span></span><span class="Apple-style-span" style="font-style: italic;"><br /></span></div><div><br /></div><div>From the study of this the Holy Spirits' definition of "The Blessing" is to be Empowered to Prosper. Therefore the next time you hear someone sneeze don't say "bless you" be more purposeful in your approach, say "be empowered to prosper" or if you want to get thier attention... just say</div><div><br /></div><div>"E2P"</div></div>