---
title: 'Timing'
date: '2009-12-30T03:09:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3189431361365606962'
blogger_filename: '/2009/12/timing.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Job'
---

&nbsp;&nbsp;&nbsp;&nbsp; I thought I was ready for a promotion to a Team Lead years ago. My good friend Sharon pointed out that <b>I was not presenting myself as promotable</b> due to the attitudes I made visible when presented with change.<br /><br />&nbsp;<b>Lesson One</b>:<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; I took some time to retrain myself to respond accurately. To embrace change as quickly as possible. It wasn't easy to agree with a decision you did not agree with. But I had to find something I could latch on to. Or I had to disconnect myself from it and remind myself that it was NOT my business to run. It is this companies business. Some day I may be asked for my opinion on the changes presented. That day is not today. Someday I'll be running a business and expect my employees to run with it instead of fight it!<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; Just like when I remind a customer that I am not the one who overdrew their account nor am I the one who charged them a fee for doing so, I'm merely the interpreter. I must remind myself that I am not the one asked to make decisions at this time. I am the one asked to follow them through, and I am the one being PAID to do so.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; Company A asks me to come work for them. They pay me X amount of dollars. Therefore ANYTHING, legal and ethical, that they ask me to do is what I'm being paid for. THEREFORE, I do NOT have the right to balk at ANY decision they make. <b>Once I separated MY personal feelings, which is the root of all selfishness</b>, and remembered that I was being paid do a job, not being paid to like it or agree with it, then I became much more sane!<br /><br />&nbsp;&nbsp;&nbsp;<b>&nbsp; Lesson Two:</b><br /><br />&nbsp;&nbsp;&nbsp;&nbsp; I learned that<b> I am being watched by others</b>... leader by title or not. Therefore EVERYTHING I do will reflect upon my work and my coworkers. <b>Once I decided that I was a leader and started acting like it... I respected myself better.... and so did management!</b><br /><br />&nbsp;&nbsp;&nbsp;&nbsp; I got promoted to become a Coach and train others... I'm looking forward to doing more to sow seed to better my company now... in return I EXPECT to receive the same from my employees when I start my own businesses. It's amazing how a little maturity makes the difference.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;<b> In the end it wasn't my performance that got my moved up... it was my attitude. My performance bought me the right to be heard. Which only helped after I had something worthwhile to say...</b><br /><br />&nbsp;&nbsp;&nbsp;&nbsp; Good night.... parting thoughts.... <b>How are YOU being PERCEIVED</b> by your peers and superiors at your place of employment or in your arena of influence?<br /><br /><br /><br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Darrell G. Wolfe