---
title: 'LOVE Enough to choose...'
date: '2009-12-29T14:47:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '337395385761628703'
blogger_filename: '/2009/12/love-enough-to-choose.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

Revelations 20...<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; God&nbsp;LOVES mankind enough to&nbsp;lock up Satan for a thousand years and raise mankind in a perfect scociety. <br /><br />&nbsp;&nbsp;&nbsp;&nbsp; God LOVES mankind enough to let Satan loose and let MAN choose who he will believe. <br /><br />&nbsp;&nbsp;&nbsp;&nbsp; God LOVES manking enough to let him choose hell...<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; We've been saying for years here in America that it's all Scociety's fault. That had the person been raised differently they would have chosen a different life. God will prove once and for all that even in a perfect scociety, many will still choose the lie. <br /><br />&nbsp;&nbsp;&nbsp;&nbsp; God LOVES us enough to let us choose. <br /><br />&nbsp;&nbsp;&nbsp;&nbsp; What have you chosen today? <br /><br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Darrell G. Wolfe