---
title: 'I AM'
date: '2009-04-01T23:18:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '10536601478046327'
blogger_filename: '/2009/04/i-am.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
---

I AM that I AM...<br /><br />God said to Moses when he asked who he should tell the people who sent him: "...tell the people I AM sent you."<br /><br />As I've been thinking about this statement it occurred to me the other day that HE IS!!!!<br /><br /><ul><li>He IS right now with me as I type this message and instructing me to do it.&nbsp;</li><li>He IS right now in the void with just the Father, Son, and Holy Spirit in perfect union.</li><li>He IS right now forming the planet and the universe.</li><li>He IS right now speaking for the "first" time "LIGHT BE!!!"</li><li>He IS right now forming Adam and giving him life</li><li>He IS right now both protecting Moses as a baby AND directing him as the mighty leader.</li><li>He IS right now appearing to Saul of Tarsus and changing his life forever.&nbsp;</li><li>He IS right now forming ME in my mothers womb.</li><li>He IS right now giving me visions and dreams as a child of what HE has called me to do.</li><li>He IS right now before time began planning my day and future.</li><li>He IS right now standing here directing me with that forsight.</li><li>He IS right now in my future directing me in my Call AND Destiny!</li><li>He IS right now standing in heaven sourrounded by the raptured believers watching events on the planet.</li><li>He IS right now Rapturing the church.</li><li>He IS right now Coming back to set up his 1,000 Reign.</li><li>He IS right now closing the books on it all and creating His new heaven and new earth.&nbsp;</li></ul><div>HE IS</div><div>HE IS</div><div>HE IS</div><div>HE IS...</div><div><br /></div><div>What are you concerned about today that you wouldn't be if you really grasped that HE IS and you were sitting in HIS seat and had HIS perspective?</div><div><br /></div>