---
title: 'Path of Life'
date: '2009-04-07T17:18:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4684807535251331302'
blogger_filename: '/2009/04/path-of-life.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
---

Thought for the Day: <br /><br />Have you ever been walking through the old park. It has stairs that lead down into the wash. There are lots of stone along the wash, some big and some little. The path is very rough…<br /><br />Sometimes when you're walking through life there are rough spots. As you walk into the rough spots in life it gets harder to walk a straight line. You end up meandering around bigger obstacles and walking over smaller ones. In fact your eyes and attention are drawn to the path directly beneath and in front of you. In order to you to get a wider perspective of where you are on the path, where you have been, where you are going… You are required to look up. However if you walk the rough path looking up you are more likely to trip and fall. The path really does need your full attention to navigate. So what are you to do if you want a good view of the wider surroundings but need to watch the path? You have two options. <br /><br />Take frequent glances up… which does give you a broader perspective and may help with navigation, but still doesn't give you a great overview of the area. <br />OR… you can just stop. Stand completely still. In standing still you make no progress for good OR BAD. You may take a good look at everything around you. You can turn to see where you came from. You can see what's around you and what you have with you. You can take a good look forward. <br /><br /><br />Once you take that good look, you can begin walking again… slowly and purposefully. Take those extra glances frequently to make sure you're still on track. Feel free to meander a bit. Life is a journey just as much as it is a destination. Every so often, stop. Take a gooooooood look at your surroundings.