---
title: 'Good and Full!'
date: '2010-05-21T20:55:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '585418515709394970'
blogger_filename: '/2010/05/good-and-full.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

Acts <a href="http://www.biblegateway.com/passage/?search=Acts%2011&amp;version=NIV">11</a>-<a href="http://www.biblegateway.com/passage/?search=Acts%2012&amp;version=NIV">12</a><br /><br /><strong>11</strong><br /><strong>24He was a good man, full of the Holy Spirit and faith</strong>, and a great number of people were brought to the Lord. <strong>25Then Barnabas went to Tarsus to look for Saul</strong>, 26and when he found him, he brought him to Antioch. So for a whole year Barnabas and Saul met with the church and taught great numbers of people. The disciples were called Christians first at Antioch. <br /><br />May it be said of me: "He was a good man Full of the Holy Spirit and Faith." Not: "We'll... you just never knew about Darrell. Sometimes he was on the mark and sometimes he wasn't." It should be my goal to always strive for the absolute best, in faith, prayer, home, work, etc... Never settle down or get too comfortable. <br /><br />Lately I noticed a lot of success in my work life. I then noticed myself slack just a little in my prayer and bible times, I then noticed my work life take a steep plunge into "straining to attain" vs "flying high". It was like wind beneath my wings anymore. I felt the strain of trying to pull my days numbers up. It took me a week to realize what had happened. <br /><br />At the point of your greatest victories will be the point of your greatest trails. When others are singing your praises is when you find yourself in the most danger. Don't get into the hype of yourself. Put on the cloak of humility. I should have the same outlook for me, my family, my performance every day. Good or bad, rain or shine, just keep pushing harder and better. <br /><br /><strong>12</strong><br />1It was about this time that King Herod arrested some who belonged to the church, intending to persecute them.<br />21On the appointed day Herod, wearing his royal robes, sat on his throne and delivered a public address to the people. 22They shouted, "This is the voice of a god, not of a man." 23Immediately, because Herod did not give praise to God, an angel of the Lord struck him down, and he was eaten by worms and died. <br /><br /><br />Your enemies cannot last. They will either repent and become Ally's like Saul/Paul. Or be cut off like Herod. Don't be distracted with those who are against you. Pay no attention to them. Focus on Jesus, the Author and Finisher of all you are convinced by His word will come to pass through faith filled words. <br /><br /><strong>12</strong><br />5So Peter was kept in prison, but the church was earnestly praying to God for him. <br />6The night before Herod was to bring him to trial, Peter was sleeping between two soldiers, bound with two chains, and sentries stood guard at the entrance. <br />9Peter followed him out of the prison, but he had no idea that what the angel was doing was really happening; he thought he was seeing a vision.<br />11Then Peter came to himself and said, "Now I know without a doubt that the Lord sent his angel and rescued me from Herod's clutches and from everything the Jewish people were anticipating." <br />12When this had dawned on him, he went to the house <br /><br />&nbsp; <br />Peter was living by faith, knowing that either he would be delivered or go to heaven. WIN WIN in his mind. He was sleeping between two soldiers. Not wringing his hands trying to figure out what to do. The church was praying. Despite the fact he wasn't expecting to get out (evidenced by his surprise that it wasn't a vision) and THEY weren't expecting their prayers to be answered (evidenced by them believing it was his ghost at the door) God met them with great power. Peter was on assignment. God had work for him to do. <br /><br />I am on assignment, I have work to do too. Therefore NO weapon formed against me shall or ever will prosper. I will not disqualify myself from my calling and God will overlook my lacks and deficiencies with His grace. Together we will accomplish all He set out for me to do before the foundation of the world! <br /><br />Glory to God!<br /><span class="goog-spellcheck-word" style="background: yellow;">DW</span><br /><br /><br /><span><iframe align="left" frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?t=your0f4d-20&amp;o=1&amp;p=8&amp;l=bpl&amp;asins=0785267131&amp;fc1=000000&amp;IS2=1&amp;lt1=_blank&amp;m=amazon&amp;lc1=0000FF&amp;bc1=000000&amp;bg1=FFFFFF&amp;f=ifr" style="align: left; height: 245px; padding-right: 10px; padding-top: 5px; width: 131px;"></iframe></span>