---
title: 'GOODNESS - Mylon Le Fevre'
date: '2010-03-15T03:04:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6916922889782374081'
blogger_filename: '/2010/03/goodness-mylon-le-fevre.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

EMIC: 03/14/10<br /><br /><a href="http://www.mylon.org/homePage.php">Mylon Le Fevre</a> was our "guest" speaker today. Guest in that he has his own ministry now, but not a guest in that he came FROM EMIC and therefore was just home for a visit.<br /><br />Some of the key things that the Holy Spirit hit me with during service:<br /><br /><ul><li>There may be mortgage problems in Texas... but the mansions are paid for in the Kingdom of God.</li><li>Son, you are a student-teacher: Teach what you know and learn what you don't.&nbsp;</li><li>This is your' assignment:</li><ul><li>Stop trying to get money in</li><li>Start seeking ways to get The Word out</li><ul><li>Your problem has been mindset, focus, and lastingness</li><li> Write a mission and vision for your projects</li><li>Lift that veil!</li></ul><li>Word and Prayer and Confession: EVERY DAY! </li></ul><li>The Goodness of God is the foundation of Faith: Gloria Copeland</li><li>Anything good is God</li><li>Anything bad is the Devil</li><li>If you don't resist the bad, because you don't know to resist it... it won't flee.</li><li>As you seek God He rewards your diligence.</li><li>Kingdom: Kings Domain/Dominion</li><ul><li>Jesus is the Lord of the obedient</li><li>Jesus is the Judge of the disobedient</li></ul><li>Are you serving God or Money?</li><li>God has GOOOOOOD Plans for you Jer: 29:11</li><li>Contentment with godliness if GREAT GAIN</li><li>Have reverse paranoia: Everybody is out to Bless Me!</li><li>Sow + Wait = Harvest EVERYTIME</li><li>Contentment means that I am just as happy before I get what I wanted as after. The item or desire doesn't affect my joy level.&nbsp;</li><ul><li>I get it, then keep right on going. I don't gain or loose momentum.</li><li>ENJOY THE WAIT!</li></ul><li>IF is a covenant word. CHOOSE life: Deut. 30:19</li><li>David, after God's own heart, RAN TOWARD his enemies: Ps23</li><li>YOU enforce the Devil's Defeat</li><li>Goodness is following me</li><li>The way you describe you life to others is a test of your confession: We should be smiling as we are handed the test. </li></ul>