---
title: 'Great Faith Requires…'
date: '2010-01-23T05:59:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1936814296622613104'
blogger_filename: '/2010/01/great-faith-requires.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p>01/21/2010<br /></p><p><a href='http://www.biblegateway.com/passage/?search=matthew%2015&amp;version=NKJV'><span style='font-size:10pt'><em>Matthew 15</em></span></a><span style='font-size:10pt'><em><br />					</em></span></p><p><span style='font-size:10pt'><em>   <br/><sup>21</sup> Then Jesus went out from there and departed to the region of Tyre and Sidon. <sup>22</sup> And behold, a woman of Canaan came from that region and cried out to Him, saying, "Have mercy on me, O Lord, Son of David! My daughter is severely demon-possessed." <br/><sup>23</sup> But He answered her not a word. <br/>And His disciples came and urged Him, saying, "Send her away, for she cries out after us." <br/><sup>24</sup> But He answered and said, "I was not sent except to the lost sheep of the house of Israel." <br/><sup>25</sup> Then she came and worshiped Him, saying, "Lord, help me!" <br/><sup>26</sup> But He answered and said, "It is not good to take the children's bread and throw it to the little dogs." <br/><sup>27</sup> And she said, "Yes, Lord, yet even the little dogs eat the crumbs which fall from their masters' table." <br/><sup>28</sup> Then Jesus answered and said to her, "O woman, great is your faith! Let it be to you as you desire." And her daughter was healed from that very hour.<br /></em></span></p><p><br /> </p><p><span style='font-size:10pt'>Great Faith Requires a miracle… It demands the need met. <br /></span></p><p><span style='font-size:10pt'>Don't see Jesus as rude here. There are factors involved that we must consider. This woman is from an area that is not part of Israel. She is not in covenant with God through Abraham. She is unlike the soldier who at least had a position of authority in Israel and had a right to come before Jesus, but humbled himself and even renounced his right by acknowledging his unworthiness in God's eyes in relation to the covenant. She is in no position of authority. She is has no relationship to the covenant. She is a woman who is not even counted in the census'. She truly is the last person who "SHOULD" have a miracle. <br /></span></p><p><span style='font-size:10pt'>    Gravity is the most common law known to people. Not everyone understands other physics. But most people at least understand that gravity means that things fall to the ground. If you jump off a building you fall to the ground. However… as all present and powerful gravity appears to be on the outside… there is a set of higher laws that overrule gravity. In fact, these laws are so powerful it takes very little to put them into effect and overrule gravity. They do not cancel gravity… they over rule it. These are the Laws of Lift and Thrust. These laws are simple to put into effect. Anyone can get the blueprints for a paper airplane and practice building it and then toss it out. For a few moments the well built airplane, made of paper and powered by hand, will over rule gravity. <br /></span></p><p><span style='font-size:10pt'>    These laws take effort though. You must know something of what it takes to operate them. The more you learn the more you can effect them. The more effort you put into these laws the more you can get back. The paper airplane doesn't get the same results that the first airplane made by the Wright Brothers got. The Wright plane didn't get the same results as a 747. Each level takes more effort and more planning, more understanding of principles and physics and laws. The skilled pilot takes recurrent training. <br /></span></p><p><span style='font-size:10pt'>    She is walking outside The Covenant. Therefore, she falls under jurisdiction of the Devil and his Law of Sin and Death. He called the ruler of the darkness of this world. He got the authority from… God? Did God tell the devil he could have earth and men? Not a chance. But God gave Dominion and The Blessing to Adam. Adam surrendered it to Satan. God tried getting The Blessing into Noah. Then Abraham, who finally taught his sons and passed it to Jesus who died and took the keys of hell and death and gave them to us. <br /></span></p><p><span style='font-size:10pt'>    Jesus tells her this when he says: <br /></span></p><p><span style='font-size:10pt'><em><sup>26</sup> But He answered and said, "It is not good to take the children's bread and throw it to the little dogs."<br /></em></span></p><p><span style='font-size:10pt'>    She is not part of this covenant. The people of Israel are the children of the Covenant. She presses in with her faith though… which is what He is looking for her to do. She says, yeah, but crumbs still fall to the dogs! We should be getting the overflow of the children's covenant. That is exactly what the people in the world ought to be… blessed by those who are BLESSED. <br /></span></p><p><span style='font-size:10pt'>    She gets her miracle. Once Jesus died… He said to his disciples to GO… and THEN the Power of the Gospel was taken to the whole world. Now we ALL are children of Abraham, through Christ, and we are under that covenant! See <a href='http://www.biblegateway.com/passage/?search=Deut%2028&amp;version=NKJV'>Duet. 28</a>, <a href='http://www.biblegateway.com/passage/?search=Psalms%20103&amp;version=NKJV'>Psalms 103</a>, <a href='http://www.biblegateway.com/passage/?search=isaiah%2053&amp;version=NKJV'>Isaiah 53</a>, and <a href='http://www.biblegateway.com/passage/?search=genesis%201:28&amp;version=NKJV'>Genesis 1:28</a> to start to see your rights in that covenant. <br /></span></p><p><br /> </p><p><span style='font-size:10pt'>I not only have a right to receive my healing, which Jesus said belongs to the children which I now am, but I have a responsibility to disperse that to others. <br /></span></p><p><br /> </p><p><span style='font-size:10pt'>Darrell G Wolfe</span></p></span>