---
title: 'Withdraw and Take Authority'
date: '2010-04-21T04:06:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4712345445962479279'
blogger_filename: '/2010/04/withdraw-and-take-authority.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=john%2010&amp;version=NKJV">John 10</a><br /><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /><sup class="versenum" id="en-NKJV-26509" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">31</sup>&nbsp;Then the Jews took up stones again to stone Him.&nbsp;<sup class="versenum" id="en-NKJV-26510" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">32</sup>&nbsp;Jesus answered them, “Many good works I have shown you from My Father. For which of those works do you stone Me?”<br /><sup class="versenum" id="en-NKJV-26511" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">33</sup>&nbsp;The Jews answered Him, saying, “For a good work we do not stone You, but for blasphemy, and because You, being a Man, make Yourself God.”<br /><sup class="versenum" id="en-NKJV-26512" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">34</sup>&nbsp;Jesus answered them, “Is it not written in your law,&nbsp;<i>‘I said, “You are gods”’</i>?<sup class="footnote" style="font-size: 0.75em; line-height: 0.5em;" value="[&lt;a href=&quot;#fen-NKJV-26512c&quot; title=&quot;See footnote c&quot;&gt;c&lt;/a&gt;]">[<a href="http://www.blogger.com/post-create.g?blogID=6583916183087899714#fen-NKJV-26512c" title="See footnote c">c</a>]</sup>&nbsp;<sup class="versenum" id="en-NKJV-26513" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">35</sup>&nbsp;If He called them gods, to whom the word of God came (and the Scripture cannot be broken),&nbsp;<sup class="versenum" id="en-NKJV-26514" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">36</sup>&nbsp;do you say of Him whom the Father sanctified and sent into the world, ‘You are blaspheming,’ because I said, ‘I am the Son of God’?&nbsp;<sup class="versenum" id="en-NKJV-26515" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">37</sup>&nbsp;If I do not do the works of My Father, do not believe Me;&nbsp;<sup class="versenum" id="en-NKJV-26516" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">38</sup>&nbsp;but if I do, though you do not believe Me, believe the works, that you may know and believe<sup class="footnote" style="font-size: 0.75em; line-height: 0.5em;" value="[&lt;a href=&quot;#fen-NKJV-26516d&quot; title=&quot;See footnote d&quot;&gt;d&lt;/a&gt;]">[<a href="http://www.blogger.com/post-create.g?blogID=6583916183087899714#fen-NKJV-26516d" title="See footnote d">d</a>]</sup>&nbsp;that the Father&nbsp;<i>is</i>&nbsp;in Me, and I in Him.”&nbsp;<sup class="versenum" id="en-NKJV-26517" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">39</sup>&nbsp;Therefore they sought again to seize Him, but He escaped out of their hand.<sup class="versenum" id="en-NKJV-26518" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">40</sup>&nbsp;<b>And He went away again</b> beyond the Jordan to the place where John was baptizing at first, and there He stayed.&nbsp;<sup class="versenum" id="en-NKJV-26519" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">41</sup>&nbsp;Then many came to Him and said, “John performed no sign, but all the things that John spoke about this Man were true.”&nbsp;<sup class="versenum" id="en-NKJV-26520" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">42</sup>&nbsp;<b>And many believed in Him there.</b></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">The best place to go after conflict is to WITHDRAW and PRAY...&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">Get quiet before God and spend some time, even if you only have a few minutes get away. You may have un-expected results.&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">In this case Jesus' rejection turned to revival.&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">I read this in the morning, by 6:30pm I had gotten fed up with my day, and my results. I got away... and decided to start over. The rest went well and I made up what I was behind and I even got&nbsp;breakthroughs&nbsp;on my knowledge of excel. If only I had remember to get away earlier!</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">Jesus, in&nbsp;verse:&nbsp;&nbsp;<sup class="versenum" id="en-NKJV-26496" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">18</sup>&nbsp;<b>No one takes it from Me, but I lay it down of Myself. I have power to lay it down, and I have power to take it again.</b> This command I have received from My Father.”&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">I take it up, I lay it down!!! That is a command from the Father. We have no choice about that. I MUST take authority over my life. I MUST NOT allow circumstances to dictate ANYTHING to me!</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">Darrell G. Wolfe</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span>