---
title: 'Gone Fishing!'
date: '2010-01-11T20:10:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7933149587063455061'
blogger_filename: '/2010/01/gone-fishing.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://search.barnesandnoble.com/Fishers-of-Men/Lester-F-Sumrall/e/9781432597580">Fishers of Men, Dr. Lester Sumrall</a><br /><br />I'm reading a small booklet from Dr. Sumrall on wtinessing. AMAZING booklet, the first few times I tried to read it I found it boring. I know now it was because I was more interested in what God is doing for ME at the time. Now I'm more interested in serving HIM, and living this Kingdom. <br /><br />Far too often witnessing is over thought, or underthought. People are either too aggressive and turn others off, or too passive and never share the Hope in them. In Chapter one of this book we studied Andrew the Apostle. Only two brief encounters of Andrew are recorded. Both shed insight into the one by one soul winner. <br /><br />Once was when he left John the Baptist to follow Jesus and immediately ran to get his brother Simon (who we know as Peter the ROCK) By this one act he won a kingdom soul winner who would win thousands. Billions if you consider Peters words are still winning people today!<br /><br />Another time he is talking with a little boy while everyone is fussing about how to feed 5,000 men plus women and children. Andrew brings over a little boy. Andrew was a people person. He didn't get the spot light and he didn't win crowds. But he won them "Won by one!" <br /><br />In Both instances Andrew provded something miracoulus by his acts.<br /><br />So what are the steps to effective witnessing that I gained understanding of as I read this account:<br /><br /><ol><li>PRAY&nbsp;for opportunities. Ask God for a chance to share his LIFE with someone else.Don't just manufacture artificially a moment to share. You'll probably just turn the person off and sound wierd. </li><li>Start, or better recognize the opening for, a dialogue about Jesus (They may call it religion, don't get crazy with them... "well you know, it's not a religion but a relationship..." just take it for what they call it and demonstrate that relationship instead of telling them about it. "I was talking with Jesus the other day..." </li><li>Share your PERSONAL story. Don't get theological with them. If they ask something you don't know... GOOD. In sales we learn that asking is a sign of geniune, even if weak, interest. Get them in touch with a specialist. Provide them with a book, website, invite them to church to ask someone there... etc. Be creative. </li><li>Start with people you know not strangers on the street. MOST people won to Christ are won by someone they know or work with. VERY few are won by street preaching and tracts. They DOES work, but usually only in the hands of someone anointed to do it and lead of the Holy Spirit to be out there. </li><li>Diologue NOT Debate... questions are good. </li></ol>Have a great day fishing today!<br /><br />Darrell G. Wolfe