---
title: 'I commit myself... therefore no one takes it from me!'
date: '2010-04-05T18:28:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5605624107853269982'
blogger_filename: '/2010/04/i-commit-myself-therefore-no-one-takes.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

Welcome to Supernatural Monday!!!<div>Spring and New are Here!<br />My Prayer and Purpose:<br /><br />Drink the Living Water of the Spirit through praying in tongues<br />Eat the bread of life: The Word<br />Eat the meat of life: DOING His Will<br />Eat the&nbsp;Veggies&nbsp;of life: living in the Basic principles of God<br />Enjoy the Sweets of life: The Rewards of God<br /><br />Be Well&nbsp;Nourished!<br /><br /><br /><a href="http://www.biblegateway.com/passage/?search=Luke%2023&amp;version=NKJV">Luke 23</a><br /><br />How fitting... the day after easter we read about His death and burial. So much could be said about this chapter however I'm looking for what the Holy Spirit has to say to me specifically today!<br /><br />Jesus died ON a cross... NOT FROM a cross!<br /><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><sup class="versenum" id="en-NKJV-25978" style="font-size: 0.65em; line-height: normal; vertical-align: text-top;"><b>46</b></sup><b>&nbsp;And when Jesus had cried out with a loud voice, He said, “Father,&nbsp;</b><i><b>‘into Your hands I commit My spirit.’</b></i><b>”</b><sup class="footnote" style="font-size: 0.75em; line-height: 0.5em;" value="[&lt;a href=&quot;#fen-NKJV-25978n&quot; title=&quot;See footnote n&quot;&gt;n&lt;/a&gt;]"><b>[</b><a href="http://www.blogger.com/post-create.g?blogID=6583916183087899714#fen-NKJV-25978n" title="See footnote n"><b>n</b></a><b>]</b></sup><b>&nbsp;Having said this, He breathed His last.&nbsp;</b></span><br /><br /><br />&nbsp;&nbsp; &nbsp; It says in another account that they didn't have to break His legs like they did the other two. People on crosses died more from&nbsp;asphyxiation&nbsp;then blood loss. But that typically only happened after breaking their legs so that they cannot press up to breath.<br /><br />&nbsp;&nbsp; &nbsp; Jesus said:<br /><br /><span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"></span><br /><h2 id="passage_heading" style="font-size: 16px; font-weight: bold;">John 10:17-19&nbsp;(New King James Version)</h2><div class="result-text-style-normal" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><sup class="versenum" id="en-NKJV-26495" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">17</sup>&nbsp;“Therefore My Father loves Me, because I lay down My life that I may take it again.&nbsp;<sup class="versenum" id="en-NKJV-26496" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">1</sup><sup class="versenum" id="en-NKJV-26496" style="font-size: 0.65em; line-height: normal; vertical-align: text-top;"><b>8</b></sup><b>&nbsp;No one takes it from Me, but I lay it down of Myself</b>. I have power to lay it down, and I have power to take it again. This command I have received from My Father.”<br /><sup class="versenum" id="en-NKJV-26497" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">19</sup>&nbsp;Therefore there was a division again among the Jews because of these sayings.</div><br /><br /><br /><br />&nbsp;&nbsp; &nbsp; In death as in life the Son of Man was out living example of the Genesis 1:26 man. SO MUST I live like this too. I my LIVE my life in dominion not as a doormat. I commit my spirit, soul, and body to God! Therefore NO DEVIL and NO MAN CAN take my life from me! I am in control THOUGH the Holy Spirit.<br /><br /><br />Today: I commit my life to YOUR will and YOUR direction!<br /><br /><br /><br /><br /><br /><br /><br /><br /></div>