---
title: 'Untitled Post'
date: '2010-03-26T04:02:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1568489459525085058'
blogger_filename: '/2010/03/luke-16-8-so-master-commended-unjust.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=Luke%2016&amp;version=NKJV">Luke 16</a><br /><br /><br /><i><sup class="versenum" id="en-NKJV-25625">8</sup> So <b>the master commended the unjust steward</b> because he had dealt shrewdly. <b>For the sons of this world are more shrewd in their generation than the sons of light. </b><br \="" /><sup class="versenum" id="en-NKJV-25626">9</sup> “And I say to you, make friends for yourselves by unrighteous mammon, that when you fail,<sup class="footnote" value="[&lt;a href=&quot;#fen-NKJV-25626c&quot; title=&quot;See footnote c&quot;&gt;c&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=Luke%2016&amp;version=NKJV#fen-NKJV-25626c" title="See footnote c">c</a>]</sup> they may receive you into an everlasting home. <sup class="versenum" id="en-NKJV-25627">10</sup><b> He who </b></i> <b><i>is</i><i>what is least is faithful also in much; and he who is unjust in </i></b> faithful in <i><b>what is least is unjust also in much</b>. <sup class="versenum" id="en-NKJV-25628">11</sup> Therefore if you have not been faithful in the unrighteous mammon, who will commit to your trust the true </i><i>riches? <b><sup class="versenum" id="en-NKJV-25629">12</sup> And if you have not been faithful in what is another man’s, who will give you what is your own?    </b><br \="" /><sup class="versenum" id="en-NKJV-25630">13</sup> “No servant can serve two masters; for either he will hate the one and love the other, or else he will be loyal to the one and despise the other. You cannot serve God and mammon.”</i><br /><br />&nbsp; &nbsp;&nbsp;&nbsp; The children of the Kingdom of God are still over messing around in the worlds system and trying to get it working for them. The problem is that the worlds system is broken and only broken people can use it with any form of success. They may seem to be doing well for awhile. But sin always has it's payback.<br /><br /><br />&nbsp;&nbsp;&nbsp;&nbsp; The hardest part about being faithful is being consistent. It is fairly easy to be faithful in a hard time or emergency. But can you be consistent day in and out. When no people are looking, do you treat your family the same.&nbsp; Are you harder to deal with on days when you're tired or days that end in "y"? Are you seeking the best interest of every customer whether a new hire is sitting with you or not? Are you treating each and every person as though you were on review for a promotion? Because you are? Jesus himself is looking for people he can trust to do work in His Kingdom. But if you have not been faithful in what is another man's who will give you what is your own? Not God!<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; Consistency is THE KEY to living a faithful life for God!.<br /><br />Darrell G. Wolfe<br /><br /><br /><br /><br /><br /><br /><br /><br />&nbsp;