---
title: 'Mark 4'
date: '2010-02-20T21:03:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '94701033896984598'
blogger_filename: '/2010/02/mark-4.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p>2.20.10<br /></p><p>02.15-2.19 2010<br /></p><p><a href='http://www.biblegateway.com/passage/?search=Mark%204-8&amp;version=NKJV'><span style='font-size:12pt'>Mark 4-8</span></a><span style='font-size:12pt'><br />				</span></p><p><br /> </p><p><span style='font-size:12pt'>Mark 4:<br /></span></p><p><span style='font-size:12pt'>The Word is Planted by others…<br /></span></p><p><span style='font-size:12pt'>The Soil is OUR heart… the soil is OUR responsibility. If we will manage and take charge of our heart soil, the Word will do what it does best… PRODUCE the LIFE of the Kingdom of God in us!<br /></span></p><p><br /> </p><p><span style='font-size:12pt'>Soil Issues:<br /></span></p><p><span style='font-size:12pt'>A Note: Jesus is Addressing Covenant Israel here. Not heathens and people of the World. Spiritually and Prophetically He is addressing the Church. Of course this could apply to the Base Entry Level Message of the Kingdom which is being Born Again. But it also applies at every stage and level of the Life of God. You can rise to any level in God's Word in this Life and become halted by something God is trying to convey to you through his Word for the following reasons. You are never free of the need to maintain you Soil!<br /></span></p><ul><li><div><span style='font-size:12pt'>Path Soil<br /></span></div><ul><li><span style='font-size:12pt'>Hard, compact, only good for walking on.<br /></span></li><li><span style='font-size:12pt'>Birds come to steal the seed. Why? Because it's hard and cannot be rooted.<br /></span></li><li><span style='font-size:12pt'>Hardness of the heart is a common theme from day 2 after creation. <br /></span></li><li><span style='font-size:12pt'>Hardness is sighted throughout the word as being caused by bitterness, unforgiveness, and a lack of reverence to God or his Word. <br /></span></li><li><span style='font-size:12pt'>It's also been caused by a lack of obedience. One starts soft to the things of God, but after turning aside from something He commands of you several times it doesn't bother you as much. Certain scriptures call it a seared conscience. <br /></span></li><li><div><span style='font-size:12pt'>Solutions:<br /></span></div><ul><li><span style='font-size:12pt'>Turn on Praise Music that stirs you or used to. Music has a way of penetrating the heart, which is why you will never see a movie without it. Don't JUST listen to it. Participate in it. The more you don't feel like it… the more you need to.<br /></span></li><li><span style='font-size:12pt'>Meditate on the Love of God! How much does He Love you? How much does He Love them? How much should you Love Him and them? Are you bitter, or living in unforgiveness? Remember this litmus test: Forgiveness IS forgetting! You cannot "Forgive but not forget" as people say. It's impossible. You forgive and as an act of choice you forget! That means you don't bring it up anymore EVER! You don't remind them of what they did five minutes ago or five years ago! You choose to wipe it out, as a judge wipes it from the record! If  the thought it comes you say: I choose to NOT remember that… I call them Lovely and Loved of God!<br /></span></li></ul></li></ul></li><li><div><span style='font-size:12pt'>Stony Soil<br /></span></div><ul><li><span style='font-size:12pt'>Soil with stones and rocks throughout blocking any real fertilization or rooting.<br /></span></li><li><span style='font-size:12pt'>This is more common among believers. Most aren't ENTIRELY hard to the things God is wanting to do in them. They don't harden themselves so far that the seed doesn't even get received. Many are soft in part to God but there are areas of their life and circumstances have caused hard spots in them. Rocks of unforgiveness and bitterness. Areas of Hurt that they defend. Instead of seeking healing for them, however, they protect them saying: "Yeah… BUT… You don't understand what happened. To me…" They don't realize they could be free of it. <br /></span></li><li><div><span style='font-size:12pt'>Since no deep root is established here, the seed takes a little root and rises up, but it lasts on for a little while. When persecution or trouble comes for the Words sake the seed dies. This doesn't just mean that people give you a hassle for being a Christian. <br /></span></div><ul><li><span style='font-size:12pt'>If God calls you to live a life of Love, Satan sends people to give you a hard time.<br /></span></li><li><span style='font-size:12pt'>If God calls you to believe for debt free living bills, collectors, or other pressures try to come.<br /></span></li><li><span style='font-size:12pt'>Since there is no root inside of you for that calling the seed dies.<br /></span></li></ul></li><li><div><span style='font-size:12pt'>The solution is the same as above:<br /></span></div><ul><li><span style='font-size:12pt'>Meditate on the Love of God and Praise your way to healing.  <br /></span></li></ul></li></ul></li><li><div><span style='font-size:12pt'>Thorny Soil<br /></span></div><ul><li><span style='font-size:12pt'>Deep and nutrient rich, but filled with other plants that drain nutrient from the plant and cause it to look alive, but produce no fruit. <br /></span></li><li><span style='font-size:12pt'>There are no hard places in this soil. But there are weeds with thorns. <br /></span></li><li><div><span style='font-size:12pt'>Thorny Weeds can be things like:<br /></span></div><ul><li><span style='font-size:12pt'>Cares-of life (Bills, Gas in the Car, Getting to work, day to dayness… etc)<br /></span></li><li><span style='font-size:12pt'>Lies of Wealth- Money is to be your servant but never your God. Wealth is by no means evil, but believing that any amount of money will "Solve your problems" is a lie and it will choke the Word. It will cause you take action contrary to the ones God is asking of you. <br /></span></li><li><span style='font-size:12pt'>Desires- For other things, maybe good things, may try to take your time and energy and attention. Maybe you have a new business idea, maybe a good one. But if God hasn't called you to it than it has become a distraction from what He HAS called you to. It is stealing your time, talent, and energy from the God ordained things and it is making HIS seed unfruitful/unproductive in your life. <br /></span></li></ul></li></ul></li><li><div><span style='font-size:12pt'>GOOD Soil!<br /></span></div><ul><li><div><span style='font-size:12pt'>Produces 30,60, and 100 fold return. <br /></span></div><ul><li><div><span style='font-size:12pt'>Let me here explain "FOLD" it is confusing to many. I got an understanding of it playing "Farmville" on face book, which eventually became a distraction on my time and I had to stop playing.<br /></span></div><ul><li><span style='font-size:12pt'>Plant an acre of Flowers and you pay $75 in seed and time. <br /></span></li><li><span style='font-size:12pt'>Wait…and wait… and wait…<br /></span></li><li><span style='font-size:12pt'>Wait a little more…<br /></span></li><li><span style='font-size:12pt'>Harvest that crop and sell it for $275. Take that and buy more seed and replant. <br /></span></li><li><span style='font-size:12pt'>That is how you start with what your given and build up your crops and farm. <br /></span></li><li><div><span style='font-size:12pt'>Let's say for example:<br /></span></div><ul><li><span style='font-size:12pt'>One kernel of Corn produces a stock with five heads and 150 kernels per head, thus 750 Kernels. <br /></span></li><li><span style='font-size:12pt'>Replanting those seeds to create a new larger harvest would be the FIRST FOLD… <br /></span></li></ul></li><li><span style='font-size:12pt'>You become productive in the Word of God and Kingdom of God by taking what He's put in you and producing more and more with it. <br /></span></li></ul></li></ul></li></ul></li></ul><p><span style='font-size:12pt'>I choose to take charge of my soil… it is up to ME what kind of Soil I will have at any point in life, and therefore what kind of productivity I will have in Him! <br /></span></p><p><span style='font-size:12pt'>Darrell G. Wolfe <br /></span></p><p><span style='font-size:12pt'><br />				</span> </p></span>