---
title: 'I speak therefore I show whose I am.'
date: '2010-04-23T12:33:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7670876260824186770'
blogger_filename: '/2010/04/i-speak-therefore-i-show-whose-i-am.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

John 12<br /><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><span class="Apple-style-span" style="font-size: 16px;"><sup class="versenum" id="en-NKJV-26581" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">4</sup>&nbsp;But one of His disciples, <b>Judas Iscariot, Simon’s&nbsp;</b><i><b>son</b>,</i>&nbsp;who would betray Him, said,</span></span><br /><br />Note for later study... Was Judas Simon PETERS son or a different&nbsp;Simon's&nbsp;son?<br /><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><sup class="versenum" id="en-NKJV-26626" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">49</sup>&nbsp;For I have not spoken on My own&nbsp;<i>authority;</i>&nbsp;but the Father who sent Me gave Me a command, what I should say and what I should speak.&nbsp;<sup class="versenum" id="en-NKJV-26627" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">50</sup>&nbsp;And I know that His command is everlasting life. <b>Therefore, whatever I speak, just as the Father has told Me, so I speak.”</b></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">I will determine to listen to God to see what HE would say before I speak. Especially before I respond to an important matter, decision, or do anything in&nbsp;writing. My daily speech must be His words.&nbsp;Inappropriate&nbsp;joking and participating in comments and conversations that do not build up but rather tear down are not acceptable and not productive.&nbsp;</span><br /><br /><br /><br /><br /><br />Darrell G. Wolfe<br /><br /><br /><br /><iframe align="left" frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?t=your0f4d-20&amp;o=1&amp;p=8&amp;l=bpl&amp;asins=0982032056&amp;fc1=000000&amp;IS2=1&amp;lt1=_blank&amp;m=amazon&amp;lc1=0000FF&amp;bc1=000000&amp;bg1=FFFFFF&amp;f=ifr" style="align: left; height: 245px; padding-right: 10px; padding-top: 5px; width: 131px;"></iframe>