---
title: 'Anointed to Produce'
date: '2010-03-10T05:12:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3468594187426821409'
blogger_filename: '/2010/03/anointed-to-produce.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p><a href='http://www.biblegateway.com/passage/?search=Luke%204&amp;version=NKJV'><span style='font-family:Bookman Old Style; font-size:12pt'><em>Luke 4</em></span></a><span style='font-family:Bookman Old Style; font-size:12pt'><em><br />					</em></span></p><p><span style='font-family:Bookman Old Style; font-size:12pt'><em><sup>17</sup> And He was handed the book of the prophet Isaiah. And when He had opened the book, He found the place where it was written: <br/>       <sup>18</sup> " The <strong>Spirit</strong> of the LORD is upon Me,<br/>       Because He has <a href='http://www.biblegateway.com/passage/?search=isaiah%2061&amp;version=NKJV'><strong>anointed</strong></a> Me<br/>      To preach the gospel to the poor;<br/>      He has sent Me to heal the brokenhearted,<sup>[<a title='See footnote j' href='http://www.biblegateway.com/passage/?search=Luke%204&amp;version=NKJV'>j</a>]</sup><br/>      To proclaim liberty to the captives<br/>      And recovery of sight to the blind,<br/>      To set at liberty those who are oppressed;<br/>       <sup>19</sup> To proclaim the acceptable year of the LORD."<sup>[<a title='See footnote k' href='http://www.biblegateway.com/passage/?search=Luke%204&amp;version=NKJV'>k</a>] <br /></sup></em></span></p><p><span style='font-family:Bookman Old Style; font-size:12pt'><em><sup>43</sup> but He said to them, "I must preach the <strong>kingdom of God</strong> to the other cities also, because for this <strong>purpose</strong> I have been sent."<br /></em></span></p><p><span style='font-family:Bookman Old Style; font-size:12pt'>There is no purpose, no drive, no desire, no function, no job, no ideal… Nothing higher and of more importance than to recognize the Kingdom of God for yourself. It is a real Kingdom, with a real King. It is not merely a play, or ritual, or religion. It is not just story. It is not just a truth to be experienced on the other side. <br /></span></p><p><span style='font-family:Bookman Old Style; font-size:12pt'>    The Kingdom of God is a real, present, penetrating powerful force. It over rides and over rules all other Kingdoms, Nations, Rules, Governments, and Authorities. No law of physics can stand in opposition to This Kingdom. <br /></span></p><p><span style='font-family:Bookman Old Style; font-size:12pt'>    There is one purpose Jesus came, and one purpose I have been called to in life. All other callings, purposes, visions, dreams, goals, beliefs, and desires MUST stem from and be evaluated and judged by this highest of callings:<br /></span></p><p><span style='font-family:Bookman Old Style; font-size:12pt; text-decoration:underline'><strong><em> To distribute the Kingdom Of God to others Anointed of the Holy Spirit. <br /></em></strong></span></p><p><span style='font-family:Bookman Old Style; font-size:12pt'>The Anointing is that power of God that <a href='http://www.biblegateway.com/passage/?search=isaiah%2010:27&amp;version=NKJV'>Destroys the Yoke and Removes the Burden.</a> It is the Anointing that Jesus walked in on earth, it is the Anointing that raised him from the dead, it is the Anointing that Paul, Peter, John, and others walked out in signs and wonders. There has been much talk of the Anointing in certain circles over the last 100 years. However we must now look to the purpose of the Anointing if we are to walk out our calling as the Last Days Church. The Purpose is The Kingdom of God. <br /></span></p><p><span style='font-family:Bookman Old Style; font-size:12pt'>I work for Jesus Christ. I don't work for man. That means that when I seek promotion in my monthly income I DO NOT SEEK that from the "JOB" that I am working at. The company I report to CANNOT pay me enough to fulfill the dreams and visions and callings of my family. I MUST by necessity outgrow working for any company to walk out the specific callings on my life. <br /></span></p><p><span style='font-family:Bookman Old Style; font-size:12pt'>Even if you were called to work for a company, you are called to increase on and outside of it. You're income should never be limited to your paycheck. GOD gives the increase. <br /></span></p><p><a href='http://www.biblegateway.com/passage/?search=1%20Corinthians+3:7&amp;version=NKJV'><strong>1 Corinthians 3:7</strong></a><br/>So then neither he who plants is anything, nor he who waters, but <strong>God who gives the increase.</strong><span style='font-family:Bookman Old Style; font-size:12pt'><br />				</span></p><p><span style='font-family:Bookman Old Style; font-size:12pt'>    So I must start to think outside the cubicle if I am to see God's will come to pass in my life. However, there is a catch and trap here. I know this, but I must not therefore seek to see what I can do, create, "make happen" to force it. Before I can "DO" anything to participate in my increase I must first accomplish a few other things:<br /></span></p><ol><li><span style='font-family:Bookman Old Style; font-size:12pt'>Make the WORD First Place and Final Authority<br /></span></li><li><span style='font-family:Bookman Old Style; font-size:12pt'>Renew My Mind, mindsets, perceptions, and thinking<br /></span></li></ol><p><br /> </p><p><span style='font-family:Bookman Old Style; font-size:12pt'>I must realize that I work for HIM now. First thing in the morning I should report to him as I would to any commander or boss. I must ask Him for the orders of the day, and week, and month, and year. I seek Him in Prayer and the Word. I seek Him throughout the day. I'm on assignment. My work is NOT a place I go to pass the time until God uses me. IT IS my field of assignment. As I prove faithful there, I can move on to other works. <br /></span></p><p><span style='font-family:Bookman Old Style; font-size:12pt'>There is more that could be and needs to be said about this… but that will come another time and place. <br /></span></p><p><span style='font-family:Bookman Old Style; font-size:12pt'>What are your orders today sir?<br /></span></p><p><br /> </p><p><span style='font-family:Bookman Old Style; font-size:12pt'>Darrell G. Wolfe</span></p></span>