---
title: 'Untitled Post'
date: '2010-02-12T14:21:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4042661794000997361'
blogger_filename: '/2010/02/02.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p>02.12.10<br /></p><p>Mark 2 &amp; 3<br /></p><p><a href='http://www.biblegateway.com/passage/?search=mark%202&amp;version=NKJV'>Mark 2</a><br />			</p><p><em> <sup>1</sup> And again He entered Capernaum after some days, and it was heard that <strong>He was in the house</strong>. <sup>2</sup> Immediately<sup>[<a title='See footnote a' href='http://www.biblegateway.com/passage/?search=mark%202&amp;version=NKJV'>a</a>]</sup> many gathered together, so that there was no longer room to receive them, not even near the door. And He preached the word to them. <sup>3</sup> Then they came to Him, bringing a paralytic who was carried by four men. <sup>4</sup> And when they could not come near Him because of the crowd, they uncovered the roof where He was. So when they had broken through, they let down the bed on which the paralytic was lying.<br /></em></p><p><br /> </p><p>    Jesus went back to Capernaum, which we read earlier in Matthew was HIS HOME… We're not just talking about A house, or SOME GUYS house… This was Jesus' House… could you imagine being a preacher and using your own house to hold ministry services, which people do all around this country, and it gets SO crowded that the people can't get in, so people start tearing up your roof so that they can get a sick guy in??<br /></p><p><br /> </p><p>    Today, the preacher would probably sue for damages! Jesus didn't see reckless people with no respect for private property, Jesus saw FAITH… What are you seeing on a daily basis that may not be what YOU think you see??<br /></p><p><br /> </p><p><br /> </p><p><a href='http://www.biblegateway.com/passage/?search=mark%203&amp;version=NKJV'>Mark 3</a><br />			</p><p><br /> </p><p><span style='font-family:Times New Roman; font-size:12pt'><em><sup>20</sup> Then the multitude came together again, so that they could not so much as eat bread. <sup>21</sup> But when His own people heard about this, they went out to lay hold of Him, for they said, "He is out of His mind." <br/><sup>22</sup> And the scribes who came down from Jerusalem said, "He has Beelzebub," and, "By the ruler of the demons He casts out demons." <br/><sup>23</sup> So He called them to Himself and said to them in parables: "How can Satan cast out Satan? <sup>24</sup> If a kingdom is divided against itself, that kingdom cannot stand. <sup>25</sup> And if a house is divided against itself, that house cannot stand. <sup>26</sup> And if Satan has risen up against himself, and is divided, he cannot stand, but has an end. <sup>27</sup> No one can enter a strong man's house and plunder his goods, unless he first binds the strong man. And then he will plunder his house.<br /></em></span></p><p><span style='font-family:Times New Roman; font-size:10pt'><strong><em>The Unpardonable Sin<br /></em></strong></span></p><p><span style='font-family:Times New Roman; font-size:12pt'><em>   <br/><sup>28</sup> "Assuredly, I say to you, all sins will be forgiven the sons of men, and whatever blasphemies they may utter; <sup>29</sup> but he who blasphemes against the Holy Spirit never has forgiveness, but is subject to eternal condemnation"— <sup>30</sup> because they said, "He has an unclean spirit."<br /></em></span></p><p><span style='font-family:Times New Roman; font-size:10pt'><strong><em>Jesus' Mother and Brothers Send for Him<br /></em></strong></span></p><p><span style='font-family:Times New Roman; font-size:12pt'><em>   <br/><sup>31</sup> Then His brothers and His mother came, and standing outside they sent to Him, calling Him. <sup>32</sup> And a multitude was sitting around Him; and they said to Him, "Look, Your mother and Your brothers<sup>[<a title='See footnote e' href='http://www.biblegateway.com/passage/?search=mark%203&amp;version=NKJV'><span style='color:blue; text-decoration:underline'>e</span></a>]</sup> are outside seeking You." <br/><sup>33</sup> But He answered them, saying, "Who is My mother, or My brothers?" <sup>34</sup> And He looked around in a circle at those who sat about Him, and said, "Here are My mother and My brothers! <sup>35</sup> For whoever does the will of God is My brother and My sister and mother."<br /></em></span></p><p><br /> </p><p><span style='font-family:Times New Roman; font-size:12pt'>Jesus says later that anyone who doesn't hate his family, meaning love HIM more then them, isn't fit for the Kingdom… But Jesus actually demonstrates that FIRST before he says it. Here He is… turning from his biological family, to say that anyone that does the will of God is His family… which means you and I are also his family!! GLORY!! We're His family, You have a big brother, His name is Jesus… He's got your back!!<br /></span></p><p><br /> </p><p><br /> </p><p><span style='font-family:Times New Roman; font-size:12pt'>Darrell G. Wolfe</span></p></span>