---
title: 'Follow The Blessing!'
date: '2010-01-02T04:43:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5436597994944174436'
blogger_filename: '/2010/01/follow-blessing.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

01/01/2010<br /><br />2010: A Journey through the Word<br /><br />Mathew 1:1-17<br /><i>So all the generations from:</i><br /><i>Abraham to David were 14</i><br /><i>David to Babylon were 14</i><br /><i>Babylon to Jesus were 14</i><br /><ul><li>God Blesses Adam... he breaks covenant. God restores him, but we never hear from him again.</li><li>God Blesses Noah... Line Broken again.</li><li>God Blesses Abraham... Issac, Jacob... David...Jesus... Me!</li></ul>&nbsp;&nbsp;&nbsp;&nbsp; God didn't give up after the fall, nor did he cease to work with man despite his having to keep a distance. He keeps trying over and over to establish that link to the Blessing he started the planet with. That blessing has made it to me!&nbsp; <br /><br /><i><b><a href="http://www.biblegateway.com/passage/?search=Galatians+3:29&amp;version=NIV">Galatians 3:29</a></b><br />If you belong to Christ, then you are Abraham's <b>seed</b>, and heirs according to the promise.</i> <br /><br /><br />&nbsp;&nbsp;&nbsp;&nbsp; However it is my responsability to pass it on. Yours TOO! <br /><br />&nbsp;&nbsp;&nbsp;&nbsp; God is looking for people who will train others. Starting at home. How many powerfull ministries have had children who did nothing for God? How many have had children that did far more? The latter list is shorter, but shouldn't be. Your children, natural and spiritual, should be standing on your shoulders and using your acheivements as a platform to build from. They will have thier own callings, but no matter what God calls them to do, it will take the BLESSING to do it!<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In 2010 I'm going to look for ways to impart The Blessing into others, starting at home, then work and church, then anywhere else I can find an open door!<br /><br /><br /><br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Pssssst... Hey you.... Pass it on!<br /><br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Be Blessed, Darrell G. Wolfe