---
title: 'Fitting to Fulfil God&#39;s BEST in 2010'
date: '2010-01-06T05:17:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1521268169326208553'
blogger_filename: '/2010/01/fitting-to-fulfil-god-best-in-2010.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

Tuesday 01/05/2010<br /><br /><a href="http://www.biblegateway.com/passage/?search=Matthew%203&amp;version=NKJV">Mathew 3</a><br /><br /><i><sup class="versenum" id="en-NKJV-23202">13</sup> Then Jesus came from Galilee to John at the Jordan to be baptized by him. <sup class="versenum" id="en-NKJV-23203">14</sup> And John </i><i>tried to<br \="" /><sup class="versenum" id="en-NKJV-23204">15</sup> But Jesus answered and said to him, “Permit </i> prevent Him, saying, “I need to be baptized by You, and are You coming to me?”     <i>it to be so now, for thus <b>it is fitting for us to fulfill all righteousness</b>.” Then he allowed Him.    <br \="" /><sup class="versenum" id="en-NKJV-23205">16</sup> When He had been baptized, Jesus came up immediately from the water; and behold, the heavens were opened to Him, and He<sup class="footnote" value="[&lt;a href=&quot;#fen-NKJV-23205c&quot; title=&quot;See footnote c&quot;&gt;c&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=Matthew%203&amp;version=NKJV#fen-NKJV-23205c" title="See footnote c">c</a>]</sup> saw the Spirit of God descending like a dove and alighting upon Him. <sup class="versenum" id="en-NKJV-23206">17</sup> And suddenly a voice </i> <i>came from heaven, saying, “This is My beloved Son, in whom I am well pleased.”</i><br /><br />So I ask myself this question every time I read this scripture, but today I stopped and waited on the Holy Spirit, who has been assigned by Jesus to lead me into ALL truth (<a href="http://www.biblegateway.com/passage/?search=John%2016:13-14&amp;version=NKJV">John16</a>), this question again. For it seems to me that the answer should be something I would want to know.<br /><br />WHY? Why would Jesus be baptized? Why would that make a difference? How does a sinless man getting baptized for the remission of sins, which was Johns stated calling, fulfill anything?<br /><br />The answer was simple and profound. First of let us note that this is the VERY FIRST act of Jesus the adult we have recorded in the scripture. Water to wine may have been in first "miracle" but this was his first act. I want to know don't you?<br /><br />The act of baptism doesn't remit your sins. It was a symbolic foreshadowing of Jesus' Death, Burial, and Resurrection. It means dying to YOU. It means dying to YOUR will, and YOUR way and taking on GOD'S will for you and your life.<br /><br />God: I'll give you my life, which I haven't done very good with anyway, and I'll take yours instead. It is a symbolic ceremony marking the trade you make with God!<br /><br />So watch this: Jesus, knowing that this is the mark of his ministry start and will now begin the count down to the cross... calls those things that be not as though they are. He says I'm going to die, and raise again, and I'm going to do it to bring righteousness to ALL who will accept it. I'm going to say yes to that NOW, HERE, and the begining of my ministry!<br /><br />The Garden was a struggle and it was the final throws of putting down the flesh, but it started right here on day one of his minstry. This was not only his ordination by God. It was his accepting and aggreeing to the terms of this New Covenant from the start. He looked forward and saw you and I standing in his washed blood and free of sin and walking out God's perfect will in 2010.<br /><br />Jesus was saying yes to:<br /><ul><li>Sleepless nights praying</li><li>Crowds drawing on and draining him</li><li>Storms, conflicts, and persecutions</li><li>responsability of a full time staff of 12, part time of 70-120</li><li>Grueling Schedule</li><li>Friends and betrayals</li><li>Eternity with men and women grateful for his gift</li><li>Delight in seeing men enjoy life abundantly</li><li>God's Perfect Will for Cir AD 30<br /></li></ul><br />In Fact, Jesus wasn't just saying yes to God's will for His life. He was saying yes to God's will for MY life... here in 2010!!!<br /><br />Thank you Jesus for saying YES to me! I say YES to you to! What can I do to serve you more in 2010?