---
title: 'What if the end is NOT near?'
date: '2010-08-29T13:28:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6597927325204242816'
blogger_filename: '/2010/08/what-if-end-is-not-near.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<b>“Therefore be ye also ready: for in such an hour as ye THINK NOT the Son of man cometh.” (Matthew 24:44)</b><br /><br />&nbsp;In an article about an article about an article... lol... The story in USA Today by<a href="http://tomkrattenmaker.com/"> Tom Krattenmaker</a> is pointed out by <strong> <a href="http://blog.cloudtenpictures.com/2010/08/but-what-if-it-is/">Jack Kinsella</a>. <b><span style="font-weight: normal;">There is a shift in public press that is interesting. The last line of the article is what hit it home for me. I always read Matthew 24:44 and thought that just meant we ought not loose sight and forget He is coming. Now I realize this was actually pointing to WHEN He is coming. It's not so much saying that we must not forget, although it is saying that, it is ALSO saying that people will seek NOT to believe. </span></b></strong><br /><br /><div class="versetext"><h3 class="PassageTitle"><a href="http://www.biblestudytools.com/kjv/matthew/24-44.html" id="" title="Go to Matthew 24:44 (Standard View)">Matthew 24:44</a></h3><span class="versenum">44</span>     <a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=5124">Therefore</a> <a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1223">*</a> #ste <a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1096">be</a>  <a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=5210">ye</a> <a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2532">also</a> <a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2092">ready:</a> <a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=3754">for</a> in <a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=3739">such</a> an <a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=5610">hour</a> as ye <a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1380">think</a>  <a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=3756">not</a> the <a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=5207">Son</a> of <a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=444">man</a> <a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2064">cometh</a> . </div><br /><br /><br /><b>Think</b>:<span class="greek">&nbsp;</span><br /><span class="greek">In Greek: dokevw</span> <span>&nbsp;</span><br /><span>Pronounced: Dokeo</span><br /><br /><table><tbody><tr><td colspan="2"><span><b>Definition</b></span></td></tr><tr><td colspan="2"><span><ol type="1"><li> to be of opinion, think, suppose</li><li> to seem, to be accounted, reputed</li></ol><b>Not:&nbsp;</b><br />In Greek:&nbsp; <span class="greek">ouj&nbsp;</span><br /><span class="greek">Pronounced: </span><span><i>oo</i>&nbsp; <script src="http://www.biblestudytools.com/resource/javascript/lexiconaudio.js" type="text/javascript"></script> <span id="LexiconAudio" url="http://www.biblestudytools.com/resource/flash/player-button.swf?audio=http://ht.salemweb.net/bst/lexicons/greek-mp3/3756g.mp3"><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" height="17" type="application/x-shockwave-flash" width="17"><param name="wmode" value="transparent"><param name="movie" value="http://www.biblestudytools.com/resource/flash/player-button.swf?audio=http://ht.salemweb.net/bst/lexicons/greek-mp3/3756g.mp3"></object></span></span><br /><br /></span><table><tbody><tr><td colspan="2"><span><b>Definition</b></span></td></tr><tr><td colspan="2"><span><ol type="1"><li> no, not; in direct questions expecting an affirmative answer</li></ol></span></td></tr><tr><td colspan="2">&nbsp;</td></tr></tbody></table><span><br /><br />&nbsp;People are at large and in mass will be looking for ways NOT to THINK about the coming of the Son of Man. This article from<a href="http://blog.cloudtenpictures.com/2010/08/but-what-if-it-is/"> Cloud Ten </a>points out that for decades the question posed by media has been: "Is the end near?" And now it has become: "What if the end isn't near?" This shift to looking for a way NOT TO THINK about it or looking for a way to THINK IT NOT is another sign of the end times. We are coming to a head. It could be several decades yet. There are certain things that still have to happen. But they could all happen very quickly! The BEST is yet to come for those who Follow Jesus. Not only in heaven, but right here on earth. The last days for believers is the BEST time to live. Miracles and Signs and Wonders are coming in force. After the gospel is preached to the WHOLE EARTH the end will come. Major crusades and signs in the streets. Healing, dramatic healing, will not just be in meetings behind doors, or even on TV. These will occur in grocery stores and on street corners. There is coming swift a new age. It is the last "Glorious Church" that Jesus is coming back for. And Glorious we are becoming.<br /><br /><br /><br />Praise God... DW<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />&nbsp;</span></td></tr></tbody></table>