---
title: 'Acts: Journey into the perfect will of God.'
date: '2010-06-02T19:06:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3342690879779705031'
blogger_filename: '/2010/06/acts-journey-into-perfect-will-of-god.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=Acts%2018&amp;version=NIV"><b>Acts 18</b></a><br /><br />&nbsp;<sup class="versenum" id="en-NIV-27569">24</sup>Meanwhile a Jew named  Apollos, a native of Alexandria, came to Ephesus. He was a learned man,  with a thorough knowledge of the Scriptures. <sup class="versenum" id="en-NIV-27570">25</sup><b>He had been instructed in the way of the Lord,  and he spoke with great fervor<sup class="footnote" value="[&lt;a  href=&quot;#fen-NIV-27570b&quot; title=&quot;See footnote  b&quot;&gt;b&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=Acts%2018&amp;version=NIV#fen-NIV-27570b" title="See footnote b">b</a>]</sup> and taught about Jesus accurately,  though he knew only the baptism of John</b>. <sup class="versenum" id="en-NIV-27571">26</sup>He began to speak boldly in the synagogue.  When Priscilla and Aquila heard him, they invited him to their home and  explained to him<b> the way of God more adequately.&nbsp;&nbsp;</b><br /><b><br /></b><br /><b>Here is a man that is already in ministry. He is preaching the repentance of John, similar to many evangelical churches today. He knows nothing of the Gifts of the Holy Spirit yet, but he is working faithfully and diligently with what he has. Then he is brought a word of correction to add to what he knows and he accepts it and progresses further.&nbsp;</b><br /><b><br /></b><br /><b>I see several things about this that I need to learn:</b><br /><b><br /></b><br /><ul><li><b>I don't need to know everything about everything before I start something.&nbsp;</b></li><li><b>I must be diligent to use what I know before I can be trusted with more.</b></li><li><b>I must not trust in my own smarts or "Know It All"-ness. I must remain correctable.&nbsp;</b></li></ul><b><br /></b><br /><br /><a href="http://www.biblegateway.com/passage/?search=Acts%2019&amp;version=NIV"><b>Acts 19</b></a><br />&nbsp;<sup class="versenum" id="en-NIV-27596">&nbsp;</sup><br />&nbsp;<sup class="versenum" id="en-NIV-27584">11</sup>God did  extraordinary  miracles through Paul, <sup class="versenum" id="en-NIV-27585">12</sup>so   that even handkerchiefs and aprons that had touched him were taken to  the sick, and their illnesses were cured and the evil spirits left them.   <br /><br /><br /><br /><sup class="versenum" id="en-NIV-27596">23</sup>About that time there  arose a great disturbance about the Way. <sup class="versenum" id="en-NIV-27597">24</sup>A silversmith named Demetrius..<sup class="versenum" id="en-NIV-27598">25</sup>He called them together,  along with the workmen in related trades, and said: "Men, you know we  receive a good income from this business.<br /><br />&nbsp;<sup class="versenum" id="en-NIV-27608">35</sup>The city clerk quieted  the crowd and said...<sup class="versenum" id="en-NIV-27614">41</sup>After he had said this,  he dismissed the assembly.<br /><br /><b>Three Men: All had a different impact.</b><br /><br /><b>Paul:&nbsp;</b><br /><b>&nbsp; &nbsp;&nbsp; Obeyed God and turned a city upside down.&nbsp;</b><br /><br /><b>&nbsp;Demetrius:</b><br /><b>&nbsp; &nbsp;&nbsp; Stirred up the city into a riot against two innocent men because he was afraid to loose money, which was his real god.</b><br /><br /><b>City Clerk:</b><br /><b>&nbsp;&nbsp;&nbsp;&nbsp; Use words to turn away an angry mob. The words the Holy Spirit used him to speak were enough to dissuade an entire angry mob and turn them all back to home.&nbsp;</b><br /><b><br /></b><br /><b><br /></b><br /><b>It only takes ONE to make a change and create an impact. What kind of impact am I causing today?</b><br /><b>&nbsp;</b> <br /><br /><br /><br /><br /><a href="http://www.biblegateway.com/passage/?search=Acts%2020&amp;version=NIV"><b>Acts 20</b></a><br /><br />&nbsp;<sup class="versenum" id="en-NIV-27621">7</sup>On the first day of the  week we came together to break bread. Paul spoke to the people and,  because he intended to leave the next day, kept on talking until  midnight. <sup class="versenum" id="en-NIV-27622">8</sup>There were many  lamps in the upstairs room where we were meeting. <sup class="versenum" id="en-NIV-27623">9</sup>Seated in a window was a young man named  Eutychus, who was sinking into a deep sleep as Paul talked on and on.  When he was sound asleep, he fell to the ground from the third story and  was picked up dead. <sup class="versenum" id="en-NIV-27624">10</sup>Paul  went down, threw himself on the young man and put his arms around him.  "Don't be alarmed," he said. "He's alive!" <sup class="versenum" id="en-NIV-27625">11</sup>Then he went upstairs again and broke bread  and ate. After talking until daylight, he left. <sup class="versenum" id="en-NIV-27626">12</sup>The people took the young man home alive and  were greatly comforted.<br /><br /><br /><b>Here Paul must be tired and about to take a journey to another city, which in those days wasn't as simple as hopping in the car and saying "Wake me up when we get there."&nbsp;</b><br /><br /><b>He could have turned in early to get a good nights rest before heading out. But his heart is for the people. He wants to give of himself everything he can before he leaves. He is willing to loose sleep that night to impart everything he can before he leaves.&nbsp;</b><br /><br /><b>He operates in faith to the level that he could raise a boy from the dead and go back to preaching about Jesus without blinking. He didn't trump it up and say "Yeah, that's right, I did that!" He just brushed it off "Oh, it's cool guys, he's fine, he's fine.... As I was saying..."&nbsp;</b><br /><b><br /></b><br /><b>I must develop a heart for the people and be willing to give of myself if I am to walk in the things of God too. I MUST step up my efforts to Pursue God, His Word, His Spirit, His Presence. Only bathed in His presence and purged of myself can I begin to operate the way He needs me to.&nbsp;</b><br /><br /><b>I must not just live FOR Him. I must put ME aside and BE Him, or rather let HIM be HIM through ME. Only when "I" die and He lives through me can I ever hope to be all He wants me to be and love His people the way He loves them, with His Love.</b><br /><b> </b><br /><b>DGW</b>