---
title: 'Water Walkers!'
date: '2010-01-20T22:37:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1077734348751289354'
blogger_filename: '/2010/01/water-walkers.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p>01/20/2010<br /></p><p><a href='http://www.biblegateway.com/passage/?search=Matthew%2014&amp;version=ESV'>Matthew 14</a> Part Two<br /></p><p>VS 24-36<br /></p><p><br /> </p><p>    Jesus has settled matters between He and His Father. It is now time to attend to the business of the Kingdom of God of which He is THE Ambassador. Jesus sees them struggling in the storm on the water, having gone out ahead of him. Jesus walks on water… the men say "Surely He is the Son of God." Yes the MEN say that… and He IS! However… is THAT the reason He can walk on water? No! For starters: If that were true He would be the only one on record. But He isn't… There were two men on the water that night… Granted Jesus did it better… but He IS the Son of God… the ONLY perfect man… Of course He did it better. <br /></p><p><br /> </p><p>    So Jesus says: Yeah peter… Come on out. Peter gets out and walks on water. It doesn't say whether it was one foot, ten, 100 feet. The Fact is Peter ALSO walked on water, so something else is going on here besides Jesus being the Son of God. <br /></p><p>    Interesting Points to Observe:<br /></p><ul><li>Peter walked on water<br /></li><li><div>Peter BEGAN to sink.<br /></div><ul><li><div>Have you ever began to sink? Ever stepped out onto the water and said… oh my… looks like I'm sinking. <br /></div><ul><li>NO! You couldn't get "oh my" out before you were under. You don't BEGIN to sink, you SINK and HARD!<br /></li></ul></li><li>The fact that Peter BEGAN to sink required a miracle!<br /></li></ul></li><li><div>Jesus gets Peter, pulls him back up, they walk together back to the boat. <br /></div><ul><li>Jesus Replies: " Peter, it's ok, you know I AM the Son of God, you didn't have a chance there. You're not at my level yet there buddy."?<br /></li><li>NOPE!<br /></li><li>Jesus Replies: "What's up? Where's your faith? Why are you doubting?<br /></li><li>YEP! Jesus FULLY expects His people to operate like He does. Anything less is not acceptable. Forgiven by mercy and covered by grace… but not acceptable. <br /></li></ul></li><li>Jesus walks in such a great anointing, ONE DAY after the bad news that people, (MORE THAN ONE) are healed by the mere touching of his garment! Why… what caused the anointing on Jesus to operate at that level? <br /></li></ul><p>Jesus Spent Time in PRAYER!<br /></p><p><br /> </p><p style='margin-left: 36pt'><strong>I make a commitment, here and now. <br /></strong></p><ul><li>I will spend time, even just five or ten minutes, every day in undistracted prayer! <br /></li><li>Separate from my time in the Word! Pray through, and get direction.<br /></li><li><div>Don't stop if something is bothering you, until you get the matter settled inside of you. <br /></div><ul><li>Nothing outside may have changed. <br /></li><li>No money came in, no answer from the doctors reversing their report. <br /></li><li>But inside, you received it and there is a knowing that ALL IS WELL! <br /></li><li>Then you walk out, the interpretation of that prayer!<br /></li></ul></li></ul><p>    Glory! 2010 The Journey into the Perfect Will of God! Darrell G. Wolfe</p></span>