---
title: 'Untitled Post'
date: '2010-04-26T23:55:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '802367363321637046'
blogger_filename: '/2010/04/john-16-13but-when-he-spirit-of-truth.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=john%2016&amp;version=NIV">John 16</a><br /><br /><br />13But when he, the Spirit of truth, comes, he will guide you into all truth. He will not speak on his own; <strong>he will speak only what he hears, and he will tell you what is yet to come.</strong> 14He will bring glory to me by taking from what is mine and making it known to you. <br /><br />24Until now you have not asked for anything in my name. <strong>Ask and you will receive</strong>, and your <strong>joy</strong> will be <strong>complete</strong>. <br /><br /><br />33"I have told you these things, so that in me you may have <strong>peace</strong>. In this world you will have trouble. But <strong>take heart! I have overcome</strong> the world." <br /><br /><br /><br /><br />As I read today, I couldn't help but thinking how full of doubt I've actually been. Not doubt in God, or His Word, or even WHAT His word says. These things are steady in me. I've been doubtful about my ability to recieve them. This is mostly due to the frequency that I find myself saying something and not doing it. If you doubt your word, faith cannot rise. <br />&nbsp; <br />I make a renewed commitment today to not only BELIEVE but walk out the grace and love of God. This morning I needed to bring something to a mexican themed potluck, but just plain couldn't think of anything to bring and we had nothing to take. So God provided a can of Refried&nbsp;Beans, GOOD beans GOOD brand, I took them home and mixed them with onions, Lime, and Red Pepper Flakes. BIG Hit! God is good, even when you doubt... Just give him a shot... <br />&nbsp; <br />I'm going to go out on a limb and start asking for stuff... <br />&nbsp; <br />DW