---
title: 'Don’t Tell'
date: '2010-02-20T22:14:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3671213678566954975'
blogger_filename: '/2010/02/dont-tell.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p><a href='http://www.biblegateway.com/passage/?search=Mark%205-8&amp;version=NKJV'>Mark 5-8</a><br />			</p><p><br /> </p><p>There are many little things I noted as I went through these chapters. But the primary thing that has caught my attention is that there is a theme. Jesus, quite often, at least once per chapter has told people that just received a miracle NOT to say anything.  Yet their first inclination is to disobey Him and do it anyway. <br /></p><p>One time he finds someone who actually wants to follow Jesus and serve his ministry and THAT man gets told to GO AND TELL… <br /></p><p>A few interesting things have come to my attention. <br /></p><ul><li><div>Jesus NEVER LIED! If he said "DON'T TELL" and the bible actually says "Strictly warned them not to tell!" He MEANT IT! <br /></div><ul><li>It's not like Jesus is saying… don't tell anyone… then winks his eye knowing He really wants them to so that He will get good publicity. Jesus Meant what He said. <br /></li></ul></li><li>Jesus said DO NOT TELL more often than he ever said TO TELL. <br /></li><li>Jesus found it impossible to enter a city after someone disobeyed this order and ended up having to preach out of the wilderness, but not by choice. <br /></li><li>Jesus was not received in the Gaderenes but once the Man he told TO TELL got through with the people Jesus was able to start a revival on his second trip there. <br /></li></ul><p><br /> </p><p>Why? Why this over arching theme of DON'T TELL?<br /></p><p><a href='http://www.biblegateway.com/passage/?search=Matthew%206:%205-7,%2016&amp;version=NKJV'>Matthew 6:5-7, and 6:16</a><br />			</p><p><sup>6</sup> But you, when you pray, go into your room, and when you have shut your door, pray to your Father who <em>is</em> in the secret <em>place;</em> and your Father who sees in secret will reward you openly.<br /></p><p>So there is a principle of not flaunting even the most amazing powers of Healing and Demonstration of God just to get attention. <br /></p><p>Yet it is obvious that God has used miracles to gather people attention and to validate his Word. <br /></p><p><br /> </p><p>There is also this reference I cannot seem to find, but vaguely remember where Jesus tells the multitude that they are coming to him because he fed them physically but he really wanted them to be seeking the Kingdom of God not just it's provisions. <br /></p><p><br /> </p><p>Mark 4<br /></p><p><span style='font-family:Times New Roman; font-size:12pt'><sup>21</sup>He said to them, "Do you bring in a lamp to put it under a bowl or a bed? Instead, don't you put it on its stand? <sup>22</sup>For whatever is hidden is meant to be disclosed, and whatever is concealed is meant to be brought out into the open. <sup>23</sup>If anyone has ears to hear, let him hear." <br /></span></p><p><span style='font-family:Times New Roman; font-size:12pt'> <sup>24</sup>"Consider carefully what you hear," he continued. "With the measure you use, it will be measured to you—and even more. <sup>25</sup>Whoever has will be given more; whoever does not have, even what he has will be taken from him."<br /></span></p><p>Mark 5<br /></p><p><sup>19</sup>Jesus did not let him, but said, "Go home to your family and tell them how much the Lord has done for you, and how he has had mercy on you." <sup>20</sup>So the man went away and began to tell in the Decapolis<sup>[<a title='See footnote d' href='http://www.biblegateway.com/passage/?search=Mark%204-8&amp;version=NIV'>d</a>]</sup>how much Jesus had done for him. And all the people were amazed.<br /></p><p><sup>42</sup>Immediately the girl stood up and walked around (she was twelve years old). At this they were completely astonished. <sup>43</sup>He gave strict orders not to let anyone know about this, and told them to give her something to eat.<br /></p><p><br /> </p><p>Mark 7<br /></p><p> <sup>36</sup>Jesus commanded them not to tell anyone. But the more he did so, the more they kept talking about it. <sup>37</sup>People were overwhelmed with amazement. "He has done everything well," they said. "He even makes the deaf hear and the mute speak."<br /></p><p><br /> </p><p>MarK 8<br /></p><p><sup>27</sup>Jesus and his disciples went on to the villages around Caesarea Philippi. On the way he asked them, "Who do people say I am?" <br /></p><p> <sup>28</sup>They replied, "Some say John the Baptist; others say Elijah; and still others, one of the prophets." <br /></p><p> <sup>29</sup>"But what about you?" he asked. "Who do you say I am?" <br/>      Peter answered, "You are the Christ.<sup>[<a title='See footnote t' href='http://www.biblegateway.com/passage/?search=Mark%204-8&amp;version=NIV'>t</a>]</sup>" <br /></p><p> <sup>30</sup>Jesus warned them not to tell anyone about him.<br /></p><p><br /> </p><p><br /> </p><p>These are just the main examples I am pondering… it's almost a contradiction… but if I've learned anything about Jesus it is that He NEVER contradicts himself. Only the confused and confused.  In time I'll get the answer I'm looking for…<br /></p><p><br /> </p><p>I haven't satisfied the question in my heart…<br /></p><p>WHY NOT TELL?<br /></p><p>There are lot of good answers… but nothing that satisfies my curiosity yet. That's my predominant thought during these chapters so far… </p></span>