---
title: 'Christ-Mas Preperations'
date: '2010-12-12T20:06:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '874570199456730237'
blogger_filename: '/2010/12/christ-mas-preperations.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

EMIC Sunday Morning Service 12.12.10<br />Pastor Terri Pearsons<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; Preparing for Christmas. Why do we spend MORE time preparing for Christmas than any other holiday BY FAR? More, even, than the holiday dedicated to Christ's Resurrection? <br /><br />&nbsp;&nbsp;&nbsp;&nbsp; It is because Christmas is about the coming of Jesus... and He is coming again! Have you noticed that we are preparing for Christ's Mass?<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; Mass: (Gathering of similar things compound into a single form)<br /><br /><br />&nbsp;&nbsp;&nbsp;&nbsp; Jesus' first coming was the gathering and compounding of God and Man into a single form!<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; Jesus' second coming is the gathering and compounding of the "Body of Christ" and the Head into a single form!<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; The rapture(latin word), the gathering, the catching away is coming... as it get's closer we feel the intense pressure to prepare earlier and earlier...<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; Christmas items being posted in stores in July... are a sign!<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; The coming is coming. <br /><br /><br /><br /><br /><br /><br /><a href="http://www.google.com/search?hl=en&amp;client=firefox-a&amp;rls=org.mozilla%3Aen-US%3Aofficial&amp;q=define%3AMass&amp;btnG=Search">Definitions of <b>Mass</b> on the Web:</a><br /><ul class="std" type="disc"><li>the property of a body that causes it to have weight in a gravitational field  </li><li>batch:  (often followed by `of') a large number or amount or extent; "a batch  of letters"; "a deal of trouble"; "a lot of money"; "he made a mint on  the stock market"; "see the rest of the winners in our huge passel of  photos"; "it must have cost plenty"; "a slew of journalists"; "a wad of  money"  </li><li>an ill-structured collection of similar things (objects or people)  </li><li>(Roman Catholic Church and Protestant Churches) the celebration of the Eucharist  </li><li>a body of matter without definite shape; "a huge ice mass"  </li><li>multitude: the common people generally; "separate the warriors from the mass"; "power to the people"  </li><li>bulk:  the property of something that is great in magnitude; "it is cheaper to  buy it in bulk"; "he received a mass of correspondence"; "the volume of  exports"  </li><li>a musical setting for a Mass; "they played a Mass composed by Beethoven"  </li><li>join together into a mass or collect or form a mass; "Crowds were massing outside the palace"</li><li>a sequence of prayers constituting the Christian Eucharistic rite; "the priest said Mass"</li><li>aggregate:  formed of separate units gathered into a mass or whole; "aggregate  expenses include expenses of all divisions combined for the entire  year"; "the aggregated amount of indebtedness"<br /><a href="http://www.google.com/url?ei=0fUETdT9G5P9nAfG_cjlDQ&amp;sig2=2ZW6wrQD50xEhJC-VINXoQ&amp;q=http://wordnetweb.princeton.edu/perl/webwn%3Fs%3Dmass&amp;sa=X&amp;ved=0CBgQpAMoAA&amp;usg=AFQjCNHlTGMY-aZSYCtya1SXEa6KLVwnBA"><span style="color: green;">wordnetweb.princeton.edu/perl/webwn</span></a></li><li>In  physics, mass (from μᾶζα) commonly refers to any of three properties of  matter, which have been shown experimentally to be equivalent: inertial  mass, active gravitational mass and passive gravitational mass. ...<br /><a href="http://www.google.com/url?ei=0fUETdT9G5P9nAfG_cjlDQ&amp;sig2=DF9kdzaafeQV-AmY6QwrcQ&amp;q=http://en.wikipedia.org/wiki/Mass&amp;sa=X&amp;ved=0CBkQpAMoAQ&amp;usg=AFQjCNHE1PvxOAYlA0wK6cRBmxJDrDrzXQ"><span style="color: green;">en.wikipedia.org/wiki/Mass</span></a></li><li>The  ''''' ( and the Bavarian form of the female noun ', i. e. "mass",  though commonly misinterpreted as the neuter noun (with a long vowel)  '', translating to "measure") is a term used in German-speaking  countries for a unit of volume, now typically used for measuring beer.  ...<br /><a href="http://www.google.com/url?ei=0fUETdT9G5P9nAfG_cjlDQ&amp;sig2=KO2dZ_j5Psug4coEBexsTw&amp;q=http://en.wikipedia.org/wiki/Ma%C3%9F&amp;sa=X&amp;ved=0CBoQpAMoAg&amp;usg=AFQjCNElVaFCa3ospHl21jolI3OoIcr3Mg"><span style="color: green;">en.wikipedia.org/wiki/Maß</span></a></li><li>The  Commonwealth of Massachusetts is a state in the New England region of  the northeastern United States. It is bordered by Rhode Island and  Connecticut to the south, New York to the west, and Vermont and New  Hampshire to the north; at its east lies the Atlantic Ocean. ...<br /><a href="http://www.google.com/url?ei=0fUETdT9G5P9nAfG_cjlDQ&amp;sig2=JdIkeZczBj5cV5YX67VwVg&amp;q=http://en.wikipedia.org/wiki/Mass.&amp;sa=X&amp;ved=0CBsQpAMoAw&amp;usg=AFQjCNGrG7Ee-3vyQfrCgc7byl_xVM_NNw"><span style="color: green;">en.wikipedia.org/wiki/Mass.</span></a></li><li>Manab  Adhikar Sangram Samiti (MASS), (Assamese মানৱ অধিকাৰ সংগ্ৰাম সমিতি), is  a regional non-profit human rights NGO in Assam. It was founded in 1991  by Parag Kumar Das along with a group of intellectuals and journalists  of Assam. ...<br /><a href="http://www.google.com/url?ei=0fUETdT9G5P9nAfG_cjlDQ&amp;sig2=kZG8q6P-geVLpu1UHo6ZsQ&amp;q=http://en.wikipedia.org/wiki/MASS&amp;sa=X&amp;ved=0CBwQpAMoBA&amp;usg=AFQjCNEaEa_qckF3MYj9ntyN4OnDwQ558A"><span style="color: green;">en.wikipedia.org/wiki/MASS</span></a></li></ul>