---
title: 'NO CARES! HEAR...DO!'
date: '2010-03-16T03:35:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3909562223657669041'
blogger_filename: '/2010/03/no-cares-heardo.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

03/15/2010<br /><br />In prayer today:<br /><i><br /></i><br /><i>&nbsp;&nbsp;&nbsp;&nbsp; Never before has there been a generation with so many tools and resources and so little success. Value has been placed on learning more than doing. Ever learning but never able to come to the knowledge of the Truth.</i><br /><i><br /></i><br /><i>&nbsp;&nbsp;&nbsp;&nbsp; It's time to focus. Game Time. Stop seeking ways to get money in and start seeking ways to get the Word out! Promotion will come but it won't satisfy you unless you were already satisfied. Your team needs your anointing, start walking in it!&nbsp;</i><br /><i><br /></i><br /><i>&nbsp;&nbsp;&nbsp;&nbsp; Ever time you feel great financial pressure you stop. Pray thankfullness over what you have and thankfulness over the Promise and Blessing. Then Pray for the needs of others starting with Leaders, Partners, and Family.</i><br /><br /><br />&nbsp;&nbsp;&nbsp;&nbsp; See: <br /><br /><h4><a href="http://www.biblegateway.com/passage/?search=2%20Timothy%203&amp;version=NKJV">2 Timothy 3</a></h4><h4><i><sup class="versenum" id="en-NKJV-29851">1</sup> But know this, that in the last days perilous times will come... <sup class="versenum" id="en-NKJV-29857">7</sup> always learning and never able to come to the knowledge of the truth...<sup class="versenum" id="en-NKJV-29860">10</sup> But you have carefully followed my doctrine, manner of life, purpose, faith, longsuffering, love, perseverance, <sup class="versenum" id="en-NKJV-29861">11</sup> persecutions, afflictions, which happened to me at Antioch, at Iconium, at Lystra—what persecutions I endured. And out of </i><i>them all the Lord delivered me.&nbsp;</i></h4><h4><i>&nbsp;</i></h4><h4 style="font-weight: normal;">Todays Reading was from <a href="http://www.biblegateway.com/passage/?search=Luke%208:14,21&amp;version=NKJV"><b>Luke 8</b></a></h4><h4 style="font-weight: normal;"><i><sup class="versenum" id="en-NKJV-25256">14</sup> Now the ones </i><i>that fell among thorns are those who, when they have heard, go out and are <b>choked with cares</b>, riches, and pleasures of life, and bring no fruit to maturity.</i></h4><h4 style="font-weight: normal;"><i><sup class="versenum" id="en-NKJV-25263">21</sup> But He answered and said to them, “My mother and My brothers are these who <b>hear</b> the word of God and <b>do</b> it.”</i></h4><h4 style="font-weight: normal;"><i>&nbsp;</i>&nbsp; &nbsp;&nbsp; The&nbsp; primary reason for fruitlessness in the life of the believer is CARES... also verbalized as NEED.&nbsp;</h4><h4 style="font-weight: normal;"><i>"HOW are we going to do this? What are we going to do? Maybe if I do XYZ I could get a better handle on this... I know if I work these hours I'll get this pay... If I get this second job NOW I'll be making it..." </i></h4><h4 style="font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp; These kinds of thoughts and words are from a need based mindset and not a Word Based mindset. No plans that were not directions given to you by the Holy Spirit will prosper for long. What you compromise to get you will eventually loose. These types of words listed above are a RED FLAG that the CARES of this world and DECEIT of riches has entered in and are CHOKING the life out of you. </h4><h4 style="font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp; Jesus says the answer is DO... not DO another job or another plan... DO THE WORD... SPEAK THE WORD ONLY.&nbsp; Meditate on the Promises of God until they become more real on the inside of you than anything else.&nbsp;</h4><h4 style="font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp; DO NOTHING until you have a clear direction from the Holy Spirit. If you don't have that direction GET AWAY as long as it takes until you have it. Get quiet and remove yourself from everything that distracts you. Turn worship and praise music on. Thank Him for everything you can think of. Pray for a while until you get a sense and awareness of HIM. Not a "feeling" with your five physical senses, but a spiritual sense of His Presence. Then get into the word. Lastly get QUIET! Wait on Him means WAIT on HIM! Sit still long enough to get direction. You may have to get ONE direction or ONE DAY at a time until you can handle the rest...</h4><h4 style="font-weight: normal;"><br />What are my assignments today sir?</h4><h4 style="font-weight: normal;">Darrell G. Wolfe</h4><h4 style="font-weight: normal;"><br /></h4><h4 style="font-weight: normal;"><br /></h4><h4 style="font-weight: normal;"><br /></h4>