---
title: 'God&#39;s Perfect Will'
date: '2010-01-06T04:59:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '297832439089572868'
blogger_filename: '/2010/01/god-perfect-will.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

Monday 01/04/2010 <br /><br /><a href="http://www.biblegateway.com/passage/?search=Matthew%202&amp;version=NKJV">Mathew 2 </a><br /><br />Joseph and Mary took personal risks and sacrifices obeying God. They had to take a bad reputation from those who wouldn't understand. Joseph was given the care of a child that wasn't "His". Neither understood the FULL impact of what this would mean to them, which is evident in how amazed they were at his 8 day old presentation at the temple and all the words spoken over him by two prophets.<br /><br />Yet here they are... obeying God... walking in HIS perfect will for thier lives. As a result they received:<br /><ul><li><b>Provision</b></li><li><b>Protection</b></li><li><b>Direction</b></li><li><b>Foreknowledge</b></li></ul>MOST of us in the church world today walk around half blind until a problem comes&nbsp; up and then say:<br /><br />"Well... God...&nbsp; You know what is going on here... what do I do now?"<br /><br />At least we hope most of us are at least that spiritual. Many would repond:<br /><br />"OH GOD!... OH JESUS!... What am I going to do? Why did you let this happen?"<br /><br />But is there a better way of walking in God's will for 2010 then EITHER response? What if God brings the <b>Provision </b>FIRST... THEN the <b>Direction</b>... through these <b>Protection </b>and <b>Foreknowledge </b>and as a result <b>you were half way to Eygpt before catastrophe hit!</b><br /><br />That is my goal for 2010! Walk in God's will, so clearly that I am provided for, led by the Holy Spirit, and LONG GONE before the problem tries to come my way!<br /><br /><br />Here's to HIS perfect will for 2010!<br /><br />Darrell G. Wolfe