---
title: 'Fed by Ravens'
date: '2010-01-09T21:23:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5694356152140453420'
blogger_filename: '/2010/01/fed-by-ravens.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span style="font-size: small;"><b>Saturday 01/09/2009 </b></span><br /><span style="font-size: small;"><b><a href="http://www.biblegateway.com/passage/?search=I%20Kings%2017&amp;version=KJV">I Kings 17</a></b></span><br /><span style="font-size: small;"><b><br /></b></span><br /><span style="font-size: small;">Elijah boldly declares that it will not rain in the land except by HIS word... Elijah... buddy... you need to be humble here... you mean God's word right? That's not what it says. Now obviously he is a prophet and thus if he says it that would be because the Spirit of God is moving on him to say it. Nevertheless God shows time and again from Gen to Rev that he is not willing to work on the earth without a participant.</span><br /><span style="font-size: small;"><br /></span><br /><span style="font-size: small;">God is about to judge Sodom and Gomorrah for their sin. He then turns to Abraham first and tells him about it...</span><br /><span style="font-size: small;"><b><br /></b></span><br /><span style="font-size: small;"><b><a href="http://www.biblegateway.com/passage/?search=Genesis+18&amp;version=KJV">Genesis 18</a></b></span><br /><span style="font-size: small;">&nbsp;<i><sup class="versenum" id="en-KJV-442">17</sup>And the LORD said, Shall I hide from Abraham that thing which I do...</i></span><br /><span style="font-size: small;"><br /></span><br /><span style="font-size: small;">&nbsp;Abraham begins to dialogue with the Lord and plead the case of this city, mostly for his nephew Lot's sake. God is always looking for a man or woman of God to get involved in the worlds affairs.</span><br /><span style="font-size: small;"><b><br /></b></span><br /><span style="font-size: small;"><b><a href="http://www.biblegateway.com/passage/?search=Ezekiel+22:30&amp;version=NIV">Ezekiel 22:30</a></b></span><br /><span style="font-size: small;"><i>"I looked for a man among them who would build up the wall and stand before me in the gap on behalf of the land so I would not have to destroy it, but I found none.</i></span><br /><span style="font-size: small;"><br /></span><br /><span style="font-size: small;">So here is Elijah... getting fed by ravens night and day&nbsp; and watered by the brook. Getting his needs met supernaturally. Then the brook dries up... if your brook dries up... your provision has moved... it may be a sign you are not ONLY in the wrong place now... but that you are being called to meet someone ELSE'S need by your moving.</span><br /><span style="font-size: small;"><b><br /></b></span><br /><span style="font-size: small;">God isn't just about meeting YOUR needs. The idea people in the church world developed, "<i>I don't need much, just enough for me and my four... I want to live humble</i>.", is a bunch of bull dung. Babies cry about their own hunger, parents cry about the hunger of their children. If one claims to be spiritual,<b> <a href="http://www.biblegateway.com/passage/?search=James+1:27&amp;version=NIV">James 1:27</a> <span style="font-weight: normal;">says, </span><span style="color: black; font-weight: normal;">he should look after orphans and widows and keep himself from being polluted by the world. One of the main pollutants of the world is selfishness which this statement is saturated with.&nbsp;</span></b></span><br /><div style="color: black;"><span style="font-size: small;"><br /></span> <br /></div><div style="color: black;"><span style="font-size: small;"><b><span style="font-weight: normal;">SO...God calls Elijah to get up and go to Zarapheth, in Sidon,(which is NOT in Israel) and see a widow woman there. God has commanded this widow woman to provide for Elijah. WAIT... how do I look after widows and orphans if I'm having THEM meet my needs? The seed sown by this young woman of faith into Elijah because the catalyst for God to supernaturally provide for her, her son, and the prophet for years! Why did God bring Elijah over?&nbsp;</span></b></span><br /></div><div style="color: black;"><span style="font-size: small;"><br /></span> <br /></div><div style="color: black;"><span style="font-size: small; font-weight: normal;">This woman has NO covenant with God, she is NOT a Jew. She is a gentile heathen woman. But she demonstrates great faith. Faith always attracts God's attention. If God commanded her to provide for Elijah... how come she was preparing to eat and die? Because the word of Elijah IS her command from God. SHE can't hear it if HE doesn't say it. Again... no covenant of her own. She isn't full of the Holy Spirit. She can't be. Jesus hasn't come to redeem the gentiles. They can only be under the blessing if they attach themselves to the blessed.</span><br /></div><div style="color: black;"><span style="font-size: small;"><br /></span> <br /></div><div style="color: black;"><span style="font-size: small; font-weight: normal;">Your Provision is about OTHERS! Believing God for new car? Believe him to TEN so that you can give 8 or 9 away! That is the Blessing Mentality... THAT is God's way... THAT is the Kingdom of God!</span><br /></div><div style="color: black;"><span style="font-size: small; font-weight: normal;"><br /></span><br /></div><span style="color: black; font-size: small; font-weight: normal;">BE Blessed... Darrell G. Wolfe</span><span style="font-weight: normal;"><br /></span><br /><br /><span style="font-weight: normal;">&nbsp;</span><b><br /></b>