---
title: 'Sun and Moon'
date: '2010-01-18T05:32:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7284845473905544246'
blogger_filename: '/2010/01/sun-and-moon.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p>    Thought to ponder…<br /></p><p><br /> </p><p>Just as the moon cycles from full and bright, then fades to black and begins to come back to light until it shines brightest…<br /></p><p>The Bible says that the "Sun of Righteousness arise with healing in His wings…" We know the Sun if Jesus…<br /></p><p>The Moon reflects the light of the Sun…<br /></p><p>The Moon is the Church…<br /></p><p>The Church was BRIGHT for nearly 300 years… it faded over time… so much so that even the World's History books calls that period where the Word was locked away from men: "The Dark Ages."<br /></p><p>Then a man named Martin Luther reminded us that it is by Faith NOT Works…<br /></p><p>Smith Wigglesworth and John Lake showed us that God still heals… abundantly and always… responding to faith…<br /></p><p>Other's came…<br /></p><p>Kenneth Copeland taught and teaches us… to live by Faith and not by sight…<br /></p><p>The Church is getting brighter… the World is getting darker… <br /></p><p>The Bible said both would happen…<br /></p><p>The World is getting darker… 2010 will have many dark moments for the world… Haiti is only the start…<br /></p><p>Are you participating in the Brightening of the Church? Or are you still on the dark side of the moon?<br /></p><p>Jump in to 2010… Jump in the flow of the Spirit of God!<br /></p><p>Come along with me… Let's impact a world with the Light of the Word…<br /></p><p><a href='http://www.biblegateway.com/passage/?search=Psalm+119:105&amp;version=KJV'><strong>Psalm 119:105</strong></a><br/><strong>Thy word is a lamp unto my feet, and a light unto my path.<br /></strong></p><p>Get in the Word of God DAILY… Let the Light wash away the darkness!<br /></p><p><br /> </p><p>Darrell G. Wolfe</p></span>