---
title: 'Untitled Post'
date: '2010-03-23T04:26:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4431667321025431789'
blogger_filename: '/2010/03/luke-13-18-then-he-said-what-is-kingdom.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=Luke%2013&amp;version=NKJV">Luke 13</a><br /><br /><i><sup class="versenum" id="en-NKJV-25533">18</sup> Then He said, “What is the kingdom of God like? And to what shall I compare it? <sup class="versenum" id="en-NKJV-25534">19</sup> It is like a mustard seed, which a man took and put in his garden; and it grew and became a large<sup class="footnote" value="[&lt;a href=&quot;#fen-NKJV-25534c&quot; title=&quot;See footnote c&quot;&gt;c&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=Luke%2013&amp;version=NKJV#fen-NKJV-25534c" title="See footnote c">c</a>]</sup> tree, and<b> the birds of the air nested in its branches</b>.”</i><br /><br /><i><sup class="versenum" id="en-NKJV-25535">20</sup> And again He said, “To what shall I liken the kingdom of God? <sup class="versenum" id="en-NKJV-25536">21</sup> It is like leaven, which a woman took and hid in <b>three measures</b><sup class="footnote" value="[&lt;a href=&quot;#fen-NKJV-25536d&quot; title=&quot;See footnote d&quot;&gt;d&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=Luke%2013&amp;version=NKJV#fen-NKJV-25536d" title="See footnote d">d</a>]</sup> of meal till it was all leavened.”</i><i></i><br /><i><sup class="versenum" id="en-NKJV-25548">33</sup> Nevertheless I must journey <b>today</b>, <b>tomorrow</b>, and the <b>day following</b>; for it cannot be that a prophet should perish outside of Jerusalem.</i> <br /><br />&nbsp;&nbsp;&nbsp;&nbsp; <br /><br />&nbsp;&nbsp;&nbsp;&nbsp; The birds of the air nest in the branches of the tree started by the seed. The Kingdom of God is currently in the hands of the Church. The Church is the Tree of Life for the world in this age and time. The individual in the Kingdom of God is equally required to grow his branch to become a nest for the birds, which are the people of the world seeking refuge.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; The people of the world are seeking ways to get thier needs met. They are turning to a broken financial system, a broken medical and health system, a broken security system, and everything else in this worlds system is broken too. The Church has always and will always have the best answers and best care for people. When the Church isn't doing her part than the world hurts. They turn to "Social Security" which has people too broke to be social and anything but secure. Government homeless programs spend more time filling papers than helping people. They finance poverty and create systems that keep people dependant on the system instead of providing the capacity to become a contributor instead of a taker.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; Unless you run a Church or Program or have the capacity too right now there isn't much you can do about that. However I can do something. I can take steps in my life to make sure that what I do is providing for others. Each of us will do something different, because our callings are unique. I don't have the resources to start a homeless program, yet, but I can write. I will do that here on my personal web journal and on my finance site.<br /><br /><b>&nbsp;&nbsp;&nbsp;&nbsp; Do not seek ways to get money in... seek ways to get the Word out!</b><br /><b><br /></b><br />&nbsp;&nbsp;&nbsp;&nbsp; From there? Who knows for sure. I will dedicate the rest of my life to creating things that supply the needs of others: Spiritually, Physically, Financially. It starts with staying on course for the two projects I have. Then finish others projects I set aside. Restaurants and libraries and other projects that WE have in our hearts to do will create jobs and fruitfulness for others too. <br /><br />&nbsp;Darrell G. Wolfe<br /><br />Side Note: Three Measures and Three Days... Working the leaven into the dough. Jesus worked the Kingdom of God into the towns as He went on his way to his last moments before the cross. The Kingdom of God works like that. We create leaven and leave behind us a wake. The results will be the fruit of our work. I must be diligent to leave good fruit.&nbsp; <br /><br /><br /><br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <i><br /></i>