---
title: 'The Great Kingdom Key'
date: '2010-01-26T19:44:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6339265612644152376'
blogger_filename: '/2010/01/the-great-kingdom-key.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

01/26/2010<br /><br />Matthew 18<br /><br /><br />God is seeking in this chapter to bring us all into the Unity of Christ. Pride cannot stand in God's presence. Humility can. Unforgiveness cannot stand in God's presence. The Forgiven forgiver can. Sin cannot stand in God's Presence. Either get it repented of or remove that person from the unit. For the Unity of the Unit is of the utmost importance. Can't we love them back? We tried that by confronting the sin. If it isn't repented of, remove them like cancer from the body. UNITY of the UNIT is primary. Within any organization, marriage, partnership, friendship, Business, etc... UNITY is Key to overcoming victories. <br /><br /><br />Only in Unity can we Bind and Loose and get results from Prayer! <br /><br />Are they ANY places that you are not in TOTAL harmony with those you are attached to. Find anything you can on your part, through prayer to make sure you stay in Unity. <br /><br />Darrell Wolfe