---
title: 'PRAYER… HIGHEST VALUE!'
date: '2010-03-16T18:56:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3522036241875336313'
blogger_filename: '/2010/03/prayer-highest-value.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p><a href='http://www.biblegateway.com/passage/?search=Luke%209&amp;version=NKJV'>Luke 9</a><br />			</p><p>There are several interesting things I've seen today. <br /></p><ul style='margin-left: 38pt'><li><div>Jesus sends his disciples out with no stuff and no money and God supernaturally provides. Then faced with a need that exceeded their experiences they reverted back to relying on Money. "How would we pay for it Jesus? This crowd is too big… we can't afford it…" This is the mindset of the person who has not yet learned to change from God as provider from Money as provider. ANYTIME you find yourself considering the cost of something as a factor in being able to do it… you have a red flag that MONEY not God is the provider or determining factor in your life. <br /></div><ul><li>BUT Darrell… The bible says to count the cost right? Yes. It is so that you can plan, write the vision and make it plain, and most importantly be specific about what you are believing for. NOT so that you can decide IF your going to do it. <br /></li></ul></li><li>Jesus, after a big day full of events… Goes to be alone and pray!<br /></li><li><div>Jesus goes to a mountain to pray, and AS HE WAS PRAYING the Glory came. <br /></div><ul><li>The Glory is reserved for those who seek God in Prayer.<br /></li><li>I always wondered what Jesus would be talking with Moses and Elijah about. Like, "Hey there, how's the last few years in heaven been? Perfect… yeah I know… See ya'll in a few days." Ha Ha. What did they talk about? Mystery solved… it was in the bible the whole time. They talked about his upcoming death that He was about to ACCOMPLISH. It's an odd thing to ACCOMPLISH death. But that is why He came. He came that WE might have LIFE! To do that HE had to be US in death!<br /></li></ul></li></ul><p><br /> </p><p>I MUST remember… PRAYER is the best thing I can do. Not writing, art, music, banking, promotions… PRAYER… <br /></p><p><br /> </p><p>PRAYER is the most valuable asset I have. It's time I started treating it that way! How much money do people pay for great concert tickets for an entertaining "Super-Star". SO MUCH MORE… should I give what I have to spend time in audience with THE KING in a one on one. THE ruler of the universe DESERVES MY attention, DESIRES MY attention! And He shall have it!<br /></p><p><br /> </p><p>Darrell G. Wolfe<br /></p></span>