---
title: 'ONE PARABLE....'
date: '2010-03-16T04:07:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8121066490867147449'
blogger_filename: '/2010/03/one-parable.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<h4><a href="http://www.biblegateway.com/passage/?search=Luke%208:11-18&amp;version=NKJV">Luke 8</a> </h4><h4 style="font-weight: normal;"><sup class="versenum" id="en-NKJV-25253">11</sup> “Now the parable is this: The seed is the word of God. <sup class="versenum" id="en-NKJV-25254">12</sup> Those by the wayside are the ones who hear; <b>then the devil comes and takes away the word</b> out of their hearts, lest they should believe and be saved. <sup class="versenum" id="en-NKJV-25255">13</sup> But the ones on the rock <i>are those</i> who, when they hear, receive the word with joy; and these have no root, who believe for a while and in time of temptation fall away. <sup class="versenum" id="en-NKJV-25256">14</sup> Now the ones <i>that</i> fell among thorns are those who, when they have heard, go out and are choked with cares, riches, and pleasures of life, and bring no fruit to maturity. <sup class="versenum" id="en-NKJV-25257">15</sup> But the ones <i>that</i> fell on the good ground are those who, having heard the word with a noble and good heart, keep <i>it</i> and bear fruit with patience.&nbsp;&nbsp; <sup class="versenum" id="en-NKJV-25258">16</sup> “No one, when he has lit a lamp, covers it with a vessel or puts <i>it</i> under a bed, but sets <i>it</i> on a lampstand, that those who enter may see the light. <sup class="versenum" id="en-NKJV-25259">17</sup> For nothing is secret that will not be revealed, nor <i>anything</i> hidden that will not be known and come to light. <sup class="versenum" id="en-NKJV-25260">18</sup> Therefore take heed how you hear. For whoever has, to him <i>more</i> will be given; and <b>whoever does not have, even what he seems to have will be taken from him.”</b></h4><h4>&nbsp;&nbsp;&nbsp;&nbsp; This is all ONE parable. Who doesn't have the Word? He who doesn't have GOOD soil so that he can have a rooting take place? He thinks he has the Word... but the soil being a hard path, rocky or full of thorns is choking out the Word and it's being taken from him. Who is responsible for the soil? The one who the soil belongs to.</h4><h4>&nbsp;&nbsp;&nbsp;&nbsp; LIGHT=WORD</h4><h4>&nbsp;&nbsp;&nbsp;&nbsp; Who lights the Word into a heart and then puts it under the bed? The one who refuses to till their own soil. The one who allows the Cares to CHOKE the light out. What is revealed? The four soils all look the same from the outside. You are talking to a group of people about the Word and there are all four types of soils present. All of them are smiling and all of them are saying AMEN! But as they walk out... live life and come back... the SOIL TYPE becomes REVEALED in their life. </h4><h4>Darrell AND Flavia Wolfe</h4>