---
title: 'Jesus&#39; M.O.'
date: '2010-01-06T22:45:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2344153205225301072'
blogger_filename: '/2010/01/jesus-mo.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

Jan, 6th , 2010<br /><br />Mathew 4<br /><br />Jesus' M.O. <a href="http://en.wikipedia.org/wiki/Modus_operandi">Modus Operandi</a>, or His Method Operation:<br /><br /><ul><li>What stands out to me while reading this chapter in Mathew 4. The chapter starts with a dialogue between Satan and Jesus. Satan asks "IF" to&nbsp;cause doubt, and Jesus replies "IT IS!" to remove all&nbsp;doubt. This should show us that the Word of God is our FIRST place and FINAL authority. Any question ever asked should lead to "What does the Word say? It says: XYZ! Therefore that is settled." </li></ul>So in looking at the begining of Jesus' Ministry I see an interesting pattern develope. <br /><ul><li>I see first of all Jesus begins his ministry with a move. He moves from his home in Nazareth, to a new house in Capernum. I believe he actually moved out of Mary's home and away from his half brothers and sisters for the simple reason that he knew his life was about to get busy and chaotic at times, and He didn't want to subject them to that. He also needed to make a clean break from Jesus Mary's son to Jesus the Prophet. He says elsewhere that&nbsp;a prophet is not accepted in his own home town, and when Mary and his half brothers and sister&nbsp;came to get his attention he drew a line saying that ANYONE who does the will of the Father was his mother and brother and sister. So we can learn from this that sometimes you need to make a clean break from who you were to who you are, even if who you were was a good thing. New Seasons can require new mindsets.</li><li>Then Jesus Message is: "Repent, for the Kingdom of Heaven is at Hand." This was a consistent message, he never altered and never changed. You see him tell his disciples when sending them out to do the same thing. </li><li>Jesus' Offer: Follow Me... and I will make you fishers of men! It is still true today. You cannot follow Jesus without a burning desire developing on the inside of you to reach others with His Truth. You can follow religion and stay by yourself, but you cannot follow Jesus without a growing and burning desire to reach others. </li><li>Jesus M.O.:</li><ul><li>Went- No standing still, you cannot sit in the church waiting for them to come to you. You MUST go out among the people and reach them. TV is a great and even nessasary outreach, but it doesn't cut it alone, you MUST be out among them. </li><li>Taught in the Church- Services are important, having a regular meeting place is important. You must feed you fish once you've caught them. </li><li>Preached a consistent message: The Gospel of the Kingdom. All Holy Spirit inspired sermons fall under this catagory. Anything that doesn't is probably just readers digest. </li><li>Healed ALL Kinds- He Demonstrated the Authority AND Power of this Kingdom He was speaking about. He expected his Fishers-of-men to do the same!</li></ul><li>This resulted in MANY coming to Him and recieving from&nbsp;Him. </li></ul>My ministry must pattern after His:<br /><ul><li>Go Among the People</li><li>Teach them the Word</li><li>Be Consistent in my message</li><li>Demonstrate His LOVE, Authority, and Power! </li></ul>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Good Thoughts for all believers, <br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Be Blessed! Darrell G. Wolfe