---
title: 'Love MORE?'
date: '2010-03-15T02:00:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '826492961816207620'
blogger_filename: '/2010/03/love-more.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=Luke%207&amp;version=NKJV">Luke 7</a><br /><i><br /></i><br /><i><sup class="versenum" id="en-NKJV-25233">41</sup> “There was a certain creditor who had two debtors. One owed five hundred denarii, and the other fifty. <sup class="versenum" id="en-NKJV-25234">42</sup> And when they had nothing with which to repay, he freely forgave them both. Tell Me, therefore, which of them will love him more?” <br \="" /><sup class="versenum" id="en-NKJV-25235">43</sup> Simon answered and said, “I suppose the </i> <i>one whom he forgave more.”    <br \="" />And He said to him, “You have rightly judged.”</i><br /><br />&nbsp;&nbsp;&nbsp;&nbsp; There is no person that needs MORE forgiveness. ALL have fallen short of the GLORY standard. However, there are those who are more aware of their shortcomings and sins and more aware of their need for the saviour. Those "Love more" because they perceive the extent of their need. What I must learn here, is that as long as I feel like saying: "At least I'm not THAT guy!" I have missed the point entirely.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; The only difference between THAT GUY and ME is:<br /><ol><li><i>The Blood of Jesus</i></li><li><i>My knowledge of the The Blood of Jesus</i></li><li><i>My Acting on The Blood of Jesus</i></li></ol>&nbsp;&nbsp;&nbsp;&nbsp; As I remember that I will be more likely to want to jump to a person's aide rather than jump on a persons back!<br /><i><br /></i><br /><i>Darrell G. Wolfe</i>