---
title: 'Broken by The Rock'
date: '2010-03-31T18:30:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5277179221600099559'
blogger_filename: '/2010/03/broken-by-rock.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=Luke%2020&amp;version=NKJV">Luke 20</a><br /><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><sup class="versenum" id="en-NKJV-25793" style="font-size: 0.65em; line-height: normal; vertical-align: text-top;"><i>7</i></sup><i>&nbsp;Then He looked at them and said, “What then is this that is written:&nbsp;<br \="" />&nbsp;&nbsp; &nbsp; &nbsp;‘ The stone which the builders rejected<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Has become the chief cornerstone’?</i><sup class="footnote" style="font-size: 0.75em; line-height: 0.5em;" value="[&lt;a href=&quot;#fen-NKJV-25793b&quot; title=&quot;See footnote b&quot;&gt;b&lt;/a&gt;]"><i>[</i><a href="http://www.blogger.com/post-create.g?blogID=6583916183087899714#fen-NKJV-25793b" title="See footnote b"><i>b</i></a><i>]</i></sup><i><br \="" /></i></span><br /><i>&nbsp;</i><sup class="versenum" id="en-NKJV-25794" style="font-size: 0.65em; line-height: normal; vertical-align: text-top;"><i>1<b>8</b></i></sup><i><b>&nbsp;Whoever falls on that stone will be broken; but on whomever it falls, it will grind him to powder.”</b></i><sup class="versenum" id="en-NKJV-25795" style="font-size: 0.65em; line-height: normal; vertical-align: text-top;"><i>19</i></sup><i>&nbsp;And the chief priests and the scribes that very hour sought to lay hands on Him, but they feared the people</i><sup class="footnote" style="font-size: 0.75em; line-height: 0.5em;" value="[&lt;a href=&quot;#fen-NKJV-25795c&quot; title=&quot;See footnote c&quot;&gt;c&lt;/a&gt;]"><i>[</i><a href="http://www.blogger.com/post-create.g?blogID=6583916183087899714#fen-NKJV-25795c" title="See footnote c"><i>c</i></a><i>]</i></sup><i>—for they knew He had spoken this parable against them.</i><br /><i><br /></i><br />There will be a day that you will either choose to fall on The Rock, or you will ignore him and The Rock will fall on you. This is true ultimately to judgement after this life and age is over. However this is also true in areas and arenas of your life. Judge yourself and you will not be judged.<br /><i><br /></i><br /><span class="Apple-style-span" style="font-family: Verdana, Arial, Helvetica, sans-serif;"></span><br /><h2 id="passage_heading" style="font-size: 16px; font-weight: bold;"><i>1 Corinthians 11:31&nbsp;(Amplified Bible)</i></h2><div class="result-text-style-normal" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><sup class="versenum" id="en-AMP-28630" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;"><i>31</i></sup><i>For if we searchingly examined ourselves [detecting our shortcomings and recognizing our own condition], we should not be judged and penalty decreed [by the divine judgment].</i><br /><i><br /></i><br />The Rock will break you. If you throw yourself on the Grace and Mercy of The Rock He will remove from you whatever needs to be removed to take you to the next level of His Plan for you. If you sense that you ought to be beyond where you are in life or in His plan... something is there holding you back. Something you may not understand. Nevertheless, if a child jumps into a fire he will be burned, despite not&nbsp;understanding&nbsp;it. Therefore it is very important to continually, daily, throw ourselves upon The Rock so that He may break us of the things that bind us and hold us back.<br /><br />If you press on without letting Him Correct, Rebuke, and Discipline you than you will find The Rock crush you instead. The Rock was not meant to crush but to be fell upon.<br /><br />Broken is Good... Broken = Whole<br /><br />Unbroken is Incomplete and empty<br /><br />Darrell G. Wolfe</div>