---
title: 'Untitled Post'
date: '2010-03-18T18:57:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8278501426752746496'
blogger_filename: '/2010/03/luke-11-9-so-i-say-to-you-ask-and-it.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=Luke%2011&amp;version=NKJV">Luke 11</a><br /><br />&nbsp;&nbsp; <br \="" /> <i><sup class="versenum" id="en-NKJV-25411">9</sup> “So I say to you, ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you. <sup class="versenum" id="en-NKJV-25412">10</sup> <b>For <u>EVERYONE</u> who asks receives, and he who seeks finds, and to him who knocks it will be opened. </b><sup class="versenum" id="en-NKJV-25413">11</sup> If a son asks for bread<sup class="footnote" value="[&lt;a href=&quot;#fen-NKJV-25413d&quot; title=&quot;See footnote d&quot;&gt;d&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=Luke%2011&amp;version=NKJV#fen-NKJV-25413d" title="See footnote d">d</a>]</sup> from any father among you, will he give him a stone? Or if </i><i>he asks for a fish, will he give him a serpent instead of a fish? <sup class="versenum" id="en-NKJV-25414">12</sup> Or if he asks for an egg, will he offer him a scorpion? <sup class="versenum" id="en-NKJV-25415">13</sup> If you then, being evil, know how to give good gifts to your children, how much more will </i><i>your heavenly Father give the Holy Spirit to those who ask Him!”</i><br /><i>&nbsp;&nbsp; <br \="" /><sup class="versenum" id="en-NKJV-25435">33</sup> “No one, when he has lit a lamp, puts </i> <i>it in a secret place or under a basket, but on a lampstand, that those who come in may see the light. <sup class="versenum" id="en-NKJV-25436">34</sup> The lamp of the body is the eye. Therefore, when your eye is good, your whole body also is full of light. But when </i><i>your eye is bad, your body also </i><i>is full of darkness. <b><sup class="versenum" id="en-NKJV-25437">35</sup> Therefore take heed that the light which is in you is not darkness.</b> <sup class="versenum" id="en-NKJV-25438">36</sup> If then your whole body </i><i>is full of light, <b>having no part dark</b>, </i><i>the whole </i><i>body will be full of light, as when the bright shining of a lamp gives you light.”</i><br /><br />&nbsp;&nbsp;&nbsp;&nbsp; I stand again seeing how I've been ever hearing but not perceiving. Pastor Terri told a story about when she first met Pastor George in college. One comment she made was how easily he accepted the Word. If it was pointed out to him that the Word of God said something he would examine it to find out if it's true. Once he saw it he would reply:<br /><br /><b>"Well, that's the what the word says. Therefore it's true. How do I need to change because of that?"&nbsp;</b><i> </i><br /><br />&nbsp;&nbsp;&nbsp;&nbsp; I don't know how many times I've read that HE GIVES... He loved the world so much that HE GAVE... EVERYONE who asks receives. So why aren't more receiving? James tells us that it's because we ask amiss. This means we ask incorrectly and with wrong motive. But right here in the same chapter is another layer on that truth.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; TAKE HEED that the light in you is not darkness, not even a part of dark. What does this mean? There is a lot of layers on this. The part speaking to me is simply this: EVERYTHING God speaks to you IS HIS WORD. His Word is Light. Therefore if you have chosen to ignore ANY part of His Word you have darkened yourself in part.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If He told you to work on something and you've been delaying, you are part dark. If He told you to stop that habbit, however trivial it seems, and you have put off dealing with that, you are part dark. If He told you ANYTHING or gave you an inner witness toward a change you need and you have not dealt with that directly and head on, than part of you is dark. Sometimes we put off the feeling or sense that it's HIM dealing with us about something so that we don't have to face it. That is ingoring His light and you will be part dark.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; This part darkness will create in you a double mind about things. You want XYZ... dr pepper... whatever, but HE told you to deal with that habbit, than you are part dark ifyou have failed to deal with that.<br /><br />Always deal with His witness and Word Directly and Immediately. It's not too late. Repent, move on, and deal with it now. <br /><br /><br />Darrell G. Wolfe <br /><br /><br /><br /><br />&nbsp; &nbsp; &nbsp;&nbsp; <i><br /></i>