---
title: 'Pressing Past!'
date: '2010-03-29T15:50:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1936602120780157470'
blogger_filename: '/2010/03/pressing-past.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=Luke%2018&amp;version=NIV">Luke 18</a><br /><i><br /></i><br /><i><sup class="versenum" id="en-NIV-25681">1</sup>Then Jesus told his disciples a parable to show them that they should always pray and not give up.</i><br /><br /><br />In this chapter Jesus is telling me that there are factors to prayer I have not participated in. As the woman had press past the judge and the blind man had to press past the people around him so must I press past the things that attempt to silence my desire and prayer.<br /><br /><i><br /></i><br /><i><sup class="versenum" id="en-NIV-25687">7</sup>And will not God bring about justice for his chosen ones, who cry out to him day and night? Will he keep putting them off? <sup class="versenum" id="en-NIV-25688">8</sup>I tell you, he will see that they get justice, and quickly. However, when the Son of Man comes, will he find faith on the earth?"</i> <br /><i><br /></i><br /><i><sup class="versenum" id="en-NIV-25722">42</sup>Jesus said to him, "Receive your sight; your faith has healed you." <sup class="versenum" id="en-NIV-25723">43</sup>Immediately he received his sight and followed Jesus, praising God. When all the people saw it, they also praised God.</i><br /><br />There are things in life that are calling for my attention. Some of them are strictly unpure. But many of them are seemingly just. Finances, work, and the pressing desire to move forward. I've allowed my own fears, past mistakes, and past misunderstandings to hinder my prayer life. If you cannot trust God and Believe He WILL answer, than your prayer is just noise. "God might, if He sees it fits into his will... blah... blah... blah" is NOT faith! It's fear based praying based on past failure. If you don't know what the will of God is, than you need to go to His word, find out the will of God and then pray it. "If it's your will..." is very rarely a faith based prayer.<br /><br /><br />&nbsp;&nbsp;&nbsp;&nbsp; I must regain a time in my life where I followed God unashamed and unhindered by past. Today is new... today begins again.<br /><br /><br />Darrell G. Wolfe