---
title: '100th Post!'
date: '2010-09-09T03:39:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6338629397064321044'
blogger_filename: '/2010/09/100th-post.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

100!<br /><br />Is 100 some kind of starters milestone? This is now my 100th post on this blog. I have several blogs, but this is my primary one. On this URL alone I've posted 99 blogs. Many were from daily reading and a few from studies. I've gone to studying topics separate from posting daily reading. Then I stopped posting altogether, or I would have hit 100 long before.&nbsp; <br /><br />Tonight, Pastor George spoke about prosperity. The purpose, and reason for it. He spoke about how the rich young ruler came to Jesus, and Jesus tried to free him from having Money Master him. He loved money instead of loving God. If money had been his servant rather than his master, Jesus would have taken him on, most likely as Judas replacement, and shown him that anything you give for Jesus comes back to you 100 fold again and again. You can't out give God!<br /><br />What does this mean to me... what am I going to do to take my money relations in God to the next level. We already started by having a separate account JUST for giving. We have the tithe auto separated through payroll deduction into that account, plus a little extra for seed. Now what? I want to start giving goals. I want to decide to set my faith towards doing some specific things for people. Examples could be:<br /><ul><li>Paying for a months groceries for someone (And actually doing their shopping for them!)</li><li>Paying someones rent/mortgage payment</li><li>Paying off/buying a car for someone</li><li>Paying off/buying a house for someone</li><li>Buying/Paying for someone to start or take over a business!</li><li>Give $1,000 to the work of God</li><li>Give $10,000, $100,000, $1,000,000 to ministry work in one offering!&nbsp;</li><li>Etc Etc... Start with a goal and work toward that.&nbsp;</li></ul>If I set my faith toward giving specifically, I believe that God will multiply my seed even faster than He is now, and that He will assist me supernaturally to see these things come to pass!<br /><br />I expect the hard part will be, stopping and remembering when any money comes into my hand to ASK God what the purpose of that money is. "Lord, is this for me? For My bills/needs/wants... etc? For my giving and giving goals? Does this belong to someone else? What would YOU have me do with this?" If I will remember that I will be on the right track to giving. This is what tonight did for me.<br /><br />DW