---
title: 'Untitled Post'
date: '2010-06-14T04:43:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3813256458333285403'
blogger_filename: '/2010/06/acts-20-22-acts-20-22-and-see-now-i-go.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span style="font-size: large;"><b>Acts 20-22 </b></span><br /><br /><span id="goog_991957920"></span><span id="goog_991957921"></span><a href="http://www.blogger.com/"></a><br /><b><a href="http://www.biblegateway.com/passage/?search=Acts+20&amp;version=NKJV">Acts 20</a></b><br /><br /><sup class="versenum" id="en-NKJV-27645">22</sup> And see, now<b> I go bound in  the spirit to Jerusalem</b>, not knowing the things that will happen to me  there, <sup class="versenum" id="en-NKJV-27646">23</sup> except that the  <b>Holy Spirit testifies in every city, saying that chains and  tribulations await me</b>. <sup class="versenum" id="en-NKJV-27647">24</sup>  But none of these things move me; nor do I count my life dear to  myself,<sup class="footnote" value="[&lt;a  href=&quot;#fen-NKJV-27647b&quot; title=&quot;See footnote  b&quot;&gt;b&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=Acts+20&amp;version=NKJV#fen-NKJV-27647b" title="See footnote b">b</a>]</sup> so that I may finish my race with  joy, and the ministry which I received from the Lord Jesus, to testify  to the gospel of the grace of God.    <sup class="versenum" id="en-NKJV-27648">25</sup> “And indeed, now I know that you all, among  whom I have gone preaching the kingdom of God, will see my face no more.  <sup class="versenum" id="en-NKJV-27649">26</sup> Therefore I testify  to you this day that I <i>am</i> innocent of the blood of all <i>men.</i>  <sup class="versenum" id="en-NKJV-27650">27</sup> For I have not  shunned to declare to you the whole counsel of God.<br /><br /><h4><a href="http://www.biblegateway.com/passage/?search=Acts%2020-22&amp;version=KJV">Acts 21</a></h4><h4></h4><h4><sup class="versenum" id="en-NIV-27656">4</sup>Finding the disciples there, we stayed with them seven days. Through the Spirit they urged Paul not to go on to Jerusalem.&nbsp;&nbsp;</h4><h4></h4>&nbsp;<sup class="versenum" id="en-NIV-27662">10</sup>After we had been there a number of days, a prophet named Agabus came down from Judea. <b><sup class="versenum" id="en-NIV-27663">11</sup>Coming over to us, he took Paul's belt, tied his own hands and feet with it and said, "The Holy Spirit says, 'In this way the Jews of Jerusalem will bind the owner of this belt and will hand him over to the Gentiles.' " </b><br />&nbsp;<sup class="versenum" id="en-NIV-27664">12</sup>When we heard this, we and the people there pleaded with Paul not to go up to Jerusalem. <sup class="versenum" id="en-NIV-27665">13</sup>Then Paul answered, "Why are you weeping and breaking my heart? I am ready not only to be bound, but also to die in Jerusalem for the name of the Lord Jesus." <sup class="versenum" id="en-NIV-27666">14</sup>When he would not be dissuaded, we gave up and said, "The Lord's will be done."<br /><br /><b><a href="http://www.biblegateway.com/passage/?search=Acts%2020-22&amp;version=KJV">Acts 22</a></b><br /><br />&nbsp;<sup class="versenum" id="en-NIV-27713">21</sup>"Then the Lord said to  me,<b> 'Go; I will send you far away to the Gentiles.' "</b><br /><br /><h2 id="passage_heading"><span style="font-size: small;"><a href="http://www.biblegateway.com/passage/?search=Galatians+2:8&amp;version=NKJV">Galatians 2:8</a></span></h2><sup class="versenum" id="en-NKJV-29086">8</sup> (for He who worked  effectively in Peter for the apostleship to the circumcised also worked  effectively in me toward the Gentiles),<br /><br /><br /><b>It's been on my mind all week reading through Paul's journey. The Scripture is an accurate record of all that happened. But just because the bible says something doesn't mean it's God's will.&nbsp;</b><br /><br /><b>For example: A woman contemplating leaving her husband to have an affair once made her decision as she was "Praying" about it and she came upon the verse that says "Put on the new man" SO she did! That is not accurately dividing the word of Truth.&nbsp;</b><br /><b><br /></b><br /><b>So I come to Paul. ONLY Jesus was perfect but in today's church we don't like to admit that Paul could have made any mistakes. We've somehow made Paul into Jesus and lost much of what he could teach us. It is these groups of thoughts that I'm pondering as I see what could be viewed as a confused Holy Spirit.&nbsp;</b><br /><b><br /></b><br /><ul><li><b><i>I go bound in  the spirit</i> to Jerusalem</b></li></ul><ul><li><b>&nbsp;</b><b>Holy Spirit testifies in every city, saying that chains and   tribulations await me</b></li></ul><ul><li><b>&nbsp;<i>Through the Spirit they urged Paul not to go</i> on to Jerusalem.&nbsp; </b><b>&nbsp;</b></li></ul><ul><li><b>Coming over to us, he  took Paul's belt, tied his own hands and feet with it and said, "The  Holy Spirit says, 'In this way the Jews of Jerusalem will bind the owner  of this belt and will hand him over to the Gentiles.' "&nbsp;</b></li></ul><b>So wait a minute. The Holy Spirit is telling him to go and not go?&nbsp;</b><br /><br /><b>Throughout the New Testament we see Paul's calling is to the gentiles.&nbsp;</b><br /><br /><b><a href="http://www.biblegateway.com/passage/?search=Acts+9:15&amp;version=NKJV">Acts  9:15</a></b><br />But the Lord said to him, “Go, for he is a chosen vessel of Mine to bear  My name before <b>Gentile</b>s, <b>kings</b>, and the <b>children</b>  of Israel.<br /><br /><b>We see him called to the children of Israel but not it's leaders. Jerusalem never had accepted him. Like Jesus who could do no miracles in Nazareth, Paul had no honor in Jerusalem. He really had no business in Jerusalem.&nbsp;</b><br /><br /><b>The problems that arose from this came because he was going to a place his calling did not take him. He was "Bound" in his spirit. It was from a burden he felt for the Jews but not a calling of the Holy Spirit. The Holy Spirit was warning him not to go. There were things that Paul could have accomplished that he didn't. There may have been letters that would have been in the New Testament that were not because he didn't write them.&nbsp;</b><br /><br /><b>It is just an opinion at this point. But I believe that from these passages I can reasonably determine that it was not the will of God for Paul to go bound to Jerusalem.&nbsp;</b><br /><b><br /></b><br /><b>So What? Who cares? Well, there is a profound misunderstanding of the will of God here. God worked it out for him to stay alive and minister anyway. But if you get the idea that any thing bad that happens is God's will you will be tempted to avoid victory. I see God warning him NOT to go and Paul going anyway. God will always keep you out of trouble if you listen to Him.&nbsp;</b><br /><br /><b>If you listen to the leading of the Holy Spirit he will direct your paths and lead you to victory.&nbsp;&nbsp;</b><br /><b><br /></b><br /><b>Are there other instances where preaching the Word of God led to Prison or Beatings? Yes. In fact in nearly every city they went to. But in this instance Paul was hindered from his ministry for years. It took two years in Felix's&nbsp; House to then be passed to Rome. Every other time he was attacked he could move on to build the church in a new city. This time is cost him several years. In fact, he never did get to start a new church again, he would live out his remaining days in Rome having people come to him. He wasn't stopped, but he never had the same impact. </b><br /><b><br /></b><br /><h4>Acts 24</h4><b></b><br /><sup class="versenum" id="en-NKJV-27788">22</sup> <i> But when Felix  heard these things, having more accurate knowledge of</i> <i>the</i> <i>  Way, he adjourned the proceedings and said, “When Lysias the commander  comes down, I will make a decision on your case.” <sup class="versenum" id="en-NKJV-27789">23</sup> So he commanded the centurion to keep Paul  and to let</i> <i>him</i> <i> have liberty, and told him not to forbid  any of his friends to provide for or visit him.</i><br /><sup class="versenum" id="en-NKJV-27790">24</sup> <i> And after some days,  when Felix came with his wife Drusilla, who was Jewish, he sent for Paul  and heard him concerning the faith in Christ. <sup class="versenum" id="en-NKJV-27791">25</sup> Now as he reasoned about righteousness,  self-control, and the judgment to come, Felix was afraid and answered,  “Go away for now; when I have a convenient time I will call for you.” <sup class="versenum" id="en-NKJV-27792">26</sup> Meanwhile he also hoped  that money would be given him by Paul, that he might release him.<sup class="footnote" value="[&lt;a href=&quot;#fen-NKJV-27792e&quot;  title=&quot;See footnote e&quot;&gt;e&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=Acts%2024&amp;version=NKJV#fen-NKJV-27792e" title="See footnote e">e</a>]</sup> Therefore he sent for him more  often and conversed with him.</i><br /><sup class="versenum" id="en-NKJV-27793">27</sup> <i> But after two years Porcius Festus  succeeded Felix; and Felix, wanting to do the Jews a favor, left Paul  bound.</i><br /><b><br /></b><br /><br /><br /><b>Paul may have been led by his own emotions into a place of less effective ministry as a result of this one move.&nbsp;</b><br /><br /><b>Lesson if this is true:</b><br /><br /><ul><li><b> Always stay true to your calling and gifting.</b></li><li><b> Heed the warnings of the Holy Spirit</b></li><li><b>Listen to those around you</b></li><li><b>Be absolutely sure if there is question among your people.</b></li></ul><br /><b>DW </b><br /><b> </b><br /><b><br /></b><br /><br /><br /><h4></h4>