---
title: 'Untitled Post'
date: '2010-05-06T20:57:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '30401216359528934'
blogger_filename: '/2010/05/acts-1-8but-you-will-receive-power-when.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=Acts%201&amp;version=NIV">Acts 1</a><br /><br />8But you<strong> will receive power</strong> when the Holy Spirit comes on you; <br />&nbsp; <br /><a href="http://www.biblegateway.com/passage/?search=Galatians+2:1&amp;version=NIV">Galatians 2</a> <br /><br /><br />Paul Accepted by the Apostles <br /><br /><strong>1Fourteen years later</strong> I went up again to Jerusalem, this time with Barnabas. I took Titus along also. <br />&nbsp; <br />&nbsp; <br /><a href="http://www.biblegateway.com/passage/?search=2%20Kings+2&amp;version=NIV">2 Kings 2</a> <br />&nbsp; <br />1 When the LORD was about to take Elijah up to heaven in a whirlwind, Elijah and Elisha were on their way from Gilgal. 2 Elijah said to Elisha, "Stay here; the LORD has sent me to Bethel." <br /><br /><br />But Elisha said, <strong>"As surely as the LORD lives and as you live, I will not leave you."</strong> So they went down to Bethel. <br /><br />3 The company of the prophets at Bethel came out to Elisha and asked, "Do you know that the LORD is going to take your master from you today?" <br /><br />"Yes, I know," Elisha replied, "but do not speak of it." <br /><br /><br />Today I got to thinking about POWER... Yes, as soon as the apostles received the baptism they recieved power and became mighty witnesses. But it seems that others don't have that same imediate effect. It could be the receiver? What I see is 11 men who followed a personal discipleship for 3 solid years and were caused to grow some in that time. They recieved instruction and although MOST of that seed didn't come to flower until after this fire baptism, it was there and it germinated. <br /><br />We look at Paul, and for all the fire he had after his conversion it was merely eaqual to the fire he had AGAINST Christ before. It wasn't until a 14 year silent period that he came back and was recognized by the apostles and got promoted of the Holy Spirit to an Apostle. Even at his return he shows himself submitted to authority by submitting his message for approval by those in authority. <br /><br />Elisha served Elijah with bulldog faith and got his power. <br /><br />Submission is a key to promotion. Submission FIRST to God and then to those he places you under. <br /><br /><br />dw