---
title: 'LOVE to FIGHT'
date: '2010-03-15T01:46:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5897830835300830892'
blogger_filename: '/2010/03/love-to-fight.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<h2 id="passage_heading"><i><br /></i></h2><h2 id="passage_heading"><i><a href="http://www.biblegateway.com/passage/?search=Luke%206:27-38&amp;version=NKJV">Luke 6:27-38</a>&nbsp;(New King James Version)</i></h2><h5><i>Love Your Enemies</i></h5><i>&nbsp;&nbsp;&nbsp;<br \="" /><sup class="versenum" id="en-NKJV-25170">27</sup> “But I say to you who hear: <b>Love</b> your enemies, <b>do good</b> to those who hate you, <sup class="versenum" id="en-NKJV-25171">28</sup> <b>bless</b> those who curse you, and <b>pray for those</b> who spitefully use you. <sup class="versenum" id="en-NKJV-25172">29</sup> To him who strikes you on the </i> <i>one cheek, <b>offer </b>the other also. And from him who takes away your cloak, <b>do not withhold </b></i><i>your tunic either. <sup class="versenum" id="en-NKJV-25173">30</sup> <b>Give to everyone</b> who asks of you. And from him who takes away your goods <b>do not ask</b> </i><i><b>them</b><sup class="versenum" id="en-NKJV-25174">31</sup> And just as you want men to do to you, you also do to them likewise.    <br \="" /><sup class="versenum" id="en-NKJV-25175">32</sup> “But if you love those who love you, what credit is that to you? For even sinners love those who love them. <sup class="versenum" id="en-NKJV-25176">33</sup> And if you do good to those who do good to you, what credit is that to you? For even sinners do the same. <sup class="versenum" id="en-NKJV-25177">34</sup> And if you lend </i> back.  <i>to those from whom you hope to receive back, what credit is that to you? For even sinners lend to sinners to receive as much back. <sup class="versenum" id="en-NKJV-25178">35</sup> But love your enemies, do good, and lend, hoping for nothing in return; and your reward will be great, and you will be sons of the Most High. For He is kind to the unthankful and evil. <sup class="versenum" id="en-NKJV-25179">36</sup> Therefore be merciful, just as your Father also is merciful.</i><br /><h5><i>Do Not Judge</i></h5><i>&nbsp;&nbsp;&nbsp;<br \="" /><sup class="versenum" id="en-NKJV-25180">37</sup> “<b>Judge not</b>, and you shall not be judged. <b>Condemn not</b>, and you shall not be condemned. <b>Forgive</b>, and you will be forgiven. <sup class="versenum" id="en-NKJV-25181">38</sup> <b>Give</b>, and it will be given to you: good measure, pressed down, shaken together, and running over will be put into your bosom. <b>For with the same measure that you use, it will be measured back to you.”&nbsp;</b></i><br /><br />Let's take a look at the Key Words placed in these verses:<br /><ul><li><i><b>Love</b></i></li><li><i><b>Do Good</b></i></li><li><i><b>Bless</b></i></li><li><i><b>Pray for Those</b></i></li><li><i><b>Offer</b></i></li><li><i><b>Do Not Withhold</b></i></li><li><i><b>Give to Everyone</b></i></li><li><i><b>Do Not Ask For Them Back</b></i></li><li><i><b>Judge Not</b></i></li><li><i><b>Condemn Not</b></i></li><li><i><b>Forgive</b></i></li></ul>&nbsp;&nbsp;&nbsp;&nbsp; This would be an impressive list for anyone to be living out, but when you take a look are realize that Jesus is directing the emphasis of this chapter to your enemies... you have a real understanding of NO EXCUSES.&nbsp; <br /><br />&nbsp;&nbsp;&nbsp;&nbsp; When you are frustrated or upset with anyone... it's time to pull out this list. Sometimes the enemy to your peace may not be someone TRYING to cause you harm. Maybe, sometimes, it's a customer, co-worker, kids, spouse, or someone else causing frustration to you... sometimes... maybe it's YOU not THEM that's the problem. No matter what the situation the solution to ALL people issues is found in the list above.<br /><br />&nbsp; &nbsp;&nbsp; Why did Jesus leave us this list of turn the other cheek type stuff? Was it to turn the residence of the Kingdom of God into a doormat? Was Jesus EVER a doormat in His life on earth? THEN... the answer is NOT that He wants doormat Christians.&nbsp; The answer is this:<br /><br /><br /><ul><li><i><b>&nbsp;</b><b>"For with the same measure that you use, it will be measured back to you.”</b></i><i><b> </b></i></li></ul>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; It's all back to what Jesus said was THE parable to explain ALL parables:<br />The SOWER went out to SOW... What you sow you reap... period. If you got problems with people, SOW LOVE, RETALIATE at the enemies attack against you in LOVE... THEN God can step in. Notice...When Jesus was being taken to a hill by his kin folk to be tossed over the edge: It doesn't say Jesus "went out swinging". It says He passed through the midst of them. Love just walks through traps and frustrations. The problem will find itself back on the person causing it if they don't repent.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; What or Who have you been frustrated with... Could you be displaying a lack of LOVE?<br /><br /><i><b><br /></b></i><br /><i><b>&nbsp;&nbsp;&nbsp;&nbsp; Darrell G. WOlfe</b></i>