---
title: 'Kingdom of God… Mustard Seeds'
date: '2010-01-20T06:34:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1813141719211497298'
blogger_filename: '/2010/01/kingdom-of-god-mustard-seeds.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p>01/19/2009    <br /></p><p>Happy Birthday Connor, my son turned five today. It's amazing to me how quickly one can grow in such a short time. I was contemplating this as I read today.<br /></p><p>Matthew 13<br /></p><h5><span style='font-size:10pt'>    <span style='font-family:Times New Roman'><strong>The Mustard Seed and the Leaven<br /></strong></span></span></h5><p><span style='font-family:Times New Roman; font-size:10pt'><em> <sup>31</sup>He put another parable before them, saying, <sup>(<a title='See cross-reference AN' href='http://www.biblegateway.com/passage/?search=matthew%2013&amp;version=ESV'><span style='color:blue; text-decoration:underline'>AN</span></a>)</sup> "The kingdom of heaven is like<sup>(<a title='See cross-reference AO' href='http://www.biblegateway.com/passage/?search=matthew%2013&amp;version=ESV'><span style='color:blue; text-decoration:underline'>AO</span></a>)</sup> a grain of mustard seed that a man took and sowed in his field. <sup>32</sup>It is the smallest of all seeds, but when it has grown it is larger than all the garden plants and becomes a tree, so that the birds of the air come and make nests in its branches."<br /></em></span></p><p><span style='font-family:Times New Roman; font-size:10pt'><em> <sup>33</sup>He told them another parable. <sup>(<a title='See cross-reference AP' href='http://www.biblegateway.com/passage/?search=matthew%2013&amp;version=ESV'><span style='color:blue; text-decoration:underline'>AP</span></a>)</sup> "The kingdom of heaven is like leaven that a woman took and hid in<sup>(<a title='See cross-reference AQ' href='http://www.biblegateway.com/passage/?search=matthew%2013&amp;version=ESV'><span style='color:blue; text-decoration:underline'>AQ</span></a>)</sup> three measures of flour, till it was<sup>(<a title='See cross-reference AR' href='http://www.biblegateway.com/passage/?search=matthew%2013&amp;version=ESV'><span style='color:blue; text-decoration:underline'>AR</span></a>)</sup> all leavened."<br /></em></span></p><p>        I know Jesus talked about being ware of the leaven of the Pharisees. However, in this context Jesus is pointing to how leaven can benefit as well. The Kingdom of God is a huge thing. You cannot fathom and explore every nook and cranny of it's function in one lifetime. This is one of the reasons we must learn from those who have come before and build from their level up. <br /></p><p><br /> </p><p>        It's amazing to me how fast one can grow in the things of God. Alvin may get saved and stay at the same level of growth for ten years.  John may have gotten saved at the same service and just sprouted wings and flew into the things of God. Ten Years later Alvin hasn't changed much, still struggling with the same things. John has become a full time pastor or worker or taken new and innovated ideas into the marketplace and revolutionized things with God's ideas… But if in the next ten years John pushes no harder but only maintains and Alvin pushes harder into the things of God, the end result twenty years after the two were saved is that Alvin is doing more for God… What's My point?<br /></p><p><br /> </p><p>        It starts small. In fact the Kingdom of God starts at the same exact level for every human being; the incorruptible seed of the Word. Everyone must be born again to enter into the Kingdom of God. Therefore we all have the same entry point. We've all been dealt the measure of faith.<br /></p><p><a href='http://www.biblegateway.com/passage/?search=Romans%2012:2-4&amp;version=ESV'><h2><span style='color:blue; font-size:10pt; text-decoration:underline'><em>Romans 12:2-4 </em></span></h2></a><h2><span style='font-size:10pt'><em>(English Standard Version)<br /></em></span></h2></p><p><span style='font-size:10pt'><em><sup>2(<a title='See cross-reference A' href='http://www.biblegateway.com/passage/?search=Romans%2012:2-4&amp;version=ESV'>A</a>)</sup> Do not be conformed to this world,<sup>[<a title='See footnote a' href='http://www.biblegateway.com/passage/?search=Romans%2012:2-4&amp;version=ESV'>a</a>]</sup> but be transformed by<sup>(<a title='See cross-reference B' href='http://www.biblegateway.com/passage/?search=Romans%2012:2-4&amp;version=ESV'>B</a>)</sup> the renewal of your mind, that by testing you may<sup>(<a title='See cross-reference C' href='http://www.biblegateway.com/passage/?search=Romans%2012:2-4&amp;version=ESV'>C</a>)</sup> discern what is the will of God, what is good and acceptable and perfect.<sup>[<a title='See footnote b' href='http://www.biblegateway.com/passage/?search=Romans%2012:2-4&amp;version=ESV'>b</a>]</sup><br />					</em></span></p><h5><span style='font-size:10pt'>Gifts of Grace<br /></span></h5><p><span style='font-size:10pt'><em> <sup>3</sup>For<sup>(<a title='See cross-reference D' href='http://www.biblegateway.com/passage/?search=Romans%2012:2-4&amp;version=ESV'>D</a>)</sup> by the grace given to me I say to everyone among you<sup>(<a title='See cross-reference E' href='http://www.biblegateway.com/passage/?search=Romans%2012:2-4&amp;version=ESV'>E</a>)</sup> not to think of himself more highly than he ought to think, but to think with sober judgment,<sup>(<a title='See cross-reference F' href='http://www.biblegateway.com/passage/?search=Romans%2012:2-4&amp;version=ESV'>F</a>)</sup> each according to<sup>(<a title='See cross-reference G' href='http://www.biblegateway.com/passage/?search=Romans%2012:2-4&amp;version=ESV'>G</a>)</sup><br />						<strong>the measure of faith</strong> that God has assigned.</em><br />				</span></p><p><br /> </p><p><span style='font-size:12pt'>        To each person on the planet God has dealt the same tools. Jesus compared them to <a href='http://www.biblegateway.com/passage/?search=Matthew%2025:14-30&amp;version=NKJV'>talents</a> parted to servants. Some had more to work with, some had less. All were judged by the results of what they did at their level. <a href='http://www.biblegateway.com/passage/?search=Romans+10:17&amp;version=NKJV'>Faith comes by hearing</a> and hearing by the Word! So God has dealt to each person on the planet, no matter what level they are at, the same measure of faith. The measure is called "BIBLE". There are those who have more access to it then others. Yet those with less access may do more with what they get. You have been given the Word of God. Sow it into your heart. Speak it with your mouth… let it grow inside of you. <br /></span></p><p><br /> </p><p><span style='font-size:12pt'>        As it grows it will become the mighty tree inside of you. You will become a tree of Righteousness planted by the waters. You may not think it's much. What does reading this chapter today have to do with me fulfilling great and mighty things I don't even know about yet? The seed may start as the smallest, most misunderstood, seemingly insignificant seed in the garden… just wait! As it grows it becomes the largest tree in the whole garden! Why? Seed… Time… Harvest… It's the plan of God from Genesis to Revelations. <br /></span></p><p><br /> </p><p><span style='font-size:12pt'>        There may be some action, some step, some plan, something that God's been telling  you to do. It seems small. It seems like it has nothing to do with the crisis you are facing now. You want a solution to your now problem and God is trying to deal with tomorrow inside of you. Take it… You NEVER know where it might lead… except that you will ALWAYS know that God's Will for your life will lead to more BLESSING than you can imagine or even keep… His plan is to turn you into a Hose of Blessing, not a water tower! Start small… <br /></span></p><ul><li><span style='font-size:12pt'>Did He tell you to write a book? Start with a basic writing on what you want to write about… set a date every week to work on it for one hour… <br /></span></li><li><span style='font-size:12pt'>Tour the world as a musician? What songs are you writing? What steps have you taken to develop your skill?<br /></span></li><li><div><span style='font-size:12pt'>Become a doctor? What classes are you taking?<br /></span></div><p><br /> </p><p><br /> </p></li></ul><p><span style='font-size:12pt'>What has God called you to do; but it seems so big and immense that you cannot fathom how you could ever do it? That's easy… plant a mustard seed. Do SOMETHING… anything… by the Leading of the Holy Spirit… that will start you toward the Call of God on your life… You'll be amazed at were you've come down the road… <br /></span></p><p><br /> </p><p><span style='font-size:12pt'>I know I am… I never imagined being a father of a five year old could be this amazing… challenging… and thrilling… <br /></span></p><p><br /> </p><p><span style='font-size:12pt'>Be BLESSED (Empowered to Prosper)<br /></span></p><p><br /> </p><p><span style='font-size:12pt'>              Darrell G. Wolfe<br /></span></p></span>