---
title: 'Born of the Spirit and Light'
date: '2010-04-09T18:58:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7895219359207401985'
blogger_filename: '/2010/04/born-of-spirit-and-light.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=John%203&amp;version=NKJV">John 3</a><br /><br /><br /><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><sup class="versenum" id="en-NKJV-26122" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;"><i>5</i></sup><i>&nbsp;Jesus answered, “Most assuredly, I say to you, unless one is born of water and the Spirit, he cannot enter the kingdom of God.&nbsp;</i><sup class="versenum" id="en-NKJV-26123" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;"><i>6</i></sup><i>&nbsp;That which is born of the flesh is flesh, and that which is born of the Spirit is spirit.</i>&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">One must be born all over again. This isn't about "Conversion". We're not trying to get your to join our group! This about understanding that you are dead, and there is a NEW you. Not just&nbsp;metaphorically. You really are NEW. Time alone prevents us from taking on our new bodies to go with our new spirits but we are NEW NOW.</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Therefore we must evaluate all we do in light of this. If an idea or task is of the flesh it will have no effect for you. You can struggle with get rich quick schemes and others projects and drive your body to death but still see no supernatural results. ALL your&nbsp;endeavors&nbsp;must be of the spirit. If you are working HIS plan than you are more than able to succeed.&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Pray until you get an unction from HIM what you should do today, what you should buy, what you should do to believe for the next step...&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">That brings up something important for me today... if I am faced with the daunting task of needing something to happen but seeing no&nbsp;solutions&nbsp;in sight than I must be VERY cautious NOT to spin and spin trying to MAKE something happen or FORCE a solution. I should shift DOWN into LOW SLOW, check inside and pray until I have exactly what the mind of God is. He is not&nbsp;surprised&nbsp;by a need and He already PLANNED on meeting this need before time began. Therefore HE is already in process of meeting that need. It will not happen if I don't jump into HIS flow and get onto HIS plan.&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><span class="Apple-style-span" style="font-size: 16px;"><sup class="versenum" id="en-NKJV-26138" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;"><i>21</i></sup></span><span class="Apple-style-span" style="font-size: 16px;"><i>&nbsp;But he who does the truth comes to the light, that his deeds may be clearly seen, that they have been done in God.”</i></span></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><span class="Apple-style-span" style="font-size: 16px;"><br /></span></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">This brings another subject to light... If there is anything in you that feels like you need to hide from others, especially those close to you that is a red flag of darkness. There are no secrets in the Kingdom of God. Everybody in heaven knows your thoughts. If you don't feel totally at peace with someone checking up on you, looking into your records, questioning why you did something... even if you did it all right... you may not have had right motives. Check that out, darkness is taking hold somehow and it needs to be purged to hear from God clearly.&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Darrell G. Wolfe</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">I've discovered an interesting book:</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><iframe align="left" frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?t=your0f4d-20&amp;o=1&amp;p=8&amp;l=bpl&amp;asins=B000K0GSMO&amp;fc1=000000&amp;IS2=1&amp;lt1=_blank&amp;m=amazon&amp;lc1=0000FF&amp;bc1=000000&amp;bg1=FFFFFF&amp;f=ifr" style="align: left; height: 245px; padding-right: 10px; padding-top: 5px; width: 131px;"></iframe></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">This man of God, no long gone to heaven, has deep and&nbsp;penetrating&nbsp;insights and I&nbsp;challenge&nbsp;anyone to read his work 365 days in a row and ask yourself this question after each reading. "What must I do about this TODAY in my life?"</span>