---
title: 'Stand Your Ground!'
date: '2010-01-06T04:39:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1969004650372704989'
blogger_filename: '/2010/01/stand-your-ground.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

Sunday Service 01/03/2010<br /><br /><span style="font-size: x-large;"><b>Stand Your Ground!</b></span><br /><br /><a href="http://www.biblegateway.com/passage/?search=ephesians%206&amp;version=NKJV">Ephesians 6</a>:<br /><br /><i><sup class="versenum" id="en-NKJV-29344">10</sup> Finally, my brethren, be strong in the Lord and in the power of His might. <sup class="versenum" id="en-NKJV-29345">11</sup> Put on the whole armor of God, that you may be able to <b>stand </b>against the wiles of the devil. <sup class="versenum" id="en-NKJV-29346">12</sup> For we do not wrestle against flesh and blood, but against principalities, against powers, against the rulers of the darkness of this age,<sup class="footnote" value="[&lt;a href=&quot;#fen-NKJV-29346c&quot; title=&quot;See footnote c&quot;&gt;c&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=ephesians%206&amp;version=NKJV#fen-NKJV-29346c" title="See footnote c">c</a>]</sup> against spiritual </i><i>hosts of wickedness in the heavenly </i><i>places. <sup class="versenum" id="en-NKJV-29347">13</sup> Therefore take up the whole armor of God, that you may be able to withstand in the evil day, and having done all, to <b>stand</b>.    <br \="" /><sup class="versenum" id="en-NKJV-29348">14</sup> <b>Stand </b>therefore...</i><br /><br />&nbsp;The word "stand" is the Greek word: Hestemi. It means:<br /><br /><ul><li>Set- as in concrete</li><li>Resolved</li><li>Resolute</li><li>Stubborn</li><li>In Military Application: Man your post, stand/remain steady at your post</li><li>In Essence: Be a BULLDOG! Aggressive, Persistent, and Determined to stand against ALL the wiles/schemes/plans of the Devil!&nbsp;</li></ul>There are VERY bad things coming for those who are in the World this Year. For many, like myself, this will be among the best years of our lives. However, for many this will be among the worst years. Finances, Governments, Health Care, Natural Disasters, and Crisis of many kinds are coming on a global scale. There are many going to be running for anything that smells stable. There we will be... the GLORIOUS Church...<br /><br />We will:<br /><br /><br /><i><sup class="versenum" id="en-NKJV-29348">14</sup> <span style="font-size: large;"><b>Stand therefore</b></span>, having girded your waist with truth, having put on the breastplate of righteousness, <sup class="versenum" id="en-NKJV-29349">15</sup> and having shod your feet with the preparation of the gospel of peace; <sup class="versenum" id="en-NKJV-29350">16</sup> above all, taking the shield of faith with which you will be able to quench all the fiery darts of the wicked one. <sup class="versenum" id="en-NKJV-29351">17</sup> And take the helmet of salvation, and the sword of the Spirit, which is the word of God; <sup class="versenum" id="en-NKJV-29352">18</sup> praying always with all prayer and supplication in the Spirit, being watchful to this end with all perseverance and supplication for all the saints—</i><br /><br /><br />We WIll be that light the world needs in dark and terrible times. We will be that house built on a rock totally undisturbed by the storm beating down on it. We will be the light on the hill, the salt, the preserving agent. They will come running and we will have an answer for all who ask us:<br /><br />What is this HOPE you have... in the middle of all this chaos? How can you NOT be worried?<br /><br /><br />Winston Churchhill said:<br />"For a nation to try to tax or borrow themselves into prosperity is as a man who stands in a bucket and then tries to list himself up by the handle!"<br /><br />This Nation, like others, has done just that. That stupid system of finance, based on rules that had to over rule the bible and the US constitution to come about is crashing around us. It is coming down. They will need answers and we will be there to provide for them.<br /><br /><br />One area I found that has been a weak spot with my ability to stand in life is my emotions. I get "hooked" by kids screaming or customers refusing to listen or understand. I get mad and frustrated because something isn't going the way <b>I</b> wanted it to. Enough is enough. In 2010 I refuse to be disturbed about anything or by anyone! I will be that rock, stable no matter what you say or do.<br /><br />Word of the Lord to the Church of EMIC, by Pastor George:<br />"After the dust settles on 2010 you will still be STANDING!"<br /><br />Standing is NOT a weak term. Not a term of struggle. It's a term with the image of a strong marine being attacked by a child sized enemy. He doesn't smile or laugh. He just stands, strong... cool... collected... able to act... but not in a rush about anything... It's the term and image of an enforcer! More on that later!<br /><br />Darrell Wolfe<br /><br />PS:<br /><br />"Darrell, what do you mean 'rules that had to over rule the bible AND the US constitution'?"<br />See:<br /><br /><a href="http://www.bvov.tv/emic/ondemand.php">Thursday 7:15 PM 4/02/2009</a><br />Graham Daniels<br /><b>Money, Banking, and Gold</b>           <br /><b>Triggers for the Cash, Strategies for Growth</b><br /><br /><a href="http://www.bvov.tv/emic/ondemand.php">Wednesday 7:15 PM 4/01/2009</a><br />Graham Daniels<br /><b>Remember Your Heritage</b>           <br /><br /><b>More on <a href="http://wealthbygold.com/index.php?option=com_content&amp;task=view&amp;id=77&amp;Itemid=63">Graham Daniels</a>&nbsp;</b><b> <br /></b>