---
title: 'The Gospel of the Kingdom of God- Expounded'
date: '2010-01-08T03:27:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1554598850248981482'
blogger_filename: '/2010/01/the-gospel-of-kingdom-of-god-expounded.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

January 01/07/2010<br />Mathew <a href="http://www.biblegateway.com/passage/?search=Mathew%205&amp;version=NKJV">Chapter 5</a><br /><br />Jesus here begins what has become known as "The Sermon on the Mount". This title is a describes where he was at the time he preached this message. We found out in chapter four that Jesus went out teaching and preaching "The Gospel of the Kingdom". <br /><br />All the teachings of Jesus are most accurately understood with this framework in mind. Everything Jesus taught, everything He did, was to bring to life the Kingdom of God in mankind. When he sent his disciples out his instructions were to tell people that: "The Kingdom of God is at hand". So what is this kingdom, how does it work, what does it mean, where is it? This is the point of all that proceeds during the entire life's work of Jesus on this planet during his earthly reign, and that of his apostles and followers after Him.<br /><br />This is NOT a random compilation of things he said that were nice truisms or good food for thought. This was a piece by piece breakdown of the details of the Kingdom of God and how to live that out. There is a word in Hebrew Word that bears on this subject; HaLaKaH from the root <a href="http://www.ancient-hebrew.org/35_dictionary_05.html">HaLaKH</a> to Walk:<br /><br />Jesus was showing us how to walk this life in the Kingdom of God out. So what was he having us walk out?<br /><br />The Blessing. The Blessing was given first to Adam, then to Noah and finally to Abraham to Jesus to You and I. This Blessing empowers anyone who walks it out to <a href="http://www.biblegateway.com/passage/?search=Deut%2028&amp;version=NKJV">prosper</a>. Ultimately Jesus teaches us that LOVE is the key to the Kingdom of God. LOVE unlocks the blessing and LOVE destroys the works of the Devil. The key points that apply to me at this time:<br /><br />:9 Blessed are the Peacemakers for they shall be called the Sons of God.<br /><ul><li>I am, more than ever at this stage of my life, learning to be and called into the role of peacemaker. Not with guns or swords but with words, seasoned with The Word. At home with my two boys constantly winding each other up, and me with them, and also at the job. Being that rock in an unstable and unsure environment. Being steady, in the midst of a national struggle to keep finances straight. I am called, not to argue and defend, but to come along side and comfort as best as I am allowed to do so.&nbsp;</li></ul>:22-23 Cursing ANY ONE, at ANY TIME, for ANY REASON is High Treason against the Commandment of LOVE.<br /><ul><li>It is a violation of the highest order and it will stop the flow of the blessing DEAD in your life until it is dealt with. Jesus doesn't think it's funny to put down, ridicule, or make fun of anyone, in or out of their presence! It's serious offense and it's not funny. <br /></li></ul>&nbsp;:37 Yes or No... Don't Swear!<br /><br /><ul><li>This also means No Excuses. If someone asks me to meet with them... I should NOT come up with the thirty reasons why I can't right now. Just say No or Yes. AND don't make that call until you are sure. You may want to say NO and the Holy Spirit may lead you to do it anyway. You may WANT to say YES and the Holy Spirit will say NO. So don't just jump out with an answer either. You may be bound to it, and not like the results. If you have no direct leading on the request at the time it is made inform the person you will get back to them as soon as you can. Then make it a point to pray about it, research, check your calender and check with those you are responsible to: Spouse, Boss, whoever. Then come back with a definite yes or no. </li></ul>:19 Whoever DOES AND TEACHES<br /><br /><ul><li>Everyone in the Kingdom is required to hear it, learn it, DO it, and Teach it to others. NO exceptions. Everyone will do their part at different levels and in different functions. But no one is exempt from growing in their walk in the Kingdom of God enough to Teach others to do the same. That's true one on and one and for those who teach thousands. </li></ul>Those are the things I picked up for my life today... there is SO much more I wanted to say... but that will have to be another entry on another day.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Blessed: Darrell G. Wolfe Ambassador of the KOG