---
title: 'The Simple Will of God...'
date: '2010-12-25T01:59:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1591460118640883137'
blogger_filename: '/2010/12/the-simple-will-of-god.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

&nbsp;&nbsp;&nbsp;&nbsp; Type in "The Will of God" into a google search... you come up with the most amazingly silly things spoken by pastors and theologians. One of the top searches has a man saying that God's sovereign will has him causing things that he forbids. The idea is that he forbids a thing and dislikes it but then wills it through his sovereign will.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; What utter nonsense! God's will is his Word. God's Word is his will. This is not a complicated topic. It takes a good theologian to help you mis understand the bible.<br /><br />&nbsp;&nbsp;&nbsp; Someone says the bible says to pray: "If it's thy will..." Yes... and No... In certain matters there is room for question. Should you go to Rome or Moscow for your next ministry trip? Should you take this job or that job? There could be room for error here on matters such as these that require a specific leading of God.<br />&nbsp;<br />&nbsp; &nbsp;&nbsp; James here in the book of <a href="http://www.biblegateway.com/passage/?search=James+4&amp;version=NKJV">James Chapter 4</a> is addressing pride in an individual that is making plans on his own, outside the leading of the Holy Spirit. The subject is pride and boasting. The understood subject is a person doing their own thing. Of course in this instance he would have no way of knowing what may come tomorrow, and would be better off saying: "If God wills..." to learn to submit to God.<br /><br />&nbsp; &nbsp;&nbsp; However Jesus tells us in <a href="http://www.biblegateway.com/passage/?search=John+7:17&amp;version=NKJV">John 7:17</a> that if anyone wills to do the will of God that he will know what is of God and what isn't. This means that anyone who is born again, and spirit filled, and praying for the will of God with the right heart (a heart of obedience) will know the will of God.<br /><br />&nbsp; &nbsp; What does knowing the will of God look like? <strong><a href="http://www.biblegateway.com/passage/?search=Philippians+4:7&amp;version=NKJV">Philippians 4:7</a> and </strong><strong><a href="http://www.biblegateway.com/passage/?search=Colossians+3:15&amp;version=NKJV">Colossians 3:15</a></strong> say that the Peace of God will rule and guard your hearts and minds. That means with any decision you will follow the Peace of God. Look inside and pray until you find that peace. You could even try an experiment. When you are faced with options A or B... Say out loud just as a test: "I will do A." If you get a check inside say out loud "I will do B." If neither option comes with peace just be still for awhile, a day or three if need be until you find that peace settling inside.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; Certain matters are not up for debate. God is sovereign. When a sovereign God makes a sovereign decision it is final! God's word, where ever he has declared his will, is final authority on the matter. His Word is of a higher authority than any fact.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; God has set in his will that salvation belongs to anyone who will receive it! That is FINAL! No One that wants into heaven will be left out. It is not God's will that anyone go to hell, but he will respect your decision to go there. <br /><br />&nbsp;&nbsp;&nbsp;&nbsp; God has set in his will that healing, prosperity, and abundance belongs to everyone who will believe. God has set in his word that his benefits are for all who believe. You recieve salvation, healing, prosperity, and the rest of his benefits the same way. Believe in your heart and confess with your mouth, with no doubting.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; So the next time you need something, don't pray "IF it be thy will..." Go to His word, find out what His will is and declare it so!<br /><br /><ol class="keyword-result-list" start="1"><li><strong><a href="http://www.biblegateway.com/passage/?search=Psalm+68:19&amp;version=NKJV">Psalm 68:19</a></strong><br />Blessed be the Lord,Who daily loads us with <b>benefits</b>,The God of our salvation!&nbsp;&nbsp;Selah&nbsp;<br /><span class="keywordresultextras"><a href="http://www.biblegateway.com/passage/?search=Psalm+68:18-20&amp;version=NKJV">Psalm 68:18-20</a> (in Context)  <a href="http://www.biblegateway.com/passage/?search=Psalm+68&amp;version=NKJV">Psalm 68</a> (Whole Chapter) </span> </li><li><strong><a href="http://www.biblegateway.com/passage/?search=Psalm+103:2&amp;version=NKJV">Psalm 103:2</a></strong><br />Bless the LORD, O my soul,And forget not all His <b>benefits</b>:<br /><span class="keywordresultextras"><a href="http://www.biblegateway.com/passage/?search=Psalm+103:1-3&amp;version=NKJV">Psalm 103:1-3</a> (in Context)  <a href="http://www.biblegateway.com/passage/?search=Psalm+103&amp;version=NKJV">Psalm 103</a> (Whole Chapter) </span> </li><li><strong><a href="http://www.biblegateway.com/passage/?search=Psalm+116:12&amp;version=NKJV">Psalm 116:12</a></strong><br />What shall I render to the LORD For all His <b>benefits</b> toward me?<br /><span class="keywordresultextras"><a href="http://www.biblegateway.com/passage/?search=Psalm+116:11-13&amp;version=NKJV">Psalm 116:11-13</a> (in Context)  <a href="http://www.biblegateway.com/passage/?search=Psalm+116&amp;version=NKJV">Psalm 116</a> (Whole Chapter)&nbsp;</span></li><li><strong><a href="http://www.biblegateway.com/passage/?search=Mark+11:24&amp;version=NKJV">Mark 11:24</a></strong><br />Therefore I say to you, whatever things you ask when you pray, <b>believe</b> that you receive them, and you will have them.<br /><span class="keywordresultextras"><a href="http://www.biblegateway.com/passage/?search=Mark+11:23-25&amp;version=NKJV">Mark 11:23-25</a> (in Context)  <a href="http://www.biblegateway.com/passage/?search=Mark+11&amp;version=NKJV">Mark 11</a> (Whole Chapter)&nbsp;</span></li><li><h4><a href="http://www.biblegateway.com/passage/?search=Deuteronomy+28&amp;version=NKJV">Deuteronomy 28</a></h4>&nbsp;<span class="keywordresultextras"></span></li></ol>