---
title: 'Martin Luther King Jr.'
date: '2010-01-19T03:14:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1423847066955906993'
blogger_filename: '/2010/01/martin-luther-king-jr.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p>01/18/2010<br /></p><p>In Memory of <a href='http://nobelprize.org/nobel_prizes/peace/laureates/1964/king-bio.html'>Martin Luther King Jr.</a><br />			</p><p>    A man who saw by faith a world living under the unity of the brethren in Christ! It was by faith that Mr. King saw the desire and will of God and took the reigns of destiny to forever change the course and direction of this earth. It if because of people like Martin Luther that I can have people like <a href='http://www.bwm.org/'>Bill Winston</a> and <a href='http://www.kcm.org/index.php?p=home'>Kenneth Copeland</a> together in the same meeting and get fed by both! GLORY to God! Thank you Jesus for the gift you gave the world in the person of Martin Luther King Jr. Forgive us Father… for turning his good work of love into a mockery of hate and fear, putting down people and your church claiming tolerance instead of embracing the Love of Christ as he did.  May we always remember him for the man he was… A Man of God!<br /></p><p><br /> </p><p>Let's take a moment to be thankful for the men of God who have brought us further into the freedom God promises in his Word!<br /></p><p><br /> </p><p>Darrell G. Wolfe</p></span>