---
title: 'Hard, Tender, Free...'
date: '2010-01-28T04:39:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7745410515474199927'
blogger_filename: '/2010/01/hard-tender-free.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.blogger.com/goog_1264652634446">01/27/2010<br /></a><br /><a href="http://www.blogger.com/goog_1264652634446"><br /></a><br /><a href="http://www.biblegateway.com/passage/?search=Matthew%2019&amp;version=AMP">Matthew 19</a><br /><br /><br />It is not about what is ALLOWED... It's about what is RIGHT.<br /><br />Hard hearts are the reason for divorce. The one seeking the divorce may not be the one with the hard heart either. But hard hearts are ALWAYS the culprit. But this is not just true of divorce but anything that robs us in life. Every act of a human that violates another human is a matter of a hard heart.<br /><br />This is compared to the tender heart of a child. Have you ever seen a small child hold a grudge? Most kids, unless badly abused, are quick to forgive AND forget. This is the way we'll have to be to function in the Kingdom of God.<br /><br />There is no forgiving without forgetting... it's all one. If you choose to bring it up, remember it, and ponder it... you are failing to act out forgiveness. When it tries to come up, remind yourself that you've forgiven them and out loud rebuke that thought from having any place in you. <br /><br />Does stuff have you or do you have stuff?<br /><br />There is nothing wrong with stuff... in fact in several places it talks about the rich women who ministered to Jesus and to Paul out of their wealth. But when stuff has you, which is evidently what happened to this young man who was grieved at the idea of giving, than you have a problem. God can't use your heart if it's not totally available to him. It's still talking about tender hearts, never left the subject from verse one...<br /><br />I determine today, that I have a tender, correctable, easy to love heart. I determine that nothing has me, but that ALL I have is open for the Masters use! That includes, Spirit, Soul, Body, Mind, Stuff, Money, Time, Sleep... Etc...<br /><br /><br />Darrell G. WOlfe