---
title: 'Steps of Faith'
date: '2010-04-29T13:21:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8179884278382195643'
blogger_filename: '/2010/04/steps-of-faith.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

Notes on Healing and Faith<br /><br />Healing doesn't mean no doctors, unless God specifically tells you no, but it also doesn't mean relying on them over what God said. You can follow some of these general principles:<br /><br /><br /><ul><li>Get the Word of God on the subject. 15 scriptures might not even be as effective as meditating on two or three. <br /></li><li>You read them several times a day, and confess them every time you are feeling pain or anything contrary to your expected outcome. <br /></li><li>Watch for words of unbelief. When you are tempted to talk about your pain change it to either</li><ul><li>How much your good body parts feel</li><li>How your injured part is recovering <br /></li><li>Then move on to new topic</li></ul><li>Take your doctors advice. Doctors aren't always right, you know that better than me. However they know some things and unless God tells you directly to ignore a certain advice follow it obediently. Submit to that authority. <br /></li><li>Many times God will use medications and surgeries for the simple reason that you aren't developed enough in faith, or ARE developed enough against it that it would either take longer or not happen. He may direct you along those lines too in the mean time. Even then you have to confess the Word over that and believe God against side effects and for recovery. The Word always takes first place and final authority. <br /></li><li>Always believe for more and better than the doctor projects. Word of God people don't settle for natural results!</li></ul>These principles apply to finances and any other need I have.