---
title: 'Jesus is LORD over all Traditions!'
date: '2010-01-19T03:50:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8473631383929430770'
blogger_filename: '/2010/01/jesus-is-lord-over-all-traditions.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p>01/18/2010<br /></p><p><a href='http://www.biblegateway.com/passage/?search=Matthew%2012&amp;version=NKJV'>Matthew 12</a><br />			</p><p><br /> </p><p>     Tradition isn't bad. Tradition is nothing more than Habit at the group level. Habits can be good for you. There is a book called <a href='http://www.amazon.com/Habits-Highly-Effective-People/dp/0671708635'>"The 7 Habits of Highly Effective People"</a> .<br /></p><p><a href='http://www.youtube.com/watch?v=gRdfX7ut8gw'>Traditions!</a><br />			</p><ul><li>Creating good habits can be a highly effective tool of your Faith life. <br /></li><li>Bad Habits can lead you to a life of frustration.<br /></li></ul><p>As a group forms a habit it becomes a tradition. Christmas is a tradition. It's not biblical. There is no biblical precedent for celebrating the birth of Christ, nor did that event take place in December. However, as a nation and all western society we have gathered and set aside this day we call Christmas, to focus and remember God's greatest gift to mankind. <br /></p><p><br /> </p><p>    So then as I look at Matthew 12 I'm not surprised to see that Jesus is being attacked by the priests.  They are concerned about their traditions. But, sad to say, their traditions had made the word of God of no effect.  See:<br /></p><p><br /> </p><p><a href='http://www.biblegateway.com/passage/?search=Matthew+15&amp;version=NKJV'><h4><span style='color:blue; text-decoration:underline'>Matthew 15</span></h4></a><h4><br />				</h4></p><h5>Defilement Comes from Within<br /></h5><p> <sup>1</sup> Then the scribes and Pharisees who were from Jerusalem came to Jesus, saying, <sup>2</sup> "Why do Your disciples transgress the tradition of the elders? For they do not wash their hands when they eat bread."<br/><sup>3</sup> He answered and said to them, "Why do you also transgress the commandment of God because of your tradition? <sup>4</sup> For God commanded, saying, <em>'Honor your father and your mother'</em>;<sup>[<a title='See footnote a' href='http://www.biblegateway.com/passage/?search=Matthew+15&amp;version=NKJV'>a</a>]</sup> and, <em>'He who curses father or mother, let him be put to death.'</em><sup>[<a title='See footnote b' href='http://www.biblegateway.com/passage/?search=Matthew+15&amp;version=NKJV'>b</a>]</sup><br />				<sup>5</sup> But you say, 'Whoever says to his father or mother, "Whatever profit you might have received from me <em>is</em> a gift <em>to God</em>"— <sup>6</sup> then he need not honor his father or mother.'<sup>[<a title='See footnote c' href='http://www.biblegateway.com/passage/?search=Matthew+15&amp;version=NKJV'>c</a>]</sup><strong> Thus you have made the commandment<sup>[<a title='See footnote d' href='http://www.biblegateway.com/passage/?search=Matthew+15&amp;version=NKJV'>d</a>]</sup> of God of no effect by your tradition. <sup>7</sup> Hypocrites!</strong> Well did Isaiah prophesy about you, saying: <br/>       <br /></p><p>                                                                    <br /></p><p><strong><sup>8</sup><br />					<em>' These</em><br />					<em>people</em><br />					<em>draw near to Me with their mouth,</em><br/>      <em>And</em><sup>[<a title='See footnote e' href='http://www.biblegateway.com/passage/?search=Matthew+15&amp;version=NKJV'>e</a>]</sup><em>honor Me with</em><br />					<em>their</em><br />					<em>lips,</em><br/>      <em>But their heart is far from Me.</em><br/>       <sup>9</sup><br />					<em>And in vain they worship Me,</em><br/>      <em> Teaching</em><br />					<em>as</em><br />					<em>doctrines the commandments of men.'</em>"<sup>[<a title='See footnote f' href='http://www.biblegateway.com/passage/?search=Matthew+15&amp;version=NKJV'>f</a>]<br /></sup></strong></p><p><br /> </p><p>    So we look at this set of passages in Matthew 12 and find the same things going on.  Jesus is saying here:<br /></p><ul><li>Look here fellas, the traditions are fine sometimes, but let's get to the heart of the matter. Were men made for traditions or traditions made for men? You've turned the thing that was meant to bless into a curse. <br /></li></ul><p>Why do we have Church on Sunday? Because God said to? No… We have it then because that is the day that our culture has decided to set aside as the day to meet. MORE people are off work, even in today's fast paced, open late society, than on any other day. <br /></p><p><br /> </p><p>    There was a tradition of the middle age church to pray to saints. This was a bad tradition for we ought to pray to the Father. <br /></p><p>That is one adjustment my family has made this last year. <br /></p><p><br /> </p><ul><li>We do not pray, typically, to Jesus… <br /></li><li>WHAT?? How can you say that?!!<br /></li><li><div>Hold on a moment there… To be more effective in life and ministry you must examine EVERY tradition and see if it's based solely in the Word or is it someone's idea about the Word?<br /></div><ul><li>John 16:26-28<br /></li><li>John 17<br /></li><li><div>Matthew 6<br /></div><ul><li>Jesus tells us that we will ask the Father in His Name.<br /></li><li>Jesus says to pray like this: Our Father…<br /></li><li>Jesus says the Father love us<br /></li><li>Jesus says in John 17 that the Father loves us just as much as He does Jesus.<br /></li><li>Your Father in Heaven sees the birds…<br /></li><li><div>It is not ME but My FATHER who does the work in Me…<br /></div><ul><li>The Theme of Jesus Life is to introduce us to our Father.<br /></li></ul></li></ul></li></ul></li><li>The Father is NOT Jesus. They are separate persons but One God! There is a difference. Jesus is not my Father. He is my Friend, Brother, Co-Heir, Lord, Savior, Healer, Deliverer…etc… But His Father is My Father!<br /></li><li>I've been adopted with the FULL RIGHTS as a SON of God. Jesus paid my adoption fees.<br /></li><li>The Father LOVES me…<br /></li></ul><p><br /> </p><p><br /> </p><p><br /> </p><p><span style='font-size:16pt'><strong>Father, <br /></strong></span></p><p><span style='font-size:16pt'><strong>I lift this message to all who read it, may it be a lightening rod to shine a light on the path of those who have never prayed effective prayers. May they learn to be strategic, effective, and powerful in their prayer life! May this be the catalyst to find other traditions, in prayer and otherwise, that do not line up perfectly with the Word. I know you hear me, as a result I KNOW I have the things I ask for. I Believe, I Receive, I Take it, I Have it, I Thank You For it!<br /></strong></span></p><p><br /> </p><p style='margin-left: 36pt'><span style='font-size:16pt'><strong>In the Name of Jesus The Anointed One, Who's I am, and Whom I serve. BE IT DONE UNTO ME AS YOU HAVE SAID (Translation of: AMEN)!<br /></strong></span></p><p><br /> </p><p><span style='font-size:16pt'><strong>                            Darrell G. Wolfe<br /></strong></span></p><p><br /> </p><p><span style='font-size:16pt'><strong><br />					</strong></span> </p></span>