---
title: 'Amazing Grace for the Seeing Blind.'
date: '2010-04-20T04:17:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6770499742879021443'
blogger_filename: '/2010/04/amazing-grace-for-seeing-blind.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

John 9<br /><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">&nbsp;<sup class="versenum" id="en-NKJV-26438" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">1</sup>&nbsp;Now as&nbsp;<i>Jesus</i>&nbsp;passed by, He saw a man who was blind from birth.&nbsp;<sup class="versenum" id="en-NKJV-26439" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">2</sup>&nbsp;And His disciples asked Him, saying, “Rabbi, who sinned, this man or his parents, that he was born blind?”<br /><sup class="versenum" id="en-NKJV-26440" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">3</sup>&nbsp;Jesus answered, “Neither this man nor his parents sinned, but that the works of God should be revealed in him.&nbsp;<sup class="versenum" id="en-NKJV-26441" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">4</sup>&nbsp;I<sup class="footnote" style="font-size: 0.75em; line-height: 0.5em;" value="[&lt;a href=&quot;#fen-NKJV-26441a&quot; title=&quot;See footnote a&quot;&gt;a&lt;/a&gt;]">[<a href="http://www.blogger.com/post-create.g?blogID=6583916183087899714#fen-NKJV-26441a" title="See footnote a">a</a>]</sup>&nbsp;must work the works of Him who sent Me while it is day;&nbsp;<i>the</i>&nbsp;night is coming when no one can work.&nbsp;<sup class="versenum" id="en-NKJV-26442" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">5</sup>&nbsp;As long as I am in the world, I am the light of the world.”&nbsp;</span><br /><br /><br /><br /><br />This is not put well into&nbsp;English. I never understood this passage. How does this man being born blind glorify God? Does a Father break his&nbsp;children's&nbsp;legs just so he can show them a new splint technique He knows? That would NOT be an act of LOVE!<br /><br />What IS Jesus saying here?? WELL... there are no punctuation marks, or capitol letters in the Greek. Some person&nbsp;translating&nbsp;decided to add those for understanding. Therefore I can re-write those for better understanding.<br /><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">Answer:</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">Neither this man nor his parents sinned!</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">New Thought:</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">BUT that the works of God should be revealed in him,&nbsp;<sup class="versenum" id="en-NKJV-26441" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">4</sup>&nbsp;I<sup class="footnote" style="font-size: 0.75em; line-height: 0.5em;" value="[&lt;a href=&quot;#fen-NKJV-26441a&quot; title=&quot;See footnote a&quot;&gt;a&lt;/a&gt;]">[<a href="http://www.blogger.com/post-create.g?blogID=6583916183087899714#fen-NKJV-26441a" title="See footnote a">a</a>]</sup>&nbsp;must work the works of Him who sent Me while it is day. Night is coming when no one can work.&nbsp;<sup class="versenum" id="en-NKJV-26442" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">5</sup>&nbsp;As long as I am in the world, I am the light of the world.”&nbsp;</span><br /><br /><br />This is means that the works of God is restoration NOT lack.<br /><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><span class="Apple-style-span" style="font-size: 10px; font-weight: bold;">25...</span>"One thing I know: that though I was blind, now I see.”&nbsp;</span><br /><br />Amazing Grace... HOW SWEET THE SOUND!!!! That saved a wretch like me... I once was lost but now am found was BLIND but now I see!<br /><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><sup class="versenum" id="en-NKJV-26478" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">41</sup>&nbsp;Jesus said to them, “If you were blind, you would have no sin; but now you say, ‘We see.’ Therefore your sin remains.</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">What does this mean??</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">The think they see but don't because they are reject The Truth Himself. Therefore they are blind. I get that. HOW would they be without sin by being blind?&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">In the natural... A blind person knows they are blind. They don't look shocked when someone says: HEY BUDDY... You can't see!</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Wow... My My... Thanks for letting me know... I hadn't noticed... lol.</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">The spiritual blind person that&nbsp;recognizes&nbsp;any level of blindness in himself can&nbsp;receive&nbsp;the light of God and see. Only that one who comes to terms with "A wretch like me" can then go on to say "But now I see".&nbsp;</span><br /><br /><br />Darrell G. Wolfe<br /><br /><iframe align="left" frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?t=your0f4d-20&amp;o=1&amp;p=8&amp;l=bpl&amp;asins=B00127H6RA&amp;fc1=000000&amp;IS2=1&amp;lt1=_blank&amp;m=amazon&amp;lc1=0000FF&amp;bc1=000000&amp;bg1=FFFFFF&amp;f=ifr" style="align: left; height: 245px; padding-right: 10px; padding-top: 5px; width: 131px;"></iframe>