---
title: 'Spirit Led'
date: '2010-04-03T19:35:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2506997413858960053'
blogger_filename: '/2010/04/spirit-led.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"></span><br /><h4><a href="http://www.biblegateway.com/passage/?search=Luke%2022&amp;version=NKJV">Luke 22</a></h4><h5><span class="Apple-style-span" style="font-weight: normal;"><span class="Apple-style-span" style="font-size: medium;">&nbsp;</span></span><span class="Apple-style-span" style="font-weight: normal;"><span class="Apple-style-span" style="font-size: medium;"><sup class="versenum" id="en-NKJV-25868" style="font-weight: bold; line-height: normal; vertical-align: text-top;"><span class="Apple-style-span" style="font-size: medium;">7</span></sup>&nbsp;Then came the <b>Day of Unleavened Bread, when the Passover must be killed.</b>&nbsp;<sup class="versenum" id="en-NKJV-25869" style="font-weight: bold; line-height: normal; vertical-align: text-top;"><span class="Apple-style-span" style="font-size: medium;">8</span></sup>&nbsp;And He sent Peter and John, saying, “Go and prepare the Passover for us, that we may eat.”&nbsp;<sup class="versenum" id="en-NKJV-25870" style="font-weight: bold; line-height: normal; vertical-align: text-top;"><span class="Apple-style-span" style="font-size: medium;">9</span></sup>&nbsp;So they said to Him, “Where do You want us to prepare?”&nbsp;<sup class="versenum" id="en-NKJV-25871" style="font-weight: bold; line-height: normal; vertical-align: text-top;"><span class="Apple-style-span" style="font-size: medium;">10</span></sup>&nbsp;And He said to them, <b>“Behold, when you have entered the city, a man will meet you carrying a pitcher of water; follow him into the house which he enters.&nbsp;</b><sup class="versenum" id="en-NKJV-25872" style="line-height: normal; vertical-align: text-top;"><span class="Apple-style-span" style="font-size: medium;"><b>11</b></span></sup><b>&nbsp;Then you shall say to the master of the house, ‘The Teacher says to you, “Where is the guest room where I may eat the Passover with My disciples?”’</b>&nbsp;<sup class="versenum" id="en-NKJV-25873" style="font-weight: bold; line-height: normal; vertical-align: text-top;"><span class="Apple-style-span" style="font-size: medium;">12</span></sup>&nbsp;Then he will show you a large, furnished upper room; there make ready.”&nbsp;<sup class="versenum" id="en-NKJV-25874" style="font-weight: bold; line-height: normal; vertical-align: text-top;"><span class="Apple-style-span" style="font-size: medium;">13</span></sup>&nbsp;So they went and found it just as He had said to them, and they prepared the Passover.</span></span></h5><div><span class="Apple-style-span" style="font-weight: normal;"><span class="Apple-style-span" style="font-size: medium;"><br /></span></span></div><div><span class="Apple-style-span" style="font-weight: normal;"><span class="Apple-style-span" style="font-size: medium;">&nbsp;&nbsp; &nbsp; On the busiest day of the year Jesus and more than 12 people with Him had a room reserved and provided for Him. That is Favor! He was also able to give detailed instructions of what they would find and what would happen. Only through a lifestyle of prayer can this type of foreknowledge and Spiritual&nbsp;wisdom&nbsp;be a daily lifestyle for the believer.&nbsp;</span></span></div><div><span class="Apple-style-span" style="font-weight: normal;"><span class="Apple-style-span" style="font-size: medium;"><br /></span></span></div><div><span class="Apple-style-span" style="font-weight: normal;"><span class="Apple-style-span" style="font-size: medium;">&nbsp;&nbsp; &nbsp; I believe to today I will develop a lifestyle of prayer to obtain the level of understanding, insight, wisdom, and spirit led life that is needed to walk in all He has for us!</span></span></div><div><span class="Apple-style-span" style="font-weight: normal;"><span class="Apple-style-span" style="font-size: medium;"><br /></span></span></div><div><span class="Apple-style-span" style="font-weight: normal;"><span class="Apple-style-span" style="font-size: medium;">Darrell G. Wolfe</span></span></div>