---
title: 'The Will of God to Heal'
date: '2010-01-13T04:04:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2871207464842621198'
blogger_filename: '/2010/01/the-will-of-god-to-heal.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

01/12/2009 <br />Mathew 8<br />:2-3<br />Once and for all Jesus sets the record straight on His will. If you are willing? I AM WILLING! It has never about His willingness but about your capacity to recieve.<br /><br />:8-13<br />Jesus comments that the GREAT faith he found here is one that says: I don't need you to come, I don't need to see, I just need you to say it and I'll call that done!<br /><br />:16 Jesus drives out demons... how does He do it? Does he kick them out with His foot? Does He beat them without His hand? Does He tell them to lay out a fleese and see if God is really willing to deliver? No...<br /><br />Jesus Drives Demons Out: WITH HIS WORD! And so it is for every believer, it is by the words of your mouth that you are Justified... made right... completed...<br /><br />:17-18<br />Isaiah 53 is qouted by Mathew here. MANY comment and say that Isaiah 53 is just talking about "spiritual" healing of the soul and that it is not a promise for devine healing of the body. Apparently someone forgot to tell Matthew. According to Matthew Isaiah 53 says that Jesus is our healer! If you need healing today, use your words like He's been teaching the whole chapter and take it.<br /><br />:26<br />Jesus has spent time telling them how important words are by pointing out the GREAT Faith... He showed them by casting out devils with His words... NOW The disciples come to him with a storm.<br /><br />Keep in mind... These are fishermen... They've weathered storms before and spent their whole lives on boats. Most of these men have seen enough storms to sleep through them themselves. THIS storm is qouted in another recording to be a GREAT storm also translated MEGA storm. It's got these seasoned professionals FREAKED OUT!<br /><br />Do they:<br />A. Cast the storm down themselves and let Him sleep.<br /><br />B. Go to Jesus and say: "Master... hey there, excuse me... we have a fairly bad storm here, worse we've ever seen. Would you mind helping us deal with this, we know you have the answer.<br /><br />C. Run crying and screaming and blaming Him for sleeping thereby questioning His will and intentions when they say: "Don't you care that we're dying here?"<br /><br />The answer:<br />C.<br /><br />What did JESUS expect them to do?<br />"What's wrong with you boys, why are you such cowards with little puny faith!"<br />Jesus expected A. or AT LEAST B.<br /><br />Then they get to the <a href="http://www.bible-history.com/smiths/G/Gadarenes%2C+Girgesenes%2C+Gerasenes/"><b><span style="font-size: small;">Gadarenes</span></b></a>, find two demon possessed men and cast the devils out and the people ask Him to leave...<br /><br />My question:<br />WHY did Jesus let them take the pigs? DID Jesus LET them take the pigs?<br /><br />After considering this a moment I realized. These people are not covenant people. They are on the border of Israel and Persia. They are raising pigs which is not a Jewish thing to do as they are unclean animals. If they are Jewish they're not living it.<br /><br />Their reaction to Jesus afterward already shows us they are resistant to the Gospel.<br /><br />Moreover, demons have every right to deal with animals and people that are not covered by the covenant, or not living in line with it. Jesus, prior to his death and ressurection couldn't tell them NOT to go into the pigs. Therefore He didn't give them permission other than that He didn't stop them...<br /><br />Also interesting... The pigs had more sense than the two men. The pigs knew better than to live with demons and ran off and killed themselves! Sometimes animals knows things humans don't know!<br /><br />So Jesus Showed us the power of words, faith vs doubt, and how to walk in correct authority. You don't cross lines you don't have the right to. COULD Jesus have said: "Go to hell and be bound for a thousand years!" I've heard people say that in prayer... I think if He could he would have... but the demons themselves point out something here... "Have you come to torment us before the appointed time?"<br /><br />There has been a time set and appointed for Demon Judgment. For whatever reasons God has allowed them to come to earth, and then Adam gave them His authority. Jesus took it back and gave it to us. So we walk in the very same authority granted to Adam in Gen 1:28 now. Those who are outside of Christ do not though. Here in lies the battle.<br /><br />There are two laws at work in the earth.<br /><ul><li>The Law of the Spirit of Life. <br /></li></ul><ul><li>The Law of Sin and Death.&nbsp;</li></ul><br />You must choose which you will participate in.<br /><br /><b><a href="http://www.biblegateway.com/passage/?search=Romans+8:2&amp;version=NIV">Romans 8:2</a></b><br />because through Christ Jesus the <b>law of the Spirit</b> of life set me free from the law of sin and death.<br /><br /><br /><ol class="keyword-result-list" start="1"><li><b><a href="http://www.biblegateway.com/passage/?search=Deuteronomy+30:19&amp;version=NIV">Deuteronomy 30:19</a></b><br />This day I call heaven and earth as witnesses against you that I have set before you <b>life and death</b>, blessings and curses. Now choose life, so that you and your children may live<br /><a href="http://www.biblegateway.com/passage/?search=Deuteronomy+30:18-20&amp;version=NIV">Deuteronomy 30:18-20</a> (in Context)  <a href="http://www.biblegateway.com/passage/?search=Deuteronomy+30&amp;version=NIV">Deuteronomy 30</a> (Whole Chapter)  </li><li><b><a href="http://www.biblegateway.com/passage/?search=Proverbs+18:21&amp;version=NIV">Proverbs 18:21</a></b><br />The tongue has the power of <b>life and death</b>,  and those who love it will eat its fruit.<br /><a href="http://www.biblegateway.com/passage/?search=Proverbs+18:20-22&amp;version=NIV">Proverbs 18:20-22</a> (in Context)  <a href="http://www.biblegateway.com/passage/?search=Proverbs+18&amp;version=NIV">Proverbs 18</a> (Whole Chapter)&nbsp;</li><li><b><a href="http://www.biblegateway.com/passage/?search=Matthew+12:36&amp;version=NKJV">Matthew 12:36</a></b><br />But I say to you that for every <b>idle word</b> men may speak, they will give account of it in the day of judgment.<br /><a href="http://www.biblegateway.com/passage/?search=Matthew+12:35-37&amp;version=NKJV">Matthew 12:35-37</a> (in Context)  <a href="http://www.biblegateway.com/passage/?search=Matthew+12&amp;version=NKJV">Matthew 12</a> (Whole Chapter)  </li> <ol><li><br /><h2 id="passage_heading">Matthew 12:35-37&nbsp;(New King James Version)</h2><sup class="versenum" id="en-NKJV-23521">35</sup> A good man out of the good treasure of his heart<sup class="footnote" value="[&lt;a href=&quot;#fen-NKJV-23521a&quot; title=&quot;See footnote a&quot;&gt;a&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=Matthew+12:35-37&amp;version=NKJV#fen-NKJV-23521a" title="See footnote a">a</a>]</sup> brings forth good things, and an evil man out of the evil treasure brings forth evil things. <sup class="versenum" id="en-NKJV-23522">36</sup> But I say to you that for every idle word men may speak, they will give account of it in the day of judgment. <sup class="versenum" id="en-NKJV-23523">37</sup> For by your words you will be justified, and by your words you will be condemned.”<br /><br /></li></ol></ol>