---
title: 'ABIDING is not passive...'
date: '2010-04-17T12:31:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1767870799968138981'
blogger_filename: '/2010/04/abiding-is-not-passive.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=john%208&amp;version=NKJV">John 8</a><br /><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><sup class="versenum" id="en-NKJV-26409" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">31</sup>&nbsp;Then Jesus said to those Jews who believed Him, “If you abide in My word, you are My disciples indeed.&nbsp;<sup class="versenum" id="en-NKJV-26410" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">32</sup>&nbsp;And you shall know the truth, and the truth shall make you free.”&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">How does one KNOW INTIMATELY anyone, anything, or any subject? He or she must spend time with it/that person! Take music for example.&nbsp;</span><br /><br /><ul><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">I could spend months sitting in the same room as my guitar and never become familiar with how it works.&nbsp;</span></li><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">I could spend time listening to someone play guitar either live or recorded and it may give me one step more familiarity, at least I know how it sounds.</span></li><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">I could pick it up and strum it every so often and play what I already know how to play... that would build familiarity around those songs and skills.&nbsp;</span></li></ul><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">But If I am ever to become intimately familiar with the guitar, not just A guitar but MY GUITAR specifically...</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span></div><div><ul><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">I must spend time playing it as often as possible.</span></li><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">I must spend time reading and learning about things I didn't know about it.</span></li><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">I must learn and&nbsp;practice&nbsp;NEW techniques and skills.&nbsp;</span></li><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">I must be purposeful in my time with the guitar to become proficient.&nbsp;</span></li></ul><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span></div></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Therefore I must spend time with HIS word, not just reading...</span></div><div><ul><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Read it</span></li><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Think about it</span></li><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Ask questions about it</span></li><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Pray about it with purpose</span></li><li><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Repeat all this over and over throughout each day.</span></li></ul><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span></div></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">I can't just put my bible down and forget what I read. That is NOT abiding.&nbsp;</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">I must think about what I've been reading throughout the day, ask myself how I'm going to change or grow according to and consistent with what I read. In between calls and tasks and duties... Meditate on that word....</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Darrell G. Wolfe</span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><iframe align="left" frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?t=your0f4d-20&amp;o=1&amp;p=8&amp;l=bpl&amp;asins=157683655X&amp;fc1=000000&amp;IS2=1&amp;lt1=_blank&amp;m=amazon&amp;lc1=0000FF&amp;bc1=000000&amp;bg1=FFFFFF&amp;f=ifr" style="align: left; height: 245px; padding-right: 10px; padding-top: 5px; width: 131px;"></iframe></span></div><div><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span></div>