---
title: 'Running From or To?'
date: '2010-11-30T04:32:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2055606232988480648'
blogger_filename: '/2010/11/running-from-or-to.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

&nbsp;&nbsp;&nbsp;&nbsp; I've heard Kenneth Copeland say several times over the last few years: "When you sin run TO God not FROM him! Your sin is none of the Devils' Business!" I've been thinking about this idea of "From" and "To".<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; Don't plan to retire FROM your job... retire TO a new and higher level of living and purpose and drive! Otherwise you rot away from boredom.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; Don't try to get a promotion FROM the position you don't like right now... you'll just end up with another position you want to get FROM again. I spent years running FROM one job to another "Greener" job that wasn't so Greener.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; When looking for your next place, house, job, task, goal... etc... look to ensure that your motive is seeking God to move in TO his next plan for you and not just FROM where you are. There is a profound difference! Even the right move with the wrong foundation will cause serious delays and detours.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DW<br /><br /><br /><br /><br /><br /><h1 class="Title"><span style="font-size: small;"><a href="http://www.biblestudytools.com/kjv/jeremiah/1.html">Jeremiah 1</a></span></h1><br /><span class="versetext" id="jer1-3" style="display: inline;">   </span>           <span class="versetext" id="jer1-4" style="display: inline;"><span class="versenum">4</span>     Then the <span class="strongs">word</span> of the <span class="strongs">LORD</span> came unto me, <span class="strongs">saying</span> ,    </span>           <span class="versetext" id="jer1-5" style="display: inline;"><span class="versenum">5</span>     <span class="strongs">Before</span> I <span class="strongs">formed</span>  thee in the <span class="strongs">belly</span> I <span class="strongs">knew</span>  thee; and before thou camest <span class="strongs">forth</span>  out of the <span class="strongs">womb</span> I <span class="strongs">sanctified</span>  thee, and I <span class="strongs">ordained</span><a href="" name="a"></a>  thee a <span class="strongs">prophet</span> unto the <span class="strongs">nations.</span>    </span>           <span class="versetext" id="jer1-6" style="display: inline;"><span class="versenum">6</span>     Then <span class="strongs">said</span>  I, <span class="strongs">Ah,</span> <span class="strongs">Lord</span> <span class="strongs">GOD!</span> behold, I <span class="strongs">cannot</span>  <span class="strongs">speak</span> : for I am a <span class="strongs">child.</span>    </span>           <span class="versetext" id="jer1-7" style="display: inline;"><span class="versenum">7</span>     But the <span class="strongs">LORD</span> <span class="strongs">said</span>  unto me, <span class="strongs">Say</span>  not, I am a <span class="strongs">child:</span> for thou shalt <span class="strongs">go</span>  to all that I shall <span class="strongs">send</span>  thee, and whatsoever I <span class="strongs">command</span>  thee thou shalt <span class="strongs">speak</span> .    </span>           <span class="versetext" id="jer1-8" style="display: inline;"><span class="versenum">8</span>     Be not <span class="strongs">afraid</span>  of their <span class="strongs">faces:</span> for I am with thee to <span class="strongs">deliver</span>  thee, <span class="strongs">saith</span>  the <span class="strongs">LORD.</span>    </span>           <span class="versetext" id="jer1-9" style="display: inline;"><span class="versenum">9</span>     Then the <span class="strongs">LORD</span> put <span class="strongs">forth</span>  his <span class="strongs">hand,</span> and <span class="strongs">touched</span>  my <span class="strongs">mouth.</span> And the <span class="strongs">LORD</span> <span class="strongs">said</span>  unto me, Behold, I have <span class="strongs">put</span>  my <span class="strongs">words</span> in thy <span class="strongs">mouth.</span>    </span>           <span class="versetext" id="jer1-10" style="display: inline;"><span class="versenum">10</span>     <span class="strongs">See</span> , I have this <span class="strongs">day</span> <span class="strongs">set</span>  thee over the <span class="strongs">nations</span> and over the <span class="strongs">kingdoms,</span> to root <span class="strongs">out</span> , and to pull <span class="strongs">down</span> , and to <span class="strongs">destroy</span> , and to throw <span class="strongs">down</span> , to <span class="strongs">build</span> , and to <span class="strongs">plant</span> .    </span>           <span class="versetext" id="jer1-11" style="display: inline;"><span class="versenum">11</span>     Moreover the <span class="strongs">word</span> of the <span class="strongs">LORD</span> came unto me, <span class="strongs">saying</span> , <span class="strongs">Jeremiah,</span> what <span class="strongs">seest</span>  thou? And I <span class="strongs">said</span> , I <span class="strongs">see</span>  a <span class="strongs">rod</span> of an almond <span class="strongs">tree.</span>    </span>           <span class="versetext" id="jer1-12" style="display: inline;"><span class="versenum">12</span>     Then <span class="strongs">said</span>  the <span class="strongs">LORD</span> unto me, Thou hast <span class="strongs">well</span>  <span class="strongs">seen</span> : for I will <span class="strongs">hasten</span>  my <span class="strongs">word</span> to <span class="strongs">perform</span>  it.    </span>