---
title: 'Untitled Post'
date: '2010-03-24T02:49:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '783868481560094213'
blogger_filename: '/2010/03/luke-14-25-now-great-multitudes-went.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=Luke%2014&amp;version=NKJV">Luke 14</a><br /><br /><i><sup class="versenum" id="en-NKJV-25575">25</sup> Now great multitudes went with Him. And He turned and said to them, <sup class="versenum" id="en-NKJV-25576">26</sup> “If anyone comes to Me and does not <b>hate</b> his father and mother, wife and children, brothers and sisters, yes, and his own life also, he cannot be My disciple.&nbsp;<sup class="versenum" id="en-NKJV-25577"></sup></i><br /><br />&nbsp; &nbsp; &nbsp; Jesus is not here telling us to HATE if He says we must LOVE right? There is a matter of degree. Have you ever taken a drink of tea but thought you drinking coke? Did it taste awful, even though you like that tea? Or even one soda but another in mind because you grabbed your friends glass?<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; In that context you hated that drink you might otherwise like a lot. In comparison to everything and everyone else, God and He alone, must be your first and only love. Your love for others does not come second to your love for Him. It comes through your love for Him. You have no love for others, not true agape love, without loving them through Him. All love outside of His love becomes destructive. Passion turns to lust, protection becomes smothering.<br /><br /><br />&nbsp;&nbsp;&nbsp;&nbsp; And as My wife pointed out as we were talking this over just now, SLEEP is NOT first place. If God calls you to pray early in the morning, do you roll over and go back to bed or do you get up and pray? Never say that you are "Not a morning person." All you do is set your mind and body up to decide that you are unavailable to be used of God in the morning. <br /><br />&nbsp;&nbsp;&nbsp;&nbsp; <b>Ask yourself this question today:</b><br /><b><br /></b><br /><i><b>"What am I allowing to take first place above God in my life?"&nbsp;</b></i><br /><b><br /></b><br /><b>&nbsp;&nbsp;&nbsp;&nbsp; If you can truly answer: <i>"Nothing."</i>&nbsp;</b><br /><br /><b>Than you are truly blessed. Strive after, aim at, and press toward that goal. </b><br /><br />&nbsp;Darrell G. Wolfe