---
title: 'Mens Meetings Golden Corral 9 AM'
date: '2010-12-08T14:06:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8586218808854241667'
blogger_filename: '/2010/12/mens-meetings-golden-corral-9-am.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

Men's Meeting<br />Saturday12-4-2010<br />9AM Golden Corral<br /><br /><a href="http://www.biblegateway.com/passage/?search=3%20John%201:2&amp;version=NKJV">3 John 1:2</a><br />Prosper in ALL things...<br /><br />We must learn to be dependent on God. As men we are often speaking about our Independence, but Godly men are DEPENDENT. We are not alone and do not do things in our own strength. We are NOT Self-Made-Men.<br /><br /><a href="http://www.biblegateway.com/passage/?search=mark%204:13-20&amp;version=NKJV">Mark 4:13-20</a> points out the key areas that keep us from being productive for God. <br /><ol><li>Cares</li><ol><li>The things that weigh on our mental energy, bills, clothes, food, housing, gas for the car, etc. </li></ol><li>Deceit</li><ol><li>The lie that MONEY will solve the problem.</li><ol><li>If only I got that raise, promotion, new job... that would fix everything...</li></ol></ol><li>Lusts</li><ol><li>Lust is pressure.&nbsp;</li><ol><li>Pressure of wanting something</li><li>Pressure to get it at any cost</li><li>Pressure to abandon God's ways in order to get it.&nbsp;</li></ol></ol></ol>1st instance of the word "Thorns" in the bible is in <a href="http://www.biblegateway.com/passage/?search=genesis%203:17-18&amp;version=NKJV">Genesis 3:17-18</a>.<br /><br /><span style="font-size: x-small;"><i><br /></i></span><br /><br /><span style="font-size: small;"><i><sup class="versenum" id="en-NKJV-73">17</sup> Then to Adam He said,  “Because you have heeded the voice of your wife, and have eaten from  the tree of which I commanded you, saying, ‘You shall not eat of it’:       <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;“ <b>Cursed </b></i><i>is the ground for your sake;  <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In toil you shall eat </i><i>of it  <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;All the days of your life.</i></span><br /><span style="font-size: small;"><i>&nbsp;<sup class="versenum" id="en-NKJV-74">18</sup>  Both <b>thorns </b>and thistles it shall bring forth for you,<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;And you shall eat the herb of the field.</i></span><br /><br /><br />Work became hard and irritating because of the curse. However we are not bound to the curse any longer. Jesus redeemed us from the curse.<br /><br />&nbsp;Things come according to the level of and direction of our expectation.<br /><br />&nbsp;Expect = Come<br /><br />LOVE God loves us.... God loves us.... GOD LOVES US!!!! In <a href="http://www.biblegateway.com/passage/?search=Genesis+1&amp;version=NKJV">Genesis 1 </a><br /><br />In Ancient Hebrew Language there were NO CAPITOLS, Punctuations (!@#$%^&amp;*), <b>BOLD</b>, <i>ITALIC</i>, <span style="background-color: yellow;">yellow </span>or <span style="background-color: magenta;">pink </span>highlighters...<br /><br />The Ancient Hebrews used a language technique to point out something within a text. This was their version of highlighting something they wanted you to see. They started with reapeating lines followed by a break from the repeat. This break from the pattern is the JUMP OFF THE PAGE LOOK AT THIS!!!<br /><br />You can see this through <a href="http://www.biblegateway.com/passage/?search=1%20Chronicles+4&amp;version=NIV">1 Chronicles 4</a>. So and so begat so and so begat so and so... <i style="background-color: yellow;"><b>JABEZ was more honorable</b></i>...<br /><br /><sup class="versenum" id="en-NKJV-3">3</sup> Then God said, “<b>Let there</b> be<br /><sup class="versenum" id="en-NKJV-4">4</sup> And God saw<br /><sup class="versenum" id="en-NKJV-6">6</sup> Then God said, “<b>Let there</b> be<br /><sup class="versenum" id="en-NKJV-7">7</sup> Thus God made<br /><sup class="versenum" id="en-NKJV-9">9</sup> Then God said, “<b>Let the</b> waters<br />And God saw that <i>it was</i> good.<br /><sup class="versenum" id="en-NKJV-11">11</sup> Then God said, “<b>Let the</b> earth<br />And God saw<br />............. <br /><br />&nbsp; <sup class="versenum" id="en-NKJV-26">26</sup> Then God said, “<u style="background-color: yellow;"><i><b>Let Us</b></i></u> make man in Our image<br /><br />Hear the Passion of God in this set up... God said let THE.... over and over... but not Man... No with man... LET US!!!!! It's as if God is saying WAIT.... LOOOK.... CHECK THIS OUT.... I'm going to jump in and get PERSONAL with this one.<br /><br />We see in <a href="http://www.biblegateway.com/passage/?search=Genesis+2&amp;version=NKJV">Genesis 2</a> that God personally got involved in forming man. <br /><sup class="versenum" id="en-NKJV-38">7</sup> And the<b> LORD God formed man</b> <i>of</i> the dust of the ground, and breathed into his nostrils the breath of life; and man became a living being.<br /><sup class="versenum" id="en-NKJV-39">8</sup> The LORD God planted a garden eastward in Eden, and there He put the man <b>whom He had formed.</b> <br /><br />Can you see Jesus on his hands and knees in the dust of His new earth creation and forming man as a sculptor forms a fine crafted statue? He takes his creation so personal that he breathes his OWN breath and spirit into him.<br /><br /><b>Clothing </b><br />He takes it so personal... that after the fall when Man had tried to clothe himself in inadequate leaves God killed the first animal to clothe Man and provide for him better than He chose for himself. <br /><br />To this day Fallen Man's mind tries to provide for himself less and God is endeavoring to raise man's eyes to HIM as provider. God always wants better for us than we want for ourselves. <br /><br /><b><a href="http://www.biblegateway.com/passage/?search=Galatians+3:13&amp;version=NKJV">Galatians 3:13</a></b><br /><i>Christ has <b>redeemed us from</b> the curse of the law, having become a curse for us...</i> <br /><br />We do not work FOR a living. We work to be fruitful and multiply! <a href="http://www.biblegateway.com/passage/?search=Gen%201:28&amp;version=NIV">Gen 1:28</a><br /><br /><b><a href="http://www.biblegateway.com/passage/?search=Ephesians+4:28&amp;version=NKJV">Ephesians 4:28</a></b><br />Let him who stole steal no longer, but rather let him labor, working with his <b>hands</b> what is good, that he may have something to <b>give</b> him who has need.<br /><br />God Peels us as onions, just let the old dried crust fall off. Don't get into condemnation over it. Just let it go. Paul called this old stuff DUNG... Animal poo... Just let it go and move on. No need to feel bad when He points out something that needs to change. Just change... and move on freer and happier. <br /><br /><br />God made an animal to carry burdens. It's called a Jack-Ass. When we try to carry our own burdens by saying "I'll take care of this"... we make ourselves a Jack-Ass.