---
title: 'The Life of God... Decision is yours'
date: '2010-04-13T01:42:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4712679886355349421'
blogger_filename: '/2010/04/the-life-of-god-decision-is-yours.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=John%204&amp;version=NKJV">John 4</a><br /><br />31 In the meantime His disciples urged Him, saying, “Rabbi, eat.” <br />32 But He said to them, “I have food to eat of which you do not know.”<br />33 Therefore the disciples said to one another, “Has anyone brought Him anything to eat?”<br />34 Jesus said to them, “<b>My food is to do the will of Him who sent Me, and to finish His work</b>. 35 Do you not say, ‘There are still four months and then comes the harvest’? Behold, I say to you, lift up your eyes and look at the fields, for they are already white for harvest! 36 And he who reaps receives wages, and gathers fruit for eternal life, that both he who sows and he who reaps may rejoice together. 37 For in this the saying is true: ‘One sows and another reaps.’ 38 I sent you to reap that for which you have not labored; others have labored, and you have entered into their labors.”...<br />...47 When he heard that Jesus had come out of Judea into Galilee, he went to Him and implored Him to come down and heal his son, for he was at the point of death. 48 Then Jesus said to him, “Unless you people see signs and wonders, you will by no means believe.”<br />49 The nobleman said to Him, “Sir, come down before my child dies!”<br />50 Jesus said to him, “Go your way; your son lives.”<b> So the man believed the word that Jesus spoke to him, and he went his way. 51 And as he was now going down, his servants met him and told him, saying, “Your son lives!”</b><br />52 Then he inquired of them the hour when he got better. And they said to him, “Yesterday at the seventh hour the fever left him.” 53 So the father knew that it was at the same hour in which Jesus said to him, “Your son lives.” And he himself believed, and his whole household.<br />54 This again is the second sign Jesus did when He had come out of Judea into Galilee.<br /><br /><br /><br />04/12/10: My Utmost for His Highest<br /><span class="Apple-style-span" style="color: #555555; font-family: verdana, geneva, sans-serif; font-size: 17px; line-height: 25px;"><a href="http://www.utmost.org/">If it is difficult to get right with God, it is because we refuse to make this moral decision about sin. But once we do decide, the full life of God comes in immediately.</a></span><br /><br />There is a theme for today... that theme is DECISION! You decide to believe. You decide to do His will. You decide to be dead to sin so that HE may live in you. It's not just the some of God's life in you... it is GOD HIMSELF in you! That is the key. It's not "Lord what can I do for you today?" It's "Lord, do something THROUGH me today. I'll just take ME out of the equation!"<br /><br />Questions to ask:<br /><br /><ul><li>What is YOUR will today?</li><li>What is YOUR plan today?</li><li>What would you like me to accomplish today?</li><li>Who needs a touch from you through me today?</li><li>How can I bring peace and rest today?</li><li>How can I bring LOVE into the situation?</li></ul><div>Darrell G. Wolfe</div>