---
title: 'Blessing Without Measure!'
date: '2010-01-02T04:05:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5077818726407975905'
blogger_filename: '/2010/01/blessing-without-measure.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

12/31/2009<br /><br />&nbsp; &nbsp;&nbsp; As I look at the end of 2009 and the beginning of 2010 I open my bible to the daily reading, Revelations 22. I find this: <br /><h4><i>Revelation 22</i></h4><i><sup class="versenum" id="en-NKJV-31078">1</sup> And he showed me a pure river of water of life, clear as crystal, proceeding from the throne of God and of the Lamb. <sup class="versenum" id="en-NKJV-31079">2</sup> In the middle of its street, and on either side of the river, </i><i>was<b> the tree of life</b>, <b>which bore twelve fruits, each </b></i><i><b>tree yielding its fruit every month</b>. The leaves of the tree </i><i>were for the <b>healing of the nations.</b></i><br /><br />Which got me thinking... that sounds a lot like:<i><b> <br /></b></i><br /><h2 id="passage_heading"><span style="font-size: small;"><i>Genesis 1:28-29 </i></span></h2><span style="font-size: small;"><i><sup class="versenum" id="en-NKJV-28">28</sup> Then God blessed them, and God said to them, “Be <b>fruitful</b> and multiply; fill the earth and subdue it; have dominion over the fish of the sea, over the birds of the air, and over every living thing that moves on the earth." <sup class="versenum" id="en-NKJV-29">29</sup> And God said, “<b>See, I have given you </b>every herb </i><i>that yields <b>seed</b> which </i><i>is on the face of all the earth, and <b>every tree whose fruit yields seed</b>; to you it shall be for food.</i></span> <br /><i><b></b></i><i><span style="font-size: small;">&nbsp;</span>&nbsp; <br /></i><br /><i>&nbsp;<a href="http://www.biblegateway.com/passage/?search=Revelations%2022:1-2&amp;version=NKJV">Pasted From: Bible Gateway</a></i><br /><br /><br /><br /><br />&nbsp; &nbsp;&nbsp; As book ends to accentuate the shelf, God places the first and last books of the bible to accentuate the story of man. The LORD God, the Begging-End, Alpha-Omega lays out His PERFECT will for mankind in the beginning of His love letter to us. He ends the love letter by reminding us what His PERFECT will is again. What is God's will? What is His PERFECT will? <br /><br />&nbsp; &nbsp;&nbsp; <b>SHALOM! Nothing Missing, Nothing Broken, Everything Whole and Complete!&nbsp;</b><br /><span style="font-size: small;"><i>&nbsp;&nbsp;&nbsp;</i>&nbsp;&nbsp;</span><br /><span style="font-size: small;">&nbsp; &nbsp;&nbsp; God's will is, was, always will be SHALOM, Dominion, Provision, Healing, Prosperity, Victory, Overcoming! </span><br /><h2 id="passage_heading" style="text-align: center;"><span style="font-size: small;"><i>&nbsp;Matthew 6:10 </i></span></h2><div style="text-align: center;">&nbsp;<span style="font-size: small;"><i><sup class="versenum" id="en-NKJV-23289">10</sup>  Your kingdom come.    </i></span><br /><span style="font-size: small;"><i>&nbsp; <b>Your will</b> be done  </i></span><br /><span style="font-size: small;"><i>&nbsp; On earth <b>as </b></i><i><b>it is in heaven</b>.  </i></span></div><div style="text-align: center;">&nbsp;&nbsp;&nbsp;&nbsp; <br /></div><br /><br />&nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; God has always intended for man to <b>be fruitful</b>, multiply, replenish the earth, and put down things that get out of order. Which can be summarized as "<b>Have Dominion</b>!" I am a child of God! Jesus paid my debt on the cross and bought my right of way back into the blessing! Just as the Tree of Life I should <b>bear fruit EVERY month</b> of 2010, not just a little either. I should be <b>increasing more and more</b> in the things of God. 2010 will have challenges yes, and I will face them in faith! I will seek the answers to each and every situation, opportunity, and decision <b>fighting FROM victory</b>, not for it!<br /><br /><br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The Blessing without Measure, in 2010!!!