---
title: 'They don&#39;t get it!'
date: '2010-01-16T02:43:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '546372397790028999'
blogger_filename: '/2010/01/they-don-get-it.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

01/15/2010<br /><a href="http://www.blogger.com/goog_1263608941009"><br /></a><br /><a href="http://www.biblegateway.com/passage/?search=Matthew%2011&amp;version=NKJV">Matthew 11</a><br /><br />John the Baptist is THE forerunner of Jesus! His entire calling, by God, in life is to prepare the way of Jesus. If anyone should "GET" what Jesus is about it's John.<br /><br />Here he is in prison doubting and confused.<br /><br />Not everyone is going to "get" you. Few, if any, will ever come close to understanding your calling and gifting to the body. Many will "get" aspects of it. One would expect that your spouse, if you married who God told you to marry, would "get" you for the most part. People in general, especially folks bound in religion, won't "get" you sometimes.<br /><br />What can you do? What is Jesus example to us when questioned about our life, calling, or intentions?<br /><br />Jesus says:<br /><ul><li>Be Kind</li><li>Point to the fruit!</li></ul>Then Jesus goes on to say something remarkable. I've never seen this before in reading this chapter.<br /><br />"...if you are willing to receive it, he is Elijah who is to come..."<br /><br />In other words... you may or may not receive the gift God brought to you in your life in the form of a teacher, mentor, etc. God gave <a href="http://www.biblegateway.com/passage/?search=Ephesians+4:11&amp;version=NKJV">gifts </a>to the body of Christ in the form of Apostles, Prophets, Evangelists, Pastors, and Teachers. A gift must be received. Otherwise it can be no benefit for you.&nbsp; <br /><br />When I first met Flavia I was saying things like: "Those name if and claim it people..." and I'd go on and complain about them. So she gives me a 2001 Southwest Believers Convention mp3. I listened to Kenneth Copeland and know from the first hearing that I need what this guy has. <br /><br />What happened? I hadn't received from them. Until I was introduced to KCM I didn't know them from anyone else. Others obviously had chosen to reject them, deceived as they were to do so. They didn't receive either. The only ones who received were the ones who believed and received the message. <br /><br />Not everyones going to get you... your not going to get everyone else. Stick to what you know about what God's told you and leave everyone else alone. When you are questioned:<br /><ul><li>Be Kind</li><li>Point to the Fruit!<br /></li></ul>