---
title: 'Hear and Obey... Water becomes Wine!'
date: '2010-04-09T04:35:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7991304375541822744'
blogger_filename: '/2010/04/hear-and-obey-water-becomes-wine.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=John%202&amp;version=NKJV">John 2</a><br /><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><sup class="versenum" id="en-NKJV-26097" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">5</sup>&nbsp;His mother said to the servants, “Whatever He says to you, do&nbsp;<i>it.</i>”<br /><sup class="versenum" id="en-NKJV-26098" style="font-size: 0.65em; line-height: normal; vertical-align: text-top;"><b>6</b></sup><b>&nbsp;Now there were set there six waterpots of stone</b>, according to the manner of purification of the Jews, containing twenty or thirty gallons apiece.&nbsp;<sup class="versenum" id="en-NKJV-26099" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">7</sup>&nbsp;Jesus said to them, “<b>Fill the waterpots with water.</b>” And <b>they filled them up to the brim</b>.&nbsp;<sup class="versenum" id="en-NKJV-26100" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">8</sup>&nbsp;And He said to them, <b>“Draw&nbsp;</b><i><b>some</b></i><b>&nbsp;out now, and take&nbsp;</b><i><b>it</b></i><b>&nbsp;to the master of the feast.” And they took&nbsp;</b><i><b>it.</b></i>&nbsp;<sup class="versenum" id="en-NKJV-26101" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">9</sup>&nbsp;When the master of the feast had tasted the water that was made wine, and did not know where it came from (but the servants who had drawn the water knew), the master of the feast called the bridegroom.&nbsp;<sup class="versenum" id="en-NKJV-26102" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">10</sup>And he said to him, “Every man at the beginning sets out the good wine, and when the&nbsp;<i>guests</i>&nbsp;have well drunk, then the inferior. <b>You have kept the good wine until now!</b>”&nbsp;<sup class="versenum" id="en-NKJV-26103" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">11</sup>&nbsp;This beginning of signs Jesus did in Cana of Galilee, and manifested His glory; and His disciples believed in Him.&nbsp;<sup class="versenum" id="en-NKJV-26104" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">12</sup>&nbsp;After this He went down to Capernaum, He, His mother, His brothers, and His disciples; and they did not stay there many days.</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">Jesus here tells the people to use the water used for cleansing. This is the DISH WATER... This is the water used to wash dishes and hands and feet... EWWW...&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">Yet this water becomes the BEST wine!</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">Listen and Obey HIM... NO MATTER WHAT He says or HOW silly it is.&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">The Results will always be amazing in the end.&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">This makes me think about my own provision. How often have I wanted to do something BIG for God but I'm too wrapped up in my current problems or situations. He asks me to write Him a story or work on a book. But it doesn't seem like it's the solution to the CURRENT situation... it's not an IMMEDIATE fix... so I don't do it... delay after delay. Then ONE day YEARS later I'm asking Him for direction. He says... I ALREADY TOLD YOU! After a few rounds of this I start&nbsp;writing&nbsp;it... SO FAR the books aren't done. But one did turn into a website and the other is MUCH farther along and a whole host of websites have come out of that&nbsp;writing. You just never know what that little obedience could turn out to mean...&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">Darrell G. Wolfe</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><iframe align="left" frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?t=your0f4d-20&amp;o=1&amp;p=8&amp;l=bpl&amp;asins=0899577474&amp;fc1=000000&amp;IS2=1&amp;lt1=_blank&amp;m=amazon&amp;lc1=0000FF&amp;bc1=000000&amp;bg1=FFFFFF&amp;f=ifr" style="align: left; height: 245px; padding-right: 10px; padding-top: 5px; width: 131px;"></iframe>This is my favorite bible. I strongly&nbsp;recommend&nbsp;this one to anyone looking for a good study bible. You can look up Hebrew and Greek definitions right in the back as you study. It's brought MUCH light to my study over the years.&nbsp;</span>