---
title: 'Seize the Day!'
date: '2010-03-30T18:38:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7267611926085612717'
blogger_filename: '/2010/03/seize-day.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=luke%2019&amp;version=NIV">Luke 19</a><br /><i><br /></i><br /><i><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"></span></i><br /><sup class="versenum" id="en-NIV-25764" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;"><i>41</i></sup><i>As he approached Jerusalem and saw the city, he wept over it&nbsp;</i><sup class="versenum" id="en-NIV-25765" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;"><i>42</i></sup><i>and said, "If you, even you, had only known on this day what would bring you peace—but now it is hidden from your eyes.&nbsp;</i><sup class="versenum" id="en-NIV-25766" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;"><i>43</i></sup><i>The days will come upon you when your enemies will build an embankment against you and encircle you and hem you in on every side.&nbsp;</i><sup class="versenum" id="en-NIV-25767" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;"><i>44</i></sup><i>They will dash you to the ground, you and the children within your walls. They will not leave one stone on another, <b>because you did not recognize the time of God's coming to you."</b></i><br /><br />&nbsp;&nbsp; &nbsp; There are times and seasons&nbsp;appointed&nbsp;for the moves of God and the changes of the Holy Spirit. It is not possible to attend a meeting of Smith Wigglesworth, John Lake, Martin Luther, John&nbsp;Wesley, or other mighty leaders. It's not possible to attend the final West Coast&nbsp;Believers&nbsp;Convention of 2009. There are defined and&nbsp;definite&nbsp;seasons. Those times are set and you cannot go back in time. Grace and Mercy are new every morning, but certain things cannot be done over, only forgiven and washed. You cannot REDO your kids lives growing up, you cannot REDO a marriage... sometimes you can start over, but not REDO.<br /><br />&nbsp;&nbsp; &nbsp; One must take a hold of the seasons that arise. You must take part in what is going on and participate in any way possible. This applies especially in the callings of God for your life in general and daily. You have divine appointments today, will you keep them?<br /><br />&nbsp;&nbsp; &nbsp; Recognize the time, before it's too late. Has God been calling you to make changes? MAKE THEM! Has God been calling you to move? MOVE! Seize the day!<br /><br />&nbsp;&nbsp; &nbsp; Darrell G. Wolfe<br /><span class="Apple-style-span" style="font-family: arial, verdana; font-size: 19px; font-weight: bold;"><b><a href="http://www.stlyrics.com/lyrics/newsies/seizetheday.htm">Newsies Cast - Seize the Day Lyrics</a></b></span><br /><br /><span class="Apple-style-span" style="font-family: Arial, Helvetica, 'Times New Roman'; font-size: 16px;">Music by Alan Menken.<br />Lyrics by Jack Feldman.<br /><br />DAVID:<br />Open the gates and seize the day<br />Don't be afraid and don't delay<br />Nothing can break us<br />No one can make us<br />Give our rights away<br />Arise and seize the day<br /><br />DAVID and NEWSIES:<br />Now is the time to seize the day<br />Send out the call and join the fray<br /><br />DAVID:<br />Wrongs will be righted<br />If we're united<br /><br />DAVID and NEWSIES:<br />Let us seize the day<br /><br />Friends of the friendless, seize the day<br />Raise up the torch and light the way<br />Proud and defiant<br />We'll slay the giant<br />Let us seize the day<br /><br />Neighbor to neighbor<br />Father to son<br />One for all and all for one<br /><br />Open the gates and seize the day<br />Don't be afraid and don't delay<br />Nothing can break us<br />No one can make us<br />Give our rights away<br /><br />Neighbor to neighbor<br />Father to son<br />One for all and all for one</span>