---
title: 'New Wine'
date: '2010-01-15T05:09:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2746575409318914801'
blogger_filename: '/2010/01/new-wine.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

01.13.10<br /><br />Mathew 9:15<br /><br />ONE thing came out higher for me this time reading this chapter than anything else. What did Jesus mean by this new wine old wineskins analogy?<br /><br />It finally makes sense for the first time... I'm not sure it would have made sense before but I have done some fasting between the time I read this last, whenever that was, and now.<br /><br />Jesus is empowering these men with the anointing to deliver his Gospel of the Kingdom. He is in constant 24-7 training mode. Nothing makes training go better than a good meal. Our best team meetings at work have always been food friendly meetings. Nothing brings a team together and builds morale like eating together.<br /><br />Fasting isn't a time for learning as much as it is for growing. Medical science has already shown us this on a scale we all do everyday and don't even think about.<br /><br />Sleep, recharges the body and allows the brain and body to assess damage and repair things that got our of order. If you eat late than you body has to digest this food which hinders this restoration process. You body should be sleeping well, NOT degesting during the restoration phase of your day. This phase for most healthy people is between 6-9 hours overnight.<br /><br />SO... fasting food (or any other natural thing that inhibits or adds distraction to your spiritual life) is a way you can bring your body under subjection to your spirit. The time normally spent preparing, eating, cleaning up after food should be spent now on things that cause you to grow, restore, or correct.<br /><br />Essentially:<br /><br />Fasting allows that which has been fed by the Word, the Holy Spirit, and Teachers, which has now been digested and stored, to now be used to restore and correct the spiritual life. All the lessons you learned, words given, things that you found in the word can now be brought out and focused and used to restore and correct.<br /><br />So the disciples who were young, and new to ministry and being fed spiritually by Jesus are not in need of a fast. Once Jesus dies and they are without Him they will fast. This time will be time the Holy Spirit may now restore and correct. Fasting in the natural is an act of obedience that opens one to partake in the spiritual and soulical (mind, will, emotions) process of restoration. Fasting of some kind should be a regular part of spiritual routine, just as sleeping is a regular part of natural routine.<br /><br />It is as un-natural NOT to fast as it is un-natural NOT to sleep. One need not fast daily, for spiritual growth operates on a higher level than natural growth. However period of dedicated fasting according to the Leading of the Holy Spirit from time to time are vital to any accelerated growth.<br /><br />What can you fast?<br />Food (Maybe not a whole day, why not fast lunches at work three days in a row and hide yourself away where no one can find you and read and pray during those three lunch hours?)<br /><br />TV, radio, internet, cell phone, etc... Some could use a WORDS fast and just be silent for an hour, two hours, a day...<br /><br />Start small build to other things... but start somewhere. <br /><br />Ask the Holy Spirit what HE would have you do at YOUR level of growth. Consult reading on proper fasting before attempting long periods without food or water. There is a right and wrong way do it. Getting excited and running off half cocked isn't' going to help you.<br /><br />Fasting:<br /><a href="http://www.ccci.org/training-and-growth/devotional-life/personal-guide-to-fasting/index.htm">Personal Guide</a><br /><a href="http://www.webmd.com/diet/fasting">Web MD</a><br /><a href="http://en.wikipedia.org/wiki/Fasting">Wikipedia</a><br /><br /><br />Darrell G. Wolfe