---
title: 'Communication'
date: '2010-01-25T03:56:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4989878574442067601'
blogger_filename: '/2010/01/communication.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p>01/22/2010<br /></p><p><a href='http://www.biblegateway.com/passage/?search=Matthew%2016&amp;version=NKJV'>Matthew 16</a><br />			</p><p>Jesus was the Master Communicator. He was able to maneuver around verbal traps and meet people at their level. EVEN JESUS wasn't always, if ever really understood. <br /></p><p>In life, no matter how skilled you may be at communication, people will at times misunderstand, misquote, and even add and subtract from what you said and get mad at YOU for it. Pat Robertson is dealing with that very issue this week. Like Pat, some of the people doing the misquoting are doing it on purpose. <br /></p><p><span style='font-size:10pt'><em>        <span style='font-family:Times New Roman'> <sup>5</sup>When they went across the lake, the disciples forgot to take bread. <sup>6</sup>"Be careful," Jesus said to them. "Be on your guard against the yeast of the Pharisees and Sadducees." <br /></span></em></span></p><p><span style='font-family:Times New Roman; font-size:10pt'><em> <sup>7</sup>They discussed this among themselves and said, "It is because we didn't bring any bread." <br /></em></span></p><p><span style='font-family:Times New Roman; font-size:10pt'><em> <sup>8</sup>Aware of their discussion, Jesus asked, "You of little faith, why are you talking among yourselves about having no bread? <strong><sup>9</sup>Do you still not understand? Don't you remember the five loaves for the five thousand, and how many basketfuls you gathered?</strong><br />						<sup>10</sup>Or the seven loaves for the four thousand, and how many basketfuls you gathered? <sup>11</sup>How is it you don't understand that I was not talking to you about bread? But be on your guard against the yeast of the Pharisees and Sadducees." <sup>12</sup>Then they understood that he was not telling them to guard against the yeast used in bread, but against the teaching of the Pharisees and Sadducees.<br /></em></span></p><p>    Jesus is talking to his people. These are the ones He has chosen to spend the most time with. They should understand Him right? What He was trying to tell them went right over their heads. Just remember to say what God said and let it be. Let people think what they will… explain only to those who really want to listen. <br /></p><p><br /> </p><p>                    Darrell G. Wolfe<br /></p><p>    </p></span>