---
title: 'SHHH… No Talking'
date: '2010-02-10T14:21:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3895153491690280430'
blogger_filename: '/2010/02/shhh-no-talking.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p>Mark 1 <br /></p><p><span style='font-size:10pt'><em><sup>23</sup> Now there was a man in their synagogue with an unclean spirit. And he cried out, <sup>24</sup> saying, "Let us alone! What have we to do with You, Jesus of Nazareth? Did You come to destroy us? <strong>I know who You are—the Holy One of God!"</strong><br />						<br/><sup>25</sup> But Jesus rebuked him, saying, <strong>"Be quiet, and come out of him!"</strong><br />						<sup>26</sup> And when the unclean spirit had convulsed him and cried out with a loud voice, he came out of him.<br /></em></span></p><p><span style='font-size:10pt'><em><sup>28</sup> And immediately His fame spread throughout all the region around Galilee.<br /></em></span></p><p><span style='font-size:10pt'><em><sup>34</sup> Then He healed many who were sick with various diseases, and cast out many demons; and <strong>He did not allow the demons to speak, because they knew Him.<br /></strong></em></span></p><p><br /> </p><p><span style='font-size:10pt'><em><sup>40</sup> Now a leper came to Him, imploring Him, kneeling down to Him and saying to Him, "If You are willing, You can make me clean." <br/><sup>41</sup> Then Jesus, moved with compassion, stretched out His hand and touched him, and said to him, "I am willing; be cleansed." <sup>42</sup> As soon as He had spoken, immediately the leprosy left him, and he was cleansed. <sup>43</sup> And He <strong>strictly warned him and sent him away at once, <sup>44</sup> and said to him, "See that you say nothing to anyone;</strong> but go your way, show yourself to the priest, and offer for your cleansing those things which Moses commanded, as a testimony to them." <br/><sup>45</sup><br />						<strong>However, he went out and began to proclaim it freely, and to spread the matter, so that Jesus could no longer openly enter the city, but was outside in deserted places; and they came to Him from every direction.<br /></strong></em></span></p><p><br /> </p><p><span style='font-size:10pt'>    Many times it's better that your business is not published everywhere, especially at the onset. If you are doing something and too many find out about they may abort what you were trying to do. This actually happened to Jesus in VS 40-45. Why did Jesus STRICTLY WARN the man not to say anything?! Because of what happened next when the man didn't obey… Jesus couldn't enter the town and things he wanted to do there were delayed or canceled. Maybe someone in that town needed him and wouldn't be meeting him out in the deserted places! <br /></span></p><p><br /> </p><p><span style='font-size:10pt'>    Maybe you are thinking about a move, a new car, a promotion, a business plan, a spouse… Whatever project the Holy Spirit has you work on, you may be best to gather what information you need from those who know something about your subject… but not tell even them what you are thinking or the depth of what you are planning. Not only could this bring bad publicity, it could open a door for fear or doubt or unbelief to work their way into your faith life and abort your plans altogether. <br /></span></p><p><br /> </p><p><span style='font-size:10pt'>    Keep your plans between you and God and follow Jesus example:<br /></span></p><p><span style='font-size:14pt'><strong><em><sup>35</sup> Now in the morning, having risen a long while before daylight, He went out and departed to a solitary place; and there He prayed.<br /></em></strong></span></p><p><br /> </p><p><span style='font-size:14pt'>Darrell G. Wolfe</span></p></span>