---
title: 'Prayer THE Priority'
date: '2010-03-14T23:41:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '228585816606797439'
blogger_filename: '/2010/03/prayer-priority.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=Luke%205&amp;version=NKJV">Luke 5</a><br /><br /><sup class="versenum" id="en-NKJV-25120">16</sup> So He Himself <i>often</i> withdrew into the wilderness and prayed.<br /><br />Prayer:<br /><br />&nbsp; &nbsp;&nbsp; Did you ever wonder how Jesus got to hear the Father? When He said I only say what I hear Him saying... was there some special connection that He had that we could never have? No... He had to use the same tools provided to us or He could not be our substitute. People didn't carry around bibles back then either. The only copy of the Hebrew bible was kept in the synagogue. Jesus undoubtedly spent a lot of time there growing up in order to know "It is written..." But He would not have kept a copy with Him like we do? How did He know the Word and will of God so well?<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; He prayed...He took Himself away from the people, crowds, noise, business, and all the things that weigh so heavily on a persons day. He took himself for a long walk (No Cars) into the wilderness.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; Prayer is the only way you will ever hear the voice of God for your life and your day. Reading the bible will give you great insight and it's alive and it will speak to you. But only through developing your prayer life and making prayer a priority will you hear Him throughout the day and be able to make solid and wise decisions.<br /><br /><ul><li>Make prayer, by yourself, free from noise and distraction (expect possibly praise-worship music) THE not A, but THE priority of each day!</li><li>It may be helpful to make your bible reading time a separate activity from your prayer time.&nbsp; Either separate them by a specific time for each, or even do one in the morning and one at night.</li><li>Prayer throughout the day is important and vital to living right. But it is not to replace Set Apart Times of Prayer.&nbsp;</li><li>Spend some time listening not just talking. Schedule in LONG periods of time to say nothing, hear nothing, JUST listen!</li><li>Bring with you items you would like to focus on, including leaders, family, callings, asking for assignments for your life and day, and asking for Divine Appointments.&nbsp;</li><li>Pray in Tongues at least Ten Minutes. (Not using tongues yet? <a href="http://www.kcm.org/real-help/article/how-receive-baptism-holy-spirit">See This</a>)</li></ul>Darrell G. Wolfe <br /><br /><br />&nbsp;&nbsp;