---
title: 'Words and Deeds'
date: '2010-06-17T18:24:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2782465772155117526'
blogger_filename: '/2010/06/words-and-deeds.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=acts%201-3&amp;version=NKJV"><b>Romans 1-3</b></a><br /><br /><b>Paul lays out here the paradox of doing. You cannot do without doing by faith. You cannot faith without faithing by do.&nbsp;</b><br /><b> </b><br /><b>Romans 1</b><br /><br /><b>&nbsp;</b><sup class="versenum" id="en-NKJV-27955">28</sup> And even as they did  not like to retain God in <i>their</i> knowledge, God gave them over to a  debased mind, to do those things which are not fitting; <sup class="versenum" id="en-NKJV-27956">29</sup> being filled with all  unrighteousness, sexual immorality,<sup class="footnote" value="[&lt;a  href=&quot;#fen-NKJV-27956c&quot; title=&quot;See footnote  c&quot;&gt;c&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=romans%201-3&amp;version=NKJV#fen-NKJV-27956c" title="See footnote c">c</a>]</sup> wickedness, covetousness,  maliciousness; full of envy, murder, strife, deceit, evil-mindedness; <i>they  are</i> whisperers, <sup class="versenum" id="en-NKJV-27957">30</sup>  backbiters, haters of God, violent, proud, boasters, inventors of evil  things, disobedient to parents, <sup class="versenum" id="en-NKJV-27958">31</sup>  undiscerning, untrustworthy, unloving, unforgiving,<sup class="footnote" value="[&lt;a href=&quot;#fen-NKJV-27958d&quot;  title=&quot;See footnote d&quot;&gt;d&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=romans%201-3&amp;version=NKJV#fen-NKJV-27958d" title="See footnote d">d</a>]</sup> unmerciful; <sup class="versenum" id="en-NKJV-27959">32</sup> who, knowing the righteous judgment of God,  that those who practice such things are deserving of death, not only do  the same but also approve of those who practice them.<br /><br /><b>Something I've learned is that all these things start with thoughts, since you do not know to cast them down you assume they are your thoughts, dwell on them, maybe even worry about them, and if not caught could act on them. As soon as you realize that they are not your thoughts and cast them down you are heading towards victory. If they keep coming back you don't beat yourself up or feel&nbsp; there is something wrong with you. They are NOT YOUR THOUGHTS they are coming at you from an enemy who wants you dead. Cast them down and choose new WORD based imaginations. Force your imagination to see God thoughts.&nbsp; </b><br /><br /><br /><b>Romans 2</b><br /><br /><b>&nbsp;</b> <sup class="versenum" id="en-NKJV-27965">6</sup> who <i> “will render  to each one according to his deeds”</i>:<sup class="footnote" value="[&lt;a href=&quot;#fen-NKJV-27965e&quot; title=&quot;See footnote  e&quot;&gt;e&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=romans%201-3&amp;version=NKJV#fen-NKJV-27965e" title="See footnote e">e</a>]</sup> <sup class="versenum" id="en-NKJV-27966">7</sup> eternal life to those who by patient  continuance in doing good seek for glory, honor, and immortality;<br /><sup class="versenum" id="en-NKJV-27972">13</sup> (for not the hearers  of the law <i>are</i> just in the sight of God, but the doers of the law  will be justified; <br /><br /><b>&nbsp;</b> <sup class="versenum" id="en-NKJV-27983">24</sup> For <i> “the name of  God is</i> <i> blasphemed among the Gentiles because of you,”</i><sup class="footnote" value="[&lt;a href=&quot;#fen-NKJV-27983g&quot;  title=&quot;See footnote g&quot;&gt;g&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=romans%201-3&amp;version=NKJV#fen-NKJV-27983g" title="See footnote g">g</a>]</sup> as it is written.<br /><br /><br /><br /><b>Romans 3</b><br /><b><br /></b><br /><sup class="versenum" id="en-NKJV-27991">3</sup> For what if some did  not believe? Will their unbelief make the faithfulness of God without  effect? <sup class="versenum" id="en-NKJV-27992">4</sup> Certainly not!  Indeed, let God be true but every man a liar. As it is written:<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>“  That You may be justified in Your words,</i><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>And may  overcome when You are judged.”</i><sup class="footnote" value="[&lt;a  href=&quot;#fen-NKJV-27992h&quot; title=&quot;See footnote  h&quot;&gt;h&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=romans%201-3&amp;version=NKJV#fen-NKJV-27992h" title="See footnote h">h</a>]</sup><br /><sup class="footnote" value="[&lt;a  href=&quot;#fen-NKJV-27992h&quot; title=&quot;See footnote  h&quot;&gt;h&lt;/a&gt;]"></sup><br /><br /><sup class="versenum" id="en-NKJV-28001">13</sup> <i>“ Their</i> <i>throat</i>  <i>is</i> <i>an open</i> <i>tomb;</i><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i> With their tongues  they have practiced deceit”;</i><sup class="footnote" value="[&lt;a  href=&quot;#fen-NKJV-28001j&quot; title=&quot;See footnote  j&quot;&gt;j&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=romans%201-3&amp;version=NKJV#fen-NKJV-28001j" title="See footnote j">j</a>]</sup><br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>“ The poison of  asps</i> <i>is</i> <i>under their lips”;</i><sup class="footnote" value="[&lt;a href=&quot;#fen-NKJV-28001k&quot; title=&quot;See footnote  k&quot;&gt;k&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=romans%201-3&amp;version=NKJV#fen-NKJV-28001k" title="See footnote k">k</a>]</sup><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <sup class="versenum" id="en-NKJV-28002">14</sup> <i>“ Whose mouth</i> <i>is</i> <i>full of  cursing and bitterness.”</i><sup class="footnote" value="[&lt;a  href=&quot;#fen-NKJV-28002l&quot; title=&quot;See footnote  l&quot;&gt;l&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=romans%201-3&amp;version=NKJV#fen-NKJV-28002l" title="See footnote l">l</a>]</sup><sup class="footnote" value="[&lt;a  href=&quot;#fen-NKJV-27992h&quot; title=&quot;See footnote  h&quot;&gt;h&lt;/a&gt;]"> </sup><br /><b><br /></b><br /><b><br /></b><br /><b><br /></b><br /><b><br /></b><br /><b><br /></b><br /><b>Words and Deeds</b><br /><b><br /></b><br /><b>These cannot be separated. Out of the heart comes words and deeds. The breed one another. You can talk right for so long and in front of certain audiences. But your talk will betray your heart and deeds.&nbsp;</b><br /><b><br /></b><br /><b>You can hear and hear and hear the right things, but only as you do will the Word of God be worked out in your life. I remember under pressure at work I cursed and the whole staff turned around and stared at me. Not because of the curse words, they used those all day everyday in that environment. It was because I used them. "Christian Boy Cussed... Watch out, Fire might come down everyone." All kinds of weird things they said. I realized at that moment something I hadn't realized ever before: They ARE watching. And Paul rightly brought up that they curse God becu</b><b>ase of US.&nbsp;</b><br /><b><br /></b><br /><b>I wish I could say that I learned from that but there were times even in my last post I let out a few choice words. Some might say, "what's the problem?" If you are generating CURSE you cannot be also generating BLESSING. The two cancel each other out. Although the Blessing will do away with the curse any time it won't have any power behind it if the one doing the Blessing is also Cursing. It's like drinking diseased water. Water is a vital source of life, but if it's diseased, than it has the opposite effect. You can add healthy water to it, and after adding enough healthy water it may dilute the power of the bad water, but ultimately you must rid the bad water entirely of the disease if you want to have the full restorative power of water in your body.&nbsp;</b><br /><b><br /></b><br /><b><br /></b><br /><b>A good reminder to watch what you Think, Imagine (allow images of in your mind), Say, and Do.&nbsp;</b><br /><b><br /></b><br /><b><br /></b><br /><b>DW</b><br /><b><br /></b><br /><b><br /></b><br /><b><br /></b><br /><b><br /></b><br /><b><br /></b><br /><b><br /></b><br /><b><br /></b>