---
title: 'Life Lived WELL!'
date: '2010-01-19T05:27:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7240252564708733442'
blogger_filename: '/2010/01/life-lived-well.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p>01/18/2010<br /></p><p><a href='Psalm%20112'>Psalms 112</a><br />			</p><p>The Holy Spirit was the ORIGINAL BLOGGER! He wrote Blogs people have been reading and talking about for over 4,000 years!<br /></p><p><br /> </p><p><br /> </p><p>     The man who Reverences The LORD and delights in the LORD's Word, excited and ready to obey and put it to work is Empowered to Prosper! (Blessed)<br /></p><p><br /> </p><p>His Life Results:<br /></p><ul><li>Descendants are Mighty<br /></li><li>Empowers his generation to Prosper<br /></li><li>Wealth, Riches, House/Land<br /></li><li>Right Standing with God ENDURES!<br /></li><li>He has and provides Light in the Darkness<br /></li></ul><p>This Man:<br /></p><ul><li>Is Gracious<br /></li><li>Full of Compassion<br /></li><li>Right with God<br /></li><li>Deals Graciously and Lends<br /></li><li>Never Shaken<br /></li><li>Etched into God's Immediate Memory!<br /></li><li>Has NO fear of evil reports.<br /></li><li>His Spirit is steadfast, trusting in God.<br /></li><li><div>His Spirit (Heart=Lit. Core) is:<br /></div><ul><li>Established<br /></li><li>No Fear Zone<br /></li><li>Wants his enemies to repent and be as blessed as he is!<br /></li></ul></li><li>Gives Abroad <br /></li><li>Gives to the poor<br /></li><li>Gets Promoted<br /></li><li>Causes the wicked to grieve<br /></li><li><div>The Desire of the wicked shall perish or fade around him.<br /></div><ul><li>Those that repent will get blessed and get renewed desires<br /></li><li>Those that resist just fade away into the background.<br /></li><li>THIS man has nothing to do but TRUST God and His enemies will be adjusted for him.<br /></li></ul></li></ul><p><br /> </p><p><br /> </p><p>                     Darrell G. Wolfe</p></span>