---
title: 'EMIC New Years Eve Service'
date: '2010-01-02T04:31:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6856943926243541671'
blogger_filename: '/2010/01/emic-new-years-eve-service.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'EMIC'
---

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Last night was <b>amazing</b>... The anointing and power of God flowed into Eagle Mounting International Church! <a href="http://www.emic.org/">EMIC</a> There were so many things said I couldn't recount them all here. Service started at 8 pm and we left in the car just after 1:23 am!<br /><br />The Highlights:<br /><ul><li>&nbsp;<b>Have faith in God!</b></li></ul><ul><li><b>2010 will be the Best of times and the Worst of times!</b></li></ul>&nbsp;&nbsp;&nbsp;&nbsp; If you are not listening to God and walking with him you be tossed about by the wild things going to hit the country this year. Natural disasters, terrorist attacks, politics, etc. We are witnessing the collapse of the Babylonian system of socialism that's been attacking this country for 110 years!<br /><br /><br /><ul><li>Jeremiah 17:5</li></ul><br />&nbsp;&nbsp;&nbsp;&nbsp; Curse is the man who's trust is in man, or in man's natural ways of operation.<br />&nbsp;&nbsp;&nbsp;&nbsp; VS<br />&nbsp;&nbsp;&nbsp;&nbsp; <b>Blessed is the man who Hopes and Trusts and who's source is in GOD!</b><br /><br /><ul><li>These are the tools of faith:</li></ul><ul><ul><li><b>I Believe</b></li><li><b>I Will</b></li><li><b>I Take It</b></li><li><b>I Have It</b></li><li><b>I Thank you For IT!</b></li><li><b>I Forgive!</b></li></ul></ul>&nbsp; &nbsp; &nbsp; These are the vocabulary that you should develope in 2010!<br /><br /><ul><li>Two phrases from Oral Roberts Message "The 4th Man" that changed many lives:</li></ul><br /><span style="font-size: small;"><i><b>"I will never bow the confession of my mouth!"</b></i></span><br /><br /><span style="font-size: small;"><b><i>"What you compromise to keep you will eventually loose!"&nbsp;</i></b></span><br /><br /><ul><li>The commitments Kenneth and Gloria made <b>43 years ago</b> and still stand by are:</li></ul><br /><ol><li><b>Never ask anybody for a place to preach.</b></li><li><b>Never preach anywhere based on a financial arrangement.</b></li><li><b>Never ask anybody for $ to meet my needs.</b></li><li><b>Never put this ministry in debt or ever borrow $ again!</b></li></ol>These were and are the keys to thier success in God. These prevent compromise and contamination.<br /><br /><ul><li>Christianity is not a religion, but it's had religions made out of it.</li></ul><br /><ul><li><b>You can change what happens in your:</b></li><ul><li><b>Nation some of the time</b></li><li><b>Community most of the time</b></li><li><b>Home ALL of the time!</b></li></ul></ul><br /><br /><b>Get ready for an amazing year! The BEST year ever for those walking and and OBEYING the voice of God. The WORST year for those trusting in Man's Broken System!</b><br /><b> <br /></b><br /><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Be Blessed! Darrell G. Wolfe<br /></b>