---
title: 'Believe!'
date: '2010-04-06T18:34:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8818778701938367413'
blogger_filename: '/2010/04/believe.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=Luke%2024&amp;version=NKJV">Luke 24</a><br /><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><sup class="versenum" id="en-NKJV-25999" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">11</sup>&nbsp;And their words seemed to them like idle tales, and <b>they did not believe</b> them.</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><sup class="versenum" id="en-NKJV-26029" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">41</sup>&nbsp;But while <b>they still did not believe</b> for joy, and marveled, He said&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">&nbsp;&nbsp; &nbsp; The Word of God has placed a HIGH priority and value on Believing. It is among the most important aspects of the life of the&nbsp;Christian&nbsp;"believer". The Disciples were constantly rebuked for their lack of faith by Jesus during His ministry. Here again He finds them not believing.&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">&nbsp;&nbsp; &nbsp; Another&nbsp;interesting&nbsp;thing we find here though is a phrase that is both awkward as it is profound:</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">...<b>they still did not believe for joy, and marveled</b>...</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">&nbsp;&nbsp; &nbsp; Believing is tied to joy. You cannot have joy if you don't believe. If you don't believe you will be a bystander and a&nbsp;marveler&nbsp;instead of a participant.&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">&nbsp;&nbsp; &nbsp; Who is responsible for your believing? YOU! Choose, as an act of your will and a quality decision to believe the truth, despite what you feel. Then take actions regarding it. Be like the man who said to Jesus:</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">"I believe Lord, help my unbelief!"&nbsp;</span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;"><br /></span><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif;">Darrell G. Wolfe</span>