---
title: 'But GOD!'
date: '2010-04-21T22:21:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '600491761916673764'
blogger_filename: '/2010/04/but-god.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=john11&amp;version=NKJV">John 11</a><br /><br /><span class="Apple-style-span" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;">Mary was sitting in the house.&nbsp;<sup class="versenum" id="en-NKJV-26541" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">21</sup>&nbsp;Now Martha said to Jesus, “Lord, if You had been here, my brother would not have died.&nbsp;<sup class="versenum" id="en-NKJV-26542" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">2</sup><sup class="versenum" id="en-NKJV-26542" style="font-size: 0.65em; line-height: normal; vertical-align: text-top;"><b>2</b></sup><b>But even now I know that whatever You ask of God, God will give You.”&nbsp;</b></span><br /><br /><br />Martha is often pointed out for her failure to&nbsp;recognize&nbsp;the important matters of life. If the man could feed 5000 + people with two fish and five loafs than you don't need to be fussing over dinner.<br /><br />However, there is another side to this dynamic. This time MARY is still sitting when action is needed and it's MARTHA who takes the action. She GETS UP and GOES! Then she displays that she too, indeed, has faith.<br /><br />My Brother died... BUT... GOD...<br /><br />It is important when a&nbsp;tragedy occurs that you recognize it, then out loud I must say BUT GOD!!!!<br /><br />Anything that happens that is contrary to what I know should or must happen, I can turn and say BUT GOD!!! Then find HIS plan and roll with it.<br /><br />But she goes on from her to backpedal a little bit. However it was this act of faith that gave Jesus room to work.<br /><br />Darrell G. Wolfe