---
title: 'The Older Brothers Lack'
date: '2010-03-24T18:35:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4364960483433387117'
blogger_filename: '/2010/03/the-older-brothers-lack.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=Luke%2015&amp;version=NKJV">Luke 15</a><br /><i><br /></i><br /><i><sup class="versenum" id="en-NKJV-25596">11</sup> Then He said: “A certain man had two sons. <sup class="versenum" id="en-NKJV-25597">12</sup> And the younger of them said to </i><i>his father, ‘Father, give me the portion of goods that falls </i><i>to me.’ So he <b>divided to them</b> </i><i>his livelihood.</i><br /><i>&nbsp;&nbsp;&nbsp; <sup class="versenum" id="en-NKJV-25616">31</sup> “And he said to him, ‘<b>Son, you are always with me, and all that I have is yours</b>. <sup class="versenum" id="en-NKJV-25617">32</sup> It was right that we should make merry and be glad, for your brother was dead and is alive again, and was lost and is found.’”</i><br /><br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Here is an interesting story about being lost and found. Both brothers had growing to do. The older brother is the one I'm concerned about here. This is the story of dedicated workers in the ministry and church world. They serve and serve. They get jealous of the younger brother who seems to be getting blessed despite his lack of obedience. The Father lovingly points out: It's all yours. The younger brother forgoes his rewards and inheritance. The older brother gets mad a calf was never offered to him. He didn't understand that the inheritance was divided to THEM no just his brother. The calf was never offered because it was already his. He had only need receive it. But he didn't. He kept working for something that He already owned. <br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This is the story of the older brother and the story I need most hear. Recieve and walk and work FROM The Blessing not FOR it!<br /><br />Darrell G. Wolfe