---
title: 'Master Over Crisis!'
date: '2010-01-20T23:58:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7664357857694198940'
blogger_filename: '/2010/01/master-over-crisis.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p>01/20/2010<br /></p><p><a href='http://www.biblegateway.com/passage/?search=Matthew%2014&amp;version=ESV'>Matthew 14</a> Part One<br /></p><p>VS 1-23<br /></p><p>    Jesus is confronted with very tough news. The one who healed so many and raised some from the dead has just been informed that his own cousin and forerunner has been murdered. COULD Jesus go raise John from the dead? If anyone could Jesus could right? He who raised others is now confronted with death in the family. He was sad for John after his last news from John's disciples. Jesus mentioned that "blessed is he who is not offended because of me." <a href='http://www.biblegateway.com/passage/?search=Matthew%2011:2&amp;version=ESV'>Matthew 11</a><br />			</p><p>Evidently John, the subject of the preceding verses to that statement, was living in some level of offense. "Hey Jesus… I thought you were supposed to come in and set things straight, lay out those hypocrites on their butts… what's up here… are you the one or should we look for another?" (My Paraphrase) <br /></p><p>It may have been a result of this offense that John was beheaded rather than set free, like Peter later was in his ministry in a similar situation. There is no direct statement either way. We know it's always God's will for a person to live long and finish their work. Did John open this door for the devil to come in and take his life? I don't think we can be dogmatic about it, since it's not directly in the text, but this is how I see it. <br /></p><p>So at his own fault or not Jesus is upset about this event. IMMEDIATELY He went away to be by himself to pray. People find Him and compassion rises in him to meet their needs. He attacks the devil's death with Healing and Provision for the People of God! But He doesn't let go of his original purpose. Sometimes your dedicated time to spend with God will get interrupted, you don't use that as an excuse to skip it that day. You make and create time, even if it means losing a little sleep to go back to what you were headed to before the interruption. <br /></p><p><br /> </p><p>Lessons from 14 A. <br /></p><ul><li><div><strong>Bad news comes, you deal with it by RUNNING (not walking) to prayer!<br /></strong></div><ul><li>Not to your five closest friends to complain and cry (also called "counseling")!<br /></li><li>You need to go get in the Word and Prayer and build yourself up on your most Holy Faith Praying in Tongues (<a href='http://www.biblegateway.com/passage/?search=Jude%2020&amp;version=ESV'>Jude 1:20</a>)<br /></li><li>When you have settled matters between you and God you can face life and the situation in faith and not doubt. There is no room for grief or sorrow in the life of a victorious believer! Avoid all forms of grief like cancer! You don't see Jesus taking two days off here to mope about. Grief is never productive! Sadness of a loss can be hard on the emotions, but emotions are not your God. Sadness and grief are not the same.<br /></li></ul></li><li><div><strong>In the middle of your attempt to get away with God your Father, for your daily time or during a crisis, you may be interrupted by a greater need.</strong> If there is a death for example others may need your faith to lift them up, they may not be at your level yet, they may not know what do to.<br /></div><ul><li>Attack the Devil with COMPASSION! Heal and Provide for the people in spite of any spirit of grief trying to take hold of you! Retaliate against the thief and killer himself by Healing and Providing for others! Respond in compassion!<br /></li></ul></li><li><div><strong>Always return to task after an interruption. <br /></strong></div><ul><li><div>Just because you were interrupted doesn't mean you don't pray!<br /></div><ul><li>Go back to your prayer room, mountain, place of solitude, as soon as possible. <br /></li><li>Being alone with God is not a "good idea" it is NUMBER ONE priority! DO NOT GO TO BED until you have spend at least ten minutes in the word and prayer! <br /></li><li>If you can't write out your journal that day fine… but read your daily reading, or whatever set of verses you have committed to and pray for a few minutes! <br /></li><li>Preferably, pray until you have a sense in your spirit that the answer to your situation has been delivered and you need only walk the interpretation of that out! </li></ul></li></ul></li></ul></span>