---
title: 'Untitled Post'
date: '2010-03-19T18:59:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3243224895148712445'
blogger_filename: '/2010/03/luke-12-35-let-your-waist-be-girded-and.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.biblegateway.com/passage/?search=Luke%2012&amp;version=NKJV">Luke 12</a><br /><br /><i><sup class="versenum" id="en-NKJV-25491">35</sup> “Let your waist be girded and </i><i>your lamps burning; <sup class="versenum" id="en-NKJV-25492">36</sup> and you yourselves be like men who wait for their master, when he will return from the wedding, that when he comes and knocks they may open to him immediately. <sup class="versenum" id="en-NKJV-25493">37</sup> Blessed </i><i>are</i> those servants whom the master, when he comes, will find watching. Assuredly, I say to you that he will gird himself and have them sit down <i>to eat, and will come and serve them. <b><sup class="versenum" id="en-NKJV-25494">38</sup> And if he should come in the second watch, or come in the third watch, and find </b></i><i><b>them so, blessed are those servants.</b> <sup class="versenum" id="en-NKJV-25495">39</sup> But know this, that if the master of the house had known what hour the thief would come, he would have watched and<sup class="footnote" value="[&lt;a href=&quot;#fen-NKJV-25495d&quot; title=&quot;See footnote d&quot;&gt;d&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=Luke%2012&amp;version=NKJV#fen-NKJV-25495d" title="See footnote d">d</a>]</sup> not allowed his house to be broken into. <sup class="versenum" id="en-NKJV-25496">40</sup> Therefore you also be ready, for the Son of Man is coming at an hour you do not expect.”    <br \="" /><sup class="versenum" id="en-NKJV-25497">41</sup> Then Peter said to Him, “Lord, do You speak this parable </i> <i>only to us, or to all </i><i>people?”    <br \="" /><b><sup class="versenum" id="en-NKJV-25498">42</sup> And the Lord said, “Who then is that faithful and wise steward, whom </b></i> <b><i>his</i><i>them their portion of food in due season? <sup class="versenum" id="en-NKJV-25499">43</sup> Blessed  master will make ruler over his household, to give</i></b> <i><b>is that servant whom his master will find so doing when he comes.</b> <sup class="versenum" id="en-NKJV-25500">44</sup> Truly, I say to you that he will make him ruler over all that he has. <sup class="versenum" id="en-NKJV-25501">45</sup> But if that servant says in his heart, ‘My master is delaying his coming,’ and begins to beat the male and female servants, and to eat and drink and be drunk, <sup class="versenum" id="en-NKJV-25502">46</sup> the master of that servant will come on a day when he is not looking for </i><i>him,</i> and at an hour when he is not aware, and will cut him in two and appoint <i>him his portion with the unbelievers. <sup class="versenum" id="en-NKJV-25503">47</sup> And that servant who knew his master’s will, and did not prepare </i><i>himself or do according to his will, shall be beaten with many </i><i>stripes. <sup class="versenum" id="en-NKJV-25504">48</sup> But he who did not know, yet committed things deserving of stripes, shall be beaten with few. For everyone to whom much is given, from him much will be required; and to whom much has been committed, of him they will ask the more.</i><i> <sup class="versenum" id="en-NKJV-25505">49</sup> “I came to send fire on the earth, and how I wish it were already kindled! <sup class="versenum" id="en-NKJV-25506">50</sup><sup class="versenum" id="en-NKJV-25507">51</sup> Do </i>  <i>But I have a baptism to be baptized with, and how distressed I am till it is accomplished!</i><br /><br /><br /><br />&nbsp; &nbsp;&nbsp; If you follow the pattern off thousand year watches, and assuming Jesus Died and Rose again bringing in the reign of the Church through the Holy Spirit in 33AD which seems to be a <a href="http://home.teleport.com/%7Esalad/4god/33ad.htm">consensus</a> but not <a href="http://www.jesuspolice.com/common_error.php?id=17">unanimous</a>, than the second watch ends about 2033 AD and the third watch begins.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; This in interesting because other signs have been pointing to this being the season but I've never heard this one talked about. We are in the last days, that much is certain. If we are not watching and paying attention and looking for His coming we tend to become overly concerned with life here. There are matters we need to attend to and when we aren't looking for His coming it seems that we have all the time in the world and delay after delay comes along to help us toward inactivity.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; Jesus IS COMING! According to this chapter He is coming READY OR NOT! Those who are ready and watching and active in His Kingdom will receive from Him and those who are not may miss out on some things that could have been theirs.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; We are to be caring for the people of God in whatever way HE has called us to. Your calling in life will always involve others. Right now one of my callings to get The Word out to people is this website. Someone else's calling may be to care for the physically needy through medicine or charity. Other's may be protectors in Law. We are called to keep others in mind serving Him by serving them.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp; It's also a warning not to allow worry, also mentioned in this chapter to steal from us. Worry is NEVER acceptable. It is NEVER to be tolerated. But it's more than that. You don't just NOT WORRY. You must also ENGAGE the Word in Faith instead. <br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;Darrell G. Wolfe