---
title: 'Questions for Christians'
date: '2010-07-02T02:37:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1527724937380608077'
blogger_filename: '/2010/07/questions-for-christians.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<b>Catching Up</b><br /><b><br /></b><br /><b>This two weeks of training has been busy.&nbsp;</b><br /><b><br /></b><br /><b>I signed on to read Romans 10 and ended up reading I Corinthians 10.&nbsp;</b><br /><b><br /></b><br /><b>This was very timely and interesting for me. </b><br /><br /><br /><h4>1 Corinthians 10</h4><br /><sup class="versenum" id="en-NKJV-28570">6</sup> Now these things became  our examples, to the intent that we should not lust after evil things  as they also lusted. <sup class="versenum" id="en-NKJV-28571">7</sup>  And do not become <b>idolaters </b>as <i>were</i> some of them. As it is  written, <i> <b>“The people sat down to eat and drink, and rose up to  play.”</b></i><sup class="footnote" value="[&lt;a  href=&quot;#fen-NKJV-28571a&quot; title=&quot;See footnote  a&quot;&gt;a&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=i%20corinthians%2010&amp;version=NKJV#fen-NKJV-28571a" title="See footnote a">a</a>]</sup> <sup class="versenum" id="en-NKJV-28572">8</sup> Nor let us commit<b> sexual immorality</b>, as some  of them did, and <b>in one day twenty-three thousand fell</b>; <sup class="versenum" id="en-NKJV-28573">9</sup> nor let us<b> tempt Christ</b>, as  some of them also tempted, and were <b>destroyed by serpents</b>; <sup class="versenum" id="en-NKJV-28574">10</sup> nor <b>complain</b>, as some of  them also complained, and were <b>destroyed by the destroyer.</b> <sup class="versenum" id="en-NKJV-28575">11</sup> Now all<sup class="footnote" value="[&lt;a href=&quot;#fen-NKJV-28575b&quot;  title=&quot;See footnote b&quot;&gt;b&lt;/a&gt;]">[<a href="http://www.biblegateway.com/passage/?search=i%20corinthians%2010&amp;version=NKJV#fen-NKJV-28575b" title="See footnote b">b</a>]</sup> these things happened to them as  examples, and<b> they were written for our admonition, upon whom the ends  of the ages have come.    </b><br /><sup class="versenum" id="en-NKJV-28576">12</sup>  Therefore let him who thinks he stands<b> take heed</b> lest he fall. <sup class="versenum" id="en-NKJV-28577">13</sup> No temptation has overtaken  you except such as is common to man; but God <i>is</i> faithful, who  will not allow you to be tempted beyond what you are able, but with the  temptation will also make the way of escape, that you may be able to  bear <i>it.</i><br /><br /><br /><sup class="versenum" id="en-NKJV-28595">31</sup> Therefore, whether you  eat or drink, or whatever you do, <b>do all to the glory of God.</b> <sup class="versenum" id="en-NKJV-28596">32</sup> <b>Give no offense</b>, either to  the Jews or to the Greeks or to the church of God, <sup class="versenum" id="en-NKJV-28597">33</sup> just as I also <b>please all <i>men</i> in all  <i>things,</i> not seeking my own profit, but the <i>profit</i> of  many, that they may be saved.</b><br /><br /><br /><br /><b>&nbsp;I see here a list, but if you are paying attention it's not the list many of us would come up with when thinking of SIN. This list was written TO God's people ABOUT God's People and therefore is a warning to all of us who ARE God's People.&nbsp;</b><br /><b><br /></b><br /><ul><li><b>Idolaters</b></li><ul><li><b>Sat down to: Eat, Drink, and Play</b></li></ul><li><b>Sexually Immoral</b></li><ul><li><b>23,000 Fell</b></li></ul><li><b>&nbsp;Tempt Christ</b></li><ul><li><b>Destroyed by serpents</b></li></ul><li><b>Complained</b></li><ul><li><b>Destroyed by Destroyer</b></li></ul></ul><b></b><br /><b><br /></b><br /><b>If I asked you to pick the SIN plaguing the church today is this the list you would choose?</b><br /><b><br /></b><br /><ul><li><b>Have I made Food, Drink, or Fun a higher priority than God?&nbsp;</b></li><li><b>Have I kept a TIGHT reign on the images and thoughts I allow?</b></li><ul><li><b>Including Shows and Commercials I allow in front of me?</b></li></ul><li><b>Have I Tempted Christ?</b></li><ul><li><b>Have I made light of the Anointing or Anointed One?</b></li><li><b>Have I failed to Factor God IN to the situations I face?</b></li><ul><li><b>The Israelites Complained against God instead of asking him when they wanted something.&nbsp;</b></li><li><b>"Why did He bring us here to die of Thirst?" VS "God, you brought us here, please give us water."</b></li></ul></ul><li><b>Complaining is EVIL. It automatically means: I don't trust God. Period. ANY complaining is failure to Trust in God.&nbsp;</b></li></ul><b></b><br /><b><br /></b><br /><b>Finally I noticed that MOTIVE is the Key to my interaction with Others and my Work Ethic before God.&nbsp;</b><br /><b><br /></b><br /><b><br /></b><br /><b>Am I doing everything as I report to HIM and not to man? Am I seeking OTHERS benefit above my own? That is a question I must re ask every day!</b><br /><b><br /></b><br /><b>Darrell G. Wolfe</b><br /><b><br /></b>