---
title: 'R.E.S.P.E.C.T....       Find out what it means to God!'
date: '2010-01-17T05:26:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6039931524841902974'
blogger_filename: '/2010/01/respect-find-out-what-it-means-to-god.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

01/16/2010 <br /><br />&nbsp;&nbsp;&nbsp;&nbsp; God told me something tonight that I had let slip from the forefront of my development. It's important and vital to long lasting growth.<br /><br /><span style="font-size: large;"><b>"Respecting ineffective leaders is just as important as learning to BE an effective leader!"&nbsp;</b></span><br /><br /><ul><li>It's one thing to study to show thyself approved a workman not needing to be ashamed but rightly dividing the Word of Truth!</li></ul><span style="font-size: xx-small;"></span><br /><h2 id="passage_heading"><span style="font-size: xx-small;"><a href="http://www.biblegateway.com/passage/?search=2%20Timothy%202:15&amp;version=KJV">2 Timothy 2:15</a>&nbsp;(King James Version)</span></h2><br /><span style="font-size: xx-small;">&nbsp;<sup class="versenum" id="en-KJV-29843">15</sup>Study to shew thyself approved unto God, a workman that needeth not to be ashamed, rightly dividing the word of truth.</span><br /><br /><br /><ul><li><span style="font-size: xx-small;"><span style="font-size: small;">It's another to know that a leader could have done better and didn't. Or think that you may have done differently.&nbsp; Or in any way criticize their leadership or decision. You cannot place a value of good or bad on their decision, it's not your place. <br /></span></span></li></ul><span style="font-size: xx-small;"><span style="font-size: small;"></span></span><br /><span style="font-size: xx-small;"><strong><a href="http://www.biblegateway.com/passage/?search=Romans+14:4&amp;version=NKJV">Romans 14:4</a></strong><br />Who are you to judge another’s servant? To his own <b>master</b> he <b>stands</b> or falls. Indeed, he will be made to stand, for God is able to make him stand.</span><span style="font-size: xx-small;"><span style="font-size: small;"> </span></span><br /><span style="font-size: xx-small;"><span style="font-size: small;"><br /></span></span><br /><ul><li><span style="font-size: xx-small;"><span style="font-size: small;">You simply see that it is their decision to make and ask God how you are going to fit yourself into or around it. In doing so you walk in the LOVE of Godand immediately put Psalms 91 and Psalms 103 and 2 Corinthians 9 into effect!&nbsp;</span></span></li></ul><h4><a href="http://www.biblegateway.com/passage/?search=Psalms%2091&amp;version=KJV"><span style="font-size: xx-small;">Psalm 91</span></a></h4><span style="font-size: xx-small;">&nbsp;<sup class="versenum" id="en-KJV-15403">7</sup>A thousand shall fall at thy side, and ten thousand at thy right hand; but it shall not come nigh thee.&nbsp;</span><br /><span style="font-size: xx-small;">&nbsp;</span><span style="font-size: xx-small;">&nbsp;</span><br /><b><a href="http://www.biblegateway.com/passage/?search=Psalms%20103&amp;version=KJV"><span style="font-size: xx-small;">Psalm 103</span></a></b><br /><h4></h4><span style="font-size: xx-small;">2...forget not all his benefits</span><br /><span style="font-size: xx-small;"><sup class="versenum" id="en-KJV-15556">6</sup>The LORD executeth righteousness and judgment for all that are oppressed.&nbsp;<sup class="versenum" id="en-KJV-15560">&nbsp;</sup></span><br /><span style="font-size: xx-small;"><sup class="versenum" id="en-KJV-15560">10</sup>He hath not dealt with us after our sins; nor rewarded us according to our iniquities.</span> <br /><span style="font-size: xx-small;"></span><br /><h4><a href="http://www.biblegateway.com/passage/?search=2%20corinthians%209&amp;version=KJV"><span style="font-size: xx-small;">2 Corinthians 9</span></a></h4><span style="font-size: xx-small;">&nbsp;<sup class="versenum" id="en-KJV-28965">8</sup>And God is able to make all grace abound toward you; that ye, always having all sufficiency in all things, may abound to every good work:</span><br /><br /><br /><span style="font-size: small;"></span><ul><li><span style="font-size: small;">When you do that, you activate THE BLESSING in your life. You will benefit from it no matter what! God will work that thing around and around until it works out for your benefit!&nbsp;</span></li></ul><span style="font-size: xx-small;">&nbsp;<strong><a href="http://www.biblegateway.com/passage/?search=Romans+8:28&amp;version=NKJV">Romans 8:28</a></strong><br />And we know that all <b>things</b> <b>work</b> together for <b>good</b> to those who love God, to those who are the called according to His purpose.</span><span style="font-size: small;"> </span><br /><ul><li><span style="font-size: small;">SO many well meaning and deceived christians have misunderstood this verse and thought it was saying the exact opposite of what it said.&nbsp;</span></li><ul><li><span style="font-size: small;">They say things like:&nbsp;</span></li><ul><li><span style="font-size: small;">"Well I guess God has a lesson for me in this."&nbsp;</span></li><li><span style="font-size: small;">Or&nbsp;</span></li><li><span style="font-size: small;">"God is going to use this to teach me something." They often qoute this verse after saying this.&nbsp; </span></li></ul><li><span style="font-size: small;">What God is saying is NOT:</span></li><ul><li><span style="font-size: small;">"I intended (or "Allowed") this because it'll be good for you. I know that broken leg hurts, but it's to teach you patience."</span></li></ul><li><span style="font-size: small;">God is not a bully.&nbsp;</span></li><ul><li><span style="font-size: small;">He says that a good father doesn't give a rock when His kids ask him for bread. </span><span style="font-size: xx-small;"><strong><a href="http://www.biblegateway.com/passage/?search=Luke+11:11&amp;version=NKJV">Luke 11:11</a></strong></span></li></ul><li><span style="font-size: xx-small;"><strong><span style="font-size: small; font-weight: normal;">The Holy Spirit is the teacher of the church! Not situations! &nbsp; </span><span style="font-size: small;"><br /></span></strong></span></li><li><span style="font-size: small;">God is saying: "The thief comes to steal, kill, destroy... but I have come that they may have life, and life MORE ABUNDANTLY!"</span><span style="font-size: xx-small;"><strong><a href="http://www.biblegateway.com/passage/?search=John+10:10&amp;version=NKJV">John 10:10&nbsp;</a></strong></span></li><li><span style="font-size: small;"><strong><span style="font-weight: normal;">I</span><span style="font-weight: normal;"> will work this out for your good DESPITE the devils attempt to take you out. Take a step back behind me, trust me, walk in love because I cannot work on your behalf if you violate the commandment of LOVE. I'll turn this on it's head and work it around and around until you benefit. Jail was NEVER God's will for <a href="http://www.biblegateway.com/passage/?search=Genesis+41:46&amp;version=NKJV">Joseph</a>, but He worked it and worked it until Joseph was promoted to 2nd to Pharaoh!<br /></span></strong></span></li></ul></ul><span style="font-size: small;"><br /></span><br /><span style="font-size: small;">Darrell G. Wolfe&nbsp;</span><span style="font-size: xx-small;"><span style="font-size: small;"> </span></span>