---
title: 'Hear More Do More'
date: '2011-10-07T15:44:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4312514453693041847'
blogger_filename: '/2011/10/hear-more-do-more.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

Daily Reading 10/06/2011 &nbsp;<b>Connect to the Word Source</b><br /><br /><b>COME:</b><br /><a href="http://www.biblestudytools.com/nkjv/2-timothy/passage.aspx?q=2-timothy+3:14-17">&nbsp;<b>2 Timothy 3:14-17</b></a><br /><span class="Apple-style-span" style="font-family: arial; font-size: 14px; line-height: 20px;"><span class="versetext" id="2ti3-14" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">14</span>&nbsp;<b>But you must continue in the things which you have learned and been assured of, knowing from whom you have learned them</b>,&nbsp;</span><span class="versetext" id="2ti3-15" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">15</span>&nbsp;and that from childhood you have known the Holy Scriptures, which are able to make you wise for salvation through faith which is in Christ Jesus.&nbsp;</span><span class="versetext" id="2ti3-16" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">16</span><b>All Scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness,&nbsp;</b></span><span class="versetext" id="2ti3-17" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><b><span class="versenum" style="margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">17</span>&nbsp;that the man of God may be complete, thoroughly equipped for every good work.</b></span></span><br /><br /><b>HEAR:</b><br />We all have sources that we feed from spiritually. Even the unsaved have spirits and&nbsp;their&nbsp;spirits feed on words from some source. Some sources are close to us: father, mother, aunt, uncle, grandmother, close friend or associate. Some sources feel close but are not as&nbsp;tangibly&nbsp;accessible: Preacher, Pastors, Generals of the Faith, those who have passed long ago but left their words to read or hear. One source is&nbsp;unchangeable&nbsp; and that is the Word of God.<br /><br />Often times we idolize out&nbsp;heroes. We put up posters of rock stars, movie stars, and even stars in the body of Christ. Rightfully we should praise our heroes in the church. People who sacrifice to bring us the word should be the ones we want to emulate. The bible says to imitate those who through faith and patience inherit the promises. <a href="http://www.biblestudytools.com/nkjv/hebrews/6-12.html">(Heb 6:12)</a>.<br /><br />However, we do also do ourselves an injustice if we turn the praise into worship and forget that these men and women of faith are in fact men and women. I don't say this to knock them down or even point out their flaws. But I say this because I find in myself a flaw. If I treat these men and women as superheroes I begin to think to myself that I can't do what they do. It was for this reason that Jesus kept pointing to himself as the <a href="http://www.biblestudytools.com/search/?q=%22son+of+man%22&amp;c=nt&amp;t=nkjv&amp;ps=10&amp;s=Bibles">Son of Man </a>and saying things like "Why do you marvel? You could do this too..." (<a href="http://www.biblestudytools.com/nkjv/mark/passage.aspx?q=mark+11:15-25">Mark 11:15-25</a> and <a href="http://www.biblestudytools.com/nkjv/luke/8-25.html">Luke 8:25</a>) Peter copied this when he was looked at in amazement for bringing healing to a crippled man. (<a href="http://www.biblestudytools.com/nkjv/acts/3-12.html">Acts 3:12</a>)<br /><br />In order to imitate them I must not downgrade them, but I must remember that they are in fact mere humans serving a supernatural God and filled with a supernatural Holy Spirit. So they ARE superheroes but so am I! If I gain that perspective than I am able to walk that out in my daily life.<br /><br />I also realize that this means I need to pay attention to the sources I gain my information from. Am I spending more time listening to the news broadcasters than I am the preached Word? I need to go back to my roots and immerse myself in the Word. If I'm driving I should listen to the Word being taught instead of listening to the radio and news.<br /><br /><b>DO:</b><br />Remind myself that I am full of the same spirit that dwells in those I feed from. If they can move mountains so can I. We serve the same Lord and are filled with the same Holy Spirit!<br /><br />I will feed myself on the Word instead of listening to news broadcasters on my drives to work.<br /><br /><b>My Prayer:</b><br />Father, thank you for your Word and the gifts you've given me in the form of the Apostle, Prophet, Evangelist, Pastor, and Teacher. I will feed on the word spoken by them as well as the written Word. Thank you for using this immersion to create a new vigor and strength in my spirit to overcome all odds.<br /><br />Darrell G. Wolfe