---
title: 'Fathers'
date: '2011-09-16T04:03:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2709889777784069740'
blogger_filename: '/2011/09/fathers.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Prayer Time'
  - 'Daily Reading'
---

<b>1 Thessalonians 2:11-12</b><br /><b><br /></b><br /><b>The New English Bible (Out of Print):</b><br />"As you well know, we dealt with you one by one, as a father deals with his children, appealing to you by encouragement, as well as by solemn injunctions, to live lives worthy of the God who calls you into his kingdom and glory. "<br /><br /><b>The Good News Translation:</b><br />You know that we treated each one of you just as parents treat their own children. We <b>encouraged </b>you, we <b>comforted </b>you, and we kept <b>urging </b>you to live the kind of life that pleases God, who calls you to share in his own kingdom and glory.<br /><br />Fathers are to encourage, comfort, and urge, but not cause anger or frustration in their kids. Something to think about. Instead of being angry all the time because their noisy... frustrated when they don't listen... happy when they go to bed... try taking a few moments to tell them how good a job they do, how lovely they are, how they are worth something to you and God. Catch them doing something right, instead of catching them doing something wrong. Double, Tripple, Exponentially increase the amount of Praise you give your kids. Despite what the idiots who give advice these days tell you, there is no such thing as too much praise.<br /><br />Yes, there will be times when you must correct. But do it with a gentle but firm hand. Do it in love. Don't just spout off about what they did wrong. Take time to explain why they must change, encourage them that correction is about behavior and not about them personally, that there is nothing wrong with them just because they did something wrong. Have them ask for forgiveness, forgive them, and NEVER mention that offense again. Saying "You always..." is an&nbsp;exaggeration&nbsp;and will only serve to increase their awareness of that rather than their awareness of the good thing they are to do. You want to sow "Always Bad" seed, you will get always bad harvest. Don't go there.<br /><br />Praise, Encourage, Comfort, Urge... With a little correction. Keep the balance 90-10. 90% Praise 10% correction. Most people don't have a problem with under correction a child, rather with incorrectly correcting and not praising them enough. <br /><br />DW<br /><br /><span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 12px;"></span><br /><ul id="Page-1" style="display: block; list-style-image: initial; list-style-position: initial; list-style-type: none; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 10px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-image: initial; list-style-position: initial; list-style-type: none; margin-bottom: 15px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><h4 class="ResultTitle" style="clear: left; font-size: 17px; font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">    <a href="http://www.biblestudytools.com/nkjv/luke/1-17.html" style="background-color: #660000; text-decoration: underline;"><span class="Apple-style-span" style="color: white;">Luke 1:17 NKJV</span></a></h4><div class="ResultText" style="font-size: 14px; margin-bottom: 3px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="Apple-style-span" style="background-color: #660000;"><span class="Apple-style-span" style="color: white;">He will also go before Him in the spirit and power of Elijah, 'to turn the hearts of the&nbsp;<span class="Highlight" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 2px; padding-right: 2px; padding-top: 0px;">fathers</span>&nbsp;to the<span class="Highlight" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 2px; padding-right: 2px; padding-top: 0px;">children</span>,' and the disobedient to the wisdom of the just, to make ready a people prepared for the Lord."</span></span></div><div class="QuickLinks" style="margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="Apple-style-span" style="background-color: #660000;"><span class="Apple-style-span" style="color: white;"><a href="http://www.biblestudytools.com/nkjv/luke/1.html" style="text-decoration: none;">Read Luke 1</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Luke+1:17" style="text-decoration: none;">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/luke/1-17-compare.html" style="text-decoration: none;">Compare Translations</a></span></span></div></li><li style="list-style-image: initial; list-style-position: initial; list-style-type: none; margin-bottom: 15px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><h4 class="ResultTitle" style="clear: left; font-size: 17px; font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">    <a href="http://www.biblestudytools.com/nkjv/ephesians/6-4.html" style="background-color: #660000; text-decoration: none;"><span class="Apple-style-span" style="color: white;">Ephesians 6:4 NKJV</span></a></h4><div class="ResultText" style="font-size: 14px; margin-bottom: 3px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="Apple-style-span" style="background-color: #660000;"><span class="Apple-style-span" style="color: white;">And you,&nbsp;<span class="Highlight" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 2px; padding-right: 2px; padding-top: 0px;">fathers</span>, do not provoke your&nbsp;<span class="Highlight" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 2px; padding-right: 2px; padding-top: 0px;">children</span>&nbsp;to wrath, but bring them up in the training and admonition of the Lord.</span></span></div><div class="QuickLinks" style="margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="Apple-style-span" style="background-color: #660000;"><span class="Apple-style-span" style="color: white;"><a href="http://www.biblestudytools.com/nkjv/ephesians/6.html" style="text-decoration: none;">Read Ephesians 6</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Ephesians+6:4" style="text-decoration: none;">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/ephesians/6-4-compare.html" style="text-decoration: none;">Compare Translations</a></span></span></div></li><li style="list-style-image: initial; list-style-position: initial; list-style-type: none; margin-bottom: 15px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><h4 class="ResultTitle" style="clear: left; font-size: 17px; font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">    <a href="http://www.biblestudytools.com/nkjv/colossians/3-21.html" style="background-color: #660000; text-decoration: none;"><span class="Apple-style-span" style="color: white;">Colossians 3:21 NKJV</span></a></h4><div class="ResultText" style="font-size: 14px; margin-bottom: 3px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="Apple-style-span" style="background-color: #660000;"><span class="Apple-style-span" style="color: white;"><span class="Highlight" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 2px; padding-right: 2px; padding-top: 0px;">Fathers</span>, do not provoke your&nbsp;<span class="Highlight" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 2px; padding-right: 2px; padding-top: 0px;">children</span>, lest they become discouraged.</span></span></div><div class="QuickLinks" style="margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="Apple-style-span" style="background-color: #660000;"><span class="Apple-style-span" style="color: white;"><a href="http://www.biblestudytools.com/nkjv/colossians/3.html" style="text-decoration: none;">Read Colossians 3</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=Colossians+3:21" style="text-decoration: none;">View in parallel</a>&nbsp;|&nbsp;<a href="http://www.biblestudytools.com/colossians/3-21-compare.html" style="text-decoration: none;">Compare Translations</a></span></span></div></li></ul>