---
title: 'Hearing and Obeying God'
date: '2011-09-28T03:58:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '266077891712866484'
blogger_filename: '/2011/09/hearing-and-obeying-god.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'Random'
  - 'Daily Reading'
---

<a href="http://www.biblestudytools.com/nkjv/1-samuel/passage.aspx?q=1+samuel+22;1+samuel+23">1 Samuel 22-23</a><br /><br />I see David here is a man of action. He doesn't spend a lot of time preaching to the men to get up and get over it! Rather, he inquires of the Lord frequently (which doesn't sound like an action sometimes to the men wanting a fight, but it is). He get's a clear and direct answer, yes or no. Then he does whatever it is without delay.<br /><br />I could learn a lesson here from David. Even though I have the Holy Spirit in me now and he didn't, the lesson still applies. David didn't just ask a general question and wait for God to come down and write on the walls or hand him a&nbsp;divine&nbsp;GPS. Instead he had some options in front of him, but waited to hear clearly Yes or No? Kenneth Copeland talks about this from time to time. Learn to hear the voice of God. Start by small things, yes or no things. Is this outfit your choice today? Yes or No? Should we see that movie Yes or No? Should we go to A or B?<br /><br />Then wait...wait for it... wait for it... an answer will bubble up to the top. If at first both answers seem just as likely and bubble up the same what should I do? Wait for it... wait for it... wait for it............. Eventually as I test the peace one will take the top. I may even say "Is it A?" and then check my gut.... than ask: "Is it B?" and check my gut. This takes practice.<br /><br />Is it&nbsp;imperative&nbsp;that I wear the right shirt today? Maybe not. Sure there could be reason that it might matter, but on any given day it probably won't matter which shirt I wear. However the more clearly I hear him today in the little things, the more clearly I will hear him in the BIG things.<br /><br />I also see in David another trait. He is demonstrating before his&nbsp;troupes&nbsp;the fine line between self preservation and self righteousness. In the case of a declared common enemy he leads them&nbsp;boldly&nbsp;into battle, after inquiring of the Lord first! In the case of Saul God's anointed, his leader who he submits to out of position even if he's not worthy of it... He chooses to hide, run, hide again... cut's a corner from his robe and apologizes for it. He has deep respect for authority, even if it's misused.<br /><br />David is able to humble himself to do that which is uncomfortable and maybe even unpopular in order to preserve the Anointing on His life.<br /><br /><a href="http://www.biblestudytools.com/nkjv/1-samuel/passage.aspx?q=1-samuel+28:16-20">1 Sam 28:16-20</a>. Anointing can be lost through even small disobedience. Which is why if I take the time to ask the Lord what I should do... I must do it and not ignore, schluff off, brush off, or otherwise not take very seriously what the Lord said. This is where I've missed it time and again. I get his call on something seemingly trivial and then say.... no no, I don't want to do that.... then when the big matters come I hear static and silence. I'm not tuned in, and can't be under pressure if I wasn't tuned in without pressure.<br /><br /><br />Good thoughts to think about... ponder... meditate... consider... image... imagine... dream about...<br /><br />Darrell G. Wolfe<br /><br /><br /><br /><br />