---
title: 'Power to Witness'
date: '2011-05-06T14:39:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1301938903450094829'
blogger_filename: '/2011/05/power-to-witness.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'Daily Reading'
---

05.06.2011&nbsp;&nbsp; <a href="http://www.biblegateway.com/passage/?search=acts%201&amp;version=NKJV">Acts 1</a><br /><br /><br /><strong>"</strong>&nbsp;<sup class="versenum" id="en-NKJV-26926"><strong><span style="font-size: x-small;">6</span></strong></sup> Therefore, when they had come together, they asked Him, saying, “Lord, will You at this time restore the kingdom to Israel?” <sup class="versenum" id="en-NKJV-26927"><strong><span style="font-size: x-small;">7</span></strong></sup> And He said to them, “<strong>It is not for you</strong> to know times or seasons which the Father has put in His own authority.<strong><sup><span style="font-size: x-small;">8</span></sup></strong> But <strong>you shall receive power</strong> when the Holy Spirit has come upon you; and <strong>you shall be witnesses</strong> to Me<br /><br /><br />The Holy Spirit will come to bring POWER TO WITNESS. The lots cast by Peter regarding the replacement for Judas were the last lots cast to make a decision. The Holy Spirit, not dice, would now move and decide for His Church. It was not until POWER came that Peter became the witness Jesus asked him to become back on that beach in John 21. Truely he was out of line making any decision on a replacement until the Power came. <br /><br /><br />Power to Witness....<br />Power to Wintess...<br />Power to Witness...<br /><br />This is missing in the church, in my life even to a large extent these days... Power to Witness... Hmm....<br /><br /><br /><br /><strong>Side Note:</strong> of all he doesn't say that no one can ever know, He says that it's not for THEM to know. Even earlier in his ministry before the cross he didn't say no one will ever know. He said that no one knows... as in no one right at this moment knows accept the Father. <br /><br />See: <a href="http://www.biblegateway.com/keyword/?search=day%20or%20hour&amp;version1=50&amp;searchtype=all">Day or Hour:</a><br />Matthew 24:36<br /><br />“But of that day and hour no one knows, not even the angels of heaven, but My Father only.<br />Mark 13:32 <br /><br />“But of that day and hour no one knows, not even the angels in heaven, nor the Son, but only the Father.