---
title: 'Humble yourself to prosper'
date: '2011-11-15T13:26:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2466391190542068778'
blogger_filename: '/2011/11/humble-yourself-to-prosper.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><b><a href="http://www.biblestudytools.com/nkjv/1-peter/5.html" target="_blank">1 Peter 5</a></b><br />6 Therefore humble yourselves under the mighty hand of God, that He may exalt you in due time, 7 casting all your care upon Him, for He cares for you.                                                                          <br /><br /><b>HEAR:</b><br />Pride says: I can do this on my own. The definition of humble is not about getting rid of things, being poor, putting yourself down, saying "I'm not worthy...", or any other such non sense. The definition of humble is acknowledging that you are not God, and rolling the care of your life over onto Him. You do your part. Let Him do His.<br /><br />For most of us this plays out silently and secretly. We say we love God, we go to church, we sing songs. We simply ignore Him Monday through Saturday. Or, we do pray daily, read the Word daily, but our prayer is one sided. It comes out like a request list or a check list of things to say to God.<br /><br />The trick with this kind of humility is that we must get before God, openly and honestly. Have a two way dialogue about situations.<br /><br />"Father, I need______Tires (or fill in the blank)____. You meet all my needs according to your riches. You give me all things to richly enjoy. So how would you have me believe you for this need?"<br /><br />Then stop and listen, pray in tongues, it may take more than 5 minute. You may have to pray quietly about this for the rest of the day or even two or three days. The point is that you don't move on this need until he tells you something. If the need is immediate he may give you a temp fix answer and a more&nbsp;permanent&nbsp;answer sometimes too. His Mercy is new every morning.<br /><br />What this does is build confidence into your answer. You could flip to your favorite provision scripture and make confessions over the issue. This will have some effect. But unless you got the Holy Spirit involved and got HIS take on the situation you won't have the confidence behind your confession. You'll be saying it, but not feeling any power of belief behind it.<br /><br />Faith is trust. Faith is confidence. Confidence in what? Confidence that God's Word is true. If I say that I'll be at your house Friday morning to pick you up, you have three responses. "I believe him." or "I guess we'll see what he does?" or "I doubt it." Each response is based on a level of confidence in my word. The confidence will be based on how long you've known me and my character. If you've known me for ten years but always known me to be a flake, than you will see my word as "We'll see" or "I doubt it". If you've known me for a month, but seen me faithful and diligent at work each day than you could respond "I&nbsp;believe&nbsp;him."&nbsp;Your confidence will be based on what I said, and how you've experience me so far.<br /><br />Therefore unless you get God's word on the situation you won't know what to have confidence in. Many people have pulled&nbsp;scriptures&nbsp;at random and gotten no results. You must see the situation from God's perspective. Two similar situations could have different roots. You must ask God, who sees the roots, what He would have you do about the situation. Only then, can you have the confidence to see it through to completion.<br /><br /><b>DO:</b><br />I'm going to take more time to follow this advice. Pray about a situation until I have an answer. Then I will have the confidence to follow through with that answer.<br /><br /><b>PRAYER:</b><br />"Father, I need______Tires (or fill in the blank)____. You meet all my needs according to your riches. You give me all things to richly enjoy. So how would you have me believe you for this need?"<br /><br /><b>Darrell G. Wolfe</b>