---
title: 'People Matters'
date: '2011-10-07T16:14:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '995298403678609841'
blogger_filename: '/2011/10/people-matters.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>Daily Reading Friday 10/07/2011 &nbsp;- &nbsp;Love</b><br /><br /><b>COME:</b><br /><b><a href="http://www.biblestudytools.com/nkjv/2-timothy/passage.aspx?q=2-timothy+4:9-22">2 Timothy 4:9-22</a></b><br /><span class="Apple-style-span" style="font-family: arial; line-height: 20px;"><span class="versetext" id="2ti4-9" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">9</span>&nbsp;<b>Be diligent to come to me quickly</b>;&nbsp;</span><span class="versetext" id="2ti4-10" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">10</span>&nbsp;for <b>Demas </b>has forsaken me, having loved this present world, and has departed for Thessalonica--<b>Crescens </b>for Galatia, <b>Titus </b>for Dalmatia.&nbsp;</span><span class="versetext" id="2ti4-11" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">11</span>&nbsp;Only <b>Luke </b>is with me. Get <b>Mark </b>and bring him with you, for he is useful to me for ministry.&nbsp;</span><span class="versetext" id="2ti4-12" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">12</span>&nbsp;And <b>Tychicus </b>I have sent to Ephesus.&nbsp;</span><span class="versetext" id="2ti4-13" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">13</span>&nbsp;Bring the cloak that I left with <b>Carpus </b>at Troas when you come--and the books, especially the parchments.&nbsp;</span><span class="versetext" id="2ti4-14" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">14</span>&nbsp;<b>Alexander </b>the coppersmith did me much harm. May the Lord repay him according to his works.&nbsp;</span><span class="versetext" id="2ti4-15" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">15</span>&nbsp;You also must beware of him, for he has greatly resisted our words.&nbsp;</span><span class="versetext" id="2ti4-16" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">16</span>&nbsp;At my first defense no one stood with me, but all forsook me. May it not be charged against them.&nbsp;</span><span class="versetext" id="2ti4-17" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">17</span>&nbsp;But the Lord stood with me and strengthened me, so that the message might be preached fully through me, and that all the Gentiles might hear. And I was delivered out of the mouth of the lion.&nbsp;</span><span class="versetext" id="2ti4-18" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">18</span>&nbsp;And the Lord will deliver me from every evil work and preserve me for His heavenly kingdom. To Him be glory forever and ever. Amen!&nbsp;</span><span class="versetext" id="2ti4-19" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">19</span>&nbsp;<b>Greet Prisca and Aquila</b>, and the household of <b>Onesiphorus</b>.&nbsp;</span><span class="versetext" id="2ti4-20" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">20</span>&nbsp;<b>Erastus </b>stayed in Corinth, but <b>Trophimus </b>I have left in Miletus sick.</span><span class="versetext" id="2ti4-21" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">21</span>&nbsp;Do your utmost to come before winter. <b>Eubulus </b>greets you, as well as <b>Pudens</b>, <b>Linus</b>, <b>Claudia</b>, and<b> all the brethren</b>.&nbsp;</span><span class="versetext" id="2ti4-22" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">22</span>&nbsp;The<b> Lord Jesus Christ&nbsp;<a href="http://draft.blogger.com/blogger.g?blogID=6583916183087899714" name="a"></a>be with your spirit</b>. Grace be with you. Amen.</span></span><br /><br /><b>HEAR:</b><br />I'd never quite noticed how many names Paul mentioned in his letters, especially this letter. This was among the last things Paul ever wrote. Here Paul is at the end of his life and he is reflecting on the lives that he has touched and those that touched him. He is handing&nbsp;responsibility&nbsp;to Timothy for those he cared for by giving status and whereabouts for each. If the most important things people say are what they say at the end of life reflecting back on a life of triumphs and&nbsp;defeats, Paul here is showing us how much people matter.<br /><br />It's not so much about the buildings you build, the empires you created, the art you painted, the stories you wrote, the businesses you ran, <a href="http://www.visionforum.com/news/blogs/doug/2011/10/9697/?fb_ref=blogindex&amp;fb_source=profile_oneline">the things you invented.</a>.. It's about the people you affected. More specifically it's about the people you affected for eternity. Mankind has had many great minds that deeply affected the lives of many around them and some that didn't even know they were being affected by them, but made no eternally significant impact.<br /><br /><b>DO:</b><br />What I do only matters in regards to who I affect and how I affect them. May I always remember to love my family and care for their needs as more important than my business ventures. May I remember that the people I sell to need the Spirit inside me more than they need my empty words and temporal products. May I enrich the lives of all those who I come in contact with.<br /><b><br /></b><br /><b>My Prayer:</b><br />Father, you have birthed inside of me<b><a href="http://www.biblestudytools.com/nkjv/romans/5-5.html">&nbsp;YOUR HEART</a></b>... help me&nbsp;exercise&nbsp;it like a muscle and grow in my capacity to use <b>LOVE </b>as a tool for great impact on the world around me.<br /><b><br /></b><br /><b>Darrell G. Wolfe</b>