---
title: 'Stir Up the Gift of God! Part 2'
date: '2011-10-04T18:46:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3319914302170905796'
blogger_filename: '/2011/10/stir-up-gift-of-god-part-2.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'Daily Reading'
---

<br /><a href="http://www.biblestudytools.com/nkjv/2-timothy/1.html">2 Timothy 1</a><br /><br /><b>Vs 6-7</b><br />Therefore I remind you to&nbsp;<b>stir up the gift</b>&nbsp;of God which is in you through the laying on of my hands. For&nbsp;<b>God has not given us a spirit of fear</b>, but of power and of love and of a sound mind.<br /><br />Stir up the gift of God <b>BECAUSE</b>... he has not given us a spirit of fear...<br /><br />Apparently<b> there is a fear that will come against you and your calling.</b> Fear will try to prevent you from fulfilling you destiny and reaching your destination. One of Timothy's fears was that he was too young to be holding his office of pastor.<br /><br />There are many <b>common fears/excuses</b> that the devil feeds people about their calling. Some of those are:<br /><br />I'm too young, too old, too inexperienced, too far down a different track, not enough time to get it done, too much time to go that way now (I'm too old to go back to school that would take 5 years)... etc etc<br /><br />Part of the reason you must<b> stir up the giftings</b> in you is because fear will try to prevent you from using them.<br /><br />You hear things in your head like: "You can't be a pastor after all you've done! Just the other day you did XYZ..."<br /><br />I can't be a musician... I'm not as good as person a, b, and c that I know. I don't know where to start, I can't go back to school, I don't have a teacher to help me learn, etc etc....<br /><br />Fear is the reason you are not pursuing all you are called to do. I can't leave that job, I can't move from that house, <b>I can't... I can't... I can't....&nbsp;</b><br /><br /><b>BUT GOD CAN! GOD WILL!</b><br /><br />Rather than meditating on the fear you have been fighting (or indulging) about why you can't... stir&nbsp;yourself&nbsp;up regarding your call and gift. God knew me before the foundation of the world. He called me for such a time as this. He called me before I was born to do the things he called me to do. I&nbsp;recognize&nbsp;and embrace that he has called me to writing, teaching, music, and more. I say that if GOD called me to it, than he has a purpose and a plan. His plans for me are for good and not for harm. Therefore I say "Here I am Lord, send me!".<br /><br />Like David seeing fear prevent the&nbsp;Israelites&nbsp;from conquering their giant enemy, I must say I'll do it!<br /><br />Darrell G. Wolfe<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />