---
title: 'Driving'
date: '2011-04-21T04:10:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3227745568120804936'
blogger_filename: '/2011/04/driving.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Mid-Evil Times'
---

Erik Liechter was driving the family home from a long day out and about. They had worked there way so far into the other side of the metroplex that it would now take an hour to get home, he was on the final stretch of that hour and getting quite tired. Wife and kids were asleep a half hour ago.<br /><br />Erik was distracted by many thoughts about things he wanted to do in life but hadn't, and things he intended to do but never got around to, and duties of tomorrow morning. He tried not to bring work home with him, but nevertheless, he did.<br /><br />It was somewhere in those thoughts that he found himself drifting into a sea of emotions and images and when he began seeing a images of flying people and impossible things happening all around him... The bumping and jarring of the vehicles snapped him into reality and he realized he'd been dreaming. The next few moments were like slow motion. His heart full of rushing incoming adrenaline began to pump faster and his mind pulled out of the sluggish haze it had succumbed to. Through his blurred vision he could see that he had veered off the road into the overgrown side fields, he glanced around to see his whole family still asleep, and all this happened within fractions of a second. He turned forward just in time to see the car headed towards a tree and realized that he wasn't even holding on the wheel. He tried to grasp for the wheel but it was too late the tree was coming and he put his hands up preparing for impact, he let out a quick "Please GOD! NO!" before the moment came he closed his eyes... nothing, darkness, dreams, void.<br /><br />When he came to himself there was light warming his cheek and he stirred. At first he thought he must be at home but then images of last night came to his mind and he didn't want to open his eyes to see what carnage awaited. He couldn't feel anything broken and he sat forward and rubbed his eyes and opened them, the bright light around him stung and blinded him so he closed them again. As his vision returned he found himself not in the drivers seat of a Lexus SUV but on the ground in a sleeping bag. He turned to see his family around him, also in sleeping bags. The material made of old, musty cloth.<br /><br />His mind was still processing and confused, he turned around all about him, no car, no road, just his Wagon and Horses and campfire... Wagon and Horses?!? He felt srongly that these were his, but had no idea why. Just then his son, Kenny age 6, stirred and sat up, he must have had the same reactions by the looks that went through his face in just moments. His wife and younger son and daughter still slept. Kenny stood up, "Where's the car Dad? What happened?" Erik shrugged, "I have no idea what's going on here son, but stay close." The two stood up and looked all around. No car, no road, nothing that smelled of civilization. That's when they noticed each others clothes. They each looked like something out of a Mid-Evil Times Show. Nothing made sense. It wasn't funny but out of nervousness they both laughed...