---
title: 'Last Days and Eternal Glory!'
date: '2011-12-30T20:29:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7236921969000018748'
blogger_filename: '/2011/12/last-days-and-eternal-glory.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b><a href="http://www.biblestudytools.com/nkjv/revelation/22.html" target="_blank">Revelations 22</a></b><br /><br />7 "Behold, I am coming quickly! Blessed is he who keeps the words of the prophecy of this book." <br />8 Now I, John, saw and heard these things. And when I heard and saw, I fell down to worship before the feet of the angel who showed me these things. 9 Then he said to me, "See that you do not do that. For I am your fellow servant, and of your brethren the prophets, and of those who keep the words of this book. Worship God."<br /><br /><br />Blessed/Empowered to Prosper is the person who keeps the words of the prophecy of this book. The book of revelations has been the most misunderstood book in the bible. People consider it shrouded in mystery and imagery and therefore too complex to understand. But the Word of God says here that keeping this book and it's words will empower you to prosper!<br /><br />All around us the signs of the end are rising. Wars, Famine, Earthquakes... All increasing in power and frequency. Demonic influence has begun to hit a new wave of boldness. Not since the days of Jesus earthly ministry has demons been so bold as to announce their presence and seek glory for it. They are traditionally hidden in side tracks and mystery. They have posed as Ghosts, Ghouls, Vampires,&nbsp;Werewolves, etc... They have played the not so subtle roles in witchcraft and other dark cults. They have shown them selves to people as aliens visiting from another planet. But they are getting bolder. TV series about ghost hunting are being taken series by the average person now. Genetic manipulation. They have even started cult followings saying that they are alien beings coming back to the planet they seeded/created using the names of God himself for their own (which can be seen by this example: rael.org).<br /><br />But under the radar... God will NOT be out matched... God is working on his Church. As with the showdown of <a href="http://www.biblestudytools.com/nkjv/1-kings/passage.aspx?q=1-kings+18:16-26" target="_blank">Baal vs God</a> in the days of Elijah there is a showdown coming. The final showdown will take place during a 7 year tribulation after the children of God, washed in the blood of Jesus, are evacuated from this planet. However these is a build up coming. I am seeing signs of it everywhere. TV has become a breeding ground for the devil but it's also being used to proclaim the gospel like never before!<br /><br />One sure way to know if you are dealing with Angels of God vs Fallen Angels/Demons is that Angels (As seen in Rev 22:8-9) will always point away from themselves to God. Position themselves as fellow servants of THE MASTER! Demons seek their own glory, sometimes subtle and most times not. They want to be viewed as god's and lords. They want to be seen as creators and masters.<br /><br />Read... study... Paul said that we should <a href="http://www.biblestudytools.com/search/?q=not+be+ignorant" target="_blank">NOT BE IGNORANT</a> of the times and happenings of God and the end times time table.<br /><br />These are the best times to live for the Body of Christ and worst time to live for the world. Are you ready, enthusiastic, excited about what God is doing and is about to do? If not you may be on the wrong side, or not sufficiently educated in your rights in Him! Get ready... Go... Fight... Win!!!<br /><br />Darrell G. Wolfe<br /><br />See:&nbsp;<a href="http://www.kcm.org/index.php?p=real_help_content&amp;id=1287">http://www.kcm.org/index.php?p=real_help_content&amp;id=1287</a>