---
title: 'Know His Will and Walk Worthy'
date: '2011-10-08T20:12:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1878887824583473232'
blogger_filename: '/2011/10/know-his-will-and-walk-worthy.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>Weekend Reading - 10/08/2011</b><br /><br /><b>COME:</b><br /><b><a href="http://www.biblestudytools.com/gnt/colossians/passage.aspx?q=colossians+1:9-14">Colossians 1:9-14</a></b><br /><span class="Apple-style-span" style="font-family: arial; font-size: 14px; line-height: 20px;"><span class="versetext" id="col1-9" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">9</span>&nbsp;For this reason we also, since the day we heard it, do not cease to pray for you, and to ask that <b>you may be filled with the knowledge of His will in all wisdom and spiritual understanding</b>;&nbsp;</span><span class="versetext" id="col1-10" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">10</span><b>&nbsp;that you may walk worthy of the Lord</b>, fully pleasing Him, being fruitful in every good work and increasing in the knowledge of God;&nbsp;</span><span class="versetext" id="col1-11" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">11</span>&nbsp;strengthened with all might, according to His glorious power, for all patience and longsuffering with joy;&nbsp;</span><span class="versetext" id="col1-12" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">12</span>&nbsp;giving thanks to the Father who has qualified us to be partakers of the inheritance of the saints in the light.&nbsp;</span><span class="versetext" id="col1-13" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">13</span>&nbsp;He has delivered us from the power of darkness and conveyed us into the kingdom of the Son of His love,&nbsp;</span><span class="versetext" id="col1-14" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">14</span>&nbsp;in whom we have redemption through His blood,&nbsp;<a href="http://draft.blogger.com/blogger.g?blogID=6583916183087899714" name="a"></a>the forgiveness of sins.</span></span><br /><br /><b>HEAR:</b><br />I hear here that being filled with the knowledge of His Will in all wisdom and spiritual understanding causes you to walk worthy of the Lord. Where two or more agree a thing may be established, therefore all I have to do is agree with Paul and the Holy Spirit to receive the intimate knowledge of His Will in all wisdom and spiritual understanding. I walk in faith which is what pleases Him. I am being fruitful in every good work. I am increasing in the knowledge of God. I am strengthened with all might (power and wealth), I have patience and longsuffing because of the Joy of knowing Him so I give thanks for the Father!<br /><br /><b>DO:</b><br />Remind myself of these things as often as I remember to do so.<br /><br /><b>My Prayer:</b><br />Father fill me, above all else, with the full and intimate knowledge of your Will in all spiritual wisdom and understanding.<br /><br /><b>Darrell G. Wolfe</b>