---
title: 'Steve Jobs Crosses Over'
date: '2011-10-07T02:35:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7193045511383210847'
blogger_filename: '/2011/10/steve-jobs-crosses-over.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Random'
---

<a href="http://www.visionforum.com/news/blogs/doug/2011/10/9697/">http://www.visionforum.com/news/blogs/doug/2011/10/9697/</a><br /><br />Steve Jobs, creator of Apple and products like iPhone and iPad left earth. The following article was posted by Doug Phillips and was so good I felt I wanted it posted here too so I can refer back to it from time to time. Read the article on his website at the link above.<br /><br />The following quote was at the end:<br /><br /><span class="Apple-style-span" style="background-color: white; font-family: 'Times New Roman', Times, serif; font-size: 15px; line-height: 18px;"><i></i></span><br /><div style="background-attachment: initial; background-clip: initial; background-color: initial; background-image: none; background-origin: initial; border-bottom-style: none; border-color: initial; border-left-style: none; border-right-style: none; border-top-style: none; border-width: initial; font-family: inherit; font-size: 1em; font: normal normal normal 14.5px/18px 'Times New Roman', Times, serif; line-height: inherit; margin-top: 15px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; position: relative; text-decoration: none; white-space: normal; z-index: 1;"><i>The death of all men remind us of the brevity of life, the lost condition of our souls, and the uselessness for earning eternal rewards through human accomplishments outside of Christ.</i></div><div style="background-attachment: initial; background-clip: initial; background-color: initial; background-image: none; background-origin: initial; border-bottom-style: none; border-color: initial; border-left-style: none; border-right-style: none; border-top-style: none; border-width: initial; font-family: inherit; font-size: 1em; font: normal normal normal 14.5px/18px 'Times New Roman', Times, serif; line-height: inherit; margin-top: 15px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; position: relative; text-decoration: none; white-space: normal; z-index: 1;"><i>“For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord” (Romans 6:23).</i></div><div style="background-attachment: initial; background-clip: initial; background-color: initial; background-image: none; background-origin: initial; border-bottom-style: none; border-color: initial; border-left-style: none; border-right-style: none; border-top-style: none; border-width: initial; font-family: inherit; font-size: 1em; font: normal normal normal 14.5px/18px 'Times New Roman', Times, serif; line-height: inherit; margin-top: 15px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; position: relative; text-decoration: none; white-space: normal; z-index: 1;"><i>There is one life. It will soon be past.&nbsp;<br style="background-attachment: initial; background-clip: initial; background-color: initial; background-image: none; background-origin: initial; background-position: initial initial; background-repeat: initial initial; border-bottom-style: none; border-color: initial; border-left-style: none; border-right-style: none; border-top-style: none; border-width: initial; font-family: inherit; font-size: 1em; line-height: inherit; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; position: relative; text-decoration: none; white-space: normal; z-index: 1;" />Only what is done for Christ will last.</i></div><br /><br /><br />Matters of life and death are often a time to ponder what I will do with the remaining days and hours I have. Will I waste them on things that don't mean anything on earth? Or will I pursue the full will and plan of God for my life?<br /><br />Darrell G. Wolfe<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />