---
title: 'Zig Ziglar Quotes'
date: '2011-09-24T02:19:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5115150995659840431'
blogger_filename: '/2011/09/zig-ziglar-quotes.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Random'
---

<br /><span class="Apple-style-span" style="background-color: white; font-family: arial, sans-serif; font-size: 13px;"></span><br /><div dir="ltr"></div>If you treat your wife like a thoroughbred, you'll never end up with a nag.<br /><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar381980.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">Zig</a><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar381980.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">&nbsp;Ziglar</a><br /><div dir="ltr"></div><div dir="ltr" original_target="http://www.brainyquote.com/quotes/quotes/z/zigziglar395136.html">Little men with little minds and little imaginations go through life in little ruts, smugly resisting all changes which would jar their little worlds.<br /><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar395136.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">Zig</a><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar395136.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">&nbsp;Ziglar</a>&nbsp;</div>Many marriages would be better if the husband and the wife clearly understood that they are on the same side.<br /><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar387370.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">Zig</a><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar387370.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">&nbsp;Ziglar</a><br /><div dir="ltr"></div><div dir="ltr" original_target="http://www.brainyquote.com/quotes/quotes/z/zigziglar173503.html">Money isn't the most important thing in life, but it's reasonably close to oxygen on the "gotta have it" scale.<br /><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar173503.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">Zig</a><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar173503.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">&nbsp;Ziglar</a>&nbsp;</div><div dir="ltr" original_target="http://www.brainyquote.com/quotes/quotes/z/zigziglar387369.html">People often say that motivation doesn't last. Well, neither does bathing - that's why we recommend it daily.<br /><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar387369.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">Zig</a><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar387369.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">&nbsp;Ziglar</a>&nbsp;</div><div dir="ltr" original_target="http://www.brainyquote.com/quotes/quotes/z/zigziglar381987.html">People who have good relationships at home are more effective in the marketplace.<br /><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar381987.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">Zig</a><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar381987.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">&nbsp;Ziglar</a>&nbsp;</div><div dir="ltr" original_target="http://www.brainyquote.com/quotes/quotes/z/zigziglar381984.html">Positive thinking will let you do everything better than negative thinking will.<br /><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar125675.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">Zig</a><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar125675.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">&nbsp;Ziglar</a><br /><br />Remember that failure is an event, not a person.<br /><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar378592.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">Zig</a><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar378592.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">&nbsp;Ziglar</a><br /><br />You can have everything in life you want, if you will just help other people get what they want.<br /><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar381984.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">Zig</a><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar381984.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">&nbsp;Ziglar</a>&nbsp;</div><div dir="ltr" original_target="http://www.brainyquote.com/quotes/quotes/z/zigziglar132266.html">You cannot tailor-make the situations in life but you can tailor-make the attitudes to fit those situations.<br /><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar132266.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">Zig</a><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar132266.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">&nbsp;Ziglar</a>&nbsp;</div><div dir="ltr" original_target="http://www.brainyquote.com/quotes/quotes/z/zigziglar381975.html">You do not pay the price of success, you enjoy the price of success.<br /><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar381971.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">Zig</a><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar381971.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">&nbsp;Ziglar</a><br /><br />You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win.<br /><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar381983.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">Zig</a><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar381983.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">&nbsp;Ziglar</a><br /><br />Your attitude, not your aptitude, will determine your altitude.<br /><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar381975.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">Zig</a><a href="http://www.brainyquote.com/quotes/quotes/z/zigziglar381975.html" saprocessedanchor="true" style="color: #5797b0;" target="_blank">&nbsp;Ziglar</a>&nbsp;</div><div dir="ltr"></div>