---
title: 'Stars and Stripes (Working Title) 1'
date: '2011-12-04T03:09:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1205918350440484887'
blogger_filename: '/2011/12/stars-and-stripes-working-title-1_3.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Stars and Stripes (Working Title)'
---

In and around you is a world you've never seen, but you always knew it was there. It wasn't obvious to your physical senses but you've had the feeling that there was more. You never really understood it, never knew what to believe. There are so many opinions. So many documentaries. So many "sightings". What do you believe?<br /><br /><br /><br />Eric Schelding didn't know what to believe either. It was the summer after his last year of college. He graduated &nbsp;<a href="http://en.wikipedia.org/wiki/Latin_honors" target="_blank">Summa Cum Laude</a> (with highest honor) from MIT. Eric was a major in <a href="http://eapsweb.mit.edu/" target="_blank">EAPS </a>(Earth, Atmospheric, and Planetary Sciences. Eric was a serious student. He spent very little time fraternizing with other students. Although all his fellow graduates were considered the best of the best they all thought too small. Eric felt their biases were too many to make them worth spending too much time with. He kept to his books and reports. He had already published 137 major scientific papers on space science and 13 books on the subject of space and space travel.<br /><br /><br /><br />Eric was&nbsp;skeptical&nbsp;of any of the UFO sightings common people bought into, however he couldn't help conjecturing that with so many star systems some must also have sparked some time of life. The&nbsp;mathematical&nbsp;odds of any life evolving to be self aware and developing twice were literally astronomical. It was highly unlikely at best. The more likely scenario was that base organism existed somewhere that could be comprised of&nbsp;elements&nbsp;not yet known to humans.<br /><br /><br /><br />Nevertheless, he would stare into the stars and dream of making space travel a reality. Government&nbsp;bureaucracies&nbsp;were too&nbsp;inefficient&nbsp;to rely on. The USA was still using space shuttles that were designed in the 1950's and 60's because they refused to invest in new technology that had already been designed and tested in smaller scales. Eric was convinced that if anyone was going to experience travel to distant parts of our own solar system, not to mention other galaxies, in his lifetime it would have to be private funded and researched.<br /><br /><br /><br />Erik's one distraction and non serious pursuit was being a fan of star films. Any star film. Star Trek (All versions), Star Wars, and any other film he could get his hands on. Lost in Space was always good for laughs. He even found Space Balls amusing. When questioned about his one less than serious pursuit he would dismiss it as research. He was smart enough to know that science imitated art as often as art imitated science. He was a much better doer than dreamer. If someone else could dream it for him, he would set his mind to making it happen.<br /><br /><br /><br />The iPhone's first release was due in great part to Erik's participation during a summer work assignment at Apple Headquarters. He sat watching Captain Jean-Luc Picard and Geordi La Forge use tricorders and thought to himself "Hey... good idea!" He spend the rest of the night drawing out schematics and processing equations. That project turned into the iPhone and revolutionized the industry. Of course he was interned and all the credit went to Steve Jobs. He doesn't receive any royalties as it's company&nbsp;intellectual&nbsp;property. But they agreed to provide a free iPhone as often as he needed a new one and lifetime free cell plan for his work. He figured that was worth more than any royalty anyway. He was of course called on from time to time to work on later editions of the newest phones too. Being oddly self serving, as he would be getting one for free he was more than happy to oblige at no extra charge. It's not often one has a hand in fashioning a device that is so intricate to ones own daily life.<br /><br /><br /><br />... DW<br /><br /><br />