---
title: 'The Author of my Adventure'
date: '2011-09-30T22:07:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3344844631051047635'
blogger_filename: '/2011/09/the-author-of-my-adventure.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Random'
  - 'Prayer Time'
---

<span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 12px;"></span><br /><h4 class="ResultTitle" style="clear: left; font-size: 14px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><a href="http://www.biblestudytools.com/my-bible/#" style="color: #3380cc; text-decoration: underline;">Hebrews 12:2 NKJV</a></h4><div><b>Jesus is the Author and Finisher of our faith.&nbsp;</b></div><b><span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 12px;"><h4 class="ResultTitle" style="clear: left; font-size: 14px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><a href="http://www.biblestudytools.com/my-bible/#" style="color: #3380cc; text-decoration: underline;">2 Timothy 3:16 NKJV</a></h4><div>All scripture is inspired by God.</div></span><span class="Apple-style-span" style="background-color: white; color: #333333; font-family: arial; font-size: 14px;"><a href="http://www.biblestudytools.com/my-bible/#" style="color: #3380cc; text-decoration: underline;">Matthew 4:4 NKJV</a>&nbsp;and&nbsp;</span></b><span class="Apple-style-span" style="background-color: white;"><span class="Apple-style-span" style="color: #333333; font-family: arial; font-size: 14px;"><a href="http://www.biblestudytools.com/my-bible/#" style="color: #3380cc; text-decoration: underline;"><b>Luke 4:4 NKJV</b></a></span><div style="color: #333333; font-family: arial; font-size: 12px;"><b>Jesus always responded to the attacks of the Devil: It is written</b></div><div style="color: #333333; font-family: arial; font-size: 12px;"><b><a href="http://www.biblestudytools.com/my-bible/#/left:passage/nkjv/john/1:1-18/">John 1:1-18</a></b></div><div style="color: #333333; font-family: arial; font-size: 12px;"><b>Jesus is THE Word of God... The Word became Flesh...</b></div><div style="color: #333333; font-family: arial; font-size: 12px;"><br /></div><div style="color: #333333; font-family: arial; font-size: 12px;"><br /></div><div><span class="Apple-style-span" style="color: #333333; font-family: arial;"><span class="Apple-style-span" style="font-size: 12px;">There is a <b>Story Teller</b> who is above and beyond all story tellers. We are living out the grandest story in <b>His-Story </b>(History). </span></span><a href="http://www.ransomedheart.com/" style="color: #333333; font-family: arial; font-size: 12px;">John Eldredge of Ransomed Heart Ministries</a><span class="Apple-style-span" style="color: #333333; font-family: arial;"><span class="Apple-style-span" style="font-size: 12px;"> wrote an amazing book called </span></span><a href="http://www.ransomedheart.com/p-933-wild-at-heart-revised-and-expanded-paperback.aspx" style="color: #333333; font-family: arial; font-size: 12px;">Wild at Heart</a><span class="Apple-style-span" style="color: #333333; font-family: arial;"><span class="Apple-style-span" style="font-size: 12px;">. He spoke of this grand story. God created Kings use His power in His&nbsp;Authority&nbsp;to rule this planet. Those Kings fell, died, there were ransomed and redeemed. Authors like </span><a href="http://www.ransomedheart.com/default.aspx" style="font-size: 12px;">John Eldredge</a><span class="Apple-style-span" style="font-size: 12px;">, </span><a href="http://www.teddekker.com/" style="font-size: 12px;">Ted Dekker</a><span class="Apple-style-span" style="font-size: 12px;">, </span><a href="http://frankperetti.com/" style="font-size: 12px;">Frank Peretti</a><span class="Apple-style-span" style="font-size: 12px;">, &nbsp;</span><a href="http://www.billmyers.com/" style="font-size: 12px;">Bill Meyers</a><span class="Apple-style-span" style="font-size: 12px;">, have written many books exploring this strange and&nbsp;beautiful&nbsp;tale that we are living in and through.&nbsp;</span></span></div><div><span class="Apple-style-span" style="color: #333333; font-family: arial;"><span class="Apple-style-span" style="font-size: 12px;"><br /></span></span></div><div><span class="Apple-style-span" style="color: #333333; font-family: arial;"><span class="Apple-style-span" style="font-size: 12px;">Everything that is said, written, or preformed of any eternal significance will refer to, quote, or be influenced by this book, this love story, this instruction manual, this epic call "The Bible" or "The Word of God". Every&nbsp;writer&nbsp;who will do anything worthy of publishing will, in essence, be diving into God's Word in order to bring some small nugget from it to our view. They may examine it, expand, expound, explore, magnify, or even beautify. Fiction and Nonfiction alike.&nbsp;</span></span></div><div><span class="Apple-style-span" style="color: #333333; font-family: arial;"><span class="Apple-style-span" style="font-size: 12px;"><br /></span></span></div><div><span class="Apple-style-span" style="color: #333333; font-family: arial;"><span class="Apple-style-span" style="font-size: 12px;"><b>There is a reason that Epic stories and Superhero stories have the strongest pull of all venues</b>. Pirates of the Caribbean, Iron Man, Superman, Batman, Lord of the Rings, and Chronicles of Narnia... these stories permeate our culture and our imaginations. The reason is that we know there is more to life than going to work in order to pay bills in order to go to work... etc. Some refuse and many don't know that there is in fact an answer to that calling within our souls. As children, created and adopted by the Most High Story Teller/Author there is an&nbsp;innate&nbsp;need within us of knowing, experiencing, exploring, and having...<b> a grand adventure</b>. There is no end to the stories that must be told, true and make believe alike. This is among the things I feel a call to do... but have yet to fully embrace... it is time... to take a step.&nbsp;</span></span></div><div><span class="Apple-style-span" style="color: #333333; font-family: arial;"><span class="Apple-style-span" style="font-size: 12px;"><br /></span></span></div><div><span class="Apple-style-span" style="color: #333333; font-family: arial;"><span class="Apple-style-span" style="font-size: 12px;">Darrell G. Wolfe</span></span></div><div style="color: #333333; font-family: arial; font-size: 12px;"><br /></div><div style="color: #333333; font-family: arial; font-size: 12px;"><br /></div></span>