---
title: 'The Prayer Template of Jesus'
date: '2011-10-07T00:05:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1327088050445665191'
blogger_filename: '/2011/10/the-prayer-template-of-jesus.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Random'
  - 'study'
---

The Lords Prayer our template for prayer topics.<br /><br /><h2 id="passage_heading" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 16px; font-weight: bold;"> <a href="http://www.biblegateway.com/passage/?search=matthew%206:9-13&amp;version=KJ21">Matthew 6:9-13&nbsp;(21st Century King James Version)</a></h2><div class="result-text-style-normal" style="font-family: 'Charis SIL', charis, Verdana, Arial, Helvetica, sans-serif; font-size: 16px;"><br />&nbsp;<sup class="versenum" id="en-KJ21-23267" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">9</sup>In this manner therefore pray ye:<br /><br /><br />Our Father who art in Heaven, hallowed be Thy name.<br /><b>Lift up the name of the Father</b><br />&nbsp;<br />&nbsp;<sup class="versenum" id="en-KJ21-23268" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">10</sup>Thy Kingdom come.<br /><b>Pray for and through the Kingdom of God</b><br /><br />Thy will be done on earth, as it is in Heaven.<br /><b>God's will is for earth to be as heaven pray accordingly.&nbsp;</b><br />&nbsp;<br />&nbsp;<sup class="versenum" id="en-KJ21-23269" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">11</sup>Give us this day our daily bread.<br /><b>Pray for today, let tomorrow care for itself.&nbsp;</b><br />&nbsp;<br />&nbsp;<sup class="versenum" id="en-KJ21-23270" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">12</sup>And forgive us our debts, as we forgive our debtors.<br /><b>Forgiveness is key to receiving.&nbsp;</b><br />&nbsp;<br />&nbsp;<sup class="versenum" id="en-KJ21-23271" style="font-size: 0.65em; font-weight: bold; line-height: normal; vertical-align: text-top;">13</sup>And lead us not into temptation, but deliver us from evil.<br /><b>God's will is to deliver you from all evil...&nbsp;</b><br /><b><br /></b><br />For Thine is the Kingdom, and the power and the glory for ever. Amen.<br /><b>The Kingdom of God is the only Power and Glory you need. Pray the Kingdom in all situation, lifting His Kingdom over your circumstance.&nbsp;</b><br />&nbsp;&nbsp;&nbsp;</div>