---
title: 'Self Imposed Restriction: Wisdom or Religion?'
date: '2011-09-09T13:19:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6554668877545950922'
blogger_filename: '/2011/09/self-imposed-restriction-wisdom-or.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<span class="Apple-style-span" style="font-family: 'times New Roman'; font-size: 16px;"></span><br /><h1 id="pageTitle" style="font: normal normal normal 32px/26px Palatino, 'Palatino Linotype', 'Hoefler Text', Times, 'Times New Roman', serif; left: 9px; letter-spacing: 2px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 11px; position: relative; text-transform: uppercase; top: 4px; width: 400px;"> COLOSSIANS 2</h1><br /><br />Colossians 2<br /><br /><i>Vs 6&nbsp;</i><br /><i>As you therefore have received Christ&nbsp;Jesus&nbsp;as Lord <b>so walk in Him, rooted and built up </b>in Him and <b>established in the faith </b>as you have been taught<b> abounding in it with thanksgiving.</b>&nbsp;</i><br /><br />The way you walk in Him rooted and built up and established in faith: Abound with Thanksgiving. How many times do I say "Thank You Sir!" to my Father in heaven? Thank you for sending Your Son, Your Word, Your Spirit, Your Giftings! Thank you for the sunrise and the sunset, the rain and the clear days, thank you for flowers and for snow...etc<br /><br /><i>Vs16-17</i><br /><i>So let no one judge you in food or in drink or regarding a festival or a new moon or&nbsp;Sabbaths&nbsp;which are a shadow of things to come, but the substance is Christ...</i><br /><i>VS 21</i><br /><i>Why...do you subject yourselves to regulations: "Do not touch, do not taste, do not handle"...</i><br /><i>Vs 23</i><br /><i>These things indeed have an appearance of wisdom in self-imposed religion, false humility, and neglect of the body, but are of no value against the indulgence of the flesh.</i><br /><br /><br />How many times have I heard: "I don't drink, I don't smoke, I don't hang with those who do" or some other such wording? It's interesting, now I don't personally drink because I have a family history of substance abuse dating back at least two generations and probably further. I made a decision to cut myself off before it became a threat, which is had just started to. There is biblical basis for those who decide that alcohol is acceptable and for those who don't. Even though my last sip of alcohol was in December 2001, I haven't any less struggle with my flesh. From soda to chocolate or just good food, my flesh wants, demands, screams, to be indulged.<br /><br />Imposing certain self regulations because they would be harmful is a good idea. But you can tell when someone has made a health and life decision out of their own best interest to protect the anointing of God on&nbsp;their&nbsp;life and when someone has imposed something out of religiousness. The self&nbsp;imposed&nbsp;religious person practically&nbsp;brags&nbsp;about not doing it. They look down on others who do it. There is an air about them, and it's repulsive. The self&nbsp;imposed&nbsp;for&nbsp;conscience&nbsp;sake person doesn't brag about it or mind if people do.<br /><br />I can't tell &nbsp;you how many times I've been at some work function or somewhere with others out to eat and people ordered wine or beer and then when they found out I didn't drink they were so apologetic and asked if I would like them not to. I tell them all, "The decision is mine and for me. It has nothing to do with you. Please enjoy!" I have no problem sitting a table full of people drinking, moderately and with wisdom. I have no problem with a Christian or Pastor that drinks a glass of wine here or there. I simply don't do it for my own reasons.<br /><br />The idea here is the flesh, what are problems for me, aren't for you. You have other things you need to tend to. If there are weak areas of the flesh, cut them out, it's better to go into heaven with one eye and without a nagging festering sin that won't let you go. Just be aware that cutting that out doesn't change your flesh. You still need to watch for other areas the flesh will creep up.<br /><br />So how do I&nbsp;conquer&nbsp;the flesh?<br /><br /><i>Chapter 3:1-2</i><br /><i>...seek those things which are above... set your mind on things above</i><br /><br />Set your mind on things above... imagine, ponder, meditate the Word... that is how you change and subdue the flesh. It looks like the solution is Mondays reading... Chapter 3.<br /><br />Darrell G. Wolfe<br /><br /><br />