---
title: 'Untitled Post'
date: '2011-09-07T04:53:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1930649948822406774'
blogger_filename: '/2011/09/03152010-in-prayer-today-never-before.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Prayer Time'
---

03/15/2010<br /><br />In prayer today:<br /><i><br /></i><br /><i>&nbsp;&nbsp;&nbsp;&nbsp; Never before has there been a generation with so many tools and resources and so little success. Value has been placed on learning more than doing. Ever learning but never able to come to the knowledge of the Truth.</i><br /><i><br /></i><br /><i>&nbsp;&nbsp;&nbsp;&nbsp; It's time to focus. Game Time. Stop seeking ways to get money in and start seeking ways to get the Word out! Promotion will come but it won't satisfy you unless you were already satisfied. Your team needs your anointing, start walking in it!&nbsp;</i><br /><i><br /></i><br /><i>&nbsp;&nbsp;&nbsp;&nbsp; Ever time you feel great financial pressure you stop. Pray thankfullness over what you have and thankfulness over the Promise and Blessing. Then Pray for the needs of others starting with Leaders, Partners, and Family.</i><br /><br />&nbsp;&nbsp;&nbsp;&nbsp; See: <br /><h4> <a href="http://www.biblegateway.com/passage/?search=2%20Timothy%203&amp;version=NKJV">2 Timothy 3</a></h4><h4> <i><sup class="versenum" id="en-NKJV-29851">1</sup> But know this, that in the last days perilous times will come... <sup class="versenum" id="en-NKJV-29857">7</sup> always learning and never able to come to the knowledge of the truth...<sup class="versenum" id="en-NKJV-29860">10</sup> But you have carefully followed my doctrine, manner of life, purpose, faith, longsuffering, love, perseverance, <sup class="versenum" id="en-NKJV-29861">11</sup> persecutions, afflictions, which happened to me at Antioch, at Iconium, at Lystra—what persecutions I endured. And out of </i><i>them all the Lord delivered me.&nbsp;</i></h4><h4> <i>&nbsp;</i></h4><h4 style="font-weight: normal;"> Todays Reading was from <b><a href="http://www.biblegateway.com/passage/?search=Luke%208:14,21&amp;version=NKJV">Luke 8</a></b></h4><h4 style="font-weight: normal;"> </h4><div>Never Posted This... it was in drafts...DW</div>