---
title: 'God Can&#39;t Lie! We are BLESSED to be a BLESSING!'
date: '2011-11-17T03:29:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6826156924115790619'
blogger_filename: '/2011/11/god-can-lie-we-are-blessed-to-be.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Mens Meeting'
---

<b><span class="Apple-style-span" style="font-size: large;">EMIC - Wed Morning Men's Meeting - 11/16/2011</span></b><br /><span class="Apple-style-span" style="font-size: large;"><br /></span><br /><b><span class="Apple-style-span" style="font-size: large;"><u>FYI: No meeting on the second week in December, 12/21/2011.</u>&nbsp;</span></b><br /><b><br /></b><br /><b>FYI: Men, Notes may be a bit disjointed. I captured the scritpures we talked about, but didn't get as many quotes as usual.&nbsp;</b><br /><br /><b>God Doesn't Lie!</b><br /><b><a href="http://www.biblestudytools.com/nkjv/numbers/23-19.html" target="_blank">Numbers </a>23:19</b><br /><i>&nbsp;19 "God is not a man, that He should lie, Nor a son of man, that He should repent. Has He said, and will He not do? Or has He spoken, and will He not make it good?</i><br /><br /><b>God Cannot Lie!</b><br /><b><a href="http://www.biblestudytools.com/nkjv/titus/1-2.html" target="_blank">Titus </a>1:2</b><br /><i>2 in hope of eternal life which God, who cannot lie, promised before time began,</i><br /><br /><b>It is IMPOSSIBLE for God to Lie!</b><br /><b><a href="http://www.biblestudytools.com/nkjv/hebrews/6-18.html" target="_blank">Hebrews </a>6:18</b><br /><i>18 that by two immutable things, in which it is impossible for God to lie, we might have strong consolation, who have fled for refuge to lay hold of the hope set before us.</i><br /><br /><b>So to recap what we just read: GOD Doesn't Lie, Cannot Lie, it is IMPOSSIBLE for God to Lie!</b><br /><br />Not only is it impossible to lie but if you read further into the story of Balaam and Balak you discover that even the prophet that had abandoned God's Word for monetary gain couldn't put forth a prophetic declaration against God's people when they were under the blessing. God won't even let someone else Lie for him! He'll expose it one way or another. He send a talking Donkey to stop that attack!<br /><br /><br /><a href="http://www.biblestudytools.com/search/?q=BLESSING+I+will+BLESS+you." target="_blank">BLESSING I will BLESS you.</a>&nbsp;Abraham was BLESSED by God.&nbsp;THE BLESSING is the action. THE BLESSING creates work/assignment. Abraham experienced THE BLESSING and became wealthy almost dispite himself. He was under God's hand and wealth came to him.&nbsp;When God speaks THE BLESSING is introduced. That is the anchor for our souls! One word from God changes everything.<br /><br />THE BLESSING is the hope which anchors us. If we become BLESSING minded there is no problem to big, no enemy to strong, nothing we cannot do!<br />___________________________________________________________________________<br /><b>Shared by Steve Wilson</b><br /><a href="http://www.biblestudytools.com/nlt/colossians/4-5.html" target="_blank">Col 4.5 (NLT)&nbsp;</a><br /><i>"Live wisely among those who are not believers, and make the most of every opportunity."</i><br /><i>(NKJV reads "walk in wisdom")</i><br /><br /><b>A word from God, through Steve, for the group:</b><br /><b><br /></b><br /><i><b>&nbsp;<u>"Every day I bring opportunities to display my power and glory in order to bless you, so you can bless others. </u>Keep your eyes upon me and hear my voice and I will lead you in the right path - put you in the right position. My Spirit was given to help you succeed, to teach and instruct you in my ways. Heed His voice and leading. I will make you successful in the financial realm, the business realm, the medical realm, the spiritual realm, whatever realm I have called you to and assigned you in. Walk with me and you WILL walk in wisdom, for I AM wisdom. Quit looking at the problem - listen and watch for the solution!"&nbsp;</b></i><br /><i><b><br /></b></i><br />I appreciate each of you and appreciate everyone sharing what's on their heart - Iron truly sharpens Iron. SW<br />__________________________________________________________________________<br /><br />Someone said: Opportunity&nbsp;meets&nbsp;Preparation<br /><br />A theme of today: Read a little further. Every time a verse is quoted something powerful is just beyond it and fitting for us today.<br /><br />Not works, but purpose. My&nbsp;assignment&nbsp;IS my ministry. Your assignment is your ministry. It's almost as though the five fold ministry gifts (Apostle, Prophet, Evangelist, Pastor, and Teacher) are the only ones NOT ministering. Instead, they teach and train US for the work of the ministry in the market places and streets. They do minister, but their job is to train us to do so in our sphere of influence. Church is the classroom/training center. The real ministry should be taking place outside the church walls.<br /><br /><br /><b>Other Scripture that was brought up:</b><br /><br /><br /><b><a href="http://www.biblestudytools.com/nkjv/2-timothy/passage.aspx?q=2-timothy+1:7-9" target="_blank">2 Timothy 1:7-9</a></b><br /><i>7 For God has not given us a spirit of fear and timidity, but of power, love, and self-discipline. 8 So you must never be ashamed to tell others about our Lord. And don't be ashamed of me, either, even though I'm in prison for Christ. With the strength God gives you, be ready to suffer with me for the proclamation of the Good News. 9 It is God who saved us and chose us to live a holy life. He did this not because we deserved it, but because that was his plan long before the world began -- to show his love and kindness to us through Christ Jesus.</i><br /><br /><br /><br /><b><a href="http://www.biblestudytools.com/nkjv/numbers/passage.aspx?q=numbers+23:16-26" target="_blank">Numbers 23:21</a></b><br /><i>18 Then he took up his oracle and said: "Rise up, Balak, and hear! Listen to me, son of Zippor! 19 "God is not a man, that He should lie, Nor a son of man, that He should repent. Has He said, and will He not do? Or has He spoken, and will He not make it good? 20 Behold, I have received a command to bless; He has blessed, and I cannot reverse it. 21 "He has not observed iniquity in Jacob, Nor has He seen wickedness in Israel. The Lord his God is with him, <b>And the shout of a King is among them</b>. 22 God brings them out of Egypt; He has strength like a wild ox.</i><br /><br /><b><a href="http://www.biblestudytools.com/nkjv/isaiah/passage.aspx?q=isaiah+61:4-9" target="_blank">Isaiah 61:4-9</a></b><br /><i>4 And they shall rebuild the old ruins, They shall raise up the former desolations, And they shall repair the ruined cities, The desolations of many generations. 5 Strangers shall stand and feed your flocks, And the sons of the foreigner Shall be your plowmen and your vinedressers. 6 But you shall be named the priests of the Lord, They shall call you the servants of our God. You shall eat the riches of the Gentiles, And in their glory you shall boast. 7 Instead of your shame you shall have double honor, And instead of confusion they shall rejoice in their portion. Therefore in their land they shall possess double; Everlasting joy shall be theirs. 8 "For I, the Lord, love justice; I hate robbery for burnt offering; I will direct their work in truth, And will make with them an everlasting covenant. 9 Their descendants shall be known among the Gentiles, And their offspring among the people. All who see them shall acknowledge them, That they are the posterity whom the Lord has blessed." </i><br /><br /><b><a href="http://www.biblestudytools.com/nkjv/2-peter/passage.aspx?q=2-peter+2:15-16" target="_blank">2 Peter 2:15-16</a></b><br /><i>15 They have forsaken the right way and gone astray, following the way of Balaam the son of Beor, who loved the wages of unrighteousness; 16 but he was rebuked for his iniquity: a dumb donkey speaking with a man's voice restrained the madness of the prophet. </i><br /><br />Darrell G. Wolfe and Others