---
title: 'Heaven if for REAL!'
date: '2011-12-06T15:48:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1039039286712119922'
blogger_filename: '/2011/12/heaven-if-for-real.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

Tuesday 12/06/2011<br /><br /><b>COME:</b><br /><a href="http://www.biblestudytools.com/nkjv/revelation/4.html" target="_blank"><b>Revelations 4</b></a><br /><span class="versetext" id="re4-2" style="display: inline; font-family: arial; font-size: 14px; line-height: 20px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">&nbsp;</span><span class="versetext" id="re4-3" style="display: inline; font-family: arial; font-size: 14px; line-height: 20px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">3</span>&nbsp;And He who sat there was&nbsp;<a href="http://draft.blogger.com/blogger.g?blogID=6583916183087899714" name="a"></a>like a jasper and a sardius stone in appearance; and there was a rainbow around the throne, in appearance like an emerald.</span><span class="versetext" id="re4-4" style="display: inline; font-family: arial; font-size: 14px; line-height: 20px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">4</span>&nbsp;Around the throne were twenty-four thrones, and on the thrones I saw twenty-four elders sitting, clothed in white robes; and they had crowns&nbsp;<a href="http://draft.blogger.com/blogger.g?blogID=6583916183087899714" name="b"></a>of gold on their heads.&nbsp;</span><span class="versetext" id="re4-5" style="display: inline; font-family: arial; font-size: 14px; line-height: 20px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">5</span>&nbsp;And from the throne proceeded lightnings, thunderings, and voices.&nbsp;<a href="http://draft.blogger.com/blogger.g?blogID=6583916183087899714" name="c"></a>Seven lamps of fire were burning before the throne, which are the&nbsp;<a href="http://draft.blogger.com/blogger.g?blogID=6583916183087899714" name="d"></a>seven Spirits of God.&nbsp;</span><span class="versetext" id="re4-6" style="display: inline; font-family: arial; font-size: 14px; line-height: 20px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">6</span>&nbsp;Before the throne there was&nbsp;<a href="http://draft.blogger.com/blogger.g?blogID=6583916183087899714" name="e"></a>a sea of glass, like crystal.</span><br /><br /><b>HEAR:</b><br />Sometimes it's good to just use your imagination. So often I learn, learn, learn, learn.... But God, throughout eternity and His Word, is a God of striking imagery. Heaven is am amazing place. Although it's not our permanent home, because God says that he's going to get rid of the current heaven and earth and make his home with us on the new earth, it is a place we attain and desire to be.<br /><br />The only people not inwardly burning to see heaven are those who don't understand it's construct or it's nature. Grace abounds there. If there is sin in your life, repent, wash in the blood of Jesus and be TOTALLY cleansed. God won't even remember you had sin. You aren't just a sinner saved by grace you are THE RIGHTEOUSNESS of God! You walk&nbsp;BOLDLY&nbsp;to the throne of Grace as a son who belongs there and is wanted there. God the Father is PASSIONATE about you!<br /><br />Beyond being a bold son of God, adopted by the Blood, heaven is also amazing in and of itself. It's a place of trees, grass, flowers, swimming, flying, anything you want. Animals are there. Kids playing who weren't given the chance to grow up on earth so they are growing up there. Heaven is full of playing kids. Then as you make your way to the Great City you encounter Gold streets, nearly clear from purity. Gates made of a single large pearl. Precious stone foundations.&nbsp;Then you come to the homes in heaven. Mansions. Each one making the largest most extravagant house here pale in comparison. The street of the prophets contains the homes of all those prophets we know and love and many you've never hear of. Go by Paul's house and see him sitting on his front steps teaching a group of people the Word of God. You find King David escorting people throughout the city. The first person you meet upon arriving in heaven is Abraham, it's still his&nbsp;bosom. It's the very&nbsp;fulfillment&nbsp;of the promise given to him. His faith in God's promise brought him more family than he ever could have hoped to have on earth.&nbsp;As you walk around flower don't get crushed under your feet. You can go swimming and then come out instantly dried by the wind. Choose to walk or fly, it's up to you.<br /><br />When you come to the throne you are taken in with it's&nbsp;beauty. John tries to give us a word picture but it fails to do it justice. We will have to see it to understand it. It's the type of thing that can be explained in&nbsp;tongues&nbsp;but not words. John does his best for us here...<br /><br />God the Father sits on an emerald throne. He is surrounded&nbsp;by a rainbow of color and light. His&nbsp;appearance&nbsp;is that of red Jasper and Sardius! The very mention of his holiness and the people around the throne room fall to their face and praise and worship God! The bible calls this type of experience <a href="http://www.biblestudytools.com/asv/1-peter/1-8.html" target="_blank">"Joy unspeakable and full of Glory</a>!"<br /><br /><b>DO:</b><br />Take a few moments and listen/watch Jesse Duplantis account of Heaven "<a href="http://www.jdmstore.org/p-116-heaven-close-encounters-of-the-god-kind.aspx" target="_blank">Close Encounters of the God Kind.</a>" You can watch it on You Tube also.<br /><br /><iframe allowfullscreen="" frameborder="0" height="315" src="http://www.youtube.com/embed/EC2niVzY9aI" width="420"></iframe><br />Take a few moments and read through the young boys&nbsp;account&nbsp;of heaven: "<a href="http://www.amazon.com/Heaven-Real-Little-Astounding-Story/dp/0849946158" target="_blank">Heaven is for Real</a>". I saw the kids story at Wal Mart. It was inspiring.<br /><br />Take a few moments and close you eyes and pray for God to open you heart regarding heaven. When that perspective is solid, there is no depression left on earth. People that leave to heaven are just going ahead of you, not leaving you for good. You may still be sad at their passing, but not&nbsp;distraught. Because you know that there is more of them in your future than your past.<br /><br />This perspective also reminds you that life here is short and to do all you can while you are here to impact the world for Jesus Christ. Pray through your daily&nbsp;assignment from God.<br /><br />Most of all... take great &nbsp;joy in your day... we will spend eternity with God... it's ALL good in that light!<br /><br /><b>PRAYER:</b><br />Father, remind me throughout today just how good heaven is and how good You are! Remind me to get my perspective straight. That way I won't take temporal things so seriously! Glory!<br /><br />Darrell G. Wolfe