---
title: 'Toilet Paper Novels'
date: '2011-04-30T21:33:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8501052305031759762'
blogger_filename: '/2011/04/toilet-paper-novels.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'TP Novels'
---

Nortahn Antivilus found himself in the situation several times a month. His psychiatrist has tried to help with therapy and medications but to no avail. He had used the restroom just before leaving the house but found that he now had to use the restroom again. In this particular case he would have to sit, which of course he could not do because he was terrified of touching anything others had touched. He wasn't just afraid of germs, he was afraid of everything, obsessive compulsive to the core. He didn't like the idea that there could be scracthes on the seat that could be hiding extra germs. <br /><br />Nortahn pulled off about 25 sheets of brown rolled paper towels from the dispenser walked to the stall, he pulled on his latex gloves and began the long process of locking the door, unlocking, and locking it several times. Methodically he folded the paper towels and laid them across the seat making sure to cover any possible area that could contact his skin including the very front where his thighs and legs could touch.<br /><br />He took one last paper towel for entertainment as he would be here for an hour of more. He began folding the brown paper as he'd learned through his training in oragami. This time he choose to fold and a tear and turned it into a small booklet. For the first time it occured to him that a book with no words just wouldn't do for a meticulas man such as himself. He took a pen and carefully began to write. His doctor had advised he write about his life so he could work through his troubles. He finished penning his story about his odd childhood, and being locked in the closet when he forgot to pick up his room and his loss of his mother at 5 and his father at 10. He explored his days at prep school during his post middle school years. Much better, here, no more closets, only strange kids who he had no problem pretending he wouldn't like to know. He never made a friend. Truth be told, nobody would have noticed if he disapeared. <br /><br />He placed the booklet into his inside coat pocket and doned another pair of gloves to comlete his task at hand. He hated the fact that some new grunt store employee would have to clean up after him since the 20 some odd towels would not properly flush along with two pairs of plastic gloves, but he also could not override his compulsive need to flush it all either. He quickly left ingnoring the knowing stair of a long time manager.