---
title: 'Assignment'
date: '2011-09-21T18:08:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2030908210551920729'
blogger_filename: '/2011/09/assignment.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Mens Meeting'
---

<span class="Apple-style-span" style="background-color: white; color: #333333; font-family: Arial, Tahoma, Helvetica, FreeSans, sans-serif; font-size: 14px; line-height: 18px;"></span><br /><h3 class="post-title entry-title" style="font: normal normal normal 18px/normal Arial, Tahoma, Helvetica, FreeSans, sans-serif; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; position: relative;"><a href="http://emicmen.blogspot.com/2011/09/assignment.html" style="color: #333399; text-decoration: none;">Assignment</a></h3><div class="post-header" style="color: #999999; line-height: 1.6; margin-bottom: 1.5em; margin-left: 0px; margin-right: 0px; margin-top: 0px;"><div class="post-header-line-1"></div></div><div class="post-body entry-content" id="post-body-3569524544815385908" style="font-size: 15px; line-height: 1.4; position: relative; width: 578px;">This week we talked about Assignment.<a href="http://www.biblestudytools.com/1-corinthians/6-19.html" style="color: #333399; text-decoration: none;">You are not your own. You are the temple of the Holy Spirit.</a>&nbsp;Your' calling is into&nbsp;<a href="http://www.biblestudytools.com/1-corinthians/1-9.html" style="color: #333399; text-decoration: none;">fellowship with Jesus</a>. You have an assignment from God. Many times people get the idea that in order to be really useful to God they must become Pastors or Teachers. However if God called you to be a real estate agent and help people find and take possession of their strategic position of opportunity and influence, than you are&nbsp;fulfilling&nbsp;the will of God in your&nbsp;assignment&nbsp;there.&nbsp;<a href="http://www.kcm.org/" style="color: #333399; text-decoration: none;">Kenneth Copeland</a>&nbsp;talks about God trying to&nbsp;maneuver&nbsp;people into the right place, but having to work around pastors trying to be&nbsp;shoe salesmen&nbsp;and shoe&nbsp;salesmen&nbsp;trying to be pastors. There was a story about a man who thought they were called to pastor but they were actually called to be financial planner.<br /><br />There are two aspects to knowing your assignment. You must know that you are where God wants you to be and work that assignment until he moves you. You should also consider the place you are going next in terms of your assignment. If God has things on your heart to do for him that are not related to your job, does the job you are going to work align itself to help or hinder your move into those things.<br /><br />Do your companions help or hinder your assignment? Do the friends you associate with encourage you into your assignment or are you having to overcome their words and actions?<br /><br />We also talked about the church being an influence in the community. Not the&nbsp;organization&nbsp;of the church but each individual as the body of Christ. Some people will not hear a pastor but you as a customer or co worker could be asked for the<a href="http://www.biblestudytools.com/1-peter/3-15.html" style="color: #333399; text-decoration: none;">&nbsp;reason for the hope</a>&nbsp;that is inside of you!<br /><br />We also had friend/guests with us.&nbsp;<a href="http://www.buildinternational.org/aboutus.html" style="color: #333399; text-decoration: none;">Missionary Sandy Anderson of Build International&nbsp;</a>was with us today. And&nbsp;<a href="http://www.heartsongfellowship.com/" style="color: #333399; text-decoration: none;">Pastor Steve Henton of Heartsong Fellowship</a>&nbsp;was with us today. We appreciated their input and wisdom and pray for their success in their assignment.<br /><br />We are men of God, for God, and on Assignment on earth for him. Thank you Jesus! Amen.</div><div class="post-body entry-content" id="post-body-3569524544815385908" style="font-size: 15px; line-height: 1.4; position: relative; width: 578px;"><br /></div><div class="post-body entry-content" id="post-body-3569524544815385908" style="font-size: 15px; line-height: 1.4; position: relative; width: 578px;">Darrell G. Wolfe</div>