---
title: 'Use the Power of the Word, while making mention in Prayer!'
date: '2011-10-15T04:11:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5933919174781304242'
blogger_filename: '/2011/10/use-power-of-word-while-making-mention.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><a href="http://www.biblestudytools.com/kjv/philemon/1.html">Philemon - The whole book.</a><br /><span class="Apple-style-span" style="font-family: arial; font-size: 14px; line-height: 20px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">4</span>&nbsp;I&nbsp;<span class="strongs" sn="2168">thank</span>&nbsp;<span class="strongs" sn="3450">my</span>&nbsp;<span class="strongs" sn="2316">God,</span>&nbsp;<span class="strongs" sn="4160">making</span>&nbsp;<span class="strongs" sn="3417">mention</span>&nbsp;of&nbsp;<span class="strongs" sn="4675">thee</span>&nbsp;<span class="strongs" sn="3842">always</span>&nbsp;<span class="strongs" sn="1909">in</span>&nbsp;<span class="strongs" sn="3450">my</span>&nbsp;<span class="strongs" sn="4335">prayers</span></span><br /><a href="http://www.biblestudytools.com/kjv/hebrews/1.html">Hebrews 1</a><br /><b>3</b>...<span class="Apple-style-span" style="font-family: arial; font-size: 14px; line-height: 20px;"><span class="strongs" sn="5342">upholding</span>&nbsp;all&nbsp;<span class="strongs" sn="3956">things</span>&nbsp;by the&nbsp;<span class="strongs" sn="4487">word</span>&nbsp;of&nbsp;<span class="strongs" sn="846">his</span>&nbsp;<span class="strongs" sn="1411">power...</span></span><br /><span class="Apple-style-span" style="font-family: arial;"><span class="Apple-style-span" style="font-size: 14px; line-height: 20px;"><b><br /></b></span></span><br /><b>HEAR:</b><br />How often do I pray for me? How often do I mention ME, I, and MYSELF in my prayers? And how often do I mention other people by name? Paul had this heart, the heart of God, for people. He wanted to see people changed and delivered and helped to become all they were created to be. He stayed up late one night (Book of Acts) just to make sure that the group he was with really got all he could give them. He didn't say to them: "oh well, I need my rest..." He was always concerned with people. My world has centered around me long enough. I must apply the teachings of God to myself first, before anyone else, for correction must start with me. But I must go beyond that and take His teaching to the world.<br /><br />God is upholding all things by the Word of his Power. The Word is the Power of God. The Power of God is the Word of God. They are two heads on a coin. I am called, among other things, to be a teacher. That is one who saturates,&nbsp;dissects, and them&nbsp;disseminates in order to&nbsp;implement&nbsp;those things in the lives of others. A good teacher doesn't just SAY things. A good teacher lives them and then educates through personal experience. They can also go beyond talking and demonstrate that which has been taught. I know a man who was given a job as a flight teacher at a college. They removed someone&nbsp;with&nbsp;a much larger degree and placed this young man in the teachers seat instead. This is because they would rather have someone with a smaller degree and more flight hours than a person with a larger degree and less flight hours. This young man is passionate about flying. He wanted a plane before he wanted a car. He can teach from real world experience.<br /><br />If the power of God is not flowing through me, why should anyone want to hear what I have to say? The answer is they shouldn't. Demonstrate the power and earn the right to be heard. This is a good note for all pastors and teachers. If the power of Jesus to heal the sick and raise the dead and cast out poverty is not demonstrated through your pastor... find a new pastor.<br /><br /><b>DO:</b><br />I will re:tool my prayer time, and be far more specific and purposeful about my praying for others, by name as often as I am able.<br /><br /><b>My Prayer:</b><br />Father. I will not ask you to give me a new heart. That is an Old Covenant request. Your word says that you have <a href="http://www.biblestudytools.com/kjv/romans/5-5.html">shed your Love abroad in my heart</a>.Romans 5:5 Bible in Basic English puts it this way.<br /><span class="Apple-style-span" style="font-family: arial; font-size: 14px; line-height: 20px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">5</span>&nbsp;And hope does not put to shame; <b>because our hearts are full of the love of God through the Holy Spirit which is given to us</b>.</span><br />Therefore I will learn to communicate and walk in your Spirit and thereby extract and put to work the Love that is Your Love which is already in my heart. I don't need more of it. I have all of it for I have all of you. I simply need to begin to put it to work by Faith!<br /><br /><b>Darrell G. Wolfe</b>