---
title: 'I&#39;m Going Fishing!'
date: '2011-05-06T14:19:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7766794576864581644'
blogger_filename: '/2011/05/i-going-fishing.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

05.05.2011&nbsp;<a href="http://www.biblegateway.com/passage/?search=john%2021&amp;version=NKJV"> John 21</a><br /><br /><strong>3 Simon Peter said to them, “I am going fishing.”</strong><br /><strong></strong><br /><br />Fishing was not a hobby or past time for peter. It was like many people today that here in Texas that say they are going fishing and jump into a small boat and cast a line and sit half asleep with a beer and do little to nothing. <br />&nbsp; <br />Fishing for Peter before he met Jesus was a profession. He owned several boats and servants(Hired Workers) and dropped large nets into the lake to gather many fish and sell them in the market. This was a major deal for Peter. Essentiallly he had denied Jesus at His trial, and now Jesus was raised from the Dead but not around much. The ministry he was serving was now dispersed and what was there to do? Peter decides that he's going to stop pursuing the ministry and the big ideas he thought he had. He's obviously mis understood the intentions of Jesus a few times. He thought there would be a kingdom but there isn't yet. He is confused about the purpose of the life and ministry of Jesus. He knows he died and rose again, but what exactly is the purpose of all this? In the wake of these roller coaster emotions he decides to do the one thing he KNOWS he can do. He's going back to work as a fisherman. Maybe it'll be part time, maybe full time. But he's going back to work. Others decided to come with him. <br />&nbsp; <br />One of Jesus first encounters with Peter was asking him to throw down his nets (Plural) after a bad day of fishing with no catch. Jesus now 3.5 years later, but not recognized as Jesus just yet from a distance, asks him to do the same. The first time peter threw ONE net out as a "Make the teacher Happy this is a waste of my time" move. The net nearly broke, indicating that he used an old net and didn't really take Jesus word as having much meaning. THIS time he through down his used good nets and brought in over 153 large fish and John recognizing the pattern said, "Woah man! It's Jesus!" Peter took off to see him. <br /><br />Jesus then uses a Q&amp;A time to restore Peter. Peter denied Jesus three times at His trial. Now Jesus restores Peter with three repetitions of Do you Love me? Peter, repurposed and refocused now turns to the task at hand and returns to the ministry, fully recovered and ready to take his mission with new life and vigor. But He's still lacking one thing... which we see the next...<br /><br />Darrell