---
title: 'Lessons from Peters Trip to Cornelius'
date: '2011-05-19T13:00:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6427838364687125052'
blogger_filename: '/2011/05/lessons-from-peters-trip-to-cornelius.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
---

<h4><a href="http://www.biblegateway.com/passage/?search=acts%2010&amp;version=KJV">Acts 10</a></h4><h4>&nbsp;Peter is called to the house of Cornelius a centurion guard who loved God.&nbsp; </h4><h4></h4><h4><i>&nbsp;<sup class="versenum" id="en-KJV-27262">2</sup>A devout man, and one that feared God with all his house, which gave much alms to the people, and prayed to God always... <sup class="versenum" id="en-KJV-27264">4</sup>  ...Thy prayers and thine alms are come up for a memorial before God.</i></h4><h4>The first thing that stands out to me here is that his Prayers and Giving stood out to God. If anything stands out to God I should make a point of making it a focus and major in my life.&nbsp; </h4><h4><i>&nbsp;<sup class="versenum" id="en-KJV-27275">15</sup>And the voice spake unto him again the second time, What God hath cleansed, that call not thou common.&nbsp;</i></h4><h4>Lord, cleanse me of mindsets that go against your will. How can I come against a person you died to save? How can I not love those you love? Create in me a heart like yours. Your love has been shed abroad in my heart, show me how to let it loose in my life.&nbsp;</h4><h4><i>&nbsp; <sup class="versenum" id="en-KJV-27305">45</sup>And they of the  circumcision which believed were astonished, as many as came with Peter,  because that on the Gentiles also was poured out the gift of the Holy  Ghost. <sup class="versenum" id="en-KJV-27306">46</sup>For they heard them speak with tongues, and magnify God.</i></h4><h4>&nbsp;Yet again, over and over in scripture Tongues is tied to the Holy Spirit. I must spend more time praying, but also spend a more time praying in tongues. </h4><h4><br /></h4><h4><br /></h4><h4><br /></h4><h4><br /></h4><h4>&nbsp;</h4><h4> </h4>