---
title: 'Men&#39;s Meeting'
date: '2011-09-08T05:03:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2187048359604082693'
blogger_filename: '/2011/09/men-meeting.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'EMIC'
  - 'Mens Meeting'
---

7am... Lake Worth<br /><br />What is the purpose of covenant?<br /><br /><ul><li>To remove all doubt</li></ul><div>Covenant is establish to define or re define relationship.</div><div><ul><li>There are 10 commandments given to Moses and of those 4 deal with our relationship with God and 6 deal with out relationship with people. The commandments of the&nbsp;covenant&nbsp;are about relationship.&nbsp;</li></ul><div>When I loose sight of relationship I TRY to&nbsp;receive, instead of just receiving as a child of God.&nbsp;</div></div><div><br /></div><div>Satan ONLY comes to steal, kill, and destroy among his tools for this are to cause division in relationship.</div><div><br /></div><div>God CANNOT lie</div><div>Numbers 23.19</div><div>Don't put human limitations on a limitless God. How you see God is reflected in how you see yourself. Are you feeling worthless or worth much? This depends on whether you KNOW God's love for you and the price He paid. Value is given by how much someone is willing to pay for something. If God gave His son... How much are you worth?</div><div><br /></div><div>Heb 6.18 Confirmed by covenant God can't lie.</div><div><br /></div><div>John 8.44 Satan was a murderer from the very beginning. It's been his nature. Check the source of your situation. God and Satan both have defined fruits. Satan Kills. God brings LIFE Abundant!</div><div><br /></div><div><br /></div><div>Husbands must learn to love their wives, in part we can do this by building her up with daily devotion acts... also taking time to study her and her needs. Read books about her needs. Not just yours. You don't become a banker,&nbsp;financier, politician, accountant, businessman, etc... without study. You don't become a Godly and Mature husband without study either!</div><div><br /></div><div>Psalm&nbsp;31 WOMAN... Read <a href="http://www.amazon.com/Woman-Wife-Mother-Pat-Harrison/dp/0892748621">Woman,Wife,Mother by &nbsp;Pat Harrison</a></div><div><br /></div><div>Darrell G. Wolfe</div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div>