---
title: 'Be Loved'
date: '2011-09-08T12:47:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8841212953976165442'
blogger_filename: '/2011/09/be-loved.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<br /><div class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt; margin-bottom: 0in; mso-outline-level: 1;"><b><span style="color: #9d3300; font-family: 'Times New Roman', serif; font-size: 21.5pt;"><br />Philippians 4 (New King James Version)<o:p></o:p></span></b></div><div class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt; margin-bottom: 0in;"><span style="background-attachment: initial; background-clip: initial; background-color: white; background-image: initial; background-origin: initial; color: #333333; font-family: Arial, sans-serif; font-size: 12.5pt;">Therefore, my BE LOVED and longed-for brethren, my joy and crown, so stand fast in the Lord, BE LOVED.</span><span style="color: black; font-family: 'Times New Roman', serif; font-size: 13.5pt;"><o:p></o:p></span></div><div class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt; margin-bottom: 0in;"><span style="background-attachment: initial; background-clip: initial; background-color: white; background-image: initial; background-origin: initial; color: #333333; font-family: Arial, sans-serif; font-size: 12.5pt;">Be Loved, beloved, loved, dear friends...</span><span style="color: black; font-family: 'Times New Roman', serif; font-size: 13.5pt;"><o:p></o:p></span></div><div class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt; margin-bottom: 0in;"><span style="background-attachment: initial; background-clip: initial; background-color: white; background-image: initial; background-origin: initial; color: #333333; font-family: Arial, sans-serif; font-size: 12.5pt;">Be Loved today! God sent his Word, His Son, His Spirit, His Gifts and Giftings, His Blessing...HIS LOVE... what else can you ask for today? Don't be like the children following&nbsp;Moses&nbsp;throwing fits in the desert... just ask, receive. It's that simple. God never berated anyone for asking for too much, religion does, God doesn't! God chides for not asking enough or at all. He wasn't mad because they wanted water, food, or meat in the desert. He was mad because they complained instead of just asking in faith. Had they been in faith they would have had WAY better food and drink!&nbsp;</span><span style="color: black; font-family: 'Times New Roman', serif; font-size: 13.5pt;"><o:p></o:p></span></div><div class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt; margin-bottom: 0in;"><span style="background-attachment: initial; background-clip: initial; background-color: white; background-image: initial; background-origin: initial; color: #333333; font-family: Arial, sans-serif; font-size: 12.5pt;">Allow God to love you like He wants to! Stop stopping Him from giving you</span><span style="color: #333333; font-family: Arial, sans-serif; font-size: 12.5pt;">&nbsp;</span><span style="background-attachment: initial; background-clip: initial; background-color: white; background-image: initial; background-origin: initial; color: #333333; font-family: Arial, sans-serif; font-size: 12.5pt;"><a href="http://www.biblestudytools.com/nkjv/1-timothy/6-17.html"><span style="color: blue;">ALL THINGS RICHLY TO ENJOY!</span></a>&nbsp;Let Him Love You!</span><span style="color: black; font-family: 'Times New Roman', serif; font-size: 13.5pt;"><o:p></o:p></span></div><div class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt; margin-bottom: 0in;"><span style="background-attachment: initial; background-clip: initial; background-color: white; background-image: initial; background-origin: initial; color: #333333; font-family: Arial, sans-serif; font-size: 12.5pt;">Today... BE LOVED.</span><span style="color: black; font-family: 'Times New Roman', serif; font-size: 13.5pt;"><o:p></o:p></span></div><div class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt; margin-bottom: 0in;"><span style="background-attachment: initial; background-clip: initial; background-color: white; background-image: initial; background-origin: initial; color: #333333; font-family: Arial, sans-serif; font-size: 12.5pt;">Darrell G. Wolfe</span><span style="color: black; font-family: 'Times New Roman', serif; font-size: 13.5pt;"><o:p></o:p></span></div>