---
title: 'Container of Belief'
date: '2011-09-21T03:39:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7136015784573876386'
blogger_filename: '/2011/09/container-of-belief.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'Random'
  - 'Prayer Time'
---

Belief.&nbsp;<div><br /></div><div>Containers contain a finite amount of space for material. Only so much water fits in a glass jar. You could have a jar filled with oil and as you pour water into it the water displaces the oil. Even though the majority of the oil is displaced quickly the&nbsp;residue&nbsp;takes a while to leave... you must keep pouring the water, consistently. The overflow is the result of much pouring.&nbsp;</div><div><br /></div><div>Faith brings about results through overflow. Through the overflow of the heart the mouth speaks. If faith is inoperative the only reason is a mixed faith container.&nbsp;<div>&nbsp;</div><div>If you are meditating The Word of God on a given topic and you are finding that there is resistance inside of you, that is an indication that there is something taking it's place. That something should be identified and&nbsp;consciously&nbsp;removed. Oil and Water do not provide a pure result. Just oil makes good for cooking, just water makes good for drinking. Both together are bad for drinking and make a mess in a frying pan.&nbsp;</div><div><br /></div><div>How do we identify what is taking up space in your believing container? Consider what you want/ask of God's Word. For example... I want to be a God Employed&nbsp;Business&nbsp;Owner. I want a multi million dollar set of businesses. I have big dreams for the future.&nbsp;</div><div><br /></div><div>When I consider income and budget needs of today I'm tend to look to a new job. The image in my mind is me working for a company and getting enough income from that company. The image in my mind is benefits, vacation, more pay. That is not consistent with the image of a business owner/entrepreneur.</div><div><br /></div><div>So the job needs of today should not be based on a raise, or how much money I could make, but rather it should be based on how that job meets today's needs and balances to provide an optimum environment for me to grow a business. The future business must be a factor in determining the job. By taking a job that steals time from the business I&nbsp;jeopardize&nbsp;the business. By taking a job that provides time and space for the business I empower the business. The job in and of it'self is not the issue. More, it is a matter of what specific free time the job allows. What hours are available in my day. Not just total hours, but specific hours. having two hours before and two hours after is not the same as having four hours before OR four hours after.&nbsp;</div></div><div><br /></div><div>More important. What takes my free time. Family should be first. However is TV or the future business a priority for me? What am I doing with my time. When I look down the road am I seeing another year in the J.O.B. or am I seeing a year of results for the business taking me ever closer to "self" employed, or as I say God Employed. Working for myself is a bad idea. Working for God is a great idea. When I close my eyes I should be able to clearly see where I am headed. If I cannot, the water is mixed with oil.&nbsp;</div><div><br /></div><div>There is more to this... but I'll leave that revelation to simmer for now...&nbsp;</div><div><br /></div><div>Darrell G.Wolfe</div><div>.</div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div>