---
title: 'Low Slow'
date: '2011-12-19T18:07:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '259500624653570842'
blogger_filename: '/2011/12/low-slow.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Random'
  - 'EMIC'
---

Pastor talked about a lot of great stuff on Sunday. I suggest you watch it:<br /><a href="http://emic.org/media.php" style="font-family: HelveticaNeueLight, 'Helvetica Neue Light', HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif;" target="_blank">Sunday 9:00 AM | Emmanuel - God with Us</a><br /><br />However what he said at the end of 2nd service really marked my&nbsp;thinking. I have been hearing a theme from God this past year... especially the past few months. He's been asking me to sing to him. Also to enter the rest of prayer. Not rest as in: "Eat the rest of your dinner". But rest as in: "Peace, calm, rest".<br /><br />Pastor George said: "You need to go into <b>Low-Slow</b>".<br /><br /><b><span style="font-size: x-large;">Low-Slow</span></b><br /><br />In other words: Stop getting worked up, rushed, anxious, etc. Don't let the season rush you. Don't pop in and out of stores at the speed of light frantically trying to get this or that. Rather, shift the gear down on the inside to <b>Low-Slow</b>.<br /><br />I read an article from Kenneth Copeland talking about prayer. He said sometimes he will go to prayer about something and he will get many ideas come to his mind all at once. He knows that means he needs to shut all that out and wait. Only after<a href="http://www.biblestudytools.com/search/?q=enter+rest&amp;c=&amp;t=nkjv&amp;ps=100&amp;s=Bibles" target="_blank"> entering true peace/rest</a> will his mind shut down and allow his spirit to&nbsp;reign. Than something from God will float to the top. It won't be a struggle but it will be easy.<br /><br /><h4 class="ResultTitle" style="clear: left; color: #; font-family: arial; font-size: 17px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">     <a href="http://www.biblestudytools.com/nkjv/hebrews/4-11.html" style="color: #;">Hebrews 4:11 NKJV</a></h4><div class="ResultText" style="background-color: ; color: #; font-family: arial; font-size: 14px; margin-bottom: 3px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Let us therefore be diligent to&nbsp;<span class="Highlight" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 2px; padding-right: 2px; padding-top: 0px;">enter</span>&nbsp;that&nbsp;<span class="Highlight" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 2px; padding-right: 2px; padding-top: 0px;">rest</span>, lest anyone fall according to the same example of disobedience.</div><br />Sometimes I feel like like Doug the Dog from Pixar's movie "Up". "Squirrel!"<br /><br /><iframe allowfullscreen="" frameborder="0" height="315" src="http://www.youtube.com/embed/HxoWHeoYU3g" width="560"></iframe><br /><br /><br />But I am&nbsp;learning&nbsp;to enter the rest. It's a slow learning process but I'm getting better every day. I'm even learning that my wife is right a lot of the time. She tries to tell me something and I'm not getting it or not wanting to get it. However I'm still struggling with how to respond appropriately to her insight sometimes.<br /><br />Lately God's been talking to me about singing to Him. No CD's, no instruments, no guitar. Just singing. Songs as they come. Maybe parts of different songs. Eventually words and music I haven't heard before. Some of it sounds good, some doesn't. But I'm learning to obey him in this. It's allowing me to see the rest side of God like never before.<br /><br />I'm learning that He can't talk until I shut up. Not just stop talking... but also stop the constant mind flow of <a href="http://www.biblestudytools.com/asv/2-corinthians/10-5.html" target="_blank">words, thoughts, and images</a>. Only after entering true rest inside can I hear Him clearly. Even if my body is moving my mind can<a href="http://www.biblestudytools.com/asv/psalms/46-10.html" target="_blank"> be still and know that He Is God</a>!<br /><br />Darrell G. Wolfe