---
title: 'Stars and Stripes (Working Title) 4'
date: '2011-12-06T04:39:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3673530768505198260'
blogger_filename: '/2011/12/stars-and-stripes-working-title-4_5.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Stars and Stripes (Working Title)'
---

...<br /><br /><br /><br />The night was uneventful after his odd dream. Erik studied the stars and mapped the meteor showers. High tech slow motion cameras caught everything on film that could be seen from one end of his sky to the other. He would have more time to pour over the details later. With all this equipment Erik was able to just relax and enjoy the show himself. The equipment would capture everything he needed. He settled into his chair and gazed through his open roof at the night sky. After natures fireworks ceased he shut up the room and fell over his bed. He didn't even bother to get under the covers. He fell asleep dreaming about meteors and space travel.<br /><br /><br /><br />Over the next week results poured in from all over the globe regarding what was seen and studies about what was recorded. Erik poured over his data and compared it to the studies coming in. There were the usual comments about UFO sightings because apparently drunk rednecks can't tell the difference between a&nbsp;comet&nbsp;and meteor and a flying saucer.<br /><br /><br /><br />Then a report out of Colorado caught his eye. A well respected astronomer noted some out of order comets at around 2:37 am MT/ 1:37 am PT. Erik pulled his recorder and focused on the half hour before and after this time note. In fact there were a few streaks of light that seemed to be contrary to the pattern. They would stand still, follow the stream, go against the stream. Then they would streak&nbsp;across&nbsp;the landscape. It was interesting. He pulled the high resolution camera footage and found the same thing but they have the distinct shape of being perfectly round with no clear tail/trail behind them.<br /><br /><br /><br />This footage wasn't entirely unusual. Various records over the decades had shown that when several meteors collide with&nbsp;each other&nbsp;on large&nbsp;scale&nbsp;showers that some can bounce off in different directions while entering earths atmosphere causing light to steak in various directions. What was odd about this set was the frequencies of these&nbsp;anomalies&nbsp;and the few that seemed to stand still for moments at a time. This could be a result of gravity, much like a plane flying against the wind can&nbsp;appear&nbsp;to be standing still for a few moments before either accelerating or changing course.<br /><br /><br /><br />This would require more looking into. There was a knock at the door that&nbsp;interrupted&nbsp;his thoughts. He didn't recall ordering anything to be shipped today but it was unlike him to forget sometimes, he had so many orders out there from time to time. When he approached the screen door there were two kids, high school age from the looks of it, wearing black and metal.&nbsp;Piercings&nbsp;showing on various facial&nbsp;extremities. They seemed to be quite nervous about something. He approached cautiously. "How can I help you?" He started.<br /><br /><br /><br />"Are you Erik&nbsp;Schelding?" the kids asked timidly.<br /><br /><br /><br />"Yes, I am. What can I do for you?" Erik felt that they were more afraid of him than he was of them, that gave him some power and he approached the door.<br /><br /><br /><br />"We visit this hillside from time to time, there is a camp we go to during the summers. We were told to come talk to you. One of the other kids said you know a lot about science and stars and stuff." They still seemed quite nervous. Erik opened the door and motioned them inside.<br /><br /><br /><br />"You could say I know a thing or two about science and stars... and stuff... what can I do for you?" Erik offered them a seat and some soda.<br /><br /><br /><br />It had been a few months since he'd tutored anyone, although he doubted that's what these two had in mind. Still it could be fun to see where this intrusion was leading.<br /><br /><br /><br />"We saw the meteor shower last night and something happened..." They turned and looked at each other and then back to Erik. "... We don't understand it, but maybe you could help."<br /><br /><br /><br />Where could this be going? Erik held their stare for a few moments. "OK, you have my attention, spit it out, what happened?"<br /><br /><br /><br />"I don't know where to start..."The young man said, the girl held his arm tight. "... we were alone and doing playing a game. Suddenly there was this light flash and she... " pointing to the young lady "...&nbsp;disappeared."<br /><br /><br /><br />"I see..." Erik felt the blood drain from his face. More light flashing and&nbsp;weird&nbsp;things? So it wasn't just him.<br /><br /><br /><br />"That's&nbsp;weird&nbsp;enough." the girl took over but when the light flash I was not at the camp anymore. I was on a cold hard metal bed, in a dark room, with a blinding light in my face. I could make out shadows but that's it."<br /><br /><br /><br />"Normally..." Erik&nbsp;interrupted "I would stop you there and say that you two had been drinking and be done with you... but there just so happens to be a few strange things going on in this mountain today so I'll hear you out... then what?"<br /><br /><br /><br />Well I could make out these shadows and they looked like... well... I don't want to admit this... I'm a straight A student... They looked like aliens. Straight&nbsp;Roswell&nbsp;stuff." Then she sat back and fiddled with her fingers. The boy&nbsp;prodded&nbsp;her to continue. "They told me that there were people on this planet holding back the evolution of our species and they may be forced to remove them if we don't get them in line."<br /><br /><br /><br />"Well... " Erik sat back and pondered... "is that all to the story?"<br /><br /><br /><br />"Yes, pretty much. There was another flash of light and I was back with him. She motioned. The boy nodded.<br /><br /><br /><br />"I'm sorry to ask this, but were you drinking?" Erik asked.<br /><br /><br /><br />"Yes... but only one beer each, far less than our usual weekend night." the boy replied.<br /><br /><br /><br />"Around what time did this occur?" Erik questioned further.<br /><br /><br /><br />"Well that's the&nbsp;weird&nbsp;thing. Both our watches stopped working at the exact same time last night, we assume it was after the flashes." They handed over the watches... both digital. They weren't off or blank. They were simply stopped. 1:35 am PT. That was too much of a coincidence. "Would you mind if I kept these for further analysis?" The kids both said that he could keep them. They didn't want to see them anymore, too&nbsp;weird.<br /><br /><br /><br />"What assistance do you believe I can be in this matter?" Erik asked.<br /><br /><br /><br />"We're not sure, but we didn't want to tell the kids at school, or our parents, the police would laugh us off... some of the other kids from the camp grounds that we trust thought you might help in some way to help us grasp what happened. We felt like we needed to tell someone. Now that we did we'd just assume&nbsp;forget&nbsp;it happened and move on... too weird man... to weird..."<br /><br /><br /><br />Erik took out a&nbsp;piece&nbsp;of paper and wrote down their contact information. "Where are you staying up here?"<br /><br /><br /><br />"Off of Sulphur Springs Rd. at Horse Flats." the young man replied.<br /><br /><br /><br />"I didn't catch your names?" Erik asked.<br /><br /><br /><br />"John Buchner but everyone calls me JB. And this is Lucy Tartanion."<br /><br /><br /><br />"JB, Lucy, it was an interesting time I had here, pleasure meeting you both. If I can be of any further assistance let me know. I'd like to take some time to look at these watches and get back to you." Erik said.<br /><br /><br /><br />They nodded and left. <br /><br /><br /><br />This trip up the hill was just getting&nbsp;weirder&nbsp;and weirder... unfortunately, unlike the kids, he wasn't so inclined to brush it off and pretend it didn't happen. He wanted to know more.<br /><br /><br /><br />...<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />