---
title: 'Stars and Stripes (Working Title) 2'
date: '2011-12-04T03:38:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6525633546906174909'
blogger_filename: '/2011/12/stars-and-stripes-working-title-2_3.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Stars and Stripes (Working Title)'
---

...<br /><br /><br /><br />It was on a Monday after locking himself away for 10 days solid that Erik decided to come up for air. It was a cool evening and the stars were just coming out. He hopped in his trusty Dodge Ram, packed full of star gazing equipment, and headed up the mountain on Hwy 2 to his cabin in the Angeles Crest Mountains. He was receiving enough income from his books, published works, and speaking engagements that he didn't have to work on any specific thing at the moment. That didn't keep him from staying busy and working on projects.&nbsp;Erik bought an entire hillside in the mountains for himself just to keep away from the lights of neighbors. That way he could work with the sky at any time of year. He also built a modest observatory. Nothing fancy mind you, but it was enough.<br /><br /><br /><br />After stopping at Newcombs Ranch Restaurant and Bar for quick bite to eat he worked his way up to his secluded mountain top. He turned his cell phone on silent and never bothered installing a land line. Who wanted to be reached in a place like this? Besides he used internet network phones to check voice mails from time to time just in case an important message came through.<br /><br /><br /><br />It was about 8pm on a cool summer evening. The stars were starting to show, although on top of the mountain it stayed light a little later because the sun had no where to hide. It was now starting to darken as the stars became brighter. There was no moon tonight. Perfect, clear skies. As he set up the equipment he noticed a letter he had nearly forgotten about. He didn't know why he kept it. After all this time. These was one girl that he let himself get attached to. She wrote him a letter to break it off because he was so wrapped up in his projects that he didn't even notice her pack and leave that day. He can't say that he regrets the incident. He was on the verge of a new discovery, he was always on the verge of a new discovery. She was important to him, but he just didn't have time for her. She figured that out too. So she left. Still... there was a tinge of guilt and sadness at the sight of the letter. Mostly, he kept it around, he guessed, to remind himself not to get caught up in these types of relationships again. Too costly. Too distracting.<br /><br /><br /><br />After everything was set up he sat back on a reclining lazyboy and waited. It would be three hours exactly before the meteor shower would begin tonight. In fact meteors were known as <a href="http://www.wisegeek.com/what-is-the-difference-between-a-comet-and-a-meteor.htm" target="_blank">meteoroids </a>when in space and meteorites when entering earth's atmosphere; but people generally called them meteors and Erik wasn't such a stuck up geek that he couldn't oblige a common name for ease of conversation. A very exiting one it was made out to be too. Projection were that this years shower would be heavier and more visible in his part of the sky than every before. Erik decided to take a few hours and rest. The alarm on the desk would wake him and start the coffee machine a few minutes before so he could get right to work. With that he closed his eyes and imagined what it would be like to work on the Enterprise.<br /><br /><br /><br />...