---
title: 'Seed, Time, Harvest!'
date: '2011-12-22T19:07:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8624187184455869806'
blogger_filename: '/2011/12/seed-time-harvest.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><a href="http://www.biblestudytools.com/nkjv/revelation/16.html" target="_blank">Revelation 16</a><br />6 For they have shed the blood of saints and prophets, And You have given them blood to drink. For it is their just due." <br /><br /><br /><b>HEAR:</b><br />How often have you heard someone say that they could not fathom a loving God sending someone to hell or doing this or that in judgement? I hear it often. Either God is thought of as a Tyrant or a Pacifist. Neither is true. God is Holy! He is Just! He is Love! He is all of these things and more.<br /><br />Consider for a moment:<br /><br />A child runs out into the street and there is on coming traffic. The father of the child allows him to run out into traffic because he doesn't want to offend him or hurt his feelings by correcting the child. Is this a good father? NO!<br /><br />Love will step in front of a gunman and take him out to prevent the gunman from harming others!<br /><br />Love will says "If you come to bring death to my family I'll take you out first!"<br /><br />Love is aggressive and defensive!<br /><b><br /></b><br /><div style="text-align: center;"><b>Seed, Time, Harvest!</b></div><br />There is also another factor here. That is "<b>Seed, Time, Harvest!</b>" The planet operates on a principle of sowing and reaping. Mankind has been killing,&nbsp;literally, God's people for 1,000's of years. He is the vineyard owner who sent people to check on the&nbsp;vineyard&nbsp;and the workers kept killing or beating the owners servants. Finally the vineyard owner is coming to deal with those evil workers!<br /><br />The&nbsp;judgement&nbsp;of God are not harsh or unloving. They are right and good! Just like serial killers who deserve death row, mankind deserves judgement. Especially those who have been violently resisting God and his people.<br /><br />ALL opportunities have been given to men to avoid this wrath and judgement before it happens. Those left are the ones who rejected God, not the ignorant. No-one is left to receive judgement accidentally!<br /><br /><b>DO:</b><br /><br />1. Make a point to not shy away from telling people about Jesus Blood and the great escape that is coming before the days of wrath come!<br /><br />2. Are there things in my life that are not what I want them to be? Pain, physical or emotional, that are the result of my own seed?&nbsp;Maybe I should seek to find the root cause of the pain instead of treating the symptom.<br /><br />I can&nbsp;believe&nbsp;for and receive&nbsp;divine&nbsp;healing, but if I feed my body toxins and don't treat it right the cause isn't being dealt with.<br /><br />I can pray and cleanse my heart of sadness, but if I am holding on to un-forgiveness or&nbsp;rehearsing&nbsp;the past things that hurt me, I can expect nothing less than depression to return.<br /><br />What&nbsp;recurring&nbsp;themes are you dealing with that won't go away? Maybe you are dealing with symptoms and not cause. Check your heart and life for a pattern of living out of line with the Word of God. Then deal with that. Once you do the symptoms will go away naturally.<br /><br /><br /><b>PRAYER:</b><br />Father, search my life and heart. Reveal to me causes, known and&nbsp;unknown, for the symptoms I experience repeatedly in life. Show me the path to repentance which will lead me beyond where I've been living.<br /><br />Darrell G. Wolfe