---
title: 'Overcoming: Falling Short'
date: '2011-09-17T13:00:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '816732651385060044'
blogger_filename: '/2011/09/overcoming-falling-short.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Mens Meeting'
  - 'Prayer Time'
  - 'Daily Reading'
---

1 Thessalonians 3:10 <a href="http://en.wikipedia.org/wiki/New_English_Bible">The New English Bible</a><br /><br />...we pray most earnestly night and day to be allowed to see you again and to mend your faith where it falls short...<br /><br />It's comforting to know that Paul isn't saying "How dare you let your faith fall short!" So often the devil comes along and berates us for falling short in one area of life or another. We can let this become a situation where we allow condemnation to make us feel bad for falling short. However these is <a href="http://www.biblestudytools.com/search/?q=no+condemnation&amp;c=&amp;t=nkjv&amp;ps=10&amp;s=Bibles">NO condemnation</a> for those who are in Christ Jesus. I am in Christ, therefore there is no condemnation for me. Yes I may fall short from time to time. I may not be as loving as I could have been, I may have been rude or just not done as much as I knew I should...<br /><br />This type of "Man I should have done better..." is a trick of the enemy to get you to beat yourself down. However being humble is not about beating yourself down but about lifting Jesus up! The person who&nbsp;truly&nbsp;knows who they are<a href="http://hopefaithprayer.com/books/In%20Him-Hagin.pdf"> IN-HIM (CHRIST</a>) and has that knowing intimately burning in&nbsp;their&nbsp;heart and mind will never suffer depression. Depression only comes by having an inner&nbsp;monologue&nbsp;of defeat. That old programming needs to be deleted and a new programming of "I am <a href="http://www.biblestudytools.com/nkjv/romans/8-37.html">more than a conqueror</a> should be built in.<br /><br />How is this built it? Sometimes we can get so into our own mind and circle on the same thoughts that we can't see the forest through the trees. Kenneth Copeland once said that a man searching for answers in his own mind can be like a man who goes through the filling cabinet over and over and over looking for a paper... sooner or later you must come to realize... the answer isn't in there! Prayer will always lead you to the answer, however God may lead you to someone who is seasoned to help you with that answer. Allow someone else to walk you out of that forest.<br /><br />Paul in this case is saying that he desires to be there for these people who may have fallen short in a few areas. Let your mentor, pastor, counselor, etc... walk you out of the forest too. It's ok to ask for help and it's ok to need help. <a href="http://www.biblestudytools.com/nkjv/ecclesiastes/4-12.html">Strength is not found in solitude but in the joining of more than one force against another force</a>. Seek help when needed, find a good church that preaches victory and not defeat. Find a good pastor who prays for your victory daily. Find a men's/women's bible study and make yourself accountable to trustworthy elders or strong men of faith.<br /><br />E2P, Darrell G. Wolfe