---
title: 'Stir Up the Gift of God! Part 1'
date: '2011-10-04T15:51:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '529697553511444012'
blogger_filename: '/2011/10/stir-up-gift-of-god-part-1.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'Daily Reading'
---

<b><span class="Apple-style-span" style="font-size: large;">Part 1</span></b><br /><a href="http://www.biblestudytools.com/nkjv/2-timothy/1.html">2 Timothy 1</a><br /><br /><b>Vs 6-7</b><br />Therefore I remind you to <b>stir up the gift</b> of God which is in you through the laying on of my hands. For <b>God has not given us a spirit of fear</b>, but of power and of love and of a sound mind.<br /><br />I've read and heard these versus&nbsp;separately&nbsp;at least a hundred times. I have often wondered what it was to stir up the gift.&nbsp;Apparently&nbsp;they are connected though. I hadn't ever paid attention to the fact they these two verses go together.<br /><br /><b>You stir up the gift of God which is in you BECAUSE God has not given you a spirit of fear but of power, love and a sound mind.&nbsp;</b><br /><br /><b>What does it mean to stir?</b><br /><a href="http://1828.mshaffer.com/d/search/word,stir"><b>Websters 1828 Dictionary for "Stir"</b></a><br /><br /><ol><li>To <b>Move</b>; to change place in any manner</li><li>To <b>Agitate</b>; bring into debate</li><li>To <b>Incite </b>to <b>Action</b>; To <b>Instigate</b>; To Prompt</li><li>To <b>Excite</b>; To <b>Raise</b>; To Put into <b>Motion</b></li></ol><br /><b>Thought&nbsp;Exercise:</b><br />(Per whatever directions for contents on the box) Pour a store bought cake mix into a bowl, open two or three eggs and plop their contents on top, then drizzle the required amount of oil onto that... Now ask yourself this question: Do I have a cake batter yet?<br /><br />The answer is no. I do not. I still have three&nbsp;separate&nbsp;contents/ingredients sitting on top of one another. If I pout that bowl, as is, into a pan and bake it at 325 degrees for 40 minutes, I still don't have cake. I have a burnt set of dry contents and an over concentrated mess on one side.<br /><br />In order to have cake mix I must take those ingredients and stir them together. I must agitate them, incite them to action, excite them, put them into motion, move them around.<br /><br />Then of course even after I have&nbsp;thoroughly&nbsp;agitated the mix I must pour them out and put them under heat for the mix to create the desired result.<br /><br /><b>Real Life:</b><br />So in life God has placed gifts inside of me. Some were brought to the surface and even placed inside by the laying on of hands of various men of God. Others were placed in me before the foundation of the world, giftings and callings that I was put on earth to explore and&nbsp;fulfill.<br /><br /><b>Each of us had gifts inside</b>. Some are the gifts the whole body of Christ has, each individual, such as:<br /><br /><b>9 FRUIT of the Spirit:</b><br /><a href="http://www.biblestudytools.com/nkjv/galatians/passage.aspx?q=galatians+5:22-23">Galatians&nbsp;5:22-23</a><br />Love, Joy, Peace,&nbsp;Long-suffering, Kindness, Goodness, Faithfulness, Gentleness, and Self&nbsp;Control.<br /><b>9 GIFTS of the Spirit:</b><br /><br /><a href="http://www.biblestudytools.com/nkjv/1-corinthians/passage.aspx?q=1-corinthians+12:5-11">1 Corinthians 12:5-11</a> The same God who works ALL IN ALL...The manifestation of the Spirit is given to EACH ONE for the profit of all:<br />Word of Wisdom, Word of&nbsp;Knowledge, Gift of Faith, Gifts of Healings, Working of Miracles, Prophecy, Discerning of spirits, Tongues, and&nbsp;Interpretation&nbsp;of Tongues<br /><b>Full ARMOR of God: </b>to withstand the Devil, having done all to stand, STAND!<br /><a href="http://www.biblestudytools.com/nkjv/ephesians/passage.aspx?q=ephesians+6:13-19">Ephesians 6-13-19&nbsp;</a><br />(Belt) Girder of Truth, Breastplate of Righteousness, Shoes of the Good news of Peace, Shield of Faith, Helmet of Salvation, Sword of the Spirit (The Word of God), and Prayer.<br /><br /><b>We also have giftings and callings in us as individuals:</b><br /><a href="http://www.biblestudytools.com/nkjv/jeremiah/1-5.html">Jeremiah 1:5 </a>Before you were born... I ordained you a prophet...<br /><br /><a href="http://www.biblestudytools.com/nkjv/ephesians/1-4.html">Ephesians 1:4</a> He chose us in Him before the foundation of the World<br /><a href="http://www.biblestudytools.com/nkjv/1-timothy/4-14.html">1 Timothy 4:14</a> the gift in you... by prophecy and laying of hands<br /><a href="http://www.biblestudytools.com/nkjv/2-timothy/1-6.html">2 Timothy 1:6</a>&nbsp;the gift in you... by laying of hands<br /><br />The holy spirit thought it SO important to note that this calling/gifting came by the laying on of hands through the leadership that it was mentioned twice to Timothy.<br /><br /><b>So how do I stir up my gifts?</b><br />How do I stir up the common gifts like love, joy, peace... miracles, tongues, etc...? How do I stir up the specific gifts like Father, Husband, Pastor, Teacher, etc?<br /><br />There is something to be said about confession. Confession is often something I've misunderstood. It has many functions, Charles Capps wrote a GREAT book on that subject called <a href="http://www.amazon.com/Faith-Confession-Charles-Capps/dp/1577941322/ref=sr_1_1?s=books&amp;ie=UTF8&amp;qid=1317742587&amp;sr=1-1">Faith and Confession</a>.<br /><br />Stirring&nbsp;is part of confession. Or many I should rather say Confession is part of&nbsp;stirring. Out of the <a href="http://www.biblestudytools.com/search/?q=mouth+speaks+abundance">abundance of the heart the mouth speaks</a>. But how do I create abundance? I need to stir.<br /><br />I need to use words to agitate, mix, move,&nbsp;instigate, incite to action, excite, raise, and put into motion. It helps me to move around physically too. Pace the floor, preach it to myself, repeat it, ponder it, talk it out aloud. As I begin to do this I find more revelation underneath I hadn't thought of before. I find myself&nbsp;stirring&nbsp;up other things. I find things that fit together I hadn't put together before.<br /><br />I can&nbsp;guarantee that a person who is depressed in any way is NOT doing this. You cannot confess the word, and stir yourself up, agitate and put into motion the truths of God in you sadly. You may start of sad or not feeling like doing it, but you won't stay that way. If you do you either don't have enough word in you to stir, so you need to get some preaching tapes and open you bible and read and take notes and get some word in you, or you have a spirit that needs to be cast out.<br /><br /><span class="Apple-style-span" style="font-size: large;"><b>Darrell G. Wolfe</b></span>