---
title: 'Soul Anchor'
date: '2011-10-22T02:22:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1066044238940624790'
blogger_filename: '/2011/10/soul-anchor.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

Daily Reading... Heb 6<br /><br /><span class="Apple-style-span" style="font-family: arial; font-size: 14px; line-height: 20px;"><span class="versetext" id="heb6-1" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">1</span>&nbsp;Therefore,<b> leaving the discussion of the elementary principles</b> of Christ, let us go on to perfection, not laying again the foundation of repentance from dead works...</span><span class="versetext" id="heb6-11" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">&nbsp;</span><span class="versetext" id="heb6-12" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">12</span><b>&nbsp;that you do not become sluggish, but imitate those who through faith and patience inherit the promises.</b>&nbsp;<b>...</b></span><span class="versetext" id="heb6-16" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">&nbsp;</span><span class="versetext" id="heb6-17" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">17</span>Thus God, determining to show more abundantly to the heirs of promise the<b> immutability of His counsel</b>, confirmed it by an oath,&nbsp;</span><span class="versetext" id="heb6-18" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">18</span>&nbsp;that by<b> two immutable things</b>, in which<b> it is impossible for God to lie</b>, we might&nbsp;<a href="http://draft.blogger.com/blogger.g?blogID=6583916183087899714" name="e"></a>have strong consolation, who have fled for refuge to lay hold of the hope set before us.&nbsp;</span><span class="versetext" id="heb6-19" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">19</span>&nbsp;<b>This hope we have as an anchor of the soul...</b></span></span><br /><br />I did it again... I make a commitment from this point forward that I&nbsp;recognize&nbsp;arguing as a sin and I refuse to do it any longer. Based on my history I know I am not going to be perfect at this. But I hereby&nbsp;acknowledge&nbsp;this as a sin in my life that needs to be corrected and will repent of it as often as I find it in me.<br /><br />Yet again today I found myself arguing with some person of lesser wisdom and&nbsp;intelligence&nbsp;I've never met through comments on an article I disagreed with. It's not important that the article was written by an emissary of&nbsp;Satan&nbsp;or that I was right. That's the hard part. Being so right and doing it wrongly.<br /><br />Arguing... the angry response of a person trying to win a verbal debate at the cost of the other person... caring more about winning the argument than winning the persons soul... is always wrong. You can be right and still be wrong in your rightness.<br /><br />Decidedly&nbsp;LOVE and ARGUING are counter productive to each other. They cancel each other out. Just as&nbsp;Arguing&nbsp;with a person will drive love out so love drives arguing out. Which is why<a href="http://www.biblestudytools.com/search/?q=soft+answer&amp;c=&amp;t=nkjv&amp;ps=10&amp;s=Bibles"> a soft&nbsp;answer&nbsp;turns away wrath</a>. Jesus had some pointed things to say to the pharisees. He was pointed and clear in his disagreements with their religious traditions. But he managed, even then, to do it in love.<br /><br />I must leave this base level, elementary discussion with people on things they refuse to understand. I cannot, for the sake of the Peace of God in me, lay again and again the foundational things for people who don't want to hear them. I cannot<a href="http://www.biblestudytools.com/search/?q=pearls+swine"> cast my pearls before swine</a> that do not appreciate them.<br /><br />Ultimately these arguments become distractions that steal Faith and Patience and therefore prevent me from entering into the promises.<br /><br />So then... I turn from these childish things to see what Paul is trying to bring me into. Help grow Holy Spirit. What are you trying to say?<br /><br /><a href="http://www.biblestudytools.com/bbe/hebrews/passage.aspx?q=hebrews+6:17-19">Hebrews 6 Bible in Basic Enlgish</a><br /><span class="Apple-style-span" style="font-family: arial; font-size: 14px; line-height: 20px;"><span class="versetext" id="heb6-17" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">17</span>&nbsp;So that when it was God's desire to make it specially clear to those who by his word were to have the heritage, that his purpose was fixed, he <b>made it more certain with an oath</b>;&nbsp;</span><span class="versetext" id="heb6-18" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">18</span>&nbsp;So that we, who have <b>gone in flight from danger to the hope </b>which has been put before us, <b>may have a strong comfort in two unchanging things</b>, in which it is not possible for God to be false;&nbsp;</span><span class="versetext" id="heb6-19" style="display: inline; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><span class="versenum" style="font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">19</span>&nbsp;And this hope is like a strong band for our souls, fixed and certain, and going in to that which is inside the veil;</span></span><br /><br />What Oath? In <a href="http://www.biblestudytools.com/nkjv/genesis/15.html">Genesis 15</a> we see Abraham ask God... How shall I know that you promise will come to pass? God has him bring a sacrifice and then in the course of the event God walks in the sacrifice to confirm it by blood. Jesus brought us into his covenant with the Father on the eve of his death. In <a href="http://www.biblestudytools.com/nkjv/luke/passage.aspx?q=luke+22:15-25">Luke 22</a> Jesus shows us the signs of his covenant. His Blood and Body are the signs of our covenant. Two things which make it impossible for God to lie. By His bodies stripes we are healed. By His Blood we are made&nbsp;righteous. As I meditate on what he did by his sacrifice, his blood and body, I am able to have confidence in the promises of God that come through His covenant with the Father in which I am made a partaker through Him.&nbsp;&nbsp; <br /><br />Soul... MIND, WILL, EMOTIONS. These are brought into anchor through HOPE which is sure through COVENANT SACRIFICE. I can be free of foolish arguments and petty bickering by calming my mind, will, and emotions in the assurance that GOD is GOD. HE is more&nbsp;interested&nbsp;in people knowing him than I am. He is their God not I. Leave convincing people to God. I will take up my job which is to LOVE people into the Kingdom.&nbsp;I may then "REST assured". This peace of God will reign in my heart. The LOVE of God can operate in me. I can be free to trust God to be God. Only then may I find the peace to turn away from foolish arguments and Love people into the&nbsp;Kingdom&nbsp;of God.<br /><br />Darrell G. Wolfe