---
title: 'Opening Scene of Job 2020'
date: '2011-10-01T04:46:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6868062471345359181'
blogger_filename: '/2011/09/opening-scene-of-job-2020.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Job''s Life Today'
---

<div style="text-align: center;">Job 1:1</div><div style="text-align: center;">There was a man in the land of Uz, whose name was Job;</div><div style="text-align: center;">and that man was blameless and upright and one who feared God and shunned evil...</div><div style="text-align: center;"><br /></div><div style="text-align: left;">Jebediah Orion Blackburn is the&nbsp;wealthiest&nbsp;man alive according to Forbes and Wikipedia. His family called him Job for short. He never took to any of the other nicknames and eventually he made it his moniker of choice. The press even caught on to it and began to publish articles with titles such as: "Job Strikes Oil Again". No one really knows for sure what Job is actually worth. He owns six of the top ten fortune 100 companies. He is a major share holder in real estate, entertainment,&nbsp;cruise lines, resorts, technology, weapons and arms, and many other fields. Disney has turned to him time and time again for help establishing their theme parks. Job has held the top defense contracts for 20 years running; out preforming and out bidding every&nbsp;competitor&nbsp;at most turns.&nbsp;</div><div style="text-align: left;"><br /></div><div style="text-align: left;">Today he is making the hardest decision he makes every day... which tie to wear. The silk tie collection boasts of over 100,000 choices. His dressing room is larger than some people's houses and the hangers rotate on a voice command. There is a touch screen image&nbsp;catalogue&nbsp;of every tie, but Job often prefers to see them up close instead. Normally there is&nbsp;hardly any hint of&nbsp;indecisiveness. Job would rather fix a mistake than loose an opportunity. Despite the enormous lifestyle he carries he still goes to the same church he has since he was a boy. The First Baptist Church of Dallas, thanks to his generous tithe checks which primarily go to the church, has also grown with him. He still finds time to serve on the board once a month and although he is too busy and too protected by media types to serve during service he still teaches a small class in the mornings on Christian Financial Principles to a pre registered limited class. Today he will be giving the offering message and despite the fact that he talks to much larger groups and audiences in his business life, speaking at the church still makes him as nervous as a little boy each time and today he just can't seem to find the perfect tie.&nbsp;</div><div style="text-align: left;"><br /></div><div style="text-align: left;">His wife and children still attend the church too, all seven sons and three daughters. They don't really attend because they want to, but rather because they don't get their allowance without sitting right next time him every Sunday morning no matter how hung over they feel from the night before. Their allowance is extremely generous and doesn't stop no matter how old they get. The oldest is 25 and is only permitted to miss only when he is on deployment for the military.&nbsp;</div><div style="text-align: left;"><br /></div><div style="text-align: left;">As he straightens the red and white tie he chose and brings it into it's perfect knot. There is a knock at the door. &nbsp;The limo is here and it's time to go. During the drive downtown, some kids are playing in the streets and he thinks back to the times that he and his best friend Abram would ride bikes and shoot the&nbsp;imaginary&nbsp;bad guys. Abram moved to Israel over 20 years ago, with his father and nephew, and doesn't make it back to the states as often as they'd like. He too became quite successful and in fact is the only real challenge in the world to taking Job's wealth status away from him. They still meet at conferences from time to time, but the meetings are always business and usually require them both to leave shortly after. They haven't had a good chat in a long time.</div><div style="text-align: left;"><br /></div><div style="text-align: left;">During the Limo ride the news speaks of the fatalities in Israel and the struggles going on there. He says a quick prayer of protection over his friend. &nbsp;The radio is turned off with a waive and a nod leaving silence for the rest of the ride to church.&nbsp;</div><div style="text-align: left;"><br /></div><div style="text-align: left;"><br /></div><div style="text-align: left;"><br /></div><div style="text-align: left;"><br /></div><div style="text-align: left;"><br /></div>