---
title: 'Full Circle'
date: '2011-04-16T14:08:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6536982573271679884'
blogger_filename: '/2011/04/full-circle_16.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Designers Danger'
---

Fashion. Couture. Money. These summed up the life of Jacques Sose'. The fact that he was born "Bobby Joe Smithe" in the backwaters of a Louisiana swamp to a deep Cajun family was known to very, very few. His own family, those that still lived, didn't know he was still alive and wouldn't recognize him if he walked in the house with all the changes he'd undergone in the last 10 years. Among the few who did know about his origins were his lawyer, who assisted with the new identity and kept it well hidden, his sister, Emma,&nbsp;who also left her past behind, and his partner Lazo Kalrian, who didn't know the details only that he had left some things behind. <br /><br /><br /><br />It was on the road between airports and meetings on the few occasions that he could find no travel with him that the memories of those days came back. Today he is driving from LAX to a GALA show in Palm Springs, CA. A beeping sound was a welcome intruder to the flash backs, accept that the beeping came from the gas indicator showing well into E. Jay, as his close friends called him, pulled off the road somewhere past San Bernardino.His mind was still full of visions of a history that he'd paid good money to supress. Apparently he'd fogotten to check the gas gauge at the last major city. <br /><br /><br /><br />This area gave him the chills. It wasn't quite the cajun swamp lands, but it still smelled of trailer parks, lucky strikes, and bud light. It took all the strength he had to put his highly paid Psychiatric medication to work in order to pull into the gas station. He pretended to be fishing for something in the car as a pan handler passed by asking for change. The man nearly knocked on Jay's window before being interupted by someone offering money accross the way. <br /><br /><br /><br />Shivering, from the filth not from the cold, he stood at the machine and threw a small fit when&nbsp;his card would not work. "Please see attendant" may as well have said "Go see swim with hungry sharks". "OK... OK..." Jay got a hold of himself "This isn't the gladiator ring in Rome this is just a gas station. You can do this. Just walk in, and pay, pump and go." He quickly strode accross the parking lot to the store to "see the attendant", chiding himself for neglecting to notify his bank of this trip to prevent his card from being declined. <br /><br /><br /><br />Jay stood in line behind a woman with a pink monster truck T-top and her two fighting kids and in front of a man with a tattered hoody that smelled like a sewage tank. He paid his for his pump in cash and rushed back to the car. He pumped, returned the nozzel, and got in. Filling out his milleage and gas log for his tax preparer Jay was suddenly distracted by a commotion in the store. The hoody wearer was flailing his arms about yelling at the attendant... gun in hand. The scene shocked him so much that he couldn't move. The man ran outside, glanced over the parking lot and headed... straight for Jay's car! Before he could think to put the car in gear and go the hoody had gotten into the backseat. "Drive!"<br /><br /><br /><br />At first Jay didn't move but at the sound of the round entering the chamber, he put the car in gear. It had been 10 years since he'd heard that sound. Cajun people all use and carry guns. He could probably still take one apart and put it back together blindfolded like his uncle used to make him do. "Where to sir?" Jay asked. "Anwhere else! Move it!" so they headed out and onto the highway toward Palm Springs. Maybe he could still make his meeting and the man could have this nice car afterward...