---
title: 'Paper'
date: '2011-04-22T22:01:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5798317556249210985'
blogger_filename: '/2011/04/paper_22.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Creative Writing Guild'
---

<div class="Section1"><br /><div class="MsoNormal"><br /><span style="font-family: Arial; font-size: x-small;"><span style="font-family: Arial; font-size: 10pt;">He stood before an audience of 3,000. He took out a blank notebook and slowly, ceremoniously, ripped out a piece of paper. The sound carried across the auditorium through his lapel mic. He never tired of this demonstration. He held out this paper over his head. Walking down passed the first 100 seat section, he stopped in near a disinterested young man in his late teens. “Excuse me, young man,” He prodded. “could you tell me what this is?” The teen looked up as he handed him the paper. “It’s a piece of paper” The young man replied un-amused. “It is?” the speaker replied. The speaker prodded further, “Is that all it is? Is that all you see?” The teen looked it over, and turned it around a few times. “A blank piece of paper?” The teen asked as if he wasn’t getting the question. <o:p></o:p></span></span></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><span style="font-family: Arial; font-size: x-small;"><span style="font-family: Arial; font-size: 10pt;">“Does anybody else see anything differently?” the speaker took the paper back and held it up again. He waited a beat before moving on. “I don’t see a blank piece of paper. I see money!” The teen must have thought it an interesting thing to say as he sat up a little straighter and leaned forward. He removed his hood to reveal a snake tattoo rotating around from his ear around his neck to the opposite shoulder and large holes in his ears. <o:p></o:p></span></span></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><span style="font-family: Arial; font-size: x-small;"><span style="font-family: Arial; font-size: 10pt;">“Potential” the speaker began to expound. “All things big or small begin as potential. This paper could be a battle plan for an expert tactician, a play in the play book of a head coach, or a new hit song or popular novel. This paper could just as easily…” he began to rip strips of paper off and crumple it before tossing it over his shoulder to the floor behind. “…be trash. Yesterday’s big ideas. How many people ever envisioned something only to see it on the market later. How many writers considered small electronic handheld devices that could carry a voice and images over distance to other hand held devices before the first cell phones hit the markets? Ideas are not enough. They must be carried out.” He held one last strip “This is a new invention” and he crumpled it u and flicked it at the teen. “Young man..” he turned. “Please examine that” <o:p></o:p></span></span></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><span style="font-family: Arial; font-size: x-small;"><span style="font-family: Arial; font-size: 10pt;">He waited as the teen turned it over a few times. “Would you like to keep it or toss it?” The speaker asked with a wink. “The teen was not appreciating the attention and threw it at the speakers chest. “Toss it!” the teen replied. The paper hit his chest and landed on the floor in front of him. “OK, the young man doesn’t want to be an inventor. Anyone else care to examine the trashed idea?” A few moments of expectant silence followed. Finally a young girl, about ten, stepped into the aisle a few rows back. “I would” she said. Her mother motioned her back but the speaker had already motioned her forward and she was stepping up to the paper, smiling. She looked at the wad of paper as though at any moment it might explode into fireworks or some great magic.<o:p></o:p></span></span></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><span style="font-family: Arial; font-size: x-small;"><span style="font-family: Arial; font-size: 10pt;">The speaker winked at her and smiled, he kicked it with his toe at her and turned to walk away. The young girl stepped up to it and picked it up from the floor. “I think” she began, and the speaker stopped and looked back over his shoulder, “I see a cave” she said finally. “Really?” the speaker turned all the way back to her. “And?” Her small face contorted into an exaggerated look of concentration. “Inside” she began again “ see a Dragon. He is a tall Dragon, stately looking, but with a broken wing. He is green and he is hiding from a man in the cave.”<o:p></o:p></span></span></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><span style="font-family: Arial; font-size: x-small;"><span style="font-family: Arial; font-size: 10pt;">The speaker then pressed her further, “Is the man in the cave or the Dragon?” To which the girl replied “The Dragon of course.” She smiled. “I DO believe this young girl may be the smarted person in the whole room today!” he exclaimed. He waited a moment to let the rooms attention build. He turned back to her, egging her on to produce more details and finally he yelled as though we really were on a mission to protect this very real Dragon… “HURRY! Enter the cave! He must be protected at all costs!” It was now he and she in the room. He treated the rest of the room as though they didn’t exist for the moment. The girls expression was dramatic and excited she opened the wad and stopped suddenly. The whole audience was enraptured with the scene. <o:p></o:p></span></span></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><span style="font-family: Arial; font-size: x-small;"><span style="font-family: Arial; font-size: 10pt;">She examined the wad as she pulled out from it’s crevices a small bit of green. “We have found the dragon!” he said triumphantly. It too was paper and she revealed it to the audience as she unfolded it. A $100 bill. “That” he said softly over his mic, “is for having a vision my young girl. Go find your dragon and get me the rest of that story.”<o:p></o:p></span></span></div><br /><div class="MsoNormal"><br /><br /></div><br /><div align="center" class="MsoNormal" style="text-align: center;"><br /><span style="font-family: Arial; font-size: x-small;"><span style="font-family: Arial; font-size: 10pt;">15 years later<o:p></o:p></span></span></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><span style="font-family: Arial; font-size: x-small;"><span style="font-family: Arial; font-size: 10pt;">25 year old Victoria De La Corazon sat huddled over a desk, cheek pasted to her notebook. The other cheek was lighted softly by the blue hue of her computer monitor. She was still wearing her sever uniform from Denny’s, she didn’t bother changing when she got home because she wanted to get to her desk immediately, back to her dragon. She had fallen asleep as fire was clashing against shield. The first signs of morning now showing against her far wall, Vicky as they called her, began to stir. She grabbed her notebook and loaded her school bags and rushed for a quick shower and change. <o:p></o:p></span></span></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><span style="font-family: Arial; font-size: x-small;"><span style="font-family: Arial; font-size: 10pt;">She had spent 7 years working on her degree from the local <st1:place w:st="on"><st1:placetype w:st="on">State</st1:placetype> <st1:placetype w:st="on">University</st1:placetype></st1:place>. She had to attend part time, as she worked full time to pay for school and apartment. One week from now she would graduate. She already had 5 major publishers giving firm offers for well paying jobs as an editor and book reviewer, due in no small part to her dear professor Charles Stanfield. She was among his best and brightest students. She could still recall the day she met him, in an auditorium full of people. It wasn’t the $100 that sparked her love for him, it was his belief in her. Now she was studying under him. As images of street signs and store fronts passed her through the window of the public bus she rode to school each morning, her thoughts drifted to another world, full of mystery and dragons and fighting for survival.<o:p></o:p></span></span></div><br /><div class="MsoNormal"><br /><br /></div><br /><div align="center" class="MsoNormal" style="text-align: center;"><br /><span style="font-family: Arial; font-size: x-small;"><span style="font-family: Arial; font-size: 10pt;">--<o:p></o:p></span></span></div><br /><div class="MsoNormal"><br /><span style="font-family: Arial; font-size: x-small;"><span style="font-family: Arial; font-size: 10pt;">Professor Charles, now President of the “Creative Writing Guild” and Head Dean for the school of fiction authors at the university, was now reclining in his dungeon. <o:p></o:p></span></span></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /><div class="MsoNormal"><br /><br /></div><br /></div><br />