---
title: 'A Call to Fellowship'
date: '2011-01-02T19:01:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '227151196370466091'
blogger_filename: '/2011/01/a-call-to-fellowship.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<a href="http://www.emic.org/">EMIC </a>Sunday Morning 01/01/2011<br /><br />Heaven has released a call to fellowship. A call to fellowship with HIM. A call to fellowship with one another. Set aside time with HIM, that is NOT optional! <br /><br /><br />God is saying let me show you how much he wants you to have fellowship with HIM. Feeling that God doesn't want you around is from a sense of unworthiness which is always of the devil. God has MADE US HIS RIGHTEOUSNESS! How then can we be unworthy? To call yourself an unworthy sinner is to call the blood of Jesus unworthy! It's blasphemy to see yourself as anything less than the very righteousness of God.<br /><br />There is nothing you can do that could make God the Father love you more than he already does before you were even born! But there are things you can do to experience that love more and to increase your fellowship with him, as the prodigal son who came back so too you can return to that fellowship. <br /><br />The more communion you have with HIM the sweeter your relationships are with others. If you have strife and bickering and complaining and sarcasm at work in your life, it is a sign that you have no communion with your Father in heaven. <br /><a href="http://www.blogger.com/goog_1564525276"><br /></a><br /><a href="http://www.biblegateway.com/passage/?search=Jeremiah%2024:7&amp;version=NKJV">Jeremiah 24:7</a><br />Then I will give them a heart to know Me, that I <i>am</i> the LORD; and they shall be My people, and I will be their God, for they shall return to Me with their whole heart.    <br /><a href="http://www.blogger.com/goog_1564525280"><br /></a><br /><a href="http://www.biblegateway.com/passage/?search=Revelation%203:20&amp;version=NKJV">Revelation 3:20</a><br />Behold, I stand at the  door and knock. If anyone hears My voice and opens the door, I will  come in to him and dine with him, and he with Me.<br /><br /><br />God said to Adam and is saying to us: Where are you? I want to walk and talk with you!