---
title: 'Thoughts about 2012'
date: '2011-11-21T00:23:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5560561690266586531'
blogger_filename: '/2011/11/thoughts-about-2012.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'Random'
  - 'Prayer Time'
---

<br /><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><span style="font-family: 'Bookman Old Style', serif; font-size: 12pt; line-height: 115%;">I've been feeling more and more, watching the in fighting and lack of leadership within the republican party, that President Obama may end up with two terms. Most people aren't seeing clear leadership from either side.&nbsp;Independents&nbsp;will not vote one out without having a clear vision from the other side. Many&nbsp;independents&nbsp;feel that the evil we know is better than the evil we do not know. So unless there is a&nbsp;divine&nbsp;intervention President Barak Obama will be heading into his second term.</span><span style="font-family: 'Bookman Old Style', serif; font-size: 12pt; line-height: 115%;"><o:p></o:p></span></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><span style="font-family: &quot;Bookman Old Style&quot;,&quot;serif&quot;; font-size: 12.0pt; line-height: 115%; mso-bidi-font-family: Tahoma; mso-fareast-font-family: &quot;Times New Roman&quot;;">However I have also felt since the begining that God has a plan for him. He will see for himself that his policies aren't working and turn to God in despair. He will become a great man and leader. I'm not a prophet, but this has been more than a desire. It's been an urge and prayer. It impresses me the same as it did on the day I was moved on to pray for Michael Jackson out of the blue, then a week later he was announced dead.<o:p></o:p></span></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><span style="font-family: &quot;Bookman Old Style&quot;,&quot;serif&quot;; font-size: 12.0pt; line-height: 115%; mso-bidi-font-family: Tahoma; mso-fareast-font-family: &quot;Times New Roman&quot;;">I have that same feeling regarding this presidential race. There will be things that happen this next year that will turn the world upside down. Some good and some bad. The people of Faith will always come out ahead! Here are some thoughts about 2012 from two people I pay attention to:</span><span style="font-family: &quot;Bookman Old Style&quot;,&quot;serif&quot;; font-size: 12.0pt; line-height: 115%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;;"><o:p></o:p></span></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><b><span style="font-family: &quot;Bookman Old Style&quot;,&quot;serif&quot;; font-size: 12.0pt; line-height: 115%; mso-bidi-font-family: Tahoma; mso-fareast-font-family: &quot;Times New Roman&quot;;">Kenneth Copeland&nbsp;prophesied&nbsp;about 2012:</span></b><span style="font-family: &quot;Bookman Old Style&quot;,&quot;serif&quot;; font-size: 12.0pt; line-height: 115%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;;"><o:p></o:p></span></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><span style="font-family: &quot;Bookman Old Style&quot;,&quot;serif&quot;; font-size: 12.0pt; line-height: 115%; mso-bidi-font-family: Tahoma; mso-fareast-font-family: &quot;Times New Roman&quot;;">"What about 2012? 2012 is a year full of surprises! Some surprises are going to shake people up. Some surprises are going to shake people down. But for those who are listening to My Voice (God's Voice), those who have made themselves available to My Spirit and to My Word, you'll have surprises... oh not like the world and not like many carnal minded Christians... Your surprises will come as "Suddenlies". Like in My Word when it says "...and suddenly there came upon them..." And you'll stand up with a big smile on your face and say "I just got a suddenly didn't I?" Oh yes, but it will not take you by surprise because I said in My Word I'd show you things to come, I said in My Word what I speak the Holy Ghost will hear and He will speak it to you and there are those of you that are seeking My Voice and seeking My Word and seeking My Name and looking at Me and My Face while I'm looking at you in your face and together we'll walk in this and together we'll walk through this and they'll come a time when you'll just smile at me and I'll just smile at you and you'll say "Ha Ha Ha I knew that all the time! Praise God! My Father showed me that was comin' and I was all prepared and it didn't come on me as a suddenly. But this other&nbsp;surprise&nbsp;that came on me oh what joy, oh what thrill, oh what goodness, I wonder what else my Father has in store for me?!"... Continued at&nbsp;<a href="http://www.youtube.com/watch?v=_Kkb94XRFhc&amp;feature=share"><span style="color: blue;">http://www.youtube.com/watch?v=_Kkb94XRFhc&amp;feature=share</span></a><o:p></o:p></span></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><span style="font-family: &quot;Bookman Old Style&quot;,&quot;serif&quot;; font-size: 12.0pt; line-height: 115%; mso-bidi-font-family: Tahoma; mso-fareast-font-family: &quot;Times New Roman&quot;;">Then I looked to see what Kim Clement had been saying about it. And this is what I found...<o:p></o:p></span></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><b><span style="font-family: &quot;Bookman Old Style&quot;,&quot;serif&quot;; font-size: 12.0pt; line-height: 115%; mso-bidi-font-family: Tahoma; mso-fareast-font-family: &quot;Times New Roman&quot;;">Kim Clement:</span></b><span style="font-family: &quot;Bookman Old Style&quot;,&quot;serif&quot;; font-size: 12.0pt; line-height: 115%; mso-bidi-font-family: Tahoma; mso-fareast-font-family: &quot;Times New Roman&quot;;"><o:p></o:p></span></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><span style="font-family: &quot;Bookman Old Style&quot;,&quot;serif&quot;; font-size: 12.0pt; line-height: 115%; mso-bidi-font-family: Tahoma; mso-fareast-font-family: &quot;Times New Roman&quot;;"><a href="http://www.kimclementvault.com/prophecyread.asp?num=495"><span style="color: blue;">http://www.kimclementvault.com/prophecyread.asp?num=495</span></a><o:p></o:p></span></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><span style="font-family: &quot;Bookman Old Style&quot;,&quot;serif&quot;; font-size: 12.0pt; line-height: 115%; mso-bidi-font-family: Tahoma; mso-fareast-font-family: &quot;Times New Roman&quot;;">"DISCUSSING HOW HE MET ELLIS SMITH, AND PROPHESIED ABOUT AN AFRICAN-AMERICAN PRESIDENT<o:p></o:p></span></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><span style="font-family: &quot;Bookman Old Style&quot;,&quot;serif&quot;; font-size: 12.0pt; line-height: 115%; mso-bidi-font-family: Tahoma; mso-fareast-font-family: &quot;Times New Roman&quot;;">I believe at that time, I was picking up about an African-American president.&nbsp; That’s what I was picking up, because you drew that out of me, and even though people have their own ideas about this present president, I want you to know there’s an African-American president coming again – again. I hate to say this – this is the Spirit of the Lord on me, I have to do it.&nbsp; The Lord said to me when He took me to Memphis, and I was in a big church there (it was an African-American church), when I was in this church, the Lord said this to me.&nbsp; Because I prophesied Obama, that he would be the president, twice.&nbsp; It was very difficult for me – not that he was a black man; in fact, I was overjoyed about it.&nbsp; It was because of his beliefs.&nbsp; But the Lord said this to me; He said, first of all, I’m going to teach America a lesson.&nbsp; They’ll never vote like this again.&nbsp; Secondly, I do not want him to misrepresent his race and his people.&nbsp; I know he’s an American, but he’s an African-American.&nbsp; So God – He said this to me:&nbsp; He will not leave in shame, and if he does, I will raise up another one, a righteous one, who will bring honor to the African-American people in the United States of America, as a president."<o:p></o:p></span></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><span style="font-family: 'Bookman Old Style', serif; font-size: 12pt; line-height: 115%;">Should&nbsp;be and interesting year...Darrell G. Wolfe<o:p></o:p></span></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal" style="margin-bottom: .0001pt; margin-bottom: 0in;"><br /></div><div class="MsoNormal"><br /></div>