---
title: '120 Years...or more...'
date: '2011-10-02T20:53:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4503485555548793909'
blogger_filename: '/2011/10/120-yearsor-more.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'EMIC'
  - 'study'
  - 'Random'
  - 'Prayer Time'
---

<b>Lives cut short:</b><br /><br />Our lives are cut short by so many things in this sin cursed world. Drugs, lifestyle, overeating, toxins, lack of body health care, murder, and many other things threaten our lives and the productivity of our lives today. There are more classified&nbsp;diseases&nbsp;today than one could have imagined 100 years ago. They aren't just being discovered they are mutating and increasing.<br /><br /><b>Not just 80 years:</b><br />Among the many things we CAN control about our lives is our words. The bible says life and death are in the tongue. (<b>Prov 18:21</b>)&nbsp;People in the church world for years thought of this as a biblical cut off time. People should live to be 70-80. This is not only false but very false. This is referring to the children of Israel living in disobedience. God needed them off the scene to move the next generation into the promise land.<br /><br /><b>Psalms 90:10</b> says: The days of our lives are 70 years, and if by reason of strength they are 80,...<br /><br /><b>Not just 120 Years:</b><br />Then some have taken the scripture in Genesis and increased our thinking to believe God for the 120 years marker...(<b>Genesis 6:3</b>)<br /><br />However I submit that even THAT marker is not refering to man in general or even to lifespan at all, but rather an actual time frame given by God to a specific group of men, those living in the preflood times with Noah. He says that there will be 120 years from the time he declares he will rid the earth of sinful men to the time he does it. This gives him time to reach Noah and get him building an ark. Have you ever been called of God to do something and then delayed, doubted, stopped and started several times... etc... I imagine with preflood tools and an entire earth population against the idea he took a while to complete this massive project. Infact I don't doubt that Noah could have taken between 100-120 years to complete the project. He was 500 when he had his third kid and 600 when the flood came. Why not more kids? I submit that he started that ark project shortly after kid 3...<br /><br /><b>Study here:</b><br /><b>Genesis 6</b> tells us another&nbsp;interesting&nbsp;fact about life and even then people are looking to use it as a cap on life. People are so quick to make the infinite finite...<br />&nbsp;Verse<b> 3</b>: And the Lord said: "My Spirit shall not strive with man forever, for he is indeed flesh, yet his days shall be 120 years.<br />Verse <b>13</b>: And God said to Noah, "The end of all flesh has come before me, for the earth is filled with violence through them, and behold, I will destroy them with the earth.<br />Genesis <b>5:32</b> Noah was 500 years old when he begat his three kids<br />Genesis <b>7:6</b> Noah was 600 years old when he entered the ark and the flood waters hit the earth.<br /><br /><b>120 Years and beyond:</b><br /><br />Since there is no real cap to our lives, and many tales are told of people in recent times living beyond 120 years I imagine it's entirely up to you and God. I have determined that, should the Lord wait long enough, I will live to 150 years old, strong, healthy, full of vigor and then decide how much longer I want to go. I will be stronger and healthier then than I am now. No sickness, feebleness, perfect eye sight, and full of the Holy Spirit. Like Moses who died at 120 years old&nbsp;(Deut 34:7), also due to disobedience by the way (Numbers 27:12-13), I will remain strong with perfect vision.<br /><br />Hmm... How long will you live?<br /><br /><br />Darrell G. Wolfe<br /><br /><br /><br /><br /><br />