---
title: 'Invitation to Apply... The Blood'
date: '2011-11-14T15:01:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4356486295477618827'
blogger_filename: '/2011/11/invitation-to-apply-blood.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'KOG'
  - 'Daily Reading'
---

<b>COME:</b><br />1 Peter 4<br /><span class="versenum" style="font-family: arial; font-size: 14px; font-weight: bold; line-height: 20px; margin-bottom: 0px; margin-left: 0px; margin-right: 3px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">6</span><span class="Apple-style-span" style="background-color: ; color: #; font-family: arial; font-size: 14px; line-height: 20px;">&nbsp;For this reason the gospel was preached also to those who are dead, that they might be judged according to men in the flesh, but live according to God in the spirit.&nbsp;</span><br /><br /><b>HEAR:</b><br />Jesus preached the Gospel to all those in Hades and in Abraham's Bosom before&nbsp;ascending&nbsp;from the dead to greet Mary at the tomb. I have become fully&nbsp;convinced, as I learn both the Mercy/Grace side of God and the Justice/Judgement side of God, &nbsp;that there is not one human on earth past or present from Adam to the final man/woman/child that will spend an eternity&nbsp;separated&nbsp;from God without having a chance to accept His gift.<br /><br />There are many who will become so hardened through life that they will reject it, which makes our influence in the World SO MUCH more important. However God is not sending people to hell because the post office lost/miss-delivered His invitation in the mail.<br /><br />Everyone on earth has been forgiven of sin. You are not in need of forgiveness you have it. You've had it since before the foundation of the world. What you are in need of is the application of the blood to your life. If you fail to apply the blood, even though it's been provided, your house is not protected. That applies to this life and the life to come. You are in need of knowing about the forgiveness that was purchased and accept it.<br /><br />The offer is a trade. You trade your life for His. He takes your sin and you take His righteousness.<br /><br />It has been proved out over and over that seeing is not believing. Many people see "Evidence" and believe it when it was made up or false. Others see evidence of something true and choose not to believe. Just because you see something doesn't mean you will believe it. Just because something is offered doesn't mean you will accept it.<br /><br />I know of a man who was offered birthday presents every year by his son. One year, he returned them all, years worth, unopened. He had taken them... but not received them. You can know about Jesus, without accepting Him. You can preach Him, but not KNOW Him.<br /><br />Contrarily, you can NOT know of Him, but be introduced to him and accept. Paul prayed a SHORT salvation prayer... <a href="http://www.biblestudytools.com/nkjv/acts/passage.aspx?q=acts+9:3-13" target="_blank">"LORD, what do you want me to do?!"</a>. I don't know how many times I've heard of near death experiences, but one bears mentioning here.<br /><br />A young lady was living in sin, she'd heard of Jesus in a&nbsp;cursory&nbsp;manner like most&nbsp;Americans, but was not&nbsp;church-ed. She was living in sin, drugs, etc. She was stabbed one night by a man who just wanted to use her. As she lay there on the ground she suddenly felt light. She stood up and looked down to see her body laying there. She was fully aware of everything around her. It was just as though she wasn't dead but the pain was gone. A door opened up in front of her and a bright light streamed in. Jesus stepped through the door and began to talk with her. He told her about His blood and her choice. She chose Him. He then gave her the choice of coming back to heaven with Him or staying on earth to complete His real calling for her. She chose to stay. Since then she has had a ministry of healing and bringing deliverance to hospitals and churches to the sick and dying.<br /><br />What happened here? We failed to reach that young woman, so Jesus stepped in and did it. He will NOT let anyone go without the choice. He said he'd leave the 99 and go out to get the 1. He does it time and again. But we, the church, could have reached her before that stabbing. I know, because I know His heart, that people were called to reach out before and didn't.<br /><br /><b>DO:</b><br />I must begin to work on having HIS heart for people and loving with HIS love. Seeing people for who they are in Him. Praying for them actively, not passively. Asking the Holy Spirit, how can I assist you today, in this situation?<br /><br /><b>PRAYER:</b><br />Father, make me more like you. Show me, day by day, how to walk out YOUR love for people. Starting at home.<br /><br /><b>Reference:</b><br /><b><a href="http://www.biblestudytools.com/nkjv/ephesians/passage.aspx?q=ephesians+2:13-21" target="_blank">Ephesians 2:13-21 (New King James Version)</a></b><br />13 But now in Christ Jesus you who once were far off have been brought near by the blood of Christ. 14 For He Himself is our peace, who has made both one, and has broken down the middle wall of separation, 15<b> having abolished in His flesh the enmity, that is, the law of commandments contained in ordinances</b>, so as to create in Himself one new man from the two, thus making peace, 16 and<b> that He might reconcile them both to God in one body through the cross, thereby putting to death the enmity. 17 And He came and preached peace to you who were afar off and to those who were near.</b> 18 For through Him we both have access by one Spirit to the Father. 19 Now, therefore, you are no longer strangers and foreigners, but fellow citizens with the saints and members of the household of God, 20 having been built on the foundation of the apostles and prophets, Jesus Christ Himself being the chief corner stone, 21 in whom the whole building, being joined together, grows into a holy temple in the Lord, <br /><br /><b><a href="http://www.biblestudytools.com/nkjv/colossians/passage.aspx?q=colossians+1:19-21" target="_blank">Colossians 1:19-21 (New King James Version)</a></b><br />19 For it pleased the Father that in Him all the fullness should dwell, 20 and by <b>Him to reconcile all things to Himself</b>, by Him, whether things on earth or things in heaven, having made peace through the blood of His cross. 21 And you, who once were alienated and enemies in your mind by wicked works, yet now He has reconciled <br /><br /><b><a href="http://www.biblestudytools.com/nkjv/2-corinthians/passage.aspx?q=2-corinthians+5:18-20" target="_blank">2 Corinthians 5:18-20 (New King James Version)</a></b><br />18<b> Now all things are of God, who has reconciled us to Himself through Jesus Christ, and has given us the ministry of reconciliation,</b> 19 that is, that God was in Christ reconciling the world to Himself, not imputing their trespasses to them, and has committed to us the word of reconciliation. 20 Now then, we are ambassadors for Christ, as though God were pleading through us: we implore you on Christ's behalf, be reconciled to God. <br /><br /><b><a href="http://www.biblestudytools.com/search/?q=apply+blood&amp;c=&amp;t=nas&amp;ps=10&amp;s=Bibles" target="_blank">Exodus 12:22 NAS</a></b><br />"You shall take a bunch of hyssop and dip it in the blood which is in the basin, and<b> apply some of the blood</b> that is in the basin to the lintel and the two doorposts ; and none of you shall go outside the door of his house until morning. <br /><br /><b><a href="http://www.biblestudytools.com/search/?q=lamb+slain&amp;c=&amp;t=nkjv&amp;ps=10&amp;s=Bibles" target="_blank">Revelation 13:8 NKJV</a></b><br />All who dwell on the earth will worship him, whose names have not been written in the Book of Life of the <b>Lamb slain from the foundation of the world. </b><br /><br /><br /><br /><br /><br />