---
title: 'Rejoice... put on a smile!'
date: '2012-09-07T04:20:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5808587618678884467'
blogger_filename: '/2012/09/rejoice-put-on-smile.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

Rejoice in the Lord always, again I say: REJOICE! <a href="http://bible.cc/philippians/4-4.htm" target="_blank">Phill 4:4</a><br /><br />To rejoice is to have joy again. It's a choice, not based on circumstances. This is a hard pill to swallow. I have been VERY busy. I haven't written anything in months. It's time I picked up again, when I can. So I write now to say this very simple thing. SMILE! You're on Candid God Cam! Yes, God is always with you. There is a cloud of witnesses that are watching you. Angels are with you. Demons are watching... and people are watching, especially the ones that you don't even realize know that you exist. Yes... they are watching too.<br /><br />Science has shown us, time and again, that if you smile, you're body will actually respond. People who smiled, on purpose, for a science test actually experience quick response in lower blood pressure and other healthy responses. So smile, who cares how you feel, smile! Before you tell me that you can't, remember that you have done it a thousand times for a church event, work, or meeting someone new. People who don't feel like smiling put on a smile all the time. Well, as it turns out there are benefits to smiling.<br /><br />Put on the garment of praise for the spirit of heaviness. If you choose joy enough times, it will eventually infect your emotions too.<br /><br />Darrell<br /><br /><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br /><a href="https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118" target="_blank">Facebook.Com/EmpoweredTooProsper</a><br /><span style="background-color: white; font-family: 'Times New Roman', Times, FreeSerif, serif; font-size: 15px; line-height: 20px;"><b><br /></b></span><span style="background-color: white; font-family: 'Times New Roman', Times, FreeSerif, serif; font-size: 15px; line-height: 20px;"><b>For other sites by Wolfe Family Conceptions:&nbsp;</b></span><br /><ul><li><a href="http://wfconceptions.wordpress.com/" target="_blank">http://wfconceptions.wordpress.com/</a></li></ul><br /><b style="background-color: white;">Darrell G. Wolfe</b><br /><br /><b style="background-color: white;">See Also N2 Good Success:</b><br /><br /><br /><ul><li><a href="http://n2gs.blogspot.com/" style="background-color: white;">http://n2gs.blogspot.com/</a></li><li><a href="https://www.facebook.com/n2goodsuccess?sk=wall" style="background-color: white;">https://www.facebook.com/n2goodsuccess</a></li><li><span style="background-color: white;">Book Suggestion from the&nbsp;</span><a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" style="background-color: white;" target="_blank">N2 Good Success Amazon Store</a></li><li><span style="background-color: white;">Product Offerings from&nbsp;</span><a href="http://www.zazzle.com/n2goodsuccess" style="background-color: white;" target="_blank">N2 Good Success Zazzle Store</a></li></ul><br /><br /><b>Bulldog Publications:&nbsp;</b><br /><b><a href="http://www.amazon.com/dp/1453815619/ref=as_li_ss_til?tag=your0f4d-20&amp;camp=213381&amp;creative=390973&amp;linkCode=as4&amp;creativeASIN=1453815619&amp;adid=1NAWEWPYWDQA3XGCY7N5&amp;&amp;ref-refURL=http%3A%2F%2Fn2gs.blogspot.com%2F" target="_blank">Bankings Basics for Believers; Now Available on Amazon.&nbsp;</a></b><br /><b>Print&nbsp;Edition</b><br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=1453815619" style="height: 240px; width: 120px;"></iframe><br /><br /><b>Kindle Edition</b><br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=B008EO488Y" style="height: 240px; width: 120px;"></iframe><br /><br /><br /><br /><br /><br /><br class="Apple-interchange-newline" /><iframe allowtransparency="true" src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fn2goodsuccess&amp;width=292&amp;height=62&amp;colorscheme=light&amp;show_faces=false&amp;border_color&amp;stream=false&amp;header=true&amp;appId=272647732784155" frameborder="0" scrolling="no" style="background-color: white; border-style: none; height: 62px; overflow: hidden; width: 292px;"></iframe><br /><br /><br /><br /><br /><br /><iframe allowfullscreen="allowfullscreen" frameborder="0" height="315" src="http://www.youtube.com/embed/pOgP3f3519I" width="420"></iframe> <br /><br />