---
title: 'Faith in His Name'
date: '2012-05-08T16:13:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7947744524274127286'
blogger_filename: '/2012/05/faith-in-his-name.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<div style="text-align: center;"><b>COME</b>:</div><blockquote class="tr_bq"><div style="text-align: justify;"><b><a href="http://www.biblestudytools.com/nkjv/acts/passage.aspx?q=acts+3:11-16" target="_blank">Acts 3:11-16</a></b></div></blockquote><blockquote class="tr_bq"><div style="text-align: justify;"><i>11 Now as the lame man who was healed held on to Peter and John, all the people ran together to them in the porch which is called Solomon's, greatly amazed. 12 So when Peter saw it, he responded to the people: "Men of Israel, why do you marvel at this? Or why look so intently at us, as though by our own power or godliness we had made this man walk? 13 The God of Abraham, Isaac, and Jacob, the God of our fathers, glorified His Servant Jesus, whom you delivered up and denied in the presence of Pilate, when he was determined to let Him go. 14 But you denied the Holy One and the Just, and asked for a murderer to be granted to you, 15 and killed the Prince of life, whom God raised from the dead, of which we are witnesses. 16 A<b>nd His name, through faith in His name, has made this man strong</b>, whom you see and know. Yes<b>, the faith which comes through Him has given him this perfect soundness</b> in the presence of you all. </i></div></blockquote><div style="text-align: center;"><b>HEAR</b>:</div><div style="text-align: center;"><br /></div><div style="text-align: justify;"><b>His Name</b>, through faith in His name, has made this man strong.&nbsp;</div><div style="text-align: justify;"><br /></div><div style="text-align: justify;"><b>His Name</b>; therefore,<b> the Name of Jesus</b>, which is above every name, has power in and of itself. However, those who would wield that name must also have faith in that name.</div><div style="text-align: justify;"><br /></div><div style="text-align: justify;">How often do we end a prayer with "...in the Name of Jesus, Amen (which means so be it)"? Did we pray the Word? Did we pray His Will? We should find out His will in prayer, and then pray it... was that prayer that we ended with His Name and So Be It a prayer based on His Will/Word? We thought it around so easily.</div><div style="text-align: justify;"><br /></div><div style="text-align: justify;"><b>Faith in His Name</b>; Do I have faith in His Name? Faith implies a firm belief and trust. I can see that which is not seen and do that which cannot be done. Telling a lame man to walk is impossible, unless you have Jesus.&nbsp;</div><div style="text-align: center;"><b><i>See the Invisible, Do the Impossible</i></b></div><div style="text-align: justify;"><br /></div><div style="text-align: justify;">But if I'm praying in doubt, fear, not really believing much will happen, I'm not praying with Faith in His name. I'm praying with Faith in the circumstances, situations, or the opinions of others. I'm praying the meditations of what I don't have or what I need or wish I had. Prayer in doubt is&nbsp;ineffective. God, in His great mercy, will sometimes use that prayer to meet our needs if there was an ounce of faith in it, and that is the level we were at.&nbsp;However, if you KNOW better... God is going to stare at you and wait for you to try again.&nbsp;</div><div style="text-align: justify;"><br /></div><div style="text-align: justify;">My kids sometimes come up to me&nbsp;whining&nbsp;about something. I can't even understand what they said sometimes, but other times I may understand what they said, but choose not to respond because they KNOW better than to talk to me a that tone of voice. I'll respond: "<i>Breath! Now speak to me correctly, with no&nbsp;whining.</i>" It may take a few tries, but eventually they do as we taught them, to put a smile in their voice when they want to talk to us.&nbsp;</div><div style="text-align: justify;"><br /></div><div style="text-align: justify;">That's what Jesus is asking from us too. Could you imagine Peter saying, "Oh God! Oh God! PLEASE heal this man... PlEEEEEEEEEASE Heal this man....." NO! He took his authority, given to him, and practice beforehand and commanded that man to be healed. But a smile in your voice! You have the Name, the Power, The Holy Spirit, The Word: That is grown up prayer and faith.&nbsp;</div><div style="text-align: justify;"><br /></div><div style="text-align: justify;">I think it would be a good practice to start our prayers in silence, or tongues, and wait for a moment. Take a deep breath and SMILE really big! Make that connection with the Holy Spirit before running off your laundry list of needs, wants, and desires. Maybe taking a moment just say: "I love you" to God and then letting the Holy Spirit lead and guide your prayer, would be more productive than running off when "The Usual".</div><div style="text-align: justify;"><br /></div><div style="text-align: justify;">If we come to God in Prayer and Thanksgiving, He'll set our minds and hearts at rest.</div><blockquote class="tr_bq"><div style="text-align: justify;"><a href="http://www.biblestudytools.com/kjv/philippians/passage.aspx?q=philippians+4:5-7" target="_blank">Philippians 4:5-7</a></div><div style="text-align: justify;">5 Let your moderation be known unto all men. The Lord is at hand. 6 Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. 7 And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.</div></blockquote><div style="text-align: center;"><b>DO</b>:&nbsp;<b>PRAYER!</b></div><div style="text-align: justify;">If there were a "method" to prayer, and there isn't just one method, I would&nbsp;prescribe&nbsp;this method.</div><div style="text-align: justify;"><br /></div><div style="text-align: justify;">I'm going to take a moment now and just:</div><br /><ul><li style="text-align: justify;">Breath... let your mind meditate on how GOOD GOD IS!</li><li style="text-align: justify;">SMILE, force it if I have to!</li><li style="text-align: justify;">Tell The Father, Jesus, and the Holy Spirit; How much I love them.&nbsp;</li><li style="text-align: justify;">Thank God for everything I can come up with to thank Him for, as long as it takes for those words of thanksgiving to stop being just words and start creating a feeling of thanks inside of me.&nbsp;</li><li style="text-align: justify;">Then I'm going to say: Father, you know what I need, tell me what to pray for or about.</li><li style="text-align: justify;">Then I'll pray in tongues a little while.&nbsp;</li><ul><li style="text-align: justify;">Then I'll be lead in my prayer.&nbsp;</li></ul></ul><br /><div style="text-align: justify;">As the Holy Spirit leads I may start praying about my life, my families life, my leaders, pastors, bosses, government... etc... I may say something like: "As you said in your word...."&nbsp;</div><div style="text-align: justify;"><br /></div><div style="text-align: justify;">Only then can I end with In the Name of Jesus - So Be It (Amen). Because only after I've prayed WITH Him, not just TO Him, can I confidently declare: So Be It, In His Name.&nbsp;</div><div style="text-align: justify;"><b><br /></b></div><div style="text-align: justify;"><b>Darrell G. Wolfe</b></div>