---
title: 'Harpoon Faith! Be bold to lay hold!'
date: '2012-03-05T06:24:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2871797528085790056'
blogger_filename: '/2012/03/harpoon-faith-be-bold-to-lay-hold.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'EMIC'
---

EMIC Second Service 11AM.<br />03/04/2012<br />Continuing our study on the Word of God for 2012! <a href="http://www.emic.org/2012.php" target="_blank">What about 2012?</a><br /><br />The people of God had just seen God break down&nbsp;Egypt&nbsp;through miracles, part the red sea, rain heavenly bread, bring an abundance of quail supernaturally, bring water out of a rock... etc, etc... Yet here they are doubting God's will at every turn.<br /><br />Moses sends the spies out to survey the land and this is what 10 of the 12 said:<br /><br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/kjv/numbers/passage.aspx?q=numbers+13:23-33" target="_blank">Numbers 13:23-33</a>27 And they told him, and said , We came unto the land whither thou sentest us, and <b>surely it floweth with milk and honey; and this is the fruit of it.</b>28 <b>Nevertheless (but)&nbsp;</b>the people be strong that dwell in the land, and the cities are walled , and very great: and moreover we saw the children of Anak there. ...<br />32 And they brought up an evil report of the land which they had searched unto the children of Israel, saying , The land, through which we have gone to search it, is a land that eateth up the inhabitants thereof; and all the people that we saw in it are men of a great stature. 33 And there we saw the giants, the sons of Anak, which come of the giants: <b>and we were in our own sight as grasshoppers, and so we were in their sight. </b></blockquote>Notice, it's not that they actually were&nbsp;grasshoppers, because we know that in just 40 short years the inhabitants of Jericho were locked up tight in the city out of fear of these&nbsp;Israelites. (<a href="http://www.biblestudytools.com/nkjv/joshua/passage.aspx?q=joshua+2:9-13" target="_blank">Joshua 2:9-13</a>). It's because they had an inner image of themselves as incapable that they were unable and unwilling to take the land.<br /><br />Not only that, but this fear drove them to direct disobedience to God's word to "GO!" Later we read that God said "ENOUGH! You are going to stay our here and die!" Then they went out to fight when he told them to stay because of the fear of loosing out on the promise. Had they repented of their unbelief and fear and asked for forgiveness God would have atoned their sin (which was provided for by the sacrifices) and led them in. But they stayed in disobedience and then went in disobedience.<br /><br />You just can't go any place and any time you feel like it. You go as you are LED. Now, lest we get all high and mighty and say "Those crazy people, why didn't they just listen?"; We've done the same things countless times in our lives too. We hear God say something, we disobey, confuse ourselves and then try to go and do it after the time has passed.<br /><br />I can say, in many ways, that this has been me the last few years. I say all the right things, around people, but don't see much in the way of results. Inside I'm dwelling in doubt and unbelief. But I've made a&nbsp;quality&nbsp;decision that it is going to change. It started last year when I started meeting with a man of God who get help me get outside of my head and see the God sized picture. It's been a slow process with lots of&nbsp;back steps&nbsp;and moving forward again... But forward I am moving. 2012 is MY YEAR! It's a year of great wealth and great opportunities. That is what the man of God, my prophet, Kenneth Copeland, said on 12/31/2011. Yes Lord! You said it, that settles it!<br /><br />Today at Church <a href="http://emic.org/staff_bio.php?id=24" target="_blank">Pastor George Pearsons</a> said:<br /><br /><br /><blockquote class="tr_bq"><span style="background-color: white; color: #333333; font-family: 'lucida grande', tahoma, verdana, arial, sans-serif; font-size: 13px; line-height: 18px; text-align: left;">Time, will either be spent wearing you down through worry, or building you up through TheWord!!</span><span style="background-color: white; color: #333333; font-family: 'lucida grande', tahoma, verdana, arial, sans-serif; font-size: 13px; line-height: 18px; text-align: left;">@<a href="http://emic.org/" target="_blank">EMIC</a></span></blockquote><br />So we then take a look at the word in Matthew:<br /><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=matthew+11:12&amp;t=kjv" target="_blank"><br class="Apple-interchange-newline" /></a><br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=matthew+11:12&amp;t=kjv" target="_blank">Matthew 11:12</a>And from the days of John the Baptist until now the kingdom of heaven suffereth violence , and the violent<a href="http://www.biblestudytools.com/lexicons/greek/kjv/harpazo.html" target="_blank"><b>&nbsp;take it by force</b></a>&nbsp;.</blockquote><br />"Take it by force" is the word <a href="http://www.biblestudytools.com/lexicons/greek/kjv/harpazo.html" target="_blank">Harpazo</a>. It is the word we use to get the word "Harpoon". It's an&nbsp;aggressive&nbsp;seizing.<br /><br /><br /><table style="-webkit-border-horizontal-spacing: 0px; -webkit-border-vertical-spacing: 0px; background-color: white; border-collapse: collapse; color: #333333; font-family: arial; font-size: 14px;"><tbody><tr style="height: 20px;"><td colspan="2" style="margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/lexicons/greek/kjv/harpazo.html" style="font-family: 'Times New Roman'; font-size: medium;" target="_blank">Harpazo</a>:<b>Definition</b></blockquote></td></tr><tr style="height: 20px;"><td colspan="2" style="margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><blockquote><ol style="margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;" type="1"><li style="list-style-image: initial; list-style-position: initial; list-style-type: none; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">to seize, carry off by force</li></ol><ol style="margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;" type="1"><li style="list-style-image: initial; list-style-position: initial; list-style-type: none; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">to seize on, claim for one's self eagerly</li></ol><ol style="margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;" type="1"><li style="list-style-image: initial; list-style-position: initial; list-style-type: none; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">to snatch out or away</li></ol></blockquote></td></tr></tbody></table><br />This is not a light word. It's not like someone gives you something and you&nbsp;politely accept the gift and nicely unwrap the paper... No this is a taking by force. God has given you something and the devil is trying to steal it from you. You have to go into enemy territory and take it by force. This is a&nbsp;commando&nbsp;raid, a spiritual swat team, a Heavenly Navy Seal Team...<br /><br />So take the Word of God, and Harpoon your BLESSING into your life!<br /><br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/kjv/joshua/14.html" target="_blank">Joshua 14</a>10 And now, <b>behold</b>, the Lord has kept me alive, as He said, these<b> forty-five years</b>, ever since the Lord spoke this word to Moses while Israel wandered in the wilderness; and<b> now, here I am</b> this day, eighty-five years old. 11 <b>As yet I am as strong this day as on the day that Moses sent me</b>; just as my strength was then, so now is my strength for war, both for going out and for coming in. 12<b><u> Now therefore, give me this mountain </u></b></blockquote><br />Here is a man, Caleb, that has been waiting for 40 years to possess his promise. He could have spent the last 40 years developing in bitterness against the people that caused his delay, or second guessing his original faith to move in and possess. He could have faded out for any number of reasons and in any number of directions. BUT, he didn't. Caleb meditated on that Word from God that it was HIS LAND so much that it supernaturally strengthened and elongated his life. Caleb was as strong, if not stronger, at 85 years old as he was at 45 years old. He was even more ready to take the land of promise after 40 years of meditating on that promise.<br /><br />Yet, a few years of self caused delay and we are given up to hopeless statements of bygone days and and things that didn't happen. We are so wrapped up in thinking about the giants in the land that we never see that we have overcome those giants before we took our first step toward them, due to our God's burden removing, yoke destroying <a href="http://n2gs.blogspot.com/2012/02/anointing-study.html" target="_blank">Anointing</a>!<br /><br />Time, should never slow me down or cause me to want to quit. Time is ALWAYS on ME side because the greater One who is in me is outside of time and space. The Word as a seed is planted, my harvest is coming. All I need it time for a breakthrough. Time is not against me, it is for me. Glory To God!<br /><br />Darrell G. Wolfe