---
title: 'Interview Skills- An Introduction'
date: '2012-01-21T09:55:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3570081961979392051'
blogger_filename: '/2012/01/interview-skills-introduction.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'Career'
---

<br /><h1 style="background-color: white; border-bottom-color: rgb(204, 204, 204); border-bottom-style: dotted; border-bottom-width: 1px; color: #333333; font-family: Arial, Tahoma, Verdana; font-size: 20px; font-weight: normal; line-height: 20px; margin-bottom: 10px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 5px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;">Interview Skills- An&nbsp;Introduction</h1><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Interviewing is one of the most important skills one can have in the workplace. You cannot move in or up without passing the interview. Yet as important as it is, few people ever take the time to study material on the skills needed to master that process. They go in to an interview, answer the questions as best as they can and hope for the best. However, there IS a process. There is a technique to interviewing. It’s just as important as your resume’, skills, experience, and accomplishments.</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">A good point to make also is this:</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Even being your very best or THE very best doesn’t mean you will get the position though.&nbsp; You may be the very best salesman in the company and that may come out swimmingly in the interview. But the fact is the person is not JUST looking for someone who is great at their job. They will also be looking for someone who will make a good “Fit” for that particular position. For Example, if the position is a supervisor working directly under a manager:</div><ul style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">A manager who is one of the top performers in a company and has been since he was an entry level employee may not be all that interested that his second in command having sales skills above average. He’s already got that nailed. But maybe he&nbsp;<strong>would&nbsp;</strong>be interested in someone with the skill to help him keep the team on task, and do paperwork, and understand procedures.</li><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">A manager who is friendly and outgoing but doesn’t know computers may need someone who has skills with Excel.</li><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">A manager who is good with data bases and numbers may need someone who can rally the troops and lift moral.</li><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">A manager who knows “Business” but may not know the specifics of this job because that manager was hired from outside may need someone who knows the nuts and bolts.</li></ul><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">There are several categories of skills required to obtain a good interview, some of the more important ones that we will explore are:</div><ul style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Concrete and Specific&nbsp;Answers:</li></ul><ul style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Knowing the Position:</li><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Know Yourself:</li><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Being Prepared:</li></ul><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Great Resources for understanding the important aspects of the interview are:</div><ul style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><a href="http://www.adlerconcepts.com/resources/2001/06/the_best_interview_question_of.php" style="color: #008dcf; text-decoration: none;" target="_blank" title="The Adler Group">Adler Concepts</a>, by The Adler Group</li><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><a href="http://www.worksmart.ca.gov/tips_interview.html" style="color: #008dcf; text-decoration: none;" target="_blank" title="Employment Developement Department">Work Smart</a>, EDD State of C<a href="http://jobsearch.about.com/cs/interviews/a/aceinterview.htm" style="color: #008dcf; text-decoration: none;" target="_blank" title="Acing the Interview">A</a></li><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><a href="http://jobsearch.about.com/cs/interviews/a/aceinterview.htm" style="color: #008dcf; text-decoration: none;" target="_blank" title="Acing the Interview">About.com</a></li><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><a href="http://www.bls.gov/oco/oco20045.htm" style="color: #008dcf; text-decoration: none;" target="_blank" title="US Department of Labor">Occupational Handbook</a>, US Department of Labor</li></ul>