---
title: 'A Nation on the Brink of Civil War... Or Revival... Or both?'
date: '2012-11-22T06:13:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1480137158188434686'
blogger_filename: '/2012/11/a-nation-on-brink-of-civil-war-or.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'News and Current Events'
---

<h3 style="text-align: center;"><b>A Nation on the Brink of Civil War... Or Revival... Or both?</b></h3>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; This is the most amazing article I've read regarding the state of the United States of America. It summarizes where we've been and what lies before us. We have some lessons we can learn. I suggest you reading this.<br /><blockquote class="tr_bq"><i>It’s a difficult Thanksgiving season. The nation is deeply divided, facing serious threats abroad and an uncertain economy at home. An unpopular war drags on, and the controversial incumbent president, after a bitter and divisive campaign, has just won re-election with barely 50 percent of the popular vote.<br />Welcome to November 1812. The war against the British is going badly. President James Madison, after winning a landslide victory in 1808, almost lost this time around. The citizens of a worried nation, in between the name-calling and rancor, nervously ask one another what exactly there is to be thankful for. Is it possible that the solutions of their fraught age could hold lessons for ours? ...<a href="http://www.bloomberg.com/news/2012-11-20/a-thanksgiving-message-for-obama-s-america.html" target="_blank">Continue Reading</a></i></blockquote>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; We must find a way to heal the land. But how? The ideals the two sides fight for could not be more opposite. But are there just two sides? Which two sides? Both Republicans and Democrats are full of Satan's forces, and peppered with God's. The real issues differ depending on which person you talk to. Both sides are filled with Christians who have sold them selves to a party that doesn't truly serve their best interest.<br /><br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; God's platform is not Republican or Democrat. It's not really even "Conservative" or "Liberal". It's God's! When Christians can sit down and talk to each other about the things God wants to see happen for the nation. THIS nation is his launching pad for ministry and ministries to the world. THIS nation will be the source and and funding for the spreading of the message of THE BLESSING and the Word of God around the world.<br /><br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; The Bible has rules about treating people fair, fair business practices, but it also limits government, and authorities. So here's a thought. What if all the real Christians got together to talk... we could either control both parties... or form our OWN coalition government... now that would be an idea!<br /><br />Darrell G. Wolfe<br /><br /><br /><br /><b>Have questions about anything I said here? Disagree? Have an update? Want to share your story? Comment Below!</b><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>Darrell G. Wolfe</b><br /><a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a><br /><a href="https://www.facebook.com/n2goodsuccess?sk=wall">https://www.facebook.com/n2goodsuccess</a><br /><br /><b style="background-color: white;">See Also:</b><br />Book Suggestion from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br /><br /><b>Bulldog Publications:&nbsp;</b><br /><b><a href="http://www.amazon.com/dp/1453815619/ref=as_li_ss_til?tag=your0f4d-20&amp;camp=213381&amp;creative=390973&amp;linkCode=as4&amp;creativeASIN=1453815619&amp;adid=1NAWEWPYWDQA3XGCY7N5&amp;&amp;ref-refURL=http%3A%2F%2Fn2gs.blogspot.com%2F" target="_blank">Bankings Basics for Believers; Now Available on Amazon.&nbsp;</a></b><br />Print&nbsp;Edition<br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=1453815619" style="height: 240px; width: 120px;"></iframe><br /><br />Kindle Edition<br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=B008EO488Y" style="height: 240px; width: 120px;"></iframe><br /><br /><br /><br /><br />