---
title: 'PRAY for Leaders'
date: '2012-10-02T04:12:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3027883454939301477'
blogger_filename: '/2012/10/pray-for-leaders.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Word of The Lord'
  - 'Season Changing'
---

<br /><div><h2>PRAY for Leaders</h2><br />Praying for our leaders, ALL our leaders. There is a temptation living inside each of us to assume we're right and MAKE others listen to us. When a leader does something we disagree with, we want to scream about it. This is MORE true for many Christians. We are, uniquely, aware of Righteousness and God's Standards. When an evil King/Leader does what is evil, we abhor it, and we reject it. However... is it possible that there is a right way and a wrong way to reject a leader and his/her decisions? We can never tolerate evil, especially in our leaders. In the USA we are given a&nbsp;privileged&nbsp;that few others enjoy, we can choose our leaders and even eject them if need be. But there must still be a right way, a right attitude and heart with which this must be done.<br /><br /><a href="http://www.biblestudytools.com/nkjv/proverbs/25.html" target="_blank">Proverbs 25 (New King James Version)</a><br /><br /><blockquote class="tr_bq"><i>2 It is the glory of God to conceal a matter, But the glory of kings is to search out a matter. 3 As the heavens for height and the earth for depth, So the heart of kings is unsearchable. 4 Take away the dross from silver, And it will go to the silversmith for jewelry. 5 Take away the wicked from before the king, And his throne will be established in righteousness. 6 Do not exalt yourself in the presence of the king, And do not stand in the place of the great; 7 For it is better that he say to you, "Come up here," Than that you should be put lower in the presence of the prince, Whom your eyes have seen.</i></blockquote><br /><br />God is showing us here that it is HE who appoints leaders and HE who uses them for HIS purposes. The sooner we get that in our mind the sooner we can get on board with His plan. Does God choice for leader always get elected? No. God will not override the will of the people. However it is God who gifts men for their office and God will use any man in an office by the very nature of his office. What do I mean by that?<br /><br />Consider if you will a thought. Satan has no creative power. He is powerless and has been since the&nbsp;beginning&nbsp; The BEST Satan can do is to use his words to twist the minds of men. Satan has no authority to make anything happen. He must convince people to do as He says through lies, fear, and threats. Satan, therefore, cannot "Anoint" a leader. Satan cannot give power or ability to someone to lead that he doesn't already have. This means that anyone who leads does so because he has been gifted by GOD for that office. Satan can only twist that man or woman not empower them. Just as King Saul turned from God's anointing to become evil, and Saul of Tarsus turned from his deception to become God's anointed, leaders possess the gifts from day one. How they use them is up to them and God's leading.<br /><br />Therefore, even an evil man must be subject to God's direction, and at times intervention. Why is this important. God will do two things to an evil leader. First, in compassion, God will reach out to him, and plead with him through Mercy. If he turns God will use that man for his purposes. If he does not turn, God will still use him for a time, and then reject him and replace him with another.<br /><br />This brings me great hope in these uncertain times. It means that no matter how dire or evil the situation looks, those who belong to God can pray, turn to God, and He WILL intervene. It's not a matter of IF. God WILL change things for His people. He may choose his own way of doing it, it may not be what the people think it will be. They may call for Him to replace and he leads the leader to repent instead. They may call for Him to lead the leader to repent and God replaces him. How God brings about Change is HIS business. But we are to pray for the change, stand boldly on His Word for that change, and believe God will do as He says he will.<br /><br /><a href="http://www.biblestudytools.com/nkjv/daniel/2-21.html" target="_blank">Daniel 2:21 (New King James Version)</a><br /><blockquote class="tr_bq"><i>And He changes the times and the seasons; He removes kings and raises up kings; He gives wisdom to the wise And knowledge to those who have understanding.</i></blockquote><a href="http://www.biblestudytools.com/nkjv/romans/13-1.html" target="_blank">Romans 13:1 (New King James Version)</a><br /><blockquote class="tr_bq"><i>Let every soul be subject to the governing authorities. For there is no authority except from God, and the authorities that exist are appointed by God.</i></blockquote><br />Our job here is to pray. Pray for God's will to be made known, and then stand on that knowledge, believing God will bring it to pass.<br /><br />Darrell G. Wolfe<br /><br /><br /><br /><b>I call you empowered 2 prosper with good success!</b><br /><a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br /><a href="https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118" target="_blank">Facebook.Com/EmpoweredTooProsper</a><br /><span style="background-color: white; font-family: 'Times New Roman', Times, FreeSerif, serif; font-size: 15px; line-height: 20px;"><b><br /></b></span><span style="background-color: white; font-family: 'Times New Roman', Times, FreeSerif, serif; font-size: 15px; line-height: 20px;"><b>For other sites by Wolfe Family Conceptions:&nbsp;</b></span><br /><ul><li><a href="http://wfconceptions.wordpress.com/" target="_blank">http://wfconceptions.wordpress.com/</a></li></ul><br /><b style="background-color: white;">Darrell G. Wolfe</b><br /><br /><b style="background-color: white;">See Also N2 Good Success:</b><br /><br /><br /><ul><li><a href="http://n2gs.blogspot.com/" style="background-color: white;">http://n2gs.blogspot.com/</a></li><li><a href="https://www.facebook.com/n2goodsuccess?sk=wall" style="background-color: white;">https://www.facebook.com/n2goodsuccess</a></li><li><span style="background-color: white;">Book Suggestion from the&nbsp;</span><a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" style="background-color: white;" target="_blank">N2 Good Success Amazon Store</a></li><li><span style="background-color: white;">Product Offerings from&nbsp;</span><a href="http://www.zazzle.com/n2goodsuccess" style="background-color: white;" target="_blank">N2 Good Success Zazzle Store</a></li></ul><br /><br /><b>Bulldog Publications:&nbsp;</b><br /><b><a href="http://www.amazon.com/dp/1453815619/ref=as_li_ss_til?tag=your0f4d-20&amp;camp=213381&amp;creative=390973&amp;linkCode=as4&amp;creativeASIN=1453815619&amp;adid=1NAWEWPYWDQA3XGCY7N5&amp;&amp;ref-refURL=http%3A%2F%2Fn2gs.blogspot.com%2F" target="_blank">Bankings Basics for Believers; Now Available on Amazon.&nbsp;</a></b><br /><b>Print&nbsp;Edition</b><br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=1453815619" style="height: 240px; width: 120px;"></iframe><br /><br /><b>Kindle Edition</b><br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=B008EO488Y" style="height: 240px; width: 120px;"></iframe><br /><br /><br /><br /><br /><br /><br class="Apple-interchange-newline" /><iframe allowtransparency="true" frameborder="0" scrolling="no" src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fn2goodsuccess&amp;width=292&amp;height=62&amp;colorscheme=light&amp;show_faces=false&amp;border_color&amp;stream=false&amp;header=true&amp;appId=272647732784155" style="background-color: white; border-style: none; height: 62px; overflow: hidden; width: 292px;"></iframe><br /></div>