---
title: 'Seed is all you need!'
date: '2012-02-19T08:43:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7105813839208711505'
blogger_filename: '/2012/02/seed-is-all-you-need.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
---

<br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/nkjv/genesis/1-1.html" target="_blank"><i>Genesis 1:1 NKJV</i></a><i>In the beginning God created the heavens and the earth.</i><i><br /></i><i><a href="http://www.biblestudytools.com/nkjv/genesis/1-2.html" target="_blank">Genesis 1:2 NKJV</a>The earth was without form, and void; and darkness was on the face of the deep. And the Spirit of God was hovering over the face of the waters.</i></blockquote><br /><blockquote class="tr_bq"><b>Genesis 1</b><br />11 Then God said, "Let the earth bring forth grass, the herb that yields seed, and the fruit tree that yields fruit according to its kind, whose seed is in itself, on the earth"; and it was so. 12 <b>And the earth brought forth grass, the herb that yields seed according to its kind, and the tree that yields fruit, whose seed is in itself according to its kind</b>. And God saw that it was good. 13 So the evening and the morning were the third day.<br /><b>Genesis 2:8</b><br />8 <b>The Lord God planted a garden eastward in Eden, and there He put the man whom He had formed. 9 And out of the ground the Lord God made every tree grow that is pleasant to the sight and good for food. </b>The tree of life was also in the midst of the garden, and the tree of the knowledge of good and evil. </blockquote><br /><blockquote class="tr_bq"><b>Contradiction? Wait, did trees get created before or after man was created?</b></blockquote><blockquote class="tr_bq"><b>REMEMBER SEED:&nbsp;</b></blockquote><ol><ol><li>If anything about Gen 2:8 confuses you, lest you think that somehow that contradicts what Gen 1 said consider this:</li><ol><li>God ALWAYS works through seed. ALL that is needed for the apple tree is in the seed. The whole Kingdom of God is as a man who casts seed into the ground! (Gen 1:28, Mark 4:26)</li><li>So if God says to you "here is an apple tree". Then takes you to an empty dirt lot and hands you a seed. He gave you an apple tree. Plant it! As far as God is concerned an Apple Tree is an Apple Tree whether it's a seed or fully grown, it's the same thing to God.&nbsp;</li><li>So when God hands you His Word and says "You are Rich!", as far as He's concerned it's done. He gave you the seed, plant it! Grow! Be Rich!&nbsp;</li></ol></ol></ol>Praise GOD! He gave you His Word, His Word is His Seed, Go get it! If God said, I believe it, and that settles it! I have what the BIBLE says I have!<br /><br />Darrell G. Wolfe