---
title: 'Do You Know Jesus?'
date: '2012-06-02T05:01:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4705596014223177260'
blogger_filename: '/2012/06/do-you-know-jesus_1.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<h3 style="text-align: center;">Do You Know Jesus?</h3><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;"><br />Do you know Jesus? Really know him? Have you been saved but "Back Slidden". Have you never really heard of Jesus or what He came to do? Maybe you've been turned off to Christianity because of the poor, or even hypocritical, treatment of Christians!&nbsp;Maybe you've had experience in the occult, demons, witch craft, UFO&nbsp;societies, etc... Maybe you played with demonic toys "Just for fun" and now your house his causing you issues because of it. Maybe you have&nbsp;committed&nbsp;crimes that you feel are too evil to be forgiven of.<br /><br /></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;"><b>I have GOOD NEWS for you!!!!!</b><br /><b><br /></b></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">That is what "Gospel" means: Good News!<br /><br /></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Jesus is the King of Kings! He is the Lord of Lords! He created ALL things, including those angels that fell into deception! His body was broken and His blood shed for your&nbsp;deliverance!<br /><br /></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Don't feel that you can't be forgiven. There is nobody, not even&nbsp;Hitler&nbsp;himself, that can't receive the free gift of Salvation if they will just ask God for it. It is a free gift. You can't earn it. All have sinned so no body can! Therefore because all have sinned all can receive it! There is no difference between one human and another when it comes go Jesus. All sinned All get the free gift of&nbsp;salvation! Jesus did not come to condemn you! He came that you might have life and have it more&nbsp;abundantly!<br /><br /></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">If you want to see this for yourself see:</div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;"><a data-mce-href="http://www.biblestudytools.com/nkjv/john/passage.aspx?q=john+3:11-21" href="http://www.biblestudytools.com/nkjv/john/passage.aspx?q=john+3:11-21" target="_blank">John 3:11-21</a>,&nbsp;<a data-mce-href="http://www.biblestudytools.com/nkjv/romans/passage.aspx?q=romans+3:18-28" href="http://www.biblestudytools.com/nkjv/romans/passage.aspx?q=romans+3:18-28" target="_blank">Romans&nbsp;3:18-28</a>,&nbsp;<a data-mce-href="http://www.biblestudytools.com/nkjv/1-corinthians/2-12.html" href="http://www.biblestudytools.com/nkjv/1-corinthians/2-12.html" target="_blank">1 Corinthians 2:12</a>.<br /><br /></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Jesus came preaching the Gospel of the Kingdom of God. That means: "Hey people! The Kingdom of God has come and that's Good News! Why?<br /><br /></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Read&nbsp;<a data-mce-href="http://www.biblestudytools.com/nkjv/deuteronomy/passage.aspx?q=deuteronomy+28:1-14" href="http://www.biblestudytools.com/nkjv/deuteronomy/passage.aspx?q=deuteronomy+28:1-14" target="_blank">Deuteronomy 28: 1-14</a>&nbsp;because all of that blessing now belongs to you according to&nbsp;<a data-mce-href="http://www.biblestudytools.com/nkjv/galatians/3-14.html" href="http://www.biblestudytools.com/nkjv/galatians/3-14.html" target="_blank">Galatians&nbsp;3:14</a>!!! The good news is that God has blessed you despite you! You can't earn it or deserve it! But you can receive it. It starts by getting your heart right.<br /><br /></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;"><b>Pray this prayer:</b></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;"><b>"Father in heaven, you are Holy! You sent you only Son to earth to die for me that I could live for you! Thank you for that gift! I receive it! I take! It's mine! I believe! I say right now that devils have no more place or authority in my life! I invite you into my heart, my house, my life, and all I am and have! Satan I command you to leave because I submitted to God! (<a data-mce-href="http://www.biblestudytools.com/nkjv/james/4-7.html" href="http://www.biblestudytools.com/nkjv/james/4-7.html" target="_blank">James 4:7</a>)"</b><br /><b><br /></b></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Now if you prayed that prayer, and you want demons to leave you alone; start to praise God. Song is among the most powerful ways to renew your mind and heart to God's word and set yourself in a peaceful place in Him! If you don't know any spiritual - scriptural songs I'll get you started here below.<br /><br /></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">If you prayed this prayer I invite you to visit this link from Jesse Duplantis to hear more about salvation:&nbsp;<a data-mce-href="http://www.jdm.org/jdmDefault.aspx?tabindex=-1&amp;tabID=50" href="http://www.jdm.org/jdmDefault.aspx?tabindex=-1&amp;tabID=50">http://www.jdm.org/jdmDefault.aspx?tabindex=-1&amp;tabID=50</a><br /><br /></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Then also explore some awesome articles from Kenneth Copeland on getting started with your walk with God here:&nbsp;<a data-mce-href="http://www.kcm.org/real-help/salvation" href="http://www.kcm.org/real-help/salvation">http://www.kcm.org/real-help/salvation</a><br /><br /></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">My favorite place to get new and old music to sing to God is at&nbsp;<a data-mce-href="http://www.pandora.com/#" href="http://www.pandora.com/#">http://www.pandora.com/</a>&nbsp;Just sign up and type in "Praise and Worship" in the search for new music box. Free Praise and Worship streaming 24/7!<br /><br />Find a good Church near you:&nbsp;<a href="http://wordchurchfinder.blogspot.com/">http://wordchurchfinder.blogspot.com/</a><br /><br /></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Let me get you started. Click Play below and wash your spirit and soul in the blood of Jesus!</div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;"><br /></div><iframe allowfullscreen="" frameborder="0" height="315" src="http://www.youtube.com/embed/23n30v08v94" width="420"></iframe><br /><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;"><br /></div><div style="font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-size: 13px; line-height: 19px;">Thank you for reading... Darrell G. Wolfe<br /><br /><div style="font-family: 'Times New Roman'; font-size: medium; line-height: normal;"><b>I call you empowered 2 prosper with good success!</b></div><div style="font-family: 'Times New Roman'; font-size: medium; line-height: normal;"><b><br /></b></div><div style="font-family: 'Times New Roman'; font-size: medium; line-height: normal;"><b>Darrell G. Wolfe</b></div><div style="font-family: 'Times New Roman'; font-size: medium; line-height: normal;"><a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a></div><div style="font-family: 'Times New Roman'; font-size: medium; line-height: normal;"><a href="https://www.facebook.com/n2goodsuccess?sk=wall">https://www.facebook.com/n2goodsuccess</a></div></div>