---
title: 'Can you miss your calling in life?'
date: '2012-02-22T21:57:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6365463800359790396'
blogger_filename: '/2012/02/can-you-miss-your-calling-in-life_22.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<div style="text-align: center;"><b>Question:</b>&nbsp;</div><div style="text-align: center;"><br /></div><div style="text-align: center;">"Can you be called and never&nbsp;fulfill&nbsp;your calling?"</div><div style="text-align: center;">Doesn't God work with you, constantly re directing you back to His calling?</div><br /><div style="text-align: center;"><b>Answer:&nbsp;</b></div><br /><div style="text-align: center;">"Have you ever known anyone that died without fulfilling&nbsp;their&nbsp;calling?"&nbsp;</div><br />Yes, we all have. Every human on the planet has a call of God on their life, not just a few select people. Every human on the planet is called to something, but we must cooperate with God to see that calling come to pass.<br /><br />The following is my answer to that question in more detail:<br /><span style="font-family: Calibri, sans-serif;"><br /></span><br />This is a great question&nbsp;<span style="font-family: Calibri, sans-serif;">and it deserves a great response. It is true that God works with the person and leads them. It is also true that in His Grace He’ll lead them as long as it takes. However it is still always the responsibility of the person to obey. God will lead, but never force.</span><br /><br /><div align="center" class="MsoNormal" style="text-align: center;"><br /></div><div align="center" class="MsoNormal" style="text-align: center;"><span style="font-family: Calibri, sans-serif;">Luke 6:47-48<o:p></o:p></span></div><div align="center" class="MsoNormal" style="text-align: center;"><span style="font-family: Calibri, sans-serif;">“Whoever <b><u>comes</u></b>to me, <b><u>hears</u></b> my word and <b><u>DOES</u></b> them… “ will build his life’s foundation on a rock.<o:p></o:p></span></div><div align="center" class="MsoNormal" style="text-align: center;"><br /></div><div align="center" class="MsoNormal" style="text-align: center;"><span style="font-family: Calibri, sans-serif;">James 1:22<o:p></o:p></span></div><div align="center" class="MsoNormal" style="text-align: center;"><span style="font-family: Calibri, sans-serif;">“But be doers of the Word, and not hearers only, deceiving yourselves.”<o:p></o:p></span></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><span style="font-family: Calibri, sans-serif;">So we see that if you hear and don’t do you end up self deceived. Thinking the whole time “Why am I not receiving what God said?” <o:p></o:p></span></div><div align="center" class="MsoNormal" style="text-align: center;"><br /></div><div align="center" class="MsoNormal" style="text-align: center;"><span style="font-family: Calibri, sans-serif;">Hebrews 13:17<o:p></o:p></span></div><div align="center" class="MsoNormal" style="text-align: center;"><span style="font-family: Calibri, sans-serif;">“Obey those who rule over you, and be submissive, for they watch out for your souls…”<o:p></o:p></span></div><div align="center" class="MsoNormal" style="text-align: center;"><br /></div><div align="center" class="MsoNormal" style="text-align: center;"><span style="font-family: Calibri, sans-serif;">Ephesians 6:13-18<o:p></o:p></span></div><div align="center" class="MsoNormal" style="text-align: center;"><span style="font-family: Calibri, sans-serif;">“Take up the armor of God and stand against the wiles of the devil…”<o:p></o:p></span></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><span style="font-family: Calibri, sans-serif;">The Word wouldn’t tell us to stand in armor if there wasn’t a fight to be had. <o:p></o:p></span></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><span style="font-family: Calibri, sans-serif;">Of course God has given you Grace so that you could have everything you need for life and godliness (2 Peter 1:2-3) So that you would have Grace to have ALL THINGS at ALL TIMES(2 Cor 9:6-12), He has given you the gifts you need to succeed (1 Cor 12, Ephesians 4:11-13) So God is always doing exceedingly and abundantly above and beyond all we ask or think (Ephesians 3:20) So yes, He is always working with us… his mercies are new every morning (Lamentations 3:22-23) But we still have a role to play to see it come to pass. Idle hands lead to poverty (Proverbs 19:15)<o:p></o:p></span></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><span style="font-family: Calibri, sans-serif;">For a wild example, it was God’s will for Michael Jackson to live long and fulfill his calling in this earth, it was a calling of his to Glorify God in his craft. He was called to write music for Church and for Secular society that would radically change and inspire people to magnify God. He knew it. He was actually working toward that. “This is it” was to be his last secular album and he was going to start creating worship and praise music and possibly start a new genre that didn’t even fit into those categories because it hadn’t been invented yet.&nbsp; He had many things that hindered him, many excuses for why he was the way he was, many demons that he invited into his life that he needed to remove, and he died young, not because God wasn’t leading I know some of the people who talked to him about His call. In the end He refused to listen to God’s leading, sowed seed that caught up to him, and died young. <o:p></o:p></span></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><span style="font-family: Calibri, sans-serif;">On 9/11 God was speaking to EVERY PERSON to keep them out of harm’s way. Some heard directly, some heard as an impression. Some obeyed and some didn’t. Some didn’t know it was God but just felt a need to stay home. One lady was headed back into the building, after the first hit they said it was all fine to go back in, and she heard God say “RUN GET OUT!” She called to everyone and said to get out and tried to convince everyone to follow her. Some did, and some did not. Those that followed her survived. Moments after the second plane hit the building. Everyone in that lobby had the change to live, not everyone obeyed. More people called in sick that day than in the history of the World Trade Center. 60,000-80,000 people could have died that day, and we only lost about 3,500, if memory serves. <o:p></o:p></span></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><span style="font-family: Calibri, sans-serif;">Among the most famous biblical examples: Saul</span><br /><span style="font-family: Calibri, sans-serif;"><br /></span><br /><span style="font-family: Calibri, sans-serif;">Saul, the first King of Israel, was given instructions and he did the opposite. Even though God worked a mighty plan to make him king, he died out of the will of God. It is completely possible to not complete your calling. Obedience to His call is required. There is case after case where this is exampled throughout the Word. <o:p></o:p></span></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><span style="font-family: Calibri, sans-serif;">There is this strange balance between God’s hand of protection and our obeying His word. If God tells me NOT to go to work via a certain route, I feel strongly about it in my gut, but I go anyway because I’m late to work and it’s the fastest way, then I get in an accident. That is ME not God. He tried to tell me. I didn’t listen. We have a responsibility to heed his Word written and spoken. <o:p></o:p></span></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><span style="font-family: Calibri, sans-serif;">So unfortunately although God’s calling is without <a href="http://bible.cc/romans/11-29.htm" target="_blank">repentance</a>&nbsp;(Romans 11:29), meaning that it’s NEVER too late to start walking in it, it also requires obedience and you can die without having fulfilled your calling, or even die before your time due to disobedience. Many pastors have been warned about over eating by prophetic words and later died from complications due to obesity because they didn’t obey the Words that were given. The Holy Spirit is our helper, but not our doer. God will always do His part, and always require you do your part. But in His Grace, he makes your part VERY easy! LOL.</span></div>