---
title: 'Key to Success- Develop Your Inner Hedgehog'
date: '2012-05-15T07:25:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6738840509996977689'
blogger_filename: '/2012/05/key-to-success-develop-your-inner_15.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Keys To Success'
---

<h3><div style="text-align: center;"><b>Keys to Success</b></div><b><div style="text-align: center;"><b>Develop Your Inner Hedgehog</b></div></b><b><div style="text-align: center;"><b>Your Life Core Message/Theme/Concept</b></div></b></h3><div style="text-align: center;"><b>1 VS 1000</b></div><blockquote class="tr_bq">“I have far more respect for the person with a single idea who gets there than for the person with a thousand ideas who does nothing.” ~ <a href="http://www.thomasedison.com/quotes.html" target="_blank">Thomas Edison</a></blockquote>I was thinking about this. I've been the guy who has the thousand ideas. I must learn to remember my <a href="http://www.jimcollins.com/media_topics/hedgehog-concept.html#audio=85" target="_blank">hedgehog concept</a> (core concept) and stick to it. My life core concept is good success, hence this blog. Everything I do is about good success. Not just success but good success.<br /><br />Developing your hedgehog concept is a life long process. There is always some refining to do, but at you look at your life, what drives you, your personal motive for doing what you do, not just at work, but in general... there is a theme that runs through it all. No matter how diverse your favorite activities are, there is always a theme.<br /><br /><div style="text-align: center;"><b>What is the hedgehog concept?</b></div><br /><a href="http://www.jimcollins.com/" target="_blank">Jim Collins</a> writes about it in a book I suggest you read called: <a href="http://www.amazon.com/Good-Great-Companies-Leap-Others/dp/0066620996/ref=sr_1_1?s=books&amp;ie=UTF8&amp;qid=1337063004&amp;sr=1-1" target="_blank">Good to Great</a>. The following is my synopsis:<br /><blockquote class="tr_bq">There is a slow moving hedgehog. He is not great at many things. He has however developed one skill, and he does so with great efficiency. He has quills that are sharp and he can roll into a ball to protect himself. He can't run fast, jump high, or do any of the amazing things other animals do.<br /><br />Meanwhile, lurking about is a crafty fox. He is smart. He is keen. He is driven. He is quick. He can jump. He is beautiful. He roams about the land. He wants to capture this hedgehog and eat him right up. So he jumps from behind only to be stung in the face. He begins to device ways to get this little hedgehog.<br /><br />Thus, day after day, the crafty fox finds new ways to surprise the hedgehog, and take him off&nbsp;guard. He jumps from the left, right, back, front, loudly,&nbsp;quietly, etc... yet each time the hedgehog responds the same. He rolls into a ball of quills, untouchable.&nbsp;</blockquote>The idea here is that no matter how many things people do to try to upset you, replace you, compete with you, etc... You do what you were created by God to do... and you CAN'T be beat. Find your core theme, and everything becomes clearer.<br /><br /><a href="http://www.jimcollins.com/media_topics/hedgehog-concept.html#audio=80" target="_blank">Walgreen's&nbsp;</a>Drug Stores were passionate about pharmacy. But so were many others companies. Yet&nbsp;Walgreen's&nbsp;felt they could be the best at Convenient Drug Stores. So when a corner lot opened down the street a block away from a very profitable store, there was NO question what to do... move the store to the corner lot. Why? Why mess with a profitable store? Because corner lots became part of their plan to walk out the convenience theme.<br /><br />So when you know what you are and what you are not, you can make clear decisions about things. One Pastor I know was invited to speak at an outdoor crusade. He knows that his calling, outside of his local church, is specifically to&nbsp;develop&nbsp;other pastors. Should I accept an invitation to speak at this event? Hands down the answer was no. He isn't called to out door crusades, he's called to teach pastors. So when an invitation came to work with a crowd of 15 pastors in Thailand came, he was ready to go. He turned down a much larger venue, to stick to his core concept.<br /><br />What things are you doing right now, that are not part of your core concept? Are you involved in things that are taking time away from your true calling? Are you accepting jobs, business ventures, etc, that are not part of your core? You can't be dogmatic about this, you must be led by the Holy Spirit as well in your decisions, pray about each opportunity. Your core concept is your general guide. Taking out the trash doesn't have to be part of your core concept.<br /><br />However, if you are not finding most of your activity feeding your core concept... you may need to prepare yourself for some changes. If you don't know what it is yet, just be faithful at what you are doing and ponder these things below. It may take time for you to develop a knowing and clarity about this important aspect of your inner drive and passion.<br /><br /><div style="text-align: center;"><b>Some ideas/questions to find your core theme:</b></div><br /><ol><li>What do you feel really passionate about?</li><li>What would you do if you didn't have to get paid?</li><li>What are you doing when you've lost all track of time?&nbsp;</li><li>What are you good at, that nobody does quite like you?</li><li>What can you be "Best in the World" at?</li><ol><li>This doesn't mean no body is better, it means that you are exceptional at this and others don't do it the way you do it.</li><li>Many, many, many people write and more write blogs. But they don't say what I say, the way I say it. I have a defined voice... which is being ever more refined through practicing my core concept.&nbsp;</li></ol><li>What do others affirm in you?&nbsp;</li><li>What do others say you are good at?</li><li>What do people come to you for?</li><ol><li>Laughter</li><li>Counsel</li><li>Technical Fixes</li><li>Help with sales,&nbsp;writing, mechanics, etc...</li></ol></ol><b><div style="text-align: center;"><b>Here are some thoughts about others core concepts:</b></div></b><br /><br /><ul><li>&nbsp;Disney - Childlike Magic</li><li>Cheesecake Factory - Best in the world Cheesecake - great food, variety, ambiance.</li><li>The Rock Church, Anaheim, CA - Building Solid Lives through Come, Hear, Do</li><li>Walgreen's&nbsp;-&nbsp;Convenient&nbsp;Drug Stores</li></ul><div>Just to name a few. My core concept is Good Success. Almost everything I do is about good success. When I talk to people on the phone at work, it's about their good success. When I help mentor someone, it's about their good success. If I write a restaurant review it's about having good success by enjoying your success at great places to eat and avoiding the bad ones. It's all about good success. Good Success motivates me.&nbsp;</div><div><br /></div><div>I also know I am a writer. You assign me a 10 page essay and my 1set rough draft is 25 pages. I have to learn to edit down to the point. I know I have a passion for music, theatre, movies, dance... not all of those passions are currently active... but I know that as I pursue, or re-awaken a passion... somewhere weaved into the middle of it, I'll be thinking about good success or helping someone reach their potential with good success.&nbsp;</div><div><br /></div><blockquote class="tr_bq"><b>What are YOUR motivations? What drives you? What is your "WHY" in your "What"? Feel free to comment below.&nbsp;</b></blockquote><br />Darrell G. Wolfe<br /><br />And a big thank you to<a href="http://scottjallen.com/?p=1816&amp;utm_source=feedburner&amp;utm_medium=feed&amp;utm_campaign=Feed%3A+scottjallencom+%28scottjallen.com+-+Worship+%7C+Art+%7C+Media%29" target="_blank"> Scott Allen</a> for posting this great Thomas Edison quote on his blog.<br /><br />Buy Jim Collins Book here:<br /><br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=0066620996" style="height: 240px; width: 120px;"></iframe>