---
title: 'The New English Bible, New Testament, Oxford Press 1961.'
date: '2012-01-16T15:27:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2945123072000926277'
blogger_filename: '/2012/01/the-new-english-bible-new-testament.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Random'
  - 'study'
---

The New English Bible, New Testament, Oxford Press 1961.<br /><br />This is an intriguing translation. There were problems with some of the creative&nbsp;licence&nbsp;they took to word some things so it should be viewed not as a&nbsp;translation, such as the New King James or New American Standard, but rather a paraphrase or assistant to understanding, such as the New Living, New International, or even The Message.<br /><br />If you understand that is is not a perfect word for word rending, but rather a thought for thought rendering, with creative&nbsp;licence&nbsp;for understanding and strong translator biases, it is a very interesting read. I often use it for daily reading for the very reason that it is a creative rendering.<br /><br />It is no longer in print, probably due to the controversies of it's day, taking so much creative licence. Ironically it was probably these very controversies that gave birth decades later to such helpful tools as The Message and The New Living versions.<br /><br />I got my version from a church library book sale. It was&nbsp;buried&nbsp;in the shelves collecting dust. I've had it for years but didn't know what a rare treasure I had until a few years ago when I tried to find one to buy.<br /><br /><b>For more Information on this intriguing version of the bible see:&nbsp;</b><br /><br /><a href="http://en.wikipedia.org/wiki/New_English_Bible">http://en.wikipedia.org/wiki/New_English_Bible</a><br /><br /><a href="http://www.bible-researcher.com/neb.html">http://www.bible-researcher.com/neb.html</a><br /><br /><b>To Purchase:&nbsp;</b><br /><a href="http://www.abebooks.com/New-English-Bible-Testament-Popular-Edition/2670098984/bd">http://www.abebooks.com/New-English-Bible-Testament-Popular-Edition/2670098984/bd</a><br /><br /><a href="http://www.amazon.com/gp/offer-listing/B003ZM6PO0/ref=dp_olp_0?ie=UTF8&amp;redirect=true&amp;condition=all">http://www.amazon.com/gp/offer-listing/B003ZM6PO0/ref=dp_olp_0?ie=UTF8&amp;redirect=true&amp;condition=all</a><br /><br /><b>For More information on bibles and translations:</b><br /><a href="http://life-equals-jesus.org/Church/DST/libBible.html">http://life-equals-jesus.org/Church/DST/libBible.html</a><br /><br /><a href="http://www.bible-researcher.com/links06.html">http://www.bible-researcher.com/links06.html</a><br /><br /><b>For Online Bibles, access to many translations online and other&nbsp;helpful&nbsp;tools like&nbsp;dictionaries&nbsp;and Lexicons and&nbsp;Interlinear&nbsp;versions:&nbsp;</b><br /><br /><a href="http://www.biblestudytools.com/">http://www.biblestudytools.com/</a><br /><br /><a href="http://www.biblegateway.com/">http://www.biblegateway.com/</a><br /><br /><a href="http://www.blueletterbible.org/">http://www.blueletterbible.org/</a><br /><br /><a href="http://biblos.com/">http://biblos.com/</a><br /><br /><b>Downloadable Online:</b><br /><a href="http://www.onlinebible.net/">http://www.onlinebible.net/</a><br /><br /><br /><b>See Also:&nbsp;</b><br /><a href="http://1828.mshaffer.com/">http://1828.mshaffer.com/</a><br /><br /><a href="http://www.1828-dictionary.com/">http://www.1828-dictionary.com/</a><br /><br /><a href="http://www.webster1828.com/">http://www.webster1828.com/</a><br /><br /><a href="http://thesaurus.com/">http://thesaurus.com/</a><br /><br /><br />Darrell G. Wolfe