---
title: 'RADICAL GRACE! Pre-Forgiven!'
date: '2012-01-09T07:55:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6760789101538812772'
blogger_filename: '/2012/01/radical-grace-pre-forgiven.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'KCM'
  - 'Prayer Time'
  - 'Daily Reading'
---

<a href="http://www.josephprince.org/index.asp" target="_blank">Joseph Prince</a> said in this weeks broadcast something that totally made me see the ministry of the Holy Spirit in a new way and showed me how to live freer in the Grace of God:<br /><br /><a href="http://www.biblestudytools.com/nkjv/john/passage.aspx?q=john+16:7-11" target="_blank">John 16:7-11 (New King James Version)</a><br />7 Nevertheless I tell you the truth. It is to your advantage that I go away; for if I do not go away, the Helper will not come to you; but if I depart, I will send Him to you. 8 And when He has come, He will <b>convict </b>the <b>world </b>of <b>sin</b>, and of <b>righteousness</b>, and of <b>judgment</b>: 9 of <b>sin</b>, because <b>they </b>do not believe in Me; 10 of <b>righteousness</b>, because I go to My Father and <b>you </b>see Me no more; 11 of <b>judgment</b>, because the <b>ruler </b>of this world is judged. <br /><br />The Holy Spirit:<br /><br /><ol><li>Convicts the&nbsp;unbeliever&nbsp;of his need for Jesus sacrifice, atonement, and Love gift!</li><li>Convicts the believer of his righteous state in Jesus!&nbsp;</li><li>Convicts the devil of his defeat and doom!</li></ol><div>GLORY TO GOD! The Holy Spirit was not assigned to beat me over the head&nbsp;every time&nbsp;I make a mistake! He was sent to convince me that I have been made the righteousness of God!&nbsp;Every time&nbsp;I start to beat myself it's the Holy Spirit who is there to remind me that I am under GRACE and to embrace that grace!</div><br /><br />This is exactly the&nbsp;opposite&nbsp;of the way most believers, including myself, have been living. We are always so worried that we let God down in someway when we fail to live up to our self proclaimed ideals! The Holy Spirit is here to remind us that Jesus himself ALSO <a href="http://www.biblestudytools.com/nkjv/matthew/passage.aspx?q=matthew+18:16-26" target="_blank">forgives </a>each one of us <a href="http://www.biblestudytools.com/nkjv/matthew/passage.aspx?q=matthew+18:16-26" target="_blank">700 + times a day</a> if need be to keep us in GRACE!<br /><br />Did you know that Jesus died and rose again before the year 1980, 1950, 1900, or even 1800? That means that there is no living man or woman alive today that sinned before Jesus went to the cross. ALL of our sins were future to him. They were forgiven before we were born. So your sin today is no different than your sin in your past or future. It's all been wiped out by the GRACE of God! You can't ever beat yourself up again for falling short in one area or another. It was wiped away before you did (Or didn't) do it! GLORY TO GOD!<br /><br />Now that is RADICAL GRACE! Darrell G. Wolfe