---
title: 'Time is Precious - Build Your House Right'
date: '2012-05-24T17:25:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5747460421704967109'
blogger_filename: '/2012/05/time-is-precious-build-your-house-right_24.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Spiritual Growth'
---

<div style="text-align: center;"><b>Time</b></div><div style="text-align: center;"><br /></div>Time is Money. That's what they say. I say Time is worth FAR more than money. Fortunes have been lost and rebuilt by one person more than once. I say time is worth more. Time is possibly the only commodity that cannot be replaced.<br /><br />Have you ever taken a look back and realized all the time wasted on things that didn't bring you progress, and didn't add value to your life? Life is like building a house. If you don't start with a good foundation, take time to measure and cut, draft out plans, follow through with the right materials, spend time doing it right, make sure not to cut corners or scimp out on details.<br /><br /><div style="text-align: center;"><b>Logs</b></div><br />Take time to enjoy your life. The person in this video not only took the time, 9 months, to build this project right, but he took the extra care to video the experience. This is a lesson we could use. Keeping a diary/blog of your life, even if you keep it for your eyes only, is a great way to keep track of your life. This has many benefits. Pictures, Diaries, Blogs, Etc... they all help us take a look back. What were we thinking back then? What mind sets did we have? Have we grown in an area but didn't recognize it without looking back? Have we let something we learned slip and we need to pick it back up? Keeping a log of life is a great way to ensure you are living it to it's fullest.<br /><br />Logs also help others see life. Kids grow up. Kids don't remember much from growing up. They have a few basic memories, impressions, etc. But the day to day&nbsp;disappears&nbsp;with time. Even parents forget more of the childs growth than they remember. Logs of various kinds are a great way to preserve those memories and lessons for the future. A few videos on you tube wouldn't hurt either.<br /><br /><iframe allowfullscreen="" frameborder="0" height="315" src="http://www.youtube.com/embed/nfNrASSti6g" width="560"></iframe><br /><br /><br /><b>I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>Darrell G. Wolfe</b><br /><a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a><br /><a href="https://www.facebook.com/n2goodsuccess?sk=wall">https://www.facebook.com/n2goodsuccess</a><br /><a href="http://empoweredtooprosper.blogspot.com/">http://empoweredtooprosper.blogspot.com/</a><br /><br /><b>See Also:</b><br />Book Suggestion from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br /><br /><b>Bulldog Publications:&nbsp;</b><br /><b><a href="http://www.amazon.com/dp/1453815619/ref=as_li_ss_til?tag=your0f4d-20&amp;camp=213381&amp;creative=390973&amp;linkCode=as4&amp;creativeASIN=1453815619&amp;adid=1NAWEWPYWDQA3XGCY7N5&amp;&amp;ref-refURL=http%3A%2F%2Fn2gs.blogspot.com%2F" target="_blank">Bankings Basics for Believers; Now Available on Amazon.&nbsp;</a></b><br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=1453815619" style="height: 240px; width: 120px;"></iframe><br /><br class="Apple-interchange-newline" />