---
title: 'If God Wills…'
date: '2012-01-21T10:22:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6392226635459925837'
blogger_filename: '/2012/01/if-god-wills.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'Will of God'
---

<br /><h1 style="background-color: white; border-bottom-color: rgb(204, 204, 204); border-bottom-style: dotted; border-bottom-width: 1px; font-family: Arial, Tahoma, Verdana; font-size: 20px; font-weight: normal; line-height: 20px; margin-bottom: 10px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 5px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;">If God&nbsp;Wills…</h1><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><a href="http://www.biblegateway.com/passage/?search=James+4&amp;version=NKJV" style="text-decoration: none;" target="_blank"><span style="color: black;">James 4</span></a></div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><sup>13</sup>&nbsp;Come now, you who say, “Today or tomorrow we will<sup>[<a href="http://www.biblegateway.com/passage/?search=James+4&amp;version=NKJV#fen-NKJV-30347g" style="text-decoration: none;" title="See footnote g">g</a>]</sup>&nbsp;go to such and such a city, spend a year there, buy and sell, and make a profit”;&nbsp;<sup>14</sup>&nbsp;whereas you do not know what&nbsp;<em>will happen</em>&nbsp;tomorrow. For what&nbsp;<em>is</em>&nbsp;your life? It is even a vapor that appears for a little time and then vanishes away.&nbsp;<strong><sup>15</sup>&nbsp;Instead you&nbsp;<em>ought</em>&nbsp;to say, “If the Lord wills, we shall live and do this or that.”&nbsp;</strong><sup>16</sup>&nbsp;But now you boast in your arrogance. All such boasting is evil.</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Among the most misused and abused scriptures in the bible is James 4:15. People throughout the world of Christianity, especially in this culture of not wanting to be bold or step on anyone’s toes, pray this prayer… “God… we desire you to do…(Fill in your need here)… if it’s your will.” We have taken a look at how seriously God takes His own word. It would appear to a casual observer that this verse in James is instructing us to pray this way. This is not so. This verse of scripture is addressed to Christians who are wrapped in pride and not interested in the will of God. The emphasis is on “I”. “I, without prayer or consideration of the Will of God, will do such and such.”</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">John 7:17 tells us that if anyone wills to do His will (wants to do right by God and wants to do what God wants) he shall know…</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">There are instances, such as travel, where the Word of God is not clear and therefore the Will of God is not clear. For example, unless you had received instruction from God to go to a city, you could not know that you were for certain supposed to be there. Thus Paul in a few instances said that he would come visit if it was the will of God, indicating that God had not given him clear direction as to whether he should go or not.</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">The concept James is bringing to the table is a fundamental one. Find out what the Will of God is, confer no longer with men or women, and do what it takes to accomplish that at any cost. Before praying, before asking for anything, before taking a step… go to the Word of God. Find out what His word has to say about the matter. If He hasn’t said anything about it specifically, such as “Go to Kansas St. and take a left”, He has still laid our principles in His Word that cover ALL life situations.</div><ol style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong><a href="http://www.biblegateway.com/passage/?search=John+7:17&amp;version=NKJV" style="color: #008dcf; text-decoration: none;">John 7:17</a></strong><br />If anyone&nbsp;<strong>wills</strong>&nbsp;to do His&nbsp;<strong>will</strong>, he shall know concerning the doctrine, whether it is from God or whether I speak on My own authority.<br /><a href="http://www.biblegateway.com/passage/?search=John+7:16-18&amp;version=NKJV" style="color: #008dcf; text-decoration: none;">John 7:16-18</a>&nbsp;(in Context)&nbsp;<a href="http://www.biblegateway.com/passage/?search=John+7&amp;version=NKJV" style="color: #008dcf; text-decoration: none;">John 7</a>&nbsp;(Whole Chapter)</li><li style="margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong><a href="http://www.biblegateway.com/passage/?search=1%20Corinthians+4:19&amp;version=NKJV" style="color: #008dcf; text-decoration: none;">1 Corinthians 4:19</a></strong><br />But I&nbsp;<strong>will</strong>&nbsp;come to you shortly, if the Lord&nbsp;<strong>wills</strong>, and I&nbsp;<strong>will</strong>&nbsp;know, not the word of those who are puffed up, but the power.<br /><a href="http://www.biblegateway.com/passage/?search=1%20Corinthians+4:18-20&amp;version=NKJV" style="color: #008dcf; text-decoration: none;">1 Corinthians 4:18-20</a>&nbsp;(in Context)&nbsp;<a href="http://www.biblegateway.com/passage/?search=1%20Corinthians+4&amp;version=NKJV" style="color: #008dcf; text-decoration: none;">1 Corinthians 4</a>&nbsp;(Whole Chapter)</li></ol>