---
title: 'Prison Praise: Break out of your circumstances!'
date: '2012-05-29T15:53:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5146727611877705221'
blogger_filename: '/2012/05/prison-praise-break-out-of-your.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'breakthrough'
---

<b>COME</b>:<br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/nkjv/acts/16.html" target="_blank">Acts 16</a><br /><i>23 And when they had laid many stripes on them, they threw them into prison, commanding the jailer to keep them securely. 24 Having received such a charge, he put them into the inner prison and fastened their feet in the stocks. 25 But at midnight Paul and Silas were praying and singing hymns to God, and the prisoners were listening to them. 26 Suddenly there was a great earthquake, so that the foundations of the prison were shaken; and immediately all the doors were opened and everyone's chains were loosed. 27 And the keeper of the prison, awaking from sleep and seeing the prison doors open, supposing the prisoners had fled, drew his sword and was about to kill himself. 28 But Paul called with a loud voice, saying, "Do yourself no harm, for we are all here." 29 Then he called for a light, ran in, and fell down trembling before Paul and Silas. 30 And he brought them out and said, "Sirs, what must I do to be saved?"  </i></blockquote><br /><b>HEAR</b>:<br /><br />There are so many things about this familiar story that I love, wonder about, question... But here is what is jumping off the page at me today. Paul and Silas were beaten for no crime. They were Roman Citizens, deserving a trial before being beaten, yet they were treated as criminals. More-over, Paul could have told them that they were Roman Citizens before being beaten but he didn't? Despite being badly wounded (a severe Roman beating is no small matter, many died during the beating) they were still considered such a threat that they were fastened in stocks in the inner prison. This is a very secure facility. People don't escape from this. This is hopeless, in the natural.<br /><br />This guard had every reason to feel safe that they were secure and to be frightened when he found all the doors open. Paul and Silas, despite being beaten and locked up, PRAISED GOD! Their prayer and praise was so powerful that it caused a supernatural earthquake and broke all the chains and doors open. Natural earthquakes don't break off the chains, this was a spiritual event with natural consequences.<br /><br />They were, however, submissive to authority. Despite the fact the authority they were placed under was wrongly abusing their power, they stayed submissive to it, even when they had a chance to be free. This, more than anything else, caused a soldiers whole family to be saved!<br /><br />Your "dead-end-job" may feel like a prison to you. You may feel you have no way out. You may feel as though you are beaten and stuck in a dark place. I ask you to factor in God! God is more powerful than your situation. Pray and Praise. Let His praise be continually on your lips. Don't be fruity about it. Don't be singing hymns when you are supposed to be helping customers. Be submissive to the authority you are under. If you've been hired to sell things, sell them! Bring your company profit! Do what you've been called to do, for now.&nbsp;Submit&nbsp;to your&nbsp;bosses&nbsp;with enthusiasm, as you would unto Jesus himself!&nbsp;Then as you are faithful in little, God will bring you out of the dark place you feel you are in, and lead you out to a new and better place.<br /><br />There is no true submission without disagreement. If you agree than you just agree. But when you disagree and still submit with enthusiasm to the decision... that is when you are preparing for promotion!<br /><br /><b>DO</b>:<br />I'm going to go to work today and serve with enthusiasm! How about you!?<br /><br /><b>PRAYER</b>:<br />Holy Spirit, lead me on each call today, in each interaction. Show me words that you would have me speak that will bring me the best, more supernatural results. Amen!<br />__<br /><br /><b>I call you empowered 2 prosper with good success!</b><br /><b><br /></b><br /><b>Darrell G. Wolfe</b><br /><a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a><br /><a href="https://www.facebook.com/n2goodsuccess?sk=wall">https://www.facebook.com/n2goodsuccess</a><br /><br /><a href="http://empoweredtooprosper.blogspot.com/">http://empoweredtooprosper.blogspot.com/</a><br /><a href="https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118">https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118</a><br /><br /><b>See Also:</b><br />Book Suggestion from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br /><br /><b>Bulldog Publications:&nbsp;</b><br /><b><a href="http://www.amazon.com/dp/1453815619/ref=as_li_ss_til?tag=your0f4d-20&amp;camp=213381&amp;creative=390973&amp;linkCode=as4&amp;creativeASIN=1453815619&amp;adid=1NAWEWPYWDQA3XGCY7N5&amp;&amp;ref-refURL=http%3A%2F%2Fn2gs.blogspot.com%2F" target="_blank">Bankings Basics for Believers; Now Available on Amazon.&nbsp;</a></b><br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=1453815619" style="height: 240px; width: 120px;"></iframe><br /><br /><br /><iframe allowtransparency="true" src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FEmpowered-To-Prosper-E2P%2F231019763613118&amp;width=292&amp;height=62&amp;colorscheme=light&amp;show_faces=false&amp;border_color&amp;stream=false&amp;header=true&amp;appId=272647732784155" frameborder="0" scrolling="no" style="border: none; height: 62px; overflow: hidden; width: 292px;"></iframe> <iframe allowtransparency="true" src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fn2goodsuccess&amp;width=292&amp;height=62&amp;colorscheme=light&amp;show_faces=false&amp;border_color&amp;stream=false&amp;header=true&amp;appId=272647732784155" frameborder="0" scrolling="no" style="border: none; height: 62px; overflow: hidden; width: 292px;"></iframe>