---
title: 'Light Burden?'
date: '2012-03-05T07:05:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5421208514041089563'
blogger_filename: '/2012/03/light-burden.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
---

<a href="http://www.biblestudytools.com/bbe/matthew/passage.aspx?q=matthew+11:12-13" target="_blank">Matthew 11:12 (Bible in Basic English)</a><br />12 And from the days of John the Baptist till now, the kingdom of heaven is forcing its way in, and men of force take it. <br /><br /><a href="http://www.biblestudytools.com/bbe/matthew/passage.aspx?q=matthew+11:28-30" target="_blank">Matthew 11:28-30 (Bible in Basic English)</a><br />28 Come to me, all you who are troubled and weighted down with care, and I will give you rest. 29 Take my yoke on you and become like me, for I am gentle and without pride, and you will have rest for your souls; 30 For my yoke is good, and the weight I take up is not hard. <br /><br /><br />The <a href="http://n2gs.blogspot.com/2012/02/anointing-study.html" target="_blank">Anointing</a>, is the burden removing, yoke destroying power of almighty God. So why then would Jesus come to remove burdens and destroy yokes just to bring us under another yoke, a lighter one, but another one?<br /><br />Man was created WITH the ability of self determination, but he was created FOR self-determined-submission.<br /><br />Man can not submit to God unless he has the ability not to submit to God. But man was not created to make his own choices or lead his own life. There is no such thing as "Self Made Men" in the Kingdom of God. All men are made in the image and likeness of God. Only a man who is submitted to God and used by God can find his true passion, calling, purpose,&nbsp;fulfillment, and happiness. Without God man is a square tire. Without God man becomes incapable of any real and lasting prosperity. Without God man creates systems of commerce that are total and abject failures.<br /><br />Only in submitting to God can we gain access to God's wisdom and resources. In that submission all the pressure of having to preform has been taken from our shoulders and we are able to simply DO what we see Him DO and SAY what we see Him SAY. Just like Jesus did. That is how we walk in a lighter easier yoke.<br /><blockquote class="tr_bq"><a href="http://bible.cc/james/4-7.htm" target="_blank">James 4:7</a>&nbsp;English Standard Version (©2001) </blockquote><blockquote>&nbsp;Submit yourselves therefore to God. Resist the devil, and he will flee from you.</blockquote>You will either submit to God or the Devil... you are NOT a free agent. God didn't say, in <a href="http://www.biblestudytools.com/bbe/deuteronomy/passage.aspx?q=deuteronomy+30:10-20" target="_blank">Deut 30:10-20</a>,&nbsp;"I set before you blessing and cursing and&nbsp;neutrality, you choose." There are two choices. Blessing or Cursing. Inaction IS a choice. We saw this in the Israelites of&nbsp;Caleb's&nbsp;day. All his generation, accept Joshua and Caleb, died off for their lack of action regarding the Word of God to them to GO and POSSESS.<br /><br />It's time to Sit and Listen: What would God say to me right now?<br /><br />