---
title: 'You have a seed!'
date: '2012-02-11T17:19:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5579906507660025641'
blogger_filename: '/2012/02/you-have-seed.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME</b>:<br />Proverbs 4:18 <br />18 But the path of the just is like the shining sun, That shines ever brighter unto the perfect day. <br /><br /><b>HEAR</b>:<br /><a href="http://www.amazon.com/gp/product/0963258486?ie=UTF8&amp;tag=your0f4d-20&amp;creativeASIN=0963258486" target="_blank">You're not broke if you have a seed!</a><br /><br />In God's kingdom everything starts as a seed, especially understanding. You first start with a glimmer of hope, and a vague understanding that you are learning something new and exciting that could radically change your life. But you don't fully understand it yet and you have more questions than answers. If you push through and pursue that knowledge God is trying to give you there comes more and more understanding until finally at last you see it for what it is.<br /><br />However, since there is no darkness in God light doesn't grow dark into night again. Rather, it grows brighter and&nbsp;brighter,&nbsp;deeper, with more color. You never see all there is to see about something God has shown you. Just when you think you see it all, there is something new on the other side of it that you didn't see before.<br /><br />If you are facing a situation in life, financial, spiritual, etc, you are not without an answer. You have a seed. You have the Word of God and some action. Maybe it's sowing money into the situation, maybe it's something else related to time, talent, or treasure.<br /><br /><b>DO</b>:<br />Pray about the seed I need to sow regarding my situations...<br /><br /><b>PRAYER</b>:<br />Holy Spirit, what seed should I be sowing today? How would you have me believe you regarding this situation.<br /><br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=0963258486" style="height: 240px; width: 120px;"></iframe><br /><br />Darrell G. Wolfe