---
title: 'When Faith didn&#39;t work... why is it my fault?'
date: '2012-02-17T08:24:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4698034836898275177'
blogger_filename: '/2012/02/when-faith-didn-work-why-is-it-my-fault.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Faith'
---

The following is inspired be a conversation I had, I will try to recap quickly.<br /><br />This wasn't the exact question... but it is the underlying issue that provoked the question and one that needs to be addressed because many people are out there asking it.<br /><br /><div style="text-align: center;"><b>The Question:</b></div><blockquote class="tr_bq">"If faith requires actions, and without those actions I cannot receive, and I have in fact not received, and you tell me it's because of my lack of certain actions... how do I not then feel condemned? Because it's always my fault and I just wasn't good enough at this faith stuff to make it work."</blockquote><div style="text-align: center;"><b>Some Scriptures to ponder:&nbsp;</b></div><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/nkjv/psalms/passage.aspx?q=psalms+25:12-13" target="_blank">Psalm 25:12-13</a>&nbsp;NKJV<br />12 Who is the man that fears the Lord? Him shall He teach in the way He chooses. 13 He himself shall dwell in prosperity, And his descendants shall inherit the earth.<br /><br />Psalms 25:12-13 NIV:<br />12 Who, then, is the man that fears the LORD? <u>He will instruct him in the way chosen for him</u>. 13 He will spend his days in prosperity, and his descendants will inherit the land.<br /><br /><a href="http://www.biblestudytools.com/joshua/1-8.html" target="_blank">Joshua 1:8</a>8 <b>Do not let this Book of the Law depart from your mouth</b>; <b>meditate on it day and night</b>, so that you may be careful to do everything written in it. <b>Then you will be prosperous and successful</b>.<br /><br /><a href="http://www.biblestudytools.com/nkjv/romans/10.html" target="_blank">Romans 10</a>14 How then shall they call on Him in whom they have not believed? And how shall they believe in Him of whom they have not heard? And how shall they hear without a preacher? 15 And how shall they preach unless they are sent? As it is written: "How beautiful are the feet of those who preach the gospel of peace, Who bring glad tidings of good things!" 16 But they have not all obeyed the gospel. For Isaiah says, "Lord, who has believed our report?" 17 So then <b>faith comes by hearing, and hearing by the word of God.<br /></b><br /><a href="http://www.biblestudytools.com/nkjv/proverbs/10-22.html" target="_blank">Proverbs 10:22</a>22 The blessing of the Lord makes one rich, And He adds no sorrow with it. </blockquote><div style="text-align: center;"><b>The Answer:</b></div><br />There are laws that govern Godly prosperity. Certain things that cause The Blessing to come to a life and certain things that cause the Curse to come. See Deut 28 for a complete list of blessing and curse if you need those two words defined.<br /><br />Certain laws apply all the time. Like the law of gravity. You drop a penny, it falls to the ground. Maybe if you are a science student you can think of exceptions... what if the wind catches it just right... etc... bottom line. It falls. Other laws, though, like the laws of lift and those regarding flight of an aircraft require that you first of all know something, then have something, then use something. Otherwise you don't have the benefit of that flight.<br /><br /><div style="text-align: center;"><b>Laws of Flight require you to:</b></div><br /><ol><li>Know Something (regarding how to operate a plane)</li><li>Have Something (a plane, gas,&nbsp;airstrip, permission/licence, etc)</li><li>Use Something (actually getting out and using it)</li></ol><br /><div style="text-align: center;"><b>Here is a thought.&nbsp;</b></div><br />A man living in 1 AD&nbsp;doesn't&nbsp;know about the laws that govern lift and flight. He&nbsp;doesn't&nbsp;know that man can fly, with the right factors in place. He isn’t to be condemned because he&nbsp;didn't&nbsp;put the laws of flight into practice. That’s not his fault.&nbsp;However, he&nbsp;isn't&nbsp;benefiting from the laws of flight without them either. A plane, fully equipped and fueled would fly just as easily in 1 AD as it does in 2012 AD. The air didn't change to allow for flight. We simply learned out to put certain laws/principles into action.<br /><br />Is it his “fault” he isn’t flying? Yes and No.<br /><br /><ul><li>No. He&nbsp;couldn't&nbsp;the laws of flight hadn’t been discovered yet.&nbsp;Neither&nbsp;had all of the previous discoveries that were needed to understand them.&nbsp;</li><li>Yes. There were there for him to discover, he just&nbsp;didn't&nbsp;look to discover them.&nbsp;</li></ul><div style="text-align: center;"><b>We don’t know what we don’t know.</b></div><div style="text-align: center;"><br /></div>So it is with these laws governing faith and prosperity. We don’t know what we don’t know. Was it our fault we&nbsp;didn't&nbsp;prosper? Yes. In the same sense that this man in 1 AD&nbsp;didn't&nbsp;fly. We didn’t know what we didn’t know. But we still&nbsp;aren't&nbsp;going to benefit until we know how to operate the laws accurately.<br /><br />There is no condemnation, yet there is responsibility for action. So you tell me that you did everything you knew to do and it still didn't work. Great. I'm glad you did what you knew to do. But all that means is you did what you knew to do. It doesn't mean you did what was needed. Many tried to fly and failed. Only after we got all the right things in order did we succeed. But once we did we can do it, without fail, over and over and over again.<br /><br /><div style="text-align: center;"><b>!!!!!No Condemnation!!!!!</b></div>GRACE is important here. This is where people in the Word of Faith camp often miss it too. We beat up ourselves over things we don't do, then we beat up everyone else for what they don't do. Then the weaker brother feels like he just isn't worth the time of day because everyone is always telling him what he did wrong instead of telling him what Jesus did right!<br /><br />NONE of us is worthy. NONE of us does it right. That's the beauty of GRACE. It's His blood, His, Word, His job, His seed, His ground, His faith, His everything! We do two things. <b>Believe and Respond</b>. That is why it's so simple that we mess it up. All that He requires of us is to believe and respond.<br /><br /><a href="http://www.biblestudytools.com/nkjv/luke/8-50.html" target="_blank">Luke 8:50</a><br />But when Jesus heard it, he answered him, saying , <b>Fear not: believe only</b>, and she shall be made whole . <br /><br />We believe and then respond to what he tells us to do. You ever wonder why Jesus was able to do all the amazing things He did? It wasn't because He was God, he laid aside his God-Side when he came to preach. He did, what He did, as a man preaching under the old covenant. He did it perfectly, because although He didn't use divine power, He was still who He was in personality.&nbsp;<a href="http://www.biblestudytools.com/ylt/philippians/passage.aspx?q=philippians+2:2-12" target="_blank">Philippians 2&nbsp;</a>We know this because he also said you can do what I do and more! <a href="http://www.biblestudytools.com/nkjv/john/5-20.html" target="_blank">John 5:20</a>&nbsp;Then Paul, Peter, and others did, in fact, do more and great things with the same anointing Jesus did.<br /><br />Jesus said what He heard His Father say, and did what He heard His Father do. (<a href="http://www.biblestudytools.com/nkjv/john/5-19.html" target="_blank">John 5:19</a>)&nbsp;So that is our&nbsp;secret&nbsp;to, we prayer and get in the Word and meditate that Word... until we come to a place where we believe and respond with no doubt. That's it! Pretty simple...<br /><br />So there is NO condemnation, we've all missed it. We've all had times we thought we were doing the right things and we weren't. We all stepped out on a legitimate&nbsp;response&nbsp;to walk on the water and then got so distracted by wind and waves that we began to sink and had to be rescued. We didn't know, what we didn't know. But we also don't reap the benefit until we put certain things into motion.<br /><br />Does that help clarify the difference?<br /><br />Darrell G. Wolfe