---
title: 'WILL'
date: '2012-01-21T10:21:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7987543860713355831'
blogger_filename: '/2012/01/will.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'Will of God'
---

<br /><h1 style="background-color: white; border-bottom-color: rgb(204, 204, 204); border-bottom-style: dotted; border-bottom-width: 1px; font-family: Arial, Tahoma, Verdana; font-size: 20px; font-weight: normal; line-height: 20px; margin-bottom: 10px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 5px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;">WILL</h1><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Come with me on a journey to the middle east. The time is at or around the 40 AD’s. There is a man traveling with a group of people through the dusty roman built roads from Jerusalem to the town of Damascus. He is steadfast and resolute in his drive and passion to end the sect called “The Way”. He is a Pharisee, a conservative. The liberal wing party of the Sadducee&nbsp; have been tearing down the fabric of the Torah. They deny the miracles of the prophets such as Elijah and Elisha. They have turned the worship of the One True God into a social gospel of morals and religious power. The signs of the Torah point to the coming of a great Messiah.</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">When Messiah comes he will set things straight. He will come and remove the Roman oppressors. Finally after centuries of disobedience the Jews are no longer being pulled away by useless idol worship. Then he came. There have been many false Messiah’s over the last few decades, but this one has turned the entire nation of Israel on it’s head. They thought they’d dealt with him by killing him at the hands of the Roman Guard, but then his disciples came and stole his body. Now they spread rumors everywhere of his resurrection which has served to spread this malicious sect all over the known world.</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Now Saul finds himself on the dusty Roman Road to Damascus. He has papers in hand to arrest or kill man, woman, and child who would dare to follow this “Way”. He feels it’s his personal mission to see that the way is paved for Messiah to come and free us from the Roman oppression. Messiah must not come and find us yet again distracted by other pretend gods.</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Suddenly a bright and blinding light!. The light is not just bright but it comes with a presence. The power emanating from it can be felt through his entire body. It pulsates and warms his very bones and spirit. He cannot stand under the power of it. He is not just caught off balance. The power of the presence so overwhelms him that he cannot stand. His legs become weak beneath him and he falls to the ground as though he were a dead man. There, laying on the ground surrounded by this light, this presence… a voice…</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">“Saul… Saul… Why are you persecuting me?”</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">That voice penetrates the soul and therefore must be heeded. He responds to this by a logical question:</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">“Who are you Lord?”</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">The voice responds: “I am Jesus who you are persecuting. It is hard for you to kick against the goads. “</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">What response can he have to that type of power and authority? When all the religious trappings have been torn away and all the pretense removed… what is the response of this man who’s soul has been laid bare?</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">“Lord! What would you have me do?”</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">In our modern vernacular we might phrase it:<br />What do you want? or What is YOUR WILL?</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Jesus doesn’t leave him there… he tells him that he will be shown what to do. Jesus doesn’t lay out the entire plan for Paul’s life there on the road. He simply gives him instructions to follow, which will lead to more instructions.</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">The Will of God is among the most sought after answers a new christian seeks and among the most confusing for many. What is the will of God? What does God will? What is He like? What is His will for mankind, for my family, for me? Do I have a call on my life? Does He have a perfect choice? If I’m offered two jobs how do I know which one God would will for me? Or do I simply sit back and observe my life as many do assuming that whatever happens is the will of God because it happened? This is a topic that need not be confusing at all. But there are foundational matters that must be settled to understand it. Therefore come with me on a journey to the Center of God’s Will!</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Darrell G. Wolfe</div>