---
title: 'What is Prosperity?'
date: '2012-01-21T08:49:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '946843798910373410'
blogger_filename: '/2012/01/what-is-prosperity.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'Prosperity'
---

<br /><h3 style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 18px; font-weight: normal; line-height: 20px; margin-bottom: 5px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;"> <span style="font-size: 12px;">The world sees prosperity as having a big house, and lots of nice cars. They see money and women all around you as prosperity. They look to icons like Micheal Jordan, Hugh Hefner, or Snoop Dog as what it means to be successful. Others look to politicians, or kings of finance like warren buffet. What is prosperity from God’s point of view?</span></h3><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px;"><span style="color: black;"><a href="http://www.biblegateway.com/" style="text-decoration: none;">1 Thessalonians 5:22-24</a>&nbsp;<sup>22</sup>Avoid every kind of evil.&nbsp;<sup>23</sup>May God himself, the God of peace, sanctify you through and through. May your whole spirit, soul and body be kept blameless at the coming of our Lord Jesus Christ.&nbsp;<sup>24</sup>The one who calls you is faithful and he will do it.</span></div><ul style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Spirit</li><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Soul</li><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Body</li></ul><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px;">God is interested in WHOLE person prosperity.</div><ul style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">He wants you to get born again and filled with his Spirit. That’s spirit prosperity.</li><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">He wants you to have a renewed mind and knowledge and wisdom and understanding.</li><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">He wants you to have healing and health, long life, wealth, and protection from attacks of the enemies of your life and calling. That’s body prosperity.</li></ul><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px;">What purpose does prosperity hold for God’s people?</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px;"><br /></div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px;">First of all, the earth was created for man not for God. He created it for us. He gave all things for us to enjoy. In this fallen world we are to make disciples of all men, preaching and teaching the Kingdom of God. This is hard to do without money. You can only reach so many and so far without money for travel, to print bibles and materials, to reach more.</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px;">I heard the story of Warren Buffets niece who was cut off from the family fortune because she offended his way of doing things. The reaction of all who heard the story was the same. “How awful! that rich man cutting off his niece from the fortune of the family. It was considered horrible that he gave little to his family and made each person even his sons work their own money…” Why? Why is this SO BAD.</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px;"><br /></div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px;">The bible says that a good man leaves an inheritance for his children’s children. Everyone instinctively knows that a rich man holding his wealth from his own family is an evil thing. But how much worse would it be if the God of heaven and earth, the God who owns the cattle on a thousand hills, and has streets made of Gold was holding out on his family. It was be an evil thing for God to live in total wealth and have his kids purposefully scrounging dumpsters. Far be it from God to do such a thing!</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px;"><br /></div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px;">Those who are of God and not living in or on their way to living in his full prosperity and provision are those who are those who are ignorant of his Promises. Usually do to traditions of Men that taught it was holy to be poor, when the bible specifically and consistently calls poverty a curse.</div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px;"><br /></div><div style="background-color: white; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px;">Darrell G. Wolfe</div>