---
title: 'Get a vision for using more of your talent!'
date: '2012-02-04T09:07:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6061505077238038371'
blogger_filename: '/2012/02/get-vision-for-using-more-of-your-talent.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><a href="http://www.biblestudytools.com/nkjv/matthew/25.html" target="_blank"><b>Matthew 25</b></a> (New King James Version)<br />24 Then he who had received the one talent came and said, 'Lord, I knew you to be a hard man, reaping where you have not sown, and gathering where you have not scattered seed. 25 And I was afraid, and went and hid your talent in the ground. Look, there you have what is yours.' 26 But his lord answered and said to him, 'You wicked and lazy servant, you knew that I reap where I have not sown, and gather where I have not scattered seed. 27 So you ought to have deposited my money with the bankers, and at my coming I would have received back my own with interest. 28 Therefore take the talent from him, and give it to him who has ten talents. <br /><br /><b>HEAR:</b><br /><b><a href="http://1828.mshaffer.com/d/search/word,talent" target="_blank">Talent</a></b>... Gift... Time... Resources... Skill... Faculty/Ability... Worth... Value... Measure...<br /><br />These are the words that come to mind as I consider this whole chapter, and specifically the lazy servant. How many of us live and die without ever discovering our true potential, calling, and gifting of God. Or worse, discover it, and fail to ever live it out.<br /><br />There is something God has planned for each of us. A vision. A plan.<a href="http://www.biblestudytools.com/nkjv/jeremiah/29-11.html" target="_blank"> He has GOOD plans too,</a> not plans to harm you and take you somewhere you don't want to go and make you miserable. That's not God. That's religion. Did you know that working for God comes with a Kingdom <a href="http://www.biblestudytools.com/nkjv/psalms/103.html" target="_blank">Benefits </a>plan? YEAH! And it's way better than anything your job offers you. Healing, Deliverance, Prosperity... way better!<br /><br />God's dream for you, is bigger than anything you can dream or <a href="http://bible.cc/ephesians/3-20.htm" target="_blank">imagine</a>. Just look at home many times in the bible God used <a href="http://www.biblestudytools.com/search/?q=god+dream&amp;c=&amp;t=nkjv&amp;ps=100&amp;s=Bibles" target="_blank">dreams </a>to communicate with people. Dreams are important to God.<br /><br /><b>DO:&nbsp;</b><br />I'm going to review my dream book today and start dreaming bigger!<br /><br /><b>PRAYER:</b><br />Holy Spirit, <a href="http://www.biblestudytools.com/nkjv/isaiah/54-2.html" target="_blank">enlarge my tent</a> and my mind. Help me see how big you can be in and through me!<br /><br />Darrell G. Wolfe<br /><br /><b>Great Resources:</b><br /><br /><b>Terri Savelle Foy: "<a href="http://www.terri.com/can-you-imagine/" target="_blank">Can you Image</a>?"&nbsp;</b><br /><b><br /></b><br /><b>Al Pearson: <a href="http://aldeanpearson.blogspot.com/2011/05/10-steps-to-building-your-self.html" target="_blank">10 Steps to building your self confidence.</a>&nbsp;</b><br /><br /><br /><iframe allowfullscreen="" frameborder="0" height="315" src="http://www.youtube.com/embed/sMwlLdVUQG4" width="420"></iframe><br /><br />