---
title: 'Yoke and Burden... Be Light!'
date: '2012-01-16T15:59:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2173367951572878856'
blogger_filename: '/2012/01/yoke-and-burden-be-light.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><b><a href="http://www.biblestudytools.com/nkjv/matthew/passage.aspx?q=matthew+11:28-30" target="_blank">Matthew 11:28-30</a>&nbsp;NKJV</b><br />28 Come to Me, all you who labor and are heavy laden, and I will give you rest. 29 Take My yoke upon you and learn from Me, for I am gentle and lowly in heart, and you will find rest for your souls. 30 For My yoke is easy and My burden is light." <br /><br /><span class="versiontext" style="background-color: #f9fdff; font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-weight: 700; line-height: 20px; text-align: justify; text-decoration: none; vertical-align: top;"><a href="http://bible.cc/matthew/11-28.htm" target="_blank"><span style="color: #0092f2;">GOD'S WORD® Translation</span>&nbsp;<span style="color: #0092f2;">(©1995)</span></a></span><br /><span style="background-color: #f9fdff; color: #001320; font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 21px; text-align: justify;">"Come to me, all who are tired from carrying heavy loads, and I will give you rest.</span><br /><span class="versiontext" style="background-color: #f9fdff; font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-weight: 700; line-height: 20px; text-align: justify; text-decoration: none; vertical-align: top;"><a href="http://bible.cc/matthew/11-28.htm" target="_blank">Weymouth New Testament</a></span><br /><span style="background-color: #f9fdff; color: #001320; font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 21px; text-align: justify;">"Come to me, all you toiling and burdened ones, and *I* will give you rest.</span><br /><span class="versiontext" style="background-color: #f9fdff; font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-weight: 700; line-height: 20px; text-align: justify; text-decoration: none; vertical-align: top;"><a href="http://bible.cc/matthew/11-28.htm" target="_blank">Young's Literal Translation</a></span><br /><span style="background-color: #f9fdff; color: #001320; font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 21px; text-align: justify;">'Come unto me, all ye labouring and burdened ones, and I will give you rest,</span><br /><span style="background-color: #f9fdff; color: #001320; font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 21px; text-align: justify;"><br /></span><br /><span style="background-color: #f9fdff; color: #001320; font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 21px; text-align: justify;"><b>The New English Bible Oxford Press 1961, out of print,</b></span><br /><span style="background-color: #f9fdff; color: #001320; font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 21px; text-align: justify;">Come to me, all whose work is hard, whose load is heavy; and I will give you relief. Bend your necks to my yoke, and learn from me, for I am gentle and humble-hearted; and your souls will find relief. For my Yoke is good to bear, my load is light.&nbsp;</span><br /><span style="background-color: #f9fdff; color: #001320; font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 21px; text-align: justify;"><br /></span><br /><br /><b>HEAR:</b><br />Why is Jesus burden lighter? I think about this as my son is in time out in his room. He get's it from me, this escalating side of personality. He starts by getting frustrated about being told to do something that he doesn't want to do, then gets a time out for throwing a fit, but then get's in bigger trouble for throwing a fit about that... and up the spiral it goes. I have found the same thing in my life. If my life is not exactly the way I want it to be I throw mini fits with God.<br /><br />Of course I'm all grown up now, so my fits are more sophisticated right? I give Him the silent treatment by ignoring Him, or I whine to Him and call it prayer, or I go buy something I know I shouldn't or he's asked me not to, like another soda for that day when he's told me to cut down. Do I recognize these as fits? Sometimes, but most of the time I'm so sophisticated that I don't see them for what they are... Plain, Simple, Childish, Fits.<br /><br />How goes Jesus respond to our desire for a better life? When we are feeling the stress of work, money, home, etc... What does Jesus say about it?<br /><br />"Come to me! ALL you who are tired of working and heavy with burdens... MY <a href="http://en.wikipedia.org/wiki/Yoke" target="_blank">yoke </a>is easy! MY burden is light!<br /><br />Regarding the yoke and burden <a href="http://www.facebook.com/notes/joseph-prince/life-with-god-is-easy-and-light/112218232165345" target="_blank">Joseph Prince said</a>:<br /><br /><i>What does it mean to be yoked with Jesus? Imagine a pair of oxen yoked together. The younger ox sees what the lead ox does and follows. If the lead ox turns left, the younger ox turns left. If the lead ox stops, the younger ox stops. When the lead ox starts moving again, the younger ox follows. Likewise, Jesus wants us to follow His leading and flow with Him.&nbsp;</i><br /><i><br /></i><br /><i>It is not hard to flow with Jesus because He will not lay anything heavy on you — "For My yoke is easy and My burden is light." (Matthew 11:30) When you are yoked with Him and you flow with Him, you will find that there is nothing heavy-hearted, ill-fitting or burdensome from the Lord. When you flow with the Lord, you will find that things fall into place. You will not be weighed down, anxious or distressed.</i><br /><br />Regarding the yoke and burden <a href="http://www.kcm.org/index.php?p=real_help_content&amp;id=1363" target="_blank">Kenneth Copeland said</a>:<br /><br /><i>News of the Anointed and His Anointing was the "good news" or "gospel" the early Church ministered. When Peter was asked to preach the basic, gospel message to the gentiles for the very first time, the first thing he told them was "how God anointed Jesus of Nazareth with the Holy Ghost and with power: who went about doing good, and healing all that were oppressed of the devil; for God was with him" (see Acts 10:38-39). When Philip preached Christ (the Anointed One and His Anointing) in Samaria, "the people with one accord gave heed unto those things which Philip spake, hearing and seeing the miracles which he did. For unclean spirits, crying with loud voice, came out of many that were possessed with them: and many taken with palsies, and that were lame, were healed" (see Acts 8:6-8). They received and heard the good news that the Anointed One and His Anointing had come to destroy the yokes from their backs. From the moment they received it, God confirmed it, just as He did in Jesus' ministry....</i><br /><i><br /></i><br /><i>...The word "Christ" is not just another name for Jesus, but a reference to the Anointed and the Anointing that was on Him and in Him. In the same way, the word "Christians" means more than just followers of Jesus. It means "the anointeds." The same yoke-destroying Anointing that was on Jesus is available to you.  </i><br /><br />It is this burden removing, yoke destroying anointing of God that we live in and with. As we follow Jesus' lead in life we operate in and under that anointing. The anointing is the very power of God that raises the dead and casts out devils. It was this anointing Jesus preached everywhere he went, his mission statement verse was found in <a href="http://www.biblestudytools.com/nkjv/isaiah/61.html" target="_blank">Isaiah 61</a> regarding the anointing.<br /><br />If we are following Jesus' lead in life, taking his direction, we do not experience burden! There is no heaviness on us, we don't experience the&nbsp;weight&nbsp;of bills, or money concerns. Indeed, you cannot serve God and Money! (<a href="http://www.biblestudytools.com/nkjv/matthew/6-24.html" target="_blank">Matthew 6:24</a>)<br /><br /><b>DO:</b><br />Follow the lead of Jesus, spend time with Him. Seek His face, not his hand. Seek His presence for who He is, not what He can do. Then watch THE BLESSING unfold around you.<br /><br /><b>PRAYER:</b><br />Spirit of Grace, you are welcome in this place. Make my heart, life, and this very room, a&nbsp;sanctuary. In your presence may I find the Grace I need to then in turn impart that Grace to my kids and family.<br /><br />Darrell G. Wolfe