---
title: 'Jesus wasn&#39;t poor, he didn&#39;t ask you to be either!'
date: '2012-01-26T18:16:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4144359255536169715'
blogger_filename: '/2012/01/jesus-wasn-poor-he-didn-ask-you-to-be.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><b><a href="http://www.biblestudytools.com/nkjv/matthew/19-21.html" target="_blank">Matthew 19:21</a></b><br />21 Jesus said to him, "If you want to be perfect, go, sell what you have and give to the poor, and you will have treasure in heaven; and come, follow Me." <br /><br />29 And everyone who has left houses or brothers or sisters or father or mother or wife or children or lands, for My name's sake, shall receive a hundredfold, and inherit eternal life. <br /><br />Compare to:<br /><b>Mark 10:30 </b><br />30will fail to receive a hundred times as much<b> in this present age</b> (homes, brothers, sisters, mothers, children and fields--and with them, persecutions) and in the age to come, eternal life. <br /><br /><br /><b>HEAR:</b><br />Paraphrase: "If you want to be complete, mature, lacking nothing, go on your way, sell what you have to sell, and begin giving to the poor, this will add to your account in heaven, which pays far better&nbsp;dividends. Then come follow me... And if you'd hung around long enough, instead of walking away sad at what I said, you'd hear me tell the disciples that anyone who left things for me would receive a 100 fold return on that investment! Besides that I didn't tell you to sell everything you have, I said to sell what you have, that means sell what you have to sell, start somewhere!"<br /><br />Isn't it funny how we like to jump to conclusions and think we know what we heard someone say and then totally miss it? Just between my wife and I there are constantly situations I heard her say words, I took those words to mean X and she meant Y. If a husband and wife, so close to each other, can misunderstand each other, how much more should we pay attention that we don't misunderstand other people, God, and the Preachers who God has sent?<br /><br />Jesus didn't tell this man to give away everything he had. He said to sell, whatever he had to sell, in order to start giving to the poor. As we know from throughout the rest of scripture OT and NT giving IS receiving... there is a seed/harvest principle here. If Jesus didn't want the man to have anything he would have just told him to get rid of everything, or leave it, or abandon it to someone else and come along, but that's not what he said. He said. Jesus said "Sell" there is a process to selling things. It takes time, you have to find a buyer, you &nbsp;have to receive the payment and process paperwork. Then to give to the poor probably meant then, as it does today, that you would give to organizations that help the poor, or maybe Jesus had a specific poor person in mind?<br /><br />Besides all of this, you can't sell everything all at once. Even estate sales end up having multiple buyers over a period of time. Especially if the man had&nbsp;multiple&nbsp;lands, which he must have if he was that wealthy. So selling would have been sell, give, sell give, sell give... etc...&nbsp;There is a LOT of process going on here.<br /><br />Through this process Jesus is going to show this young man how to get OFF the worlds system of wealth creation and hop over on to God's system of wealth creation. Jesus didn't want the man poor, how can you give to the poor and be poor? Jesus didn't say, and you know, I'm the poorest of them all, so you need to give to me... Jesus didn't need that money because HE wasn't poor either! He was a successful carpenter. Poor people don't hire a staff of 12, part time staff of 120, and engage the services of a treasurer. Jesus owned a home in <a href="http://ntweblog.blogspot.com/2006/03/did-jesus-have-house-in-capernaum.html" target="_blank">Capernum</a>&nbsp;(<a href="http://www.biblestudytools.com/my-bible/#/left:passage/nkjv/mark/2/&amp;right:passage/nkjv/john/1:35-42/" target="_blank">Mark 2:1, John 1:35-42</a>). He was funded at birth with&nbsp;immense&nbsp;wealth, and by many rich men and women during his years in ministry. He slept in a manger because the Inn keeper lost his parents reservations, which may have belonged to his family by the way (See&nbsp;Joseph&nbsp;Prince that that explanation).<br /><br />The purpose of accumulation is&nbsp;distribution. Become a&nbsp;<u>distributor for the Kingdom</u>. <br /><br /><b>DO:</b><br />Pray about where Holy Spirit is leading me to sow my time, talent, and treasure today... so that I may engage HIS system of operation and gain wealth his way: To become a <u>distributor for the Kingdom</u>.<br /><br /><b>PRAYER:</b><br />Holy Spirit, tell me today, what to give, when to give it, and whom to give it to!<br /><br />Darrell G. Wolfe<br /><br />See Also:<br /><br /><a href="http://www.youtube.com/watch?v=cFhfrDkUo3w">http://www.youtube.com/watch?v=cFhfrDkUo3w</a><br /><br /><a href="http://www.squidoo.com/Money-Christian">http://www.squidoo.com/Money-Christian</a><br /><br /><a href="http://www.christiananswers.net/christmas/mythsaboutchristmas.html">http://www.christiananswers.net/christmas/mythsaboutchristmas.html</a><br /><br />The poster of this video posted it to disagree with the preacher, but I&nbsp;liked it!<br /><br /><iframe allowfullscreen="" frameborder="0" height="315" src="http://www.youtube.com/embed/cFhfrDkUo3w" width="420"></iframe><br /><br />