---
title: 'THE BLESSING: Abundance of Fruit from the Old and New!'
date: '2012-01-18T17:01:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '391493742524890156'
blogger_filename: '/2012/01/the-blessing-abundance-of-fruit-from.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><b><a href="http://www.biblestudytools.com/nkjv/matthew/13.html" target="_blank">Matthew 13</a></b><br />12 For whoever has, to him more will be given, and he will have abundance... <br /><br />22 Now he who received seed among the thorns is he who hears the word, and the cares of this world and the deceitfulness of riches choke the word, and he becomes unfruitful. <br /><br />51 Jesus said to them, "Have you understood all these things?" They said to Him, "Yes, Lord." 52 Then He said to them, "Therefore every scribe instructed concerning the kingdom of heaven is like a householder who brings out of his treasure things new and old." <br /><br /><b>HEAR:</b><br />Three things stood out to me today. Are they related? I don't know, let's take a look and find out together. Whoever has will be given more until he has an abundance... too much... overflow... Why? Because that is God's nature, to give to overflow. If you don't have the Kingdom of God working in you than you are not connected to THE BLESSING that the Kingdom of God restores to you. If you don't have THE BLESSING the only other option is THE CURSE. The Curse takes from you what little you have. THE BLESSING adds to you until it overflows into the lives around you. That's why Abraham was blessed to be a blessing. That's what THE BLESSING does!<br /><br />So why did the word become unfruitful in this hearer of The Word of BLESSING? Because the idea of wealth became so powerful to him that he began to be consumed by it. He wanted that wealth so badly, maybe because he grew up poor, or because every business he'd tried on his own failed, or because he was afraid of being poor, or maybe he is like the rich young ruler that go his wealth by the covenant promises but failed to see how Jesus was tying the covenant promises to this deeper understanding of them. No most people, especially unsaved and religious people, are fearful of people taking from them or others motives. This is the only reason you could see someone preaching about seed/harvest and giving/receiving as wanting your money. You take an honest, prayerful look at Kenneth Copeland and you will find that he is trying to get something TO YOU not take anything FROM YOU. But there are charlatans out there. There are slick preachers that are out for your money. Jesus called these tares/darnels/weeds in the Kingdom of God. It is those men who probably got the message of wealth from THE BLESSING but failed to receive it God's way, so they turned it into a business.<br /><br />Now a scribe is a teacher of the Law. Jesus says here that a teacher of the Law, should he get on board with the Kingdom of God can bring fabulous understanding, deeper understanding of The Kingdom from both the new and old covenant. Jesus, among other things, was actually&nbsp;prophesying&nbsp;the ministry of Paul here. He was showing that a proper understanding of both old and new will give a fuller understanding of both.<br /><br /><b>LESSON:&nbsp;</b><br />This is a lesson the Church could use. We have for many years failed to understand the old covenant, what it is and isn't. We failed to understand THE BLESSING of Adam, Noah, Abraham, Jesus, and Me/You. <a href="http://www.biblestudytools.com/nkjv/proverbs/10-22.html" target="_blank">THE BLESSING makes rich</a> and adds no sorrow with it. So THE BLESSING causes you to be fruitful, multiply, fill up, subdue, and have&nbsp;dominion. That is why Jesus used covenant&nbsp;verbiage&nbsp;when he said the seed becomes unfruitful. <a href="http://www.biblestudytools.com/search/?q=god+mammon" target="_blank">You cannot serve God and Money</a>. But if you serve God then money commeth! And it comes in abundance, to the full, until it overflows! God's interested in causing you to be the&nbsp;distribution&nbsp;center! The blessing recreates the Garden of Eden everywhere you go. That's what it did for Abraham and Joseph, and David, and anyone who would follow in it. In the Garden Gold and Silver grew right on top of the ground. So God is not concerned about you having wealth or material things.<br /><br />So what happened in this seed that made the man unfruitful? He got caught up in the cares of wealth. He was &nbsp;so concerned with getting money, how to get money, how to make more money, that he failed to enter the Kingdom of God ways of doing things. God's ways are <a href="http://www.biblestudytools.com/nkjv/matthew/7-7.html" target="_blank">Ask and Receive, Knock and Open, Seek and Find</a>, and Sow and Reap.<br /><br />How many times have I switched jobs looking for the next big thing, tried this project or that MLM business trying to make it rich. All the while God is saying sow, water, wait... Work this Kingdom. The first harvest off of one seed isn't big. But if you sow that harvest it gets bigger, and then sow that harvest and it gets bigger.<br /><br />What does it mean to sow? Sow money? Yes and No. You can sow money into the Kingdom and not receive a harvest. Money isn't seed. However the heart-faith-action behind the act of giving is the seed. When God asks you to start writing a book, a song, a blog, go to work for a company you don't know much about, move to another state, etc etc Those are all seeds as well. Abraham left Ur and Haran. That was seed too.<br /><br />So by gaining a proper understanding of the old and new covenant I can understand THE BLESSING which is THE KINGDOM OF GOD. Then I understand giving and receiving an abundance and I can operate in obedience to God and not seeking a buck. Then I can focus on writing what HE told me to write, not because it will or won't make money but because HE told me to. I become focused on getting God's Words into people rather than getting money from them. If I post a comment on a blog&nbsp;somewhere, is it to get people to follow my link and buy my book, or was it truly to add to their conversation and BLESS them!? Now we are talking Kingdom!<br /><br /><b>DO:&nbsp;</b><br />Seek God about what I'm doing, saying, and working on. Make sure I'm doing what He has assigned me to do. And just as importantly STOP DOING anything HE has NOT assigned me to do.<br /><br /><b>PRAYER:&nbsp;</b><br />Show me the things I need to focus on and those I need to cut out. Thank you for clarity and focus in my work, making my hours productive for The Kingdom of God.<br /><br />Darrell G. Wolfe