---
title: 'Administer THE BLESSING today!'
date: '2012-01-21T19:09:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '86742395096564916'
blogger_filename: '/2012/01/administer-blessing-today.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><b><a href="http://www.biblestudytools.com/nkjv/matthew/passage.aspx?q=matthew+15:21-28" target="_blank">Matthew 15:21-28</a></b><br />21 Then Jesus went out from there and departed to the region of Tyre and Sidon. 22 And behold, a woman of Canaan came from that region and cried out to Him, saying, "Have mercy on me, O Lord, Son of David! My daughter is severely demon-possessed." 23 But He answered her not a word. And His disciples came and urged Him, saying, "Send her away, for she cries out after us." 24 But He answered and said, "I was not sent except to the lost sheep of the house of Israel." 25 Then she came and worshiped Him, saying, "Lord, help me!" 26 But He answered and said, "It is not good to take the children's bread and throw it to the little dogs." 27 And she said, "Yes, Lord, yet even the little dogs eat the crumbs which fall from their masters' table." 28 Then Jesus answered and said to her, "O woman, great is your faith! Let it be to you as you desire." And her daughter was healed from that very hour. <br /><br /><b>HEAR:</b><br />At first glance Jesus' response to this woman seems rude, even uncharacteristic. I thought Jesus was LOVE himself. How could he treat this woman so badly. She wasn't Israeli. The centurion wasn't Israeli. Well the centurion was in a&nbsp;ruling&nbsp;position over Israel and therefore had the authority to ask. Technically, in the natural, Jesus was under the&nbsp;Centurions&nbsp;authority as Rome had conquered Israel and was occupying it.<br /><br />We are BLESSED to be a BLESSING. Jesus was sent to Israel first, only under Paul and Peter's ministry was THE BLESSING opened up to all people. Yet part of THE BLESSING was to be a blessing to all people. So She correctly responded that she wasn't part of the Masters table, as a non Jew, but she did have a right to the scraps. That gave Jesus the opening He needed to administer THE BLESSING to her!<br /><br />I'm not outside the Covenant today. But many, many people are. Those that have not accepted Jesus are outside the Covenant. It is my JOB and DUTY to administer the BLESSING to them, but under GRACE they need not beg.<br /><br /><b>DO:</b><br />Make it a point to pray for opportunities to administer THE BLESSING wherever I go.<br /><br /><b>PRAYER:</b><br />Holy Spirit, use me to dispense your BLESSING this week. Thank you for the opportunity!<br /><br />Darrell G. Wolfe