---
title: 'Only Believe.'
date: '2012-02-07T17:06:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2493410507088378453'
blogger_filename: '/2012/02/only-believe.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><b><a href="http://www.biblestudytools.com/nkjv/matthew/27.html" target="_blank">Matthew 27</a></b><br />50 And Jesus cried out again with a loud voice, and yielded up His spirit. 51 Then, behold, the veil of the temple was torn in two from top to bottom; and the earth quaked, and the rocks were split, 52 and the graves were opened; and many bodies of the saints who had fallen asleep were raised; 53 and coming out of the graves after His resurrection, they went into the holy city and appeared to many. 54 So when the centurion and those with him, who were guarding Jesus, saw the earthquake and the things that had happened, they feared greatly, saying, "Truly this was the Son of God!" <br /><br /><b>HEAR:</b><br />As I read about the death of my sweet Jesus... I am reminded that he did for me, what I could not possibly do for myself. It's an insane question to even ask yourself if you die his death, because his death was more than physical. He took on the sins of the whole world. No human could do that. All he asks in return is that I believe. Yet, we struggle with that belief. We struggle to believe that He cares, that He will, that He'll do what His word says He'll do.<br /><br /><b>DO:</b><br />Today, I'm going to practice Believing!<br /><br /><b>PRAYER:</b><br />Holy Spirit, reveal today, throughout the day, areas/thoughts/words/imaginations that are rooted in unbelief. Show me where I can begin to alter my thought life toward believing your promises.<br /><br />Darrell G. Wolfe<br /><br />Only Believe.