---
title: 'Raise the Dead Things in my life!'
date: '2012-01-12T17:36:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5768387550257979298'
blogger_filename: '/2012/01/raise-dead-things-in-my-life.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><b><a href="http://www.biblestudytools.com/parallel-bible/passage.aspx?q=matthew+9%3A18&amp;t=nkjv&amp;t2=rhe" target="_blank">Matthew 9:18</a></b><br />New King James Version (NKJV)<br />18 While He spoke these things to them, behold, a ruler came and worshiped Him, saying, "My daughter has just died, but come and lay Your hand on her and she will live." <br /><br /><b>HEAR:</b><br />I don't know how many times I've read this and heard it. Mark records this as "My daughter lies at the point of death", <a href="http://www.biblestudytools.com/nkjv/mark/5-23.html" target="_blank">Mark 5:23</a>. Today it just caught my attention. There is a difference between being dead and near dead, but not much. So often things have looked hopeless in a situation to the point that in our mind they are already dead. Maybe it's a person, like this daughter. Or maybe it's a career, a dream, an idea. Maybe it's a situation like trying to make the payment before the deadline.<br /><br />This father could have had a near heart attack himself when the man comes along from his house to tell him that his daughter was "dead, trouble the master no longer". But he didn't, He listened to Jesus' instruction: "Feat Not, only Believe" and stuck with it.<br /><br />Are there things in my life that are dead, or near dead? Have I let anything pass away because I didn't see how it could ever change? Did I let some gift or calling or dream pass away?<br /><br />Jesus doesn't see any difference between dead and near dead. He can raise it up anyway. Even after decay has set in to the four day dead body of&nbsp;Lazarus, Jesus can raise him up.<br /><br /><b>DO:</b><br />I'm going to pray about the things I have let slip and ask God to renew my mind to what He has called me to do. Perhaps there are things that He has for me that I let die, like music. Perhaps I could allow Him to raise those things from the dead for me so that I can walk them out.<br /><br /><b>PRAYER:</b><br />Father, Daddy, Are there things in my life, callings, giftings, dreams, that I let die? Did I allow a disease of unbelief or fear creep in like a cancer and kill off those things? If there are things You have for me that I let die, please raise them from the dead and&nbsp;reignite&nbsp;the fire in me once again!<br /><br />Darrell G. Wolfe