---
title: 'What are you allowing in your life?'
date: '2012-01-25T17:58:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7954644966066753263'
blogger_filename: '/2012/01/what-are-you-allowing-in-your-life.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'Daily Reading'
---

<b>COME:</b><br /><b><a href="http://www.biblestudytools.com/nkjv/matthew/passage.aspx?q=matthew+18:18-20" target="_blank">Matthew 18</a></b><br />18 Assuredly, I say to you, <b>whatever you bind on earth will be bound in heaven, and whatever you loose on earth will be loosed in heaven.</b> 19 Again I say to you that if two of you agree on earth concerning anything that they ask, it will be done for them by My Father in heaven. 20 For where two or three are gathered together in My name, I am there in the midst of them." <br /><br /><br /><a href="http://bible.cc/matthew/18-18.htm" target="_blank">International Standard Version</a>&nbsp;(©2008) "I tell you with certainty, whatever you <b>prohibit </b>on earth will have been prohibited in heaven, and whatever you <b>permit </b>on earth will have been permitted in heaven.<br /><br /><a href="http://bible.cc/matthew/18-18.htm" target="_blank">New Living Translation</a>&nbsp;(©2007) "I tell you the truth, whatever you <b>forbid </b>on earth will be forbidden in heaven, and whatever you <b>permit </b>on earth will be permitted in heaven.<br /><br /><br /><b><a href="http://www.biblestudytools.com/nkjv/job/1.html" target="_blank">Job 1</a></b><br />9 So Satan answered the Lord and said, "Does Job fear God for nothing? 10 Have You not made a hedge around him, around his household, and around all that he has on every side? You have blessed the work of his hands, and his possessions have increased in the land. 11 But now, stretch out Your hand and touch all that he has, and he will surely curse You to Your face!" 12 And the Lord said to Satan, "<b>Behold, all that he has is in your power; only do not lay a hand on his person</b>." So Satan went out from the presence of the Lord. <br /><br /><b>Behold = LOOK! Check it out!</b><br /><br /><br /><b><a href="http://www.biblestudytools.com/nkjv/genesis/1-28.html" target="_blank">Genesis 1:28</a></b><br />28 Then God blessed them, and God said to them, "Be fruitful and multiply; fill the earth and subdue it; have dominion over the fish of the sea, over the birds of the air, and over every living thing that moves on the earth."<br /><br /><b><br /></b><br /><b>HEAR:</b><br />Jesus here doing much more than giving us the keys to the Kingdom, or even offering us a way to use the Kingdom to our advantage. He is doing those things too. But I now also see a warning here. He just finished telling us how to deal with someone who is out of line in the Church. He wraps this up by telling us that what we allow will be allowed and what we forbid will be forbidden.<br /><br />In other words, we have the spiritual authority over our own lives, individually and collectively. We have been given dominion. In Genesis the foundation of&nbsp;person-hood&nbsp;was THE BLESSING. Among other things, we are given the authority, command, and responsibility to Subdue (put down things that are out of order) and have Dominion (authority of a domain).<br /><br />God will not usurp the authority He gave us. He will not override our will. He won't MAKE you get saved just because He did EVERYTHING he could do to get you there, you MUST respond in kind. So when it comes to things that are out of order in your life and heart he expects you to participate. Faith and Fear operate out of the same point of your spirit. There are opposing forces. <a href="http://www.biblestudytools.com/bbe/hebrews/11.html" target="_blank">Heb 11</a> says that Faith is substance of Hope. Opposite that Fear is substance of Negative Hope. <a href="http://bible.cc/job/3-25.htm" target="_blank">Job 3:25</a> shows us what happened to Job. He had been making sacrifices "Just in case they may have done something wrong", specifically in case they cursed God, which is something Satan had been trying to sow into his heart for years, and apparently it got it far enough that he was worried that his Kids might do it. Satan said it, Job said it, Job's wife said it... "Curse God" was the temptation involved here, because Job refused to curse God right up to the very end, God said Job didn't sin with His mouth.<br /><br />But Job DID allow fear to break down those hedges which is why God said to Satan in essence: "<i>Look you fool! You are up here complaining about hedges and they are already broken because of his fear. He's already in your hands, why are you up here talking to me about it?</i>"<br /><br />God was NOT testing Job, but he's not going to lie for him either. Jesus talked about dealing with people who were out of order in your house, church, etc. He concluded with "Bind/Loose it's up to you, not me". He will ALLOW whatever you allow.<br /><br />I've heard religious nonsense about God "Allowing something to teach you a lesson". NO! He allows what you allow, he binds what you bind. What are you allowing in your mind, heart, house, life? Are there thoughts and ideas that are contrary to the Word of God that you have allowed to stay? Are there people who need to go? Are there things, tasks, idle games, TV shows... things that are not evil, but aren't building you up... What needs to go? What have you been allowing?<br /><br /><b>DO:</b><br />Pray about complaining words, imaginations, habits, or anything else that is a hindrance to my life in God... find the things that need to be bound and let them go!<br /><br /><b>PRAYER:</b><br />Holy Spirit, show me things that need to be bound and loosed in my life. I agree to work with you to clean house!<br /><br />Darrell G. Wolfe