---
title: 'Minister and Ministry. What is it?'
date: '2012-01-08T07:34:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6150905389721288869'
blogger_filename: '/2012/01/minister-and-ministry-what-is-it.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'Prayer Time'
---

<a href="http://www.biblestudytools.com/search/?q=minister&amp;c=nt&amp;t=nkjv&amp;ps=100&amp;s=Bibles" target="_blank">MINISTER:</a><br /><br />Acts 26:16 NKJV But rise and stand on your feet; for I have appeared to you for this purpose, to make you <b>a minister and a witness</b> both of the things which you have seen and of the things which I will yet reveal to you. <br /><br />Romans 15:16 NKJV that I might be a minister of Jesus Christ to the Gentiles, <b>ministering the gospel of God</b>, that the offering of the Gentiles might be acceptable, sanctified by the Holy Spirit. <br /><br />1 Corinthians 9:13 NKJV Do you not know that those who <b>minister the holy things</b> eat of the things of the temple, and those who serve at the altar partake of the offerings of the altar? <br /><br />Ephesians 3:7 NKJV of which I became<b> a minister according to the gift of the grace of God</b> given to me by the effective working of His power. <br /><br />1 Timothy 4:6 NKJV If you instruct the brethren in these things, you will be <b>a good minister of Jesus Christ,</b> nourished in the words of faith and of the good doctrine which you have carefully followed. <br /><br />1 Peter 4:10 NKJV <b>As each one has received a gift, minister it to one another</b>, as good stewards of the manifold grace of God. <br /><br />What is a minister? Ministry? I was told once that a certain christian singer wasn't in ministry because he didn't get people saved at his concerts. Therefore he is christian entertainment not ministry. Really? Is that the definition? He may not be everything you want him to be, but I have turned to his music time and time again when I was going through things in life and found the comfort of the Holy Spirit, Encouragement, Power to move on. What is ministry then anyway?<br /><br /><b><a href="http://1828.mshaffer.com/d/search/word,minister" target="_blank">To Minister</a></b> (also the root for <a href="http://1828.mshaffer.com/d/search/word,administer" target="_blank">administer</a>):<br /><b>Noun</b><br />Properly, a chief servant; hence, an agent appointed to transact or manage business under the authority of another,&nbsp;One to whom a king or prince entrusts the direction of affairs of state,&nbsp;A magistrate; an executive officer.&nbsp;A delegate; an embassador; the representative of a sovereign at a foreign court; usually such as is resident at a foreign court, but not restricted to such.<br /><b>Verb </b><br /><b>To afford supplies; to give things needful; to supply the means of relief; to relieve.&nbsp;To give medicines.</b><br /><br /><b>Minister in the Greek here in Acts 26 is:&nbsp;<a href="http://www.biblestudytools.com/lexicons/greek/kjv/huperetes.html" target="_blank"><span style="background-color: white; color: #333333; font-family: BSTGreek; font-size: 21px;">uJphrevthß&nbsp;</span>Huperetes&nbsp;</a></b><br /><b>Definition:</b><br />"servant an underrower, subordinate rower any one who serves with hands: a servant in the NT of the officers and attendants of magistrates as -- of the officer who executes penalties of the attendants of a king, servants, retinue, the soldiers of a king, of the attendant of a synagogue of any one ministering or rendering service any one who aids another in any work an assistant of the preacher of the gospel"<br /><br />So we find here that there is no such limitation to the word minister, and therefore ministry, that only if people get saved are they ministered to. There are ministers who's ministry is primarily to the saved. How can I minister salvation to saved people? Unless there is more to it.<br /><br />Of course... there is! The Gospel is not just about getting people saved to prevent a trip to hell. That is a very shallow look at the work of Jesus. The Gospel is about restoring THE BLESSING to us. To help us to enter into the Kingdom of God and all that entails. Now of course salvation and forgiveness of sins is the entrance or door to that life. But salvation itself is about more than forgiveness from sins. You are saved from sin, sickness, demons, fear, hell, poverty, and everything else listed as a curse in Deut 28!<br /><br />So to be a minster is to administer or supply or provide relief to the people you are assigned to. Anyone operating in the dispensing of any part of THE BLESSING into someone, including the simple gift of supernatural joy is a minister and in ministry at that point.<br /><br />Do you doubt your gift has anything to do with ministry? Well financial freedom is part of THE BLESSING so if you are a banker or accountant that is your ministry. Doctor? Healing is part of THE BLESSING. Singer? Joy and Encouragement are part of THE BLESSING... there is no Godly career on earth that doesn't tie into THE BLESSING. So no matter what you are called to do by God you are a minister!<br /><br />Praise God! Darrell G. Wolfe