---
title: 'Interviews PT 2-Know the Position'
date: '2012-01-21T09:56:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8709839524867250566'
blogger_filename: '/2012/01/interviews-pt-2-know-position.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'Career'
---

<br /><h1 style="background-color: white; border-bottom-color: rgb(204, 204, 204); border-bottom-style: dotted; border-bottom-width: 1px; color: #333333; font-family: Arial, Tahoma, Verdana; font-size: 20px; font-weight: normal; line-height: 20px; margin-bottom: 10px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 5px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;">Interviews PT 2-Know the&nbsp;Position</h1><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>Knowing the Position</strong></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">You must know the position for which you are applying. I would also say that applying for a position and then declining it can begin to look bad for you if you do it over and over with the same company. You will look like a flake. Many times the employers don’t make this easy. They post job descriptions but not salary levels and you are left to fend for yourself asking: “Is this a fit for me? “</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>Narrow Your Search</strong></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">If you know what you are looking for in a job, than you will be able to weed through the countless job offers on the internet and in the&nbsp;newspaper&nbsp;more easily. You can spend your time pushing for the jobs you really want and not wasting your time on interviews for positions you won’t enjoy.</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>Research</strong></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Take time to research the positions you apply for, before applying. If you are not sure that you are a great fit, find out. There are so many tools on the internet now for understanding job descriptions and fields. Take some time to research these.</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>Network</strong></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Also, you can get to know people within the field now through social networking tools like&nbsp;<strong><a href="http://www.linkedin.com/" style="color: #008dcf; text-decoration: none;" target="_blank">Linked In</a></strong>. Ask questions, people love to talk about themselves and what they do. Do you have any&nbsp;<strong>friends</strong>&nbsp;or&nbsp;<strong>contacts</strong>&nbsp;in that field, or better yet in that company? Ask questions. Introduce yourself to the&nbsp;<strong>managers</strong>&nbsp;at the company if possible. If it’s a large company that has multiple offices don’t be afraid to just walk into one of the branches, even if it’s not the one you are thinking of working at, and&nbsp;<strong>introduce yourself to the manager</strong>, ask them if you could have a few minutes of&nbsp;their&nbsp;time. Tell them that you are thinking of coming to work for the&nbsp;company&nbsp;and that you are interested in finding out more about the inner working and what it takes.</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>Ask Good Questions</strong></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Ask good questions. “<strong>What does the day in the life of an employee of XYZ look like</strong>? What attributes make a great employee in your field? What things do people often struggle with as they first come on board? What does vacation/benefits look like?</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Think&nbsp;through the places you’ve worked, what you liked and didn’t like. Ask questions that will help you understand if this is a place you want to work. I realized recently that I prefer a company that follows a modern model for vacation, where all the house given are lumped into one box and you use them as you see fit. I was quite put out upon working for a company that still&nbsp;separated&nbsp;personal vs vacation vs sick time and punished you for using sick time when they offered it and wouldn’t let you use it for anything else or pay you out if you didn’t use it. This felt to me very double minded. I chose to leave that company and go back to a company that had a more straight forward way of dealing with time off.</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">You may have things about your personality that won’t fit certain companies or&nbsp;departments&nbsp;within a company. It would be best for you do know before you formally apply or interview that the company fits in your “<strong>Must Have’s</strong>” and “<strong>Must Not Haves</strong>‘”.</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>Details</strong></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">After you have determined that the company and position fits you, learn details about the position. Learn the shop talk. Find out terms that are used within the industry or field. The more you know about the position, and the more you know about how you can fit the position, the better. You should be able to personally relate the skills and personality traits you posses to the position.</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>Finally</strong></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Once you know the position well, and you are convinced that you would make a good fit for each other, you must know&nbsp;yourself&nbsp;well enough to convince them.</div>