---
title: 'Humility - The Power of Christian Life'
date: '2012-03-23T17:25:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3531854843036744808'
blogger_filename: '/2012/03/humility-power-of-christian-life.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Mens Meeting'
---

David, a young man at the time, came to find his brothers and give them food. His brothers made fun of him and told him to get out and go home. He saw everyone was scared. So he inquired about what was happening.<br /><br />David was told that a Giant man was threatening them and challenging them. David asked "What will be given to the man who kills this un-circumcised&nbsp;Philistine?" He goes to the king and get's&nbsp;permission&nbsp;to go. He runs out &nbsp;at the man who is taunting them and making fun of God.<br /><br />Goliath says: "I'm going to kill you!"<br /><br />David says: "No, I'm going to kill you!"<br /><br />Both of these are bold statements! But what was the source of the boldness? Why did one type of boldness fail and the other succeed?<br /><br />Goliath made his statement with confidence in his size, strength, and training. David made his statement with confidence in his God!<br /><br />So this then begs a question? What is your source? What do you trust in to put you in a place of victory. <a href="http://bible.cc/romans/12-3.htm" target="_blank">Romans 12:3</a> says that we should not think of ourselves more highly than we ought, but with sober judgment. This doesn't mean that we should put ourselves down or build ourselves up. It means that we should learn what the Word of God says about us and come into agreement with God about what HE says about us.<br /><br /><a href="http://www.biblestudytools.com/nkjv/1-peter/passage.aspx?q=1-peter+5:5-7" target="_blank">1 Peter 5:5-7</a>&nbsp;tells us that God resist the proud but gives grace to the humble. It also says that if we humble ourselves to Him that HE will exalt us!<br /><br />So this idea of humility... what does it mean for us as born again children of God? Humility is a character trait that allows us to walk with God. We throw away our own works and put on His nature and character.<br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/nkjv/philippians/2.html" target="_blank">Philippians 2 (New King James Version)</a><i>1 Therefore if there is any consolation in Christ, if any comfort of love, if any fellowship of the Spirit, if any affection and mercy, 2 fulfill my joy by being like-minded, having the same love, being of one accord, of one mind. 3 Let nothing be done through selfish ambition or conceit, but in lowliness of mind let each esteem others better than himself. 4 Let each of you look out not only for his own interests, but also for the interests of others. 5 Let this mind be in you which was also in Christ Jesus, 6 who, being in the form of God, did not consider it robbery to be equal with God, 7 but made Himself of no reputation, taking the form of a bondservant, and coming in the likeness of men. </i></blockquote>We have been made equal with God, sons of the Most High, CO-Heirs with Jesus. What a lofty thing! Yet, it was not by anything WE did, so there is no room for pride. We have this mind, that we are made the righteousness of God, yet we don't esteem ourselves better than others. Why not? Because all have fallen short of the Glory of God yet that very fact means that we all have been made the righteousness of God! <a href="http://www.biblestudytools.com/nkjv/romans/passage.aspx?q=romans+3:21-26" target="_blank">Romans 3:21-26</a>.<br /><br />We are all walking out the Grace that was given to us. We are all walking in the level of understanding we have received from Him. So we help each other up and out of the mire around us. When one of us stumbles into something we don't look down on him, we don't ask him: "Where is your faith man?!" Instead we become moved with the compassion of God for him and love him with God's love. We become dispensers of God's grace and mercy and forgiveness.<br /><br />This is walking in&nbsp;humility:<br /><br /><ol><li>Acknowledge that we are nothing in our own ability and strength.</li><li>Acknowledge that are of GREAT WORTH to Him who gave His all for us and MADE us His righteousness!&nbsp;</li><li>Acknowledge all our ability comes from and through Him!</li><li>Then take that and dispense it to others!&nbsp;</li></ol><div>Walking in humility always leads us to become God inside minded first and Others minded second. The "Self- Center" universe fades away. I am not the center of my life any more. Jesus is! When Jesus is the center of my life, the needs of others become paramount in my mind. I'm no longer thinking about what I need, what I want! I am thinking about others! I begin asking more questions in order to get to know people, rather than compromise every conversation with what I'm thinking, what I know, what I want, what I need, what I'm doing...&nbsp;</div><div><br /></div><div>The sign of Humility is NOT that I put myself down. Actually putting yourself down is still a self-focused mindset and just another side of the coin of pride.&nbsp;</div><div><br /></div><div>The sign of Humility is that I don't think of myself much at all. My words, thoughts, imaginations, and dreams are about Jesus and how he wants to impact others...&nbsp;</div><div><br /></div><div>A litmus test is a basic test to determine the quality of something in reference to Acid VS Base (Alkaline). This is a very&nbsp;layman's&nbsp;explanation. Every person who cleans pools for a living knows this test well. You drop a few drops into the pool and they turn a color. This color is compared to an indicator chart which tells you where this water falls on a scale from very Acidic to Very Alkaline. <a href="http://www.havuz.org/pool_pool/pool_maintenance/pool_chemicals/acid_soda_ash.htm" target="_blank">You simple add more acid</a> to make this water turn back to being more Acidic thereby lowering the <a href="http://en.wikipedia.org/wiki/PH" target="_blank">pH levels</a>. The acidic levels in the water help keep the pool clean from toxins and growth of plant life in the water. Often seeing green water is an indication that the pH levels are not balanced.&nbsp;</div><div><br /></div><div>The<a href="http://en.wikipedia.org/wiki/Litmus" target="_blank">&nbsp;litmus test </a>of Humility: How often do you think about you?</div><div><br /></div><div>If YOU are the center of your thoughts, prayers, hopes, dreams, desires... you probably aren't dealing with Humility. Now God is thinking about you ALL THE TIME! He's not thinking about himself, he's thinking about you! So then, being like Him, you ought to be thinking about HIM and the needs of the people he loves so much!</div><div><br /></div><div>Becoming God-Centered is not hard. Just start to fill your mind with thoughts about Him. The easiest way to do this is to start thanking Him. Thank him for anything you can think of. Start by thanking him for saving you from hell. Thank him for the trees, rocks, birds, sunshine, rain... whatever you see or think about to thank him for. You can do this for a long time without running out of things to thank Him for. As you do this you become saturated with thoughts of Him and thoughts outside of you! <a href="http://www.biblegateway.com/passage/?search=Psalm+118&amp;version=NIV" target="_blank">Psalms 118 </a>is a good place to start. Also Psalms 23 and 103!&nbsp;</div><br /><br />Thank you Jesus! Darrell G. Wolfe