---
title: 'Fear Not; Only Believe... Be not double minded.'
date: '2012-02-15T17:29:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '550522232279266435'
blogger_filename: '/2012/02/fear-not-only-believe-be-not-double.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<blockquote class="tr_bq"><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=mark+5:36&amp;t=kjv" target="_blank">Mark 5: 36&nbsp;</a><br />The English Bible, out of print Oxford Press<br /><b>"Do not be afraid; only have faith"</b><br />NKJV <b>"Do not be afraid; only&nbsp;believe"</b><br />Bible in Basic English <b>"Have no fear; only believe"</b><br />The Message <b>"Don't listen to them; just trust me"</b><br />In Luke's version of this account in the Luke 8:50 KJV "<b>Fear Not; Believe Only</b>"</blockquote><b>So simple... so profound... fear and doubt are nearly the same</b>. Doubt is not trusting. Fear is faith in the opposite reaction. Fear of a spider is faith in that spiders ability to harm you. Fear that God will not come through is faith that God will not come through. Doubt is being unsure that God will come through. Doubt is not trusting God will come through. Doubt is trust that God will not come through. Doubt says I will believe when I see it. Faith says I believe therefore I will see it!<br /><blockquote class="tr_bq"><a href="http://www.biblegateway.com/passage/?search=1+John+4%3A8&amp;version=NIV" target="_blank">1 John 4:8&nbsp;NIV</a>"Whoever does not love does not know God, because <b>God is love</b>"</blockquote><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/nkjv/james/passage.aspx?q=james+1:2-8" target="_blank">James 1:2-8</a>2 My brethren, count it all <b><u>joy</u> </b>when you fall into <b><u>various trials</u></b>, 3 knowing that the <b><u>testing </u></b>of your <b><u>faith </u></b>produces <b><u>patience</u></b>. 4 But let patience have its perfect work, that you may be <b><u>perfect and complete, lacking nothing</u></b>. 5 If any of you lacks <b><u>wisdom</u></b>, let him ask of God, who gives to all liberally and without reproach, and it will be given to him. 6<b><u> But let him ask in faith, with no doubting</u></b>, for he who doubts is like a wave of the sea driven and tossed by the wind. 7 For let not that man suppose that he will receive anything from the Lord; 8 he is a <b><u>double-minded man, unstable</u></b> in all his ways..</blockquote><blockquote class="tr_bq">"Fear sees just what man sees. Faith sees what God sees and acts upon it. Faith creates action, and people of action, like Caleb and Joshua. Instead of frustration, the joy of expectation grips us. Faith in God says 'It can be done'. Have a blessed day." REINHARD BONNKE</blockquote>God is Love. The Word of God is the Word of Love. Faith comes by hearing and hearing by the Word of Love.<br /><br />SO: Meditate on the Word of Love until you see (hope - expectation) His plans for you, which are good and not fore harm, plans for a hope and a future (Jeremiah 29:11). Then faith comes as you continue to meditate on those plans, which are in the Word of Love. Faith then gives substance to the plans of Hope as you continue to meditate them. These are not your' plans, they are God's plans. Patience then is produced as you give action to faith and put it to use. You laugh at Satan's attempts to divert you or cause you to doubt because you know that putting your faith to work produces patience, which produces "Perfect and complete lacking nothing", also known as Shalom/Peace. If there is something you are unsure about in the process you ask for wisdom without doubt, sure that He will give you the answers you need, because you meditated on the Word of Love Himself!<br /><br />... Hmmm... Good thought... Darrell G. Wolfe<br /><br />This thought has been expounded : <a href="http://n2gs.blogspot.com/2012/02/answer-to-faith-struggles-and-doubt.html" target="_blank">The Answer to faith struggles and doubt</a>