---
title: 'Miracles and The Word, believing and seeing are not equal.'
date: '2012-03-23T15:17:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3661840648581316089'
blogger_filename: '/2012/03/miracles-and-word-believing-and-seeing.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><a href="http://www.biblestudytools.com/nkjv/luke/16.html" target="_blank">Luke 16 (New King James Version)</a><br />31 But he said to him, 'If they do not hear Moses and the prophets, neither will they be persuaded though one rise from the dead.' " <br /><br /><b>HEAR:</b><br />This is an interesting verse that I've read and passed over many times. I find two interesting things about it.<br /><br /><ol><li>Jesus was&nbsp;prophesying&nbsp;his own being raised from the dead and how it won't&nbsp;persuade&nbsp;people who do not respect the Word of God (which is Jesus). Those who did not already respect God and His Word, will simply explain away the&nbsp;Resurrection&nbsp;of Jesus.&nbsp;</li><ol><li>They may explain it away by saying it didn't happen. Like the religious people of His day or many secular scholars today.</li><li>They may say He never really died.&nbsp;</li><li>They may use any number of mental gymnastics, but in the end, they will not accept the simple&nbsp;Resurrection.</li></ol><li>Faith comes by hearing, and hearing; and hearing comes by the Word of God. So seeing someone raise from the dead won't bring faith. People just find another&nbsp;explanation.&nbsp;</li></ol>They will either believe the Word or something else. The miracle attracts attention but not belief.&nbsp;Miracles&nbsp;of any kind are the dinner bell of the spirit. Miracles attract peoples attention so that they can come and hear the Word. Once their attention is attracted they will either respond in belief or unbelief. It is the Word that they respond to.<br /><br />Miracles are important. They meet the needs of people, much better than a food stamp can! They get peoples attention in order to get them to listen. They provide some proof or evidence of God's power to those who need a little something to hang on to while digesting the truth.<br /><br />But in the end, it is never a miracle that causes&nbsp;someone&nbsp;to&nbsp;believe. It is The Word of God AND their response to it.<br /><br /><b>DO:</b><br />Today I will choose to hear and believe The Word in my life. What does the Word say about me today? If it says I'm healed, then I believe it! If is says I'm rich, then I believe it! If it says I'm more than a&nbsp;conqueror, then I&nbsp;believe&nbsp;it!<br /><br /><b>PRAYER:</b><br />Holy Spirit, work in my hear through your Grace today. Help me saturate my heart with what your word says about me. Then help me take that anointing to others!<br /><br />Darrell G. Wolfe