---
title: '@ Work'
date: '2012-06-02T01:57:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5278263346689830652'
blogger_filename: '/2012/06/work.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
---

<br />Walk the Walk. That was what I heard growing up in churches. What does that mean? Unfortunately most of the people quoting that to me didn't know either, though they thought they did. They would have said that to walk to walk means, "Don't drink, don't chew, don't go with girls/guys who do", or something to that effect.<br /><br />God is far more interested in what you ought to do, than with what you ought not to do. In fact, He's not really so much&nbsp;interested&nbsp;in what you do as He is in what He's done for you already!<br /><br />Still... walking out life in the Kingdom of God is not the same as walking out life in the world. There are things we do differently, in some cases drastically differently. The following are links to articles that help with the practical side of everyday living in this world, but not of it.<br /><br /><br /><br /><br /><div style="text-align: center;"><b>@ WORK</b></div><b><br /></b><b>Career:</b><br /><ul><li><b>Interviews</b></li><ul><li><a href="http://n2gs.blogspot.com/2012/01/interview-skills-introduction.html" target="_blank">Interview Skills - An Introduction</a></li><li><a href="http://n2gs.blogspot.com/2012/01/interviews-pt-1-concrete-and-specific.html" target="_blank">Interview Skills - Pt 1 Concrete and Specific</a></li><li><a href="http://n2gs.blogspot.com/2012/01/interviews-pt-2-know-position.html" target="_blank">Interview Skills - Pt 2 Know the Position</a></li><li><a href="http://n2gs.blogspot.com/2012/01/interviews-pt-3-know-yourself.html" target="_blank">Interview Skills - Pt 3 Know Yourself</a></li></ul></ul><a href="/images/imported/blogger-googleusercontent-com/bankingbasicsforbelievers-cover-final-0e0994cf2f51.jpg" imageanchor="1" style="clear: right; float: right; margin-bottom: 1em; margin-left: 1em;"><br /></a><ul><li style="font-weight: bold;">Overcoming Attitudes:</li><ul><li><a href="http://n2gs.blogspot.com/2012/05/working-christians-battle.html" target="_blank">The Working Christians Battle</a></li><li><a class="GM1BAGKBPB" href="http://draft.blogger.com/blogger.g?blogID=1439151656287635991#editor/target=post;postID=7307660723526643007;onPublishedMenu=overview;onClosedMenu=overview;postNum=1;src=postname" style="border: 0px; color: #1155cc; cursor: pointer; font-family: Arial, Helvetica, sans-serif; font-size: 13px; margin: 0px 10px 0px 0px; padding: 0px; vertical-align: baseline;">Attitude Is Altitude</a></li></ul></ul><br /><br /><br /><br /><br /><b>I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>Darrell G. Wolfe</b><br /><a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a><br /><a href="https://www.facebook.com/n2goodsuccess?sk=wall">https://www.facebook.com/n2goodsuccess</a><br /><a href="http://empoweredtooprosper.blogspot.com/">http://empoweredtooprosper.blogspot.com/</a><br /><br /><b>See Also:</b><br />Book Suggestion from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br /><br /><b>Bulldog Publications:&nbsp;</b><br /><b><a href="http://www.amazon.com/dp/1453815619/ref=as_li_ss_til?tag=your0f4d-20&amp;camp=213381&amp;creative=390973&amp;linkCode=as4&amp;creativeASIN=1453815619&amp;adid=1NAWEWPYWDQA3XGCY7N5&amp;&amp;ref-refURL=http%3A%2F%2Fn2gs.blogspot.com%2F" target="_blank">Bankings Basics for Believers; Now Available on Amazon.&nbsp;</a></b><br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=1453815619" style="height: 240px; width: 120px;"></iframe><br /><br class="Apple-interchange-newline" />