---
title: 'The Humility of being served!'
date: '2012-01-12T05:30:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1836192741664988300'
blogger_filename: '/2012/01/the-humility-of-being-served.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><b><a href="http://www.biblestudytools.com/nkjv/matthew/passage.aspx?q=matthew+8:14-15" target="_blank">Matthew 8:14-15</a></b><br />14 Now when Jesus had come into Peter's house, He saw his wife's mother lying sick with a fever. 15 So He touched her hand, and the fever left her. And she arose and served them. <br /><br /><b>HEAR:</b><br />So often I thought of this verse from the perspective of Peter's Mom. However today I walk in the footsteps of Jesus. I am His body on this earth. I am here, called to do greater works than He did. I am His ambassador on this earth. So I must begin to see how He operated and operates today if I am to cooperate with Him in His work!<br /><br />So for the sake of exercise I take Jesus name out of the verse and replace it with my own, to gain perspective as a minister of Jesus and His Grace! When I do I find myself shocked, maybe a little horrified at first. Here I come to this&nbsp;woman's&nbsp;house. She has been laying with a fever sick in bed, not a great feeling I might add, especially before the invention of&nbsp;NyQuil! Now I come and heal her. Then I let her get up from her bed to serve me? Isn't this a little self serving pastor? You came and healed the woman just so you could get served?<br /><br />I can see it now. Aunt Nosy doing an interview for CNN: "That pastor is the most selfish thing I've ever seen. Here she was just sick near to death with this horrid fever. This pastor comes over and heals her just to make her get up and serve him. It's the worst thing I ever seen. All these pastors want is your money and service! Who do they think they are?"<br /><br />So what is the other perspective here Jesus? Service is the heart of God. Not that we serve Him, but that he serves us. Jesus didn't come to be served but to serve. No body is a better servant that God! He has a servants heart. Those of us who have been called His children have been born into that servants heart. The hardest thing you may ever have to do is not get down and wash someones feet... it's to allow your feet to be washed,&nbsp;especially&nbsp;by someone you feel is greater than you!<br /><br />When you allow someone poorer than you to sow a financial seed into your&nbsp;life, or take you out to eat, knowing that you could do more for them financially than they could ever do for you, there is a&nbsp;tendency&nbsp;to feel bad about it. But if you know the heart of God is service. If you know that the person cannot receive a harvest until they sow a seed. If you know that your life is good ground to sow into. You cannot stop their harvest by rejecting their seed. You just need to swallow your pride and allow them to sow the seed God asked them to sow. It's not about you and your pride, it's about them and the harvest God is trying to bring into their life!<br /><br />Peter's Mom wasn't just sowing seed for herself either. If you have ever met a good mom, and I'll bet you have, you'll know that they are just as concerned about their son's future as&nbsp;theirs, if not more so. Peter's Mom was sowing seed for Peter's future life and ministry.<br /><br />Now, you don't go around saying: Serve Me! Serve Me! That was the pious attitude of the Pharisees. That is a stench in the nose of God. Don't con people into serving you. But don't deny them the opportunity either. Sometimes the hardest thing for a servant to do is be served.<br /><br />As a former server at restaurants I always want to get up and do their job. Not because they aren't doing a good job, but because I have a felt need to serve. Swallow your pride and allow&nbsp;someone&nbsp;the gift of service back to you. When you can allow yourself to be served, in humility not demanding it but also not rejecting it, you are taking a great big step toward walking in the shoes of Jesus on this earth.<br /><br /><b>DO:</b><br />The next time someone wants to do something nice for me, offers me a cookie or whatever, I am gong to say yes and receive it with joy. I will BLESS that gift or act of service asking God to multiply and increase that back to them!<br /><br /><b>PRAYER:</b><br />Father, may my life be a place of good ground that others can sow into. Not so that I can have&nbsp;their&nbsp;gifts, but so that they can receive a harvest of abundance back to them!<br /><br />Darrell G. Wolfe