---
title: 'Work to Believe, not to receive!'
date: '2012-03-26T15:30:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3433818078761815614'
blogger_filename: '/2012/03/work-to-believe-not-to-receive.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/nkjv/luke/passage.aspx?q=luke+17:5-10" target="_blank">Luke 17:5-10 (New King James Version)</a>5 And the apostles said to the Lord, "Increase our faith." 6 So the Lord said, "If you have faith as a mustard seed, you can say to this mulberry tree, 'Be pulled up by the roots and be planted in the sea,' and it would obey you. 7 And which of you, having a servant plowing or tending sheep, will say to him when he has come in from the field, 'Come at once and sit down to eat'? 8 But will he not rather say to him, 'Prepare something for my supper, and gird yourself and serve me till I have eaten and drunk, and afterward you will eat and drink'? 9 Does he thank that servant because he did the things that were commanded him? I think not. 10 So likewise you, when you have done all those things which you are commanded, say, 'We are unprofitable servants. <b>We have done what was our duty to do</b>.' " </blockquote><br /><b>HEAR:</b><br />It doesn't take much faith to receive the things of God. Yet we all, at one time or another, ask God for more faith. Closely related to faith is belief. <a href="http://www.biblestudytools.com/nkjv/james/1.html" target="_blank">James </a>1&nbsp;tells us that if one asks something of God and doubts that he will not receive it, period. <a href="http://www.biblestudytools.com/nkjv/romans/passage.aspx?q=romans+10:6-9" target="_blank">Romans </a>10 tells us that we must confess (to say the same thing as) with our mouth and believe in our heart.<br /><br />So belief become this paramount issue. We know we are supposed to be healed and prosperous, so why are most of us still lacking after years of knowing this. Is the Word of God false? Is the teaching false and we miss-understood the Word? Or is there something else we have missed that was right in front of us all the time. We have the 10 steps to this and the 30 things to know about that... these are all GREAT&nbsp;materiel. But there is something simple we need in order to make these things function.<br /><br />Have you ever seen someone else&nbsp;receive&nbsp;something from God and you KNOW that they aren't doing half of the spiritual and natural things you are doing. I remember growing up I had two younger brothers. One was just three years younger than me so we often went places together in those early days. I'm guessing I would have been about 9 and he about 6 at this period in time. I was always the responsible one, I was the eldest. I did everything right (more or less). He was the one who would get into trouble just because he could. He laughed at spankings. He was a very frustrating person to be around, especially for his perfectionist older brother.<br /><br />We had each been given money to go and get something from the fast food place near our hotel this day. We sat back and considered what we wanted. I ordered what I could afford. He told the lady he wanted X and Y but didn't have money for both. She gave him the other for free. I, who was standing RIGHT THERE got nothing extra. I was so mad. Years latter that story became a parable for how he always got things and got away with things while I had to be perfect to get anything.<br /><br />Oh how&nbsp;righteous&nbsp;I was... or was I?<br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/nkjv/isaiah/64-6.html" target="_blank">Isaiah 64:6</a>6 But we are all like an unclean thing, And all our righteousnesses are like filthy rags; We all fade as a leaf, And our iniquities, like the wind, Have taken us away. </blockquote>Here we see that everything we do is not good enough. Our best works are filled with selfish intentions. Jesus is the only person who ever walked on this earth with any real righteousness. Paul said it well too. He starts by counting all of his special degrees, his classy&nbsp;heritage and pedigree, and he recounts his impressive resume. If anyone ought to have a shot at being right before God it's Saul of Tarsus (who was later re named Paul).<br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/nkjv/philippians/3-8.html" target="_blank">Philippians 3:8</a>8 Yet indeed I also count all things loss for the excellence of the knowledge of Christ Jesus my Lord, for whom I have suffered the loss of all things, and count them as <b>rubbish</b>, that I may gain Christ.</blockquote>Paul was also a Christian killer and murderer, before getting saved through a powerful encounter with the risen Jesus himself. This word "rubbish" that Paul uses is the word for "trash" or "dung" or "Poop". All of our "righteous works" or "good works" are poop!<br /><br />Notice Jesus says in Luke 17:10 that servants don't get rewards for doing their job. They just get to continue to be servants and not killed. We can't take all the good things we do: help an old lady&nbsp;across&nbsp;the street, feed the poor at shelters, go to church, read the bible, pray daily... etc... we can't take those things and hold them before God and say: LOOK I did it!<br /><br />He thinks about that the same way we look at a 4 year&nbsp;old's&nbsp;drawings. He admires them, he things they are adorable. But their not prize worthy.<br /><br />So how then do we receive from God? We believe. What do we believe? We believe that we are righteous now, not by our works but by HIS! We are righteous with Jesus' righteousness! Because of that we are pre-qualified for EVERYTHING God has for us. Not one thing we do makes us more qualified. A person who came to Jesus 2 seconds ago is just as qualified to receive from God as the person who came 20 years ago.<br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/nkjv/romans/passage.aspx?q=romans+3:17-27" target="_blank">Romans 3:22</a>21 But now the righteousness of God apart from the law is revealed, being witnessed by the Law and the Prophets, 22 even the righteousness of God, through faith in Jesus Christ, to all and on all who believe. For there is no difference; 23 for all have sinned and fall short of the glory of God, 24 being justified freely by His grace through the redemption that is in Christ Jesus...</blockquote>We ARE righteous before God through Jesus. We cannot earn His blessings. We can only believe His blessings. The secret to receiving ALL God has for us has nothing to do with doing, it has everything to do with believing!<br /><br />You know what Devin knew that I didn't know back then... He asked! He got more, because he asked for more! Amazing!<br /><br />It's time to work on Believing!<br /><br />DO:<br />Today, I will meditate (ponder, contemplate, think about, talk about, speak out loud, and imagine and dream about) the Word of God and all he says about me. I will "work" not to get, but to believe I already have!<br /><br />PRAYER:<br />Spirit of Grace, help me today, to re program my heart to believe!<br /><br /><a href="http://www.biblestudytools.com/nkjv/mark/9-23.html" target="_blank">Mark 9:23</a><br />23 Jesus said to him, "If you can believe, all things are possible to him who believes." <br /><br /><a href="http://www.biblestudytools.com/nkjv/mark/11-24.html" target="_blank">Mark 11:24</a><br />24 Therefore I say to you, whatever things you ask when you pray, believe that you receive them, and you will have them. <br /><br /><a href="http://www.biblestudytools.com/nkjv/matthew/passage.aspx?q=matthew+21:21-22" target="_blank">Matthew 21:21-22 </a><br />21 So Jesus answered and said to them, "Assuredly, I say to you, if you have faith and do not doubt, you will not only do what was done to the fig tree, but also if you say to this mountain, 'Be removed and be cast into the sea,' it will be done. 22 And whatever things you ask in prayer, believing, you will receive." <br /><br />See also:<br /><a href="http://www.kcm.org/real-help/article/now-are-we-christ-jesus">http://www.kcm.org/real-help/article/now-are-we-christ-jesus</a><br /><br /><a href="http://www.kcm.org/mp3/series">http://www.kcm.org/mp3/series</a><br /><br /><a href="http://www.impactministries.com/tabid/550/Default.aspx">http://www.impactministries.com/tabid/550/Default.aspx</a><br /><br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=0883687305" style="height: 240px; width: 120px;"></iframe> <br /><br />Darrell G. Wolfe