---
title: 'Quiet Time Results'
date: '2012-01-13T17:19:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1267590890205461388'
blogger_filename: '/2012/01/quiet-time-results.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><b><a href="http://www.biblestudytools.com/nkjv/matthew/passage.aspx?q=matthew+10:26-28" target="_blank">Matthew 10:26-27</a>&nbsp;NKJV</b><br />26 Therefore do not fear them. For there is nothing covered that will not be revealed, and hidden that will not be known. 27 "<u>Whatever I tell you in the dark, speak in the light; and what you hear in the ear, preach on the housetops. </u><br /><br /><b><a href="http://www.biblestudytools.com/gw/matthew/passage.aspx?q=matthew+10:26-27" target="_blank">Matthew 10:26-27 (GOD'S WORD Translation)</a></b><br />26 So don't be afraid of them. Nothing has been covered that will not be exposed. Whatever is secret will be made known. 27 Tell in the daylight what I say to you in the dark. Shout from the housetops what you hear whispered. <br /><br /><b>HEAR:&nbsp;</b><br />How often do I speak what's on my mind? Answer: Often! How often do I make sure that what's on my mind is the Word of God? Answer: Not often enough! How often do I stay silent unless God has spoken? Answer: Rarely!<br /><br />Many of us humans love to speak. We love to hear ourselves speak. We don't often remain silent very well. Isn't this verse asking us to speak? Yes. It's asking us to speak something very specific. What God tells you in secret or whispers in your ear.<br /><br />If 'm not spending time with Him in the dark, quiet, secret place than I won't have heard anything to say from Him.<br /><br /><b><a href="http://www.biblestudytools.com/search/?q=secret+place" target="_blank">Matthew 6:6 NKJV&nbsp;</a></b><br />But you, when you pray, go into your room, and when you have shut your door, <u>pray to your Father who is in the secret place</u>; and your Father who sees in secret will reward you openly.<br /><br /><b><a href="http://www.biblestudytools.com/nkjv/psalms/91.html" target="_blank">Psalm 91</a></b><br />1 <u>He who dwells in the secret place of the Most High</u> Shall abide under the shadow of the Almighty. <br /><br />By spending time in His secret place I hear from Him. I get to hear things in my alone time that I can proclaim loudly from the roof tops, or from space even, which is technically what I'm doing right now as the internet lives travel under and over ground and even by&nbsp;satellite.<br /><br />My secret place, lately, has been my office, at night when everyone else is asleep, or sometimes the car on the way to work. Where is your secret place? Have you spent time hearing from God? Turn off the radio, talk show, TV, Star Trek,&nbsp;Facebook, etc... Spend some time hearing from God.<br /><br />Kenneth Hagin commented that some people say: "I don't know about those people who hear from God..." His reply was "I don't know about those people who don't!" If you are not hearing from God maybe your receiver needs fixing? That is the right,&nbsp;privilege, and responsibility of the&nbsp;believer&nbsp;is to hear the Masters Voice.<br /><br /><b><a href="http://www.biblestudytools.com/nkjv/isaiah/30-21.html" target="_blank">Isaiah 30:21</a></b><br />21 Your ears shall hear a word behind you, saying, "This is the way, walk in it," Whenever you turn to the right hand Or whenever you turn to the left. <br /><br /><br /><b>DO:</b><br />I am going to make sure I spend time in the presence of God in song, study, fellowship, and prayer. Turning off the distractions around me.<br /><br /><b>PRAYER:</b><br />Holy Spirit, you are welcome hear. Come into this room and make it your&nbsp;sanctuary. Fill this room and my heart with your perceived presence. Speak to me. <a href="http://www.biblestudytools.com/nkjv/isaiah/6-8.html" target="_blank">Here I am</a>. <a href="http://www.biblestudytools.com/nkjv/1-samuel/passage.aspx?q=1-samuel+3:1-11" target="_blank">Your servant is listening</a>.<br /><br />Darrell G. Wolfe