---
title: 'GRACE - Love your neighbor and be free!'
date: '2012-01-06T16:34:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7468189511546732774'
blogger_filename: '/2012/01/grace-love-your-neighbor-and-be-free.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><b><a href="http://www.biblestudytools.com/nkjv/matthew/5.html" target="_blank">Matthew 5</a></b><br />43 "You have heard that it was said, 'You shall love your neighbor and hate your enemy.' 44<u> But I say to you, love your enemies, bless those who curse you, do good to those who hate you, and pray for those who spitefully use you and persecute you, </u>45 that you may be sons of your Father in heaven; for He makes His sun rise on the evil and on the good, and sends rain on the just and on the unjust. 46 For if you love those who love you, what reward have you? Do not even the tax collectors do the same? 47 And if you greet your brethren only, what do you do more than others? Do not even the tax collectors do so? 48 <u>Therefore you shall be perfect, just as your Father in heaven is perfect. </u><br /><br /><b>HEAR:</b><br />LOVE and GRACE. This whole chapter is demonstrating what it takes to walk in THE BLESSING. It starts out "BLESSED are those...". BLESSED means empowered to prosper. So Empowered to Prosper are those who walk in these things. Those who are poor in spirit are those who realize and acknowledge that on&nbsp;their&nbsp;own they are nothing and have nothing; therefore they rely on God's gift of Grace. By Grace I am NOT an old sinner. I WAS an old sinner but I am saved by GRACE!<br /><br />I can't be both at the same time. I am either an old sinner or I am saved. I can't be both. Through GRACE I have access to the Kingdom of Heaven, and ALL the&nbsp;resources&nbsp;that the kingdom of heaven gives me access to. This great grace is an amazing thing. I am delivered from the law and trying to walk according to it's statutes. But Darrell? Doesn't the chapter go on to tell me that the law has been enhanced and that I have a deeper obedience to the law. Not only must I love my&nbsp;neighbor&nbsp;but also my enemy? AH yes! But this isn't out of white knuckled obedience. The GRACE of God has been given to you. You are full of the Holy Spirit. The LOVE of God has been shed abroad in your heart. You walk in LOVE not out of obedience but out of your new nature. You have been made a new creation.<br /><br />How do I walk in this LOVE? I've been saved for years and I keep failing to walk in LOVE. That is because you haven't realized who you are IN HIM. When you understand the TOTAL GRACE that has been given to you all sin begins to melt away from you. When you say:&nbsp;"I'm so unworthy. I've been trying to change for years but I can't seem to. I am such a failure."&nbsp;You hear the voice of God in response to your words saying: "I'm not against you. I LOVE you. I am not holding your past, present, or future against you! Stop looking at that and start looking at my LOVE. What you look at is what you become. Look at my LOVE and become my LOVE."<br /><br />As you start to meditate on the LOVE of God for you all the other stuff melts away and you become that which you behold. You become perfect as The Father is perfect!<br /><br /><b>DO:</b><br />Find every place the bible talks about LOVE, IN HIM, IN WHOM, IN CHRIST and meditate on these. This will radically change your life. Get Kenneth Hagins mini book "In Him". Listen to Joseph Prince, he majors on Grace. Meditate on this until the LOVE of God for you is bigger than anything else in your mind, heart, or life. Until you're immediate response to sin is GRACE! When that happens you won't to things to harm others or judge them. You will dispense GRACE to them, just as your Father in heaven does.<br /><br /><b>PRAYER:</b><br />Thank you for your GRACE, Father. Blow up that GRACE in my heart. May I be like you!<br /><br />Darrell G. Wolfe