---
title: 'How do I stay focused?'
date: '2012-01-04T21:56:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7582540930517577644'
blogger_filename: '/2012/01/how-do-i-stay-focused.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Prayer Time'
---

I had a question for God in my prayer time. I find myself focused from time to time and then scattered to too many things at once. I get scattered un-focused and then loose momentum on everything. Eventually I give up on all of it for a time and start from scratch. SO...<br /><br /><b>How do I focus and deal with long term and short term goals without expending mental energy on too many things at once, short&nbsp;circuiting&nbsp;my whole program?</b><br /><br />Here is the reply I got immediately in prayer:<br /><br /><br /><ol><li><b>Write out each goal, big or small, separately. Place all the details you know and organize each in the same written format for ease of reading through.&nbsp;Separate&nbsp;paper for each goal.&nbsp;</b></li><li><b>Create&nbsp;separate&nbsp;folders for active, standby, and completed projects. Place the goals in each folder respectively. In my case I have three blogs I write on actively, or should be, so those would go in "Active". I have a restaurant I want to start someday. I may do research on that from time to time, but that is a future project that would go in "Standby"&nbsp;</b></li><li><b>Review these folders/goals often. Confess the Word of them and pray over them daily.&nbsp;</b></li><ol><li><b>Add to each goal as information or instruction comes, as you receive it. But then go back to steps 1-3. Don't get wrapped up in or consumed by this new information. Treat it like <a href="http://www.biblestudytools.com/search/?q=mary+pondered" target="_blank">Mary </a>did, ponder these things in your heart.&nbsp;</b></li></ol><li><b>REST! Know that I am God!</b></li></ol><div>You only DO what I say do. Roll the care of "HOW" and "WHEN" over onto me. "When" is not a question you should be asking because FAITH IS NOW! Call them done now! Remember THE BLESSING it makes rich without sorrow. If you feel you are toiling you are doing it wrong. The faith life is productive without toil. Go back to steps 1-4.&nbsp;</div><div><br /></div><div>Darrell G. Wolfe</div><br /><br /><br /><br />