---
title: 'Replace old programs... daily renewing and rewiring.'
date: '2012-01-24T07:26:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8955840266155928642'
blogger_filename: '/2012/01/replace-old-programs-daily-renewing-and_23.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<br />Today on Facebook<a href="http://www.facebook.com/olgahermans" target="_blank"> Olga Hermans</a>&nbsp;posted a link to her latest blog post from <a href="http://www.thechoicedrivenlife.com/daily-choice#comment-4546" target="_blank">TheChoiceDrivenLife.Com</a>:<br /><br />‎"Successful people do 'daily' what others do 'occassionally'."<a href="http://www.thewisdomcenter.tv/AboutUs/MeetThePastoralTeam/tabid/2542/Default.aspx" target="_blank"> Mike Murdock</a><br /><br />What a thought. The difference isn't knowing some secret, or being pre-wealthy. It isn't the right circumstance. It's not a big outbreak or breakthrough. It's just doing the right thing for long enough to see the result. Like the flywheel effect described in <a href="http://www.amazon.com/Good-Great-Companies-Leap-Others/dp/0066620996" target="_blank">Good to Great</a>. Just keep pushing the big heavy wheel and eventually little movements add up until it hits a breakthrough momentum. However if you push for awhile, get tired, then try the other way, that only produces canceled results.<br /><br /><a href="http://scottjallen.com/?p=1371" target="_blank">Scott Allen</a> posted today a Pixar tweet: "Go Ahead, Accept a Challenge."<br /><br />My thoughts:<br /><br />Challenge the things that have been staring you in the face and staring you down. Has debt, or lack of the money to do what you think you need to do been challenging your belief? Have you been wondering if God Can? If God Will? If you can receive? Or having any other thought of defeat?<br /><br />Sometimes in life there are things that attempt to suffocate the Word in your heart and make it fruitless/cause it to come to no real effect.<br /><br />These are the times that you lock yourself in your closet, or somewhere to pray, and you start to confess the Word and Pray until you come out with the right attitude. Your outlook is&nbsp;changeable&nbsp;by you. You control your emotions by&nbsp;controlling&nbsp;what you are saying to yourself. If you've never taken the time to ask God to show you the broken record or self dialogue that has been going on and on in the back of your mind, do it! It's quite revealing. Lies the devil sold you that you didn't even know were playing back there, many have been there so long you didn't&nbsp;recognize&nbsp;them, but they are&nbsp;ruling&nbsp;your thought life and emotions.<br /><br />I liken these thoughts to base code on a computer. There are codes and programs that run all the time on most computers that you don't know are there, you can't see them running. There is no logo, icon, window or any indication that they are there. But they are slowing down your processor and gumming up your computer. Sometimes these are even harmful programs that came attached to some other program you downloaded. This is why having a computer person check you computer every so often is needful. Checking what runs at start up is important. It causes start up to be slower and constantly running code slows the computer.<br /><br />The thoughts that are so base to your personality that they cause your reactions to situations and gut responses, those thoughts must be brought in line with the Word of God. Only through prayer will you be able to flush those out and meditating on The Word of God will replace them. You need a high level program to turn off and replace those other programs.<br /><br />Then you need to do this daily, by daily repetition of Meditating on the Word of God, and then daily doing the tasks you are assigned by him, you can replace your unproductive thoughts,&nbsp;habits, and ideas, with new ones.<br /><br />Also by daily getting little bits done toward projects you get the projects done. Books are written in an afternoon, it takes line by line, paragraph by paragraph.<br /><br />Take time today to replace the old programs running around in your head...<br /><br />Darrell G. Wolfe