---
title: 'You&#39;re Not Broke You Have A Seed!'
date: '2012-02-19T22:39:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5544956678306700127'
blogger_filename: '/2012/02/you-not-broke-you-have-seed.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Prosperity'
  - 'Keys To Success'
  - 'Books'
  - 'Quotes and Sayings'
---

Highlights from the Book:&nbsp;<a href="http://www.amazon.com/Youre-Not-Broke-Have-Seed/dp/0963258486" target="_blank">You're Not Broke You Have A Seed!</a><br /><br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=0963258486" style="height: 240px; width: 120px;"></iframe> <br /><br />I had this book on my shelf, read it in 2007 without much thought about it. Made a few notes, highlighted some things. Lately I have really struggled with taking my life vision and ministry work to a new level... I'm just not satisfied working at a "J.O.B." anymore. I got too lazy and willing to let that be enough. I tried several jobs. But now God is showing me that although he may continue to use the J.O.B. for now, it's not the end all and I need to remember that. I guess I let that slip somewhere along the way. Ultimately God wants to use the job as a place to obtain seed, not the place to meet your need. GOD is your provider, not your job. When the job becomes your provider you are tempted to do or say things that are not totally in line with God's Word to "perform". Pressure mounts to say something a certain way to get a sale, when that isn't the full and honest truth. Something simple, like having a good idea and personalizing it with a story that didn't actually happen, just to get the point&nbsp;across. That may be common in the sales world, but it is a LIE! You must be cautious not to jump from example of what could be to saying it had been.<br /><br />So here are some things that stood out to me from the book. Some are notes I made for myself and some are direct quotes from the book.<br /><blockquote class="tr_bq">"Therefore, God protects His children from money until we understand that we are not to be the servant of money; rather, money is to be our servant... We have to let the Holy Ghost escort us into the wealth of God."</blockquote><blockquote class="tr_bq">"I'm not broke; I have a seed!"</blockquote><blockquote class="tr_bq">"To some people&nbsp;seed-time&nbsp;is a sad time when it should be a shouting time. You can sow your way out, but God is not going to let you work your way out by jobs. If you work your way out, you will not have the grace you need to maintain your walk with God."&nbsp;</blockquote><blockquote class="tr_bq">&nbsp;"God is ministering to you so do not take it lightly. The Holy Spirit is producing some things in your life, and when He is finished, even your own family will not know you." Notated and confirmed 02/10/2012 and 07/16/2007"</blockquote><blockquote>&nbsp;"The Lord told Isaac, 'I am going to do this for you, and you don't have to leave this land to prosper.' Nor do we have to leave our physical location; the only thing we have to do is learn how to operate properly in the Spirit... You have to move in revelation, not in position, and the rest will take care of itself."</blockquote><blockquote class="tr_bq">"A famine is when you may have a good job, but you're barely keeping up with your bills."</blockquote><blockquote class="tr_bq">"Who is a sower? A sower is one who is operating under stewardship. What I have is not really mind. I am in management for Someone Else, and whatever He tells me to do with whatever I have I am willing to do it."</blockquote><blockquote class="tr_bq">&nbsp;"When I say 'eating your seed' I am talking about buying something to appease the prosperity that is in you. However, you have to sow your way to the prosperity that belongs to you."</blockquote><blockquote class="tr_bq">"The job is not God's way. The job is not to make a living, it is to get seed so you can sow for a living. Some say, 'If I can only get a good job. The job I have now is not a good job. The pay isn't enough'"</blockquote><blockquote class="tr_bq">&nbsp;"When you got on God's system properly, you don't need a budget. A budget is merely to stop you from overspending, but when you get into the system (God's System) you can't overspend. Now until you get out of the system (The Worlds System), you will have to budget yourself... You can plant a financial seed but if you let words come out the wrong way, you will uproot the seed wit the words of your mouth."</blockquote>Words are your primary seed. Money just activates your words. So does anythings you sow (Time, Talent, and Treasures are all seed). Remember, Money is not Good or Bad, it only amplifies and expresses the heart.<br /><br /><blockquote class="tr_bq">"Expectation that cannot be killed is&nbsp;expectation&nbsp;that cannot be denied. You have to have&nbsp;expectation!... Once you have planted the seed, go to sleep. "Thou will keep him in perfect peace, whose mind is stayed on the Thee" Isaiah 26:3) "Trust in the Lord with all thine heart, and lean not unto thine own understanding" (Proverbs 3:5) Build up your expectation and go to sleep. In other words, plant your seed, then go about your Father's business, praising the Lord <i>(For you are calling it down NOW not when you see it)</i></blockquote><br /><br />Referring to Luke 5:6<br /><br /><blockquote class="tr_bq">The ship did not run over and the net did not break until they obeyed...</blockquote><br />Kenneth Copeland has also said that: "the only reason the net broke is because Peter threw out one net, the old worn out one, because he'd just cleaned all his good nets. He was just trying to humor the preacher, he wasn't expecting anything to happen."<br /><br />It's comforting to know that God isn't trying to keep His blessing from us, but he's trying to get us to do the least bit to move toward Him so that he can legally get it to us! Peter's latter catch when Jesus told him to put out nets after His&nbsp;Resurrection&nbsp;was a REAL harvest!<br /><br />Isaiah 55:10-11 rain gives seed which gives more seed and bread! The Word gives seed and bread!<br /><br /><blockquote class="tr_bq">My check is not my source. You have to come to that conclusion, if not, when famine comes, you will be just like other people... So, as you are reading this, God is aiming to make you switch masters.</blockquote><blockquote class="tr_bq">The key to operating God's Law and to avoid frustration and the temptation to quit is to understand that with God there is an appointed time and due season for everything.&nbsp;</blockquote><blockquote class="tr_bq">Whatever you have now, whatever He says to you to do with it, do it, and you will jump systems.&nbsp;</blockquote><br /><br /><a href="http://www.biblestudytools.com/nkjv/1-thessalonians/5-16.html" target="_blank">1 Thessalonians 5:16 Rejoice always</a><br /><br /><blockquote class="tr_bq">The key to standing tall between "I believe" and "There it is" is Rejoice always! Rejoice means to brighten up, spin around, and leap! Don't be looking at bills all day long. Look at the Bible, look at what God has Promised!&nbsp;</blockquote>Keys to receiving your Due Season:<br /><br /><ol><li>Honor the Lord</li><li>Speak to your seed</li><li>Speak to your mountain (Debt, Lack, Etc)</li><li>Be Aggressive</li></ol><div>Remember this:</div><div><br /></div><div>We Must disconnect the DO from the GET.&nbsp;</div><div><br /></div><div>Your Job is NOT your source.&nbsp;</div><div><br /></div><div>As long as your job is your source, God can't be. He won't take second place. Make up in your mind right now, that your JOB is a place God has brought you to get seed and bread as you switch systems. In God's system you are always called to "DO" things, because we find our greatest enjoyment in providing for others. Your DOING is for the benefit of others.&nbsp;</div><div><br /></div><div>However your DOING is NOT tied to your&nbsp;RECEIVING. Just because God calls you to be an author, doesn't mean you will make an income from your books/blog/etc. God may ask you to SOW all of that and bring income to you a million other ways.&nbsp;</div><div><br /></div><div>You DO because it's your call to DO, don't concern yourself with how you will monetize it. Just do what you do, and allow God to bless you with income beyond your ability to produce. As far as God is concerned He could have you wake up to Gold nuggets on your kitchen floor every morning, like manna in the wilderness.&nbsp;</div><div><br /></div><div>He could bring you money and income from many places you've never thought of. He isn't concerned about YOU MAKING ENOUGH. Just DO what He says DO, God will be the one who brings you the income and resources.&nbsp;</div><br /><br />That is the end of my notes on the book! I suggest you buy a copy yourself and keep it in your library. It was a good faith stretcher.<br /><br />Darrell G. Wolfe