---
title: 'GRACE - Judgment Free'
date: '2012-01-11T05:30:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6751325077021238266'
blogger_filename: '/2012/01/grace-judgment-free.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><a href="http://www.biblestudytools.com/nkjv/matthew/passage.aspx?q=matthew+7:1-5" target="_blank">Matthew 7:1-5</a><br />1 "Judge not, that you be not judged. 2 For with what judgment you judge, you will be judged; and with the measure you use, it will be measured back to you. 3 And why do you look at the speck in your brother's eye, but do not consider the plank in your own eye? 4 Or how can you say to your brother, 'Let me remove the speck from your eye'; and look, a plank is in your own eye? 5 Hypocrite! First remove the plank from your own eye, and then you will see clearly to remove the speck from your brother's eye. <br /><br /><b>HEAR:</b><br />How can you remove the plank from your own eye? And how can you help a brother with his speck? Isn't any attempt to do either an act of judgment and works? How can you, an imperfect person help another imperfect person with anything? Jesus is saying here that no matter what you want to help someone with you are guilty of greater!<br /><br />How many times have I seen&nbsp;religious people try to talk to someone, or myself, about being holier and getting our walk straight! Some had good intentions and some did not. Some were just trying to walk better and some were so steeped in religious bondage that all they could do was carry a verbal whip. I think of&nbsp;organisations&nbsp;like the one I ran into in college that trick you into coming to a church group and then begin to&nbsp;interrogate&nbsp;you and tell you that if you weren't&nbsp;baptized&nbsp;in water in their church you are&nbsp;going&nbsp;to hell.<br /><br />So what's up Jesus? How do I remove my plank? How can I honestly help anyone with their speck?<br /><br />GRACE! It is through GREAT GRACE! I don't judge because sin has already been judged! Jesus bore the judgment for all sin that ever was or will be. Not one person on this planet is going to hell because of their sin. Am I saying that no one is going to hell? No. That's not what I'm saying. The only sin that anyone will go to hell over is rejecting Jesus' free gift! Choosing to stand before God on their own works rather than take the trade Jesus offered.<br /><br />What does that mean for those of us who have accepted Jesus? We have no sin. That doesn't mean we don't sin from time to time. But I have news for you. Jesus died and rose before you were born. That means all your sin was future to Him. That means he died for all your sin on the cross. That means that the sin you haven't&nbsp;committed&nbsp;yet is already cleansed! Therefore... you have no sin. You can walk TOTALLY free. God the Father loves you and is proud of you. He is for you.<br /><br />What does that mean for those who haven't accepted Jesus? They have no sin. What?!?! Yes, until they stand before Jesus they have no sin. They still have time to accept or reject Him. We treat the sinner with the same Grace that we treat the believer! I have nothing to say about your works, good or bad. If you choose to be a sinner I have nothing but love and grace for you! That's how Jesus could eat with sinners and still be righteous. He already paid the price in His mind for them. The price He was about to pay made them clean. He didn't see them for what they were doing, He saw them for what He was going to do!<br /><br />What GRACE!<br /><br /><b>DO:</b><br />I will treat all people with the same GRACE that Jesus treats me. In that LOVE for them, perhaps, some will come to Him through my life and example.<br /><br /><b>PRAYER:</b><br />Father, use my life! BLESS me so&nbsp;extravagantly&nbsp;that people of all walks have to ask: How do I get to know your God! I&nbsp;yield&nbsp;myself to you, use me, use my life!<br /><br />Darrell G. Wolfe