---
title: 'Faith is a Response'
date: '2012-06-27T14:35:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3384523054623069729'
blogger_filename: '/2012/06/faith-is-response.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<h2 style="text-align: center;"> Faith is a Response</h2><h4><span style="background-color: white;">COME:</span></h4><a href="http://www.biblestudytools.com/nkjv/romans/11.html" style="background-color: white;" target="_blank">Romans 11</a><br /><blockquote class="tr_bq"><i>5 Even so then, at this present time there is a remnant according to the election of grace. 6 And if by grace, then it is no longer of works; otherwise grace is no longer grace. But if it is of works, it is no longer grace; otherwise work is no longer work. 7 What then? Israel has not obtained what it seeks; but the elect have obtained it, and the rest were blinded. 8 Just as it is written: "God has given them a spirit of stupor, Eyes that they should not see And ears that they should not hear, To this very day." 9 And David says: "Let their table become a snare and a trap, A stumbling block and a recompense to them. 10 Let their eyes be darkened, so that they do not see, And bow down their back always." 11 I say then, have they stumbled that they should fall? Certainly not! But through their fall, to provoke them to jealousy, salvation has come to the Gentiles.<br />  </i><i><br /></i><i></i><i>20 Well said. Because of unbelief they were broken off, and you stand by faith. Do not be haughty, but fear. 21 For if God did not spare the natural branches, He may not spare you either.<br />  </i><i><br /></i><i></i><i></i><i>32 For God has committed them all to disobedience, that He might have mercy on all. 33 Oh, the depth of the riches both of the wisdom and knowledge of God! How unsearchable are His judgments and His ways past finding out!  </i></blockquote><h4> <span style="background-color: white;">HEAR:</span></h4>As I ponder this Chapter, home of so much debate between strict&nbsp;Calvinists&nbsp;and the rest of the Church, I ponder our friend Israel. We can be sure through reading this chapter that God is not through with Israel. The Word says here that much of Israel was cut off and blinded. God turned them over to see but not see and hear but not hear. I can see how a person could get the idea that God had actively done this to them.<br /><br />Then we read further and we see the real reason they were cut off.&nbsp;Unbelief. It was their own refusal to believe that cut them off and blinded them. God gave us a choice in <a href="http://bible.cc/deuteronomy/30-19.htm" target="_blank">Deut 30:19</a>, Life or Death: Your Choice! That means that it's not God's choice whether you believe or doubt, get saved or go to hell, get healed or die sick... It's yours. Will you believe or not?<br /><br />God clearly isn't done with Israel. He's brought them back into being as a nation and he's playing out the end times scenario in which they will play the central role. In fact, we are merely here during their Pause. He placed the nation on a type of Time Out. He's been dealing with them the whole time, but he has a specific plan he's working out.<br /><br /><a href="http://www.biblestudytools.com/nkjv/romans/11.html" style="background-color: white;" target="_blank">Romans 11</a><br /><blockquote class="tr_bq"><i>25 For I do not desire, brethren, that you should be ignorant of this mystery, lest you should be wise in your own opinion, that blindness in part has happened to Israel until the fullness of the Gentiles has come in. </i></blockquote>We, the Gentiles, are merely here during this time of Grace between Jesus coming and the time when the last 7 weeks of Daniel is poured out. Let us not think that time in Daniel is about Judging Israel either, no, it's about saving them! Israel will come to believe on Jesus during that time as a nation.<br /><br />So what does all this mean to us? To me? Am I guilty of unbelief? Have I spent so much time in Church, religious&nbsp;circles and meetings that I don't believe? Sure I&nbsp;believe&nbsp;in Jesus. I believe He died and rose again. I believe He is my Savior and Lord. I believe He paid for my deliverance from sin, sickness, demons, and fear. I believe that by His strips I've been healed from every sickness, disease, and injury that will ever try to come against me. I believe that He has paid for my provision and that My God is meetings all of my needs, wants, and desires according to His Riches in Christ Jesus!<br /><br />But when the sickness comes on me, when finances misbehave... what is my response? Faith is a response. If I walk into a room and slap you on the back and say: "<i>Hey man! I believe that!"</i> But you haven't said anything to me yet. It's out of context! I can't have faith in what you say, until you say something to have faith in. So when finances go out of whack... what is my response. If I say I have faith that Jesus paid for my provision but I respond to the lack in fear or doubt... My faith is dead.<br /><br />I've been cut off from The BLESSING. I may believe all those things with my head. I may very well be saved and going to heaven. But I'm not living out any of the benefits (<a href="http://draft.blogger.com/"><span id="goog_796569958"></span>Psalms 103<span id="goog_796569959"></span></a>) that come with being in Covenant with Jesus.<br /><br />Faith is so simple, that only a&nbsp;religious&nbsp;person could mess it up! Talk to God, Hear God, Respond!<br /><h4>DO:</h4><span style="background-color: white;">I must choose my&nbsp;response&nbsp;to thoughts, emotions, and situations today. The best trained&nbsp;professionals&nbsp;in any field are trained over and over, so that when faced with a real situation they will respond appropriately. Athletes, Medics, Martial Artists... They all train in order to respond.&nbsp;</span><br /><br />I will choose to respond in Faith today. How will I train myself to do this?<br /><br /><ol><li><b style="background-color: white;">PRAY:</b><span style="background-color: white;"> Faith is a response. Hear the spoken, as well as written, Word of God for my life.&nbsp;</span></li><li><b style="background-color: white;">Rehearse</b><span style="background-color: white;">: Consider situations that I've had trouble responding in faith to in the past, and rehearse, just like an actor, a different response.</span></li><li><b>Imagine</b>: Create a movie inside of my mind of my responding in faith and getting the results God promises in His Word!&nbsp;</li><li><b>Catch Myself</b>: When I say something that is not of faith. Correct the response and behavior while reaffirming and reminding myself of who I am IN HIM.&nbsp; </li><li><b>Follow Through</b>: When situations arise that are contrary to me, respond in faith. When I don't correct the response as soon as I am able.&nbsp;</li></ol><br /><br /><h4>PRAY:</h4><b style="background-color: white;">PRAY:</b><span style="background-color: white;">&nbsp;Faith is a response. Hear the spoken, as well as written, Word of God for my life.&nbsp;</span><br /><br />Father, HELP! Emotions should not dictate to me how I respond to life. Help me see things from Your perspective. Help me calm down, be still, know that YOU are God, and Listen for what you would say to me... then respond.<br /><br /><br /><br /><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><br /><b>Darrell G. Wolfe</b><br /><a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a><br /><a href="https://www.facebook.com/n2goodsuccess?sk=wall">https://www.facebook.com/n2goodsuccess</a><br /><br /><a href="http://empoweredtooprosper.blogspot.com/">http://empoweredtooprosper.blogspot.com/</a><br /><a href="https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118">https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118</a><br /><br /><b>See Also:</b><br />Book Suggestion from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br /><br /><b>Bulldog Publications:&nbsp;</b><br /><b><a href="http://www.amazon.com/dp/1453815619/ref=as_li_ss_til?tag=your0f4d-20&amp;camp=213381&amp;creative=390973&amp;linkCode=as4&amp;creativeASIN=1453815619&amp;adid=1NAWEWPYWDQA3XGCY7N5&amp;&amp;ref-refURL=http%3A%2F%2Fn2gs.blogspot.com%2F" target="_blank">Bankings Basics for Believers; Now Available on Amazon.&nbsp;</a></b><br />Print&nbsp;Edition<br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=1453815619" style="height: 240px; width: 120px;"></iframe><br /><br />Kindle Edition<br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=B008EO488Y" style="height: 240px; width: 120px;"></iframe><br /><br /><br /><br /><br /><br /><br /><br />