---
title: 'The Day of Christ’s Return Part 1'
date: '2012-01-21T09:44:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2246429609710177796'
blogger_filename: '/2012/01/the-day-of-christs-return-part-1.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'Prophecy'
---

<br /><h1 style="background-color: white; border-bottom-color: rgb(204, 204, 204); border-bottom-style: dotted; border-bottom-width: 1px; color: #333333; font-family: Arial, Tahoma, Verdana; font-size: 20px; font-weight: normal; line-height: 20px; margin-bottom: 10px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 5px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;"> The Day of Christ’s Return Part&nbsp;1</h1><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">The day of the return of Jesus Christ may be one of the most intriguing parts of living the Christian Life. For those who believe that He came, died, rose again, left the Holy Spirit with us, and is coming again for us… we live in constant expectation of His return. We may allow it to fall from the front of our mind, but we easily recall it at a moments notice!</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Many, most, would say that we simply cannot know the date. They point to two concepts found in a few scriptures and say that it is a settled matter. I am not so sure. I am now seeing this from a new point of view, one I did not hold two years ago. There have been many false prophets, some had good intentions some did not, which have made false claims, one of them will proved wrong today in fact. But let’s examine the details of this topic. It is interesting.</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Item One: No man knows the day or hour</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Item Two: He will come like a thief in the night. (Indicating that he will not be expected.)</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Item Three (Really built into item Two): That he will come when we think not (also indicating that we won’t be expecting him).</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">What are the scriptures people point to?</div><ol start="1" style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong><a href="http://www.biblegateway.com/passage/?search=Matthew+24:36&amp;version=KJV" style="color: #008dcf; text-decoration: none;">Matthew 24:36</a></strong><br />But of that day and hour&nbsp;<strong>know</strong>eth&nbsp;<strong>no</strong>&nbsp;<strong>man</strong>,&nbsp;<strong>no</strong>,&nbsp;<strong>no</strong>t the angels of heaven, but my Father only.</li><li style="margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Matthew24:<sup>44</sup>Therefore be ye also ready: for in such an hour<strong>&nbsp;as ye think not</strong>&nbsp;the Son of man cometh.<br /><a href="http://www.biblegateway.com/passage/?search=Matthew+24:35-37&amp;version=KJV" style="color: #008dcf; text-decoration: none;">Matthew 24:35-37</a>&nbsp;(in Context)&nbsp;<a href="http://www.biblegateway.com/passage/?search=Matthew+24&amp;version=KJV" style="color: #008dcf; text-decoration: none;">Matthew 24</a>&nbsp;(Whole Chapter)</li><li style="margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong><a href="http://www.biblegateway.com/passage/?search=Matthew+25:13&amp;version=KJV" style="color: #008dcf; text-decoration: none;">Matthew 25:13</a></strong><br />Watch therefore, for ye&nbsp;<strong>know</strong>&nbsp;neither the day&nbsp;<strong>no</strong>r the hour wherein the Son of&nbsp;<strong>man</strong>&nbsp;cometh.<br /><a href="http://www.biblegateway.com/passage/?search=Matthew+25:12-14&amp;version=KJV" style="color: #008dcf; text-decoration: none;">Matthew 25:12-14</a>&nbsp;(in Context)&nbsp;<a href="http://www.biblegateway.com/passage/?search=Matthew+25&amp;version=KJV" style="color: #008dcf; text-decoration: none;">Matthew 25</a>&nbsp;(Whole Chapter)</li><li style="margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong><a href="http://www.biblegateway.com/passage/?search=Mark+13:32&amp;version=KJV" style="color: #008dcf; text-decoration: none;">Mark 13:32</a></strong><br />But of that day and that hour&nbsp;<strong>know</strong>eth&nbsp;<strong>no</strong>&nbsp;<strong>man</strong>,&nbsp;<strong>no</strong>,&nbsp;<strong>no</strong>t the angels which are in heaven, neither the Son, but the Father.<br /><a href="http://www.biblegateway.com/passage/?search=Mark+13:31-33&amp;version=KJV" style="color: #008dcf; text-decoration: none;">Mark 13:31-33</a>&nbsp;(in Context)&nbsp;<a href="http://www.biblegateway.com/passage/?search=Mark+13&amp;version=KJV" style="color: #008dcf; text-decoration: none;">Mark 13</a>&nbsp;(Whole Chapter)</li><li style="margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong><a href="http://www.biblegateway.com/passage/?search=1%20Thessalonians+5:2&amp;version=KJ21" style="color: #008dcf; text-decoration: none;">1 Thessalonians 5:2</a></strong><br />For you yourselves know perfectly that the Day of the Lord so cometh as a&nbsp;<strong>thief in</strong>&nbsp;the night.<br /><a href="http://www.biblegateway.com/passage/?search=1%20Thessalonians+5:1-3&amp;version=KJ21" style="color: #008dcf; text-decoration: none;">1 Thessalonians 5:1-3</a>&nbsp;(in Context)&nbsp;<a href="http://www.biblegateway.com/passage/?search=1%20Thessalonians+5&amp;version=KJ21" style="color: #008dcf; text-decoration: none;">1 Thessalonians 5</a>&nbsp;(Whole Chapter)</li><li style="margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong><a href="http://www.biblegateway.com/passage/?search=2%20Peter+3:10&amp;version=KJ21" style="color: #008dcf; text-decoration: none;">2 Peter 3:10</a></strong><br />But the Day of the Lord will come as a&nbsp;<strong>thief in</strong>&nbsp;the night, in which the heavens shall pass away with a great noise, and the elements shall melt with fervent heat. The earth also and the works that are therein shall be burned up.<br /><a href="http://www.biblegateway.com/passage/?search=2%20Peter+3:9-11&amp;version=KJ21" style="color: #008dcf; text-decoration: none;">2 Peter 3:9-11</a>&nbsp;(in Context)&nbsp;<a href="http://www.biblegateway.com/passage/?search=2%20Peter+3&amp;version=KJ21" style="color: #008dcf; text-decoration: none;">2 Peter 3</a>&nbsp;(Whole Chapter)</li></ol><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">I submit that the common understanding of these scriptures may not be the correct understanding.</div>