---
title: 'When Truth Comes...   It can take a few passes.'
date: '2012-04-10T15:52:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7088079327659366785'
blogger_filename: '/2012/04/when-truth-comes-it-can-take-few-passes.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

I'm reading <a href="http://www.biblestudytools.com/nkjv/john/4.html" target="_blank">John 4</a>. The whole chapter.<br /><br />Jesus comes talking to a Samaritan woman.&nbsp;Samaritans&nbsp;were considered half breeds between Jews and those who&nbsp;conquered&nbsp;Israel over the years. They wouldn't even drink out of the same pot. It was not dissimilar to the Blacks and Whites of the historic southern USA. There are still pockets of&nbsp;separation&nbsp;to this day in certain areas of the south.&nbsp;Jesus came talking to the woman, his disciples were surprised to see it when they came but they chose wisely to keep their mouth shut. Jesus knew, as all rational and spiritual men do, that all race&nbsp;separation&nbsp;is nothing but a tool of Satan to create distrust. It is when men work together, in God, that things really get done that better man's life and prosperity.<br /><br />You see her religious nature when Jesus begins talking with her. He gives her a spiritual truth (living water) and she responds with a natural response (are you greater than our prophet?). He responds with a Word of Knowledge (a gift of the Holy Spirit) and she responds with a&nbsp;religious&nbsp;debate over places of worship.<br /><br />The same thing happens today. You tell someone that it is God's will to heal them and they start debating about someone they knew that believed for healing and didn't make it. Or you tell someone about God's love for them and they ask about evolution, or my personal favorite: "Can God make a rock so heavy that He can't lift it?"<br /><br />She ends the debate with saying that Messiah will come and settle the debate. People usually do this today by saying: Let's agree to disagree... or we'll see when Jesus comes back who was right... Jesus settles her debate. "I AM He." She is left to wonder about the whole thing and goes and tells the people.<br /><br />When Jesus is revealed it settles all debate. She goes and tells people and they come. Eventually they tell her that they no longer believe because of her word but because they heard for&nbsp;themselves.<br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/nkjv/john/4.html" target="_blank">John 4<br /> </a>42 Then they said to the woman, "Now we believe, not because of what you said, for we ourselves have heard Him and we know that this is indeed the Christ, the Savior of the world." </blockquote>This is the crux of the deal. We have heard Him ourselves. This is the end all. When people finally overcome all their objections and hear the Word of God for themselves... they hear the voice of God speak in them while the read the Word or while they listen to a message. When they take the initiative to come and hear without being spoon fed by others. Then the Word of God starts to become real to them and they believe. THIS is the point that real change begins to happen for people.<br /><br />Unfortunately there is no formula. There is no recipe that says after X amount of times and after saying XY amount of scriptures they'll believe. People respond as they respond. The important thing is to&nbsp;respond&nbsp;to them with the same things Jesus used. What did Jesus use in his conversation with the woman?<br /><br />Jesus used:<br /><br /><ul><li>The message of the Gospel - Living Water</li><li>The Gifts of the Spirit - 1 Corinthians 12 a Word of Knowledge</li><li>He revealed that He was the Anointed One - So must we reveal that He is the Anointed One.</li><li>He ministered to the people. He gave them words and actions.&nbsp;</li></ul><div>Jesus obviously didn't just pick this at Random. He was praying that morning as He always does, and then listen for God to speak up inside Him and tell him what to say the whole time. We can't use formulas, but we can understand principles and then walk these out through prayer in our dealings with people.&nbsp;</div><div><br /></div><div>Darrell G. Wolfe</div><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />