---
title: 'Best In The World!'
date: '2012-05-24T21:41:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1605914049116265708'
blogger_filename: '/2012/05/best-in-world_24.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Keys To Success'
---

<div style="text-align: center;"><strong>Core Concept:</strong></div><br />Staying true to your core concept/theme means that you are staying true to the thing or things you can be best in the world at. Now when I say "Best In The World" I don't mean that there is no one better than you. One could say that it's debatable whether there is a difference between <a href="http://www.ericclapton.com/" target="_blank">Eric Clapton</a> and <a href="http://www.jimihendrix.com/us/home" target="_blank">Jimi Hendrix</a> in ability. <br /><br />However, There is no debate that they operate in different styles. It's clear, from a non partial casual observer that they are both excellent players and have their own unique style. They both add something to the world of music. <br /><br />The idea here is that they are both "Best In The World" at what they do. This is because they have something of themselves to add to their music and nobody else does it quite like them. <br /><br />What is there, in your life, that you do BEST! This is not to say that there is nobody else who is better, this is rather to say that there is something that you do really well, and nobody does it quite like you. <br /><br />You can always tell an amatuer musician from a professional. This is the difference between copying the music and sound, even a good copy... vs adding your own unique style to it. What do you do, that you do, and only you do the way you do it? What do you do and loose all track of time because you love it? What would you do if you have billions of dollars in the bank and could do anything you felt like for hours a day? <br /><br />Go to that! Start small... even if all you can do is read about it, because you don't have the equipment yet... start somewhere... and work toward doing what only you do, because you love it. <br /><br /><blockquote class="tr_bq">"Choose a job you love, and you will never have to work a day in your life." - Confucius </blockquote><br /><br /><br /><iframe allowfullscreen="" frameborder="0" height="315" src="http://www.youtube.com/embed/lt0DTHws420" width="420"></iframe><br /><br /><br /><b>I call you empowered 2 prosper with good success!</b><br /><b><br /></b><br /><b>Darrell G. Wolfe</b><br /><a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a><br /><a href="https://www.facebook.com/n2goodsuccess?sk=wall">https://www.facebook.com/n2goodsuccess</a><br /><a href="http://empoweredtooprosper.blogspot.com/">http://empoweredtooprosper.blogspot.com/</a><br /><br /><b>See Also:</b><br />Book Suggestion from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br /><br /><b>Bulldog Publications:&nbsp;</b><br /><b><a href="http://www.amazon.com/dp/1453815619/ref=as_li_ss_til?tag=your0f4d-20&amp;camp=213381&amp;creative=390973&amp;linkCode=as4&amp;creativeASIN=1453815619&amp;adid=1NAWEWPYWDQA3XGCY7N5&amp;&amp;ref-refURL=http%3A%2F%2Fn2gs.blogspot.com%2F" target="_blank">Bankings Basics for Believers; Now Available on Amazon.&nbsp;</a></b><br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=1453815619" style="height: 240px; width: 120px;"></iframe><br /><br class="Apple-interchange-newline" /><br /><br />