---
title: 'Posting a You Tube Video into a Blog/Website'
date: '2012-04-27T05:00:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3614084917248623241'
blogger_filename: '/2012/04/posting-you-tube-video-into-blogwebsite.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Technology & Tools'
---

<div style="text-align: center;"><b>Instructions for:&nbsp;Posting a You Tube Video into a Blog/Website</b></div><div style="text-align: justify;"><br /></div><div style="text-align: justify;">Knowing something about HTML can be helpful, but it's not&nbsp;necessary. The following instructions are specifically for <a href="http://blogger.com/">Blogger.Com</a> blogs, but the same basic instructions work for WordPress.Com blogs and generally anything you want to post a video into, including emails, websites, etc.&nbsp;</div><div style="text-align: justify;"><br /></div><div style="text-align: justify;">For example. Let's say you have an awesome You Tube video you found and it goes just GREAT with the topic you were&nbsp;writing&nbsp;about.&nbsp;</div><div style="text-align: justify;"><br /></div><div style="text-align: justify;"></div><ul><li>All you need to do it <b>go to the video</b> in YouTube.&nbsp;</li><ul><li>Beneath the video,&nbsp;</li><ul><li>click "<b>Share</b>",&nbsp;</li><li>then click "<b>Embed</b>".&nbsp;</li><li>A box with a bunch of HTML comes up pre-highlighted for you.&nbsp;</li><li>Simply right click on your mouse and hit <b>copy</b>, or if you are keyboard literate use Control-C.&nbsp;</li></ul></ul><li>Then <b>pull up the post</b> you were writing.&nbsp;</li><ul><li>I suggest that if you are not HTML literate, at least a little, find the place you want to Embed the video and then hit the "Enter" button several times to create space in your post.&nbsp;</li><li>Now in your post at the top you'll see two views.&nbsp;</li><ul><li>"Compose" is the default view that you type into.&nbsp;</li><li>"<b>HTML</b>" is the <b>view </b>that shows you all the back code. For example; when you hit "Enter" over and over creating space between the paragraphs you will see the code&nbsp;</li><ul><li>"&lt;br /&gt;".&nbsp;</li></ul></ul><li>So find a bunch of those and look just above them and you'll probably find amidst the code the words you typed in your paragraph, with a bunch of other funny markings indicating to the computer that you wanted bold&nbsp;letters, or whatever.&nbsp;</li><li>Then you just <b>click wherever you want the video, </b>next to one of those break marks&nbsp;</li><ul><li>"&lt;br /&gt;"&nbsp;</li></ul><li>Then right <b>click paste </b>(or Control-V).&nbsp;</li></ul></ul><br /><div style="text-align: justify;">If you still need help, try watching this video I found on the subject. You could also right click on this webpage and click "View Page Source" and scroll down until you find the words "www.YouTube.com". Try using Control-F to find it. You'll see where I posted this video.&nbsp;</div><div style="text-align: justify;"><br /></div><div style="text-align: justify;"><iframe allowfullscreen="" frameborder="0" height="315" src="http://www.youtube.com/embed/-3l0feGWTi0" width="420"></iframe></div><div style="text-align: justify;"><br /></div><div style="text-align: justify;"><br /><br /><br /><div style="text-align: start;"><span style="background-color: white; font-family: 'Trebuchet MS', Trebuchet, sans-serif; font-size: 12.727272033691406px; line-height: 16.363636016845703px;">______________________________________________</span></div><div style="text-align: start;"><br /></div><div style="text-align: start;"><br /></div><div style="text-align: start;">By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a></div><div style="text-align: start;"><br /></div><div style="text-align: start;"><a href="http://www.darrellwolfe.com/" rel="nofollow" style="background-color: white; color: #397dbf; font-family: 'Trebuchet MS', Trebuchet, sans-serif; line-height: 16.363636016845703px; text-decoration: none;" target="_blank">www.DarrellWolfe.com</a></div><div style="text-align: start;"><br /><h4><a href="http://darrellwolfe.blogspot.com/2013/11/connect.html" style="background-color: white; color: #397dbf; font-family: 'Trebuchet MS', Trebuchet, sans-serif; line-height: 16.363636016845703px; text-decoration: none;">Connect</a></h4></div><div style="text-align: start;"><span style="font-family: Trebuchet MS, sans-serif;">Tumblr&nbsp;<a href="http://darrellwolfe.tumblr.com/" rel="nofollow" target="_blank">DarrellWolfe</a><br /><span style="line-height: 16.363636016845703px;">Facebook&nbsp;</span><a href="https://www.facebook.com/DarrellGWolfe" style="line-height: 16.363636016845703px;" target="_blank">DarrellGWolfe</a><br /><span style="line-height: 16.363636016845703px;">Twitter&nbsp;</span><a href="https://twitter.com/darrellwolfe" style="line-height: 16.363636016845703px;" target="_blank">@DarrellWolfe</a><br /><span style="line-height: 16.363636016845703px;">Google+&nbsp;</span><a href="https://plus.google.com/b/106337514196493406365/+DarrellWolfeBlogspot/posts" rel="" style="line-height: 16.363636016845703px;" target="_blank">DarrellGWolfe</a><br />YouTube&nbsp;<a href="http://www.youtube.com/user/darrellgwolfe" target="_blank">DarrellGWolfe</a></span><br /><ul></ul></div><div style="text-align: start;"><span style="background-color: white; font-family: 'Trebuchet MS', Trebuchet, sans-serif; font-size: 12.727272033691406px; line-height: 16.363636016845703px;"><br /></span></div><div style="text-align: start;"><span style="background-color: white; font-family: 'Trebuchet MS', Trebuchet, sans-serif; font-size: x-small; line-height: 16.363636016845703px;"><i><b>Disclaimers:</b></i></span></div><div style="text-align: start;"><span style="background-color: white; font-family: 'Trebuchet MS', Trebuchet, sans-serif; font-size: x-small; line-height: 16.363636016845703px;"><i><b><br /></b></i></span><span style="background-color: white; font-family: 'Trebuchet MS', Trebuchet, sans-serif; font-size: x-small; line-height: 16.363636016845703px;"><i><b>FOR MY FULL DISCLAIMER: See my "<a href="http://www.darrellwolfe.com/p/about-20.html" target="_blank">Start Here About</a>" page.&nbsp;<a href="http://www.darrellwolfe.com/p/about-20.html" target="_blank">Click Here</a></b></i></span></div><div style="text-align: start;"><span style="background-color: white; font-family: 'Trebuchet MS', Trebuchet, sans-serif; font-size: x-small; line-height: 16.363636016845703px;"><i><br /></i></span><span style="background-color: white; font-family: 'Trebuchet MS', Trebuchet, sans-serif; font-size: x-small;"><i><span style="line-height: 16.363636016845703px;">*&nbsp;<b>Information here is As-Is.</b>&nbsp;These are the opinions of a fellow traveler and seeker of truth. I am not a doctor, lawyer,&nbsp;</span><span style="line-height: 16.363636016845703px;">licensed</span><span style="line-height: 16.363636016845703px;">&nbsp;financial advisor, tax preparer, etc, etc... I'm just one guy, sharing what he's learned. As such, the information may be as true or faulty as the guy on the buss stop giving you directions. If you need accurate information I encourage you to seek the help of a professional in your field.&nbsp;</span></i></span></div><div style="text-align: start;"><span style="background-color: white; font-family: 'Trebuchet MS', Trebuchet, sans-serif; font-size: x-small;"><span style="line-height: 16.363636016845703px;"><i><br /></i></span></span><span style="font-family: Trebuchet MS, Trebuchet, sans-serif; font-size: x-small;"><span style="background-color: white; line-height: 16.363636016845703px;"><i>*<b>&nbsp;I do make money from this blog.</b>&nbsp;<a href="http://biblehub.com/1_timothy/5-18.htm" target="_blank">1 Tim 5:18</a>&nbsp;says the worker is worthy of his wages. I do earn affiliate commissions or freebies from some of the products I discuss at various points on this blog. Regardless I only suggest things that have personally helped me, or someone I know. If you click on an "Affiliate Link" and you buy something I'll get a cut. Thanks for your support!&nbsp;</i></span></span></div><div style="text-align: start;"><span style="font-family: Trebuchet MS, Trebuchet, sans-serif; font-size: x-small;"><span style="background-color: white; line-height: 16.363636016845703px;"><i><br /></i></span></span><span style="font-family: Trebuchet MS, Trebuchet, sans-serif; font-size: x-small;"><span style="background-color: white;"><span style="line-height: 16.363636016845703px;"><i>*&nbsp;<b>I am a conservative Christian.</b>&nbsp;I write from a bible-centric point of view. I welcome people from other points of view to jump into the&nbsp;conversation. If you don't like bible-centric writing: I encourage you not to read my posts.... Unless you want to learn something new.&nbsp;</i></span></span></span></div><div style="text-align: start;"><span style="font-family: Trebuchet MS, Trebuchet, sans-serif; font-size: x-small;"><span style="background-color: white;"><span style="line-height: 16.363636016845703px;"><i><br /></i></span></span></span><span style="font-family: Trebuchet MS, Trebuchet, sans-serif; font-size: x-small;"><span style="background-color: white;"><span style="line-height: 16.363636016845703px;"><i><b>* In all you do: Live Long and Prosper, with GOOD SUCCESS!&nbsp;</b></i></span></span></span></div><div style="text-align: start;"><span style="background-color: white; font-family: 'Trebuchet MS', Trebuchet, sans-serif; font-size: x-small;"><span style="line-height: 16.363636016845703px;"><i><br /></i></span></span><span style="background-color: white; font-family: 'Trebuchet MS', Trebuchet, sans-serif; font-size: x-small;"><span style="line-height: 16.363636016845703px;"><i><br /></i></span></span><i><span style="font-size: x-small;"><b><span style="background-color: white; font-family: 'Trebuchet MS', Trebuchet, sans-serif;"><span style="line-height: 16.363636016845703px;">Thank you,&nbsp;</span></span><a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a></b></span></i></div><div><i><span style="font-size: x-small;"><br /></span></i></div></div>