---
title: 'GRACE - Great Faith'
date: '2012-01-07T07:57:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6364672495611597173'
blogger_filename: '/2012/01/grace-great-faith.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
---

<a href="http://www.josephprince.org/Resources_Daily_Grace_Inspirations.asp?active=resources" target="_blank">Joseph Prince</a> said something today that I just had to post even though I got home late and should be in bed. It's been on my mind off and on throughout the whole day.<br /><br />The Lord asked Jospeh "There were two people Jesus said had "<a href="http://www.biblestudytools.com/search/?q=great+faith" target="_blank">Great Faith</a>". There was a Centurion and a Canaanite woman.&nbsp;What was so special about their faith?"<br /><br />Joseph said that he replied "Oh that's easy Lord I heard this preached many times, the Centurion was a man under authority and he understood authority and how Jesus could wield it..."<br /><br />The Lord replied: "OK, then how does that apply to the woman? What do those two have in common?"<br /><br />Joseph flipped back and forth many times and finally gave up: "Lord tell me."<br /><br /><b>Centurion:</b><br /><br /><h4 class="ResultTitle" style="background-color: white; clear: left; font-family: arial; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><a href="http://www.biblestudytools.com/nkjv/matthew/8-10.html"><span style="color: blue;">Matthew 8:10 NKJV</span></a></h4><div class="ResultText" style="background-color: white; color: #333333; font-family: arial; margin-bottom: 3px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">When Jesus heard it, He marveled, and said to those who followed, "Assuredly, I say to you, I have not found such&nbsp;<span class="Highlight" style="background-color: #ffff96; font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 2px; padding-right: 2px; padding-top: 0px;">great</span>&nbsp;<span class="Highlight" style="background-color: #ffff96; font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 2px; padding-right: 2px; padding-top: 0px;">faith</span>, not even in Israel!</div><br /><br /><b>Canaanite Woman:</b><br /><br /><h4 class="ResultTitle" style="background-color: white; clear: left; font-family: arial; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><a href="http://www.biblestudytools.com/nkjv/matthew/15-28.html"><span style="color: blue;">Matthew 15:28 NKJV</span></a></h4><div class="ResultText" style="background-color: white; color: #333333; font-family: arial; margin-bottom: 3px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Then Jesus answered and said to her, "O woman,&nbsp;<span class="Highlight" style="background-color: #ffff96; font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 2px; padding-right: 2px; padding-top: 0px;">great</span>&nbsp;is your&nbsp;<span class="Highlight" style="background-color: #ffff96; font-weight: bold; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 2px; padding-right: 2px; padding-top: 0px;">faith</span>! Let it be to you as you desire." And her daughter was healed from that very hour.</div><br /><br />Here was the reply. One was a man with military submission and authority and one was a housewife woman. You couldn't get much more&nbsp;separate&nbsp;than these two.<br /><br />They were both not under the law.<br /><br />The LAW was not given to bring a righteousness&nbsp;consciousness. It was given to make one sin conscious. It was given to make us aware of our sin and need for a savior. Those who meditate in the law become hyper aware of sin and condemnation.<br /><br />These two were not under the law so they were not hyper aware of sin and condemnation. They were only hyper aware of Jesus. So now under GRACE we are to purge ourselves of being sin/law aware and become Jesus/Grace aware. Then we too can walk in great faith!<br /><br />He also said: You are not preaching GRACE radically enough, as Paul did, until you are totally misunderstood by religion.<br /><br />Darrell G. Wolfe