---
title: 'Interviews PT 1- Concrete and Specific'
date: '2012-01-21T09:56:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '223555495705636647'
blogger_filename: '/2012/01/interviews-pt-1-concrete-and-specific.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'Career'
---

<br /><h1 style="background-color: white; border-bottom-color: rgb(204, 204, 204); border-bottom-style: dotted; border-bottom-width: 1px; color: #333333; font-family: Arial, Tahoma, Verdana; font-size: 20px; font-weight: normal; line-height: 20px; margin-bottom: 10px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 5px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;">Interviews PT 1- Concrete and&nbsp;Specific</h1><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>Concrete and Specific:</strong></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">One of the key elements to mastering the interview process is knowing how to give&nbsp;<strong>Concrete and Specific Answers</strong>&nbsp;to every question that is asked. Consider the following example:</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">The interviewer is asking the same questions to 15 different candidates. Marvin who is looking for a trainer asks one question that he is more interested in than all the rest: “Tell me about a time you worked with another worker who was under preforming?”</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Then 14 candidates come in with answers that sound something like this:</div><ul style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">” Once I worked with someone who was struggling in their sales stats. I gave her suggestions about how to profile for sales and ask open ended questions. She improved so dramatically within the two sessions we worked together that her supervisor emailed me a thank you note.”</li></ul><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Then candidate 15 comes in and is asked the same question with a very different answer:</div><ul style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; list-style-type: square; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="list-style-type: square; margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">“Last month, I worked with Rachel. She had worked four hours that day and only had one sale so far. Her position is to take incoming calls. The first thing I did was take some time to understand her struggle. I asked whether she was having more trouble identifying opportunities to sell or how to word them. She replied that both were equally troublesome to her. So I had her walk me through the call she had just gotten finished with. We reviewed the account together and I showed her the five places I always look on each call for clues. I also pointed out six sales possibilities that could have saved this customer money and time. We pulled up some previous calls and reviewed each account. I roll played with her to help her practice saying the information to me first, and help her tweak things to her style. Then we took some live calls together. The first set of calls I profiled with her and walked her through each account and what I saw and narrowed the best sale for that call. The next set of calls I had her walk me through each account. Then I sat back and let her work on her last set standing by to answer questions. Then I made a plan with her to check in at the end and see how she did. By the end of the day she had moved from a 2% sales rate, of sales per call with one sale, to a 15% sales rate with 9 sales. This was still below our goal, but much better than she had been doing. I checked in with her three times in the following 4 weeks and found she moved from a Month To Date of 12% to 19% to 23%. This is not a top performers data but well within our accepted range. I received a personal email from her supervisor thanking me for my work and letting me know that she was still preforming at the levels expected, and credited me with having provided her with the tools she needed.</li></ul><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">NOW…</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Which of these answers would the interviewer see as identifying the candidate he is looking for? Of course the second. But the first is the type of answer that most people give. Or they will throw out five examples, all on which are at that basic surface level. The concrete and specific answer technique means:</div><ol style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><li style="margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">You are giving&nbsp;<strong>specific&nbsp;</strong>answers. HOW did you help? WHICH open ended questions? WHICH employee, or if privacy is an issue give something. “I worked with someone from Tara’s team.” WHEN did you do this?” What screens did you look at with her? As much detail as you can without being a chatter box. Stick to details that pertain to the questions. The color of Rachel’s shirt doesn’t matter, unless you specifically used that to “build rapport” with her. Details are important. Use details that highlight something you feel is something you did well in that situation that had a direct positive result.</li><li style="margin-bottom: 0px; margin-left: 20px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">You are giving&nbsp;<strong>concrete&nbsp;</strong>answers. “She had a low sales rate that day”, does not cut it. “She had a 2% sales rate that day with only one sale in her first four hours of her shift” is concrete. It nails down exactly what we are talking about here. It gives the interviewer, Marvin, a place to frame and understand the situation and relate it to situations either similar to ones he had, or similar to ones he might expect you’d be in.</li></ol>