---
title: 'Send me a picture to use as an object lesson.'
date: '2012-04-30T15:24:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1834342313795198855'
blogger_filename: '/2012/04/send-me-picture-to-use-as-object-lesson.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Object Lessons'
---

<br />I have an idea. I'm going play a game with you that a pastor I once new did with the children of the congregation. I think it's a fun game for any age group.<br /><br /><h2>Here is your job:<b> Send me a picture that you took yourself and I'll make in an object lesson.</b></h2><br /><b>Disclosure:</b><br />I only agree to use pictures that follow these disclosures and I will use as many as I can keep up with. Obviously if I get a 1000 pictures I could not use them all. I'll pick the best ones.&nbsp;*<i>The picture must be in good taste and clean. It must be taken with your own camera and not taken from the internet somewhere, or be someone else's photo that you do not have permission to use. It must be clear and good quality, not a poor image. Fuzzy can be OK, if that was obviously done on purpose. It can be something normal, like a head shot or family photo. It can be something abstract like a close up of a flower or leaf. Use your imagination. Try to make it difficult. Have fun, use your imagination. You can leave it as a Facebook Post on this blogs page. You can send it by email to DarrellGWolfe@gmail.com. You can leave it as a comment on the blog as well. Or you can post the link to the <a href="https://picasaweb.google.com/" target="_blank">Picasa </a>or <a href="http://www.flickr.com/" target="_blank">Flickr </a>Public Album</i>*<br /><br />Have Fun Scouting: I look forward to this&nbsp;exercise!<br /><br />Darrell G. Wolfe<br />