---
title: 'Prepare the way of the Lord'
date: '2012-01-05T17:33:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8039218082732000934'
blogger_filename: '/2012/01/prepare-way-of-lord.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><b><a href="http://www.biblestudytools.com/nkjv/matthew/passage.aspx?q=matthew+3;matthew+4" target="_blank">Matthew 3</a></b><br />3 For this is he who was spoken of by the prophet Isaiah, saying: "The voice of one crying in the wilderness: <b>'Prepare the way of the Lord; Make His paths straight.'</b> " <br /><br /><b><a href="http://www.biblestudytools.com/nkjv/luke/1.html" target="_blank">Luke 1</a></b><br />76 And you, child, will be called the<b> prophet of the Highest</b>; For you will <b>go before the face of the Lord</b> to<b> prepare His ways,</b> 77 <u>To give knowledge of salvation</u> to His people By the remission of their sins, 78 Through the tender mercy of our God, With which the Dayspring from on high has visited us; 79 <u>To give light to those who sit in darkness</u> and the shadow of death, <u>To guide our feet into the way of peace.</u>"  <br /><b><br /></b><br /><b>HEAR:</b><br />I got stuck on this one line today: Prepare the way of the Lord. How do you prepare the way of the Lord. What does that mean? It's interesting to now too that it wasn't just his mission to prepare the way it was his message. He was the voice crying out: PREPARE THE WAY!<br /><br />What does it mean to prepare the way? I find in Luke the mission given to him prophetically by his father the priest.<br /><br /><ol><li>To give knowledge of salvation</li><li>To give light to those in darkness</li><li>To guide us in the way of peace</li></ol><br />Do you see how each begins with give. God is a giver. We who are his are also givers. Our mission is to give. Salvation points to the fact that we were slaves to sin and the curse. But THE BLESSING has been restored. We preach THE BLESSING and all it's benefits (Psalms 103) everywhere we go.<br /><br />Light refers to understanding.&nbsp;Darkness operates a certain way. In a corporate world darkness says: "Take because you fend for yourself", "Lie to get ahead", "Step on or over others to climb up".<br /><br />More importantly Darkness says things like: "It's flu season, I get the flu every year. I wonder how bad it's going to be this year?", "I live on a fixed income", "I don't see how I could ever make it", "This kind of bad stuff just happens to me all the time, I must be unlucky", "I know this relationship is bad for me, but I just need her/him".<br /><br />Light shows us that THE BLESSING prospers us in the midst of famine, heals the incurable disease, and meets every need we have. It's a new way of thinking.<br /><br />Peace is from the Hebrew word/idea of Shalom. Nothing missing, nothing broken, everything whole and complete! There are ways that lead to life and ways that lead to death.<br /><br />Proverbs 14:12 NKJV There is a way that seems right to a man, But its end is the way of death.<br />Proverbs 16:25 NKJV There is a way that seems right to a man, But its end is the way of death.<br /><br />The natural man says during famine: Hoard, hold, store up. The Spiritual man says: GIVE MORE, sow, increase!<br /><br /><b>DO:</b><br />My mission in life, preparing the way of Jesus into the lives of people around me, AND preparing the way of Jesus to return to this earth and find a glorious church:<br /><br /><ol><li>To give knowledge of salvation</li><li>To give light to those in darkness</li><li>To guide us in the way of peace</li></ol><b>PRAYER:</b><br />Holy Spirit! You are welcome here in my life, heart, mind, house, and ways. Lead and Guide me into all truth and show me things to come so that I can prepare myself, my family, and those I am assigned to coach and train.<br /><br /><b><a href="http://www.biblestudytools.com/kjv/john/16-13.html" target="_blank">John 16:13 </a></b><br />13 Howbeit when he, the Spirit of truth, is come , he will guide you into all truth: for he shall not speak of himself; but whatsoever he shall hear , that shall he speak : and he will shew you things to come .<br /><br />Darrell G. Wolfe