---
title: 'To Walk in Authority Today: First Be Still'
date: '2012-01-28T17:12:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2661964583864789611'
blogger_filename: '/2012/01/to-walk-in-authority-today-first-be.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><b><a href="http://www.biblestudytools.com/nkjv/psalms/passage.aspx?q=psalms+16:5-7" target="_blank">Psalm 16:5-7 NKJV</a></b><br />5 O Lord, You are the portion of my inheritance and my cup; You maintain my lot. 6 The lines have fallen to me in pleasant places; Yes, I have a good inheritance. 7 I will bless the Lord who has given me counsel; My heart also instructs me in the night seasons. <br /><b><a href="http://www.biblestudytools.com/psalms/passage.aspx?q=psalms+16:5-7" target="_blank">Psalms 16: 5-7 NIV</a></b><br />5 LORD, you have assigned me my portion and my cup; you have made my lot secure. 6 The boundary lines have fallen for me in pleasant places; surely I have a delightful inheritance. 7 I will praise the LORD, who counsels me; even at night my heart instructs me. <br /><br /><b><a href="http://www.biblestudytools.com/nkjv/proverbs/passage.aspx?q=proverbs+3:5-6" target="_blank">Proverbs 3:5-6 NKJV</a></b><br />5 Trust in the Lord with all your heart, And lean not on your own understanding; 6 In all your ways acknowledge Him, And He shall direct your paths. <br /><b><a href="http://www.biblestudytools.com/proverbs/passage.aspx?q=proverbs+3:5-6" target="_blank">Proverbs 3: 5-6 NIV</a></b><br />5 Trust in the LORD with all your heart and lean not on your own understanding; 6 in all your ways acknowledge him, and he will make your paths straight. <br /><br /><b>HEAR:</b><br />My Father in Heaven has given me assignment and boundaries. He counsels me in throughout my day and especially in my quiet times. My spirit is led and directed by Holy Spirit, moving in me to will and <a href="http://www.biblestudytools.com/search/?q=will+and+do+his+good&amp;c=nt&amp;t=nkjv&amp;ps=100&amp;s=Bibles" target="_blank">to do His good pleasure</a>. I trust in my Lord and acknowledge Him in all my ways, therefore he will make my paths straight!<br /><br />So many times I rush through life, through my days without&nbsp;acknowledging&nbsp;Him. Maybe I read my bible and ran a post for this site. I felt the leading of the Holy Spirit in it. It was the anointing. But I didn't STOP,<a href="http://www.biblestudytools.com/nkjv/psalms/46-10.html" target="_blank"> be still and know</a> that He is God. I want to remember to take time to be still in His presence, reminding myself that I don't need the answers and solutions to all the various things I am facing and decisions I am making. Only one thing is needful, sit at the feet of Jesus and listen, He has all the answers I need now and will ever need. He'll tell me what to do and say if I will just listen and stop trying to force my will onto the situations at hand.<br /><br />Authority used without being under authority, is not authority. If I process an override as an officer of the bank I do so under the authority given to me. As a customer I can't hop over the counter and try to override things. I haven't been given that authority or the codes&nbsp;necessary. I have to be submitted to the authority of God, listen to his instruction, receive the codes for that&nbsp;situation&nbsp;and then carry that command out. Only with the command codes can I carry out the assignment for the day. They change daily to prevent fraud and&nbsp;sabotage&nbsp;of the Devil. <a href="http://www.biblegateway.com/passage/?search=Matthew+6%3A34&amp;version=NIV" target="_blank">So all I need is today's instruction</a>, not the ever intricate detail of the years to come.<br /><br /><b>DO:</b><br />I'm going to sit and listen to Holy Spirit tell me about today before I start it.<br /><br /><b>PRAYER / CONFESSION:</b><br />This is my day! There are many like it but this one is mine. I have been given authority today. to rule my domain, put down those things that are out of order, so that I may be fruitful, multiply, and increase. I ascribe worth to my Father in Heaven.<br /><br />Your Kingdom is here, in me! Your will be done today in and through my life. I accept&nbsp;today's&nbsp;bread of provision and instruction. I am forgiven, so I forgive. Reveal to me those points of my life that are out of order that I might bring those in line with your Word. YOU are my power and my source. In YOU I trust!<br /><br />Darrell G. Wolfe<br /><br /><br /><iframe allowfullscreen="" frameborder="0" height="315" src="http://www.youtube.com/embed/M4e87vIRpds" width="420"></iframe><br /><br /><br />