---
title: '“Pay Attention to Me…My system is stronger than ever.”'
date: '2012-09-10T15:42:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1483346368580727748'
blogger_filename: '/2012/09/pay-attention-to-memy-system-is.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Word of The Lord'
---

<br />“Pay Attention to Me…My system is stronger than ever.”<br />Don’t pay attention to or make any plans based on what the media says<br />or what the politicians say. Stand on My Word in John 16. Pay attention to Me.<br />I [the Holy Spirit] will obey verses 13-15. I will show you things to come. I will<br />lead you through troubled times. I already have THE plan for you, and it’s very<br />good. Follow it. It will not only get you through, it will place you in a very high<br />place—a rich place—a strong place of victory. <br />You will have to discipline yourself and be diligent to listen to Me. All the<br />other voices will have a plan, a word, an idea for your future and security.<br />Don’t listen to Babylon’s system. It has fallen apart. My system is stronger than<br />ever. My kingdom is flourishing, and THE BLESSING is the place to be. <br />Keep your eyes on My Word. Listen to it. It will guide you and I will<br />perform it. Love Me. Love My people as I have loved you. Walk in it. Love never<br />fails, and neither does My plan.<br />Be very cautious to stay completely clean from covetousness. First<br />Timothy 6:10 must live in the forefront of your thinking. If you will do these<br />things and continue therein, you will come into your wealthy place. A place<br />lifted up. A place in Me already planned and prepared for you now. Here. Not<br />heaven—not yet. But it will seem like heaven right in the midst of all the<br />trouble, and you’ll be able to reach out to untold numbers of suffering people<br />with the Good News of the gospel. <br />I’m coming very soon. Sooner than you think. Keep your eyes on Me and<br />you’ll get the job done.<br />&nbsp; &nbsp; &nbsp;—Prophecy delivered by Kenneth Copeland<br />&nbsp; &nbsp; &nbsp; &nbsp; Oct. 19, 2008<br />