---
title: 'Interviews PT 3- Know Yourself'
date: '2012-01-21T09:57:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5493202579005854355'
blogger_filename: '/2012/01/interviews-pt-3-know-yourself.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'Career'
---

<br /><h1 style="background-color: white; border-bottom-color: rgb(204, 204, 204); border-bottom-style: dotted; border-bottom-width: 1px; color: #333333; font-family: Arial, Tahoma, Verdana; font-size: 20px; font-weight: normal; line-height: 20px; margin-bottom: 10px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 5px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none;"> Interviews PT 3- Know&nbsp;Yourself</h1><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong><a href="http://en.wikipedia.org/wiki/Know_thyself" style="color: #008dcf; text-decoration: none;" target="_blank">Nosce Te Ipsum</a>&nbsp;-&nbsp;Know Thyself</strong></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">This phrase primarily means to know your strengths and weaknesses. The bible says: Do not think of yourself more highly than you ought to. This doesn’t mean to put&nbsp;yourself&nbsp;down, as some religious folks would have you believe, but rather to know who you are are and who you aren’t. Know the giftings God has placed inside of you and also what he hasn’t called you to. By doing so you are able to narrow down the position that fit you and those that do not.</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><a href="http://www.biblestudytools.com/gnt/romans/12-3.html" style="color: #008dcf; text-decoration: none;" target="_blank"><strong>Romans 12:3</strong></a></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><em>3&nbsp;And because of God’s gracious gift to me I say to every one of you: Do not think of yourself more highly than you should. Instead, be modest in your thinking, and judge yourself according to the amount of faith that God has given you.</em></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>Know your strengths</strong></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">You have been given strengths and giftings by God. He has enabled you to be particularly good at certain things. If you know what those strengths are then you can boldly assert what they are and be confident in your answers.</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Maybe you are strong at something but not as strong as you want to say you are. Don’t be tempted to overstate your strengths. If you are hired into a position for stating you are stronger at something than you are it will be found out quickly. Humility isn’t about putting yourself down. It’s about knowing what you can and can’t do and where the source of your can do came from.</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>Know your areas of opportunity</strong></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">You also have areas that you are growing in. There are things that you aren’t good at. Nobody is good at everything. Some areas you will be strong in you just aren’t yet. If you know these areas of opportunity and are strategically honest about them you will either know to avoid certain positions, or you will be able to communicate how these areas are not&nbsp;dis-qualifiers&nbsp;to your new desired position.</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Personally: I talk a lot. That makes me a GREAT writer and blogger. When I was given assignments to write 500 words about something, I didn’t struggle to get up to 500 words, I struggled to get back DOWN to 500 words and edit out the un-necessary. This meant that as a call center rep I often struggled with handle time. They wanted my average calls to come to 255 seconds and I was always pushing over 300. After I left they actually raised it to 300, oh well…</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Interviewers will ask what my weakness are (Areas of Opportunity)</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>I could tell the interviewer that:</strong>&nbsp;<em>I talk too much and can’t seem to figure out how to lower it… that doesn’t quite sell my opportunity.</em></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>OR</strong></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>I could tell the interviewer that</strong>:&nbsp;<em>I enjoy meeting new people and getting to know them. I am honestly interested in people and want their best interest. I also have a strong desire to have things done right and not half done. As a result I sometimes take longer on calls than my counterparts. I am actively working on finding ways to say less, not ask certain questions that open the&nbsp;conversation&nbsp;up or encourage long stories.&nbsp;</em></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">One highlights weakness and one highlights area of opportunity.</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>The important questions:</strong></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">Answer these questions for yourself so that you can articulate it to the interviewer:</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>How am I the BEST fit for this position? How am I going to add value to this company, department, or team?</strong></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">I am a great fit for this position because…</div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><em>Ex: I am a great fit for this position because I have 4 years of background in banking related sales. I have sold in person and over the phone. I know my customers and ask great questions. I am not only able to meet their needs with the best products and services but I am able to uncover other needs they didn’t realize they had. Just the other day someone came in to order checks and I was able to uncover for her that her mortgage rate was 7% and current rates are in the low 4% range. She was hooked up wit my mortgage partner and refinanced into a 4.32%. It dropped her monthly payment and will cut years off of her loan if she makes the same payment she was making.&nbsp;</em></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;"><strong>Task for you:</strong></div><div style="background-color: white; color: #555555; font-family: Arial, Tahoma, Verdana; font-size: 12px; line-height: 20px; padding-bottom: 15px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">List for yourself your top 3 areas of strength and top 3 areas of opportunity. Practice talking to yourself or a training partner about these 6 areas.</div>