---
title: 'Grace'
date: '2012-02-15T17:30:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2154417743300937117'
blogger_filename: '/2012/02/grace.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<b>COME:</b><br /><b><a href="http://www.biblestudytools.com/nkjv/matthew/23.html" target="_blank">Matthew 23</a></b><br />25 Woe to you, scribes and Pharisees, hypocrites! For you cleanse the outside of the cup and dish, but inside they are full of extortion and self-indulgence. 26 Blind Pharisee, first cleanse the inside of the cup and dish, that the outside of them may be clean also. <br /><br /><b>HEAR:</b><br />Clean first the inside... If you want a clean life you must first have a clean heart and mind. Today, as I reflect on my own growth in the last few months, learning about radical GRACE, reminding and renewing my mind and heart about who I am IN HIM.<br /><br />If I feel that I am not good enough, or capable, of walking out the things of God... It is because I am not convinced in my heart who I am IN HIM...<br /><br /><b>DO:</b><br />Meditate on His Word... who am I to Him?<br /><br /><b>PRAYER:&nbsp;</b><br />Reveal your heart toward me to me.<br /><br />Darrell G. Wolfe