---
title: 'New Years Eve... short recap'
date: '2012-01-01T06:52:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '931425205607754023'
blogger_filename: '/2011/12/new-years-eve-short-recap.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'EMIC'
  - 'Season Changing'
  - 'KCM'
---

Too many notes from tonight to do a full recap. I will be posting the full notes soon. Some take&nbsp;a ways:<br /><br /><br /><br /><a href="http://www.kcm.org/bvov-media" target="_blank">Kenneth Copeland</a>&nbsp;tonight quoting&nbsp;<a href="http://www.nhm.cc/" target="_blank">Norval Hayes</a>:<br /><br />You didn't make a decision to aggressively possess all God has for you. Because you didn't decide you didn't hear. Because you didn't hear you couldn't see it. Because you couldn't see it you couldn't say it. Because you couldn't say it you didn't act on it. Because you didn't act on it you didn't receive it.<br /><br /><br /><br />If you don't end 2012 as the best year you've ever had or even heard of it's because you didn't make a decision to take what God has planned for his Body this year. Anyone not operating under the blessing is going to have a hard year, but for those operating under the blessing they will&nbsp;hardly&nbsp;even notice the bad things happening around them.<br /><br />Jesus said "<a href="http://www.biblestudytools.com/nkjv/john/5-19.html" target="_blank">I only do what I see my Father do</a>..." In like manner we must pay close attention to the Word of God. Not just for ten minutes in the morning or night. Turn the TV and Facebook and whatever else distracts you off! Turn the news and political debates OFF!<br /><br />When you see the Word say "Despise" as in <a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=isaiah+30:12&amp;t=kjv" target="_blank">Isaiah 30:12</a>&nbsp;it can mean to<a href="http://1828.mshaffer.com/d/search/word,despise" target="_blank"> reject or have a low opinion of</a>. It basically means to think nothing about. They just ignored the Word of God. Paul also Ignored his degrees and history, thought nothing of it because of the Anointing!<br /><br /><b>Some of you have become weary in well doing.<span style="font-size: x-large;">&nbsp;</span></b><br /><b><span style="font-size: x-large;"><br /></span></b><br /><b><span style="font-size: x-large;">If you become weary in well doing &amp; faint in your mind by giving attention to other things and NOT giving attention to the Word!</span></b><br /><br /><br />2012 is going to be a time of GREAT Wealth and GREAT Opportunities!<br /><br />Enter into the REST!<br /><br />Both Sin and Victory over sin have the same root. Attention/Focus. What are you giving your attention to, that will rule what you say and do.<br /><br />It upsets God when his people don't let him Bless them!<br /><br />More notes to come...<br />Darrell G. Wolfe<br /><br /><br /><br /><br /><br /><br /><br /><br /><br />