---
title: 'RIGHT GRACE!'
date: '2012-01-10T07:00:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7671534897869120523'
blogger_filename: '/2012/01/right-grace.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<b>COME:</b><br /><a href="http://www.biblestudytools.com/nkjv/matthew/passage.aspx?q=matthew+6:25;matthew+6:33" target="_blank">Matthew 6:25, 33</a><br />25 "Therefore I say to you, do not worry about your life, what you will eat or what you will drink; nor about your body, what you will put on...<br />33 But <b>seek first</b> the <b>kingdom of God </b>and His <b>righteousness</b>, and all these things shall be added to you.<br /><br /><b>HEAR:</b><br />For a long time now I've stopped at this verse and had a knowing deep in my spirit that there was more here than I was catching. I would sit for minutes at a time, staring at it, praying about,&nbsp;dissecting&nbsp;it with concordances. Still there was something I was missing. I have felt there was&nbsp;something&nbsp;profound and life changing, specifically about the word righteousness.<br /><br />How do I seek first His Righteousness? I would ask myself. Well I must become Righteousness Conscious. OK. So I would spend time listening about who I am IN HIM, IN CHRIST, IN WHOM... My position in righteousness. My place in&nbsp;righteousness. I studied MUCH of Kenneth&nbsp;Copeland's&nbsp;material about understanding your place of Authority in God as THE Righteousness of God.<br /><br /><a href="http://www.kcm.org/pdf/force.bk.pdf">http://www.kcm.org/pdf/force.bk.pdf</a><br /><br /><a href="http://www.kcm.org/mp3/series#52473">http://www.kcm.org/mp3/series#52473</a><br /><br />But still something was missing... until today. I had a dawning of light. I had a breakthrough. It was soft and subtle. It wasn't a lightening flash of breakthrough. But rather it was like the halogen lamps that light up slowly.&nbsp;Righteousness&nbsp;is a gift of GRACE. To be intimate with your free gift of Righteousness you must be intimate with how you got it. GRACE. It's about GRACE. It's not about doing all the right things, the right ways. It's not about the "7 steps to receive" or the "10 steps to this or that". It's not even so much, at first, about God's ways of doing things. It's about GRACE.<br /><br />When you really understand that God is for you and not against you! THAT is when it gets exciting! I haven't got the FULL ramification of this light yet, but it's dawning on me that Jesus LOVES me A LOT! I am HIS FAVORITE kid! And you are too!<br /><br /><b>DO:</b><br />I'm going to remind myself daily just how much Jesus loves me!<br /><br /><b>PRAYER:</b><br />Father, YOU love me just as much as you do Jesus! THANK YOU!<br /><br />Darrell G. Wolfe<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />