---
title: 'Michael Hyatt&#39;s Tips to Blogging Success and what you can learn from them for YOUR everyday life.'
date: '2013-03-25T03:54:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8473932816278810141'
blogger_filename: '/2013/03/michael-hyatt-tips-to-blogging-success_24.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Keys To Success'
---

<h2 style="text-align: center;">Michael Hyatt's Tips to Blogging Success:</h2><ol><li>Blog Consistently</li><ol><li>3-5 Times a Week</li><li>If you take a day, post that too. "I'm taking the day off today"</li></ol><li>Make it about the audience</li><ol><li>Stop&nbsp;writing&nbsp;about YOU all the time, talk about THEIR NEEDS.</li></ol><li>Get Involved In Social Media</li><li>Find Your Voice</li><ol><li>Write, Write, Write some more..</li><li>Try new things...</li><li>Find Your Grove</li><li>Do it enough, experimental enough until you find it</li><ol><li>You'll eventually get to the place where it sounds like you.</li><li>You want to get to the place where people say: "I feel like your just talking to me, like we're sitting over a cup of coffee" THAT is you voice!</li></ol></ol><li>Take Time... You'll hit a breakthrough/inflection point, keep digging.</li><ol></ol></ol>Tips for Building a bigger audience faster, mistakes:<br /><br /><ol><li>Don't Fail to get Email Addresses!</li><ol><li>He uses <a href="http://mailchimp.com/?pid=GAW&amp;source=website&amp;gclid=CM3bobH1lrYCFTCmPAodgT0ADA" target="_blank">Mail Chimp</a></li><li>Build an Email Newsletter List</li><li>Sign up should go on the TOP RIGHT corner of the blog. That's the PRIME realestate. Use an&nbsp;incentive&nbsp;of value! Use old posts that are valuable.&nbsp;</li><li>Use apple keynote to create a pdf.</li></ol><li>Don't be Inconsistent</li><ol><li>Whether it's 5-3-1 times a week, stick to it!&nbsp;</li><li>State Intention&nbsp;</li><ol><li>(Ex Once a week)</li><li>(Put it on the calendar!)</li><li>(Sit Down and Write)</li></ol><li>Create a Template! His looked like this:</li><ol><li>GREAT Headline</li><ol><li>Not too cleaver</li><li>Simple, clear, about them!</li></ol><li>Opening Story</li><li>Opening Image (get it from a photo site, or make your own!)</li><li>Make a list! Make it solve a problem!</li><ol><li>Bullet/Enumerated</li></ol><li>Summary and closing questions for comments!</li><li>Your template may be different, but have one!</li></ol><li>Lone Ranger Mentality</li><ol><li>You are NOT in this yourself!</li><li>Network with others, writers, authors, other bloggers who are trying to build THEIR platform!</li><li>Be Intentional! and Network</li></ol><li>Obsessing over the technology!</li><ol><li>Learn code if you so desire. But don't let the technology distract you from writing which is the REAL purpose!</li></ol><li>Perfectionism, stop it!</li><ol><li>Have WOW! But don't try to be so perfect that you procrastinate to nothingness!&nbsp;</li><li>You probably know enough to get started! You don't need to know the end game before you start, you'll figure it out as you go!</li><li>Don't give up because it's not where you want it to be, keep working it!</li></ol><li>Don't be too focused on the numbers!</li><ol><li>Looking at your stats all day will distract you from&nbsp;writing. Stop it!</li><li>Maybe look once in a while to see if you are being effective, but don't drown in there.&nbsp;</li><li>"It's not a good time right now" Just do it!</li></ol><li>Don't Quit!</li><ol><li>People often quit before their inflection point!</li><li>Keep Showing Up</li></ol><li>The only way you sell today is by permission! Sales is not, and cannot be, about you forcing yourself on other people. Be true, authentic, and meaningful to them!</li></ol></ol><br /><br /><div style="text-align: center;"><iframe allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/s75yWp6NOJM" width="560"></iframe></div><div style="text-align: center;"><br /></div><br /><br /><br /><div style="text-align: center;"><iframe allowfullscreen="" frameborder="0" height="315" src="http://www.youtube.com/embed/zBKYnYFrbic" width="560"></iframe></div><div style="text-align: center;"><br /></div><div style="text-align: center;"><br /></div><br /><b>Have questions about anything I said here? Want to share your story? Comment Below!</b><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br />Blog:&nbsp;<a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a><br />Facebook:&nbsp;<a href="https://www.facebook.com/n2goodsuccess?sk=wall" target="_blank">https://www.facebook.com/n2goodsuccess</a><br />Twitter:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b style="background-color: white;">See Also:</b><br />Books by Darrell G. Wolfe:&nbsp;<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6" style="font-family: verdana, arial, helvetica, sans-serif; font-size: 13px;" target="_blank">Amazon.com/author/darrellgwolfe&nbsp;</a><br />Book Suggestions from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Brand and Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br />Other Blogs and Sites by the Wolfe Family:&nbsp;<a href="http://wfconceptions.wordpress.com/" target="_blank">http://wfconceptions.wordpress.com/&nbsp;</a><br /><br /><br /><br />___<br /><div><br /></div><br /><br />