---
title: 'Vision and Mission'
date: '2013-11-14T19:32:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '810555217685919603'
blogger_filename: '/2013/11/vision-and-mission_14.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<h3 class="post-title entry-title" itemprop="name">Vision and Mission </h3><div class="post-header"> </div><h4>My Personal Life Mission</h4><div class="widget-content"><div style="text-align: center;"><span style="line-height: 18px;"><b>Providing People Tools to enter&nbsp;Into <a href="http://n2gs.blogspot.com/2012/03/good-success.html" target="_blank">Good Success</a>!</b></span></div><div style="font: 100% Georgia, serif;"><b style="font-family: 'trebuchet ms', Trebuchet, sans-serif; font-size: 13px; line-height: 18px;"><span style="color: #251a9c;"></span></b><br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv">Joshua 1:8</a><br /><br />This book of the law shall not depart out of thy mouth; but thou shalt  meditate therein day and night, that thou mayest observe to do according  to all that is written therein: for then thou shalt make thy way  prosperous ,<u><b> and then thou shalt have good success.</b></u></blockquote></div></div><h4>My Life Vision</h4><ul><li>Providing Biblical Answers to Practical Problems&nbsp;</li><li>People walking free (<i>spiritually, emotionally, mentally, intellectually, physically,&nbsp;and financially</i>) to pursue the perfect will of God for their lives. </li><li>People living disconnected from the World's System. </li><li>&nbsp;Blog Posts, Books, Merchandise, and other creative arts materials, provided to aide and assist in that freedom.&nbsp;</li><li>Music, Stories, Books, and Blogs created inspire people to live a life full of God's Goodness!</li></ul><br />DW 