---
title: 'Boy Scouts Deal with &quot;Gay&quot; question...'
date: '2013-01-30T18:46:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '774146428629648252'
blogger_filename: '/2013/01/boy-scouts-deal-with-question.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'News and Current Events'
---

&nbsp;I read an article about the boyscouts dealing with the "Gay" question.&nbsp;Here is my problem with an article like the one posted below at the bottom of this post. Havings struggled with this myself when I was younger, there are two statements that operate under false assumptions in this article.<br /><ol><li>LDS says that you "can be gay but can't act on those feeling"</li><li>"And I want every boy, regardless of sexual orientation, to be able to participate in the scouting program."</li></ol>These statements operate under the premise that you can be "Gay" just like you can be black or white, male or femail, etc. Gay, contrary to popular cultural belief is NOT a state that one is, but a mindset one operates under. <br /><br />Now, Christian's have been quick to call it a choice, which in essence it is, but it's a choice in the same way that alcoholism or addiction is a choice. It's a result of mindsets and decisions, but not a direct choice. Nobody says: "I think I'll choose to be an alcoholic" Likewise nobody(not most of them anyway) says: "I think I'll choose to be gay."<br /><br />However, this is not to say that being alcoholic or gay is choiceless and automatic. Both are the result of conditioning and beliefs. Anyone who wants to be free of alcoholism can be, anyone who wants to be free of homosexuality can be. Not through pop culture programs either. AA isn't any more effective for Alcoholics than other so-called "Gay recovery programs" have been for Gays. Those fail because they attempt to use psychology and therapy to do something only Faith in the Word of God can do.<br /><br />All mindsets are the result of the overflow of the heart. What have been put in the ears, in the eyes and spoken by the mouth becomes belief. We see this with <a href="http://en.wikipedia.org/wiki/Anorexia_nervosa" target="_blank">anorexia</a>&nbsp;all the time. You can tell the girl she is TOO skinny, and it's unhealthy, and she needs to eat, but in her mind she is fat and nothing YOU say can change that. To her, she is fat and she must stop eating. It's not truth, but to her it feels true. This is the case with "gay". You may feel gay, you may believe you are gay. There actually is no such thing. Gay is a state of mind. All twisted or incorrect states of mind can be changed by the renewing of your mind through the Word of God. You need to saturate yourself with who you are according to the One who created you, and not who the broken world says you are. <br /><br />This is a VERY unpopular teaching and I don't expect it to become any more popular, but it's the truth. If you don't want to be "free" of being gay, don't be, that is your decision. If you want to be you can be. Here are three great resources for help:<br /><ol><li><a href="http://www.kcm.org/bvov-media">http://www.kcm.org/bvov-media</a></li><li><a href="http://exodusinternational.org/">http://exodusinternational.org/</a></li><li><a href="http://www.amazon.com/You-Dont-Have-Gay-Homosexuality/dp/0942817087">http://www.amazon.com/You-Dont-Have-Gay-Homosexuality/dp/0942817087</a></li></ol><br />Read more about that article: <a href="http://www.myfoxhouston.com/story/20811532/boy-scouts-consider-lifting-gay-ban#ixzz2JU7oxFdi">http://www.myfoxhouston.com/story/20811532/boy-scouts-consider-lifting-gay-ban#ixzz2JU7oxFdi</a><br /><br /><b>Have questions about anything I said here? Want to share your story? Comment Below!</b><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br />Blog:&nbsp;<a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a><br />Facebook:&nbsp;<a href="https://www.facebook.com/n2goodsuccess?sk=wall" target="_blank">https://www.facebook.com/n2goodsuccess</a><br />Twitter:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b style="background-color: white;">See Also:</b><br />Books by Darrell G. Wolfe:&nbsp;<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6" style="font-family: verdana, arial, helvetica, sans-serif; font-size: 13px;" target="_blank">Amazon.com/author/darrellgwolfe&nbsp;</a><br />Book Suggestions from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Brand and Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br />Other Blogs and Sites by the Wolfe Family:&nbsp;<a href="http://wfconceptions.wordpress.com/%C2%A0" target="_blank">http://wfconceptions.wordpress.com/&nbsp;</a>