---
title: 'Grace v Purgatory'
date: '2013-10-30T15:35:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '9209470265577143157'
blogger_filename: '/2013/10/grace-v-purgatory.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'Spiritual Growth'
---

<br /><h4 style="text-align: center;">Study: Purgatory&nbsp;v Grace</h4><br />Apparently this is an issue that still needs to be settled. Let me settle this right up front.<br /><br /><div style="text-align: center;"><b>There is no such thing as Purgatory.&nbsp;</b></div><br />It's not only missing from the bible as a topic, it's directly opposed to the entire life, ministry, message, death, burial, and resurrection of Jesus. Everything Jesus is lays in direct opposition to the concept of Purgatory.<br /><br /><div style="text-align: center;"><b>So why is it so prevalent among some churches? </b></div><div style="text-align: center;"><b><br /></b></div><div style="text-align: center;"><b>Grace is hard to believe. Grace says that we cannot earn it.</b> </div><br /><blockquote class="tr_bq">Study <a href="http://www.scripturecatholic.com/purgatory.html" target="_blank">what Catholics have to say about Purgatory</a> and you will find this: a total lack of understanding regarding Grace. <br /><br />Study scriptures on Grace and you find something totally opposed to the very concept of purgatory. <a href="http://www.whatchristianswanttoknow.com/20-inspirational-bible-verses-about-grace/" target="_blank">http://www.whatchristianswanttoknow.com/20-inspirational-bible-verses-about-grace/</a></blockquote><br /><b>Purgatory is a works based idea</b>. It says, gosh I need to pay for my sins on earth. <b>Grace is not a works based idea, but a gift based idea</b>. ALL sin, past, present, future, every man, every woman, from Adam to the last man to live from the first sin to the last, was paid for by Jesus!<br /><br />But wait, there more! In fact it was not dead works for which Jesus died really at all, it was death itself. Dead works are the fruit, not the root. It was the power and force of death, working in and through men, like spiritual cancer, that Jesus came to deal with.<br /><br />In fact, cancer in the body (and every other malady that affects us on earth) is simply a natural manifestation of this death that came to us through Adam. Our works don't make it happen. You didn't DO anything that caused you to have cancer, it came because Death is already here working against us. <br /><br />Jesus exchanged our death for his life. Your works, bad or good, have never been the issue. It was death in you that Jesus dealt with. Death in you that would send you to hell to be separated from God. Death in you was dealt with. There is NO SIN that can send you to hell. Rather your sins are fruit of the real problem. Death is working in you. (See my post on <a href="http://empoweredtooprosper.blogspot.com/2013/10/foundations-class-2-levels-of-change.html?view=magazine" target="_blank">Levels of Change</a>).<br /><br />Jesus didn't die for what you've done (although that was covered by it too), he died for who you are! You have a disease called death and he gives you the free exchange of life. In fact, it is that very life He gives you, that if you access it and take hold of it, can repel cancer from your body and heal you. <br /><br /><blockquote class="tr_bq"><h4 style="text-align: center;">Come to God and say&nbsp;</h4><h4 style="text-align: center;">"Father, I have death working in me. I accept the gift of your Son, who died and rose again for me. Jesus I receive the life you died to give me."</h4></blockquote><br />That it is it. You are born again. You may or may not feel like it, but you are. You can't change yourself. Even if you spent an eternity in purgatory you would not be one once closer to heaven because it's not about paying for your actions. It's about being given a new nature. You can't do that, only HE can. If you just prayed that prayer, and meant it in your heart, you have that new nature now. And you are bound for heaven regardless of anything you do or don't do.<br /><br />Reading your bible, going to church, praying then are not things you do to earn heaven stripes. You don't HAVE to do any of those things. However, they are simply ways to engage the new life that is in you and facilitate the growth of that life to impact your life on earth from the inside out.<br /><br /><h4 style="text-align: center;">Amputee Parable </h4><br />Amputees sometimes feel as though the missing leg is still there, just like born again believers still feel the old dead nature is still there. It's a false perception because the nervous system has been programed for so long to respond to it.<br /><br />Treating the amputee with medications only can often prolong this "Phantom Limb Syndrome" because it re-enforces the neural pathways that tell the mind the leg is still there. Medications can help short term to deal with symptoms, but what must be done is to stimulate the new nerve endings with as many things as possible (hot things, cold things, prickly things, wet things, etc) and this will create new neural pathways in the mind telling it something has changed here.&nbsp; <br /><br />For the Born Again Believer the neural pathways are still there, programed by the old dead nature. Treating it with religious activities and dead religious works can temporarily ease the pain but may simply re-enforce the belief that the dead man is still there. Rather we must view activities, like bible reading, praying, church going, and practicing loving your neighbor, as ways to stimulate the new spiritual nerve endings and create new pathways in our soul to spirit neural network. <br /><br />Then, there is NO CONDEMNATION when you forget to read you bible for a day, week, year, etc. It's about living out this new life. However as you stimulate these new nerve endings you will find you want to stimulate them more and you will want to read your bible more. Pray more. Go to Church more. As you do, you find more and more about the new nature that is already in you, and trying to grow from the inside out.<br /><br />If you find you don't want to do those things, that is simply the old pathways resisting reprogramming, ignore them and do it anyway. Just remember, don't do them as works to be done, check lists to be crossed off so that you can be a "Good Christian". Do them as ways to intentionally stimulate those new nerve endings. <br /><br /><br /><b>How about you? You see anything to add to this? Want to  share what examples you have seen or experience in yourself or others?  Comment below.&nbsp;</b><br /><div><b><br /></b></div><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br /><b>Blog</b>:&nbsp;<a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br /><b>Facebook</b>:&nbsp;<a href="https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118" target="_blank">Facebook.Com/EmpoweredTooProsper</a><br /><b>Twitter</b>:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b>See Also: </b><br /><a href="https://www.facebook.com/n2goodsuccess" target="_blank">https://www.facebook.com/n2goodsuccess </a><br /><a href="https://www.facebook.com/towdahaudio" target="_blank">https://www.facebook.com/towdahaudio</a><br /><a href="https://www.facebook.com/TexasLivingInfo" target="_blank">https://www.facebook.com/TexasLivingInfo</a>