---
title: 'Talk about Confession!'
date: '2013-03-04T16:54:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2640539669816464990'
blogger_filename: '/2013/03/talk-about-confession.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<h2 style="text-align: center;">Talk about Confession!</h2>Amazing... Mary, full of the Holy Spirit begins to praise and thank God and utter prophecy. This could be among the more powerful confessions in scripture.<br /><br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/nkjv/luke/1-48.html" target="_blank">Luke 1:48 (New King James Version)</a>For He has regarded the lowly state of His maidservant; For behold, <b>henceforth all generations will call me blessed. </b></blockquote><br />And we have called her Blessed haven't we! In fact Wiki doesn't just call her Mary, Virgin Mary, Mary the Mother of Jesus... Wiki (and the Roman Catholics) call her the Blessed Virgin Mary!<br /><br /><blockquote class="tr_bq">Blessed Virgin Mary (Roman Catholic)<br /><a href="http://en.wikipedia.org/wiki/Blessed_Virgin_Mary_(Roman_Catholic)" target="_blank">http://en.wikipedia.org/wiki/Blessed_Virgin_Mary_(Roman_Catholic)</a></blockquote><br />What has God been talking to you about? What has raised up in your spirit by the Holy Spirit? Are confessing His Word to you?<br /><br />This is going to be the year of my <a href="http://www.emic.org/blog/?p=286" target="_blank">GREATEST BLESSING EVER!</a><br /><br />DW<br /><br /><br /><b>Have questions about anything I said here? Want to share your story? Comment Below!</b><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br />Blog:&nbsp;<a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br />Facebook:&nbsp;<a href="https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118" target="_blank">Facebook.Com/EmpoweredTooProsper</a><br />Twitter:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b style="background-color: white;">See Also:</b><br />Books by Darrell G. Wolfe:&nbsp;<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6" style="font-family: verdana, arial, helvetica, sans-serif; font-size: 13px;" target="_blank">Amazon.com/author/darrellgwolfe&nbsp;</a><br />Book Suggestions from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Brand and Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br />Other Blogs and Sites by the Wolfe Family:&nbsp;<a href="http://wfconceptions.wordpress.com/" target="_blank">http://wfconceptions.wordpress.com/&nbsp;</a><br />