---
title: 'Transitions - Pressing through resistance: Study Notes from 07/20/2013'
date: '2013-07-21T02:25:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2022645400664536494'
blogger_filename: '/2013/07/transitions-pressing-through-resistance_20.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Spiritual Growth'
---

<h4 style="text-align: center;">The following is my take away from the bible study I went to today. It was led by Pastor Scott Graham. <a href="https://www.facebook.com/notes/scott-graham/transitions-pressing-through-resistance/10151556388327536" target="_blank">"Transitions - Pressing through resistance"</a></h4><blockquote class="tr_bq"><br /><a href="https://www.youversion.com/bible/107/exo.14.net" target="_blank">Exodus 14</a><br /><br /><br />1 The Lord spoke to Moses: 2 “Tell the Israelites that they must turn and camp before Pi-hahiroth, between Migdol and the sea; you are to camp by the sea before Baal Zephon opposite it. 3 Pharaoh will think regarding the Israelites, ‘They are wandering around confused in the land – the desert has closed in on them.’ 4 I will harden Pharaoh’s heart, and he will chase after them. I will gain honor because of Pharaoh and because of all his army, and the Egyptians will know that I am the Lord.” So this is what they did. <br /><br /><br />10 When Pharaoh got closer, the Israelites looked up, and there were the Egyptians marching after them, and they were terrified. The Israelites cried out to the Lord, 11 and they said to Moses, “Is it because there are no graves in Egypt that you have taken us away to die in the desert? What in the world have you done to us by bringing us out of Egypt? <br /><br /><br />13 Moses said to the people, “Do not fear! Stand firm and see the salvation of the Lord that he will provide for you today; for the Egyptians that you see today you will never, ever see again. 14 The Lord will fight for you, and you can be still.” 15 The Lord said to Moses, “Why do you cry out to me? Tell the Israelites to move on. 16 And as for you, lift up your staff and extend your hand toward the sea and divide it, so that the Israelites may go through the middle of the sea on dry ground. 17 And as for me, I am going to harden the hearts of the Egyptians so that they will come after them, that I may be honored because of Pharaoh and his army and his chariots and his horsemen. 18 And the Egyptians will know that I am the Lord when I have gained my honor because of Pharaoh, his chariots, and his horsemen.” <br /><br />30 So the Lord saved Israel on that day from the power of the Egyptians, and Israel saw the Egyptians dead on the shore of the sea. 31 When Israel saw the great power that the Lord had exercised over the Egyptians, they feared the Lord, and they believed in the Lord and in his servant Moses. </blockquote><h4 style="text-align: center;">The Door is Not Typical</h4>Sometimes you find yourself with mountains on both sides, a sea before you, and an enemy behind. There would seem to be no way out. Truth be told if you'd been praying God would have been telling you that you were headed here and why and you wouldn't be surprised. Never-the-less here you are. There is a door. God led you INTO this situation. You are not here because you made a mistake or took the wrong course. It's where God wanted you. You are in the perfect will of God, but it doesn't FEEL right.<br /><br />You don't SEE the door. But God has a door. Part of the reason you don't see the door is that it's unusual and nontraditional and out of the norm. In fact he never has opened this door before. It's the first time he's ever opened this type of door for anyone. How can you stay calm?<br /><br />How would you feel hemmed in on all sides with no apparent solution and no apparent way out? I'd feel like a cornered animal and start wanting to claw and fight my way out!&nbsp; <br /><br /><b>You have two options.&nbsp;</b><br /><ol><li><b>You can sit and whine and complain and cry and carry on. You can blame your leaders. You can threaten.</b></li><li><b>You can STOP, DROP, and PRAY. Go into LOW SLOW. Slow down your inner self until you can ask in faith expecting an answer. Don't ask what the solution is. Don't ask "Why?". Simply ask for instruction. What do you want me to do next? What is the next indicated step?</b></li></ol>If your prayer is full of worry and fret and anxiety, if you prayer is filled with a racing mind and many thoughts, you aren't there yet. Stop praying with words, and go into Worship. Find some worship music that inspires you and get into His presence. Find a way to focus on Him strong enough and long enough that all that other settles down and dissipates. Don't even pray for the answer. Just ask Him for the next indicated step and then thank Him for it until you have it. If you don't get it in one prayer session than keep returning until you have the next step.<br /><br />Be prepared, that next step may seem odd. It may seem unusual. In fact it may be something no one else has ever done. He may ask you to start walking into the water. He may ask you to walk around the city and then yell at it. He may ask you to bake your last food for someone else. He may ask you to start pouring your last little vessel of oil into borrowed jars.You get the point.<br /><br />Many times the door he has for you is unexpected and won't be based on anything you can plan on based on your experience.<br /><br /><h4 style="text-align: center;">Red Light Indicator</h4>There is a Red Light Indicator on your dashboard. It's a signal that something is wrong. If you try to hear instruction from God, and you can't hear it because your mind is busy, scattered, racing, full of many thoughts and/or worries... STOP. Go into Low Slow. That state of mind is an indication you are off course, at least mentally/emotionally, and you need to get back over onto Him!<br /><br /><br /><b>Have questions about anything I said here? Want to share your story? Comment Below!</b><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br />Blog:&nbsp;<a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a><br />Facebook:&nbsp;<a href="https://www.facebook.com/n2goodsuccess?sk=wall" target="_blank">https://www.facebook.com/n2goodsuccess</a><br />Twitter:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b style="background-color: white;">See Also:</b><br />Books by Darrell G. Wolfe:&nbsp;<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6" style="font-family: verdana, arial, helvetica, sans-serif; font-size: 13px;" target="_blank">Amazon.com/author/darrellgwolfe&nbsp;</a><br />Book Suggestions from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Brand and Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br /><br /><br /><br /><br />___<br /><br />