---
title: 'Jesus is The Good Shepherd. Who am I?'
date: '2013-10-22T12:40:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8354018531325635287'
blogger_filename: '/2013/10/jesus-is-good-shepherd-who-am-i.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<h4>COME:</h4><a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=1&amp;user_id=darrellwolfe&amp;version=107" target="_blank"></a><br /><blockquote class="tr_bq"><a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=1&amp;user_id=darrellwolfe&amp;version=107" target="_blank">John 10</a><br /><br /><span class="verse v1" data-usfm="JHN.10.1"><span class="label">1</span><span class="content"> “I tell you the solemn truth,</span><span class="note f"></span><span class="content"> the one who does not enter the sheepfold</span><span class="note f"></span><span class="content"> by the door,</span><span class="note f"></span><span class="content"> but climbs in some other way, is a thief and a robber. </span></span><span class="verse v2" data-usfm="JHN.10.2"><span class="label">2</span><span class="content"> The one who enters by the door is the shepherd of the sheep. </span></span><span class="verse v3 focused" data-usfm="JHN.10.3"><span class="label">3</span><span class="content"> The doorkeeper</span><span class="note f"></span><span class="content"> opens the door</span><span class="note f"></span><span class="content"> for him,</span><span class="note f"></span><span class="content"> and the sheep hear his voice. He</span><span class="note f"></span><span class="content"> calls his own sheep by name and leads them out.</span><span class="note f"></span><span class="content">  </span></span><span class="verse v4" data-usfm="JHN.10.4"><span class="label">4</span><span class="content"> When he has brought all his own sheep</span><span class="note f"></span><span class="content"> out, he goes ahead of them, and the sheep follow him because they recognize</span><span class="note f"></span><span class="content"> his voice. </span></span><span class="verse v5 selected" data-usfm="JHN.10.5"><span class="label">5</span><span class="content"> They will never follow a stranger,</span><span class="note f"></span><span class="content"> but will run away from him, because they do not recognize</span><span class="note f"></span><span class="content"> the stranger’s voice.”</span></span><br /><br /><span class="verse v5 selected" data-usfm="JHN.10.5"><span class="content"><span class="verse v7" data-usfm="JHN.10.7"><span class="content"> </span></span><span class="verse v8" data-usfm="JHN.10.8"><span class="label">8</span><span class="content"> All who came before me were</span><span class="note f"></span><span class="content"> thieves and robbers, but the sheep did not listen to them.</span><span class="note f"></span><span class="content">  </span></span><span class="verse v9" data-usfm="JHN.10.9"><span class="label">9</span><span class="content"> I am the door. If anyone enters through me, he will be saved, and will come in and go out,</span><span class="note f"></span><span class="content"> and find pasture.</span><span class="note f"></span><span class="content">  </span></span><span class="verse v10" data-usfm="JHN.10.10"><span class="label">10</span><span class="content"> The thief comes only to steal and kill</span><span class="note f"></span><span class="content"> and destroy; I have come so that they may have life, and may have it abundantly.</span></span> </span></span><br /><br /><span class="verse v26" data-usfm="JHN.10.26"><span class="content"></span></span><span class="verse v27" data-usfm="JHN.10.27"><span class="label">27</span><span class="content"> My sheep listen to my voice, and I know them, and they follow me. </span></span><span class="verse v28" data-usfm="JHN.10.28"><span class="label">28</span><span class="content"> I give</span><span class="note f"></span><span class="content"> them eternal life, and they will never perish;</span><span class="note f"></span><span class="content"> no one will snatch</span><span class="note f"></span><span class="content"> them from my hand. </span></span><span class="verse v29" data-usfm="JHN.10.29"><span class="label">29</span><span class="content"> My Father, who has given them to me, is greater than all,</span><span class="note f"></span><span class="content"> and no one can snatch</span><span class="note f"></span><span class="content"> them from my Father’s hand. </span></span><span class="verse v30" data-usfm="JHN.10.30"><span class="label">30</span><span class="content"> The Father and I</span><span class="note f"></span><span class="content"> are one.”</span></span></blockquote><br /><br /><br /><h4>HEAR:</h4>It sounds black and white. Jesus' sheep hear his voice and do not listen to another. But there is a caveat to this. You have to listen! How do those sheep, that are part of the flock, go astray? They follow their own desires, or get mislead by a stranger. Maybe the stranger does lead them, as much as he intimidates them. Either way, it is the shepherd that goes after them when they are found missing and rescues them from their own folly. <br /><br /><a href="http://www.biblegateway.com/passage/?search=Matthew+18%3A21-22&amp;version=NASB" target="_blank">Jesus told Peter </a>to forgive 70 times 7 times, that 490 times a day if need be. But scratch our forgiving others, that is secondary... first we most know, deeply know who WE are to Jesus, before we can treat others the way He would have us treat them. WE ARE the sheep that have gone astray. Some of us leave many times a day, some only every few weeks or months. Some of us wonder inches (we said something mean we shouldn't have said) some of us wonder miles (we shouldn't be this far away, doing this or that).<br /><br />No matter how far we've wondered, OR HOW OFTEN, Jesus is there to bring us back to the fold. I don't know anyone that has needed 490 forgiveness's a day, but I know Jesus would hold himself to a higher standard than he would Peter, so I have a feeling that would just be the beginning of his forgiveness's. He came all the way to earth, and died just for me... I am WORTH a lot to Him. <br /><br /><a href="http://www.youtube.com/watch?v=jtM7D_RN0jM" target="_blank">Life of the Shepherd</a><br /><div style="text-align: center;"><br /></div><div style="text-align: center;"><br /></div><div style="text-align: center;"><iframe allowfullscreen="" frameborder="0" height="360" src="//www.youtube.com/embed/jtM7D_RN0jM" width="480"></iframe></div><div style="text-align: center;"><br /></div><div style="text-align: center;"><br /></div><a href="http://www.biblestudytools.com/lexicons/greek/nas/ginosko.html" target="_blank"><u><b>Know </b></u></a>who you are to the Good Shepherd, and you will find it easier to get along with the sheep in your fold.<br /><h4>DO:</h4>I'm going to ponder who I am to HIM, and attempt to see others (co-workers, bosses, customer, family, etc) through His eyes today. <br /><br /><br /><br /><b>How about you? You see anything to add to this? Want to  share what examples you have seen or experience in yourself or others?  Comment below.&nbsp;</b><br /><div><b><br /></b></div><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br /><b>Blog</b>:&nbsp;<a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br /><b>Facebook</b>:&nbsp;<a href="https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118" target="_blank">Facebook.Com/EmpoweredTooProsper</a><br /><b>Twitter</b>:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b>See Also: </b><br /><a href="https://www.facebook.com/n2goodsuccess" target="_blank">https://www.facebook.com/n2goodsuccess </a><br /><a href="https://www.facebook.com/towdahaudio" target="_blank">https://www.facebook.com/towdahaudio</a><br /><a href="https://www.facebook.com/TexasLivingInfo" target="_blank">https://www.facebook.com/TexasLivingInfo</a>