---
title: 'God Protects'
date: '2013-09-13T11:06:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8738815146930269362'
blogger_filename: '/2013/09/god-protects.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<h4>COME:</h4><a href="https://www.bible.com/bible/1/gen.7.kjv" target="_blank"><br /></a><a href="https://www.bible.com/bible/1/gen.7.kjv" target="_blank">Genesis 7</a><br /><div class="p"><span class="verse v22" data-usfm="GEN.7.22"><span class="label">22</span><span class="content">All in whose nostrils was the breath of life, of all that was in the dry land, died.</span><span class="note f"></span></span></div><div class="p"><span class="verse v23" data-usfm="GEN.7.23"><span class="label">23</span><span class="content">And  every living substance was destroyed which was upon the face of the  ground, both man, and cattle, and the creeping things, and the fowl of  the heaven; and they were destroyed from the earth: and Noah only  remained alive, and they that were with him in the ark.</span></span></div><br /><br /><h4>HEAR:</h4>Again, God in his Mercy finds a man, not a perfect man but one that will serve God. Just as Abraham believed God and it was credited to him as Righteousness so here Noah believed God, as evidenced by his undertaking this HUGE building project with no sign that it would be needed. Yet again, in the midst of sin God seeks to protect and cover. He finds one man willing to believe and covers him and his family. He protects the seed of Eve though him. <br /><br /><br /><br /><h4>DO:</h4>Believe God today... <br /><br /><br /><br /><br /><b>How about you? You see anything to add to this? Want to  share what examples you have seen or experience in yourself or others?  Comment below.&nbsp;</b><br /><div><b><br /></b></div><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br />Blog:&nbsp;<a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br />Facebook:&nbsp;<a href="https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118" target="_blank">Facebook.Com/EmpoweredTooProsper</a><br />Twitter:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b style="background-color: white;">See Also:</b><br />Books by Darrell G. Wolfe:&nbsp;<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6" style="font-family: verdana, arial, helvetica, sans-serif; font-size: 13px;" target="_blank">Amazon.com/author/darrellgwolfe&nbsp;</a><br />Book Suggestions from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Brand and Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a>