---
title: 'Levels of Change Part Nine'
date: '2013-11-12T20:50:00.0020000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8665390026611446848'
blogger_filename: '/2013/11/levels-of-change-part-nine_2.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Spiritual Growth'
  - 'Keys To Success'
  - 'Faith'
  - 'Freedom'
---

<br /><div align="center" class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto; mso-outline-level: 2; text-align: center;"><b><span style="font-family: &quot;Times New Roman&quot;,&quot;serif&quot;; font-size: 18.0pt; mso-fareast-font-family: &quot;Times New Roman&quot;;">Foundations Class #2</span></b></div><div align="center" class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto; mso-outline-level: 2; text-align: center;"><b><span style="font-family: &quot;Times New Roman&quot;,&quot;serif&quot;; font-size: 18.0pt; mso-fareast-font-family: &quot;Times New Roman&quot;;">Levels of Change</span></b></div><div align="center" class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto; mso-outline-level: 3; text-align: center;"><b><span style="font-family: &quot;Times New Roman&quot;,&quot;serif&quot;; font-size: 13.5pt; mso-fareast-font-family: &quot;Times New Roman&quot;;">Bob Hamp</span></b></div><div align="center" class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto; mso-outline-level: 4; text-align: center;"><b><span style="font-family: &quot;Times New Roman&quot;,&quot;serif&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Times New Roman&quot;;"><a href="http://gatewaypeople.com/ministries/freedom-kairos/media1">Class can be seen on GatewayPeople.Com</a></span></b></div><div align="center" class="MsoNormal" style="line-height: normal; mso-margin-bottom-alt: auto; mso-margin-top-alt: auto; mso-outline-level: 4; text-align: center;"><br /></div><div class="MsoNormal" style="text-align: center;"><b><span style="font-family: &quot;Times New Roman&quot;,&quot;serif&quot;; font-size: 12.0pt; mso-fareast-font-family: &quot;Times New Roman&quot;;">Part Nine</span></b><i> </i></div><br /><h4 style="text-align: center;">A Parable: The Kingdom of God is like: <a href="http://www.youtube.com/watch?v=5BlsoyE1CIw" target="_blank">Phantom Limb Syndrome</a></h4><ul><li><a href="http://www.webmd.com/pain-management/guide/phantom-limb-pain" target="_blank">http://www.webmd.com/pain-management/guide/phantom-limb-pain</a></li><li><a href="http://www.youtube.com/watch?v=5BlsoyE1CIw" target="_blank">http://www.youtube.com/watch?v=5BlsoyE1CIw&nbsp;</a></li><li><a href="http://www.youtube.com/watch?v=YL_6OMPywnQ" target="_blank">http://www.youtube.com/watch?v=YL_6OMPywnQ </a></li><li>Phantom Limb Syndrome is where a limb, a leg for example, is  removed, but the brain still sends signals as though it's there. The  missing foot can itch, burn, hurt, etc. </li></ul><div style="text-align: center;"></div><div style="text-align: center;"><iframe allowfullscreen="" frameborder="0" height="315" src="//www.youtube.com/embed/5BlsoyE1CIw" width="560"></iframe></div><div style="text-align: center;"><br /></div><br />When  doctors treat the symptom of the nervous system (ei: giving Tylenol  when the missing foot hurts) they can actually strengthen the nervous  systems embedded reactions telling the brain the leg is still in tact.  It was successful temporarily, but it maintained the lie over time. This  was because as the treatment made it better for a moment and then it  got worse again, and more medicine made it better, but then it got worse  again, and it could strengthen the programing of the brain. <br /><br /><h4 style="text-align: center;">Phantom Limb Syndrome Solution</h4>Instead some doctors who know this  will instead prescribe a series of treatments that engage the new nerve  endings. Touch the NEW nerve endings with hot things, cold things,  prickly things, soft things, as many new sensations as possible to  stimulate the NEW nerve endings, telling the nervous system through new  experiences that something has indeed change, allowing the brain to be  re-routed for this new information. Get the FOCUS of the brain to what  is NEW THERE. <br /><br />In order to allow the new nature you  were born with to reprogram our nervous system we must begin to  stimulate the new nerve endings, which allows the nervous system to  reprogram those new experiences into our beliefs. <br /><br />Many  people who get saved are told to go to church, read your bible, pray,  etc... Newsflash... you don't HAVE to do any of those things. They have  nothing to do with your going to heaven or being saved. <br /><br />However  the Bible is a book full of Words written BY GOD FOR YOU and it's full  of information about what has been done in you already. Instead of  wrestling with a dead man who isn't there anymore we can begin to  stimulate our nervous system to what is NEW in us. Going to church and  being with other believers, hearing the Word Taught, but also talking  WITH other believers allows us to renew our nervous system to that which  is NEW there. Bible Reading, Pastors Messages, Prayer, Church  Gathering, Etc are all ways to stimulate what is new about you, that  which has ALREADY happened.<br /><br />The more of these you do,  with the mindset that you are not doing them "to become", but rather,  "to discover" what you "have become", the faster we can re-program our  nervous system to understand what is new about us and what has died.<br /><br /><div class="MsoNormal"></div><div class="MsoNormal"><h4>The Struggle: The Old You is dead. The New You is alive. The FLESH has old programming left over from the old you. You are not fighting the old you. That you is dead. What must be done now is to teach and train the flesh that something NEW has happened.</h4></div><div class="MsoNormal"><br /></div><i>*The teachings of this class are not my own, they are derived from notes I took during a class at Gateway Church. You may view the class on their website by following the link at the top of the page.</i><br /><br />__<br /><br /><b>Have questions about anything I said here? Want to share your story? Comment Below!</b><br /><b><br />I call you empowered 2 prosper with good success!</b><br /><b><br />N2 Good Success</b><b><span style="font-size: 10.0pt;">Darrell G. Wolfe</span></b><br />Blog:&nbsp;<a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a><br />Facebook:&nbsp;<a href="https://www.facebook.com/n2goodsuccess?sk=wall" target="_blank">https://www.facebook.com/n2goodsuccess</a><br />Twitter:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b><span style="background: white;">See Also:</span></b><br />Books by Darrell G. Wolfe:&nbsp;<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6" target="_blank"><span style="font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; font-size: 10.0pt;">Amazon.com/author/darrellgwolfe&nbsp;</span></a><br />Book Suggestions from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Brand and Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br /><div class="MsoNormal"><br /></div>