---
title: 'Parable of Two Sons'
date: '2013-09-09T12:21:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5963983456399634581'
blogger_filename: '/2013/09/parable-of-two-sons.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<h4>COME:</h4><div class="heading passage-class-0"><h3><a href="http://www.biblegateway.com/passage/?search=Luke+15%3A11-32&amp;version=NIV" target="_blank">Luke 15:11-32</a></h3><div class="txt-sm">New International Version (NIV)</div></div><h3><span class="text Luke-15-11" id="en-NIV-25600">The Parable of the Lost Son</span></h3><span class="text Luke-15-11"><sup class="versenum">11&nbsp;</sup>Jesus continued: <span class="woj">“There was a man who had two sons.</span></span> <span class="text Luke-15-12" id="en-NIV-25601"><span class="woj"><sup class="versenum">12&nbsp;</sup>The younger one said to his father, ‘Father, give me my share of the estate.’ So he divided his property between them.</span></span><br /><span class="text Luke-15-13" id="en-NIV-25602"><span class="woj"><sup class="versenum">13&nbsp;</sup>“Not long after that, the younger son got together all he had, set off for a distant country and there squandered his wealth in wild living.</span></span><br /><h4>HEAR:</h4>BOTH son's were part of the family first, one left to do some wild living and the other son stayed and did his duty but with no real joy of serving. BOTH sons were wrong. However I just noticed something else...<br /><br />BOTH sons were sons. One wasn't adopted in. Therefore both these boys were part of the family of God, both were "saved" and they went two ways. One served religiously, one went off on his own and ignored his status as a son. Both were of the family.<br /><br />This isn't a story of someone coming to Christ. This is a story of people who are already IN Christ needing to learn who they are and who they are OF. They both had something to learn. <br /><br /><h4>DO:</h4>I need to spend time today thinking about who I AM IN CHRIST! <br /><br /><br /><br /><b>How about you? You see anything to add to  this? Want to share what examples you have seen or experience in  yourself or others? Comment below.&nbsp;</b><br /><div><b><br /></b></div><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br />Blog:&nbsp;<a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br />Facebook:&nbsp;<a href="https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118" target="_blank">Facebook.Com/EmpoweredTooProsper</a><br />Twitter:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b style="background-color: white;">See Also:</b><br />Books by Darrell G. Wolfe:&nbsp;<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6" style="font-family: verdana, arial, helvetica, sans-serif; font-size: 13px;" target="_blank">Amazon.com/author/darrellgwolfe&nbsp;</a><br />Book Suggestions from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Brand and Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br /><br /><br /><br /><br />