---
title: 'Vision and Mission'
date: '2013-11-04T21:03:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4984666978904824114'
blogger_filename: '/2013/11/vision-and-mission.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'News and Current Events'
---

<h4>Mission of N2GS</h4><div class="widget-content"><div style="text-align: center;"><span><span style="line-height: 18px;"><b>Providing the tools you need&nbsp;to enter&nbsp;Into <a href="http://n2gs.blogspot.com/2012/03/good-success.html" target="_blank">Good Success</a>!</b></span></span></div><div style="font: 100% Georgia, serif;"><b style="font-family: 'trebuchet ms', Trebuchet, sans-serif; font-size: 13px; line-height: 18px;"><span style="color: #251a9c;"><blockquote class="tr_bq"><div style="font: 100% Georgia, serif;"><b style="font-family: 'trebuchet ms', Trebuchet, sans-serif; font-size: 13px; line-height: 18px;"><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"><span style="color: #251a9c;">Joshua 1:8 - Interlinear Bible</span></a><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"></a></b></div><div class="versetext" style="font: 100%/20px arial; margin: 10px 0px 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;">This </div></blockquote></span></b></div></div><a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=h&amp;t=kjv&amp;sn=05612" style="text-decoration: none;"><span style="color: #251a9c;">book</span></a><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"> of the </a><a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=h&amp;t=kjv&amp;sn=08451" style="text-decoration: none;"><span style="color: #251a9c;">law</span></a><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"> shall not </a><a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=h&amp;t=kjv&amp;sn=04185" style="text-decoration: none;"><span style="color: #251a9c;">depart</span></a><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"> out of thy </a><a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=h&amp;t=kjv&amp;sn=06310" style="text-decoration: none;"><span style="color: #251a9c;">mouth;</span></a><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"> but thou shalt </a><a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=h&amp;t=kjv&amp;sn=01897" style="text-decoration: none;"><span style="color: #251a9c;">meditate</span></a><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"> therein </a><a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=h&amp;t=kjv&amp;sn=03119" style="text-decoration: none;"><span style="color: #251a9c;">day</span></a><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"> and </a><a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=h&amp;t=kjv&amp;sn=03915" style="text-decoration: none;"><span style="color: #251a9c;">night,</span></a><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"> that thou mayest </a><a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=h&amp;t=kjv&amp;sn=08104" style="text-decoration: none;"><span style="color: #251a9c;">observe</span></a><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"> to </a><a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=h&amp;t=kjv&amp;sn=06213" style="text-decoration: none;"><span style="color: #251a9c;">do</span></a><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"> according to all that is </a><a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=h&amp;t=kjv&amp;sn=03789" style="text-decoration: none;"><span style="color: #251a9c;">written</span></a><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"> therein: for then thou shalt </a><a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=h&amp;t=kjv&amp;sn=06743" style="text-decoration: none;"><span style="color: #251a9c;">make</span></a><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"> thy </a><a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=h&amp;t=kjv&amp;sn=01870" style="text-decoration: none;"><span style="color: #251a9c;">way</span></a><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"> </a><a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=h&amp;t=kjv&amp;sn=06743" style="text-decoration: none;"><span style="color: #251a9c;">prosperous</span></a><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"> , and then thou shalt have good </a><a href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=h&amp;t=kjv&amp;sn=07919" style="text-decoration: none;"><span style="color: #251a9c;">success</span></a><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv" style="text-decoration: none;" target="_blank"> .</a><h4>Vision of N2GS</h4><ul><li><strong>Providing Biblical Answers to Practical Problems</strong></li><li><strong>People walking free</strong> (<em>spiritually, emotionally, mentally, intelectually, physically,&nbsp;and financially</em>) <strong>to pursue the perfect will of God for their lives</strong></li><li><strong>People living disconnected from the World's System. </strong></li><li><strong>Blog Posts, Books, Merchandise, and other creative arts maerials, provided to aide and asist in that freedom. </strong></li></ul><br />DW