---
title: 'Don&#39;t Be Devoured'
date: '2013-11-14T15:21:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6456610006093930055'
blogger_filename: '/2013/11/don-be-devoured.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<h4>COME:</h4><br /><blockquote class="tr_bq"><a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">1 Peter 5:8&nbsp;</a><br /><br />8Be sober, be vigilant; because your adversary the devil walks about like a roaring lion, seeking whom he may devour. </blockquote><h4>HEAR:</h4>Today in my <a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">Joseph Prince Devotional</a> reading plan on YouVersion, he brought up a very interesting point. The devil is SEEKING WHOM he may devour. He doesn't have the right to just devour whomever he wants to.<br /><br />I've been dealing with a lot of conflicting emotions this year, and conflicting plans. But I have a say in whether the Devil devours me, my emotions, and my time. I have to make that choice every time I become aware of it.&nbsp; <br /><h4>DO:</h4>Be aware of the things that would devour in my life, and take a stand on the Word against them. <br /><br /><br /><b>How about you? You see anything to add to this? Want to  share what examples you have seen or experience in yourself or others?  Comment below.&nbsp;</b><br /><div><b><br /></b></div><b>I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>© N2 Good Success</b><b><span style="font-size: x-small;"> Darrell G. Wolfe</span></b><br /><div class="separator" style="clear: both; text-align: center;"><a href="/images/imported/blogger-googleusercontent-com/e2p-logo-b7b5454b818d.jpg" style="margin-left: 1em; margin-right: 1em;"><br /></a></div><b>Blog</b>:&nbsp;<a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br /><b>Facebook</b>:&nbsp;<a href="https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118" target="_blank">Facebook.Com/EmpoweredTooProsper</a><br /><b>Twitter</b>:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><br />