---
title: 'Lotto?'
date: '2013-02-08T09:00:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3667833905719824696'
blogger_filename: '/2013/02/lotto.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Object Lessons'
---

So the other day I talked to a man who was not planning to start a ministry or business by taking steps or making steps toward it. He was just "planning" to win the lotto so that he can go on missions trips and evangelize. But he's doing NOTHING toward that end until he wins the lotto. And he was serious about planning to win. He got mad when I laughed about the plan.<br /><br />Amazing! A grown man, at retirement age “planning”  on winning the lotto so that he can go on the missions field. Maybe, just maybe, God told him that would be His plan. Wealth transfer from the wicked to the righteous is in God’s M.O. But God isn’t about luck. If God called you to the missions field He has a billion ways to supply you and He doesn’t want you waiting on the lotto. What are you going over to teach people? Just trust God and win the lotto or trust God and HE will provide for you?<br /><br />Now, I believe God will take money away from the World and use them to fund you. He may tell you to go buy a lotto ticket in a strategic move. If God told you to buy it you'll win though. You won't need to go buy it again and again and again... There was once, many years ago, when I happened to be eating at a casino on Christmas day because it was the only place open and I wasn't paying my Dad was. As I walked outside I noticed a machine and had a nickel in my pocket. I felt a strong pull toward a machine. I ignored it thinking God wouldn't want me gambling, but I couldn't shake it. So I walked over, pulled the handle and lights went off and sounds happened and I got nevous, I thought I broke it!<br /><br />The man next to me says "just stay there and a lady will come and give you some money!" I said, well ok then! This lady comes and gives me over $750 in cash and then the machine drops $200 in coins on top of that. I had been praying all that week for the money to register my car and smog it. Praise God for unusual provision. But you know God has never sent me back into a casino again. It was an instruction for one time. It was obedience to pull the handle once. Going back in to pull the handle again hoping to duplicate the results would be seeking men rather than seeking God. God's not a formula.<br /><br />So what about this man who plans to win the lotto? Well there was a man who did just that. He was a statician and figured the most likely winning numbers and played them over and over for years. He won mini pots of a few hundred and even a few thousand several times and then won the big one. Millions! He took that money straight to a team of advisors and set out a plan to turn it into billions. There was a man who didn't just SAY he was going to win, he developed a strategy.<br /><br />What am I saying? This man who said he was going to win the lotto and go on missions trips... did he hear from God? Maybe he did. And maybe he'll go on missions trips. I'll tell you know that if he doesn't go he didn't hear. The thing is... he wasn't making any plans. He didn't go get his passport, or plan for the handling of that money or estate planning or check into international business/banking. He didn't DO anything to plan. Therefore I doubt his plan was faith.<br /><br />What is your vision for the future... what are you doing about it now?<br /><br />DW<br /><br /><br /><b>Have questions about anything I said here? Want to share your story? Comment Below!</b><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br />Blog:&nbsp;<a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a><br />Facebook:&nbsp;<a href="https://www.facebook.com/n2goodsuccess?sk=wall" target="_blank">https://www.facebook.com/n2goodsuccess</a><br />Twitter:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b style="background-color: white;">See Also:</b><br />Books by Darrell G. Wolfe:&nbsp;<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6" style="font-family: verdana, arial, helvetica, sans-serif; font-size: 13px;" target="_blank">Amazon.com/author/darrellgwolfe&nbsp;</a><br />Book Suggestions from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Brand and Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br />Other Blogs and Sites by the Wolfe Family:&nbsp;<a href="http://wfconceptions.wordpress.com/" target="_blank">http://wfconceptions.wordpress.com/&nbsp;</a><br />