---
title: 'Leviathan'
date: '2013-09-06T13:28:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5558956343247087914'
blogger_filename: '/2013/09/leviathan.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'Daily Reading'
---

I've always thought of leviathan as the dragon flying in the sky, but the verses that talk of it indicate it is a deep see creature, that breathes fire. Could be interesting for later study...<br /><br /><br /><br /><br /><a href="http://bible.us/1/psa.104.26.kjv" target="_blank">Psalms 104</a><br />24O Lord, how manifold are thy works! in wisdom hast thou made them all: the earth is full of thy riches. 25So is this great and wide sea, wherein are things creeping innumerable, both small and great beasts. 26There go the ships: there is that leviathan, whom thou hast made to play therein. 27These wait all upon thee; that thou mayest give them their meat in due season. <br /><br /><br /><br /><ul class="resource_list"><li class="reference"><h3><a href="https://www.bible.com/bible/1/job.41.1.kjv">Job 41:1 (KJV)</a></h3>Canst thou draw out leviathan with an hook? or his tongue with a cord which thou lettest down? <br /> </li><li class="reference"><h3><a href="https://www.bible.com/bible/1/psa.74.14.kjv">Psalms 74:14 (KJV)</a></h3>Thou brakest the heads of leviathan in pieces, and gavest him to be meat to the people inhabiting the wilderness. <br /> </li><li class="reference"><h3><a href="https://www.bible.com/bible/1/psa.104.26.kjv">Psalms 104:26 (KJV)</a></h3>There go the ships: there is that leviathan, whom thou hast made to play therein. <br /> </li><li class="reference"><h3><a href="https://www.bible.com/bible/1/isa.27.1.kjv">Isaiah 27:1 (KJV)</a></h3>In that day the Lord with his sore and great and strong sword shall  punish leviathan the piercing serpent, even leviathan that crooked  serpent; and he shall slay the dragon that is in the sea. <br /> </li></ul><div id="sidebar"></div><footer class="" id="footer" role="contentinfo"></footer><br />