---
title: 'Hearing God - The Answer to writers block'
date: '2013-11-08T04:01:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3860586062291380864'
blogger_filename: '/2013/11/hearing-god-answer-to-writers-block.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Gateway Freedom Ministries'
  - 'study'
  - 'Random'
  - 'breakthrough'
  - 'Word of The Lord'
  - 'Daily Reading'
---

<h4>Hearing God:</h4><blockquote class="tr_bq"><a href="http://m.biblestudytools.com/nkjv/psalms/140-6.html">Psalm 140:6 NKJV</a><br />I said to the Lord: "You are <span class="Highlight">my</span> God; <span class="Highlight">Hear</span> the <span class="Highlight">voice</span> of <span class="Highlight">my</span> supplications, O Lord. </blockquote><blockquote class="tr_bq"><a href="http://m.biblestudytools.com/nkjv/romans/10-17.html">Romans 10:17 NKJV</a><br />So then faith comes by <span class="Highlight">hearing</span>, and <span class="Highlight">hearing</span> by the word of <span class="Highlight">God</span>.<br /><a href="http://m.biblestudytools.com/nkjv/matthew/17-5.html">Matthew 17:5 NKJV</a><br />While he was still speaking, behold, a bright cloud overshadowed them; and suddenly a <span class="Highlight">voice</span> came out of the cloud, saying, "This is <span class="Highlight">My</span> beloved Son, in whom I am well pleased. <span class="Highlight">Hear</span> Him!" <br /><a href="http://m.biblestudytools.com/nkjv/john/10-16.html">John 10:16 NKJV</a><br />And other sheep I have which are not of this fold; them also I must bring, and they will <span class="Highlight">hear</span> <span class="Highlight">My</span> <span class="Highlight">voice</span>; and there will be one flock and one shepherd.<br /><a href="http://m.biblestudytools.com/nkjv/john/10-27.html">John 10:27 NKJV</a><span class="Highlight">&nbsp;</span><br /><span class="Highlight">My</span> sheep <span class="Highlight">hear</span> <span class="Highlight">My</span> <span class="Highlight">voice</span>, and I know them, and they follow Me.</blockquote><br />Isn't it intersting how if you look up "hear" or "hearing" in the bible all the old testament is man asking God to hear them. And then Jesus comes and it's about US hearing HIM!<br /><br /><h4>Theme of Hearing God:</h4><br />There has been this theme popping up everywhere, in everything I listen to, it comes up in conversations, I hear it taught and preached in a way I've never heard it. I don't know if I'm the only one catching this wind or if there are others. It is "Hearing God".<br /><ul><li>A Men's class teacher talked about taking part of his prayer time and sitting at the computer praying silently and writing down whatever he hears God saying into notes.</li><li>I recalled Kenneth Copeland telling a story about a man who was whining to God and all of a sudden he had a revelation: <i>&nbsp;</i></li><ul><li><i>*Here sits a man who knows nothing doing all the talking to the one who knows everything!</i></li></ul><li>As I'm writing down a list of things I want to make part of my Spiritual Fitness Plan I have the impression that I should dedicate the first moments of my day, before I get out of Bed to simply asking God what He'd like to tell me or talk about before I start the day and then SHUT UP and Listen!</li><li>Pastor Jerry Dirman on a podcast talks about not hearing as clearly so he'll just stop what he's doing sometimes and go outside and put his hands into the air and say "I'm listening Father"&nbsp;</li><li>I hear Jeremy Pearsons talking about not just choosing to believe for this or that, but asking God: "Father, how would you have me believe you regarding this thing?" or "What do you want to do with this or that?"&nbsp;</li><li>Bob Hamp is ministering to a woman and he hands her a list of scriptures. Tells her to read them silently, NOT out loud. And tells her to ask God to read them to her... interesting thought. It's not US reading His Word to us that matters as much as HIM reading His Word to us!</li></ul>I am realizing that hearing God's Word doesn't just mean reading the bible, hearing the bible on Audio tapes, or even hearing the Bible Taught by other people. So often I hear things like "<i>One Word from God will change your life forever!</i>" and I think to myself: "<i>Yeah, that's good. I need to read more bible and listen to more teaching tapes, and do more scripture confessions...</i>" I may have even entertained that God may speak directly to me from time to time, or a scripture would pop off the page as I read... but it always felt more like hunting for God's voice on a scavenger hunt through his Book. But that's not really it at all!<br /><br />It's about hearing God speak to us directly, daily, hourly, moment by moment. Literally waiting to hear from God before we take the next step.<br /><br />How often have I developed a plan (or worked on a project), feeling led or impressed at some level (or not), asking God to bless my project or help lead me through my project. This isn't bad, but there is a higher order available.<br /><br />What if, first of all, I asked Him if I should be working on that project at all? What if before I ever sat down to work on anything I asked Him what He'd like me to be doing? What if he tells me to do the dishes when I'd like to be writing, or tells me to be writing when I'd rather distract myself with doing the dishes.<br /><h4>Writers Block Revelation</h4><br />Today at lunch I had a deeper revelation of something God's been trying to impress me with. Sometimes it helps to start talking to other people and He can start speaking to all of us through me as I'm talking. This one not only gave me excitement, and I could feel God's anointing on it, I could feel His voice speaking through me to me... but the guys seemed to feel it too. Even said I should record it and turn it into a TED Talk... maybe I will someday after I've had a chance to vet it out. What was that revelation?<br /><br />You sit down and start to work on a creative project (writing or song writing for me, maybe it's art or woodwork, or excel for you). It feels right at first. Everything is flowing. Then it starts to gum up. Slows down. Then it's feels awful. Like you have just bitten something bitter. It's as though something in you is resisting harder and harder to take another step. It's like gum on you shoe. It's like molasses inside of you. It's harder and harder to move forward, until eventually you just throw your hands up and quit the project. Some quit for a few minutes, hours, days, some quit for years or never return at all. Many writers call this writers block.<br /><blockquote class="tr_bq">Michael Hyatt said: <i>Hobby writers write when they are inspired, but professional writers are inspired when they write.</i>&nbsp;</blockquote>I also heard someone say this week that: <br /><blockquote class="tr_bq"><i>"...your conscience isn't just for telling you when something is right or wrong. It's much broader than that. It affects everything you do. You conscience is there to tell you if you are on track with God, moment by moment."</i></blockquote>Many writers tell about how they feel: "<i>The story wants to go one direction, and if I try to force it the story gets dry and boring and it's harder and harder to write.</i>". Well what if that is because the Holy Spirit&nbsp; is trying to direct you another way? <br /><br />This got me thinking about this hearing God thing. What if writers block isn't a bad thing at all, but in fact a tool God has given you. When it was flowing you were tracking with Him. The Holy Spirit is our inspiration. He is the one who inspires men to create in the first place.<br /><br />So rather than asking Him to help you with your project... why don't you stop everything. Ask Him what He'd like you to help Him write (create)? Now THAT is inspired creating and you don't ever have to be "blocked" if you are working with THE Inspirer on HIS project! <br /><br />However, He only gives piece by piece, section by section. It's as though you are working with him to create an entire room but all he gives you is a three inch by three inch square. As He gives you more squares you start to think that you know where it's going so you take off running with it. And you may have been right at first but now you are running in a direction He isn't leading and it's you making it up on your own and it gets harder and harder and gums up. It's not because you are a bad writer, or that you "lost your inspiration" so you need to stop for awhile... it's because you left your inspiration behind and took off running on your own. Just stop. Breath. Forget everything you did after you felt that "inner molasses" start to build up.<br /><br />Ask the Holy Spirit: "Holy Spirit, I apologize for taking off without you. Where were we again? Show me what YOU would like to write about?" Then wait. Don't just start writing. Wait until you hear Him. It may not be audible. But there will be a sentence, a word, an image, a sound, a feeling, something. Go back to writing square by square, as He shows you each peice.<br /><h4>REST:</h4>Be willing to stop when He does. He knows your needs better than you do and He knows that you MUST rest your body and mind. He will tell you to stop before you feel you are ready to stop, sometimes. Adrenaline is telling your body/mind to keep going. If He tells you to put it down, do it. Follow Him square by square. ONLY as you follow His lead, will the room look the way He intended. <br /><br />&nbsp;DW