---
title: 'Grace and Mercy (Fall and Redemption)'
date: '2013-09-12T15:29:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '644890312905306518'
blogger_filename: '/2013/09/grace-and-mercy-fall-and-redemption.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'Daily Reading'
---

<h4>COME:</h4><blockquote class="tr_bq"><a href="https://www.bible.com/bible/114/gen.3.nkjv" target="_blank">&nbsp;Genesis 3</a><br /><div class="p"><span class="verse v21" data-usfm="GEN.3.21"><span class="label">21</span><span class="content">Also for Adam and his wife the </span><span class="sc"><span class="content">Lord</span></span><span class="content"> God made tunics of skin, and clothed them.</span></span></div><div class="p"><span class="verse v22" data-usfm="GEN.3.22"><span class="label">22</span><span class="content">Then the </span><span class="sc"><span class="content">Lord</span></span><span class="content"> God said, “Behold, the man has become like one of Us, to know good and  evil. And now, lest he put out his hand and take also of the tree of  life, and eat, and live forever”— </span></span><span class="verse v23" data-usfm="GEN.3.23"><span class="label">23</span><span class="content">therefore the </span><span class="sc"><span class="content">Lord</span></span><span class="content"> God sent him out of the garden of Eden </span><span class="note x"></span><span class="content">to till the ground from which he was taken. </span></span><span class="verse v24" data-usfm="GEN.3.24"><span class="label">24</span><span class="content">So </span><span class="note x"></span><span class="content">He drove out the man; and He placed </span><span class="note x"></span><span class="content">cherubim </span><span class="note x"></span><span class="content">at the east of the garden of Eden, and a flaming sword which turned every way, to guard the way to the tree of </span><span class="note x"></span><span class="content">life.</span></span></div><br /><br /><a href="https://www.bible.com/bible/114/gen.4.nkjv" target="_blank">Genesis 4</a><br /><div class="p"><span class="verse v13" data-usfm="GEN.4.13"><span class="label">13</span><span class="content">And Cain said to the </span><span class="sc"><span class="content">Lord</span></span><span class="content">, “My punishment </span><span class="it"><span class="content">is</span></span><span class="content"> greater than I can bear! </span></span><span class="verse v14" data-usfm="GEN.4.14"><span class="label">14</span><span class="content">Surely You have driven me out this day from the face of the ground; </span><span class="note x"></span><span class="content">I shall be </span><span class="note x"></span><span class="content">hidden from Your face; I shall be a fugitive and a vagabond on the earth, and it will happen </span><span class="it"><span class="content">that</span></span><span class="content">  </span><span class="note x"></span><span class="content">anyone who finds me will kill me.”</span></span></div><div class="p"><span class="verse v15" data-usfm="GEN.4.15"><span class="label">15</span><span class="content">And the </span><span class="sc"><span class="content">Lord</span></span><span class="content"> said to him, “Therefore, whoever kills Cain, vengeance shall be taken on him </span><span class="note x"></span><span class="content">sevenfold.” And the </span><span class="sc"><span class="content">Lord</span></span><span class="content"> set a </span><span class="note x"></span><span class="content">mark on Cain, lest anyone finding him should kill him.</span></span></div><br /><a href="https://www.bible.com/bible/114/gen.4.nkjv" target="_blank">Genesis 4</a><br /><div class="p"><span class="verse v25" data-usfm="GEN.4.25"><span class="label">25</span><span class="content">And Adam knew his wife again, and she bore a son and </span><span class="note x"></span><span class="content">named him Seth, “For God has appointed another seed for me instead of Abel, whom Cain killed.” </span></span><span class="verse v26" data-usfm="GEN.4.26"><span class="label">26</span><span class="content">And as for Seth, </span><span class="note x"></span><span class="content">to him also a son was born; and he named him Ē´nosh. Then </span><span class="it"><span class="content">men</span></span><span class="content"> began </span><span class="note x"></span><span class="content">to call on the name of the </span><span class="sc"><span class="content">Lord</span></span><span class="content">.</span></span></div></blockquote><br /><h4>HEAR:</h4>In the midst of our sin, fallen state God is merciful. Despite the Sin of Adam God provides proper covering for them. He sheds the blood of a lamb and provides tunics for them. Their own attempts at covering were inadequate at best. Fig leaves. He then locks them out of the Garden and from the Tree of Life. This is also for their benefit. A seed of Ishshah is to be born that will be bitten by the Great Serpent but will crush his head. A redeemer is to come. If they were to eat of the Tree of Life too they would be locked into this fallen state forever, that truly would be Hell. The longer men lived the more their minds grew darker and more wicked. <br /><br />From their first children we see Murder has begun. Keyin is driven to the wilderness after killing Hevel the Righteous. Again we see God's Mercy and Grace covering Keyin's murder with a protective covering.<br /><br />We see God blessing Ish and Ishshah with a third son Shet. And Men began to call on the name of the Lord at that time. (by the way this means that all this took place over a LONG time and there were other sons and daughters of Ish and Keyin and Hevel before Shet came along. Populations were growing in the earth.)<br /><br />Every time we fall, EVERY TIME, God's Mercy, Grace, Love is there to cover us and restore us, or at least protect us. Keyin would have had some restoration had he been repentant, I'm sure of it. Since he was not, God could only protect him instead. Even if you are running from God, God is still watching out for you and protecting you as best as you allow him too. That still small bad feeling about going to a certain place, or taking a certain route are God trying to protect you.<br /><br />Despite anything we do, even murder, God is there wanting to restore, protect, and show great GRACE to us! <br /><br /><br /><h4>DO:</h4>I'm going to show more Mercy and Grace to others today, given all that I've been given. <i>Lord, show my how to be a conduit for your Grace and Mercy today. </i><br /><br /><h4>Side Note 1:</h4><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=genesis+2&amp;t=kjv" target="_blank">Genesis 2</a> Man calls names his female counterpart: Woman (H0802 '<a href="http://www.biblestudytools.com/lexicons/hebrew/kjv/ishshah-2.html" target="_blank">Ishshah</a>) Bone of my bones, flesh of my flesh. In their pre sin state she his counterpart. Literally Opposite of Man.<br /><br /><br /><a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=genesis+3&amp;t=kjv" target="_blank">Genesis 3</a> After the fall man calls his female counterpart Eve Mother of all living (H02332 <a href="http://www.biblestudytools.com/lexicons/hebrew/kjv/chavvah.html" target="_blank">Chavvah</a>) Literally Life/Living. <br /><h4>Side Note 2:</h4>Genesis 1-5: Adam had Abel and Cain and after Cain killed Abel and was sent away he had Seth. However in Genesis 5 we see that Adam lived 130 years and had Seth and had other kids and died at 930 years old. So then it cannot be assumed in any genealogy in the bible that the first child mentioned is the first born child of the Parent, only that the child mentioned is the one chosen by God to be part of a special lineage or is worthy of mention for one reason or another. <br /><br /><h4>Side Note 3:</h4><a href="http://www.biblestudytools.com/cjb/genesis/5.html" target="_blank">The Hebrew Names of the First Offspring of Men</a>:<br />Adam: Adam (man) came from Adamah (earth)<br />Gen 2 CJB Called himself Ish(man)<br />Eve: Ishah (Woman)&nbsp; Chavvah (Live/Living/Woman)<br /><br />1st Cain: Keyin<br />2nd Abel: Hevel, Killed by Keyin<br />3rd Seth: Shet<br /><br />Fast Forward:<br />Enoch: Hanokh<br />Methuselah: Metushelach<br />Lamech: Lemekh<br />Noah: Noach<br />Sons of Noach Shem, Ham, and Japheth: Shem, Ham, Yefet<br /><br /><br /><b>How about you? You see anything to add to this? Want to share what  examples you have seen or experience in yourself or others? Comment  below.&nbsp;</b><br /><div><b><br /></b></div><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br />Blog:&nbsp;<a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br />Facebook:&nbsp;<a href="https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118" target="_blank">Facebook.Com/EmpoweredTooProsper</a><br />Twitter:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b style="background-color: white;">See Also:</b><br />Books by Darrell G. Wolfe:&nbsp;<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6" style="font-family: verdana, arial, helvetica, sans-serif; font-size: 13px;" target="_blank">Amazon.com/author/darrellgwolfe&nbsp;</a><br />Book Suggestions from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Brand and Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a>