---
title: 'That&#39;s IT! It&#39;s time for a Founders Party!'
date: '2013-07-20T00:46:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8503395325479152681'
blogger_filename: '/2013/07/that-it-it-time-for-founders-party.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'News and Current Events'
  - 'Sensitive Issues'
---

<h4 style="text-align: center;">What?!</h4><br /><blockquote class="tr_bq">- Christian photographers Elane Photography in New Mexico were  approached by a same sex couple&nbsp;looking to hire a wedding photographer.  Elane Photography politely declined citing their Christian faith and  were sued by the couple under the state’s anti-discriminatory laws, and  won. In New Mexico you apparently have no right to your free expression  and practice of faith any longer.<br /><div style="background-color: white; border: medium none; color: black; overflow: hidden; text-align: left; text-decoration: none;"><br />Read more:  <a href="http://www.foxnews.com/opinion/2013/03/26/gay-marriage-religious-freedom-are-incompatible/#ixzz2ZXabl6lk" style="color: #003399;">http://www.foxnews.com/opinion/2013/03/26/gay-marriage-religious-freedom-are-incompatible/#ixzz2ZXabl6lk</a></div></blockquote><br />It's one thing for a state to create a law allowing same-sex marriage. I'm against it, but it is what it is. I recognize that there is a difference between a marriage as a biblical union before God and a Man and his Wife and some artificial state sponsored document.<br /><br />You could call that state document a marriage, a union, an arrangement, a tax protected status, you can call it whatever you want. It is not, nor can it ever be a "Marriage" as defined by God. Whatever! Nor could you call the state sponsored document equal to "Marriage" if it was a heterosexual couple either. Just signing a paper doesn't make you married in God's world. There is more to Biblical Marriage than a piece of paper. <br /><br />But NOW you are taking things to a new level. Now you are not just telling me I can't tell you "No!" to your marriage. Now you aren't just telling me I have to tolerate your position. Now you are telling me that the state has the right to tell me I have to do business with you and by doing so "endorse" your marriage? This isn't a gay/straight issue anymore. It's not even a Religion V Gay issue anymore.<br /><br />Now it's a Constitutional Issue. Under NO circumstance does the government have the right to tell you what you must purchase or who you must or must not to business with, unless that issue is in violation of National Security. As in the case of doing business with a terrorist organization or something of that nature.<br /><br />This is a much larger issue now. You have an administration that is forcing people to buy health insurance, that is Anti-Constitutional. You have an Administration that is telling people who they MUST do business with, that is Anti-Constitutional. Every last human being that voted for or votes for in the future<br /><br /><br />It is now my claim that you cannot call yourself a Christian and vote for people that take your freedom and fight the God you claim to serve. If you vote for any Republican or Democrat that supports Abortion, Gay Rights, or the taking of your God given liberties; you are a traitor to Jesus Christ and I dare to say that you must choose Him or Them!<br /><br />Any Pastor that endorsed Obama should resign his pastorate! Any Pastor that endorses ANY candidate that holds anti biblical view should be force-ably removed from the pulpit by his people as a traitor to Jesus!<br /><br />What IS the solution? Republicans aren't any better than Democrats here sometimes, but they are better on the many issues. We must form our own party. One built on Faith and Trust in God as THE founder of this country. We were silent as they tried to force us from Politics claiming a fake "separation of Church and State" that has no legal basis in the Constitution or any of the Founding Documents. Enough is enough. I'm calling for the formation of a Founders Party. Retuning America to it's God Given and God Centered Roots!<br /><br />If you are gay, I'm NOT against you. I'm not even going to tell you to stop being gay. But I AM going to tell you to stop getting into MY business!&nbsp; <br /><br />You have the right to exist and be who you want to be in your home. You do NOT have the right to force me to endorse it! <br /><br /><br />My name is Darrell G. Wolfe and I endorse this message! <br /><br /><br /><br /><b>Have questions about anything I said here? Want to share your story? Comment Below!</b><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br />Blog:&nbsp;<a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a><br />Facebook:&nbsp;<a href="https://www.facebook.com/n2goodsuccess?sk=wall" target="_blank">https://www.facebook.com/n2goodsuccess</a><br />Twitter:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b style="background-color: white;">See Also:</b><br />Books by Darrell G. Wolfe:&nbsp;<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6" style="font-family: verdana, arial, helvetica, sans-serif; font-size: 13px;" target="_blank">Amazon.com/author/darrellgwolfe&nbsp;</a><br />Book Suggestions from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Brand and Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br /><br /><br /><br /><br />___