---
title: 'Moving Up, Lessons in Leadership'
date: '2013-02-04T18:37:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7751890005610737257'
blogger_filename: '/2013/02/moving-up-lessons-in-leadership.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'Observations'
---

As I've pondered success and growing into new levels of success I am reminded of an interview I had recently with a former supervisor. Since we last really sat down to chat we've both had promotions. He shared something that had never occured to me regarding leadership. It takes new skills at each level. These are the levels in my field, but the principles will carry over into other fields.<br /><br /><br /><ol><li>The front line employee is taking calls and is responsible only to himself, for the most part.&nbsp;</li><li>The front line Lead position is still right there in the mix and has a lot of influence, taking escalated issues and irate customers, but this person has influence over each of his direct reports in a very real and immediate way.&nbsp;</li><li>The front line Supervisor is a salary position. It's full of meetings and reports. Due to the nature of this position the person has a lead or two under them along with 15-30 front line staff. This person would like to be there in the middle of it all, sharing their expertise, and is able to at some level. But the administrative details of the position make it hard to balance.&nbsp;</li><li>The Manager. Now for a person who was VERY hands on at the Front Line, Lead and Supervisor level there comes a switch. It could be intimidating for a Front Line employee to be coached by someone this far above them. So the Manager cannot be in the midst of it or the results could be counter productive. He must now lead through his leaders. This process is the other side of delegation.&nbsp;</li></ol><div>Delegation, is what I want to ponder right now. I've always thought of delegation as the simple handing out of tasks and following up on their progress. But as I've studied this more, and read books like "<a href="http://www.amazon.com/gp/product/0688103804?ie=UTF8&amp;creativeASIN=0688103804&amp;tag=your0f4d-20" target="_blank">The One Minute Manager Meets the Monkey</a>", I've realized it's more about trust than anything else. You must develop your people into people you can trust. You also can't wait around for them to become that way on their own. Some will never get their, due to their own choices or mindsets, these you will have to lay aside and allow to stay where they are until their light turns on. Most can be lead into leadership.<br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm.amazon.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=0688103804" style="height: 275px; width: 1500px;"></iframe><br />Delegation is about training the next generation of leaders. I think of Jesus, how he took a rag tag band of people and turned them into the group that would turn the Roman world upside down. How did he do it? Did he personally train 1,000's of people? No. And neither can an effective high level manager. Instead, He trained 120 people superficially in meetings, 12 people one and one, and 3 people he allowed into his inner most circle and closest experiences to watch him and learn.<br /><br />So likewise, if you want leaders you have to train them to be leaders. At the Lead Level, you can allow some of your Front Line to take on small responsiblities, maybe sending out an email when new information comes out on a particular subject. This will take the load off of you in creating the email and through simple edits and collaberation you can duplicate your time and start training a leader.<br /><br />At the Supervisor level you can begin to designate higher level tasks and time to do them, not long time, but time. Also at the Supervisor level you take your leads and let them into your inner circle to start getting in their head. The sooner they are thinking right the sooner you can trust them to make decisions you would have made in your absence.<br /><br />At the Manager level you have many people under you. You can't personally coach them all, but you can work with your leaders to lead others to lead. The problem is you now have people with their own needs, desires, and ideas. You have to work with them. You can't create carbon copies of leaders. But what you can do is find their potential within and bring it out of them.<br /><br />In all levels you have to find trust. This is what my leaders have done in and for me over the years that has produced a leader, in training, in me. They didn't JUST assign me projects, they actually asked me to decide what types of projects I could/would like to work on. They were digging out of me something they never could have put in me.<br /><br />When training a leader...<br /><br /><ol><li>What is their motivation?</li><li>What is their strength?</li><li>What is their strongest area of growth (formerly known as weakness)?</li><li>What can you asign them, at their level, in line with business needs, that they can work on themselves?</li><li>What can you show/demonstrate/allow them access to that they wouldn't see without your allowing them?&nbsp;</li><li>Be an Open Book. Don't disclose condidential information, or share EVERY attitude and thought you have about the staff around you, that's just foolish and immature. But DO be an open book. If you struggled with something and you found a way to overcome, share the struggle not just the solution. The process you used to overcome is often MORE valuable than the solution itself.&nbsp;</li><li>... Other ideas about developing leaders? Please share below.&nbsp;</li></ol>See this video also: <a href="https://www.youtube.com/watch?v=MH9qvpXDVGI" target="_blank">Antony Bell on Developing Leaders</a><br /><br /><br /><div><br /></div><iframe allowfullscreen="" frameborder="0" height="315" src="http://www.youtube.com/embed/MH9qvpXDVGI" width="420"></iframe><br /><br /><br /><b>Have questions about anything I said here? Want to share your story? Comment Below!</b><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br />Blog:&nbsp;<a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a><br />Facebook:&nbsp;<a href="https://www.facebook.com/n2goodsuccess?sk=wall" target="_blank">https://www.facebook.com/n2goodsuccess</a><br />Twitter:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b style="background-color: white;">See Also:</b><br />Books by Darrell G. Wolfe:&nbsp;<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6" style="font-family: verdana, arial, helvetica, sans-serif; font-size: 13px;" target="_blank">Amazon.com/author/darrellgwolfe&nbsp;</a><br />Book Suggestions from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Brand and Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br />Other Blogs and Sites by the Wolfe Family:&nbsp;<a href="http://wfconceptions.wordpress.com/" target="_blank">http://wfconceptions.wordpress.com/&nbsp;</a><br /><div><br /></div></div>