---
title: 'Where are the jobs?'
date: '2013-02-08T01:45:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1460424453597482327'
blogger_filename: '/2013/02/where-are-jobs.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'News and Current Events'
---

When I came across this I had to take a moment to think about it. On one hand it makes perfect sense. On another hand it's hard to believe this many people could ever be put out of work by Robots. The fact is that jobs are disapearing and being replaced by new jobs. But the jobs of the future are high tech and high skill. Not nessasarily high "education". The old days of going to get a bachelors or even masters or PhD and being gaurunteed a job are gone. In todays marketplace a job could just as easily go to a young kid right out of highschool who spent his freetime learning computers and technology instead of playing games or "hanging out" with friends all the time.<br /><br /><blockquote class="tr_bq"><span style="font-family: Times New Roman, serif; font-size: x-small;"><a href="https://marketdataconnection.wellsfargo.com/m/m.w?lp=GetStory&amp;NewsID=623031701" target="_blank">PAUL WISEMAN and BERNARD CONDON, AP Business Writers</a></span><span style="font-family: Times New Roman, serif; font-size: x-small;">Released : Friday, January 25, 2013 1:19 PM</span><span style="font-family: Times New Roman, serif; font-size: x-small;">WASHINGTON -- They seem right out of a Hollywood fantasy, and they are: Cars that drive themselves have appeared in movies like "I, Robot" and the television show "Knight Rider."</span><span style="font-family: Times New Roman, serif; font-size: x-small;">Now, three years after Google invented one, automated cars could be on their way to a freeway near you. In the U.S., California and other states are rewriting the rules of the road to make way for driverless cars. Just one problem: What happens to the millions of people who make a living driving cars and trucks, jobs that always have seemed sheltered from the onslaught of technology?</span><span style="font-family: Times New Roman, serif; font-size: x-small;">"All those jobs are going to disappear in the next 25 years," predicts Moshe Vardi, a computer scientist at Rice University in Houston. "Driving by people will look quaint; it will look like a horse and buggy."</span><span style="font-family: Times New Roman, serif; font-size: x-small;">If automation can unseat bus drivers, urban deliverymen, long-haul truckers, even cabbies, is any job safe?</span><span style="font-family: Times New Roman, serif; font-size: x-small;">Vardi poses an equally scary question: "Are we prepared for an economy in which 50 percent of people aren't working?"</span></blockquote><br />The days are coming however that some stats say 55% of the USA will be self employed. So stop hanging onto that corporation. What is God calling you to do, learn, train for?<br /><br />There's a thought... DW<br /><br /><br /><b>Have questions about anything I said here? Want to share your story? Comment Below!</b><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br />Blog:&nbsp;<a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a><br />Facebook:&nbsp;<a href="https://www.facebook.com/n2goodsuccess?sk=wall" target="_blank">https://www.facebook.com/n2goodsuccess</a><br />Twitter:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b style="background-color: white;">See Also:</b><br />Books by Darrell G. Wolfe:&nbsp;<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6" style="font-family: verdana, arial, helvetica, sans-serif; font-size: 13px;" target="_blank">Amazon.com/author/darrellgwolfe&nbsp;</a><br />Book Suggestions from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Brand and Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br />Other Blogs and Sites by the Wolfe Family:&nbsp;<a href="http://wfconceptions.wordpress.com/" target="_blank">http://wfconceptions.wordpress.com/&nbsp;</a><br />