---
title: 'Grace in time of need'
date: '2013-10-18T05:58:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '10797074987150674'
blogger_filename: '/2013/10/grace-in-time-of-need.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'Word of The Lord'
  - 'Daily Reading'
---

<h4>COME:</h4><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/kjv/hebrews/4-16.html" target="_blank">Hebrews 4:16 (King James Version)</a><br />16 Let us therefore come <b>boldly unto the throne of grace</b>, that we may <b>obtain mercy</b>, and find grace to <b>help in time of need.  </b></blockquote><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/kjv/hebrews/passage.aspx?q=hebrews+5:1-6" target="_blank">Hebrews 5:1-6 (King James Version)&nbsp;</a><br /><br />1 For every high priest taken from among men is ordained for men in things pertaining to God, that he may offer both gifts and sacrifices for sins: 2 <b>Who can have compassion on the ignorant</b> , and on them that are out of the way ; <b>for that he himself also is compassed with infirmity. </b>3 And by reason hereof he ought , as for the people, so also for himself, to offer for sins.  </blockquote><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/kjv/2-corinthians/12.html" target="_blank">2 Corinthians 12 (King James Version)&nbsp;</a><br /><br />5 Of such an one will I glory : yet of myself I will not glory , but in mine infirmities. 6 For though I would desire to glory , I shall not be a fool; for I will say the truth: but now I forbear , lest any man should think of me above that which he seeth me to be, or that he heareth of me. 7 And lest I should be exalted above measure through the abundance of the revelations, there was given to me a thorn in the flesh, the messenger of Satan to buffet me, lest I should be exalted above measure . 8 For this thing I besought the Lord thrice, that it might depart from me. 9 And he said unto me, <b>My grace is sufficient for thee: for my strength is made perfect in weakness</b>. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me. 10 Therefore I take pleasure in infirmities, in reproaches, in necessities, in persecutions, in distresses for Christ's sake: for when I am weak , then am I strong. <br /><a href="http://www.biblestudytools.com/kjv/2-corinthians/9.html" target="_blank"><br /></a><a href="http://www.biblestudytools.com/kjv/2-corinthians/9.html" target="_blank">2 Corinthians 9 (King James Version)</a><br /><br />6 But this I say, He which soweth sparingly shall reap also sparingly; and he which soweth bountifully shall reap also bountifully . 7 Every man according as he <b>purposeth in his heart,</b> so let him give; not grudgingly , or of necessity: for God loveth a cheerful giver. 8 And God is able to make <b>all grace abound toward you; that ye, always having all sufficiency </b>in all things, may abound to every good work: 9 (As it is written , He hath dispersed abroad ; he hath given to the poor: his righteousness remaineth for ever. 10 Now he that ministereth seed to the sower both minister bread for your food, and multiply your seed sown, and increase the fruits of your righteousness;) 11 Being enriched in every thing to all bountifulness, which causeth through us thanksgiving to God. 12 For the administration of this service not only supplieth the want of the saints, but is abundant also by many thanksgivings unto God; 13 Whiles by the experiment of this ministration they glorify God for your professed subjection unto the gospel of Christ, and for your liberal distribution unto them, and unto all men; 14 And by their prayer for you, which long after you for the exceeding grace of God in you. 15 Thanks be unto God for his unspeakable gift.  </blockquote><h4>HEAR:</h4>As you are in touch with your own infirmity...<br /><br /><br /><a href="http://www.biblestudytools.com/lexicons/greek/kjv/astheneia.html" target="_blank">Infirmity: G 769 Astheneia</a><br /><br /><table style="width: 100%px;"><tbody><tr><td colspan="2"><b>Definition</b></td></tr><tr><td colspan="2"><br /><ol type="1"><li> want of strength, weakness, infirmity <ol type="a"><li> of the body <ol type="1"><li> its native weakness and frailty </li><li> feebleness of health or sickness </li></ol></li><li> of the soul <ol type="1"><li> want of strength and capacity requisite 1b</li></ol></li><li> to understand a thing 1b</li><li> to do things great and glorious 1b</li><li> to restrain corrupt desires 1b</li><li> to bear trials and troubles</li></ol></li></ol></td></tr></tbody></table>As you are in touch with your own infirmity... You must become intimately aware of your infirmity, your lack of ability to change, native-innate weakness, feebleness of strength to change your thoughts, feelings, and behaviors. You must realize that you, in and of yourself, do not contain the strength or capacity required to understand the things of God, do the things of God, restrain corrupt desires, or walk in love which is the thing needed to bear up under trials and troubles!<br /><br />WHY? Why must you admit to God and yourself that you are weak? Because God is not looking to change your behaviors, thoughts, and feelings; nor is he looking to change your environment. He is looking to change YOU... from the inside out.<br /><br />And as you begin to be aware of your frailty and fault, your pride in how great you are will melt away. As pride leaves, your compassion for others will rise.<br /><br />Also as pride leaves room is opened up in your heart to receive the mercy and grace of God. This grace gives you ALL SUFFICIENCY to do ALL THINGS. Now, you begin to be able to increase your capacity to think, feel, and do, that which you could not think feel and do. It is AS you realize that you can't, you begin to understand that HE can, in you. You realize it's a matter of the heart, not the head. <br /><br /><br /><h4>DO:</h4>I will meditate on my weakness, but also HIS GRACE in me... <br /><br /><blockquote class="tr_bq"><h4 class="ResultTitle"><a href="http://www.biblestudytools.com/my-bible/#">Philippians 2:13 KJV</a></h4><div class="ResultText">For  it is   God  which  worketh   in  you  both  <span class="Highlight">to</span> <span class="Highlight">will</span>   <span class="Highlight">and</span>  <span class="Highlight">to</span> <span class="Highlight">do</span>   of  his good pleasure. </div><br /><h4 class="ResultTitle"><a href="http://www.biblestudytools.com/my-bible/#">Hebrews 13:21 KJV</a></h4><div class="ResultText">Make   you  perfect   in  every  good  work  <span class="Highlight">to</span>  <span class="Highlight">do</span>   his  <span class="Highlight">will</span>,  working   in  you  that which is wellpleasing  in his  sight,  through  Jesus  Christ;  <span class="Highlight">to</span> whom  be glory  for  ever  <span class="Highlight">and</span> ever.  Amen. </div></blockquote><br /><br /><b>I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br /><b>Blog</b>:&nbsp;<a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br /><b>Facebook</b>:&nbsp;<a href="https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118" target="_blank">Facebook.Com/EmpoweredTooProsper</a><br /><b>Twitter</b>:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b>See Also: </b><br /><a href="https://www.facebook.com/n2goodsuccess" target="_blank">https://www.facebook.com/n2goodsuccess </a><br /><a href="https://www.facebook.com/towdahaudio" target="_blank">https://www.facebook.com/towdahaudio</a><br /><a href="https://www.facebook.com/TexasLivingInfo" target="_blank">https://www.facebook.com/TexasLivingInfo</a>