---
title: 'Overdraft Protection is a scam!'
date: '2013-02-10T02:42:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3729498466532936087'
blogger_filename: '/2013/02/overdraft-protection-is-scam.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Finances'
---

<h2 style="text-align: center;">Overdraft Protection is a scam...</h2>OK, so maybe it's not always a scam. There are people who could benefit from it. So let me explain. There are two different terminologies that mean TOTALLY different things that you should know about. Details vary from bank to bank but the essence of these are about the same at most banks. Allow me to explain.<br /><h3 style="text-align: center;">Overdraft Protection</h3>Overdraft protection means that if your account becomes overdrawn for any reason the bank will pull money from another account to cover it. Typcially this comes from a linked savings account, credit card, or line of credit. There is most often a transfer fee associated. You typically pay a fee of $25-$40 per item (up to four per day) for overdrafts. So intead you have this protection and it pulls money from a linked account to cover you and charges a transfer fee of between $10-$20 per day (rather than per item). So instead of paying four $35 fees ($140) you pay one transfer fee of $15. Would you rather pay $15 or $140? Obviously Overdraft Protection (ODP) is worth it if you are going to have an overdraft.<br /><h3 style="text-align: center;">Debit Card Overdraft Service</h3>The debit card overdraft service is the banks answer to the new overdraft rules that came with the stupid <a href="http://en.wikipedia.org/wiki/Dodd%E2%80%93Frank_Wall_Street_Reform_and_Consumer_Protection_Act" target="_blank">Dodd-Frank ACT</a> (a monsterous peice of legislation that is only hurtin the consumer I assure you). <a href="http://dsc.discovery.com/tv-shows/mythbusters/videos/polishing-a-turd-minimyth.htm" target="_blank">Mythbusters proved you CAN polish poop</a>, and so the banks polished poop (the Dodd-Frank ACT) too.<br /><br /><iframe allowtransparency="true" frameborder="0" height="350" id="dit-video-embed" scrolling="no" src="http://static.discoverymedia.com/videos/components/dsc/daa5115fe2242f50b8fdd0df9c358ee5cd6c5b14/snag-it-player.html?auto=no" width="600"></iframe><br /><br />So... what did the banks do? They created the Debitcard Overdraft Service. This is how this works. By default all personal (non business) checking accounts will decline your Debitcard if there are not enough funds for the one-time ATM/Debitcard Purchase. You have $10, you try to buy something for $20, your card is declined. You get ZERO fees. You just don't get what you are trying to buy. The banks lost a TON of money.<br /><br /><i>BTW... the people paying overdraft fees are the only ones making "free checking" accounts cost effective for the banks. If you think about it, the average check-2-check person makes NO money for the bank. You have to have 1000's in your savings and leave it long periods before the bank can make use of it to lend. You have to have credit good enough to lend on. So if you have no money and bad credit you are literally a waste of the banks time and money. So when you complain about why all accounts require direct deposit or balances or transactions to stay free why can't they just be "free" anymore? Remember... who paid for all that "free" call centers, technology, websites, branches, tellers, bankers, etc... Not you, if you have no money or credit. So when you say that you are taking your accounts elsewhere and you have no money or credit the banks says (THANK GOD! They were costing us money!) They designed the system to make people who don't make them money want to leave... surprise they did it on purpose!&nbsp;</i><br /><br />Anyway... Bank says, you don't want your card declined? You don't want to be embarrased at the register when your card doesn't work because you ran out of money? OK. Enroll in the debit card overdraft service. We will (at our discretion) let your things go through and then charge you fees for each item just like we do with checks. BUT when items you had the money for, but pended forever because the lazy merchant took their time processing it, post negative, those get fees too. So now people are right back paying $100's of dollars in fees again.<br /><br />This service does NOT decline the card for recurring transactions. Netflix, LA Fitness, and other "autopay" type things still clear posting negative and get fees.<br /><br />This service does NOT decline until it checks your overdraft protection first. Which means that instead of declining your card it will pull money from that savings first. AND charge a transfer fee.<br /><h3 style="text-align: center;">CHECKS</h3>So checks don't get declined. Checks, EChecks, and all other account number based transactions come through nightly processing and cause overdrafts more often than not. Checks are evil. <a href="http://www.dailymail.co.uk/news/article-1230044/End-cheque-book-Traditional-paper-payment-abolished-2018.html" target="_blank">The UK is killing checks soon</a>. You should too. You should not own checks. Let me say this another way. STOP WRITTING CHECKS! Checks are posted electronically now so it is common for a check you wrote for $5 to post for $500 because a computer read it wrong.<br /><br />Also, DON'T give your account numbers (or card numbers) over the phone or online to other companies. The VAST MAJORITY of claims filed at banks on accounts related to errors not fraud. Merchants take the wrong amount, wrong date, take payment without asking, take payment after being told to stop, etc, etc... I've even seen once where a lady gave her number to her sisters cell phone company to pay her bill one month because her sister was short. Three years later that company started drafting again because her sister was late again, without asking either her or her sister. Don't give out your numbers to anyway, except for employer/tax return direct deposits.<br /><br /><h3 style="text-align: center;">Bill Pay</h3>Most banks Bill Pay will send payments WITHOUT releasing your account/card numbers to the places you are paying. Bill Pay does not have to be automatic/recurring. Bill Pay can pay anyone, not just bills. It can send electronic payments to your bills, but in other cases it can send a cashiers check (which doesn't have your account number on it) by mail if needed. It's the only safe way to make payments.<br /><br /><h3 style="text-align: center;">SOLUTIONS</h3><br /><ul><li>Make SURE that your "Debitcard Overdraft Service" is turned OFF! So that your one-time debit card transations get declined if you don't have enough money.</li><li>STOP giving our your account numbers and/or writing checks. &nbsp;</li><li>Use Bill Pay exclusively as your one and only form of payment for bills and all non-purchases.</li><li>Use a seperate account or credit card for autopay items you must do, like netflix.&nbsp;</li><li>Finally, if you've done all this, turn that overdraft protection off. If you run out of money your card will decline. Then you'll remember to transfer the money from savings yourself and save yourself the transfer fee.&nbsp;</li></ul><div>Therefore, IF you are set up right, you don't need overdraft protection and probably would benefit from turning that linkage off. IF you insist on writing checks... keep it... but you'll probably pay more fees than those who don't.&nbsp;</div><div><br /></div><div>DW</div><div><br /></div><div><b>Have questions about anything I said here? Want to share your story? Comment Below!</b><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br />Blog:&nbsp;<a href="http://n2gs.blogspot.com/">http://n2gs.blogspot.com/</a><br />Facebook:&nbsp;<a href="https://www.facebook.com/n2goodsuccess?sk=wall" target="_blank">https://www.facebook.com/n2goodsuccess</a><br />Twitter:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b style="background-color: white;">See Also:</b><br />Books by Darrell G. Wolfe:&nbsp;<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6" style="font-family: verdana, arial, helvetica, sans-serif; font-size: 13px;" target="_blank">Amazon.com/author/darrellgwolfe&nbsp;</a><br />Book Suggestions from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Brand and Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a><br />Other Blogs and Sites by the Wolfe Family:&nbsp;<a href="http://wfconceptions.wordpress.com/" target="_blank">http://wfconceptions.wordpress.com/&nbsp;</a></div>