---
title: 'Tongues: Study References'
date: '2013-02-25T06:44:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3821187686898844287'
blogger_filename: '/2013/02/tongues-study-references.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
---

If you are going to study Tongues you need to have a proper context. You must also make sure to throw out everything you think you know and take the words for what they say, not skim them and think you know what they say. Much has been misread by old religion. It is also very helpful to go back and study the Greek on much of the NT around this. English translations by religious scholars have totally messed up a variety of scriptures because they translated with their own biases. The following are the scripture verses I reference when I study this topic. I'll be adding to this if I find more, from time to time.<br /><br />Verses on Tongues:<br /><br /><ul><li>Saved and Spirit Filled are a seperate Issue:</li><ul><li>How does Jesus give the disciples the Holy Spirit in <a href="http://www.biblestudytools.com/nkjv/john/20-22.html" target="_blank">John 20:22</a> and then also tell them to wait for the Holy Spirit. Isn't that a bit double minded? Unless there are two things happening here.&nbsp;</li><ul><li><a href="http://www.biblestudytools.com/nkjv/john/20-22.html" target="_blank">John 20:22 </a>VS <a href="http://www.biblestudytools.com/nkjv/acts/passage.aspx?q=acts+1:7-8" target="_blank">Acts 1:7-8</a></li></ul><li>When the Holy Spirit arrives on the scene it is noticable. The Apostles notice when He's NOT there.&nbsp;<a href="http://www.biblestudytools.com/nkjv/acts/passage.aspx?q=acts+8:12-22" target="_blank">Acts 8:12-22</a>&nbsp;Either says:</li><ul><li>If the Holy Spirit coming on you is the SAME as being born again, you need hands laid on you and evidence before you are saved... OR</li><li>If the Holy Spirit coming on you is NOT THE SAME as being born again, which this verse indicates, there is something else going on here.&nbsp;</li></ul></ul><li>"Evidence":</li><ul><li>I'm not among those who believe that Tongues is "THE" evidence of being Spirit Filled, but I do believe it's among the strongest evidences. &nbsp;</li><ul><li><a href="http://www.biblestudytools.com/nkjv/acts/2.html" target="_blank">Acts 2</a>: Holy Spirit = Tongues</li><li><a href="http://www.biblestudytools.com/nkjv/acts/passage.aspx?q=acts+8:1-18" target="_blank">Acts 8:1-18</a>&nbsp;Holy Spirit clearly sperate issue from being saved, tongues not mentioned, but implied as SOMETHING was clear evidence or lack thereof, and in most other instances Tongues is present.&nbsp;</li><ul><li>(Vs 12 They Believed and Baptised)(Vs 15-17 Spirit had not come on them, so Apostles laid hands on them. Vs 18 Simon "Saw" the spirit come on them... how so?)&nbsp;</li></ul><li><a href="http://www.biblestudytools.com/nkjv/acts/passage.aspx?q=acts+10:45-48" target="_blank">Acts 10:45-48</a> Peter sees them "get the Holy Spirit" How does he know? Tongues and Praise.&nbsp;</li><li><a href="http://www.biblestudytools.com/nkjv/acts/passage.aspx?q=acts+19:1-7" target="_blank">Acts 19:1-7</a> Paul comes accross people saved by baptism of repentance but clearly notices they don't have the Holy Spirit on them and lays hands on them. What is the result? Tongues.&nbsp;</li></ul></ul><li>Who works what in whom? What does "ALL" mean to you?</li><ul><li><a href="http://www.biblestudytools.com/nkjv/1-corinthians/12-6.html" target="_blank">1 Cor 12:6</a></li></ul><li>What does "Pray in the Spirit" mean?</li><ul><li><a href="http://www.biblestudytools.com/nkjv/1-corinthians/passage.aspx?q=1-corinthians+14:12-15" target="_blank">1 Cor 14:12-16</a></li><ul><li><a href="http://www.biblestudytools.com/nkjv/ephesians/6-18.html" target="_blank">Ephesians 6:18</a></li><li><a href="http://www.biblestudytools.com/nkjv/jude/1-20.html" target="_blank">Jude 1:20</a></li></ul><li>Notice that Paul is asking the Corinthians to seek the gifts that build... which means they have the right and ability to develope all the gifts they want to.</li><li>I'd suggest to read and re-read 1 Cor 14 over and over and over... because MOST people make it say exactly the opposite of what it says.&nbsp;</li></ul></ul><ul><li>Other: Verses and Sections</li><ul><li>All of 1 Corinthians 12, 13, 14</li><li>All of Acts</li><li><a href="http://www.biblestudytools.com/nkjv/daniel/5-25.html" target="_blank">Daniel 5:25 </a>"Mene Mene Tekel Upharsin" What was that? God speaking in a language unkown to ALL the scholars around the King, and Daniel interpreting the Word of God through God's unkown language. Sound Familiar?</li><li><a href="http://www.biblestudytools.com/nkjv/genesis/passage.aspx?q=genesis+11:4-14" target="_blank">Genesis 11:4-11</a> Babel is the begining of conusion in language, and The Holy Spirit is the restoration of that confusion!&nbsp;</li><li>Pray in the Spirit (<a href="http://www.biblestudytools.com/nkjv/1-corinthians/14-2.html" target="_blank">1 Cor 14:2</a>,&nbsp;<a href="http://www.biblestudytools.com/nkjv/1-corinthians/passage.aspx?q=1-corinthians+14:13-15" target="_blank">1 Cor 14:13-15</a>,&nbsp;<a href="http://www.biblestudytools.com/nkjv/romans/passage.aspx?q=romans+8:26-27" target="_blank">Romans 8:26-27</a>,&nbsp;<a href="http://www.biblestudytools.com/nkjv/ephesians/6-18.html" target="_blank">Ephesians 6:18</a>,&nbsp;<a href="http://www.biblestudytools.com/nkjv/jude/1-20.html" target="_blank">Jude 1:20</a>)</li></ul></ul>