---
title: 'John 9: God gets glory from Healing; not sickness!'
date: '2013-04-17T11:16:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5345749470351113915'
blogger_filename: '/2013/04/john-9-god-gets-glory-from-healing-not.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<h4>COME:</h4><br /><b><a href="https://www.youversion.com/bible/1/jhn.9.kjv" target="_blank">John 9</a></b><br /><blockquote class="tr_bq">1And as Jesus passed by, he saw a man which was blind from his birth.<b>2And his disciples asked him, saying, Master, who did sin, this man, or his parents, that he was born blind?3Jesus answered, Neither hath this man sinned, nor his parents: but that the works of God should be made manifest in him.4I must work the works of him that sent me, while it is day: the night cometh, when no man can work.</b>5As long as I am in the world, I am the light of the world.6When he had thus spoken, he spat on the ground, and made clay of the spittle, and he anointed the eyes of the blind man with the clay,7And said unto him, Go, wash in the pool of Siloam, (which is by interpretation, Sent.) He went his way therefore, and washed, and came seeing.</blockquote><blockquote class="tr_bq">35Jesus heard that they had cast him out; and when he had found him, he said unto him, Dost thou believe on the Son of God?36He answered and said, Who is he, Lord, that I might believe on him?37And Jesus said unto him, Thou hast both seen him, and it is he that talketh with thee.38And he said, Lord, I believe. And he worshipped him.39And Jesus said, For judgment I am come into this world, that they which see not might see; and that they which see might be made blind.40And some of the Pharisees which were with him heard these words, and said unto him, Are we blind also?<b>41Jesus said unto them, If ye were blind, ye should have no sin: but now ye say, We see; therefore your sin remaineth. </b></blockquote><br /><br /><br /><br /><br /><h4>HEAR:</h4><br />One of the worst mistakes we make in American Christianity is to read the bible in&nbsp;English. One of the other worst mistakes we make is to not speak, read, or write in proper&nbsp;English&nbsp;and therefore we do not use punctuation correctly. John 9:1-4 is among the most misquoted and misunderstood verses in the NT. Jesus did NOT say that the man was born blind so that God could be glorified. That is how people read it though. They use this verse among others to certify their anti-biblical position that God brings disaster on people for his sovereign and divine reasons. Usually to "teach them" something. I think they use "teach" because you CAN learn from, and sometimes in spite of, circumstances. I think they also use "teach"&nbsp;because&nbsp;they can't think of any other good reason God would do such a thing.<br /><br />Punctuation is an English idea. Greek and Hebrew have no such punctuation. Therefore when the bible translators bring the text into English from Greek they must choose to punctuate as THEY see fit to help us read it. But most bibles are based on the King James translation which was&nbsp;punctuated&nbsp;by very religious people a long time ago. As God brings more and more light from His Word and we begin to understand verses in context with other verses we see where some of these errors&nbsp;occurred&nbsp; There are no errors in the text - God's Word is perfect, but there are errors in our rendering and translation of the text.<br /><br />Here is how it reads:<br /><blockquote class="tr_bq">Neither hath this man sinned, nor his parents: but that the works of God should be made manifest in him.I must work the works of him that sent me, while it is day: the night cometh, when no man can work.</blockquote>Here is how it should read:<br /><blockquote class="tr_bq">Neither hath this man sinned, nor his parents<b>.</b>&nbsp;&nbsp;</blockquote><blockquote class="tr_bq">But that the works of God should be made manifest in him<b>;</b> I must work the works of him that sent me, while it is day<b>. T</b>he night cometh, when no man can work.</blockquote>If you notice the changes here is what is actually being said. Jesus almost never gave direct answers to questions. He did not ever answer their question of "Why" this man was born blind.<br /><br />He answered their question regarding sin. Neither him nor his parents sinned. End of statement/thought.<br /><br />New statement/thought: So that God's works should be made real on the earth I must work them. And then he went on to work those works and heal the man.<br /><br />Those two statements are&nbsp;separate. God's work is always to heal, bless, and deliver. NEVER will God purposefully cause, 'allow', or in any other way endorse sin, sickness, disease, poverty, fear, lack, etc. God can reach you in any circumstance of your life. The Holy Spirit is your teacher, not the devil. You will learn more totally healed and delivered and&nbsp;prosperous&nbsp;sitting in your office praying and reading the Word than you ever could distracted by sin, sickness, or poverty.<br /><br />Notice one other verse here:<br /><blockquote class="tr_bq">&nbsp;If ye were blind, ye should have no sin: but now ye say, We see; therefore your sin remaineth.</blockquote>Religion is blind. ALL religion. I laugh when people ask me if I'm religious, since I carry my bible everywhere. I reply "Religious? No! I hate religion!" They really get surprised by that. SO I then I have to explain it, which opens up into great conversations.<br /><br /><h4>DO:</h4><br />I'm going to remember today that God loves me, Jesus loves me, Holy Spirit loves me, and Jesus is LORD over sin, sickness, and poverty. I'm going to remember today that I have been assigned to do the works of Jesus as his representative on this earth. We are the body of Christ and we must BE the body of Christ. That means that I am to do now, what Jesus did then and would do today.<br /><br />If I'm upset at work over natural temporal stuff, I will be distracted into NOT doing the works of God. I must keep my focus on MY service to people, and not focus on what others fail to do, or do wrongly.<br /><br />DW<br /><br /><b>Have questions about anything I said here? Want to share your story? Comment Below!</b><br /><b><br class="Apple-interchange-newline" />I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br />Blog:&nbsp;<a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br />Facebook:&nbsp;<a href="https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118" target="_blank">Facebook.Com/EmpoweredTooProsper</a><br />Twitter:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b style="background-color: white;">See Also:</b><br />Books by Darrell G. Wolfe:&nbsp;<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6" style="font-family: verdana, arial, helvetica, sans-serif; font-size: 13px;" target="_blank">Amazon.com/author/darrellgwolfe&nbsp;</a><br />Book Suggestions from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Brand and Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a>