---
title: 'John 10:  Hireling vs Shepherd'
date: '2013-04-18T11:07:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8768524701523246158'
blogger_filename: '/2013/04/john-10-hireling-vs-shepherd.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<h4>COME:</h4><br /><b><a href="https://www.youversion.com/bible/1/jhn.10.kjv" target="_blank">JOHN 10</a></b><br /><blockquote class="tr_bq">7Then said Jesus unto them again, Verily, verily, I say unto you, I am the door of the sheep.8All that ever came before me are thieves and robbers: but the sheep did not hear them.9I am the door: by me if any man enter in, he shall be saved, and shall go in and out, and find pasture.10The thief cometh not, but for to steal, and to kill, and to destroy: I am come that they might have life, and that they might have it more abundantly.11I am the good shepherd: the <b><u>good shepherd giveth his life for the sheep</u></b>.12<b><u>But he that is an hireling, and not the shepherd, whose own the sheep are not, seeth the wolf coming</u></b>, and leaveth the sheep, and fleeth: and the wolf catcheth them, and scattereth the sheep.13<b><u>The hireling fleeth, because he is an hireling, and careth not for the sheep.</u></b>14I am the good shepherd, and know my sheep, and am known of mine.15As the Father knoweth me, even so know I the Father: and<b><u> I lay down my life for the sheep.</u></b></blockquote><br /><h4>HEAR:</h4>As a representative of the Body of Christ I walk on this planet as Jesus. I am Jesus to everyone I meet because I bear His Name, His Authority, His Power, His Spirit, His Blood, His Broken Body replaced mine on the cross. So then, if I am<a href="http://bible.cc/john/14-12.htm" target="_blank"> to do the works of Jesus and greater works</a> than those, how can I let poor attitudes work in me?<br /><br />I must prepare myself to treat each and every person like Jesus would treat them, not just as the ones I feel like treating well. The&nbsp;hireling runs from wolves. What does that mean? It means that he doesn't care enough about the sheep to protect them and die to himself and his comfort for them.<br /><br /><br /><h4>DO:</h4><br />Am I going to be a hireling or a shepherd today?<br /><br /><b>How about you? You see anything to add to this? Want to share what examples you have seen or experience in yourself or others? Comment below.&nbsp;</b><br /><br /><b>I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>N2 Good Success</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br />Blog:&nbsp;<a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br />Facebook:&nbsp;<a href="https://www.facebook.com/pages/Empowered-To-Prosper/231019763613118" target="_blank">Facebook.Com/EmpoweredTooProsper</a><br />Twitter:&nbsp;<a href="http://twitter.com/n2goodsuccess" target="_blank">http://twitter.com/n2goodsuccess</a><br /><br /><b style="background-color: white;">See Also:</b><br />Books by Darrell G. Wolfe:&nbsp;<a href="http://www.amazon.com/Darrell-Wolfe/e/B008F07FO6" style="font-family: verdana, arial, helvetica, sans-serif; font-size: 13px;" target="_blank">Amazon.com/author/darrellgwolfe&nbsp;</a><br />Book Suggestions from the&nbsp;<a href="http://astore.amazon.com/your0f4d-20/190-6424964-9305846" target="_blank">N2 Good Success Amazon Store</a><br />Brand and Product Offerings from&nbsp;<a href="http://www.zazzle.com/n2goodsuccess" target="_blank">N2 Good Success Zazzle Store</a>