---
title: 'It Is Written - 21 Day Gateway Church Devotional Challenge Day 3'
date: '2014-01-08T13:21:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3284503907774123609'
blogger_filename: '/2014/01/it-is-written-21-day-gateway-church_8.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<h3 style="text-align: center;"><a href="http://gatewaydevotions.com/it-is-written/day-3" target="_blank">It Is Written - 21 Day Gateway Church Devotional Challenge Day 3</a></h3><div><br /></div><div>I'm way behind, but I'm doing these in order because they are building on one another. See the link above to view these devotionals yourself.&nbsp;</div><div><br /></div><h4>COME:</h4><div><blockquote class="tr_bq"><br />Psalm 105:41<br />  41 He opened the rock, and water gushed out; like a river it flowed in the desert.<br /><br />Psalm 1:1-3<br />1 Blessed is the man who does not walk in the counsel of the wicked or stand in the way of sinners or sit in the seat of mockers. 2 But his delight is in the law of the LORD, and on his law he meditates day and night. 3 He is like a tree planted by streams of water, which yields its fruit in season and whose leaf does not wither. Whatever he does prospers.<br /><br />Joshua 1:8<br />  8 Do not let this Book of the Law depart from your mouth; meditate on it day and night, so that you may be careful to do everything written in it. Then you will be prosperous and successful.<br /><br />Isaiah 49:9-10<br />9 to say to the captives, 'Come out,' and to those in darkness, 'Be free!' "They will feed beside the roads and find pasture on every barren hill. 10 They will neither hunger nor thirst, nor will the desert heat or the sun beat upon them. He who has compassion on them will guide them and lead them beside springs of water.&nbsp;</blockquote><blockquote class="tr_bq">Isaiah 12:3<br />3 With joy you will draw water from the wells of salvation.&nbsp;</blockquote><blockquote class="tr_bq">Jeremiah 17:7-8<br />  7 "But blessed is the man who trusts in the LORD, whose confidence is in him. 8 He will be like a tree planted by the water that sends out its roots by the stream. It does not fear when heat comes; its leaves are always green. It has no worries in a year of drought and never fails to bear fruit."</blockquote></div><div><br /><br /><h4>HEAR:</h4></div><div>When I'm feeling dry and unproductive and fruitless... it's a red flag I haven't been in the Word enough.&nbsp;</div><div><br /></div><div><br /></div><div><h4>DO:</h4></div><div>Keep up this daily routine, don't beat myself up about the days I miss. Keep moving forward, one days morning routine at a time.&nbsp;</div><div><br /></div><div>DW</div><div><br /></div><div><br /></div><div><br /></div><div><br /></div>