---
title: 'Fresh and Startling and Intriguing'
date: '2014-02-16T04:54:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8712694055602738922'
blogger_filename: '/2014/02/fresh-and-startling-and-intriguing_15.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Lessons in Fiction'
---

<h3 style="text-align: center;"><br />02/15/2014 Writing Quote</h3><br /><br /><br /><div><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I liked this quote. From the introduction to “<a href="http://www.amazon.com/gp/product/0812550706/ref=as_li_ss_tl?ie=UTF8&amp;camp=1789&amp;creative=390957&amp;creativeASIN=0812550706&amp;linkCode=as2&amp;tag=your0f4d-20">Ender's Game</a>” By Orson Scott Card:</div><br /><div><br /></div><br /><div><br /></div><br /><span style="font-family: Calibri, sans-serif; font-size: x-small;"><br /><br /><br /><br /><br /><br /><br /></span><br /><br /><div><br />“I felt a strong desire to write stories that would do for others what <br />Asimov’s story had done for me. In other genres, that desire is usually <br />expressed by producing thinly veiled rewrites of the great work: Tolkien’s <br />disciples far too often simply rewrite Tolkien, for example. In Science Fiction, <br />however, the whole point is that the ideas are<b> fresh and startling and <br />intriguing: </b>you imitate the great ones, not by rewriting their stories, but <br />rather by creating stories that are just as startling and new.”<br /><br /><br /><br /><br /></div><br /><br /><br /><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="http://rcm-na.amazon-adsystem.com/e/cm?lt1=_blank&amp;bc1=000000&amp;IS2=1&amp;bg1=FFFFFF&amp;fc1=000000&amp;lc1=0000FF&amp;t=your0f4d-20&amp;o=1&amp;p=8&amp;l=as4&amp;m=amazon&amp;f=ifr&amp;ref=ss_til&amp;asins=0812550706" style="height: 240px; width: 120px;"></iframe><br /><br /><br /><br /><br /><br /><br /><br />******<br /><br /><br /><br />Thank you for reading. I hope you enjoyed this. I'd love to make a community with this project. If you would like to add, comment on, critique, or otherwise participate... that would be great! Please include any information about yourself, your blog/wesbite/amazon author page that you want to share with the community also.<br /><br /><br /><br /><br /><br /><a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://twitter.com/DarrellWolfe" target="_blank">@DarrellWolfe</a><br /><br /><br /><br />To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br /><br /><br /><br />For Non-Fiction writing by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell G. Wolfe: Click Here</a><br /><br /><br /><br />Any work not otherwise attributed is Copy Right Darrell G. Wolfe<br /><br /><br /><br />All Rights Reserved © Darrell G. Wolfe<br /><br /><br /><br /><b>Disclosure of Material Connection: Some of the links in the post above are “affiliate links.” This means if you click on the link and purchase the item, I will receive an affiliate commission. I may also have received one or more of the products or services mentioned above for free in the hope that I would mention it on my blog. Regardless, I only recommend products or services I use personally and believe will add value to my readers. I am disclosing this in accordance with the Federal Trade Commission’s&nbsp;<a href="http://www.gpo.gov/fdsys/pkg/CFR-2003-title16-vol1/content-detail.html" target="_blank">16 CFR, Part 255</a>: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.” A Big Thank You to&nbsp;<a href="http://michaelhyatt.com/five-ways-to-comply-with-the-new-ftc-guidelines-for-bloggers.html" target="_blank">Michael Hyatt</a>&nbsp;for helping us Bloggers with these new legal disclosure requirements.</b><br /><br /><br /><br /><br /><br /><div style="clear: both; float: left; padding-bottom: 10px; text-align: right;"><br /><br /></div><br />