---
title: 'Akeem | Hitchhiker, but not'
date: '2014-12-02T02:19:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6550432476136299767'
blogger_filename: '/2014/12/akeem-hitchhiker-but-not.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Real Life Stories'
---

<div class="WordSection1"><div class="MsoNormal"><br /></div><div class="MsoNormal"><span style="font-family: &quot;Georgia&quot;,&quot;serif&quot;; font-size: 12pt;">When I passed the car, and then a block down the freeway I see a man in a grey suit pants and brown suit jacket with a brief case walking on the freeway. I heard inside of me, “pick him up”. I obeyed immediately. I moved stuff aside and opened my door and leaned out and motioned my thumb to him “international hitch hiking symbol”. <o:p></o:p></span></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><span style="font-family: &quot;Georgia&quot;,&quot;serif&quot;; font-size: 12pt;">Picked up Akeem on the side of the road. He’s from NJ. He stated his gas ran out, he thinks, and that was his car I passed. He was afraid to attempt to hold out his thumb to hitch hike because he wasn’t sure if it was illegal to do so in Texas. He’s working for ADT now, lots of OT because he’s running low on money. That’s why he’s out of gas. He’s running late to work, and my picking him up is really helping him get there faster, maybe an hour or more faster than walking. He’s very grateful, it was cold out there and his jacket is light. <o:p></o:p></span></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><span style="font-family: &quot;Georgia&quot;,&quot;serif&quot;; font-size: 12pt;">I asked if he had people at work that could help him back to deal with the car after work. He said he did. That part would be covered. <o:p></o:p></span></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><span style="font-family: &quot;Georgia&quot;,&quot;serif&quot;; font-size: 12pt;">I drove him to work nearby and still ended up at work just a few moments late. I felt/heard God say “thank you, he’s one of mine”. I said “You’re welcome”. I felt bad that I didn’t just get gas for his car. God said “I have people for that. You are one cog in that wheel. You did good son.” <o:p></o:p></span></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><span style="font-family: &quot;Georgia&quot;,&quot;serif&quot;; font-size: 12pt;">God said: “If you keep opening your heart to me, and spending time practicing to hear my voice, and open your heart to worship, you’ll notice more and more of these unique moments in life. <o:p></o:p></span></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><span style="font-family: &quot;Georgia&quot;,&quot;serif&quot;; font-size: 12pt;">It’s important to know about Favor, believe in Favor, be ready and willing to declare Favor over your life. BUT… Favor is not a magic spell. It’s not something you can declare every morning, without being in relationship with Me, and expect it to work the Favor Magic in your life. Favor is a byproduct of relationship with me. If you are deepening your relationship with me, Favor will come. Listen to Me. Hear Me. Obey what you hear. Favor is just as likely to use you to bless someone as it is to use someone to bless you.” <o:p></o:p></span></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><span style="font-family: &quot;Georgia&quot;,&quot;serif&quot;; font-size: 12pt;">Inside of me I saw/heard an inner me jump up and down and say “Whooooo Hoooo!” <o:p></o:p></span></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div><div class="MsoNormal"><br /></div></div>