---
title: 'The Book Of Job: Study Summary. Jobs Background.'
date: '2014-05-07T04:27:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1183318214450978271'
blogger_filename: '/2014/05/the-book-of-job-study-summary-jobs.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Job Research'
  - 'Job'
---

<h3>The introduction to my summary of my study of Job.&nbsp;</h3>In August 2013 The Lord told me to start studying the book of Job. Which I have off and on ever since. It seems like the moment I think I'm done and I put it down I get more insight into it. I don't know that I'll ever be "done" studying this amazing book! Throughout this summary page you will find links to the articles/posts I put up for this study, as well as links to other resources I've found and/or used.<br /><br />The book of Job is among the most misunderstood books in the entire bible. And yet properly understood one of the most exciting! I found it to be a powerful reminder of our need for the Great Mediator Jesus, and his healing and restoration in our lives.<br /><br />I started by breaking down the entire book and analyzing it as a whole. Which you can read through in my post "<a href="http://empoweredtooprosper.blogspot.com/2013/11/the-entire-book-of-job-for-further-study.html" target="_blank">The Entire Book Of Job - For Further Study</a>".<br /><br />Then I looked to see when <a href="http://empoweredtooprosper.blogspot.com/2013/10/job-mentioned-in-other-books.html" target="_blank">Job is Mentioned In Other Books</a>. I figure that if we are going to look into Job's life and find anything we need to know about him, God has included that information in His Word.<br /><br /><br /><h3><b>Who Is Job?</b></h3><b><br /></b><br /><h4><b>When Did Job Live?</b></h4><br /><a href="https://www.apologeticspress.org/apcontent.aspx?category=11&amp;article=2516" target="_blank">Apologetic Press: When Did Job Live?</a>&nbsp;sheds some light on the idea that it was most likely post flood and pre-moses.<br /><br />From these other mentions we can assume some information about <a href="http://empoweredtooprosper.blogspot.com/2013/10/jobs-history-and-family.html" target="_blank">Job's History and Family</a>. He is the son of Issachar and grandson of Israel/Jacob. However, some scholars say that he was not related to Abraham. Or even lived at the same time or before Abraham. I'm<br /><br />Some say this had some bearing on the life of Job because he would have been either without the Covenant with God, or at least without Abraham's Covenant. Although saying Job is without Covenant at all, doesn't make any big picture sense.<br /><br />Job would have at the very least have had the Covenant struck with Adam that was carried on by Noah and past through his kids. The sacrifices Job made and his reliance on God indicates that he had a strong inward tie to God, and that only happens through some kind of relationship, albeit a religious distant one.<br /><br />I'm inclined to say that if the name is mentioned he as being the name of the son of Issachar. It's likely that it refers to the same person. Either way, through Abraham or Noah, Job did have a covenant relationship with God, and that seems obvious repeatedly throughout the text in his references to his relationship.<br /><br />It's also apparent that this Job served God as one who received the covenant past down to him. <a href="http://biblehub.com/job/42-5.htm" target="_blank">Job 42:5</a>, Job says that he'd heard about God, but never seen him before that moment. So no matter how he got his knowledge of God the result is the same. He'd been taught through past down knowledge, religious tradition essentially (even if family religious tradition and not formal).<br /><br /><br /><h4><b>Where Did Job Live?</b></h4><br />The <a href="http://empoweredtooprosper.blogspot.com/2013/10/jobs-land-photos.html" target="_blank">Land Photos</a>&nbsp;and <a href="http://empoweredtooprosper.blogspot.com/2013/10/job-research-regional-maps.html" target="_blank">Regional Maps</a> I found were somewhat helpful in getting a handle on this man. We find that Job lived in the land of Uz. At first I thought this was Ur, the same place Abraham came from. It is not the same place.<br /><br /><a href="http://en.wikipedia.org/wiki/Ur" target="_blank">UR </a>is located in Mesopotamia, in modern day Iraq. Abraham left UR and traveled west to the land of the Canaanites. Interestingly, Abraham's Father left UR headed to Canaan but stopped in Haran (<a href="http://www.biblestudytools.com/nkjv/genesis/11.html" target="_blank">Gen 11:31-32</a>), which gives me some indication it was Abraham's father Terah that would have first got the call to go. Abraham, then Abram, got the call to leave Haran and continue to "A land that I will show you" which ended up being Canaan. God had obviously been working on this family for a while in this call. (<a href="http://www.biblestudytools.com/nkjv/genesis/12.html" target="_blank">Gen 12</a>)<br /><br />Job however, is listed as being in the Land of <a href="http://en.wikipedia.org/wiki/Land_of_Uz" target="_blank">UZ. Wiki</a> sheds some light on this actually being a part of the area known as Edom. Now Edom, also called Idumea, is the land of Esau. Esau is the grandson of Abraham, Son of Isaac, Brother of Jacob/Israel, Uncle of Issachar. When Jacob received the blessing and inherited more land in Canaan (God's promised land to the descendants of Abraham's Blessing) Esau took up his stakes in the land just south.<br /><br />This now paints further the picture that Job actually is the son of Issachar. Now Joseph, the 11th son of Israel would have been Job's Uncle. So this probably took place in the time period when Joseph was serving in Egypt, and it could be that after his restoration Job either stayed in Edom or moved to Goshen when the descendants of Israel relocated. Or it could be that Job, being very old by the time of his trial had already relocated to Goshen with his family when he was younger, and further relocated back to Edom after the famine, which is a more likely timescale.<br /><br /><br /><h4>Who is the man Job?</h4><br /><b>Before The Trial</b><br /><br />Job was righteous. He was teacher, counselor, philanthropist, king. He was either mayor of the city, king, or something like that. He was the most respected leader of his region. Not only did he not lie, cheat, or steal; Job actively sought out the poor, widows, strangers, and destitute and looked for people to help. He gave shelter to strangers/visitors so that NO person would ever come to his city and sleep in the open elements. He gave, gave, gave, gave of himself to others. The <a href="http://empoweredtooprosper.blogspot.com/2014/05/the-character-of-job.html" target="_blank">Character of Job</a> is so iron tight, that few today could live up to him.<br /><br />In fact, it was probably that very giving nature that caused him to be a man of great wealth. Whoever sows a lot reaps alot. (<a href="http://biblehub.com/2_corinthians/9-6.htm" target="_blank">2 Cor 9:6</a>) God specifically shows his heart for the poor by saying "whoever gives to the poor lends to the Lord, and he will repay them!" <a href="http://biblehub.com/proverbs/19-17.htm" target="_blank">Proverbs 19:17</a>. God also says that whoever gives to the poor will lack nothing. <a href="http://biblehub.com/proverbs/28-27.htm" target="_blank">Proverbs 28:27</a>.<br /><br />Job was a wealthy man that served God and had a big family. In modern terms&nbsp;<a href="http://empoweredtooprosper.blogspot.com/2014/05/jobs-wealth-calculating-wealth-of-job.html" target="_blank">Job's Wealth</a>&nbsp;would be worth over $XXXXXX? Job today, would make Bill Gates seam like a warm up act. Not only because of his wealth, but because of how he used it. Job wouldn't just give to charity for tax deductions, Job spent his wealth on others as a way of life. He poured himself out for them. Imagine Bill Gates Money, Time, Resources, with the heart of <a href="http://en.wikipedia.org/wiki/Mother_Teresa" target="_blank">Mother Theresa</a>!<br /><br />He worshiped God. Job's statement about God giving and taking was not accurate truth, but his attitude was right. He did not curse God for the curse that came on his life. He worshiped in the face of hardship. He had a habit of making sacrifices to God. This was a man who lived his life in deep reverence to the things of God, and heart of God.<br /><br /><br /><br /><br /><br /><a href="http://empoweredtooprosper.blogspot.com/2013/09/research-on-jobs-friends.html" target="_blank">Jobs Friends</a> were an interesting study.<br /><br /><br /><br /><br /><br /><i>* I find it interesting that God uses the book of Job to mention two amazing creatures. <a href="http://empoweredtooprosper.blogspot.com/2013/09/leviathan.html" target="_blank">Leviathan </a>and <a href="http://www.biblegateway.com/passage/?search=job+40:15-24" target="_blank">Behemoth</a>. Indicative of the description we would give dinosaurs.&nbsp;</i><br /><br /><i>* This post is under construction until the Job study is complete-ish. Therefore it will have more content as the study progresses. DW</i><br /><br /><br /><br /><br /><br />