---
title: '#Habitation @Gatewaypeople'
date: '2014-07-21T00:25:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2825219122163196250'
blogger_filename: '/2014/07/habitation-gatewaypeople.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Church Notes'
---

<ul><li>In south Africa the major church there has planted over 90 churches. They win over 500,000 people to Jesus per week.</li><li>They said "We must win the lost at any cost."</li><li>This is not just what they believe, it is what they breath.</li><li>Saul was breathing threats. This Church is breathing soul winning.</li><li>What you breath out will be what others&nbsp; breath in. Like second hand smoke. Smoke can fill a room and be shared breathed atmosphere.</li><li>You become like God by being in His presence and breathing in.</li><li>God breathed on Adam and he lived. Gen 1-2</li><li>Jesus breathed on his disciples and they were born again. John 20:21</li><li>What we breath in is what we become. </li><li>Breath in the Word of God and the Spirit of God... then breath out into your life.</li><li>What are you breathing today?</li></ul>*Random church notes from @Gatewaypeople #Habitation<br /><br /><br />