---
title: 'The Book Of Job in Modern Style.'
date: '2014-03-02T22:12:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2833555210943779905'
blogger_filename: '/2014/03/the-book-of-job-in-modern-style_2.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Job''s Life Today'
---

<h4><br />Job Tell His Story</h4><br /><br /><br />It was the worst day of anyones life... ever. Ten months ago, without any warning, tragedy struck. My morning was great, got my work out in, prayed for two hours over my family and kids. I turned my phone on, which I keep off at night and during my morning routine.<br /><br /><br /><br />I was about to send my weekly tithe check in through my bill pay app. The following events happened during that morning, before I had turned my phone on at 9 AM.<br /><br /><br /><br />I got a voice mail from my vice president of marketing.<br /><br /><br /><br />Uz Foods, a high end grocery line was under attack. Distribution channels had provided contaminated food and there was a mass lawsuit being filled in conjunction with a full investigation of the matter by the FDA. Stock prices raided as a mass sell off ensued.<br /><br /><br /><br />A fire broke out in my clothing factory burning down the entire building, all the merchandise, and killing all but one employee who made it out and called 911.<br /><br /><br /><br />A small band of terrorists attacked an alternative fuel car manufacturing plant killing all but one employee who escaped just before the largest mass suicide bomb ever wiped out the building and an entire city block.<br /><br /><br /><br />After that news I sat down with my wife to Pray and Thank God for His blessings in our lives, all the good times we had and ask his direction for what to do.<br /><br /><br /><br />The next morning I had a painful sore on my neck. Over the next nine months a full blown staph infection had taken my entire body over from head to toe. Antibiotics seemed to do no good. My private doctor had been good to me for years and set up a home hospital in one of my spare rooms, despite the fact I was out of money and may never be able to pay him for it.<br /><br /><br /><br />Despite it all. I learned a valuable lesson. And I'd like to share it with you.<br /><br /><br /><br /><br /><br /><br /><br />******<br /><br /><br /><br />Thank you for reading. I hope you enjoyed this. I'd love to make a community with this project. If you would like to add, comment on, critique, or otherwise participate... that would be great!<br /><br /><br /><br />Please include any information about yourself, your blog/wesbite/amazon author page that you want to share with the community also.<br /><br /><br /><br /><i>* I may include "Affiliate Links" which means I earn a commission when you buy products I link to. To see my full about page and disclosures:&nbsp;<a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a></i><br /><br /><br /><br /><a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br /><br /><br /><br />To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br /><br /><br /><br />For Non-Fiction writing by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell G. Wolfe: Click Here</a><br /><br /><br /><br /><br /><br /><br /><br /><br />