---
title: 'Injury'
date: '2014-01-27T13:50:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '644434609587757550'
blogger_filename: '/2014/01/injury_27.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Writing Practice'
---

<h4><br />Fiction Writing Practice 2014/01/27</h4><br />The bombs are exploding around him. Joe can hear the bullets slam into the roof of the structure, another plane raid. He should be brave, strong, he should be out in the fray attacking back, like all his fellow soldiers. He doesn't understand this. He is paralyzed, he can't move. It's not like him to be this afraid. The rain is leaking through the holes in the roof and soaking him from head to toe. He closes his eyes and takes a deep breath...<br /><br /><br /><br />When Joe opens his eyes the building is gone. He's laying in his bed, back home in Joshua Tree, CA. There is no raid. It's just a dream... or is it a memory... He's not sure anymore. It's the same one he's had every night for two years now. The rain was just night sweats. The feeling of not being able to move is because he cannot, in fact, move. Gunshot wound to the spine paralyzed him from the waste down. This dream was more vivid than his usual dreams.<br /><br /><br /><br />As he comes to he realizes there is storm outside today. As he picks up his legs with his hands and swings them over the bed, lifeless. The crackle on the roof alerts his suspicion. The white bumpy blanket outside the window confirms, ice storm, bad one this time. He's facing a battle, but it's a battle of another kind.<br /><br /><br /><br />Funny thing is, this battle didn't start in a war. He would love to say that his spinal injury was from fighting enemy soldiers in a war in Afghanistan, but instead it was some punk 14 year old kid who didn't know what a good thing he had in America, stealing a wallet with $20 and some closed credit cards.<br /><br /><br /><br /><br /><br />dw<br /><br /><br />