---
title: 'Eta | That parade was the bomb!'
date: '2014-11-28T19:43:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1459575910883236493'
blogger_filename: '/2014/11/eta-that-parade-was-bomb.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
---

<br /><br /><br /><br />She's standing in mid air, 100 feet or more above the crowds. She can see a line of people in costume's dancing down the street, with large deorated vehicles in between groups. There are crowds on both of the street bundled in heavy clothing to ward against the cold air and a light dusting of snow from earlier today. She doesn't feel the chill, she's a spectator, not a participant. Eta stands, stationary, just watching the spectacal. <br /><br />Suddenly, her vision is blocked by something brown and right up in her face, she takes a few steps back and she's confronted with a large brown baloon. A few more steps back and it's as large as a house, full of hot air. As it passes she can take in a full view. It's a... turkey? Yes, it's a turkey the size of a house, full of hot air, floating&nbsp; high above the crowds, and just below and even with her. <br /><br />She can see Santa on his sligh toward the end of the event... She knows this somehow. It's familiar, something her parents were involved in before she shut out them, their memories, and society in general. What's it called? There's a tradition for this? Santa is and his float are just below her now. She see's the clock on the building, it's 1:17 pm... <br /><br />Flash. Her chest is compressed, she can't breath. The buildings around her crumble. She is thrown back 1,000's of feet. She she takes the next breath she see's the cloud, just like on the movies, and old WWII videos. A mushroom cloud. The buildings are evaporating in every direction. The inhabitants won't even know what hit them until it's far, far too late. It's moving with great speed for miles, buildings evaporate before the wave in every direction. <br /><br /><br />Devestation... <br /><br />As she sucks in a deep breath the world around her evaporates and turns black, then white, then the world she was in a few moments ago comes back into view. People bustling about the metroplex. Food Court vendors handing out samples. Shes' back in the chair, with her laptop, and latte'. <br /><br />It's getting worse... these visions... she needs answers... <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />