---
title: 'Unknown Antagonist'
date: '2014-12-30T14:43:00.0030000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6878421373461480339'
blogger_filename: '/2014/12/unknown-antagonist_30.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
---

<br /><br /><br /><br /><div style="border-width: 100%; direction: ltr;"><br /><br /><div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.6041in;"><br /><br /><div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.6041in;"><br /><br /><div style="border-width: 100%; direction: ltr;"><br /><br /><div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.6041in;"><br /><br /><div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.6041in;"><br /><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />Someone is brought<br />in by Dr. Briar to fix the project with sound and spirit world experiments. He<br />is superior in intellect to most, he is a strong strategist, and he has motives<br />that are not entirely purely scientific. His motives differ from Dr. Briar's in<br />that sense. He's RICH… but so rich that making more money has no appeal to him.<br />He'd be just as likely to drop a billion on a failing business just for the fun<br />of turning it around as he would to just watch the money burn and spin that<br />business wildly out of control. He's bored… he likes the power of anonymity. He<br />made Dr. Briar think that Dr. Briar sought out his help; when in fact, he<br />orchestrated the whole thing. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />Who is this<br />Antagonist? Does he have a name? Will we ever know it? How much mystery is<br />good, vs how much do we need to build flesh and blood into this guy and make<br />him more real, menacing? Then again, the unknown has it's own fear built in.<span style="mso-spacerun: yes;">&nbsp; </span></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />He motivated by<br />money, in the sense that once should have gain, value, profit of some kind of<br />out one's expenditure of energy. That value added need not be monetary though.<br />Power. Control. Can the other dimensions, what some call the spirit world, be<br />accessed? Can they be manipulated? Can they be controlled? These are the real<br />power, the real questions. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />***</div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />"Yes, Dr. Briar<br />I am! That is why you brought me here. To fix this reject project and bring<br />something valuable out of it. Keep me appraised of any changes."</div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />The black suited man<br />turned and left the room. His tuft of white hair bouncing along as he walked<br />away.</div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />****</div><br /></div><br /></div><br /></div><br /></div><br /></div><br /></div><br />