---
title: '2014/02/18 Daily Reading'
date: '2014-02-18T13:13:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '697441503658262481'
blogger_filename: '/2014/02/20140218-daily-reading.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<h4>COME:</h4><blockquote class="tr_bq"><a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=98&amp;content=0" target="_blank">Day 98</a><br />Your Advocate Always Wins Your Case<br />1 John 2:1<br />1My little children, these things I write to you, so that you may not sin. And if anyone sins, we have an Advocate with the Father, Jesus Christ the righteous.</blockquote><blockquote class="tr_bq">Devotional&nbsp;</blockquote><blockquote class="tr_bq">If you want a glimpse of some real-life celestial drama, picture this: God the Father sits as Judge of the universe with Jesus Christ at His right hand, who is not only your High Priest, but also your Advocate.<br />When your accuser, the devil, comes along and says, “You have done this wrong and you have not done that right,” Jesus says, “Father, the devil is right, but My blood has paid for what the devil is accusing him of.”</blockquote><br /><h4>HEAR:</h4>I miss it. Often. The fact I miss it has NO bearing on my right standing with God. I am right with Him regardless of my actions or faults. I am right with Him because of WHO He is and WHAT He has done.<br /><br />I can receive today because of that.<br /><br /><h4>DO:</h4>I will hold my head high. Ignore my faults and failures and focus on HIS success! That will allow me to let His success flow through me to you (you being whoever I come in contact with today, through this blog, work, family, friends, etc).<br /><br /><br /><br /><b>How about you? You see anything to add to this? Want to share what examples you have seen or experience in yourself or others? Comment below.&nbsp;</b><br /><div><b><br /></b></div><b>I call you empowered 2 prosper with good success!</b><br /><b><br /></b><b>©&nbsp;</b><b><span style="font-size: x-small;">Darrell G. Wolfe</span></b><br /><div class="separator" style="clear: both; text-align: center;"><a href="/images/imported/blogger-googleusercontent-com/e2p-logo-b7b5454b818d.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><br /></a></div><b>Bible Study Blog</b>:&nbsp;<a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br /><b>Facebook</b>:&nbsp;<a href="https://www.facebook.com/DarrellGWolfe" rel="nofollow" target="_blank">Facebook.Com/DarrellGWolfe</a><br /><b>Twitter</b>:&nbsp;<a href="http://twitter.com/darrellwolfe" rel="nofollow" target="_blank">@DarrellWolfe</a><br /><b>Personal Blog</b>:&nbsp;<a href="http://www.darrellwolfe.com/">www.DarrellWolfe.Com</a>