---
title: 'Dark Room (combined two days writting into one page. Still needs work.'
date: '2014-12-30T14:43:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1686398324827018721'
blogger_filename: '/2014/12/dark-room-combined-two-days-writting.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
---

  <br /><div style="border-width: 100%; direction: ltr;"> <div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.6041in;"> <div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.6041in;"> <div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">After what seems 10 days, as per the marks on the box, Ash wakes to the sound of his food being delivered for breakfast. He eats in silence. He doesn't even hear the noise they've been pumping into the room for 10 days. When he is done he places his tray on the shelf and it disappears into the wall again.</div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">*Click* The sound in the overhead turns off. The air pressure changes as a slight crake in the wall snaps open. The crack opens wider as the panel disappears into the wall and the crack becomes a doorway, which opens into a long hall. Ash makes his way down the long hall, lit with a blue tinted LED strand. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">The floor is stretched chicken wire, over deep triangles of foam cut at different angles. The walls, ceiling, all made of the same substance. One chair, bolted to the floor. It looks comfortable enough. Like a dentist chair. Seeing no other option, he takes a seat.</div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">The silence is deafening, immediately. Ash clapped his hand once, and noticed that the clap was essentially absorbed, rather than bouncing back to him. It was as though sound itself was sucked out of the room. If it were possible for sound to be less than nothing, this was it. The sound was sucked right out of him, so that all he could hear was his own heartbeat, and breathing. Even his ears began to make their own ringing. This all hit him moments after entering the room, it started subtle, and grew worse over the first moments in the room. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">Cool air is keeping the room a comfortable 74*F.</div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">The lights go out. Light was immediately absent. Completely absent. The only thing Ash could see was the flashes of white dots dancing around his eyes from having been in the light moments earlier. What utter and stark contrast to the room he was in. The sound... or lack of sound... in this room was astonishing. It was though sound itself was being sucked out. He could hear nothing but a ringing for the first few minutes. After a while, the ringing subsided and he could hear the beating of his own heart, and the sloshing of bodily fluids throughout his own body.</div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">After the silence of 10 days in the white room, all of Ash's racing thoughts have subsided. He's moved past wondering where he is, when he'll leave, he's now just him. Alone with his thoughts. And increasingly, his past.</div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">Eventually, after what felt like an hour, but it was probably only minutes, he found that even these sounds faded into the background of his attention. He could almost hear his own thoughts. As though that voice in his head, that was always present, telling him what to do, and where to go, and how to act, watch out for that... don't say that... oh man, why did you do that for? It was as though the inner voice became almost audible. As&nbsp; though he could hear himself think. Or rather as though his thoughts could speak to him audibly. It was an odd sensation, but occupying his mind was the only thing he could do. He'd never admit it to a captor, but solitary confinement was his favorite part of being a prisoner of war. He enjoyed self-time, and silence. Accusation follows on the heels of this. Anytime he's alone, it starts. What you should have done differently.</div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">Alone, in the dark now, with no sound of any kind, negative sound. He sits. Lays back in the reclining dentist chair, and he waits. He waits. He sleeps.</div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">His concentration snapped into focus suddenly with the feeling that he was not alone in this room. He'd known before he entered the room that cameras were on him, and he was being observed... but that wasn't it. He felt the air in the room change, as though someone had entered the room with him. He could hear breathing in the room. He wasn't tied to the chair, he could get up, but where to? He couldn't see, he'd memorized the layout though. He knew the entrance he came from, and he didn't see any other known entry ways before the door shut out the light. Ash slowed his breathing, and observed with his four remaining senses for any clue as to the whereabouts and intention of the new participant. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">***</div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><span style="font-style: italic;">Ash... Ash...&nbsp;</span></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">He sits up. How long was he asleep? Is he asleep? How would you know in dark silence?</div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><span style="font-style: italic;">Ash... we know about you Ash... We know who you are... what you've done... how could you...&nbsp;</span></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">Ash shakes his head... the voices vanish. What as that?</div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">***</div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><span style="font-style: italic;">It's beginning... the biometrics just spiked. </span></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><span style="font-style: italic;">Good, good... let's see how he does.</span></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><span style="font-style: italic;">The previous test subjects had nowhere near the discipline that Mr. Ashland does. This should be an interesting observation. He's incredible. Getting a trained military man, accustomed to being alone for days and weeks, a survival expert. He is already outlasted every scientist, street volunteer, and audio geek we've ran through these tests. Many of them didn't make it through the prep room, but we've never had anyone last this long, he's been in there for three hours and just now he's starting to show signs of a dimensional tear. You are a genius!</span></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><span style="font-style: italic;">Yes, Dr. Briar I am! That is why you brought me here. To fix this reject project and bring something valuable out of it. Keep me appraised of any changes.</span></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">The black suited man turned and left the room. His tuft of white hair bouncing along as he walked away.</div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">***************************</div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div></div></div></div>