---
title: 'Story Structure: White Noise'
date: '2014-10-30T06:07:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5292860087329109460'
blogger_filename: '/2014/10/story-structure-white-noise.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Story Structure'
  - 'White Noise'
---

<p dir=ltr>Three Act</p><p dir=ltr>I. <br>Keeps having dreams, starts hearing and perceiving spiritual things, xxxxx happens to push him over the edge and find out what's happening to him. </p><p dir=ltr>II.<br>Pushes to find answers, develops a hap hazard team, and meets Eta who is having the same experiences. Xxxx happens and they must choose to give up or pursue.</p><p dir=ltr>III.<br>Faced with a daunting task they pursue truth, picking up clues, and misdirection. When xxxx happens that nearly ends the whole pursuit, it may even look like its over, but they find one more thing to push them forward.</p><p dir=ltr>IV. </p><p dir=ltr>Final Showdown between Ash and Eta against xxxxx. </p><p dir=ltr>They leave the situation victors and losers. They are assessing where to go after all this. One believes more, one believes something happened,<br>But remains unconvinced. </p><p dir=ltr>They part company, the end... Except, there is another event...or hint of one, will that propel them into another story? </p><p dir=ltr>End book one.<br><br></p><p dir=ltr>Story Arc<br><br><br><br><br><br><br><br></p><p dir=ltr>Disruption <br>Ash is on training and disappears for days, meanwhile he is being tested in a secret facility, studying sounds effect on perceiving the supernatural...</p><p dir=ltr>Ash is home now, retired from the service and starts feeling the effects of the experiment, while researchers are secretly keeping tabs on him. </p><p dir=ltr>OR... We pick up the story in Oregon, and find out through bits of reveal about the experiment.</p><p dir=ltr>Maybe the first reveal is a vivid dream of a white box room, and he thinks its PTSD via a recurring nightmare but it's actually suppressed memory.<br></p><p dir=ltr>Open Doors</p>