---
title: '2014/03/05 Daily Reading Wed'
date: '2014-03-05T15:21:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '9050785796782905579'
blogger_filename: '/2014/03/20140305-daily-reading-wed.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<h4>COME:</h4><blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12.222222328186035px; line-height: 24.000001907348633px; margin-bottom: 20px; padding: 0px;"><a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?day=113&amp;user_id=darrellwolfe&amp;version=1" target="_blank">Day 113 of Joseph Prince Devotional</a></blockquote><blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12.222222328186035px; line-height: 24.000001907348633px; margin-bottom: 20px; padding: 0px;">When It Is More Blessed To Receive<br />Luke 10:42<br />42… Mary has chosen that good part, which will not be taken away from her.”&nbsp;</blockquote><blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12.222222328186035px; line-height: 24.000001907348633px; margin-bottom: 20px; padding: 0px;">If Jesus comes to your home, what would you do? Would you ask Him to sit down and then start serving Him? Or would you sit down and start drawing from Him? Would you let Him serve you and fill you up?</blockquote><br /><h4>HEAR:</h4>I'm not serving in an official role in a church. But have I turned my blogs into serving? Am I so busy trying to "Build a platform" that I am no longer really sitting and listening?<br /><br /><br /><h4>DO:</h4>&nbsp;I think it's time to take a look at my calendar again and take a REALISTIC look at what I can commit to.<br /><br />5:30 AM is too early... I've never done it, probably won't. So I need to find a time that I WILL do my commitments.<br /><div><br /></div><br /><br /><b>How about you? You see anything to add to this? Want to share what examples you have seen or experience in yourself or others? Comment below.&nbsp;</b><br /><div><b><br /></b></div><b>I call you empowered 2 prosper with good success!</b><br /><b><br /></b><a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank"><b>By&nbsp;</b><b><span style="font-size: x-small;">Darrell Wolfe</span></b></a><br /><b><span style="font-size: x-small;"><br /></span></b><b><span style="font-size: x-small;"><br /></span></b><br /><div class="separator" style="clear: both; text-align: center;"><a href="/images/imported/blogger-googleusercontent-com/e2p-logo-b7b5454b818d.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><br /></a></div><div class="separator" style="clear: both; text-align: center;"><a href="/images/imported/blogger-googleusercontent-com/e2p-logo-b7b5454b818d.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><br /></a></div><div class="separator" style="clear: both; text-align: center;"><a href="/images/imported/blogger-googleusercontent-com/e2p-logo-b7b5454b818d.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><br /></a></div><b>Bible Study Blog</b>:&nbsp;<a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br /><b>Facebook</b>:&nbsp;<a href="https://www.facebook.com/DarrellGWolfe" rel="nofollow" target="_blank">Facebook.Com/DarrellGWolfe</a><br /><b>Twitter</b>:&nbsp;<a href="http://twitter.com/darrellwolfe" rel="nofollow" target="_blank">@DarrellWolfe</a><br /><b>Personal Blog</b>:&nbsp;<a href="http://www.darrellwolfe.com/">www.DarrellWolfe.Com</a>