---
title: 'How Music Affects the Body | SuperConsciousness Magazine'
date: '2014-11-04T05:52:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7258895089111074497'
blogger_filename: '/2014/11/how-music-affects-body.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
  - 'Research'
---

<div dir="ltr">  Music can slow down and equalize brain waves. It has been demonstrated  repeatedly: brain waves can be modified by both music and  self-generated sounds. Ordinary consciousness consists of beta waves,  which vibrate from fourteen to twenty hertz. Beta waves occur when we  focus on daily activities in the external world, as well as when we  experience strong negative emotions. Heightened awareness and calm are  characterized by alpha waves, which cycle from eight to thirteen hertz.  Periods of peak creativity, meditation, and sleep are characterized by  theta waves, from four to seven hertz, and deep sleep, deep meditation  and unconsciousness produce delta waves, ranging to .5 to three hertz.  The slower the brain waves, the more relaxed, contented and peaceful we  feel. <br /><br /><a href="http://www.superconsciousness.com/topics/art/how-music-affects-body">http://www.superconsciousness.com/topics/art/how-music-affects-body</a></div><div dir="ltr">DarrellWolfe.com via Mobile</div>