---
title: 'Discovery | Exploring My Experiences'
date: '2014-10-20T06:26:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2509497529121663526'
blogger_filename: '/2014/10/discovery-exploring-my-experiences.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<br /><br /><br /><h3>Discuss ONE experience for each of the following:</h3><br /><h4>A Rewarding Ministry Experience. </h4>Once, when leading a group for the Christian Club on Campus, at College of the Desert, I (and the group) laid hands on a young lady, and she received the baptism of the Holy Spirit and began speaking in other tongues. That was the first moment I saw that something bigger than me was possible. God really could use me. And it frightened me, as much as it thrilled me. <br /><br /><br /><h4>A Gratifying Personal Achievement.&nbsp;</h4>Publishing <a href="http://www.darrellwolfe.com/p/banking-basics-for-believers-book-by.html" target="_blank">Banking Basics for Believers</a>. A woman I didn't know, was informed by a friend of mine to read it. I gave her a copy, my gift. She said that it helped her personally and professionally understand money in a new way. She was doing the job I had been doing when I started writing it. She felt that it should be mandatory reading. What an amazing circle of experience. <br /><br /><br /><h4>A Touching Relationship Experience.</h4>Hearing my wife (to be at the time) pray in tongues for the first time. It was the first time I found out that it still existed. Before her, I thought it had either died centuries ago, or was happening in some remote monastery. When I heard her, my world opened wider than ever before. I knew I needed more of whatever she had. <br /><br /><br /><h4>A Tremendously Difficult Life Experience.</h4>My Pastor-Father came out as an Alcoholic Atheist, later turned Crack Addict, then Psychologist. Parents Divorced. World crashed down. I struggled with identity for those first few years. But as I look back now... I struggled with identity for years before too. As a child I'd seen Jesus with my own eyes, and a demon too. Yet I grew up in this frozen-chosen religious traditional church, full of people who wouldn't know God if he walked up and said hello. There were precious few born again people in those churches. So I was always torn between the life of the supernatural I experienced around me, and the dead religiosity of the people around me. So as I look back... it wasn't an event that changed me... it was an event that crystallized the difference, and forced me to choose which world I would live in: Spiritual or Natural. <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />