---
title: 'Discovery | Strengths Finders - Top Five'
date: '2014-10-20T00:30:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3151149715063189245'
blogger_filename: '/2014/10/discovery-strengths-finders-top-five_19.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'study'
  - 'Discovery'
---

<br /><h4>Top 5 <a href="https://www.gallupstrengthscenter.com/?utm_source=googadwords&amp;utm_medium=web&amp;utm_campaign=newhomepage&amp;gclid=CjwKEAjwwo2iBRCurdSQy9y8xWcSJABrrLiS-tdTCVyJH2ubG37fCYn8kbvnHEt5e6RDDOwa5WesLRoC3e3w_wcB" target="_blank">Strengths Finder</a> Results: </h4><ul><li>Intellection</li><ul><li>&nbsp;Introspective Thinker who enjoys a good intellectual conversation.</li><li>Write Journal</li></ul><li>Learner&nbsp;</li><ul><li>Constant satisfaction in learning new facts, skills, and beginning a new area of study. No topic is off limits, and the process of learning, rather than the result, is the only aim. </li><li>Embrace new technologies and opportunities to learn something new. </li></ul><li>Ideation</li><ul><li>&nbsp;Derive energy from a new concept of idea. I revel in taking the world we all know and turning it around so people can view it from a strangely enlightening angle.</li><li>Write Journal, process ideas into clear thoughts before communicating them to others.&nbsp; </li></ul><li>Achiever</li><ul><li>&nbsp;I take immense satisfaction in being productive and accomplishing things. The day must not end, without accomplishing something.&nbsp;</li><li>I must learn to take breaks, and enjoy the success of a job well done. </li></ul><li>Input</li><ul><li>I take joy in knowing more... about anything and everything. I am a sponge for new, interesting, curious, or even strange information.&nbsp;</li><li>I will journal, write, and store this information to pull up and use another day.</li></ul></ul><br /><h3>Top Five Summaries:</h3><br /><h4>INTELLECTION</h4>PEOPLE EXCEPTIONALLY TALENTED IN THE INTELLECTION THEME ARE CHARACTERIZED BY THEIR INTELLECTUAL ACTIVITY. THEY ARE INTROSPECTIVE AND APPRECIATE INTELLECTUAL DISCUSSIONS.  <br /><br />People with strong Intellection talents like to think. They like mental activity. They like to exercise the “muscles” of their brain, stretching them in multiple directions.People with strong Intellection talents are introspective. This introspection gives them time to reflect and ponder. Wherever it leads them, their mental hum is a constant in their lives. <br /><br />Suggestion: Write and Journal, take time alone to think and process. <br /><br /><br /><br /><h4>LEARNER</h4>PEOPLE EXCEPTIONALLY TALENTED IN THE LEARNER THEME HAVE A GREAT DESIRE TO LEARN AND WANT TO CONTINUOUSLY IMPROVE. THE PROCESS OF LEARNING, RATHER THAN THE OUTCOME, EXCITES THEM.  <br /><br />People with strong Learner talents constantly strive to learn and improve. The process of learning is as important to them as the knowledge they gain. Learners are energized by the steady and deliberate journey from ignorance to competence. They are excited by the thrill of learning new facts, beginning a new subject, and mastering an important skill. Learning builds their confidence. <br /><br />Suggestion: Be an early adopter of new technologies, and seldom used systems. Be a catalyst for change. <br /><br /><br /><h4>IDEATION </h4><br />PEOPLE EXCEPTIONALLY TALENTED IN THE IDEATION THEME ARE FASCINATED BY IDEAS. THEY ARE ABLE TO FIND CONNECTIONS BETWEEN SEEMINGLY DISPARATE PHENOMENA. <br /><br />People with strong Ideation talents are creative and appreciate originality. They relish free-thinking experiences such as brainstorming and discussion groups. They have a natural capacity to consider issues from multiple perspectives. They revel in taking the world we all know and turning it around so people can view it from a strangely enlightening angle. They think outside the box. They are fascinated by new ideas and concepts, which come to them easily. They love ideas because they can be profound, they can be novel, they can be clarifying, they can be contrary, and they can be bizarre. For all these reasons they derive a jolt of energy whenever a new idea occurs to them. <br /><br />Suggestion: Take time to think through ideas before communicating them, others will not be able to connect the dots you have connected. Also, you get bored easy, play mental games with the world around you (silently so you don't disturb others). Write and Journal your ideas.<br /><br /><br /><h4>ACHIEVER</h4><br />PEOPLE EXCEPTIONALLY TALENTED IN THE ACHIEVER THEME WORK HARD AND POSSESS A GREAT DEAL OF STAMINA. THEY TAKE IMMENSE SATISFACTION IN BEING BUSY AND PRODUCTIVE. <br /><br />Achievers have a constant need for attainment. They have an internal fire burning inside them. It pushes them to do more, to achieve more. People with strong Achiever talents feel as if every day starts at zero. By the end of the day they must accomplish something meaningful to feel good about themselves. And “every day” means every single day — workdays, weekends, holidays, and even vacations. If the day passes without some form of achievement, no matter how small, Achievers feel dissatisfied. Upon finishing a challenging project, they rarely seek to be rewarded with a rest or an easy assignment. While they appreciate recognition for past achievements, their motivation lies in striving toward the next goal on the horizon. <br /><br />Suggestion: Take breaks, limit your commitments to reasonable goals, preferably a few important tasks, rather than many less important ones. Try setting goals within the home and non-work environments, it will help you engage in these aspects of your life, and feel more satisfaction from participating in them.<br /><br /><br /><br /><h4>INPUT </h4><br />PEOPLE EXCEPTIONALLY TALENTED IN THE INPUT THEME HAVE A CRAVING TO KNOW MORE. OFTEN THEY LIKE TO COLLECT AND ARCHIVE ALL KINDS OF INFORMATION. <br /><br />People with strong Input talents are inquisitive. They always want to know more. They crave information. They like to collect certain things, such as ideas, books, memorabilia, quotations, or facts. Whatever they collect, they do it because it interests them. They find many things interesting and have a natural curiosity. The world is exciting precisely because of its infinite variety and complexity. A few minutes of surfing the Internet may turn into hours once their curiosity takes off. They constantly acquire, compile, and file things away. Their pursuits keep their minds fresh. And they know that one day some of the information or things they have gathered will prove valuable. <br /><br />Suggestion: Embrace this aspect of your personality by reading, even things like the dictionary, thesaurus, and encyclopedia (or Wikipedia). Devise systems for storing and accessing this knowledge Accept that you will never feel as though you know enough. <br /><br /><br />