---
title: 'Jobs Curse Mindset tore down his blessing.'
date: '2014-05-07T18:13:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7099109291525428370'
blogger_filename: '/2014/05/jobs-curse-mindset-tore-down-his.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Job Research'
  - 'study'
  - 'Job'
---

<br /><div style="text-align: center;"><h3>The Curse VS The Blessing of Job</h3></div><b>Poetic Writing:</b><br />It's also important to note that the&nbsp;writing&nbsp;style of the book is poetic. It is a&nbsp;<a href="http://en.wikipedia.org/wiki/Biblical_poetry#Didactic_poems" target="_blank">didactic poem</a>, which means that it has an&nbsp;<a href="http://en.wikipedia.org/wiki/Didacticism" target="_blank">instructional or informational</a>&nbsp;quality and is meant to teach.<br /><br /><br /><b>Satan's Words:</b><br /><blockquote class="tr_bq"><b><a href="http://www.biblestudytools.com/nkjv/job/1.html" target="_blank">Job 1:9-11</a></b><b><br /></b>9 So Satan answered (God) ... now, stretch out Your hand and touch all that he has, and he will surely <b>curse You</b> to Your face!"<br /><br /><b><a href="http://www.biblestudytools.com/nkjv/job/2.html" target="_blank">Job 2:4-5</a></b><br />4 So Satan answered (God) ... stretch out Your hand now, and touch his bone and his flesh, and he will surely<b> curse You</b> to Your face!" </blockquote><b>Job's Words:</b><br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/nkjv/job/1.html" target="_blank"><b>Job 1:5</b></a><br />5 So it was, when the days of feasting had run their course, that Job would send and sanctify them, and he would rise early in the morning and offer burnt offerings according to the number of them all. For Job said, "It may be that my sons have sinned and <b>cursed God</b> in their hearts." Thus Job did regularly.<br /><br /><a href="http://www.biblestudytools.com/nkjv/job/3-25.html" target="_blank"><b>Job 3:25</b></a><br />25 For the thing I greatly feared has come upon me, And what I dreaded has happened to me.</blockquote><b>Job's Wife's Word's:</b><br /><blockquote class="tr_bq"><b><a href="http://www.biblestudytools.com/nkjv/job/2.html" target="_blank">Job 2</a><br /></b><br />9 Then his wife said to him, "Do you still hold fast to your integrity? <b>Curse God </b>and die!"  </blockquote><br /><b>Compare this to:&nbsp;</b><br /><br />God says "<a href="http://www.wholeperson-counseling.org/ndoc/fear-not.html" target="_blank">Fear Not</a>" many, many, many times. You cannot please God without Faith (<a href="http://www.biblestudytools.com/nkjv/hebrews/11-6.html" target="_blank">Hebrews 11:6</a>). Faith comes by hearing. Hearing comes by The Word of God. Faith is believed in the heart and spoken through the mouth. (<a href="http://www.biblestudytools.com/nkjv/romans/10-17.html" target="_blank">Romans 10:17</a>&nbsp;and <a href="http://www.biblestudytools.com/nkjv/romans/passage.aspx?q=romans+10:9-10" target="_blank">10:9-10</a>).<br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/nkjv/luke/6-45.html" target="_blank">Luke 6:45</a><br />A good man out of the good treasure of his heart brings forth good; and an evil man out of the evil treasure of his heart brings forth evil. For out of the abundance of the heart his mouth speaks.</blockquote><b>Job's Issue:</b><br /><br />Job was BLESSED... he understood THE BLESSING. Job was the richest man in the east. He and Abraham were contemporaries, he most likely predated Abraham.<br /><br />Job was afraid of the Curse. He had the curse on his mind. Satan had been trying to break down the hedge this man lived in that protected him. The only way that Satan can break down this hedge is to get him to curse God.<br /><br />Satan is looking over the earth to see whom he MAY devour. That means he cannot devour just anyone he chooses. He must have access to them. <a href="http://biblehub.com/1_peter/5-8.htm" target="_blank">1 Peter 5:8</a><br /><br />Job therefore faith, for anything positive or negative, is believed in the heart and spoken with the mouth (<a href="http://www.biblestudytools.com/nkjv/romans/passage.aspx?q=romans+10:9-10" target="_blank">Romans 10:9-10</a>). As man thinks in his heart he becomes what he thinks (<a href="http://biblehub.com/proverbs/23-7.htm" target="_blank">Proverbs 23:7</a>)<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br class="Apple-interchange-newline" />