---
title: 'The 2014 Journal Template'
date: '2014-07-07T04:20:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3507284864467613318'
blogger_filename: '/2014/07/the-2014-journal-template.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<br /><h4>I've drafted a new routine for my mornings.&nbsp;</h4><br />It has been helpful in the past, and I got off it. I'm returning to it now because I need that routine. I thought I'd share it with you so that you could use it. You won't see me using it here often, because I will use it in my private journal. But I'll put down the routine here first so you can see how it fits, and then the blank template I use after that, based on the routine.<br /><br /><h4>Routine: All in one journal entry</h4><ul><li><b>BE STILL</b>: It must start with BE STILL before going to writing, bible devotional, or other things. Prayer will be involved, but it will be listening, not speaking.&nbsp;</li><li><b>PRAYER</b>: This is the time I do some talking, but still listening also.&nbsp;</li><ul><li>Prayers, Petitions, and Thanksgivings be made on behalf of: FIRSTLY&gt;</li><ul><li>For all people</li><li>Then Kings, Leaders, Those in Authority</li><ul><li>SO THAT we may lead a tranquil and quite life in all godliness and dignity.&nbsp;</li></ul></ul><li>God desires all men to:</li><ul><li>Be saved</li></ul><br /><ul><li>Come to the knowledge of the Truth.&nbsp;</li></ul><li><i><a href="http://biblehub.com/context/1_timothy/2-1.htm" target="_blank"><b>1 Timothy 2</b></a></i></li><li><i>1 First of all, then, I urge that&nbsp;<a href="http://biblehub.com/greek/1162.htm" target="_blank">entreaties&nbsp;</a>and&nbsp;<a href="http://biblehub.com/greek/4335.htm" target="_blank">prayers</a>,&nbsp;<a href="http://biblehub.com/greek/1783.htm" target="_blank">petitions&nbsp;</a>and&nbsp;<a href="http://biblehub.com/greek/2169.htm" target="_blank">thanksgivings</a>, be made on behalf of all men, 2 for kings and all who are in authority, so that we may lead a tranquil and quiet life in all godliness and dignity. 3 This is good and acceptable in the sight of God our Savior, 4 who desires all men to be saved and to come to the knowledge of the truth. 5 For there is one God, and one mediator also between God and men, the man Christ Jesus, 6 who gave Himself as a ransom for all, the testimony given at the proper time. 7 For this I was appointed a preacher and an apostle (I am telling the truth, I am not lying) as a teacher of the Gentiles in faith and truth. 8 Therefore I want the men in every place to pray, lifting up holy hands, without wrath and dissension.</i></li></ul></ul><ul><li><b>BIBLE</b>: Instead of a bible devotional, I'm going to do a bible study. Take one of Kenneth's study notes from the front of my bible and do those.</li></ul><br /><ul><li><b>JOURNAL&nbsp;</b>entry will include all of the above, and anything else on my mind at the time. Take a moment to jot down:</li><ul><li>How you are feeling:</li><li>How you are believing:</li><li>What's happening in your life right now:</li></ul></ul><br /><blockquote class="tr_bq"><br /></blockquote><h4>I created a template from this. I'll use it tomorrow!</h4><br /><br /><br /><h3>Daily Routine:</h3><h4>BE STILL: Just Listen, write down what He tells you.&nbsp;</h4><div><b>What did God say today?</b></div><br /><b>God Said: (write down anything you here God say today)</b><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><h4>PRAYER: This is the time I do some talking, but still listening also.</h4><div>These are to be made on behalf of:&nbsp;</div><div><ul><li><b>FIRST&nbsp;</b>for&nbsp;<b>all people</b>, then&nbsp;<b>Kings</b>,&nbsp;<b>Leaders</b>, those in&nbsp;<b>Authority</b>, then you would be included in all men, so your family, kin folk, etc.&nbsp;</li><li><b>God desires all men to:</b>&nbsp;Be saved and come to the knowledge of the Truth.</li></ul></div><i><a href="http://biblehub.com/context/1_timothy/2-1.htm" target="_blank"><b>1 Timothy 2</b></a></i><br /><div><i>1 First of all, then, I urge that entreaties and prayers, petitions and thanksgivings, be made on behalf of all men, 2 for kings and all who are in authority, so that we may lead a tranquil and quiet life in all godliness and dignity. 3 This is good and acceptable in the sight of God our Savior, 4 who desires all men to be saved and to come to the knowledge of the truth. 5 For there is one God, and one mediator also between God and men, the man Christ Jesus, 6 who gave Himself as a ransom for all, the testimony given at the proper time. 7 For this I was appointed a preacher and an apostle (I am telling the truth, I am not lying) as a teacher of the Gentiles in faith and truth. 8 Therefore I want the men in every place to pray, lifting up holy hands, without wrath and dissension.</i></div><br /><div><a href="http://biblehub.com/greek/1162.htm" target="_blank">Entreaties&nbsp;</a>(specific felt need),</div><div><a href="http://biblehub.com/greek/4335.htm" target="_blank">Prayers&nbsp;</a>(exchange of desires/wishes),&nbsp;</div><div><a href="http://biblehub.com/greek/1783.htm" target="_blank">Petitions/Intersessions</a>&nbsp;(Intersection of heaven and earth, hit the bullseye, request something specific of a King. Technical/Civil term: VERY specific requests that meet an exact need!).&nbsp;</div><div><a href="http://biblehub.com/greek/2169.htm" target="_blank">Thanksgivings</a>&nbsp;( Lit: giving thanks for God's grace! Gratitude, Thankfulness)<br /><br />Pray scriptures that are on your heart and all of the things listed above.&nbsp;</div><i><br /></i><b>Did anything else come up in prayer that should be notated?&nbsp;</b><br /><i><br /></i><i><br /></i><i><br /></i><i><br /></i><br /><h4>BIBLE: Instead of a bible devotional, I'm going to do a bible study.&nbsp;</h4><div>Take one of <a href="http://www.kcm.org/index.php?p=media_download" target="_blank">Kenneth's study notes</a> from the front of my bible and do those.</div><div>JOURNAL entry will include all of the above, and anything else on my mind at the time. Any other study you have access to would be fine too.<br /><br />Take a moment to jot down anything that you need to:</div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><h4>JOURNAL: What's Up Today?&nbsp;</h4></div><br /><b>How you are feeling:</b><br /><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /><div><b>How you are believing:</b></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><br /></div><div><b>What's happening in your life right now:</b></div><div><br /></div><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />The End Of The Journal Today...&nbsp;</div>