---
title: 'Convention Notes: #SWBC2014 Kenneth Copeland 07/05/14'
date: '2014-07-06T05:58:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5628132895407403274'
blogger_filename: '/2014/07/convention-notes-swbc2014-kenneth.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Service Notes'
---

<br /><h3><div>Convention Notes: <a href="http://www.kcm.org/southwest/#!home" target="_blank">#SWBC2014</a> Kenneth Copeland 07/05/14</div></h3><br />These are my random notes from tonights final service at&nbsp;<a href="http://www.kcm.org/southwest/#!home" target="_blank">#SWBC2014</a>.<br /><br /><b>1 John 5: Love Command</b><br /><b>Mark 4:14: Satan comes to steal the Word.&nbsp;</b><br /><b>John 10:10 The Thief comes only to steal, kill, and destroy (In that order!)&nbsp;</b><br /><br />If Satan can't steal the Word out of you, then he can't kill or destroy you either. The Word of God is first place and final authority and the ONLY priority you will ever have.<br /><br />Despise: Does NOT mean to hate.<br /><b>Despise: Means to think little of, or pay little attention to.&nbsp;</b><br /><br /><blockquote class="tr_bq"><b>If you are not getting up early enough to be in the Word before you eat, get ready, leave for the day... then you are despising the Word of God.&nbsp;</b></blockquote><br />Failure to love is a failure of the Word working in you.<br /><br />If you have ever gone on a juice fast you'll know your body goes through astonishing changes fairly quickly. This is because of the simultaneous reduction in toxins going in, and increase of micro-nutrients going in.<br /><br />A believers convention (or any concentrated time in the Word) is like a juice fast for the Spirit!<br /><br />Mark 4: Persecution comes for the Word's sake. That Word is what Satan is after. If he can't stop it from sprouting he'll attempt to stop it from producing.<br /><br />Like the grape plant I have out back. Lot's of big leaves, and the meager-est fruit I've ever seen. It's not fit to feed the dog with.<br /><br /><h4>Hot Buttons:</h4>Satan knows your buttons. He doesn't pull new tricks. He just keeps pushing the same buttons that have always worked on you. Until... you begin to choose different reactions, he'll keep pushing the same ones.<br /><br />If discussions about not having enough for bills, or something broken needs to be replaced, can get you depressed instantly... then he'll keep finding new ways to push those "money worry" buttons.<br /><br />In fact, money worry is a sign that you are already serving the wrong Master (Matthew 6-7).<br /><br /><blockquote class="tr_bq">In 2 Cor 12, Pauls thorn was a messenger of Satan. In the bible, <b>thorns always equal worries.&nbsp;</b><div>(Study that out)</div></blockquote><br /><b>The deceitfulness of riches,</b> is the lie that money will solve your problem. If you have caught yourself saying that getting a hold of more money would be the solution to you situation, you are believing a lie. Just for example, if you need a car, God can bring you a car without giving you the money for one!<br /><br /><br />Once you figure out how to roll the care over onto God this should become your new favorite saying:<br /><br /><blockquote class="tr_bq"><b>I can't tell you how much I DON'T CARE! Jesus is MY caretaker!&nbsp;</b></blockquote><br /><b>Heb 13:12-15 - The Fruit of my lips = Thanksgiving</b><br /><br />Gratefulness is the key that is missing for many people.<br /><br /><h4>!!!!!*****Heavenly Mathematics*****!!!!!!</h4><br />Heavens Mathematics are not based on numbers, they are based on obedience. The Lord said to Kenneth one time, "I have a million ways to make you a billionaire! ... And you can't think of three!"<br /><br />You don't always need money to buy a car, God can bring you a car without money.<br /><br /><br /><h4><b>Thoughts about my future: The Plan</b></h4><div><ul><li>Be led to give</li><li>Be led to receive</li><li>Be totally unconcerned with how things will come, or where they'll come from.&nbsp;</li></ul></div><br /><h4><b>Grace - Forgiveness&nbsp;</b></h4><br />The first act of Grace it Forgiveness.<br />The first act of Forgiveness is Grace.<br /><br /><br /><h4>Matthew 6:24-34: Take No Thought Saying</h4><br />You take thoughts by saying them. You possess things with your mind and mouth. You take pain by acknowledging it, either with words or sounds. Pain is VERY real. It's not just imaginary. However, the same functions of your brain that are used for higher thought, are used for processing pain. This is why when you are "put to sleep" you cannot feel pain, even though it is still happening. This is why some people who pass their pain threshold pass out. This is also why pain makes it hard to concentrate on much else.<br /><br />You can use this same physiological make up in reverse. Instead of saying "Ow! Oh this hurts... oh this hurts..." (Taking pain by saying)<br /><br />You can replace those thoughts/words with His Word. "OH! Thank you Jesus for healing!" Pull out some <a href="http://www.kcm.org/real-help/health-and-healing" target="_blank">healing </a>scriptures and start to say those out loud instead.<br /><br />But if you wait until you stub your toe to start this it's not going to work real well for you. Go get yourself an aspirin while you work on it.<br /><br />Think about the pill bottle. Someone you trust told you that pill would reduce or eliminate your pain. You believed them. You acted on it, and experienced some positive results. Then you've been convinced over many repeated uses over 20-30+ years that it works. You've developed faith in that pill to take your pain.<br /><br />Switching to the Word while you are in pain is hard. You may want to go take that pill, but take it in Faith, then start meditating the Word of God. Only after you have spent time meditating the Word will you have had the chance to build up your Faith in that Word as strong, or stronger, than you had in that pill. You can come to the point where the pill doesn't cross your mind, the Word is the first place you go when pain attacks. But that will take time to develop.... and develop it you must if you are going to be successful in God's Kingdom.<br /><br /><br /><h4>Practice His Presence.&nbsp;</h4><br />You can't wait until you have the stubbed toe to start this meditation on the Word. Therefore, you should start to practice God's presence everywhere you go, all the time. Ask him when you should get up, go to bed, ask Him about your routine in the day/week/month/year... Be LED through your day. Be LED in the morning. Be LED at work about each decision.<br /><br />Start by saying: "I am your to command and correct sir! I am grateful for __Fill in as many things as you can here___."<br /><br />If you are in pain, and you do this, you'll find that this replaces your pain in time.<br /><br /><br /><h4>The Works of Jesus</h4><br /><br />The Works of Jesus are whatever the Father tells Him to do.<br /><br />If you only ever did/said what the Father told you to do/say this would create:<br /><div><ul><li>Decreased pressure to perform.</li><li>Increased pressure to be still and listen.&nbsp;</li></ul></div><b>Look up "Be" scriptures in the Word. Ex</b><br /><br /><ul><li>Light BE</li><li>BE made whole</li><li>Amen (So BE it)</li><li>BE it done unto me as you have said</li></ul><br /><br />Instead of calling it your confession list, call it you "It Is Written" list. Take scriptures down that you can read with your eyes, confess with your mouth, and meditate on in your heart.<br /><br />Don't ever violate a leading of the Lord. Even if you are wrong, it's better to be wrong trying to obey God than be dead ignoring Him. He can fix something you did trying to obey Him. It's getting the people ignoring Him to start listening that He has trouble with.<br /><br /><b>NEVER say "Yeah But..." to the Word of God.&nbsp;</b><br /><br /><br />Proverbs says: Do not let the Word depart from your eyes.<br /><br />You can't eat the memory of a potato. You have to put the Word in your eyes daily if you want a strong spirit.<br /><br /><br />Faith is developed as a seed is. It starts off needing a little extra care and protection. But eventually it will produce if allowed the right atmosphere.<br /><br />Fear = Love violated<br /><br />If you have a hard time believing God, fear is present, and so is clouded thinking as a result.<br /><br />Perfected Love casts out fear.<br /><br />Romans 4<br /><br />Faith = Confidence<br /><br />Meditation = Increased capacity for faith<br /><br />Josh 1:8: Joshua was about to lead a group of people to become Giant killers! Meditation was the key to his success!<br /><br />Psalms 127: Sleep scripture<br /><br />Awake to righteousness! Is a good morning scripture.<br /><br />Take JOY by Faith!<br /><br /><br /><br /><br />DW