---
title: 'The Part Is Yours... Can you hear the call?'
date: '2014-12-16T02:48:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3667559562305370087'
blogger_filename: '/2014/12/the-part-is-yours-can-you-hear-call.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Spiritual Growth'
---

<h3>Why am I here?</h3><br /><br />It seems like a such a simple question. This weekend I went to see <a href="http://www.google.com/url?url=http://www.youtube.com/watch%3Fv%3Deg3FLdrs0oY&amp;rct=j&amp;frm=1&amp;q=&amp;esrc=s&amp;sa=U&amp;ei=BZmPVNiwFZf-yQTBgIGIBA&amp;ved=0CBoQtwIwAQ&amp;sig2=f0XGlnKmY0Q-6wz4OEW-pw&amp;usg=AFQjCNEd3nX4_b-peijT7oB6ogzpfot92w">Truthical</a>&nbsp;at&nbsp;<a class="g-profile" href="https://plus.google.com/113284816242244797515" target="_blank">+GatewayPeople</a>&nbsp;Church in Southlake, TX. The subtext: <br /><br /><blockquote class="tr_bq">The Part Is Yours... if you want it...&nbsp;&nbsp; </blockquote>The main character, a famous actress, is aware that there is more to life, or at least hopes there is. She receives a pamphlet for a casting call that her agent tells her to avoid. It's for a show called "Truthical". She wonders into the stage and is met by a yound lady who begins to tell her about this wonderful producer, and how there are no auditions, anyone who wants to be in the production can be in it.... you are left with a question at the end... The Part Is Yours, but...<br /><br /><blockquote class="tr_bq">Will you accept the part designed and created just for you? </blockquote><div></div><br />The crux of the question is to ask a lost person if they would accept the call to accept Jesus and be saved. It's among the best evangelistic tools I've ever seen because I, yes even I, found myself weeping, and laughing, and carried away with this marvelous production to the very same question... <br /><br /><blockquote class="tr_bq">So after you accept the call to be saved, will you accept the calling He has placed on your life? Will you accept the part he has written just for you? </blockquote><br />I'm saved, born again, baptised in the Holy Spirit, working my way free from Religion and toward Freedom In Him. In fact, they mentioned religious tradition&nbsp;in the play. The main character says: "What you mean, get religion, and follow a bunch of rules and traditions?" The guide says "No, that's a difference production. It's called Tradionical, and it's much more widely known, and has had terrible reviews!" <br /><br />So why do I feel so... blank? Why do I feel like I should not just be headed toward doing something more, but actually have been doing it for a long time already by now. I feel like there is something I could have done had a taken a right turn a while back, and now I'm here wondering where here is. <br /><br />After taking the <a href="http://www.darrellwolfe.com/2014/11/discovery-finding-your-place-in-gods.html">Discovery</a> path I learned alot more about who I am, and who I'm not. I know I had tedious physical&nbsp;work that involves manipulating minute details with my hands. Everything from wood carving to data entry to building computers is out for me. I know writing is a part of my path, which is why I'm here, writing blogs that few may ever read. I cannot help but write. And so I write. <br /><br />Music? Maybe. I find music follows me whereever I go, like a lost dog asking me to take it home. But I don't find myself drawn toward it, like I do writing. Maybe I just haven't found my place in music yet. <br /><br />And so... here I am, asking myself, asking God, what is my part? What was the role written just for me from before time, and how do I stop lolligaging and get to it!? <br /><blockquote class="tr_bq"><br /><strong>What about you? Do you know what your role is? What have you been cast for? And have you ever tried to live our someone elses role because you thought it was yours or you wanted it to be yours, only to find it didn't fit right (like taking a shower with your clothes on)? Answer in the comments below, or hit me on the twitter or Google+. </strong></blockquote><br /><br /><br /><br /><br /><br /><h4><div><script src="https://apis.google.com/js/plusone.js"></script><g:plus action="share"></g:plus></div></h4><h4>By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a></h4><div><a href="http://www.darrellwolfe.com/p/about-20.html" style="font-family: Georgia, 'Times New Roman', serif;" target="_blank">About This Blog, and Darrell.&nbsp;</a></div>