---
title: 'Discovery |  Uniquely You Spiritual Gifts'
date: '2014-10-20T06:14:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8286410321952842472'
blogger_filename: '/2014/10/discovery-uniquely-you-spiritual-gifts_19.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Discovery'
---

<br /><br /><h3><a href="https://uniquelyyou.org/content/combining-23-spiritual-gifts-and-4-disc-personality-types-approx-40-printed-pgs-summarized-s" target="_blank">UniquelyYou.Org | Spiritual Gifts Assessment </a></h3><br /><div id="primary-sg"><div id="primary-sg-title"><h4>Primary Spiritual Gifts</h4></div><ul><li>Teaching (40/40) </li><li>Prophecy / Perceiving (38/40) </li><li>Leadership (38/40) </li><li>Encouraging / Exhorting (38/40) </li></ul></div><div id="good-fit-opp-title"><h4>Good Fit Opportunities</h4></div><ul><li>Coaching</li><li>Deacons / Deaconesses</li><li>Discipleship</li><li>Elders</li><li>Men's Women's Ministries</li><li>Scripture Reader</li><li>Trustees</li></ul><br /><div id="primary-sg-desc-title"><h4>Your Primary Spiritual Gifts Descriptions</h4></div><div class="intro">Spiritual Gifts are supernatural motivations given to every believer. Everyone doesn't receive the same gift.   Just as many parts of the human body work together as one, so Spiritual Gifts are given to the Body of Christ to serve as one.<br /><br />Their purpose is to encourage and mature Christians for more  effective ministry. These gifts are featured based upon their functional   and practical use.<br /></div><div style="font-weight: bold;">Teaching<br /></div>Christians  with the Gift of Teaching prefer explaining why things are true. While  the prophet declares truth,     the teacher explains the reasons why it is true. Interested in  research, those with the Gift of Teaching like to dig into seemingly     insignificant details. They enjoy presenting what they discover.  Often negligent of the needs of others, they press toward a deeper     understanding. They love to study. Searching patiently and  persistently, they may miss the obvious. They stretch the limits of  learning,     setting high standards of education.<br /><b>In a word:</b> In-depth<br /><b>Overuse:</b> Digs too deep<br /><b>Goal:</b> Reveal truth, don't exhaust it<br /><b>Scripture:</b> Rom. 12:6,7b; Col. 3:16; Jam. 3:1; 2; 2 Tim. 2:2<br /><br /><div style="font-weight: bold;">Prophecy / Perceiving<br /></div>Prophets  today are not exactly like prophets of old. Old Testament Prophets  spoke the literal Word of God.     Today people with the Gift of Prophecy seem to have the same  seriousness and straight forward attitude toward truth. They like to  share     truth, regardless of what anyone thinks. Prophets today are  motivated to confront anyone with what they believe is right.     When controlled by the Holy Spirit, the Gift of Prophecy is a  powerful tool to reprove, rebuke and exhort others.     Prophets often find themselves pointing the way, declaring specific  truth or standing up for something significant.<br /><b>In a word:</b> Bold<br /><b>Overuse:</b> Fighter<br /><b>Goal:</b> Declare truth, don't divide Christians<br /><b>Scripture:</b> ph. 4:7,11; 1 Cor. 14:1,3; 2 Pet 1:19-21<br /><br /><div style="font-weight: bold;">Leadership<br /></div>The  Gift of Leadership, much like the Gift of Administration / Ruling, is  evident in those who demonstrate an unusual     ability to influence others. They seem to have an independent  determination to challenge and direct others toward a specific goal.     They stand out and take stands. Those with the Gift of Leadership  tend to be multi-talented excelling with their people and tasks skills.     Often result-oriented and driven, they need to guard their  strengths. They also need to be more sensitive and patient with those  who     don't respond as well or positive as they. They are great  motivators. <br /><b>In a word:</b> Dreamer<br /><b>Overuse:</b> Too demanding and impatient<br /><b>Goal:</b> Lead by example and willingness to be a servant<br /><b>Scripture:</b> Rom. 12:6,8c; John 13:13-17; Heb. 13:17<br /><br /><div style="font-weight: bold;">Encouraging / Exhorting<br /></div>Christians  with the Gift of Encouraging find themselves exhorting others. They are  compelled to give advice. As     counselors, they seem to often have steps of action. While Prophets  declare truth and Teachers clarify truth, Encouragers / Exhorters     like to tell you what to do with truth. They bless others with a  strong sense of concern. Often looking to encourage others, they are     sought out as counselors. People find Encouragers friendly,  understanding and practical. They enjoy using their communication skills  to     share specific insights.<br /><b>In a word:</b> Encourager<br /><b>Overuse:</b> Talks too much<br /><b>Goal:</b> Apply truth, don't create expectations<br /><b>Scripture:</b> Rom. 12:6,8; Acts 11:23-24; Heb. 10:24-25<br /><br /><br />