---
title: 'Bomb Vision | Eta'
date: '2014-11-25T02:38:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7993100424485424382'
blogger_filename: '/2014/11/bomb-vision-eta_24.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
---

<br /><br /><br /><br /><br /><br />City street. cars driving by. People walking along, minding their own business, most looking down at their smart phones as if they were walking by GPS. Now there's people running, the streets of roped off, and they are wearing a variety of joggins suits, they have numbers on their backs. It's a marathon.&nbsp;She knows this place, but she's never been here. Boston, MA. A flash of light. Glass splattered. the percussion hits her chest and it's over... <br /><br /><br /><br />Her friend Janice is still chatering away about the latest episode of Blacklist. She must not have been staring blankly for long, because her friend didn't notice at all. These waking dreams are getting more and more vivid. More details. It's strange how eerie they are. Suddenly, she notices everyone in the bar looking to the T.V. Stunned silence. Another terrorist attack. This time a bomb went off at the Boston Marathon... wait, did they say Boston? A sick feeling comes over her... is that even possible? <br /><br /><br /><br />Her friend notices that she's gone pale, she asks the bartender for water. They start to fan her. Eta folds her head into her hands and starts to cry, for the first time in 20 years, she is crying uncontrollably, and she's not entirely sure why... and she loves it... and she hates it... and she let's it wash over her. <br /><br /><br /><br /><br /><br />***<br /><br /><br /><br /><br /><br />Darrell Wolfe