---
title: 'Research: Erase Hard Drive/ Thumb Drive'
date: '2014-12-02T03:26:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6710027492609772709'
blogger_filename: '/2014/12/research-erase-hard-drive-thumb-drive.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
  - 'Research'
---

<br /><br /><br /><br /><h2><a href="http://www.techrepublic.com/blog/the-enterprise-cloud/five-ways-to-intentionally-destroy-your-data/">2: Degaussing</a></h2>Hard drives are nothing more than bottles of data held in place by magnetic glue. By removing the magnetic glue, you can create a breakdown of the underlying bits and bytes and scramble them in a way that's pretty tough to recover from. If the degaussing device used is good enough, you'll destroy all of the bits and bytes at the user level as well as the low-level formatting that makes it function as a drive. (If you're serious about data security, you'll use a powerful degausser.)<br />Although degaussing might be looked at as a way of simply erasing a drive, it's actually a destructive mechanism, though <a href="http://www.youtube.com/watch?v=5zKjGQAPhUs" target="_blank">it's not nearly as fun to watch</a> as a shredder.<br />Powerful degaussers will also render inoperable a drives servo motors and will damage the spindle motor of the drive. It truly is a paperweight when you're done.<br />A really good degausser is expensive, but it doesn't cost as much as a really good shredder, and it might be enough for your needs. Also, it's a fast process. Take a look at <a href="http://www.youtube.com/watch?v=dt7YbhjXZfA" target="_blank">this YouTube video of a hard drive degausser in action</a>.<br /><br /><br /><br /><h2><span class="mw-headline" id="Magnetic_data_storage_media"><a href="http://en.wikipedia.org/wiki/Degaussing">Wiki: Degaussing</a></span></h2><h2><span class="mw-headline"></span>&nbsp;</h2><h2><span class="mw-headline">Magnetic data storage media</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="http://en.wikipedia.org/w/index.php?title=Degaussing&amp;action=edit&amp;section=3" title="Edit section: Magnetic data storage media">edit</a><span class="mw-editsection-bracket">]</span></span></h2>Data is stored in the <a class="mw-redirect" href="http://en.wikipedia.org/wiki/Magnetic_media" title="Magnetic media">magnetic media</a>, such as <a class="mw-redirect" href="http://en.wikipedia.org/wiki/Hard_drive" title="Hard drive">hard drives</a>, <a href="http://en.wikipedia.org/wiki/Floppy_disk" title="Floppy disk">floppy disks</a>, and <a href="http://en.wikipedia.org/wiki/Magnetic_tape" title="Magnetic tape">magnetic tape</a>, by making very small areas called <a href="http://en.wikipedia.org/wiki/Magnetic_domain" title="Magnetic domain">magnetic domains</a> change their magnetic alignment to be in the direction of an applied magnetic field. This phenomenon occurs in much the same way a compass needle points in the direction of the Earth's magnetic field. Degaussing, commonly called erasure, leaves the domains in random patterns with no preference to orientation, thereby rendering previous data unrecoverable. There are some domains whose magnetic alignment is not randomized after degaussing. The information these domains represent is commonly called magnetic <a href="http://en.wikipedia.org/wiki/Remanence" title="Remanence">remanence</a> or <a class="mw-redirect" href="http://en.wikipedia.org/wiki/Remanent_magnetization" title="Remanent magnetization">remanent magnetization</a>. Proper degaussing will ensure there is insufficient magnetic remanence to reconstruct the data.<sup class="reference" id="cite_ref-2" jquery111103204393070843961="58"><a href="http://en.wikipedia.org/wiki/Degaussing#cite_note-2"><span>[</span>2<span>]</span></a></sup><br />Erasure <i>via</i> degaussing may be accomplished in two ways: in <a href="http://en.wikipedia.org/wiki/Alternating_current" title="Alternating current">AC</a> erasure, the medium is degaussed by applying an alternating field that is reduced in amplitude over time from an initial high value (i.e., AC powered); in <a href="http://en.wikipedia.org/wiki/Direct_current" title="Direct current">DC</a> erasure, the medium is saturated by applying a unidirectional field (i.e., DC powered or by employing a <a class="mw-redirect" href="http://en.wikipedia.org/wiki/Permanent_magnet#Types_of_permanent_magnets" title="Permanent magnet">permanent magnet</a>). A <b>degausser</b> is a device that can generate a magnetic field for degaussing magnetic storage media.<sup class="reference" id="cite_ref-3" jquery111103204393070843961="61"><a href="http://en.wikipedia.org/wiki/Degaussing#cite_note-3"><span>[</span>3<span>]</span></a></sup><br /><h3><span class="mw-headline" id="Irreversible_damage_to_some_media_types">Irreversible damage to some media types</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="http://en.wikipedia.org/w/index.php?title=Degaussing&amp;action=edit&amp;section=4" title="Edit section: Irreversible damage to some media types">edit</a><span class="mw-editsection-bracket">]</span></span></h3>Many forms of generic magnetic storage media can be reused after degaussing, including audio <a class="mw-redirect" href="http://en.wikipedia.org/wiki/Reel-to-reel" title="Reel-to-reel">reel-to-reel</a> tape, <a href="http://en.wikipedia.org/wiki/VHS" title="VHS">VHS</a> videocassettes, and <a href="http://en.wikipedia.org/wiki/Floppy_disk" title="Floppy disk">floppy disks</a>. These older media types are simply a raw medium which are overwritten with fresh new patterns, created by fixed-alignment read/write heads.<br />For certain forms of computer data storage, however, such as modern <a class="mw-redirect" href="http://en.wikipedia.org/wiki/Hard_drive" title="Hard drive">hard drives</a> and some <a class="mw-redirect" href="http://en.wikipedia.org/wiki/Tape_backup" title="Tape backup">tape backup</a> drives, degaussing renders the magnetic media completely unusable and damages the storage system. This is due to the devices having an infinitely variable read/write head positioning mechanism which relies on special servo control data (e.g. <a href="http://en.wikipedia.org/wiki/Gray_code#Position_encoders" title="Gray code">Gray Code</a>) that is meant to be permanently embedded into the magnetic media. This servo data is written onto the media a single time at the factory using special-purpose servo writing hardware.<br />The servo patterns are normally never overwritten by the device for any reason and are used to precisely position the read/write heads over data tracks on the media, to compensate for sudden jarring device movements, thermal expansion, or changes in orientation. Degaussing indiscriminately removes not only the stored data but also the servo control data, and without the servo data the device is no longer able to determine where data is to be read or written on the magnetic medium. The medium must be <a href="http://en.wikipedia.org/wiki/Disk_formatting" title="Disk formatting">low-level formatted</a> to become usable again; with modern hard drives, this is generally not possible without manufacturer-specific and often model-specific service equipment.<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />