---
title: 'Dr Leona Tesla PHD Organizational Behavior from Harvard. Case studies that turn the tide in her research.'
date: '2014-03-23T06:14:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5258258700281424782'
blogger_filename: '/2014/03/dr-leona-tesla-phd-organizational.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Supernatural'
---

<h3 style="text-align: center;">03/23/2014 Writing Practice</h3><br /><br /><br /><br /><br />They started cropping up everywhere. It was one thing to have a healing line at a Church and have people healed of unverified things, "feeling better" didn't really account for a miracle in her mind. But this latest phenomenon was something else. She wasn't sure what yet, but it was something else.<br /><br />Dr. Leona Tesla received her PHD in Organizational Behavior from Harvard.<br /><blockquote class="tr_bq"><a href="http://www.hbs.edu/doctoral/areas-of-study/organizational-behavior/Pages/default.aspx" target="_blank">http://www.hbs.edu/doctoral/areas-of-study/organizational-behavior/Pages/default.aspx</a><br /><span style="background-color: white; color: #181818; font-family: 'Trade Gothic W01 Roman', Arial, Helvetica, Verdana, sans-serif; font-size: 17px; line-height: 24px;">The Organizational Behavior program is presented jointly by the faculty of Harvard Business School and the&nbsp;</span><a class="ext" href="http://www.wjh.harvard.edu/soc/" style="background-color: white; color: #a41034; font-family: 'Trade Gothic W01 Roman', Arial, Helvetica, Verdana, sans-serif; font-size: 17px; line-height: 24px; text-decoration: none;">Department of Sociology</a><span style="background-color: white; color: #181818; font-family: 'Trade Gothic W01 Roman', Arial, Helvetica, Verdana, sans-serif; font-size: 17px; line-height: 24px;">&nbsp;in the Faculty of Arts and Sciences. The program combines training in the theory and methods of <b>psychology </b>and <b>sociology</b>, the study of <b>business administration</b>, and <b>empirical research on organizational phenomena</b>. Students have the choice of focusing their research at either the micro (i.e. psychological, interpersonal) or macro (i.e. sociological, organizational) level.</span></blockquote>Dr. Tesla did her Doctoral Thesis on the group dynamics of healing ministries, debunking most as pure fakes and frauds, and others as well intentioned but benign entities.<br /><br />"I wouldn't say I'm on a mission to debunk them all..." She confided to her friend, "... I am merely on a search for the truth. These people should want truth just as much as I do. After all they are putting their trust, and money, into this stuff."<br /><br />But now, sitting in her office staring at this new growing trend, she was perplexed. These were no slick suited preachers asking for money in exchange for a laying on of hands. They weren't even holding services. These were, from all outward appearances, every day men and women. They were Doctors, Lawyers, Mechanics, Servers, Cashiers, and Janitors. They came from all back grounds. They came from all over the country.<br /><br />The stories intrigued even her skeptic mind, if for no other reason than the sheer number of them.<br /><br />Take for instance the case study of Gwendolyn Manning. She was an 87 year old widow. She'd been brought to the store by her care worker to buy groceries. "<i>My favorite outing of the week</i>" she said.<br /><br /><blockquote class="tr_bq"><i>The grocery clerk that was stocking the shelves stopped to say hello, "Like he does every week" Gwen recounts.&nbsp;</i><i><br /></i><i>"But this time he's just happier, you know darlin', like he got a pep in his step!" Gwen smiles. "He reaches his hand out to take mine and says,&nbsp;</i><i><br /></i><i>'Can I pray for anything today Gwen Dear?',&nbsp;</i><i><br /></i><i>I says to him 'Well, you know it sure would be nice to heal up from these surgeries and walk again... but Doctor says that isn't in the card no mo'.&nbsp;</i><i><br /></i><i>'Well Gwen, you know anything is possible for God.'</i><i><br /></i><i>Then he reaches out to touch my hand and says 'Gwen, be healed, and walk again, in Jesus Name', then he smiles really big and nods. He goes back to stocking his shelves. Well I didn't think anything of it. Until a few isles later I saw something I wanted high on the third shelf up and my aide had gone to another isle, and almost like a gut reaction I just stood up to get it myself. I was putting it in my cart and walking with the cart down a few feet to get something else I just had to have when my aide screams from the end of the isle...&nbsp;</i><i><br /></i><i>"Ms Gwen! You're Walking?!" She looks shocked and happy and scared all at the same time!&nbsp;</i><i><br /></i><i>"Well, I said, so I am. And I just kep' walking down the isle, and I walked right out that store, and my aide had to bring the electric wheel chair herself and I aint stopped walking since. Honey, I walked three miles yesterday in the rain! Just because I could!"&nbsp;</i></blockquote><br />What an odd encounter. She interviewed the woman's doctors, examined pre and post XRays. The metal that had been installed in the womans hips was completely missing, and brand new bones had replaced it. The metal had vanished. It was the oddest thing she'd ever seen.<br /><br />But once Dr Tesla put out the article in the classifieds, and put a paid Facebook add out asking for verifiable testimonies of healing, account after account had come in to her office. 85% of them she normally through out, but this week her mail box had exploded. She had to shut down her ads due to overwhelming response.<br /><br />Gwen was just one such case. In most church cases there is nothing more than a placebo effect on a mass group scale taking place. That was the conclusion of her research. But now... well now some other phenomenon was in play. She wondered to herself for a moment if she'd been watching too many episodes of <a href="http://www.syfy.com/alphas" target="_blank">Alpha's </a>and had lost her skeptic edge?<br /><br />This would need to be verified more. She was going to need to bring in help. Someone with an even higher degree of skepticism than hers. Maybe even someone with a vendetta to prove them wrong, that might just balance her current situation. Because she found herself being swayed, ever so slightly, by what she was seeing. A stronger skeptic around might not be a bad idea.<br /><br />It's time to call Aaron Worcheskivitch "Skeptic At Large".<br /><br /><br /><br />******<br /><br />Thank you for reading. I hope you enjoyed this. I'd love to make a community with this project. If you would like to add, comment on, critique, or otherwise participate... that would be great!<br /><br />Please include any information about yourself, your blog/wesbite/amazon author page that you want to share with the community also.<br /><br /><i>* I may include "Affiliate Links" which means I earn a commission when you buy products I link to. To see my full about page and disclosures:&nbsp;<a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a></i><br /><br /><a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br /><br />To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br /><br />For Non-Fiction writing by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell G. Wolfe: Click Here</a><br /><br /><br /><br /><br /><br /><div style="clear: both; float: left; padding-bottom: 10px; text-align: right;"><br /></div>