---
title: 'The secret key to being happy!'
date: '2014-03-07T13:53:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4628057554932767222'
blogger_filename: '/2014/03/the-secret-key-to-being-happy.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<h3>2014/03/07 Bible Journal Friday</h3><h4><br /></h4><h4>COME:</h4><blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px; margin-bottom: 20px; padding: 0px;"><br /><a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">Day 115</a><br />Let Jesus Wash Your Feet<br />John 13:8<br />8Peter said to Him, “You shall never wash my feet!” Jesus answered him, “If I do not wash you, you have no part with Me.”</blockquote><blockquote class="tr_bq"><span style="background-color: #eeedeb; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px;">Once we have accepted Christ as our Lord and Savior, we are bathed all over, and cleansed by His blood once and for all eternity! His blood has perfected us forever (Hebrews 10:14), and we only need to wash our feet because we walk in the world and our feet pick up dust and dirt, causing us to stumble....</span>&nbsp;<span style="background-color: #eeedeb; color: #333333; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 12px; line-height: 21.600000381469727px;">by washing our feet with a deeper revelation of Himself through His Word. Beloved, this is what gives us victory in our daily walk!</span></blockquote><br /><br /><blockquote class="tr_bq" style="-webkit-background-clip: padding; background-clip: padding-box; background-color: white; border: 0px; color: #888888; font-family: 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 17px; line-height: 2em; margin: 0px; padding: 0px; text-indent: 1em;"><a href="https://www.bible.com/users/darrellwolfe/reading-plans/28-joseph-prince?initial=true&amp;user_id=darrellwolfe" target="_blank">John 13</a><br /><blockquote><span class="verse v12" data-usfm="JHN.13.12" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; cursor: pointer; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">12</span><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;">So after he had washed their feet, and had taken his garments, and was set down again, he said unto them,&nbsp;</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; margin: 0px; padding: 0px;">Know ye what I have done to you?</span></span></span><span class="verse v13" data-usfm="JHN.13.13" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">13</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; margin: 0px; padding: 0px;">Ye call me Master and Lord: and ye say well; for so I am.</span></span></span><span class="verse v14" data-usfm="JHN.13.14" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">14</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; margin: 0px; padding: 0px;">If I then, your Lord and Master, have washed your feet; ye also ought to wash one another's feet.</span></span></span><span class="verse v15" data-usfm="JHN.13.15" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">15</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; margin: 0px; padding: 0px;">For I have given you an example, that ye should do as I have done to you.</span></span></span><span class="verse v16" data-usfm="JHN.13.16" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">16</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; margin: 0px; padding: 0px;">Verily, verily, I say unto you, The servant is not greater than his lord; neither he that is sent greater than he that sent him.</span></span></span><span class="verse v17" data-usfm="JHN.13.17" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="label" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #aaaaaa; font-weight: bold; line-height: 1; margin: 0.9em 4px 0px 0px; padding: 0px;">17</span><span class="wj" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; margin: 0px; padding: 0px;"><span class="content" style="-webkit-background-clip: padding; background-clip: padding-box; border: 0px; color: #c45e5e; margin: 0px; padding: 0px;">If ye know these things, <b><i><u>happy</u></i></b>&nbsp;are ye if ye do them.</span></span></span></blockquote></blockquote><br /><h4>HEAR:</h4>Happy... I haven't been REALLY happy in a long long time. I've been so concerned with service. I'm serving him at home. I'm serving him at work. I'm serving him by writing my blogs... But...<br /><br />I notice here, a pre-requisite to service. It's being washed by Him! Not just once. Daily. Washed daily in his Word and Presence. It's not enough just to read a passage of devotional and check that off the list. That's not His presence.<br /><br />I must spend time in worship and prayer AND Word. Actually reading his Word. If I want this result of "Happy".<br /><br /><h4>DO:</h4>I'm going to spend more time BEING with Jesus, and less time DOING for Jesus!<br /><br /><br /><br /><br /><b>How about you? You see anything to add to this? Want to share what examples you have seen or experience in yourself or others? Comment below.&nbsp;</b><br /><div><b><br /></b></div><b>I call you empowered 2 prosper with good success!</b><br /><b><br /></b><a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank"><b>By&nbsp;</b><b><span style="font-size: x-small;">Darrell Wolfe</span></b></a><br /><b><span style="font-size: x-small;"><br /></span></b><b><span style="font-size: x-small;"><br /></span></b><br /><div class="separator" style="clear: both; text-align: center;"><a href="/images/imported/blogger-googleusercontent-com/e2p-logo-b7b5454b818d.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><br /></a></div><div class="separator" style="clear: both; text-align: center;"><a href="/images/imported/blogger-googleusercontent-com/e2p-logo-b7b5454b818d.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><br /></a></div><div class="separator" style="clear: both; text-align: center;"><a href="/images/imported/blogger-googleusercontent-com/e2p-logo-b7b5454b818d.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><br /></a></div><b>Bible Study Blog</b>:&nbsp;<a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br /><b>Facebook</b>:&nbsp;<a href="https://www.facebook.com/DarrellGWolfe" rel="nofollow" target="_blank">Facebook.Com/DarrellGWolfe</a><br /><b>Twitter</b>:&nbsp;<a href="http://twitter.com/darrellwolfe" rel="nofollow" target="_blank">@DarrellWolfe</a><br /><b>Personal Blog</b>:&nbsp;<a href="http://www.darrellwolfe.com/">www.DarrellWolfe.Com</a>