---
title: 'It Is Written - 21 Day Gateway Church Devotional Challenge Day 2'
date: '2014-01-07T13:26:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5207818768118886682'
blogger_filename: '/2014/01/it-is-written-21-day-gateway-church_7.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<br /><h3 style="text-align: center;"><a href="http://gatewaydevotions.com/it-is-written/day-2" target="_blank">It Is Written - 21 Day Gateway Church Devotional Challenge</a></h3><h4 style="text-align: center;">Day 2</h4><div style="text-align: center;"><br /></div><div style="text-align: center;">Ok, so it's Jan 7th and I'm on day two? Yes I'm behind. I'll be catching up tomorrow probably.&nbsp;</div><h4>Come:</h4><blockquote class="tr_bq">Matthew 4:4 (New International Version)<br />4 Jesus answered, "It is written: 'Man does not live on bread alone, but on every word that comes from the mouth of God.' " <br /><br />Joshua 1:8 (New International Version) <br />8 Do not let this Book of the Law depart from your mouth; meditate on it day and night, so that you may be careful to do everything written in it. Then you will be prosperous and successful. <br /><br /><br />Job 23:12 (New International Version) <br />12 I have not departed from the commands of his lips; I have treasured the words of his mouth more than my daily bread. <br /><br /><br />Isaiah 55:2 (New International Version) <br />2 Why spend money on what is not bread, and your labor on what does not satisfy? Listen, listen to me, and eat what is good, and your soul will delight in the richest of fare.</blockquote><br /><h4>Hear:</h4>Daily time is paramount to success in life. My daily routine doesn't need to be three hours of prayer and bible study every morning. It can be ten minutes of quiet and prayer, ten minutes of bible and devotional, and ten minutes of journal. Routine, no matter how small, is better than binge eating God's word, followed by weeks and months of starving.<br /><br /><br /><h4>Do:</h4>My new Routine, roughly ten minutes each of:<br /><br /><ul><li>Quiet. Nothing by some rain sound for background noise. Not praying, not reading, just letting the dust settle in my mind.</li><li>Prayer. Actively praying for Flavia, the Kids, and more.&nbsp;</li><li>Journal. A short daily journal entry. Private that no one else reads. I'll ask myself three things.&nbsp;</li><ul><li>What am I thankful for?</li><li>What am I feeling?</li><li>What's going on in life right now?</li></ul></ul><div><br /></div><div>DW</div><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />