---
title: 'How Sound Affects Your Brain'
date: '2014-11-04T05:53:00.0020000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3901673185541208380'
blogger_filename: '/2014/11/how-sound-affects-your-brain_3.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
  - 'Research'
---

<div dir="ltr"><br /><br />  Instead, you can use a concept called "brainwave entrainment" to get the same effect.</div><br /><div dir="ltr"><br />Brainwave entrainment is any method that causes your brainwave frequencies to fall into step with a specific frequency. It's based on the concept that the human brain has a tendency to change its dominant EEG frequency towards the frequency of a dominant external stimulus (such as music, or sound).</div><br /><div dir="ltr"><br />The type of sound frequencies that are typically used in brainwave entrainment are called "binaural" beats. The way that these work is that two tones close in frequency generate a beat frequency at the difference of the frequencies.</div><br /><div dir="ltr"><br /><br /></div><br /><div dir="ltr"><br />I know this sounds complicated, but it's pretty simple to understand when you think about it. For example, a 495 Hz audio tone and 505 Hz audio tone (whether overlaid in music or in a sound frequency) will produce a 10 Hz beat, roughly in the middle of the alpha brain wave range, like this:</div><br /><div dir="ltr"><br /><br /></div><br /><div dir="ltr"><br /><a href="http://www.bengreenfieldfitness.com/2012/05/how-you-can-use-sound-and-music-to-change-your-brain-waves-with-laser-accuracy-and-achieve-huge-focus-and-performance-gains/">http://www.bengreenfieldfitness.com/2012/05/how-you-can-use-sound-and-music-to-change-your-brain-waves-with-laser-accuracy-and-achieve-huge-focus-and-performance-gains/</a></div><br /><div dir="ltr"><br />DarrellWolfe.com via Mobile</div><br />