---
title: 'Eta | The Need To Know'
date: '2014-11-28T20:03:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7501609851663507110'
blogger_filename: '/2014/11/eta-need-to-know.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
---

<br /><br /><br />Another day, another latte. More web searches turning interesting tid bits of seemingly useless data. It's a distraction, but she's no closer to the answer. Eta stares into the crowds below as they meander through the mall. <br /><br />The man in black is back again. He passes the lockers, again. Every day, like clock work, except that he strikes at a different time each day, there seems to be no pattern, or ryhme to his showing up. It's given her something to expect each day. How is leaving? <br /><br />The thought struck her so quickly it was as though it was not her thought. To her knowledge of the floor plans she hacked her way into for this mall, there was no exit down that hallway. It led to lockers, and two bathrooms with no windows or doors. And yet... everyday, he came. She&nbsp;assumed it was a he, you&nbsp;never know these days, but the build was mandly, nice even... no, Eta doesn't have those thoughts. Shut them out. Shut them down. Focus on the tasks at hand. <br /><br />Different times of day. He (or she... but probably a he) comes at different times each day. He passess the locker in her vision, and he never comes out. She's here until close, and he never comes out. Where is he going? He can't be spending the whole day in the bathroom, can he? But how does he leave without her seeing? She glances away periodically, if for no other reason than boredom, and not to look too conspicious. But could he be leaving while she's not looking each time? Two weeks she's been watching him, and he's been showing up and... not leaving? <br /><br />She's had enough! She's following him this time. She packs her laptop and bag, she meanders quickly enough to get there, but slowly enough to look nonchalant. She cannot be seen as following him. It was dangerous of course. She didn't know who he was, or why she was following him, but she wanted answers. CIA, Mosad, MI6, KGB, PRC... Hard to say. It's unlikely that he's affiliated with Falcons Nest (FC). She was one of a very few FC's in the world, and she was decomissioned. Suddenly the thought that he was watching her, and not the other way around struck her cold. What if he wants her to follow him back her, out of public line of site, so he can take her out in the hallways or rest room? It's what she'd have done. She stopped, in the middle of the court yard, staring down the long hallway toward the rest rooms. She wouldn't fall for that. <br /><br />Or, she was just bein paranoid, as her training had taught her to be, and this was just some skater kid or local mall rat who just happened to disapear down a long hallway, everyday, and never come out... curiosity told her to go in,&nbsp;paranoia told her to stay out. So she found a bench seat within few of the locker and hallway, but sat as though she wasn't watching, and opened her laptop. She'd angled the mirror inside her glassess toward the hallway and locker. She'd sit... and watch. <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />