---
title: 'The Tale Overdraft Prevention Pt 2'
date: '2014-01-14T15:27:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4920104506338332485'
blogger_filename: '/2014/01/the-tale-overdraft-prevention-pt-2.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Coffee House Money Chats'
---

<h3 style="text-align: center;">The Tale Overdraft Prevention Pt 2...</h3><br />"Well let's see. We stopped fees for purchases, which was 75-80% of your battle. Now let's deal with those last pesky payments. Anytime you use your account number or card number to pay a bill you run risks. The company takes days to clear the payment. The company takes a payment they weren't supposed to, take a payment after you told them to stop, they take the wrong amount, on the wrong date, and basically just mess up your account. So we need to completely stop giving your card or account number to other companies. Even checks can be turned into electronic items and mis-processed or you simply forget to write it down. The more you control things, the less they control things, the better. We need to pay bills without using checks, account numbers or debit card numbers."<br /><br />"How am I supposed to do that?"<br /><br />"Now you have options. You pay in person with cash. You take out cash and buy money orders and mail them..."<br /><br />"Wow, that would be a lot of extra work and cost to pay for envelopes and stamps and money orders."<br /><br />"Yes... but not as much cost as paying for overdraft fees."<br /><br />"That's true..."<br /><br />"But there is another option. You can use your bill payment service through your bank. Almost every bank offers one now. Pull up your app again...." Joe unlocks his screen and goes back to the main menu. "See here. 'pay a bill'..."<br /><br />"I think I noticed that before but I never paid attention to it."<br /><br />"You can get prepaid debit cards from various places with way less hassle than your bank gives you. This bill payment service is one of the only reasons to have a bank account. Check it out. You can make a payment to any bill. It doesn't have to be automatic, you just type in the amount, select a date and hit send. The money comes out of your account today and it's done. No waiting days for it to clear. Best part? The other company never gets your account number. I even send my mom birthday checks through bill payment service at my bank. She gets a cashiers check in her mail box within a week. But most of my payments are large companies so they get the payment in 1-2 days electronically."<br /><br />"That sounds cool. But what if I'm paying it the day it's due?"<br /><br />"That's why you can't just have the tools you need a system to use them the right way. There's a few more things to discuss."<br /><br />"You...<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />..... "Let's meet again and talk about how it's working for you. When would be a good time to meet?"<br /><br /><br />