---
title: 'Island Wake Up Call'
date: '2014-10-26T06:08:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6357319526454916221'
blogger_filename: '/2014/10/island-wake-up-call_25.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
---

<br /><br />Ash came to himself blinded by a terrible light, which hurt his eyes. He rolled over onto his belly, and planted his face into his pillow... No, this wasn't a pillow, it was... sand? He accidentally breathed some in and began coughing uncontrollably. He would have to get his bearings, but first he'd have to get his senses. He rose to his hands and knees and calmed his mind, slowed his heart rate. Focus. That's what he needed right now. His eyes still hurt too much to open, but he didn't need them just yet.<br /><br /><br /><br />Birds. Sand. Wind in trees. Water washing ashore in a quiet steady cadence. He was back on the island? The sand between his fingers was cold to the touch, but the sun on his back and face was quite warm. These had to be white sand islands. He was back to the training center? Had he ever left? What happened.... wait... What is that?<br /><br /><br /><br />***********<br /><br /><br /><br /><br /><br />Eta was thrashing around, blindly looking for something or someone to attack. It was only after she ran out of breath that she realized she was alone. Her eyesight was coming back, but it was still much to bright to fully open her eyes, even with the clothe that she'd tied around her face to block the sun. <br /><br /><br /><br />All she could see was trees, water, sand. Now that she was too tired to fight.... nothing... she could hear the sounds of the island herself. There was one sound that was not familiar... A rustling in the trees, less than half a <a href="http://usmilitary.about.com/od/theorderlyroom/f/faqklickdef.htm" target="_blank">klick</a> away. <br /><br /><br /><br /><br /><br />****************<br /><br /><br /><br />Sir<br /><br /><br /><br />What is it seargent?!<br /><br /><br /><br />Motion sensors dedect movement on one of the south islands.<br /><br /><br /><br />We haven't trained down there in months. Are you sure it's not those stupid Monkey's again? <br /><br /><br /><br />We checked sir, camera footage is rough from the distance, but we captured this image.<br /><br /><br /><br />Well I'll be... Get a unit down there now, and go in armed, we don't know what to expect.<br /><br /><br /><br />Yes sir<br /><br /><br /><br />With that the door closed and left the General alone. Where have those two been?!<br /><br /><br /><br /><br /><br /><br /><br />******<br /><br /><br /><br />Thank you for reading. I hope you enjoyed <br />this. I'd love to make a community with this project. If you would like <br />to add, comment on, critique, or otherwise participate... that would be <br />great!<br /><br /><br /><br />Please include any information about yourself, <br />your blog/wesbite/amazon author page that you want to share with the <br />community also.<br /><br /><br /><br /><i>* I may include "Affiliate Links" <br />which means I earn a commission when you buy products I link to. To see <br />my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a></i><br /><br /><br /><br /><a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br /><br /><br /><br />To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br /><br /><br /><br />For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell G. Wolfe: Click Here</a>