---
title: 'Ash White Room'
date: '2014-12-27T20:26:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4686156854191216690'
blogger_filename: '/2014/12/ash-white-room.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
---

Bright blinding white permeated the room. A white cardboard box sat on a thin enameled snow white plastic table in a room covered in white painted steel walls. Only the black table legs gave any accent to the hyper real characteristics of this LED lit room. How he got here and why he didn’t know. Looking down he noticed the white form fitting uniform he was wearing. His deep tan the only other contrast in this other clinically pure room. A soft hiss was coming from the ceiling, but he couldn’t look up because the ceiling was lit from end to end to end with LED’s, turned on high, air conditioner maybe. He could barely see around him without squinting. Disorientation started to settle down after the first few moments awake and he found his bearings. Training kicked in.  His thoughts moved to business, take stock. “Name/Rank: Captain Therun Ashmun.”, he said out loud, more to himself than anyone else. No response. Taking inventory of his body, every part was accounted for, legs, arms, toes, fingers, the scar on his neck under his right ear. No pains, other than the usual. He sat down on his knees monk style and closed his eyes and took deep breaths. Capt Therun “Ash” Ashmun tried to recall his last memory before finding himself in this room void of any obvious doors, windows, or openings of any kind, not even a seem was apparent as he circled the room with his eyes. The thoughts came like rapid fire. He didn’t bother feeling about because he was obviously handled before arriving here and obviously must be under surveillance this very moment. No way to defend against attack without knowing where the openings are, but there would be no use because if he were going to be killed he would be in some danky prison cell not this white washed room in some overly tailored biking suit. Still, better to be defensive and keep himself against a wall ready to react.  “Bring it in Ash, bring yourself together… all this white is a bit disorienting. What was the last thing you recall?” He had been on Sriklan Island a survival training facility. He had just dropped in from 15,000 feet in air-camo nearly a new suit-shoot being developed, nearly invisible from the ground and air. He landed without a hitch, taking out three guards, high tech motion sensored mannequins, from the air. Working through the forest to the hacienda he had retaken the residence and recovered the “stolen” technology and send it back up on a UAV that had landed after he signaled. Routine training mission. Next time they’d use people and fake bullets but this time real bullets and fake people provided real time use of the weapon. The fake bullets never quite felt right. One man recovery missions were a great way to have peace. He swam off island to a nearby island and was waiting for his evac. He was perched in a tall tree, hidden by branches on the tallest point of the island. There was a flash of light around him and He… that’s it, there was no other memory. He woke up here.  The box on the table was the only thing in the room with him, besides the table itself, which seems to be built into the floor. He approached the table cautiously. Eyes had adjusted some to the light, but there was still not much to see. The legs and table appeared to be built of high strength alloy. No hopes of breaking it. He pushed at the box, but it too appeared to be a part of the table. It didn’t budge. Other than being attached it seemed like any other white shipping box, sealed in white duct tape end to end.  The table was cool to the touch, not cold, but cool, like everything else in this room, floor, walls, etc. Ash pealed at the tape slowly, ready to react to it’s contents. This box was obviously here for him, it was the only thing in the room, and no-one had reacted to his being awake. Laying the tape aside he opened the lid and found a pair of ear buds and an iPhone, each neatly wrapped in their own plastic bag. He opened the first bag and turned on the phone. It booted silently…   