---
title: 'Does Science Conflict With Christianity and the Bible? Not Directly.'
date: '2014-04-01T02:34:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7158226955113742033'
blogger_filename: '/2014/03/does-science-conflict-with-christianity.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Quote'
  - 'study'
---

<br /><h4><br />I started listening to the Phil Vischer podcast recently.&nbsp;</h4><br />It's really interesting because here is this guy with a dry wit and quirky humor and he's really very well versed in biblical truth. Then he brings on people who know quite a bit too. They banter back and forth and in between saying nothing about everything they begin to say some very profound things.<br /><br />One such example that got me thinking enough to comment on the post was Episode 80.<br /><br /><a href="http://philvischer.com/the-phil-vischer-podcast/thanksgiving-walmart-and-science-vs-the-bible-with-john-walton/#comment-67151">http://philvischer.com/the-phil-vischer-podcast/thanksgiving-walmart-and-science-vs-the-bible-with-john-walton/#comment-67151</a><br /><br />&nbsp;I'm just finding the podcast now and listening to older episodes. I came across this one and wanted to put my two cents in. I was REALLY interested in the conversation and topics brought up.<br /><br />Interesting Conversation: Science vs Christianity; are they opposed?<br /><br /><h4>Skye poses this question.</h4><br /><blockquote class="tr_bq">“Science posits “Uniformitarianism”, that all natural laws are what they are and do not change. It is the basis for discovery and making scientific assumptions. If gravity was different today than it was yesterday than how could we calculate anything in physical space? Doesn’t Christianity claim that laws do change, that nature was different before Genesis 1, will be different after Revelations 19, and it changes often when God intervenes (Miracles, Jesus Resurrection and&nbsp;Ascension, etc)? Do these conflict?”</blockquote><h4><br />My answer.</h4><br />No. Christianity makes no such claim. The Bible makes no claim that natural law (gravity and such) will have been different before or different in the future. The bible makes no claim that it won’t change either. There simply isn’t any information. What do these examples claim?<br /><br /><b>Natural Changes</b>: Earth Changing, sea being gone in the new earth. These are geographic changes. Like new islands popping up in the sea we have now. Rivers cutting new paths. These changes happen now too, they will be more dramatic in the “new earth”. Maybe he’ll even destroy the whole planet and give us a new one. That’s still possible within “natural law” for one who has power over it and created it in the first place. Of course, again, we don't know. Maybe he uproots the whole things and starts over.<br /><br /><b>Miracles</b>: Miracles, Jesus Resurrected Body and Ascension, these are not examples of natural law being changed. They are examples of “Higher Order Law” taking precedence over “Lower Order Law”. We see this in airplanes. Planes and birds do not break natural law of gravity to take off to flight. They use another higher order law, called the law of lift, to put themselves above the law of gravity.<br /><br />Miracles involve spiritual order laws which transcend and take precedence over natural law. When a man comes into a hospital room to a person with an "Incurable" disease and lays hands on that sick person and they become well. It's simply an example of Higher Order Spiritual Law taking place.<br /><br />My thought would be that these are not laws God came up with arbitrarily, but in fact they are of his nature. So the new heaven and new earth would have the same basic laws, yet we'd have better knowledge of and access to the higher order laws. Jesus new resurrected body is capable of putting into effect a higher order that we are not capable of putting into effect, at least not consistently.<br /><br /><blockquote class="tr_bq"><b>Miracles always seemed quite rational to me from that perspective.</b><b><br /></b><b>"A miracle is something science just doesn't understand yet..."</b></blockquote><br />Darrell<br /><br /><br /><br /><b>How about you? You see anything to add to this? Want to share what examples you have seen or experience in yourself or others? Comment below.&nbsp;</b><br /><div><b><br /></b></div><b>I call you empowered 2 prosper with good success!</b><br /><b><br /></b><a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank"><b>By&nbsp;</b><b><span style="font-size: x-small;">Darrell Wolfe</span></b></a><br /><b><span style="font-size: x-small;"><br /></span></b><b><span style="font-size: x-small;"><br /></span></b><br /><div class="separator" style="clear: both; text-align: center;"><a href="/images/imported/blogger-googleusercontent-com/e2p-logo-b7b5454b818d.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><br /></a></div><div class="separator" style="clear: both; text-align: center;"><a href="/images/imported/blogger-googleusercontent-com/e2p-logo-b7b5454b818d.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><br /></a></div><div class="separator" style="clear: both; text-align: center;"><a href="/images/imported/blogger-googleusercontent-com/e2p-logo-b7b5454b818d.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><br /></a></div><b>Bible Study Blog</b>:&nbsp;<a href="http://empoweredtooprosper.blogspot.com/" style="background-color: white;" target="_blank">http://empoweredtooprosper.blogspot.com/</a><br /><b>Facebook</b>:&nbsp;<a href="https://www.facebook.com/DarrellGWolfe" rel="nofollow" target="_blank">Facebook.Com/DarrellGWolfe</a><br /><b>Twitter</b>:&nbsp;<a href="http://twitter.com/darrellwolfe" rel="nofollow" target="_blank">@DarrellWolfe</a><br /><b>Personal Blog</b>:&nbsp;<a href="http://www.darrellwolfe.com/">www.DarrellWolfe.Com</a><br /><br />