---
title: 'Taking A Break Today 04/12/2014'
date: '2014-04-13T04:37:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1395926745053187302'
blogger_filename: '/2014/04/taking-break-today-04122014.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'News & Events'
---

<h3>I'm not posting this week.&nbsp;</h3><div>I decided that I'm not posting this week. I drained my mental engery on other things. But among those things was some writing I did for other topics. So I figured I'd let you know that I'm doing a prophecy study. Here is the first part excerpt from the first post I did for that study. If you'd like to read more click the link at the bottom.<br /><br /><br /><h3 class="post-title entry-title" itemprop="name" style="background-color: white; color: #666666; font-family: 'Trebuchet MS', Trebuchet, Verdana, sans-serif; font-size: 22px; font-weight: normal; margin: 0.75em 0px 0px; position: relative;">Daniel 2: The Statue of Nations and 4, make that 5, Kingdoms Of World History</h3><div class="post-header" style="background-color: white; color: #666666; font-family: 'Trebuchet MS', Trebuchet, Verdana, sans-serif; font-size: 11px; line-height: 1.6; margin: 0px 0px 1.5em;"><div class="post-header-line-1"></div></div><div class="post-body entry-content" id="post-body-4719133344697335756" itemprop="description articleBody" style="background-color: white; color: #666666; font-family: 'Trebuchet MS', Trebuchet, Verdana, sans-serif; font-size: 13px; line-height: 1.4; position: relative; width: 546px;"><h3 style="margin: 0px; position: relative;">The Four Kingdoms Before Jesus' Coming</h3>Daniel lays out in perfect high definition the ages of world history from his time to the end of time, as it pertains specifically to Israel.<br /><br />Daniel is not giving us all of history from Creation forward. He is giving us history as it pertains to World Level affairs, or World Kingdoms. Even more specifically only those world powers which, at one point or another, will have possession of God's People and God's Holy City Jerusalem.<br /><br />Although the USA and USSR both like to call themselves "World Superpowers", they are not World Kingdoms. They also do not, at this time, have possession of God's Holy City, so they would not be included in God's Recorded Calendar.<br /><br />Let's look at the text of Daniel Chapter 2 and then break it down.</div><a href="http://discerningthetime.blogspot.com/2014/04/daniel-2-statue-of-nations-and-4-make.html" target="_blank"><br /></a><a href="http://discerningthetime.blogspot.com/2014/04/daniel-2-statue-of-nations-and-4-make.html" target="_blank">To Read The Article Click Here</a><br /><br /><br /></div><h4>By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a></h4><div><h4><a href="http://darrellwolfe.blogspot.com/2013/11/connect.html" style="background-color: white; color: #397dbf; font-family: 'Trebuchet MS', Trebuchet, sans-serif; line-height: 16.363636016845703px; text-decoration: none;" target="_blank">Connect</a></h4></div><div><h4><i><b><span style="font-family: Trebuchet MS, Trebuchet, sans-serif;"><span style="line-height: 16.363636016845703px;">I am an&nbsp;affiliate</span></span></b></i></h4><br /><ul><li><span style="font-family: Georgia, Times New Roman, serif;"><i><span style="line-height: 16.363636016845703px;">I earn&nbsp;commissions&nbsp;off of some of my suggestions.&nbsp;</span></i><i style="line-height: 16.363636016845703px;">Full Disclaimers (<a href="http://www.darrellwolfe.com/p/about-20.html" target="_blank">Click Here</a>)</i></span></li><li><i><span style="font-family: Georgia, Times New Roman, serif;">See my Store for more suggestions (<a href="http://www.darrellwolfe.com/p/books-resources.html" rel="nofollow" target="_blank">Click Here</a>)</span></i></li></ul></div><h4>To Respond Leave A Comment on This Post</h4><br />