---
title: '36 Hours'
date: '2014-02-03T13:40:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6793323701772937095'
blogger_filename: '/2014/02/36-hours_3.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Writing Practice'
  - 'White Noise'
---

<h3 style="text-align: center;"><br />2014/02/03 Writing Practice</h3><br />The iPod only had two songs loaded. One said "Instruction", the other said "Listen". So Ash placed the ear buds in his ears and pressed play.<br /><br /><br /><br />"Greetings Capt Ashmun. No doubt you have many questions. Sadly you may not ever find the answers to all of them. However if you cooperate in this little experiment I can assure you that you will be returned to your old life, you are under no immediate physical danger. You won't recall volunteering for this assignment, an unfortunate side effect of the mind wipe procedure. All you have to do is listen to the next track. This room is a verbal room, so if you need to use the facilities simply say so, and the rooms AI will produce that for you. If you would like a bed, say so as well. Meals will be served three times a day. The track you are about to listen to will play for 36 hours. After which time you will be free to go. Thank you for your participation in this process. And now, let us begin..."<br /><br /><br /><br /><i>*(Maybe he's in here for 5 days... maybe there is no track, because he could choose not to put it in, probably would choose that. So maybe the iPod is ONLY instructions. The sound is coming from the room itself.)</i><br /><br /><br /><br />With that, there is a soft click and a slurry of sound comes from the iPod matching the sound that was playing from the roof. It was quite relaxing. Ash walked the perimeter of the room once more checking for any possible sign of escape. Thinking through the instructions is he called out-loud, "Bed", and &nbsp;a portion of the wall came undone through a small seam, a flat surface the size of a double bed came out of the wall, the top of the surface seemed to be made of memory foam. A small box opened just above holding a blanket and pillow.<br /><br /><br /><br /><i>(*They probably didn't leave in on the floor if there was a bed. In first setting have him on this bed, and it retracts when he gets up. He can't get it back until it's explained HOW to access the rooms features. Room ends up having a star trek feel? Food Replicators, things being beamed in? That could be cheesy or cool, depending on how you write it... )</i><br /><br /><br /><br />Ash didn't take long to catch on, he said out loud "Exit", nothing happened.<br /><br /><br /><br />"Now, Now Capt Ashmun, you know the rules, 36 hours..." came a voice from the speakers above.<br /><br /><br /><br /><br />