---
title: 'Images'
date: '2014-02-13T13:37:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3258468333214366023'
blogger_filename: '/2014/02/images_13.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Writing Practice'
---

Whisps of images pass before him. It started Yesterday. One here or there. At first they seemed like shadows, mere plays of light on highly reflective walls. <br /><br />Now they are taking form. High tech place. <br /><br />Whatever these holograph's are supposed to be they were odd. Some were starting to resemble people. Others animals. Still not clear enough to make out exactly.<br /><br />*****<br /><br />Do you suppose it's working?<br /><br />He's reacting to something.<br /><br />What's wrong with the implant? <br /><br />We have images... but we're not seeing whatever it is he <u>is</u><br /><br /><u><br /></u><br /><u><br /></u><br /><u><br /></u><br /><br /><br />******<br /><br /><br /><br />Thank you for reading. I hope you enjoyed this. I'd love to make a community with this project. If you would like to add, comment on, critique, or otherwise participate... that would be great! Please include any information about yourself, your blog/wesbite/amazon author page that you want to share with the community also.<br /><br /><br /><br /><br /><br /><a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://twitter.com/DarrellWolfe" target="_blank">@DarrellWolfe</a><br /><br /><br /><br />To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br /><br /><br /><br />For Non-Fiction writing by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell G. Wolfe: Click Here</a><br /><br /><br /><br />Any work not otherwise attributed is Copy Right Darrell G. Wolfe<br /><br /><br /><br />All Rights Reserved © Darrell G. Wolfe<br /><br /><br /><br /><b>Disclosure of Material Connection: Some of the links in the post above are “affiliate links.” This means if you click on the link and purchase the item, I will receive an affiliate commission. I may also have received one or more of the products or services mentioned above for free in the hope that I would mention it on my blog. Regardless, I only recommend products or services I use personally and believe will add value to my readers. I am disclosing this in accordance with the Federal Trade Commission’s&nbsp;<a href="http://www.gpo.gov/fdsys/pkg/CFR-2003-title16-vol1/content-detail.html" target="_blank">16 CFR, Part 255</a>: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.” A Big Thank You to&nbsp;<a href="http://michaelhyatt.com/five-ways-to-comply-with-the-new-ftc-guidelines-for-bloggers.html" target="_blank">Michael Hyatt</a>&nbsp;for helping us Bloggers with these new legal disclosure requirements.</b><br /><br /><br /><br /><br />