---
title: 'Command the winds!'
date: '2014-01-20T15:14:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4230624923836069537'
blogger_filename: '/2014/01/command-winds.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<h4>COME</h4><br /><div style="text-align: center;"><iframe allowfullscreen="" frameborder="0" height="333" mozallowfullscreen="" msallowfullscreen="" oallowfullscreen="" src="http://www.flickr.com/photos/dullhunk/7442742102/in/photolist-ckFZVG-eiAx6R-eiAybT-eiGhhS-bZJknS-bZJn4E-bZJkL1-bZJmfu-bZJmBy-bZJm35-bZJmvJ-bZJnbL-bZJmnw-bZJnmm-bZJnuy-jgfsiH-7yH1uK-9rywdd-fEj9JA-eXJM2E-eiAwEe-9m3FCy-acdiXn-abeZ22-bZJkSb-bZJm9N-bZJmHd-96m3ES-7xWBC9-8PXijg-cAfzYE-cAfB2j-cAfzsy-cAfB7G-cAfAbq-aFyhaH-cAfzMW-fuZ5av-8mqS1U-cAfAUq-cAfzAN-cAfAEq-fveHTs-cAfAz5-api7tB-api8c8-api8KZ-api6MM-apkRQJ-api7ex-apkQ2y/player/" webkitallowfullscreen="" width="500"></iframe></div><div style="text-align: center;"><br /></div><blockquote class="tr_bq"><em style="border: 0px; margin: 0px; padding: 0px;"><span style="color: #030404; font-family: calluna, 'Trebuchet MS', Tahoma, Verdana, sans-serif; font-size: 17px; letter-spacing: 0.5039999485015869px; line-height: 26.875px;">2 Corinthians 10:3–5</span></em>&nbsp;</blockquote><blockquote class="tr_bq"><em style="border: 0px; margin: 0px; padding: 0px;">For though we walk in the flesh, we do not war according to the flesh. For the weapons of our warfare are not carnal but mighty in God for pulling down strongholds, casting down arguments and every high thing that exalts itself against the knowledge of God, bringing every thought into captivity to the obedience of Christ.</em><cite style="border: 0px; color: #77533b; display: block; font-family: calluna, 'Trebuchet MS', Tahoma, Verdana, sans-serif; font-size: 18px; font-style: normal; letter-spacing: 0.5039999485015869px; line-height: 26.875px; margin: 0px 0px 20px; padding: 0px; text-align: center; text-transform: uppercase; width: 2341.796875px;"><a class="lbsBibleRef" data-reference="2 Corinthians 10.3–5" data-version="nkjv" href="http://biblia.com/bible/nkjv/2%20Corinthians%2010.3%E2%80%935" style="border: 0px; color: #996b4c; margin: 0px; padding: 0px; text-decoration: none;" target="_blank">2 CORINTHIANS 10:3–5</a></cite><span style="color: #030404; font-family: calluna, 'Trebuchet MS', Tahoma, Verdana, sans-serif; font-size: 17px; letter-spacing: 0.5039999485015869px; line-height: 26.875px;">- See more at: http://gatewaydevotions.com/it-is-written/day-20#sthash.Q7Ifrj4u.dpuf</span></blockquote><br /><br /><h4>HEAR</h4>In the devotional today The author tells this story:<br /><blockquote class="tr_bq"><span style="color: #030404; font-family: calluna, 'Trebuchet MS', Tahoma, Verdana, sans-serif; letter-spacing: 0.5039999485015869px; line-height: 26.875px;">...I was at the church teaching a Bible class and one of those wild, Texas storms came blowing in from the west. My wife was at home with our children and the storm sirens began to go off, signaling there was a tornado nearby. She turned on The Weather Channel and the radar map showed the tornados were in our neighborhood. So she grabbed the kids and went into the safest room in the house. They were huddled in there for about 15 minutes and my son, Seth, was tired of cowering under the tornado. He stood up, lifted his finger and said, “God, I command You, in Jesus’ name, to move that tornado! - See more at: http://gatewaydevotions.com/it-is-written/day-20#sthash.Q7Ifrj4u.dpuf</span></blockquote>He starts to say that the kid needed to know who the boss was but God probably likes his spunk anyway... I was thinking about that. I was thinking about Jesus. He talked to storms. He said we'd do greater things. I KNOW Kenneth Copeland has talked to storms they've obeyed him. My own son has talked to storms and they obeyed him.<br /><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/gnt/john/14-12.html" target="_blank">John 14:12</a><br /><span class="versenum" style="background-color: white; color: #333333; font-family: arial; font-size: 14px; font-weight: bold; line-height: 20px; margin: 0px 3px 0px 0px; padding: 0px;">12</span><span style="background-color: white; color: #333333; font-family: arial; font-size: 14px; line-height: 20px;">&nbsp;I am telling you the truth: those who believe in me will do what I do - yes, they will do even greater things, because I am going to the Father.</span></blockquote>So here's my thought for today. I know, beyond any doubt, that I have authority over tornadoes and storms. But where I've struggled is the intangible things. I need to take authority over my life, job, career, sickness, finances, etc...<br /><br />I'm going to live free of worry about money, just like Jesus did (with his 12 full time staff, 120 part time staff, and full time treasurer/CPA!) Accept I'll get a CPA who doesn't betray me. I hope.<br /><div><br /></div><br /><h4>DO</h4>Start to ask myself... &nbsp;instead of just speaking (complaining) about things, what things could I be speaking to?<br /><br /><br />DW<br /><br /><br /><br /><br /><br />