---
title: 'It Is Written - 21 Day Gateway Church Devotional Challenge Day 9'
date: '2014-01-09T13:42:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4810284520309938559'
blogger_filename: '/2014/01/it-is-written-21-day-gateway-church.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Daily Reading'
---

<h4 style="text-align: center;"><a href="http://gatewaydevotions.com/it-is-written/day-9" target="_blank">It Is Written - 21 Day Gateway Church Devotional Challenge Day 9</a></h4><br />I've decided that if you miss days you just miss them. Keep your mind in the now and not the past. If you want to go back and re-read missed devotional days that's ok. But do NOT allow this feeling of being "behind" and needing to "catch up". You don't catch up in life. You either walk closer to or further from the plan of God. There is no catch up. That's an illusion. Just start where you are and walk.<br /><br /><br /><h4>COME:</h4><blockquote class="tr_bq"><a href="http://www.biblestudytools.com/job/32-8.html" target="_blank">Job 32:8</a>8 But it is the spirit in a man, the breath of the Almighty, that gives him understanding.<br /><br />Job 12:13<br />13 "To God belong wisdom and power; counsel and understanding are his.<br /><br />Psalm 119:34<br />34 Give me understanding, and I will keep your law and obey it with all my heart.<br /><br />Luke 24:45<br />45 Then he opened their minds so they could understand the Scriptures.<br /><br />James 1:5<br />If any of you lacks wisdom, he should ask God, who gives generously to all without finding fault, and it will be given to him.</blockquote><blockquote class="tr_bq">Devotional Excerpt: ...<span style="color: #030404; font-family: calluna, 'Trebuchet MS', Tahoma, Verdana, sans-serif; font-size: 17px; letter-spacing: 0.5039999485015869px; line-height: 26.875px;">Stress came into her life, she panicked when she couldn’t breathe, became fearful and didn’t understand what was happening. That happens to a lot of believers who don’t read the Word of God. - See more at: http://gatewaydevotions.com/it-is-written/day-9#sthash.pdv35txk.dpuf</span>&nbsp;</blockquote><br /><h4>HEAR:</h4>When I'm feeling stressed I need to turn to God's Word and Prayer. Find that place of peace and then from that place of peace and rest I can hear Him more clearly. Kenneth Copeland talked about situation where he felt tremendous pressure, like when his aunt was dying and he wanted to rush to the hospital and panic like the rest of his family. But he chose instead to go into "LOW SLOW".<br /><br />He purposefully slowed down, ate his eggs, got dressed slowly. Forcing his body to slow forced his mind to slow which allowed him to bring/keep his spirit into the top place in that situation. He was able to pray calmly on the way to the hospital. When he got there she'd died. But he calmly walked over to her and said in a quite restful tone of voice: "In the name of Jesus, you wake up now." and she did. "Oh hi Kenneth. When did you get here?"<br /><br />That's the kinds of LOW SLOW we all need at all times, but especially during a crisis or pressure situation.<br /><h4>DO:</h4>Instead of freaking out and rushing I'm going to go into low slow. DW<br /><br /><br /><br /><br />