---
title: 'White Noise Notes | 09/16/14'
date: '2014-09-16T14:48:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '9085961425609741335'
blogger_filename: '/2014/09/white-noise-notes-091614.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Writing Practice'
  - 'White Noise'
---

White Noise Notes:<br><br>Science experiments need replication and controls. They would both be in the same process. White room first, then dark room. <br><br>Possibly they don't remember being in the room? They have flash backs to it later?<br><br>Or they do go through the room, with some results, but then experience results after they leave?<br><br>They are both found on the beach/island after X hours? (48 hours?) The subdermal beacons went dark for that long, then reappear next to each other on a different island than the one's they were dropped off on, both were on different islands, found on the same third island. <br><br>They return to normal life, in different states, but end up needing to talk to each other about the experiences they are having. <br><br>They end up on a wild adventure to find the one who did this to them. They are being followed by someone, but never quite see them. They are seeing things that "aren't there" so they attribute the people following them to this new phenomenon. <br><br>The end? Unkown... ties to&nbsp;a new story? Most likely... <br><br>Gypsies<br>Cowboys<br>LA Thugs/Mexican Gangs<br>A retired pastor, a pastor of a large church, a priest????&nbsp;Maybe not a pastor, maybe a spiritual mentor that doesn't work at a church.... hmm....<br><br>Book: White Noise<br>Series: Phenomenon?<br><br><a href="http://en.wikipedia.org/wiki/Phenomenon" target="_blank">Phenomenon: </a><br><br>A <b>phenomenon</b> (<a href="http://en.wikipedia.org/wiki/Greek_language" title="Greek language">Greek</a>: φαινόμενoν, <i>phainomenon</i>, from the verb φαίνειν, <i>phainein</i>, "to show, shine, appear, to be manifest (or manifest itself)"),<sup class="reference" id="cite_ref-Dictionary_1-0" jquery111105312826050717606="77"><a href="http://en.wikipedia.org/wiki/Phenomenon#cite_note-Dictionary-1"><span>[</span>1<span>]</span></a></sup> plural <b>phenomena</b>, is any <a href="http://en.wikipedia.org/wiki/Observation" title="Observation">observable</a> <a class="mw-redirect" href="http://en.wikipedia.org/wiki/Occurrence" title="Occurrence">occurrence</a>.<sup class="reference" id="cite_ref-2" jquery111105312826050717606="80"><a href="http://en.wikipedia.org/wiki/Phenomenon#cite_note-2"><span>[</span>2<span>]</span></a></sup> Phenomena are often, but not always, understood as 'appearances' or '<a href="http://en.wikipedia.org/wiki/Experience" title="Experience">experiences</a>'. These are themselves sometimes understood as involving <a href="http://en.wikipedia.org/wiki/Qualia" title="Qualia">qualia</a>.<br>The term came into its modern philosophical usage through <a href="http://en.wikipedia.org/wiki/Immanuel_Kant" title="Immanuel Kant">Immanuel Kant</a>, who contrasted it with the <a href="http://en.wikipedia.org/wiki/Noumenon" title="Noumenon">noumenon</a>. In contrast to a phenomenon, a noumenon is not directly accessible to observation. Kant was heavily influenced by <a class="mw-redirect" href="http://en.wikipedia.org/wiki/Gottfried_Leibniz" title="Gottfried Leibniz">Leibniz</a> in this part of his philosophy, in which phenomenon and noumenon serve as interrelated technical terms.<br><br><div><br></div><div>The noumenon /ˈnɒuːmɨnɒn/ is a posited object or event that is known (if at all) without the use of the senses.[1] The term is generally used in contrast with, or in relation to "phenomenon", which refers to anything that appears to, or is an object of, the senses. In Platonic philosophy, the noumenal realm was equated with the world of ideas known to the philosophical mind, in contrast to the phenomenal realm, which was equated with the world of sensory reality, known to the uneducated mind.[2] Much of modern philosophy has generally been skeptical of the possibility of knowledge independent of the senses, and Immanuel Kant gave this point of view its classical version, saying that the noumenal world may exist, but it is completely unknowable to humans. In Kantian philosophy the unknowable noumenon is often linked to the unknowable "thing-in-itself" (Ding an sich, which could also be rendered as "thing-as-such" or "thing per se"), although how to characterize the nature of the relationship is a question yet open to some controversy.<br><br><br>Darrell Wolfe