---
title: 'Conflict and Plot'
date: '2014-03-18T02:18:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1632958473789203266'
blogger_filename: '/2014/03/conflict-and-plot_17.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Other Blogs and Authors'
---

<h3 style="text-align: center;"><br />Conflict and Plot</h3><br /><br /><br /><a href="http://thewritepractice.com/3d-conflict/?utm_source=feedburner&amp;utm_medium=feed&amp;utm_campaign=Feed%3A+TheWritePractice+%28The+Write+Practice%29" target="_blank">How to Develop Your Plot With Three-Dimensional Conflict</a>&nbsp;<em style="border: 0px; color: #a8a8a8; font-family: Merriweather; font-size: 14px; line-height: 24px; margin: 0px; outline: 0px; padding: 0px; text-align: center; vertical-align: baseline;">by</em><span style="color: #a8a8a8; font-family: Merriweather; font-size: 14px; line-height: 24px; text-align: center;">&nbsp;</span><a href="http://www.creativejuicer.wordpress.com/" rel="author external" style="color: #a8a8a8; font-family: Merriweather; font-size: 14px; line-height: 24px; margin: 0px; padding: 0px; text-align: center; text-decoration: none; vertical-align: baseline;" title="Visit Emily Wenstrom’s website">Emily Wenstrom</a><br /><br /><br /><br />Is an interesting article. She talks about the need for three dimensions of conflict in order to develop plot.<br /><br /><br /><br />1. External-world conflict<br /><br /><br />2. External-personal conflict<br /><br /><br />3. Internal conflict<br /><br /><br /><br /><br />It was a quick read, but very informative for me as a writer.<br /><br /><br /><br />You need all three to have a story deep enough to be interesting. To read more<a href="http://thewritepractice.com/3d-conflict/?utm_source=feedburner&amp;utm_medium=feed&amp;utm_campaign=Feed%3A+TheWritePractice+%28The+Write+Practice%29" target="_blank"> click here</a><br /><br /><br /><br /><br /><br /><br /><br />******<br /><br /><br /><br />Thank you for reading. I hope you enjoyed this. I'd love to make a community with this project. If you would like to add, comment on, critique, or otherwise participate... that would be great!<br /><br /><br /><br />Please include any information about yourself, your blog/wesbite/amazon author page that you want to share with the community also.<br /><br /><br /><br /><i>* I may include "Affiliate Links" which means I earn a commission when you buy products I link to. To see my full about page and disclosures:&nbsp;<a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a></i><br /><br /><br /><br /><a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br /><br /><br /><br />To Subscribe to the&nbsp;<a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br /><br /><br /><br />For Non-Fiction writing by&nbsp;<a href="http://www.darrellwolfe.com/" target="_blank">Darrell G. Wolfe: Click Here</a><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><div style="clear: both; float: left; padding-bottom: 10px; text-align: right;"><br /><br /></div><br />