---
title: 'Dark Room - Ashlund'
date: '2014-10-18T17:55:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '9000020115683760591'
blogger_filename: '/2014/10/dark-room-ashlund.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
---

<br /><br /><h3 style="text-align: center;">10/18/14 | Writing Practice</h3><br /><br />Once seated the light was immediately absent. Completely absent. The only thing Ash could see was the flashes of white dots dancing around his eyes from having been in the light moments earlier. What utter and stark contrast to the room he was in. The sound... or lack of sound... in this room was astonishing. It was though sound itself was being sucked out. He could hear nothing but a ringing for the first few minutes. After a while, the ringing subsided and he could hear the beating of his own heart, and the sloshing of bodily fluids throughout his own body.<br /><br />Eventually, after what felt like an hour, but it was probably only minutes, he found that even these sounds faded into the background of his attention. He could almost hear his own thoughts. As though that voice in his head, that was always present, telling him what to do, and where to go, and how to act, watch out for that... don't say that... oh man, why did you do that for? It was as though the inner voice became almost audible. As&nbsp; though he could hear himself think. Or rather as though his thoughts could speak to him audibly. It was an odd sensation, but occupying his mind was the only thing he could do. He'd never admit it to a captor, but solitary confinement was his favorite part of being a prisoner of war. He enjoyed self time, and silence. Accusation follows on the heals of this. Anytime he's alone, it starts. What you should have done differently.<br /><br />His concentration snapped into focus suddenly with the feeling that he was not alone in this room. He'd known before he entered the room that camera, most likely equipped with monitoring capabilities were on him, and he was being observed... but that wasn't it. He felt the air in the room change, as though someone had entered the room with him. He could hear breathing in the room. He wasn't tied to the chair, he could get up, but where to? He couldn't see, he'd memorized the layout though. He knew the entrance he came from, and he didn't see any other known entry ways. Ash slowed his breathing, and observed with his four remaining senses for any clue as to the whereabouts and intention of the new participant. <br /><br />***************************<br /><br />Dr... It's beginning... the biometrics just spiked. The presence is there...<br /><br />Good, good... let's see how he does. The previous test subjects had no where near the discipline that Mr. Ashlund does. This should be an interesting observation. <br /><br />***************************<br /><br />Thank  you for reading. I hope you enjoyed this. I'd love to make a community  with this project. If you would like to add, comment on, critique, or  otherwise participate... that would be great!<br /><br />Please  include any information about yourself, your blog/wesbite/amazon author  page that you want to share with the community also.<br /><br /><i>*  I may include "Affiliate Links" which means I earn a commission when  you buy products I link to. To see my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a></i><br /><br /><a href="http://authorfun.blogspot.com/" target="_blank">It's Author Fun</a>&nbsp;By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" target="_blank">Darrell Wolfe</a><br /><br />To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a><br /><br />For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell G. Wolfe: Click Here</a><br /><br /><br /><br /><br /><br /><div style="clear: both; float: left; padding-bottom: 10px; text-align: right;"><br /><br /></div>