---
title: 'Dark Elf | Out of the Shadows'
date: '2015-06-23T04:25:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6775967410953755595'
blogger_filename: '/2015/06/dark-elf-out-of-shadows.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
---

<div style="border-width: 100%; direction: ltr;"> <div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.4513in;"> <div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.4513in;"> <div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; margin: 0in;"><span style="font-size: 11.0pt;">As the tablet's glow grew to life, an image appeared. On the image of a full moon, two torches crossed paths at the top, over the scales of justice below. The torches were made of gold, but held black and white flames. Upon the gold scales sat two weights named </span><span style="background: white; color: #252525; font-size: 10.5pt;">Adrasteia and </span><span style="color: #252525; font-size: 10.5pt;">Hekate</span><span style="font-size: 11.0pt;">&nbsp;. </span></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">Dark Elf entered his password, and the screens around the room booted to life. As he checked his monitors he was able to observe 1000's of cameras from around the world, but front and center were his prime monitors. From here he could see his entire operation. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">Anonymous served it's purpose, now it was time to come out of the shadows. It was amazing how much could be accomplished through some keystrokes and well placed religious bull. Dark Elf roamed the dark net, smirking periodically at Hacker Aliases like "HellRazzer567". Really? That's the best you could come up with. Children. It was time to establish his own ID. Something to set him apart from his Anonymous friends. Dark Elf would do nicely. It was simple enough to remember, innocuous enough to be tracked to 100's of other individuals. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">So far the instructions of his masters had paid dividends many times over. He was rich, powerful, and operated from the shadows. Just levitate a few chairs and the powerless will flock to you as though you had all the answers. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">The Islamist Extremists were so easy to manipulate too. It was astonishing how easy it was to get some bearded scarf wearer to bomb a building by hacking their website and posting the challenge. These people were not any smarter than these looser addicts that were constantly doing his bidding at his hotel. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">The great Dr. Briar was becoming a nuisance, but he was assured that he still served a purpose. He had a few ideas about what to do when that purpose was complete. Hiring a man to play the part of wealthy contributor? 100,000 dollars. The look on his face when he got the texts? Priceless. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">What a moron.</div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">Meanwhile, it was nice to be king. Lord rather. Lord Dark Elf. It had a nice ring to it, eh? </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div></div></div></div>