---
title: 'The Heart of a Story: Fiction Themes'
date: '2015-07-26T04:50:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'DRAFT'
blogger_post_id: '9062382833825936100'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

So I just watched <a href="http://www.imdb.com/title/tt1121096/" target="_blank">Seventh Son</a>, an alright movie, not great. But it got me thinking about story telling. What makes Lord of the Rings different from Seventh Son? It's not just the length or complexity of the story. It's deeper...<br /><br /><br /><br />It's the theme.<br /><br /><br /><br />Good isn't good; bad isn't bad. Their both just misunderstood. It comes from an anti-theistic anti-biblical world view. The half withes get together to accomplish what man and witch on their own could not. The great deception coming upon these end times is that witches can be good.<br /><br /><br /><br />Many of my high school and college friends went on to become Wiccans. They live under the false impression that you can be a "good" <a href="https://en.wikipedia.org/wiki/Wicca" target="_blank">Wiccan</a>. The thing is... in way you can. You can be "good" under the worlds definition... but you cannot be full of LIFE on that path.<br /><br /><br /><br />There are no neutral sources in this world... sources can be from the<br /><br /><br /><br /><br /><br /><ul><br /><li>Tree of LIFE</li><br /><li>Tree of the knowledge of Good and Evil.&nbsp;</li><br /></ul><br /><br /><br /><br /><br />Wicca, and other flavors of witchcraft, have one thing in common: Seeking Knowledge.<br /><br /><br /><br />Interestingly,<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />