---
title: 'Boston Bombing Vision | Eta'
date: '2015-01-14T06:09:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7888506752458016352'
blogger_filename: '/2015/01/boston-bombing-vision-eta_13.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
---

<br /><br /><br /><br /><div style="border-width: 100%; direction: ltr;"><br /><br /><div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.2388in;"><br /><br /><div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.2388in;"><br /><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />Over at the café',<br />Janice is still chattering away about the latest episode of Blacklist, which<br />Eta is normally very into. Today she just feels less normal. That dream, it had<br />gone away since she'd been doing her herbal teas, but now it was back. Was this<br />a relapse? </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />Suddenly, in her<br />mind's eye, <span style="font-style: italic;">she saw a waiter walk by and trip<br />on her purse, dropping the bottle of Perrier he was carrying. </span></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />She turned to Janice<br />who had stopped talking, and was now staring at Eta. " You feeling' ok<br />hun? "</div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />"I'm fine<br />Janice, I'm sorry… these darn headaches, what were you saying? " Eta<br />denied it. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />"You need<br />something? I always carry the standards, generic of course… same thing, less<br />money…" </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />"Janice, it's<br />nothing really." Just then a waiter walked by with a bottle of Perrier. He<br />tripped on her purse, and she reached out and caught the bottle before it hit<br />the ground. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />"You have<br />amazing reflexes! Thank you!" the waiter stated, and he moved on looking<br />embarrassed. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />"Wow girl<br />!" Janice exclaimed. "You really are good! " Janice went back to<br />recanting the television show. Eta tried to appear interested, she actually<br />really enjoyed the show. But these episodes were getting out of control. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />Then, Janice<br />disappeared. She was somewhere else, far away. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><span style="font-style: italic;">City street. cars driving by. People walking along,<br />minding their own business, most looking down at their smart phones as if they<br />were walking by GPS. Now there's people running, the streets of roped off, and<br />she can see people in jogging suits, numbers on their back. Then her attention<br />is drawn to a young man placing a backback in the trash can. She knows this<br />place, but she's never been here. A blinding flash of light. Glass splattering<br />all over her. The percussion hits her chest and…</span></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />it's over... It's<br />the same one she's been having for weeks now. There are the little things that<br />she seems to see before they happen. Like the waiter. Coincidence. Maybe. But<br />then there's this dream, what could it mean? She must not have been staring blankly<br />for too long, because her friend didn't notice at all this time. These waking<br />dreams are getting more and more vivid. More details. It's strange how eerie<br />they are. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />"Oh my!"<br />she hears from just behind her, she turns to see the whole restaurant slowly<br />turning to see the television. Stunned silence. Another terrorist attack. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />"An explosion<br />just went off at the Boston Marathon just moments ago…" the reporter<br />covering the information they had so far. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />…wait, did they say<br />Boston? A sick feeling comes over her... is that even possible? Then it<br />happens. She sees the young man, from her dream, running away from the scene in<br />the news with all the other people. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />Her friend notices<br />that she's gone pale, she asks the bartender for water. They start to fan her.<br />Eta folds her head into her hands at stares at the T.V. in total shock.<br />"What is happening?" They all assume she's talking about the recent<br />rise in terrorist attacks… if they only knew. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />"Excuse me,<br />Janice, I have to make a call. I have friends in that area. I'll see you later<br />ok?" Eta does not wait for an answer, she walks to a nearby payphone,<br />which are getting harder to come by these days, keeping her face from a clear<br />line of sight to any cameras she sees. She calls the F.B.I. hotline with an<br />anonymous tip regarding the bomber, and the news channel that had the photo.<br />Then she heads home… to process. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />***</div><br /></div><br /></div><br /></div><br />