---
title: '01/11/15 @GatewayPeopleNFW'
date: '2015-01-17T22:51:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3323013735663500835'
blogger_filename: '/2015/01/011115-gatewaypeoplenfw.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<span xmlns=''><p><span style='color:black'><strong>Mathew</strong> 7:1-2<br /></span></p><p><span style='color:black'><strong>Luke</strong> 6:37-38<br /></span></p><p><span style='color:black'>Judge not and pick your measure...<br /></span></p><p> <br /> </p><p><span style='color:black'>Give, and it will be given is not just about money. Being a giver is all about the heart. Being a giver involves time, talent, treasure, inconveniencing yourself for others....<br /></span></p><p> <br /> </p><p> <br /> </p><p><span style='color:black'>Judgment, Condemnation, Forgiveness... You give judgment and you reap judgment. You give forgiveness and forgiveness will be reaped. <br /></span></p><p> <br /> </p><p> <br /> </p><p><span style='color:black'><strong>Deut</strong> 15:7-8<br /></span></p><p><span style='color:black'>God gave the land, therefore, give to your brother. Don't close your hand because he can't pay you back. Lend to the poor, GOD pays you back.<br /></span></p><p> <br /> </p><p><span style='color:black'>You should give without being greived about it. You can only grieve over giving when you thought it was yours.<br /></span></p><p> <br /> </p><p><span style='color:black'>Why did God create-invent giving? Do you really think that God needs your money to support His work??? <br /></span></p><p> <br /> </p><p><span style='color:black'>God, So over that He gave!<br /></span></p><p> <br /> </p><ol><li><div><span style='color:black'>Deal with a selfish heart.<br /></span></div><ol><li><span style='color:black'>&lt;before we give&gt;<br /></span></li></ol></li><li><div><span style='color:black'>Deal with a grieving heart.<br /></span></div><ol><li><span style='color:black'>&lt;after we give&gt;<br /></span></li></ol></li><li><div><span style='color:black'>Develop a generous heart. <br /></span></div><ol style='margin-left: 54pt'><li><span style='color:black'>&lt;you were born again generous&gt;<br /></span></li></ol></li><li><div><span style='color:black'>Develop a grateful heart.<br /></span></div><ol><li><span style='color:black'>&lt;remember what you have been given, this will allow you to be grateful&gt;<br /></span></li></ol></li></ol><p> <br /> </p><p> <br /> </p><p> <br /> </p><p><span style='color:black'>What causes extravagant generosity? Never forget that your saved!<br /></span></p><p> <br /> </p><p><span style='color:black'>What are you saying to me?<br /></span></p><p> <br /> </p><p><span style='color:black'>About heart not behavior. <br /></span></p><p> <br /> </p><p> <br /> </p><p style='margin-left: 27pt'> <br /> </p><p> <br /> </p><p> <br /> </p><p> <br /> </p><p> <br /> </p><p> <br /> </p><p> <br /> </p><p> <br /> </p><p> <br /> </p><p> <br /> </p><p> <br /> </p><p> <br /> </p><p> <br /> </p><p> <br /> </p><p> <br /> </p><p> <br /> </p><p> <br /> </p><p> <br /> </p><p><span style='color:black'>...<br /></span></p></span>