---
title: 'Dark Elf | Out of the Shadows'
date: '2015-06-23T04:25:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3006725142658502884'
blogger_filename: '/2015/06/dark-elf-out-of-shadows_22.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
---

<div style="border-width: 100%; direction: ltr;"><br /><br /><div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.4513in;"><br /><br /><div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 6.4513in;"><br /><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; margin: 0in;"><br /><span style="font-size: 11.0pt;">As the<br />tablet's glow grew to life, an image appeared. On the image of a full moon, two<br />torches crossed paths at the top, over the scales of justice below. The torches<br />were made of gold, but held black and white flames. Upon the gold scales sat<br />two weights named </span><span style="background: white; color: #252525; font-size: 10.5pt;">Adrasteia and </span><span style="color: #252525; font-size: 10.5pt;">Hekate</span><span style="font-size: 11.0pt;">&nbsp;. </span></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />Dark Elf entered his<br />password, and the screens around the room booted to life. As he checked his<br />monitors he was able to observe 1000's of cameras from around the world, but<br />front and center were his prime monitors. From here he could see his entire<br />operation. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />Anonymous served<br />it's purpose, now it was time to come out of the shadows. It was amazing how<br />much could be accomplished through some keystrokes and well placed religious<br />bull. Dark Elf roamed the dark net, smirking periodically at Hacker Aliases<br />like "HellRazzer567". Really? That's the best you could come up with.<br />Children. It was time to establish his own ID. Something to set him apart from<br />his Anonymous friends. Dark Elf would do nicely. It was simple enough to<br />remember, innocuous enough to be tracked to 100's of other individuals. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />So far the<br />instructions of his masters had paid dividends many times over. He was rich,<br />powerful, and operated from the shadows. Just levitate a few chairs and the<br />powerless will flock to you as though you had all the answers. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />The Islamist<br />Extremists were so easy to manipulate too. It was astonishing how easy it was<br />to get some bearded scarf wearer to bomb a building by hacking their website<br />and posting the challenge. These people were not any smarter than these looser<br />addicts that were constantly doing his bidding at his hotel. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />The great Dr. Briar<br />was becoming a nuisance, but he was assured that he still served a purpose. He<br />had a few ideas about what to do when that purpose was complete. Hiring a man<br />to play the part of wealthy contributor? 100,000 dollars. The look on his face<br />when he got the texts? Priceless. </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />What a moron.</div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br />Meanwhile, it was<br />nice to be king. Lord rather. Lord Dark Elf. It had a nice ring to it, eh? </div><br /><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /><br /></div><br /></div><br /></div><br /></div><br />