---
title: 'Boston Bombing Vision | Eta'
date: '2015-01-14T06:09:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2502620978049387333'
blogger_filename: '/2015/01/boston-bombing-vision-eta.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
---

  <br /><div style="border-width: 100%; direction: ltr;"> <div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.2388in;"> <div style="direction: ltr; margin-left: 0in; margin-top: 0in; width: 7.2388in;"> <div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">Over at the café', Janice is still chattering away about the latest episode of Blacklist, which Eta is normally very into. Today she just feels less normal. That dream, it had gone away since she'd been doing her herbal teas, but now it was back. Was this a relapse? </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">Suddenly, in her mind's eye, <span style="font-style: italic;">she saw a waiter walk by and trip on her purse, dropping the bottle of Perrier he was carrying. </span></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">She turned to Janice who had stopped talking, and was now staring at Eta. " You feeling' ok hun? "</div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">"I'm fine Janice, I'm sorry… these darn headaches, what were you saying? " Eta denied it. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">"You need something? I always carry the standards, generic of course… same thing, less money…" </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">"Janice, it's nothing really." Just then a waiter walked by with a bottle of Perrier. He tripped on her purse, and she reached out and caught the bottle before it hit the ground. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">"You have amazing reflexes! Thank you!" the waiter stated, and he moved on looking embarrassed. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">"Wow girl !" Janice exclaimed. "You really are good! " Janice went back to recanting the television show. Eta tried to appear interested, she actually really enjoyed the show. But these episodes were getting out of control. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">Then, Janice disappeared. She was somewhere else, far away. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><span style="font-style: italic;">City street. cars driving by. People walking along, minding their own business, most looking down at their smart phones as if they were walking by GPS. Now there's people running, the streets of roped off, and she can see people in jogging suits, numbers on their back. Then her attention is drawn to a young man placing a backback in the trash can. She knows this place, but she's never been here. A blinding flash of light. Glass splattering all over her. The percussion hits her chest and…</span></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">it's over... It's the same one she's been having for weeks now. There are the little things that she seems to see before they happen. Like the waiter. Coincidence. Maybe. But then there's this dream, what could it mean? She must not have been staring blankly for too long, because her friend didn't notice at all this time. These waking dreams are getting more and more vivid. More details. It's strange how eerie they are. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">"Oh my!" she hears from just behind her, she turns to see the whole restaurant slowly turning to see the television. Stunned silence. Another terrorist attack. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">"An explosion just went off at the Boston Marathon just moments ago…" the reporter covering the information they had so far. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">…wait, did they say Boston? A sick feeling comes over her... is that even possible? Then it happens. She sees the young man, from her dream, running away from the scene in the news with all the other people. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">Her friend notices that she's gone pale, she asks the bartender for water. They start to fan her. Eta folds her head into her hands at stares at the T.V. in total shock. "What is happening?" They all assume she's talking about the recent rise in terrorist attacks… if they only knew. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">"Excuse me, Janice, I have to make a call. I have friends in that area. I'll see you later ok?" Eta does not wait for an answer, she walks to a nearby payphone, which are getting harder to come by these days, keeping her face from a clear line of sight to any cameras she sees. She calls the F.B.I. hotline with an anonymous tip regarding the bomber, and the news channel that had the photo. Then she heads home… to process. </div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;"><br /></div><div style="font-family: Calibri; font-size: 11.0pt; margin: 0in;">***</div></div></div></div>