---
title: 'Expectation leads to premeditated disappointment'
date: '2016-04-10T20:01:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3466723761721326594'
blogger_filename: '/2016/04/expectation-leads-to-premeditated.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Renewing the Mind (Stinking Thinking)'
  - 'Resting'
  - 'Recovery'
  - 'In The Mire'
---

<br /><br /><h3>"Expectation leads to premeditated disappointment". That's a phrase my dad enjoys using.&nbsp;</h3><div><br /></div><div>I recently wrote (<a href="http://www.darrellwolfe.com/2016/04/observation-expectations-and.html">here</a>) about reading The Shack, by Paul Young.<div><br />A fiction novel, it deals with real and tough emotional responses to God, and it was the most profound book I've read in years. I was subtly, but throughly effected.<br /><br />I'm learning now to "let go, and let God" in an entirely new way. It's not about not caring, in fact, my caring increased. It's about relaxing into his arms. Trusting him in new ways. Gaining new perspectives.<br /><br />I've always treated life as though it were a race from one destination to the next. "What do you want from me?" was my common question to God.<br /><br />It turns out, he doesn't. He's not asking anything of me, not really. He has desires for me. Plans. He would like to work with me and through me to accomplish great things. But....<br /><br />It's not as though there's a checklist that I'm getting further and further behind on as I fail to follow. Rather; every day He presents opportunities. Some big (take that job), some small, (spend five minutes with me this morning before you go).<br /><br />Quiet time is for me, not Him. He wants me to work in and through him ALL DAY, praying constantly (even if only in my mind). Morning quiet time is for me to have a chance to settle down, relax in him, and not get too worked up into the day. It sets the tone of the day, and keeps me from getting back to my check list mentality.<br /><br />I can take it, leave it, do 3 minutes, 30, 60, 90 minutes... all the same to Him. It's about relating to him, not about checking off my list.<br /><br />I can "pray" while taking a shower, cooking, driving, at work, even while talking to someone else (preferably then, so I don't say the wrong things). So quiet time is not about "getting my prayer time in".<br /><br />It's just about, relaxes and retuning. It's like taking a few moments to tune the radio dial before starting my "drive" into the day.<br /><br />That's a whole new concept.<br /><br />Darrell<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /></div></div>