---
title: 'The Creative Way; creating fiction that readers crave.'
date: '2016-09-12T06:13:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3744265069431248800'
blogger_filename: '/2016/09/the-creative-way-creating-fiction-that_11.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Writing Practice'
  - 'Craft'
---

<br /><br />Ted Dekker (my favorite author) created a writing course called&nbsp;<a href="https://thecreativeway.com/launch-page-1-8506883yp7afn2d" target="_blank">The Creaive Way</a>; which is an online course sounds like an awesome investment, but I don't have that money, not even by a long shot. However, in his free introductory videos he gave the keys (combined with what I've already learned) that I think I need for now.<br /><br /><br /><br />What is story? <b>Story is a series of events involving <u>worthy characters</u> who <i>change </i>(are transformed) as a result of those events.</b><br /><br /><br /><br /><b>Without transformation you don't have a story, you just have a series of events.&nbsp;</b><br /><br /><br /><br />Use the writing process to explore a fundamental question, and facilitate transformation in your own life. That transformation will bleed onto the page, and your reader will be transformed too.<br /><br /><br /><br />If you as a writer are not changing as a result of your characters' journey, you didn't write a story worth reading.<br /><br /><br /><br />The Fictive Bubble holds your story. Take your reader into the bubble, keep them in the bubble the whole time.<br /><br /><br /><br />While in the bubble, your character will take a journey from where is today (on a hill) to where he wants to be (the hill on the other side) and he needs a path through the foggy valley between.<br /><br /><br /><br />That path must be clear to you, you are your character's muse or guide. <b>He will hit seven way points.&nbsp;</b><br /><br /><b><br /></b><br /><br /><br /><ol><br /><li><b>Backstory</b>.&nbsp;</li><br /><ul><br /><li>In the first few pages, introduce your reader to the protagonist and his/her world.</li><br /></ul><br /><li><b>Inciting Event</b></li><br /><ul><br /><li>The event that forces the protag into the story, with a clear goal.</li><br /><li>There my be a clear, specifc threat.</li><br /></ul><br /><li><b>Series of Challenges and Solutions.</b></li><br /><ul><br /><li>Your protag tries a series of solutions, and fails.&nbsp;</li><br /><li>Things seem to go well, and all hope is lost.</li><br /><li>Something BIG has to happen, or all is lost.</li><br /><li>Subtle changes. Character is wrestling through, lost in the fog.</li><br /></ul><br /><li><b>Dramatic turning point.</b></li><br /><ul><br /><li>A major change in your characters perspective.</li><br /><li>Small changes came before now, but this is a major change for your character. The path is now clear. May come at a cost.</li><br /></ul><br /><li><b>Climax (Goal Reached)</b></li><br /><ul><br /><li>Antagonist overcome, goal reached.</li><br /></ul><br /><li><b>Wrap Up</b></li><br /><ul><br /><li>Resolve/Resoration</li><br /><li>One last scene to show how the character's world turned out.</li><br /></ul><br /><li><b>Celebration</b></li><br /><ul><br /><li>Celbrating his victory. One scne, or less than a full scene.</li><br /><li>Hint at the future?</li><br /></ul><br /></ol><br /><br /><br /><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><br /><div><br /><br /></div><br /></blockquote><br /><h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;"><br />By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4><br /><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><br /><i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote><br /><ul><br /><li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li><br /><li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li><br /><li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li><br /><li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li><br /></ul><br /><ul><br /></ul><br />