---
title: 'So today was nice?'
date: '2016-02-28T09:00:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '295855664975482521'
blogger_filename: '/2016/02/so-today-was-nice.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Resting'
  - 'Recovery'
---

<h3><br />I woke up late with no where to go, and nothing to do. I think some people call that sleeping in on a Saturday.</h3><br />My head didn't hurt as much as it usually does. So that was nice.<br /><br />By about 3pm ish, I actually left the house for a while. Went to Walmart, Sonic, Wendy's and In-n-Out.<br /><br />It was really nice outside. Cool enough not to feel hot, but warm enough for a t-shirt, breeze outside, 70's?<br /><br /><br />I did not feel especially down, or moody.<br /><br /><br />I did the dishes. Several days worth. That took an hour and half. But my wife baked angel food cake, and <a href="http://www.instructables.com/id/macerated-strawberries/">macerated strawberries</a> for strawberry shortcake.  So have two sinks full of dishes again tomorrow, but the desert was lovely.<br /><br />Other than the errand, and doing dishes, we basically watched <a href="https://www.youtube.com/watch?v=24GFQQfZIm4">Gilmore Girl's</a> re-runs all day. I forgot how much I REALLY enjoyed that show. The wry wit, and comic timing are impeccable, it's so hard to find great writing, directing, and acting like that. Punchy.<br /><br /><br /><div style="text-align: center;"><iframe allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/24GFQQfZIm4" width="420"></iframe></div><div style="text-align: center;"><br /></div><br /><br /><b>Yet... I left the day with the usual empty feeling.</b><br /><br /><br /><br />Like there's something I should have been doing (for years now) that would have made me the successful person I think I should be, but I'm too lazy so here I am.<br /><br />I have 148 IQ, which is officially over the line for Genius. I have the typical low EQ to match. I am a text book genius, so gifted I could be anything, so gifted I'm too distracted to do anything, so I'm working for peanuts at for a corporation that pays OK, but still too broke to get fast food without checking the budget first.<br /><br />As usual, I can see every disaster before it hits, but no one that needs to listen to me will, and no one that does listen to me can do anything, and the disaster hits, and I just watch. I could have prevented it, but they wouldn't let me. It's like watching an accident in slow motions months in advance, and then watching again in real time right in front of you. You feel like you could have stopped it, but then you realize you couldn't, because you are invisible.<br /><br />Election season is worse, because I watch mass amounts of people voting for a man like Trump, which anyone with a brain can tell is an empty shell with no brain of his own... yet the uneducated, unthinking masses go for him in droves. What good does it do to be smarter than most humans? So you can see them destroy themselves, and you with them, and unlike them you see it coming? At least they get to enjoy the stupidity for a moment. It's like watching a train coming at you, and being unable to move.<br /><br />I have this constant sinking feeling that if I applied just HALF of my mental capacity I could be independently wealthy by any standard right now. I could be discussing my intellectual property rights, and stock and property portfolios... not worried about whether I should get the $3 cheeseburger, because the one I really want is $5.<br /><br /><br /><b>And yet... even as I sit here...</b><br /><br /><br />I am instantly full of "ideas" about what I could be doing to produce passive income, and lacking any motivation to actually do any of them. So I'm sitting here writing this.<br /><br />At least if I was writing for a Niche Website, or working on my novel I would feel like I could pretend I was working on/towards something. But I'm not. I'm 35.5 years old right now, and my expectation for anything greater than this slips a little further away every year.<br /><br />I had a niche website that was promising, I could have made something with it, and I didn't even write on it more than one day all year in 2015. So I just let the domain name expire. Who cares. What's the point.<br /><br /><br /><br /><b>So here I sit again. It's late.</b><br /><br /><br /><br />I don't want to go to bed, because I'll wake up and it'll be tomorrow, and then it will be another night, and them Monday will come and I'll start all over.<br /><br />I'm on a merry go round that hasn't stopped my entire life, and the music sucks.<br /><br />I think I'll go try out that prayer chair thing again, then go to bed, I guess.<br /><br /><br /><br /><br />Darrell