---
title: 'Freedom from Depression | by Bob Hamp'
date: '2016-12-29T01:13:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '9154749497191233821'
blogger_filename: '/2016/12/freedom-from-depression-by-bob-hamp.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Renewing the Mind (Stinking Thinking)'
  - 'In The Mire'
  - 'Resting'
  - 'Recovery'
  - 'Emotions'
  - 'Freedom/Kairos'
---

<br />Notes from listening to&nbsp;<a href="https://www.youtube.com/watch?v=SFoULjoOP9M&amp;t=53s" target="_blank">Freedom from Depression</a> | by <a href="http://bobhamp.com/media/" target="_blank">Bob Hamp</a>.<br /><br /><h4>1. What is depression?</h4>Depression is a process and not a state of being. You are not on/off with depression. You are either full of life or lacking some life. The more life you lack, the more depression exists.<br /><br /><b>Depression is: Suppression</b><br /><br />The enemy understands you were made in God's image, and He wars to suppress that image in you.<br /><br /><br /><b>Depression is not: Expression</b><br /><br />You were created to express God's image in your geography.<br /><br />You are always moving further toward one or the other.<br /><br />Life is a more or less proposition (not an on/off proposition).<br /><br />Adam plugged into the source of Knowledge instead of the source of Life.<br /><br />God didn't just kick them out of the Garden, He kicked the Garden out of them. They could once see spiritual Truth with their eyes, they could only now see with the eyes of their heart.<br /><br />Knowing you need help.... to the degree that you are lacking life, you need more aliveness.<br /><br />Getting well isn't about your trying harder to believe...<br /><br />Getting into His Presence is reconnecting to the source, so you can fill up with Life.<br /><br />It's not just enough to pull up to the gas pump, read the gas pump, be near the gas pump.. you actually have to connect to the gas pump.<br /><br />Whatever you feed grows...<br /><br /><strong>Sooner or later, you can develop an appetite that is so serious, you can't imagine anything else.</strong><br /><br />Shame is what happens when we're exposed and we run to our knowledge of good and evil, we run and hide.<br /><br />Adam ran and hid not because nakedness was wrong, but because he became aware of himself. He felt the need to hide because he felt shame about being naked before Eve. They felt the need to cover from each other. He didn't want another human to see what he didn't want her to see.<br /><br /><em>*38:00</em><br /><h4>2. Depression is a multi-modal process</h4>All of you is involved in depression, not just spirit or emotion. There are five arenas that we can get involved in our own recovery. Also, it's not about pathology (what's wrong) but about measures of health. <br /><br />Don't think "nothing's wrong with me"; rather, "how could I be more alive tomorrow?"<br /><ol><li><strong>Physical</strong> (body)</li><li><strong>Cognitive</strong> (thoughts)</li><li><strong>Emotional</strong> (feelings are chemical experiences)</li><li><strong>Spiritual</strong> (spirit - core of our identity)</li><li><strong>Social</strong> (connection - we were designed for connection, not designed to be alone. Also, connections affect our mindsets (for good or bad))</li></ol><strong>Isolation</strong>: Often people who start to experience shame (something's wrong with me) begin to isolate. The opposite of isolation doesn't mean that you lay bare in front of everybody. In fact, baring all to everyone can be another way of keeping people at a distance. You have to let someone in, way in.<br /><br />The opposite of Isolation is purposeful choices about intimacy. Who can I share myself with, and what will be mirrored back to me is God's opinion of me.<br /><br />If you feel the need to pull back, and you don't even know why, don't worry about why. You were designed to be connected, just re-engage and you'll discover why.<br /><br />If you use the internet to reach out to someone, that can be a first step. But if you don't continue to form a relationship in person you are still isolated. The internet can serve you as a way to foster connections, but cannot substitute real connections.<br /><br />Those who do the truth come to the light... light exposes and lifts up.<br /><br /><strong>Truth/Uncover</strong>: The solution to bad is not to do better, it's to do Truth/Uncover.<br /><br /><strong>Body</strong>: Your body is amazingly complex. Chemicals, electrical signals, blood, all perfectly balanced. But when it gets out of balance begins to work against itself. Any machine that doesn't get used, or doesn't get used properly, falls apart.<br /><br /><strong>Nutrition</strong>: Comfort food is a biological thing. Some food functions like Xanax. It numbs, and numbs, until you spiral out of weight balance. This causes negative chemical reactions in your emotional and cognitive arenas.<br /><br /><strong>Sleep</strong>: Insomnia (lack of sleep)&nbsp;and Hypersomnia (too much sleep)&nbsp;are both symptoms of depression. <br /><br /><strong>Body Chemistry</strong>: Interplay of chemicals and hormones and electronic signals are required for you to function normally.<br /><br /><strong>Medication</strong>: Medication can temporarily help re-balance the chemicals. This is like a little donut&nbsp;spare tire. Don't expect to drive on the spare tire forever, but use it when you need to. Use medication while you work on other areas to get re-balanced, then change your tire.<br /><br /><strong>Posture</strong>: Depression is linked to hunched/head down posture. It both causes it, and is caused by it. Your blood and electrical signals need to flow to the whole body.<br /><ul><li><strong>Stretch</strong>: Stand up, hands up high into the air, head back staring at the ceiling, stretch your hands high. Hold that posture for a 30 seconds. This will open the neuro-chemical flow and electrical flow of the body. </li><li><strong>Bounce and shake</strong>: Stand up, arms at your side, head up, shoulders back. Bounce, slightly, and shake your hands at your side. This causes the electrical and blood flow to get un-stuck.</li></ul><strong>Relationships</strong>: Poor and Good can cause issues. If your relationship patterns have caused you to shut down, shut out friends, stop your routines; that relationship is negative. If it can be fixed, fix it. If not, you may need to cut it off.<br /><br /><strong>Exercise</strong>: Causes the body to flow and produces positive chemicals.<br /><br /><em>*1:10:00</em><br /><strong>Self-Talk / Agreement / Confession / Hearing</strong>: A dialogue can take place in your head and its completely you, but it could be God or the enemy. If you agree with negative ideas/thoughts, you take them in. Feeding true information does not counter false information. You need to deal with the heart. When you hear the voice of God, your heart is touched, not just your mind. It's not about you doctrinally arguing with yourself, it's about hearing God say it to you. What you say with your mouth isn't necessarily what you believe in your heart. Don't try really heart to change what you believe in your heart; rather, connect with God and hear his voice and that changes your heart. BUT, God won't yell over the noise. You must be still and listen to hear Him.If<br /><br /><strong>Cognitive and Spiritual battle plan: "I'm ignoring this and listening to this..."</strong><br /><br /><strong>Spiritual</strong>: Spiritual forces are empowered in your life through agreement. They will either work to oppose the work of God or offer a counterfeit.<br /><ul><li><strong>Bondage</strong> - looks at our need to be fathered and says "I can do that", but then counterfeits. "This will protect, comfort, nurture you", it says. The opposite of bondage is to know (in your heart) that God is your Daddy.</li><li><strong>Spirit of Perversion (<a href="http://biblehub.com/isaiah/19-14.htm" target="_blank">Isaiah 19:14</a>)</strong>: This is not just sexuality, but also doctrine and truth. This spirit distorts and twists God's truth about you or your reality. "I may say something, but you hear something else," is an example of the Spirit of Perversion. Distortion is caused here. If you find yourself not agreeing with God's Truth, this is a result of the Spirit of Perversion/Distortion.</li><li><strong>Spirit of&nbsp;Heaviness (<a href="http://biblehub.com/isaiah/61-1.htm" target="_blank">Isaiah 61</a>)</strong>: The opposite of the Spirit of Heaviness is Joy. You don't win a battle over darkness by agreeing with it/joining with it. Joy is in you because it's a fruit of the Holy Spirit. If you are born again, it is in you (even if it's hidden away and it's been a long time since you felt it). If you just assume that things will always be bad, hard, awful, you've agreed with the Spirit of Heaviness.</li></ul><br /><br />So, broken or whole, "right or wrong", that's what I'm thinking about today,<br /><br />Darrell W.<br /><br />