---
title: 'Jazmin Doe - Hacker/Orphan'
date: '2016-10-04T02:40:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2795025160471226852'
blogger_filename: '/2016/10/jazmin-doe-hackerorphan.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Character Sketch'
  - 'White Noise'
---

<h3>&nbsp;</h3><h3>Jazmin&nbsp;Doe - Hacker/Orphan</h3><br /><h4>Getting into the background: Jazmin</h4><br /><div class="MsoNormal" style="margin-bottom: 0in;"><span style="font-family: &quot;book antiqua&quot; , serif; font-size: 10pt;">Jazmin&nbsp;Doe was the victim of a botched abortion attempt. The "doctor" delivered her whole, and she was thrown into a dumpster. The cries were heard by a passer-by and reported to the police. She was turned over to an adoption agency. One arm was injured and never grew right.</span><br /><span style="font-family: &quot;book antiqua&quot;; font-size: x-small;"></span><br /><span style="font-family: &quot;book antiqua&quot;; font-size: x-small;">Ms. Wu left her last name as Doe, as she did with all her orphans. She felt it gave them a unity together as a family, and the opportunity to shed the name for one of their own choosing if they wanted as they got older.</span><br /><span style="font-family: &quot;book antiqua&quot;; font-size: x-small;"></span><br /><span style="font-family: &quot;book antiqua&quot;; font-size: x-small;">She a mixed girl, mostly black. At the time of the story she is 16 years old.</span><br /><span style="font-family: &quot;book antiqua&quot;; font-size: x-small;"></span><br /><span style="font-family: &quot;book antiqua&quot;; font-size: x-small;">She is Chester's protégé, a hacker, and a good one. She's not as white hat as Chester though. She makes a living (secretly) doing grey hat, and black hat work.</span><br /><span style="font-family: &quot;book antiqua&quot;; font-size: x-small;"></span><br /><span style="font-family: &quot;book antiqua&quot;; font-size: x-small;">She wants to impress her mentor and make money for herself, not always possible to do at the same time.</span><br /><span style="font-family: &quot;book antiqua&quot;; font-size: x-small;"></span><br /><span style="font-family: &quot;book antiqua&quot;; font-size: x-small;">She thinks she's about to get&nbsp;a pay day and impress her mentor when she goes behind Chester to show him up. Instead it gets her in trouble... and killed?</span></div><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><div><br /></div></blockquote><h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote><ul><li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li><li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li><li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li><li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li></ul><ul></ul>