---
title: 'Faith: You keep using this word. I do not think it means what you think it means...'
date: '2016-06-08T13:13:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4952231251021475048'
blogger_filename: '/2016/06/faith-you-keep-using-this-word-i-do-not_8.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Armchair Theology'
  - 'Spiritual Growth'
---

<br /><h3>Deciding you want something, then hunting for a few bible verses to go with it, is not #Faith. That's wishing hard.&nbsp;</h3><br /><blockquote class="tr_bq"><i>So faith comes from hearing, and hearing through the word of Christ.</i><i><a href="http://biblehub.com/esv/romans/10.htm">English Standard Version</a>&nbsp;|Romans 10:17</i></blockquote><br />Faith doesn't come by reading.<br /><br />Faith comes&nbsp;<b><u>ONLY&nbsp;</u></b>by hearing.<br /><br />Knowing you have a need is not the start.<br /><br />Don't say: "I need money. God I'm believing you for money... and here are three verse to back up my request."<br /><br />That prayer seldom works.<br /><br />Rather: "God I need money. You knew that already. Now. What do you want to talk about today?"<br /><br />Then listen.<br /><br />Even if He doesn't want to talk about your "money problem". Respond to whatever He says.<br /><br />Faith begins where the will of God is known. Faith&nbsp;<b>ONLY</b>&nbsp;operates as a response to a&nbsp;<b>Word you Heard.&nbsp;</b><br /><br />If you didn't hear a word, there is nothing to respond to, Faith doesn't exist yet.<br /><br />#RUListening ?<br /><br /><br /><div><div style="text-align: center;">********</div><br /></div><div>By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts">Darrell Wolfe</a>&nbsp;| #<a href="http://ctt.ec/5xc67">BeStillBeLed</a></div><div><br />Story Teller | Creative |&nbsp;<a href="http://www.16personalities.com/infj-personality">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder">Intellection</a>&nbsp;| Learner | Ideation | Achiever | Input | Multipotentialite<br /><br />New here?<br /><br /><ul><li><a href="http://darrellwolfe.blogspot.com/p/about-20.html" target="_blank">Start Here</a>&nbsp;for more information.</li><li><a href="http://darrellwolfe.blogspot.com/p/q.html" target="_blank">Ask&nbsp;</a>me anything</li><li><a href="http://darrellwolfe.blogspot.com/p/got-freedom.html" target="_blank">Got LIFE? Not sure, click HERE to find out.</a></li><li>See&nbsp;<a href="http://www.darrellwolfe.com/p/by-darrell.html" target="_blank">DarrellWolfe.com</a>&nbsp;for more of my sites.</li></ul><div><br /></div></div><br /><br />