---
title: 'Distortion: Outline'
date: '2016-10-06T00:52:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7574371869157948998'
blogger_filename: '/2016/10/distortion-outline_5.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Writing Practice'
  - 'Outline'
  - 'White Noise'
  - 'Character Sketch'
---

<h3><br />Outline for Distortion, a White Noise novel.</h3><br /><br /><br /><em>*In Progress</em><br /><br /><br /><br /><br /><br /><ol><br /><li><b>Back-story.&nbsp;</b></li><br /><ul><br /><li>In the first few pages, introduce your reader to the protagonist and his/her world.</li><br /><li>Scene List:</li><br /><ul><br /><li>Street Noise - Ash is introduced. </li><br /><li>Action: He sees a homeless man go crazy, beats him up. His coffee is knocked out of his hand by a woman in a hurry. </li><br /><ul><br /><li>Reaction: Heads home, has crazy dream. </li><br /><li>Decision: Need to go to file the report in the morning.</li><br /></ul><br /><li>Action: Next day, Ash needs to file a police report. He calls and lets him know he's on the way. There he finds that the old man has died, suspiciously. </li><br /><ul><br /><li>Reaction: They ask some questions, and ask him not to leave town. "Standard procedure." He doesn't like Georges' look or evasive stance. </li><br /><li>Decision: Heads to... </li><br /></ul><br /><li></li><br /><li></li><br /><li>He stops and picks up a woman whose car broke down.</li><br /><li>She asks a lot of questions, casually. On their way out of town, they are ran off the road.</li><br /><li>??????</li><br /><li>X</li><br /><li>x</li><br /><li>x</li><br /><li>x</li><br /><li>x</li><br /></ul><br /></ul><br /><li><b>Inciting Event</b></li><br /><ul><br /><li>The event that forces the protag into the story, with a clear goal.</li><br /><li>There may be a clear, specific threat.</li><br /><li><strong>Scene List:</strong></li><br /><ul><br /><li><strong>Shattered</strong>&nbsp;- </li><br /><li>Car was run off the road.</li><br /><li>Grace reveals that she is&nbsp;a reporter, and she witnessed one attempt on his life already (something in his coffee), which she knocked out of his hand to save him.</li><br /><li>Tries to make it to his house, but they were followed, house destroyed.</li><br /><li>Tries to make it to back-up site, kills hit-man. More could come, house destroyed, may as well leave town. He has a contact living in LA. Ash hasn't seen Chester since he consulted him on a joint case with the NSA. No recent ties, should be the best place to find him. </li><br /><li>Grace and Ash head to LA.</li><br /></ul><br /></ul><br /><li><b>Series of Challenges and Solutions.</b></li><br /><ul><br /><li>Your protag tries a series of solutions&nbsp;and fails.&nbsp;</li><br /><li>Things seem to go well, and all hope is lost.</li><br /><li>Something BIG has to happen, or all is lost.</li><br /><li>Subtle changes. Character is wrestling through, lost in the fog.</li><br /><li>Scene List:</li><br /><ul><br /><li>X</li><br /><li>X</li><br /><li>X</li><br /></ul><br /></ul><br /><li><b>Dramatic turning point.</b></li><br /><ul><br /><li>A major change in your characters perspective.</li><br /><li>Small changes came before now, but this is a major change for your character. The path is now clear. May come at a cost. This is where his inner goal is realized.</li><br /><li>Scene List:</li><br /><ul><br /><li>X</li><br /><li>X</li><br /><li>X</li><br /></ul><br /></ul><br /><li><b>Climax (Goal Reached)</b></li><br /><ul><br /><li>Antagonist overcome, goal reached.</li><br /><li>Using the trans-formative new perspective he gained in step 4, he overcomes the outer goal and his inner struggle at the same time.</li><br /><li>Scene List:</li><br /><ul><br /><li>X</li><br /><li>X</li><br /><li>X</li><br /></ul><br /></ul><br /><li><b>Wrap Up</b></li><br /><ul><br /><li>Resolve/Restoration</li><br /><li>One last scene to show how the character's world turned out.</li><br /><li>Scene List:</li><br /><ul><br /><li>X</li><br /><li>X</li><br /><li>X</li><br /></ul><br /></ul><br /><li><b>Celebration</b></li><br /><ul><br /><li>Celebrating his victory. One scene, or less than a full scene.</li><br /><li>Hint at the future?</li><br /><li>Scene List:</li><br /><ul><br /><li>X</li><br /><li>X</li><br /><li>X</li><br /></ul><br /></ul><br /></ol><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><br /><div><br /><br /></div><br /></blockquote><br /><h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;"><br />By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4><br /><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><br /><i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote><br /><ul><br /><li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li><br /><li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li><br /><li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li><br /><li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li><br /></ul><br /><ul><br /></ul><br />