---
title: 'Panic Attack'
date: '2016-03-01T15:56:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4467946716483621350'
blogger_filename: '/2016/03/panic-attack.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Renewing the Mind (Stinking Thinking)'
  - 'Resting'
  - 'Recovery'
  - 'In The Mire'
---

<h3><br />Today started out well. I had a lovely morning, with a few pleasant distractions.</h3><br />Then I went to work.<br /><br />I walked in to what was an already overwhelming situation. It's not important to discuss the details. It is sufficient to say that I have a 660% workload, and I'm past burn out. I think I passed that three months ago.<br /><br />And yet... I still care.<br /><br />I know that it's literally impossible for any human being to do what I'm doing with anything other than a passing touch on quality work. And yet I struggle and strive to get it done anyway.<br /><br />My name is on that work.<br /><br />But I can't focus. I try to gather my thoughts, make some to-do lists, and then I get a whole new pile of crap dumped on me during the day. I can't touch one single thing I started the day with, not one.<br /><br />I normally work some overtime, because I can dig out a little. But today? I gave up. What's the point.<br /><br />I had such trouble breathing, focusing, and keeping my blood pressure in line, that I had to get up and leave. I took a real lunch, outside the building.<br /><br />It helped a little, but the stupid spring is already here. It was 78 degrees and I have no air conditioning in the car until my back-ordered part comes in.<br /><br />I got no winter, that sucked.<br /><br />Well... there's that.<br /><br />Darrell<br /><br /><br /><br />