---
title: 'I don&#39;t feel like it...'
date: '2016-09-30T13:59:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6718422240062358278'
blogger_filename: '/2016/09/i-don-feel-like-it.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'In The Mire'
  - 'Emotions'
---

I just don't feel like it. I don't want to wake up each day, or keep going. Being awake is exhausting.<br /><br />In <a href="https://www.lynda.com/Business-Skills-tutorials/Shane-Snow-Storytelling/491532-2.html" target="_blank">Shane Snow on Storytelling</a>,&nbsp;Snow introduces Relatability, Novelty, Tension, and Fluency as the elements of great stories. They are the elements that keep us wanting to come back again, or stay through to the end.<br /><br />There is a phenomenon were oxytocin is built in the brain when experiencing&nbsp;great stories together. They&nbsp;found that sitting&nbsp;kids in a room and telling them stories actually produced oxytocin&nbsp;in their brain, and the act of hearing stories together created bonds. <br /><br />Maybe I'm telling myself the wrong stories, and&nbsp;since I'm doing it alone, they are starving me of the bonds I need. <br /><br />I need to spend time telling and hearing stories with others... maybe that would help.<br /><br />Darrell<br /><br /><br /><br /><br /><br />