---
title: 'A Stone&#39;s Throw | A Parable for the #Christian &amp; #LGBT Communities'
date: '2016-06-22T04:15:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8658010439989594528'
blogger_filename: '/2016/06/a-stone-throw-parable-for-christian.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'News & Events'
  - 'Armchair Theology'
  - 'Spiritual Growth'
---

<h3>A Parable...(Fiction with a point)</h3><br />Joseph Oilman was well known in the region of Dallas Texas, for being a spiritual man, and friend to all. He and his staff were around a table at a local Starbucks, discussing a new project to feed the homeless and provide them with job skills.<br /><br />They were also planning a second project to refer those homeless to a partnering local health clinic, to provide treatment for people who's insurance did not cover the needed medications.<br /><br />A large, angry, crowd of people walked in and interrupted him. They brought news papers before him, and laid them on the table. A shooting at an Orlando nightclub had resulted in about 50 gay men and women being murdered.<br /><br />The crowd, mostly full of religious teachers and pastors, also brought forth a young gay man. They tossed him into a chair in front of Joseph, as though he were on trial.<br /><br />The leader of the angry crowd, a pastor in Fort Worth, laid a bible on the table. It was crisp, new, no markings or notes. The edges glittered in golden sheen.<br /><br />The pastor turned to Joseph, and said:<br /><blockquote class="tr_bq"><i>"Look here, the bible says that homosexuality is a sin, deserving of death. Does this man deserve to die or not?"</i></blockquote>They had been trying to discredit Joseph Oilman for some time now, and they hoped this would be the day. His "Love Hard" campaign had made them look bad, and he would be put against the bible now. He'd have to choose. They had him this time.<br /><br />Joseph, raised his eyebrow, looking slightly irritated at the interruption. He turned from the crowd, and slowly opened his back back. He fiddled around silently in the bag for about two minutes.<br /><br /><blockquote class="tr_bq"><i>"Well?"</i> the pastor said<i>. "Are you going to answer us?"</i></blockquote>Joseph pulled out his own bible. It was not new or shiny. It was well worn, broken on the edges. There were notes hand written across the pages, underlines, highlights, and markings of various kinds.<br /><br />Turning to the same passage (<a href="http://biblehub.com/niv/romans/1.htm" target="_blank">Romans 1</a>), Joseph tossed his own bible on the table, right on top of the other mans'. He pointed to the page, and read it upside down.<br /><br />He replied:<br /><blockquote class="tr_bq"><i>"Well now... " </i>Joseph paused for effect.<i>.. "According to this list of things that deserve death, there is:</i><ul><li><i>depraved mind/depravity</i></li></ul><ul><li><i>wickedness</i></li></ul><ul><li><i>evil</i></li></ul><ul><li><b><i>greed</i></b></li></ul><ul><li><b><i>envy</i></b></li></ul><ul><li><b><i>murder</i></b></li></ul><ul><li><b><i>strife</i></b></li></ul><ul><li><i>deceit</i></li></ul><ul><li><i>malice</i></li></ul><ul><li><b><i>gossips</i></b></li></ul><ul><li><i>slanderers</i></li></ul><ul><li><i>God-Haters</i></li></ul><ul><li><i>Insolent</i></li></ul><ul><li><b><i>arrogant</i></b></li></ul><ul><li><b><i>boastful</i></b></li></ul><ul><li><i>those who invent ways of doing evil</i></li></ul><ul><li><i>people who disobey parents or leadership</i></li></ul><ul><li><i>people of no understanding (ignorant people)</i></li></ul><ul><li><i>unfaithful people</i></li></ul><ul><li><b><i>people who don't walk in love</i></b></li></ul><ul><li><b><i>people who don't show mercy</i></b></li></ul></blockquote><br /><div><br /></div><div>He took a moment to re-read the list to himself again, under his breath.</div><blockquote class="tr_bq"><i>"Nope... I'm not seeing 'being gay' on this particular list... but I'm about 99% sure that you are personally violating three or more of these right now as we speak."</i></blockquote><br />His staff got a kick out of that. Some laughed, some snorted.<br /><blockquote class="tr_bq"><i>"Tell you what... bring me a gun and we'll start with you first, since it says here that you need to die. Then we can take out anyone else who wants to use this list as the measuring stick? How does that sound?"</i></blockquote><br /><br />The pastor looked like someone had poured lemon straight in his mouth. He grabbed his bible, and turned away in a huff. Stomping out the door. About half the crowd left with him.<br /><br />The remaining half stayed, and apologized to the young gay man for their harsh treatment of him.<br /><br />Joseph Oilman addressed to the remaining crowd:<br /><blockquote class="tr_bq"><i>"Now... if the rest of you, and you young man, would like to hear about what the WHOLE bible says, in context, about how God feels about every human on earth... please turn with me (if you have a bible) to <a href="http://biblehub.com/john/3-16.htm" target="_blank">John 3:16</a>..."</i></blockquote><br /><h4><b>*** On a personal note:</b></h4>When I heard (<a href="http://thescoopblog.dallasnews.com/2016/06/fort-worth-pastor-calls-orlando-shooting-victims-the-scum-of-the-earth.html/" target="_blank">here</a>) that a pastor in Fort Worth, Texas and another related Pastor in Sacramento, California actually said they supported the shooting of gays... my heart dropped.<br /><br /><b>To this pastor (and others like him):</b><br /><blockquote class="tr_bq">You need to get saved... it's obvious you are not. You can't be, and speak like this. You are in Fort Worth, shut down your church. All of you need to get saved, then go to <a href="http://gatewaypeople.com/ministries/freedom/events/freedom-basics" target="_blank">Gateway Church's Freedom Ministry</a>.</blockquote><br /><b>To my gay friends out there:&nbsp;</b><br /><blockquote class="tr_bq">God does not hate you, some religious people do. There's a big difference. Religion hated Jesus too. He died for me, you, and everyone else on earth (even the religious people). He loves you passionately, more than any lover (male or female) you will ever know.</blockquote><br /><ul><li><b style="background-color: cyan;">God LIFE? Not sure? <a href="http://darrellwolfe.blogspot.com/p/got-freedom.html" target="_blank">Click here to find out.&nbsp;</a></b></li></ul><br /><br /><br /><div><div style="text-align: center;">********</div><br /></div><div>By <a href="https://plus.google.com/+DarrellWolfe/posts">Darrell Wolfe</a>&nbsp;| #<a href="http://ctt.ec/5xc67">BeStillBeLed</a></div><div><br />Story Teller | Creative | <a href="http://www.16personalities.com/infj-personality">INFJ</a> | <a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder">Intellection</a> | Learner | Ideation | Achiever | Input | Multipotentialite<br /><br />New here?<br /><br /><ul><li><a href="http://darrellwolfe.blogspot.com/p/about-20.html" target="_blank">Start Here</a> for more information.</li><li><a href="http://darrellwolfe.blogspot.com/p/q.html" target="_blank">Ask </a>me anything</li><li><a href="http://darrellwolfe.blogspot.com/p/got-freedom.html" target="_blank">Got LIFE? Not sure, click HERE to find out.</a></li><li>See <a href="http://www.darrellwolfe.com/p/by-darrell.html" target="_blank">DarrellWolfe.com</a> for more of my sites.</li></ul><div><br /></div></div>