---
title: 'Provider My Ass...Part Two God''s Answer'
date: '2016-11-05T08:00:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6744522502969215943'
blogger_filename: '/2016/11/provider-my-asspart-two.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Renewing the Mind (Stinking Thinking)'
  - 'Resting'
  - 'Recovery'
  - 'In The Mire'
  - 'Emotions'
---

<div>
<i>Friday Night / Sat Morning</i></div>
<div>
<br /></div>
<div>
Dear God,</div>
<div>
<br /></div>
<div>
I find myself silent tonight. Not without words, for you made me a writer. I am without argument. The anger I tried to drum up an hour ago, was gone. It's missing.</div>
<div>
<br /></div>
<div>
Inside, stillness. Weird stillness. Like you silenced the enemy, and you silenced yourself, and I was left alone with my thoughts and only my thoughts for the first time in a long time.&nbsp;</div>
<div>
<br /></div>
<div>
For future me's sake, and those who may stumble across this post, let me tell you what happened tonight minus details that belong to others.</div>
<div>
<br /></div>
<div>
A friend stopped me in the middle of a conversation we were having and said to me and said he felt led to give me "this", and handed me a folded green amount of money. I took it, shook his hand, and thanked him. Surprised, and honored, and knowing in my heart that despite the fact I don't deserve it because I've been a total ass to God and my family... Jesus blood paid for all that and he was trying to love on me.&nbsp;</div>
<div>
<br /></div>
<div>
We kept talking, and I told him a few of the things that had been on my heart to tell him, but I knew I needed to wait until after the meeting to do it.&nbsp;</div>
<div>
<br /></div>
<div>
Further into the conversation, he said he had a different number, but he thought i'd be offended (as we men tend to hate accepting help) and handed me a crisp $100.00. I later checked, and the folded money was actually $40.00.</div>
<div>
<br /></div>
<div>
Few people even know this blog exists, so he didn't know about the post I just wrote this past Monday, October 31, 2016, titled <b><a href="http://ihaveennui.blogspot.com/2016/10/provider-my-ass.html" target="_blank">Provider My Ass..</a></b></div>
<div>
<br /></div>
<div>
My friend told me later in the conversation (and I paraphrase), that I was going to be like a grace-version of Pharaoh. God did miracle after miracle in his presence, to the point that all of your arguments and rationalizations are destroyed, and you have to know He is God.&nbsp;</div>
<div>
<br /></div>
<div>
Even if you harden your heart, it keeps coming.&nbsp;</div>
<div>
<br /></div>
<div>
No matter how hard you try to be, he's going to shower so much love on you, like the Egyptian miracles, that you'll have no argument left.</div>
<div>
<br /></div>
<div>
Between the men I've submitted to... and my Psychologist I just started going to... I have a feeling I'm in store for a total transformation. I don't know what the guy on the other side of that looks like. I don't know if he can restore his marriage, relationship with his children, or day-to-day sanity. I don't know if that guy is sober or not.&nbsp;</div>
<div>
<br /></div>
<div>
I don't know what the transformation will be... but I believe it will be profound.<br />
<br />
Come to think of it... the miracles were for Moses as much as Pharaoh. Moses' heart needed convincing too. He was a reluctant leader, and the burning bush got him moving, but not convinced. By the time Moses left Egypt, He was convinced and obedient.&nbsp;</div>
<div>
<br /></div>
<div>
God told me a long time ago I would have a Moses and Joshua blend style ministry. I would have to lead them out, and lead them in... so the analogy my friend used was deeply personal for me, even though he didn't know that because I'd never talked about that with him.<br />
<div>
<br />
I sit here with $140.00, which is what I needed to really prepare for a part-time job thing I want to do. As usual... God shows up and blows my mind.</div>
</div>
<div>
<br /></div>
<div>
This doesn't mean I'm less hurt, frustrated, confused, and my desires that run counter to the things I "know" are "right" haven't done away. But a certain intensity is missing... Hm....<br />
So, broken or whole, "right or wrong", that's what I'm thinking about today,<br />
<br />
Darrell W. <br />
<br /></div>
