---
title: 'Premeditated Disappointments'
date: '2016-08-10T11:41:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8283894768625596965'
blogger_filename: '/2016/08/premeditated-disappointments.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Renewing the Mind (Stinking Thinking)'
  - 'Resting'
  - 'Recovery'
  - 'In The Mire'
  - 'Emotions'
---

<br />As my psychologist dad says...<br /><br /><blockquote class="tr_bq"><b>Expectations Are Premeditated Disappointments</b></blockquote><br />and...<br /><br /><blockquote class="tr_bq"><b>Plan Plans Not Outcomes</b></blockquote><br />I have had in my mind and heart a "way it's supposed to go/be", all my life. So far almost exactly NOTHING has every gone the way it was supposed to go, or been the way it was supposed to be.<br /><br />As it turns out, I'm a lousy planner of outcomes.<br /><br />I'm an idealist, who can tell you what the right principles are, but specific outcomes are only within God's hands, not man's.<br /><br />Maybe I do need to die after all... die to self.<br /><br />Maybe I need to die to "I want" and "I need" and "I desire" and just, simply, follow His lead.<br /><br />But if I do that, if I follow His lead, that will lead me down paths I don't want to go, into situations I don't want to be in... that will take me to a prison after being beaten (Paul &amp; Silas), it will get me thrown into a Lion's den (Daniel)... Sure, they overcame those situations, but not without cost.<br /><br />Then again... isn't there a cost to NOT following his lead?<br /><br />By the scale of my imaginations for what my life should have been... this life has been a GRAND DISAPPOINTMENT... I imagined I'd be a Ted Dekker by now, or leading a Pixar by now, or something other than struggling to pay bills and working a 9-5. That's where MY planning has gotten me.<br /><br />So maybe the cost of following Him, and there IS a cost, isn't as high as the cost of not following Him?<br /><br /><br />There's a thought...<br /><br />Darrell