---
title: 'Dissapointment'
date: '2016-08-09T13:15:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2694119690578618508'
blogger_filename: '/2016/08/dissapointment.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'In The Mire'
  - 'Emotions'
---

<br />For several days I have been wandering around thinking about this impending job offer. I felt like I was hearing God say "I got this", and that's it. That's all He'd say. Of course I didn't&nbsp;<i>feel&nbsp;</i>as though he Got This, but I said "OK Lord, I trust you got this".<br /><br />I got the call yesterday, they want to offer the job, but for WAY less than I was expecting.<br /><br />Overtime is not likely in this new position, but possible. So that's a concession.<br /><br />I'm taking an effective pay-cut.<br /><br />I've spent SO many years making "not enough" or "barely enough", I was really hoping this position would put us over the top... but it's another in a long line of "better, almost there". I was hoping to be past "almost there" years ago.<br /><br />Only I could turn a great job offer into something to complain about.<br /><br />It's just that... I always expected I'd be something by now.<br /><br />In 2002-2004 I was having big dreams, and I was expecting those dreams to have happened years ago... Those dreams are all but dead now.<br /><br />I never intended, ever, to have a "career" working for any company. I thought I'd be a self-employed millionaire by now. I NEVER intended to be with the same company ten years later... that's so disheartening.<br /><br />Intellectually, I can admit I didn't "DO" the things I needed to "DO" to become wealthy. I always felt like I was one idea away, or maybe one new contact or new resource away...<br /><br />But it's time to face the facts... those were dreams of a naive young kid, who didn't understand how hard the world really was.<br /><br />MAYBE... someday... I'll figure out what I needed to know to get an idea to actually work...<br /><br />But it's time to face the fact that I'm just another cog in the wheel of some corporate machine, and I probably will be for another ten years. I guess I just need to let those dreams die.<br /><br />Darrell<br /><div><br /></div>