---
title: 'Practice: Re-write another author.'
date: '2016-04-07T13:39:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3561074865491056690'
blogger_filename: '/2016/04/practice-re-write-another-author.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Writing Practice'
---

<br /><br />So, from what I can tell&nbsp;<a href="http://amzn.to/22f2SX8" target="_blank">By the Light of the Moon </a>by Dean Koontz (Author), is a decent story. But I'm having a heck of a time getting past the first 10 pages. He is confusing. I like some of the phrasing he uses to paint a picture of the idea, but he uses too much. So much, in fact, that the idea he's trying to paint may be lost.<br /><br />I'm pretty sure he's trying to say it was a heck of a hot day here, but this is what he says:<br /><br /><blockquote class="tr_bq">"The expired day lay buried in the earth, in the asphalt. Unseen but felt, its ghost haunted the Arizona night: a hot spirit rising lazily from every inch of ground that Dylan crossed."</blockquote><br />I'm like... what? I suppose it would be fine if these phrases were scattered about, amidst more plain writing. Instead, it feels as though this complicated word choice is in every paragraph.<br /><br />So I am left to ask myself, how would I write that, but still use his idea?<br /><br /><blockquote class="tr_bq">"The expired day lay buried in the asphalt, the hot Arizona spirit rising to haunt Dylan as he crossed."</blockquote>Something like that, I think. Don't use ten words, when five would do. Maybe it's just a style difference. Different styles for different readers.<br /><br />Darrell