---
title: 'See me... don&#39;t change me?'
date: '2016-11-28T20:19:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6894708138794524357'
blogger_filename: '/2016/11/see-me-don-change-me.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Renewing the Mind (Stinking Thinking)'
  - 'Resting'
  - 'In The Mire'
  - 'Emotions'
  - 'Freedom/Kairos'
---

<br />Dr. Bob Hamp asked me a difficult question to ponder last time we met. He told me not to come up with answers right away, but to be pondering:<br /><br /><em>How can you start to have your legitimate needs met legitimately, rather than through the counterfeits you've used (or are using)?</em><br /><br />I suppose the first step is to figure out what are my legitimate needs? What am I not getting that I sought to get from others (bosses, workaholism, drugs/alcohol/other addictive behaviors)? <br /><br />What is it that I'm getting from the men I've started to hang around that I didn't feel I was getting elsewhere? <br /><br />I tied one thing in today, as I pondered. The guys and I are starting a Podcast (name pending - current&nbsp;working title&nbsp;Lost and Found "LaF", outcasts and infidels getting to know THE JESUS rejected by religion). <br /><br />Our goal is to reach those who aren't "accepted" by the church or religion.<br /><br />I've been thinking about my self-talk when I come home, conversation with my spouse. What is it that I think/feel? <br /><br />"Pressure" - comes to mind. So many things in the house need me and I'm not enough to produce for them (too broke to fix the appliances which ALL need to be replaced). Every scratch, dent, broken light switch, is another reminder that I'm not enough. I don't have it in me. Every time my wife or kids are&nbsp;disappointed in my behavior or choices, every time&nbsp;my wife&nbsp;reminds me not to make a purchase because we're broke... it's just more and more layers of pressure to be something more that I can't be.<br /><br />My friend Rudy, and others recently, accept me for me... just me. They will encourage my growth, but... they see me?<br /><br />I don't feel that my some of the people closest to me see <strong><em>me</em></strong>, but the person she wants me to be. It may not be true, but it's how I feel when I'm there. Like I have to be the idealized version of their version of me... and I can't be. Then again, I've learned that may be my fault, not theirs.<br /><br />I thought it was interesting that the <a href="https://www.16personalities.com/infj-strengths-and-weaknesses" target="_blank">INFJ</a> type actually says (under weaknesses):<br /><ul><li>Extremely Private – INFJs tend to present themselves<strong> as the culmination of an idea</strong>. This is partly because they believe in this idea, but also because INFJs are extremely private when it comes to their personal lives, using this image to keep themselves from having to truly open up, even to close friends. Trusting a new friend can be even more challenging for INFJs.</li></ul><br />I don't know, it's a half thought. But... it's what I have today.<br /><br />So, broken or whole, "right or wrong", that's what I'm thinking about today,<br /><br />Darrell W. <br /><br />