---
title: 'Processesing my time with Dr. Bob - Session #4'
date: '2016-12-09T15:21:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '944921685262299861'
blogger_filename: '/2016/12/processesing-my-time-with-dr-bob.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Renewing the Mind (Stinking Thinking)'
  - 'In The Mire'
  - 'Resting'
  - 'Recovery'
  - 'Emotions'
  - 'Freedom/Kairos'
---

<br />Some of the stuff I talked to Dr. Bob about yesterday:<br /><br /><a href="https://www.youtube.com/watch?v=AMgyWT075KY" target="_blank">Arrival (2016)</a>, they attempt to establish communication with an alien race. But games made it more<br />competitive/adversarial. Symbols made it easier to communicate. Sometimes analogies can help.<br /><br /><br /><ul><li>How do you pray if your don't Trust God, are mad at Him, don't want to hear him? What if you heard God, and did what He said, and it turned out bad?</li></ul><br /><div><br /></div>"Though he slay me, yet I will trust in him."<br />"Lord, to who would we go to for answers?"<br />You have to be honest and open about your hurt, pain, frustrations... and not JUST when you are feeling angry and yelling, but in your calmer moments too. Don't just open the door, yell at God, then close it again when you're calm. Keep the door open, and let your conversations be:<br /><br />I'm angry with you, I think you didn't do so right by me, here's why....<br /><br />instead of:<br /><br />I surrender all...<br /><br />If that's what they need to be.<br /><br /><br /><br /><ul><li>How do you want what you don't want, or stop wanting what you shouldn't want?</li></ul><br />Wanting the right things and not wanting the wrong things is a matter of source. The source you are connected to drives the wants. If you are disconnected from your source, the wants/desires will be skewed.<br /><br />The short answer is... you don't. You don't change your wants... you change your source. But if you are mad at your source, you're wants cannot change. Deal with the source, and let the wants be what they are for now.<br /><br /><br /><br /><ul><li>What if God's answer is: "I'm not you?"</li></ul><br />That is the crux of God's answer to Job. I'm not you. But what if that's exactly the answer you need. He's not us. He doesn't see like us, think in our limited way of thinking. His perspective is higher and eternal, ours is lower and temporal. Getting His perspective will help us think the way he thinks, which changes the contents of our hearts/minds.<br /><br />Do to that, the only way to do that, is to connect with Him. Which means having those open, honest discussions, above.<br /><br /><br /><br /><ul><li>How do you feel about Medication?</li></ul><br /><br />Spare tire: If you have a flat in the dessert, you put your spare tire on. You don't drive that spare tire for ten years, but you put that little donut tire on to get you to a place where you can repair or replace the broken tire. Medication is your spare tire.<br /><br />Missing glasses: If your sight (spiritually/emotionally) is malfunctioning, put on any pair glasses you can find (even if it's an old pair with the wrong prescription) just so you can see well enough to get where you need to be and get the right fitting glasses put back on again.<br /><br />Went to Primary Care Dr, and got two at the Primaries suggestion:<br /><br />Zoloft - takes a while to build up, but will help stabilize.<br /><br />Xanax - works quick, but not long lasting. Take as needed.<br /><br /><br /><br /><ul><li>Helping others...</li></ul><br />Helping others is a good thing, even and especially if you don't feel whole yet. LIFE is not an On or Off proposition. You have quantities of it. If you only have 2% LIFE, then you have 2% to give. If you have 51% LIFE, you have 51% to give to others. What you have given, pulls on the source to refill beyond what you gave.<br /><br />Even if you don't feel whole yet, you keep giving, and it will be given back to you, pressed down, shaken together, running over.<br /><br /><br />Afterward, hear this on the radio:<br /><br />Start being aware of the nuanced feelings you have. The more nuanced you can describe them the better.<br /><br /><blockquote class="tr_bq"><b>"I'm noticing that I'm feeling...."</b></blockquote><br />This can be a wonderful tool for helping you drive into the experience of those feelings and process them. <a href="http://amzn.to/2heHGRR" target="_blank">Susan David, Emotional Agility</a><br /><br />So, broken or whole, "right or wrong", that's what I'm thinking about today,<br /><br />Darrell W. <br /><br />