---
title: 'Financial Training Course (Future Project Needs Your Help)'
date: '2016-05-28T05:09:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5551532482684245483'
blogger_filename: '/2016/05/financial-training-course-future.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Savings'
  - 'Lending'
  - 'Credit'
  - 'Investments'
  - 'Banking'
  - 'Blessed Money'
  - 'Retirement'
---

<h3>Banking Basics - Financial Training Course</h3><br />I'm considering the idea of developing a Banking Basics training course. It could consist of basic things a person would need to know to be financially successful.&nbsp;<div><br /></div><div>I want this to be simple enough to hear once and walk away with something small to read to remember the points. Maybe 1-3 courses and if there are more than one course they should be stand alone, you don't need to take them in order and you don't need to take all three to benefit from one.</div><div><ul><li><b>Money Management</b> (Balancing, Budgeting, and Basics of Money as a Tool)</li><li><b>Savings and Investing </b>(Buying the future one dollar at a time)(Including Retirement)</li><li><b>Using Credit </b>(Maybe teach on credit if they want to build it or use it for select things)</li></ul><div>Over the past 10+ years, I've helped people one on one with these topics. I can build meaningful material, cover it in a quick class and provide an impact to others. Let's break it down into more detail.</div><br /><b>Money Management</b><br /><ul><li>Money as a tool, what's for/not for, money not bad or good. Money = Time</li><li>How a bank account works, registers, processing, posting, etc.</li><li>Overdraft Prevention NOT Overdraft Protection</li><li>Debit Card Overdraft Service</li><li>Overdraft Protection</li><li>Bill Pay</li><li>Recurring Debit Card Transactions</li><li>Envelope System/Multiple Accounts</li></ul></div><div><b>Saving and Investing</b><br /><ul><li>Why pay $35,000 for a $20,000 car that looses value?</li><li>Small steps, savings, investing, purchases, time.&nbsp;</li><li>Property Rent V Own</li><li>15 Year Mortgage</li><li>Retirement 30-50% income boost by owning home.&nbsp;</li><li>IRA, 401K, Roth V Traditional</li></ul></div><div><b>Using Credit</b><br /><ul><li>Best option, live without credit</li><li>IF you must or feel that you want to engage in credit, here are the things you need to know.&nbsp;</li><li>FICO Building</li><li>Score Breakdown</li><li>Credit Cards are Transaction Tools NOT Borrowing Tools</li><li>Buy less home</li><li>Borrow strategically</li></ul><br /><b>I would like YOUR help:</b><br /><ul><li>Do you have any thoughts on this idea?&nbsp;</li><li>What topics would YOU want to see covered?</li><li>Is there any question you have about money or banking basics that I have no already answered on this site? Check out the links on my <a href="http://bankingbasicsforbelievers.blogspot.com/p/ask-insider.html" target="_blank">Ask The Insider</a> page to see what I've already written about.</li></ul><br />If you have ideas, comment on the&nbsp;<a href="http://bankingbasicsforbelievers.blogspot.com/p/ask-insider.html" target="_blank">Ask The Insider</a>&nbsp;page, or email me at: <a href="mailto:YourMoneyIsHis@outlook.com" target="_blank">YourMoneyIsHis@outlook.com</a><br /><br /><br /><b>The Insider</b></div>