---
title: 'You are wired for story. Did you know that?'
date: '2016-09-11T08:17:00.0050000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '9082632840176443277'
blogger_filename: '/2016/09/you-are-wired-for-story-did-you-know.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Fiction'
  - 'NonFiction'
  - 'Other'
---

<br />
I'm almost done reading a book called&nbsp;<a href="http://amzn.to/2c6YgCA">Wired for Story: The Writer's Guide to Using Brain Science to Hook Readers from the Very First Sentence</a>, by Lisa Cron (Author)<br />
<br />
Mind blown. We are literally wired for story. She breaks down the brain science behind every element of the craft and character creation. I'll never write a "teach you" book again without including story because of this book.<br />
<br />
In one section, she takes a mediocre idea that has no pull, and turns it into a story I still want to read and think about days later. All without actually writing the story. She just breaks down the brain science behind why we think the way we do, and then gives us just enough of the background that the story starts writing itself. Amazing.<br />
<br />
Here's a Ted Talk called&nbsp;<a href="https://youtu.be/74uv0mJS0uM" target="_blank">Wired for story:</a>&nbsp;given by Lisa Cron at TEDxFurmanU:<br />
<br />
<iframe allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/74uv0mJS0uM" width="560"></iframe>

<br />
<br />
<br />
<iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&amp;OneJS=1&amp;Operation=GetAdHtml&amp;MarketPlace=US&amp;source=ss&amp;ref=as_ss_li_til&amp;ad_type=product_link&amp;tracking_id=your0f4d-20&amp;marketplace=amazon&amp;region=US&amp;placement=1607742454&amp;asins=1607742454&amp;linkId=cb398291fede8257cc921e6104bd35b5&amp;show_border=true&amp;link_opens_in_new_window=true" style="height: 240px; width: 120px;"></iframe>

<br />
<br />
Thanks to checking her out!<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;"><br /></span></div>
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Story Teller | <a href="https://www.16personalities.com/infj-personality">INFJ</a> | Futuristic | Intellection | Learner | Ideation | Achiever | Command | Input | Focus | <a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en">Multipotentialite</a><o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
