---
title: 'The FutureScapes Writing Contest, 2016 Theme is Cities of Empowerment.'
date: '2016-04-30T05:30:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '63721422464320684'
blogger_filename: '/2016/04/the-futurescapes-writing-contest-2016_29.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Writing Practice'
---

<br /><br />The <a href="http://www.futurescapescontest.com/" target="_blank">FutureScapes Writing Contest</a>, 2016 Theme is <a href="http://www.futurescapescontest.com/empowerment-cities/" target="_blank">Cities of Empowerment</a>. They specifically reference HG Wells, and Star Trek in their examples of works that have inspired our lives.<br /><br /><br /><br />What does the idealized future, 30 years from now, look like to me?<br /><br /><br /><br />As a Libertarian and Science Fiction fan, this could be fun.<br /><br /><br /><br />Some ideas off the cuff.<br /><br /><br /><br />Technology, voting and running for office from the home computer/tablet/social media.<br /><br /><br /><br />Using Liberty as the primary focus. Less government, and more crowd sourced solutions.<br /><br /><br /><br />Google Voice empowering the blind and deaf.<br /><br /><br /><br />Schools built on competition (open enrollment, and specialized training programs). Are they funded by taxes, or other means? Product Tax (ei: lotteries, but ones where 90% of all funds go to the schools not the lottery admins; or, Schools that produce product for purchase).<br /><br /><br /><br />Voters rewarded (through business contributions) for positive results, on mutually agreed upon metrics. Balanced Budgets, increased economic growth, lower crime rates.<br /><br /><br /><br />Elderly, Physically Disabled, Mentally Disabled, Poor... how are they provided for without further drain on government resources and increased taxes?<br /><br /><br /><br />Innovation. The US Constitution encourages the Congress to encourage Art and Science, but through intellectual property rights (not taxes and grants). How could this idea be expanded and developed?<br /><br /><br /><br /><br /><br /><br /><br />Darrell