---
title: 'Other people&#39;s emotions...'
date: '2016-06-05T21:32:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1757819014969256438'
blogger_filename: '/2016/06/other-people-emotions.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Renewing the Mind (Stinking Thinking)'
  - 'Resting'
  - 'Recovery'
  - 'In The Mire'
  - 'Emotions'
---

<br />Here's a weird one for you. I can be feeling generally good, with no particular sadness.<br /><br /><br />Someone else has an emotional upset (especially my wife or child), and I feel as through I've been hurled through a wall into depression. I could be feeling alight, then one of them gets sad or angry, and I suddenly want to throw myself into oncoming traffic.<br /><br />I have to leave, in a hurry, and close myself up into a small space. My office usually, and shut it all out. The smaller the space the better. A closet, a corner, wrapped in a blanket, under the bed, somewhere confined and small.<br /><br />Then... with some time... that wave of overwhelming emotion passes and I can re-enter the world.<br /><br />This sounds an awful like like what people describe for kids on the Autism spectrum...<br /><br /><b>Maybe I have the slightest touch of Autism?&nbsp;</b><br /><br /><br /><a href="http://psychcentral.com/quizzes/autism-quiz.htm" target="_blank"><b>Short Autism Screening Test</b></a><br /><br /><ul><li>Results of your Short Autism Screening Quiz \You scored a total of &nbsp;24</li><li>Based upon your responses to this autism screening measure, you have symptoms associated with an autism spectrum disorder diagnosis. People who've scored similarly to you on this screening measure will often meet the diagnostic criteria for autism or Asperger syndrome, a milder form of autism.&nbsp;</li></ul><div><br /></div><div><br /></div><br /><div><a href="http://mindchecker.channel4.com/test-autism.html" target="_blank"><b>Mind Checker</b></a></div><div><ul><li><b>Above average score, but below the threshold</b></li><li><b>You scored slightly higher than average on this test, but are still below the threshold of 32 points that would likely indicate an autistic spectrum disorder.&nbsp;</b></li><li><b>Just because you have scored higher than average, it does not mean that you are likely to be autistic</b> - many people who score highly have no problems functioning in their day-to-day lives.&nbsp;</li><ul><li>This can be because of a good match with their chosen career (anecdotally, mathematicians and computer scientists score higher in this AQ test)&nbsp;</li><li>or because they have a supportive family/social network that prevents any secondary problems occurring.&nbsp;</li></ul><li>If you feel that you are not able to function normally in day-to-day life, it may be worth talking to your GP about these test results.</li></ul><ul><li>Autism can be mild, in which case the impact on daily life is minimal - or it can be so severe that sufferers struggle to function in their day-to-day lives, where the world seems a strange and scary place. There is currently no cure for ASD, but there are a range of treatments that can improve/manage the symptoms.</li></ul><ul><li>Autistic Spectrum Disorders have a wide range of symptoms, grouped into three broad categories:</li></ul><ul><li>Problems and difficulties with social interaction, such as a lack of understanding and awareness of other people's emotions/feelings.</li><li>Difficulty with language and communication skills, such an inability to start conversations or take part in them properly (often resulting in interrupting others inappropriately).</li><li>Unusual patterns of thought and physical behavior – such as making repetitive physical movements (e.g. hand tapping or twisting).</li></ul></div><div><br /></div><div><br /></div><div><div><a href="https://www.verywell.com/what-is-mild-autism-260244" target="_blank"><b>What Does Mild Autism Mean?</b></a></div></div><div><br /></div><div><ul><li>Answer: Because autism is a "spectrum disorder," it is possible to have a very wide range of symptoms. At one point, there were five different autism spectrum diagnoses, and people whose autistic symptoms were less challenging were generally diagnosed with Asperger syndrome. &nbsp;In 2013, however, the diagnostic criteria were changed. Rather than five separate autism spectrum diagnoses, there is now only one: Autism Spectrum Disorder.</li></ul><ul><li>To make matters more difficult, a person with "mild autism" may have advanced communication skills and academic abilities, but have very delayed social skills, severe sensory issues, and/or extreme difficulties with organizational skills.</li></ul></div><div><div><br /></div></div><div>By Darrell</div>