---
title: 'Power of Prayer (Series) | How to have a daily dynamic prayer life (Message) | Jimmy Evans'
date: '2016-07-31T05:13:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1374309793084812061'
blogger_filename: '/2016/07/power-of-prayer-series-how-to-have.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Spiritual Growth'
  - 'Church Notes'
---

<h3>Power of Prayer (Series) | <a href="http://gatewaypeople.com/ministries/life/events/the-power-of-prayer-a-gateway-series/session/2016/07/30/how-to-have-a-daily" target="_blank">How to have a daily dynamic prayer life (Message)</a> | Jimmy Evans&nbsp;</h3><h4>@<a href="http://gatewaypeople.com/ministries/life/events/the-power-of-prayer-a-gateway-series/session/2016/07/30/how-to-have-a-daily" target="_blank">GatewayPeople </a>Church, Southlake Texas | My Church Notes from service today</h4><br /><h4>Why we pray:&nbsp;</h4><br /><ul><li><b>Acknowledge God, allowing Him access to us (generally and specifically)</b></li><ul><li>He knocks on the door of your heart, He doesn't kick it down. You need to open it to Him (not just once at salvation, but every single day). He will reside in you up to, but limited to, the space you give to Him willingly.</li><li>A day without prayer is a boast against God, a day without prayer is a day without his FULL assistance, direction, provision, or &nbsp;protection (to a point, one could say, your cooperation with it).&nbsp;</li><li>You can't make the play, if you didn't show up to practice.</li><li>We are sheep. There are no:</li><ul><li>Homing Sheep (Sheep can't find their own way).</li><li>Pack Sheep (they can't bear burdens well).</li><li>Attack Sheep (they can't defend themselves).</li></ul><li>You need a Shepherd to guide/lead you, bear your burdens, defend/protect. If you try to do these things for yourself, you will be limited at best.</li></ul><li><b>Build a Prioritized/Personalized Relationship with God.</b></li><ul><li>Dialogue not Monologue. And really, since God knows everything about you, GOD should be doing at least 60% of the talking.&nbsp;</li><li>Kenneth told the story of a man who said: "Here lies a man who knows nothing, doing all the talking to the One who knows everything!"</li><li>God wants Darrell time (put your name there).</li><li>I don't get into God's presence after I'm right, I get into His presence to GET right. Only screwed up people qualify to get into His presence.&nbsp;</li></ul><li><b>Exercise Authority</b></li><ul><li>Whining in the Spirit is not a spiritual gift.&nbsp;</li><li>God won't do for you, what He gave you the Authority to do yourself.&nbsp;</li><li>You can either be defeated or win, but you can't be both, and you must decide. He gave you the tools. He doesn't want you lifting burdens that you can't carry, but he doesn't want to carry what he told you to carry.&nbsp;</li></ul></ul><br /><br /><h4>How we pray</h4><br /><ul><li><b>Don't be an attention hog.</b> Don't pray to be a religious show off or get attention. (Religion)</li><li><b>Don't babble </b>on and on, repetitively, hoping that you'll get heard if you say it enough. (Non-Relational).</li><li><b>Pray in this manner (this is the PATTERN of the Lords Prayer):</b></li><ul><li><b>Thanks Giving &amp; Praise</b></li><ul><li>Acknowledge his Name and Address</li><li>See Him for who HE is.</li><li>Clear your heart to see Him as He is, not as you want Him to be.</li><li>Thank Him for who he is and what he's done.</li><li>Really think about your life recently, what can you thank him for, honestly (not religiously).</li></ul><li><b>Surrender to His Authority (Submit)</b></li><ul><li>YOUR WILL - Seek his guidance, wisdom, direction.</li><li>What do YOU want? What are YOU doing in this moment/day/year?</li></ul><li><b>Provision Seeking</b></li><ul><li>Not just money... Favor, Direction, Wisdom</li><li>Set before him, honestly, your temptations, pains, hurts, wounds, needs, wants, desires... surrender them to Him. Let Him heal, change, alter, kill, or enhance what He needs to get your heart in tune with His.</li></ul><li><b>Forgiveness and Forgive</b></li><ul><li>Focus on His goodness and Grace in your life, then focus on what goodness and grace you can let Him show others in/through you.</li></ul><li><b>Divine Right (Submit)</b></li><li>There are three things that he will NEVER share or let you have.</li><ul><li>Kingdom - I'm not building my kingdom today God, I submit to your kingdom and your authority (Lordship) today.</li><li>Power - I operate through your power, not mine. I will not seek to use my power, but yours only.&nbsp;</li><li>Glory - I send all Glory to you. Not religiously, but genuinely. Not with a fake humility "to God be the glory" every time someone just wants to tell me I did a good job. But honestly, openly, direct praise to God when given the opportunity.&nbsp;</li></ul><li><b>AMEN</b></li><ul><li>So Be It - Stamp it with the final Seal of Approval.</li><li>There is NO POINT to pray (3 minutes or 3 hours) if you are going to walk away in the same doubt you started in.&nbsp;</li><li>End the prayer with "let it be done as you said Lord"</li><li>Or, "I believe I receive as you said".</li><li>Or, "Yes Lord"</li><li>something to show you are in agreement with God today.</li></ul></ul></ul><div><br /></div><div><br /></div><br /><div style="text-align: center;">********<br /><div><br /></div></div><h4><b>My Comfort vs God's Will</b></h4><br />So..... I'm going to be honest. I'm not doing well lately. I've let stress build inside me for so many months that I am nearly constantly irritated. I'm in red gas gauge, relapse sounds great, screw life, un-healthy mindset territory.<br /><br />Did I go up for prayer today? No.<br /><br />Why not? Because... been there done that.<br /><br />I've been in a thousand prayer lines, special services, healing meetings, Freedom Classes, Kairos, Personal Ministry sessions... Mens' meetings, Coffee Meet Ups with an older male friend... been there done that...<br /><br />As Jesus said to Mary... ONE THING IS NEEDED....<br /><br />There's nothing wrong with any of those things... they just aren't the meal. Those are the side dishes, drinks, and desert.<br /><br />The main course is, has always been, can only ever be, a living walking vibrant, two-way, on-going, relationship with Jesus through the Holy Spirit.<br /><br />I haven't just been lazy by not getting up early to spend time with Him... I've been purposefully ignoring Him.<br /><br />All the prayer lines in the world won't fix that.<br /><br /><h4>Work problems - Pray for your leaders...</h4><br />I was mad at Him because my job got hard...<br /><br />Real hard...<br /><br />Vietnam War sounds better than this hard...<br /><br />I had it great (for the first time in my life) for two years... and it all went to hell last October.<br /><br />I knew... I knew he wanted me to pray through that time. Pray for the leadership and department. In fact, I was there at JUST the right time to do that praying.<br /><br />I didn't want to. I wanted to be mad at Him for making my life HARD. I said I was mad at "leadership", whoever that nameless entity is. But I wasn't, not really, I was mad at HIM for leading me to a watering hole, then letting it dry up.<br /><br />Instead of praying... I tried to get out. But 40+ applications later without only one nibble... I guess I'm just here until I'm not.<br /><br />Maybe the sooner I get to praying for leadership, the sooner I can move on to the next thing.<br /><br /><h4>SEERS SEE</h4><br />ALL my life I <b>SEE</b>. No jest, I am a <b>SEER</b>, like the biblical kind. It's a subset of the Prophet gifting.<br /><br />I see everything, constantly, all the time.<br /><br />I walk into any business, church, organization... a person's case files or emails.... a person's story... I SEE. I see the path. I see the answers. I see the right way to handle, turn, not turn, etc.<br /><br />I get mad when I see leaders make poor decisions, or do something in a way that is ineffective when I can see (obvious to me) that there is a better way.<br /><br />But... leadership don't ask me, they just decide.<br /><br /><br /><h4>Pray for your leadership BECAUSE YOU SEE</h4><br /><br />It's only JUST fully occurred to me, tonight, that these two things went together.<br /><br />I get into situations where I feel like I should be praying for my leaders, but, I SEE what they should do and they don't, so I get mad at them.<br /><br />In fact, it is <b>BECAUSE </b>I see, that I can effectively pray for them.<br /><br />Huh?!<br /><br />I can see what they can't; therefore, I can prayer specifically and targetedly for them and their wisdom to see into the situation and make right decisions.<br /><br />Meanwhile, my seeing is getting me mad, and destroying my opportunity to pray for them (the very thing my seeing was supposed to help me do).<br /><br />The enemy knows what he's doing, that's for certain. He uses the very gift that should help me, and uses it to destroy me and my opportunity.<br /><br />I guess I've come to the end of myself.<br /><br />I give up.<br /><br />I'll start praying for my leaders at work tonight.<br /><br /><br /><br /><div><div style="text-align: center;">********</div><br /></div><div>By <a href="https://plus.google.com/+DarrellWolfe/posts">Darrell Wolfe</a>&nbsp;| #<a href="http://ctt.ec/5xc67">BeStillBeLed</a></div><div><br />Story Teller | Creative | <a href="http://www.16personalities.com/infj-personality">INFJ</a> | <a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder">Intellection</a> | Learner | Ideation | Achiever | Input | Multipotentialite<br /><br />New here?<br /><br /><ul><li><a href="http://darrellwolfe.blogspot.com/p/about-20.html" target="_blank">Start Here</a> for more information.</li><li><a href="http://darrellwolfe.blogspot.com/p/q.html" target="_blank">Ask </a>me anything</li><li><a href="http://darrellwolfe.blogspot.com/p/got-freedom.html" target="_blank">Got LIFE? Not sure, click HERE to find out.</a></li><li>See <a href="http://www.darrellwolfe.com/p/by-darrell.html" target="_blank">DarrellWolfe.com</a> for more of my sites.</li></ul><div><br /></div></div>