---
title: 'Oy vey'
date: '2016-03-08T05:01:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2045965903942042798'
blogger_filename: '/2016/03/oy-vey.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'In The Mire'
  - 'Renewing the Mind (Stinking Thinking)'
---

<br /><h3>I feel Oy Vey!</h3><br /><h4>Overwhelmed.</h4><blockquote class="tr_bq"><a href="https://en.wikipedia.org/wiki/Oy_vey">Oy vey </a>or oyvey ist mir is a Yiddish phrase expressing dismay or exasperation. Also spelled oy vay, oy veh, or oivey, and often abbreviated to oy, the expression may be translated as, "oh, woe!" or "woe is me!" Its Hebrew equivalent is oy vavoy.</blockquote><div><blockquote class="tr_bq"><a href="http://www.chabad.org/library/article_cdo/aid/699508/jewish/What-Does-Oy-Vey-Mean.htm">Oy</a> is found many times in the Bible (see <a href="http://www.chabad.org/9949#v29">Numbers 21:29</a>, <a href="http://www.chabad.org/15833#v7">I Samuel 4:7</a> and <a href="http://www.chabad.org/15934#v11">Isaiah 3:11</a> for a few examples). Vey is newer than oy; it is oy’s Aramaic equivalent.</blockquote><div><br /></div>I feel like this today. I'm forcing myself to take a lunch today. I often don't feel I can. Not because of anything a boss told me, just my own internal clock. If I have 30 things to do today, and time enough for only 5-8 of them, I feel I cannot take a break.<br /> <br /><br /><h4>Exhausted before I start.</h4><br />Hours worked never burn me out, tasks incomplete do. I could work 55 hours but keep my to-do list under the stress bar and feel invigorated. I can work 35 hours with a long to-do list that never ends, and I feel like taking a spike and driving it through my head! Figuratively... mostly.<br /> <br /><br />In fact, when work cut back on overtime (OT) because they know we're too busy, and wanted to keep us from burning out, they accidentally screwed someone like me. Someone who's to-do list is not longer without the additional OT. The shorter hours and longer to-do list are MORE stressful than longer hours and shorter to-do list.<br /> <br /><br />So much so, that only two months of this reduced OT and I'm now completely burnt out. I worked 50-55 hours for years and years... but 40-45 hour weeks have screwed me. I need to leave, run away, run screaming for the hills... at least... that's how I feel right now.<br /> <br /><br />In fact, my current mental state is so marred the hours I do work are harder than they were before. I have a harder time focusing, and I'm now looking for medication for stress. I'm starting with natural herbal remedies, but I'm considering going to the Doctor for Prozac.<br /> <br /><br />I guess in the end I shouldn't internalize the stress like this. It's their to-do list, not mine. At the end of the day, it's them, not me, who will suffer from my reduced productivity (hours and mentally).<br /> <br /><br />And it's them who have already lost me... looking for a new job. One in which my time is more my own.<br /> <br /><br />In the meantime... I forced myself to take a lunch today. I guess I'll go back at the end of my hour, and hope to focus on one thing at a time until the clock ticks over... since it's obvious my to-do list is screwed.<br /> <br /><br />Stressed! Darrell</div><div> <br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> </div>