---
title: 'Announcement: Change Complete | Evolution Begins Here'
date: '2016-05-29T08:10:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8311400901341981877'
blogger_filename: '/2016/05/announcement-change-complete-evolution.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'News & Events'
---

<br /><h4>Hello Followers,</h4><br />Many of you came to me for a variety of reasons. As a Multipotentialite I've struggled with having any real focus. I thought I could get one unifying theme for all of my writing to fit on one site... I couldn't.<br /><br />Therefore, I am separating my content, writing, studies, etc, into Niche Specific sites. This will allow me to focus on as many topics as I want to; while allowing my followers to pick from only those topics that interest them.<br /><br /><h4>New Site</h4><a href="http://www.darrellwolfe.com/p/start-here-about.html" target="_blank">DarrellWolfe.Com (HERE)</a>&nbsp;is live, and will act as my single point of entry for referred traffic. When I want to tell someone to check me out, I will hand out one card, one link, point everyone into one direction.<br /><br />I have listed all of my sites (and will continue to list others as my interests continue to expand) on The Hub page. In the future, as I publish books, videos, podcasts, and other material, DarrellWolfe.Com will be the One Stop Shop for all of my crazy ideas.<br /><br /><h4>Where's the old content?</h4>With the exception of <a href="http://bankingbasicsforbelievers.blogspot.com/" target="_blank">Banking Basics (HERE)</a>, which I've purposefully kept separate from my name (as I'm still working in that industry); I have carried through the same web template and branding elements into every site for flow and consistency.<br /><br />Make sure to check out my <a href="http://darrellwolfe.blogspot.com/p/about-20.html" target="_blank">NEW Start Here/About page (HERE)</a>... to see if this is the blog you want to continue to follow. Also check out <a href="http://www.darrellwolfe.com/p/by-darrell.html" target="_blank">The Hub</a> for all of the Niche Specific options. The main ones I will put into this post for your review.<br /><br />Thanks for your patience as I work through this change.<br /><br /><div>----</div><div><br />By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts">Darrell Wolfe</a>&nbsp;| #<a href="http://ctt.ec/5xc67">BeStillBeLed</a></div><div><br />Story Teller | Creative |&nbsp;<a href="http://www.16personalities.com/infj-personality">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder">Intellection</a>&nbsp;| Learner | Ideation | Achiever | Input | Multipotentialite<br /><br /><br /><h4>Here is a list of the Specific Sites I've created for you:</h4><br /><h4>My Blog</h4><div><ul><li><a href="http://darrellwolfe.blogspot.com/" target="_blank">Exploring LIFE, with Darrell Wolfe is my personal blog.</a></li><ul><li><i>Practical application of spiritual principles. &nbsp;</i></li><li><i>Exploring an un-complicated LIFE with God through stories, arm-chair theology, and random observations.</i></li></ul></ul><div><br /></div></div><h4>Niche Sites</h4>These are sites I built specifically with the audience in mind, in order to provide targeted information and specific topics.<br /><br /><ul><li><a href="http://bankingbasicsforbelievers.blogspot.com/" target="_blank">Banking Basics</a>&nbsp;for Believers</li><ul><li><i>Your inside information on banking, money, and finance... from one Insiders' perspective.</i></li><li><i>Telling you everything you need to know, a few things they won't tell you, and some things they don't want you to know.</i></li></ul></ul><ul><li><a href="http://toposconsulting.blogspot.com/" target="_blank">Your Topos</a></li><ul><li><i>Creating your strategic position of opportunity and influence.</i></li></ul></ul><ul><li><a href="http://thelifeinfortworth.blogspot.com/" target="_blank">The Life in Fort Worth Blog</a></li><ul><li><i>Helping you Discover, Navigate, and Enjoy Forth Worth Texas</i></li></ul></ul><ul><li><a href="http://lifefoodfunfamily.blogspot.com/" target="_blank">LIFE in Review</a></li><ul><li><i>Exploring Family, Fun, and Food (review and travel blog)</i></li></ul></ul><ul><li><a href="http://wolfeforoffice.blogspot.com/" target="_blank">Wolfe For Office</a></li><ul><li><i>Liberty, Reason, &amp; Compassion</i></li><li><i>If I were running for office... these are my thoughts and views on all things related to politics, policies, and government.</i></li></ul></ul><br /><h4>Journals</h4>These are my Web-Journals. When I study a particular topic, I like to tear it apart. I tend to loose notebooks. It's easier for me to post my studies online, then I can retrieve (&amp; search) them easily. These are not written with a reader in mind, just myself. I post them publicly for those who may find them helpful anyway.<br /><br /><br /><ul><li><a href="http://towdahaudio.blogspot.com/" target="_blank">Towdah Audio</a></li><ul><li><i>My Music and Audio journal. I've been a musician and volunteer Audio Board Technician for many years (off and on). I enjoy music and audio. This is my journal for what that mood strikes.</i></li></ul></ul><ul><li><a href="http://empoweredtooprosper.blogspot.com/" target="_blank">Empowered to Prosper</a></li><ul><li><i>My bible study journal. Unfiltered, fresh from the study room.&nbsp;</i></li><li><i>I typically only post here when I'm getting into a study, but I've always intended to use it more often.</i></li></ul></ul><ul><li><a href="http://authorfun.blogspot.com/">AuthorFun</a>&nbsp;</li><ul><li><i>My Fiction writing practice journal. I may post daily for a while, and go months without posting.&nbsp;</i></li></ul></ul><ul><li><a href="http://discerningthetime.blogspot.com/" target="_blank">Discerning The Time</a></li><ul><li><i>Studies into End Times Prophecy, and today's applications.</i></li></ul></ul><br /><div></div><br /><ul style="-webkit-text-stroke-width: 0px; color: black; font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px;"><li><a href="https://ihaveennui.wordpress.com/about/" target="_blank">I Have... Ennui</a></li><ul><li><i>One Man's Journey through the vallue of the shadow of depression...</i></li></ul></ul></div>