---
title: 'Taking the edge off'
date: '2016-02-23T13:54:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3375179167843366210'
blogger_filename: '/2016/02/taking-edge-off.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Resting'
  - 'Recovery'
  - 'In The Mire'
---

<br /><br /><h4>Today was tough.&nbsp;</h4><div>I walked up the path to the steps that lead to the entrance, and I stopped. I turned around, and looked at the beautiful day.<br /><br />Today was my favorite kind of day. A cool 52* F, overcast Grey skies, no leaves on the trees (no pollen to sneeze), birds chirping, and a hint of mist as though rain would drip at any moment. That is my favorite type of weather. I should have been born in northern Ireland, or maybe Oregon?<br /><br />Reluctantly, I headed inside. Inside is what I expected. Three days worth of work, and questions from every angle on top of it. Tomorrow three more days worth of work will get dog piled on me too, with no end in immediate sight.<br /><br />Finally, at lunch time... I decided to break away.<div><br /><blockquote class="tr_bq">A good walk, push ups, wieght lifts... takes edge off <a href="https://twitter.com/hashtag/Ennui?src=hash">#Ennui</a><br />— Darrell Wolfe (@DarrellWolfe) <a href="https://twitter.com/DarrellWolfe/status/701894575359598592">February 22, 2016</a></blockquote><br />I took a walk around the building, did some push ups on the stairs, lifted two 20 lbs weights, some leg lifts, and then headed back up the stairs to the coffin (I mean desk).<br /><br />It didn't change things 180 degrees. I didn't come back pumped, and full of life. I still felt the same as I have for many years. But maybe, just maybe, the walk made me a little lighter. I may have smiled a few more times in the last half of my day.<br /><br />I ended the day in some deep reflection about my personal life and relationship.<br /><br />On balance, I guess it wasn't my worst day this month.<br /><br />Darrell</div></div>