---
title: 'Expectations Are Premeditated Disappointments'
date: '2016-08-10T12:00:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '66063991138028369'
blogger_filename: '/2016/08/expectations-are-premeditated.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Armchair Theology'
  - 'Spiritual Growth'
---

<br />As my psychologist dad says, and I paraphrase...<br /><br /><blockquote class="tr_bq"><b>Expectations Are Premeditated Disappointments</b></blockquote><br />and...<br /><br /><blockquote class="tr_bq"><b>Plan Plans Not Outcomes</b></blockquote><br />I have had in my mind and heart a "way it's supposed to go/be", all my life.<br /><br />So far almost exactly NOTHING has every gone the way it was supposed to go, or been the way it was supposed to be.<br /><br />As it turns out, I'm a lousy planner of outcomes.<br /><br />I'm an idealist, who can tell you what the right principles are, but specific outcomes are only within God's hands, not man's.<br /><br />Maybe I do need to die after all... die to self.<br /><br />Maybe I need to die to...<br /><br /><ul><li>"I want"</li><li>"I need"</li><li>"I desire"</li></ul>... and just, simply, follow His lead.<br /><br />But if I do that, if I follow His lead, that will lead me down paths I don't want to go, into situations I don't want to be in... that will take me to a prison after being beaten (<a href="http://biblehub.com/context/acts/16-16.htm" target="_blank">Paul &amp; Silas</a>), it will get me thrown into a Lion's den (<a href="http://biblehub.com/nasb/daniel/6.htm" target="_blank">Daniel</a>)... Sure, they overcame those situations, but not without cost.<br /><br />Then again... isn't there a cost to NOT following his lead?<br /><br />By the scale of my imaginations for what my life should have been... this life has been a GRAND DISAPPOINTMENT... I imagined I'd be a Ted Dekker by now, or leading a Pixar by now, or something other than struggling to pay bills and working a 9-5.<br /><br />But this is where MY planning has gotten me.... one more promotion, one more step up the ladder... that's where my ability to plot and scheme and work my way up has gotten me.<br /><br />I'm grateful for the promotion, but I shouldn't even be here... I should be WAY up that mountain by now...<br /><br />So maybe the cost of following Him, and there IS a cost, isn't as high as the cost of not following Him (His Plan / His Leading)?<br /><br />There's a thought...<br /><br />Going to be honest, I've been frustrated with God because of my lack of progress toward those BIG dreams... so I stopped praying actively months ago. Here and there, yes, but actively (daily/more than daily) no.<br /><br /><blockquote class="tr_bq"><i>God I forgive you for not giving me what I wanted, now please show me what YOU wanted all along?</i></blockquote><br />Maybe that's a better prayer...<br /><br />Darrell<br /><br /><br /><br /><div><div style="text-align: center;">********</div><br /></div><div>By <a href="https://plus.google.com/+DarrellWolfe/posts">Darrell Wolfe</a>&nbsp;| #<a href="http://ctt.ec/5xc67">BeStillBeLed</a></div><div><br />Story Teller | Creative | <a href="http://www.16personalities.com/infj-personality">INFJ</a> | <a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder">Intellection</a> | Learner | Ideation | Achiever | Input | Multipotentialite<br /><br />New here?<br /><br /><ul><li><a href="http://darrellwolfe.blogspot.com/p/about-20.html" target="_blank">Start Here</a> for more information.</li><li><a href="http://darrellwolfe.blogspot.com/p/q.html" target="_blank">Ask </a>me anything</li><li><a href="http://darrellwolfe.blogspot.com/p/got-freedom.html" target="_blank">Got LIFE? Not sure, click HERE to find out.</a></li><li>See <a href="http://www.darrellwolfe.com/p/by-darrell.html" target="_blank">DarrellWolfe.com</a> for more of my sites.</li></ul><div><br /></div></div>