---
title: 'A question to ponder: Why am I so surprised when God comes through for me?'
date: '2016-11-27T08:51:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3071988411637592291'
blogger_filename: '/2016/11/a-question-to-ponder-why-am-i-so.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Renewing the Mind (Stinking Thinking)'
---

A year ago, or so, I had a growing idea to start a Podcast. I less-than-diligently played with my audio recording function and had nothing to say when the mic was on. My best times are discussing the things of God with others.<br /><br />So I thought... maybe I could start a Podcast with another guy or several, and talk in that format. Invite guests... but I don't know anybody I could do that with... I don't have friends... whatever...<br /><br />So then, recently, I started hanging with a group of rough and raw christian guys. The kind who are unafraid to be open and honest about their struggles and doubts; but also, their successes and triumphs.. One guy started a podcast with a group format. Where regulars and visitors can come and just talk... I joined the group...<br /><br />Then tonight it hit me... that desire from a while back just got answered. It came in a package and format I wasn't expecting and didn't recognize until the second recording was wrapped up and we were sitting at Taco Bell discussing it...<br /><br />God totally met my desire... wow...<br /><br />Then one friend said: "Why do you keep seeming so surprised by these things (God coming through)?"<br /><br />I don't know? But it really is bugging me... my whole life God comes through, and I don't know why I'm so surprised. Why don't I trust Him to do this by now?<br /><br />What things are so broken in me that I cannot believe He'll do it again, and again, and again? Why do I doubt he will THIS TIME (every time)?<br /><br />A question to ponder....<br /><br /><br />So, broken or whole, "right or wrong", that's what I'm thinking about today,<br /><br />Darrell W. <br /><br />