---
title: 'When did &quot;The Great Sadness&quot; start for me?'
date: '2016-08-07T04:51:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7519090264331221963'
blogger_filename: '/2016/08/when-did-great-sadness-start-for-me.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Renewing the Mind (Stinking Thinking)'
  - 'Resting'
  - 'Recovery'
  - 'In The Mire'
  - 'Emotions'
---

<br /><br />In&nbsp;<a href="http://amzn.to/2b43mAe" target="_blank">The Shack: Where Tragedy Confronts Eternity Paperback</a>&nbsp;(*affiliate link), Author <a href="https://smile.amazon.com/s/ref=dp_byline_sr_book_1?ie=UTF8&amp;text=William+P.+Young&amp;search-alias=books&amp;field-author=William+P.+Young&amp;sort=relevancerank">William P. Young</a>&nbsp;describes the depression that follows tragedy "The Great Sadness".<br /><br />Where did my Great Sadness start?&nbsp;<div><br /></div><div>I remember being sad all my life. I wanted to die (leave earth more specifically, I was open to an Enoch or Elijah type exit) as early as 5th grade.&nbsp;</div><div><ul><li>I guess my dad leaving the ministry to announce to the world he was an atheist was tough.</li><li>Dad leaving the house to be a crack addict was tough.</li><li>Brother dying was a relief, him leaving his daughter behind without a dad was tough.</li></ul></div><div>These all happened by the time I was grown (18+)</div><div><br /></div><div>I don't recall the year, but Uncle Glen leaving us... that was the moment my life became a tad more bitter.&nbsp;</div><div><br /></div><div>He was one of the few who could cheer me up, make me laugh, help me navigate an otherwise crazy family. I still use his handkerchief bunny and disappearing quarter tricks on kids today. And I still enjoy a good round of pool (billiards).&nbsp;</div><div><br /></div><div>When his wife Blanche died he just stopped showing up. I found out later that she was his blood tie to the family, and when she died he did not feel obligated to show up anymore. Frankly... when I got old enough neither did I. There was nothing warm and fuzzy about my family.&nbsp;</div><div><br /></div><div>I get that he didn't want to show up to family events (Christmas, Thanksgiving, etc... ) neither did I. I stopped going when I got old enough too.&nbsp;</div><div><br /></div><div>But the fact he cut ME out (my middle name was named after him).... THAT was tough. He was the closet thing I really had to someone to look up to in my family. Him and Jim.<br /><br />I felt his death when he stopped showing up (years before he eventually actually died physically). That was a loss... and a great sadness... and it felt like a betrayal.&nbsp;</div><div><br /></div><div>There was something in our relationship that felt like a promise.. a promise he broke by cutting us out...&nbsp;</div><div><br /></div><div>I guess I feel that way with God too.&nbsp;</div><div><br /></div><div>Jesus showed up in the sky when I was young, right there in front of me... if felt like a promise I couldn't quite verbalize... I had other spiritual experiences... but ultimately nothing came of any of that. I thought I found something in 2002-2004... but it came up empty too.&nbsp;</div><div><br /></div><div>My life feels like a series of broken promises... meaningless goal setting... dreams that I wished I didn't dream.</div><div><br /></div><div>I just wish I could be a "normie". Go to work, head to the bar for a few drinks with the guys, and head home to a family I enjoyed.&nbsp;</div><div><br /></div><div>I wish I wasn't irritated all the time; as though the act of being awake was itself the greatest irritation of all.<br /><br />But I am... I just... am.</div><div><br /></div><div>Glen... I forgive you for leaving me before you left the world. You did what you had to do with the end of your life. I'd probably have done the same.</div><div><br /></div><div>Jesus... You and I are stilling working this whole thing out. But I forgive you for slights that I perceived (even though I intellectually know that you've always only been there for me, I still struggle to believe that).<br /><br />You are weaving tapestry I cannot see from my perspective. Maybe I never will until I get to the other side of eternity.&nbsp;</div><div><br /></div><div>I just wish I could be the engaged, interested, 'present', joyful person everyone wants me to be... I'm a great actor... I just wish I could be who I try to be on the outside.<br /><br />Ce la vie.<br /><br />Darrell</div>