---
title: 'Provider My Ass... Part One My Question'
date: '2016-11-01T04:03:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '381724868281260801'
blogger_filename: '/2016/10/provider-my-ass.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'In The Mire'
  - 'Emotions'
---

Dear God,<br />
<br />
You want open an honest? Here it is. <br />
<br />
You suck as a provider. I've worked my ass off, two jobs for along time, then 55-hour weeks for years. I couldn't "afford" to take Paid Time Off (PTO) because it would eat into overtime. If I worked more than 40 but less than 50, that money-suck you gave me (family, house, cars, etc.) would cry out for more like a monetary black hole.<br />
<br />
We've never made ends meet. We were always short, something always went a month or two behind. We caught up, barely, with tax returns and windfalls just to get behind again. <br />
<br />
We cut everything out, all expendable expenses. We don't pay for cell phones, cable, any of it. We're still always broke. You're not my provider. You may be someone else's, but you haven't been mine.<br />
<br />
I'm tired, I'm broken, you suck! I'm just about threw with you... I'm ready to throw it all away and go live for the Devil. At least he pays his people.<br />
<br />
Darrell<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />