---
title: '*Sigh* Venting made me feel better...'
date: '2016-07-24T02:32:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2276323587481232127'
blogger_filename: '/2016/07/sigh-venting-made-me-feel-better.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'In The Mire'
---

Weeks now... I have no "get up and go". I haven't been able to focus at work or at home. I'm practically useless in both places.<br /><br />I have a few fits of mental activity &amp; acuity, usually not more than minutes at a time, followed by hours/days of *BLAH*.<br /><br />I eat but I'm not satisfied, I really just want a drink. Sober since 2002 doesn't even mean anything to me anymore. Sober why? For what? What's the point?<br /><br />Work why? To make money to pay bills to have a house so that I can eat so that I can live so that I can.. work? Vicious awful cycle.<br /><br />I show at work with a never ending to-do list that will never be under control. Leadership that doesn't listen or understand. And for what? So some spoiled idiot that didn't read their contract or understand the basics of sales negotiations, and will probably vote for Hillary or Trump, can whine in my ear?<br /><br />I want off this ride.<br /><br />....<br /><br />On the other hand...<br /><br />I enjoyed reading DB McDowell's "Girl who stole tomorrow". And I'm enjoying the prospect of writing novels myself.<br /><br />I was feeling very stuck on my current (1st) work in progress, White Noise - The Tower, until I had a realization this morning at Preston's game (which was also fun).<br /><br />It's good to learn all the rules of a craft. Then you know which ones bend and which ones break and why things aren't working when they aren't working. But eventually you have to break some of those rules.<br /><br />The Structure of a full length novel is often described as 3 Act, W Story Structure, etc. But if I'm writing short episodic fiction, the W may need to be a V.<br /><br />So I need to go back and look at the novel from that angle, and maybe move some of what I was working on to book 2.<br /><br />And that's what I'm going to do right now.<br /><br />OK... I feel a LITTLE better. <br /><br />:) Darrell<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />