---
title: 'Eradicate the word &quot;had&quot; from your writing.'
date: '2016-09-05T01:58:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3003744349883956243'
blogger_filename: '/2016/09/eradicate-word-from-your-writing_4.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Writing Practice'
  - 'Craft'
  - 'Editors Eye'
---

<br /><br />I have been writing for years, first as a hobbiest with passing intrest, then semi-professionally as a blogger, then professionally as a Complaints Reporter and Letter Writers, and now as Technical Writer working on Policy &amp; Procedure (P&amp;P). In that time, I've had the opportunity to edit other's work even more often than my own.<br /><br /><br /><br /><h4><br />Had is an easy way to clean up your manuscript</h4><br />Among the most common pitfalls I've seen, in both Nonfiction and Fiction writing, is the word "HAD". You can almost always simply delete it, and it the sentence will not only remain fully intact, but the meaning will be clearer.<br /><br /><br /><br />I notice it in my writing, in my Letter Writers, and I've seen it three times today in other authors at <a href="http://www.scribophile.com/authors/darrell-g-wolfe/" target="_blank">Scribophile</a>. Below are the works I critiqued/edited today.<br /><br /><br /><br />Both are examples of good storytelling and world building. Both have edit issues to work out to be ready for publishing.<br /><br /><br /><br />Both are examples of how incomplete craft (my own included) can be overcoming by a darn good story... and how perfecting the craft makes them that much better.<br /><br /><br /><br />I'll just pull out just a few instances of "had" from each for this post, and offer my own potential edits for them.<br /><br /><br /><br /><h4><br />Examples of "had"</h4><br /><br /><br /><a href="http://www.scribophile.com/authors/simon-anthony-marriott/works/faiths-odium/106864" target="_blank">Faiths Odium, Chapter 4: The Fat Shepherd</a><br /><br /><br /><br /><ul><br /><li>The king had used taxes to set up shelters for the homeless within the city</li><br /><li>The king used taxes to set up shelters for the homeless within the city</li><br /></ul><br /><ul><br /><li>In truth he had always rooted for the underdog and the hopeless.</li><br /><li>In truth he always rooted for the underdog and the hopeless.</li><br /></ul><br /><ul><br /><li>The disgruntled wench had a look of scorn, but offered up the axe regardless.&nbsp;</li><br /><li>The disgruntled wench scowled, but offered up the axe.&nbsp;</li><br /></ul><br /><ul><br /><li>In this instance, had is appropriately used: "Rynarr could see his tongue <b>had </b>been partially removed, a common punishment for speaking out of turn, probably ordered by a lord that thought himself above the law."</li><br /></ul><br /><br /><br /><br /><a href="http://www.scribophile.com/authors/richard-j-ford/works/fenilia/106738" target="_blank">Fenilia, Chapter 12: Chapter Twelve.</a><br /><br /><br /><br /><ul><br /><li>A blade had materialised in N’s hand before the dagger had even touched the stone.&nbsp;</li><br /><li>A blade materialised in N’s hand before the dagger even touched the stone.&nbsp;</li><br /></ul><br /><ul><br /><li>Jason had said moments before.</li><br /><li>Jason said moments before.</li><br /></ul><br /><ul><br /><li>Jade had not realised, but there were various paths leading this way and that between them and the trapdoor they had so unwittingly come through.</li><br /><li>Jade did not recognize the paths leading back to the trapdoor they unwittingly came through on their way in.</li><br /></ul><br /><ul><br /><li>In this instance, had is appropriately used: She had no choice but to increase the pace of her shuffling, whilst still making sure not to fall over.</li><br /></ul><br /><br /><br /><br /><br /><a href="https://www.wattpad.com/302447748-distortion-white-noise-episode-1-street-noise" target="_blank">Distortion</a><br /><br /><br /><br />In my own first novel (posted on Wattpad) I found several instances in the first chapter:<br /><br /><br /><br /><br /><br /><ul><br /><li>The leaves had begun to fall, most had turned shades of orange and yellow, matching perfectly the Pumpkins that had been dotting porches and windows through the city the past few weeks.</li><br /></ul><br /><ul><br /><li>The leaves began to fall, most already turning shades of orange and yellow, matching perfectly the Pumpkins that were dotting porches and windows throughout the city the past few weeks.</li><br /></ul><br /><br /><br />I hope that gives you some ideas. Look for other words you use frequently in a word count search. See if you can elimante these in your next re-write.<br /><br /><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><br /><div><br /><br /></div><br /></blockquote><br /><h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;"><br />By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4><br /><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><br /><i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote><br /><ul><br /><li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li><br /><li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li><br /><li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li><br /><li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li><br /></ul><br /><ul><br /></ul><br />