---
title: 'Getting Excited...Being Led is Premeditated Joy'
date: '2016-08-11T13:03:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5648274552803675300'
blogger_filename: '/2016/08/getting-excitedbeing-led-is.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Armchair Theology'
  - 'Spiritual Growth'
---

<h3>Getting Excited...Being Led is Premeditated Joy</h3><br />If one let's go of their pre-conceived ideas of how it was "supposed to be", and opens up their mind to the possibilities of what is, they can find elements of peace interlaced throughout the process.<br /><br />I got thrown off this week because a promotion didn't come in the package I thought it would. I got disappointed, not because it's not great, but because it didn't match the picture in my head.<br /><br />Once I took a step back, looked at all of the angles, shades, and hues... I realized that it would be a great fit for this season. It's not what I designed, but it's what I need for now.<br /><br />I've almost zero in my life come to pass the way I imagined it would be, which has led to a lot of disappointment.<br /><br />As it turns out, life is not a novel, in which you can craft the paragraphs of life to flow into a perfect seamless flow.<br /><br />Rather, life is more like a wild forest. You don't get to prune the forest, you get to walk through it and enjoy it for what it is. You get to choose which paths you walk down, not what those paths look like (or which trees, bushes, or dangers will be there).<br /><br />In this forest though, you rarely get the opportunity to walk back and take a different path. Once you choose the choice is made. So you just keep moving forward. Periodically, you will find new paths to choose from.<br /><br />You can either take that walk alone, make those choices alone, or you can acknowledge that there is an invisible Guide (<a href="http://biblehub.com/hebrew/7307.htm" target="_blank">Ruach</a>) there with you. You can enjoy the company of your guide, talk with your guide, while you journey... and when faced with options, you can ask your guide about the benefits and dangers of both paths.<br /><br />Sometimes your guide will tell you the results of both choices and tell you both are fine...<br /><br />Sometimes your guide will tell you NOT to pursue a path. But even if you do, your guide will come with you anyway...<br /><br />Take some time to thank your Ruach today.<br /><br /><br /><div><div style="text-align: center;">********</div><br /></div><div>By <a href="https://plus.google.com/+DarrellWolfe/posts">Darrell Wolfe</a>&nbsp;| #<a href="http://ctt.ec/5xc67">BeStillBeLed</a></div><div><br />Story Teller | Creative | <a href="http://www.16personalities.com/infj-personality">INFJ</a> | <a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder">Intellection</a> | Learner | Ideation | Achiever | Input | Multipotentialite<br /><br />New here?<br /><br /><ul><li><a href="http://darrellwolfe.blogspot.com/p/about-20.html" target="_blank">Start Here</a> for more information.</li><li><a href="http://darrellwolfe.blogspot.com/p/q.html" target="_blank">Ask </a>me anything</li><li><a href="http://darrellwolfe.blogspot.com/p/got-freedom.html" target="_blank">Got LIFE? Not sure, click HERE to find out.</a></li><li>See <a href="http://www.darrellwolfe.com/p/by-darrell.html" target="_blank">DarrellWolfe.com</a> for more of my sites.</li></ul><div><br /></div></div>