---
title: 'Observation: Expectations and Requirements'
date: '2016-04-06T05:18:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7225388581342146683'
blogger_filename: '/2016/04/observation-expectations-and.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Randomness'
  - 'Perspective'
  - 'Armchair Theology'
  - 'Spiritual Growth'
---

<br /><br />In&nbsp;<a href="http://amzn.to/1Mcvfn0" target="_blank">The Shack (here) </a>by Wm. Paul Young, Mack finds out that God has no expectations of him, no requirements. God fulfilled everything in Jesus.<br /><br />I had to ask myself, how often do I follow into this pattern of "Expectation". When I had my first big surrender, in 2002, I asked God "What do you want from me?!" in a very frustrated tone.<br /><br />I just now (2016) realized that He doesn't want anything from me, not really. He wants ME. Relationship with ME. He wants to experience life together, as a fluid motion. For God, it really is about the journey and not the destination.<br /><br />It's not about what I accomplished for him. There's no tasks list, to-do list, nothing I must get done before leaving earth, or be counted a failure. There are opportunities that I could miss to jump in and participate, but that's what they are, opportunities.<br /><br />I am free to put my list down, stop feeling like I'm "behind", and just live. One day, one prayer, one decision, at &nbsp;time.<br /><br />Wow!<br /><br />Darrell