---
title: 'Do you fear death?'
date: '2016-03-25T13:46:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1145600185023620609'
blogger_filename: '/2016/03/do-you-fear-death.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Renewing the Mind (Stinking Thinking)'
  - 'Resting'
  - 'Recovery'
  - 'In The Mire'
---

<br /><br />I was listening to a pastor on the radio this morning, giving his easter message. He asked "Do you fear death?" and I laughed.<br /><br />Firstly, because it reminded me of a scene from Pirates of the Caribbean: Dead Man's Chest - <a href="https://youtu.be/zo-OYwh6KHA">Davy Jones Introduction</a> (<a href="http://[youtube%3Dhttps://www.youtube.com/watch?v=zo-OYwh6KHA&amp;w=560&amp;h=315]">here</a>). Davy Jones asks "Do you fear death, boy?"<br /><div><br /></div><div><div style="text-align: center;"><iframe allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/zo-OYwh6KHA" width="560"></iframe></div></div><div><br /></div><div><br /></div><div><br /></div><div>Secondly, it's such a silly sounding question in my mind.<br /><br /><h4><b>How could ANY believer fear death?</b></h4><br />To die is to be with Jesus?<br /><br />No more questions, doubts, fears, lack, poverty, sickness or 'death' of any kind. In my mind, to fear death is an absolutely preposterous idea. In fact, it's been my single highest desire and request since at least ten years old "Please let me leave this stupid planet, and come home."<br /><br />Now pain, I fear. I don't want pain. If you told me I could have death, but it would come with pain I'd be the first to shy away from that. In fact, that is why life is what I fear, not death.<br /><br /><h4>The question should be, "Do you fear life?"</h4><br />To that I can give a resounding "YES!"<br /><br />To solve that... would be my greatest win.<br /><br />For me... life is torture. I was given a mind to understand mysteries, and a character/emotional state that shatters at a pin drop.<br /><br />I keep ending up in the same places. People impressed by my cognitive abilities, and surprised by my lack of emotional strength. What others feel is light pressure, I always perceive as torture.<br /><br />I keep ending up in human/people facing jobs, but it's human interaction that is my Achilles Heel.<br /><br />What always amazes me is the people who go on and on about how great life is... that is something I've never experienced. Why are all these people so dang happy all the time?<br /><br />It's like the rest of humanity is in on some joke, but I'm the only one in the room that speaks another language.<br /><br /><br />Darrell</div>