---
title: 'Focused Character Bio and Rough Outlines...'
date: '2016-09-24T20:00:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4780010748453079120'
blogger_filename: '/2016/09/focused-character-bio-and-rough-outlines_24.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Book Review Notes'
  - 'Craft'
  - 'Research'
---

<h3><br />...&nbsp;are crucial to have before you start, but they're not what you think they are.</h3><br /><br /><br /><blockquote class="tr_bq"><br /><b><i>Notes from Lisa Cron's <a href="http://amzn.to/2cRcwz9http://amzn.to/2cRcwz9" target="_blank">Wired for Story</a>: My notes from around page 91</i></b></blockquote><br /><br /><br /><h4><br />Focused Character Bio's to answer only TWO questions.</h4><br />Having no character bio to start is just as bad as having one that's too detailed or robust. One gives you no thread to weave into the story, no "why" or "what" to hang on to. The other gives you so many details these are still obscured.<br /><br /><br /><br />Page 91:<br /><br /><blockquote class="tr_bq"><br />That's why, when writing your protagonists' bio, the goal is to pinpoint two things: </blockquote><br /><blockquote class="tr_bq"><br />1. the event in his past that knocked his worldview out of alignment, triggering the internal issue that keeps him from achieving his goal; </blockquote><br /><blockquote class="tr_bq"><br />2. and the inception of his desire for the goal itself.&nbsp;</blockquote><br />So that's an order for<br /><br /><br /><br />1. One worldview altering event (broken soul, pain point, causing a fear) that keeps him from his inner lifelong goal. This event can happen before the story proper and we may only catch glimpses of it.It may not even be referenced&nbsp;at all, but it will weave through every action's motivation and reaction we see.<br /><br /><br /><br />2. The inception of the goal itself, prior to the worldview changing event. The goal is deeper than the fear, but the fear has him/her stunted.<br /><br /><br /><br /><h4><br />Rough Outline of the starting Why's and What's.</h4><br />Once you have:<br /><br /><br /><br />He's always wanted:<br /><br />His internal issue keeps him from attaining what he's always wanted.<br /><br /><div><br /><br /></div><br /><div><br />You then need a "situation" to put him in that will bring him to a place where what he's always wanted and his internal issue MUST be forced to battle each other within him until he's either defeated or he overcomes.</div><br /><div><br /><br /></div><br /><div><br />The story then forces him to reassess his internal worldview and his goal and find they were both off the mark.</div><br /><br /><br /><br /><br /><h4><br />Do's and Don'ts</h4><br /><br /><br /><ol><br /><li>Do keep in mind that the story is about the characters internal change from his old worldview to his new one.&nbsp;</li><br /><li>Don't be uncomfortable digging deep into your characters psyches.</li><br /><li>Don't try to write the bio well, you are looking for raw data, not pretty prose.</li><br /><li>Do write a SHORT bio for each and every character.</li><br /></ol><br /><br /><br /><br /><br />THE BEST pre-outlining work I've ever seen is in this book starting on page 95:<br /><br /><br /><br /><ul><br /><li>The Premise: "What would happen if...." Once you have that, you need to ask OK. HOW would that happen. We do that by...</li><br /><li>Asking ourselves: "Why?"</li><br /><ul><br /><li>What does she want, what is she afraid of it?</li><br /></ul><br /><li>Drill from the general to the specific. If you can't see it, it's not specific enough yet.</li><br /><ul><br /><li>What's her life like now? What's she really want? Why is she afraid of it?</li><br /><li>Are there any subplot things happening in her life that could tie into the bigger plot?</li><br /><li>What clocks can we set on timers about to go off?</li><br /></ul><br /><li>Figuring out the what.</li><br /><ul><br /><li>What would happen to put these two in the same place, each for their character's own separate reason, at the same time?</li><br /></ul><br /></ul><br /><br /><br /><h4><br /><b>A focused pre-outline</b></h4><br /><b><br /></b><br /><b>A focused outline</b> doesn't set the entire stage, every plot point, every turn. It simply lays the groundwork for who is doing what, where and why. Maybe a little how, but that comes as you write.<br /><br /><br /><br /><h4><br />The WHY</h4><br /><br /><br />It knows the (internal) end goal, the fear preventing that goal, and the question that needs an answer. The answer will be the conclusion, but you need not know the answer up front, just the question you want the answer to.<br /><br /><br /><br />If the groundwork is properly laid, the answer will be a series of events in which worthy characters are transformed.<br /><br /><br /><br /><br /><br />WHY does the premise make sense for this character? Why this person, at this time, doing this adventure? What is the internal desire and fear at war within him/her that sets them on this adventure?<br /><br /><br /><br />Specific WHY, it cannot be general. If it's too general, you can't envision it. Keep drilling down into more and more specific why's until you begin to see a story unfolding before you... THEN you start writing.<br /><br /><br /><br />Background, background, background, but only around the WHY. Favorite color, parents' names, where he went to high school are ONLY relevant if they answer the WHY behind this story. Focus only on the WHY(s) in the background and drill further and further into it until you get the clear picture.<br /><br /><br /><br /><br /><br /><h4><br />The WHAT</h4><br />The WHAT happens must have a story reason. It's very convenient for two people to end up at the same place at the same time. Each person must have their own story reason for being there, not just because the plot needs it to happen.<br /><br /><br /><br />Use the WHYs to understand their reason for doing the WHATs.<br /><br /><h4><br /><br />The story is in the specifics</h4><br /><br /><br />If we can't see it, we can't feel it. We are hard wired to ask "Is it safe, or not?" Therefore, every story is our chance to live a dangerous situation (physically, socially, emotionally dangerous, it comes in all kinds), without the actual consequences.<br /><br /><br /><br />We want to know what it FEELS like to be a:<br /><br /><br /><br /><ul><br /><li>Spy or Soldier</li><br /><li>Gangster or Mafia Boss</li><br /><li>Defuse a bomb</li><br /><li>Be in love</li><br /><li>Leave a bad relationship or find a new relationship</li><br /><li>Travel the world in search of treasure</li><br /><li>Face the school bully</li><br /><li>etc.</li><br /></ul><br /><div><br />All of this, we want to feel. We can't feel it if we can't see it. We can't see it unless we are living inside the skin&nbsp;of our protagonist. We want to live vicariously through him/her, without consequences of our own.</div><br /><div><br /><br /></div><br /><h4><br />Consider the 10,000-foot view vs the up close view.</h4><br /><blockquote class="tr_bq"><br />In October 2006, nearly six thousand people worldwide died in hurricane-induced floods.</blockquote><br /><div><br /><br /></div><br /><div><br />Does that make you feel anything? Maybe a little pity or shame (unless you were close to one of those people).&nbsp;</div><br /><div><br /><br /></div><br /><blockquote class="tr_bq"><br />A mother stands at the shoreline. She sees the wave coming, and there is nothing she can do. They cannot run in time. She holds him close, she says I'll never let you go. The wave collapses upon them, they are ripped from each other's arms. Just before she is taken down again, she sees it in his eyes "You lied, you said you wouldn't let go?!", then the water engulfs her again. She wakes on the shoreline, he is nowhere to be found. She lives with that haunting image, and comes back to this shore every year to mourn, and ask for the waves to take her instead.</blockquote><br /><div><br /><br /></div><br /><div><br />Did you feel anything more that time? Probably, because it broughtt it down to the specific, down to a one on one level.</div><br /><div><br /><br /></div><br /><div><br />That's what story must do. It's not the struggle of class warfare, it's Kevin's struggle.&nbsp;</div><br /><br /><br /><br /><br /><br /><br /><h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;"><br />By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4><br /><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><br /><i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote><br /><ul><br /><li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li><br /><li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li><br /><li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li><br /><li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li><br /></ul><br /><ul><br /></ul><br />