---
title: '&quot;Good&quot; Night?'
date: '2016-02-24T15:18:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3697433866683700320'
blogger_filename: '/2016/02/night.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'In The Mire'
---

<br /><h3>I have often wondered: Is there such a thing as a "Good" Night?</h3><br /><br />Do other human beings experience this phenomenon?<br /><br />I suppose I have. I must have, in my nearly 36 years, experienced a hand full of "Good" nights. I can't recall at the moment.<br /><br />For me, every night I've ever had, as long as I can remember, is a heavy experience. I do not want to go to bed. Going to bed would mean surrendering to tomorrow.  If I go to bed, I will sleep, and wake up, and tomorrow will be here.<br /><br />I'm not ready for tomorrow, not yet.<br /><br />Tomorrow means getting ready, going into the world to face other human beings again, and their awful emotions.<br /><br />I enjoy the idea of Spock. An alien who's race experiences emotions so deeply, that they are violent. Thus, they learn to control and suppress these emotions through Logic, defeating their only true enemy, Emotional Self.<br /><br />That's me, Spock. I have found my enemy, he stands before me in the mirror.<br /><br />Some may believe me when I try to present myself as not having emotions. Not the few who know me best, my wife for example, but some.<br /><br />But, it's not true. I have them, possibly more deeply than most (like Spock). However, I am without the ability to process them, understand them, or experience them as such.<br /><br />Maybe this is where I got my obsession with language and story.<br /><br />Language is intimately tied to experience.Particularly, self-talk.<br /><br />You may have a feeling, let's say a physical feeling like Hunger. But unless you understand that feeling, you can describe it in some basic sense, you know what to do about that feeling... you may just feel it, but not know what to do.<br /><br />You may be a baby that cries, there's thing happening to me, in my belly area. It's uncomfortable, I don't like it, what is this? Crying commences.<br /><br />But if you know it's hunger. It's a signal your body is giving you to eat. You then go, "Oh, I know this feeling. This is hunger. I will eat, and it will stop."<br /><br />That's me with emotions.<br /><br />I read one one of the many personality test sites that I've used over the years, that I am somewhat of an emotional chameleon. The description quite fit my experience well.<br /><br />Often I can look like I'm showing great empathy. I actually feel what the other person is feeling, as they are describing it. It's like "Sympathy Pains", at the emotional level. But this is only partially true.<br /><br /><br />What's really happening, is they are using language to describe a feeling/experience. I do not possess this language, so I am learning the feeling through them. I absorb their current emotional state in the process, and it overwhelms my system. Like a computer crash, I shut down.<br /><br />My shut down may simply look like a blank stare in my eye. Often though, it comes out as anger. Frustration about this feeling I'm having, it's uncomfortable, and I don't know what to do with it.<br /><br />This happens at work when there are too many tasks at once, especially when those tasks involve interaction with other human beings, and very especially when those humans are in their own hyper-emotional state.<br /><br />This happens with my wife, often. She experiences emotions so freely. She cries when she's happy, and sad. I can't tell the difference most of the time. It looks the same to me. Crying is related to pain, why would one cry when they are happy? That makes no sense to me. She has to tell me which is which, I can't tell.<br /><br />When other humans beings express emotions over a 3 (on a 1-10 scale) I get this over-load feeling, and I shut down/crash. I either stare blankly, or I get angry/frustrated. Anger and frustration, I've learned, is not the normal healthy response to someone else's sadness, apparently.<br /><br />All of that to say... Tomorrow.<br /><br />There will be tasks, humans, and emotions. I don't mind the tasks as much... the other two... Uhg. Just the thought makes me want to stay up a few more hours, delay that "tomorrow" a little longer.<br /><br />But I think I'll start getting ready for bed. It's an early day tomorrow.<br /><br />"Good" Night to you, if there is such a thing. Live long, and prosper.<br /><br />Darrell