---
title: 'Feelings: Thesaurus List'
date: '2016-10-06T01:35:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6979285714438735298'
blogger_filename: '/2016/10/feelings-thesaurus-list_5.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Writing Practice'
  - 'Feelings'
---

<br /><br /><br /><br /><br /><br /><br /><br /><a href="http://writershelpingwriters.net/2010/10/emotion-thesaurus-entry-collection-samples/" target="_blank"><strong>Emotion Thesaurus:</strong></a><br /><br /><br /><br /><strong>FEAR:</strong><br /><br /><ul><br /><li>shaking, trying not to shake</li><br /><li>a white-knuckled grip</li><br /><li>leg muscles tightening, ready to run</li><br /><li>shivery skin, crawling flesh</li><br /><li>dizziness</li><br /><li>gasping for air</li><br /><li>dry mouth</li><br /><li>crying</li><br /><li>shaking the head in denial</li><br /><li>a voice that goes shrill</li><br /><li>stuttering, mispronouncing words</li><br /><li>a compulsion to talk non-stop about anything</li><br /><li>loosening of the bladder</li><br /><li>holding back a scream or cry</li><br /><li>flinching at noises</li><br /><li>the sudden urge to flee</li><br /><li>hyper-sensitivity to touch…</li><br /><li>Stomach dropped.</li><br /><li>Hair on neck/arms raised.</li><br /><li>Sucked in air.</li><br /><li>Head moved back.</li><br /><li>Ears tingled.</li><br /><li>Queasy, nauseous, </li><br /></ul><br /><br /><br /><strong>&nbsp;PANIC:</strong><br /><br /><ul><br /><li>Uncontrolled shaking</li><br /><li>Risking a different or lesser danger in order to escape</li><br /><li>Holding oneself tight (wrapping the arms around oneself to make smaller)</li><br /><li>High tolerance to pain, not feeling/noticing injuries</li><br /><li>Increased stength, stamina</li><br /><li>Grabbing onto someone and refusing to let go</li><br /><li>Claustrophobia</li><br /><li>Anxiety attacks, pain in the chest, lungs or throat</li><br /><li>Clutching at the throat or chest</li><br /><li>Gasping for air</li><br /><li>A harried, wild appearance</li><br /><li>Thoughts that turn to death or the worst possible outcome</li><br /><li>Copious sweating</li><br /><li>Backing away in quick jerky steps</li><br /><li>Passing out from a stress overload, lack of oxygen, or both…</li><br /></ul><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><br /><div><br /><br /></div><br /></blockquote><br /><h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;"><br />By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4><br /><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><br /><i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote><br /><ul><br /><li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li><br /><li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li><br /><li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li><br /><li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li><br /></ul><br /><ul><br /></ul><br />