---
title: 'New enhancement to my LIFE verses...'
date: '2016-06-08T04:50:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3082169348962551629'
blogger_filename: '/2016/06/new-enhancement-to-my-life-verses.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Armchair Theology'
  - 'Spiritual Growth'
---

<h3>So for years know I've had certain bible verses that come up over and over and over again as it relates to my relationship with God and His calling on my life.&nbsp;</h3><div><br /></div><div>I put these verses together into a paragraph to tell my spiritual journey (past, present, and future), both to myself and to others.<br /><div><br /><h4>These have become my life verses, and guides.&nbsp;</h4><div>Here's what I already had:<br /><br /><blockquote class="tr_bq"><i>I am called to lead the Distressed, In-Debt, and Discontent (<a href="http://biblehub.com/niv/1_samuel/22.htm">1 Samuel 22:1-3</a>), into the LIFE Jesus promised (<a href="http://biblehub.com/john/10-10.htm">John 10:10</a>), by showing them how to meditate on the Word of God (<a href="http://biblehub.com/joshua/1-8.htm">Josh 1:8</a>) and by telling stories inspired by it. Stories break down the barriers between heart and mind, helping both become stronger (<a href="http://biblehub.com/niv/2_samuel/23.htm">2 Samuel 23:8</a><a href="http://www.biblestudytools.com/2-samuel/23-8.html">&nbsp;</a>&amp;&nbsp;<a href="http://biblehub.com/2_corinthians/10-4.htm">2 Cor 10:4</a>). Stories can pull down strongholds that separate our heart from God's!</i></blockquote><br /><h4>Straggler Verse:</h4><div>There is one other verse that's come up over and over in my life. It's become a guide post for me personally, but I've never quite understood how it fit into my calling.&nbsp;</div><div><br /></div><div>It was as frequent as the others, but never quite fit with the others... until today.</div><div><br /></div><div>It was the verse that helped me come to terms with the somewhat Gypsie nature of my life.</div><div><br /></div><div>You see, I am frequently moving from job to job, church to church, city to city. I switched majors throughout college, and never graduated.</div><div><br /></div><div>I was enjoying each transition and job, learning, growing. Then the time would come where that place I was in felt like it was an old shirt that didn't fit anymore. Something else would then beg my attention... and I'd move on.&nbsp;</div><div><br /></div><div>I felt like something must be wrong with me, so I had asked God if I was one of those "Church Hoppers" I hear pastors hating on.&nbsp;</div><div><br /></div><h4>Then in 2009, God gave me <a href="http://biblehub.com/context/acts/17-26.htm" target="_blank">Acts 17:26</a> to set my heart free:</h4><div><blockquote class="tr_bq"><i>26 He (GOD) made from one man every nation of mankind to live on all the face of the earth, having determined their appointed times and the boundaries of their habitation,&nbsp;</i></blockquote><div><br /></div><div>This verse set my heart free many times since then.&nbsp;</div><div><br /></div><div>I can go to a (church, job, city, friendship) with enthusiasm and vigor, stay and serve for whatever season I'm there (2 months, 5 years, whatever). When the season dries up, and a new season calls; that is normal, healthy, and wonderful for my life. God appointed each of these seasons, <b>times AND places</b> for me.</div><div><br /></div><div>This gave me freedom to move more fluidly in his plan since 2009.&nbsp;</div><div><br /></div><blockquote class="tr_bq"><b>Not only was I not moving because I was broken; rather, they were his design for me the whole time!</b></blockquote><div><br /></div><h4>But I never saw how this fit with my "calling".&nbsp;</h4></div><div><br /></div><div>Then I recently learned I'm a&nbsp;<a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: inherit;">Multipotentialite</a>, and it's normal for my tribe to move from thing to thing. In fact, that is part of our unique value contribution to the world around us. We can take a multi-discipline approach, and see things others cannot see with our diversified background.</div><div><br /></div><div><br /></div><div>Tonight I went to a class by&nbsp;<a href="http://bobhamp.com/category/foundations-of-freedom/" target="_blank">@BobHamp</a>, called&nbsp;<a href="http://tdcounseling.com/class/healing-body-soul-spirit-part-1/" target="_blank">Healing: Body, Soul, Spirit - Part 1</a>. While he was talking I had a strong sense of DejaVu. God deals with people in different ways, but for me; this has always been accompanied by a sense of prophetic timing. I've learned that when I have this feeling, I should pay extra special attention.&nbsp;</div><blockquote class="tr_bq"><i>Side Speculation: No science or scripture to back this up, but my personal opinion is that these feelings are the result of the spirit (which is timeless) catching up with the soul (mind, will, emotions) which is temporal (locked in space time). Your spirit may have been ready&nbsp;</i><i>for</i><i>&nbsp;(or even present in) this moment days or years in advance, and you are&nbsp;</i><i>now&nbsp;</i><i>just catching up in real time .</i></blockquote><div><br /></div><div>Among the many things we talked about tonight (which I will journal privately about next) Bob Hamp mentioned this life verse of mine in Acts 17.</div><div><br /></div><div>Then the Holy Spirit took me for a ride when he read past 17:26 to 17:27... I know... profound!&nbsp;</div><div><br /></div><blockquote class="tr_bq"><i>27that they would seek God, if perhaps they might grope for Him and find Him, though He is not far from each one of us;&nbsp;</i></blockquote><div><br /></div><div>Mankind was made for relationship with God. Mankind lost that relationship in the Fall. Jesus&nbsp;restored access to that relationship. The Holy Spirit's job is to help us live out of that access.</div><div><br />Everything God does in our lives is to help us find him. Like any lover, he wants to be sought after, but he also wants to be caught/found. The entire reason and purpose of his plans in our lives come down to one thing only:</div><div><br /><blockquote class="tr_bq"><b>The central passion and purpose of the human condition, is to find God. @BobHamp, Paraphrase. <a href="http://ctt.ec/2AbwX" target="_blank">Tweet This</a></b></blockquote><br />Everything comes down to that. The verse goes on to say that we are his children, and we partake of his divine nature, and we have our being In Him.</div><blockquote class="tr_bq"><i>28for in Him we live and move and exist, as even some of your own poets have said, ‘For we also are His children.’ 29“Being then the children of God, we ought not to think that the Divine Nature is like gold or silver or stone, an image formed by the art and thought of man. 30“Therefore having overlooked the times of ignorance, God is now declaring to men that all people everywhere should repent, 31because He has fixed a day in which He will judge the world in righteousness through a Man whom He has appointed, having furnished proof to all men by raising Him from the dead.”</i></blockquote><div><br /></div><h4>New Life Verse</h4><div><br /></div><div>So my life verse is no longer just Acts 17:26, it now includes 27 as well.<br /><br /><blockquote class="tr_bq"><i>We are all here on this earth at exactly the time and place we were meant to be for each season, and the purpose of our life is to seek, grope for, and find God (<a href="http://biblehub.com/context/acts/17-26.htm">Acts 17:26-27</a>); come with me and we'll do LIFE together!</i></blockquote><br /><h4>Putting it all together:</h4><blockquote class="tr_bq"><i><br />I am called to lead the Distressed, In-Debt, and Discontent (<a href="http://biblehub.com/niv/1_samuel/22.htm">1 Samuel 22:1-3</a>), into the LIFE Jesus promised (<a href="http://biblehub.com/john/10-10.htm">John 10:10</a>), by showing them how to meditate on the Word of God (<a href="http://biblehub.com/joshua/1-8.htm">Josh 1:8</a>) and by telling stories inspired by it. Stories break down the barriers between heart and mind, helping both become stronger (<a href="http://biblehub.com/niv/2_samuel/23.htm">2 Samuel 23:8</a><a href="http://www.biblestudytools.com/2-samuel/23-8.html"> </a>&amp; <a href="http://biblehub.com/2_corinthians/10-4.htm">2 Cor 10:4</a>). Stories can pull down strongholds that separate our heart from God's! We are all here on this earth at exactly the time and place we were meant to be for each season, and the purpose of our life is to seek, grope for, and find God (<a href="http://biblehub.com/context/acts/17-26.htm">Acts 17:26-27</a>); come with me and we'll do LIFE together!</i></blockquote></div></div></div></div><div><br /></div><div><br /></div><div><ul><li><b>What are your life verse, and what do they mean to you? Comment on the site, or share on social.</b></li></ul></div><div><br /></div><div><br /><div><div style="text-align: center;">********</div><br /></div><div>By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts">Darrell Wolfe</a>&nbsp;| #<a href="http://ctt.ec/5xc67">BeStillBeLed</a></div><div><br />Story Teller | Creative |&nbsp;<a href="http://www.16personalities.com/infj-personality">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder">Intellection</a>&nbsp;| Learner | Ideation | Achiever | Input | Multipotentialite<br /><br />New here?<br /><br /><ul><li><a href="http://darrellwolfe.blogspot.com/p/about-20.html" target="_blank">Start Here</a>&nbsp;for more information.</li><li><a href="http://darrellwolfe.blogspot.com/p/q.html" target="_blank">Ask&nbsp;</a>me anything</li><li><a href="http://darrellwolfe.blogspot.com/p/got-freedom.html" target="_blank">Got LIFE? Not sure, click HERE to find out.</a></li><li>See&nbsp;<a href="http://www.darrellwolfe.com/p/by-darrell.html" target="_blank">DarrellWolfe.com</a>&nbsp;for more of my sites.</li></ul><div><br /></div></div></div><div><br /></div><div><br /></div>