---
title: 'The Sons of Glory: A space series??? (working title, not final title)'
date: '2016-07-31T13:51:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7532189485179764825'
blogger_filename: '/2016/07/the-sons-of-glory-space-series-working_31.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Space'
  - 'Sons of Glory'
---

<br />The idea of What Next has always captured my imagination... God completes what he's told us about (earth 6K, tribulation/ratpure, earth 1K reign of Christ, renewed heaven and earth...)... THEN what?<div><br /><br /></div><br /><div><br />WHY are SO many people interested in space travel movies, and alien documentaries?</div><br /><div><br /><br /></div><br /><div><br />What if we ARE going to be in the stars traveling in ships to other worlds?</div><br /><div><br /><br /></div><br /><div><br />What would that look like?</div><br /><div><br /><br /></div><br /><div><br />What if the Son's of God (<a href="http://biblehub.com/esv/romans/8.htm" target="_blank">Romans 8</a>) were the Prime Race, rulers of the galaxy, but other races were just as much a part of the plan of heaven? Humans were the Levites in a galactic sense?&nbsp;</div><br /><div><br /><br /></div><br /><div><br />Other races of creation had the same struggles and rewards, same heaven and hell, but with a prime difference of not needing direct sacrifice/salvation.&nbsp;</div><br /><div><br /><br /></div><br /><div><br />Ponder::</div><br /><div><br /><br /></div><br /><div><br /><ul><br /><li>Jesus died for SIN not sins. Sins (actions) are the result of SIN (spiritual condition).&nbsp;</li><br /><li>ADAM was the first MAN, Son of God, Created in God's likeness. Angels pre-date MAN, and some of those sinned and fell, but only MAN had the right of redemption as he was a SON, created in God's image/likeness...</li><br /><li>Adam's fall ushered in SIN (the condition) and Jesus died to put SIN (the condition) to death.&nbsp;</li><br /><li>Therefore, men don't need to be saved from sins (actions) they need to be saved from SIN (the condition). Sins (actions) are a natural byproduct of their Spiritual Condition. Yes, of course, sins (actions) are covered by Jesus sacrifice, in the same way leaves are covered in the treatment of a root. But sins (actions) were not the cause of death, SIN (the condition) was.&nbsp;</li><br /><li>What IF, other races of being had SIN (the condition) and as a result sins (actions) just like humans, BUT, their condition was just as much ADAM's fault as our condition. They were subject to the condition the FirstBorn MAN created in the universe, because, he had control over the universe.&nbsp;</li><br /><li>Therefore, what IF, Jesus sacrifice treated their condition as it did ours, and they were still out there (like we are today) able to take some of the benefits of the salvation, but they are waiting for ultimate (physical) redemption?</li><br /><li>Revelations 20 mentions Satan, Death, and Hades being thrown into the lake of fire... no mention of the rest of the 1/3 of fallen angels.&nbsp;</li><br /><li>WHAT IF, when Satan, Death, and Hades falls... the rest scatter across the universe. WE (REDEEMED MAN) take out across the universe to round them up, and set the other worlds free. Angels and Redeemed Man working together on the starships.</li><br /><li>WHAT IF, those worlds knew us through visitations, visions, dreams, prophecies (all like us), but they are as we are today... in HOPE and STRUGGLE...&nbsp;</li><br /><li>What if all the other systems were aware of God's Sons, but only partially? Through prophecies and visitations like we have?&nbsp;</li><br /><li>What if they were just as torn about the meaning and purpose of life, the debates of science vs religion, desire vs virtue, etc etc...&nbsp;</li><br /><li><b>What if the other creatures were not Human, per se, but held the same/similar issues as us? Because they suffer from the same condition and actions caused by Adam, King of the Universe... some believe, some don't... man shows up in his starship... then what??????</b></li><br /></ul><br /><br /><blockquote class="tr_bq"><br /><b><i>Future Glory <a href="http://biblehub.com/esv/romans/8.htm" target="_blank">Romans 8</a></i><i><br /></i></b><i><a href="http://biblehub.com/romans/8-18.htm">18</a>For I consider that the sufferings of this present time are not worth comparing with the glory that is to be revealed to us. </i></blockquote><br />What if the things to be revealed in us are WAY more than we currently imagine? What if our immediate solar system (Sun with 8-9 planets) is just not even the TIP of the iceberg of his creation? WHY would he create so many solar systems, if we weren't supposed to go there?<br /><br /><blockquote class="tr_bq"><br /><i><a href="http://biblehub.com/romans/8-19.htm">19</a>For <b>the creation waits with eager longing for the revealing of the sons of God</b>. </i></blockquote><br />ALL creation, earth, mars, venus, other planets in the solar system....<br /><br /><blockquote class="tr_bq"><br /><i><a href="http://biblehub.com/romans/8-20.htm">20</a>For the creation was subjected to futility, not willingly, but because of <b>him who subjected</b> it, in hope <a href="http://biblehub.com/romans/8-21.htm">21</a>that the <b>creation itself will be set free from its bondage</b> to corruption and obtain the freedom of the glory of the children of God. </i></blockquote><br />What if other worlds (creation, persons, not sons) are out there waiting for Adam's curse to be lifted? Like what about the creature with the four heads in God's throne room...<br /><br /><br /><br />One time, Jesse Duplantis went to heaven, and Jesus said "There's other things... things you don't know about..." and that was it for that statement. He could have been talking about things happening on earth. But what IF he was talking about a larger creation. <br /><br /><blockquote class="tr_bq"><br /><i><a href="http://biblehub.com/romans/8-22.htm">22</a>For we know that the whole creation has been groaning together in the pains of childbirth until now. <a href="http://biblehub.com/romans/8-23.htm">23</a>And not only the creation, but we ourselves, who have the firstfruits of the Spirit, groan inwardly as we wait eagerly for adoption as sons, the redemption of our bodies. </i></blockquote><br />We ALL groan for the redemption of the Sons of God in body, physically redeemed bodies and planet.<br /><br /><blockquote class="tr_bq"><br /><i><a href="http://biblehub.com/romans/8-24.htm">24</a>For in this hope we were saved. Now hope that is seen is not hope. For who hopes for what he sees? <a href="http://biblehub.com/romans/8-25.htm">25</a>But if we hope for what we do not see, we wait for it with patience.&nbsp;</i><i><a href="http://biblehub.com/romans/8-26.htm">26</a>Likewise the Spirit helps us in our weakness. For we do not know what to pray for as we ought, but the Spirit himself intercedes for us with groanings too deep for words. <a href="http://biblehub.com/romans/8-27.htm">27</a>And he who searches hearts knows what is the mind of the Spirit, because<a href="http://biblehub.com/esv/romans/8.htm#footnotes">g</a> the Spirit intercedes for the saints according to the will of God. <a href="http://biblehub.com/romans/8-28.htm">28</a>And we know that for those who love God all things work together for good,<a href="http://biblehub.com/esv/romans/8.htm#footnotes">h</a> for those who are called according to his purpose. </i></blockquote><br />&nbsp;Tongues is a needed gift for helping us speak to other beings/races/creatures. What if the FULL manifestation of tongues is our innate ability to understand and speak all language, because it all comes from HIM anyway?<br /><br /><blockquote class="tr_bq"><br /><i><a href="http://biblehub.com/romans/8-29.htm">29</a>For those whom he foreknew he also predestined to be conformed to the image of his Son, in order that he might be the firstborn among many brothers. <a href="http://biblehub.com/romans/8-30.htm">30</a>And those whom he predestined he also called, and those whom he called he also justified, and those whom he justified he also glorified.</i></blockquote><br /><div><br />The Sons of Glory: A space series???</div><br /><div><br /><br /></div><br /><br /><br /><h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;"><br />By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4><br /><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><br /><i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote><br /><ul><br /><li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li><br /><li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li><br /><li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li><br /><li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li><br /></ul><br /><ul><br /></ul><br /></div><br />