---
title: 'Processesing my time with Dr. Bob - Session #3'
date: '2016-12-02T03:34:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2184377051108556580'
blogger_filename: '/2016/12/processesing-my-time-with-dr-bob_1.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Renewing the Mind (Stinking Thinking)'
  - 'In The Mire'
  - 'Resting'
  - 'Recovery'
  - 'Emotions'
  - 'Freedom/Kairos'
---

<br /><strong>Music</strong><br /><br />We talked about how music has been a recurring love/hate music pattern for me. How every time I settle down just a little, God whispers music back into my life. I reluctantly agree, instruments flood to me. I finally realized last week that maybe God was just trying to get me to "play".<br /><br />He suggested, that maybe switching things up (learning new techniques, styles, just playing with sounds without regard to technique, play with open tuning because it forces you out of the grooves and patterns you know) all may re-engage my right brain (emotional/creative) side. Music could really be the avenue through which I could gain access to the rest of myself.<br /><br />He let me know about <a href="http://tommyemmanuel.com/" target="_blank">Tommy Emmanuel</a>, and Martin XXX?, two men who were known Thumb Technics. Afterward I found this: <a href="https://www.youtube.com/watch?v=ENJuNCkPfx0" target="_blank">My Life As A One-Man Band | Tommy Emmanuel | TEDxMelbourne</a>. <a href="https://www.youtube.com/watch?v=i3ZMoymgqbU" target="_blank">Chet Atkins</a> inspired Tommy Emmanuel.&nbsp;It reminded me that I also wanted to learn more about playing <a href="https://www.youtube.com/watch?v=_uXZiDNw51w" target="_blank">BB King</a> stuff. <br /><strong></strong><br /><strong>Legitimate Needs</strong><br /><br />Addiction and broken behaviors can be an attempt to meet legitimate needs through counterfeits. The key is to learn what those legitimate needs are, and find ways to meet them legitimately. <br /><br />Some of the needs we identified, are Nurture, Validation/Value, Connection, See Me... Can you get access to those Right Brain parts without another human/addiction taking you there? Can you can access to them on your own? Music may be an avenue through which I could gain access to a side of me that has long been locked away.<br /><br /><strong>Central Processing Units (CPU)</strong><br /><br />The human heart is a CPU. CPUs are designed to have flow going in and getting processed and going out. They are not designed to retain or hold. <br /><br />By shutting off Right Brain emotions, it creates a glut/backup in the CPU; which prevents the flow in and out.<br /><br /><br />So, broken or whole, "right or wrong", that's what I'm thinking about today,<br /><br />Darrell W. <br /><br />