---
title: 'First round of critiques for Distortion Scene 1 "Street Noise"'
date: '2016-09-18T05:30:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2976117677770502346'
blogger_filename: '/2016/09/first-round-of-critiques-for-distortion.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'News & Updates'
---

One of the scariest things for most authors (especially fiction authors) to do is open their work to the blatant critique of others. The author got to know their work so well, they know the backstory (that never made it onto the page), etc.<br />
<br />
<br />
This very intimacy makes them blind to the things the reader sees immediately.<br />
<br />
<blockquote class="tr_bq">
<a href="http://www.writersdigest.com/writing-articles/by-writing-goal/write-first-chapter-get-started/get-messy-with-your-first-draft">As Ernest Hemingway famously said, “The first draft of anything is *crap.”</a></blockquote>
<br />
I put out the 1st scene of Distortion, "Street Noise", for a writers critique. It was quite illuminating. I chose not to take it personally but learn from each point. Some things I agreed with, some I didn't. Some were clear craft mistakes while others were stylistic choices I could take or leave.<br />
<br />
I have a feeling that my re-write will be so much better due to this experience. I also found a critique buddy (Hey Ashleigh!) who I can work with as I go through re-writes.<br />
<br />
Distortion Scene 1 "Street Noise" can be read in its current form (as of today) in the second draft on my <a href="http://authorfun.blogspot.com/2016/08/white-noise-distortion-second-draft.html">It's Author Fun website (here)</a>. That was you can see what the original looks like if you'd like to read it before you read the critiques.<br />
<br />
Here was the feedback:<br />
<br />
<ul>
<li><a href="http://authorfun.blogspot.com/2016/09/distortion-critique-1.html">Crit 1 (Summary Crit)</a></li>
<li><a href="http://authorfun.blogspot.com/2016/09/distortion-critique-2.html">Crit 2 (Line by line crit)</a></li>
<li><a href="http://authorfun.blogspot.com/2016/09/distortion-critique-3.html">Crit 3 (Line by line crit)</a></li>
<li><a href="http://authorfun.blogspot.com/2016/09/distortion-critique-4.html">Crit 4 (Line by line crit)</a></li>
<li><a href="http://authorfun.blogspot.com/2016/09/distortion-critique-5.html">Crit 5 (Line by line crit)</a></li>
</ul>
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;"><br /></span></div>
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Story Teller | <a href="https://www.16personalities.com/infj-personality">INFJ</a> | Futuristic | Intellection | Learner | Ideation | Achiever | Command | Input | Focus | <a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en">Multipotentialite</a></span></div>
<div class="MsoNormal">
<br /></div>
