---
title: 'Time Travel Theories'
date: '2016-08-08T06:37:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2468295981907737364'
blogger_filename: '/2016/08/time-travel-theories_7.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Research'
---

<br /><br />Time Travel Theories<br /><br /><br /><br />There are many ideas about what time travel would look like.<br /><br /><br /><br />I see time as the fourth dimension. We exist in and can manipulate 3 dimensions (height, width, depth - a box we call space/planet/earth). We are trapped inside time. We cannot manipulate that final layer. We are four dimensional, trapped by the fourth.<br /><br /><br /><br />Theoretically, traveling faster than light would put you outside space/time. But GOD IS LIGHT... he's not just faster than light, the stuff literally emanates from him. GOD is outside the space/time condition.<br /><br /><br /><br />God doesn't just see the future and past, he is PRESENT in the past, the future, the now, all at the same time. He can spend thousands of years talking with you about turtles, and never miss one second of anyone else's life.<br /><br /><br /><br />WHAT would happen if YOU could go backward in time? There are theories of time travel:<br /><br /><br /><br /><br /><br /><ol><br /><li>You could only go back as your consciousness in your own younger body (wolverine in Days of Future Past). I try to go back further than 1980, and it doesn't work.&nbsp;</li><br /><li>You can go, but only as an invisible observer. Actions past are fixed and cannot be changed or interacted with. Think of it as High Def TV. You can watch, but that's it.</li><br /><li>You can go, and affect the time, but that creates a second timeline. The original stays in tact, a second one comes off of that one forming a new timeline, parallel but different from the first. In this version, you can kill your younger self, but still live because THAT you didn't grow up to come back, the OTHER you from the OTHER timeline did.</li><br /><li>You can go, and affect the time, but there is ONLY one timeline... so you kill you, and you cease to exist, but then... you couldn't grow up to go back and kill you... so... do you still die? That one is freaky... The universe could implode in this version.</li><br /><ol><br /><li>&nbsp;Can you go back in time to become your own great-grandfather? That would be weird....&nbsp;</li><br /></ol><br /><li>I'm sure there's other ideas... Imagine the possibilities</li><br /></ol><br /><br /><br /><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><br /><div><br /><br /></div><br /></blockquote><br /><h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;"><br />By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4><br /><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><br /><i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote><br /><ul><br /><li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li><br /><li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li><br /><li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li><br /><li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li><br /></ul><br /><ul><br /></ul><br />