---
title: 'Addiction sucks - Dr. Pepper is just as dangerous as alcohol'
date: '2016-10-24T12:36:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2018230817190262600'
blogger_filename: '/2016/10/addiction-sucks-dr-pepper-is-just-as.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Recovery'
  - 'Emotions'
---

<br />Addiction sucks because of what it's a fight with your own body and mind. The substance of your addiction is irrelevant - the behavior patterns/thought patterns are the same. I've gone through the same patterns with Dr. Pepper as I ever did with Alcohol, Pornography, PillPopping...<br /><br />I had one guy in an online AA meeting try to tell me it was rude to compare Dr. Pepper or Chocolate to more serious addictions.As I see it, it's just as dangerous.<br /><br />Some of the things I've done for Dr. Pepper:<br /><br /><b>Tend to dangerous excess</b> - &nbsp;I'm an addict by personality. I tend toward excess in everything I do. I once had such a craving for Dr. Pepper that I bought a 36 pack on a Sunday afternoon and with the exception of 5-6 to the family drank 30 between Sunday evening and Thursday morning. I had an onset of gout by Friday that lasted two weeks. That was one incident. What if I did those same things over and over and died by 38? Would that be any less dangerous that Alcohol?<br /><br /><b>Hiding the purchase</b> - Even though we were on a "budget" and I knew money was tight, I'd go to a gas station and instead of paying at the pump I'd buy a large soda, some food, and put what I figured the tank needed in gas. I'd pay for it inside so it was one purchase. I really enjoyed over-guessing so I could get change back and use it for more soda later in the day.<br /><br /><b>Hiding the evidence</b> - I'd make sure any trash, wrappings, cans, or evidence of the purchases was tossed before getting home.<br /><br /><b>Be self-focused</b> - all of that behavior was about me. It didn't matter if I was literally cutting the grocery budget down for the wife and kids. It didn't matter is they got to enjoy any of the snacks (which they all do too). I wanted what I wanted and I wanted it right now!<br /><br /><b>Financial failure </b>- you could say that the hurt to them was minor in comparison, but is reducing the grocery budget secretly really minor? If she has to pull mortgage payment money to pay for groceries because I do these things so often without her and then when I'm with her I beg for more purchases and she gives in to make me happy and we end up behind on the house payment every month.... is that really minor?<br /><br /><b>Shame/Guilt</b> - I feel powerless before the desire, give in and do it, then feel guilty afterward.<br /><br /><b>Anger/Irritability</b> - the only reason she gives in when we are out and about, even though we're broke, is because I get angry, depressed, frustrated, irritable, mean, and then silent when I can't buy what food/snacks/drinks I want and when. "We need to pay for (insert bill here) and probably shouldn't do that right now," is enough to send me into a full emotional tailspin... which usually get's me to jump tracks and start thinking about the stronger addictions and running back to those.<br /><br /><b>In my more rational moments</b>, this all sounds INSANE of course. Dr. Pepper cannot have that much control over your life, can it? But it's not just Dr. Pepper. I do it with Cheeseburgers, or really any opportunity to eat out. And it's come to a point where I think I either need to increase income or reduce expenditures to feed the desire to eat-out whenever I want.<br /><br />I can either get a second job, or start a side business, or freelance to earn more.... or I can? There's nothing left to reduce. We've cut out every expense most people pay for, and we're still broke.<br /><br />I may be what the AA folks call a "Dry Drunk", meaning that I don't have alcohol but I'm acting like I do.<br /><br />And in fact, my mind goes back to alcohol, pills, and more often. I find myself staring at it at the grocery store like it's a life-saving blood transfusion and all I need to do is insert it into my body and I'll be revived.<br /><br />So you ask, can Dr. Pepper really be as bad as alcohol? The substance? No. The bent/broken personality built around it? Yes, absolutely.<br /><br />DarrellW