---
title: 'Pressure!'
date: '2016-02-26T10:13:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6438709814533216166'
blogger_filename: '/2016/02/pressure.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'In The Mire'
---

<h3>Squeeze, strain, burden, tension, compressing, crushing, encumbrance, heaviness, load... &nbsp;PRESSURE!</h3><div><br /><blockquote class="tr_bq">pres·sure [ˈpreSHər] NOUN<br /><ul><li><i>the continuous physical force exerted on or against an object by something in contact with it:</i></li><li><i>"the slight extra pressure he applied to her hand"</i></li><li><i>the use of persuasion, influence, or intimidation to make someone do something:</i></li><li><i>"the proposals put pressure on Britain to drop its demand"</i></li></ul></blockquote><br />Not by be confused with:</div><div><br /></div><blockquote class="tr_bq"><i>Peace</i><br /><ul><i><li><i>relaxation, ease, peace</i></li></i></ul></blockquote><div><br /><h4><b>People pressure</b></h4></div><div><br />There are so many people in this world. Customer people. Co-Worker people. Boss people. Family people. Drivers sharing the road people.</div><div><br />They all come with their emotional deposit, to place in me.</div><div><br />Every human interaction comes with an expectation or "proper" behavior, thoughts, feelings. Why can't my "feelings" today be strongly for something, and be strongly against the same thing tomorrow?</div><div><br />Why would you hold me to what I said yesterday? I don't remember what I said yesterday, this is what I'm saying today.</div><div><br /><h4>Task pressure</h4></div><div><br />I guess it's the Genesis 3 curse, thorns and thistles, with the sweat of your brow you will bring forth food from the land.</div><div><br />Everywhere I go, it's "do more with less".</div><div><br />You do a great job, how about we increase your work load 430%, but please keep the same quality and consistency.</div><div><br />While you're at it, everyone else's work load increased by that much too, but they are less capable of handling it than you, so help them too will ya?</div><div><br />Don't be late on anything. We just can't imagine why this is bothering you so much?</div><div><br />WT?!</div><div><br /><h4>Planet pressure</h4></div><div><br />I hate the human body. The entire experience of pleasure and pain is incomprehensible to me. If I had the opportunity to feel no pain, but the cost was no pleasure either, I would take it in a heart beat.</div><div><br />And what's with hunger and taste? Why can't everything taste the same and bring no pleasure, then I could eat only what I need and not what I don't, and I would have no PRESSURE to do otherwise.<br />Make me a machine, PLEASE make me a machine.</div><div><br /><blockquote class="tr_bq">"Earth? What a terrible name for a planet, Earth. You may as well call it dirt. Planet dirt." <a href="https://www.youtube.com/watch?v=C7rw9SFsQ_I" target="_blank">Jetfire, Transformers.</a></blockquote><br /><div style="text-align: center;"><iframe allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/C7rw9SFsQ_I" width="420"></iframe></div></div><div><br /><br />When I come into work and see more work than I can handle, why does it make me panic inside?<br />When someone displays emotions in my presence, why does it give me the same feeling?Both require only one answer, escape.<br /><br />This is especially true when they are combined into one thing. The overwhelming amount of tasks, are combined with people interactions. The combination of the two is insanity.<br /><br />I lived in a car for six months (2006), and it didn't make me want to go back to drinking (sober since Jan 2002).<br /><br />I work 4 months of 430% work load, that comes with 430% increase in people interactions, and I'm ready to not just fall off the sobriety wagon, but go running and screaming headlong into the ocean of it!<br /><br />I go through each day, trying to remember WHY. Why would someone choose sobriety? Why did I? Why would I face other human beings without a chemical buffer between them and I? I can't recall...<br />I think I feel better now that I vented. Only a little, but a little is better than nothing.<br /><br />Incremental wins.<br /><br />Darrell</div>