---
title: 'Righteousness vs Salvation | Being Right with God, and being Saved are not the same...'
date: '2016-06-10T13:14:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2289997243597192189'
blogger_filename: '/2016/06/righteousness-vs-salvation-being-right.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Armchair Theology'
  - 'Spiritual Growth'
---

<h3><b>Righteousness</b>&nbsp;vs Salvation</h3><br /><blockquote class="tr_bq"><i><a href="http://biblehub.com/romans/10-10.htm">10</a>For with the <b>heart </b>man believeth unto <b>righteousness</b>; and with the <b>mouth </b>confession is made unto <b>salvation</b>. <a href="http://biblehub.com/kjv/romans/10.htm" target="_blank">Romans 10</a> | King James Bible</i></blockquote><br /><b>A deeper look (<a href="http://biblehub.com/interlinear/romans/10-10.htm" target="_blank">here</a>):</b><br /><blockquote class="tr_bq">dikaiosynē |&nbsp;<a href="http://biblehub.com/greek/1343.htm">1343</a><span style="color: black;">&nbsp;</span><a href="http://biblehub.com/greek/strongs_1343.htm">[e]</a>δικαιοσύνῃ |&nbsp;<b>righteousness</b><b>Short Definition</b>: justice, justness, righteousness<br /><b>My Definition: Be Right With God</b>&nbsp;</blockquote><blockquote class="tr_bq">sōtērian |&nbsp;<a href="http://biblehub.com/greek/4991.htm">4991</a>&nbsp;<a href="http://biblehub.com/greek/strongs_4991.htm">[e]</a>σωτηρίαν |&nbsp;<b>salvation</b><br /><b>Short Definition</b>: salvation, welfare, prosperity, deliverance, preservation, salvation, safety.<br /><b>My Definition: Whole, Restored to Pre-Fall State</b></blockquote><br /><h4>Right vs Saved</h4>Being <b>Right</b> with God, and being <b>Saved </b>are two different but inter-dependent concepts.<br /><br /><ul><li>Right-ness is the legal/positional state of being.</li></ul><ul><li>Saved is the outward manifestation(s) of that right state of being.</li></ul><br /><br />I am right with God by believing in and on the finished work of His Son, Jesus Christ. That is it. That is all there is to it. There is no work left. If I believe, I am made Right-With-God (<i>righteous</i>)<br /><br />I experience the effects of that Rightness by opening my mouth, and speaking the things in my heart.<br /><br />So once I believe that Jesus paid the forever price to my sin, I open my mouth and tell him. I am saved from sin.<br /><br /><br /><h4>Salvation's Manifestations</h4>However, Salvation is more than just freedom from sin. It is healing, wholeness, provision, sound mind, a total restoration of the Pre-Fall State.<br /><br />Why am I not experiencing that? Because we still live in the fallen world. The final and total restoration will come at the end of all things. But we can experience degrees of this state now, here, on this earth.<br /><br />And the degrees will be dependent on our believing and saying.<br /><br /><br /><h4><b>Mind vs Heart</b></h4>I cannot get there on my own. For all the good <a href="https://en.wikipedia.org/wiki/Christian_apologetics" target="_blank">Christian Apologetics</a> has done to strengthen believers, it cannot change the heart of an unbeliever.<br /><br />It is possible that, through the course of tearing down mental walls, truth can reach the heart through this reasoned approach, but it cannot change the heart on its own.<br /><br />So I can know (in my mind) that the bible says healing belongs to me as His child, but still struggle with my heart.<br /><br />Because faith doesn't come by reading and passing a test.<br /><br /><h4>Convinced</h4>Once I believe at the heart level, I open my mouth and effortlessly say what is on my heart (<a href="http://biblehub.com/luke/6-45.htm" target="_blank">Luke 6:45</a>).<br /><br />This is part of the reason more healings and miracles occur over-seas than in the USA. We are so full of "teaching", our mind is so full of theological positions (some God's some just Man's), that our heart is cut off from the process much of the time.<br /><br />As we discussed the other day (<a href="http://darrellwolfe.blogspot.com/2016/06/faith-you-keep-using-this-word-i-do-not.html" target="_blank">here</a>), Faith comes by hearing the voice of God.<br /><br /><blockquote class="tr_bq"><i>So faith comes from hearing, and hearing through the word of Christ.<a href="http://biblehub.com/esv/romans/10.htm">English Standard Version</a> |Romans 10:17</i></blockquote><br />So the trick is to convince the heart... that can only come from spending time with the One...<br /><br />You cannot hear Him speak to your heart, if you are not listening...<br /><br />Spend some time listening today.<br /><br />#BeStillBeLed<br /><br /><br /><br /><div><div style="text-align: center;">********</div><br /></div><div>By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts">Darrell Wolfe</a>&nbsp;| #<a href="http://ctt.ec/5xc67">BeStillBeLed</a></div><div><br />Story Teller | Creative |&nbsp;<a href="http://www.16personalities.com/infj-personality">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder">Intellection</a>&nbsp;| Learner | Ideation | Achiever | Input | Multipotentialite<br /><br />New here?<br /><br /><ul><li><a href="http://darrellwolfe.blogspot.com/p/about-20.html" target="_blank">Start Here</a>&nbsp;for more information.</li><li><a href="http://darrellwolfe.blogspot.com/p/q.html" target="_blank">Ask&nbsp;</a>me anything</li><li><a href="http://darrellwolfe.blogspot.com/p/got-freedom.html" target="_blank">Got LIFE? Not sure, click HERE to find out.</a></li><li>See&nbsp;<a href="http://www.darrellwolfe.com/p/by-darrell.html" target="_blank">DarrellWolfe.com</a>&nbsp;for more of my sites.</li></ul><div><br /></div></div><div><br /></div>