---
title: 'The Word &amp; The Spirit - Life &amp; Death'
date: '2016-11-27T06:53:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2069246987174581392'
blogger_filename: '/2016/11/the-word-spirit-life-death.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Armchair Theology'
  - 'Spiritual Growth'
---

<br /><h3>In Acts 2:41, three thousand were saved.&nbsp;</h3><br />It was asked in a meetings recently if this was circling back to an earlier scripture parallel. It does, and here is the backstory:<br /><br /><br />After Abraham had kids who had kids who had kids… over time… a nation arose within the land of Egypt. They were called The Children of Israel (Abraham’s grand-kid Jacob was renamed Israel, these were his offspring). They came to Egypt when Jacob/Israel was still alive and his son Joseph helped deliver them and the nation of from a famine. As they stayed there over 430 years they grew to a nation but also became slaves.<br /><br />Moses was called to set the nation of Israel free from Egypt, and this is the first time the distinct “Nation of Israel” was birthed. Prior to this, they were a people within a people. So just as Abraham was called “out from his people”, so this nation within a nation was called out to become its own nation. God was doing on a national level the same thing he’d done on an individual level some 500 years before.<br /><br />They were birthed through miracles, passed through the red sea, and Moses left them to go up to the mountain to talk to the God who’d delivered them. However, they had just spend 430 years worth of generations in the land, culture, traditions, and mindsets of Egypt (spiritually = The World). Those old mindsets were ingrained in them.<br /><br />When Moses stayed up there over 40 days (over a month) they began to think he wasn’t coming back. So they begged Aaron to make them a god of gold to worship. This is the mindset/culture that they’d just come from just a few months before. They sinned by doing this, rejected The God for a smaller god they could understand.<br /><br />Now, Moses was on that mountain receiving the Word of God. God literally hand wrote the commandments on tablets for Moses to bring to the people. That was interrupted when God told Moses what they’d done, and threatened to kill them all and start over creating a nation from Moses’s kids. Moses pleaded with Him not to, and went down to the people.<br /><br />But when Moses got to the camp, he became so angry that he threw the tablets down and broke them. He then got so mad at what he saw that he had the priests go through the camp and kill the people involved in this treachery and 3,000.00 people were killed the same day the Word of God was supposed<br /><br />Hear this::<br /><br /><br /><ul><li><b>The same day the WORD was to be delivered, 3,000 people died from their SIN.</b></li></ul><ul><li><b>In Acts 2, The same day the SPIRIT of God was delivered to mankind, 3,000 people were saved from their SIN.</b></li></ul><br /><br />The Word (laws to obey/good deeds) without the Spirit (living power to become a new creation) brings death, but the Word (living an active) through the Spirit (activating force) brings LIFE.<br /><br /><b>You cannot live by the Word without the Spirit.</b><br /><br /><br /><br /><div><div style="text-align: center;">********</div><br /></div><div>By <a href="https://plus.google.com/+DarrellWolfe/posts">Darrell Wolfe</a>&nbsp;| #<a href="http://ctt.ec/5xc67">BeStillBeLed</a></div><div><br />Story Teller | Creative | <a href="http://www.16personalities.com/infj-personality">INFJ</a> | <a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder">Intellection</a> | Learner | Ideation | Achiever | Input | Multipotentialite<br /><br />New here?<br /><br /><ul><li><a href="http://darrellwolfe.blogspot.com/p/about-20.html" target="_blank">Start Here</a> for more information.</li><li><a href="http://darrellwolfe.blogspot.com/p/q.html" target="_blank">Ask </a>me anything</li><li><a href="http://darrellwolfe.blogspot.com/p/got-freedom.html" target="_blank">Got LIFE? Not sure, click HERE to find out.</a></li><li>See <a href="http://www.darrellwolfe.com/p/by-darrell.html" target="_blank">DarrellWolfe.com</a> for more of my sites.</li></ul><div><br /></div></div>