---
title: 'It&#39;s so easy to do things your own way...'
date: '2016-06-09T13:15:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8756354995157532945'
blogger_filename: '/2016/06/it-so-easy-to-do-things-your-own-way_9.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Armchair Theology'
  - 'Spiritual Growth'
---

<h3>... plotting, scheming, planning, working the plan, just trying to get this thing to work.</h3><div><br /></div><h4>Submit to God’s righteousness</h4><blockquote class="tr_bq"><i><a href="http://biblehub.com/romans/10-2.htm">2</a>For I bear them witness that they have a zeal for God, but not according to knowledge.&nbsp;<a href="http://biblehub.com/romans/10-3.htm">3</a>For,&nbsp;<b>being ignorant of the righteousness of God</b>, and&nbsp;<b>seeking to establish their own</b>, they did not&nbsp;<b>submit to God’s righteousness</b>. |&nbsp;<a href="http://biblehub.com/esv/romans/10.htm" target="_blank">Romans 10</a>&nbsp;| English Standard Version</i></blockquote><blockquote class="tr_bq">...being&nbsp;<b>ignorant&nbsp;</b>of the righteousness of God (God's ways of doing and being)...</blockquote><div><br /></div><b>Defined (<a href="http://biblehub.com/interlinear/romans/10-3.htm" target="_blank">here</a>):</b><br /><blockquote class="tr_bq">dikaiosynē |&nbsp;<a href="http://biblehub.com/greek/1343.htm">1343</a><span style="color: black;">&nbsp;</span><a href="http://biblehub.com/greek/strongs_1343.htm">[e]</a><br />δικαιοσύνῃ |&nbsp;<b>righteousness</b><br /><b>Short Definition</b>: justice, justness, righteousness<br /><b>My Definition: Be Right With God</b></blockquote><blockquote class="tr_bq">hypetagēsan |&nbsp;<a href="http://biblehub.com/greek/5293.htm">5293</a><span style="color: black;">&nbsp;</span><a href="http://biblehub.com/greek/strongs_5293.htm">[e]</a><br />ὑπετάγησαν |&nbsp;<b>they submitted<br />Short Definition</b>: I place under, subject to<br /><b>My Definition: Hand It Over</b></blockquote><br />If I submit a report to my teacher/boss, I am handing it over to them. I may have a memory of it (a copy) but the report has been turned over. I'm not working on it still, I'm done with it.<br /><div><br /></div><div>If I submit a form online, it's gone. I can fill out a new one, but that form is handed over.<br /><div><br /></div><div>Seeking to establish your own will/plan does not leave room for God's. You can always bring Him your hurts, pains, problems, questions... He's happy to hear you.</div><div><br /></div><div>However, what you cannot do is come to God with a list of demands (your will), ask Him to bless them (so-called prayer), and then leave to go about your day. This is not prayer, this is submitting your list.</div><div><br /></div><div>Being right with God could also be understood to mean being in step with Him. In that sense, I cannot be right if I'm not listening. If I'm turning myself, my situation, my problem to Him, then I'm following not leading.&nbsp;</div><div><br /></div><div>So next time I pray, instead of bringing a list of demands, why don't I ask Him what He'd like to talk about today... and just Listen.&nbsp;</div><div><br /></div><div><br />Commercial Disclosures:<br /><blockquote class="tr_bq"><i><b>Warning</b>: You may want to talk about your perceived problem, and he wants to talk about something seemingly unrelated. He may choose to deal with your problem without your help, while He has you dealing with something totally different. He may choose to fix the root cause of the problem, so that the problem stops recurring. He may want to fix your heart so that the "problem" stays, but your experience changes. Side effects may include peace, joy, reduced anxiety, surprising events, and adventures. Some people have found their desires changed, while the problem still persisted. Some people have found the problem went away, seemingly on its own. Your results may vary.</i></blockquote><br /><br /><div><div style="text-align: center;">********</div><br /></div><div>By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts">Darrell Wolfe</a>&nbsp;| #<a href="http://ctt.ec/5xc67">BeStillBeLed</a></div><div><br />Story Teller | Creative |&nbsp;<a href="http://www.16personalities.com/infj-personality">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder">Intellection</a>&nbsp;| Learner | Ideation | Achiever | Input | Multipotentialite<br /><br />New here?<br /><br /><ul><li><a href="http://darrellwolfe.blogspot.com/p/about-20.html" target="_blank">Start Here</a>&nbsp;for more information.</li><li><a href="http://darrellwolfe.blogspot.com/p/q.html" target="_blank">Ask&nbsp;</a>me anything</li><li><a href="http://darrellwolfe.blogspot.com/p/got-freedom.html" target="_blank">Got LIFE? Not sure, click HERE to find out.</a></li><li>See&nbsp;<a href="http://www.darrellwolfe.com/p/by-darrell.html" target="_blank">DarrellWolfe.com</a>&nbsp;for more of my sites.</li></ul><div><br /></div></div></div></div>