---
title: 'Dishes make my want to cry or scream, depending on the day.'
date: '2016-02-21T02:37:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3268931009392387588'
blogger_filename: '/2016/02/dishes-make-my-want-to-cry-or-scream.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'In The Mire'
---

<br /><h4>I can tell my emotional state by looking at the sink.</h4><br />In my home, we've decided the dishes and trash fall under my domain. These are my contribution to the household. I feel better if I do them at night before bed, and wake up to a clean kitchen.<br /><br />Sometimes, many times, when get home from work and I look at the sink I feel an overwhelming flood of emotion. I don't know what this emotion is. It comes out as anger, but anger is almost always not a root emotion. Anger is usually a reaction to another emotion you don't want to experience or admit.<br /><br />The task stands before me, it seems daunting, and the only word I that comes to mind is "overwhelming". It's as though the sink is about to swallow me. I often want to sit on the ground in the kitchen, and cry. But since I haven't really cried since I was a teenager, I just stare at it. I either shut down entirely, blank-emotional state, or I get angry.<br /><br />I might try to blame my anger on my wife and kids: "Why do you just pile all this crap up in here?" But that's not really it. I'm not mad at them. I'm mad at my own inability to process simple emotions, to the point that dishes make me want to lay down and die.<br /><br />In his book "<a href="http://the%20mars%20and%20venus%20diet%20and%20exercise%20solution/">The Mars and Venus Diet and Exercise Solution</a>", John Gray discusses the differences between male and female brain chemistry. He described most of my problems with emotional state in terms of brain science and chemical imbalance, and it was remarkable how accurate it was.<br /><br /><a href="https://en.wikipedia.org/wiki/Neuroscience_of_sex_differences#Neurotransmitters">Neurotransmitters</a>, Serotonin and Dopamine, react differently in men and women.<br /><br />Women tend to be more naturally <a href="https://en.wikipedia.org/wiki/Serotonin">Serotonin </a>deficient. This leads to less feelings of wellbeing or peace or optimism. Connection with other people, helps the body produce higher levels of this chemical; hence the need for women to connect and talk more often.<br /><br />Meanwhile, men tend to be more naturally <a href="https://en.wikipedia.org/wiki/Dopamine">Dopamine </a>deficient. John Gray describes <a href="http://www.marsvenus.com/blog/john-gray/addictions-for-men">on his blog</a>,  "Dopamine is the brain chemical that gives us pleasure, increases our focus and makes us feel good". Without this chemical, the male cannot focus or feel good.<br /><br />Men wake up in the morning with a finite amount of this Dopamine chemical. They go into the day, and use this as they perform decision making, or focus, tasks. When they come home, they have depleted this chemical, and tend to be "lazy" in mind and body. Talking requires focus and drains this chemical, so they don't want to talk, which the wife needs to refill her Serotonin. This creates a negative spiral of "I need what you don't have to get what I don't have".<br /><br />Tasks help create more Dopamine. So this dis-engaged male, can go into task mode and come 'alive' again, as this helps to produce more of the needed chemical. This explains why I often feel better if I can push though my overwhelming feeling, and start doing the dishes as a "task". It helps to temporarily re-charge my tank.<br /><br /><br />Sometimes I just can't get past it. I need to shut down, either through sleep, or mindless scrolling through feeds.<br /><br />So... that's interesting.<br /><br />Darrell