---
title: 'Foundations of Freedom 4/5 | Hearing God'
date: '2016-12-20T04:42:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2511377668543227109'
blogger_filename: '/2016/12/foundations-of-freedom-45-hearing-god.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Renewing the Mind (Stinking Thinking)'
  - 'In The Mire'
  - 'Resting'
  - 'Recovery'
  - 'Emotions'
  - 'Freedom/Kairos'
---

<br />Re-Listening to&nbsp;<a href="https://tdacad.com/about/" target="_blank">Bob Hamp</a>'s&nbsp;<a href="https://www.youtube.com/playlist?list=PLnIIzkbSbhmULFuueFoyftz6iJlQog3ww" target="_blank">Foundations of Freedom</a>&nbsp;courses.&nbsp;Starting over at lesson 2/5, Hearing God. These are my notes from this go-around:<br /><br /><h4>Hearing God</h4>When we change the things we've been focusing on, often times the things that that have been holding or harming us&nbsp;will change without our focusing on them.<br /><br />The presence of God (oven) is what transforms us (dough into cookie). You connect to the source, by Hearing God. Faith comes by hearing.<br /><br />If a plane flys by and you stop and hear it, what caused the plane's noise? The plane, not you. You just stopped to hear it.<br /><br />"I am your person"....<br /><br />God wants to talk to me.<br /><br />Spirit to spirit exchange. He may not be trying to give us "information/knowledge"... heart to heart... bypassing the mind. Often what we receive&nbsp;is a reality, preverbal... preconscious.<br /><br />Your spirit then translates that truth through your mind/will/emotions... it may come as an image, word, sense... etc.<br /><br />Does that word from God align with the written Word (Bible), and does it bring the fruit of the spirit (love, joy, peace, etc.)<br /><br />When you hear "You can leave" does it fill you with peace, love, and joy, or does it fill you with vengeance, anger, heaviness?<br /><br /><i>*30:00</i><br /><br /><h4>Use The Word as a filter:</h4><ol><li>Does what I'm hearing/seeing/sensing line up with the Word of God and the Nature of God as it is revealed in the Word.</li><li>Does it produce, in you and the people affected by it, the fruit of the spirit in <a href="http://biblehub.com/bsb/galatians/5.htm" target="_blank">Gal 5</a>?</li><ul><li><strong>Flesh</strong>: The acts of the flesh are obvious: sexual immorality, impurity, and debauchery; idolatry and sorcery; hatred, discord, jealousy, and rage; rivalries, divisions, factions, and envy; drunkenness, carousing, and the like. I warn you, as I did before, that those who practice such things will not inherit the kingdom of God.</li><li><strong>Spirit</strong>: But the fruit of the Spirit is:</li><ul><li>love</li><li>joy</li><li>peace</li><li>patience</li><li>kindness</li><li>goodness</li><li>faithfulness</li><li>gentleness</li><li>and self-control.</li></ul></ul><li>Does it set people free?</li><ul><li>Not necessarily from the circumstance or suffering, but from the power of that circumstance over you.</li><li>Sometimes Paul got free from prison, sometimes not so much. But the Word of God set him free in those circumstances to have peace, love, and joy.</li></ul></ol><a href="http://biblehub.com/2_timothy/3-16.htm" target="_blank">2 Tim 3:16</a>: All scripture is God breathed. The word scripture refers to "documents". This book is God breathed. <br /><br /><a href="http://biblehub.com/niv/hebrews/4.htm" target="_blank">Hebrews 4:12</a>: The Word of God is living and active, sharper than any two edges sword. The spoken Word is alive. The written word is dead until the breath of God is breathed into your heart through them.<br /><br />The Word and the Book are not the same thing. The Book contains the words of God, but that is not the same thing as the spoken Word of God.<br /><br />Language is a way we describe a thing, but it is not the thing. We say "car" but car doesn't come out of our mouth. Rather, a mental picture is communicated to another person who knows what car means. But they have different pictures unless they both know what that car looks like.<br /><br />But when God speaks, the things he speaks come out of his mouth. When God says PLANET, a planet comes out of his mouth into existence.<br /><br />If God says: "Peace be still", what comes out of his mouth is PEACE in a package that is deliverable and if you will tune into it, it will come inside and change you.<br /><br />When we reduce the Word of God to a paragraph and a verse, we miss the point. The Word of God becomes a reality in and to us, if we'll allow it.<br /><br />It's like when you say: "You just had to be there..." <br /><br />Nobody else can experience your experience. You cannot left brain understand the Word of God. You cannot experience the Word by reading... but reading can help you access the Word which can bring you to the experience.<br /><br />The <a href="https://www.bible.com/bible/1/rom.10.8-9.kjv" target="_blank">Word of Faith</a> is in your mouth and heart... only then is it an experience.<br /><br />"I love you... and anything that stands in the way of me loving you, even if it's you, I will overwhelm it..."<br /><br />When we tune in to hear his voice, and all we want is information or correction, He might do that... but what He really wants is to say "I love you" and for that to impact you.<br /><br />The Word of God is the expression of his heart and intention toward you since before time.<br /><br /><a href="https://www.bible.com/bible/1/col.1.17" target="_blank">Col 1:17</a>: And he is before all things, and by him all things consist.&nbsp; <br /><a href="https://www.bible.com/bible/1/heb.11.3" target="_blank">Heb 11:3</a>: The World which was made of the Word of God.<br /><br />An atom is made of <a href="https://en.wikipedia.org/wiki/Quark" target="_blank">Quark</a>s, quarks are made of energy/vibration/sound. E=MC2. Energy equals Matter times the speed of light squared. But if energy could be slowed down, it becomes matter. <br /><br />God's Word is literally holding everything together. <br /><br />The further things are from God the more things fall apart.... What we want to do is get a better knowledge of good so that we can get things right and get back to God.<br /><br />The further we get from His Word, the more things break down. You cannot make yourself right or start doing right... you just have to get in tune with His Word, and those things will be made right without your trying. <br /><br />If things are falling apart that is not a sign of your "failure" it's a s sign of your distance from Him.<br /><br />He is saying: "Come back to me, and I'll bring peace where there was anxiety, health where there was sickness, soundness where there was confusion."<br /><br /><em>*57:50</em><br /><br /><h4>Confession</h4><br />We think of confession of "confessing sin". The word Confession comes from a compound word in the Greek. HomoLogos. <br /><br /><ul><li>Homo=Same</li><li>Logos=The Expression of what's in God's heart.</li></ul><br />Confession is to say what God is saying. If God is talking about your sin, and you confess sin, then you are confessing. If God is saying you are Righteous, but you are talking about sin, that it not confession.<br /><br />He convicts the world of <a href="http://biblehub.com/john/16-8.htm" target="_blank">sin and righteousness</a>, not just one of the other.<br /><br />Confession is when we hear, believe, and speak/act. <br /><br />Here's where that goes wrong. What if we confess not what God's saying, but we want. "I want to be rich and have a Cadillac." We are confession our desires and passions and wants. But if that's not what God's saying, it will only lead to frustration.<br /><br /><h4>A Prayer Offered In Faith Requires Hearing God</h4><br />The reason most of us&nbsp;don't have our prayers answered, is because we don't take the time to hear God before we pray. So we're just praying out of our desires, not out of hearing. <br /><br />A prayer that's offered in faith CANNOT be offered in faith unless it came from hearing.<br /><br />Praying our motives doesn't count and doesn't work. God won't do magic for you. Prayer is not a magic formula to get what you want.<br /><br />Check your motivations.<br /><ul><li>"I got up early for you and I have all these things that I need to hear from you about..." </li><li>"So you got up for you, huh?"</li></ul>Don't go into prayer with a motivation, a list of things to pray about, just go in to hear. God may have an agenda that has nothing to do with you or your circumstances. Just go in with no expectation other than what He may want to talk about.<br /><br />God is doing something in the world and wants me to come cooperate with Him. He won't bless MY agenda, but he'll bless me when I get on His agenda.<br /><br />If power comes to my house through the in wire, to the stereo and back the out wire. If you snip the out wire the power will never manifest. If we study and hear our brains out, but never return it to Him, there's no completed circuit. <br /><br />You do this through prayer back to him, and through you to others. <br /><br />If it doesn't go through your life, the power coming to you can't be drawn on. Life comes to me, inhabits me, and go through me. It's a circuit.<br /><br />"I only do what I see my Father do, say&nbsp;what I hear my Father say..." but then he said "stretch out your withered hand." He completed the circuit, and it manifested. <br /><br />Sabbath is the frequency on which God broadcasts. It's those moments when you are still that he can speak. If you are constantly running, busy, listening to radio... He may try to interrupt you at a stop light, as you are going to bed or waking up, or in the middle of the night... <br /><br />"<a href="https://www.youtube.com/watch?v=JU4U8_wMdRs" target="_blank">In the stillness, in the quiet place..</a>." God speaks in a <a href="http://biblehub.com/niv/1_kings/19.htm" target="_blank">gentle whisper</a>.<br /><br />Don't try to "think what God is thinking"... more like when you hear a plane or car going by... just hear what God is saying. It might just be a phrase or a single word, an image, a sense of something... <br /><br />Listen.... Be Still.... <br /><br /><br />So, broken or whole, "right or wrong", that's what I'm thinking about today,<br /><br />Darrell W.<br /><br />