---
title: 'Interviews 3 | Know Yourself'
date: '2016-05-28T06:33:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2269632832916601039'
blogger_filename: '/2016/05/interviews-3-know-yourself.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Job'
  - 'Get Hired'
---

<h4><a href="http://en.wikipedia.org/wiki/Know_thyself">Nosce Te Ipsum</a> - Know Thyself</h4><br />This phrase primarily means to know your strengths and weaknesses.<br /><blockquote class="tr_bq"><i>Do not think of yourself more highly than you ought to.&nbsp;</i><a href="http://www.biblestudytools.com/gnt/romans/12-3.html">Romans 12:3</a></blockquote><div>This common phrase doesn’t mean to put yourself down, as some religious folks would have you believe. Rather, it asks that you know who you are and who you aren’t.&nbsp;</div><div><br /></div><div>Know the gifting(s) God has placed inside of you and also what he hasn’t called you to. By doing so you are able to narrow down the position that fit you and those that do not.<br /><br /><h4>Know your strengths</h4>You have been given strengths and giftings by God. He has enabled you to be particularly good at certain things. If you know what those strengths are then you can boldly assert what they are and be confident in your answers.<br /><br />If you are not sure what your strengths and giftings are, check out another article I wrote called "<a href="http://toposconsulting.blogspot.com/2016/05/discovery-finding-your-place-in-gods.html" target="_blank">Discovery | Finding Your Place In God's Plan</a>".<br /><br />Maybe you are strong at something but not as strong as you want to say you are. Don’t be tempted to overstate your strengths. If you are hired into a position for stating you are stronger at something than you are it will be found out quickly.<br /><br /><h4>Know your areas of opportunity</h4><br />Humility isn’t about putting yourself down. It’s about knowing what you can and can’t do, and being honest about both.<br /><div><br /></div>You have areas that you are growing in.<br /><br /><ul><li>There are things that you aren’t good at. Nobody is good at everything.&nbsp;</li><li>There are things that you are good at, but you don't enjoy. That's important to know too.</li><li>Some areas you will be strong in at a future date, but you just aren’t there yet.&nbsp;</li></ul><br />If you know these areas of opportunity and are strategically honest about them you will either know to avoid certain positions, or you will be able to communicate how these areas are not dis-qualifiers to your new desired position.<br /><br />Example: I talk a lot.<br /><blockquote class="tr_bq">That makes me a GREAT writer and blogger. When I was given assignments to write 500 words about something, I didn’t struggle to get up to 500 words, I struggled to get back DOWN to 500 words and edit out the un-necessary.&nbsp;</blockquote><blockquote class="tr_bq">This meant that as a call center rep I often struggled with handle time. They wanted my average calls to come to 255 seconds or less. I was always pushing over 300-350, on a good day. After I left they actually raised the goal to 300, oh well…</blockquote><br />Interviewers may ask what my weakness are (Areas of Opportunity). This isn't as common these days, but the question is still out there. Sell yourself by showing that you know your areas of opportunity, and you are actively working on them.<br /><br /><blockquote class="tr_bq">I could tell the interviewer that: I talk too much and can’t seem to figure out how to lower it… that doesn’t quite sell my opportunity.</blockquote><b>OR</b><br /><blockquote class="tr_bq">I could tell the interviewer that: I enjoy meeting new people and getting to know them. I am honestly interested in people and want their best interest. I also have a strong desire to have things done right and not half done. As a result I sometimes take longer on calls than my counterparts. I am actively working on finding ways to say less, not ask certain questions that open the conversation up or encourage long stories. I'm also working on asking more direct questions that allow me to build rapport and enjoy the interaction, without taking a long time to do it.</blockquote>One highlights weakness and one highlights area of opportunity.<br /><br /><br /><h4>The important questions:</h4><br />Answer these questions for yourself so that you can articulate it to the interviewer:<br /><br /><ul><li>How am I the BEST fit for this position?&nbsp;</li><li>How am I going to add value to this company, department, or team?</li></ul><br />I am a great fit for this position because…<br /><blockquote class="tr_bq">I am a great fit for this position because I have 4 years of background in banking related sales. I have sold in person and over the phone. I know my customers and ask great questions. I am not only able to meet their needs with the best products and services but I am able to uncover other needs they didn’t realize they had.&nbsp;</blockquote><blockquote class="tr_bq">Just the other day someone came in to order checks and I was able to uncover for her that her mortgage rate was 7% and current rates are in the low 4% range. She was hooked up with my mortgage partner and refinanced into a 4.32%. It dropped her monthly payment and will cut years off of her loan. She was ecstatic!</blockquote><br /><b>Homework Assignment:</b><br /><br /><ul><li>List for yourself your top 3 areas of strength and top 3 areas of opportunity.&nbsp;</li><li>Practice talking to yourself or a training partner about these 6 areas.</li></ul><br /><br /><br /><b>See Also:</b><br /><ul><li><a href="http://toposconsulting.blogspot.com/2016/05/interview-skills-introduction.html" target="_blank">Interview Skills- An Introduction</a></li></ul><ul><li><a href="http://toposconsulting.blogspot.com/2016/05/interviews-pt-1-concrete-and-specific.html" target="_blank">Interviews PT 1- Concrete and Specific</a></li></ul><ul><li><a href="http://toposconsulting.blogspot.com/2016/05/interviews-2-know-job-description.html" target="_blank">Interviews 2 | Know the Job Description</a></li></ul><ul><li><a href="http://toposconsulting.blogspot.com/2016/05/interviews-3-know-yourself.html" target="_blank">Interviews PT 3- Know Yourself</a></li></ul><ul><li><a href="http://toposconsulting.blogspot.com/2016/05/resume-gods-or-yours.html" target="_blank">Resume: God's or Yours?</a></li></ul><ul><li><a href="http://toposconsulting.blogspot.com/2016/05/discovery-finding-your-place-in-gods.html" target="_blank">Discovery | Finding Your Place In God's Plan</a></li></ul><ul><li><a href="http://toposconsulting.blogspot.com/2014/03/the-hedgehog-sweet-spot-finding-your.html" target="_blank">The Hedgehog &amp; The Sweet Spot. Finding Your Unique Place In This World.&nbsp;</a></li></ul><br /><b><a href="https://plus.google.com/+DarrellWolfe/posts">Darrell Wolfe</a>, Topos Consultant</b></div>