---
title: 'Distortion Critique 1'
date: '2016-09-18T04:48:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5322213287696955844'
blogger_filename: '/2016/09/distortion-critique-1_17.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'critique'
  - 'White Noise'
---

<br /><br />So I put out scene one from Distortion for a writer's critique. Here was the result:<br /><br /><br /><br />It's amazing how awesome this feedback was. You can live with your stuff long enough that you become blind to it. I have a lot of work to do (first novel) but I've studied the craft long enough to understand everything everyone is saying. Besides all the specific points, the two themes I noticed were a lack of emotional/physical reaction (nothing to keep you in Ash's head) and the Great Sin (show don't tell). I also changed tense and didn't notice (no that was not on purpose). There were many other great points, and I have a lot of work to do. Thanks again to&nbsp;<a href="http://www.scribophile.com/" target="_blank">http://www.scribophile.com/&nbsp;</a>for making a community for writers.<br /><br /><br /><br /><br /><br /><div class="user" style="background-color: white; color: #222222; font-family: Verdana, sans-serif; font-size: 14px; position: relative; z-index: 10;"><br /><div style="font-weight: bold; text-align: center; word-wrap: break-word;"><br /><a href="http://www.scribophile.com/authors/celina-a-igwe/" style="color: #c70c14; outline: 0px; text-decoration: none;">Celina A. Igwe</a></div><br /></div><br /><div class="bubble" style="background-color: white; border-radius: 8px; border: 2px solid rgb(221, 221, 221); color: #222222; font-family: Verdana, sans-serif; font-size: 14px; margin-left: 90px; position: relative;"><br /><div class="comment" style="padding: 10px;"><br /><h4 style="border-bottom: 2px solid rgb(238, 238, 238); color: #353e34; font-size: 16px; line-height: 22px; margin: 0px 0px 10px; padding-bottom: 5px;"><br />Opening Comments</h4><br /><div style="margin-top: 10px;"><br />Great start! I'm excited to see how this develops!</div><br /><h4 style="border-bottom: 2px solid rgb(238, 238, 238); color: #353e34; font-size: 16px; line-height: 22px; margin: 40px 0px 10px; padding-bottom: 5px;"><br />Plot</h4><br /><div style="margin-top: 10px;"><br />Based on the first chapter alone, of course, I am wondering if there is a plot? &nbsp;Will this be a series of dreams or is there a reality Ash must also deal with. &nbsp;Are their people in his life that he's trying to reconnect with? If the story is a series of dreams or memories, I wondered what he is trying to get to. &nbsp;What is there to be resolved?&nbsp;</div><br /><h4 style="border-bottom: 2px solid rgb(238, 238, 238); color: #353e34; font-size: 16px; line-height: 22px; margin: 40px 0px 10px; padding-bottom: 5px;"><br />Pacing</h4><br /><div style="margin-top: 10px;"><br />I did appreciate that many times the pacing felt like a dream, a bit disjointed and such. But I'm not sure if you intended the format or not. &nbsp;The constant breaks, for me, felt choppy, and I had a hard time following the action and I found my self pausing after every break, which slowed the pace and confused the action. &nbsp;</div><br /><h4 style="border-bottom: 2px solid rgb(238, 238, 238); color: #353e34; font-size: 16px; line-height: 22px; margin: 40px 0px 10px; padding-bottom: 5px;"><br />Description</h4><br /><div style="margin-top: 10px;"><br />I realize by the end that is all a memory or a dream, but I did still desire a bit more description. &nbsp;Have you ever had those types of dreams that you swore were real? They can be more than images. &nbsp;Or even memories have specific feelings and emotions behind it. &nbsp;Some people even capture memories with certain hues of color. &nbsp;Developing more palatable descriptions may take us deeper into character interactions and/or plot points.</div><br /><div style="margin-top: 10px;"><br />&nbsp;Did it take place in the day or in the night? Or both? &nbsp;Did the locations switch (as some dreams do) or is it the same constant location? Can he tell what is a dream or not? &nbsp;These are just some question I had.&nbsp;</div><br /><h4 style="border-bottom: 2px solid rgb(238, 238, 238); color: #353e34; font-size: 16px; line-height: 22px; margin: 40px 0px 10px; padding-bottom: 5px;"><br />Point Of View</h4><br /><div style="margin-top: 10px;"><br />I wondered as I read, since PTSD is such a personal and individual experience, just for fun, how would this story work in first person? &nbsp;Personally for me, I felt far away from him when I wanted to be directly in his head. &nbsp;I wanted to feel what he was feeling and capture it all from his eyes only. &nbsp;So maybe, just for fun, you could try rewriting a few lines in first person just to see how it feels. &nbsp;Worse case scenario is you get a another perspective or deeper development of the character.</div><br /><h4 style="border-bottom: 2px solid rgb(238, 238, 238); color: #353e34; font-size: 16px; line-height: 22px; margin: 40px 0px 10px; padding-bottom: 5px;"><br />Characters</h4><br /><div style="margin-top: 10px;"><br />Ash seemed a bit distant to me. &nbsp;I could understand his facts and actions, but it was hard for me to get into him. What I mean is, it was hard for me to earnestly care for him, though I really wanted to. &nbsp;Playing with first person pov, may help discover ways to include "him" more...if that makes sense. &nbsp;If you want to stick to third person, then it may help to include more of his thoughts into story. &nbsp;Does he know it's a memory/dream? Has this happened before or is it the first time? How does he feel? Is the question i kept asking.</div><br /><h4 style="border-bottom: 2px solid rgb(238, 238, 238); color: #353e34; font-size: 16px; line-height: 22px; margin: 40px 0px 10px; padding-bottom: 5px;"><br />Closing Comments</h4><br /><div style="margin-top: 10px;"><br />This work has great potential to become something both entertaining and enlightening. &nbsp;I'm excited to read more!</div><br /></div><br /><h6 style="border: none; color: #353e34; font-size: 16px; line-height: 22px; margin: 10px 0px 0px; padding-bottom: 5px; padding-right: 5px; text-align: right;"><br /></h6><br /></div><br /><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><br /><div><br /><br /></div><br /></blockquote><br /><h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;"><br />By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4><br /><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><br /><i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote><br /><ul><br /><li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li><br /><li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li><br /><li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li><br /><li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li><br /></ul><br /><ul><br /></ul><br />