---
title: 'Interviews 2 | Know the Job Description'
date: '2016-05-28T05:48:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2929709118356567844'
blogger_filename: '/2016/05/interviews-2-know-job-description.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Job'
  - 'Get Hired'
---

<h4>Knowing the Position, Title, and Job Description are key</h4>You must know the position for which you are applying.<br /><br />Applying for a position and then declining it can begin to look bad for you if you do it over and over with the same company. <i>You will look like a flake.&nbsp;</i><br /><br />Many times the employers don’t make this easy. They post job descriptions but not salary levels and you are left to fend for yourself asking: “<i>Is this a fit for me?"</i><br /><br />Where do you start?<br /><h4>Narrow Your Search</h4>If you know what you are looking for in a job, then you will be able to weed through the countless job offers on the internet and in the newspaper more easily.<br /><br />You can spend your time pushing for the jobs you really want and not wasting your time on interviews for positions you won’t enjoy.<br /><br /><h4>Research</h4>Take time to research the positions you apply for, before applying.<br /><br />If you are not sure that you are a great fit, find out first (or at least develop an educated guess). There are so many tools on the internet now for understanding job descriptions and fields.<br /><br />Take some time to research the Job Description. Look for key words, required, preferred skills, and job duties. Try to determine if you have these skills from another job. It's always important that you had the job title previously, just the skill.<br /><br />For example, you may see a Job Description that requires 2 years compliance experience. You've never worked in the that job title, but have you had any duties that required you to be exposed to, in charge of, or relating to compliance to company rules and regulations. Every team lead has had to be aware of the regulations, and ensure their teams are in compliance.<br /><br /><h4>Then tailor you resume to the job description.&nbsp;</h4><div><br /></div>Put that experience in your resume, and talk to it in the interviews.<br /><br />The resume will not only help you when you meet the recruiters and interviewers; but, it will help you get past the screeners. If your resume doesn't open the screeners door, your interview skills won't have a chance to be used.<br /><br /><br /><b>Network</b><br /><br />Get to know people within the field (in person or through social sites like <a href="http://www.linkedin.com/">Linked In</a>).<br /><br />Ask questions, people love to talk about themselves and what they do. Do you have any friends or contacts in that field, or better yet in that company? Ask questions. Introduce yourself to the managers at the company if possible.<br /><br />If it’s a large company that has multiple offices don’t be afraid to just walk into one of the branches, even if it’s not the one you are thinking of working at, and introduce yourself to the manager, ask them if you could have a few minutes of their time.<br /><br />Tell them that you are thinking of coming to work for the company and that you are interested in finding out more about the inner working and what it takes.<br /><br /><h4>Ask Good Questions</h4><br /><ul><li>What does the day in the life of an employee of XYZ look like?&nbsp;</li><li>What attributes make a great employee in your field?&nbsp;</li><li>What things do people often struggle with as they first come on board?&nbsp;</li></ul><br />Think through the places you’ve worked, what you liked and didn’t like. Ask questions that will help you understand if this is a place you want to work.<br /><br />I realized recently that I prefer a company that follows a modern model for vacation, where all the hours are lumped into one box and you use them as you see fit.<br /><br />I was quite put out upon working for a company that still separated personal vs vacation vs sick time and punished you for using sick time when they offered it and wouldn’t let you use it for anything else or pay you out if you didn’t use it. This felt to me very double minded. I chose to leave that company and go back to a company that had a more straight forward way of dealing with time off.<br /><br />You may have things about your personality that won’t fit certain companies or departments within a company.<br /><br />It would be best for you do know before you formally apply or interview that the company fits in your “Must Have’s” and “Must Not Haves‘”.<br /><br /><br /><b>Details</b><br /><b><br /></b>After you have determined that the company and position fits you, learn details about the position. Learn the shop talk. Find out terms that are used within the industry or field.<br /><br />The more you know about the position, and the more you know about how you can fit the position, the better. You should be able to personally relate the skills and personality traits you posses to the position.<br /><br /><br /><b>See Also:</b><br /><ul><li><a href="http://toposconsulting.blogspot.com/2016/05/interview-skills-introduction.html" target="_blank">Interview Skills- An Introduction</a></li></ul><ul><li><a href="http://toposconsulting.blogspot.com/2016/05/interviews-pt-1-concrete-and-specific.html" target="_blank">Interviews PT 1- Concrete and Specific</a></li></ul><ul><li><a href="http://toposconsulting.blogspot.com/2016/05/interviews-2-know-job-description.html" target="_blank">Interviews 2 | Know the Job Description</a></li></ul><ul><li><a href="http://toposconsulting.blogspot.com/2016/05/interviews-3-know-yourself.html" target="_blank">Interviews PT 3- Know Yourself</a></li></ul><ul><li><a href="http://toposconsulting.blogspot.com/2016/05/resume-gods-or-yours.html" target="_blank">Resume: God's or Yours?</a></li></ul><ul><li><a href="http://toposconsulting.blogspot.com/2016/05/discovery-finding-your-place-in-gods.html" target="_blank">Discovery | Finding Your Place In God's Plan</a></li></ul><ul><li><a href="http://toposconsulting.blogspot.com/2014/03/the-hedgehog-sweet-spot-finding-your.html" target="_blank">The Hedgehog &amp; The Sweet Spot. Finding Your Unique Place In This World.&nbsp;</a></li></ul><br /><b><a href="https://plus.google.com/+DarrellWolfe/posts">Darrell Wolfe</a>, Topos Consultant</b>