---
title: 'Grace Scriven - Reporter'
date: '2016-10-04T02:14:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3813409933653689733'
blogger_filename: '/2016/10/grace-scriven-reporter_3.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
  - 'Character Sketch'
---

<h3><br />Grace Scriven - Reporter</h3><br /><br /><br /><h4><br />Getting into the background: Grace</h4><br />Grace Scriven has wanted nothing less than to be a reporter. She was assigned fluff pieces and other things she didn't like for over ten years of her career. She had enough, so she went Freelance. She kept enough work through Freelancing that she paid the bills. She also worked for more than one news paper this way.<br /><br /><br /><br />In the meantime, she kept her eye out for stories that could "make her career". She wants to prove her worth as a real journalist, and make a difference in peoples' lives, give them a voice. <br /><br /><br /><br />She is also willing to step on people's toes to get her reports, which doesn't make her a lot of friends, or give her the chance to make a positive impact on the people she meets. Her desire to be a star reporter often leaves her pushing her sources too far and too hard; hurting the ones she was supposed to be giving a voice to.<br /><br /><br /><br />After several false starts, she found a story nobody was following. Grace titled the piece, "What Noise - A science experiment gone amuck (working title)."<br /><br /><br /><br />She spent the better part of two years worth of her off time looking into the operation. She finally landed a solid lead with Dr. Briar's trip to Ashland, Oregon. She decided to follow him there where she hoped to catch him doing something nefarious, or at least get a clue to what they were up to. She knew his volunteers kept disappearing, but he didn't know how to prove it.<br /><br /><br /><br />She saw Dr. Briar put something into Ash's drink, but she didn't know who he was. She assumed he must be a former volunteer. Before she could warn him, without exposing her disguise, a man jumped him knocking him over. The coffee spilled, and disaster was averted for the moment.<br /><br /><br /><br />Before she left the scene, she caught Dr. Briar staring at her. Recognition hit his eyes, and she ran.<br /><br /><br /><br />Grace needed to get to this guy before Dr. Briar could get to him again, so she lifted her hood and poured water on the engine to produce steam (a trick she'd learned from growing up around her mechanic father, who would wash down engines he worked on). Pretending to be stranded, she hoped Ash would stop and give her a ride, which he did. She tried to play it safe, ask questions, before she could reveal her real reason for getting to him, they were run off the road and chased through a forest.<br /><br /><br /><br />She agreed to run with him, as her life was in danger now too.<br /><br /><br /><br /><strong>Action!</strong><br /><br /><br /><br /><br /><br /><h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;"><br />By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4><br /><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><br /><i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote><br /><ul><br /><li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li><br /><li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li><br /><li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li><br /><li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li><br /></ul><br /><ul><br /></ul><br />