---
title: 'I serve in my spirit... a relaxed and peaceful way to &quot;Serve God&quot; !'
date: '2016-06-12T03:42:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5689597585406111137'
blogger_filename: '/2016/06/i-serve-in-my-spirit-relaxed-and.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Armchair Theology'
  - 'Spiritual Growth'
---

<h3><i>A Roman Story</i></h3><br /><br /><i>Hi Daddy.... Good morning.&nbsp;</i><br /><i><br /></i><i>Hey there Son. How are you this morning?&nbsp;</i><br /><i><br /></i><i>Tired. I was thinking about my new friends back in Rome. The ones I met on my last trip to Italy. How do you think they're doing these days? I need to get down there, I really think we could help them. Maybe you and I could go and give them some gifts and treats? I know they were having a hard go of it, last time we talked.&nbsp;</i><br /><i><br /></i><i>That sounds like a good idea. I'll check the schedule, and see when we can fit in a trip over there. OK?</i><br /><i><br /></i><i>That sounds great.&nbsp;</i><br /><i><br /></i><i>Now I do have a few things I'd like to chat about before you head out today.&nbsp;</i><br /><i><br /></i><i>Alright Daddy. What's on your heart?</i><br /><i><br /></i><i>You remember the other day when...</i><br /><div><br /></div><div><br /></div><br /><div style="text-align: center;">********</div><br /><blockquote class="tr_bq"><i>God, whom <b>I serve in my spirit</b> in preaching the gospel of his Son, is my witness <b>how constantly I remember you in my prayers</b> at all times; and I pray that now at last by God’s will the way may be opened for me to come to you. <a href="http://biblehub.com/romans/1-9.htm" target="_blank">Romans 1:9-10</a></i></blockquote><br /><i><a href="http://biblehub.com/interlinear/romans/1-9.htm" target="_blank">Interlinear</a>:</i><br /><blockquote class="tr_bq"><a href="http://biblehub.com/greek/3000.htm">3000</a> <a href="http://biblehub.com/greek/strongs_3000.htm">[e]</a><b><a href="http://biblehub.com/greek/latreuo__3000.htm">latreuō</a> | λατρεύω</b>Short Definition: <b>I serve, worship</b>3000 latreúō (from latris, "someone hired to accomplish a technical task because qualified") – properly, to render technical, acceptable service because specifically qualified (equipped).<br /><br /><a href="http://biblehub.com/greek/4151.htm">4151</a> <a href="http://biblehub.com/greek/strongs_4151.htm">[e]</a><b><a href="http://biblehub.com/greek/pneumati_4151.htm">pneumati</a> | πνεύματί</b>Short Definition: <b>wind, breath, spirit</b>4151 pneúma – properly, spirit (Spirit), wind, or breath. The most frequent meaning (translation) of <a href="http://biblehub.com/greek/4151.htm">4151</a> (<b>pneúma</b>) in the NT is "spirit" ("Spirit"). Only the context however determines which sense(s) is meant.&nbsp;The Hebrew counterpart (<b>rûach</b>) has the same range of meaning as&nbsp;<a href="http://biblehub.com/greek/4151.htm">4151</a> (pneúma), i.e. it likewise can refer to spirit/Spirit, wind, or breath.</blockquote><div><br /></div><div><br /></div><h4><i><b>I serve in my spirit &nbsp;(What/Where/Why I do... )</b></i></h4><div><br /></div><div>When I say that I'm going to "serve the Lord"... many religious things immediately come to mind.&nbsp;</div><div><br /></div><div><ul><li>Preach/Teach/Pastor</li><li>Worship Leader/ Play on Worship Team</li><li>Usher, Greater, Checker</li><li>Clean the church bathrooms</li><li>Tithe/Give offerings</li><li>Read my bible every morning, and beat myself up when I don't</li><li>Pray (go through my checklist of wishes and people I wish for)</li></ul></div><div><br /></div><div>The fall was the result of Adam's action in taking the fruit of a single tree.&nbsp;</div><div><br /></div><div>The tree Knowledge.&nbsp;</div><div><br /></div><div>The Tree of Knowledge of Good was not the opposite of the Tree of the Knowledge of Evil...</div><div><br /></div><div>The Tree of the Knowledge of Good and Evil is a single tree, and that tree is the source of all human suffering.</div><div><ul><li><i>If you haven't read my definition of <a href="http://darrellwolfe.blogspot.com/p/got-freedom.html" target="_blank">LIFE, see HERE</a> for more on that.</i></li></ul></div><div><br /></div><div>There is a subtle lie built into all of these things listed above. These are Good Things, and you Know to do them. But they are physical actions that can all (even the form of prayer at the end) be taken by someone who has no LIFE, and no living relationship with LIFE Himself.&nbsp;</div><div><br /></div><div>If I have LIFE, I am connected to LIFE Himself. That connection is a spiritual connection.</div><blockquote class="tr_bq"><i>God is spirit, and those who worship him must worship in spirit and truth.”&nbsp;English Standard Version | <a href="http://biblehub.com/john/4-24.htm" target="_blank">John 4:24</a></i></blockquote><div><br /></div>We are Spirit, Soul, &amp; Body. My SPIRIT is the real me.<br /><div><br /></div><div>So if I am to serve in spirit, I have to make, keep, and maintain a spiritual connection.&nbsp;</div><div><br /></div><div><br /></div><div><br /></div><div><h4><b>So how did Paul serve "in" his spirit?&nbsp;</b><i><b>...how constantly I remember you in my prayers&nbsp;</b></i><i>(How I do...&nbsp;<a href="https://en.wikipedia.org/wiki/Modus_operandi" target="_blank">Modus Operandi</a>)</i></h4><div>The NASB translates it this way:<br /><blockquote class="tr_bq"><i>For God, whom I serve in my spirit in the preaching of the gospel of His Son, is my witness as to how <b>unceasingly I make mention of you</b>,&nbsp;<a href="http://biblehub.com/nasb/romans/1.htm">New American Standard Bible&nbsp;</a>, Romans 1:9</i></blockquote><div><br /></div><b></b><br /><ul><b><li><b>He just talked WITH God.&nbsp;</b></li></b></ul><b></b><br /><div><br /></div>I mean seriously... that's it. No to-do list. No nine things you must do to be super-spiritual. He talked with God.&nbsp;</div><div><br /></div><div>He did not just talk TO God, he talked with Him.&nbsp;</div><div><br /></div><div>He had dialogue.&nbsp;</div><div><br /></div><div>He had a relationship.&nbsp;</div><div><br /></div><div>Notice the conversational, almost nonchalant, phrasing: "I make mention of you..."</div><div><br /></div><div>That could sound like:&nbsp;</div><div><br /></div><blockquote class="tr_bq"><i>"Oh... by the way Jesus. I was thinking about the 1st Church of Rome just now. How are they? You know they serve you, but they have needs. Can we talk about them for a few moments?"</i></blockquote><div><br /></div><div>Frequent dialogue with the one who made you... that's all serving God means.&nbsp;</div><div><br /></div><div>That's way less pressure than a to-do list.&nbsp;</div><div><br /></div><div><br /><br /><div><div style="text-align: center;">********</div><br /></div><div>By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts">Darrell Wolfe</a>&nbsp;| #<a href="http://ctt.ec/5xc67">BeStillBeLed</a></div><div><br />Story Teller | Creative |&nbsp;<a href="http://www.16personalities.com/infj-personality">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder">Intellection</a>&nbsp;| Learner | Ideation | Achiever | Input | Multipotentialite<br /><br />New here?<br /><br /><ul><li><a href="http://darrellwolfe.blogspot.com/p/about-20.html" target="_blank">Start Here</a>&nbsp;for more information.</li><li><a href="http://darrellwolfe.blogspot.com/p/q.html" target="_blank">Ask&nbsp;</a>me anything</li><li><a href="http://darrellwolfe.blogspot.com/p/got-freedom.html" target="_blank">Got LIFE? Not sure, click HERE to find out.</a></li><li>See&nbsp;<a href="http://www.darrellwolfe.com/p/by-darrell.html" target="_blank">DarrellWolfe.com</a>&nbsp;for more of my sites.</li></ul></div></div></div>