---
title: 'Anointing |  The Burden Removing, Yoke Destroying Power of God'
date: '2017-01-26T10:48:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8145625140849636829'
blogger_filename: '/2017/01/anointing-burden-removing-yoke.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Spiritual Growth'
---

<br />
I woke up this morning with neck pain, as is often the case. But rather than whine about it, or toss and turn until the pain meds kicked in, I decided to get up and pray.<br />
<br />I felt led to look up <a href="http://biblehub.com/esv/isaiah/61.htm">Isaiah 61</a>:<br /><blockquote class="tr_bq">
<i>1The Spirit of the Lord GOD is upon me&nbsp;because <b>the LORD has anointed me</b> to bring good news to the poor;&nbsp;he has sent me to bind up the brokenhearted, to proclaim liberty to the captives, and the opening of the prison to those who are bound;&nbsp;2to proclaim the year of the LORD’s favor, and the day of vengeance of our God; to comfort all who mourn;&nbsp;3to grant to those who mourn in Zion— to give them a beautiful headdress instead of ashes, the oil of gladness instead of mourning, the garment of praise instead of a faint spirit; that they may be called oaks of righteousness, the planting of the LORD, that he may be glorified.&nbsp;4They shall build up the ancient ruins; they shall raise up the former devastations; they shall repair the ruined cities, the devastations of many generations</i></blockquote>
<br />This chapter has been precious to me ever since I first learned about the anointing, in 2003, but in light of my new found healing and inner freedom, it is taken on a whole new depth of meaning to me.<div>
<br /></div>
<div>
One of the keys to understanding the anointing is to go back and read through Moses' first encounters with God, his establishment of Aaron as the priest of Israel, and God's specific instructions for creating an oil that can only be used by the priests for anointing and nothing else.</div>
<div>
<br /></div>
<div>
Then take a close look at&nbsp;<a href="http://biblehub.com/isaiah/10-27.htm">Isaiah 10:27</a>:</div>
<div>
<blockquote class="tr_bq">
<i>And it shall come to pass in that day, that his <b>burden shall be taken away</b> from off your shoulder, and his yoke from off your neck, and the <b>yoke shall be destroyed</b> because of the <b>anointing</b>.&nbsp;</i><i><a href="http://biblehub.com/kj2000/isaiah/10.htm">King James 2000 Bible</a></i></blockquote>
Many translations render the last word "Fat" or "Fatness". The word can be translated either Oil or Fat, depending on its context (oil = fat).</div>
<div>
<br /></div>
<div>
Some translations take that and impose their own interpretation on it, and say because you grew too fat or because of your prosperity. This is not wrong, but it is incomplete. The word Fat can mean that you are doing well in this culture, and someone who is anointed is doing well.&nbsp;</div>
<div>
<br /></div>
<div>
The actual word here in this context is referring back to the anointing Oil, as given by Moses and used by the priests.&nbsp;</div>
<div>
<br /></div>
<div>
One of my first pastors, <a href="http://www.oasischurch.net/new-page/">Pastor Stewart Roberts</a>, had this oil made according to the <a href="http://www.experience-essential-oils.com/holy-incense-and-holy-anointing-oil.html">original biblical</a> formula, found in <a href="http://biblehub.com/exodus/30-34.htm">Exodus 30:34-35</a>. He used it in services to anoint people, as we are all now a royal priesthood. It's a highly fragrant oil, the smell is sweet and powerful. If someone were recently anointed you would know by your nose that they'd entered the room.</div>
<div>
<br /><b>So what is the&nbsp;Anointing?</b> It is the: <b>The Burden Removing, Yoke Destroying Power of God</b><br /><br />So if we are all now filled with the HolySpirit of God, and anointed, what are we anointed to do?</div>
<div>
<br /></div>
<div>
<ul>
<li>Bring good news to the poor: You don't have to be poor anymore (spiritually, physically, or financially).&nbsp;</li>
</ul>
<ul>
<li>Heal broken hearts (distorted lenses, and hurting hearts).</li>
</ul>
<ul>
<li>Tell people who have been captive (to sin, sickness, demons, and fear) that they can be free!</li>
</ul>
<ul>
<li>Use that Power of God to take people who are bound (by addictions, sickness, demons, or fear) and set them free (by letting God's power work through you to heal, cast out, and deliver).&nbsp;</li>
</ul>
</div>
<div>
But that's not all! There's more:</div>
<div>
<br /></div>
<div>
<ul>
<li>The Acceptable Year of the Lord refers to the <a href="https://en.wikipedia.org/wiki/Jubilee_(biblical)">Jubilee Year</a>&nbsp;when all debts are wiped clean and everyone's property and fortune are restored. This was a type and shadow of Jesus' death and resurrection setting us free from Sin, Sickness, Demons, and Fear. We are to tell everyone we can about this Freedom and LIFE Jesus came to give.</li>
</ul>
<ul>
<li>Because of the gift of Jesus, we are able to show them beauty despite the death and destruction around them; Joy or Gladness or Thankfulness despite the sadness or grief they feel; and show them how to praise God in the very midst of adversity.</li>
</ul>
<ul>
<li>These attributes allow us to help them become firmly rooted in God's Kingdom, and they will then rebuild and restore others.</li>
</ul>
</div>
<div>
<br /></div>
<div>
We are living in the last of the last days before the return of Jesus. The darkness of this world will continue to increase. The debt, death, and violence will not get better, only worse.&nbsp;</div>
<div>
<br /></div>
<div>
Nevertheless, so too will God's people get more powerful. Where sin abounds, grace does much MORE <a href="http://biblehub.com/romans/5-20.htm">abound</a>.&nbsp;</div>
<div>
<br /></div>
<div>
We will prosper despite the darkness and build the Kingdom of God until the day Jesus returns for his Bride.&nbsp;</div>
<div>
<br /></div>
<div>
We will do it one soul at a time!</div>
<div>
<br /></div>
<div>
Let's go set the captives free!</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<div>
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;"><br /></span></div>
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Story Teller | <a href="https://www.16personalities.com/infj-personality">INFJ</a> | Futuristic | Intellection | Learner | Ideation | Achiever | Command | Input | Focus | <a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en">Multipotentialite</a></span></div>
<div class="MsoNormal">
<br /></div>
</div>
</div>
