---
title: 'White Nose | Scene 3'
date: '2017-07-22T04:10:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6027245629970741358'
blogger_filename: '/2017/07/white-nose-scene-3.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
---

<div dir="ltr">
The Aleve took effect with the help of two breakfast whiskey sours. It had been three days since his tussle in town and he still couldn't sleep, despite the nighttime cocktail.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Beams of light broke through the trees outlining Ash's house, tucked back off of the main road by a mile long rock driveway. One such beam was tanning his pale country face as he rocked on an old wooden chair he'd carved himself. Whittling was one of his most relaxing and profitable talents.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
One look in the mirror each summer reminded him that he only retained two colors, pale Irish freckle and redneck red. Ash was careful to avoid too much contact with summer's star.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Dust down the drive revealed the presence of a visitor before the sound of tires on gravel confirmed it. Ash hasn't been visited by more than three people in the eight years he'd been back in town, so he picked up the hunting rifle, just in case.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
The scope showed the local sheriff, his friend Dan. He didn't usually come by unannounced. He kept the rifle on his lap, it made him feel better.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Dan pulled up followed by real other squad cars. He got out first, walked to the porch, and say down next to Ash on the other rocking chair.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
"Any chance you've lost a weapon or sold one recently"</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
"No, can't say that I....<br /><br />TBC</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Darrell<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /></div>
