---
title: 'Valley Seasons Church Notes'
date: '2017-06-11T20:01:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5192498569305040282'
blogger_filename: '/2017/06/valley-seasons-church-notes_11.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Church Notes'
---

<br />
<br />
<br />
Pastor JO<br />
<br />
Heart Of The City Church<br />
June 10, 2017<br />
====================================<br />
Mountains, Valleys &amp; Plains Part 2<br />
null<br />
http://bible.com/events/230949<br />
====================================<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span>• You have to learn to live with and in the valleys.<br />
<br />
II Corinthians 11:23-27 NKJV<br />
Are they ministers of Christ?—I speak as a fool—I am more: in labors more abundant, in stripes above measure, in prisons more frequently, in deaths often. From the Jews five times I received forty stripes minus one. Three times I was beaten with rods; once I was stoned; three times I was shipwrecked; a night and a day I have been in the deep; in journeys often, in perils of waters, in perils of robbers, in perils of my &nbsp;own countrymen, in perils of the Gentiles, in perils in the city, in perils in the wilderness, in perils in the sea, in perils among false brethren; in weariness and toil, in sleeplessness often, in hunger and thirst, in fastings often, in cold and nakedness—<br />
http://bible.com/114/2co.11.23-27.NKJV<br />
<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span>• &nbsp;Paul knew about mountain top experiences but he knew about the valleys. I can do all things means that I can handle both the full seasons and the empty seasons. How you handle the emtpy seasons will determine the outcome and quality of your life.<br />
<br />
I Kings 20:28 NKJV<br />
Then a man of God came and spoke to the king of Israel, and said, “Thus says the Lord : ‘Because the Syrians have said, “The Lord &nbsp;is God of the hills, but He is not God of the valleys,” therefore I will deliver all this great multitude into your hand, and you shall know that I am the Lord .’ ”<br />
http://bible.com/114/1ki.20.28.NKJV<br />
<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span>• Note: God says he'll fight because of what others said about Him. He will show off on your behalf to show himself as God.<br />
<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span>• I'm in a valley season right now. I feel like God has abandoned me. I know he hasn't but I feel like he has.<br />
<br />
<br />
Valley Of Attention<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span>• God may either bring you to or allow a valley season because He wants your attention.<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span>• When God seems delayed you get tempted to make your own provision (Golden Calf).<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span>• If another human gets your primary attention you'll be let down.<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span>• Come to Heart of the City Church and get offended. Because we're human. But what do you do with that offence? How you handle it is how you will choose the direction of your life. Offense brings pain.<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span>• Pain.<br />
<span class="Apple-tab-span" style="white-space: pre;">		</span>○ If you respond to pain the right way it will make you better.<br />
<span class="Apple-tab-span" style="white-space: pre;">		</span>○ If you respond to pain the wrong way it will make you bitter.<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span><br />
<br />
<br />
Valley Of Preparation<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span>• Jonah went through a valley preparation due to his own disobedience.<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span>• You're somewhere in the future and you look much better than you do right now. (Song?)<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span>KimClement<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span>You're somewhere in the future and you look much better than you look right now! We here at House of Destiny look forward to welcoming you into our family. It is our desire to help you reach your fullest potential in your life as you grow in your walk with God.<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span>https://www.kimclement.com/partner.php<br />
<span class="Apple-tab-span" style="white-space: pre;">	</span><br />
<span class="Apple-tab-span" style="white-space: pre;">	</span>• I'm in the season of rebuild. It's time to be stripped down to the frame, old parts removed, some replaced and others rebuilt and still others modified. Cylinders bored out for more capacity, new aftermarket performance parts installed... Powder coating to prevent corrosion... Repainted and repackaged... Ready for the next season of performance which will look nothing like today or the past.<br />
<br />
Isaiah 40:4 NKJV<br />
Every valley shall be exalted And every mountain and hill brought low; The crooked places shall be made straight And the rough places smooth;<br />
http://bible.com/114/isa.40.4.NKJV<br />
<br />
Darrell Wolfe<br />
<div>
<br /></div>
<br />
<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell
G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
<div class="MsoNormal">
<br /></div>
