---
title: 'Daily Diet | Through His Spirit | #BeStillBeLed'
date: '2017-01-30T13:59:00.0020000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4533751518127865480'
blogger_filename: '/2017/01/daily-diet-through-his-spirit.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Spiritual Growth'
---

<br /><a href="https://www.biblegateway.com/passage/?search=1+Corinthians+2%3A9-10&amp;version=ESV" target="_blank">1 Corinthians 2:9-10 English Standard Version (ESV)</a><br /><blockquote class="tr_bq">
9 But, as it is written,<br /><br /><i>“What no eye has seen, nor ear heard,<br />    nor the heart of man imagined,<br />what God has prepared for those who love him”—&nbsp;</i></blockquote>
<blockquote class="tr_bq">
10 these things <b>God has revealed to us through the Spirit</b>. For the Spirit searches everything, even the depths of God.</blockquote>
<a href="https://www.biblegateway.com/passage/?search=1+Corinthians+2%3A9-10&amp;version=AMP" target="_blank">1 Corinthians 2:9-10Amplified Bible (AMP)</a><br /><blockquote class="tr_bq">
9 but just as it is written [in Scripture],<br /><br /><i>“Things which the eye has not seen and the ear has not heard,<br />And which have not entered the heart of man,<br />All that God has prepared for those who love Him [who hold Him in affectionate reverence, who obey Him, and who gratefully recognize the benefits that He has bestowed].”&nbsp;</i></blockquote>
<blockquote class="tr_bq">
10 For <b>God has unveiled them and revealed them to us through the [Holy] Spirit;</b> for the Spirit searches all things [diligently], even [sounding and measuring] the [profound] depths of God [the divine counsels and things far beyond human understanding].</blockquote>
<br /><div style="text-align: center;">
***</div>
<br /><br />Today I had no particular chapter and verse in mind, so I picked up my bible and it opened to 1 Corinthians 2. I read through chapters 2 and 3; and a verse that I had previously highlighted kept sticking out in my heart/mind.&nbsp;<div>
<br /></div>
<div>
<b>But God...</b></div>
<div>
<br /></div>
<div>
I always enjoy a good "But God". This or that awful thing happened, But God.... This or that truth about life is solid, But God... This or that giant has come to challenge us, But God...&nbsp;</div>
<div>
<br /></div>
<div>
<b>But God has revealed them to us through His Spirit.</b><br />Revealed what? The things which no eye has seen or ear heard. In other words, how can I know God's will and plan for my life, day, weeks, month, year....&nbsp;</div>
<div>
<br /></div>
<div>
By getting in touch with His Spirit.&nbsp;</div>
<div>
<br /></div>
<div>
The HolySpirit is my guide, helper, teacher. It is the HolySpirits job to show me what I need to know to walk with him, and He Loves me, and He enjoys me, and He loves surprising me with things.<br /><br />Let's say that life has done what life does, and I end up with a need for X.&nbsp;</div>
<div>
<br /></div>
<div>
Some of the people in churches I've been to would go grab a verse that applies and shout: "In the name of Jesus, according to His word ____fill in verse here___ I demand X come into my life."</div>
<div>
<br /></div>
<div>
That's not wrong, but it's woefully incomplete. Rather, let's start by hearing God. You see, some circles call that faith, but faith requires hearing first. If you paused, prayed, and heard God and he gave your that verse and those words, then it would be faith. But if you just decided to do it, or did it because you heard someone else do it, it's not faith.</div>
<div>
<br /></div>
<div>
Faith comes by hearing. Not reading. Not even hearing someone else. Faith comes by hearing God's active voice. This is where it gets tricky. You see, the bible is not God's word. The bible is a book that contains God's word. It's dead words on a page until he actively (in the present) speaks them to you.&nbsp;</div>
<div>
<br /></div>
<div>
So you can get faith by reading the bible&nbsp;if God speaks it to you. Or you can read it and walk away dead (like the Pharisees). It's only when God (in the present here and now) speaks to you that you can then respond in faith.</div>
<div>
<br /></div>
<div>
Now, God can speak through the bible or through a preacher or friend... and you can respond in faith.&nbsp;</div>
<div>
<br /></div>
<div>
So, it's not faith because you found a verse. It's not faith because you heard a preacher or friend do it and you believed it. It's faith when God speaks it and you believe it.</div>
<div>
<br /></div>
<div>
So, back to this verse. God has revealed the things we haven't heard before to us through the HolySpirit.&nbsp;</div>
<div>
<br /></div>
<div>
So it's time to spend time hearing God's voice through His HolySpirit.&nbsp;</div>
<div>
<br /></div>
<div>
Next time you sit down for a quiet moment with God, don't just jump into your devotional, chapter, whatever... pause. Listen. See where He will direct you for that moment in time. He may just want to say: "Hi, I love you." Or He may want to give you a crucial piece&nbsp;of instruction to the next portion of your life.<br /><br /><b>#BeStillBeLed</b><br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
<br />
<div class="MsoNormal" style="-webkit-text-stroke-width: 0px; color: black; font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-caps: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px;">
</div>
<br />
<div class="MsoNormal" style="-webkit-text-stroke-width: 0px; color: black; font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-caps: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px;">
<div style="margin: 0px;">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
</div>
</div>
</div>
