---
title: 'Eternity'
date: '2017-05-21T19:46:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4253445376401111786'
blogger_filename: '/2017/05/eternity.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

Heart of the City Church
May 20, 2017
====================================
The Eternal Season
null
http://bible.com/events/220385
====================================

John 8:31-32 NKJV
Then Jesus said to those Jews who believed Him, “If you abide in My word, you are My disciples indeed.  And you shall know the truth, and the truth shall make you free.”
http://bible.com/114/jhn.8.31-32.NKJV

II Peter 2:1-3 NKJV
But there were also false prophets among the people, even as there will be false teachers among you, who will secretly bring in destructive heresies, even denying the Lord who bought them, and bring on themselves swift destruction. And many will follow their destructive ways, because of whom the way of truth will be blasphemed. By covetousness they will exploit you with deceptive words; for a long time their judgment has not been idle, and their destruction does not slumber.
http://bible.com/114/2pe.2.1-3.NKJV

John 14:6 NKJV
Jesus said to him, “I am the way, the truth, and the life. No one comes to the Father except through Me.
http://bible.com/114/jhn.14.6.NKJV

II Peter 2:4-11 NKJV
For if God did not spare the angels who sinned, but cast them down to hell and delivered them into chains of darkness, to be reserved for judgment; and did not spare the ancient world, but saved Noah, one  of eight people , a preacher of righteousness, bringing in the flood on the world of the ungodly; and turning the cities of Sodom and Gomorrah into ashes, condemned them to destruction, making them an example to those who afterward would live ungodly; and delivered righteous Lot, who  was oppressed by the filthy conduct of the wicked (for that righteous man, dwelling among them, tormented his righteous soul from day to day by seeing and hearing their lawless deeds)— then  the Lord knows how to deliver the godly out of temptations and to reserve the unjust under punishment for the day of judgment, and especially those who walk according to the flesh in the lust of uncleanness and despise authority. They  are presumptuous, self-willed. They are not afraid to speak evil of dignitaries, whereas angels, who are greater in power and might, do not bring a reviling accusation against them before the Lord.
http://bible.com/114/2pe.2.4-11.NKJV

Matthew 25:41-46 NKJV
“Then He will also say to those on the left hand, ‘Depart from Me, you cursed, into the everlasting fire prepared for the devil and his angels:  for I was hungry and you gave Me no food; I was thirsty and you gave Me no drink;  I was a stranger and you did not take Me in, naked and you did not clothe Me, sick and in prison and you did not visit Me.’ “Then they also will answer Him, saying, ‘Lord, when did we see You hungry or thirsty or a stranger or naked or sick or in prison, and did not minister to You?’  Then He will answer them, saying, ‘Assuredly, I say to you, inasmuch as you did not do it to one of the least of these, you did not do it to Me.’  And these will go away into everlasting punishment, but the righteous into eternal life.”
http://bible.com/114/mat.25.41-46.NKJV

Matthew 25:30 NKJV
And cast the unprofitable servant into the outer darkness. There will be weeping and gnashing of teeth.’
http://bible.com/114/mat.25.30.NKJV

Matthew 5:22 NKJV
But I say to you that whoever is angry with his brother without a cause shall be in danger of the judgment. And whoever says to his brother, ‘Raca!’ shall be in danger of the council. But whoever says, ‘You fool!’ shall be in danger of hell fire.
http://bible.com/114/mat.5.22.NKJV

Mark 9:43-48 NKJV
If your hand causes you to sin, cut it off. It is better for you to enter into life maimed, rather than having two hands, to go to hell, into the fire that shall never be quenched—  where ‘Their worm does not die And the fire is not quenched.’ And if your foot causes you to sin, cut it off. It is better for you to enter life lame, rather than having two feet, to be cast into hell, into the fire that shall never be quenched—  where ‘Their worm does not die, And the fire is not quenched.’ And if your eye causes you to sin, pluck it out. It is better for you to enter the kingdom of God with one eye, rather than having two eyes, to be cast into hell fire—  where ‘Their worm does not die And the fire is not quenched.’
http://bible.com/114/mrk.9.43-48.NKJV

I Timothy 2:3-4 NKJV
For this is  good and acceptable in the sight of God our Savior, who desires all men to be saved and to come to the knowledge of the truth.
http://bible.com/114/1ti.2.3-4.NKJV

II Peter 3:9 NKJV
The Lord is not slack concerning His promise, as some count slackness, but is longsuffering toward us, not willing that any should perish but that all should come to repentance.
http://bible.com/114/2pe.3.9.NKJV

Heaven Is a Real Place

Genesis 2:4 NKJV
This is the history of the heavens and the earth when they were created, in the day that the Lord God made the earth and the heavens,
http://bible.com/114/gen.2.4.NKJV

Revelation 21:1-8 NKJV
Now I saw a new heaven and a new earth, for the first heaven and the first earth had passed away. Also there was no more sea. Then I, John, saw the holy city, New Jerusalem, coming down out of heaven from God, prepared as a bride adorned for her husband. And I heard a loud voice from heaven saying, “Behold, the tabernacle of God is with men, and He will dwell with them, and they shall be His people. God Himself will be with them and  be their God. And God will wipe away every tear from their eyes; there shall be no more death, nor sorrow, nor crying. There shall be no more pain, for the former things have passed away.” Then He who sat on the throne said, “Behold, I make all things new.” And He said to me, “Write, for these words are true and faithful.” And He said to me, “It is done! I am the Alpha and the Omega, the Beginning and the End. I will give of the fountain of the water of life freely to him who thirsts. He who overcomes shall inherit all things, and I will be his God and he shall be My son. But the cowardly, unbelieving, abominable, murderers, sexually immoral, sorcerers, idolaters, and all liars shall have their part in the lake which burns with fire and brimstone, which is the second death.”
http://bible.com/114/rev.21.1-8.NKJV

