---
title: 'Idols | Images of the heart that take you away from God''s Love.'
date: '2017-03-14T14:47:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2725038759354359228'
blogger_filename: '/2017/03/idols-images-of-heart-that-take-you.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Love and Marriage'
  - 'Spiritual Growth'
---

<h3>
Can you imagine carving a wooden statue, bowing down to it, and calling it your god?</h3>
<br />
<h4>
It sounds ridiculous, right? Nobody in modern western culture would bow down to a wood statue, that's just stupid.</h4>
<br />
I've read about "Idols" all my life. I always wondered, why would these ancient people be so dumb as to bow down and worship a wooden statue? I mean, how ignorant do you have to be?<br />
<br />
However, that got me thinking... if the entire ancient world (for most of Israel's history) had this issue with idols... there must be something more to it. Maybe, just maybe, we still deal with idols in the United States of America in 2017.<br />
<br />
The following chapter has been my meditation for a few months now. I thought I'd share my thoughts about idols.:<br />
<blockquote class="tr_bq">
<a href="http://www.biblestudytools.com/nkjv/ezekiel/14.html">Ezekiel 14 NKJV</a><br />
1 Now some of the elders of Israel came to me and sat before me. 2 And the word of the Lord came to me, saying,&nbsp;</blockquote>
<blockquote class="tr_bq">
3 "Son of man, <b>these men have set up their <a href="http://biblehub.com/hebrew/1544.htm">idols</a> in their hearts</b>, and <b>put before them that which causes them to stumble into iniquity</b>. Should I let Myself be inquired of at all by them? 4 Therefore speak to them, and say to them, 'Thus says the Lord God: "Everyone of the house of Israel who sets up his idols in his heart, and puts before him what causes him to stumble into iniquity, and then comes to the prophet, <b>I the Lord will answer him who comes, according to the multitude of his idols, 5 that I may seize the house of Israel <u>by their heart</u>,</b> because they are all estranged from Me by their idols." '&nbsp;</blockquote>
<blockquote class="tr_bq">
6 "Therefore say to the house of Israel, 'Thus says the Lord God: "Repent, turn away from your idols, and turn your faces away from all your abominations. 7 For anyone of the house of Israel, or of the strangers who dwell in Israel, who separates himself from Me and <b>sets up his idols in his heart and puts before him what causes him to stumble into iniquity</b>, then comes to a prophet to inquire of him concerning Me, I the Lord will answer him by Myself. 8 I will set My face against that man and make him a sign and a proverb, and I will cut him off from the midst of My people. Then you shall know that I am the Lord. 9 And if the prophet is induced to speak anything, I the Lord have induced that prophet, and I will stretch out My hand against him and destroy him from among My people Israel.&nbsp;</blockquote>
<blockquote class="tr_bq">
10 And they shall bear their iniquity; the punishment of the prophet shall be the same as the punishment of the one who inquired, 11 that the house of Israel may no longer stray from Me, nor be profaned anymore with all their transgressions, <b>but that they may be My people and I may be their God</b>," says the Lord God.' "&nbsp;</blockquote>
<br />
<h4>
Definitions for our purposes today:</h4>
<b>Iniquity</b>: Consequence of Sin / Bent toward sin<br />
<br />
<b>Hypocrite</b>: Crete (speak) Hippa (underneath), one who speaks underneath. An Actor, pretender, one who speaks in the&nbsp;covert&nbsp;instead of the overt.<br />
<br />
<b>Idol</b>: An Image. The word from which we get: Imagination.<br />
<br />
<br />
<h4>
Breaking it down, what is an idol?</h4>
<b>Representation</b>: At the most basic level, the ancient people were not worshiping a statue. They didn't believe that the statue was their god. They believed that the statue was a physical representation of their god, something with which to focus their minds on during worship. The "real god" was out there somewhere, but this gave them something to look at, focus on, and talk to.<br />
<br />
<b>Heart Issue vs Physical Issue</b>: When you look at this verse in&nbsp;Ezekiel 14, you see that <b>an Idol is set up in the heart.</b> Worshiping an idol is worshiping an image, idea, ideal, thought, or imagination that counters God's image for you and your life or counters anything about who God is.<br />
<br />
<b>An Idol is</b> an image/want/thought/ imagination/desire turned into a movie in my head that sounds better than what I have right now and makes me want to pursue that desire despite what God has said about it.<br />
<br />
When any image (imagination) causes me to want God, or the things of God, less... it is an <b>Idol In My Heart</b>.<br />
<div>
<br />
<br />
<h4>
Self-Stumbling, who needs the devil?</h4>
You ever have a song stuck in your head, maybe from a commercial? All someone has to do is start the song, and you will finish it, even if only in your head. Think of your weaknesses, the desires you entertain but shouldn't as songs. He doesn't have to hold your hand all the way into sin. All the devil has to do is start the song, and you'll finish it.<br />
<br />
When I entertain images in my heart that counter God's image for me, I am setting myself up to stumble. Nobody else put that stumbling block in front of me, I did it to myself. Sure, the devil may have started the song, but I finished on my own just fine.&nbsp;</div>
<br />
We all have these, areas that we are prone to wonder in, mire in, linger in... look too long at.<br />
<br />
For me, it was Pornography and Sex. Stare just a little longer at that girl across the way, imagine what it would be like to be with her. I'm not even looking for hardcore porn, just noticed an advertisement or a Facebook post... and I lingered there. That old song starts playing.<br />
<br />
Once that song starts playing, I can make more and more room for that image. And the more room I make, the more room it takes... until it becomes and all-consuming fire.<br />
<br />
<b>Iniquity </b>can either be called the Consequence of Sin or the Bent Toward Sin.Therefore, When you set up images in your own heart, causing yourself to stumble, you create a bent (habit, tendency, pattern) toward sin... it gets easier and easier to go back; easier and easier to go further.<br />
<div>
<br /></div>
<br />
<h4>
Did you betray God and commit spiritual adultery?</h4>
Long, LONG, before you ever committed physical adultery (or insert your sin here), you committed spiritual adultery (also known as Idolatry).<br />
<br />
Only God should be that all-consuming fire in our heart (<a href="http://biblehub.com/deuteronomy/4-24.htm" target="_blank">Deut 4:24</a> &amp; <a href="http://biblehub.com/hebrews/12-29.htm" target="_blank">Hebrews 12:29</a>). Our God is out lover. He is jealous. When you set up images in your heart that counter His will for you, His place in your heart, or images of God himself that are not real to his nature... you are committing idoltry/spiritual adultery.<br />
<br />
So if you want a sure fire way to fall into Idolatry, here are the steps.<br />
<h4>
3 Steps into idolatry:</h4>
<ol>
<li>Make serving God convenient (make His Word and Presence a lower priority than other desires or pressures).</li>
<li>Add Other Things. Start feeding false images that counter his Word/Will.</li>
<li>Spiritual Departure. The images will lead you further and further from Him until you wake up one day to find yourself far, far away.</li>
</ol>
<div>
<br /></div>
<h4>
Here are the order of events as I see them in Ezekiel 14:</h4>
<ol>
<li><b>Presumption</b>: Images, once established in the heart, cause us to make provision for the image. We set up our own image and stumbling block.</li>
<li><b>Estrangement</b>/Adultery: Images counter to God are spiritual adultery/affair. They cause us to separate ourselves from God, God's Will, God's True Image (of us and Him).</li>
<ul>
<li>Jer 3:9-14</li>
</ul>
<li><b>Consequences </b>(verse 10): They (<i>the person who sets up a counterfeit image in their own heart</i>), will bear (<i>have in and on themselves</i>) their iniquity (<i>consequence/bent</i>).&nbsp;</li>
<ul>
<li><b>Association</b>: Anyone who participates or supports this person will suffer the same fate.</li>
</ul>
<li><b>GRACE</b>: God's ultimate plan is to brings us back to Him.</li>
</ol>
<br />
<h4>
GRACE</h4>
Sin will not affect God's love for you; however, sin will affect your love for God. Sin&nbsp;separates&nbsp;the heart and makes you deaf to his voice. Tuning into Sin tunes out God.<br />
<br />
God loves you more than you could possibly understand. God is so passionate about the object of His love that he will not stand for anything to harm the object of His love; even when the thing causing the harm is the object of His love.<br />
<br />
If you are being harmed by sin, and you are because it brings death, God will step in and try to bring you out of it and bring you back to Himself. You are never too far gone for God.<br />
<br />
<blockquote class="tr_bq">
<b>Sin creates distance but does not diminish His love for you.</b></blockquote>
Some make the mistake of seeing a set of verses like this and seeing an angry God. Nothing could be further from the truth. God is passionately in love with you, and he doesn't want to see you hurt.<br />
<br />
The natural by-product of sin is death, as the natural by-product of jumping from a roof is falling to the ground. He doesn't want to see death in your life. He didn't bring the death, it was just a consequence. He wants to prevent death, or heal it if you persist into it.<br />
<br />
<i><br /></i>
<i>Those are the thoughts perculating in my mind, more to come,</i><br />
<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span> <span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
<div class="MsoNormal">
<br /></div>
