---
title: 'An Open Letter: John Stumpf, Wells Fargo Board, and Policy Making Departments'
date: '2017-07-21T04:37:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7507548989472793081'
blogger_filename: '/2017/07/an-open-letter-john-stumpf-wells-fargo.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Leadership'
  - 'Banking'
---

<br />
On 12/28/13, I wrote the following letter to the&nbsp;then CEO &amp; President of Wells Fargo, John Stumpf. It was in part, a response to the LA Times Article and the poor response from Wells Fargo leadership.<br />
<br />
I later worked for the executive office and saw how they handle these letters. They assign them to a paper-pusher who could care less. They draft a form response, and it gets tallied in the statistics.<br />
<br />
By the time it makes it to the CEO, it's only data in a pie chart. "We had 365 complaints this month. x number of complaints about checking, y number about sales practices, Etc." They tally it up, if it's not a big enough stat, it gets zero attention. Most things that do require attention get just enough to make it go away, but never deal with the root.<br />
<br />
I was one of many hundreds who spoke up loudly and actively for years before 2013 and years after. The news cycle of 2016 showed that it cost them $185 Million dollars to ignore the feedback their frontline Team Members tried to give them.<br />
<br />
The final straw for me and my 11-year career with Wells Fargo came when they promoted Tim Sloan to CEO. I'd been watching Tim since he gave the official Wells Fargo response to the LA Times article about the sales goals issues. He said:<br />
<br />
<i>"I'm not aware of any overbearing sales culture," Chief Financial Officer Timothy Sloan said in an interview. LA Times article "<a href="http://www.latimes.com/business/la-fi-wells-fargo-sale-pressure-20131222-story.html" target="_blank">Wells Fargo's pressure-cooker sales culture comes at a cost</a>", published on 12/21/2013.</i><br />
<br />
When I saw that they replaced John Stumpf with an even more willingly ignorant leader, Tim Sloan, I made my escape.<br />
<br />
I'm happy I left the mega-bank. I hope the sales industry can do better. A true consultative approach. I help you get what you WANT and NEED and I benefit. That's true sales, which hasn't existed for a long time.<br />
<br />
Since that period of my life is over, the results are all public now anyway, I feel free to share this letter from 2013. Maybe other CEOs or future CEOs could learn from their mistake.<br />
<br />
I hope you enjoy:<br />
<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span> <span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a><br />
<br />
<br />
<h1>
TO: John Stumpf, Wells Fargo Board, and Policy Making Departments<o:p></o:p></h1>
<h1>
FROM: Darrell G. Wolfe<o:p></o:p></h1>
<h2>
WhoAmI<o:p></o:p></h2>
<div class="MsoNormal">
My name is Darrell G. Wolfe. I’ve worked for Orange Phone Banker (Consumer, Premier, and IRA), Westlake Phone Bank (Consumer, Banker Coach), Branches as personal banker (various in DFW), and Westlake Inbound Sales. I’ve taken over 95,000 phone calls for the Wells Fargo Call Center network between service and sales. <o:p></o:p></div>
<div class="MsoNormal">
I’ve spent 8 years working for Wells Fargo in two states, two call centers, multiple positions, and several branches. I am a leader in sales and service and I provide constant value to my team, providing insight into their calls, and helping my teams succeed one customer situation at a time. I’ve been a Banker Coach, Navigator, Rising Star, MVP, and won several Service Excellence Awards. <o:p></o:p></div>
<div class="MsoNormal">
I fully bought into the Wells Fargo Vision and Values, and I’ve lived them every day of my career. I’ve been passionate about the Wells Fargo &amp; Co. Brand and a Wells Fargo evangelist for many years. That passion has turned to sadness as I see a company void of even pretending to live by those standards on the front lines, in all lines of business. <o:p></o:p></div>
<h2>
Wells Fargo at a Crossroads<o:p></o:p></h2>
<div class="MsoNormal">
Wells Fargo Bank has a strong reputation for being conservative, strong, and stable because we don’t lend to people we shouldn’t lend to, we keep strong reserve requirements, and we have a strong reputation… which I believe has been slowly degrading since 2008… maybe since 1998… &nbsp;<o:p></o:p></div>
<div class="MsoNormal">
Ever since the Norwest Merger Wells Fargo has slowly lost a reputation of doing what’s right for the customer at the grass roots level. You may find an article here or there by a bank-industry magazine that fluffs our image, but the street isn’t saying good things, and it’s been heading in the wrong direction ever since I came in 2006.<o:p></o:p></div>
<div class="MsoNormal">
Sales are fine, but sales without integrity are not fine, and Wells Fargo &amp; Co. has not demonstrated to me in my 8-year career the high level of integrity at the Community Banking or Phone Bank Level that we have in our written literature, for some time now. We may be treating our highest net worth clients well, and our business clients well, and since those relationships account for 80% of more of our profits we’ll likely be in business for some time to come. <o:p></o:p></div>
<div class="MsoNormal">
But I am personally and professionally appalled at how we (as an institution) treat the everyday person. <o:p></o:p></div>
<div class="MsoNormal">
Blind visits to branches by independent auditors and impartial phone call observations I believe would reveal a bank that is far more interested in selling you more things you don’t need than servicing what you have. <o:p></o:p></div>
<div class="MsoNormal">
I actually just talked to a young lady who had been a Sales Banker for BofA for 8 years came to Wells Fargo one month ago only to discover that even though our sales “goals” are lower the pressure we put on the sales people to sell, the micromanaging, is higher. In my opinion, we don’t even know the basics of customer service. As a company, we’re so focused on sales we skip service to meet our sales goals. <o:p></o:p></div>
<div class="MsoNormal">
In short, we’ve been on the slow road to becoming the next Bank of America: “the bank too big to care about the little guy.” <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<h2>
Positive Memorable Customer Experience<o:p></o:p></h2>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
For years I heard the words FCR (First Call Resolution) and PME (Positive Memorable Customer Experience). I don’t hear that talked about at all anymore. When a bad experience is had by a person they are likely to share that with 10-15 people in their circle of influence. But more importantly, people don’t buy products and services. They don’t buy from companies. They pay for BRANDS they trust from PEOPLE they trust. But they don’t buy a product. They PAY for a product. <o:p></o:p></div>
<div class="MsoNormal">
They BUY how that product or service will make them feel, they buy the experience. Think of the iPhone. Not only is it a TOP OF THE LINE product, but it comes in an amazing package, it’s stylish, it’s enviable. They aren’t buying an iPhone, they are buying connections to their friends and family (facebook/twitter apps), they are buying time savings apps (better connectivity to schedule and tasks), etc. <o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
There are many amusement parks, but only Disney creates a magical experience, there is no other like Disney. They don’t sell rides, they sell a magical experience, and rides are weaved into that tapestry, and so our products and services and popcorn balls, and overpriced burgers… but you willingly pay more because you are there for the experience. My wife is convinced that there is no other cruise ship company worth using except Disney Cruises, and so am I. I am loyal to the brand, because they create magical experiences, they do it seamlessly, they do it consistently and they are always raising the bar for themselves, out doing themselves every time I visit a Disney facility. <o:p></o:p></div>
<div class="MsoNormal">
Wells Fargo has turned this concept on its head. If Wells Fargo ran Disney Land we’d have cast members chasing people into the street trying to convince them to buy another lemonade when they had one in each hand already and pressuring them to buy a third “just for emergencies”. We regularly put sales ahead of customer experience. We pay very little but lip service to the customer experience. And that’s been consistent across two states, two call centers, four departments, 4 branches, and conversations with many people from other places in Wells Fargo. <o:p></o:p></div>
<h2>
Goals vs People<o:p></o:p></h2>
<div class="MsoNormal">
My experience at Wells Fargo &amp; Co. has been that we love our goals, stats, and spread sheets. We’re more interested in meeting goals than we are interested in how those goals are affecting the Positive Memorable Customer Experiences, both with our External Customers (customers) and Internal Customers (Employees). Most goals feel as though the goals are set for the sake of the goal. <o:p></o:p></div>
<div class="MsoNormal">
Unnecessarily overly complicated ICP/MPP systems are set up in twisting curves of “if this then that” formulas every winding into more and more metrics to keep track of, all in the name of meeting the goals. But for what? What happens over the next 20 years if we lose our loyal customers to smaller banks that can provide positive memorable customer experiences while we were trying to track our goals? <o:p></o:p></div>
<div class="MsoNormal">
The very existing of Alabang indicates we care more about profit than customer experience. Alabang call center hardly ever meets the customers need, transfers them to sales without telling them why (or the customer understanding why). They actually speak very decent English “linguistically”, but they have very little conceptual understanding about what they are talking about. Their referrals are anything but needs-based, often reading the entire list of ECPR&nbsp;offers at (not to or with but at) the customer and receiving banker. <o:p></o:p></div>
<h2>
Phone Bank<o:p></o:p></h2>
<div class="MsoNormal">
Our service bankers are not looking for needs and meeting them. They are pushing whoever they can into the sales department to meet arbitrary goals created by people who, it seems, don’t live in the real world and don’t listen to these callers. The people who end up in sales are almost always the very young, very old, English-as-second-language (language barrier) people, or mentally disabled. These are the easiest to push over to sales without getting an objection, but almost none of them know where they were transferred or why. <o:p></o:p></div>
<div class="MsoNormal">
Specifics, ask bankers on the sales floor for any phone bank sales dept and these are the referrals they get day in and day out. These examples are not the exception they are the norm. It’s actually quite rare to have a customer transferred to sales that belong in sales and knows why they were transferred to sales. At this rate there should not be two departments, let’s just make all bankers both service and sales and blend the goals, most sales bankers spend their whole day doing service requests that service didn’t complete or transferring callers to the department they should have been transferred to in the first place. <o:p></o:p></div>
<div class="MsoNormal">
Here are examples of the calls inbound sales bankers get over and over and over:<o:p></o:p></div>
<div class="MsoListParagraphCxSpFirst" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Bill Pay</b> - Elderly Lady who doesn’t own a computer<o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Bill Pay</b> – TEEN Checking customer, the teen checking doesn’t get it for free AND they don’t have any bills! <o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Bill Pay</b> – But Online Banking shows DISABLAED and they should have been transferred to Online not sales if they really wanted it. <o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Second Savings as ODP</b>&nbsp; - To protect the “real” savings account from overdrafts in case of fraud, the account is already covered for fraud with Zero Liability so this is a scare tactic to sell un-needed products. <o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>“Online Checking</b>” – for someone who does two online purchases or less per month, really? That was finding and meeting a need? Pay a monthly service fee for two transactions a month?<o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>New Joint Checking/Savings</b> – because they couldn’t figure out how to transfer money online between other Wells Fargo customers. But setting up an account just to do transfers once in a while will have fees associated and they don’t tell them that part. <o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Second Checking</b> – Not based on expressed or discovered a need, but as a default referral. The customer isn’t managing the account they have, doesn’t want a second checking, cannot use a second checking, and often hangs up as soon as they are transferred. <o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Account Reviews</b> – customers think they’re being transferred to a fraud department or aren’t given a reason for being transferred or they are told: “You’re account has been flagged, let me a get a specialist for you”. Nearly no customer is told they are being transferred to sales for a review to discuss new products and services. <o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Debit Card</b> - They are transferred to order a debit&nbsp;card when it should have been replaced in service. <o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>New Checking/Savings</b> – when it should have been an account conversion in service<o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>ATM Card</b> – “As a back up in case you lose your Debit Card” when we offer temp debit cards, AND VL explicitly tells the banker NOT to refer a backup ATM card and they do it anyway. <o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>New Account:</b> Current Accounts are Negative/Charged Off/Opportunity<o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>CD</b>: service banker tells the customer to look into CD’s and transfers to sales with the promise of earning the customer more interest (or way more interest) but there was only $200 in their checking, no savings, and no money elsewhere. This is also common. <o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Online Banking</b>: transferred to sales for online banking but the online was disabled and it has to be handled by online customer service. <o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Order a new card:</b> when the old card should have been replaced or re-linked. <o:p></o:p></div>
<div class="MsoListParagraphCxSpLast" style="mso-list: l0 level1 lfo1; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-bidi-font-weight: bold; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b><u>Just to name a few<o:p></o:p></u></b></div>
<div class="MsoNormal">
<br /></div>
<h2>
ECPR is our enemy, not our friend. <o:p></o:p></h2>
<div class="MsoNormal">
When I was a service banker the referral would sound like this: “I see here you are using ACH to make payments. ACH can cause problems, lead to overdrafts, and you are open to the potential of merchants taking money you didn’t agree on, or other errors. To prevent that we offer our Bill Pay service. It prevents overdrafts by taking the money our first, and errors by not ever giving your account number or card number to the merchant. Do you use our online right now? Great, you’ll use the same username and password to access Bill Pay. Let me get one of my specialists on the line to activate that for you, ok?” <o:p></o:p></div>
<div class="MsoNormal">
Now they sound like this: Banker sees Bill Pay in ECPR “I see here you’re Bill Pay hasn’t been activated yet, let me get someone to take care of that for you…”. The customer comes over and their online is disabled because they don’t use online banking and have no use for Bill Pay. <o:p></o:p></div>
<div class="MsoNormal">
Bankers are not making needs based referrals, they just offer what it’s in ECPR because it’s there, and what’s in ECPR is almost never the right thing for the customer. They aren’t even putting basic common sense or thought into it. If ECPR is to continue, it would make sense to say “I see this customer has an offer for Bill Pay, let me ask some questions.<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoNormal">
In short our service department lies, misrepresents, or mishandles customer more often than not. It’s not just phone bank though. <o:p></o:p></div>
<h2>
The Branch<o:p></o:p></h2>
<div class="MsoNormal">
When I did my year and a half tour at the branch I saw the same thing. Praise is given for sales credit despite how it is made. The people that broke the most rules to meet goals were promoted the ones who stayed honest and couldn’t meet goals were asked to leave. The role of the sales banker at the branch is to sell products for sale's sake, not because it’s doing what’s right for the customer. <o:p></o:p></div>
<div class="MsoNormal">
They are so sales oriented that I think you would be hard pressed to find a customer who is enrolled in the debit card overdraft service that actually knows what it is and that they were signed up for it. Bankers are just enrolling them without telling them to meet pressure from their managers. <o:p></o:p></div>
<div class="MsoNormal">
They open products people don’t need, when things really get tight the manager comes to you and tell you to open accounts for your friends and/or family and keep them open for 45 days and close them. <o:p></o:p></div>
<div class="MsoNormal">
Working for Wells Fargo branches was like working for a sleazy used car dealer (I worked several branches in DFW), but it’s so hard to meet sales goals that the banker doesn’t even get the commission the used car salesman would have gotten. The managers weren’t bad or evil, the one of the district managers might have been, but the pressure to meet goals rolls downhill. <o:p></o:p></div>
<div class="MsoNormal">
Examples of patterns (not isolated incidents) at the branches are:<o:p></o:p></div>
<div class="MsoNormal">
<br /></div>
<div class="MsoListParagraphCxSpFirst" style="mso-list: l1 level1 lfo2; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Pushing people into the Debit Card Overdraft Service:</b> the customer isn’t right for the debit card overdraft service, the pros and cons are not being clearly explained, the customer isn’t sure it’s right and the banker/manager gets pushy and argues with the customer that they really need it. They stop just short of demanding it. In fact, in MANY MANY cases the customer is being enrolled without even asking, or they are told in passing they are going to enroll the customer without telling them what it is. <o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo2; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Second Savings:</b> opening a second savings for someone who can barely save in the first savings and they customer ends up with TWO savings with monthly service fees and no money in either, all under the guise of having one “real savings” and one “overdraft savings”, just to get a sale. <o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo2; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Second Checking:</b> but the customer cannot even manage the one account they have.<b> </b><o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo2; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Bankers open opportunity accounts:</b> but doesn’t explain to the customer what that means. <o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo2; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Bankers take application:</b> then avoid telling the customer the loan app status, lie and tell the customer that they don’t know to avoid confrontation. <o:p></o:p></div>
<div class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo2; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Open New Checking:</b> instead of just converting the account they already have, making the customer go through un-necessary changes of direct deposits and ach set up. <o:p></o:p></div>
<div class="MsoListParagraphCxSpLast" style="mso-list: l1 level1 lfo2; text-indent: -.25in;">
<!--[if !supportLists]--><span style="font-family: &quot;symbol&quot;; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;times new roman&quot;; font-size: 7pt; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b>Open New Checking:</b> Not tell the customer what the requirements or that it would be getting a MSF. <o:p></o:p></div>
<br />
<div class="MsoNormal">
<br /></div>
</div>
<div class="MsoNormal">
A Concerned Team Member</div>
