---
title: 'Now I Lay Me Down to Sleep...'
date: '2017-05-31T07:32:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8002013836669449739'
blogger_filename: '/2017/05/now-i-lay-me-down-to-sleep.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Perspective'
  - 'Personal and Spiritual Growth'
  - 'Spiritual Growth'
---

<p dir="ltr">Idaho isn't all it was cracked up to be in my head. We got here with a few arguments along the way, but that's normal trip stuff. </p>
<p dir="ltr">Once we arrived, nothing worked. All the apartments were gone, leased between 1 day and 5 minutes before we arrived. We were stuck at a hotel an extra two weeks. </p>
<p dir="ltr">We eventually landed a small house with no central air, for more than we planned to pay before moving here, but it was clearly a God given find, so we took it.</p>
<p dir="ltr">I'd been contacted over and over for writing contracts, once I got here, those calls vanished. I ended up at an amazing company, one I think I can make a great career with, but at half the pay I was expecting before moving to Idaho (the pay those writers contracts would have paid). </p>
<p dir="ltr">We planned to attend a specific church, but once we got here it never clicked, never felt right. We found another, it's clicking, but there's a lot to miss about our home church in Texas. I miss nothing about Texas, except that church.</p>
<p dir="ltr">So... Now what? No clue. Trust God, follow his voice. See what's next...</p>
<p dir="ltr">Valla Con Dios...</p>
<p dir="ltr">We'll keep listening. We'll serve where we're planted. Take the opportunities as they come. Go from there...</p>
<p dir="ltr">#BeStill&amp;Hear</p>
