---
title: 'Freedom From vs Freedom ToBe'
date: '2017-06-01T06:43:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1373106042564043888'
blogger_filename: '/2017/05/freedom-from-vs-freedom-tobe.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Perspective'
  - 'Spiritual Growth'
---

<p dir="ltr">For many Freedom is understood through the lense if being free from...</p>
<p dir="ltr">Addiction<br>
Pain<br>
Loneliness<br>
Him/Her<br>
The Situation<br>
The Job<br>
Debt<br>
Poverty<br>
Etc.</p>
<p dir="ltr">So we follow the rat race seeking whatever we think will make us free. When that doesn't provide the freedom we sought, we seek another fix, and another... An endless cycle of seeking freedom but never being free.</p>
<p dir="ltr">What if Freedom has nothing to do with whatever jail you are in, however you've defined your personal jail.</p>
<p dir="ltr">What if Freedom is about becoming WHO you were always meant to be... And in that pursuit all the "other" (addiction, pain, the jails) falls off when you aren't even looking...</p>
<p dir="ltr">You don't know when you got "free from", you just look back and realize you don't have all the issues you had. You have battles in front of you but you have definitely won some battles too, and you didn't&#8203;even notice you had won.</p>
<p dir="ltr">It's as though the act of becoming a butterfly was so profound that you have trouble remembering what it was like to crawl.</p>
<p dir="ltr">People who lose a limb often experience phantom pains in the missing limb. This is because the neural pathways are still there even though the limb is gone.</p>
<p dir="ltr">Prescribing meds for the pain only serves to reenforce the pathway telling the brain the limb is still there. </p>
<p dir="ltr">The key is to retrain the brain, create new pathways, show the brain the limb is gone. To do this, the new nerve endings must be activated. Rubbing the new stump of the leg with a variety of materials, soft, hard, scratchy, etc., causes the brain to rewire and recognize the new stump, creating new neural pathways.</p>
<p dir="ltr">That's your job, and my job, now... Scratch the new limb. That's the purpose of prayer and Bible study, church, small groups, etc...</p>
<p dir="ltr">They are not dead religious activities, they are opportunities to scratch the new limb (your born again spirit). </p>
<p dir="ltr">Go scratch something...</p>
