---
title: 'Writers Block - How do you write when you don''t know what to write?'
date: '2017-07-22T04:08:00.0030000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3142900126211413479'
blogger_filename: '/2017/07/writers-block-how-do-you-write-when-you.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'write'
---

So, I recently had a comment on this blog. I'm not sure if it's ligit but I think that it's a question a lot of writers ask:<br />
<br />
<br />
<i>"... I was curious to find out how you center yourself&nbsp;and cⅼear your tһoughts before writіng. I have had trouble clearing my thoughts in getting my thoughts out. I truly dߋ take pleasurе in writing, however, it just seems like&nbsp;the fіrѕt 10 to 15 minutes is wasted just trying to figurｅ out how to begin. Any recommendations or&nbsp;tips? Appгеciate іt!" AnonymousJuly 1, 2017 at 4:31 PM</i><br />
<div>
<br /></div>
<br />
The way this is phrase means that this is either a spam comment or it's just a google translate comment. Not sure. Nevertheless, it's a good question.<br />
<br />
Having a mind that is clear isn't necessary for writing. Writing requires thoughts. My professor once said: "Throw up on the page, we can clean it up afterward". And that's done wonders for me. If you are going to write, just start. You could end up with something so long and winding that you need to cut it into three different posts for your blog, but you'll have started.<br />
<br />
Templates can help. Having a template with a fill in the blank header, subheader, etc, but that didn't work well for me.<br />
<br />
Lately, I'm only writing when I feel like I need to say something.<br />
<br />
For creative writing, I just close my eyes and watch the movie playing in my head. It may start with something as simple as "A beam of light pierced the window, revealing a dust highway as it found it's mark on the far wall..."<br />
<br />
Then I just watch the movie in my mind and write what I see happening. I don't worry about form or format, because that can always be cleaned up later.<br />
<br />
I wrote a whole first draft of a novel only to find out that the secondary character didn't work for this story. I cut her out, replaced her with a new character and I'm on the new draft now. The old character I cut will get her OWN novel in the next book.<br />
<br />
I hope that helps,<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span> <span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
<div class="MsoNormal">
<br /></div>
