---
title: 'Topos Consulting Questionaire'
date: '2017-09-06T16:49:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4239803226266977553'
blogger_filename: '/2017/09/topos-consulting-questionaire.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Templates'
---

<br />If you think you'd like to have me help you tell your story, work on your website, or polish your personal or business brand, just email <a href="mailto:Me@DarrellWolfe.com">Me@DarrellWolfe.com</a> and provide me the following:<br /><br /><h4>Your Contact Information:</h4><ul><li>Your Name&nbsp;</li><li>Your Position</li><li>Brand Name</li><li>Industry</li><li>Address</li><li>Telephone</li><li>Email</li><li>How did you hear about Topos Consulting?</li></ul><br />The following are questions to consider. Don't worry if you don't have the answers yet, this is part of why you are using Topos Consulting. But these will get you thinking:<br /><div><br /></div><h4>What is your story?</h4><div><ul><li>What product or service do you provide?</li><li>Why did you decide to pursue this business?</li><li>What makes you special, unique, or qualified to do this?</li><li>What is your favorite part of doing this work?&nbsp;</li><li>Why do you find it rewarding?</li><li>What value do you provide?</li><li>What impact has it had on the people you serve?</li></ul></div><h4>What are your brand elements?</h4><ul><li>Colors (Do you have RBG, or Hexidecimal Codes?)</li><li>Fonts (Georgia, Times New Roman, Etc)</li><li>Logos (or images)</li><li>Do you have digital copies for any of these?</li></ul><h4>eTools: Do you already have any of the following?</h4><div><ul><li>Website</li><li>Domain Name</li><li>Facebook Account (personal not business)</li><li>Facebook Page (business not personal)</li><li>Email List Service</li><li>Google Place Listing</li></ul></div><h4>eTools: Do you already have user ID's for any of the following?</h4><ul><li>Wordpress.Com or Blogger</li><li>Domain.com</li><li>Facebook</li><li>Google Place</li><li>MailChimp</li><li>Gumroad or another way to store and deliver the PDF?</li></ul><br />Darrell