---
title: 'Become not do'
date: '2017-06-02T06:31:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3454046171386176596'
blogger_filename: '/2017/06/become-not-do.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Perspective'
  - 'Spiritual Growth'
  - 'Freedom/Kairos'
---

<p dir="ltr">From 7 Habits of Highly Effective People:</p>
<p dir="ltr">As Emerson once put it, &#8220;What you are shouts so loudly in my ears I cannot hear what you say.&#8221;</p>
<p dir="ltr">It's one thing to put on a smile at work on a bad day because the customer doesn't need to know about that. You got a job to do. We've all had to do that and it's ok.</p>
<p dir="ltr">It's another thing to lie to those closer to you, or worse yourself. Who you are produces what you do. If those two are not aligned it creates cognitive dissonance, spiritual tremors, anxiety breakdowns.</p>
<p dir="ltr">The solution isn't to stop doing good or well... though that's exactly what you'll be tempted to do to some the cognitive dissonance.</p>
<p dir="ltr">The solution it's to become who you were created to be. As you become, your doing gets better as a byproduct.</p>
<p dir="ltr">#ScratchTheNewLimb<br>
#ChangeTheFocus</p>
<p dir="ltr">Darrell<br>
</p>
