---
title: 'Because... Parents aren&#39;t always right. #DadLessons'
date: '2017-05-20T08:52:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4231871368950029120'
blogger_filename: '/2017/05/because-parents-aren-always-right.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Just Because'
  - 'Fiction'
---

<p dir="ltr">"Because I said so!", Alex screamed, as he slammed the Bible on the table. The walls shook slightly, the reverberation of his voice trembled through the hall. His face was bright red.</p>
<p dir="ltr">The small boys face muscles scrunched up and he took a step back. Kyle could never know which behavior was going to set his Dad off again. His pulse is beating in his throat. Palms sweaty against his tiny pant legs.</p>
<p dir="ltr">Alex pointed to the back, "Go to your room. Now!"</p>
<p dir="ltr">Kyle reluctantly agreed. In trouble again, but not quite sure why this time. If only he could figure out how to ask a question without triggering world war three. </p>
<p dir="ltr">Kyle took the Lego creation he'd made earlier, the one he'd saved all day to show his Dad, the one his Dad had no time to see right now... He tossed it against the wall. Legos splattered into a million tiny plastic rain drops. He'd probably get in trouble for that too but at least he'd get some attention.</p>
<p dir="ltr">Selah</p>
