---
title: 'When things don&#39;t go the way you planned... go into Low Slow.'
date: '2017-01-25T19:22:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3467185501650656798'
blogger_filename: '/2017/01/when-things-don-go-way-you-planned-go.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Renewing the Mind (Stinking Thinking)'
  - 'Resting'
  - 'Emotions'
  - 'Freedom/Kairos'
---

<br />One step at a time, one day at a time...<br /><br />We got a 2010 Mazda Tribute, SUV, to better prepare for Idaho roads. I quit Wells Fargo this week (Sunday night). I'm working on the house, getting ready to sell. I'm looking into getting my freelance writing&nbsp;career launched full time.<br /><br />Here's a story about Low Slow:<br /><br />We saw the 2010 Mazda Tribute and I felt strongly this was our SUV. It jumped off the page and I had perfect peace about getting it. I applied for the pre-financing through USAA and it went through with no questions (miracle!).<br /><br />We went down to the AutoNation on Saturday but they couldn't get it worked out, even with USAA. The trade-in was just too high to add to the loan. We left and I felt disappointed.<br /><blockquote class="tr_bq"><b>STOP</b>: Now, this is the part of these stories where Old Dead Darrell would get dejected, complain that "maybe I can't hear God afterall", spiral into depression, and start thinking about all kinds of negative things I could do to "feel better".&nbsp;</blockquote>This time around, post-healing, Healed Darrell started to feel disappointed. But we drove to a nearby iHop and decided to celebrate anyway, even though it looked like we'd lost this one. As we sat there, I started getting into my left-brain head. Working numbers, getting antsy, etc. She saw it, and got worried. Mentioned it. I pulled back and thought about that a moment. I closed my notebook, and tried to settle down inside.<br /><br />I said: "Let's go into Low Slow". A phrase Kenneth Copeland talks about to describe getting quiet before God (instead of worked up), and listning for his direction.<br /><br />"Lord, I believe you had this car for us. Either I missed it, and it's not our car. In that case, I don't want it. Or, I didn't miss it, but I had the rest of the plan wrong. You let us know what you want us to do."<br /><br />We ate, we talked, cried a little... I went to the bathroom... While there, I had an epiphany. Why trade in the Mazda? I could see it private party. I have some tax return/401K money coming in. I can pay any difference myself. Or pay it off, then sell it. Then I'd just be buying the Tribute outright with no trade-in. I called my sales person and told him the plan and that I'd be back. I worked with USAA all Monday morning, and they said I didn't need to trade-in the Mazda3 to get the Tribute. So we went down and bought it Monday.<br /><br />All went easy... until... road noise...<br /><br />Another attempt to get me out of peace. I started hearing and feeling a&nbsp;vibration from the Tribute. It was loud and awful. I panicked. Car problems are enough to put me in a tail-spin normally too. But I went into Low Slow. Tried to stay out of panick. Prayed, looked at it. Eventually figured out the plastic housing was loose. Zip tied that down, replaced a bolt. 80% of the noise was gone, but some remained. Tires. The tires are clipping on the sides. It needs new tires and an alignment. No problem.<br /><br />Problem, again, solved. Go into Low Slow next time you have a crisis moment, and listen for God. He'll lead you out. He doesn't take us around the Valley of the Shadow of Death, but he doesn't let us camp there either. He takes us THROUGH...<br /><br /><br />So, broken or whole, "right or wrong", that's what I'm thinking about today,<br /><br />Darrell W.<br /><br />