---
title: 'Order. Chaos. In Between... The Bible'
date: '2017-08-22T07:03:00.0020000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2035221594563815342'
blogger_filename: '/2017/08/order-chaos-in-between-bible.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'News and Current Events'
  - 'Armchair Theology'
---

<h3>
The Dark Ages were primarily due to religion.&nbsp;</h3>
<div dir="ltr">
Religious leaders had the audacity to claim that only they could interpret the Word of God for the simple-minded laymen. Even clergy of lower stature couldn't read the bible. This led to the strange fantasies, whimsies, and odd ideas of any number of so-called "Priests".&nbsp;</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
Enter <a href="https://en.wikipedia.org/wiki/Martin_Luther" target="_blank">Martin Luther</a>, circa 1517 A.D. He had the outrageous claim that all men were saved by Faith, and not deeds required of them by Religious Leaders. How did he get this idea? Reading the bible for himself.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
The Reformation directly caused the Enlightenment.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
When men were allowed to read the Bible for themselves, instead of being told what to believe by so-called leaders, they found a God of order. Therefore, the Earth created by this God would have&nbsp;order.</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
This thought led to <a href="https://en.wikipedia.org/wiki/Isaac_Newton" target="_blank">Newtonian </a>Physics, printed books, engines, light bulbs, Einstein's theory of relativity...</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
All science, medical advancements, everything you drive, see, eat...</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
The next time you see a car or bus, or think that you have the "right" to speak your mind without fear of being burned at the stake... You can thank the B I B L E...&nbsp;</div>
<div dir="ltr">
<br /></div>
<div dir="ltr">
In short without men reading God's word for themselves, you'd be packing your mule cart to head to the nearest township,&nbsp; paying your tax to the king, and hoping to live to 40.&nbsp;</div>
<br />
And yet, we see a&nbsp;world of people tearing down statues because they think they are being oppressed when really they are causing a new Dark Age. ANY TIME the bible is suppressed, men do dark deeds and put each other in bondage.<br />
<br />
You need not want to read it yourself, but you should fight to the death for the right of others to do so, publicly. Without the Bible, you are headed to a dark age again. Freedom of Thought, Freedom of Religion, is only possible with that book openly discussed, read, and followed by teachers, lawyers, and politicians. Without it, we are in for a world of hurt.<br />
<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span> <span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
<div class="MsoNormal">
<br /></div>
