---
title: 'Focus... Unfocused'
date: '2017-08-27T20:00:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1860577894077462834'
blogger_filename: '/2017/08/focus-unfocused.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<p dir="ltr">There's a version of my writing that is organized, thoughtful, researched, helpful, even inspired at times... And then there's the other stuff. </p>
<p dir="ltr">The other stuff is wild, incoherent, off the cuff, straight from my mind to your eyes, unfiltered, unedited. </p>
<p dir="ltr">I've tried to separate these into different sites, combined them again, separated them again.... *sigh*</p>
<p dir="ltr">I have too many thoughts, too many opinions, I know too much to ever make any of it make coherent sense on one website.</p>
<p dir="ltr">So, here's my newest attempt to make it work... My blog, the one under my name, DarrellWolfe.com, it's for my randomness. This is where I'll post whatever I want, whatever thinking about, randomness.</p>
<p dir="ltr">I'll link out to posts at my other sites, be they few or many, and you can find the organized stuff there. </p>
<p dir="ltr">Let's see if that helps me keep some semblance of order.</p>
<p dir="ltr">Darrell Wolfe Version 1,037<br><br><br><br></p>
