---
title: 'White Noise | Distortion | Scene Two | TBC'
date: '2017-05-19T06:00:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '209617373181567442'
blogger_filename: '/2017/05/white-noise-distortion-scene-two-tbc.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
---

A few THC pills,&nbsp;more than necessary, stopped Ash's hands from shaking as he filled a short glass with ice and Jameson's. Topping it off with a sleeping pill, and the night was sure to embrace him soon.<br>
<br>
The night air bit his nose as Ash stepped out onto the patio; he'd spent worse nights than this in the deserts. Ash zipped up the sub-zero sleeping bag and settled into the hammock. Night owls and bats were still out this time of year and they're combined symphony was the final step to his sleep concoction.<br>
<br>
***<br><br>
<i>The mess hall wasn't as full this time of day. The food was dry by late afternoon but it was never very good anyway. Ash twirled spegettiini on his fork as two guys nearby chattered on about what they'd do when they get home.</i><div><i><br></i></div><div><i>Suddenly time slowed down. The roof caved in and a compression wave through him against the wall. He slid down the wall losing consciousness.&nbsp;</i></div><div><i><br></i></div><div><i>When he came-to a few moments later there was total chaos. Other buildings were collapsing, missile fire. Through the smoke, Ash saw bodies laying in contorted positions. The two men nearest him wouldn't be going home after all.</i></div><div><i><br></i></div><div><i>He had no injuries that he could feel. Ash tested his balance, nothing broken.</i></div><div><i><br></i></div><div><i>He made his way over the rubble and out through a hole in the wall. Others would care for the wounded this is what he was built for.</i></div><div><i><br></i></div><div><i>The armory. The spoters tower was gone. He grabbed his rifle and made his way to an antenna tower on the edge of camp. Through the scope Ash made out five shooters, two holding miscle launchers. He aimed at the first center mass and fired, re scoped the second launcher and fired again. The first was just falling by the time the second target was hit.</i></div><div><i><br></i></div><div><i>The remaining three were crouching behind some rocks. One ran for the hill side, then there was two. Like coke cans on a fence.</i></div><div><i><br></i></div><div><i>Two ran for the Jeep, keeping their heads down. He didn't need to see them, just the seat backs.&nbsp;</i></div><div><i><br></i></div><div><i>One</i></div><div><i><br></i></div><div><i>Zero</i></div><div><i><br></i></div><div><i>The Jeep drove off into a hillside. By this point the troops had geared up and drove out in the Hummers to ensure there were no more. His job was done.&nbsp;</i></div><div><i><br></i></div><div><i>Days later he received a note...<br></i>
<i><br></i>
<br>
***<br>
<br>
The next day, drowsier&nbsp;than usual, Ash woke to a beam of light piercing his closed eyes. A reflection from the glass sliding door. That meant it was later in the morning than Ash card to admit.</div><div><br></div><div><br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br></span> <span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
<div class="MsoNormal">
<br></div>
</div>