---
title: 'Credit Building'
date: '2017-08-19T15:34:00.0020000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4095030890789163017'
blogger_filename: '/2017/08/credit-building_19.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Credit'
  - 'Banking'
---

<p dir="ltr">I just met three people working at Carl's Jr. We had a great talk about income, credit, and demystifying credit. </p><p dir="ltr">So many people need a financial doctor and don't know it. Or they do know that they need one but don't know how easy it is to have one. </p><p dir="ltr">I gave them a few tips, my business card for credit, my friend Ben's business card for Insurance and Investments, and told them to come see me so we can get into more details.</p><p dir="ltr">They didn't realize that someone would be willing to help without having to pay a consulting fee or go or a class.</p><p dir="ltr">I love helping people. Love it. And as Zig Ziglar said: You can have anything you want in life if you help enough other people get what they want. </p><p dir="ltr">I don't concern myself with whose going to make me a sale, who I can get something from, etc. If I simply help everyone I can, without regards to my reward for it, the reward will come as a byproduct.</p><p dir="ltr">It was a great reminder that I'm on the right path.</p><p dir="ltr">Darrell</p>