---
title: 'A man, a woman, a forest and the secrets rendezvous... A story of recovery after betrayal and affair.'
date: '2017-03-13T05:25:00.0020000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '635790541371245552'
blogger_filename: '/2017/03/a-man-woman-forest-and-secrets.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Love and Marriage'
  - 'Fiction'
  - 'Spiritual Growth'
  - 'NonFiction'
---

<h4>
My Story...</h4>
This is the first of many writings I will do on this very personal topic that so radically affected and changed my life and that of my family.<br />
<br />
The last half of 2016 was the worst year of my life. I had suffered from Pornography and Sexual Addiction since I was 5 years old. That addiction created a division in my soul, two people competing for the same body. The Christian Darrell and the Sex-Addict Darrell were fighting for control. I never could gain complete mastery over the addict. I tried locking him away in a corner of my heart, but he kept getting free. That struggle culminated in my near-abandonment of everything I was and held dear.<br />
<br />
Finally, I cracked.<br />
<br />
<i>"If I can't be a whole Christian," </i>I reasoned, <i>"I will be a whole heathen."</i><br />
<br />
In October 2016, I went back to smoking, drinking, and I started having an affair. I moved into the guest room and told my wife I was leaving her, the kids, God, Jesus, Church... All of it.<br />
<br />
At the same time, I knew I wasn't in a good place. I reached out for one last chance Hail-Mary Pass. I put myself out to a Men's Small Group leader, who had a background with addicts. I showed up every Friday. I also started seeing a Christian Psychologist. I had a few talks with another friend who knew something about sexual addiction. I didn't admit to anyone, other than my Psychologist, the full breadth of my on-going decisions, but I admitted to as much as I felt I could. These didn't stop my behaviors, but they were a last attempt before cutting all ties with Christian Darrell.<br />
<br />
<h4>
But God...</h4>
On January 6th, 2017, my wife and I were discussing a pending divorce, when God stepped in. He spoke through her, and she shared the hurts and pains of her heart. As she shared her story, the shame wall that I had locked the Addict behind melted. The two partial personas evaporated, melded, and became one whole person.<br />
<br />
God miraculously delivered me from the bondage that held me captive my entire life. He healed the division in my soul and I became one whole person for the first time since I was five years old.<br />
<br />
Since that day, I've been having to work out the salvation he started in my soul. The brokenness was healed but the old thought patterns established in my brain still needed re-wiring. The mind needed to be renewed to the healing experienced in my soul/spirit.<br />
<br />
During this time, my wife and I fell in love again. She leaned in to my healing process and joined me in it.<br />
<br />
<h4>
Our Story...</h4>
However, I found it difficult to understand her side, how she felt. I didn't understand the wounds she received during my years of pain. I was so wrapped up in my own experience, I had never been through or understood her experience. I needed some help to transition from my healing to helping her with her own healing.<br />
<br />
The following story was provided for me by my wife. After I betrayed her and scarred her heart, we came together and found healing and restoration. We are now in love and building the marriage we never had.<br />
<br />
As I recovered, I was very focused on what my experience was. But every time I shared what I had been going through, I was causing her new (renewed) pain. I didn't understand. I couldn't see what her side looked like because I hadn't lived it.<br />
<br />
In an effort to help me understand her side and how it felt for her, she provided the following. It was so profound that I asked her permission to share it publicly, so it could help other Husbands and Wives. She agreed.<br />
<br />
Here is a fictionalized tale, to help Husbands hear their wives pain after an affair.... and help wives communicate it.<br />
<br />
Since this story was written, we've gone through additional healing. This was the first of several steps that helped me see her pain for what it really was. The story isn't done, we have additional healing to go through. But we're on the right path now.<br />
<br />
We hope this helps you on your journey...<br />
<div>
<br /></div>
<br />
<div style="text-align: center;">
****</div>
<h4>
A man, a woman, a forest and the secrets rendezvous.</h4>
My husband, my lover, my rival and sometimes friend. We started out with promise and potential, and it turned into pain and despair.<br />
<br />
After 13 years of confusion, pain, hurts, and love loss we were at the brink of destruction. He communicated to me that he was more hurt and more broken than I had ever known or realized; he still is learning just&nbsp;how hurt I was over the years.<br />
<br />
But he was sorrowful and wanting peace.<br />
<br />
I was hurt at the thought of him leaving me, the children and all the potential I still saw for us.<br />
<br />
The rejection and from that point on the hurtful words stung every time they were spoken. Why did he want to hurt me so much? Why did he hate me and despise me for wanting to love him?<br />
<br />
He told me of his hurting heart, his broken soul, and his anguished spirit. I cried with him, prayed for him and at times begged for God to answer his prayers...even the point of yelling "Why?!" at God for him and for myself, who was also hurting and in pain.<br />
<br />
I know he enjoyed the forest, through the years we talked about the peacefulness of nature and rest that can sometimes be found there. He would afterward&nbsp;go for walks in the forest, staying later, walking farther and growing more distant from me as the days and months went on.<br />
<br />
I wanted to help, to be a part of and comfort him in this time of struggle. So, the next time he went to the forest and didn't return for days without a word I decided to find him.<br />
<br />
I entered the forest at the entrance to the hiking path, I knew he wouldn't stay on the path but it was a good place to start. The trail got steep, I fell a few times scrapping my hand and knee. With blood on my clothes, I turned around and headed home.<br />
<br />
On my way out of the forest, an arrow flew by me, seemingly out of nowhere scrapping my shoulder as it passed. I ran out the forest and went home to take care of the scraps and bruises. My husband eventually came home and seeing me bandaged, he&nbsp;asked: "What happened?".<br />
<br />
I told him that I went to find him, but got hurt and had to return home. I thought he would appreciate the gesture and recognize my efforts. Instead, he was angry and defensive. He told me I deserved the scraps and bruises and that even the arrow was in part my fault as I should have stayed out of the forest and left him be.<br />
<br />
I asked if he knew where the arrow came from, he said the arrows were coming from inside the forest and it's not a big deal, it was none of my business what others were doing in the forest and I should get over it. He didn't care that my arm was still bleeding, though I was concerned that it could become a bigger problem. I had to deal with it on my own and try to move forward, wounded and bleeding.<br />
<br />
He continued to go to the forest and I tried a few more times to find him, and every time I came home scraped, bruised and with an arrow wound or two. I stopped telling him that I was going into the forest and hoped that if I found him I would have the right thing to say that would make up for my intrusion, and perhaps help him.<br />
<br />
The day came, after a huge fight, that he left for the forest and was gone for a week, I knew that this was it, either I would find him or he would be lost forever. I got some gear, hiking boots this time, some extra water and of course some protein bars. I was going to find him and I wasn't going to turn back. I decided to enter the forest from a new direction and work my way around, hopefully avoiding those arrows that seemed to find me every time I entered that hateful forest.<br />
<br />
But of course it wasn't long before the arrows found me, it was beginning to feel purposeful. But how? Who? They always got me, a scrap here, a wound there... I was limping, the wound in my arm&nbsp;cut deeper with repeated strikes. My head was bleeding from a fall that happened when an arrow went through my leg. But I was going to find him or die trying and I continued on.<br />
<br />
Up ahead I heard some laughter, I thought perhaps they could help me, I ran out of bandages and water many hours before. As I moved toward the sounds I noticed a clearing, through the trees the sun was shining, the grass was green and I think I heard the sounds of a brook. I heard a woman clearly now, "just one more" she said, and then we will eat. I heard the voice of my husband saying "okay" and then less than a second later an arrow found me.<br />
<br />
With great speed and a sharp pointed tip, it struck my chest, grazing my heart, punctured a lung and continued straight through my body like a sharp hot knife through butter. I lost all feeling in my body, the pain was so great that I could not think. I stumbled forward into the clearing. I could see the smiles on their face as they stood hand-in-hand holding the bow that had just released an arrow.<br />
<br />
THE ARROW.<br />
<br />
The moment they looked away from each other and noticed me the woman's face went from joyful laughter to slight amusement. However, my husband's face held an expression of shock and frustration. He realized that I was bloodied, though he took little responsibility at that moment. He felt that it must be a ploy or exaggeration of any pain that could possibly come from an arrow.<br />
<br />
I tried to call for help, to plead for assistance, but I had a hard time forming words. I managed to say:<br />
<blockquote class="tr_bq">
"come... hurt... arrow..."&nbsp;</blockquote>
After that last bit of energy was used up, I fell... The soft grass breaking my fall to a soft thud, and I lay there bleeding; wondering if I was going to die now&nbsp;and if I was hoping it would happen quickly.<br />
<br />
They looked at me, unmoving, not willing to respond just yet. As though they wondered as well, and perhaps if I did die, at they could carry on with their day. The woman turned to my husband and whispered something into his ear. He looked at her with a sorrowful smile and said: "I can't, I need to at least check on her, I'll come back if I can."<br />
<br />
She held his gaze, he kissed her and said: "It's probably not as bad as it seems." With that, he slowly turned and walked over to where I lay. He spoke harshly, accusing me of taking things too far and telling me of the time an arrow had cut his arm. It wasn't so bad, did he fall to the ground in heap? No! So why am I doing this, dramatic display of unnecessary drama?<br />
<br />
He wanted me to get up, he offered to walk me home, and then we could talk and sort things out. He was upset when I didn't move. He turned to look at the woman, she still had the bow in arm and arrows nearby, and she spoke to him of the meal she had prepared<br />
<br />
He was torn, I could tell as I gasped for air. He thought and observed me for a little. Then he saw the puddle of blood beginning to form from under my body and realized that this may be more serious than he thought. He knelt down, pressing his hands to the hole in my chest, trying to stop the blood from leaving my body so quickly. He tried to apologize, to explain, and to reason through what was happening and what happened.<br />
<br />
But that wasn't going to stop the bleeding. He didn't want me do die but was still trying to figure out why? Why was arrow able to pierce through and wound so greatly. If only I had stayed away or at the edge of the forest, I may be hurt but not dying.<br />
<br />
<blockquote class="tr_bq">
<b>Why could he not see that I was only able to get this wound because of how deeply I cared for him?</b></blockquote>
I pushed through the minor and not so minor wounds, through the hunger and dehydration, and turned my head toward the voices I heard in the clearing, I was in the one place, in just the right position (of desperation in looking for him) that the arrow found no resistance in being able to go straight through me.<br />
<br />
I was too weak to convince him that this was the truth, that the pain was real, or that his inability to understand the wounds didn't make them hurt less.<br />
<br />
I could feel the pain from the arrow, and I could feel the blood draining from my body a little more with every pained heartbeat, but what hurt more than that, was when even after knowing that I was hurt, bleeding and possibly dying, he looked up and turned his head away from me to look at her. His thoughts lingering on what he had just given up, what he was currently missing out on, and how happy he had felt in the forest with her.<br />
<br />
She saw him looking and she raised a plate, inviting him to come back to the meal. He slowly shook his head no, but his stomach growled in protest. She raised the bow and an arrow, with the same phrase I had heard before. She said: "just one more", but this time added, "the damage is done, one more can't make things any worse".<br />
<br />
He looked at her, the bow and the new shiny arrow, and he remembered how much fun it was to hold the bow, to raise the arrow and excitement as you release the arrow, watching it soar through the sky and disappear into the trees of the forest. He, knew from that first conversation long before that his wife was getting scraped&nbsp;and bruised, but in the moment it was fun.<br />
<br />
As I laid there I realized that he still liked the woman, the bow, and the arrows. I was bleeding to death, but he held none of these things as his responsibility. They were things he was fond of, and yes they hurt his wife, but why should that change his perspective of them or how he had felt when he was with them?<br />
<br />
His hands now covered in blood, he was sorry and was doing whatever he could to try to save me. He raced to get bandages and water. And slowly he worked to stop the bleeding so he could get me out of the forest. So he could get his wife help and see her healed. He realized he loved her, needed her and wanted her, but would she be able to survive? He wasn't sure.<br />
<br />
The problem was located&nbsp;in what he didn't realize; that with every fond thought or memory of the picnic, the woman or the bows, &nbsp;his hands lifted slightly off of my chest and the blood was able to flow more freely from my body. Any patch or bandage that he had positioned would get soaked and loosened.<br />
<br />
Because the bleeding had been slowed down, I was able to communicate a little here and there. I tried to ask, then I begged him to see the arrow, the bow, the picnic and the woman in light of the devastation they caused, but he could not.<br />
<br />
He considered pretending to be over that time, to act like it now meant little or nothing, as though her pain and suffering overwrote what he had experienced before. That when he thought of the picnic, instead of remembering the satisfaction of the meal, the image of my dehydrated flesh would replace it. And when he thought of the bow and arrows, instead of remembering the fun, the images of my broken body would replace it. And when he thought of the woman, instead of remembering easy times of conversation and connection, the image of my body limp in a puddle of my own blood would replace them... But I could tell that it still bothered him. I wanted real change, real connection, not pretending.<br />
<br />
Turning his head around toward her, and seeing the blood on his&nbsp;hands,&nbsp;tears started to fill his eyes...<br />
<br />
He lifted his hand from her not yet bandaged body without thinking about the pain she would feel and began to cry. She was in pain and tired but looking up at him she felt sorry for him. With as much energy as she could muster she raised a hand to his cheek wiping a tear, saying 'I am hurt, but it will be alright'...<br />
<br />
Looking into her eyes he slowly&nbsp;spoke&nbsp;as more tears ran down his cheeks and said 'I miss her, I was beginning to love her and I miss her'.<br />
<br />
When she heard this she wished she was well enough to run away, into the forest so she could have the comfort of death. The pain would be gone, and this would be over. But she kept her hand on his cheek, offering comfort and saying again to him 'it will be alright'.<br />
<br />
He cried a little more turning his head to the picnic, 'I wish you could see my side of this, maybe if you could understand somehow it could comfort you to know that while you thought I was alone and in pain, hurting and longing for help. And though every action brought you pain and heartache, I was not alone...I&nbsp;had&nbsp;someone to talk to, to be with... And that time was special to me.<br />
<br />
She nodded her head lowered her hand and a tear slowly fell down her cheek, she closed her eyes, and every last bit of energy she had in her drained from her soul, just as the blood was draining from her body.<br />
<div>
<br /></div>
<h4>
And now...</h4>
And this is where we were, me slowly getting patched up, hoping he can give me his full undivided thoughts so that the bleeding can be stopped. I am laying here, pleading with all that I am to be enough, but how can I be?<br />
<br />
How can someone so hurt and broken compete with a happy memory? The work of trying to patch someone up versus the memory of the ease of a picnic in a forest clearing.<br />
<br />
I am jealous of those memories because we didn't get to have that type of time. And sometimes when his hands lift, ever so slightly, and the blood flows again the pain is worse than the original strike of the arrow.<br />
<br />
In the back of my mind, I wish he would let me be so I can die and find peace in death. I know that life is better, that once healed life will be more than I ever imagined, but right now when I feel the blood seeping through the bandage, dripping from my wounds and he tells me that his affections for her shouldn't be an issue, I wish that he could see the truth.<br />
<br />
That it is an issue, that's it is still causing pain... I can feel him the slight lift of his hand, the blood, and the pain...and just because he cannot perceive these things doesn't mean they are not happening.<br />
<br />
So I lay here wondering why did these things happen? And when will the bleeding stop, so I can begin to heal? And how can his perception change so he can see behind the veil, and into the heart of what has happened?<br />
<div>
<br /></div>
<div style="text-align: center;">
<div style="text-align: center;">
****</div>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
<b><i>UPDATE</i></b>: We had an amazing year and a half with our first real connection. It wasn't sunshine and roses, it was definitely not easy, but we became a real couple. Counseling helped us communicate. We moved from North Texas to North Idaho in March 2017. On June 25, 2018, my wife died. The cause: An enlarged heart leading to blood clots. She was seven weeks pregnant. For more on what happened (<a href="http://www.darrellwolfe.com/2018/06/flavia-antoinette-wolfe-heres-what.html" target="_blank">click here</a>).<br />
<br />
The woman in the forest? She disappeared. The fun was gone so she vanished. She was a mirage, a fake connection, and now I've lost both. Sin will always take you further than you wanted to go and cost you more than you wanted to pay.<br />
<br />
<br />
<div style="-webkit-text-stroke-width: 0px; color: black; font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-caps: normal; font-variant-ligatures: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-decoration-color: initial; text-decoration-style: initial; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px;">
</div>
<br />
<div style="-webkit-text-stroke-width: 0px; color: black; font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-caps: normal; font-variant-ligatures: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-decoration-color: initial; text-decoration-style: initial; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px;">
<div style="margin: 0px;">
****</div>
<div style="margin: 0px;">
<br /></div>
</div>
<div style="text-align: center;">
This story set me (Darrell) free in profound ways, helping me connect with my wife's heart. It set her (Flavia) free to share her heart and know she was really heard.&nbsp;</div>
<div style="text-align: center;">
<br /></div>
<div style="text-align: center;">
I hope it helped you and set you free too. Share this story with other Husbands and Wives (and those to be), that it may set them free too.&nbsp;</div>
<br />
<br /></div>
</div>
<b>God Bless,</b><br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell &amp; Flavia Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span> <span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
<div class="MsoNormal">
<br /></div>
