---
title: 'I Hate My Birthday... Is that wrong?'
date: '2017-06-10T18:04:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8267505885354175629'
blogger_filename: '/2017/06/i-hate-my-birthday-is-that-wrong.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Perspective'
---

<p dir="ltr"><br></p>
<p dir="ltr">&#8220;Let the day on which I was born perish, And the night which announced: &#8216;There is a man-child conceived.&#8217; JOB 3:3 AMP</p>
<p dir="ltr">http://bible.com/1588/job.3.3.AMP<br></p>
<p dir="ltr">It sounds melodramatic when I read Job say it; however, this has basically been my complaint for as long as I can remember. </p>
<p dir="ltr">Job 3 shows an entire chapter of him wishing he was never born and cursing his birthday. I've always hated my birthday too, often telling people to keep me off of birthday celebration lists and calendars. </p>
<p dir="ltr">I've made due with life but wished I'd have left it long ago... That hasn't changed but I'm starting to get the sense that shell is cracking. </p>
<p dir="ltr">Maybe, just maybe, I won't hate and despise my birthday in the future, maybe I'll learn to accept that I'm here on Earth and be happy about it? That sounds like a stretch right now. </p>
<p dir="ltr">Right now I'm just content with being in a place where I'm feeling maybe being alive isn't all bad... That's a huge step up from my past 36.5 years. </p>
<p dir="ltr">Maybe I'll let my name stay on the birthday list as a rebellion against depression... Who knows, maybe I won't hate it... Maybe... <u>DW</u></p>
