---
title: 'What doesn&#39;t kill you makes you stronger????'
date: '2017-06-05T17:06:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5891849709937546770'
blogger_filename: '/2017/06/what-doesn-kill-you-makes-you-stronger.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Personal and Spiritual Growth'
---

<p dir="ltr">What doesn't kill you only makes you stronger.</p>
<p dir="ltr">Ask a Vet with an amputated limb if they feel stronger now or before the limb was taken... I'd bet before. Injury, all injury, is by definition a lack of perfection. </p>
<p dir="ltr">What doesn't kill you, more often than not,&nbsp; makes you weaker, more timid, more cautious, slower... Not stronger.</p>
<p dir="ltr">Sure, we can learn from the past, become more resilient. We can use pressure, under certain circumstances, to build resistance based strengths, like a body builder pushing back on the resistance of the weights... </p>
<p dir="ltr">But by no means is the saying: "What doesn't kill you only makes you stronger" an accurate portrayal of Truth, nor should it EVER be spoken to someone in pain.</p>
<p dir="ltr">The enemy comes ONLY to steal, kill, and destroy, that's why the pain/attack came, not to make you stronger but to kill you.</p>
<p dir="ltr">God's Grace brought you through but He didn't bring you to...</p>
<p dir="ltr">God's Grace can heal you too.</p>
<p dir="ltr">Selah</p>
<p dir="ltr">#LiesAboutGod</p>
