---
title: 'It''s a new season...'
date: '2017-05-02T03:18:00.0040000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6446752622700503522'
blogger_filename: '/2017/05/its-new-season.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Personal & Spiritual Growth'
---

<br />
I just read a Facebook post from a friend/close acquaintance I know who was just laid off from a place I wanted to work at one time. It reminded me of my current season here...<br />
<br />
I came to North Idaho with plans.... and they haven't worked out the way I intended. I'm not living where I thought I'd live, working where I thought I'd work, or doing the things I thought I'd be doing.<br />
<br />
This season feels like a microcosm of my life... I'm not where I thought I'd be by now. I'm having trouble coming up with the motivation to do the things I maybe ought to be doing.<br />
<br />
<i>*Shhhh...</i> Do you feel that? That wind gently blowing through the trees, down the hills, brushing your shoulders...<br />
<br />
<a href="https://youtu.be/mbSAnYihlt8" target="_blank">It's a new season</a>! It's a fresh anointing.... it's coming your way.<br />
<br />
The past doesn't matter. Not ten years ago, ten months ago, or ten minutes ago. God is always ready, ever ready, to do a new thing. He does best with participating people.<br />
<br />
If you are feeling like I am, it's time to go into Low Slow.... shift down a few gears. Don't run after everything that shines, every job application, every idea, every fleeting feeling... Listen for the One who knows the best path, the one you haven't seen yet. Let Him lead you right to it.<br />
<br />
Most of all... trust that this new season.<br />
<br />
It's a season of power. The same power raised Christ Jesus from the dead. The same power that created a prosperous Abraham, a successful Joseph, a powerhouse in Elijah, and a double powerhouse in Elisha.<br />
<br />
Watch this as you meditate on your new season:<br />
<br />
<iframe allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/mbSAnYihlt8" width="560"></iframe>

<br />
<div style="-webkit-text-stroke-width: 0px; color: black; font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-caps: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-decoration-color: initial; text-decoration-style: initial; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px;">
</div>
<br />
<div style="-webkit-text-stroke-width: 0px; color: black; font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-caps: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; margin: 0px; orphans: 2; text-align: start; text-decoration-color: initial; text-decoration-style: initial; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px;">
<i>*<a href="https://youtu.be/mbSAnYihlt8" target="_blank">It's a new season</a>! by&nbsp;<a href="https://www.facebook.com/IsraelHoughton/" target="_blank">Israel and New Breed</a></i></div>
<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell
G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
<div class="MsoNormal">
<br /></div>
