---
title: 'DNA Of The Heart | Church Notes'
date: '2017-05-07T19:37:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2510412447706784824'
blogger_filename: '/2017/05/dna-of-heart-church-notes.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Church Notes'
---

Heart Of The City Church May 6, 2017<br />
<br />
DNA Of The Heart:&nbsp;<a href="http://bible.com/events/213349">http://bible.com/events/213349</a><br />
<br />
==================================== Local churches mentioned in the Bible:<br />
<br />
<ul>
<li>Antioch, Pisidia: Acts 13:14; Gal 1:2&nbsp;</li>
<li>Antioch, Syria: Acts 11:26 (Paul's home base)&nbsp;</li>
<li>Athens: Acts 17:34&nbsp;</li>
<li>Babylon: 1 Peter 5:13; Acts 2:9&nbsp;</li>
<li>Berea: Acts 17:11&nbsp;</li>
<li>Caesarea: Acts 10:1,48&nbsp;</li>
<li>Cenchrea: Rom 16:1&nbsp;</li>
<li>Colossae: Col 1:2 Corinth: Acts 18:1&nbsp;</li>
<li>Crete: Titus 1:5&nbsp;</li>
<li>Cyrene: Acts 11:20&nbsp;</li>
<li>Damascus: Acts 9:19&nbsp;</li>
<li>Derbe: Acts 14:20; Gal 1:2&nbsp;</li>
<li>Ephesus: Acts 18:19&nbsp;</li>
<li>Hierapolis Col 4:13&nbsp;</li>
<li>Iconium: Acts 14:1; Gal 1:2&nbsp;</li>
<li>Jerusalem: Acts 2:5&nbsp;</li>
<li>Joppa: Acts 9:36, 38&nbsp;</li>
<li>Laodicea: Rev 1:11, Col 4:15&nbsp;</li>
<li>Lydda: Acts 9:32&nbsp;</li>
<li>Lystra: Acts 14:6; Gal 1:2&nbsp;</li>
<li>Pergamum: Rev 1:11&nbsp;</li>
<li>Philadelphia: Rev 1:11&nbsp;</li>
<li>Philippi: Acts 16:12&nbsp;</li>
<li>Puteoli, Italy: Acts 28:13-14&nbsp;</li>
<li>Rome: Rom 1:7&nbsp;</li>
<li>Sardis: Rev 1:11&nbsp;</li>
<li>Sharon: Acts 9:35&nbsp;</li>
<li>Smyrna: Rev 1:11&nbsp;</li>
<li>Tarsus: Acts 9:30&nbsp;</li>
<li>Thessalonica: Acts 17:1&nbsp;</li>
<li>Thyatira: Rev 1:11; Acts 16:14&nbsp;</li>
<li>Troas: Acts 20:6-7&nbsp;</li>
</ul>
<br />
<br />
House Of Grace --------------------------- You want grace extended to you? Extend grace to others. ---------------------------<br />
<br />
Ephesians 2:8-9 NKJ For by grace you have been saved through faith, and that not of yourselves; it is the gift of God, not of works, lest anyone should boast. http://bible.com/114/eph.2.8-9.NKJV City On A Hill ---------------------------<br />
<br />
In the same way you freely talk about your favorite sports team or movie, you should be able to talk freely about Jesus. ---------------------------<br />
<br />
House Of Prayer ---------------------------<br />
<br />
PUSH, Pray Until Something Happens Prayer is the engine room if the Church. ---------------------------<br />
<br />
Mark 11:17 NKJV Then He taught, saying to them, “Is it not written, ‘My house shall be called a house of prayer for all nations’ ? But you have made it a ‘den of thieves.’ ” http://bible.com/114/mrk.11.17.NKJV<br />
<br />
House Of Restoration ---------------------------<br />
<br />
Restoration is the act of returning something to its former owner or condition (or better). ---------------------------<br />
<br />
House Of Redemption Titus 2:14 NKJV who gave Himself for us, that He might redeem us from every lawless deed and purify for Himself His own special people, zealous for good works. http://bible.com/114/tit.2.14.NKJV House Of Healing ---------------------------<br />
<br />
Good still heals! ---------------------------<br />
<br />
Acts 10:38 NKJV how God anointed Jesus of Nazareth with the Holy Spirit and with power, who went about doing good and healing all who were oppressed by the devil, for God was with Him. http://bible.com/114/act.10.38.NKJV House Of Faith ---------------------------<br />
<br />
Believe God and his promises. ---------------------------<br />
<br />
Genesis 15:6 NKJV And he believed in the Lord , and He accounted it to him for righteousness. http://bible.com/114/gen.15.6.NKJV Safe House ---------------------------<br />
<br />
City of refuge, safe place, if you've created a mess of life, this is a safe place to be. ---------------------------<br />
<br />
The Whole Army ---------------------------<br />
<br />
No more standing by the side lines. It's time to stand up and be a part of the battle. We are all equal and have a role to play in the end time battle. Bonus: We are a house of worship! ---------------------------<br />
<br />
Galatians 3:28 NKJV There is neither Jew nor Greek, there is neither slave nor free, there is neither male nor female; for you are all one in Christ Jesus. http://bible.com/114/gal.3.28.NKJV Matthew 23:11 NKJV But he who is greatest among you shall be your servant. http://bible.com/114/mat.23.11.NKJV<br />
<br />
Exodus 21:5-6 NKJV But if the servant plainly says, ‘I love my master, my wife, and my children; I will not go out free,’ then his master shall bring him to the judges. He shall also bring him to the door, or to the doorpost, and his master shall pierce his ear with an awl; and he shall serve him forever. http://bible.com/114/exo.21.5-6.NKJV<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span><span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
