---
title: 'The Shroud'
date: '2017-11-27T01:00:00.0020000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8519181914964483348'
blogger_filename: '/2017/11/the-shroud.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Writing Craft'
  - 'Writing Practice'
---

Shadow enveloped Stephen as he watched the movements below from his perch in the old church bell tower. His cloak danced in the breeze as a proud flag, his face enshrouded under the familiar hood. He watched the events of Ashland, Idaho with a passive interest, until he noticed someone looking at him... directly?<br />
<br />
It had been three hundred years since anyone had seen him, really seen him. Could this Captain Ashland be one of them? A seer? Unlikely. Not many were left in the world. Although the rumors of the shadow world claimed they were on the rise, ever since the Azusa Street Revival.<br />
<br />
Stephen moved from his perch, pacing left to right. The Captain's eyes followed him. "I must tell the others," he said. "There is an awakening..."<br />
<br />
His form morphed into a black whisp of cloud and he&nbsp;floated away from the perch, into the mountains.<br />
<br />
<br />
***<br />
<br />
Ash noticed the figure evaporated into a cloud of smoke. He shook his head. When would these visions ever get better?<br />
<br />
<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span> <span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
<div class="MsoNormal">
<br /></div>
