---
title: 'White Noise - Distortion - Grounded Cafe - Re-Write #3'
date: '2017-05-02T07:33:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '485869841503254939'
blogger_filename: '/2017/05/white-noise-distortion-grounded-cafe-re.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Fiction'
  - 'White Noise'
---

<i>*White Noise - Distortion - Grounded Cafe - Re-Write #3</i><br />
<br />
<div style="text-align: center;">
***</div>
<div style="text-align: center;">
<br /></div>
<h4>
Grounded Cafe</h4>
<br />
Through the window of the Grounded Cafe, Ash noticed two men dressed in all black duck behind a blue minivan. Ice ran down his spine. His right arm shot to the Glock 9mm at his side. Sucking a breath he took a second look— &nbsp;They were gone. Black mist poured out from under the minivan and evaporated into the early morning air.<br />
<br />
He shook his head, closed his eyes. Counting to ten, silently, Ash released the grip on his sidearm, which he now realized was a tape measure and not a Glock. Ash hadn’t had a right to carry a weapon since he left the service. He let his arm fall to his side. Reality settled back onto his shoulders.<br />
<br />
A college age girl walked by just outside the window, head buried in her smartphone. She bumped into Chester, the town’s crazy old homeless man who was headed the other direction. She didn’t even notice. He gave her a dirty looked and kept walking the other way. She sat down at a table just outside the farthest window of the Cafe. A small green frog sat on her shoulder. The bottom half of the frog was a mist that disappeared into her spine. The frog’s red eyes stared at Ash, and it cocked its head to one side. Then it was gone.<br />
<br />
He didn’t see these creatures on every person, and they weren’t all exactly alike. But he saw them often enough. PTSD, Post Traumatic Stress Disorder, his doctor had called it. They tried giving him a mountain of drugs to help him sleep and keep the delusions at a minimum. Nothing really helped. When Washington legalized medicinal THC, his doctor gave him the card he would need. He crossed the border once a month for his medicine.<br />
<br />
Since then, sleep was more regular but the delusions came and went. He could still hear the diagnosis in his mind. “As long as you are not a harm to yourself or others, you should be just fine. Think of it as an amusing distraction,” the doctor advised.<br />
<br />
“Ash,” Derek the Barist’ called his attention to the present. “Here you go, man. Extra Large Java-Chip, Almond Milk, Three Shots, with Peppermint and Whip. I even through a candied coffee bean on there for you.”<br />
<br />
Turning from the window, Ash grabbed his coffee from the stand. “Thanks, Derek”.<br />
<br />
“Always my friend.” Derek kept smiling as he turned his attention to the next order.<br />
<br />
The cool leather crunched and crinkled as Ash settled into his favorite corner chair. Up against a wall so nobody could surprise him. Within a quick few steps from three exit paths. Easy to be missed in the dark corner but easy to scope the entire room at the same time.<br />
<br />
A young man with a hoodie typing furiously at a keyboard. A woman talking on the phone, failing to pacify the toddler in the stroller to her side. Two men speaking in hushed tones at a table across the way. It’s not quite full season yet, so the Cafe’ isn’t too busy—<br />
<br />
Screeching tires— Crunching metal— Thud— the building shook slightly. The small-town crowd that had been meandering between the stores that recently opened for the season began pooling just outside the view of the front window.<br />
<br />
Ash took his coffee from the side table and headed out the front door. The two men Ash had seen huddled in conversation across the cafe pushed past him on the way out the door to see what was happening.<br />
<br />
Steam billowed from what was left of the front end of an old silver Honda Civic, 1990’s model.The car was T-boned into the side of a black Toyota pick-up. Both drivers had already gotten out of the vehicles. No one to rescue.<br />
<br />
“What do you care?” said Chester, an old man with a graying beard and brown plaid dress jacket who was climbing up into the back of the pick-up. “Yeah— I know—” he yelled then her murmured something Ash couldn’t hear.<br />
<br />
Great— He’s having another episode.<br />
<br />
“Chester,” Ash said. “Chester, is that you old man? Why don’t you come down from there?”<br />
<br />
Chester, the town Kook as some called him, looked at Ash with a flicker of recognition which faded quickly. Just behind him, a dark mist rose from the bed of the truck.<br />
<br />
Not again. Not now.<br />
<br />
The mist grew until it towered over Chester as a father over his toddler. It grew arms with bulging muscles but the head of a bull, red eyes, and three white streaks across its chest.<br />
<br />
Another smaller creature, akin to a hairless monkey, was coming out of Chester’s spine and whispering into his ear. Reacting to each murmur as though it were the other half of an invisible conversation.<br />
<br />
The larger creature stared directly at Ash. It bent down and the smaller creature evaporated. The bull-man whispered into Chester’s ear and he too snapped his attention at Ash. Then he leapt off the truck toward Ash, knocking down two men from the crowd on his way to the street.<br />
<br />
Ash felt his feet sticking to the pavement as though they were glued. He raised one arm in defense as the old man tackled him, nails trashing at his throat.<br />
<br />
“Jesus—,” Ash let out.<br />
<br />
The old man stopped attacking, looking dazed. Ash needed no further opening. He struck the old man in the chin with his elbow and followed with a strike to the side of the neck with a knife hand. Rolling out from under him, he hog-tied Chester with his own belt, then he sat on him with one knee to keep him from moving.<br />
<br />
Siren’s broke up the crowd and the Sheriff’s SUV pulled to stop next to them.<br />
<br />
“You alright?” The Sheriff asked.<br />
<br />
“Danny,” Ash replied. “To be honest, I’m feeling a bit embarrassed that I was caught off guard by a crazy old homeless man.” They both laughed.<br />
<br />
“I’ll take it from here,” Danny and his deputy Ralph took Chester and laid him in the back seat of the squad car.<br />
<br />
“You need medical attention,” Danny said. “Your neck is all scratched to heck, man.”<br />
<br />
“No,” Ash replied. “It’s not as bad as it looks. I’ll take care of it at home.”<br />
<br />
“Whatever you say, but I need you down at the station for a statement tomorrow. OK?”<br />
<br />
“Sounds good. See you then, Danny.”<br />
<br />
“Cool. Take care of that, Ash.”<br />
<br />
Ash started to reach for the coffee that had miraculously survived the ordeal, when the same young woman from earlier, still oblivious to the world, walked by and kicked the drink open, pouring all over the pavement and the bottom edge of his jeans.<br />
<br />
“Great! Thanks, lady!” Ash yelled. She kept walking. She either didn’t hear or pretended not to.<br />
<br />
“Could this day get any better?” Ash mumbled to himself as he walked down the street for home.<br />
<br />
<br />
<div style="text-align: center;">
***</div>
<br />
End Scene. A story by,<br />
<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span> <span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
<div class="MsoNormal">
<br /></div>
