---
title: 'What is a Topos? A strategic position of opportunity and influence'
date: '2017-04-24T19:40:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7570433204240388692'
blogger_filename: '/2017/04/what-is-topos-strategic-position-of_24.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Productivity'
  - 'Professional Growth'
  - 'Personal & Spiritual Growth'
  - 'News & Events'
---

<h4>What does Topos mean?</h4><a href="http://biblehub.com/greek/5117.htm">Topos is a Greek</a> word meaning: "Place, or Opportunity"<br /><h4>Properly:</h4><ul><li>Any portion of space marked off, as it were, from surrounding, space</li></ul><div><h4>Metaphorically: </h4><ul><li>The condition or station held by one in any company or assembly</li><li>opportunity, power, occasion for acting</li><li>A spot (general in space, but limited by occupancy; whereas chora is a large but participle locality).</li></ul><h4>As used by me:&nbsp;</h4><blockquote class="tr_bq"><i>Topos is a strategic position of opportunity and influence</i></blockquote><br /><h4>Topos: Your Calling</h4>Everyone has a God given calling on this earth. There is something you were created and designed to do. What you are doing now may be "The Calling"; or, it may be the calling for this season of your life. Either way, you are either in your Topos, or you need to find it.<br /><br />As you read the stories of biblical heros  like Noah, Abraham, Joseph, Moses, David, Nehemiah, Peter, and Paul... etc... you find that God put them in the right place to do the right thing at the right time.<br /><br />They ended up in their Topos, a strategic place of opportunity and influence. Some men, like king Saul before David were in their Topos but never reached their full potential because of sin, disobedience, or laziness.&nbsp;</div><div><br /></div><div>I'm on a life-long quest to reach the center of my Topos... and I want to help you find yours too.&nbsp;</div><div><br /></div><div>Follow this blog to take that journey with me.</div><div><br /></div><div>Darrell</div>