---
title: 'Change: It&#39;s harder than you thought and better than you imagined'
date: '2017-04-04T03:53:00.0020000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5331790677037745662'
blogger_filename: '/2017/04/change-it-harder-than-you-thought-and.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'News & Updates'
---

<br />I'm at the tail end of an end and the head of a beginning.<br /><br />After 7 years in Nort Texas (Fort Worth), we moved. We spent the last few months getting the house ready to sell, selling the house, and moving. A week (03/19 - 03/24) was spent on the road and since then we lived in a hotel until we could find a place to live.<br /><br />On Friday (03/31/17), we moved into our new house (rental). We're still unpacking, building storage shelves, figuring out to live with a basement for washer/dryer (odd).<br /><br />We just found a store (<a href="http://entertainmart.com/">EntertainmentMart</a>) that sells games, Pokemon cards, and more. They allow the kids and adults to come play against each other live every Monday and Wed. So the kids are now adjusting.<br /><br />There are things I already really enjoy about North Idaho... some of the transitions were easier than others.<br /><br />Some things didn't go the way I wanted and some things went better. I just needed to learn to flow, slow down, breath, and listen... it's always about listening to the Holy Spirit.<br /><br />Well... that's my update for now. I'll write more later.<br /><br /><br /><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"></span></div><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;;"><br /></span> <span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div><div class="MsoNormal"><br /></div>