---
title: '2016 - 2017 - The Winds of Change (I Love my wife!)'
date: '2017-01-08T06:30:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8652994299603502493'
blogger_filename: '/2017/01/2016-2017-winds-of-change-i-love-my-wife.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Renewing the Mind (Stinking Thinking)'
  - 'In The Mire'
  - 'Resting'
  - 'Recovery'
  - 'Emotions'
  - 'Freedom/Kairos'
---

<br />2016 was the worst year of my life. I almost went back to an old life, partially did.<br /><br />Earlier this week, I came within a breath of making decisions that would have led to the destruction of a family, and ultimately my spiritual&nbsp;then&nbsp;physical death.<br /><br />But God....<br /><br />Last night (Friday night), God used Flavia (my wife) to break through the walls.<br /><br />For the first time in my 36 years on planet earth, I know I'm going to be OK. I'm OK with not being OK, and now I'm going to be.<br /><br />He used her to heal me. And now I have to help heal the pain I've caused her for 14 years.<br /><br />It will be a journey, but one worth taking with her by my side.<br /><br />I am "In Love" with Flavia A. Wolfe, and I want the world to know it.<br /><br />I'm looking forward to 2017, really really looking forward to what miracles God has in store for this family this year.<br /><br />**<br /><br />PS: I'm open to anything, even the call to ministry. I surrender all. I'm willing to pay it forward, use me.<br /><div><br /></div><br />So, broken or whole, "right or wrong", that's what I'm thinking about today,<br /><br />Darrell W.<br /><br />