---
title: 'Dancing Ice'
date: '2017-01-12T19:14:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7707357087140677621'
blogger_filename: '/2017/01/dancing-ice.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Dancing Ice'
---

<h4>Dancing Ice</h4>Shimmers of light glanced off the icicles hanging from the eaves of the winter cabin, prisms of a pure and clean world. A blanket of fresh powder covered the ground. <a href="http://www.arwen-undomiel.com/elvish/girlnames.html">Aditi</a> sat on the window sill, watching Jeff shovel snow. Grumbling to himself, complaining about how hard it was on his back. Jeff was a human, and like most humans, he’d lost sight of the wonder of winter.<br /><br />Aditi had previously attempted to reach him, convince him to open his eyes and see but he was deaf and blind to her presence. With a deep sigh, she floated up to her place above the cabinets. She was preparing for spring. Her work was to make the flowers more colorful, and the animals more playful. She did her job well for the past 3,000 years. She’d avoided humans for the most part, but Jeff was an exception. There was something about him that made her happy and sad at the same time. She knew Yah had a plan for this one, but he just couldn’t see it.<br /><br />So she set up her shop in his cabin and watched over him. She saved him from countless times he’d left the stove on, forgotten to close the door during bear season, or the time he was distracted and nearly walked into the street while a garbage truck was driving through town. That was harder because she had to get his attention, which was so hard to do. She finally pinched his neck. She didn’t like hurting him but it was better than seeing him run over by a garbage truck.<br /><br />Having completed her preparations for the day, Aditi put on her warmest outfit, fluttered her wings, and took off through the vent in the ceiling. She made her way outside, past Jeff and his grumbling shovel, and went to find more supplies. This would be the best spring she’d ever put on. The other elves would be so happy or jealous, she wasn’t sure which!<br /><br /><h4>TBC...</h4><h4 style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px; margin: 0px; position: relative;">By&nbsp;<a href="https://plus.google.com/+DarrellWolfe/posts" style="color: #149adf; text-decoration: none;" target="_blank">Darrell Wolfe</a></h4><blockquote class="tr_bq" style="background-color: white; color: #333333; font-family: Verdana, Geneva, sans-serif; font-size: 15.4px; line-height: 19.6px;"><i>Storyteller | Creative | <a href="http://www.16personalities.com/infj-personality" style="color: #149adf; text-decoration: none;" target="_blank">INFJ</a>&nbsp;|&nbsp;<a href="https://www.gallupstrengthscenter.com/Purchase/en-US/Product?Path=Clifton%20StrengthsFinder" style="color: #149adf; text-decoration: none;" target="_blank">Intellection</a>&nbsp;|&nbsp;Ideation | Input | Learner | Achiever | Multipotentialite</i></blockquote><ul><li><i>See my full about page and disclosures: <a href="http://authorfun.blogspot.com/p/what-is-this.html" target="_blank">Click Here</a>.&nbsp;</i></li><li><i>Also check out my <a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">Resources and Suggestions </a>for writers (<a href="http://authorfun.blogspot.com/p/affiliate-store.html" target="_blank">here</a>).&nbsp;</i></li><li><i>To Subscribe to the <a href="http://feeds.feedburner.com/AuthorFun" target="_blank">RSS: Click Here</a></i></li><li><i>For Non-Fiction writing by <a href="http://www.darrellwolfe.com/" target="_blank">Darrell Wolfe: Click Here</a></i></li></ul><ul></ul>