---
title: 'The Good Will Hunting Dilemma'
date: '2017-06-05T08:02:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4524033607227880192'
blogger_filename: '/2017/06/the-good-will-hunting-dilemma.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Perspective'
  - 'Personal and Spiritual Growth'
---

<p dir="ltr">Do you know the problem with having a 148IQ (Genius, for those who don't know)?</p>
<p dir="ltr">You know so many things, memorize things easily, perform tasks that take others time to learn in practically no time, excel at almost everything fact based (except human relationships)...</p>
<p dir="ltr">You can do anything, be anything...</p>
<p dir="ltr">Therefore, nothing holds your attention very long. You have trouble sticking to a task long enough to see the payoff.</p>
<p dir="ltr">I've started and restarted more careers than most people have in a lifetime. </p>
<p dir="ltr">I've been: </p>
<p dir="ltr">Cart Attendant/Cashier<br>
Western Clothing Salesman<br>
Hat shaper/Cleaner<br>
Pool Cleaner<br>
Maintenance for a Summer camp<br>
Restaurant server for five separate companies in eight locations.<br>
Call center customer service<br>
Call center sales<br>
Branch/Retail banking sales<br>
Executive Office complaints management<br>
Policy &amp; Procedure (P&amp;P) writer<br>
Freelance writer<br>
Blogger<br>
Audio Technician<br>
And many other things...</p>
<p dir="ltr">I went to Jr College for six years, changed majors three times, collected 78 units, never graduated...</p>
<p dir="ltr">And after all that, at nearly 37 years old...</p>
<p dir="ltr">I still don't know what I want to be when I grow up. I have inklings, ideas, I'm clearer now then I was earlier in life... But I'm still totally unclear on the path...</p>
<p dir="ltr">It's like in Man of Steel, young Clark Kent is getting so many inputs he can't handle it, he runs to hide in the closet...</p>
<p dir="ltr">That's how I've felt my entire life...</p>
<p dir="ltr">You can tell me how great I am at X, Y, or Z... But it's hard to feel successful when you're this far along and you have no better ideas than you did in highschool...</p>
<p dir="ltr">I often wish I was dumber, that way I could settle down into a single career, be happy enough, go out for drinks with the boys on Friday, watch the game, etc... Normie stuff? </p>
<p dir="ltr">Being a genius has not helped me one bit... </p>
<p dir="ltr">God must have a plan but I'm not seeing it...</p>
<p dir="ltr">Here's hoping it comes soon..</p>
<p dir="ltr">#GoodWillHuntingDilema</p>
