---
title: '2016 - 2017 The Winds of Change'
date: '2017-01-08T06:29:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '526660228486994643'
blogger_filename: '/2017/01/2016-2017-winds-of-change.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'News & Updates'
  - 'Other'
---

<br />
2016 was the worst year of my life. I almost went back to an old life, partially did.<br />
<br />
Earlier this week, I came within a breath of making decisions that would have led to the destruction of a family, and ultimately my spiritual then physical death.<br />
<br />
But God....<br />
<br />
Last night (Friday night), God used Flavia (my wife) to break through the walls.<br />
<br />
For the first time in my 36 years on planet earth, I know I'm going to be OK. I'm OK with not being OK, and now I'm going to be.<br />
<br />
He used her to heal me. And now I have to help heal the pain I've caused her for 14 years.<br />
<br />
It will be a journey, but one worth taking with her by my side.<br />
<br />
I am "In Love" with Flavia A. Wolfe, and I want the world to know it.<br />
<br />
I'm looking forward to 2017, really really looking forward to what miracles God has in store for this family this year.<br />
<br />
**<br />
<br />
PS: I'm open to anything, even the call to ministry. I surrender all. I'm willing to pay it forward, use me.<br />
<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;"><br /></span></div>
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Story Teller | <a href="https://www.16personalities.com/infj-personality">INFJ</a> | Futuristic | Intellection | Learner | Ideation | Achiever | Command | Input | Focus | <a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en">Multipotentialite</a><o:p></o:p></span></div>
<div class="MsoNormal">
<br /></div>
