---
title: 'Writing Prompt | Room and Bored'
date: '2018-04-24T06:17:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7032317433817949247'
blogger_filename: '/2018/04/writing-prompt-room-and-bored.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Writing Practice'
---

At the Heart Writers group meeting tonight, led by <a href="https://www.laurenstinton.com/about-lauren/" target="_blank">Lauren Stinton</a>, we did a short writing prompt.<br />
<br />
You have seven minutes to write (fiction or nonfiction) and it must include these three items/themes:<br />
<br />
<ol>
<li>Jesus is Lord of all</li>
<li>Princess</li>
<li>Cat</li>
</ol>
<br />
Here is my result, with a bit of post-meeting editing and addition. Keep in mind, I wrote it in OneNote on my phone...<br />
<br />
<div style="text-align: center;">
***</div>
<h4>
Room and Bored</h4>
The light amplified through the double glass window pane, despite the clawed dusty drapes, warming Princess' furry belly. She was Queen of this castle and she held the honor with dignity.<br />
<br />
Her human was a good servant. He brought her food at the appointed time. He changed her box. He performed his part admirably.<br />
<br />
Then her life shattered.<br />
<br />
Her human walked in the front door and laid a box on the table. "Princess, I have a surprise for you, " He said.<br />
<br />
She rolled off the couch back and sauntered over. The pawed the box. It moved. She jumped back, "Moew," she cried.<br />
<br />
A soft rumble came from the box.<br />
<br />
Her human pulled out a small kitten.<br />
<br />
<i>How could he? Has he taken to dethroning me?</i><br />
<br />
"This little guy was hurt and alone," her human said."He needs our help. His name is Jesus, it's Spanish."<br />
<br />
She saw the kitten was missing a paw. Remembering her first days in the veterinary clinic, where Leeland saved her, her heart softened... a little.<br />
<br />
Over time, she learned to love the kitten as her own. Eventually, she realized that she could make room in her life for another, that maybe, just maybe, she was not Lord of All...<br />
<br />
<div style="text-align: center;">
***</div>
<br />
Now... go do something! See you around,<br />
<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span> <span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
<div class="MsoNormal">
<br /></div>
