---
title: 'Love Is...'
date: '2019-06-18T08:18:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4767264845686191892'
blogger_filename: '/2019/06/love-is.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<blockquote class="tr_bq">
<div style="text-align: center;">
<i>1 Corinthians 13</i></div>
<i><div style="text-align: center;">
<i>4Love is patient, love is kind, it is not envious. Love does not brag, it is not puffed up. 5It is not rude, it is not self-serving, it is not easily angered or resentful. 6It is not glad about injustice, but rejoices in the truth. 7It bears all things, believes all things, hopes all things, endures all things. 8Love never ends.&nbsp;</i></div>
</i></blockquote>
<div style="text-align: center;">
<br /></div>
<br />
Love is patient<br />
<br />
Love is kind<br />
<br />
Love is not envious.<br />
<br />
Love does not brag<br />
<br />
Love is not puffed up<br />
<br />
Love is not rude<br />
<br />
Love is not self-serving<br />
<br />
Love is not easily angered or resentful<br />
<br />
Love is not glad about injustice but rejoices in the truth.<br />
<br />
Love bears all things<br />
<br />
Love believes all things<br />
<br />
Love hopes all things<br />
<br />
Love endures all things<br />
<br />
Love never ends.<br />
<div>
<br /></div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span></div>
