---
title: 'Friendship Lessons'
date: '2019-10-19T22:05:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2798694385256110801'
blogger_filename: '/2019/10/friendship-lessons.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<br />
<br />
Reflecting on friendship...<br />
<br />
I've been making new friends the last 15 +/- months, learning about friendship again as a single adult (Widower)... I've seen a few lessons play out this year.<br />
<br />
<ul>
<li>Keep&nbsp; can your eyes open, friends can come from the most random unexpected places.</li>
</ul>
<ul>
<li>Keep your heart open, people of different politics and even faith backgrounds can teach you more about love then some of your own tribe.</li>
</ul>
<ul>
<li>Keep your heart protected, some that start out exciting may show they were never your real friend to begin with. Or at least, not a healthy friend you should keep around. Inner trust should be earned over time. Had to learn that with a few before I finally understood.</li>
</ul>
<ul>
<li>Keep valuing your heart and soul and time above all else. If they don't value you, walk away.</li>
</ul>
<ul>
<li>Keep your expectations in check, don't fall for someone's potential. I've watched friends make asinine decisions that either already turned out bad or are practically guaranteed to do so.&nbsp;</li>
</ul>
<ul>
<li>Keep your opinion to yourself unless they ask, nothing you can do but watch it go bad, and shake your head. How do I congratulation someone for starting something that is guaranteed to be their 3rd divorce in the making? I hope your happy, I hope I am wrong, but I'm not. Ironically, this applied to more than two friends this year.&nbsp;</li>
</ul>
<ul>
<li>Keep your opinions honest, for those who do ask. It serves them no good to nod and smile and secretly know it's a bad idea. Encourage some to push forward, if they're doing the right thing. Encourage others to run away or redirect or stop. Be blunt but kind.</li>
</ul>
<ul>
<li>Keep working and investing, you may need to suit up for your friends when it's inconvenient, but the good ones will suit up for you. Time and opportunity will show which ones were which.</li>
</ul>
<ul>
<li>Keep knocking but don't chase, some friends were self protective and needed coaxing and reassurance to come out of their shell, they may become fabulous friends even from a distance. But some never do come out, and those you should allow to stay hidden in their opaque glass boxes. Leave them alone. If they wanted your friendship, they'd meet you half way. They may come out later, when they're ready.</li>
</ul>
<ul>
<li>Keep in mind the opportunity your miss, I've found out my own kids make pretty awesome friends too. Don't ignore friends because they didn't come in the package you wanted. Water the seeds you're given. Or you may be missing opportunities in front of you to chase mirages that never were real.&nbsp;</li>
</ul>
<ul>
<li>Keep conflict to a minimum. If conflict arises, do what the Bible says. Run to them, try to work it out with them. If you need to get others involved, do so. But if the person refuses, don't keep trying, walk away from them. Boot them from your life. Don't let them back without proof they're ready to change, and heal the past. Continuing to try will only make it worse for both of you. Walk away.</li>
</ul>
<div>
What about you? What lessons have you learned in making friends?&nbsp;</div>
<br />
Comment on this post and let us know.<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span></div>
