---
title: 'Book Reflection: Mere Christianity by C.S. Lewis'
date: '2019-05-24T04:45:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1478713393981800576'
blogger_filename: '/2019/05/book-reflection-mere-christianity-by-cs.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Books'
---

<h4 style="text-align: center;"></h4><div><div style="text-align: center;"><iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="https://ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&amp;OneJS=1&amp;Operation=GetAdHtml&amp;MarketPlace=US&amp;source=ss&amp;ref=as_ss_li_til&amp;ad_type=product_link&amp;tracking_id=&amp;language=en_US&amp;marketplace=amazon&amp;region=US&amp;placement=0060652926&amp;asins=0060652926&amp;linkId=2768fd58d290c27fa61f8c4a818a8826&amp;show_border=true&amp;link_opens_in_new_window=true" style="height: 240px; width: 120px;"></iframe></div></div><div style="text-align: center;"><br /></div><h4></h4><h4 style="text-align: center;">Mere Christianity<span style="white-space: pre;"> - <a href="https://amzn.to/2M7Qood" target="_blank">Buy Now</a></span></h4><div style="text-align: center;"><br /></div>This is a reflection paper of the text Mere Christianity (Lewis, 1952, 1980). The content was first delivered as radio broadcast material between 1942-1944 by Clive Staples “CS” Lewis. Lewis then gathered the materials and published them as three sperate works, later combining and editing the text that became Mere Christianity. With the mind of a scholar and the mouth of a layman, Lewis takes us through the various topics that affect our lives as Christians and provides practical break-downs of how we are to treat each topic, supplemented by a host of modern parallels and parables. He is careful not to take any position that is not laid solidly in the Word of God, leaving those positions that are controversial within the Church either without an opinion or a well-deserved analysis of each side. However, far from a dry treatment of theology, Lewis gives us a laugh through each turn as he cuts through the heady stuff for the “why behind” each discussion item. Broadly, Lewis discusses the issues of Right &amp; Wrong, What Christians Believe, Christian Behavior vs Secular Behavior, and then concludes with a layman’s review of how the deepest theological topics (Trinity, virgin birth, and free will to name a few) still have profound impact on our daily lives and experiences with God.<br /><br /><h4>Take Aways</h4><br /><span style="white-space: pre;"> </span>I have read this particular book several times, at least four times now. I have referenced its work many times more. In some ways, I view my calling similar to his. I feel I am called to understand the deep things of God and make them accessible to everyday people. In my men’s Bible Study, back in Texas, I was consistently asked for the breakdown of particular scriptures and how to apply them accurately but with a layman’s understanding. They remarked how simple I made big things, which is exactly what C.S. Lewis does in all his works. For example, when discussing how we can only understand some of the deep things of God imperfectly, Lewis says:<br />You may ask what good it will be to us if we do not understand it. But that is easily answered. A man can eat his dinner without understanding exactly how food nourishes him. A man can accept what Christ has done without knowing how it works; indeed, he certainly would not know how it works until he has accepted it. Page 55, The Perfect Penitent.<br /><br /><span style="white-space: pre;"> </span>As a man who is fairly disgruntled with the state of our Government in the past five decades or more, I was challenged yet again by Lewis’s discussion of Social Morality. He said it’s not the job of Pastors to lay out specific political agendas any more than it is for them to lay out building codes or write novels. We are each given talents. Christians who are talented in the areas of governance should be leading that charge. He also challenged that both modern Liberals and modern Conservatives would both have items to balk at if we were to walk into a truly Biblical Society.<br /><br /><span style="white-space: pre;"> </span>In regards to Sexual Morality, Lewis challenged that each generation has a standard of modesty and yet that standard has nothing to do with being Chaste. A woman on an island wearing nothing but a leaf skirt could be more Chaste than a woman covered head to toe in Victorian dress. We must not confuse the two, as they are unrelated.<br /><br />I depart with my favorite paragraph of the book this time around. Lewis is discussing Sexual Morality, and he seeks to understand its root. Is it because we are starved sexually that we are prone to sexual excess? Given the modern discussion of sex-trafficking, this may be more relevant than ever.<br /><br />Or take it another way. You can get a large audience together for a strip-tease act – that is, to watch a girl undress on stage. Now suppose you come to a country where you could fill a theatre by simply bringing a covered plate on to the stage and then slowly lifting the cover so as to let everyone see, just before the lights went out, that it contained a mutton chop or a bit of bacon, would you not think that in that country something had gone wrong with the appetite for food? And would not anyone who had grown up in a different world think there was something equally queer about the state of sex instinct among us? Page 96, Sexual Morality<br /><br />He goes on to observe that one possible conclusion was to think they had starved in that fictitious country. But if one looks at the way glutton’s eat food in ours, you could also see that perhaps the appetite itself was broken or twisted. So it is with Sexual Appetite, Sexual Identity Disorders, and many modern issues, such as LBGT rights. The appetite has been broken, twisted, and it needs to be restored to God’s Health.<br /><br />I continue to be challenged by material written long before my birth and challenged to produce my own. This generation needs its own army of C.S. Lewis’s; able to produce the timeless truths of God’s Word in a modern layman’s way, using modern parallels, parables, and addressing modern issues… showing they really aren’t all that new or special.<br /><br /><h4>Bibliography</h4><br />Lewis, C. S. (1952, 1980). Mere Christianity. New York, NY: Harper Collins Publishers.<br /><br /><br /><br /><br /><span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br /><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br /><br /><span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br /><span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a>&nbsp;(Myers-Briggs Type): INFJ</span></div>