---
title: 'A Text Message (SMS) From God to You'
date: '2019-05-26T14:51:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1117117051230907799'
blogger_filename: '/2019/05/a-text-message-sms-from-god-to-you.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Templates'
---

A Text Message (SMS) From God to You<br /><br />This tool is designed to help you practice hearing from God... One word from God can change your life forever.<br /><br />Here's how it works:<br /><br /><ol><li>Start by getting a pad of paper and a pen&nbsp;</li><ul><li>(or you can do it electronically in OneNote or Evernote... but there's something about handwriting that helps you stay out of your head and in tune with your heart).</li></ul><li>Write each of these statements and leave enough room to write what you hear.</li><ul><li>I see you…</li><li>I hear you...</li><li>I care...</li><li>I am...</li></ul><li>Get really still, in a quiet place or with worship music if you'd like.</li><li>Focus on your heart and belly, not your mind.</li><li>Then just write whatever you feel God's response is saying.&nbsp;</li></ol>Don't over think it, or second-guess... this is just a tool to help you practice hearing God.<br /><br />Here is an example of what I heard when I tried it the first time.<br /><br /><b>I see you…</b><br /><span style="white-space: pre;"> </span>- Afraid to take on new challenges because you think you'll fail.<br /><span style="white-space: pre;"> </span>- Lonely &amp; Aching for a companion<br /><span style="white-space: pre;"> </span>- So busy you keep putting the urgent in front of the important.<br /><br /><b>I hear you…</b><br /><span style="white-space: pre;"> </span>- Complaining about not having enough…<br /><span style="white-space: pre;"> </span>- Crying "I can't do this anymore"<br /><span style="white-space: pre;"> </span>- Asking for help<br /><br /><b>I care…</b><br /><span style="white-space: pre;"> </span>- About all of your needs (spiritual, emotional, financial, and physical).<br /><span style="white-space: pre;"> </span>- About your boys more than you do (I've got them).<br /><span style="white-space: pre;"> </span>- About your future &amp; I have idea and plans you haven't imagined yet.<br /><br /><b>I am…</b><br /><span style="white-space: pre;"> </span>- You spouse<br /><span style="white-space: pre;"> </span>- Your healer<br /><span style="white-space: pre;"> </span>- Your provider<br /><span style="white-space: pre;"> </span>- Your Comforter<br /><span style="white-space: pre;"> </span>- Your Way Out &amp; Your Way Up<br /><span style="white-space: pre;"> </span>- Your Unexpected End<br /><span style="white-space: pre;"> </span>- Your Boys' Father<br /><span style="white-space: pre;"> </span>- Your Future Wife's Father<br /><span style="white-space: pre;"> </span>- Your Father<br /><span style="white-space: pre;"> </span>- Your Friend<br /><br /><b>*Come Play With Me!*</b><br /><div><br /></div><br /><span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br /><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div><div class="MsoNormal"><span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a>&nbsp;&amp; <a href="http://topos.consulting/">Topos.Consulting</a></span><br /><br /><span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br /><span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a>&nbsp;(Myers-Briggs Type): INFJ</span></div>