---
title: 'Discipleship Model of Lay Counseling'
date: '2020-11-28T02:11:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3701955656528516994'
blogger_filename: '/2020/11/discipleship-model-of-lay-counseling.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Class Assignment'
  - 'Mental Health'
---

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12pt;">&nbsp;</span></p>

<h3 style="text-align: center;"><span class="MsoBookTitle"><span style="font-size: 12.0pt; line-height: 107%;">Pastoral
Care Interview:&nbsp;</span></span><b><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;;">With
Sean Fryling, Pastor for Real Life Ministries</span></b></h3>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">&nbsp;</span><span style="font-size: 12pt;">Darrell
Wolfe</span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Biblical
Counseling, The King’s University<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Counseling
in the Church (BIBC 3304)<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Glenna
Massey<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">November
29, 2020</span></p>

<p class="MsoNormal"><b><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">&nbsp;</span></b></p><p class="MsoNormal"><b><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;"><br /></span></b></p>

<h4 style="text-align: left;">Abstract</h4><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">On
Wednesday, November 11, 2020, I interviewed Sean Fryling, Pastoral Care Pastor
for Real Life Ministries in Post Falls, Idaho </span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;Tjtk1bmc&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;(Fryling,
2020)&quot;,&quot;plainCitation&quot;:&quot;(Fryling,
2020)&quot;,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:347,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/ED27TIYR&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/ED27TIYR&quot;],&quot;itemData&quot;:{&quot;id&quot;:347,&quot;type&quot;:&quot;interview&quot;,&quot;abstract&quot;:&quot;Darrell
Wolfe (Interviewer) student at The King's University, sat down with Sean F
(Interviewee) Pastoral Care Pastor for Real Life Ministries, Post Falls, ID to
discuss the Pastoral Care/Lay Counseling available at Real
Life.&quot;,&quot;language&quot;:&quot;English&quot;,&quot;title&quot;:&quot;Pastoral
Care/Lay Counseling Interview: Real Life
Ministries&quot;,&quot;title-short&quot;:&quot;Interview - Pastoral
Care&quot;,&quot;URL&quot;:&quot;https://www.reallifeministries.com/pastoral-care&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Fryling&quot;,&quot;given&quot;:&quot;Sean&quot;}],&quot;interviewer&quot;:[{&quot;family&quot;:&quot;Wolfe&quot;,&quot;given&quot;:&quot;Darrell&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,11]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">(Fryling, 2020)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-end'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">. Though many
pastors freely meet with their congregants, most of the churches in North Idaho
are too small for a designated counseling ministry. After asking several
people, including two licensed counselors, Real Life was the only church I found
with an advertised Pastoral Counseling service in this area. Several people
indicated they send people to Real Life for that need (which played an
interesting role in our interview). Real Life also offers group opportunities,
like Griefshare and Celebrate Recovery. While Elijah House (mentioned in the
text on pages 90 and 307) holds office right here in the area, they did not
respond to my request for an interview </span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;l9HaPvc9&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;(Tan
&amp; Scalise, 2016)&quot;,&quot;plainCitation&quot;:&quot;(Tan &amp; Scalise,
2016)&quot;,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:172,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/WI9NZZZA&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/WI9NZZZA&quot;],&quot;itemData&quot;:{&quot;id&quot;:172,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BV4409
.T35 2016&quot;,&quot;edition&quot;:&quot;Revised and updated
edition&quot;,&quot;event-place&quot;:&quot;Grand Rapids,
Michigan&quot;,&quot;ISBN&quot;:&quot;978-0-310-52427-4&quot;,&quot;number-of-pages&quot;:&quot;318&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Michigan&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Lay Counseling: Equipping Christians for a
Helping Ministry&quot;,&quot;title-short&quot;:&quot;Lay
counseling&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Tan&quot;,&quot;given&quot;:&quot;Siang-Yang&quot;},{&quot;family&quot;:&quot;Scalise&quot;,&quot;given&quot;:&quot;Eric
T.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2016&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 11.0pt;">(Tan &amp; Scalise, 2016)</span><!--[if supportFields]><span
style='font-size:12.0pt;line-height:200%;mso-bidi-font-family:"Times New Roman"'><span
style='mso-element:field-end'></span></span><![endif]--><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">. The following
are the results of my interview with Sean and some conclusions about Pastoral
Care as described by Real Life.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; margin-left: .5in; text-indent: .5in;"><i><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Keywords:
pastoral care, lay counseling, marriage counseling<o:p></o:p></span></i></p>

<h4 style="text-align: left;"><br /></h4><h4 style="text-align: left;">The Interview</h4><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Right
up front, Sean let me know that Real Life no longer offers true lay counseling but
offers a discipleship model. He is the third pastor to handle Pastoral Care for
Real Life. The first two pastors who started the program were both licensed
mental health counselors who met with members of the congregation for
counseling sessions. As the ministry grew, the need for counseling outgrew the
ability of these two men to keep up with demand, which is when they began to
develop the discipleship model. Sean has a Masters in Theology and moved from
California to join the staff at Real Life ministries. Although the church
typically only hires and trains from within, due to the same discipleship model
throughout the church, they brought Sean in as one of the few “outsiders”. <o:p></o:p></p>

<span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 11.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;"><br clear="all" style="mso-special-character: line-break; page-break-before: always;" />
</span>

<p class="MsoNormal"><b><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">&nbsp;</span></b></p>

<h4 style="text-align: left;">Lay Counseling Ministry System: Discipleship Model</h4><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">The model
described by Sean would be closest to an Informal-Spontaneous model of lay
counseling, conducted by small group leaders and class leaders in the context
of on-going relationship. To his knowledge, Real Life did not base their model
from any other church’s model, though some of the work predated his arrival.
Pastors in the community previously referred their members to Real Life;
however, Sean discouraged this practice. He says that “all we do is
discipleship”. He said that when a pastor refers people to Real Life, Sean
calls the pastor to discuss what it means to disciple your own people, and
offers to help the pastor develop a discipleship culture in his own church. Through
this process, they have worked with multiple churches around the country to
develop a discipleship culture in their own church communities.<o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">As Sean sees it,
“counseling” has been largely ineffective for Real Life, they even removed the
term counseling from the website and replaced it with Pastoral Care. What they
found was more effective was “discipleship”. When someone comes in to meet with
Sean, he assesses their needs in one to five intake sessions. He offers
biblical insights and a non-judgmental ear, then directs them to a small group,
group class (such as Celebrate Recovery), and/or to service-involvement in a
ministry. He says that “relationship is key”. He claims that up to ninety-five
percent of the people who see him find their problems resolve themselves when
they are plugged into vibrant community and into active (not passive) discipleship.<o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">In these small
group/class environments, leaders are hand-selected, supervised, and trained in
on-going relationship with their own leadership. The culture of the church is a
culture of “discipleship”. He says that leaders must be “pastoral”; they must
know the names of the people in their groups, their family’s names, their
successes, and struggles, and follow up with them regularly. They are expected
to reach out to anyone missing more than two weeks to see how they are doing
and if there is anything they can do to help. They are also expected to look
for those who are “pastoral” within their own groups, and disciple them into up
and coming leaders. <o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">For a select few,
typically couples, who need more than small group community offers, Sean meets
with them for regular Pastoral Care (counseling). The counseling is focused on
listening to them, helping them listen to each other, and listening for and seeking
God’s heart in the counseling session. Sean said that he only works with people
who demonstrate and openness to hear God and change. If they are defensive,
blaming, or showing any other signs of abuse, addiction, mental illness, or
trauma, he refers them to licensed counselors in the area with a demonstrated
heart to provide biblical counseling as well as clinical therapy. He stopped
referring to counselors outside of this list, because he found anyone going to
a counselor who did not also discuss the Bible often showed no improvement or
even got worse. Sean claims these cases of requiring referral comprise less
than five percent of the people he sees.</p><p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">&nbsp; <o:p></o:p></p>

<h4 style="text-align: left;">Counseling Process</h4><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sean’s
most common on-going counseling is done with couples in the form of marriage
counseling and pre-marital counseling, though he works with others too. The
approach is described as “take the Bible, apply it to real life, and change
will happen in the context of relationships lived out of those realities”. He
says that many people have never heard the real-life application of Biblical
wisdom as applied to marriage conflicts. Sean will use psychological techniques
if they work; however, he does not purposefully study them. He prefers to leave
those to “professionals”. There is only one assessment or test used in his
office, it is known as the Prepare/Enrich Marriage and Premarital Assessment <!--[if supportFields]><span
style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;Uc8Zd9oL&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;({\\i{}P/E
Assessment}, 2020)&quot;,&quot;plainCitation&quot;:&quot;(P/E Assessment,
2020)&quot;,&quot;noteIndex&quot;:0},&quot;citationItems&quot;:[{&quot;id&quot;:468,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/97GXK8J8&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/97GXK8J8&quot;],&quot;itemData&quot;:{&quot;id&quot;:468,&quot;type&quot;:&quot;webpage&quot;,&quot;abstract&quot;:&quot;EMBRACE
THE JOURNEY Relationships thrive when there is understanding.<span
style='mso-spacerun:yes'>  </span>Let us provide the insights to get there. THE
#1 PREMARITAL AND MARRIAGE ASSESSMENT FOR OVER 35
YEARS&quot;,&quot;container-title&quot;:&quot;Prepare-Enrich&quot;,&quot;genre&quot;:&quot;Informational
Sales Page&quot;,&quot;title&quot;:&quot;PREPARE/ENRICH PREMARITAL AND MARRIAGE
ASSESSMENT&quot;,&quot;title-short&quot;:&quot;P/E
Assessment&quot;,&quot;URL&quot;:&quot;https://www.prepare-enrich.com/&quot;,&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,22]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><span style="line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt;">(<i>P/E
Assessment</i>, 2020)</span><!--[if supportFields]><span style='mso-element:
field-end'></span><![endif]-->. He claims that it has a high success rate in
predicting marital failure and works well in preparing a couple to marry or go
deeper in marriage. <o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Each
session starts with prayer and focuses on listening. He says that he knows he
is successful if he did more listening and asking than talking or preaching.
Sean also stated that the better he listens for the Holy Spirit in the session,
the more accurate and helpful questions he can ask. The sessions are focused on
faith in God to restore, hope that God will show up and things will get better,
and on loving each other well. <o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If
the church refers to a specialist, they will work with the individual to get
the help they need. How much support, especially financial support, depends on how
connected they are in the church. If the person rarely comes and is not
involved, Sean tries to get them involved first. He finds most problems resolve
themselves in connected community. However, if they are connected and still
struggling beyond what the church can provide, they will jump in and assist the
person with getting the right help. Sometimes this includes helping them apply
for help that is available, such as Medicaid or other insurances, while
sometimes the help is direct financial aid in the form of paying for a certain
number of sessions. <o:p></o:p></p><p class="MsoNormal" style="line-height: 200%;"><br /></p>

<h4 style="text-align: left;">Counselor/Leader Selection, Training, and Oversight</h4><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Real
Life bases their model on the foundation scripture of Matthew 4:19: “Follow me,
and I will make you fishers of men”. One cannot simply sign up to lead a class
and be leading by the next week. When someone has either asked to lead or has
been identified as a good candidate to lead; they are invited into a selection
process. <o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">The process begins
informally as a series of coffee meetings. The pastoral care team member, often
Sean himself, seeks to understand the person’s background, motives, and history
with discipleship. They want to know first, “are you a disciple”? If they are
not actively being discipled, they are referred into a small group or mentorship
to begin that process first. They see the progression as Share (the good news),
Connect (with community), Minister (within community), and Disciple (be trained
and be training others). Therefore, the next thing they want to know is if the
candidate is disciplining people already. Are they already leading in the roles
they have? Have they reached out to people, shared with them, helped them
connect with community, etc.?<o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">Once selected, the
leader is trained under other pastors and leaders who are looking for
“pastoral” qualities. They watch how the person develops and whether they take
initiative to lead well and love well. Through weekly check-ins, they seek to
ensure the process is going well for everyone involved. <o:p></o:p></p>

<p class="MsoNormal" style="line-height: 150%; margin-bottom: 0in; text-indent: .5in;">They
ask questions such as:<o:p></o:p></p>

<p class="MsoListParagraphCxSpFirst" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]-->How are you, really? Is everything going well? <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]-->Are you making disciples? How many leaders are
you developing?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]-->Are you loving people well, reaching out when
they are missing, and generally “pastoral”?<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="line-height: normal; margin-left: .25in; mso-add-space: auto; mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]--><span style="font-family: Symbol; mso-bidi-font-family: Symbol; mso-fareast-font-family: Symbol;">·<span style="font-family: &quot;Times New Roman&quot;; font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]-->Do you know that you are more important to us
than the tasks we assign you?<o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">Leaders are all
accountable to other leaders. Everyone is responsible for the people who serve
under them, attend their group, or participate in their classes. Therefore, if
there are issues or failure during the leading process, they are not rejected
but discipled further, with a focus on confession and healing. If someone
appears to be struggling, Sean himself may take them out for coffee and say
“Hey, how are things going? What’s happening in your life”? He said, “Never
assume you know anything. You might think they are slacking, but they are
dealing with a death in the family.”<o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">Sean said that the
church must stop expecting baby Christians (new Christians) to come into the
church knowing anything. Too often the church the focuses on “getting people
saved” and then once saved they are left to figure it all out on their own.
Then the churches wonder why the pews are full of baby Christians who have not
grown. This process of discipleship is the process Real Life uses to bring
people from one level of maturity to the next. Sunday mornings are the “lecture
hall” of Church. Lectures are good but are the least effective mode of
transformation. Discipleship has proven to be the most effective. People are
transformed in the context of connected community.<o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">When asked for the
greatest dilemma he has experienced as a Pastoral Care/Counselor, Sean said
that the issues of boundaries with the opposite sex often poses the biggest
problems. A person will let a person of the opposite sex drop off things at the
house or become too close on social media; then an affair is discovered, or
someone ends up in prison. The best policy is to not be too loose with any
relationship, regardless of how harmless you think it is. <o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">When asked for his
thoughts on the LGBT community, Sean smiled. To anyone claiming LGBT identity,
Real Life says “Welcome, we are so glad you are here.” However, if that person
wants to lead or perform a same-sex wedding, there will be deeper
conversations. Real Life does not consider “orientation” a sin; however, does
consider the only appropriate expression of sex to be within the confines of a
one-man, one-woman, marital covenant relationship. There have been pastors on
staff who had an LGBT orientation but did agree that the expression of that
would be sin, and therefore live as celebrate pastors. They are loved and
welcome on staff, provided they continue that lifestyle.<o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">Finally, he said that
abiding in relationship with God is more important than any work he does for
the ministry. If he finds he is relying too much on his own skills, he
considers that a warning sign he is not abiding enough. He said he is steadfast
in not brining work home. He leaves on time (unless there is a true crises) and
turns off the phone when home. He will not answer calls, texts, or emails from
the home. If he were to answer the phone while his wife was talking, he would
be telling her that the church was more important than her heart, and he
refuses to do so. He was even fired once for taking a hard stand on this
policy, the church later repented and brought him back. <o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">Sean said his
personal best practice to avoid burnout was a quote from Dallas Willard, which
he keeps on his desk: “Ruthlessly eliminate hurry from your life”. To practice
this, he chooses the slow lane on the freeway, picks the longest line in the
grocery store, and lingers after service. He asks himself this question: “Do
you rest from your work; or, do you work from a place of rest? You’ll always
find joy and peace in rest.” <o:p></o:p></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;">Sean left me with
this parting thought: “The reason we have so many Bible colleges is because the
church failed to do its job in discipleship.” For this reason, pastors are generally
selected from within Real Life, trained up to be disciplers, and then hired on
staff after an ordination process (including defending a theological position).
They hire very few people from Bible colleges unless those people have shown an
affinity for the discipleship culture or have been raised into the discipleship
culture by attending Real Life for some time. Many of their pastors were former
electricians or farmers; “sound familiar?” he said with a wink.<o:p></o:p></p><p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><br /></p>

<h4 style="text-align: left;">Conclusion</h4><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The interview gave me mixed feelings. On one hand, I
lament over pastors who say things like “If you just believed this Bible, you
wouldn’t be depressed”. In my experience, it has been Biblically oriented
licensed mental health professionals that provided me with the most growth, while
well-meaning pastors often did more harm than good. In some ways, I felt that
sentiment during this interview. However, Sean listens and asks questions, gets
the counselee talking and expressing emotions, and naturally does the things a
good counselor would do. He did some of these with me during the interview. So,
I feel that he may be a “counselor” even if he does not study counseling
techniques.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; On the other hand, I found my heart “burned within me” as
he described the atmosphere of discipleship (Luke 24:32)</span><span style="font-size: 12.0pt; line-height: 200%;">. I am, by nature and nurture, an
isolationist. This is a character defect I have been working on for a few
years. I have come a long way, but I am nowhere near as connected as Sean
described. I do not know that I would pass the Real Life selection process for
leadership as I exist today. This will be a continued area of improvement for
me.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%;">The Real Life setup does not seek to
incorporate counseling techniques into its model, I see this as a deficit.
While I would prefer to see a layer of lay counseling added to the Real Life
model, I am hard-pressed to ignore the amazing work they have done and their
results. I would love to see the discipleship model as the foundation under
which a lay counseling service operated. Lay counseling could reach those who
find it hard to connect and counseling training could make the disciple-makers
more effective. While I will continue to seek training as a lay counselor and
possibly a licensed counselor, I will be looking for ways to incorporate
discipleship into my life as well. The benefits of connected community are core
to any effective counseling program. </span><b><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;"><o:p></o:p></span></b></p><p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%;"><br /></span></p>

<h4 style="text-align: left;">References</h4><h1><o:p></o:p></h1>

<p class="MsoBibliography"><o:p>&nbsp;</o:p></p>

<p class="MsoBibliography"><!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_BIBL
{&quot;uncited&quot;:[],&quot;omitted&quot;:[],&quot;custom&quot;:[]}
CSL_BIBLIOGRAPHY <span style='mso-element:field-separator'></span><![endif]-->Fryling, S. (2020, November 11).
<i>Pastoral Care/Lay Counseling Interview: Real Life Ministries</i> (D. Wolfe,
Interviewer) [Interview]. https://www.reallifeministries.com/pastoral-care<o:p></o:p></p>

<p class="MsoBibliography"><i>PREPARE/ENRICH
PREMARITAL AND MARRIAGE ASSESSMENT</i>. (2020). [Informational Sales Page]. Prepare-Enrich.
https://www.prepare-enrich.com/<o:p></o:p></p>

<p class="MsoBibliography">Tan,
S.-Y., &amp; Scalise, E. T. (2016). <i>Lay Counseling: Equipping Christians for
a Helping Ministry</i> (Revised and updated edition). Zondervan.<o:p></o:p></p>

<p class="MsoNormal"><!--[if supportFields]><span style='mso-element:field-end'></span><![endif]--><o:p>&nbsp;</o:p><span style="font-size: 12pt; text-align: center;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="text-align: center;"><span style="text-align: left;"><b>~~~~~~~~~~~~~</b></span><span style="font-size: 12pt; text-align: left;">&nbsp;</span></p><p align="center" class="MsoNormal" style="text-align: center;"><span style="font-size: 12pt; text-align: left;"><br /></span></p>

<h3 style="text-align: center;"><span style="font-size: 11.0pt;">Interview Questions</span></h3>

<br />

<h4 style="text-align: left;"><span style="font-size: 11.0pt; line-height: 200%;">Counseling Ministry/System</span></h4>

<p class="MsoListParagraphCxSpFirst" style="mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->1.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->How
do you explain the difference between clinical counseling and biblical
counseling?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->2.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->What
model do you prefer? <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; mso-list: l1 level2 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->a.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->Informal-Spontaneous;
Informal-Organized; Formal-Organized<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->3.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->Did
you base your model on examples of other ministry’s models? If so, which ones.<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->4.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->Where
do you counsel: In office, coffee shops, homes?<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->5.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->What
types of resources do you offer outside of one-on-one Counseling?<o:p></o:p></p>

<h4 style="text-align: left;"><span style="font-size: 11.0pt; line-height: 200%;">Counseling</span></h4>

<p class="MsoListParagraphCxSpFirst" style="mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->6.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->Your
approach: Psychology vs Christianity?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; mso-list: l1 level2 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->a.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->Separate
but equal; equal mixable; only the Bible is needed; use whatever works if it
lined up with scriptures, other way of seeing things?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->7.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->Do
you use any tests (spiritual gifts, personality, or otherwise) with counselors
or counselees?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->8.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->How
do you rely on the Holy Spirit in Counseling?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->9.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->When
do you refer to specialist, attorney, licensed counselor? <o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->10.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;
</span><!--[endif]-->Do
you assist with that referral, financially or otherwise, make sure they are
seen?<o:p></o:p></p>

<h4 style="text-align: left;"><span style="font-size: 11.0pt; line-height: 200%;">Counselors</span></h4>

<p class="MsoListParagraphCxSpFirst" style="mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->11.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;
</span><!--[endif]-->How
do you select counselors?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->12.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;
</span><!--[endif]-->How
do you train counselors?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->13.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;
</span><!--[endif]-->How
do you decide who to assign a counselee with?<o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->14.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;
</span><!--[endif]-->How
do you evaluate the effectiveness of counseling?<o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="mso-list: l1 level1 lfo2; text-indent: -.25in;"><!--[if !supportLists]-->15.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;
</span><!--[endif]-->What,
if any, oversight/supervision do counselors receive?<o:p></o:p></p>

<h4 style="text-align: left;"><span style="font-size: 11.0pt; line-height: 200%;">Additional Required for
Class</span></h4>

<p class="MsoListParagraphCxSpFirst" style="mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->1.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->Ask the pastor/counselor about the greatest
ethical issue he/she has addressed and why he/she sees it as his/her greatest
dilemma. <o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->2.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->Ask the pastor/counselor if and how he/she
integrates biblical truths into counseling a specific counseling topic. Pick
one topic that is relevant to current sociopolitical and spiritual trends
impacting the church and community. <b><i>LGBT Clients</i></b><o:p></o:p></p>

<p class="MsoListParagraphCxSpMiddle" style="mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->3.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->If there are topics from our readings you do not
understand, ask the pastor you are interviewing for his/her perspective and
insight. <i>Nothing I can think of today. Test warning, but I don’t think he
would know. Just posted it in General Questions in Blackboard.</i><o:p></o:p></p>

<p class="MsoListParagraphCxSpLast" style="mso-list: l0 level1 lfo1; text-indent: -.25in;"><!--[if !supportLists]-->4.<span style="font-size: 7pt; font-stretch: normal; font-variant-east-asian: normal; font-variant-numeric: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span><!--[endif]-->Ask about the pastor’s self-care.<o:p></o:p></p>

<div><!--[if !supportFootnotes]--><br clear="all" />

<hr align="left" size="1" width="33%" />

<!--[endif]-->

<div id="ftn1">

<p class="MsoFootnoteText"><a href="file:///C:/Google%20Drive/School_Darrell/-TKU/Courses/Counseling%20in%20the%20Church%20-%20BIBC3304ONL2/Wolfe,%20Darrell_%20Interview%20Questions.docx#_ftnref1" name="_ftn1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[1]</span></span><!--[endif]--></span></a> <a href="https://www.reallifeministries.com/pastoral-care">https://www.reallifeministries.com/pastoral-care</a>
<o:p></o:p></p><p class="MsoFootnoteText"><br /></p>

</div>

</div>
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
