---
title: 'Render unto God and Caesar: Was Jesus’ Mission and Message Political? Exegesis of Luke 20:19-26'
date: '2020-12-04T07:35:00.0020000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '1342866883910740461'
blogger_filename: '/2020/12/render-unto-god-and-caesar-was-jesus.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Class Assignment'
  - 'Biblical Studies'
---

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12pt;">Research
Paper:</span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span class="MsoBookTitle"><span style="font-size: 12.0pt; line-height: 200%;">Was Jesus’
Mission and Message Political? <o:p></o:p></span></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span class="MsoBookTitle"><span style="font-size: 12.0pt; line-height: 200%;">Exegesis of Luke
20:19-26<o:p></o:p></span></span></p>

<p class="MsoNormal" style="line-height: 200%;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">&nbsp;</span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Darrell
Wolfe<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Literature,
The King’s University<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Life
of Jesus (BIBL-2302)<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Professor
Jason Moraff<o:p></o:p></span></p>

<p align="center" class="MsoNormal" style="line-height: 200%; text-align: center;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">December
6, 2020<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%;"><b><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">&nbsp;</span></b></p>

<p class="MsoNormal"><b><span style="font-size: 12.0pt; line-height: 107%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;">&nbsp;</span></b></p>

<h3 style="text-align: left;">Introduction</h3><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">This
paper seeks to examine the question: Was Jesus’ mission and message political?
The answer requires a definition of the word: Political. For this paper,
“political” will be used to mean those activities and policies which together affect
the governing of a country or kingdom<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn1" name="_ftnref1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[1]</span></span><!--[endif]--></span></a>.&nbsp; The paper will examine how Jesus’ mission and
message had political ramifications. The paper will establish that God is
directly involved in the affairs of his people and sees himself as a literal
King. The paper will examine the text of Luke 20:19-26 where a group is sent to
Jesus to trap him and hand him over to the government because the political
leadership of Israel were threatened by him. The paper will position Jesus as king
over a literal kingdom, and what that might mean for us today. The history, culture,
and conflict into which King Jesus was born are relevant to examine this
question of Jesus’ mission and message.<o:p></o:p></span></p>

<h3 style="text-align: left;">God’s Kingdom Reign, Israel, and the Roman Empire</h3><h1><o:p></o:p></h1>

<h4 style="text-align: left;">Israel’s Rightful King</h4><h2><o:p></o:p></h2>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Up
to the time of Samuel, God himself reigned as king over Israel. Israel rejected
God as their King and requested a natural king so they could be like everyone
else (Samuel 8:6-9). Samuel warned Israel that the king they requested would
take everything that belonged to them including taxes (Samuel 8:20-22). Then
after God replaced the first king (Saul) with the second king (David), God
promised David that a king would come from his own line that would build a
house (family) for God and that this new king’s throne would last forever (1 Chronicles
17:1-27).<o:p></o:p></span></p>

<h4 style="text-align: left;">The Ages of Kings</h4><h2><o:p></o:p></h2>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">In
587 BCE, Babylon conquered Israel and destroyed the Temple, seemingly ending
the line of Israeli Kings.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn2" name="_ftnref2" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[2]</span></span><!--[endif]--></span></a> In
Daniel, Nebuchadnezzar’s statue showed Israel their new kings beginning from
King Nebuchadnezzar the Babylonian leading up to the arrival of the Messiah-King.
Daniel describes the final kingdom as the “rock not cut from human hands” that
will crush every previous kingdom, which would grow until it filled the earth
(Daniel 2). History shows that this came to pass in the form of the golden
Babylonian empire, the silver Medo-Persian empire, the bronze Grecian-Macedonian
empire, the iron Roman empire, and the final Rock Kingdom; which was
established when Jesus arrived preaching and teaching the Kingdom of God.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn3" name="_ftnref3" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[3]</span></span><!--[endif]--></span></a> <o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Israel’s
national identity was preserved in part due to the fall of Babylon to Persia
who then held a policy toward Jews that “oscillated between toleration and
benign neglect”.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn4" name="_ftnref4" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[4]</span></span><!--[endif]--></span></a>
When the Persian Empire took over, Kings Cyrus and Darius were more friendly to
the people of Israel and allowed for them to return to their homeland and
rebuild the Temple (circa 520-519 BCE).<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn5" name="_ftnref5" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[5]</span></span><!--[endif]--></span></a> When
the new Grecian-Macedonian Empire attempted to Hellenize Judea (175-168 BCE),
it created such resistance that it led to a massive revolt under the
Maccabeans.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn6" name="_ftnref6" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[6]</span></span><!--[endif]--></span></a>
This led to a spirit of independence among the Jewish people. Several smaller
revolts and rebellions rose from time to time. In the final stages of Roman
rule, Daniel predicted a kingdom whose people did not mix well, this was
largely referring to the conflicts between Israel and Rome. <o:p></o:p></span></p>

<h4 style="text-align: left;">Israel’s Conflicts with Rome</h4><h2><o:p></o:p></h2>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Caesar
Augustus (27 BCE to 14 AD) divided Rome into ten provinces (just as Daniel
predicted with the ten toes), and Jesus (The Rock) was born in the middle of
his reign.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn7" name="_ftnref7" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[7]</span></span><!--[endif]--></span></a> In
63 BCE, Rome expanded to include Israel. “Rome ruled her empire with tolerance
for local customs and cultures…” and the issue that impacted ordinary people
most was taxation because it forced peasant farmers into hardship<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn8" name="_ftnref8" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[8]</span></span><!--[endif]--></span></a>. The
society was village-based and agrarian; therefore, the increasing pressure to
pay taxes monetized the society breaking down cultural norms.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn9" name="_ftnref9" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[9]</span></span><!--[endif]--></span></a> &nbsp;The people generally believed that the
“benefits of peace and prosperity that Rome claimed to give its subjects could
not obscure the fact that the empire served primarily the prosperity of the
Romans and local elites who supported them”.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn10" name="_ftnref10" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[10]</span></span><!--[endif]--></span></a> The
Jews assimilated aspects of Roman culture (such as speaking Greek) while
denouncing other aspects (such as Roman sacrifices). The religious leaders
governed the people on behalf of Rome and the local Governor (Pilate). The average
people held attitudes that “ranged from mercenary accommodation to violent
protest”.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn11" name="_ftnref11" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[11]</span></span><!--[endif]--></span></a>
Horsley describes the condition of Israel during the times of Jesus as follows:<o:p></o:p></span></p>

<p class="MsoQuote"><span style="font-size: 12.0pt; line-height: 107%;">"Domestic
affairs were left to the priestly aristocracy again. From 6 to 66 C.E. four
principal families dominated the society, with the office of high priest, in
effect, alternating among them. The priestly aristocracy also dominated the
Sanhedrin or high counsel throughout this period. Partially because of the
awkward combination of Roman governor and Jewish priestly aristocracy, Roman
control of Jewish Palestine was not as tight as it had been under Herod. But
with all matters of importance in the hands of the high priests and the Roman
governor, there was no legitimate channel for political participation by the people."<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn12" name="_ftnref12" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[12]</span></span><!--[endif]--></span></a><o:p></o:p></span></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<h4 style="text-align: left;">The Political Class</h4><h2><o:p></o:p></h2>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Since
Rome ruled in conjunction with local leaders, in this case, priestly
aristocracy, there was no clear separation between religion, morals, law, and
politics.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn13" name="_ftnref13" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[13]</span></span><!--[endif]--></span></a>
There were three religious-political parties with influence in Israel during
the days of Jesus. The Essenes are never mentioned in the Gospels; however, their
works are retained in the Dead Sea Scrolls.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn14" name="_ftnref14" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[14]</span></span><!--[endif]--></span></a>
They were a monastic-style secret club who were preparing to fight a physical
holy war with Rome to free Israel from their oppression. The Essenes would
certainly have had a role to play in the mindset of average townsfolk,
especially since the mini-revolt under Herod (circa 4 AD) would be still fresh
in their minds from just a few decades before.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn15" name="_ftnref15" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[15]</span></span><!--[endif]--></span></a> <o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">The
Pharisees were known for being detail-oriented interpreters of the Torah. They
held the most influence over the average first-century Jewish mind.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn16" name="_ftnref16" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[16]</span></span><!--[endif]--></span></a> While
Mark 12:13 and Matthew 22:15 lay the tax question at the feet of the Pharisees,
Luke 20:19-20 only refers to the test givers as spies sent by the chief priests
and scribes (lawyers). Most Pharisees were local Rabbis in the villages, but
there were some Pharisees represented in Temple leadership.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn17" name="_ftnref17" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[17]</span></span><!--[endif]--></span></a>
This means the ones interacting with Jesus in Galilee are likely different than
the ones posing the tax question in the temple.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">The
Sadducees were the dominant ruling class of high priests and other high-ranking
officials within the Temple. The Sadducees held almost all political power, but
their religious views were not influential.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn18" name="_ftnref18" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[18]</span></span><!--[endif]--></span></a> These
were the most threatened by Jesus because any revolt of the people would bring
down quick and harsh reaction from Pilate (just as Herod had done before him),
which threatened their own rule by association. <o:p></o:p></span></p>

<h3 style="text-align: left;">Literary Setting</h3><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">It
is into this climate that we find Jesus entering Jerusalem for a showdown with
the elite leadership of Israel, which led to his death on the cross. Some
estimate that this took place on Tuesday of Passion Week (a few days later, on
Friday, Jesus would be killed).<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn19" name="_ftnref19" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[19]</span></span><!--[endif]--></span></a> <o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Luke
brings us the most complete account of Jesus’ life of all four gospels. Luke’s
writing shows a passion for details that could be compared to a fine artist.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn20" name="_ftnref20" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[20]</span></span><!--[endif]--></span></a> Though
they did not understand his meaning, Jesus prepared his disciples for the
Passion Week letting them know they would be heading to Jerusalem and that he
would be killed (Luke 18:31). Jesus rides into Jerusalem on a donkey to praises
reserved for the coming of Messiah. They even call him a king (Luke 19:38). Upon
arrival, Jesus drove out the money changers and traders and taught in the temple.
The chief priests and lawyers wanted to kick him out but were afraid of the
people starting a riot (Luke 19:47-48). <o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">It
is while Jesus was teaching in the temple that the leaders came to challenge
him. In one such challenge, he told the story of the vineyard owner whose son
was killed by the hired staff, who were then killed by the owner himself. The
leadership of the temple recognized this parable was spoken against them and
they began to look for ways to hand Jesus over to the governor (who had the
authority to kill him). Within days of these events, Jesus would be arrested at
night, turned over to Pilate’s guards, and executed as a rebellion leader. It
is in this context that we find our way into the key text.<o:p></o:p></span></p>

<h3 style="text-align: left;">Exegesis of Luke 20:19-26 (NEB)</h3><h1><o:p></o:p></h1>

<p class="MsoQuote">The lawyers and chief priests wanted to lay hand on him
[Jesus] there and then, for they saw that this parable was aimed at them; but
they were afraid of the people. So they watched their opportunity and sent
secret agents in the guise of honest men, to seize upon some word of his as a
pretext for handing him over to the authority and jurisdiction of the Governor.
They put a question to him: “Master”, they said, “we know that what you speak
and teach is sound; you pay deference to no one, but teach in all honesty the
way of life that God requires. Are we or are we not permitted to pay taxes to
the Roman Emperor?” <o:p></o:p></p>

<p class="MsoQuote">He saw through their trick and said, “Show me a silver piece.
Whose head does it bear, and whose inscription?” <o:p></o:p></p>

<p class="MsoQuote">“Caesar’s”, they replied. <o:p></o:p></p>

<p class="MsoQuote">“Very well then,” he said, “pay Caesar what is due to Caesar
and pay God what is due to God”. <o:p></o:p></p>

<p class="MsoQuote">Thus, their attempt to catch him out in public failed, and
astonished by his reply, they fell silent.<span class="MsoFootnoteReference"> <a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn21" name="_ftnref21" title=""><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[21]</span></span><!--[endif]--></a></span> <o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<h4 style="text-align: left;">The Politics of the Question</h4><h2><o:p></o:p></h2>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Jesus
could have ridden the wave of the crowd’s emotional response to consolidate
power and take over as King of Israel.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn22" name="_ftnref22" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[22]</span></span><!--[endif]--></span></a>
The opportunity mirrors that of the temptation in the wilderness (Luke 4). The
various challenges to Jesus’ authority were all clashes between two regimes or worldviews.
The question of the tax was the most obviously political question, not the only
politically motivated question.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn23" name="_ftnref23" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[23]</span></span><!--[endif]--></span></a> <o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">They
challenge Jesus: Is it legal to pay taxes? If he answers yes, he is going to
upset the people who resent taxation, losing favor with them. If he answers no,
he is guilty of rebellion and they can hand him over to the Roman Governor to
be treated as a rebel. They believe they have him trapped. Jesus sees through
their trap and gives his now-famous response: “Render to Caesar what is
Caesar’s and God what is God’s” (Luke 20:24-26). Taxation was a flashpoint for
the average citizens, and Jesus’ answer “might be interpreted to question
whether Caesar deserved any or all that he asked for”.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn24" name="_ftnref24" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[24]</span></span><!--[endif]--></span></a>
However, Jesus avoids giving a clear yes or no and turns the hearer into the
interpreter, wrestling with what is Caesar’s and what is God’s?<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn25" name="_ftnref25" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[25]</span></span><!--[endif]--></span></a><o:p></o:p></span></p>

<h4 style="text-align: left;">The Coin</h4><h2><o:p></o:p></h2>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">At
face value (pun intended), the Denarius bears Caesar’s image and inscription.
The coin belongs to Caesar; therefore, he has a right to request some of his
own coin back. By that reasoning, it is appropriate to pay taxes because you
have already agreed to abide by the terms of the government by carrying the
coin in the first place.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn26" name="_ftnref26" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[26]</span></span><!--[endif]--></span></a> The
coin itself brings an interesting dynamic to the interpretation. The silver
Denarius became the backbone of the Roman economy. Many versions of the coin
were in circulation throughout the empire at the time. A common theme on the
coins was the image, reverse image, and inscription combining to create a claim
at the divinity of Caesar.<span class="MsoFootnoteReference"> <a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn27" name="_ftnref27" title=""><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[27]</span></span><!--[endif]--></a></span> The
image on the front of a Denarius bore the image of Caesar and became a way of
propagandizing him as a god.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn28" name="_ftnref28" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[28]</span></span><!--[endif]--></span></a><o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">Jesus’
observation about the coin itself is fascinating. “Whose image does the coin
bear? Whose inscription?” Torah refers to mankind as being created in the image
of God (literally, bearing God’s image) (Genesis 1:27). The people are told to
meditate on God’s Torah and bind it to their foreheads and arms (Deuteronomy
11:18-21). Today, Orthodox Jews wrap the tefillin around their arm, binding a
small box with a portion of scripture locked inside.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn29" name="_ftnref29" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[29]</span></span><!--[endif]--></span></a> The
Rabbis who were to bear the image and inscription of God were rejecting God’s
Messiah by even asking this question. In this sense, “Render unto God” could be
read as render unto God the respect and honor due to his Messiah (the rock, the
final King).<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn30" name="_ftnref30" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[30]</span></span><!--[endif]--></span></a><o:p></o:p></span></p>

<h3 style="text-align: left;">Theological Implications</h3><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><i><span style="font-size: 12.0pt; line-height: 200%;">One cannot separate religion and
politics in the Gospels.</span></i><span style="font-size: 12.0pt; line-height: 200%;"> The following points are presented for consideration. God established
Israel as a nation and himself as their literal king. When they rejected him, God
promised future kings would exact taxes; then promised each of the nations that
arose to rule Israel. God fulfilled his promise to Israel by never letting her
live without a king, he never promised that every king would be of Israel.
Therefore, he fulfilled his promise through Samuel in the Israeli kings, but
also in Babylonian, Persian, Greek, and Roman kings. In first-century Israel,
aristocrats ruled the temple and the people on behalf of Rome. Therefore, every
interaction with a religious ruler was an interaction with a political ruler
(akin to a mayor, senator, or governor today). These leaders were threatened by
Jesus’ mission and message. Therefore, his mission and message threatened the
politics of the day. <o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><i><span style="font-size: 12.0pt; line-height: 200%;">The coin confirms God’s role in the
tax.</span></i><span style="font-size: 12.0pt; line-height: 200%;"> Render unto
Caesar what is Caesar’s goes beyond giving him back the coin his kingdom
produced. Samuel 8 and Daniel 2 confirm that God himself established Caesar
over Israel and the taxes he would exact from them.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><i><span style="font-size: 12.0pt; line-height: 200%;">The coin confirmed the political
leaders should have been God’s image-bearers.</span></i><span style="font-size: 12.0pt; line-height: 200%;"> Render unto God the honor and obedience due to him as
his image and inscription bearers. To bear his image and inscription but show
loyalty to Caesar at the expense of loyalty to God’s final King is the ultimate
rejection of God as King. This brings their rejection full circle from Samuel
to Jesus. Those who would bear God’s image and inscription should submit each
decision, especially political decisions, to God.<o:p></o:p></span></p>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><i><span style="font-size: 12.0pt; line-height: 200%;">Jesus’ “Kingdom of God” is a real
kingdom</span></i><span style="font-size: 12.0pt; line-height: 200%;">. God
predicts the four empires and a final rock kingdom that would replace them.
That kingdom of God is the kingdom of the rock. Jesus tells Peter that “on this
Rock (confession of Jesus as Messiah and God) I will build my Church” (Matthew
16:13-20; Luke 9:18-20). Jesus’ kingdom replaces every other kingdom,
eventually conquering Rome just as predicted. The final conquering of Rome was
not accomplished through swords but through the power of God in his people.
Today, the only remnant of the Roman Empire is the “Roman Catholic Church”. <o:p></o:p></span></p>

<h3 style="text-align: left;">Conclusion</h3><h1><o:p></o:p></h1>

<p class="MsoNormal" style="line-height: 200%; text-indent: .5in;"><span style="font-size: 12.0pt; line-height: 200%;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; It
could be said that the Kingdom of God has filled the entire earth. It filled
the known world at the time. The Judeo-Christian ethic has influenced (if not dominated)
world policies and governments since its foundation in the first century.
Whether one could say that Jesus’ mission and message were political depends on
how politics is defined. However, it has been established that his mission and
message had radical political ramifications. God himself has always been the king
of his people and expects their loyalty over any kingdom or government in which
they reside, and over any party affiliation. Given this relationship, it brings
new thoughts to scriptures like “you cannot serve God and money” (Luke 16:13).The
Denarius would have been in Jesus’ money bag with Judas’ when he said this.
Although Jesus often cited the Kingdom of God is not like other kingdoms, it
was predicted as one which would displace the natural kingdoms of Babylon,
Persia, Greece, and Rome. Therefore, it is hard to say that it is only a
“spiritual kingdom”. The first-century p</span><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;;">eople disagreed about who
Messiah (The Anointed One) ought to be. Some believed that there might be three
Anointed Ones, a King, a Priest, and a Prophet.<a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftn31" name="_ftnref31" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 12.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[31]</span></span><!--[endif]--></span></a>
In hindsight, we can see that Jesus was all three, and yet something entirely
different than each title would have suggested to that first-century audience.
Finally, </span><span style="font-size: 12.0pt; line-height: 200%;">to be in the
kingdom of God is to use God’s power to affect the world. It does not
necessarily mean taking positions of power; however, it does mean that the
effectual use of his power will change the culture and affect (or even
displace) governments. Based on these findings, at least in many meaningful
aspects, Jesus’ mission and message were political. </span><b><span style="font-size: 12.0pt; line-height: 200%; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-theme-font: major-fareast;"><o:p></o:p></span></b></p>

<div><!--[if !supportFootnotes]--><br clear="all" />

<hr align="left" size="1" width="33%" />

<!--[endif]-->

<div id="ftn1">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref1" name="_ftn1" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[1]</span></span><!--[endif]--></span></a>
This definition is my own paraphrase of the Oxford Languages dictionary.<o:p></o:p></p>

</div>

<div id="ftn2">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref2" name="_ftn2" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[2]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;0lOy5zCb&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Bruce
Chilton, {\\i{}Pure Kingdom: Jesus\\uc0\\u8217{} Vision of God}, Studying the
Historical Jesus (Grand Rapids, Mich.\\uc0\\u8239{}: London: Eerdmans\\uc0\\u8239{};
Society for Prommoting Christian Knowledge,
1996).&quot;,&quot;plainCitation&quot;:&quot;Bruce Chilton, Pure Kingdom:
Jesus’ Vision of God, Studying the Historical Jesus (Grand Rapids, Mich. :
London: Eerdmans ; Society for Prommoting Christian Knowledge, 1996).&quot;,&quot;noteIndex&quot;:2},&quot;citationItems&quot;:[{&quot;id&quot;:415,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/DFZRZQ67&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/DFZRZQ67&quot;],&quot;itemData&quot;:{&quot;id&quot;:415,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS2417.K5
C49 1996&quot;,&quot;collection-title&quot;:&quot;Studying the historical
Jesus&quot;,&quot;event-place&quot;:&quot;Grand Rapids, Mich. :
London&quot;,&quot;ISBN&quot;:&quot;978-0-8028-4187-2&quot;,&quot;number-of-pages&quot;:&quot;178&quot;,&quot;publisher&quot;:&quot;Eerdmans
; Society for Prommoting Christian
Knowledge&quot;,&quot;publisher-place&quot;:&quot;Grand Rapids, Mich. :
London&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Pure kingdom: Jesus' vision of
God&quot;,&quot;title-short&quot;:&quot;Pure
kingdom&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Chilton&quot;,&quot;given&quot;:&quot;Bruce&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1996&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Bruce
Chilton, <i>Pure Kingdom: Jesus’ Vision of God</i>, Studying the Historical
Jesus (Grand Rapids, Mich. : London: Eerdmans ; Society for Prommoting
Christian Knowledge, 1996).<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--> Pg. 24<o:p></o:p></p>

</div>

<div id="ftn3">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref3" name="_ftn3" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[3]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;gBlUe0ny&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;S.R.
Driver, \\uc0\\u8220{}CHAP. 2. NEBUCHADNEZZAR\\uc0\\u8217{}S
DREAM,\\uc0\\u8221{} in {\\i{}Cambridge Bible for Schools and Colleges}, Daniel
(Cambridge University Press, 1900), https://biblehub.com/commentaries/cambridge/.&quot;,&quot;plainCitation&quot;:&quot;S.R.
Driver, “CHAP. 2. NEBUCHADNEZZAR’S DREAM,” in Cambridge Bible for Schools and
Colleges, Daniel (Cambridge University Press, 1900),
https://biblehub.com/commentaries/cambridge/.&quot;,&quot;noteIndex&quot;:6},&quot;citationItems&quot;:[{&quot;id&quot;:530,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/JTLIVJ8C&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/JTLIVJ8C&quot;],&quot;itemData&quot;:{&quot;id&quot;:530,&quot;type&quot;:&quot;chapter&quot;,&quot;collection-title&quot;:&quot;Daniel&quot;,&quot;container-title&quot;:&quot;Cambridge
Bible for Schools and Colleges&quot;,&quot;publisher&quot;:&quot;Cambridge
University Press&quot;,&quot;title&quot;:&quot;CHAP. 2. NEBUCHADNEZZAR’S
DREAM&quot;,&quot;URL&quot;:&quot;https://biblehub.com/commentaries/cambridge/&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Driver&quot;,&quot;given&quot;:&quot;S.R.&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,28]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1900&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->S.R.
Driver, “CHAP. 2. NEBUCHADNEZZAR’S DREAM,” in <i>Cambridge Bible for Schools
and Colleges</i>, Daniel (Cambridge University Press, 1900),
https://biblehub.com/commentaries/cambridge/.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn4">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref4" name="_ftn4" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[4]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;eU5TBSio&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Chilton,
{\\i{}Pure Kingdom}.&quot;,&quot;plainCitation&quot;:&quot;Chilton, Pure
Kingdom.&quot;,&quot;noteIndex&quot;:4},&quot;citationItems&quot;:[{&quot;id&quot;:415,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/DFZRZQ67&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/DFZRZQ67&quot;],&quot;itemData&quot;:{&quot;id&quot;:415,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS2417.K5
C49 1996&quot;,&quot;collection-title&quot;:&quot;Studying the historical
Jesus&quot;,&quot;event-place&quot;:&quot;Grand Rapids, Mich. :
London&quot;,&quot;ISBN&quot;:&quot;978-0-8028-4187-2&quot;,&quot;number-of-pages&quot;:&quot;178&quot;,&quot;publisher&quot;:&quot;Eerdmans
; Society for Prommoting Christian
Knowledge&quot;,&quot;publisher-place&quot;:&quot;Grand Rapids, Mich. :
London&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Pure kingdom: Jesus' vision of
God&quot;,&quot;title-short&quot;:&quot;Pure
kingdom&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Chilton&quot;,&quot;given&quot;:&quot;Bruce&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1996&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Chilton,
<i>Pure Kingdom</i>.<!--[if supportFields]><span style='mso-element:
field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn5">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref5" name="_ftn5" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[5]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION {&quot;citationID&quot;:&quot;RNZJXqgH&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;\\uc0\\u8220{}The
Decree of Darius (Ezra 5:3-6:13) July 26-27,\\uc0\\u8221{} in {\\i{}Beyond
Today Bible Commentary by United Church of God}, accessed November 28, 2020,
https://bible.ucg.org/bible-commentary/Ezra/Tattenai's-inquiry-regarding-the-temple-reconstruction-and-the-decree-of-Darius/.&quot;,&quot;plainCitation&quot;:&quot;“The
Decree of Darius (Ezra 5:3-6:13) July 26-27,” in Beyond Today Bible Commentary
by United Church of God, accessed November 28, 2020, https://bible.ucg.org/bible-commentary/Ezra/Tattenai's-inquiry-regarding-the-temple-reconstruction-and-the-decree-of-Darius/.&quot;,&quot;noteIndex&quot;:4},&quot;citationItems&quot;:[{&quot;id&quot;:528,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/IS6FR8S6&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/IS6FR8S6&quot;],&quot;itemData&quot;:{&quot;id&quot;:528,&quot;type&quot;:&quot;chapter&quot;,&quot;container-title&quot;:&quot;Beyond
Today Bible Commentary by United Church of
God&quot;,&quot;title&quot;:&quot;The Decree of Darius (Ezra 5:3-6:13) July
26-27&quot;,&quot;URL&quot;:&quot;https://bible.ucg.org/bible-commentary/Ezra/Tattenai's-inquiry-regarding-the-temple-reconstruction-and-the-decree-of-Darius/&quot;,&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,28]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->“The
Decree of Darius (Ezra 5:3-6:13) July 26-27,” in <i>Beyond Today Bible
Commentary by United Church of God</i>, accessed November 28, 2020, https://bible.ucg.org/bible-commentary/Ezra/Tattenai's-inquiry-regarding-the-temple-reconstruction-and-the-decree-of-Darius/.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn6">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref6" name="_ftn6" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[6]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;yIER3tz7&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Richard
A. Horsley, {\\i{}Jesus and the Spiral of Violence: Popular Jewish Resistance
in Roman Palestine}, 1st ed (San Francisco: Harper &amp; Row, 1987),
https://archive.org/stream/jesusspiralofv00hors.&quot;,&quot;plainCitation&quot;:&quot;Richard
A. Horsley, Jesus and the Spiral of Violence: Popular Jewish Resistance in
Roman Palestine, 1st ed (San Francisco: Harper &amp; Row, 1987),
https://archive.org/stream/jesusspiralofv00hors.&quot;,&quot;noteIndex&quot;:6},&quot;citationItems&quot;:[{&quot;id&quot;:413,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/L2BFIE4U&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/L2BFIE4U&quot;],&quot;itemData&quot;:{&quot;id&quot;:413,&quot;type&quot;:&quot;book&quot;,&quot;archive&quot;:&quot;Archive.org&quot;,&quot;call-number&quot;:&quot;BS2417.P6
H67 1987&quot;,&quot;edition&quot;:&quot;1st ed&quot;,&quot;event-place&quot;:&quot;San
Francisco&quot;,&quot;ISBN&quot;:&quot;978-0-06-254448-3&quot;,&quot;number-of-pages&quot;:&quot;355&quot;,&quot;publisher&quot;:&quot;Harper
&amp; Row&quot;,&quot;publisher-place&quot;:&quot;San
Francisco&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Jesus and the Spiral of Violence: Popular
Jewish Resistance in Roman Palestine&quot;,&quot;title-short&quot;:&quot;Jesus
and the spiral of
violence&quot;,&quot;URL&quot;:&quot;https://archive.org/stream/jesusspiralofv00hors&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Horsley&quot;,&quot;given&quot;:&quot;Richard
A.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1987&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Richard
A. Horsley, <i>Jesus and the Spiral of Violence: Popular Jewish Resistance in
Roman Palestine</i>, 1st ed (San Francisco: Harper &amp; Row, 1987),
https://archive.org/stream/jesusspiralofv00hors.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--> Chapter 1 – See also the
apocryphal books of 1 and 2 Maccabees.<o:p></o:p></p>

</div>

<div id="ftn7">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref7" name="_ftn7" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[7]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;EZy67gZr&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Jonathan
Welton, {\\i{}Raptureless}, 3rd Edition Printing (Place of publication not
identified: Bookbaby, 2015),
http://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=4188734.&quot;,&quot;plainCitation&quot;:&quot;Jonathan
Welton, Raptureless, 3rd Edition Printing (Place of publication not identified:
Bookbaby, 2015),
http://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=4188734.&quot;,&quot;noteIndex&quot;:7},&quot;citationItems&quot;:[{&quot;id&quot;:520,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/UBMET87P&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/UBMET87P&quot;],&quot;itemData&quot;:{&quot;id&quot;:520,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;Raptureless
is a scholarly approach to reinterpreting Matthew 24 and \&quot;end
times\&quot; eschatology.&quot;,&quot;edition&quot;:&quot;3rd Edition
Printing&quot;,&quot;event-place&quot;:&quot;Place of publication not
identified&quot;,&quot;ISBN&quot;:&quot;978-1-68222-669-8&quot;,&quot;language&quot;:&quot;English&quot;,&quot;note&quot;:&quot;OCLC:
933450766&quot;,&quot;publisher&quot;:&quot;Bookbaby&quot;,&quot;publisher-place&quot;:&quot;Place
of publication not identified&quot;,&quot;source&quot;:&quot;Open
WorldCat&quot;,&quot;title&quot;:&quot;Raptureless&quot;,&quot;title-short&quot;:&quot;Raptureless&quot;,&quot;URL&quot;:&quot;http://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=4188734&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Welton&quot;,&quot;given&quot;:&quot;Jonathan&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,27]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2015&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Jonathan
Welton, <i>Raptureless</i>, 3rd Edition Printing (Place of publication not
identified: Bookbaby, 2015),
http://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=4188734.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn8">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref8" name="_ftn8" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[8]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;6akeDbQJ&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Richard
Bauckham, {\\i{}Jesus: A Very Short Introduction}, Very Short Introductions 275
(Oxford: New York\\uc0\\u8239{}: Oxford Univ Press,
2011).&quot;,&quot;plainCitation&quot;:&quot;Richard Bauckham, Jesus: A Very
Short Introduction, Very Short Introductions 275 (Oxford: New York : Oxford
Univ Press,
2011).&quot;,&quot;noteIndex&quot;:8},&quot;citationItems&quot;:[{&quot;id&quot;:181,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/347PFS56&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/347PFS56&quot;],&quot;itemData&quot;:{&quot;id&quot;:181,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BT203
.B38
2011&quot;,&quot;collection-number&quot;:&quot;275&quot;,&quot;collection-title&quot;:&quot;Very
short introductions&quot;,&quot;event-place&quot;:&quot;Oxford&quot;,&quot;ISBN&quot;:&quot;978-0-19-957527-5&quot;,&quot;number-of-pages&quot;:&quot;125&quot;,&quot;publisher&quot;:&quot;New
York : Oxford Univ
Press&quot;,&quot;publisher-place&quot;:&quot;Oxford&quot;,&quot;source&quot;:&quot;Library
of Congress ISBN&quot;,&quot;title&quot;:&quot;Jesus: A Very Short
Introduction&quot;,&quot;title-short&quot;:&quot;Jesus&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Bauckham&quot;,&quot;given&quot;:&quot;Richard&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2011&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Richard
Bauckham, <i>Jesus: A Very Short Introduction</i>, Very Short Introductions 275
(Oxford: New York : Oxford Univ Press, 2011).<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--> Pg. 20<o:p></o:p></p>

</div>

<div id="ftn9">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref9" name="_ftn9" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[9]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;dOTHRseC&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Horsley,
{\\i{}Jesus and the Spiral of Violence}.&quot;,&quot;plainCitation&quot;:&quot;Horsley,
Jesus and the Spiral of
Violence.&quot;,&quot;noteIndex&quot;:10},&quot;citationItems&quot;:[{&quot;id&quot;:413,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/L2BFIE4U&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/L2BFIE4U&quot;],&quot;itemData&quot;:{&quot;id&quot;:413,&quot;type&quot;:&quot;book&quot;,&quot;archive&quot;:&quot;Archive.org&quot;,&quot;call-number&quot;:&quot;BS2417.P6
H67 1987&quot;,&quot;edition&quot;:&quot;1st
ed&quot;,&quot;event-place&quot;:&quot;San Francisco&quot;,&quot;ISBN&quot;:&quot;978-0-06-254448-3&quot;,&quot;number-of-pages&quot;:&quot;355&quot;,&quot;publisher&quot;:&quot;Harper
&amp; Row&quot;,&quot;publisher-place&quot;:&quot;San
Francisco&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Jesus and the Spiral of Violence: Popular
Jewish Resistance in Roman Palestine&quot;,&quot;title-short&quot;:&quot;Jesus
and the spiral of
violence&quot;,&quot;URL&quot;:&quot;https://archive.org/stream/jesusspiralofv00hors&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Horsley&quot;,&quot;given&quot;:&quot;Richard
A.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1987&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Horsley,
<i>Jesus and the Spiral of Violence</i>.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn10">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref10" name="_ftn10" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[10]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;6akeDbQJ&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Richard
Bauckham, {\\i{}Jesus: A Very Short Introduction}, Very Short Introductions 275
(Oxford: New York\\uc0\\u8239{}: Oxford Univ Press,
2011).&quot;,&quot;plainCitation&quot;:&quot;Richard Bauckham, Jesus: A Very
Short Introduction, Very Short Introductions 275 (Oxford: New York : Oxford
Univ Press,
2011).&quot;,&quot;noteIndex&quot;:8},&quot;citationItems&quot;:[{&quot;id&quot;:181,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/347PFS56&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/347PFS56&quot;],&quot;itemData&quot;:{&quot;id&quot;:181,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BT203
.B38
2011&quot;,&quot;collection-number&quot;:&quot;275&quot;,&quot;collection-title&quot;:&quot;Very
short introductions&quot;,&quot;event-place&quot;:&quot;Oxford&quot;,&quot;ISBN&quot;:&quot;978-0-19-957527-5&quot;,&quot;number-of-pages&quot;:&quot;125&quot;,&quot;publisher&quot;:&quot;New
York : Oxford Univ
Press&quot;,&quot;publisher-place&quot;:&quot;Oxford&quot;,&quot;source&quot;:&quot;Library
of Congress ISBN&quot;,&quot;title&quot;:&quot;Jesus: A Very Short
Introduction&quot;,&quot;title-short&quot;:&quot;Jesus&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Bauckham&quot;,&quot;given&quot;:&quot;Richard&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2011&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Richard
Bauckham, <i>Jesus: A Very Short Introduction</i>, Very Short Introductions 275
(Oxford: New York : Oxford Univ Press, 2011).<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--> Pg. 20<o:p></o:p></p>

</div>

<div id="ftn11">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref11" name="_ftn11" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[11]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION {&quot;citationID&quot;:&quot;kujBzsB3&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Nicholas
Perrin, Jeannine K. Brown, and Joel B. Green, {\\i{}Dictionary of Jesus and the
Gospels (DJG)}, IVP Bible Dictionary Series, K is for Kingdom; Judaism, Common
(Downers Grove, Ill: IVP Academic, 2013),
http://search.ebscohost.com/login.aspx?direct=true&amp;db=nlebk&amp;AN=633424&amp;site=ehost-live.&quot;,&quot;plainCitation&quot;:&quot;Nicholas
Perrin, Jeannine K. Brown, and Joel B. Green, Dictionary of Jesus and the
Gospels (DJG), IVP Bible Dictionary Series, K is for Kingdom; Judaism, Common
(Downers Grove, Ill: IVP Academic, 2013),
http://search.ebscohost.com/login.aspx?direct=true&amp;db=nlebk&amp;AN=633424&amp;site=ehost-live.&quot;,&quot;noteIndex&quot;:9},&quot;citationItems&quot;:[{&quot;id&quot;:472,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/VV9Y4R2F&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/VV9Y4R2F&quot;],&quot;itemData&quot;:{&quot;id&quot;:472,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;1993
ECPA Gold Medallion (Reference Text) 1993 Christianity Today Critics'Choice
Award The 2014 ECPA Christian Book Award Winner (Bible Reference) 2014 Readers'Choice
Award Winner Preaching's Preacher's Guide to the Best Bible Reference for 2014
(Gospels and Jesus) The second edition of the Dictionary of Jesus and the
Gospels is a thoroughly reconstructed and revised version of the critically
acclaimed 1992 first edition. Since that groundbreaking volume was published, a
wave of Jesus and Gospel scholarship has crested and broken on the shores of a
new century. Jesus has been proposed as sage, shaman, revolutionary, marginal
Jew, Mediterranean peasant or a prophet of Israel's restoration. The
non-canonical Gospels have been touted, examined and reassessed. There are
revised understandings of historiography, orality, form criticism, empire and
more. The second edition of the DJG amply weighs and assess the gains and
shortcomings of this new scholarship. Here is a self-contained reference
library of information and perspective essential to exploring Jesus and the
Gospels. This volume bridges the gap between scholars and those pastors,
teachers, students and interested readers who want thorough treatments of key
topics in an accessible and summary format. Articles cover each Gospel, major
themes in the Gospels, key episodes in the life of Jesus, significant
background topics, as well as issues and methods of interpretation. Among other
benefits, it allows multiple opportunities for each of the Gospels to be
weighed and heard in its own voice. Bibliographies are full and up to date,
putting readers in touch with the best work in the field. All of this allows
the articles to serve as launching pads for further research. When the first
edition of the Dictionary of Jesus and the Gospels was published, it was
immediately recognized as an innovative reference work. By taking a particular
corpus of biblical books and exploring it with in-depth articles written by
specialists in the field, it refashioned a staple reference genre. This
dictionary model has now been applied to each segment of the biblical canon in
successive volumes. Those who have enjoyed and benefitted from the wealth in
the first edition will find the second edition an equally indispensable
companion to study and research. Over ninety percent of the articles have been
completely rewritten, and the rest thoroughly revised and updated. Here is the
doorway into a reliable and comprehensive summary and appraisal of the last
twenty years of Jesus scholarship. A new generation of scholars has opened the
way to make this a Dictionary of Jesus and the Gospels for the twenty-first
century.&quot;,&quot;collection-number&quot;:&quot;K is for Kingdom; Judaism,
Common&quot;,&quot;collection-title&quot;:&quot;IVP Bible Dictionary
Series&quot;,&quot;event-place&quot;:&quot;Downers Grove,
Ill&quot;,&quot;ISBN&quot;:&quot;978-0-8308-2456-4&quot;,&quot;language&quot;:&quot;English&quot;,&quot;publisher&quot;:&quot;IVP
Academic&quot;,&quot;publisher-place&quot;:&quot;Downers Grove,
Ill&quot;,&quot;source&quot;:&quot;EBSCOhost&quot;,&quot;title&quot;:&quot;Dictionary
of Jesus and the Gospels
(DJG)&quot;,&quot;title-short&quot;:&quot;DJG&quot;,&quot;URL&quot;:&quot;http://search.ebscohost.com/login.aspx?direct=true&amp;db=nlebk&amp;AN=633424&amp;site=ehost-live&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Perrin&quot;,&quot;given&quot;:&quot;Nicholas&quot;},{&quot;family&quot;:&quot;Brown&quot;,&quot;given&quot;:&quot;Jeannine
K.&quot;},{&quot;family&quot;:&quot;Green&quot;,&quot;given&quot;:&quot;Joel
B.&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,23]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2013&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Nicholas
Perrin, Jeannine K. Brown, and Joel B. Green, <i>Dictionary of Jesus and the
Gospels (DJG)</i>, IVP Bible Dictionary Series, K is for Kingdom; Judaism,
Common (Downers Grove, Ill: IVP Academic, 2013),
http://search.ebscohost.com/login.aspx?direct=true&amp;db=nlebk&amp;AN=633424&amp;site=ehost-live.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--> See: Judaism, Common 1.2.2<o:p></o:p></p>

</div>

<div id="ftn12">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref12" name="_ftn12" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[12]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;4L1OnVEZ&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Horsley.&quot;,&quot;plainCitation&quot;:&quot;Horsley.&quot;,&quot;noteIndex&quot;:11},&quot;citationItems&quot;:[{&quot;id&quot;:413,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/L2BFIE4U&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/L2BFIE4U&quot;],&quot;itemData&quot;:{&quot;id&quot;:413,&quot;type&quot;:&quot;book&quot;,&quot;archive&quot;:&quot;Archive.org&quot;,&quot;call-number&quot;:&quot;BS2417.P6
H67 1987&quot;,&quot;edition&quot;:&quot;1st ed&quot;,&quot;event-place&quot;:&quot;San
Francisco&quot;,&quot;ISBN&quot;:&quot;978-0-06-254448-3&quot;,&quot;number-of-pages&quot;:&quot;355&quot;,&quot;publisher&quot;:&quot;Harper
&amp; Row&quot;,&quot;publisher-place&quot;:&quot;San
Francisco&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Jesus and the Spiral of Violence: Popular
Jewish Resistance in Roman Palestine&quot;,&quot;title-short&quot;:&quot;Jesus
and the spiral of
violence&quot;,&quot;URL&quot;:&quot;https://archive.org/stream/jesusspiralofv00hors&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Horsley&quot;,&quot;given&quot;:&quot;Richard
A.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1987&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Horsley.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--> Pg. 11<o:p></o:p></p>

</div>

<div id="ftn13">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref13" name="_ftn13" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[13]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION {&quot;citationID&quot;:&quot;aJxMV061&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Benjamin
Uffenheimer, Yair Hoffman, and Henning Reventlow, {\\i{}Politics and
Theopolitics in the Bible and Postbiblical Literature}, Journal for the Study
of the Old Testament. Supplement Series (Sheffield, England: Sheffield Academic
Press, 1994),
http://search.ebscohost.com/login.aspx?direct=true&amp;db=nlebk&amp;AN=243970&amp;site=ehost-live.&quot;,&quot;plainCitation&quot;:&quot;Benjamin
Uffenheimer, Yair Hoffman, and Henning Reventlow, Politics and Theopolitics in
the Bible and Postbiblical Literature, Journal for the Study of the Old
Testament. Supplement Series (Sheffield, England: Sheffield Academic Press,
1994),
http://search.ebscohost.com/login.aspx?direct=true&amp;db=nlebk&amp;AN=243970&amp;site=ehost-live.&quot;,&quot;noteIndex&quot;:12},&quot;citationItems&quot;:[{&quot;id&quot;:425,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/2A8SXZS2&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/2A8SXZS2&quot;],&quot;itemData&quot;:{&quot;id&quot;:425,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;This
volume contains papers from the third symposium held by the University of Tel
Aviv, Israel, and the Ruhr University, Bochum, Germany, with the aim of
furthering dialogue between Jewish and Christian biblical scholars. The papers
examine the ways in which political issues and events are reflected in the
Bible and in the postbiblical literature, the term'theopolitics'expressing the
conviction of both communities that the politics of human life have always been
and continue to be subject to the rule and providence of God. The hope of the
symposium is that through examination of the ways in which Jews and Christians
have reflected upon political and ethical theories there may arise new
possibilities for better mutual
understanding.&quot;,&quot;collection-title&quot;:&quot;Journal for the Study
of the Old Testament. Supplement Series&quot;,&quot;event-place&quot;:&quot;Sheffield,
England&quot;,&quot;ISBN&quot;:&quot;978-1-85075-461-9&quot;,&quot;language&quot;:&quot;English&quot;,&quot;note&quot;:&quot;issue:
Vol. 171&quot;,&quot;publisher&quot;:&quot;Sheffield Academic
Press&quot;,&quot;publisher-place&quot;:&quot;Sheffield,
England&quot;,&quot;source&quot;:&quot;EBSCOhost&quot;,&quot;title&quot;:&quot;Politics
and Theopolitics in the Bible and Postbiblical Literature&quot;,&quot;URL&quot;:&quot;http://search.ebscohost.com/login.aspx?direct=true&amp;db=nlebk&amp;AN=243970&amp;site=ehost-live&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Uffenheimer&quot;,&quot;given&quot;:&quot;Benjamin&quot;},{&quot;family&quot;:&quot;Hoffman&quot;,&quot;given&quot;:&quot;Yair&quot;},{&quot;family&quot;:&quot;Reventlow&quot;,&quot;given&quot;:&quot;Henning&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,19]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1994&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Benjamin
Uffenheimer, Yair Hoffman, and Henning Reventlow, <i>Politics and Theopolitics
in the Bible and Postbiblical Literature</i>, Journal for the Study of the Old
Testament. Supplement Series (Sheffield, England: Sheffield Academic Press,
1994),
http://search.ebscohost.com/login.aspx?direct=true&amp;db=nlebk&amp;AN=243970&amp;site=ehost-live.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn14">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref14" name="_ftn14" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[14]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;pbMkjIMr&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Bauckham,
{\\i{}Jesus}.&quot;,&quot;plainCitation&quot;:&quot;Bauckham,
Jesus.&quot;,&quot;noteIndex&quot;:13},&quot;citationItems&quot;:[{&quot;id&quot;:181,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/347PFS56&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/347PFS56&quot;],&quot;itemData&quot;:{&quot;id&quot;:181,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BT203
.B38
2011&quot;,&quot;collection-number&quot;:&quot;275&quot;,&quot;collection-title&quot;:&quot;Very
short introductions&quot;,&quot;event-place&quot;:&quot;Oxford&quot;,&quot;ISBN&quot;:&quot;978-0-19-957527-5&quot;,&quot;number-of-pages&quot;:&quot;125&quot;,&quot;publisher&quot;:&quot;New
York : Oxford Univ
Press&quot;,&quot;publisher-place&quot;:&quot;Oxford&quot;,&quot;source&quot;:&quot;Library
of Congress ISBN&quot;,&quot;title&quot;:&quot;Jesus: A Very Short
Introduction&quot;,&quot;title-short&quot;:&quot;Jesus&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Bauckham&quot;,&quot;given&quot;:&quot;Richard&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2011&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Bauckham,
<i>Jesus</i>.<!--[if supportFields]><span style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn15">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref15" name="_ftn15" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[15]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;V9xxLnzi&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Horsley,
{\\i{}Jesus and the Spiral of Violence}.&quot;,&quot;plainCitation&quot;:&quot;Horsley,
Jesus and the Spiral of
Violence.&quot;,&quot;noteIndex&quot;:14},&quot;citationItems&quot;:[{&quot;id&quot;:413,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/L2BFIE4U&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/L2BFIE4U&quot;],&quot;itemData&quot;:{&quot;id&quot;:413,&quot;type&quot;:&quot;book&quot;,&quot;archive&quot;:&quot;Archive.org&quot;,&quot;call-number&quot;:&quot;BS2417.P6
H67 1987&quot;,&quot;edition&quot;:&quot;1st
ed&quot;,&quot;event-place&quot;:&quot;San
Francisco&quot;,&quot;ISBN&quot;:&quot;978-0-06-254448-3&quot;,&quot;number-of-pages&quot;:&quot;355&quot;,&quot;publisher&quot;:&quot;Harper
&amp; Row&quot;,&quot;publisher-place&quot;:&quot;San
Francisco&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Jesus and the Spiral of Violence: Popular
Jewish Resistance in Roman Palestine&quot;,&quot;title-short&quot;:&quot;Jesus
and the spiral of
violence&quot;,&quot;URL&quot;:&quot;https://archive.org/stream/jesusspiralofv00hors&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Horsley&quot;,&quot;given&quot;:&quot;Richard
A.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1987&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Horsley,
<i>Jesus and the Spiral of Violence</i>.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn16">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref16" name="_ftn16" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[16]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;DsVSO0G7&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Bauckham,
{\\i{}Jesus}.&quot;,&quot;plainCitation&quot;:&quot;Bauckham, Jesus.&quot;,&quot;noteIndex&quot;:15},&quot;citationItems&quot;:[{&quot;id&quot;:181,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/347PFS56&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/347PFS56&quot;],&quot;itemData&quot;:{&quot;id&quot;:181,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BT203
.B38 2011&quot;,&quot;collection-number&quot;:&quot;275&quot;,&quot;collection-title&quot;:&quot;Very
short
introductions&quot;,&quot;event-place&quot;:&quot;Oxford&quot;,&quot;ISBN&quot;:&quot;978-0-19-957527-5&quot;,&quot;number-of-pages&quot;:&quot;125&quot;,&quot;publisher&quot;:&quot;New
York : Oxford Univ
Press&quot;,&quot;publisher-place&quot;:&quot;Oxford&quot;,&quot;source&quot;:&quot;Library
of Congress ISBN&quot;,&quot;title&quot;:&quot;Jesus: A Very Short
Introduction&quot;,&quot;title-short&quot;:&quot;Jesus&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Bauckham&quot;,&quot;given&quot;:&quot;Richard&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2011&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Bauckham,
<i>Jesus</i>.<!--[if supportFields]><span style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn17">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref17" name="_ftn17" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[17]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;7BCSLr1z&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Bauckham,
{\\i{}Jesus}.&quot;,&quot;plainCitation&quot;:&quot;Bauckham,
Jesus.&quot;,&quot;noteIndex&quot;:23},&quot;citationItems&quot;:[{&quot;id&quot;:181,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/347PFS56&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/347PFS56&quot;],&quot;itemData&quot;:{&quot;id&quot;:181,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BT203
.B38 2011&quot;,&quot;collection-number&quot;:&quot;275&quot;,&quot;collection-title&quot;:&quot;Very
short
introductions&quot;,&quot;event-place&quot;:&quot;Oxford&quot;,&quot;ISBN&quot;:&quot;978-0-19-957527-5&quot;,&quot;number-of-pages&quot;:&quot;125&quot;,&quot;publisher&quot;:&quot;New
York : Oxford Univ
Press&quot;,&quot;publisher-place&quot;:&quot;Oxford&quot;,&quot;source&quot;:&quot;Library
of Congress ISBN&quot;,&quot;title&quot;:&quot;Jesus: A Very Short
Introduction&quot;,&quot;title-short&quot;:&quot;Jesus&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Bauckham&quot;,&quot;given&quot;:&quot;Richard&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2011&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Bauckham,
<i>Jesus</i>.<!--[if supportFields]><span style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn18">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref18" name="_ftn18" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[18]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;Hw8A4AEL&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Bauckham.&quot;,&quot;plainCitation&quot;:&quot;Bauckham.&quot;,&quot;noteIndex&quot;:16},&quot;citationItems&quot;:[{&quot;id&quot;:181,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/347PFS56&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/347PFS56&quot;],&quot;itemData&quot;:{&quot;id&quot;:181,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BT203
.B38
2011&quot;,&quot;collection-number&quot;:&quot;275&quot;,&quot;collection-title&quot;:&quot;Very
short
introductions&quot;,&quot;event-place&quot;:&quot;Oxford&quot;,&quot;ISBN&quot;:&quot;978-0-19-957527-5&quot;,&quot;number-of-pages&quot;:&quot;125&quot;,&quot;publisher&quot;:&quot;New
York : Oxford Univ
Press&quot;,&quot;publisher-place&quot;:&quot;Oxford&quot;,&quot;source&quot;:&quot;Library
of Congress ISBN&quot;,&quot;title&quot;:&quot;Jesus: A Very Short
Introduction&quot;,&quot;title-short&quot;:&quot;Jesus&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Bauckham&quot;,&quot;given&quot;:&quot;Richard&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2011&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Bauckham.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn19">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref19" name="_ftn19" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[19]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;Ojg8EQBY&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;F.W.
Farrar, \\uc0\\u8220{}Luke 20,\\uc0\\u8221{} in {\\i{}Cambridge Bible for
Schools and Colleges} (Cambridge University Press, 1891), 20,
https://biblehub.com/commentaries/cambridge/luke/20.htm.&quot;,&quot;plainCitation&quot;:&quot;F.W.
Farrar, “Luke 20,” in Cambridge Bible for Schools and Colleges (Cambridge University
Press, 1891), 20,
https://biblehub.com/commentaries/cambridge/luke/20.htm.&quot;,&quot;noteIndex&quot;:17},&quot;citationItems&quot;:[{&quot;id&quot;:536,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/XWVMA4Z8&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/XWVMA4Z8&quot;],&quot;itemData&quot;:{&quot;id&quot;:536,&quot;type&quot;:&quot;chapter&quot;,&quot;container-title&quot;:&quot;Cambridge
Bible for Schools and Colleges&quot;,&quot;publisher&quot;:&quot;Cambridge
University Press&quot;,&quot;title&quot;:&quot;Luke
20&quot;,&quot;URL&quot;:&quot;https://biblehub.com/commentaries/cambridge/luke/20.htm&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Farrar&quot;,&quot;given&quot;:&quot;F.W.&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,29]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1891&quot;]]}},&quot;locator&quot;:&quot;20&quot;}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->F.W.
Farrar, “Luke 20,” in <i>Cambridge Bible for Schools and Colleges</i>
(Cambridge University Press, 1891), 20,
https://biblehub.com/commentaries/cambridge/luke/20.htm.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn20">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref20" name="_ftn20" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[20]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;8eO7lytU&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Daniel
J. Harrington, {\\i{}The Synoptic Gospels Set Free: Preaching Without Anti-Judaism}
(New York\\uc0\\u8239{}; Mahwah, NJ: Paulist Press,
2009).&quot;,&quot;plainCitation&quot;:&quot;Daniel J. Harrington, The Synoptic
Gospels Set Free: Preaching Without Anti-Judaism (New York ; Mahwah, NJ:
Paulist Press, 2009).&quot;,&quot;noteIndex&quot;:3},&quot;citationItems&quot;:[{&quot;id&quot;:184,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/CXCYLEBF&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/CXCYLEBF&quot;],&quot;itemData&quot;:{&quot;id&quot;:184,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BS2555.52
.H325 2009&quot;,&quot;event-place&quot;:&quot;New York ; Mahwah,
NJ&quot;,&quot;ISBN&quot;:&quot;978-0-8091-4583-6&quot;,&quot;number-of-pages&quot;:&quot;231&quot;,&quot;publisher&quot;:&quot;Paulist
Press&quot;,&quot;publisher-place&quot;:&quot;New York ; Mahwah,
NJ&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;The Synoptic Gospels Set Free: Preaching
Without Anti-Judaism&quot;,&quot;title-short&quot;:&quot;The Synoptic Gospels
set free&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Harrington&quot;,&quot;given&quot;:&quot;Daniel
J.&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2009&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Daniel
J. Harrington, <i>The Synoptic Gospels Set Free: Preaching Without Anti-Judaism</i>
(New York ; Mahwah, NJ: Paulist Press, 2009).<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn21">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref21" name="_ftn21" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[21]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;4IqV5jQj&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;{\\i{}The
New English Bible (NEB) New Testament 1961}, vol. Library Copy-Inherited from
First Christian Church, Norwalk CA (Oxford University Press, Cambridge
University Press, 1961),
https://en.wikipedia.org/wiki/New_English_Bible.&quot;,&quot;plainCitation&quot;:&quot;The
New English Bible (NEB) New Testament 1961, vol. Library Copy-Inherited from
First Christian Church, Norwalk CA (Oxford University Press, Cambridge
University Press, 1961),
https://en.wikipedia.org/wiki/New_English_Bible.&quot;,&quot;noteIndex&quot;:2},&quot;citationItems&quot;:[{&quot;id&quot;:459,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/FH6D6XDY&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/FH6D6XDY&quot;],&quot;itemData&quot;:{&quot;id&quot;:459,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;The
New English Bible (NEB) is an English translation of the Bible. The New
Testament was published in 1961 and the Old Testament (with the Apocrypha) was
published on 16 March 1970.[1] In 1989, it was significantly revised and
republished as the Revised English Bible.\n\nNear the time when the copyright
to the English Revised Version was due to expire (1935), the Oxford University
Press (OUP), and the Cambridge University Press (CUP), who were the current
English Revised Version copyright holders, began investigations to determine
whether a modern revision of the English Revised Version text was necessary. In
May 1946 G.S. Hendry, along with the Presbytery of Stirling and Dunblane
produced a notice, which was presented to the General Assembly of the Church of
Scotland, indicating that the work of translating should be undertaken in order
to produce a Bible with thoroughly \&quot;modern English.\&quot; After the work
of delegation was finished, a general conference was held in October 1946 where
it was determined that a completely fresh translation should be undertaken
rather than a revision as originally suggested by the University Presses of
Oxford and Cambridge.&quot;,&quot;archive&quot;:&quot;https://www.cambridge.org/core/journals/new-testament-studies/article/new-english-bible-new-testament-library-edition-pp-xiii-447-21s-popular-edition-pp-x-432-8s-6d-oxford-university-press-london-cambridge-university-press-1961/B21271C1DDB453F0DFC6C9480E4B6A8F&quot;,&quot;ISBN&quot;:&quot;UNKNOWN
OR N/A&quot;,&quot;language&quot;:&quot;Englsih&quot;,&quot;number-of-pages&quot;:&quot;447&quot;,&quot;publisher&quot;:&quot;Oxford
University Press, Cambridge University Press&quot;,&quot;title&quot;:&quot;The
New English Bible (NEB) New Testament 1961&quot;,&quot;title-short&quot;:&quot;New
English Bible
(NEB)&quot;,&quot;URL&quot;:&quot;https://en.wikipedia.org/wiki/New_English_Bible&quot;,&quot;volume&quot;:&quot;Library
Copy - Inherited from First Christian Church, Norwalk
CA&quot;,&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1961&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]--><i>The
New English Bible (NEB) New Testament 1961</i>, vol. Library Copy-Inherited
from First Christian Church, Norwalk CA (Oxford University Press, Cambridge
University Press, 1961), https://en.wikipedia.org/wiki/New_English_Bible.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--> [added for understanding]<o:p></o:p></p>

</div>

<div id="ftn22">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref22" name="_ftn22" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[22]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;ok2l1riI&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;John
Howard Yoder, {\\i{}The Politics of Jesus: Vicit Agnus Noster}, 2nd ed (Grand
Rapids, Mich.\\uc0\\u8239{}: Carlisle, UK: Eerdmans\\uc0\\u8239{}; Paternoster
Press, 1994).&quot;,&quot;plainCitation&quot;:&quot;John Howard Yoder, The
Politics of Jesus: Vicit Agnus Noster, 2nd ed (Grand Rapids, Mich. : Carlisle,
UK: Eerdmans ; Paternoster Press,
1994).&quot;,&quot;noteIndex&quot;:21},&quot;citationItems&quot;:[{&quot;id&quot;:416,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/TV9X9LE8&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/TV9X9LE8&quot;],&quot;itemData&quot;:{&quot;id&quot;:416,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BT202
.Y63 1994&quot;,&quot;edition&quot;:&quot;2nd
ed&quot;,&quot;event-place&quot;:&quot;Grand Rapids, Mich. : Carlisle,
UK&quot;,&quot;ISBN&quot;:&quot;978-0-8028-0734-2&quot;,&quot;number-of-pages&quot;:&quot;257&quot;,&quot;publisher&quot;:&quot;Eerdmans
; Paternoster Press&quot;,&quot;publisher-place&quot;:&quot;Grand Rapids, Mich.
: Carlisle, UK&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;The politics of Jesus: vicit Agnus
noster&quot;,&quot;title-short&quot;:&quot;The politics of
Jesus&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Yoder&quot;,&quot;given&quot;:&quot;John
Howard&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1994&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->John
Howard Yoder, <i>The Politics of Jesus: Vicit Agnus Noster</i>, 2nd ed (Grand
Rapids, Mich. : Carlisle, UK: Eerdmans ; Paternoster Press, 1994).<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--> Pg. 43-44<o:p></o:p></p>

</div>

<div id="ftn23">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref23" name="_ftn23" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[23]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;0tI77KOj&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Yoder.&quot;,&quot;plainCitation&quot;:&quot;Yoder.&quot;,&quot;noteIndex&quot;:22},&quot;citationItems&quot;:[{&quot;id&quot;:416,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/TV9X9LE8&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/TV9X9LE8&quot;],&quot;itemData&quot;:{&quot;id&quot;:416,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BT202
.Y63 1994&quot;,&quot;edition&quot;:&quot;2nd
ed&quot;,&quot;event-place&quot;:&quot;Grand Rapids, Mich. : Carlisle,
UK&quot;,&quot;ISBN&quot;:&quot;978-0-8028-0734-2&quot;,&quot;number-of-pages&quot;:&quot;257&quot;,&quot;publisher&quot;:&quot;Eerdmans
; Paternoster Press&quot;,&quot;publisher-place&quot;:&quot;Grand Rapids, Mich.
: Carlisle, UK&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;The politics of Jesus: vicit Agnus
noster&quot;,&quot;title-short&quot;:&quot;The politics of
Jesus&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Yoder&quot;,&quot;given&quot;:&quot;John
Howard&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1994&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Yoder.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--> Pg. 44<o:p></o:p></p>

</div>

<div id="ftn24">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref24" name="_ftn24" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[24]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;u4LpXNPj&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Perrin,
Brown, and Green, {\\i{}DJG}.&quot;,&quot;plainCitation&quot;:&quot;Perrin,
Brown, and Green,
DJG.&quot;,&quot;noteIndex&quot;:23},&quot;citationItems&quot;:[{&quot;id&quot;:472,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/VV9Y4R2F&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/VV9Y4R2F&quot;],&quot;itemData&quot;:{&quot;id&quot;:472,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;1993
ECPA Gold Medallion (Reference Text) 1993 Christianity Today Critics'Choice
Award The 2014 ECPA Christian Book Award Winner (Bible Reference) 2014
Readers'Choice Award Winner Preaching's Preacher's Guide to the Best Bible Reference
for 2014 (Gospels and Jesus) The second edition of the Dictionary of Jesus and
the Gospels is a thoroughly reconstructed and revised version of the critically
acclaimed 1992 first edition. Since that groundbreaking volume was published, a
wave of Jesus and Gospel scholarship has crested and broken on the shores of a
new century. Jesus has been proposed as sage, shaman, revolutionary, marginal
Jew, Mediterranean peasant or a prophet of Israel's restoration. The
non-canonical Gospels have been touted, examined and reassessed. There are
revised understandings of historiography, orality, form criticism, empire and
more. The second edition of the DJG amply weighs and assess the gains and
shortcomings of this new scholarship. Here is a self-contained reference
library of information and perspective essential to exploring Jesus and the
Gospels. This volume bridges the gap between scholars and those pastors,
teachers, students and interested readers who want thorough treatments of key
topics in an accessible and summary format. Articles cover each Gospel, major
themes in the Gospels, key episodes in the life of Jesus, significant
background topics, as well as issues and methods of interpretation. Among other
benefits, it allows multiple opportunities for each of the Gospels to be
weighed and heard in its own voice. Bibliographies are full and up to date,
putting readers in touch with the best work in the field. All of this allows
the articles to serve as launching pads for further research. When the first
edition of the Dictionary of Jesus and the Gospels was published, it was
immediately recognized as an innovative reference work. By taking a particular
corpus of biblical books and exploring it with in-depth articles written by
specialists in the field, it refashioned a staple reference genre. This
dictionary model has now been applied to each segment of the biblical canon in
successive volumes. Those who have enjoyed and benefitted from the wealth in
the first edition will find the second edition an equally indispensable companion
to study and research. Over ninety percent of the articles have been completely
rewritten, and the rest thoroughly revised and updated. Here is the doorway
into a reliable and comprehensive summary and appraisal of the last twenty
years of Jesus scholarship. A new generation of scholars has opened the way to
make this a Dictionary of Jesus and the Gospels for the twenty-first
century.&quot;,&quot;collection-number&quot;:&quot;K is for Kingdom; Judaism,
Common&quot;,&quot;collection-title&quot;:&quot;IVP Bible Dictionary
Series&quot;,&quot;event-place&quot;:&quot;Downers Grove,
Ill&quot;,&quot;ISBN&quot;:&quot;978-0-8308-2456-4&quot;,&quot;language&quot;:&quot;English&quot;,&quot;publisher&quot;:&quot;IVP
Academic&quot;,&quot;publisher-place&quot;:&quot;Downers Grove,
Ill&quot;,&quot;source&quot;:&quot;EBSCOhost&quot;,&quot;title&quot;:&quot;Dictionary
of Jesus and the Gospels
(DJG)&quot;,&quot;title-short&quot;:&quot;DJG&quot;,&quot;URL&quot;:&quot;http://search.ebscohost.com/login.aspx?direct=true&amp;db=nlebk&amp;AN=633424&amp;site=ehost-live&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Perrin&quot;,&quot;given&quot;:&quot;Nicholas&quot;},{&quot;family&quot;:&quot;Brown&quot;,&quot;given&quot;:&quot;Jeannine
K.&quot;},{&quot;family&quot;:&quot;Green&quot;,&quot;given&quot;:&quot;Joel
B.&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,23]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2013&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Perrin,
Brown, and Green, <i>DJG</i>.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn25">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref25" name="_ftn25" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[25]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;6CXw0WfZ&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Immanuel
Maurice Wallerstein, \\uc0\\u8220{}Render unto Caesar?: The Dilemmas of a
Multicultural World,\\uc0\\u8221{} {\\i{}Sociology of Religion} 66, no. 2
(2005): 121\\uc0\\u8211{}33.&quot;,&quot;plainCitation&quot;:&quot;Immanuel
Maurice Wallerstein, “Render unto Caesar?: The Dilemmas of a Multicultural
World,” Sociology of Religion 66, no. 2 (2005):
121–33.&quot;,&quot;noteIndex&quot;:17},&quot;citationItems&quot;:[{&quot;id&quot;:446,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/J3CIXATI&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/J3CIXATI&quot;],&quot;itemData&quot;:{&quot;id&quot;:446,&quot;type&quot;:&quot;article-journal&quot;,&quot;container-title&quot;:&quot;Sociology
of
Religion&quot;,&quot;ISSN&quot;:&quot;1069-4404&quot;,&quot;issue&quot;:&quot;2&quot;,&quot;journalAbbreviation&quot;:&quot;Sociology
of Religion&quot;,&quot;page&quot;:&quot;121-133&quot;,&quot;source&quot;:&quot;EBSCOhost&quot;,&quot;title&quot;:&quot;Render
unto Caesar?: the dilemmas of a multicultural world&quot;,&quot;title-short&quot;:&quot;Render
unto
Caesar?&quot;,&quot;volume&quot;:&quot;66&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Wallerstein&quot;,&quot;given&quot;:&quot;Immanuel
Maurice&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2005&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Immanuel
Maurice Wallerstein, “Render unto Caesar?: The Dilemmas of a Multicultural
World,” <i>Sociology of Religion</i> 66, no. 2 (2005): 121–33.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn26">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref26" name="_ftn26" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[26]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;IMaUf0Gy&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Skye
Jethani, Holy Post Podcast, Unknown, https://www.holypost.com/.&quot;,&quot;plainCitation&quot;:&quot;Skye
Jethani, Holy Post Podcast, Unknown,
https://www.holypost.com/.&quot;,&quot;noteIndex&quot;:25},&quot;citationItems&quot;:[{&quot;id&quot;:538,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/KQ9ZF46C&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/KQ9ZF46C&quot;],&quot;itemData&quot;:{&quot;id&quot;:538,&quot;type&quot;:&quot;interview&quot;,&quot;title&quot;:&quot;Holy
Post
Podcast&quot;,&quot;URL&quot;:&quot;https://www.holypost.com/&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Jethani&quot;,&quot;given&quot;:&quot;Skye&quot;}],&quot;issued&quot;:{&quot;literal&quot;:&quot;Unknown&quot;}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Skye Jethani, Holy Post Podcast,
Unknown, https://www.holypost.com/.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--> I recently heard Jethani say
something like this; however, I cannot find the quote or podcast episode. I
want to ensure I give him credit for inspiring the idea.<o:p></o:p></p>

</div>

<div id="ftn27">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref27" name="_ftn27" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[27]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;aEArrCDb&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Richard
E Oster, \\uc0\\u8220{}\\uc0\\u8216{}Show Me a Denarius\\uc0\\u8217{}: Symbolism
of Roman Coinage and Christian Beliefs,\\uc0\\u8221{} {\\i{}Restoration
Quarterly} 28, no. 2 (1985):
107\\uc0\\u8211{}15.&quot;,&quot;plainCitation&quot;:&quot;Richard E Oster,
“‘Show Me a Denarius’: Symbolism of Roman Coinage and Christian Beliefs,”
Restoration Quarterly 28, no. 2 (1985): 107–15.&quot;,&quot;noteIndex&quot;:18},&quot;citationItems&quot;:[{&quot;id&quot;:534,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/XPGPYUAC&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/XPGPYUAC&quot;],&quot;itemData&quot;:{&quot;id&quot;:534,&quot;type&quot;:&quot;article-journal&quot;,&quot;call-number&quot;:&quot;ATLA0000968471&quot;,&quot;container-title&quot;:&quot;Restoration
Quarterly&quot;,&quot;ISSN&quot;:&quot;0486-5642&quot;,&quot;issue&quot;:&quot;2&quot;,&quot;journalAbbreviation&quot;:&quot;Restoration
Quarterly&quot;,&quot;page&quot;:&quot;107-115&quot;,&quot;source&quot;:&quot;EBSCOhost&quot;,&quot;title&quot;:&quot;'Show
me a denarius': symbolism of Roman coinage and Christian
beliefs&quot;,&quot;title-short&quot;:&quot;'Show me a
denarius'&quot;,&quot;volume&quot;:&quot;28&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Oster&quot;,&quot;given&quot;:&quot;Richard
E&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;1985&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Richard
E Oster, “‘Show Me a Denarius’: Symbolism of Roman Coinage and Christian
Beliefs,” <i>Restoration Quarterly</i> 28, no. 2 (1985): 107–15.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn28">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref28" name="_ftn28" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[28]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;eOZNEhaV&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Josephus
Flavius, \\uc0\\u8220{}Roman Currency,\\uc0\\u8221{} in {\\i{}Josephus Flavius:
Complete Works and Historical Background (Annotated and Illustrated) (Annotated
Classics) Kindle Edition}, trans. William Whiston (Annotated Classics, 2013),
800,
https://www.amazon.com/Josephus-Flavius-Historical-Background-Illustrated-ebook/dp/B00B4I367Q.&quot;,&quot;plainCitation&quot;:&quot;Josephus
Flavius, “Roman Currency,” in Josephus Flavius: Complete Works and Historical
Background (Annotated and Illustrated) (Annotated Classics) Kindle Edition,
trans. William Whiston (Annotated Classics, 2013), 800,
https://www.amazon.com/Josephus-Flavius-Historical-Background-Illustrated-ebook/dp/B00B4I367Q.&quot;,&quot;noteIndex&quot;:16},&quot;citationItems&quot;:[{&quot;id&quot;:533,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/344YWQVZ&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/344YWQVZ&quot;],&quot;itemData&quot;:{&quot;id&quot;:533,&quot;type&quot;:&quot;chapter&quot;,&quot;abstract&quot;:&quot;*
Illustrated with historical maps, timelines, graphical family trees of Jewish
leaders, images of coinage, as well as models of contemporary Jerusalem,
Solomon's Temple, and Herod's Temple\n* Annotated with concise introduction,
that includes modern view of history and analysis of Josephus works\n* Includes
biographies of Josephus, Hasmonaean Dynasty, Herodian Dynasty, Herod,
Vespasian, Titus and Domitian\n* Includes explanation of Hebrew, Greek, and
Roman coinage, units of measure, as well as Hebrew, Julian, and
Syrian/Macedonian calendars.\n*Includes the original text of Josephus'
references to Jesus in Book XVIII and Book XX of Antiquities of the Jews, as
well as description of Essenes.\n* Each book has its own active Table of
Contents.\n* The original footnotes are hyperlinked for easy reference.\n* All
Annotated Classics books are beautifully designed for easy reading and
navigation on e-Readers and mobile
devices.&quot;,&quot;container-title&quot;:&quot;Josephus Flavius: Complete
Works and Historical Background (Annotated and Illustrated) (Annotated
Classics) Kindle Edition&quot;,&quot;ISBN&quot;:&quot;ASIN :
B00B4I367Q&quot;,&quot;page&quot;:&quot;800&quot;,&quot;publisher&quot;:&quot;Annotated
Classics&quot;,&quot;title&quot;:&quot;Roman
Currency&quot;,&quot;URL&quot;:&quot;https://www.amazon.com/Josephus-Flavius-Historical-Background-Illustrated-ebook/dp/B00B4I367Q&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Flavius&quot;,&quot;given&quot;:&quot;Josephus&quot;}],&quot;translator&quot;:[{&quot;family&quot;:&quot;Whiston&quot;,&quot;given&quot;:&quot;William&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2013&quot;,1,21]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Josephus
Flavius, “Roman Currency,” in <i>Josephus Flavius: Complete Works and
Historical Background (Annotated and Illustrated) (Annotated Classics) Kindle
Edition</i>, trans. William Whiston (Annotated Classics, 2013), 800,
https://www.amazon.com/Josephus-Flavius-Historical-Background-Illustrated-ebook/dp/B00B4I367Q.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn29">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref29" name="_ftn29" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[29]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;jY8M0How&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Ann
Spangler and Lois Tverberg, {\\i{}Sitting at the Feet of Rabbi Jesus: How the
Jewishness of Jesus Can Transform Your Faith}, Updated edition (Grand Rapids,
Michigan: Zondervan, 2018).&quot;,&quot;plainCitation&quot;:&quot;Ann Spangler
and Lois Tverberg, Sitting at the Feet of Rabbi Jesus: How the Jewishness of
Jesus Can Transform Your Faith, Updated edition (Grand Rapids, Michigan:
Zondervan, 2018).&quot;,&quot;noteIndex&quot;:28},&quot;citationItems&quot;:[{&quot;id&quot;:186,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/VFB8VX5A&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/VFB8VX5A&quot;],&quot;itemData&quot;:{&quot;id&quot;:186,&quot;type&quot;:&quot;book&quot;,&quot;abstract&quot;:&quot;Sitting
at the Feet of Rabbi Jesus takes readers on a fascinating journey, helping them
discover how learning about the Jewish world of Jesus can enrich their own
faith. This newly expanded softcover edition includes a discussion guide and a
Jewish Seder liturgy&quot;,&quot;call-number&quot;:&quot;BT590.J8 S63
2018&quot;,&quot;edition&quot;:&quot;Updated edition&quot;,&quot;event-place&quot;:&quot;Grand
Rapids,
Michigan&quot;,&quot;ISBN&quot;:&quot;978-0-310-33069-1&quot;,&quot;number-of-pages&quot;:&quot;301&quot;,&quot;publisher&quot;:&quot;Zondervan&quot;,&quot;publisher-place&quot;:&quot;Grand
Rapids, Michigan&quot;,&quot;source&quot;:&quot;Library of Congress
ISBN&quot;,&quot;title&quot;:&quot;Sitting at the Feet of Rabbi Jesus: How the
Jewishness of Jesus Can Transform Your
Faith&quot;,&quot;title-short&quot;:&quot;Sitting at the feet of Rabbi
Jesus&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Spangler&quot;,&quot;given&quot;:&quot;Ann&quot;},{&quot;family&quot;:&quot;Tverberg&quot;,&quot;given&quot;:&quot;Lois&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2018&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Ann
Spangler and Lois Tverberg, <i>Sitting at the Feet of Rabbi Jesus: How the
Jewishness of Jesus Can Transform Your Faith</i>, Updated edition (Grand
Rapids, Michigan: Zondervan, 2018).<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn30">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref30" name="_ftn30" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[30]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION {&quot;citationID&quot;:&quot;HVnEDuSj&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Thomas
Lemke, \\uc0\\u8220{}Render unto God... What Exactly? An Examination of Matthew
22:15-22,\\uc0\\u8221{} Blog, {\\i{}The Chi Files} (blog), October 30, 2017,
http://thechifiles.com/2017/10/30/render-unto-god-what-exactly/.&quot;,&quot;plainCitation&quot;:&quot;Thomas
Lemke, “Render unto God... What Exactly? An Examination of Matthew 22:15-22,”
Blog, The Chi Files (blog), October 30, 2017,
http://thechifiles.com/2017/10/30/render-unto-god-what-exactly/.&quot;,&quot;noteIndex&quot;:28},&quot;citationItems&quot;:[{&quot;id&quot;:473,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/GT87TS2Z&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/GT87TS2Z&quot;],&quot;itemData&quot;:{&quot;id&quot;:473,&quot;type&quot;:&quot;post-weblog&quot;,&quot;abstract&quot;:&quot;This
passage showcases Jesus' rhetorical prowess like few other passages do. But to
see and understand how it works, we have to turn to the Old
Testament.&quot;,&quot;container-title&quot;:&quot;The Chi
Files&quot;,&quot;genre&quot;:&quot;Blog&quot;,&quot;language&quot;:&quot;en-US&quot;,&quot;title&quot;:&quot;Render
unto God... what exactly? An examination of Matthew
22:15-22&quot;,&quot;title-short&quot;:&quot;Render unto God... what
exactly?&quot;,&quot;URL&quot;:&quot;http://thechifiles.com/2017/10/30/render-unto-god-what-exactly/&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Lemke&quot;,&quot;given&quot;:&quot;Thomas&quot;}],&quot;accessed&quot;:{&quot;date-parts&quot;:[[&quot;2020&quot;,11,23]]},&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2017&quot;,10,30]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Thomas
Lemke, “Render unto God... What Exactly? An Examination of Matthew 22:15-22,”
Blog, <i>The Chi Files</i> (blog), October 30, 2017,
http://thechifiles.com/2017/10/30/render-unto-god-what-exactly/.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

<div id="ftn31">

<p class="MsoFootnoteText" style="text-indent: .5in;"><a href="file:///C:/Users/darre/Google%20Drive/School_Darrell/-TKU/Courses/Life%20of%20Jesus%20-%20BIBL2302ONL2/RESEARCH%20-%20POLITICAL%20JESUS/Research%20Paper_Life%20of%20Jesus_Wolfe,%20Darrell%20Final.docx#_ftnref31" name="_ftn31" title=""><span class="MsoFootnoteReference"><!--[if !supportFootnotes]--><span class="MsoFootnoteReference"><span style="font-family: &quot;Times New Roman&quot;,serif; font-size: 10.0pt; line-height: 107%; mso-ansi-language: EN-US; mso-bidi-language: AR-SA; mso-bidi-theme-font: minor-bidi; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-fareast-language: EN-US; mso-fareast-theme-font: minor-fareast;">[31]</span></span><!--[endif]--></span></a>
<!--[if supportFields]><span style='mso-element:field-begin'></span><span
style='mso-spacerun:yes'> </span>ADDIN ZOTERO_ITEM CSL_CITATION
{&quot;citationID&quot;:&quot;Tfpulf5s&quot;,&quot;properties&quot;:{&quot;formattedCitation&quot;:&quot;Bauckham.&quot;,&quot;plainCitation&quot;:&quot;Bauckham.&quot;,&quot;noteIndex&quot;:17},&quot;citationItems&quot;:[{&quot;id&quot;:181,&quot;uris&quot;:[&quot;http://zotero.org/users/6953150/items/347PFS56&quot;],&quot;uri&quot;:[&quot;http://zotero.org/users/6953150/items/347PFS56&quot;],&quot;itemData&quot;:{&quot;id&quot;:181,&quot;type&quot;:&quot;book&quot;,&quot;call-number&quot;:&quot;BT203
.B38 2011&quot;,&quot;collection-number&quot;:&quot;275&quot;,&quot;collection-title&quot;:&quot;Very
short
introductions&quot;,&quot;event-place&quot;:&quot;Oxford&quot;,&quot;ISBN&quot;:&quot;978-0-19-957527-5&quot;,&quot;number-of-pages&quot;:&quot;125&quot;,&quot;publisher&quot;:&quot;New
York : Oxford Univ
Press&quot;,&quot;publisher-place&quot;:&quot;Oxford&quot;,&quot;source&quot;:&quot;Library
of Congress ISBN&quot;,&quot;title&quot;:&quot;Jesus: A Very Short Introduction&quot;,&quot;title-short&quot;:&quot;Jesus&quot;,&quot;author&quot;:[{&quot;family&quot;:&quot;Bauckham&quot;,&quot;given&quot;:&quot;Richard&quot;}],&quot;issued&quot;:{&quot;date-parts&quot;:[[&quot;2011&quot;]]}}}],&quot;schema&quot;:&quot;https://github.com/citation-style-language/schema/raw/master/csl-citation.json&quot;}
<span style='mso-element:field-separator'></span><![endif]-->Bauckham.<!--[if supportFields]><span
style='mso-element:field-end'></span><![endif]--><o:p></o:p></p>

</div>

</div>
<br />
<br />
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
