---
title: 'In this world, but not of it...'
date: '2020-10-29T05:05:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2932704427971105106'
blogger_filename: '/2020/10/in-this-world-but-not-of-it.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
  - 'Armchair Theology'
---

<h3 style="text-align: left;">Is JesusРђЎ mission and message political?&nbsp;</h3><div><br /></div><div>The question came up in class, studying the Life of Jesus. This question is more and more difficult the longer I consider it. My gut says that we have an obligation to be involved in political matters, to influence the kingdom perspectives in houses of power; especially since we live in a representative form of government.</div><div><br /></div><h4 style="text-align: left;">But, is Jesus' mission and message political?</h4><div><br /></div><div>In John 18, Jesus clearly tells a political leader that his kingdom is not of this world. He reinforces that by saying that his people are not fighting for that reason. In this we have an Рђюin but not ofРђЮ demonstration(1). So he wasnРђЎt establishing an earthly reign at that time.</div><div><br /></div><div>Further, in Luke 17, Jesus tells us that his kingdom cannot be observed in the natural. HeРђЎs not trying to take over and rule a physical kingdom at this time(2). Therefore, his goal was not to overthrow the political leadership and take their rule. At least not in the traditional sense.&nbsp;</div><div><br /></div><div>Yet, every message he preached had to do with the way we live here, the way we treat each other here. In Matthew 18, Jesus tells us that our forgiveness should be as extravagant as LamechРђЎs vengeance(3). Therefore, he certainly intended for our lives to be changed by entering into His kingdom. Historically, we can see that his kingdom revolutionized the Roman Empire. In that sense, through changed lives, his impact was very real and present tense. In Matthew 16, Jesus tells us that he will give the keys to his kingdom to the church, inferring that his kingdom is still operating now, today, in but separate from the earthРђЎs systems of power.&nbsp;</div><div><br /></div><div>The best examples of this "in but not of" lifestyle were the prophets and leaders active during exile. These were God's people living among foreign leadership. Daniel, who would have been well known by the Jews in JesusРђЎ audience, lived in Babylon but was not of Babylon. Showing his separateness by not eating their food. But did Jesus ever reference these in his style? It's interesting to note that he references himself as the Son of Man, a frequent phrase in the OT. One particularly interesting passage is in Daniel 7, where there is a reference to the Son of Man coming on the clouds, another famous reference of Jesus talking about his second coming.&nbsp;</div><div><br /></div><div>Jesus rarely came into conflict with Rome, but often with religious leaders.</div><div><br /></div><div>If anything, I would have to call Jesus' style apathetic to natural rulers. He tells the Pharisees to render to Cesar what is Cesar's and God what is God's(6).</div><div><br /></div><div>From the gospels alone, I see primarily an interest in working the Kingdom of God out wherever we are. Being aware that the world system is hostile to us (be wise as serpents but harmless as doves)(7).&nbsp;</div><div><br /></div><div>This is hard for me. I can see how my defense of another may involve me getting involved in political matters. Yet... The longer I ponder this question, I'm finding no evidence that I should be involved. In fact, all the evidence seems to be pointing me toward political apathy. I need to work his kingdom here, now, despite the system. I need to be about my father's business, regardless of what the world does.&nbsp;</div><div><br /></div><div>I'm going to have to ponder this more. Thank you for asking.</div><div><br /></div><div><br /></div><h4 style="text-align: left;">References:</h4><div><br /></div><div><span style="white-space: pre;">	</span>1. РђюJesus answered, РђюMy kingdom is not of this world. If my kingdom were of this world, my servants would have been fighting, that I might not be delivered over to the Jews. But my kingdom is not from the world.РђЮРђЮ</div><div>РђГРђГJohnРђг РђГ18:36Рђг РђГESVРђгРђг</div><div>https://www.bible.com/59/jhn.18.36.esv</div><div><br /></div><div><span style="white-space: pre;">	</span>2. РђюBeing asked by the Pharisees when the kingdom of God would come, he answered them, РђюThe kingdom of God is not coming in ways that can be observed, nor will they say, РђўLook, here it is!РђЎ or РђўThere!РђЎ for behold, the kingdom of God is in the midst of you.РђЮРђЮ</div><div>РђГРђГLukeРђг РђГ17:20-21Рђг РђГESVРђгРђг</div><div>https://www.bible.com/59/luk.17.20-21.esv</div><div><br /></div><div><span style="white-space: pre;">	</span>3. Spangler and Tverberg, Pg. 42-43&nbsp;</div><div><span style="white-space: pre;">	</span>РђюThen Peter came up and said to him, РђюLord, how often will my brother sin against me, and I forgive him? As many as seven times?РђЮ Jesus said to him, РђюI do not say to you seven times, but seventy-seven times.РђЮ&nbsp;</div><div>РђГРђГMatthewРђг РђГ18:21-22Рђг РђГESVРђгРђг</div><div>https://www.bible.com/59/mat.18.21-22.esv</div><div><br /></div><div><span style="white-space: pre;">	</span>4. РђюAnd Jesus answered him, РђюBlessed are you, Simon Bar-Jonah! For flesh and blood has not revealed this to you, but my Father who is in heaven. And I tell you, you are Peter, and on this rock I will build my church, and the gates of hell shall not prevail against it. I will give you the keys of the kingdom of heaven, and whatever you bind on earth shall be bound in heaven, and whatever you loose on earth shall be loosed in heaven.РђЮРђЮ</div><div>РђГРђГMatthewРђг РђГ16:17-19Рђг РђГESVРђгРђг</div><div>https://www.bible.com/59/mat.16.17-19.esv</div><div><br /></div><div><span style="white-space: pre;">	</span>5. РђюI kept looking in the night visions, And behold, with the clouds of heaven One like a Son of Man was coming, And He came up to the Ancient of Days And was presented before Him.</div><div>Daniel 7:13 NASB1995</div><div>https://bible.com/bible/100/dan.7.13.NASB1995</div><div><br /></div><div><span style="white-space: pre;">	</span>6. He said to them, РђюThen give back to Caesar what is CaesarРђЎs, and to God what is GodРђЎs.РђЮ</div><div>Luke 20:25 NIV</div><div>https://luke.bible/luke-20-25</div><div><br /></div><div><span style="white-space: pre;">	</span>7. РђюBehold, I send you out as sheep among wolves. Therefore be wise as serpents, and harmless as doves.</div><div>Matthew 10:16 WEB</div><div>https://bible.com/bible/206/mat.10.16.WEB</div><div><br /></div>
<div><br /></div><div style="text-align: center;">***</div>
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
