---
title: 'Value is an the inside out proposition.'
date: '2020-02-29T15:17:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2853963357507849547'
blogger_filename: '/2019/12/value-from-inside-out.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

<div>How you value yourself is how others will evaluate you...</div><div><br></div><div>What you are getting back from the world around you is far more dependant on what is inside than you realize. You're getting from others the energy you put out.</div><div><br></div><div>This is about value not behavior, even if behavior is affected by value. One must not discount external feedback in regards to behavior modifications. If everyone says you interrupt a lot (my old nemesis), then maybe work on that.</div>
<br>
However...<div><br></div><div>Value is intrinsic. It is known in a deep inner knowing. It is not dependant upon external feedback. In fact, value has the opposite affect. Value is an inside out presentation.<br>
<br>
People's reactions to you is more likely a byproduct or response of the value you project.<br>
<br>
If you value yourself less, you project that value, you tolerate things, and things come.<br>
<br>
If you value yourself more, people still try to test your value but you shut those people down faster. And, people of higher value are attracted to you. People with lower values walk away faster.<br><br>
So attracting higher value starts first internally, by increasing your own value of you, then externally as people respond to that.<br><br>
What I would add as a Christian, is that any value you have for yourself apart from Christ is empty. It's hard to see our failure and own our value. The more honest we are the less we value ourselves... Unless... We know that our value is based not on our deeds but on his eyes.<br>
<br>
Our value is what he says it is, and he says it's worth the price of His Son.<br>
<br>
Therefore, the paradigm shift is knowing who we are in His eyes. Not church. Not Religion. But God's eyes.<br>
<br>
When we see ourselves the way he sees us, our identity becomes firm and unmovable. Then from that identity, we work inside out, and people begin to respond differently.<br><br>For example, I noticed this play out in an interaction with my friend one Sunday. She could see the difference in my eyes, demeanor, how I talk and carry myself. And instead of pushing me away she leaned in more. Even responded to a coffee invite she's usually too busy for.<br><br>
I could see her perceiving me differently because of my mindset shifts and how they affect my presentation.<br><br>
She's not my person, but, it was encouraging to see someone who used to respond to me one way shift how she responded as I changed from the inside out.<br>
<br>Want to take it to the next level?&nbsp;</div><div><br></div><div>Begin calling others to a higher valuation of themselves!&nbsp;</div><div><br></div><div>#Selah<br><div id="mc_embed_signup"><form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank"><div id="mc_embed_signup_scroll"><br></div></form></div>
</div>