---
title: 'I have a confession... I killed Jesus the Christ.'
date: '2020-11-25T05:58:00.0030000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '6041510652413886330'
blogger_filename: '/2020/11/i-have-confession-i-killed-jesus-christ.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<div>In class, a discussion question was posed. How would we answer the following?</div><div><br /></div><div><div></div></div><blockquote><div><div>1) In his 1933 essay "The Church and the Jewish Question," a defense of the Jewish people against the Nazi's, Dietrich Bonhoeffer wrote that because the Jewish people "hung the redeemer on the cross" they will continue to "endure the curse of its action in long-drawn-out suffering." How would you evaluate and respond to this statement? To help address this question, explore who is responsible for Jesus' death in the Gospels (and Acts). Why does this question matter?</div><div><br /></div><div>2) From a "purely historical" perspective, why was Jesus crucified? From the perspectives of the Gospels, what is the significance of his death? How would our faith be impacted if the Gospels ended with Jesus' death and did not include the resurrection?</div></div><div></div></blockquote><div><br /></div><div><!--x-tinymce/html-mce_53709328511606282457812--><p>The question in both of these questions:&nbsp;</p><p></p><p><strong>Who was Jesus, and why was he crucified?&nbsp;</strong></p><p></p><p>In the fall, God rushed in to take the fig leaves (man's attempt to cover himself) and replace them with animal skins (symbolic of the lamb who would be slain). Just a few short years later (decades are short in a 900 year lifetime), Abel's sacrifice was one of the flocks (probably a lamb, although unknown).&nbsp;</p><p></p><p>Israel then is birthed into a nation, and an Atonement Lamb is sacrificed for sin. Isaiah 53 (really 52--56) paints such an elaborate picture of this Lamb who would be slain. It tells us that "all of like sheep have gone astray" (Isaiah 53:6). Then Isaiah 55:3 tells us:</p><p></p><blockquote>
<p>Come to me with your ears wide open.<br />Listen, and you will find life.<br />I will make an everlasting covenant with you.<br />I will give you all the unfailing love I promised to David.</p>
</blockquote><p></p><p>The covenant of David is forever. All of us have gone astray. The throne of David is the throne of Jesus. Jesus was rejected by "his own". But his own is everyone on planet Earth too. Romans rejected him. Jewish leaders rejected him. And we have all rejected him at one time or another. Even those of us who were "Christians" have rejected him when we chose not to follow his Word in some fashion or choice.&nbsp;</p><p></p><p>We have a Messiah who was the ultimate fullness of what it meant to be walking in God the Father's Torah. That Torah has not passed away, so says Jesus himself. Therefore, the covenant with Israel still stands today as it always has. He is still their God, and those who bless Israel will be blessed; those who curse Israel will be cursed, and the Kingdom of God will one day manifest physically and reside as its capital in Jerusalem.&nbsp;</p><p></p><p>Jesus himself said that he would be handed over to be crucified, the Passover supper was about this very thing. He said the woman with the oil was anointing him for burial and predicted that her sacrifice would be included in the spread of the Good News. Jesus even rebukes Peter for trying to prevent him from fulfilling this end. (Matthew 16:23; 26:2, 26-30; Mark 14:6-9; 20-26; Luke 18:31-34, 22:7-38; John 13:31-38). By quoting Isaiah 61, Jesus is tying himself to the larger ongoing prophetic words of Isaiah about a suffering savior who would come (Luke 4:14-30).&nbsp;</p><!-- x-tinymce/html-mce_53709328511606282457812 --><p></p><p></p><p>Isaiah 53 goes on to say:</p><p></p><blockquote>
<p>5But he was pierced for <em><strong>our rebellion</strong></em>, crushed for <em><strong>our sins</strong></em>.<br />He was beaten so <em><strong>we could be whole</strong></em>. He was whipped so <em><strong>we could be healed</strong></em>.</p>
<p></p>
<p>6<strong>All</strong> of us, like sheep, <strong>have strayed</strong> away. We have <strong>left God’s paths to follow our own</strong>. <em><span style="text-decoration: underline;"><strong>Yet the&nbsp;Lord&nbsp;laid on him the sins of us all.</strong></span></em></p>
<p></p>
<p>10But i<strong>t was the&nbsp;Lord’s good plan</strong> to crush him and cause him grief. Yet when his life is made an offering for sin, <em>he will have many descendants</em>. He will enjoy a long life, and the&nbsp;Lord’s good plan will prosper in his hands.</p>
<p></p>
<p>11When he sees all that is accomplished by his anguish, <em><strong>he will be satisfied</strong></em>.</p>
</blockquote><p></p><p><em>(See also: Romans 3:23, which is quoting Isaiah)</em></p><p></p><p></p><p>Jesus was crushed for my sins, not only for some Pharisee's sin in 33 A.D. It was the Father's plan to do so, many years before it happened. And Jesus sees what he accomplished in me through it, and he is satisfied with the results.&nbsp;</p><p></p><p></p><p>The People of Israel did not hang Jesus… you and I did. Our sin. Our rejection of "good". Our need for a savior brought him to the cross.&nbsp;</p><p></p><p><strong>No… Israel did not kill Jesus. I did. And I am grateful for the Grace he's shown me in it.&nbsp;</strong></p><p></p><p><!--x-tinymce/html-mce_53709328511606282457812-->






























</p><p>Darrell</p></div>
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
