---
title: 'Stop letting your emotions rule your life and dictate your relationships.'
date: '2020-02-14T05:33:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7070723730636859394'
blogger_filename: '/2020/02/stop-letting-your-emotions-rule-your.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

The tendency of the human heart to bend towards HIDING and Self Protecting is the oldest frailty we humans have.&nbsp;<div><br></div><div>It started in the Garden of Eden.</div><div><br></div><div>As soon as man disconnected from intimacy with God it created disconnection in his intimacy with others. The first fall out of the Fall was to cover and hide. The second fall out of the Fall was to blame others for the experience we're having rather than take ownership of our part in it.</div><div><br></div><div>1. Hiding</div><div>2. Blaming</div><div><br></div><div>These two poisonous traits are the root of our sin nature.&nbsp;</div><div><br></div><div>I see this play out in my son's debates. He did this to me, he's always, he never, well if you wouldn't, that's because you...</div><div><br></div><div>Unfortunately, many of us never outgrow this tendency. We continue to run from... HIDING from others, self protecting, blaming others for our own emotions.</div><div><br></div><div>How often I told my wife, kids, bosses, or even God himself... "If you wouldn't/would... I...."</div><div><br></div><div>Rather than taking ownership of my emotions, I wanted to make other people responsible for them.</div><div><br></div><div>If only this person would stop doing x, start doing y, if z circumstances would change... THEN my emotions would be good.&nbsp;</div><div><br></div><div>No matter how hard the external circumstances, your emotions are yours alone. Talk to the POWs, and others who maintained their joy in the worst places on Earth.</div><div><br></div><div>Paul and Silas were sent to prison unfairly, beaten without due process, and still... They sang.</div><div><br></div><div>So if you're ready for the hardest and most rewarding task you've ever been assigned:</div><div><br></div><div>Own Your Emotions!</div><div><br></div><div>Say this out loud:</div><div><br></div><div>"I acknowledge that I am having feels. These feelings area my own. While they are in response to external stimuli, they were not caused by others and cannot be fixed by others. I chose to lean into this emotion, get curious about it, determine what I can my heart is telling me, what truths or lies are involved, and let the Holy Spirit guide me through healing and restoration. I will not ask others to change, I will only determine what I'm feeling and how I will choose to respond. That may mean cutting off relationship, but, it will more often mean pressing into relationship and exposing what I would rather hide, owning what I would rather blame, and allowing this to be about my emotion and not the circumstances, actions, it words that led to it."</div><div><br></div><div>Selah</div><div><br></div><div><br></div><div><br></div>