---
title: 'A Christian simply cannot marry a non-Christian. It''s life and death serious.'
date: '2020-03-29T23:57:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2710762599599485937'
blogger_filename: '/2020/03/a-christian-simply-cannot-marry-non.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

<div>In a dating thread on Facebook, a conversation arose about faith and dating...</div><div><br></div>Someone said they were upset because they wanted a relationship with a Christian woman who wouldn't accept an offer from a non-Christian.&nbsp;<div><br></div><div>Someone else in the conversation thread said they didn't mind if the person was religious they just didn't want it jammed down their throat.</div><div><br></div><div>Someone else said they had no such standard but did like it if the person had some kind of Faith.</div><div><br></div><div>A year ago, I'd have felt different. But today, here was my reply:</div><div><br></div><div>Jesus is a pre-qualification for me. It's not even enough to be a "Christian". We need to have as much overlap in worldview as possible.<br></div><div><br></div><div><div>See.</div><div><br></div><div>Faith is a term people often use synonymous with religion. A set of beliefs. Esoteric. Heady. Just believe.</div><div><br></div><div>In my worldview.&nbsp;</div><div><br></div><div>Jesus is a living, breathing, active participant in my life. I speak to Him. He speaks to me. It's dialogue, not monologue. He is my Lord, my King, my best friend, my lover, my everything.</div><div><br></div><div>There's literally not a single relationship on Earth that matters more than my relationship with him.&nbsp;</div><div><br></div><div>So within that framework:</div><div><br></div><div>A marriage involves three, active, participants.&nbsp;</div><div><br></div><div>A man who is submitted to Jesus.&nbsp;</div><div><br></div><div>A woman submitted to Jesus.&nbsp;</div><div><br></div><div>A man and woman submitted to each other.&nbsp;</div><div><br></div><div>And Jesus leading the marriage. The real, actual, person Jesus. Not the historical figure from societies ideas about him.&nbsp;</div><div><br></div><div>In my worldview, that's a dynamic two-way friendship and relationship with Jesus. He is Lord of <b><i><u>our</u></i></b> lives. Any relationship with a woman who was not <i>equally submitted</i> to His Lordship would be impossible for me. A non-starter. And that's as it should be.&nbsp;</div><div><br></div><div>This isn't about religion, it's way beyond that.</div><div><br></div><div>Point a gun at my kid's head and tell me you'll shoot unless I renounce Jesus, I'll tell the kids that I'll see them on the other side. I'd do them to say hi to Mom for me.</div><div><br></div><div>It's life and death serious for me.&nbsp;</div><div><br></div><div>So that's why it's a non-starter.</div></div><div><br></div><div><div>This is actually practical too.</div><div><br></div><div>Because every single decision, from schooling the kids, Sunday habits, where we live... It's ALL submitted to God in prayer.&nbsp;</div><div><br></div><div>I'm going to deeply rely on her ability to hear the voice of God and speak prophetically into our lives and into every day decisions.&nbsp;</div><div><br></div><div>That's simply just not possible unless she shares my worldview.</div></div><div><br></div><div>**To which I got this reply**</div><div><i>Darrell G Wolfe wow! Did you really state you would rather see your kids get murdered than denounce a mythical figure?? I will get kicked out of this group for this but I don’t care! You are a freaking idiot!</i><br></div><div><br></div><div>**To which I reply:</div><div><br></div><div><div>No. I said I would rather see my kids murdered&nbsp; than denounce the only person who has the power to save my soul and theirs. The only person that ever matters in any reality. The one who existed before this Earth, came and died for me, and lives today. The only friend that will ever ultimately matter. He and I speak frequently. He's not mythical. We speak, two way. And I love him more than I love my life. He is my everything. There's literally nothing and no one on Earth that matters more.&nbsp;</div><div><br></div><div>Someday, everyone that's ever lived will agree. Some with pleasure. Some with distaste.&nbsp;</div><div><br></div><div>But every knee will bow to Him eventually. At the end of all things.&nbsp;</div><div><br></div><div>Love you brother. Sorry you can't see it yet.</div></div><div><br></div><div>#Selah</div><div><br></div>