---
title: 'Collaborate with someone, do something magical.'
date: '2020-03-06T14:47:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3587484524980156474'
blogger_filename: '/2020/03/collaborate-with-someone-do-something.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

<div>NO HIDING means we lean in to uncomfortable places and topics. The more we would want to shy away, we lean in harder, even and especially religion and politics.</div><div><br></div><div>If you want to skip the whole post and get the point, here it is:</div><div><br></div><div><b>Go collaborate today, make things happen. The world is made better when we stop waiting for a handout and we start handing out ourselves.</b><br></div><div><br></div>I'm going to get political here for a moment. But before I do, let me say that I believe both the Red and Blue teams we have today are killing us. This isn't about Republican or Democrat, I think they should both be replaced. This is about Capitalism vs Socialism. I think this is important, and it's worth saying.<div><br></div><div>***On to my point, this is in response to a Reddit thread:</div><div>https://www.reddit.com/r/changemyview/comments/fdziov/cmv_mike_bloombergs_campaign_is_proof_that_the/?utm_medium=android_app&amp;utm_source=share<br></div><div><br></div><div><div>The Free Market, not Big Government, has given you everything that's ever made your life better, even the device you are reading this on.</div><div><br></div><div>When people are free to associate with each other without interference by big government or big corporations magic things happen.</div><div><br></div><div>Socialism is death. Capitalism and Free Markets are responsible for raising more people from poverty than any other system in history, by a long shot.&nbsp;</div><div><br></div><div>What people think they hate is Capitalism. What they actually hate is Crony Capitalism, which is actually a form of Socialism.&nbsp;</div><div><br></div><div>Socialism and Crony Capitalism both require Big Government. Real capitalism requires small government. We haven't seen real capitalism in my lifetime. Unfortunately. It made us prosperous as a nation, then we allowed progressivism to suffocate us.</div><div><br></div><div>This Reddit thread had the right heart behind it but shows deep ignorance on serval levels.</div><div><br></div><div>Just to name a few:</div><div><br></div><div>The inference is raising the income tax rate.</div><div><br></div><div>Income tax rates are for "earned income" so they only apply to money made from working a job. They have zero affect on "the rich". Their income didn't come from any job. So to tax the rich, as the author would like to do, would require taxing other income sources, namely real estate and investments at this higher rate for amounts over a certain amount.</div><div><br></div><div>Which is fine, if your philosophy is to tax the rich more. Then again, how do you measure fair.</div><div><br></div><div>If we each put in the same percentage, that would be fair. For those who earn more to pay a higher percentage is not fair, but, you could theoretically argue that they are responsible for more because they get more from the economy. I suppose.</div><div><br></div><div>All the data, supports lower taxes and fewer regulations and free markets are the BEST way to raise everyone's income.</div><div><br></div><div>Our economy soared under Trump's lower regulations and lower taxes and suffocated under Obama's death grip on regulations and taxes.</div><div><br></div><div>It's not rocket science.</div><div><br></div><div>Open Source software makes our digital Life better because people freely collaborate without top down interference. This is why more people are using Android than Apple iOS, by a long shot. Because Android is Open Source, allowing more people to contribute more, making it better and cheaper, making it available to more people. Every prepaid phone used by the nation's poorest people is an Android, NOT an Apple. Because Free Market, Free Association, and Open Source Collaboration make the world a better place.</div><div><br></div><div>Anytime people can collaborate without being told what they can or cannot do by some Big Brother, magical things happen and cool stuff gets created.&nbsp;</div><div><br></div><div>Now... I'm taking about small business.&nbsp;</div><div><br></div><div>Real innovation happens when the government gets out of the way.</div><div><br></div><div>Big Corporations AND Big Government are the problem. Big Corporations get bigger under Big Government, because they get new regulations passed that snuff out smaller competition. Deregulation allows smaller leaner companies to compete and outshine the big guys. Redbox and Netflix started small and put Blockbuster out of business. In a Socialist</div><div>System (Big Brother had his hands in everything, telling everyone what to do), we'd still have Blockbuster and no concept that Netflix or Redbox were possible.</div><div><br></div><div>If you want the world to be better for people, let the government do what it was designed to do and stop making it do what it wasn't designed to do.</div><div><br></div><div>Government can and should set and enforce rules to make sure nobody gets abused or taken advantage of.&nbsp;</div><div><br></div><div>Government should be a referee in the game only. It should NEVER be a player in the game. When government starts being a player, the system collapses. Even as a referee if it's too involved and too tightly observing, it stifles the game. Imagine if referees took the coaches job and stopped plays in the middle to tell quarterbacks they're holding the ball wrong. Coaches and Refs are different roles.&nbsp;</div><div><br></div><div>The system we have today has the government playing all the roles and even competing with the players.&nbsp;</div><div><br></div><div>The system we need to return to is one in which the players play freely without government interference and the government only steps in when absolutely necessary.</div><div><br></div><div>The Free Market. Is the real "Social" construct. It's one in which people freely associate, work together, collaborate, and make things happen without Big Brother always stepping in to squash things.&nbsp;</div><div><br></div><div>The Free Market, not Big Government, has given you everything that's ever made your life better, even the device you are reading this on.</div></div><div><br></div><div><b>Go collaborate today, make things happen. The world is made better when we stop waiting for a handout and we start handing out ourselves.</b><br></div><div><br></div><div>#Selah</div><div><br></div>