---
title: 'Depends on how you look at it...'
date: '2020-03-14T13:01:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7472948308862631826'
blogger_filename: '/2020/03/depends-on-how-you-look-at-it.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

<div>From some distant Galaxy, the destruction of our solar system would be barely a match flicker.&nbsp;<br></div><div><br></div>From the vantage point of heaven, things here don't matter as much.<div><br></div><div>I and my boys are living without Flavia here... For us this is painful and sad. But last I heard from Jesus, she was teaching at classes, playing with the kids, and finally walking on water like she'd always dreamed of doing. Since she went ahead of us, she's even had a hand in preparing our homes there.&nbsp;</div><div><br></div><div>From her vantage point, this is a temporary separation. She's not concerned.</div><div><br></div><div>Perspective</div><div><br></div><div>Today, 3/15/2020, many are concerned about the coronavirus and how it's affecting society and commerce and businesses and toilet paper... Why toilet paper people!?</div><div><br></div><div>This time next year, some will be grieving there loss of loved ones with compromised immune systems that didn't survive this virus.&nbsp;</div><div><br></div><div>This time next year, MOST people won't be thinking about it, because the news media will have time then to worry about something else instead. The coronavirus will have become just another non-issue something we worried about that didn't actually end up happening to most people.</div><div><br></div><div>Some, though, will be pondering life from my perspective, as one who lost. Realizing, some things just aren't worth getting worked up about.</div><div><br></div><div>There are things that matter. This just isn't one of them.</div><div><br></div><div>#Shalom</div><div>#LiveLong&amp;Prosper</div><div>#Selah</div><div><br></div>