---
title: 'My tongues journey...'
date: '2021-02-12T04:49:00.0060000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3915693636059815043'
blogger_filename: '/2021/02/my-tongues-journey.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
  - 'Studies'
---

<p></p><p></p><p>
</p><p>My story with tongues:</p>

<p>Being an "intellectual", I struggle with emotional things. Yet, the spirit is so closely tied to our emotional experience and expression. One day, after learning that the gifts did not die out with the Apostles (like I grew up believing); I began studying everything I could find on the topic. I then put down everyone else's book and studied my own Bible for any references to the event.&nbsp;</p>

<p>My conclusion found it's hook in 1 Corinthians 12:6. He works all of these things in all people. It's not that one person gets this and another gets that. In fact, the wording of the passage uses two different words for "another" meaning "another of the same kind, another of a different kind).&nbsp;</p>

<p>He works them to different individuals as the need arises in different situations, but, he works all of them in all people.&nbsp;</p>

<p>SO... Here I was, an organs and hymnals former-preacher's kid, faced with God's Word. What was I to do?&nbsp;</p>

<p>I sat in the back of my pick-up truck, bowed my knees, and said "God, you said this is for everyone. I receive it now. I will listen. I will open my mouth. I will saw whatever I hear, regardless of how silly it sounds."</p>

<p>Eventually, a syllable. Then a part of a word. After an hour, a short few words... One day, after doing this for many days, phrases and paragraphs came.&nbsp;</p>

<p>It's now my go-to prayer language. I start prayer there and then see where it goes.&nbsp;</p>

<p>Sometimes I "feel" something, sometimes I don't. Always, if I will stop, quite my heart, listen, they come.&nbsp;</p>

<p>I hope that helps someone.&nbsp;</p>

<p>************</p>

<p>1 Corinthians 12&nbsp;</p>

<p>4 Now there are different gifts, but the same Spirit. 5 And there are different ministries, but the same Lord. 6 And there are different results, <strong>but the same God who produces <em>all of them in everyone</em></strong><em>.</em> 7 T<em><strong>o each person</strong></em> the manifestation of the Spirit is given for the benefit of all. 8 For one person is given through the Spirit the message of wisdom, and another the message of knowledge according to the same Spirit, 9 to another faith by the same Spirit, and to another gifts of healing by the one Spirit, 10 to another performance of miracles, to another prophecy, and to another discernment of spirits, to another different kinds of tongues, and to another the interpretation of tongues. 11 It is one and the same Spirit, distributing as he decides to each person, who produces all these things. (NETBible)</p>


<p>Alternate wording: And there are diversities of operations, <strong>but it is the same God which worketh all in all.</strong> (12:6 KJV)</p><p>
</p><p></p><p></p><p></p><p></p><p><br /><br />To see an old study I did on Tongues:<br /></p><div><span face="&quot;verdana&quot; , sans-serif"><li><a href="http://www.darrellwolfe.com/2015/04/tongues-foundation.html" target="_blank">Tongues | The Foundation</a></li><li><a href="http://www.darrellwolfe.com/2015/04/tongues-foreshadowing.html" target="_blank">Tongues | The Foreshadowing</a></li><li><a href="http://www.darrellwolfe.com/2015/04/tongues-fulfillment.html" target="_blank">Tongues | The Fulfillment</a></li><li><a href="http://www.darrellwolfe.com/2015/04/tongues-facts.html" target="_blank">Tongues | The Facts</a></li><li><a href="http://www.darrellwolfe.com/2015/04/tongues-familiar.html" target="_blank">Tongues | The Familiar</a></li></span></div><p> </p><p><br />
<br />
<br />
</p><div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<div class="fx-relay-email-input-wrapper"><input class="email" id="mce-EMAIL" name="EMAIL" required="" style="padding-right: 30px;" type="email" value="" /><div class="fx-relay-icon" style="bottom: 0px; right: 2px; top: 0px;"><button class="fx-relay-button" id="fx-relay-button" style="height: 24px; min-width: 24px; width: 24px;" title="Generate new alias" type="button"></button></div></div><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
