---
title: 'Given the New Perspective on Paul (NPP), how would you present the Gospel today?'
date: '2021-10-18T21:39:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8216753801030979800'
blogger_filename: '/2021/10/given-new-perspective-on-paul-npp-how.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'Class Assignment'
  - 'Biblical Studies'
  - 'Armchair Theology'
---

Q: Given the New Perspective on Paul (NPP), how would you present the Gospel today?<div><br></div><div>A: My distillation from a year (so far) of listening to NT Wright and Tim Mackie and Michael Heiser:</div><div><br></div><div>God created a good world with the intention of being with his humans as co-rulers of that world.&nbsp;</div><div><br></div><div>Rebellions of various kinds have gotten that project off track, and are the source of all the evil and brokenness we see.&nbsp;</div><div><br></div><div>God began restoring the world to himself through Jesus. His spirit filled body are called to work with him to create pockets of heaven right in the middle of all that brokenness.&nbsp;</div><div><br></div><div>One day, Jesus will return and restore all things fully to God's good order.&nbsp;</div><div><br></div><div>In the meantime, we are invited to participate in God's good world by becoming new kinds of humans, being changed from the inside out, to Love God and Love our Neighbor.</div><div><br></div><div>If you can feel that something inside of you is broken, even if you cannot identify what it is, God has an offer for you.</div><div><br></div><div>Give yourself to Him. Allow him to prune the brokenness out and place a new heart inside and make you into a new kind of human from the inside out.&nbsp;</div><div><br></div><div>He demands your absolute loyalty but not your perfection.&nbsp;</div><div><br></div><div>He will do all the changing, he asks you to let him do it.&nbsp;</div><div><br></div><div>And when he's done some work on you, he'll ask you to start working with others to bring them into this new way of being human.&nbsp;</div><div><br></div>