---
title: 'The dangers of western American Christianity... and the real Gospel of the Kingdom of God.'
date: '2021-10-06T13:35:00.0050000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '5354526517757970110'
blogger_filename: '/2021/10/the-dangers-of-western-american.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
  - 'Class Assignment'
  - 'Biblical Studies'
  - 'Armchair Theology'
---

<p><i>*I'm oversimplifying, it's a blog post and I'm just jotting a few ideas down to ponder. </i><br /></p><p></p><p>This morning I saw yet another post that derives (whether the author knows it or not) from broken reformation thinking. The poster asks: "Will God save any person that God does not want to save?"&nbsp;</p><p>I don't know if the poster is seriously asking or if they're trolling the Calvinists with such a question, but it prompted me to write the following.</p><p>&nbsp;</p><p><b>Western American Christiany's "Gospel": </b><br /></p><p>When we present the gospel as something akin to "believe these statements, say the magic password, and go live any way you want because you have your ticket to go to heaven when you die"... we basically misrepresent the entire package start to finish.&nbsp;</p><p><i>Note: God works through imperfect people and imperfect representations of his real offer. Introduce someone to Yahway and Yeshua, and the Ruach will take over and do the rest. But... if we know better, we should do better.&nbsp;</i></p><p></p><p>&nbsp;</p><p><b>When/How it went off the rails: <br /></b></p><p>As the church grew increasingly full of gentile believers, they eventually lost touch with their Jewish roots. Some late-early church fathers began asking all the wrong questions about a Greek idea of disembodied afterlife in which we leave this mortal coil for the "real thing".&nbsp; <br /></p><p><i>Side note: Did you see a new Matrix movie is coming out? It asks these questions too.&nbsp; </i><br /></p><p>To make matters worse, around <a href="https://en.wikipedia.org/wiki/Constantine_the_Great_and_Christianity" target="_blank">312AD</a>
 the church received a huge blessing, which became its downfall. They 
went from persecution to favored status. While the relief from 
persecution was a blessing, various leaders received political power 
which was not a blessing but a trap. As it is today, which anyone awake should know by surveying the American Christianity landscape in 2019-2021. <br /></p><p>And in the transition from the early Jewish+Gentile Sect called The Way or Christians to a Greek/Gentile movement later called Christianity, we lost our moorings and went from being a movement of Jesus Communities quietly loving their neighbor and looking forward to the Kingdom of God, to a religion with priests and temples who did all the wrong things asking all the wrong questions.&nbsp;</p><p>This religion called Christianity (not to be confused with biblical the biblical Christians) took on Greek and Roman questions about a disembodied afterlife. These events, set up the later reformers of the 1500s to start asking all the wrong questions about "who goes to heaven and who doesn't".&nbsp;</p><p>These developments started having us asking questions about "who's in and who's out". Reformers rightly gave us the truth about salvation by grace through faith, but then misdefined all the terms for us.</p><p>Today, in chat-rooms all over Christian Middle Earth, people ask "will so and so still go to heaven if", argue about free will vs sovereignty, and debate whether someone who's "in" can become "out". All of this is largely based on the wrong paradigm. <br /> <br />The fact is, the biblical hope has very little to say about "going to heaven when we die". More on that:<br /></p><ul style="text-align: left;"><li><a href="https://draft.blogger.com/#">Compelled: Speaking and Living the Gospel - Tim Mackie</a></li><li><a href="https://www.youtube.com/watch?v=ICHovRHJAYY" target="_blank">What is the Gospel? NT Wright</a></li><li><a href="https://www.youtube.com/watch?v=fzSkIBgeETo" target="_blank">What is the True Meaning of the Gospel? Michael Heiser</a></li><li><a href="https://www.youtube.com/watch?v=MMwz3A44viM" target="_blank">What God wanted on Earth Dr Michael Heiser</a></li></ul><p style="text-align: left;"><br /><b>What IS the Gospel, then?</b></p><p style="text-align: left;">Read the book of Matthew and you will find a fascinating theme: &nbsp; <br /></p><p style="text-align: left;"></p><blockquote><p style="text-align: left;"><i>Jesus went throughout all of Galilee, teaching in their synagogues, <b>preaching the gospel of the kingdom</b>, and healing all kinds of disease and sickness among the people. (<a href="https://biblehub.com/matthew/4-23.htm" target="_blank">Mat 4</a>)&nbsp;&nbsp;</i></p><p style="text-align: left;"><i>And this <b>gospel of the kingdom</b> shall be preached in all the world for a witness unto all nations; and then shall the end come. (Mat 24)</i>&nbsp; </p></blockquote><p style="text-align: left;">You know what you won't find? You won't find "Believe on me, say a magic prayer, and go to heaven when you die". You'll find a teacher who is very concerned with this world, not another disembodied world. The entire Jewish hope, which is the Christian hope, is The Kingdom of God. It's themes bleed through every page of the Bible from Genesis to Revelation.&nbsp;</p><p style="text-align: left;">This Kingdom is about a New Heaven and New Earth implemented by the Day of the Lord.&nbsp;</p><p style="text-align: left;"></p><p style="text-align: left;"><b>The Gospel is this: </b>&nbsp;</p><ul style="text-align: left;"><li>God made a good world to live in with the humans he created to rule beside him as his co-rulers.&nbsp;</li><li>This project was delayed by several rebellions, but God has begun to make things right through a man called Abraham and his seed called Jesus.&nbsp;</li><li>Jesus defeated death and now reigns as King of Kings and Lord of Lords from Yahweh's throne.&nbsp;</li><li>One day, he will return to judge all those who rejected Yahweh (spirit and human).&nbsp;</li><li>At that time, he will create a New Heaven and New Earth, and the Kingdom of God will reside on Earth as it was always intended.&nbsp;</li><li>Anyone who chooses this Kingdom is invited, free of charge. One cannot earn their place in this kingdom, it's a free invitation.&nbsp;</li><li>Accepting Citenship in the Kingdom of God is similar to accepting Citenship in the United States of America, or Canada, or any other large nation. It means learning the culture of this citizenship, and being a good citizen. This invitation will require you die to your old life and allow the Spirit to begin giving you a new heart and making you into a new kind of human. The fact this process is taking place will be reflected by changes in attitude and behavior. But those are fruit of the change only. They are not how you earn or keep your membership in the Kingdom.&nbsp;</li><li>All are welcome but only those who remain loyal to Yahweh are welcome to stay. Loyalty does not mean perfection in action but loyalty in believing. You attempt to live rightly before him because it's how you love him. You will make mistakes and they are welcome. What is not welcome is outright rebellion. </li></ul><p style="text-align: left;"></p><p style="text-align: left;"></p><p style="text-align: left;"><b>Simply Put:</b> You are invited to become a member of the Kingdom of God, it will cost you everything, even your life, but the rewards are membership in a Kingdom that has no end. Even after you die, you will receive a renewed body on a renewed earth in which Jesus is Lord and King. All who join this Kingdom will be there, including anyone you loved who is also a member. Come, join the Kingdom, and look forward to new creation. <br /> <br /> Selah</p><p style="text-align: left;"><br /> <br /> Subscribe Now - Pursue a No Hiding Lifestyle </p><div id="mc_embed_signup"><form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank"><div id="mc_embed_signup_scroll"><div class="fx-relay-email-input-wrapper"><input class="email" id="mce-EMAIL" name="EMAIL" required="" style="padding-right: 30px;" type="email" value="" /><div class="fx-relay-icon" style="bottom: 0px; right: 2px; top: 0px;"><button class="fx-relay-button" id="fx-relay-button" style="height: 24px; min-width: 24px; width: 24px;" title="Generate new alias" type="button"></button></div></div><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
