---
title: 'What culture are you incentiviving?'
date: '2021-06-10T15:46:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2434432366187188602'
blogger_filename: '/2021/06/what-culture-are-you-incentiviving.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
---

<div>You get what you incentivize.&nbsp;</div><div><br></div><div>I work in the fraud call center for a bank. When I was hired the culture was built around being aware, stopping fraud, we were constantly told what our fraud loss numbers were as a dept compared to the budget for loss. We each felt personally responsible for protecting the bank because any loss we let through affected our seal neighbor.</div><div><br></div><div>In the last two years, they've moved away from that model and added a handle time. So what's incentivized now? Average Handle Time (AHT). So, someone calls in and they pass the identity test procedures but I'm still suspicious that might not be them. Do I press for more identification? Unless I'm dead sure it's not them... Heck jo I don't! You want quick calls. You gave a test procedure. They passed. I'm giving you your quick call. You can have me be thorough or quick, you chose quick.&nbsp;</div><div><br></div><div>Business owners, pastors, leaders... What are you seeing in your culture that you don't like? I guarantee YOU are incentiviving that culture.&nbsp;</div><div><br></div><div>You won't change it be yelling, or lecturing. You'll only ever change it by changing the incentives, including what you use to measure "success".&nbsp;</div><div><br></div><div>Selah</div>