---
title: 'What does it mean to “abide” and “bear fruit”? A look at John Chapters 13-17, and Jesus’ final instructions.'
date: '2021-02-08T18:24:00.0030000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3484842491400359689'
blogger_filename: '/2021/02/what-does-it-mean-to-abide-and-bear.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musings'
  - 'Studies'
---

<p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">ABIDE. Be Fruitful. Jesus’ final instructions to his disciples, and us. What do they mean? A look at John 14-17</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;"><br /></p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;"><br /></p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">DQ10: "Abide in ME"</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in 0in 0in 0.375in;"><span style="font-weight: bold;">Prepare</span>: Read John 14-17 and the accompanying "Abiding" articles.</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in 0in 0in 0.375in;"><span style="font-weight: bold;">Participate</span>: Describe what it means to "Abide in Christ" and describe those relationships expressed by Jesus in His teachings and prayers. &nbsp;What did the Holy Spirit reveal to your heart?&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">Repeat patterns are one Hebraic way of emphasizing a point. We see several such patterns in these passages (John Chapters 14-17).</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">Abide IN: Jesus is in the father, the father is in Jesus, the Holy Spirit is in us, we are in them, we are to be united with them and each other. There is a co-unity theme throughout these passages. God WITH Us.</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">Do My Words: IF you love me, do my words. As he will later tell Peter (feed my sheep) (John 21). His words, commands, teachings, all revolve around loving well. Love God. Love each other. Serve each other. Cast no stone. Summarized in John 16:23-28.</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">Results: Do works like I did and greater. Ask and it will be done. Bear Fruit.&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">The Original Testament is the context for the New Testament. Bearing fruit, to a Hebrew ear, should harken back to the commands to Adam (Genesis 1:28), Noah (Genesis 9:1), Abram (Genesis 12:1; 14:19-20; 17:6), Isaac (Gen 26), Jacob/Israel (Gen 29, 35:11), and others. Be Fruitful. Multiply. To be fruitful is to multiply. Therefore, to Bear Fruit in Jesus is to multiply his spirit in others. Although we cannot save anyone, we can testify of his goodness. Throughout the section, The Holy Spirit is seen as helping on this mission, and convicting the world of sin, righteousness and judgement. The section begins by tying this together: I loved you, you love one another, the world will see that love and know you are mine (John 13: 34-35).&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">Therefore, to abide is to allow his love for you to run through you to others The fruit of that lifestyle is the replication of his love in others and through them to others. We together, multiply his love throughout the world, ever increasing, until the day he returns to take us (individually) to be with him (death) or the day he returns (corporately) to be with us here on Earth (resurrection).&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">It’s not our job to convict the “world” of sin, that’s the Holy Spirit’s job (John 16:7-11). Our job it to be love and then love as we are loved.&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">There really is only one mission. God love us, we abide in his love, we share that loved as an overflow with others until we leave or he comes.&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">Probing Deeper:</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">Eternal Perspective: John 14 begins by showing me that if I will keep my eyes on the ultimate outcome (being at home in the Father’s house, in heaven, and eventually on earth after the resurrection), it will keep my heart stable and untroubled. I can be at peace despite the turbulence of this life.&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">Although the ultimate goal will be the physical reunion of The Church, Jesus, and His Father; the intermediate goal is “union”. Even though Jesus left, he never stopped being Emanuel, God WITH Us. He repeats this theme of “I will come to him”, “I will make myself known to him”, “They will be one with us”.&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">His Love &amp; Word: He makes it clear that those who LOVE Him will live by His words, instructions, teachings, and commands. Where I (and much of Church history) miss his heart in this, is paying close attention to what that means. This is no rigid following of religious rules (the church I grew up in was like this). He is not making a new class of Pharisees. The Hebraic “Law” was “Wisdom Teachings”, instructions for living well. His “commands”, his “teachings”,&nbsp;&nbsp;were things like “Love God. Love your neighbor. Neither do I condemn you, go and sin no more.” His lifestyle was his teaching. Sadly, I have all too often focused on “do this good” or “don’t do that bad”, which are dead works from the Tree of Knowledge. The Tree of Life is a tree of loving people through His spirit, which changes people from the inside out, not the outside in. In 15:12, Jesus says “THIS is my command: Love one another”. We are often guilty of obeying commands he did not give (don’t smoke, don’t watch those movies, etc.) but not obeying the primary commandment he did give: “Love one another”.&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">Abide: The phrase is compared to a vine. As a vine cannot live without being connected to the root system, with the life flowing from the root; we cannot “live” without the LIFE of God flowing through us. Abide, in this sense, takes us back to Eden, in the Tree of LIFE. It is not important WHAT we “know” (wrong tree) as much as it is important WHO we are connected with (Jesus, Father, Spirit, Tree of LIFE).&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">Ask/Receive: Another fascinating repeated pattern is his desire that we “ask the Father.. He will do it”, and the references to works and manifesting Jesus (John 14: 12-13; 21; 15:7; 16:23-28). If we are loving God, loving Jesus, listening to his words spoken by His Spirit to our spirit, loving one another… then our desires will be aligned with His desires, we will ask and he will do what we ask. This is not about self satisfaction, though it satisfies our hearts.&nbsp;&nbsp;James makes it clear that we don’t have because we either do not ask or we ask with selfish motives (James 1). We must abide first, which includes love of Him and his word and his people; then after we are aligned with his desires, we can ask. Our desires will be his desires, and he will do what we ask. He will heal, move mountains, and perform miracles confirming our words. Study the requests of the apostles to see what they asked for, it was almost always “others” or “mission” centered.&nbsp;&nbsp;&nbsp;</p><p style="-webkit-text-size-adjust: auto; font-family: Calibri; font-size: 11pt; margin: 0in;">&nbsp;</p>
<br />
<br />
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
