---
title: 'Notes from the: Church InTension Podcast May 26'
date: '2021-08-12T17:03:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '2076669544530237339'
blogger_filename: '/2021/08/notes-from-church-intension-podcast-may.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Studies'
---

<div class="WordSection1">  <p class="MsoNormal">While listening to this podcast episode, I was struck by how much was relevant to my own life. Whether at work, school, online chatrooms, and especially in my closest relationships, these principles are foundational to healthy interactions and healthy community.</p><p class="MsoNormal">Here are the highlights from my notes, but you'll have to listen to the episode for details and context:</p><p class="MsoNormal"><b><u>Church InTension Podcast May 26<o:p></o:p></u></b></p>  <p class="MsoNormal"><a href="https://church-intension.simplecast.com/episodes/title">https://church-intension.simplecast.com/episodes/title</a></p>  <p class="MsoNormal"><i>with Hrishi Baskaran (Leaders in Tension: The Difference between Transparency and Vulnerability / Church InTension Podcast May 26)<o:p></o:p></i></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><i>Four Leadership Issues</i></b></p><p class="MsoNormal">*Transparency over Vulnerability/Invulnerability</p><p class="MsoListParagraph" style="text-indent:-.25in;mso-list:l1 level1 lfo2"><o:p></o:p></p>  <p class="MsoListParagraph" style="text-indent:-.25in;mso-list:l1 level1 lfo2">*Conflict over harmony<o:p></o:p></p>  <p class="MsoListParagraph" style="text-indent:-.25in;mso-list:l1 level1 lfo2">*Clarity over Certainty<o:p></o:p></p>  <p class="MsoListParagraph" style="text-indent:-.25in;mso-list:l1 level1 lfo2">*Accountability over Popularity <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><u>Transparency over Vulnerability/Invulnerability<o:p></o:p></u></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><i>Invulnerability</i></b>: I can’t let anyone see my failures or lacks. I have to look like I have all the answers. I have to look confident so that they will feel hopeful about the future.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><i>Vulnerability</i></b>: “Hey, you know, I failed to do x.” Shows you have weakness, but doesn’t involve any risk.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><i>Transparency</i></b>: “I failed to do X because of Y.” Gives enough detail that someone can judge your character, involves risk.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><u>Conflict over harmony<o:p></o:p></u></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><i>Harmony</i></b>: Is created through an environment of healthy conflict. You must confront and be confrontable.<o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><u>Clarity over Certainty<o:p></o:p></u></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><i>Decision Making:</i></b> “The key is not to come to a place of certainty, per se. The key is to come to a place of clarity and closure.” Hrishi Baskaran  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">We don’t abandon decisions, we just make new ones based on new data points.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><i>Leadership Myths: <o:p></o:p></i></b></p>  <p class="MsoListParagraph" style="text-indent:-.25in;mso-list:l0 level1 lfo1"><!--[if !supportLists]--><span style="mso-list:Ignore">1.<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span><!--[endif]-->I can have all the information.<o:p></o:p></p>  <p class="MsoListParagraph" style="text-indent:-.25in;mso-list:l0 level1 lfo1"><!--[if !supportLists]--><span style="mso-list:Ignore">2.<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span><!--[endif]-->Everyone is eventually going to agree.<o:p></o:p></p>  <p class="MsoListParagraph" style="text-indent:-.25in;mso-list:l0 level1 lfo1"><!--[if !supportLists]--><span style="mso-list:Ignore">3.<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  </span></span><!--[endif]-->We can decide not to decide, which is a decision. <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><i>Planks</i></b>: Walk a plank on the floor or 100s of feet in the air. Skill is the same, but the risk and consequence of failure is exponentially higher.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">In the pursuit of certainty, many of us go through life artificially inflating the risk in our minds.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">We need to come to clarity and closure, we’ll never have certainty.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal"><b><u>Accountability over Popularity <o:p></o:p></u></b></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">We feel that we will influence people better if they “like us”. Real leaders are interested in pressing into conflict so that it lifts the people up to a higher level of ability and performance.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">I want to see you be your best, and I am willing to come into conflict with you and challenge you in order to lift you up to another level.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">We have a responsibility to speak TRUTH in LOVE. At the sake of my popularity, and desire for harmony, and risk of exposing myself, I must confront you for the benefit of the organization and for your growth.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">If you have to let someone go, they will know it is coming and agree with the decision.  <o:p></o:p></p>  <p class="MsoNormal"><o:p>&nbsp;</o:p></p>  <p class="MsoNormal">For more on Hrishi Baskaran, see: <o:p></o:p></p>  <p class="MsoNormal"><a href="https://www.tablegroup.com/">https://www.tablegroup.com/</a></p><p class="MsoNormal"><br></p><p class="MsoNormal"><br></p></div>  