---
title: 'Superman brings Freedom?'
date: '2022-01-08T17:58:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '684118984637365854'
blogger_filename: '/2022/01/superman-brings-freedom.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Creative Writing Guild'
---

<p></p><p></p><p>*Dreams are weird… Let me tell you about the one I had this morning. While I could theologize it, I think I'm just going to let it do it's own work. Enjoy.&nbsp;</p><p><br /></p><p style="text-align: center;">***<br /></p><p><br />The zing of metallic sulfur hung in the air after the warning shots had been fired into a nearby parked car. <br /><br />Clark’s stomach turned in knots at the decision in front of him. <br /><br />Lex Luther had Louse Lane and Jimmy on their knees to each side of him, just in front. He fired the warning shots to make sure he had Clark’s full attention. He was wearing Kryptonite, large and obvious, in a necklace, but that was just for show. The cars up and down the streets were holding it in their open trunks, ensuring Clark would be weakened upon approaching the scene from any reasonable distance.<br /><br />“Well, Superman, or should I say Clark,” Lex said via loudspeaker. “This is how it ends.” He cracked a nauseating smile. <br /><br />Lex had figured out Superman’s secret identity and issued the challenge via live media coverage.<br /><br />“I mean, with facial recognition programming what it is now, the average computer Geek probably would’ve figured this out by now.” Clark quipped to his boss, Perry White, as they watched the scene live from the news van, just before Clark walked out and down the street. “If I ever decided to have a private life, it would take wearing masks, and those are so uncomfortable.” <br /><br />Perry offered a sympathetic laugh. <br /><br />Clark made a decision, his stomach tension eased, but the sense of dread over the outcome of this decision crept up his spine, and crawled on his skin. <br /><br />“It’s been nice knowing you Perry. I’m sorry for the way things are about to turn out.” Clark offered a weak smile, set his glasses down on the table, nodded, and walked out of the van onto the street. <br /><br />Hundreds had left their buildings to huddle in the street, thousands watched from windows in the towering metropolis high-rises. <br /><br />TV cameras were covering the scene from every angle, Lex had called in the media before announcing to the world he would take down superman. <br /><br />The plan was ingenuous, really. <br /><br />Simple. <br /><br />Elegant. <br /><br />Unable to approach without being weakened, he would be incapable of saving both. Theoretically, he could fly fast enough that he could snatch one before the bullet reached them and the Kryptonite would affect his abilities. But, he could never reach both in time. They were too far apart for him to get both, and he couldn’t stop and pivot without loosing the momentum and having the Kryptonite trap him there. <br /><br />The arm-chair quarterbacks would watch this footage a thousand times and come up with solutions that Clark hadn’t considered, but he was under pressure, time was of the essence, and he had enough of this. <br /><br />“Enough!” Clark yelled loud enough for the whole block to hear. As he walked down the street, he tore off his white dress shirt for the last time, buttons ripped and flew as he would never need it again. Underneath his suit was the iconic Superman uniform. He ripped the sleeves from this uniform too, and ripped the iconic S in half. The S stood for “hope” on Krypton, but hope died this day. <br /><br />Hope for a better world…<br /><br />Hope for a world in which he could love his enemies, just like the Prophet had asked many years ago, according to his mother. <br /><br />Hope that he could just arrest all the bad men, when they would just get out on technicalities. <br /><br />Hope… died in Clark that day. <br /><br />It was time for a new tact, one he had intentionally and publicly and proudly avoided for his entire season as “Superman”. <br /><br />Men like Lex Luther would keep cropping up, and the failed Justice Systems would keep letting them out, or letting them operate their empires from within the Prison walls. No, it was time for a new Justice. <br /><br />Not everyone would understand, but that didn’t matter anymore. <br /><br />Someone may succeed in stopping him one day, but he was going to clean up the world’s scum. <br /><br />“So…” Lex said, “Which is it going to be? Are you going to choose Louise or Jim- .” But his voice was cut short.<br /><br />Lex looked down in horror, both hands had been removed by lazer beams from Superman’s eyes. <br /><br />He fell to the ground in pain. <br /><br />“Lex, the world doesn’t need you, it never did. And I’m done offering you chances to repent.” Clark turned to a nearby camera, looked straight into the lens, “Every last criminal on earth, anyone who has caused another pain, I’m coming for you next.”<br /><br />Then, turning back in Lex’s direction, Clark let out a single blast of from his eyes.<br /><br />Lex’s eyes opened wide, gasping, but no sound came from his mouth. A huge hole where his chest once stood, and a breath later, he slumped over and fell to the ground. <br /><br />A tear fell from his cheek, as Clark nodded to Louise and Jimmy, and then he took off into the air.<br /><br />He didn’t plan on becoming Emperor Clark that day… <br /><br />Clark&nbsp; strode down the aisle of his fortress, black cape gracing the floor, thinking back to that day, he grabbed the windowsill, sighing at the outcome. He looked over his empire, listening for the slightest sound of mistreatment of one of his citizens. <br /><br />Another tear rolled down his beard, no grayer than it was 300-years ago, remembering Louise’s International Funeral 50-years into his reign. <br /><br />This is how freedom died, to save the world. <br /></p><p style="text-align: center;">****<br /></p><p><br /></p><p><br /></p><p><label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;</p><div id="mc_embed_signup"><form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank"><div id="mc_embed_signup_scroll"><div class="fx-relay-email-input-wrapper"><input class="email" id="mce-EMAIL" name="EMAIL" required="" style="padding-right: 30px;" type="email" value="" /><div class="fx-relay-icon" style="bottom: 0px; right: 2px; top: 0px;"><button class="fx-relay-button" id="fx-relay-button" style="height: 24px; min-width: 24px; width: 24px;" title="Generate new alias" type="button"></button></div></div><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
