---
title: 'Get To Know You Bio'
date: '2024-09-03T06:32:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '106030085423766419'
blogger_filename: '/2024/09/get-to-know-you-bio.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Bio'
---

<h3 style="text-align: left;">I am Darrell G Wolfe, Storyteller, Writer, Thinker, Armchair Theologian, Reconstructing The Way of Yeshua at www.NoHiding.Faith. I hail from North Idaho (near Coeur dAlene).</h3>
<p>I grew up as a pastor’s kid in the Disciples of Christ (DOC), my dad was an alcoholic pastor (MDiv, DMin) turned atheist crack-addict psychologist (MFT). Meanwhile, I was having visions and spiritual experiences as a child that did not match the experiences of others in my circles. After our family left the ministry in 1996 (16-years old for me), I went through multiple expressions and traditions, and landed in the Word of Faith / Pentecostal movement for years (2003-2018).</p>
<p>After a mental health crises and recover in 2016-2017, then loosing my late-wife in 2018, I was spurred by questions my kids and I didn’t have the framework to answer. I finally took the journey I had been avoiding for decades and went to Bible School. I completed my BA in General Christian Studies at The Kings University (TKU) in December 2022.</p>
<p>Recently, after spending time soul-searching, I realized I was answering an awful lot of questions for people about the Bible. I found myself reading biblical scholarship in my free time, and missing my access to EBSCOhost, JSTOR, and other repositories of academic journal articles. I found myself hungry for more. So here I am, at Fuller Theological Seminary, getting a MATS, with very little idea as to whether this will always be a passion-project or if it will ever pivot into a paid career.</p>
<p>Meanwhile, my “tent making job” is a Business Intelligence Analyst (BIA) where I write SQL, Python, and work with Excel, Power BI, and Tableau for a local county agency.</p>
<p>I am remarried to a fellow widow, and together we have six kids ranging 12-27.</p>
<p>Other terms that describe me:</p>
<ul>
<li>AuDHD</li>
<li>INFJ/INTP (INXX)</li>
<li>Clifton Strengths: Intellection, Learner, Ideation, Achiever, Input
<ul>
<li>But I’m curious to see if those changed since 2014, having experienced such a massive upheaval in my own personal growth, AuDHD demasking, etc.</li>
</ul>
</li>
<li>SciFi, Fantasy nerd, recently completed:
<ul>
<li>Wheel of Time</li>
<li>He Who Fights With Monsters</li>
<li>Mistborn</li>
</ul>
</li>
<li>Current Top Favorite Bible Thinkers:
Michael Heiser, Tim Mackie, NT Wright, Mark Nanos, Mark Kinzer, Thorsten Moritz</li>
</ul>
<p>The books that made me:</p>
<p>Bauckham, Richard. <em>Jesus and the God of Israel: God Crucified and Other Studies on the New Testament’s Christology of Divine Identity</em>, n.d. <a href="https://www.amazon.com/Jesus-God-Israel-Testaments-Christology/dp/0802845592">https://www.amazon.com/Jesus-God-Israel-Testaments-Christology/dp/0802845592</a>.</p>
<p>Cloud, Henry, and John Sims Townsend. <em>Boundaries: When to Say Yes, How to Say No to Take Control of Your Life</em>. Updated and Expanded [edition]. Boundaries. Grand Rapids, Michigan: Zondervan, 2017.</p>
<p>———. <em>How to Have That Difficult Conversation You’ve Been Avoiding: With Your Spouse, Adult Child, Family, Boss, Coworker, Friend, Parent or Someone You’re Dating</em>. Boundaries. Grand Rapids, Mich: Zondervan, 2006.</p>
<p>Du Plessis, David. <em>The Spirit Bade Me Go: The Astounding Move of&nbsp; God in the Denominational Churches</em>. Alucha, FL: Bridge-Logos Publishers, 1970.</p>
<p>Du Plessis, David, and Bob Slosser. <em>A Man Called Mr. Pentecost: David Du Plessis as Told to Bob Slosser</em>. Plainfield, N.J.: Logos International, 1977.</p>
<p>Fee, Gordon D., and Douglas K. Stuart. <em>How to Read the Bible Book by Book: A Guided Tour</em>. Grand Rapids, Mich: Zondervan, 2002.</p>
<p>———. <em>How to Read the Bible for All Its Worth</em>. 3rd ed. Grand Rapids, Mich: Zondervan, 2003.</p>
<p>Hamp, Bob. <em>Think Differently Live Differently Keys to a Life of Freedom.</em> Southlake, Texas, USA: <a href="http://bobhamp.com">bobhamp.com</a>, 2016. <a href="https://tdacad.com/product/think-differently-live-differently-book/">https://tdacad.com/product/think-differently-live-differently-book/</a>.</p>
<p>Heiser, Michael. <em>Angels: What the Bible Really Says about God’s Heavenly Host</em>, 2018. <a href="https://search.ebscohost.com/login.aspx?direct=true&amp;scope=site&amp;db=nlebk&amp;db=nlabk&amp;AN=1900613">https://search.ebscohost.com/login.aspx?direct=true&amp;scope=site&amp;db=nlebk&amp;db=nlabk&amp;AN=1900613</a>.</p>
<p>———. <em>Demons: What the Bible Really Says about the Powers of Darkness</em>. Bellingham, WA: Lexham Press, 2020.</p>
<p>———. <em>The Unseen Realm: Recovering the Supernatural Worldview of the Bible</em>. First edition. Bellingham, WA: Lexham Press, 2015.</p>
<p>Kinzer, Mark. “Finding Our Way Through Nicaea: The Deity of Yeshua, Bilateral Ecclesiology, and Redemptive Encounter with the Living God.” <em>Kesher Journal</em> 24 / SUM 210 (2010). <a href="https://www.kesherjournal.com/article/finding-our-way-through-nicaea-the-deity-of-yeshua-bilateral-ecclesiology-and-redemptive-encounter-with-the-living-god/">https://www.kesherjournal.com/article/finding-our-way-through-nicaea-the-deity-of-yeshua-bilateral-ecclesiology-and-redemptive-encounter-with-the-living-god/</a>.</p>
<p>Moraff, Jason. “‘Among My Own Nation’: Reading the Way, Paul, and ‘the Jews’ in Acts within Judaism.” Dissertation, Fuller Theological Seminary, School of Theology, Center for Advanced Theological Studies, 2021.</p>
<p>Nanos, Mark D. “Paul and Judaism, Why Not Paul’s Judaism.” <em>Reading Paul Within Judaism : Collected Essays of Mark D. Nanos, Vol. 1</em>. Part 1 A New Approach to the Apostle Paul as a Torah-Observant Jew. Eugene, OR: Cascade Books, 2017. <a href="https://web.p.ebscohost.com/ehost/ebookviewer/ebook/bmxlYmtfXzE2OTE4MzhfX0FO0?sid=c0e38d84-c9c6-45ca-a253-4921d0fce688@redis&amp;vid=9&amp;format=EK&amp;rid=2">https://web.p.ebscohost.com/ehost/ebookviewer/ebook/bmxlYmtfXzE2OTE4MzhfX0FO0?sid=c0e38d84-c9c6-45ca-a253-4921d0fce688@redis&amp;vid=9&amp;format=EK&amp;rid=2</a>.</p>
<p>Rudolph, David J., and Joel Willitts, eds. <em>Introduction to Messianic Judaism: Its Ecclesial Context and Biblical Foundations</em>. Grand Rapids, MI: Zondervan, 2013.</p>
<p>Sailhamer, John. <em>The Pentateuch as Narrative: A Biblical-Theological Commentary</em>. Library of Biblical Interpretation. Grand Rapids, Mich: Zondervan, 1995.</p>
<p>Scazzero, Peter. <em>Emotionally Healthy Spirituality: It’s Impossible to Be Spiritually Mature, While Remaining Emotionally Immature</em>. Zondervan, 2014. <a href="https://www.amazon.com/Emotionally-Healthy-Spirituality-Impossible-Spiritually/dp/B08SHX5632/ref=sr_1_6?crid=30T0P57ZF972Q&amp;keywords=The+Emotionally+Healthy+church&amp;qid=1643520881&amp;s=books&amp;sprefix=the+emotionally+healthy+churc%2Cstripbooks%2C221&amp;sr=1-6">https://www.amazon.com/Emotionally-Healthy-Spirituality-Impossible-Spiritually/dp/B08SHX5632/ref=sr_1_6?crid=30T0P57ZF972Q&amp;keywords=The+Emotionally+Healthy+church&amp;qid=1643520881&amp;s=books&amp;sprefix=the+emotionally+healthy+churc%2Cstripbooks%2C221&amp;sr=1-6</a>.</p>
<p>Schiffman, Lawrence H., and Chaim Potok. <em>Reclaiming the Dead Sea Scrolls: The History of Judaism, the Background of Christianity, the Lost Library of Qumran</em>. Anchor Yale Bible Reference Library. New Haven, Conn.: Yale Univ. Pr, 2009.</p>
<p>Synan, Vinson. <em>The Holiness-Pentecostal Tradition: Charismatic Movements in the Twentieth Century</em>. 2nd ed. Grand Rapids, MI; Cambridge, U.K.: William B. Eerdmans Publishing Company, 1971.</p>
<p>Tverberg, Lois, and Ann Spangler. <em>Sitting at the Feet of Rabbi Jesus: How the Jewishness of Jesus Can Transform Your Faith</em>. E-Edition via Logos Bible Software. Grand Rapids, Michigan: Zondervan, 2018.</p>
<p>Walton, John H. <em>The Lost World of Genesis One: Ancient Cosmology and the Origins Debate.</em> Westmont: InterVarsity Press, 2010. <a href="https://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=2030851">https://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=2030851</a>.</p>
<p>Welton, Jonathan. <em>Raptureless</em>. 3rd Edition Printing. Place of publication not identified: Bookbaby, 2015. <a href="http://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=4188734">http://public.ebookcentral.proquest.com/choice/publicfullrecord.aspx?p=4188734</a>.</p>
<p>Witherington, Ben. <em>Reading and Understanding the Bible</em>. Oxford ; New York: Oxford University Press USA, 2015.</p>
<p>Wright, N. T. <em>Jesus and the Victory of God</em>. 1st North American ed. Vol. 2 of <em>Christian Origins and the Question of God</em>. Minneapolis: Fortress Press, 1996. <a href="https://www.logos.com/product/37361/christian-origins-and-the-question-of-god-series">https://www.logos.com/product/37361/christian-origins-and-the-question-of-god-series</a>.</p>
<p>Wright, N. T. <em>Surprised by Hope: Rethinking Heaven, the Resurrection, and the Mission of the Church</em>. San Francisco, CA: HarperOne an Imprint of Harper Collins Publishers, 2014.</p>
<p>Wright, N. T. <em>The Day the Revolution Began: Reconsidering the Meaning of Jesus’s Crucifixion</em>. San Francisco, CA: HarperOne an Imprint of Harper Collins Publishers, 2018.</p>
<p>Wright, N. T., and Michael F. Bird. <em>The New Testament in Its World: An Introduction to the History, Literature, and Theology of the First Christians</em>. London : Grand Rapids, MI: SPCK ; Zondervan Academic, 2019.</p>
<p>Yancey, Philip. <em>Where Is God When It Hurts?</em> Grand Rapids, Mich.: Zondervan, 1997.</p>
<p><em>David DuPlessis&nbsp; - “Forgiveness” June 30, 1967&nbsp; Pm</em>. Audio Recording: Posted to YouTube by Jay Hearn, 1967.</p>
<p><em>Prohibition Theology (@prohibitiontheology)</em>. TikTok Channel, n.d. <a href="https://www.tiktok.com/@prohibitiontheology">https://www.tiktok.com/@prohibitiontheology</a>.</p>
<!-- notionvc: 235718bd-6cef-4643-ac97-add596eec27b -->
<br />
<br />
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
