---
title: 'Returning to The Oneness... a spiritual cloud drive?'
date: '2025-09-21T02:18:00.0010000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4964005120774620630'
blogger_filename: '/2025/09/returning-to-oneness-spiritual-cloud.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Musing'
---

My father was a pastor in the Disciples of Christ (DOC) denomination of US-American Churchianity. He had an MDiv and DMin, and pastored ~1978-1996. He got his MFT after becoming an atheist and left the church.<div><br></div><div>I saw the spiritual world a lot as a child, I saw Jesus, I saw a demon, and I saw... Things...&nbsp;</div><div><br></div><div>I became a Fundamentalist, and then a Pentecostal... And then left Churchianity myself. But I never left the core conviction that Jesus was real. All the things I didn't understand and got wrong never really took that conviction away.&nbsp;</div><div><br></div><div>I now know that Genesis 1-11 was written by the biblical authors and redactors as a polemic counter narrative to the Babylonian creation mythologies. I know it was written in exile, and it was NEVER intended to be read literally. The earth is billions of years old and multiple types of hominids roamed this planet and even interbred before Homo Sapiens became the last hominids. We created cultures starting about 200,000 years ago, maybe as long as 500,000... Evidence evolving on our understanding of that ancient past.&nbsp;</div><div><br></div><div>But the core conviction that Jesus died and rose again, and is, and I am returning to him when I die, and might be coming back never leaves me.&nbsp;</div><div><br></div><div>Quantum physics creates a whole other path to pondering bigger ideas too...&nbsp;</div><div><br></div><div>And then I think about other creation mythologies, like the various Indigenous Americans have, and I wonder ....&nbsp;</div><div><br></div><div>This got me thinking about Cloud Drives, Google Drive, One Drive, Box...&nbsp;</div><div><br></div><div>When I upload files they don't become nebulous indistinct entities. They stay in their form, and I can reprint them and turn them back into physical documents.&nbsp;</div><div><br></div><div>What if our consciousness is like that, and God is like a Hard Drive?</div><div><br></div><div>Just thinking...</div><div>Darrell Wolfe&nbsp;</div>