---
title: 'Vision & Values'
date: '2023-08-27T20:49:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Meals and Manuscripts (MM) - Working Title'
blogger_status: 'LIVE'
blogger_page_id: '3452876449737376682'
blogger_filename: '/p/vision-values.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Meals and Manuscripts (MM) - Working Title/feed.atom'
---

<h3 style="text-align: left;"><span style="font-weight: normal;">&nbsp;*UNDER CONSTRUCTION*</span></h3><h2><br /></h2><div><a href="https://chat.openai.com/share/dc72d84e-38c6-49a4-a491-23900810a45c" rel="nofollow" target="_blank"><b>Conversations with Chat GPT about this idea.</b></a></div><h4 style="text-align: left;">Tagline: In a nutshell</h4><div><div><blockquote><b>Gather &gt; Eat &gt; Grow Together</b></blockquote></div><div>1. Gather: The Way of Jesus is an invitation into <b><i>community</i></b>.</div><div><br /></div><div>2. Eat: Meals provide an atmosphere that fosters <b><i>authentic</i></b> relationships.</div><div><br /></div><div>3. Grow: We grow horizontally with each other in <b><i>shared</i></b> community, and vertically in prayerful academic <b><i>study</i></b> of the biblical authors.</div><div><br /></div><h4 style="text-align: left;">Vision: We See</h4><blockquote><p style="text-align: left;">We are Jesus People, and we exist to serve as a local expression of 'The Way of Jesus' by creating gatherings centered on building authentic life-long relationships and chosen-family through communal meals, shared time and resources, music, and providing a safe space to re-read the biblical authors in their own original contexts.</p></blockquote><h4 style="text-align: left;">Mission: We Do</h4><div><ul style="text-align: left;"><li><b>Connection</b>: We hold regular get-togethers, both face-to-face and online; scheduling events with time to focus on building real, authentic connections and sparking meaningful conversations.</li><li><b>Meals</b>: We select locations that enrich our community meals and create a family &amp; friends atmosphere, teaming up with local businesses where possible.</li><li><b>Education</b>: We provide easy-to-understand educational materials (ours and other’s) to help everyone dive deeper into the Bible's original context; we take advantage of the best of biblical scholarship when and where possible. For educational resources, see our sister site: <a href="https://www.nohiding.faith/p/resources.html" target="_blank">NoHiding.Faith Resources Page</a>.</li><li><b>Resources</b>: We act as a resource hub, directing those who have to give to those who need it (spiritually, physically, financially, etc.).</li><li><b>Continually Adapting</b>: We prioritize adapting as needed to better meet the spiritual and relational needs of our community; always choosing authenticity over tradition.</li></ul></div></div>