---
title: 'Daily Quite Time Guide'
date: '2017-04-24T18:59:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_page_id: '4055708392342025142'
blogger_filename: '/p/daily-routine.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<p><br /><i> The following is an outline I have used for my daily/morning routine. I don't follow it to the letter each and every time. This is more like a guideline, to help steer me along. I've found it quite useful. Feel free to do some, none, all, or out of order. These are just items on the menu, not rules to which one must adhere.</i><br />&nbsp;</p><h3 style="text-align: left;">Mindset (Renew your mind)</h3><p>If your mindset is skewed, you will turn the following into dry religious duties. If that is your perception, stop. Right now. Read this first.</p><p>An amputee with a leg missing below the knee, will often still feel the missing leg. This is known as “phantom limb syndrome”. Taking pain pills or anti-itch medicine can serve to strengthen the mind’s perception that the limb is in fact still present and itching/hurting when it is actually not even there.</p><p>One tool that is being used with amputees is to begin to exercise the new nerve endings. They will rub soft, hard, hot, cold, scratchy, smooth, objects over the new limb ending. The idea is to activate the new nerve endings and re-program the brain’s neural connections and “muscle memory” showing that things have changed.&nbsp;</p><p>Without this process, the brain continues to attempt to follow established neural pathways and send misinformation to the rest of the brain/body connection centers.&nbsp;</p><p>And so it is with our Spirit/Body connections. We will often follow default ways of doing life “Do this, Don’t do that”, which flow from the Tree of Knowledge. After entering the Kingdom of God, you no longer need the Tree of Knowledge. Knowledge of Good and Knowledge of Evil are irrelevant. The Tree of the Knowledge of Evil brings death. The Tree of the Knowledge of Good, also brings death. A better knowledge of Good is another path to death, dry religious death.</p><p>You disconnect from a better knowledge of Good by connecting to the Tree of Life (<a href="http://www.darrellwolfe.com/p/got-life.html" rel="nofollow" target="_blank">Got Life?</a>) by entering into LIFE promised through knowing Jesus.&nbsp;</p><p>As you go about the following activities, do not think of them as things you “must do” to be right with God or gain his approval or even gain victory of sin. All of those come from the Tree of Knowledge, from a better Knowledge of Good.</p><p>Rather, think of these activities as ways to scratch the new nerve endings. You are a spiritual amputee. You’ve been cut off from dead works and dead mindsets. You have LIFE flowing through you now. But you still have old patterns that take you to the missing limb. These activities are just tools to help you scratch the new nerve endings, to discover LIFE inside of you, and connect with that LIFE (Jesus/Father/Holy Spirit).&nbsp;</p><p>Go ahead, scratch the new limb...&nbsp;</p><p><br /></p><h3 style="text-align: left;"> Daily Routine</h3><h3 style="text-align: left;">&nbsp;</h3><h4 style="text-align: left;"> 1. BE STILL</h4><p></p><p>Just Listen, write down what He tells you.&nbsp;</p><p> What is God saying today?&nbsp;</p><p>What's on His heart today?&nbsp;</p><p>Is he bringing a thought, image, song, directing you to look at an <a href="https://biblehub.com/proverbs/6-6.htm" rel="nofollow" target="_blank">ant hill</a>?&nbsp;</p><p><i>Go with it, follow His lead. <br /> </i><br /> <br /></p><h4 style="text-align: left;"> 2. PRAYER</h4><p>This is the time I do some talking, but still listening also.&nbsp; <br /> <br /> <a href="https://biblehub.com/context/1_timothy/2-1.htm" rel="nofollow" target="_blank"></a></p><blockquote><i><a href="https://biblehub.com/context/1_timothy/2-1.htm" rel="nofollow" target="_blank">1 Timothy 2</a><a>: 1-8 </a>- First of all, then, I urge that <b>entreaties </b>and <b>prayers</b>, <b>petitions </b>and <b>thanksgivings</b>, be made on behalf of all men, for kings and all who are in authority, so that we may lead a tranquil and quiet life in all godliness and dignity. This is good and acceptable in the sight of <b>God our Savior, who desires all men to be saved and to come to the knowledge of the truth</b>. For there is one God, and one mediator also between God and men, the man Christ Jesus, who gave Himself as a ransom for all, the testimony given at the proper time. For this I was appointed a preacher and an apostle (I am telling the truth, I am not lying) as a teacher of the Gentiles in faith and truth. Therefore I want the men in every place to pray, lifting up holy hands, without wrath and dissension.</i></blockquote><p></p><p><br /><br />Here's the types of things Paul instructs Timothy to tell his church to pray about/for:<br /></p><ul style="text-align: left;"><li> <a href="https://draft.blogger.com/#">Entreaties </a>(specific felt need), </li><li> <a href="https://draft.blogger.com/#">Prayers </a>(exchange of desires/wishes), </li><li> <a href="https://draft.blogger.com/#">Petitions/Intersessions</a> (Intersection of heaven and earth, hit the bullseye, request something specific of a King. Technical/Civil term: VERY specific requests that meet an exact need!). </li><li> <a href="https://draft.blogger.com/#">Thanksgivings</a> ( Lit: giving thanks for God's grace! Gratitude, Thankfulness)&nbsp;</li></ul><p><br />God's will is for everyone:<br /></p><ul><li>To be repent and be saved (<a href="https://draft.blogger.com/#">2 Peter 3:9</a>).</li><li>Be saved and come to the knowledge of the Truth (<a href="https://draft.blogger.com/#">1 Timothy 2:4</a>).</li><li>Filled with the knowledge of His will through all Wisdom (<a href="https://draft.blogger.com/#">Col 1:9).</a> </li><li>Be given the Spirit of Wisdom and revelation in the knowledge of Him. (<a href="https://draft.blogger.com/#">Eph 1:15-23</a>) </li></ul><p><i>*Yes, Calvinists, every human being on earth past present and future.</i><br /> <br /></p><h4 style="text-align: left;"> 3. BIBLE </h4><p>There are many ways to read the Bible, here are two of my favorites:</p><ul style="text-align: left;"><li><b>Read. Just read.&nbsp;</b></li><ul><li>Read it like a book/novel. Don't dissect it, parse it, pull it apart. Just read the text as though it were a novel or letter or story. <br /></li><li>Get a reader bible, or change the settings on your app to remove verses and headers. One great reader bible is the Messiah edition (<a href="https://www.tyndale.com/sites/immersebible/messiah/" rel="nofollow" target="_blank">here</a>).&nbsp;</li><li>Take some notes, what did you get out of reading today? <br /></li></ul></ul><p>&nbsp;</p><ul style="text-align: left;"><li><b>Study</b>.&nbsp;</li><ul><li>This is the time to pull it apart, dissect, etc.&nbsp;</li><ul><li><b>Words</b>: Look up Words, what do they mean, check for scholars who did reviews of the word's usage in the original language.&nbsp;</li><li><b>Phrasing</b>: Could another phrasing have been used? Why was this one used? NET Bible is especially helpful for this.&nbsp;</li><li><b>Background</b>: Culture, Neighbors, Geography, History, all play a role in helping understand what is being said. Don't just rely on what something means in the 21st century, find out what the author and original audience understood it to mean, you may be surprised.<br /></li></ul><li><b>&nbsp;Use tools</b></li><ul><li><a href="https://biblehub.com/interlinear/2_peter/3-9.htm" rel="nofollow" target="_blank">BibleHub's Interlinear</a></li><li><a href="https://www.blueletterbible.org/" rel="nofollow" target="_blank">Blue Letter Bible's search</a></li><li><a href="https://netbible.org/bible/Exodus+32" rel="nofollow" target="_blank">NET Bible with Full Notes</a></li><li><a href="https://www.logos.com/basic?utm_medium=partner&amp;utm_source=nakedbible" rel="nofollow" target="_blank">Logos Bible Software (Free Version available)</a>&nbsp;</li><li><a href="https://www.bible.com/bible/90/GEN.1.LEB" rel="nofollow" target="_blank">The Lexham English Bible</a><br /></li></ul><li><b>Commentaries</b>:&nbsp;</li><ul><li>Although some commentaries are good, commentaries can be distracting. If it's a devotional commentary, tell you how to apply it life, this is okay and possibly helpful.&nbsp;</li><li>More helpful, are commentaries that interact with the text, tell you what the Ancient Near East or 2nd Temple Period culture would understand a text to mean. Not all commentaries are created equal. Look for ones that do the hard work.&nbsp;</li><ul><li>The Dictionary of Jesus and the Gospels is a good example. Available through Logos Bible Software or <a href="https://www.amazon.com/Dictionary-Jesus-Gospels-IVP-Bible/dp/0830817778" rel="nofollow" target="_blank">Amazon</a>.&nbsp;<br /></li></ul></ul></ul></ul><p> <br /> <br /></p><h4 style="text-align: left;"> 4. JOURNAL</h4><ul style="text-align: left;"><li>What's Up Today? </li><li> How you are feeling?</li><li>This is where you take stock of your emotional state. Is there something that you should re-write? </li><li> How you are believing: </li><li> Are you EXPECTING the right things? </li><li>What's happening in your life right now?</li><li>Take stock of what's happening. Even seemingly boring stuff, that comes to mind. The weather, garden, kids, work, etc... big, small, doesn't matter. What's happening TODAY, and/or, recently, or is about to happen? </li></ul><p>  <br /> The End... go about your day! </p>