---
title: 'Affiliate Disclosure: Disclosure of Material Connection'
date: '2018-04-28T20:15:00.0010000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_page_id: '5856186985419661710'
blogger_filename: '/p/affiliate-disclosure-disclosure-of.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<h4>
*Disclosure of Material Connection:</h4>
Some of the links on this page are “affiliate links.” This means if you click on the link and purchase the item, I will receive an affiliate commission. I may also have received one or more of the products or services mentioned above for free in the hope that I would mention it on my blog.<br />
<br />
Regardless, I only recommend products or services I use personally and believe will add value to my readers.<br />
<br />
I am disclosing this in accordance with the Federal Trade Commission’s&nbsp;<a href="http://www.gpo.gov/fdsys/pkg/CFR-2003-title16-vol1/content-detail.html">16 CFR, Part 255</a>: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.” A Big Thank You to&nbsp;<a href="http://michaelhyatt.com/five-ways-to-comply-with-the-new-ftc-guidelines-for-bloggers.html">Michael Hyatt</a>&nbsp;for helping us Bloggers with these new legal disclosure requirements.<br />
<br />
<blockquote class="tr_bq">
<i>As iron sharpens iron, so one person sharpens another. (Proverbs 27:17 NIV)</i></blockquote>
<br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span></div>
