---
title: 'Personal, Spiritual, and Professional Growth'
date: '2018-04-28T20:36:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_page_id: '4677077098914255326'
blogger_filename: '/p/personal-and-spiritual-growth.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<h3>
Personal, Spiritual, and Professional Growth</h3>
<br />
<h4>
Podcasts, Blogs, Ministries, and Thought Leaders</h4>
<div>
Here are the people/ministries/websites I listen to and/or read most often (in no particular order):<br />
<br />
<h4>
LIFE changing messages</h4>
<ul>
<li><a href="https://www.churchofthehighlands.com/media/message/living-the-crucified-life">Living the Crucified Life</a>, Pastor Chris Hodges, Church of the Highlands, AL&nbsp;</li>
<li><a href="http://bobhamp.com/category/foundations-of-freedom/">Foundations of Freedom,</a>&nbsp;Bob Hamp&nbsp;</li>
<li>Lake City Church:&nbsp;<a href="http://lakecity.church/paul-young/">Guest Paul Young's Story (2014)</a>&nbsp;</li>
<li>Check out Elevation Church; Pastor Steven Furtick's "Functional Faith Series:&nbsp;</li>
<ul>
<li><a href="http://elevationchurch.org/sermons/functional-faith/">Functional Faith</a>&nbsp;</li>
<li><a href="http://elevationchurch.org/sermons/the-frame-game/">The Frame Game</a>&nbsp;</li>
<li><a href="http://elevationchurch.org/sermons/it-is-what-it-is-but-its-not-what-it-seems/">It is what it is, but it's not what it seams</a>&nbsp;</li>
<li><a href="http://elevationchurch.org/sermons/the-seed-is-on-schedule/">The Seed is on Schedule</a>&nbsp;</li>
<li><a href="http://elevationchurch.org/sermons/the-test-and-the-blessing/">The Test and The Blessing</a>&nbsp;</li>
<li><a href="http://elevationchurch.org/sermons/are-you-headed-in-the-right-direction/">Are you headed in the right direction?</a>&nbsp;</li>
<li><a href="http://elevationchurch.org/sermons/handle-it/">Handle It!</a>&nbsp;</li>
</ul>
<li>Gateway Freedom Ministries Links&nbsp;</li>
<ul>
<li><a href="http://gatewaypeople.com/ministries/freedom?campus=45">Gateway Church - Freedom Ministries</a>&nbsp;</li>
</ul>
</ul>
<h4>
Blogs/Podcasts/Ministries</h4>
</div>
<div>
Blogs<br />
<ul>
<li><a href="http://michaelhyatt.com/">Michael Hyatt</a>&nbsp;</li>
<li><a href="http://www.smartpassiveincome.com/">Pat Flynn: Smart Passive Income</a>&nbsp;</li>
<li><a href="http://goinswriter.com/">Jeff Goins</a>&nbsp;</li>
<li><a href="http://sethgodin.typepad.com/">Seth Godin</a>&nbsp;</li>
<li><a href="http://www.helpingwritersbecomeauthors.com/podcasts/">Helping Writers Become Authors&nbsp;</a>(KM Weiland)&nbsp;</li>
</ul>
<br />
Podcasts<br />
<ul>
<li><a href="http://philvischer.com/">Phil Vischer</a>&nbsp;Podcast&nbsp;</li>
<li><a href="http://bobhamp.com/category/foundations-of-freedom/">Foundations of Freedom,</a>&nbsp;Bob Hamp&nbsp;</li>
<li><a href="http://www.helpingwritersbecomeauthors.com/podcasts/">Helping Writers Become Authors&nbsp;</a>(KM Weiland)&nbsp;</li>
<li><a href="http://www.smartpassiveincome.com/podcasts/">Smart Passive Income (Podcast)</a>, Pat Flynn&nbsp;</li>
<li><a href="https://1daybb.com/">1 Day Business Breakthrough</a>, Pat Flynn &amp; Chris Ducker&nbsp;</li>
</ul>
<br />
Ministries/Podcasts<br />
<ul>
<li><a href="http://gatewaypeople.com/ministries/freedom-kairos/media1">Gateway Church</a>&nbsp;(Pastor Robert Morris)&nbsp;</li>
<li><a href="http://www.kcm.org/">Kenneth Copeland Ministries</a>&nbsp;</li>
<li><a href="http://www.pearsonsministries.com/">Jeremy Pearsons</a>&nbsp;</li>
<li><a href="http://www.impactministries.com/Resources/Audio.aspx">Dr. James Richards</a>&nbsp;</li>
<li><a href="http://www.awmi.net/">Andrew Womack</a>&nbsp;</li>
<li><a href="http://www.josephprince.org/">Joseph Prince</a>&nbsp;</li>
<li><a href="http://www.jerrysavelle.org/media/podcast-rss/">Jerry Savelle</a>&nbsp;</li>
<li><a href="http://www.jdm.org/jdmdefault.aspx?tabindex=-1&amp;tabID=297">Jesse Duplantis</a>&nbsp;</li>
<li><a href="http://bobhamp.com/category/foundations-of-freedom/">Foundations of Freedom,</a>&nbsp;Bob Hamp&nbsp;</li>
<li><a href="http://elevationchurch.org/sermons/">Elevation Church</a>, Pastor Steven Furtick&nbsp;</li>
<li><a href="http://lakecity.church/video/">Lake City Church</a>, Pastor Mike Rima&nbsp;</li>
</ul>
<br />
Other Ministries, Thinkers, Radio Shows, Podcasts, Etc<br />
<ul>
<li><a href="http://www.npr.org/programs/ted-radio-hour/">TED Radio Hour, NPR&nbsp;</a></li>
<li><a href="http://johnbatchelorshow.com/">John Batchelor Show</a>&nbsp;</li>
<li><a href="http://www.dennisprager.com/">Dennis Prager Show</a>&nbsp;</li>
<li><a href="http://www.insight.org/">Insight For Living, Chuck Swindoll</a>&nbsp;</li>
<li><a href="http://www.focusonthefamily.com/radio.aspx?">Focus on the Family</a>&nbsp;</li>
<li><a href="http://www.glennbeck.com/content/radio/">Glenn Beck Radio</a>&nbsp;</li>
<li><a href="http://www.daveramsey.com/show/radio/">Dave Ramsey Show</a>&nbsp;</li>
<li><a href="http://www.daveramsey.com/entreleadership/podcast">Dave Ramsey: EntreLeadership Podcast</a>&nbsp;</li>
<li><a href="http://www.rzim.org/let-my-people-think-broadcasts/">Let My People Think, Ravi Zacharias</a>&nbsp;</li>
<li><a href="http://www.truthforlife.org/about/about-alistair-begg/">Truth For Life, Alistair Begg</a>&nbsp;</li>
</ul>
<h4>
Marriage</h4>
Here are some great resources on reducing friction in&nbsp;marriage, and becoming a better husband (or wife).<br />
<ul>
<li>Matthew&nbsp;Fray,&nbsp;writes at&nbsp;<a href="http://mustbethistalltoride.com/about/">MustBeThisTallToRide</a>.&nbsp;</li>
<ul>
<li>MUST READ: "<a href="http://mustbethistalltoride.com/an-open-letter-to-shitty-husbands/">An open letter to shitty husbands</a>."&nbsp;</li>
</ul>
</ul>
<h4>
Overcoming Depression, Building Life Skills</h4>
The following resources helped with general overcoming and life skills, or a change in perspective.<br />
<ul>
<li>Journey 2 Identity (<a href="http://www.j2i.org/">J2I</a>)&nbsp;</li>
<ul>
<li><a href="http://www.j2i.org/blog/how-can-i-help">"How can I help?"; the dreaded question.</a>&nbsp;</li>
<li><a href="http://www.j2i.org/resources.html">J2I's Resource Page</a>&nbsp;</li>
</ul>
<li><a href="http://seth%20adam%20smith/">Seth Adam Smith</a>&nbsp;</li>
<ul>
<li>Writes/Blogs on&nbsp;<a href="http://sethadamsmith.com/suicide-and-depression/">suicide &amp; depression</a>&nbsp;and life&nbsp;an&nbsp;Keep Moving Forward.&nbsp;</li>
<li>He did a video for the Mormon Church: "<a href="https://www.youtube.com/watch?v=rIxttI8tN1I">Sitting on the Bench: Thoughts on Suicide Awareness and Prevention</a>."&nbsp;</li>
</ul>
</ul>
<h4>
Professional Growth &amp; Career Help</h4>
<h4>
<div style="font-weight: 400;">
<ul>
<li><a href="http://money.usnews.com/money/blogs/outside-voices-careers/2011/09/26/how-to-answer-behavorial-interview-questions">How to&nbsp;answer&nbsp;Behavioral Interview Questions</a>&nbsp;</li>
<li><a href="http://blog.timesunion.com/careers/50-behavioral-based-interview-questions-you-might-be-asked/1538/">50 Behavioral Interview Questions</a>&nbsp;</li>
<li><a href="http://www.youtube.com/watch?v=_u9wl3KktY0&amp;list=UU-yC7yCogIwq8m4pDkaz-5A&amp;feature=c4-overview">Lou Adler</a>&nbsp;of the&nbsp;<a href="http://louadlergroup.com/why-we-should-banish-job-descriptions-and-resumes/">Adler Group</a>. You may not know him but any decent hiring manager in a large corporation has been trained under the&nbsp;<a href="http://www.adlerconcepts.com/resources/2001/06/the_best_interview_question_of.php">Adler Interview Method</a>.&nbsp;</li>
<li><a href="http://jobsearch.about.com/od/resumetips/fl/best-resume-tips-2014.htm">2014 Resume Tips</a>&nbsp;</li>
</ul>
<div>
<br /></div>
</div>
</h4>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span><span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
</div>
