---
title: 'Writing StoryCraft Database'
date: '2019-02-26T09:00:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_page_id: '2304655444108369224'
blogger_filename: '/p/writing-craft-database.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

True Story: I didn't know there was a craft to writing, but there IS!<br />
<br />
I tried to write my first story in 2004. It was fascinating for pages, but quickly became linear and went no-where. I figured I must not have what it takes and gave up.<br />
<br />
Later, I had a thought. Subtle, yet profound.<div><br /></div><div></div><blockquote><div><i>Musicians must learn the notes, chords, and structure of music before they can improvise.&nbsp;</i></div><div><i><br /></i></div><div><i>Artists spend years with technique and craft before they impress us and make it look easy.&nbsp;</i></div><div><i><br /></i></div><div><i>I wonder if there's a craft to this creative writing stuff?</i></div></blockquote><div><br />
Well... there is! It's learnable. Here are some of the best Links, Books, Authors, Teachers, Podcasts, Articles, Tools, and anything else I've found helpful to my own writing all in one central link-database.<br />
<blockquote class="tr_bq">
<b><i>Enjoy, Learn, Grow, Study, Write!</i></b></blockquote>
<i>*Update as of 12/24/2023, some of these links are broken and some resources outdated, some are still timeless and amazing. I'll be cleaning up what's here, and adding more in the coming year. When my wife died, June 25, 2018, I couldn't write a word, but now after five years, I'm ready to start again, with a fresh set of perspectives, and a trauma-informed dark humor, and maybe, just maybe a little wisdom. Shalom. PSS: I also know what a database actually is now, so I'm considering building one based on writing, to be determined...&nbsp;</i></div><div><i>*Updated 01/19/2025</i></div><div><i><br /></i></div><div><i><br />
</i><h4>
<u>WRITING CRAFT LESSONS/EDUCATION</u></h4>
<div>
<br /></div>
<div>
<b>Articles by me:</b></div>
<ul>
<li>Article: <a href="http://www.darrellwolfe.com/2017/10/the-w-story-structure-4-sequence-story.html?m=1" target="_blank">The W Story Structure - 4 Sequence Story Structure</a></li>
<ul>
<li>This is the story structure I found to be the perfect balance between Pantser (no structure to start, put it in later) and Outliner (preplan every scene before writing one)</li>
</ul>
</ul>
<ul>
<li>Article: <a href="http://www.darrellwolfe.com/2018/04/writing-craft-show-dont-tell.html" target="_blank">Writing Craft: Show / Don't Tell</a></li>
<ul>
<li>I build a single sentence using show / don't tell. Building layer on layer, showing how you can take the thought you had in the draft, and build it into the final version.</li>
</ul>
</ul>
<ul style="text-align: left;">
<li>Article: <a href="http://www.darrellwolfe.com/2018/04/writing-craft-getting-unstuck.html" target="_blank">Writing Craft: Getting UnStuck</a></li>
<ul>
<li>Several people have asked me to help them get unstuck. Here's one (of many) possible lessons along those lines.</li></ul></ul><ul style="text-align: left;"><li>Article:&nbsp;<a href="https://www.darrellwolfe.com/2025/01/yesand-yesbut-noand-and-nobut-narrative.html">Yes/And, Yes/But, No/And, and No/But: Narrative Tools for Dynamic Storytelling ~ Darrell Wolfe, Storyteller</a></li><ul>
</ul>
</ul>
<div>
<br /></div><div><a href="https://photos.app.goo.gl/GhrMX5cSZiDuALMs6" target="_blank"><b>Writing Notes Google Photos Album</b></a> with helpful thoughts, graphs, reminders, and randomness. -&nbsp;</div><div><br /></div>
<h3 style="text-align: left;"><b>Books, Articles, Authors, Authorities, Podcasts, and more (that are not me):</b></h3><div><b><br /></b></div>
YouTube: <a href="https://youtube.com/playlist?list=PLSbGHx9UCQ8oMXx3aBAZlv-Xf8Xet4dTG&amp;si=kGWesGmXHhy0-1_q" target="_blank"><b>Storytelling Playlist</b></a> (a collection of storytelling help I'm curating for myself and you).<br /><br /><b><u><div><b><u><br /></u></b></div></u></b><h3 style="text-align: left;"><b><u>Author/Teacher/Mentor/Guide/Gurus:</u></b></h3></div><div><br /></div><div><ul><li><b><u><a href="http://www.kmweiland.com/">K.M. Weiland</a>&nbsp;runs a website and podcast called "Helping writers become authors".</u></b></li><ul><li>Website:&nbsp;<a href="http://www.helpingwritersbecomeauthors.com/">http://www.helpingwritersbecomeauthors.com</a>&nbsp;</li><li>Her&nbsp;<a href="http://www.helpingwritersbecomeauthors.com/">Story Structure Database</a>&nbsp;(<a href="http://www.helpingwritersbecomeauthors.com/story-structures/">here</a>) outlines movies and books you've probably read and breaks them down into their story structures. This helps writers understand story structure for the own writing.</li><li><a href="http://amzn.to/2bdYQAL">Structuring Your Novel: Essential Keys for Writing an Outstanding Story Paperback</a>, by K. M. Weiland (Author) -&nbsp;K.M. Weiland (Author)<a href="http://www.helpingwritersbecomeauthors.com/">(Blogger)(Teacher)(Podcaster)</a>&nbsp;is the best teacher of fiction craft I've run into. If you are serious about writing you need to listen to her podcasts and read her blog. She'll give you a Ph.D. in story craft for free through the blog and podcast, the books she writes take you even deeper.</li><li>Podcast: Her podcast by the same name as her website is a MUST listen on a regular basis if you're serious about writing.</li></ul></ul></div><div><b><u><br /></u></b></div><div><b><u><br /></u></b><ul style="text-align: left;"><li>Brandon Sanderson:</li><ul><li>YouTube:&nbsp;<ul><li><a href="https://youtube.com/playlist?list=PLSH_xM-KC3Zv-79sVZTTj-YA6IAqh8qeQ&amp;si=Fp2fUl0X20p2uZoW" target="_blank">2020 Creative Writing Lectures at BYU</a></li><li></li><li><a href="https://youtube.com/playlist?list=PLSH_xM-KC3ZtjKTR2z8rPWxv1pP6bOVzZ&amp;si=Mbjbcv3qBOQ5FVCg" target="_blank">Writing Advice</a></li></ul></li><li>Sanderson's Website:</li><ul><li><a href="https://faq.brandonsanderson.com/knowledge-base/what-are-sandersons-laws-of-magic/" target="_blank">What Are Sanderson’s Laws Of Magic?</a></li></ul></ul></ul><div><ul><li>Book:&nbsp;<a href="http://www.amazon.com/gp/product/0470530707/ref=as_li_ss_tl?ie=UTF8&amp;camp=1789&amp;creative=390957&amp;creativeASIN=0470530707&amp;linkCode=as2&amp;tag=your0f4d-20">Writing Fiction For Dummies</a>, By&nbsp;<a href="http://www.amazon.com/Randy-Ingermanson/e/B001IXMD5S/ref=ntt_athr_dp_pel_1">Randy Ingermanson</a><a href="http://www.amazon.com/Writing-Fiction-Dummies-Randy-Ingermanson/dp/0470530707/ref=as_li_wdgt_ex?&amp;linkCode=waf&amp;tag=your0f4d-20#"></a>&nbsp;and&nbsp;<a href="http://www.amazon.com/Peter-Economy/e/B000APWG16/ref=ntt_athr_dp_pel_2">Peter Economy</a></li><ul><li>MUST READ for any new author. This breaks down every element of a story from structure to character to world-building, in an easy to understand way. Everything became simple after reading this book.</li></ul></ul><ul style="text-align: left;"><li>Site:&nbsp;<a href="http://ingermanson.com/">Randy Ingermanson</a>'s website also offers a ton of help for writers through his blog, including:</li><ul><li><a href="http://www.advancedfictionwriting.com/articles/writing-the-perfect-scene/">How to write a perfect scene</a></li><li><a href="http://www.advancedfictionwriting.com/articles/snowflake-method/">The Snowflake Method</a></li></ul></ul><ul style="text-align: left;"><li>Hilary&nbsp;Layne at&nbsp;&nbsp;<a href="https://www.youtube.com/channel/UCBmqEPwc_8yJB-nhLjm9krw/about">The Second Story - YouTube</a>&nbsp;provides a better way to conceive of progress and a better way to conceive of a "first draft" as more of a sketch than actually "writing" the prose and dialogue and stuff.</li><ul><li><a href="https://www.youtube.com/watch?v=8738WWNvOLs&amp;list=PLSbGHx9UCQ8oMXx3aBAZlv-Xf8Xet4dTG&amp;index=50&amp;t=565s">Subplots Can't Hurt You (Rules, Principles, and Structure) - YouTube</a>&nbsp;</li><li><a href="https://www.youtube.com/watch?v=RmhAGZJOf_o&amp;list=PLSbGHx9UCQ8oMXx3aBAZlv-Xf8Xet4dTG&amp;index=51">Professor Trailer | Rice University Precollege Online Program</a>).&nbsp;</li></ul></ul></div><ul style="text-align: left;"><li>Dan Harmon -&nbsp;<a href="https://www.youtube.com/watch?v=-XGUVkOmPTA&amp;list=PLSbGHx9UCQ8oMXx3aBAZlv-Xf8Xet4dTG&amp;index=30" target="_blank">Story Circle: 8 Proven Steps to Better Stories</a></li></ul><ul style="text-align: left;"><li>Jeff Kitchen -&nbsp;<a href="https://www.youtube.com/watch?v=b2RlPZmz9nc&amp;list=PLSbGHx9UCQ8oMXx3aBAZlv-Xf8Xet4dTG&amp;index=21&amp;t=5809s" target="_blank">First 3 Hours Of Writing A Story (Starting From Nothing) - Jeff Kitchen [FULL INTERVIEW]</a></li><ul>
<ul></ul>
</ul>
</ul>
<ul>
<li>Book:&nbsp;<a href="http://amzn.to/2c6YgCA">Wired for Story: The Writer's Guide to Using Brain Science to Hook Readers from the Very First Sentence</a>, by Lisa Cron (Author) -&nbsp;Mind blown. We are literally wired for story. She breaks down the brain science behind every element of the craft and character creation. I'll never write a "teach you" book again without including story because of this book.</li>
</ul>
<ul>
<li>Site: Lisa Cron, <a href="http://wiredforstory.com/free-resources" target="_blank">WiredForStory.com</a>, check it her amazing resources.</li>
</ul>
<ul>
<li>Ted Talk: <a href="https://m.youtube.com/watch?v=74uv0mJS0uM" target="_blank">Lisa Cron, Wired For Story</a></li>
</ul>
<ul>
<li>Article:&nbsp;<a href="https://writersinthestorm.wordpress.com/2011/12/02/body-language-an-artistic-writing-tool/" target="_blank">Body Language: An Artistic Writing Tool</a>, by <a href="https://writersinthestorm.wordpress.com/2010/05/01/sharla-rae/" target="_blank">Sharla Rae</a></li>
<ul>
<li>The article gives a comprehensive list of ways to SHOW NOT TELL feelings in your characters and writing.</li>
</ul>
</ul>
<ul>
<li>Author/Teacher: <a href="http://www.chrisfoxwrites.com/" target="_blank">Chris Fox</a>, has a <a href="https://www.youtube.com/channel/UCu6RYg6_-pTQxLVq3Fv6lYg/featured" target="_blank">YouTube</a> channel as well as books.&nbsp;</li>
</ul>
<ul>
<li>Video: <a href="https://www.youtube.com/watch?v=o770MEm8s6o&amp;list=PLM1AIkhjcj6cIs7c5qnQvE1_qgTSr5RAi" target="_blank">20 Books to $50K</a></li>
</ul>
<ul>
<li><b>Facebook Groups</b></li>
<ul>
<li><a href="https://www.facebook.com/groups/1582424518747057/" target="_blank">Ninja Writers</a></li>
<li><a href="https://www.facebook.com/groups/writersofnorthidaho/" target="_blank">Writers of North Idaho... And beyond</a>.</li>
</ul>
</ul>
<div>
<br /></div>
<div>
<b>See Also,</b></div>
<ul>
<li>Book:&nbsp;<a href="http://www.amazon.com/gp/product/0898798108/ref=as_li_ss_tl?ie=UTF8&amp;camp=1789&amp;creative=390957&amp;creativeASIN=0898798108&amp;linkCode=as2&amp;tag=your0f4d-20">T</a><a href="http://www.amazon.com/gp/product/0898798108/ref=as_li_ss_tl?ie=UTF8&amp;camp=1789&amp;creative=390957&amp;creativeASIN=0898798108&amp;linkCode=as2&amp;tag=your0f4d-20">he Complete Guide to Writing and Selling the Christian Novel</a>, By Penelope J. Stokes -&nbsp;Gives you insight into this specific niche.</li>
</ul>
<ul>
<li>Book:&nbsp;<a href="http://amzn.to/2byOJkL">On Writing Well: The Classic Guide to Writing Nonfiction 30 Anv Rep Edition</a>, by William Zinsser (Author) -&nbsp;Writing Craft (fiction and nonfiction). Grammar, punctuation, etc.</li>
</ul>
<ul>
<li>Site:&nbsp;<a href="https://onestopforwriters.com/">One Stop For Writers</a>&nbsp;is a website that also has some great resources.&nbsp;</li>
</ul>
<ul>
<li>Book:&nbsp;<a href="http://amzn.to/2bM1o4j">The Elements of Style, Fourth Edition 4th Edition</a>, by William Strunk Jr. (Author), E. B. White (Author) -&nbsp;Writing Craft (fiction and nonfiction). Grammar, punctuation, etc.</li>
</ul>
<ul></ul>
<div>
<br /></div>
<h4>
<u>WRITING CRAFT TOOLS</u></h4>
<b></b><br />
<div>
<b><b>Research It!</b></b></div>
<b> </b><br />
<div>
<ul>
<li><b>ChatGPT-4</b> - (<a href="https://chat.openai.com" target="_blank">https://chat.openai.com</a>) has become invaluable as a research tool. I can ask it specific questions (Would an Officer in the USAF have this skill?) and get targeted responses with links that I can use to read and verify the answers. It also helps me with StoryCraft. I can paste my outline of the story structure, and ask it for plot holes or weaknesses, and it will itemize them!&nbsp;<a href="https://chat.openai.com/g/g-oBrrXepkk-storycraft-editor" target="_blank">https://chat.openai.com/g/g-oBrrXepkk-storycraft-editor</a></li></ul><ul><li><span style="font-weight: bold;"><a href="https://www.notion.so" target="_blank">Notion</a>: (https://www.notion.so) </span>is the new best notes and research tool. There is even more functionality than Microsoft OneNote. I still have all my OneNote research saved, but I'm moving it to Notion.</li></ul><ul><li><span style="font-weight: bold;"><a href="https://site.onenote.com/?public=1&amp;wdorigin=ondcauth2&amp;wdorigin=ondc" target="_blank">Microsoft OneNote</a>&nbsp;</span><i>(Best Notes Tool Ever!) &lt; Until it was replaced by Notion, but keeping this up, it's still useful.</i></li>
<ul>
<li>This is my favorite! I've used Evernote and GNotes, but this just works best for me. It sinks from my Android Phone to my Windows Computer&nbsp;seamlessly. It stores all the notes I could ever want, with links. I wrote the entire first rough draft of my first novel in One Note before moving all of that later to Scrivener.&nbsp;</li>
<li>Writing: I keep research, ideas,&nbsp;plot line&nbsp;ideas, character bios, links to the thousand little things I wanted to put into the story, random ideas, all of it here. It's my digital brain.&nbsp;</li>
</ul>
</ul>
</div>
<b> </b>
<br />
<div>
<b><b><br /></b></b></div>
<b> Write It!</b><br />
<ul>
<li><a href="http://www.literatureandlatte.com/scrivener.php">Scrivener, by Literature &amp; Latte</a>&nbsp;- $40&nbsp;</li>
<ul>
<li>Michael Hyatt (<a href="https://michaelhyatt.com/switched-to-scrivener.html">here</a>) first turned me on to this program. It is absolutely the best thing I've seen for writers who want to publish any book Fiction or Non-fiction. He even uses it for publishing blog posts, and other content.&nbsp;</li>
<li>This program allows me to write my scenes in any order they come to my mind. When it comes to&nbsp;<a href="http://www.helpingwritersbecomeauthors.com/secrets-of-story-structure-pt-1-why/">Story Structure</a>, I'm a&nbsp;<a href="http://www.urbandictionary.com/define.php?term=Pantser&amp;defid=5370740">Pantser&nbsp;</a>or Edit-As-You-Go, not an Outliner. So this tool allows me to move scenes around, re-organize whole sections and see the story through corkboards at every level 1 inch view and 10,000-foot view.&nbsp;</li>
<li>Thanks to Michael Hyatt (and his Affiliate Code:&nbsp;<a href="https://michaelhyatt.com/switched-to-scrivener.html">MICHAELHYATT</a>) I got it at a discount.</li>
</ul>
<li><a href="http://www.spacejock.com/yWriter5.html">yWriter 5</a>&nbsp;- <b>Free </b>(switched to Scrivener, but this got me started)</li>
<ul>
<li>This program pretty much does what Scrivener does, but for free. But being free, it's a bit less User-Friendly. Think "Open Office vs Microsoft Word". They both get the job done, but the user experience is way different. I used yWriter happily until I could afford Scrivener.&nbsp;</li>
<li>This program also has one feature I didn't find in Scrivener (maybe it's there, but I didn't find it), a timeline broken down by POV.&nbsp;</li>
<li>yWriter is a word processor which breaks your novel into chapters and scenes, helping you keep track of your work while leaving your mind free to create. It will not write your novel for you, suggest plot ideas or perform creative tasks of any kind. yWriter was designed by an author, not a salesman!&nbsp;</li>
</ul>
</ul>
<div>
<br /></div>
<div>
<b>Edit It!</b></div>
<div>
<ul>
<li><a href="https://grammarly.go2cloud.org/SHi9">Grammarly</a>&nbsp;- Free and Paid/Month&nbsp;</li>
<ul>
<li>The free version is MORE than I need right now, but in the future, I may start using the paid version. That depends on how much I'm writing, and how much it's paying me.&nbsp;</li>
<li>This is an App/Extension that checks your grammar, in outstanding ways.&nbsp;</li>
<li>There is a Chrome Extension, that checks your grammar from within your browser, no matter what site you are typing on (Facebook Twitter, Comments, Etc.,).&nbsp;</li>
<li>There is a Microsoft Extension for Word and Outlook. I'm using it right now to edit my first novel. I'm seriously considering publishing my first novel without an Editor thanks to Grammarly.</li>
</ul>
<li>Worthy Mentions:</li>
<ul>
<li><a href="http://www.gingersoftware.com/?chnl=gsrch&amp;campaignid=1054143271&amp;adgroupid=52032938552&amp;keyword=ginger%20writing&amp;matchtype=e&amp;gclid=CjwKCAjwq_vWBRACEiwAEReprJBgSZrYQ3emebrGYDpgNStPAE4xulLBzJx_1gUCKMwI-mFonN30ThoCjacQAvD_BwE" target="_blank">Ginger</a>&nbsp;- They have a free Chrome Extension. I'm trying it out now.</li>
<li><a href="https://www.autocrit.com/pages/" target="_blank">AutoCrit</a> - You can paste it into the website for free, but you buy the software. Haven't tried it, but it came recommended by a Writers Group.</li>
<li><a href="http://www.hemingwayapp.com/desktop.html" target="_blank">Hemingway Editor</a> - Also came recommended by a Writers Group. Costs. Haven't tried it yet.</li>
<li><a href="http://www.hemingwayapp.com/" target="_blank">Hemingway App</a> - Same company, just the online version. Paste the text in online and look for errors.&nbsp;</li>
</ul>
</ul>
<div>
<br /></div>
<ul>
<ul>
</ul>
</ul>
<div>
<b>Publish It!</b></div><div><ul><ul>
</ul>
</ul>
<ul style="text-align: left;">
<li><a href="https://kdp.amazon.com/en_US/" target="_blank">Kindle Direct Publishing</a> - is where I publish the Kindle copy of the book.</li>
<ul>
<li>You can upload a word document and it will format it for you. However, it's not quite right that way. Learn a bit about formatting, (Scrivner helps there too) and then upload it. This site puts it into Kindle directly.</li></ul></ul><ul style="text-align: left;">
<li>Bethany Atazadeh - YA Fantasy Author</li><ul><li><a href="https://www.youtube.com/watch?v=sqhDUUMA6YE&amp;t=1051s" target="_blank">Where I Self-Publish My Books (UPDATED for 2023)</a> I self-publish my books through SEVEN different companies:</li></ul></ul><ul style="text-align: left;"><ul><li>Kindle Direct Publishing (KDP), Digital Book &amp; Audio Book</li><li>Draft2Digital (D2D), Digital Book</li><li>Google Play, Digital Book</li><li>Kobo, Digital Book</li><li>Apple Books, Digital Book</li><li>Barnes and Noble Press. Paperback Book</li></ul></ul><ul style="text-align: left;"><ul><li><i>Ingramspark, &lt;&lt;&lt; She, and every other Indie Author, hates this company&lt;&lt;&lt;&lt;&lt;</i></li></ul></ul>
<div>
<br /></div>
<div>
<ul>
<ul>
</ul>
</ul>
</div>
</div>
<div>
<b>Promote and Sell It!</b></div>
</div>
<div>
<ul>
<li><a href="http://www.domain.com/" target="_blank">Domain.Com</a> - is where I buy my domain names. <i>Still true in 2023.</i></li>
<ul>
<li>Someone said, can't recall who, that you shouldn't host the website where you bought your domain name. That way, if you end up in a dispute with the host of the site, you can start a new site (keep that site template saved on your personal cloud somewhere, GDrive?) and go point the domain name to the new site while you are fixing the dispute.</li>
</ul>
</ul>
<ul>
<li><a href="https://blogger.com/">Blogger</a>&nbsp;- This is where my website lives.&nbsp;<i>Still true in 2023.</i></li>
<ul>
<li>This service, offered by Google, will let you build a blog for FREE. It's hands-down the easiest to use. WordPress has a learning curve that is much steeper (and more restrictive) than Blogger.</li>
<li><b>Templates/Design:</b> Blogger comes with some enhanced templates, but I prefer to use another site called <a href="http://maybe%20i%20should%20write%20a%20post%20about%20the%20top%20%2810/?)%20things%20I%27d%20do%20when%20starting%20a%20new%20Blogger%20Blog." target="_blank">BTemplates</a>. I download a template I like from there and upload it to Blogger. Then, I personalize it. I then save a copy of that template to my cloud (GDrive or OneDrive) in case I need it later.&nbsp;</li>
<li><b>Article</b>:&nbsp;<a href="http://www.darrellwolfe.com/2017/10/how-to-use-bloggercom-and-domaincom-to.html" target="_blank">How to use Blogger.Com and Domain.Com to host your Top Level Domain Name for less than $10/Year.&nbsp;</a></li>
<li><b>Article</b>: Maybe I should write a post about the top (10?) things I'd do when starting a new Blogger Blog.</li>
</ul>
</ul><div><br /></div>
<ul>
<li><i><a href="https://gumroad.com/">GUMROAD:</a>&nbsp;- Sell products, name your own price! I don't use this anymore, but it's a fun option.</i></li>
<ul>
<li><i>I can upload a PDF copy of my book and sell that direct from my website to consumers. I can name a price, or allow them to name their own.</i></li>
</ul>
</ul>
<ul>
<li><a href="http://ifttt.com/">IFTT</a>&nbsp;</li>
<ul>
<li>Social Media tool mostly. Let's me automate "If Blogger post, Then Post to Facebook" or whatever I want it to do, it's got 1,000s of options.</li>
</ul>
</ul>
</div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<br /></div>