---
title: 'Book Store: Fiction'
date: '2020-04-01T19:01:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_page_id: '3617856336633846637'
blogger_filename: '/p/fiction.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

*Disclosure of Material Connection: Most of the links on this page are “affiliate links". See the bottom of this page for details.<br /><br /><h2 style="text-align: left;">This page lists a variety of stories (fiction books) that have fed my soul!&nbsp;</h2><div><br /></div><div><b style="font-style: italic;">In 2023 and beyond, I'm using&nbsp;<a href="https://www.goodreads.com/user/show/41133256-darrell-wolfe" target="_blank">GoodReads&nbsp;</a>instead of listing them here. But I'll still some of my favorites here from time to time.</b></div>
<h4>
There's nothing like a story.</h4>
Stories inspire our hearts to believe in the impossible, breaking past the barriers our minds create. We read nonfiction with the eye of the skeptic, but for a good story, we willingly suspend disbelief and allow our hearts to dream again. In so doing, we often learn truths our minds were afraid to face. Here are some of my favorite authors who also pack powerful Truths inside their pages.<br /><div><div><br /></div><div><br /></div><div><a href="https://www.goodreads.com/author/show/38550.Brandon_Sanderson?from_search=true&amp;from_srp=true" target="_blank"><b>Brandon Sanderson</b></a></div><div><span>&nbsp;&nbsp; &nbsp;</span><span>&nbsp;&nbsp; &nbsp;</span>The Final Empire (Mistborn, #1)</div><div><br /></div><div><a href="https://www.goodreads.com/author/show/108424.Patrick_Rothfuss?from_search=true&amp;from_srp=true" target="_blank"><b>Patrick Rothfuss</b></a></div><div><span style="white-space: normal;"><span style="white-space: pre;">	</span>The Name of the Wind (The Kingkiller Chronicle, #1)</span></div><div><br /></div><div><a href="https://www.goodreads.com/author/show/6252.Robert_Jordan" target="_blank"><b>Robert Jordan</b></a></div><div><span style="white-space: normal;"><span style="white-space: pre;">	</span>The Eye of the World (The Wheel of Time, #1)</span></div><div><br /></div>
<div><br /></div><b><u><a href="https://www.goodreads.com/author/show/1441.Ted_Dekker" target="_blank">Ted Dekker</a></u></b></div><div><br /><a href="https://draft.blogger.com/#">Hacker: The Outlaw Chronicles</a>&nbsp;by Ted Dekker (Author) The story of a young Hacker girl, who went on a wild adventure into the supernatural realm beyond trying to save her mom, but saved herself too in the process.&nbsp;</div><div><br /><a href="https://draft.blogger.com/#">Saint: A Paradise Novel (here)</a> by Ted Dekker (Author) He's an assassin, or is he? He finds a secret to his past that unlocks supernatural abilities, at a cost.<br /><br /></div><div><a href="https://draft.blogger.com/#">Circle Series 4-in-1 (The Circle Series)</a>, by Ted Dekker (Author) It beings when a man named Thomas Hunter finds himself being chased down an alley after working the late shift at a coffee house. When a bullet grazes his head, he awakens to an entirely different reality. Now every time he falls asleep, he wakes up in the other reality--and every choice he makes impacts the fate of two worlds. <br /> <br /><br /><br /><u><a href="https://www.goodreads.com/author/show/16231.Bill_Myers?from_search=true&amp;from_srp=true" target="_blank"><b>Bill Myers</b>&nbsp;</a><br /></u><br /><a href="https://draft.blogger.com/#">Soul Tracker (The Soul Tracker Series)</a> Part 1, by Bill Myers  (Author) David Kauffman is devastated when his young daughter meets an untimely death. Desperate to contact her, he meets Gita Patekar who works for “Life After Life”—an organization dedicated to tracking and recording the experiences of the soul once it leaves the body. Despite Gita’s warnings that God is opposed to contacting the dead, David uses the organization’s computer to try to find his daughter.</div><div><br /><a href="https://draft.blogger.com/#">The Presence (The Soul Tracker Series)</a> Part 2, by Bill Myers  (Author) The first subjects exposed to The Presence went insane. Now a far more terrifying experiment is about to begin… A diverse group of unusual characters is airlifted to a remote mountain lodge. Here they hope to participate in a séance connecting them to the spirit world. David Kauffman and his teenage son have joined them to debunk a world-class psychic and expose her as a hoax.<br /><br /></div><div><a href="https://draft.blogger.com/#">The Seeing (The Soul Tracker Series)</a> Part 3, by Bill Myers  (Author) Young Luke Kauffmann acquires a pair of strange goggles that gives him glimpses into dimensions around him, where dark, sinister forces exert their powers to influence—and glimmering creatures of light strive to stop them. Thanks to the help of a beautiful but quirky techie, Luke increases the power of the goggles until he is thrust even deeper into the spirit world.<br /><br /></div><div><a href="https://draft.blogger.com/#">Eli</a>, by Bill Myers  (Author) What If Jesus Had Not Come Until Today? Who Would Follow Him? Who Would Kill Him? <br /><br /> <br /> <br /> <br /> <b><u><a href="https://www.goodreads.com/author/show/2975035.K_M_Weiland?from_search=true&amp;from_srp=true" target="_blank">K.M. Weiland</a><br /></u></b> <br /><br /><a href="https://draft.blogger.com/#">Dreamlander</a>, by K. M. Weiland (Author) Only one person in a generation may cross the barrier of dreams to reach the other world - a world of war-scarred countries and fallen faiths. When a Chicago-born journalist finds himself on the far side of his dreams, he must hurl himself into battle to save a princess from her own people, two worlds from annihilation, and himself from a dream come way too true. <br /> <br /><br /> <br /><b><u><a href="https://www.goodreads.com/author/show/6853959.Lauren_Stinton?from_search=true&amp;from_srp=true" target="_blank"> Lauren Stinton <br /></a></u></b><br /><i>Hamal Books Series:</i></div><div><i><br /></i></div><div><i>Welcome to King’s Barrow, where the gifts have lived side by side for hundreds of years: flamemakers, jewelers, weathermakers, growers, artists, seers, alchemists—and healers, like seventeen-year-old Hamal. He knows he isn’t the best, or even the smartest, healer in the city. He isn’t good with numbers, and he always leaves scars..... <b>an Unlikely Hero Story</b></i></div><div><br /></div><div><a href="https://amzn.to/2xJ7HW4" target="_blank">Should I Choose to Die Again (The Hamal Books Book 1)</a></div><div><br /></div><div><a href="https://amzn.to/39C6ltj" target="_blank">The One-Eyed Man (The Hamal Books Book 2)</a></div><div><br /></div><div><a href="https://amzn.to/2wTHZOp" target="_blank">The Healer Who Didn't Remember (The Hamal Books Book 3)</a></div><div><br /></div><div><a href="https://amzn.to/3ayJ2SA" target="_blank">Flicker: A Hamal Short Story (The Hamal Books)</a></div><div><br /></div><div><br /></div><div><i>House of Elah Series:</i></div><div><i><br /></i></div><div><i>A tale of twins sons, raised by another, in a world of Magic and Power. A childless father, who's chosen family is worth risking everything for. An adventure for the ages.<br /></i><br /><a href="https://amzn.to/2QZWM0D" target="_blank">The House of Elah (Book 1)</a><br /><br /><a href="https://amzn.to/3dOmor5" target="_blank">The Alusian's Quest (The House of Elah Book 2)<br /></a><br /><a href="https://amzn.to/2R3GwvN" target="_blank">The King's Man (The House of Elah Book 3)<br /></a><br /><br /><br /><div>
<h4>
<b>Other fiction authors include:</b></h4>
<div>
<br /></div>
<div>
<a href="http://amzn.to/2c2tE6x">Ender's Game</a>, by Orson Scott Card &nbsp;(Author)</div>
<div>
One of the classics of Science Fiction. A child born into a world that survived an alien attack is trained to lead a fight on alien turf. Children think quicker (due to video games) so they make the perfect subjects of the test.</div>
<div>
<br /></div>
<div>
<a href="http://amzn.to/2cfVCck">The Girl Who Stole Tomorrow (S-Impact Book 1)</a>, by <a href="https://www.goodreads.com/author/show/14558395.D_B_McDowell?from_search=true&amp;from_srp=true" target="_blank">D.B. McDowell</a> (Author)</div>
<div>
A girl lives in a world that was destroyed by creatures with elemental powers, called Seejin. She makes discoveries that lead her on a grand adventure, with a shocking end.<br />
<br />
<a href="http://amzn.to/2c6RVa6">Lord of the Rings,</a>&nbsp;by JRR Tolkien (Author)<br />
If you don't know this book, you've been living under a rock somewhere. Elves, Wizards, Men, Dwarves... read it.<br />
<br />
<a href="http://amzn.to/2cMGAdZ">Chronicles of Narnia</a>, by C. S. Lewis &nbsp;(Author)<br />
The Lion, obviously an archetype of Jesus, dies to save one young man. What a way to personalize the gospel story. Another story that really makes you think about your relationship with God.<br />
<br />
<a href="http://amzn.to/2cOfxmQ">Harry Potter and the Sorcerer's Stone</a>, by J.K. Rowling &nbsp;(Author)&nbsp;<br />
I read the first Harry Potter and watched a few of the movies. I read a book "Finding Jesus in Harry Potter". I'm torn on my opinion because it has some strong messages I don't like, but it has some I do. I'm including it here because it's been a huge impact on our nation, and it's worth considering if you want a good story.<br />
<div>
<br /></div>
<div>
<a href="http://amzn.to/2c2v7Kn">Pilgrim's Progress</a>, by John Bunyan (Analogy)</div>
<div>
This story falls squarely within a sub-genre called Parable or Analogy. The protagonist's name is Christian, and this story follows the ups and downs of the Christian's life. It is meant to be a sermon with a plot. Despite&nbsp;its&nbsp;clear message, it still manages to work as a story and inspires the heart to believe.&nbsp;</div>
<div>
<br /></div>
<a href="http://amzn.to/1Mcvfn0">The Shack</a>, by Wm. Paul Young (Author)<br />
<div>
This is our generations Pilgrim's Progress, the story of a man who went to the place of his daughter's murder, to find freedom for his soul. This has none of the analogy of Pilgrim's progress, it's all story, yet it packs all the same punch. It leaves you thinking about your own walk with God in an entirely new way. Let's just say this: God is a big black woman... Ok, Go.</div>
<div>
<br /></div>
<div>
<a href="http://amzn.to/2cMDHKk">This Present Darkness</a>&nbsp;by Frank E. Peretti (Author)</div>
What if you could see the fight between angels and demons going on around you all the time? What if you could hear the debate for your soul and the deception they are trying to get you to believe. This story is not an analogy, but it does make you think about what's going on in your very room right now, you may even get a little crept out.<br />
<br /><br /><i><br />*Disclosure of Material Connection: Some of the links on this page are “affiliate links.” This means if you click on the link and purchase the item, I will receive an affiliate commission. I may also have received one or more of the products or services mentioned above for free in the hope that I would mention it on my blog.<br /><br />Regardless, I only recommend products or services I use personally and believe will add value to my readers.<br /><br />I am disclosing this in accordance with the Federal Trade Commission’s <a href="http://www.gpo.gov/fdsys/pkg/CFR-2003-title16-vol1/content-detail.html">16 CFR, Part 255</a>: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.” A Big Thank You to <a href="http://michaelhyatt.com/five-ways-to-comply-with-the-new-ftc-guidelines-for-bloggers.html">Michael Hyatt</a> for helping us Bloggers with these new legal disclosure requirements.<br /><br />As iron sharpens iron, so one person sharpens another. (Proverbs 27:17 NIV)</i></div><div><i><br /></i></div><div><i><br /></i></div><div><i><br /></i></div><div><i><br /></i></div><div><i><b>The End... For Now.</b></i></div>
</div>
</div>
