---
title: 'My Links'
date: '2024-03-22T17:39:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_page_id: '6769772550561384600'
blogger_filename: '/p/my-links.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
---

<h3 style="text-align: left;">My Links... Darrell Wolfe</h3><br /><br /><br /><h4 style="text-align: left;">Biblical Studies</h4><br /><a href="http://Academia.edu">Academia.edu</a><br /><br /><a href="https://nohidingfaith.blogspot.com/p/blog-page.html">No Hiding Faith (Theology Blog)</a><br /><br /><i><br /></i><div><i>Biblical Studies Related<br /></i><br /><a href="https://fuller.edu/master-of-arts-in-theological-studies/">MA in Theological Studies</a> My Degree in Progress<br /><a href="https://netbible.org/bible/Genesis+1">New English Translation (NET) Bible</a><br /><br /><a href="https://www.bible.com/bible/90/GEN.1.LEB">Lexham English Bible (LEB) on YouVersion</a><br /><br /><a href="https://www.logos.com/">Logos Bible Software</a><br /><br /><br /><h4 style="text-align: left;">Business Intelligence Analyst</h4><br /><a href="https://github.com/darrellwolfe">GitHub</a><br /><br /><a href="https://www.linkedin.com/in/darrellgwolfe/">LinkedIn</a><br /><br /><a href="https://public.tableau.com/app/profile/darrell.wolfe/vizzes">Tableau: Darrell Wolfe</a><br /><br /><a href="https://public.tableau.com/app/profile/kootenai.county/vizzes">Tableau: Kootenai County</a><br /><br /><br /><h4 style="text-align: left;">Personal Writing</h4><br /><a href="https://darrellglenwolfe.blogspot.com/p/resources.html">Darrell Wolfe, Storyteller (Personal Blog)</a><br /><br /><a href="https://darrellglenwolfe.blogspot.com/p/writing-craft-database.html">Writing StoryCraft Database ~ Darrell Wolfe, Storyteller</a><br /><a href="https://darrellglenwolfe.blogspot.com/p/sayings-to-live-by.html">Sayings To Live By ~ Darrell Wolfe, Storyteller</a><br /><br /><br /><h4 style="text-align: left;">Creative Writing</h4><br /><a href="https://www.royalroad.com/fiction/106260/manna-sarcasm-burritos">Fiction: Royal Road: Manna, Sarcasm, &amp; Burritos</a></div><div><br /><br /><h4 style="text-align: left;">Mental Health, Psychology, and Neurodivergence</h4><br /><a href="https://www.facebook.com/profile.php?id=100089776621771">ADHD, Autism &amp; Mental Health Memes &amp; Videos, by Wolfe Bookmarks </a><br />Helpful Links for Mental Health and Growth<br /><br /><a href="https://embrace-autism.com/">Embrace Autism | The ultimate autism resource</a><br /><br /><a href="https://www.gallup.com/cliftonstrengths/en/254033/strengthsfinder.aspx">StrengthsFinder 2.0 | EN - Gallup</a><br /><br /><a href="https://www.assessment.com/">MAPP Career Assessment</a><br /><br /><a href="https://www.16personalities.com/free-personality-test">16 Personalities (Myers Briggs Augmented)</a><br /><br /><br /><br /><br /><br /><br />  </div>