---
title: 'Building the Building: Permits, Fees, Compliance, and Codes'
date: '2018-02-23T07:18:00.0000000+00:00'
draft: true
blogger_blog: 'The Playground, LLC'
blogger_status: 'LIVE'
blogger_post_id: '8765724867803599764'
blogger_filename: '/2018/02/building-building-permits-fees.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Playground, LLC/feed.atom'
categories:
  - 'PreLaunchResearch'
---

The MOST confusing and mysterious part of the business planning if figuring out what we'd need to have in regards to&nbsp;Permits, Fees, Compliance, and Codes. There seems to be no uniform or even general answers available. However, the City of Hayden seems to have a process for Pre-Development whereby you meet with the staff and work out these details. This could be a good place to start.<br />
<br />
<b><br /></b>
<b>QuickLinks:</b><br />
<br />
Permits, Etc.<br />
<ul>
<li><a href="http://www.kcgov.us/departments/building/" target="_blank">Kootenai County Building Department</a>&nbsp;</li>
<li><a href="https://www.cdaid.org/building" target="_blank">City of Hayden Building Dept</a></li>
<ul>
<li><a href="http://www.cityofhaydenid.us/government/finance/fee_schedule.php" target="_blank">City of Hayden Fee Schedule</a></li>
</ul>
</ul>
See Also:<br />
<ul>
<li><a href="https://www.cdaid.org/building" target="_blank">City of Coeur d’Alene Building Dept</a></li>
<li><a href="http://www.postfallsidaho.org/departments/public-services/building/" target="_blank">City of Post Falls Building Dept</a></li>
<li><a href="http://www.rathdrum.org/building" target="_blank">City of Rathdrum Building Dept</a></li>
</ul>
<br />
<br />
<br />
<a href="http://www.cityofhaydenid.us/government/community_and_economic_development/planning.php" target="_blank"><br /></a>
<a href="http://www.cityofhaydenid.us/government/community_and_economic_development/planning.php" target="_blank">City of Hayden: Permits</a><br />
<br />
Pre-Development Procedures<br />
<br />
The following procedures shall be followed for all development within the City of Hayden.&nbsp; Commercial building permit applications, site plan applications, land use, and subdivision applications are accepted only following a pre-development meeting.&nbsp; <b>Pre-development meetings are held for one hour increments and are available for scheduling on Tuesdays and Wednesdays at 10:00 and 11:00 a.m.&nbsp; Meetings must be scheduled by noon of the Monday of the same week.</b>&nbsp; Advanced scheduling of a few weeks in advance is recommended as available time slots may fill quickly.<br />
<br />
<ul>
<li>Customers will complete a Pre-development Meeting Request Form</li>
<li>City staff from Building, Planning and Engineering will be present at the meeting along with other involved agency staff (such as the Fire Department)</li>
<li>Notes customized to your development proposal will be drafted during the meeting and emailed to the contact person identified on the meeting request form.</li>
<li>A file folder will be created for future reference</li>
<li>The meeting is informational in nature and is provided to assist you during permitting and development processes.&nbsp; Feedback is based on an assessment of the information provided by&nbsp; you, as the applicant, at the meeting as well as codes, regulations, and fees in effect at the time of the meeting.&nbsp; Timing of application as well as alterations to the site plan and/or project scope, and detailed project review, among other things, may affect the applicability of those items discussed.&nbsp; Because the pre-development review meeting is designed to provide conceptual level review, no approvals are intended or implied until the permit application, review, and approval process has been completed; as such, the items noted herein may not be addressed completely or accurately at the meeting.</li>
<li>Upon development application, the information from this file will be transferred to the building permit application, development application, or site plan application file</li>
</ul>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />