---
title: '1,000 True Fans is all you need...'
date: '2018-03-05T06:15:00.0000000+00:00'
draft: true
blogger_blog: 'The Playground, LLC'
blogger_status: 'LIVE'
blogger_post_id: '5402710318264325145'
blogger_filename: '/2018/03/1000-true-fans-is-all-you-need.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Playground, LLC/feed.atom'
categories:
  - 'PreLaunchResearch'
  - 'Ideas Goals Dreams'
  - 'Funding'
---

If you follow internet guru's like Pat Flynn, or Seth Godin, or Michael Hyatt, you will hear the term: "1,000 True Fans". I hadn't bothered to find the source of this term until today.<br />
<br />
Seth Godin's blog (<a href="http://sethgodin.typepad.com/seths_blog/2008/03/1000-true-fans.html" target="_blank">here</a>), links back to the original author <a href="http://kk.org/thetechnium/1000-true-fans/" target="_blank">Kevin Kelly's blog (here)</a>. It's a great essay/article. Worth a read.<br />
<br />
As we sat to lunch today, Flavia and I talked about how this principle would apply to The Playground.<br />
<br />
If we had 100,000 people give $10.00 toward our concept, that would be $1,000,000 ($1Mil) toward the start-up.<br />
<br />
If we had 10,000 people give $100 toward our concept, that would be $1,000,000 ($1Mil) toward the start-up.<br />
<br />
If we had 1,000 people give $1,000 toward our concept, that would be $1,000,000 ($1Mil) toward the start-up.<br />
<br />
The point is, it doesn't take as much as you think. If those who like the idea give what they can to help, and we enlist businesses through a dedication wall, allowing those persons' to have a place of permanent advertising in our business, and if we combine that with grants and other fund-raising, we can totally fund an amazing start-up without having to "go cheap".<br />
<br />
Here's to all of the amazing True Fans we are going to have!<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />