---
title: 'Funding the Business'
date: '2018-02-23T06:48:00.0040000+00:00'
draft: true
blogger_blog: 'The Playground, LLC'
blogger_status: 'LIVE'
blogger_post_id: '5561971395663809960'
blogger_filename: '/2018/02/funding-business.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Playground, LLC/feed.atom'
categories:
  - 'PreLaunchResearch'
---

There are several avenues we are looking into for funding the start-up. We have decided that there will not be any owners other than Flavia &amp; Darrell Wolfe (and eventually the kids or other family). Therefore, we will not accept investors/stockholders.<br />
<br />
<div style="text-align: center;">
***</div>
<br />
<h4>
Mini Pitch:</h4>
We want to give North Idaho a place to play &amp; grow!<br />
<br />
Help us give North Idaho a place to play &amp; grow, here's what that looks like:<br />
<br />
The Playground is a Movement-Based Entertainment Center for the Coeur d'Alene, Idaho Community. The facility features an indoor over-sized <a href="https://theplaygroundllc.blogspot.com/2018/02/playsmart-worlds-best-playgrounds.html">PlaySmart Playground</a>, tables and seating for parents (who tire quickly) and meeting rooms. There are also mini-events and movement-based arcade games (but only those that keep the body moving).<br />
<br />
See our website for ongoing development details and updates.<br />
<div>
<br /></div>
<div>
https://theplaygroundllc.blogspot.com/</div>
<div>
<br /></div>
<div style="text-align: center;">
***</div>
<br />
<br />
<b>We are looking into the following options:</b><br />
<div>
<br /></div>
<b>1. Crowd Funding</b><br />
<ul>
<li><a href="https://www.gofundme.com/" target="_blank">GoFundMe</a></li>
<ul>
<li><a href="https://www.gofundme.com/theplaygroundllc">https://www.gofundme.com/theplaygroundllc</a></li>
<ul>
</ul>
</ul>
</ul>
<div>
<br /></div>
<div>
<b>2. Grants</b><br />
<ol><ul>
</ul>
</ol>
<b>3. SBA Start-Up&nbsp;Loans</b><br />
<div>
<br /></div>
<div>
<div style="text-align: center;">
***<br />
<br /></div>
</div>
<h4>
<b>1. Crowd Funding:</b></h4>
Articles on Crowd Funding:<br />
<ul>
<li>Entrepreneur.com: <a href="https://www.entrepreneur.com/article/228534" target="_blank">10 Top Crowdfunding Websites</a></li>
<li>Forbes.com: <a href="https://www.forbes.com/sites/chancebarnett/2013/05/08/top-10-crowdfunding-sites-for-fundraising/#5cda2a293850" target="_blank">Top 10 Crowdfunding Sites For Fundraising</a></li>
<li>Intuit Quickbooks: <a href="https://quickbooks.intuit.com/r/crowd-funding/8-crowdfunding-sites-which-is-best-for-you/" target="_blank">8 Crowdfunding Sites: Which Is Best for You</a>?</li>
<li>CrowdFunding.com: <a href="https://www.crowdfunding.com/" target="_blank">Top Fundraising &amp; Crowdfunding Online Platforms</a></li>
</ul>
<div>
<b><br /></b></div>
<div>
<b>Will use:</b></div>
<br />
<a href="https://www.gofundme.com/" target="_blank"><b>GoFundMe</b></a><br />
<b>https://www.gofundme.com/theplaygroundllc</b><br />
<ul>
<li>Set a monetary&nbsp;goal, tell your story (who, what, why, when, where), share, share, share the links, embed the widget, spread the news.</li>
<li>GoFundMe charges nothing to have the&nbsp;posting but does charge a percentage/fee per transaction.</li>
</ul>
<b><br /></b> <i><b>Won't use:</b></i><br />
<i><a href="https://gogetfunding.com/" target="_blank"><span style="color: black;"><b><br /></b></span></a> <a href="https://gogetfunding.com/" target="_blank">GoGetFunding</a>&nbsp;(No Go &gt; Costs of GoGetFunding are very high compared to GoFundMe).</i><br />
https://gogetfunding.com/the-playground-llc/<br />
<ul>
<li><a href="https://gogetfunding.com/how-to-fundraise/" target="_blank">How it works</a></li>
<li>We're a 'keep-it-all' personal crowdfunding site meaning that even if you don't reach your fundraising goal, you still keep all of the funds raised (minus our industry low fees).</li>
<li>It's completely free to start your fundraiser! We charge a competitive 6.9% fee on funds raised (2.9% of which is a payment processing fee*) - making our fees lower than all of our major competitors. This fee is automatically deducted when you receive a donation - you don't have to do anything and you won't get any bills from us. We know that the features and personal support we provide will help attract extra donations that will more than cover this fee.</li>
<li>Some sites say they are '100% Free' but they actually charge donors. Not cool. *If you connect payment handlers PayPal and Stripe, they charge an additional minimal fee of between $0.25 and $0.30 per transaction. For more info and your local rate, please see the PayPal and Stripe fees page.&nbsp; Please note: Some developing countries or those with payment restrictions may be subject to higher fees. If so, you will be advised during campaign creation</li>
<li>Unlike many other crowdfunding sites, you don't have to wait until your campaign ends before accessing your donations. Just wait for a small period (7 days, typically) for the funds to clear.</li>
</ul>
<b><br /></b> <b>Either won't work or requires more information:</b><br />
<br />
<a href="https://www.indiegogo.com/" target="_blank">IndieGoGo</a><br />
<ul>
<li><a href="https://entrepreneur.indiegogo.com/education/guide/pre-launch-calendar-checklist/?utm_source=entrepreneur&amp;utm_medium=referral&amp;utm_campaign=etr-upsells&amp;utm_content=cta&amp;r=etr-ref-etr-upse" target="_blank">Pre-Launch Guide</a></li>
<li><a href="https://learn.indiegogo.com/pricing-and-fees/" target="_blank">Fees</a></li>
<li>It's unclear as to whether IndieGoGo would be of any help to The Playground, LLC for our purposes.</li>
<li>Example of a similar business using this service: <a href="https://www.indiegogo.com/projects/first-ever-youth-special-needs-parkour-facility-gym-kids#/" target="_blank">First ever Youth &amp; Special Needs Parkour Facility</a></li>
</ul>
<div>
<a href="https://www.patreon.com/" target="_blank">Patreon</a></div>
<div>
<ul>
<li>Who It’s Good For: Because Patreon prides itself on supporting creators (from podcasters to game creators to artists), this platform is best if you’re pursuing a creative venture.</li>
</ul>
</div>
<a href="https://www.kickstarter.com/" target="_blank">Kickstarter</a><br />
<ul>
<li>Kickstarter would not work for The Playground, LLC as it's not for starting traditional businesses.</li>
<li>Kickstarter is specifically for creative projects in the following categories: Art, Comics, Crafts, Dance, Design, Fashion, Film &amp; Video, Food, Games, Journalism, Music, Photography, Publishing, Technology, and Theater. Make an album, write a book, create an immersive theater experience, score a film — you name it.</li>
</ul>
<br />
<div style="text-align: center;">
***</div>
<br />
<h4>
<b>2. Grants:</b></h4>
TBC...<br />
<br />
We have learned about a friend of the family who understands grants, pending a meeting with her.<br />
<br />
<a href="https://www.cdaid.org/grant2017" target="_blank">Coeur d'Alene Idaho: Community Opportunity Grant</a><br />
<div>
<div>
<ul>
<li>The City of Coeur d’Alene issued a Notice of Funding Availability on October 13, 2017 to invite competitive proposals for projects or services that benefit low-to-moderate income Coeur d'Alene citizens or neighborhoods, and/or promote job creation/economic development which would impact low-to-moderate income employees. Any individuals, profit or nonprofit organizations, business or governmental agencies may submit a proposal for funding under the City of Coeur d’Alene’s Community Development Block Grant (CDBG) Program.&nbsp;</li>
</ul>
</div>
<div>
<div>
<a href="https://www.idahononprofits.org/grant-opportunities" target="_blank">Grant Opportunities</a>&nbsp;in North Idaho</div>
</div>
</div>
<div>
<div>
<ul>
<li>Mostly geared toward Non-Profits</li>
<li>Members of the Idaho Nonprofit Center may subscribe to the Society for Nonprofits Organizations (SNPO) and receive full access to SNPO and GrantStation.com. Sign up now! Call (208) 424-2229 for more information on how to take advantage of this great member benefit.</li>
</ul>
</div>
<div>
Networking through the <a href="http://www.cdachamber.com/your-chamber/join-the-chamber/" target="_blank">CDA Chamber of Commerce</a> could help us find more; however, it's a $500 fee for the minimum entry level (annually).</div>
</div>
<div>
<br /></div>
<br />
<br />
<a href="https://www.nerdwallet.com/blog/small-business/small-business-grants-for-women/" target="_blank">Small-Business Grants for Women: 10 Go-To Spots</a><br />
<br />
<ul>
<li><a href="http://www.grants.gov/web/grants/search-grants.html">Grants.gov</a> is a database of federally sponsored grants, including grants for small businesses. To apply, you must obtain a DUNS number for your business (a unique nine-digit identification number), register to do business with the U.S. government through its System Award Management <a href="https://www.sam.gov/portal/SAM/?portal:componentId=9615a076-c195-44d7-9bf4-ff1d3d101e6c&amp;interactionstate=JBPNS_rO0ABXc0ABBfanNmQnJpZGdlVmlld0lkAAAAAQATL2pzZi9uYXZpZ2F0aW9uLmpzcAAHX19FT0ZfXw**&amp;portal:type=action##11">website</a>, and create an account at Grants.gov.</li>
</ul>
<ul>
<li>The SBA sponsors about 100 <a href="https://www.sba.gov/tools/local-assistance/wbc">Women’s Business Centers</a> nationwide, designed to help women entrepreneurs with business development and access to capital. Some, such as the <a href="http://cacapital.org/">California Capital Financial Development Corp.</a>, lend money directly, while others help you find small-business grants and loans that you may qualify for.</li>
</ul>
<ul>
<li>The <a href="https://ambergrantsforwomen.com/get-an-amber-grant/?utm_expid=16497869-50.q2f8YOaKQg-BgO77JhkXdQ.1&amp;utm_referrer=https%3A%2F%2Fambergrantsforwomen.com%2Fabout-us%2Ffaq-online-grants-for-women%2F">Amber Grant Foundation</a> awards $500 to a different women-owned business every month. At the end of each year, one of the 12 grant winners is awarded an additional $2,500. The application is relatively simple: Explain your business, describe what you’d do with the grant money and pay a $7 application fee. The foundation’s advisory board chooses the winners, looking for women with passion and a good story. Businesses operating in the U.S. and Canada are eligible.</li>
</ul>
<ul>
<li>Eileen Fisher, a women’s clothing retailer, <a href="https://www.eileenfisher.com/grants/women-owned-business/grant-program-guidelines/">awards a total of $100,000</a> to up to 10 women business owners each year. To be eligible, women must make up at least 51% of your business’s ownership and leadership, your business must have been in operation for at least three years, earn less than $1 million in annual revenue, and be focused on environmental or social change.</li>
</ul>
<ul>
<li><a href="https://smallbusiness.fedex.com/grant-contest.html">FedEx</a> awards up to $25,000 apiece to 10 small businesses annually. In 2017, the contest provided a total prize pool of $120,500. Winners also receive money to use toward FedEx Office print and business services. The application requires an explanation of your business, how you’d use the money, photos of your business and — this part is optional — a short video explaining your business. To be eligible, you must operate a for-profit business with fewer than 99 employees and at least six months of operating history.</li>
</ul>
<ul>
<li>This nonprofit trade association awards $4,000 per month in <a href="https://www.nase.org/Membership/Benefits/Growth_Grants.aspx">growth grants</a> to small businesses that can be used for a variety of business needs, including marketing, advertising and hiring employees.</li>
</ul>
<ul>
<li><a href="https://www.nerdwallet.com/blog/small-business/small-business-grants-minorities/">Find small-business grants for minorities</a></li>
</ul>
<br />
<div>
<a href="https://www.nerdwallet.com/blog/small-business/small-business-grants/" target="_blank">Small-Business Grants: Where to Find Free Money</a></div>
<ul>
<li><a href="https://www.sba.gov/starting-business/learn-about-business-laws/contact-government-agency/economic-development-agencies">Economic Development Administration</a>: This U.S. Department of Commerce agency provides <a href="https://www.eda.gov/grants/">grants</a>, resources and technical assistance to communities to support economic growth and encourage entrepreneurship and innovation. Each state’s agency helps businesses find financing (including state or regional grants), secure locations and recruit employees. You can search for regional offices and local resources at the <a href="https://www.eda.gov/resources/">EDA’s website</a>.</li>
</ul>
<ul>
<li><a href="https://www.sba.gov/tools/local-assistance/sbdc">Small Business Development Centers</a>: Your local SBDC provides support for small businesses and aspiring entrepreneurs. They’re often associated with local universities or the state’s economic development agency, and many can help connect business owners with financing opportunities, as well as mentors and networking opportunities and training on basic business skills.</li>
</ul>
<div>
<br /></div>
<div>
<div>
<a href="https://www.sba.gov/blogs/government-grants-small-business-think-you-qualify" target="_blank">Government Grants for Small Business—Think you Qualify?</a></div>
</div>
<div>
<br /></div>
<div>
<ul>
<li>This article basically says there are no Federal Government Grants unless you're a High Tech business or Advanced R&amp;D business.</li>
</ul>
<div>
<br /></div>
</div>
<div>
<a href="https://www.fundera.com/blog/small-business-grants" target="_blank">Want Free Money? Check Out This List of 106 Small Business Grants</a></div>
<ul>
<li>Many states actually have a STEP program, <a href="http://commerce.idaho.gov/idaho-business/international-trade/state-trade-and-export-promotion-grant">Idaho included</a>. However, they each have individual application processes and qualification criteria, so make sure you double-check what you need to do to apply!</li>
</ul>
<ul>
<li>Each year, <a href="https://www.jpmorganchase.com/corporate/news/stories/mission-main-street-grants.htm">Chase Bank puts aside $3 million</a> to split between 20 small businesses—that’s $150,000 each. You’ll have to answer a few essay questions regarding your business, its story, and its community impact, and then winners are decided by a panel of small business experts and senior executives. You’ll also get a free trip to Google for a small business marketing workshop, and more.</li>
</ul>
<ul>
<li>Similarly, Coca-Cola’s <a href="http://www.coca-colacompany.com/our-company/the-coca-cola-foundation/">community-giving branch</a> centers around empowering women, improving access to clean water, and fostering healthy living and youth development. If your small business doesn’t qualify under the mostly charity-centric criteria, then try to see if you can contract or cater for the nonprofit that does.</li>
</ul>
<ul>
<li><a href="http://www.nase.org/become-a-member/grants-and-scholarships/BusinessDevelopmentGrants.aspx">NASE</a> offers small business grants of up to $5,000. Just register and see if you’re eligible!</li>
</ul>
<ul>
<li>This is the inaugural year for <a href="https://www.lendingtree.com/about/business-grant">LendingTree’s Small Business Grant</a> Contest. The winning small business will receive $50,000 to fund the needs of their growing business!</li>
</ul>
<ul>
<li>Though an international program, Walmart’s <a href="http://news.walmart.com/news-archive/2011/09/14/walmart-launches-global-womens-economic-empowerment-initiative">GWEEI</a> should still be on your list if you’re a female business owner: they’ve pledged to support women-owned businesses with over $100 million in grants.</li>
</ul>
<ul>
<li><a href="http://investor.kimberly-clark.com/releasedetail.cfm?releaseid=667272">This initiative</a> provides up to $15,000 grants to 12 “mompreneurs,” alongside business counsel and networking opportunities.</li>
</ul>
<ul>
<li><a href="https://sites.google.com/site/openmeadowsfoundation/">Open Meadows</a> funds projects with $2,000 grants, so long as they’re designed and led by women.</li>
</ul>
<ul>
<li>The <a href="https://www.mbda.gov/page/grants-and-loans">MBDA</a> has regular grant competitions for minority business owners, alongside a long list of other resources for you to learn from.</li>
</ul>
<ul>
<li>Hosted by AT&amp;T Experts, <a href="http://www.attexperts.com/grant">this grant</a> offers $1,000 to unique business ideas submitted in the form of a two-minute video. (Note that if your business is already established, its annual revenue must be can’t be greater than $20,000.</li>
</ul>
<ul>
<li>Fundera now hosts our <a href="https://www.fundera.com/resources/zach-grant">very own small business grant</a>, giving out $2,500 every year to entrepreneurs looking to start or fund their businesses. All you have to do is submit a video entry to the annual contest explaining why you started your company, follow us on social media, and… That’s all! <a href="https://www.fundera.com/resources/zach-grant">Apply today</a> to get that easy capital.</li>
</ul>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div style="text-align: center;">
***</div>
<div>
<br /></div>
<br />
<h4>
<b><br /></b><b>3. SBA Start-Up Loans:</b></h4>
I have a friend who does these, I'll be meeting with him to get more details in the future.<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br /></div>
