---
title: 'Why Storytelling?'
date: '2017-09-06T16:55:00.0000000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4325213164706352561'
blogger_filename: '/2017/09/why-storytelling.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'Stories'
---

Storytelling is the lifeblood of the human race. Sure, many have replaced books with movies or YouTube videos, but great stories transcend.<br /><br />From ancient times, The Storyteller, was a guest of kings and paupers. He/She was the keeper of legacies, histories, and entertainment. Unlike the best selling "5 secrets to a better ...." or "10 things you need to know about...", type books, stories stick with you. I can't remember the 7 habits, but I remember Frodo beating all odds to get that ring to the volcano.<br /><br />When you think about all the elements of your brand, story is among the most important parts. Once your brand story is simple and simply told, it informs the rest of your brand. It decides the fonts, colors, and styles you use.<br /><br />Your brand story will be the the thing you use to get who you are into the mouths of your truest fans, so they can tell others who you are. Often without knowing they are telling your story.<br /><br />Food for thought...<br /><br />Here are some clips from great articles about using story telling in Brand Marketing:<br /><br /><br /><br />FastCompany:&nbsp;<a href="http://www.fastcompany.com/3031419/hit-the-ground-running/why-our-brains-crave-storytelling-in-marketing" target="_blank">Why our brains crave storytelling in marketing</a><br /><br /><blockquote class="tr_bq">When reading straight data, only the language parts of our brains work to decode the meaning. But when we read a story, not only do the language parts of our brains light up, but any other part of the brain that we would use if we were actually experiencing what we’re reading about becomes activated as well.   </blockquote><br /><br />i-Scoop:&nbsp;<a href="http://www.i-scoop.eu/art-storytelling-6-content-marketing-context-questions/" target="_blank">Questions to ask yourself about your brand story</a><br /><br /><br /><ul><li>What is the story and narrative behind everything you do as a brand, ranging from what you stand for to the reason why you developed solution X or decided to support ‘good cause Y’?&nbsp;</li></ul><ul><li>How can you get to that story that’s part of your brand and even people’s DNA instead of to just the facts?&nbsp;</li></ul><ul><li>How do you actually connect with people in the language they understand best: the language they can “visualize” in a story-like context?</li></ul><ul><li>What types of stories appeal to your content marketing “personas”?</li></ul><ul><li>What about the stories your customers and ‘audiences’ are already telling? How do you listen to those and include them?&nbsp;</li></ul><br /><br />Entrepreneur.Com:&nbsp;<a href="http://www.entrepreneur.com/article/241725" target="_blank">Storytelling Could Bring Your Brand to Life and Strengthen Your Marketing Impact</a><br /><br /><blockquote class="tr_bq">A brand's story is no longer limited to or controlled by the media outlets and advertising that it uses. One would even say that this has been completely reversed: the media now runs stories based on how much traction they've gained elsewhere. Your customers and advocates are now the tastemakers, giving power to the stories that resonate with them.   </blockquote><br /><br /><a href="http://www.forbes.com/sites/work-in-progress/2013/02/05/5-secrets-to-using-storytelling-for-brand-marketing-success/" target="_blank">Forbes: 5 Secrets to Use Storytelling for Brand Marketing Success</a><br /><br /><blockquote class="tr_bq">Honesty and transparency are important in brand storytelling. Yes, you’re crafting “stories,” but they need to be rooted in the reality of your brand, products, and industry. In other words, even brand stories must adhere to the three primary steps of brand-building: consistency, persistence, and restraint.  </blockquote><br />Darrell