---
title: 'The Shroud'
date: '2017-11-27T01:00:00.0020000+00:00'
draft: false
categories:
  - 'Writing Craft'
  - 'Writing Practice'
---
Shadow enveloped Stephen as he watched the movements below from his perch in the old church bell tower. His cloak danced in the breeze as a proud flag, his face enshrouded under the familiar hood. He watched the events of Ashland, Idaho with a passive interest, until he noticed someone looking at him\... directly?

It had been three hundred years since anyone had seen him, really seen him. Could this Captain Ashland be one of them? A seer? Unlikely. Not many were left in the world. Although the rumors of the shadow world claimed they were on the rise, ever since the Azusa Street Revival.

Stephen moved from his perch, pacing left to right. The Captain's eyes followed him. "I must tell the others," he said. "There is an awakening\..."

His form morphed into a black whisp of cloud and he floated away from the perch, into the mountains.

***

Ash noticed the figure evaporated into a cloud of smoke. He shook his head. When would these visions ever get better?

Darrell G. Wolfe

Storyteller \| Writer \| Thinker \| Consultant \| [Multipotentialite](https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en)
