---
title: 'New Scene - White Noise'
date: '2017-09-26T07:52:00.0000000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '4590906529174438238'
blogger_filename: '/2017/09/new-scene-white-noise.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'White Noise'
---

I already don't love this scene, it's going nowhere and doing nothing, but I think there's a spark of something in here. I'll have to rework it later:<br />
<br />
<br />
<div style="text-align: center;">
***</div>
<br />
Normally, the workshop would have his full attention. But his over-dose concoction left him more groggy than it had in days past.<br />
<br />
After a shower, Ash opted for the front porch. He brought his coffee, thanks to the Kurieg, a Christmas gift from Sheriff Danny, and a microwaved breakfast sandwich. The wrap-around porch was situated with a view of the forest. Thanks to his family’s inheritance, he owned 100’s of acres in any direction of the house, with the exception of an easement that served as an access road for his neighbors.<br />
<br />
The sun was still at the back of the house, which left him in relative shade. Three white-tail deer were eating berries off of the wild bushes he’d left to attract them. It was already hunting season, but they seemed to know they had sanctuary here. He’d never fired a weapon this close to the house and they seemed to know it.<br />
<br />
The three deer each twitched their ears backward and raised their heads in unison. They looked back down the five-mile driveway. He called it a driveway, even though it was just a dirt road with rocks and a periodic planning from Ben, the local snow plower, tow truck driver, plainer, and anything else that needed an occasional driver.<br />
<br />
Dust clouds billowed into the air about a mile down the road, the white-tail hopped off into the forest. Ash walked inside and grabbed his pistol, shoving into the holster under his flannel shirt; then took the rifle outside and laid it again the rail in front of the rocking chair before resuming his coffee and breakfast.<br />
<br />
Eventually, a Ford Ranger pulled into the roundabout in front of the house. A rental, based on the tags. The driving style didn’t give Ash the impression that he was under attack, so he let the rifle be for now. He could make out a single occupant, female, darker skin, crazy hair popping out the back of a bright multi-colored crocheted hat. She stepped out of the vehicle revealing a form-fitting joggers outfit, equally bright, mostly purple.<br />
<br />
“I’m sorry to bother you,” She said with a warm voice, unlike any he’d heard around these parts. “I’m a bit lost.”<br />
<br />
“It happens, the GPS sends people here occasionally,” He looked her over before landing on her eyes. Not a bad distraction for an otherwise groggy morning. “Where are you trying to get to?”<br />
<br />
“Some trail, called Hiawatha?”<br />
<br />
“Well ma’am, you are quite a ways off then. I’d say you are about a two-hour drive by the time you get back to the freeway and then on to Lookout Pass.”<br />
<br />
“Uhg,” her eyes dropped and she looked like she might cry. “Dang GPS! I’ve already driven around quite a bit to land here. I think I’ll have to make that a trip tomorrow. Is there any kind of city around here, hotel, anything really?”<br />
<br />
“Town’s not much to see this&nbsp;time of year, it’s more of a summer spot for tourists. Just set the GPS for Harrison. Once you land on 97, you’ll drive right through it. Don’t blink though, or you’ll miss it. It’s only about one or two blocks long. Make sure to stop by the Ice Cream place, they should be open until Oktoberfest. That will help you forget the drive you took to get here.”<br />
<br />
<div style="text-align: center;">
***</div>
<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span> <span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
<div class="MsoNormal">
<br /></div>
