---
title: 'New Scene - White Noise'
date: '2017-10-01T07:47:00.0010000+00:00'
draft: false
categories:
  - 'Writing Practice'
  - 'White Noise'
---

The following is a re-write of what I posted recently. I like this MUCH better.<br />
<br />
<div style="text-align: center;">
***</div>
<div style="text-align: center;">
<br /></div>
Normally, the workshop would have his full attention. But his over-dose concoction left him more groggy than it had in days past.<br />
<br />
After a shower, Ash opted for the front porch. He brought his coffee, thanks to the Kurieg, a Christmas gift from Sheriff Danny, and a microwaved breakfast sandwich. The wrap-around porch was situated with a view of the forest. Thanks to his family’s inheritance, he owned 100’s of acres in any direction of the house, with the exception of an easement that served as an access road for his neighbors.<br />
<br />
The sun was still at the back of the house, which left him in relative shade. Three white-tail deer were eating berries off of the wild bushes he’d left to attract them. It was already hunting season, but they seemed to know they had sanctuary here. He’d never fired a weapon this close to the house and they seemed to know it.<br />
<br />
The three deer each twitched their ears backward and raised their heads in unison. They looked back down the five-mile driveway. He called it a driveway, even though it was just a dirt road with rocks and a periodic plaining from Ben, the local snow plower, tow truck driver, plainer, and anything else that needed an occasional driver.<br />
<br />
The subtle crunch of rock under boot caught Ash’s attention too. A shadowy figure was making their way down the driveway, through the trees. If they were there to hurt him, they’d be making a quieter approach; however, old training required he be cautious just in case.<br />
<br />
The figure was still about a five minute walk away, Ash walked inside and grabbed his pistol, shoving into the holster under his flannel shirt; then took the rifle outside and laid it again the rail in front of the rocking chair before resuming his coffee and breakfast. Eventually, she came into view. A female, darker skin, crazy hair popping out the back of a bright multi-colored crocheted hat. The sun revealed a form-fitting joggers outfit, equally bright, mostly purple.<br />
<br />
“I’m sorry to bother you,” She said with a warm voice as she approached. “… but my car broke down a few miles down the road.” She smiled with a the easy going smile of an ignorant city girl.<br />
<br />
“You should have called a cab, before walking through the woods alone,” Ash gestured to her, “in that.”<br />
<br />
“What’s that supposed to mean, mister? ‘In that’? What’s wrong with this?” He was about to answer, but she waived it off. “Besides, I tried to call a tow truck, but there’s no cell signal out here. It’s like I stepped back in time to the stone ages.” Her skin flushed a shade red, and bit her lip.<br />
<br />
A lump caught his throat, as he realized he’d upset her. Ash wasn’t used to prolonged human interaction with strangers. He didn’t even sell his own goods but used the local consignment shop to sell them so he could avoid these unpleasant conversations. “I’m sorry. I didn’t mean to offend. It’s just that those bright colors could attract the wrong kind of attention from animals that could see you as a threat.”<br />
<br />
She looked down at the ground, and kicked a small rock aside. “I’m sorry too. I’m working on my temper.” She looked up again, and caught his eye, and hesitated. “I mean… Let’s start over. Can I borrow your phone?”<br />
<br />
“I would let you, except for I don’t have one.”<br />
<br />
“You don’t have a phone? No cell, no land line, nothing?” The skin on her nose scrunched up, and her head tilted to one side. “How do you survive out here without a phone?”<br />
<br />
“I live here to avoid civilization, I generally don’t want to be reached.”<br />
<br />
“But what about emergencies?”<br />
<br />
“You mean like when lost young ladies break down on the road and come wandering onto my property? That wasn’t in my original planning when I decided not to have a phone. Besides, I have a voice mail that I access only when I go into town and use the Library computer.”<br />
<br />
“Well, I guess we’re getting a bit off track here. Can you help me find someone who does have a phone so I can call a Tow Truck?”<br />
<br />
“Sorry, no-one for miles. I keep it that way. Let me see if I can help.” He motioned for her to follow him. She stood to the side as he grabbed his tool box and threw it in the back of the truck. He laid his rifle on the back seat and closed the door. He waived her into the passenger side as he climbed in the driver’s seat.<br />
<br />
“I’m not sure I should be climbing into an ancient pick-up truck with a stranger.” She winked and smiled, mischievously.<br />
<br />
“Well, you can come inside a strangers cabin and wait for no-one to show up for weeks, or you can hop in the truck.” He smiled back.<br />
<br />
“Heard!” She hopped in, put on her seat belt, and crossed her legs. “My name’s Destiny, yours?”<br />
<br />
“Ash.” He replied.<br />
<br />
“Ash, as in the ash left over after a camp fire?”<br />
<br />
“Something like that.”<br />
<br />
The engine turned over and rumbled to life. Her white teeth, and relaxed posture put him at ease in a way he hadn’t been in a very long time. She chattered on about where she’d been, how she got onto the back roads, and where she’d come from. A reporter, following a lead about a reduction in small towns in America. Only bolstered by the fact she couldn’t even find this one. The GPS had told her to take a side road to cut-off miles of the drive down a curvy highway, only to then have her lose the GPS signal before she found the highway again.<br />
<br />
After about 30 minutes working on the electric SUV she’d rented, Ash realized he was in far over his head. Carburetors he understood, not this new computerized junk. “Well, I give up. You need a real mechanic.”<br />
<br />
“Well, thanks for trying.” She looked around, possibly a little concerned after his warning about wild animals.<br />
<br />
“Don’t worry, I’m not leaving a helpless city girl alone in the woods. I’ll drive you into town and get Ed to come pick it up and bring it to his shop. There’s a small Motel in town you can stay at while he looks it over.”<span style="white-space: pre;"> </span><br />
<br />
“Motel?” Destiny’s head shot back, eyebrows raised. “How long is this going to take?”<br />
<br />
“Things are pretty dead this time of year, so he can probably look at it right away. But we’re not exactly an electric car mecca, so he’ll probably have to order parts or have the rental company send a new vehicle and pick this one up. Knowing this area, you’re here until at least tomorrow.<br />
<br />
“Well, I’m not sure this is the town I was headed for, but it sounds like the perfect town for my story. Maybe I’ll just stay around a few days after all, make the trip worth it.”<br />
<br />
“Suit yourself,” Ash said as he pulled into town from a side road. He pointed left, and her eyes followed, then pointed right. That’s it. Welcome to Deer Ridge, Idaho. Population 420, no jokes please, we’ve heard ‘em all.”<br />
<br />
She stifled a giggle. “OK. Fair enough.”<br />
<br />
“Ed’s Auto is up that way, to the left. Carrie’s Ice Cream is open until Oktoberfest, so you’ll have that until then. She also serves some decent coffee. There’s a small grocery there. And the rest of the shops are closed until next spring. You can walk the bay of the lake from just over that wall there. It’s pretty any time of year.”<br />
<br />
Ash pulled onto the only road, and stopped in front of Ed’s. After a few moments, Ed and Destiny were on their way to her car. She smiled again, and waved her fingers as they passed. His chest tightened, ears tingled, it took an extra moment to remember to breath. He hadn’t felt like this in many decades. Shrugging it off, Ash grabbed a few things from the grocery before heading back to his refuge.<br />
<br />
<div style="text-align: center;">
***</div>
<br />
<br />
<br />
<br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18.0pt;">Darrell G. Wolfe</span><span style="font-family: &quot;times new roman&quot; , serif; mso-bidi-font-family: &quot;Times New Roman&quot;; mso-bidi-font-size: 12.0pt; mso-bidi-theme-font: minor-bidi;"><o:p></o:p></span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span> <span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant |&nbsp;</span><a href="https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling?language=en" style="font-family: &quot;tempus sans itc&quot;;">Multipotentialite</a></div>
<div class="MsoNormal">
<br /></div>
