---
title: 'Glenn Discovers a door to truth.'
date: '2020-04-14T07:04:00.0010000+00:00'
draft: false
categories:
  - 'Stories that matter...'
---

<div><b>Stories that matter:</b></div><div><br></div><div>The blank screen screamed at Glenn, the angry cursor blinking furiously at him, taunting him.&nbsp;</div><div><br></div><div><i>Looser</i></div><div><i><br></i></div><div><i>Incapable</i></div><div><i><br></i></div><div><i>Good for nothing</i></div><div><i><br></i></div><div><i>Waste of time</i></div><div><i><br></i></div><div><i>Waste of space</i></div><div><br></div><div>In reality, it was just a computer monitor. It had no mind of its own... he knew that. But it was easier to personify the anger than admit that these were his own thoughts. If they came from him, he'd have to admit he believed them. Maybe it was time to give up. Accept fate. Live the rest of his days working at a dead end job as an accountant, failing to live up to the potential everyone could see but him.&nbsp;</div><div><br></div><div>Scanning the dusty shelves of the ancient study he'd inherited from his famous author uncle, the anger boiled in him. He was so fed up with everyone's expectations of greatness, with his own expectations, with his inability to accept a "normal" life and his inability to achieve his higher purpose.&nbsp;</div><div><br></div><div>He slammed his fist on the oak desk. Then picked up a hardback copy of his uncle's last work and threw it against the far wall.</div><div><br></div><div>Rather than a thud, the sound that returned to him was a ping. As though the book had struck something solid and metal. But it had clearly hit the wall, he could see the dent in the drywall.</div><div><br></div><div>After further investigation, there was definitely something behind the drywall. Tearing it further apart,&nbsp; he found a safe buried inside the wall. Three years living in this old house and he was always discovering something new about uncle's eccentricities. It was a fingerprint scan lock. Without a copy of uncle's fingerprint, he'd need a locksmith to come help pry it open. Just for fun, he placed his own finger on the lock. The light turned green, and it hissed, and the door cracked.&nbsp;</div><div><br></div><div>Inside the safe was an old leather journal, a Bible, and a few scattered notes. Taking them to the large leather thinking chair, he set them on the side table. The journal was well worn, used for years.&nbsp;</div><div><br></div><div>It creaked as he opened it to the first page.&nbsp;</div><div><br></div><div><i>Dear Glenn,&nbsp;</i></div><div><i><br></i></div><div><i>You're only three now, so you won't understand this yet. But after your father died, I took it upon myself to make sure you had everything you needed to be successful. As you will know, I paid for your school, I hopefully watched you do many things. But if you're reading this, I've passed myself and you've found my hidden treasures. I prayed to my God that you'd only find this when you were absolutely ready to read it. Everything I ever wanted to tell you but didn't know how is here. The Bible, is my most prized possession. I realize I have sixty of them on the shelves, but this one, this one is mine. Open it, let the pages, and my notes, speak to you. Just be careful... You will find it's no ordinary Bible. It holds the secret to my success. I'm so happy you'll be taking my place in this grand adventure.&nbsp;</i></div><div><i><br></i></div><div><i>With Love, your Uncle, Clive</i></div><div><br></div><div>Glenn set the journal aside. What could be so special about a Bible? Picking it up, it was barely held together. The spine was literally duct taped together. Several pages were loose, threatening to fall out. Highlighter had been used on practically every page, visible even without opening the book.&nbsp;</div><div><br></div><div>It had been decades since he'd bothered with fairy tales about walking on water and raising the dead. Opening the Bible to the bookmarked page, he noticed the line that was highlighted in green... He read it aloud... "... Enoch walked with God, and he was no more, for God took him..."</div><div><br></div><div>He shrugged, set the book down.&nbsp;</div><div><br></div><div>A breeze blew through the open window from the garden. Glenn got up to close the window and the wind blew harder. Half way there he had to stop because he couldn't see.</div><div><br></div><div>Leaves blew into the room, swirling about him. Dust forced him to close his eyes against the onslaught. He decided to wait for a break in the storm so he could make his way to the window. Standing there a moment, he waited.... The wind died down. He pulled the corner of his shirt from his pants and used it to wipe his eyes free of the dust.</div><div><br></div><div>When he opened his eyes.....</div><div><br></div><div>The room was gone. He was standing in a pile of leaves before a tree that was larger than anything he'd ever seen.&nbsp;</div><div><br></div><div>"I've been expecting you..." A voice startled him from behind. Glenn turned and faced the voice. A large man, six foot at least, sat on a root of the oversized tree, and smoked a pipe. He was covered in fur and had a wild look about him. "... Come come..."&nbsp;</div><div><br></div><div>"Hello, im-" he was cut off</div><div><br></div><div>"Glenn. Yes. I know. And I'm Enoch. Welcome to my home..."</div><div><br></div><div>TBC...</div><div><br></div><div>#Selah</div><div><br></div><div><br></div><div><br></div>