---
title: 'Short Story: The memory is the last to go...'
date: '2020-04-21T06:09:00.0020000+00:00'
draft: false
categories:
  - 'Writing'
  - 'White Noise'
---

<div><i>Short Story: The memory is the last to go...&nbsp;</i></div><div><i><br /></i></div><div style="text-align: center;">***</div><div style="text-align: center;"><br /></div><div>The morning fog crisped Ahs’s nose as it mixed with the eerie mists emanating from the mingling crowds. The scent of the river always felt clean but mysterious this time of year. As though it promised to one day reveal its secrets, held in one of the many 1940’s cars at the bottom before people learned to stop driving over thin ice.&nbsp;</div><div><br /></div><div>He walked the edges of town, avoiding the largest concentration of people, barely aware of the purple clouds wafting from a couple sneaking a groping session behind the tree, mixing with the purple and green fog flowing from Eddie, the bank manager sitting across the street, doing his best not to appear to be watching them. The colors of every hue wafting from the people mixing mostly into ghastly greys in the waning fall crowds.&nbsp;</div><div><br /></div><div>He did his best to ignore the mists after years of it. The only way to keep his sanity intact. Eyes down, straight ahead. But you had to look up, look both ways, to cross the street. His eyes were drawn to a particularly dark charcoal grey puff, he knew before he finished his glance that it would be Hank.&nbsp;</div><div><br /></div><div>Sure enough, covered in dirt and three layers of Goodwill, there was Hank, fighting with a knot in his bicycle basket.</div><div><br /></div><div>Approaching cautiously, you never knew what mood Hank would be in, “Hey there Soldier, can I lend a hand?”</div><div><br /></div><div>“Hmpf,” Hank let out a more defeated than usual grunt. “Why not, I’ve been trying to get this damned knot untied for three hours.”&nbsp;</div><div><br /></div><div>An exaggeration, it had probably been three minutes. But that was Hank, he also ‘single-handedly’ defeated an entire Vietnam platoon with nothing but a make-shift shank carved from the remains of a Tonkin Snub-nosed Monkey.</div><div><br /></div><div>Ash silently took the knot from Hank, pulled out his pocket knife-</div><div><br /></div><div>“Stop-” Hank retorted. “That’s my best rope!”</div><div><br /></div><div>“Don’t worry old man,” Ash said. “I’m not going to cut it, just prying it loose.”</div><div><br /></div><div>Hank eyed him warily.&nbsp;</div><div><br /></div><div>“There,” Ash said, a few moments later. “It’s all loose for you.” He put his pocket knife in the Kevlar holster.&nbsp;</div><div><br /></div><div>Hank inspected the rope. “No frays,” he mumbled. “Thanks.”&nbsp; With that, he promptly ignored Ash, as usual, and went back to whatever imperative task his three hundred plastic bags in the buggy behind his bike required.&nbsp;</div><div><br /></div><div>Ash left him to his project. Hank reminded him of his father. If he couldn’t save Dad, or himself for that matter, the least he could do would be to show some kindness to one of their own kind.&nbsp;</div><div><br /></div><div>“How long,” Ash let out audibly. As he walked the docks to his boat, images of himself running around the countryside with only half an awareness of his insanity raced through his mind. <i>Like father like son</i>. He shrugged, climbing aboard. The fog was heavier here but the mists of the crowds stayed behind with them.&nbsp;</div><div><br /></div><div>Letting loose the tie-downs, he then started the engines and set off up-river for home, ripples disappearing into the fog… much like his memory, he feared.</div><div><br /></div><div style="text-align: center;">***</div>
<div><br /></div><div><br /></div><div><div><i>A short story, by Darrell Wolfe, Storyteller</i></div><div><br /></div></div>
