---
title: 'Major Theron "Ash" Ashland, USAF Spec Ops, Special Tactics Unit'
date: '2023-11-26T05:19:00.0000000+00:00'
draft: false
categories:
  - 'White Noise'
---

<div>Theron Ashland&nbsp;</div><div>Major Theron "Ash" Ashland, USAF Spec Ops, Special Tactics Unit</div><div>We're Air Force Special Tactics, and our motto is "First There...That Others May Live."&nbsp;</div><div><br /></div><div><ul style="text-align: left;"><li>Birth Date: xx/xx/1978, in Moon-Wolf Hollow, Idaho, on the family tree-farm, which is hundreds of acres of wooded hills, streams, and a small lake.</li><ul><li>His father was a distant, hard-working, lumberman. The father died when Ash was very young.&nbsp;</li><li>His mother was kind but broken by the loss of his father. Widowhood took root in her life as an identity, and she lived in the past in a way that left Theron taken care of physically, but emotionally unsupported. He developed an attachment style of Avoidant, so that he would never burden his mother with his emotions. She too died when Ash was just 18, and he spent the year getting his family’s affairs in order, including leaving the family property in Trust, deeded to an LLC, which was managed by a friend of the family, including tree harvesting.</li></ul></ul><div><br /></div><ul style="text-align: left;"><li>Enrolled at University of Idaho in 1997 at 19 - Ash majored in Organizational Leadership. But at the beginning of his fourth year, 9/11 happened and he dropped everything to enlist in the USAF the next day.</li></ul><ul style="text-align: left;"><li>USAF Enlistment: 09/12/2001, Age at Enlistment: 23</li><ul><li>He became a sniper in the USAF Spec Ops, Special Tactics Unit, working his way through the Enlisted Ranks.&nbsp;</li><li>Pouring himself into each assignment was his way of running from his own past. He handled the family property remotely through calls, and never went home on leave.</li></ul></ul><div><br /></div><ul style="text-align: left;"><li>Injured on Duty: xx/xx/2010, Age at Injury: 33</li><ul><li>After being injured (shot?) badly enough to require a lengthy hospital stay and rehab, Ash was restless and ended up using his time to complete the BA he left behind ten years earlier. Stacking summer and winter school on top of the maximum units the school would allow, he used all the time he wasn’t in Physical Therapy on school.&nbsp;&nbsp;</li><li>Temporary Disability Retired List (TDRL): 2010-2011 During which he completed a BA (BOLD) and MBA program, then joined Officer Training School (OTS).</li></ul></ul><ul style="text-align: left;"><li>After his return to service, now as an Officer, Ash climbed to the rank of Major between 2011-2018.</li><ul><li>During this time, his Leadership as an Officer with deep field experience became invaluable to his superiors, and a point of frustration to his peers, which his advice ran counter to theirs, which was always.</li></ul></ul><ul style="text-align: left;"><li>Medically Discharged: xx/xx/2018 at 40-year’s old.</li><ul><li>After an injury achieved in the field under suspicious circumstances, Ash was medically discharged at 40-year’s old. He went home to Moon-Wolf Hollow, Idaho, USA - Where he has been quietly living on his family property, alone, a valued member of the town, but truly known by very few.</li></ul><li>Home Life:</li><ul><li>He runs a small business selling hand-crafted woodwork, and he is a part-time weapons instructor for the local shooting club.&nbsp;</li><li>Ash keeps to himself, never attends parties, rarely comes to town for parades or events, especially if tourists are in town.</li><li>Ash does attend a local church, but only as a socially expected norm for the region. He is an admitted agnostic when pressed.&nbsp;</li><li>His only real friend in town is the local sheriff, a retired Army veteran who understands Ash’s need to be alone.</li><li>He also attends a wounded warriors recovery group once a month.&nbsp;</li><li>His PTSD symptoms come and go, some months worse than others.&nbsp;</li><li>When he was first discharged, he was prescribed strong narcotics, and those helped him through the early days. Eventually, just before his full discharge, they found a cocktail that worked well enough.&nbsp;</li><li>His local doctor, Sam?XXX, who played the dual role of small-town physician and mental health therapist, admitted that Idaho was behind the times on narcotics, and that Marijuana was showing a lot of good results in studies for PTSD. He went across the boarder to WA to get it for a while, but eventually obtained the necessary materials to grow his own. The local Sheriff backed this decision, and kept the feds away. Luckily, they left small towns like this alone most of the time, out of the spotlight.</li></ul><li>This is the state we find him, at a coffee shop, where he is having a particular over-powering PTSD vision, one he hasn’t had at this level since his first days in the hospital after he was found and recovered unconscious.</li></ul></div><div><br /></div><div><b>Etymology</b></div><div>Theron: "θηρίον" (therion) - Wild Animal, Beast, Untamed, by extension, Hunter</div><div>Ashland: An estate where Ash trees propagate.</div><div><br /></div><div><b>Myer’s Briggs/16-Personalities Type:</b></div><div>Commander: ENTJ-A / ENTJ-T</div><div>Bold, imaginative and strong-willed leaders, always finding a way – or making one.</div><div><br /></div><div><b>Clifton Strengths:</b></div><div><ol style="text-align: left;"><li>Strategic - ENTJs are known for their ability to quickly identify patterns and various possibilities in a given situation.</li><li>Command - This strength aligns with the ENTJ's natural leadership qualities and their ability to take control of a situation and make decisions.</li><li>Achiever - Their driven nature to accomplish goals and constant need for achievement resonates well with this strength.</li><li>Focus - ENTJs typically have the ability to set clear goals and remain on track towards achieving them.</li><li>Significance - They often seek to make a big impact and want their work and presence to be of significant value.</li></ol></div><div><b>Attachment Style:</b></div><div><b>Avoidant</b></div><div>Unhealthy Relationships, Codependent, May be an Addict.</div><div>I’m OK, You’re NOT OK.</div><div>I can self regulate</div><div>I cannot bring my needs to anyone, ever.</div><div>Because I cannot bring my needs to anyone, and some needs require others, I have learned to shut my needs down to the point I may not know they exist. You will have a difficult time feeling connected to me.</div><div><br /></div><div><br /></div><div><br /></div>
