---
title: 'Grounded Cafe (take four) - #WhiteNoise #Distortion'
date: '2023-12-31T08:28:00.0000000+00:00'
draft: false
categories:
  - 'White Noise'
---

<div><i>As I begin writing again, seriously, for the first time since I started my widower journey, I will be posting various rough drafts here. Feel free to consider this an Alpha read...</i></div><div><br /></div><!-- wp:paragraph -->
<p>Ice raced down Ash’s spine, an old familiar call to attention. He turned his head toward movement in his peripheral, was that two hostiles across the street? Through the undusted window of the Grounded Cafe, Ash caught sight of two shadowy figures creeping across the cracked asphalt. Fog clung to the air like a white parka, casting the figures in a blurry haze. <br /><br />Approximately 11 meters, two potential hostiles, he couldn’t make out weapons, but the way they moved indicated non-casual presence.<br /><br />As he turned his full attention to the two figures creeping along the sidewalk on the opposite side of the road, they turned their heads toward him, then dashed behind a parked blue minivan. One peeked out from the van, pointing something his direction.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Was that a gun?</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>A ghostly whisper of danger, the scent of death hung in the air — tangy copper mixed with the dryness of dust. It was a taste Ash had grown accustomed to during his time overseas.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>His right arm shot to the Glock 10mm at his side, cold steal against his palm.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Sucking in a breath to steady himself, he took a second look—</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>They were gone.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Black mist poured out from under the minivan and evaporated into the early morning air.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Shaking his head, Ash closed his eyes, counting to ten, silently as he released his breath slowly, letting it pass over tight lips.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Ash released the grip on his sidearm, which he now realized was a tape measure and not a Glock. Ash hadn’t carried a weapon regularly since he left the service (for this very reason, for safety, to ensure the danger was real before he engaged).</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Really, Ash, come on, what danger could there possibly be in Moon-Wolf Hollow, Idaho? He thought. A random teenager shoplifting is the worst case of crime we’ve had in a whole year.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>These days, he kept his weapons close, but locked in a case, with the ammunition stored separately, until he was at the firing range or doing a demonstrations, as he occasionally did for local organizations. In some other state, he probably wouldn’t own any, but he lived in one of the last remaining hold-outs of freedom in the USA.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Ash noted that his arm was still holding the tape measure stiffly, he let his arm fall to his side, and wiped the sweat from his hands on his pant leg. Reality settled back onto his shoulders. A glimpse of himself in the glass window revealed a strong gray overtaking the sideburns. Other than a few wrinkles, he hadn’t aged that badly. Some might even say he was still young.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“Hello!” Oh yeah, Mrs. Maverick had been asking him a question, what was it? What was she asking?</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“Hello,” She called again. “Ash? Is everything… Okay?”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Ash slowly turned toward, trying to look casual. “I’m sorry, Mrs. Maverick,” Ash said, trying to force an awkward smile into his tense jaw. “I thought I saw- “ what was he going to say that wouldn’t sound crazy? “Nevermind, what was your question again?”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“I was asking-” her lips tightened, and her nostrils flared, then she pulled at the edges of her bright yellow and orange wool blazer. “Would you be willing to do such a large custom project? Do you have the availability for that in your schedule?”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Ash pulled a tattered leather notebook from his messenger bag, and flipped through his notes.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“Honestly,” he replied. I don’t know if I do at this moment. I have several other projects ahead for this next season already. But I might. Let me run some calculations back at my shop, and I’ll get back to you.” Ash forced another smile.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“Very well.” She nodded curtly, and walked to a table at the other end of the cafe, then sat with a small gaggle of other wealthy bored women. Mrs Maverick was one of many such retired house wive’s that had moved to small town Idaho from some other city.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>For the last 50-years or more, the town had a consistent population of 450, give or take a teenager moving away. But the last five years had seen significant growth in the larger towns in the area, and it had spread into Moon-Wolf Hollow, Idaho now. Last estimate was closer to 950, and counting.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Ash turned from his vendor table, against the window in the cafe, and checked to see if anyone else had noticed his momentary lapse of lucidity.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Jenny was selling her soaps and candles at the table next to him, she was busy wrapped up in conversation with a customer, a little old lady who loved her scents.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>James was pretending to organize his ironwork, for the sixtieth time that day, probably to avoid snoring in his camping chair, like he did last weekend.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Craig trimmed his pot-plants at the table on the other side, which was allowed now that Idaho finally caught up with the 21st century and realized it was supposed to be the state of Freedom and not a state where personal morals were shoved down people’s throats. A lot of money on policing and jails was saved by foregoing the persecution of victim-less crimes, and that money was poured into increasing the availability of mental health facilities throughout the state. It was a move Ash had reservations about, but he could see the logic. And it didn’t hurt in his case, as a new facility had opened in town just a few years ago, not that it was staffed at the moment. But, that was a normal small town problem. Craig had given Ash a few pointers on growing himself. He developed a unique selling pitch, by treating them as a form of Bonsai, except you could use the trimming, so to speak.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>There weren’t many customer’s this time of day, but it was one of the last opportunities of the season, before the town buttoned up the hatches for the long winter ahead.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Handfuls of folks lingered, a tourist family staying at the motel next door eyed some crochet stuffies made to look similar to famous movie and cartoon characters, most of which Ash didn’t recognize. He never had kids, and wasn’t much of a kid himself in his youth.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>A young man with a hoodie typed furiously at a keyboard.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>A woman jabbered away on the phone, failing to pacify the toddler in the stroller to her side.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Two men spoke in hushed tones at a table not far from Ash.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>A purple and white haze turned Ash’s attention back to the sidewalk outside, a woman in a purple hoodie walked by just outside the window, head buried in her smartphone. She bumped into Hank, the town’s crazy old homeless man who was headed the other direction, into the foggy evening. She didn’t appear to notice him. He gave her a dirty look and kept walking the other way, mumbling to himself as usual.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>The woman sat down at a table just outside the farthest window of the Cafe, he couldn’t make out her face, possibly one of the towns last tourists before the few stores left went into hibernation.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>An orange Maple leaf lazily floated down to the table in front her. She brushed it aside, and it fell inside a pumpkin whose top had been kicked off. The leaf caught on fire from the candle, and slowly embered away. She didn’t take notice of that either. A purple and white vapor swaddled her like a blanket, as she leaned over an open book of some kind.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Old Hank stared at her from the corner of the building. A small green frog sat on his shoulder. The bottom half of the frog was a mist that disappeared into Hank’s spine. The frog’s red eyes stared at her, then at Ash, and it cocked its head to one side. Then it was gone, in a whisp of grey-green fog that continued to waft around Hank as he walked away out of sight.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Ash didn’t see these creatures on every person, every time, but almost everyone had a mist cloak. Though some people’s mists were more pronounced, while others were barely visible</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>The town psychic, Genevieve, called it an “aura”, when he explained it to her in a rather desperate confidence one day. “Some of them must have a stronger aura,” she suggested. She was a bit of a quack but he was willing to try everything to at least understand it if he couldn’t get rid of it.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>He’d been to quite a few doctors, and that having born no fruit, he went to pastors, priests, the town psychic, a passing faith-healer, and even a local Rabbi from a larger town nearby. Each of them had their opinions and suggestions. While non of them offered any real relief, the Rabbi was the most gentle and inquisitive of the bunch, more often asking honest and curious questions, and offering few if any answers. But at least Ash felt heard and understood with the Rabbi, who had nothing to sell but time, and a good chat over coffee.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Generally, the creatures came from within a person and would go back into them, like human genie bottles. Not everyone had a creature, but people sometimes did. The Creatures weren’t all alike, either. There were repeats of similar versions, but each seemed unique to the person.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“You don’t fit the profile for Schizoaffective Disorder, as your life and thinking are otherwise quite normative. I would call this Post Traumatic Stress Disorder with Psychotic Features. This is rare, but can happen with serious abuse or trauma, then again, we could have a traumatic brain injury affecting the visual cortex. The mind is still a mystery to us in many ways…”, his latest doctor had offered this explanation before he left the clinic without a town shrink six months ago.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>The VA docs tried giving him a mountain of drugs to help him sleep and keep the delusions at a minimum. Nothing really helped, most made it worse.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>When the Federal government forced legalized medicinal THC on all the states as a human right, and Idaho finally gave up on the failed war on drugs and allowed doctors and people to choose their own path in life, his Idaho VA doctor said to try pot, as it was clinically shown to have better results for some people that anti-psychotics. Ash didn’t bother telling the VA doc that he’d already been growing it on his property for several years now.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>The magical medical folks at Big Pharma managed to create a pill form with less hallucinogenic properties and twice the pain killing properties, but it cost too much and his VA insurance didn’t cover it yet, although the decision was before the Senate hearing committee, thanks to PTSD Health advocates. If the Fed would just finish eliminating for-profit medicine, he could try that someday. The only thing he hated more than big government was big pharma and big corporations.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>He liked living in one of the last small towns where people left people alone to be themselves.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>For now, Ash started growing it himself a few years ago, his sleep was more regular but the delusions came and went. He could still hear the original diagnosis in his mind.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“As long as you are not a harm to yourself or others, you should be just fine. Think of it as an amusing distraction,” the doctor advised.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>— Ash heard his name.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“Ash-”, Derek the Barist’ called his attention to the present, standing in front of his table with a frosty blending drink, and green whip cream. “Here you go, man. Extra large Java-Chip, almond milk, six shots, with peppermint and crème de menthe. I even through a few extra candied coffee beans on there for you.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Derek’s mists swirled around in deep blue and a streaks of orange. Ash couldn’t remember the last time he’d seen Derek get angry, even when some tourist was giving him a tongue lashing for being too slow.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“Thanks, Derek”, Ash said as he took the drink gratefully.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“Always my friend,” Derek said. “How’s business been today?”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“I haven’t sold much, but it’s nice to get out of the house a few more times before the snow makes it hard to leave the property.” Ash took a sip, the cold creamy mint made his mouth tingle, “… this is really good.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>He set it down. “I mean… I can get the tractor and snow blower out and punch my way down the road when I have to. But 110 acres is a lot to manage, and my house isn’t exactly off the main road.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“I get. I don’t know how you guys live that far out of town, my hats off to you for the effort. But I do appreciate how nice it is. Should we have another meeting up there before the roads become impassable?”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“I think we can do that — “ Ash stopped when he noticed Sam walk in, and waved him over to join them.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“Sam,” Derek gave him a bear hug, “We should have the next Kairos meeting at Ash’s house, before the road become impassable. I can help him get it ready for guests.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Sam smiled, but he gave Ash a sideways glance. “How are you feeling about this idea? Is it too much? Are you okay, you looked a little tense earlier, through the window.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Ash felt his gut tighten, Sam had noticed. If anyone would notice, it was Sam. He squinted at Sam, he felt the question scroll across his face, but couldn’t gather the words to ask it without sounding crazy.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“I was in the jeep,” Sam offered.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“Ah,” Ash replied. “I’m alright, I think it would be good for me.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“Okay,” Sam shrugged. “You bring food, and I’ll bring drinks?”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Derek squinted at Sam, “As long as you don’t bring that piss water you brought last time!”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Sam grinned, “I’ll behave and bring something a distinguished gentleman like you would approve of.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“Then I accept,” Derek shook Sam’s hand, then Ash’s, and then headed back to his coffee machines.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Ash wasn’t sure about all the Bible stuff, but he enjoyed having a crew around him, it reminded him of his team in the service. So he put up with the religious part for the sake of comradery, besides, most of the time they just talked about town stuff, news, or sports.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“Hey,” Sam turned his full attention to Ash. “Did you hear the news?”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Ash picked up one of his popular Sasquatch figurines, wiggling it in front of Sam, “They finally found Big Foot?” Ash noted that it felt good to smile, he didn’t do that enough lately.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“No, still looking I’m afraid-“ Sam still laughed at his jokes, like when they were kids. “They found a new doctor for the clinic. He just came into town last week, he’s staying at the hotel until his rental cabin is set up. His moving truck comes in tomorrow and he’s bringing some new equipment to town. He said he’ll be ready to start seeing clients by the end of week.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“That’s good, especially with Old Hank hanging around again.” Ash nodded to Old Hank still outside the window, but now barely noticeable from the corner of the building, peeping at all the people in the shop.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“Yeah, but,” Sam replied, and used an over exaggerated nod back to Ash. “I think this guy might be able to help you.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“What’s this guy got that the last fifty hasn’t?” Ash asked.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“This guy is a bid deal or something. I’m not sure where they picked him up, He says he’s here to enjoy a semi-retirement or something. He’s a PhD out of Harvard or Yale or one of those big stuffy places with smart people.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“Hmm —“ Ash started to form a reply, but lost it. The fog outside was creeping into his head. It had been a longer week than he planned, more sales than he hoped, which was great, but exhausting. “I guess we’ll see. I’ll check in with him after the Oktoberfest this weekend.”</p>
<!-- /wp:paragraph -->
