---
title: 'Reflecting on my new writing process...'
date: '2025-03-10T05:56:00.0010000+00:00'
draft: false
categories:
  - 'Storytelling'
  - 'FAAFO'
---

I've been busy with life, work, and school. I haven't had a weekend to dedicate to writing in a while. But I forced a few minutes out of the end of tonight. It was hard at first, like that writers block feeling of staring at a blank page, even though it wasn't blank as I had started chapter 3 two weeks ago. But I felt "lost", like "where am I going with this"?&nbsp;<div><br></div><div>So, taking queues both from my template (what tiny goal are we trying to achieve right now and how can we answer it with yes/but or no/and), and queues from the other writing lessons I've learned (what are each characters motives, what would the twin cats care about, that will affect what they say and what he learns...)... And then taking detour into dialogues with AI about what currency might look like in a world with ubiquitous magic and real gods...&nbsp;</div><div><br></div><div>It began to take shape. It started slow, like cold honey, and then began to flow more easily as I explored those ideas.&nbsp;</div><div><br></div><div>It began to feel like a block of marble that I was chipping away at carefully, to see what figure might be waiting to be uncovered, as some famous artist said, I think?</div><div><br></div><div>And even after only about 20 minutes doing these things, I felt completely unstuck.&nbsp;</div><div><br></div><div>This process is working. I'm not going to haul off and teach a class until I'm at least 500 chapters into it and I know it's working. &nbsp;</div><div><br></div><div>But I definitely feel this process has merit. And others don't need my process. But I can show them techniques and tools and flavors, and let them become their own chefs, as Brandon Sanderson says.&nbsp;</div><div><br></div><div>Lastly, I began writing my "Integrative Statement" for a seminary class. It's oddly vague instructions left me floundering a bit.&nbsp;</div><div><br></div><div>But I recalled the professor says he did that on purpose to let us put what we wanted.&nbsp;</div><div><br></div><div>As I drafted the first section, I realized that all my biblical studies in academics are making my storytelling better. This is because, despite European theologians best attempts to obscure this with their stupid "systems", the biblical authors were deeply saturated in narrative, story, metaphor, allegory, poetic imagery, and using the written arts to weave together and explore archetypes of the human condition.&nbsp;</div><div><br></div><div>CS Lewis and JRR Tolkien and Brandon Sanderson all do the same. So did Jesus.&nbsp;</div><div><br></div><div>This is the model. This is The Way.&nbsp;</div><div><br></div><div>Story as Device, but not preaching.&nbsp;</div>
