---
title: 'FAAFO (Fuck Around, And Find Out) | Manna, Sarcasm, & Burritos (MSB), Season 1'
date: '2025-02-16T04:31:00.0000000+00:00'
draft: false
categories:
  - 'FAAFO'
  - 'MSB'
---

<h1 style="text-align: left;">Manna, Sarcasm, &amp; Burritos (MSB), Season 1</h1><div><h2 style="text-align: left;">FAAFO (Fuck Around, And Find Out)</h2><div><br /></div><div>First things first…</div><div><br /></div><div>While humorous, this working title has a purpose.&nbsp;</div><div><br /></div><div><b>TLDR: I want to try an experiment, test the results, and pivot as needed. I want to Fuck Around… and Find Out if it works. Ha ha. I’m sure Royal Road won’t let me post that title, so I’ll come up with something better for the postings.&nbsp;</b></div><div><br /></div><div>I’ve been studying the craft of writing for years now. I kept running into dead-ends with my main story (White Noise, Distortion). I will get back to it someday, but I’m too close to it, and I need a new outlet.&nbsp;</div><div><br /></div><div>I heard that Shirtaloon (Travis Deverell) was a fellow academic, a graduate student. He just NEEDED to write something silly, so he started “He Who Fights with Monsters” on Royal Road. It took off, and eventually he started an entire brand around it.&nbsp;</div><div><br /></div><div><a href="https://hewhofightswithmonsters.com/" target="_blank">Shirtaloon </a>/ <a href="https://hewhofightswithmonsters.com/" target="_blank">About — Shirtaloon</a> / Quote:</div><div><br /></div><blockquote style="border: none; margin: 0px 0px 0px 40px; padding: 0px; text-align: left;"><div><i>In the middle of penning a dry academic paper, Shirtaloon had a revelation: he desperately needed to write something very silly.&nbsp;</i></div><div><i>It all begins with an idea. Maybe you want to launch a business. Maybe you want to turn a hobby into something more. Or maybe you have a creative project to share with the world. Whatever it is, the way you tell your story online can make all the difference.&nbsp;</i></div><div><i>To his surprise and delight, he found a warm and welcoming audience in the world of online serialized fiction. Transitioning his work into actual books, he is continually startled at the appetite for his particular blend of high magic, wild adventure and absurd nonsense.&nbsp;</i></div><div><i>Success has allowed him to fund an excessive board game collection he doesn’t have time to play because he’s always writing. The unplayed games sit on the shelves behind him as he works, silently judging.</i></div></blockquote><div><br /></div><div><br /></div><div>Along with the other authors and writing teachers I have listed at <a href="https://www.darrellwolfe.com/p/writing-craft-database.html" target="_blank">Writing StoryCraft Database</a>, Shirtaloon is my inspiration for taking this next journey.&nbsp;</div><div><br /></div><div>I want to start a new story, to which I have no emotional ties. Take it as far as it will go, be that three chapters, or three hundred chapters, and take it further if it gains traction.&nbsp;</div><div><br /></div><div>Ultimately, I just want an outlet to practice fiction with low commitment.&nbsp;</div><div><br /></div><div>As such, I want to post the chapters on Royal Road, Substack, and my own personal blog (DarrellWolfe.com), offer the option of “<a href="http://buymeacoffee.com/darrellwolfestoryteller" target="_blank">Buy Me a Coffee</a>” but make no promises as to the frequency of my writing at this time. If for some reason it really takes off, I will dedicate to it full-time, but for now, I just want an outlet to practice without the commitment of writing a book in full. I also know this is a great way to get alpha and beta readers to provide feedback, so I hope to improve my craft over time.&nbsp;</div><div><br /></div><div><br /></div><div>DarrellWolfe.com</div><blockquote style="border: none; margin: 0px 0px 0px 40px; padding: 0px;"><div style="text-align: left;"><br /></div></blockquote><div><a href="https://www.darrellwolfe.com/p/writing-craft-database.html" target="_blank">DarrellWolfe's Profile | Royal Road&nbsp;</a></div><div><br /></div><div><a href="https://www.darrellwolfe.com/p/writing-craft-database.html" target="_blank">Darrell G. Wolfe (D.G. Wolfe) (@darrellwolfe) - Wattpad&nbsp;</a></div><div><br /></div><div><a href="https://www.darrellwolfe.com/p/writing-craft-database.html" target="_blank">Darrell Wolfe | Substack&nbsp;</a></div><div><br /></div><div>“<a href="http://buymeacoffee.com/darrellwolfestoryteller" target="_blank">Buy Me a Coffee</a>”</div><div><br /></div><h2 style="text-align: left;">AI Disclosure</h2><blockquote style="border: none; margin: 0px 0px 0px 40px; padding: 0px;"><div style="text-align: left;"><i>"I utilize artificial intelligence to assist with brainstorming ideas, conducting research, and performing basic editing tasks for my stories. However, I do not use AI to write my stories or to generate extensive portions of content. My use of AI is strictly as a supportive tool to enhance my own creative process."</i></div></blockquote><div><br /></div><div><br /></div><h2 style="text-align: left;">This story is about…</h2><div><br /></div><div>Right now I only have a vague idea and I'm going to start with posting one chapter only and then decide where it goes.&nbsp;</div><div><br /></div><div>I do vaguely believe that the character starts off both financially devastated and personally devastated as a young widower. Out of necessity, Mark decides to take part in an experiment as a test subject for money. Plus he figures his life can't get any worse. After the experiment he discovers the ability to see beyond the veil. But then, he is sucked into an alternate universe full of read gods, myths, legends, magic, etc.&nbsp;</div><div><br /></div><div>The alternate universe will have an litRPG style progression, but may or may not have the video game tropes. I suspect his sense of progression will come through magical texts, gods called Watchers, and his ability development.</div><div><br /></div><div>The story will definitely have magic and magical creatures and pull from the ancient near East Divine Council themes and mythologies.&nbsp;</div><div><br /></div><div>It might even pull some Akkadian, Ugaritic, and Hebrew language, although it will be transliterated and probably fictionalized or morphed for the story purposes.&nbsp;</div><div><br /></div><div>In much the same way Stargate SG1 felt grounded because it pulled from actual Myths and Legends, from the real world, I want to do the same. I will eventually pulls from as many cultures as possible, ANE, Egyptian, Europe/Thor?, China, Choctaw/indigenous peoples, etc. But they will be morphed into my story needs and fictionalized.</div><div><br /></div><div>I want the tone to be sarcastic and fun, but also handle serious topics, pulling from religion, history, philosophy, psychology, and more.</div><div><br /></div><div>Mark is a 30-year old widower, who was financially devastated as a result of his wife’s death, and he finds an advert to get paid as a test subject. The results leave him interacting with the unseen realm, and eventually sucked into an alternate reality.&nbsp;</div><div><br /></div><div>Will this story start en-media-res, or will it start right there? I think I’ll write those scenes for discovery and then decide what actually becomes the origin post.</div><div><br /></div><div>I think on the blog, I will post under two tags:</div><div><ul style="text-align: left;"><li><a href="https://www.darrellwolfe.com/search/label/FAAFO" target="_blank">FAAFO </a>- For updates about what I'm learning, or the craft of writing, business of writing, etc.</li><li><a href="https://www.darrellwolfe.com/search/label/WatcherChronicles" target="_blank">WatcherChronicles </a>- Chapters/Episodes, actual fiction writing.</li></ul></div><div><br /></div><div>Let the fucking around and finding out begin…&nbsp;</div><div><br /></div><div><br /></div><div><br /></div>
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
</div>
