---
title: 'Chapter 1 - Burritos, Dreams, and a Magical Tattoo'
date: '2025-02-16T21:04:00.0000000+00:00'
draft: false
categories:
  - 'MSB'
---
Markus wanted a burrito.

He kicked a pile of take-out containers aside near the overflowing trashcan and opened the small apartment fridge. He was greeted by the familiar scent of old milk and the sight of nothingness.

Sighing, Markus closed the fridge and stood staring at this collection of magnets,

"Sorry I'm Late. I Didn't Want to Come."

"This House Runs on Coffee, Chaos, and Cuss Words."

"Everything Happens for a Reason. Sometimes That Reason is You Were Dumb."

"Procrastinators Unite\... Tomorrow."

Then his eyes landed on the center magnet,

"If You're Looking for a Sign, This is It."

Momentarily amused, Markus took a deep breath, ran his hand over Janie the Cat who was resting on top of the fridge, as usual. It was a bit chilly, if by bit you mean you can see your breath on the wind. So he grabbed his coat and headed down the street to the local Food Truck Pavilion.

As he arrived at Jorge's Famous Tacos, the line was so long it wrapped around the corner, and he decided to try his luck at the ATM while he waited.

Denied.

He tried another card.

Denied.

His warped reflection from the sheet metal wall behind the ATM mocked him, his ragged beard, now showing a wisp of grey, and decided he probably needed to shower today when he got home. Before walking away, Markus rifled through his wallet looking for any other cards or hidden money, coupons, anything. He found a third card that he had forgotten was even in his wallet.

Markus held the card to his chest and whispered "Please". When he put the card into the machine there was a flash on the screen. It didn't ask him for his PIN. Instead, it beeped and out came a twenty dollar bill. Not one to look a gift horse in the mouth, he took it and put it in his wallet. The screen read, "Balance \$ -19.50." That was the last of his money for another week and a half. He would probably have to sell blood again tomorrow. But at least he could have a burrito today.

Waiting in line, Markus thought about how he and his late-wife used to come here and dream about the future, laugh about some mishap at work, or talk about his stories.

It was their spot.

Now it was his.

His smile faded.

"She was too young," he half-whispered to himself as he took another step forward in line. Pregnancy is supposed to be a happy thing, their first child. One night they sat on the couch and talked about their plans, their future, their hopes. The next morning she woke up him to tell him she wasn't feeling well, and she collapsed in the living room.

Panic.

Emergency personnel, a flurry of activity.

"I'm calling time," the doctor said. Not that Markus heard it clearly, but as through a haze.

Just like that, all those plans shattered into a million pieces of glass, then floated away on the wind like dust, the words "Blood Clot" forever seared into his psyche.

"Three years," he said under his breath. "... it can't be three years already."

The line moved forward. A young girl and her mother passed by, about the age his daughter would have been, holding her mother's hand, begging for ice cream. He took a deep breath, letting it out slowly, just as his grief counselor had taught him.

The intensity of the pain in those early years had faded to a dull ache, and even that was only a background noise to his daily life. That was, until his novel royalties dried up, and his company laid half the staff off a few weeks ago.

His parents were in his hometown still, and they offered to let him move home when-, he felt his chest ache. When he became a widower. Maybe he could take them up on it now, since things were so awful. But, he still felt like holding out, something had to go his way soon, right?

His turn in line. Jorge waved at him from the line, and turned back to his busy tickets. Jorge's wife just nodded and smiled, knowing his order by heart.

Just as he handed the magical last twenty to the cashier, his grip loosened and the twenty dollar bill flew away into the wind. They both looked at it fly away, watching it float higher and higher into the distance.

Markus teared up, balled his fists, and started to visibly shake.

He tried his magical card at the register.

Declined.

No magic left in you today, he thought. Dejected, he  turned to walk away.

"Listen, Markus," Juliana said, "We know you. This one is on us, okay?"

In another life, Markus would never have accepted, he wasn't a helpless schmuck. But, really, lately, he was just that. He couldn't even keep his trash cans empty at home. So swallowing his pride, he nodded, offered a tight smile, and took the burrito.

The walk of shame to the covered, heated, seating area felt like a bag of rocks on his shoulders. Seeing the throngs of people taking up most of the tables inside the eatery, and feeling the chill of the wind on his neck, he opted to eat at home. "It's less human-ey at home anyway." He muttered to himself.

As he left the Pavilion, a flyer stuck to his shoe. He tried shaking it off, but it wouldn't budge. He pulled it off the bottom of his shoe, and read it.

"Broke? Paid Test Subjects Needed. For details see Esion Etihw Institute website, link below..."

The flyer was torn, and the website was missing. "Desperate times..." Markus said to nobody in particular, and stuffed the flyer in his pocket.

***

At his unkempt apartment, Markus sat on the couch and began flipping through the Netflix and Hulu shows as he ate his burrito.  Janie the Cat, a calico with one green eye and one blue eye, watched him intently from the coffee table, apparently waiting for Markus to drop some of his food.

"Ugh, I forgot to feed you again, didn't I?"

*Meow* She cocked her head expectantly.

As he glanced back at his kitchen, he winced. There was no cat food. He remembered. He took a morsel of chicken from the burrito, and handed it to her.

"I'll get you food, I promise."

*Meow* She cocked her head the other way.

Markus felt guilty, and handed her another piece of chicken from his burrito. Which she gladly ate. Then Janie jumped over onto the couch, and began pulling at his pockets.

"I don't have any food hiding in there. Okay? I'll try to find you some in a minute. Maybe there's some tuna in the cupboard. I'll look in a minute I promise."

*Meow* Janie the Cat aggressively tugged at his pocket.

Markus stood up, annoyed. "Look," He pulled his pockets inside out. "No food." As he did, the flyer from the Pavilion fell to the floor and Janie went to pounce on it.

Shaking his head, Markus sat back down and went back to scrolling. But Janie the Cat grabbed the flyer, and brought it to him, placing it on his lap.

He grabbed the flyer back and tossed it on the coffee table.

Janie the Cat jumped over to the table, grabbed it, and placed it back on his lap.

"Insistent today, huh?" He said.

Inspecting the flyer again, Markus read it out-loud to Janie, "Broke? Paid Test Subjects Needed. For details see Esion Etihw Institute website, link below..."

Markus tried sounding out the name of the business and mused to Janie the Cat, "that looks French or some shit, I guess."

A Google Search wasn't helpful, as it was full of advertisements. But as a software developer, currently without a contract, Markus was on his last paid month of ChattyCathyAI-Pro, before his former employers' subscription ran out at the end of the month.  He ran the name through the AI search engine, and the results came back with a brief description of the company and a link.

"Esion Etihw Institute is an industry leader in dimensional research. We use bleeding edge techniques including  sensory manipulation, psychoacoustics, and psychotropic therapies to transcend human limitations and explore the possibilities of extra dimensionality. One day, we will break the bonds of our existence."

After clicking the link, he was greeted by a landing page that said, "Apply now to be a paid test subject. We pay same day, in cash. And you just might become a super human."

"Well," Markus said. "I have no idea what any of that is supposed to mean. But getting paid to be a lab rat is better than not getting paid to be a developer or writer." So he filled out the application, and hit submit. Janie the Cat was asleep and purring next to him, and had eaten the last half of his burrito while was he was distracted.

"I guess I deserve that," he said. Janie curled up tighter. He felt bad, when was the last time he fed her, anyway? Flipping through more shows, Markus landed on Schitt's Creek. "As bad as they have it," He said to sleeping Janie, "... they have each other."

***

A few freelance jobs, that were so small he would have laughed at them a year ago, got him through the week. At the end of the week, Markus was a half hour early to the testing facility, which was in against a hill on the outskirts of town. He paced the lobby, palms sweaty, and tried to strike up a conversation with the administrative assistant working the front desk.

"So how do you pronounce that name, anyway?"

"It is pronounced, Ess Eeon Et Eeww"

"Is it French?"

"No." She replied, with a practiced smile.

The phone rang and she held up a finger to Markus. Speaking to the caller, "Yes, Mr. Thaddeus. I understand. I'll tell him."

Turning to Markus, she said, "Excuse me." Then she disappeared into an office door behind the desk.

With no-one to pester with questions, or feel awkward about, Markus walked the room checking out the PR Posters and write ups about the institute in scientific magazines, "Breakthrough in audio therapy..." I wonder what that means.

One realistic painting of a golf course near a forest looked hyper realistic. As he stared at the intricate detail, the image shimmered and distorted, like summer heat waves in a window pane. Then the trees in the painting began to sway, and then there was a small figure riding a large dinosaur who walked out of the forest.

The scene zoomed in, and the man, wearing white robes, gave Markus a wild grin.

*Ding*, the elevator behind him warned of someone approaching his floor, just two floors to go on the way down.

Markus turned to face the other direction. When he glanced back to the painting, the image was back to being a still image of the company golf course.

"You're seeing things, my dude. You need sleep." Markus mumbled to himself. He made a mental note to check the cost of out-of-pocket medications and use his test-subject paycheck to obtain some as soon as possible.

As he waited, he realized the painting reminded him of his recurring dream. At least once a year, since he was six, he dreamed about the portal that took him to the wild group of humans co-habiting with dinosaurs. He could still feel the musty robes on the old man, with the wild look in his eye, "The Watchers are coming..." Then he would wake up, it always started and ended in the same place, for thirty years. Markus even wrote a book about it, that was successful for a time, but the royalties had since dried up. And with the death of his wife, he just couldn't get himself to write the sequel. The dream happened again last night.

He was 36 today. A great day to die from being a lab rat. Everything else is gone, maybe now it's his turn to die in a facility full of doctors. He shrugged. He kept watching the painting, waiting for it to turn into a movie again, but it remained still.

The elevator doors opened behind him. "Hello," a friendly voice said.

Markus turned around to see a brunette woman in a lab coat, holding a digital tablet, and smiling with a friendly smile and relaxed posture. "You must be Markus." She said.

"Yes, Um..." Markus glanced back at the image of the golf course. It was still just a painting.

"That catches people's attention often. It's a painting, but the real golf course looks just as impressive." She motioned for him to follow.

"I'm Jay, by the way," She said. "Like the bird. Right this way, Markus." She ushered him into the elevator.

***

As they approached the testing room, Markus got his first glimpse at the famous Anechoic chamber

(also called the Negative Sound Chamber). It was a large grey room, filled with sound baffling triangles of various sizes and directions. Floor, ceiling, and walls were covered in them, but the floor had a sturdy wire frame to walk on, so as not to disturb the sound padding.

In the center, was a chair, much like a dentist chair. Next to the chair was a machine with wires, and above the chair was a large speaker aimed directly down.

Jay ushered Markus to sit, "As covered in the orientation video, these wires will monitor your vital signs and record valuable data from the test. We will ask you a series of questions to understand any subjective experiences you have had. This room makes people nervous, so this will help you relax."

Jay handed him a small gummy bear, which he thought was funny, and he sat and chewed on it while she strapped him with wires. "These restraints are for your protection. This room will be pitch black, and sometimes participants want to get up, we don't want you hurting yourself or the equipment, so we strap you in. If it is too overwhelming, say so. We can hear you, we will stop the experiment and debrief."

"You know how to make a guy feel special," Markus half-giggled to himself.

Jay unbuttoned his shirt and placed the final electrodes on his chest. As her fingers brushed his chest, he was reminded of how long it had been since another human touched him. He felt an ache in his chest, but took a breath.

Noticing his tightened reaction, Jay asked, "You okay?"

"Oh I'm fine," Markus lied. "Your fingers were cold." He let out a nervous chuckle. She nodded and kept working.

"I assure you, test is unorthodox, but safe." She left him in the chair and closed the door.

Finally, he was alone, strapped to a chair, in a pitch black room.

"Is this what my life has come to?" He said out-loud. Immediately he noticed how hallow his voice felt. In a normal room, your voice bounces off the walls. Here, the walls ate your voice. Odd sensation. Markus opted not to speak out-loud for the rest of the test.

A soft hissing came from the speaker above him, reminiscent of a breeze or ocean waves. And he felt himself getting tired, warm, and fuzzy, as if he was buzzed at the bar. Then his vision began shifting. White smoke filled his vision in the otherwise dark room. The smoke started to take shapes, then began to look like animals and humans moving about. It was both terrifying and compelling. He couldn't look away, he felt drawn to them. But he couldn't reach them, because he was strapped to the chair. Then the shapes faded, and the darkness came back.

Markus wasn't sure if he had fallen asleep, or not, but was informed he had been in the room for the full six hours, which was longer than almost any other participant to date. The data they obtained was helpful, and they debriefed him on his experience, including a questionnaire.

Jay was quite animated after their debrief, and assured him she would be in touch at a later date. Then they deposited the test money into his Venmo account.

"We are paying you right now," Jay pressed a few buttons on her tablet, and nodded.

Markus' phone buzzed in his pocket. He looked at the Venmo message, and his heart skipped a beat. "Is there a mistake?"

"No mistake," Jay said.  "To be frank," she became a bit more animated, as they walked the lobby to the front door. "No other recent test subject has ever stayed the full six hours. We are giving you the full sum allotted to a full day test."

Markus shook her hand, "Thank you, thank you so much!" He decided to leave quickly before they changed their mind or delivered a catch.

On the bus, heading home, he looked at his phone in disbelief.

\$1,000.00 USD

"That's a lot of burritos..."

***

A few stops before home, Markus got off the bus, and grabbed some tacos, then headed to the cemetery. He sat at his late-wife's graveside, and placed a taco on the headstone. "This one is yours," and he held his up to hers as if it were a toast.

The cemetery was peaceful, and he always felt like he belonged here for some reason. "It's been three years..."  he said quietly to the headstone. "What are we going to do, Kitten? This is a lot of money, but it won't last long."

A light breeze whipped some wind chimes into song, and then a light shone through the clouds onto the center of a tree trunk nearby. The light grew until it was nearly blinding, then opened into a scene in front of him, with distant figures and shapes moving inside. "No no no no no no... ", he said and ran home.

After shutting the door behind him, Janie the Cat walked up and walked through his legs several times. His breath finally caught up with him, and he shook his head, and rubbed his eyes.

"I'm losing it Janie girl," he said.

Pacing the room, his phone rang to the Esion Etihw Institute, no answer. He tried ten more times, and finally relented to leaving a voice-mail. "You told me to call if there were any lingering side effects. Give me a call back."

Then he remembered that he forgot to stop at the store on the way home. He looked at Janie apologetically, then noticed the birthday card on the cabinet door. It was taped there by his late-wife, who was also a Janie, which is how Janie the Cat got her name. He was used to speaking with Janie the Human, but she's gone. So when the cat showed up, she became Janie the Cat.

He opened the card, and saw her handwriting, "Welcome to The Suck - May the Odds Be Ever In Your Favor. Happy 30th Birthday." Markus ached for her, for the memory, for the day, for his unraveling mental health.

*Meow* Janie the Cat looked at the cabinet door in anticipation.

Markus opened the door to see if there was any cat food left. He began reaching for what might be a can of tuna hiding in the back, when the entire doorway burst into light.

Just then, Janie jumped up into his arms causing him to lose his balance, and he fell into the light.

"No no no no no no no no no no no no no no no no no-"

***

When his vision returned, Markus found himself on his back, on the grass, looking at a sunny day with clouds dotting the sky, barely hiding the three suns.

Three suns!? He bolted to an upright position and looked around.

Janie the Cat was perched on a nearby rock. All around them was a forest of pine trees. As Markus stood, shakily, feeling his body for injuries, he felt a faint buzzing all around him and in him.

He did not notice any other people or animals, and then looked back to Janie the Cat, "What have we gotten into now? What kind of drugs did they give me?"

"I wondered when you were going to wake up."

Markus looked around for the voice, pivoting a full 360 degrees. But he saw no other people. "I need to wake up, I need to wake up, I need to wake up and get home..."

"Home? Why," the voice clearly now coming from Janie the Cat. "After all the effort it took to get you back here, that's just rude," she teased.

Markus stared at her in disbelief, "Did you just talk? Wait, Back here? Wait, did you just talk?"

Janie settled into a curl, front paws in folded onto one another, "Well not here, exactly. Here, but not here. Not now. Now is not then. But now is still here. Then is here. But then is not now." She paused, bobbing her head side to side, thoughtfully, chewing on that explanation, and then looked back to him and smiled.

"You're a talking cat," Markus said to himself. "This is a really weird trip." Then he remembered eating the gummy at the testing center. "Ah, this is a trip. I'm on an LSD trip, or whatever was in that gummy. I really need to wake up."

Then he got dizzy, and placed his hand on a tree trunk to steady himself.

"Eat this," Janie said. A small piece of bread floated to him.

"Isn't that how I got into this mess?" Markus said. "My cat is talking and sending me bread with telekinesis. This is a weird freaking trip."

"Technically, not telekinesis, it is Mishkahlism." Janie's voice was calm and curious, not rushed. "It is using the mind, but all Manna Arts use the mind and will. Specifically, in this case, I am simply changing the density of the object in relation to the mass around it, not dissimilar to the way a balloon full of air stays on the ground but when full of Helium it floats. It's just basic science. Well, for these parts anyway."

"I see..." Markus started, then let the phrase fade slowly off his tongue. "Um. Huh."

Markus eyed the floating bread carefully, then looked at it from various angles, as it bobbed ever so slightly in the air. He waved his hands above and below and around. It reminded him vaguely of a scone.

"No strings," He said more to himself than to Janie. Hesitantly, he took the bread floating steadily in front of him, and gave her one last look.

Janie motioned to him with her paw and nodded.

"I mean," Markus said to her. "I'm already on a trip, so, why not eat floating magical bread while talking to a cat that talks back."

Taking a small hesitant nibble, Markus noted the taste was bland, somewhat bitter, with a slight sweetness that offset the bitter. He could imagine liking it with some butter and honey.

"It's a bit dry," He coughed some crumbs.

"Oh yes, yes yes," Janie chided herself. "How silly of me. Come-come." She hopped down from the rock and nodded for him to follow."

Janie meandered in a sauntering non-straight line through the trees, humming a tune to herself that sounded familiar.

"Is that Moonlight Serenade by Glenn Miller?" He asked her.

"Indeed," Janie smiled at back at him before continuing their journey. "It is one of my favorite songs from your reality."

They walked through the forest a few moments and just beyond their clearing, over a hill, they came up to a stream. Janie approached, sniffed the stream, and licked some water for herself. Then she tasted it with a thoughtful posture for a moment. Finally, she turned to Markus, "It's safe. This water is Tov. You can drink it."

Still feeling dryness in his mouth from the crumbs of his nibble, he drank the water by cupping his hands to his mouth. With the water making it palatable, he finished the bread. A sense of energy washed over him and his whole body became warmer, his muscles stronger, and his mind clearer.

"What is that?"

"It's a Manna Cake. I think that particular one is from Skybread, though I much prefer Ethereal Bites or Angel's Crust. But it's been in my dimensional storage so long, I'm not quite sure who made it now."

"You have dimensional storage?" Markus raised his eyebrow at her.

"Heavens yes," Janie said, clicking her tongue at him. "Tch tch tch tch tch. I never would have survived living with you if I didn't gather and store my own food."

Markus felt his cheeks flush with embarrassment and guilt, "Oh, um, Geeze, I'm sorry about that. I've just been so..." He trailed off, not sure how to finish the sentence, and then still feeling crazy for talking to a cat that talks back.

"Markus," Janie sat up straighter. "Look at me."

He found himself staring into her dual colored eyes for a moment, seeing in them a person and not a pet for the first time.

"It's not your fault. The accident, the way you've been living, the pain, the lack of self-care-" her voice cut off as the sound of branches breaking in the near distance caught both of their attention.

"Oh bother," Janie finally said. "Not yet, he's not ready. I just got him here." She spoke staring up at the sky, listening for a moment. She paused, then replied to the sky "Ugh! Fine, fine."

She walked up to Markus, who was still sitting on the grass near the stream.

"I need you to listen carefully. Pick up that stick." Janie nodded to a stick about the length of his leg.

He felt a sense of urgency in her voice that wasn't there before, so he picked it up. The stick felt good in his hand, almost like playing swords as a kid.

"Listen!" Janie warned with new urgency. The sound of something brushing against the trees and breaking twigs came closer.

"Tell the stick to defend you. Say it. 'Defend me'. Do it, now!"

Markus felt cold sweat rush down his back at the mystery sounds coming, and the sudden urgency of her tone.

"Um..." He tried to find his voice. "Defend me, Mr Stick."

A surge of blue light encircled his body, flowed down his arms and enveloped the stick. It began to pulse and grow brighter blue, and then a faint humming sound came from the pulses. Images of a Jedi holding a light saber rush through his mind.

Out of the trees walked a huge white and grey wolf, on all fours, with neck-hair bristling to a point. It was nearly the same size as Markus, and possibly heavier. Behind it, three smaller wolves flanked.

His skin felt prickly, and his palms sweaty, as Markus held the stick tighter. It began pulsing with energy and blue light.

The lead wolf glanced at Janie, who was now perched on a tree branch up high, and growled in a low barely audible tone. After a few deafening moments, it slowly drew its gaze back to Markus, who took a step back at the eye contact.

Suffocating stillness lasting for a few moments, Markus barely breathing.

Couching on his front paws, then bouncing forward, the wolf lunged at Markus, teeth snapping open.

More from fearful instinct than anything resembling skill, Markus swung the glowing stick and it struck the wolf in the shoulder, making hissing sound as it made contact.

The wolf was thrown to the side and rolled a few feet away. On the side that was struck, a black mark of burned skin and hair let off the smell of burning flesh, and possibly bone showing through the wound.

"You're going to pay for that," the wolf said.

"Oh, great," Markus replied. "The deadly wolves are talking now too."

The wolf paused, looked from Markus, to Janie, to Markus to Janie. "Oh, no..." he laughed mockingly. "You didn't, you cheater."

"Kill him," one of the smaller wolves remarked as it walked forward.

"He is mine," the first wolf barked behind him, and the smaller wolf backed off.

The lead wolf lunged again.

Now flooded with stress hormones and some weird pulsing energy, Markus switched his grip and moved one leg back into a baseball bat stance, then struck down with the glowing stick-saber. He flinched at the sight of huge jaws coming his way - the sounds rushed him. Stick making contact, bone cracking, and flesh searing.

Then stillness-

When he peeked, the body of the wolf was torn in half on each side of him, blood pooling at his feet.

The other three glanced at their leader, then to Markus, then took off running into the woods shouting behind them, "We'll be back, wolf killer!"

Markus eyed the pooling blood and began to throw up all over it.

He ran to the stream, washing his mouth out, and the blood from his hands and arms. He scrubbed furiously at his arms, then sat by the stream shaking slightly.

"Well done," Janie the cat said, from a high tree branch. "I didn't think you were ready, I guess I was wrong."

"What the hell was that?" Markus said, half to Janie, half to himself.

"That was your orientation?" Janie offered, shrugging.

"Orientation?!"

"You're a bit tense," Janie observed.

"Tense. Tense, the talking cat says," Markus began pacing by the water.

"Tense," Janie said. "Yes. You are tense. This should help."

Just then, Markus' arm burned slightly, and words began to appear on his arm in a readable yet artistic script. "Wolf Killer" glowed in a blue font on his left forearm.

"You always wanted a tattoo," Janie offered.

Markus, still shaking and pacing, now focused on the blue, grey, and white colors radiating and pulsing from the new tattoo.

"I almost died just now," Markus complained.

"I'm sorry," Janie replied. "I always forget that people from your reality need to adjust to this world. You've been through a lot. I'll take you somewhere to adjust and process."

The glowing script on Markus' arm faded, and he began to feel light headed and weak, "I don't feel so good."

"Oh, Manna drag..." Janie said. "You need to rest. Yes. Food. Rest. Process. But not here. First we get you cleaned up. Go get into the stream and wash all that junk off." Janie touched the water with her paw, and gestured for him to enter.

He wasn't thrilled about getting into the water, but he almost threw up again looking at the wolf's blood on his pants and shirt, so he didn't argue. As he walked into the stream, which had been cold when he drank, it became just warm enough to be tolerable. Markus scrubbed at his clothes until the water around him was clear.

"We'll get you new clothes," Janie said as he walked out of the stream. She blew at him and a warm wind blew softly over him. A few moments later, his clothes were dry, though still stained red. Then she pulled another small cake from her dimensional space and it floated to him.

"Eat," She said. "This will restore you energy. We need to get you to a safer spot to rest."

***

As they entered a clearing, a tent and campfire up ahead were inside a circle of white powder. As they crossed the line, a previously invisible barrier flashed with tint of blue before disappearing again.

"You'll be safe here." Janie walked to warm herself by the fire.

As he sat down, Markus exhaustion washed over him. Making eye contact with Janie the Cat, he said, "Have you always been able to talk?"

"Yes," She replied.

"Why didn't you talk when we were in my apartment the last three years?"

"Cats don't talk in your reality," She said, then pursed her cat mouth thoughtfully. "Well... Not normally, not audibly." She shrugged.

"What is that supposed to mean?" Markus challenged.

"Rest," She replied. "You need rest. Plenty of time for questions. For now, you rest." She nodded to the tent. "You'll be safe here."

Seeing the three suns setting, and a purple moon with pink rings taking prominence in the sky, Markus nodded agreement.

As he laid down, pulling a large wool blanket over him, he felt the exhaustion wash over him. Janie curled up at his feet, guarding the doorway.

"This is a dream?" Markus asked Janie. "Right?"

"Shh," She said simply. "I'll get someone to help you transition tomorrow."

As he faded, he thought this was a weird trip. He expected he would wake up in his apartment or in a hospital back home, and have new stories to write about.

***

Authors note - Let me know if anything made you laugh, or if you felt disconnected at any point. I'd love to know.

***
