---
title: 'My opening thoughts... I have no idea how I will use Buy Me A Coffee'
date: '2025-01-25T21:54:00.0000000+00:00'
draft: false
---

<p data-pm-slice="0 0 []"><strong>My opening thoughts... I have no idea how I will use <a href="buymeacoffee.com/darrellwoli" rel="noopener noreferrer nofollow">Buy Me A Coffee</a></strong></p><p>In General, I know what marketing people do with tools like "<a href="buymeacoffee.com/darrellwoli" rel="noopener noreferrer nofollow">Buy Me A Coffee</a>" and Patreon and others. They create a false sense of scarcity and urgency by limiting certain content to certain people who can pay for the upgrades stuff. </p><p>The very thought of doing something like that makes me want to die inside. I would rather have a universe where all our needs our met, nobody has too much or too little, and we just do what we love and our motivation is to enjoy sharing what we love with our kindred spirits. </p><p>I also come from a unique eccentric mix of Judeo-Christian traditions, which have caused me to deconstruct the US-American Churchianity of my upbringing and seek out The Way of Rabbi Yeshua (who is way more interesting than my Church told me he was). As a result, my ethic is to share freely, widely, and openly. However, if I'm working so many hours to keep lights and food on that I can't write, I have nothing to share. </p><p><em>So here is my opening thought about starting this Buy Me Coffee channel.... </em></p><p><strong>Support My Work: </strong>If you want to support my work so I can keep doing more, buy my work on Amazon/Kindle/Audible (when it becomes available there, there is nothing there today, 01/25/2025), or <a href="buymeacoffee.com/darrellwoli" rel="noopener noreferrer nofollow">Buy Me A Coffee</a>.</p><p><strong>My goal</strong>: Subject to change, you will never have to pay me anything to have access to my content outside of Amazon's ecosystem. So if you want to support me outside that system, Buy Me A Coffee. </p><p></p><p><strong>Writing - Where you can find me</strong></p><p><strong>I write</strong> blogs, fiction, and academic articles. I will post those on the various channels for which they are appropriate. </p><ul><li><p>Blog - www.DarrellWolfe.com - My most random thoughts of the moment.</p></li><li><p>Blog - www.NoHiding.Faith - All my biblical studies writing goes here.</p></li><li><p>Fiction - </p><ul><li><p>Darrellwolfe.com - Sometimes post rough drafts and short stories and practice writing stuff on my personal blog, www.DarrellWolfe.com</p></li><li><p>Royal Road - <a href="https://www.royalroad.com/profile/429937" rel="noopener noreferrer nofollow">DarrellWolfe's Profile | Royal Road</a></p></li><li><p>Wattpad - <a href="https://www.wattpad.com/user/darrellwolfe" rel="noopener noreferrer nofollow">Darrell G. Wolfe (D.G. Wolfe) (@darrellwolfe) - Wattpad</a></p></li><li><p>Good Reads - I don't see how to use Good Reads to post anything, but if that's possible I have a profile there: <a href="https://www.goodreads.com/darrellgwolfe" rel="noopener noreferrer nofollow">https://www.goodreads.com/darrellgwolfe</a></p></li><li><p>Amazon/Audible - ($) - This is the only avenue other than Buy Me Coffee where I plan to add a price tag to my work. </p></li></ul></li></ul><p></p><p><strong>Community - Discord</strong></p><p><strong>Storytellers - <a href="https://discord.gg/6UK5Txeq" rel="noopener noreferrer nofollow">https://discord.gg/6UK5Txeq</a></strong></p><p>I just started a discord server where we can start to build whatever we want there. Maybe separate channels for fiction, biblical studies, exvangelicals, etc. I dont' know, let's figure it out together.</p><p></p><p>What else should I be considering? I anticipate nobody will actually read this post, or it will be years from now. But I wanted to put it out into the ether and let it marinate while I work on a complete re-write of my first novel for the fourth time, but this time with new tools and a reasonable expectation of putting something out worth reading. We shall see.</p><p></p><p><strong>Darrell Wolfe, Storyteller </strong></p><p></p><p></p>
<br />
<br />
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>

