---
title: 'Worldbuilding: Manna, Sarcasm, and Burritos (MSB) - Brineborn'
date: '2025-12-20T00:31:00.0000000+00:00'
draft: false
categories:
  - 'MSB'
---

Worldbuilding: Manna, Sarcasm, and Burritos (MSB)<br />
<br /><br /><div>The <b>Brineborn</b>, humanoid evolution of a cetacean-adjacent branch (other similar species include whales, dolphins, porpoises, and manatees). Specifically, they were an offshoot from an ancestor that later also branched into dolphins and manatees.</div><div><br /></div><div>They are residents of Oceana (Water World), one of the three orbs of the three suns.</div><div><br /></div><div>They are sometimes colloquially known as the Thrumfolk and the Aqualithae in some languages.</div><div><br /></div><div>Scholars list them as the Manadelphids species. “Manadelphids are a sapient cetacean-adjacent lineage that split from the shared ancestor before the dolphin/manatee divergence.” — Scholar Atticus Finch</div><div><br /></div><div>Brineborn are heavy-set folk with webbed feet and hands, thick fingers, and they move well on land, but slowly. Often they use transport equipment to keep up with other Offspring of Creator on missions. The most common equipment one might find a Brineborn using is the Aqua-Sled, a manna-enforced floating transport with a water pod inside and a cover with misters. Expensive Aqua-Sleds may even be fully submerged pods that can travel over land. Most are open-air but covered. Mist-Cloaks are also common: manna-enforced cloaks that draw moisture from the air (and/or from dimensional storage) and mist the Brineborn periodically to keep them from drying out.</div><div><br /></div><div>They have hues of grey skin, sometimes with blue hues and undertones. As a result of their need to keep water content high—and their use of water-enhanced equipment—the Brineborn’s skin is usually wet, moist, or tacky to the touch. Trying to grab hold of a Brineborn is difficult, as fingers slip off easily. A determined grappler may resort to hooks or barbs to gain purchase, though such tactics are widely regarded as cruel.</div><div><br /></div><div>They have large black eyes with no differentiation between pupil and iris like land mammals (non-aquatics). The skin and muscles around their eye close around it when blinking like a camera lens. Their first membrane is translucent and closes sideways; it allows them to see while protecting the eye from both water and sand. A larger cover allows them to fully close their eyes for meditation or sleep.</div><div>In the water, they are not the fastest of the aquatic folk, but they will beat any non-aquatic Offspring in a water race.</div><div><br /></div><div>Brineborn are immune to most diseases and have a high regeneration capability; therefore, affliction specialists will find this a hard foe to beat. They require water often to keep healthy. When on extended land trips, they may drink more in a day than most non-aquatics do in a month. As often as possible, they seek bodies of water to soak in—and even sleep in. Any large city will have inns that cater to aquatics, with pools instead of beds in the room. When this is not possible, seasoned Brineborn Manna Artists will keep water in dimensional storage to be used as needed.</div><div><br /></div><div>Brineborn have sonar echolocation that operates at shorter distances than their dolphin cousins, but it runs deeper and provides more information. They are capable of reading density, voids in spaces (like hidden caves), and determining the composition of hidden materials (rocks, walls, buildings, even devices). This makes it very hard to hide anything—or anyone—from a Brineborn. A potential issue with their deep sonar capabilities is that vibrations sent into land or buildings may be felt by those with sufficient perception, revealing the Brineborn’s location to those they have revealed.</div><div><br /></div><div>Mind-attacks are a component of resonating frequencies on the electromagnetic range. Both sonar and mind-attacks are more effective and can be brought to bear over greater distances underwater, but can operate within a short range on land.</div><div><br /></div><div>Their excess fat and thick skin serve as a barrier to heat and cold, and also a natural armor in war. While they may don armor, they are resilient even without it.</div><div><br /></div><div>Expect a Brineborn to have heavy attacks, both physical and resonant in nature. They are capable of sending waves of sound—or even mental assaults—with vicious efficiency.</div><div><br /></div><div>That being said, if a Brineborn has their water content reduced (physically or magically), they become weak and may even die. They are slow on land, and therefore speed attacks may whittle their defenses down over time, as they may be too slow to defend against a dedicated speedster. However, if a speedster falls prey to their sonic blasts, the Brineborn can quickly reclaim the offensive.</div><div><br /></div><div>The Brineborn’s water dependence means their regeneration wanes in low-water conditions. In that state, afflictions and toxins may have a stronger effect. While tissues are quick to regenerate, major organs—especially those related to nerves, hearing, or sonar—may take much longer to recover, if at all. This also means that attacks which drain water from the body (dehydration attacks) can be lethal to a Brineborn.</div><div><br /></div><div>While generally kind and amenable, Brineborn are not to be trifled with. If they feel the need to defend themselves or others, they will only leave the fight when one side or the other is incapable of proceeding. It is rare for a bar fight involving a Brineborn to end well for the offender.</div><div><br /></div>
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>

