---
title: 'Why...?'
date: '2025-03-31T01:02:00.0010000+00:00'
draft: false
categories:
  - 'Musing'
---

Simon Sinek wrote a book, and a speech, and an empire, around the question... It starts with Why!&nbsp;<div><br></div><div>I am listening to The Way of Kings, Brandon Sanderson, book 2, and Kaleden just defeat Seth son son Balano, Truthless of Shinovar. I found myself thinking how hard Kaledens life was in the story, and how he found a real smile. I then thought about Simon's book, and I wondered...&nbsp;<br><div><br></div><div>Today, I ask myself, why?&nbsp;</div><div><br></div><div>Why do I get up in the morning when I don't want to?&nbsp;</div><div><br></div><div>Why do I get up and do this for and with people I'm responsible for, when everything in me says to turn it app off and go to bed?</div><div><br></div><div>Why do I bother trying to make things better when it only makes my life harder?</div><div><br></div><div>Why do I keep hoping, when I've never seen a positive outcome for it?&nbsp;</div><div><br></div><div>The only place I ever find solace is in fictional worlds, in which magic and super powers exist.&nbsp;</div><div><br></div><div>But here I am... Getting gas, eating dinner, and trying to find motivation to do another task or two before I succumb to sleep in a few hours.&nbsp;</div><div><br></div><div>The problem is, I really don't know why.&nbsp;</div><div><br></div><div>I know I feel responsible.&nbsp;</div><div><br></div><div>I know I feel I "must" continue.</div><div><br></div><div>But I don't understand why.&nbsp;</div><div><br></div><div>I wish I had a "why" that left me feeling compelled, rather than one that left me feeling coerced and conscripted.&nbsp;</div><div><br></div><div>But I guess if it keeps me breathing another day, it's better than nothing. So I go on...&nbsp;</div><div><br></div><div>But I wish I had a why...&nbsp;</div><div><br></div><div>I wish I woke up in the morning glad to be alive and excited for the future.&nbsp;</div><div><br></div><div>I never have. Not once that I can recall in my whole life. I've been entertained, distracted, and amused... But never genuinely excited.&nbsp;</div><div><br></div><div>I watch it in others, and it feels like I wish I had that.&nbsp;</div><div><br></div><div>I see glimpses of it when I write, creative fiction, even if I don't do it very often.&nbsp;</div><div><br></div><div>Maybe someday.... Someday I'll have a why.&nbsp;</div><div><br></div><div>Selah</div><div><br></div><div>Darrell Wolfe&nbsp;</div></div>
