---
title: 'Worldbuilding: Manna, Sarcasm, and Burritos (MSB) - Leonids'
date: '2025-12-20T00:28:00.0000000+00:00'
draft: false
categories:
  - 'MSB'
---

Worldbuilding: Manna, Sarcasm, and Burritos (MSB)<div><br />
<div><b>Leonids </b>are lion Humanoid evolutions (of the catfolk). They are an offspring built by the heat of the desert and the community of their pride (family). Leonids are highly social Offspring with a strong early dependence on family, and a near-fanatic loyalty to their chosen family in adulthood.</div><div><br /></div><div>Leonids come in golden, white, and sometimes black stripes on either. Their heads possess long manes in place of what humans would call hair. These manes can be cut short, braided, dreaded, decorated with jewelry, or any other number of unique personalizations. Younger Leonids of this most recent generation, learning from other Offspring around the realm, are fond of piercings and head worn accoutrement.&nbsp;</div><div><br /></div><div>Leonids are on average very tall and large, up to 7 Ft (over 2 meters). They boast strong muscular bodies and iron grips with razor sharp retractable claws. When a Leonid runs or jumps, there are few land Offspring that can beat them over short distances.&nbsp;&nbsp;</div><div><br /></div><div>They boast fur all over their body, and their eyes can be unnerving when their gaze is directed at you. The voice of a Leonid can vary, but will often have the weight of Authority when speaking, especially after they are advanced Manna Artists. The Manna-enhanced roar of a Leonid can be incapacitating to an enemy (whether on the battle field or in a bar fight, or when caught in friendly fire all the same).&nbsp;</div><div><br /></div><div>The scent-reading capabilities of Leonids are quite high, even able to determine emotions, stress, fear, love, attraction simply through the pheromone released by the other party. They are natural lie detectors. They pick up on vibrations in the ground through their sensitive paw-pads, and may detect incoming movement from up to a mile away.&nbsp;</div><div><br /></div><div>While their eyes are strong in low-light, due to their hunting background evolution, they can be blinded by sudden expressions of glaring bright lights.&nbsp;</div><div><br /></div><div>While strong and tough skinned, a Leonid is still a mammal. They are susceptible to any number of physical attacks and may require a dedicated healer nearby in war. They are weak to sudden bright lights, and easier to take out when isolated away from their team. They will still give a fight to behold alone, but if you are going to take down a Leonid, they had better be alone.&nbsp;</div><div><br /></div><div><br /></div>
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
</div>
