---
title: 'Writing Practice 01/02/2025 | Angst the happy dragon'
date: '2025-01-02T18:00:00.0030000+00:00'
draft: false
categories:
  - 'Writing Practice'
---

<p>*From a conversation about a book Preston was reading… this phrase came up. Good prompt.</p>
<p>How does one get ready for their appointment with God?</p>
<hr />
<hr />
<hr />
<hr />
<hr />
<p>“How does one get ready for their appointment with a god?” L’Ang asked. He turned to his dragon, waiting for a response.</p>
<p>Angst, the tiny pet dragon, sat on his perch near the window, soaking the rare winter sunshine through the window. He nodded thoughtfully for a moment. “I see your predicament. It’s not an entirely uncommon experience, but it’s not exactly a daily experience either. What does one say, ‘Howdy there diety, how’s the weather?’ That would seem an odd start, indeed.” Angst the dragon smiled to himself, amused at the idea.</p>
<p>L’Ang crossed the room to stand next to Angst, intending to look out the window, but he caught his own reflection instead. He began fussing over the grey hairs beginning to shoot up in his otherwise jet black hair. “I’m not sure what one is to say to a god… Or, for that matter, why he wants to see me… me of all people.”</p>
<p>“You fuss too much,” Angst said, then shook his wings and stretch them before hopping onto L’Angs shoulder. “Let’s go outside and take a walk, that seems to help you regulate.”</p>
<p>“You’re a good friend, Angst.” L’Ang replied, and then walked outside to the path leading into the forest.</p>
<!-- notionvc: 1e11b263-fc6f-43c5-9cfa-ec3a80d2e4c2 -->
