---
title: 'Worldbuilding: Manna, Sarcasm, and Burritos (MSB) - Dragonborn'
date: '2025-12-20T00:32:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '8535547788399058255'
blogger_filename: '/2025/12/worldbuilding-manna-sarcasm-and_61.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'MSB'
---

Worldbuilding: Manna, Sarcasm, and Burritos (MSB)<br />
<br /><br /><div>The <b>Dragonborn </b>are a Humanoid evolution an ancient serpent species. In mythology they consider themselves to be born of their own mythological ancestor The Great Dragon.&nbsp;</div><div><br /></div><div>Natives of Zora (Lava/Fire/Rock World) one of the three orbs around the three suns.</div><div><br /></div><div>Scholars are unable to confirm or verify is the ancestral species existed. It is clear that they were born of a serpent-like race that grew out of the primordial past on Zora. At one time in the eons of yesteryear, the orb that is now called Zora was a green orb with much water and plant life, and it evolved in ways similar to Markus’s home world Earth 1. What scholars know today is that when the great convergence occurred (the three suns and three orbs became intertwined with each other), it pushes Zora closer to its home star, and the orb grew hot and violent. It eventually found its rhythm and balance. While some water and greenery still exists, it is mostly in underground cave systems, and the light used for photosynthesis is produced by manna veins in the rock. As a result, this serpent species evolved to not only tolerate but embrace the heat.&nbsp;</div><div><br /></div><div>In light of this assumed lineage, Scholars on Ha’Aretz named their taxonomy for the residents of Zora after their own mythological serpent, Leviathanidae Hominidius.&nbsp;</div><div><br /></div><div>Dragonborn swim in the lava as if in water. Their homeland has greenery and water regions, full of animal life. But the Dragonborn are the only sentient of Creator’s Offspring on Zora. Large swaths of the Orb are covered in volcanoes and lava lakes; with ash clouds periodically blanketing the skies. The entire orb is covered in an immense heat, which creates a natural greenhouse where the green lands thrive. The animal life and bird life are hardy creatures. Dragonborn were the apex predator long before they developed sentients.&nbsp;</div><div><br /></div><div>Zora now has a rich economy of exports in obsidian, sulfur salts, rare crystals, and ash used for saponification.&nbsp;</div><div><br /></div><div>Dragonborn are no larger than the average human, with similar appendages. Obsidian scales cover their bodies in heat-shedding capabilities. Their scales are black with iridescent reflections of blues and reds which give off purple hues. These scales are overlapping and harder than steel, leaving them basically immune to any physical damage unless it has sufficient force to break through. Their fingers boast long sharp claws. On their backs, two fin-like wings of leather and a strong tail mark them as uniquely identifiable.</div><div><br /></div><div>The Dragonborn have no external ears to speak of, while their hearing is decent to a degree, it is less than a human’s hearing. Instead they sense vibrations and they can pick up chemicals from the air with their tongues. They are also near legendary in their capability to see heat sources even through thick walls or determining their location deep underground. Their entire body, especially their manna channels, are tuned to pull heat and therefore sense it. Their eye-sight is sufficient for most activities, but these other sense are their primary cognitive framework. They may taste you on the air before you are near enough to see clearly; especially if you are pungent from perfumes, food, or other activities. They develop a taste profile of their frequent contacts.&nbsp;</div><div><br /></div><div>Since the Dragonborn are used to hot humid greenhouse climates, they get sluggish in the cold. Their joints stiffen and scales become brittle. While water poses no problem to the Dragonborn in and of itself, the closer the water gets to freezing the more painful or even damaging it will be to the Dragonborn. Their bodies were evolved to live in and off-put heat, they are cold-blooded serpent-kind and require a regular external heat to retain their normative body temperature. In the atmosphere of Ha’Aretz, Dragonborn are not immediately in danger but may and often do require external heat sources to maintain their comfort if not their life. As such, they carry heat sources with them. The most common heat source is a manna infused heat cords of iron woven into a belt which is buckled across the chest.&nbsp;</div><div><br /></div><div>When forced into battle scenarios, Dragonborn are powerful in both close-range melee attacks and longer distance area denial. They are able to interact with any heat source, including drawing power from the sun directly. So they are less potent at night unless ample fires are present, which they will usually start themselves at the beginning of a night fight, growing more dangerous as the fire grows. They can glass the ground turning it into either slippery obsidian-like surfaces with little traction or even into molten material that both traps and burns their enemies. They can pull heat, fire, and flame from the sun, nearby fires, or other heat sources causing a fire-storm in the air around them, aimed at their targets. These attacks can be broad or pin-point accurate, depending on their needs. When up close, they may grab you and hold you to their chest, burning you skin to skin. They may also wield weapons (swords, axes, staves, maces, nunchucks, throwing knives, etc.) that are doused in flame or supercharged with explosive heat. Since they can pull heat from external sources, this means they may be able to draw heat directly from their enemy’s bodies as well, though this kind of attack is difficult as it becomes a matter of will against will. It is also dangerous for the Dragonborn as the same attack in reverse, heat drawn from the body, is a particular weakness for them. It is not an attack they like to use except for in extreme circumstances, for fear that their enemy may realize it can be reversed to extreme effect.&nbsp;</div><div><br /></div><div>While modern Dragonborn are sophisticated scientists, alchemists, forgers, and miners, in addition to being warriors of renown, they also tend to hold their religious ideals with an amount of reverence that surprises outsiders meeting them for the first time. They are usually not fundamentalists, but rather reverently spiritual. Most Dragonborn believe Leviathan is a myth of the ancient past, and instead hold to one of two ideals. Either Ra-Ah the sun god as their patron deity (less common), or a direct reverence for the nature of hot and cold itself (more common). Thus you are more likely than not to find some version of the Yin-Yang in blue and red upon their person, either in an emblem or a tattoo mark or metal sash or belt of some kind.&nbsp;</div><div><br /></div><div>On Zora, their home orb, Dragonborn have nests where they congregate together at times while at other times they sojourn solo. While on Ha’Aretz, they tend to stay near populated areas, due to the fact that groups mean heat sources. Both the body heat of crowds and more importantly the many ways in which others of Creators Offspring need heat for cooking and forging and even heating living spaces when colder months arrive. If a Dragonborn is traveling alone, they will make sure they are equipped with multiple rechargeable heat sources to bring with them. They also plan routes that would allow them to build fires, so they might avoid a tree-less prairie or the desert at night.&nbsp;</div><div><br /></div><div>Due to many unfair stereotypes, the Dragonborn go out of their way to be cordial to strangers which allows them to avoid unnecessary attention or complications. With their friends, they may let more of their wit show allowing their smile crack through the facade. With enemies, their cold emotionless stare creates its own kind of fear, as fire billows around and from them hungry to devour and consume.</div><div><br /></div>
<br />
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
