---
title: 'Worldbuilding: Manna, Sarcasm, and Burritos (MSB) - Wolf-Folk'
date: '2025-12-20T01:52:14.8880000+00:00'
draft: false
categories:
  - 'MSB'
---

<div>Worldbuilding: Manna, Sarcasm, and Burritos (MSB)</div><div><br /></div><div><b>Wolf-Folk </b>(Werewolves, Wolves) are a humanoid evolutionary branch from their Great Wolf ancestor. This divergence predates the divergence into the common dogfolk by millions of years, but sentience hit the many of Creator’s Offspring around the same demarcation 100,000 years ago, scholar say.&nbsp;</div><div><br /></div><div>Important History</div><div><br /></div><div>Wolf-Folk have a unique development within Ha’Aretz as they are considered to have extra-normal developmental anomalies in their history of origin. The trouble is, for scholars, separating fact from mythology.&nbsp;</div><div><br /></div><div>According to widespread mythology, the Wolf-Folk began as a simple evolutionary branch of the Great Wolf that developed sentience around the time of the Creator’s Offspring gifting explosion. At some point, Creator decided to gift them with the ability to better bond with their closest geographical neighbor, the humans. As such, they could morph their form into the approximate shape of humans, but always with traits of their wolf heritage visible.&nbsp;</div><div><br /></div><div>Still other more localized colloquial mythologies speak of a secret pact between the rebel elohim (The Anunnaki) and a smaller subset of the Wolf-Folk, giving them an edge over their competition in exchange for an eternity of service for them and their descendants. Sometimes this mythology is tied to the Anunnaki named NasuApu.&nbsp;</div><div><br /></div><div>However, some scholars believe that this ability to trans-mutate came from exposure to a particular strain of manna vein known to have been in abundance in their territory of origin at the time of the Creator’s Offspring explosion. This is an educated guess at this time, the evidence may lean to supporting this hypothesis but it is circumstantial at this time.</div><div><br /></div><div>Note: In truth, unbeknown to most in Ha’Aretz, but known to the reader of this secret chronicle, the accounts above are all true in part. Creator did give this gift to the Wolf-Folk as a gift to make stronger ties with the humans and he used the manna vein in their region as a mechanism for this gift evolution. However, NasuApu did make pacts with some Wolf-Folk giving them even more and stranger abilities. He has also made pacts with human-born agents to turn them into his Wolf-Folk agents. It was such a pact like this, with a disillusioned human male named Dallu (whose name meant weakness) where The White Wolf Clan originated, giving Dallu the new title Bel-Dallu (Lord of Weakness). This made him a werewolf, and gave him supernatural control of the Manna Arts empowered not only from Bel-Dallu’s new evolved manna channels but drawing from NasuApu itself.&nbsp;</div><div><br /></div><div>Wolf-Folk did originally have peaceful and harmonious pacts with the human-born. However, various infightings, wars, and even natural disasters drove them apart. For a time, they became myths and legends to the human world until they reappeared out of the mountains after the great frost melted. In the thousands of years between, mythologies (such as those above) developed, and human-born distrusted the Wolf-Folk. For their part, the Wolf-Folk lost all sense of story or mythology about a human world and were surprised to find groups of people that looked similar to their upright form but without the ability to take their wolf form. They thought them broken or dysfunctional. Thus, the groups remained apart for centuries after coming back into contact.&nbsp;</div><div><br /></div><div>Today, regions of the world experience different outcomes. In some regions, Wolf-Folk have formed lasting bonds with both the human world and others of Creator’s Offspring. They are welcome members of societies, even holding prominent authority and government roles. In other regions, there is peace but still distrust, and so while they pass each other in the markets, even doing business between each other, the humans and Wolf-Folk do not intermingle personally. Still in other regions, they are outright hostile to each other, keeping to their own territories in tenuous peace treaties, with occasional outbreaks of war.&nbsp;</div><div><br /></div><div>In Kaldea, the Wolf-Folk were largely run off into other lands until a decade ago when a new White Wolf Clan moved into the mountains east of the capital of Kaldea. While efforts were made to either create peace treaties or if not, run them off, all efforts failed. The King, already busy with other matters, is content to leave the region to them until such time as they create a nuisance worth the investment of his entire army. Meanwhile, Bel-Dallu wins converts by the day and brings them into his fold, turning human-born into Wolf-Folk through dark arts and darker pacts of gods.&nbsp;</div><div><br /></div><div>***</div><div><br /></div><div>About the Wolf-Folk, General Overview:&nbsp;</div><div><br /></div><div>Wolf-Folk are hunters by nature and operate from Den sites. These Den sites are usually territorial and continue for generations within any given clan until circumstance drive them onto other geographies. The Wolf-Folk are shape shifters; any given clan may have a culture of staying in wolf form or human form more often, as their needs and risks and cultures dictate.&nbsp;</div><div><br /></div><div>When in wolf form, they look like any natural wolf, but 2-3 times larger, sometimes as large as cattle in extreme cases. Due to this form similarity, all wolves, even the non-sentient wolves, are treated as potentially dangerous or signs of Wolf-Folk activity, even if no Wolf-Folk are present. In this form and size, they are powerful runners, have jaws of brutal bite force, and can often overpower an untrained manna artist or non-manna trained human one-to-one.</div><div><br /></div><div>When in human form, they still retain their pointed wolf ears, and wild hair and thick side burns, and pointed teeth. Their transformation can either take minutes or fractions of a second, depending on the age and experience of the individual. In this human form, they are stronger than the average human, faster runners, and retain their enhanced sense of smell, sight, and hearing. They do not have the power of their wolf form, but their human form is still formidable.&nbsp;</div><div><br /></div><div>In either form, they can see farther than most humans. Their sense of smell is still their primary cognitive framework for the world, as with their cousins the dog-folk. They can follow scent trails that are days old when hunting. Their hearing can pick up voices from up to 5 miles away, if the wind and terrain conditions are right.&nbsp;</div><div><br /></div><div>As fighters, in either form, they tend to rely on their sheer strength and sharp teeth and claws to slash at opponents. They are also capable of wielding the Manna Arts, but this varies by individual. Wolf-Folk are not known to be patient by nature, and patience is required to wield the Manna Arts.&nbsp;</div><div><br /></div><div>Youth culture prizes aggression; elder culture prizes restraint. Among them, patience is not natural—it is earned, and therefore revered. Younger individuals will usually rely on the size and strength of their wolf form to surprise and overwhelm an enemy, and operate in packs to isolate them. However, as individuals age they grow in their patience and many become wielders of the great arts. When they do, they can become powerful mages, as their will can be hard to near unbreakable. These individuals may single-handedly overwhelm whole groups of enemy combatants with their deft handling of brutal manna attacks and defenses. They also use the defenses to shield their more impatient younger brethren.&nbsp;</div><div><br /></div><div>In our local case, The White Wolf Clan is a particular clan of werewolf zealots whose stated aim is to break Kaldea and tear it down. They spread their message of how Kaldea has failed the lower classes, and some disgruntled residents have developed sympathies for the clan if not outright joined them.&nbsp;</div><div><br /></div>
