---
title: 'Worldbuilding: Manna, Sarcasm, and Burritos (MSB) - Mantisai'
date: '2025-12-20T00:34:00.0000000+00:00'
draft: false
categories:
  - 'MSB'
---

Worldbuilding: Manna, Sarcasm, and Burritos (MSB)<br /><br /><div><br /></div><div><b>Mantisai </b>are an evolution of an earlier mantid branch of insect. As they developed sentience and grew in prowess, they also grew in height and weight. That being said, they did not become massive by the standards of other sentients. Mantisai grow to an average of 4.5 feet tall, and may weigh up to 100 pounds. Rarely is one found larger, but individuals do vary. They are usually found in shades of green, grey, or tan. Though one unique lineage has been rumored to have a teal tint which may or may not be natural. They have existed in most climates and zones throughout Ha’Aretz as a sentient but largely non-humanoid group of Creator’s Offspring.&nbsp;</div><div><br /></div><div><br /></div><div>They have six limbs: four stride-legs (used for walking/climbing) and two grasp-limbs (used as arms). Their&nbsp; pointed spiked feet leave very little mark on even the softest terrain. It might be easy to mistake their marks for a group of walking sticks, staves, and canes if there are also footsteps of other groups present. Their front two limbs are long and cut at sharp angles. Their forearms are wide and bladed with sharp spikes which were originally helpful for climbing varied surfaces and holding prey. As they grew and began interacting with other sentients, these bladed arms became their easiest and most readily available weapon for self-defense or attack. As they evolved into sentience, the end of their forearms developed finger-like tendrils. They are able to use them with great poise and dexterity, and due to their thinness, reach into spaces, even inside equipment, that no non-Mantisai could hope to accomplish. Their grip strength is weaker with their quasi-hands, but if caught between their arm sections, it is hard to escape.&nbsp;</div><div><br /></div><div>Mantisai have arrow shaped heads, with large green eyes and tiny pupils. They have two antennae which seem to move about of their own accord constantly. They have two grips on their mouths and act as a type of mouth claw. Their heads swivel to a far greater degree than any other creature save for the Great Owls. With larger eyes, they have advanced motion detection and near 365 degree peripheral awareness. They see very well within 100 feet; however, tend to see less well into the distance. They are able to detect scents on the air, but with less acuity than the dog-folk or cat-folk.&nbsp;</div><div><br /></div><div>One of their most useful traits in terms of inter-sapient societal interactions is their stealth and dexterity. They can walk up nearly any surface, even straight verticals or inverted ceilings, with nearly the same ease as walking the ground. The spine-like grips on their feel retract and extend punching into surfaces just enough to get an iron grip on them. While this works well with porous materials (rock, stone) it does not work on glass or polished metals Even when using this feature, they are nearly silent in their movements. They can grow so perfectly still for extended periods, that someone might mistake them for a tree or a statue.&nbsp;</div><div><br /></div><div>Mantisai are ultimately non-humanoid species and do not always think like the two-legs. They understand community and friendship, but they do not hold the same moral misgivings. They are often hired as thieves, spies, and assassins and they usually lose no sleep over their duties as long as they deem the job or target to have earned their just dues. But for most Mantisai, this is less an emotional justice and more of a calculated justice. Things are right or wrong because they simply are, and this can lead them to calculated decisions, like considering it no choice at all to sacrifice the few for the many. Nevertheless, they are not fundamentalists in their sense of justice. They simply tend toward a logical calculation over an emotional appeal. If you want them to change their mind, you must appeal to the logic.&nbsp;</div><div><br /></div><div>For advanced Manna Artist Mantisai; there is a talent available for complete camouflage. Their outer skin, and sometimes even eye color, can change to match their environment. This functions as a skill of both body manipulation of their chromatic colors and manna manipulation to augment this physical capacity. It requires extensive training and deep meditation to develop the skill. Only the most proficient can perform the task instinctively. For most who do develop the skill, at least a few moments of concentration are required to completely blend with their surroundings. This only impacts visible light spectra. Which means infrared (heat-vision) will still uncover them unless they do something externally to mask their heat signature. Ultraviolet may also expose them as the very nature of their pigments that allow for the camouflage react strongly to UV Lamps, practically causing them to glow white in the dark. This is much harder to disguise.&nbsp;</div><div><br /></div><div>It is quite likely that if you get to know a Mantisai, they will tell you that “Rumors of eating our spouse are racist and greatly exaggerated from our ancestral past. Only when a pair wanted to separate but there were disputes in the process would that ever happen today, and even then it is exceedingly rare. It’s almost always symbolic these days… except for Aunt Zizzarat. Don’t get me started on Aunt Zizzarat.” — Scholar Clinock Satrine&nbsp;</div><div><br /></div><div>When not busy with life’s many activities, you may find a Mantisai meditating in complete stillness or people watching and observing the strange habits of the two-legs. They do not make great party hosts, but find intellectual pursuits and logical puzzles highly entertaining. If you are wanting small talk and entertainment, you are unlikely to find it with the Mantisai unless by accident of their misunderstanding something. But if you are wanting to puzzle out the mysteries of the universe, you are hard pressed to find a better conversation partner. For this reason, you will also find the Mantisai among the scholars of the world. Wherever great libraries are found, Mantisai will be in attendance. By extension, they make wonderful professors, tutors, file system keepers, programmers, and other high-logic professions. They also make wonderful alchemists and inventors.&nbsp;</div><div><br /></div><div>While these all portray Mantisai as quite formidable, they are fairly weak to physical attacks. Their bodies are light and their shells while hard are thin. A direct attack with sufficient strength will cause massive damage and potentially death. To counter this, they develop a martial art that involves moving with the opponent using their momentum against them. That being said, sheer blunt force can be a deadly and quick end to a Mantisai. Also, due to their large eyes and visual awareness sudden blasts of bright light or strobe lights can disorient the Mantisai. It takes special goggles to attempt to overcome this limitation, but those in turn limit their visual awareness which is one of their primary talents. So the solution becomes another harm.&nbsp;</div><div><br /></div><div>When in battle, they focus on grappling if unarmed. But due to their physical weakness to blunt force, they prefer to be range fighters, using their enhanced field of awareness to call out battlefield tactics to their teams, and fire longer range weapons. They will fire off magical attacks of energy bursts, and magically enhanced projectiles of any kind (arrows, throwing knives, and even manna charges rocks if needed). If forced into close-range combat, they are in danger, so they will usually carry manna-charged whips and chain weapons to fling at enemies who approach in closer range, and at least one spear and one long sword as the final defense. These are all back-up choices, as they will avoid close-range combat if at all possible.&nbsp;</div><div><br /></div><div>One might wonder how this weakness to close-range combat may interact with their work when hired as a close range assassin. The short answer is that they take all the above precautions, but generally try to avoid close-range combat. They sneak into places and hide in plain sight, typically using poisoned in food, laced darts, or attack their target while sleeping. More often, they are hired as thieves. They can enter someplace with near perfect silence, hide when needed, retrieve items with expert dexterity, and be gone without much of a trace they were ever there. But if something goes wrong, they have their back-up options available either on their person or in dimensional storage.&nbsp;</div><div><br /></div>
<br />
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>

