---
title: 'Worldbuilding: Manna, Sarcasm, and Burritos (MSB) - Mastiffarians'
date: '2025-12-20T00:29:00.0000000+00:00'
draft: false
categories:
  - 'MSB'
---

<div>Worldbuilding: Manna, Sarcasm, and Burritos (MSB)</div><div><br /></div><div><br /></div><div><b>Mastiffarians </b>(dogfolk), Humanoid divergent evolution of the dog-breed similar to that which became Mastiffs on Earth 1 (Markus’ home world in this LitRPG Portal Fantasy).&nbsp;</div><div><br /></div><div>Mastiffarians are most easily identified by their massive heads, with long loose jowls and thick triangular black noses.&nbsp;</div><div><br /></div><div>Mastiffarians are barrel chested, thick-necked, muscular humanoids. They are the natural bouncers of choice at the local clubs due to their desire to protect while remaining largely non-violent, inspired by a livity-like tradition. They may also be seen in other roles that protect or provide; priests, healers, chefs, body guards, law enforcement, stewards and butlers. One prominent position a well-known and seasoned Mastiffarian may find themselves in is that of a Mediator or dispute settler. They do not enjoy conflict, so are not attracted to professions like ‘lawyer’. But when two parties have even a fainting hope of settling disputes before the courts are involved, they may hire a seasoned Mastiffarian to host a round-table in their camp.&nbsp;</div><div><br /></div><div>They are wide and muscular, but only slightly taller than the average human, ranging 6’ to 6.5’ on average. While they are tall, it is their sheer musculature that differentiates them. They are often able to lift weights that few other Offspring of Creator their size could manage. Even the mighty Leonid cannot out-lift a Mastiffarian.&nbsp;</div><div><br /></div><div>They have short bristled fur, with a chocolate brown fur and erratic black strip patterns throughout. The strip patterns are inheritable and genetic, so often family lines can be seen in the patterns, though they still vary from individual to individual.&nbsp;</div><div><br /></div><div>The Mastiffarian Offspring folk are loyal and playful, despite their gruff first impression. Once they know you are a friend, they will be kind and gentle, despite their massive size.&nbsp;</div><div><br /></div><div>Mastiffarians have low visual acuity. They see just fine in low to average light conditions, especially within the close ranges. However, they are functionally near-sighted, so they may not be able to see details like faces from more than 20 feet away. This makes them perfect in low light or dusk conditions, and for operating as bouncers or patrol officers.&nbsp;</div><div><br /></div><div>Where they lack in sight, they make up for in Hearing and Scent. They have a scent-first cognition, and will smell you long before they can see you, given the conditions are right to carry your scent to them. They associate scent with emotions, so if they scent a friend, they will let their guard down. If they scent a foe, they will be ready for the fight long before they see it. Due to this scent-first cognition, they make excellent trackers, perceiving signs left behind in the air and on surfaces that a human would never pick up. Their hearing will also notice thumps, footsteps, and may differentiate from another room the exact size and weight of an object being dropped or moved.&nbsp;</div><div><br /></div><div>Being both massive and strong, the Mastiffarian is hard to rile up. They remain calm in the oddest of frays. In a bar fight, a Mastiffarian may pick up two drunken fighters, one in each hand, and then carry them to the front door, then set them outside like a crate of spoiled fruit, all while yawning in boredom or distracted by what they want for dinner.&nbsp;</div><div><br /></div><div>Being deeply loyal to chosen-family, the Mastiffarian has a high anxiety when separated from that chosen family. If they are apart too long, you may see them needless creating needless messes or even tearing apart things just to get the anxiety out. It’s very difficult to really antagonize a Mastiffarian. But if you want to get their ire, pick on their friends and chosen-family. A Mastiffarian that has chosen loyalties will conquer nations to see their chosen-family saved; and if not, then avenged.&nbsp;</div><div><br /></div><div>Because they are built like a brick house, they require near constant feeding. Their muscle mass alone means a high calorie requirement. They are also prone to long bouts of sleep and naps. When on duty, they may look bored but they are hyper-aware of their environment. But if they are off-duty, you will usually find them sleeping or eating; often with some form of entertainment or distraction running 24-7.&nbsp;</div><div><br /></div><div>Mastiffarians are massive and legitimately dangerous when needed. As a culture, they tend toward non-violence. For the Mastiffarian, violence is a last resort, and strictly defensive. They will use violence when needed, but they prefer the minimum viable product approach. This is why a Mastiffarian may simply pick up and remove a drunken fighter, rather than physically harm them.&nbsp;</div><div><br /></div><div>They believe in Creator and that all Offspring are worthy of dignity, freedom, and love.&nbsp;</div><div><br /></div><div>They resist systems of oppression and call those systems Babblers, because they drown truth in noise—status, power, conquest, and the sacred lie that people exist to be used. That is an ethos that Creator did not give Ha’Aretz (the land).&nbsp;</div><div><br /></div><div>Mastiffarians believe in sharing their personal resources that Creator gave them with those in their field of influence, and that hoarding is a sin against Creator (therefore extreme wealth that isn’t used for the benefit of all is evil). “It is a great sin when neighbors go cold or hungry while we are fed in our warm homes.” - Mastiffarian Priest, Basil the Benevolent</div><div><br /></div><div>The Mastiffarians are well known for their drum circles around the fire pits and are often found playing instruments. Likewise, they may be seen embracing the reality of grief, lamenting turmoil, and drawing hard boundaries around poor behavior.&nbsp;</div><div><br /></div><div>Even when they must enter battle, they might be found telling the enemies that “This is not the way Creator would have you be!” They are always balancing the edge of goodness of kindness and the goodness of protection.&nbsp;</div><div><br /></div><div>They might be found binding as prisoners rather than killing enemies, when possible. Though, if it is clear that an enemy released will do more harm to Creator’s Offspring than an enemy killed, they may make that call reluctantly.&nbsp;</div><div><br /></div><div>The constant cognitive dissonance between the world as they would have it and the world as it is, makes the choices of the Mastiffarians sometimes appear erratic to the outside observer, but knowing their culture and basic ethos will make sense of most choices.&nbsp;</div><div><br /></div><div>As with all cultures, individuals may vary on how well they hold to the cultural expectations. An assassin Mastiffarian is a seriously hard thing to conceive, but it is not impossible an individual may have chosen to abandon their upbringing and gone this way.&nbsp;</div><div><br /></div><div>While most Mastiffarians live in communal pack groups of chosen-family. When among their own nation, the pack groups will be all Mastiffarians. When young, this will be their blood-line pack, parents, siblings. Eventually, they form chosen-family groups as adults. When out among the wider mix of Creator’s Offspring, their pack groups will be chosen-family from among the variety of Offspring.&nbsp;</div><div><br /></div><div>They keep individual cabins/homes, but always set up a communal campsite to host their chosen family for gatherings, discussions, meals, and more. They are dispute settlers, and often great mediators. These campsites may be as simple as the front or back yard of a town home, or as grand as a mansion ballroom. Likewise, they may be as rural yet grand as an entire campground on several acres.&nbsp;</div><div><br /></div><div>Mastiffarians are not against the acquisition of wealth, only the hoarding of wealth. If wealth is attained in ways that honor all involved, including the poor, and that wealth is used to increase their ability to give to those around them, then wealth can be a moral good.&nbsp;</div><div><br /></div>
<br /><br />
<br />
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>

