---
title: 'MSB: Cosmo Valentine is a Mastiffarian'
date: '2026-02-08T07:45:00.0000000+00:00'
draft: false
categories:
  - 'MSB'
  - 'Character Sketch'
---

<div>Cosmo Valentine is a Mastiffarian from the Maplewood forest pack.&nbsp;</div><div><br /></div><div>Mastiffarians are humanoid dogkind, evolved from ancient dogs with features similar to mastiffs, boxers, and other hearty breeds of dog from Earth 1.&nbsp;</div><div><br /></div><div>Cosmo stands several heads taller than humans, with muscular body, and hanging jowls. His brown fur is marked by stripes of black haphazardly painted on as if he ran through a sprinkler of black oil. His brown eyes put people at ease, with a friendly face and demeanor.&nbsp;</div><div><br /></div><div>Cosmo has a large body that while muscular is also adorned with hanging skin and a tail that is both brutally strong and yet has a mind of its own. He is often embarrassed by the way his tail causes unintentional damage to people and things alike; or by the ways his mere movement through spaces can knock over or into others in his excitement.&nbsp;</div><div><br /></div><div>As a Mastiffarian, he is king, loyal, trustworthy, and calm under the most absurd circumstances, unless food is involved. While not strictly a pacifist, because he loves a good evenly matched fight far too much, Cosmo prefers to find non-violent solutions to his and other’s problems. When working as a bouncer at a club a few years ago, he would pick up misbehaving people by the color or arms or whatever seemed gentlest, then take them outside and set them gently on the ground. He would warn them to stay outside until they learned to behave like civilized people. Sometimes, he would even sit with them and talk it out if they seemed amenable.&nbsp;</div><div><br /></div><div>On the occasion where the powerful abused the powerless; however, Cosmo was often less gentle. In fact, should the situation be brutal enough to offend Cosmo’s loyalty to the powerless, his eyes would turn blood red, and he would become quite violent with the offender. Yet his friendly and casual demeanor never quite fades. As such, he is just as likely to be making jokes or puns while out with friends, or while slaying the evil power abusers. Once, Cosmo found a particularly vile human preying on pups and children. He held the man up to his eyes, smiled, and said, “Alligator’s gotta eat!” just before tossing him into the water to become prey to an apex species.&nbsp;</div><div><br /></div><div>Cosmo is for food, games, play, and the enjoyment of community regardless of species or origin.</div><div><br /></div><div>Cosmo is against any person or system that puts powerful people in a place to abuse the powerless.&nbsp;</div><div><br /></div><div>On his black sleeveless robe, embroidered in large colorful decorative letters, is his favorite quote: “It is a great sin when neighbors go cold or hungry while we are fed in our warm homes.” - Mastiffarian Priest, Basil the Benevolent</div><div><br /></div><div>Cosmo’s favorite hobby is cooking, and you can find a cookout in Cosmo yard at most times of most days, wherever his yard is for the day. He travels from place to place frequently, but he always establishes a campsite or communal space for others to join him for food and fun times.&nbsp;</div><div><br /></div><div>Depending on how you meet Cosmo, you may be tempted to think he’s a monk for his clothing, a cook or bartender for his hobby, or a guardian for his work. He is all of these and none of these. Cosmo sees himself as a protector of the innocent. He protects their peace with his presence and hospitality, and their lives, goods, or even bodies with his strength. While non-violence is his first go-to, he will escalate as much as needed to stand between the powerless and powerful.&nbsp;</div><div><br /></div><div>In fighting scenarios, Cosmo is usually found wielding only his hands and fists. When his power is fully unleashed in a war scenario, his fists begin to glow bright green with healing magic for his friends, and healing drain for his enemies. As a healer and non-violence-first personality, he will often stand behind a team and support them through healing, shields, and defensive techniques. As a result, many enemies think he is the weak-link to take down in order to defeat the team. In this, they are sadly mistaken. For his offensive capabilities are just as powerful as the strongest of the team, he just prefers to reserve them for when it is absolutely necessary.&nbsp;</div><div><br /></div><div>In cases where offense becomes needed, Cosmo can use his knowledge of anatomy (due to his healing affinity) to unmake people at the cellular level. He may thwart their own innate healing, or if he gets his hands on them, directly drain life energy from them to use for himself or his allies. He can also send an energetic punch that will stop their heart from beating. Due to the rarity of need, even Cosmo does not know all his offensive capabilities, and he may need to learn them on the fly when an occasion presents itself.</div><div><br /></div>
