---
title: 'MSB: Lehavah, Threxan niece of Ko''Akh'
date: '2026-02-02T06:06:00.0000000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '921452301427635876'
blogger_filename: '/2026/02/msb-lehavah-threxan-niece-of-koakh.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'MSB'
  - 'Character Sketch'
---

<br />
<div>לֶהָבָה — Lehavah — “Flame” (also used as a modern given name)</div><div><br /></div><div>The Reclusive Artist</div><div>A creative individual who lives in seclusion, often possessing a unique perspective or talent.</div><div><br /></div><div>Lehavah is the niece of Ko’Akh the Mighty and has served as Ko’Akh’s shadow and apprentice within Threxan territory until her hundredth year—barely old enough to be taken seriously among the Threxan herds, but old enough to be tested in the wider world.&nbsp;</div><div><br /></div><div>Lehavah is a full head taller than even her uncle, with green-gray scales, and she has braided Copper rings on each of her prominent horns. She wears a toga like wrap loosely draped around her body, but in a way that says fashion and attention to detail. Her pale blue eyes provide a sharp contrast to her green-gray dark scales. She wears braided copper rings around her horns: apprentice marks that glint with quiet pride and a little too much eagerness.&nbsp;</div><div><br /></div><div>Where Ko’Akh is judgment and patience, Lehavah is craft and curiosity and driven passion.—more forge than courtroom—carrying a rune-carved siege hammer of her own making. Her magic doesn’t bloom as effortless force the way Ko’Akh’s appears; it lives in preparation: wards hammered into copper, sigils etched into steel, and oaths bound into braided metal. Lehavah is detached but driven focus by nature, but her inner fire hits like an explosive supernova when her emotions boil over. She must often be reminded to recenter, reembody, and engage in sensory therapy to regulate her dysregulated nervous system.</div><div><br /></div><div>Lehavah is the niece of Ko’Akh and her uncle’s apprentice. She turned 100-years-old last year and was finally called from the herd to be at Ko’Akh’s side to begin her formal training in the wider world. She is often hyper-focused on her own interests without noticing the world around her. She often ignores or doesn’t bother with interpersonal interactions unless they are interesting to her. Sometimes her focus can make it hard to switch to interruptions to her work or even to her expectations, which can take her from a calm focus to outbursts of emotion.&nbsp;</div><div><br /></div><div>Lehavah comes from a culture that does not recognize gender as relevant to tasks, capabilities, roles, or professions. Due to the fact gender norms don’t exist in Threxia, Threxans who are new to the wider world are often confused when they meet the gender norm expectations that often exist within human cultures.</div><div><br /></div><div>As a trade, Lehavah is a blacksmith, craftsman, and metal worker. She creates decorative, utility, and weapon crafts. At her side or in her hand, she carries a massive siege hammer, covered in runes which glow bright blues, reds, and yellows while she works. When working, which she nearly always is, she wears thick hide from a wild beast, which has been expertly crafted to prevent the flames of her forge from singing her other clothes.&nbsp;</div><div><br /></div><div>In contrast to Ko’Akh’s warm and congenial manner towards friends and strangers alike, Lehavah is often oblivious to the people around her unless they are directly relevant. Relevance may be the result of their assisting her with a project, being on a team together, or if they are either telling Lehavah something interesting or they are an attentive audience while she tells them something interesting. Otherwise, the world could be crashing around her and she would be lost in her thoughts, forge plans, or crafting her metals.&nbsp;</div><div><br /></div><div>Because other races seem so irrational to her, she often probes for more clarity and understanding, asking people to explain their perspectives. But this can come across as a challenge or offense to more subtext driven cultures, leading her to be at a total loss as to why the other party is suddenly aggressive towards her.</div><div><br /></div>
<br />
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
