---
title: 'MSB: Veppam - Draconian Alchemist of Zora'
date: '2026-02-08T06:23:00.0000000+00:00'
draft: false
categories:
  - 'MSB'
  - 'Character Sketch'
---

<div style="text-align: right;"><b><i>Veppam (Tamil வெப்பம், heat)</i></b></div><div style="text-align: right;"><br /></div><div>Veppam is a Draconian from the Volcano province of Zora. He was a third prince of his realm which gave him royal duties but not a high chance of having to ever take the throne. Due to his station, Veppam was never given a proper challenge. While Draconians are fierce and take their training seriously, even for princes, there was a hesitance in Veppam’s sparring partners to take it too hard on the prince, lest he take out his anger on them later using his station. When he met Tertius in the palace library one day, Tertius noticed Veppam’s countenance was troubled. After some discussion, Tertius invited him to personal training that only an ancient one could provide. He was given permission to train with Tertius as often as possible, and they spent many such sessions training both on Zora and in Tertius’ Scriptorium over the last few years. That was why he was quick to accept Tertius’ invite to a special class-training in his chosen hometown.&nbsp;</div><div><br /></div><div>Veppam is on par with the average height of a human. His body is covered in obsidian metallic scales, with iridescent sheen. In between his scales a dark red glow pulsed with his heart beat. His retractable claws are made of this same material. On his back, fully folded in most of the time, are leathery wings that end in sharpened points. His tail runs down his back and wraps around his waste, but when extended it can whip around up to twice his height. He has no physical external ears, so his hearing while good but not better than humans.&nbsp;</div><div><br /></div><div>As both a prince and a Draconian in general, Veppam is cordial to a fault, as their race attempts to overthrow their violent reputation (primarily due to old lore) using etiquette and hospitable practices. Some Draconians (also known as Dragonborn) present themselves more like a posh butler than a fierce warrior. Nevertheless, their war-time capabilities are not to be taken lightly. Veppam has been raised in a culture that knows their society is safest when outsiders view them as harmless, or at least, not a threat. In this, Veppam faces increasing pressure as he attempts to quell the fire burning within him to uphold this cultural facade. Eventually, he learns that feigning powerlessness or softness is not in-itself wise. True strength comes from knowing your own limits, healing your triggers, and using selective but assertive force when the occasion calls for it. This comes into acute view when his cordialness fails to calm down people who mean his party harm, at which point he is left with the decision to protect his people or hold up his inherited facade.&nbsp;</div><div><br /></div><div>Veppam is a prince and therefore a member of the highest society on Zora. Personally, he is a devotee of the cult of The Great Dragon, or the cult of Leviathan. This cult is considered quaint on Zora and is often associated with backwards thinking folks. Most Draconians either worship Ra-Ah the sun deity (less common) or find themselves in a direct reverence for the nature of heat, fire, light, etc., in a mix of quasi spiritualistic reverence and scientific fascination. Therefore, Veppam holds these in his heart as well, but remains fascinated with the Leviathan mythologies, and wonders if there is more than myth to its histories.</div><div><br /></div><div>As a Draconian, Veppam requires heat, often extreme heat. He can withstand the cold for brief periods, but may find even a cool rainy day to be unbearable after enough time has passed. Therefore, he carries heat-cores full of fire manna both within his dimensional storage in stasis, and on his person, acting like magical hand warmers, layering him in a thin coat of fire manna when in use.&nbsp;</div><div><br /></div><div>Veppam’s primary realm of study is Alchemy, and he is able to brew potions, elixirs, tinctures, and work with transfusing concepts into inanimate objects or weapons. Veppam, as a prince and scholar, is not wild and reckless with his craft. He is clean, orderly, organized, methodical, and bases his craft as much on precession as on instinct. He is most successful with heat-based and fire-based and light-based products.</div><div><br /></div><div>While Veppam may have a calm and cordial demeanor with people, and an orderly methodological approach to his craft, he remains pensive, locked, rigid, and must learn to allow for the variable of chaos in his approach to life. This becomes a point of contention he must work through.</div><div><br /></div><div>Common Alchemical Products</div><div><ul style="text-align: left;"><li>Potions – temporary effects</li><li>Elixirs – long-term or permanent effects</li><li>Tinctures – subtle, stacking effects</li><li>Catalysts – enable other magic or crafting</li><li>Philosophical Stones – rare, narrative-tier items</li><li>Alkahests – universal solvents (can unmake things)</li><li>Homunculi – artificial life (always morally loaded)</li><li>Infused Materials – alchemically altered metals, glass, ink, bone</li></ul></div><div><br /></div>
