---
title: 'MSB: Gwendol of the Wetlands Pride is a Leonid warrior.'
date: '2026-02-08T07:08:02.9370000+00:00'
draft: false
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '7717397446223412939'
blogger_filename: '/2026/02/msb-gwendol-of-wetlands-pride-is-leonid.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'MSB'
  - 'Character Sketch'
---

<br />
<div>Gwendol of the Wetlands Pride is a Leonid warrior. She and her twin brother, Gareth, are sent by the Pride to take part in Tertius’ offer to train two of their most promising members, whichever two the Pride chooses to send.</div><div><br /></div><div>Gwendol stands heads taller than the human race average, and eye to eye with her brother. While somewhat leaner than her brother, she is still packed with muscles seen easily even through her white fur. As a woman Leonid, she does not possess the large mane of her brother. She instead has a head of silvery-white hair that she keeps cut short and spiked. While both Leonids wear earrings, Gwendol wears many on each ear, and a necklace of gold with a fine blue jewel, which powers her private dimensional storage space.&nbsp;</div><div><br /></div><div>Unlike Gareth’s brutal great hammer, Gwendol carries a bow for ranged attacks, and two one-handed axes, made of the same titanium with gold inlays, like her brother’s hammer. Where Gareth is brute-strength, Gwendol is a dancing wind carving through hordes of monsters or enemies as if she is threshing wheat.&nbsp;</div><div><br /></div><div>The Wetlands Pride twins are a force to be reckoned with on any battlefield, but the logistics are up to someone else. They consider themselves the first into battle and last to leave, but they leave decisions about what battle to join to their leaders.&nbsp;</div><div><br /></div><div>That having been said, leaders do need to keep them busy doing something, or they will find themselves getting up to mischief and trouble, as they are still curious cats.&nbsp;</div><div><br /></div><div>Whereas Gareth is the first to stand up in a tavern to protect a server from harassment but a brute, Gwendol stands back and watches the room. She scans for exits and blind spots when they enter. She scan for additional combatants Gareth might not see coming. She calls out the shots as she sees them, or intervenes as needed.&nbsp;</div><div><br /></div><div>If Gareth is quick to punch, Gwendol is cautiously curious before acting. Gareth opens the fights, but Gwendol usually ends them decisively. She protects Gareth, mostly from himself. He’s always getting into situations where she feels the need to intervene.&nbsp;</div><div><br /></div><div>While all Leonids, male and female, are strong, Gwendol is doubly so. As a result of her status as a warrior and accomplishments on the battlefield, and her competitive nature, many intellectuals find her intimidating physically. While her mind for puzzles and situational awareness often make her incapable of bearing too much attention from non-intellectuals. She hopes to find friends who are both, but often ends up alone on the edge watching from the sidelines of social functions, assuming the role of guardian instead.</div><div><br /></div><div><br /></div>
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>

