---
title: 'MSB: Gareth of the Wetlands Pride is a Leonid warrior.'
date: '2026-02-08T07:07:29.1240000+00:00'
draft: true
blogger_blog: 'Darrell Wolfe, Storyteller'
blogger_status: 'LIVE'
blogger_post_id: '3728419605398017372'
blogger_filename: '/2026/02/msb-gareth-of-wetlands-pride-is-leonid.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Darrell Wolfe, Storyteller/feed.atom'
categories:
  - 'MSB'
  - 'Character Sketch'
---

<div>Gareth of the Wetlands Pride is a Leonid warrior. He and his twin sister, Gwendol, are sent by the Pride to take part in Tertius’ offer to train two of their most promising members, whichever two the Pride chooses to send.&nbsp;</div><div><br /></div><div>Gareth is a tall white Leonid with golden eyes and a proud mane of white hair. His muscles show through his fur, and he carries multiple weapons for all forms of combat. His most precious weapon is his great hammer, which is titanium with gold inlays magically fortified and sealed with runic enhancements. In addition to his great hammer, he also carries a long sword on his back, a dagger at his side, and dimensional bag at his hip with exploding metallic balls. Gareth was born and bred for combat, and it shows in the way he carries himself even at rest.&nbsp;</div><div><br /></div><div>Despite his gruff demeanor and sturdy posture, Gareth is no brute. He resents when anyone uses strength to prey on the weak, as strength should defend the most vulnerable of any Pride. While he will be among the louder patrons in any tavern, he will be the first to step into a fight he wasn’t invited to if a vulnerable party is at risk. This gets him into situations that may sometimes require a more diplomatic hand to settle.&nbsp;</div><div><br /></div><div>Gareth’s sister is his fellow warrior, and he does not consider her a weaker opponent. They are true equals on the battlefield, and often operate as with one mind under stress, seamlessly taking symbiotic roles on the field.&nbsp;</div><div><br /></div><div>Gareth was told by his great grandmother that she was shown in a vision that his name should be Gareth, for his ancestor also bore that name in a different world and time. He never knew if she was telling him the truth or spinning a tale for a youngster, and she died many years before he was old enough to think of the question. So he likes to think that grandmother went on a journey to find this older Gareth in the greater multiverse.&nbsp;</div><div><br /></div><div>Being a mammal, Gareth is prone to the normal realities that brings, including being vulnerable to cuts and breaks of the mammal body. That being said, his magically enhanced body can take a lot of punishment before he needs a rest. On the battlefield, he may run to his opponents, but he often simply walks into the fray, as though he were stalking his prey, and then he acts in sudden bursts of movement that are blinding and overwhelmingly strong.&nbsp;</div><div><br /></div><div>Extreme heat and cold are both dangerous to Leonids after prolonged exposure, so while their fur offers natural protection to most elements, they may still be found with coats in the winter and cooling devices in summer.&nbsp;</div><div><br /></div><div>Gareth knows he is not ‘smart’ in the ways many count brain power. He is an adept magic user and powerhouse fighter, but he leaves complicated things to his sister, Gwendol, and other leaders and thinkers. Because of this, he often feels intimidated by smart people, because he doesn’t often know how to respond. He can be a tad clueless when it comes to puzzles and riddles. Therefore, between this and his quick-to-act nature, he can sometimes find himself trapped in situations that are legitimately beyond him and requiring rescue.&nbsp;</div><div><br /></div><div><br /></div><div><br /></div><div><br /></div>
<br />
<br />
<br />
<br />
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>
