---
title: 'MSB: An-Ying, Mantisai, Cult of Shadows, Path of Smoke & Shadows...'
date: '2026-02-02T06:07:00.0000000+00:00'
draft: false
categories:
  - 'MSB'
  - 'Character Sketch'
---

<div>Chinese (Mandarin) - 暗影 (Ànyǐng) — “dark shadow”</div><div><br /></div><div>An-Ying is a Mantisai from the Cult of Shadows, a reclusive cult in the Mantisai homelands under Mahakala (The Great Darkness, lord Protector), who is a god dedicated to protection from the shadows. As a servant of Mahakala, An-Ying watches and observes the world around him, with an eye to prevent or judge injustices.&nbsp;</div><div><br /></div><div>Many misunderstand the cult of shadows, due to their reclusive nature. Rumors abound that world leaders have been assassinated and nations turned over by the secret machinations of the Cult of Shadows. Due to these (not entirely untrue) rumors, any dark robed Mantisai seen within a rural city may be blamed for all sorts of calamities that fall on their community. Ironically, it is the work of the Cult of Shadows that usually prevents or mitigates these same disasters, but that does not stop rural superstitions.</div><div><br /></div><div>An-Ying is a full member of the cult but has struggled with developing his path due to blockages in his use of shadow essence. Tertius was asked by the elders of the cult to take over An-Ying’s training in the Manna Arts, as a favor to them. They’ve had many working arrangements for as long as the cult has existed. Tertius agrees to help An-Ying get unstuck and progress on his path. Why is An-Ying stuck?</div><div><br /></div><div>An-Ying is quiet, growing bitter at his failure to follow his father’s path. An-Ying’s father was executed by a foreign government for a misunderstanding over his involvement in their political upheaval. Members of the cult knew the real story, that Hiro, An-Ying’s father, was the scalpel behind the scenes removing the gang leaders who were attempting to overthrow the governmental structures of the town. When the cult learned of Hiro’s treatment, they quietly removed the king every leader involved in it, and planted a king who would follow the way of justice in their place; all without the people of the kingdom being aware of anything more than in-fighting and factionalism. The pressure to live up to Hiro’s legacy has given An-Ying a father wound and identity crisis. He cannot find his own path because he’s too distracted by failing to live up to his father’s.</div><div><br /></div><div>An-Ying is trained to be quiet, observe from the shadows, and have patience of a stone. But he does not find quietness or patience to be virtues he can hold for long. His impatience with his own lack of progress leads him to bitterness and resentment; a feeling that he is fundamentally broken and has no value in his role. This bitterness leads to outbursts of anger, sometimes shouting, and sometimes violent reactions. Rather than still rock in the shadows, An-Ying finds himself the burning embers that lead to a smoke filled room. The Shadow essence path requires stillness and patience; but when An-Ying attempts to build these virtues to manipulate shadow he always falls short, because body wants to burn instead. This burning is recognized by Tertius as a misaligned path, and he encourages him to embrace the burning and see where it leads.</div><div><br /></div><div>Working with Tertius, An-Ying learns to embrace his fire affinity and blend it with his shadow training to develop a smoke affinity. Where there is smoke, there is fire. In this way, he re-purposes his training rather than letting it go to waste. He forges it in the fires of his true affinity, and creates a new path no other Mantisai in memory has followed.&nbsp;</div><div><br /></div><div>An-Ying, as a Mantisai, retained the basic shape and form of his Preying Mantis ancestors; walking on four legs and using his front two arms for more humanoid tasks. All six limbs have retractile blades for attack and defense. At core, though evolved and sentient, the Mantisai are hunters. They require a prey and a hunt to keep them motivated and in motion.</div><div><br /></div><div>An-Ying is usually found wearing black-leather-like armor, with dark red cracks glowing throughout like the embers of a smoldering fireplace or volcano. He wears a belt upon which are thousands of thin ceramic leafs, which he imbues with his smoke manna and throws at his enemies. He also wears two long daggers which mirror his razor edge arm braces.</div><div><br /></div><div>While most with the fire affinity are known for their bright fire and flames and sun manna; An-Ying develops an entirely unseen path&nbsp; of Smoke &amp; Shadows; where “Flame is truth. Shadow is secrecy. Smoke is the verdict.”</div><div><br /></div><div>He can burn objects by touching them, and throw intense balls of manna that are smoky-shadows on the outside by burning infernos on the inside. In low visibility darkness, you will feel the attack before you see it.&nbsp;</div><div><br /></div><div>Through Smoke &amp; Shadows, An-Ying is able to blend with most shadows becoming nearly invisible even feet away in bright daylight. When no natural shadow is available, for an extra manna cost, An-Ying can use smoke to blur the eye and create an absence of light which mimics shadow in most respects. But its heat can still be felt from up close. On a hot day, this could be overlooked as a passive heat absorbed by the building or object which obscures him. But on a cold night this heat creates suspicions for guards. To overcome this, An-Ying, at times, has to create a building fire to hide within.&nbsp;</div><div><br /></div><div>The insidious nature of his Smoke &amp; Shadows technique allows him to create area of effect attacks where his smoke takes on substance and clings to the oils in skin or clothing, and it dries out and burns natural resources (such as those made of wood).&nbsp;</div><div><br /></div><div>Given that smoke, via heat, are his primary tools; wind and cold are his antidotes. When the wind or cross breeze is too strong, it can either dispel his hiding or reveal it in some way. It can lead to ineffective area attacks. And a strong enough wind can threaten to put his fire out entirely if his manna reserves are too low to resist. Like wind, cold can be a problem. The cold evening won’t hinder his ability to burn but it will make his heat more obvious and suspicious, ruining his ability to hide using smoke. In extreme cold, as when attacked by ice or cold water, his fire can be snuffed out. This still leaves an advanced martial artist with blades for weapons, but without his fire his throwing leafs are useless, and his options are far more limited. In addition, his body growing cold could cause him to freeze up or in extreme cases die.</div><div><br /></div><div>An-Ying only answers to An-Ying, and his verdict is slow in coming, for he was trained to observe before acting. Yet, when he does act, his judgment is final and the smoke he leaves in his wake is the sign of his judgment.</div><div><br /></div><div>At higher grades of the Manna Arts, An-Ying learns to manipulate smoke to such a degree that he can create long-distance avatars to speak through fire-pits and fire-places; communicating with allies and terrifying foes.</div><div><br /></div><div>At the highest grades, he learns to make his shadows tangible to the point that he can manipulate objects as though he had extra hands. The number of additional arms and hands is only dependent upon his ability to hold them in his mind’s eye.&nbsp;</div><div><br /></div><div>An-Ying can also take advantage of the fact that heat rises, and change his own body to adapt to this feature of smoke. But since the heat for the reaction is coming from him, he can direct his smoke levitation in the directions he wants to go. This may allow him to float up to or down from a tall roof, or even fly, albeit more slowly than a bird, to far off destinations limited by his manna capacity, which can be drained harder in unfavorable conditions.</div><div><br /></div><div>While not the silent stone his father’s legacy would have predicted, his more aggressive approach still allows him to operate within the shadows, while taking far more aggressive action against injustice, as he sees fit.</div><div><br /></div><div>In later years, he finds followers who want to join him on his path, and he is forced to decide if he must start a new cult or school dedicated to this path. He does not know if it still falls within Mahakala’s domain. But he is assured that this is the will of Mahakala, to become a new cult under his brand and divine protection. So he accepts his somewhat unwelcome status as leader of a new cult. Blah.&nbsp;</div>
