---
title: 'MSB: Rufus Fangborn, a Half-Wolf, half-Mastiffarian'
date: '2026-02-09T02:01:00.0000000+00:00'
draft: false
categories:
  - 'MSB'
  - 'Character Sketch'
---

<div><b>Rufus Fangborn, a Half-Wolf, half-Mastiffarian</b>, was ostracized from his pack in his teens for being too aggressive for Mastiffarian culture. The pack leader looked at him in disgust, “Es un híbrido; no es uno de los nuestros,” which means “He is a hybrid, he is not one of us.” They sent him on his way, refusing eye contact, turning their backs to him as he left, with only that which he could carry with him, and without weapons or storage items; without weapons for they did not trust his violent nature, without storage items because they were too valuable for must remain with the pack. So he wandered for many years, mostly keeping to himself in the woods as a hunter, sometimes making temporary homes in larger cities where the various Offspring of Creator mixed and he could blend in with the crowds. But even then he was often shunned for his clear Wolf heritage.</div><div><br /></div><div>Rufus’ pack was from a region far to the south of Keldeah, and Cosmo Valentine found Rufus roaming the woods and wetlands as he traveled to meet Tertius and Ko’Akh in Salem Village. While a Mastiffarian himself, Cosmo was from a different pack and pack culture, and he told Rufus that there are none of Creator’s Offspring that are not precious to him, and that his old pack leader sounded like a wolf in heart.&nbsp;</div><div><br /></div><div>Rufus bore the large frame and dense body mass of his Mastiff heritage, along with the drooping jowls. His ears were pointed and long from his wolf side. While he fur was Mastiff short, it was white and grey from his wolf father, and it raised on his shoulders when enraged. His silver wolf eyes were set under strong Mastiff eye ridges. Rufus wore a dark green hunters cloak with a hood. On his back was a bow and at his hip a quiver. On his chest were strapped two curved daggers, resembling fangs. On the hilt of each dagger were emeralds with a soft hint of earth affinity manna.&nbsp;</div><div><br /></div><div>Given his mixed heritage, and violent outbursts from youth, Rufus was never considered anything other than a fetch mule for the pack, and was never allowed to enter formal training of any kind. He learned to fight first by himself in the woods, defending himself from the attacks of local beasts and monsters there who would have made a meal of him. Later he received some training while picking up odd jobs in security. Despite his lack of fight training, his size and demeanor made him an easy hire for security guard groups looking to use intimidation as a tool. So he trained, he watched, he grew.&nbsp;</div><div><br /></div><div>Rufus felt the manna around him, and sometimes he thought he could manipulate it, but it was fleeting and he never grasped it fully or made any practical use of it. Sometimes, when he wasn’t thinking about it, he would find roots, branches, or vines coming to his aid. Whether it be to defend him from beasts or to help him gather things around his camp. But as soon as he paid direct attention to it and tried to make it happen on purpose, it would stop entirely.&nbsp;</div><div><br /></div><div>Cosmo heard his story, and knew it was an appointed meeting by the elohim. He invited him to join him on his journey to Salem Village and meet Tertius. Rufus decided it would be better than his aimless wandering, so he joined. Cosmo was nothing like the Mastiffarians in Rufus’ old pack. Cosmo was a gentle warrior-monk, a damned fine cook, a healer, and generally a pacifist. On more than one occasion, Rufus felt the blood lust inside of him to attack a group of people who came too close, but Cosmo befriended them, healed any who needed it, and introduced Rufus to their best fighters. The more they traveled together, the more Rufus felt a kinship that made him wonder if this was what Pack-Life was supposed to feel like.&nbsp;</div><div><br /></div><div>While his magical abilities are still largely unknown, Cosmo told Rufus that it was clear that Rufus had at least some innate affinity with earth manna.&nbsp;</div><div><br /></div><div>It was also clear from the few attacks they endured on the way, two by beasts and one by roaming thieves, that neither Cosmo or Rufus were pushovers. Cosmo always began with negotiation and diplomacy, but when the attacks began, neither held back. Rufus used his twin fangs in melee and his bow to bring down people coming from any distance over 100 meters. In one instance where a particularly large beast attacked Rufus, and Cosmo was preoccupied with another, roots shot from the ground and hold the beast still while Rufus finished it off with bow shots from a safe distance. When the fight was over, and Rufus began paying attention to the roots, they fell limp and pulled back into the earth. He was both grateful and frustrated by the experience. Cosmo sat with him that night and discussed the Manna Arts. As he listened to Rufus’ experiences and watched him attempt to draw from nature intentionally, Cosmo noted, “Manna is like water or sand, the more you close your first around it, the more it slips away. Rather, become a vessel in which it can reside.” This sounded like goofy spooky nonsense, but Cosmo was a trained Manna Artist, so he tried to consider Cosmo’s words.</div><div><br /></div><div>Rufus was nervous when he saw Salem in the distance. Going into populated towns was always a gamble for him, and smaller towns were usually more hostile to wolf-kind. Cosmo, sensing Rufus’ hesitation, assured him that he was in safe company, and they headed into the town.&nbsp;</div><div>&nbsp;</div><div><br /></div>
<br />
<div id="mc_embed_signup">
<form action="https://darrellwolfe.us3.list-manage.com/subscribe/post?u=979cb0db6ca74343e82a059ba&amp;id=14df3ba97b" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
<div id="mc_embed_signup_scroll">
<label>Subscribe Now - Pursue a No Hiding Lifestyle</label>&nbsp;<input class="email" id="mce-EMAIL" name="EMAIL" required="" type="email" value="" /><br />
<div aria-hidden="true" style="left: -5000px; position: absolute;">
<input name="b_979cb0db6ca74343e82a059ba_14df3ba97b" tabindex="-1" type="text" value="" /></div>
<div class="clear">
<input class="button" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" /></div>
</div>
</form>
</div>
<br />
<span style="font-family: &quot;tempus sans itc&quot;;">Shalom: Live Long and Prosper!</span><br />
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;; font-size: 18pt;">Darrell Wolfe (DG Wolfe)</span></div>
<div class="MsoNormal">
<span style="font-family: &quot;tempus sans itc&quot;;">Storyteller | Writer | Thinker | Consultant @&nbsp;<a href="http://www.darrellwolfe.com/p/start-here-about_12.html" target="_blank">DarrellWolfe.com</a></span><br />
<br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.gallupstrengthscenter.com/" target="_blank">Clifton StrengthsFinder</a>: Intellection, Learner,&nbsp;</span><span style="font-family: &quot;tempus sans itc&quot;;">Ideation,</span><span style="font-family: &quot;tempus sans itc&quot;;">&nbsp;Achiever, Input</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><a href="https://www.16personalities.com/infj-personality" target="_blank">16Personalities</a> (Myers-Briggs Type): INFJ</span><br />
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span>
<span style="font-family: &quot;tempus sans itc&quot;;"><br /></span></div>

