---
title: 'VIsion and Mission'
date: '1980-01-02T05:59:00.0000000+00:00'
draft: true
blogger_blog: 'N2 Good Success Resource Center'
blogger_status: 'LIVE'
blogger_post_id: '7895882937155710849'
blogger_filename: '/1980/01/vision-and-mission.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/N2 Good Success Resource Center/feed.atom'
---

<h4>
Mission of N2GS</h4>
<div class="widget-content">
<div style="text-align: center;">
<span style="line-height: 18px;"><b>Providing the tools you need&nbsp;to enter&nbsp;Into <a href="http://n2gs.blogspot.com/2012/03/good-success.html" target="_blank">Good Success</a>!</b></span></div>
<div style="font: 100% Georgia, serif;">
<b style="font-family: 'trebuchet ms', Trebuchet, sans-serif; font-size: 13px; line-height: 18px;"><span style="color: #251a9c;"></span></b><br />
<blockquote class="tr_bq">
<a href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=joshua+1:8&amp;t=kjv">Joshua 1:8</a><br />
<br />
This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night, that thou mayest observe to do according to all that is written therein: for then thou shalt make thy way prosperous , and then thou shalt have good success.</blockquote>
</div>
</div>
<h4>
Vision of N2GS</h4>
<ul>
</ul>
<ul>
<li>Providing Biblical Answers to Practical Problems&nbsp;</li>
<li>People walking free (<i>spiritually, emotionally, mentally, intellectually, physically,&nbsp;and financially</i>) to pursue the perfect will of God for their lives. </li>
<li>People living disconnected from the World's System. </li>
<li>&nbsp;Blog Posts, Books, Merchandise, and other creative arts materials, provided to aide and assist in that freedom. </li>
</ul>
<br />
DW