---
title: 'Business Plan (under construction)'
date: '2018-03-18T13:19:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'The Playground, LLC'
blogger_status: 'LIVE'
blogger_page_id: '1599141879170860100'
blogger_filename: '/p/business-plan-in-progress.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Playground, LLC/feed.atom'
---

<h2 style="text-align: center;">
The Playground</h2>
<div style="text-align: center;">
<i><br /></i> <i>Type: a Community Entertainment Center</i></div>
<div style="text-align: center;">
<i><br /></i> <i>Tagline: Giving North Idaho a Place to Play</i><br />
<i><br /></i></div>
<h3 style="text-align: center;">
</h3>
<h3 style="text-align: center;">
Business Plan</h3>
<div style="text-align: center;">
<i><br /></i> <i>Flavia Wolfe, Member (77%) - President &amp; Chief Creative Officer (CCO)</i><br />
<i><br /></i> <i>Darrell Wolfe, Member (23%) - Vice President &amp; Chief Implementation Officer (CIO)</i></div>
<br />
<h4>
</h4>
<h4>
</h4>
<h4>
<br /><u>Executive Summary</u></h4>
<br />
<b>Product/Service</b><br />
<div>
<br /></div>
The Playground is a Movement-Based Entertainment Center for the Coeur d'Alene, Idaho Community. The facility features an indoor over-sized <a href="https://theplaygroundllc.blogspot.com/2018/02/playsmart-worlds-best-playgrounds.html">PlaySmart Playground</a>, tables and seating for parents (who tire quickly) and meeting rooms. There are also mini-events and movement-based arcade games.<br />
<div>
<br />
<b>Customers</b><br />
<b><br /></b> The Playground's target market is the local community; including families, teenagers, young adults, and local businesses (and their staff). We are not an "event" or "special occasion" or "theme park"; rather, we are a local hang-out for the local community.<br />
<br />
<b>Future of the Company</b><br />
<b><br /></b> As the Coeur d'Alene, Idaho area continues to grow, the need for local cost-effective activities grows with it. There are frequent requests on localized Facebook groups for places to "take the kids". There are many free activities here, weather permitting. However, when it's too hot or too cold, there are very few places to take the family that will not break the bank.<br />
<br />
<b>Mission Statement</b><br />
<br />
Giving North Idaho a Place to Play!<br />
<br />
<b>Vision Statement</b><br />
<br />
The Playground&nbsp;provides the local community with a "place to play". Kids of all ages (even adults) can come to get their energy out, build community, learn &amp; grow. It provides families a "place to play" so that kids can get their energy out in a safe and fun environment and so that parents can catch up on work, find community with other parents, or just relax without worrying about the kids. It provides a forum for classes, meetings, and more; serving business and churches as well as families. See <a href="https://theplaygroundllc.blogspot.com/p/what-is-playground.html" target="_blank">"What is The Playground?"</a><br />
<br />
<br />
<br />
<br />
<br />
<h4>
<u>Organization &amp; Management</u></h4>
<b><br /></b> <b>Legal Structure</b><br />
<br />
The Playgound, LLC is a Limited Liability Corporation (LLC) registered in the state of Idaho.<br />
<div>
<br /></div>
<div>
NAICS Code: 713990<br />
Code Description: All Other Amusement and Recreation Industries (Recreational Facility/Trampoline Facility) NAICS Website: https://www.naics.com/naics-code-description/?code=713990</div>
<div>
<br />
<b>Intellectual Property Rights</b><br />
<b><br /></b>All Intellectual Property Rights are held by The Playground, LLC</div>
<div>
<h4>
<b>Principal Members</b></h4>
<ul>
<li>Flavia Wolfe, Member (77%) - President &amp; Chief Creative Officer (CCO)</li>
<li>Darrell Wolfe, Member (23%) - Vice President &amp; Chief Implementation Officer (CIO)</li>
</ul>
</div>
<div>
<br /></div>
<div>
<b>Principal Roles &amp; Responsibilities are as outlined:</b><br />
<b><br /></b> Only Darrell &amp; Flavia Wolfe have decision making authority on behalf of the business/LLC.<br />
<br />
<b>Flavia A Wolfe: President &amp; Chief Creative Officer (CCO)</b><br />
<ul>
<li>Creative Vision</li>
<li>Organization &amp; Structure</li>
<li>Hiring &amp; Firing Employees/Team Members</li>
<li>Accounting, Books, and Bill Payments</li>
<li>Operations &amp; Administrations</li>
<li>Customer Experience</li>
</ul>
<b>Darrell G Wolfe: Vice President &amp; Chief Implementation Officer (CIO)</b><br />
<ul>
<li>Organization &amp; Structure</li>
<li>Hiring &amp; Firing Employees/Team Members</li>
<li>Taxes &amp; Reporting</li>
<li>Operations &amp; Administrations</li>
<li>Accounting, Books, and Bill Payments</li>
</ul>
<b>Other Roles:</b><br />
<b><br /></b> Other assistant managers and employees are employed by the LLC and have no ownership interest or final decision-making authority. They operate under the limited authority of their role.<br />
<br />
<b>Market, General &amp; Assistant Manager Roles &amp; Responsibilities:</b><br />
<ul>
<li>Become CPR/First Aid Certified (paid for by The Playground)</li>
<li>Oversee Team Members</li>
<li>Assist in interviews, hiring, and firing processes</li>
<li>Override transaction authority</li>
<li>Refunds &amp; Discounts</li>
<li>Opening &amp; Closing Duties (including keys and codes)</li>
</ul>
<b>Team Member Roles &amp; Responsibilities:</b><br />
<ul>
<li>Become CPR/First Aid Certified (paid for by The Playground)</li>
<li>Operate Cash Register/Payments</li>
<li>Watch Kids / Referee</li>
<li>Assist with private parties</li>
<li>Food Preparation, Food Handling, Food&nbsp;Delivery, Order Taking</li>
<li>Cleaning: Includes trash, lost &amp; found, wiping and disinfection floors and surfaces.</li>
<li>Turning Off &amp; On the equipment.</li>
<li>Repairing rips and tears in equipment.</li>
</ul>
</div>
<div>
<b>Who can sell?</b><br />
<br />
Darrell &amp; Flavia Wolfe are the primary contacts and agents. In addition, employees run cash register &amp; sales based on listed pricing. Any special group rates or requests are handed to Flavia for consideration.<br />
<br />
Future: Once we have the revenue to support the need, we will hire a full-time events planner.<br />
<br />
<br />
<br />
<br />
<br /></div>
<div>
<div>
<b><u>Industry</u></b><br />
<br />
<br />
<b>Company Advantages</b><br />
<b><br /></b> The Playground has no direct competition in the metropolitan area. Those play-facilities that do exist are not well done or of a similar concept. The bounce houses have inconsistent hours, focusing on parties and rentals. The amusement parks in the area are cost-prohibitive for the average family to visit often (more than once a year).<br />
<br />
<br />
<b>The Playground Offers:</b><br />
<ul>
<li>Child Safe Check-In/Check-Out</li>
</ul>
<ul>
<li>A large play facility made from a material that allows a clear line of sight throughout, giving parents the freedom to relax and peace of mind to know where the kids are at all times.</li>
</ul>
<ul>
<li>Comfortable seating for parents while kids play, family meals, community building with other parents.</li>
</ul>
<ul>
<li>WiFi for parents to use (for work and play of their own)</li>
</ul>
<ul>
<li>Affordable Prices (for entry and food) that allow families to visit often.</li>
</ul>
<ul>
<li>Group Activities (such as Pokemon Nights, and Art Nights) that allow for families to build community with each other.</li>
</ul>
<ul>
<li>Corporate/Adult/OlderTeen Nights, including Team Building/Team Meeting nights</li>
</ul>
<br />
<b>Regulations</b><br />
<u><br /></u> <span style="background-color: yellow;">To Be Researched (what regulations affect kids, playgrounds, and food delivery?)</span><br />
<br />
See&nbsp;<a href="http://theplaygroundllc.blogspot.com/p/regulations-appendix.html" target="_blank">Regulations Appendix</a>&nbsp;for more details.<br />
<br />
<br />
<br />
<br />
<div>
<br /></div>
<h4>
<u>Service/Product Line</u></h4>
<br />
<b>Product Lifecycle</b><br />
<b><br /></b>The PlaySmart Playgrounds are made of a material that has a life-span of&nbsp;xxxxx&nbsp;years. Replacement components for well-worn areas are available for a minimal cost (from PlaySmart).<br />
<br />
<br />
<b>Research &amp; Development (R&amp;D)/ Future Vision</b><br />
<b><br /></b>The following R&amp;D is being considered:<br />
<ul>
<li>Software to integrate membership, POS, Discounts, Website and Social Media.</li>
</ul>
<ul>
<li>Potentially a larger facility with more areas of play, full-service kitchen, and more activities/playrooms.</li>
</ul>
<ul>
<li>Opening other businesses also focused on play. In the future, we would like to expand into a larger facility (or several facilities next to each other) to include a larger rope/net climbing playground (see Going Bonkers in Lewisville, TX for example), Bounce Houses, Trampoline Park, Rock Climbing, and Parkour Gym (Ninja Warrior, Spartan training).</li>
</ul>
<div>
<br /></div>
<b>Pricing Structure</b><br />
<b><br /></b> Prices are structured for profit but still affordable for the average family. Additional revenue opportunities are available through games, food court, and special group activities/classes.<br />
<br />
<br />
<b>Entry</b><br />
<ul>
<li>Single Visit</li>
<ul>
<li>Kids (3-17): $10</li>
<li>Adults (&amp; Kids under 3): $5</li>
</ul>
</ul>
<ul>
<li>Monthly Memberships available:</li>
<ul>
<li>Monthly, Family up to Four: $45</li>
<li>Monthly, Family up to Eight: $90</li>
</ul>
</ul>
<ul>
<li>Annual Memberships available:</li>
<ul>
<li>Monthly, Family up to Four: $450</li>
<li>Monthly, Family up to Eight: $900</li>
</ul>
</ul>
<ul>
<li>Larger Groups: Call for Quote&nbsp;</li>
</ul>
<br />
<br />
<b>Additional Revenue Opportunities</b><br />
<b><br /></b> <b>Food Court</b><br />
<ul>
<li>Burgers $5</li>
<li>Grilled Cheese $3</li>
<li>Hot Dogs $3</li>
<li>Pizza $5</li>
<li>Soda by the cup, free refills $1.50</li>
</ul>
<b>Mini Market</b></div>
<div>
<ul>
<li>Candy, Snacks, Chips, IceCream</li>
<li>Vended Water Bottles</li>
<li>Vended Soda, Juice, CapriSuns, etc.</li>
</ul>
</div>
<div>
<b>Arcade (Games)</b></div>
<div>
<ul>
<li>Movement-Based Games $0.25/Game</li>
<ul>
<li>Dane Dance Revolution</li>
<li>Skee Ball</li>
<li>xx</li>
<li>xx</li>
<li>x</li>
<li>x</li>
<li>x</li>
</ul>
<li>Nerf Shooting Gallery</li>
</ul>
<b>Activities/Classes</b><br />
<ul>
<li>$10 to attend (includes entry)</li>
<li>$5 for members</li>
</ul>
<br />
<br />
<ul>
</ul>
<div>
<br /></div>
<h4>
<u>Marketing &amp; Sales</u></h4>
<b>Growth Strategy</b><br />
<b><br /></b> We will grow in stages, adjusting at each stage:<br />
<br />
<b>Stage 1: Soft Opening</b><br />
<b><br /></b> Start with a soft opening, relying on word of mouth, friends, acquaintances to drop-by.<br />
<br />
Have Website/Social Media/Google Place Pages intact before soft opening, then ask those who come in, or those we talk to, to like the Facebook Page, Check out our Coupon (on Website in exchange for email address), and "save" us on their Google Maps.<br />
<br />
<b>Stage 2: Launch/Gran Opening</b><br />
<b><br /></b> After two weeks, make any adjustments, and launch an ad-campaign.<br />
<br />
Place Facebook Ads, Newspaper Ads, Issue Press Release, Other, as needed.<br />
<br />
<b>Stage 3: Continual</b><br />
<b><br /></b> Quarterly, issue discounts, promotions, buy-one-get-one for Entry and Classes.<br />
<br />
Quarterly, review activities for effectiveness and adjust.<br />
<br />
<h4>
Customer Communications</h4>
We will communicate via the following:<br />
<br />
<b>Channels of communication: </b><br />
<ul>
<li>Facebook (and Facebook Events)</li>
<li>Website Updates</li>
<li>Calendar: Website/Google Calendar (sharable, embeddable)</li>
<li>Email List</li>
</ul>
<b>Types of communication:</b><br />
<ul>
<li>Past Events (Here's what we did)</li>
<li>Present Events (Here's what we're doing)</li>
<li>Future Events (Here's what coming)</li>
<li>Coupon/Discounts/Promotions</li>
<li>Tips/Articles</li>
<li>Play/Energy Tips</li>
<li>Other local family/kid events around town</li>
<li>Painting/Pokemon/Other Tips</li>
</ul>
<b><br /></b>
<br />
<b><br /></b> <b><br /></b>
<br />
<h4>
<u>Funding Request</u></h4>
<b>Summary of Funds Needed:</b><br />
<br />
<i>What funds are needed, for what, and by when?</i><br />
The Playground needs $xxxxxx by xx/xx/xx in order to launch our soft opening. We currently have $xxxxx and we still need $xxxxxxx.<br />
<br />
<br />
<b>Summar of Cost Projections:</b><br />
<br />
Costs (Startup, including three months Ongoing)<br />
<br />
Startup costs are one time for purchases of equipment, building, and other startup fees/costs. Many costs cannot be exactly as they are dependent upon a final deal/invoice.<br />
<br />
These cost projections are a good faith estimate. See the <a href="http://theplaygroundllc.blogspot.com/p/costs-projections-appendix.html" target="_blank">Costs Projections Appendix</a> for details.<br />
<br />
<br /></div>
<div>
<b>Summary of Financial Projections</b><br />
<br />
<i>What will you make, on what, and by when?</i><br />
Based on our estimates (below) using the pricing estimates from the Service/Product Line section on this plan, we believe we will gross:<br />
<ul>
<li>$xxxxx in our first month</li>
</ul>
<ul>
<li>$xxxxx in our first quarter</li>
</ul>
<ul>
<li>$xxxxx in our first six months</li>
</ul>
<ul>
<li>$xxxxx in our first year</li>
</ul>
<ul>
<li>$xxxxx in our first two years</li>
</ul>
<h4>
<span style="font-weight: normal;">Our projected net earnings would be:</span></h4>
<div>
<ul>
<li>$xxxxx in our first month</li>
</ul>
<ul>
<li>$xxxxx in our first quarter</li>
</ul>
<ul>
<li>$xxxxx in our first six months</li>
</ul>
<ul>
<li>$xxxxx in our first year</li>
</ul>
<ul>
<li>$xxxxx in our first two years</li>
</ul>
These income projections are a good faith estimate. See <a href="http://theplaygroundllc.blogspot.com/p/financial-projections-appendix.html" target="_blank">Financial Projections Appendix</a> for more details.<br />
<br />
<br /></div>
<h4>
</h4>
<h4>
Appendix</h4>
<i><br /></i> <i>See <a href="http://playgroundcda.blogspot.com/p/resources.html">Resources</a> for additional materials and background.</i><br />
<i><br /></i> <i><br /></i> <i><br /></i> <i><br /></i> <i><br /></i></div>
</div>
</div>
