---
title: 'Financial Projections Appendix'
date: '2018-03-18T08:43:00.0010000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'The Playground, LLC'
blogger_status: 'LIVE'
blogger_page_id: '4722514394454612880'
blogger_filename: '/p/financial-projections-appendix.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Playground, LLC/feed.atom'
---

<br />
Under Construction<br />
<br />
Financial Projections Appendix<br />
<br />
<br />
<br />
<h4>
<br />Estimates Based on the Following Assumptions:</h4>
The average family has xxx(#) of kids. We expect the average weekly customer to be one parent with two or more children. Full families will also come, but this would typically be on a weekend or time off. We expect that most of our business will be conducted Thursday through Sunday.<br />
<br />
<b>Entry:</b><br />
If one parent comes with their two youngest children while the older children are at school, that family would spend $xxxx.<br />
<br />
If one parent came with all xxx of their kids, that family would spend $xxxxx.<br />
<br />
If two parents came with all of their kids, that family would spend $xxxx.<br />
<br />
The average ticket price would&nbsp;be:&nbsp;$xxxx per family.<br />
<br />
The average attendees would be xxx adults and xxx kids on a weekday.<br />
<br />
The average attendees would be xxx adults and xxx kids on a weekend.<br />
<br />
<b>Food:</b><br />
If half of the attending families purchased two meals, the food revenue would be $xxxxxx.<br />
<br />
<b>Games:</b><br />
Games cost $25. We expect one-quarter of the families would spend $2-5 on games per visit.<br />
<br />
<b>Events:</b><br />
If&nbsp;xxxxx&nbsp;kids attend one event per month, and there are&nbsp;xxxx&nbsp;events, the total revenue from events would be $xxxxx.<br />
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<div>
<br /></div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />