---
title: 'Costs Projections Appendix'
date: '2018-03-18T08:40:00.0040000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'The Playground, LLC'
blogger_status: 'LIVE'
blogger_page_id: '709621924144063646'
blogger_filename: '/p/costs-projections-appendix.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Playground, LLC/feed.atom'
---

<br />
Under Construction<br />
<br />
<br />
Costs Projections Appendix<br />
<br />
<br />
<br />
<br />
<br />
<div>
<h4>
Building - Interior/Exterior</h4>
</div>
<div>
<ul>
<li>Building (Rent/Lease/Buy)</li>
<li>Parking Expansion/Labeling</li>
<li>Signage (Inside and Outside)</li>
<li>Remodel (Walls, Wiring, Plumbing, Paint)</li>
</ul>
<div>
<br /></div>
</div>
<div>
<h4>
Equipment - The Playground</h4>
</div>
<div>
<ul>
<li>Equipment, Playground(s): $xxxxxx</li>
<li>Equipment, Other (Example: games, nerf shooting range)</li>
</ul>
</div>
<div>
<br /></div>
<h4>
Equipment - The Food Court</h4>
<div>
<ul>
<li>Equipment, Kitchen (Stove, Refridgerator, PrepStations, Etc)</li>
<li>Three-Basin Sink</li>
<li>Handwashing Sink</li>
<li>Auxilliary Sink</li>
<li>Pizza Oven (countertop)</li>
<li>Grill - Flat</li>
<li>Fryer (countertop)</li>
<li>Workstations (three)</li>
<li>Refridgerator</li>
<li>Freezer</li>
<li>Cold Food Prep Station</li>
<li>Hood (to&nbsp;zoning&nbsp;ordinance)</li>
<li>Knives, Spatulas, Etc.</li>
</ul>
<div>
<br /></div>
</div>
<div>
<h4>
<b>Equipment - The Office</b></h4>
</div>
<div>
<ul>
<li>Equipment, Point of Sale (POS) System</li>
<li>Equipment, Office Computer</li>
<li>Equipment, Customer User Interface(s)</li>
</ul>
</div>
<div>
<br /></div>
<h4>
Business Costs</h4>
<div>
<ul>
<li>Ongoing Costs times three: $xxxxxx</li>
<li>Vendors</li>
<li>Food/Supplies</li>
<li>Office Supplies</li>
<li>Cleaning Supplies</li>
<li>Bathroom Supplies</li>
</ul>
</div>
<div>
<br /></div>
<div>
<br /></div>
<h4>
Government &amp; Memberships (Licenses/Permits/Fees/Membership Fees)</h4>
<div>
<ul>
<li>Secretary of State LLC Filing - $100.00</li>
</ul>
<ul>
<li>Kootenai County</li>
</ul>
<ul>
<li>City of Hayden/Coeur d'Alene</li>
</ul>
<ul>
<li>Chamber of Commerce Membership</li>
</ul>
<ul>
<li>Food Handling Permits</li>
</ul>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br /></div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />