---
title: 'Resources & Research Links'
date: '2018-02-23T07:19:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'The Playground, LLC'
blogger_status: 'LIVE'
blogger_page_id: '56965057521896389'
blogger_filename: '/p/resources.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Playground, LLC/feed.atom'
---

<h3>
The Playground, LLC, a Family Entertainment Center, a Place to Play</h3>
<div>
<br />
<br />
The following are quick links and links to research (AKA: Appendix in the business plan).</div>
<div>
<br /></div>
<h4>
</h4>
<h4>
Playground Equipment</h4>
<ul>
<li><a href="http://theplaygroundllc.blogspot.com/2018/02/playsmart-worlds-best-playgrounds.html" target="_blank">Research: PlaySmart Playground Equipment</a></li>
<li><a href="http://theplaygroundllc.blogspot.com/2018/02/lego-themed-play-and-displays.html" target="_blank">Research: Oversized Lego-Style Blocks</a></li>
</ul>
<ul>
<li><b>QuickLinks:</b></li>
<li><a href="http://www.playsmart.com/">PlaySmart: The World's Best Playgrounds</a></li>
<ul>
<li><a href="http://www.playsmart.com/index.php/results/">Equipment List</a></li>
<li>They offer <a href="http://www.playsmart.com/index.php/get-started/financing/">in-house financing</a>, even for limited credit.</li>
</ul>
</ul>
<blockquote class="tr_bq">
<i>Each playground is composed of individual <a href="http://www.playsmart.com/index.php/products/events/">Events </a>that allow children to play interactively with each other, and children benefit from a healthy dose of exercise as well!&nbsp;</i></blockquote>
<br />
<br />
<div>
<h4>
<b>&nbsp;Food Vendors /&nbsp; Kitchen Equipment</b></h4>
</div>
<div>
<ul>
<li><a href="http://theplaygroundllc.blogspot.com/2018/02/restaurant-equipment-research.html" target="_blank">Research: Food Vendors /&nbsp; Kitchen Equipment</a></li>
</ul>
<ul>
<li><b>QuickLinks:</b></li>
<ul>
<li><a href="http://www.fsafood.com/main/aboutus.aspx">Food Services of America (FSA)</a></li>
<li><a href="https://sysco.com/">Sysco Foods</a></li>
<ul>
<li>Christian Kearns, Culinary Consultant</li>
<li>kearns.christian@spk.sysco.com</li>
<li>208-777-6215&nbsp;</li>
</ul>
<li><a href="http://midwayrestaurantequipment.com/">Midway Restaurant Equipment &amp; Supply</a></li>
<ul>
<li>midwayrestaurantsupply@gmail.com</li>
</ul>
</ul>
</ul>
<div>
<br /></div>
<div>
<br /></div>
<h4>
</h4>
<h4>
</h4>
<h4>
Building the Building</h4>
</div>
<div>
<ul>
<li><a href="http://theplaygroundllc.blogspot.com/2018/02/business-entity-type-name-research.html" target="_blank">Research: Building the Building Buy vs Lease</a></li>
<li><a href="http://theplaygroundllc.blogspot.com/2018/02/building-building-permits-fees.html" target="_blank">Research: Building the Building: Permits, Fees, Compliance, and Codes</a></li>
</ul>
<ul>
<li><b>QuickLinks:</b></li>
<li><a href="http://www.steelmasterusa.com/" target="_blank">Steel Master Building Systems</a></li>
</ul>
</div>
<div>
Permits, Etc.<br />
<ul>
<li><a href="http://www.kcgov.us/departments/building/" target="_blank">Kootenai County Building Department</a>&nbsp;</li>
<li><a href="https://www.cdaid.org/building" target="_blank">City of Hayden Building Dept</a></li>
</ul>
See Also:<br />
<ul>
<li><a href="https://www.cdaid.org/building" target="_blank">City of Coeur d’Alene Building Dept</a></li>
<li><a href="http://www.postfallsidaho.org/departments/public-services/building/" target="_blank">City of Post Falls Building Dept</a></li>
<li><a href="http://www.rathdrum.org/building" target="_blank">City of Rathdrum Building Dept</a></li>
</ul>
<br />
<br />
<br />
<h4>
Funding the Business</h4>
<ul>
<li><a href="http://theplaygroundllc.blogspot.com/2018/02/funding-business.html" target="_blank">Research: Funding the Business</a></li>
</ul>
<ul>
<li><b>QuickLinks:</b></li>
<li><a href="https://www.gofundme.com/" target="_blank">GoFundMe</a></li>
<ul>
<li><a href="https://www.gofundme.com/theplaygroundllc">https://www.gofundme.com/theplaygroundllc</a></li>
<ul></ul>
</ul>
<li><a href="https://gogetfunding.com/" target="_blank">GoGetFunding</a></li>
<ul>
<li><a href="https://gogetfunding.com/the-playground-llc/">https://gogetfunding.com/the-playground-llc/</a></li>
</ul>
</ul>
<br />
<br /></div>
<div>
<div>
<h4>
Employer/Employee Research</h4>
</div>
<div>
<ul>
<li><a href="http://theplaygroundllc.blogspot.com/2018/02/employeremployee-research.html" target="_blank">Research: Employer/Employee Research</a></li>
</ul>
<ul>
<li><b>QuickLinks:</b></li>
<li>TBD...</li>
</ul>
<div>
<br />
<br /></div>
</div>
</div>
<div>
<h4>
Entity Filing - Idaho Secretary of State</h4>
<ul>
<li><a href="http://theplaygroundllc.blogspot.com/2018/02/business-entity-type-name-research.html" target="_blank">Research: Business Entity Type &amp; Name Research</a></li>
</ul>
<ul>
<li><b>QuickLinks:</b></li>
<li><a href="https://www.accessidaho.org/public/sos/corp/search.html">Idaho SOS - Entity Search</a></li>
</ul>
<ul>
<li><a href="https://sos.idaho.gov/general/general.html">Idaho Secretary of State Contact Information</a>:<br />Business Entities (Corporations, LLCs, ABNs, etc.)<br />(208) 334-2301<br />(208) 334-2080<br />business@sos.idaho.gov<br /><br />Business Forms &amp; Fees Index<br /><ul>
<li><a href="https://sos.idaho.gov/corp/abn_form.html">Assumed Business Name (ABN)</a></li>
<li><a href="https://sos.idaho.gov/corp/llc_form.html">Limited Liability Company</a></li>
<ul>
<li><a href="https://sos.idaho.gov/corp/2015/LLC%20Cert%20org%202015%20FILL.pdf">Certificate of Organization Limited Liability Company</a>&nbsp;$100.00</li>
<li><a href="https://sos.idaho.gov/corp/2015/LLC%20Amend%202015%20FILL.pdf">Amendment to Certificate of Organization of Limited Liability Company</a>&nbsp;$30.00</li>
<li>Filing an Annual Report No Fee</li>
<li><a href="https://sos.idaho.gov/corp/2015/changeRA_RO2015%20Fillable.pdf">Statement of Change of Registered Office or Registered Agent, or both</a>&nbsp;No Fee</li>
<li><a href="https://sos.idaho.gov/corp/acro4/change_bus_address.pdf">Statement of Change of Business Mailing Address</a>&nbsp;No Fee</li>
</ul>
</ul>
<div>
<b><br /></b></div>
<div>
On-Line Services<br />
<ul>
<li><a href="https://sos.idaho.gov/corpar/Default.aspx">File your Annual Report</a></li>
<li><a href="https://www.accessidaho.org/public/sos/corp/search.html">Business Records Search</a></li>
</ul>
</div>
</li>
</ul>
</div>
<div>
<br />
<br /></div>
<h4>
</h4>
<h4>
Small Business Resources</h4>
<ul>
<li><b>QuickLinks:</b></li>
<li><a href="https://www.sba.gov/business-guide">SBA.Gov (Small Business Startup)</a></li>
<li><a href="https://www.sba.gov/business-guide/plan/write-your-business-plan-template">SBA (Business Plan Info)</a></li>
<li><a href="http://www.pacni.org/">Panhandle Area Council (PAC)</a> (Small Business Advising for North Idaho)&nbsp;</li>
<li><a href="https://www.nolo.com/legal-encyclopedia/local-start-up-requirements-small-business-30068.html">Local Start-Up Requirements for Small Businesses</a></li>
<li><a href="http://www.cdaedc.org/index.php/site/why">CDA Economic Development Corporation (EDC)</a></li>
<ul>
<li>Identifying and locating potential sites, in partnership with our local commercial brokers and building/property owners; and gathering detailed site and building information</li>
<li>Providing assistance in facilitating the permitting processes on both the local and state level</li>
</ul>
</ul>
<br />
<br />
<br />
<br />