---
title: 'Events & Meetings'
date: '2018-03-05T05:30:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'The Playground, LLC'
blogger_status: 'LIVE'
blogger_page_id: '4270866577128618620'
blogger_filename: '/p/events.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Playground, LLC/feed.atom'
---

In addition to the playground being open normal business hours to the general puclic, we plan to use the facility to host a range of special community events. Some of the events will be after hours and some of these events will be ways to give back to the local community.<br />
<br />
<ul>
<li>Parties &amp; Party Rooms</li>
<li>Pokemon Nights</li>
<li>Paint Classes (for kids and adults)</li>
<li>Corporate Events</li>
<li>Meeting Rooms</li>
</ul>
<br />
<br />
<div style="text-align: center;">
***</div>
<br />
<b>Parties &amp; Party Rooms</b><br />
<br />
Birthday Parties will not shut down The Playground to the normal use and public. Parties can be scheduled during normal business&nbsp;hours and will be assigned to the use of a party room. In some cases, after-hours parties can be arranged at an additional cost.<br />
<br />
<b>Pokemon Nights</b><br />
<br />
We will use the rooms to host Pokemon get-togethers and official Pokemon Tournaments. One of the party rooms will be Pokemon Themed.<br />
<br />
<b>Paint Classes (for kids and adults)</b><br />
<br />
After-hours, generally, we will host Paint Classes for a cost that includes paint and play.<br />
<br />
<b>Kids Paint Nights </b>will include a kid-friendly project followed by a play time.<br />
<br />
<b>Adult Paint Nights</b> will include the use of the Paint Room and instructor-led class, while you can bring the kids and let them play just outside (within eye/earshot). Kids are free to come and go from the Paint Room, parents don't need to hire a babysitter just to have some "me time".<br />
<br />
<br />
<b>Teen Nights &amp; Young Adult Nights</b><br />
<br />
Too cool to play with the small kids? Come to a night dedicated just to you. Only 13 and above are allowed entrance on Teen Nights, where the young adults can run, jump, climb through our structures (big enough for anyone 3-103).<br />
<br />
<br />
<b>Corporate Event Nights</b><br />
<br />
Who said that playtime is just for kids? The Playground offers P<a href="http://www.playsmart.com/index.php/media/album/">laySmart Playground Equipment</a> that was designed to accommodate kids of any age or size. Bring the CEO, take your shoes off, and go run around like a hamster!<br />
<br />
Since the Corporate Events Nights are scheduled "after-hours", you won't have to worry about running over any smaller kids, just the ones you hired!<br />
<br />
You'll also have use of the Meeting Room, which features a projector wall and sound system to use for your presentations. The Black-Board wall allows you to write directly onto the wall during your meeting. Take a few pictures of it and erase when you're done to keep your corporate secrets to yourself.<br />
<br />
<br />
<b>Meeting Rooms</b><br />
<br />
In addition to the uses already described, we foresee the facilities being available to be used by local churches, bible studies, and small groups before or after hours. In some cases, the facility may be offered for special church or non-profit events at a reduced cost (as the owners feel led to participate).<br />
<br />
<br />