---
title: 'Vision and Values'
date: '2023-09-24T19:54:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'The Freedom Center'
blogger_status: 'LIVE'
blogger_page_id: '8585214048702648637'
blogger_filename: '/p/eleutheria-vision-and-values.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Freedom Center/feed.atom'
---

<h2 style="text-align: left;">The Freedom Center: Vision and Values</h2><p><br /></p><h4 style="text-align: left;">Vision: The Freedom Center: Healing the heart while training the mind.</h4><div><br /></div><h4 style="text-align: left;">Theme: Eleutheria (ἐλευθερία): For Freedom, The Anointing of the Anointed One Has Set Us Free</h4><div><br /></div><h4 style="text-align: left;">Mission: The Best of Biblical Studies and Modern Psychology&nbsp;</h4><p></p><blockquote><i>The Freedom Center is dedicated to harmonizing spiritual and psychological well-being, grounded in the transformative concept of 'Eleutheria'—the liberation granted through a timeless tradition of divine deliverance. We are committed to providing tools and resources rooted in the most reputable and up-to-date academic biblical studies and scholarly psychological research for achieving complete wellness.</i></blockquote><p></p><h4 style="text-align: left;">Core Values:</h4><p></p><ul style="text-align: left;"><li><b>Integrity</b>: Applying rigorously vetted scholarly research and psychological studies.</li><li><b>Compassion</b>: Providing tools and resources that are deeply rooted in empathy and understanding.</li><li><b>Freedom</b>: Focusing on liberation from mental and spiritual burdens, echoing the core message of Galatians 5:1.</li></ul><p></p><h4 style="text-align: left;">Content Pillars:</h4><p></p><ul style="text-align: left;"><li><b>Academic Insight</b>: Articles, webinars, and discussions rooted in academic biblical scholarship and modern psychology.</li><li><b>Theology of Freedom</b>: In-depth exploration of the scriptural foundations of "Eleutheria," leveraging academic biblical studies to illuminate the various dimensions of freedom in both the Ancient Near Eastern contexts of the Hebrew Bible, and the Second Temple Judaism within a Roman World contexts of the B'rit Chadashah (New Testaments).</li><li><b>Practical Wisdom</b>: How-to guides and toolkits, e.g., mindful prayer techniques, cognitive behavioral therapy, and their intersections.</li><li><b>Personal Stories</b>: Testimonials and case studies demonstrating the effective blending of spiritual and mental approaches to well-being.</li><li><b>Community</b>: Forums or discussion panels for sharing experiences and seeking guidance.</li></ul><p></p><p><br /></p><h4 style="text-align: left;">Diving into the biblical basis for <b><i>Eleutheria</i></b></h4><p style="text-align: left;">"Eleutheria" (ἐλευθερία) is a Greek term that translates to "freedom" or "liberty." In ancient Greek philosophy and political thought, it was often used to describe the state of being free from slavery or oppression. In a broader sense, it can also refer to the freedom of thought, speech, and action.</p><p>In the context of biblical studies, the term appears in the New Testament, particularly in Pauline writings, to describe the freedom that believers have in Christ. This freedom is often understood in various dimensions: freedom from sin, freedom from the Law, and freedom to serve others in love.</p><h4 style="text-align: left;">Diving deeper: Freedom vs Exile</h4><p>Embedded within the historical pages of the Hebrew Bible, the theme of exile stands as a metaphor for death, and freedom signifies a form of rebirth. From Adam and Eve’s exile from Eden to Israel's Babylonian exile, the narrative arcs towards redemption and return.&nbsp;</p><p>The Northern Kingdom of Israel (10 of the 12 tribes) was exiled into Assyria in 722 B.C., never to return in any definitive way to this day. They are often known as the "Lost Tribes" due to this exile.&nbsp;</p><p>The Southern Kingdom of Judah was exiled to Babylon in 586 BCE. While they were later allowed to return to their homeland and rebuild the temple (~539 BCE), the mood was still one of exile. Much like a home-prison sentence, they were at home but not self-ruled. Some scholars believe that much of the Hebrew Bible took its final form during the exile and shortly after, reflecting on their experiences as exiles. Thus, the stories of Genesis 1-11 reflect this theme of Exile-as-Death, and serve as a prelude to the rest of the Hebrew Bible narrative and reflection.</p><p>Throughout the Second Temple period (586 BC-AD 70), Jewish authors continued to write and discuss these themes of exile, some of these themes find their way into the Hebrew Bible's final texts, while others are explored in other second temple Jewish literature, including those books included in the Greek translation of the Hebrew Bible, known as the Septuagint.</p><p>As these ideas evolved in the minds and hearts of first century Jewish residents of Roman Palestine (the Roman's name for the region including Israel), they came to infuse the texts of the Jewish New Testament authors, specifically in the teachings of Yeshua HaMashiach (Iesus ha-Christos; Jesus the Anointed One; or as some have nicknamed him: Oily Josh).</p><p>Yeshua is perceived by these first century Jewish authors as pioneering a new Exodus, transcending physical, spiritual, and psychological limitations, and enabling a novel return from exile.&nbsp;</p><p>Contrary to many modern voices, influenced more by westernized Platonic thought and Medieval Theologians than the Jewish authors of the biblical texts, Yeshua was not bringing about a "spiritual" non-material Kingdom only.&nbsp;</p><p>Rather, his first disciples learned first-hand that the Kingdom of Jesus, while not of this world, was very much an active part in this world. His Kingdom would be typified by a sharing of resources, dedication to the meditative study of Torah, and the application of Torah wisdom in actively loving Yahweh's imagers (humankind).&nbsp;</p><p>This is seen, for example, in Yeshua's noting that those who would be his would be known by their love for one another, clothing the naked, feeding the hungry, and visiting those in distress. Acts 2 shows this new community, filled by Yeshua's breath (The Holy Spirit), having no lack because they shared their resources openly (spiritually, physically, gastronomically &lt;food&gt;, and financially).</p><p>Yeshua demonstrated to his followers and fellow Rabbis that meditating on the Torah, Prophets, and Writings (TaNaKh) should result in a life of freedom for Yahweh's people.</p><p>In its Greek origin, the term Eleutheria embodies freedom from slavery and oppression; in the Hebraic and New Testament contexts, it takes on additional dimensions. Here, freedom evolves into a comprehensive state of well-being, harmonizing one’s relationship with both Yahweh and Yahweh's people, and by extension of these, with one's self; as articulated in Galatians 5:1 and echoed in Isaiah 10:27 and Romans 12:2.</p><p></p><blockquote><p><i>“For freedom Christ has set us free. Stand firm, therefore, and do not be subject again to a yoke of slavery.” (Galatians 5:1, LEB)</i></p><div><i>“And this shall happen: on that day, he will remove his burden from your shoulder and his yoke from your neck, and a yoke will be destroyed because of fat.” (Isaiah 10:27, LEB)</i></div><p><i>“And do not be conformed to this age, but be transformed by the renewal of your mind, so that you may approve what is the good and well-pleasing and perfect will of God.” (Romans 12:2, LEB)</i></p></blockquote><p></p><p>Our foundational principle, 'Eleutheria,' stems from this intricate blend of Greek and Hebrew thinking.&nbsp;</p><p>This is the "freedom" that The Freedom Center aims to explore and enable: a multi-dimensional liberation grounded in time-honored tradition of meditating on the Torah, Prophets, and Writings (including the Second Writings, aka New Testament) and adding to that the most current scholarly insights into a healthy mind, healthy spirituality, and healthy community.</p><p><i>*&nbsp;<a href="https://biblehub.com/greek/1657.htm" target="_blank">ἐλευθερία</a>&nbsp;from Bible Hub</i></p>