---
title: 'About'
date: '2012-01-02T03:07:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Forefront Entertainment'
blogger_status: 'LIVE'
blogger_page_id: '4979874040241624878'
blogger_filename: '/p/about.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Forefront Entertainment/feed.atom'
---

<br />
<div style="color: #; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="font-weight: bold; line-height: 1.4;">Forefront Entertainment;</strong>&nbsp;<strong style="font-weight: bold; line-height: 1.4;">Studios and Productions</strong></div>
<div style="color: #; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="font-weight: bold; line-height: 1.4;">Exposing the&nbsp;Possibilities!</strong></div>
<div style="color: #; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="font-weight: bold; line-height: 1.4;">FESP</strong>&nbsp;is about taking the cutting edge, the forefront, the leading role in all forms of the entertainment industry! Movies, Music, Concerts, Theatre, Productions of all types, shapes, and sizes are at their best when they are pushing the envelope. The best entertainment of our time has been from sources that did more than anyone else was doing, more than others thought could be done. We do more than others think is possible. We dream on a higher level than others can dream. We create with our creator pushing aside the darkness to show that He CAN and He WILL!</div>
<div style="color: #; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
Inspired by those who came before like, Apple, Lucas Films, Pixar, Google, and others... we see a bright future filled with things people haven't seen or imagined yet. We are a private owned company that puts God first in everything!</div>
<div style="color: #; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="font-weight: bold; line-height: 1.4;">What is Forefront:&nbsp;</strong></div>
<div style="color: #; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<a data-mce-href="http://thesaurus.com/browse/forefront" href="http://thesaurus.com/browse/forefront" style="color: #cd4517; line-height: 1.4;" target="_blank">Forefront</a>:&nbsp;Beginning, Center, Cutting Edge, Focus, Front, Lead, Leading Edge, Limelight, Spearhead, State of the Art...</div>
<div style="color: #; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<a data-mce-href="http://1828.mshaffer.com/d/search/word,forefront" href="http://1828.mshaffer.com/d/search/word,forefront" style="color: #cd4517; line-height: 1.4;" target="_blank">Websters 1828 - Forefront</a>: The foremost part, the front of the battle. It is the part where the contest is most warm and where the soldier is most exposed! (2 Sam 11:15)</div>
<div style="color: #; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<a data-mce-href="http://mw2.merriam-webster.com/dictionary/cutting%20edge" href="http://mw2.merriam-webster.com/dictionary/cutting%20edge" style="color: #cd4517; line-height: 1.4;" target="_blank">Cutting Edge</a>: A sharp effect or quality. The Foremost part of place; Vangaurd</div>
<div style="color: #; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<strong style="font-weight: bold; line-height: 1.4;">Our founding&nbsp;scriptures:</strong></div>
<div style="color: #; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=ephesians+3:20&amp;t=kjv" href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=ephesians+3:20&amp;t=kjv" style="color: #cd4517; line-height: 1.4;" target="_blank"><strong style="color: #; font-weight: bold; line-height: 1.4;">Ephesians 3:20</strong></a></div>
<div style="color: #; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
20&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1161" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1161" style="color: #cd4517; line-height: 1.4;">Now</a>&nbsp;unto him that is&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1410" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1410" style="color: #cd4517; line-height: 1.4;">able</a>&nbsp;to&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=4160" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=4160" style="color: #cd4517; line-height: 1.4;">do</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=5228" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=5228" style="color: #cd4517; line-height: 1.4;">exceeding</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=4053" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=4053" style="color: #cd4517; line-height: 1.4;">abundantly</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=5228" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=5228" style="color: #cd4517; line-height: 1.4;">above</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=3956" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=3956" style="color: #cd4517; line-height: 1.4;">all</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=3739" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=3739" style="color: #cd4517; line-height: 1.4;">that</a>&nbsp;we&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=154" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=154" style="color: #cd4517; line-height: 1.4;">ask</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2228" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2228" style="color: #cd4517; line-height: 1.4;">or</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=3539" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=3539" style="color: #cd4517; line-height: 1.4;">think</a>&nbsp;, according&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2596" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2596" style="color: #cd4517; line-height: 1.4;">to</a>&nbsp;the&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1411" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1411" style="color: #cd4517; line-height: 1.4;">power</a>&nbsp;that&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1754" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1754" style="color: #cd4517; line-height: 1.4;">worketh</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1722" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1722" style="color: #cd4517; line-height: 1.4;">in</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2254" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2254" style="color: #cd4517; line-height: 1.4;">us</a>...</div>
<div style="color: #; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=1-peter+2:9&amp;t=kjv" href="http://www.biblestudytools.com/interlinear-bible/passage.aspx?q=1-peter+2:9&amp;t=kjv" style="color: #cd4517; line-height: 1.4;" target="_blank"><strong style="color: #; font-weight: bold; line-height: 1.4;">1 Peter 2:9</strong></a></div>
<div style="color: #; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
9&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1161" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1161" style="color: #cd4517; line-height: 1.4;">But</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=5210" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=5210" style="color: #cd4517; line-height: 1.4;">ye</a>&nbsp;are a&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1588" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1588" style="color: #cd4517; line-height: 1.4;">chosen</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1085" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1085" style="color: #cd4517; line-height: 1.4;">generation,</a>&nbsp;a&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=934" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=934" style="color: #cd4517; line-height: 1.4;">royal</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2406" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2406" style="color: #cd4517; line-height: 1.4;">priesthood,</a>&nbsp;an&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=40" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=40" style="color: #cd4517; line-height: 1.4;">holy</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1484" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1484" style="color: #cd4517; line-height: 1.4;">nation,</a>&nbsp;a&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=4047" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=4047" style="color: #cd4517; line-height: 1.4;">peculiar</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2992" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2992" style="color: #cd4517; line-height: 1.4;">people;</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=3704" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=3704" style="color: #cd4517; line-height: 1.4;">that</a>&nbsp;ye should shew&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1804" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1804" style="color: #cd4517; line-height: 1.4;">forth</a>&nbsp;the&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=703" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=703" style="color: #cd4517; line-height: 1.4;">praises</a>&nbsp;of him who hath&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2564" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2564" style="color: #cd4517; line-height: 1.4;">called</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=5209" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=5209" style="color: #cd4517; line-height: 1.4;">you</a>&nbsp;out&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1537" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1537" style="color: #cd4517; line-height: 1.4;">of</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=4655" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=4655" style="color: #cd4517; line-height: 1.4;">darkness</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1519" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=1519" style="color: #cd4517; line-height: 1.4;">into</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=846" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=846" style="color: #cd4517; line-height: 1.4;">his</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2298" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=2298" style="color: #cd4517; line-height: 1.4;">marvellous</a>&nbsp;<a data-mce-href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=5457" href="http://www.biblestudytools.com/interlinear-bible/strongs.ashx?ll=g&amp;t=kjv&amp;sn=5457" style="color: #cd4517; line-height: 1.4;">light</a>...</div>
<div style="color: #; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<b>Contact us:</b></div>
<div style="color: #; font-family: Arial, 'Trebuchet MS', sans-serif; font-size: 13px; line-height: 18px; margin-bottom: 18px;">
<b>Forefront Entertainment&nbsp;</b><br />
<b>&nbsp;Address: PO Box 1001 Newark, TX 76071&nbsp;</b><br />
<b>&nbsp;Phone: (903) 345-5965&nbsp;</b><br />
<b>&nbsp;Email: DarrellGWolfe@gmail.com</b></div>