---
title: 'Home Sweet Home'
date: '2012-02-08T23:06:00.0010000+00:00'
draft: true
blogger_blog: 'The Life In Fort Worth Blog'
blogger_status: 'LIVE'
blogger_post_id: '3598104718910903526'
blogger_filename: '/2012/02/home-sweet-home.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Life In Fort Worth Blog/feed.atom'
categories:
  - 'Navigate'
  - 'Discover'
  - 'Enjoy'
---

<br />
<h1 style="font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 2.4em; font-weight: normal; line-height: 1.5em; margin: 0px 0px 20px;">
<strong>Home Sweet Home</strong></h1>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">
Weather your home is an apartment or a house you know that home is home. It may not be the forever place, the dream home, the place you want to retire... but there is something about sleeping in your own bed, waking up and doing what you want in your place. Single, Married, or Family... home is home.&nbsp;Travelers often tell me that the adventures they have are only meaningful in relation to getting home. There is something about getting into your own routine that makes home a great place to be.</div>
<h2 style="font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 1.8em; font-weight: normal; line-height: 1.5em; margin: 0px 0px 20px;">
<strong>Houses:</strong></h2>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">
There are a lot of home builders in the DFW area. In fact the home building trade here, although slower than it once was, is booming compared to other places. That's because people are running from other states to move here.&nbsp;<strong style="color: black;">The friendly atmosphere, the conservative tea party values, the stable housing market</strong>&nbsp;and low housing prices all make Texas a safe haven from the non sense outside. There are many great builders out here But I'd like to highlight a few.</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">
Houses in Texas are<strong style="color: black;">&nbsp;much less expensive to buy</strong>&nbsp;than many other states. As a first time home buyer I bought a 4 bedroom, 2 bath, 1,300 square foot house with a big back yard against a green belt, in the Sendera Ranch area from Lennar, for $119,000. There are areas in LA and Orange County California that would have cost me between $250,000 and $1,000,000 for the same house with half the land or no yard at all.</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">
Most houses in the DFW area range from $120,000 to $300,000 depending on size, location, and trimmings. A house for $300,000 here could easily be over a million in certain parts of&nbsp;California. For those looking to spend over a million there are few limitations to your hearts content here. You can have a nearly anything you want out here.</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">
One thing to note however:&nbsp;<strong style="color: black;">Property Tax is higher!</strong>&nbsp;Part of the reason for that Texas Properties didn't loose value as much here in Texas as other states is that they never went up as high or as fast as other states. Property taxes here are nearly double that of other states so the actual monthly payment for a $100,000 house is closer to a $200,000 house in other states. This is a vague generality but it get's the idea&nbsp;across.</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">
Some of my favorite home builders in the DFW area, the ones I have gone through, toured, enjoyed, and wanted to buy are:</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">
<br />
<ul>
<li><strong style="color: black;"><a data-mce-href="http://www.lennar.com/" href="http://www.lennar.com/" style="color: #743399;" target="_blank">Lennar</a></strong></li>
<li><strong style="color: black;"><a data-mce-href="http://dreeshomes15-px.rtrk.com/Dallas/" href="http://dreeshomes15-px.rtrk.com/Dallas/" style="color: #743399;" target="_blank">Drees</a></strong></li>
<li><strong style="color: black;"><a data-mce-href="http://www.khov.com/?ref=Google_Corporate&amp;s_kwcid=TC|13142|khovanian||S|e|7420583717&amp;gclid=CPa4-_r7z6sCFcoBQAodrG6XUg" href="http://www.khov.com/?ref=Google_Corporate&amp;s_kwcid=TC|13142|khovanian||S|e|7420583717&amp;gclid=CPa4-_r7z6sCFcoBQAodrG6XUg" style="color: #743399;" target="_blank">K Hovanian</a></strong></li>
<li>And for the person who has no budget restrictions and LOT's of imagination try Veranda:</li>
<ul>
<li><strong style="color: black;">&nbsp;<a data-mce-href="http://www.verandadesignerhomes.com/" href="http://www.verandadesignerhomes.com/" style="color: #743399;" target="_blank">Veranda Designer Homes</a></strong></li>
</ul>
</ul>
</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">
</div>
<h2 style="font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 1.8em; font-weight: normal; line-height: 1.5em; margin: 0px 0px 20px;">
<strong>Apartments:</strong></h2>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">
There are many great apartments in the DFW area. A comprehensive list can be found on&nbsp;<a data-mce-href="http://www.rent.com/account/myrent/view" href="http://www.rent.com/account/myrent/view" style="color: #743399;" target="_blank">Rent.com</a>. I find that generally apartments run from $500/month to $2000/month depending on where you want to live and how close to the city, what quality the apartments are. You should be able to find a very decent two bedroom apartment for $900-$1,200. If you find it for less than $700 you probably don't want to live there, unless you are used to living in places that are less than clean. Those prices are usually found in the inner city areas and bring a lot of baggage with them. I didn't really end up paying less here is Texas for my apartment as much as I got more for what I paid.&nbsp;</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">
One apartment building I can vouch for is&nbsp;<a data-mce-href="http://www.copperridgeapthomes.com/" href="http://www.copperridgeapthomes.com/" style="color: #743399;" target="_blank">Copper Ridge Apartments</a>&nbsp;in&nbsp;<a data-mce-href="http://roanoketexas.com/" href="http://roanoketexas.com/" style="color: #743399;" target="_blank">Roanoke Texas</a>. The apartments are well managed and cleanly kept. The pool is a great place to hand out and there are two amazing bbq grills at the pool side. If you rent there tell them you heard about them from this website and Darrell Wolfe sent you. There are great open floor plans, balconies, pool, and a really neat park nearby with a water feature for the kids in summer. Also nearby is some of the most unique dining, including<a data-mce-href="http://txliving.wordpress.com/2011/09/05/twisted-root-burger-company/" href="http://txliving.wordpress.com/2011/09/05/twisted-root-burger-company/" style="color: #743399;" target="_blank">&nbsp;Twisted Root Burger</a>, and a paid entry water park called&nbsp;<a data-mce-href="http://hfalls.com/" href="http://hfalls.com/" style="color: #743399;" target="_blank">Hawaiian&nbsp;Falls</a>.</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">
I'm sure there is more information I could put here. But this should get you going for now.</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; margin-bottom: 24px;">
Thank you for your time, Darrell G. Wolfe</div>
