---
title: 'Businesses'
date: '2012-02-08T23:05:00.0010000+00:00'
draft: true
blogger_blog: 'The Life In Fort Worth Blog'
blogger_status: 'LIVE'
blogger_post_id: '230038750905837061'
blogger_filename: '/2012/02/businesses.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Life In Fort Worth Blog/feed.atom'
categories:
  - 'Navigate'
---

<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; margin-bottom: 24px;">
<strong style="color: black;">Business in Texas is really quite simple.</strong>&nbsp;Certain fields of work require&nbsp;licensing&nbsp;in any state, such as restaurants, medical, etc... However the process of starting a business in most cases is quite simple.</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; margin-bottom: 24px;">
<strong style="color: black;">Filing your Business:</strong></div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; margin-bottom: 24px;">
Filing for an<strong style="color: black;">&nbsp;LLC or Corporation is $300</strong>&nbsp;from the<a data-mce-href="http://www.sos.state.tx.us/corp/generalfaqs.shtml" href="http://www.sos.state.tx.us/corp/generalfaqs.shtml" style="color: #743399;" target="_blank">&nbsp;Texas Secretary of State</a>&nbsp;(SOS). These formations are&nbsp;<strong style="color: black;">good forever</strong>, as long as you maintain your structure. If the structure changes it requires re-filing/amending your file. If two people start an LLC together and one leaves, you must re-file. Filing a DBA (Doing Business As), also known as an Assumed Name Certificate is done at the county level. Typically you MUST file a DBA with EACH county you will conduct business in. For Online sales just register where you live. Most of the time registering the<strong style="color: black;">&nbsp;DBA is between $10-25 per certificate</strong>. You only file one certificate per name that you use and the registration is&nbsp;<strong style="color: black;">good for 10 years</strong>. Filing is done at the county clerks office.</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; margin-bottom: 24px;">
<strong style="color: black;">Counties in Texas</strong>&nbsp;can be a bit more confusing. There are about 5-6 major counties in southern&nbsp;California, there are 100's in&nbsp;Texas.</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; margin-bottom: 24px;">
<strong style="color: black;">Common counties in DFW are</strong>:</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; margin-bottom: 24px;">
<a data-mce-href="http://www.co.wise.tx.us/" href="http://www.co.wise.tx.us/" style="color: #743399;" target="_blank">Wise</a>,&nbsp;<a data-mce-href="http://dentoncounty.com/dept/main.asp?Dept=17&amp;Link=50" href="http://dentoncounty.com/dept/main.asp?Dept=17&amp;Link=50" style="color: #743399;" target="_blank">Denton</a>,&nbsp;<a data-mce-href="http://www.co.collin.tx.us/county_clerk/index.jsp" href="http://www.co.collin.tx.us/county_clerk/index.jsp" style="color: #743399;" target="_blank">Collin</a>,&nbsp;<a data-mce-href="http://www.co.parker.tx.us/ips/cms/countyoffices/countyClerk.html" href="http://www.co.parker.tx.us/ips/cms/countyoffices/countyClerk.html" style="color: #743399;" target="_blank">Parker</a>,&nbsp;<a data-mce-href="http://www.tarrantcounty.com/ecountyclerk/cwp/view.asp?A=735&amp;Q=435718" href="http://www.tarrantcounty.com/ecountyclerk/cwp/view.asp?A=735&amp;Q=435718" style="color: #743399;" target="_blank">Tarrant (Home of Fort Worth)</a>,&nbsp;<a data-mce-href="http://www.dallascounty.org/department/countyclerk/roam.php" href="http://www.dallascounty.org/department/countyclerk/roam.php" style="color: #743399;" target="_blank">Dallas</a></div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; margin-bottom: 24px;">
Most often if you live near Fort Worth you will use&nbsp;Tarrant&nbsp;County or Denton County, if you live in Dallas you will use Dallas county. There are MANY counties out here though. You should look at a&nbsp;<a data-mce-href="http://www.censusfinder.com/maptx.htm" href="http://www.censusfinder.com/maptx.htm" style="color: #743399;" target="_blank">Texas county map</a>&nbsp;just to be sure.</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; margin-bottom: 24px;">
<strong style="color: black;">Business Banking:</strong></div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; margin-bottom: 24px;">
If you are going to do any real business where you get paid and you plan on&nbsp;<strong style="color: black;">making more than $500-$1,000 a year</strong>, you will most likely want to open a business account. Many banks offer business accounts for their customers. Wells Fargo, Chase, and Capitol One are all larger banks located in the DFW Texas area. Many of these&nbsp;<strong style="color: black;">accounts can be free, if you have to pay for it keep looking</strong>. I suggest comparing at least these three banks against one another for their benefits and&nbsp;<strong style="color: black;">meeting with a local banker</strong>&nbsp;about them. Doing your research online doesn't always tell you everything there is to know about the&nbsp;<strong style="color: black;">intricacies&nbsp;</strong>of the accounts and the&nbsp;<strong style="color: black;">benefits</strong>&nbsp;they come with. If you can't make it in person, at least&nbsp;<strong style="color: black;">call a sales banker</strong>&nbsp;by phone for more information.</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; margin-bottom: 24px;">
Just a helpful note, if you are going in person&nbsp;<strong style="color: black;">make an appointment</strong>&nbsp;to ensure the business banker is there for you. If you are shopping by phone,&nbsp;<strong style="color: black;">call the 800# for sales</strong>. Branches aren't set up to go into detail by phone.<strong style="color: black;">&nbsp;You will need to decide if you are using an EIN or your social for the business account</strong>. It can be VERY helpful to use an EIN from the&nbsp;beginning, even if you only file the business taxes on your return. This keeps things&nbsp;separate&nbsp;and eventually you can continue that&nbsp;separation&nbsp;as the business expands.</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; margin-bottom: 24px;">
<strong style="color: black;">Tax ID:</strong></div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; margin-bottom: 24px;">
An&nbsp;<strong style="color: black;">EIN</strong>&nbsp;(Employer Identification Number) is a<strong style="color: black;">&nbsp;Federal Tax ID</strong>, just like a social for your business. You can apply for an EIN online for free at&nbsp;<a data-mce-href="https://sa1.www4.irs.gov/modiein/individual/index.jsp" href="https://sa1.www4.irs.gov/modiein/individual/index.jsp" style="color: #743399;" target="_blank">www.irs.gov</a>.</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; margin-bottom: 24px;">
<strong style="color: black;">State Tax ID</strong>. There is also a&nbsp;<strong style="color: black;"><a data-mce-href="http://www.window.state.tx.us/taxinfo/sales/new_business.html" href="http://www.window.state.tx.us/taxinfo/sales/new_business.html" style="color: #743399;" target="_blank">Texas Sales Tax ID</a></strong>. In some cases you must also obtain this tax ID as well.</div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; margin-bottom: 24px;">
<strong style="color: black;">Warning</strong>: I have found that you can apply to your hearts content for EIN #'s all day long and never use them. However if you apply for a Texas Sales Tax ID and don't use it you must STILL report quarterly to the IRS or cancel the ID. I once applied just to see how easy it was and the state sent me a tax bill for $1,000 based on&nbsp;their&nbsp;best guess of the sales I might have made. My wife informed them I didn't sell anything and we never even ended up starting up the business and they waived it... but had she not called we might have been in big trouble for ignoring it.&nbsp;<strong style="color: black;">Only apply for a state tax ID if you are going to use it!</strong></div>
<div style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; margin-bottom: 24px;">
Hopefully this article helps some.</div>
<h3 style="font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 1.4em; font-weight: normal; line-height: 1.5em; margin: 0px 0px 20px;">
<strong>BUSINESS Links</strong></h3>
<ul style="color: #333333; font-family: Helvetica, Arial, 'Lucida Grande', Verdana, sans-serif; font-size: 16px; line-height: 19px; list-style-image: initial; list-style-position: initial; margin: 0px 0px 24px 0em; padding: 0px 0px 0px 1em;">
<li><a data-mce-href="http://factfinder.census.gov/servlet/SAFFFacts?_event=Search&amp;geo_id=&amp;_geoContext=&amp;_street=&amp;_county=76052&amp;_cityTown=76052&amp;_state=&amp;_zip=76052&amp;_lang=en&amp;_sse=on&amp;pctxt=fph&amp;pgsl=010&amp;show_2003_tab=&amp;#038" href="http://factfinder.census.gov/servlet/SAFFFacts?_event=Search&amp;geo_id=&amp;_geoContext=&amp;_street=&amp;_county=76052&amp;_cityTown=76052&amp;_state=&amp;_zip=76052&amp;_lang=en&amp;_sse=on&amp;pctxt=fph&amp;pgsl=010&amp;show_2003_tab=&amp;#038" style="color: #743399;">Census Data By Zip</a></li>
<li><a data-mce-href="http://www.dallascounty.org/department/countyclerk/roam.php" href="http://www.dallascounty.org/department/countyclerk/roam.php" style="color: #743399;" target="_blank" title="DBA/ASN filling and Search">Dallas County Clerk</a></li>
<li><a data-mce-href="http://dentoncounty.com/dept/main.asp?Dept=17&amp;Link=50" href="http://dentoncounty.com/dept/main.asp?Dept=17&amp;Link=50" style="color: #743399;" target="_blank" title="DBA/ASN filling and Search">Denton County Clerk</a></li>
<li><a data-mce-href="http://www.sba.gov/category/navigation-structure/counseling-training/online-small-business-training" href="http://www.sba.gov/category/navigation-structure/counseling-training/online-small-business-training" style="color: #743399;" target="_blank">SBA Online Training</a></li>
<li><a data-mce-href="http://www.sos.state.tx.us/corp/generalfaqs.shtml" href="http://www.sos.state.tx.us/corp/generalfaqs.shtml" style="color: #743399;" target="_blank" title="All things you need to know about business in Texas. ">Secretary of State</a></li>
<li><a data-mce-href="http://www.tarrantcounty.com/ecountyclerk/cwp/view.asp?A=735&amp;Q=435718" href="http://www.tarrantcounty.com/ecountyclerk/cwp/view.asp?A=735&amp;Q=435718" style="color: #743399;" target="_blank" title="DBA/ASN filling and Search">Tarrant County Clerk</a></li>
<li><a data-mce-href="https://ourcpa.cpa.state.tx.us/coa/Index.html" href="https://ourcpa.cpa.state.tx.us/coa/Index.html" style="color: #743399;" target="_blank" title="Online LLC and Corporation Name and Tax Status Search">Texas Comptroller</a></li>
<li><a data-mce-href="http://www.co.travis.tx.us/county_clerk/dba.asp" href="http://www.co.travis.tx.us/county_clerk/dba.asp" style="color: #743399;" target="_blank" title="DBA/ASN filling and Search">Travis County Clerk</a></li>
<li><a data-mce-href="http://www.ers.usda.gov/StateFacts/TX.htm" href="http://www.ers.usda.gov/StateFacts/TX.htm" style="color: #743399;" target="_blank" title="Texas vital statistics and economic research">USDA Texas State Statistics</a></li>
<li><a data-mce-href="http://www.co.wise.tx.us/" href="http://www.co.wise.tx.us/" style="color: #743399;" target="_blank" title="DBA/ASN filling and Search">Wise County Clerk</a></li>
</ul>
