---
title: 'Priceline (Internet Travel Service)'
date: '2015-06-21T12:59:00.0000000+00:00'
draft: true
blogger_blog: 'The Life In Fort Worth Blog'
blogger_status: 'LIVE'
blogger_post_id: '3991009960664506782'
blogger_filename: '/2015/06/priceline-internet-travel-service.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Life In Fort Worth Blog/feed.atom'
categories:
  - 'Enjoy'
---

<h3>
<a href="http://www.priceline.com/help/#/" target="_blank">Priceline </a>(Internet Travel Service)</h3>
<div>
<br />
Can be written at:<br />
<h4>
Executive Services<br />Priceline.com LLC<br />800 Connecticut Ave.<br />Norwalk, CT 06854</h4>
<br />
Welll... I dedicated to myself that I would give the good the bad and the other. Let me tell you about Priceline. First of all, I have a general principal I have found to be overwhelmingly true. The more a company spends on advertising, the worse they customer service must be. If the only place I've heard of you is commercials... it's because my friends haven't used you and raved about you. This one is no exception. Sorry <a href="https://www.youtube.com/watch?v=wQrDmQ6yGss" target="_blank">William Shatner,</a> this company is a bust.<br />
<br />
<br />
My mom comes into town. She is leaving tomorrow for Chicago, and she booked a hotel there through Priceline.<br />
<br />
The price of the hotel is the same as it would have been if she booked it through the hotel directly ( she uses this hotel often). Plans changed, she decided to not stay in Chicago, but drive directly down to Pontiac, IL instead.<br />
<br />
She called well over 24 hours in advance (usual industry standard) to cancel the hotel reservation. She was informed that the reservation was booked through a web provider so they couldn't cancel it, she'd have to call them. But they couldn't even see which web provider booked it.<br />
<br />
She went through emails and found out it was Priceline. She called them to get told that they had a no cancellation policy, and they would be charging a $100 cancellation fee. Escalated twice, still same answer.<br />
<br />
<div>
<ul>
<li>That will be disputed with the Credit Card Company.&nbsp;</li>
<li>This entire family will never use Priceline to book anything.</li>
<li>I found the Yelp entry for <a href="http://www.yelp.com/biz/priceline-fair-oaks" target="_blank">Priceline </a>(74 reviews with a ONE star rating... that's bad averages).&nbsp;</li>
</ul>
</div>
<br />
<h4>
Recommendation:&nbsp;</h4>
<br />
DO NOT use Priceline. In fact, do not book anything through any of these services. Develop a relationship with a favorite (hotel, airline, etc) and build that relationship and points with them.<br />
<br />
<br /></div>
<br />
<br />
<b>Life In Fort Worth By&nbsp;<a href="https://plus.google.com/+DarrellWolfe" target="_blank">Darrell Wolfe</a></b><br />
<h4>
<ul>
<li>New to the blog?&nbsp;<a href="http://www.lifeinfortworth.com/p/about.html" target="_blank">Start HERE</a></li>
</ul>
<ul>
<li>Click&nbsp;<a href="http://eepurl.com/OjOcn" target="_blank">HERE to Subscribe</a>&nbsp;by email.&nbsp;</li>
</ul>
</h4>
<div>
<b><br /></b></div>
<br />
<div>
</div>
<br />
<div style="-webkit-text-stroke-width: 0px; color: black; font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px;">
<div style="margin: 0px;">
<b>What is YOUR favorite thing about Texas? Comment Below!</b></div>
</div>
