---
title: '2016 Republican Party Primary Election Ballot Tarrant County'
date: '2016-02-22T04:48:00.0000000+00:00'
draft: true
blogger_blog: 'The Life In Fort Worth Blog'
blogger_status: 'LIVE'
blogger_post_id: '578118937200215223'
blogger_filename: '/2016/02/republican-party-primary-election.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Life In Fort Worth Blog/feed.atom'
categories:
  - 'VOTE'
  - 'Navigate'
  - 'Discover'
  - 'Enjoy'
---

<br />
<table class="norm-5px" style="background-color: white; border-collapse: collapse; color: black; font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif; font-size: 13.19px; margin-bottom: 10px; margin-left: 40px; margin-right: 40px; width: 85%;" summary="March 1, 2016 - Primary Election"><tbody>
<tr><th class="normalize" scope="row" style="background-color: whitesmoke; border: 1px solid rgb(204, 204, 204); font-size: 1em; font-weight: normal; padding: 5px;" valign="top" width="50%">Last Day of Early Voting</th><td style="background-color: whitesmoke; border-collapse: collapse; border: 1px solid rgb(204, 204, 204); font-size: 1em; padding: 5px;" valign="top" width="50%">Friday, February 26, 2016</td></tr>
</tbody></table>
<br />
<ul>
<li><a href="http://www.sos.state.tx.us/elections/voter/2016-important-election-dates.shtml" target="_blank"><b>Election Dates</b></a></li>
</ul>
<br />
<br />
I figured I should do little research to see how the most conservative candidates are, in some cases there was only one option. I'm looking for candidates who want smaller government, less regulation, less government spending, more privatized industry. Those where only once choice exists (no challenger), are in non numbered bullet.<br />
<br />
If you couldn't tell from my about page, I'm a CONSERVATIVE. I'm bordering on libertarian in my beliefs about limited government. On my points I'm more libertarian than "GOP".<br />
<div>
<br /></div>
Here's the the things. This is (and is not) a job interview. At work in the hiring process, we look for two things, Qualifications and Temperament, both equally. In the case of elections, I'm looking for these in a different way. I want to know that you know something about the field to which you are applying (asking for my vote), but I care as much (or more) that you hold my values.<br />
<br />
I don't want to send a well qualified person who will stomp all over my rights, over a less qualified person who will preserve them. So your credentials mean something, but they mean less than your messaging, historical decision making, and affiliations. I'm a BIG fan of David Barton and <a href="http://www.wallbuilders.com/" target="_blank">Wallbuilders</a>, so that gives you credit in my book to start.<br />
<br />
So here we go...<br />
<br />
<br />
<b><i>Research</i>:</b><br />
<br />
<br />
<br />
<br />
<ul>
<li><a href="http://www.oilandgaslawyerblog.com/2015/12/texas-railroad-commission-candidates.html" target="_blank">Oil and Gas Lawyer Blog&nbsp;</a></li>
<li><a href="http://www.texasgopvote.com/topics/texas-railroad-commission" target="_blank">Texas GOP Vote</a>&nbsp;(RR)</li>
<li><a href="http://www.texasgopvote.com/topics/2016-elections" target="_blank">Texas GOP Vote 2016</a></li>
<li><a href="http://www.texasgopvote.com/government/green-vs-green-texas-supreme-court-place-5-008598" target="_blank">Green vs Green</a></li>
<li><a href="http://www.texasgopvote.com/government/texas-proposition-research-four-texas-008604" target="_blank">Propositions Research</a></li>
<li><a href="http://wilcoonline.com/meet-the-candidates-railroad-commissioner-p1044-174.htm" target="_blank">Meet the Candidates &nbsp;- RR</a>&nbsp;</li>
<li><a href="http://www.texasgop.org/leadership-directory/texas-supreme-court/" target="_blank">Texas Supreme Court (Currently)</a></li>
<li><a href="http://texasjudges.org/compare-judicial-candidates-2016/" target="_blank">Judges - Compare</a></li>
<li><a href="https://ballotpedia.org/Texas_judicial_elections,_2016" target="_blank">Texas judicial elections, 2016</a></li>
<li><a href="http://www.nationalreview.com/bench-memos/429207/texas-supreme-court-elections-eva-guzman-joe-pool" target="_blank">National Review, Retired Lawyer and Blogger weighs in on Supreme Court Races.</a></li>
</ul>
<br />
<br />
<h3>
March 01, 2016 - Precinct 3043 Tarrant County - Ballot</h3>
<br />
<h3>
Republican Party Primary Election</h3>
<h3>
<b><span style="font-size: large;">Preference for Presidential Nominee</span></b></h3>
<br />
You may vote for one presidential candidate<br />
whose name appears on the ballot or as<br />
uncommitted. Make only ONE choice.<br />
<br />
<b><span style="font-size: large;">1. Ted Cruz, my number one guy.&nbsp;</span></b><br />
2. Ben Carson, was my number one, but I'd love to see him as VP or on the Presidential Cabinet for Health and Human Services.<br />
<br />
<br />
<br />
<b><span style="font-size: large;">United States Representative, District 12</span></b><br />
<br />
<ul>
<li>Kay Granger</li>
</ul>
<br />
<br />
<b><span style="font-size: large;">Railroad Commissioner</span></b><br />
<br />
<br />
Lance N. Christian -None of the candidates except Lance Christian has special expertise in oil and gas regulation and none has served on a state regulatory agency board. -&nbsp;Geoscientist at Railroad Commission. I can't even find a website for this guy, I guess he doesn't want to be found, no go.<br />
<br />
Wayne Christian -&nbsp;Wayne Christian Authored 5 Legislative Bills that Would Increase Regulations and Provide Solyndra-like Subsidies for Renewable Energy (Texas GOP Vote), that alone would take him off my list, no matter how conservative his website looks. - Financial planner; former member of Texas House of Representatives. <a href="http://christianfortexas.com/">ChristianforTexas.com</a>, Wayne says: I have had the honor of serving our state for over a decade, fighting for limited government, fiscal responsibility, and a strong state economy in the Texas Legislature. - Only Candidate That Has Had Direct Oversight Of The Railroad
Commission. Only Candidate With Experience Standing Up To Obama’s Epa. Only Candidate With A Record Of Standing Up For Private
Property Rights. Only Candidate With A 15 Year Record Of Fighting To Slash
Taxes And Regulations<br />
<div class="MsoNormal">
<o:p></o:p><br /></div>
<br />
<br />
<b><span style="font-size: large;">1. Weston Martinez </span></b>- Texas Real Estate Commission public member; Career in oil and gas business development; Political commentator; worked against voter fraud in south Texas. &nbsp;- <b>We need to work hard to keep the EPA out of Texas!</b> <a href="http://westonfortexas.com/">WestonforTexas.com</a> - Weston's story : involved in organizing Hispanics for Ted Cruz for president. In addition to his conservative grassroots work on behalf of Texans. -&nbsp;Weston is also the only candidate in the race with oil and gas experience. &nbsp;As a small business owner, Weston has actually built a business that services oil and gas companies in Texas.<br />
<br />
Ron Hale - Worked across multiple industries, from security to engineering; licensed engineer who specializes in anti-terrorism consulting for the Oil and Gas industry. RonHaleforTexas.com, (sorry, but your website sucks. If you can't get a decent website, I don't trust you to do anything else well either).<br />
<br />
John Greytok -&nbsp;Austin attorney and lobbyist. <a href="http://johngreytok.com/beliefs/" target="_blank">JohnGreytok.com</a> - &nbsp;John's story: I believe in limited government. &nbsp;As a conservative I believe you know how to run your own life far better than any bureaucrat or so called “expert.”<br />
<br />
Gary Gates -&nbsp;Real estate investor; Master’s degree in tax law; Army veteran. <a href="http://www.garygatesfortexas.com/voting_action_center?splash=1" target="_blank">GaryGatesforTexas.com</a>, says all the right stuff, just didn't grab my attention. I still don't know who you are.<br />
<br />
Doug Jeffrey - U.S. Air Force veteran; founder of a venture capital business, and commercial real estate developer. <a href="http://dougjeffrey4texas.com/">DougJeffrey4Texas.com</a>, your opening page asks me for my email and my donation, but says little to nothing about your story... You lost me at hello.<br />
<br />
<br />
<br />
<b><span style="font-size: large;">Justice, Supreme Court, Place 3</span></b><br />
<br />
<br />
Comparing these two (<a href="http://texasjudges.org/compare-lehrmann/" target="_blank">Compare here</a>) I can't find any reason to pick one over the other. They are both conservative, but Debra's already in the role, probably built relationships. But an endoresment from David Barton is enough to put me over the 51% mark.<br />
<br />
<blockquote class="tr_bq">
<em>It is telling that the PAC associated with Texans for Lawsuit Reform, a nonpartisan group that advocates civil justice reform, endorsed Lehrmann when she ran in 2010, but has endorsed Massengale in the upcoming March 2016 election. In order to figure out why, I looked into Lehrmann’s record on the Texas Supreme Court and read some of her decisions. It turns out that since 2010 Lehrmann has dissented more often — over 40 times — than any other member of the Court (all of whom are Republicans). Many of her dissents were in cases applying the landmark Texas Medical Liability Act (TMLA), a comprehensive-reform statute passed by the legislature in 2003 (with the support of TLR) in response to a medical-malpractice crisis that jeopardized the availability of health care in Texas. Lehrmann has consistently — even doggedly — advanced positions that would restrict the application of TMLA by, for example, allowing the assertion of claims that are time-barred under the plain terms of TMLA. In one case, Tenet Hospitals Ltd. v. Rivera (2014), Lehrmann cast the sole dissenting vote in an 8-1 decision enforcing a 10-year “statute of repose” to bar the assertion of a claim filed 15 years after the date of the medical treatment at issue. Lehrmann reasoned that the statute of repose violated the state constitution (a common tactic of activist judges), asserting that “Statutes of repose present harsh barriers to the administration of justice,” and that a 10-year limit is not “a reasonable use of the police power.” In another case, Molinet v. Kimbrell (2011), Lehrmann wrote a dissent finding an “ambiguity” in a two-year statute of limitations, which she then resolved in favor of allowing a claim, based on “legislative history” consisting of an isolated colloquy between two legislators. In a controversial case involving the recognition of same-sex divorces in Texas prior to Obergefell, Lehrmann recused herself without explanation. This is just a sample from her reported decisions. These characteristics — frequent, sometimes lone dissents; resort to unreliable legislative history to defeat the clear text of a statute; questioning the wisdom of the legislature’s policy judgments; consistent plaintiff-orientation; dogmatic and unpersuasive reasoning — are often, based on my experience, indicia of an activist judge. Read more at: </em><a href="http://www.nationalreview.com/bench-memos/426850/texas-judicial-election"><em>http://www.nationalreview.com/bench-memos/426850/texas-judicial-election</em></a></blockquote>
<br />
Debra Lehrmann, Incumbent/currently in role.&nbsp;<a href="http://75.103.78.169/wp/about-judge-lehrmann/" target="_blank">judgedebralehrmann</a>.com says: Respects the Constitution and never legislates from the bench, Strictly interprets the law, Twenty-eight years on the bench. May be a non-conservative activist judge.<br />
<div>
<br /></div>
<b><span style="font-size: large;">1. Michael Massengale </span></b>- <a href="http://michaelmassengale.com/">michaelmassengale.com</a> says: was appointed to the First Court of Appeals by Governor Rick Perry on June 15, 2009. He was elected in 2010 and re-elected to a full term in 2012. He also curates a blog on the history of the Texas Constitution, at <a href="http://www.texconst.wordpress.com/">www.texconst.wordpress.com</a>. He's endorsed by a lot of conservatives, including David Barton - President – Wallbuilders*<br />
<div>
<br /></div>
<br />
<b><span style="font-size: large;">Justice, Supreme Court, Place 5</span></b><br />
<br />
Comparing these two (<a href="http://texasjudges.org/compare-paul-green-v-rick-green/" target="_blank">compare here</a>) Paul Green has the experience in the court system hands down. Paul Green is probably doing a decent job, and has all the right endorsements.<br />
<br />
But the supreme court isn't about the court system, it's about the Constitution (state and federal). We do need a watchdog with unwaivering passion for our history.<br />
<blockquote class="tr_bq">
<em>Rick Green has no prior judicial experience, and scant elevant legal experience. He styles himself a “constitutionalist,” but the bulk of the Texas Supreme Court’s docket concerns mundane — albeit important — matters of state law. His judicial temperament is questionable. According to press reports (e.g., here and here), his brief tenure in Texas’s part-time legislature (which meets for 140 days every other year) was marred by ethical controversies involving his promotion of the dietary supplements Metabolife and FocusFactor. After he left the legislature, he reportedly decked the opponent who defeated him, Patrick Rose. Rick Green ran for an open seat on the Texas Supreme Court in 2010 and narrowly lost to Debra Lehrmann in the Republican primary runoff. Afterwards, in Trump-like fashion, he sued his critics, including former Chief Justice Tom Phillips, contending that their campaign against him was libelous.&nbsp;Read more at: </em><a href="http://www.nationalreview.com/bench-memos/428859/texas-judicial-elections-green-vs-green"><em>http://www.nationalreview.com/bench-memos/428859/texas-judicial-elections-green-vs-green</em></a></blockquote>
<br />
<br />
<strong><span style="font-size: large;">1. Paul Green</span></strong> - <a href="http://texansforjusticepaulgreen.com/">texansforjusticepaulgreen.com</a>, says: By comparison to my background and my record, my opponent doesn't practice law, he’s never tried a case, he’s never appealed a case. And I think that the people of Texas deserve somebody that actually knows what they’re doing if they want to go to the highest civil court in the state. Unfortunately, an endorsement from Rick Perry is a down step in my book, Rick's not a true conservative, he's not bad, but not great.<br />
<div>
&nbsp;</div>
<span style="font-size: large;"><span style="font-size: small;">Rick Green -</span>&nbsp;</span><span style="background-color: white;"><span style="color: #222222; font-family: &quot;helveticaneue&quot; , &quot;helvetica neue&quot; , &quot;helvetica&quot; , &quot;arial&quot; , sans-serif;"><span style="line-height: 20.8px;">Justice Green has an opponent, Rick Green, that is very comfortable, and happy as a radio host and&nbsp;traveling&nbsp;for <a href="http://www.wallbuilders.com/" target="_blank">Wallbuilders </a>(David Barton's Group), but has decided that the Supreme Court needs a&nbsp;‘Constitutional Watchdog’. YES it does!! -&nbsp;</span></span></span><a href="http://rickgreen4texas.com/" style="font-family: HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 20.8px;">rickgreen4texas.com</a><span style="color: #222222; font-family: &quot;helveticaneue&quot; , &quot;helvetica neue&quot; , &quot;helvetica&quot; , &quot;arial&quot; , sans-serif; line-height: 20.8px;"> says: "Rick strongly believes that a parent's right to direct the education and up brining of their children is a fundamental right protected under the constitution." Tim Lambert, Chairman of Texas Home School Coalition PAC. This</span><br />
<span style="color: #222222; font-family: &quot;helveticaneue&quot; , &quot;helvetica neue&quot; , &quot;helvetica&quot; , &quot;arial&quot; , sans-serif;"><span style="line-height: 20.8px;"></span></span><br />
<div>
<br /></div>
<br />
<b><span style="font-size: large;">Justice, Supreme Court, Place 9</span></b><br />
<br />
The Comparison (<a href="http://texasjudges.org/compare-guzman/" target="_blank">here</a>) doesn't give Joe Pool much to go on. He's got credentials, just less than hers. However, his website (<a href="http://joepooljr.com/" target="_blank">here</a>) makes some startling allegations, and supports removing Eva Guzman. Anyone that takes an action to support Planned Parenthood is a traitor and an enemy of the state. Eva Guzman must go. However, the National Review says that this allegation was false and Joe Pool is not a conservative, she is. He is a democrat in republican's clothing.<br />
<br />
<strong><span style="font-size: large;">1. Eva Guzman</span></strong>,&nbsp;<a href="http://evaguzman.com/">evaguzman.com</a>&nbsp;says: Eva Guzman joined the Supreme Court of Texas in 2009, making history as the first Latina to sit on the state’s highest civil court. The next year, the people of Texas elected her to a full term. And Eva Guzman became the first Hispanic woman elected to statewide office in Texas. A proud Texan, Eva Guzman strives for excellence in her work on our state’s highest civil court. Justice Guzman believes “a judge’s highest duty is to uphold the Constitution.” <a href="https://www.tlrpac.com/why-tlrpac-has-endorsed-justice-eva-guzman-vs-joe-pool-place-9" target="_blank">TLRPAC</a> also endorses her as the conservative.<br />
<div>
<br /></div>
<span style="font-size: medium;">Joe Pool</span>,&nbsp;<a href="http://joepooljr.com/">joepooljr.com</a>&nbsp;says: His argument won my vote.<br />
<ul>
<li>WHAT IF JUSTICES WORE THEIR SPONSORS ON THEIR ROBES LIKE NASCAR DRIVERS?</li>
<li>As a Christian Constitutional Conservative, Joe believes that in recent years the Texas Supreme Court has taken a turn that should be impermissible to “We the People.”&nbsp;</li>
<li>Jury verdicts from lower courts are being overturned a staggering 74% of the time and the vast majority of Justices are initially appointed. Joe pledges to only rule in accordance with the Constitution and his conscience.&nbsp;</li>
<li>Joe will ensure that the freedoms and rights of his fellow Texans to live according to our Christian values will not be infringed.</li>
</ul>
<br />
<br />
<b><span style="font-size: large;">Judge, Court of Criminal Appeals, Place 2</span></b><br />
<br />
Compared (<a href="http://texasjudges.org/TzzuW" target="_blank">here</a>) , not much stood out, other than the quotes at the end. Ray didn't have one. In campaigns, messaging matters. Mary and Ray can duke it out with each other, Chris gives me the right vibes.<br />
<br />
<br />
Mary Lou Keel -<a href="http://www.maryloukeel.com/#!blank/wsgxe" target="_blank"> maryloukeel.com</a>, &nbsp;To pursue justice one case at a time based on the evidence in the case and the applicable law. Her site says: Mary Lou Keel has two rivals in the Republican primary, both men. By any relevant, objective criteria, they are both under-qualified for the job they seek. -- There is one area where <b>Rival 1 manages to outdo Keel: &nbsp;bad rulings</b>. He has a habit of wrongly throwing out physical evidence of crime, suppressing confessions and dismissing charges in cases as serious as child molestation and online solicitation of a minor. He claims that he refuses to follow the law if he disagrees with it, and he takes pride in being known as a "contrarian" and a "different kind of judge." --- She says: My husband is a Democrat, but he is also my single greatest supporter. &nbsp;I would never have run for the 232nd District Court in 1994 but for his encouragement. -- Sorry, but that may be a deal breaker too, divided house. I also notice how much she points to the number of cases she's presided over, but says nothing of substance on her website about her support for conservative constitutional values. Some of the buzz words are there, but this website screams moderate to me.<br />
<br />
<br />
Ray Wheless (Mary refers to as&nbsp;<b>Rival 1)</b>- <a href="http://judgeraywheless.com/">judgeraywheless.com</a>, <b>Endorsed by Texas Homeschool PAC.</b> Our forefathers made it very clear that the paramount goal of government is to establish Justice. &nbsp;Without Justice, there can be no right to life, liberty or the pursuit of happiness. There is no greater calling for a Judge than that of protector of these God given rights. If I am elected to this Court, I will uphold the plain language of the Texas Constitution and the United States Constitution as intended by our forefathers.<br />
<br />
<br />
<b><span style="font-size: large;">1. Chris Oldner </span>-</b> &nbsp;<a href="http://chrisoldner.com/">chrisoldner.com</a>, It’s important we have honest and ethical judges who fairly apply the law – to everyone. &nbsp;During my 15 years on the bench, I've always stood by these principles to protect the integrity of our judicial system. &nbsp;To maintain law and order in Texas, I will always strictly apply the law, protect the constitution, and push back against special interest groups who seek to corrupt our courts for personal and political gain. - “I’m a Republican by choice, not by convenience, and am proud to promote conservative causes; like preserving the constitution constitution, limited government, the rule of law, and a judiciary which applies the law, but doesn't make it.”<br />
<div>
<br /></div>
<br />
<br />
<b><span style="font-size: large;">Judge, Court of Criminal Appeals, Place 5</span></b><br />
<br />
Compared (<a href="http://texasjudges.org/compare-harle-v-webster-v-smith-r/" target="_blank">here</a>), Scott Walker is missing from this page, and Steve Smith didn't get a picture or website linked. Hmm...<br />
<br />
Scott Walker (( What an unfortunate name for this election cycle, to have the same name as a person running for president, you are buried in the Google Hits for your name.)) <a href="http://scottwalkerforjudge.com/">scottwalkerforjudge.com</a> says, he's the father of a public school teacher (will he support home schoolers?) Scott Walker is a lifelong Texan. Scott Walker and his wife both descend from a long line of conservatives, and both have been conservative Republicans all of their adult lives. They have been married for 42 years. Scott and his wife are evangelical Christians and are active members in their Dallas area church. The website is weak on make up and content, I'm not sure how much he wanted this.<br />
<br />
<b><span style="font-size: large;">1. Brent Webster -</span></b> &nbsp;<a href="http://websterforjudge.com/">websterforjudge.com</a> says , &nbsp;Endorsed by Texans for Fiscal Responsibility / Texas Home School Coalition -- As a lifelong conservative, our common sense values inform every aspect of my life. I believe in individual liberty and a government that does not intrude on the lives of its citizens. I hold dear the rights of the unborn and will always fight to ensure their protection.<br />
<br />
Sid Harle - <a href="http://electsidharle.com/">electsidharle.com</a> says, his video is compelling. He is a caring and honest person, who stands for family values and doing what's right. He shows compassion. &nbsp;-- I would be honored to have your vote in the upcoming Republican Primary Election. My track record has shown I will serve the citizens of Texas with the utmost character, experience and integrity.<br />
<div>
<br /></div>
Steve Smith -- Google could not find his website, so maybe he dropped out?? I give up trying to find him.&nbsp;<a href="https://ballotpedia.org/Steve_Smith_(Texas)" target="_blank">Ballotpedia</a>&nbsp;gave information under Steve that helped me understand Sid Harle:: "Smith announced his intention to run for seat 5 Texas Court of Criminal Appeals. Incumbent Judge Cheryl Johnson (R) announced that she would not seek re-election. <b>The reason Smith cited for declaring his candidacy was that Republican candidate Sid Harle was not conservative enough for the court.</b> He will face three fellow Republican candidates in a primary election.[3][6]"<br />
<br />
<br />
<br />
<b><span style="font-size: large;">Judge, Court of Criminal Appeals, Place 6</span></b><br />
<br />
Compared (<a href="http://texasjudges.org/compare-keasler-v-davis-r/" target="_blank">here</a>), Richard has no picture or website liked, did he drop out? The rest of his information is blank.<br />
<br />
<br />
<b><span style="font-size: large;">1. Michael E. Keasler </span>-</b>- &nbsp;<a href="http://judgekeasler.com/">judgekeasler.com</a>&nbsp;(website could use some work, I can barely read it) says, The following quate from<a href="http://texasjudges.org/compare-keasler-v-davis-r/" target="_blank"> texasjudges.org</a>&nbsp;Judicial Philosophy – I believe strongly in judicial restraint, and, like Justice Scalia, I am a textualist. &nbsp;Appellate courts should look to the plain meaning of a statute rather than attempting to psychoanalyze the legislature to determine some unspoken “legislative intent.” &nbsp;Judges should not create law in the name of statutory construction. I use logic, common sense, and plain language in crafting judicial opinions.<span class="Apple-tab-span" style="white-space: pre;"> </span><br />
<br />
<br />
Richard Davis - Can't find much of anything about this guy, he must have dropped out.<br />
<br />
<br />
<b><span style="font-size: large;">State Senator, District 12</span></b><br />
<br />
<ul>
<li>Jane Nelson</li>
</ul>
<br />
<br />
<b><span style="font-size: large;">State Representative, District 93</span></b><br />
<br />
<ul>
<li><b>Matt Krause, for the record, I LOVE this guy!!!&nbsp;</b></li>
</ul>
<br />
<br />
<b><span style="font-size: large;">Justice, <a href="https://ballotpedia.org/Texas_Second_District_Court_of_Appeals" target="_blank">2nd Court of Appeals</a> District, Place 3</span></b><br />
<br />
Honestly, the first three sound about equal, the last two are no-go's. The only one that stood out with messaging that appealed to me was Elizabeth Kerr.<br />
<br />
Dabney Bassel, <a href="http://dabneybasselforjudge.com/">dabneybasselforjudge.com</a>, “as a justice, i will bring my conservative view of the law to the 2nd court of appeals, i promise to work hard every day, strictly apply the law as it is written, give all parties a prompt and fair resolution of their cases, and never legislate from the bench.”<br />
<br />
Mary Colchin Johndroe &nbsp; <a href="http://maryjohndroe.com/">maryjohndroe.com</a>, “Grounded by my conservative values, I pledge to you my abiding respect for the law and the Constitution.”<br />
<br />
<b><span style="font-size: large;">1. Elizabeth Kerr</span></b> <a href="http://kerrforjustice.com/">kerrforjustice.com</a>. “We all deal with life’s adversities. How we handle these situations defines us. Justices on the Court of Appeals settle disputes of adversity in the law. Liberal judges try to expand the law; conservative judges apply the law. With no apologies, I will be a conservative judge.”<br />
<br />
William Anthony "Andy" Porter, couldn't find an online presence. <a href="http://ballotpedia.org/Andy_Porter">ballotpedia.org/Andy_Porter</a><br />
<br />
Bill Ray <a href="http://billrayforjustice.com/">billrayforjustice.com</a>, says: "I have been on the front lines of a political campaign before, having run against Wendy Davis in her Fort Worth City Council Campaign. I am of the Christian Faith and a member of First United Methodist Church of Fort Worth."<br />
<br />
<br />
<br />
<b><span style="font-size: large;">Justice, 2nd Court of Appeals District, Place 4 (Unexpired Term)</span></b><br />
<br />
<ul>
<li>Bonnie Sudderth</li>
</ul>
<br />
<br />
<b><span style="font-size: large;">District Judge, 17th Judicial District</span></b><br />
<br />
<ul>
<li>Melody Wilkinson</li>
</ul>
<br />
<br />
<b><span style="font-size: large;">District Judge, 48th Judicial District</span></b><br />
<br />
<ul>
<li>David Evans</li>
</ul>
<br />
<br />
<b><span style="font-size: large;">District Judge, 67th Judicial District</span></b><br />
<br />
<ul>
<li>Don Cosby</li>
</ul>
<br />
<br />
<b><span style="font-size: large;">District Judge, 96th Judicial District</span></b><br />
<br />
<br />
R.H. Wallace, Jr. &nbsp;<a href="http://judgewallace.com/">judgewallace.com</a>, (Your website kind of sucks dude, you could use some branding help). A Defender Of Freedom And Justice, he says:&nbsp;"The strength of America is in our Constitution. With this said, Judges should apply the law, not make the law."<br />
<br />
<b><span style="font-size: large;">1. Traci DeAnne Hutton</span>&nbsp;</b><a href="http://tracihutton.com/">tracihutton.com</a>, Families divided by divorce, unmarried fathers seeking parental rights, partners forming a business and first-time home buyers at closing have one thing in common: They need experienced legal guidance that gets results. And they need it now.&nbsp;<a href="http://huttonforjudge.com/">huttonforjudge.com</a>, She has three adult children; a son, Conner who is a U.S. Marine and two daughters, Caitlin and MacKenzie. <b>As a family, the Hutton’s attend Gateway church in Southlake. SOLD!</b><br />
<br />
<br />
<br />
<b><span style="font-size: large;">District Judge, 153rd Judicial District</span></b><br />
<br />
<ul>
<li>Susan McCoy</li>
</ul>
<br />
<br />
<b><span style="font-size: large;">District Judge, 213th Judicial District</span></b><br />
<br />
<ul>
<li>Louis E. Sturns</li>
</ul>
<br />
<br />
<b><span style="font-size: large;">District Judge, 342nd Judicial District</span></b><br />
<br />
<ul>
<li>Wade Birdwell</li>
</ul>
<br />
<br />
<b><span style="font-size: large;">District Judge, 348th Judicial District</span></b><br />
<br />
<br />
Mike Wallach &nbsp;<a href="http://mikewallachforjudge.com/">mikewallachforjudge.com</a>, Susan and I are active members of Bear Valley Community Church. I believe that I can bring my knowledge from my many years as a courtroom lawyer to the Bench and provide correct application of the law in a fair and balanced manner to all participants in the litigation process. I am asking for your vote for the opportunity to serve you as Judge of the 348th District Court. <i>This one kind of bored me.</i><br />
<br />
<span style="font-size: large;"><b>1. Brooke Allen</b> </span>&nbsp;<a href="http://brookeallenforjudge.com/">brookeallenforjudge.com</a>, Brooke Allen is a true conservative running to serve all of Tarrant County as Judge of the 348th District Court. Her page screams conservative (<a href="http://www.brookeallenforjudge.com/about-1.html" target="_blank">here</a>) &nbsp; &nbsp; Allen’s philosophy is simple, Texans deserve conservative judges on the bench who strictly interpret the laws as written, apply the law fairly and equally to all parties before them, and never legislate from the bench. ((She comes across as volunteer oriented. She also gives more about herself than Lumley)) I'd vote for Allen, but it was almost a toss up between her and Lumley.<br />
<div>
<br /></div>
<div>
Lisa Lumley &nbsp;<a href="http://lisaforjudge.com/">lisaforjudge.com</a>, Constitutional Conservative, As a lifelong conservative, member of the Tarrant County Republican Party Executive Committee and daughter of a combat veteran, Lisa shares our conservative values. As an attorney, Lisa takes great pride in her work defending personal property rights, especially for veterans who risk their lives defending our country. As our new judge, we can trust Lisa to uphold and defend our constitutional rights. Lisa is passionate about her conservative judicial philosophy. ((She comes across as business, professional))</div>
<br />
<br />
<br />
<b><span style="font-size: large;">District Judge, 352nd Judicial District</span></b><br />
<br />
<ul>
<li>Mark Pittman</li>
</ul>
<br />
<br />
<b><span style="font-size: large;">District Judge, 396th Judicial District</span></b><br />
<br />
<ul>
<li>George Gallagher</li>
</ul>
<br />
<br />
<b><span style="font-size: large;">Criminal District Judge, Court No. 2</span></b><br />
<br />
<ul>
<li>Wayne Salvant</li>
</ul>
<br />
<br />
<b><span style="font-size: large;">Family District Judge, 360th Judicial District</span></b><br />
<br />
Both of these make the right statements, but Bennett screams conservative, while Sinha feels like he pays it a mandatory tribute.<br />
<br />
Mike Sinha &nbsp;<a href="http://judgemikesinha.com/">judgemikesinha.com</a>, As Judge of the 360th District Court. &nbsp;Judge Mike Sinha has a proven conservative track record throughout his career. In his 25 years on the bench, he has never signed a Judicial Bypass Order. When re-elected, Judge Mike Sinha will continue to serve our Tarrant County families with CONSERVATIVE REPUBLICAN VALUES.<br />
<br />
<b><span style="font-size: large;">1. Patricia Baca Bennett</span></b> <a href="http://patriciabennettforjudge.com/">patriciabennettforjudge.com</a>, Patricia Baca Bennett is a Constitutional Conservative who believes that the judge's role is to apply the law as passed by the Legislature to the facts of the case before her. Patricia has been married for 19 years and is the mother of two children, including one special needs child. She understands the need to protect children while respecting the rights of parents. Family courts in Texas are courts of law and equity. However, equitable principles can only be used if there is no adequate remedy at law and are limited by both statute and case law. A judge who sees a modern-day family court as simply a "court of equity" fails to recognize the limits Texas law places upon a judge.<br />
<div>
<br /></div>
<div>
<br /></div>
<br />
<br />
<b><span style="font-size: large;">Sheriff</span></b><br />
<br />
This is tough, both Anderson and Waybourn could be good. At first the idea of being tougher on crime and illegals and terrorism sounds good... but then... it starts to sound like big brother government. Dee Anderson sounds like the fiscal conservative I would want. He also helped create the Amber Alert, so... that's hard to beat.<br />
<br />
<b><span style="font-size: large;">1. Dee Anderson</span></b> &nbsp;<a href="http://sheriffanderson2016.com/">sheriffanderson2016.com</a>, Incumbent: During his fifteen years as spokesman, he appeared on virtually every national network news show, as well as appearing live on all three major network morning news shows. &nbsp;Officer Anderson was in the national spotlight in 1996 during the kidnapping of Amber Hagerman, a nine-year-old Arlington girl who was later found murdered.&nbsp;<b>Anderson co-founded the AMBER Plan,</b>&nbsp;a cooperative effort between law enforcement and the media to instantly alert the public of a suspected child abduction. &nbsp;The AMBER Plan has received State-wide and even national acclaim. &nbsp;The National Center for Missing and Exploited Children has adopted the plan, and Sheriff Anderson has traveled to Washington, D.C. to testify about the plan for the U.S. Congress.<br />
<div>
<br /></div>
<b>An arcticle on Anderson's site: </b>Sheriff Dee Anderson and challenger Bill Waybourn, a former suburban police chief, are two of the best-known local law officers of this generation. But only one can be the Tarrant County sheriff for the next four years, and voters must choose between two Republicans with completely different missions for the office. No Democrat is running. <b>Waybourn, 56, of Dalworthington Gardens, has been police chief and chief of public safety there for 31 years. He is more flamboyant, has more law enforcement training and wants the Tarrant County sheriff to become more of a crimefighter again, saying the office should take on a larger role in protecting the county against terrorism and in training city jailers to hold illegal immigrants for federal officials’ review. </b>Anderson acknowledges that he was slow starting his campaign. Instead of that, voters should consider his 15 years of quiet, <b>thrifty management of Tarrant County jails that consistently exceed state standards</b>. He says Change is not needed.<br />
<br />
Bill E. Waybourn <a href="http://www.billwaybourn.com/#!meet-bill/ctvq" target="_blank">&nbsp;billwaybourn.com</a>, I believe this is a pivotal moment for Tarrant County and for Texas. &nbsp;The county deserves a strong conservative Sheriff that is willing to build relationships in the community and lead from the front. I am humbly asking for your support and vote. &nbsp;If elected I will bring the same values that have served me throughout my life to the front lines of Tarrant County, and will work tirelessly to make the Tarrant County Sheriff’s Office the standard bearer for all law enforcement agencies in Texas.<br />
<div>
<br /></div>
John Garris (found little on this guy, and his website gave me an error message), I'm moving on from him.<br />
<br />
<br />
<br />
<br />
<b><span style="font-size: large;">County Tax Assessor-Collector</span></b><br />
<br />
<ul>
<li>Ron Wright</li>
</ul>
<br />
<br />
<b><span style="font-size: large;">County Commissioner, Precinct No. 3</span></b><br />
<br />
<ul>
<li>Gary Fickes</li>
</ul>
<br />
<br />
<b><span style="font-size: large;">Constable, Precinct No. 4</span></b><br />
<br />
Compare them <a href="http://onyourballot.vote411.org/race-detail.do?id=13931096#.Vs4s_3IUXRY" target="_blank">HERE</a>. I plead my ignorance of this office. But my gut impression would be to go with the guy who says "While speaking with the public." An open ear is the sign of a good leader, few leaders SEEK feedback from those they lead.<br />
<br />
<br />
PROCESS SERVING:  What changes, if any, need to be made regarding process serving?<br />
<br />
<strong><span style="font-size: large;">1. J.D. Sparks:</span></strong>&nbsp; While speaking with the public, I have found that the main challenge of the Constable is Process Serving and the amount of time it takes to have the service executed. From the first day of taking the Office of Constable, I will assign Deputies to areas of the Precinct and hold them accountable for the Processes in their area being served in the time that is required by Law.&nbsp;&nbsp;&nbsp;&nbsp; <br />
<br />
<br />
Michael Hardy:&nbsp;&nbsp; The service of civil process can be very challenging if the rules are not followed. Then you have the old adage that for every rule in civil process there is an exception. Personally I believe that the Constables serving civil process, on a routine basis, in uniform creates more opportunity for escalation and/or embarrassment to a defendant. Communication with plaintiffs is paramount to good service. Professional service in a business-like manner would bring about a more desired result.&nbsp;&nbsp;&nbsp; <br />
<br />
<br />
Joe D. "Jody" Johnson:&nbsp;&nbsp; The manner in which process service is currently conducted in precinct #4 is very sound. Public safety is always priority one as is the safety of our deputies.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br />
<br />
<br />
<b><span style="font-size: large;">County Chair</span></b><br />
<br />
This is an open position, no incumbent. Both good be ok.&nbsp; <br />
<br />
Tim O'Hare - Attorney and real estate investor, made headlines when he was on the Dallas County council, proposing to fine landlords who rent to illegals. He just moved to Southlake.<br />
<br />
David Wylie - Wylie is a computer consultant and he's been involved with the Tarrant County Rep Party for decades. He said "A contested race will sharpen all swords." <br />
<br />
<br />
<br />
------------------------------------------------------------------------------------------------------<br />
<br />
<h4>
<span style="font-size: large;">
Proposition 1</span></h4>
Texas should replace the property tax<br />
system with an alternative other than an<br />
income tax and require voter approval to<br />
increase the overall tax burden.<br />
<b>Yes</b><br />
<br />
<b style="background-color: white; color: #222222; font-family: HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 20.8px;">Proposition 1:&nbsp;</b><span style="background-color: white; color: #222222; font-family: &quot;helveticaneue&quot; , &quot;helvetica neue&quot; , &quot;helvetica&quot; , &quot;arial&quot; , sans-serif; font-size: 16px; line-height: 20.8px;">Texas should replace the property tax system with an alternative other than an income tax and require voter approval to increase the overall tax burden.</span><br />
<span style="background-color: white; color: #222222; font-family: &quot;helveticaneue&quot; , &quot;helvetica neue&quot; , &quot;helvetica&quot; , &quot;arial&quot; , sans-serif; font-size: 16px; line-height: 20.8px;"></span><br />
<div>
<br /></div>
<span style="background-color: white; color: #222222; font-family: &quot;helveticaneue&quot; , &quot;helvetica neue&quot; , &quot;helvetica&quot; , &quot;arial&quot; , sans-serif; font-size: 16px; line-height: 20.8px;">This proposition started as saying we should “reform” the property tax system, and before passage was amended almost unanimously to read “replace” the property tax system due to the fact that you can lose your property if you cannot pay your property taxes. In many cases homes are paid for but the tax payments alone exceed the original mortgage payments. This slams those on fixed retirement incomes and sometimes even forces elderly out of their homes. This is NOT sustainable, nor even a moral tax system, and needs to be changed. VOTE YES!</span><br />
<br />
<h4>
<span style="font-size: large;">
Proposition 2</span></h4>
Texas cities and counties should be<br />
required to comply with federal<br />
immigration laws or be penalized by loss<br />
of state funds.<br />
<b>Yes</b><br />
<br />
<div style="background-color: white; color: #222222; font-family: HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 20.8px; margin-bottom: 0.5em;">
<b>Proposition 2:</b>&nbsp;Texas cities and counties should be required to comply with federal immigration laws or be penalized by loss of state funds. This is a clear shot across the bow to send a message to mayors and legislators alike that “sanctuary cities” like Houston and San Antonio, that essentially provide safe harbor to those here illegally, will not be tolerated. Unless you LIKE the idea of such sanctuary cities, VOTE YES!</div>
<div>
<br /></div>
<br />
<h4>
<span style="font-size: large;">
Proposition 3</span></h4>
Texas should prohibit governmental<br />
entities from collecting dues for labor<br />
unions through deductions from public<br />
employee paychecks.<br />
<b>Yes</b><br />
<br />
<div style="background-color: white; color: #222222; font-family: HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 20.8px; margin-bottom: 0.5em;">
<b>Proposition 3:</b>&nbsp;Texas should prohibit governmental entities from collecting dues for labor unions through deductions from the public employee paychecks.</div>
<div style="background-color: white; color: #222222; font-family: HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 20.8px; margin-bottom: 0.5em;">
This proposition was promoted by the Republican Party of Texas when it was learned that the Texas government essentially collects union dues, a portion of which then goes into Democratic campaign coffers. This is a no-brainer. All conservatives should clearly VOTE YES!</div>
<div style="background-color: white; color: #222222; font-family: HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 20.8px; margin-bottom: 0.5em;">
<br /></div>
<h4>
<span style="font-size: large;">
Proposition 4</span></h4>
Texas and its citizens should strongly<br />
assert 10th Amendment Rights<br />
guaranteed by the U. S. Constitution<br />
which states "The powers not delegated<br />
to the United States by the Constitution,<br />
nor prohibited by it to the States, are<br />
reserved to the States respectively, or to<br />
the people."<br />
<b>Yes&nbsp;</b><br />
<br />
<div style="background-color: white; color: #222222; font-family: HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 20.8px; margin-bottom: 0.5em;">
<b>Proposition 4:</b>&nbsp;Texas and its citizens should strongly assert 10th Amendment Rights guaranteed by the U.S. Constitution which states “The powers not delegated to the United States by the Constitution, nor prohibited by it to the States, are reserved to the States respectively, or to the people.”</div>
<div style="background-color: white; color: #222222; font-family: HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 20.8px; margin-bottom: 0.5em;">
This is the best resolution to come down the pike in several election cycles. It instructs the Texas government and people to resist the illegal intrusions and power grabs by the federal government at every turn. ALL GOVERNMENT functions not “enumerated” in the Constitution are explicitly reserved TO THE STATES by the 10th Amendment. For over a million Texas Republican Primary voters, they will have the opportunity to actually read the text of the 10th Amendment itself for the first time. VOTE YES!</div>
<br />
<br />
<div>
<br /></div>
<br />
<b>Life In Fort Worth By&nbsp;<a href="https://plus.google.com/+DarrellWolfe" target="_blank">Darrell Wolfe</a></b><br />
<h4>
<ul>
<li>Click&nbsp;<a href="http://eepurl.com/OjOcn" target="_blank">HERE to Subscribe</a>&nbsp;by email.&nbsp;</li>
</ul>
</h4>
<div>
<b></b><br />
<div>
<br /></div>
</div>
<br />
<div>
</div>
<br />
<div style="color: black; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px;">
<div style="margin: 0px;">
<b>What is YOUR favorite thing about Texas? Comment Below!</b></div>
</div>
