---
title: 'Disclosure Templates'
date: '2050-01-22T17:00:00.0000000+00:00'
draft: true
blogger_blog: 'The Life In Fort Worth Blog'
blogger_status: 'DRAFT'
blogger_post_id: '278244278704813500'
blogger_filename: '/2050/01/disclosure-templates.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Life In Fort Worth Blog/feed.atom'
---

My Disclosure<br />
<br />
Disclosure of Material Connection: Some of the links in the post above are “affiliate links.” This means if you click on the link and purchase the item, I will receive an affiliate commission.  I may also have received one or more of the products or services mentioned above for free in the hope that I would mention it on my blog. Regardless, I only recommend products or services I use personally and believe will add value to my readers. I am disclosing this in accordance with the Federal Trade Commission’s <a href="http://www.gpo.gov/fdsys/pkg/CFR-2003-title16-vol1/content-detail.html" target="_blank">16 CFR, Part 255</a>: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.” A Big Thank You to <a href="http://michaelhyatt.com/five-ways-to-comply-with-the-new-ftc-guidelines-for-bloggers.html" target="_blank">Michael Hyatt</a> for helping us Bloggers with these new legal disclosure requirements.<br />
<br />
<br />
<br />
<br />
<ol style="background-color: white; border: 0px; color: #272727; font-family: Georgia, Times, 'Times New Roman', serif; font-size: 16px; line-height: 24px; list-style-image: initial; list-style-position: initial; margin: 0px 0px 1.5em 3em; outline: 0px; padding: 0px; vertical-align: baseline;">
<li style="border: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px 0px 1em; outline: 0px; padding: 0px; vertical-align: baseline;"><strong style="border: 0px; font-family: inherit; font-style: inherit; margin: 0px; outline: 0px; padding: 0px; vertical-align: baseline;">Disclosure 1: No Material Connection.</strong>&nbsp;This is the standard disclosure I use when I don’t have any embedded links or a relationship with any of he products or services I have mentioned:<div class="setoff" style="background-color: #eeeeee; background-position: initial initial; background-repeat: initial initial; border: 1px solid rgb(214, 214, 214); font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 0.9em; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 15px 20px; vertical-align: baseline;">
Disclosure of Material Connection: I have not received any compensation for writing this post. I have no material connection to the brands, products, or services that I have mentioned. I am disclosing this in accordance with the Federal Trade Commission’s&nbsp;<a href="http://www.access.gpo.gov/nara/cfr/waisidx_03/16cfr255_03.html" style="border: 0px; color: #4382c4; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;" target="_blank">16 CFR, Part 255</a>: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.”</div>
</li>
<li style="border: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px 0px 1em; outline: 0px; padding: 0px; vertical-align: baseline;"><strong style="border: 0px; font-family: inherit; font-style: inherit; margin: 0px; outline: 0px; padding: 0px; vertical-align: baseline;">Disclosure 2: Affiliate Links.</strong>&nbsp;This is the disclosure I use when I included an embedded affiliate link from Amazon or some other provider:<div class="setoff" style="background-color: #eeeeee; background-position: initial initial; background-repeat: initial initial; border: 1px solid rgb(214, 214, 214); font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 0.9em; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 15px 20px; vertical-align: baseline;">
Disclosure of Material Connection: Some of the links in the post above are “affiliate links.” This means if you click on the link and purchase the item, I will receive an affiliate commission. Regardless, I only recommend products or services I use personally and believe will add value to my readers. I am disclosing this in accordance with the Federal Trade Commission’s&nbsp;<a href="http://www.access.gpo.gov/nara/cfr/waisidx_03/16cfr255_03.html" style="border: 0px; color: #4382c4; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;" target="_blank">16 CFR, Part 255</a>: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.”</div>
</li>
<li style="border: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px 0px 1em; outline: 0px; padding: 0px; vertical-align: baseline;"><strong style="border: 0px; font-family: inherit; font-style: inherit; margin: 0px; outline: 0px; padding: 0px; vertical-align: baseline;">Disclosure 3: Review or Sample Copy.</strong>&nbsp;This is the disclosure I use when I am reviewing a book or other product that I have received from someone in the hope that I will review it:<div class="setoff" style="background-color: #eeeeee; background-position: initial initial; background-repeat: initial initial; border: 1px solid rgb(214, 214, 214); font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 0.9em; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 15px 20px; vertical-align: baseline;">
Disclosure of Material Connection: I received one or more of the products or services mentioned above for free in the hope that I would mention it on my blog. Regardless, I only recommend products or services I use personally and believe will be good for my readers. I am disclosing this in accordance with the Federal Trade Commission’s&nbsp;<a href="http://www.access.gpo.gov/nara/cfr/waisidx_03/16cfr255_03.html" style="border: 0px; color: #4382c4; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;" target="_blank">16 CFR, Part 255</a>: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.”</div>
<div style="border: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin-bottom: 1em; margin-top: 1em; outline: 0px; padding: 0px; vertical-align: baseline;">
If you are a&nbsp;<a href="http://brb.thomasnelson.com/" style="border: 0px; color: #4382c4; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;" target="_blank" title="Thomas Nelson Book Review Blogger Site">Thomas Nelson Book Review Blogger</a>, you might want to use this disclaimer:</div>
<div class="setoff" style="background-color: #eeeeee; background-position: initial initial; background-repeat: initial initial; border: 1px solid rgb(214, 214, 214); font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 0.9em; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 15px 20px; vertical-align: baseline;">
Disclosure of Material Connection: I received this book free from Thomas Nelson Publishers as part of their&nbsp;<a href="http://brb.thomasnelson.com/" style="border: 0px; color: #4382c4; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;" target="_blank" title="Thomas Nelson Book Review Blogger Site">Book Review Blogger program</a>. I was not required to write a positive review. The opinions I have expressed are my own. I am disclosing this in accordance with the Federal Trade Commission’s 16 CFR, Part 255: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.”</div>
</li>
<li style="border: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px 0px 1em; outline: 0px; padding: 0px; vertical-align: baseline;"><strong style="border: 0px; font-family: inherit; font-style: inherit; margin: 0px; outline: 0px; padding: 0px; vertical-align: baseline;">Disclosure 4: Sponsored Post.</strong>&nbsp;This is the disclosure I use when someone pays me to write a post for a product, service, or conference. I turn down more of these posts than I accept, because I have to be genuinely excited about the product:<div class="setoff" style="background-color: #eeeeee; background-position: initial initial; background-repeat: initial initial; border: 1px solid rgb(214, 214, 214); font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 0.9em; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 15px 20px; vertical-align: baseline;">
Disclosure of Material Connection: This is a “sponsored post.” The company who sponsored it compensated me via a cash payment, gift, or something else of value to write it. Regardless, I only recommend products or services I use personally and believe will be good for my readers. I am disclosing this in accordance with the Federal Trade Commission’s&nbsp;<a href="http://www.access.gpo.gov/nara/cfr/waisidx_03/16cfr255_03.html" style="border: 0px; color: #4382c4; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;" target="_blank">16 CFR, Part 255</a>: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.”</div>
</li>
<li style="border: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px 0px 1em; outline: 0px; padding: 0px; vertical-align: baseline;"><strong style="border: 0px; font-family: inherit; font-style: inherit; margin: 0px; outline: 0px; padding: 0px; vertical-align: baseline;">Disclosure 5: Employee/Shareholder Relationship.</strong>&nbsp;This is the disclosure I use when I am writing about a book my company, Thomas Nelson, has published.<div class="setoff" style="background-color: #eeeeee; background-position: initial initial; background-repeat: initial initial; border: 1px solid rgb(214, 214, 214); font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 0.9em; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 15px 20px; vertical-align: baseline;">
Disclosure of Material Connection: I am the CEO of Thomas Nelson, the company that published this book. Regardless, I only recommend books that I have personally read and believe will be good for my readers. I am disclosing this in accordance with the Federal Trade Commission’s&nbsp;<a href="http://www.access.gpo.gov/nara/cfr/waisidx_03/16cfr255_03.html" style="border: 0px; color: #4382c4; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;" target="_blank">16 CFR, Part 255</a>: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.”</div>
</li>
</ol>
<div style="background-color: white; border: 0px; color: #272727; font-family: Georgia, Times, 'Times New Roman', serif; font-size: 16px; line-height: 24px; margin-bottom: 1.5em; outline: 0px; padding: 0px; vertical-align: baseline;">
Feel free to borrow this method or any of my disclosure copy. If you improve upon it, I’d love to hear about it in the comments below.<br />
<br />
My Disclosure<br />
<ol style="border: 0px; list-style-image: initial; list-style-position: initial; margin: 0px 0px 1.5em 3em; outline: 0px; padding: 0px; vertical-align: baseline;">
<li style="border: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px 0px 1em; outline: 0px; padding: 0px; vertical-align: baseline;"><div class="setoff" style="background-color: #eeeeee; border: 1px solid rgb(214, 214, 214); font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 0.9em; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 15px 20px; vertical-align: baseline;">
Disclosure of Material Connection: Some of the links in the post above are “affiliate links.” This means if you click on the link and purchase the item, I will receive an affiliate commission. Regardless, I only recommend products or services I use personally and believe will add value to my readers. I am disclosing this in accordance with the Federal Trade Commission’s&nbsp;<a href="http://www.access.gpo.gov/nara/cfr/waisidx_03/16cfr255_03.html" style="border: 0px; color: #4382c4; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 0px; text-decoration: none; vertical-align: baseline;" target="_blank">16 CFR, Part 255</a>: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.”</div>
</li>
</ol>
</div>
