---
title: 'Moving to DFW?'
date: '2015-05-08T04:33:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'The Life In Fort Worth Blog'
blogger_status: 'LIVE'
blogger_page_id: '7917806864054602623'
blogger_filename: '/p/fyi.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Life In Fort Worth Blog/feed.atom'
---

<br />
<h3>
The Basics of Moving&nbsp;to (or around) the Dallas - Fort Worth Texas Area.</h3>
<br />
There are several things I wish I knew either before of just after moving to Texas from California. Many of which were just practical things, like what to pack, how to prepare the kids, etc.Some of them were things I didn't know to expect, like how different the Drivers License and Car Registration is here.<br />
<br />
Here are some things I put together just to help you transition in your move to Texas.<br />
<br />
<h3>
Top Need To Knows</h3>
<h4>
<ul>
<li><a href="http://www.lifeinfortworth.com/2012/02/top-10-need-to-knows.html" target="_blank">Top Need To Knows</a></li>
</ul>
</h4>
<h3>
Other Really Helpful Information</h3>
<div>
<h4>
Kids</h4>
</div>
<div>
<ul>
<li><a href="http://texaslivinginfo.blogspot.com/2012/02/moving-with-kids.html" target="_blank">Moving with Kids - Stuff to think about and prepare for</a></li>
<li><a href="http://texaslivinginfo.blogspot.com/2012/02/kids-stuff.html" target="_blank">Kids Stuff - Stuff to do with your kids here</a></li>
</ul>
</div>
<h4>
Auto</h4>
<div>
<ul>
<li><a href="http://www.lifeinfortworth.com/2015/04/how-to-register-your-car-and-get-your.html" target="_blank">How To Register Your Car And Get Your Drivers License In Texas</a></li>
</ul>
</div>
<div>
<h4>
Home</h4>
</div>
<div>
<ul>
<li>Find a Place to Stay</li>
<ul>
<li><a href="http://texaslivinginfo.blogspot.com/2012/02/home-sweet-home.html" target="_blank">Home Sweet Home - Looking for a home or apartment</a></li>
</ul>
<li>Utility Info</li>
<ul>
<li><a href="http://stormcenter.oncor.com/default.html" target="_blank">Oncor Storm Center</a></li>
<li><a href="http://www.powertochoose.org/" target="_blank">PowerToChoose.Org</a> (You an choose your electric company!)</li>
<li><a href="http://ww2.ambitenergy.com/rates-and-plans" target="_blank">Ambit Energy Electric</a>: Earn Free Electricity</li>
</ul>
</ul>
</div>
<div>
<h4>
Business</h4>
</div>
<div>
<ul>
<li><a href="http://texaslivinginfo.blogspot.com/2012/02/businesses.html" target="">Businesses - Starting and Running a Business in Texas</a></li>
<ul>
<li><a href="http://www.handsonbanking.org/" target="_blank">Hands on Banking - Free Online Training for&nbsp;Entrepreneurs&nbsp;and Small Business</a></li>
</ul>
<li>Banking and Finance</li>
<ul>
<li><a href="http://www.handsonbanking.org/" target="_blank">Hands on Banking - Free Online Training for most financial topics and for most ages.</a></li>
</ul>
</ul>
</div>
<div>
<h4>
Government Interactions</h4>
<ul>
<li><a href="http://texaslivinginfo.blogspot.com/2012/02/voting.html" target="_blank">Voting - Resources for voting information</a></li>
<ul>
<li><a href="http://texaslivinginfo.blogspot.com/2012/02/texas-counties-map.html" target="_blank">What County am I am? There are so many!</a></li>
</ul>
<li><br /></li>
<ul>
</ul>
</ul>
<br />
<br /></div>
