---
title: 'Resources'
date: '2015-05-08T04:27:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'The Life In Fort Worth Blog'
blogger_status: 'LIVE'
blogger_page_id: '3477089850920043127'
blogger_filename: '/p/resources_6.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Life In Fort Worth Blog/feed.atom'
---

<span style="font-family: inherit;">The following are some resources you might find helpful when living in or visiting the Fort Worth Texas Area.</span><br />
<span style="font-family: inherit;"><br /></span>
<span style="font-family: inherit;"><br /></span>
<br />
<h3>
<span style="font-family: inherit; font-size: small;">Fort Worth Moving/Relocation Guides and Checklists:</span></h3>
<div>
<ul>
<li><a href="http://www.realsimple.com/home-organizing/organizing/moving/moving-checklist" target="_blank"><span style="font-family: inherit;">Real Simple's Moving Checklist</span></a></li>
<li><a href="http://moving.about.com/od/afterthemove/a/after_checklist.htm" target="_blank"><span style="font-family: inherit;">Moving.About: After Moving Checklist</span></a></li>
<li><span style="font-family: inherit;"><a href="http://www.fortworthchamber.com/explore-fort-worth/moving-to-fort-worth/" target="_blank">Fort Worth Chamber of Commerce Moving Guides</a></span></li>
<li><a href="http://movingtotexas.net/dallas-fort-worth/" target="_blank">Dallas In A Nut-Shell</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://123relocation.com/Texas/" style="color: #ae4e1e; text-decoration: none;">123 Relocation Guide</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.dmv.org/tx-texas/relocation" style="color: #ae4e1e; text-decoration: none;">DMV Relocation Guide</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.emic.org/downloads_all.php?cat=10" style="color: #ae4e1e; text-decoration: none;">EMIC Relocation Packet</a></li>
</ul>
</div>
<h3>
<span style="font-family: inherit; font-size: small;">Travel:</span></h3>
<div style="font-weight: normal;">
<span style="font-family: inherit;"><br /></span></div>
<ul style="background-color: white; color: #5d5d5d; font-weight: normal; line-height: 1.2; margin: 0px; padding: 0px 0px 0px 1.25em;"><ul>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.texas.aaa.com/en-tx/Pages/Home.aspx" style="color: #ae4e1e; line-height: 1.2; text-decoration: none;">AAA Texas</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.amtrak.com/servlet/ContentServer?pagename=Amtrak/HomePage&amp;WT.mc_t=FY11BRAND&amp;WT.mc_n=kwGAGSEARCH&amp;WT.mc_r=365&amp;utm_source=google&amp;utm_medium=cpc&amp;utm_term=amtrak" style="color: #ae4e1e; text-decoration: none;">Amtrak</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.dfwairport.com/" style="color: #ae4e1e; line-height: 1.2; text-decoration: none;">DFW Airport</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.enterprise.com/car_rental/deeplinkmap.do?bid=019&amp;cnty=US&amp;language=en&amp;arc=GSSB183&amp;cm_mmc=Google-_-Brand-_-GS_SE_Top_B_NTL_E_US-_-enterprise" style="color: #ae4e1e; line-height: 1.2; text-decoration: none;">Enterprise Rent-A-Car</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.hojo.com/HowardJohnson/control/home?variant=&amp;cid=IP_PPC_GGL_TM%20&amp;iataNumber=00065402&amp;client_account2=1000008335&amp;008=&amp;004=2031984502&amp;005=13515402&amp;006=6318085822&amp;007=Search&amp;002=2189879" style="color: #ae4e1e; text-decoration: none;">Howard Johnson Hotels</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.priceline.com/default.asp?refid=PLGOOGLECPC&amp;refclickid=S_priceline_e&amp;gclid=CI3nvf60uasCFY_CKgod9yZkgA" style="color: #ae4e1e; text-decoration: none;">Priceline Travel Booking</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="https://www.facebook.com/TexasHillCountry" style="color: #ae4e1e; text-decoration: none;">Texas Hill Country</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.traveltex.com/" style="color: #ae4e1e; line-height: 1.2; text-decoration: none;">Texas Tourism</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><br /></li>
</ul>
</ul>
<h4>
<span style="font-family: inherit;">Churches and Ministries in DFW</span></h4>
<h4>
<ul style="background-color: white; color: #5d5d5d; font-weight: normal; line-height: 1.2; margin: 0px; padding: 0px 0px 0px 1.25em;"><ul>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.arcchurches.com/find-a-church" style="color: #ae4e1e; text-decoration: none;">Locator: ARC Planted Churches</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://churches.kcm.org/" style="color: #ae4e1e; text-decoration: none;">Locator: KCM Related Churches</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://wordchurchfinder.blogspot.com/" style="color: #ae4e1e; text-decoration: none;">Locator: Word Church Finder</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://gatewaypeople.com/" style="color: #ae4e1e; text-decoration: none;">Gateway Church</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://emic.org/" style="color: #ae4e1e; text-decoration: none;">Eagle Mountain Int Church</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.fellowshipoftheparks.com/" style="color: #ae4e1e; text-decoration: none;">Fellowship of the Parks Church</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://hhttp//www.heritageoffaith.com/" style="color: #ae4e1e; line-height: 1.2; text-decoration: none;">Heritage of Faith Christian Center (Church)</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.kcm.org/bvov-media" style="color: #ae4e1e; text-decoration: none;">Kenneth Copeland Ministries</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://thepottershouse.org/" style="color: #ae4e1e; line-height: 1.2; text-decoration: none;">Potters House Church</a>&nbsp;Dallas TX, Bishop T.D. Jakes</li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.svtx.org/" style="color: #ae4e1e; text-decoration: none;">Shepherd's Voice Church</a></li>
</ul>
</ul>
</h4>
<h4>
<span style="font-family: inherit;">
Home Owners</span></h4>
<ul>
<li><b><span style="font-family: inherit;">DIY</span></b></li>
<ul>
<li><a href="http://www.todayshomeowner.com/" target="_blank"><span style="font-family: inherit;">Todays Home Owners - DIY Home Ownership</span></a></li>
<li><a href="http://www.diynetwork.com/" target="_blank"><span style="font-family: inherit;">DIY Network</span></a></li>
</ul>
<li><b><span style="font-family: inherit;">Garden</span></b></li>
<ul>
<li><span style="font-family: inherit;"><a href="http://www.wbfarmstore.net/category/blog/" target="_blank">Wells Brothers</a>: Pet, Lawn, and Garden Supply</span></li>
<li><span style="font-family: inherit;"><a href="http://northtexasvegetablegardeners.com/" target="_blank">North Texas Vegetable Gardeners</a>&nbsp;Gardening Blog</span></li>
<li><span style="font-family: inherit;"><a href="http://grownorthtexas.org/" target="_blank">Grow North Texas</a>: Gardening Blog</span></li>
</ul>
</ul>
<div>
<ul>
<li><b><span style="font-family: inherit;">Finding Your Home</span></b></li>
<ul>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.texasliving.com/" style="color: #ae4e1e; text-decoration: none;">Texas Living Real Estate Sales</a></li>
<li><span style="font-family: inherit;"><a href="http://www.lifeinfortworth.com/2012/02/home-sweet-home.html" target="_blank">Home Sweet Home</a> - Looking for a home or apartment</span></li>
</ul>
</ul>
<ul>
<li><b><span style="font-family: inherit;">Utility Info for DFW</span></b></li>
<ul>
<li><a href="http://stormcenter.oncor.com/default.html" target="_blank"><span style="font-family: inherit;">Oncor Storm Center</span></a></li>
<li><span style="font-family: inherit;"><a href="http://www.powertochoose.org/" target="_blank">PowerToChoose.Org</a>&nbsp;(You an choose your electric company!)</span></li>
<li><span style="font-family: inherit;"><a href="http://ww2.ambitenergy.com/rates-and-plans" target="_blank">Ambit Energy Electric</a>: Earn Free Electricity</span></li>
</ul>
</ul>
</div>
<h4>
<span style="font-family: inherit;">
Auto</span></h4>
<div>
<ul>
<li><a href="http://www.txdmv.gov/" target="_blank"><span style="font-family: inherit;"><b>Car Registration </b>@&nbsp;<span style="color: black;">DMV -</span>&nbsp;TX Dept of Motor Vehicles&nbsp;</span></a></li>
<li><a href="http://www.txdps.state.tx.us/driverlicense/" target="_blank"><span style="font-family: inherit;"><b>Drivers License</b> Get/Renew @TX DPS - Dept of Public Safety</span></a></li>
<li><span style="font-family: inherit;"><a href="http://www.texas.aaa.com/home.html?zip=76262&amp;stateprov=tx&amp;city=roanoke&amp;devicecd=PC&amp;referer=www.texas.aaa.com" target="_blank"><b>AAA Texas</b>: Insurance, Roadside Assistance, Travel Planning, and More</a></span></li>
</ul>
</div>
<div>
<div>
<h4>
<span style="font-family: inherit;">Government Websites:</span></h4>
<ul style="background-color: white; color: #5d5d5d; line-height: 1.2; margin: 0px; padding: 0px 0px 0px 1.25em;"><ul>
<li><a href="http://texaslivinginfo.blogspot.com/2012/02/voting.html" target="_blank"><span style="font-family: inherit;">Voting - Resources for voting information</span></a></li>
<ul>
<li><span style="font-family: inherit;"><a href="http://texaslivinginfo.blogspot.com/2012/02/texas-counties-map.html" target="_blank">What County am I am? There are so many!</a></span></li>
</ul>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.ers.usda.gov/StateFacts/TX.htm" style="color: #ae4e1e; text-decoration: none;">USDA Statistics for TX</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.txdmv.gov/" style="color: #ae4e1e; text-decoration: none;">Auto DMV - Dept of Motor Vehicles</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.txdps.state.tx.us/rsd/vi/" style="color: #ae4e1e; text-decoration: none;">Auto Inspections</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.registeredtexan.com/" style="color: #ae4e1e; text-decoration: none;">Auto Registration Info</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://factfinder.census.gov/servlet/SAFFFacts?_event=Search&amp;geo_id=&amp;_geoContext=&amp;_street=&amp;_county=76052&amp;_cityTown=76052&amp;_state=&amp;_zip=76052&amp;_lang=en&amp;_sse=on&amp;pctxt=fph&amp;pgsl=010&amp;show_2003_tab=&amp;" style="color: #ae4e1e; text-decoration: none;">Census Data</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.txdps.state.tx.us/driverlicense/" style="color: #ae4e1e; text-decoration: none;">Drivers Licenses - DPS</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.uscis.gov/portal/site/uscis" style="color: #ae4e1e; text-decoration: none;">Immigration Info</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.texasports.org/" style="color: #ae4e1e; text-decoration: none;">Texas Ports</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.texas.gov/en/Pages/default.aspx" style="color: #ae4e1e; text-decoration: none;">Texas.Gov (One stop site for Info)</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.ers.usda.gov/StateFacts/TX.htm" style="color: #ae4e1e; text-decoration: none;">USDA TX State Statistics</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.usps.com/" style="color: #ae4e1e; text-decoration: none;">USPS Mail</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.sos.state.tx.us/elections/pamphlets/largepamp.shtml" style="color: #ae4e1e; text-decoration: none;">Voting Info - Tx Sec of State</a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.votexas.org/" style="color: #ae4e1e; text-decoration: none;">Voting Info - Votexas.org</a></li>
</ul>
</ul>
</div>
<h4>
<span style="font-family: inherit;">Business Information:</span></h4>
<h4>
<div style="font-weight: normal;">
</div>
<div style="font-weight: normal;">
<ul>
<li><a href="http://texaslivinginfo.blogspot.com/2012/02/businesses.html" target=""><span style="font-family: inherit;">Businesses - Starting and Running a Business in Texas</span></a></li>
<ul>
<li><a href="http://www.handsonbanking.org/" target="_blank"><span style="font-family: inherit;">Hands on Banking - Free Online Training for&nbsp;Entrepreneurs&nbsp;and Small Business</span></a></li>
<li><a href="http://factfinder.census.gov/servlet/SAFFFacts?_event=Search&amp;geo_id=&amp;_geoContext=&amp;_street=&amp;_county=76052&amp;_cityTown=76052&amp;_state=&amp;_zip=76052&amp;_lang=en&amp;_sse=on&amp;pctxt=fph&amp;pgsl=010&amp;show_2003_tab=&amp;" style="background-color: white; color: #ae4e1e; line-height: 1.2; text-decoration: none;"><span style="font-family: inherit;">Census Data By Zip</span></a></li>
<li><a href="http://www.dallascounty.org/department/countyclerk/roam.php" style="background-color: white; color: #ae4e1e; line-height: 1.2; text-decoration: none;"><span style="font-family: inherit;">Dallas County Clerk</span></a></li>
<li><a href="http://dentoncounty.com/dept/main.asp?Dept=17&amp;Link=50" style="background-color: white; color: #ae4e1e; line-height: 1.2; text-decoration: none;"><span style="font-family: inherit;">Denton County Clerk</span></a></li>
<li><a href="http://www.ers.usda.gov/StateFacts/TX.htm" style="background-color: white; color: #ae4e1e; line-height: 1.2; text-decoration: none;"><span style="font-family: inherit;">Hands On Banking - Business Training</span></a></li>
<li><a href="http://www.handsonbanking.org/en/" style="background-color: white; color: #ae4e1e; line-height: 1.2; text-decoration: none;"><span style="font-family: inherit;">Hands On Banking - Financial Training</span></a></li>
<li><a href="http://www.sba.gov/category/navigation-structure/counseling-training/online-small-business-training" style="background-color: white; color: #ae4e1e; line-height: 1.2; text-decoration: none;"><span style="font-family: inherit;">SBA Online Training</span></a></li>
<li><a href="http://www.sos.state.tx.us/corp/generalfaqs.shtml" style="background-color: white; color: #ae4e1e; line-height: 1.2; text-decoration: none;"><span style="font-family: inherit;">Secretary of State Site</span></a></li>
<li><a href="http://www.tarrantcounty.com/ecountyclerk/cwp/view.asp?A=735&amp;Q=435718" style="background-color: white; color: #ae4e1e; line-height: 1.2; text-decoration: none;"><span style="font-family: inherit;">Tarrant County Clerk (Fort Worth Area)</span></a></li>
<li><a href="https://ourcpa.cpa.state.tx.us/coa/Index.html" style="background-color: white; color: #ae4e1e; line-height: 1.2; text-decoration: none;"><span style="font-family: inherit;">Texas Comptroller</span></a></li>
<li><span style="background-color: white; color: #ae4e1e; font-family: inherit; line-height: 1.2; text-decoration: none;"><a href="http://www.ers.usda.gov/StateFacts/TX.htm" style="background-color: white; color: #ae4e1e; line-height: 1.2; text-decoration: none;">USDA Statistics</a></span></li>
</ul>
</ul>
</div>
</h4>
<h4>
<span style="font-family: inherit;">
Banking and Finances</span></h4>
<ul>
<li><span style="font-family: inherit;">Bank and Credit Unions in Texas, I can't name them all, but here are some.&nbsp;</span></li>
<ul>
<li><span style="font-family: inherit;">Banks</span></li>
<ul>
<li><span style="font-family: inherit;">Wells Fargo</span></li>
<li><span style="font-family: inherit;">JP Morgan Chase Bank</span></li>
<li><span style="font-family: inherit;">Bank of America</span></li>
<li><span style="font-family: inherit;">Capitol One Bank</span></li>
<li><span style="font-family: inherit;">Bank of Texas</span></li>
</ul>
<li><span style="font-family: inherit;">Credit Unions</span></li>
<ul>
<li><span style="font-family: inherit;">American Airlines Credit Union</span></li>
<li><span style="font-family: inherit;">DATCU Credit Union</span></li>
</ul>
</ul>
<li><span style="font-family: inherit;">Banking and Finance Education</span></li>
<ul>
<li><span style="font-family: inherit;"><a href="http://www.handsonbanking.org/" target="_blank">Hands on Banking </a>- Free Online Training for most financial topics and for most ages.</span></li>
<li><span style="font-family: inherit;"><a href="http://www.daveramsey.com/get-started/" target="_blank">Dave Ramsey</a> - Financial Peace and Total Money Makeover</span></li>
</ul>
</ul>
</div>
<h4>
<span style="font-family: inherit;">
Job Search:</span></h4>
<ul style="background-color: white; color: #5d5d5d; line-height: 1.2; margin: 0px; padding: 0px 0px 0px 1.25em;">
<ul>
<li><a href="http://www.indeed.com/jobs?indpubnum=4470538411044660" target="_blank"><span style="font-family: inherit;">Indeed</span></a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><span style="color: #ae4e1e; font-family: inherit; text-decoration: none;"><a href="http://www.workintexas.com/" style="color: #ae4e1e; text-decoration: none;">Work In Texas</a></span></li>
</ul>
</ul>
<h4>
<span style="font-family: inherit;">Restaurants and Food:</span></h4>
<ul style="background-color: white; color: #5d5d5d; line-height: 1.2; margin: 0px; padding: 0px 0px 0px 1.25em;">
<ul>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.urbanspoon.com/c/13/Dallas-restaurants.html" style="color: #ae4e1e; text-decoration: none;"><span style="font-family: inherit;">Urban Spoon</span></a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://lifeinwortworth.yelp.com/" target="_blank"><span style="font-family: inherit;">Yelp</span></a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><span style="color: #ae4e1e; font-family: inherit; text-decoration: none;"><a href="http://txliving.wordpress.com/2011/10/12/pizza-inn-fort-worth-alliance/" style="color: #ae4e1e; text-decoration: none;">Pizza Inn</a></span></li>
</ul>
</ul>
<h4>
<span style="font-family: inherit;">Food-Recipes</span></h4>
<ul>
<li><span style="font-family: inherit;"><a href="http://cpkathome.blogspot.com/2012/07/chicken-tequila-fettuccine.html" target="_blank">Copy Cat Recipes</a>, from your favorite restaurants.</span></li>
</ul>
<h4>
<span style="font-family: inherit;">
Attractions:</span></h4>
<ul style="background-color: white; color: #5d5d5d; line-height: 1.2; margin: 0px; padding: 0px 0px 0px 1.25em;">
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://hfalls.com/roanoke/" style="color: #ae4e1e; text-decoration: none;"><span style="font-family: inherit;">Hawaiian Falls Water Park (Roanoke)</span></a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.legolanddiscoverycenter.com/dallasfw/" style="color: #ae4e1e; text-decoration: none;"><span style="font-family: inherit;">Legoland Discovery Center, Grapevine</span></a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.nrh2o.com/" style="color: #ae4e1e; text-decoration: none;"><span style="font-family: inherit;">NRH2O Water Park (N Richland Hills)</span></a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.naturalbridgecaverns.com/" style="color: #ae4e1e; text-decoration: none;"><span style="font-family: inherit;">Natural Bridge Caverns</span></a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.sixflags.com/hurricaneharbortexas/index.aspx" style="color: #ae4e1e; text-decoration: none;"><span style="font-family: inherit;">Six Flags Hurricane Harbor Water Park (Arlington)</span></a></li>
<li style="margin: 0px; padding: 0.25em 0px;"><a href="http://www.sixflags.com/overtexas/index.aspx" style="color: #ae4e1e; text-decoration: none;"><span style="font-family: inherit;">Six Flags Over Texas</span></a></li>
</ul>
<br />
<h4>
<span style="font-family: inherit;">
Fun Book Recommendations
</span></h4>
<span style="font-family: inherit;"><br /></span>
<br />
<div style="text-align: left;">
<span style="font-family: inherit;"><br /></span></div>
<div style="text-align: left;">
<iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&amp;OneJS=1&amp;Operation=GetAdHtml&amp;MarketPlace=US&amp;source=ss&amp;ref=ss_til&amp;ad_type=product_link&amp;tracking_id=your0f4d-20&amp;marketplace=amazon&amp;region=US&amp;placement=158479903X&amp;asins=158479903X&amp;linkId=ZANRMU7RKKUR2QX3&amp;show_border=true&amp;link_opens_in_new_window=true" style="height: 240px; width: 120px;">&amp;amp;amp;amp;amp;amp;amp;lt;br&amp;amp;amp;amp;amp;amp;amp;gt;</iframe><span style="font-family: inherit;"><br /></span></div>
<div>
<div style="text-align: left;">
<span style="font-family: inherit;"><br /></span></div>
<div style="text-align: left;">
<iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&amp;OneJS=1&amp;Operation=GetAdHtml&amp;MarketPlace=US&amp;source=ss&amp;ref=ss_til&amp;ad_type=product_link&amp;tracking_id=your0f4d-20&amp;marketplace=amazon&amp;region=US&amp;placement=B00007AXGJ&amp;asins=B00007AXGJ&amp;linkId=RQXFPY2WNMYNV45V&amp;show_border=true&amp;link_opens_in_new_window=true" style="height: 240px; width: 120px;">
</iframe><span style="font-family: inherit;">
</span></div>
</div>
<div>
<div style="text-align: left;">
<span style="font-family: inherit;"><br /></span></div>
<div style="text-align: left;">
<iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&amp;OneJS=1&amp;Operation=GetAdHtml&amp;MarketPlace=US&amp;source=ss&amp;ref=ss_til&amp;ad_type=product_link&amp;tracking_id=your0f4d-20&amp;marketplace=amazon&amp;region=US&amp;placement=1596523174&amp;asins=1596523174&amp;linkId=JN54M6LN2BKMNZQ7&amp;show_border=true&amp;link_opens_in_new_window=true" style="height: 240px; width: 120px;">
</iframe><span style="font-family: inherit;">
</span></div>
</div>
<div style="text-align: left;">
<span style="font-family: inherit;"><br /></span></div>
<div style="text-align: left;">
<span style="font-family: inherit;"><br /></span></div>
<div style="text-align: left;">
<span style="font-family: inherit;">The End... Of this page...</span></div>
<span style="font-family: inherit;"><br /></span>
<br />
<div>
<br /></div>
