---
title: 'Local Resources'
date: '2017-04-12T07:03:00.0010000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Life In North Idaho'
blogger_status: 'LIVE'
blogger_page_id: '3481790518843896103'
blogger_filename: '/p/local-resources.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Life In North Idaho/feed.atom'
---

<br />
Whether you live here or you are just coming for a visit; Food, Fun, and Family are the three cornerstones to a enjoying your time in North Idaho.<br />
<br />
In addition, we've included facts about North Idaho to help you navigate some of the unique aspects of Idaho government, terrain, and culture.<br />
<br />
<br />
<h4>
Food</h4>
<a href="https://goo.gl/maps/yKQHWfMkKhD2" target="_blank">The Fedora</a> - fine dining food without the fine dining cost.<br />
<br />
<a href="https://goo.gl/maps/ciDCb9BpjF52" target="_blank">Gross Donuts</a> -<br />
<br />
<a href="https://goo.gl/maps/KXEozNPQPZr" target="_blank">Meltz Extreme Grilled Cheese</a> -<br />
<br />
<a href="https://goo.gl/maps/mmNSV1YvL172" target="_blank">Human Bean Coffee</a> -<br />
<br />
<h4>
Fun</h4>
<a href="https://goo.gl/maps/7uzvvuPVzH42" target="_blank">Coeur d'Alene, Idaho</a> is also known as Lake City or CDA. It is the heart of access to the lake and lake activities at the north end.<br />
<br />
Lake Coeur d'Alene -<br />
<br />
<a href="https://goo.gl/maps/MhUzDYDojZ62" target="_blank">Silverwood Theme Park</a> - Review Pending<br />
<br />
<a href="https://goo.gl/maps/fpVm2BVXW7G2" target="_blank">Post Falls, Idaho</a> is also known as River City as the entire city was built along the Spokane River which feeds into (or out from?) Lake Coeur d'Alene.<br />
<br />
<br />
<h4>
Family</h4>
<a href="https://goo.gl/maps/Wc3QnJbQNG82" target="_blank">Lake City Church (CDA)</a> -<br />
<br />
<a href="https://goo.gl/maps/jBDPT4tTi2v" target="_blank">Lake City Church (Rathdrum)(Office)</a> - Temporarily meeting at the&nbsp;<a href="https://goo.gl/maps/iw4ofEaQMP72" target="_blank">Kootenai Technical Education Campus</a>.<br />
<br />
<br />
<h4>
Facts</h4>
State Government Website<br />
CDA City Website<br />
<br />
<a href="https://goo.gl/maps/LZEUwbUQ5Vy" target="_blank">Coeur d'Alene Public Library</a><br />
<a href="https://goo.gl/maps/2bnZFjGvqes" target="_blank">Coeur d'Alene City Hall</a><br />
<a href="https://goo.gl/maps/N31ch2LMxAw" target="_blank">PARKING IN DOWNTOWN CDA (Diamon Parking)</a> - The Diamond Parking lot (paid) is the best place to park if you are visiting downtown CDA without staying at the resort.<br />
<br />
Drivers Licence<br />
Car Registration<br />
Boat Registration<br />
Hunters Licence<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />