---
title: 'START HERE | About'
date: '2017-04-12T07:05:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'Life In North Idaho'
blogger_status: 'LIVE'
blogger_page_id: '7931751860170703008'
blogger_filename: '/p/start-here-about.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Life In North Idaho/feed.atom'
---

About Life In North Idaho / Start Here<br />
<br />
We just moved to Coeur d'Alene (North Idaho) from Fort Worth (North Texas). A new area can be confusing so I'm setting this site up as a one-stop shop for links and important information around town. I hope you benefit from this content as well.<br />
<br />
Also, if you need information and you can't find it. Let me know. Research is a speciality of mine and I'd love to help you out and add that content to this site.<br />
<br />
See you around town,<br />
<br />
Darrell<br />
<br />
<br />
---- TBC ----<br />
<br />
Compelling Tag Line Statement (Make Me Care.)<br />
Supporting Statement showing your value proposition (What’s In It for me?).<br />
**Pictures would be helpful, anything that gives your reader the “feeling” you want them to have. Customer’s buy products based on perceived benefits and how that product makes them feel. Pictures convey more than words.**<br />
Pain / Pleasure Statement:<br />
•<span class="Apple-tab-span" style="white-space: pre;"> </span>What’s the theme that runs through all your readers? Who are your clients?<br />
•<span class="Apple-tab-span" style="white-space: pre;"> </span>What do my clients want to avoid? What is their pain point?<br />
•<span class="Apple-tab-span" style="white-space: pre;"> </span>What would my clients want to have or aspire to? What do they want most?<br />
•<span class="Apple-tab-span" style="white-space: pre;"> </span>An explanation should be benefit-oriented. Explanations are functional, but functionality should be tilted in favor of the user. For example, “We make websites” is a functional explanation, but it lacks the user-focused orientation. To make this explanation even more compelling, you could angle it towards the user to show them the value: “Get a website that makes you money.”<br />
<br />
Who are you and why am I here?<br />
•<span class="Apple-tab-span" style="white-space: pre;"> </span>Who are you? Who started your company?<br />
•<span class="Apple-tab-span" style="white-space: pre;"> </span>What does your company do? What do you sell?<br />
•<span class="Apple-tab-span" style="white-space: pre;"> </span>Where is your company headquartered? Do you have offices elsewhere? Or, where does your company provide services?<br />
•<span class="Apple-tab-span" style="white-space: pre;"> </span>When did you start your company? What hours is your business open?<br />
•<span class="Apple-tab-span" style="white-space: pre;"> </span>Why did your company start? What's your company's mission?<br />
•<span class="Apple-tab-span" style="white-space: pre;"> </span>How does your company help people? How does your product work?<br />
<br />
Services Offered<br />
List of Services with brief explanations.<br />
•<span class="Apple-tab-span" style="white-space: pre;"> </span>S<br />
•<span class="Apple-tab-span" style="white-space: pre;"> </span>S<br />
•<span class="Apple-tab-span" style="white-space: pre;"> </span>S<br />
•<span class="Apple-tab-span" style="white-space: pre;"> </span>s<br />
<br />
Trust / Testimonials / Social Proof<br />
This is the area we will tell the user about what you’ve done for others (in their own words if possible).<br />
<br />
Guarantees (if any):<br />
What types of Guarantees or Money Back items do you offer?<br />
<br />
Call To Action<br />
Do THIS next! (A button would be nice here. Button links to either an email sign up form or just opens an email.).<br />
<br />
Examples: Sign up for email, free giveaway, contact us, buy now…. Etc.<br />
<br />
Contact Information / Next Steps<br />
We offer several convenient ways to contact us:<br />
First Last, Title<br />
555-555-5555<br />
123 Main St. Somewhere, ST 55555<br />
Email me at Me@email.com<br />
www.myaddress.com<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />