---
title: 'Start Here: Let''s Talk About Sex!'
date: '2020-09-01T23:00:00.0000000+00:00'
draft: true
blogger_type: 'PAGE'
blogger_blog: 'The Dirty Pastor'
blogger_status: 'LIVE'
blogger_page_id: '238374608232330062'
blogger_filename: '/p/start-here-lets-talk-about-sex.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/The Dirty Pastor/feed.atom'
---

<h3 style="text-align: left;">Sex. Christianity. Education.&nbsp;</h3><div><br /></div><h3 style="text-align: left;">SEX! It's what's for dinner! And breakfast... lunch... late night snack.&nbsp;</h3><div><br /></div><h4 style="text-align: left;">Sex is God's idea and he fully endorses it.&nbsp;</h4><div><ul style="text-align: left;"><li>If you are struggling in your sexuality, frustrated with the level of intimacy you experience with your partner, or secretly battling sexual addiction or trauma wounds... you've come to the right place.&nbsp;</li></ul><ul style="text-align: left;"><li>I help Christians explore the fullness of what God designed sex to be, heal from past sexual trauma or misunderstandings about sex, and become more fully integrated into their whole sexual experience, spirit, soul, body, and mind.&nbsp;</li></ul></div><div><br /></div><div>Thanks for listening,&nbsp;</div><div><br /></div><div>The Dirty Pastor, Sex. Christianity. Education.&nbsp;</div><div><br /></div><h4 style="text-align: left;">History of Sexuality and Christianity</h4><div><br /></div><div>When I say Sex is God's idea and he fully endorses it, does that make you cringe? If so, you probably have experience in the "church". Christian Religious circles, in particular, have been treating the topic of SEX as though it was tabboo, forbidden, and dirty for over 100 years.&nbsp;</div><div><br /></div><div>Though not exclusive to the late 1800's, the <a href="https://historyofsexuality.umwblogs.org/pre-20th-century/victorian-era-2/" target="_blank">Victorian Era</a>, initiated in large part due to the <a href="https://www.history.com/topics/colonial-america/puritanism" target="_blank">Puritan Movement</a>,&nbsp;popularized the idea that Men were lustful creatures and sex should be given to them begrudgingly. Women were encouraged to suppress their sex drives to the point that many doctor's believed they had none, and women displaying a desire for sex were treated as ill, even having their sex organs removed.&nbsp;</div><div><br /></div><div><b>FUN FACT:</b> Interestingly, The <a href="https://classroom.synonym.com/puritans-marriage-religion-12086280.html" target="_blank">Puritans</a> themselves did not hold such a view, but the drive for purity took on a societal life of its own. In fact, Puritans viewed sex as holy and the man was considered to have an obligation to pleasure his wife. His impotency was considered grounds for divorce because he could not fulfill this function.</div><div><br /></div><div><br /></div><h4 style="text-align: left;">The Turnaround: Let's Talk About Sex</h4><div><br /></div><div>The <a href="https://en.wikipedia.org/wiki/Sexual_revolution" target="_blank">Sexual Revolution</a> of the 1960's-1980's initiated a new era in our ability to talk about sex. Although not entirely positive, the movement broke the barriers held to so firmly by Christians in North America, and allowed unprecedented access to discuss the physical, emotional, and social boundaries around sex.&nbsp;</div><div><br /></div><div>The saying "bring it to the light so it gets handled right" applies here. While sex was considered a dirty, dark, and secret thing mentioned only in whispers, marriages fell apart, needs went unspoken and unmet, and couples were left without the tools to succeed. As a result, men and women turned to any resource they could find to scratch the God-Given itch they were biologically designed to scratch. Since The Church was largely silent, people turned to The World, Pornography, and other secular psychology materials to educate or indulge.&nbsp;</div><div><br /></div><div>Anecdotally, Hotel staff often cite that Pastor's Conferences bring the largest influx of pay-per-view Pornography revenue each year. Emphasizing the need to bring these discussion into the forefront. Pastor's fall from pulpits due to infidelity on a regular basis, and this is in large part because they are among the most ostracized for discussing their needs and problems in this area.&nbsp;</div><div><br /></div><h4 style="text-align: left;">God's Moving in Your Sex Life</h4><div><br /></div><div><div>It's long past time to begin treating this Sexual Epidemic as an opportunity to bring healing and health to marriages, not as an area of "sin" to be shunned and swept away from polite conversation.&nbsp;</div><div><br /></div></div><div>Luckily for you and I, the winds of change have been blowing in the church for some time. Healthier churches are opening up discussions for sex within marriages conferences, books have been published, and a few great podcasts are paving the way for more honest and detailed discussions.&nbsp;</div><div><br /></div><div>Two very good ones, <a href="https://oneextraordinarymarriage.com/one-extraordinary-marriage-show/" target="_blank">One Extraordinary Marriage (OEM)</a> produces shows such as "614: WHAT YOU DON’T KNOW ABOUT YOUR SPOUSE’S ORGASM". While <a href="https://fiercemarriage.com/podcast" target="_blank">The Fierce Marriage</a> podcast discusses hard topics like "Rebuilding Trust After Betrayal" and "Surviving Infidelity".&nbsp;</div><div><br /></div><div>In the spirit of <a href="https://en.wikipedia.org/wiki/Ruth_Westheimer" target="_blank">Dr Ruth</a>, I have decided to add my voice to this topic. This decision came at the encouragement of several friends who have benefited from my brutally open and honest discussion of the topics of sex, sexuality, sexual techniques and positions, sexual history, sexual trauma and healing, and more.</div><div><br /></div><div>If you have questions, feel free to email <a href="mailto:Me@DarrellWolfe.com">Me@DarrellWolfe.com</a> and I will attempt to include them in a future blog post or podcast episode, private details excluded of course.&nbsp;</div><div><br /></div><div><div>Thanks for listening,&nbsp;</div><div><br /></div><div>The Dirty Pastor, Sex. Christianity. Education.&nbsp;</div></div>