---
title: 'First Time - Bike with no training wheels.'
date: '2011-04-19T14:20:00.0000000+00:00'
draft: true
blogger_blog: 'Connor David Wolfe - Journal'
blogger_status: 'LIVE'
blogger_post_id: '2941604729260166122'
blogger_filename: '/2011/04/first-time-bike-with-no-training-wheels.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Connor David Wolfe - Journal/feed.atom'
---

&nbsp;Connorbot,<br />
<br />
You also learned to ride your bike without training wheels this last week. That was an event. I should tell you about it. I took you and Preston to the park near the pool. I would run with you just behind with my hand on the bottom of your seat. You didn't need that you were fine from the first time your tried. You insisted I needed to be there and so I put the tips of my fingers on your lower back, but didn't hold you up at all. You didn't need me, I even ran along with my hand behind but not touching you and you didn't notice the difference. You were riding on your own. But everytime I would back off you would immediately drive into the grass saying that you could not ride without me there. It was 100% mental because you WERE riding without my assistance already, but you couldn't comprehend that then. It was frustrating as I was out of shape and my chest hurt running that much. But it was an experience I would not give up for anything. <br />
<br />
You didn't actually get off a long run without me until of all things Preston got his knee skinned. Of the two I would expect the one with the training wheels to be the one not to get hurt. I half expected you to get a few bumps because you would be falling your first few times without the wheels. But no, Preston did. I then had to deal with him and you were very upset. However, Since I had him and his bike to carry I could run behind you. I would put them down and push you with one big shove and then pick them up, amazingly you could now instantly ride for over 100 feet before taking off into the grass. All you needed was my unavailability? Two days later we went out again and you took off down the street to the round about down the road where they had not yet built houses. <br />
<br />
You were riding in circles and figure eights within a few minutes. You even learned to skid to a stop and start by yourself without my pushing you. Within two trips out your an expert biker. I told you that as soon as you get better and balancing I'll take you out on the dirt path. That won't be long I can assure you. You potty trained yourself before three I'm sure you that you will fine on a dirt path in no time. I love you Son. You are a very, very unique and cool kid. I'm glad I got to be your Dad. <br />
<br />
Dad