---
title: 'Growing in Desire'
date: '2011-04-19T14:08:00.0000000+00:00'
draft: true
blogger_blog: 'Connor David Wolfe - Journal'
blogger_status: 'LIVE'
blogger_post_id: '6501614768320500844'
blogger_filename: '/2011/04/growing-in-desire.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Connor David Wolfe - Journal/feed.atom'
---

Connorbot,<br />
<br />
This morning I got up late and sat on the couch and you came and sat next to me with your hand held leapster explorer. You wanted to show me your new Toy Story 3 game. You picked two players and I wished I had time to play it with you. I got up to go get dressed and you gently but firmly placed your arm over my belly and put your hand on my opposite leg. It was a non-verbal "You aren't going anywhere." Usually you would whine or throw a fit if anything, but today you just put your arm out as a silent, nope! Then to seal that non verbal cue you got up in my lap, never taking your eyes off of your game. <br />
<br />
I sat there for a few minutes and helped you out and told you that I had to get dressed and you let me up. It was very cute! I am so proud of you. You are getting bigger and more mature. I don't always deal kindly with your outbursts, but you aren't much different than I am. I suppose if I calm down you will calm down. If the Lord delays long enough, which I don't think He will, I look forward to seeing you with my Grandkids. You'll have a much better start than I did.