---
title: 'First Love. First Heart Break'
date: '2020-12-07T07:16:00.0020000+00:00'
draft: true
blogger_blog: 'Connor David Wolfe - Journal'
blogger_status: 'LIVE'
blogger_post_id: '6436178485865238914'
blogger_filename: '/2020/12/first-love-first-heart-break.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Connor David Wolfe - Journal/feed.atom'
---

<p>&nbsp;Connor. I'm so sorry. You lost your mom and now you're having your first heart break. But you're handling it well and growing into an impressive man.</p><p>I always intended to write in here more, apparently I did not. Maybe I can try to be in here more often now.&nbsp;</p><p>It's hard to see today, but this will be the weight room for your heart. You'll grow through this experience in ways you can't comprehend today.</p><p>I'm right here, watching, helplessly. I wish I could fix it for you. But you're a man now. Becoming a great man. I'm proud of you. I love you.&nbsp;</p><p>Keep coming to me, and to your real Father in heaven. He's given you to me for a season, and over the next few years I'll be handing you back to him a bit at a time.&nbsp;</p><p>One day, you'll have your own house. You'll do things, make decisions, you'll make mistakes. That's okay. Failure is always an option, just fail forward. Let it teach you. Let it help you grow.&nbsp;</p><p>I'm so proud of you.&nbsp;</p><p>Darrell, Daddy, Wolfe</p><p><br /></p><p><br /></p><p><br /></p>