---
title: 'My Preston'
date: '2011-04-19T18:11:00.0000000+00:00'
draft: true
blogger_blog: 'Preston Markus Wolfe - Journal'
blogger_status: 'LIVE'
blogger_post_id: '4206626855797756050'
blogger_filename: '/2011/04/my-preston.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Preston Markus Wolfe - Journal/feed.atom'
---

Preston, son... be not slow to act. I thought you were the easy one at first. Because you were quiet. You got a bike for Christmas. You sat on it and said that it was too hard to push the pedals, so you just sat on it mad that we wouldn't push you. ha ha. Then you finally realized we weren't going to pedal for you and you started to learn. Now you ride down the street with amazing speed for your size. You also delay potty training. You just refuse, you could, but you have refused to go anywhere but your pull up. Mommy finally took off your pull up and forced you to run around naked until you used the potty. <br />
<br />
You are starting to get it. In the last few days you've gone #2 in the potty all by yourself twice. I'm relieved, but motivating you has been very hard. <br />
<br />
I think that your greatest self governing task will be motivating yourself, or just deciding to do something whether you feel motivated or not. Keep that in check and the sky is the limit for you. You have a covenant with God and based on your obedience to that coveneant you are empowered to prosper with good success! I love you Preston. Dad.