---
title: 'Meningococcal B VIS via CDC Website'
date: '2020-06-10T18:47:00.0020000+00:00'
draft: true
blogger_blog: 'To Vacs or not to Vacs, that is the question.'
blogger_status: 'LIVE'
blogger_post_id: '6739112322567806577'
blogger_filename: '/2020/06/meningococcal-b-vis-via-cdc-website.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/To Vacs or not to Vacs, that is the question./feed.atom'
---

<div><a href="https://www.cdc.gov/vaccines/hcp/vis/vis-statements/mening-serogroup.html" target="_blank">Meningococcal B VIS</a></div><div><br /></div><div><div class="card-header h4 bg-tertiary" style="background-color: rgb(206, 236, 231) !important; border-bottom: 1px solid rgba(0, 0, 0, 0.125); box-sizing: border-box; font-family: &quot;Open Sans&quot;, apple-system, blinkmacsystemfont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, arial, sans-serif; font-size: 1.375rem; line-height: 1.3; margin-bottom: 0px; margin-top: 0px; padding: 0.5rem 1rem;">Why get vaccinated?</div><div class="card-body " style="box-sizing: border-box; flex: 1 1 auto; font-family: &quot;Open Sans&quot;, apple-system, blinkmacsystemfont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, arial, sans-serif; font-size: 17px; min-height: 1px; padding: 1rem;"><p style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px;"><span style="box-sizing: border-box; font-weight: bolder;">Meningococcal B vaccine</span>&nbsp;can help protect against&nbsp;<span style="box-sizing: border-box; font-weight: bolder;">meningococcal disease</span>&nbsp;caused by serogroup B.&nbsp; A different meningococcal vaccine is available that can help protect against serogroups A, C, W, and Y.</p><p style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px;"><span style="box-sizing: border-box; font-weight: bolder;">Meningococcal disease</span>&nbsp;can cause meningitis (infection of the lining of the brain and spinal cord) and infections of the blood. Even when it is treated, meningococcal disease kills 10 to 15 infected people out of 100. And of those who survive, about 10 to 20 out of every 100 will suffer disabilities such as hearing loss, brain damage, kidney damage, loss of limbs, nervous system problems, or severe scars from skin grafts.</p><p style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px;"><span style="background-color: #f7cb4d;">Anyone can get meningococcal disease but certain people are at increased risk, including:</span></p><ul style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px; padding-left: 25px;"><li style="box-sizing: border-box; margin-bottom: 0.4rem;"><span style="background-color: #f7cb4d;">Infants younger than one year old</span></li><li style="box-sizing: border-box; margin-bottom: 0.4rem;"><span style="background-color: #f7cb4d;">Adolescents and young adults 16 through 23 years old</span></li><li style="box-sizing: border-box; margin-bottom: 0.4rem;"><span style="background-color: #f7cb4d;">People with certain medical conditions that affect the immune system</span></li><li style="box-sizing: border-box; margin-bottom: 0.4rem;"><span style="background-color: #f7cb4d;">Microbiologists who routinely work with isolates of&nbsp;<em style="box-sizing: border-box;">N.&nbsp;meningitidis,</em>&nbsp;the bacteria that cause meningococcal disease</span></li><li style="box-sizing: border-box; margin-bottom: 0.4rem;"><span style="background-color: #f7cb4d;">People at risk because of an outbreak in their community</span></li></ul><div><br /></div><div><div class="card mb-3" style="background-clip: border-box; background-color: white; border-radius: 0.25rem; border: 1px solid rgb(224, 224, 224); box-sizing: border-box; display: flex; flex-direction: column; margin-bottom: 1rem !important; min-width: 0px; overflow-wrap: break-word; position: relative;"><div class="card-header h4 bg-tertiary" style="background-color: rgb(206, 236, 231) !important; border-bottom: 1px solid rgba(0, 0, 0, 0.125); box-sizing: border-box; font-size: 1.375rem; line-height: 1.3; margin-bottom: 0px; margin-top: 0px; padding: 0.5rem 1rem;">Talk with your health care provider</div><div class="card-body " style="box-sizing: border-box; flex: 1 1 auto; min-height: 1px; padding: 1rem;"><div style="box-sizing: border-box;"><div class="card border-0" style="background-clip: border-box; background-color: transparent !important; border-radius: 0.25rem; border: none; box-sizing: border-box; display: flex; flex-direction: column; height: auto; min-width: 0px; overflow-wrap: break-word; position: relative;"><div class="card-body bg-white" style="background-attachment: initial !important; background-clip: initial !important; background-image: initial !important; background-origin: initial !important; background-position: initial !important; background-repeat: initial !important; background-size: initial !important; box-sizing: border-box; flex: 1 1 auto; min-height: 1px; padding: 1rem;"><p style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px;">Tell your vaccine provider if the person getting the vaccine:</p><ul style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px; padding-left: 25px;"><li style="box-sizing: border-box; margin-bottom: 0.4rem;">Has had an&nbsp;<span style="box-sizing: border-box; font-weight: bolder;">allergic reaction after a previous dose of meningococcal B vaccine</span>, or has any&nbsp;<span style="box-sizing: border-box; font-weight: bolder;">severe, life-threatening allergies.</span></li><li style="box-sizing: border-box; margin-bottom: 0.4rem;">Is<span style="box-sizing: border-box; font-weight: bolder;">&nbsp;pregnant or breastfeeding.</span></li></ul><p style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px;">In some cases, your health care provider may decide to postpone meningococcal B vaccination to a future visit.</p><p style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px;">People with minor illnesses, such as a cold, may be vaccinated. People who are moderately or severely ill should usually wait until they recover before getting meningococcal B vaccine.</p><p style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;">Your health care provider can give you more information.</p></div></div></div></div></div><div class="card " style="background-clip: border-box; border-radius: 0.25rem; border: 1px solid rgb(224, 224, 224); box-sizing: border-box; display: flex; flex-direction: column; min-width: 0px; overflow-wrap: break-word; position: relative;"><a class="onThisPageAnchor" id="risks" name="Risks%20of%20a%20vaccine%20reaction" style="background-color: transparent; box-sizing: border-box; color: inherit;" title="Risks of a vaccine reaction"></a><div class="card-header h4 bg-tertiary" style="background-color: rgb(206, 236, 231) !important; border-bottom: 1px solid rgba(0, 0, 0, 0.125); box-sizing: border-box; font-size: 1.375rem; line-height: 1.3; margin-bottom: 0px; margin-top: 0px; padding: 0.5rem 1rem;">Risks of a vaccine reaction</div><div class="card-body " style="box-sizing: border-box; flex: 1 1 auto; min-height: 1px; padding: 1rem;"><div style="box-sizing: border-box;"><div class="card border-0" style="background-clip: border-box; border-radius: 0.25rem; border: none; box-sizing: border-box; display: flex; flex-direction: column; height: auto; min-width: 0px; overflow-wrap: break-word; position: relative;"><div class="card-body bg-white" style="background-attachment: initial !important; background-clip: initial !important; background-image: initial !important; background-origin: initial !important; background-position: initial !important; background-repeat: initial !important; background-size: initial !important; box-sizing: border-box; flex: 1 1 auto; min-height: 1px; padding: 1rem;"><ul style="background-color: transparent !important; box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px; padding-left: 25px;"><li style="box-sizing: border-box; margin-bottom: 0.4rem;">Soreness, redness, or swelling where the shot is given, tiredness, fatigue, headache, muscle or joint pain, fever, chills, nausea, or diarrhea can happen after meningococcal B vaccine. Some of these reactions occur in more than half of the people who receive the vaccine.</li></ul><p style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px;"><b style="background-color: #f7cb4d;">People sometimes faint after medical procedures, including vaccination. Tell your provider if you feel dizzy or have vision changes or ringing in the ears.</b></p><p style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;"><b style="background-color: #f7cb4d;">As with any medicine, there is a very remote chance of a vaccine causing a severe allergic reaction, other serious injury, or death.</b></p><p style="background-color: transparent !important; box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;"><br /></p><p style="background-color: transparent !important; box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;"><br /></p><p style="background-color: transparent !important; box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;"><br /></p><p style="background-color: transparent !important; box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;"><br /></p><p style="background-color: transparent !important; box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;"><br /></p></div></div></div></div></div></div></div></div>