---
title: 'DTaP (Diphtheria, Tetanus, Pertussis) VIS via CDC Wesbites'
date: '2020-06-10T18:44:00.0010000+00:00'
draft: true
blogger_blog: 'To Vacs or not to Vacs, that is the question.'
blogger_status: 'LIVE'
blogger_post_id: '3868901553339484432'
blogger_filename: '/2020/06/dtap-diphtheria-tetanus-pertussis-vis.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/To Vacs or not to Vacs, that is the question./feed.atom'
---

<br /><div><div><a href="https://www.cdc.gov/vaccines/hcp/vis/vis-statements/dtap.html" target="_blank">DTaP (Diphtheria, Tetanus, Pertussis) VIS</a></div></div><div><br /></div><div><div class="card-header h4 bg-tertiary" style="background-color: #ceece7; border-bottom: 1px solid rgba(0, 0, 0, 0.125); box-sizing: border-box; font-family: &quot;Open Sans&quot;, apple-system, blinkmacsystemfont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, arial, sans-serif; font-size: 1.375rem; line-height: 1.3; margin-bottom: 0px; margin-top: 0px; padding: 0.5rem 1rem;">Why get vaccinated?</div><div class="card-body" style="box-sizing: border-box; flex: 1 1 auto; font-family: &quot;Open Sans&quot;, apple-system, blinkmacsystemfont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, arial, sans-serif; font-size: 17px; min-height: 1px; padding: 1rem;"><p style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px;"><span style="box-sizing: border-box; font-weight: bolder;">DTaP vaccine</span>&nbsp;can prevent&nbsp;<span style="box-sizing: border-box; font-weight: bolder;">diphtheria</span>,&nbsp;<span style="box-sizing: border-box; font-weight: bolder;">tetanus</span>, and&nbsp;<span style="box-sizing: border-box; font-weight: bolder;">pertussis</span>.</p><p style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px;">Diphtheria and pertussis spread from person to person. Tetanus enters the body through cuts or wounds.</p><ul style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px; padding-left: 25px;"><li style="box-sizing: border-box; margin-bottom: 0.4rem;">DIPHTHERIA (D) can lead to difficulty breathing, heart failure, paralysis, or death.</li><li style="box-sizing: border-box; margin-bottom: 0.4rem;">TETANUS (T) causes painful stiffening of the muscles. Tetanus can lead to serious health problems, including being unable to open the mouth, having trouble swallowing and breathing, or death.</li><li style="box-sizing: border-box; margin-bottom: 0.4rem;">PERTUSSIS (aP), also known as “whooping cough,” can cause uncontrollable, violent coughing which makes it hard to breathe, eat, or drink. Pertussis can be extremely serious in babies and young children, causing pneumonia, convulsions, brain damage, or death. In teens and adults, it can cause weight loss, loss of bladder control, passing out, and rib fractures from severe coughing.</li></ul><div><div class="card mb-3" style="background-clip: border-box; background-color: white; border-radius: 0.25rem; border: 1px solid rgb(224, 224, 224); box-sizing: border-box; display: flex; flex-direction: column; margin-bottom: 1rem; min-width: 0px; overflow-wrap: break-word; position: relative;"><div class="card-header h4 bg-tertiary" style="background-color: #ceece7; border-bottom: 1px solid rgba(0, 0, 0, 0.125); box-sizing: border-box; font-size: 1.375rem; line-height: 1.3; margin-bottom: 0px; margin-top: 0px; padding: 0.5rem 1rem;">Talk with your health care provider</div><div class="card-body" style="box-sizing: border-box; flex: 1 1 auto; min-height: 1px; padding: 1rem;"><div style="box-sizing: border-box;"><div class="card border-0" style="background-clip: border-box; background-color: transparent; border-radius: 0.25rem; border: none; box-sizing: border-box; display: flex; flex-direction: column; height: auto; min-width: 0px; overflow-wrap: break-word; position: relative;"><div class="card-body bg-white" style="background-attachment: initial !important; background-clip: initial !important; background-image: initial !important; background-origin: initial !important; background-position: initial !important; background-repeat: initial !important; background-size: initial !important; box-sizing: border-box; flex: 1 1 auto; min-height: 1px; padding: 1rem;"><p style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px;">Tell your vaccine provider if the person getting the vaccine:</p><ul style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px; padding-left: 25px;"><li style="box-sizing: border-box; margin-bottom: 0.4rem;">Has had an&nbsp;<span style="box-sizing: border-box; font-weight: bolder;">allergic reaction after a previous dose of any</span><span style="box-sizing: border-box; font-weight: bolder;">&nbsp;vaccine that protects against tetanus, diphtheria, or pertussis</span>, or has any&nbsp;<span style="box-sizing: border-box; font-weight: bolder;">severe, life-threatening allergies</span>.</li><li style="box-sizing: border-box; margin-bottom: 0.4rem;">Has had&nbsp;<span style="box-sizing: border-box; font-weight: bolder;">a coma, decreased level of consciousness, or prolonged seizures within 7 days after a previous dose of any pertussis vaccine (DTP or DTaP).</span></li><li style="box-sizing: border-box; margin-bottom: 0.4rem;">Has&nbsp;<span style="box-sizing: border-box; font-weight: bolder;">seizures or another nervous system problem</span>.</li><li style="box-sizing: border-box; margin-bottom: 0.4rem;">Has ever had&nbsp;<span style="box-sizing: border-box; font-weight: bolder;">Guillain-Barré Syndrome</span>&nbsp;(also called GBS).</li><li style="box-sizing: border-box; margin-bottom: 0.4rem;">Has had&nbsp;<span style="box-sizing: border-box; font-weight: bolder;">severe pain or swelling after a previous dose</span>&nbsp;<span style="box-sizing: border-box; font-weight: bolder;">of any vaccine that protects against tetanus or diphtheria.</span></li></ul><p style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px;">In some cases, your child’s health care provider may decide to postpone DTaP vaccination to a future visit.</p><p style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px;">Children with minor illnesses, such as a cold, may be vaccinated. Children who are moderately or severely ill should usually wait until they recover before getting DTaP.</p><p style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;">Your child’s health care provider can give you more information.</p></div></div></div></div></div><div class="card mb-3" style="background-clip: border-box; border-radius: 0.25rem; border: 1px solid rgb(224, 224, 224); box-sizing: border-box; display: flex; flex-direction: column; margin-bottom: 1rem; min-width: 0px; overflow-wrap: break-word; position: relative;"><a class="onThisPageAnchor" id="risks" name="Risks%20of%20a%20vaccine%20reaction" style="background-color: transparent; box-sizing: border-box; color: inherit;" title="Risks of a vaccine reaction"></a><div class="card-header h4 bg-tertiary" style="background-color: #ceece7; border-bottom: 1px solid rgba(0, 0, 0, 0.125); box-sizing: border-box; font-size: 1.375rem; line-height: 1.3; margin-bottom: 0px; margin-top: 0px; padding: 0.5rem 1rem;">Risks of a vaccine reaction</div><div class="card-body" style="box-sizing: border-box; flex: 1 1 auto; min-height: 1px; padding: 1rem;"><div style="box-sizing: border-box;"><div class="card border-0" style="background-clip: border-box; border-radius: 0.25rem; border: none; box-sizing: border-box; display: flex; flex-direction: column; height: auto; min-width: 0px; overflow-wrap: break-word; position: relative;"><div class="card-body bg-white" style="background-attachment: initial !important; background-clip: initial !important; background-image: initial !important; background-origin: initial !important; background-position: initial !important; background-repeat: initial !important; background-size: initial !important; box-sizing: border-box; flex: 1 1 auto; min-height: 1px; padding: 1rem;"><ul style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px; padding-left: 25px;"><li style="background-color: transparent; box-sizing: border-box; margin-bottom: 0.4rem;">Soreness or swelling where the shot was given, fever, fussiness, feeling tired, loss of appetite, and vomiting sometimes happen after DTaP vaccination.</li><li style="background-color: transparent; box-sizing: border-box; margin-bottom: 0.4rem;">More serious reactions, such as seizures, non-stop crying for 3 hours or more, or high fever (over 105°F) after DTaP vaccination happen much less often. Rarely, the vaccine is followed by swelling of the entire arm or leg, especially in older children when they receive their fourth or fifth dose.</li><li style="box-sizing: border-box; margin-bottom: 0.4rem;"><b style="background-color: #f7cb4d;">Very rarely, long-term seizures, coma, lowered consciousness, or permanent brain damage may happen after DTaP vaccination.</b></li></ul><p style="background-color: transparent; box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;">As with any medicine, there is a very remote chance of a vaccine causing a severe allergic reaction, other serious injury, or death.</p></div></div></div></div></div></div></div></div>