---
title: 'Where''s my tribe?'
date: '2021-06-14T17:13:00.0010000+00:00'
draft: true
blogger_blog: 'Eleutheria  | Freedom Theology'
blogger_status: 'LIVE'
blogger_post_id: '4499356750542709834'
blogger_filename: '/2021/06/wheres-my-tribe.html'
blogger_source: 'takeout-20260223T235336Z-3-001.zip:Takeout/Blogger/Blogs/Eleutheria  _ Freedom Theology /feed.atom'
categories:
  - 'Musings'
---

I'm a xxxxxxx?&nbsp;<div><br></div><div>One of the hard parts of deconstruction and reconstruction, is a lack of label and identity.</div><div><br></div><div>My identity, ultimately, is found in God and His Word. I am a child of YHWH, follower of The Way, first called Christian at Antioch, citizen of The Kingdom of God, blood bought, spirit filled, believer, adopted brother of Jesus, adopted son of God....&nbsp;</div><div><br></div><div>But when it comes to a group of fellow traveler's... there is no movement or "group" that fits.</div><div><br></div><div>I'm not Liberal but I'm definitely post-conservative.</div><div><br></div><div>I'm Christian, but I reject much of western American Christianity.</div><div><br></div><div>I'm spirit filled, and believe in the healthy expression of all God's spiritual gifts; but, I reject Pentecostal, Charismatic, and Word of Faith expressions and definitions of those terms.&nbsp;</div><div><br></div><div>If I had to gather a group of like minded mentors, I'd appeal to Drs Michael S. Heiser , N. T. Wright , Tim Mackie and the BibleProject, Bob Hamp , John Walton and his work on Genesis, and a few others that are slipping my mind at the moment... With a scatter shot of Phil Vischer and Skye Jethani ...&nbsp;</div><div><br></div><div>So what tribe do I bring to? The scholar tribe? The thinker tribe? Hm...&nbsp;</div><div><br></div><div>I guess I'll keep growing and find out.</div><div><br></div><div></div><div><br></div><div><br></div>